### ISSUE TITLE
Issues with llama-2-7b-f

### ISSUE THREAD

**Issue by maggarwal25** [langchain-ai/langchain#10012]
### System Info

latest versions for python and langchain

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

I used the demo code to run Sagemaker using Langchain for llama-2-7b-f

However, I'm getting the following issues:

```
ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
 "code":424,
 "message":"prediction failure",
 "error":"string indices must be integers"
}
```

This is what is shown from AWS Logs:
`[INFO ] PyProcess - W-80-model-stdout: [1,0]<stdout>:TypeError: string indices must be integers`

How do I resolve this

### Expected behavior

Shown:

```
ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
 "code":424,
 "message":"prediction failure",
 "error":"string indices must be integers"
}
```

**Comment by maggarwal25** [comment]
@dosu-bot

The issue is that the "string indices must be indices", but your transformation does not deal with that. Here is the curretn code, please see below and change to avoid this error:

```from langchain.docstore.document import Document
from typing import Dict
from langchain import PromptTemplate, SagemakerEndpoint
from langchain.llms.sagemaker_endpoint import LLMContentHandler
from langchain.chains.question_answering import load_qa_chain
import json

example_doc_1 = """
string
"""

docs = [
    Document(
        page_content=example_doc_1,
    )
]

query = """
prompt
"""

prompt_template = """Use the following pieces of context to answer the question at the end.

{context}

Question: {question}
Answer:"""
PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

class ContentHandler(LLMContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        input_dict = {"inputs": prompt, "parameters": model_kwargs}
        return json.dumps(input_dict).encode('utf-8')

    def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        print("output: ", response_json[0])
        return response_json[0]["generation"]

content_handler = ContentHandler()

chain = load_qa_chain(
    llm=SagemakerEndpoint(
        endpoint_name="endpointname",
        credentials_profile_name="profilename",
        region_name="us-east-1",
        model_kwargs={"temperature": 1e-10, "max_length":500},
        endpoint_kwargs={"CustomAttributes": "accept_eula=true"},
        content_handler=content_handler,
    ),
    prompt=PROMPT,
)

chain({"input_documents": docs, "question": query}, return_only_outputs=True)```

**Comment by physiii** [comment]
We are having this issue to. llama-2 works but llama-2 chat does not which is one of the most popular models.

This should be on your automated testing so you know when the integration breaks.

Discussing with AWS and this and other issues are why people are moving away from langchain to just writing the integrations themselves.

Trying to hold on but seems like everyday we are dealing with langchain issues instead of building the app.

**Comment by amizlish** [comment]
@maggarwal25 
try changing the Content handler as follows:


 ```
 def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        def split_sentence(sentence, delimiters):
            for d in delimiters:
                sentence = sentence.replace(d, '|')
            return sentence.split('|')
        delimiters = ["--Question--:","--Answer--:"]
        system, user , _= split_sentence(prompt, delimiters)

        input_dict = {'inputs': [[{'role': 'system',
                      'content': f"{system}Question: \n"},
                     {'role': 'user','content':f'{user}\nAnswer:'}]
                    ],
         'parameters': model_kwargs}

        return json.dumps(input_dict).encode('utf-8')
```

   ```
 def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        print("output: ", response_json[0])
        return response_json[0]["generation"]["content"]
```

a bit ugly I suppose.

**Comment by prkhrv** [comment]
@maggarwal25 Were you able to solve this issue?

**Comment by prkhrv** [comment]
If Anyone facing the same issue, try this

```python
class ContentHandler(LLMContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt: str, model_kwargs: dict) -> bytes:
        payload = {
            "inputs": [
                [
                    {"role": "user", "content": prompt},
                ],
                ],
                "parameters": {"max_new_tokens": 1000, "top_p": 0.6, "temperature": 0.1},
        }

        input_str = json.dumps(
            payload,
        )
        
        return input_str.encode("utf-8")

    def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        content = response_json[0]["generation"]["content"]
        return content
```

**Comment by mirodrr** [comment]
@prkhrv , I tried your solution, and I don't get an error, but the content comes back empty

I try the same prompt with the SageMaker SDK, and it works fine. Very strange

**Comment by mirodrr** [comment]
@prkhrv , nevermind, the actual issue was setting temperature to "0.0". 

I have never seen this behavior with other models, but Llama 2 70b chat was consistently giving me empty responses with that temprature

Your fix works, thanks for posting

**Comment by mahdyshabeeb** [comment]
@prkhrv I am facing the same issue while trying to use a Llama model hosted on GCP (Vertex AI - Model Garden).
I am using the VertexAIModelGarden module to create the LLM and when calling the LLM for inference the same error is returned.
Do I have also to create a ContentHandler class? And how can I make the LLM use that class?
