### ISSUE TITLE
`create_pandas_dataframe_agent` does not pass the `handle_parsing_error` variable into the underlying Agent.

### ISSUE THREAD

**Issue by limgw1** [langchain-ai/langchain#10045]
### System Info

Python Version: 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ]
Langchain Version: 0.0.273
Jupyter Notebook Version: 5.3.0

### Who can help?

@hwchase17 
@agola

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce the behaviour:
1. Create a function to be used 
```
def _handle_error(error) -> str:  
    return str(error)[:50]
```
2. Run `create_pandas_dataframe_agent`, pass in `handle_parsing_errors=_handle_error`

### Expected behavior

I expect an output similar to the last section of https://python.langchain.com/docs/modules/agents/how_to/handle_parsing_errors, but instead I still get the normal OutputParserError

**Comment by limgw1** [comment]
@dosu-bot I have updated to v0.0.277, it still returns the error.
I am unable to provide the example due to privacy reasons, but here is the Traceback.
OutputParserException                     Traceback (most recent call last)
Cell In[14], line 16
     13         conversation.append(("Agent 1",clean_user_string(user_msg.content)))
     15 #         refined_user_msg_content = refine_msg_content(user_msg.content)
---> 16         response = assistant_agent.run(user_msg.content)+ " Next request."
     17         assistant_msg = HumanMessage(content=f"{response}")
     18         print(Fore.GREEN+f"Agent 2:\n\n{clean_assistant_string(response)}\n\n")

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py:481, in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    479     if len(args) != 1:
    480         raise ValueError("`run` supports only one positional argument.")
--> 481     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    482         _output_key
    483     ]
    485 if kwargs and not args:
    486     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    487         _output_key
    488     ]

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py:288, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    286 except (KeyboardInterrupt, Exception) as e:
    287     run_manager.on_chain_error(e)
--> 288     raise e
    289 run_manager.on_chain_end(outputs)
    290 final_outputs: Dict[str, Any] = self.prep_outputs(
    291     inputs, outputs, return_only_outputs
    292 )

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/chains/base.py:282, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    276 run_manager = callback_manager.on_chain_start(
    277     dumpd(self),
    278     inputs,
    279 )
    280 try:
    281     outputs = (
--> 282         self._call(inputs, run_manager=run_manager)
    283         if new_arg_supported
    284         else self._call(inputs)
    285     )
    286 except (KeyboardInterrupt, Exception) as e:
    287     run_manager.on_chain_error(e)

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py:1039, in AgentExecutor._call(self, inputs, run_manager)
   1037 # We now enter the agent loop (until it returns something).
   1038 while self._should_continue(iterations, time_elapsed):
-> 1039     next_step_output = self._take_next_step(
   1040         name_to_tool_map,
   1041         color_mapping,
   1042         inputs,
   1043         intermediate_steps,
   1044         run_manager=run_manager,
   1045     )
   1046     if isinstance(next_step_output, AgentFinish):
   1047         return self._return(
   1048             next_step_output, intermediate_steps, run_manager=run_manager
   1049         )

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py:847, in AgentExecutor._take_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
    845     raise_error = False
    846 if raise_error:
--> 847     raise e
    848 text = str(e)
    849 if isinstance(self.handle_parsing_errors, bool):

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py:836, in AgentExecutor._take_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
    833     intermediate_steps = self._prepare_intermediate_steps(intermediate_steps)
    835     # Call the LLM to see what to do.
--> 836     output = self.agent.plan(
    837         intermediate_steps,
    838         callbacks=run_manager.get_child() if run_manager else None,
    839         **inputs,
    840     )
    841 except OutputParserException as e:
    842     if isinstance(self.handle_parsing_errors, bool):

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/agents/agent.py:457, in Agent.plan(self, intermediate_steps, callbacks, **kwargs)
    455 full_inputs = self.get_full_inputs(intermediate_steps, **kwargs)
    456 full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)
--> 457 return self.output_parser.parse(full_output)

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain/agents/mrkl/output_parser.py:52, in MRKLOutputParser.parse(self, text)
     47     return AgentFinish(
     48         {"output": text.split(FINAL_ANSWER_ACTION)[-1].strip()}, text
     49     )
     51 if not re.search(r"Action\s*\d*\s*:[\s]*(.*?)", text, re.DOTALL):
---> 52     raise OutputParserException(
     53         f"Could not parse LLM output: `{text}`",
     54         observation=MISSING_ACTION_AFTER_THOUGHT_ERROR_MESSAGE,
     55         llm_output=text,
     56         send_to_llm=True,
     57     )
     58 elif not re.search(
     59     r"[\s]*Action\s*\d*\s*Input\s*\d*\s*:[\s]*(.*)", text, re.DOTALL
     60 ):
     61     raise OutputParserException(
     62         f"Could not parse LLM output: `{text}`",
     63         observation=MISSING_ACTION_INPUT_AFTER_ACTION_ERROR_MESSAGE,
     64         llm_output=text,
     65         send_to_llm=True,
     66     )

OutputParserException: Could not parse LLM output: `I have the average shift duration for each staff member.`

**Comment by limgw1** [comment]
@dosu-bot
1. Could you provide the exact error message that accompanies the OutputParserException? 
`OutputParserException: Could not parse LLM output: I have the average shift duration for each staff member.`

2. Could you confirm whether the error occurs consistently for all inputs, or only for specific inputs? If it's the latter, could you provide an example of an input that causes the error? 
As long as there is a `Thought:` with no `Action:` or `Final Answer:`, the error will come out

3. Could you confirm whether the error still occurs if you set handle_parsing_errors=True or handle_parsing_errors="Check your output and make sure it conforms!"? 
Yes it still occurs

**Comment by hwchase17** [comment]
you can already do this by using agent_executor_kwargs

eg 
```
create_pandas_dataframe_agent(
...,
agent_executor_kwargs={"handle_parsing_errors": True}
)
