### ISSUE TITLE
PydanticOutputParser failing to parse basic string into JSON

### ISSUE THREAD

**Issue by benjaminb** [langchain-ai/langchain#10057]
### System Info

Given a string resembling a JSON-string array, such as I'm often getting from LLM completions, I'm trying to convert the string to a Python list of strings. I'm finding the the `PydanticOutputParser` is throwing an error when plain old `json.loads` with `strict=False` is doing fine.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

For example this code:
```python
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
import json

class Lines(BaseModel):
    lines: list[str] = Field(description="array of strings")

line_parser = PydanticOutputParser(pydantic_object=Lines)
lines = '[\n  "line 1",\n  "line 2"\n]'

print("Just JSON:")
print(json.loads(lines, strict=False))
print("LangChain Pydantic:")
print(line_parser.parse(lines))
```

produces the following output:
```sh
Just JSON:
['line 1', 'line 2']
LangChain Pydantic:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gt/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 27, in parse
    json_object = json.loads(json_str, strict=False)
  File "/opt/miniconda3/envs/gt/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/miniconda3/envs/gt/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda3/envs/gt/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjaminbasseri/Dropbox/Work/GT Schools/scratch work/meme-generation/parse_test.py", line 14, in <module>
    print(line_parser.parse(lines))
  File "/opt/miniconda3/envs/gt/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 33, in parse
    raise OutputParserException(msg, llm_output=text)
langchain.schema.output_parser.OutputParserException: Failed to parse Lines from completion [
  "line 1",
  "line 2"
]. Got: Expecting value: line 1 column 1 (char 0)
```

### Expected behavior

I would expect the parser to be able to handle a simple case like this

**Comment by PazBazak** [comment]
I think their regex is causing this

`match = re.search(r"\{.*\}", text.strip(), re.MULTILINE | re.IGNORECASE | re.DOTALL)`

it matches None because your JSON has no curly braces.

**Comment by DomainFlag** [comment]
Is there any traction on this issue?

```
from typing import List
from pydantic import RootModel

class OutputItem(BaseModel):
    output: str
    description: str

class JSONParser(RootModel):
    root: List[OutputItem]

# Example usage:
json_data = """[
  {
    "output": "x1",
    "description": "y1"
  },
  {
    "output": "x2",
    "description": "y2"
  }
]"""

try:
    parsed_data = JSONParser.model_validate_json(json_data)
    print(parsed_data.root)
except Exception as e:
    print(f"Error parsing JSON: {e}")
```


You're group matcher /  capturing is buggy and doesn't consider all types of pydantic objects like an object above encoded as valid JSON Array:

https://github.com/langchain-ai/langchain/blob/0bdb4343838c4513d15cd9702868adf6f652421c/libs/langchain/langchain/output_parsers/pydantic.py#L24C11-L24C11

**Comment by ChrisTho23** [comment]
I had the same issue and fixed it by adding 'please output your response in the demanded json format' to the end of my prompt template. It seems like the LLM sometimes loses track of the imposed instruction for the output, especially for long prompts. Hope that helps

**Comment by GonyRosenman** [comment]
i encountered similar issues when trying to use a pydantic output parser, and it seems like its very sensitive to the style of output instruction. 

specifically, i wanted the output to be 2 lists containing 5 strings each, the strings from the 2 lists are logically connected. i was struggling to get the desired output for a while until i tried this approach: 
 
> I had the same issue and fixed it by adding 'please output your response in the demanded json format' to the end of my prompt template. It seems like the LLM sometimes loses track of the imposed instruction for the output, especially for long prompts. Hope that helps

this started giving me better results, together with making a more simplistic description of the output in the pydantic BaseNodel object.
