### ISSUE TITLE
max_marginal_relevance_search not implemented in Redis

### ISSUE THREAD

**Issue by RoderickVM** [langchain-ai/langchain#10059]
### System Info

LangChain version: 0.0.276
Python version: 3.11.2
Platform: x86_64 Debian 12.2.0-14

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
import os, openai
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Redis

embeddings = OpenAIEmbeddings()

rds = Redis.from_existing_index(
    embeddings,
    index_name = INDEX_NAME,
    schema = "redis_schema_kws.yaml",
    redis_url = "redis://10.0.1.21:6379",
)

returned_docs_mmr = rds.max_marginal_relevance_search(question, k=3, fetch_k=3, lambda_mult=0.8)
```

The returned error message is: `NotImplementedError:`

Could you provide additional information on your ETA to have MMR search implemented in Redis?

### Expected behavior

Retrieve the Document objects.

**Comment by RoderickVM** [comment]
Thanks for the reply (although from a bot)!

I am building a specialized chatbot to answer questions and retrieve documentation snippets related to labor law from a relatively big dataset built with official legislation documents from the government.

MMR searches can be very powerful since these documents are very broad, and the users' relevant topics are spread along the entire document corpus.

I have a Redis database installed since it is very robust and fast. Due to this, I intend to use it once the chatbot is for production deployment. I haven't tried any other vector stores.

**Comment by HTahboub** [comment]
@baskaryan this can probably be closed now too

**Comment by baskaryan** [comment]
thanks all!
