### ISSUE TITLE
StreamingStdOutCallbackHandler().on_llm_start isn't called since version 0.0.272 (0.0.271 still works)

### ISSUE THREAD

**Issue by rhoef** [langchain-ai/langchain#10054]
### System Info

0.0.272, linux, python 3.11.2 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

I have a pretty standard RetievalQA chain like this. The `on_llm_start` callback isn't executed since version 0.0.272 (I verified that 0.0.271 is working)

```
    loader = TextLoader("data.txt")
    documents = loader.load()
    openai = ChatOpenAI(**llm_params, callbacks= [StreamingStdOutCallbackHandler()])

    text_splitter = RecursiveCharacterTextSplitter(**chunking_params)
    texts = text_splitter.split_documents(documents)

    embeddings = OpenAIEmbeddings()
    docsearch = Chroma.from_documents(texts, embeddings)

    qa = RetrievalQA.from_chain_type(
        llm=openai,
        retriever=docsearch.as_retriever(),
    )
```

### Expected behavior

`on_llm_start` callback should be called

**Comment by rhoef** [comment]
Sorry for being unclear in communication. I used a custom handler class, although not clear from the code above. Anyhow, I found the bug when updating from an old version to 0.0.277 and found that 0.0.271 is the last version that calls the function of the custom handler. I verified that my code (with is the same as your btw) works with 0.0.271 and does not work with 0.0.272

**Comment by NazimHAli** [comment]
+1 running into the same error with `FinalStreamingStdOutCallbackHandler`. Creating a custom callback and overriding `on_llm_start` shows it won't get called.

```python
class StreamCallbackHandler(FinalStreamingStdOutCallbackHandler):
    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        print("on_llm_start")
```

**Comment by int0x03** [comment]
+1, other callback methods are called, like on_chain_start, on_chat_model_start, on_llm_end, but not on_llm_start

**Comment by l-pa** [comment]
For me, after removing the `on_chat_model_start` the `on_llm_start` was called

**Comment by venkata-mi** [comment]
on_chat_model_start works for me as I was using ChatOpenAI
