### ISSUE TITLE
Add SelfQueryRetriever support for Redis Vector Stores

### ISSUE THREAD

**Issue by RoderickVM** [langchain-ai/langchain#10064]
### Feature request

Implement Self Query retriever to Redis vector stores.

### Motivation

I was trying the different retrievers for my project (AI chatbot that answers various human resources and labor law questions based on a dataset built from complete local labor legislation, company handbooks, job descriptions and SOPs).

I plan to deploy this chatbot in a production environment, therefore I chose Redis (for its robustness and speed) as a vector store.

### Your contribution

I am not a pro developer; so, unfortunately, the only contributions I can make is limited to "real-world" testing.

**Comment by Spartee** [comment]
Should be done in #10199
