### ISSUE TITLE
ConversationTokenBufferMemory and ConversationSummaryBufferMemory does not work with db-backed histories

### ISSUE THREAD

**Issue by erunistic** [langchain-ai/langchain#10078]
### System Info

the memories are pruned after saving using .pop(0). However, db-backed histories read messages and copies into list each turn. This makes it so that the actual db does not change at every turn, and so max_token_limit parameter gets ignored and the memory prints out the entire conversation for history.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Initialize redis chat history
use redis chat history as chat_history for ConversationSummaryBufferMemory
set max_token_limit to 1.
Print history at every turn.
Still prints the entire history

### Expected behavior

Initialize redis chat history
use redis chat history as chat_history for ConversationSummaryBufferMemory
set max_token_limit to 1.
Print history at every turn.
Print nothing since max_token_limit = 0

**Comment by AvikantSrivastava** [comment]
@hwchase17 shouldn't the ConversationSummaryBufferMemory be compatible with db-backed memory?
are there any plans to make it work? if so I am happy to contribute!
