### ISSUE TITLE
ElasticSearch authentication

### ISSUE THREAD

**Issue by Lishenga** [langchain-ai/langchain#10077]
### System Info

On the elasticsearch authentication, you have implemented it this way on the elasticsearch.py file found in the vectorstores folder

```py
if api_key:
            connection_params["api_key"] = api_key
        elif username and password:
            connection_params["basic_auth"] = (username, password)
```

but i think it should be this way 
```py
if api_key:
            connection_params["api_key"] = api_key
        elif username and password:
            connection_params["http_auth"] = (username, password)
```

with that change the authentication succeeeds. What i have just changed is this connection_params["basic_auth"] = (username, password) to this connection_params["http_auth"] = (username, password)

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Create an elasticsearch instance on an EC2 instance using docker that has SSL and also uses username and password and then try to authenticate to that elasticsearch instance using langchain you will see the error

### Expected behavior

The expected behavior is successfull authentication

**Comment by joemcelroy** [comment]
Hi there,

According to the documentation, it is [basic_auth](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connecting). Could you tell me more details about your elasticsearch instance? (which version specifically?) To use all the features ElasticsearchStore provides, please use v8.9.0 or above :-)

I will also double check this, we dont have a test case for this method of authentication. 

Joe
