### ISSUE TITLE
Text splitting with keep_separator is True still removes any whitespace, even if separator is whitespace

### ISSUE THREAD

**Issue by jamesw6811** [langchain-ai/langchain#10085]
```
text = "foo _bar_ baz_ 123"
separator = "_"

text_splitter = CharacterTextSplitter(
    chunk_size=4,
    chunk_overlap=0,
    separator="_",
    keep_separator=True,
)

print(text_splitter.split_text(text))
```
RETURNS:
`['foo', '_bar', '_ baz', '_ 123']`
EXPECTED:
`['foo ', '_bar', '_ baz', '_ 123']`

^see whitespace next to `foo`

https://github.com/langchain-ai/langchain/blame/324c86acd5be9bc9d5b6dd248d686bdbb2c11cdc/libs/langchain/langchain/text_splitter.py#L155 removes all whitespace from the text. I can't figure out the purpose of this line.

**Comment by IlyaMichlin** [comment]
[This](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/text_splitter.py#L155) line is causing thes issue where it strips every doc. It is probably the desired behaviour in most of the cases.
Maybe add a flag for that line?

**Comment by jamesw6811** [comment]
Thanks @IlyaMichlin !

Something like the following?

```
CharacterTextSplitter(
    chunk_size=4,
    chunk_overlap=0,
    separator="_",
    keep_separator=True,
    keep_whitespace=True
)
```
`keep_whitespace` would default to `False`

then, functionally:
`if not keep_whitespace: text = text.strip()`

**Comment by jamesw6811** [comment]
Thank you!
