### ISSUE TITLE
Issue: chroma retriever where_document parameter passed in search_kwargs is invalid

### ISSUE THREAD

**Issue by PTTrazavi** [langchain-ai/langchain#10082]
### Issue you'd like to raise.

I am using chroma db as retriever in ConversationalRetrievalChain, but the parameter "where_document" does not work.
```python
search_kwargs = {
    "k": k,
    "filter": filter,
    "where_document": {"$contains": "1000001"}
}
retriever = vectordb.as_retriever(
    search_kwargs=search_kwargs
)
```
In chroma official site [chroma](https://docs.trychroma.com/usage-guide), it says: 
Chroma supports filtering queries by metadata and document contents. The where filter is used to filter by metadata, and the where_document filter is used to filter by document contents.

### Suggestion:

can ConversationalRetrievalChain support where_document filter for chroma db?

**Comment by ssk2706** [comment]
@dosu-bot is there any way using which I can add a filter for all the documents stored in multiple directories dynamically
