### ISSUE TITLE
Parsing intermediate steps: Object of type AgentAction is not JSON serializable

### ISSUE THREAD

**Issue by Tech-Netiums** [langchain-ai/langchain#10099]
### System Info

python 3.9 langchain 0.0.250

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Follow the steps in [Access Intermediate Steps](https://github.com/langchain-ai/langchain/blob/master/docs/extras/modules/agents/how_to/intermediate_steps.ipynb) within the Agent "How To".

When converting the steps to json:
print(json.dumps(response["intermediate_steps"], indent=2))

This raises the error:
TypeError: Object of type AgentAction is not JSON serializable

### Expected behavior

This issue is similar to the one raised in #8815. 
However the bot answer is not satisfying as using 
```
from langchain.load.dump import dumps

print(dumps(response["intermediate_steps"], pretty=True))
```
will not serialize the `AgentAction`

I can propose a `__json__()` function to correct this the lib json-fix or either inherit the class from dict

**Comment by Omer-ler** [comment]
Hi @Tech-Netiums - 
[This](https://github.com/langchain-ai/langchain/issues/8815) solved my issue (which was the same as yours).
Good luck!
