### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_experimental.data_anonymizer'

### ISSUE THREAD

**Issue by skye0402** [langchain-ai/langchain#10126]
### System Info

Langchain 0.0.279 / Langchain experimental 0.0.12/ Python 3.10

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Follow the guideline: https://python.langchain.com/docs/guides/privacy/presidio_data_anonymization

I was able to make it work by downloading the source of the langchain experimental and copy & pasting the missing folder into the local lib folder.
However, this won't be a good option when building a docker image. Why isn't it part of the experimental library 0.0.12?

### Expected behavior

Example codes will work.

**Comment by skye0402** [comment]
It has been resolved in langchain_experimental 0.0.13 which was published today. Closing.

**Comment by MuriloBianco** [comment]
link?

**Comment by mwzkhalil** [comment]
having same error while importing create_spark_dataframe_agent from langchain_experimental
`
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-28-3b7e8be6eb0b>](https://localhost:8080/#) in <cell line: 3>()
      1 import openai
      2 import os
----> 3 from langchain_experimental.agents.agent_toolkits import create_spark_dataframe_agent
      4 from langchain.agents import load_tools, initialize_agent
      5 from langchain.agents import AgentType

ModuleNotFoundError: No module named 'langchain_experimental'
`

**Comment by mwzkhalil** [comment]
Solved by doing 
`
pip install langchain_experimental
`

**Comment by TrilokiDA** [comment]
pip install langchain_experimental

This worked for me

**Comment by nikitamalviya** [comment]
> Solved by doing `pip install langchain_experimental`

Make sure to have python=3.8.1

`pip install numpy torch tensorflow langchain langchain-experimental`
