### ISSUE TITLE
ConversationalRetrievalChain doesn't work with Azure OpenAI

### ISSUE THREAD

**Issue by decoderdot** [langchain-ai/langchain#10128]
### System Info

Latest

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use ConversationalRetrievalChain with an Azure OpenAI gpt model

This is the code:

llm = AzureOpenAI(engine=OPENAI_DEPLOYMENT_NAME, model=OPENAI_MODEL, temperature=0.0)
qa = ConversationalRetrievalChain.from_llm(llm, retriever)

I get the following error:

usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for LLMChain
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)

### Expected behavior

The code executes without any error

**Comment by decoderdot** [comment]
Thanks, I am new to python but will look into implementing the abstract class.
In a nutshell, does it mean that we can't directly use Langchain with the Azure OpenAI models?

**Comment by jimmyland22** [comment]
I'm still encountering this issue. Doesn't seem like anyone contributed the code for the abstract class?
