### ISSUE TITLE
SageMaker Endpoints with Streaming Capability

### ISSUE THREAD

**Issue by dazajuandaniel** [langchain-ai/langchain#10125]
### Feature request

With the new announced [support for Streaming in SageMaker Endpoints](https://aws.amazon.com/blogs/machine-learning/elevating-the-generative-ai-experience-introducing-streaming-support-in-amazon-sagemaker-hosting/), Langchain can add a Streaming capability to the `SagemakerEndpoint` class.

We can leverage the code that already exists as part of the blog post and extend where required by using the [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker-runtime/client/invoke_endpoint_with_response_stream.html) API

### Motivation

Decreasing latency is important for developers. Streaming is currently available in `OpenAI`, `ChatOpenAI`, `ChatAnthropic`, `Hugging Face Text Generation Inference`, and `Replicate`. Having `SageMaker` opens the possibilities to a wide range of developers that leverage this AWS Service.

### Your contribution

I can work on this feature to start the process with guidance from the core development team and the community.

**Comment by iritsanna** [comment]
Is there anyone with an update on this issue? How to implement the latest streaming capability in langchain?

**Comment by jay2jp** [comment]
I believe this pull request would add this feature [pull request from lyoh001 ](https://github.com/langchain-ai/langchain/pull/12122)

**Comment by AlvinKimata** [comment]
To resolve the issue, you can pass the `endpoint_kwargs` in the SagemakerEndpoint class:

```python
llm=SagemakerEndpoint(
        endpoint_name=endpoint_name,
        client=client,
        model_kwargs={"temperature": 0.1, "InferenceComponentName": inferenceComponentName},
        endpoint_kwargs={"InferenceComponentName": inferenceComponentName},
        content_handler=content_handler,
        streaming = False
```
