### ISSUE TITLE
How to develop an efficient question answering solution acting as a customer assistant based on RAG or Fine tuning?

### ISSUE THREAD

**Issue by rgniche** [langchain-ai/langchain#10188]
### System Info

0.0.274

### Who can help?

@hwchase17 @agola11 @eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.llms import VertexAI
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory
import os

PROMPT= """
        You are a customer service assistant.
        Your task is to respond to user questions.
        Start by greeting the user and introducing yourself as BotAssistant, and end with a polite closing. If you don't know the answer, suggest contacting customer service at 3232. Always conclude with: "I hope I've answered your request
        Query: """

llm_model=VertexAI(
                model_name="text-bison@001",
                max_output_tokens=1024,
                temperature=0.1,
                top_p=0.8,
                top_k=40,
                verbose=True,
            )
conversation = ConversationChain(
                        llm=llm_model, 
                        verbose=True, 
                        memory=ConversationBufferMemory(),
                    )

qst="I have an issue with my order; I received the wrong item. What should I do?"
conversation.predict(input=PROMPT+qst)

```

### Expected behavior

I want to develop an llm that acts as a customer assistant( to use for E comerce), responding to user queries using a JSON dataset containing question-answer pairs,possibly incorporating pdf documents of terms and conditions and offer descriptions. How can I effectively use Retrieval Augmented Generation to address this challenge? Is fine-tuning a recommended approach?

Sometimes, the answers to queries are indirect, and they may include links to previously provided answers on the same topic.do you think that a graph representation of the questions answers pairs dataset is relevant?

Any help,links would be appreciated,

**Comment by rgniche** [comment]
@hwchase17 @agola11 @eyurtsev an idea?

**Comment by austinmw** [comment]
What about for non OpenAI LLMs? It seems `create_conversational_retrieval_agent` is only available for OpenAI unfortunately?
