### ISSUE TITLE
Issue: RedisVectorStoreRetriever not accessible

### ISSUE THREAD

**Issue by ramosmario** [langchain-ai/langchain#10186]
### Issue you'd like to raise.

After PR [#8612](https://github.com/langchain-ai/langchain/pull/8612), access to [RedisVectorStoreRetriever](https://github.com/langchain-ai/langchain/blob/27944cb611ee8face34fbe764c83e37841f96eb7/libs/langchain/langchain/vectorstores/redis/base.py#L1293) has been removed

### Suggestion:

Include **RedisVectorStoreRetriever** import in [redis/__init__.py](https://github.com/langchain-ai/langchain/blob/27944cb611ee8face34fbe764c83e37841f96eb7/libs/langchain/langchain/vectorstores/redis/__init__.py) on line 1

current: `from .base import Redis`
suggestion update: `from .base import Redis, RedisVectorStoreRetriever`

**Comment by FrancescoSaverioZuppichini** [comment]
same here

**Comment by Spartee** [comment]
@ramosmario Thanks, hopefully using ``as_retriever`` or adding the ``.base`` worked in the meantime. Should be fixed by https://github.com/langchain-ai/langchain/pull/10414

Let me know if that solves it for you.

**Comment by ramosmario** [comment]
thank you @Spartee !
