### ISSUE TITLE
Add sqlite-vss as a vectorstore option

### ISSUE THREAD

**Issue by nfcampos** [langchain-ai/langchain#1019]
https://github.com/asg017/sqlite-vss

I think this is an interesting option, FAISS indices backed with SQLite storage and interface, could be the easiest step up from in memory FAISS to something persisted before going for a hosted vector store

**Comment by philippe2803** [comment]
Working on it

**Comment by abdul-hamid-achik** [comment]
this one seems to be done already guys https://github.com/langchain-ai/langchain/pull/10047

btw big thanks for adding this 💯

**Comment by philippe2803** [comment]
This issue should be marked as resolved. The PR has been merged and we now have sqlite-vss as an option for vector store.
