### ISSUE TITLE
Error failed to index when using ElasticsearchStore.from_documents

### ISSUE THREAD

**Issue by mikysetiawan** [langchain-ai/langchain#10218]
### System Info

Python : v3.10.10
Langchain : v0.0.281
Elasticsearch : v8.9.0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I was following this documentation https://python.langchain.com/docs/integrations/vectorstores/elasticsearch
my script was

```
# GENERATE INDEXING

loader = TextLoader("models/state_of_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

db = ElasticsearchStore.from_documents(
    docs,
    embeddings,
    es_url="http://localhost:9200",
    index_name="test-basic", 
    es_user=os.environ.get("ELASTIC_USERNAME"),
    es_password=os.environ.get("ELASTIC_PASSWORD"),
)
```

but it raising an error when indexing the document

```
Created a chunk of size 132, which is longer than the specified 100
Created a chunk of size 107, which is longer than the specified 100
Created a chunk of size 103, which is longer than the specified 100
Created a chunk of size 104, which is longer than the specified 100
Error adding texts: 336 document(s) failed to index.
First error reason: failed to parse
Traceback (most recent call last):
  File "D:\Project\elastic-langchain\main.py", line 31, in <module>
    db = ElasticsearchStore.from_documents(
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 1027, in from_documents
    elasticsearchStore.add_documents(documents)
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\langchain\vectorstores\base.py", line 101, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 881, in add_texts
    raise e
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 868, in add_texts
    success, failed = bulk(
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\elasticsearch\helpers\actions.py", line 521, in bulk    
    for ok, item in streaming_bulk(
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\elasticsearch\helpers\actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\elasticsearch\helpers\actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "D:\Project\elastic-langchain\.venv\lib\site-packages\elasticsearch\helpers\actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 336 document(s) failed to index.
```

### Expected behavior

It can indexing and not raising any errror

**Comment by mikysetiawan** [comment]
1. Connection to Elasticsearch = it's fine, because I try without .from_documents it's not giving any error, only empty result
2. Index creation = it's already created, I checked from http://127.0.0.1:9200/test-basic/_mapping

```
{
    "test-basic": {
        "mappings": {
            "properties": {
                "vector": {
                    "type": "dense_vector",
                    "dims": 1536,
                    "index": true,
                    "similarity": "cosine"
                }
            }
        }
    }
}
```

3. Documents : https://github.com/hwchase17/chat-your-data/blob/master/state_of_the_union.txt
4. Embedding Function : as you can see, my code only using default indexing but it raises an error

**Comment by mikysetiawan** [comment]
@dosu-bot

there is no problem with my indexes

```
{
    "test-basic": {
        "mappings": {
            "properties": {
                "vector": {
                    "type": "dense_vector",
                    "dims": 1536,
                    "index": true,
                    "similarity": "cosine"
                }
            }
        }
    }
}
```

also I'm not using any pipeline

**Comment by mikysetiawan** [comment]
@dosu-bot

hi this is my code, even if the document only have 2 words like "Madam Speaker" it's raising the same error, so I think the problem is not the document


main.py
```python
import os
from dotenv import load_dotenv
from langchain.vectorstores.elasticsearch import ElasticsearchStore
from langchain.embeddings.openai import OpenAIEmbeddings

from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter

load_dotenv()

# GENERATE INDEXING

loader = TextLoader("models/state_of_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

# Check the vector field in your documents
vector_query_field = 'vector'  # replace with your actual vector field

db = ElasticsearchStore.from_documents(
    docs,
    embeddings,
    es_url="http://localhost:9200",
    index_name="test-basic", 
    es_user=os.environ.get("ELASTIC_USERNAME"),
    es_password=os.environ.get("ELASTIC_PASSWORD"),
    distance_strategy="COSINE",
    # distance_strategy="EUCLIDEAN_DISTANCE",
    # distance_strategy="DOT_PRODUCT",
    strategy=ElasticsearchStore.ApproxRetrievalStrategy(),
    vector_query_field=vector_query_field
)

db.client.indices.refresh(index="test-basic")

query = "What did the president say about Ketanji Brown Jackson"
results = db.similarity_search(query)
print(results)
```

**Comment by mikysetiawan** [comment]
@dosu-bot

I found the problem, the problem is from embeddings on [libs/langchain/langchain/vectorstores/elasticsearch.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/elasticsearch.py) line 822, if I change the condition to false, it's work

my embeding if I print it to console is

```
client=<class 'openai.api_resources.embedding.Embedding'> model='text-embedding-ada-002' deployment='text-embedding-ada-002' openai_api_version='' openai_api_base='' openai_api_type='' openai_proxy='' embedding_ctx_length=8191 openai_api_key='sk-' openai_organization='' allowed_special=set() disallowed_special='all' chunk_size=1000 max_retries=6 request_timeout=None headers=None tiktoken_model_name=None show_progress_bar=False model_kwargs={}
```

**Comment by mikysetiawan** [comment]
so the problem is dims size of vector, from elasticsearch documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

![image](https://github.com/langchain-ai/langchain/assets/26665849/a4f83c6a-2a4c-49d1-905e-3a0bf8f6050b)

what can I do?
@hwchase17 @eyurtsev

**Comment by mikysetiawan** [comment]
so the problem is dims size of vector, from elasticsearch documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html

![image](https://github.com/langchain-ai/langchain/assets/26665849/a4f83c6a-2a4c-49d1-905e-3a0bf8f6050b)

must upgrade to minimum elasticsearch 8.8

**Comment by joemcelroy** [comment]
Thanks for using Elasticsearch! Will make this more clear that its best used with Elasticsearch 8.8+.

**Comment by VBoB13** [comment]
> must upgrade to minimum elasticsearch 8.8

Now this is good to know... I just upgraded my LangChain using `pip install -U langchain`, then the old `ElasticVectorSearch` object started to throw "Depricated" warnings thus I had to re-write the code.
Re-writing the code wasn't difficult, but when it doesn't work the way it did in the past (e.g. simple embeddings that I could do before is not possible).

Now I just gotta upgrade our whole Elasticsearch service 😭

**Comment by joemcelroy** [comment]
> Now I just gotta upgrade our whole Elasticsearch service 😭

Hey @VBoB13 What version of Elasticsearch are you running? It should work fine with 8 +, just some of the features like hybrid search wont be available. 

Also to note, `ElasticVectorSearch` relies on brute force approach to do vector search (via a script calculation). You can enable this via using the ExactRetrievalStrategy. This should behave exactly how `ElasticVectorSearch` works.

Joe

**Comment by VBoB13** [comment]
@joemcelroy I was using version 8.3.3 from [this Docker Hub project](https://hub.docker.com/r/sebp/elk/)
I had the exact same error as above, so I just assumed that I might have to upgrade Elasticsearch to make it all work.

I proceeded to upgrade to version 8.9.1 (which should be the latest version as of now) and new indices now work as expected.
Due to the changes made in how the ElasticsearchStore works (compared to the old ElasticVectorStore), it does not allow me to use the old indices to search through, thus I will have to recreate all the old indices..

**Comment by joemcelroy** [comment]
Yes `ElasticVectorStore` used brute force approach so you should be able to search on the old indices with setting the [brute force strategy](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#exactretrievalstrategy) (tho may need to tweak the vector and text fields aswell)

Approx (which is what ElasticsearchStore uses) uses the HNSW algorithm to search which scales better when you have a large number of vectors. Its why its our preferred default now.

**Comment by VBoB13** [comment]
I can confirm that it now works as intended 😄

**Comment by w5688414** [comment]
Thanks, I use this command, it works:

```
sudo docker run \
      -d \
      --name es02 \
      --net elastic \
      -p 9200:9200 \
      -e discovery.type=single-node \
      -e ES_JAVA_OPTS="-Xms512m -Xmx512m"\
      -e xpack.security.enabled=false \
      -e cluster.routing.allocation.disk.threshold_enabled=false \
      -it \
      docker.elastic.co/elasticsearch/elasticsearch:8.9.1
```
