### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by mamingsuper** [langchain-ai/langchain#1023]
thanks for creating this amazing tool. Just a stupid question from newbie, could anyone help me to fix it? Thanks

I run 
from langchain.agents import load_tools

and encounter with
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/var/folders/1s/cmtvypz54h3f0jx3nsjzvhn80000gn/T/ipykernel_67867/2458684745.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/1s/cmtvypz54h3f0jx3nsjzvhn80000gn/T/ipykernel_67867/2458684745.py) in 
----> 1 from langchain.agents import load_tools

ImportError: cannot import name 'load_tools' from 'langchain.agents' ([/opt/anaconda3/envs/bertopic/lib/python3.7/site-packages/langchain/agents/__init__.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/bertopic/lib/python3.7/site-packages/langchain/agents/__init__.py))

**Comment by Neeesh399** [comment]
Hi! I'm also new to LangChain and have never answered questions here before, so I apologize if I'm not following the correct conventions, but I was having the same issue and was able to fix it by uninstalling Python 3.7 and reinstalling the latest version (Python 3.11.2) and using pip to uninstall/reinstall LangChain.  

That fixed it for me, hope it works for you too. Good luck!

**Comment by HuizhiXu** [comment]
I had the same problem and fixed it by upgrading python 3.7 to python 3.9.

**Comment by VoxHwa** [comment]
Is this a version problem or what? I encountered same when using python 3.11

**Comment by ashish-delta4infotech** [comment]
i am using python version 3.9 but still i am getting an error while loading 
```

from langchain.tools import OpenAPISpec

ImportError: cannot import name 'OpenAPISpec' from 'langchain.tools' (/home/superman7/anaconda3/lib/python3.9/site-packages/langchain/tools/__init__.py)

```

**Comment by KeshavSingh29** [comment]
I get something similar as well, 
```python 
ImportError: cannot import name 'tool' from 'langchain.tools'
```
Looking at the documentation, tools is defined as a function in base.py

**Comment by not-apollo** [comment]
Just a heads up to people on this thread, most of my import errors were because I was using an older version of langchain. This repo is updating like crazy (for good reason) - make sure you're up to date if you're having problems.
For example the above:

```
from langchain.tools import BaseTool, StructuredTool, Tool
```

is totally valid in 1.7.0
