### ISSUE TITLE
Language parameter in OpoenAI() is not working anymore!

### ISSUE THREAD

**Issue by venturaEffect** [langchain-ai/langchain#10230]
### System Info

All latest versions

### Who can help?

@agola

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The parameter language="es" in OpenAI() is not working anymore. And I have to present it tomorrow at the university! I can't find any solution for this. Nowhere. 

Pretty simple code that was working perfectly and now not anymore:

`model= OpenAI(temperature=0, language="es")`

Now I'm getting this error message:  

`C:\Users\zaesa\anaconda3\Lib\site-packages\langchain\utils\utils.py:155: UserWarning: WARNING! language is not default parameter.
                language was transferred to model_kwargs.
                Please confirm that language is what you intended.
  warnings.warn(  `

How to solve it?

### Expected behavior

It should just search in spanish pages and answer in spanish. It was pretty simple. Now it just doesn't work anymore. Any help will be really apprecaited.

**Comment by subhan97ahmed** [comment]
Which version of Langchain you are using?

**Comment by venturaEffect** [comment]
Thanks for answering me @subhan97ahmed. 

I was using the version 0.0.266

Updated to the last one. Same issue. Went back to old version.

Tried also this code:

`    conversation_history.append(
        {"role": "assistant", "content": assistant_response})
    conversation_history.append(
       {"role": "system", "content": "Always answer in spanish and without repeating yourself in the same answer, or in other answers"})
`

And to search just on spanish websites tried on: 

`search = GoogleSearchAPIWrapper()`

This:

`search = GoogleSearchAPIWrapper(
    language="es", api_key=google_api_key, cse_id=google_cse_id
)`

but I get errors telling there are no extra fields permitted for api_key, cse_id and lang.

This is weeird because it should accept these parameters.

Appreciate your help!

**Comment by subhan97ahmed** [comment]
@venturaEffect 

I did not see any language parameter being used in docs or code. Tried using model_kwargs but it didn't work. Maybe this will help your use case. Hope this helps.

```
from langchain.chat_models import ChatOpenAI
from langchain import PromptTemplate, LLMChain
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)

template="You are a helpful assistant that talks only in {language}."
system_message_prompt = SystemMessagePromptTemplate.from_template(template)
human_template="{text}"
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)

chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

chat = ChatOpenAI(temperature=0)

chat(chat_prompt.format_prompt(language="Spanish", text="Hi").to_messages())
```

**Comment by venturaEffect** [comment]
Thanks a lot for this code snippet. Will have to think how to add this with the custom database I have and the access to the internet. Still can't understand why it doesn't work the parameters of  `search = GoogleSearchAPIWrapper( language="es", api_key=google_api_key, cse_id=google_cse_id )` to just search for spanish web pages.
