### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.schema.document'; 'langchain.schema' is not a package

### ISSUE THREAD

**Issue by bathroomhu** [langchain-ai/langchain#10266]
### System Info

Since we updated to the latest langchain we are also getting this issue. We are a startup, just launched, updated yesterday now all our apps don't work. First customer annoyed.

**Please, please help!**

Name: langchain
Version: 0.0.281

`    data_state_nsw_legisation_index_instance = FAISS.load_local("data_indexes/federal/federal_legislativeinstruments_inforce_index", embeddings)
  File "/opt/homebrew/lib/python3.10/site-packages/langchain/vectorstores/faiss.py", line 472, in load_local
    docstore, index_to_docstore_id = pickle.load(f)
ModuleNotFoundError: No module named 'langchain.schema.document'; 'langchain.schema' is not a package`

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

data_state_nsw_legisation_runner = RetrievalQA.from_chain_type(llm=ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0,
                                                openai_api_key=openai_api_key_value),
                                                chain_type="stuff",
                                                retriever=data_state_nsw_legisation_index_instance.as_retriever())

### Expected behavior

yesterday before we updated is was working perfectly, we updated to the latest version and it all stopped :(

**Please help!** the team is scrambling

**Comment by bathroomhu** [comment]
It did not fix the problem

**Comment by eyurtsev** [comment]
@bathroomhu the underlying store is relying on `pickle` for serialization. Pickling is brittle to changes in the environment (e.g., updating the underlying code). Your options are:

1. re-create the store from scratch
2. restore the previous environment and loading the data from the store, and re-implement `save_local` to serialize without using pickle
3. Use a different vectorstore which does not rely on pickle for serialization

**Comment by MohammadHeydari** [comment]
Try this one: 

`from langchain_core.documents import Document`

it works
