### ISSUE TITLE
DOC: One link in Chain->Diff cll methods is not working

### ISSUE THREAD

**Issue by kislayads** [langchain-ai/langchain#10272]
### Issue with current documentation:

[This](https://python.langchain.com/docs/modules/chains/how_to/call_methods#:~:text=See%20an%20example%20here.) link is not working. 

<img width="1228" alt="image" src="https://github.com/langchain-ai/langchain/assets/84584929/19a6f523-8584-4338-80e0-ffe78c51714a">

**Comment by ShatilKhan** [comment]
It worked in my case & took me to [this site](https://python.langchain.com/docs/modules/agents/tools/custom_tools.html)
Do check your Browser or Internet settings ,maybe you could find possible reasons why it happened
