### ISSUE TITLE
GPU usage 0 even with n_gpu_layers.

### ISSUE THREAD

**Issue by Dharmavineta** [langchain-ai/langchain#10276]
GPU usage doesn't change and my Local Llama model only runs under CPU

``I'm running a local llama 2 7b model(hugging face bloke model), on my local machine, everything works fine, except that only cpu works and GPU usage remains 0 throughout. I've included n_gpu_layers and other such options, but gpu just doesn't work for some reason. 

device ram= 16gb
 Vram = 6gb. 

I can see 100% usage of my CPU, but nothing changes with respect to GPU usage. 

This is my code in python. 
`
from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from transformers import AutoModelForCausalLM, AutoTokenizer

# MODEL_PATH = "D:\yarn-llama-2-7b-128k.Q2_K.gguf"
MODEL_PATH = "D:\llama-2-7b-chat.Q3_K_M.gguf"

def load_model():
    """Loads Llama model"""
    callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
    Llama_model = LlamaCpp(
        model_path=MODEL_PATH,
        temperature=0.5,
        max_tokens=2000,
        top_p=1,
        callback_manager=callback_manager,
        verbose=True,
        n_gpu_layers=100,
        n_batch=512

    )
    return Llama_model

llm = load_model()

model_prompt = """
a discussion between hitler and buddha
"""

response = llm(model_prompt)

print(response)

`

Does anybody have any idea how to include gpu ?

**Comment by YogeshTembe** [comment]
I tried following commands on windows but gpu is not utilised.

1) set CMAKE_ARGS="-DLLAMA_CUBLAS=on"
2) set FORCE_CMAKE=1
3) pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir

can you please let me know if anything is missing in steps.

**Comment by erlebach** [comment]
I have the same issue on Linux. The GPU is utilized on my mac. Has anybody run with the GPU on Linux? Thanks.
