### ISSUE TITLE
[create_csv_agent] Change dataframe as according to the prompt, and also save when required

### ISSUE THREAD

**Issue by rafayaar** [langchain-ai/langchain#10281]
### Feature request

Currently there isn't any feature which we can use to actually manipulate/change and save the data frame.

**Examples:**
If I say rename columns to Column1, Column2, Column3. 
Make new column named as [Column4] having data concatenated from Column1 and Column2

It should actually perform the functionalities and make changes in dataframe. And once user is done with its prompt there should be a function or a specific prompt which user can use to actually save manipulated dataframe as CSV.

``` 
agent = create_pandas_dataframe_agent(
    ChatOpenAI(temperature=0, model="gpt-3.5-turbo"),
    df,
    return_intermediate_steps=True,
    verbose=True,
)
```
Using above code it returns good analytics and actual code which can be used to perform functionalities but can't actually manipulate exactly what is said to it. PLUS we cant save dataframe.

### Motivation

One can use this feature to actually manipulate data based on prompts, which can aid in Data Science industry.

### Your contribution

I looked into the source code but couldn't manage to locate the implementation of agent itself.

**Comment by YungCos** [comment]
I'm interested
