### ISSUE TITLE
Docker for development and sandboxing

### ISSUE THREAD

**Issue by blob42** [langchain-ai/langchain#1031]
I propose to put together a dockerfile/compose for quickly setting up a dev/build container. 

This will also have the  benefit of extra security in the scenarios of code executions as mentioned in #1026.

I will make a PR for this. 

## Update:

This issue will be used to track the progress of PRs related to Docker. Separating development/testing from security/sandboxing will make it easier to manage changes and distribute the work.

### Development and testing with docker

The use of docker here is to provide a consistent environment for development and testing. The docker images here are not meant to be used for untrusted code execution by chains/agents.

- #1055

### Docker image for untrusted code execution

- #1266 

This issue aims to create a Docker image that can be used to run untrusted code for chains/agents, with proper sandboxing and output sanitization. The following options will be considered:

The following options will be consider:

1. Using a virtualised runtime for docker such as [gVisor](https://gvisor.dev/)
Pros: Offers almost the same level of sandboxing as full virtualization 
Cons: Potential performance issues
2. Drop all capabilities from the container [see](https://github.com/glotcode/docker-run)
3. For PythonREPL: Use [sandboxlib](https://doc.pypy.org/en/latest/sandbox.html)
4. Update the exec family of Tools and allow execution on a remote shell (like ssh) . Users can redirect the shell to a full virtual machine (kvm, xen ... )  

### Motivation

The various REPLs and shells than can be used by agents come with a significant risk of running untrusted and potentially malicious code. Docker can add an extra layer of sandboxing to mitigate these risks. Additionally, it is important to ensure proper sanitization of the agent's output to prevent information disclosure or other security vulnerabilities.  refer to #1026

**Comment by hwchase17** [comment]
thanks - love this idea

**Comment by blob42** [comment]
Since docker will be used for both a development as well as an execution env for schains/agent I am moving all the comments related to docker to this issue in order to split the work over multiple PRs

**Comment by jj701** [comment]
Any progress on creating a dev container:

.devcontainer
    devcontainer.json
    Dockerfile
