### ISSUE TITLE
DOC: <Observation Streaming Using Call Back>

### ISSUE THREAD

**Issue by axen2u** [langchain-ai/langchain#10312]
### Issue with current documentation:

When I am using a tool with `return_direct = True` , the observation step will provide the answer. Is there a way to stream that observation from the intermediate steps using callbacks. I found no information regarding this. It is much appreciated if we can add something  regarding that as well.

**Comment by maziyarpanahi** [comment]
This is an interesting question, @axen2u have you found a way to make this happen?

**Comment by axen2u** [comment]
@maziyarpanahi add Final Answer: to tool output using string concatenation.
