### ISSUE TITLE
Langchain doesnt work with Databricks Model serving asking generate (str type expected (type=type_error.str)

### ISSUE THREAD

**Issue by Prashantramappa** [langchain-ai/langchain#10318]
### System Info

I have created a LLama 7b model and in Databricks i have used model serving options. When i test model it works in databricks, but when i use the same model to connect with Langchain i get this error.

this works in Databricks model endpoint:

Json input:
{
  "dataframe_split": {
    "columns": [
      "prompt",
      "temperature",
      "max_tokens"
    ],
    "data": [
      [
        "what is ML?",
        0.5,
        100
      ]
    ]
  }
}

code:-
from langchain.llms import Databricks

llm = Databricks(endpoint_name="databricks-llama-servingmodel", model_kwargs={"temperature": 0.1, "max_tokens": 100})
llm ("who are you")

Error:-
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

### Who can help?

 @hwchase17
  @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Any model you take LLM and use the below notebook
https://github.com/databricks/databricks-ml-examples/blob/master/llm-models/llamav2/llamav2-7b/02_mlflow_logging_inference.py (for model serving)

Try using model serving in Langchain as show in the code and official langchain documents

from langchain.llms import Databricks

llm = Databricks(endpoint_name="databricks-llama-servingmodel", model_kwargs={"temperature": 0.1, "max_tokens": 100})
llm ("who are you")

### Expected behavior

llm("who are you")
expected output:- I am language model

**Comment by Prashantramappa** [comment]
I have changed my Databricks MLFLOw signature to follow the above standards and i want to tell you that now it Promopt(str) and Stop (list['str'])
{
  "dataframe_split": {
    "columns": [
      "prompt",
      "stop"
    ],
    "data": [
      [
        "what is ML?",
        "\n"
      ]
    ]
  }
}

using my Databricks model End point....it works

output:
{"predictions": {"candidates": ["Machine learning (ML) is a subset of artificial intelligence (AI) that involves training algorithms to learn from data and make predictions or decisions without being explicitly programmed. ML algorithms can analyze large datasets, identify patterns, and learn from errors to improve their performance over time.\nIn simple terms, machine learning is a way for machines to learn from data without being explicitly programmed. The algorithms can analyze the data, identify patterns, and make predictions or decisions based on that data.\nMachine learning is used in many applications such as image and speech recognition, natural language processing, recommendation systems, fraud detection, and many more."]
   
but the issue still remains the same.
==============================

Refer to Some of the solved errors- Looks like the issue is with generation - 
https://github.com/langchain-ai/langchain/issues/9923
With this, they fixed
generations.append([Generation(text=text["text"], generation_info=text)])

 I don't know if this helps me or not, I have talked to the Databricks team and they referred us to Langchain to post as an issue stating the above issue link.

**Comment by Prashantramappa** [comment]
FIXED- generations. append([Generation(text=text["candidates"][0])]) (because I stored output as candidates name) in the line langchain/libs/langchain/langchain/llms/base.py in the line 1004...it works.... please fix it so that next upcoming issues can be changed....looks like function should have input to pass based on their custom need.
https://github.com/langchain-ai/langchain/issues/9923 -- solution  helped

**Comment by Girrajjangid** [comment]
```python
from langchain.llms import Databricks

llm = Databricks(endpoint_name="mpt-7b-instruct-v6", model_kwargs={"max_new_tokens": 10})
llm("How are you?")
```
Here is the Error
```python
ValidationError                           Traceback (most recent call last)
File <command-4180369415271508>, line 4
      1 from langchain.llms import Databricks
      3 llm = Databricks(endpoint_name="mpt-7b-instruct-v6", model_kwargs={"max_new_tokens": 10})
----> 4 llm("How are you?")

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/llms/base.py:825, in BaseLLM.__call__(self, prompt, stop, callbacks, tags, metadata, **kwargs)
    818 if not isinstance(prompt, str):
    819     raise ValueError(
    820         "Argument `prompt` is expected to be a string. Instead found "
    821         f"{type(prompt)}. If you want to run the LLM on multiple prompts, use "
    822         "`generate` instead."
    823     )
    824 return (
--> 825     self.generate(
    826         [prompt],
    827         stop=stop,
    828         callbacks=callbacks,
    829         tags=tags,
    830         metadata=metadata,
    831         **kwargs,
    832     )
    833     .generations[0][0]
    834     .text
    835 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/llms/base.py:621, in BaseLLM.generate(self, prompts, stop, callbacks, tags, metadata, **kwargs)
    612         raise ValueError(
    613             "Asked to cache, but no cache found at `langchain.cache`."
    614         )
    615     run_managers = [
    616         callback_manager.on_llm_start(
    617             dumpd(self), [prompt], invocation_params=params, options=options
    618         )[0]
    619         for callback_manager, prompt in zip(callback_managers, prompts)
    620     ]
--> 621     output = self._generate_helper(
    622         prompts, stop, run_managers, bool(new_arg_supported), **kwargs
    623     )
    624     return output
    625 if len(missing_prompts) > 0:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/llms/base.py:523, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    521     for run_manager in run_managers:
    522         run_manager.on_llm_error(e)
--> 523     raise e
    524 flattened_outputs = output.flatten()
    525 for manager, flattened_output in zip(run_managers, flattened_outputs):

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/llms/base.py:510, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    500 def _generate_helper(
    501     self,
    502     prompts: List[str],
   (...)
    506     **kwargs: Any,
    507 ) -> LLMResult:
    508     try:
    509         output = (
--> 510             self._generate(
    511                 prompts,
    512                 stop=stop,
    513                 # TODO: support multiple run managers
    514                 run_manager=run_managers[0] if run_managers else None,
    515                 **kwargs,
    516             )
    517             if new_arg_supported
    518             else self._generate(prompts, stop=stop)
    519         )
    520     except (KeyboardInterrupt, Exception) as e:
    521         for run_manager in run_managers:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/llms/base.py:1004, in LLM._generate(self, prompts, stop, run_manager, **kwargs)
    998 for prompt in prompts:
    999     text = (
   1000         self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
   1001         if new_arg_supported
   1002         else self._call(prompt, stop=stop, **kwargs)
   1003     )
-> 1004     generations.append([Generation(text=text)])
   1005 return LLMResult(generations=generations)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-eb6651ff-b4bc-4caf-b63c-3f507671a21e/lib/python3.10/site-packages/langchain/load/serializable.py:75, in Serializable.__init__(self, **kwargs)
     74 def __init__(self, **kwargs: Any) -> None:
---> 75     super().__init__(**kwargs)
     76     self._lc_kwargs = kwargs

File /databricks/python/lib/python3.10/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
```

**Comment by mastercard-rob** [comment]
I've encountered the same issue. As a workaround I'm using the following code

```python
from langchain.llms import Databricks

def transform_output(response):
    return response['candidates'][0]['text']

llm = Databricks(endpoint_name="llama-2-7bn-chat-hf", 
                 transform_output_fn=transform_output,
                 verbose=True)

print(llm("why is the sky blue?"))
```
The transform_output function extracts the text from the response received from the API

**Comment by Blackkadder** [comment]
Getting same issue:
```python

llm = Databricks(host="xxxx.net",
    api_token= xxxxx,
    endpoint_name="llama_2_13b_hf_model_serving", 
    model_kwargs={"temperature": 0.000001})

agent = initialize_agent(
    llm=llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    tools=tools,
    prompt = prompt,
    handle_parsing_errors = True,
    early_stopping_method = 'generate'
)
```
Error
```
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

```

**Comment by pgaods** [comment]
I am also having the same issue. The Databricks embedding model works but not for Llama-2 and mixtral. I am using langchain 0.1 above:

```
from langchain_community.llms.databricks import Databricks
lc_llm=Databricks(endpoint_name="databricks-llama-2-70b-chat", databricks_uri="databricks", max_tokens=500, transform_output_fn=transform_output, verbose=True)
lc_llm("Who is beethoven")
```

**Comment by pgaods** [comment]
The error i receive is this:

`400 Client Error: Bad Request for url: https://eastus2-c2.azuredatabricks.net/serving-endpoints/databricks-llama-2-70b-chat/invocations. Response text: Bad request: json: unknown field "prompt"`

**Comment by srijitcn** [comment]
When you use chat models from Databricks foundation model in a chain, you need to use `ChatDatabricks` and `ChatPromptTemplate` api as below

```
from langchain.chat_models import ChatDatabricks
from langchain.prompts import ChatPromptTemplate

llm_model = ChatDatabricks(endpoint="databricks-llama-2-70b-chat",max_tokens = 200, temperature=0.1, )
prompt = ChatPromptTemplate.from_template("Follow the instruction: {question}")
```

**Comment by pgaods** [comment]
> When you use chat models from Databricks foundation model in a chain, you need to use `ChatDatabricks` and `ChatPromptTemplate` api as below
> 
> ```
> from langchain.chat_models import ChatDatabricks
> from langchain.prompts import ChatPromptTemplate
> 
> llm_model = ChatDatabricks(endpoint="databricks-llama-2-70b-chat",max_tokens = 200, temperature=0.1, )
> prompt = ChatPromptTemplate.from_template("Follow the instruction: {question}")
> 
> chain = LLMChain(
>     llm = llm_model_agent,
>     prompt = prompt_agent
> )
> 
> chain("Who is Beethoven")
> ```

Thank you, it worked!

**Comment by jeroaranda** [comment]
but can I use tools?
