### ISSUE TITLE
Issue: GPT4All LLM continue to generate undesired tokens even if stop attribute has been specified

### ISSUE THREAD

**Issue by ThibaultDef** [langchain-ai/langchain#10345]
### Issue you'd like to raise.

I was led to use GPT4All for building a personal chatbot. It generated undesired output. More precisely, it generates the all conversation, after writing the first prompt. For solving this problem, I instantiated GPT4All with a not empty list value for attribute `stop` : 

`
llm = GPT4All(
    model=local_path,
    callbacks=callbacks,
    verbose=True,
    streaming=True,
    stop=["System:"],
)
`

However, it continues to generate these undesired output. 

### Suggestion:

Finally I may have found a small fix to solve this problem for this type of LLM. I intent to create a PR very soon, if you agree with this.

**Comment by ThibaultDef** [comment]
@dosu-bot : Is there a specific format for branch title ?

**Comment by ThibaultDef** [comment]
Hello @baskaryan
It is a simple issue, but may be very useful to have.
Is it possible to check the related PR ?

**Comment by Mico52000** [comment]
I am encountering this issue while trying to develop a langchain react agent. I am setting the stop parameter  = ["Observation"] but to no avail, It never stops generating
