### ISSUE TITLE
DOC: What is the Difference between OpenAIAgent and agent=AgentType.OPENAI_FUNCTIONS

### ISSUE THREAD

**Issue by Hsgngr** [langchain-ai/langchain#10361]
### Issue with current documentation:

Overall there are so many terms on top of each other and I do understand we are trading off growing fast to having clean, set terms but lets discuss about currently what is the common way to define an AGENT that uses openAI for reasoning engine, and answers questions using tools that we define.

What is the AgentExecutor if we can also run agent.run()
What is AgentExecutorIterator

We can define an agent like this:
```
agent = initialize_agent(tools, llm, agent=AgentType.OPENAI_FUNCTIONS,
                         agent_kwargs=agent_kwargs, verbose=True, return_intermediate_steps=True,)
```

But also we can define an agent like this: [(From this documentation: Custom LLM Agent)](https://python.langchain.com/docs/modules/agents/how_to/custom_llm_agent)
```
llm = OpenAI(temperature=0)
llm_chain = LLMChain(llm=llm, prompt=prompt)

agent = LLMSingleActionAgent(
    llm_chain=llm_chain,
    output_parser=output_parser,
    stop=["\nObservation:"],
    allowed_tools=tool_names
)
```
There are also ChatAgent, OpenAIAgent and more[ Classes](https://js.langchain.com/docs/api/agents/classes/)

I would like to have a custom agent that I use with openai api and I will give custom tools like weather  functions or finance functions etc. What is the cleanest way to do this currently ? (8 September 2023)

**Comment by broven** [comment]
In my opinion, it's the same, read the initialize_agent code, you can see that `initialize_agent` just like a factory, initlize the agent and create agentExector for you
```python
def initialize_agent(
     ...
    agent: Optional[AgentType] = None,
    ...
) -> AgentExecutor:
  agent_cls = AGENT_TO_CLASS[agent]
  return AgentExecutor.from_agent_and_tools(
      agent=agent_obj,
      tools=tools,
      callback_manager=callback_manager,
      tags=tags_,
      **kwargs,
  )
```
