### ISSUE TITLE
Couldn't import BaseMessageConverter from 

### ISSUE THREAD

**Issue by mattthomps1** [langchain-ai/langchain#10377]
### System Info

Python 3.10.8 running on mac mini in VS Code

### Who can help?

@asai95 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

attempt to import basemessage converter following customer storage guide here - https://python.langchain.com/docs/integrations/memory/sql_chat_message_history

Enter from langchain.memory.chat_message_histories.sql import BaseMessageConverter
Actual behavior - ImportError: cannot import name 'BaseMessageConverter' from 'langchain.memory.chat_message_histories.sql' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/memory/chat_message_histories/sql.py)

### Expected behavior

Being able to import the BaseMessageConverter

**Comment by asai95** [comment]
Hey @mattthomps1 👋
Which langchain version did you install? This was added in 0.0.281.

**Comment by mattthomps1** [comment]
I feel dumb, that fixed it, thank you!  I'm stoked for this sql
integration, it's incredibly helpful.  Thanks for working on it!

Regards,

Matthew Thompson
202-641-4884

**Comment by mattthomps1** [comment]
@asai95 - thanks again, I got it to work but wanted to add some thoughts on the documentation that may help.  I'm new to programming but it was hard to figure out that SQLChatMessageHistory wasn't a memory object that I could use in a chain.  I got it to work with the below and wanted to offer in case it helps with the documentation: 

# Fictitious function that takes a user input and interview_id
def call_interview(user_input, interview_id):
    # Call the interview chain
    model_response = interview({
        "user_input": user_input
    })
    
    # Set up the db chat history
    session_id= interview_id
    chat_history = SQLChatMessageHistory(
        session_id= session_id,
        connection_string='your connection string',
        custom_message_converter=CustomMessageConverter(
            interview_id= interview_id
            )   
    )
    # Extract the 'text' from model_response
    response_text = model_response.get('text', '')
    
    # Add the chat messages to memory
    chat_history.add_user_message(user_input)
    chat_history.add_ai_message(response_text)
    print(chat_history)

    return model_response, respondent_id

**Comment by mattthomps1** [comment]
Actually I found an easier way - to the extent it helps, I finally saw that you could change the BaseChatMessageHistory in the memory object with the chat_memory variable.  I had to set the memory up in the function but it worked without needing to add in the messages later.  I'm glad I finally figured it out, this is really cool, much appreciated!

def call_sql_interview(user_input, interview_id, respondent_id=None):
    # Create respondent if there is none
    if respondent_id is None:
        with app.app_context():
            respondent_id = create_respondent()
    
    # Set up the db chat history
    session_id= f"{respondent_id}_{interview_id}"
    chat_history = SQLChatMessageHistory(
    session_id= session_id,
    connection_string='your connection string',
    custom_message_converter=CustomMessageConverter(
        respondent_id= respondent_id,
        interview_id= interview_id
        )   
    )
    memory = ConversationBufferMemory(memory_key="chat_history",return_messages=True, chat_memory=chat_history) 
    sql_interview = LLMChain(
        llm=llm,
        prompt=prompt,
        verbose=True,
        memory=memory
    )
    
    # Call the interview chain
    model_response = sql_interview({
        "user_input": user_input
    })

    print(chat_history)

    return model_response, respondent_id
