### ISSUE TITLE
Support for llama-cpp-python server

### ISSUE THREAD

**Issue by Avinash-Raj** [langchain-ai/langchain#10415]
### Feature request

Currently [llama-cpp-python](https://github.com/abetlen/llama-cpp-python#web-server) provides server package which acts like a drop-in replacement for the OpenAI API.

Is there any specific langchain LLM class which supports the above server or do we need to alter the existing `OpenAI` class with a different `openai_api_base` ?

### Motivation

I would like to have a dedicated machine or host which runs only the llama-cpp-python server wheres as the client which uses langchain should interact with just like we are doing with OpenAI.

### Your contribution

I would like to contribute but before that I need to check if there's any solution already available.

**Comment by Avinash-Raj** [comment]
@dosu-bot I don't want to use LlamaAPI  and the above mentioned `LlamaCppEmbeddings` class directly uses `llama-cpp-python` package not it's server. See, I don't want to include the model path anywhere in the codebase. Since I already have a server running with all the parameters defined.

**Comment by kicocisco** [comment]
> @dosu-bot I don't want to use LlamaAPI and the above mentioned `LlamaCppEmbeddings` class directly uses `llama-cpp-python` package not it's server. See, I don't want to include the model path anywhere in the codebase. Since I already have a server running with all the parameters defined.

I have been modifying the openai class with my own api location. It works OK, but I have not been successful in creating embeddings, have you tried such a thing?

**Comment by CarloNicolini** [comment]
You should do a number of things:
1. Follow [this](https://www.reddit.com/r/LocalLLaMA/comments/15ak5k4/short_guide_to_hosting_your_own_llamacpp_openai/
) guide. It explains how to modify the `api_like_OAI.py` file for the Llamacpp server example to strictly follow the same API like OpenAI:

Then you can *fake* OpenAI llm by replacing the address with your local address:

```python
os.environ[
        "OPENAI_API_KEY"
    ] = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # can be anything
os.environ["OPENAI_API_BASE"] = "http://localhost:8081/v1"
os.environ["OPENAI_API_HOST"] = "http://localhost:8081"
# TODO make it using a proper subclassing for this specialized object
llm = OpenAI(
    model_name="text-davinci-003",  # can be anything indeed
    temperature=temperature,
    openai_api_base="http://localhost:8081/v1",
    max_tokens=max_new_tokens,
    top_p=top_p,
    model_kwargs=dict(
        openai_key="sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        top_k=top_k,
    ),
    presence_penalty=0.0,
    n=1,
    best_of=1,
    batch_size=20,
    logit_bias={},
    streaming=True
)

**Comment by prakashex** [comment]
Hi @CarloNicolini , I have my llama2-chat model running using llama-cpp-python[server] , using the above solutions , I just have to use the OpenAI class , and  it should work right ?

**Comment by CarloNicolini** [comment]
> Hi @CarloNicolini , I have my llama2-chat model running using llama-cpp-python[server] , using the above solutions , I just have to use the OpenAI class , and it should work right ?

Yes it works but you need also to setup the OPENAI_API_KEY and OPENAI_API_HOST environment variables.

**Comment by dzianisv** [comment]
This worked for me
```python
from langchain_openai import OpenAI
OpenAI(openai_api_base=os.environ.get("LLAMACPP_API_ENDPOINT", "http://localhost:8080/"), openai_api_key="hello.world")
```

**Comment by chozillla** [comment]
I still have not gotten this to work. I ended up using the HTTP server from llama.cpp
