### ISSUE TITLE
CharacterTextSplitter doesn't break down text into specified chunk sizes

### ISSUE THREAD

**Issue by anihamde** [langchain-ai/langchain#10410]
### System Info

langchain version 0.0.285

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

CharacterTextSplitter has options for `chunk_size` and `chunk_overlap` but doesn't make use of them in the splitting. Though this is not technically erroneous, it is misleading given that a lot of the documentation shows CharacterTextSplitter with these arguments specified, implying that the class is creating desirably sized chunks when in reality it is not. Here is an [example](https://python.langchain.com/docs/integrations/vectorstores/activeloop_deeplake) of such documentation implying this.

Below is a code sample reproducing the problem. RecursiveCharacterTextSplitter works to reorganize the texts into chunks of the specified `chunk_size`, with chunk overlap where appropriate. Meanwhile, CharacterTextSplitter doesn't do this. You can observe the difference in the overlap behavior by printing out `texts_c` and `texts_rc`.

```
from langchain.schema.document import Document
from langchain.text_splitter import CharacterTextSplitter, RecursiveCharacterTextSplitter

doc1 = Document(page_content="Just a test document to assess splitting/chunking")
doc2 = Document(page_content="Short doc")
docs = [doc1, doc2]

text_splitter_c = CharacterTextSplitter(chunk_size=30, chunk_overlap=10)
text_splitter_rc = RecursiveCharacterTextSplitter(chunk_size=30, chunk_overlap=10)

texts_c = text_splitter_c.split_documents(docs)
texts_rc = text_splitter_rc.split_documents(docs)

max_chunk_c = max([ len(x.to_json()['kwargs']['page_content']) for x in texts_c])
max_chunk_rc = max([ len(x.to_json()['kwargs']['page_content']) for x in texts_rc])

print(f"Max chunk in CharacterTextSplitter output is of length {max_chunk_c}")
print(f"Max chunk in RecursiveCharacterTextSplitter output is of length {max_chunk_rc}")
```

### Expected behavior

Either remove the arguments from CharacterTextSplitter to avoid ambiguity, use RecursiveCharacterTextSplitter which performs the expected behavior of resizing into appropriately sized chunks, or add to CharacterTextSplitter a split_text function to perform the aforesaid expected behavior

**Comment by luizzappa** [comment]
The documentation and function definition need to be updated, I wasted a few hours trying to figure out why
`CharacterTextSplitter` was not generating chunks...

**Comment by hteeyeoh** [comment]
> The documentation and function definition need to be updated, I wasted a few hours trying to figure out why `CharacterTextSplitter` was not generating chunks...

Same here. Agree with that

**Comment by theb4rt** [comment]
> The documentation and function definition need to be updated, I wasted a few hours trying to figure out why `CharacterTextSplitter` was not generating chunks...

https://python.langchain.com/docs/modules/data_connection/document_transformers/character_text_splitter

Same problem, docs need to be updated

**Comment by shaojun** [comment]
@theb4rt update to what?could you clarify

**Comment by licaoyuan123** [comment]
The doc needs to be updated. If not specify the `chunk_size` and `chunk_overlap`, it will use the default parameters and generate large chunks.
For example, the below code can only get one chunk unless using the commented line.

`from langchain_text_splitters import  CharacterTextSplitter
import json

doc = """I am Superman.
You are Batman.
We are friends.
"""

text_splitter = CharacterTextSplitter(separator = "\n")
# text_splitter = CharacterTextSplitter(separator = "\n", chunk_size=1, chunk_overlap=0)


chunks = text_splitter.split_text(doc)
print(len(chunks))
for chunk in chunks:
	print(f"chunk: {chunk}")`
