### ISSUE TITLE
Is there a support for extracting images from pdf?

### ISSUE THREAD

**Issue by SuperJokerayo** [langchain-ai/langchain#10423]
### Feature request

Provide a parameter to determine whether to extract images from the pdf and give the support for it.

### Motivation

There may exist several images in pdf that contain abundant information but it seems that there is no support for extracting images from pdf when I read the code. 

### Your contribution

I'd like to add the feature if it is really lacking.

**Comment by octaviotastico** [comment]
This, and extracting tables would be very helpful!

**Comment by mhendy25** [comment]
Extracting images and graphical data from a PDF will be super handy!

**Comment by Claudio9701** [comment]
Using [Unstructured](https://unstructured.io) seems to be the solutions but if you rather implemented from scratch the steps could be:

1. Upload PDF and create text embeddings with metadata {contains_illustration: true | false}
2. Select PDF and pages with illustrations and convert them to PNG images with [pdf-img-convert.js](https://www.npmjs.com/package/pdf-img-convert)
3. Extract illustrations on the generated images using [a Detectron2 model fine-tuned on digitized books illustrations](https://huggingface.co/spaces/dbmdz/detectron2-model-demo)
4. Create image embeddings with [CLIP or a similar model](https://huggingface.co/docs/transformers/model_doc/clip)
