### ISSUE TITLE
keep min_seconds and max_seconds of create_base_retry_decorator configurable

### ISSUE THREAD

**Issue by divinajustin** [langchain-ai/langchain#10435]
### Feature request

Hi 
Currently, min_seconds and max_seconds of create_base_retry_decorator are hard-coded values. Can you please make these parameters configurable so that we can pass these values from AzureChatOpenAI similar to max_retries

eg:     llm = AzureChatOpenAI(
        deployment_name=deployment_name,
        model_name=model_name,
        max_tokens=max_tokens,
        temperature=0,
        max_retries=7,
        min_seconds=20,
        max_seconds=60
    )

### Motivation

Setting these values will help with RateLimiterror. Currently, these parameters need to be updated in the library files, which is impractical to set up in all deployed environments.

### Your contribution

NA

**Comment by ShantanuNair** [comment]
@hinthornw I had also suggested this over slack. Also curious if the docs for with_retry decorator are up? I'd be happy to give that a try

**Comment by justinian336** [comment]
I would also like this feature for embeddings. It's pointless to retry after 4 seconds when my rate-limited provider is telling me to retry after 43 seconds when my quota replenishes...
