### ISSUE TITLE
Could not parse tool input: {'name': 'AI_tool', 'arguments': 'What is a pre-trained chatbot?'} because the arguments is not valid JSON.

### ISSUE THREAD

**Issue by Prajith-mapview** [langchain-ai/langchain#10433]
### System Info

      I am using OpenAIFunctionsAgent  with langchain-0.0.285, parse tool input occurs frequently when provided an input

Could not parse tool input: {'name': 'AI_tool', 'arguments': 'What is a pre-trained chatbot?'} because the arguments is not valid JSON.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

     retriever = db.as_retriever()  # Milvus 

        tool = create_retriever_tool(
            retriever,
            "document_search_tool",
            "useful for answering questions related to XXXXXXXX."
        )

        tool_sales = create_retriever_tool(
            retriever,
            "sales_tool",
            "useful for answering questions related to buying or subscribing XXXXXXXX."
        )

        tool_support = create_retriever_tool(
            retriever,
            "support_tool",
            "useful for when you need to answer questions related to support humans on XXXXXXXX."
        )
        tools = [tool, tool_sales]

        llm = ChatOpenAI(model_name="gpt-3.5-turbo-0613", temperature=0.3)
        system_message = SystemMessage(
            content=(
                "You are a digital team member of XXXXXXXX Organization, specialising in XXXXXXXX."
                "Always respond and act as an office manager of XXXXXXXX, never referring to the XXXXXXXX "
                "as an external or separate entity. "
           
                "* Please answer questions directly from the context, and strive for brevity, keeping answers under 30 words."
                "* Convey information in a manner that's both professional and empathetic, embodying the values of XXXXXXXX."

            )
        )
        prompt = OpenAIFunctionsAgent.create_prompt(
            system_message=system_message,
            extra_prompt_messages=[MessagesPlaceholder(variable_name="chat_history")]
        )
        agent = OpenAIFunctionsAgent(llm=llm, tools=tools, prompt=prompt, verbose=True)

        memory = ConversationBufferWindowMemory(memory_key="chat_history", return_messages=True, k=6)
        agent_executor = AgentExecutor(
            agent=agent,
            tools=tools,
            memory=memory,
            verbose=True,
        )

      result = agent({"input": question, "chat_history": chat_history})
      answer = str(result["output"])

     print(answer)

### Expected behavior

i need to remove the error

**Comment by gargoyle777** [comment]
hi,
Bot is right, i had the same problem.
Too much python and we forgot that ' !="

**Comment by aarzoov** [comment]
it is relevant, i get this error 
Could not parse tool input: {'arguments':}

**Comment by shamussim-ai** [comment]
I get a similar error
**Error**
```   > Entering new AgentExecutor chain...
Could not parse tool input: {'arguments': "{'__arg1': 'acne treatment for male teenagers around the age of 12 years old'}", 'name': 'BingSearch'} because the `arguments` is not valid JSON.Invalid or incomplete response
Invoking: `BingSearch` with `acne treatment for male teenagers around the age of 12 years old`
```
After that I also get a HTTP error but I think thats a result of this first error
```
----> [1](vscode-notebook-cell:?execution_count=94&line=1) result = agent_executor.invoke({"What other forms of acne treatment are there for male teenagers around the age of 12 years old ?"})  

HTTPError: 404 Client Error: Resource Not Found for url: https://api.bing.microsoft.com/?q=acne+treatment+for+male+teenagers+around+the+age+of+12+years+old&count=10&textDecorations=True&textFormat=HTML
```

**Code to Reproduce**
```from langchain.retrievers import PubMedRetriever
from langchain_community.document_loaders import PubMedLoader

retriever =PubMedRetriever()
from langchain_community.utilities import BingSearchAPIWrapper
search = BingSearchAPIWrapper()

tools= [
    Tool(
        name="PubMedSearch",
        func=retriever.invoke,
        description="useful for when you need to answer questions about current events"
    ),
    Tool(
        name="BingSearch",
        func=search.run,
        description="Bing Search API"
    )
]
memory_key = "history"

from langchain.agents.openai_functions_agent.agent_token_buffer_memory import (
    AgentTokenBufferMemory,
)

memory = AgentTokenBufferMemory(memory_key=memory_key, llm=model, max_token_limit = 13000)

from langchain.agents.openai_functions_agent.base import OpenAIFunctionsAgent
from langchain.prompts import MessagesPlaceholder
from langchain_core.messages import SystemMessage
system_message = SystemMessage(
    content=(
        "You are an expert Doctor."
        "Use the web search tool to gain insights from web search"        
    )
)

prompt = OpenAIFunctionsAgent.create_prompt(
    system_message=system_message,
    extra_prompt_messages=[MessagesPlaceholder(variable_name=memory_key)],
)

#The Agent
agent = OpenAIFunctionsAgent(llm=model, tools=tools, prompt=prompt)

#The Agent Executor
from langchain.agents import AgentExecutor
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=memory,
    verbose=True,
    return_intermediate_steps=True,
    handle_parsing_errors=True
)

result = agent_executor.invoke({"What is the recommended dose of doxycycline?"})```

**Setup**
Windows 10
