### ISSUE TITLE
DOC: Include instructions for Weaviate Schema Configuration

### ISSUE THREAD

**Issue by RoderickVM** [langchain-ai/langchain#10438]
### Issue with current documentation:

The current [Weaviate documentation](https://python.langchain.com/docs/integrations/providers/weaviate) in LangChain doesn't include instructions for setting up Weaviate's Schema to integrate it properly with LangChain. This will prevent any future issues like this one: #10424

### Idea or request for content:

Include in the documentation a reference to [Weaviate Auto-Schema](https://weaviate.io/developers/weaviate/config-refs/schema#auto-schema), explaining this is the default behavior when a `Document` is loaded to a Weaviate vectorstore. Also, give examples of how the Schema JSON file can be adjusted to work without problems with LangChain.

**Comment by VpkPrasanna** [comment]
I would like to raise a PR for this issue , can the maintaner point me to where to put the docs?
