### ISSUE TITLE
Warning using SQLRecordManager

### ISSUE THREAD

**Issue by RoderickVM** [langchain-ai/langchain#10439]
### System Info

LangChain version: 0.0.285
Python version: 3.11.2
Platform: x86_64 Debian 12.2.0-14
Weaviate 1.21.2 as vectorstore

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Following the instructions [here](https://python.langchain.com/docs/modules/data_connection/indexing#quickstart), 

`from langchain.indexes import SQLRecordManager, index` returns the following warning:
```
/lib/python3.11/site-packages/langchain/indexes/_sql_record_manager.py:38: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()
```
LangChain's [indexes documentation](https://api.python.langchain.com/en/latest/api_reference.html#module-langchain.indexes) doesn't include `SQLRecordManager`. Additionally, `RecordManager` [documentation ](https://api.python.langchain.com/en/latest/indexes/langchain.indexes.base.RecordManager.html#langchain-indexes-base-recordmanager)doesn't mention it can be used with SQLite.

### Expected behavior

No warnings.

**Comment by kientv** [comment]
@RoderickVM I get same issue like you:

>   record_manager.update(
>   File ".../venv/lib/python3.11/site-packages/langchain/indexes/_sql_record_manager.py", line 269, in update
>     update_time = self.get_time()
> 

Did you solve this issue?
