### ISSUE TITLE
DOC: Supabase Vector self-querying

### ISSUE THREAD

**Issue by tleyden** [langchain-ai/langchain#10444]
### Issue with current documentation:

It does not list `tiktoken` as a dependency, and while trying to run the code to create the  `SupabaseVectorStore.from_documents()`, I got this error:

```
ImportError: Could not import tiktoken python package. This is needed in order to for OpenAIEmbeddings. Please install it with `pip install tiktoken`.

```

### Idea or request for content:

Add a new dependency to `pip install tiktoken`

cc @gregnr

**Comment by leo-gan** [comment]
@tleyden Please, provide an URL of the failed page.
I've found this https://python.langchain.com/docs/modules/data_connection/retrievers/self_query/supabase_self_query 
But it has this `pip install tiktoken` line.

**Comment by tleyden** [comment]
It was fixed yesterday in https://github.com/langchain-ai/langchain/pull/10452 - thanks for taking a look!
