### ISSUE TITLE
BedrockChat model mistakenly removed in latest version?

### ISSUE THREAD

**Issue by kaleko** [langchain-ai/langchain#10468]
### System Info

It looks like BedrockChat was removed from the chat_models/__init__.py when ChatKonko was added in this commit: https://github.com/langchain-ai/langchain/pull/10267/commits/280c1e465c4b89c6313fcc2c0679e3756b8566f9#diff-04148cb9262d722a69b81a119e1f8120515532263a1807239f60f00d9ff2a755

I'm guessing this was accidental, because the BedrockChat class definitions still exist.

@agola11 @hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

.

### Expected behavior

I expect `from langchain.chat_models import BedrockChat` to work

**Comment by devstein** [comment]
@kaleko Dosu mispoke. It can't make PRs (yet). I agree this looks like a mistake! Are you able to make a PR to fix?

**Comment by 3coins** [comment]
@kaleko 
Can you plz close this issue, if the import has been fixed.
