### ISSUE TITLE
Issue: Error in LangChainTracerV1.on_chain_end callback: Unknown run type:

### ISSUE THREAD

**Issue by moayadeldin** [langchain-ai/langchain#10460]
I am trying to trace my LangChain runs by using LangChain Tracing Native Support on my local host, I created a session named agent_workflow and tried to receive the runs on it but it didn't work.

The problem is that whenever I run the RetrievalQA chain it gives me the following error:
`Error in LangChainTracerV1.on_chain_end callback: Unknown run type: retriever`

This is the code snippet specifying the problem:

```
os.environ["LANGCHAIN_TRACING"] = "true"
os.environ["LANGCHAIN_SESSION"] = "agent_workflow"
embed = OpenAIEmbeddings(
    model=self.embedding_model_name
)

vectorStore = Chroma.from_documents(texts,embed)

 def retrieval(self,question):

      qa = RetrievalQA.from_chain_type(
          llm,
          chain_type="stuff",
          retriever= vectorStore.as_retriever(k=1),
          verbose=True,
          chain_type_kwargs={
              "verbose":True,
              "prompt":prompt,
              "memory": memory,
          }
      )
      
      with get_openai_callback() as cb:
             response = qa.run({"query":question})
  
      return qa.run({"query":question})
```
How can I solve this? I saw a tutorial where it worked with initialized_agent instead of RetrievalQA but don't know whether this is the case or not.

**Comment by moayadeldin** [comment]
@dosu-bot 

I tried your solution and changed the _on_chain_end function in the source code as you told me but the same error exactly existed, which was: Error in LangChainTracerV1.on_chain_end callback: Unknown run type: retriever

Think about the problem step by step as why this is happening and how to avoid it, then provide the solution

**Comment by dsaks9** [comment]
Not exactly sure why this is the case, and i'm pivoting to another solution so won't be looking into this any further at the moment, but I run into the same error when executing my chain(s) via a python script in the terminal but it seems to work when I execute the code in a jupyter notebook.
