### ISSUE TITLE
Issue: Which version of langchain supports the elasticsearch 7.6

### ISSUE THREAD

**Issue by eswarthammana** [langchain-ai/langchain#10481]
### Issue you'd like to raise.

Hi Team,

I have a fixed elasticsearch version 7.6 which i cannot upgrade. could you please share me some details about which version of langchain supports mentioned version.

Problem with the latest langchain i have faced, similarity search or normal search says that KNN is not available. "Unexpected keyword argument called 'knn'".

if possible please share a sample code to connect with the existing elastic search and create an index to update the Elasticsearch data to Lang chain supported data format or document format.

**Comment by eswarthammana** [comment]
@dosu-bot

> _🤖_
> 
> Hi,
> 
> Based on the information I found in the LangChain repository, the minimum version of Elasticsearch that LangChain supports is 8.9.0. This is specified in the docker-compose file under the services section for Elasticsearch, where the image is specified as `docker.elastic.co/elasticsearch/elasticsearch:8.9.0` [source](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/tests/integration_tests/vectorstores/docker-compose/elasticsearch.yml).
> 
> Regarding the issue you're facing with the 'knn' keyword, it seems like a similar issue was resolved in the past. The issue was titled ["Can't use the ElasticVectorSearch store with the provided notion q-a example"](https://github.com/langchain-ai/langchain/issues/829). The solution involved changes in the `index` method of the `ElasticsearchStore` class and the `__init__` method of the same class. You can find the detailed changes in the issue discussion.
> 
> Unfortunately, as your Elasticsearch version is 7.6, it's not supported by the current version of LangChain. You might face compatibility issues or missing features, as you've already experienced with the 'knn' keyword.
> 
> As for the sample code to connect with Elasticsearch and create an index, you can refer to the `ElasticsearchStore` class in the LangChain codebase [here](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/elasticsearch.py). However, please note that this code is designed to work with Elasticsearch 8.9.0 and may not work as expected with version 7.6.
> 
> I hope this information helps. If you have any other questions or need further clarification, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [Can't use the ElasticVectorSearch store with the provided notion q-a example](https://github.com/langchain-ai/langchain/issues/829)
> * [libs/langchain/langchain/vectorstores/elasticsearch.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/elasticsearch.py)
> * [libs/langchain/tests/integration_tests/vectorstores/docker-compose/elasticsearch.yml](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/tests/integration_tests/vectorstores/docker-compose/elasticsearch.yml)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

After modify the ElasticSearchStore with strategy as ExactRetrievalStrategy, i am able to solve the KNN issue, this strategy doesn't involve KNN.

But now i am facing another issue which is elastic search connection exception as "failed to establish a new connection: (errno 11001) getaddrin" . In the ElasticSearchStore i am using es_connection with the existing elastic search connection.

**Comment by eswarthammana** [comment]
@dosu-bot

But now i am facing the following exception which i mentioned above.

elastic search connection exception as "failed to establish a new connection: (errno 11001) getaddrin" . In the ElasticSearchStore i am using es_connection with the existing elastic search connection.

how can i fix this issue...

**Comment by eswarthammana** [comment]
@dosu-bot

python: 3.10.x
langchain: 0.0.287
elasticsearch: 7.12.0

Following is the code i am using to connect Langchain with Elasticsearch and perform similarity search.

`es_connection = Elasticsearch("http://localhost:8500")

vectorstore = ElasticsearchStore(
    embedding=OpenAIEmbeddings(),
    index_name="movieratings",
    es_connection="http://localhost:9500"
)

print(vectorstore.similarity_search('koyla'))`

But the above code throws exception as "AttributeError: 'str' object has no attribute 'search'"

Please share a solution to fix the issue.

**Comment by eswarthammana** [comment]
@dosu-bot

Here is the traceback you have requested

Traceback (most recent call last):
  File "C:\xxxx\AI\langchain\es_langchain.py", line 21, in <module>
    print(vectorstore.similarity_search('koyla'))
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 592, in similarity_search
    results = self._search(query=query, k=k, filter=filter, **kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 683, in _search
    response = self.client.search(
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\elasticsearch\client\utils.py", line 153, in _wrapped    
    return func(*args, params=params, headers=headers, **kwargs)
TypeError: Elasticsearch.search() got an unexpected keyword argument 'query'

**Comment by joemcelroy** [comment]
Hi there,

By default `ElasticVectorStore` uses brute force. You should be able to use the [ExactRetrievalStrategy](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#exactretrievalstrategy) which relies on script score rather than knn.

Joe

**Comment by eswarthammana** [comment]
@dosu-bot @joemcelroy 

python: 3.10.x version
langchain: 0.0.287 version
elasticsearch py: 7.12.0 version
ES: 7.6 version

I am following the steps mentioned in the [link](https://python.langchain.com/docs/use_cases/question_answering/).
Thanks for the reply. I am using ExactRetrievalStrategy as mentioned in the below code.

`import os
from langchain.document_loaders import WebBaseLoader
from elasticsearch import Elasticsearch

loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
data = loader.load()

from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size = 500, chunk_overlap = 0)
all_splits = text_splitter.split_documents(data)

from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import ElasticsearchStore

vectorstore = ElasticsearchStore.from_documents(
    documents=all_splits, 
    embedding=OpenAIEmbeddings(),
    index_name="posts",
    es_url="http://localhost:8500",
    strategy=ElasticsearchStore.ExactRetrievalStrategy()
)

question = "What are the approaches to Task Decomposition?"
docs = vectorstore.similarity_search(question)
print(len(docs))`


Following is the exception i have received

> Traceback (most recent call last):
>   File "C:\xxxx\AI\langchain\langchain_example_1.py", line 28, in <module>
>     docs = vectorstore.similarity_search(question)
>   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 592, in similarity_search
>     results = self._search(query=query, k=k, filter=filter, **kwargs)
>   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\vectorstores\elasticsearch.py", line 683, in _search
>     response = self.client.search(
>   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\elasticsearch\client\utils.py", line 153, in _wrapped    
>     return func(*args, params=params, headers=headers, **kwargs)
> TypeError: Elasticsearch.search() got an unexpected keyword argument 'query' 

In the above code, able to retrieve the web data, split the data and converted to Documents. While creating a new index i faced a problem replated to Mappings, so i created a new index using postman, then data insertion and Embeddings created. Now while retrieve or search, looks the query buildup is having some problem.
please share your suggestions.

**Comment by joemcelroy** [comment]
its really tough with ES 7.6 (a version released over 3 years ago) - which elasticsearch client have you installed? The complaint here is that the keyword query isn't supported which i assume you're using the ES 7.x client here which doesn't support it. 

Possibly use 8.x client and see what happens.

**Comment by eswarthammana** [comment]
@dosu-bot @joemcelroy 

After i have created an index using postman, 

With the below [code ref](https://python.langchain.com/docs/use_cases/question_answering/)

`from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import ElasticsearchStore

vectorstore = ElasticsearchStore.from_documents(
documents=all_splits,
embedding=OpenAIEmbeddings(),
index_name="posts",
es_url="http://localhost:8500/",
strategy=ElasticsearchStore.ExactRetrievalStrategy()
)`

I am assuming the Mapping created is having some problem 

> 
Caused by: java.lang.ClassCastException: class org.elasticsearch.index.fielddata.ScriptDocValues$Doubles cannot be cast to class org.elasticsearch.xpack.vectors.query.VectorScriptDocValues$DenseVectorScriptDocValues (org.elasticsearch.index.fielddata.ScriptDocValues$Doubles is in unnamed module of loader 'app'; org.elasticsearch.xpack.vectors.query.VectorScriptDocValues$DenseVectorScriptDocValues is in unnamed module of loader java.net.FactoryURLClassLoader @24934262)

In the below image the vector is created as float, is this what we expected?

![float image](https://github.com/langchain-ai/langchain/assets/23114153/7ecb2359-e555-4fda-9605-c02bad40e6e6)

Vector data in the elastic search 

![vector](https://github.com/langchain-ai/langchain/assets/23114153/23d67330-7317-4b42-8fb7-0a65560e27a4)

Any suggestions

**Comment by joemcelroy** [comment]
Needs to be declared as a dense_vector field, not a float. https://www.elastic.co/guide/en/elasticsearch/reference/7.6/dense-vector.html#dense-vector

**Comment by joemcelroy** [comment]
The query is the tough part as it’s calling on a method signature which isn’t supported by the 7.x client. I don’t have a better suggestion to overcome that issue other than upgrading.

**Comment by eswarthammana** [comment]
@dosu-bot @joemcelroy 

> python: 3.10.x version
> langchain: 0.0.287 version
> elasticsearch py: 7.12.0 version
> ES: 7.6 version

After performing some minor modification at the langchain python module. we are able to create an index, mappings, insertion of vector data and also perform search. I tested only for ExactRetrievalStrategy strategy. Following are the changes avaialble.

**Change 1**
#change of index inside the strategy by removing the index=False

> source: from langchain.vectorstores import ElasticsearchStore
> index function of ElasticsearchStore.ExactRetrievalStrategy()
> update the return by removing index = False

below is the updated code

`return {
            "mappings": {
                "properties": {
                    vector_query_field: {
                        "type": "dense_vector",
                        "dims": dims_length
                    },
                }
            }
        }`

**Change 2**
#Elasticsearchstore modify the private function _create_index_if_not_exists, body = indexSettings

> source: from langchain.vectorstores import ElasticsearchStore
> modify the index creation argument with parameter reference rather keyword arguments

after modification

`self.client.indices.create(index=index_name, body=indexSettings)`

**Change 3**
#Remove source=fields, for self.client.search in Elasticsearchstore private function _search

source: from langchain.vectorstores import ElasticsearchStore
modify the private function _search by removing the source=fields 

after modification
`response = self.client.search(
            index=self.index_name,
            body=query_body,
            size=k,
        )`

please confirm the last modification, what is the purpose of source=fields, i could see metadata updates in the fields parameter, will it cause any problem?

**Comment by joemcelroy** [comment]
> please confirm the last modification, what is the purpose of source=fields, i could see metadata updates in the fields parameter, will it cause any problem?

Source specifies the fields that are returned in the response for each hit. For Langchain, that will be the query field and metadata field + any additional fields the user is interested in.
