### ISSUE TITLE
Issue: Use huggingface_hub InferenceClient instead of InferenceAPI

### ISSUE THREAD

**Issue by teckick** [langchain-ai/langchain#10483]
### Issue you'd like to raise.

Langchain is still using the deprecated huggingface_hub `InferenceApi` in the latest version. the `InferenceApi` will be removed from version '0.19.0'.

```
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_deprecation.py:127: FutureWarning: '__init__' (from 'huggingface_hub.inference_api') is deprecated and will be removed from version '0.19.0'. `InferenceApi` client is deprecated in favor of the more feature-complete `InferenceClient`. Check out this guide to learn how to convert your script to use it: https://huggingface.co/docs/huggingface_hub/guides/inference#legacy-inferenceapi-client.
  warnings.warn(warning_message, FutureWarning)
```

### Suggestion:

It it recommended to use the new `InferenceClient` in huggingface_hub.

**Comment by keenborder786** [comment]
okay, I will work on this one.

**Comment by SamirCitric** [comment]
Does this mean its not possible to use langchain anymore?

**Comment by dosuken123** [comment]
@SamirCitric It's still possible to use langchain with HB models. It's just the client langchain using was deprecated and we need to move to a new one. https://huggingface.co/docs/huggingface_hub/guides/inference#legacy-inferenceapi-client
