### ISSUE TITLE
Redis vector  init error

### ISSUE THREAD

**Issue by scorpiord** [langchain-ai/langchain#10487]
### System Info

Langchain:0.0.286
python:3.10.10
redis:5.0.0b4

### Who can help?

@hwc

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

rds = Redis.from_texts(
    texts,
    embeddings,
    metadatas=metadata,
    redis_url="XXXXX",
    index_name="XXXX"
)
The following exception occurred：
AttributeError: 'RedisCluster' object has no attribute 'module_list'

The version of my redis package is 5.0.0b4.

An error occurred in the following code：

langchain\Lib\site-packages\langchain\utilities\redis.py

def check_redis_module_exist(client: RedisType, required_modules: List[dict]) -> None:
    """Check if the correct Redis modules are installed."""
-> installed_modules = client.module_list()

### Expected behavior

redis init success

**Comment by Spartee** [comment]
Ok so a couple things about this error

```
)
The following exception occurred：
AttributeError: 'RedisCluster' object has no attribute 'module_list'

The version of my redis package is 5.0.0b4.

An error occurred in the following code：

langchain\Lib\site-packages\langchain\utilities\redis.py

def check_redis_module_exist(client: RedisType, required_modules: List[dict]) -> None:
"""Check if the correct Redis modules are installed."""
-> installed_modules = client.module_list()
```


1. You need to update Redis. 5.0 is very out of date. So out of date our check doesn't even come back haha
2. Are you using Redis Stack? ``docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest``

**Comment by Spartee** [comment]
AHH apologies, confusing naming. I though you meant your redis-server version was 5.0. I should've read more closely

Are you using Redis Stack?

**Comment by Spartee** [comment]
This problem commonly occurs for those who are using Elasticache and think it has the same functionality. It does not.

**Comment by scorpiord** [comment]
> Redis Stack

thank you for your reply。Yes，I'm using Redis Stack

**Comment by ewpreston** [comment]
What version of Redis server are you running? You can use the INFO command from redis-cli attached to the Redis database. It's the first item in the response.

**Comment by scorpiord** [comment]
> INFO

> INFO
# Server
redis_version:9.0.30
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:2029-05-30 16:00:00
redis_mode:cluster
os:Linux 4.18.0-305.el8.x86_64 x86_64

In 5.0.0b4 redis package:
The 【module_list】 method is defined in 【redis.commands.core.ModuleCommands】
But, class RedisCluster(AbstractRedisCluster, RedisClusterCommands) do not extends ModuleCommands
So the error happens

**Comment by scorpiord** [comment]
> What version of Redis server are you running? You can use the INFO command from redis-cli attached to the Redis database. It's the first item in the response.

redis_version:9.0.30
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:2029-05-30 16:00:00
redis_mode:cluster
os:Linux 4.18.0-305.el8.x86_64 x86_64

In 5.0.0b4 redis package:
The 【module_list】 method is defined in 【redis.commands.core.ModuleCommands】
But, class RedisCluster(AbstractRedisCluster, RedisClusterCommands) do not extends ModuleCommands
So the error happens

**Comment by ewpreston** [comment]
I'm very confused. The most recent version of Redis is 7.2. Can you download the latest redis stack from docker hub and try that?

docker run -d --name my-redis-stack -p 6379:6379 redis/redis-stack:latest

**Comment by scorpiord** [comment]
> I'm very confused. The most recent version of Redis is 7.2. Can you download the latest redis stack from docker hub and try that?
> 
> docker run -d --name my-redis-stack -p 6379:6379 redis/redis-stack:latest

Sorry, version 9 is our own customized version with additional layers. The underlying Redis version is 6.2.

**Comment by scorpiord** [comment]
> I'm very confused. The most recent version of Redis is 7.2. Can you download the latest redis stack from docker hub and try that?
Sorry, version 9 is our own customized version with additional layers. The underlying Redis version is redis 6.2.13.
 
> docker run -d --name my-redis-stack -p 6379:6379 redis/redis-stack:latest
We have installed Redisearch on a Redis cluster, not on a single node.

client = get_client(redis_url=redis_url, **kwargs)
# check if redis has redisearch module installed
check_redis_module_exist(client, REDIS_REQUIRED_MODULES)
When the redis is a cluster,the【get_client】method gets a instance of instance RedisCluster, not a instance of  Redis which extends 【redis.commands.core.CoreCommands】
I think this is why the error happens

**Comment by scorpiord** [comment]
> So, version 6.2.13 doesn't support Vector Similarity Search. You'll need 6.4.x and ensure you have the search module installed as well. 

Our redis has installed search module. Running commands like ft.search techDoc "Redis" in redis-cli can also return correct results.Do I have to upgrade version from 6.2.13 to 6.4.x?

>Please try it on the Redis Stack first, so validate that the code does work. Getting the right version of Redis installed is key here.
 On redis installed through the command 【docker run -d --name my-redis-stack -p 6379:6379 redis/redis-stack:latest】,the code is ok.But I think the reason is that redis_mode is standalone.Have you tried running the code in a cluster?

**Comment by Spartee** [comment]
@scorpiord To my knowledge, RediSearch doesn't work in a cluster today. That's when people (usually companies) use Redis Cloud or Redis Enterprise since they both support that.
