### ISSUE TITLE
Elasticsearch ELSER Timeout

### ISSUE THREAD

**Issue by DrSebastianK** [langchain-ai/langchain#10506]
### System Info

Python 3.10.12
Google Colab
Elasticsearch Cloud 8.9.2
Langchain - latest

### Who can help?

@hwchase17 @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps:

1. Load list of documents
2. Setup ElasticsearchStore of Langchain, with appropriate ES cloud credentials
3. Successfully create index with custom embedding model (HF embedding model, deployed on colab)
4. Deploy ELSER model and run it (with default model id).
5. Try creating index with SparseVectorRetrievalStrategy (ELSER) over the same list of documents.
6. Tried to change timeout, but didn't effect the outcome.
7. NOTE: It does start uploading docs and docs count is increasing, but it stops after about 10 sec. I tried to run the ELSER model on 3 nodes, but nothing changed.

### Expected behavior

WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode([https://-------.us-central1.gcp.cloud.es.io:443](https:/------.us-central1.gcp.cloud.es.io/))> has failed for 1 times in a row, putting on 1 second timeout
---------------------------------------------------------------------------
ConnectionTimeout                         Traceback (most recent call last)
[<ipython-input-92----------cb>](https://-------colab.googleusercontent.com/outputframe.html?vrz=colab_20230911-060143_RC00_564310758#) in <cell line: 1>()
----> 1 elastic_elser_search = ElasticsearchStore.from_documents(
      2     documents=split_texts,
      3     es_cloud_id="cloudid",
      4     index_name="search-tmd-elser",
      5     es_user="elastic",

10 frames
[/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py](https://---XXXX-----0-colab.googleusercontent.com/outputframe.html?vrz=colab_---XXXX-----#) in perform_request(self, method, target, body, headers, request_timeout)
    197                 exception=err,
    198             )
--> 199             raise err from None
    200 
    201         meta = ApiResponseMeta(

ConnectionTimeout: Connection timed out

**Comment by joemcelroy** [comment]
Thanks for report. ELSER is taking a while to transform the text so the bulk import is timing out. I will add a feature to allow the developer to change the default "chunk" batch size from 500 so that it reduces hitting the timeout.

**Comment by DrSebastianK** [comment]
Thanks for the response. I am looking forward to using this feature.

**Comment by joemcelroy** [comment]
@DrSebastianK within 303, you can now pass in bulk args when ingesting documents, to reduce hitting the timeout. See [documentation](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#question-im-getting-timeout-errors-when-indexing-documents-into-elasticsearch-how-do-i-fix-this) on how to do this 😀
