### ISSUE TITLE
Support jinja2 template format when using ChatPromptTemplate.from_template_file

### ISSUE THREAD

**Issue by mep-um** [langchain-ai/langchain#10519]
### Feature request

BaseStringMessagePromptTemplate.from_template supports the template_format variable, while BaseStringMessagePromptTemplate.from_template_file does not.

### Motivation

All supported template formats (including Jinja2) should be supported by all template loaders equally.

### Your contribution

I'm not experienced enough with the Langchain codebase to submit PRs at this time.

**Comment by HTahboub** [comment]
Are you sure you are referring to the right class? It does not seem that `ChatPromptTemplate` has a method called `from_template_file`. Maybe you meant `ChatMessagePromptTemplate`?

**Comment by mep-um** [comment]
Correct. I've updated my comment to reflect that change.

**Comment by HTahboub** [comment]
Well, the only use of the `template_format` parameter in the `from_template` method is to figure out the input variables, but `from_template_file` actually takes those in as a parameter, so there's no use for a `template_format` parameter here.

**Comment by HTahboub** [comment]
From what I can tell, the outcome would be the exact same in both cases if you pass in the correct `input_variables` and specify the `template_format` as a kwarg so that it gets passed onto the class. However, I think you are right as far as that it's a bit counterintuitive as it is. There doesn't seem to be a good reason for these methods to be implemented differently.

**Comment by lvieirajr** [comment]
Any updates on this issue? it actually breaks in the case you have a for loop and you are trying to use this, even when passing the input variables, unless I'm missing something on how this is used.

Here is a screenshot with an example:
<img width="1434" alt="Screenshot 2023-10-07 at 3 25 34 AM" src="https://github.com/langchain-ai/langchain/assets/283394/1d1125a2-ead6-4517-bddf-9200826ec8e3">
