### ISSUE TITLE
Opensearch metadata_field and metadata_filter not working

### ISSUE THREAD

**Issue by abhinavmishra05** [langchain-ai/langchain#10524]
### System Info

langchain version = 0.0.281 
python =  3.11
opensearch-py = 2.3.0

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am trying to do metadata based filtering alongside the query execution using `OpensearchVectorSearch.similarity_search()`. But when I use `metadata_field` and `metadata_filter`, the search doesn't seems to take that into account and still returns results outside of those filters.

Here is myr code:

`response = es.similarity_search( query = "<sample query text>", K =4, metadata_field = "title", metadata_filter = {"match":{"title": "<sample doc title>}}, )`

Here `es` is the `OpenSearchVectorSearch` object for `index1`

The output structure is like this:
`[Document(page_content = ' ', metadata={'vector_field' : [], 'text' : ' ', 'metadata' : {'source' : ' ', 'title' : ' ' }})]`

Here the title I see is not the title I specified in my query.

Steps to reproduce:

1. Create an Opensearch index with multiple documents.
2. Run similarity_search() query with a metadata_field and/or metadata_filter

### Expected behavior

The query should be run against the specified `metadata_field` and `metadata_filter` and in output, I should only see the correct document name I specified in `metadata_field` and `metadata_filter`

**Comment by abhinavmishra05** [comment]
So, if I want to execute my query against a set of documents in my index and not all the documents, how would I go about executing that query using the metadata_field parameter in `max_marginal_relevance_search()` ? Is this supported through `OpensearchVectorSearch`? assume that the `metadata_field` is named `title` and value of `title` is present in a list.

**Comment by abhinavmishra05** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for bringing this issue to our attention. Based on the information you've provided and the context from the LangChain repository, it appears that the `similarity_search()` function in the `OpenSearchVectorSearch` class of LangChain does not directly handle the `metadata_field` and `metadata_filter` parameters. These parameters are not mentioned in the function's signature or its body.
> 
> However, the `metadata_field` parameter is used in the `max_marginal_relevance_search()` function of the same class. This function uses `metadata_field` to access the metadata of the search results. The `metadata_filter` parameter is not used in any of the provided code.
> 
> Therefore, if you're trying to use `metadata_field` and `metadata_filter` parameters with the `similarity_search()` function, it might not work as expected because these parameters are not handled within this function.
> 
> As for your question about any changes or updates in the `similarity_search()` function from version 0.0.281 to the latest version (v0.0.287), I wasn't able to find any specific changes related to this function in the repository. However, it's possible that there might be changes or updates that I might have missed.
> 
> I hope this information helps. If you have any further questions or need additional clarification, please don't hesitate to ask.
> 
> ## Sources
> * [libs/langchain/langchain/vectorstores/chroma.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/chroma.py)
> * [libs/langchain/langchain/vectorstores/faiss.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/faiss.py)
> * [libs/langchain/langchain/vectorstores/annoy.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/annoy.py)
> * [libs/langchain/langchain/vectorstores/mongodb_atlas.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/mongodb_atlas.py)
> * [libs/langchain/langchain/vectorstores/opensearch_vector_search.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/opensearch_vector_search.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

So, if I want to execute my query against a set of documents in my index and not all the documents, how would I go about executing that query using the `metadata_field` parameter in `max_marginal_relevance_search()` ? Is this supported through OpensearchVectorSearch? assume that the metadata_field is named title and value of title is present in a list.

**Comment by ahaseeb1997** [comment]
Hi @abhinavmishra05 

Were you able to fix this?
I'm having the same issue, I want to filter out the documents on the basis of metadata. This functionality is available in case of PGVector but I think it's not available for OpenSearch.

**Comment by ahs8w** [comment]
It's still unclear if this is fixed.  When I try to run a query with a filter:
```
filter = {"bool": {"filter": {"match": {"metadata.section_title": "<filter>"}}}}

vectorstore.similarity_search(
    "<query>",
    k=5,
    pre_filter=filter,
)
```

The filter is completely ignored.

**Comment by silva-fabiofreitas** [comment]
> It's still unclear if this is fixed. When I try to run a query with a filter:
> 
> ```
> filter = {"bool": {"filter": {"match": {"metadata.section_title": "<filter>"}}}}
> 
> vectorstore.similarity_search(
>     "<query>",
>     k=5,
>     pre_filter=filter,
> )
> ```
> 
> The filter is completely ignored.

use:
boolean_filter=filter
