### ISSUE TITLE
Handle by default `ToolException`

### ISSUE THREAD

**Issue by clemlesne** [langchain-ai/langchain#10528]
### Feature request

As of today, if a tool crashes, the whole agent or chain crashes. From a user point-of-view, it is understandable that a specific tool is not available.

### Motivation

The user experience should be maintained if a dependency is broken. Plus, catching by default tool error can enhance the software reliability.

### Relates

- https://github.com/langchain-ai/langchain/issues/8348

**Comment by harkrish1** [comment]
Would be great to have this
