### ISSUE TITLE
Issue: Is LangSmith playground compatible with Azure OpenAI?

### ISSUE THREAD

**Issue by gchlodzinski** [langchain-ai/langchain#10533]
### Issue you'd like to raise.

1. I have downloaded original LangSmith walkthrough notebook and modified it to run AzureOpenAI llm instead of OpenAI
2. After successful run of the first example I went to Langsmith, selected first LLM call and opened it in the Playground.
3. I have filled up OpenAI key and hit 'Start'

Here is the error I get:

Error: Invalid namespace: $ -> {"id":["langchain","chat_models","azure_openai","AzureChatOpenAI"],"lc":1,"type":"constructor","kwargs":{"temperature":0,"openai_api_key":{"id":["xxx"],"lc":1,"type":"secret"},"deployment_name":"chat-gpt","openai_api_base":"yyy","openai_api_type":"azure","openai_api_version":"2023-03-15-preview"}}

I have played with different ways of setting OPEN_API_KEY but none of them works, the same error is consistently displayed.
So it is a bug or Azure Open AI does not work by design in the Playground?

**Comment by gchlodzinski** [comment]
Dear bot,
The answer is not relevant. There is no place in the Playground to run Python code. It only let me specify AzureOpenAI settings, like below. 
![settings](https://github.com/langchain-ai/langchain/assets/561223/dda45886-16dd-41c8-b819-d060f52031ed)

**Comment by thundersaiyan** [comment]
I'm facing similar issue :(

**Comment by hinthornw** [comment]
Hi all - we're adding azureopenai, anthropic, and support for a few other providers in the upcoming week. Thanks for your patience. I know the current functionality is restrictive

**Comment by zyz9074** [comment]
I'm facing similar issue

**Comment by RickMartian** [comment]
Any updates on this issue? I'm facing the same problem.

**Comment by hinthornw** [comment]
You can specify Azure OpenAI in the secrets button in the playground
<img width="428" alt="image" src="https://github.com/langchain-ai/langchain/assets/13333726/040af2b7-cefb-443f-9ac0-d27c9d358e4f">

**Comment by RickMartian** [comment]
> You can specify Azure OpenAI in the secrets button in the playground <img alt="image" width="428" src="https://user-images.githubusercontent.com/13333726/272061695-040af2b7-cefb-443f-9ac0-d27c9d358e4f.png">

Thanks for the help! I'm currently using langsmith hosted by langchain at smith.langchain.com, and there I could not see this option. Do you know if I need to do something else to appear this option?

**Comment by ssowonny** [comment]
> You can specify Azure OpenAI in the secrets button in the playground <img alt="image" width="428" src="https://user-images.githubusercontent.com/13333726/272061695-040af2b7-cefb-443f-9ac0-d27c9d358e4f.png">

I tried this but still get the same error message: `Invalid namespace: $ ...`

**Comment by nillwyc** [comment]
> > You can specify Azure OpenAI in the secrets button in the playground <img alt="image" width="428" src="https://user-images.githubusercontent.com/13333726/272061695-040af2b7-cefb-443f-9ac0-d27c9d358e4f.png">
> 
> Thanks for the help! I'm currently using langsmith hosted by langchain at smith.langchain.com, and there I could not see this option. Do you know if I need to do something else to appear this option?

i cant see the buttons-->[Switch to Azure OpenAI] or [Use Proxy] either. TT

**Comment by nillwyc** [comment]
hey guys
i found a new case,
where could i set  API endpoint?
![image](https://github.com/langchain-ai/langchain/assets/22739979/20f9cf07-221c-4f47-8266-27dc282ef8c5)
![image](https://github.com/langchain-ai/langchain/assets/22739979/b8b2b04a-dd0b-41d6-9d82-ea8f341eae5e)

**Comment by gchlodzinski** [comment]
Hello @hinthornw, unfortunately I still have the same error and others here confirm behaviour I am observing.
Is there any change to look at the issue and fix it?

**Comment by gchlodzinski** [comment]
Issue is solved.
