### ISSUE TITLE
Issue: Can I load THUDM/chatglm-6b?

### ISSUE THREAD

**Issue by ggnicolau** [langchain-ai/langchain#10553]
I've been searching for a large-context LLM with a relatively low parameter count suitable for local execution on multiple T4 GPUs or a single A100. My primary goal is to summarize extensive financial reports. While I came across FinGPT v1, it seems it isn't hosted on HuggingFace.

However, I did find chatglm-6b, which serves as the foundation for FinGPT v1. This model is accessible on HuggingFace, but I'm facing issues loading it.

Here's a snippet that successfully loads and uses the model outside Langchain:

```
from transformers import AutoModel, AutoTokenizer

model_name = "THUDM/chatglm2-6b"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)

# model = AutoModel.from_pretrained(model_name, trust_remote_code=True).cuda()

# 按需修改，目前只支持 4/8 bit 量化
# model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).quantize(4).cuda()

import torch

has_cuda = torch.cuda.is_available()
# has_cuda = False  # force cpu

if has_cuda:
    #model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4",trust_remote_code=True).half().cuda()  # 3.92
    model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).quantize(4).cuda()
else:
    model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4",trust_remote_code=True).half()  # float()

response, history = model.chat(tokenizer, f"Summarize this in a few words: {a}", history=[])

```

But, when I try the following, to use in Langchain:

```
from langchain.llms import HuggingFacePipeline

llm = HuggingFacePipeline.from_model_id(
    model_id="THUDM/chatglm-6b",
    task="text-generation",
    model_kwargs={"temperature": 0, "max_length": 64},
)
```

I encounter this error:

```
ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
```

From what I gather, the ChatGLM model cannot be passed directly to HuggingFace's pipeline. While the Langchain documentation does mention using ChatGLM as a local model, it seems to primarily focus on using it via an API endpoint:

```
endpoint_url = "http://127.0.0.1:8000"

# direct access endpoint in a proxied environment
# os.environ['NO_PROXY'] = '127.0.0.1'

llm = ChatGLM(
    endpoint_url=endpoint_url,
    max_token=80000,
    history=[["我将从美国到中国来旅游，出行前希望了解中国的城市", "欢迎问我任何问题。"]],
    top_p=0.9,
    model_kwargs={"sample_model_args": False},
)
```

Would anyone have insights on how to correctly load ChatGLM for tasks within Langchain?

**Comment by wizardbyron** [comment]
> I've been searching for a large-context LLM with a relatively low parameter count suitable for local execution on multiple T4 GPUs or a single A100. My primary goal is to summarize extensive financial reports. While I came across FinGPT v1, it seems it isn't hosted on HuggingFace.
> 
> However, I did find chatglm-6b, which serves as the foundation for FinGPT v1. This model is accessible on HuggingFace, but I'm facing issues loading it.
> 
> Here's a snippet that successfully loads and uses the model outside Langchain:
> 
> ```
> from transformers import AutoModel, AutoTokenizer
> 
> model_name = "THUDM/chatglm2-6b"
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
> 
> # model = AutoModel.from_pretrained(model_name, trust_remote_code=True).cuda()
> 
> # 按需修改，目前只支持 4/8 bit 量化
> # model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).quantize(4).cuda()
> 
> import torch
> 
> has_cuda = torch.cuda.is_available()
> # has_cuda = False  # force cpu
> 
> if has_cuda:
>     #model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4",trust_remote_code=True).half().cuda()  # 3.92
>     model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).quantize(4).cuda()
> else:
>     model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4",trust_remote_code=True).half()  # float()
> 
> response, history = model.chat(tokenizer, f"Summarize this in a few words: {a}", history=[])
> ```
> 
> But, when I try the following, to use in Langchain:
> 
> ```
> from langchain.llms import HuggingFacePipeline
> 
> llm = HuggingFacePipeline.from_model_id(
>     model_id="THUDM/chatglm-6b",
>     task="text-generation",
>     model_kwargs={"temperature": 0, "max_length": 64},
> )
> ```
> 
> I encounter this error:
> 
> ```
> ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.
> ```
> 
> From what I gather, the ChatGLM model cannot be passed directly to HuggingFace's pipeline. While the Langchain documentation does mention using ChatGLM as a local model, it seems to primarily focus on using it via an API endpoint:
> 
> ```
> endpoint_url = "http://127.0.0.1:8000"
> 
> # direct access endpoint in a proxied environment
> # os.environ['NO_PROXY'] = '127.0.0.1'
> 
> llm = ChatGLM(
>     endpoint_url=endpoint_url,
>     max_token=80000,
>     history=[["我将从美国到中国来旅游，出行前希望了解中国的城市", "欢迎问我任何问题。"]],
>     top_p=0.9,
>     model_kwargs={"sample_model_args": False},
> )
> ```
> 
> Would anyone have insights on how to correctly load ChatGLM for tasks within Langchain?
> 
> ### Suggestion:
> _No response_

You can try [chatglm.cpp](https://github.com/li-plus/chatglm.cpp) to host a quantized model model on laptop for development.

**Comment by hooyao** [comment]
You can try the following adapter, please ignore the ugly coding
```python
from typing import List, Optional

from langchain.llms.base import LLM
from transformers import AutoTokenizer, AutoModel, AutoConfig


class ChatGLM3(LLM):
    max_token: int = 2048
    temperature: float = 0.8
    top_p = 0.9
    tokenizer: object = None
    model: object = None
    history_len: int = 1024

    def __init__(self):
        super().__init__()
        model_config = AutoConfig.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
        self.tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
        self.model = AutoModel.from_pretrained("THUDM/chatglm3-6b", config=model_config,
                                               trust_remote_code=True).half().cuda()

    @property
    def _llm_type(self) -> str:
        return "GLM"

    def _call(self, prompt: str, history: List[str] = [], stop: Optional[List[str]] = None):
        response, _ = self.model.chat(
            self.tokenizer, prompt,
            history=history[-self.history_len:] if self.history_len > 0 else [],
            max_length=self.max_token, temperature=self.temperature,
            top_p=self.top_p)
        return response
```
Use is just like any langchain LLM
```python
    llm = ChatGLM3()
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    print(llm_chain.run(question))
```

**Comment by link-king** [comment]
> ```python
> prompt
> ```



> You can try the following adapter, please ignore the ugly coding
> 
> ```python
> from typing import List, Optional
> 
> from langchain.llms.base import LLM
> from transformers import AutoTokenizer, AutoModel, AutoConfig
> 
> 
> class ChatGLM3(LLM):
>     max_token: int = 2048
>     temperature: float = 0.8
>     top_p = 0.9
>     tokenizer: object = None
>     model: object = None
>     history_len: int = 1024
> 
>     def __init__(self):
>         super().__init__()
>         model_config = AutoConfig.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
>         self.tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm3-6b", trust_remote_code=True)
>         self.model = AutoModel.from_pretrained("THUDM/chatglm3-6b", config=model_config,
>                                                trust_remote_code=True).half().cuda()
> 
>     @property
>     def _llm_type(self) -> str:
>         return "GLM"
> 
>     def _call(self, prompt: str, history: List[str] = [], stop: Optional[List[str]] = None):
>         response, _ = self.model.chat(
>             self.tokenizer, prompt,
>             history=history[-self.history_len:] if self.history_len > 0 else [],
>             max_length=self.max_token, temperature=self.temperature,
>             top_p=self.top_p)
>         return response
> ```
> 
> Use is just like any langchain LLM
> 
> ```python
>     llm = ChatGLM3()
>     llm_chain = LLMChain(prompt=prompt, llm=llm)
>     print(llm_chain.run(question))
> ```

how to define prompt?
