### ISSUE TITLE
LangChain's Chroma similarity_search return results from other db

### ISSUE THREAD

**Issue by fengyuyan** [langchain-ai/langchain#10555]
### System Info

LangChain 0.0.281
Platform: Centos

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hi,

I have two vector stores:

splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
splits_1 = splitter.split_documents(docs_1)
splits_2 = splitter.split_documents(docs_2)

store1 = Chroma.from_documents(documents=splits_1, embedding=HuggingFaceEmbeddings())
store2 = Chroma.from_documents(documents=splits_2, embedding=HuggingFaceEmbeddings())

Then I use store2 to do similarity search, it returns results from splits_1, that's very wired. Can someone please help?

Thanks
Tom

### Expected behavior

Different vector store should use its own pool to do the similarity search

**Comment by fengyuyan** [comment]
Hi Dosu,

Thanks for your reply! I just tried the latest version 0.0.287, the issue exists too. I just create a very simple case to reproduce as below. Looks like it always use all vectores to do the similarity search.

from langchain.vectorstores import Chroma
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader

splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
doc1 = PyPDFLoader(r'/root/work/docs/doc1.pdf').load() # content is "Tom is in US"
doc2 = PyPDFLoader(r'/root/work/docs/doc2.pdf').load() # content is "Jerry is in China"

splits1 = splitter.split_documents(doc1)
splits2 = splitter.split_documents(doc2)
store1 = Chroma.from_documents(documents=splits1, embedding=HuggingFaceEmbeddings())
store2 = Chroma.from_documents(documents=splits2, embedding=HuggingFaceEmbeddings())

result = store2.similarity_search('Jerry')

print(result)

**Comment by fengyuyan** [comment]
The issue still exists! I am using Python 3.10 and there is no error.

**Comment by clitch123** [comment]
I found a work-around for this, basically creating an empty chroma vector store and removing any collections before you add in the documents. This way previous context is not populated into a new vector store and you can search each vector store's context separately.

```
splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
splits_1 = splitter.split_documents(docs_1)
splits_2 = splitter.split_documents(docs_2)

store1 = Chroma(embedding_function=HuggingFaceEmbeddings())
store1.delete_collection() #deletes any content in the vector store

store1 = store1.from_documents(documents=splits_1, embedding=HuggingFaceEmbeddings())

store2 = Chroma(embedding_function=HuggingFaceEmbeddings())
store2.delete_collection() #deletes any content in the vector store

store2 = store2.from_documents(documents=splits_2, embedding=HuggingFaceEmbeddings())
```

**Comment by dillip9676** [comment]
@stossenbrink , I got the same problem when performing the similarity search. To solve this first store the vector store in you local machine and then load the stored vector store individually for different data files you created.

use this reference code to save and load the vector store using chroma 

# reference - https://python.langchain.com/docs/integrations/vectorstores/chroma
# save to disk
db2 = Chroma.from_documents(docs, embedding_function, persist_directory="./chroma_db")
docs = db2.similarity_search(query)

# load from disk
db3 = Chroma(persist_directory="./chroma_db", embedding_function=embedding_function)
docs = db3.similarity_search(query)
print(docs[0].page_content)
