### ISSUE TITLE
SQLRecordManager index adds documents outside existing Redis vectorstore index

### ISSUE THREAD

**Issue by RoderickVM** [langchain-ai/langchain#10551]
### System Info

langchain_version: "0.0.287"
library: "langchain"
library_version: "0.0.287"
platform: "Linux-6.1.0-12-amd64-x86_64-with-glibc2.36"
py_implementation: "CPython"
runtime: "python"
runtime_version: "3.11.2"

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

After following the [indexing instructions](https://python.langchain.com/docs/modules/data_connection/indexing), `index` stores the documents in a Redis vectorstore, but it does so outside the vectorstore's index.

```
import os, time, json, openai
from langchain.vectorstores.redis import Redis
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.indexes import SQLRecordManager, index
from langchain.schema import Document
from datetime import datetime
from pathlib import Path

openai.api_key  = os.environ['OPENAI_API_KEY']

VECTORS_INDEX_NAME = 'Vectors'
COLLECTION_NAME = 'DocsDB'
NAMESPACE = f"Redis/{COLLECTION_NAME}"
REDIS_URL = "redis://10.0.1.21:6379"

embeddings = OpenAIEmbeddings()

record_manager = SQLRecordManager(NAMESPACE, db_url="sqlite:///cache_Redis.sql")
record_manager.create_schema()

rds_vectorstore = Redis.from_existing_index(
    embeddings,
    index_name=VECTORS_INDEX_NAME,
    redis_url=REDIS_URL,
    schema='Redis_schema.yaml'
)

index(
    document,
    record_manager,
    rds_vectorstore,
    cleanup = "full", # None: for first document load; "incremental": for following documents
    source_id_key = "title",
)
```
When exploring the Redis vectorstore, all `documents` loaded outside the specified `VECTORS_INDEX_NAME`.

When `documents` are loaded to the vectorstore without `RecordManager` `index`, they are created inside the specified `VECTORS_INDEX_NAME` when using the following code:
```
rds = Redis.from_documents(
    document,
    embeddings,
    index_name=VECTORS_INDEX_NAME,
    redis_url=REDIS_URL,
    index_schema='Redis_schema.yaml'
)
```

### Expected behavior

`Documents` loaded into a Redis vectorstore using `index` `RecordManager` should be created inside the vectorstore's index.

**Comment by nfcampos** [comment]
@eyurtsev any idea?
