### ISSUE TITLE
Can not use QianfanLLMEndpoint

### ISSUE THREAD

**Issue by WAL-l** [langchain-ai/langchain#10567]
### System Info

Unresolved reference 'QianfanLLMEndpoint' 

Name: langchain
Version: 0.0.288

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.llms.baidu_qianfan_endpoint import QianfanLLMEndpoint

### Expected behavior

I hope to use Qianfan model but I can't import it, even though i have update my langchain, it can't work.

**Comment by NuODaniel** [comment]
Thanks for you feedback, `QianfanLLMEndpoint` depends on `qianfan` and `ernibot`. Could you show more info about this issue like captures or detail logs. @WAL-l

**Comment by NuODaniel** [comment]
Checked to the code of langchain version [0.0.288](https://github.com/langchain-ai/langchain/tree/v0.0.288). it seems like QianfanLLMEndpoint had not been added into this version.  @WAL-l

**Comment by NuODaniel** [comment]
@WAL-l hi Qianfan has been supported in 0.0.291. FYI

**Comment by xwdreamer** [comment]
@WAL-l ，please use this version 0.0.292
```
pip install langchain==0.0.292
pip install qianfan==0.0.3
```
