### ISSUE TITLE
Document' object has no attribute '_lc_kwargs

### ISSUE THREAD

**Issue by taweijm** [langchain-ai/langchain#10579]
### System Info

langchain version 0.0.285
langsmith version 0.0.28
Python version 3.11.2

### Who can help?

@hwchase17 

### Information

- [X ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I followed tutorial in RAG cookbook with "With Memory and returning source documents"

Steps for changing behaviour 

1. use FAISS.from documents and save to files
    embeddings = OpenAIEmbeddings()    
    vectorstore  = FAISS.from_documents(documents, embeddings)
    vectorstore.save_local("data/faiss_index")

2. load from file
    embeddings = OpenAIEmbeddings()
    vectorstore = FAISS.load_local("data/faiss_index", embeddings)
    retriever = vectorstore.as_retriever()
 
3. error raised "Document' object has no attribute '_lc_kwargs" in step 5 
    final_inputs = {
         "context": lambda x: _combine_documents(x["docs"]),
         "question": itemgetter("question")
    }

here is the screen shot when using langsmith

<img width="543" alt="RAG" src="https://github.com/langchain-ai/langchain/assets/105797032/038b1b98-4dde-47a1-a79b-4061014c05a2">

### Expected behavior

Expected behaviour is LLM give result without error

**Comment by nfcampos** [comment]
@taweijm Hi would you be able to add here a stack trace you're seeing for the error?

**Comment by taweijm** [comment]
Hi Nuno,

sure, here the stack trace that raise the error :

For version langchain-0.0.285 and langsmith version 0.0.28 :

final_inputs = {
"context": lambda x: self._combine_documents(x["docs"]), "question":
itemgetter("question") }

for FAISS, I'm using :
embeddings = OpenAIEmbeddings()
pathFaiss = pathlib.Path("data/faiss_index")

if os.path.exists(pathFaiss):
vectorstore = FAISS.load_local(pathFaiss, embeddings)
retriever = vectorstore.as_retriever()

but when upgrade to langchain version 0.0.299 and langsmith to version
0.0.40 (latest version) but it show error already on step 3

the error "'HumanMessage' object is not subscriptable" show in step 3 from
6 :

standalone_question = { "standalone_question": {
"question": lambda x: x["question"],
"chat_history": lambda x: self._format_chat_history(x['chat_history']) }
| CONDENSE_QUESTION_PROMPT
| ChatOpenAI(temperature=0)
| StrOutputParser(), }

TIA,
David JM
