### ISSUE TITLE
MapRerankDocumentsChain UserWarning & ValueError

### ISSUE THREAD

**Issue by ton77v** [langchain-ai/langchain#10670]
### System Info

langchain==0.0.292
OS Windows10
Python 3.11

### Who can help?

Probably  @hwchase17 @agola11

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Example code for Q/A chain with "Map Re-Rank" following the official tutorials:

```
precise_chat_model = ChatOpenAI(
    model_name='gpt-3.5-turbo',
    temperature=0,
    openai_api_key=OPENAI_API_KEY
)
qa_chain: MapRerankDocumentsChain = load_qa_chain(
    llm=precise_chat_model,
    chain_type='map_rerank',
    verbose=True,
    return_intermediate_steps=True
)
question = 'Question'
query = {'input_documents': pages,  'question': question}
answer = qa_chain(query, return_only_outputs=False)
```
Full example with PDF that raises Exception all the time: https://gist.github.com/ton77v/eb5b90e72b1652ebccee86ac80b1e01f

Every time I use this chain with any page the UserWarning appears:
```
UserWarning: The apply_and_parse method is deprecated, instead pass an output parser directly to LLMChain.
```

And for the specific documents (usually when 10+ pages) the ValueError is raised upon finishing the chain.
* Gist above raises this error all the time!

```
File "...site-packages\langchain\output_parsers\regex.py", line 35, in parse
raise ValueError(f"Could not parse output: {text}")
ValueError: Could not parse output: Code execution in Ethereum....
```

### Expected behavior

I expect to get an answer without any Exceptions and Warnings

**Comment by ton77v** [comment]
@dosu-bot what output parser is used by `apply_and_parse` by default?

**Comment by geg00** [comment]
@dosu-bot I'm using the function ConversationalRetrievalChain not the llm directly.
Any way to fix this issue?

**Comment by devstein** [comment]
Hey @geg00 as of right now Dosu only responds to the issue author. We're working on a way to allow users to "fork" an issue to interact with Dosu outside of Github. Stay tuned 😄 

Let me know if you have any feedback or thoughts on Dosu in the meantime!

**Comment by geg00** [comment]
> Hey @geg00 as of right now Dosu only responds to the issue author. We're working on a way to allow users to "fork" an issue to interact with Dosu outside of Github. Stay tuned 😄
> 
> Let me know if you have any feedback or thoughts on Dosu in the meantime!

I still need to know how to resolve the issue with map_reranker while using ConversationalRetrivalChain.
😁
