### ISSUE TITLE
Deployment template for AWS

### ISSUE THREAD

**Issue by 3coins** [langchain-ai/langchain#1067]
This issue pertains to tasks related to creating a deployment template for deploying an API Gateway + Lambda + langchain backed service to AWS.

**Comment by 3coins** [comment]
@hwchase17 
I noticed that the current deployment templates are setup under separate repositories. Can you help create a new repo for this. Also, can you please assign this issue to me. Thanks for your help!

cc @ellisonbg

**Comment by hwchase17** [comment]
would love to work on this. what do you imagine this separate repo looking like?

**Comment by 3coins** [comment]
@hwchase17 
Thanks for helping with this. I would suggest `langchain-aws-template` for this repository. As for the content, I had these tasks in mind for now.
1. CDK or SAM template for setting the infra (API Gateway + Lambda)
2. Lambda will use langchain to call a SageMaker endpoint with an LLM model deployed(Would like to use LLM class from https://github.com/hwchase17/langchain/pull/965)
3. README with instructions

Let me know if you have any suggestions to improve the repo.

**Comment by 3coins** [comment]
@hwchase17 
Can you help create a new repo for this. Here is the template I have so far; I have added you as a collaborator to this repo.
https://github.com/3coins/langchain-aws-template

**Comment by Sam1320** [comment]
Is there a way to access this template with the progress so far? seems to be a private repository.

**Comment by 3coins** [comment]
@Sam1320 
Thanks for your interest. I am trying to get this imported into it's own public repo, so the community can contribute openly.

**Comment by 3coins** [comment]
@hwchase17 
Please let me know if you have any suggestions for the deployment template. If something is missing in the current code, I can work on updating the code and making sure it meets the repo's quality bar. Looking forward to work with you on this. Thanks for your help.

**Comment by 3coins** [comment]
@Sam1320 
Still waiting for @hwchase17 to create a repo under langchain, but I have made the existing repo public, plz feel free to try and provide feedback. 
https://github.com/3coins/langchain-aws-template

**Comment by abrichr** [comment]
I am interested in contributing!

Another option for a quick and dirty implementation is wrapping [AWS CLI](https://github.com/aws/aws-cli) commands.

**Comment by Agamago** [comment]
Is there any plan to complete this project? It appears as tho many Langchain users are struggling to deploy their tools to AWS lambdas because of conflicting dependencies. Is there any plan to fix this or create an official lambda layer for langchain applications ?
