### ISSUE TITLE
HuggingFace Data Loader fails when context is not str

### ISSUE THREAD

**Issue by deanchanter** [langchain-ai/langchain#10674]
### System Info

langchain                   0.0.285
python 3.11.4

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Try to load https://huggingface.co/datasets/hotpot_qa/viewer/fullwiki/validation

from langchain.document_loaders import HuggingFaceDatasetLoader
dataset_name = "hotpot_qa"
page_content_column = "context"
name = "fullwiki"

loader = HuggingFaceDatasetLoader(dataset_name, page_content_column, name)
docs = loader.load()

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[/Users/deanchanter/Documents/GitHub/comma-chameleons/hello_doc_read.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/hello_doc_read.ipynb) Cell 1 line 8
      [4](vscode-notebook-cell:/Users/deanchanter/Documents/GitHub/comma-chameleons/hello_doc_read.ipynb#Y125sZmlsZQ%3D%3D?line=3) name = "fullwiki"
      [7](vscode-notebook-cell:/Users/deanchanter/Documents/GitHub/comma-chameleons/hello_doc_read.ipynb#Y125sZmlsZQ%3D%3D?line=6) loader = HuggingFaceDatasetLoader(dataset_name, page_content_column, name)
----> [8](vscode-notebook-cell:/Users/deanchanter/Documents/GitHub/comma-chameleons/hello_doc_read.ipynb#Y125sZmlsZQ%3D%3D?line=7) docs = loader.load()

File [~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:87](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:87), in HuggingFaceDatasetLoader.load(self)
     85 def load(self) -> List[Document]:
     86     """Load documents."""
---> 87     return list(self.lazy_load())

File [~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:76](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:76), in HuggingFaceDatasetLoader.lazy_load(self)
     59     raise ImportError(
     60         "Could not import datasets python package. "
     61         "Please install it with `pip install datasets`."
     62     )
     64 dataset = load_dataset(
     65     path=self.path,
     66     name=self.name,
   (...)
     73     num_proc=self.num_proc,
     74 )
---> 76 yield from (
     77     Document(
     78         page_content=row.pop(self.page_content_column),
     79         metadata=row,
     80     )
     81     for key in dataset.keys()
     82     for row in dataset[key]
     83 )

File [~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:77](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/document_loaders/hugging_face_dataset.py:77), in <genexpr>(.0)
     59     raise ImportError(
     60         "Could not import datasets python package. "
     61         "Please install it with `pip install datasets`."
     62     )
     64 dataset = load_dataset(
     65     path=self.path,
     66     name=self.name,
   (...)
     73     num_proc=self.num_proc,
     74 )
     76 yield from (
---> 77     Document(
     78         page_content=row.pop(self.page_content_column),
     79         metadata=row,
     80     )
     81     for key in dataset.keys()
     82     for row in dataset[key]
     83 )

File [~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/load/serializable.py:75](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/langchain/load/serializable.py:75), in Serializable.__init__(self, **kwargs)
     74 def __init__(self, **kwargs: Any) -> None:
---> 75     super().__init__(**kwargs)
     76     self._lc_kwargs = kwargs

File [~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/pydantic/main.py:341](https://file+.vscode-resource.vscode-cdn.net/Users/deanchanter/Documents/GitHub/comma-chameleons/~/Documents/GitHub/comma-chameleons/env/lib/python3.11/site-packages/pydantic/main.py:341), in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Document
page_content
  str type expected (type=type_error.str)

### Expected behavior

Either extend class to handle more types of data or update docs. Will to do a  PR to extend if your open.

**Comment by deanchanter** [comment]
Ok I will open a doc bug and do a doc PR for that first until I have time
write the extension as i also want add support for split and length. Note I
must likely will extend using a similar method as the json loader.

**Comment by sachinsingh3107** [comment]
@dosu-bot, If this issue is not resolved yet, can I pick this issue?

**Comment by devstein** [comment]
@sachinsingh3107 Right now, Dosu only responds to the issue author, but to answer your question, yes! 

Contribution are always encourage. Just make sure there isn't an open PR already for it

**Comment by sathayen** [comment]
@deanchanter  is there any open PR that fixes this bug? I can only see the merged PR that updates the documentation. (btw thank you for adding this information!)

**Comment by deanchanter** [comment]
Unfortunately, no. I have not had time finish a fix. I just finished the
project that found this bug so I was going to look into it. One fix would
be doing similar to the json loader where a schema can be defined but I
want to look deeper into it and make sure this is not more generic issue
with the loaders.

**Comment by sathayen** [comment]
>>> I want to look deeper into it and make sure this is not more generic issue with the loaders.
@deanchanter unless something wrong with my code below, I am running into the same KeyError with DataFrameLoader as well . Here I am reading a json downloaded from a dataset on HF. 
`df = pd.read_json("/path/to/test.json", encoding='utf-8')
print(df)
loader = DataFrameLoader(df)
data = loader.load()` 
KeyError -->
document_loaders\dataframe.py", line 23, in lazy_load
    text = row[self.page_content_column]

**Comment by deanchanter** [comment]
Do you have a column called text? the dataframeloader default value is 'text'  but if you already have a json try the json loader.  https://python.langchain.com/docs/modules/data_connection/document_loaders/json

can you point to the hf dataset? or share the format of the data you are trying to load?

**Comment by sathayen** [comment]
no, by default the dataset does not have the 'text' column . I did not try the JSON loader as on windows the documentation suggests you need `pip install jq` which is not easily available in my current env in vscode (not using git bash etc) .  

 I tried the following HF datasets (used test.json from my cached dir) -- https://huggingface.co/datasets/squad/ and https://huggingface.co/datasets/cuad , loaded those in pandas df.

**Comment by deanchanter** [comment]
set `page_content_column = 'context'`
https://python.langchain.com/docs/integrations/document_loaders/hugging_face_dataset

**Comment by sathayen** [comment]
thank you @deanchanter !  I completely missed this. I misinterpreted 'text' as a column content type  (text, binary etc)  than the actual column label ('text' , 'context' etc. )  . All good now. Thank you again!

**Comment by JeffreyHe-1e** [comment]
Hi @deanchanter I'd like to contribute to this problem too. Were you able to find any similar issues with other document loaders? Thank you for your work!

**Comment by deanchanter** [comment]
I have not had anytime to work on it. As a user I would want it to more
open to accept any data scheme.

**Comment by JeffreyHe-1e** [comment]
Hi @deanchanter, what is the desired behaviour of your example code segment? Yes, the code shouldn't give any errors. What should be the resulting docs that is loaded by the HuggingFaceDatasetLoader, if we set the page_content to "context"?

I'm new to Langchain and Hugging Face. I see in the [hotpot_qa](https://huggingface.co/datasets/hotpot_qa) dataset, the "context" key has value: 
"context": {
        "sentences": [["Sent 1"], ["Sent 21", "Sent 22"]],
        "title": ["Title1", "Title 2"]
},

Should the loader load a list, where each element is the result of the HuggingFaceDatasetLoader with page_content set to each of the titles?
