### ISSUE TITLE
Is there a way to pass Dictionary as an Action input when you use Zero Shot Agent?

### ISSUE THREAD

**Issue by jpark2111** [langchain-ai/langchain#10681]
### System Info

python==3.8
langchain==217

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm testing one of the tools that is being used in the zero shot agent, which is making an external api call and get json response. I'm trying to use LLMRequestsChain, and this chain needs an input as dictionary with query and url keys to make a call.

`inputs = {
                "query": user_message,
                "url": f"{endpoint}/user/{mxUser}/accounts?page=1&records_per_page=10"
  }  
  result = agent_chain.zero_shot_agent_chain().run({"question": inputs})
`
Once the dict has been passed to the tool which is the LLMRequestsChain, It throws InvalidSchema exception saying `No connection adapters were found for '{\n    "query": "what\'s my balance?",\n    "url": "targeted url"\n}'`

### Expected behavior

looks like the dict has been passed to the tool as a string. Is there any workaround or any idea to work with?

**Comment by ketangangal** [comment]
any solution
