### ISSUE TITLE
Issue:Sitemap Loader filter updated pages

### ISSUE THREAD

**Issue by DonTizi** [langchain-ai/langchain#10703]
### Issue you'd like to raise.

Hi , I want to know how it would be possible to filter with the Sitemap Loader updated pages of 2023 from a website. I do not want to get all the website but only 2023 updated pages. 

Here is my code:
`# fixes a bug with asyncio and jupyter
import nest_asyncio
nest_asyncio.apply()

from langchain.document_loaders.sitemap import SitemapLoader

loader = SitemapLoader(
    "",
    filter_urls=[""]
)
docs = loader.load()`

How can it be possible in it please?
Thank you,

**Comment by RayaneMelDz** [comment]
> _🤖_
> 
> Hello,
> 
> To filter the pages updated in 2023, you can modify the `parse_sitemap` method in the `SitemapLoader` class to check the `lastmod` tag of each URL. The `lastmod` tag in the sitemap XML usually contains the last modification date of the page. Here's how you can do it:
> 
> ```python
> def parse_sitemap(self, soup: Any) -> List[dict]:
>     """Parse sitemap xml and load into a list of dicts.
> 
>     Args:
>         soup: BeautifulSoup object.
> 
>     Returns:
>         List of dicts.
>     """
>     els = []
>     for url in soup.find_all("url"):
>         loc = url.find("loc")
>         if not loc:
>             continue
> 
>         # Strip leading and trailing whitespace and newlines
>         loc_text = loc.text.strip()
> 
>         if self.filter_urls and not any(
>             re.match(r, loc_text) for r in self.filter_urls
>         ):
>             continue
> 
>         # Extract the lastmod tag
>         lastmod = url.find("lastmod")
>         if lastmod:
>             # Check if the page was updated in 2023
>             lastmod_date = lastmod.text.strip()
>             if not lastmod_date.startswith("2023"):
>                 continue
> 
>         els.append(
>             {
>                 tag: prop.text
>                 for tag in ["loc", "lastmod", "changefreq", "priority"]
>                 if (prop := url.find(tag))
>             }
>         )
> 
>     for sitemap in soup.find_all("sitemap"):
>         loc = sitemap.find("loc")
>         if not loc:
>             continue
>         soup_child = self.scrape_all([loc.text], "xml")[0]
> 
>         els.extend(self.parse_sitemap(soup_child))
>     return els
> ```
> 
> This modification will make the `parse_sitemap` method ignore any URLs that were not last modified in 2023. Please note that this assumes the `lastmod` tag is in the format `YYYY-MM-DD`. If the format is different, you may need to adjust the condition accordingly.
> 
> This solution is based on a similar issue that was solved in the LangChain repository: [Sitemap - add filtering by modified date](https://github.com/langchain-ai/langchain/issues/5280).
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best regards, Dosu
> 
> ## Sources
> * [Sitemap - add filtering by modified date](https://github.com/langchain-ai/langchain/issues/5280)
> * [libs/langchain/langchain/document_loaders/sitemap.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/document_loaders/sitemap.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

How can I change the parse_sitemap in google colabotary?
