### ISSUE TITLE
PineconeArgumentError: The argument to upsert had type errors: argument must be array.

### ISSUE THREAD

**Issue by binodev** [langchain-ai/langchain#10708]
### System Info

Hello everyone,

I am encountering an issue while trying to use Pinecone store  in my Node.js environment. 

When i try to store the vector in an existing index, I am receiving the following error:

PineconeArgumentError: The argument to upsert had type errors: argument must be array.

here is my code :

  async function training(bot, documents) {
    if (!bot || !bot.name) {
      throw new Error('Invalid bot or bot name is missing.');
    }
    if (!documents || !Array.isArray(documents) || documents.length === 0) {
      throw new Error('Invalid documents array.');
    }
  
    try {
      const botName = bot.name;
   
      console.log('Bot Name:', botName);
  
      const keys = documents.map(url => path.basename(url));
      console.log('Document keys:', keys);
  
      const rawDocs = await chargerDocumentsDeS3(keys);
      console.log('Raw documents retrieved:', rawDocs.length);
  
      /* Split text into chunks */
      const textSplitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });
      let docs = await textSplitter.splitDocuments(rawDocs);
      console.log('Number of split documents:', docs.length);
      //console.log(docs)
      const index = pinecone.Index( botName);
      await PineconeStore.fromDocuments(docs, new OpenAIEmbeddings(), {
        pineconeIndex:index,
        maxConcurrency: 5, // Maximum number of batch requests to allow at once. Each batch is 1000 vectors.
      });
  
      console.log('Upload and processing complete.');
      return { message: 'Upload and processing complete.' };
    } catch (error) {
      console.error('Error during upload and processing:', error);
      throw new Error('Something went wrong during upload and processing.');
    }
  }

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

  async function training(bot, documents) {
    if (!bot || !bot.name) {
      throw new Error('Invalid bot or bot name is missing.');
    }
    if (!documents || !Array.isArray(documents) || documents.length === 0) {
      throw new Error('Invalid documents array.');
    }
  
    try {
      const botName = bot.name;
   
      console.log('Bot Name:', botName);
  
      const keys = documents.map(url => path.basename(url));
      console.log('Document keys:', keys);
  
      const rawDocs = await chargerDocumentsDeS3(keys);
      console.log('Raw documents retrieved:', rawDocs.length);
  
      /* Split text into chunks */
      const textSplitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });
      let docs = await textSplitter.splitDocuments(rawDocs);
      console.log('Number of split documents:', docs.length);
      //console.log(docs)
      const index = pinecone.Index( botName);
      await PineconeStore.fromDocuments(docs, new OpenAIEmbeddings(), {
        pineconeIndex:index,
        maxConcurrency: 5, // Maximum number of batch requests to allow at once. Each batch is 1000 vectors.
      });
  
      console.log('Upload and processing complete.');
      return { message: 'Upload and processing complete.' };
    } catch (error) {
      console.error('Error during upload and processing:', error);
      throw new Error('Something went wrong during upload and processing.');
    }
  }

### Expected behavior

I want a solution

**Comment by binodev** [comment]
docs is an array. i checked it in my console.

**Comment by poipiii** [comment]
im facing the same issue too i checked that i passed an array of Document objects and it still returns the upsert error

**Comment by gonzar11** [comment]
I am having the same error.

**Comment by gonzar11** [comment]
It looks like there is a problem with the version of @pinecone-database/pinecone. From version 1.0 the api for upsert has been changed https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md#upserting
Now the function expects an array:
```
namespace.upsert([
  {
    id: '1',
    values: [0.1, 0.2, 0.3, 0.4],
    metadata: { genre: 'comedy', runtime: 120 },
  },
  {
    id: '2',
    values: [0.5, 0.6, 0, 0.8],
    metadata: { genre: 'horror', runtime: 120 },
  },
]);
``` 
Instead of an `upsertRequest`
```
index.upsert({
  upsertRequest: {
    vectors: [
      {
        id: '1',
        values: [0.1, 0.2, 0.3, 0.4],
        metadata: { genre: 'comedy', runtime: 120 },
      },
      {
        id: '2',
        values: [0.5, 0.6, 0.7, 0.8],
        metadata: { genre: 'horror', runtime: 120 },
      },
    ],
    namespace: 'imdb',
  },
});
```
I can work on a PR for this.

**Comment by gonzar11** [comment]
Someone is working in the Pinecone upgrade https://github.com/langchain-ai/langchainjs/pull/2648

**Comment by charles-ward-personal** [comment]
Is there any update on this? I am facing the same issue

**Comment by mitchossi** [comment]
+1 (aka same here)

**Comment by 0xRishav** [comment]
Any update?

**Comment by gonzar11** [comment]
It was fixed on the last version. 
Have a look at the new doc https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/pinecone

**Comment by pcoterecollective** [comment]
@gonzar11 Still get the same error...

**Comment by ElectricCodeGuy** [comment]
It seems like: maxConcurrency: is not a part of the  import { PineconeStore, PineconeLibArgs } from "langchain/vectorstores/pinecone";?
 
If i copy straight from the docs it trows me an error stating it does not exist within  PineconeLibArgs

**Comment by xgg94** [comment]
Still not working with langchain@0.0.96 and @pinecone-database/pinecone@1.1.1
Any suggestions?

**Comment by 0xRishav** [comment]
@xgg94 I have used pinecone and openai embeddings directly without langchain.

**Comment by htoann** [comment]
Try using hnswlib-node instead of Pinecone

**Comment by matheuslemke** [comment]
On version 0.0.214 it is fixed!

**Comment by Akuna444** [comment]
If you have been using old version, please upgrade to newer version. It must be working!
