### ISSUE TITLE
Custom Tool Return Direct BUT only if it doesnt raise a Tool Exception

### ISSUE THREAD

**Issue by Hsgngr** [langchain-ai/langchain#10714]
### System Info

0.0.287 langchain

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Currently I have a Custom Tool like this:
```
def _handle_error(error: ToolException) -> str:
    return (
        "The following errors occurred during tool execution:"
        + error.args[0]
        + "please try another tool."
    )
    tools = [
      Tool.from_function(
             name="GetCurrentWeather",
             func=get_current_weather,
             description="useful for getting the current weather for a location",
             return_direct=True,
             handle_tool_error=_handle_error)]
```
It works unless I add the return_direct=True.

When I do return_direct= True instead of trying other tools it just returns this:

```
> Entering new AgentExecutor chain...
16 AgentAction --> Thought: The question is asking about the current weather in Uludağ.
17 Action: GetCurrentWeather
18 Action Input: Uludağ
19 Thought: The question is asking about the current weather in Uludağ.
20 Action: GetCurrentWeather
21 Action Input: Uludağ
22 Observation:The following errors occurred during tool execution:the location is not found. please try another tool.
23 > Finished chain.
24 The following errors occurred during tool execution:location is not found.please try another tool.
```

### Expected behavior

Let's see the same thing without the `return_direct=True`:
```
> Entering new AgentExecutor chain...
Thought: The question is asking about the current weather in Uludağ.
Action: GetCurrentWeather
Action Input: Uludağ

Observation:The following errors occurred during tool execution:location is not found. please try another tool.
I couldn't find the current weather for Uludağ. I should try another tool.
Action: DuckDuckSearch
Action Input: "Uludağ current weather"

Observation:Current Weather. 7:35 PM. 78° F. RealFeel® 74°. RealFeel Shade™ 74°. Air Quality Fair. Wind W 14 mph. Wind Gusts 24 mph. Sunny More Details. 7:14. —. This table gives the weather forecast for Uludag at the specific elevation of 2543 m. Our advanced weather models allow us to provide distinct weather forecasts for several elevations of Uludag. ..
```
So it goes for the other tools. It should be like this for return_direct.

It should return directly only if it doesn't get an error.

**Comment by ivanstepanovftw** [comment]
Langchain is very overengineered...

**Comment by westonCoder** [comment]
I agree with this suggestion. I need a custom tool to output directly but ONLY if it doesn't raise an exception. 

I guess a workaround would be to output a known value if there is an exception and retry the run.
Another workaround would be to raise a `ToolException` with a known value within its text and retry the run if that text is present in the response.

this is kind of clunky and it would be nice to have a more streamlined solution.

**Comment by Daviderikmollberg** [comment]
A feature like this has been added to LangGraph. See example here:
https://github.com/langchain-ai/langgraph/blob/main/examples/chat_agent_executor_with_function_calling/dynamically-returning-directly.ipynb

**Comment by nanodan** [comment]
I would like to re-open this, it seems this is still not possible.
