### ISSUE TITLE
How to custom prompt in agent type CHAT_CONVERSATIONAL_REACT_DESCRIPTION 

### ISSUE THREAD

**Issue by easontsai** [langchain-ai/langchain#10721]
```
agent_chain = initialize_agent(
    tools,
    llm,
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True,
    return_intermediate_steps=True,
    handle_parsing_errors=True,
    memory=memory
)
```

how to overwrite the PREFIX, SUFFIX and FORMAT_INSTRUCTIONS when I using the CHAT_CONVERSATIONAL_REACT_DESCRIPTION and creating agent by ```initialize_agent``` function?

**Comment by btrcm00** [comment]
You just need to define your own variables and pass them to initialize function like the following.

```
agent_chain = initialize_agent(
    tools,
    llm,
    agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    verbose=True,
    return_intermediate_steps=True,
    handle_parsing_errors=True,
    memory=memory,
    prefix=custom_prefix,
    suffix=custom_suffix,
    format_instructions=custom_format_instructions
)
```

**Comment by guidorietbroek** [comment]
We've created a subclass of the ConvoOutputParser and that way it is possible to edit the get_format_instructions() method to load your custom format instructions.

**Comment by xiaoyaoyang** [comment]
same question, it looks like you have to define custom agent, wondering if there is a way to define it similar to AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION

**Comment by kamalkech** [comment]
@spartan-minhbui format_instructions not working the agent not take consideration this property

**Comment by hdnh2006** [comment]
> We've created a subclass of the ConvoOutputParser and that way it is possible to edit the get_format_instructions() method to load your custom format instructions.

Yes, but you cannot set your own format instructions without defining a new class, because you are importing a variable and passing it to a function as it is done [here](https://github.com/langchain-ai/langchain/blob/cc173344737d4ac7ff96a04bfe2e93022b32d8b7/libs/langchain/langchain/agents/conversational_chat/output_parser.py#L17):
```
    def get_format_instructions(self) -> str:
        """Returns formatting instructions for the given output parser."""
        return FORMAT_INSTRUCTIONS
```

There is a way to pass this parameter in the init as you do in agents and other functions:
```
# Define a class that parses output for conversational agents
class ConvoOutputParser(AgentOutputParser):
    """Output parser for the conversational agent."""
    format_instructions: str = FORMAT_INSTRUCTIONS
```
And another way to do it directly in the agent, in the `create_prompt` function:
```
    def create_prompt(
        cls,
        tools: Sequence[BaseTool],
        system_message: str = PREFIX,
        human_message: str = SUFFIX,
        input_variables: Optional[List[str]] = None,
        output_parser: Optional[BaseOutputParser] = None,
        format_instructions: str = None
    ) -> BasePromptTemplate:
... # continues...

        format_instructions = human_message.format(
            format_instructions=_output_parser.get_format_instructions() if format_instructions is None else format_instructions
        )

```

Particullarly the second option will allow you to define the `format_instructions` template when you are defining the agent. As it is available for the other parameters in the `agent_kwargs`:
```
agent = initialize_agent(
    agent = AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    #agent = AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    tools = tools,
    #tools = load_knowledge_tools(),
    llm = llm_agent,
    verbose = True,
    max_iterations = 3,
    early_stopping_method = 'generate',
    memory = b_w_memory,
    handle_parsing_errors = True,
    agent_kwargs={
        'system_message':PREFIX,
        'human_message':SUFFIX,
        'template_tool_response':TEMPLATE_TOOL_RESPONSE,
        }
)
```

I'll try a PR, any thought about this @guidorietbroek ?

**Comment by hdnh2006** [comment]
> format_instructions=custom_format_instructions

This doesn't work, if you pass the `format_instructions` while you are initializing the agent, the template remains the same:
```

FORMAT_INSTRUCTIONS = "These are my new format_instructions"

agent = initialize_agent(
    agent = AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
    #agent = AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    tools = tools,
    #tools = load_knowledge_tools(),
    llm = llm_agent,
    verbose = True,
    max_iterations = 3,
    early_stopping_method = 'generate',
    memory = b_w_memory,
    handle_parsing_errors = True,
    format_instructions = FORMAT_INSTRUCTIONS
)

print(agent.agent.output_parser.get_format_instructions())
RESPONSE FORMAT INSTRUCTIONS
----------------------------

When responding to me, please output a response in one of two formats:

**Option 1:**
Use this if you want the human to use a tool.
Markdown code snippet formatted in the following schema:

```json
{{{{
    "action": string, \\ The action to take. Must be one of {tool_names}
    "action_input": string \\ The input to the action
}}}}
```

**Option #2:**
Use this if you want to respond directly to the human. Markdown code snippet formatted in the following schema:

```json
{{{{
    "action": "Final Answer",
    "action_input": string \\ You should put what you want to return to use here
}}}}
```
```
