### ISSUE TITLE
async mongodb chat message history 

### ISSUE THREAD

**Issue by ma2za** [langchain-ai/langchain#10729]
### Feature request

Switch to motor in the [MongoDBChatMessageHistory](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/chat_message_histories/mongodb.py) class for asyncio support.

### Motivation

There is already a PR #10645 for async Document Loader for MongoDB, this way we can keep consistency in the mongodb clients.

### Your contribution

I already implemented it, if you want  I can submit a PR.

**Comment by dRAT3** [comment]
Yo any progress on this?
