### ISSUE TITLE
Issue: How to update Pinecone vectors data using langchain

### ISSUE THREAD

**Issue by Satenderpal** [langchain-ai/langchain#10739]
### Issue you'd like to raise.

I am using langchain with Pinecone to push the embedding into the Pincone vector db. using below code. But I see that there is too many IDs created for the single PDF file in Pincone Browswer(My PDF file more than 250 pages). I want to update my PDF for the same Index. How can I do ?

`from langchain.document_loaders import UnstructuredPDFLoader, OnlinePDFLoader, PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma, Pinecone
from langchain.embeddings.openai import OpenAIEmbeddings
import pinecone
import os
from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain

loader = UnstructuredPDFLoader("example.pdf")
data = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=0)
texts = text_splitter.split_documents(data)
type(texts)

OPENAI_API_KEY = "sk-xxxxx"
PINECONE_API_KEY = "xxxx"
PINECONE_API_ENV = "us-west-gcp-free"

embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

pinecone.init(
    api_key=PINECONE_API_KEY,  
    environment=PINECONE_API_ENV
)
index_name = "langchaintest"
docsearch = Pinecone.from_texts([t.page_content for t in texts], embeddings, index_name=index_name)`

I want to update my vectors Due to multiple IDs I am not able to get the ID to update the New one PDF file

### Suggestion:

ID should be one for the single PDF file.

**Comment by Satenderpal** [comment]
@dosu-bot
Firstly I want to push data into pinecone in single Id for the single PDF file. When I followed your langchain documentation and create a sample program it creates too many IDs for the single pdf file. 
I want only single ID = for Single PDF file:
I am currently using below code , where can I need to update ?:
```
from langchain.document_loaders import UnstructuredPDFLoader, OnlinePDFLoader, PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma, Pinecone
from langchain.embeddings.openai import OpenAIEmbeddings
import pinecone
import os
from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain

loader = UnstructuredPDFLoader("example.pdf")
data = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=0)
texts = text_splitter.split_documents(data)
type(texts)

OPENAI_API_KEY = "sk-xxxxx"
PINECONE_API_KEY = "xxxx"
PINECONE_API_ENV = "us-west-gcp-free"

embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

pinecone.init(
api_key=PINECONE_API_KEY,
environment=PINECONE_API_ENV
)
index_name = "langchaintest"
docsearch = Pinecone.from_texts([t.page_content for t in texts], embeddings, index_name=index_name)
```

**Comment by Leon-Sander** [comment]
Hello, you can't stuff your 250 page pdf in one single vector. There is a maximum possible size, you are working with OpenAI Embeddings, they can encode 8k tokens at max. 
You defined: 
```
text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=0)
```
Therefore one vector is going to contain a token size that corresponds to a chunk_size of 2000 characters (since the lenght measuring function for RecursiveCharacterTextSplitter is len() which operates on characters), which would be something around 500 probably.

You have to take that into account when populating your vector database.
Hope this helps.
