### ISSUE TITLE
get_openapi_chain throws error when running example from docs

### ISSUE THREAD

**Issue by rubensmau** [langchain-ai/langchain#10733]
### System Info

pydantic    '1.10.0'   or '2.3.0'
langchain  '0.0.292'
python       '3.11.5'

### Who can help?

@hwchase17 
@agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chains.openai_functions.openapi import get_openapi_chain
chain = get_openapi_chain("https://www.klarna.com/us/shopping/public/openai/v0/api-docs/")
chain("What are some options for a men's large blue button down shirt")

Error message when running with pydantic 1
Unable to parse spec from source https://chat-web3-plugin.alchemy.com/openapi.yaml  error 

Error message when running with pydantic 2
AttributeError: type object 'OpenAPISpec' has no attribute 'from_url'

### Expected behavior

normal execution without errors

**Comment by kirankc** [comment]
Any fix for this? I used examples from the latest OpenAPI version - 3.1.0 and the issue still persists with the error "Unable to parse spec from source".

OpenAPI version - 3.1.0 Examples
https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.1/webhook-example.yaml

**Comment by kirankc** [comment]
If anyone runs into the same issue, I was able to resolve it by installing "openapi-schema-pydantic"

**Comment by landxman** [comment]
pip uninstall pydantic
pip install pydantic==1.10.9

**Comment by mzheng-sb** [comment]
same issue here...

**Comment by wingleungchoi** [comment]
fixed the issue by adding openapi-schema-pydantic  and downgrading pydantic to 1.10.9
```
poetry add openapi-schema-pydantic
poetry add pydantic==1.10.9
```

My environment
```
...
pydantic = "1.10.9"
openapi-schema-pydantic = "^1.2.4"
```
thank @landxman and @kirankc

**Comment by hpnrep6** [comment]
#9408 made the OpenAPI Spec dependency optional and #11936 carried over the optionality when openapi_schema_pydantic was switched to openapi_pydantic. I was able to run the example by installing openapi_pydantic.

Should the docs be updated to note that openapi_pydantic needs to be installed before running the example? @baskaryan 

Related: #9520

**Comment by cesdaile-te** [comment]
Still have the same issue with clean install on Colab following the example in langchain docs. workaround above did not resolve the `Unable to parse spec from source` error

**Comment by benm4nn** [comment]
same issue here...  :-(

**Comment by 3cha1n** [comment]
Solution for me on Colab at least (but maybe relevant to anyone with this issue) is that after noticing that `pip install openapi_schema_pydantic` simply didn't work (pip can't find the package, no doubt because there's no PyPi package for the Colab OS) I installed the package from github and that worked fine:
```
pip install git+https://github.com/kuimono/openapi-schema-pydantic.git@master
```

My specs:
```
Python 3.10.12
pydantic: 1.10.12
openapi-schema-pydantic: 1.2.4
langchain: 0.0.316
openai: 0.28.1
```

@cesdaile-te @benm4nn

**Comment by amirhoseinsh** [comment]
@3cha1n It did not work for me even after I installed openapi-schema-pydantic.

**Comment by 3cha1n** [comment]
@amirhoseinsh you're welcome to check my colab: https://colab.research.google.com/drive/1_8uunxIg9VDNC-Sm74lEvPVs9ai38Z43

**Comment by 3cha1n** [comment]
@Manouchehri Do you check openapi-schema-pydantic was installed successfully? I had to install openapi-schema-pydantic manually as follows:

`pip install git+https://github.com/kuimono/openapi-schema-pydantic.git@master`

**Comment by anujmehta** [comment]
Tried installing following, but the error still persists

```
i/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```

```
openapi-pydantic = "0.3.2"
langchain = "0.0.319"
```

**Comment by fquellec** [comment]
None of the above solutions worked for me. It seems that for the latest versions of langchain, you need to install `openapi-pydantic` : 

```
pip install openapi-pydantic
```

**Comment by YoungHS-NUS** [comment]
> None of the above solutions worked for me. It seems that for the latest versions of langchain, you need to install `openapi-pydantic` :
> 
> ```
> pip install openapi-pydantic
> ```

@fquellec's solution works for me. python version is 3.10.13
