### ISSUE TITLE
LLaMa-2-13B-chat deployed on azureml studio giving out of context response

### ISSUE THREAD

**Issue by Manikanta5112** [langchain-ai/langchain#10747]
### Issue you'd like to raise.

Recently, we re-deployed the llam2-13-B chat model on azure ML Studio, whenever we are trying to do in-contex learning (RAG QA), always replied back with out of context response.

Currently we are passing request payload as using langchain:

System prompt: sys msg + context
Human prompt: question
Response: out of context response

2nd variation:

Human prompt: context + question
Response: junk answers like \n

Any suggestions who have experienced?

And, we are also followed the required input format.

**Comment by eryk-dsai** [comment]
Hi,

From my experience: make sure that your entire prompt follows the Meta's guidelines as to how it should be format. There is ready to go method that formats the list of messages in the [unmerged PR](https://github.com/langchain-ai/langchain/blob/87597a10fac62ae342f7d137b22429a530849f28/libs/langchain/langchain/chat_models/huggingface_pipeline.py#L154) that you can copy.

Second, System prompt should contain the general description of what the model is expected to do, like "you will be given text passages and question. Answer the question using information from the context". Follow that up with the HumanMessage that contains context and question, `Passages: ... Question: ...` 

This should lead to better outputs
