### ISSUE TITLE
LLMSingleActionAgent Doesnot provide Expected response

### ISSUE THREAD

**Issue by Raji0196** [langchain-ai/langchain#10749]
### Issue you'd like to raise.

I am using LLMSingleActionAgent with ReAct Prompt. Most of the times it fails to give the proper response to the input. For example, when I greet the agent, it is not greeting back most of the times. Below is the response snippet

![image](https://github.com/langchain-ai/langchain/assets/77723011/82e15dd2-1dcc-4c55-b34d-a4a4199dce2b)

![image](https://github.com/langchain-ai/langchain/assets/77723011/14aebdb5-0c84-4e0a-8e9b-ffa98ff7e373)

**Below is my Agent code:**

agent = LLMSingleActionAgent(
    llm_chain=llm_chain,
    output_parser=output_parser,
    stop=["\nObservation:"],
    allowed_tools=tool_names
)

**Part of Prompt:**

You have access to the following tools. you can use tools, your Previous conversation history to answer the questions
{tools}

Previous Conversation history:
{history}

Use the following format:
Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, can be one of [{tool_names}] or {history}
Action Input: the input to the action
Observation: the result of the action
Thought: I now know the final answer
Final Answer: the final answer to the original input question

**Output Parser:**

class CustomOutputParser(AgentOutputParser):

    def parse(self, llm_output: str) -> Union[AgentAction, AgentFinish]:
        # Check if agent should finish
        if "Final Answer:" in llm_output:
            return AgentFinish(
                # Return values is generally always a dictionary with a single `output` key
                # It is not recommended to try anything else at the moment :)
                return_values={"output": llm_output.split("Final Answer:")[-1].strip()},
                log=llm_output,
            )
        # Parse out the action and action input
        regex = r"Action\s*\d*\s*:(.*?)\nAction\s*\d*\s*Input\s*\d*\s*:[\s]*(.*)"
        match = re.search(regex, llm_output, re.DOTALL)
        if not match:
            raise ValueError(f"Could not parse LLM output: `{llm_output}`")
        action = match.group(1).strip()
        action_input = match.group(2)
        # Return the action and action input
        return AgentAction(tool=action, tool_input=action_input.strip(" ").strip('"'), log=llm_output)

**Comment by rohit-pachar** [comment]
I am facing the same issue when using gemini models it is returning thought
