### ISSUE TITLE
Add optional embedding layer to agent tools

### ISSUE THREAD

**Issue by John-Church** [langchain-ai/langchain#1075]
Tools are currently chosen based on a prompt. If you have a few tools this works well but if you have dozens it will not. A possible solution is to optimally embed tool descriptions and have the agent choose tools based on top embeddings. This would allow applications to create highly specialized tools and pass in dozens of them to an agent minimizing errors over an application that adds a few tools which do many things.

**Comment by aristsakpinis93** [comment]
[This](https://github.com/hwchase17/langchain/blob/e63f9a846be7a85de7d3e3a1b277a4521b42808d/langchain/agents/agent.py#L707) is essentially where fuzzy matching could be applied through embeddings instead of using static string matching of dict keys.
