### ISSUE TITLE
pip install from source creates UNKNOWN package

### ISSUE THREAD

**Issue by bryfry** [langchain-ai/langchain#10760]
### System Info

Python Version: `Python 3.10.12`
LangChain Version: `master`

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Following [Getting Started - Installing - From Source](https://python.langchain.com/docs/get_started/installation#from-source)

```
python3 -m pip install -e .
```

Yields an install of `UNKNOWN` package due to missing `[project]` section in the `pyproject.toml`

```
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
```

### Expected behavior

```
Successfully built langchain
Installing collected packages: langchain
Successfully installed langchain-0.0.294
```

**Comment by hwchase17** [comment]
you are probably installing it in the wrong folder - you want to `cd libs/langchain` and then run this
