### ISSUE TITLE
Voice to text integration

### ISSUE THREAD

**Issue by John-Church** [langchain-ai/langchain#1076]
Would be incredible to have. Probably whisper to start. Happy to work on this after finishing up guards. Open to ideas for implementation.

**Comment by vvv-tech** [comment]
you're talking about this type of integration?
https://langchain.readthedocs.io/en/latest/reference/integrations.html
(i guess not, so please be more precise 🙂🙂)

i guess you're talking about creating example where you're using some Speech To Text model along with LLM
so i suggest it would be helpful for a ton of people if someone implement HF Pipeline with STT and LLM
for example:
- https://huggingface.co/facebook/wav2vec2-large-960h-lv60-self (STT)
- https://huggingface.co/EleutherAI/gpt-neo-1.3B (LLM)

and put this guide somewhere in 
https://langchain.readthedocs.io/en/latest/use_cases/chatbots.html
or better in self-created repository on Github with further adding link to it to documentation

**Comment by MikeMcGarry** [comment]
I've implemented this using Whisper (https://openai.com/research/whisper) to turn my voice into text to feed into the LLM and then using Eleven Labs (https://beta.elevenlabs.io/speech-synthesis) on the other end to turn the resulting completion into voice. It's pretty incredible and makes things way more real. 

https://github.com/hwchase17/langchain/assets/30035387/1aa2962e-1c2f-41c0-a2dc-0489b44c5321

Note that the `agent_chain` in the code below refers to an instance of a `ConversationalAgent` initialised outside this code block with access to an Evernote export which allows it to know what I like to eat for breakfast.

```
from pvrecorder import PvRecorder
from elevenlabs import generate, play
import openai

def print_prediction(prediction_text: str, type: str = "AI"):
    print("\n")
    print(f"{type}: ")
    for char in prediction_text:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(0.030)
    print("\n")

while True:
    recorder = PvRecorder(device_index=0, frame_length=512)
    audio_input = []
    try:
        recorder.start()
        print("Recording")
        while True:
            frame = recorder.read()
            audio_input.extend(frame)
    except KeyboardInterrupt:
        recorder.stop()
        print("Recording Complete")
        with wave.open("./tmp.wav", 'w') as f:
            f.setparams((1, 2, 16000, 512, "NONE", "NONE"))
            f.writeframes(struct.pack("h" * len(audio_input), *audio_input))
    finally:
        recorder.delete()

    with open("./tmp.wav", "rb") as file:
        user_input = openai.Audio.transcribe(model="whisper-1", file=file)

    write_input = Thread(target=print_prediction, kwargs={"prediction_text": user_input.text, "type": "Mike"})
    write_input.start()
    write_input.join()

    # create a completion
    prediction = agent_chain.run(input=user_input.text)
    audio = generate(
        text=prediction,
        voice="Adam",
        model="eleven_monolingual_v1"
    )

    play_prediction = Thread(target=play, kwargs={"audio": audio})
    write = Thread(target=print_prediction, kwargs={"prediction_text": prediction})
    play_prediction.start()
    write.start()
    play_prediction.join()
    write.join()
```

**Comment by MikeMcGarry** [comment]
How would we think about folding this into Langchain? Would it be something we create a class for that we can add into a chain at the start (voice to text) and end (text to voice) of the chain?

**Comment by agilebean** [comment]
@MikeMcGarry 
Thanks for sharing your solution. 
Do you think that a speed improvement could be achieved by writing the audio into memory and reading from it instead of read/write as `.wav` to the file system?
