### ISSUE TITLE
Using StructuredTool with agent

### ISSUE THREAD

**Issue by Zylon989** [langchain-ai/langchain#10778]
### System Info

Using this Code I am getting this error:
TypeError: Chain.__call__() got an unexpected keyword argument 'question'

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

  from pydantic import BaseModel, Field
  
  from langchain.chat_models import ChatOpenAI
  from langchain.agents import Tool
  from langchain.embeddings.openai import OpenAIEmbeddings
  from langchain.text_splitter import CharacterTextSplitter
  from langchain.vectorstores import FAISS
  from langchain.document_loaders import PyPDFLoader
  from langchain.chains import RetrievalQA
  from langchain.agents import initialize_agent
  from langchain.agents import AgentType
  from langchain.tools import StructuredTool
  from dotenv import load_dotenv
  class DocumentInput(BaseModel):
      question: str = Field()
  
  load_dotenv()
  
  llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613")
  
  tools = []
  files = [
      # https://abc.xyz/investor/static/pdf/2023Q1_alphabet_earnings_release.pdf
      {
          "name": "alphabet-earnings",
          "path": "/Users/harrisonchase/Downloads/2023Q1_alphabet_earnings_release.pdf",
      },
      # https://digitalassets.tesla.com/tesla-contents/image/upload/IR/TSLA-Q1-2023-Update
      {
          "name": "tesla-earnings",
          "path": "/Users/harrisonchase/Downloads/TSLA-Q1-2023-Update.pdf",
      },
  ]
  
  for file in files:
      loader = PyPDFLoader(file["path"])
      pages = loader.load_and_split()
      text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
      docs = text_splitter.split_documents(pages)
      embeddings = OpenAIEmbeddings()
      retriever = FAISS.from_documents(docs, embeddings).as_retriever()
  
      # Wrap retrievers in a Tool
      tools.append(
          StructuredTool.from_function(
              args_schema=DocumentInput,
              name=file["name"],
              description=f"useful when you want to answer questions about {file['name']}",
              func=RetrievalQA.from_chain_type(llm=llm, retriever=retriever),
          )
      )
  
  llm = ChatOpenAI(
      temperature=0,
      model="gpt-3.5-turbo-0613",
  )
  
  agent = initialize_agent(
      agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
      tools=tools,
      llm=llm,
      verbose=True,
  )
  
  agent({"input": "did alphabet or tesla have more revenue?"})

### Expected behavior

Compare the two documents!

**Comment by Zylon989** [comment]
@dosu-bot
I changed the code using this:
agent({"input": {"question": "did alphabet or tesla have more revenue?"}})

but still getting the same error: TypeError: Chain.call() got an unexpected keyword argument 'question' ??

**Comment by Zylon989** [comment]
@dosu-bot
Now I am getting the error:
ValueError: Missing some input keys: {'input'}

**Comment by Zylon989** [comment]
@dosu-bot
It's working with from langchain.chains.base import Chain
but now I am getting a new error : TypeError: Chain._call() missing 1 required positional argument: 'self'

**Comment by Zylon989** [comment]
@dosu-bot
But I am using an agent not an llm-chain! How to solve this using an agent?

**Comment by Zylon989** [comment]
@dosu-bot
Error:
    func=RetrievalQA.from_chain_type(llm=llm, retriever=retriever)(),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chain.__call__() missing 1 required positional argument: 'inputs'

**Comment by Zylon989** [comment]
@dosu-bot
Now I am getting again the error : TypeError: Chain._call() missing 1 required positional argument: 'self'

**Comment by Zylon989** [comment]
@dosu-bot
changed the code, but still getting the same error!
I am usind the RetrievalQA from langchain and imported like this
from langchain.chains import RetrievalQA

**Comment by itxabdullahbinasad** [comment]
@Zylon989 Hey zylon i am going through very similar problem did your problem get solved , plz let me know will be waiting for the response
