### ISSUE TITLE
Prompt was changed to different meaning

### ISSUE THREAD

**Issue by ch1zzzz** [langchain-ai/langchain#10789]
### System Info

I'm building a chatbot to introduce matching job openings from files to users. When the user input "I want to find a job", it is modified to "What kind of job are you looking for?" which ask the model what job he is looking for, but of course, it won't get an answer.

Human input: I want to find a job
Human input in Prompt after formatting: What kind of job are you looking for?
Chatbot: As an AI, I don't have personal preferences or the ability to look for a job.

Here is my prompt and conversation:
```
template = """ 
You are an AI assistant specifically tasked with finding matching
job opportunities in our job data based on user requests.

###
Context from data: {context}
###
{chat_history}

Human: {question}
Chatbot:"""

prompt = PromptTemplate(
input_variables=["question", "chat_history", "context"],
template=template
)
qa = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=db.as_retriever(),
    combine_docs_chain_kwargs={"prompt": prompt},
    memory=memory,
    verbose=True
)
```

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

template = """ 
You are an AI assistant specifically tasked with finding matching
job opportunities in our job data based on user requests.

###
Context from data: {context}
###
{chat_history}

Human: {question}
Chatbot:"""

prompt = PromptTemplate(
input_variables=["question", "chat_history", "context"],
template=template
)
qa = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=db.as_retriever(),
    combine_docs_chain_kwargs={"prompt": prompt},
    memory=memory,
    verbose=True
)

### Expected behavior

the prompt should be what user have input

**Comment by Tsukumizu** [comment]
@ch1zzzz 
Go deeper into your ConversationalRetrievalChain. You'll find that the culprit is condense_question_llm, declared as follows:

`condense_question_chain = LLMChain(
            llm=_llm,
            prompt=condense_question_prompt,
            verbose=verbose,
            callbacks=callbacks,
        )`

where a LLMchain is defined with a condense_question_prompt. Here is the content of this prompt:

`_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:"""
CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)`

You can modify it to return nothing.

**Comment by ch1zzzz** [comment]
> @ch1zzzz Go deeper into your ConversationalRetrievalChain. You'll find that the culprit is condense_question_llm, declared as follows:
> 
> `condense_question_chain = LLMChain( llm=_llm, prompt=condense_question_prompt, verbose=verbose, callbacks=callbacks, )`
> 
> where a LLMchain is defined with a condense_question_prompt. Here is the content of this prompt:
> 
> `_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.
> 
> Chat History: {chat_history} Follow Up Input: {question} Standalone question:""" CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)`
> 
> You can modify it to return nothing.

Thanks for your explanation!
