### ISSUE TITLE
GrobidParser: process_xml chunk_bboxes[0][0]["page"], IndexError: list index out of range

### ISSUE THREAD

**Issue by zaurask** [langchain-ai/langchain#10801]
Using the GrobidParser with `segment_sentences=False` results in `langchain/document_loaders/parsers/grobid.py", line 87, in process_xml
    chunk_bboxes[0][0]["page"],
IndexError: list index out of range` for some PDFs.

From my own testing with the offending PDFs I suspect the following if-block in the GrobidParser is indented incorrectly, it needs one more level of indentation. Adding this indentation solved the issue on my end.
https://github.com/langchain-ai/langchain/blob/20c6ade2fc24c458a080eaa468add7c61dc8dbc3/langchain/document_loaders/parsers/grobid.py#L80-L93

If you need a reproduction to verify, let me know.

**Comment by dddkhoa** [comment]
I also encounter this error when dealing with Grobid Parser.  The fix @zaurask said (to indent one more level for the `if segment_sentences is not True` block) works for me.

**Comment by gruenbergera** [comment]
I would also like to comment in support of @dddkhoa comment in support of @zaurask fix for the parser code.
