### ISSUE TITLE
MongoDBAtlasVectorSearch: Make It Work with Existing MongoDB Collection (rather than having to create a new one)

### ISSUE THREAD

**Issue by ghost** [langchain-ai/langchain#10820]
### Feature request

When using MongoDBAtlasVectorSearch, the user is limited to only first populate a MongoDB collection of documents using either add_document or add_text methods. Those methods create documents on the given collection using a fixed structure. What if the user already has a collection on MongoDB with custom structure (still containing the field 'embedding' which is used to measure similarity)? This is not currently supported and the user would have to implement a wrapper around MongoDBAtlasVectorSearch to achieve that. 

For instance the following code won't work (docs will be empty):
```
from langchain.vectorstores import MongoDBAtlasVectorSearch
from langchain.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
index_name = "index_name_from_MongoDB"

docsearch = MongoDBAtlasVectorSearch(embeddings, collection=collection, index_name=index_name)

query = "What did the president say about Ketanji Brown Jackson"
docs = docsearch.similarity_search(query)

print(docs[0].page_content)
```
This is because the collection is not populated using any of the original methods of MongoDBAtlasVectorSearch, e.g. add_document or add_text, hence the structure of the collection might be different (containing additional fields and missing the 'text' field for example).

**Comment by AthulVincent** [comment]
I was able to search in a collection with a custom structure using:
`vectorstore = MongoDBAtlasVectorSearch(collection, embeddings, text_key="new_text", embedding_key="new_emb")`
I also manually populated the document and the search was successful. I believe the functionality you are looking for already exists and is working as intended.
