### ISSUE TITLE
how to use LongContextReorder with RetrievalQAChain 

### ISSUE THREAD

**Issue by imhager** [langchain-ai/langchain#10834]
### Issue you'd like to raise.

in  docs，has a simple demo to use LongContextReorder to reorder docs.
but ,if i want use it with RetrievalQAChain ,how can i use it. thx

**Comment by pmespresso** [comment]
@dosu-bot

1 validation error for RetrievalQA
document_transformer
  extra fields not permitted (type=value_error.extra)

**Comment by devstein** [comment]
Hey @pmespresso As of now, Dosu only responds to the issue author. Stay tuned for changes to that soon :)

**Comment by pmespresso** [comment]
btw @imhager here's how I got it to work:

```
reordering = LongContextReorder()

pipeline_compressor = DocumentCompressorPipeline(
    transformers=[
        reordering
    ]
)

compression_retriever = ContextualCompressionRetriever(base_compressor=pipeline_compressor, base_retriever=vector_store.as_retriever())

qa = ConversationalRetrievalChain.from_llm(llm=llm, retriever=compression_retriever, memory=memory, return_source_documents=True)
```

**Comment by imhager** [comment]
> btw @imhager here's how I got it to work:
> 
> ```
> reordering = LongContextReorder()
> 
> pipeline_compressor = DocumentCompressorPipeline(
>     transformers=[
>         reordering
>     ]
> )
> 
> compression_retriever = ContextualCompressionRetriever(base_compressor=pipeline_compressor, base_retriever=vector_store.as_retriever())
> 
> qa = ConversationalRetrievalChain.from_llm(llm=llm, retriever=compression_retriever, memory=memory, return_source_documents=True)
> ```

thanks, i'll try it.

**Comment by pmespresso** [comment]
welp OpenAI now has 128k context lengths so I think this is all useless now

**Comment by imhager** [comment]
> welp OpenAI now has 128k context lengths so I think this is all useless now

i agree,As the length supported by the model grows,the need for reordering decreases

**Comment by weissenbacherpwc** [comment]
why do you think this is the case? The longer the context is, the more likely it is that "lost-in-the-middle" occurs if I understood this correctly

**Comment by imhager** [comment]
> why do you think this is the case? The longer the context is, the more likely it is that "lost-in-the-middle" occurs if I understood this correctly

yes, u r right. My scenario is to sort the query results through a vector library, hoping for better results
