### ISSUE TITLE
Issue: use QianfanChatEndpoint and RetrievalQA Error

### ISSUE THREAD

**Issue by liye199033** [langchain-ai/langchain#10831]
### Issue you'd like to raise.

`
llm = QianfanChatEndpoint(
    model="ChatGLM2-6B-32K",
    qianfan_ak="xxx",
    qianfan_sk="xxx"
)

embedding = ErnieEmbeddings(
  qianfan_ak="xxx",
  qianfan_sk="xxx"
)
db = Chroma.from_documents(texts, embedding)
retriever = db.as_retriever()

qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

qa.run("请问事项的名称是什么？")
`

an error occurred in the above code.

`
File "/Users/xxx/Workspace/xxx/smart_gov_nav/chatbot/venv/lib/python3.11/site-packages/langchain/chat_models/baidu_qianfan_endpoint.py", line 63, in convert_message_to_dict
    raise TypeError(f"Got unknown type {message}")
TypeError: Got unknown type content="Use the following pieces of context to answer the users question. \nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\n办事大厅名称\n " additional_kwargs={}
`

Because the type of message in the convert_message_to_dict argument is SystemMessage. That's why this error occurred. How to use it correctly?

**Comment by liye199033** [comment]
SystemMessage does not have a name attribute
@dosu-bot

**Comment by NuODaniel** [comment]
HI, thanks for using Qianfan, feel free to contact me if you have any problems. @liye199033
