### ISSUE TITLE
PyPDF2 used in Google Drive loader has vulnerability issues

### ISSUE THREAD

**Issue by joe-barhouch** [langchain-ai/langchain#10832]
### System Info

The GoogleDrive loader currently uses the PyPDF2 library instead of the PyPDF. 
Since PyPDF2 was already merged to the original one, it shouldn't be used anymore. 
[https://data.safetycli.com/v/59234/f17/?utm_source=pyupio&utm_medium=redirect&utm_campaign=pyup_rd&utm_id=081](url)
This is the vulnerability issue that gets picked up, note that it is fixed in PyPDF

Also I tried to change the loader using `file_loader_cls` but it just doesn't work 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

No functionality issue but https://data.safetycli.com/v/59234/f17/?utm_source=pyupio&utm_medium=redirect&utm_campaign=pyup_rd&utm_id=0817&utm_content=data showcases the bug

### Expected behavior

This error should not pop up

**Comment by joe-barhouch** [comment]
As for the `file_loader_cls`, I wanted to pass UnstructuredPDFLoader or PdfReader but those accept `file_path` argument and wont' work with the GoogleDriveLoader since it requires an IO loader

**Comment by ventz** [comment]
@joe-barhouch As an aside - I found it obnoxious that they don't support both file_path and BytesIO.

In our case, since I had read the files (from a context which provides me the bites), I used `tempfile` to create a file handle and passed that. (You can use `tempfile.name` for the object to pass to file_path, and it works perfectly)
