### ISSUE TITLE
Installing from source (pip install -e .) fails with multiple top-level packags found

### ISSUE THREAD

**Issue by ichernev** [langchain-ai/langchain#10844]
### System Info

Linux, Python 3.11.5

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. `python -m venv .venv`
2. `. .venv/bin/activate`
3. `pip install -e .`

### Expected behavior

To install package in a local virtualenv.

What happens:
```
% pip install -e .  
Obtaining file:///home/iskren/src/deepinfra/libs/langchain
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['libs', 'langchain'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by ichernev** [comment]
So you need to: `cd libs/langchain` and do `pip install -e .` from there...

**Comment by emhagman** [comment]
> So you need to: `cd libs/langchain` and do `pip install -e .` from there...

For anyone looking for a solution for `requirements.txt` here, you can use:
`langchain @ git+https://github.com/langchain-ai/langchain@master#subdirectory=libs/langchain`

The `#subdirectory=` feature is supported since

**Comment by qazwsx042** [comment]
The following approach solves my problem.

```python
from setuptools import setup, find_packages

setup(
    name="LangChain",
    version="0.0.312",
    packages=find_packages(),
)
```
