### ISSUE TITLE
Directory loader does not extract text between <strong> </strong> tags in HTML

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#10841]
### System Info

LANGCHAIN - 0.0.0286
OS - Windows

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

To reproduce, take a HTML document that has text between STRONG tags of HTML tags and extract using directoryloader

### Expected behavior

It should extract all the text from HTML

**Comment by rajib76** [comment]
But I think this is more than this. Sharing one more details the text is ignored only if the strong tag is within a div tag.

**Comment by andrewisplinghoff** [comment]
Cannot reproduce this bug with langchain==0.0.339, unstructured==0.10.30 and UnstructuredHTMLLoader. Can you try with the latest versions? If it still happens, can you please provide a full HTML file that allows to reproduce the problem?
