### ISSUE TITLE
create_conversational_retrieval_agent does not work with fallbacks

### ISSUE THREAD

**Issue by monilouise** [langchain-ai/langchain#10852]
### System Info

Langhchain version: 0.0.296
Python version: 3.9.7
Platform: Windows 10

### Who can help?

I need to implement a fallback for my RAG application based on Langchain conversational retrievers because my application  needs to use GPT 4 only for RAG and GPT 3.5 for generic questions (eg.: ChatGPT).  A way to implement this behaviour is by means of fallbacks, because infortunately create_conversational_retrieval_agent() enforces the same LLM for all the tools.  So, I wrote the following code:

```
short_llm = ChatOpenAI(
    deployment_id=DEPLOYMENT_NAME_GPT_3_5_4K,
    engine=DEPLOYMENT_NAME_GPT_3_5_4K,
    model_name=model_gpt_3_5_4k,
    temperature=0,
    openai_api_base=BASE_URL,
    openai_api_key=API_KEY,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

long_llm = ChatOpenAI(
    deployment_id=DEPLOYMENT_NAME_GPT_4_8K,
    engine=DEPLOYMENT_NAME_GPT_4_8K,
    model_name=model_gpt_4_8k,
    temperature=0,
    openai_api_base=BASE_URL,
    openai_api_key=API_KEY,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

chat_llm = short_llm.with_fallbacks([long_llm])
```

And to create the agent:

`agent_executor = create_conversational_retrieval_agent(chat_llm, tools, verbose=True, sytem_message=system_prompt, remember_intermediate_steps=False)`

But the following error occurs:

```
C:\ProgramData\Anaconda3\lib\site-packages\langchain\agents\agent_toolkits\conversational_retrieval\openai_functions.py in create_conversational_retrieval_agent(llm, tools, remember_intermediate_steps, memory_key, system_message, verbose, max_token_limit, **kwargs)
     58 
     59     if not isinstance(llm, ChatOpenAI):
---> 60         raise ValueError("Only supported with ChatOpenAI models.")
     61     if remember_intermediate_steps:
     62         memory: BaseMemory = AgentTokenBufferMemory(

ValueError: Only supported with ChatOpenAI models.
```

In fact, chat_llm has the following type: langchain.schema.runnable.base.RunnableWithFallbacks.  It apparently does not inherit ChatOpenAI .

Is there any workaround?  My requirement is to use long LLM for RAG/retriever tools and a short one for normal conversation with ChatGPT 3.5

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
short_llm = ChatOpenAI(
    deployment_id=DEPLOYMENT_NAME_GPT_3_5_4K,
    engine=DEPLOYMENT_NAME_GPT_3_5_4K,
    model_name=model_gpt_3_5_4k,
    temperature=0,
    openai_api_base=BASE_URL,
    openai_api_key=API_KEY,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

long_llm = ChatOpenAI(
    deployment_id=DEPLOYMENT_NAME_GPT_4_8K,
    engine=DEPLOYMENT_NAME_GPT_4_8K,
    model_name=model_gpt_4_8k,
    temperature=0,
    openai_api_base=BASE_URL,
    openai_api_key=API_KEY,
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()]
)

chat_llm = short_llm.with_fallbacks([long_llm])
```

And to create the agent:

`agent_executor = create_conversational_retrieval_agent(chat_llm, tools, verbose=True, sytem_message=system_prompt, remember_intermediate_steps=False)`

### Expected behavior

Conversational retrieval agents should be able to work with fallbacks.

**Comment by Tsukumizu** [comment]
Actually, a rewrited version of ConversationalRetrievalChain may be more suitable for your demands. You mention that "my application needs to use GPT 4 only for RAG and GPT 3.5 for generic questions", therefore, actually three chains are needed here. Look at the abstract pipeline below: 

A LLM chain to  judge "whether this question needs externel knowledge, return true or false";
Then, depending on the results, let's choose a chain from below:
a LLM chain to answer generic question like "Q: Thank you very much!" and it returns "You are welcome!"; 
A BaseCombineDocumentsChain to for RAG like "Q: Introduce the causes of leukemia? and it returns: "The causes of leukemia are......"

Due to confidentiality reasons, I cannot reveal the code I am working on to you. Here is an abstract version:
`convR_qa = NewConversationalRetrievalChain(
            retriever=retriever,
            memory=memory,
            
            intention_detector=intention_detector_chain,
            generic_chain=generic_chain,
            combine_docs_chain=combine_docs_chain,
        )`
If you delve into the structure of ConversationalRetrievalChain, I believe you will gain something.

**Comment by monilouise** [comment]
> Actually, a rewrited version of ConversationalRetrievalChain may be more suitable for your demands. You mention that "my application needs to use GPT 4 only for RAG and GPT 3.5 for generic questions", therefore, actually three chains are needed here. Look at the abstract pipeline below:
> 
> A LLM chain to judge "whether this question needs externel knowledge, return true or false"; Then, depending on the results, let's choose a chain from below: a LLM chain to answer generic question like "Q: Thank you very much!" and it returns "You are welcome!"; A BaseCombineDocumentsChain to for RAG like "Q: Introduce the causes of leukemia?" After retrieving the vectorDB, it returns: "The leukemia are usually caused by......"
> 
> Due to confidentiality reasons, I cannot reveal the code I am working on to you. Here is an abstract version: `convR_qa = NewConversationalRetrievalChain( retriever=retriever, memory=memory, intention_detector=intention_detector_chain, generic_chain=generic_chain, combine_docs_chain=combine_docs_chain, )` If you delve into the structure of ConversationalRetrievalChain, I believe you will gain something.

Thanks @Tsukumizu , I'll look at your suggestions and ConversationalRetrievalChain.

I notice that create_conversational_retrieval_agent() apparently does not use ConversationalRetrievalChain.  Does anyone know the reason?  Let me know if I should open a separate issue about it.

**Comment by Tsukumizu** [comment]
@monilouise 
You can refer to the official document https://python.langchain.com/docs/use_cases/question_answering/how_to/conversational_retrieval_agents
An agent component takes on most of the work. While reducing the workload, it also increases the difficulty of customization. From my own experience, ConversationalRetrievalChain is more suitable for your scenario.
