### ISSUE TITLE
The model appears to be missing from the _default_params method in the baidu_qianfan_endpoint.py file

### ISSUE THREAD

**Issue by liye199033** [langchain-ai/langchain#10867]
### System Info

langchain 0.0.295
python 3.11
os macOS 12.5 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The model appears to be missing from the _default_params method in the baidu_qianfan_endpoint.py file
`
    @property
    def _default_params(self) -> Dict[str, Any]:
        """Get the default parameters for calling OpenAI API."""
        normal_params = {
            "stream": self.streaming,
            "request_timeout": self.request_timeout,
            "top_p": self.top_p,
            "temperature": self.temperature,
            "penalty_score": self.penalty_score,
        }

        return {**normal_params, **self.model_kwargs}
`
Line 183 of the chat_completion.py file in the qianfan module failed to be executed.
`
    def do(
        self,
        model: Optional[str] = None,
        endpoint: Optional[str] = None,
        stream: bool = False,
        retry_count: int = 1,
        request_timeout: float = 60,
        backoff_factor: float = 0,
        **kwargs,
    ) -> QfResponse:
        """
        if model is EB, use EB SDK to deal with the request
        """
        if "messages" in kwargs and isinstance(kwargs["messages"], QfMessages):
            kwargs["messages"] = kwargs["messages"]._to_list()
        if not GLOBAL_CONFIG.DISABLE_EB_SDK:
            if model in ["ERNIE-Bot-turbo", "ERNIE-Bot"]:
                import erniebot  #line 183

                erniebot.ak = self._client._auth._ak
                erniebot.sk = self._client._auth._sk
                erniebot.access_token = self._client._auth.access_token()
                # compat with eb sdk
                if model == "ERNIE-Bot":
                    model = "ernie-bot-3.5"
                return erniebot.ChatCompletion.create(
                    model=model.lower(), messages=kwargs["messages"], stream=stream
                )
        return super().do(
            model,
            endpoint,
            stream,
            retry_count,
            request_timeout,
            backoff_factor,
            **kwargs,
        )
`

but even with model，baidu will return the following error

`
  File "/Users/xxx/Workspace/xxx/xxx/chatbot/venv/lib/python3.11/site-packages/erniebot/backends.py", line 113, in handle_response
    raise errors.InvalidParameterError(emsg)
erniebot.errors.InvalidParameterError: the length of messages must be an odd number
`

![image](https://github.com/langchain-ai/langchain/assets/131761099/6cb46e17-2a53-45c7-9b60-1e0f6b252947)

because there are two messages in the requested messages
 

### Expected behavior

able to return correct results

**Comment by liye199033** [comment]
I am using the RetrievalQA chain and the odd number error occurs
`
llm = QianfanChatEndpoint(
  qianfan_ak="xxx",
  qianfan_sk="xxx"
)

embedding = ErnieEmbeddings(
  qianfan_ak="xxx",
  qianfan_sk="xxx"
)
db = Chroma.from_documents(texts, embedding)
retriever = db.as_retriever()

qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

qa.run("请问事项的名称是什么？")
`

**Comment by liye199033** [comment]
@dosu-bot

**Comment by liye199033** [comment]
@dosu-bot

I am using the RetrievalQA chain and the odd number error occurs
`
llm = QianfanChatEndpoint(
qianfan_ak="xxx",
qianfan_sk="xxx"
)

embedding = ErnieEmbeddings(
qianfan_ak="xxx",
qianfan_sk="xxx"
)
db = Chroma.from_documents(texts, embedding)
retriever = db.as_retriever()

qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

qa.run("请问事项的名称是什么？")
`

**Comment by NuODaniel** [comment]
> @dosu-bot
> 
> I am using the RetrievalQA chain and the odd number error occurs ` llm = QianfanChatEndpoint( qianfan_ak="xxx", qianfan_sk="xxx" )
> 
> embedding = ErnieEmbeddings( qianfan_ak="xxx", qianfan_sk="xxx" ) db = Chroma.from_documents(texts, embedding) retriever = db.as_retriever()
> 
> qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)
> 
> qa.run("请问事项的名称是什么？") `

Hi, do you still get this problem, i tried to reproduce this issue by the following code(fix the ErnieEmbedding init fields name). As a result, not error thrown. 
- langchain 0.0.300

```
from langchain.chat_models import QianfanChatEndpoint
from langchain.embeddings import ErnieEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA

llm = QianfanChatEndpoint(
qianfan_ak="your_ak",
qianfan_sk="your_sk"
)

embedding = ErnieEmbeddings(
ernie_client_id="your_ak",
ernie_client_secret="your_sk"
)

texts = ["hi", "qianfan"]
from langchain.schema import Document

db = Chroma.from_documents([Document(page_content=text) for text in texts], embedding)
retriever = db.as_retriever()

qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

qa.run("请问事项的名称是什么？")
```
