### ISSUE TITLE
Issue: How to set the language (default is English) when using UnstructuredImageLoader with PaddleOCR

### ISSUE THREAD

**Issue by jonlimx** [langchain-ai/langchain#10876]
### Issue you'd like to raise.

I am using langchain.document_loaders.image.UnstructuredImageLoader to load data from an image with a table on it. I chose PaddleOCR by setting os.environ["TABLE_OCR"] = "paddle" . However, I didn't find a place to set the detection language to other language. Could you please let me know how to do it. I have gotten stuck on it for a while.

**Comment by jonlimx** [comment]
@dosu-bot how to choose a ocr lib for UnstructuredImageLoader?

**Comment by Moibe** [comment]
Same warning: Warning: No languages specified, defaulting to English. It appear using it individually: 
loader = UnstructuredPDFLoader(file_path=file_path) there is no parameter to define language but yet the warning keeps popping when: data = loader.load()
