### ISSUE TITLE
langchain.chat_models import fails

### ISSUE THREAD

**Issue by mstyer-google** [langchain-ai/langchain#10887]
### System Info

Langchain: 0.0.81
Python: 3.11.5
System: Ubuntu

Trying to install Langchain and run the basic Quick Start sample code. Importing langchain.chat_models thows a ModuleNotFoundError.

```
$ python3
Python 3.11.5 (main, Aug 25 2023, 07:43:52) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from langchain.llms import OpenAI
>>> from langchain.chat_models import ChatOpenAI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'langchain.chat_models'
```

Any suggestions?

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

1. pip install langchain[all]
2. run python3 REPL
3. try to import langchain.chat_models

### Expected behavior

chat_models import succeeds.

**Comment by leo-gan** [comment]
It was solved with updating LangChain to new version.

**Comment by PriyanshuRanjann** [comment]
ImportError: cannot import name 'LangSmithParams' from 'langchain_core.language_models.chat_models' (c:\Users\Admin\anaconda3\Lib\site-packages\langchain_core\language_models\chat_models.py)

How to solve this?
