### ISSUE TITLE
"Minimax" object has no field "_client"

### ISSUE THREAD

**Issue by cclc** [langchain-ai/langchain#10917]
### System Info

when I run this command `python3 ./libs/langchain/tests/integration_tests/llms/test_minimax.py`
It always reports this error `ValueError: "Minimax" object has no field "_client"`

After I replaced "_client" with "client", it works.

version is `langchain==0.0.297`

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

python3 ./libs/langchain/tests/integration_tests/llms/test_minimax.py

### Expected behavior

Don't throw erros

**Comment by cclc** [comment]
In v0.0.299, This problem still exists

**Comment by zirenlegend** [comment]
In v0.0.312, This problem still exists

**Comment by hunter-xue** [comment]
this should be an issue of pydantic v1, looks like pydantic v2 fix it. so the better way to resolve this problem is: DON'T use underscore as pylthon method name.

**Comment by geezerrrr** [comment]
Has this problem been resolved?

**Comment by oldpiao** [comment]
这个问题还没有解决吗？我在0.2.15上依然遇到了此问题
