### ISSUE TITLE
LocalAI embeddings shouldn't require OpenAI

### ISSUE THREAD

**Issue by jamesbraza** [langchain-ai/langchain#10912]
### System Info

macOS Ventura 13.5.2, M1

### Who can help?

@mudler 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://github.com/langchain-ai/langchain/blob/v0.0.298/libs/langchain/langchain/embeddings/localai.py#L197

### Expected behavior

Why does LocalAI embeddings require OpenAI?  I think LocalAI's embeddings has no need for OpenAI, it has a whole embeddings suite: https://localai.io/features/embeddings/

I think it should be directly usable with its [`/embeddings` endpoint](https://github.com/go-skynet/LocalAI/blob/v1.25.0/api/api.go#L190)

**Comment by jamesbraza** [comment]
Thank you @dosu-beta.  The [docstring in `LocalAIEmbeddings`](https://github.com/langchain-ai/langchain/blob/v0.0.298/libs/langchain/langchain/embeddings/localai.py#L123) is clear about `openai` being required, with OpenAI keys configured.  I think it should be opt-in for added behaviors, but not required by default

**Comment by mudler** [comment]
The LocalAI embeddings are using the OpenAI library as there is 1:1 compatibility with their API. There is no need of an API key, what's the issue here?

**Comment by jamesbraza** [comment]
Ha you're right, I was definitely reading too quickly.  I saw use of `openai` package, the need to set `OPENAI_API_KEY`, and all the validations around OpenAI env vars, and I didn't keep reading to see `OPENAI_API_KEY` was being set to a random string.

I opened https://github.com/langchain-ai/langchain/pull/10946 to better document this design choice.

**Comment by mkhludnev** [comment]
If it's required, let's bump it #22399
