### ISSUE TITLE
Optimization by PROmpting (OPRO)

### ISSUE THREAD

**Issue by leo-gan** [langchain-ai/langchain#10913]
### Feature request

[LARGE LANGUAGE MODELS AS OPTIMIZERS](https://arxiv.org/pdf/2309.03409.pdf) is promising method to optimize prompts, to find the best prompts.
Not sure the LangChain is the best tool to apply this method but Hey, it is LangChain :exclamation: 

### Motivation

For workflows that use a stable prompts, this method could significantly improve results. 
So, there is definitely a valid use case for it.

### Your contribution

Not sure I can do it. Sorry.

**Comment by Aditya-k-23** [comment]
I am looking into contributing to this issue, can you provide a more comprehensive acceptance criteria with specific metrics that we aim to improve

**Comment by leo-gan** [comment]
In paper, authors use `accuracy` as a metric. Is that what you asking for?

**Comment by vsokolovskii** [comment]
@Aditya-k-23 have you started working on it? I'd like to contribute too, we can collaborate on this one if you're open :)

**Comment by vsokolovskii** [comment]
@leo-gan, I see that you're one of the main contributors here, where would you put this feature in the library? Is it just a new chain or sth more which needs a dedicated package alongside with agents and chains?

**Comment by leo-gan** [comment]
> @leo-gan, I see that you're one of the main contributors here, where would you put this feature in the library? Is it just a new chain or sth more which needs a dedicated package alongside with agents and chains?

@hwchase17 Do you want to answer to it?
