### ISSUE TITLE
Disable Retry on Timeout

### ISSUE THREAD

**Issue by totalhack** [langchain-ai/langchain#1094]
The OpenAI API has been quite unreliable this week and I am getting a bunch of timeouts. I don't want langchain to retry as I'm pretty sure OpenAI is still counting these requests toward billing, so I'd like to set max_retries=None or 0 but that doesn't seem to work.

**Comment by hwchase17** [comment]
setting `max_retries=0` seems to work for me - what issue are you seeing?

**Comment by totalhack** [comment]
That didn't work for me. I'll have to test again though.

**Comment by asmithar** [comment]
This doesn't seem to work for me either. I passed max_retries=0. This is my code : 
 LLMChain(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=-1, max_retries=0),
                             prompt=prompt)
