### ISSUE TITLE
Issue: getting ValueError(f"One output key expected, got {outputs.keys()}") in a ConversationalRetrievalChain  call

### ISSUE THREAD

**Issue by paulfields** [langchain-ai/langchain#10953]
### Issue you'd like to raise.

Not sure this is the right place to raise this, but I'm having difficulty with the return value of ConversationalRetrievalChain (called "qa" in my code) when return_source_documents=True.  The object returned is (I believe) a python dictionary object with two keys, "answer" and "source_documets". When I  execute the folllwing line <output = self.qa({"question": question})> I get an error back that reads ValueError(f"One output key expected, got {outputs.keys()}").

Any help on why this is happening and how I can fix?

**Comment by keenborder786** [comment]
@paulfields , can you please post a snippet of your code that you are trying to execute and it will also be great if you can post a traceback of your error.

**Comment by paulfields** [comment]
Thanks - I went a different direction with the code. Response was much appreciated.
