### ISSUE TITLE
Streaming not working with langchain

### ISSUE THREAD

**Issue by shrikant14** [langchain-ai/langchain#1096]
Snippet:
llm = OpenAI(streaming=True,
                 callback_manager=AsyncCallbackManager([StreamingLLMCallbackHandler(websocket)]),
                 verbose=True,
                 temperature=0)
chain = load_qa_chain(llm, chain_type="stuff",callback_manager= AsyncCallbackManager([]) )
a=await chain.arun(input_documents=docs, question=question)

Error:
  File "/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 230, in acreate
    return (TypeError: 'async_generator' object is not iterable

**Comment by hwchase17** [comment]
@agola11 any ideas?

**Comment by agola11** [comment]
Can you post the full trace, and try updating your openai package? Also no need to pass in empty `AsyncCallbackManager` in `load_qa_chain`

**Comment by agola11** [comment]
It seems related to this issue, which was fixed last month https://github.com/openai/openai-python/issues/171
