### ISSUE TITLE
DOC: HuggingFacePipeline.from_model_id throws Value error

### ISSUE THREAD

**Issue by pranavbhat12** [langchain-ai/langchain#10985]
### Issue with current documentation:

I tried to load LLama2-7b model from huggingface using HuggingFacePipeline.from_model_id but throws a value error: ValueError: The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please discard the `device` argument when creating your pipeline object.

Here is my Code:
compute_dtype=getattr(torch,"float16")
bnb_config=BitsAndBytesConfig(
      load_in_4bit=True,
      bnb_4bit_quant_type="nf4",
      bnb_4bit_compute_dtype=compute_dtype,
      bnb_4bit_use_double_quant=True,
  )

 model_name="meta-llama/Llama-2-7b-hf"

llm = HuggingFacePipeline.from_model_id(
      model_id=model_name,
      task="text-generation",
      pipeline_kwargs={
          "return_full_text":True,  # langchain expects the full text
          "temperature":0.5,  # 'randomness' of outputs, 0.0 is the min and 1.0 the max
          "max_new_tokens":512,  # max number of tokens to generate in the output
          "repetition_penalty":1.1, 
          "return_dict_in_generate":True,
          },
      model_kwargs={
          "quantization_config":bnb_config,
      }
  )

Logs:

WARNING:langchain.llms.huggingface_pipeline:Device has 1 GPUs available. Provide device={deviceId} to `from_model_id` to use availableGPUs for execution. deviceId is -1 (default) for CPU and can be a positive integer associated with CUDA device id.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-14e8e7a13801>](https://localhost:8080/#) in <cell line: 1>()
----> 1 llm=prepare_model()

[/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py](https://localhost:8080/#) in __init__(self, model, tokenizer, feature_extractor, image_processor, modelcard, framework, task, args_parser, device, torch_dtype, binary_output, **kwargs)
    788 
    789         if hf_device_map is not None and device is not None:
--> 790             raise ValueError(
    791                 "The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please "
    792                 "discard the `device` argument when creating your pipeline object."

ValueError: The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please discard the `device` argument when creating your pipeline object.

Is it problem with Langchain?

**Comment by pranavbhat12** [comment]
Even Setting device=0 getting same ValueError.

**Comment by eryk-dsai** [comment]
Hi, I addressed your issue in the [PR](https://github.com/langchain-ai/langchain/pull/11009). I think you don't need to pass `return_full_text` parameter and more importantly you shouldn't pass `return_dict_in_generate` set to `True` because you will get error

**Comment by jediyoda36** [comment]
is it possible to use multi-gpus ?

**Comment by GonyRosenman** [comment]
i am experiencing the same issue, i have accelerate and a multi-GPU environment, 

my code:

`hf = HuggingFacePipeline.from_model_id(
                model_id=self.config['instruction_model'],
                task="text-generation",
                pipeline_kwargs={"max_new_tokens": 1000},
                model_kwargs={'device_map':'auto','offload_folder': self.config['model_kwargs'].get('offload_folder')})
            return hf`
            
if i don't set device_map auto, the model is loaded to CPU. if i do set it, i receive this error:

`File "/home/miniconda3/envs/psyq/lib/python3.9/site-packages/langchain_community/llms/huggingface_pipeline.py", line 152, in from_model_id
    pipeline = hf_pipeline(
  File "/home/miniconda3/envs/psyq/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 1070, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
  File "/home/miniconda3/envs/psyq/lib/python3.9/site-packages/transformers/pipelines/text_generation.py", line 70, in __init__
    super().__init__(*args, **kwargs)
  File "/home/miniconda3/envs/psyq/lib/python3.9/site-packages/transformers/pipelines/base.py", line 799, in __init__
    raise ValueError(
ValueError: The model has been loaded with `accelerate` and therefore cannot be moved to a specific device. Please discard the `device` argument when creating your pipeline object.
python-BaseException`
