### ISSUE TITLE
Issue: I want to load SitemapLoader but only 2023 lastmod pages.

### ISSUE THREAD

**Issue by DonTizi** [langchain-ai/langchain#10981]
### Issue you'd like to raise.

Hi , I'm using the SiteMap Loader as a document Loader , and I want to filter the lastmod metadata for the 2023 year only and nothing else, is it possible? 

Here is my code:
`# fixes a bug with asyncio and jupyter
import nest_asyncio
nest_asyncio.apply()

from langchain.document_loaders.sitemap import SitemapLoader

loader = SitemapLoader(
    "https:www.example.ca.sitemap.xml",
    filter_urls=["https://www.example.ca/en/"]
)
docs = loader.load()`

**Comment by RayaneMelDz** [comment]
@dosu-bot , how to implement it in my code
