### ISSUE TITLE
Error with db = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory=persist_directory)

### ISSUE THREAD

**Issue by paulfields** [langchain-ai/langchain#10990]
### Issue you'd like to raise.

When I run the following line:
db = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory=persist_directory)

I get the error "You are using a deprecated configuration of Chroma."

I need to know what the new form of Chroma.from_documents() function is so that I can specify a persistent directory.

**Comment by paulfields** [comment]
This answer is not correct - it notes the very same syntax I used in my question:
db = Chroma.from_documents(docs, embedding_function, ids=None, collection_name="langchain", persist_directory="./chroma_db")

This function call has been deprecated.

Please provide an updated syntax to call Chroma.from_documents.

Thanks

**Comment by yashskhandelwal** [comment]
+1

**Comment by yashskhandelwal** [comment]
Noticed the same issue locally, so moved to FAISS DB. This needs to be fixed.

**Comment by grim-reapper** [comment]
> ### Issue you'd like to raise.
> When I run the following line: db = Chroma.from_documents(documents=chunks, embedding=embeddings, persist_directory=persist_directory)
> 
> I get the error "You are using a deprecated configuration of Chroma."
> 
> I need to know what the new form of Chroma.from_documents() function is so that I can specify a persistent directory.
> 
> ### Suggestion:
> _No response_

I'm facing exactly the same issue. Do you find any solution?

**Comment by paulfields** [comment]
This is what ended up working
db = Chroma.from_documents(documents=chunks, embedding=embeddings,collection_name=collection_name, persist_directory=persist_db)
