### ISSUE TITLE
Issue: <Retrieval QA returns empty result>

### ISSUE THREAD

**Issue by theoflaus** [langchain-ai/langchain#11015]
### Issue you'd like to raise.

I have a simple Retrieval QA chain that used to work proprerly. Here's an example : 
![image](https://github.com/langchain-ai/langchain/assets/48955402/7242d7b9-e11a-4a00-8070-bf53b7d6c708)

But now, without any modifications to the code, it always returns me an empty string as a result : 
![image](https://github.com/langchain-ai/langchain/assets/48955402/9a71c72e-e7f8-4b37-a7bf-1298f0ef3811)

Any idea why ?

**Comment by Dafterfly** [comment]
I also had this problem, the issue might be with llama-cpp. After I ran `pip install --upgrade llama-cpp-python` I was able to get an answer

**Comment by dobahoang** [comment]
@dosu-bot
i got same error when use version langchain 0.1.6
The probability that I get an empty RESULT is 80%, the remaining 20% I get the result from retrieval (in conditions where the prompt is quite long due to using several shots, chroma db, LCEL, ....)
