### ISSUE TITLE
Issue: How to use custom prompt template with retrievalqa chain

### ISSUE THREAD

**Issue by chank20** [langchain-ai/langchain#11014]
### Issue you'd like to raise.

The goal is to use custom prompt template with retrievalqa chain. I have included my code below. You can see that PromptTemplate includes the input variables ['context', 'persona', 'question'], but I can't figure out where to pass in the 'persona' variable. Some examples of a  'persona' variable would be "Pirate" or "Shakespeare" to get the LLM to respond like a pirate or Shakespeare. The 'persona' variable is a simplification of the real question, which is how to use custom input variables and custom PromptTemplate with RetrievalQA chain. 

This may stem from not understanding RetrievalQA chain under the hood. You'll notice that when I call the chain, I need to pass in only the "query" parameter (which is not an input variable from the custom promptTemplate). I don't understand this as well: where do the input variables "context" and "question" go?

```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.document_loaders import PyPDFLoader
from langchain.chat_models import ChatOpenAI
from langchain.text_splitter import TokenTextSplitter
from langchain import PromptTemplate

import os
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY

# Define the LLM
# llm = ChatOpenAI(temperature=0,model_name="gpt-4")
llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo")

# Data Ingestion
loader = PyPDFLoader("../data/Batman_wiki.pdf")
pages = loader.load()

# Chunk and Embeddings
text_splitter = TokenTextSplitter(chunk_size=100, chunk_overlap=0)
texts = text_splitter.split_documents(pages)

embeddings = OpenAIEmbeddings()

# Vector Store
db = Chroma.from_documents(documents=texts, embedding=embeddings)

# Create Prompt
template = """Use the following pieces of context to answer the question at the end. 
If you don't know the answer, just say that you don't know.
Don't try to make up an answer.
{context}

Respond in the persona of {persona}

Question: {question}
Answer: 
"""

prompt = PromptTemplate.from_template(template)

# Initialise RetrievalQA Chain
chain = RetrievalQA.from_chain_type(
    llm,
    retriever=db.as_retriever(),
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt},
    # persona="Shakespeare"
)

response = chain({"query": question, "persona": "Shakespeare"})

print(response) 
```

**Comment by chank20** [comment]
Okay that makes sense, but still doesn't answer the question of "where do I pass in the 'persona' variable?" in the RetreivalQA Chain?

**Comment by DmitryKatson** [comment]
+1 Have the same question here

**Comment by seanroades** [comment]
+1

**Comment by mkopani** [comment]
+1

**Comment by sumitkapar** [comment]
hi  @dosu-bot , @dosu-beta  : My question is similar to the question asked above : 
I am not able to figure out how we can pass variale to the input_variable in prompt : 

prompt_with_loader = PromptTemplate(
    input_variables=["query", "username", "password"],
    template=
    """
    Based on the instruction you are tasked to construct a Python script that performs the following action: {query}. Utilize the specifics in the given API documentation to understand the required endpoint, method, and parameters.

    Credentials for authentication:
    Username: {username}
    Password: {password}

    Please create a Python script using the 'requests' library to execute the desired action. Ensure the script includes:
    - Parsing of the necessary details from the API specification
    - Basic Authentication with the provided username and password (encoded in Base 64)
    - Proper use of the relevant HTTP method, headers, body, and parameters as per the API specification
    - print the response of the api
    - Error handling for the request
    """
)
chain_type_kwargs = {"prompt": prompt_with_loader} , 

**qa_chain = RetrievalQAWithSourcesChain.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        chain_type_kwargs=chain_type_kwargs,
        return_source_documents=False,
        verbose=True
        )**. // when i am goining to hit this block it gives me this ERRR :  document_variable_name summaries was not found in llm_chain input_variables: ['query', 'username', 'password'] (type=value_error)   
        
        pls can you guide us here

**Comment by cy-artmobile** [comment]
The below worked for me (just used normal chaining with a prompt):

retriever = vectordb.as_retriever()

template = '''Below is an instruction that describes a task. Write a response that appropriately completes the request

# ### Instruction: {prompt}

# ### Response:'''
prompt_template = PromptTemplate.from_template(template)

qa = RetrievalQA.from_chain_type(
    llm=llm, 
    chain_type="stuff", 
    retriever=retriever, 
    verbose=True,
)

**question = """How to perform INNER JOINS in SQL?"""**

**chain = prompt_template | qa**

**answer = chain.invoke({"prompt": question})**

**Comment by meet1919** [comment]
You add extra data in `partial_variables`

```python
prompt = PromptTemplate(
    template=template, 
    input_variables=[
        'context', 
        'question',
    ],
    partial_variables={'persona': persona}
)

# Initialise RetrievalQA Chain
chain = RetrievalQA.from_chain_type(
    llm,
    retriever=db.as_retriever(),
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt}
)

response = chain({"query": question})

print(response) 
```

**Comment by mingjun1120** [comment]
> You add extra data in `partial_variables`
> 
> **EDIT**: Partial variables doesnt work in RetrievalQA chain. Not what I expected and throws `KeyError`
> 
> ```python
> template = '''
> If you don't know the answer, just say that you don't know.
> Don't try to make up an answer.
> {context}
> 
> Respond in the persona of %s
> 
> Question: {question}
> Answer:
> '''
> prompt = PromptTemplate(
>     template=template % (persona), 
>     input_variables=[
>         'context', 
>         'question',
>     ]
> )
> 
> # Initialise RetrievalQA Chain
> chain = RetrievalQA.from_chain_type(
>     llm,
>     retriever=db.as_retriever(),
>     return_source_documents=True,
>     chain_type_kwargs={"prompt": prompt}
> )
> 
> response = chain({"query": question})
> 
> print(response) 
> ```

What if I have more than 1 `partial variables`, how can I pass it into my prompt template?

**Comment by grafuls** [comment]
you need to include the persona on the prompt and pass it on the chain:

```python
template = '''
If you don't know the answer, just say that you don't know.
Don't try to make up an answer.
{context}

Respond in the persona of {persona}

Question: {question}
Answer:
'''
prompt = PromptTemplate(
    template=template, 
    input_variables=[
        'context', 
        'persona',
        'question',
    ]
)

# Initialise RetrievalQA Chain
chain = RetrievalQA.from_chain_type(
    llm,
    retriever=db.as_retriever(),
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt}
)

response = chain({"query": question, "persona": persona})

print(response) 
```

**Comment by meet1919** [comment]
> > You add extra data in `partial_variables`
> > **EDIT**: Partial variables doesnt work in RetrievalQA chain. Not what I expected and throws `KeyError`
> > ```python
> > template = '''
> > If you don't know the answer, just say that you don't know.
> > Don't try to make up an answer.
> > {context}
> > 
> > Respond in the persona of %s
> > 
> > Question: {question}
> > Answer:
> > '''
> > prompt = PromptTemplate(
> >     template=template % (persona), 
> >     input_variables=[
> >         'context', 
> >         'question',
> >     ]
> > )
> > 
> > # Initialise RetrievalQA Chain
> > chain = RetrievalQA.from_chain_type(
> >     llm,
> >     retriever=db.as_retriever(),
> >     return_source_documents=True,
> >     chain_type_kwargs={"prompt": prompt}
> > )
> > 
> > response = chain({"query": question})
> > 
> > print(response) 
> > ```
> 
> What if I have more than 1 `partial variables`, how can I pass it into my prompt template?

Write multiple `%s` in the prompt
