### ISSUE TITLE
AnthropicFunctions with Bedrock

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#11045]
### Feature request

Hi, I'm using the Anthropic Claude V2 model through Amazon Bedrock. I'd like to submit a feature request for function calling simialr to `langchain_experimental.llms.anthropic_functions.AnthropicFunctions`

### Motivation

A large amount of people are using Anthropic's models through Bedrock

### Your contribution

Not sure

**Comment by heythisischris** [comment]
For anyone who's interested, I'm working on a package which provides barebones function calling for Anthropic Claude V2 model through Amazon Bedrock: https://www.npmjs.com/package/bedrock-node.

It's inspired by the XML encoding solution suggested by Anthropic and implemented by Langchain.

**Comment by metaskills** [comment]
>  I'm working on a package which provides barebones 

Thank you for your open-source work. This is the Python repo. Also, your solution seems to eject full force from [LangChainJS](https://github.com/langchain-ai/langchainjs) which seems to support this work already?

- https://github.com/langchain-ai/langchainjs/pull/2892

But some issues seem to suggest not?

- https://github.com/langchain-ai/langchainjs/issues/3140
- https://github.com/langchain-ai/langchainjs/issues/2907
