### ISSUE TITLE
Validation errors for SQLDatabaseSequentialChain

### ISSUE THREAD

**Issue by anumoysengupta** [langchain-ai/langchain#11084]
### System Info

![image](https://github.com/langchain-ai/langchain/assets/9436757/3e5a6899-c01f-45ef-9458-942d69f3fe38)
My Langchain is upto date and credentials are also perfectly fine. 
I am importing SQLDatabaseSequentialChain from langchain_experimental.sql package

Still I am getting the following error. Any support would be definitely helpful.

### Who can help?

@eyurtsev @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

!pip install langchain==0.0.302
!pip install --user --upgrade langchain.experimental

### Expected behavior

This statement will not generate any output but it will execute without any error. Now its giving me error

**Comment by keenborder786** [comment]
@anumoysengupta will be happy to help. Can you please post of your code???
