### ISSUE TITLE
web_base loader is broken 

### ISSUE THREAD

**Issue by DmitryKatson** [langchain-ai/langchain#11095]
### System Info

Name: langchain
Version: 0.0.299

### Who can help?

@eyurtsev @hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Just follow https://python.langchain.com/docs/integrations/document_loaders/web_base

```
from langchain.document_loaders import WebBaseLoader
loader = WebBaseLoader("https://www.espn.com/")
data = loader.load()
```

### Expected behavior

The standard WebLoader is broken when we pass webpath as described in the [docs](https://python.langchain.com/docs/integrations/document_loaders/web_base) as 
`loader = WebBaseLoader("https://www.espn.com/")`

However it workes if we pass as
`loader = WebBaseLoader(["https://www.espn.com/"])`

The reason for that is [this commit](https://github.com/langchain-ai/langchain/commit/097ecef06bbc51ae21e134af4dfbb4ebe4902f3a)

Also because of this breaking change the other Custom Web Loaders  are broken as well IMSDbLoader, AZLyricsLoader, and CollegeConfidentialLoader

**Comment by DmitryKatson** [comment]
This is not very useful as web_base loader doesn't work as it's written in the docs. The team should fix the web_base loader or change the docs and all dependent loaders

**Comment by JahangirJadi** [comment]
from langchain.document_loaders import WebBaseLoader
from langchain.indexes import VectorstoreIndexCreator

url = 'https://lilianweng.github.io/posts/2023-06-23-agent/'
loader = WebBaseLoader(URL)

This made me crazy.

loader.load not working. Please fix it.

error:
436 raise InvalidURL(*e.args)
438 if not scheme:
--> 439 raise MissingSchema(
440 f"Invalid URL {url!r}: No scheme supplied. "
441 f"Perhaps you meant https://github.com/langchain-ai/langchain/issues/3542{url}?"
442 )
444 if not host:
445 raise InvalidURL(f"Invalid URL {url!r}: No host supplied")

MissingSchema: Invalid URL 'h': No scheme supplied. Perhaps you meant [https://h?](https://h/?)

**Comment by DmitryKatson** [comment]
> from langchain.document_loaders import WebBaseLoader from langchain.indexes import VectorstoreIndexCreator
> 
> url = 'https://lilianweng.github.io/posts/2023-06-23-agent/' loader = WebBaseLoader(URL)
> 
> This made me crazy.
> 
> loader.load not working. Please fix it.
> 
> error: 436 raise InvalidURL(*e.args) 438 if not scheme: --> 439 raise MissingSchema( 440 f"Invalid URL {url!r}: No scheme supplied. " 441 f"Perhaps you meant [https://github.com/langchain-ai/langchain/issues/3542{url}](https://github.com/langchain-ai/langchain/issues/3542%7Burl%7D)?" 442 ) 444 if not host: 445 raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
> 
> MissingSchema: Invalid URL 'h': No scheme supplied. Perhaps you meant [https://h?](https://h/?)

@JahangirJadi 
So as a quick workaround solution this works.

url = 'https://lilianweng.github.io/posts/2023-06-23-agent/'
loader = WebBaseLoader(**[**URL**]**)

**Comment by selfmeister** [comment]
worked for me:
`# Set web_paths as a list containing a single URL if web_path is a string
        if isinstance(web_path, str):
            self.web_paths = [web_path]
        else:
            self.web_paths = list(web_paths)`
