### ISSUE TITLE
Feature: `QianfanChatEndpoint` Support function_call

### ISSUE THREAD

**Issue by danielhjz** [langchain-ai/langchain#11105]
### Feature request

- `QianfanChatEndpoint` Or `ErnieBotChat` support function calling

### Motivation

Neither `QianfanChatEndpoint` and `ErnieBotChat` supported ERNIE-Bot Function ability now. We need this for developing agent by function_call where is only supported by openai function_call AFAIK.

### Your contribution

ready to PR

**Comment by NuODaniel** [comment]
Ive new a PR request here, https://github.com/langchain-ai/langchain/pull/11107, PTAL
