### ISSUE TITLE
Chains with no inputs

### ISSUE THREAD

**Issue by Omegastick** [langchain-ai/langchain#1113]
If I'm not mistaken, right now, chains with no inputs aren't possible unless you override `Chain.prep_inputs()`.

My use-case for this is chatbots with "cold-starts". The first call doesn't have an input, allowing the chatbot to start the conversation. Along the same lines, chains that include an environment (in the RL sense) for the agent to interact with, which wouldn't really make sense to require an 'input'.

If there's no reason this use-case shouldn't be handled, I can make a PR.

**Comment by hwchase17** [comment]
this use case should def be allowed! whats the error you're running into?

**Comment by Omegastick** [comment]
I think this has been implemented by someone else now. Closing.
