### ISSUE TITLE
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: Invalid prompt: prompt must start with "  Human:" turn, prompt must end with "  Assistant:" turn

### ISSUE THREAD

**Issue by tarek-kerbedj** [langchain-ai/langchain#11130]
### System Info

Langchain version = 0.0.231
python = 3.10

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

    from langchain.llms import Bedrock
    model_kwargs={"max_tokens_to_sample":8000}
    resp = Bedrock(credentials_profile_name="default",
        model_id="anthropic.claude-v2",model_kwargs={"max_tokens_to_sample":8000})

### Expected behavior

this same piece of code used to work just fine in the past weeks , now it's causing a prompt error 
i'm sure that bedrock changed something on their end

**Comment by jlonge4** [comment]
@tarek-kerbedj this is actually an issue with the prompt that went into affect yesterday. All bedrock prompts must be in the following format "\n\nHuman: <CustomerPrompt> 
\n\nAssistant:"

I hope this helps.

**Comment by Nav25oct** [comment]
Experiencing the similar issue with agents. (tried ReAct and load_chat_planner, load_chat_executor). However, when I am running as single prompt with "\n\nHuman:<prompt>\n\nAssistant:" its returning the result but not with Agents.

ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Invalid prompt: prompt must start with "

_Human:" turn, prompt must end with "

Assistant:" turn

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)_

**Comment by shane-thompson** [comment]
Same error for me using the VectorStoreIndexWrapper in Langchain.  I think this is related to the prompt change and this commit should fix it if i'm not mistaken.  (https://github.com/langchain-ai/langchain/commit/23065f54c047c71c9d71b724013f9652f9867930).

**Comment by tarek-kerbedj** [comment]
> @tarek-kerbedj this is actually an issue with the prompt that went into affect yesterday. All bedrock prompts must be in the following format "\n\nHuman: \n\nAssistant:"
> 
> I hope this helps.

this does work only for simple enough enough queries , but what about Sql chains and other pre-defined chains ?

**Comment by jlonge4** [comment]
@tarek-kerbedj i think @shane-thompson prompt wrapper may handle all of our issues. Hopefully the prompt wrapper would be called last so that anything you use (chain or otherwise) that formats a prompt will be wrapped before invoking the model.

**Comment by tarek-kerbedj** [comment]
> @tarek-kerbedj i think @shane-thompson prompt wrapper may handle all of our issues. Hopefully, the prompt wrapper would be called last so that anything you use (chain or otherwise) that formats a prompt will be wrapped before invoking the model.

Hey , although that did solve it for some features , unfortunately it isn't working with SQLchain
i'm getting this error now 
ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "Here" LINE 1: Here is the SQL query and answer: ^ [SQL: Here is the SQL query and answer: SQLQuery: SELECT COUNT(*) as num_clients FROM clients] (Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by jlonge4** [comment]
This appears to be a prompt engineering issue now where Claude tends to say "here is a {whatever you asked for} a lot. It needs to be instructed to return the SQL query only

**Comment by masihmoloodian** [comment]
Based on the AWS document: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html

import boto3
import json

bedrock = boto3.client('bedrock', 
                        'us-east-1', 
                        endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",  # <- Add this to solve (not recognized by the service.)
                        aws_access_key_id="",
                        aws_secret_access_key="",
                        )

modelId = 'anthropic.claude-v2'
accept = 'application/json'
contentType = 'application/json'

# NOTE: Body must same as following style
prompt = "Hello"
claude_prompt = f"\n\nHuman:{prompt}\n\nAssistant:"
body = json.dumps({
                "prompt": claude_prompt,
                "temperature": 0.5,
                "top_p": 1,
                "top_k": 250,
                "max_tokens_to_sample": 200,
                "stop_sequences": ["\n\nHuman:"]
                })
response = bedrock.invoke_model(body=body, modelId=modelId, accept=accept, contentType=contentType)
response_body = json.loads(response.get('body').read())
print(response_body.get('completion'))

**Comment by sajithamma** [comment]
`
import boto3
import json

session = boto3.Session(
    aws_access_key_id='XXX',
    aws_secret_access_key='XXXXX',
)


bedrock = boto3.client('bedrock')
response = bedrock.list_foundation_models()
print(response.get('modelSummaries'))

#All works till here


prompt = "Hello"
claude_prompt = f"\n\nHuman:{prompt}\n\nAssistant:"

body = json.dumps({
                "prompt": claude_prompt,
                "temperature": 0.5,
                "top_p": 1,
                "top_k": 250,
                "max_tokens_to_sample": 200,
                "stop_sequences": ["\n\nHuman:"]
                })

modelId = "anthropic.claude-v2"  
accept = "application/json"
contentType = "application/json"

response = bedrock.invoke_model(
    body=body, modelId=modelId, accept=accept, contentType=contentType
)
response_body = json.loads(response.get("body").read())

print(response_body.get("completion"))


`

# Error:

Getting Error: ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service.

**Comment by timyurchak** [comment]
> ` import boto3 import json
> 
> session = boto3.Session( aws_access_key_id='XXX', aws_secret_access_key='XXXXX', )
> 
> bedrock = boto3.client('bedrock') response = bedrock.list_foundation_models() print(response.get('modelSummaries'))
> 
> #All works till here
> 
> prompt = "Hello" claude_prompt = f"\n\nHuman:{prompt}\n\nAssistant:"
> 
> body = json.dumps({ "prompt": claude_prompt, "temperature": 0.5, "top_p": 1, "top_k": 250, "max_tokens_to_sample": 200, "stop_sequences": ["\n\nHuman:"] })
> 
> modelId = "anthropic.claude-v2" accept = "application/json" contentType = "application/json"
> 
> response = bedrock.invoke_model( body=body, modelId=modelId, accept=accept, contentType=contentType ) response_body = json.loads(response.get("body").read())
> 
> print(response_body.get("completion"))
> 
> `
> 
> # Error:
> Getting Error: ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service.

client name should be 
bedrock = boto3.client('**bedrock-runtime**')

**Comment by sajithamma** [comment]
> > ` import boto3 import json
> > session = boto3.Session( aws_access_key_id='XXX', aws_secret_access_key='XXXXX', )
> > bedrock = boto3.client('bedrock') response = bedrock.list_foundation_models() print(response.get('modelSummaries'))
> > #All works till here
> > prompt = "Hello" claude_prompt = f"\n\nHuman:{prompt}\n\nAssistant:"
> > body = json.dumps({ "prompt": claude_prompt, "temperature": 0.5, "top_p": 1, "top_k": 250, "max_tokens_to_sample": 200, "stop_sequences": ["\n\nHuman:"] })
> > modelId = "anthropic.claude-v2" accept = "application/json" contentType = "application/json"
> > response = bedrock.invoke_model( body=body, modelId=modelId, accept=accept, contentType=contentType ) response_body = json.loads(response.get("body").read())
> > print(response_body.get("completion"))
> > `
> > # Error:
> > Getting Error: ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service.
> 
> client name should be bedrock = boto3.client('**bedrock-runtime**')

**UnknownServiceError: Unknown service: 'bedrock-runtime'. Valid service names are:** 

(bedrock is available but bedrock-runtime is not available)
