### ISSUE TITLE
Issue: load_agent_executor returning ConfigError

### ISSUE THREAD

**Issue by LorAutumn** [langchain-ai/langchain#11156]
### Issue you'd like to raise.

I am trying to run a PlanAndExecute agent. The load_agent_executor method call returns: 
"pydantic.v1.errors.ConfigError: field "retry_chain" not yet prepared so type is still a ForwardRef, you might need to call OutputFixingParser.update_forward_refs()."

This is my code:
`import os
import dotenv
from langchain.chat_models import ChatOpenAI
from langchain_experimental.plan_and_execute import PlanAndExecute, load_agent_executor, load_chat_planner
from langchain.llms import OpenAI
from langchain.agents.tools import Tool
from langchain.chains.llm_math.base import LLMMathChain
from langchain.tools import DuckDuckGoSearchRun
from langchain.output_parsers import OutputFixingParser

dotenv.load_dotenv()

apikey = os.getenv("OPEN_AI_API_KEY", default="")

search = DuckDuckGoSearchRun()
llm = OpenAI(temperature=0, openai_api_key=apikey)
llm_math_chain = LLMMathChain.from_llm(llm=llm, verbose=True)
tools = [
    Tool(
        name="Search",
        func=search.run,
        description="useful for when you need to answer questions about current events"
    ),
    Tool(
        name="Calculator",
        func=llm_math_chain.run,
        description="useful for when you need to answer questions about math"
    ),
]

model = ChatOpenAI(temperature=0)
planner = load_chat_planner(model)
executor = load_agent_executor(model, tools, verbose=True)
agent = PlanAndExecute(planner=planner, executor=executor, verbose=True)`

**Comment by aronweiler** [comment]
I can confirm I am experiencing this issue, as well.  It appears to be a bug in the `OutputFixingParser`- probably a circular reference.  I have not really investigated, but as a quick workaround, I have code that looks like this:

``` python
try:
    output_parser = StructuredChatOutputParserWithRetries.from_llm(llm=self.llm)
except Exception as e:
    logging.error(f"Could not create output parser: {e}")
    logging.warning("Falling back to default output parser")
    output_parser = StructuredChatOutputParserWithRetries()
```
The `StructuredChatOutputParserWithRetries` references `OutputFixingParser`, which is where the error seems to be.

It only occurs for me when I run in a docker container, though, never when just running from vscode debugger.

**Comment by mehrdad-shokri** [comment]
I think it use to work a few days ago, nothing special changed in my work but now it doesn't work. any ideas?

**Comment by aronweiler** [comment]
I'm in mobile, so can't investigate right now, but it's probably related to this: https://github.com/langchain-ai/langchain/pull/11092/files
