### ISSUE TITLE
ISSUE: how can i get answer only based on vector store? If the context is not available in vector store

### ISSUE THREAD

**Issue by armmosikyan66** [langchain-ai/langchain#11157]
template = """Use the following pieces of context to answer the question at the end. If the answer can't be determined using only the information in the provided context simply output "NO ANSWER", just say that you don't know, don't try to make up an answer. Use three sentences maximum. Keep the answer as concise as possible. 
    {context}
    Question: {question}
    Helpful Answer:"""
    QA_CHAIN_PROMPT = PromptTemplate.from_template(template)

    qa = RetrievalQA.from_chain_type(
        llm=streaming_llm,
        chain_type="stuff",
        retriever=compression_retriever,
        callback_manager=manager,
        chain_type_kwargs={
            "prompt": QA_CHAIN_PROMPT
        }
    )

**Comment by armmosikyan66** [comment]
> _🤖_
> 
> Based on the context provided, it seems you want to configure the RetrievalQA in LangChain to return an answer based only on the vector store, even when the context is not available in it.
> 
> In LangChain, you can use the `VectorDBQA` class for this purpose. This class is designed for question-answering against a vector database. Here is an example of how you can use it:
> 
> ```python
> from langchain.chains.retrieval_qa.base import VectorDBQA
> from langchain.schema.vectorstore import VectorStore
> 
> # Initialize your VectorStore
> vectorstore = VectorStore(...)
> 
> # Initialize VectorDBQA
> vector_db_qa = VectorDBQA(vectorstore=vectorstore, k=4, search_type="similarity")
> 
> # Now you can use vector_db_qa to get answers based on the vector store
> ```
> 
> In this example, `vectorstore` is your initialized vector store. The `k` parameter is the number of documents to query for, and `search_type` is the type of search to use over the vector store. It can be either "similarity" or "mmr".
> 
> However, please note that the `VectorDBQA` class is marked as deprecated, so it's recommended to migrate to the `RetrievalQA` class if possible. The context does not provide enough information on how to configure `RetrievalQA` to return an answer based only on the vector store when the context is not available in it.
> 
> For more details, you can refer to the source code of the `VectorDBQA` class in the LangChain codebase: [libs/langchain/langchain/chains/retrieval_qa/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/base.py)
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/base.py)
> * [libs/langchain/langchain/chains/qa_with_sources/vector_db.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/qa_with_sources/vector_db.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

i need to use Contextual compression and custom prompt to do that logic

**Comment by armmosikyan66** [comment]
> _🤖_
> 
> Hello,
> 
> You're correct that the `VectorDBQA` class is deprecated and the recommended approach is to use the `RetrievalQA` class. To configure `RetrievalQA` to return an answer based solely on the vector store when the context is not available in it, you need to initialize the `RetrievalQA` class with a `retriever` that is an instance of `VectorStoreRetriever`. The `VectorStoreRetriever` should be initialized with your vector store.
> 
> Here is an example of how you can do this:
> 
> ```python
> from langchain.llms import LlamaCpp
> from langchain.chains import RetrievalQA
> from langchain.vectorstores import Chroma
> from langchain.embeddings import GPT4AllEmbeddings
> from langchain.document_loaders import WebBaseLoader
> from langchain.text_splitter import RecursiveCharacterTextSplitter
> 
> # Load and split an example document
> loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
> data = loader.load()
> text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
> all_splits = text_splitter.split_documents(data)
> 
> # Initialize your vector store
> vectorstore = Chroma.from_documents(documents=all_splits, embedding=GPT4AllEmbeddings())
> 
> # Initialize the LLM
> llm = LlamaCpp(
>     model_path="/path/to/your/model",
>     n_gpu_layers=1,
>     n_batch=512,
>     n_ctx=2048,
>     f16_kv=True,
> )
> 
> # Initialize the RetrievalQA with the retriever
> qa_chain = RetrievalQA.from_chain_type(
>     llm,
>     retriever=vectorstore.as_retriever(),
> )
> ```
> 
> In the above code, replace `/path/to/your/model` with the path to your model. The `RetrievalQA` class will now use the vector store to retrieve documents and answer questions. If the context is not available in the vector store, it will return an answer based solely on the vector store.
> 
> This is supported by the following code in the `RetrievalQA` class:
> 
> ```python
> class RetrievalQA(BaseRetrievalQA):
>     """Chain for question-answering against an index."""
> 
>     retriever: BaseRetriever = Field(exclude=True)
> 
>     def _get_docs(
>         self,
>         question: str,
>         *,
>         run_manager: CallbackManagerForChainRun,
>     ) -> List[Document]:
>         """Get docs."""
>         return self.retriever.get_relevant_documents(
>             question, callbacks=run_manager.get_child()
>         )
> 
>     async def _aget_docs(
>         self,
>         question: str,
>         *,
>         run_manager: AsyncCallbackManagerForChainRun,
>     ) -> List[Document]:
>         """Get docs."""
>         return await self.retriever.aget_relevant_documents(
>             question, callbacks=run_manager.get_child()
>         )
> ```
> 
> In the `_get_docs` and `_aget_docs` methods, the `RetrievalQA` class uses the `retriever` to get relevant documents for the question. The `retriever` is an instance of `VectorStoreRetriever` which retrieves documents from the vector store.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/base.py)
> * [docs/extras/use_cases/question_answering/how_to/local_retrieval_qa.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/extras/use_cases/question_answering/how_to/local_retrieval_qa.ipynb)
> * [libs/langchain/langchain/chains/qa_with_sources/vector_db.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/qa_with_sources/vector_db.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

still aftre the question out of context i get result why ? 
here is my chain 
template = """Strictly Use ONLY the following context to answer the question at the end. Think step-by-step and then answer. If the answer can't be determined using only the information in the provided context simply output "NO ANSWER", just say that you don't know, don't try to make up an answer. Use three sentences maximum. Keep the answer as concise as possible. 
    {context}
    Question: {question}
    Helpful Answer:"""
    QA_CHAIN_PROMPT = PromptTemplate.from_template(template)

    qa = RetrievalQA.from_chain_type(
        llm=streaming_llm,
        chain_type="stuff",
        retriever=compression_retriever,
        callback_manager=manager,
        chain_type_kwargs={
            "prompt": QA_CHAIN_PROMPT
        }
    )

    return qa

**Comment by aqt01** [comment]
Hey! @armmosikyan66 did you solve it? 
I'm having the same situation right now

**Comment by armmosikyan66** [comment]
> Hey! @armmosikyan66 did you solve it? I'm having the same situation right now

Hey! I actually stopped using langchain after the issue, so I don't have a solution

**Comment by anigos** [comment]
I am stuck with this now. I can see this is an open issue. Did anyone face it? I can see I am not able to control LLM just to read the documents from vector store and tell “I don’t know” if not present in the store. In my case it is completely ignoring my documents and giving answer from his own intelligence.
