### ISSUE TITLE
Keeping chat session ids with chatbot agents

### ISSUE THREAD

**Issue by assafelovic** [langchain-ai/langchain#1115]
First off kudos for this remarkable library!

I'm experimenting with chatbot agents, but missing how can I save a specific conversation sessions and context per user. 
The issue is that if I deploy this and serve to multiple users, the context gets confused. Any suggestions?

**Comment by ashavish** [comment]
@assafelovic  - did you find any workaround for this ?

**Comment by zoltan-fedor** [comment]
Here is an initial implementation for this: https://github.com/hwchase17/langchain/pull/1058#issuecomment-1478775638

**Comment by zoltan-fedor** [comment]
This has been added recently in v0.0.126, see https://github.com/hwchase17/langchain/pull/2122
