### ISSUE TITLE
Add `hierarchy` key to Document metadata in `ConfluenceLoader`

### ISSUE THREAD

**Issue by ClaudioSalvatoreArcidiacono** [langchain-ai/langchain#11163]
### Feature request

Add `hierarchy` key to Document metadata returned by `ConfluenceLoader`.

So, for example if a page is located under the pages Page A/Page B, the `hierarchy` should be equal to `Page A/Page B`

This could be achieved by calling the confluence endpoint using `expand = "ancestors"`.

For example [this](https://github.com/langchain-ai/langchain/blob/cfa2203c626a2287d60c1febeb3e3a68b77acd77/libs/langchain/langchain/document_loaders/confluence.py#L282) would become

```python
pages = self.paginate_request(
    self.confluence.get_all_pages_from_space,
    space=space_key,
    limit=limit,
    max_pages=max_pages,
    status="any" if include_archived_content else "current",
    expand=f"{content_format.value},ancestors",
)
```

### Motivation

Page Hierarchy is very important in a confluence-like space and it would definitely be relevant when searching for documents in the Vector Store.

### Your contribution

I am willing to submit a PR to add this feature.

**Comment by LiquidDegu** [comment]
Was there any progress on this Feature request
