### ISSUE TITLE
Runtime Exception in create_extraction_chain_pydantic (RuntimeError: no validator found)

### ISSUE THREAD

**Issue by hedb** [langchain-ai/langchain#11166]
### System Info

Langchain 0.0.302
Pydantic 2.4.1

reproducing code:

```

from langchain.chains import create_extraction_chain_pydantic
from langchain.chat_models import ChatOpenAI
from pydantic import BaseModel, model_validator
from typing import Any



class TestData(BaseModel):
    company_name: str


llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")
chain = create_extraction_chain_pydantic(pydantic_schema=TestData, llm=llm)
extracted_subsidiary_list = chain.run('')
```

Exception:
**RuntimeError: no validator found for <class '__main__.TestData'>, see `arbitrary_types_allowed` in Config**

Tried adding: (didn't help)
```

    @model_validator(mode='after')
    def dummy_validator(self):
        return self

    @model_validator(mode='before')
    @classmethod
    def dummy_validator1(cls, data: Any) -> Any:
        return data
```

### Who can help?

@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```

from langchain.chains import create_extraction_chain_pydantic
from langchain.chat_models import ChatOpenAI
from pydantic import BaseModel, model_validator
from typing import Any



class TestData(BaseModel):
    company_name: str


llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")
chain = create_extraction_chain_pydantic(pydantic_schema=TestData, llm=llm)
extracted_subsidiary_list = chain.run('')
```

### Expected behavior

Doesn't throw exception

**Comment by duckworth** [comment]
I am also seeing this same issue 
```Exception: no validator found for <class 'TestData'>, see `arbitrary_types_allowed` in Config``` 

I have even tried:

``` python
from pydantic import BaseModel

class TestData(BaseModel):
    # Define your fields here
    
    class Config:
        arbitrary_types_allowed = True

# calling code
create_extraction_chain_pydantic(pydantic_schema=TestData, llm=llm).run("foo")

```

**Comment by hedb** [comment]
> class TestData(BaseModel):
>     company_name: str

See my reproducing code in the issue submission
It has exactly your suggestion, and fails eventhough TestData is a pydantic model

**Comment by hedb** [comment]
@duckworth 
Yeap,tried it as well, including defining validators.

**Comment by duckworth** [comment]
> @duckworth Yeap,tried it as well, including defining validators.

Yeah, seems like dropping Pydantic down to 1.10.1 for now is the only option.
