### ISSUE TITLE
Argument 'value' has incorrect type (expected str, got SecretStr) (type=type_error) in chatAnthropic- Induced in 0.0.301

### ISSUE THREAD

**Issue by vcet-project** [langchain-ai/langchain#11165]
### System Info

Hi Team,
The issue is while calling the ChatAnthropic function with the right anthropic secret key. The type SecretStr is not getting resolved. Discussed over here:https://github.com/langchain-ai/langchain/pull/10724

### Who can help?

@josh

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

To recreate the error :
from langchain.chat_models import ChatAnthropic
claude_chat = ChatAnthropic(anthropic_api_key="xy-key")

### Expected behavior

It should initialize the claude chat

**Comment by joshuasundance-swca** [comment]
@eyurtsev should I make a pr to fix this? If so, is there an approach mentioned in the PR thread you prefer? I think putting the fix in the env function is best if other models will also be using SecretStr in the future. 

I think this affects langchain > 0.0.300

**Comment by joshuasundance-swca** [comment]
Fixed in v.0.0.305

#11182

**Comment by vcet-project** [comment]
Thanks @joshuasundance-swca
