### ISSUE TITLE
Bedrock InvokeModel failes on GA release

### ISSUE THREAD

**Issue by mrichman** [langchain-ai/langchain#11189]
### System Info

Lambda Python 3.11 runtime

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

As of Bedrock GA today, I get this error:

"/var/task/langchain/llms/bedrock.py", line 237, in _prepare_input_and_invoke raise ValueError(f"Error raised by bedrock service: {e}") ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: The requested operation is not recognized by the service. 

### Expected behavior

It should invoke the model. I'm guessing with today's GA release of Bedrock, an underlying API call changed.

**Comment by mrichman** [comment]
I see the client name was fixed an hour ago to `bedrock-runtime`: https://github.com/langchain-ai/langchain/blob/fd96878c4b41363ef391b580f85dc78c879b8a79/libs/langchain/langchain/llms/bedrock.py#L187

When will the updated PIP package be available?

**Comment by evolate-tim** [comment]
You can still work around this.

    bedrock_runtime = boto3.client(service_name="bedrock-runtime", region_name="us-east-1",)

    titan_llm = Bedrock(
        model_id="amazon.titan-text-express-v1", client=bedrock_runtime, credentials_profile_name=profile
    )
    titan_llm.model_kwargs = {"temperature": 0.5, "maxTokenCount": 700}

**Comment by masihmoloodian** [comment]
```
Based on the AWS document: https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters.html

import boto3
import json

bedrock = boto3.client('bedrock', 
                        'us-east-1', 
                        endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",  # <- Add this to solve (not recognized by the service.)
                        aws_access_key_id="",
                        aws_secret_access_key="",
                        )

modelId = 'anthropic.claude-v2'
accept = 'application/json'
contentType = 'application/json'

# NOTE: Body must same as following style
prompt = "Hello"
claude_prompt = f"\n\nHuman:{prompt}\n\nAssistant:"
body = json.dumps({
                "prompt": claude_prompt,
                "temperature": 0.5,
                "top_p": 1,
                "top_k": 250,
                "max_tokens_to_sample": 200,
                "stop_sequences": ["\n\nHuman:"]
                })
response = bedrock.invoke_model(body=body, modelId=modelId, accept=accept, contentType=contentType)
response_body = json.loads(response.get('body').read())
print(response_body.get('completion'))
```

**Comment by evolate-tim** [comment]
The Bedrock class has a function called "_human_assistant_format" that will be invoked if the model used is from anthropic.

**Comment by Javed6234** [comment]
> I see the client name was fixed an hour ago to `bedrock-runtime`:
> 
> https://github.com/langchain-ai/langchain/blob/fd96878c4b41363ef391b580f85dc78c879b8a79/libs/langchain/langchain/llms/bedrock.py#L187
> 
> When will the updated PIP package be available?

On 0.0.309 and had to update to `values["client"] = session.client("bedrock", **client_params)`

**Comment by Javed6234** [comment]
Nvm, needed to upgrade boto3 and botocore
