### ISSUE TITLE
Return output from map chain in the final result of ConversationalRetrievalChain.

### ISSUE THREAD

**Issue by gftempleton** [langchain-ai/langchain#11209]
### Feature request

Hi, 
I am working on Document QA, and using ConversationalRetrievalChain, with map-reduce as chain type. 
In the final result of ConversationalRetrievalChain, I want to get the individual output from each map-chain.

### Motivation

This is a separate issue, and I think there should be a parameter that we can pass, to get the output of these chains as well. 

### Your contribution

Not as of now.

**Comment by Farhan-Faisal** [comment]
I will like to look into it and see whether something like this is already implemented. If not, I will try to implement it and submit a PR.

**Comment by gftempleton** [comment]
Hi Farhan, 
Thank you for answering. 
I need the final result dictionary to have the intermediate results, just like we have source dictionary and other stuff. 
Thanks.

**Comment by PitcairnHotdog** [comment]
Hi gftempleton,

MapReduceDocumentChain contains a flag named “return_intermediate_steps” that allows intermediate steps to be outputted along with the final result. I guess that is what you are referring to?

After looking into it, I did find out that this flag didn't work with ConversationalRetrievalChain. I got a "ValueError: "run" not supported when there is not exactly one output key." Could you please kindly confirm whether this is also the issue you encountered?
