### ISSUE TITLE
DOC: What is the difference between OpenAIFunctionsAgent and OpenAIMultiFunctionsAgent?

### ISSUE THREAD

**Issue by DayuanJiang** [langchain-ai/langchain#11225]
### Issue with current documentation:

What is the difference between OpenAIFunctionsAgent and OpenAIMultiFunctionsAgent? The document do not clarify it.

**Comment by ivanstepanovftw** [comment]
One is `BaseSingleActionAgent`, other is `BaseMultiActionAgent`. One for single action, other for multiple actions. While one provides to OpenAI API tools as is, other is extending it to be able to call multiple tools at the time. Here is explanation for `OpenAIMultiFunctionsAgent`:
```
# OpenAI functions returns a single tool invocation
# Here we force the single tool invocation it returns to
# itself be a list of tool invocations. We do this by constructing
# a new tool that has one argument which is a list of tools
# to use.
```
