### ISSUE TITLE
Add support for a variety of languages to LanguageParser

### ISSUE THREAD

**Issue by ThatsJustCheesy** [langchain-ai/langchain#11229]
### Feature request

[LanguageParser](https://github.com/langchain-ai/langchain/blob/e9b51513e9bab738c741a348ffbf0f36ce19faf6/libs/langchain/langchain/document_loaders/parsers/language/language_parser.py#L21C7-L21C21) is a parser for Document Loaders that, given source code, splits each top-level function or class into separate documents. As stated in its documentation:

> This approach can potentially improve the accuracy of QA models over source code.
>
> Currently, the supported languages for code parsing are Python and JavaScript.

We would like to add support for additional languages, such as C, C++, Rust, Ruby, Perl, and so on.

### Motivation

There is an [open request](https://github.com/langchain-ai/langchain/issues/10996) for "CPP" (presumably C++) support. By integrating a generic parsing library (such as [tree-sitter](https://github.com/tree-sitter/py-tree-sitter#py-tree-sitter)), we could make LanguageParser work with many more languages, and thus be more generally useful.

### Your contribution

We intend to submit a pull request for this issue no later than mid-November, and likely sooner.

**Comment by ThatsJustCheesy** [comment]
@dosu-bot Hi again. We're just wondering if you are able to identify any past issues similar to this one? We would like to make sure our work addresses any previous concerns in this area.

**Comment by devstein** [comment]
Hey @Megabear137 as of now Dosu only responds to the author of the thread to reduce noise. We're working on a feature to let users "fork" issues for personal use.

Let me know if you have any other ideas/feedback!

**Comment by ThatsJustCheesy** [comment]
@dosu-bot Hey there. From the languages that LangChain supports but does not currently have a language parser for, which are the most commonly used?

**Comment by ThatsJustCheesy** [comment]
@Megabear137 TIOBE index or similar might be helpful for us to gauge that

I personally am somewhat skeptical about the usefulness of TIOBE for predicting general trends, but for such low-stakes decisions, doubt it would really hurt

**Comment by ThatsJustCheesy** [comment]
The [supposed](https://www.tiobe.com/tiobe-index/) current most-used languages, ignoring stuff it doesn't make sense for us to support:

<details><summary>Expand</summary>
<ul>
<li>Python (done)</li>
<li>C</li>
<li>C++</li>
<li>Java</li>
<li>C#</li>
<li>JavaScript (done)</li>
<li>Visual Basic (??)</li>
<li>PHP</li>
<li>Go</li>
<li>Pascal</li>
<li>MATLAB</li>
<li>Swift</li>
<li>Fortran</li>
<li>R</li>
<li>Kotlin</li>
<li>Ruby</li>
<li>Rust</li>
<li>Ada</li>
<li>COBOL (??)</li>
<li>Lua</li>
<li>Perl</li>
<li>Julia</li>
<li>D</li>
<li>Dart</li>
<li>Haskell</li>
<li>Objective-C</li>
<li>F#</li>
</ul>
</details>

We obviously might not do all of these, but a good selection would be helpful.

If anyone reading this wants support for a particular language, please comment!

**Comment by ehartford** [comment]
Hello
I need to add a LanguageParser for COBOL
Can you please advise, how I can implement this?

**Comment by ThatsJustCheesy** [comment]
@ehartford aha, that's one I removed from the list. I thought it would be too arcane 😅

If either of these grammars work as advertised:

- https://github.com/yutaro-sakamoto/tree-sitter-cobol
- https://github.com/Neppord/tree-sitter-cobol

then it should be easy enough to create a COBOL LanguageParser using the framework we're creating. If we find time (as we're doing this for a school project), we can add it to our eventual PR as well

**Comment by ehartford** [comment]
https://github.com/langchain-ai/langchain/pull/11674

**Comment by harshil1973** [comment]
I recently generated embeddings for the contour project which is a Kubernetes ingress controller written in Golang and tried to chat but without a specific language parser, I don't think it will give good results. So, maybe I can add Golang support with some support🙂.

**Comment by Mario928** [comment]
@ThatsJustCheesy i wish to contribute for java language.iI have two questions:
1.Is it fine if i use javalang instead of tree-sitter library parser?.
2.Can i raise the PR directly here and share the link or you prefer any other way.

Also,Nice initiative.Hoping to hear from you soon

**Comment by ThatsJustCheesy** [comment]
Hi @Mario928, you could definitely use some other parsing library/libraries. We aren't trying to homogenize all `LanguageParser` segmenter implementations, merely add new ones where gaps existed previously :)

If you want to work on a Java implementation, we'll avoid working on one. (And it would be nice to link your PR here when you open one)

**Comment by jaevans** [comment]
I was looking to add a golang parser (in go) and wasn't sure how to integrate it as a general solution. I really like the tree-sitter idea to cover a bunch of languages at once. I'd be happy to help with this as it aligns with my interest in langchain.

**Comment by Mario928** [comment]
Thanks for confirming @ThatsJustCheesy .I will try to implement java parser using javalang and share the PR link here within 2-3 days.

**Comment by ThatsJustCheesy** [comment]
C++ parser is done on our side.

**Comment by jelalalamy** [comment]
Hey! I'd like to contribute for C# if possible.

**Comment by LeilaChr** [comment]
Ruby parser is done on our side.

**Comment by Megabear137** [comment]
Just wanted to mention here that I'll be working on a C Parser.

**Comment by LeilaChr** [comment]
Scala parser is done.

**Comment by Harrolee** [comment]
Anyone started on a TypeScript parser?

**Comment by Harrolee** [comment]
I found your [branch](https://github.com/ThatsJustCheesy/langchain/tree/d01-languageparser). I'll use your template to add a TypeScript parser.

**Comment by ThatsJustCheesy** [comment]
We intend to submit our PR sometime this week

**Comment by Mario928** [comment]
I will submit PR for the Java parser max in 4 days.So that we can then submit final PR.Sorry for delay,i have already started,just got caught up with some personal stuff.

**Comment by Harrolee** [comment]
Submitted a [pr](https://github.com/ThatsJustCheesy/langchain/pull/1) for typescript support.

**Comment by Mario928** [comment]
Submitted a [PR](https://github.com/ThatsJustCheesy/langchain/pull/2) for Java language. @ThatsJustCheesy. Please verify and accept this PR.

**Comment by alexrmacleod** [comment]
@ThatsJustCheesy please do Solidity and unlock the power of blockchain programming for everyone. Or please provide me with the steps of how to create a solidity parser that works and i will try! thankyou.

**Comment by Microsvuln** [comment]
I wonder if C/C++ support has been merged already ? @ThatsJustCheesy

**Comment by ThatsJustCheesy** [comment]
@Microsvuln Our pull request is open still: #13318

**Comment by eickeBuecking** [comment]
Is there any update on if and when this will get merged? Would love to see additional languages... Thanks in advance!

**Comment by ThatsJustCheesy** [comment]
@eickeBuecking We are waiting for a maintainer to review. If you want it prioritized, you could ping one of them in the pull request thread :)

**Comment by rawandahmad698** [comment]
We need swift support

**Comment by khushiDesai** [comment]
Hi, I am Khushi, a 4th year student at UofT CS. I’m working with my teammates @anushak18, @ashvini8, and @ssumaiyaahmed, who are also 4th year students at UofT CS. We would like to take the initiative to work on incorporating swift support.
