### ISSUE TITLE
Implement a custom LangChain class wrapper (LLM model/Agent) for StarCoder model

### ISSUE THREAD

**Issue by mratanusarkar** [langchain-ai/langchain#11252]
### Feature request

Is it possible to integrate any language model (LM) trained on source code or opensource codebases on various programming languages e.g. :
- [StarCoder](https://github.com/bigcode-project/starcoder)
- [replit/replit-code-v1-3b](https://huggingface.co/replit/replit-code-v1-3b)
- [Bloom](https://bigscience.huggingface.co/blog/bloom)
- etc...

as an [LLM Model](https://python.langchain.com/en/latest/modules/models.html) or an [Agent](https://python.langchain.com/en/latest/modules/agents.html) with [LangChain](https://github.com/hwchase17/langchain), and [chain](https://python.langchain.com/en/latest/modules/chains.html) it in a complex usecase?

It would be really cool if, during a general query, the LangChain system has the capability to understand code context (possibly when chained to a vector DB or any data source that contains code or a full code repo), _kind of like chatting with your codebase_!

Any help / hints on the same would be appreciated!

### Motivation

Initially inspired by this [Issue #173](https://github.com/nomic-ai/gpt4all/issues/173)
Raised a similar Issue long back with StarCoder [Issue #53](https://github.com/bigcode-project/starcoder/issues/53)

### Your contribution

n/a

**Comment by mratanusarkar** [comment]
@dosu-bot can you show me a full implementation of Integrating [StarCoder](https://github.com/bigcode-project/starcoder) (as an example) with LangChain?

**Comment by mratanusarkar** [comment]
@dosu-bot can you show me a full implementation of Integrating [StarCoder](https://github.com/bigcode-project/starcoder) (as an example) with LangChain?
So that the LLM has a full context of programming language and the code.
And If I point it to a codebase or a github repo or local path to a codebase,
It will be able to understand the codebase and allow me to chat with me codebase.

**Comment by mratanusarkar** [comment]
@dosu-bot can you show me a full implementation of Integrating [StarCoder](https://github.com/bigcode-project/starcoder) (as an example) with LangChain?
So that the LLM has a full context of programming language and the code.
And If I point it to a codebase or a github repo or local path to a codebase,
It will be able to understand the codebase and allow me to chat with my codebase.

**Comment by mratanusarkar** [comment]
> Firstly, regarding the integration of external language models like StarCoder, the LangChain framework does not currently have built-in support for this.

This is exactly my feature request and the reason for opening this issue.

**Comment by sudranga** [comment]
@mratanusarkar Atleast for starcoder, I don't believe this needs anything specific. Here's an example using starchat hosted on HuggingFaceHub. Starchat is fine tuned on starcoder to act as a programming assistant. You could also run a local version using HuggingFacePipeline. But, it needs a lot of resources. If desired, you should be able to hook this up with a retrieval pipeline.

#!/usr/bin/env python3
import langchain
langchain.verbose=True
from langchain.llms import HuggingFaceHub
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] =  "your key"

model_kwargs = {"max_new_tokens":256, "do_sample":True, "temperature":0.2, "top_k":50, "top_p":0.95, "stop": ["<|end|>"]} # You may need to play around with these parameters.

llm = HuggingFaceHub(
    repo_id= "HuggingFaceH4/starchat-beta", model_kwargs=model_kwargs
)

template = "<|system|>\n<|end|>\n<|user|>\n{question}<|end|>\n<|assistant|>"
prompt = PromptTemplate.from_template(template)
llm_chain = LLMChain(
    llm=llm,
    prompt=prompt,
)

stop = "<|end|>"
q = "Generate a complete hello world program in Java"
output = llm_chain.generate([{"question": q}])
for generation in output.generations:
    print (generation[0].text)

**Comment by mratanusarkar** [comment]
@sudranga I looked it up. looks like it acts as a code completion and code assist in general based on past text.
What I am looking for is different! It is more along the lines of "code insight" or "chatting with a codebase".
Similar to the "chat with pdf", or "chat with doc" solutions out there, I want to chat with my codebase by attaching a github repo link or an offline codebase path to the system.

**Comment by devstein** [comment]
@mratanusarkar FWIW, we're hoping to add this functionality to Dosu in the future. 

We want to make it super easy for users to interact with any codebase. 

Do you have a specific use-case in mind for "chatting with your codebase"?

**Comment by sudranga** [comment]
@mratanusarkar You should be able to hook this up with a retrieval pipeline (RAG). Would that not suffice?

**Comment by sancelot** [comment]
I don't understand why it should not be possible.
I think that's already something that can be done.
It sounds to me as simple as :
 your code files must be tokenized  using starcoder tokenizer , and filled in using embdeddings

**Comment by MarioLiao** [comment]
Hey me and some other people are looking into this issue. We are first time contriubutors, so if any has any more information on this issue and/or if someone is already working on this issue, please tell me and it would be much appreciated

**Comment by MarioLiao** [comment]
Hey @mratanusarkar My group and I would like some of your insights on this problem. Do you have any suggestions on where to start. I understand the main solution will to be create a wrapper class that has on the functionaily to integrate starcoder into langhchain. Do you know of any examples or files to look at that have already done something similar to this. Thank you very much!
