### ISSUE TITLE
Chat cache results in  KeyError: 'message'

### ISSUE THREAD

**Issue by OrLevy23** [langchain-ai/langchain#11268]
### System Info

I'm trying to use langchain with cache using gptcache, using pydantic models 

(prior to this message I'm building prompt of mixed human and system messages)
```
 chain = create_structured_output_chain(Job, llm, prompt, verbose=False)
 res = chain.run({'job': job})
```

when not using cache everything seems to work but when getting from cache I'm seeing this error:
```
  File "/Users/orlevy/Projects/tfg/llm-service/venv/lib/python3.9/site-packages/langchain/schema/output.py", line 62, in set_text
    values["text"] = values["message"].content
KeyError: 'message'
```

When I digged a little further it seems like this code, is not generating the same response (we are losing function call response) :
<img width="661" alt="image" src="https://github.com/langchain-ai/langchain/assets/21291210/cfeccb45-4806-4f85-a01c-67b42a882c8d">

modified code a bit(not sure if this is actually a good idea) but this one seems to work for chat:
```
        res = get(prompt, cache_obj=_gptcache)
        if res:
            return [
                ChatGeneration(
                    message=AIMessage(content='',
                                      additional_kwargs=generation_dict['message']['additional_kwargs']
                                      ),
                    generation_info=dict(finish_reason=generation_dict.get("finish_reason")),
                ) for generation_dict in json.loads(res)
            ]
```
would really appreciate 

your help with this

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. use chat with chain messages
2. use cachegpt (used postgres)
3. make one call
4. cache should be populated
5. from that point on when using cache we see error

### Expected behavior

I should be able to use cache

**Comment by OrLevy23** [comment]
this code did not change anything, actually I've debugged it and it seems like this code is not called at all in my usecase

**Comment by OrLevy23** [comment]
@dosu-bot
this code did not change anything, actually I've debugged it and it seems like this code is not called at all in my usecase.

**Comment by OrLevy23** [comment]
@dosu-bot issue is not with set_text but rather before that with the generation of the data.
the object that is created looks like that:
``` 
{'text': '', 'generation_info': {'finish_reason': 'stop'}}
```
and all the actual response is redacted (again this is what I pinpointed that it looks to get lost):
![image](https://github.com/langchain-ai/langchain/assets/21291210/9b8e2b38-f50e-4cdc-af59-96cd2d9c7b81)

**Comment by dxv2k** [comment]
I face similar issue, does anyone figure out how to fix it yet?
