### ISSUE TITLE
Sub Question Query Engine

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#11260]
### Feature request

Hi, does langchain have a feature similar to LlamaIndex's [Sub Question Query Engine](https://gpt-index.readthedocs.io/en/latest/examples/query_engine/sub_question_query_engine.html)? If not, I'd like to submit a feature request!

### Motivation

This capability is very useful!

### Your contribution

Not sure.

**Comment by austinmw** [comment]
Bump!

**Comment by sjinwoo** [comment]
I am looking for the same functionality. Are we making progress?

**Comment by Axultan** [comment]
Bump

**Comment by baskaryan** [comment]
Thanks for the question @austinmw! Does the MultiQueryRetriever match what you're looking for, or did you have something else in mind: https://python.langchain.com/docs/modules/data_connection/retrievers/MultiQueryRetriever

**Comment by austinmw** [comment]
Hi @baskaryan, thanks for your reply. I think the functionality seems slightly different. MultiQueryRetriever appears to be similar to test-time augmentation of a query, whereas LlamaIndex's sub question query engine tries to specifically separate out when multiple questions are being asked, then ask each individually.

**Comment by baskaryan** [comment]
The docs example focuses on augmentation, but since you can pass in your own prompt it should be able to handle any type of single question -> multiple questions mapping, including decomposing a multi-part question into distinct questions

**Comment by austinmw** [comment]
Ah interesting, alright thanks!

**Comment by baskaryan** [comment]
I believe there is a section for adding a custom prompt https://python.langchain.com/docs/modules/data_connection/retrievers/MultiQueryRetriever#supplying-your-own-prompt, but would be good to add one specific to the use case you mentioned (question decomposition)! Will add a ticket for it

**Comment by kuabhish** [comment]
Thanks man. this helped.. i could crack this with langchain with a small change in the prompt.

Please help me understand. 
How can i use this same logic with self query retriever?


Like if I ask the selfqueryretriever. the question.
```
Summarize the notes written by GUY_A.
```
and self query retreiver understand that..and works nicely.

even if I ask.
```
Summarize the notes written by GUY_A and GUY_B
```
then also it can understand.

But when I pass 
```
Compare the notes written by GUY_A and GUY_B
```
its failing to get results
error-
```
UnexpectedCharacters: No terminal matches 'o' in the current parser context, at line 1 col 29
```

so i feel `self-query retreiver` is limited and `multiquery retriever` is powerful.


but what i wanted at the end.. `per user retrieval`.. and i found it to happen dynamically with self query retriver.


now but i cant trust on the compare prompts.. written by users. for these `self-query retreiver`

so. how can i acheive the power of multi query retriever but also the power of self-query/per user retriever..
