### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.chat_models'

### ISSUE THREAD

**Issue by MSMALG** [langchain-ai/langchain#11277]
### System Info

Langchain version 0.0.305
Python version 3.101.1
Platform VScode

I am trying to create a chatbot using langchain and streamlit by running this code:
```
import os
import streamlit as st
from st_chat_message import message
from dotenv import load_dotenv


from langchain.chat_models import ChatOpenAI
from langchain.schema import (
    SystemMessage,
    HumanMessage,
    AIMessage
)


def init():
    load_dotenv()

    #Checking Openai api key
    if os.getenv("OPENAI_API_KEY") is None or os.getenv("OPENAI_API_KEY") == "":
        print("OPENAI_API_KEY is NOT set yet")
        exit(1)
    else:
        print("OPENAI_API_KEY is fully set")

    st.set_page_config(
        page_title = "ZIKO",
        page_icon = "🤖"
    )

def main():
    init()

    chat = ChatOpenAI(temprature = 0)
    messages = [
        SystemMessage(content="You are a helpful assistant.")
        #HumanMessage(content=input),
        #AIMessage()
    ]

    st.header("ZIKO 🤖")

    with st.sidebar:
        user = st.text_input("Enter your message: ", key = "user")
    
    if user:
        message(user, is_user = True)
        messages.append(HumanMessage(content=user))
        response = chat(messages)
        message(response.content)



if __name__ == '__main__':
    main()
```

But I am getting this message:
ModuleNotFoundError: No module named 'langchain.chat_models'

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:
Installing langchain
Importing  langchain.chat_modules

### Expected behavior

Module loads successfully

**Comment by a-gasior** [comment]
I had this same issue and switched my python from version 3.10.12 -> 3.11.5 and the issue was resolved.

**Comment by code-haven** [comment]
I ran into this and realised that it was failing because I had the import inside a folder called "langchain" which causes the interpreter to look for files within the folder. I renamed the module to something else and it worked.
