### ISSUE TITLE
[Feature Request] Chain-of-Verification (CoVe) 

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#11285]
### Feature request

Hi, I'd like to request the chain type of Chain-of-Verification (CoVe).

### Motivation

I see that there's already a `LLMCheckerChain` and a `SmartLLMChain` which use related techniques, but implementing the below four-step process as described in https://arxiv.org/abs/2309.11495 would, I think, still be a very popular feature.

**Chain-of-Verification steps:**
1. drafts an initial response
2. plans verification questions to fact-check its draft
3. answers those questions independently so the answers are not biased by other responses
4. generates its final verified response

### Your contribution

Not sure yet.

**Comment by fapont** [comment]
Hello, I would be very interested in working on this project to get hands-on with the library :)
Is it ok ?

**Comment by lijameshao** [comment]
Hi @austinmw, I've recently written a [blog post](https://medium.com/@james.li/a-langchain-implementation-of-chain-of-verification-cove-to-reduce-hallucination-0a8fa2929b2a) on the implementation on this, but I haven't packaged it into a module.

I'll look more into how I can contribute.

In the meantime, please feel free to make a copy of the [Colab](https://colab.research.google.com/drive/10EEKZCuD6ZLqywIg_r3d7mLuQwHNINT3?usp=sharing) to test out your use cases.

**Comment by fapont** [comment]
Hi @lijameshao, I also worked on a packaged version using langchain using langchain classes such as `MapReduceDocumentsChain`, I didn't had time to finish this contribution yet but I would be interested to share my implementation with you if you're interested.

I planned to finish this PR next week, tell me if you're interested :)

**Comment by lijameshao** [comment]
> Hi @lijameshao, I also worked on a packaged version using langchain using langchain classes such as `MapReduceDocumentsChain`, I didn't had time to finish this contribution yet but I would be interested to share my implementation with you if you're interested.
> 
> I planned to finish this PR next week, tell me if you're interested :)

Hi @fapont, sounds good - let's collaborate and make it happen :)

**Comment by fapont** [comment]
> > Hi @lijameshao, I also worked on a packaged version using langchain using langchain classes such as `MapReduceDocumentsChain`, I didn't had time to finish this contribution yet but I would be interested to share my implementation with you if you're interested.
> > I planned to finish this PR next week, tell me if you're interested :)
> 
> Hi @fapont, sounds good - let's collaborate and make it happen :)

Maybe we could have a talk next week if you want
