### ISSUE TITLE
PGVector 'mmr' does not apply the filter at the time of retrieval

### ISSUE THREAD

**Issue by ssolta** [langchain-ai/langchain#11295]
### System Info

langchain==0.0.291

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
elements_for_filter = ['a10','b10']
 the_filter = {
     'type': {
         'in': elements_for_filter
     }
 }
 if rag_similarity_strategy == 'similarity_score_threshold':
     retriever = vectordb.as_retriever(search_type=rag_similarity_strategy, search_kwargs={
          "k": 4, 'score_threshold': 0.6,
          'filter': the_filter})
 elif rag_similarity_strategy == 'mmr':
     retriever = vectordb.as_retriever(search_type=rag_similarity_strategy, search_kwargs={
         'filter': the_filter, "k": 4, 'lambda_mult': 0.5,
         'fetch_k': 20,
         })
```

### Expected behavior

I expect the retrieve apply the filter when I use 'mmr' as it does when I used 'similarity_score_threshold' but it does not.

**Comment by ssolta** [comment]
It seems that in the following function calling line 741 in pgvector.py the filter is not passed so the filter wouldn't be applied when the __query_collection is called.
` return self.max_marginal_relevance_search_by_vector(
            embedding,
            k=k,
            fetch_k=fetch_k,
            lambda_mult=lambda_mult,
            **kwargs,
        )`

**Comment by tasansal** [comment]
I can confirm this issue. I didn't see any PR to fix this. @ssolta are you working on fixing this or need help?
