### ISSUE TITLE
VLLMOpenAI class should be generalised

### ISSUE THREAD

**Issue by mauri3112** [langchain-ai/langchain#11291]
### Feature request

we are using your VLLMOpenAI class in a project to connect to our vLLM. we however don't use openAI, and found kind of weird that you have this implemented, but naming suggests it is specifically for openAI only. You could generalise this class so that it can be used with any kind of vLLM (which it already does). So basically just some refactoring might be the whole thing.

### Motivation

We are using this VLLMOpenAI class with other open source models. Kind of misleading and unintuitive to say we use the VLLMOpenAI class. We wish ourselves a custom class for open source models or any other kind of vLLM deployment.

### Your contribution

No time capacity :( So other than my genuine enthusiasm on your project and the whole documenting of the feature I can't really offer much more...

**Comment by mspronesti** [comment]
@mauri3112 Not sure I understand the point of this comment. `VLLMOpenAI` refers to the fact that the class integrates [vLLM's OpenAI-compatible API](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html#openai-compatible-server) into langchain. 
It has nothing to do with OpenAI models, it's just the interface to be OpenAI-like. To use it you need a vLLM server exposing the model you want to use and served with vLLM
```shell
python -m vllm.entrypoints.openai.api_server --model <valid_model_supported_in_vllm>
```
and then you can use langchain's `VLLMOpenAI` to call it from the server's URL using an OpenAI-like interface. 
If you don't like this approach or if you find it confusing, just use [langchain.llms.VLLM](https://python.langchain.com/docs/integrations/llms/vllm) instead.

**Comment by mauri3112** [comment]
The think is, that [langchain.llms.VLLM](https://python.langchain.com/docs/integrations/llms/vllm) doesn't provide the alternative to use a vLLM as a client (vLLM is running on a different server). So I want to have the same mechanism as for openAI, but for open source models that we host ourselves in separate servers.

**Comment by mspronesti** [comment]
@mauri3112 I see. Then `VLLMOpenAI` is the right class for this.

**Comment by JerryFan996** [comment]
that is a nice problem for a project. I will see whether I can develop a new class.
