### ISSUE TITLE
Azure Cognitive Search vector DB store performs slow embedding as it does not utilize the batch embedding functionality

### ISSUE THREAD

**Issue by butlfrazp** [langchain-ai/langchain#11313]
### System Info

- Langchain Version: 0.0.306
- Python Version: 3.10.11
- Azure Cognitive Seach (any sku)
- Embedding that has batch functionality

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

1. Get a document (or set of documents) that will produce a few hundred chunks
2. Run the sample code provided by Langchain to index those documents into the Azure Search vector store (sample code below)
3. Run steps 1 and 2 on another vector store that supports batch embedding (milvus implementation supports batch embeddings)
4. Analyze the delta between the two vectorization speeds (Azure Search should be noticeably slower)

Sample code:

```python
import openai
import os
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores.azuresearch import AzureSearch

vector_store_address: str = "YOUR_AZURE_SEARCH_ENDPOINT"
vector_store_password: str = "YOUR_AZURE_SEARCH_ADMIN_KEY"

embeddings: OpenAIEmbeddings = OpenAIEmbeddings(deployment=model, chunk_size=1)
index_name: str = "langchain-vector-demo"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)

from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter

loader = TextLoader("../../../state_of_the_union.txt", encoding="utf-8")

documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

vector_store.add_documents(documents=docs)
```

### Expected behavior

The expected behavior for the Azure search implementation to also support batch embedding if the implementation of the embedding class supports batch embedding. This should result in significant speed improvements when comparing the single embedding approach vs the batch embedding approach.

**Comment by butlfrazp** [comment]
It seems like I cannot assign this, but I am going to work on this issue.

**Comment by pietz** [comment]
I'm facing the same issue. I had my hopes up that the async version of add_documents() would accelerate things but it didn't work the way I hoped.

Currently adding documents will request an embedding for each doc sequentially until it has 1000 embeddings. Then it will upload them to the vector store and continue with the next 1000.

Two possible improvements:

1. Allow to send documents to the embedding function in batches. I believe Azure OpenAI currently allows batches up 16 but they will hopefully increase this number soon.
2. Send the the requests for embeddings asynchronously, where multiple requests are send out before responses get back. There is aadd_documents() but it seems to send out everything in a sequential fashion for some reason.

**Comment by pablocastilla** [comment]
Hi, here we have the same issue. When we split a document in 180 chunks it takes one minute to upload to azure.

**Comment by pietz** [comment]
Nothing has happened here, so let me post my dirty workaround to be used as an alternative to `vector_store.add_documents(docs)`:

```python
for i in tqdm(range(0, len(docs), 1000)):
    embeddings_batch = embedder.embed_documents([x.page_content for x in docs[i:i+1000]])
    docs_batch = []
    for j, doc in enumerate(docs[i:i+1000]):
        key = str(uuid.uuid4())
        doc_id = base64.urlsafe_b64encode(bytes(key, "utf-8")).decode("ascii")
        doc_dict = {
            "id": doc_id,
            "content": doc.page_content,
            "content_vector": embeddings_batch[j],
            "metadata": json.dumps(doc.metadata)
        }
        docs_batch.append(doc_dict)
    vector_store.client.upload_documents(docs_batch)
```
