### ISSUE TITLE
OperationalError: (pyodbc.OperationalError) ('08001', '[08001] 

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#11337]
### System Info

latest version of langchain. python=3.11.4

### Who can help?

@all 

### Information

- [x] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.agents import *
from langchain.llms import OpenAI
from langchain.sql_database import SQLDatabase

from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor

from langchain.chat_models import ChatOpenAI 

# from secret_key import openapi_key

openapi_key = "######"

os.environ['OPENAI_API_KEY'] = openapi_key

def chat(question):

    llm = OpenAI(temperature=0)
    tools = load_tools(["llm-math"], llm=llm)

    agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)

    driver = 'ODBC Driver 17 for SQL Server'  
    host = '####'
    database = 'chatgpt'
    user = 'rnd'
    password = '###'
    #db_uri = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{password}@{host}/{database}?driver={driver}")
    db = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{password}@{host}/{database}?driver=ODBC+Driver+17+for+SQL+Server")

    llm = ChatOpenAI(model_name="gpt-3.5-turbo",
                    temperature=0, 
                    max_tokens=1000)

    # toolkit = SQLDatabaseToolkit(db=db)
    toolkit = SQLDatabaseToolkit(db=db, llm=llm)
    agent_executor = create_sql_agent(
        llm=llm,
        toolkit=toolkit,
        verbose=True,
        reduce_k_below_max_tokens=True,
    )

    mrkl = initialize_agent(
        tools,
        ChatOpenAI(temperature=0),
        agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True,
        handle_parsing_errors=True,
    )

    return agent_executor.run(question)

### Expected behavior

i need to connect to test server, but i'm getting an error while connecting to it, but is working fine on local server , been getting 
"OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]Named Pipes Provider: Could not open a connection to SQL Server [53].  (53) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (53)')
"

**Comment by jyoti194** [comment]
Hi, thank you for response.
But here I'm able to connect to the same server using pyodbc.connect but when I'm trying with connection string in sqlalchemy I'm getting the above mentioned error.

**Comment by jyoti194** [comment]
hi @dosu-bot , can you explain about Using a DSN (Data Source Name)(2nd point), 
this another simple code which i was using to test with test server
from sqlalchemy import create_engine

server = '-------'
# database = 'HR_Git'
database = 'it_feb'
username = 'sa'
password = '------'  # Removed the space

# Define the connection string
# connection_string = f'mssql+pyodbc://{username}:{password}@{server}:1433/{database}?driver=ODBC+Driver+17+for+SQL+Server'
connection_string = f"mssql+pyodbc://username:password@tcp:hostname/database?driver={'ODBC Driver 17 for SQL Server'}"


engine = create_engine(connection_string)

result = engine.execute('SELECT * FROM mst_Area')  

for row in result:
    print(row)

engine.dispose()

note: i have just removed server details and password

**Comment by jyoti194** [comment]
Hi @dosu-bot , do i need to create a DSN ie. system DSN in test server? or local machine?

**Comment by jyoti194** [comment]
Hi dosu-bot , my password is "root@123" does having a @ in real password as an "@" symbol in it, and so this interferes with the latter connection string?

**Comment by jyoti194** [comment]
@dosu-bot,
1. this the error
  "sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08001', '[08001] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: A non-recoverable error occurred during a database lookup.\r\n (11003) (SQLDriverConnect); [08001] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0); [08001] [Microsoft][ODBC Driver 17 for SQL Server]A network-related or instance-specific error has occurred while establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and if SQL Server is configured to allow remote connections. For more information see SQL Server Books Online. (11003)')"
2.langchain information
Name: langchain
Version: 0.0.306
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: C:\Users\rndbcpsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: aiohttp, anyio, dataclasses-json, jsonpatch, langsmith, numexpr, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: langchain-experimental

3. code snippet
 import sqlalchemy

from sqlalchemy import create_engine

# server = '------'
server = '-------'
# database = 'HR_Git'
database = 'it_feb'
username = 'sa'
password = 'root@123'  

# Define the connection string
connection_string = f'mssql+pyodbc://{username}:{password}@{server}:1433/{database}?driver=ODBC+Driver+17+for+SQL+Server'
# connection_string = f'mssql+pyodbc://username:password@sql'
# connection_string = f"mssql+pyodbc://username:password@hostname/database?driver={'ODBC Driver 17 for SQL Server'}"


engine = create_engine(connection_string)

result = engine.execute('SELECT * FROM dbo.mst_Area')  

for row in result:
    print(row)

engine.dispose()

note: i just removed the server name and password

**Comment by jyoti194** [comment]
Hi @dosu-bot ,
I'm able to connect to the test server, the issue was with the special character only and after using 
from urllib.parse import quote_plus

password = quote_plus("your_password_with_@_symbol")

this I'm able to connect.
i have another question, my db is very huge so, as i'm running a query im getting  tocke error or parsing error, instead of working on entire db can i work on SQL View? how to do that?

**Comment by jyoti194** [comment]
Hi dosu-bot , can you link any work done related to this, i need to understand it in detail, thank you.

**Comment by devstein** [comment]
Hi @jyoti194 I'm the creator of [Dosu](https://dosu.dev). We're working on improving the types of request Dosu can handle.

What are you looking for when you ask Dosu for 
> can you link any work done related to this, i need to understand it in detail, thank you.

Are you looking for merged PRs? Or something else?


Also, any thoughts/comments/feedback is super valuable!

**Comment by jyoti194** [comment]
Hi @devstein , i was trying to get assistant on, if there is any related work which can help me in understanding things lot better.

Dosu was good with giving responses based on the information provided.

i have another question, I'm trying to doing a project to create a chatbot using langchain and chatgpt openai, on the data is from sql server management studio, I'm able to create a chatbot with a small database with the above  code i have provided, but if the database is huge like around 5gb, for such i,m getting error like " token limit error" or "parsing errors" how to solve it or deal with the dataset?

here is the code snipet:
from langchain.agents import *
from langchain.llms import OpenAI
from langchain.sql_database import SQLDatabase

from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor

from langchain.chat_models import ChatOpenAI

from secret_key import openapi_key
openapi_key = "######"

os.environ['OPENAI_API_KEY'] = openapi_key

def chat(question):

llm = OpenAI(temperature=0)
tools = load_tools(["llm-math"], llm=llm)

agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)


driver = 'ODBC Driver 17 for SQL Server'  
host = '####'
database = 'chatgpt'
user = 'rnd'
password = '###'
#db_uri = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{password}@{host}/{database}?driver={driver}")
db = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{password}@{host}/{database}?driver=ODBC+Driver+17+for+SQL+Server")

llm = ChatOpenAI(model_name="gpt-3.5-turbo",
                temperature=0, 
                max_tokens=1000)

# toolkit = SQLDatabaseToolkit(db=db)
toolkit = SQLDatabaseToolkit(db=db, llm=llm)
agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True,
    reduce_k_below_max_tokens=True,
)

mrkl = initialize_agent(
    tools,
    ChatOpenAI(temperature=0),
    agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True,
)

return agent_executor.run(question)

Thank you.

**Comment by jyoti194** [comment]
@dosu , instead of tables like here

include_tables=['table1', 'table2']  # Include only the tables you want
db = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{password}@{host}/{database}?driver=ODBC+Driver+17+for+SQL+Server", include_tables=include_tables)

can i use view directly?

**Comment by jyoti194** [comment]
Hi @dosu-bot , 
ImportError: cannot import name 'SQLDatabaseSequentialChain' from 'langchain.chains' (c:\Users\rndbcpsoft\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\__init__.py)

**Comment by jyoti194** [comment]
@dosu-bot ,
pip install langchain==0.0.312
        ^
SyntaxError: invalid syntax
