### ISSUE TITLE
Issue: Documents embeddings with many and similar numbers don't return good results

### ISSUE THREAD

**Issue by juan-gomez-stellion** [langchain-ai/langchain#11331]
### Issue you'd like to raise.

Hi! I am trying to create a question answering chatbot with PDFs. There is something different in these documents. I have different articles with their number, example: article 1.2.2.1.3, article 1.2.3.4.5, article 2.3.4.1.3, etc.

When I ask for a specific article, it can't find the answer and return "the article x.x.x.x.x is not in the context". I have tried with some embeddings techniques and vector store, but it does not work.

Any ideas?

PD: The PDF documents are around 450 pages

**Comment by juan-gomez-stellion** [comment]
I am using OpenAIEmbeddings and FAISS database, is there any thing that I can do to resolve the problem with this tools?

**Comment by juansebm** [comment]
Hey there! I'm really interested into this issue. I did get the same problem over a month ago and couldn't solve it at all. Did you find any other way to make this embedding thing better?
