### ISSUE TITLE
Conversational Chain Error 429

### ISSUE THREAD

**Issue by harchyboy** [langchain-ai/langchain#11347]
### System Info

Today, all of a sudden I'm getting a error status code 429 using the Conversation chain. Nothing has changed, expect the day I've run the script. Any ideas?
It works with the normal LLM chain, so it must be to do with the Conversation Chain not working or the memories.

Using Flowise.
Chrome

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Request failed with status code 429 and body {"error":{"message":"Rate limit reached for 10KTPM-200RPM in organization org-ByeURhCRRujcKf7u7QrlrudH on tokens per min. Limit: 10000 / min. Please try again in 6ms. Contact us through our help center at help.openai.com if you continue to have issues.","type":"tokens","param":null,"code":"rate_limit_exceeded"}}

### Expected behavior

I expect the LLM chain to write the content.

**Comment by Justinljg** [comment]
Your conversation chain may have accumulated too much chat history(>10000 tokens). I think if you set a max token for your memory it should work. Example : ```memory=ConversationTokenBufferMemory(llm=OpenAI(), max_token_limit=600)```

**Comment by sudranga** [comment]
I guess its possible. What memory do you use? Some of the memory types do make additional calls(primarily to summarize) to the LLM
