### ISSUE TITLE
Missing 1 required positional argument for function that has `self` argument.

### ISSUE THREAD

**Issue by SongpolR** [langchain-ai/langchain#11341]
### System Info

langchain==0.0.286

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

``` python
def add_product(self, input: str):
        print(f"🟢 Add product {input}")
```

``` python
tools = [
       Tool(
            name="AddProduct",
            func=add_product,
            description="""
                Add product to order.

                Input of this tool must be a single string JSON format:

                For example: '{{"name":"Nike Pegasus 40"}}'
            """
        )
]
```

``` python
agent = initialize_agent(
        tools=tools, 
        llm=__gpt4, 
        agent=AgentType.OPENAI_FUNCTIONS, 
        verbose=True,
        prompt=prompt
)
```

### Expected behavior

Error:

```
TypeError: add_product() missing 1 required positional argument: 'input'
```

Expected: 
```
Function `add_product` called with correct input.
```

**Comment by SongpolR** [comment]
Problem solved by following @dosu-bot instruction.

**Comment by omiguelpinheiro** [comment]
You were doing soo good dosu

**Comment by omiguelpinheiro** [comment]
You were doing soo well dosu
