### ISSUE TITLE
How can `Document` metadata be passed into prompts?

### ISSUE THREAD

**Issue by batmanscode** [langchain-ai/langchain#1136]
Here is an example:

- I have created vector stores from several podcasts
- `metadata = {"guest": guest_name}`
- `question = "which guests have talked about <topic>?"`

Using `VectorDBQA`, this could be possible if `{context}` contained text + metadata

**Comment by batmanscode** [comment]
Another format for retrieving text with metadata could be:

```
TEXT: <what the guest said>
GUEST: <guest_name>
```

Or maybe even:

```
TEXT: <what the guest said>
METADATA: {"guest": guest_name}
```

This way when asking questions, I can ask things like `"what did <guest_name> say about <topic>?"`

**Comment by sbc-max** [comment]
I have a number of different uses cases where this would also be helpful. I considered just adding the metadata directly to the text before embedding, but that's not ideal.

**Comment by flash1293** [comment]
Not 100% sure whether applicable to your case, but if you are using the stuff chain, you can do this by adjusting the `document_prompt`:

```
document_prompt = PromptTemplate(input_variables=["page_content", "id"], template="{page_content}, id: {id}")
qa = RetrievalQA.from_chain_type(llm=OpenAI(temperature=0), chain_type="stuff", retriever=vector_store.as_retriever(), chain_type_kwargs={"document_prompt": document_prompt})
```

if there is an `id` metadata in your doc, it will be injected correctly

**Comment by batmanscode** [comment]
> Not 100% sure whether applicable to your case, but if you are using the stuff chain, you can do this by adjusting the `document_prompt`:
> 
> ```
> document_prompt = PromptTemplate(input_variables=["page_content", "id"], template="{page_content}, id: {id}")
> qa = RetrievalQA.from_chain_type(llm=OpenAI(temperature=0), chain_type="stuff", retriever=vector_store.as_retriever(), chain_type_kwargs={"document_prompt": document_prompt})
> ```
> 
> if there is an `id` metadata in your doc, it will be injected correctly

Wow that's cool, didn't know about that kwarg! Thanks, will try this 😃

**Comment by connorjoleary** [comment]
This won't change the docs grabbed by the retriever right? For example if I have a guest (Greg) stored in the metadata and I ask "what did Greg say", the retriever won't take the guest into account when grabbing the source and use it to match on something like similarity.

**Comment by flash1293** [comment]
No, that's just for the refinement of the context documents by the LLM part.

**Comment by joe-barhouch** [comment]
Is there a way i could do the same with a ConversationalRetrievalChain? 
I keep running into the error: ValueError: Missing some input keys
This is my function:
`def get_conversation_chain(vectorstore: FAISS):
    llm = ChatOpenAI(model="gpt-4-0613", temperature=0.5, streaming=False)
    # llm = ChatOpenAI(model="gpt-3.5-turbo-16k", temperature=0.2)

    templates = [
        SystemMessagePromptTemplate.from_template(
            prompts.system_prompt_v1,
            input_variables=["context", "source", "page_number"],
        ),
        HumanMessagePromptTemplate.from_template(
            prompts.user_prompt,
            input_variables=["context", "source", "page_number"],
        ),
    ]
    qa_template = ChatPromptTemplate.from_messages(templates)

    memory = ConversationSummaryBufferMemory(
        llm=llm, max_token_limit=5000, memory_key="chat_history", return_messages=True
    )
    memory.input_key = "question"
    memory.output_key = "answer"

    conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vectorstore.as_retriever(
            k=5, search_type="mmr", fetch_k=20, lambda_mult=0.5
        ),
        memory=memory,
        return_source_documents=True,
        chain_type="stuff",
        combine_docs_chain_kwargs={"prompt": qa_template},
    )

    return conversation_chain

`

**Comment by Robs-Git-Hub** [comment]
> Is there a way i could do the same with a ConversationalRetrievalChain? I keep running into the error: ValueError: Missing some input keys This is my function: ` def get_conversation_chain(vectorstore: FAISS): llm = ChatOpenAI(model="gpt-4-0613", temperature=0.5, streaming=False)

@joe-barhouch  Did you solve this? I want to use metadata as an input_variable but it only seems to allow 'context', which is page_content.

**Comment by joe-barhouch** [comment]
I had to step back from Conversational Agents. The layer of abstraction helps with prototypes but hurts full fledged apps.

I ended up implementing my own version with LLMChain with a memory. All of the document retrieval is taken care of by immediately calling `similarity_search` or similar calls directly from your vectorstore.
Then i can get the metadata I have created and pass it into the prompt.

At the end of the day the RAG application just copy paste the results to the prompt, so I just handled it on my own without the need of the abstraction layer of Conversation Agents

**Comment by Robs-Git-Hub** [comment]
> @Robs-Git-Hub had to step back from Conversational Agents. The layer of abstraction helps with prototypes but hurts full fledged apps.

Thanks for the quick reply. Very helpful, and I was reaching a similar conclusion.

**Comment by theekshanamadumal** [comment]
### for ConversationalRetrievalChain

```
document_combine_prompt = PromptTemplate(
     input_variables=["source","year", "page","page_content"],
     template= """source: {source}
     year: {year}
     page: {page} 
     page content: {page_content}"""
)
```





```
qa = ConversationalRetrievalChain.from_llm(
                         ...           ,
        combine_docs_chain_kwargs={
            "prompt": retrieval_qa_chain_prompt,
            "document_prompt": document_combine_prompt,
        },
        
)
```

**Comment by joe-barhouch** [comment]
@theekshanamadumal 
 Unless you query the metadata, this will give an error with the missing input variables passed into the prompt template

**Comment by AI-General** [comment]
What is difference between "prompt" and "document_prompt"?

**Comment by theekshanamadumal** [comment]
> @theekshanamadumal Unless you query the metadata, this will give an error with the missing input variables passed into the prompt template

**Comment by theekshanamadumal** [comment]
> What is difference between "prompt" and "document_prompt"?

document prompt is the Prompt template used to organize content  in retrieved documents.
This ends up in the main prompt as the 'context'

**Comment by marwantest1** [comment]
> ### for ConversationalRetrievalChain
> ```
> document_combine_prompt = PromptTemplate(
>      input_variables=["source","year", "page","page_content"],
>      template= """source: {source}
>      year: {year}
>      page: {page} 
>      page content: {page_content}"""
> )
> ```
> 
> ```
> qa = ConversationalRetrievalChain.from_llm(
>                          ...           ,
>         combine_docs_chain_kwargs={
>             "prompt": retrieval_qa_chain_prompt,
>             "document_prompt": document_combine_prompt,
>         },
>         
> )
> ```

i tried this and it gives me error 
```
ValidationError: 1 validation error for StuffDocumentsChain document_propmt extra fields not permitted (type=value_error.extra)
```
 , im trying to use ConversationalRetrievalChain.from_llm to search from vector db , and i stored metadata with it , so i want the conversationalretrievalchain to include the metadata in the prompt to let the LLM aware of the metadata.
 and here is my code 
      custom_prompt_template = """
    {context}

    Question: {question}
    """
    custom_prompt = PromptTemplate(
    template=custom_prompt_template,
    input_variables=["context", "question"],
    )
    document_combine_prompt = PromptTemplate(
     input_variables=["candidatename"],
     template= """
        candidatename:{candidatename}
        """
)
    conversation_chain=ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=SelfQueryRetriever.from_llm(llm,vectorstore,document_content_description,metadata_field_info,verbose=True),
       
        memory=memory,
        verbose=True,
        return_source_documents=True,
        combine_docs_chain_kwargs={"prompt": custom_prompt,
                                   "document_propmt":document_combine_prompt
                                   }
    )

response=st.session_state.conversation({'question':user_question})

**Comment by sgautam666** [comment]
> @Robs-Git-Hub had to step back from Conversational Agents. The layer of abstraction helps with prototypes but hurts full fledged apps.
> 
> I ended up implementing my own version with LLMChain with a memory. All of the document retrieval is taken care of by immediately calling `similarity_search` or similar calls directly from your vectorstore. Then i can get the metadata I have created and pass it into the prompt.
> 
> At the end of the day the RAG application just copy paste the results to the prompt, so I just handled it on my own without the need of the abstraction layer of Conversation Agents

Hello, I am looking for similar use case. I am extracting some metadata using 'similarity_search'. Now I want to use this to another QA chain. Can you show me the code snippet you used?
