### ISSUE TITLE
Issue: differences between tool and llm

### ISSUE THREAD

**Issue by ZyeG** [langchain-ai/langchain#11365]
### Issue you'd like to raise.

Hi, I want to clarify some questions about tool and llm usage.

If an agent is initialized with multiple llm and tools, 
1. how does the agent choose which llm or tool to use to answer the prompt? 
2. How is llm different from tools? Can you give some examples of each category? 
3. Can the agent use multiple tools/llm? If the agent can use multiple tools, what happen if the output generated by such tools/llm conflict with each other? In that case, which result will be returned to user?

for example, in the code beloew (cited from langchain doc), the agent is initialized with both 'llm_chain=llm_chain' (where llm_chain is OpenAI)and 'tools=tools' (where tool is google search engine). Which one is used to generate the result?

```search = GoogleSearchAPIWrapper()
tools = [
    Tool(
        name="Search",
        func=search.run,
        description="useful for when you need to answer questions about current events",
    )
]

prefix = """Have a conversation with a human, answering the following questions as best you can. You have access to the following tools:"""
suffix = """Begin!"

{chat_history}
Question: {input}
{agent_scratchpad}"""

prompt = ZeroShotAgent.create_prompt(
    tools,
    prefix=prefix,
    suffix=suffix,
    input_variables=["input", "chat_history", "agent_scratchpad"],
)
memory = ConversationBufferMemory(memory_key="chat_history")

llm_chain = LLMChain(llm=OpenAI(temperature=0), prompt=prompt)
agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True)
agent_chain = AgentExecutor.from_agent_and_tools(
    agent=agent, tools=tools, verbose=True, memory=memory
)

agent_chain.run(input="How many people live in canada?")
agent_chain.run(input="what is their national anthem called?")```

**Comment by sudranga** [comment]
1. The agent asks the LLM to decide on a tool.
2. LLM is the large language model. Tools are generally constructs that the LLM can use to augment its abilities to answer a query.
3. Atleast, langchain requests that the LLM choose a single action (see https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/chat/prompt.py)

HTH
