### ISSUE TITLE
Does langchain index the speaker notes in powerpoint?

### ISSUE THREAD

**Issue by rishimalhotra2** [langchain-ai/langchain#11363]
### Issue you'd like to raise.

When I use directory loader, does langchain index the speaker notes in powerpoint?

**Comment by AthulVincent** [comment]
Hi @rishimalhotra2 . You could try with a PowerPoint document with only speaker notes to test whether the speaker notes are indexed. If not I could take a look into implementing this functionality.

**Comment by jamieRowen-mediacom** [comment]
Have just tested this with a presentation that only has speaker notes and it does not pick them up

**Comment by jamieRowen-mediacom** [comment]
My guess would be that this should become part of [unstructured](https://github.com/Unstructured-IO/unstructured). A cursory scan of [SO](https://stackoverflow.com/questions/63659972/extract-presenter-notes-from-pptx-file-powerpoint) suggests that it shouldn't be too hard to extract them:

**Comment by jamieRowen-mediacom** [comment]
My apologies, I think this feature is already available. You can pass the argument `include_slide_notes=True` on creating the document loader.
