### ISSUE TITLE
Issue: sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by BillBridge** [langchain-ai/langchain#11379]
### Issue you'd like to raise.

Hi, I have implemented the indexing workflow as in https://python.langchain.com/docs/modules/data_connection/indexing making use of Pinecone and sqlite. This runs perfect within a Pycharm dev environment. But after building the app with Pyinstaller, I get the following error: sqlite3.OperationalError: unable to open database file. I think this one is coming from langchain.indexes.index. The error message is very cryptic. Why can't this file be opened? Is it locked? Is it corrupted - no as I can open it with a desktop sql manager app. I tried different locations for storing the sqlite database but makes no difference. 
Does anyone has some ideas on how to solve this?

**Comment by BillBridge** [comment]
@dosu-bot
the sqlite database file is an absolute path. Connecting to the database is being dealt with by the index method in langchain.indexes. I can not change the logics of this method.

**Comment by BillBridge** [comment]
Seems it is caused by UnstructuredPDFLoader. Will create a new issue.

**Comment by nie-s** [comment]
How you solve the issus T_T

**Comment by Ankit9721** [comment]
i m getting error when  a running the code
