### ISSUE TITLE
StreamlitCallbackHandler thinking.. / spinner Not stopping

### ISSUE THREAD

**Issue by quantumalchemy** [langchain-ai/langchain#11398]
### System Info

python:3.10.13 bookworm (docker)
streamlit
Version: 1.27.1
langchain
Version: 0.0.306

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

   # Display assistant response in chat message container
    with st.chat_message("🧞‍♂️"):
        message_placeholder = st.empty()
        cbh = StreamlitCallbackHandler(st.container())
        AI_response = llm_chain.run(prompt,callbacks=[cbh])

### Expected behavior

 the "Thinking.." spinner STOPS or hides after LLM finishes its response

No Parameters I can find here
https://api.python.langchain.com/en/latest/callbacks/langchain.callbacks.streamlit.streamlit_callback_handler.StreamlitCallbackHandler.html 
that would affect this

**Comment by quantumalchemy** [comment]
thanks but not working - seems like complete() is not being called 
anyway to show generic    .. strip out  spinner AND "thinking.." just display the LLM stream and nothing else?
I see you can use custom "thought_labeler "  can you give me example of a custom thought_labeler  that would have No " spinner and No "thinking.." just stream?

**Comment by heiningair** [comment]
I have the same issue. It never stops getting out of the "thinking..." aka "running" state. Have you been able to find a workaround for that?

**Comment by MiNeves00** [comment]
Same issue on my side. Thinking does not stop until i give it a new input.

**Comment by fcasadome** [comment]
I used `st.rerun()` to redraw the conversation to fix this, but it enters some infinite loop after upgrading to the new streamlit version 1.28.0

**Comment by TheDarkTrumpet** [comment]
I had the same issue.  I decided to debug this further.

I created a fork and committed the change in: https://github.com/TheDarkTrumpet/langchain

I'm still pretty new to LangChain, so before I do a pull request, I will likely need some help verifying the chain.

The modification was on the `on_chain_end` in the streamlit_callback.py file to change the `pass` to the following:

```python
if 'answer' in outputs:
     self.on_agent_finish(outputs['answer'])
     self._parent_container.markdown(f'{outputs["answer"]}')
```

**Comment by Hadi2525** [comment]
I have this solution that probably can be a remedy to replace `StreamlitCallbackHandler` until the issue is fixed.

You set your handler to `StreamingStdOutCallbackHandler`, you can parse the stdout to the streamlit using the context manager. Here is an example code:
`from io import StringIO
from contextlib import contextmanager, redirect_stdout

@contextmanager
def st_capture(output_func):
    with StringIO() as stdout, redirect_stdout(stdout):
        old_write = stdout.write

        def new_write(string):
            ret = old_write(string)
            output_func(stdout.getvalue())
            return ret
        
        stdout.write = new_write
        yield

When calling your LLM Chain, run this:

```
with st.chat_message("assistant"):
            output = st.empty()
            with st_capture(output.info):
                chain.invoke(user_prompt)
`

**Comment by ucola** [comment]
Any progress on this issue? @Hadi2525 can you do a whole example with your code?

**Comment by BioStarr** [comment]
Any info on this, since I got same bug.

**Comment by KedoKudo** [comment]
I made a tiny PR that should resolve this issue:https://github.com/streamlit/streamlit/pull/8311

In the meantime, please use the following code to force an update to the container status:

```python
callback = StreamlitCallbackHandler(st.container())
response = llm.qa.invoke(user_prompt)
callback._current_thought._container.update(
    label="",
    state="complete",
    expanded=True,
)
```

**Comment by BioStarr** [comment]
Works thanks :)

After change integration what part of langchain should I upgrade with pip?

**Comment by KedoKudo** [comment]
> Works thanks :)
> 
> After change integration what part of langchain should I upgrade with pip?

The change is in `streamlit`, `langchain_community` is providing a thin wrapper for the callback provided by `streamlit`.

**Comment by BioStarr** [comment]
Thanks, this works beautifully now. 5/5 stars for fix.

Could I possibly bother you for list of arguments since while I am waiting for bot to respond there is empty text displayed until streaming starts, and I would like to see how to remove it.

![image](https://github.com/langchain-ai/langchain/assets/58954329/c62fb70c-4a99-4871-bad1-3bab0e84545a)

**Comment by KedoKudo** [comment]
> Thanks, this works beautifully now. 5/5 stars for fix.
> 
> Could I possibly bother you for list of arguments since while I am waiting for bot to respond there is empty text displayed until streaming starts, and I would like to see how to remove it.
> 
> ![image](https://private-user-images.githubusercontent.com/58954329/313705376-c62fb70c-4a99-4871-bad1-3bab0e84545a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NzUzMzUsIm5iZiI6MTcxMDg3NTAzNSwicGF0aCI6Ii81ODk1NDMyOS8zMTM3MDUzNzYtYzYyZmI3MGMtNGE5OS00ODcxLWJhZDEtM2JhYjBlODQ1NDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE5MDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTk2MjdkNWFhOWMxNDhkZWY0MWIzMTg2YmEyMTU2NWJhYTI4MzU3ZWMyNjNhOTVkOThmZjk0MDkxOTMwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmqMLP76xskZuFjwh4pRZIgDj0kbiPBqU0VSCFYl1Ls)

You are asking to modify the default behaviors of `st.container`, the only solution I can think of would be doing a monkey patching until streamlit provide a way to modify the default text in an empty container:

```python
callback = StreamlitCallbackHandler(st.container(), collapse_completed_thoughts=False)
# save the original func
org_on_llm_start = callback.on_llm_start

def new_on_llm_start(*args, **kwargs):
    org_on_llm_start(*args, **kwargs)
    callback._current_thought._container.write("")

# patch
callback.on_llm_start = new_on_llm_start
```
