### ISSUE TITLE
Issue: prevent a agent from exceeding the token limit

### ISSUE THREAD

**Issue by Ethanmbinns** [langchain-ai/langchain#11405]
### Issue you'd like to raise.

Hey there, I'm trying got find a way to prevent an agent from going over the token limit, I've looked at the docs, asked around and had no luck.

This is the error for better content:
 [ERROR] InvalidRequestError: This model's maximum context length is 16384 tokens. However, your messages resulted in 17822 tokens. Please reduce the length of the messages.

Any help would be great 😊

**Comment by eyurtsev** [comment]
take a look if this helps: https://api.python.langchain.com/en/latest/agents/langchain.agents.openai_functions_agent.agent_token_buffer_memory.AgentTokenBufferMemory.html

https://python.langchain.com/docs/use_cases/question_answering/how_to/conversational_retrieval_agents

**Comment by Ethanmbinns** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for reaching out. The error you're encountering is due to the total number of tokens in your messages exceeding the model's maximum context length. In LangChain, you can manage this by setting the `max_tokens` attribute of the `OpenAI` class to a specific value that is within the model's maximum context length.
> 
> Here's an example of how you can set the `max_tokens` attribute:
> 
> ```python
> from langchain.llms import OpenAI
> 
> # Create an instance of the OpenAI class
> openai = OpenAI(model_name="text-davinci-003")
> 
> # Get the maximum context size for the model
> max_context_size = openai.modelname_to_contextsize(openai.model_name)
> 
> # Set the max_tokens attribute to a value within the model's maximum context length
> openai.max_tokens = max_context_size - 1  # or any value less than max_context_size
> 
> # Alternatively, you can use the max_tokens_for_prompt method
> prompt = "Tell me a joke."
> openai.max_tokens = openai.max_tokens_for_prompt(prompt)
> ```
> 
> This will ensure that the number of tokens generated by the model does not exceed the model's maximum context length, thus preventing the InvalidRequestError.
> 
> You can also refer to these similar issues for more context:
> 
> * [Issue #2333](https://github.com/langchain-ai/langchain/issues/2333)
> * [Issue #3670](https://github.com/langchain-ai/langchain/issues/3670)
> * [Issue #5237](https://github.com/langchain-ai/langchain/issues/5237)
> 
> Please note that the default value of `max_tokens` in the `OpenAI` class is 256. If you're frequently encountering this error, you might want to consider setting `max_tokens` to a lower value.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 11836 tokens (11580 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.](https://github.com/langchain-ai/langchain/issues/2333)
> * [Feedback error while running langchain](https://github.com/langchain-ai/langchain/issues/3670)
> * [Token limit reached trying to use plugin](https://github.com/langchain-ai/langchain/issues/5237)
> * [libs/langchain/langchain/llms/openai.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/openai.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

A couple follow up questions,

1. I'm using Azure OpenAI how can I modify it to work with that.
2. Dose this number include the prompt I pass to the agent (as the prompt is quite big).
3. What is the behaviour of the agent when it reaches the limit

**Comment by junoriosity** [comment]
@Ethanmbinns @eyurtsev  I am receiving the same issue, when making use of some ChatGPT plugins.

Is there any solution how to overcome this issue? 🙂

**Comment by junoriosity** [comment]
@Ethanmbinns @eyurtsev 

I am currently trying to make use of a ChatGPT plugin in langchain:

```
from langchain.chat_models import ChatOpenAI
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
from langchain.tools import AIPluginTool

tool = AIPluginTool.from_plugin_url("https://www.wolframalpha.com/.well-known/ai-plugin.json")

llm = ChatOpenAI(temperature=0, streaming=True, max_tokens=1000)
tools = load_tools(["requests_all"])
tools += [tool]

agent_chain = initialize_agent(
    tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True
)
# agent_chain.run("what t shirts are available in klarna?")

agent_chain.run("How can I solve dx/dt = a(t)*x + b(t)")

```

However, I get the error:

```
InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 5071 tokens (4071 in the messages, 1000 in the completion). Please reduce the length of the messages or completion.

```

Do you have any idea to overcome this?

**Comment by KastanDay** [comment]
This issue generally is one of the biggest obstacles to langchain agents -- it should truncate by default or expose a hook where we can pass a `runnable` to truncate the text, much like the [`intermediate_steps` runnable hook](https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps).

**Comment by KastanDay** [comment]
I created my own truncate function, it works beautifully. 🚀

Full implementation here: https://github.com/KastanDay/langchain-improved-agents/blob/uiuc-dot-chat/libs/langchain/langchain/chat_models/openai.py#L330

Here's the core idea, in `libs/langchain/langchain/chat_models/openai.py`:

```python
def _truncate_messages(self, messages: List[BaseMessage]):
        '''
        Trim context to fit in window. Trim most recent messages first... TBD best strategy.
        TODO: Prioritize system message and most recent human message. All others are less important (older are least important)
        '''
        num_tokens_in_messages = self.get_num_tokens_from_messages(messages)
        print("/\/\/\/\/\ num_tokens_in_messages", num_tokens_in_messages)
        
        context_window_size = BaseOpenAI.modelname_to_contextsize(self.model_name)
        if self.get_num_tokens_from_messages(messages) > context_window_size:
            encoding = tiktoken.encoding_for_model(self.model_name)
            t_used = 0
            truncated_messages = []
            truncated_section = ''
            for message in messages:
                if type(message) in [SystemMessage, HumanMessage, AIMessage]:
                    m = type(message)(content='')
                    for token in encoding.encode(message.content):
                        if t_used < context_window_size: 
                            m.content += str(encoding.decode([token]))
                            t_used += 1
                        else:
                            truncated_section += str(encoding.decode([token]))  # Add the truncated part to the variable
                    truncated_messages.append(m)
                else: 
                    logging.error(f"SUPER BAD: Message is of weird type. It's type is {type(message)}. Full content is: {message}")

            log = Log(message="OpenAI LLM.generate()",
                model_name=str(self.model_name), 
                model_temp=float(self.temperature), 
                openai_api_base=str(self.openai_api_base), 
                original_messages=str(messages), 
                truncated_messages=str(truncated_messages), 
                content_that_was_truncated=str(truncated_section), 
                num_tokens_in_original=num_tokens_in_messages, 
                num_tokens_in_truncated=self.get_num_tokens_from_messages(truncated_messages), 
                message_was_truncated=True
                )
            response = log_client.send(log)
            response.raise_for_status()
            return truncated_messages
        else:
            # No truncation
            log = Log(message="OpenAI LLM.generate()",
                original_messages=str(messages),
                model_name=str(self.model_name),
                model_temp=float(self.temperature),
                openai_api_base=str(self.openai_api_base),
                truncated_messages=None, 
                num_tokens_in_original=num_tokens_in_messages, 
                num_tokens_in_truncated=None, 
                message_was_truncated=False
                )
            response = log_client.send(log)
            response.raise_for_status()
        return messages 

    def _generate(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        stream: Optional[bool] = None,
        **kwargs: Any,
    ) -> ChatResult:
        
        messages = self._truncate_messages(messages)
        # ... the rest of the _generate() function
```
