### ISSUE TITLE
Redis from_existing_index does not raise ValueError when index does not exist

### ISSUE THREAD

**Issue by ibrahoss** [langchain-ai/langchain#11409]
### System Info

langchain 0.0.303, python 3.9, redis-py 5.0.1, latest redis stack with RedisSearch module 

### Who can help?

@eyurtsev

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Try to create Redis vector store like this from non existent index_name:
`      
               embeddings = OpenAIEmbeddings()
               vectorstore = Redis.from_existing_index(
                        embeddings,
                        index_name=index_name,
                        schema='schema.yaml',
                        redis_url=REDIS_URL,
                    )
` 
it executes and returns object of Redis type, and logs that index was found. However, of course it fails to query later. 

### Expected behavior

It should raise a ValueError accortding to doc.

**Comment by ibrahoss** [comment]
dose-beta's response did not help. But I managed to fix the issue in my app by dropping the index instead bulk deleting all its keys. It seems that FT.INFO command returns info with empty index. Empty index is hidden in redisinsight causing the confusion. So, I think this can be closed as no issue.

**Comment by Spartee** [comment]
@ibrahoss I'm having trouble following here. Is this solved? Is there a way we can make this better?

**Comment by ibrahoss** [comment]
@Spartee sorry for the confusion, yes my issue was solved, and this issue can be closed as not an issue. it works as expected.

**Comment by Spartee** [comment]
@baskaryan please close
