### ISSUE TITLE
Issue: Custom Redirect URI as parameter in SharePointLoader

### ISSUE THREAD

**Issue by rkritin98** [langchain-ai/langchain#11423]
### Issue you'd like to raise.

I am trying to access documents from SharePoint using Langchain's [SharePointLoader](https://api.python.langchain.com/en/latest/document_loaders/langchain.document_loaders.sharepoint.SharePointLoader.html).

I changed the redirect URI to a local host on this [documentation](https://python.langchain.com/docs/integrations/document_loaders/microsoft_sharepoint). How can I pass the new redirect URI as a parameter to the [SharePointLoader](https://api.python.langchain.com/en/latest/document_loaders/langchain.document_loaders.sharepoint.SharePointLoader.html) function.

**Comment by keenborder786** [comment]
@rkritin98 why do you need to change the redirect URL on the SharepointLoader? Once you have the redirect URL for your application on the Microsoft Identity App, you don't need to specify the redirect URL on your loader. Hopefully, this makes sense.
