### ISSUE TITLE
Bearer token support for self-deployed OpenLLM

### ISSUE THREAD

**Issue by ColinLeverger** [langchain-ai/langchain#11438]
Hello there,

I have deployed an OpenLLM on a managed service that is protected by the use of an auth Bearer token:

```bash
curl -X 'POST' \
  'https://themodel.url/v1/generate' \
  -H "Authorization: Bearer Sh6Kh4[ . . . super long bearer token ]W18UiWuzsz+0r+U"
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "What is the difference between a pigeon",
  "llm_config": {
    "use[ . . . and so on]
    }
  }'
```

Curl works like a charm. 

In LangChain, I try to create my new llm as such:

```python
llm = OpenLLM(server_url="https://themodel.url/v1/generate", temperature=0.2)
```

But I don't know how to include this Bearer token, I even suspect it is impossible... 
**Bot seems to confirm this is impossible as of 5 Oct 2023, as seen in https://github.com/langchain-ai/langchain/discussions/11437** ; this issue would then be a feature request.

Thanks! 
Cheers,
Colin

_Originally posted by @ColinLeverger in https://github.com/langchain-ai/langchain/discussions/11437_

**Comment by ColinLeverger** [comment]
Continuing to debug: it appears that the `openllm_client` is also to be touched for introducing this feature, especially in this file: https://github.com/bentoml/OpenLLM/blob/main/openllm-client/src/openllm_client/benmin/_http.py#L20 

Also, it appears that HTTPS is not supported at this time by openllm but only HTTP.

**Comment by Farhan-Faisal** [comment]
Hi,
We are a group of students from the University of Toronto and are interested in looking into this issue. We will submit a PR and a formatted feature request in the coming couple of weeks after debugging this a little more.
