### ISSUE TITLE
Error while importing LLMChain 

### ISSUE THREAD

**Issue by Hazzerback25** [langchain-ai/langchain#11448]
### Issue you'd like to raise.

When I'm running the code "from langchain.chains import LLMChain", I'm getting the following error: 
'RuntimeError: no validator found for <class 're.Pattern'>, see `arbitrary_types_allowed` in Config'

<img width="887" alt="Screenshot 2023-10-06 at 12 01 49 AM" src="https://github.com/langchain-ai/langchain/assets/85587494/0b171391-bbc6-41f8-b237-17bc99b11b95">
<img width="871" alt="Screenshot 2023-10-06 at 12 01 58 AM" src="https://github.com/langchain-ai/langchain/assets/85587494/592c2688-be0f-4cf4-8e7d-a4a56d7d056c">

**Comment by eyurtsev** [comment]
@Hazzerback25  the exception is from XMLOutputParser, could you check what pydantic version you're using?
