### ISSUE TITLE
Qdrant - Load the saved vector db/store ?

### ISSUE THREAD

**Issue by VpkPrasanna** [langchain-ai/langchain#11471]
### Issue you'd like to raise.

I use Qdrant through langchain  to store vectors.  But I can't find any example in docs where the dataset is searched based on a previously created collection. How to load the data? I found that Pinecone has "from_existing_index" function, which probably does the thing. But Qdrant doesn't have such a function. I created my own solution using qdrant_client, but I would like to use Langchain to simplify the script. How to do it?

**Comment by VpkPrasanna** [comment]
hi 

> _🤖_
> 
> Hello,
> 
> Thank you for your question. Currently, the `Qdrant` class in LangChain does not have a method similar to Pinecone's "from_existing_index" function for loading a previously created collection. However, you can use the `construct_instance` or `aconstruct_instance` class methods of the `Qdrant` class to create a new instance and connect to the existing collection. Here's an example:
> 
> ```python
> from qdrant_client import QdrantClient
> from langchain.vectorstores import Qdrant
> from langchain.embeddings import OpenAIEmbeddings
> 
> embeddings = OpenAIEmbeddings()
> collection_name = "MyExistingCollection"  # replace with your collection name
> 
> qdrant = Qdrant.construct_instance(
>     texts=[],  # no texts to add
>     embedding=embeddings,
>     collection_name=collection_name,
> )
> ```
> 
> In this code, `embeddings` is an instance of the `Embeddings` class that you want to use. If you don't have it, you can create it using the appropriate model. For example, if you're using OpenAI's GPT-3 model, you can do:
> 
> ```python
> from langchain.embeddings import OpenAIEmbeddings
> 
> embeddings = OpenAIEmbeddings()
> ```
> 
> Please note that this will not check if the collection actually exists in the Qdrant server. If the collection does not exist, any operation that requires the collection (like `add_texts`, `similarity_search`, etc.) will fail.
> 
> This approach was derived from the source code of the `Qdrant` class in the LangChain repository [here](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/qdrant.py).
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> ## Sources
> * [Documentation should point out how to retrieve a vectorstore already uploaded in a database](https://github.com/langchain-ai/langchain/issues/3191)
> * [[Q] How to re-use QDrant collection data that are created separatly with non-default vector name?](https://github.com/langchain-ai/langchain/issues/2594)
> * [libs/langchain/langchain/vectorstores/qdrant.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/qdrant.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
@dosu-bot the above mentioned method does not work out for RAG based implementations

**Comment by VpkPrasanna** [comment]
here is it 
`
    from qdrant_client import QdrantClient
`
`
    client = QdrantClient(path=saved_db_path)
        db = Qdrant(
            client=client,
            collection_name=self.collection_name,
            embeddings=embeddings,
        )
`

the above piece of code helps you to load the saved qdrant path

**Comment by karrtikiyer-tw** [comment]
🙏 thanks
