### ISSUE TITLE
Add condition in Prompt based on the retriever

### ISSUE THREAD

**Issue by mrcmoresi** [langchain-ai/langchain#11474]
### Issue you'd like to raise.

Hello, 
I'm trying to change dynamically a prompt, based on the value of the context in a ConversationalRetrievalChain

```
prompt_template = """You are an AI assistant.
Use the following pieces of context to answer the question, in a precise way, at the end. 

Context: {context if context else "some default: I don't have information about it"}

Question: {question}
Helpful Answer :"""
QA_PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

llm = AzureChatOpenAI(
        temperature=0,
        deployment_name="gpt-35-turbo",
    )

memory = ConversationBufferWindowMemory(
    k=1,
    output_key='answer',
    memory_key='chat_history',
    return_messages=True)

retriever = vector.as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": .70})

qa_chain = ConversationalRetrievalChain.from_llm(llm=llm,
                                                memory=memory,
                                                retriever=retriever,
                                                condense_question_prompt=CONDENSE_QUESTION_PROMPT,
                                                combine_docs_chain_kwargs={'prompt': QA_PROMPT},
                                                return_source_documents=True,
                                                verbose=True)
```

The idea is when the retriever gets 0 documents, to have something in the context that push the model to say I don't know and don't make up and answer. I already try by adding in the prompt "if you don't know the answer don't make it up" and didn't work.

Any idea how to add a condition in the template or control the LLM based on the output of the retriever?

**Comment by mrcmoresi** [comment]
@dosu-bot you didn't fully get what i'm trying to do, I don't want to change the question in case there's no document retrieved. What I want to do is, in case the retriever returns 0 documents, I want either send directly as output a phrase like "I don't know about that" or to set the context of the QA_PROMPT to a fix value let's say "I don't have that information, could please rephrase your question or ask a different topic".

**Comment by sudranga** [comment]
@mrcmoresi Is this really about adding "extra" info to the prompt or do you just want the chain to return a fixed message if no relevant documents are found?
I think you are looking for the latter. If so, you could look at the returned source documents and 'rewrite' the response (but then you may have to update memory of the chain). 
I think it would be best to expose an option in the ConversationalRetrievalChain to return a fixed user-defined message if no relevant documents are found. Seems like it would be a fairly common request and one that should be supported in a straightforward manner. I can originate a PR .

**Comment by mrcmoresi** [comment]
hi @sudranga, thanks for your answer.
yes, exactly what I want is to return a fixed message when relevant documents are not found. 

I think the option you mentioned is the best alternative, just to expose an option in the ConversationalRetrievalChain. 

currently what I'm doing is, I override the _get_docs method of the ConversationalRetrievalChain so when there is not document retrieved, I return a "fixed" document, saying "not document retrieved, please ask for clarification". which will be the context of the LLM to generate the answer. This is consuming a call to the LLM which is unnecessary if an answer would be returned directly.

**Comment by sudranga** [comment]
Opened a PR: https://github.com/langchain-ai/langchain/pull/11519

**Comment by pai4451** [comment]
Hi @mrcmoresi, did you find any solution?

**Comment by mrcmoresi** [comment]
Hi @pai4451 I used the new feature from the PR https://github.com/langchain-ai/langchain/pull/11519 but I'm not using async calls.

**Comment by sudranga** [comment]
Looks like i missed it. Will add it.

**Comment by sudranga** [comment]
Done. https://github.com/langchain-ai/langchain/pull/13297

**Comment by pai4451** [comment]
@sudranga Thanks for implementing the async version. This is what I need.
