### ISSUE TITLE
Redis Vectorestore.add_documents() should use embed_documents() instead of  embed_query()

### ISSUE THREAD

**Issue by benchello** [langchain-ai/langchain#11496]
### Feature request

The Redis Vectorstore `add_documents()` method calls `add_texts()` which embeds documents one by one like:
```
embedding = (
                embeddings[i] if embeddings else self._embeddings.embed_query(text)
            )
```
The `add_documents()` method would seem to imply that it is a good way to jointly embed and upload a larger list of documents, but using an API call for each document as above is slow and prone to run into rate limits. 

Redis `add_documents()` could pass a kwarg `from_documents=True`to `add_texts()` which would change embedding to 

```
embedding = (
                embeddings[i] if embeddings else self._embeddings.embed_documents(documents)
            )
```

### Motivation

This would simplify the overall use of the Redis Vectorstore and would be more inline with how the example documents imply the add_documents() method should be used. Currently `add_documents()` is not suitable for something like a csv or a long list of smaller documents unless it is used like:
```
add_documents(
        documents=split_documents,
        embeddings=embedder.embed_documents(texts),
    )
```

### Your contribution

I could create a PR for this issue if it makes sense!

**Comment by Spartee** [comment]
@bholagabbar this can be closed
