### ISSUE TITLE
Add support for google scholar querying with serpapi

### ISSUE THREAD

**Issue by HamJaw1432** [langchain-ai/langchain#11505]
### Feature request

We propose the addition of Google Scholar querying with the serpapi, as google Scholar is a prominent platform for accessing academic and scholarly articles.

### Motivation

Google scholar is a crucial resource for researchers, students, and professionals in various fields. Integrating Google Scholar querying with serpapi would provide users with the ability to programmatically retrieve search results from Google Scholar, giving the llms more better/more reliable information to work with.

### Your contribution

We intend to submit a pull request for this issue at some point in November.

**Comment by keenborder786** [comment]
@HamJaw1432 I have started working on this feature as I also this, please see #11513

**Comment by HamJaw1432** [comment]
Hey @keenborder786 this looks good to me, it seems that you are done with the code needed (i think), My team and I were going to do this for a school project but we will work on a new issue. Your code is a good reference for us so thank you!

**Comment by ilyazub** [comment]
Looks like this was resolved in #11513.
