### ISSUE TITLE
The ElasticsearchStore implementation is not correct.

### ISSUE THREAD

**Issue by via-red** [langchain-ai/langchain#11539]
### System Info

langchain==0.0.310

### Who can help?

@joemcelroy ：It seems that the method _select_relevance_score_fn was forgotten to be implemented in vectorstores-elasticsearch.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

elastic_vector_search = ElasticsearchStore(
    index_name='langchain-demo',
    es_connection=es,
    embedding=embedding,
)
    
retriever = elastic_vector_search.as_retriever(
        search_type="similarity_score_threshold",
        search_kwargs={'score_threshold': 0.8})

error log：
line 268, in similarity_search_with_relevance_scores
    docs_and_similarities = self._similarity_search_with_relevance_scores(
  File "/usr/local/lib/python3.10/site-packages/langchain/schema/vectorstore.py", line 242, in _similarity_search_with_relevance_scores
    relevance_score_fn = self._select_relevance_score_fn()
  File "/usr/local/lib/python3.10/site-packages/langchain/schema/vectorstore.py", line 211, in _select_relevance_score_fn
    raise NotImplementedError

### Expected behavior

I hope to implement the method and submit the changes as soon as possible. Thank you for your understanding.

**Comment by via-red** [comment]
code：
elastic_vector_search = ElasticsearchStore(
index_name='langchain-demo',
es_connection=es,
embedding=embedding,
)

retriever = elastic_vector_search.as_retriever(
search_type="similarity_score_threshold",
search_kwargs={'score_threshold': 0.8})
documents = retriever.get_relevant_documents(query=keyword)//The place where the error occurred.

**Comment by joemcelroy** [comment]
thanks! Happy to review the PR :). Should be relatively straightforward with `min_score`.

The only gotcha AFAIK is hybrid search which doesn't have a score. I will find out the best way to handle this.

**Comment by via-red** [comment]
The following document is a method I found to calculate mixed scores, and I hope it can provide you with some help @joemcelroy ：
[_searcher.py](https://github.com/castorini/pyserini/blob/e371ed3661e90db6b797290493d973cb6c089c43/pyserini/search/hybrid/_searcher.py)

**Comment by Tjoker-cell** [comment]
@joemcelroy  Is there a rough timeframe for the fix of this issue?  I hope it can be fixed as soon as possible.

**Comment by joemcelroy** [comment]
Im happy to accept a PR for this and review. The first step is to do it and throw an error when hybrid is True (which should be simple) then we can figure out how we achieve this with hybrid. 

min-score is a difficult one because its hard to establish what min-score should actually be before request. Would love your thoughts on its usefulness.

**Comment by younes-io** [comment]
I'm using `OpenSearchVectorSearch` and I come across the same error unfortunately.. I thought this is already in place, and with deadlines, I don't know how to work around this issue... :/

**Comment by ugm2** [comment]
I am also experiencing the same problem with `ElasticsearchStore`, but I don't fully understand `_select_relevance_score_fn` to be able to create a PR. Is there an alternative to get scores with the documents?

**Comment by natnael1455** [comment]
I am using langchain 0.1.0 still the issue is there for ElasticsearchStore. is there a work around
