### ISSUE TITLE
Support max_marginal_relevance_search for ElasticSearchStore

### ISSUE THREAD

**Issue by izzabudaka** [langchain-ai/langchain#11547]
### System Info

max_marginal_relevance_search is mentioned in the ElasticSearchStore python documentation, but when calling the referenced API with langchain 0.0.310 and Python 3.9 I receive a NotImplementedError.

https://api.python.langchain.com/en/latest/vectorstores/langchain.vectorstores.elasticsearch.ElasticsearchStore.html#langchain.vectorstores.elasticsearch.ElasticsearchStore.max_marginal_relevance_search

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
vector_store = ElasticsearchStore(
    embedding=OpenAIEmbeddings(),
    index_name="{INDEX_NAME}",
    es_cloud_id="{CLOUD_ID}",
    es_user="{USER}",
    es_password="{PASSWORD}"
)

pages = vector_store.max_marginal_relevance_search("test query")
```

### Expected behavior

max_marginal_relevance_search functions as per the documentation.

**Comment by sudranga** [comment]
PR in progress at https://github.com/langchain-ai/langchain/pull/11633
