### ISSUE TITLE
Issue: Add Examples of implementing Tree of Thoughts using Langchain

### ISSUE THREAD

**Issue by rajveer43** [langchain-ai/langchain#11546]
### Issue you'd like to raise.

https://arxiv.org/abs/2305.10601

### Suggestion:

https://arxiv.org/abs/2305.10601

**Comment by rajveer43** [comment]
yes

**Comment by baskaryan** [comment]
example here! https://github.com/langchain-ai/langchain/blob/master/cookbook/tree_of_thought.ipynb
