### ISSUE TITLE
Issue: Inference Client in Lang chain

### ISSUE THREAD

**Issue by Nuna7** [langchain-ai/langchain#11545]
### Issue you'd like to raise.

Hi, I am trying to use Hugging Face model for langchain. However, I got this error :

"FutureWarning: '__init__' (from 'huggingface_hub.inference_api') is deprecated and will be removed from version '0.19.0'. `InferenceApi` client is deprecated in favor of the more feature-complete `InferenceClient`. Check out this guide to learn how to convert your script to use it: https://huggingface.co/docs/huggingface_hub/guides/inference#legacy-inferenceapi-client."

This is my code :

`

  os.environ["HUGGINGFACEHUB_API_TOKEN"] = huggingFace_api_key
  
  llm_repo_id = "google/flan-t5-xxl"
  
  def generate_pet_name(animal_type,pet_color):
      llm = HuggingFaceHub(
      repo_id=llm_repo_id, model_kwargs={"temperature": 0.5})

      prompt_template = PromptTemplate(
          input_variables = ['animal_type','animal_color'],
          template = "I have an {animal_type} with {animal_color} in color. Suggest me five name which sound" 
                                                      + "appropriate with the color for my {animal_type}")
  
      name_chain = LLMChain(llm=llm,prompt=prompt_template,output_key="pet_name")
  
      response = name_chain({'animal_type':animal_type,'animal_color':pet_color})
      return response

`

How do I get rid of this warning.

**Comment by Nuna7** [comment]
After using your code :
client = InferenceClient(
TypeError: __init__() got an unexpected keyword argument 'endpoint'

**Comment by anupj** [comment]
So I believe this error happens because the [python code](https://api.python.langchain.com/en/latest/_modules/langchain/llms/huggingface_hub.html#HuggingFaceHub) for HuggingFaceHub llm still uses the about-to-be deprecated `InferenceApi`.

`from huggingface_hub.inference_api import InferenceApi` 

To fix this properly would require updating the `langchain.llms.huggingface_hub` module to use the new `InferenceClient`.

**Comment by anupj** [comment]
This [PR](https://github.com/langchain-ai/langchain/pull/11469) should fix this issue. I'd say it requires urgent attention so that we can start connecting to HuggingFace LLMs again.
