### ISSUE TITLE
Support for case insensitive query search something like "$regex" instead of "$contains"

### ISSUE THREAD

**Issue by meet1919** [langchain-ai/langchain#11571]
### Issue you'd like to raise.

To get documents from collections (vector db) there is a method:

```python
class Collection(BaseModel):
    name: str
    id: UUID
    metadata: Optional[CollectionMetadata] = None
    _client: "API" = PrivateAttr()
    _embedding_function: Optional[EmbeddingFunction] = PrivateAttr()

    def __init__(
        self,
        client: "API",
        name: str,
        id: UUID,
        embedding_function: Optional[EmbeddingFunction] = ef.DefaultEmbeddingFunction(),
        metadata: Optional[CollectionMetadata] = None,
    ):
        self._client = client
        self._embedding_function = embedding_function
        super().__init__(name=name, metadata=metadata, id=id)

    '''
    '''
    def get(
            self,
            ids: Optional[OneOrMany[ID]] = None,
            where: Optional[Where] = None,
            limit: Optional[int] = None,
            offset: Optional[int] = None,
            where_document: Optional[WhereDocument] = None,
            include: Include = ["metadatas", "documents"],
        ) -> GetResult:
            """Get embeddings and their associate data from the data store. If no ids or where filter is provided returns
            all embeddings up to limit starting at offset.
    
            Args:
                ids: The ids of the embeddings to get. Optional.
                where: A Where type dict used to filter results by. E.g. `{"$and": ["color" : "red", "price": {"$gte": 4.20}]}`. Optional.
                limit: The number of documents to return. Optional.
                offset: The offset to start returning results from. Useful for paging results with limit. Optional.
                where_document: A WhereDocument type dict used to filter by the documents. E.g. `{$contains: {"text": "hello"}}`. Optional.
                include: A list of what to include in the results. Can contain `"embeddings"`, `"metadatas"`, `"documents"`. Ids are always included. Defaults to `["metadatas", "documents"]`. Optional.
    
            Returns:
                GetResult: A GetResult object containing the results.
    
            """
            where = validate_where(where) if where else None
            where_document = (
                validate_where_document(where_document) if where_document else None
            )
            ids = validate_ids(maybe_cast_one_to_many(ids)) if ids else None
            include = validate_include(include, allow_distances=False)
            return self._client._get(
                self.id,
                ids,
                where,
                None,
                limit,
                offset,
                where_document=where_document,
                include=include,
            )
```

To query documents by searching for a particular term in the document `where_document = {"$contains": "langchain"}` can be passed to the `get()` method. This value for the key/operator `$contains` is case sensitive. How to search for keywords irrespective of case?

### Suggestion:

I want to extract entities from a sentence and pass it get documents from the chromadb that contains that words. But this entities need to be case sensitive. If the LLM outputs a different case like for example, the document contains the keyword: "Langchain", but asking llm to extract the entity from the sentence it isnt always sure that it will generate "Langchain", it can output: "langchain". This can be handled if the first letter of the entities generated is capitalized. But this may not work for keywords like OpenCV.

**Comment by meet1919** [comment]
@dosu-bot About the feedback you asked:
To better understand your needs and to propose a suitable solution, could you please provide more details about your use case? Specifically, it would be helpful to know:

1. Are you looking for a global setting to make all $contains queries case-insensitive, or do you need to switch between case-sensitive and case-insensitive searches?
2. Are there any specific performance considerations we should be aware of for your use case? For example, would you be okay with a potential trade-off between search speed and case-insensitivity?
3. Could you provide some examples of the types of queries you're trying to perform? This will help us understand the complexity and variety of the searches you need to support.


I want switch between $regex and $contains if there is a trade-off in performance when using $regex. If there is no compromise in the search speed $contains can search for all the case-insensitive queries by changing global settings.

Types of Queries can be, "OpenCV", "NumPy", "FedEx", "iPhone", "WordPad", "JavaScript", "LinkedIn", "WordPress", "YouTube", etc.

**Comment by meet1919** [comment]
@dosu-bot for the questions you asked as below:

```
Thanks for reaching out with your question. To better assist you, I need a bit more information about your current setup and usage of the LangChain framework.

1. Could you please provide more details about the data structure you're working with? Specifically, what are the fields in your documents and what types of data do they contain?

2. Are you currently using any specific indexing or search optimization techniques in your application?

3. Could you provide an example of how you're currently using the $contains operator in your get() method calls?

4. Are there any constraints or requirements that we should be aware of when considering modifications to the get() method or the framework?

The more context you can provide, the better I can assist you in finding a solution that fits your needs.
```
Answers:
1. Document will contain text data, so $contains will search for words. 
2. No I am not using anny specific indexing or search optimization technique. 
3. Currently I am using `get()` method as follow: `vector_store.get(where_document={"$contains": "langchain"}))`
4. No there are no constrains. Just add $regex or make $contains case-insensitive.

**Comment by meet1919** [comment]
@dosu-bot I am using Chromadb, Redis is irrelevant for me.

**Comment by meet1919** [comment]
@dosu-bot
1. Name: langchain
Version: 0.0.305

2. Name: chromadb
Version: 0.4.6

3. No other library in conjunction with Langchain and Chromadb
4. There is no such specific document size, total number of documents and frequency of queries. You can assume the maximum values possible.

**Comment by meet1919** [comment]
@dosu-bot you know what, what I want to do is very simple, but you keep on asking many questions. I am done with it.

**Comment by devstein** [comment]
Hey @meet1919 Sorry Dosu couldn't help you more. If Dosu get "stuck" asking clarifying questions, it means they aren't able to find anything with the repository to concretely answer your question. 

We're working on improving this! As for your question, `WhereDocument` type comes from ChromaD, so I'd go their Discord or [Github](https://github.com/chroma-core/chroma/issues) to find an answer.

Let me know if you have any other ideas on ways we can make Dosu more useful!

**Comment by devstein** [comment]
@meet1919 I'm not familiar with all VectorDBs, but I use Supabase/Postgres with pgvector, which you can definitely do insensitive queries using SQL.

> About Dosu-bot, does it search with internet and bringing the information into its context while generating answer? Along with information from the source code in the context too. Follow-up questions are asked properly but is there a way to converge the planning process rather than keeping on asking questions?

Not yet. Internet information can be noisy and not always relevant to the issue, which is why we haven't incorporated it yet.
For converging the planning process, yes this is actively being worked on so stay tuned.
