### ISSUE TITLE
similarity_search_with_relevance_scores is not working properly with Pinecone

### ISSUE THREAD

**Issue by Vickywwww** [langchain-ai/langchain#11587]
### System Info

Langchain Version: 0.0.311
Python: 3.10.9

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I loaded the my vector store from **pinecone** and try to find top-3 most similar documents with the relevance score
```
vectorstore = Pinecone(index, embed.embed_query, text_field)
answers = vectorstore.similarity_search_with_score(query, 3)
for item in answers:
    print(item[1]) # print out score
```
By running above code, I can get relevance score for those 3 documents:
```
0.851780415
0.851505935
0.850369573
```
It looks as expected

But when I try to use `similarity_search_with_relevance_scores` to find out similar docs:
```
answers= vectorstore.similarity_search_with_relevance_scores(query, score_threshold=0.8)
```
From my understanding it should return me at least 3 docs since we do have docs similar higher than 0.85, but I got warning `No relevant docs were retrieved using the relevance score threshold 0.8` with an empty return

And I tried vectorstore retriever as well and got same warning and empty return:
```
retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.8}
)
answer = retriever.get_relevant_documents(query)
print(answer)
```
Did I use the score function incorrectly ? If not, is there any other ways to query with score_threshold? 
Thanks

### Expected behavior

When using 
```
answers= vectorstore.similarity_search_with_relevance_scores(query, score_threshold=0.8)
```
or 
```
retriever = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"score_threshold": 0.8}
)
answer = retriever.get_relevant_documents(query)
print(answer)
```
It should return me few of doc that have >= 0.8 similarity.

**Comment by Vickywwww** [comment]
Thanks for explaining that, it makes sense to me, but as a python beginner, can you give me more details on how to do it? Like: should I import Scann, override provide the `relevance_score_fn` ?

**Comment by sudranga** [comment]
Something like this should work: 
  
class PineconeCustom(Pinecone):
    def _cosine_relevance_score_fn(distance: float) -> float:
        """Normalize the distance to a score on a scale [0, 1]."""
        return (1.0 + distance)/2

vectorstore = PineconeCustom(index, embed.embed_query, text_field)
....
