### ISSUE TITLE
AzureOpenAI doesn't expose parameter to set custom HTTP headers.

### ISSUE THREAD

**Issue by maciej-skorupka** [langchain-ai/langchain#11593]
### Feature request

Hey hi hello :)

Some organizations expose Azure OpenAI endpoints via some proxies that need additional HTTP headers. Currently AzureOpenAI class doesn't expose (at least I wasn't able to find one) a capability to set this. Similarly to what is possible in OpenAIEmbeddings ([https://api.python.langchain.com/en/latest/embeddings/langchain.embeddings.openai.OpenAIEmbeddings.html#langchain.embeddings.openai.OpenAIEmbeddings.headers](https://api.python.langchain.com/en/latest/embeddings/langchain.embeddings.openai.OpenAIEmbeddings.html#langchain.embeddings.openai.OpenAIEmbeddings.headers)). Something similar was already discussed ([https://github.com/langchain-ai/langchain/issues/2120](https://github.com/langchain-ai/langchain/issues/2120)) and embeddings have that already solved. It would be great to have that also for AzureOpenAI class.

### Motivation

I need this to get via proxy that needs additional HTTP headers.

### Your contribution

I don't think I can contribute to this.

**Comment by SDonkelaarGDD** [comment]
This is an useful feature. I have time to contribute on this. 

Can someone assign me this issue?

**Comment by maiqingqiang** [comment]
use model_kwargs https://github.com/langchain-ai/langchain/pull/11756#issuecomment-1761201933
