### ISSUE TITLE
Return ids for the document returned from the Similarity Search.

### ISSUE THREAD

**Issue by meet1919** [langchain-ai/langchain#11592]
### Feature request

I want to get the ids of the document returned when performing `similarity_search()` or `similarity_search_with_score()`. The id should be present in the metadata = {"id": id}

  

### Motivation

Want to update the metadata of the documents that are returned in the similarity search. This update can only be done if the the documents returned has the id in its metadata. When adding the documents to the vectordb, I am not adding the ids, as they are automatically generated if not passed. 

### Your contribution

No contributions but below is the changes that can be made:

```
def _results_to_docs_and_scores(results: Any) -> List[Tuple[Document, float]]:
    return [
        # TODO: Chroma can do batch querying,
        # we shouldn't hard code to the 1st result
        (Document(page_content=result[0], metadata=(result[1] | {'id': result[3]}) or {}), result[2])
        for result in zip(
            results["documents"][0],
            results["metadatas"][0],
            results["distances"][0],
            results["ids"][0]
        )
    ]

```

**Comment by FelixOpolka** [comment]
This would indeed be very useful!
