### ISSUE TITLE
How to debug vercel failures?

### ISSUE THREAD

**Issue by sudranga** [langchain-ai/langchain#11635]
### Issue you'd like to raise.

I submitted a PR. Vercel 'deployment' failed. There is no other info. I dont seem to have access for this PR on vercel. How do i debug this?

**Comment by sudranga** [comment]
@dosu-beta: What do you say?

**Comment by sudranga** [comment]
1. When i click on [Inspect](https://vercel.com/langchain/langchain/2R3PURPCTmpnivLfPxZ7YNYrFLSA), it says 404. So, i have no information as to what fails.
2. No
3. There are no new dependencies
4. No
5. 310

**Comment by robcaulk** [comment]
@sudranga how did you solve this? We are running in to the same issue in another PR https://github.com/langchain-ai/langchain/pull/21581

**Comment by sudranga** [comment]
@robcaulk Someone else resolved it for me
