### ISSUE TITLE
Using hash for indexing prompts SQLAlchemyCache

### ISSUE THREAD

**Issue by markowanga** [langchain-ai/langchain#11655]
### Feature request

I want to make similar implementation of SQLAlchemyCache that can index prompts by md5 hash.

### Motivation

Postgres have limitation for 2704 bytes on index. Processing on simple index can be faster.

### Your contribution

I have prepared cache implementation – I will add it in contributing PR

**Comment by audvin** [comment]
Looking forward to this!

**Comment by markowanga** [comment]
I forgot to close issue – It's already released
