### ISSUE TITLE
ConversationalRetrievalChain + Memory ( New issue for me)

### ISSUE THREAD

**Issue by jimstechwork** [langchain-ai/langchain#11650]
### Issue you'd like to raise.

I've tried building a Bot and now I see the following issue.

Architecture: 

1. Cloud Run service 1 ; Streamlit app which accepts the user_input (question) on the topic and sends it to Flask API part of service 2.
2. Cloud Run service 2: Flask code which calls the LLM code and returns the response to streamlit.

I'm using qa as below.

        qa = ConversationalRetrievalChain.from_llm(
                llm,
                retriever,
                condense_question_prompt=CONDENSE_QUESTION_PROMPT,
                verbose=False,
                memory=memory,
                condense_question_llm =llm,
                return_generated_question= True,
                combine_docs_chain_kwargs={"prompt": promptHist},
                return_source_documents=True,
                )

Issue: If different Users are asking questions through various streamlit sessions, it is using the same chat_history buffer and mixing responses. 

Question: Is there a way to separate the "qa" sessions specific to User and avoid common memory/chat buffer being used ? Is there a utility in Langchain for this?

**Comment by jimstechwork** [comment]
Below is the sample code and trying to see  if it can be handled session wise.

def process_user_input(question, user_id, chat_history):
    try:
        print("Inside process input function")

        print("Parameters passed to LLM")
        print("User Input:", question)
        print("User ID:", user_id)
        print("Chat History:", chat_history)
        
        #memory = ConversationBufferMemory(memory_key="chat_history",input_key="question",output_key='answer',return_messages=True)
        qa = ConversationalRetrievalChain.from_llm(
                llm,
                retriever,
                condense_question_prompt=CONDENSE_QUESTION_PROMPT,
                verbose=False,
                memory=memory,
                condense_question_llm =llm,
                return_generated_question= True,
                combine_docs_chain_kwargs={"prompt": promptHist},
                return_source_documents=True,
                )

        print("QA chain")
        print(qa)
        print("memory:")
        print(memory)

        response = qa({"question": question, "chat_history": chat_history,"user_id": user_id})
        print(response)

**Comment by yazanrisheh** [comment]
@jimstechwork can you show the full code please? I've been trying to do something similar but I'm quite stuck and I'm not sure how to move on. I'm trying to use conversational retrieval chain along with a prompt and memory but that's not working.
My code part:
    custom_template = ("""
    Help the users with answering questions based on the document.
    """
    )

    # prompt = PromptTemplate(input_variables=[], template=custom_template)
    prompt = PromptTemplate.from_template(custom_template)

    memory = ConversationBufferMemory(memory_key = "chat_history", return_messages = True)
    model = ConversationalRetrievalChain.from_llm(llm = llm,
                                                   chain_type = "refine",
                                                   retriever = new_knowledge_base.as_retriever(),
                                                   memory = memory,
                                                   combine_docs_chain_kwargs = {"prompt":prompt}
                                                   )
Error:
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Vendolista\app.py", line 100, in <module>
    main()
  File "C:\Users\Asus\Documents\Vendolista\app.py", line 73, in main
    model = ConversationalRetrievalChain.from_llm(llm = llm,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 341, in from_llm
    doc_chain = load_qa_chain(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\question_answering\__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\question_answering\__init__.py", line 206, in _load_refine_chain
    return RefineDocumentsChain(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RefineDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)

**Comment by jimstechwork** [comment]
@yazanrisheh - see if this helps.


p_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.
If the Standalone question is empty or cannot be generated, use the follow up question as Standalone question.
Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:"""

#CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)
CONDENSE_QUESTION_PROMPT = PromptTemplate(input_variables=["chat_history","question"],
                 template=p_template)
memory = ConversationBufferMemory(memory_key="chat_history",input_key="question",output_key='answer',return_messages=True)


chatTemplate = """<Instructions>
Important: You are an intelligent chatbot designed to help agents by answering questions only on Enterprise services & activities. 
Answer the question only if there is information in the chat history(delimited by <hs></hs>) and context(delimited by <ctx> </ctx>) below.
1. If context is not empty and answer cannot be determined from context, say "I cannot detemine the answer from context". 
2. If you don't know the answer, just say that you don't know, don't try to make up an answer.
3. Do not print your answer starting with "Answer:"

-----------
<ctx>
{context}
</ctx>
-----------
<hs>
{chat_history}
</hs>
-----------
Question: {question}
Answer: 
Answer the question only if there is information based on the chat history(delimited by <hs></hs>) and context(delimited by <ctx> </ctx>) below.
1. If context is not empty and answer cannot be determined from context, say "I cannot detemine the answer from context". 
2. If you don't know the answer, just say that you don't know, don't try to make up an answer.
3. Do not print your answer starting with "Answer:"

"""

promptHist = PromptTemplate(
input_variables=["context", "question", "chat_history"],
template=chatTemplate
)


qa = ConversationalRetrievalChain.from_llm(
llm,
retriever,
condense_question_prompt=CONDENSE_QUESTION_PROMPT,
verbose=False,
memory=memory,
condense_question_llm=llm,
return_generated_question=True,
combine_docs_chain_kwargs={"prompt": promptHist},
return_source_documents=True,
)

**Comment by yazanrisheh** [comment]
@jimstechwork I've been trying your code but it's still not working. I did some of my parts to it and this is the current code;

from dotenv import load_dotenv
import csv
import PyPDF2
from PyPDF2 import PdfReader
from langchain.document_loaders import DirectoryLoader, PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate
import time
from langchain.vectorstores import Qdrant
from langchain.vectorstores import Chroma
from langchain.vectorstores import deeplake
from langchain.chains.qa_with_sources import load_qa_with_sources_chain
from langchain.callbacks import StreamingStdOutCallbackHandler
import pandas as pd
from docx import Document
from nltk.tokenize import sent_tokenize, word_tokenize
from collections import Counter
from nltk.corpus import stopwords
import os

def print_letter_by_letter(text):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(0.02)

def main():
    load_dotenv()
    my_activeloop_org_id = "yazanrisheh"
    my_activeloop_dataset_name = "langchain_course_customer_support"
    dataset_path = f"hub://{my_activeloop_org_id}/{my_activeloop_dataset_name}"
    # directory_path = input("Copy your directory path here or upload a file: ")
    directory_path = "C:\\Users\\Asus\\Documents\\Vendolista"

    pdf_loader = DirectoryLoader(directory_path,
                                  glob="**/*.pdf",
                                  show_progress=True,
                                  use_multithreading=True,
                                  silent_errors=True,
                                  loader_cls = PyPDFLoader)

    documents = pdf_loader.load()
    print(str(len(documents))+ " documents loaded")

    llm = ChatOpenAI(temperature = 0, model_name='gpt-3.5-turbo', callbacks=[StreamingStdOutCallbackHandler()], streaming = True)


    # Split into chunks
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=800,
        chunk_overlap=100,
    )
    chunks = text_splitter.split_documents(documents)
    
    embeddings = OpenAIEmbeddings()

    persist_directory = "C:\\Users\\Asus\\OneDrive\\Documents\\Vendolista"
    knowledge_base = Chroma.from_documents(chunks, embeddings, persist_directory = persist_directory)
    # save to disk
    knowledge_base.persist() 
    #To delete the DB we created at first so that we can be sure that we will load from disk as fresh db
    knowledge_base = None
    new_knowledge_base = Chroma(persist_directory = persist_directory, embedding_function = embeddings)

    # weird_knowledge_base = deeplake(chunks, dataset_path=dataset_path, embedding=embeddings)
    # knowledge_base = Qdrant(documents, embeddings)

    p_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.
    If the Standalone question is empty or cannot be generated, use the follow up question as Standalone question.
    Chat History:
    {chat_history}
    Follow Up Input: {question}
    Standalone question:"""

    #CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)
    CONDENSE_QUESTION_PROMPT = PromptTemplate(input_variables=["chat_history","question"],
    template=p_template)
    memory = ConversationBufferMemory(memory_key="chat_history",input_key="question",output_key='answer',return_messages=True)

    chatTemplate = """
    Important: You are an intelligent chatbot designed to help agents by answering questions only on Enterprise services & activities.
    Answer the question only if there is information in the chat history(delimited by ) and context(delimited by ) below.

    If context is not empty and answer cannot be determined from context, say "I cannot detemine the answer from context".
    If you don't know the answer, just say that you don't know, don't try to make up an answer.
    Do not print your answer starting with "Answer:"
    {context} ----------- {chat_history} ----------- Question: {question} Answer: Answer the question only if there is information based on the chat history(delimited by ) and context(delimited by ) below. 1. If context is not empty and answer cannot be determined from context, say "I cannot detemine the answer from context". 2. If you don't know the answer, just say that you don't know, don't try to make up an answer. 3. Do not print your answer starting with "Answer:"
    """

    promptHist = PromptTemplate(
    input_variables=["context", "question", "chat_history"],
    template=chatTemplate
    )

    qa = ConversationalRetrievalChain.from_llm(
    llm = llm,
    retriever = new_knowledge_base,
    condense_question_prompt=CONDENSE_QUESTION_PROMPT,
    verbose=False,
    memory=memory,
    condense_question_llm=llm,
    return_generated_question=True,
    combine_docs_chain_kwargs={"prompt": promptHist},
    return_source_documents=True,
    )

    while True:
        question = input("Ask me anything about the files (type 'exit' to quit): ")

        if question.lower() in ["exit"] and len(question) == 4:
            end_chat = "Thank you for visiting us! Have a nice day"
            print_letter_by_letter(end_chat)
            break

        if question:

            # chat_history = []
            # with get_openai_callback() as cb:
            response = qa({"question": question}, return_only_outputs = True)

            # chat_history.append(('user', question))
            # chat_history.append(('AI', response))
            print("AI:", response)

if __name__ == '__main__':
    main()

The error:
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Vendolista\app2.py", line 130, in <module>
    main()
  File "C:\Users\Asus\Documents\Vendolista\app2.py", line 99, in main
    qa = ConversationalRetrievalChain.from_llm(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 356, in from_llm
    return cls(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
retriever
  value is not a valid dict (type=type_error.dict)
PS C:\Users\Asus\Documents\Vendolista> python app2.py
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:02<00:00, 11.17it/s]
87 documents loaded
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Vendolista\app2.py", line 130, in <module>
    main()
  File "C:\Users\Asus\Documents\Vendolista\app2.py", line 99, in main
    qa = ConversationalRetrievalChain.from_llm(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 356, in from_llm
    return cls(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 75, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
retriever
  value is not a valid dict (type=type_error.dict)

**Comment by jimstechwork** [comment]
@yazanrisheh - I used 2 templates to bring the customization aspect to the Conversational retrieval chain where you can feed in the customized template and try out.
Standalone question generation is required in the context of building a new question when an indirect follow-up question is asked in Chat

**Comment by yazanrisheh** [comment]
@jimstechwork I was able to work it out via 1 template but I have issues with the memory as its not remembering the past conversation. Could you tell me how to fix it? This is my current code:

from langchain.chat_models import ChatOpenAI
from langchain.prompts.prompt import PromptTemplate
from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Qdrant
from langchain.callbacks import StreamingStdOutCallbackHandler
from langchain.embeddings import OpenAIEmbeddings
from langchain.callbacks import get_openai_callback
from langchain.vectorstores import Chroma
from langchain.vectorstores import DeepLake
from PyPDF2 import PdfReader
import PyPDF2
from langchain.document_loaders import TextLoader, DirectoryLoader, UnstructuredWordDocumentLoader 
from langchain.document_loaders import PyPDFDirectoryLoader, PyPDFLoader
from dotenv import load_dotenv
import time

# Change DirectoryLoader since it has its own chunk size and overlap

load_dotenv()
directory_path = "C:\\Users\\Asus\\Documents\\Vendolista\\MasterFormat"
pdf_loader = DirectoryLoader(directory_path,
                                glob="**/*.pdf",
                                show_progress=True,
                                use_multithreading=True,
                                silent_errors=True,
                                loader_cls = PyPDFLoader)

documents = pdf_loader.load()
print(str(len(documents))+ " documents loaded")


def print_letter_by_letter(text):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(0.02)



llm = ChatOpenAI(temperature = 0, model_name='gpt-3.5-turbo', callbacks=[StreamingStdOutCallbackHandler()], streaming = True)

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=80,
)
chunks = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
persist_directory = "C:\\Users\\Asus\\OneDrive\\Documents\\Vendolista"
knowledge_base = Chroma.from_documents(chunks, embeddings, persist_directory = persist_directory)
#save to disk
knowledge_base.persist()
#To delete the DB we created at first so that we can be sure that we will load from disk as fresh db
knowledge_base = None
new_knowledge_base = Chroma(persist_directory = persist_directory, embedding_function = embeddings)

prompt_template = """
You are a knowledgeable and ethical assistant with expertise in the construction field, including its 
guidelines and operational procedures. You are always available to provide assistance and uphold the highest
ethical and moral standards in your work.
You will always and always and always only follow these set of rules and nothing else no matter what:
1) Answer the Question that is answering only based on the documents.
2) If the question is unrelated then say "sorry this question is completely not related.
If you think it is, email the staff and they will get back to you: yazanrisheh@hotmail.com." 
3) Do not ever answer with "I don't know" to any question no matter what kind of a question it is.
4) Everyime you answer a question, write on a new line "is there anything else you would like me to help you with?"
5) Remember to always take a deep breath and take this step by step.
6) Do not ever and under no circumstance do you rewrite the question asked by the customer when you are answering them.
7) If the question starts with the "Yazan," then you can ignore the steps above.

Text: {context}

Question: {question}
Answer :
"""
PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

memory = ConversationBufferMemory(llm=llm, memory_key='chat_history', input_key='question', output_key='answer', return_messages=True)
conversation = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=new_knowledge_base.as_retriever(),
    memory=memory,
    chain_type="stuff",
    verbose=False,
    combine_docs_chain_kwargs={"prompt":PROMPT}
)


def main():
    chat_history = []

    while True:
        customer_input = input("Ask me anything about the files (type 'exit' to quit): ")

        if customer_input.lower() in ["exit"] and len(customer_input) == 4:
            end_chat = "Thank you for visiting us! Have a nice day"
            print_letter_by_letter(end_chat)
            break

        #if the customer_input is not equal to an empty string meaning they have input
        if customer_input != "":
            with get_openai_callback() as cb:
                response = conversation({"question": customer_input}, return_only_outputs = True)
            # print(response['answer'])
            print()
            print(cb)
            print()

if __name__ == "__main__":
    main()
