### ISSUE TITLE
Prompt invalid with ConversationalRetrievalChain

### ISSUE THREAD

**Issue by yazanrisheh** [langchain-ai/langchain#11656]
I am trying to use a prompt with my chain but I am getting an error which I'm not sure how to solve. Also, I was wondering is it possible to use a constitutional principle to apply it to the ConversationalRetrievalChain? If so, can someone guide me on how to do so? Sorry for beginner questions but I am new to all of this including coding. Thanks in advance!

Code:
from dotenv import load_dotenv
import csv
import PyPDF2
from PyPDF2 import PdfReader
from langchain.document_loaders import DirectoryLoader, PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.prompts import PromptTemplate
import time
from langchain.chains.qa_with_sources import load_qa_with_sources_chain
from langchain.vectorstores import Chroma
from langchain.callbacks import StreamingStdOutCallbackHandler
import pandas as pd
from docx import Document
from nltk.tokenize import sent_tokenize, word_tokenize
from collections import Counter
from nltk.corpus import stopwords
import os

def print_letter_by_letter(text):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(0.02)

def main():
    load_dotenv()
    # directory_path = input("Copy your directory path here or upload a file: ")
    directory_path = "C:\\Users\\Asus\\OneDrive\\Documents\\Vendolista"

    pdf_loader = DirectoryLoader(directory_path,
                                  glob="**/*.pdf",
                                  show_progress=True,
                                  use_multithreading=True,
                                  silent_errors=True,
                                  loader_cls = PyPDFLoader)

    documents = pdf_loader.load()
    print(str(len(documents))+ " documents loaded")

    llm = ChatOpenAI(temperature = 0, model_name='gpt-3.5-turbo', callbacks=[StreamingStdOutCallbackHandler()], streaming = True)

    # Split into chunks
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
    )
    chunks = text_splitter.split_documents(documents)
    
    
    embeddings = OpenAIEmbeddings()
    persist_directory = "C:\\Users\\Asus\\OneDrive\\Documents\\Vendolista"
    knowledge_base = Chroma.from_documents(chunks, embeddings, persist_directory = persist_directory)
    #save to disk
    knowledge_base.persist() 
    #To delete the DB we created at first so that we can be sure that we will load from disk as fresh db
    knowledge_base = None
    new_knowledge_base = Chroma(persist_directory = persist_directory, embedding_function = embeddings)

    custom_template = ("""
    Help the users with answering questions based on the document.
    """
    )

    # prompt = PromptTemplate(input_variables=[], template=custom_template)
    prompt = PromptTemplate.from_template(custom_template)

    memory = ConversationBufferMemory(memory_key = "chat_history", return_messages = True)
    model = ConversationalRetrievalChain.from_llm(llm = llm,
                                                   chain_type = "refine",
                                                   retriever = new_knowledge_base.as_retriever(),
                                                   memory = memory,
                                                   combine_docs_chain_kwargs = {"prompt":prompt}
                                                   )

    while True:
        question = input("Ask me anything about the files (type 'exit' to quit): ")

        if question.lower() in ["exit"] and len(question) == 4:
            end_chat = "Thank you for visiting us! Have a nice day"
            print_letter_by_letter(end_chat)
            break

        if question:

            chat_history = []
            # with get_openai_callback() as cb:
            response = model({"question": question}, return_only_outputs = True)

            chat_history.append(('user', question))
            chat_history.append(('AI', response))
            print("AI:", response)

if __name__ == '__main__':
    main()

Error:

86 documents loaded
Traceback (most recent call last):
  File "C:\Users\Asus\Documents\Vendolista\app.py", line 100, in <module>
    main()
  File "C:\Users\Asus\Documents\Vendolista\app.py", line 73, in main
    model = ConversationalRetrievalChain.from_llm(llm = llm,
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 341, in from_llm
    doc_chain = load_qa_chain(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\question_answering\__init__.py", line 249, in load_qa_chain
    return loader_mapping[chain_type](
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\chains\question_answering\__init__.py", line 206, in _load_refine_chain
    return RefineDocumentsChain(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for RefineDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)

**Comment by andrewsanchez** [comment]
See my response here, @yazanrisheh   https://github.com/langchain-ai/langchain/issues/6530#issuecomment-1771141465

**Comment by tsantra** [comment]
I am using llama2 with ConversationalRetrievalChain and after adding custom system prompt model behaves weirdly. 

system_template = """Use the following pieces of context to answer the users question. 
    If you cannot find the answer from the pieces of context, just say that you don't know, don't try to make up an answer.
    
    
    ----------------
    {context}
    
    ### RESPONSE :
    
    """

    # Create the chat prompt templates 
    messages = [
    SystemMessagePromptTemplate.from_template(system_template),
    HumanMessagePromptTemplate.from_template("{question}")
    ]
    qa_prompt = ChatPromptTemplate.from_messages(messages)        
    
    
    chain = ConversationalRetrievalChain.from_llm(
        bigdl_llm,
        retriever,        
        memory=memory,
        verbose=False,
        return_source_documents=True,
        rephrase_question=False,
        condense_question_prompt=CONDENSE_QUESTION_PROMPT,
        combine_docs_chain_kwargs={"prompt": qa_prompt})


Model response (attached pic): It is now generating Assistant Human and ### Response. Before it was only generating the answer. My idea to customize this system prompt is to stop the model from conversing with itself. I am trying to add some kind of stop words. Like ###RESPONSE through the prompt. Not sure if this is the right way. Can you please help. 

![image](https://github.com/langchain-ai/langchain/assets/45886215/50f5240b-1477-4a25-8dc6-8aba04808a74)

**Comment by yazanrisheh** [comment]
@tsantra I'm also struggling with that cuz it feels like its talking to itself. In my case, it keeps on rephrasing the question I ask it and answers that
