### ISSUE TITLE
include_df_in_prompt should be compared as boolean value and not None

### ISSUE THREAD

**Issue by Yanni8** [langchain-ai/langchain#11677]
### System Info

Version `0.0.312`

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

# Description

The parameter `include_df_in_prompt` on the method `create_pandas_dataframe_agent` is a boolean value which should be eigther `True` or `False`.

If you specify your own suffix in the create_pandas_dataframe_agent method it results in an error saying that the variable include_df_in_prompt should be False.

## For example

```python
 agent = create_pandas_dataframe_agent(ChatOpenAI(temperature=0),df, AgentType.OPENAI_FUNCTIONS, suffix=sufix)
```
Results in 
```
ValueError: If suffix is specified, include_df_in_prompt should not be.
``` 

This is also the correct behavior. However, if you set `include_df_in_prompt` to `False`, the error still occurs. 

## For example
```python
 agent = create_pandas_dataframe_agent(ChatOpenAI(temperature=0),df, AgentType.OPENAI_FUNCTIONS, suffix=sufix, include_df_in_prompt=False)
```

But everything just works fine if I use `None` instade of `False`

## For example
```python
 agent = create_pandas_dataframe_agent(ChatOpenAI(temperature=0),df, AgentType.OPENAI_FUNCTIONS, suffix=sufix, include_df_in_prompt=None)
``

### Expected behavior

It should also work when I use `False` instade of `None`

**Comment by CrasCris** [comment]
If i create this suffix="""
Columnas informacion : {informacion}
Este es el contexto de la conversacion que has tenido con el 'Usuario': {contexto}
Inicia!
Pregunta: {input}
{agent_scratchpad}"""

and i put the include_df_in_prompt=False,
why i got this error "
    system_message = SystemMessage(content=prefix + suffix)
TypeError: can only concatenate str (not "NoneType") to str"
i dont want to send the full dataframe in the promt, i just want to send usefull information to the LLM to help it
