### ISSUE TITLE
 Integrating `create_citation_fuzzy_match_chain` with `ConversationalRetrievalChain`

### ISSUE THREAD

**Issue by timxieICN** [langchain-ai/langchain#11673]
### Feature request

Similar to the discussion in this thread https://github.com/langchain-ai/langchain/issues/7239, I would like to have a way to show inline citations in QA tasks.

Specially, I haven't had a whole lot of success integrating `create_citation_fuzzy_match_chain` with `ConversationalRetrievalChain`

### Motivation

The point of this change is to enable QA based chains (e.g. ConversationalRetrievalChain) to easily do inline citations, and surface the citations as part of metadata fields

### Your contribution

TBD

**Comment by timxieICN** [comment]
I would say that's a poor response. 
In my opinion, the proper way is to somehow replace the `load_qa_chain` of `ConversationalRetrievalChain` with `create_citation_fuzzy_match_chain`

**Comment by timxieICN** [comment]
ok, let's start simple - do you have any suggestions on how to create a `StuffDocumentsCitationChain` by combing the custom logic of `create_citation_fuzzy_match_chain` with the existing `StuffDocumentsChain`?

**Comment by timxieICN** [comment]
@dosu-bot

ok, let's start simple - do you have any suggestions on how to create a `StuffDocumentsCitationChain` by combing the custom logic of `create_citation_fuzzy_match_chain` with the existing `StuffDocumentsChain`?

**Comment by timxieICN** [comment]
@dosu-bot

I tried something similar, but now seeing error
```
llm_chain_variables = values["llm_chain"].prompt.input_variables
AttributeError: 'function' object has no attribute 'prompt'
```

**Comment by timxieICN** [comment]
@dosu-bot

A related question:
If I use `ConversationalRetrievalChain.llm(memory=ConversationTokenBufferMemory())`, is there a way for me to save extra information into `additional_kwargs` of the `data` field, other than `content` field?

**Comment by timxieICN** [comment]
@dosu-bot

Is there a way of not having to create a subclass such as `CustomConversationBufferMemory`, but able to justify the `output_key` to distinguish between a `content` and `additional_kwargs` before calling `save_context`?

**Comment by timxieICN** [comment]
@dosu-bot:

Switching gears - If I use `ConversationalRetrievalChain.llm(memory=ConversationTokenBufferMemory())`, how does the `ConversationalRetrievalChain` leverage `chat_history`? based on my analysis, the `chat_history` only makes an impact on rephrasing the question given the argument `rephrase_question`

**Comment by timxieICN** [comment]
@dosu-bot
Thanks, yes, I'm on the same page. I was asking if the memory or `chat_history` is used anywhere else other than in `rephrase_question` within `ConversationalRetrievalChain.llm(memory=ConversationTokenBufferMemory())`

**Comment by timxieICN** [comment]
@dosu-bot:
Then how does `self.combine_docs_chain` use the memory or `chat_history`?

**Comment by SunXianyong** [comment]
@dosubot:
I'm developing based on your discussions.
But I faced a new problem：After I integrated create_citation_fuzzy_match_chain and StuffDocumentsChain. The chunk parameter of the on_llm_new_token function in my callbacks is always ''. How can I ensure that my streaming output only contains chat's answer content?
