### ISSUE TITLE
text split by llm?

### ISSUE THREAD

**Issue by sudranga** [langchain-ai/langchain#11691]
### Feature request

Would it make sense to use an llm to split a large document into smaller documents that have complete context?

### Motivation

My best guess is that most of the existing splitters may drop context ?

### Your contribution

Could try

**Comment by beongeist** [comment]
Certainly an interesting idea! Definitely could improve quality of splits for documents that don't have easy line breaks to go by. 

One flaw is the if a single document gets too large to fit in the token space, then you would have split the document to fit it into the LLM's context size. 

Another is the computational/api cost, but there are definitely scenarios where the benefits would outweigh the cost.

**Comment by Siddhijain16** [comment]
> Certainly an interesting idea! Definitely could improve quality of splits for documents that don't have easy line breaks to go by.
> 
> One flaw is the if a single document gets too large to fit in the token space, then you would have split the document to fit it into the LLM's context size.
> 
> Another is the computational/api cost, but there are definitely scenarios where the benefits would outweigh the cost.

Hi @beongeist , have you started the implementation? What are the steps you are following ? Results are favorable ??

**Comment by necarlson97** [comment]
Just posting this medium article on a [sliding window approach by Ayham Boucher](https://medium.com/@ayhamboucher/llm-based-context-splitter-for-large-documents-445d3f02b01b), in case it is of use to this conversation, or anyone working on an implementation.
