### ISSUE TITLE
Agent stopped due to iteration limit or time limit.

### ISSUE THREAD

**Issue by xxm1668** [langchain-ai/langchain#11699]
### Issue you'd like to raise.

![run](https://github.com/langchain-ai/langchain/assets/129041904/931e32c0-ef57-470f-9834-81d2da6f2be4)
如何获取打印的日志呢？不知道怎么关闭这些打印的日志

**Comment by xxm1668** [comment]
我其实想说的是response = agent_exec.run("游戏角色马里奥是谁？")，返回值是Agent stopped due to iteration limit or time limit.

return_direct = True，response就可以获取大模型回答的结果了

**Comment by timxieICN** [comment]
I think you can just set `verbose=True` in `initialize_agent`? Not sure if you are looking for something else
