### ISSUE TITLE
Allow API_KEY to be optional when API_BASE is selected for OpenAI.

### ISSUE THREAD

**Issue by haseeb-heaven** [langchain-ai/langchain#11700]
### Feature request

I propose a feature that allows the **API key** to be set as an optional **parameter** when changing the `openai_api_base` in LangChain's implementation of OpenAI. This feature would make it possible to set the API key to an empty string or any arbitrary string, similar to how it's done in **LiteLLM**. 

Relevant resources:
- LangChain OpenAI: [GitHub Repo](https://github.com/langchain-ai/langchain)
- LiteLLM Proxy: [Documentation](https://docs.litellm.ai/docs/proxy_server#create-a-proxy-for-multiple-llms)

### Motivation

The motivation for this proposal is to facilitate testing and development scenarios where the `openai_api_base` is pointed to a local or mock server that doesn't require an API key. Currently, when the API key is set to empty or an arbitrary string, LangChain OpenAI throws an `AuthenticationError`. This behavior is frustrating when trying to test or develop without a valid OpenAI API key.

### Your contribution

I am willing to help implement this feature and submit a PR, but I would appreciate guidance from the maintainers or community to ensure the changes are made correctly and in line with the project's standards and practices.

**Comment by Undertone0809** [comment]
Do you replicate this process ? I never see any error name "AuthenticationError" in code. If a local server is used, theoretically there will be no permission issues.

**Comment by haseeb-heaven** [comment]
Its not about local server but hosted online server which doesn't need any authentication but we need to setup the API key in our code in order to send requests,

Thats why i proposed changes to make the API key to set optional if we change our api base.
