### ISSUE TITLE
Add support for themoviedb querying to get movie info

### ISSUE THREAD

**Issue by HamJaw1432** [langchain-ai/langchain#11728]
### Feature request

The proposal is to enhance our Langchain by integrating support for querying The Movie Database (TMDb) using a Tool to retrieve detailed information about movies. 

[https://developer.themoviedb.org/docs/getting-started](url)
[https://github.com/celiao/tmdbsimple/](url)

### Motivation

Allowing users to query The Movie Database (TMDb) would allow users to ask information regarding moives, and this tool will give the llms better/more reliable information to work with.

### Your contribution

We intend to submit a pull request for this issue at some point in November for a school project.

**Comment by keenborder786** [comment]
@HamJaw1432 This is already integrated. Please check the following [link](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/load_tools.py#L147)

**Comment by HamJaw1432** [comment]
Oh I see I see, thanks for the heads up

**Comment by jcopps** [comment]
Well this is a good tool way of interacting the TMDB. 
The API document is vast and this tool only uses the search by text API.
