### ISSUE TITLE
Add option to specify prompt for SelfQueryRetriever

### ISSUE THREAD

**Issue by JanHorcicka** [langchain-ai/langchain#11735]
### Feature request

There is an option to specify the prompt sent to LLM and also the CONDENSE_QUESTION prompt. But there is no way to specify the prompt that is being used by SelfQueryRetriever. This can be helpful to provide additional context to the LLM in order to construct a proper query.

### Motivation

For my use case, the default prompt sent to LLM to generate a query doesn't work. Although the question I am asking the LLM is good, it is not able to figure the correct filter it should use. I think if I was able to modify the query, it could solve the issue and start returning correct queries.

### Your contribution

Not really.

**Comment by gwc4github** [comment]
Try this:
retriever = SelfQueryRetriever.from_llm(
                                        llm, 
                                        db, 
                                        document_content_description,
                                        metadata_field_info,
                                        chain_kwargs={"schema_prompt": schema_prompt},
                                        verbose=True)

**Comment by JanHorcicka** [comment]
Thanks for the answer, but it doesn't seem to work. I get `1 validation error`. Looking at the code, the `kwargs` seems to be used only for `allowed_comparators` and `allowed_operators`.

**Comment by JanHorcicka** [comment]
Hello. It is still relevant.
