### ISSUE TITLE
IndexError: pop from empty list - bug in ConversationTokenBufferMemory

### ISSUE THREAD

**Issue by chelseac704** [langchain-ai/langchain#11734]
### System Info

Langchain version: 0.0.312
Python: 3.10.11
Platform: Ubuntu

### Who can help?

@hwchase17 @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.memory import ConversationTokenBufferMemory

max_token_limit = 0
memory = ConversationTokenBufferMemory(
    llm=llm,  # Azure OpenAI GPT3.5
    max_token_limit=max_token_limit,
    return_messages=True,
)
context_pair = {
    "inputs": {"input": "Example input message."},
    "outputs": {"outputs": "Example output message."}
}

memory.save_context(**context_pair)
```

### Expected behavior

The above code produces an `IndexError: pop from empty list`

Due to some token budgeting we're doing, sometimes the space for the memory gets reduced to 0 (specifically when a user has a long message, we prioritize tokens for their message and the AI response). So we create memory with `max_token_limit=0`, and **ideally we'd like the memory to be pruned such that the buffer is empty.**  However, we instead get the above error.

### Where the bug seems to be
The culprit seems to be in `memory.save_context()` , which we call directly in some cases or sometimes it happens internally like:

```
chat_chain = ConversationChain(
    memory=memory, llm=llm, prompt=prompt_template
)
ai_response = chat_chain.predict(input=user_message)  # internal call to save_context()
```

Within `save_context`, there's a loop:

```
while curr_buffer_length > self.max_token_limit:
    pruned_memory.append(buffer.pop(0))
    curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
```

Oddly, when the buffer is an empty list, `curr_buffer_length` is 3 when it should be 0. So the loop continues and tries to pop from the empty buffer list and we get the above error.

![langchain_bug](https://github.com/langchain-ai/langchain/assets/67058165/7c76afc1-56eb-4497-ae27-3e8ae8d4ddf3)

**Comment by keenborder786** [comment]
@chelseac704  I am looking into it.

**Comment by keenborder786** [comment]
Hello, Why don't you implement your `CustomConversationTokenBufferMemory` as follow:

```python

import os

from langchain.memory import ConversationTokenBufferMemory
from typing import Dict,Any

max_token_limit = 0

class CustomConversationTokenBufferMemory(ConversationTokenBufferMemory):
    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        input_str, output_str = self._get_input_output(inputs, outputs)
        self.chat_memory.add_user_message(input_str)
        self.chat_memory.add_ai_message(output_str)
        buffer = self.chat_memory.messages
        curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
        if curr_buffer_length > self.max_token_limit:
            pruned_memory = []
            while curr_buffer_length > self.max_token_limit and buffer:
                pruned_memory.append(buffer.pop(0))
                curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)


memory = CustomConversationTokenBufferMemory(
    llm=llm, 
    max_token_limit=max_token_limit,
    return_messages=True,
)
context_pair = {
    "inputs": {"input": "Example input message."},
    "outputs": {"outputs": "Example output message."}
}

memory.save_context(**context_pair)
```

**Comment by keenborder786** [comment]
This will work for your usecase.

**Comment by chelseac704** [comment]
Yeah, we've implemented something similar that works.
