### ISSUE TITLE
async SQLDatabaseChain 

### ISSUE THREAD

**Issue by mrctito** [langchain-ai/langchain#11732]
### Feature request

Hello everyone!

Please when will we have SQLDatabaseChain async?

I believe it's crucial for all Chains to be async so that we can have a serverless service serving multiple clients.

Thank you!

### Motivation

I believe it's crucial for all Chains to be async so that we can have a serverless service serving multiple clients.

### Your contribution

I dont know how to contribute. Maybe I coult test your code.

**Comment by mrctito** [comment]
You can count on me, I'll be delighted to collaborate!
In fact, I already have an implementation of a serverless service to
respond to database-related queries, waiting for this feature to go into
production. So when this new capability is ready, I can test it quickly!

Em qui., 12 de out. de 2023 às 17:32, dosu-beta[bot] <
***@***.***> escreveu:

**Comment by sglebs** [comment]
I also need this feature. I will add more: we need to make sure it can be async all the way down, including the database driver. For example, it should work with something like:

```
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/mydb 
```

if you are using SQLAlchemy, for example, the engine to be instantiated is different:

```
from sqlalchemy import create_engine
from sqlalchemy.ext.asyncio import create_async_engine

database_url = os.getenv("DATABASE_URL")
if database_url.find("+asyncpg") > 0:
    engine = create_async_engine(database_url)
else:
    engine = create_engine(database_url)
```

SQLDatabaseChain should have similar smarts inside and support 100% async.

**Comment by sudranga** [comment]
This branch: https://github.com/sudranga/langchain/tree/11732 contains an implementation of async sql chain. I think things need to be reworked a little bit. 
A sample code that works with the branch contents is:

import gevent.monkey
gevent.monkey.patch_all()

import asyncio
import asyncio_gevent
asyncio.set_event_loop_policy(asyncio_gevent.EventLoopPolicy())
import langchain
langchain.verbose=True

from langchain.utilities import SQLDatabase
from langchain.llms import OpenAI
from langchain_experimental.sql import SQLDatabaseChain

async def say(what):
    cnt = 0
    while cnt < 5:
        print(what)
        await asyncio.sleep(1)
        cnt += 1

async def do_db():
    db = await SQLDatabase.from_uri_async("sqlite+aiosqlite:///Chinook.db")
    llm = OpenAI(temperature=0, verbose=True)
    db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
    await db_chain.arun("How many employees are there?")

async def main():
    task1 = asyncio.create_task(say("HELLO"))
    task2 = asyncio.create_task(do_db())
    await task1
    await task2
    print("done")

asyncio.run(main())

**Comment by yazanrisheh** [comment]
@sglebs @mrctito @sudranga 
Hey guys. You guys seem experts and I've just been learning both programming and LangChain for the past 6 months.

So I have a fully working and functional code when doing it sync however I'm trying to switch to async and the 2 issues I am saving is that 

1) Chat is not being saved in chat history
2) The questions and answers arent being saved in my Sql Alchemy db either.

I've made my code as short as possible to make it easy to read. I appreciate the help and thank you in advance

import asyncio
from langchain.llms import OpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.vectorstores import FAISS
from langchain.schema.vectorstore import VectorStoreRetriever
import time
retriever = load_emdeddings(cfg.faiss_persist_directory, cfg.embeddings).as_retriever(search_kwargs = {"search_type" : "similarity"})
memory = ConversationBufferWindowMemory(k=2, chat_memory=chat_message_history, memory_key="chat_history", return_messages=True)

custom_prompt_template = """
You are an amazing bot named "XYZ", designed to provide assistance and answer queries related to the XYZ book.. You are primarily trained on the XYZ data. When engaging in conversation, please adhere to these guidelines:

The user you are in communication with is referred to as {User_Name}.
The user's location is noted as {User_Location}.
Personalize your interactions by addressing the user with their name, but use it sparingly and only at moments that seem most fitting.


{context}
Chat History: {chat_history}

Question: {question}

"""

# Create a PromptTemplate instance with your custom template
custom_prompt = PromptTemplate(
    template=custom_prompt_template,
    input_variables=["context", "question", "chat_history", "User_Name", "User_Location"],
)

qa = ConversationalRetrievalChain.from_llm(llm=cfg.llm, memory= memory, retriever=retriever, combine_docs_chain_kwargs={"prompt": custom_prompt})

# Define your list of queries
queries = ['How many chocolates are there?', 'What is the calories for those chocolates?', 'What is the name of the chocolates']
# Define an async function to process a single query
async def process_query(query):

    result = await qa._acall(inputs={"question": query, "User_Location": "Jamacia", "User_Name": "Brandon", "chat_history":[]})
    return result

# Use asyncio to run all queries in parallel
async def process_all_queries():
    tasks = [process_query(query) for query in queries]
    results = await asyncio.gather(*tasks)
    return results

My SQL module:

class CustomMessage(Base):
    tablename = "custom_message_store"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(Text)
    type = Column(Text)
    content = Column(Text)
    created_at = Column(DateTime)
    author_email = Column(Text)


class CustomMessageConverter(BaseMessageConverter):
    def init(self, author_email: str):
        self.author_email = author_email

    def from_sql_model(self, sql_message: Any) -> BaseMessage:
        if sql_message.type == "human":
            return HumanMessage(
                content=sql_message.content,
            )
        elif sql_message.type == "ai":
            return AIMessage(
                content=sql_message.content,
            )
        else:
            raise ValueError(f"Unknown message type: {sql_message.type}")

    def to_sql_model(self, message: BaseMessage, session_id: str) -> Any:
        now = datetime.now()
        return CustomMessage(
            session_id=session_id,
            type=message.type,
            content=message.content,
            created_at=now,
            author_email=self.author_email,
        )

    def get_sql_model_class(self) -> Any:
        return CustomMessage


chat_message_history = SQLChatMessageHistory(
    session_id="user1@example.com",
    connection_string="mssql+pyodbc://User\SQLEXPRESS/db_name?driver=ODBC+Driver+17+for+SQL+Server",
    custom_message_converter=CustomMessageConverter(author_email="user1@example.com"),
)

**Comment by TitanXtream** [comment]
Hi everyone, 
Adding async system to the SQLDatabaseChain is actually a great suggestion. We can really manage clients requests in a serverless way. 
Well but what about the current situation? Do I have to use the synchronous system only? Is there any other option?

I am making an app that needs to interact with 100 users or may be 1000 so I don't think synchronous system is a good way.
Please help anyone....
