### ISSUE TITLE
TypeError: BaseChatModel.__call__() missing 1 required positional argument: 'messages'

### ISSUE THREAD

**Issue by HoustonMuzamhindo** [langchain-ai/langchain#11733]
### Issue you'd like to raise.

I am following the notebook in this github to create two agents with tools:

https://github.com/langchain-ai/langchain/blob/master/cookbook/two_agent_debate_tools.ipynb

I am also using AzureOpenAI instead of OpenAI directly because of corporate firewalls. I am getting this error:

TypeError                                 Traceback (most recent call last)
Cell In[25], line 34
     24     agent_description = AzureChatOpenAI(
     25                             openai_api_base=BASE_URL,
     26                             openai_api_version="2023-05-15",
   (...)
     29                             openai_api_type="azure",
     30                         )(temperature=1.0)(agent_specifier_prompt).content
     31     return agent_description
---> 34 agent_descriptions = {name: generate_agent_description(name) for name in names}

Cell In[25], line 34, in (.0)
     24     agent_description = AzureChatOpenAI(
     25                             openai_api_base=BASE_URL,
     26                             openai_api_version="2023-05-15",
   (...)
     29                             openai_api_type="azure",
     30                         )(temperature=1.0)(agent_specifier_prompt).content
     31     return agent_description
---> 34 agent_descriptions = {name: generate_agent_description(name) for name in names}

Cell In[25], line 24, in generate_agent_description(name)
     13 def generate_agent_description(name):
     14     agent_specifier_prompt = [
...
     29                             openai_api_type="azure",
     30                         )(temperature=1.0)(agent_specifier_prompt).content
     31     return agent_description

TypeError: BaseChatModel.__call__() missing 1 required positional argument: 'messages'

**Comment by HelloWorldLTY** [comment]
I have the same question here. Does any one solve it?
