### ISSUE TITLE
AttributeError: 'BloomForCausalLM' object has no attribute 'is_quantized'

### ISSUE THREAD

**Issue by gapirajat** [langchain-ai/langchain#11759]
### System Info

Google Colab
langchain==0.0.313
transformers==4.34.0
Python 3.10.12

[Dependencies](https://pastebin.com/raw/T1BqzVq1)

I am trying to download huggingface model and feed them to the chain. It was working prior to few weeks. I have tried to change model id to other models.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
```
!pip install langchain transformers

from langchain import HuggingFacePipeline
llm = HuggingFacePipeline.from_model_id(model_id = "bigscience/bloom-560m", task = "text-generation")
```
### Expected behavior

Successful execution
## Screenshot
![Screenshot_2023-10-13_09-37-20](https://github.com/langchain-ai/langchain/assets/86911396/51f46569-6bcc-4057-81a6-68eba060af50)

**Comment by gapirajat** [comment]
Same when tested in kaggle

**Comment by gapirajat** [comment]
Works fine if you remove 
```
        if (
            model.is_quantized
            or model.model.is_loaded_in_4bit
            or model.model.is_loaded_in_8bit
        ) and device is not None:
            logger.warning(
                f"Setting the `device` argument to None from {device} to avoid "
                "the error caused by attempting to move the model that was already "
                "loaded on the GPU using the Accelerate module to the same or "
                "another device."
            )
            device = None

        if device is not None and importlib.util.find_spec("torch") is not None:
```

**Comment by gapirajat** [comment]
I want to contribute (Im new) should I simply create a branch and push

**Comment by eryk-dsai** [comment]
https://github.com/langchain-ai/langchain/pull/11891
