### ISSUE TITLE
DOC:**Page Not Found**

### ISSUE THREAD

**Issue by rdhillbb** [langchain-ai/langchain#11758]
### Issue with current documentation:

From the page 
https://python.langchain.com/docs/integrations/platforms/aws

If you select  See a [usage example.](https://python.langchain.com/docs/integrations/llms/amazon_api_gateway_example) the following message is generated:

**Page Not Found**
We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

https://python.langchain.com/docs/integrations/llms/amazon_api_gateway_example

**Comment by chyroc** [comment]
this issue should be closed.
