### ISSUE TITLE
feat: add NASA API tool

### ISSUE THREAD

**Issue by matiasjacob25** [langchain-ai/langchain#11787]
### Feature request

The feature proposal is to integrate a new Langchain tool that would provide support for queries on [https://api.nasa.gov/](NASA APIs)

Here is the list of NASA APIs that will be integrated into the new tool:
- APOD
- Asteroids NeoWs
- Earth
- EONET
- EPIC
- GeneLab
- Insight
- Mars Rover Photos
- NASA Image and Video Library
- TechTransfer
- TLE API
- Vesta/Moon/Mars Trek WMTS

### Motivation

Currently, Langchain does not provide access to a large data pool of reliable information related to astronomy. The integration of a NASA API tool would allow users to retrieve updated and accurate data related to satellite imagery, mission data and other space-related information. In cases where accuracy of data is critical, the NASA API tool may also be preferred over its GPT-generated counterpart.

### Your contribution

I am part of a group of 3 other students that will be able to submit a PR for this issue sometime in November.

**Comment by JaynouOliver** [comment]
Hi, @matiasjacob25 I would like to collaborate on this issue with you.

**Comment by matiasjacob25** [comment]
Hey @JaynouOliver, I appreciate your interest in collaborating with me on this issue, but as I have mentioned in the issue description I'm currently working on this issue with 3 other members and it is actually part of a school project. This will be my team's first open-source contribution, and we would like to work towards submitting an initial PR before receiving input/feedback from the Langchain community! If you are still interested in collaborating, we would love for you to take a look at our PR changes sometime in November.

**Comment by matiasjacob25** [comment]
Hey @dosu-bot we're thinking about integrating multiple NASA APIs through a toolkit. We were also thinking of routing the API calls using different "modes". The modes would be supplied with different prompts which would allow the query to decide which NASA API would be most appropriate.

**Comment by matiasjacob25** [comment]
Hey @JaynouOliver , my team and I finally came around to posting our PR solution for the NASA API toolkit. We originally planned on integrating multiple NASA APIs into our toolkit, but with this being my team and I's first contribution, we felt that it may be more effective to set the base for the toolkit and integrate the NASA Image and Video Library API, in hopes that our team and others could extend on the toolkit to include other NASA APIs in the future.

I know you were originally curious about working on this issue with me, so if you have any suggestions or are thinking about extending the tool, that'd be great!

**Comment by JaynouOliver** [comment]
Thank you so much for the reply. I will take a look at it. But I will be available from January next year. So I won't be able to work on it.
I will incorporate my feedback and if you can extend it I would like to join from Jan
