### ISSUE TITLE
Issue: <add_texts method in AzureSearch class throwing a metadata error>

### ISSUE THREAD

**Issue by msunkarahend** [langchain-ai/langchain#11780]
### Issue you'd like to raise.

my Azure search index has 4 fields
id, user_id, content, content_vector.

I am trying to add a conversation to the azure search vector store for a user_id ="msunkara"

The code is given below:

    memory_vector_store: AzureSearch = AzureSearch(
        azure_search_endpoint=vector_store_address,
        azure_search_key=vector_store_password,
        index_name=memory_index_name,
        embedding_function=embeddings.embed_query)
     
    history = []
    user_id = "msunkara"
    session_id = "1"

query = Hi
res.content = Hi, How can I assist you today?

    history.append("User: "+ query + " Assistant: " + res.content)

    memory_id = session_id + user_id
    metadata = [{"user_id": user_id}]
    memory_vector_store.add_texts(history,keys = [memory_id],metadatas=metadata)

The above code is throwing the below error:
Result: Failure Exception: HttpResponseError: () The request is invalid. Details: The property 'metadata' does not exist on type 'search.documentFields'. Make sure to only use property names that are defined by the type. 

Help me solve this problem

**Comment by msunkarahend** [comment]
@dosu-bot But i dont want it to be defined as metadata in the azure search index. I want it to be by my own custom field name user_id. so tell me how to override it to my custom name using langchain framework.

**Comment by msunkarahend** [comment]
@dosu-bot I have multiple azure search classes intialized in the code. How to make sure the environment variable is for the memory_vector_store  only

**Comment by msunkarahend** [comment]
@dosu-bot 

I have two AzureSearch instances defined in the application.

    vector_store: AzureSearch = AzureSearch(
        azure_search_endpoint=vector_store_address,
        azure_search_key=vector_store_password,
        index_name=index_name,
        embedding_function=embeddings.embed_query
        )

    memory_vector_store: AzureSearch = AzureSearch(
        azure_search_endpoint=vector_store_address,
        azure_search_key=vector_store_password,
        index_name=memory_index_name,
        embedding_function=embeddings.embed_query
        )

now, i want to define the environment variable 
    import os
    os.environ["AZURESEARCH_FIELDS_TAG"] = "user_id"

ONLY to the memory_vector_store and not vector_store. How to do it?

**Comment by msunkarahend** [comment]
@dosu-bot Can you raise a feature request with the development team to define the custom field names while initializing the AzureSearch instances.

**Comment by pappala-naidu** [comment]
if you index schema is like:

id:
content:
content_vector:
user_id:

then  try this:

```
extra_fields = {"extra_fields": {"user_id": user_id}}
memory_vector_store.add_texts(history,keys = [memory_id], **extra_fields)

```

**Comment by bhanu-pappala** [comment]
if you index schema is like:

id:
content:
content_vector:
user_id:

then try this:

```
extra_fields = {"extra_fields": {"user_id": user_id}}
memory_vector_store.add_texts(history,keys = [memory_id], **extra_fields)

```
