### ISSUE TITLE
bug : error - TypeError: from_llm() got an unexpected keyword argument 'return_source_documents'

### ISSUE THREAD

**Issue by amoghagastya** [langchain-ai/langchain#1179]
The return Source Documents parameter for ChatVectorDBChain is not working. Getting the following error - 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/46256520/220151201-669c6a1a-63af-4a49-bc67-8289da1788c3.png">

Code causing the error below -
qa = ChatVectorDBChain.from_llm(OpenAI(temperature=0), vectorstore, qa_prompt=QA_PROMPT,return_source_documents=True)

**Comment by hwchase17** [comment]
this works for me - can you make sure you've upgraded your version of langchain to the most recent one?
