### ISSUE TITLE
Getting an error while importing MultiPromptChain

### ISSUE THREAD

**Issue by azazel92** [langchain-ai/langchain#11819]
### System Info

Langchain version: 0.0.313
Python version: Python 3
OS: Mac

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chains.router.multi_prompt import MultiPromptChain

Assume have already installed langchain and other necessary libraries

Error I get:
cannot import name 'BasePromptTemplate' from 'langchain.schema'. I checked in the langchain.schema file. BasePromptTemplate is indeed not there. But then I don't know how to get that file. I see PromptTemplate file in the langchain.schema file

### Expected behavior

To import MultiPromptChain

**Comment by azazel92** [comment]
@dosu-bot - the issue is not resolved by the above suggestion.

I did the below steps:

**Step 1: Imported BasePromptTemplate**
from langchain.prompts import BasePromptTemplate

**2. Imported MultiPromptChain and couple other libraries as shown below**
from langchain.chains.router.multi_prompt import MultiPromptChain
from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
from langchain.prompts import PromptTemplate

The first step works well, but when i run the code mentioned in the 2nd step, i get the below error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[330], line 1
----> 1 from langchain.chains.router.multi_prompt import MultiPromptChain
      2 from langchain.chains.router.llm_router import LLMRouterChain,RouterOutputParser
      3 from langchain.prompts import PromptTemplate

File ~/anaconda3/lib/python3.10/site-packages/langchain/chains/router/__init__.py:2
      1 from langchain.chains.router.base import MultiRouteChain, RouterChain
----> 2 from langchain.chains.router.llm_router import LLMRouterChain
      3 from langchain.chains.router.multi_prompt import MultiPromptChain
      4 from langchain.chains.router.multi_retrieval_qa import MultiRetrievalQAChain

File ~/anaconda3/lib/python3.10/site-packages/langchain/chains/router/llm_router.py:14
     12 from langchain.output_parsers.json import parse_and_check_json_markdown
     13 from langchain.pydantic_v1 import root_validator
---> 14 from langchain.schema import BaseOutputParser, BasePromptTemplate, OutputParserException
     15 from langchain.schema.language_model import BaseLanguageModel
     18 class LLMRouterChain(RouterChain):

ImportError: cannot import name 'BasePromptTemplate' from 'langchain.schema' (/Users/Azazel/anaconda3/lib/python3.10/site-packages/langchain/schema.py)

Can you explain the above error? And how may I fix it?

Also one side question -> I believe you are a bot, so which LLM is powering you? is it something github has built on it;s own or one of the available LLMs such as GPT-4, Llama?

**Comment by devstein** [comment]
> Also one side question -> I believe you are a bot, so which LLM is powering you? is it something github has built on it;s own or one of the available LLMs such as GPT-4, Llama?

@azazel92 As Dosu mentioned, it's a combination of OpenAI GPT models and others 😄 


Did you solve this issue? Dosu's suggestions are actually the most likely causes

**Comment by visin109** [comment]
from langchain.prompts.base import BasePromptTemplate

class CustomPromptTemplate(BasePromptTemplate):
    def __init__(self, template):
        self.template = template

    def format(self, context, chat_history, question):
        return self.template.format(context=context, chat_history=chat_history, question=question)

    def format_prompt(self, context, chat_history, question):
        return self.format(context, chat_history, question)
qa_prompt = CustomPromptTemplate(template="some prompts here")
formatted_prompt = qa_prompt.format_prompt(context="", chat_history="", question="")

qa = ConversationalRetrievalChain.from_llm(llm, vectorstore.as_retriever(), memory=memory, get_chat_history=lambda h : h,prompt=formatted_prompt


for this im getting the following error.
ValueError: "CustomPromptTemplate" object has no field "template" 
I used this method to implement prompts for the conversational retireval chain to limit the model's responses to go put of context. How to resolve this error

If any other methods are there to introduce prompts to limit the model going out of context, please suggest them.
Fyi, I have already used combined_kwargs parameter for prompts but didn't work as im getting validation error stating its not a dict.
