### ISSUE TITLE
ConfluenceLoader's keep_newlines is not passed correctly

### ISSUE THREAD

**Issue by Littlecowherd** [langchain-ai/langchain#11853]
### System Info

LangChain version: v0.0.314

### Who can help?

@eyurtsev @baskaryan 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
    from langchain.document_loaders import ConfluenceLoader

    loader = ConfluenceLoader(url="xxx", session=get_session())
    docs = loader.load(page_ids=["xxx"], keep_newlines=True)
    for doc in docs:
        print(doc.page_content)
        have_newlines = "\n" in doc.page_content
        print(f"{have_newlines=}")
```

read the source code, I found the `keep_newlines` arguments are not passed to `process_page` function when load with `cql` and `page_ids` 
file: `langchain.document_loaders.confluence.py`
function: `Confluence.load`
lines: 308-353

<img width="781" alt="image" src="https://github.com/langchain-ai/langchain/assets/19882756/1d11d7dd-f883-4782-8b5d-3365ca2dff87">
<img width="821" alt="image" src="https://github.com/langchain-ai/langchain/assets/19882756/b87f3a16-65a4-490c-851f-0c51a534d171">

### Expected behavior

The `keep_newlines` parameter is passed correctly and empty lines are correctly retained

**Comment by MonoMarkor** [comment]
hello i am having the sam issue

**Comment by mukulasija** [comment]
Facing the same issue
