### ISSUE TITLE
Issue: When using ChatGLM, I can't connect to the endpoint_url.

### ISSUE THREAD

**Issue by 1024689068** [langchain-ai/langchain#11859]
### Issue you'd like to raise.

When I use the chatglm code from the official documentation, I can't connect to the endpoint URL provided there.

The official website is: https://python.langchain.com/docs/integrations/llms/chatglm

The specific code is as follows：

          from langchain.llms import ChatGLM
          from langchain.prompts import PromptTemplate
          from langchain.chains import LLMChain
          
          template = """{question}"""
          prompt = PromptTemplate(template=template, input_variables=["question"])
          
          endpoint_url = "http://127.0.0.1:8000"
          
          llm = ChatGLM(
              endpoint_url=endpoint_url,
              max_token=80000,
              history=[["我将从美国到中国来旅游，出行前希望了解中国的城市", "欢迎问我任何问题。"]],
              top_p=0.9,
              model_kwargs={"sample_model_args": False},
          )
          
          llm_chain = LLMChain(prompt=prompt, llm=llm)
          
          question = "北京和上海两座城市有什么不同？"
          
          llm_chain.run(question)

The code is encountering the following error：

        ValueError: Error raised by inference endpoint: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with 
url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000163A6691F70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

I have tried many methods I found online, but they didn't have much effect. I'm not sure if it's necessary to open a specific server through cmd to connect to 127.0.0.1:8000.

**Comment by 1024689068** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for reaching out with your issue. The error message you're seeing typically indicates that the server at the endpoint URL "http://127.0.0.1:8000/" is not running. The endpoint URL is where the ChatGLM model is hosted. If the server is not running, you will not be able to connect to it.
> 
> Here are a few things you can check:
> 
> 1. **Server Status**: Ensure that the server hosting the ChatGLM model is running at the specified endpoint URL. If you're running the server locally, you would need to start the server before you can connect to it.
> 2. **Network Connection**: Ensure that your network connection is stable and that the server is reachable from your network.
> 3. **Endpoint URL**: Ensure that the endpoint URL is correct and that the server is listening on the correct port. In the context shared, it appears that the server is set to run on port 8001, not 8000. This could be the reason why you are unable to connect to the server at "http://127.0.0.1:8000/". You should try connecting to "http://127.0.0.1:8001/" instead.
> 
> Regarding your question about whether you need to open a specific server to connect to 127.0.0.1:8000, if you are running the server locally, you would need to start the server before you can connect to it. If the server is not running locally, you would need to ensure that the server is running and that the endpoint URL is correct. If the server is running on a different machine, you would need to ensure that the server is reachable from your machine and that there are no network issues preventing you from connecting to the server.
> 
> I hope this helps! If you have any other questions or need further clarification, please don't hesitate to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [Max retries exceeded with url: /chain-runs](https://github.com/langchain-ai/langchain/issues/2145)
> * [libs/langchain/langchain/llms/chatglm.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/chatglm.py)
> * [libs/langchain/langchain/cli/create_repo/templates/repo/.env](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/cli/create_repo/templates/repo/.env)
> * [docs/docs_skeleton/docs/integrations/llms/chatglm.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs_skeleton/docs/integrations/llms/chatglm.ipynb)
> * [libs/langchain/langchain/chat_models/azureml_endpoint.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chat_models/azureml_endpoint.py)
> * [libs/langchain/tests/integration_tests/llms/test_chatglm.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/integration_tests/llms/test_chatglm.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.


Thank you for your response. I still have some questions about this issue. Where can I obtain the server code for ChatGPT LM, and once I have the server, how can I connect it to 127.0.0.1:8000?

**Comment by ropz12138** [comment]
I encountered the same issue. I started a server using the webui_demo provided by ChatGLM's official documentation, and this server was set up using gradio. When I set the endpoint_url in the ChatGLM class in langchain to this public URL, I got a response<405> error. I believe this seems to be an issue with the server. How should I start the server? Or is there another way to resolve this issue?
