### ISSUE TITLE
KuzuGraph not working

### ISSUE THREAD

**Issue by decentropy** [langchain-ai/langchain#11874]
### System Info

Name: kuzu
Version: 0.0.10 (latest)

Name: langchain
Version: 0.0.311

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am using the example from langchain documentation:
https://python.langchain.com/docs/use_cases/graph/graph_kuzu_qa

This line fails:
graph = KuzuGraph(db)

F```
ile [~/.local/lib/python3.10/site-packages/langchain/graphs/kuzu_graph.py:71](https://file+.vscode-resource.vscode-cdn.net/home/steve/Projects/homelab/homeapi/notebooks/~/.local/lib/python3.10/site-packages/langchain/graphs/kuzu_graph.py:71), in KuzuGraph.refresh_schema(self)
     69 for table in rel_tables:
     70     current_table_schema = {"properties": [], "label": table["name"]}
---> 71     properties_text = self.conn._connection.get_rel_property_names(
     72         table["name"]
     73     ).split("\n")
     74     for i, line in enumerate(properties_text):
     75         # The first 3 lines defines src, dst and name, so we skip them
     76         if i < 3:

AttributeError: 'kuzu._kuzu.Connection' object has no attribute 'get_rel_property_names'
```

### Expected behavior

should work like example

**Comment by yzhang1918** [comment]
The method "get_rel_property_names" has been removed since kuzu 0.0.10.

Check this PR: https://github.com/kuzudb/kuzu/pull/2207

A temporary solution is to use kuzu==0.0.9

```
pip install kuzu==0.0.9
```

**Comment by karbasia** [comment]
I've created a PR to resolve this issue: #16885

**Comment by baskaryan** [comment]
Should be fixed in https://github.com/langchain-ai/langchain/pull/16885
