### ISSUE TITLE
Enable token usage count for AWS Bedrock

### ISSUE THREAD

**Issue by alex-ld** [langchain-ai/langchain#11906]
### Feature request

There should be a callback handler like [OpenAICallbackHandler](https://github.com/langchain-ai/langchain/blob/31f264169db4ab23689f2e179983f1cfdfd1a33a/libs/langchain/langchain/callbacks/openai_info.py#L120) for AWS Bedrock models, so that we can easily get the token usage and monitor cost.

It looks like the AWS Bedrock API doesn't return with token usage. Unlike OpenAI.

Can we have similar feature, perhaps [using the internal Anthropic tokenizer to count](https://github.com/langchain-ai/langchain/blob/31f264169db4ab23689f2e179983f1cfdfd1a33a/libs/langchain/langchain/llms/bedrock.py#L405)?

### Motivation

Cost monitoring

### Your contribution

PR

**Comment by krrishdholakia** [comment]
Hey @alex-ld you can do this via ChatLiteLLM - all responses return token usage. You can also use our cost calculator functions to calculate cost for each call. 

```python
from langchain.chat_models import ChatLiteLLM
from langchain.schema import AIMessage, HumanMessage, SystemMessage

chat = ChatLiteLLM(model="bedrock/anthropic.claude-v2")

messages = [
    HumanMessage(
        content="Translate this sentence from English to French. I love programming."
    )
]
chat(messages)
```

Calculate cost: https://docs.litellm.ai/docs/completion/token_usage#5-completion_cost

```python
from litellm import completion_cost
cost = completion_cost(model="bedrock/anthropic.claude-v2", prompt="Hey!", completion="How's it going?")
formatted_string = f"${float(cost):.10f}"
print(formatted_string)
```

Langchain Docs: https://python.langchain.com/docs/integrations/chat/litellm
LiteLLM Docs: https://docs.litellm.ai/docs/providers/bedrock

**Comment by VBoB13** [comment]
> You can also use our cost calculator functions to calculate cost for each call.

I might be too much of a beginner to notice, but it doesn't look like this implementation supports the use of Agents that utilizes Bedrock LLMs..
Are there any plans to support this soon?
The context manager for OpenAI that LangChain provides is very straight forward, and it'd be awesome to see something similar for Bedrock models.

**Comment by nggih** [comment]
https://how.wtf/how-to-count-amazon-bedrock-anthropic-tokens-with-langchain.html I have the same problem but mine is specific on Anthropic Claude usage, I found the solution on the link

**Comment by pratik60** [comment]
There are two pr's submitted by the community here: 

https://github.com/langchain-ai/langchain/pull/19127
https://github.com/langchain-ai/langchain/pull/19448

Hoping we can merge one soon. I don't think either of them support counting of tokens when streaming though.

**Comment by dmenini** [comment]
Thanks @pratik60 for the mention of my PR in this issue, I totally missed it. Indeed I am adding support for token usage info for Bedrock models, and I plan on adding the LLMCallback to mimic the OpenAI one's (unless someone else does it first).

For streaming, extracting the usage info is a bit more complicated as it's provider dependant. I can add the feature for anthropic only, as that is the only provider I have access to. Will open a PR for this as soon as possible.

**Comment by pratik60** [comment]
@dmenini I'm also just using Anthropic from Bedrock, so fortunately that works for me.
