### ISSUE TITLE
Adding an IMDb tool

### ISSUE THREAD

**Issue by jesseyao89** [langchain-ai/langchain#11926]
### Feature request

A tool to allow agents to search and retrieve data from IMDb (https://www.imdb.com/).

### Motivation

IMDb is one of the largest movie databases available online. Adding this tool would allow agents to intelligently retrieve up-to-date movie information from IMDb, enhancing the experience of its users. For example, with this tool, users could utilize LangChain through easily accessible prompts to find movies based on favorite genres, relations to other movies, or other information such as actors and producers.

### Your contribution

If all goes well, a PR can be ready sometime in November with this feature implemented.

**Comment by Pyrunix** [comment]
Hello, as we continue to work on this implementation, we'd like to ask if anyone has any suggestions or ideas we should implement with this. Thanks
