### ISSUE TITLE
OpenAI and GooseAI each overwrite openai.api_key

### ISSUE THREAD

**Issue by zswitten** [langchain-ai/langchain#1192]
```from langchain.llms import GooseAI, OpenAI
import os
os.environ['OPENAI_API_KEY'] = 'ooo'
os.environ['GOOSEAI_API_KEY'] = 'ggg'
import openai
print(openai.api_key)
o = OpenAI()
print(openai.api_key)
g = GooseAI()
print(openai.api_key)
o = OpenAI()
print(openai.api_key)

------

ooo
ooo
ggg
ooo
```

This makes it annoying (impossible?) to switch back and forth between calls to OpenAI models like Babbage and GooseAI models like GPT-J in the same notebook.

```
prompt = 'The best basketball player of all time is '
args = {'max_tokens': 3, 'temperature': 0}
openai_llm = OpenAI(**args)
print(openai_llm(prompt))
gooseai_llm = GooseAI(**args)
print(gooseai_llm(prompt))
print(openai_llm(prompt))

---

Michael Jordan

Michael Jordan

InvalidRequestError: you must provide a model parameter
```

I'm pretty sure this behavior comes from the validate_environment method in the [two](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py) llm [files](https://github.com/hwchase17/langchain/blob/master/langchain/llms/gooseai.py) which despite its name seems to not just validate the environment but also change it.

**Comment by zswitten** [comment]
Actually I think the more pertinent issue (since both your GOOSE_API_KEY and OPENAI_API_KEY should be valid) is that https://github.com/hwchase17/langchain/blob/master/langchain/llms/gooseai.py overwrites `openai.api_base`.

**Comment by zswitten** [comment]
A workaround is to set `openai.api_base = 'https://api.openai.com/v1' before each call to OpenAI.

**Comment by FergusFettes** [comment]
Aha! This explains the errors I was getting on the OpenAI endpoint:
```
InvalidRequestError: you must provide a model parameter 
```
after using GooseAI!

This should be upgraded to a bug IMO.
