### ISSUE TITLE
Streaming support with ConversationChain

### ISSUE THREAD

**Issue by marcocello** [langchain-ai/langchain#11945]
### System Info

langchain          0.0.316
langserve          0.0.10
python               3.11.4 on darwin

### Who can help?

@agola11 @hwchase17 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

Langserve example here (https://github.com/langchain-ai/langserve-launch-example/blob/main/langserve_launch_example/chain.py) in which I want to use ConversationChain instead of ChatOpenAI.

server.py

    #!/usr/bin/env python
    """A server for the chain above."""

    from fastapi import FastAPI
    from langserve import add_routes

    from chain import conversation_chain

    app = FastAPI(title="My App")

    add_routes(app, conversation_chain)

    if __name__ == "__main__":
        import uvicorn

        uvicorn.run(app, host="localhost", port=8000)

chain.py
```
from langchain.llms import OpenAI`
from langchain.chains import ConversationChain
from langchain.prompts import PromptTemplate
from langchain.memory import ConversationBufferMemory

template = """Assistant is a large language model trained by OpenAI.

Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.

{history}
Human: {input}
Assistant:"""

prompt = PromptTemplate(input_variables=["history", "input"], template=template)

conversation_chain = ConversationChain(
    llm=OpenAI(temperature=0),
    prompt=prompt,
    verbose=True,
    memory=ConversationBufferMemory(),
)
```

### Expected behavior

I was expecting to have a streaming response as the ChatOpenAI behavior. It seems to me that ConversationChain doesn't support streaming response.

**Comment by dmahlow** [comment]
Are there any updates on this? Is ConversationChain not being able to be streamed from a bug or as expected? If the former, what's a good way of fixing this?

**Comment by deuscapturus** [comment]
None of the chains have implemented a stream method.  I'm investigating to see why this is so.

**Comment by seanmavley** [comment]
@deuscapturus I am seriously also considering switching. I see potential with langchain and langserve, however, both are waaay too early to be used for anything serious.

It should be stable hopefully in a year or two's time.

I've looked into Haystack, and now Llama Index, you mentioned. There's also Flowise.

I've sunk too much time into Langchain I'd wanna be careful which step I take next

**Comment by cfa532** [comment]
Here is my piece of code that actually makes Conversation chain streams. @deuscapturus is right that Langchain is a mess, even though which is much less messier that a year ago.

`class MyStreamingHandler(StreamingStdOutCallbackHandler):
    def __init__(self) -> None:
        super().__init__()

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        sys.stdout.write(token)
        sys.stdout.flush()
        #time.sleep(1)

CHAT_LLM = ChatOpenAI(temperature=0, model="gpt-4", max_tokens=2048, streaming=True,
                      callbacks=[MyStreamingHandler()])     # ChatOpenAI cannot have max_token=-1
chain = ConversationChain(llm=CHAT_LLM, memory=ConversationBufferWindowMemory(k=6), verbose=False)
chain.output_parser = StrOutputParser()`

**Comment by cfa532** [comment]
> Here is my piece of code that actually makes Conversation chain streams. @deuscapturus is right that Langchain is a mess, even though which is much less messier that a year ago.
> 
> `class MyStreamingHandler(StreamingStdOutCallbackHandler): def **init**(self) -> None: super().**init**()
> 
> ```
> def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
>     sys.stdout.write(token)
>     sys.stdout.flush()
>     #time.sleep(1)
> ```
> 
> CHAT_LLM = ChatOpenAI(temperature=0, model="gpt-4", max_tokens=2048, streaming=True, callbacks=[MyStreamingHandler()]) # ChatOpenAI cannot have max_token=-1 chain = ConversationChain(llm=CHAT_LLM, memory=ConversationBufferWindowMemory(k=6), verbose=False) chain.output_parser = StrOutputParser()`

However I am pulling my hair for a day trying to get the following code works. According to some comments, it suppose to be the right way of streaming, instead of overriding the on_llm_new_token().

**Comment by ttessarolo** [comment]
Here is my current solution to stream results to client using SSE. 
First a generator function:

```javascript
async function* chat(input, sessionId) {
  let id = 0;
  const { chain } = getConversationalChain(sessionId);  // get from cache
  const emitter = new EventEmitter();
  chain.call({
    input,
    callbacks: [
      {
        handleLLMNewToken(data) {
          emitter.emit("data", { data, id: id++, event: "text" });
        },
        handleLLMEnd(data) {
          emitter.emit("data", { event: "end" });
        },
      },
    ],
  });

  for await (const [data] of on(emitter, "data")) {
    if (data.event === "end") return;
    yield data;
  }
}
```

and then I use that function to SSE to client:
```javascript
import Fastify from "fastify";
import { FastifySSEPlugin } from "fastify-sse-v2";

fastify.get("/chat", async function (req, res) {
  const prompt = req.query.prompt;
  const sessionId = req.query.sessionId;
  res.sse(chat(prompt, sessionId));
});
``

**Comment by kevin12314** [comment]
> Here is my piece of code that actually makes Conversation chain streams. @deuscapturus is right that Langchain is a mess, even though which is much less messier that a year ago.
> 
> `class MyStreamingHandler(StreamingStdOutCallbackHandler): def **init**(self) -> None: super().**init**()
> 
> ```
> def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
>     sys.stdout.write(token)
>     sys.stdout.flush()
>     #time.sleep(1)
> ```
> 
> CHAT_LLM = ChatOpenAI(temperature=0, model="gpt-4", max_tokens=2048, streaming=True, callbacks=[MyStreamingHandler()]) # ChatOpenAI cannot have max_token=-1 chain = ConversationChain(llm=CHAT_LLM, memory=ConversationBufferWindowMemory(k=6), verbose=False) chain.output_parser = StrOutputParser()`

 I used this code and made some adjustments, finally successfully making the conversation chain streams. Here is my code.
```python
class MyStreamingHandler(StreamingStdOutCallbackHandler):
    def init(self) -> None:
        super().init()
    
    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        sys.stdout.write(token)
        sys.stdout.flush()
        #time.sleep(1)

async def process_chunks(qustion:str):
    final_result = None
    async for chunk in chain.astream(qustion):
        final_result=chunk
        print('')
        print(final_result)

CHAT_LLM = ChatOpenAI(openai_api_key="",temperature=0, model="gpt-4", max_tokens=2048, streaming=True,
    callbacks=[MyStreamingHandler()]) # ChatOpenAI cannot have max_token=-1

chain = ConversationChain(llm=CHAT_LLM, memory=ConversationBufferWindowMemory(k=6), verbose=False)
asyncio.run(process_chunks("hello. tell me something about yourself"))
```

**Comment by rhighs** [comment]
@kevin12314 well, this really doesn'y solve the problem, it's writing to stdout. If that's your goal great, but I would advise a better approach leveraging python generators so that you'll point the stream to write wherever you want it to.

**Comment by rhighs** [comment]
I hate doing this, but *SIGH* here I got a workaround that enables streaming an lllm response whilst saving stuff into a memory buffer. I came up with this after looking at how RunnableLambda is implemented and basically overriding its _transform method to let input chunks pass through the stream and then call the callback with the collected input, which is the place where you should update memory state.

This sucks, but it does the job and until someone has enough patience to work on this and comes out with a better solution for langchain itself you can use this:

```python
class RunnableCollector(RunnableLambda):
    def _transform(
        self,
        input: Iterator[Input],
        run_manager: CallbackManagerForChainRun,
        config: RunnableConfig,
        **kwargs: Any,
    ) -> Iterator[Output]:
        final: Input
        got_first_val = False
        for ichunk in input:
            yield cast(Output, ichunk)

            if not got_first_val:
                final = ichunk
                got_first_val = True
            else:
                try:
                    final = final + ichunk  # type: ignore[operator]
                except TypeError:
                    final = ichunk

        call_func_with_variable_args(
            self.func, cast(Input, final), config, run_manager, **kwargs
        )


class RunnableFilter(RunnableLambda):
    def __init__(self, filter: Callable[[Input], bool], **kwargs) -> None:
        super().__init__(func=lambda _: None, **kwargs)
        self.filter = filter

    def _transform(
        self,
        input: Iterator[Input],
        run_manager: CallbackManagerForChainRun,
        config: RunnableConfig,
        **kwargs: Any,
    ) -> Iterator[Output]:
        for ichunk in input:
            if self.filter(ichunk):
                yield ichunk


class RunnableMap(RunnableLambda):
    def __init__(self, mapping: Callable[[Input], Output], **kwargs) -> None:
        super().__init__(func=lambda _: None, **kwargs)
        self.mapping = mapping

    def _transform(
        self,
        input: Iterator[Input],
        run_manager: CallbackManagerForChainRun,
        config: RunnableConfig,
        **kwargs: Any,
    ) -> Iterator[Output]:
        for ichunk in input:
            yield self.mapping(ichunk)


def setup_chain(
    model="gpt-3.5-turbo",
) -> RunnableSerializable:
    memory = ConversationBufferMemory(memory_key="history", return_messages=True)

    def save_into_mem(input_output: Dict[str, Any]):
        message = input_output.pop("output")
        memory.save_context(input_output, {"output": message.content})
        print("\n\n2.\t", memory.load_memory_variables({}))

    chain = (
        RunnablePassthrough.assign(
            history=RunnableLambda(memory.load_memory_variables)
            | itemgetter("history"),
            dummy=RunnableLambda(lambda x: print("input?", x)),
        )
        | ChatPromptTemplate.from_messages(
            [
                ("system", SYSTEM_MESSAGE),
                MessagesPlaceholder(variable_name="history"),
                ("user", "{input}"),
            ]
        )
        | ChatOpenAI(
            model=model,
            temperature=0,
            streaming=True,
        )
    )

    chain = (
        RunnablePassthrough.assign(
            output=chain,
        )
        | RunnableFilter(
            filter=lambda chunk: type(chunk) is AddableDict
            and "output" in chunk
            or "input" in chunk
        )
        | RunnableCollector(save_into_mem)
        | RunnableFilter(
            filter=lambda chunk: type(chunk) is AddableDict
            and "output" in chunk
            and not "input" in "chunk"
        )
        | RunnableMap(mapping=lambda chunk: cast(Output, chunk["output"]))
    )

    return chain
```

NOTE: this is really focused only on streaming output consumption, I haven't tested anything else nor async transforms which shouldn't differ too much in behavior...

**Comment by ccurme** [comment]
Please see [this tutorial](https://python.langchain.com/v0.2/docs/tutorials/chatbot/) for the recommended way to manage memory in chat applications. There is a section on streaming [here](https://python.langchain.com/v0.2/docs/tutorials/chatbot/#streaming). Will close this issue but can re-open if issues remain.
