### ISSUE TITLE
DOC: There is no documentation about how to interrupt the streaming generation once the model started generation.

### ISSUE THREAD

**Issue by TheJerryChang** [langchain-ai/langchain#11959]
### Issue with current documentation:

Currently in the streaming documentation page, there is no guidance on how to interrupt the streaming once the model start generation. I want to implement the same "Stop generation" button functionality in chatGPT web, which should stopped the streaming generation. I tried to use try except but it is not working.

### Idea or request for content:

There is no documentation about how to interrupt the streaming generation once the model started generation. Even an error happens during new token generation, the program will not stop running but raise an error. How to stop the generation if an error happened?

**Comment by TheJerryChang** [comment]
@dosu-bot

I have the following custom stream handler:
`class MyCustomHandler(StreamingStdOutCallbackHandler):
    def __init__(self, uuid, global_info, socketio):
        self.uuid = uuid
        self.global_info = global_info
        self.socketio = socketio
    def on_llm_new_token(self, token: str, **kwargs) -> None:
        res = {
            "text": token
        }
        pr
        self.socketio.emit(self.uuid, res, namespace='/chat')
    def on_llm_error(self, error: BaseException, **kwargs) -> None:
        print("I detect ", error)`

Where based on your reply, I should see "I detect error" in the console, but I still repeatedly receiving "Error in MyCustomHandler.on_llm_new_token callback: name 'pr' is not defined" instead.

The chat model is defined in this way:
`if stream:
            llm = AzureChatOpenAI(
                openai_api_base=azure_api_base,
                openai_api_type=azure_api_type,
                openai_api_key=azure_api_key,
                openai_api_version=azure_api_version,
                model_name=model_name,
                temperature=temperature,
                deployment_name=deployment_name,
                streaming=stream,
                callbacks=[MyCustomHandler(uuid=callbacks_info["uuid"], global_info=callbacks_info["global_info"], socketio=callbacks_info["socketio"])] 
            )`

So how could I interrupt the streaming?

**Comment by TheJerryChang** [comment]
@dosu-bot
How to implement the actual code to stop the streaming? I tried to add "return" in the except but it still keeps print "I detect error", the "pr" is leaved there by purpose to through an exception:
try:
            res = {
                "text": token
            }
            pr
 except:
            print("I detect error")
            return

**Comment by TheJerryChang** [comment]
@dosu-bot
With the code above, it is still not stopping the streaming, can you assign question to others for help

**Comment by Osten** [comment]
Interrupting generation is just a basic use case, and I cannot find anywhere how to do it. This is just a bot chat on how to catch errors during generation. I just don't want to interrupt the whole app every time I want to stop the inference, but I cannot find anywhere how?

**Comment by hamaadtahiir** [comment]
yes, I need help on the same issue. I dont know of any way to interrupt the token generation process in langchain esp while using llama cpp python

**Comment by pai4451** [comment]
interested the solution

**Comment by Osten** [comment]
I found a solution that works if you capture the keyboard interrupt, then
it can be cancelled in command prompt using ctrl+c. But if you want to make
a gradio interface or something I don't know how to do it.

**Comment by TheJerryChang** [comment]
Hi guys sorry for the late reply. So I found a solution by using langchain LCEL interface instead of the general writing. Their documentation is here (everyone know it is not a good documentation :D): https://python.langchain.com/docs/expression_language/interface#stream.

So once you switch to LCEL and use chain.stream(), you could eventually interrupt the streaming process by raising an exception during the iteration. For example in my code:
<
try:
            for token in chain.stream({"total_days": user_travel_days, "route": route, "comments": comments, "foods": food_list, "hotels": hotel_list}):
                if user_stop_flags.get_item(uuid):
                    raise RuntimeError("User stopped streaming")
                if check_special_char(token.content):
                    continue
                if continue_output == False:
                    if is_valid_char(token.content):
                        continue_output = True
                    else:
                        continue
                content += token.content + ""
                res = {
                    "text": token.content
                }
                socketio.emit(uuid, res, namespace='/chat')
        except RuntimeError as e:
            print("User stopped generation")
        except:
            error_occur = True
>
And the variable "user_stop_flags" is a global dic variable to track if a user choose to stop the streaming. This is my workaround and so hope it could help you out :D

**Comment by hamaadtahiir** [comment]
@TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain

**Comment by shessenauer** [comment]
+1 on above question. Very surprised there is not more docs/examples of this use case.

**Comment by TheJerryChang** [comment]
> @TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain

For my use case, Im using Chat model and did not try with completion process. How do you do the streaming? Did you use chain.stream()? I personally think as long as it supports calling chain.stream() to proceed the streaming, it then could be interrupted by raising an exception during the iteration

**Comment by Spider-netizen** [comment]
> @TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain

Did you solve this? It seems I'm facing the same issue.



> > @TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain
> 
> For my use case, Im using Chat model and did not try with completion process. How do you do the streaming? Did you use chain.stream()? I personally think as long as it supports calling chain.stream() to proceed the streaming, it then could be interrupted by raising an exception during the iteration

I'm using `.astream_events ` method of `AgentExecutor`. Trying to figure what's the way to stream an agent response but also be able to cancel it before it finishes generating.

**Comment by calls9-amirbraham** [comment]
Any solutions please ?

**Comment by Emmaccen** [comment]
it's **2025** and I'm still here trying to get wind of a way around this for months. Still can't find anything from the Docs that solves this. It's an essential requirement.

Anyone got a fix or hack yet?
