### ISSUE TITLE
Issue: <ConversationBufferWindowMemory doesn't work with db based chat history>

### ISSUE THREAD

**Issue by Kuramdasu-ujwala-devi** [langchain-ai/langchain#11958]
### Issue you'd like to raise.

I'm experimenting with natural language to SQL conversion using SQLDatabaseChain and SQLDatabaseAgent. In this experiment, I'm utilizing the ConversationBufferWindowMemory. However, I've encountered an issue where the memory is not functioning as expected. When I ask a question related to a previous question or answer, the chain/agent isn't handling memory and instead responds independently of the question asked based on memory.
How to fix this 
@dosubot

**Comment by Kuramdasu-ujwala-devi** [comment]
Can you give code how to add memory (ConversationBufferWindowMemory ) to SQLDatabasechain and Sql agent with proper template to

**Comment by Kuramdasu-ujwala-devi** [comment]
@dosubot
Getting this erro while trying implement the code which you gave 
Error - from langchain.prompts import FewShotPromptTemplate, MessagesPlaceholder, SystemMessage, HumanMessagePromptTemplate, ChatPromptTemplate

ImportError: cannot import name 'SystemMessage' from 'langchain.prompts'

**Comment by sbisen** [comment]
@dosu-bot when I add multiple table to the SQLDatabase, chain/agent isn't handling memory, looks like it is not saving the chat history, 
Here is my code:
    sql_db_chain = load_few_shot_chain(llm, db, examples)
    m1 = ConversationBufferWindowMemory(k=4,return_messages=True)
    chat = m1.load_memory_variables({})['history']
    prompt = chat_prompt.format(info=table_info, history=chat, input=question)
    answer = sql_db_chain(prompt)
    answer_str = str(answer) if not isinstance(answer, str) else answer
    m1.save_context({'input': question}, {'answer': answer_str})
