### ISSUE TITLE
Issue: TypeError: TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'

### ISSUE THREAD

**Issue by ulyaatsaniya** [langchain-ai/langchain#11961]
### Issue you'd like to raise.

I got this error when I built a ChatBot with Langchain using VertexAI. I'm seeing this error and couldn't find any details so far.

File /opt/conda/lib/python3.10/site-packages/langchain/llms/vertexai.py:100, in completion_with_retry.<locals>._completion_with_retry(*args, **kwargs)
     98 @retry_decorator
     99 def _completion_with_retry(*args: Any, **kwargs: Any) -> Any:
--> 100     return llm.client.predict(*args, **kwargs)

TypeError: TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'

**Comment by ulyaatsaniya** [comment]
Hi, it still not working

I was calling it with the retriever

from langchain.retrievers import GoogleVertexAISearchRetriever, GoogleVertexAIMultiTurnSearchRetriever
import vertexai
from langchain.llms import VertexAI
import langchain

vertexai.init(project=PROJECT_ID, location=REGION)
llm = VertexAI(model_name=MODEL)

retriever = GoogleVertexAIMultiTurnSearchRetriever(
    project_id=PROJECT_ID,
    location_id=DATA_STORE_LOCATION,
    data_store_id=DATA_STORE_ID,
    # max_extractive_answer_count=3,
    # get_extractive_answers=True
)

prompt = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

qa_chain = RetrievalQA.from_llm(
    llm=llm, prompt=prompt, retriever=retriever, return_source_documents=True
)

query = "How to get insurance benefit?"
results = qa_chain({"query": query})

**Comment by ulyaatsaniya** [comment]
@desu-bot

Still doesn't work

**Comment by angussaw** [comment]
I am encountering the same issue

llm = VertexAI(temperature=0, model_name="text-bison@001")
my_text = "What day comes after Friday?"
llm(my_text)

TypeError: _TextGenerationModel.predict() got an unexpected keyword argument 'candidate_count'

What version of langchain are you using?

**Comment by ulyaatsaniya** [comment]
Hi @angussaw 
I'm using langchain version 0.0.317 released on Oct 18, 2023

**Comment by angussaw** [comment]
downgrading to 0.0.310 works for me

**Comment by ulyaatsaniya** [comment]
Yes, but GoogleVertexAIMultiTurnSearchRetriever cannot be imported on version above 0.0.310

**Comment by SaurabhTayde** [comment]
@ulyaatsaniya 

Was facing same issue while working with langchain, vertexAI, Palm-2 and chromaDB. I downgraded 'google-cloud-aiplatform' and 'langchain' and it worked for me.  Downgraded to following:

google-cloud-aiplatform==1.34.0
langchain==0.0.310

 If langchain downgrading is not feasible for you (as you mentioned earlier), try downgrading just 'google-cloud-aiplatform'.

**Comment by wnmurphy** [comment]
Same error, it's an update in the `VertexAI` class to support new [features](https://github.com/googleapis/python-aiplatform/commit/587df744e2b6c4b3e1a96ff69937697fe80a97be#diff-d590796a957403a21f44437451d471ad5138a0fa138bd996c102d832bc9a9806R1618) from Google's AI Platform [1.35.0](https://github.com/googleapis/python-aiplatform/releases/tag/v1.35.0)

Bumping `google-cloud-aiplatform==1.35.0` resolved issue for me.
