### ISSUE TITLE
how to connect to sql view in database  

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#11980]
### System Info

latest version of langchain. python=3.11.4

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

How to connect to SQL view in the database, instead of using the all the tables from the DB, as the DB is huge(6Gb), I'm unable to get any out a correct output, I'm getting token error and when it is performing any join its unable to fetch a correct answer, but when I using a selected table its working efficiently in terms of accuracy and time taking. 

Can I get a appropriate method by which I can deal with the huge data without getting token or parser errors.
and how to work with the SQL views in the database.

here is the code for the connection string I have tried which includes the tables and its working fine,  

 from urllib.parse import quote_plus
driver = 'ODBC Driver 17 for SQL Server'
host = '########'
user = '#####'
database = 'HR_Git'
password = '#########' 
encoded_password = quote_plus(password)  

db = SQLDatabase.from_uri(f"mssql+pyodbc://{user}:{encoded_password}@{host}/{database}?driver={quote_plus(driver)}", include_tables = ['EGV_emp_departments'], sample_rows_in_table_info=2)

Thank you.

### Expected behavior

How to work with the SQL views inside the database and  way to avoid token and parser error.

**Comment by HassanA01** [comment]
This issue seems interesting to me! Do you think it would be feasible to finish this within a month?

**Comment by jyoti194** [comment]
> This issue seems interesting to me! Do you think it would be feasible to finish this within a month?

Yes it can be

**Comment by virux99** [comment]
how can we access views of sql with langchain? did anyone manage to do this?

**Comment by akesh1235** [comment]
Hello All,
To connect to and work with SQL views in the LangChain framework, you just need to activate a argument `view_support=True` in SQLDatabase

```
from langchain.llms import  SQLDatabase

# Connect to the database
db = SQLDatabase.from_uri( 	
    "mysql+pymysql://{db_user}:{db_password}@{db_host}/db_name}", 	
    include_tables=['Track'], 	                      
    view_support = True,
)```

**Comment by vishalpatidar00789** [comment]
even this din work for me.

**Comment by NisaarAgharia** [comment]
i have created SQL agent , it is able to get the view i have created , but when doing get table info, nothing is returned and the Flow for agent is stuck.

@dosubot

**Comment by anthobio23** [comment]
@akesh1235 your solution this correct. thanks

**Comment by jyoti194** [comment]
@vishalpatidar00789 are you using SQLDatabaseChains? view_support=True workers with that.

**Comment by madhubandru** [comment]
> Hello All, To connect to and work with SQL views in the LangChain framework, you just need to activate a argument `view_support=True` in SQLDatabase
> 
> ```
> from langchain.llms import SQLDatabase
> 
> # Connect to the database
> db = SQLDatabase.from_uri( 	
>     "mysql+pymysql://{db_user}:{db_password}@{db_host}/db_name}", 	
>     include_tables=['Track'], 	                      
>     view_support = True,
> )```
> ```

@akesh1235 Is it possible to allow SQL DB engine to access only view but not the tables?

**Comment by JACKSPARROWbts** [comment]
@madhubandru  Hi madhu , can you tell me how did you managed to allows access to langchain only to views not tables ?

**Comment by JACKSPARROWbts** [comment]
@madhubandru  Hi madhu , can you tell me how did you managed to allows access to langchain only to views not tables ?

**Comment by madhubandru** [comment]
> [@madhubandru](https://github.com/madhubandru) Hi madhu , can you tell me how did you managed to allows access to langchain only to views not tables ?

@JACKSPARROWbts 

In the below code, view_support = True enables access to views and by default it will have access to tables.
Just to allow access to only views, pass the views names in `include_tables`. 

```
from langchain.llms import SQLDatabase
from sqlalchemy import create_engine, inspect

#Get all Views names
db_engine = create_engine("mysql+pymysql://{db_user}:{db_password}@{db_host}/db_name}")
view_inspector = inspect(db_engine)
all_views = view_inspector.get_view_names()

# Connect to the database
db = SQLDatabase.from_uri( 	
    "mysql+pymysql://{db_user}:{db_password}@{db_host}/db_name}", 	
    include_tables=all_views, 	                      
    view_support = True,
)
```
