### ISSUE TITLE
ParentDocumentRetriever: parent_splitter and ids are incompatible

### ISSUE THREAD

**Issue by pprados** [langchain-ai/langchain#11982]
### System Info

**description**
With parent_splitter, it's not possible to know the number of IDs before the split.
So, it's not possible to know the ID of each fragment.
Then, it's not possible to manage the life cycle of the fragment because it's impossible to know the list of IDs associated with the original big document.

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.embeddings import OpenAIEmbeddings
from langchain.retrievers import ParentDocumentRetriever
from langchain.schema import Document
from langchain.storage import InMemoryStore
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores.chroma import Chroma

vectorstore = Chroma(
    collection_name="full_documents",
    embedding_function=OpenAIEmbeddings()
)
store = InMemoryStore()

docs = [Document(page_content=txt, metadata={"id": id}) for txt, id in [("aaaaaa", 1), ("bbbbbb", 2)]]
ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=store,
    id_key="id",
    parent_splitter=RecursiveCharacterTextSplitter(
        chunk_size = 2,
        chunk_overlap  = 0,
        length_function = len,
        add_start_index = True,
    ),
    child_splitter=RecursiveCharacterTextSplitter(
        chunk_size = 1,
        chunk_overlap  = 0,
        length_function = len,
        add_start_index = True,
    ),
).add_documents(docs,ids=[doc.metadata["id"] for doc in docs])
```
Produce:
```
ValueError: Got uneven list of documents and ids. If `ids` is provided, should be same length as `documents`.
```

### Expected behavior

No error.

**Comment by eyurtsev** [comment]
@pprados That part of the interface doesn't make sense. Not sure of a good solution right now, but I don't think that a parent splitter should be allowed as an argument

**Comment by pprados** [comment]
@eyurtsev 
I propose a new implementation of the same idea.
See my full response in pull-request number [11968](https://github.com/langchain-ai/langchain/pull/11968).

I started proposing preliminary pull-requests, to enrich lanchain before eventually accepting my proposal.
- [Adds an in-memory implementation of RecordStore](https://github.com/langchain-ai/langchain/pull/13200)
- [Add a Wrapper vectorstore, compatible with SelfQueryRetriever](https://github.com/langchain-ai/langchain/pull/13190)
- [Add SQLDocStore](https://github.com/langchain-ai/langchain/pull/13181)

I can't valide one pull-request, because of a [lint bug](https://github.com/langchain-ai/langchain/actions/runs/6826771623/job/18567408066) in code that is not mine.

**Comment by pprados** [comment]
@eyurtsev
A complet new implementation is in [pull-request 13910](https://github.com/langchain-ai/langchain/pull/13910)
