### ISSUE TITLE
Add Alpha Vantage API Tool

### ISSUE THREAD

**Issue by adam-badar** [langchain-ai/langchain#11994]
### Feature request

We propose the integration of a new tool into Langchain that will provide comprehensive support for queries on the AlphaVantage Trading API. AlphaVantage offers a wide range of financial data and services, and this integration will enhance Langchain's capabilities for financial data analysis.

Here is the list of AlphaVantage APIs that will be integrated into the new tool:

- [TIME_SERIES_DAILY](https://www.alphavantage.co/documentation/#daily)
- [TIME_SERIES_WEEKLY](https://www.alphavantage.co/documentation/#weekly)
- [Quote Endpoint](https://www.alphavantage.co/documentation/#latestprice)
- [Search Endpoint](https://www.alphavantage.co/documentation/#symbolsearch)
- [Market News & Sentiment](https://www.alphavantage.co/documentation/#news-sentiment)
- [Top Gainers, Losers, and Most Actively Traded Tickers (US Market)](https://www.alphavantage.co/documentation/#gainer-loser)

### Motivation

The integration of AlphaVantage Trading API support in Langchain will provide users with access to a wealth of financial data, enabling them to perform in-depth analysis, develop trading strategies, and make informed financial decisions, all with real-time information

### Your contribution

I am a University of Toronto Student, working in a group and plan to submit a PR for this issue in November

**Comment by aajaleel** [comment]
@dosubot we updated the feature request, can you take a look again and provide any feedback?

**Comment by devstein** [comment]
@aajaleel As of now, Dosu only responds to the issue author 😄 

Dosu isn't great at implementing features that require external docs yet, but try it out and see! It usually does a good job of finding reference classes within the codebase.

 Let me know if you have feedback or ideas!

**Comment by aajaleel** [comment]
@devstein I was not aware, thank you for letting me know Devin! We'll definitely get started and check in with Dosu along the way. I'll keep you posted about how it goes, and please also share any suggestions you have as well!

**Comment by adam-badar** [comment]
@dosu-bot We are trying to update the libs/langchain/langchain/utilities/alpha_vantage.py file. However we are getting the following error when running the file: ImportError: cannot import name 'timeout' from partially initialized module 'asyncio' (most likely due to a circular import). 

Is there another way we can test our changes? What is the protocol for this?
