### ISSUE TITLE
KayAiRetriever: without metadata filtering, wrong results

### ISSUE THREAD

**Issue by olgadk7** [langchain-ai/langchain#12008]
### System Info

Hello! Even though [API](https://api.python.langchain.com/en/latest/retrievers/langchain.retrievers.kay.KayAiRetriever.html) mentions a metadata param, it's not found in [code](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/kay.py#L9). 

Without metadata filtering, querying “Tell me about the returns of Palantir Technologies Inc.” returns docs with 'company_name': 'ETSY INC'.

Thank you

### Who can help?

@eyurtsev? 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.retrievers import KayAiRetriever
retriever = KayAiRetriever.create(dataset_id="company", data_types=["10-K"], num_contexts=1)
retriever.get_relevant_documents(“Tell me about the returns of Palantir Technologies Inc.?")

### Expected behavior

[Document(page_content="Company Name: ETSY INC \n Company Industry: SERVICES-BUSINESS SERVICES, NEC \n Form Title: 10-K 2020-FY \n Form Section: Risk Factors \n Text: Any events causing ... abroad.", metadata={'chunk_type': 'text', 'chunk_years_mentioned': [], 'company_name': 'PALANTIR TECHNOLOGIES INC', 'company_sic_code_description': 'SERVICES-BUSINESS SERVICES, NEC', 'data_source': '10-K', 'data_source_link': 'https://www.sec.gov/Archives/edgar/data/1370637/000137063721000012', 'data_source_publish_date': '2020-01-01T00:00:00Z', 'data_source_uid': '0001370637-21-000012', 'title': 'ETSY INC |  10-K 2020-FY '})]

**Comment by plv** [comment]
Hi @olgadk7 , we had an issue on our backend at Kay.ai. It should be fixed now, I retried your query and got an expected result

```python
>>> from langchain.retrievers import KayAiRetriever

>>> retriever = KayAiRetriever.create(dataset_id="company", data_types=["10-K"], num_contexts=1)

>>> retriever.get_relevant_documents("Tell me about the returns of Palantir Technologies Inc.?")

[Document(page_content='Company Name: PALANTIR TECHNOLOGIES INC \n Company Industry: SERVICES-PREPACKAGED SOFTWARE \n Form Title: 10-K 2022-FY \n Form Section: Risk Factors \n Text: Add: employer payroll taxes related to stock based compensation 17,156 106,283 Adjusted income from operations $ 420,753 $ 473,452 68 Components of Results of Operations Revenue We generate revenue from the sale of subscriptions to access our software in our hosted environment along with ongoing O&M services ("Palantir Cloud"), software subscriptions in our customers\' environments with ongoing O&M services ("On Premises Software"), and professional services.Palantir Cloud Our Palantir Cloud subscriptions grant customers the right to access the software functionality in a hosted environment controlled by Palantir and are sold together with stand ready O&M services, as further described below.We promise to provide continuous access to the hosted software throughout the contract term.Revenue associated with Palantir Cloud subscriptions is generally recognized over the contract term on a ratable basis, which is consistent with the transfer of control of the Palantir services to the customer.On Premises Software Sales of our software subscriptions grant customers the right to use functional intellectual property, either on their internal hardware infrastructure or on their own cloud instance, over the contractual term and are also sold together with stand ready O&M services.', metadata={'chunk_type': 'text', 'chunk_years_mentioned': [], 'company_name': 'PALANTIR TECHNOLOGIES INC', 'company_sic_code_description': 'SERVICES-PREPACKAGED SOFTWARE', 'data_source': '10-K', 'data_source_link': 'https://www.sec.gov/Archives/edgar/data/1321655/000132165523000011', 'data_source_publish_date': '2022-01-01T00:00:00Z', 'data_source_uid': '0001321655-23-000011', 'title': 'PALANTIR TECHNOLOGIES INC |  10-K 2022-FY '})]
```

**Comment by olgadk7** [comment]
Hi @plv, thank you.
 
Yes, it works for Palantir now. Unfortunately, when i do the same for SHOPIFY INC, with num_contexts=7, 6 of the docs have 'company_name': 'ETSY INC', and 1, 'COTY INC'.  

And filtering the returned documents based on the metadata after they have been retrieved is not really an economical solution, as suggested by @dosu-bot.

**Comment by olgadk7** [comment]
good catch, but why does it return ETSY, instead of error? 

and, what are you plans / timeline for metadata filtering (eg by 'company_name'), and ordering (eg by 'data_source_publish_date')?

ty!

**Comment by plv** [comment]
@olgadk7 Sorry for the late reply, was out on Friday and missed your post :) 

>good catch, but why does it return ETSY, instead of error?

Kind of how if you type in random nonsense into Google, you still somehow get results. We attempt a "best effort" search. It is more of "neural search" and less "rigid database".

>and, what are you plans / timeline for metadata filtering (eg by 'company_name'), and ordering (eg by 'data_source_publish_date')?

Right now we actually do smart filtering automatically. If you mention a company name that exists in our DB (i.e. they have filed a 10k/10q) then we filter on that company name behind the scenes. 

Would you prefer explicit filtering support in the API?

P.S. If you have any more questions feel free to reach out to our support email -- hello@kay.ai :)

**Comment by olgadk7** [comment]
I would prefer explicit filtering. Thank you, closing!
