### ISSUE TITLE
TypeError: UnstructuredYoloXModel.initialize() got an unexpected keyword argument 'extract_images_in_pdf' while running Semi_structured_multi_modal_RAG_LLaMA2.ipynb

### ISSUE THREAD

**Issue by Sanchita333** [langchain-ai/langchain#12010]
### System Info

Hi, I am facing an issue when attempting to run the "Semi_structured_multi_modal_RAG_LLaMA2.ipynb" notebook from the cookbook.
![image](https://github.com/langchain-ai/langchain/assets/91419837/0a29dd3e-40a1-4264-8e07-bf0edc63b882)
**Environment Details**
Langchain Version: 0.0.317
I would appreciate any assistance in resolving this issue. Thank you.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

TypeError: UnstructuredYoloXModel.initialize() got an unexpected keyword argument 'extract_images_in_pdf'

### Expected behavior

The notebook should run without any issues and produce the expected output as documented in the cookbook

**Comment by Sanchita333** [comment]
The code i am using from https://github.com/langchain-ai/langchain/blob/master/cookbook/Semi_structured_multi_modal_RAG_LLaMA2.ipynb
raw_pdf_elements = partition_pdf(filename=path+"LLaVA.pdf",
                                 # Using pdf format to find embedded image blocks
                                 extract_images_in_pdf=True,
                                 # Use layout model (YOLOX) to get bounding boxes (for tables) and find titles
                                 # Titles are any sub-section of the document 
                                 infer_table_structure=True, 
                                 # Post processing to aggregate text once we have the title 
                                 chunking_strategy="by_title",
                                 # Chunking params to aggregate text blocks
                                 # Attempt to create a new chunk 3800 chars
                                 # Attempt to keep chunks > 2000 chars 
                                 # Hard max on chunks
                                 max_characters=4000, 
                                 new_after_n_chars=3800, 
                                 combine_text_under_n_chars=2000,
                                 image_output_dir_path=path)

**Comment by giulioco** [comment]
having the same issue

**Comment by harshit-wadhwani** [comment]
I am having the same issue in 
`def embedding_creation(filename, subjectname):
    persist_directory = f"./{subjectname}"
    loader = UnstructuredPDFLoader(filename, strategy = 'hi_res')
    documents = loader.load()`

**Comment by Manikanta5112** [comment]
same issue here

**Comment by pedropivotto** [comment]
same issue here

**Comment by akionux** [comment]
I had the same issue but resolved by upgrading `unstructured-inference==0.7.10`.
`extract_images_in_pdf` parameter was [introduced](https://github.com/Unstructured-IO/unstructured-inference/commit/1cf12e90abda720086bcf03d1aefcbaaeef4fc4f#diff-c6d89eb358afac0d0b649e57e180d11365b35a9ae6c2a6ca64c49294b49fb942R473) in `0.7.10`.

**Comment by luckylwk** [comment]
> unstructured-inference==0.7.10

This worked for me! 👍
