### ISSUE TITLE
Bedrock chain not working with AsyncCallbackHandler

### ISSUE THREAD

**Issue by davide-pet** [langchain-ai/langchain#12035]
### System Info

Name: langchain
Version: 0.0.317

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [X] Async

### Reproduction

Hello @agola11
I got this runtime warning:
RuntimeWarning: coroutine 'AsyncCallbackManagerForLLMRun.on_llm_new_token' was never awaited
  run_manager.on_llm_new_token(chunk.text, chunk=chunk)

I try to stream over a websocket the generated tokens. When I try to add a AsyncCallbackHandler to manage this streaming and run acall the warning occurs and nothing is streamed out.

class StreamingLLMCallbackHandler(AsyncCallbackHandler):

    def __init__(self, websocket):
        self.websocket = websocket
        self.intermediate_result = []

    async def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        self.intermediate_result.append(token)
        await self.websocket.send_text(token)

    async def on_llm_end(self, token: str, **kwargs: Any) -> None:
        await self.websocket.send_text("[END]")

stream_handler = StreamingLLMCallbackHandler()

model_kwargs = {
        "max_tokens_to_sample": 8000,
        "temperature": 0.7,
        # "top_k": 250,
        # "top_p": 1,
        "stop_sequences" : ['STOP_LLM']
        }

llm = Bedrock(
        client=bedrock,
        model_id="anthropic.claude-v2",
        # provider_stop_sequence_key_name_map={'anthropic': 'stop_sequences'},
        streaming=True,
        callbacks=[stream_handler],
        model_kwargs=model_kwargs
        )

prompt_template = f"""
Human:
{{context}} {{question}}
Assistant:"""

PROMPT = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
chain_type_kwargs = {"prompt": PROMPT}

pinecone.init(api_key=PINECONE_API_KEY, environment=PINECONE_API_ENV)
chat_vectorstore = Pinecone.from_existing_index(index_name='intelligencechat1', embedding= OpenAIEmbeddings(openai_api_key= OPENAI_API_KEY), namespace='146')

chain = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type="stuff",
            return_source_documents=True,
            chain_type_kwargs=chain_type_kwargs,
            retriever=chat_vectorstore.as_retriever(search_kwargs={'k' : 4}),)

query = 'summarize'
result = await chain.acall(({"query": query}))

### Expected behavior

The expected behavior is that each token is streamed sequentially over the websocket.
the chain work in syncronous mode without 'acall'

**Comment by davide-pet** [comment]
doesn't look like  a helpful answer.

**Comment by DLOVRIC2** [comment]
Running into the same issue.

> 
> I got this runtime warning:
> RuntimeWarning: coroutine 'AsyncCallbackManagerForLLMRun.on_llm_new_token' was never awaited
> run_manager.on_llm_new_token(chunk.text, chunk=chunk)
> 

This is because the invoke_stream methods are not async so the run manager can't be awaited.

Adding async methods to Bedrock is vital for production chatbots powered by Bedrock and Langchain

**Comment by hteeyeoh** [comment]
Hitting the same issue. Does it mean that currently Bedrock did not support AsyncCallbackHandler for streaming?

**Comment by DLOVRIC2** [comment]
@hteeyeoh  true.

I've made updates to allow for async streaming. Works for me, I'll add some tests and open a PR tomorrow

**Comment by hteeyeoh** [comment]
Cool. Thanks for your response

**Comment by DLOVRIC2** [comment]
@davide-pet 
@hteeyeoh 

I have just created a pull request to add this functionality

https://github.com/langchain-ai/langchain/pull/12477

Feel free to pull that fork before it gets merged if you are in a hurry to use it. We've used this in the production last week and its working quite nicely.

WIth this, you are able to do something like:

```
import boto3
import asyncio
import langchain
from langchain.llms.base import LLM
from langchain.llms.bedrock import Bedrock
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.callbacks import AsyncIteratorCallbackHandler

langchain.debug = True

bedrock_client = boto3.client("bedrock-runtime")
llm = Bedrock(
    client=bedrock_client,
    model_id="anthropic.claude-v2",
    streaming=True,
    callbacks=[AsyncIteratorCallbackHandler()],
)
prompt = PromptTemplate.from_template("Human: Hey!\n\nAssistant: Hey!")
chain = LLMChain(llm=llm, prompt=prompt)


async def runner():
    response = await chain.acall({"input": "Hey, how are you?"})
    print(f"This is the response: {response}")
    return response


async def chat():
    task = asyncio.create_task(runner())
    async for chunk in llm.callbacks[0].aiter():
        yield chunk

    await task


asyncio.run(chat())

```

Hope that helps!

**Comment by hteeyeoh** [comment]
> @davide-pet @hteeyeoh
> 
> I have just created a pull request to add this functionality
> 
> #12477
> 
> Feel free to pull that fork before it gets merged if you are in a hurry to use it. We've used this in the production last week and its working quite nicely.
> 
> WIth this, you are able to do something like:
> 
> ```
> import boto3
> import asyncio
> import langchain
> from langchain.llms.base import LLM
> from langchain.llms.bedrock import Bedrock
> from langchain.chains import LLMChain
> from langchain.prompts import PromptTemplate
> from langchain.callbacks import AsyncIteratorCallbackHandler
> 
> langchain.debug = True
> 
> bedrock_client = boto3.client("bedrock-runtime")
> llm = Bedrock(
>     client=bedrock_client,
>     model_id="anthropic.claude-v2",
>     streaming=True,
>     callbacks=[AsyncIteratorCallbackHandler()],
> )
> prompt = PromptTemplate.from_template("Human: Hey!\n\nAssistant: Hey!")
> chain = LLMChain(llm=llm, prompt=prompt)
> 
> 
> async def runner():
>     response = await chain.acall({"input": "Hey, how are you?"})
>     print(f"This is the response: {response}")
>     return response
> 
> 
> async def chat():
>     task = asyncio.create_task(runner())
>     async for chunk in llm.callbacks[0].aiter():
>         yield chunk
> 
>     await task
> 
> 
> asyncio.run(chat())
> ```
> 
> Hope that helps!

Thanks. Will give it a try

**Comment by hteeyeoh** [comment]
hi @DLOVRIC2 one small curious, with your changes above means that im also able to stream the output by just calling the chain using ainvoke? like chain.ainvoke?

**Comment by khang-it-vn** [comment]
Hello there, I had the same issue, and I fixed that:

from typing import Any
from langchain_core.callbacks import AsyncCallbackHandler

class BedrockAsyncCallbackHandler(AsyncCallbackHandler):
    
    def __init__(self, instance_callback):
        self.__instance_callback = instance_callback

    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        status = self.__instance_callback.client_state.name
        if status == 'CONNECTED':
            try:
                await self.__instance_callback.send_text(token)
                print(token)
            except RuntimeError as e:
                print(f"Error sending data: {e}")
                
    async def on_llm_error(self, error: BaseException, **kwargs: Any) -> Any:
        reason = kwargs.get("reason")
        if reason == "GUARDRAIL_INTERVENED":
            print(f"Guardrails: {kwargs}")

# Link ref: https://python.langchain.com/docs/integrations/llms/bedrock

You can try that, it might work for you.

**Comment by hteeyeoh** [comment]
> Hello there, I had the same issue, and I fixed that:
> 
> from typing import Any from langchain_core.callbacks import AsyncCallbackHandler
> 
> class BedrockAsyncCallbackHandler(AsyncCallbackHandler):
> 
> ```
> def __init__(self, instance_callback):
>     self.__instance_callback = instance_callback
> 
> async def on_llm_new_token(self, token: str, **kwargs) -> None:
>     status = self.__instance_callback.client_state.name
>     if status == 'CONNECTED':
>         try:
>             await self.__instance_callback.send_text(token)
>             print(token)
>         except RuntimeError as e:
>             print(f"Error sending data: {e}")
>             
> async def on_llm_error(self, error: BaseException, **kwargs: Any) -> Any:
>     reason = kwargs.get("reason")
>     if reason == "GUARDRAIL_INTERVENED":
>         print(f"Guardrails: {kwargs}")
> ```
> 
> # Link ref: https://python.langchain.com/docs/integrations/llms/bedrock
> You can try that, it might work for you.

Thanks @khang-it-vn . It is working once they enable it in langchain. Recent releases was working fine with it.
