### ISSUE TITLE
Add Async _acall and _astream to Bedrock

### ISSUE THREAD

**Issue by davide-pet** [langchain-ai/langchain#12054]
### Feature request

Currently Bedrock and BedrockChat models do not sypport async calls and streaming.
it would be very useful to have working ChatOpenAI methods like _acall and _astream in Bedrock llms too so that we can use Claude2 and other Bedrock Models in production easily

### Motivation

without async functionalities it is hard to build production level chatbots using Bedrock models, including claude2 which is one of the most desired models

### Your contribution

I am trying myself, but I am having difficulties. If someone can help, it would be very appreciated by many,

**Comment by davide-pet** [comment]
not a useful answer

**Comment by baskaryan** [comment]
added in https://github.com/langchain-ai/langchain/pull/12477
