### ISSUE TITLE
The LCEL memory example returns KeyError

### ISSUE THREAD

**Issue by sradu** [langchain-ai/langchain#12057]
### System Info

langchain==0.0.319, mac, python 3.10

### Who can help?

@hwchase17 @agola11 

I'm trying to use this exact example from: https://python.langchain.com/docs/expression_language/cookbook/memory

```
  model = ChatOpenAI()
  prompt = ChatPromptTemplate.from_messages([
      ("system", "You are a helpful chatbot"),
      MessagesPlaceholder(variable_name="history"),
      ("human", "{input}")
  ])

  memory = ConversationBufferMemory(return_messages=True)

  memory.load_memory_variables({})

  chain = RunnablePassthrough.assign(
      memory=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
  ) | prompt | model

  inputs = {"input": "hi im bob"}
  response = chain.invoke(inputs)
```

and getting:
```
  File "/Users/name/.pyenv/versions/3.10.10/lib/python3.10/site-packages/langchain/schema/prompt_template.py", line 60, in <dictcomp>
    **{key: inner_input[key] for key in self.input_variables}
KeyError: 'history'
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Please run the code above.

### Expected behavior

To have it work like the documentation.

**Comment by sradu** [comment]
I can't believe I spent two hours on this. The typo is:

```
  chain = RunnablePassthrough.assign(
      memory=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
      ^^^ this should be history
  ) | prompt | model
```

**Comment by juanluisrto** [comment]
I owe you two hours @sradu

**Comment by rtomaf** [comment]
The docs (https://python.langchain.com/docs/expression_language/cookbook/memory) should be corrected:

FROM:

chain = RunnablePassthrough.assign(
    memory=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
) | prompt | model

TO

chain = RunnablePassthrough.assign(
    history=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
) | prompt | model

**Comment by majumba** [comment]
caught me out as well - thankyou!!

**Comment by RaedShabbir** [comment]
Would you mind sharing how to best save and load inputs and outputs inside the LCEL? 

Or do we have to manually do this outside? 

Thank you!

**Comment by usersina** [comment]
@RaedShabbir maybe I can share what I already found, hoping it would help!

I ultimately want to use an [Agent with LCEL](https://python.langchain.com/docs/expression_language/cookbook/agent) but also with a [Conversation Summary Buffer](https://python.langchain.com/docs/modules/memory/types/summary_buffer). I initially followed the [`Agents -> How to -> Custom Agent -> Adding memory` section](https://python.langchain.com/docs/modules/agents/how_to/custom_agent#adding-memory) but there was no way to implement the buffer functionality, so I tried to improvise.

That said, what I have does not currently call the `predict_new_summary` but directly load all chat history with `load_memory_variables`. Ideally, I would create a custom function that takes the decision of whether it should summarize or not, and maybe even return the last `k` messages but always summarize anything before that?
I think it's [implicitly implemented in this section of the documentation](https://python.langchain.com/docs/modules/memory/types/summary_buffer#using-in-a-chain). Maybe another section there for usage with LCEL would be nice.

## Code Example (minus imports)

- Create the prompt 

```python
MEMORY_KEY = "chat_history"

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are Larry. A helpful AI assistant capable of performing a variety of tasks on the data available to you through the custom tools you have been provided with.",
        ),
        MessagesPlaceholder(variable_name=MEMORY_KEY),
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)
```

- Bind some custom tools

```python
tools = [
    Tool1(),
    Tool2(),
]

llm = ChatOpenAI(model=config.model)
formatted_functions = [format_tool_to_openai_function(t) for t in tools]
llm_with_tools = llm.bind(functions=formatted_functions)

for f in formatted_functions:
    print(f"function: {f}")
```

- Create the memory
```python
history = ChatMessageHistory()
history.add_user_message("Hi, my name is Jeff.")
history.add_ai_message("Hello Jeff! How can I assist you today?")

memory = ConversationSummaryBufferMemory(
    llm=ChatOpenAI(model="gpt-3.5-turbo"),
    return_messages=True,
    memory_key=MEMORY_KEY,
    chat_memory=history
)

print(memory.load_memory_variables({}))
memory.predict_new_summary(existing_summary="", messages=history.messages)
```
> {'chat_history': [HumanMessage(content='Hi, my name is Jeff.'), AIMessage(content='Hello Jeff! How can I assist you today?')]}
> 'The human introduces themselves as Jeff. The AI greets Jeff and asks how it can assist him.'

- Create the agent
```python
agent = (
    {
        "input": lambda x: x["input"],
        "agent_scratchpad": lambda x: format_to_openai_function_messages(
            x["intermediate_steps"]
        ),
    }
    | RunnablePassthrough.assign(
        # chat_history=RunnableLambda(memory.load_memory_variables) | itemgetter(MEMORY_KEY)
        **{MEMORY_KEY: RunnableLambda(memory.load_memory_variables) | itemgetter(MEMORY_KEY)}
    )
    | prompt
    | llm_with_tools
    | OpenAIFunctionsAgentOutputParser()
)

agent_executor = AgentExecutor(agent=agent, tools=tools)  # type: ignore
```

- Use the agent
```python
response = agent_executor.invoke({"input": "Hi, my name is Jeff."})
```
> {'input': 'Hi, my name is Jeff.', 'output': "Hello again, Jeff! It seems we've already greeted each other. Is there anything specific you'd like to know or do? I'm here to help!"}

**Comment by brandonhresko** [comment]
@usersina Im trying to implement conversational buffer memory (PostgresChatMessageHistory) to my LCEL agent. do I need to add another RunnableLambda that saves memory context?

**Comment by pechaut78** [comment]
> @usersina Im trying to implement conversational buffer memory (PostgresChatMessageHistory) to my LCEL agent. do I need to add another RunnableLambda that saves memory context?

`from langchain.memory import ConversationSummaryMemory
from langchain_core.runnables import RunnableLambda,RunnablePassthrough

memory = ConversationSummaryMemory(
    llm=llm, return_messages=True, output_key="answer", input_key="question"
    )


def save_mem(x):
    print(x["answer"])
    print(x["question"])
    memory.save_context({"question": x["question"]}, {"answer": x["answer"]})
    return x

def load_mem(x):
    return memory.load_memory_variables({})


from langchain import PromptTemplate
from langchain.prompts.chat import  ChatPromptTemplate,HumanMessagePromptTemplate,SystemMessagePromptTemplate
from langchain.schema import  SystemMessage

chat_prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate.from_template("Tu es un assistant qui répond à l'utilisateur, voici l'historique de conversation: {chat_history}"),
        HumanMessagePromptTemplate.from_template(" {question}") 
     ])


from langchain_core.output_parsers import StrOutputParser

output_parser = StrOutputParser()

chain = {"chat_history": RunnableLambda(memory.load_memory_variables), "question": RunnablePassthrough()}  | chat_prompt | llm | output_parser 
save_chain =  {"question": RunnablePassthrough(), "answer": RunnablePassthrough()| chain} | RunnableLambda(save_mem)
`

And you use save_chain when you want to use te momory mechanism
