### ISSUE TITLE
DOC: Improve MarkDown Splitting and Metadata as Part of RAG.

### ISSUE THREAD

**Issue by JayGhiya** [langchain-ai/langchain#12067]
### Issue with current documentation:

The current documentation for rag does not focus on adding metadata to chunks to make sure before even doing similarity search on vector db only the relevant docs with correct metadata are retrieved from vector db. 
The issue is with open source embedding models having only mostly 512 sequence length. 
Lot of context is lost if correct metadata is not present in each chunk.
This improves ability of local model to  improve results by factor of magnitude. We tested the same with local hosted embedded model and codellama to improve queries on mermaid and currently getting results onpar with gpt4.

### Idea or request for content:

This notebook covers the same.

https://github.com/unoplat/unoplat-lamp/blob/1-mermaid-expert/llm-rag/Mermaid%20Expert%20RAG.ipynb 

The comparison is done with codellama without the KB and gpt4.

**Comment by strokesegment** [comment]
Do you have a better solution? I found in the document split that the title information is stored as metadata information, but I think it should be added to the content.
