### ISSUE TITLE
Running SQLDatabaseChain adds prefix "SQLQuery:\n" infront of returned SQL by LLM, causing invalid query when ran on Database using chain

### ISSUE THREAD

**Issue by zahidiqbalnbs** [langchain-ai/langchain#12077]
### System Info

Running SQLDatabaseChain with LangChain version 0.0.319 and Snowflake return SQL query which is to be executed on snowflake database in next step. But returned query contains the prefix "SQLQuery:\n" which will broke the whole chain when the query gets executed on snowflake. How to get rid of this "SQLQuery:\n" prefix from query.

Note: Using AWS Bedrock endpoint with Anthropic Claudev2 LLM.

Using default prompt provided in the langchain:

`Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer. Unless the user specifies in his question a specific number of examples he wishes to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database.

Never query for all the columns from a specific table, only ask for a the few relevant columns given the question.

Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table.

Use the following format:

Question: Question here
SQLQuery: SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here
`

Getting following response in debug/verbose mode:

`"text": " SQLQuery:\nSELECT top 5 p.productname, sum(od.quantity) as total_sold\nFROM products p\nJOIN orderdetails od ON p.productid = od.productid \nGROUP BY p.productname\nORDER BY total_sold DESC\n"
}`

Any help would be appreciated.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Just use SQLDatabaseChain with AWS Bedrock Anthropic Claude 2 to produce this one.

### Expected behavior

Should not prefix  "SQLQuery:\n" in front returned SQL query.

**Comment by zahidiqbalnbs** [comment]
Hi @dosu-bot.

I have made your suggested changes in my prompt but still issue is there it still gives me text along with SQL query instead of just SQL query.

Use the following format:

Question: Question here
SQL Query to run
SQLResult: Result of the SQLQuery
Answer: Final answer here


Response:

"text": " Here is the SQL query and result to find the top 5 products with the highest sales:\n\nQuestion: Find the top 5 products with the highest sales.\n\nSQLQuery:\nSELECT p.productname, SUM(od.quantity) AS total_quantity\nFROM products p\nJOIN orderdetails od ON p.productid = od.productid  \nGROUP BY p.productname\nORDER BY total_quantity DESC\nLIMIT 5\n"
 

Suggest other ways or fixes to handle this scenario, I need only SQL query instead of this extra text.

**Comment by matt-at-allera** [comment]
hey @zahidiqbalnbs I'm running into this same issue using the AWS Bedrock endpoint with Anthropic Claudev2 LLM. Let me know if you make any progress on this. I've gotten it to somewhat work when modifying the prompt with the words "return only the generated SQL query and nothing else", but when that is done, the SQL query results are outputted, but no final human-readable answer. I'm also having trouble with the SQL agent... it repeatedly performs the `sql_db_list_tables` action and eventually times out. Interestingly enough, it is able to find the correct tables.

**Comment by syedair** [comment]
I am also facing the same issue. This is not only limited to Claudev2 LLM. I have tested with multiple LLMs and sharing my results.

I am using [Titanic Dataset](https://www.kaggle.com/datasets/ibrahimelsayed182/titanic-dataset) and using Amazon Athena as my backend DB. I am also testing with Amazon Bedrock SDK.


```python3
db_chain = SQLDatabaseChain.from_llm(textgen_llm, db, verbose=True)
response=db_chain.run(query)

> Entering new SQLDatabaseChain chain...
Total Passengers
SQLQuery:Question: Total Passengers
SQLQuery: SELECT COUNT(*) FROM titanic

Failed to execute query.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pyathena/common.py", line 522, in _execute
    query_id = retry_api_call(
               ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pyathena/util.py", line 85, in retry_api_call
    return retry(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:1: mismatched input 'Question'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UNLOAD', 'UPDATE', 'USE', <query>
```

It fails because anything after `SQLQuery:` is sent to the Database... This includes the extra text `Question: Total Passengers`. The extra test can be anything like `Here is the query:`, etc, which is sent to the Database as it is. 

Changing the prompt as well doesn't help as recommended by the bot @dosubot.

This behavior is the same with majority of the LLMs which I tested:
1. "anthropic.claude-v2"
2. "anthropic.claude-v1"
3. "anthropic.claude-instant-v1"


The following LLMs seems to work:
1. "ai21.j2-ultra-v1"
2. "ai21.j2-mid-v1"
3. "cohere.command-text-v14"

The output from `Jurassic-2 series by AI21 Labs` and `Command by Cohere` is working as expected, though it messes up sometimes too randomly.
```
> Entering new SQLDatabaseChain chain...
Total Passengers
SQLQuery:SELECT count(*) FROM titanic
SQLResult: [(891,)]
Answer:891
> Finished chain.
891
```

I think the same issue was with "gpt-3.5-turbo" and "gpt-4" but don't have any credits left to test it.

**Comment by tarek-kerbedj** [comment]
still facing the same problem , I wish they prioritize this issue

**Comment by akumar-ai-lab** [comment]
Can someone please solve this issue with SQLDatabaseChain as it is continuously appending text along with SQL query and code fails as it can execute only SQL code with out any text

**Comment by syedair** [comment]
@dosu-bot, modifying `query.py` and updating the `_strip` function didn't resolve it. It appears that that function is not called at all.

**Comment by ztanruan** [comment]
Any updates on this issue with Claude v2:1 on Bedrock ?
