### ISSUE TITLE
Confluence document loader not handling pagination correctly anymore (when using Confluence Cloud)

### ISSUE THREAD

**Issue by cccs-eric** [langchain-ai/langchain#12082]
### System Info

LangChain 0.0.317
atlassian-python-api 3.41.3

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When playing with documents from Confluence (Cloud hosting in my case), I have noticed that I am getting multiple copies of the same document in my vector store or from my Confluence retriever (custom implementation not in LangChain).  In both cases, the vector store is populated with LangChain's Confluence document loader and my retriever is also using that same document loader.  The problem happens in `ConfluenceLoader.paginate_request()` in the `while` loop until we reach `max_pages`.  In summary, you will get copies of the same documents until you reach `max_pages`.  For example, if your query (I'm using CQL in my use-case) returns 10 documents and `max_pages` is set to `200`, you will get 20 copies of each document.  This also makes the search process much slower.

The previous pagination system of Confluence REST server was leveraging an index controlled by the `start` parameter.  According to this [page](https://developer.atlassian.com/cloud/confluence/change-notice-moderize-search-rest-apis/), it has been deprecated in favor of a cursor system.  It is now recommended to follow `_links.next` instead of relying on the `start` parameter and getting an empty result when documents to be returned have been exhausted.  

This change is now in effect for the Cloud hosting of Confluence, not sure about private deployments.  You can see for yourself by running a script that looks like this:

```python
from atlassian import Confluence

site = "templates" # Public site 
confluence = Confluence(url=f"https://{site}.atlassian.net/")

cql='type=page AND text~"is"'
response_1 = confluence.cql(cql=cql, start=0)
print(response_1) # Easier to see in debug mode
next_start = len(response_1["results"])*1000
response_2 = confluence.cql(cql=cql, start=next_start)
print(response_2) # Notice returned documents are the same as in response_1
```

### Expected behavior

The Confluence document loader should handle properly pagination for both the old (using `start`) and new way (cursor) to maintain backward compatibility for private Confluence deployments.  It should also properly stop when `max_pages` has been reached.

**Comment by cccs-eric** [comment]
See this somewhat related [Atlassian bug report ](https://github.com/atlassian-api/atlassian-python-api/issues/820)for this on how to solve this.

**Comment by amicus-veritatis** [comment]
any progress on this issue?

**Comment by mrjbu** [comment]
I'm also keen to learn if there has been any update about this issue.

If anyone has any ideas for a work around I'd be glad to read them. And if I think of anything I'll post it here

**Comment by hgye** [comment]
Hi,
When I trying using CQL to get all pages, I'm also facing the same problem.

After some investigate of Atlassian official documents, I found ```start``` parameters are DEPRECATE, instead we should using ```cursor``` parameters in responses "_links.next" as next time request. 
But in file ``` libs/community/langchain_community/document_loaders/confluence.py``` , which is still uing start as query parameters. It will cause everything it will fetch at most  25(limit value) pages repeat again and again, until reach max_pages(default is 1000). 

I just did a quick workaround in following patch file, wish it will helpful.

[confluence_cql.patch](https://github.com/langchain-ai/langchain/files/15373870/confluence_cql.patch)
Thanks.

**Comment by hgye** [comment]
Patch content
```
❯ cat confluence_cql.patch
diff --git a/libs/community/langchain_community/document_loaders/confluence.py b/libs/community/langchain_community/document_loaders/confluence.py
index 8a70758dd..8350c3c91 100644
--- a/libs/community/langchain_community/document_loaders/confluence.py
+++ b/libs/community/langchain_community/document_loaders/confluence.py
@@ -4,15 +4,9 @@ from io import BytesIO
 from typing import Any, Callable, Dict, Iterator, List, Optional, Union

 import requests
-from langchain_core.documents import Document
-from tenacity import (
-    before_sleep_log,
-    retry,
-    stop_after_attempt,
-    wait_exponential,
-)
-
 from langchain_community.document_loaders.base import BaseLoader
+from langchain_core.documents import Document
+from tenacity import before_sleep_log, retry, stop_after_attempt, wait_exponential

 logger = logging.getLogger(__name__)

@@ -396,17 +390,25 @@ class ConfluenceLoader(BaseLoader):
         yield from self._lazy_load()

     def _search_content_by_cql(
-        self, cql: str, include_archived_spaces: Optional[bool] = None, **kwargs: Any
-    ) -> List[dict]:
-        url = "rest/api/content/search"
+        self,
+        cql: str,
+        include_archived_spaces: Optional[bool] = None,
+        nexturl: str = "",
+        **kwargs: Any,
+        # ) -> List[dict]:
+    ) -> tuple[List[dict], str]:
+        if nexturl:
+            response = self.confluence.get(nexturl)
+        else:
+            url = "rest/api/content/search"

-        params: Dict[str, Any] = {"cql": cql}
-        params.update(kwargs)
-        if include_archived_spaces is not None:
-            params["includeArchivedSpaces"] = include_archived_spaces
+            params: Dict[str, Any] = {"cql": cql}
+            params.update(kwargs)
+            if include_archived_spaces is not None:
+                params["includeArchivedSpaces"] = include_archived_spaces

-        response = self.confluence.get(url, params=params)
-        return response.get("results", [])
+                response = self.confluence.get(url, params=params)
+        return response.get("results", []), response["_links"].get("next", "")

     def paginate_request(self, retrieval_method: Callable, **kwargs: Any) -> List:
         """Paginate the various methods to retrieve groups of pages.
@@ -431,6 +433,7 @@ class ConfluenceLoader(BaseLoader):

         max_pages = kwargs.pop("max_pages")
         docs: List[dict] = []
+        nexturl: str = ""
         while len(docs) < max_pages:
             get_pages = retry(
                 reraise=True,
@@ -444,9 +447,15 @@ class ConfluenceLoader(BaseLoader):
                 ),
                 before_sleep=before_sleep_log(logger, logging.WARNING),
             )(retrieval_method)
-            batch = get_pages(**kwargs, start=len(docs))
-            if not batch:
-                break
+            if self.cql:  # only cql
+                batch, nexturl = get_pages(**kwargs, nexturl=nexturl)
+                if not nexturl:
+                    docs.extend(batch)  # final iter result extend
+                    break
+            else:
+                batch = get_pages(**kwargs, start=len(docs))
+                if not batch:
+                    break
             docs.extend(batch)
         return docs[:max_pages]
```

**Comment by PraMis30** [comment]
@hgye What was the langchain and atlassian-python-api version that you tested this patch with
