### ISSUE TITLE
API Key Leakage in the BaseLanguageModel 

### ISSUE THREAD

**Issue by pomcho555** [langchain-ai/langchain#12110]
### System Info

Langchain:0.0.319
Python:3.11.2
System: macOS 13.5.2 arm64

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I implemented a generic module to handle many types of chat models. I executed the following script after I set `OPENAI_API_KEY=xxx` in `.env` file.

```python
from dataclasses import dataclass, field

from langchain.schema.language_model import BaseLanguageModel
from langchain.chat_models import ChatOpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

@dataclass
class ModelConfig:
    """Model Configuration"""

    model: BaseLanguageModel
    arguments: field(
        default_factory=dict
    )  # This could be any arguments for BaseLanguageModel child class

    def init_model(self) -> BaseLanguageModel:
        return self.model(**self.arguments)

if __name__ == "__main__":
    model = ModelConfig(model=ChatOpenAI, arguments=dict())
    print(model)

```

And then the output contains **a leaked API key**!

```sh
<class 'openai.api_resources.chat_completion.ChatCompletion'> openai_api_key=xxxx>
```

### Expected behavior

My idea off the top of my head is to use, say,  `__str__` directive inside the original class. But this seems just a workaround for ChatOpenAI class. So something more generic feature in `BaseLanguageModel` would be more decent. Like should have a common property in the base class, which handle API token across any LLM models and this property might be a special class that can hide the value when other class and functions call this.

https://github.com/langchain-ai/langchain/blob/08f5e6b8012f5eda2609103f33676199a3781a15/libs/langchain/langchain/chat_models/openai.py#L181-L238

## Similar issue.

#8499

**Comment by samadkoita** [comment]
Tracking this issue here: https://github.com/langchain-ai/langchain/issues/12165
