### ISSUE TITLE
Is there any loader for Microsoft OneNote like EverNoteLoader or ObsidianLoader

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#12125]
### Feature request

Microsoft OneNote loader like EverNoteLoader or ObsidianLoader

### Motivation

N/A

### Your contribution

N/A

**Comment by dvanwag** [comment]
Agreed. I have several .one notebooks I would love to integrate.

**Comment by Dylan20XX** [comment]
Hi there, we're a small team of developers and we would like to work on this issue.

**Comment by dvanwag** [comment]
> Hi there, we're a small team of developers and we would like to work on this issue.

How can we help?

**Comment by Dylan20XX** [comment]
> > Hi there, we're a small team of developers and we would like to work on this issue.
> 
> How can we help?

Hi dvanwag, we'd love to hear any suggestions and input that you have as our team works on developing this feature. We're first-time contributors here, so we appreciate any guidance from the community. At the moment, we've only just started delving into it, but we're currently looking at how we can use the OneNote API via an existing Python library for this.

**Comment by dvanwag** [comment]
> > > Hi there, we're a small team of developers and we would like to work on this issue.
> > 
> > 
> > How can we help?
> 
> Hi dvanwag, we'd love to hear any suggestions and input that you have as our team works on developing this feature. We're first-time contributors here, so we appreciate any guidance from the community. At the moment, we've only just started delving into it, but we're currently looking at how we can use the OneNote API via an existing Python library for this.

The API is a good first step. The challenge with OneNote .one files may be they are updated in real time at the user makes and captures new notes, so there may need to be a request feature built into the call (I am not a developer by trade, so forgive me if I'm not articulating this correctly).  

Microsoft also has their Graph app that may help pull in data, but I know very little how it works. If there is a way to drill down into Notebooks, Sections, and Pages to make queries AI can answer, I'd say that would be the sweet spot for so many users and would likely surpass the capabilities of Window's built in CoPilot.

**Comment by dvanwag** [comment]
Yes, I think @Dylan20XX Dylan20XX, @mail2mhossain, and I are happy with the new document loader for OneNote that can be found here: https://python.langchain.com/docs/integrations/document_loaders/microsoft_onenote.  Thank you so much to the community for helping us figure this out and deploy the loader for OneNote users!

**Comment by juqing27** [comment]
@dosu-bot Hi, has anyone tried the langchain onenote loader ([here](https://python.langchain.com/docs/integrations/document_loaders/microsoft_onenote/)) yet? It's simply not working for me. The url/webpage to give consent to appears as expected, however after pasting the resulting page url, the console shows this error:


Visit the following url to give consent:
https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?client_id=...&response_type=code&scope=Notes.Read+offline_access+openid+profile
Paste the authenticated url here:
<I pasted the resulting url>
Traceback (most recent call last):
  File "...\test_onenote_1\lc_onenote_2.py", line 15, in <module>
    documents = loader.load()
                ^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\langchain_core\document_loaders\base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\langchain_community\document_loaders\onenote.py", line 65, in lazy_load
    self._auth()
  File "...\venv\Lib\site-packages\langchain_community\document_loaders\onenote.py", line 164, in _auth
    self.access_token = access_token_json["access_token"]
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'access_token'

Process finished with exit code 1

Anyone has a clue?

**Comment by anandncode** [comment]
Hi,

Is there any chance that oneNote loader will available for javascript? it would be really helpful

**Comment by asadCoder** [comment]
Hi @anandncode, were you able to open a feature request for this in the JS library?
