### ISSUE TITLE
Issue: View context used in query in ConversationalRetrievalChain

### ISSUE THREAD

**Issue by Anaudia** [langchain-ai/langchain#12167]
### Issue you'd like to raise.

How can I see the context that was used to answer a specific question? 

from langchain.memory import ConversationBufferWindowMemory
memory = ConversationBufferWindowMemory(k=3, memory_key="chat_history", return_messages=True)

qa = ConversationalRetrievalChain.from_llm(llm_model, vector_store.as_retriever(search_type='similarity', search_kwargs={'k': 2}), memory=memory)
query = "Can I as a manager fly business class?"

##predict with the model
text = f"""[INST] <<SYS>> You are a HR-assistant that answers questions:
<</SYS>> 
{query} [/INST]
"""
result = qa({"question": text})
result

**Comment by dianz17** [comment]
You can see it by enabeling the **{"verbose":True}  just like this:

qa = ConversationalRetrievalChain.from_llm(
    llm = chat,
    retriever = chroma_retriever,
    condense_question_llm = llm,
    memory=memory,
    combine_docs_chain_kwargs={"prompt": promptHist},
    **{"verbose":True} 
)

With that parameter enabled you will see what is being inserted into {context} (what the retriever is returning). Just keep in mind that im using a custom prompt and is something similar to this:

chatTemplate = """
You are a friendly and helpful salesperson stores. 
If you don't know the answer to a question, clearly state that you don't have that information. Do not improvise answers.

Please consult the following documents for information: {context}

Current conversation:
{chat_history}

Human: 
{question}
AI: 
"""

I hope this information is useful.
