### ISSUE TITLE
For New Contributors: Use SecretStr for api_keys

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#12165]
Hello LangChain community,

We're always happy to see more folks getting involved in contributing to the LangChain codebase.

This is a good first issue if you want to learn more about how to set up
for development in the LangChain codebase.

## Goal

Your contribution will make it safer to print out a LangChain object
without having any secrets included in raw format in the string representation.

## Set up for development

Prior to making any changes in the code:

https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md

Make sure you're able to test, format, lint from `langchain/libs/langchain`

```sh
make test
```

```sh
make format
```

```sh
make lint
```

## Shall you accept

Shall you accept this challenge, please claim one (and only one) of the modules from the list
below as one that you will be working on, and respond to this issue.

Once you've made the required code changes, open a PR and link to this issue.

## Acceptance Criteria

- invoking str or repr on the the object does not show the secret key

Integration test for the code updated to include tests that:

- confirms the object can be initialized with an API key provided via the initializer
- confirms the object can be initialized with an API key provided via an env variable

Confirm that it works:

- either re-run notebook for the given object or else add an appropriate test
that confirms that the actual secret is used appropriately (i.e.,`.get_secret_value()`)

**If your code does not use `get_secret_value()` somewhere, then it probably contains a bug!**

## Modules

- [ ] langchain/chat_models/anyscale.py @aidoskanapyanov 
- [ ] langchain/chat_models/azure_openai.py @onesolpark 
- [x] langchain/chat_models/azureml_endpoint.py @fyasla 
- [ ] langchain/chat_models/baichuan.py
- [ ] langchain/chat_models/everlyai.py @sfreisthler 
- [x] langchain/chat_models/fireworks.py @nepalprabin 
- [ ] langchain/chat_models/google_palm.py @faisalt14 
- [ ] langchain/chat_models/javelin_ai_gateway.py
- [ ] langchain/chat_models/jinachat.py
- [ ] langchain/chat_models/konko.py
- [ ] langchain/chat_models/litellm.py
- [ ] langchain/chat_models/openai.py @AnasKhan0607 
- [ ] langchain/chat_models/tongyi.py
- [ ] langchain/llms/ai21.py
- [x] langchain/llms/aleph_alpha.py @slangenbach 
- [ ] langchain/llms/anthropic.py
- [ ] langchain/llms/anyscale.py @aidoskanapyanov 
- [ ] langchain/llms/arcee.py
- [ ] langchain/llms/azureml_endpoint.py
- [ ] langchain/llms/bananadev.py
- [ ] langchain/llms/cerebriumai.py
- [ ] langchain/llms/cohere.py @arunsathiya 
- [ ] langchain/llms/edenai.py @kristinspenc 
- [ ] langchain/llms/fireworks.py
- [ ] langchain/llms/forefrontai.py
- [ ] langchain/llms/google_palm.py @Harshil-Patel28 
- [ ] langchain/llms/gooseai.py
- [ ] langchain/llms/javelin_ai_gateway.py
- [ ] langchain/llms/minimax.py
- [ ] langchain/llms/nlpcloud.py
- [ ] langchain/llms/openai.py @HassanA01 
- [ ] langchain/llms/petals.py @akshatvishu 
- [ ] langchain/llms/pipelineai.py
- [ ] langchain/llms/predibase.py
- [ ] langchain/llms/stochasticai.py
- [x] langchain/llms/symblai_nebula.py @praveenv 
- [ ] langchain/llms/together.py
- [ ] langchain/llms/tongyi.py
- [ ] langchain/llms/writer.py @ommirzaei 
- [ ] langchain/llms/yandex.py

### Motivation

Prevent secrets from being printed out when printing the given langchain object.

### Your contribution

Please sign up by responding to this issue and including the name of the module.

**Comment by HassanA01** [comment]
Hey @eyurtsev  ! I am working with a group of 4 and would like to tackle this issue for my project at my course. Do you think completing these modules would be feasible in a month?

**Comment by eyurtsev** [comment]
@HassanA01 yes definitely. But the work is very similar across all the modules -- I would suggest selecting a single module per individual and should be just a few lines of code. This is a good entry point to set up for development w/ langchain and learn a little bit about the code structure

**Comment by HassanA01** [comment]
@eyurtsev Sounds good! Also, do you have another issue that might be a little bit more complex but doesn't require too much knowledge about the in-depths of langchain which we can also tackle and would be feasible to complete in 2-3 weeks

**Comment by faisalt14** [comment]
Hey, I’m also part of @HassanA01’s group and am planning to work on the langchain/chat_models/google_palm.py module. 😁

**Comment by HassanA01** [comment]
No worries! My group and I will get started to tackle this issue. I'll work on the langchain/llms/openai.py module!

**Comment by HassanA01** [comment]
@eyurtsev Is it fine if as a group of 5, we make **one** PR to the upstream main with 5 module fixes (1 per team member)?

**Comment by AnasKhan0607** [comment]
Another member of the team 🫡. Will be tackling the langchain/chat_models/openai.py module.

**Comment by eyurtsev** [comment]
@HassanA01 totally fine -- claim the modules that you want :)

**Comment by Harshil-Patel28** [comment]
Hey @eyurtsev. I'm also a member of the team. Ill be working on the langchain/llms/google_palm.py module 😊

**Comment by arunsathiya** [comment]
I have taken `langchain/llms/cohere.py` - 

- https://github.com/langchain-ai/langchain/pull/12188

**Comment by kristinspenc** [comment]
Hey, I’m also part of @HassanA01’s group and am planning to work on the langchain/llms/edenai.py module.

**Comment by aidoskanapyanov** [comment]
Hi @eyurtsev! Thanks for creating this "good first issue" 👍. 
Can you please assign me on `langchain/chat_models/anyscale.py` and `langchain/llms/anyscale.py`?

**Comment by onesolpark** [comment]
Hey @eyurtsev thanks for setting this up.
Can you assign me to langchain/chat_models/azure_openai.py.
Happy to get involved in contributing to the LangChain codebase.

**Comment by aidoskanapyanov** [comment]
@eyurtsev I'm having an issue with installing the dependencies with poetry. It automatically removes some of the libraries. Then I end up with `ModuleNotFoundError: No module named 'rapidfuzz'` error when trying to run tests or anything with poety. It's related to this issue #12237. 

For anyone facing this issue, as a workaround for now I installed the missing packages like so:
```
python -m pip install rapidfuzz
python -m pip install filelock
python -m pip install msgpack
python -m pip install build
```

**Comment by slangenbach** [comment]
@eyurtsev, thanks for making it easy future contributors to get going.
You can sign me up for **langchain/llms/aleph_alpha.py**

**Comment by nepalprabin** [comment]
Been using Langchain for a while. Thanks @eyurtsev for setting this up. Hope I can return something useful to the community.
You can sign me up for **langchain/chat_models/fireworks.py**.

**Comment by gautamanirudh** [comment]
Hey @eyurtsev,
You can assign me to langchain/llms/ai21.py.

**Comment by nepalprabin** [comment]
> Been using Langchain for a while. Thanks @eyurtsev for setting this up. Hope I can return something useful to the community. You can sign me up for **langchain/chat_models/fireworks.py**.

I implemented SecretStr for fireworks but while testing, do I need to bypass fireworks package or simply ```@pytest.mark.requires("openai")``` works? @eyurtsev

**Comment by samadkoita** [comment]
@eyurtsev Thanks for this initiative.
I have taken a crack at langchain/llms/gooseai.py
https://github.com/langchain-ai/langchain/pull/12496

**Comment by nepalprabin** [comment]
> > Been using Langchain for a while. Thanks @eyurtsev for setting this up. Hope I can return something useful to the community. You can sign me up for **langchain/chat_models/fireworks.py**.
> 
> I implemented SecretStr for fireworks but while testing, do I need to bypass fireworks package or simply `@pytest.mark.requires("openai")` works? @eyurtsev

[#12475](https://github.com/langchain-ai/langchain/pull/12475)

**Comment by ommirzaei** [comment]
Hey @eyurtsev Thanks for setting this up. 
Could you please assign me to `langchain/llms/writer.py`. Thanks!

**Comment by sfreisthler** [comment]
Hi @eyurtsev, can you please assign me to langchain/chat_models/everlyai.py? Thanks!

**Comment by akshatvishu** [comment]
Hey @eyurtsev , I would like to work on `langchain/llms/yandex.py`. Thanks!

**Comment by fyasla** [comment]
Hello :wave:,
Thank you for setting this up!
I have started to work on `langchain/chat_models/azureml_endpoint.py`

**Comment by praveenv** [comment]
Hi, noticed that no one was working on `langchain/llms/symblai_nebula.py`, so just submitted a PR for it.

**Comment by pkcodesat** [comment]
@eyurtsev Kindly assign langchain/llms/azureml_endpoint.py to me. Thanks!

**Comment by hiroshitashir** [comment]
Just created a PR for langchain/chat_models/javelin_ai_gateway.py above at https://github.com/langchain-ai/langchain/pull/13092. Thanks!

**Comment by ilyazub** [comment]
Hi. In https://github.com/langchain-ai/langchain/pull/13207, I masked API keys that are used in `langchain/utilities/serpapi.py` and `langchain/utilities/google_scholar.py`.

**Comment by faisale** [comment]
@eyurtsev, I'll handle `langchain/llms/pipelineai.py`.

**Comment by Muhmdk** [comment]
Hey @eyurtsev, Thank you for setting this up, I would love to work on langchain/llms/azureml_endpoint.py.

**Comment by ch1zzzz** [comment]
Hi @eyurtsev, could you please assign me ```langchain/chat_models/baichuan.py```? Thanks!

**Comment by HassanFazal97** [comment]
Hey @eyurtsev, I would like to work on `langchain/llms/anthropic.py`. Could you assign me to that please

**Comment by shivangsoni** [comment]
Hi @eyurtsev, Can you please assign langchain/llms/fireworks.py to me?

**Comment by kahlkritzinger** [comment]
Hey @eyurtsev, please assign `langchain/llms/stochasticai.py` to myself. Thanks for setting this up!

**Comment by chennavc** [comment]
Hey @eyurtsev, I'd like to contribute to issue #12165 by working on the langchain/llms/azureml_endpoint.py module. I'm prepared to implement SecretStr for API keys, ensuring enhanced security. Looking forward to making a positive impact!

**Comment by zuhorer** [comment]
hey, @eyurtsev, I would like to contribute and take up:
 langchain/llms/azureml_endpoint.py module

**Comment by zuhorer** [comment]
hey @eyurtsev, I would like to take up:
langchain/llms/anthropic.py

**Comment by raphaelreiss** [comment]
Hi @eyurtsev, I would like to take: langchain/llms/arcee.py. Thank you for this nice setup !

**Comment by chyroc** [comment]
@eyurtsev coule you please assign me `langchain/chat_models/jinachat.py`, thanks

**Comment by yliang412** [comment]
Hi @eyurtsev, could you please assign me `langchain/llms/cerebriumai.py`, thanks!

**Comment by xavier-xia-99** [comment]
Hello @eyurtsev Could you please assign me `langchain/chat_models/litellm.py` :)

**Comment by lwunder** [comment]
Hi @eyurtsev could I get assigned to `langchain/llms/predibase.py`? Thanks!

**Comment by normand1** [comment]
Hi @eyurtsev thanks for the great issue, please assign `langchain/llms/together.py` to me please, thanks!

**Comment by nhywieza** [comment]
Hi @eyurtsev , could you please assign me langchain/chat_models/baichuan.py? thanks

**Comment by lujingxuansc** [comment]
Hi @eyurtsev  , could you please assign me langchain/llms/nlpcloud.py? thanks

**Comment by chrismcgale** [comment]
Hi @eyurtsev, I'd like to help with llms/minimax. Will get started now if you could assign it to me, thanks.

**Comment by rshah98626** [comment]
Just an FYI (@eyurtsev), I'm working to mask the `langchain/llms/tongyi.py` key.

**Comment by mmahmad** [comment]
I'll take langchain/llms/anthropic.py

**Comment by zuhorer** [comment]
> I'll take `langchain/llms/anthropic.py`
> 
> 
> 
> Edit: Oops, looks like it was already covered in https://github.com/langchain-ai/langchain/pull/11185.
> 
> 
> 
> @eyurtsev you can mark anthropic as resolved from the checklist.


Hi, I believe there has been a confusion as the issues are not checked for a while. I asked to assigned to llm/anthropic. Hopefully you can take another issue🙂. It would be really helpfully.

**Comment by Sierrra** [comment]
Hi @eyurtsev !
Could you please check my PR #13649  for langchain/llms/yandex.py ?

**Comment by SarathChennammsetty** [comment]
Hey @eyurtsev, I'd like to contribute to the **azureml_endpoint.py** module. Will get started now if you could assign it to me, thanks.

**Comment by fadilparves** [comment]
Hi @eyurtsev , thanks for this new contributors issue. Can you please assign me to `langchain/chat_models/tongyi.py` ? 
Thank you

**Comment by eekaiboon** [comment]
Hi @eyurtsev, can you please assign me to `langchain/llms/arcee.py`? Thank you!

**Comment by tholapz** [comment]
Hi @eyurtsev
 Please assign the `langchain/llms/bananadev.py` to me. 

ty

**Comment by aibysid** [comment]
Hello @eyurtsev, could you kindly assign me  langchain/llms/anthropic.py? I'm currently engaged in projects that involve langchain, and contributing to these modules would greatly enhance my understanding of the project's intricacies. Thank you!

**Comment by eyurtsev** [comment]
Hello everyone! thank you all for your contributions! We've made a lot of progress with SecretStrs in the code base. 

First time contributors -- hope you had fun learning how to work in the code base and thanks for putting in the time. All contributors -- thanks for all your efforts in improving LangChain.

We'll re-open a new first time issue in a few months.

**Comment by TheJagStudio** [comment]
Hi, I'd like to contribute to this migration.

Proposed scope: Two partner packages still using raw str for API keys:

langchain-huggingface — HuggingFaceEndpointEmbeddings and HuggingFaceEndpoint both declare huggingfacehub_api_token: str | None. I'd switch to SecretStr | None with secret_from_env(...) and call .get_secret_value() at the point of use in the model validators.
langchain-nomic — NomicEmbeddings.__init__ accepts nomic_api_key: str | None. I'd widen to str | SecretStr | None (backwards-compatible) and add an isinstance unwrap before nomic.login(key).
I'll flag the HuggingFace narrowing as a potential breaking change in the PR description. Could a maintainer assign me?
