### ISSUE TITLE
`poetry install --with test`: Group(s) not found: test (via --with)

### ISSUE THREAD

**Issue by arunsathiya** [langchain-ai/langchain#12170]
### System Info

I am trying to setup the local development environment with `poetry install --with test` but I am running into the error `Group(s) not found: test (via --with)`

```
> origin/master:master via 🐍 v3.11.6
> 57% langchain ❯ poetry install --with test

Group(s) not found: test (via --with)
```

Could you advise on what might be happening here?

### Who can help?

@eyurtsev, I think you might be able to advise here? 🙏🏼 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

- Clone repository
- With poetry installed, run `poetry install --with test`

### Expected behavior

Local development setup works without an error.

**Comment by eyurtsev** [comment]
choose the pyproject.toml that corresponds to the lib that you're working with:

cd: libs/langchain for langchain
or: libs/experimental for langchain_experimental

then use the poetry command

**Comment by arunsathiya** [comment]
Thank you, @eyurtsev! That helped.
