### ISSUE TITLE
Integrate RetryOutputParser with ConversationalRetrievalChain

### ISSUE THREAD

**Issue by timxieICN** [langchain-ai/langchain#12175]
### Feature request

Is there a way to integrate `RetryOutputParser` with `ConversationalRetrievalChain`? Specifically, if I use OpenAI's function calling to generate the response in a specific format, the LLM model does not always follow the instructions and then it would fail the Pydantic model validation.

Therefore, it's important to build the retry mechanism for the `LLMChain` (aka, `doc_chain` argument).

### Motivation

Specifically, if I use OpenAI's function calling to generate the response in a specific format, the LLM model does not always follow the instructions and then it would fail the Pydantic model validation.

Therefore, it's important to build the retry mechanism for the `LLMChain` (aka, `doc_chain` argument).

### Your contribution

TBD

**Comment by timxieICN** [comment]
@dosu-bot
I don't think this would work. Let me be a bit more specific:

I have the following code:
```
ConversationalRetrievalChain.from_llm(
      llm=AzureOpenAI,
      retriever=...,
      memory=ConversationTokenBufferMemory,
      chain_type="stuff",
```

So behind the scenes a `LLMChain` is called to send the payload to OpenAI model endpoint. How do I build `RetryOutputParser` around my codes `ConversationalRetrievalChain`

**Comment by timxieICN** [comment]
@dosu-bot

I have the following code:
```
ConversationalRetrievalChain.from_llm(
      llm=AzureOpenAI,
      retriever=...,
      memory=ConversationTokenBufferMemory,
      chain_type="stuff",
)
```
So behind the scenes a LLMChain is called to send the payload to OpenAI model endpoint. How do I build RetryOutputParser around my codes ConversationalRetrievalChain so that retry mechanism can be leveraged LLM response fails pydantic model schema validation?

**Comment by timxieICN** [comment]
@dosu-bot

OK, how do I get `RetryOutputParser` to work with `LLMChain`?

**Comment by sudranga** [comment]
@timxieICN I believe this PR https://github.com/langchain-ai/langchain/pull/11719 is required
