### ISSUE TITLE
Add a config chain before the ConversationalRetrievalChain : search Kwargs

### ISSUE THREAD

**Issue by MohamedTaha314** [langchain-ai/langchain#12189]
### Feature request

I want to add a config chain prior to the ConversationalRetrievalChain that is going to process the query and set the retriever's search kwargs ( k, fetch_k, lambda_mult ) depending on the question, how can I do that and pass the parameters from the config chain output

### Motivation

The motivation is to have a dynamic ConversationalRetrievalChain that retrieves the documents the right way for each question.

### Your contribution

I have none for now, I don't know where to start

**Comment by MohamedTaha314** [comment]
> _🤖_
> 
> Hi there,
> 
> Thanks for your interest in LangChain and for your question. You can indeed add a config chain before the `ConversationalRetrievalChain` to dynamically set the retriever's search parameters (`k`, `fetch_k`, `lambda_mult`) based on the question. Here's a step-by-step guide on how you can achieve this:
> 
> 1. **Create a new chain**: This new chain will wrap around the existing `ConversationalRetrievalChain`. It will take in the question, dynamically set the parameters, and then call the `ConversationalRetrievalChain` with these parameters. Here's an example of how you can do this:
> 
> ```python
> from langchain.chains.base import Chain
> from langchain.schema.runnable.config import RunnableConfig
> from langchain.pydantic_v1 import BaseModel
> from typing import Any, Dict, Optional, Type
> 
> class ConfigChain(Chain):
>     """Chain for setting config parameters dynamically."""
> 
>     retrieval_chain: ConversationalRetrievalChain
>     """The retrieval chain to set the parameters for."""
> 
>     class Config:
>         """Configuration for this pydantic object."""
> 
>         extra = Extra.forbid
>         arbitrary_types_allowed = True
>         allow_population_by_field_name = True
> 
>     @property
>     def input_keys(self) -> List[str]:
>         """Input keys."""
>         return ["question", "chat_history"]
> 
>     def get_input_schema(
>         self, config: Optional[RunnableConfig] = None
>     ) -> Type[BaseModel]:
>         return InputType
> 
>     @property
>     def output_keys(self) -> List[str]:
>         """Return the output keys.
> :meta private:
>         """
>         return self.retrieval_chain.output_keys
> 
>     def _call(
>         self,
>         inputs: Dict[str, Any],
>         run_manager: Optional[CallbackManagerForChainRun] = None,
>     ) -> Dict[str, Any]:
>         question = inputs["question"]
>         # Set the parameters based on the question
>         k = ...  # Set this based on the question
>         fetch_k = ...  # Set this based on the question
>         lambda_mult = ...  # Set this based on the question
>         self.retrieval_chain.retriever.k = k
>         self.retrieval_chain.retriever.fetch_k = fetch_k
>         self.retrieval_chain.retriever.lambda_mult = lambda_mult
>         # Call the retrieval chain with the new parameters
>         return self.retrieval_chain._call(inputs, run_manager)
> ```
> 
> In this example, you would replace the `...` with your own logic for setting the parameters based on the question. Then, you can use this new `ConfigChain` in place of the `ConversationalRetrievalChain`, and it will dynamically set the parameters for each question.
> 
> 2. **Use the new chain**: Once you've created the `ConfigChain`, you can use it in place of the `ConversationalRetrievalChain` in your code. The `ConfigChain` will take care of setting the parameters for the `ConversationalRetrievalChain` based on the question.
> 
> Please note that this is a high-level guide and you might need to adjust the code to fit your specific use case. If you have any further questions or run into any issues, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [libs/langchain/langchain/chains/conversational_retrieval/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/conversational_retrieval/base.py)
> * [libs/langchain/tests/unit_tests/chains/test_conversation_retrieval.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/unit_tests/chains/test_conversation_retrieval.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Ok, but what if I want the parameters to be determined by an chain containing an LLM, having this prompt and a JSON parser :

"""
Your Job is to assess the question the user is asking, and determine 3 values that would change based on the question's nature :

- fetch_k : the number of documents needed to get an overview on the question : Integer varies from 20 to 35.
- k : the number of documents taken from the original documents that are going to be used to answer the question : Integer varying from 5 to 12
- lambda_mult : the variance of the k documents taken from the fetch_k, a float varying from 0 to 1, with 0 means getting documents that are really similar, and 1 means taking documents that are very varied.

EXAMPLES :
1 . Who is better, company X or company Y ? => {fetch_k : 35, k = 11, lambda_mult = 1}
2 . Talk to me specifically about the company Z. => {fetch_k : 20, k = 5, lambda = 0.4}

Do the same for this :{question}

"""

**Comment by sourabh-circuitry** [comment]
Yes, We still don't have this feature with the latest version of Lang chain
