### ISSUE TITLE
Error reshaping array in _extract_images_from_page() in pdf.py

### ISSUE THREAD

**Issue by maredudd** [langchain-ai/langchain#12196]
### System Info

langchain==0.0.320
Ubuntu 20.04
Python 3.11.5

### Who can help?

@SuperJokerayo  @baskaryan 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When I try to parse a PDF and extract an image I get the following error:

```
  File "<.....>/lib/python3.11/site-packages/langchain/document_loaders/parsers/pdf.py", line 106, in _extract_images_from_page
    np.frombuffer(xObject[obj].get_data(), dtype=np.uint8).reshape(
ValueError: cannot reshape array of size 45532 into shape (4644,3282,newaxis)
```

The code I have to run the parser is:
```
loader = PyPDFLoader(doc["file"], extract_images=True)
pages = loader.load_and_split()
```

I can't give you a copy of the document since it's confidential. It's a scanned 11-page document.

### Expected behavior

I expected `load_and_split()` to return a list of 11 pages with the text parsed from the image in each page.

If I change to `extract_images=False` then it returns an empty list of 0 pages as expected.

**Comment by SuperJokerayo** [comment]
hi, can you print out the filter that image objects used in your pdf? Maybe it is a filter with loss but operated as lossless filter and I’d like to fix it. And i suggest that you can use PuMuPDF to extract pdf which may be useful. You can also transfer your scanned image to JEPG which can be filtered by DCTdecode if you only want to use PyPDF.

**Comment by maredudd** [comment]
hi @SuperJokerayo, the filter is CCITTFaxDecode. 

This is the object in the file:

```
<</Type/XObject/Subtype/Image/Width 3282/Height 4644/ColorSpace/DeviceGray/BitsPerComponent 1/Length 45424/Decode[ 0 1]/DecodeParms<</Columns 3282/K -1/Rows 4644>>/Filter/CCITTFaxDecode/Name/X>>
```

When running it the values are:

`height`: 4644
`width`: 3282
`len(xObject[obj].get_data())`: 45532

I''ve been unable to reproduce the issue in a test document unfortunately I will try out your suggestions (PyMuPDF and/or JEPG), thanks.

**Comment by SpAcY001** [comment]
hi @maredudd I am facing the same issue as well, did you come up with anything
thanks.

**Comment by maredudd** [comment]
> hi @maredudd I am facing the same issue as well, did you come up with anything thanks.

@SpAcY001 I changed to using PyMuPDF which worked well for me.
