### ISSUE TITLE
Issue: RSSFeedLoader unreliable publish date

### ISSUE THREAD

**Issue by sgordon16** [langchain-ai/langchain#12202]
### Issue you'd like to raise.

The `publish_date` field returned in the metadata seems unreliable and is very often empty for many news sites. The publish date can easily be parsed directly from the RSS feed from the `pubDate` tag which, although optional, is pretty standard and is much more reliable than trying to pull it from the article itself which is currently being done using the `NewsURLLoader`.

### Suggestion:

We can override the `publish_date` coming from the `NewsURLLoader` metadata with the `published` field from the feed entry in the `RSSFeedLoader`

**Comment by mariomeyer** [comment]
This is still happening.. I confirm we can get the PubDate from the RSS feed even if the Newspaper3k cannot get a publish date for the article.
