### ISSUE TITLE
ModuleNotFoundError: No module named 'rapidfuzz'

### ISSUE THREAD

**Issue by jamesbraza** [langchain-ai/langchain#12237]
### System Info

https://github.com/langchain-ai/langchain/tree/d2cb95c39d5569019ab3c6aa368aa937d8dcc465
(just above `v0.0.322`)

MacBook Pro, M1 chip, macOS Ventura 13.5.2

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

With Python 3.10.11:

```bash
python -m venv venv
source venv/bin/activate
pip install poetry
poetry install --with test
make test
```

This gets:

```
poetry run pytest --disable-socket --allow-unix-socket tests/unit_tests/
Traceback (most recent call last):
  File "/Users/james.braza/code/langchain/venv/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/poetry/console/application.py", line 11, in <module>
    from cleo.application import Application as BaseApplication
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/application.py", line 12, in <module>
    from cleo.commands.completions_command import CompletionsCommand
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/commands/completions_command.py", line 10, in <module>
    from cleo import helpers
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/helpers.py", line 5, in <module>
    from cleo.io.inputs.argument import Argument
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/io/inputs/argument.py", line 5, in <module>
    from cleo.exceptions import CleoLogicError
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/exceptions/__init__.py", line 3, in <module>
    from cleo._utils import find_similar_names
  File "/Users/james.braza/code/langchain/venv/lib/python3.10/site-packages/cleo/_utils.py", line 8, in <module>
    from rapidfuzz.distance import Levenshtein
ModuleNotFoundError: No module named 'rapidfuzz'
```

### Expected behavior

I expected installation to install everything necessary to run tests

**Comment by jamesbraza** [comment]
Thank you @dosubot, yes I can manually install `rapidfuzz`, but the point is that `langchain` should have installed everything right off the bat when I ran `poetry install --with test`

**Comment by jamesbraza** [comment]
I think it's because:

- `poetry` depends on `cleo`, where `cleo==2.0.1` depends on `rapidfuzz<3`: https://github.com/python-poetry/cleo/blob/2.0.1/pyproject.toml#L36
    - https://github.com/python-poetry/cleo/issues/353 is an issue about supporting `rapidfuzz` 3
- `langchain==0.0.322` depends on `rapidfuzz>=3`: https://github.com/langchain-ai/langchain/blob/v0.0.322/libs/langchain/pyproject.toml#L117

So there may be some dependency mismatching

**Comment by dlqqq** [comment]
Just ran into this issue myself. Why does poetry not raise a warning here?

**Comment by kzmain** [comment]
> Just ran into this issue myself. Why does poetry not raise a warning here?

I fixed this issue by 
`pip3 install build pyproject-hooks requests-toolbelt`
`pip3 install --upgrade rapidfuzz filelock msgpack`

**Comment by khaledadrani** [comment]
I faced the same issue. The mistake was installing both poetry and langchain in the same virtual environment.

First, you have to install poetry outside of your langchain environment using pipx  

```
pip install pipx # it is ok to install this globally
pipx install poetry
```

After, poetry will be accessible within any virtual environment. This will also make sure that the dependencies of langchain and of poetry do not get mixed. You can then use poetry within your virtual environment.

I hope this help.

**Comment by khaledadrani** [comment]
I faced the same issue. The mistake was installing both poetry and langchain in the same virtual environment.

First, you have to install poetry outside of your langchain environment using pipx  

```
pip install pipx # it is ok to install this globally
pipx install poetry
```

After, poetry will be accessible within any virtual environment. This will also make sure that the dependencies of langchain and of poetry do not get mixed. You can then use poetry within your virtual environment.

I hope this help.

**Comment by jamesbraza** [comment]
Many other repos using `poetry` don't have this issue. I appreciate all the workaround posed, but the dependency resolution needs to be fixed in LangChain's requirements.

**Comment by itallominatti** [comment]
In my case my poetry had been randomly uninstalled, I solved it by reinstalling poetry

**Comment by cotarelorodrigo** [comment]
> pip install requests_toolbelt

+1

**Comment by cotarelorodrigo** [comment]
> I had to install rapidfuzz and requests_toolbelt
> 
> pip install rapidfuzz pip install requests_toolbelt

+1
