### ISSUE TITLE
Issue: Problems getting filtering to work with langchain, OpenSearchVectorSearch, similarity_search_with_score

### ISSUE THREAD

**Issue by jrabyIBM** [langchain-ai/langchain#12240]
### Issue you'd like to raise.

Using langchain on AWS lambda function to call an AWS OpenSearch Serverless vector index.  I did not file as a bug, as I suspect that this is a usage problem, but it might be a bug.

I have built an OpenSearch vector index, using AWS OpenSearch Serverless, and are using it to perform vector queries against document chunks.  This is all working well. I would now like to add the ability to filter these searches by document (there may be hundreds or thousands of vector entries per document).  There is metadata included with each entry, which includes a DocumentId field, which is a string-ized guid.  I thought it would be simple to filter against this metadata attribute, but cannot get it working.  

The call I am making is:
```
    docs = vsearch.similarity_search_with_score(
        theQuery,
        index_name="vector-index2",
        vector_field = "vector_field",
        search_type="script_scoring",
        pre_filter=filter_dict,
        space_type="cosinesimil",
        engine="faiss",
        k = 3
    )
```

Typical unfiltered output:
{"doc": {"page_content": "seat is  installed ... facing", "metadata": {"DocumentId": "{8B5D5890-0000-C1E8-B0B6-678C8509665D}", "DocumentTitle": "2023-Toyota-RAV4-OM.pdf", "DocClassName": "Document"}}, "score": 1.8776696}]

For filter_dict, I have tried:
    filter_dict = {'DocumentId':theDocId}                                    <-- Gets an error 
    filter_dict = {'bool': {'must': {'term': {'DocumentId': theDocId} } } }  <-- doesn’t find anything
    filter_dict = {'bool': {'must': {'match': {'DocumentId': theDocId} } } } <-- doesn’t find anything
    filter_dict = {'must': {'match': {'DocumentId': theDocId} } }            <-- Gets an error
    filter_dict = {'match': {'DocumentId': theDocId} }                         <-- doesn’t find anything

theDocId is a string set to an input parameter and looks like this:  {8B5D5890-0000-C1E8-B0B6-678C8509665D}.  Results are the same if I use a string constant (i.e. '{8B5D5890-0000-C1E8-B0B6-678C8509665D}')

Same results if I use search_type=”approximate_search” in conjunction with boolean_filter=filter_dict

Any suggestions on how to get this to work?

**Comment by jrabyIBM** [comment]
@dosu-bot Thanks for the quick reply!

However, using filter=filter_dict was the first thing that I tried.  I found that it was ignored (i.e. I always got the same result set back, regardless of what value was passed in the filter_dict.
After consulting with the docs for OpenSearchVectorSearch (see [https://api.python.langchain.com/en/latest/vectorstores/langchain.vectorstores.opensearch_vector_search.OpenSearchVectorSearch.html#langchain.vectorstores.opensearch_vector_search.OpenSearchVectorSearch.similarity_search_with_score]) I saw that for OpenSearch,  you have to use boolean_filter if using search_type=“approximate_search”, or pre_filter when using search_type="script_scoring".

Please let me know if you don't think that I am referring to the correct docs.  But this does match the behavior I see.  If I use filter, it appears to be ignored.  But the documented boolean_filter / pre_filter parameters appear to work (in that if I pass them, then I don't get any results back, -they are filtering everything out...)  I think that those are the correct parameters, but I am somehow not passing the right values in filter_dict.

**Comment by jrabyIBM** [comment]
@dosu-bot Thanks again.  That is a syntax that I had not tried before.  However it is not working for me either.  I am using 
```
    filter_dict = {'term': {'DocumentId': '{8B5D5890-0000-C1E8-B0B6-678C8509665D}' } }  
    docs = vsearch.similarity_search_with_score(
        theQuery,
        index_name="vector-index3",
        vector_field = "vector_field",
        search_type="approximate_search", 
        space_type="cosinesimil", 
        boolean_filter=filter_dict, 
        engine="faiss",
        k = 3
    )
```
But unfortunately this does not return any results.  It should return multiple results where the DocumentId metadata field matches.  But instead, it appears to be filtering out all results, including ones that should match.

**Comment by jrabyIBM** [comment]
@dosu-bot Thanks, but that did not work for me.  Here is the updated code:

```
    vsearch = OpenSearchVectorSearch(
        opensearch_url=ossEndpoint,
    	embedding_function = embeddings,
    	http_auth=awsauth,
        timeout = 300,
        use_ssl = True,
        verify_certs = True,
        vector_field = "vector_field",
        connection_class = RequestsHttpConnection,
        engine="faiss",
        index_name="vector-index3"
	)
    filter_dict = {'term': {'DocumentId': '{8B5D5890-0000-C1E8-B0B6-678C8509665D}' } }  
    docs = vsearch._approximate_search_query_with_boolean_filter(
        theQuery,
        boolean_filter=filter_dict,
        k=3,
        index_name="vector-index3",
        space_type="cosinesimil", 
        engine="faiss",
        vector_field = "vector_field"
    )
```

The error I get is:
"'OpenSearchVectorSearch' object has no attribute '_approximate_search_query_with_boolean_filter'"

**Comment by canfang-feng** [comment]
I got the exact same issues. It didn't work for me either with all the solutions Dosubot proposed. I spent a lot of time in fixing the bugs when using langchain but still failed.

**Comment by jrabyIBM** [comment]
@jingwentony Thanks for the suggestion.  The value in the DocumentId field that I am trying to match is: '{8B5D5890-0000-C1E8-B0B6-678C8509665D}'.   I have tried using both:
filter_dict = {‘terms’: {'DocumentId': ['{8B5D5890-0000-C1E8-B0B6-678C8509665D}'] } }
  and
filter_dict = {‘terms’: {'DocumentId': ['8B5D5890-0000-C1E8-B0B6-678C8509665D'] } }

But in both cases no results are found (meaning that it is filtering, but it filters out everything, including the values that I want to be returned...)

This is true both for script_scoring + pre_filter, and approximate_search + boolean_filter

So, still searching for a syntax that will filter

**Comment by jingwentony** [comment]
I finally got it working with the following format. 

boolean_filter  = {"bool":{"should":[ 
{"match" : {"metadata1":"value1"}}, 
{"match" : {"metadata2":"value2"}},
]}}
    
I do get a lot of information from this post https://stackoverflow.com/questions/21933787/elasticsearch-not-returning-results-for-terms-query-against-string-property.
 
The difference in field type (analyzed vs not analyzed) is quite tricky, I switch the word "term" to "match" and it helped a lot. Hopefully it helps.

**Comment by jrabyIBM** [comment]
@jingwentony thanks for the suggestions.  I wish I could say that this worked for me, but it did not.  I am wondering if this may be a bug / limitation of vector indexes in AWS OpenSearch Serverless.  I have defined the DocumentId field as a text metadata field in my vector index, and set "Filterable" to true.  So it seems that filtering on it should work, but none of the suggested syntax approaches work for me, either as a boolean_filter (when using approximate_search) or as a pre_filter (when using script_scoring).  

I gather that others are able to get this to work with ElasticSearch or OpenSearch, so I am suspecting a problem with AWS OpenSearch Serverless.  I may try the regular AWS (non Serverless) OpenSearch next.

**Comment by jrabyIBM** [comment]
This turned out to be pilot error after all, although I must say that there is a lot of room for improvement in the documentation.  There were two primary changes that I had to make:

- The first is that when data is indexed via LangChain, this is done by passing a python dictionary into the LangChain text splitter to generate a List of LangChain documents.  Each element of the dictionary is then stored as an OpenSearch field as metadata.  The field names are "metadata.<name>".  So the search filter must be 'metadata.documentid': '<id>'.  I was searching on 'documentid': '<id>' -which was not the correct field name.  Not sure how I should have known that.
- The second issue is that searching for data stored in OpenSearch as a string-ized guid does not work if the string contains curly braces or dashes.  So searching for

    ”documentid”: “{83fa9155-4d9b-4af4-913b-f55dba49a02a}”

You must instead search for:

    ”documentid”: “83fa91554d9b4af4913bf55dba49a02a”

And the curly braces and dashes must be removed from the guid string before indexing the document as well.

Maybe there is a search syntax that would find the guid strings with embedded curly braces and dashes, -not sure, but it does work after stripping them from the guid value.  

I am closing this issue with the solution above

**Comment by progpyftk** [comment]
This topic has helped me a lot.

This did not work for me:
`filter =  {"bool":{"filter": {"term": {"metadata.lesson_id": "TyKfB"}}}}`
    
This worked (thanks to @jingwentony)
 ```
boolean_filter = {"bool":{"should":[
   {"match" : {"metadata.lesson_id":"TyKfB"}},
]}}
```
