### ISSUE TITLE
retriever.get_relevant_documents

### ISSUE THREAD

**Issue by darthShana** [langchain-ai/langchain#12244]
### System Info

langchain in /opt/conda/lib/python3.11/site-packages (0.0.322)

Python 3.11.6

installed on 
image: jupyter/datascience-notebook

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

As per the documentation 

retriever = SelfQueryRetriever.from_llm(llm, vectorstore, document_content_description, metadata_field_info, verbose=True)
retriever.get_relevant_documents("What are some movies about dinosaurs")

### Expected behavior

We would see verbose output such as
`    query=' ' filter=Comparison(comparator=<Comparator.GT: 'gt'>, attribute='rating', value=8.5)
` 
however no verbose output is printed

**Comment by mohammre** [comment]
I am having the same issue, when you apply filter with retrievers get_relevant_documents  always return am empty list. 
There is a feature in as_retriever (return_source_doc=True, but still if you apply filter with as_retriever , it doesn't return any source document

**Comment by darthShana** [comment]
I guess what im trying to say is according to the documentation here
https://python.langchain.com/docs/modules/data_connection/retrievers/self_query/

by setting verbose=True in
`retriever = SelfQueryRetriever.from_llm(llm, vectorstore, document_content_description, metadata_field_info, verbose=True)
`
we should be able to see
`    query=' ' filter=Comparison(comparator=<Comparator.GT: 'gt'>, attribute='rating', value=8.5)
`
however this doesn't happen
And its pretty critical for debugging to see what the query and filter and attributes that its come up with 
I havent attempted to extend any of the classes of langchain, Can i create a copy of the SelfQueryRetriever and print json from the line bellow?

`        url, json, headers = self._create_request(query)
`
