### ISSUE TITLE
Returning detailed results of intermediate components

### ISSUE THREAD

**Issue by DanielRoeder1** [langchain-ai/langchain#12257]
### Issue you'd like to raise.

I am currently using a chain with the following components:
FewshotPrompt ( with SemanticSimilarityExampleSelector) -> LLM -> Outputparser

By default, this will give me the parsed text output of my LLM. 
For my purposes, I would need the output of this chain to include all intermediate steps (preferably in a dict).

For this chain that would be: 
1. The samples selected by the Example Selector
2. The generated Fewshot Prompt
3. The raw LLM output
4. The parsed LLM output

From the documentation, it is not apparent to me how this could be achieved with the current state of the library.
(The documentation also does not outline details about the usage of Callbacks in the LCEL language)

### Suggestion:

If this is currently implemented then add a simple example to the documentation. If this is not the case then some type of callback that allows collecting this data from intermediate steps should be added.

**Comment by DanielRoeder1** [comment]
The Problem with this type of implementation is that the FewshotTemplate needs to be provided with either examples or an example_selector in the init. Thus providing them in this manner does not seem to be an option.

**Comment by rosskipp** [comment]
@DanielRoeder1 I came across this post when trying to do something similar - you can use a RunnablePassthrough to get the results of intermediate components. here's a simple example:

```python
# This passthrough allows us to pass the prompt through the chain
llm_runnable = RunnableParallel(passed=RunnablePassthrough(), output=self.llm)

# each chain is just the prompt into the llm
chain = prompt | llm_runnable

results = chain.invoke({ "foo": "bar"})

prompt = results['passed']
llm_result = results['output']
```

This got a little unwieldy for my multi-part chains, so I ended up creating a few small chains in a class and saving off the intermediates as they were run to class variables, which worked out alright for my needs.

Hope that helps.
