### ISSUE TITLE
OpenAIEmbeddings vector different from the openai library and changes from time to time

### ISSUE THREAD

**Issue by KanaSukita** [langchain-ai/langchain#12314]
### System Info

I got different embedding results using OpenAIEmbeddings and the original openai library. Besides the embeddings from both OpenAIEmbeddings and openai change from time to time. Sometimes it returns the same results but sometimes it returns differently , especially after I exceeds the time limit.

I am using langchain-0.0.321. I tried dig a little deeper in the OpenAIEmbeddings source code and find that there is a process using the tokenizer. I tried use the same tokenizer in the original openai library and get the same result compared to not using it, so I think this is not the problem. Can someone explain a little bit why the results in different libraries and different requests may change? 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
import openai
from langchain.embeddings.openai import OpenAIEmbeddings

text = 'where are you going'
vec1 = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY).embed_query(text)
vec2 = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY).embed_query(text)

if not vec1 == vec2:
    print('vec1:', vec1[:3])
    print('vec2:', vec2[:3])

vec3 = openai.Embedding.create(input=[text], model='text-embedding-ada-002')['data'][0]['embedding']

if not (vec1 == vec3 or vec2 == vec3):
    print('vec1:', vec1[:3])
    print('vec2:', vec2[:3])
    print('vec3:', vec3[:3])
```

### Expected behavior

the results are as below
```
vec1: [0.0004729258755920449, -0.011402048647760918, -0.012062848996486476]
vec2: [0.00046853933082822383, -0.01143268296919534, -0.012086534739296315]

vec1: [0.0004729258755920449, -0.011402048647760918, -0.012062848996486476]
vec2: [0.00046853933082822383, -0.01143268296919534, -0.012086534739296315]
vec3: [0.00040566621464677155, -0.011434691026806831, -0.012049459852278233]

```

**Comment by hinthornw** [comment]
Seems that OpenAI's api is sometimes unfortunately indeterminate...

**Comment by pedrojrv** [comment]
Not sure if this got somewhere but I am observing the same issue.
