### ISSUE TITLE
Elevenlabs-langchain API should integrate very important parameter 'voice'

### ISSUE THREAD

**Issue by agilebean** [langchain-ai/langchain#12312]
### Feature request

The langchain API integration Elevenlabs should accomodate the very important parameter `voice`.

### Motivation

Without the voice parameter, the Elevenlabs langchain integration is unusable because `play()` switches the voice randomly with every execution.

### Your contribution

I tracked down the releveant code in the [Elevenlabs-langchain integration API](https://api.python.langchain.com/en/latest/_modules/langchain/tools/eleven_labs/text2speech.html#ElevenLabsText2SpeechTool.stream_speech) down to this section:

```
def _run(
        self, query: str, run_manager: Optional[CallbackManagerForToolRun] = None
    ) -> str:
        """Use the tool."""
        elevenlabs = _import_elevenlabs()
        try:
            speech = elevenlabs.generate(text=query, model=self.model)
            with tempfile.NamedTemporaryFile(
                mode="bx", suffix=".wav", delete=False
            ) as f:
                f.write(speech)
            return f.name
        except Exception as e:
            raise RuntimeError(f"Error while running ElevenLabsText2SpeechTool: {e}")

[[docs]](https://api.python.langchain.com/en/latest/tools/langchain.tools.eleven_labs.text2speech.ElevenLabsText2SpeechTool.html#langchain.tools.eleven_labs.text2speech.ElevenLabsText2SpeechTool.play)    def play(self, speech_file: str) -> None:
        """Play the text as speech."""
        elevenlabs = _import_elevenlabs()
        with open(speech_file, mode="rb") as f:
            speech = f.read()

        elevenlabs.play(speech)


[[docs]](https://api.python.langchain.com/en/latest/tools/langchain.tools.eleven_labs.text2speech.ElevenLabsText2SpeechTool.html#langchain.tools.eleven_labs.text2speech.ElevenLabsText2SpeechTool.stream_speech)    def stream_speech(self, query: str) -> None:
        """Stream the text as speech as it is generated.
        Play the text in your speakers."""
        elevenlabs = _import_elevenlabs()
        speech_stream = elevenlabs.generate(text=query, model=self.model, stream=True)
        elevenlabs.stream(speech_stream)
```

The calls to `elevenlabs.generate` and `elevenlabs.play` must be extended with the `voice` parameter.

After this change, the langchain calls `run`, `play`, and importantly, `stream_speech`, could be made analogue the calls from the ElevenLabs API, e.g. seen [in this repo](https://github.com/langchain-ai/langchain/issues/1076#issuecomment-1552363555):
```
  prediction = agent_chain.run(input=user_input.text)
    audio = generate(
        text=prediction,
        voice="Adam",
        model="eleven_monolingual_v1"
    )
```

**Comment by agilebean** [comment]
It's still valid and relevant as ever to fix this issue. Without it, the API from ElevenLabs is not usable!

**Comment by adam-clarey** [comment]
I'm also needing this feature

**Comment by agilebean** [comment]
please reopen, otherwise the Elevenlabs API is unusable!
