### ISSUE TITLE
Issue: Similarity_search on Vector Store does not work.

### ISSUE THREAD

**Issue by franva** [langchain-ai/langchain#12326]
### Issue you'd like to raise.

I am using Langchain + Chroma to do a Q&A program with a csv document as its knowledge base.

The CSV file looks like below:
[![enter image description here][1]][1]

Here is the CSV file:
https://1drv.ms/u/s!Asflam6BEzhjgbkdegCGfZ7FI4O1Og?e=2X6ior

And code for creating embedding:

    from langchain.document_loaders.csv_loader import CSVLoader
    from langchain.embeddings.openai import OpenAIEmbeddings
    from langchain.vectorstores.chroma import Chroma
    from langchain.text_splitter import RecursiveCharacterTextSplitter as RCTS
    
    file_path = "Test.csv"
    doc_pages = []
    
    csv_loader = CSVLoader(file_path)
    doc_pages = csv_loader.load()
    print(f"Extracted {file_path} with {len(doc_pages)} pages...")
    
    splitter = RCTS(chunk_size = 3000, chunk_overlap = 300)
    splitted_docs = splitter.split_documents(doc_pages)
    
    embedding = OpenAIEmbeddings()
    persist_directory = "docs_t/chroma/"
    
    vectordb = Chroma.from_documents(
        documents=splitted_docs,
        embedding=embedding,
        persist_directory=persist_directory
    )
    
    vectordb.persist()
    
    print(vectordb._collection.count())

Here is the Testing code:

    result = vectordb.similarity_search("what is the Support Item Name for 01_003_0107_1_1", k=3)
    for r in result:
        print(r.page_content, end="\n\n")

And I see this testing code returns all other non-relevant information.

Which part leads to this issue?

  [1]: https://i.stack.imgur.com/Ev3cn.png

**Comment by franva** [comment]
I am surprised to see nowadays even Github issues got something with AI chatbot, good job ~! :)

As to your suggestions:
1. I am not convinced that the OpenAI `OpenAIEmbeddings` is not capable of accurately capturing semantic similiarities. Even it is so, I am not sure how to prove this and fix this.
2. This might be true, as I looked at 2 different Document objects and found that yes indeed they look similar. But even this is the case, I still have to use this csv file. So what can be the solution to this?
3. The Chroma issue, I checked the both issues mentioned by the bot and found they didn't mention too much useful information for my case.

So still need some one experienced to look into this issue and suggest a solution.

Many thanks

**Comment by franva** [comment]
thanks @dosubot and @baskaryan Looking forward to the help from the expert. Really appreciated.

**Comment by franva** [comment]
The suggested options are not helpful.

**Comment by vilakshan2996** [comment]
I couldn't find any CSV files in the folder. If you come across more irrelevant items, why not try reducing the chunk size to 100 or even lower values? You can also consider adjusting the chunk_overlap since each token may be equivalent to the size of one word.

**Comment by franva** [comment]
Hi @vilakshan2996  I have tried the csv file in an incognito mode and it opens with the data.
Please try this link: https://1drv.ms/u/s!Asflam6BEzhjgbkdegCGfZ7FI4O1Og?e=2X6ior
Let me know if you still cannot get the CSV file.

I used to use 1500 as the chunk_size and 50 as the overlap which made it worse.

**Comment by vilakshan2996** [comment]
In your case, I think it would be better if you could convert the Excel sheet to a pandas DataFrame and create a column called 'document' that combines all the elements in each row in a meaningful way. Then, you can pass that 'document' to the vector database. It's better to split it by row here rather than using tokens. Here is the code I use in my case for a similar problem, but with only two columns.

`import pandas as pd
from langchain.document_loaders import DataFrameLoader
# Read all sheets into a dictionary
data = pd.read_excel("Technical Questions Cleaned.xlsx", sheet_name=None)

# Access individual DataFrames using sheet names
for sheet_name, df in data.items():
    df['text'] = "for technical question \"" + df['Question']+"\" this is the answer \""+df["Answer"]+"\""
    loader = DataFrameLoader(df, page_content_column="text")
    documents = loader.load()
    addToVectorDB(documents,"support")


def addToVectorDB(documents,collection_name):
    ## here we are using OpenAI embeddings but in future we will swap out to local embeddings
    embedding = OpenAIEmbeddings()
    vectordb = Chroma.from_documents(collection_name=collection_name,documents=documents, 
                                    embedding=embedding,persist_directory="db")
    # persiste the db to disk`

try with this, and give me a reply.

**Comment by franva** [comment]
Hi @vilakshan2996 ,

Appreciated for your help :)

I understood that you want to load the CSV file line by line, row by row, and re-write each row to be a meaningful sentence and provide these sentences to the vector store so that the accuracy will improve. (Please correct me if my understanding of your approach is not right.)

Here is one line of the data in the CSV file:

Support Item Number | Support Item Name | Registration Group Number | Registration Group Name | Support Category Number | Support Category Name | Unit | Quote | Start date | End Date | Non-Face-to-Face Support Provision | Provider Travel | Short Notice Cancellations. | NDIA Requested Reports | Irregular SIL Supports | Type
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01_002_0107_1_1 | Assistance With Self-Care Activities - Standard - Weekday Night | 107 | Daily Personal Activities | 1 | Assistance with Daily Life (Includes SIL) | H | No | 20230701 | 99991231 | Y | Y | Y | N | N | Price Limited Supports

Since there are so many columns, I literally do not know how to make a meaningful sentence which would include all columns.

I should have provided the extraction code earlier. I actually use CSVLoader and [the CSVLoader generates one document per row, that document is generated using all columns of the corresponding row.](https://github.com/langchain-ai/langchain/issues/6961#issuecomment-1614517423)

So if you just want to have each row as a separated document and save these documents into the vector store, it has already been done.

btw, here is the code which I extract the CSV data:

```

elif parts[1] == '.csv':
            csv_loader = CSVLoader(os.path.join(path, filename))
            pages = csv_loader.load()
            ............
```

**Comment by smttsp** [comment]
@franva, I am not sure where the discrepancy coming from and I won't try to predict. But I can guide you a little bit with debugging as I've been through the same things today.

I would start with CSVLoader, and see if there is any anomaly. In my case, I had a problem with that (yours doesn't seem to be the case but 🤷)

This is how I loaded, you might wanna try something similar:
```
    loader = CSVLoader(
        file_path=file_path,
        source_column="text",
        metadata_columns=["label"],
    )
```

Once you load, check the docs. Then check what is inside the vector_db. You can pull the embeddings from vector_db as follows:

```
embeds = vector_db._collection.get(include=['embeddings', "metadatas"])
embeds["embeddings"] # --> gives you all the embeddings in vector_db
embeds["metadatas"] # --> gives you all the metadatas in vector_db
```
Check what is inside `embeds`. Play with the data, this step helped me a lot to understand how the data was stored.

The next thing you can do is creating embeddings manually. If you create an embedding from the first row of the csv file, then `top_k_results` should contain it as well. You can even 

```
    oe_embedder = OpenAIEmbeddings()
    for text, label in zip(df.text, df.label):
        embedding_vector = oe_embedder.embed_query(text)
        top_k_results = vector_db.similarity_search_by_vector(embedding_vector, k=5)
```

you can even compare embedding of the first row with all the embeddings in vector_db. You should get `1.0` among the results. You can do something like this:

```
    mx = -1
    for embed, meta in zip(embeds["embeddings"], embeds["metadatas"]):
        cur_cor = numpy.dot(embed, txt_embed)
        if cur_cor > mx:
            mx = cur_cor
            print(cur_cor, meta["label"], "---", meta["text"])
```

Overall, I think debugging could help you (or anyone facing similar problems) to learn so much more than getting the answer here.

Just sharing based on my experience today. Hope it helps!
