### ISSUE TITLE
GPT-4 reads the images

### ISSUE THREAD

**Issue by K1yomi** [langchain-ai/langchain#12323]
### System Info

GPT-4 can now read images. How to combine images and text in PDF or WORD when calling the API?

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

document loader?

### Expected behavior

maybe we can have a document loader that loads text and images at the same time.

**Comment by hinthornw** [comment]
OpenAI has not yet provided public API access
