### ISSUE TITLE
Unable to filter results in Neo4j Vectorstore.as_retriever() method using filter paramter in search_kwargs

### ISSUE THREAD

**Issue by snatthani** [langchain-ai/langchain#12335]
### Issue you'd like to raise.

Hello Team,

I am trying to build a QA system with text files as its knowledge base. While creating embeddings I have provided different metadata tags to documents.

I want to use this metadata to filter documents before sending them to LLM to generate answer.

I am using as_retriever() method to filter the documents based on 'key':'value' pair. Code below
```
vectordb.as_retriever(
    search_type="similarity",
    search_kwargs = {
        'filter' : {'key1' : 'value1'}
    }
)
```

This method works great to filter out the documents when I am using ChromaDB as VectorStore, but does not work when I use Neo4j as VectorStore. It returns the same results with or without filter using Neo4j

To figure out the issue, I checked langchain's source code for implementation of ChromaDB and Neo4j Vectorstore.

In ChomaDB the similarity_search() method is implemented as follows - 

https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/chroma.py
![image](https://github.com/langchain-ai/langchain/assets/19748080/8c2e2feb-baa0-45bc-9f19-73aa4c86044d)

Here the filter parameter is passed to the next function - self.similarity_search_with_score(query, k, filter=filter).

But when I checked the same method for Neo4j
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/neo4j_vector.py
![image](https://github.com/langchain-ai/langchain/assets/19748080/834ff3b7-bd20-454d-904e-83a765a1986f)

Here the filter parameter or the **kwargs is not passed to the next function -
self.similarity_search_by_vector(
            embedding=embedding,
            k=k,
            query=query,
     )

Please check if this is what is causing the issue.

Also let me know if something is wrong in my implementation.

Thanks in Advance

**Comment by mkampman** [comment]
@snatthani You beat me by 5 minutes :). I encountered the same issue and came to the same conclusion, the **kwargs is not passed to the  self.similarity_search_by_vector function.

**Comment by snatthani** [comment]
@mkampman , good to know that other people are also facing similar issue, I thought I am doing something wrong at my part.

**Comment by snatthani** [comment]
@dosu-bot

I tried your suggested solution, but it does not completely work for me.

I am trying to build a QA system using Neo4j as my VectorDB, where I have multiple pdfs and each pdf has multiple tags assigned to it as metadata. Different pdf documents can have same tags.

From each pdf, multiple text chunks are created and embeddings for each chunk is stored in VectorDB. Also each chunk from a pdf is assigned the same metadata tags that was present for the pdf.

I want to use this metadata tags to filter out chunks before sending them to LLM to generate answer.

The as_retriever() method will retrieve top 'k' relevant chunks.

Your suggested solution will then apply filter on these top 'k' chunks and return chunks. Therefore the number of chunks to be send to LLM will be less than 'k'.

What I want is filtering at the retrieval stage itself just like it happens in ChromaDB, so that top 'k' chunks have same metadata tag.

Also this solution only uses 1 filter and might not work if multiple filter conditions are there.

As, I mentioned above, for Neo4j vectorstore source code the filter parameter or the **kwargs is similarity_search() method is not passed to the next function -
self.similarity_search_by_vector(
embedding=embedding,
k=k,
query=query,
)

Can we have a solution where the Neo4j retrieval system itself does the filtering, this might require changes in the underlying code of LangChain.

**Comment by Praniyendeev** [comment]
I am having a similar issue, did this prove to be helpful??

**Comment by sxIhsan** [comment]
same problem here

**Comment by economy** [comment]
@dosubot's recent suggestion does not work due to how Neo4j does vector index queries. The fix would be easy enough from langchain's end, but pre-filtering on an ANN search doesn't seem to be possible in the current Neo4j implementation. 

Some discussion and possible workarounds here: https://community.neo4j.com/t/vector-search-index-pre-filtered-query/64465/10

**Comment by sharjeelshahid** [comment]
Neo4jVector.from_existing_graph functions provided the one argument 'retrieval_query' to transform the cipher query results. So you may use it to add your required filters. Following is the example...

docsearch = Neo4jVector.from_existing_graph(
        embedding=OpenAIEmbeddings(),
        url=NEO4J_URI,
        username=NEO4J_USERNAME,
        password=NEO4J_PASSWORD,
        index_name=VECTOR_INDEX_NAME,
        node_label=VECTOR_NODE_LABEL,
        text_node_properties=[VECTOR_SOURCE_PROPERTY],
        embedding_node_property=VECTOR_EMBEDDING_PROPERTY,
        # retrieval_query=retrieval_query_window,
        **retrieval_query=filters + "\n" + retrieval_query_window,**
    )

**Comment by blacksmithop** [comment]
Here's what such a query would look like in Cypher
```cypher
MATCH (n)
WHERE n.embedding IS NOT NULL AND n.custom_id = $custom_id
WITH n AS node, vector.similarity.cosine(n.embedding, $embedding) AS score
ORDER BY score DESC
LIMIT 10
RETURN node, score
```
This works as intended

Here I filtered the results based on a property `custom_id` and ranked the matches based on cosine similarity.
The Cypher for Cosine similarity is created at [neo4j_vector.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/neo4j_vector.py#L998-L1007) and your custom filter query comes in [here](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/neo4j_vector.py#L1009-L1010)

I don't know why this does not work as intended through Langchain. I would appreciate  if someone could look into this.
