### ISSUE TITLE
How to pass existing doc embeddings to FAISS ?

### ISSUE THREAD

**Issue by shaktisd** [langchain-ai/langchain#1233]
I have some existing embeddings created from 
`doc_embeddings = embeddings.embed_documents(docs)`

how to pass doc embeddings to FAISS vector store
`from langchain.vectorstores import FAISS`

right now FAISS.from_text() only takes an embedding client and not existing embeddings.

**Comment by hetthummar** [comment]
@shaktisd I am also facing the same problem. Did you got an answer?

**Comment by Xmaster6y** [comment]
You can use the `from_embeddings` method.
```python
texts = [d.page_content for d in docs]
doc_embeddings = embeddings.embed_documents(docs)
text_embedding_pairs = zip(texts, doc_embedding_pairs)
faiss = FAISS.from_embeddings(text_embedding_pairs, embeddings)
```

**Comment by shaktisd** [comment]
Thanks for suggesting the solution.
