### ISSUE TITLE
Issue with OpenAI tokenizer not functioning as expected in streaming mode

### ISSUE THREAD

**Issue by OrelOfficely** [langchain-ai/langchain#12339]
### System Info

I am developing an app utilizing the streaming functionality in Python 3.10. I've crafted my own generator and callback for this purpose. However, I've stumbled upon an issue when setting llm.streaming to true and utilizing a callback - the OpenAI tokenizer appears to malfunction, displaying a token count of 0$ which is not the expected behavior.

### Who can help?

@agola11 
@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

    def arun(self, g, chat_history, query:str, config:dict, agent_id:str):
        try:
            llm = ChatOpenAI(
                temperature=0, 
                verbose=False, 
                model='gpt-4',  
                streaming=True,  
                callbacks=[ChainStreamHandler(g)]
            )
            with get_openai_callback() as cb:
                custom_agent = customAgent.run(g, llm, chat_history, query, config, agent_id)
                print(cb)
                return custom_agent
        finally:
            g.close()
            
 

Tokens Used: 0
        Prompt Tokens: 0
        Completion Tokens: 0
Successful Requests: 0
Total Cost (USD): $0.0

### Expected behavior

I aim to have the tokenizer working correctly to gauge the token usage and its corresponding cost. Any guidance or suggestions to rectify this problem would be greatly appreciated

**Comment by rsarvis** [comment]
I'm getting same problem...

```
chain = LLMChain(
    llm = ChatOpenAI(
        streaming=True
    ),
    prompt = ChatPromptTemplate.from_messages([('human', "What should I call my store that sells {product}")])
)
with get_openai_callback() as cb:
    output = chain.run(product="paper airplanes")
print(cb)
```

yields:

Tokens Used: 0
	Prompt Tokens: 0
	Completion Tokens: 0
Successful Requests: 0
Total Cost (USD): $0.0

But:

```
chain = LLMChain(
    llm = ChatOpenAI(
        streaming=False
    ),
    prompt = ChatPromptTemplate.from_messages([('human', "What should I call my store that sells {product}")])
)
with get_openai_callback() as cb:
    output = chain.run(product="paper airplanes")
print(cb)
```

yields

Tokens Used: 90
	Prompt Tokens: 17
	Completion Tokens: 73
Successful Requests: 1
Total Cost (USD): $0.0001715

**Comment by girithodu** [comment]
@OrelOfficely @rsarvis were you able to figure out how to get token tracking working when you have streaming = True?
