### ISSUE TITLE
Issue: Update `anyio` dependency

### ISSUE THREAD

**Issue by francesca-raimondi-causalens** [langchain-ai/langchain#12337]
### Issue you'd like to raise.

Since version `v0.0.299` `LangChain` depends on `anyio = "<4.0"`.

### Suggestion:

 Could you please relax the `anyio` dependency to support a wider range of versions `<5.0` as `4.0.0` has been out since August?

**Comment by bustedware** [comment]
Ran into a different but somewhat related issue
```
error: anyio 4.0.0 is installed but anyio<4.0 is required by {'langchain'}
```

Even though:
```
> pip3 list | findstr anyio
anyio                        3.7.1
```

hope this helps
