### ISSUE TITLE
filter query within vector_store.similarity_search() is not working as expected.

### ISSUE THREAD

**Issue by msunkarahend** [langchain-ai/langchain#12366]
### System Info

azure-search-documents==11.4.0b8, langchain

### Who can help?

@hwchase17 
@agola11 
@dosu-bot

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

    fields in azure search index and their content is as below:

    
    Code:
    memory_vector_store: AzureSearch = AzureSearch(
        azure_search_endpoint=vector_store_address,
        azure_search_key=vector_store_password,
        index_name=memory_index_name,
        embedding_function=embeddings.embed_query
        )
 user_id = "dtiw"
session_id = "ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm"
relevant_docs = memory_vector_store.similarity_search(
        query=query,
        k=4, 
        search_type="similarity",
        filters = f"user_id eq '{user_id}' and session_id eq '{session_id}'"
    )
    if relevant_docs:
        prev_history = "\n".join([doc.page_content for doc in relevant_docs])
    else:
        logging.info(f"relevant docs not found")
        prev_history = ""

logging.info(f" the relevant docs are {relevant_docs}")
logging.info(f"the previous history is {prev_history}")

### Expected behavior

expected answer:
 [Document(page_content='User: who are you?\nAssistant: I am an AI assistant here to help you with any company-related questions you may have. How can I assist you today?', metadata={'id': 'ZHRpd2FyaUBoZW5kcmlja3Nvbi1pbnRsLmNvbWYwZTZjODNlLTk4ZGEtNGI4Mi04YTkwLTU0NGE1NTEwNzZlZjIwMjMxMDI2MTk0MzI4', 'session_id': 'ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm', 'user_id': 'dtiw', '@search.score': 0.78985536, '@search.reranker_score': None, '@search.highlights': None, '@search.captions': None}), 
 
 Document(page_content='User: Hi, whats up?\nAssistant: Please stick to the company-related questions. How can I assist you with any company-related queries?', metadata={'id': 'ZHRpd2FyaUBoZW5kcmlja3Nvbi1pbnRsLmNvbWYwZTZjODNlLTk4ZGEtNGI4Mi04YTkwLTU0NGE1NTEwNzZlZjIwMjMxMDI2MTk0MjU5', 'session_id': 'ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm', 'user_id': 'dtiw', '@search.score': 0.7848022, '@search.reranker_score': None, '@search.highlights': None, '@search.captions': None})]

'User: who are you?\nAssistant: I am an AI assistant here to help you with any company-related questions you may have. How can I assist you today?'
'User: Hi, whats up?\nAssistant: Please stick to the company-related questions. How can I assist you with any company-related queries?'

Given answer:
the relevant docs are <iterator object azure.core.paging.ItemPaged at 0x7d82ae149b10>
the previous history is

**Comment by msunkarahend** [comment]
@dosu-bot In the search index , I have 
1. id
2. user_id
3. session_id
4. content
5. content_vector fields.

I am trying to retrieve top 4 chunks (content) from the index filtering with user_id and session_id. I expected the following code to work but it is not working.

  memory_vector_store: AzureSearch = AzureSearch(
      azure_search_endpoint=vector_store_address,
      azure_search_key=vector_store_password,
      index_name=memory_index_name,
      embedding_function=embeddings.embed_query
      )
  user_id = "dtiw"
  session_id = "ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm"
  
  relevant_docs = memory_vector_store.similarity_search(
  query=query,
  k=4,
  search_type="similarity",
  filters = f"user_id eq '{user_id}' and session_id eq '{session_id}'"
  )
  if relevant_docs:
  prev_history = "\n".join([doc.page_content for doc in relevant_docs])
  else:
  logging.info(f"relevant docs not found")
  prev_history = ""

I also tried

    relevant_docs = memory_vector_store.similarity_search(
        query=query,
        k=4, 
        search_type="similarity",
        search_kwargs = {'filters': f"user_id eq '{user_id}' and session_id eq '{session_id}'"}
    )

not working. can you resolve this issue.

**Comment by msunkarahend** [comment]
@dosu-bot I satisified all the above conditions. but still I am not able to retrieve any chunks. the relevant_docs is empty. I dont have any error. but the relevant docs are empty even though the index has content related to that filtered query with some similarity to the query. can you please further debug this issue.

**Comment by msunkarahend** [comment]
@dosu-bot

when i remove the filtered expression from the code, it is retreiving the chunks (content) from the index. I am pasting the code below again  for reference.

relevant_docs = memory_vector_store.similarity_search(
    query=query,
    k=4,
    search_type="similarity",
    filters = f"user_id eq '{user_id}' and session_id eq '{session_id}'"
)

The embedding function is provided by the langchain in its source code, i am not providing any model from my side. 

when i tried from azure portal the filter expression worked separately.

user_id eq 'dtiw'

session_id eq 'ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm'

but together 
user_id eq 'dtiw' and session_id eq 'ZjBlNmM4M2UtOThkYS00YjgyLThhOTAtNTQ0YTU1MTA3NmVm' didn't work.

**Comment by msunkarahend** [comment]
@dosu-bot the azuresearch.py doesn't accept the filters to be a dictionary. it accepts only the filters as str. I am using azure cognitive search as the vector store to store the memory. so please help me write Odata $filter expression for multiple filters that is accepted by azuresearch.py of langchain to retrieve the content from the cognitve search

**Comment by glejdis** [comment]
@msunkarahend how did you solve this issue? I am facing the same problem when using hybrid search in AzureSearch.
