### ISSUE TITLE
[Feature Request]: Self-RAG support (NEW TECHNIQUE) 

### ISSUE THREAD

**Issue by casper-hansen** [langchain-ai/langchain#12375]
### Feature request

Self-RAG is a new open-source technique (MIT license) that implements:
1. **Adaptive retrieval via retrieval tokens:** allows you to fine-tune LLMs to output `[Retrieval]` tokens mid-generation to indicate when to perform retrieval. It has been empirically shown to improve open-source models to match ChatGPT level of performance in RAG tasks.
2. **Critique tokens:**
    - w_rel (default 1.0): This variable controls the emphasis on relevance during beam search.
    - w_sup (default 1.0): This variable controls the emphasis on support from the document during beam search.
    - w_use (default 0.5): This variable controls the emphasis on overall quality during beam search.

Requirements:
- make it compatible with vLLM for inference such that any fine-tuned Self-RAG model can be deployed in a framework with PagedAttention implemented.
- able to query vector database

Website: https://selfrag.github.io/
Model: https://huggingface.co/selfrag/selfrag_llama2_7b
Code: https://github.com/AkariAsai/self-rag

![image](https://github.com/run-llama/llama_index/assets/27340033/9911d86d-e44e-49b1-95ef-87f3b9a9e0e6)
![image](https://github.com/run-llama/llama_index/assets/27340033/b262766c-2318-431c-9714-a0738ad66fc4)

### Motivation

The main motivation behind the proposal is to allow for more precise responses while using RAG to help reduce hallucinations.

### Your contribution

I am not available to help with a contribution.

**Comment by RonB** [comment]
Hi Casper,
Here is an [interesting video](https://youtu.be/i4V9iJcxzZ4) on that topic.
There is a lot more to it than just a change in the retrieval of the data (i.e. the vectorstore)
It is an interesting approach and I wonder (and doubt) if this could be achieved by changing the model to create the embedding vectors. If you would use another approach as proposed in the video and in the paper, where you will need to train a critics model and a retriever model and try to mimic this by a langchain agent that breaks up the different steps in individual llm calls, I wonder how efficient and costly this would be. Thoughts?

**Comment by meambobbo** [comment]
I haven't fully dug into self-rag yet, but very intrigued. it looks like they supply their own 7B or 13B models based on 'diverse' training data. The selfrag models are based off Llama2 and seem to have two key features:
- they can inject their own special tokens into text/prompts
- they can perform inference on prompts containing their special tokens without getting confused by them
- they retain LLM ability of next text prediction in addition to the injected special tokens

@RonB seems correct that the approach is a framework that is more than just a retriever implementation. It sounds more like a framework that would incorporate langchain than something langchain would incorporate.

Looking at requirements.txt of the original author's implementation in the code link from OP, they're not using langchain. I think the real request here would be a rewrite of their implementation that leverages langchain and encapsulates an entire selfrag lifecycle into a langchain chain, so it could be called like a function. The way they deal with retrieved content and define retrievers also seems very specific, whereas langchain tries to make this more abstract and cross-compatible.

The other big piece here is that it looks like you need to fine-tune their models (using their tooling) against your dataset. Their codebase and provided scripts seem to be a lot of the meat-and-potatoes, which incorporate mechanisms to generate and train models against your data.

They reference a small sample set of wikipedia as provided vector-embedded data for demo purposes. A lot of their testing seems to incorporate larger datasets of wikipedia you can download, but they do not provide. Might be reading that wrong.

While their doc seems very well-intended, it seems quite easy to quickly get lost.
