### ISSUE TITLE
Action: Python REPL Action Input: pip install rust-python Observation: invalid syntax (<string>, line 1)

### ISSUE THREAD

**Issue by viswatejagajulavarthy** [langchain-ai/langchain#1239]
pip install rust-python gave  invalid syntax (<string>, line 1)
should the agent not have permission to install the necessary packages?

'''
https://replit.com/@viswatejaG/Python-Agent-LLM

 agent.run("run rust code in python function?")

> Entering new AgentExecutor chain...
 I need to find a way to execute rust code in python
Action: Python REPL
Action Input: import rust
Observation: No module named 'rust'
Thought:Retrying langchain.llms.openai.BaseOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
 I need to find a library that allows me to execute rust code in python
Action: Python REPL
Action Input: pip install rust-python
Observation: invalid syntax (<string>, line 1)
Thought:Retrying langchain.llms.openai.BaseOpenAI.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=600).
 I need to find a library that allows me to execute rust code in python
Action: Google Search
Action Input: rust python library
'''

**Comment by wiseman** [comment]
This is just the LLM making a syntax mistake. I've seen it do the same thing. I had one run where it tried to (incorrectly) execute `pip install <package>` as Python code, then it tried to use a non-existent `Terminal` tool to run `pip install <package>` and then, finally and successfully, `import pip; pip.main(['install', '<package>'])`.

I don't think this is an issue with langchain, unless you think the [PythonREPL prompt](https://github.com/hwchase17/langchain/blob/5457d48416a19e8811d70429b14410b0362d4920/langchain/agents/load_tools.py#L30) could be tweaked in some way to guide the LLM better.

**Comment by MahimaYdv0** [comment]
I'm facing this same issue, @viswatejagajulavarthy what worked for you??
