### ISSUE TITLE
sourceDocuments are not returned when streaming with RetrievalQAChain but returns properly when *not* using streaming

### ISSUE THREAD

**Issue by carlos-monsterlabz** [langchain-ai/langchain#12400]
### System Info

Langchain: 0.0.166
Ubuntu: 22.04
NodeJS: 18.18.2

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a retrieval chain with streaming:
```
this.chain = RetrievalQAChain.fromLLM(this.model, this.store.asRetriever(), {
      prompt: PromptTemplate.fromTemplate(this.prompt),
      returnSourceDocuments: true,
      stream: true
    });
```
2. Call `stream()` on the chain:
```
const response = await this.chain.stream({
      query: question,
      callbacks: [
        {
          handleLLMNewToken(token) {
            onChunkCallback(token);
          },
          handleLLMEnd(result, res2) {
            onEnd(result, res2);
          }
        },
      ]
    });
```
3. View the `sourceDocuments` property on the returned response, and set `verbose: true` on the chain and observe the chain output shows a `sourceDocuments` property that is an empty array.

### Expected behavior

The `sourceDocuments` property is populated the same way it is when not using streaming which shows the source documents the model used to generate the answer.

**Comment by EdwardPrentice** [comment]
Yes it's still relevant and it affects the latest version of langchain, specifically the js/ts library. Example code:

```
const result = await chain.stream({ question: myQuestion, chat_history: myHistory});
console.log(result);
> ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
```

From the result object there is no way to access the source documents. Changing `.stream` to `.invoke` solves the problem but now the answer cannot be streamed (eg in the case of a chat application).

**Comment by varunbharill** [comment]
Hi @EdwardPrentice , 
Were you able to solve this? 
I am writing a backend django API to stream response in langchain but I am not sure how to do bot - stream the response and return the source docs. 

Any thoughts?
