### ISSUE TITLE
Issue: Passing multiple arbitrary parameters to a tool.

### ISSUE THREAD

**Issue by Maximiliano-Villanueva** [langchain-ai/langchain#12410]
### Issue you'd like to raise.

I'm building an agent to interact with neo4j with a custom chain (I'm aware of the chains already implemented for this case), my problem comes when I try to pass multiple arbitrary arguments to my tool. What i want to know is how can I propagate arguments from the creation of the agent / tool, and how to propagate arguments thorugh the execution of the AgentExecutor. Here is my code so far.

I have a chain that I use as a tool:

```
class LLMCypherGraphChain(Chain, BaseModel):
    input_key: List[str] = ["question", "content_type"]
```
Then i create my AgentExecutor and use the initialize_agent method, I instanciate the class previously defined and use the run method as a function to execute.

```
class GraphAgent(AgentExecutor):
@classmethod
    def initialize(cls,...)
        cypher_tool = LLMCypherGraphChain(
            llm=llm,
            input_key=["question", "content_type"],
            graph=graph,
            verbose=verbose,
            memory=readonlymemory
        )

        # Load the tool configs that are needed.
        tools = [
            Tool(
                name="Cypher search",
                func=cypher_tool.run,
                description="""
                Utilize this tool to search within a database, specifically designed to answer x questions.
                This specialized tool offers streamlined search capabilities to help you find the movie information you need with ease.
                Input should be full question.""",  # noqa
            )
        ]

        agent_chain = initialize_agent(
            tools,
            llm,
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            verbose=verbose,
            memory=memory,
            return_intermediate_steps=True
        )
    def run(self, *args, **kwargs):
        return super().run(*args, **kwargs)
```

So at this point I only need to instanciate the agent and run it. 

```
self.agent_executor = GraphAgent.initialize(
           ...
        )

res = self.agent_executor({"question": "my question",
                           "input": "my question",
                           "random_param": "my other param"})
```

So the problem is that I have this agent stored in a variable to avoid recreating it, that means self.agent_executor is only initialized once but then I want to be able to propagate the question and random_param to my tool.

I have seen some posts about passing parameters to tools but none of them actualy solved this problem. I am not sure if using agent_kwargs in the initialize_agent would be a solution (I'm not quiet sure how that propagates to the tools) but that only would happen once, when the instanciation is done. 

Right now Im getting this error, so I am not understanding how arguments are propagated:

ERROR:root:A single string input was passed in, but this chain expects multiple inputs ({'question', 'content_type'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`

Any help is appreciated! thanks!

**Comment by Maximiliano-Villanueva** [comment]
The problem is that the LLMChain is generating the input for the run method of my LLMCypherGraphChain. In the "plan" method defined by:
```
    def plan(
        self,
        intermediate_steps: List[Tuple[AgentAction, str]],
        callbacks: Callbacks = None,
        **kwargs: Any,
    ) -> Union[AgentAction, AgentFinish]:
        """Given input, decided what to do.

        Args:
            intermediate_steps: Steps the LLM has taken to date,
                along with observations
            callbacks: Callbacks to run.
            **kwargs: User inputs.

        Returns:
            Action specifying what tool to use.
        """
        full_inputs = self.get_full_inputs(intermediate_steps, **kwargs)
        full_output = self.llm_chain.predict(callbacks=callbacks, **full_inputs)
        return self.output_parser.parse(full_output)
```

the prediction of the llm is:
```
'Action:\n```\n{\n  "action": "Cypher search",\n  "action_input": "Who directed the green mile?"\n}\n```\n'
```

I'm still unable to identify how can i modify this action_input to adapt it to the input expected by the run method of my chan which is a Dict with a certain format. And of course the dictionary is supposed contain parameters not generated by the LLM but rather propagated through the run method

**Comment by sudranga** [comment]
@Maximiliano-Villanueva In your tool description, there's no description of args that the tool needs (question, content_type). The args need to be described for the prompt to the llm to be properly formatted and for the agent to extract them and pass it on to the appropriate tool.

**Comment by Maximiliano-Villanueva** [comment]
> @Maximiliano-Villanueva In your tool description, there's no description of args that the tool needs (question, content_type). The args need to be described for the prompt to the llm to be properly formatted and for the agent to extract them and pass it on to the appropriate tool.

@sudranga are you talking about args_schema? Because I have also tried that, either way Im confused on how this is going to change when the StructuredChatAgent, which is the agent generated by STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, has the following piece of code: 

```
    def _take_next_step(
        self,
        name_to_tool_map: Dict[str, BaseTool],
        color_mapping: Dict[str, str],
        inputs: Dict[str, str],
        intermediate_steps: List[Tuple[AgentAction, str]],
        run_manager: Optional[CallbackManagerForChainRun] = None,
    ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
        """Take a single step in the thought-action-observation loop.

        Override this to take control of how the agent makes and acts on choices.
        """
         ...
        for agent_action in actions:
            if run_manager:
                run_manager.on_agent_action(agent_action, color="green")
            # Otherwise we lookup the tool
            if agent_action.tool in name_to_tool_map:
                tool = name_to_tool_map[agent_action.tool]
                return_direct = tool.return_direct
                color = color_mapping[agent_action.tool]
                tool_run_kwargs = self.agent.tool_run_logging_kwargs()
                if return_direct:
                    tool_run_kwargs["llm_prefix"] = ""
                # We then call the tool on the tool input to get an observation
                observation = tool.run(
                    agent_action.tool_input,
                    verbose=self.verbose,
                    color=color,
                    callbacks=run_manager.get_child() if run_manager else None,
                    **tool_run_kwargs,
                )

        return result
```

What i want to point out from this piece of code is that tool.run always passes a string (agent_action.tool_input) since this is the output of the LLMChain, and of course I won't modify the prompt to pass sensitive information... I was thinking about inheriting from this class and overwrite that function.

Btw if this is not what you meant please clarify your answer.

**Comment by sudranga** [comment]
Hi, Yes. But, tool_input is a union of str, dict. If you have tried describing the args, what error do you see? It would also help if you paste your complete code

**Comment by Maximiliano-Villanueva** [comment]
right now I'm defining the tool like this, as you can see I'm already providing the args_schema, which I see that is correct in the args attribute of the Tool, but if you check the call to the tool.run as I mentioned in the previous message it never checks for those arguments but rather always passes the agent_action.tool_input which is the output defined in the LLMChain. here is the code:


```
# Third party imports
from typing import Optional
from langchain.agents import initialize_agent
from langchain.agents.agent import AgentExecutor
from langchain.agents.tools import Tool
from langchain.agents import AgentType

from langchain.base_language import BaseLanguageModel

from langchain.memory import ReadOnlySharedMemory
from langchain.memory.buffer import ConversationBufferMemory


# Internal imports
from database.base import GraphDB
from modules.agents.graph_query_engine.chains import LLMCypherGraphChain

from pydantic import BaseModel, Field

class ToolInputSchema(BaseModel):
    question: str = Field()
    content_type: str = Field()
    input: str = Field()

class GraphAgent(AgentExecutor):
    """Graph agent"""

    @staticmethod
    def function_name() -> str:
        return "Graph Agent"

    @classmethod
    def initialize(cls,
                   llm: BaseLanguageModel,
                   graph: GraphDB,
                   verbose: bool = True,
                   *args,
                   **kwargs):
        if llm is None:
            raise Exception(f"llm is None")

        memory = ConversationBufferMemory(
            memory_key="chat_history",
            return_messages=True
        )

        # set the output key so that memory doesn't error on save
        memory.output_key = "output"

        readonlymemory = ReadOnlySharedMemory(memory=memory)
        
        cypher_tool = LLMCypherGraphChain(
            llm=llm,
            input_key=["question", "content_type"],
            graph=graph,
            verbose=verbose,
            memory=readonlymemory
        )
        
        # Load the tool configs that are needed.
        tools = [
            Tool(
                name="Cypher search",
                func=cypher_tool.run,
                description="""
                Utilize this tool to search within a database, specifically designed to answer x questions.
                This specialized tool offers streamlined search capabilities to help you find the movie information you need with ease.
                Input should be full question.""",  # noqa
                args_schema=ToolInputSchema
            )
        ]

        agent_chain = initialize_agent(
            tools,
            llm,
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            verbose=verbose,
            memory=memory,
            return_intermediate_steps=True
        )

        return agent_chain

    def run(self, *args, **kwargs):
        return super().run(*args, **kwargs)

```

**Comment by dmenini** [comment]
It indeed would be a nice feature, and this is actually a huge limitation of tools. I may give it a go as soon as I have some time.

I also faced this issue. My problem was that the external API called by the tool required a user-specific token to correctly run. This token of course is different for each request to my service, thus it has to be injected into the run method as per your example, as recreating the tool/agent at each call would be too much overhead. 

I ended up doing this:
1. Define your tool as instance of BaseTool
2. Add a custom method to the class to inject the data that you need
3. In  the _run method use the value injected by using the custom method
4. In your code, inject the data before calling the agent

Snippet:

```python
class CustomTool(BaseTool):

    data: Optional[Any] = None

    def inject_data(self, data: Optional[Any]) -> None:
        self.data = data

   def _run(self, query: str, *tool_args: Any, **tool_kwargs: Any) -> str:
        if self.data is None:
            raise RuntimeError('Please inject data before using this tool')

        ...
```

And in your execution code:

```python
tool = self.chain.lookup_tool('My tool')
tool.inject_data(data)
```

I hope this helps you as a workaround until a more elegant solution becomes possible

**Comment by sudranga** [comment]
Ah, sorry i missed the part where not all of the tool args is not injected by the LLM. Let me check if something is possible via storing context in the run manager.

**Comment by Maximiliano-Villanueva** [comment]
> It indeed would be a nice feature, and this is actually a huge limitation of tools. I may give it a go as soon as I have some time.
> 
> If it helps, I also faced this issue. My problem was that the external API called by the tool required a user-specific token to correctly run. This token of course is different for each request to my service, thus it has to be injected into the run method as per your example, as recreating the tool/agent at each call would be too much overhead.
> 
> I ended up doing this:
> 
> 1. Define your tool as instance of BaseTool
> 2. Add a custom method to the class to inject the data that you need
> 3. In  the _run method use the value injected by using the custom method
> 4. In your code, inject the data before calling the agent
> 
> Snippet:
> 
> ```python
> class CustomTool(BaseTool):
> 
>     data: Optional[Any] = None
> 
>     def inject_data(self, data: Optional[Any]) -> None:
>         self.data = data
> 
>    def _run(self, query: str, *tool_args: Any, **tool_kwargs: Any) -> str:
>         if self.data is None:
>             raise RuntimeError('Please inject data before using this tool')
> 
>         ...
> ```
> 
> And in your execution code:
> 
> ```python
> agent_executor = ...
> tool = agent_executor.lookup_tool('My tool')
> tool.inject_data(data)
> ```
> 
> I hope this helps you as a workaround until a more elegant solution becomes possible

Thanks for your response, this is what I was thinking on doing but I wanted to know if there was a cleaner and more efficient way to do this.

**Comment by sudranga** [comment]
I added an example test case at : https://github.com/langchain-ai/langchain/pull/12600. HTH.

**Comment by Maximiliano-Villanueva** [comment]
@sudranga I just checked your PR and it was exactly what I was looking for!
