### ISSUE TITLE
Adding a memory to the openAPI agent

### ISSUE THREAD

**Issue by MohamadAlAdraa** [langchain-ai/langchain#12424]
### Issue you'd like to raise.

In the create_openapi_agent there is an argument called **shared_memory** and it is passed to the LLM in the **ZeroShotAgent**. What is the difference between this one:
agent = ZeroShotAgent(
        llm_chain=LLMChain(llm=llm, prompt=prompt, **memory=shared_memory**), (this is a readonly memory as defined in the doc)
        allowed_tools=[tool.name for tool in tools],
        **kwargs,
    )
and adding it to the AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        callback_manager=callback_manager,
        verbose=verbose,
        **memory=memory,** (I added it myself)
        **(agent_executor_kwargs or {}),
    )

**Comment by keenborder786** [comment]
Hello, I don't see any argument called `shared memory` in the`'create_openapi_agent' function. Therefore, I'm not so sure what you are referring to. To pass memory to an agent, you need to provide memory to the `AgentExecutor` which is a `Chain` that operates according to the type of the agent we are using. To make the agent stateful by passing memory to the agent executor, you can do the following:

```python
AgentExecutor.from_agent_and_tools(
    agent=agent,
    tools=tools,
    callback_manager=callback_manager,
    verbose=verbose,
    return_intermediate_steps=return_intermediate_steps,
    max_iterations=max_iterations,
    max_execution_time=max_execution_time,
    early_stopping_method=early_stopping_method,
    agent_executor_kwargs={'memory': memory}
)
```
