### ISSUE TITLE
Developing an api request manager that automatically avoids rate limits

### ISSUE THREAD

**Issue by Ozziko** [langchain-ai/langchain#12423]
### Feature request

Currently: api-based models that pass rate limits raise an error and abort.
Desirable: sending api requests together in parallel, in a way that tracks their global token usage and response times, and waits as needed to avoid the rate limit.

### Motivation

Currently api-based models that pass rate limits raise an error and abort, but it's totally avoidable if the models track the token usage and wait as needed before calls.

### Your contribution

I'm not available to contribute more

**Comment by joliss** [comment]
It looks like [openlimit](https://github.com/shobrook/openlimit) implements some of this functionality for vanilla OpenAI in Python, so perhaps it's worth looking at how they do it.
