### ISSUE TITLE
ValueError: Could not parse output - map_rerank

### ISSUE THREAD

**Issue by rtomaf** [langchain-ai/langchain#12459]
### System Info

Langchain version: 0.0.325
Python version: Python 3.11.6

### Who can help?

@hwchase17

`chain_type="map_rerank"` is not working when the search cannot be found on the DB

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Code:

```
from dotenv import load_dotenv
from langchain.vectorstores.chroma import Chroma
from langchain.chains.retrieval_qa.base import RetrievalQA
from langchain.chat_models.openai import ChatOpenAI
from langchain.embeddings.openai import OpenAIEmbeddings
import langchain


load_dotenv()
chat = ChatOpenAI()
embeddings = OpenAIEmbeddings()

db = Chroma(
    persist_directory="emb",
    embedding_function=embeddings,   
)

retriever = db.as_retriever()
chain = RetrievalQA.from_chain_type(
    llm=chat,
    retriever=retriever,
    chain_type="map_rerank",
    verbose=True
)
result = chain.run("Who was Michael Jackson?") # <-- not in the database
print(result)
```

Prints:

```
raise ValueError(f"Could not parse output: {text}")
ValueError: Could not parse output: I don't know.
```

### Expected behavior

Print: "I don't know"

**Comment by sudranga** [comment]
I added this: https://github.com/langchain-ai/langchain/pull/11519. Looks like we may need to do something similar for retrievalqa chains.

**Comment by abdullaha1rafi** [comment]
Facing the similar issue. Is this solved?

**Comment by spagnoloe-capchase** [comment]
Same issue here, it seems sometimes the `LLMChain` returns a text that lacks the `Score`, and then the `RegexParser` fails in [here](https://github.com/langchain-ai/langchain/blob/1ea6d83188da1e9bb5baed57ac9e0fc969b77905/libs/langchain/langchain/output_parsers/regex.py#L28).
