### ISSUE TITLE
Issue: <It seems that my agent has no memory ability>

### ISSUE THREAD

**Issue by jwpaq** [langchain-ai/langchain#12469]
### Issue you'd like to raise.

During using the agent, I added memory to the agent, but the result seems to be no memory ability，my code is as follows:

`llm=ChatOpenAI(temperature=0, model="gpt-3.5-turbo-16k-0613")

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

agent = initialize_agent(
tools=tools_name,
llm=llm,
memory=memory,
verbose=True,
agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
)`

The results indicate that the agent has no memory, but memory does record the conversation

![image](https://github.com/langchain-ai/langchain/assets/149214596/b1132bdb-d885-494c-a057-a9b2c01b7a58)

**Comment by sudranga** [comment]
@jwpaq Can you try AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION ? A STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION agent ignores memory.
