### ISSUE TITLE
Get document ids from ConversationalRetrievalChain's reponse

### ISSUE THREAD

**Issue by rangelrey** [langchain-ai/langchain#12479]
### Feature request

Module: langchain.chains.conversational_retrieval.base.ConversationalRetrievalChain

`qa = ConversationalRetrievalChain(
            retriever=self.vector_store.as_retriever(),  # type: ignore
            combine_docs_chain=self.doc_chain,
            question_generator=LLMChain(
                llm=self.answering_llm, prompt=CONDENSE_QUESTION_PROMPT
            ),
            verbose=False,
        )`

`model_response = qa(
                {
                    "question": user_message,
                    "chat_history": formatted_chat_history,
                    "custom_personality": self.prompt_content,
                }
            )`

I would like that the model_response (the result from called the ConversationalRetrievalChain) returns the document ids in which the answer is based

### Motivation

My motivation is to be able to document which documents is the model basing its responses to further analyse and use this input for user experience improvement and transparency.

One possibility would be to use the _get_docs method under ConversationalRetrievalChain, but this would imply calling twice the model

### Your contribution

As of now the model_response returns:

`{'question': 'Who won the Olympics in 92?', 'chat_history': [()], 'custom_personality': 'xxxxxx
', 'answer': 'The US won the Olympics'}`

My proposal would be:

`{'question': 'Who won the Olympics in 92?', 'chat_history': [()], 'custom_personality': 'xxxxxx
', 'answer': 'The US won the Olympics', 'documents_source': [Document(), Document()...]}`

**Comment by fyasla** [comment]
Hello :wave: 
If i understand well what you need it already exists thanks to the **return_source_documents** parameter!

See [this example](https://python.langchain.com/docs/use_cases/question_answering/chat_vector_db#return-source-documents) and the [ConversationalRetrievalChain API documentation](https://api.python.langchain.com/en/latest/chains/langchain.chains.conversational_retrieval.base.ConversationalRetrievalChain.html)

Sorry if i misunderstood

**Comment by rangelrey** [comment]
I totally missed this, thanks for the answer!!
