### ISSUE TITLE
chatglm3-6b-32k----Please support chatglm3-6b-32k thank you very much

### ISSUE THREAD

**Issue by coderwpf** [langchain-ai/langchain#12514]
### Issue with current documentation:

Please support chatglm3-6b-32k thank you very much

**Comment by datalee** [comment]
chatglm3  model supports functionalities like function calls, **code interpretation**, and intelligent Agent capabilities.
i want to use **code interpretation** ability  with  create_pandas_dataframe_agent，to implement excel Q&A
