### ISSUE TITLE
Custom LLM Implementation

### ISSUE THREAD

**Issue by VpkPrasanna** [langchain-ai/langchain#12547]
### Feature request

Integrate other models from hugging face models models (likely decoder based models) as a LLM  , which we can use for RAG applications

### Motivation

Since the model weights of LLM are huge we can have our own model trained on small dataset they can be pluged into RAG applications 

### Your contribution

need to think of it actually how can i able to contribute to this

**Comment by VpkPrasanna** [comment]
@dosu-bot it will cannot be so specifc to BERT based models it can be any decoder models basically basically some text generation models or summarization models

**Comment by VpkPrasanna** [comment]
@dosu-bot can you re-write the function based on LLM as base class ?

**Comment by javaidiqbal11** [comment]
Hugging face have multiple models that can be integrate in the custom LLM, here is the supporting material:

[Building Custom Model](https://huggingface.co/docs/transformers/en/custom_models)
