### ISSUE TITLE
Fix hallucination problem with `SQLDatabaseChain`

### ISSUE THREAD

**Issue by ajndkr** [langchain-ai/langchain#1254]
## Description

Based on my experiments with `SQLDatabaseChain` class, I have noticed that the LLM tends to hallucinate `Answer` if `SQLResult` field results as `[]`. As I primarily used OpenAI as the LLM, I am not sure if this problem exists for other LLMs.

This is surely an undesirable outcome for users if the agent responds back with incorrect answers. With some prompt engineering, I think the following can be added to the default prompt to tackle this problem:

```
If the SQLResult is empty, the Answer should be "No results found". DO NOT hallucinate an answer if there is no result.
```

If there are better prompts to tackle this, that's great too!

**Comment by AjinkyaIndulkar** [comment]
I would like to contribute if this fix makes sense. @hwchase17

**Comment by agola11** [comment]
cc @fpingham who did a lot of work on SqlDatabaseChain... does this seem reasonable?

**Comment by fpingham** [comment]
I've faced this problem as well and I think this would be a good addition to the prompt. @ajndkr did you try it out? Did it solve the problem for you?

**Comment by ajndkr** [comment]
it worked for me but I have to tweak the agent prefix a bit as well.

**Comment by fpingham** [comment]
Do you mean to use the agent instead of the chain? I understand that these are independent.

**Comment by ajndkr** [comment]
sorry, I don't follow the question. Does it matter if I use an agent or chain? Wouldn't the fix be limited to the `SqlDatabaseChain` as a tool?

**Comment by fpingham** [comment]
AFAIK the agent does not use the chain but instead uses the `SQLDatabase` object directly

**Comment by ajndkr** [comment]
Ah! now I understand, you are talking about the SQL agent. I think I opened this issue before agent toolkits were introduced.

Maybe the SQL agent doesn't have a hallunication problem but if `SQLDatabaseChain` is separate from it, we could  update it with the suggested change.

**Comment by fpingham** [comment]
Yeah since you said 'the agent prefix' I thought you referred to the agent. I think the agent does not have this problem because it has some kind of instruction not to invent if the tables do not give it an answer. I would go through with this for the chain.

**Comment by ajndkr** [comment]
super.

**Comment by rubensmau** [comment]
Using SQLDatabaseChain, and Chinook.db . If i ask : "What is my name?" , I get as an answer:
SQLQuery: SELECT FirstName, LastName FROM Employee WHERE EmployeeId = 3
SQLResult: [('Jane', 'Peacock')]

**Comment by ajndkr** [comment]
> Using SQLDatabaseChain, and Chinook.db . If i ask : "What is my name?" , I get as an answer: SQLQuery: SELECT FirstName, LastName FROM Employee WHERE EmployeeId = 3 SQLResult: [('Jane', 'Peacock')]
> 
> Tried to add to the end of the prompt , some alerts, but without success.

what's the expected answer here? @rubensmau

**Comment by ajndkr** [comment]
Based on my suggestion, the answer will be "I don't know" only when `SQLResult: []`. As the above example is not an empty list, my prompt suggestion won't work.
