### ISSUE TITLE
while importing LlamaIndexRetriever, an error occurs that

### ISSUE THREAD

**Issue by tamura-go-tamura** [langchain-ai/langchain#12563]
### System Info

from langchain.retrievers.llama_index import LlamaIndexRetriever
------

```shell
llama-index==0.8.55
langchain==0.0.325
```

> in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    503     if len(args) != 1:
    504         raise ValueError("`run` supports only one positional argument.")
--> 505     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    506         _output_key
    507     ]
    509 if kwargs and not args:
    510     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    511         _output_key
    512     ]
in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, run_name, include_run_info)
    308 except BaseException as e:
    309     run_manager.on_chain_error(e)
--> 310     raise e
    311 run_manager.on_chain_end(outputs)
    312 final_outputs: Dict[str, Any] = self.prep_outputs(
    313     inputs, outputs, return_only_outputs
...
---> 32 response = index.query(query, response_mode="no_text", **self.query_kwargs)
     33 response = cast(Response, response)
     34 # parse source nodes
AttributeError: 'VectorStoreIndex' object has no attribute 'query'

Attribute "query" is a deprecated method. Therefore, it needs to be updated. 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from llama_index import VectorStoreIndex
from langchain.chains import RetrievalQA
from langchain.llms import OpenAI
from langchain.retrievers.llama_index import LlamaIndexRetriever
index = VectorStoreIndex.from_documents(**hoge)
retriever = LlamaIndexRetriever(index = index)
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff",retriever=LlamaIndexRetriever(index=index))
query = "What did the president say about Ketanji Brown Jackson"
qa.run(query)
```

### Expected behavior

Successfully read llama index retriever

**Comment by eolivelli** [comment]
I am seeing the same error.
I tried to tweak the code of LlamaIndexRetriever but without luck.
It seems that LlamaIndexRetriever is based on an old version of LlamaIndex

**Comment by tamura-go-tamura** [comment]
@eolivelli 
I think so too. You can it quickly by editing LlamaIndexRetriever like this.

[libs/langchain/langchain/retrievers/llama_index.py](https://github.com/langchain-ai/langchain/pull/12565/files#diff-18289a052ef0a888483e5e6dd1c81db7f482cde033b31a47773e73190aefcd70)

**Comment by eolivelli** [comment]
Thank you @tamura-go-tamura 

I hope that your PR will be committed soon
https://github.com/langchain-ai/langchain/pull/12565
