### ISSUE TITLE
After doing merge_from with Faiss, vector store appears as None. 

### ISSUE THREAD

**Issue by berkemkeskin-softtech** [langchain-ai/langchain#12570]
### Issue with current documentation:

I have a faiss vector store that I created before, when I print it it appears as <langchain.vectorstores.faiss.FAISS object at 0x0000022B3DFBBB50>. Then, I create a new faiss vector store and when I print it, it appears as <langchain.vectorstores.faiss.FAISS object at 0x0000022B7D0F4810>. I want to merge these two faiss objects, so I tried the merge_from method. However, when I try merge_from, vector store appears None. Here is my code:

    vector_store = FAISS.from_texts(text_chunks, embeddings,
                                        metadatas=[{"source": f"{created_pkl_name}:{i}"} for i in
                                                   range(len(text_chunks))])
    print("vector_store_new: ",vector_store) # <langchain.vectorstores.faiss.FAISS object at 0x0000022B7D0F4810>

    if os.path.exists(faiss_path_all):

        with open(faiss_path_all, 'rb') as faiss_file_all:
            all_data = pickle.load(faiss_file_all)
            print("all_data: ", all_data) # <langchain.vectorstores.faiss.FAISS object at 0x0000022B3DFBBB50>

        all_data = all_data.merge_from(vector_store)
        print(all_data) # None
How I can solve this problem? Is there another way for merge two faiss vector stores?

### Idea or request for content:

From the example (https://python.langchain.com/docs/integrations/vectorstores/faiss?highlight=FAISS#merging) I tried the same way, but still it doesn't work for me.

**Comment by berkemkeskin-softtech** [comment]
I wondered if it was going to another function with the same name, and it really was. I imported langchain and it worked lol.

**Comment by naveenfaclon** [comment]
if i have data coming from 3 datasources and i want to store all of them in one FAISS embeddings how to do that how to keep their embedding in one vectordb
