### ISSUE TITLE
Issue: Amazon Bedrock Cohere Command - Malformed input request: 2 schema violations found, please reformat your input and try again.

### ISSUE THREAD

**Issue by nishanth-k-10** [langchain-ai/langchain#12620]
### Issue you'd like to raise.

I've have been trying to work with AWS bedrock Cohere command LLM with Langchain and I'm referring [https://github.com/aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch/blob/main/ask-bedrock-with-rag.py](url) as source. 
**Below are few snippet of code that I'm working with,**

def create_bedrock_llm(bedrock_client):
    bedrock_llm = Bedrock(
        model_id="cohere.command-text-v14", 
        client=bedrock_client,
        verbose = True,
        model_kwargs={'temperature': 0}
        )
    return bedrock_llm

bedrock_client = bedrock_client = boto3.client(service_name="bedrock-runtime", region_name="us-east-1")
llm = create_bedrock_llm(bedrock_client)
template = """"Your are a expert financial reporter who analyzes performance of the company. The relevant information for answering the question is given below. Try to give detailed answer using the context available. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}

Answer:"""
prompt = PromptTemplate(template=template,
                            input_variables=['context', 'question'])

embedding = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
db = Chroma(persist_directory=DB_CHROMA_PATH, embedding_function=embedding)
retriever=db.as_retriever(search_kwargs={'k': 3})

qa = RetrievalQA.from_chain_type(llm=llm, 
                                     chain_type="stuff", 
                                     retriever=retriever,
                                     return_source_documents=True,
                                     chain_type_kwargs={"prompt": prompt, "verbose": True},
                                     verbose=True)
                                     

while True:
    query = input("\nEnter the query\n")
    if query.lower() == 'exit':
        break
    res = qa(query)
    print(res)
    
**Error**:
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: 2 schema violations found, please reformat your input and try again.

### Suggestion:

I have tried with API request using invoke_model() function with the same prompt schema which worked perfectly fine and response was recieved.

**Comment by nishanth-k-10** [comment]
Still didn't solve the issue though.
Below is the API request where I passed the same prompt and it worked.
{
  "modelId": "cohere.command-text-v14",
  "contentType": "application/json",
  "accept": "*/*",
  "body": {
    "prompt": prompt,
    "max_tokens": 100,
    "temperature": 0.8,
    "return_likelihood": "GENERATION"   
  } 
}

But I want to do it using with Langchain's bedrock

**Comment by nishanth-k-10** [comment]
I found the problem, the langchain library was outdated.

**Comment by kishoreiitd** [comment]
@nishanth-k-10 which version of langchain solved this issue? I am also facing the same issue while making an API call to Amazon Bedrock (claude v2 model).

**Comment by Abubakarjutt** [comment]
I am also getting this error when I use llama v1.

**Comment by Dinuda** [comment]
Using `anthropic.claude-v2` resolved my issue, was using `amazon.titan-text-express-v1`
