### ISSUE TITLE
Langchain Information Extraction

### ISSUE THREAD

**Issue by HasnainKhanNiazi** [langchain-ai/langchain#12636]
I am trying to use Langchain information extraction chain with OpenAI. Firstly, I am reading a PDF file having some text about products or product. There is no specefic format of PDF, it can be in any format like, there can be only one product on one page or one product can be on two pages or there can be 10 products on one page. So it's completely random. How can I extract the the useful information (some key attributes) for all the products. Currently, I am using Pydantic to validate the output schema and I am using `PyPDFLoader` to load the pdf and then using the `load_and_split`.

```
loader = PyPDFLoader(file_path=file_path)
pages = loader.load_and_split()
```

And then I am looping on the pages like this:

```
llm = ChatOpenAI(temperature=0, model=model_name, openai_api_key=key)
chain = create_extraction_chain(schema, llm)

for index in range(0, len(pages)):
         output = chain.run(pages[index])
         results.append(output)
```

How can I run the extraction in such a way that it should be completely automated, currently, it is just extracting information from one page and then other and then other.

**Comment by HasnainKhanNiazi** [comment]
@dosu-bot if I divide the text into multiple chunks like this;

```
from langchain.text_splitter import TokenTextSplitter

# Assume that 'text_from_pdf' is the text extracted from the PDF file
text_splitter = TokenTextSplitter(chunk_size=10, chunk_overlap=0)
texts = text_splitter.split_text(text_from_pdf)
```

then I need to call chain.run(texts[0]) or text[1] ....upto text[N] but in this case also, model is taking only chunk in the context but not complete PDF document text.

**Comment by JoffreyLemery** [comment]
@HasnainKhanNiazi 

Dis you finally succeed ? I'm facing the same situation !

**Comment by eyurtsev** [comment]
Closing as extraction use case has now been updated:

Please review: https://python.langchain.com/docs/use_cases/extraction
