### ISSUE TITLE
MRKL agent is passing "Observation" text to tools when using non-OpenAI LLMs and breaks structured input tools

### ISSUE THREAD

**Issue by thoraxe** [langchain-ai/langchain#12645]
### System Info

Python 3.9.16
Langchain 0.0.326
Linux (Fedora 37)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.utilities import SerpAPIWrapper
from langchain.agents import AgentType, initialize_agent
from langchain.tools import Tool

import langchain
langchain.debug = True

from langchain.llms import OpenAI
llm = OpenAI(temperature=0, verbose=True)

search = SerpAPIWrapper()

events_tool = Tool(
    name="events_tool_serp",
    description="A tool to look up current events",
    func=search.run,
)
tools = [events_tool]

agent = initialize_agent(
    tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True
)

agent.run("What happened yesterday?")
```

When the above code is run with OpenAI, things work OK. However, when swapped for a different LLM endpoint:

```python
# using IBM watsonx.ai
from model_context import get_watsonx_predictor
llm = get_watsonx_predictor(
    model="codellama/codellama-34b-instruct", min_new_tokens=5, verbose=True
)
```

Odd things happen:

```
[llm/start] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:LangChainInterface] Entering LLM run with input:
{
  "prompts": [
    "Answer the following questions as best you can. You have access to the following tools:\n\nevents_tool_serp: A tool to look up current events\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [events_tool_serp]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: What happened yesterday?\nThought:"
  ]
}
[llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:LangChainInterface] [2.65s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": " I should look up current events\nAction: events_tool_serp\nAction Input: yesterday\nObservation:",
        "generation_info": {
          "generated_token_count": 25,
          "input_token_count": 160,
          "stop_reason": "STOP_SEQUENCE",
          "stop_sequence": "\nObservation:",
          "input_text": "Answer the following questions as best you can. You have access to the following tools:\n\nevents_tool_serp: A tool to look up current events\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [events_tool_serp]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\nBegin!\n\nQuestion: What happened yesterday?\nThought:"
        },
        "type": "Generation"
      }
    ]
  ],
  "llm_output": {
    "token_usage": {
      "generated_token_count": 25,
      "input_token_count": 160
    }
  },
  "run": null
}
[chain/end] [1:chain:AgentExecutor > 2:chain:LLMChain] [2.65s] Exiting Chain run with output:
{
  "text": " I should look up current events\nAction: events_tool_serp\nAction Input: yesterday\nObservation:"
}
[tool/start] [1:chain:AgentExecutor > 4:tool:events_tool_serp] Entering Tool run with input:
"yesterday
Observation:"
```

The `Observation:` text is being passed into the tool. For simple tools like search engines, this often is not a problem. However, when your tool expects a structured input, you sometimes end up with tool input like the following:

```
"foo,bar
Observation:"
```

This results in the tool attempting to do something like splitting on `,` and then the second part of the resulting array is:

```
bar
Observation:
```

Which definitely breaks the tool.

### Expected behavior

The `Observation:` text should definitely not be passed as part of the tool input.

The MRKL output parser is here:
https://github.com/langchain-ai/langchain/blob/v0.0.327/libs/langchain/langchain/agents/mrkl/output_parser.py#L26-L77

The regex does appear to match the groups correctly:
https://regex101.com/r/v7Tg1n/1

It's unclear, though, why the `Observation:` text is ending up getting passed into the input.

Although, when you use newline characters (`\n`) in the string, and not actual newlines, it does appear that the `Observation` part is being caught in the group:
https://regex101.com/r/MMCvYn/1

I tried to spelunk into the code to figure out when the agent "base" calls `parse` to see why the `Observation` text would be getting passed into parse in the first place, but it seems that one possible fix here would be to modify the parse RegEx for MRKL to make sure it does NOT capture the observation component.

Changing the RegEx in the MRKL agent to the following:
```python
            r"Action\s*\d*\s*:[\s]*(.*?)[\s]*Action\s*\d*\s*Input\s*\d*\s*:[\s]*(.*)Observation:"
```

And then modifying the tool input strip:
```python
        if action_match:
            action = action_match.group(1).strip()
            action_input = action_match.group(2)
            tool_input = action_input.strip()
```

fixes the issue if "Observation" got passed in, but I am assuming that `parse` shouldn't have gotten this in the first place.

**Comment by thoraxe** [comment]
@dosu-bot Unfortunately, your first suggestion doesn't quite work.

The MRKL agent doesn't use `HUMAN_MESSAGE`:
https://github.com/langchain-ai/langchain/blob/v0.0.327/libs/langchain/langchain/agents/mrkl/prompt.pyz

`HUMAN_MESSAGE` is explicitly part of the chat agent:
https://github.com/langchain-ai/langchain/blob/v0.0.327/libs/langchain/langchain/agents/chat/prompt.py#L30

Changing the `HUMAN_MESSAGE` in the reproducer I posted in the OP did not change the behavior -- the `Observation` is still passed to the tool.

Your second suggestion doesn't make sense:
> The solution was to switch the regex used in the conversational agent to the regex used in the mrkl agent.
But I am using the MRKL agent and not the conversational agent. And the MRKL agent regex is what's broken.

**Comment by thoraxe** [comment]
@dosu-bot

I am not using OpenAI, so `promptlayer_openai.py` is not relevant. In fact, I'm doing the opposite - using non-OpenAI LLMs.

**Comment by imfht** [comment]
> @dosu-bot
> 
> I am not using OpenAI, so `promptlayer_openai.py` is not relevant. In fact, I'm doing the opposite - using non-OpenAI LLMs.

I run into same problem when using non openai model. do you found the solution now? 
any help for information would be thanks!

**Comment by deanchanter** [comment]
I came across this today as I beating my head against the wall for a similar issue trying to build a react agent.  @dosu-bot was close.  The problem was for me the templates assume that models will drop the stop sequence during the tool input generation. So what I did to make my life easier was I change the prompt template to have a different stop and adjust my llm according.  If you still want "observation" printed out in the scratchpad add it to the tool output like @dosu-bot shared from the old agents. 

```python
from typing import Optional

from dotenv import load_dotenv
from langchain.agents import AgentExecutor
from langchain.agents.format_scratchpad import format_log_to_str
from langchain.agents.output_parsers import JSONAgentOutputParser
from langchain.memory import ConversationBufferMemory
from langchain.tools.render import render_text_description_and_args
from langchain_core.callbacks import CallbackManagerForToolRun
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnablePassthrough
from langchain_core.tools import BaseTool

from genai import Client, Credentials
from genai.extensions.langchain import LangChainChatInterface
from genai.schema import TextGenerationParameters

load_dotenv()

from langchain.agents.react.output_parser import ReActOutputParser

from langchain_core.prompts import PromptTemplate


prompt_template = """Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.

Assistant is constantly learning and improving, and its capabilities are constantly evolving. It is able to process and understand large amounts of text, and can use this knowledge to provide accurate and informative responses to a wide range of questions. Additionally, Assistant is able to generate its own text based on the input it receives, allowing it to engage in discussions and provide explanations and descriptions on a wide range of topics.

Overall, Assistant is a powerful tool that can help with a wide range of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or just want to have a conversation about a particular topic, Assistant is here to assist.

TOOLS:
------

Assistant has access to the following tools:

{tools}

To use a tool, please use the following format:


Thought: Do I need to use a tool? Yes
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Run




When you have a response to say to the Human, or if you do not need to use a tool, you MUST use the format:


Thought: Do I need to use a tool? No
Final Answer: [your response here]


Begin!

Previous conversation history:
{chat_history}

New input: {input}
{agent_scratchpad}"""




prompt = PromptTemplate.from_template(prompt_template)
 
class WordLengthTool(BaseTool):
    name = "GetWordLength"
    description = "Returns the length of a word."

    def _run(self, word: str, run_manager: Optional[CallbackManagerForToolRun] = None) -> int:
        return len(word)


tools: list[BaseTool] = [WordLengthTool()]

client = Client(credentials=Credentials.from_env())
llm = LangChainChatInterface(
    client=client,
    model_id='meta-llama/llama-2-70b-chat',
    parameters=TextGenerationParameters(
        max_new_tokens=250, 
        #min_new_tokens=20, 
        #temperature=0, 
        #decoding_method="sample",
        temperature = 0,
        #top_p = .85,
        #top_k = 50,
        #repetition_penalty = 1.05,
        #max_new_tokens = 2048,
        stop_sequences=["\nRun"],
        include_stop_sequence = False
    ),
)
prompt = prompt.partial(
    # get tools with their descriptions and args in plain text
    tools=render_text_description_and_args(list(tools)),
    tool_names=", ".join([t.name for t in tools]),
)

memory = ConversationBufferMemory()

def get_mem(input):
    return memory.buffer_as_str


agent = (
    RunnablePassthrough.assign(
        # format the agent's scratchpad to a string
        agent_scratchpad=lambda x: format_log_to_str(x["intermediate_steps"]),
        # pass the memory as the chat history
        chat_history=get_mem,
    )
    | prompt
    | llm
    | ReActSingleInputOutputParser()
)
agent_executor = AgentExecutor(agent=agent, tools=tools, handle_parsing_errors=True, verbose=True, memory=memory)

```

**Comment by lotrdinesh** [comment]
Adding the below in case this is useful for someone else. I am not sure if this is relevant for the case in point (seemed like a similar issue).

I had a similar issue while using "langchain.agents.create_react_agent". Passing stop_sequence as "False"  worked for me. In case one needs to avoid hallucinations, we can use a different "stop_sequence" string (Default is "Observation:". This issue comes if the prompt contains "\nObservation:" string).

I am not sure why this issue does not come for OpenAI LLMs.

**Comment by Darshanbc** [comment]
I am using AWS bedrock with nova pro model I am facing the same issue however by passing stop_sequence as false is not helping
