### ISSUE TITLE
MultiLanguageModel: work with multiple LLM with the interface of a single one

### ISSUE THREAD

**Issue by fapont** [langchain-ai/langchain#12656]
### Feature request

The idea is to have an object that can be used in the same way as `LanguageModel` objects, but the object would contain a list of `LanguageModels` that could be chosen according to rules.

For instance I would to call my list of LLM with a round robin strategy in order to distribute requests among multiple LLM.

Example:
```
llm1 = OpenAI(key1)
llm2 = OpenAI(key2)

muti_llm = MultiLLM([llm1, llm2], method="round-robin")
multi_llm.predict(...) # will use llm1
multi_llm.predict(...) # the second time will use the llm2
```

### Motivation

The motivations behind these features are:
- leveraging multi account to avoid API limits per account
- act as a load balancer to easily create balancing strategies (round robin, random, least connection, ...)
- (in the future maybe) have the possibility to make shadowing between multiple LLM or other strategies 

### Your contribution

I started working on that but I'm not sure about the object hierarchy I need to implement to achieve this goal properly without impacting too much the existing codebase.

Here is my naive implementation:

```python
LanguageModelInput = TypeVar("LanguageModelOutput")

class BaseMultiLanguageModel(BaseLanguageModel[LanguageModelInput], ABC):
    language_models: List[BaseLanguageModel] = Field(
        description="List of language models",
        min_items=1
    )

    @property
    @abstractmethod
    def active_model(self) -> BaseLanguageModel:
        ...
    
    def generate_prompt(self, prompts: List[PromptValue], stop: Optional[List[str]] = None, callbacks: Callbacks = None, **kwargs: Any) -> LLMResult:
        return self.active_model.generate_prompt(prompts, stop, callbacks, **kwargs)
    
    async def agenerate_prompt(self, prompts: List[PromptValue], stop: Optional[List[str]] = None, callbacks: Callbacks = None, **kwargs: Any) -> LLMResult:
        return await self.active_model.agenerate_prompt(prompts, stop, callbacks, **kwargs)
    
    def predict(self, text: str, *, stop: Optional[Sequence[str]] = None, **kwargs: Any) -> str:
        return self.active_model.predict(text, stop=stop, **kwargs)
    
    def predict_messages(self, messages: List[BaseMessage], *, stop: Optional[Sequence[str]] = None, **kwargs: Any) -> BaseMessage:
        return self.active_model.predict_messages(messages, stop=stop, **kwargs)
    
    async def apredict(self, text: str, *, stop: Optional[Sequence[str]] = None, **kwargs: Any) -> str:
        return await self.active_model.apredict(text, stop=stop, **kwargs)
    
    async def apredict_messages(self, messages: List[BaseMessage], *, stop: Optional[Sequence[str]] = None, **kwargs: Any) -> BaseMessage:
        return await self.active_model.apredict_messages(messages, stop=stop, **kwargs)

    def invoke(self, input: Input, config: Optional[RunnableConfig] = None, **kwargs: Any) -> Output:
        return self.active_model.invoke(input, config, **kwargs)


# Example of subclasses creation

class RandomMultiChatModel(BaseMultiLanguageModel[PromptValue]):
    @property
    def active_model(self) -> BaseLanguageModel:
        choice = randint(0, len(self.language_models) - 1)
        print(f"Using LLM: {choice}")
        return self.language_models[choice]

class RoundRobinMultiChatModel(BaseMultiLanguageModel[PromptValue]):
    index: int = 0

    @property
    def active_model(self) -> BaseLanguageModel:
        self.index = (self.index + 1) % len(self.language_models)
        print(f"Using LLM: {self.index}")
        return self.language_models[self.index]

# Usage
llm1 = ChatOpenAI(openai_api_key=OPENAI_API_KEY_1)
llm2 = ChatOpenAI(openai_api_key=OPENAI_API_KEY_2)

round_robin_multi_llm = RoundRobinMultiChatModel(language_models=[llm1, llm2])
round_robin_multi_llm.predict("Hello, how are you?") # use the same methods as BaseLanguageModel
```

This is working with simple examples but I'm not sure this inheritance hierarchy is the best so any help would be appreciated to define the best solution :)

**Comment by fapont** [comment]
@dosu-bot Thanks for these ideas ! Do you think you could ask maintainers for their inputs on this ? 😊

**Comment by fapont** [comment]
> Just to add a use case because I see your proposal as a must: if the context is large, we should pickup a large context model (ie gpt-3.5-turbo-16k); if we should retry because the model did not understand it, we could repeat with a more expensive one: GPT4 vs GPT 3.5
> If we reach a rate limit, we could try with an equivalent one (i.e. gpt-3.5-turbo-0613).
> In means it is not only the same model using different credentials, but also different models hosted in different places (self-hosted, huggingface, ...) Besides, I imagine several approaches to select a model/strategy within the list: robin, always start with 1st one in the list, start with the latest one that worked, random...
> The proposed architecture above seems to make it feasible but I wanted to be sure we don't miss anything.

Thanks for your message ! Indeed this can lead to many model selection strategies so we need to think about having the more flexibility without introducing a new messy class ahah

Can't wait to hear from other people interested in this feature 😊

**Comment by hinthornw** [comment]
This is probably easier to manage via expression language than to create a new class at this point in time. For instance, to route based on incoming message length, you could do something like this:

```
import tiktoken
from langchain.chat_models import ChatAnthropic, ChatOpenAI
from langchain.prompts.chat import ChatPromptTemplate, ChatPromptValue
from langchain.schema.output_parser import StrOutputParser
from langchain.schema.runnable import RunnableLambda

short_context = ChatOpenAI(model="gpt-3.5-turbo")
medium_context = ChatOpenAI(model="gpt-3.5-turbo-16k")
long_context = ChatAnthropic(model="claude-2")

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful AI."),
        ("user", "{input}"),
    ]
)


def select_model(prompt: ChatPromptValue):
    num_tokens = short_context.get_num_tokens_from_messages(prompt.messages)
    if num_tokens > 15_000:
        return long_context
    elif num_tokens > 4000:
        return medium_context
    return short_context


chain = prompt | select_model | StrOutputParser()
```

**Comment by fapont** [comment]
@hinthornw you're right it is possible to create rules using runnables chaining but I think more complex use cases with a retry mechanism could be complex to implement (e.g. retry with another model based on an exception raised, @shuther ). 

IMO, all the complexity could be embedded in the class, so it could be used in any other string as if you were using a classic BaseLanguageModel instead of adding new steps each time.

**Comment by ishaan-jaff** [comment]
Hi @fapont, @shuther @hinthornw i'm the maintainer of LiteLLM we allow you to do this today through:
- the `litellm package` 
- `ChatLiteLLM` our langchain integration 
Please let me know if this does not solve your problem 

Here's how to use it
## Router - load balancing([Docs](https://docs.litellm.ai/docs/routing))
LiteLLM allows you to load balance between multiple deployments (Azure, OpenAI). It picks the deployment which is below rate-limit and has the least amount of tokens used.

```python
from litellm import Router

model_list = [{ # list of model deployments 
    "model_name": "gpt-3.5-turbo", # model alias 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-v-2", # actual model name
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-functioncalling", 
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "gpt-3.5-turbo", 
        "api_key": os.getenv("OPENAI_API_KEY"),
    }
}]

router = Router(model_list=model_list)

# openai.ChatCompletion.create replacement
response = await router.completion(model="gpt-3.5-turbo", 
                messages=[{"role": "user", "content": "Hey, how's it going?"}])

print(response)
```
