### ISSUE TITLE
arXiv API Wrapper

### ISSUE THREAD

**Issue by kennethleungty** [langchain-ai/langchain#1269]
Hey @hwchase17 , the arXiv API is a pretty useful one for retrieving specific arXiv information, including title, authors, topics, and text abstracts. Am thinking of working to include it within langchain, to add to the collection of API wrappers available.

How does that sound?

**Comment by stepp1** [comment]
Hi! I went ahead an wrote an integration. Any feedback on the PR would be great.

**Comment by kennethleungty** [comment]
Nice work @stepp1 , will wait to this pull request to go through before I append my enhancements on your foundations
