### ISSUE TITLE
ChatTongyi class  use  _generate method as async call and result in replying text dispeared

### ISSUE THREAD

**Issue by joeylin** [langchain-ai/langchain#12695]
### System Info

langchain 0.0.327

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

it is easy to reproduction
use AsyncIteratorCallbackHandler() to get ChatTongyi stream data, 
it only get warning: 
`/venv/lib/python3.10/site-packages/langchain/chat_models/tongyi.py:365: RuntimeWarning: coroutine 'AsyncCallbackManagerForLLMRun.on_llm_new_token' was never awaited
  run_manager.on_llm_new_token(chunk.content, chunk=chunk)`
and the reply text dispeared

I look into the code , and find the problem is in the _agenerate() with only using _generate()
![image](https://github.com/langchain-ai/langchain/assets/2030833/ee37d1c0-3824-4932-91f0-3e0c1aafe61f)

we can see, the stream functionality in _generate() is incomplete and problematic. One of them is the questionable support for asynchronous callback, 
![image](https://github.com/langchain-ai/langchain/assets/2030833/84a3e1a9-f936-4002-aea3-889afbd618f8)
and this is where error happens
![image](https://github.com/langchain-ai/langchain/assets/2030833/070b61ad-d6ad-4aaf-ac3f-1f6f116942db)
it should use _astream()

pls, fix it , thx

### Expected behavior

return stream data

**Comment by joeylin** [comment]
no, it should add  await on run_manager.on_llm_new_token
`if run_manager:
            run_manager.on_llm_new_token(chunk.content, chunk=chunk)
`

**Comment by joeylin** [comment]
could anybody deal with the issue ?

**Comment by joeylin** [comment]
yes, I think so

**Comment by joeylin** [comment]
oh my god. no one care about it .

**Comment by LyonLen** [comment]
I tried a quick way to fix it.(May not a good solution)
`import asyncio
from typing import List, Optional, Any, Iterator

from langchain.callbacks.manager import AsyncCallbackManagerForLLMRun
from langchain.chat_models.tongyi import ChatTongyi, _convert_delta_to_message_chunk
from langchain.schema import BaseMessage
from langchain.schema.messages import AIMessageChunk
from langchain.schema.output import ChatGenerationChunk


class SelfChatTongyi(ChatTongyi):

    def _stream(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> Iterator[ChatGenerationChunk]:
        message_dicts, params = self._create_message_dicts(messages, stop)
        params = {**params, **kwargs, "stream": True}
        # Mark current chunk total length
        length = 0
        default_chunk_class = AIMessageChunk
        for chunk in self.stream_completion_with_retry(
            messages=message_dicts, run_manager=run_manager, **params
        ):
            if len(chunk["output"]["choices"]) == 0:
                continue
            choice = chunk["output"]["choices"][0]

            chunk = _convert_delta_to_message_chunk(
                choice["message"], default_chunk_class, length
            )
            finish_reason = choice.get("finish_reason")
            generation_info = (
                dict(finish_reason=finish_reason) if finish_reason is not None else None
            )
            default_chunk_class = chunk.__class__
            chunk = ChatGenerationChunk(message=chunk, generation_info=generation_info)
            yield chunk
            if run_manager:
                asyncio.run(run_manager.on_llm_new_token(chunk.text, chunk=chunk))
            length = len(choice["message"]["content"])`
