### ISSUE TITLE
Issue: How can I utilize different histories for different users

### ISSUE THREAD

**Issue by Anaudia** [langchain-ai/langchain#12706]
### Issue you'd like to raise.

I am using the ConversationBufferWindowMemory class and I would like to have different memories for different users. So that each user has its individual memory. 

memory = ConversationBufferWindowMemory(k=3, memory_key="chat_history", return_messages=True)

qa = ConversationalRetrievalChain.from_llm(llm_model, vector_store.as_retriever(search_kwargs={'k': 2}), memory=memory,

**Comment by 19950606** [comment]
@Anaudia  your code is helpful.. I would also need to know on how can then link this to api like FastAPI etc in such a way that if i ask anything it then pulls the history in db and add to conversation buffer  so that it reply the question and then after it saves the new question and answer in db

**Comment by Anaudia** [comment]
I have saved each QA object for every user in a dict, using the session_id as the key. You can get the session_id from FastAPI.

**Comment by 19950606** [comment]
I have tried to creat modules as attached


On fast api end point i want to put user_id  and question, then in db each
pair of question,response , user_id must be saved in db. then succeeding
responses and questionsmust have conversation buffer memory catered for.
But its not working

**Comment by shreyansh-gp** [comment]
> @Anaudia your code is helpful.. I would also need to know on how can then link this to api like FastAPI etc in such a way that if i ask anything it then pulls the history in db and add to conversation buffer so that it reply the question and then after it saves the new question and answer in db

same question
