### ISSUE TITLE
Issue: When using FAISS vector store, how can I get the size of vector store

### ISSUE THREAD

**Issue by TheJerryChang** [langchain-ai/langchain#12767]
### Issue you'd like to raise.

When using FAISS vector store, how can I get the size of vector store?
For example, I used FAISS.load_local(path, embeddings) to load a vector store, how to get the size of the loaded vector store? Which should be the total number of documents in it.

**Comment by TheJerryChang** [comment]
That is great! Thanks for the answer. 

I have another question, how do I increase the randomness when using the similarity_search? For now, if I set k = 5 and fetch_k = 50, the same query I run everytime gives me the same result, because the similarity_search is extracting 5 documents from a fixed 50 documents every time. How to make the similarity_search to search from other documents as well?

**Comment by EjazHabibDar14** [comment]
I am using this code to load my FAISS Vector store from my directory faiss index which has two files index.faiss and index.pkl.

vector_store = FAISS.load_local("faiss index", embedder, allow_dangerous_deserialization=True)

Now this has created an object of the faiss vector for me which contains chunk_id, document, page and content.
Now what I want is to store my faiss vector store embeddings and above columns in a database like SQlite3.
Can you please guide me how can I go about it.
