### ISSUE TITLE
Issue: getting not implemented error when using async chromium loader

### ISSUE THREAD

**Issue by HRUSHI1212** [langchain-ai/langchain#12763]
### Issue you'd like to raise.

I tried to use webscraping by using langchain and used the async chromium loader as per the lanchain documentation but I was getting error asyncio.run() error so I made some chnages that i found on web but its still not working .
below is the code:
import asyncio
import playwright
from langchain.document_loaders import AsyncChromiumLoader
from langchain.document_transformers import BeautifulSoupTransformer
import nest_asyncio
nest_asyncio.apply()

async def main():
    # Create an instance of AsyncChromiumLoader with a list of URLs
    urls = ["https://www.hdfcbank.com/personal/borrow/popular-loans/personal-loan/eligibility"]  # Replace with your desired URLs
    loader = AsyncChromiumLoader(urls)

    # Load the URLs
    html = await loader.load()

    # Print the HTML content
    for url, content in html.items():
        print(f"URL: {url}\nHTML Content: {content}\n")

if __name__ == "__main__":
    asyncio.run(main())

**Comment by HRUSHI1212** [comment]
this is also not working

**Comment by anudeepadi** [comment]
@HRUSHI1212 Did you try executing with the commands `pip install playwright` and then `playwright install` because it worked for me with these.

**Comment by jerry1900** [comment]
i met the same question with "RuntimeError: asyncio.run() cannot be called from a running event loop" using jupyter as posted below:
![image](https://github.com/langchain-ai/langchain/assets/5378029/bc588c69-3faf-432f-99ed-658bf6ea3162)
![1706169408086](https://github.com/langchain-ai/langchain/assets/5378029/d9972d7d-557c-4604-ab73-dbd264617860)

what's interesting is that, i change another development environment Pycharm to load the same code ,it worked as below:
![1706169523341](https://github.com/langchain-ai/langchain/assets/5378029/44401eb1-6bbc-44f0-977e-36da6670a390)
 
I highly suspected that Jupyter which is working on browser kernel ,would have problems using asyn method of another browser(Chromium),it has some conflicts.  So when you meet this problem, you may change another development environment to have another shot.

**Comment by IAmStoxe** [comment]
To run asyncio in jupyter, add this bad boy to the top:

https://gist.github.com/IAmStoxe/fe3ec1f4420163cb80a974b95e7962cb

```python
# This import is required only for jupyter notebooks, since they have their own eventloop
import nest_asyncio

nest_asyncio.apply()
```

**Comment by karan842** [comment]
@jerry1900 thanks for sharing this tip of environment :)  

I was using Jupyter Notebook inside VSCode and still got NotImplementedError. 

Then I move to .py script and run exact code. 

It worked for me.

**Comment by IAmStoxe** [comment]
That's precisely how I do it. Maybe restart the kernel.
