### ISSUE TITLE
Issue: Schema error when ingesting documents

### ISSUE THREAD

**Issue by nextaiarnav** [langchain-ai/langchain#12772]
### Issue you'd like to raise.

The error
{'error': [{'message': "'id' is a reserved property name, no such prop with name 'id' found in class 'LangChain_14ee2519c3154dcb9ea3f47a8967d0e8' in the schema. Check your schema files for which properties in this class are available"}]}

loader = ConfluenceLoader(
url="URL", username="USERNAME", api_key="API_KEY")
documents = loader.load(space_key="SPACE_KEY", include_attachments=True, limit=150)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(documents)
db = Weaviate.from_documents(documents, embeddings, client=client, by_text=False)
chatbot = RetrievalQA.from_chain_type(
llm=llm,
chain_type="stuff",
retriever=db.as_retriever(search_type="similarity",search_kwargs={"k": 1}),
)
prompt = PromptTemplate(template=template, input_variables=["query"])
import sys
while True:
message=input("prompt: ")
if message=='exit':
print('Exiting')
sys.exit()
if message=='':
continue
response = chatbot.run(prompt.format(query=message))

**Comment by tsmith023** [comment]
Just to add onto this, I did some digging for you @nextaiarnav 😁

LangChain's `ConfluenceLoader` makes a metadata field `id` here: https://github.com/langchain-ai/langchain/blob/0da75b9ebd1e5a485a295d6f519f2d7be1f89f0a/libs/langchain/langchain/document_loaders/confluence.py#L512

But `id` is a reserved property name in Weaviate as detailed [here](https://github.com/weaviate/weaviate/blob/master/entities/schema/validation.go#L37) so LangChain will need to add some extra logic here: https://github.com/langchain-ai/langchain/blob/0da75b9ebd1e5a485a295d6f519f2d7be1f89f0a/libs/langchain/langchain/vectorstores/weaviate.py#L150
to deal with this fact (perhaps renaming `id` to `page_id`?)
