### ISSUE TITLE
Add support for Cohere embed V3

### ISSUE THREAD

**Issue by ojpetar** [langchain-ai/langchain#12793]
### Feature request

The new cohere V3 embed endpoints have a new required parameter - input_type.
Langchain currently doesn't support this parameter

https://txt.cohere.com/introducing-embed-v3/

### Motivation

Being able to use the newest multilingual embedding capabilities is something users who are developing an international product would find very important

### Your contribution

Documentation!

**Comment by kacperlukawski** [comment]
I can take that task over. I've already contributed to Cohere embeddings.

**Comment by ojpetar** [comment]
@kacperlukawski that would be awesome - I can take a stab at the nodeJS implementation. much more familiar with that one

**Comment by jnance314** [comment]
@kacperlukawski thanks for putting in the work! Can you update us here once it's ready?

**Comment by kacperlukawski** [comment]
@jnance314 Added a new PR with that change: #12940

**Comment by eyurtsev** [comment]
Merged with https://github.com/langchain-ai/langchain/pull/12940

**Comment by mehradans92** [comment]
Hi. Quick question on the `input_type` parameter. Looks like cohere API considers `search_document` for the actual doc and `search_query` for the query.  How would you pass this to langchian here. Should `search_document` be used for `embed_documents` func and `aembed_documents` be used for?

**Comment by antoniolanza1996** [comment]
@mehradans92 `embed_documents` uses `input_type="_search_document"`. Instead, `embed_query` uses `input_type="search_query`. You can see this in PR #12940 code changes

**Comment by mehradans92** [comment]
Great! Thanks @antoniolanza1996
