### ISSUE TITLE
PLEASE make all subsequent versions of Langchain backwards compatible!!!

### ISSUE THREAD

**Issue by tyler-suard-parker** [langchain-ai/langchain#12803]
### Feature request

Example of what NOT to do:
https://github.com/langchain-ai/langchain/issues/12507

Langchain, PLEASE stop doing this. PLEASE make all your updates backwards compatible. As it is, if you keep making changes like moving modules around, existing scripts break with every new update of Langchain.

### Motivation

It is so frustrating to have to try and guess which version of Langchain will actually work with my code.

### Your contribution

Just stop moving modules around.  You cause way more harm than good when you do that, because tutorials for Langchain have to be rewritten and new versions of Langchain are not compatible with Langchain code written just a few months ago.

**Comment by hwchase17** [comment]
Responded in original issue, but this was not intentional and we'll add better testing to ensure things like this dont happen.

Thanks for flagging, and if it does happen again please let us know.
