### ISSUE TITLE
Langchain ConfluenceLoader.load(): Get "when" field in metadata

### ISSUE THREAD

**Issue by Vickywwww** [langchain-ai/langchain#12812]
### System Info

langchain: 0.0.311

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

We're trying to load confluence pages using `ConfluenceLoader.load()`.
If we load pages by list of page_ids:
```
loader = ConfluenceLoader(
     url=baseUrl,
     username=username, 
     api_key= api_key
)

documents = loader.load(
    page_ids = ["2081227164", "2096890841", "2081227310"], 
    include_attachments=False, 
    limit=50,
    max_pages=1000
 )
```
We are able to get `when` field in metadata.
However, if we reuqest pages by space
```
documents = loader.load(
    space_key = spaceName,
    include_attachments=False, 
    limit=50,
    max_pages=1000
 )
```
The when field will not be in metadata.

### Expected behavior

Is there any methods we can request pages by space and also get `when` field? This is really important for us.
Thanks :)

**Comment by SufiSR** [comment]
I ran into the same issue. 

The version information comes back empty from your module for whatever reason.
Directly accessing it through the atlassian-python-api module is possible though:

confluence.get_page_by_id(page.metadata['id'], expand="version") works like a charm.
