### ISSUE TITLE
Extraction of contents from docx files through UnstructuredWordDocumentLoader

### ISSUE THREAD

**Issue by Kirankumar2609** [langchain-ai/langchain#12825]
### System Info

langchain=0.0.208
platform=Windows
python=3.9.16

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import UnstructuredWordDocumentLoader

loader = UnstructuredWordDocumentLoader(docx_file_path, mode="elements")
data = loader.load()
data

### Expected behavior

Page numbers of the contents extracted using UnstructuredWordDocumentLoader(docx_file_path, mode="elements") are not in sync with the actual page number of the contents which are there in the docx file.

**Comment by Kirankumar2609** [comment]
@hwchase17 / @eyurtsev Can you help on this?

**Comment by umair313** [comment]
@Kirankumar2609 can you elaborate on the issue? As I understand you are saying that the page number and number of documents are not in sync for example if you have 5 pages in the docx file you should have 5 documents. 

Note: when you use `mode='elements'` then 

> the unstructured library will split the document into elements such as Title and NarrativeText. You can pass in additional unstructured kwargs after mode to apply different unstructured settings.

**Comment by Kirankumar2609** [comment]
@umair313 yes. The page number of the final document extracted does not match with the actual page number of the docx file. Eg: if there are 24 pages in the docx file, the page number of the last extracted document(present in 24th page of docx file) comes up as either 18 or 19 even though the document content match with the actual content present in the 24th page of docx file.

**Comment by umair313** [comment]
can you provide an example?

**Comment by umair313** [comment]
> @umair313 yes. The page number of the final Document extracted does not match with the actual page number of the docx file. Eg: if there are 24 pages in the docx file, the page number of the last extracted Document(present in 24th page of docx file) comes up as either 18 or 19, even though the Document content matches with the actual content present in the 24th page of the docx file.

can you provide an example?

**Comment by Kirankumar2609** [comment]
@umair313 

actual content:
![image](https://github.com/langchain-ai/langchain/assets/85477926/b21baafd-92f4-45bf-a4f1-c3bf7cceb761)


langchain result:
![image](https://github.com/langchain-ai/langchain/assets/85477926/9b5537d1-b671-4664-992c-b27f139c3598)

**Comment by Kirankumar2609** [comment]
> try upgrading to latest langchain version `0.0.335`

latest langchain is also having the same issue

**Comment by Kirankumar2609** [comment]
> I am on linux with python3.11.4 and getting `AttributeError: 'Document' object has no attribute 'page_number'` with langchain==0.0.208 and langchain==0.0.335.
> 
> I think its been removed so try to upgrade both python and langchain.

I don't want it to be removed. I need the page numbers. But the correct one!

**Comment by umair313** [comment]
@Kirankumar2609 what are your `unstructured` and `python-docx` versions?

**Comment by Kirankumar2609** [comment]
> @Kirankumar2609 what are your `unstructured` and `python-docx` versions?

unstructured=0.8.1
python-docx=0.8.11

**Comment by Kirankumar2609** [comment]
> > > @Kirankumar2609 what are your `unstructured` and `python-docx` versions?
> > 
> > 
> > The issue persists even if I upgrade these libraries to the latest version.
> 
> ok what file type you are using?

.docx files
