### ISSUE TITLE
RecursiveCharacterTextSplitter with regex separator raises error if there is only 1 match of the regex

### ISSUE THREAD

**Issue by zegmonteiro** [langchain-ai/langchain#12832]
### System Info

- Langchain=0.0.325
- Python=3.10.0
- Windows

### Who can help?

@IlyaMichlin @hwchase17 @baskaryan

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Running this example:

`from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.schema.document import Document

splitter = RecursiveCharacterTextSplitter(
    chunk_size=100, 
    chunk_overlap=20,
    length_function = len,
    is_separator_regex = True,
    separators=["\n(?=\d.\d{1,2}(\.*)\n)", "\.(?=\n\w)", "\n", "\.", " "]
)

documents = [Document(page_content="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. \n1.1\nNeque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?")]

splitted_documents = splitter.split_documents(documents)

print(splitted_documents)
`

Raises 'list index out of range' error on the line "splits = [_splits[i] + _splits[i + 1] for i in range(1, len(_splits), 2)]" of the text_splitter.py file

`def _split_text_with_regex(
    text: str, separator: str, keep_separator: bool
) -> List[str]:
    # Now that we have the separator, split the text
    if separator:
        if keep_separator:
            # The parentheses in the pattern keep the delimiters in the result.
            _splits = re.split(f"({separator})", text)
            splits = [_splits[i] + _splits[i + 1] for i in range(1, len(_splits), 2)]
            if len(_splits) % 2 == 0:
                splits += _splits[-1:]
            splits = [_splits[0]] + splits
        else:
            splits = re.split(separator, text)
    else:
        splits = list(text)
    return [s for s in splits if s != ""]`

### Expected behavior

The expected behavior was not to raise the error, but continue with the recursive split by the next patterns.

**Comment by zegmonteiro** [comment]
I figured out that with keep_separator=False I can change how I construct the regex not to capture what I want to maintain and then the error does not occur. Anyway, keeping the issue open because still think that the code without keep_separator=False should not raise an error.

**Comment by 16dprice** [comment]
I'm also getting this same issue today. This issue should definitely not have been closed.

Here is the current `_split_text_with_regex` function:
```python
def _split_text_with_regex(
    text: str, separator: str, *, keep_separator: Union[bool, Literal["start", "end"]]
) -> list[str]:
    # Now that we have the separator, split the text
    if separator:
        if keep_separator:
            # The parentheses in the pattern keep the delimiters in the result.
            _splits = re.split(f"({separator})", text)
            splits = (
                ([_splits[i] + _splits[i + 1] for i in range(0, len(_splits) - 1, 2)])
                if keep_separator == "end"
                else ([_splits[i] + _splits[i + 1] for i in range(1, len(_splits), 2)])
            )
            if len(_splits) % 2 == 0:
                splits += _splits[-1:]
            splits = (
                ([*splits, _splits[-1]])
                if keep_separator == "end"
                else ([_splits[0], *splits])
            )
        else:
            splits = re.split(separator, text)
    else:
        splits = list(text)
    return [s for s in splits if s != ""]
```

If you call it with these inputs, it fails
```python
keep_separator = True
separator = r"<\|TEXTID:(\d+)\|>"
text = "<|TEXTID:0|>c<|TEXTID:0|><|TEXTID:1|>"

_split_text_with_regex(text=text, separator=separator, keep_separator=keep_separator)
```

**Comment by 16dprice** [comment]
Here's a better example actually. With the same function, the following code fails:

```python
text = "acaa"
separator = "(a)"
keep_separator = True

_split_text_with_regex(text=text, separator=separator, keep_separator=keep_separator)
```
but this code succeeds
```python
text = "acaa"
separator = "a"
keep_separator = True

_split_text_with_regex(text=text, separator=separator, keep_separator=keep_separator)
```

So the issue is when there's groups in the separator. In fact, it seems that it has to do with the _parity_ of groups in the regex (e.g. if there's an even or odd number of them). So, if we use the `text = abcabab`, then the following regexes cause this function to succeed or fail:
```python
"(a)" # FAIL
"(a)(b)(c)" # FAIL

"(a)(b)" # PASS
"(a)b(c)" # PASS
```
