### ISSUE TITLE
OpenAIEmbeddings Sending TikToken Tokens Rather than Texts

### ISSUE THREAD

**Issue by pedrojrv** [langchain-ai/langchain#12854]
### System Info

langchain==0.0.263

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.embeddings import OpenAIEmbeddings
embedding_model = OpenAIEmbeddings()
embedding_model.embed_query("Hello")
```

### Expected behavior

Send "Hello" to OpenAI, it now sends the tiktoken tokens.

**Comment by pedrojrv** [comment]
The issue I believe comes from this PR #8604

**Comment by codingdudecom** [comment]
I'm running into the same issue. I don't understand how the solution proposed is to modify the code. 

Is there an actual solution for this?

**Comment by summer-2014** [comment]
Same issue here

**Comment by OrkhanAlikhanov** [comment]
Same issue, I wish there was an option to turn tokenization off

**Comment by ccurme** [comment]
You can disable the tokenization by passing `check_embedding_ctx_length=False`:
```python
OpenAIEmbeddings(check_embedding_ctx_length=False)
```
Agreed that this is not obvious at the moment.

**Comment by Fatih-U** [comment]
I was facing this issue and last two configuration lines resolved my case (self hosted vllm served embedding models) : 

```
OpenAIEmbeddings(
    model=Config.OPENAI_EMBEDDING_MODEL_ID,
    openai_api_base=Config.OPENAI_EMBEDDING_API_BASE,
    openai_api_key=Config.OPENAI_API_KEY,
    check_embedding_ctx_length=False,  # Skip token length checking
    tiktoken_enabled=False  # Disable tiktoken completely
```
)
