### ISSUE TITLE
'super' object has no attribute 'parse_obj'

### ISSUE THREAD

**Issue by shubhank-saxena** [langchain-ai/langchain#12866]
### System Info

Langchain version - 0.0.330
Python version - 3.10

### Who can help?

@hwchase17 
@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hello! I am using NLAToolkit to load the OpenAPI spec and here is the code sample

```python
  llm = ChatOpenAI(
      model_name="gpt-4",
      temperature=0,
      openai_api_key=bot_config["OPENAI_API_KEY"],
  )

  memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

  analytics_toolkit = NLAToolkit.from_llm_and_spec(
      llm, OpenAPISpec.from_spec_dict(api_spec)
  )
  ```
  I have ensured that api_spec is a dict.
  
  Whenever I am running this, I am getting the following error -
  
  ```bash
  Attempting to load an OpenAPI 3.0.3 spec.  This may result in degraded performance. Convert your OpenAPI spec to 3.1.* spec for better support.
Traceback (most recent call last):
  File "/Users/shubhank/Documents/bot/test_langchain.py", line 3, in <module>
    output_answer = ask_question_from_llm(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhank/Documents/bot/langchain_code.py", line 61, in ask_question_from_llm
    llm, OpenAPISpec.from_spec_dict(api_spec)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhank/.local/share/virtualenvs/bot-vTuYgIC7/lib/python3.11/site-packages/langchain/utilities/openapi.py", line 218, in from_spec_dict
    return cls.parse_obj(spec_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shubhank/.local/share/virtualenvs/bot-vTuYgIC7/lib/python3.11/site-packages/langchain/utilities/openapi.py", line 202, in parse_obj
    return super().parse_obj(obj)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'super' object has no attribute 'parse_obj'
```

### Expected behavior

It should load the API spec and then answer the question accordingly. This was working previously as I have had tested it before!

**Comment by racheldengg** [comment]
Can anyone confirm if https://github.com/mike-oakley/openapi-pydantic is the github repository that is importing the OpenAPI superclass? As seen in utilities/openapi.py
`
try:
    from openapi_pydantic import OpenAPI
except ImportError:
    OpenAPI = object  # type: ignore
    `

I think the parse_obj function does exist in OpenAPI, as shown in the openapi-pydantic README.md:
<img width="718" alt="image" src="https://github.com/langchain-ai/langchain/assets/92647291/5b32ac3c-c8f4-48b9-b080-46b7e11da845">

I'm thinking this might be an import error? Or an issue with how the dependency is being configured. Any thoughts/replies are all greatly appreciated!

**Comment by vmwarealthomas** [comment]
For any folks running into this issue see the thread from [here](https://github.com/langchain-ai/langchain/issues/12866#issuecomment-1798365940). You need to run pip install `openapi-pydantic`

**Comment by rsk2327** [comment]
> I'm thinking this might be an import error? Or an issue with how the dependency is being configured. Any thoughts/replies are all greatly appreciated!

Definitely an import error. Not sure why the openapi_pydantic package is not added as a hard dependency since the rest of the functions is dependent on it.
