### ISSUE TITLE
ChromaDB validation error for Document metadata.

### ISSUE THREAD

**Issue by muitobanco** [langchain-ai/langchain#1287]
Hi there, loving the library.

I'm running into an issue when trying to run the chromadb example using Python.

It fine upto the following:

`docs = docsearch.similarity_search(query)`

Receiving the following error:

`File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document
metadata
  none is not an allowed value (type=type_error.none.not_allowed)`
  
I did some debugging and found that the metadatas from the `results` in chromadb in this code bit:

```
docs = [
            # TODO: Chroma can do batch querying,
            # we shouldn't hard code to the 1st result
            Document(page_content=result[0], metadata=result[1])
            for result in zip(results["documents"][0], results["metadatas"][0])
        ]
```

Are all "None" shown as follows:

`.. this.']], 'metadatas': [[None, None, None, None]], 'distances': [[0.3913411498069763, 0.43421220779418945, 0.4523361325263977, 0.45244452357292175]]}`

Running langchain-0.0.94 and have all libraries up to date.

Complete code:

```
with open('state_of_the_union.txt') as f:
    state_of_the_union = f.read()

text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_text(state_of_the_union)
embeddings = OpenAIEmbeddings()
docsearch = Chroma.from_texts(texts, embeddings)

print('making query')

query = "What did the president say about Ketanji Brown Jackson"
docs = docsearch.similarity_search(query)

print(docs[0].page_content)
```

Any help would be appreciated 👍

**Comment by schiehll** [comment]
I ran into the same issue! I think the problem is that `similarity_search` only works for documents and not for texts. If you do it with `text_splitter.split_documents` and then `Chroma.from_documents` it works. I had to create documents from my texts to make it work.

**Comment by jeffchuber** [comment]
Hi @muitobanco and @schiehll - I believe this PR fixes the issue - https://github.com/hwchase17/langchain/pull/1714
