### ISSUE TITLE
It seems that stop does not work with ollama models.

### ISSUE THREAD

**Issue by glad4enkonm** [langchain-ai/langchain#12892]
### System Info

 pip freeze
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==23.3.1
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
dbus-python==1.2.16
diskcache==5.6.3
distro==1.4.0
distro-info==0.23+ubuntu1.1
entrypoints==0.3
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
llama-cpp-python==0.2.11
MarkupSafe==1.1.0
more-itertools==4.2.0
netifaces==0.10.4
numpy==1.24.4
oauthlib==3.1.0
pexpect==4.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.1+ubuntu0.20.4.1
python-debian==0.1.36+ubuntu1.1
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
sos==4.5.6
ssh-import-id==5.10
systemd-python==234
Twisted==18.9.0
typing-extensions==4.8.0
ubuntu-advantage-tools==8001
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
zipp==1.0.0
zope.interface==4.7.1

### Who can help?

I'm trying to run an agent based on local `ollama mistral:7b-instruct` and stop is not working. Is it a bug or I configured wrong? Thanks in advance!

```
from langchain.agents import Tool, AgentExecutor, LLMSingleActionAgent, AgentOutputParser
from langchain.prompts import StringPromptTemplate
from langchain.llms import OpenAI
from langchain.utilities import SerpAPIWrapper
from langchain.chains import LLMChain
from typing import List, Union
from langchain.schema import AgentAction, AgentFinish, OutputParserException
import re
from langchain.llms import Ollama
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout_final_only import FinalStreamingStdOutCallbackHandler

from langchain.agents import tool

@tool
def get_word_length(word: str) -> int:
    """Returns the length of a word."""    
    return len(word.strip().split()[0])

tools = [get_word_length]

# Set up the base template
template = """Answer the following questions as best you can. You have access to the following tools:

{tools}

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question 

Begin! If you can use a tool, use it before the final answer. Do not make up an observation before calling an action!

Question: {input}
{agent_scratchpad}"""

# Set up a prompt template
class CustomPromptTemplate(StringPromptTemplate):
    # The template to use
    template: str
    # The list of tools available
    tools: List[Tool]

    def format(self, **kwargs) -> str:
        # Get the intermediate steps (AgentAction, Observation tuples)
        # Format them in a particular way
        intermediate_steps = kwargs.pop("intermediate_steps")
        thoughts = ""
        for action, observation in intermediate_steps:
            thoughts += action.log
            thoughts += f"\nObservation: {observation}\nThought: "
        # Set the agent_scratchpad variable to that value
        kwargs["agent_scratchpad"] = thoughts
        # Create a tools variable from the list of tools provided
        kwargs["tools"] = "\n".join([f"{tool.name}: {tool.description}" for tool in self.tools])
        # Create a list of tool names for the tools provided
        kwargs["tool_names"] = ", ".join([tool.name for tool in self.tools])
        return self.template.format(**kwargs)
    
prompt = CustomPromptTemplate(
    template=template,
    tools=tools,
    # This omits the `agent_scratchpad`, `tools`, and `tool_names` variables because those are generated dynamically
    # This includes the `intermediate_steps` variable because that is needed
    input_variables=["input", "intermediate_steps"]
)

class CustomOutputParser(AgentOutputParser):

    def parse(self, llm_output: str) -> Union[AgentAction, AgentFinish]:
        # Check if agent should finish
        if "Final Answer:" in llm_output:
            return AgentFinish(
                # Return values is generally always a dictionary with a single `output` key
                # It is not recommended to try anything else at the moment :)
                return_values={"output": llm_output.split("Final Answer:")[-1].strip()},
                log=llm_output,
            )
        # Parse out the action and action input
        regex = r"Action\s*\d*\s*:(.*?)\nAction\s*\d*\s*Input\s*\d*\s*:[\s]*(.*)"
        match = re.search(regex, llm_output, re.DOTALL)
        if not match:
            raise OutputParserException(f"Could not parse LLM output: `{llm_output}`")
        action = match.group(1).strip()
        action_input = match.group(2)
        # Return the action and action input
        return AgentAction(tool=action, tool_input=action_input.strip(" ").strip('"'), log=llm_output)


output_parser = CustomOutputParser()

ollama = Ollama(model="mistral:7b-instruct", callbacks=[FinalStreamingStdOutCallbackHandler()])

# LLM chain consisting of the LLM and a prompt
llm_chain = LLMChain(llm=ollama, prompt=prompt)

tool_names = [tool.name for tool in tools]
agent = LLMSingleActionAgent(
    llm_chain=llm_chain,
    output_parser=output_parser,
    stop=["Observation:"],
    allowed_tools=tool_names
)

agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True)
agent_executor.run("How many letters in the word astronomia?")
```

    @hwchase17
    @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Run the code above

### Expected behavior

Expected to stop on Observation

**Comment by glad4enkonm** [comment]
@dosu-bot explain how can i change my code to pass stop param?

**Comment by glad4enkonm** [comment]
So far i understand it is a bug and need to be fixed, I used debug tools to get to the http request to ollama.
It sends a request with 2 stop arguments, and the one under options is null.

`b'{"prompt": "Answer the following questions as best you can. You have access to the following tools:\n\nget_word_length: get_word_length(word: str) -> int - Returns the length of a word.\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [get_word_length]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question \n\nBegin!\n\nQuestion: How many letters in the word astronomia?\n", "model": "mistral:7b-instruct", "options": {"mirostat": null, "mirostat_eta": null, "mirostat_tau": null, "num_ctx": null, "num_gpu": null, "num_thread": null, "repeat_last_n": null, "repeat_penalty": null, "temperature": null, "stop": null, "tfs_z": null, "top_k": null, "top_p": null}, "stop": ["Observation:"]}' (edited)`

the next is a simplified example in curl

```
curl -X POST http://localhost:11434/api/generate -d '{                        
  "model": "mistral:7b-instruct",
  "prompt":"I want you to output a funny joke then the following text: `Observation:`",
  "stop": ["Observation:"],
  "options": {"stop": null},
  "stream": false
}'
```

**Comment by glad4enkonm** [comment]
So far i understand it is a bug and need to be fixed, I used debug tools to get to the http request to ollama.
It sends a request with 2 stop arguments, and the one under options is null.

`b'{"prompt": "Answer the following questions as best you can. You have access to the following tools:\n\nget_word_length: get_word_length(word: str) -> int - Returns the length of a word.\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [get_word_length]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question \n\nBegin!\n\nQuestion: How many letters in the word astronomia?\n", "model": "mistral:7b-instruct", "options": {"mirostat": null, "mirostat_eta": null, "mirostat_tau": null, "num_ctx": null, "num_gpu": null, "num_thread": null, "repeat_last_n": null, "repeat_penalty": null, "temperature": null, "stop": null, "tfs_z": null, "top_k": null, "top_p": null}, "stop": ["Observation:"]}' (edited)`

the next is a simplified example in curl

```
curl -X POST http://localhost:11434/api/generate -d '{                        
  "model": "mistral:7b-instruct",
  "prompt":"I want you to output a funny joke then the following text: `Observation:`",
  "stop": ["Observation:"],
  "options": {"stop": null},
  "stream": false
}'
```

**Comment by glad4enkonm** [comment]
it was closed by mistake, could you please reopen it?

**Comment by glad4enkonm** [comment]
now reopened

**Comment by glad4enkonm** [comment]
I created a fix that solved problem in my case. @hwchase17 @agola11, could you have a look and decide if that might be useful to others?

**Comment by stefnestor** [comment]
At least for me, the original error bug is still there but at least it doesn't infinitely keep talking to itself anymore. (Thanks @glad4enkonm !)

[Previous code/setup outline](https://medium.com/@stefnestor/python-streamlit-local-llm-2aaa75961d03) with Python's Streamlit w/changes today

```bash
$ brew install ollama
$ ollama --version
ollama version is 0.1.23

$ pip install langchain --upgrade
$ pip list langchain | grep langchain
langchain                                         0.1.5
langchain-community                               0.0.19
langchain-core                                    0.1.21
```

<img width="735" alt="image" src="https://github.com/langchain-ai/langchain/assets/26751266/c70f71cb-b5c8-4ca4-ad96-473aaf421a1e">
