### ISSUE TITLE
Please provide tutorials for using other LLM models beside OpenAI.

### ISSUE THREAD

**Issue by groundswel** [langchain-ai/langchain#1289]
Please provide tutorials for using other LLM models beside OpenAI. Even though documentation implies it is possible to use other LLM models there is no solid example of that.  I would like to download a LLM model and use it with langchain.

**Comment by robertritz** [comment]
Having tried several, I think the reason no examples are shown is that their outputs are suboptimal. With lots of prompt engineering, you can get usable results but nothing as comprehensive or as good as GPT-3 Davinci.

But this depends on your use case. If you want shorter more specific answers then I had good luck with Cohere or even some models on the Hugging Face Hub.
