### ISSUE TITLE
Encounter KeyError: 'user_agent' while using CohereRerank()

### ISSUE THREAD

**Issue by plaban1981** [langchain-ai/langchain#12899]
### System Info

langchain==0.0.330
Python 3.10.12

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CohereRerank

#
compressor = CohereRerank()
#

Error Encountered
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-29-be190c4da94f>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 #
----> 5 compressor = CohereRerank()
      6 #
      7 compression_retriever = ContextualCompressionRetriever(

2 frames
/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.validate_model()

[/usr/local/lib/python3.10/dist-packages/langchain/retrievers/document_compressors/cohere_rerank.py](https://localhost:8080/#) in validate_environment(cls, values)
     53             values, "cohere_api_key", "COHERE_API_KEY"
     54         )
---> 55         client_name = values["user_agent"]
     56         values["client"] = cohere.Client(cohere_api_key, client_name=client_name)
     57         return values

KeyError: 'user_agent'

### Expected behavior

The below error should not have been encountered as the COHERE API Key has alreday been set and cohere.Client() is workin with the api key provided

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-29-be190c4da94f>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 #
----> 5 compressor = CohereRerank()
      6 #
      7 compression_retriever = ContextualCompressionRetriever(

2 frames
/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.validate_model()

[/usr/local/lib/python3.10/dist-packages/langchain/retrievers/document_compressors/cohere_rerank.py](https://localhost:8080/#) in validate_environment(cls, values)
     53             values, "cohere_api_key", "COHERE_API_KEY"
     54         )
---> 55         client_name = values["user_agent"]
     56         values["client"] = cohere.Client(cohere_api_key, client_name=client_name)
     57         return values

KeyError: 'user_agent'

**Comment by gardner** [comment]
A workaround:

```python
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CohereRerank
from os import getenv

class CustomCohereRerank(CohereRerank):
    user_agent = 'gardner'

def get_compressor(retriever):
    if getenv("COHERE_API_KEY", False) != False:
        return ContextualCompressionRetriever(
            base_compressor=CustomCohereRerank(), base_retriever=retriever
        )
    else:
        return retriever
```

**Comment by gardner** [comment]
@billytrend-cohere do you recognize this part of the code?

**Comment by yoch** [comment]
Hi,

Same issue here with up to date version.

The workaround is simply to pass the user_agent explicitely, but according to the documentation I'm not intended to do so.

```
compressor = CohereRerank(
    model='rerank-multilingual-v2.0',
    user_agent="langchain", # fixes the KeyError: 'user_agent'
)
```

**Comment by gardner** [comment]
@dosubot this was fixed in https://github.com/langchain-ai/langchain/pull/14029
