### ISSUE TITLE
RuntimeError when setting up self hosted model + runhouse integration

### ISSUE THREAD

**Issue by dcavadia** [langchain-ai/langchain#1290]
Im having this bug when trying to setup a model within a lambda cloud running SelfHostedHuggingFaceLLM() after the rh.cluster() function. 

`
from langchain.llms import SelfHostedPipeline, SelfHostedHuggingFaceLLM
from langchain import PromptTemplate, LLMChain
import runhouse as rh
gpu = rh.cluster(name="rh-a10", instance_type="A10:1").save()
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
llm = SelfHostedHuggingFaceLLM(model_id="gpt2", hardware=gpu, model_reqs=["pip:./", "transformers", "torch"])
`

![image](https://user-images.githubusercontent.com/53955221/221334016-8b3a8e90-f240-417d-a064-3f0a149bd465.png)

I made sure with sky check that the lambda credentials are set, but the error i get within the log is this, which i havent been able to solve.

![image](https://user-images.githubusercontent.com/53955221/221334232-53a424e3-d49e-43f6-92fb-01d0ca6c64db.png)

If i can get any help solving this i would appreciate it.

**Comment by dongreenberg** [comment]
Being discussed in https://github.com/run-house/runhouse/issues/9, we can close this.
