### ISSUE TITLE
Langchain connects Neo4j v5.9 error Could not use APOC procedures

### ISSUE THREAD

**Issue by ichenhua** [langchain-ai/langchain#12901]
### System Info

I have successfully installed the apoc plugin by pressing the neo4j document, and run ` return apoc.version() ` on the neo4j client to return successfully. 
However, when Neo4jGraph was used in Langchain connection, errors were still reported.
```
ValueError: Could not use APOC procedures. Please ensure the APOC plugin is installed in Neo4j and that 'apoc.meta.data()' is allowed in Neo4j configuration 
```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.graphs import Neo4jGraph

graph = Neo4jGraph(
    'bolt://localhost:7687',
    'neo4j',
    'chenhuabc'
)

print(graph)

# ValueError: Could not use APOC procedures. Please ensure the APOC plugin is installed in Neo4j and that 'apoc.meta.data()' is allowed in Neo4j configuration 

### Expected behavior

I have successfully installed the apoc plugin by pressing the neo4j document, and run ` return apoc.version() ` on the neo4j client to return successfully. 
However, when Neo4jGraph was used in Langchain connection, errors were still reported.
```
ValueError: Could not use APOC procedures. Please ensure the APOC plugin is installed in Neo4j and that 'apoc.meta.data()' is allowed in Neo4j configuration 
```

**Comment by ichenhua** [comment]
the config has been modified
```
dbms.security.procedures.unrestricted=apoc.*
dbms.security.procedures.allowlist=apoc.*
```
and, `call apoc.meta.data()` is ok.

**Comment by ichenhua** [comment]
already solved.

**Comment by taigfs** [comment]
> already solved.

hey @ichenhua, how did you solve it?

**Comment by billygogo** [comment]
I solved this problem.

1. copy  this file  'apoc-5.14.0-core.jar' from **/var/lib/neo4j/labs/**   to  **/var/lib/neo4j/plugins**
2. update this file **/var/lib/neo4j/conf/neo4j.conf**  
dbms.security.procedures.unrestricted=apoc.*
dbms.security.procedures.allowlist=apoc.*

good luck~!

**Comment by vriez** [comment]
> the config has been modified
> 
> ```
> dbms.security.procedures.unrestricted=apoc.*
> dbms.security.procedures.allowlist=apoc.*
> ```
> 
> and, `call apoc.meta.data()` is ok.

this worked for me

**Comment by hafiz031** [comment]
> I solved this problem.
> 
> 1. copy  this file  'apoc-5.14.0-core.jar' from **/var/lib/neo4j/labs/**   to  **/var/lib/neo4j/plugins**
> 2. update this file **/var/lib/neo4j/conf/neo4j.conf**
>    dbms.security.procedures.unrestricted=apoc.*
>    dbms.security.procedures.allowlist=apoc.*
> 
> good luck~!

In my case I updated in `/etc/neo4j/neo4j.conf` file, which also worked.

**Comment by 631068264** [comment]
If run neo4j with docker  try `--env='NEO4JLABS_PLUGINS=["apoc"]'`

**Comment by LeJoshymo** [comment]
Has anyone experienced this connecting to Aura?

**Comment by VikrantModi** [comment]
While using the process for apoc error , I am getting this error .Please solve this error 



"DBMS failed to start: DBMS process terminated, see logs..
The following logs and troubleshooting guide may help you diagnose the issue:
Desktop logs
Neo4j DBMS logs
Troubleshooting guide"

**Comment by niejichun** [comment]
> 如果使用 docker 运行 neo4j 尝试`--env='NEO4JLABS_PLUGINS=["apoc"]'`



> If run neo4j with docker try `--env='NEO4JLABS_PLUGINS=["apoc"]'`

This works for me

**Comment by nathan-sumit** [comment]
> Has anyone experienced this connecting to Aura?

I haven't been able to get this to work for Neo4j Aura, I don't believe you can edit the .conf file i Aura.

**Comment by sikdarananya** [comment]
> While using the process for apoc error , I am getting this error .Please solve this error
> 
> "DBMS failed to start: DBMS process terminated, see logs.. The following logs and troubleshooting guide may help you diagnose the issue: Desktop logs Neo4j DBMS logs Troubleshooting guide"

Hey, were you able to solve it?

**Comment by luisramosbosch** [comment]
HI guys, I have neo4j desktop in windows, and I am experimenting the same issue. 

ValueError: Could not use APOC procedures. Please ensure the APOC plugin is installed in Neo4j and that 'apoc.meta.data()' is allowed in Neo4j configuration

I installed apoc following the desktop assistant, and this this:


    copy this file 'apoc-5.14.0-core.jar' from /var/lib/neo4j/labs/ to /var/lib/neo4j/plugins
    update this file /var/lib/neo4j/conf/neo4j.conf
    dbms.security.procedures.unrestricted=apoc.*
    dbms.security.procedures.allowlist=apoc.*


with no luck


Luis

**Comment by VikrantModi** [comment]
> HI guys, I have neo4j desktop in windows, and I am experimenting the same issue.
> 
> ValueError: Could not use APOC procedures. Please ensure the APOC plugin is installed in Neo4j and that 'apoc.meta.data()' is allowed in Neo4j configuration
> 
> I installed apoc following the desktop assistant, and this this:
> 
> ```
> copy this file 'apoc-5.14.0-core.jar' from /var/lib/neo4j/labs/ to /var/lib/neo4j/plugins
> update this file /var/lib/neo4j/conf/neo4j.conf
> dbms.security.procedures.unrestricted=apoc.*
> dbms.security.procedures.allowlist=apoc.*
> ```
> 
> with no luck
> 
> Luis

**Comment by matteo-rizzo** [comment]
Be careful of the db name, that could cause the error.

**Comment by enochkan** [comment]
for those of you who're on a mac, installed using `brew`, try running

```bash
cp labs/apoc-2025.01.0-core.jar plugins
```

before changing config.

**Comment by MrMoggy** [comment]
In addition to the above configuration, if it still doesn't take effect, restart neo4j. If it still doesn't work, restart your computer. My macOS took effect only after restarting.

**Comment by chuan2019** [comment]
I encountered the same issue. In my case, I run Neo4j in docker containers, in my docker-compose.yml file, I added the following `environment` configurations
```
services:
  neo4j:
    ...
    environment:
      ...
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      ...
```
and the issue is fixed.
