### ISSUE TITLE
Issue: How to deploy langchain using docker and redis used by langchain

### ISSUE THREAD

**Issue by VpkPrasanna** [langchain-ai/langchain#12910]
### Issue you'd like to raise.

I am using  RedisChatMessageHistory from langchain  and i am trying to deploy it using docker and i am facing issues in connecting to the redis . can someone help me over here @hwchase17

**Comment by VpkPrasanna** [comment]
@dosu-bot this was my compose file but still it is not working 


`version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    networks:
      - my-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  Bot:
    image: imagex
    container_name: container1
    ports:
      - "8000:8000"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge

volumes:
  redis_data:`

**Comment by umair313** [comment]
@VpkPrasanna what error you are getting when connecting to Redis?
can you share the code as well?

**Comment by VpkPrasanna** [comment]
I am try to connect something like this 
`
url = "redis://localhost:6379/0"
redis_client = get_client(redis_url=url)
`
this is how i am connecting to redis-client in my application container

**Comment by Spartee** [comment]
try replacing ``localhost`` with ``redis``

**Comment by VpkPrasanna** [comment]
> try replacing `localhost` with `redis`

This method worked , thanks @Spartee  @umair313
