### ISSUE TITLE
DocArrayInMemorySearch | Pydantic 2+ Breaking Changes

### ISSUE THREAD

**Issue by WalnutStudios** [langchain-ai/langchain#12916]
### System Info

langchain==0.0.330
Python 3.10.8

### Who can help?

@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Was using latest release of pydantic (2.4.2).

getting errors to install langchain[docarray]

Above that:
ImportError: cannot import name 'ROOT_KEY' from 'pydantic.main' (...venv\lib\site-packages\pydantic\main.py)

Retried using pydantic 1.10.13. Works fine now. Not sure if worth adding to the error message or building in langchain dependence of pydantic version <2.0

I didn't try all the versions, but I know 2.4.2 breaks.

### Expected behavior

I wasn't able to set my index. Here is where the code broke:
index = VectorstoreIndexCreator(
    vectorstore_cls=DocArrayInMemorySearch
).from_loaders([loader])

**Comment by angusfong** [comment]
Does LangChain have plans update support for Pydantic v2? It is difficult to pin to Pydantic 1 in my development workflow. For instance, I am using Mistral AI's Python client, which has a hard dependency on pydantic 2.
