### ISSUE TITLE
PGVector: support for concurrency

### ISSUE THREAD

**Issue by VinzenzKlass** [langchain-ai/langchain#12933]
### Feature request

When trying to concurrently fetch many collections from a single postgres server using PGVector, this will currently produce this error:
``` 
(psycopg2.errors.InternalError_) tuple concurrently updated
```

This is the expected behaviour for the code as it is and is produced by this line:
```
statement = sqlalchemy.text("CREATE EXTENSION IF NOT EXISTS vector")
```

There is no support for concurrent `CREATE EXTENSION` Operations in Postgres, as outlined in [this post](https://www.postgresql.org/message-id/3473.1393693757%40sss.pgh.pa.us):

> It'd be necessary to add some kind of locking scheme if you want to avoid "tuple concurrently updated" errors.  This is not really any different from the situation where two transactions both want to update the same row in a user table: unless the application takes extra steps to serialize the updates, you're going to get "tuple concurrently updated" errors. 
> 
> We do have such locking for DDL on tables/indexes, but the theory in the past has been that it's not worth the trouble for objects represented by single catalog rows, such as functions or roles.  You can't corrupt the database with concurrent updates on such a row, you'll just get a "tuple concurrently updated" error from all but the first-to-arrive update.

As the post suggests, if we want to concurrently run these statements, a locking Scheme is needed. This can easily be achieved by using Postgres' `pg_advisory_xact_lock`, as described [here](https://www.postgresql.org/docs/16/explicit-locking.html#ADVISORY-LOCKS) & [here](https://www.postgresql.org/docs/16/functions-admin.html):

``` 
BEGIN;
SELECT pg_advisory_xact_lock(1573678846307946496);
CREATE EXTENSION IF NOT EXISTS vector;
COMMIT;
``` 

This will acquire an exclusive transaction-level advisory lock, waiting if necessary which is automatically released at the end of the transaction. My proposal is therefore to change the current bare `CREATE EXTENSION IF NOT EXISTS vector` with the above to allow for concurrent execution without errors or having to retry.

### Motivation

We have a scenario where it would be beneficial to concurrently retrieve a large number of collections from a single server, and this would appear to be the easiest way to achieve this.

### Your contribution

I will submit an according PR.

**Comment by eyurtsev** [comment]
Thanks @VinzenzKlass
