### ISSUE TITLE
openai has no ChatCompletion attribute, this is likely due to an old version of the openai package. 

### ISSUE THREAD

**Issue by cta2106** [langchain-ai/langchain#12949]
### System Info

Langchain v0.0.323
Openai v1.0.1 (latest)
Python v3.11.6

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(
    model_name="gpt-4",
    request_timeout=120,
)

```

openai has no ChatCompletion attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)

### Expected behavior

There is an issue with ChatOpenAI that I believe may be related to the newest openai python package update.

**Comment by DavisBroda** [comment]
Same error

**Comment by ddm1293** [comment]
Same

**Comment by dimasgb7** [comment]
same

**Comment by anwoflow** [comment]
looks like openai just changed their API and the openai.Completion.create doesn't work at the moment. 
client.chat.completions.create is what works now, and it looks like the response structure also changed.

**Comment by msunkarahend** [comment]
I am also getting the same error. 
![image](https://github.com/langchain-ai/langchain/assets/142630126/2aacefd6-8ce3-4002-9c3d-69ee7d33c066)

earlier, i got another error(shown below).. but then changed the code to azure SDK instead of using langchain. 
![image](https://github.com/langchain-ai/langchain/assets/142630126/e19893c3-891c-4f75-907a-b2fc0ef974c8)

Is it an issue with langchain or openai package.. what should i do to avoid such errors in future as well. when i productionize my code i cant afford to have this type of errors.. what is the best way going forward.

**Comment by theECEjourney** [comment]
OpenAI dev day fever ? 😅

**Comment by gaodi16366** [comment]
same when using AzureChatOpenAI

**Comment by msunkarahend** [comment]
https://github.com/langchain-ai/langchain/issues/12956#issuecomment-1797060350

openai 0.28.1
langchain 0.0.330

this should solve the issue for now.

**Comment by TranPhu1999** [comment]
> [#12956 (comment)](https://github.com/langchain-ai/langchain/issues/12956#issuecomment-1797060350)
> 
> openai 0.28.1 langchain 0.0.330
> 
> this should solve the issue for now.

Until there is a patch to fix this issue, this work for me, thanks

**Comment by EduuF** [comment]
> [#12956 (comment)](https://github.com/langchain-ai/langchain/issues/12956#issuecomment-1797060350)
> 
> openai 0.28.1 langchain 0.0.330
> 
> this should solve the issue for now.

It worked for me, thanks a lot

**Comment by karfly** [comment]
Looking forward to see proper integration of new openai lib

**Comment by Yual16078** [comment]
I also encountered the same problem, hope it can help you

Terminal:
export OPENAI_API_KEY='your-api-key-here'

`from openai import OpenAI

client = OpenAI()
# defaults to getting the key using os.environ.get("OPENAI_API_KEY")
# if you saved the key under a different environment variable name, you can do something like:
# client = OpenAI(
#   api_key=os.environ.get("CUSTOM_ENV_NAME"),
# )`

**Comment by ChameliMasha** [comment]
Faced the same issue.

AttributeError: module 'openai' has no attribute 'ChatCompletion'
My Python version is 3.12.0  and openai version 1.1.1.  

Tried reinstalling openai but it didin't work. Still getting the same error

**Comment by HEYBOY789** [comment]
same error. Any fix?

**Comment by Kotrotsos** [comment]
The latest SDK introduced breaking changes in Chatcompletions payload and response. 
Revert to the 'old' SDK until you have those fixed.
requirements.txt
`openai == 0.28.1`

the `client.chat.completions.create` is new for instance.

`from openai import OpenAI
client = OpenAI()

response = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Who won the world series in 2020?"},
    {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
    {"role": "user", "content": "Where was it played?"}
  ]
)`

**Comment by tkreuder** [comment]
In case somebody uses the combination together with **llama_index**:
```
openai==0.28.1
langchain==0.0.330
llama_index==0.8.62
```

These versions work fine together. So you just need to update your requirements.txt (or requirements.in) and pin the packages to these versions.

**Comment by ArslanKAS** [comment]
> openai==0.28.1
> langchain==0.0.330

Thank you

**Comment by roaringsheep** [comment]
> The latest SDK introduced breaking changes in Chatcompletions payload and response. Revert to the 'old' SDK until you have those fixed. requirements.txt `openai == 0.28.1 langchain == 0.0.330`
> 
worked like a charm. Thank you!

**Comment by vshelke** [comment]
> [#12956 (comment)](https://github.com/langchain-ai/langchain/issues/12956#issuecomment-1797060350)
> 
> openai 0.28.1 langchain 0.0.330
> 
> this should solve the issue for now.

Thanks a lot man, this worked for me.

**Comment by ica574** [comment]
I have the same issue. Resolved it temporarily by reverting `openai`, and `langchain` to an older version.

**Comment by vlasvlasvlas** [comment]
yep needed to rollback version til the patch/fix gets published

**Comment by deepnavy** [comment]
If you want to try new OpenAI capabilities with LangChain try this pre-release `pip install langchain==0.0.331rc2`

**Comment by lesong36** [comment]
> If you want to try new OpenAI capabilities with LangChain try this pre-release `pip install langchain==0.0.331rc2`

Which I did try, but it is same result.

------------
Name: langchain
Version: 0.0.331rc2
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /home/coty/miniconda3/envs/jupyter/lib/python3.11/site-packages
Requires: aiohttp, anyio, dataclasses-json, jsonpatch, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: jupyter_ai, jupyter_ai_magics, langchain-experimental, langserve
---
Name: openai
Version: 1.1.2
Summary: Client library for the openai API
Home-page: 
Author: 
Author-email: OpenAI <support@openai.com>
License: 
Location: /home/coty/miniconda3/envs/jupyter/lib/python3.11/site-packages
Requires: anyio, distro, httpx, pydantic, tqdm, typing-extensions
Required-by: guidance, jupyter_ai, pyautogen
---
Name: langchain-experimental
Version: 0.0.39
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /home/coty/miniconda3/envs/jupyter/lib/python3.11/site-packages
Requires: langchain
Required-by: 
Note: you may need to restart the kernel to use updated packages.


from langchain.llms import OpenAI
llm = OpenAI()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 3
      1 from langchain.llms import OpenAI
----> 3 llm = OpenAI()

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/load/serializable.py:97, in Serializable.__init__(self, **kwargs)
     96 def __init__(self, **kwargs: Any) -> None:
---> 97     super().__init__(**kwargs)
     98     self._lc_kwargs = kwargs

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/pydantic/main.py:339, in pydantic.main.BaseModel.__init__()

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/pydantic/main.py:1102, in pydantic.main.validate_model()

File ~/miniconda3/envs/jupyter/lib/python3.11/site-packages/langchain/llms/openai.py:266, in BaseOpenAI.validate_environment(cls, values)
    263 try:
    264     import openai
--> 266     values["client"] = openai.Completion
    267 except ImportError:
    268     raise ImportError(
    269         "Could not import openai python package. "
    270         "Please install it with `pip install openai`."
    271     )

AttributeError: module 'openai' has no attribute 'Completion'

**Comment by shlomi-schwartz** [comment]
I trust that this will receive the attention it merits, as it is a significant impediment for projects relying on Langchain.

**Comment by ryan-dervakos** [comment]
I think they fixed this, I did a fresh install of my project and now it works

**Comment by ksteward** [comment]
Perhaps it fixed your issue but I'm seeing a conflict over OpenAI() between langchain's version and OpenAI's version.
I updated to the `openai==1.2.0` and `langchain==0.0.333` but am seeing a conflict in the use of OpenAI():  Having the folloiwing imports results in an error message:
`from openai import OpenAI`
`from langchain.llms import OpenAI`

"ImportError: cannot import name 'OpenAI' from 'openai'"

Having the `from openai import OpenAI` and then client=OpenAI() in a separate script w/o importing langchain doesn't have the error.
Langchain team ?
