### ISSUE TITLE
Recent langchain version not matching openai v1.0.0+ release spec for client

### ISSUE THREAD

**Issue by realoptimal** [langchain-ai/langchain#12958]
### System Info

Langchain: v0.0.331
openai: v1.1.0
platform: Mac M2
python: 3.11.2

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Import OpenAI from llms
2. Instantiate it

```
>>> from langchain.llms import OpenAI
>>> llm = OpenAI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/pydantic/v1/main.py", line 1102, in validate_model
    values = validator(cls_, values)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lifehedging/.pyenv/versions/myenv/lib/python3.11/site-packages/langchain/llms/openai.py", line 266, in validate_environment
    values["client"] = openai.Completion
                       ^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'Completion'. Did you mean: 'completions'?
```

### Expected behavior

It correctly instantiates provided an API key is present in the environment

**Comment by dimasgb7** [comment]
same

**Comment by GhimBoon** [comment]
openai just dropped their 1.0 which have changes in the API interfaces:
https://github.com/openai/openai-python/discussions/631

Langchain currently doesn't support openai 1.0 API.

**Comment by kordou** [comment]
Hi i hust trying to install it and got the same error. any fixes ?

**Comment by aiyuekuang** [comment]
if fixed this，call me，please

**Comment by realoptimal** [comment]
Should have filed this differently.  Fix is to use a OpenAI v0.28.1

**Comment by rajib76** [comment]
Is moving to 0.28.1 the only way?

**Comment by kordou** [comment]
O installed a version of open ai smaller that 1 and it works

Στις Παρ 10 Νοε 2023, 5:22 π.μ. ο χρήστης rajib ***@***.***>
έγραψε:

**Comment by iamrehman** [comment]
Facing the same problem.

**Comment by satoooh** [comment]
```python
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
```

@realoptimal 
Does using ChatOpenAI instead of OpenAI solve your problem?
I was facing the same kind of error, but I solved it by introducing the `langchain-openai` library and using ChatOpenAI.
