### ISSUE TITLE
Issue: "response_format" parameter on the new GPT-4-turbo model

### ISSUE THREAD

**Issue by tiagobe86** [langchain-ai/langchain#12953]
### "response_format" parameter on the new GPT-4-turbo model

I can sucessfully call the new GPT-4-turbo model by using:

`const model = new ChatOpenAI({modelName:"gpt-4-1106-preview"})`

But I can't add the "response_format" parameter to set its response explicitly to be a json, as stated in:

https://platform.openai.com/docs/guides/text-generation/json-mode

### Suggestion:

Is there a way to pass the parameter to the model or this should be added to the ChatOpenAI code?

**Comment by tiagobe86** [comment]
@dosu-bot

I see there is a model_kwargs variable. How do I pass the response_format variable using model_kwargs?

**Comment by davidrmcgee** [comment]
@dosu-bot, I am going to encourage this "enhancement to the ChatOpenAI class". You should also let the team know that their knowledge is out of date. @tiagobe86 is reporting an API update that was announced today and provided a reference. This statement is no longer correct as of a few hours ago. "Please note that the "response_format" parameter is not a standard parameter for the OpenAI API..."

@tiagobe86 report back on your efforts?

**Comment by amicus-veritatis** [comment]
same here, function calling doesn't work well for `gpt-4-1106-preview` model.

**Comment by tiagobe86** [comment]
@davidrmcgee @dosu-bot

I got it to work by passing the "response_format" variable under the modelKwargs parameter.

   ```javascript
 const chat = new ChatOpenAI({
      modelName: "gpt-4-1106-preview", 
      modelKwargs: {
        "response_format": { 
          type: "json_object" 
        }
      }
    });

``` 


Anyway, I think it is a good idea to implement this variable in the `ChatOpenAI` class.

**Comment by ekalosak** [comment]
I can confirm that the Python equivalent works:
```py
model = ChatOpenAI(
    model="gpt-3.5-turbo-1106",
    model_kwargs={"response_format": {"type": "json_object"}},
)
```

**Comment by Palisand** [comment]
As of this writing, you can also use `ChatOpenAI.with_structured_output(method="json_mode")`.
