### ISSUE TITLE
Module 'openai' has no attribute 'Embedding'

### ISSUE THREAD

**Issue by lucasdnr** [langchain-ai/langchain#12954]
### System Info

LangChain: 0.0.331
OpenAI: 1.1.0
Python:  3.11.2 

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Full Message:

> ...langchain/embeddings/openai.py", line 284, in validate_environment
>     values["client"] = openai.Embedding
>                        ^^^^^^^^^^^^^^^^
> AttributeError: module 'openai' has no attribute 'Embedding'. Did you mean: 'embeddings'?

Code line caught this error:

`index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory":"persist"}).from_loaders([loader])`

### Expected behavior

Creates Vector Store Index

**Comment by mwade-noetic** [comment]
I am also having the same issue.  Dropped back several version of openai library to no avail.  I am using python 3.11.4.  Latest openai (1.1.1) and langchain 0.0.331.  I also attempted version 0.0.330 of langchain and still getting the same issue.  The openai library seems to use openai.embeddings instead of openai.Embedding.

**Comment by alexmc2** [comment]
I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.

**Comment by dosuken123** [comment]
It looks like openai-python restructured package at their v1.0.x release https://github.com/langchain-ai/langchain/issues/12967#issuecomment-1797092130. This is likely the root cause that langchain can't find a designated class in `openai` package namespace.

We need to find an alternative class in the new architecture.

**Comment by alexmc2** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

It's working! Thanks so much! :D

**Comment by alexmc2** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

It's working! Thanks so much @dosuken123! :D

**Comment by 95** [comment]
Having this same issue as well, trying the fix

**Comment by Vkdel001** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

Life Saver !!

**Comment by KiranEC11** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

Thanks, it worked for me.

**Comment by zawkhantmaung-loftal** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

Thank you, it worked for me.

**Comment by lpm0073** [comment]
> > I'm also having the same issue with Python 3.11.4, openai (1.1.1), and LangChain 0.0.331.
> 
> Temporal "fix".. pin openai to 0.28.1 version! @alexmc2
> 
> `openai==0.28.1`

@benjaminbascary that worked. thanks!

**Comment by PavelAgurov** [comment]
I have the same issue in Colab

**Comment by seifeur** [comment]
same issue on collab, even with openai==0.28.1..

**Comment by PavelAgurov** [comment]
It works with openai==0.28.1, but need to restart kernel after re-install

**Comment by Vkdel001** [comment]
Many thanks 🙏

**Comment by vdelatorrelabs** [comment]
Yes openai = "0.28.1" solves the problem thanks!

**Comment by gurudewan** [comment]
is there any update - want to use this with new version of openai so i can use the latest models

**Comment by seifeur** [comment]
Solved in the latest update.

**Comment by Vkdel001** [comment]
Thanks

**Comment by shinchima** [comment]
> openai==0.28.1

thank you!!!!!!!!!!!!

my  langchain Version: 0.0.316
openai==0.28.1

works for me too.

**Comment by entzyeung** [comment]
It works for me too
