### ISSUE TITLE
A ton of Bugs after OpenAI API update today

### ISSUE THREAD

**Issue by Vanekkk1** [langchain-ai/langchain#12956]
### System Info

all last versions as of 6/11/2023

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run anything with OpeanAI ChatCompletions and Embeddings 

### Expected behavior

File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/embeddings/openai.py", line 284, in validate_environment
    values["client"] = openai.Embedding
                       ^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'Embedding'. Did you mean: 'embeddings'?

File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)

**Comment by msunkarahend** [comment]
@dosu-bot
even if i upgrade the openai to openai==1.1.0 version (latest). the issue is not resolved.

**Comment by vanduyta** [comment]
Hi, the same happened to me since I did not have fixed versions in requirements file. What worked was to install 
openai                 0.28.1
langchain              0.0.330
Good luck and good night after this wonderful evening with errors...

**Comment by dosuken123** [comment]
I checked in https://github.com/langchain-ai/langchain/issues/12967 that using `openai==v0.28.1` https://github.com/openai/openai-python/releases/tag/v0.28.1 mitigates this issue for now.

openai-python might have changed their API at the recent v1 bump.

**Comment by msunkarahend** [comment]
> Hi, the same happened to me since I did not have fixed versions in requirements file. What worked was to install openai 0.28.1 langchain 0.0.330 Good luck and good night after this wonderful evening with errors...

Thanks @vanduyta and @dosuken123. it worked for me too

**Comment by Bijas48** [comment]
> Hi, the same happened to me since I did not have fixed versions in requirements file. What worked was to install openai 0.28.1 langchain 0.0.330 Good luck and good night after this wonderful evening with errors...

Its work, thanks man

**Comment by m-cavazza** [comment]
This could be due to the new 'client' model of the OpenAI API in v1.1.0+
On the regular API where you would previously write:
 **openai.ChatCompletion.create** 
the syntax is now:
 **openai.chat.completions.create**
check also:
https://github.com/openai/openai-python/discussions/631
However, with Langchain we have no such access, and are getting this kind of error:
<img width="876" alt="Langchain" src="https://github.com/langchain-ai/langchain/assets/94544819/14dc4780-e62e-45c8-9291-d4563b585423">

**Comment by PilotGFX** [comment]
My issue was: ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs']) 
force installing langchain 0.335 and openai 1.3.0  works here. i have not tried all releases.  for info i can disclose openai 0.28 is from september the 26th 2023 and openai 1.3.0 is from november 15th 2023.
