### ISSUE TITLE
map_reduce Summarization results in AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Nilsooo** [langchain-ai/langchain#13004]
### System Info

Hi everyone, 

I am receveing the following error message when following your [documentation on the summarization.]( https://python.langchain.com/docs/use_cases/summarization): AttributeError: 'NoneType' object has no attribute 'startswith'

Any ideas what the problem is?

Looks like this is point where the notebook breaks:
` 62     # Check if the model matches a known prefix
   63     # Prefix matching avoids needing library updates for every model version release
   64     # Note that this can match on non-existent models (e.g., gpt-3.5-turbo-FAKE)
   65     for model_prefix, model_encoding_name in MODEL_PREFIX_TO_ENCODING.items():
---> 66         if model_name.startswith(model_prefix):
     67             return get_encoding(model_encoding_name)`

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [x] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://python.langchain.com/docs/use_cases/summarization

### Expected behavior

I exepect to receive a summary of summaries as explained here: https://python.langchain.com/docs/use_cases/summarization

**Comment by SrinivasMadsi** [comment]
It is expecting model to provide, I did like below to solve this issue
llm = AzureChatOpenAI(
    api_key=api_key,
    api_version=api_version,
    azure_endpoint=azure_endpoint,
    azure_deployment=chat_deployment_name,
    model='gpt-4o'  
)

Refer: https://github.com/openai/tiktoken/blob/main/tiktoken/model.py
