### ISSUE TITLE
Issue: Opensearch retiever threshold based on similarity score

### ISSUE THREAD

**Issue by VinuAbraham** [langchain-ai/langchain#13007]
### Issue you'd like to raise.

I am trying to create a rag using langchain, aws bedrock and opensearch. For I created an index using the code, 
```
from opensearchpy import OpenSearch
aos_client = OpenSearch(
        hosts=[{"host": opensearch_cluster_domain, "port": ops_port}],
        http_auth=auth,
        use_ssl=True,
        verify_certs=True,
        connection_class=RequestsHttpConnection,
        pool_maxsize=20,
    )
    settings = {"settings": {"index": {"knn": True, "knn.space_type": "cosinesimil"}}}
    response = aos_client.indices.create(index=index_name, body=settings)
```
For the retrieval part I am using langchain "RetrievalQA". Code for the same is 
```
gen_qa = RetrievalQA.from_chain_type(
            llm,
            chain_type="stuff",
            retriever=retriever.as_retriever(
                search_kwargs={"k": int(k), "score_threshold": float(score_threshold)}
            ),
            chain_type_kwargs=self.general_chain_type_kwargs,
            return_source_documents=True,
        )
```
I need to limit the docs returned from opensearch index based on similarity score. Eventhough I am giving the score threshold in search_kwargs, seems like it has no effect. 
Also tried this code  from the langchain [doc](https://api.python.langchain.com/en/latest/vectorstores/langchain.vectorstores.opensearch_vector_search.OpenSearchVectorSearch.html#langchain.vectorstores.opensearch_vector_search.OpenSearchVectorSearch.similarity_search_with_relevance_scores) 
```
docsearch.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={'score_threshold': 0.8}
)
```
And this is throwing NotImplementedError.
Is there any way that I can say to the retriever that I only need relevant docs which has a similarity score greater than a certain threshold. Any help will be appreciated, thanks.

**Comment by VinuAbraham** [comment]
@dosu-bot So what you are saying is that, langchain has not yet implemented the similarity_score_threshold method.  When i checked the code for opensearch vector from the file opensearchsearch_vector_search.py, I can see that the functionality i need is implemented there. How can i integrate this with the RetievalQA chain?

**Comment by younes-io** [comment]
https://github.com/langchain-ai/langchain/issues/13242
