### ISSUE TITLE
Issue: langchain agent doesnt work with the new json mode of gpt4-1106-preview

### ISSUE THREAD

**Issue by fisipro2** [langchain-ai/langchain#13003]
### Issue you'd like to raise.

When using the new gpt's json mode by setting response_format={ "type": "json_object" }, the langchain agent failed to parse the openai output, is there any plan to support that?

**Comment by bhargav-11** [comment]
bump

**Comment by shariqanwar20** [comment]
bump

**Comment by GhaithDek** [comment]
looks like we have a better reponse here:
https://github.com/langchain-ai/langchain/issues/12953#issuecomment-1796524810
or here:
https://js.langchain.com/docs/integrations/chat/openai

**Comment by zedle** [comment]
> looks like we have a better answer here: [#12953 (comment)](https://github.com/langchain-ai/langchain/issues/12953#issuecomment-1796524810) or here: https://js.langchain.com/docs/integrations/chat/openai

The kwarg method works, but breaks agents.

**Comment by LizaKing0** [comment]
> Bumping this!
> 
> ` llm = AzureChatOpenAI(
> 
> ```
>     model_kwargs={"response_format": {type: "json_object"}},
> )`
> ```
> 
> When running this via `AgentExecutor`
> 
> I get the following error
> 
> ` File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps **kw).encode(obj) File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) TypeError: keys must be str, int, float, bool or None, not type`

This particular case is because you're missing " around the type key. Should be 

```python
model_kwargs={"response_format": {"type": "json_object"}}
```

**Comment by aiwalter** [comment]
its still not working, no? Or is it working for anyone?

**Comment by cklapperich** [comment]
@aiwalter it seems to be working for me on python with the latest release, though I haven't tested it with Agents yet. :)
