### ISSUE TITLE
看了新的OpenAI开发者大会，langchain还有存在的必要吗

### ISSUE THREAD

**Issue by aiyuekuang** [langchain-ai/langchain#13046]
### Issue you'd like to raise.

新的chatgpt可以直接帮助人类分析，规划，似乎已经脱离了原本的软件开发模式，从人设计，到了ai设计了，langchain是不是已经过时了？

**Comment by aiyuekuang** [comment]
但是新版的chatgpt，貌似可以创建自己的gpt应用，我认为有代替langchain的功能点，这是否会有很大的影响

**Comment by williamxhero** [comment]
不好说，感觉很有可能会失去意义。Agent其实根本思想是可以反复调用 LLM 来实现任务规划，这一切都起源于一篇叫 什么 树决策 的论文。但如果我们都看到了，GPT现在直接可以返回多个步骤，不用反复调用。所以趋势很明显。

**Comment by lesong36** [comment]
Maybe it's a game of winter take all, but in my opinion, People like horizontal expansion, but not so many success on it.

Those focusing on its own field would get the most value. 
Just like Microsoft should focus on infrastructure.
OpenAI has its niche in LLM
NVIDIA earn money on GPU
Langchain organize the information routing.
...
