### ISSUE TITLE
No module named 'langserve.packages' when creating langchain-cli apps

### ISSUE THREAD

**Issue by umitmertcakmak** [langchain-ai/langchain#13049]
### System Info

Windows WSL 2 Ubuntu
Python 3.10.6
langchain-0.0.331 langchain-cli-0.0.15 langserve-0.0.24 langsmith-0.0.60

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

In a new virtual environment with Python 3.10.6, After running:
`pip install -U "langchain-cli[serve]"`

which installs "langchain-0.0.331 langchain-cli-0.0.15 langserve-0.0.24 langsmith-0.0.60" as shown below:

Successfully installed PyYAML-6.0.1 SQLAlchemy-2.0.23 aiohttp-3.8.6 aiosignal-1.3.1 annotated-types-0.6.0 anyio-3.7.1 async-timeout-4.0.3 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 dataclasses-json-0.6.1 exceptiongroup-1.1.3 fastapi-0.104.1 frozenlist-1.4.0 gitdb-4.0.11 gitpython-3.1.40 greenlet-3.0.1 h11-0.14.0 httpcore-1.0.1 httpx-0.25.1 httpx-sse-0.3.1 idna-3.4 jsonpatch-1.33 jsonpointer-2.4 langchain-0.0.331 langchain-cli-0.0.15 langserve-0.0.24 langsmith-0.0.60 markdown-it-py-3.0.0 marshmallow-3.20.1 mdurl-0.1.2 multidict-6.0.4 mypy-extensions-1.0.0 numpy-1.26.1 packaging-23.2 pydantic-2.4.2 pydantic-core-2.10.1 pygments-2.16.1 requests-2.31.0 rich-13.6.0 shellingham-1.5.4 smmap-5.0.1 sniffio-1.3.0 sse-starlette-1.6.5 starlette-0.27.0 tenacity-8.2.3 tomli-2.0.1 typer-0.9.0 typing-extensions-4.8.0 typing-inspect-0.9.0 urllib3-2.0.7 uvicorn-0.23.2 yarl-1.9.2

I try to run `langchain app new my-app --package rag-conversation`, and get the following error

Traceback (most recent call last):
  File "/home/mert/REPOSITORIES/GenAI/langserve-template/langserve-env/bin/langchain", line 5, in <module>
    from langchain_cli.cli import app
  File "/home/mert/REPOSITORIES/GenAI/langserve-template/langserve-env/lib/python3.10/site-packages/langchain_cli/cli.py", line 6, in <module>
    from langchain_cli.namespaces import app as app_namespace
  File "/home/mert/REPOSITORIES/GenAI/langserve-template/langserve-env/lib/python3.10/site-packages/langchain_cli/namespaces/app.py", line 12, in <module>
    from langserve.packages import get_langserve_export
ModuleNotFoundError: No module named 'langserve.packages'

### Expected behavior

Pulling template into a local repository

**Comment by jzvikart** [comment]
I'm also getting this error when trying to use `langchain` CLI.

Upon closer look I see that the current version of `langchain-cli` installs `langserve` module, but there is no module `packages` in it. Was it removed?

**Comment by pantulis** [comment]
It seems there was a breaking commit in langchain itself

https://github.com/langchain-ai/langserve/commit/eaaac09431e16a0a532c09642e2b934881301a8d

**Comment by angoodkind** [comment]
I'm getting a similar error when trying to use the `rag-conversation` template. When I run `langchain serve` I get the error: `ModuleNotFoundError: No module named 'rag_conversation'`. Is this also due to the breaking commit? How would I correct it?

**Comment by umitmertcakmak** [comment]
@angoodkind, which versions of the libraries you are using?

**Comment by MarkEdmondson1234** [comment]
I updated to latest version and it got fixed

**Comment by pantulis** [comment]
I got this error when trying to work with the opengpts repository, but the temporary fix for me was changing the dependency on langserve to be exactly equal to 0.0.23 and managed to make it run the opengpts backend and frontends, but repos move so fast that it is probably fixed by now.

**Comment by umitmertcakmak** [comment]
It works after an update, thank you!

**Comment by angoodkind** [comment]
I'm new to langchain. Since I had the error for the Template module, do I need to run an update on the whole langchain installation, or just the Template installation? How do Ido that?

**Comment by 5shekel** [comment]
what works for me as of now
```powershell
$ pip install -U "langchain-cli[serve]==0.0.15" langserve==0.0.22

$langchain app new my-app --package rag-conversation-zep
Adding https://github.com/langchain-ai/langchain.git@master...
 - Downloaded templates\rag-conversation-zep to rag_conversation_zep
To install:

pip install -e \
  my-app\packages\rag_conversation_zep
Run it? [y/N]: y
```

```

**Comment by umitmertcakmak** [comment]
I just installed it again
`pip3 install langchain-cli`

then run
`langchain app new my-app --package rag-chroma-private`
