### ISSUE TITLE
The prompt word format misleads the output content of the large model

### ISSUE THREAD

**Issue by ichenhua** [langchain-ai/langchain#13054]
### System Info

langchain   0.0.331

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

response_schemas = [
            ResponseSchema(type='list', name='disease', description='disease name')
]

**prompt**
The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "```json" and "```":

```json
{
        "disease": list  // disease name
}
```

**output**
{
        "disease": "感冒"  // disease name
}

This output cannot be parsed by StructuredOutputParser，Because it contains notes。

### Expected behavior

Expect to generate prompt words：

**prompt**
The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "```json" and "```"，and the field "disease" meas "disease name".

```json
{
        "disease": list
}
```

Expected output：

{
        "disease": "感冒"
}

**Comment by ichenhua** [comment]
What I mean is that this method built into langchain doesn't make sense for prompt words.
```
output_parser = StructuredOutputParser(response_schemas=response_schemas)
format_instructions = output_parser.get_format_instructions()
```

**Comment by xuhuizhang** [comment]
i guess the langchain team should change the prompt format from "The output should be a markdown code snippet formatted in the following schema, including the leading and trailing" to  "The output should be a markdown code snippet formatted in the following schema, including the leading"

or add the 

> {format_instruction}
> no trailing output at last.
> {message}

into the template, that wold work
