### ISSUE TITLE
Multiple values for keyword argument 'embedding_function'

### ISSUE THREAD

**Issue by 95** [langchain-ai/langchain#13050]
### System Info

Running on google colab. 
Everything was working up until today, which makes me think it's openAi update-related.

Versions:
Requirement already satisfied: langchain in /usr/local/lib/python3.10/dist-packages (**0.0.331**)
Requirement already satisfied: chromadb in /usr/local/lib/python3.10/dist-packages (**0.4.16**)
Openai version pinned to 0.28.1 as @hwchase17 recommended prior -- which had fixed my embeddings issue.

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python3
from langchain.vectorstores import Chroma
from langchain.embeddings import OpenAIEmbeddings

embeddings = OpenAIEmbeddings()
vectorstore = Chroma.from_documents(documents=splits, embedding_function=embeddings, persist_directory='/content/wtf')
vectorstore.persist()
retriever = vectorstore.as_retriever()

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-5-d086aa9b6782>](https://localhost:8080/#) in <cell line: 7>()
      5 
      6 embeddings = OpenAIEmbeddings()
----> 7 vectorstore = Chroma.from_documents(documents=splits, embedding_function=embeddings, persist_directory='/content/wtf')
      8 vectorstore.persist()
      9 retriever = vectorstore.as_retriever()

1 frames
[/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py](https://localhost:8080/#) in from_texts(cls, texts, embedding, metadatas, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    618             Chroma: Chroma vectorstore.
    619         """
--> 620         chroma_collection = cls(
    621             collection_name=collection_name,
    622             embedding_function=embedding,

TypeError: langchain.vectorstores.chroma.Chroma() got multiple values for keyword argument 'embedding_function'

### Expected behavior

It should run without an error and correctly embed the document splits, outputting the data in the persist directory.

**Comment by shawnesquivel** [comment]
@95  I don't know the solution for this but it works when you dont use named function parameters. try this instead

causes error
```
from langchain_community.vectorstores import Chroma
    db = Chroma.from_documents(
        documents=docs,
        embedding_function=embeddings,

```

no error
```
from langchain_community.vectorstores import Chroma

    db = Chroma.from_documents(
        docs,
        embeddings,
```

**Comment by orshkuri** [comment]
This is what worked for me:
`
from langchain_community.vectorstores import Chroma
db = Chroma(
        embedding_function=embeddings, 
        persist_directory=persistent_directory
    )
    db.add_documents(docs)
`
