### ISSUE TITLE
OpenAI instance of Runnable expected

### ISSUE THREAD

**Issue by wonderkidshihab** [langchain-ai/langchain#13053]
### System Info

# Hi there,
I have started learning about Langchain today. I was creating my first langchain prompt template but something doesn't seem to work.

Here is my code in main.py:
```python
from openai import OpenAI
from dotenv import load_dotenv
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

# Load the .env file
load_dotenv()

# Create an instance of the OpenAI class
def generate_pet_name(animal_type="dog"):
    
    prompt_template = PromptTemplate(
        input_variables=['animal_type'],
        template="I have a {animal_type} as my pet. Suggest me a name for it.",
    )

    name_chain = LLMChain(
        llm=OpenAI(),
        prompt=prompt_template,
    )

    response = name_chain({'animal_type': animal_type})
    print(response)


if __name__ == "__main__":
    generate_pet_name(animal_type="dog")
```

While I think the code is okay and I have followed the GitHub get started it doesn't seem to work and throwing me this error:
```console
Traceback (most recent call last):
  File "/Users/ss/Workspace/Ai/AMP/main.py", line 28, in <module>
    generate_pet_name(animal_type="dog")
  File "/Users/ss/Workspace/Ai/AMP/main.py", line 18, in generate_pet_name
    name_chain = LLMChain(
                 ^^^^^^^^^
  File "/Users/ss/Workspace/Ai/AMP/.venv/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/ss/Workspace/Ai/AMP/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for LLMChain
llm
  instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
llm
  instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
  ```
  
  
  Please Help me as I am not that proficient in Python.

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Just copy the code given there and run it. You will see the error.

### Expected behavior

Run the code and get a response without error

**Comment by adfriend2003** [comment]
I faced this issue and the resolution is following:

The issue is this line:
`
from openai import OpenAI
`

Replace above line with following:
`
from langchain.llms import OpenAI
`

Hence, the prob is wrong package.

**Comment by wonderkidshihab** [comment]
@adfriend2003 Thanks man... it helped me a lot

**Comment by Zeeshan0123** [comment]
import os
os.environ["GOOGLE_API_KEY"] = ''

from langchain.prompts import PromptTemplate

post_prompt = PromptTemplate.from_template(
    """You are a business owner. Given the theme of a post, write a social media post to share on my socials.

Theme: {theme}
Content: This is social media post based on the theme above:"""
)

review_prompt = PromptTemplate.from_template(
    """You are an expert social media manager. Given the presented social media post, it is your job to write a review for the post.

Social Media Post:
{post}
Review from a Social Media Expert:"""
)

from llama_index.llms.palm import PaLM

llm = PaLM(temperature=5)

from langchain_core.runnables import RunnablePassthrough
chain = (
    {"post": RunnablePassthrough() | post_prompt | llm | output_parser } 
    | review_prompt
    | llm
    | output_parser
)

chain.invoke({"theme": "Having a black friday sale with 50% off on everything."})

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-49-f8c8c78df21a>](https://localhost:8080/#) in <cell line: 3>()
      1 from langchain_core.runnables import RunnablePassthrough
      2 chain = (
----> 3     {"post": RunnablePassthrough() | post_prompt | llm | output_parser }
      4     | review_prompt
      5     | llm
      
 
TypeError: Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'llama_index.llms.palm.PaLM'>

anyone resolve this error please share the solution

**Comment by bretzNiklas** [comment]
For me this issue was caused by importing a function named "llm" that shadowed the actual llm variable i wanted to use.
I fixed this by going from
`import llm`

to

`from llm import llm`

**Comment by l024258** [comment]
> I faced this issue and the resolution is following:
> 
> The issue is this line: `from openai import OpenAI`
> 
> Replace above line with following: `from langchain.llms import OpenAI`
> 
> Hence, the prob is wrong package.

I am facing the similar problem with 

`from langchain_openai import AzureChatOpenAI, AzureOpenAI`
langchain version is 0.1.4

Can someone help me out here?
