### ISSUE TITLE
Seeing an error ModuleNotFoundError: No module named 'langchain.globals'

### ISSUE THREAD

**Issue by amrit2cisco** [langchain-ai/langchain#13064]
### System Info

LangChain version pinned to "^0.0.278" (using Poetry)
Python 3.11.5

Other modules from langchain (such as langchain.cache and langchain.chains) are imported within the same file in the application code and are able to be found. Only the `langchain.globals` module is not being recognized

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Import langchain.globals

Error happens on application startup

### Expected behavior

Expected to be able to find the module, as langchain's other module's are able to be found by the same application code

**Comment by aisu-programming** [comment]
Did what the bot said and I got the following error:

ImportError: cannot import name 'globals' from partially initialized module 'langchain' (most likely due to a circular import) (SOMAEPATH\langchain.py)

**Comment by aisu-programming** [comment]
https://github.com/langchain-ai/langchain/issues/2079#issuecomment-1487416187

Found the comment here and found that I'm not a smart man either.😅
