### ISSUE TITLE
Issue: AgentExecutor typings should accept Runnable for the agent property (to support LCEL agent)

### ISSUE THREAD

**Issue by lucas-labs** [langchain-ai/langchain#13075]
### Issue you'd like to raise.

Using LCEL as suggested on the [docs](https://python.langchain.com/docs/modules/agents/), combined with `AgentExecutor`, generates a typing error when passing the runnable agent to the `AgentExecutor` constructor. This is because `AgentExecutor` defines its `agent` property as of type `BaseSingleActionAgent | BaseMultiActionAgent`:

https://github.com/langchain-ai/langchain/blob/55aeff6777431dc24e48f018e39aa418f95a6489/libs/langchain/langchain/agents/agent.py#L728-L731

So:
```python
agent = {
    ...
} | prompt | llm | OpenAIFunctionsAgentOutputParser()

# agent would be of type Runnable[Unknown, Unknown]
# but the typing on AgentExecutor only takes a BaseSingleActionAgent 
# or a BaseMultiActionAgent as a valid agent
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
#                                      ↳  "Runnable[Unknown, Unknown]" is incompatible with "BaseSingleActionAgent"
#                                      ↳  "Runnable[Unknown, Unknown]" is incompatible with "BaseMultiActionAgent"

```

### Suggestion:

`AgentExecutor` should accept a `Runnable` for its agent property

**Comment by maozguttman** [comment]
Or you can add a new `AgentExecutor.from_runnable_and_tools` classmethod (i.e. constructor) which accepts a runnable and creates an agent object (`RunnableMultiActionAgent`/`RunnableAgent`) as `AgentExecutor.validate_runnable_agent` does.

**Comment by mintuhouse** [comment]
Can't find the methods described by @maozguttman 
And this still seem to be an issue
