### ISSUE TITLE
how to use reranker model with langchain in retrievalQA case?

### ISSUE THREAD

**Issue by valkryhx** [langchain-ai/langchain#13076]
### System Info

version 0.0.331

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

omit

### Expected behavior

I would like to use  BAAI/bge-reranker-large  model as the reranker to rerank the  intial retrieval results, 
how to use this model with langchain ?
I have seen the demo with Cohere ranker, 
but how to use ohter reranker models?
Does langchain support other reranker models except for CohereReranker?

**Comment by 631068264** [comment]
@valkryhx Do you have any idea to solve?

**Comment by zhangjiekui** [comment]
from __future__ import annotations

from typing import Dict, Optional, Sequence

from langchain.schema import Document
from langchain.pydantic_v1 import Extra, root_validator

from langchain.callbacks.manager import Callbacks
from langchain.retrievers.document_compressors.base import BaseDocumentCompressor

from sentence_transformers import CrossEncoder
from config import bge_reranker_large
# 参照文件改写 https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/document_compressors/cohere_rerank.py
class BgeRerank(BaseDocumentCompressor):
    """Document compressor that uses `BAAI/bge-reranker`."""

    model_name:str = bge_reranker_large
    """Model name to use for reranking."""
    top_n: int = 10
    """Number of documents to return."""
    model:CrossEncoder = CrossEncoder(model_name)
    """CrossEncoder instance to use for reranking."""


    def bge_rerank(self,query,docs):

        model_inputs =  [[query, doc] for doc in docs]
        scores = self.model.predict(model_inputs)
        results = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)

        return results[:self.top_n]


    class Config:
        """Configuration for this pydantic object."""

        extra = Extra.forbid
        arbitrary_types_allowed = True

    def compress_documents(
        self,
        documents: Sequence[Document],
        query: str,
        callbacks: Optional[Callbacks] = None,
    ) -> Sequence[Document]:
        """
        Compress documents using Cohere's rerank API.

        Args:
            documents: A sequence of documents to compress.
            query: The query to use for compressing the documents.
            callbacks: Callbacks to run during the compression process.

        Returns:
            A sequence of compressed documents.
        """
        if len(documents) == 0:  # to avoid empty api call
            return []
        doc_list = list(documents)
        _docs = [d.page_content for d in doc_list]
        results = self.bge_rerank(query, _docs)
        final_results = []
        for r in results:
            doc = doc_list[r[0]]
            doc.metadata["relevance_score"] = r[1]
            final_results.append(doc)
        return final_results

**Comment by plaban1981** [comment]
> ## 参照文件改写 https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/document_compressors/cohere_rerank.py
> ##code `
> 
> ```
> from __future__ import annotations
> from typing import Dict, Optional, Sequence
> from langchain.schema import Document
> from langchain.pydantic_v1 import Extra, root_validator
> 
> from langchain.callbacks.manager import Callbacks
> from langchain.retrievers.document_compressors.base import BaseDocumentCompressor
> 
> from sentence_transformers import CrossEncoder
> from config import bge_reranker_large
> 
> class BgeRerank(BaseDocumentCompressor):
>     model_name:str = 'bge_reranker_large_model_path'  
>     """Model name to use for reranking."""    
>     top_n: int = 10   
>     """Number of documents to return."""
>     model:CrossEncoder = CrossEncoder(model_name)
>     """CrossEncoder instance to use for reranking."""
> 
>     def bge_rerank(self,query,docs):
>         model_inputs =  [[query, doc] for doc in docs]
>         scores = self.model.predict(model_inputs)
>         results = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)
>         return results[:self.top_n]
> 
> 
>     class Config:
>         """Configuration for this pydantic object."""
> 
>         extra = Extra.forbid
>         arbitrary_types_allowed = True
> 
>     def compress_documents(
>         self,
>         documents: Sequence[Document],
>         query: str,
>         callbacks: Optional[Callbacks] = None,
>     ) -> Sequence[Document]:
>         """
>         Compress documents using BAAI/bge-reranker models.
> 
>         Args:
>             documents: A sequence of documents to compress.
>             query: The query to use for compressing the documents.
>             callbacks: Callbacks to run during the compression process.
> 
>         Returns:
>             A sequence of compressed documents.
>         """
>         if len(documents) == 0:  # to avoid empty api call
>             return []
>         doc_list = list(documents)
>         _docs = [d.page_content for d in doc_list]
>         results = self.bge_rerank(query, _docs)
>         final_results = []
>         for r in results:
>             doc = doc_list[r[0]]
>             doc.metadata["relevance_score"] = r[1]
>             final_results.append(doc)
>         return final_results
> ```
> 
> `

@zhangjiekui  how to resolve config  in **from config import bge_reranker_large** Please advise

**Comment by whm233** [comment]
nice

**Comment by whm233** [comment]
> from config import bge_reranker_large

这个是用来干嘛的大佬

**Comment by zhangjiekui** [comment]
就是你存在在本地的模型地址，或者是模型的官方名称（如HuggingFace），可以删除那一行，我是从我的代码文件中直接拷贝过来的，我把模型名称地址放到配置文件里了。

**Comment by whm233** [comment]
谢谢大佬



发自我的iPhone


------------------ Original ------------------
From: zhangjiekui ***@***.***&gt;
Date: Thu,Dec 14,2023 8:47 PM
To: langchain-ai/langchain ***@***.***&gt;
Cc: whm233 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [langchain-ai/langchain] how to use reranker model with langchainin retrievalQA case? (Issue #13076)





 
就是你存在在本地的模型地址，或者是模型的官方名称（如HuggingFace），可以删除那一行，我是从我的代码文件中直接拷贝过来的，我把模型名称地址放到配置文件里了。

**Comment by zhangjiekui** [comment]
> > ## 参照文件改写 https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/document_compressors/cohere_rerank.py
> > ##code `
> > ```
> > from __future__ import annotations
> > from typing import Dict, Optional, Sequence
> > from langchain.schema import Document
> > from langchain.pydantic_v1 import Extra, root_validator
> > 
> > from langchain.callbacks.manager import Callbacks
> > from langchain.retrievers.document_compressors.base import BaseDocumentCompressor
> > 
> > from sentence_transformers import CrossEncoder
> > from config import bge_reranker_large
> > 
> > class BgeRerank(BaseDocumentCompressor):
> >     model_name:str = 'bge_reranker_large_model_path'  
> >     """Model name to use for reranking."""    
> >     top_n: int = 10   
> >     """Number of documents to return."""
> >     model:CrossEncoder = CrossEncoder(model_name)
> >     """CrossEncoder instance to use for reranking."""
> > 
> >     def bge_rerank(self,query,docs):
> >         model_inputs =  [[query, doc] for doc in docs]
> >         scores = self.model.predict(model_inputs)
> >         results = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)
> >         return results[:self.top_n]
> > 
> > 
> >     class Config:
> >         """Configuration for this pydantic object."""
> > 
> >         extra = Extra.forbid
> >         arbitrary_types_allowed = True
> > 
> >     def compress_documents(
> >         self,
> >         documents: Sequence[Document],
> >         query: str,
> >         callbacks: Optional[Callbacks] = None,
> >     ) -> Sequence[Document]:
> >         """
> >         Compress documents using BAAI/bge-reranker models.
> > 
> >         Args:
> >             documents: A sequence of documents to compress.
> >             query: The query to use for compressing the documents.
> >             callbacks: Callbacks to run during the compression process.
> > 
> >         Returns:
> >             A sequence of compressed documents.
> >         """
> >         if len(documents) == 0:  # to avoid empty api call
> >             return []
> >         doc_list = list(documents)
> >         _docs = [d.page_content for d in doc_list]
> >         results = self.bge_rerank(query, _docs)
> >         final_results = []
> >         for r in results:
> >             doc = doc_list[r[0]]
> >             doc.metadata["relevance_score"] = r[1]
> >             final_results.append(doc)
> >         return final_results
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> 
> @zhangjiekui how to resolve config in **from config import bge_reranker_large** Please advise

Just the bge_reranker_large model name or local path (I put it in the config.py), be free to del that line of code

**Comment by levin8023** [comment]
is there any tools for Text Embeddings Inference rerank models server like HuggingFaceHubEmbeddings instead of local running rerank models ?

**Comment by Jerry-hyl** [comment]
So how can I use this bge rerank model in RetrievalQA?

**Comment by whm233** [comment]
> So how can I use this bge rerank model in RetrievalQA?

from langchain.retrievers.document_compressors.BgeRerank import BgeRerank
from langchain.chains import RetrievalQA
from langchain.retrievers import ContextualCompressionRetriever
compressor = BgeRerank()
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=db_retriever
)

kc = RetrievalQA.from_llm(llm=qwllm, retriever=compression_retriever, prompt=prompt)

**Comment by Jerry-hyl** [comment]
@whm233 Thanks!

**Comment by thangckt** [comment]
hi @whm233 
which version of langchain that can use this 
```
from langchain.retrievers.document_compressors.BgeRerank import BgeRerank
```
I install `langchain=0.1.13` and can not found `BgeRerank` 
Thank.

**Comment by Scottie-tech** [comment]
May I ask if the parameter model_name in the modification method you provided can accept the path of the local model? `compressor = BgeRerank(model_name='D:\bge_reranker_base')`
I am unable to load the local model using this assignment method. The code will automatically connect to the code repository of the huggingface and attempt to download the model. Finally, this error will be displayed: 
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bge_reranker_large_model_path is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by whm233** [comment]
> hi @whm233 which version of langchain that can use this
> 
> ```
> from langchain.retrievers.document_compressors.BgeRerank import BgeRerank
> ```
> 
> I install `langchain=0.1.13` and can not find `BgeRerank` Thank.

you should make BgeRerank.py flie and copy the code in it

**Comment by whm233** [comment]
> May I ask if the parameter model_name in the modification method you provided can accept the path of the local model? `compressor = BgeRerank(model_name='D:\bge_reranker_base')`
> 
> I am unable to load the local model using this assignment method. The code will automatically connect to the code repository of the huggingface and attempt to download the model. Finally, this error will be displayed:
> 
> OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bge_reranker_large_model_path is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

this is my code 
from __future__ import annotations
from typing import Dict, Optional, Sequence
from langchain.schema import Document
from langchain.pydantic_v1 import Extra, root_validator

from langchain.callbacks.manager import Callbacks
from langchain.retrievers.document_compressors.base import BaseDocumentCompressor

from sentence_transformers import CrossEncoder
#from config import bge_reranker_large

class BgeRerank(BaseDocumentCompressor):
    model_name:str = '/data/shared/Qwen/filedir/bge-reranker-base'  
    """Model name to use for reranking."""    
    top_n: int = 3   
    """Number of documents to return."""
    model:CrossEncoder = CrossEncoder(model_name)
    """CrossEncoder instance to use for reranking."""

    def bge_rerank(self,query,docs):
        model_inputs =  [[query, doc] for doc in docs]
        scores = self.model.predict(model_inputs)
        results = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)
        return results[:self.top_n]

**Comment by whm233** [comment]
> May I ask if the parameter model_name in the modification method you provided can accept the path of the local model? `compressor = BgeRerank(model_name='D:\bge_reranker_base')`
> 
> I am unable to load the local model using this assignment method. The code will automatically connect to the code repository of the huggingface and attempt to download the model. Finally, this error will be displayed:
> 
> OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bge_reranker_large_model_path is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Perhaps you should set the address of the model directly in the source code

**Comment by Scottie-tech** [comment]
> > 请问您提供的修改方法中model_name的参数是否可以接受局部模型的路径？`compressor = BgeRerank(model_name='D:\bge_reranker_base')`
> > 我无法使用此赋值方法加载本地模型。代码将自动连接到 huggingface 的代码库并尝试下载模型。最后，将显示此错误：
> > OSError：我们无法连接到“https://huggingface.co”来加载此文件，在缓存文件中找不到它，并且看起来bge_reranker_large_model_path不是包含名为 config.json 的文件的目录的路径。在“https://huggingface.co/docs/transformers/installation#offline-mode”中签出您的互联网连接或查看如何在离线模式下运行库。
> 
> 也许你应该直接在源代码中设置模型的地址

Thanks, Modify the address in the source code is the correct solution

**Comment by Alissa-fa** [comment]
> ## 参照文件改写 https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/document_compressors/cohere_rerank.py
> ##code `
> 
> ```
> from __future__ import annotations
> from typing import Dict, Optional, Sequence
> from langchain.schema import Document
> from langchain.pydantic_v1 import Extra, root_validator
> 
> from langchain.callbacks.manager import Callbacks
> from langchain.retrievers.document_compressors.base import BaseDocumentCompressor
> 
> from sentence_transformers import CrossEncoder
> # from config import bge_reranker_large
> 
> class BgeRerank(BaseDocumentCompressor):
>     model_name:str = 'bge_reranker_large_model_path'  
>     """Model name to use for reranking."""    
>     top_n: int = 10   
>     """Number of documents to return."""
>     model:CrossEncoder = CrossEncoder(model_name)
>     """CrossEncoder instance to use for reranking."""
> 
>     def bge_rerank(self,query,docs):
>         model_inputs =  [[query, doc] for doc in docs]
>         scores = self.model.predict(model_inputs)
>         results = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)
>         return results[:self.top_n]
> 
> 
>     class Config:
>         """Configuration for this pydantic object."""
> 
>         extra = Extra.forbid
>         arbitrary_types_allowed = True
> 
>     def compress_documents(
>         self,
>         documents: Sequence[Document],
>         query: str,
>         callbacks: Optional[Callbacks] = None,
>     ) -> Sequence[Document]:
>         """
>         Compress documents using BAAI/bge-reranker models.
> 
>         Args:
>             documents: A sequence of documents to compress.
>             query: The query to use for compressing the documents.
>             callbacks: Callbacks to run during the compression process.
> 
>         Returns:
>             A sequence of compressed documents.
>         """
>         if len(documents) == 0:  # to avoid empty api call
>             return []
>         doc_list = list(documents)
>         _docs = [d.page_content for d in doc_list]
>         results = self.bge_rerank(query, _docs)
>         final_results = []
>         for r in results:
>             doc = doc_list[r[0]]
>             doc.metadata["relevance_score"] = r[1]
>             final_results.append(doc)
>         return final_results
> ```
> 
> `

谢谢，我跟你有同样的想法，很有参考价值。
但是想请教下要如何理解在 BaseDocumentCompressor 里的注释说：
“    **Note** users should favor using a RunnableLambda
    instead of sub-classing from this interface.”
