### ISSUE TITLE
Summarization chain batching is not working with Replicate

### ISSUE THREAD

**Issue by shyamsantoki** [langchain-ai/langchain#13108]
### System Info

LangChain version: 0.0.300
Python version: 3.10.12

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

```py
# Prompt
prompt_text = """You are an assistant tasked with summarizing tables and text. \ 
Give a concise summary of the table or text. Table or text chunk: {element} """
prompt = PromptTemplate.from_template(prompt_text)

# Summary chain
model = Replicate(
    model="meta/llama-2-7b-chat:13c3cdee13ee059ab779f0291d29054dab00a47dad8261375654de5540165fb0",
    model_kwargs={"temperature": 0.75, "max_length": 3000, "top_p":0.25}
)
summarize_chain = {"element": lambda x: x} | prompt | model | StrOutputParser()

# Apply to text
texts = [i.text for i in text_elements]
text_summaries = summarize_chain.batch(texts, {"max_concurrency": 5})
```

Error:
```txt
ValueError: config must be a list of the same length as inputs, but got 27 configs for 5 inputs
```

With OpenAI, it is working as expected.

### Expected behavior

The summarization chain (powered by Replicate) should process each chunks batch-wise.

**Comment by bjohn22** [comment]
I am facing exactly the same issue. it works as expected with open: Open AI: 
![image](https://github.com/langchain-ai/langchain/assets/64164805/9045e81c-5584-48c9-a4c0-a5aafe65dc19)

Here is llama with Replicate:
![image](https://github.com/langchain-ai/langchain/assets/64164805/2eafb10c-f046-404a-ba88-ee7da3990da8)

**Comment by maxlenix** [comment]
i am getting another type of error on the same pie
<img width="926" alt="error_openai" src="https://github.com/langchain-ai/langchain/assets/161713239/688318ce-6c53-4260-b17a-0ed529b6face">
ce of code
