### ISSUE TITLE
Qianfan llm error calling "ERNIE-Bot-4"

### ISSUE THREAD

**Issue by mimadiule** [langchain-ai/langchain#13116]
### System Info

langchain version 0.0.332, affect all platforms
There is a mistake in the file:
qianfan\resources\llm\completion.py
this `endpoint="/chat/completions-pro`, is not correct ,it should be `endpoint="/chat/completions_pro`,"
like below:
``
"ERNIE-Bot-4": QfLLMInfo(
                endpoint="/chat/completions_pro",
                required_keys={"messages"},
                optional_keys={
                    "stream",
                    "temperature",
                    "top_p",
                    "penalty_score",
                    "user_id",
                    "system",
                },
            ),
``

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

llm = QianfanLLMEndpoint(streaming = True,temperature = 0.5)
# llm.model = "ERNIE-Bot-turbo"
llm.model = "ERNIE-Bot-4"
# llm.model = "ChatGLM2-6B-32K"
res = llm("hi")

this will report error

### Expected behavior

should work without error

**Comment by danielhjz** [comment]
> ### System Info
> langchain version 0.0.332, affect all platforms There is a mistake in the file: qianfan\resources\llm\completion.py this `endpoint="/chat/completions-pro`, is not correct ,it should be `endpoint="/chat/completions_pro`," like below: `"ERNIE-Bot-4": QfLLMInfo( endpoint="/chat/completions_pro", required_keys={"messages"}, optional_keys={ "stream", "temperature", "top_p", "penalty_score", "user_id", "system", }, ),`
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [ ]  My own modified scripts
> 
> ### Related Components
> * [x]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [ ]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> llm = QianfanLLMEndpoint(streaming = True,temperature = 0.5)
> 
> # llm.model = "ERNIE-Bot-turbo"
> llm.model = "ERNIE-Bot-4"
> 
> # llm.model = "ChatGLM2-6B-32K"
> res = llm("hi")
> 
> this will report error
> 
> ### Expected behavior
> should work without error

Hi, Thanks for using Qianfan.
Try upgrade `qianfan` and retry!
```bash
 pip install qianfan --upgrade
```

**Comment by stonekim** [comment]
Related PR：https://github.com/baidubce/bce-qianfan-sdk/pull/28
