### ISSUE TITLE
LCEL stream function doesn't use LLM cache

### ISSUE THREAD

**Issue by molntamas** [langchain-ai/langchain#13119]
### System Info

LangChain version : 0.0.327
Python version : 3.10.11
Platform : Windows 11

### Who can help?

@agola11 @hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

I was using streaming callbacks with LLMChains.
I switched now to use LangChain Expression Language (LCEL), and using the stream/astream functions.
They don't seem to save the results to the configured LLM cache and don't load the results from there.

I'm not sure if this is intentional, or a bug.
If it is intentional I'm wondering how I should use the cache.

Code to reproduce the issue:

```python
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI
from langchain.globals import set_llm_cache
from langchain.cache import InMemoryCache

set_llm_cache(InMemoryCache())

model = ChatOpenAI(cache=True)
prompt = ChatPromptTemplate.from_template(
    "tell me a joke in about 5 sentences about {topic}"
)
chain = prompt | model

for s in chain.stream({"topic": "bears"}):
    print(s.content, end="", flush=True)

print("\n\nFINISHED FIRST COMPLETION\n")

for s in chain.stream({"topic": "bears"}):
    print(s.content, end="", flush=True)
```

### Expected behavior

The second result should be the same and should be retrieved quickly from the LLM cache.

**Comment by z-sako** [comment]
hello, I also encountered this problem, have you found a solution? @molntamas ，thanks

**Comment by molntamas** [comment]
Hi @z-sako,
I didn't address it yet. I hope it gets adjusted in future langchain version.
What I'm not sure whether this behaviour, not using the cache, is intentional or not.
If it would be OK to add it in langchain LCEL, then I guess it shouldn't be too difficult to implement.
