### ISSUE TITLE
Documentation Link Broken

### ISSUE THREAD

**Issue by tkejr** [langchain-ai/langchain#1312]
<img width="1440" alt="Screenshot 2023-02-26 at 8 17 04 PM" src="https://user-images.githubusercontent.com/52064142/221456499-8f60c89d-0e72-45e9-8a20-1483b2a0b62b.png">
When I click in awesome paper it redirects me here https://memprompt.com/ which doesn't open !

**Comment by hwchase17** [comment]
link works for me.... https://memprompt.com

does it still not work for you?
