### ISSUE TITLE
httpx openai support

### ISSUE THREAD

**Issue by bennybhr** [langchain-ai/langchain#13122]
### Feature request

please  support  httpx_client  in openai version 1.1.1
just one more parameter
if there is another solution  i would like to get it 
thanks 

### Motivation

cant work without ssl cert

### Your contribution

in AzureChatOpenAI  and AzureOpenAI class 
add  parameter openai_http_client
in method validate_environment
please add  at line 134 the next code
values["http_client"] = get_from_dict_or_env(
            values, "openai_http_client", "OPENAI_HTTP_CLIENT", default=""
        )

**Comment by baskaryan** [comment]
AzureChatOpenAI and ChatOpenAI should support directly passing in `http_client` as of 0.0.332! Working on support for AzureOpenAI and OpenAI

**Comment by bennybhr** [comment]
hi 
i am workin with  version  338  and it still not working
in azure_openai.py  in the code there is a line  195 that transfer the http_client  to  openai package 
but the function AzureChatOpenAI   d'ont have the field  http_cleint as a parameter 
 
i fix  it  in my station  after  line   181  i entered this 3 lines 
            import httpx
            cert = "client.pem"
            values["http_client"] = httpx.Client(verify=cert)

and its working  
you have all the  code just  get the parameter and pass it to values["http_client"]
