### ISSUE TITLE
Custom implementation for query checker tool

### ISSUE THREAD

**Issue by sud962468** [langchain-ai/langchain#13125]
### Feature request

We are using langchain create_sql_agent to build a chat engine with database.

I want to write custom implementation for tool : query_sql_checker_tool
In this custom logic, we want to modify the sql query before execution.

Example:
original query : select * from transaction where type = IPC
modified query : select * from (select * from transaction where account_id = 123) where type = IPC

Can you please provide me way forward to achieve this ?
 

### Motivation

To protect some data from client, need this functionality

### Your contribution

I'm not familiar with the internal code, but I can help if guided.

**Comment by sud962468** [comment]
@dosubot I am getting error with the above code. Please find below stack trace:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/validators.py", line 751, in find_validators
    if issubclass(type_, val_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sudhanshuagarwal/Phoenix/bitbucket/sql-agent/final.py", line 103, in <module>
    class CustomQueryChecker(BaseSQLDatabaseTool, BaseTool):
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/fields.py", line 506, in infer
    return cls(
           ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/fields.py", line 436, in __init__
    self.prepare()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/fields.py", line 557, in prepare
    self.populate_validators()
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/fields.py", line 831, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/v1/validators.py", line 760, in find_validators
    raise RuntimeError(f'error checking inheritance of {type_!r} (type: {display_as_type(type_)})')
RuntimeError: error checking inheritance of <langchain.utilities.sql_database.SQLDatabase object at 0x14d8f3b10> (type: SQLDatabase)


 Can you please help me in resolving this ?

**Comment by sud962468** [comment]
Above error got resolved. Now getting bellow error:

1 validation error for CustomQuerySQLCheckerTool
db
  field required (type=value_error.missing)
  
Can you please help me to resolve this ?

**Comment by sud962468** [comment]
@dosu-bot
Above error got resolved. Now getting bellow error:

1 validation error for CustomQuerySQLCheckerTool
db
field required (type=value_error.missing)

Can you please help me to resolve this ?

**Comment by sud962468** [comment]
@dosu-bot
query_checker_tool = QuerySQLCheckerTool(db=db, llm=llm)
Can you please write class QuerySQLCheckerTool, accepting db and llm as parameter ?

**Comment by sud962468** [comment]
@dosu-bot

I have added the CustomQuerySQLCheckerTool in create_sql_agent. please find below code:
agent_executor = create_sql_agent(llm=llm,
                                toolkit=toolkit,
                                agent_type=AgentType.OPENAI_FUNCTIONS,
                                query_checker_tool=CustomQuerySQLCheckerTool(db=lm_database, llm=llm)
                                )
                                
Issue is that this Custom tool is not getting called. Can you please help ?

**Comment by baonhat1802** [comment]
@sud962468 Did you find a solution ? I am facing the same error... When I updated langchain to the newest version, all of my custom tools are dead now
