### ISSUE TITLE
How do I use multiple GPU when using a model with hugging face?

### ISSUE THREAD

**Issue by girlsending0** [langchain-ai/langchain#13128]
### Issue you'd like to raise.

Hi. 
I am currently using the model of the hugging face.
The code I use is below.

`llm = HuggingFacePipeline.from_model_id(model_id="beomi/llama-2-ko-7b", task="text-generation", model_kwargs={"max_length": 2000}, device=0)`

Currently I am only using device=0, but I would like to load the model using multiple devices (device=0,1,2,3).
But I couldn't find a way to handle multiple devices for HuggingFacePipeline.from_model_id.

If you know anything about this, I hope you can help.

**Comment by girlsending0** [comment]
File "/home/hanjh/bin/miniconda3/envs/langchain/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/home/hanjh/HJ/demo_llama.py", line 87, in <module>
    llm = HuggingFacePipeline.from_model_id(model_id="beomi/llama-2-ko-7b", task="text-generation", device_map='auto', model_kwargs={"max_length": 2000})
  File "/home/hanjh/bin/miniconda3/envs/langchain/lib/python3.9/site-packages/langchain/llms/huggingface_pipeline.py", line 159, in from_model_id
    return cls(
  File "/home/hanjh/bin/miniconda3/envs/langchain/lib/python3.9/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/hanjh/bin/miniconda3/envs/langchain/lib/python3.9/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for HuggingFacePipeline
device_map
  extra fields not permitted (type=value_error.extra)




Now this error appears. Is there any other way?

**Comment by jediyoda36** [comment]
I got similar question, when I set `device_map="auto"`, the model just inference on CPU not my GPUs. 
```python
model = HuggingFacePipeline.from_model_id(model_id=llm_model_dict["chinese-alpaca-13B"],
            task="text-generation",
            device_map="auto",
            model_kwargs={
                          "torch_dtype" : load_type,
                          "low_cpu_mem_usage" : True,
                          "temperature": 0.2,
                          "max_length": 1000,
                          "repetition_penalty":1.1}
            )
```

**Comment by importTthis** [comment]
> 我遇到了类似的问题，当我设置时`device_map="auto"`，模型只是在 CPU 上进行推理，而不是在我的 GPU 上进行推理。
> 
> ```python
> model = HuggingFacePipeline.from_model_id(model_id=llm_model_dict["chinese-alpaca-13B"],
>             task="text-generation",
>             device_map="auto",
>             model_kwargs={
>                           "torch_dtype" : load_type,
>                           "low_cpu_mem_usage" : True,
>                           "temperature": 0.2,
>                           "max_length": 1000,
>                           "repetition_penalty":1.1}
>             )
> ```

您有解决该问题么，我有和你一样的疑问.

**Comment by jediyoda36** [comment]
> > 我遇到了类似的问题，当我设置时`device_map="auto"`，模型只是在 CPU 上进行推理，而不是在我的 GPU 上进行推理。
> 
> > 
> 
> > ```python
> 
> > model = HuggingFacePipeline.from_model_id(model_id=llm_model_dict["chinese-alpaca-13B"],
> 
> >             task="text-generation",
> 
> >             device_map="auto",
> 
> >             model_kwargs={
> 
> >                           "torch_dtype" : load_type,
> 
> >                           "low_cpu_mem_usage" : True,
> 
> >                           "temperature": 0.2,
> 
> >                           "max_length": 1000,
> 
> >                           "repetition_penalty":1.1}
> 
> >             )
> 
> > ```
> 
> 
> 
> 您有解决该问题么，我有和你一样的疑问.
> 
> 

解决了，分别load模型和tokenizer，再自己组装成pipe，load模型的时候把device map这个参数传进去就行

`HuggingFacePipeline.from_model_id`这个接口有bug，不过你看这个接口的源码做的事情其实就是我上面说的，只不过他们套了一大堆逻辑判断，估计有地方的逻辑出bug了

**Comment by importTthis** [comment]
soga. 我原来大致看了一下接口的，套来套去，谢谢

**Comment by WenTingTseng** [comment]
解决了，分别load模型和tokenizer，再自己组装成pipe，load模型的时候把device map这个参数传进去就行

請問有這段程式碼可提供嗎
感謝

**Comment by jediyoda36** [comment]
> `解决了，分别load模型和tokenizer，再自己组装成pipe，load模型的时候把device map这个参数传进去就行`
> 
> 請問有這段程式碼可提供嗎 感謝
```python
class LLMModelLoader:
    def __init__(self, model_id, embedding_id):
        self.model_id = model_id
        self.embedding_id = embedding_id

    def load(self):
        model_id = self.model_id
        tokenizer = AutoTokenizer.from_pretrained(
            model_id,
            trust_remote_code=True,
            dtype="auto",
        )
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype="auto",
            trust_remote_code=True,
            low_cpu_mem_usage=True,
            temperature=0.5,
            max_length=4000,
            device_map="auto",
        )
        model_pipeline = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=4000,
        )
        hf = HuggingFacePipeline(pipeline=model_pipeline)
        embedding = HuggingFaceEmbeddings(model_name=self.embedding_id)
        return hf, embedding
```
@WenTingTseng 大概就是这样，自己手动组装成pipline，本质上和`from_model_id `这个API做的是一件事
（直接贴了代码里的一部分，embedding那部分忽略就好

**Comment by SteamerLee** [comment]
There is another way that works in my program for utilizing all GPUs. You may set 'device=None', 'device_map=None', and 'model_kwargs=dict(device_map='balanced')'.

Example:
model = HuggingFacePipeline.from_model_id(
        model_id='xxx',
        ......,
        device=None,
        device_map=None,
        model_kwargs=dict(device_map='balanced'),
)

** It works as well when 'balanced' is replaced by 'auto'.

**Comment by jediyoda36** [comment]
At the current time point (2024), it might be a better choice to use vllm for multi-card inference, vllm can be packaged as an OpenAI API service.
