### ISSUE TITLE
DOC: Install openai with langchain[openai]

### ISSUE THREAD

**Issue by cbornet** [langchain-ai/langchain#13134]
### Issue with current documentation:

The documentation recommends to install openai with `pip install openai`.
If you do it currently (langchain 0.0.332) then an incompatible openai version is installed (1.1.2).
It's better to install it using `pip install langchain[openai]` as that will pick a version compatible with langchain.
So I propose to replace it in the docs.
WDYT ?

**Comment by baskaryan** [comment]
What are the incompatibilities you're seeing with openai 1.1.2?

**Comment by cbornet** [comment]
For instance https://github.com/langchain-ai/langchain/issues/13114

**Comment by cbornet** [comment]
Also https://github.com/langchain-ai/langchain/issues/13027

**Comment by cbornet** [comment]
OpenAI 1.0 has a bunch of breaking changes: https://github.com/openai/openai-python/discussions/742

**Comment by baskaryan** [comment]
ChatOpenAI, AzureChatOpenAI, OpenAIEmbeddings and AzureChatOpenAIEmbeddings should be compatible as of 0.0.332. 

OpenAI and AzureOpenAI should be compatible in master as of #13099. So I think all OpenAI integrations should work by 0.0.334, which will be released soon!

**Comment by cbornet** [comment]
Cool! But it seems to me that it is still a best practice to let the langchain package specify which openai versions it is compatible with.
Actually any optional dependency should be imported via an "extra" package.

**Comment by cbornet** [comment]
Otherwise it could break at the next openai major release.

**Comment by cbornet** [comment]
One of the tradeoffs is that `langchain[openai]` requires  Python 3.9+ (because it installs tiktoken) whereas langchain and openai only require Python 3.8.1+.

**Comment by cbornet** [comment]
Since the recommended way to install OpenAI in docs is now to use the langchain-openai package, this issue has less importance.
It would however be a convenient way to install the package if https://github.com/langchain-ai/langchain/pull/15975 gets merged.
