### ISSUE TITLE
How to retrieve custom number of docs from parent retriver document , I have 100 docs and i don't want the reteiver to just retrieve only 4 docs

### ISSUE THREAD

**Issue by dheekshayogananda** [langchain-ai/langchain#13145]
### Issue you'd like to raise.

I have 100 docs , from which i am trying to retrieve top 10 docs which are most relevant to my query using parent document retriever. How can this be achieved.

**Comment by dheekshayogananda** [comment]
@dosu-bot
can we choose how many docs are retrieved from the parent document retriever.?

**Comment by dheekshayogananda** [comment]
@dosu-bot
I want to limit the number of relevant docs retrieved by parent document retriever. Is there something to do with get_relavant_documents function

**Comment by umair313** [comment]
@dheekshayogananda if you getting docs after similarity search then you must be getting score with it you can filter these to get the top 10

**Comment by samiulhq** [comment]
Hi,
I am having issues with get_relevant_documents function. It appears that the number of retrieved parent documents is set to 4 and I was not able to find any option to provide a parameter to retrieve more documents.

**Comment by samiulhq** [comment]
Hi, @dheekshayogananda  I have identified a potential solution to this set the search_kwargs={"k":<number of documents>} in the retriever object.

Example 
retriever= ParentDocumentRetriever(
    vectorstore=langchain_chroma,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
 )
retriever.search_kwargs={"k":10}

**Comment by sukidesuka** [comment]
retriever = ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=store,
    child_splitter=child_splitter,
    search_kwargs={"k": 10}
)
