### ISSUE TITLE
getiing an error with openai v1

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#13162]
### System Info

Getting the below error when try to use load_qa_chain

openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

run load_qa_chain

### Expected behavior

it should not error

**Comment by kevcmk** [comment]
This dosu-bot is a complete nuisance

**Comment by Espacio-root** [comment]
`openai migrate <path-to-langchain>/document-loaders/parsers/audio.py` replace `<path-to-langchain>` with the actual path to langchain module.
and changing line 66 in audio.py file to: `transcript = client.audio.transcriptions.create(model="whisper-1", file=file_obj)`
should fix the issue.

**Comment by haomengqi00709** [comment]
I'm not using langchain, only on openai.File.create, I got the same error, anyone can help?

**Comment by super-harsh** [comment]
OpenAI has made some changes to the helper methods and code structs. Updating the package(`pip install --upgrade openai`)  and method calls fixed it for me. :) 

Hope this helps you.
