### ISSUE TITLE
Support OpenAI seed for deterministic outputs

### ISSUE THREAD

**Issue by chris-boson** [langchain-ai/langchain#13177]
### Feature request

Support OpenAI seed and fingerprint parameters to get more consistent outputs for the same inputs and model version.

https://cookbook.openai.com/examples/deterministic_outputs_with_the_seed_parameter#seed
https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed

### Motivation

Running unit tests that are dependent on LLM responses often leads to random flakiness.

### Your contribution

PR

**Comment by kennethleungty** [comment]
I am doing this to pass seed

``` 
ChatOpenAI(model=model_name, 
temperature=0, 
model_kwargs={"seed": 42})
```

**Comment by chrispy-snps** [comment]
We would also like to see the `seed` parameter supported.

**Comment by rajib76** [comment]
> I am doing this to pass seed
> 
> ```
> ChatOpenAI(model=model_name, 
> temperature=0, 
> model_kwargs={"seed": 42})
> ```

How are you getting back the system fingerprint. I am using load qa chain

**Comment by dave-espinosa** [comment]
> I am doing this to pass seed
> 
> ```
> ChatOpenAI(model=model_name, 
> temperature=0, 
> model_kwargs={"seed": 42})
> ```

As far as openai version 1.40.1 is concerned (August 2024), the updated use of `seed` would be:

```python
ChatOpenAI(model=model_name, 
temperature=0, 
seed=42)
```

**Comment by Junjie-Chu** [comment]
```
structured_agent_llm = agent_llm.with_structured_output(
    schema=ScoringPointJudgement,
    method="json_schema",
    tools=tools,
    strict=True,
    )
```
Cannot work together with ```.with_structured_output()```, I use gpt4o.
