### ISSUE TITLE
Setting a custom http_client fails with pydantic ConfigError

### ISSUE THREAD

**Issue by daichi-m** [langchain-ai/langchain#13185]
### System Info

<pre>
platform = macOS-10.16-x86_64-i386-64bit
version = 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
langchain.version = 0.0.332
pydantic.version = 1.10.13
openai.version = 1.2.0
</pre>

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm trying to initialize an instance of AzureChatOpenAI with a custom http_client. Following is the code I'm using - 

<pre>
from langchain.chat_models import AzureChatOpenAI
from langchain.schema import HumanMessage, SystemMessage
import httpx

messages = [
    SystemMessage(content="You are a helpful assistant that translates English to Spanish"),
    HumanMessage(content="Good morning Vietnam!")
]
client = httpx.Client()

chat = AzureChatOpenAI(
    openai_api_key="my-secret-key",
    openai_api_version="2023-07-01-preview",
    model="gpt-4",
    deployment_name="my-deployment-name",
    azure_endpoint="https://my-instance.openai.azure.com",
    http_client=client
)
# AzureChatOpenAI.update_forward_refs()
chat(messages)
</pre>

This fails with the following pydantic config error:

<pre>
Traceback (most recent call last):
  File "azure-custom.py", line 24, in <module>
    chat = AzureChatOpenAI(
  File "langchain-env/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 860, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "http_client" not yet prepared so type is still a ForwardRef, you might need to call AzureChatOpenAI.update_forward_refs().
</pre>

### Expected behavior

As per the [ChatOpenAI API Doc](https://api.python.langchain.com/en/latest/chat_models/langchain.chat_models.openai.ChatOpenAI.html), `http_client` seems to be a valid parameter to set in order to customize the httpx client in the background. But I'm unable to do that customization. 
Adding `AzureChatOpenAI.update_forward_refs()` also does not solve this issue - the code raises the error even before hitting that line.

**Comment by daichi-m** [comment]
The same error occurs if I use ChatOpenAI class as well (which has the http_client field defined in it)

<pre>
chat = ChatOpenAI(
    openai_api_key="my-secret-key",
    model="gpt-4",
    http_client=client
)
</pre>

Similar error stacktrace is seen again:

<pre>
Traceback (most recent call last):
  File "/Users/s0m01up/mlp/genai/langchain/expt/azure-custom.py", line 13, in <module>
    chat = ChatOpenAI(
  File "/Users/s0m01up/mlp/genai/langchain/expt/langchain-env/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 860, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "http_client" not yet prepared so type is still a ForwardRef, you might need to call ChatOpenAI.update_forward_refs().
</pre>

**Comment by baskaryan** [comment]
Hi @daichi-m, I believe  #13154 fixed this. Should work as of 0.0.334, let me know if you're still seeing issues!

**Comment by daichi-m** [comment]
@baskaryan Yes, the later versions of langchain do not suffer from this issue. We can close this issue
