### ISSUE TITLE
The Agent is not using Custom Tools.

### ISSUE THREAD

**Issue by baonhat1802** [langchain-ai/langchain#13194]
### System Info

I just updated langchain to newest version and my Agent is not working anymore. 

Tool structure : 

 ```
class Data_Retriever(BaseModel):
    db : Any
   
    class Config:
        extra = Extra.forbid

    def run(self,request) -> str:
        data = self.db.get(request)
        return data
```

When Agent uses the above tool, it will always stop at "Action Input" step : 

```
> Entering new AgentExecutor chain...

AI: Thought: Do I need to use a tool? Yes
Action: Data_Retriever
Action Input: DATA 

> Finished chain.
``` 

Does anyone know how to fix this ? I'm using langchain==0.0.332

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```from langchain.tools import BaseTool, StructuredTool, Tool, tool
from langchain.agents import AgentType, initialize_agent,load_tools

tools = [
        Tool(
        name="Music Search",
        func=lambda x: "'All I Want For Christmas Is You' by Mariah Carey.", # Mock Function
        description="A Music search engine. Use this more than the normal search if the question is about Music, like 'who is the singer of yesterday?' or 'what is the most popular song in 2022?'",
        ),
        ]

agent = initialize_agent(
            agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION, 
            tools=tools, 
            llm=llm, 
            verbose=True)

agent.run(input = "Random song")
```
### Expected behavior

The output should be All I Want For Christmas Is You' by Mariah Carey.

My agent stopped once it hit the action input step.

> Entering new AgentExecutor chain...
AI: Thought: Do I need to use a tool? Yes
Action: Music Search
Action Input: "Random song"

> Finished chain.

**Comment by baonhat1802** [comment]
@dosu-bot I didn't face any error when the Agent stopped at Action step, it just finished the chain and did not use the tool

**Comment by baonhat1802** [comment]
@dosu-bot even this tool is not working 
```
class HelloWorldTool(BaseTool):
    name = "send_message_tool"
    description = (
        """useful for when you need to send a message to a human."""
    )

    def _run(self, query: str) -> str:
        """Use the tool."""

        # My custom validation logic would go here.

        return f"Sent {query}"

    async def _arun(self, query: str) -> str:
        """Use the tool asynchronously."""

        # My custom validation logic would go here.

        return f"Sent {query}"
```
I only get this 
```> Entering new AgentExecutor chain...
AI: Thought: Do I need to use a tool? Yes
Action: send_message_tool
Action Input: {"message": "Hello"}


> Finished chain.```

**Comment by baonhat1802** [comment]
@dosu-bot 
Can you take a look at this tool ? Did I do anything wrong ? 
```
"""Get image that is related to the question."""
class Image_Retriever(BaseModel):
    image_db : Any
   
    class Config:
        extra = Extra.forbid

    def run(self,question) -> str:
        image = self.image_db.search_image(question)
        s3 = image[0]
        link = image[1]
        page = image[2]
        caption = image[3]
        citation = image[4]
        filename = image[5]

        output = output_format(s3=s3,link=link,page=page,caption=caption,citation=citation,filename=filename)
      
        return output
```

**Comment by namedgraph** [comment]
@baonhat1802 have you solved this?

I'm starting to think this framework is just an over-engineered joke :/

**Comment by baonhat1802** [comment]
@namedgraph I have given up and used langchain==0.0.264 instead (It worked for me) 
Although when using this version, I could not use AzureOpenAI (Langchain 0.0.264 has the class but DOES NOT allow me to connect to)

Hopefully this can solve your problems...

**Comment by ManojKumarTiwari** [comment]
Did we make any progress in this regards?? Cause I'm also facing the same issue

**Comment by baskaryan** [comment]
Hi all! @baonhat1802 what model were you using? not able to reproduce using the latest version of langchain

![Screenshot 2024-02-05 at 11 19 13 AM](https://github.com/langchain-ai/langchain/assets/22008038/bcfa84d0-cdd0-4599-bb4f-62b8bc9c16bb)

**Comment by lastrei** [comment]
same issue ，event on GPT-4o
![image](https://github.com/langchain-ai/langchain/assets/32331131/433b2640-8084-440c-8a14-a3641dbb6a2f)

**Comment by emmyxth** [comment]
Has anyone followed up on this? Did we find out why this is happening?

**Comment by emmyxth** [comment]
@wcisco17 do you know why your solution works and if this problem is rooted in Langchain or GPT4o? Such that if I used Claude, for example, would this problem still persist without your solution?

**Comment by wcisco17** [comment]
> @wcisco17 do you know why your solution works and if this problem is rooted in Langchain or GPT4o? Such that if I used Claude, for example, would this problem still persist without your solution?

Switching LLM's might not be the best solution, GPT-4o and Claude by comparison, according to the latest benchmark are not too far from each other in terms of reasoning and basic use, might just be an architecture prob. I would just make sure you explicitly define your agents for one use case (example delegation), if at any point a specific one goes off the rails, break it down further. Also try to employ certain strategies to mitigate this such as [Chain-of-Verification](https://arxiv.org/abs/2309.11495), chaining your prompts or [Supervisions](https://langchain-ai.github.io/langgraph/tutorials/multi_agent/agent_supervisor/). 

By the way, it took me way too long to realize that the problem wasn't with the LLM itself but with the agent architecture I was using.
