### ISSUE TITLE
MlflowAIGatewayEmbeddings : Default Batch size incompatible with Azure OpenAI text-embedding-ada-002

### ISSUE THREAD

**Issue by coltonpeltier-db** [langchain-ai/langchain#13197]
### System Info

The text-embedding-ada-002 OpenAI embedding model on Azure OpenAI has a maximum batch size of 16. MlflowAIGatewayEmbeddings has a hard-coded batch size of 20 which results in it being unusable with Azure OpenAI's text-embedding-ada-002.

The best fix would be to allow a configurable batchsize as an argument to MlflowAIGatewayEmbeddings,

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a gateway route to the text-embedding-ada-002 on azure openai
```
ROUTE_NAME = "azure-ada-002"

# Try to delete the route if it already exists
try:
    delete_route(ROUTE_NAME)
    print("Route deleted")
except:
    print("Route does not exist, creating..")

create_route(
    name=ROUTE_NAME,
    route_type="llm/v1/embeddings",
    model = {
        "name" : "text-embedding-ada-002",
        "provider" : "openai",
        "openai_config" : {
            "openai_api_type" : azure_openai_type,
            "openai_api_key": azure_openai_key,
            "openai_deployment_name": "ada-embed-v1",
            "openai_api_base": azure_openai_base,
            "openai_api_version": "2023-05-15"
        }
    }
)
```
2.  Initialize the `MlflowAIGatewayEmbeddings` and try to embed more than 16 documents
```
from langchain.embeddings import MlflowAIGatewayEmbeddings
import pandas as pd

azure_ada = MlflowAIGatewayEmbeddings(route="azure-ada-002")

test_strings = [
    "aaaa" for i in range(20)
]
azure_ada.embed_documents(test_strings)
```
3. Observe the error
```
HTTPError: 400 Client Error: Bad Request for url: https://ohio.cloud.databricks.com/gateway/azure-ada-002/invocations. Response text: {
  "error": {
    "message": "Too many inputs. The max number of inputs is 16.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

### Expected behavior

I should be able to use the `MlflowAIGatewayEmbeddings` class with Azure OpenAI.

**Comment by coltonpeltier-db** [comment]
I could be wrong, but those replies don't seem relevant. The issue seems to be the hardcoded 20 on this line seems to be the problem:
https://github.com/langchain-ai/langchain/blob/362a446999944f9764813fbf0c27a5d2682f4531/libs/langchain/langchain/embeddings/mlflow_gateway.py#L60C35-L60C35

**Comment by coltonpeltier-db** [comment]
Yep, issue still exists right [here](https://github.com/langchain-ai/langchain/blob/v0.1.6/libs/community/langchain_community/embeddings/mlflow_gateway.py#L66) where the batch size is 20.

[Here in the documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings) for azure you can see the max supported batch size is 16.

**Comment by NiklasLue** [comment]
They updated the batch size to 2048, even though the documentation you linked is not showing this yet.
Hope this helps.

**Comment by Taoudi** [comment]
> They updated the batch size to 2048, even though the documentation you linked is not showing this yet. Hope this helps.

Is there anyway to increase it?

**Comment by vlasvlasvlas** [comment]
> They updated the batch size to 2048, even though the documentation you linked is not showing this yet. Hope this helps.

is this real now it jumpts from 16 to up to 2048? so dunno its ok to use maybe like 1024?
