### ISSUE TITLE
Warning: model not found. Using cl100k_base encoding. with  Azure Openai and  load_summarize_chain when I am trying to implement map_reduce

### ISSUE THREAD

**Issue by GonzaloMoreno** [langchain-ai/langchain#13224]
### System Info

Hi:  I have tried several strategies to implement  map reduce summarization using Azure OpenAi and Langchain . My model is "gpt-35-turbo-16k".

I have tried several experiments but always get to the same warning: 

from langchain.schema.document import Document
from langchain.chains.mapreduce import MapReduceChain
from langchain.text_splitter import CharacterTextSplitter
from langchain.document_loaders import TextLoader
llm_summary = AzureChatOpenAI(
            openai_api_base= azure_api_base,
            openai_api_version=azure_openai_api_version,
            deployment_name=azure_deployment_name,
            openai_api_key=azure_openai_api_key,
            openai_api_type= azure_api_type,
            model_name=azure_model_name,
            temperature=azure_model_temperature
            
    )

text="""The ReduceDocumentsChain handles taking the document mapping results and reducing them into a single output.\
        It wraps a generic CombineDocumentsChain (like StuffDocumentsChain) but adds the ability to collapse documents before passing it 
        to the CombineDocumentsChain if their cumulative size exceeds token_max. In this example, we can actually re-use our chain for combining
        our docs to also collapse our docs."""
        
text1=""" You can continue with your English studies and never use Inversion in sentences. That’s perfectly okay. However, if you are preparing for a Cambridge or IELTS exam or other exams or situations where you need to demonstrate an extensive use of English, you will be expected to know about Inversion.

Let’s start with why and when. After all, if you don’t know why we use Inversion, you won’t know when to use it.

WHY & WHEN do we use INVERSION?
Inversion is mainly used for EMPHASIS. The expressions used (never, rarely, no sooner, only then, etc.) have much more impact when used at the beginning of a sentence than the more common pronoun subject, especially as most of  them are negative.
Negatives are more dramatic. Consider negative contractions: don’t, won’t, can’t, haven’t, etc. They usually have strong stress in English whilst positive contractions: I’m, he’ll, she’s, we’ve, I’d, etc. usually have weak stress. 
"""

doc= [Document(page_content=text1)]

chain = load_summarize_chain(llm_summary, chain_type="map_reduce") #chain_type="map_reduce"

chain.run(doc)`

and Strategy 2 with text_splitter: 

`from langchain import PromptTemplate
from langchain.chains.summarize import load_summarize_chain
from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=5000, chunk_overlap=50)
chunks = text_splitter.create_documents([text1])

chain = load_summarize_chain(
    llm_summary,
    chain_type='map_reduce',
    verbose=False
)
summary = chain.run(chunks)
summary

I always get the same output:

<img width="1473" alt="image" src="https://github.com/langchain-ai/langchain/assets/7675634/fc871a72-4f5f-43ff-9725-52a718ebaeac">

I have some questions:

1) How to fix this warning?
2) Can I trust in the output when the model is not found? 

### Who can help?

@agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

run this chunks of code in any notebook

### Expected behavior

I want to fix this warning helping to langchain to find the model.

**Comment by GonzaloMoreno** [comment]
@dosu-bot I have verified the deployment name and the api version and  they are the right ones. The problem it seems to be with load_summarize_chain. It works fine when the method is "stuff", but it fails when it is "map_reduce"

**Comment by glejdis** [comment]
@GonzaloMoreno did you find a solution?

**Comment by nyck33** [comment]
+1 I get similar errors https://github.com/langchain-ai/langchain/issues/17409#issue-2130090661

**Comment by auserwn** [comment]
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.
Warning: model not found. Using cl100k_base encoding.


how to reslove the problem?

**Comment by amzfc** [comment]
# 调试过程
	openai.py 697行 self.embed_documents([text])[0]
	openai.py 668行  self._get_len_safe_embeddings(texts, engine=engine)
	openai.py 459行，根据模型名选择 编码，（不同的模型使用不同的编码）

#结论
1. OpenAIEmbeddings 初始化时，如果不指定 model 参数，则会默认使用 cl100k_base 编码
2. 另外需要注意，openAI模型使用的三种编码：gpt2、p50k_base和cl100k_base，当你不是openAI模型，而是其他模型，比如从huggface上下载的模型，它们有自己的编码和语料库，（tokenizer.json，tokenizer_config.json，vocab.txt），如果使用cl100k_base 编码，那么向量化后的结果是不对的。
#测试

def tiktoken_token(text):
    import tiktoken
    enc = tiktoken.get_encoding("cl100k_base")
    enc_output =  enc.encode(text)
    return enc_output

def huggface_download_token(text)
   from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(
                pretrained_model_name_or_path="your download file path"
            )
    tokenized = tokenizer.encode(text, add_special_tokens=False)
    returrn tokenized 

两个函数会得到不同的结果
