### ISSUE TITLE
Issue: <openai APIConnectionError>

### ISSUE THREAD

**Issue by zhangleinice** [langchain-ai/langchain#13247]
### Issue you'd like to raise.

```
import uvicorn
import os

from typing import AsyncIterable, Awaitable
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.responses import FileResponse, StreamingResponse
from langchain.callbacks import AsyncIteratorCallbackHandler
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, ChatMessage
import asyncio

async def wait_done(fn, event):
    try:
        await fn
    except Exception as e:
        print('error', e)
        event.set()
    finally:
        event.set()

async def call_openai(question):
    callback = AsyncIteratorCallbackHandler()
    model = ChatOpenAI(
        openai_api_key= os.environ["OPENAI_API_KEY"],
        streaming=True, 
        callbacks=[callback]
    )

    print('question', question)
    coroutine = wait_done(model.agenerate(messages=[[HumanMessage(content=question)]]), callback.done)
    task = asyncio.create_task(coroutine)
    print('task', task)
    print('coroutine', callback.aiter())

    async for token in callback.aiter():
        yield f"{token}"

    await task

app = FastAPI()

@app.get("/")
async def homepage():
    return FileResponse('static/index.html')

@app.post("/ask")
def ask(body: dict):
    print('body', body)
    # return call_openai(body['question'])
    return StreamingResponse(call_openai(body['question']), media_type="text/event-stream")

if __name__ == "__main__":
   uvicorn.run(host="127.0.0.1", port=8888, app=app)
```
   
   
   run it:
   
(venv) (base) zhanglei@zhangleideMacBook-Pro chatbot % python server.py                                                                                                
INFO:     Started server process [46402]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
INFO:     127.0.0.1:53273 - "GET / HTTP/1.1" 200 OK
body {'question': '你好'}
INFO:     127.0.0.1:53273 - "POST /ask HTTP/1.1" 200 OK
question 你好
question 你好
task <Task pending name='Task-6' coro=<wait_done() running at /Users/zhanglei/Desktop/github/chatbot/server.py:21>>
coroutine <async_generator object AsyncIteratorCallbackHandler.aiter at 0x117158e40>
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.

**Comment by zhangleinice** [comment]
openai.proxy = {
            "http": "http://127.0.0.1:7890",
            "https": "http://127.0.0.1:7890"
        }
        
 After I added the proxy, it worked

**Comment by balala8** [comment]
it work for me,ubuntu 22.04
```shell
pip install --upgrade certifi
```
