### ISSUE TITLE
AWS LangChain using bedrock: Setting Relevance Score Function

### ISSUE THREAD

**Issue by mansourshams** [langchain-ai/langchain#13273]
### System Info

Thank you for your great help. I have issue with setting the score function (I have AWS LangChain using bedrock). What I have is:

from langchain.vectorstores import FAISS
loader = CSVLoader("./rag_data/a.csv") 
documents_aws = loader.load() 
docs = CharacterTextSplitter(chunk_size=2000, chunk_overlap=400, separator=",").split_documents(documents_aws)

def custom_score(i):
    #return 1 - 1 / (1 + np.exp(i))
    return 1

vectorstore_faiss_aws = FAISS.from_documents(documents=docs,embedding = br_embeddings)
vectorstore_faiss_aws.relevance_score_function=custom_score

This made no difference in the scores (did not give any errors either as I am getting large negative numbers and the vectorstore_faiss_aws.similarity_search_with_relevance_scores is indifferent to the score_threshold value)

Then I tried:
vectorstore_faiss_aws = FAISS(relevance_score_fn=custom_score).from_documents(documents=docs,embedding = br_embeddings)

and it gave the following error:
 FAISS.__init__() missing 4 required positional arguments: 'embedding_function', 'index', 'docstore', and 'index_to_docstore_id'

Your advice is highly appreciated

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The code is included:

from langchain.vectorstores import FAISS
loader = CSVLoader("./rag_data/a.csv") 
documents_aws = loader.load() 
docs = CharacterTextSplitter(chunk_size=2000, chunk_overlap=400, separator=",").split_documents(documents_aws)

def custom_score(i):
    #return 1 - 1 / (1 + np.exp(i))
    return 1

vectorstore_faiss_aws = FAISS.from_documents(documents=docs,embedding = br_embeddings)
vectorstore_faiss_aws.relevance_score_function=custom_score

### Expected behavior

The score to be in the range of 0 and 1 and the vectorstore_faiss_aws.similarity_search_with_relevance_scores to react to score_threshold

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your help. This was helpful. A Follow-up question. It seems that the metric used here is L2. How can I change it to cosine similarity?

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your great help. In your answer you used DistanceStrategy.MAX_INNER_PRODUCT . What is the difference of this and DistanceStrategy.DOT_PRODUCT?

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your answer. I have a follow-up question. Once I set the distance strategy for FAISS, do I need to explicitly set it for similarity_search_with_score method?

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your help. I have a follow-up question. Do I need to normalize_L2 to True?

Thank you

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your help. Can you tell me about Jaccard similarity and what needs to be set in its conjunction. Is it better than MAX_INNER_PRODUCT and do I need to set normalize_L2 ? Also, what is the range of values for Jaccard Similarity? As far as I know, Jaccard similarity is defined for binary valued vectors, but FAISS is not binary valued. So how is the Jaccard similarly calculated with langchain?

**Comment by mansourshams** [comment]
@dosu-bot

I am using the latest version of langchain by issuing

!pip install --upgrade langchain

I do not see any errors, I am using langchain for an RAG application and would like to know if the Jaccard Similarity is better than MAX_INNER_PRODUCT and if I need to set normalize_L2

**Comment by mansourshams** [comment]
@dosu-bot

Thank you for your great help. Do you have any information in the range of values returned by Jaccard and how does it map into similarity, I am specifically asking about langchain implementation for non binary vectors.

**Comment by annjawn** [comment]
I wonder if `override_relevance_score_fn` can be used with `FAISS.from_documents`. I tried but ended up with `unexpected keyword argument 'override_relevance_score_fn'` error.

**Comment by annjawn** [comment]
@dosu-bot I wonder if `override_relevance_score_fn` can be used with `FAISS.from_documents`. I tried but ended up with `unexpected keyword argument 'override_relevance_score_fn'` error.
