### ISSUE TITLE
Use "parse_file" in class "ConversationBufferMemory" raise a ValidationError

### ISSUE THREAD

**Issue by Natmat626** [langchain-ai/langchain#13282]
### System Info

Platform:Windows
LangChain:0.0.335
python:3.9.12

### Who can help?

@eyurtsev @hwchase17 @hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here is my code:

from langchain.memory import ConversationBufferMemory
import langchain.load

ChatMemory = ConversationBufferMemory()
ChatMemory.chat_memory.add_ai_message("Hello")
ChatMemory.chat_memory.add_user_message("HI")
tojson = ChatMemory.json()

with open('E:\\memory.json', 'w') as file:
    file.write(tojson)
    file.close()

ParserChatMemory = ConversationBufferMemory.parse_file('E:\\memory.json')

### Expected behavior

Regarding the parse_file method in ConversationBufferMemory, there is not much introduction in the document, and I have not found a similar problem description. However, saving Memory into a file/or generating it from a file is a normal requirement, but when I execute parse_file This method throws a "ValidationError", the complete description is as follows:

ValidationError: 1 validation error for ConversationBufferMemory
chat_memory
  instance of BaseChatMessageHistory expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseChatMessageHistory)

If there is any violation of my operation, please tell me, thank you very much

**Comment by Natmat626** [comment]
@dosu-bot
Your answer doesn't work

**Comment by B3AU** [comment]
I have a similar error. I implemented a custom chat history. Calling outputs an error.

```
issubclass(type(history),BaseChatMessageHistory) #output: True

ConversationBufferMemory(chat_memory=history,
                         memory_key='chat_history',
                         return_messages=True)
```
gives this error:
```
ValidationError: 1 validation error for ConversationBufferMemory
chat_memory
  instance of BaseChatMessageHistory expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseChatMessageHistory)
```

**Comment by tommyM86** [comment]
I also have this problem. I'm trying to use 
```history: BaseChatMessageHistory = StreamlitChatMessageHistory(key="messages")```

with
```
memory: ConversationBufferMemory = ConversationBufferMemory(memory_key="chat_history",
                                                            return_messages=True,
                                                            chat_memory=history)
```
and get the same error:
```
This error was raised: 1 validation error for ConversationBufferMemory
chat_memory
  instance of BaseChatMessageHistory expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseChatMessageHistory)
```
