### ISSUE TITLE
Issue: Create async streaming custom LLM

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [langchain-ai/langchain#13289]
### Issue you'd like to raise.

I currently have an OLLAMA model running locally. I aim to develop a CustomLLM model that supports asynchronous streaming to interface with this model. However, the OLLAMA adapter provided by LangChain lacks support for these specific features. How can I accomplish this integration?

**Comment by Nikita-Sherstnev** [comment]
@dosu-bot I tried to use your class, but LangChain keeps calling _stream method instead of _astream.

**Comment by valentimarco** [comment]
@dosu-bot can you implement the _agenerate method?
