### ISSUE TITLE
NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}} when using openai==1.2.3 and langchain==0.0.335

### ISSUE THREAD

**Issue by glejdis** [langchain-ai/langchain#13284]
### System Info

from langchain.chat_models import AzureChatOpenAI

llm_chat = AzureChatOpenAI(deployment_name="gpt-4_32k", model_name = 'gpt-4-32k', openai_api_version=openai.api_version, temperature=0)

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables = ["text"],
    template="{text}"
)

llmchain = LLMChain(llm=llm_chat, prompt=prompt)
llmchain.run(text)

NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

openai==1.2.3 and langchain==0.0.335

from langchain.chat_models import AzureChatOpenAI
text = "Where is Germany located?"
llm_chat = AzureChatOpenAI(deployment_name="gpt-4_32k", model_name = 'gpt-4-32k', openai_api_version=openai.api_version, temperature=0)

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables = ["text"],
    template="{text}"
)

llmchain = LLMChain(llm=llm_chat, prompt=prompt)
llmchain.run(text)

### Expected behavior

In europe

**Comment by alkhawli** [comment]
also having the same error with OpenAI()

**Comment by kottofy** [comment]
Seems like it has to do with the `api_base`. I added `/openai` on to the end of my endpoint and it worked.

```python
from langchain.chat_models import AzureChatOpenAI
from langchain.schema import HumanMessage

OPENAI_API_BASE="https://MY_AOAI.openai.azure.com" + "/openai"
OPENAI_API_KEY=""
OPENAI_API_VERSION="2023-05-15"
OPENAI_API_TYPE="azure"
DEPLOYMENT_NAME_GPT_4="gpt-4-32k"

llm = AzureChatOpenAI(
    openai_api_base= OPENAI_API_BASE,
    openai_api_key=OPENAI_API_KEY,
    openai_api_version=OPENAI_API_VERSION,
    openai_api_type= OPENAI_API_TYPE,
    model_name=DEPLOYMENT_NAME_GPT_4,
    temperature=0.0
)

message = HumanMessage(
    content="Translate this sentence from English to French. I love programming."
)
llm([message])
```

**Comment by as-km** [comment]
I have the same issue, which has to do with API VERSION 
2023-11-01 vs 2023-07-01-Preview (which worked beforehand...)

**Comment by Swain0114** [comment]
My langchain version is 0.0.336 and openai is 1.3.4.

I use azure_endpoint instead of openai_api_base and it works. If your openai version is above 1.0.0, class AzureChatOpenAI would re-format your openai_api_base. I think it's the issue came from.

```
            azure_llm = AzureChatOpenAI(
                deployment_name=deploy_name,
                openai_api_type=os.getenv("AZURE_OPENAI_TYPE"),
                openai_api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
                openai_api_key=self.openai_api_key,
                azure_endpoint="https://**{your_endpoint}**.openai.azure.com/openai/deployments/**{deployment_name}**/chat/completions?api-version=2023-07-01-preview",
            )
```

**Comment by ashishkumardas1025** [comment]
I am facing the same error. Can any one help me on this. I also tried using the Chromadb but facing the same error.
 
docsearch = FAISS.from_documents(texts, embeddings)

**Comment by dchinn1** [comment]
> I am facing the same error. Can any one help me on this. I also tried using the Chromadb but facing the same error.
> 
> docsearch = FAISS.from_documents(texts, embeddings)

Make sure you're using ```AzureOpenAIEmbeddings``` and not ```OpenAIEmbeddings```, and you include as a parameter for ```AzureOpenAIEmbeddings```: ```azure_deployment = ... # <- add your deployment name here```

This answer helped me immensely with what I expect is a similar issue to yours (embeddings endpoint 404ing)

https://github.com/langchain-ai/langchain/issues/14018#issuecomment-1837144072

**Comment by Anang1502** [comment]
Hi @glejdis,
Did you get any solution to this issue? I am also facing the same issue.

**Comment by giulio-utf** [comment]
Any news on this?

**Comment by janantala** [comment]
Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`

**Comment by yuvaldream** [comment]
any new?

**Comment by janantala** [comment]
> > Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`
> 
> it worked! Where did you get the api version?I check Azure document and cloud not find information about the version.

From network inspector in https://oai.azure.com/portal chat

**Comment by 35sui-com** [comment]
> > > Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`
> > 
> > 
> > it worked! Where did you get the api version?I check Azure document and cloud not find information about the version.
> 
> From network inspector in https://oai.azure.com/portal chat

Would you give me screenshot？I can't find your result，and I use the version as the following，langchain return Resource not found error
<img width="932" alt="image" src="https://github.com/langchain-ai/langchain/assets/166781603/e8218ecf-ab6e-4784-a0a2-f24aa351e99f">

**Comment by janantala** [comment]
> > > > Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`
> > > 
> > > 
> > > it worked! Where did you get the api version?I check Azure document and cloud not find information about the version.
> > 
> > 
> > From network inspector in https://oai.azure.com/portal chat
> 
> Would you give me screenshot？I can't find your result，and I use the version as the following，langchain return Resource not found error <img alt="image" width="932" src="https://private-user-images.githubusercontent.com/166781603/327605915-e8218ecf-ab6e-4784-a0a2-f24aa351e99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3Mjc5NjMsIm5iZiI6MTcxNDcyNzY2MywicGF0aCI6Ii8xNjY3ODE2MDMvMzI3NjA1OTE1LWU4MjE4ZWNmLWFiNmUtNDc4NC1hMGEyLWYyNGFhMzUxZTk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwOTE0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTFlMGI1NmU2MGQzODllNWVkODE3MzIyNzc0NjA2ZWMxZTAxYmM2ZjBhYTEzN2U3OGI2N2RlN2YyYmIxOWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lyTsBE-qLHSR9Po9Jw-zbnyQ39-VIh1H45Uo6N7XYJM">

![Uploading Screenshot 2024-05-03 at 11.14.06.png…]()

**Comment by janantala** [comment]
> > > > Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`
> > > 
> > > 
> > > it worked! Where did you get the api version?I check Azure document and cloud not find information about the version.
> > 
> > 
> > From network inspector in https://oai.azure.com/portal chat
> 
> Would you give me screenshot？I can't find your result，and I use the version as the following，langchain return Resource not found error <img alt="image" width="932" src="https://private-user-images.githubusercontent.com/166781603/327605915-e8218ecf-ab6e-4784-a0a2-f24aa351e99f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjgwMTgsIm5iZiI6MTcxNDcyNzcxOCwicGF0aCI6Ii8xNjY3ODE2MDMvMzI3NjA1OTE1LWU4MjE4ZWNmLWFiNmUtNDc4NC1hMGEyLWYyNGFhMzUxZTk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwOTE1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2M2MGE5YWU0OTU3NDY1MjEwMjZhOGY3YzVjMWE3OTMxOGJlM2RlODNjNmE0YzEwMDEyZWI2ZmMxZGIwOTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D3H6nrA2UrVhWioJdWAJmL7L0c9tTt1yHOuRXJyZROE">

![Screenshot 2024-05-03 at 11 14 06](https://github.com/langchain-ai/langchain/assets/840789/c7f9effd-ebef-4e9a-8ad9-0220e8ef7651)

**Comment by youkaisteve** [comment]
> Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`

It works for me, tks

**Comment by Sabeeh789** [comment]
import openai, os, requests

openai.api_type = "azure"
openai.api_version = "2024-02-15-preview"

# Azure OpenAI setup
openai.api_base = "https://openaichatplaygrounddemo.openai.azure.com/" # Add your endpoint here
openai.api_key = os.getenv("OPENAI_API_KEY") # Add your OpenAI API key here
deployment_id = "azure_openai" # Add your deployment ID here

# Azure AI Search setup
search_endpoint = "https://searchopenaichat.search.windows.net"; # Add your Azure AI Search endpoint here
search_key = os.getenv("SEARCH_KEY"); # Add your Azure AI Search admin key here
search_index_name = "hotels-sample-index"; # Add your Azure AI Search index name here

def setup_byod(deployment_id: str) -> None:
    """Sets up the OpenAI Python SDK to use your own data for the chat endpoint.

    :param deployment_id: The deployment ID for the model to use with your own data.

    To remove this configuration, simply set openai.requestssession to None.
    """

    class BringYourOwnDataAdapter(requests.adapters.HTTPAdapter):

        def send(self, request, **kwargs):
            request.url = f"{openai.api_base}/openai/deployments/{deployment_id}/extensions/chat/completions?api-version={openai.api_version}"
            return super().send(request, **kwargs)

    session = requests.Session()

    # Mount a custom adapter which will use the extensions endpoint for any call using the given `deployment_id`
    session.mount(
        prefix=f"{openai.api_base}/openai/deployments/{deployment_id}",
        adapter=BringYourOwnDataAdapter()
    )

    openai.requestssession = session

setup_byod(deployment_id)


message_text = [{"role": "user", "content": "What are the differences between Azure Machine Learning and Azure AI services?"}]

completion = openai.ChatCompletion.create(
    messages=message_text,
    deployment_id=deployment_id,
    data_sources=[  # camelCase is intentional, as this is the format the API expects
      {
  "type": "azure_search",
  "parameters": {
    "endpoint": "'$search_endpoint'",
    "index_name": "hotels-sample-index",
    "semantic_configuration": "default",
    "query_type": "simple",
    "fields_mapping": {
      "content_fields_separator": "\n",
      "content_fields": [
        "Description",
        "Category"
      ],
      "filepath_field": "HotelId",
      "title_field": "HotelName",
      "url_field": null,
      "vector_fields": []
    },
    "in_scope": true,
    "role_information": "You are an AI assistant that helps people find information.",
    "filter": null,
    "strictness": 3,
    "top_n_documents": 5,
    "authentication": {
      "type": "api_key",
      "key": "admin_key"
    },
    "key": "'$search_key'",
    "indexName": "'$search_index'"
  }
}
    ],
    temperature=0,
    top_p=1,
    max_tokens=800,
    stop=null,
    stream=true

)
print(completion)

**Comment by Sabeeh789** [comment]
I'm getting the 404 Resource not found error in this code

**Comment by Sabeeh789** [comment]
Can somebody help. I'm not using langchain just openai ?

**Comment by Sabeeh789** [comment]
import openai, os, requests

openai.api_type = "azure"
openai.api_version = "2024-02-15-preview"

# Azure OpenAI setup
openai.api_base = "https://openaichatplaygrounddemo.openai.azure.com/" # Add your endpoint here
openai.api_key = os.getenv("OPENAI_API_KEY") # Add your OpenAI API key here
deployment_id = "aaa" # Add your deployment ID here

# Azure AI Search setup
search_endpoint = "aaa"; # Add your Azure AI Search endpoint here
search_key = os.getenv("SEARCH_KEY"); # Add your Azure AI Search admin key here
search_index_name = "aaa"; # Add your Azure AI Search index name here

def setup_byod(deployment_id: str) -> None:
    """Sets up the OpenAI Python SDK to use your own data for the chat endpoint.

    :param deployment_id: The deployment ID for the model to use with your own data.

    To remove this configuration, simply set openai.requestssession to None.
    """

    class BringYourOwnDataAdapter(requests.adapters.HTTPAdapter):

        def send(self, request, **kwargs):
            request.url = f"{openai.api_base}/openai/deployments/{deployment_id}/extensions/chat/completions?api-version={openai.api_version}"
            return super().send(request, **kwargs)

    session = requests.Session()

    # Mount a custom adapter which will use the extensions endpoint for any call using the given `deployment_id`
    session.mount(
        prefix=f"{openai.api_base}/openai/deployments/{deployment_id}",
        adapter=BringYourOwnDataAdapter()
    )

    openai.requestssession = session

setup_byod(deployment_id)


message_text = [{"role": "user", "content": "What are the differences between Azure Machine Learning and Azure AI services?"}]

completion = openai.chat.completions.create(
    messages=message_text,
    deployment_id=deployment_id,
    data_sources=[  # camelCase is intentional, as this is the format the API expects
      {
  "type": "azure_search",
  "parameters": {
    "endpoint": "'$search_endpoint'",
    "index_name": "index",
    "semantic_configuration": "default",
    "query_type": "simple",
    "fields_mapping": {
      "content_fields_separator": "\n",
      "content_fields": [
        "Description",
        "Category"
      ],
      "filepath_field": "HotelId",
      "title_field": "HotelName",
      "url_field": null,
      "vector_fields": []
    },
    "in_scope": true,
    "role_information": "You are an AI assistant that helps people find information.",
    "filter": null,
    "strictness": 3,
    "top_n_documents": 5,
    "authentication": {
      "type": "api_key",
      "key": "key"
    },
    "key": "'$search_key'",
    "indexName": "'$search_index'"
  }
}
    ],
    temperature=0,
    top_p=1,
    max_tokens=800,
    stop=null,
    stream=true

)
print(completion)

**Comment by Sabeeh789** [comment]
### Here's the Code
`import openai, os, requests

openai.api_type = "azure"
openai.api_version = "2024-02-15-preview"

# Azure OpenAI setup
openai.api_base = "Endpoint" # Add your endpoint here
openai.api_key = os.getenv("OPENAI_API_KEY") # Add your OpenAI API key here
deployment_id = "aaa" # Add your deployment ID here

# Azure AI Search setup
search_endpoint = "https://searchopenaichat.search.windows.net"; # Add your Azure AI Search endpoint here
search_key = os.getenv("SEARCH_KEY"); # Add your Azure AI Search admin key here
search_index_name = "index"; # Add your Azure AI Search index name here

def setup_byod(deployment_id: str) -> None:
    """Sets up the OpenAI Python SDK to use your own data for the chat endpoint.

    :param deployment_id: The deployment ID for the model to use with your own data.

    To remove this configuration, simply set openai.requestssession to None.
    """

    class BringYourOwnDataAdapter(requests.adapters.HTTPAdapter):

        def send(self, request, **kwargs):
            request.url = f"{openai.api_base}/openai/deployments/{deployment_id}/extensions/chat/completions?api-version={openai.api_version}"
            return super().send(request, **kwargs)

    session = requests.Session()

    # Mount a custom adapter which will use the extensions endpoint for any call using the given `deployment_id`
    session.mount(
        prefix=f"{openai.api_base}/openai/deployments/{deployment_id}",
        adapter=BringYourOwnDataAdapter()
    )

    openai.requestssession = session

setup_byod(deployment_id)


message_text = [{"role": "user", "content": "Which is the best hotel in New York?"}]

completion = openai.chat.completions.create(
    messages=message_text,
    deployment_id=deployment_id,
    data_sources=[  # camelCase is intentional, as this is the format the API expects
      {
  "type": "azure_search",
  "parameters": {
    "endpoint": "'$search_endpoint'",
    "index_name": "index",
    "semantic_configuration": "default",
    "query_type": "simple",
    "fields_mapping": {
      "content_fields_separator": "\n",
      "content_fields": [
        "Description",
        "Category"
      ],
      "filepath_field": "HotelId",
      "title_field": "HotelName",
      "url_field": null,
      "vector_fields": []
    },
    "in_scope": true,
    "role_information": "You are an AI assistant that helps people find information.",
    "filter": null,
    "strictness": 3,
    "top_n_documents": 5,
    "authentication": {
      "type": "api_key",
      "key": "key"
    },
    "key": "'$search_key'",
    "indexName": "'$search_index'"
  }
}
    ],
    temperature=0,
    top_p=1,
    max_tokens=800,
    stop=null,
    stream=true

)
print(completion)`

**Comment by Sabeeh789** [comment]
`import openai, os, requests

openai.api_type = "azure"
openai.api_version = "2024-02-15-preview"
openai.api_base = "endpoint" # Add your endpoint here
openai.api_key = os.getenv("OPENAI_API_KEY") # Add your OpenAI API key here
deployment_id = "id" # Add your deployment ID here

search_endpoint = "Search_Endpoint"; # Add your Azure AI Search endpoint here
search_key = os.getenv("SEARCH_KEY"); # Add your Azure AI Search admin key here
search_index_name = "index"; # Add your Azure AI Search index name here

def setup_byod(deployment_id: str) -> None:
    """Sets up the OpenAI Python SDK to use your own data for the chat endpoint.

    :param deployment_id: The deployment ID for the model to use with your own data.

    To remove this configuration, simply set openai.requestssession to None.
    """

    class BringYourOwnDataAdapter(requests.adapters.HTTPAdapter):

        def send(self, request, **kwargs):
            request.url = f"{openai.api_base}/openai/deployments/{deployment_id}/extensions/chat/completions?api-version={openai.api_version}"
            return super().send(request, **kwargs)

    session = requests.Session()

    # Mount a custom adapter which will use the extensions endpoint for any call using the given `deployment_id`
    session.mount(
        prefix=f"{openai.api_base}/openai/deployments/{deployment_id}",
        adapter=BringYourOwnDataAdapter()
    )

    openai.requestssession = session

setup_byod(deployment_id)


message_text = [{"role": "user", "content": "What are the differences between Azure Machine Learning and Azure AI services?"}]

completion = openai.chat.completions.create(
    messages=message_text,
    deployment_id=deployment_id,
    data_sources=[  # camelCase is intentional, as this is the format the API expects
      {
  "type": "azure_search",
  "parameters": {
    "endpoint": "'$search_endpoint'",
    "index_name": "index",
    "semantic_configuration": "default",
    "query_type": "simple",
    "fields_mapping": {
      "content_fields_separator": "\n",
      "content_fields": [
        "Description",
        "Category"
      ],
      "filepath_field": "HotelId",
      "title_field": "HotelName",
      "url_field": null,
      "vector_fields": []
    },
    "in_scope": true,
    "role_information": "You are an AI assistant that helps people find information.",
    "filter": null,
    "strictness": 3,
    "top_n_documents": 5,
    "authentication": {
      "type": "api_key",
      "key": "key"
    },
    "key": "'$search_key'",
    "indexName": "'$search_index'"
  }
}
    ],
    temperature=0,
    top_p=1,
    max_tokens=800,
    stop=null,
    stream=true

)
print(completion)`

**Comment by Sabeeh789** [comment]
I'm facing this error in Azure open AI Studio add your data View code option . I tried to call the azure endpoint thorough api call but it gives me Resource not found error

**Comment by AmrinKareem** [comment]
> Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`

This worked for me!

**Comment by ahmedshafikk** [comment]
> Hello, I have resolved this using api version `2024-02-15-preview` instead of Model version displayed in azure table `0613`

thanks this solved the problem
