### ISSUE TITLE
Utilize metadata during retrieval in ConversationalRetrieval and PGvector

### ISSUE THREAD

**Issue by toobashahid210** [langchain-ai/langchain#13281]
I am using PGvector as retriever in my Conversational Retriever Chain. 
in my document there is some meta information saved like topic, keywords etc. 

how can use this meta information in retrieval instead of only using content? 

Would appreciate any solution for this.

**Comment by huantt** [comment]
- If you want to filter by metadata in Chain, you can use [SelfQueryRetriever](https://python.langchain.com/docs/modules/data_connection/retrievers/self_query/).
- If you want to use metadata to create the answer, you can do it in the prompt, it can access to both content & metadata of retrieved documents.

**Comment by mwwoo121** [comment]
Would you point me to the current location of the provided sources?.  Below links are no longer valid.
[libs/langchain/tests/integration_tests/vectorstores/test_pgvector.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/integration_tests/vectorstores/test_pgvector.py)
[tests/integration_tests/vectorstores/test_pgvector.py](https://github.com/hwchase17/langchain/blob/master/tests/integration_tests/vectorstores/test_pgvector.py)
