### ISSUE TITLE
Langchain Stopped Working in AWS Lambda Function using version 0.0.95, it works fine inn 0.0.94

### ISSUE THREAD

**Issue by adeolaemmanuelmorren** [langchain-ai/langchain#1329]
Langchain Stopped Working in AWS Lambda Function using version 0.0.95, 

it works fine in 0.0.94

Specifically it fails to build my AWS Sam Application it gets stuck at [INFO]: Running PythonPipBuilder:ResolveDependencies

switching to 0.0.94 is the solution for now...

**Comment by jianghoy** [comment]
Do you have more detail in the error message? Like is there something after `ResolveDependencies`?

**Comment by adeolaemmanuelmorren** [comment]
Nope that's all I have it just stays stuck there...
