### ISSUE TITLE
OpenAI exception classes have different import path in openai 1.2.3, causing breaking change in ChatOpenAI - Simple fix

### ISSUE THREAD

**Issue by andrei-assa** [langchain-ai/langchain#13323]
### System Info

- Langchain version: langchain==0.0.335
- OpenAI version: openai==1.2.3
- Platform: Darwin MacBook Pro 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103 arm64
- Python version: Python 3.9.6

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Example script:

```python
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI()
user_input = input("Input prompt: ")
response = llm.invoke(user_input)
```

```python
    return self._generate(
  File "...lib/python3.9/site-packages/langchain/chat_models/openai.py", line 360, in _generate
    response = self.completion_with_retry(
  File "...lib/python3.9/site-packages/langchain/chat_models/openai.py", line 293, in completion_with_retry
    retry_decorator = _create_retry_decorator(self, run_manager=run_manager)
  File "...lib/python3.9/site-packages/langchain/chat_models/openai.py", line 73, in _create_retry_decorator
    openai.error.Timeout,

Exception module 'openai' has no attribute 'error'
```

Cause appears to be in `langchain.chat_models.openai`: https://github.com/langchain-ai/langchain/blob/5a920e14c06735441a9ea28c1313f8bd433dc721/libs/langchain/langchain/chat_models/openai.py#L82-L88

Modifying above to this appears to resolve the problem:

```python
  errors = [
      openai.Timeout,
      openai.APIError,
      openai.APIConnectionError,
      openai.RateLimitError,
      openai.ServiceUnavailableError,
]
```

### Expected behavior

Chat model invocation should return a BaseMessage.

**Comment by mbrner** [comment]
The current dependencies require [openai<1.0.0](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/pyproject.toml#L49) any plans to move to openai >=1.0.0
