### ISSUE TITLE
Add POST API Functionality to LangChain

### ISSUE THREAD

**Issue by mwzkhalil** [langchain-ai/langchain#13334]
### Feature request

LangChain supports GET functions, but there is no support for POST functions. This feature request proposes the addition of POST API functionality to enhance the capabilities of LangChain.

### Motivation

The motivation behind this feature request is to extend the capabilities of LangChain to handle not only GET requests but also POST requests. 

### Your contribution

I am willing to contribute to the development of this feature. I will carefully follow the contributing guidelines and provide a pull request to implement the POST API functionality.

**Comment by mwzkhalil** [comment]
In the 'openapi.py' file, there is a GET function, but no POST function is present. I am referring to external APIs, and my
objective is to both retrieve (GET) and send (POST) data.

'
def get_openapi_chain(
    spec: Union[OpenAPISpec, str],
    llm: Optional[BaseLanguageModel] = None,
    prompt: Optional[BasePromptTemplate] = None,
    request_chain: Optional[Chain] = None,
    llm_chain_kwargs: Optional[Dict] = None,
    verbose: bool = False,
    headers: Optional[Dict] = None,
    params: Optional[Dict] = None,
    **kwargs: Any,
) -> SequentialChain:
    """Create a chain for querying an API from a OpenAPI spec.

    Args:
        spec: OpenAPISpec or url/file/text string corresponding to one.
        llm: language model, should be an OpenAI function-calling model, e.g.
            `ChatOpenAI(model="gpt-3.5-turbo-0613")`.
        prompt: Main prompt template to use.
        request_chain: Chain for taking the functions output and executing the request.
    """
    if isinstance(spec, str):
        for conversion in (
            OpenAPISpec.from_url,
            OpenAPISpec.from_file,
            OpenAPISpec.from_text,
        ):
            try:
                spec = conversion(spec)  # type: ignore[arg-type]
                break
            except Exception:  # noqa: E722
                pass
        if isinstance(spec, str):
            raise ValueError(f"Unable to parse spec from source {spec}")
    openai_fns, call_api_fn = openapi_spec_to_openai_fn(spec)
    llm = llm or ChatOpenAI(
        model="gpt-3.5-turbo-0613",
    )
    prompt = prompt or ChatPromptTemplate.from_template(
        "Use the provided API's to respond to this user query:\n\n{query}"
    )
    llm_chain = LLMChain(
        llm=llm,
        prompt=prompt,
        llm_kwargs={"functions": openai_fns},
        output_parser=JsonOutputFunctionsParser(args_only=False),
        output_key="function",
        verbose=verbose,
        **(llm_chain_kwargs or {}),
    )
    request_chain = request_chain or SimpleRequestChain(
        request_method=lambda name, args: call_api_fn(
            name, args, headers=headers, params=params
        ),
        verbose=verbose,
    )
    return SequentialChain(
        chains=[llm_chain, request_chain],
        input_variables=llm_chain.input_keys,
        output_variables=["response"],
        verbose=verbose,
        **kwargs,
    )

'

**Comment by mwzkhalil** [comment]
thank you found this 
[https://github.com/langchain-ai/langchain/pull/7777](issue)

**Comment by jaymon0703** [comment]
That PR was never merged, and there is no way to submit more than GET request. See https://github.com/langchain-ai/langchain/blob/d6e34f9ee5a4a1b1bca80e39eb45fd65cefb65c2/libs/langchain/langchain/chains/api/base.py#L169.

Is this functionality going to be added to LangChain?
