### ISSUE TITLE
Reduce embeddings size

### ISSUE THREAD

**Issue by Mohit0928** [langchain-ai/langchain#13332]
### Issue you'd like to raise.

I'm trying to replicate [this example](https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#basic-example) of langchain. I'm using ElasticSearch as the database to store the embedding. In the given example I have replaced `embeddings = OpenAIEmbeddings()` with `embeddings = OllamaEmbeddings(model="llama2")` which one can import `from langchain.embeddings import OllamaEmbeddings`. I'm running `Ollama` locally. But, I'm running into below error:
```
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'The number of dimensions for field [vector] should be in the range [1, 2048] but was [4096]')
```
The Ollama model always create the embedding of size `4096` even when I set the chunk size of `500`. Is there any way to reduce the size of embedding? or is there anyway to store larger size embeddings in `ElasticSearch`

**Comment by LeiTi34** [comment]
@Mohit0928 were you able to resolve this?
