### ISSUE TITLE
Issue: <How to do streaming response from Ollama??>

### ISSUE THREAD

**Issue by shawsa-artc** [langchain-ai/langchain#13333]
### Issue you'd like to raise.

I couldnt find any documentation on this , please help

How can i stream the response from Ollama ?

**Comment by tien-tran0906** [comment]
This workaround kindda solves it for me:

```python 
from langchain_community.llms import Ollama
from langchain.callbacks.base import BaseCallbackHandler

class StreamingCallbackHandler(BaseCallbackHandler):
    def __init__(self):
        self.partial_output = ""

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        self.partial_output += token
        print(token, end="", flush=True)

llm = Ollama(model="mistral:instruct", callbacks=[StreamingCallbackHandler()])

response = llm.invoke("prompt here")

print(response)
```

I'm using:
langchain==0.1.11
langchain-community==0.0.27

**Comment by vishalnagda1** [comment]
Here is the code suggested in the [documentation](https://python.langchain.com/docs/integrations/llms/ollama/):
```python
from langchain_community.llms import Ollama

llm = Ollama(model="llama2")

query = "Tell me a joke"

for chunks in llm.stream(query):
    print(chunks)
```

Below given is the sample Flask app demonstrating the Ollama streaming using rest API.
```python
import os
import json

from langchain_community.llms import Ollama

from flask import Flask, Response, request
from flask import stream_with_context

app = Flask(__name__)

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://0.0.0.0:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "llama2")

llm = Ollama(model=OLLAMA_MODEL, base_url=OLLAMA_BASE_URL)

def generate_tokens(question):
    for chunks in llm.stream(question):
        yield chunks

@app.route("/users/chat", methods=["POST"])
def ask_ai():
    def generate_json(question):
        with app.app_context():  # Ensure we're within the application context
            full_content = ""
            for token in generate_tokens(question):
                full_content += token
                json_data = {
                    "model": OLLAMA_MODEL,
                    "content": token,
                    "done": False
                }
                json_str = json.dumps(json_data)  # Convert JSON data to a string
                json_bytes = json_str.encode('utf-8')  # Encode JSON string to bytes
                yield json_bytes
                yield b'\n'  # Yield newline as bytes

            # Once streaming is finished, yield one last JSON object with "done" set to True
            json_data = {
                "model": OLLAMA_MODEL,
                "full_content": full_content,
                "done": True
            }
            json_str = json.dumps(json_data)  # Convert JSON data to a string
            json_bytes = json_str.encode('utf-8')  # Encode JSON string to bytes
            yield json_bytes
    
    request_data = request.json
    question = request_data.get("question")
    return Response(stream_with_context(generate_json(question)), mimetype='application/json')


if __name__ == '__main__':
    app.run(debug=True)

```

Below given is the CURL to get the streaming response from Flask server

```shell
curl --location 'localhost:5000/users/chat' \
--header 'Content-Type: application/json' \
--data '{
    "question": "Hello"
}'
```

**Comment by MikeyBeez** [comment]
Langchain is blockware if you don't use openai.  Nothing works properly for ollama.  Avoid using it entirely.

**Comment by MikeyBeez** [comment]
Do this instead:

import os
import requests
import json
from datetime import datetime

def create_memories_directory():
    if not os.path.exists("memories"):
        os.makedirs("memories")

def save_prompt_and_response(prompt, response):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"memories/{timestamp}.txt"

    with open(filename, "w") as file:
        file.write(f"User: {prompt}\n\n")
        file.write(f"Agent: {response}\n\n")

def main():
    model_name = "gemma:2b"  # Replace with the desired model name
    api_url = "http://localhost:11434/api/generate"

    create_memories_directory()

    while True:
        prompt = input("Enter your prompt (or type 'quit' to exit): ")
        print()  # Print a newline after the prompt

        if prompt.lower() == "quit":
            break

        data = {"model": model_name, "prompt": prompt}
        response = requests.post(api_url, json=data)

        print("Agent: ", end="")  # Print "Agent: " before streaming starts

        response_text = ""
        for line in response.iter_lines():
            if line:
                line_decoded = line.decode("utf-8")
                response_json = json.loads(line_decoded)
                print(response_json["response"], end="")  # Print the output
                response_text += response_json["response"]

        print("\n")  # Print a newline after streaming finishes
        save_prompt_and_response(prompt, response_text)

if __name__ == "__main__":
    main()
