### ISSUE TITLE
PowerPoint loader crashing

### ISSUE THREAD

**Issue by Ricu** [langchain-ai/langchain#13342]
### System Info

Langchain Version: 0.0.335
Platform: Windows 10
Python Version = 3.11.3
IDE: VS Code

### Who can help?

@eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

MWE:
A PowerPoint presentation named "test.pptx" in the same folder as the script. Content is a title slide with sample text.

```python
from langchain.document_loaders import UnstructuredPowerPointLoader
def ingest_docs():
  loader= UnstructuredPowerPointLoader('test.pptx')
  docs = loader.load()
  return docs
```

I get a problem in 2/3 tested environments:

1. Running the above MWE with `ingest_docs()` in a simple python script will yield no problem. The content of the PowerPoint (text on the title slide) is displayed.
2. Running the above MWE in a Jupyter Notebook with `ingest_docs()` will cause the cell to run indefinetely. Trying to interrupt the kernel results in: `Interrupting the kernel timed out`. A fix is to restart the kernel.
3. Running the MWE in Streamlit (see code below) will result the spawned server to die immediately. (The cmd Window simply closes)
```python
import streamlit as st
from langchain.document_loaders import UnstructuredPowerPointLoader
def ingest_docs():
  [as above]

st.write(ingest_docs())
```

### Expected behavior

I expect the MWE to work the same in the Notebook and Streamlit environments just as in the simple Python script.

**Comment by Ricu** [comment]
@dosu-bot Explicitly installing libmagic did not fix the problem. Note, when I talk about "environment" I do not mean Python Virutal Environments but rather the context in which the script is executed.

**Comment by Ricu** [comment]
@umair313 yes, as can be seen in the MWE in the initial post its a pptx, created using PowerPoint. Not sure what you mean by rendering tool.

**Comment by Ricu** [comment]
@umair313 any news from your side?

**Comment by qiuhualiu** [comment]
please try to pip install python-magic-bin
