### ISSUE TITLE
CosmosDBHistoryMessage

### ISSUE THREAD

**Issue by PrasenjitGiri** [langchain-ai/langchain#13361]
### System Info

CosmosDBHistory messages are wiping out the session of each run. 
Need the library to not recreate the object for the same session or else this cannot be used as chatbot which is stateless

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`import os
from time import perf_counter

from langchain.chat_models import AzureChatOpenAI
from langchain.memory.chat_message_histories import CosmosDBChatMessageHistory
from langchain.schema import (
    SystemMessage,
    HumanMessage
)

from logger_setup import logger

llm = AzureChatOpenAI(
    deployment_name=os.getenv('OPENAI_GPT4_DEPLOYMENT_NAME'),
    model=os.getenv('OPENAI_GPT4_MODEL_NAME')
)

cosmos_history = CosmosDBChatMessageHistory(
    cosmos_endpoint=os.getenv('AZ_COSMOS_ENDPOINT'),
    cosmos_database=os.getenv('AZ_COSMOS_DATABASE'),
    cosmos_container=os.getenv('AZ_COSMOS_CONTAINER'),
    session_id='1234',
    user_id='user001',
    connection_string=os.getenv('AZ_COSMOS_CS')
)

# cosmos_history.prepare_cosmos()

sys_msg = SystemMessage(content='You are a helpful bot that can run various SQL queries')
# cosmos_history.add_message(sys_msg)

human_msg = HumanMessage(content='Can you tell me how things are done in database')
cosmos_history.add_message(human_msg)

messages = []

messages.append(sys_msg)
messages.append(human_msg)

start_time = perf_counter()
response = llm.predict_messages(messages=messages)
end_time = perf_counter()

logger.info('Total time taken %d s', (end_time - start_time))

print(response)

messages.append(response)

cosmos_history.add_message(response)

`

### Expected behavior

Need this to save it for each subsequent web service calls with the same session id

Also this code does not retrieve data 
try:
    logger.info(f"Reading item with session_id: {self.session_id}, user_id: {self.user_id}")
    item = self._container.read_item(
        item=self.session_id,
        partition_key=self.user_id
    )
except CosmosHttpResponseError as ex:
    logger.error(f"Error reading item from CosmosDB: {ex}")
    return

But using sql does
query = f"SELECT * FROM c WHERE c.id = '{self.session_id}' AND c.user_id = '{self.user_id}'"
items = list(self._container.query_items(query, enable_cross_partition_query=True))

if items:
    item = items[0]
    # Continue with reading the item
else:
    logger.info("Item not found in CosmosDB")
    return

**Comment by PrasenjitGiri** [comment]
@dosu-bot not working

**Comment by makoit** [comment]
I'm also trying to use cosmosdb for chat history, but I cannot find any example or documentationhow to use it with a conversational chain and how to setup the db service on azure.
