### ISSUE TITLE
VertexAIModelGarden _generate method not in sync with VertexAI API

### ISSUE THREAD

**Issue by trevdoz** [langchain-ai/langchain#13370]
### System Info

LangChain version: 
Platform: WSL for Windows (Linux 983G3J3 5.15.90.1-microsoft-standard-WSL2)
Python version: 3.10.6

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1a. Create a project in GCP and deploy an open source model from Vertex AI Model Garden (follow the provided Colab notebook to deploy to an endpoint)
1b. Instantiate a VertexAIModelGarden object 
```python
llm = VertexAIModelGarden(project=PROJECT_ID, endpoint_id=ENDPOINT_ID)
```
2. Create a prompt string
```python
prompt = "This is an example prompt"
```
3. Call the generate method on the VertexAIModelGarden object
```python
llm.generate([prompt])
```
4. The following error will be produced:
```python
../python3.10/site-packages/langchain/llms/vertexai.py", line 452, in <listcomp>
    [Generation(text=prediction[self.result_arg]) for prediction in result]
TypeError: string indices must be integers
```

### Expected behavior

Expecting the generate method to return an LLMResult object that contains the model's response in the 'generations' property

In order to align with Vertex AI api the _generate method should iterate through response.predictions and set text property of Generation object to the iterator variable since response.predictions is a list data type that contains the output strings.
```python
for result in response.predictions:
            generations.append(
                [Generation(text=result)]
            )
```

**Comment by trevdoz** [comment]
@dosu-bot the generate method shouldn't convert the result iterator variable to a dict because the result is just a string that contains the output. It should simply create a Generation object by setting the text property equal to the result

**Comment by lkuligin** [comment]
@trevdoz has the problem been solved for you? can we close the issue?

**Comment by xesf** [comment]
Just started doing some tests with VertexAI Model Garden and got the exact same issue above with the result from the GCP Llama2 not chained correctly into SQLDatabaseChain.

`SQL compilation error:
syntax error line 1 at position 0 unexpected 'P'.
[SQL: P]`
