### ISSUE TITLE
Issue: <error faq() takes 1 positional argument but 2 were given>

### ISSUE THREAD

**Issue by zhangleinice** [langchain-ai/langchain#13383]
### Issue you'd like to raise.

```
openai.proxy = {
            "http": "http://127.0.0.1:7890",
            "https": "http://127.0.0.1:7890"
        }

callback = AsyncIteratorCallbackHandler()

llm = OpenAI(
    openai_api_key= os.environ["OPENAI_API_KEY"],
    temperature=0, 
    streaming=True, 
    callbacks=[callback]
)
embeddings = OpenAIEmbeddings()

# faq
loader = TextLoader("static/faq/ecommerce_faq.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

docsearch = Chroma.from_documents(texts, embeddings)

faq_chain = RetrievalQA.from_chain_type(
    llm, 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(),
)

@tool("FAQ")
def faq(input) -> str:
    """"useful for when you need to answer questions about shopping policies, like return policy, shipping policy, etc."""
    print('faq input', input)
    return faq_chain.acall(input)

tools = [faq]

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

conversation_agent = initialize_agent(
    tools, 
    llm, 
    agent="conversational-react-description", 
    memory=memory, 
    verbose=True,
)
    
 async def wait_done(fn, event):
    try:
        await fn
    except Exception as e:
        print('error', e)
        # event.set()
    finally:
        event.set()


async def call_openai(question):

    # chain = faq(question)
    chain = conversation_agent.acall(question)

    coroutine = wait_done(chain, callback.done)

    task = asyncio.create_task(coroutine)

    async for token in callback.aiter():
        # print('token', token)
        yield f"{token}"

    await task

app = FastAPI()

@app.get("/")
async def homepage():
    return FileResponse('static/index.html')

@app.post("/ask")
def ask(body: dict):
    return StreamingResponse(call_openai(body['question']), media_type="text/event-stream")

if __name__ == "__main__":
   uvicorn.run(host="127.0.0.1", port=8888, app=app)
```

RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Thought: Do I need to use a tool? No
AI: 你好！很高兴认识你！

> Finished chain.
INFO:     127.0.0.1:65193 - "POST /ask HTTP/1.1" 200 OK
conversation_agent <coroutine object Chain.acall at 0x1326b78a0>
coroutine <async_generator object AsyncIteratorCallbackHandler.aiter at 0x133b49340>

> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: FAQ
Action Input: 如何更改帐户信息error faq() takes 1 positional argument but 2 were given

**Comment by zhangleinice** [comment]
Only call_openai function chain = conversation_agent.acall(question) is used

**Comment by zhangleinice** [comment]
There was no problem when I used chain = faq(question), but I got an error after using conversation_agent.acall(question).

**Comment by zhangleinice** [comment]
> _🤖_
> 
> It seems like you're encountering an error with the `faq()` function, which is expecting one argument but is receiving two. The error message suggests that the function `faq()` is being called with two arguments somewhere in your code, but from the code snippet you've provided, it's not immediately clear where this is happening.
> 
> Could you please provide more context or a more detailed traceback of the error? This would help in identifying the exact line of code where the error is occurring. Also, if you have made any modifications to the `faq()` function or the way it's being called, sharing those details would be helpful as well.
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot
Only call_openai function chain = conversation_agent.acall(question) is used
There was no problem when I used chain = faq(question), but I got an error after using conversation_agent.acall(question).

**Comment by zhangleinice** [comment]
```python
 async def call_openai(question):
     chain = conversation_agent.acall({'input': question})
     coroutine = wait_done(chain, callback.done)
     task = asyncio.create_task(coroutine)
     async for token in callback.aiter():
         yield f"{token}"
     await task
 ```


@dosu-bot
After I tried changing it to this, I still got the same error.

**Comment by Izbushkoo** [comment]
Obviously there is some mistake in code base in langchain 0.0.335 package cause the same issue with LCEL .invoke()/.batch() calls
