### ISSUE TITLE
ElasticSearch allow for multiple vector_query_fields than default text & make it a kwarg in search functions 

### ISSUE THREAD

**Issue by DJ2695** [langchain-ai/langchain#13398]
### Feature request

Elastic supports natively to have multiple DenseVectors in a document, which can be selected during query time / search. The langchain vector search  interface enables to pass additional keyword args. But at the moment, the implementation of _search in the ElasticSearch implementation does not consider the `vector_query_field` variable, which could be passed through the kwargs. Furthermore, there should be a solution, to allow a document to have multiple text fields that get passed as a queryable vector, not just the standard text field.

### Motivation

If you have multiple vector fields in one index, this feature could simplify the query of the right one, like it's natively allowed in Elastic. In the current implementation one would need to add additional vector fields in the metadata and change the `vector_query_field` of ElasticSearchStore the whole class every time before you call the search. This is not a clean solution and I would vote for a more generic and clean solution.

### Your contribution

I could help by implementing this issue, although I need to state that I am not an expert in Elastic. I saw this issue when we tried to use an existing index in Elastic to add and retrieve Documents within the Langchain Framework.

**Comment by joemcelroy** [comment]
Hi there,

You can build your own strategy too, to help with how you index and query.

Example for just BM25

```python
class BM25RetrievalStrategy(ApproxRetrievalStrategy):

    def __init__(
        self
    ):
        pass

    def query(
        self,
        query: Union[str, None],
        filter: List[dict],
        **kwargs,
    ):
                
        if query:
            query_clause = [{
                "multi_match": {
                    "query": query,
                    "fields": ["text"],
                    "fuzziness": "AUTO",
                }
            }]
        else:
            query_clause = []


        bm25_query = {
            "query": {
                "bool": {
                    "filter": filter,
                    "must": query_clause
                }
            },
        }

        print("query", bm25_query)

        return bm25_query


vectorstore = ElasticsearchStore(
  index_name="movies_self_query",
  es_connection=client,
  strategy=BM25RetrievalStrategy()
)
```
