### ISSUE TITLE
Missing escape in `llms.utils.enforce_stop_tokens()`

### ISSUE THREAD

**Issue by morganveyret** [langchain-ai/langchain#13397]
### System Info

Not relevant.

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use any LLM relying on stop words with special regex characters.

For example instanciate a `HuggingFacePipeline` LLM instance with [openchat](https://huggingface.co/openchat/openchat_3.5) model. This model uses `<|end_of_turn|>` stop words.

Since the `llms.utils.enforce_stop_tokens()` function doesn't escape the provided stop words strings the `|` chars are interpreted as part of the regex instead of the stop word. So in this case any single `<` chars in the output would trigger the
split.

### Expected behavior

Stop words should be escaped with `re.escape()` so the split only happens on the complete words.

**Comment by umair313** [comment]
I am looking into that. will submit a PR.

@hwchase17
@agola11

**Comment by efriis** [comment]
Won't fix - see #11113 and #13468
