### ISSUE TITLE
Add support for multimodal embeddings from Google Vertex AI

### ISSUE THREAD

**Issue by SDonkelaarGDD** [langchain-ai/langchain#13400]
### Feature request

Currently no support for multi-modal embeddings from VertexAI exists. However, I did stumble upon this experimental implementation of [GoogleVertexAIMultimodalEmbeddings](https://js.langchain.com/docs/modules/data_connection/experimental/multimodal_embeddings/google_vertex_ai) in LangChain for Javascript. Hence, I think this would also be a very nice feature to implement in the Python version of LangChain.

### Motivation

Using multi-modal embeddings could positively affect applications that rely on information of different modalities. One example could be product search in a web catalogue. Since more cloud providers are making [endpoints for multi-modal embeddings](https://cloud.google.com/vertex-ai/docs/generative-ai/embeddings/get-multimodal-embeddings) available, it makes sense to incorporate these into LangChain as well. The embeddings of these endpoints could be stored in vector stores and hence be used in downstream applications that are built using LangChain.

### Your contribution

I can contribute to this feature.

**Comment by beatgeek** [comment]
It seems it would be an update to this - `libs/langchain/langchain/embeddings/vertexai.py` where currently it's only for `textembedding-gecko` and lacks the function for image embeddings.

**Comment by SDonkelaarGDD** [comment]
@beatgeek indeed, I agree that that could be a good place to put it. We could make an extra class method `embed_multimodal()` that calls the multi-modal endpoint, as it can be used to embed both the images and text.

**Comment by pmoraesm** [comment]
Indeed, it's a nice feature to have!
