### ISSUE TITLE
Missing required arguments; Expected either ('model' and 'prompt') or ('model', 'prompt' and 'stream')

### ISSUE THREAD

**Issue by rockman25** [langchain-ai/langchain#13410]
### System Info

langchain = 0.0.335
openai = 1.2.4
python = 3.11

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Modified example code (https://python.langchain.com/docs/integrations/llms/azure_openai) from langchain to access AzureOpenAI inferencing endpoint

```
import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-05-15"
os.environ["OPENAI_API_BASE"] = "..."
os.environ["OPENAI_API_KEY"] = "..."

# Import Azure OpenAI
from langchain.llms import AzureOpenAI

# Create an instance of Azure OpenAI
# Replace the deployment name with your own
llm = AzureOpenAI(
    deployment_name="td2",
    model_name="text-davinci-002",
)

# Run the LLM
llm("Tell me a joke")
```

I get the following error:
TypeError: Missing required arguments; Expected either ('model' and 'prompt') or ('model', 'prompt' and 'stream') arguments to be given

If I modify the last line as follows:
`llm("Tell me a joke", model="text-davinci-002") `
i get a different error: 
Completions.create() got an unexpected keyword argument 'engine'

It appears to be passing all keywords to the create method, the first of which is 'engine', and it appears that and other kws are being added by the code.

### Expected behavior

I expect the model to return a response, such as is shown in the example.

**Comment by rockman25** [comment]
@dosu-bot This does not work. In fact, I get an error message saying 'AzureOpenAI' object has no attribute 'run'.

**Comment by rockman25** [comment]
@dosu-bot Two problems with the latest solution: the argument should be 'prompts', not 'prompt'. But worse is when I use the correct argument I get the same error I started with--it's looking for a second argument, which is 'model'. But if I add that, now it once again gives an error saying Completions.create() got an unexpected keyword.

**Comment by playermanny2** [comment]
same issue here, seems like the new APIs for openai has broken this

**Comment by gcpdev** [comment]
I can confirm the problem, as I am facing the same issue at the moment by using AzureOpenAI in langchain 0.0.335.

As a workaround use:
`!pip install langchain==0.0.242
!pip install pip install openai==0.28`

**Comment by fenilvanvi-ifix** [comment]
I also faced the same issue yesterday. Today, I upgraded the langchain and openai versions. Now, it is working fine.

`!pip install langchain==0.0.336`
`!pip install openai==1.3.0`

**Comment by aht** [comment]
Works fine after upgrading to `langchain==0.0.339` now.

**Comment by Dhivyno** [comment]
@rockman25 I had the same problem except I was using a deepseek coder local LLM from LM studio and I managed to fix it by adding a parameter called "model":"deepseek-ai_deepseek-coder-6.7b-instruct" 

`from autogen import AssistantAgent, UserProxyAgent, config_list_from_json

config_list = [
    {
        **"model":"deepseek-ai_deepseek-coder-6.7b-instruct",**
        "base_url": "http://localhost:1234/v1",
        "api_key":"NULL"
    }
]

llm_config={
    "timeout": 600,
    "seed": 42,
    "config_list": config_list,
    "temperature": 0
}

assistant = AssistantAgent(
    name="Assistant",
    llm_config=llm_config,
    system_message="You are a coder specializing in Python."
)

user_proxy = UserProxyAgent(
    name="user_proxy",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
    code_execution_config={"work_dir": "web"},
    llm_config=llm_config,
    system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)

task1 = """
Write python code to convert an input in roman numerals to decimal output.
"""

task2 = """
Explain the code written by the Assistant to convert roman numerals to decimal.
"""

user_proxy.initiate_chat(
    assistant,
    message=task1
)

user_proxy.initiate_chat(
    assistant,
    message=task2
)`

I'm not sure how this plays into AzureOpenAI because I'm just a beginner programmer 😅 but hopefully it helps in some way.

**Comment by jeandtx** [comment]
@Dhivyno Man just saved my day
