### ISSUE TITLE
`get_openai_callback()` does not count tokens when LCEL chain used with `.stream()` method

### ISSUE THREAD

**Issue by orestxherija** [langchain-ai/langchain#13430]
### System Info

```
langchain==0.0.335
python==3.10
```

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

From the LCEL interface [docs](https://python.langchain.com/docs/expression_language/interface) we have the following snippet:
```python
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate

model = ChatOpenAI()
prompt = ChatPromptTemplate.from_template("tell me a joke about {topic}")
chain = prompt | model

for s in chain.stream({"topic": "bears"}):
    print(s.content, end="", flush=True)
```

From the token usage tracking [docs](https://python.langchain.com/docs/modules/model_io/chat/token_usage_tracking) we have the snippet
```python
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-4")

with get_openai_callback() as cb:
    result = llm.invoke("Tell me a joke")
    print(cb)
```
that yields the following output:
```
    Tokens Used: 24
        Prompt Tokens: 11
        Completion Tokens: 13
    Successful Requests: 1
    Total Cost (USD): $0.0011099999999999999
```

I am trying to combine the two concepts in the following snippet
```python
from langchain.prompts import ChatPromptTemplate
from langchain.callbacks import get_openai_callback
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(model_name="gpt-4")
prompt = ChatPromptTemplate.from_template("tell me a joke about {topic}")
chain = prompt | llm

with get_openai_callback() as cb:
    for s in chain.stream({"topic": "bears"}):
        print(s.content, end="", flush=True)
    print(cb)
```
but get the following result:
```
    Tokens Used: 0
        Prompt Tokens: 0
        Completion Tokens: 0
    Successful Requests: 0
    Total Cost (USD): $0
```

Is token counting (and pricing) while streaming not supported at the moment?

### Expected behavior

The following but with the actual values for tokens and cost.
```
    Tokens Used: 0
        Prompt Tokens: 0
        Completion Tokens: 0
    Successful Requests: 0
    Total Cost (USD): $0
```

**Comment by orestxherija** [comment]
@dosu-bot None of those issues is relevant to the one I raised.

**Comment by girithodu** [comment]
@orestxherija orestxherija  Were you able to figure out how to track the token usage? I am currently struggling with this issue.

**Comment by NguyenDrasp** [comment]
the problem is ChatOpenAI() can not count token when streming so you have to count it yourself 
https://github.com/langchain-ai/langchain/blob/22d90800c86799a3a385b73ba09608c9b6565e0a/libs/community/langchain_community/chat_models/openai.py#L607
![image](https://github.com/langchain-ai/langchain/assets/85470821/1b83fd62-c567-4b5c-bd40-738be80a3a59)

**Comment by baskaryan** [comment]
> the problem is ChatOpenAI() can not count token when streming so you have to count it yourself
> 
> https://github.com/langchain-ai/langchain/blob/22d90800c86799a3a385b73ba09608c9b6565e0a/libs/community/langchain_community/chat_models/openai.py#L607
> 


Yep as @NguyenDrasp mentioned, OpenAI doesn't currently return token usage when streaming. We could try to add our own approximate token counting to handle this, feel free to open an [Ideas Discussion item](https://github.com/langchain-ai/langchain/discussions/categories/ideas) with this feature request if that'd be useful! 

Closing issue, but let me know if I'm missing something and we can reopen.

**Comment by hgoona** [comment]
> > the problem is ChatOpenAI() can not count token when streming so you have to count it yourself
> > https://github.com/langchain-ai/langchain/blob/22d90800c86799a3a385b73ba09608c9b6565e0a/libs/community/langchain_community/chat_models/openai.py#L607
> 
> Yep as @NguyenDrasp mentioned, OpenAI doesn't currently return token usage when streaming. We could try to add our own approximate token counting to handle this, feel free to open an [Ideas Discussion item](https://github.com/langchain-ai/langchain/discussions/categories/ideas) with this feature request if that'd be useful!
> 
> Closing issue, but let me know if I'm missing something and we can reopen.

@baskaryan Can we use agent_executor.astream_events method to count tokens? 
If so, which events/what is the best way to count the Prompt tokens and Completion tokens when using an Agent with Tools and Memory?

**Comment by eyurtsev** [comment]
The main issue is that token counts aren't provided by the OpenAI API when streaming, so the calculation needs to be carried out on the client side.

Once you know how to do the calculation, you can do it:

Using astream events get the 'on chat model end' event and tokenize to count the tokens.

Using invoke, batch, stream pass a custom callback that calculates tokens from the 'on chat model end' callback.

To calculate the tokens can probably use tiktoken, but I'd recommend checking OpenAI forums to see how folks estimate the number of tokens in the streaming response.

**Comment by hgoona** [comment]
Thanks @eyurtsev - I've figured out how to use TikToken for my particular LLM to count the tokens based on the block of strings, but I still haven't figured out WHICH parts of the event `on_chat_model_end` need to be counted. (using `.astream_event()` )

I'm finding that my Token count result is very different to the Total Token count in LangSmith traces by a large margin (up to 100s of tokens); so I must be counting the wrong things OR is the LangSmith Token count incorrect sometimes??

Ultimate objective is to know what OpenAI will be charging me.

Can you please tell me **which** parts of **what** events I should be using my TokenCounter to count? 
And also, which parts are "Prompt" tokens and which are "Completion" tokens?
(I'm guessing in OpenAI terms Prompt = Input token cost, and
Completion = Output token cost, right?)

**Comment by frankcarey** [comment]
@hgoona and others - you can see a worked example of recreating the llm_info in this PR. I am using kwargs info, so it may be a bit fragile, but it's working for us. https://github.com/fablestudio/fable-saga/pull/55
