### ISSUE TITLE
Issue: problem with conversationchain take multiple inputs

### ISSUE THREAD

**Issue by xasxin** [langchain-ai/langchain#13433]
### Issue you'd like to raise.

Hi, I'm trying to make a chatbot using conversationchain. The prompt takes three variables, “history” from memory, user input: "input", and another variable say variable3. But it has an error “Got unexpected prompt input variables. The prompt expects ['history', 'input', 'variable3'], but got ['history'] as inputs from memory, and input as the normal input key. ”

This error doesn't occur if I'm using llmchain. So how can I prevent it if I want to use conversationchain?

Thanks

**Comment by SteveMilesQuant** [comment]
I'm also running into this and it's not the template. Code:
<code>
import os
from langchain.chains import ConversationChain
from langchain.prompts.prompt import PromptTemplate
from langchain.memory import ConversationSummaryMemory
from langchain_openai import OpenAI


CHARACTER_TEMPLATE = '''You are a character in a story. Your name is {character_name}. The input you receive is from a human Player.

Previous conversation history:
{history}

New input:
{input}

Response:'''

llm = OpenAI(
    temperature=1, openai_api_key=os.environ.get('OPENAPI_API_KEY'), max_tokens=1024)

character_prompt = PromptTemplate(
    input_variables=['history', 'input', 'character_name'],
    template=CHARACTER_TEMPLATE
)

conversation = ConversationChain(
    llm=llm,
    prompt=character_prompt,
    memory=ConversationSummaryMemory(llm=llm)
)
</code>

Message:
Got unexpected prompt input variables. The prompt expects ['character_name', 'history', 'input'], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error)

**Comment by AndriaSiradze** [comment]
Have same issue any solution ?
