### ISSUE TITLE
Request new feature for Robotic Application

### ISSUE THREAD

**Issue by Prof-pengyin** [langchain-ai/langchain#13440]
### Feature request

Hi Guys,

Here I made a new fork to [https://github.com/MetaSLAM/CyberChain](https://github.com/MetaSLAM/CyberChain), where I would like to combine the powerful Langchain ability and GPT4 into the real-world robotic challenges. 

My question raised here is mainly about:

1. How can I setup the Chat GPT 4 version into Langchain, where I would like to levevarge the powerful visual inference of GPT4;
2. I there any suggestion for the memory system, because the robot may travel through a large-scale environment for lifelong navigation, I would like to construct a memory system within langchain to enhance its behaviour in the long-term operation.

Many thanks for your hard work, and Langchain is difinitely an impressive work.

Max

### Motivation

Combine real-world robotic application with the LangChain framework.

### Your contribution

I will provide my research outcomes under our MetaSLAM organization (https://github.com/MetaSLAM), hope this can benefit both robotics and AI communitry, targeting for the general AI system.

**Comment by Prof-pengyin** [comment]
The automatic feedback doesn't solve the problem.

**Comment by ComeBackTo2016** [comment]
You can implement a tool and directly call the GPT4V interface within the tool. This should be a relatively simple approach. On the other hand, you can also integrate any models you need within the LLM framework.
