### ISSUE TITLE
create_csv_agent UnicodeDecodeError('utf-8' )

### ISSUE THREAD

**Issue by egisgeoai** [langchain-ai/langchain#13444]
### System Info

python

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain import OpenAI
from langchain.chains import AnalyzeDocumentChain
from langchain.chains.summarize import load_summarize_chain
from langchain_experimental.agents.agent_toolkits import create_csv_agent
from langchain.chains.question_answering import load_qa_chain
from langchain.chat_models import ChatOpenAI
from langchain.agents import AgentType

model = ChatOpenAI(model="gpt-4") # gpt-3.5-turbo, gpt-4

agent = create_csv_agent(model,"APT.csv",verbose=True)

agent.run("how many rows are there?")

### Expected behavior

UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-25-0a5f8e8f5933>](https://localhost:8080/#) in <cell line: 11>()
      9 model = ChatOpenAI(model="gpt-4") # gpt-3.5-turbo, gpt-4
     10 
---> 11 agent = create_csv_agent(model,"APT.csv",verbose=True)
     12 
     13 agent.run("how many rows are there?")

11 frames
/usr/local/lib/python3.10/dist-packages/pandas/_libs/parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb1 in position 0: invalid start byte

**Comment by umair313** [comment]
@egisgeoai answers provided by the bot is help full?
