### ISSUE TITLE
Langchain SQLDatabase is not able to access  table information correctly from private schema of PostgreSQL database

### ISSUE THREAD

**Issue by vishnua2j** [langchain-ai/langchain#13455]
### System Info

Langchain Version: 0.0.336
OS: Windows

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Using "SQLDatabase.from_uri" I am not able to access table information from private schema of PostgreSQL database. But using the same I am able to access table information from public schema of PostgreSQL DB.  How can I access table information from all the schema's ? Please find the code below. Can someone help me?

db = SQLDatabase.from_uri(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}",sample_rows_in_table_info=5) 

print(db.get_table_names())

### Expected behavior

I expected it give information of tables from all the schemas.

**Comment by developer20sujeet** [comment]
**Option 1** 

schema_name='Private-Schema'
engine = create_engine("ur detaiuls ")


metadata_obj = MetaData(schema=schema_name)
db = SQLDatabase(engine,**metadata=metadata_obj**)


Option 2 
db = SQLDatabase(engine,schema=**schema_name_Value**)
