### ISSUE TITLE
Can't load docx file with directory in content.

### ISSUE THREAD

**Issue by charleybin** [langchain-ai/langchain#13452]
### System Info

Error info:

<CT_SectPr '<w:sectPr>' at 0x2c9fa6c50> is not in list

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. create a new word ( .docx ) file,  
2. wirte some content inside, then insert a directory in some where and save file.  
3. upload .docx file.
4. click Button 'add file to Knowledge base'
5. check the file added. 
6. you could see "DocumentLoader, spliter is None" and  Document count is 0.

### Expected behavior

load docx file successful.

**Comment by umair313** [comment]
Can you explain point 2,3,4 where you are trying to `upload the file`? where is that 'add file to Knowledge base' button?

> - create a new word ( .docx ) file,
> - wirte some content inside, then insert a directory in some where and save file.
> - upload .docx file.
> - click Button 'add file to Knowledge base'
> - check the file added.
> - you could see "DocumentLoader, spliter is None" and Document count is 0.
