### ISSUE TITLE
OpenAI Assitant

### ISSUE THREAD

**Issue by ADianan** [langchain-ai/langchain#13453]
### Feature request

Can you allow the usage of existing Open ai assistant instead of creating a new one every time when using OpenAI Runnable 

### Motivation

I dont want to clutter my assistant list with a bunch of clones

### Your contribution

The developer should only provide the assistant ID in the Constructor for OpenAIRunnable

**Comment by ADianan** [comment]
how do i use existing openai assistant instead of creating new ones with OpenaiRunnable
________________________________

**Comment by Jyumpp** [comment]
@ADianan The code for OpenAI Assistants have already been merged into langchain master as part of Agents, just pending the next ad-hoc PyPI release, or using the master branch directly rather than a release.

**Comment by hinthornw** [comment]
As @Pflyg pointed out, you just specify the assistant ID.

**Comment by hasansustcse13** [comment]
I want to create an OpenAI assistant using an existing ID, but I'm encountering an error.

1. assistant = OpenAIAssistantRunnable(assistant_id='assistant_id', as_agent=True)
`openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`
2. assistant = OpenAIAssistantRunnable(assistant_id='assistant_id', as_agent=True, client=openai.OpenAI(api_key=self.model.openai_api_key))
`pydantic.v1.errors.ConfigError: field "client" not yet prepared, so the type is still a ForwardRef. You might need to call OpenAIAssistantRunnable.update_forward_refs()`

In both cases, an error is encountered. The only successful scenario is when the openai_api_key is set in the environment, but my requirement is for the user to provide it. Has anyone else faced a similar issue? Any assistance would be appreciated.

@hinthornw @Pflyg @ADianan

**Comment by black7375** [comment]
How to [modified](https://platform.openai.com/docs/api-reference/assistants/modifyAssistant) or [delete](https://platform.openai.com/docs/api-reference/assistants/deleteAssistant) with `OpenAIAssistantRunnable`?

**Comment by MichaelChenGithub** [comment]
Hi @hasansustcse13 , you can include the parameter client= OpenAI(api_key=OPENAI_APIKEY) to specify the use of the passed API KEY to create the agent. The complete code would be as follows:

a`gent = OpenAIAssistantRunnable(client=OpenAI(api_key=openai_api_key), assistant_id=assistant_id, as_agent=True)`

FTR: https://api.python.langchain.com/en/latest/agents/langchain.agents.openai_assistant.base.OpenAIAssistantRunnable.html

**Comment by dontnet-wuenze** [comment]
> How to [modified](https://platform.openai.com/docs/api-reference/assistants/modifyAssistant) or [delete](https://platform.openai.com/docs/api-reference/assistants/deleteAssistant) with `OpenAIAssistantRunnable`?
> 
> I think we need to add code similar to the following.
> 
> ```python
> @classmethod
> def delete_assistant(
>     assistant_id: str
>     client: Optional[Union[openai.OpenAI, openai.AzureOpenAI]] = None
> ):
>     client = client or _get_openai_client()
>     return client.beta.assistants.delete()
> ```

I face the same issue, hope langchain can support delete assistant
