### ISSUE TITLE
Issue: Sitemap Loader not fetching

### ISSUE THREAD

**Issue by nextaiarnav** [langchain-ai/langchain#13460]
### Issue you'd like to raise.

Wrote the following code in Google Colab but it is unable to fetch the data. Kindly help.

from langchain.document_loaders.sitemap import SitemapLoader
sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml")
docs = sitemap_loader.load()
print(docs)

![image](https://github.com/langchain-ai/langchain/assets/148566663/599ae1dc-51ce-455d-93ba-f22704e5e029)

**Comment by nextaiarnav** [comment]
Thanks @DosuBot. Issue Resolved

**Comment by eyurtsev** [comment]
The docs have moved -- use this URL instead:  https://python.langchain.com/sitemap.xml

**Comment by sachinmandhotra1** [comment]
The root cause could be related to blocking of the scraping process by the website, since there is no User Agent value defined in the base class.
I was able to fix the issue by installing the fake user agent module in python.
command - 'pip install fake-useragent'
