### ISSUE TITLE
Text splitters inhéritance

### ISSUE THREAD

**Issue by GasparQ** [langchain-ai/langchain#13510]
### System Info

I am facing an issue using `MarkdownHeaderTextSplitter` class and, after looking at the code, I noticed that the problem might be present in several Text Splitters and I did not find any issue on this, so I create a new one.

I am trying to use `MarkdownHeaderTextSplitter` regarding the `TextSplitter` interface by calling the method `transform_document`.

However, the [`MarkdownHeaderTextSplitter` does not inherit from `TextSplitter`](https://github.com/langchain-ai/langchain/blob/35e04f204ba3e69356a4f8f557ea88f46d2fa389/libs/langchain/langchain/text_splitter.py#L331) and I wondered if it was a justified implementation or just an oversight.

It seems that the [`HTMLHeaderTextSplitter` is in that case too](https://github.com/langchain-ai/langchain/blob/35e04f204ba3e69356a4f8f557ea88f46d2fa389/libs/langchain/langchain/text_splitter.py#L496).

Can you give me some insight on how to use theses classes if the behavior is normal ?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This code is a good way to reproduce what I am trying to do

```python
from langchain.text_splitter import MarkdownHeaderTextSplitter
from langchain.document_loaders import TextLoader

loader = TextLoader("test.md")
document = loader.load()

transformer = MarkdownHeaderTextSplitter([
    ("#", "Header 1"),
    ("##", "Header 2"),
    ("###", "Header 3"),
])

tr_documents = transformer.transform_documents(document)
```

### Expected behavior

I want this to return a list of documents (`langchain.docstore.document.Document`) splitted in the same way `MarkdownHeaderTextSplitter.split_text` does on the content of a markdown document [as presented in the documentation](https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/markdown_header_metadata).

**Comment by DSamuylov** [comment]
I came up with a similar question, and I believe it would be helpful to align logic here.

In addition to the example that @GasparQ mentioned to demonstrate how it would facilitate applying `MarkdownHeaderTextSplitter` to a loaded document, it would be also helpful to inherit metadata.

Currently, after splitting text with:

```
markdown_text = "# Header 1\nContent 1\n## Header 2\nContent 2"
splitter = MarkdownHeaderTextSplitter([
    ("#", "Header 1"),
    ("##", "Header 2"),
])

documents = splitter.split_text(markdown_text)
```

the metadata would contain only `Header 1` and `Header 2` fields, and if I would like to update metadata, I need to do something like this:

```
for document in documents:
    document.metadata.update({"source": "my-source-value"})
```

However, if we pass a document as input following the example from @GasparQ, `source` field and other metadata that maybe set on `Document` instance should be inherited by the output of `MarkdownHeaderTextSplitter`. For example, this is the behaviour of `RecursiveCharacterTextSplitter.split_documents`.
