### ISSUE TITLE
YoutubeLoader translation not working

### ISSUE THREAD

**Issue by gsanjeev432** [langchain-ai/langchain#13523]
### System Info

langchain == 0.0.336
python == 3.9.6

### Who can help?

@hwchase17 @eyu

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Code:

video_id = YoutubeLoader.extract_video_id("https://www.youtube.com/watch?v=DWUzWvv3xz4")
loader = YoutubeLoader(video_id, add_video_info=True,
                                   language=["en","hi","ru"],
                                   translation = "en")

loader.load()

Output:

[Document(page_content='में रुके शोध सजावट हाउ टू लेट सफल टीम मेंबर्स नो दैट वास नॉट फीयर कॉन्टेक्ट्स रिस्पोंड फॉर एग्जांपल एक्टिव एंड स्ट्रैंथ एंड assistant 3000 1000 कॉन्टैक्ट एंड वे नेवर रिग्रेट थे रिस्पांस यू वांट यू ऑटोमेटेकली गेट नोटिफिकेशन टुडे ओके खुफिया इज द नोटिफिकेशन पाइथन इन नोटिफिकेशन सीनेटर नोटिफिकेशन प्यार सेलिब्रेट विन रिस्पोंस वर्षीय बेटे ईमेल एस वेल एजुकेटेड व्हाट्सएप नोटिफिकेशन इफ यू वांट एनी फीयर अदर टीम मेंबर टू ऑल्सो गेट नोटिफिकेशन व्हेन यू व्हेन यू रिसीवर रिस्पांस फ्रॉम अननोन फीयर कांटेक्ट सुधर रिस्पांस सिस्टम लिफ्ट से ज़ू और यह टीम मेंबर कैन रिस्पोंड इम्युनिटी द न्यू कैंट व ईमेल ऐड्रेस आफ थे पर्सन वरीय स्वीडन से लेफ्ट से अब दूर एक पाठ 7 टारगेट्स ऑयल सुबह रायपुर दिस ईमेल एड्रेस नो अब्दुल विल गेट एनी नोटिफिकेशन फ्रॉम assistant साक्षी व्हेनेवर एनी बडी दिस पॉइंट स्ट्रेन ईमेल अब्दुल विल अलसो गेट डर्टी में अगर सब्जेक्ट लाइन रिस्पांस रिसीवड ए [संगीत]', metadata={'source': 'DWUzWvv3xz4', 'title': 'How to Notify your team member Immediately when a Lead Responds', 'description': 'Unknown', 'view_count': 56, 'thumbnail_url': 'https://i.ytimg.com/vi/DWUzWvv3xz4/hq720.jpg', 'publish_date': '2021-10-04 00:00:00', 'length': 87, 'author': '7Targets AI Sales Assistant'})]

### Expected behavior

The output video transcript should be in English.

**Comment by RaflyLesmana3003** [comment]
Hello @gsanjeev432! 👋 It appears there might be a misunderstanding here, if you refer to the [documentation](https://python.langchain.com/docs/integrations/document_loaders/youtube_transcript#add-language-preferences).

```
Language param : It's a list of language codes in a descending priority, en by default.


translation param : It's a translate preference when the youtube doesn't have your selected language, en by default.
```

The translated transcript should work when your video doesn't have a transcript in your language preference, defined here as ["en", "hi", "ru"]. but in the your given video it found "hi" as autogenerated transcript language, so i think it expected result by this code.


But indeed, it appears that your concern makes sense. We can certainly make improvements to address this issue.

**Comment by gsanjeev432** [comment]
@RaflyLesmana3003 But when I do this:

loader = YoutubeLoader(video_id, add_video_info=True,
                                   language=["en"],
                                   translation = "en")

It gives following error:

NoTranscriptFound: 
Could not retrieve a transcript for the video https://www.youtube.com/watch?v=DWUzWvv3xz4! This is most likely caused by:

No transcripts were found for any of the requested language codes: ['en']

Basically, I just need the transcript in English even if it is available in some other language. Can you provide me the code for achieving this?

**Comment by RaflyLesmana3003** [comment]
@gsanjeev432, can we close this issue, already create new PR and merged 🙌🏻
