### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.indexes'

### ISSUE THREAD

**Issue by Bakar31** [langchain-ai/langchain#1352]
I am encountering the following error when trying to import VectorstoreIndexCreator from langchain.indexes:
`ModuleNotFoundError: No module named 'langchain.indexes'`

**Comment by pratik-kanthi** [comment]
use the latest version

**Comment by mouyong** [comment]
how to install latest version

**Comment by rishabhrkaushik** [comment]
pip install langchain==0.0.118

**Comment by rishabhrkaushik** [comment]
> how to install latest version

pip install langchain==0.0.118

**Comment by noambenshoham** [comment]
Maybe your file called "langchain.py" ? I had the same problem and fixed it by changing the name of the file.

**Comment by mouyong** [comment]
1. open link: https://pypi.org/project/langchain/ , remember the latest version.
2. Specify installation version: `pip install langchain==x.y.z`

**Comment by aza1200** [comment]
My file was name "langchain.py" After I changed the file name, the problem solved

**Comment by ausboss** [comment]
> My file was name "langchain.py"

Thanks for sharing this. I made this mistake twice today already 💀

**Comment by dackdel** [comment]
where is it saved? i might need to change the name too. getting this error.

**Comment by caue-paiva** [comment]
getting the same error even after installing new updated version and changing the file name

**Comment by jakesant** [comment]
@pratik-kanthi Saying 'use the latest version' is not helpful if you're already using the latest version...

@Bakar31 Are you running this in a virtual environment? I am and had a similar problem, but the only solution that worked for me was to delete the virtual environment and create another one.
