### ISSUE TITLE
RAG but for fact checking

### ISSUE THREAD

**Issue by samber** [langchain-ai/langchain#13526]
### Feature request

I would be very nice to be able to build something similar to RAG, but for checking an assumption quality against a knowledge base.

### Motivation

Currently, RAG allows a semantic search but does not help when it comes to evaluating the quality of a user input, based on your vector db.

The point is not to fact-check the news in a newspaper (must be very hard actually...), but to evaluate truth in a random prompt.

### Your contribution

- prompting
- PR
- doc
- discussions

**Comment by hinthornw** [comment]
Is the request for an evaluator that accepts a generation as input and scores it based on factuality , grounding it on some retrieved reference docs?

**Comment by samber** [comment]
Yes. I would suggest a step between doc retrieval and answer generation, that evaluates a score and adapts the final answer based on it.
