### ISSUE TITLE
New update broke embeddings models

### ISSUE THREAD

**Issue by Will-Holt60** [langchain-ai/langchain#13539]
### System Info

LangChain version: 0.0.337
Python version: 3.10.13

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

db = Chroma.from_documents(docs, AzureOpenAIEmbeddings())

### Expected behavior

This worked on previous versions of LangChain using OpenAIEmbeddings(), but now I get this error

BadRequestError: Error code: 400 - {'error': {'message': 'Too many inputs. The max number of inputs is 16.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by mspronesti** [comment]
Hi @Will-Holt60, I opened a PR to fix this.
