### ISSUE TITLE
Upgrading to OpenAI Python 1.0+ = ImportError: Could not import openai python package.

### ISSUE THREAD

**Issue by johnsonfamily1234** [langchain-ai/langchain#13567]
### System Info

Using langchain 0.0.337 python, FastAPI.

When I use openai up through 0.28.1 it works fine. Upgrading to 1.0.0 or above results in the following error (when I try to use ChatOpenAI from langchain.chat_models):

"ImportError: Could not import openai python package. Please install it with `pip install openai`."

Trying to follow this notebook to integrate vision preview model:
https://github.com/langchain-ai/langchain/blob/master/cookbook/openai_v1_cookbook.ipynb

Any thoughts on what I might try? Thanks!

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

1. install openai (1.0.0), langchain (0.0.337) & langchain-experimental (0.0.39)
2. in FastAPI route, import ChatOpenAI from langchain.chat_models
3. Use ChatOpenAI as usual (working fine w/ openai <= 0.28.1

`    llm = ChatOpenAI(
      temperature=temperature,
      streaming=True,
      verbose=True,
      model_name=nameCode,
      max_tokens=tokens,
      callbacks=[callback],
      openai_api_key=relevantAiKey,
    )`

### Expected behavior

I would expect to not get a "failed import" error when the package is clearly installed.

**Comment by umair313** [comment]
@johnsonfamily1234 
what `pip freeze | grep openai`shows?

**Comment by johnsonfamily1234** [comment]
@umair313 and anyone else who sees this - I foolishly wasn't in a virtual environment.
