### ISSUE TITLE
 ConversationChain failure after changing template text

### ISSUE THREAD

**Issue by nickums** [langchain-ai/langchain#13578]
I am having a wonderful time with my code, but after changing my template  it now fails  before I even get to give my input. Baffling!

all the required imports are not shown here nor is all the prompt text (containing no special characters)
    template = '''Your task is to extract the relationships between terms in the input text,
                        Format your output as a json list. '''
    prompt = ChatPromptTemplate.from_messages([
                        SystemMessagePromptTemplate.from_template(template),
                        HumanMessagePromptTemplate.from_template("{input}"),
                        MessagesPlaceholder(variable_name="history "),
                        ])
    llm = ChatOpenAI(temperature=0.8, model_name='gpt-4-1106-preview') 
    memory = ConversationBufferMemory(return_messages=True)
    conversation = ConversationChain(memory=memory, prompt=prompt, llm=llm)](url)

  Traceback  .........
 conversation = ConversationChain(memory=memory, prompt=prompt, llm=llm)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationChain
__root__    Got unexpected prompt input variables. The prompt expects ['input', 'history '], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error)

**Comment by a3131919** [comment]
I got the same error here but I used PromptTemplate as my module: 

validationError: 1 validation error for ConversationChain
__root__
  Got unexpected prompt input variables. The prompt expects ['chat_history', 'human_input'], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error). 

 I think the ConversationChain may not accept the "prompt" properties.

**Comment by umair313** [comment]
@nickums ,
@a3131919 

try this out 

```
template = """Your task is to extract the relationships between terms in the input text,
Format your output as a json list.
{history}
"""
prompt = ChatPromptTemplate.from_messages([
    SystemMessagePromptTemplate.from_template(template),
    HumanMessagePromptTemplate.from_template("{input}"),
])
llm = ChatOpenAI(temperature=0.8, model_name='gpt-4-1106-preview')
memory = ConversationBufferMemory(return_messages=True)

conversation = ConversationChain(memory=memory, prompt=prompt, llm=llm, verbose=True)

conversation.predict(input="what is your task?")
```
