### ISSUE TITLE
The tracing on_llm_error() implementation calls _on_chain_error(), not _on_llm_error()

### ISSUE THREAD

**Issue by jwatte** [langchain-ai/langchain#13580]
### System Info

Linux 20.04 LTS
Python 3.6

### Who can help?

@hwchase17 seems like this got introduced on 2023-11-16

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Attempt to use a tracer to trace an LLM error
2. Note that the tracer hook for _on_chain_error is called instead

### Expected behavior

_on_llm_error hook should be called.

**Comment by observeinc-infra** [comment]
Pull request https://github.com/langchain-ai/langchain/pull/13581 has a proposed fix and test.
