### ISSUE TITLE
Issue: `pgvector` versions in `poetry.lock` are really old

### ISSUE THREAD

**Issue by orestxherija** [langchain-ai/langchain#13617]
### Issue you'd like to raise.

The compatible versions for library `pgvector` listed in `poetry.lock` are really old: `"pgvector (>=0.1.6,<0.2.0)"`.

Are we able to update them to more recent ones?

### Suggestion:

Update versions to recent ones.

**Comment by baron** [comment]
I think this issue can be closed:

https://github.com/pgvector/pgvector-python is 0.2.4
https://github.com/pgvector/pgvector is 0.5.1

on the current langchain:

Successfully installed numpy-1.26.2 pgvector-0.2.4
