### ISSUE TITLE
Integration of tabular data querying with LangChain

### ISSUE THREAD

**Issue by abhijithneilabraham** [langchain-ai/langchain#1361]
Hi, I am reaching out due to several requests from others in the field.

I am the author of TableQA: https://github.com/abhijithneilabraham/tableQA, a tool to query natural language on tabular data. The tool uses a BERT based huggingface model for QA on free text, and uses heuristics to combine it with tabular data to make SQL queries from natural language. 

The request from some users was to provide support with LangChain. I was wondering if I should raise an issue to LangChain to merge a feature for tabular data support, with the methodology provided in TableQA as an additional approach?

Regards.

**Comment by hwchase17** [comment]
TableQA looks awesome. Thinking outloud, theres a few options as I see them:

1. TableQA looks pretty good as a standalone package - could just link to it from a page. Eg we could add a page on tabular data support, link to our stuff internally, but then also link to your repo.
2. could add it as chain of sorts. eg we could have a ChatTableQAChain. the main things added in here would probably be (1) a preprocessing step to combine historical conversation with current question to distill it to a standalone question to pass to table qa, (2) a rephraser on the way out to convert the result to a natural language result (looks currently like the result of the sql query only?)
3. As a standalone tool, so then people could use it as a tool in an agent

any of these sound best? we can also do all! or other, if you have better ideas :)
