### ISSUE TITLE
Prompt language translations

### ISSUE THREAD

**Issue by lakshyaag** [langchain-ai/langchain#1363]
Starting a new issue to track [this idea](https://twitter.com/mathisob/status/1630620380707667968?s=20) to provide functionality to translate prompts based on the input language.

**Comment by lakshyaag** [comment]
Utilizing this library: [GoogleTrans](https://github.com/ssut/py-googletrans) to provide automatic translations. However, I'm running into version issues error with `poetry`. Can somebody help me out? @hwchase17

**Comment by AldawsariNLP** [comment]
try this: 
Poetry add googletrans =="3.1.0a0"
remove the latest version of googletrans. 
let me know if it worked!

**Comment by lakshyaag** [comment]
Nope, not working. Still giving me an issue.

**Comment by tuhoangwkm** [comment]
Please add prompt like this: Answer in as the same language as question

**Comment by ccasadei** [comment]
Just add the following sentence to the question: "Please answer in <Italian/Spanish/French/....>".
In this way the input can be in any language and only the output language is specified.
