### ISSUE TITLE
Langchain.schema.runnable now missing from docs?

### ISSUE THREAD

**Issue by muonmax** [langchain-ai/langchain#13631]
### System Info

Lanchain V: 0.339

### Who can help?

@hwchase17
@agola11 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Following any example that uses a `langchain.schema.runnable` object. For example the "[Adding memory](https://python.langchain.com/docs/expression_language/cookbook/memory)" tutorial uses `RunnableLambda` and `RunnablePassthrough`.

- I no longer see `langchain.schema` in the API docs (see image below).
- Searching in the API docs also doesn't return any results when searching for `RunnablePassthrough`
<img width="363" alt="image" src="https://github.com/langchain-ai/langchain/assets/94480542/1b3ded17-c669-406d-8309-4f953f42c1f6">

### Expected behavior

- I don't see anything in the release notes about the `langchain.schema.runnables` being removed or relocated.
- I would have expected to see them in the API docs, or at least for them to still be returned when searching for them.
- Not sure if this is a documentation build issue and the modules are still importable as I have not updated my Langchain version yet. I was just using the docs as a reference and then starting getting 404 errors upon page refresh (e.g. [this](https://api.python.langchain.com/en/latest/schema/langchain.schema.messages.AIMessageChunk.html#langchain.schema.messages.AIMessageChunk) page for `AIMessageChunk` also no longer exists)

**Comment by muonmax** [comment]
I think I see a [commit to main](https://github.com/langchain-ai/langchain/commit/d82cbf5e764c6e0a9d0bee2558119d302b0b57ad) where a bunch of stuff was moved out into the "langchain_core" library?

`langchain_core` docs may not have been populated correctly since they don't show the `...schema.runnables` docs either.

**Comment by muonmax** [comment]
@baskaryan - just bringing this to your attention. I can see more commits to main this morning but the docs are still missing many commonly used components in the tutorials/cookbooks (e.g. anything in `.schema.`, etc.).

**Comment by nickzhao8** [comment]
This issue should be fixed as per #13744.
