### ISSUE TITLE
ddg error: backend "news" is obsolete so should raise an error and example should be updated

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [langchain-ai/langchain#13648]
### System Info

Ubuntu 22
python 3.10.12
Langchain==0.0.339
duckduckgo-search==3.9.6

### Who can help?

@timonpalm who created [the PR](https://github.com/langchain-ai/langchain/pull/8292)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps are straight from [this help page](https://python.langchain.com/docs/integrations/tools/ddg) which is [this notebook](https://github.com/langchain-ai/langchain/blob/611e1e0ca45343b86debc0d24db45703ee63643b/docs/docs/integrations/tools/ddg.ipynb#L69)

```
from langchain.tools import DuckDuckGoSearchResults
search = DuckDuckGoSearchResults(backend="news")
search.run("Obama")
```
This results in error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/.local/lib/python3.10/site-packages/langchain/tools/base.py", line 365, in run
    raise e
  File "/home/USER/.local/lib/python3.10/site-packages/langchain/tools/base.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/home/USER/.local/lib/python3.10/site-packages/langchain/tools/ddg_search/tool.py", line 61, in _run
    res = self.api_wrapper.results(query, self.num_results, backend=self.backend)
  File "/home/USER/.local/lib/python3.10/site-packages/langchain/utilities/duckduckgo_search.py", line 108, in results
    for i, res in enumerate(results, 1):
  File "/home/USER/.local/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 96, in text
    for i, result in enumerate(results, start=1):
UnboundLocalError: local variable 'results' referenced before assignment
```

Looking at the source code of duckduckgo-search package I see this function: 
```
def text(
    self,
    keywords: str,
    region: str = "wt-wt",
    safesearch: str = "moderate",
    timelimit: Optional[str] = None,
    backend: str = "api",
    max_results: Optional[int] = None,
) -> Iterator[Dict[str, Optional[str]]]:
    """DuckDuckGo text search generator. Query params: https://duckduckgo.com/params

    Args:
        keywords: keywords for query.
        region: wt-wt, us-en, uk-en, ru-ru, etc. Defaults to "wt-wt".
        safesearch: on, moderate, off. Defaults to "moderate".
        timelimit: d, w, m, y. Defaults to None.
        backend: api, html, lite. Defaults to api.
            api - collect data from https://duckduckgo.com,
            html - collect data from https://html.duckduckgo.com,
            lite - collect data from https://lite.duckduckgo.com.
        max_results: max number of results. If None, returns results only from the first response. Defaults to None.
    Yields:
        dict with search results.

    """
    if backend == "api":
        results = self._text_api(keywords, region, safesearch, timelimit, max_results)
    elif backend == "html":
        results = self._text_html(keywords, region, safesearch, timelimit, max_results)
    elif backend == "lite":
        results = self._text_lite(keywords, region, timelimit, max_results)

    for i, result in enumerate(results, start=1):
        yield result
        if max_results and i >= max_results:
            break

```

My assessment is that langchain should raise an exception if backend is not part of ["api", "html", "lite"] and the notebook should not mention this "news" feature anymore.

### Expected behavior

Crashing when creating instance of ` DuckDuckGoSearchResults` with invalid `backend` argument and updating the documentation.

**Comment by thiswillbeyourgithub** [comment]
1. Good question @dosubot, indeed I tested the api, html and lite backend and they all returned results without crashing.
2. I'm using duckduckgo-search latest version which is 3.9.6
3. No more logs to share.

Additionnal information: I checked on [the pypi of duckduckgo-search](https://pypi.org/project/duckduckgo-search/) and they appear to still have a way to search for news so instead of changing the documentation, updating the ddg wrapper would solve the issue.

**Comment by deedy5** [comment]
Just use DDGS.news() function like so:
```python3
def news_results(self, query: str, num_results: int) -> List[Dict[str, str]]:
    from duckduckgo_search import DDGS

    with DDGS() as ddgs:
        results = ddgs.news(
            query,
            region=self.region,
            safesearch=self.safesearch,
            timelimit=self.time,
            max_results=num_results,
        )
        # rest of the code...
```

**Comment by thiswillbeyourgithub** [comment]
But then the argument `backend` does not mean for langchain anything close to what it means for ddgs. I think it might be better to have another name for the langchain argument like "source" that could be any of news, search, instant.

The reason I stumbled upon this bug was partly because I couldn't find documemtation about this backend argument.

**Comment by Carlcarrie** [comment]
leave backend out to avoid no error and [] response - e.g.

@tool("News")
def search_news_tool(query):
    """Useful to search the News. Expects a search query. Provide each source as a link and have at least 3 valid sources/links in the final response. Provide 250+ word responses. """
    with DDGS() as ddgs:
        ddgs_gen = ddgs.news(
                query,
                region="us-en",
                safesearch="moderate",
                timelimit="y",
                max_results=3,
        )
        if ddgs_gen:
                return [r for r in ddgs_gen]
    return []

**Comment by Carlcarrie** [comment]
@tool("News")
def search_news_tool(query):
    """Useful to search the News. Expects a search query. Provide each source as a link and have at least 3 valid sources/links in the final response. 
    Provide 250+ word responses. Escape monetary amounts and latex so st.markdown can display properly. Display news images 200 x 200"""

    with DDGS() as ddgs:
        ddgs_gen = ddgs.news(
                query,
                region="us-en",
                safesearch="moderate",
                timelimit="y",
                max_results=3,
        )
        if ddgs_gen:
                df = pd.DataFrame([result for result in ddgs_gen])
                return [r for r in ddgs_gen]
    return []``

**Comment by Carlcarrie** [comment]
@tool("News")
def search_news_tool(query):
    """Useful to search the News. Expects a search query. Provide each source as a link and have at least 3 valid sources/links in the final response. 
    Provide 250+ word responses. Escape monetary amounts and latex so st.markdown can display properly. Display news images 200 x 200"""

    with DDGS() as ddgs:
        ddgs_gen = ddgs.news(
                query,
                region="us-en",
                safesearch="moderate",
                timelimit="y",
                max_results=3,
        )
        if ddgs_gen:
                df = pd.DataFrame([result for result in ddgs_gen])
                return [r for r in ddgs_gen]
    return []

**Comment by Carlcarrie** [comment]
Important to ***leave backend out*** in your tool code for News to work (inconsistent with ddgs.text)


``` Python
@tool("News")
def search_news_tool(query):
    """Useful to search the News. Expects a search query. Provide each source as a link and have at least 3 valid sources/links in the final response. 
    Provide 250+ word responses."""

    with DDGS() as ddgs:
        ddgs_gen = ddgs.news(
                query,
                region="us-en",
                safesearch="moderate",
                timelimit="y",
                max_results=3,
        )
        if ddgs_gen:
                df = pd.DataFrame([result for result in ddgs_gen])
                return [r for r in ddgs_gen]
    return []
