### ISSUE TITLE
Issue: How to validate Tool input arguments without raising ValidationError

### ISSUE THREAD

**Issue by deepakagrawal** [langchain-ai/langchain#13662]
### Issue you'd like to raise.

I am creating a tool that takes a multiple input arguments (say input1, input2). I would like to validate their types and also make sure that the tool only receives input1 and input2. How do I validate this without breaking the llm chain. I would instead like to return a warning to the llm agent. something like, "The input passed were incorrect, please try again"

**Comment by deepakagrawal** [comment]
@dosu-bot, can you show an example of how is this "warning" used by the llm agent?

**Comment by deepakagrawal** [comment]
@dosu-bot this breaks the langchain flow due to raise ValidationError.

**Comment by deepakagrawal** [comment]
@dosu-bot you are going in loop. This was your initial solution. But that did not work.

**Comment by deepakagrawal** [comment]
@dosu-bot where would l call this function validate_inputs?

**Comment by ahmadaii** [comment]
@deepakagrawal Were you be able to handle this? I'm facing similar validation problem :)

**Comment by hmasdev** [comment]
@deepakagrawal @ahmadaii 
I also faced a similar validation problem. However, I have solved it.
So, I share a simple instant solution with you.

```bash
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import langchain
>>> langchain.__version__
'0.0.330'
>>> from functools import wraps
>>> from langchain.tools import StructuredTool
>>> from langchain import pydantic_v1 as pydantic
>>> # HERE IS A SAMPLE TOOL
>>> def joint(a: str, b: str) -> str:
...     '''joint two strings'''
...     return a + b
...
>>> joint_tool = StructuredTool.from_function(joint, name=joint.__name__, description=joint.__doc__, handle_tool_errors=True)  
>>> # PROBLEM REPRODUCTION
>>> joint_tool.run(dict(a='a', b='b'))
'ab'
>>> joint_tool.run(dict(a='a')) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\dev_libs\langchain\libs\core\langchain_core\tools.py", line 311, in run
    parsed_input = self._parse_input(tool_input)
  File "D:\dev_libs\langchain\libs\core\langchain_core\tools.py", line 246, in _parse_input
    result = input_args.parse_obj(tool_input)
  File "D:\dev_libs\langchain\venv\lib\site-packages\pydantic\v1\main.py", line 526, in parse_obj
    return cls(**obj)
  File "D:\dev_libs\langchain\venv\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for jointSchemaSchema
b
  field required (type=value_error.missing)
>>> # SOLUTION IS AS FOLLOWS
>>> joint_tool.__config__.extra = pydantic.Extra.allow            
>>> def handle_validation_error_deco(func):
...     
...     @wraps(func)
...     def wrapped(*args, **kwargs):
...         try:
...             return func(*args, **kwargs)
...         except pydantic.ValidationError as e:
...             return str(e)
...     return wrapped
...

>>> joint_tool.run  = handle_validation_error_deco(joint_tool.run)
>>> joint_tool.run(dict(a='a'))
'1 validation error for jointSchemaSchema\nb\n  field required (type=value_error.missing)'
>>> type( joint_tool.run(dict(a='a'))) 
<class 'str'>
```

By the way, I think that this problem is essentially caused because ValidationError is not handled in `BaseTool.run` and `BaseTool.arun`:
- https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/tools.py#L311 ;
- https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/tools.py#L386 .

So I believe one of the best solutions is as follows
- [] To add a filed named like `handle_validation_error` whose type should be `Optional[Union[bool, str, Callable[[pydantic.ValidationError], str]]]` to `BaseTool`;
- [] To add codes to handle `ValidationError` in `BaseTool.run` and `BaseTool.arun`.

**Comment by mnicstruwig** [comment]
@hmasdev Unfortunately I don't believe the proposed solution works [(I think because Pydantic is particular about modifying fields after declaration](https://stackoverflow.com/questions/65857313/overwrite-method-on-pydantic-instance)):

```python
>>> tool.run = handle_validation_error(tool.run)
ValueError: "StructuredTool" object has no field "run"
```

The fix to override the field appears to be to use the built-in `object`'s `__setattr__` data model method in order to force the override (this is the proposed answer from the link above):

So the workaround for others waiting for the PR to get merged would be to do:

```python
object.__setattr__(joint_tool, "run", handle_validation_error_deco(joint_tool.run)
```

**Comment by hmasdev** [comment]
@mnicstruwig 
Thanks for alternative solution.

Just in case, I afraid that you forget to set the config before overwriting `tool.run`.

```python
>>> tool.__config__.extra = pydantic.Extra.allow 
>>> tool.run = handle_validation_error(tool.run)
```

See https://github.com/pydantic/pydantic/blob/v1.10.13/pydantic/main.py#L356

But your solution is better :)

**Comment by deepakagrawal** [comment]
Sorry for looong delay in response. I ended up overwriting the _parse_input function of the tool

def _parse_input(
        self,
        # pyre-ignore
        tool_input: Union[str, Dict],
    ) -> Union[str, Dict[str, Any]]:
        """Convert tool input to pydantic model."""
        input_args = self.args_schema
        if isinstance(tool_input, str):
            if input_args is not None:
                key_ = next(iter(input_args.__fields__.keys()))
                input_args.validate({key_: tool_input})
            return tool_input
        else:
            if input_args is not None:
                try:
                    result = input_args.parse_obj(tool_input)
                    return {k: v for k, v in result.dict().items() if k in tool_input}
                except ValidationError as e:
                    logger.error(f"Failed to validate input: {e}")
                    return "Failed to validate input. I cannot use this tool. You should try another tool."
        return "Failed to validate input. I cannot use this tool. You should try another tool."

**Comment by Bhargav-1997** [comment]
Hello,
I have also encountered the same issue, where I want to perform the input validation and based on results either continue with tool execution or ask user for correct inputs.

I need your suggestion about will it be a good approach to have a separate LLM agent with set of instructions for input validation using Chain of Thoughts and based on validation from LLM decide on next step?

**Comment by SinaArdehali** [comment]
there seems to be no proper way of doing input validation in custom tools with Langchain 😞

**Comment by mnicstruwig** [comment]
@SinaArdehali and @Bhargav-1997 @deepakagrawal, I've found a lot of success using `magentic` ([magentic](https://github.com/jackmpcollins/magentic)) instead for this use-case, since it allows you to "pause" at the function calling step to do whatever you'd like with your input arguments.
