### ISSUE TITLE
Issue: how to remain the chain in different api calls?

### ISSUE THREAD

**Issue by RedNoseJJN** [langchain-ai/langchain#13697]
### Issue you'd like to raise.

This question may be stupid but I find nothing to refer to.
I'm using langchain.chains.LLMChain in flask api, but I found that the chain will be reloaded and reconstructed if I call the api after a call. So the first question I wanna ask is how to make my LLMChain be remembered so that I can use it directly in the next call.
I tried to use session in flask, but get ```Object of type LLMChain is not JSON serializable```.
Thanks.

**Comment by RedNoseJJN** [comment]
@dosu-bot I see. So my question now is: is there any possibility not to load the model every time when I call the api? If I can not save the chain, then I need to load and construct it every time. Can this be solved.

**Comment by RedNoseJJN** [comment]
@dosu-bot but is that case, won't things messed up if I have multi-user situation? If the chain is set as global, everyone who calls it is using the same chain isn't it?

**Comment by RedNoseJJN** [comment]
@dosu-bot alright. this is actually what I did at the very beginning. But I have a question about this solution: how to remain the history recorded? I used ConversationBufferMemory in my code, but found that the history will be reset in each call. What can I do to remain this history remembering function in my API?

**Comment by RedNoseJJN** [comment]
@dosu-bot can't understand why so complicated. I will try to find other solutions on my own.

**Comment by rohanpatelg** [comment]
> ### Issue you'd like to raise.
> This question may be stupid but I find nothing to refer to. I'm using langchain.chains.LLMChain in flask api, but I found that the chain will be reloaded and reconstructed if I call the api after a call. So the first question I wanna ask is how to make my LLMChain be remembered so that I can use it directly in the next call. I tried to use session in flask, but get `Object of type LLMChain is not JSON serializable`. Thanks.
> 
> ### Suggestion:
> _No response_

@RedNoseJJN  did you find any solution regarding this?

**Comment by LucasLee-ff** [comment]
> _🤖_
> 
> You're correct in your concern about the global LLMChain object in a multi-user Flask API environment. The LLMChain object is not thread-safe and can lead to race conditions if shared across multiple requests. Therefore, it's recommended to create a new instance of the LLMChain object for each user request to ensure that each user's interactions with the LLMChain are isolated and don't interfere with each other.
> 
> Here's an example of how you can do this in a Flask route:
> 
> ```python
> from flask import Flask, request
> from langchain.chains import LLMChain
> from langchain.llms import OpenAI
> from langchain_core.prompts import PromptTemplate
> 
> app = Flask(__name__)
> 
> @app.route('/generate', methods=['POST'])
> def generate():
>     data = request.get_json()
>     prompt_template = "Tell me a {adjective} joke"
>     prompt = PromptTemplate(
>         input_variables=["adjective"], template=prompt_template
>     )
>     llm = LLMChain(llm=OpenAI(), prompt=prompt)
>     result = llm.predict(adjective=data.get('adjective', 'funny'))
>     return {'result': result}
> ```
> 
> In this example, a new LLMChain object is created for each POST request to the '/generate' endpoint. The adjective for the joke is extracted from the request data, and the LLMChain object is used to generate a joke based on this adjective. The generated joke is then returned in the response.
> 
> As for initializing the LLMChain object, it takes two main parameters: `llm` and `prompt`. The `llm` parameter is the language model to call, and the `prompt` parameter is an instance of a class that inherits from `BasePromptTemplate`, which is used to format the prompt that will be passed to the language model. There are also other optional parameters that can be set when initializing an `LLMChain` object, such as `output_key`, `output_parser`, `return_final_only`, and `llm_kwargs`.
> 
> For more details, you can refer to the [LLMChain class in the LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/llm.py).
> 
> ## Sources
> * [libs/langchain/langchain/chains/llm.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/llm.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

The LLMChain object is not thread-safe, but what about the LLM object? Can I create a global LLM object and a global PromptTemplate object at the beginning, and only create new instance of the LLMChain object for each user request?
