### ISSUE TITLE
Add system_fingerprint in OpenAI callbacks

### ISSUE THREAD

**Issue by kennethleungty** [langchain-ai/langchain#13707]
### Feature request

Given that the seed is already in beta phase, the system_fingerprint would also be highly useful in tracking deterministic responses. Suggest to add a `system_fingerprint` as part of the callbacks. https://api.python.langchain.com/en/latest/callbacks/langchain.callbacks.openai_info.OpenAICallbackHandler.html#langchain.callbacks.openai_info.OpenAICallbackHandler

### Motivation

Given that the seed is already in beta phase, the system_fingerprint would also be highly useful

### Your contribution

Proposed suggestion

**Comment by kennethleungty** [comment]
This is specifically for the LangChain expression language

llm = ChatOpenAI(model=model_name, temperature=0, 
                 model_kwargs={"seed": cfg.OPENAI_LLM_SEED})
prompt = PromptTemplate.from_template(prompt_template)

chain = (
    prompt
    | llm
    | StrOutputParser())

output = chain.invoke({'topic': 'cats'})


Now the output is a string after invoke. Need to get system_fingerprint

**Comment by chris-boson** [comment]
Related? https://github.com/langchain-ai/langchain/issues/13177
