### ISSUE TITLE
get token count for other LLM Models 

### ISSUE THREAD

**Issue by VpkPrasanna** [langchain-ai/langchain#13719]
### Feature request

it could be better where i can add a callback to get the total token spend on other LLMS apart from OPENAI ?

### Motivation

since there is a call back for openai why don't we have for other models too just to see how much token is consumed ?

### Your contribution

Happy to contribute to the issue with PR later

**Comment by VpkPrasanna** [comment]
@dosubot is there any method presently available to get the total token spend on other models ?

**Comment by marosjev-cde** [comment]
Hello everyone, 

is there any new information on this topic? Or similar thread on github?

Thanks!
