### ISSUE TITLE
ChatML

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#1374]
[ChatML](https://github.com/openai/openai-python/blob/main/chatml.md) is the underlying format consumed by ChatGPT models. In the future, you will be able to interact with this format.

> Traditionally, GPT models consumed unstructured text. ChatGPT models instead expect a structured format, called Chat Markup Language (ChatML for short). ChatML documents consists of a sequence of messages. Each message contains a header (which today consists of who said it, but in the future will contain other metadata) and contents (which today is a text payload, but in the future will contain other datatypes). We are still evolving ChatML, but the current version (ChatML v0) can be represented with our upcoming "list of dicts" JSON format. --OpenAI team

Here's an example of [ChatML v0](https://github.com/openai/openai-python/blob/main/chatml.md):

```
[
 {"token": "<|im_start|>"},
 "system\nYou are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible.\nKnowledge cutoff: 2021-09-01\nCurrent date: 2023-03-01",
 {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
 "user\nHow are you",
 {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
 "assistant\nI am doing well!",
 {"token": "<|im_end|>"}, "\n", {"token": "<|im_start|>"},
 "user\nHow are you now?",
 {"token": "<|im_end|>"}, "\n"
]
```

Here are five ways to incorporate ChatML into LangChain:

1. **ChatML Pipeline Integration**: Integrate ChatML with LangChain for structured input/output processing in multi-turn conversations.
2. **ChatML-Assisted Model Chaining**: Combine ChatML and LangChain to enable seamless transitions between different LLMs in a conversation.
3. **ChatML-LangChain Grounded Agents**: Develop grounded agents using ChatML for structured interactions with users and APIs within LangChain.
4. **ChatML-Assisted Multi-Model Conversations**: Utilize ChatML and LangChain for building chat experiences that leverage multiple LLMs.
5. **ChatML-LangChain Development Tools**: Create tools and libraries to simplify building chatbot applications using both ChatML and LangChain.

**Comment by 44-5-53-6-k** [comment]
Does anyone want to collaborate on that?

**Comment by UnderTheCraft** [comment]
@44-5-53-6-k I'm interested. But I have to admit, that I'm fairly new to the LangChain Lib and therefore only know some stuff.
In case you are more experienced, we can have a look at it together in more detail. :)

**Comment by 44-5-53-6-k** [comment]
@UnderTheCraft I've talked with one person, and they said, conversation memory can actually use ChatML API under the hood, but I can't verify it yet. I will try to track how does it send the request

**Comment by UnderTheCraft** [comment]
@44-5-53-6-k ok, please keep me updated :)
