### ISSUE TITLE
_TextGenerationModel.predict() got an unexpected keyword argument 'functions'Issue: <Please write a comprehensive title after the 'Issue: ' prefix>

### ISSUE THREAD

**Issue by prajwalghadge07** [langchain-ai/langchain#13766]
### Issue you'd like to raise.

I  am trying to create a vertex ai and langchain based entity extraction program. I have stored my documents in form of vector embeddings in chromadb. I have been trying to extract the attributes/features like name, price, etc but whenever i run chains I'm getting this error.

**Comment by prajwalghadge07** [comment]
I'm trying to make it compatible with google cloud platform using vertex ai

**Comment by lkuligin** [comment]
Please, share a concise code snippet that reproduces the error.
