### ISSUE TITLE
Issue: how to access to cached question and answer in InMemoryCache

### ISSUE THREAD

**Issue by reddiamond1234** [langchain-ai/langchain#13778]
### Issue you'd like to raise.

InMemoryCache works, but it doesn't print to stderr like all other LLM responses. I checked logs and response is stored. I don't know how to access to this stored values...

### Suggestion:

option to view object or option to return values.

**Comment by keenborder786** [comment]
@reddiamond1234 You can get the underlying cache storage object as follow:

Prehaps you can give a snippet of your code so that I can help you in a better way.

```python
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.schema.runnable import RunnableLambda
from langchain.globals import set_llm_cache
from langchain.cache import InMemoryCache
cache_instance = InMemoryCache()

set_llm_cache(cache_instance)

import os
os.environ['OPENAI_API_KEY'] = ''
model = ChatOpenAI()
prompt = ChatPromptTemplate.from_template("tell me a joke about {topic}")

def strip(output:str) -> str:
    return output.content


chain = prompt | model | RunnableLambda(strip)
print(chain.invoke({"topic":"coding"}))
print(chain.invoke({"topic":"coding"}))
print(cache_instance._cache)

```

**Comment by reddiamond1234** [comment]
@keenborder786 i am not using LCEL... Here is my code for RAG (with Chroma):

def pipeline():
             
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name, model_kwargs=kwargs)

    # database 
    db = Chroma(
        persist_directory=persist_directory, 
        embedding_function=embeddings,
        client_settings=Settings(chroma_db_impl='duckdb+parquet', persist_directory=persist_directory, anonymized_telemetry=False)
        )
    
    retriever = db.as_retriever(search_kwargs={"k": target_source_chunks}, score_threshold=0.75, lambda_mult=0.5) 
    
    prompt_template_chat = """<SYS>\nYou are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Please ensure that your responses are socially unbiased and positive in nature.\n</SYS>
    \n\n
    [INST]Think step by step. Answer only for question within the context (delimited by <ctx></ctx>) provided, otherwise say you don't have right context to answer the question. Don't answer to question with your knowledge or add it to answer based on context provided. Answer in language asked. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information and say you don't know. Make sure to answer in few sentences with only relevant information.
    \n
    <ctx>{context}</ctx>
    \n
    Question: {question}
    \n
    Answer in English:[/INST]""" 

    PROMPT = PromptTemplate(
        template=prompt_template_chat, 
        input_variables=["context", "question"],
    )

    chain_type_kwargs = {"prompt": PROMPT}
    
    qa = RetrievalQA.from_chain_type(
        llm=llm, 
        chain_type="stuff",
        retriever=retriever,
        chain_type_kwargs=chain_type_kwargs,
        return_source_documents= True,
    )

    try:
        while True:
           
            query = input("\n") # get question from keyboard
             
            query = query.strip()    # remove spaces at the start/end of string
            
            if query.strip() == "": # prevent empty string
                continue   

            query = "based on given context, " + query
          
            # Get the answer from the chain
            res = qa({"query":query}) 

            logger.info(res)   

    except:
        exit(1)

**Comment by reddiamond1234** [comment]
> I hope this helps. Let me know if it works for you.

sorry for late reply... It works. Thank you.

**Comment by jyoti194** [comment]
Hi @reddiamond1234 @keenborder786 I created a chatbot which interact with MS SQL database in natural language and fetch the data, i have a new requirement where the search history question should be displayed while we go on the question tab, can it be done throw langchain framework or any other method.

**Comment by jyoti194** [comment]
@keenborder786 @reddiamond1234 

i want to include the cache memory in my code where im using SQLDatabaseChain to interact with the sql db, here below is my code, can u guide me with it

from urllib.parse import quote_plus
server_name = constants.server_name
database_name = constants.database_name
username = constants.username 
password = constants.password
encoded_password = quote_plus(password)
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

# Create an engine to connect to the SQL database
engine = create_engine(connection_uri)

model_name="gpt-3.5-turbo-16k"
db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT'])

llm = ChatOpenAI(temperature=0, verbose=False, model=model_name) 

PROMPT_SUFFIX = """Only use the following tables:
{table_info}
Previous Conversation:
{history}
Question: {input}"""

_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, 
then look at the results of the query and return the answer. 
Given an input question, create a syntactically correct MSSQL query by considering only the matching column names from the question, 
then look at the results of the query and return the answer.
If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not present do not consider such columns.
Write the query only for the column names which are present in view. 
Execute the query and analyze the results to formulate a response. 
Return the answer in sentence form.

Use the following format:

Question: "Question here"
SQLQuery: "SQL Query to run"
SQLResult: "Result of the SQLQuery"
Answer: "Final answer here"

"""

PROMPT = PromptTemplate.from_template(_DEFAULT_TEMPLATE + PROMPT_SUFFIX)
    
memory = None
cache = InMemoryCache()



# Define a function named chat that takes a question and SQL format indicator as input
def chat1(question):
    
    # global db_chain

    global memory
    
    
    # try: 
    if memory == None:
        
        memory = ConversationBufferMemory()
        
    db_chain = SQLDatabaseChain.from_llm(llm, db, prompt=PROMPT, verbose=True, memory=memory)
    llm_string = str(db_chain)
        

    greetings = ["hi", "hello", "hey"]

    if any(greeting == question.lower() for greeting in greetings):
        print(question)
        print("Hello! How can I assist you today?")
        return "Hello! How can I assist you today?"
    
    else:
            # Use the lookup method to check if the question is in the cache
            cached_answer = cache.lookup(question, llm_string)
            if cached_answer is not None:
                return cached_answer 
            else:
                answer = db_chain.run(question)
                cache[question] = answer  # Store the answer in the cache
                history = memory.load_memory_variables()["history"]
                print(history)
                return answer

    
    # except exc.ProgrammingError as e:
    #     # Check for a specific SQL error related to invalid column name
    #     if "Invalid column name" in str(e):
    #         print("Answer: Error Occured while processing the question")
    #         print(str(e))
    #         return "Invalid question. Please check your column names."
        
    #     else:
    #         print("Error Occured while processing")
    #         print(str(e))
    #         return "Unknown ProgrammingError Occured"
          
        
    # except openai.RateLimitError as e:
    #     print("Error Occured while fetching the answer")
    #     print(str(e))
    #     return "Rate limit exceeded. Please, Mention the Specific Columns you need!"
    
    # except openai.BadRequestError as e:
    #     print("Error Occured while fetching the answer")
    #     print(str(e))
        
        
    #     return "Context length exceeded: This model's maximum context length is 16385 tokens. Please reduce the length of the messages."
        
    # except Exception as e:
    #     print("Error Occured while processing")
    #     print(str(e))
    #     return "Unknown Error Occured"
