### ISSUE TITLE
Issue: Conversational retrieval chain, response_if_no_docs_found not working

### ISSUE THREAD

**Issue by JoAmps** [langchain-ai/langchain#13771]
### Issue you'd like to raise.

It stated in the docs that there's a parameter called response_if_no_docs_found, which If specified, the chain will return a fixed response if no docs 
    are found for the question.

I have tried it and asked another person, who says they tried it and it doesn't work, 
how do i get it to work
because its a very important aspect

**Comment by JoAmps** [comment]
But the thing is, no matter the question asked, there would be docs retrieved, because it needs to retrieve the docs to check if the question is feasible, so even if it is a question that is not relevant, there would be docs retrieved,
so in what situation would this  response_if_no_docs_found be met?

**Comment by sglebs** [comment]
> But the thing is, no matter the question asked, there would be docs retrieved, because it needs to retrieve the docs to check if the question is feasible, so even if it is a question that is not relevant, there would be docs retrieved, so in what situation would this response_if_no_docs_found be met?

@JoAmps In my usage I can see that if no docs match the minimum score provided (e.g. 0.85) then no docs would be returned. So, " even if it is a question that is not relevant, there would be docs retrieved" is not accurate. At least in my experiments.
