### ISSUE TITLE
Azure OpenAI (with openai module 1.x.x) seems not working anymore

### ISSUE THREAD

**Issue by solyarisoftware** [langchain-ai/langchain#13785]
### System Info

$ python3 --version
Python 3.11.6

$ pip show openai | grep Version
Version: 1.3.5

$ pip show langchain | grep Version
Version: 0.0.340

### Who can help?

Who wants to use AzureOpenai deployments with langchain, enabling last openai package versione 1.x.x. 

### Information

- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models

### Reproduction

Hi @hwchase17, @agola11, all!
Thanks in advance for your huge work.

I so far successfully used langchain with the openai module 0.28.x. 
Today I upgraded the openai package to the latest version (1.x.x), and I installed also the latest langchain package version.

I configured the environment variables (as described above) and I run the following simple program, as described in langchain documentation: https://python.langchain.com/docs/integrations/chat/azure_chat_openai

```
$ source path/.langchain_azure.env
$ cat path/.langchain_azure.env
# https://python.langchain.com/docs/integrations/llms/azure_openai

export OPENAI_API_TYPE=azure
export OPENAI_API_VERSION=2023-09-01-preview
export AZURE_OPENAI_ENDPOINT="https://xxxxxxxxxxx.openai.azure.com/"
export AZURE_OPENAI_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

Program that generate a run-time exception:
```python
# langchain_simple.py
# this example follows the langchain documentation example at: https://python.langchain.com/docs/integrations/chat/azure_chat_openai
import os

from langchain.chat_models import AzureChatOpenAI
from langchain.schema import HumanMessage

model = AzureChatOpenAI(
    openai_api_version="2023-05-15",
    azure_deployment="gpt-35-turbo" # my existing deployment name
)

message = HumanMessage(content="Translate this sentence from English to French. I love programming.")
model([message])
```

I got the following exception:

```
$ py langchain_simple.py
/home/giorgio/.local/lib/python3.11/site-packages/langchain/chat_models/azure_openai.py:162: UserWarning: As of openai>=1.0.0, if `deployment_name` (or alias `azure_deployment`) is specified then `openai_api_base` (or alias `base_url`) should not be. Instead use `deployment_name` (or alias `azure_deployment`) and `azure_endpoint`.
  warnings.warn(
/home/giorgio/.local/lib/python3.11/site-packages/langchain/chat_models/azure_openai.py:170: UserWarning: As of openai>=1.0.0, if `openai_api_base` (or alias `base_url`) is specified it is expected to be of the form https://example-resource.azure.openai.com/openai/deployments/example-deployment. Updating https://openai-convai.openai.azure.com/ to https://openai-convai.openai.azure.com/.
  warnings.warn(
Traceback (most recent call last):
  File "/home/giorgio/gpt/langchain/langchain_simple.py", line 9, in <module>
    model = AzureChatOpenAI(
            ^^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/giorgio/.local/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureChatOpenAI
__root__
  base_url and azure_endpoint are mutually exclusive (type=value_error)
```

BTW, I do not understand exactly the error sentence:
```base_url and azure_endpoint are mutually exclusive (type=value_error)```

Where am I wrong?
Thanks 
Giorgio

### Expected behavior

I didn't expect to have run-time errors

**Comment by solyarisoftware** [comment]
I think this problem is totally unrelated to the embeddings.  In fact I discovered the origin of the problem that's caused by a "conflict" in some environment variables. Specifically `OPENAI_*` and `AZURE_*`.

if I set:

```bash
export AZURE_OPENAI_ENDPOINT="https://xxxxxxxxxxx.openai.azure.com/"
export AZURE_OPENAI_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

```

WHITOUT having any `OPENAI_*` variabls set, then all works fine (as described in the langchain documentation: https://python.langchain.com/docs/integrations/chat/azure_chat_openai

See:
 
```python
# test_issue.py
import os

from langchain.chat_models import AzureChatOpenAI
from langchain.schema import SystemMessage, HumanMessage
from langchain.callbacks import get_openai_callback

# check the os environment variable settings
azure_openai_api_key = os.environ["AZURE_OPENAI_API_KEY"]
azure_openai_endpoint = os.environ["AZURE_OPENAI_ENDPOINT"]

llm = AzureChatOpenAI(
    openai_api_version="2023-09-01-preview",
    azure_deployment="gpt-35-turbo",
    model_name="gpt3.5-turbo"
)


messages = [
    SystemMessage(
        content=(
            "You are ExpertGPT, an AGI system capable of "
            "anything except answering questions about cheese. "
            "It turns out that AGI does not fathom cheese as a "
            "concept, the reason for this is a mystery."
        )
    ),
    HumanMessage(content="Tell me about parmigiano, the Italian cheese!")
]

with get_openai_callback() as cb:

    res = llm(messages)

    # print the response
    print(res.content)

    # print the total tokens used
    print(cb.total_tokens)

```

When I run the above program, I obtain:

```
I'm sorry, I am an AGI system that is not capable of answering questions about cheese, including parmigiano. This is due to the fact that AGI systems do not have personal experiences or sensory perceptions that would allow them to comprehend the taste, texture, or appearance of food items like cheese. Is there anything else I can assist you with?
138
```

But the problem comes up when some `OPENAI_*` are set (maybe `OPENAI_API_BASE`).

So , even if in practice I solved my particular issue, just removing all `OPENAI_*` OS vars already set in my host and used any other programs not using langchain library, I think langchain documentation could be more clear and currently misleading:  

There is a inconsistency between what said 

in this page:
https://python.langchain.com/docs/integrations/chat/azure_chat_openai

and in this page:
https://python.langchain.com/docs/integrations/llms/azure_openai

Specifically, the chapter:  https://python.langchain.com/docs/integrations/llms/azure_openai#api-configuration contains maybe obsolete info regarding OS environment variable settings and it could be updated/corrected.

For this reason I'd keep open this issue #13785

What do you think?
Thanks 
giorgio

**Comment by kphillipsjr1101** [comment]
Looks like in embeddings/azure_openai.py where it defines the client parameters at the end, it is setting the value of base_url to the value of the endpoint provided. It appears that the value is set in the client to the same value as the expected azure_endpoint which then leads to the raised error regarding the mutual exclusivity.

As a workaround until an official fix is put in place, you can simply comment out the client initialization line for the base_url which avoids the conflict.
![image](https://github.com/langchain-ai/langchain/assets/12927297/9d2d0410-1299-46ec-b6d8-15cec7403285)

**Comment by kphillipsjr1101** [comment]
My apologies, look like I misread the issue and assumed it was affecting the AzureOpenAI Embeddings class as I was troubleshooting some issues with it and found this post in my searches. I see that this is specifically for the Chat Model.

**Comment by ingridstevens** [comment]
I had the same issue of this error message: `base_url and azure_endpoint are mutually exclusive (type=value_error)`  when using `openai==1.6.1` and the Azure Endpoint.

***Fixed it by removing all OPENAI_* environment variables (thanks to @solyarisoftware for the fix)**

Now my env variables are named: 

```
AZURE_OPENAI_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxx
AZURE_OPENAI_ENDPOINT=https://xxxxxxxxxx.openai.azure.com/
```

(I had to restart VSCode for the changes to take into effect)

**Comment by Nziranziza** [comment]
I had to set the following environment variables for this to work

```
OPENAI_API_VERSION=
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_ENDPOINT=
```

**Comment by JAIS0N** [comment]
> Looks like in embeddings/azure_openai.py where it defines the client parameters at the end, it is setting the value of base_url to the value of the endpoint provided. It appears that the value is set in the client to the same value as the expected azure_endpoint which then leads to the raised error regarding the mutual exclusivity.
> 
> As a workaround until an official fix is put in place, you can simply comment out the client initialization line for the base_url which avoids the conflict. ![image](https://private-user-images.githubusercontent.com/12927297/285992270-9d2d0410-1299-46ec-b6d8-15cec7403285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzUwNjcsIm5iZiI6MTcwNzk3NDc2NywicGF0aCI6Ii8xMjkyNzI5Ny8yODU5OTIyNzAtOWQyZDA0MTAtMTI5OS00NmVjLWI2ZDgtMTVjZWM3NDAzMjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA1MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYTFiMWUyNWQ1MzdkYzFhMjNkYmU0NGNjMjgyMDZjN2Q3ZWRkOTE3MDY4MzU0NzM3Mjg1MzZhMmFlMTMyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vMNcZl472X9dYIuUje1uRqsUN7K0sVLwYUfs8KJB5H8)

Even after commenting base URL facing the same issue
 "As of openai>=1.0.0, Azure endpoints should be specified via the `azure_endpoint` param not `openai_api_base` (or alias `
base_url`).  (type=value_error)"

OpenAI version 1.6.1

**Comment by JAIS0N** [comment]
> ### System Info
> $ python3 --version Python 3.11.6
> 
> $ pip show openai | grep Version Version: 1.3.5
> 
> $ pip show langchain | grep Version Version: 0.0.340
> 
> ### Who can help?
> Who wants to use AzureOpenai deployments with langchain, enabling last openai package versione 1.x.x.
> 
> ### Information
> * [x]  My own modified scripts
> 
> ### Related Components
> * [x]  LLMs/Chat Models
> 
> ### Reproduction
> Hi @hwchase17, @agola11, all! Thanks in advance for your huge work.
> 
> I so far successfully used langchain with the openai module 0.28.x. Today I upgraded the openai package to the latest version (1.x.x), and I installed also the latest langchain package version.
> 
> I configured the environment variables (as described above) and I run the following simple program, as described in langchain documentation: https://python.langchain.com/docs/integrations/chat/azure_chat_openai
> 
> ```
> $ source path/.langchain_azure.env
> $ cat path/.langchain_azure.env
> # https://python.langchain.com/docs/integrations/llms/azure_openai
> 
> export OPENAI_API_TYPE=azure
> export OPENAI_API_VERSION=2023-09-01-preview
> export AZURE_OPENAI_ENDPOINT="https://xxxxxxxxxxx.openai.azure.com/"
> export AZURE_OPENAI_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> ```
> 
> Program that generate a run-time exception:
> 
> ```python
> # langchain_simple.py
> # this example follows the langchain documentation example at: https://python.langchain.com/docs/integrations/chat/azure_chat_openai
> import os
> 
> from langchain.chat_models import AzureChatOpenAI
> from langchain.schema import HumanMessage
> 
> model = AzureChatOpenAI(
>     openai_api_version="2023-05-15",
>     azure_deployment="gpt-35-turbo" # my existing deployment name
> )
> 
> message = HumanMessage(content="Translate this sentence from English to French. I love programming.")
> model([message])
> ```
> 
> I got the following exception:
> 
> ```
> $ py langchain_simple.py
> /home/giorgio/.local/lib/python3.11/site-packages/langchain/chat_models/azure_openai.py:162: UserWarning: As of openai>=1.0.0, if `deployment_name` (or alias `azure_deployment`) is specified then `openai_api_base` (or alias `base_url`) should not be. Instead use `deployment_name` (or alias `azure_deployment`) and `azure_endpoint`.
>   warnings.warn(
> /home/giorgio/.local/lib/python3.11/site-packages/langchain/chat_models/azure_openai.py:170: UserWarning: As of openai>=1.0.0, if `openai_api_base` (or alias `base_url`) is specified it is expected to be of the form https://example-resource.azure.openai.com/openai/deployments/example-deployment. Updating https://openai-convai.openai.azure.com/ to https://openai-convai.openai.azure.com/.
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/giorgio/gpt/langchain/langchain_simple.py", line 9, in <module>
>     model = AzureChatOpenAI(
>             ^^^^^^^^^^^^^^^^
>   File "/home/giorgio/.local/lib/python3.11/site-packages/langchain/load/serializable.py", line 97, in __init__
>     super().__init__(**kwargs)
>   File "/home/giorgio/.local/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
>     raise validation_error
> pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureChatOpenAI
> __root__
>   base_url and azure_endpoint are mutually exclusive (type=value_error)
> ```
> 
> BTW, I do not understand exactly the error sentence: `base_url and azure_endpoint are mutually exclusive (type=value_error)`
> 
> Where am I wrong? Thanks Giorgio
> 
> ### Expected behavior
> I didn't expect to have run-time errors

What change you did to solve this? You anyway werent using any OPENAI_ variables version is necessary

**Comment by JAIS0N** [comment]
> export OPENAI_API_TYPE=azure
> export OPENAI_API_VERSION=2023-09-01-preview

Arent these two necessary ?

**Comment by JAIS0N** [comment]
> I think this problem is totally unrelated to the embeddings. In fact I discovered the origin of the problem that's caused by a "conflict" in some environment variables. Specifically `OPENAI_*` and `AZURE_*`.
> 
> Now, following what is described in the langchain documentation: https://python.langchain.com/docs/integrations/chat/azure_chat_openai
> 
> 1 I set:
> 
> ```shell
> export AZURE_OPENAI_ENDPOINT="https://xxxxxxxxxxx.openai.azure.com/"
> export AZURE_OPENAI_API_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
> ```
> 
> WHITOUT having any `OPENAI_*` variables set.
> 
> 2 I run the test program:
> 
> ```python
> # test_issue.py
> import os
> 
> from langchain.chat_models import AzureChatOpenAI
> from langchain.schema import SystemMessage, HumanMessage
> from langchain.callbacks import get_openai_callback
> 
> # check the os environment variable settings
> azure_openai_api_key = os.environ["AZURE_OPENAI_API_KEY"]
> azure_openai_endpoint = os.environ["AZURE_OPENAI_ENDPOINT"]
> 
> llm = AzureChatOpenAI(
>     openai_api_version="2023-09-01-preview",
>     azure_deployment="gpt-35-turbo",
>     model_name="gpt3.5-turbo"
> )
> 
> 
> messages = [
>     SystemMessage(
>         content=(
>             "You are ExpertGPT, an AGI system capable of "
>             "anything except answering questions about cheese. "
>             "It turns out that AGI does not fathom cheese as a "
>             "concept, the reason for this is a mystery."
>         )
>     ),
>     HumanMessage(content="Tell me about parmigiano, the Italian cheese!")
> ]
> 
> with get_openai_callback() as cb:
> 
>     res = llm(messages)
> 
>     # print the response
>     print(res.content)
> 
>     # print the total tokens used
>     print(cb.total_tokens)
> ```
> 
> 3 When I run the above program, I obtain the expected output:
> 
> ```
> I'm sorry, I am an AGI system that is not capable of answering questions about cheese, including parmigiano. This is due to the fact that AGI systems do not have personal experiences or sensory perceptions that would allow them to comprehend the taste, texture, or appearance of food items like cheese. Is there anything else I can assist you with?
> 138
> ```
> 
> But exception above reported comes up when some `OPENAI_*` are set (maybe `OPENAI_API_BASE`).
> 
> So , even if in practice I solved my particular issue, just removing all `OPENAI_*` OS vars already set in my host and used any other programs not using langchain library, I think langchain documentation could be more clear and currently misleading:
> 
> There is a inconsistency between what said
> 
> in this page: https://python.langchain.com/docs/integrations/chat/azure_chat_openai
> 
> and in this page: https://python.langchain.com/docs/integrations/llms/azure_openai
> 
> Specifically, the chapter: https://python.langchain.com/docs/integrations/llms/azure_openai#api-configuration contains maybe obsolete info regarding OS environment variable settings and it could be updated/corrected.
> 
> For this reason I'd keep open this issue #13785
> 
> What do you think? Thanks giorgio

**This didn't work**
`#os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["AZURE_OPENAI_ENDPOINT"] = "https://kxxxxxxxxt.openai.azure.com/"
#os.environ["OPENAI_API_VERSION"] = "2023-09-15-preview"
os.environ["AZURE_OPENAI_API_KEY"] = "xxxxxxxxxxxxxxxxxxxxxxx"

As you can see I excluded OPENAI_API_TYPE and OPENAI_API_VERSION but is still facing `embeddings = AzureOpenAIEmbeddings(azure_deployment="text-embedding-ada-002",openai_api_version="2023-03-15-preview")
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
__root__
  base_url and azure_endpoint are mutually exclusive (type=value_error)`
`
also restarted VScode as per @ingridstevens suggestions no avail

**Comment by JAIS0N** [comment]
After removing version facing openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by jdeepak-4u** [comment]
Use AzureOpenAIEmbeddings...for more details refer below.

https://python.langchain.com/docs/integrations/text_embedding/azureopenai

**Comment by khordoo-m** [comment]
I had the same issue. Have to delete the OpenAI Key frmo the enviromanl varibale lists to Make it works :
```
os.environ.pop('OPENAI_API_BASE',None)
AZURE_OPENAI_API_KEY=YourKEY
AZURE_OPENAI_ENDPOINT=YOUR ENDPOUNT
```
