### ISSUE TITLE
How to add json_object to ChatOpenAI class?

### ISSUE THREAD

**Issue by paolomagnani-mxm** [langchain-ai/langchain#13783]
### Issue you'd like to raise.

How can I add the new parameter **JSON MODE** ( https://platform.openai.com/docs/guides/text-generation/json-mode )
to this snippet of code?
```python
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(
            model_name="gpt-3.5-turbo-1106",
            temperature=1,
            max_tokens=None
)
```

I see in openai it should be used in this way:
```python
response = client.chat.completions.create(
  model="gpt-3.5-turbo-1106",
  response_format={ "type": "json_object" },
  messages=[
    {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
    {"role": "user", "content": "Who won the world series in 2020?"}
  ]
)
```

Thanks!!

**Comment by ms-mousa** [comment]
I see it can be in JS version like so 
```javascript
// Coerce response type with JSON mode.
// Requires "gpt-4-1106-preview" or later
const jsonModeModel = new ChatOpenAI({
  modelName: "gpt-4-1106-preview",
  maxTokens: 128,
}).bind({
  response_format: {
    type: "json_object",
  },
});
```
From here https://github.com/langchain-ai/langchainjs/issues/3226#issuecomment-1805905999

I'm also curious how this can be done in python side

**Comment by paolomagnani-mxm** [comment]
Thanks @ForrestTrepte this seems to work!
Anyway I have a problem with some functions that I used before passing the `json_obejct`.

Indeed before use the method [get_num_tokens_from_messages](https://api.python.langchain.com/en/latest/llms/langchain.llms.openai.OpenAI.html#langchain.llms.openai.OpenAI.get_num_tokens_from_messages):
```python
chat.get_num_tokens_from_messages(messages)
```
([this method](https://api.python.langchain.com/en/latest/llms/langchain.llms.openai.OpenAI.html#langchain.llms.openai.OpenAI.get_num_tokens_from_messages))

to check the number of the tokens before running the LLM, but now with the binding, it says:

```
AttributeError: 'RunnableBinding' object has no attribute 'get_num_tokens_from_messages'
```

**Comment by devhe4d** [comment]
can we define what JSON schema is desired for us to return? for example I want to set it to return a custom schema

**Comment by blacksmithop** [comment]
> can we define what JSON schema is desired for us to return? for example I want to set it to return a custom schema

See [Pydantic parser](https://python.langchain.com/docs/modules/model_io/output_parsers/types/pydantic)
