### ISSUE TITLE
how to handle a PDF(including tables..)

### ISSUE THREAD

**Issue by girlsending0** [langchain-ai/langchain#13805]
### Issue you'd like to raise.

Hello
I have to configure the langchain with PDF data, and the PDF contains a lot of unstructured table.
We have a string and a table, so how do you recommend handling it?

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> Hello @girlsending0! Nice to see you again. I hope your project is going well. Let's take a look at your new issue.
> 
> To handle PDF data in LangChain, you can use one of the provided PDF parsers. These parsers include `PDFMinerParser`, `PDFPlumberParser`, `PyMuPDFParser`, `PyPDFium2Parser`, and `PyPDFParser`.
> 
> For unstructured tables and strings, you might find `PDFPlumberParser` or `PDFMinerParser` useful as they are known for their capabilities in handling such data.
> 
> Here's how you can import and use one of these parsers:
> 
> ```python
> from langchain.document_loaders.parsers.pdf import PDFPlumberParser
> 
> # Initialize the parser
> parser = PDFPlumberParser()
> 
> # Load your PDF data
> data = parser.load('path_to_your_pdf_file')
> 
> # Now you can process the data
> processed_data = parser.process(data)
> ```
> 
> Please replace `'path_to_your_pdf_file'` with the actual path to your PDF file. The `load` method reads the PDF file, and the `process` method processes the loaded data.
> 
> Please note that the actual methods and their usage might vary depending on the parser. The above code is a general example and might not work as is. Please refer to the specific parser's documentation or source code for exact usage details.
> 
> LangChain provides several PDF parsers, each with its own capabilities and handling of unstructured tables and strings:
> 
> 1. `PyPDFParser`: This parser uses the `pypdf` library to extract text from PDF files. It can also extract images from the PDF if the `extract_images` parameter is set to `True`. The images are then processed with RapidOCR to extract any text. This parser does not have specific handling for unstructured tables and strings.
> 2. `PDFMinerParser`: This parser uses the `PDFMiner` library. It can concatenate all PDF pages into a single document or return one document per page based on the `concatenate_pages` parameter. It can also extract images and process them with RapidOCR. This parser does not have specific handling for unstructured tables and strings.
> 3. `PyMuPDFParser`: This parser uses the `PyMuPDF` library. It can extract text and images (processed with RapidOCR) from PDF files. It does not have specific handling for unstructured tables and strings.
> 4. `PyPDFium2Parser`: This parser uses the `PyPDFium2` library. It can extract text and images (processed with RapidOCR) from PDF files. It does not have specific handling for unstructured tables and strings.
> 5. `PDFPlumberParser`: This parser uses the `PDFPlumber` library. It can extract text and images (processed with RapidOCR) from PDF files. It also has a `dedupe` parameter that can be used to avoid duplicate characters.
> 6. `AmazonTextractPDFParser`: This parser uses the `Amazon Textract` service. It can process both single and multi-page documents, and supports JPEG, PNG, TIFF, and non-native PDF formats. It can also linearize the output, formatting the text in reading order and outputting information in a tabular structure or outputting key/value pairs with a colon (key: value). This can help language models achieve better accuracy when processing these texts.
> 
> In summary, all parsers can extract text and optionally images from PDF files, but they do not have specific capabilities for handling unstructured tables and strings, except for the `AmazonTextractPDFParser` which can linearize the output.
> 
> You can find more details about these parsers in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/parsers/pdf.py).
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> ## Sources
> * [feat: Add Linearized output to Textract PDFLoader](https://github.com/langchain-ai/langchain/issues/12068)
> * [libs/langchain/langchain/document_loaders/parsers/**init**.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/parsers/__init__.py)
> * [libs/langchain/langchain/document_loaders/parsers/pdf.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/parsers/pdf.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
what else I need to do for fetching unstructured table in pdf into some meaning ful format?
        loader = PyPDFLoader(file_path)
        document = loader.load()
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
        texts = text_splitter.split_documents(documents=document)

**Comment by deepak-habilelabs** [comment]
@girlsending0 did above asked query resolved by you?

**Comment by girlsending0** [comment]
@deepak-habilelabs no... that's very simple answer...
can you solve these problem?

**Comment by deepak-habilelabs** [comment]
> @deepak-habilelabs no... that's very simple answer... can you solve these problem?

No till now, can u pls assist me in solving these?
        loader = PyPDFLoader(file_path)
        document = loader.load()
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
        texts = text_splitter.split_documents(documents=document)
       How can I further proceed?

**Comment by pranjaldoshi96** [comment]
Please add the solution here. This looks like a tricky thing to do, if somehow this loader identifies this tables/charts and extract it's meaning and convert it into string explaining it, generate embedding and then interact with it. 

Not sure how a simple loader will do that though.

**Comment by deepak-habilelabs** [comment]
> Please add the solution here. This looks like a tricky thing to do, if somehow this loader identifies this tables/charts and extract it's meaning and convert it into string explaining it, generate embedding and then interact with it.
> 
> Not sure how a simple loader will do that though.

@pranjaldoshi96 did any one try UnstructuredPDFLoader?

> @dosu-bot.
> 
> Is [extracting images](https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf#extracting-images) from pdf feature available in langchain js version as well, or is this something that can be done only with python version ?

@riturajgc for extracting images from pdf, u simply have to set a parameter " extract_images=True" in pypdf loader

**Comment by deepak-habilelabs** [comment]
https://medium.com/@knowledgrator/extract-custom-table-from-pdf-with-llms-2ad678c26200
just give it a try, I hope this also works for you all :))
