### ISSUE TITLE
Langchain Database Agent with local LLM

### ISSUE THREAD

**Issue by dinonovak** [langchain-ai/langchain#13826]
I am using local LLM with langchain: openhermes-2.5-mistral-7b.Q8_0.gguf

When using database agent this is how I am initiating things:

`db = SQLDatabase.from_uri(sql_uri)

model_path = "./openhermes-2.5-mistral-7b.Q8_0.gguf"

n_gpu_layers = 1 # Change this value based on your model and your GPU VRAM pool.
n_batch = 512 # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.
n_ctx=50000
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

llm = LlamaCpp(
    model_path=model_path,
    #temperature=0,
    n_gpu_layers=n_gpu_layers, n_batch=n_batch, 
    n_ctx=n_ctx,
    callback_manager=callback_manager, 
    verbose=True,
)

#toolkit = CustomSQLDatabaseToolkit(db=db, llm=llm)
toolkit = SQLDatabaseToolkit(db=db, llm=llm)
toolkit.get_tools()

PREFIX = '''You are a SQL expert. You have access to a Microsoft SQL Server database.
            Identify which tables can be used to answer the user's question and write and execute a SQL query accordingly.
         '''

FORMAT_INSTRUCTIONS = """RESPONSE FORMAT INSTRUCTIONS
----------------------------

When responding please, please output a response in this format:

thought: Reason about what action to take next, and whether to use a tool.
action: The tool to use. Must be one of: {tool_names}
action_input: The input to the tool

For example:

thought: I need to get all tables from database
action: sql_db_list_tables
action_input: Empty string
"""

agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True,
    agent_kwargs={
                  'prefix': PREFIX, 
                  'format_instructions': FORMAT_INSTRUCTIONS,
                  }
)

now = datetime.datetime.now()
print("Starting executor : ")
print(now.strftime("%Y-%m-%d %H:%M:%S"))

agent_executor.run("Who is oldest user")`

When Entering chain I usually get error "Could not parse LLM output" as despite the instructions Action Input part is not created by LLM.

> Entering new AgentExecutor chain...
Action: sql_db_list_tables
Traceback (most recent call last):
  File "/Users/dino/Codings/python/LLM_test1/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 1032, in _take_next_step
    output = self.agent.plan(
  File "/Users/dino/Codings/python/LLM_test1/.venv/lib/python3.9/site-packages/langchain/agents/agent.py", line 636, in plan
    return self.output_parser.parse(full_output)
  File "/Users/dino/Codings/python/LLM_test1/.venv/lib/python3.9/site-packages/langchain/agents/mrkl/output_parser.py", line 70, in parse
    raise OutputParserException(
langchain.schema.output_parser.OutputParserException: Could not parse LLM output: `Action: sql_db_list_tables`

Any Idea how to fix this ?

**Comment by dinonovak** [comment]
Unfortunately, looks like suggested solution is not working.
Could you please help with where exactly proposed code needs to be added, as after adding it is not triggered.

**Comment by dinonovak** [comment]
I have adjusted agent_executor declaration:
`agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    #agent_type=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION, //not supported ?
    verbose=True,
	  agent_executor_kwargs={"handle_parsing_errors": True},
    handle_parsing_errors=True,
    agent_kwargs={
                  'prefix': PREFIX, 
                  'format_instructions': FORMAT_INSTRUCTIONS,
				          'suffix': SUFFIX
                  }
)`

This seems to trigger fallback as now chain does not error immediately, bt still looks like openhermes-2.5-mistral-7b.Q8_0.gguf still is not creating required format of message.

> Entering new AgentExecutor chain...
Action: sql_db_list_tablesAction: sql_db_list_tables
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to specify an input for the action.
Action: sql_db_list_tables, [empty string] I need to specify an input for the action.
Action: sql_db_list_tables, [empty string]
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to provide an empty string as the input.
Action: sql_db_list_tables, '' I need to provide an empty string as the input.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to specify an input for the action.
Action: sql_db_list_tables, '' I need to specify an input for the action.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to provide an empty string as the input.
Action: sql_db_list_tables, '' I need to provide an empty string as the input.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to specify an input for the action.
Action: sql_db_list_tables, '' I need to specify an input for the action.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to provide an empty string as the input.
Action: sql_db_list_tables, '' I need to provide an empty string as the input.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to specify an input for the action.
Action: sql_db_list_tables, '' I need to specify an input for the action.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to provide an empty string as the input.
Action: sql_db_list_tables, '' I need to provide an empty string as the input.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to specify an input for the action.
Action: sql_db_list_tables, '' I need to specify an input for the action.
Action: sql_db_list_tables, ''
Observation: Invalid Format: Missing 'Action Input:' after 'Action:'
Thought: I need to provide an empty string as the input.

This is how llm is instructed, could it be the case that this should be defined somewhere else as to me it seems that it is ignored completely?

`PREFIX = '''You are a SQL expert. You have access to a Microsoft SQL Server database.
            Identify which tables can be used to answer the user's question and write and execute a SQL query accordingly.
         '''

FORMAT_INSTRUCTIONS = """RESPONSE FORMAT INSTRUCTIONS
----------------------------

When responding please, please output a response in this format:

thought: Reason about what action to take next, and whether to use a tool.
action: The tool to use. 
action_input: The input to the tool

For example:

thought: I need to get all tables from database
action: sql_db_list_tables
action_input: Empty string
"""

SUFFIX = ' Begin!'`

**Comment by RyanmaxinWSIB** [comment]
Hi, I just wanted to let you know I've been struggling with the same issues. I don't have an exact answer to your problem, but I will note that this model is working for me pretty well:

https://huggingface.co/TheBloke/Nous-Hermes-Llama2-70B-GGUF

You can also try the 7B or 13B versions depending on how strong your hardware is, but I'm not sure how good the results will be.

**Comment by guitmonk-1290** [comment]
@RyanmaxinWSIB Have you used this model with the SQL agent from langchain?
