### ISSUE TITLE
getting an error with DallEAPIWrapper

### ISSUE THREAD

**Issue by IgorianKiselev02** [langchain-ai/langchain#13825]
### System Info

Hello! I got this error while trying to run code from [docs](https://python.langchain.com/docs/integrations/tools/dalle_image_generator).

I have Python 3.11.3, openai 1.3.5 and langchain 0.0.340 .

```
You tried to access openai.Image, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Write code from [docs](https://python.langchain.com/docs/integrations/tools/dalle_image_generator) and run it using python3.

```python
from langchain.chains import LLMChain
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate
from langchain.utilities.dalle_image_generator import DallEAPIWrapper

llm = OpenAI(temperature=0.9)
prompt = PromptTemplate(
    input_variables=["image_desc"],
    template="Generate a detailed prompt to generate an image based on the following description: {image_desc}",
)
chain = LLMChain(llm=llm, prompt=prompt)
image_url = DallEAPIWrapper().run(chain.run("halloween night at a haunted museum"))

print(image_url)
```

### Expected behavior

get an image url

**Comment by IgorianKiselev02** [comment]
openai.Image is no longer supported with OpenAI version >=1.0.0, so I don't think that using OpenAI version compatible with v1.1 is a solution.

**Comment by AI-Chef** [comment]
Why we use DallEAPIWrapper but not a dall-e-3 chain?
