### ISSUE TITLE
 Unable to get page count. Is poppler installed and in PATH

### ISSUE THREAD

**Issue by akashAD98** [langchain-ai/langchain#13838]
### System Info

im running it on google Collab

### Who can help?

trying the example of mult-modal rag - I tried everything no matter what if still getting this error
please tell if if there is any alternative way or how can we install it? @bas

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

just run it on collab & we will not able to get output from partitions

https://github.com/langchain-ai/langchain/blob/master/cookbook/Multi_modal_RAG.ipynb

![image](https://github.com/langchain-ai/langchain/assets/62583018/2f10bb44-82e9-4dc9-9c66-e84b5a18c6e1)

### Expected behavior

it should work normal without error on collab

**Comment by kulaone** [comment]
I had the same problem with XFA PDF
When installing poppler-utils I got a new error:
`UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7bb25f8173d0>`

**Comment by terwayp** [comment]
I am getting the same error too. Any updates on this? 
```UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x452315ee0>```

**Comment by chibeze01** [comment]
getting the same error i installed poppler on windows from the official site and using byaldi RAGMultiModalModel to index. uising pdf2image. but getting this error.
