### ISSUE TITLE
lang chain Azure vector search not working neither on its direct fields nor on its metadata fields 

### ISSUE THREAD

**Issue by savitaraghuvanshi** [langchain-ai/langchain#13833]
Please help , I am blocked on it from many days .

**I am trying to filter question of answer from pdf doc based on uploaded email filter . Only if email match happen answer the question from that document else just empty .
I tried following code its not working rather even in case of OTHER email id also it  give answer from my email uploaded document which is wrong , seems like filtering not working .**
        
First i tried by putting email as metadata it did not work then i added as independent email field its not working there either .

I am instantiating vector store like below , it has email field in it . I am able to create and successfully able to upload pdf doc with all the fields  including email is populated . I checked created index and email field is filterable , searchable .

- Creating azure instance as below :
`
`self.vector_store = AzureSearch(azure_search_endpoint=endpoint, azure_search_key=admin_key, index_name=index_name, embedding_function=embedding_function,fields=fields)`

- After doc uploaded as shown below it has email in it .

```

"@odata.context": "https://ops-documents.search.windows.net/indexes('index-new-5')/$metadata#docs(*)",
  "value": [
    {
      "@search.score": 1,
      "id": "NjQ1YWViNWQtNDJkNy00NTcxLTlkMTktMDIzZTc0NTZlNDhm",
      "content": "ICAO TRIP 2023 –  .",
"metadata": "{\"source\": \"7-pl\", \"page\": 7, \"file_id\": \"65612fd773a9aa51a0939c96\", \"upload_document_name\": \"SITA Lab Furhat Backoffice IMM officer Dialog - v1.pdf\", \"email\": \"savita.raghuvanshi@st.com\", \"company\": \"sita\"}",
     "email": "savita.raghuvanshi@st.com"
```
 

- 
- Using following way to search :       

       
```
my_retriever = self.vector_store.as_retriever(search_kwargs={'filter': {  'email': email }})
qa = RetrievalQA.from_chain_type(llm=self.llm,chain_type="stuff",retriever=my_retriever,chain_type_kwargs={"prompt": self.PROMPT},
            return_source_documents=True,
        )
        results = qa({"query": question})
```

```
Installations using as : 
**I am using OPENAI_API_VERSION="2023-10-01-preview" with gpt4 model** 
azure-common==1.1.28
azure-core==1.29.5
azure-identity==1.15.0
azure-search==1.0.0b2
azure-search-documents==11.4.0b8
langchain==0.0.326
```

Kindly let me know if anything needed from me . Thanks so much for your help .

**Comment by savitaraghuvanshi** [comment]
I tried this but no luck : 
       
my_retriever = self.vector_store.as_retriever(
            search_kwargs={'filter': ("email eq '%s'" % email)}
        )

        print(f"my_retriever : {my_retriever}")

        qa = RetrievalQA.from_chain_type(
            llm=self.llm,
            chain_type="stuff",
            retriever=my_retriever,
            chain_type_kwargs={"prompt": self.PROMPT},
            return_source_documents=True,
        )
        results = qa({"query": question})

Log : my retriever logged as below :
my_retriever : tags=['AzureSearch'] vectorstore=<langchain.vectorstores.azuresearch.AzureSearch object at 0x7fa3ab4fdc60> search_kwargs={'filter': "email eq 'ken.sul@st.com'"}

**Comment by lz-chen** [comment]
There is a typo in your key. It should be 'filters' instead of 'filter'

**Comment by thelazydogsback** [comment]
The documentation clearly says "filter"

```
 search_kwargs (Optional[Dict]): Keyword arguments to pass to the
                search function. Can include things like:
                    k: Amount of documents to return (Default: 4)
                    score_threshold: Minimum relevance threshold
                        for similarity_score_threshold
                    fetch_k: Amount of documents to pass to MMR algorithm (Default: 20)
                    lambda_mult: Diversity of results returned by MMR;
                        1 for minimum diversity and 0 for maximum. (Default: 0.5)
                    filter: Filter by document metadata
```
