### ISSUE TITLE
create_extraction_chain does not work with other LLMs?i try with llama_api

### ISSUE THREAD

**Issue by Dante690** [langchain-ai/langchain#13847]
### System Info

Python 3.9.18

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hi i try this example, but doesnt work
```
from llamaapi import LlamaAPI
from langchain.chains import create_extraction_chain
llama = LlamaAPI("My Api KEy")

from langchain_experimental.llms import ChatLlamaAPI
model = ChatLlamaAPI(client=llama)
schema = {
    "properties": {
        "name": {"type": "string"},
        "height": {"type": "integer"},
        "hair_color": {"type": "string"},
    },
    "required": ["name", "height"],
}
inp = """
Alex is 5 feet tall. Claudia is 1 feet taller Alex and jumps higher than him. Claudia is a brunette and Alex is blonde.
        """

chain = create_extraction_chain(schema, model)
chain.run(inp)
```

  File "C:\mini\envs\py39\lib\site-packages\langchain\output_parsers\openai_func
tions.py", line 136, in parse_result
    return res.get(self.key_name) if partial else res[self.key_name]
TypeError: string indices must be integers

### Expected behavior

Extraction from text

**Comment by Dante690** [comment]
Maybe can someone help with this..

**Comment by AndreaBrg** [comment]
@keenborder786, do you know if there is any workaround? I'm trying to build a web scraper as shown [here](https://python.langchain.com/docs/use_cases/web_scraping#llm-with-function-calling) but using `ChatOllama` instead of `ChatOpenAI`, but it does not work due to the use of `create_extraction_chain`.
