### ISSUE TITLE
DOC: How langchain_experimental.rl_chain works

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#13865]
### Issue with current documentation:

Hi, can we get more documentation on `langchain_experimental.rl_chain`? I'm having trouble wrapping my head around how it works, and the documentation is sparse. 

From the notebook intro, originally I thought it was going to tune the human written prompt template and then output a new and improved prompt template that it found was better. However it seems to be doing something else.

**Comment by 169** [comment]
@austinmw You can see this [notebook](https://github.com/langchain-ai/langchain/blob/e17edc4d0b1dccc98df2a7d1db86bfcc0eb66ca5/cookbook/learned_prompt_optimization.ipynb)

**Comment by austinmw** [comment]
@169 I mentioned in my post that I read that notebook already
