### ISSUE TITLE
"No module named 'chromadb'" — add chromadb as dependency?

### ISSUE THREAD

**Issue by slhck** [langchain-ai/langchain#1387]
Trying to follow the guides:

- https://langchain.readthedocs.io/en/latest/modules/indexes/getting_started.html
- https://langchain.readthedocs.io/en/latest/modules/indexes/vectorstore_examples/chroma.html

But when I run:

```
db = Chroma.from_documents(texts, embeddings)
```

I get:

```
ModuleNotFoundError                       Traceback (most recent call last)
File ~/Library/Caches/pypoetry/virtualenvs/docs-bot-z8dlOdVH-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py:40, in Chroma.__init__(self, collection_name, embedding_function, persist_directory)
     39 try:
---> 40     import chromadb
     41     import chromadb.config

ModuleNotFoundError: No module named 'chromadb'
```

In my Poetry dependencies, I only had `langchain` and `openai`.

I'd suggest adding a line somewhere in the docs that this is an optional dependency and should be installed?

Once I do:

```
poetry add chromadb
```

It works.

**Comment by slhck** [comment]
Interestingly I did not hit this exception path:

https://github.com/hwchase17/langchain/blob/4b5e850361bd4b47ac739748232d696deac79eaf/langchain/vectorstores/chroma.py#L32-L46

Using v0.0.98.

**Comment by slhck** [comment]
Make sure that it's installed in the same site packages directory. You may have used a different version of pip from a different python environment.

**Comment by IqraShahid-dev** [comment]
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I don't think so it's a pip problem.
I have noticed that during `pip install chromadb` , torch process gets killed maybe memory issue.

![Capture (2)](https://user-images.githubusercontent.com/76934404/226525912-b12a26cd-0d03-4606-b70a-b5d4d2ebbee6.jpg)

with this `pip install torch --no-cache-dir`  

![Capture (3)](https://user-images.githubusercontent.com/76934404/226526294-0a0564bf-1569-4ca1-8aad-5bceac857f9c.jpg)

What's the chromadb package size?

**Comment by slhck** [comment]
This is the size:

```
~/Library/Caches/pypoetry/virtualenvs/docs-bot-z8dlOdVH-py3.10
➜ du -hs lib/python3.10/site-packages/chromadb/
376K	lib/python3.10/site-packages/chromadb/

~/Library/Caches/pypoetry/virtualenvs/docs-bot-z8dlOdVH-py3.10
➜ du -hs lib/python3.10/site-packages/chromadb-0.3.10.dist-info
 32K	lib/python3.10/site-packages/chromadb-0.3.10.dist-info
```

For me using the following `pyproject.toml` was enough, using Poetry:

```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "test"}]

[tool.poetry.dependencies]
python = "^3.10,<3.11"
langchain = "^0.0.98"
openai = "^0.27.0"
chromadb = "^0.3.10"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
mypy = "^1.0.1"
isort = "^5.12.0"
jupyter = "^1.0.0"
notebook = "^6.5.2"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Then run `poetry install`. I generally prefer to use Poetry over user or system library installations.

(Make sure to update to the most recent version of the packages; the above are a bit outdated.)

**Comment by IqraShahid-dev** [comment]
Thanks,
Well my main issue was memory.
With combination of larger instance and poetry ,I am able to resolve my problem.

**Comment by UdayanSL** [comment]
> Thanks, Well my main issue was memory. With combination of larger instance and poetry ,I am able to resolve my problem.

Can you please help me out with how you took care of the situation. I am also facing the same issue...will be really helpful if you could elaborate the steps

**Comment by RatanPrakash** [comment]
> 

Did you restart the terminal after the installation. try that it worked for me.

**Comment by berkayaltug** [comment]
Hi everyone, [this is](https://github.com/oobabooga/text-generation-webui/issues/2236#issuecomment-1558691724) how you can fix this error.

**Comment by khurramwbox** [comment]
Did you restart the terminal after the installation?
I have tried lot of different combination like install with pip, conda etc but it solved with just restarting kernel

**Comment by vijay-pushparaj** [comment]
After restart  it worked for me

**Comment by RatanPrakash** [comment]
Close this issue for now.

**Comment by slhck** [comment]
I will close this issue once the chromadb dependency is properly documented. I'm not sure if this has been done in the meantime.

**Comment by hilarykitz** [comment]
I found this was a version mismatch - langchain expected version 1.5.6. Pinning "chromadb": "1.5.6" in my package.json sorted the issue in my node project, i assume you will need to just align the version in python as well :)

**Comment by wingleungchoi** [comment]
chromadb.py

**Comment by wingleungchoi** [comment]
In my case, it is because I named a file with `chromadb.py`. Python tries to import from this file instead installed package.

**Comment by Lykos2** [comment]
Restart the terminal.It worked for me

**Comment by harshpatel0204** [comment]
> chromadb

refer this link for solution:
https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

**Comment by ashishnex007** [comment]
![image](https://github.com/langchain-ai/langchain/assets/105256502/4baddb5a-ca3c-4b1d-bd15-6b9b6c747572)

Tho I installed chromadb, still have this issue 
pls help anyone

**Comment by Rumeysakeskin** [comment]
`pip install chromadb`
