### ISSUE TITLE
Issue: AgentExecutor stopping before reaching the set max_iteration and max_execution_time limits without meeting the stop condition

### ISSUE THREAD

**Issue by XO-Appleton** [langchain-ai/langchain#13897]
### Issue you'd like to raise.

```python
llm = ChatOpenAI(model=gpt_4, temperature=0, api_key=os.environ['OPENAI_API_KEY'])

llm_chain = LLMChain(llm=llm, prompt=react_prompt)

tool_names = [tool.name]

agent = LLMSingleActionAgent(
    llm_chain=llm_chain,
    output_parser=react_output_parser,
    stop=["\nObservation:"],
    allowed_tools=tool_names,
    max_execution_time=240,
    max_iterations=120,
    handle_parsing_errors=True
)

agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, tools=[tool], verbose=True)
response = agent_executor.run(textual_description)
```

This is my setup for AgentExecutor. It is prompted to solve OpenAI gym's Taxi problem and only stop after the passenger is dropped off at the destination. But as the title suggests the AgentExecutor chain finishes before reaching the stopping limits or achieving the stopping condition.

Also when I use GPT-3 model sometimes it stops following the ReAct template occasionally and raises errors as my output parser cannot process the output correctly. I wonder if there is a way to change that.

**Comment by XO-Appleton** [comment]
I don't think `_should_continue` returned False in my case cause there was 15-ish ReAct steps and there was not an error/warning message saying it reached the maximum iteration limit as usual. In my case the execution time was only 47 seconds as well which is within the limit.

Is there a way to prompt or the LLM (in my case GPT-4) or modify the chain so that the LLM keeps iterating and only stops when the set objective is achieved?

**Comment by keenborder786** [comment]
@XO-Appleton  can you please better format your code using the '```python' markdown otherwise it is very had to understand.

**Comment by XO-Appleton** [comment]
> @XO-Appleton can you please better format your code using the '```python' markdown otherwise it is very had to understand.

Sorry, I got too used to asking GPT about debugging xd

After checking the source code I've also realized that `max_iteration` and `max_execution_time` need to be set when initializing AgentExecutor. I specified them while initializing my agent object instead, hence leaving them to be the default value of 15 and None.

<img width="892" alt="Screenshot 2023-11-27 at 4 35 33 PM" src="https://github.com/langchain-ai/langchain/assets/41369365/df0705fd-6120-4e45-ad0e-8c85c6331e4e">
