### ISSUE TITLE
MultiVector Retriever BaseStore

### ISSUE THREAD

**Issue by raelix** [langchain-ai/langchain#13909]
### Feature request

MultiVectorRetriever is really helpful to add summary and hypothetical queries of our documents to improve the retrievers but only these two are stored in the vectorstore, instead the entire document is within a BaseStore (Memory or Local).
The main issue is that:
- the Memory one is not going to persist across restarts 
- the File one is going to create tons of files
Why not keeping the original document in the vectorstore as well instead of using external file/memory?

### Motivation

Keep documents, questions and summaries on the same vectorstore.

### Your contribution

I could work on that but I would like to know your point of view.

**Comment by sushilkhadkaanon** [comment]
@raelix @dosu-bot Hey guys, it would be really helpful. Have you resolved this?
Or is there any way to save the BaseStore and load ?

**Comment by raelix** [comment]
hey @sushilkhadkaanon , I don't know why this as been closed as it's very helpful.
At the end I wrote it by myself. 
Anyway let me attach here the code I wrote maybe this could help you and other ppl interested on it.

```python
import json
import sqlite3
from typing import Tuple, Iterator
from typing import Sequence, List, Optional
from langchain.schema import BaseStore
from pypika import Query, Table, Field, Column


class ChromaStore(BaseStore[str, bytes]):

    def __init__(self, path, table_name):
        self.connection = sqlite3.connect('{path}/chroma.sqlite3'.format(path=path))
        self.table = Table(table_name)
        self.id_column = Field('id')
        self.data_column = Field('data')
        self._create_table()

    def _create_table(self):
        id_column = Column('id', 'VARCHAR(50)', nullable=False)
        data_column = Column('data', 'VARCHAR(2500)', nullable=False)
        create_table_query = Query.create_table(self.table).columns(id_column, data_column).if_not_exists()
        cursor = self.connection.cursor()
        cursor.execute(create_table_query.get_sql())
        cursor.close()

    def mget(self, keys: Sequence[str]) -> List[Optional[bytes]]:
        select_query = Query.from_(self.table).select(self.data_column).where(self.id_column.isin(keys))

        cursor = self.connection.cursor()
        cursor.execute(select_query.get_sql())
        results = cursor.fetchall()

        cursor.close()

        data_list = []
        for result in results:
            if result[0] is not None:
                data_list.append(json.loads(result[0]).encode("utf-8"))
            else:
                data_list.append(None)

        return data_list

    def mset(self, key_value_pairs: Sequence[Tuple[int, bytes]]) -> None:
        insert_queries = []
        for key, value in key_value_pairs:
            insert_query = Query.into(self.table).columns(self.id_column, self.data_column).insert(key, json.dumps(value.decode('utf-8')))
            insert_queries.append(insert_query)

        cursor = self.connection.cursor()
        for query in insert_queries:
            cursor.execute(query.get_sql())

        self.connection.commit()

        cursor.close()

    def mdelete(self, keys: Sequence[int]) -> None:
        delete_query = Query.from_(self.table).delete().where(self.id_column.isin(keys))

        cursor = self.connection.cursor()
        cursor.execute(delete_query.get_sql())

        self.connection.commit()

        cursor.close()

    def yield_keys(self, prefix: Optional[str] = None) -> Iterator[str]:
        select_query = Query.from_(self.table).select(self.id_column)
        if prefix:
            select_query = select_query.where(self.id_column.like(f'{prefix}%'))

        cursor = self.connection.cursor()
        cursor.execute(select_query.get_sql())

        for row in cursor.fetchall():
            yield row[0]

        cursor.close()
```
Then you can simply using it by:
```python
from langchain.storage._lc_store import create_kv_docstore
cs = ChromaStore("your_db_path", "docstore")
store = create_kv_docstore(cs)
mvr = MultiVectorRetriever(
            vectorstore=vector_store,
            docstore=store,
            ...
        )
```

@efriis, @hwchase17 if you think it could be a good for you, I can create a PR. Does it make sense?

**Comment by FaDavid98** [comment]
Hey @raelix. Can you help me how could i use your solution in my case? 
Here is my code:
```
from langchain.retrievers.multi_vector import MultiVectorRetriever
from langchain.storage import InMemoryStore
from langchain_community.vectorstores import Chroma
from langchain_core.documents import Document
#from langchain_openai import OpenAIEmbeddings
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings

# The vectorstore to use to index the child chunks
vectorstore = Chroma(collection_name="summaries",persist_directory="./chroma_db", embedding_function=FastEmbedEmbeddings())#OpenAIEmbeddings())

# The storage layer for the parent documents
store = InMemoryStore()
id_key = "doc_id"
print(store)
# The retriever (empty to start)
retriever = MultiVectorRetriever(
    vectorstore=vectorstore,
    docstore=store,
    id_key=id_key,
)

# Add texts
doc_ids = [str(uuid.uuid4()) for _ in texts]
summary_texts = [
    Document(page_content=s, metadata={id_key: doc_ids[i]})
    for i, s in enumerate(text_summaries)
]
retriever.vectorstore.add_documents(summary_texts)
retriever.docstore.mset(list(zip(doc_ids, texts)))

# Add tables
table_ids = [str(uuid.uuid4()) for _ in tables]
summary_tables = [
    Document(page_content=s, metadata={id_key: table_ids[i]})
    for i, s in enumerate(table_summaries)
]
retriever.vectorstore.add_documents(summary_tables)
retriever.docstore.mset(list(zip(table_ids, tables)))
```

**Comment by raelix** [comment]
You should, create a new python file with the content of my snippet. Then your code should be changed in:
```python
from langchain.storage._lc_store import create_kv_docstore # Import this

# The storage layer for the parent documents
# store = InMemoryStore() # you don't need this anymore
cs = ChromaStore("./chroma_db", "docstore")
id_key = "doc_id"
# The retriever (empty to start)
store = create_kv_docstore(cs)
retriever = MultiVectorRetriever(
    vectorstore=vectorstore,
    docstore=store,
    id_key=id_key,
)
# The rest is already fine
```

**Comment by FaDavid98** [comment]
@raelix 
```
# Add tables
table_ids = [str(uuid.uuid4()) for _ in tables]
summary_tables = [
    Document(page_content=s, metadata={id_key: table_ids[i]})
    for i, s in enumerate(table_summaries)
]
retriever.vectorstore.add_documents(summary_tables)
retriever.docstore.mset(list(zip(table_ids, tables)))
```
When i am running this it uses the mset from the encoder_backed file and not the mset from your ChromaStore class. That is supposed to work like that?

**Comment by raelix** [comment]
hey @FaDavid98 yes, that's correct. If you want, for completeness you can check my code [here](https://github.com/raelix/telegram-ai-bot/blob/main/vectorstore/vector_store_wrapper.py#L70)

**Comment by FaDavid98** [comment]
@raelix thanks for your hep. I was able to save and use it properly. I am facing now an interesting problem. If i ask my model abot Renault Zoe (which is mentinone in my pdf) i got an answer, but if i ask something specific about the zoe it answers that this information is not mentioned in the context ( but in the first case the information was in the answer, and it is in the document). Why the retriever can't find it?

**Comment by BENHIMA-Mohamed-Amine** [comment]
@raelix, @FaDavid98   can you help me, I used the code above and I got this error:
TypeError: Expected a Document instance

can you help me guys, i will be thankful :)

**Comment by yc247** [comment]
> You should, create a new python file with the content of my snippet. Then your code should be changed in:
> 
> ```python
> from langchain.storage._lc_store import create_kv_docstore # Import this
> 
> # The storage layer for the parent documents
> # store = InMemoryStore() # you don't need this anymore
> cs = ChromaStore("./chroma_db", "docstore")
> id_key = "doc_id"
> # The retriever (empty to start)
> store = create_kv_docstore(cs)
> retriever = MultiVectorRetriever(
>     vectorstore=vectorstore,
>     docstore=store,
>     id_key=id_key,
> )
> # The rest is already fine
> ```

Hi @raelix, thank you for the solution! I wonder what is "docstore" here in cs = ChromaStore("./chroma_db", "docstore"). Is it just a name? Also How can I access docstore? When I load it, it seems like it is just vector store?

**Comment by huangpan2507** [comment]
> @raelix thanks for your hep. I was able to save and use it properly. I am facing now an interesting problem. If i ask my model abot Renault Zoe (which is mentinone in my pdf) i got an answer, but if i ask something specific about the zoe it answers that this information is not mentioned in the context ( but in the first case the information was in the answer, and it is in the document). Why the retriever can't find it?

How do you solve the error
>_lc_store.py", line 19, in _dump_document_as_bytes
>    raise TypeError("Expected a Document instance")
>TypeError: Expected a Document instance

I solved this problem by use
> ...
>raw_pdf_elements = []
>        for file_name in pdf_paths:
>            print(f"Processing PDF: {file_name}")
>            # Get elements
>             one_raw_pdf_elements = partition_pdf(
>                filename=file_name,
>                languages=["chi_sim", "eng"],
>                strategy='hi_res',
>                # Using pdf format to find embedded image blocks
>                extract_images_in_pdf=True,
>                # Use layout model (YOLOX) to get bounding boxes (for tables) and find titles
>                # Titles are any sub-section of the document
>                infer_table_structure=True,
>                 # Post processing to aggregate text once we have the title
>                chunking_strategy="by_title",
>                extract_image_block_output_dir=self._img_path,
>                form_extraction_skip_tables = False
>            )
>            raw_pdf_elements.extend(one_raw_pdf_elements)
>
>        class Element(BaseModel):
>            type: str
>            text: Any
>
>        # Categorize by type
>        categorized_elements = []
>        for element in raw_pdf_elements:
>            if "unstructured.documents.elements.Table" in str(type(element)):
>                categorized_elements.append(Element(type="table", text=str(element)))
>            elif "unstructured.documents.elements.CompositeElement" in str(type(element)):
>                categorized_elements.append(Element(type="text", text=str(element)))
>...
>         vectorstore = Chroma(
>                  persist_directory=self._persist_directory,
>                  embedding_function=embeddings
>        )

>        parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=200)
>        child_splitter = RecursiveCharacterTextSplitter(chunk_size=400)
>        fs = LocalFileStore("/mnt/AI/data_base/vector_db/chroma_new_huangpan")
>        store = create_kv_docstore(fs)
>        id_key = "doc_id"
>        retriever = ParentDocumentRetriever(
>                vectorstore=vectorstore,
>                docstore=store,
>                child_splitter=child_splitter,
>                parent_splitter=parent_splitter,
>            )
>       # Add texts
>       texts = [i.text for i in text_elements if i.text != ""]
>retriever.docstore.mset(list(zip(doc_ids_text, [Document(page_content=s) for i, s in enumerate(texts)])))

@FaDavid98 @raelix  hi, can you help me?
I found the create_kv_docstore will translate the texts that you store in `retriever.docstore.mset` to another language(like text both has english word and chinese word), eg, it will translate the chinese word to english word and Unicode!!!! 
That is to say:  origin text is  English words + Chinese words， but after store it into create_kv_docstore, the text like bellow, they are english words + Unicode
the text store in 

`{"page_content": "\u6240\u6709\u5916\u90e8\u57f9\u8bad\u4f9b\u5e94\u5546\u5fc5\u987b\u4e0e\u516c\u53f8\u7b7e\u8ba2\u5546\u4e1a\u5408\u540c\u540e\uff0c\u624d\u53ef\u5f00\u59cb\u63d0\u4f9b\u670d\u52a1\u3002\u672c\u5408\u540c\u5e94\u5305\u62ec \u5e38\u89c4\u7684\u5408\u540c\u4fe1\u606f\uff0c\u5305\u62ec\u4f46\u4e0d\u9650\u4e8e\u670d\u52a1\u8303\u56f4\u3001\u4ea4\u4ed8\u65f6\u95f4\u548c\u4ed8\u6b3e\u6761\u6b3e\u7b49\u3002\n\nThe addition of training vendors may be initiated by employees, a prior approval is\n\nThe addition of training vendors may be initiated by employees, a prior approval is required for all training sessions. The company can make informed decisions about training vendors and maintain control over the quality and cost of training programs.\n\nrequired for all training sessions.\n\nThe company can make informed decisions about\n\nThe", "type": "Document"}`

How to solve this problem?  who can help me?

**Comment by huangpan2507** [comment]
> retriever.docstore.mset(list(zip(doc_ids_text, [Document(page_content=s) for i, s in enumerate(texts)])))

@BENHIMA-Mohamed-Amine   translate the texts to Document object,  i think it will help because I had met the same issue before.
