### ISSUE TITLE
Link to URL to load product details

### ISSUE THREAD

**Issue by yazanrisheh** [langchain-ai/langchain#13920]
@dosu-bot

I have a project where I need to extract product details from product links online. What is the best url loader for this use case?

Also, for the previous links that I already appended to a csv file called "Lalal". How can I create embeddings only for the new URL link that I will extract so that I dont have to embed the entire document every single time.

Please write the code for me in python.

**Comment by keenborder786** [comment]
@yazanrisheh I can help you out. Please give me some time.

**Comment by keenborder786** [comment]
It will be great if you can further elaborate on this line 'How can I create embeddings only for the new URL link that I will extract so that I dont have to embed the entire document every single time.'

**Comment by yazanrisheh** [comment]
Hello @keenborder786 Thank you for replying!

So what I am trying to do is create a chatbot that basically extracts information like product name, brand, price etc... and put them in a csv file so that I can query over them. However, everytime I add a new product I dont want to constantly embed the entire document over and over again. Instead, I want to embed just the new product I added to my file.

**Comment by umair313** [comment]
@yazanrisheh 
to prevent creating embedding for existing URLs, you can do something like, first get all the documents from your Vectore store and then filter out new URL so you will be left with new URL which need to embidd.

**Comment by yazanrisheh** [comment]
@umair313 sorry I'm still a bit confused. Can you explain a bit more in details? Also, do you by any chance have the code snippet for it? Thanks
