### ISSUE TITLE
Issue: create_sql_agent omits and limits actual information retrieved from SQL tables

### ISSUE THREAD

**Issue by hamzaawan99** [langchain-ai/langchain#13931]
### Issue you'd like to raise.

When utilizing the create_sql_agent module by LangChain to interact with a SQL database and generate SQL queries from natural language, I've encountered an issue with the responses. Currently, when I execute queries, the SQL Agent responds with placeholder information, citing security reasons for omitting the actual data. However, for my use case, it is crucial to receive the real information retrieved from the SQL database tables.

Also, it limits the information as well even with `top_k=50`. The database return 50 records but in the output it only shows 10-12 with the following output: Please note that this is a partial list. There are more ...

langchain == 0.0.313
langchain-experimental == 0.0.32

```
dbmssql = SQLDatabase.from_uri(
        connection_url,
        include_tables=[
            "table_1",
            "table_2",
            "table_3",
            "table_4",
        ],
        view_support=False
    )

chat_llm = ChatOpenAI(
    model="gpt-4",
    temperature=0,
    verbose=True,
    openai_api_key=openai_api_key,
    request_timeout=600
)

def create_mssql_db_agent(dbmssql):

    few_shot_docs = [
        Document(page_content=question, metadata={
            "sql_query": few_shots[question]})
        for question in few_shots.keys()
    ]
    vector_db = FAISS.from_documents(few_shot_docs, embeddings)
    retriever = vector_db.as_retriever()

    tool_description = """
    This tool will help you understand similar examples to adapt them to the user question.
    Input to this tool should be the user question.
    """

    retriever_tool = create_retriever_tool(
        retriever, name="sql_get_similar_examples", description=tool_description
    )
    custom_tool_list = [retriever_tool]

    custom_suffix = """
    I should first get the similar examples I know.
    If the examples are enough to construct the query, I can build it.
    Otherwise, I can then look at the tables in the database to see what I can query.
    Then I should query the schema of the most relevant tables
    """

    agent = create_sql_agent(
        agent_executor_kwargs={"return_intermediate_steps": True},
        llm=chat_llm,
        toolkit=SQLDatabaseToolkit(db=dbmssql, llm=chat_llm),
        verbose=True,
        agent_type=AgentType.OPENAI_FUNCTIONS,
        extra_tools=custom_tool_list,
        suffix=custom_suffix,
        top_k=50,
        # return_intermediate_steps=True
    )
    return agent
```

**Comment by hamzaawan99** [comment]
Thanks for the response. This agent also takes a lot of time to execute, can we log some time for each tool in the agent?
Which arguments are possible for agent_executor_kwargs in 

```
agent = create_sql_agent(
        agent_executor_kwargs={"return_intermediate_steps": True},
        llm=chat_llm,
        toolkit=SQLDatabaseToolkit(db=dbmssql, llm=chat_llm),
        verbose=True,
        agent_type=AgentType.OPENAI_FUNCTIONS,
        extra_tools=custom_tool_list,
        suffix=custom_suffix,
        top_k=50,
        # return_intermediate_steps=True
    )
    return agent
```

**Comment by sseyedi01** [comment]
Hi, I have the same problem. Maybe you found the solution

**Comment by hamzaawan99** [comment]
@sseyedi01 I followed this article [https://medium.com/@yernenip/few-shot-prompting-with-codellama-langchain-and-mysql-94020ee16a08](url). It uses SQLDatabaseChain instead of agent. It does not solve all the issues but it does improve results, shows actual data from the database in response and reduces the time for execution as well.

**Comment by srivats1818** [comment]
Not even a single solution is working which has been mentioned above.
