### ISSUE TITLE
'HTTPClient' object has no attribute 'configuration'

### ISSUE THREAD

**Issue by crazyseabiscuit** [langchain-ai/langchain#13943]
### System Info

machine: mackbook pro Sonoma 14.1.1
package:
python = "3.10.13"
openai = "^0.28.1"
pandas = "^2.1.1"
ipython = "^8.16.0"
langchain = "^0.0.306"
python-dotenv = "^1.0.0"
seaborn = "^0.13.0"
tqdm = "^4.66.1"
torch = "^2.1.0"
transformers = "^4.35.2"
accelerate = "^0.24.1"
sentencepiece = "^0.1.99"
openllm = "^0.4.27"

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

follow the instruction https://python.langchain.com/docs/integrations/llms/openllm
1)openllm start dolly-v2
2)
from langchain.llms import OpenLLM
server_url = "http://localhost:3000"  # Replace with remote host if you are running on a remote server
llm = OpenLLM(server_url=server_url)
llm("what is the meaning of life")

error:
line 229 /langchain/llms/openllm.py 220
AtrributionError: "HttpClient" object has not attribute 'configuration'

### Expected behavior

return a response from LLM

**Comment by crazyseabiscuit** [comment]
langchain                                    0.0.306
openllm                                      0.4.28
openllm-client                               0.4.28
openllm-core                                 0.4.28
Python 3.10.13

**Comment by lujingxuansc** [comment]
I found a PR, but it hasn't been merged yet. https://github.com/langchain-ai/langchain/pull/12968
