### ISSUE TITLE
PineconeProtocolError: Failed to connect; did you specify the correct index name?

### ISSUE THREAD

**Issue by blockdev723** [langchain-ai/langchain#13951]
### System Info

To train data in Pinecone, I used the function.
_pinecone = Pinecone.from_documents(docs, self.embeddings, index_name=self.index_name)

all the parameters have values always:
![image](https://github.com/langchain-ai/langchain/assets/47790805/da013cf4-a082-44d0-9505-0013835c4b90)

![image](https://github.com/langchain-ai/langchain/assets/47790805/6764a84c-a59c-43a5-9dfe-4ecea69e68ef)

But, this error occurs often like this: 
![image](https://github.com/langchain-ai/langchain/assets/47790805/9aee7fed-49c4-4e6e-941f-94c3f442244c)

 @hwchase17 , I am looking forward to fixing this issue asap. Thank you.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

class PineConeIndexer:
    
    def __init__(self):
        self.embeddings = OpenAIEmbeddings()

        # initialize pinecone
        pinecone.init(
            api_key=os.environ.get('PINECONE_API_KEY'), 
            environment=os.environ.get('PINECONE_ENV') 
        )

        self.index_name = os.environ.get('PINECONE_INDEX_NAME')

   def upsert_index_from_task(self, task):
        try:
           # get doc
            ....
            _pinecone = Pinecone.from_documents(docs, self.embeddings, index_name=self.index_name)
            return {"success": True, "error": None}
        except Exception as e:
            return {"success": False, "error": str(e)}

### Expected behavior

sometimes, this error occurs: 

PineconeProtocolError
Failed to connect; did you specify the correct index name?

ProtocolError
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by blockdev723** [comment]
I've set the index_name correctly, confirmed it on Pinecone dashboard. 
This issue occurred sometimes, not every time.

**Comment by MohamedTaha314** [comment]
Same issue, here, it happens rarely, but for no apparent/clear reason
