### ISSUE TITLE
`ConversationSummaryMemory` does not support for multi-languages.

### ISSUE THREAD

**Issue by FavorMylikes** [langchain-ai/langchain#1395]
https://github.com/hwchase17/langchain/blob/499e76b1996787f714a020917a58a4be0d2896ac/langchain/chains/conversation/prompt.py#L36-L59

Every time the `openai` call summary request is just added to the prompt head message, it will lead `llm` giving a response with the same language, and then, when you ask it do something again, it will make a mistake.

**Comment by galvaofelipe** [comment]
Hey FavorMylikes, did you find a solution to customizing the ConversationSummaryMemory summarization prompt? I'm looking forward to using summarization in my Brazilian Portuguese chatbot, and right now it seems I'd have to implement a new Memory class.
