### ISSUE TITLE
ImportError: cannot import name 'agenerate_from_stream' from 'langchain_core.language_models.chat_models'

### ISSUE THREAD

**Issue by nicoloboschi** [langchain-ai/langchain#13958]
### System Info

Current LangChain master commit: 
https://github.com/langchain-ai/langchain/commits/391f200 

### Who can help?

@hwchase17 @baskaryan

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Just run 
```
from langchain.chat_models import BedrockChat
```

Stacktrace: 
```
tests/e2e-tests/test_compatibility_matrix.py:10: in <module>
    from langchain.chat_models import ChatOpenAI, AzureChatOpenAI, ChatVertexAI, BedrockChat
/tmp/venv/lib/python3.11/site-packages/langchain/chat_models/__init__.py:20: in <module>
    from langchain.chat_models.anthropic import ChatAnthropic
/tmp/venv/lib/python3.11/site-packages/langchain/chat_models/anthropic.py:18: in <module>
    from langchain.chat_models.base import (
/tmp/venv/lib/python3.11/site-packages/langchain/chat_models/base.py:1: in <module>
    from langchain_core.language_models.chat_models import (
E   ImportError: cannot import name 'agenerate_from_stream' from 'langchain_core.language_models.chat_models' (/tmp/venv/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py)
```

### Expected behavior

To being able to import the required modules

**Comment by HuskyDanny** [comment]
Same problem here. I just followed the quick start for using **ChatOpenAI** class with pip install -e . for langchain dependency

I do see there is no such function from langchain_core:
![image](https://github.com/langchain-ai/langchain/assets/40053881/c3c85fdb-4f8b-4e3b-aea9-d7d15a9bd5bf)

Full example code and error:
![image](https://github.com/langchain-ai/langchain/assets/40053881/b69458a5-52f9-4439-8bfb-61c1611ed13a)

**Comment by cbornet** [comment]
FIxed by https://github.com/langchain-ai/langchain/pull/13932 ?

**Comment by HuskyDanny** [comment]
langchain_core should be >= 0.0.7 in the pyproject.toml, the latest change fixed it. After reinstalling, it works fine.

**Comment by nicoloboschi** [comment]
Yeah after using langchain_core >= 0.0.7 everything worked fine, closing
