### ISSUE TITLE
Advance metadata filtering for PGVector

### ISSUE THREAD

**Issue by raghav-knowbe4** [langchain-ai/langchain#13955]
### Feature request

PGVector in Langchain does not support advance metadata filtering such as "OR" clause.
For now, there is no way to perform filters such as:

```
{
"$or": [
     {"uploaded_by": {"$eq": "USER1"}},
     {"org": {"$eq": "ORG"}},
  ]
}
```

### Motivation

Our team is unable to use langchain with PGVector due to its lack of support for "OR" filter.
Having advanced metadata filtering like that in Pinecone/Qdrant would really help

https://docs.pinecone.io/docs/metadata-filtering

### Your contribution

For now, I see existing PR: https://github.com/langchain-ai/langchain/pull/12977
This could possibly solve the issue.

**Comment by bradfordben** [comment]
The PR is ready for review by the langchain developers. Not sure the next steps to get it reviewed.

**Comment by diegovalenzuelaiturra-latam** [comment]
probably related to this [issue](https://github.com/langchain-ai/langchain/issues/16146)

**Comment by Robs-Git-Hub** [comment]
Is this working for anyone now?
