### ISSUE TITLE
Issue: Chroma.from_documents does not save metadata properly

### ISSUE THREAD

**Issue by YanaSSS** [langchain-ai/langchain#13963]
### Issue you'd like to raise.

I create my vector db using the following code:
```
db = Chroma.from_documents(
            chunked_documents,
            embeddings,
            persist_directory=db_path + '/' + db_type,
            client_settings=chroma_settings,)
```
`chunked_documents` is a list of elements of type Document.
I have added metadata which is a simple numerical id: `{'id': 1}`

```
embeddings = HuggingFaceInstructEmbeddings(
        model_name=args.embedding_model,
        model_kwargs={"device": args.device},
    )
```

```
CHROMA_SETTINGS = Settings(
    anonymized_telemetry=False,
    is_persistent=True,
)
```

What happens is that I run `db.similarity_search(query, k=3)` and for part of the answers, the metadata dict is empty. Has anyone encountered such an issue? 

Just to point out, when I create the db using the `from_texts()` method where I add raw texts and metadata separately I do not encounter the issue and when running `db.similarity_search()` the returned answer, contains the respective metadata.

**Comment by umair313** [comment]
@YanaSSS please specify your versions

**Comment by YanaSSS** [comment]
chromadb==0.4.6
langchain==0.0.267
Python 3.10.8

**Comment by i-mprovising** [comment]
Shouldn't the metadata value type be str, not int?
