### ISSUE TITLE
Nvidia TensorRT LLM Connector

### ISSUE THREAD

**Issue by jdye64** [langchain-ai/langchain#13975]
### Feature request

NVIDIA TensorRT is an open-source SDK for high-performance deep learning inference, includes a deep learning inference optimizer and runtime that delivers low latency and high throughput for inference applications. I propose that a connector be added to langchain allowing users to use TensorRT with minimal configuration.

### Motivation

There are several implementations of this connector floating around the internet. Lots of folks seem to want this. Rather than have everyone need to add that connector manually it seems to make sense to natively include it in Langchain.

### Your contribution

I am happy to open the PR for this and will do so shortly.

**Comment by peterableda** [comment]
@jdye64 Why are you calling out TensorRT specifically here? IIUC you are integrating with the Triton Inference Server and you will talk to its exposed APIs so theoretically this will support any model that's deployed on Triton.

**Comment by jdye64** [comment]
@peterableda previous this client had just been for tensorRT specifically. It has since been expanded to cover any model served by triton. The PR title simply hasn't changed

**Comment by DeekshithaDPrakash** [comment]
Isn't there any way to connect custom llm from tensort-llm backend to langchain?
