### ISSUE TITLE
Singel object extraction

### ISSUE THREAD

**Issue by Yanni8** [langchain-ai/langchain#13971]
### Feature request

Currently, the extraction chain only supports the extraction of an Array of object.

For example

```python
from typing import Optional

from langchain.chains import create_extraction_chain_pydantic
from langchain.pydantic_v1 import BaseModel


# Pydantic data class
class Properties(BaseModel):
    person_name: str
    person_height: int
    person_hair_color: str
    dog_breed: Optional[str]
    dog_name: Optional[str]


# Extraction
chain = create_extraction_chain_pydantic(pydantic_schema=Properties, llm=llm)

# Run
inp = """Alex is 5 feet tall. Claudia is 1 feet taller Alex and jumps higher than him. Claudia is a brunette and Alex is blonde."""

chain.run(inp)
# Results in
#
#  [Properties(person_name='Alex', person_height=5, person_hair_color='blonde', dog_breed=None, dog_name=None),
#  Properties(person_name='Claudia', person_height=6, person_hair_color='brunette', dog_breed=None, dog_name=None)]
#
````

There is currently no option available to just get one `Properties` object.

It would be nice if you could define at the beginning if you are interested in one object or an array of objects

For example

```` python
chain = create_extraction_chain_pydantic(pydantic_schema=List[Properties], llm=llm) -> Array of Properties
chain = create_extraction_chain_pydantic(pydantic_schema=Properties] llm=llm) -> Just one Propertie
`````

### Motivation

It would just make life easier when you knew that you were only dealing with one object.

It might also improve the response and prevent wrong or incomplete responses. 

### Your contribution

I would create and submit a PR that contains this feature.

**Comment by eyurtsev** [comment]
We've updated the extraction use case docs now: https://python.langchain.com/docs/use_cases/extraction
