### ISSUE TITLE
DOC: streamlit memory parameters - memory_key and chat_history

### ISSUE THREAD

**Issue by annachrome** [langchain-ai/langchain#13995]
### Issue with current documentation:

Streamlit tutorial suggests
```
from langchain.memory import ConversationBufferMemory
from langchain.memory.chat_message_histories import StreamlitChatMessageHistory

# Optionally, specify your own session_state key for storing messages
msgs = StreamlitChatMessageHistory(key="special_app_key")

memory = ConversationBufferMemory(memory_key="history", chat_memory=msgs)
if len(msgs.messages) == 0:
    msgs.add_ai_message("How can I help you?")
```

but in version 0.340, definition of ConversationBufferMemory only includes parameter memory_key but not chat_history.

I have noticed my model outputs being less accurate for the same script when streamlit is incorporated and I suspect this is the issue.

### Idea or request for content:

Please clarify how to best implement Streamlit with chat history.

**Comment by sfc-gh-jcarroll** [comment]
Thanks @annachrome 

You can fix it by just removing the `memory_key` arg from ConversationMemoryBuffer

I submitted a PR https://github.com/langchain-ai/langchain/pull/16072

There's also a working example code here: https://github.com/langchain-ai/streamlit-agent/blob/main/streamlit_agent/basic_memory.py (also linked in the doc already)
