### ISSUE TITLE
SQLDatabaseChain returning Question and SQL Query instead of answer

### ISSUE THREAD

**Issue by NivedhaBalakrishnan** [langchain-ai/langchain#13994]
### System Info

Code

db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, return_sql=False, use_query_checker=True, prompt=prompt_template)
db_chain.run("What are some recently added dockets and their title?")

Verbose
> Entering new SQLDatabaseChain chain...
What are some recently added dockets and their title?
SQLQuery:SELECT id, title, modifyDate FROM docket ORDER BY modifyDate DESC LIMIT 5;
SQLResult: [('CMS-2023-0184', 'CY 2024 Inpatient Hospital Deductible and Hospital and Extended Care Services Coinsurance Amounts.  CMS-8083-N', datetime.datetime(2023, 11, 1, 15, 34, 1)), ('CMS-2023-0183', '(CMS-10143)  State Data for  the Medicare Modernization Act (MMA)', datetime.datetime(2023, 11, 1, 10, 34, 24)), ('CMS-2023-0181', 'CHIP State Plan Eligibility (CMS-10398 #17)', datetime.datetime(2023, 11, 1, 10, 25, 35)), ('CMS-2023-0182', '(CMS-10434 #77) Medicaid and Continuous  Eligibility for Children', datetime.datetime(2023, 11, 1, 10, 24, 56)), ('CMS-2023-0180', 'Virtual Groups for Merit Based Incentive Payment System (MIPS) (CMS-10652)', datetime.datetime(2023, 10, 31, 13, 8, 24))]
Answer:SELECT id, title, modifyDate FROM docket ORDER BY modifyDate DESC LIMIT 5;
> Finished chain.

Output:
'SELECT id, title, modifyDate FROM docket ORDER BY modifyDate DESC LIMIT 5;'

The chain is not returning the SQLResult in the chat format even though the query is executed correctly.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

prompt_suffix = """
If asked for recent dockets, give 5 most recent ones.
Make sure the table name is in the database.

Table name: docket,
Use only these columns when selecting: id, title, modifyDate
"""

prompt_template = PromptTemplate.from_template(prompt_suffix)

db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, return_sql=False, use_query_checker=True, prompt=prompt_template)
db_chain.run("What are some recently added dockets and their title?")

### Expected behavior

Example output:

The recently added dockets with their dates are:\n\n* CMS-2023-0181 - CY 2024 Inpatient Hospital Deductible and Hospital and Extended Care Services Coinsurance Amounts (November 1st, 2023'

**Comment by mmahmad** [comment]
FYI, I see that it's a consistent behavior in all SQL chains (no surprise):

- sql-pgvector: https://github.com/langchain-ai/langchain/blob/master/templates/sql-pgvector/sql_pgvector/chain.py#L67
- sql-ollama: https://github.com/langchain-ai/langchain/blob/master/templates/sql-ollama/sql_ollama/chain.py#L27
- sql-llama2: https://github.com/langchain-ai/langchain/blob/master/templates/sql-llama2/sql_llama2/chain.py#L29
- sql-llamacpp: https://github.com/langchain-ai/langchain/blob/master/templates/sql-llamacpp/sql_llamacpp/chain.py#L61

**Comment by anshumankmr** [comment]
Is there a way to resolve this>?

**Comment by sandeeppolsani** [comment]
How can we resolve this ?
