### ISSUE TITLE
Issue: openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### ISSUE THREAD

**Issue by arunkumars27** [langchain-ai/langchain#14018]
### Issue you'd like to raise.

I use the below code to load data and splitted it and embedded it and finally pushing it into vector store. during that process,
I'm getting **openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}**. After this method failed, I also tried with AzurecosmosDBVectorsearch vector store it also failed and returned the same error. Kindly help on this.

```
from langchain.embeddings.azure_openai import AzureOpenAIEmbeddings
from langchain.vectorstores.azure_cosmos_db import AzureCosmosDBVectorSearch
from langchain.vectorstores.chroma import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader

# Load PDF
loaders = [
    PyPDFLoader("ai.pdf")
]
docs = []
for loader in loaders:
    docs.extend(loader.load())
    # Define the Text Splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1500,
    chunk_overlap=150
)

# Create a split of the document using the text splitter
res_splits = text_splitter.split_documents(docs)

embedding = AzureOpenAIEmbeddings(
    openai_api_version="1699-02-30",
    openai_api_key="xxxxxxxxxxxxxxxxxxxxxxxxx",
    #   model_name="gpt-35-turbo",
    azure_endpoint="https://ggggggggggggggggggggggg.openai.azure.com/")
persist_directory = 'docs/chroma/'



#  Create the vector store
vectordb = Chroma.from_documents(
    documents=res_splits,
    embedding=embedding,
    persist_directory=persist_directory
)

print(vectordb._collection.count())

```

**Comment by dchinn1** [comment]
I'm having the same issue that the embeddings endpoint results in a 404 resource not found error. The attempted url was "my-resource.openai.azure.com/openai/embeddings", I've also tried "my-resource.openai.azure.com/embeddings" just in case.

**Comment by mspronesti** [comment]
You might be missing the deployment name when instantiating the `AzureOpenAIEmbeddings` object.  

```py
embedding = AzureOpenAIEmbeddings(
    openai_api_version="1699-02-30",
    openai_api_key="xxxxxxxxxxxxxxxxxxxxxxxxx",
    #   model_name="gpt-35-turbo",
    azure_endpoint="https://ggggggggggggggggggggggg.openai.azure.com/"
    azure_deployment = ... # <- add your deployment name here
)
```

**Comment by dchinn1** [comment]
> You might be missing the deployment name when instantiating the `AzureOpenAIEmbeddings` object.
> 
> ```python
> embedding = AzureOpenAIEmbeddings(
>     openai_api_version="1699-02-30",
>     openai_api_key="xxxxxxxxxxxxxxxxxxxxxxxxx",
>     #   model_name="gpt-35-turbo",
>     azure_endpoint="https://ggggggggggggggggggggggg.openai.azure.com/"
>     azure_deployment = ... # <- add your deployment name here
> )
> ```

This helped immensely. I was using OpenAIEmbeddings previously, and switching to the AzureOpenAIEmbeddings seems to have solved my issue (I did include the azure_deployment name, which was the name of my embeddings deployment).

**Comment by Mantavya131** [comment]
Hey there, I have got a problem with it which I am  badly stuck in. Please see if I can be helped.

This is the code:

![image](https://github.com/langchain-ai/langchain/assets/82157757/079a7a50-b681-46bb-aa72-77fd3606c25e)
![image](https://github.com/langchain-ai/langchain/assets/82157757/eaee9f17-6afc-4242-aaf9-210f410d6c58)



--------------------------------------------------------------------------------
And this is the error:

![image](https://github.com/langchain-ai/langchain/assets/82157757/4feced1d-f4a0-4278-b9e6-e7537b7242d4)

**Comment by dchinn1** [comment]
> Hey there, I have got a problem with it which I am badly stuck in. Please see if I can be helped.
> 
> This is the code:
> 
> ![image](https://private-user-images.githubusercontent.com/82157757/303819178-079a7a50-b681-46bb-aa72-77fd3606c25e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDgxMTAsIm5iZiI6MTcwNzU0NzgxMCwicGF0aCI6Ii84MjE1Nzc1Ny8zMDM4MTkxNzgtMDc5YTdhNTAtYjY4MS00NmJiLWFhNzItNzdmZDM2MDZjMjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA2NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MmNjNDQ2YjU3YTQ5MDA3ZjA4MzU5OGM2OTc5NjIxNWNlOGYwYjc4M2FmNWM0NzUxOGM1NmU2NjMxNTI5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9iLx6hgz_emCdQBWqKc6nlL6FS2K40M6W4D4OJRZ32w) ![image](https://private-user-images.githubusercontent.com/82157757/303819221-eaee9f17-6afc-4242-aaf9-210f410d6c58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDgxMTAsIm5iZiI6MTcwNzU0NzgxMCwicGF0aCI6Ii84MjE1Nzc1Ny8zMDM4MTkyMjEtZWFlZTlmMTctNmFmYy00MjQyLWFhZjktMjEwZjQxMGQ2YzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA2NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjZhYTllMDQ3NDU3ZWI0YjcyMjhhYmM2YzA5YzA3MjJkYjRjNTkwYTc5ZDZlNGFjZWQ4MTE3OTcwOWI3MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7KDv5dwHgWG3nkm8WoQCqgIeZE3D-h6hyMV1XMTcmOA)
> 
> And this is the error:
> 
> ![image](https://private-user-images.githubusercontent.com/82157757/303819296-4feced1d-f4a0-4278-b9e6-e7537b7242d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NDgxMTAsIm5iZiI6MTcwNzU0NzgxMCwicGF0aCI6Ii84MjE1Nzc1Ny8zMDM4MTkyOTYtNGZlY2VkMWQtZjRhMC00Mjc4LWI5ZTYtZTc1MzdiNzI0MmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDA2NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkODA4ZTQxNzU1MzQwZDFlOGVjN2NmNmVlYWRiYmM5NzNhYzA1ZTNmYTQ0NGI4YzZmNmE5ODA5OGFlNTgxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EbULv3FceMeyUFYtzI3oorWt5nHKqowdFRqXxcIEAH0)

You posted your API key, make sure to rotate that immediately and you should remove it from the post.
