### ISSUE TITLE
Doctran translate documents

### ISSUE THREAD

**Issue by abasovvyusif** [langchain-ai/langchain#14020]
### System Info

IPython          : 8.15.0
ipykernel        : 6.25.0
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.5.0
jupyter_server   : 1.23.4
jupyterlab       : 3.5.3
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
notebook         : 6.5.4
qtconsole        : 5.4.2
traitlets        : 5.7.1

Python 3.11.6
Langchain '0.0.340'

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

TypeError: object Document can't be used in 'await' expression

translated_document = await qa_translator.atransform_documents(documents)
from official documentation notebook :
https://github.com/langchain-ai/langchain/blob/1cd9d5f3328e144cbe5d6ef52a22029d4fdf0cce/docs/docs/integrations/document_transformers/doctran_translate_document.ipynb

### Expected behavior

The problem might be arise due to specific python version or asyncio .

**Comment by eileengray** [comment]
Hello @Dosu,

I'm experiencing the same problem. I tried the corrected code but unfortunately this gave me another error. See exception below.

`---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[4], line 5
      2 qa_translator = DoctranTextTranslator(language="english", openai_api_model="gpt-3.5-turbo")
      4 #Bug??https://github.com/langchain-ai/langchain/issues/14020
----> 5 translated_document = await qa_translator.atransform_documents(documents)
      6 print(translated_document[0].page_content)

File ~/jupyterproject/danielaspenv/lib/python3.11/site-packages/langchain/document_transformers/doctran_text_translate.py:87, in DoctranTextTranslator.atransform_documents(self, documents, **kwargs)
     83 loop = asyncio.get_running_loop()
     84 future = loop.run_in_executor(
     85     None, partial(self.transform_documents, **kwargs), documents
     86 )
---> 87 return await asyncio.wrap_future(future)

File /usr/lib/python3.11/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~/jupyterproject/danielaspenv/lib/python3.11/site-packages/langchain/document_transformers/doctran_text_translate.py:44, in DoctranTextTranslator.transform_documents(self, documents, **kwargs)
     41 def transform_documents(
     42     self, documents: Sequence[Document], **kwargs: Any
     43 ) -> Sequence[Document]:
---> 44     raise NotImplementedError

NotImplementedError: `
