### ISSUE TITLE
Don't proceed with chatting until the user provides his name and phone number

### ISSUE THREAD

**Issue by agoor97** [langchain-ai/langchain#14057]
### Issue you'd like to raise.

I want to customize a LLM (a GPT-3.5-turbo) for chatting but don't proceed with chatting until the user provides his name and his phone number and validates the count of his phone number.

Please help me I tried many methods but without any significant result

**Comment by agoor97** [comment]
Thank you for your response I appreciate that. Unfortunately, I need to store these variables (name and phone number). Can You help me, please? 
Also after I copy the code to the mentioned class. How to use it Later

**Comment by vignxs** [comment]
Look at Kor python module to extract and store the data from memory.

Langchain also provides tagging and extraction.

**Comment by agoor97** [comment]
Great, it works thank you
