### ISSUE TITLE
Support for Perplexity's PPLX models: `pplx-7b-online` and `pplx-70b-online`

### ISSUE THREAD

**Issue by jamino30** [langchain-ai/langchain#14079]
### Feature request

Support for Perplexity's new [PPLX models](https://blog.perplexity.ai/blog/introducing-pplx-online-llms).

### Motivation

Boosting online LLM support, particularly for Perplexity-based models, would be highly impactful and useful.

### Your contribution

Currently working on a PR!

**Comment by zohaibdr** [comment]
Hi. Just wondering if the support for perplexity has been added yet?
