### ISSUE TITLE
Combine langchain retrievers

### ISSUE THREAD

**Issue by RishiMalhotra920** [langchain-ai/langchain#14082]
### Issue you'd like to raise.

I am using ConversationalRetrievalChain. I have created two vector stores and I want the query from ConversationalRetrievalChain to be compared against both vector stores and results from both vector stores to be used to create the final answer.

So I have decided to create two retrievers 

retriever1 = vectorstore1.as_retriever()
retriever2 = vectorstore2.as_retriever()

How can I now override the Retriever class so that when the query is compared against my custom_retriever, it is compared against documents from both retrievers, and documents from both retrievers are used to create the prompt.

Note: i don't want to merge the vectorstores because that messes up the similarity search.

**Comment by RishiMalhotra920** [comment]
@dosu-bot

I tried running your code and get this issue:

"CustomRetriever" object has no field "retrievers".

Can you modify your code?

**Comment by GMartin-dev** [comment]
@RishiMalhotra920 you can user a merge retriever, already does this job for you.
https://python.langchain.com/docs/integrations/retrievers/merger_retriever

**Comment by ssk2706** [comment]
@GMartin-dev when I try to merge two retrievers I get answers from ConversationalRetrivalChain based on only the first retriever present in the list of retrievers defined 

Like if I do this- 
merger = MergerRetriever(retrievers= [vectordb_ret,db1_ret])

Then LLM is only able to get perfect answers when query is about vectordb_ret
Once I ask question related to db1_ret it doesn't give back correct answer please help

**Comment by GMartin-dev** [comment]
> @GMartin-dev when I try to merge two retrievers I get answers from ConversationalRetrivalChain based on only the first retriever present in the list of retrievers defined
> 
> Like if I do this- merger = MergerRetriever(retrievers= [vectordb_ret,db1_ret])
> 
> Then LLM is only able to get perfect answers when query is about vectordb_ret Once I ask question related to db1_ret it doesn't give back correct answer please help

Could be a lot of stuff happening:
- The second retriever is not getting relevant documents correctly.
- The model could not be good enough to figure out the answer or the prompt is too complex.
- The context could be too long and you have a "lost in the middle" issue.

do you have a link to a run on langsmith to debug/ take a look to the prompt?

**Comment by ssk2706** [comment]
@GMartin-dev No,  I don't have access to langsmith

**Comment by ssk2706** [comment]
@GMartin-dev I am using ChromaDB vector-store is that what causing the problem??
