### ISSUE TITLE
in AWS langchain Bedrock, how do I set temperature?

### ISSUE THREAD

**Issue by mansourshams** [langchain-ai/langchain#14083]
### System Info

in AWS langchain Bedrock, how do I set temperature?

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Tried putting it as a parameter of Bedrock and gave error that such parameter does not exist. Then put is as paramenters of kwargs and it had no effect

### Expected behavior

Expected this to be a direct parameter of Bedrock, but it seems that it is not

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you. Can you also give an example of setting Top K and Top P

**Comment by mansourshams** [comment]
@dosu-bot.

How do I make the LLM to not give less likely answers?

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you. what are the default values of top_k and top_p?

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you. How is setting temperature, top_k, or top_p with RetrievalQA.from_chain_type ?

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you. If I use FAISS.from_documents to build my vectorstore, do I need to define temperature, top_k, and top_p and if so how should it be done
?

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you. 

I have

from langchain.vectorstores import FAISS

and then

FAISS.from_documents

If I use FAISS.from_documents to build my vectorstore, do I need to define temperature, top_k, and top_p and if so how should it be done

**Comment by mansourshams** [comment]
@dosu-bot.

Thank you.

in the context of bedrock, which models support or are compatible with defining temperature, top_k, and top_p ?

**Comment by sameemqureshi** [comment]
@dosu-bot,
how do we take a user input for the temperature parameter in model_kwargs?

**Comment by sameemqureshi** [comment]
@dosu-bot
