### ISSUE TITLE
Runnablemap different input for each chain

### ISSUE THREAD

**Issue by vignxs** [langchain-ai/langchain#14098]
### Issue you'd like to raise.

langchain_core.runnables.base.RunnableMap

Im trying use this and i want to know is there any way that i can give different input for each chain

**Comment by vignxs** [comment]
@dosu-bot
Can you share the sample snippet of calling this batch with different inputs?

**Comment by bchabros** [comment]
@vignxs is there any option to use batch method in this way that different input use on different chain in parallel

I have four chians 
```
general_info_chain = chain_parser(general_info, GeneralInfo, document='combined_text'))
first_product_chain = chain_parser(first_product, FirstProduct, document='combined_text')
limits_chain = chain_parser(limits_, Limits, document='combined_text')
clause_chain = chain_parser(clause, Clause, document="chunk"
```

based on this function:
```
def chain_parser(
    prompt: str, pydantic_class: type[T], llm: str = "gpt-4-turbo", document: str = "combined_text"
) -> RunnableSerializable[dict, Any]:
    """Create one prompt chain for parallel chain."""
    parser = PydanticOutputParser(pydantic_object=pydantic_class)

    if llm == "gpt-35-turbo":
        model = AzureChatOpenAI(
            deployment_name=deployment_name,
            model_name="gpt-35-turbo-16k",
            temperature=0.1,
            api_key=current_settings.openai.api_key,
            azure_endpoint=current_settings.openai.endpoint,
            api_version=current_settings.openai.api_version,
        )
    else:
        model = AzureChatOpenAI(
            deployment_name=deployment_name,
            model_name="gpt-4",
            temperature=0.1,
            api_key=current_settings.openai.api_key,
            azure_endpoint=current_settings.openai.endpoint,
            api_version=current_settings.openai.api_version,
        )

    prompt = PromptTemplate(
        template=prompt,
        input_variables=[document],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    return prompt | model | parser
```

I want to run them parallel in that way 
**combined_text** is a str var
**chunks** is list of str 
```
map_chain = RunnableParallel(
    general_info=general_info_chain,
    first_product=first_product_chain,
    limits_deductible=limits_deductible_chain,
    clause=clause_chain
)
parallel_chain = map_chain.batch([{"combined_text": combined_text,  
                                                             "chunk": chunk} for chunk in chunks])
```

But I've got wrong result. Do you have any idea?
Thank you in advance!

**Comment by vignxs** [comment]
``
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.schema.runnable import RunnableParallel
from typing import Any, Dict, Optional
from langchain_core.load.dump import dumpd, dumps
from langchain_core.runnables.config import (
    RunnableConfig,
    ensure_config,
    get_executor_for_config,
    patch_config,
)

class CustomRunnableParallel(RunnableParallel):
    def invoke(self, inputs: Dict[str, Any], config: Optional[RunnableConfig] = None) -> Dict[str, Any]:
        from langchain_core.callbacks.manager import CallbackManager

        

> --Setup callbacks

        config = ensure_config(config)
        callback_manager = CallbackManager.configure(
            inheritable_callbacks=config.get("callbacks"),
            local_callbacks=None,
            verbose=False,
            inheritable_tags=config.get("tags"),
            local_tags=None,
            inheritable_metadata=config.get("metadata"),
            local_metadata=None,
        )
        # Start the root run
        run_manager = callback_manager.on_chain_start(
            dumpd(self), inputs, name=config.get("run_name")
        )

        try:
            steps = dict(self.steps)
            with get_executor_for_config(config) as executor:
                futures = []
                for key, step in steps.items():
                    step_input = inputs.get(key, {}).get('topic')  # Extract the 'topic' from the specific input
                    future = executor.submit(
                        step.invoke,
                        {'topic': step_input},  # Pass 'topic' as expected by the step
                        patch_config(
                            config,
                            callbacks=run_manager.get_child(f"map:key:{key}"),
                        ),
                    )
                    futures.append((key, future))
                output = {key: future.result() for key, future in futures}
        except BaseException as e:
            run_manager.on_chain_error(e)
            raise
        else:
            run_manager.on_chain_end(output)
            return output



``

Usage

from main import CustomRunnableParallel

custom_map_chain = CustomRunnableParallel(joke=joke_chain, poem=poem_chain)
result = custom_map_chain.invoke({
    "joke": {"topic": "bear"},
    "poem": {"topic": "sun"}
})

result

**Comment by vignxs** [comment]
not sure if this helps but this is how I implemented it.
