### ISSUE TITLE
Issue: openai.ChatCompletion is no longer supported in openai>=1.0.0 

### ISSUE THREAD

**Issue by noviljohnson** [langchain-ai/langchain#14107]
### Issue you'd like to raise.

i am using load_qa_chain() 
chain=load_qa_chain(OpenAI(temperature=0.25,model_name="gpt-3.5-turbo-1106"),  chain_type="stuff", prompt=PROMPT)

i got the following error

"""
     APIRemovedInV1: 
    You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at 
    https://github.com/openai/openai-python for the API.

    You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

    Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

   A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
"""

and the line that raised the error is 

anaconda3/envs/Doc2/lib/site-packages/langchain/llms/openai.py:115

**Comment by 169** [comment]
@noviljohnson This is a usage that is no longer supported, you can see the warning message:

```
You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
```

**Comment by noviljohnson** [comment]
i am able to resolve it by using  ` from langchain.chat_models import ChatOpenAI `
instead of  ` from langchain.llms import OpenAIChat `.
