### ISSUE TITLE
Issue:How to get all the Pages of Confluence Spaces.

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#14113]
### Issue you'd like to raise.

I am in need to get all the pages and page id of a particular Confluence Spaces, How can I get all the page id?

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> Sure, I can help with that. You're correct in your understanding of how to use the `ConfluenceLoader` class and the `load` method to retrieve pages from a specific Confluence Space.
> 
> To print all the pages and their respective IDs, you can iterate over the `documents` list and print the `id` and `title` attributes of each `Document` object. Here's how you can modify your code to do this:
> 
> ```python
> from langchain.document_loaders import ConfluenceLoader
> 
> # Initialize the ConfluenceLoader with your Confluence site details and credentials
> loader = ConfluenceLoader(
>     url="https://yoursite.atlassian.com/wiki",
>     username="me",
>     api_key="12345"
> )
> 
> # Load the documents from a specific space
> documents = loader.load(space_key="SPACE", include_attachments=True, limit=50)
> 
> # Print all the pages and their respective IDs
> for document in documents:
>     print(f"Page ID: {document.id}, Page Title: {document.title}")
> ```
> 
> In this code, `"SPACE"` should be replaced with your actual Confluence Space key. The `load` method will return a list of `Document` objects, each representing a page in the specified Confluence Space. The `for` loop then iterates over each `Document` object in the `documents` list, and the `print` function is used to print the `id` and `title` of each page.
> 
> Please note that the `limit` parameter in the `load` method specifies the maximum number of documents to retrieve in a single API call, not the total number of documents to retrieve. If you want to control the total number of documents to retrieve, you can use the `max_pages` parameter.
> 
> I hope this helps! If you have any further questions, feel free to ask.
> 
> For more information, you can refer to the [ConfluenceLoader class in the langchain/document_loaders/confluence.py file](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/confluence.py) and the [Document class in the langchain_core/documents/base.py file](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/documents/base.py) in the LangChain repository.
> 
> ## Sources
> * [libs/langchain/langchain/document_loaders/confluence.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/confluence.py)
> * [libs/core/langchain_core/documents/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/documents/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

   print(f"Page ID: {document.id}, Page Title: {document.title}")
AttributeError: 'Document' object has no attribute 'id'

**Comment by sameermahajan** [comment]
I am having the same problem with the code shown here.

**Comment by deepak-habilelabs** [comment]
> I am having the same problem with the code shown here.
@sameermahajan 
Its already been solved, dm me for the source code :)

**Comment by sameermahajan** [comment]
@deepak-habilelabs I have also opened https://github.com/langchain-ai/langchain/issues/15869 with more details for the issue that I am facing. I believe @GauravWaghmare is looking at that currently.
