### ISSUE TITLE
Expose Amazon Bedrock amazon-bedrock-invocationMetrics in response

### ISSUE THREAD

**Issue by ben-gineer** [langchain-ai/langchain#14120]
### Feature request

Amazon Bedrock now provides some useful metrics when it has finished:

`"completion":"Response from Bedrock...","stop_reason":"stop_sequence","stop":"\n\nHuman:","amazon-bedrock-invocationMetrics":{"inputTokenCount":16,"outputTokenCount":337,"invocationLatency":4151,"firstByteLatency":136}}`

It would be good to expose these via LangChain, similar to how OpenAI API provides them.

### Motivation

To make it easier to calculate the cost of Amazon Bedrock queries.

### Your contribution

I'm happy to test any solution. I'd look to existing developers to guide us how best to expose them.

**Comment by shabie** [comment]
Did you have something like this in mind https://python.langchain.com/docs/modules/model_io/llms/token_usage_tracking?

**Comment by ben-gineer** [comment]
Yep. Something like that.

**Comment by thiagotps** [comment]
This issue is important. Langchain api should not thrown out useful bedrock data.
