### ISSUE TITLE
Volc Engine MaaS has wrong entry in LLM type to class dict (causing SpaCy to not work with LangChain anymore)

### ISSUE THREAD

**Issue by DirkKoelewijn** [langchain-ai/langchain#14127]
### System Info

* Windows 11 Home (build 22621.2715)
* Python 3.12.0
* Clean virtual environment using Poetry with following dependencies:
```
python = "3.12.0"
langchain = "0.0.344"
spacy = "3.7.2"
spacy-llm = "0.6.4"
```

### Who can help?

@h3l As the creator of the pull request where VolcEngine was introduced
@baskaryan As tag handler of that pull request

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Anything that triggers spaCy's registry to make an inventory, for example:

```python
import spacy

spacy.blank("en")
```

With the last part of the Traceback being:
```
  File "PROJECT_FOLDER\.venv\Lib\site-packages\langchain\llms\__init__.py", line 699, in __getattr__
    k: v() for k, v in get_type_to_cls_dict().items()
       ^^^
  File "PROJECT_FOLDER\.venv\Lib\site-packages\langchain_core\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "PROJECT_FOLDER\.venv\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for VolcEngineMaasLLM
__root__
  Did not find volc_engine_maas_ak, please add an environment variable `VOLC_ACCESSKEY` which contains it, or pass  `volc_engine_maas_ak` as a named parameter. (type=value_error)
```

#### What I think causes this

I am quite certain that this is caused by [`langchain.llms.__init__.py:869 (for commit b161f30)`](https://github.com/langchain-ai/langchain/blob/b161f302ff56a14d8d0331cbec4a3efa23d06e1a/libs/langchain/langchain/llms/__init__.py#L869C51-L869C51):

```python
def get_type_to_cls_dict() -> Dict[str, Callable[[], Type[BaseLLM]]]:
    return {
        "ai21": _import_ai21,
        "aleph_alpha": _import_aleph_alpha,
        "amazon_api_gateway": _import_amazon_api_gateway,
        ...
        "qianfan_endpoint": _import_baidu_qianfan_endpoint,
        "yandex_gpt": _import_yandex_gpt,
        # Line below is the only that actually calls the import function, returning a class instead of an import function
        "VolcEngineMaasLLM": _import_volcengine_maas(),
    }
```

The Volc Engine Maas LLM is the only in this dict to actually call the import function, while all other entries only the function itself, and do not call it.

### Expected behavior

Class to type dict only returns import functions, not actual classes:

```python
def get_type_to_cls_dict() -> Dict[str, Callable[[], Type[BaseLLM]]]:
    return {
        "ai21": _import_ai21,
        "aleph_alpha": _import_aleph_alpha,
        "amazon_api_gateway": _import_amazon_api_gateway,
        ...
        "qianfan_endpoint": _import_baidu_qianfan_endpoint,
        "yandex_gpt": _import_yandex_gpt,
        # What I think would be correct (now without function call)
        "VolcEngineMaasLLM": _import_volcengine_maas,
    }
```

Unfortunately I don't have time to put in a PR myself, but I hope this helps finding the solution!

**Comment by DirkKoelewijn** [comment]
For anyone else having this problem:

The workaround for now is to fix the langchain version to `0.0.343` until this issue is resolved.

**Comment by h3l** [comment]
@DirkKoelewijn Thank you for identifying this bug. I have submitted a Pull Request and am now awaiting for it to be merged.

**Comment by DirkKoelewijn** [comment]
Thank you very much!
