### ISSUE TITLE
Amazon DocumentDB Vector Store

### ISSUE THREAD

**Issue by ip9inderpreet** [langchain-ai/langchain#14140]
### Feature request

Amazon DocumentDB has launched its vector search feature recently. Let us add Amazon DocumentDB as vector store in langchain.

### Motivation

This will help large customer base of Amazon DocumentDB to adopt langchain and seamlessly build AI/ML apps

### Your contribution

Amazon DocumentDB team can help with testing and technical help. 
https://aws.amazon.com/about-aws/whats-new/2023/11/vector-search-amazon-documentdb/
https://docs.aws.amazon.com/documentdb/latest/developerguide/vector-search.html

**Comment by prajwalsaokar** [comment]
@vidur2 and I are interested in working on this! We sent over a quick email if you're still open to collaboration.

**Comment by andywonderboi** [comment]
Question, based on this thread I'm assuming no but can the langchain imports for mongodb atlas be used with a DocumentDB endpoint? 
https://python.langchain.com/docs/integrations/vectorstores/mongodb_atlas

**Comment by hrbf-tech** [comment]
I have the same question.  How can we use langchain with documentDB?

**Comment by ip9inderpreet** [comment]
Hi All, We will contribute to langchain for integrating DocumentDB as vector store soon. Meanwhile, you can use LLM module of langchain and use API of DocumentDB directly to build your solution.

**Comment by hrbf-tech** [comment]
> Hi All, We will contribute to langchain for integrating DocumentDB as vector store soon. Meanwhile, you can use LLM module of langchain and use API of DocumentDB directly to build your solution.

Thanks for the reply. Could you share a workshop or tutorial on how to implement the solution via API that you propose?

**Comment by ip9inderpreet** [comment]
Hi Team, Here is the PR to resolve this issue: https://github.com/langchain-ai/langchain/pull/17757
