### ISSUE TITLE
Issue:  'BM25Retriever' has no attribute 'from_documents'

### ISSUE THREAD

**Issue by arnavroh45** [langchain-ai/langchain#14167]
### Issue you'd like to raise.

Code: 
retriever = BM25Retriever.from_documents(
    [
        Document(page_content="foo"),
        Document(page_content="bar"),
        Document(page_content="world"),
        Document(page_content="hello"),
        Document(page_content="foo bar"),
    ]
)

Error:
---> 30 retriever = BM25Retriever.from_documents(
     31     [
     32         Document(page_content="foo"),
     33         Document(page_content="bar"),
     34         Document(page_content="world"),
     35         Document(page_content="hello"),
     36         Document(page_content="foo bar"),
     37     ]
     38 )

AttributeError: type object 'BM25Retriever' has no attribute 'from_documents'

**Comment by umair313** [comment]
@arnavroh45 what Langchain Version you are using kindly use the updated version.

**Comment by arnavroh45** [comment]
> @arnavroh45 what Langchain Version you are using kindly use the updated version.

I am using Version: 0.0.350
