### ISSUE TITLE
Cloudflare Vectorize Support

### ISSUE THREAD

**Issue by Manouchehri** [langchain-ai/langchain#14179]
### Feature request

Looks like it should be doable to have Cloudflare Vectorize support, as there's a HTTP API for Vectorize.

https://developers.cloudflare.com/api/operations/vectorize-list-vectorize-indexes

### Motivation

Similar to langchain-js, it would be nice if we could use Cloudflare Vectorize when using LangChain with Python. It would allow us to use the same vector store for both our TypeScript Workers and Python Lambdas.

https://js.langchain.com/docs/integrations/vectorstores/cloudflare_vectorize

### Your contribution

N/A sadly

**Comment by tddschn** [comment]
Langchain JS supports vectorize while the python library doesn't. I think this is a valid issue and should be re-opened and @Manouchehri has provided all the info necessary for this feature request.

**Comment by AkshataDM** [comment]
+1 any updates on this?  A lot of functionalities like Re ranking make use of functions from Langchain's VectorStore class. Would be really great to have this integration in Python.
