### ISSUE TITLE
Add new Document Loader for JIRA

### ISSUE THREAD

**Issue by Wosin** [langchain-ai/langchain#14180]
### Feature request

I think Langchain should have a Document Loader that would allow reading all issues from provided project as documents.

### Motivation

Langchain currently has agent for JIRA, but there is no Document Loader that would allow to read all issues from specified project and store them in Vector database. This could be a very useful tool for RAG usecases and building internal knowledge bases in the companies. 

### Your contribution

I can create a PR for this issue.

**Comment by clej37** [comment]
@Wosin any progress on this that you could share (given that you suggested to create a PR)?
