### ISSUE TITLE
Passing BaseModel type data from agent to tool

### ISSUE THREAD

**Issue by dongho0505** [langchain-ai/langchain#14192]
### Issue you'd like to raise.

We create an agent using initialize_agent, register the tool, and configure it to be selected through the agent.
However, in the agent, regardless of which tool is selected, I want to pass a data object called request of BaseModel type when executing the tool.
I would appreciate it if you could tell me how to configure and connect the agent and tool.

**Comment by keenborder786** [comment]
For this you can use a Custom Tool in which you can pass custom objects. Please see this: https://python.langchain.com/docs/modules/agents/tools/custom_tools
