### ISSUE TITLE
How do i use system prompt template inside conversational retrieval chain?

### ISSUE THREAD

**Issue by Kunal1505** [langchain-ai/langchain#14191]
@dosubot  , how do i use system prompt inside conversational retreival chain?
prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(
            "You are a nice chatbot named James-AI having a conversation with a human."
        ),
        MessagesPlaceholder(variable_name="chat_history"),
        HumanMessagePromptTemplate.from_template("{question}")]
)

memory = ConversationBufferWindowMemory(k=5, memory_key="chat_history", return_messages=True)
**retriever = new_db.as_retriever(search_type="similarity_score_threshold", 
                                 search_kwargs={"score_threshold": .65, 
                                                "k": 2})**

**qa = ConversationalRetrievalChain.from_llm(cfg.llm, verbose=True,retriever=retriever, memory=memory, prompt=prompt)**
                                              
if i use like that then it says 
ValidationError: 1 validation error for ConversationalRetrievalChain
prompt
  extra fields not permitted (type=value_error.extra)

**Comment by Kunal1505** [comment]
@dosubot , if i use return source documents is true in conversational retreival chain then i get this error
ValueError: One output key expected, got dict_keys(['answer', 'source_documents'])

**Comment by Kunal1505** [comment]
@dossubot im using conversationalbufferwindow memory and i want it to return source documnets but seems like conversational retreival chain does not have it

memory = ConversationBufferWindowMemory(k=5, memory_key="chat_history", return_messages=True, output_key="answer")

retriever = load_emdeddings(cfg.faiss_persist_directory, cfg.embeddings).as_retriever(search_type="similarity_score_threshold", 
                                 search_kwargs={"score_threshold": .65, 
                                                "k": 2})
custom_prompt_template = """
You are a friendly chatbot named "HR Navigator" having a conversation with a human.
{context}
Chat History: {chat_history}

Question: {question}
"""

# Create a PromptTemplate instance with your custom template
custom_prompt = PromptTemplate(
    template=custom_prompt_template,
    input_variables=["context", "question", "chat_history"],
)
# Use your custom prompt when creating the ConversationalRetrievalChain
qa = ConversationalRetrievalChain.from_llm(
    cfg.llm,
    verbose=False,
    retriever=retriever,
    memory=memory,
    combine_docs_chain_kwargs={"prompt": custom_prompt},
    return_source_documents = True
)

**Comment by llamasrock** [comment]
Hey @dosubot,

With the first solution you provided, how do we pass on the context of the template to the ConversationalRetrievalChain?

```
from langchain.prompts import PromptTemplate

# Define your custom prompt template
custom_prompt_template = """
{context}

Question: {question}
"""

# Create a PromptTemplate instance with your custom template
custom_prompt = PromptTemplate(
    template=custom_prompt_template,
    input_variables=["context", "question"],
)

# Use your custom prompt when creating the ConversationalRetrievalChain
qa = ConversationalRetrievalChain.from_llm(
    cfg.llm,
    verbose=True,
    retriever=retriever,
    memory=memory,
    combine_docs_chain_kwargs={"prompt": custom_prompt},
)
```

**Comment by MayankOrManiyo** [comment]
hey, @dosu-bot
