### ISSUE TITLE
TypeError: 'HumanMessage' object is not subscriptable

### ISSUE THREAD

**Issue by Kunal1505** [langchain-ai/langchain#14196]
Hey @dosubot, im using this code
memory = ConversationBufferMemory(
    return_messages=True, output_key="answer", input_key="question"
)

retriever = load_emdeddings(cfg.faiss_persist_directory, cfg.embeddings).as_retriever(search_type="similarity_score_threshold", 
                                 search_kwargs={"score_threshold": .65, 
                                                "k": 2})

memory.load_memory_variables({})
_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:"""
CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(_template)

template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
ANSWER_PROMPT = ChatPromptTemplate.from_template(template)

DEFAULT_DOCUMENT_PROMPT = PromptTemplate.from_template(template="{page_content}")

def _combine_documents(
    docs, document_prompt=DEFAULT_DOCUMENT_PROMPT, document_separator="\n\n"
):
    doc_strings = [format_document(doc, document_prompt) for doc in docs]
    return document_separator.join(doc_strings)
def _format_chat_history(chat_history: List[Tuple[str, str]]) -> str:
    # chat history is of format:
    # [
    #   (human_message_str, ai_message_str),
    #   ...
    # ]
    # see below for an example of how it's invoked
    buffer = ""
    for dialogue_turn in chat_history:
        human = "Human: " + dialogue_turn[0]
        ai = "Assistant: " + dialogue_turn[1]
        buffer += "\n" + "\n".join([human, ai])
    return buffer

_inputs = RunnableParallel(
    standalone_question=RunnablePassthrough.assign(
        chat_history=lambda x: _format_chat_history(x["chat_history"])
    )
    | CONDENSE_QUESTION_PROMPT
    | ChatOpenAI(temperature=0)
    | StrOutputParser(),
)

_context = {
    "context": itemgetter("standalone_question") | retriever | _combine_documents,
    "question": lambda x: x["standalone_question"],
}
conversational_qa_chain = _inputs | _context | ANSWER_PROMPT | ChatOpenAI()

loaded_memory = RunnablePassthrough.assign(
    chat_history=RunnableLambda(memory.load_memory_variables) | itemgetter("history")
)
# Now we calculate the standalone question
standalone_question = {
    "standalone_question": {
        "question": lambda x: x["question"],
        "chat_history": lambda x: _format_chat_history(x["chat_history"]),
    }
    | CONDENSE_QUESTION_PROMPT
    | ChatOpenAI(temperature=0)
    | StrOutputParser(),
}
# Now we retrieve the documents
retrieved_documents = {
    "docs": itemgetter("standalone_question") | retriever,
    "question": lambda x: x["standalone_question"],
}
# Now we construct the inputs for the final prompt
final_inputs = {
    "context": lambda x: _combine_documents(x["docs"]),
    "question": itemgetter("question"),
}
# And finally, we do the part that returns the answers
answer = {
    "answer": final_inputs | ANSWER_PROMPT | ChatOpenAI(),
    "docs": itemgetter("docs"),
}
# And now we put it all together!
final_chain = loaded_memory | standalone_question | retrieved_documents | answer

inputs = {"question": "what is my name?"}
result = final_chain.invoke(inputs)
memory.save_context(inputs, {"answer": result["answer"].content})
result

**if i run this second time then im getting this error
TypeError: 'HumanMessage' object is not subscriptable**

**Comment by keenborder786** [comment]
@Kunal1505 I can help you if you can please make your code more cleaner. Please use ```python when writing code.

**Comment by umair313** [comment]
can't read the code at all.

**Comment by iandailey** [comment]
I ran into the same problem. The issue is the _format_chat_history function. The HumanMessage type and the AIMessage type of the tuple do not allow you to index, so using dialogue_turn[0] and dialogue_turn[1] won't work.

To solve this, I converted the message content into strings and then added them to a new list. I then took the new list and made it a list of tuples. Now that the tuple list are all strings, it is subscriptable as needed. It may not be efficient but it works. 

Here is my code:
```python
def _format_chat_history(chat_history: List[Tuple]) -> str:
  buffer = ""
  chat_str = []
  for dialogue_turn in chat_history:
    chat_str.append(dialogue_turn.content)
  tup_list = [(chat_str[i], chat_str[i+1]) for i in range(len(chat_str)-1)]
  for dialogue_turn in tup_list:
    human = "Human: " + dialogue_turn[0]
    ai = "Assistant: " + dialogue_turn[1]
    buffer += "\n" + "\n".join([human, ai])

  
  return buffer
