### ISSUE TITLE
ConversationalRetrievalChain returns sources to questions without context

### ISSUE THREAD

**Issue by sergej-d** [langchain-ai/langchain#14203]
### Issue you'd like to raise.

Hi,

I am wondering if anyone has a work around using ConversationalRetrievalChain to retrieve documents with their sources, and prevent the chain from returning sources for questions without sources.

query = "How are you doing?"
result = chain({"question": query, "chat_history": chat_history})
result['answer']

"""
I'm doing well, thank you.

SOURCES: /content/xxx.pdf
"""

### Suggestion:

SOURCES:

**Comment by umair313** [comment]
@sergej-d  you can use threshold for this 
https://python.langchain.com/docs/modules/data_connection/retrievers/vectorstore#similarity-score-threshold-retrieval

**Comment by Ignat2003** [comment]
I have the same problem
