### ISSUE TITLE
ConversationChain error with multiple inputs

### ISSUE THREAD

**Issue by markwealthio** [langchain-ai/langchain#14210]
### Issue you'd like to raise.

ValidationError: 2 validation errors for ConversationChain
advisor_summary
  extra fields not permitted (type=value_error.extra)
__root__
  Got unexpected prompt input variables. The prompt expects ['advisor_summary', 'history', 'input'], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error)
  
  How to resolve this error?

**Comment by umair313** [comment]
@markwealthio please provide other information as well
- relevant code
- python, langchain versions

**Comment by markwealthio** [comment]
Hi @umair313 

I am trying to do the following:

Behave like the Professor with the following details {details}
                          
Current conversation:
{history}
Human: {input}
Anna:
"""

PROMPT = PromptTemplate(input_variables=["history", "input", "details"], template=template)
conversation = ConversationChain(
    prompt=PROMPT,
    llm=llm,
    verbose=False,
    memory=ConversationBufferWindowMemory(k=5, ai_prefix="Anna"),
)

I want to do something like this. Would appreciate any help!
