### ISSUE TITLE
BiliBiliLoader Credential No Sessdata error

### ISSUE THREAD

**Issue by Jiaaming** [langchain-ai/langchain#14213]
### System Info

Mac os
Python3.9

### Who can help?

@Jiaaming
I'm working on this issue.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

when you run the BiliBiliLoader example from the official [docs](https://python.langchain.com/docs/integrations/document_loaders/bilibili)
```
loader = BiliBiliLoader(
        [
            "https://www.bilibili.com/video/BV1g84y1R7oE/",
        ]
    )
docs = loader.load()
print(docs)
```
will get
```
bilibili_api.exceptions.CredentialNoSessdataException.CredentialNoSessdataException: Credential 类未提供 sessdata 或者为空。

Process finished with exit code 1
```

The is because the original [bilibili_api](https://nemo2011.github.io/bilibili-api/#/get-credential) require a Credential to fetch the info from the video

### Expected behavior

Should return a Document object
```
[Document(page_content="Video Title:...,description:....)]
```

**Comment by Jiaaming** [comment]
Already open a pull request [here](https://github.com/langchain-ai/langchain/pull/14214)

**Comment by Shengguang-Zhou** [comment]
It's still not been solved

**Comment by fenghuoliansanyue** [comment]
Modify the following file:
\Lib\site-packages\langchain_community\document_loaders\bilibili.py

Add the following in the call library function area:
```
from bilibili_api import Credential
sessdata = ""
bili_jct = ""
buvid3 = ""
credential = Credential(sessdata=sessdata, bili_jct=bili_jct, buvid3=buvid3)
```
See this link below for more information:
https://geekdaxue.co/read/bilibili-api-docs/docs-get-credential.md
then,find the following code:
`v = video.Video(bvid=bvid.group())`
change to:
`v = video.Video(bvid=bvid.group(), credential=credential)`
then,it will be ok!
**Do not disclose the above information to others!!!**
