### ISSUE TITLE
Filters dont work with Azure Search Vector Store retriever

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#14227]
### System Info

langchain                 0.0.342
langchain-core            0.0.7
azure-search-documents    11.4.0b8

Python: 3.10

### Who can help?

@hw

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The following code works fine:

```
from langchain_core.vectorstores import VectorStore, VectorStoreRetriever

index_name: str = "langchain-vector-demo"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name="vector-1701341754619",
    embedding_function=embeddings.embed_query
)

res = vector_store.similarity_search(
    query="Can Colleagues contact their managers?", k=20, search_type="hybrid",  filters="title eq '25_1_0.pdf'")

The res object contains the chunkcs where title is 25_1_0.pdf' ONLY
```

However when using it with an LLM:

```
llm = AzureChatOpenAI(
    azure_deployment="chat",
    openai_api_version="2023-05-15",
)
    
retriever = vector_store.as_retriever(search_type="similarity", filters="title eq '25_1_0.pdf'", kwargs={"k": 3})
chain = RetrievalQA.from_chain_type(llm=llm,
                                    chain_type="stuff",
                                    retriever=retriever,
                                    return_source_documents=True)

result = chain({"query": 'Can Colleagues contact their managers??'})

for res in result['source_documents']:
    print(res.metadata['title'])
```

My output has chunks which dont respect the filter:

142_2_0.pdf
99_9_0.docx
99_9_0.docx
142_2_0.pdf

### Expected behavior

The answer generated with source_documents, should contain chunks which respects the given filters.

**Comment by Gauravmahapatrocdm** [comment]
Hey, I am also looking for the similar solution, Did you find any solutions around this?

**Comment by lkartawidjaja** [comment]
@Gauravmahapatrocdm, I was able to have the filter working by passing it as a search keyword arguments.

In the above example, I got it working by using the following:
`retriever = vector_store.as_retriever(search_kwargs={"k":3, filters="title eq '25_1_0.pdf'"})`

**Comment by HeroAntagonist** [comment]
retriever = vector_store.as_retriever(search_kwargs={"k":3, filters="title eq '25_1_0.pdf'"})
@lkartawidjaja How did this work if the kwargs only accepts dict format and filters=... is not in dict format?

**Comment by lkartawidjaja** [comment]
@HeroAntagonist. My bad it should be:
`retriever = vector_store.as_retriever(search_kwargs={"k":3, “filters”: “title eq '25_1_0.pdf'"})`

**Comment by PaSchwarz** [comment]
i'm facing the same issue and the solution from @lkartawidjaja is not working for me.

vectorstore.similarity_search(query="*", top_k=3, search_type="hybrid", filters="user_id eq '52436546'") ist working fine and giving me:
[Document(page_content='test', metadata={'file_name': 'test - kopie.txt', 'user_id': '52436546'})]

but when using it as retriever the filter is not applied properly:
retriever = self.vectorstore.as_retriever(search_kwargs={"filters":"user_id eq '52436546'"})
print(retriever.invoke("*"))

gives me: [Document(page_content='test', metadata={'file_name': 'test - kopie.txt', 'user_id': '52436546'}), Document(page_content='test', metadata={'file_name': 'test.txt', 'user_id': '584eae6a-e8a2-44c1-ba76-3870586a489d'}), Document(page_content='test', metadata={'file_name': 'test - kopie.txt', 'user_id': '524365461'}), Document(page_content='Dein Name ist Hans Hubert', metadata={'file_name': 'name2.txt', 'user_id': '524365461'})]
