### ISSUE TITLE
DOC: How to create a custom filtered retriever

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#14229]
### Issue with current documentation:

I cant find documentattion about filtered retrievers, basically I want to fix this issue: https://github.com/langchain-ai/langchain/issues/14227

### Idea or request for content:

And according to other github issues, the way to fix it is with custom filtered retrievers.

So I tried the following:

```
class FilteredRetriever:
    def __init__(self, retriever, title):
        self.retriever = retriever
        self.title = title

    def retrieve(self, *args, **kwargs):
        results = self.retriever.retrieve(*args, **kwargs)
        return [doc for doc in results if doc['title'].startswith(self.title)]

filtered_retriever = FilteredRetriever(vector_store.as_retriever(), '25_1_0.pdf')

llm = AzureChatOpenAI(
    azure_deployment="chat",
    openai_api_version="2023-05-15",
)
    
retriever = vector_store.as_retriever(search_type="similarity",  kwargs={"k": 3})
chain = RetrievalQA.from_chain_type(llm=llm,
                                    chain_type="stuff",
                                    retriever=filtered_retriever,
                                    return_source_documents=True)

result = chain({"query": 'Can Colleagues contact their managers??'})

for res in result['source_documents']:
    print(res.metadata['title'])
```

However I get this error:
```
ValidationError: 1 validation error for RetrievalQA
retriever
  value is not a valid dict (type=type_error.dict)
```

but as I cant find documentation about it, I am not sure how to solve it

**Comment by levalencia** [comment]
@dosubot 

ValueError: "FilteredRetriever" object has no field "retriever"

**Comment by Ge7alt** [comment]
I too am trying to create a custom retriever, and i want to instantiate the object with the classname

but i am getting the error `TypeError: Serializable.__init__() takes 1 positional argument but 2 were given`
```
class CustomRetriever(BaseRetriever, BaseModel):
    classname: str

    def _get_relevant_documents(
        self, 
        query: str, 
        *,
        run_manager: CallbackManagerForRetrieverRun, 
        # **kwargs,
    ) -> List[Document]:

        results = search(self, query, self.classname, limit=5)

        documents = []
        for result in results["data"]["Get"][self.classname]:
            doc = Document(
                page_content=result["content"],
                metadata={"source": result["source"],
                          "page": result["page"],
                          'score': result["_additional"]['certainty']
                          }
            )
            documents.append(doc)
        return documents
```

**Comment by jkyamog** [comment]
> @levalencia I had the same problem. Solved by doing these 4 things:
> 
> 1. removing **init** method from the class
> 2. Inheriting the MyCustomRetriever not only from `BaseRetriever` but also from `base model`
> 3. specifying the custom fields inside the class itself.
> 4. having pydantic <2 and langchain >0.1
>    Here is my implementation, I hope it will help
> 
> ```
> from langchain_core.retrievers import BaseRetriever
> class LangchainBasedRetriever(BaseRetriever, BaseModel):
>     sas_token: str
>     oid: str
>         
>     def _get_relevant_documents(
>         self, query: str, *, run_manager: CallbackManagerForRetrieverRun
>     ):
>         search_engine = SimilaritySearch(self.oid)
>         similarity_search_results = search_engine.similarity_search_new(query, self.sas_token)
>         return similarity_search_results
> 
> retriever = LangchainBasedRetriever(sas_token="sfdgjskldfgj", oid="sdsdfgsdf")
> ```

Thanks for this.  What made it work is your hint to downgrade pydantic.  

`pip install 'pydantic<2' `

could this be related to #7835
