### ISSUE TITLE
Dall-E Image Generator return url without authentication information

### ISSUE THREAD

**Issue by majiayu000** [langchain-ai/langchain#14223]
### System Info

MacOS

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

As described in the [docs page](https://python.langchain.com/docs/integrations/tools/dalle_image_generator):

```
from langchain.agents import initialize_agent, load_tools

tools = load_tools(["dalle-image-generator"])
agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
output = agent.run("Create an image of a halloween night at a haunted museum")
```

Below is output:
```
> Entering new AgentExecutor chain...
 I need to generate an image from a text description
Action: Dall-E-Image-Generator
Action Input: "Halloween night at a haunted museum"
Observation: https://oaidalleapiprodscus.blob.core.windows.net/private/org-yt03sAlJZ8YRfqIcNivAAqZu/user-xV6mgISZftMROz9SukNqCHqH/img-EKpmrjqlb1988YrkkBm0vgjr.png?st=2023-12-04T08%3A30%3A50Z&se=2023-12-04T10%3A30%3A50Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-03T23%3A02%3A03Z&ske=2023-12-04T23%3A02%3A03Z&sks=b&skv=2021-08-06&sig=9TvprwW3Wl3ZHj%2B2ga6juBT1KQLJIc9TUz%2BDIVcd3XA%3D
Thought: I now know the final answer
Final Answer: https://oaidalleapiprodscus.blob.core.windows.net/private/org-yt03sAlJZ8YRfqIcNivAAqZu/user-xV6mgISZftMROz9SukNqCHqH/img-EKpmrjqlb1988YrkkBm0vgjr.png?st=2023-12-04T08%3A30%3A50Z&se=2023-12-04T10%3A30%3A50Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-03T23%3A02%3A03Z&ske=2023-12-04T23%

> Finished chain.
```

Seems ok? But the url has been cut, it not origin! So you will not get the right picture.

Instead got this:
<img width="1472" alt="image" src="https://github.com/langchain-ai/langchain/assets/19658300/f856e606-9d9e-466d-bd8f-de4eed70f15c">

### Expected behavior

Dalle is a import tool in openai. 

I want get the picture which I can see it. So it should give me the origin link.

Just like this:
```
> Entering new AgentExecutor chain...
I can use the Dall-E-Image-Generator to generate an image of a volcano island based on the text description.
Action: Dall-E-Image-Generator
Action Input: "A volcano island"
Observation: https://oaidalleapiprodscus.blob.core.windows.net/private/org-yt03sAlJZ8YRfqIcNivAAqZu/user-xV6mgISZftMROz9SukNqCHqH/img-H3m0wSNxDXVUkUKiE9kOKgvg.png?st=2023-12-04T09%3A39%3A05Z&se=2023-12-04T11%3A39%3A05Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-03T22%3A42%3A28Z&ske=2023-12-04T22%3A42%3A28Z&sks=b&skv=2021-08-06&sig=WSEO5/OX5GgYaNTWxZhNmsK%2BqeaDLMEsDdGEnHX18BY%3D
Thought:I now know the final answer.
Final Answer: The image of a volcano island can be found at the following link: https://oaidalleapiprodscus.blob.core.windows.net/private/org-yt03sAlJZ8YRfqIcNivAAqZu/user-xV6mgISZftMROz9SukNqCHqH/img-H3m0wSNxDXVUkUKiE9kOKgvg.png?st=2023-12-04T09%3A39%3A05Z&se=2023-12-04T11%3A39%3A05Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-03T22%3A42%3A28Z&ske=2023-12-04T22%3A42%3A28Z&sks=b&skv=2021-08-06&sig=WSEO5/OX5GgYaNTWxZhNmsK%2BqeaDLMEsDdGEnHX18BY%3D

> Finished chain.
The image of a volcano island can be found at the following link: https://oaidalleapiprodscus.blob.core.windows.net/private/org-yt03sAlJZ8YRfqIcNivAAqZu/user-xV6mgISZftMROz9SukNqCHqH/img-H3m0wSNxDXVUkUKiE9kOKgvg.png?st=2023-12-04T09%3A39%3A05Z&se=2023-12-04T11%3A39%3A05Z&sp=r&sv=2021-08-06&sr=b&rscd=inline&rsct=image/png&skoid=6aaadede-4fb3-4698-a8f6-684d7786b067&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2023-12-03T22%3A42%3A28Z&ske=2023-12-04T22%3A42%3A28Z&sks=b&skv=2021-08-06&sig=WSEO5/OX5GgYaNTWxZhNmsK%2BqeaDLMEsDdGEnHX18BY%3D
```

**Comment by yuewenma** [comment]
@majiayu000 Have you solved this issue? I also encountered the same problem.

**Comment by majiayu000** [comment]
> @majiayu000 Have you solved this issue? I also encountered the same problem.

I did not fix this.

**Comment by dave-16** [comment]
the Dall-E generated links will only work for 1 hour so what you should do is get the url then download it or if you want to use like firebase you can use the api to uplod to the bucket and get the downloadable url but when uploading to firebase make the expiration date to un expiredable or set duration
`def upload_image_to_firebase(image_url):
    try:
        # Fetch the image from the URL
        response = requests.get(image_url)
        if response.status_code != 200:
            raise Exception(f"Failed to fetch image from {image_url}")

        # Upload the image to Firebase Storage
        blob = bucket.blob('images/image.jpg')

        # Convert image content to bytes
        image_bytes = BytesIO(response.content)

        # Upload image bytes to Firebase Storage
        blob.upload_from_file(image_bytes, content_type='image/jpeg')

        # Get the download URL with a far-future expiration time (e.g., one year)
        expiration_time = datetime.datetime.utcnow() + datetime.timedelta(days=365*10)  # Set to expire in 10 years
        download_url = blob.generate_signed_url(expiration=expiration_time, method='GET')
        
        return download_url`
