### ISSUE TITLE
`OpenAIChat` returns only one result

### ISSUE THREAD

**Issue by smileehn** [langchain-ai/langchain#1422]
`OpenAIChat` currently returns only one result even if `n > 1`:

```
full_response = completion_with_retry(self, messages=messages, **params)
return LLMResult(
    generations=[
        [Generation(text=full_response["choices"][0]["message"]["content"])]
    ],
    llm_output={"token_usage": full_response["usage"]},
)
```

Multiple choices in `full_response["choices"]` should be used to create multiple `Generation`s.

**Comment by xgdyp** [comment]
I also encountered this problem.

**Comment by Yongtae723** [comment]
I reply this issue for person who have the same issue

you can generate multiple result by something like

```python
model = ChatOpenAI(model="gpt-4", n=4)

message = model.generate(
    messages = [messages],
)
```

※note : Type of messages is `List[List[BaseMessage]]` , not `List[BaseMessage]` which we usually use for `predict_messages`
