### ISSUE TITLE
Error YahooFinanceNewsTool() Tools

### ISSUE THREAD

**Issue by wwExpert** [langchain-ai/langchain#14248]
### System Info

When running the tool: Error YahooFinanceNewsTool() 
the following error message is displayed:

```
File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\tools\yahoo_finance_news.py", line 66, in <listcomp>
    if query in doc.metadata["description"] or query in doc.metadata["title"]
KeyError: 'description'
```

I have tried to reproduce the error. It looks like the docs element does not contain a field that can return a "description".

```
        loader = WebBaseLoader(web_paths=links)
        docs = loader.load()
        print(docs) # only insert for test
```
output print (docs):

....
tieren\nAlle ablehnen\nDatenschutzeinstellungen verwalten\n\n\n\n\n\nZum Ende\n                    \n\n\n\n\n\n\n\n\n\n\n\n\n', metadata={'source': 'https://finance.yahoo.com/m/280830e6-928c-3b1f-97f4-bd37147499cb/not-even-tesla-bulls-love-the.html', 'title': 'Yahooist Teil der Yahoo Markenfamilie', 'language': 'No language found.'}), Document(page_content='\n\n\nYahooist Teil der Yahoo Markenfamilie\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n    guce           guce     \n\n\n\n    Yahoo ist Teil der Yahoo MarkenfamilieDie Websites und Apps, die wir betreiben und verwalten, einschließlich Yahoo und AOL, sowie unser digitaler Werbedienst Yahoo Advertising.Yahoo Markenfamilie.\n\n    Bei der Nutzung unserer Websites und Apps verwenden wir CookiesMithilfe von Cookies (einschließlich ähnlicher Technologien wie der Webspeicherung) können die Betreiber von Websites und Apps Informationen auf Ihrem Gerät speichern und ablesen. Weitere Informationen finden Sie in unserer Cookie-Richtlinie.Cookies, um:\n\n\nunsere Websites und Apps für Sie bereitzustellen\nNutzer zu authentifizieren, Sicherheitsmaßnahmen anzuwenden und Spam und Missbrauch zu verhindern, und\nIhre Nutzung unserer Websites und Apps zu messen\n\n\n\n    Wenn Sie auf „Alle akzeptieren“ klicken, verwenden wir und unsere Partner (einschließlich der 239, die dem IAB Transparency & Consent Framework angehören) Cookies und Ihre personenbezogenen Daten, wie IP-Adresse, genauen Standort sowie Browsing- und Suchdaten, auch für folgende Zwecke:\n\n\npersonalisierte Werbung und Inhalte auf der Grundlage von Interessenprofilen anzuzeigen\ndie Effektivität von personalisierten Anzeigen und Inhalten zu messen, sowie\nunsere Produkte und Dienstleistungen zu entwickeln und zu verbessern\n\n    Klicken Sie auf „Alle ablehnen“, wenn Sie nicht möchten, dass wir und unsere Partner Cookies und personenbezogene Daten für diese zusätzlichen Zwecke verwenden.\n\n    Wenn Sie Ihre Auswahl anpassen möchten, klicken Sie auf „Datenschutzeinstellungen verwalten“.\n\n    Sie können Ihre Einstellungen jederzeit ändern, indem Sie auf unseren Websites und Apps auf den Link „Datenschutz- und Cookie-Einstellungen“ oder „Datenschutz-Dashboard“ klicken. Weitere Informationen darüber, wie wir Ihre personenbezogenen Daten nutzen, finden Sie in unserer Datenschutzerklärung und unserer Cookie-Richtlinie.\n\n\n\n\n\n\n\n\nAlle akzeptieren\nAlle ablehnen\nDatenschutzeinstellungen verwalten\n\n\n\n\n\nZum Ende\n           
         \n\n\n\n\n\n\n\n\n\n\n\n\n', metadata={'source': 'https://finance.yahoo.com/news/minister-khera-participates-unesco-global-215400355.html', 'title': 'Yahooist Teil der Yahoo Markenfamilie', 'language': 'No language found.'})]

....

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The example in the LangChain docs.

### Expected behavior

The example in the LangChain docs.

**Comment by maurochiong** [comment]
I tried tool as described here: https://python.langchain.com/docs/integrations/tools/yahoo_finance_news
Does not work.

**Comment by abdinal1** [comment]
Same problem with using GPT 4 as LLM, failed and throws this error!

**Comment by Pitch749** [comment]
Hello, I changed the _format_result as said to try and went a bit deeper, seems like the WebBaseLoader doesn't load the pages because of cookie popup

**Comment by astudzinski** [comment]
> Hello, I changed the _format_result as said to try and went a bit deeper, seems like the WebBaseLoader doesn't load the pages because of cookie popup Edit: I added cookies in the session header and worked so need to create a session in Yahoofinance to pass it to WebBaseLoader I guess but not an expert.

Can You explain how YOu added cookies in the new session header?

**Comment by Pitch749** [comment]
@astudzinski, sorry I was off, in case you didn't find out yet, I added manually in langchain_community.document_loaders.web_base in default_header_template. I copied it from my nav and added in the dict.

You could also pass the session with the right param to WebBaseLoader in class YahooFinanceNewsTool(BaseTool) but I don't care that much for now.
Hope this help.

**Comment by diviyank** [comment]
Hello,

A detailed implementation of the solution made by @Pitch749  (Thank you!):

```py
from typing import Iterable, Optional

from langchain_core.callbacks import CallbackManagerForToolRun
from langchain_core.documents import Document
from langchain_core.tools import BaseTool
from requests.exceptions import HTTPError, ReadTimeout
from urllib3.exceptions import ConnectionError

from langchain_community.document_loaders.web_base import WebBaseLoader


class YahooFinanceNewsTool(BaseTool):
    """Tool that searches financial news on Yahoo Finance."""

    name: str = "yahoo_finance_news"
    description: str = (
        "Useful for when you need to find financial news "
        "about a public company. "
        "Input should be a company ticker. "
        "For example, AAPL for Apple, MSFT for Microsoft."
    )
    top_k: int = 10
    """The number of results to return."""

    def _run(
        self,
        query: str,
        run_manager: Optional[CallbackManagerForToolRun] = None,
    ) -> str:
        """Use the Yahoo Finance News tool."""
        try:
            import yfinance
        except ImportError:
            raise ImportError(
                "Could not import yfinance python package. "
                "Please install it with `pip install yfinance`."
            )
        company = yfinance.Ticker(query)
        try:
            if company.isin is None:
                return f"Company ticker {query} not found."
        except (HTTPError, ReadTimeout, ConnectionError):
            return f"Company ticker {query} not found."

        links = []
        try:
            links = [n["link"] for n in company.news if n["type"] == "STORY"]
        except (HTTPError, ReadTimeout, ConnectionError):
            if not links:
                return f"No news found for company that searched with {query} ticker."
        if not links:
            return f"No news found for company that searched with {query} ticker."
        loader = WebBaseLoader(
            web_paths=links,
            header_template={
                "Cookie": "EuConsent:#AddYourNavigatorCookieHere"
            },
        )
        docs = loader.load()
        result = self._format_results(docs, query)
        if not result:
            return f"No news found for company that searched with {query} ticker."
        return result

    @staticmethod
    def _format_results(docs: Iterable[Document], query: str) -> str:
        doc_strings = [
            "\n".join([doc.metadata["title"], doc.metadata["description"]])
            for doc in docs
            if "description" in doc.metadata
            and (query in doc.metadata["description"] or query in doc.metadata["title"])
        ]
        return "\n\n".join(doc_strings)
```
