### ISSUE TITLE
Request: ability to set callbacks with LCEL at instantiation

### ISSUE THREAD

**Issue by jamesbraza** [langchain-ai/langchain#14241]
### Feature request

With `LLMChain`, it was possible to instantiate with `callbacks`, and just pass around the `LLMChain`.

With LCEL, the only way to handle `callbacks` is to pass them to every `invoke` call.  This requires one to pass around both the runnable LCEL object as well as the `callbacks`.

### Motivation

It's preferable to bake the `callbacks` into the LCEL object in advance at instantiation, then they get called each `invoke`.

### Your contribution

I can contribute something if I can get a confirm this is desirable.  The callbacks would be inserted at the base of the LCEL:

```python
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.schema.callbacks.stdout import StdOutCallbackHandler
from langchain.schema.runnable import RunnableConfig

config = RunnableConfig(callbacks=[StdOutCallbackHandler()])
prompt = PromptTemplate.from_template(
    "What is a good name for a company that makes {product}?"
)
runnable = config | prompt | ChatOpenAI()
runnable.invoke(input={"product": "colorful socks"})
```

**Comment by dumbPy** [comment]
Is this implemented or part of the roadmap somewhere so I can track it?
The example doesn't seem to run at least on v0.1.3

**Comment by jcmcclurg** [comment]
I'd also be interested in this feature.

**Comment by s-pike** [comment]
You can sort of do this already using `.with_config` (but it's not well documented, as you've mentioned in #14134) and doesn't give as full logging as you get from using `callbacks` in `LLMChain` (as mentioned in #14135):

```
config = RunnableConfig(callbacks=[StdOutCallbackHandler()])
prompt = PromptTemplate.from_template(
    "What is a good name for a company that makes {product}?"
)

# in two lines
runnable = prompt | ChatOpenAI()
runnable = runnable.with_config(config)

# OR in one line
runnable = (prompt | ChatOpenAI()).with_config(config)

runnable.invoke(input={"product": "colorful socks"})
```

The callbacks are then baked in to the object in advance, and get called on each `invoke`.

**Comment by austinmw** [comment]
@s-pike Hi,

If you get a moment, using your method, how could I print info from the following callback?

```python
from langchain_community.callbacks.bedrock_anthropic_callback import BedrockAnthropicTokenUsageCallbackHandler
```
