### ISSUE TITLE
DOC:  UnstructuredExcelLoader code comment‘s error

### ISSUE THREAD

**Issue by Mike575** [langchain-ai/langchain#14271]
### Issue with current documentation:

In  UnstructuredExcelLoader code comment,  introduce 'elements' mode for twice, but nothing about 'single' mode.
Original code comment are following:
  Unstructured loaders, UnstructuredExcelLoader can be used in both "single" and "elements" mode. **_If you use the loader in "elements" mode_**,  each sheet in the Excel file will be a an Unstructured Table element. **_If you use the loader in "elements" mode_**, an HTML representation of the table will be available in the "text_as_html" key in the document metadata.

**Comment by umair313** [comment]
@Mike575 are you talking about this code comment? in that there is mentioned about `single`, `element` mode.
