### ISSUE TITLE
DOC: Why use LCEL  ModuleNotFoundError: No module named 'langchain_core'

### ISSUE THREAD

**Issue by Nghiauet** [langchain-ai/langchain#14287]
### Issue with current documentation:
In this Announcements (https://github.com/langchain-ai/langchain/discussions/categories/announcements)  [LangChain Core #13823
](https://github.com/langchain-ai/langchain/discussions/13823) hwchase17 say he  

> TL;DR: we are splitting our core functionality to langchain-core to make LangChain more stable and reliable. This should be invisible to the eye and will happen in the background for the next two weeks, and we’d recommend not using langchain-core until then, but we’re flagging for transparency.

RunnablePassthrough moved from `langchain_core.runnables `  to from `langchain.schema.runnable`  
And the same 

langchain version : 0.0.336

### Idea or request for content:

**change** 
```
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.runnables import ConfigurableField
```

**To** 
```
from langchain.schema.runnable  import RunnablePassthrough
from langchain.schema  import StrOutputParser
from langchain.prompts import ChatPromptTemplate
from langchain.schema.runnable import RunnablePassthrough
from langchain.schema.runnable.utils import ConfigurableField
```

**Comment by AvijeetPrasad** [comment]
I found this useful, when working with the examples given in 

https://python.langchain.com/docs/expression_language/how_to/map

Following your advice, 

Changed

```python
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
```

To 

```python
from langchain.schema.runnable  import RunnablePassthrough
from langchain.schema  import StrOutputParser
```

and now the example for 'Manipulating inputs and outputs' works nicely :)

**Comment by hinthornw** [comment]
Update langchain and/or install langchain_core to get this to work.

**Comment by AvijeetPrasad** [comment]
I had the following (latest) packages installed, but still had the issue:

Name                    Version                   Build  Channel
langchain                 0.0.350                  pypi_0    pypi
langchain-community       0.0.3                    pypi_0    pypi
langchain-core            0.1.1                    pypi_0    pypi
langchain-experimental    0.0.47                   pypi_0    pypi

**Comment by Nghiauet** [comment]
> I had the following (latest) packages installed, but still had the issue:
> 
> Name	Version	Build	Channel
> langchain	0.0.350	pypi_0	pypi
> langchain-community	0.0.3	pypi_0	pypi
> langchain-core	0.1.1	pypi_0	pypi
> langchain-experimental	0.0.47	pypi_0	pypi

can you provide your code and your error message for more clarify.

**Comment by AvijeetPrasad** [comment]
@Nghiauet, I was just running the examples given in https://python.langchain.com/docs/expression_language/how_to/map

```python
from langchain.chat_models import ChatOpenAI
from langchain.embeddings import OpenAIEmbeddings
from langchain.prompts import ChatPromptTemplate
from langchain.vectorstores import FAISS
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough

vectorstore = FAISS.from_texts(
    ["harrison worked at kensho"], embedding=OpenAIEmbeddings()
)
retriever = vectorstore.as_retriever()
template = """Answer the question based only on the following context:
{context}

Question: {question}
"""
prompt = ChatPromptTemplate.from_template(template)
model = ChatOpenAI()

retrieval_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | model
    | StrOutputParser()
)

retrieval_chain.invoke("where did harrison work?")
```

**Comment by Nghiauet** [comment]
> ```python
> from langchain_core.output_parsers import StrOutputParser
> from langchain_core.runnables import RunnablePassthrough
> ```

Did you try change 
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough
to 
from langchain.schema.runnable import RunnablePassthrough
from langchain.schema  import StrOutputParser
like I mentions in the issue
