### ISSUE TITLE
Error catching in BedrockBase

### ISSUE THREAD

**Issue by JuR-0** [langchain-ai/langchain#14347]
### System Info

I want to use the `with_retry` from the Runnable class with Bedrock class to initiate a retry if Bedrock is raising a ThrottlingException (too many requests)  the problem is the error catching in `BedrockBase` class in the `_prepare_input_and_invoke` method is too broad. (line 269)
```
        except Exception as e:
            raise ValueError(f"Error raised by bedrock service: {e}")
```
Is it possible to use something like :
```
        except Exception as e:
            raise ValueError(f"Error raised by bedrock service: {e}") from e
```
Or:
```
        except Exception as e:
            raise ValueError(f"Error raised by bedrock service: {e}")with_traceback(e.__traceback__)
```
To keep the initial exception type.

Am I missing something that would explain this broad error catching?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

No reproduction needed

### Expected behavior

Expected behavior explained previously

**Comment by triyam** [comment]
@baskaryan, @eyurtsev, @hwchase17 Kindly review my PR

**Comment by JuR-0** [comment]
> @baskaryan, @eyurtsev, @hwchase17 Kindly review my PR: #14376

Your PR ain't solving the problem. It's still raises a ValueError anyway.
I made PR with what I had in mind: [#14398](https://github.com/langchain-ai/langchain/pull/14398)
