### ISSUE TITLE
Support SageMaker Inference Component of multi model endpoint

### ISSUE THREAD

**Issue by jc1518** [langchain-ai/langchain#14344]
### Feature request

I have created a multi model inference endpoint in the new version of SageMaker studio (the original one now is called studio classic). I don't see there is a place that I can set the `inference component` in the `SagemakerEndpoint` class. So I ended up get an expected error from SageMaker.

`An error occurred (ValidationError) when calling the InvokeEndpointWithResponseStream operation: Inference Component Name header is required for endpoints to which you plan to deploy inference components. Please include Inference Component Name header or consider using SageMaker models.`

### Motivation

To support multi model endpoint in SageMaker which is cost efficient way to run models.

### Your contribution

I can test and verify.

**Comment by jc1518** [comment]
All good now, it turns out that I need to upgrade my boto3 to the latest version to support InferenceComponentName.

**Comment by chandra447** [comment]
@jc1518 currently I am using the boto3==1.34.17 but still face the issue, can you drop down which version of boto has helped to solve this issue.

Thank you
