### ISSUE TITLE
OpenAIEmbeddings bug

### ISSUE THREAD

**Issue by youfak** [langchain-ai/langchain#14377]
### System Info

langchain==0.0.344
langchain-experimental>=0.0.42
python==3.10.12
 ```
embeddings = OpenAIEmbeddings(model_name=model,
                                                  openai_api_key=get_model_path(model),
                                                  chunk_size=CHUNK_SIZE)
```
error
```
WARNING! model_name is not default parameter.
                    model_name was transferred to model_kwargs.
                    Please confirm that model_name is what you intended.
  warnings.warn(
2023-12-07 12:36:12,645 - embeddings_api.py[line:39] - ERROR: Embeddings.create() got an unexpected keyword argument 'model_name'
AttributeError: 'NoneType' object has no attribute 'conjugate'
```

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
                    from langchain.embeddings.openai import OpenAIEmbeddings
                    embeddings = OpenAIEmbeddings(model_name="text-embedding-ada-002",
                                                  openai_api_key='xxxx',
                                                  chunk_size=512)
                    data = embeddings.embed_documents(texts)

```

### Expected behavior

Normal loading

**Comment by mspronesti** [comment]
It's not a bug. The parameter is called `model`, not `model_name`.

**Comment by youfak** [comment]
> OpenAIEmbeddings
Thank you very much. The problem seems to have been resolved
