### ISSUE TITLE
index with redis as vector store cannot delete documents

### ISSUE THREAD

**Issue by edwardzjl** [langchain-ai/langchain#14383]
### System Info

langchain==0.0.346
python==3.11.6

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Hi there!

I'm currently exploring the index feature in Langchain to load documents into the vector store upon my app startup.

However, I've encountered an issue where the index doesn't delete old documents when utilizing Redis as the vector store. After some investigation, I discovered that the `delete` function in `langchain.vectorstores.redis.base.Redis` is a static method, which poses a limitation—it cannot access instance variables, including the essential `key_prefix`. Without the `key_prefix`, Redis is unable to delete documents correctly.

This leads me to question why the `delete` method of the Redis vector store is static. I've noticed that other vector stores, such as Pinecone, do not have a static `delete` function and seem to handle this differently.

### Expected behavior

index with Redis as vector store should delete documents correctly.

**Comment by Reintjuu** [comment]
I haven't tested this myself, but was browsing through the source. There seem to be tests available that cover this:

https://github.com/langchain-ai/langchainjs/blob/79a04e05dda11298b9c1123d75b0387473690453/libs/langchain-redis/src/tests/vectorstores.test.ts#L169C1-L183C6
