### ISSUE TITLE
Is there any way we can have Elastic Search integrated with it.

### ISSUE THREAD

**Issue by Rishav-hub** [langchain-ai/langchain#1439]
I liked the SQLDatabase integration. If you can let me know what changes I need to do for the elastic search?

**Comment by AlpriElse** [comment]
There are docs on how to use Elasticsearch as your vector store here:
https://langchain.readthedocs.io/en/latest/modules/indexes/vectorstore_examples/elasticsearch.html

The source code for this is here:
https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/elastic_vector_search.py

Is this what you're looking for?

**Comment by Rishav-hub** [comment]
I am having all my data in my Elastic Search. When the user gives some text I need it to query from Elastic Search and return all the outputs. I don't need it to summarize the output.

**Comment by Chirag313** [comment]
@Rishav-hub did you find any answer?

**Comment by Rishav-hub** [comment]
> @Rishav-hub did you find any answer?

@Chirag313 No we have changed the approach, we are not using elastic anymore. Rather than using Weaviate Vector store our vector embeddings.

**Comment by Chirag313** [comment]
@Rishav-hub Can you tell me how did that approach pan out?

**Comment by llermaly** [comment]
@Chirag313 Something that would be cool is having a tool (or documentation about) how to handle the "text to elasticsearch DSL" flow.

So for example the input is : "how many apples are sold in average"

Step1: turn NLP into ES query aggregation
Step2: run the ES query and return the aggregations
Step3: Find the answer in the aggregations and return the answer in human language 

I wonder if this is possible using chains/tools and how.

Thanks!
