### ISSUE TITLE
value error when using huggingfacehub API

### ISSUE THREAD

**Issue by MegalaRamu** [langchain-ai/langchain#14400]
### System Info

Hi Team,

Am trying to connect to SQL/CSV using the HuggingFaceHUb and I get value error. This value error occurs even when I use the same example as given in https://python.langchain.com/docs/use_cases/qa_structured/sql except that instead of openAI am using huggingfaceHub

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

st.title("SQL DB with Langchain")

#entering input through streamlit into the app for querying
input_text = st.text_input("enter the text for search")
#input_period = st.text_input("enter the period for which you need summarization")

#connecting to hugging face API
os.environ["HUGGINGFACEHUB_API_TOKEN"] = huggingface_write_key

#SQL
db = SQLDatabase.from_uri("sqlite:///Chinook.db")
repo_id = "google/flan-t5-xxl"
llm = HuggingFaceHub(
    repo_id=repo_id, model_kwargs={"temperature": 0.2}
)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)

if input_text:
	st.write(db_chain.run(input_text))

### Expected behavior

Expected to give output for the query thats run

**Comment by MegalaRamu** [comment]
@dosu-bot Hi,

Am sure the hugging face API token is valid as I have used it to test other things.

Also I have installed huggingface_hub as am able to import it properly.

this is the error I receive:
ValueError: Error raised by inference API: Input validation error: inputs tokens + max_new_tokens must be <= 2048. Given: 2658 inputs tokens and 0 max_new_tokens

**Comment by MegalaRamu** [comment]
@dosu-bot 
Am getting error when i try this statement from libs.langchain.langchain.text_splitter import TextSplitter
No module named 'libs.langchain'
I tried installing libs also seperately?

Do you mean to use from langchain.text_splitter import RecursiveCharacterTextSplitter?

**Comment by MegalaRamu** [comment]
@dosu-bot

what i used is
from langchain.text_splitter import TextSplitter

the above works. Now I do have a DB for which I need to enter query and find the results. This text splitter should be used for the whole DB? or for the search text that I send?

**Comment by MegalaRamu** [comment]
@dosu-bot

As mentioned in the code example provided by you I have tried using the text splitter using the hugging face tokenizer itself for which am getting error.

code:
repo_id = "google/flan-t5-xxl"
tokenizer = AutoTokenizer.from_pretrained(repo_id)
text_splitter = TextSplitter.from_huggingface_tokenizer(tokenizer)

error:
TypeError: Can't instantiate abstract class TextSplitter with abstract method split_text

**Comment by shivajimanthri** [comment]
ValidationError: 1 validation error for HuggingFaceEndpoint __root__ Could not authenticate with huggingface_hub. Please check your API token. (type=value_error)
