### ISSUE TITLE
Issue: ElasticsearchStore with ssl_verify = {'verify_certs':False} does not work

### ISSUE THREAD

**Issue by Civel-1** [langchain-ai/langchain#14403]
### Issue you'd like to raise.

I am using langchain 0.0.316 an trying to create a ElasticsearchStore to do some similarity_search

However, whenever I try to create it (using from_documents or not) I get the following error : 

`raise ValueError("check_hostname requires server_hostname")`

This is a SSL error, and I suspect it to be the problem as I cannot use SSL. Somewhere else in the project, I cannot with Python to Elastic using verify_certs = False and everything works perfectly.

Thus I tried to create ElasticsearchStore with the following arguments :

```
db = ElasticsearchStore(texts,
                                      es_url='...',
                                      index_name = '...',
                                      embedding,
                                      ssl_verify = {'verify_certs'=False'})
```

But I still have the error and nothing has changed. 
How can I make langchain to initialize Elastic without checking for ssl certificates ?

**Comment by Civel-1** [comment]
Are you sure that SSL certificates to false are not supported yet ? 

Looking at this piece of code from the langchain tests files : 
```
    def test_similarity_search_with_ssl_verify(self, elasticsearch_url: str) -> None:
        """Test end to end construction and search with ssl verify."""
        ssl_verify = {
            "verify_certs": True,
            "basic_auth": ("ES_USER", "ES_PASSWORD"),
            "ca_certs": "ES_CA_CERTS_PATH",
        }
        texts = ["foo", "bar", "baz"]
        docsearch = ElasticVectorSearch.from_texts(
            texts,
            FakeEmbeddings(),
            elasticsearch_url=elasticsearch_url,
            ssl_verify=ssl_verify,
        )
        output = docsearch.similarity_search("foo", k=1)
        assert output == [Document(page_content="foo")]
```
If looks like verify_certs is a supported parameter ? Or is it just supported when True and not False ?

**Comment by manel00** [comment]
Hello, is there a way to verify the certs with the param already? for me it is not working with it still

**Comment by Civel-1** [comment]
I don't think so,.
For me, creating a elastic connection first initialized with verify_certs to false then use it as a es_connection param when creating the ElasticsearchStore did the trick.

**Comment by RyanAlexton** [comment]
> I found a way to work around this. You can instantiate a ElasticsearchStore by using an existing elastic connection.
> 
> ```
> elastic_client = Elasticsearch(..., verify_certs=False)
> db = ElasticsearchStore(texts,
>                                       index_name = '...',
>                                       embedding,
>                                       es_connection = elastic_client)
> ```

@Civel-1 hello, i used the code you provide, but meet the wrong:AttributeError: 'Elasticsearch' object has no attribute 'options', is the wrong version of Elasticsearch or any other problems?
