### ISSUE TITLE
db_chain_sql_out.return_sql

### ISSUE THREAD

**Issue by Nageshyr** [langchain-ai/langchain#14404]
### System Info

from langchain.llms import GooglePalm
from sqlalchemy import create_engine
from langchain.utilities import SQLDatabase
from langchain.llms import GooglePalm
from langchain_experimental.sql import SQLDatabaseChain

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

st.write(db_chain_sql_out.return_sql) is returning bool value "True" Instead of the model generated actual SQL Statement - 
I am using Google Palm - is this the normal output?

### Expected behavior

Expecting model generated SQL

**Comment by Nageshyr** [comment]
======================================= version ===========================

Name: langchain
Version: 0.0.284
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT


=================== code  =========================================
question = st.text_input("Enter your question:")
tab_titles = ["Results","Sql Text"]
tabs = st.tabs(tab_titles)
db_chain_sql_out = SQLDatabaseChain.from_llm(llm, db, return_sql=True, verbose = True)
db_chain_results = SQLDatabaseChain.from_llm(llm, db, verbose = True)


#Pass the Query[question]
if question:
    with tabs[0]:
        st.write("")
        st.header(":blue[Response]")
        st.write(db_chain_results.run(f"{question}"))

    with tabs[1]:
        st.write(db_chain_sql_out.return_sql)

==================================== Error ===================================

None, just returns the Boolean value "True"

**Comment by triyam** [comment]
Try to print

```diff

tabs = st.tabs(tab_titles)
+ print(db)
db_chain_sql_out = SQLDatabaseChain.from_llm(llm, db, return_sql=True, verbose = True)

```

What does it says?

**Comment by Nageshyr** [comment]
Hey Mishra,

TY for reaching out...I got an error trying the suggested code...

Error...

TypeError: can only concatenate tuple (not "NoneType") to tuple

File
"C:\Users\ny250012\AppData\Roaming\Python\Python310\site-packages\streamlit\runtime\scriptrunner\script_runner.py",
line 534, in _run_script
    exec(code, module.__dict__)
File "D:\Python-Code\langchain\MyLangChain\lc_td_test.py", line 36, in
<module>
    tabs = st.tabs(tab_titles) + print(db)

Pl. let me know - Thx
