### ISSUE TITLE
Web Scraping with ChatOllama gives SSL: WRONG_VERSION_NUMBER 

### ISSUE THREAD

**Issue by AndreaBrg** [langchain-ai/langchain#14450]
### Issue you'd like to raise.

Hi, I'm trying to implement the [web scraping tutorial ](https://python.langchain.com/docs/use_cases/web_scraping#llm-with-function-calling) using ChatOllama instead of ChatOpenAI.

This is what I'm trying to do:

```
import pprint

from langchain.chains import create_extraction_chain
from langchain.document_loaders import AsyncChromiumLoader
from langchain.document_transformers import BeautifulSoupTransformer
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chat_models import ChatOllama


def extract(content: str, schema: dict, llm):
    return create_extraction_chain(schema=schema, llm=llm).run(content)


def scrape_with_playwright(urls, schema, llm):
    loader = AsyncChromiumLoader(urls)
    docs = loader.load()
    bs_transformer = BeautifulSoupTransformer()
    docs_transformed = bs_transformer.transform_documents(
        docs, tags_to_extract=["span"]
    )
    print("Extracting content with LLM")

    # Grab the first 1000 tokens of the site
    splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
        chunk_size=1000, chunk_overlap=0
    )
    splits = splitter.split_documents(docs_transformed)

    # Process the first split
    extracted_content = extract(schema=schema, content=splits[0].page_content, llm=llm)

    return extracted_content


if __name__ == '__main__':
    llm = ChatOllama(base_url="https://localhost:11434", model="llama2")

    schema = {
        "properties": {
            "news_article_title": {"type": "string"},
            "news_article_summary": {"type": "string"},
        },
        "required": ["news_article_title", "news_article_summary"],
    }

    urls = ["https://www.wsj.com"]
    extracted_content = scrape_with_playwright(urls, schema=schema, llm=llm)

    pprint.pprint(extracted_content)

```
Instead of the results shown I get this error: `requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))` when the `extract` function is called.

Could anyone please help me understand what I'm doing wrong? Thanks!

**Comment by AndreaBrg** [comment]
@dosu-bot thanks, changing  the `base_url` from `https://localhost:11434` to `http://localhost:11434` worked.

However, it returns another error: `ValueError: Ollama call failed with status code 400. Details: invalid options: function_call, functions`. I noticed that `function_call` and `functions` are created by `get_llm_kwargs` found in [openai_functions](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_functions/utils.py#L31). Does this mean that web scraping can only be done using `ChatOpenAI`?

**Comment by navicstein** [comment]
@AndreaBrg just use `OllamFunctions` ???


doc: https://python.langchain.com/docs/integrations/chat/ollama_functions

```sh
$ poetry add langchain_experimental
```

```python
from langchain_experimental.llms.ollama_functions import OllamaFunctions

llm = OllamaFunctions(
    model="llama2",
)
schema = {
        "properties": {
            "news_article_title": {"type": "string"},
            "news_article_summary": {"type": "string"},
        },
        "required": ["news_article_title", "news_article_summary"],
    }

urls = ["https://www.wsj.com"]
extracted_content = scrape_with_playwright(urls, schema=schema, llm=llm)
pprint.pprint(extracted_content)

```

**Comment by 812781385** [comment]
OllamaFunctions using bind_tools and enabling streams throws an error:
ValueError: Ollama call failed with status code 400. Details: {"error":"invalid options: functions"}

llmmodel = OllamaFunctions(model=model, base_url='http://localhost:11434', format="json")
llmmodel = llmmodel.bind_tools(
    tools=[
      {
        "name": "get_ship",
        "description": "get ship info",
        "parameters": {
          "type": "object",
          "properties": {
            "mmsi": {
              "type": "string",
              "description": "mmsi, " "ps： 13324313",
            }
          },
          "required": ["mmsi"],
        },
      },
    ],
    function_call={"name": "get_ship"},
  )
response = llmmodel.stream(prompt)
