### ISSUE TITLE
merge two FAISS indexes 

### ISSUE THREAD

**Issue by SiddiqueFarhan** [langchain-ai/langchain#1447]
I am generating index using the below mentioned code:

index = FAISS.from_documents(docs, embeddings)

Since the indexes are from large books, and in future, I aim to convert more books to embeddings too.

Since there is cost associated with the conversion of docs to embedding, I want to be able to add the knowledge of new index to the the already existing index so that I can have a consolidated DB.

Is there any sophisticated way to do this?

**Comment by sanasz91mdev** [comment]
@SiddiqueFarhan  are you able to do this?
https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/faiss.html?highlight=FAISS#merging

Its giving error

**Comment by wangxiaoci27** [comment]
I have the same problem.

**Comment by jgroehm** [comment]
Same problem as well.

**Comment by jgroehm** [comment]
Made a local hacky modification to langchain>vectorstores>faiss.py which seems to be working for me so far. New to this library so not sure what the downstream effect might be for others, or if there's a better way to handle this. 
     
     class FAISS(VectorStore):
     ...
        # Merge two IndexFlatL2
        try:
            self.index.merge_from(target.index)  # AttributeError: 'IndexFlat' object has no attribute 'merge_from'

        except Exception as e:
            # print(f"Built-in merging failed {e}. FlatIndex Manual Override Starting")
            vectors1 = np.array(self.index.reconstruct_n(0, self.index.ntotal))
            vectors2 = np.array(target.index.reconstruct_n(0, target.index.ntotal))

            # Concatenate the vectors.
            merged_vectors = np.vstack((vectors1, vectors2))

            # Create a new index.
            faiss = dependable_faiss_import()
            new_index = faiss.IndexFlatL2(merged_vectors.shape[1])

            # Add the merged vectors to the new index.
            new_index.add(merged_vectors)

            # Replace the old index with the new one.
            self.index = new_index


#------
""" Example Use Case
def load_faiss_db(db_path):
    """
    load faiss db
    """
    db = FAISS.load_local(db_path, embeddings=embeddings)
    return db

db0 = load_faiss_db(db_paths[0])
# db0.docstore.__dict__

[db0.merge_from(load_faiss_db(i)) for i in db_paths[1:]]


save_path = os.path.join(faiss_output_path, "merged")
Path(save_path).mkdir(parents=True, exist_ok=True)
db0.save_local(save_path)
"""

**Comment by Wesleytys0130** [comment]
I have the same problem. :((

**Comment by lingji-yidong** [comment]
AttributeError: 'IndexFlat' object has no attribute 'merge_from'

Solution:

```
pip uninstall faiss-gpu
pip install faiss-cpu
```

It works for me.

**Comment by jgroehm** [comment]
Thanks @lingji-yidong, you're right that works. 

Probably not an optimal long-term solution though since some of the most useful indexes are implemented on GPU. 

Ref: [Faiss on the GPU](https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU)

**Comment by goheesheng** [comment]
This needs to be merged asap, it's a great concept

>

**Comment by goheesheng** [comment]
> 

Why though?

**Comment by goheesheng** [comment]
> Thanks @lingji-yidong, you're right that works.
> 
> Probably not an optimal long-term solution though since some of the most useful indexes are implemented on GPU.
> 
> Ref: [Faiss on the GPU](https://github.com/facebookresearch/faiss/wiki/Faiss-on-the-GPU)

Why isn't it optimal? It's just merging

**Comment by Damian89** [comment]
I can confirm on current langchain 0.0.304 the same problem still happens when using merge_from:

![image](https://github.com/langchain-ai/langchain/assets/11396147/e9bfca13-3f32-41cd-bf5c-5e910b719a33)

**Comment by lsperanca-imperial** [comment]
@Damian89, I have got `AttributeError: 'IndexFlat' object has no attribute 'merge_from'` as well. However, a quick search led me to [this answer](https://github.com/facebookresearch/faiss/issues/577#issuecomment-418283242) and [this workaround](https://gist.github.com/mdouze/586746666ef493dbc363aef9266bb990).

The answer states that the `IndexFlat` has no merging method. The workaround is a manual implementation of the merge for such an index by a `faiss` developer. Maybe that could be implemented? I am sorry I am too busy for offering a PR, but maybe someone else? (Please test the gist before implementing. I did not.)

For completion: I am in `faiss-gpu` for the first time. I have never get such an error while I was using `faiss-cpu` a few months ago.

**Comment by pankaj90** [comment]
I am receiving similar error as mentioned by @Damian89. Can someone from team confirm when this issue will be fixed? Thanks in advance.

**Comment by Damian89** [comment]
@pankaj90 actually this happens to me only on faiss-gpu, not faiss-cpu.

@lsperanca-imperial I actually used the quickfix made by @jgroehm in this thread. Works.

**Comment by Damian89** [comment]
I think this AI bot is not smart... I would not close this issue just based on my comment -.-

**Comment by Damian89** [comment]
qed

**Comment by devstein** [comment]
@Damian89 Thanks for flagging this bug with Dosu! Dosu should be smarter than that 😄

**Comment by calebebrim** [comment]
Mee too... same issue with GPU version.

**Comment by ramamimu** [comment]
please help, why 'merge_from' only compatible on CPU. this library is very useful

**Comment by lsperanca-imperial** [comment]
Hi Ahmad. The FAISS itself did not implemented this method for GPU. It has nothing to do with langchain.

Though, you can find a workaround in the chain of answers here.

________________________________
