### ISSUE TITLE
generic codebase?

### ISSUE THREAD

**Issue by DiTo97** [langchain-ai/langchain#14483]
### Feature request

It would be nice to write code for any generic LLM to use in a given chain, being able to specify its provider and parameters in a config file outside the source code.

Is there a built-in way to do so? What major roadblocks would you see in doing that?

### Motivation

Most examples that I see in the docs or over the Internet tend to specify from code whether the LLM to be used in a given chain has to be from openAI, anthropic, LLaMA, etc., resulting in different codebases, while it would be great to write one single unified codebase and compare the performance of different open-source or API LLMs by simply changing one line of config.

This would be especially relevant when the specific LLM provider is not set or known from the get-go and multiple ones should be compared to find the most suitable one in terms of perfomance, efficiency and cost for any given LLM-driven application.

### Your contribution

I don't have time for a PR now, but since I have been doing a similar thing for our private codebase at the laboratory, combining openAI, anthropic and LLaMA under a single unified spell without using the langchain framework, I may be interested in supporting that in the future as the framework already has lots of interesting features in terms of tooling, memory and storage.

**Comment by DiTo97** [comment]
@dosu-bot

Thanks for the clarification. The module you shared is a great starting point for unifying the way LLM libraries are imported.

The autoLLM discussion that you mentioned (#9869) pointed in the same direction with a minimal, yet interesting, implementation, but it has been closed without further notice. Any reason why it was not supported?

Now that I look at more examples, e.g., [conversation summary buffer](https://python.langchain.com/docs/modules/memory/types/summary_buffer), I see that the same idea would translate to memory, extending further than LLM only, making it far easier to experiment with different LLM (and memory, if needed) settings.

**Comment by DiTo97** [comment]
Anyone from the contrib team (not you, Dosu bot) that can share insights on what's the direction for this?

I will just try to name a few from commits history: @mgoin, @efriis, @nfcampos.

After the 0.1.x release and the structuring in langchain, langchain-core and -community, many common abstract classes for model, memory, embedding and vectorstore seem to be present, according to the [API docs](https://api.python.langchain.com/en/stable/langchain_api_reference.html). Therefore, the ability to configure a chain with one or more agents, each with a model and optional memory and toolkits, interacting with one or more embeddings or vectorstores, fully from a config file where pieces can be swapped in and out does not seem to be a long shot away.

**Comment by mgoin** [comment]
Hey @DiTo97 I'm just a contributor for the DeepSparse LLM backend and haven't worked on anything else/large-scale on LangChain - try contacting @baskaryan since he is a maintainer

**Comment by DiTo97** [comment]
Hi @baskaryan. Any ups on this?
