### ISSUE TITLE
why the sql langchain's custom prompt is not working?

### ISSUE THREAD

**Issue by SonamJain1** [langchain-ai/langchain#14487]
### Issue you'd like to raise.

I tried to work on SQL cutsom prompt, but it didn't work and is still giving the wrong sql queries . Here is the code : def process_user_input(user_input):
    create_db()
    input_db = SQLDatabase.from_uri('sqlite:///sample_db_2.sqlite')
    llm_1 = OpenAI(temperature=0)
    db_agent = SQLDatabaseChain.from_llm(llm = llm_1,
                            db = input_db,
                            verbose=True,)
    chain = create_sql_query_chain(ChatOpenAI(temperature=0), input_db)
    response = chain.invoke({"question": user_input})

**Comment by Kashi-2002** [comment]
You can find related solutions on #12006. You can check how to pass the custom prompt in the agent.
