### ISSUE TITLE
Is 'collection_name' required when initializing 'PGVector'?

### ISSUE THREAD

**Issue by sjinwoo** [langchain-ai/langchain#14518]
### System Info
```langchain = "^0.0.345"```
I want to embed and store multiple documents in PGVector and RAG query the DB.
When saving documents, I am specifying a collection_name for each document.
(For example, if I have 3 documents, I have 3 collection_names)
Is it possible to separate collections like this?
Also, is the collection_name required when connecting to PGVector?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

db1 = PGVector.from_documents(
    embedding=embed,
    documents=documents,
    collection_name="my doc 1",
    connection_string=CONNECTION_STRING
)

db2 = PGVector.from_documents(
    embedding=embed,
    documents=documents,
    collection_name="my doc 2",
    connection_string=CONNECTION_STRING
)

# after, To query the DB where the document is stored.

db_connection = PGVector(
    embedding=embed,
    documents=documents,
    collection_name="my doc 2",         # I don't want to specify a collection_name.
    connection_string=CONNECTION_STRING
)

### Expected behavior

I want to connect to the PGVector only the first time, and then use that session to query the collection_name (1 document in my case).

**Comment by perezpefaur** [comment]
Same here, doesn´t make sense
