### ISSUE TITLE
  Qdrant retriever with existing data leads to pydantic.error_wrappers.ValidationError: 1 validation error for Document page_content   none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by Thiru-GVT** [langchain-ai/langchain#14515]
### System Info

Python 3.10.2
langchain version 0.0.339
WSL 

### Who can help?

@hwchase17 
@agola11 

### Information

- [x ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
I am using Qdrant on docker with information preloaded. However im unable to get it to search

```
MODEL_TO_USE = 'all-mpnet-base-v2'
client = QdrantClient(QDRANT_ENDPOINT, port=6333, timeout=120)
embeddings = HuggingFaceEmbeddings(model_name=MODEL_TO_USE)
qdrant = Qdrant(client, collection_name, embeddings)
conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=qdrant.as_retriever(search_kwargs={'k': 5}),
        get_chat_history=lambda h : h,
        memory=memory
    )

# im using a streamlit frontend
import streamlit as st
st.session_state.conversation = conversation_chain 

# during chat
result = st.session_state.conversation({
                "question": user_query, 
                "chat_history": st.session_state['chat_history']})
```

Result would then lead to the error. 

### Expected behavior

Chat is supposed to work instead of getting

```
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document
page_content
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by Thiru-GVT** [comment]
Hmm I dont think thats it. The full error is below:

```
2023-12-11 10:24:32.027 Uncaught app exception
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/user/git/rag_service/main.py", line 126, in <module>
    result = st.session_state.conversation({
  File "/home/user/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/home/user/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/user/.local/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 148, in _call
    docs = self._get_docs(new_question, inputs, run_manager=_run_manager)
  File "/home/user/.local/lib/python3.10/site-packages/langchain/chains/conversational_retrieval/base.py", line 305, in _get_docs
    docs = self.retriever.get_relevant_documents(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/schema/retriever.py", line 211, in get_relevant_documents
    raise e
  File "/home/user/.local/lib/python3.10/site-packages/langchain/schema/retriever.py", line 204, in get_relevant_documents
    result = self._get_relevant_documents(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/schema/vectorstore.py", line 656, in _get_relevant_documents
    docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/langchain/vectorstores/qdrant.py", line 274, in similarity_search
    results = self.similarity_search_with_score(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/vectorstores/qdrant.py", line 350, in similarity_search_with_score
    return self.similarity_search_with_score_by_vector(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/vectorstores/qdrant.py", line 608, in similarity_search_with_score_by_vector
    return [
  File "/home/user/.local/lib/python3.10/site-packages/langchain/vectorstores/qdrant.py", line 610, in <listcomp>
    self._document_from_scored_point(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/vectorstores/qdrant.py", line 1921, in _document_from_scored_point
    return Document(
  File "/home/user/.local/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document
page_content
  none is not an allowed value (type=type_error.none.not_allowed)
```

It seems the error is coming from `self.similarity_search_with_score_by_vector` which then uses ` self._document_from_scored_point` which likely returns nothing?

**Comment by erik09876** [comment]
I have the same problem with the Neo4jVector as retriever.

**Comment by HeAndres** [comment]
same problem here :)

**Comment by mac-chaffee** [comment]
One possible cause for this issue is that if you are upserting data points manually (without using langchain), you have to make sure your payload is still using the langchain format, which has two required fields: `metadata` and `page_content`.

If you perform a search and Qdrant returns a point that doesn't include the `page_content` field, you'll see that `ValidationError`.

These key names are configurable too: https://github.com/langchain-ai/langchain/blob/148347e858fa548f849fbe36f19fc041a34d6ebf/libs%2Fcommunity%2Flangchain_community%2Fvectorstores%2Fqdrant.py#L1202-L1203

**Comment by mars203030** [comment]
have you found solution?

**Comment by urbanscribe** [comment]
anything new on this?

**Comment by ErikValle2** [comment]
> I have the same problem with the Neo4jVector as retriever.

Same here

**Comment by ottusp** [comment]
@mac-chaffee This is the key! When we delegate the creation of points to `langchain_community.qdrant`, either through `add_texts` or `from_texts` (or any other method that creates points really), Qdrant automatically adds two fields to the payload, and they're meant to store the text value of that vector and the metadata you're using. By default, they are `page_content` and `metadata`.

The key thing here is that when you use `langchain_community.qdrant` to search over the database, the lib expects all the points to have the `page_content` field on the payload (which is not true if you haven't added that when you created your points). So it raises an error.

To fix this, you have a few options:
- Remove all your points, and add them again using `add_texts` or `add_documents`;
- Update your points, adding `page_content` and `metadata` keys to the payload of each point;
- Stop using `langchain_community.qdrant`. Instead, use only Qdrant from `qdrant_client` package.

To have a more concrete view of what I'm talking about, please take a look at [this method](https://github.com/langchain-ai/langchain/blob/148347e858fa548f849fbe36f19fc041a34d6ebf/libs/community/langchain_community/vectorstores/qdrant.py#L1913) from the source library. `_build_payloads` is called when creating the points that are being added to the database.

IMO, this takes away the flexibility of the payload from qdrant, but I haven't searched much on how flexible indexing is in this database. Anyway, hope my solution helps

**Comment by fikrisandi** [comment]
Hi guys, I have similar problem, but i am using chroma, instead of Qdrant. Anyone can help me?

Thank you

**Comment by uzumakinaruto19** [comment]
> page_content

same here, u solved it any how?

**Comment by Anush008** [comment]
@uzumakinaruto19, use the new `langchain-qdrant` package.

```
pip install --upgrade --quiet  langchain-qdrant
```

```
from langchain_qdrant import Qdrant
```

https://python.langchain.com/v0.2/docs/integrations/vectorstores/qdrant/

**Comment by uzumakinaruto19** [comment]
> @uzumakinaruto19, use the new `langchain-qdrant` package.
> 
> ```
> pip install --upgrade --quiet  langchain-qdrant
> ```
> 
> ```
> from langchain_qdrant import Qdrant
> ```
> 
> https://python.langchain.com/v0.2/docs/integrations/vectorstores/qdrant/

That is for qdrant right?
i have issues with Neo4j vectorstore
