### ISSUE TITLE
DOC: Please add stronger contrast or labeling between notebook input and output blocks

### ISSUE THREAD

**Issue by kaesluder** [langchain-ai/langchain#14532]
### Issue with current documentation:

Page: https://python.langchain.com/docs/modules/memory/

In dark mode, there is very little contrast between inputs and outputs. Especially for pages imported from Jupyter notebooks, it can be really confusing figuring out which code blocks are safe to test in a `.py` function and which code blocks are intended for use in Jupyter. 

Adding in explicit contrast or labeling between input and output blocks would be helpful.

![image](https://github.com/langchain-ai/langchain/assets/113563866/ba628424-fcc5-4496-8053-128254e068a7)

**Comment by cyai** [comment]
Here, #15137 this might help
