### ISSUE TITLE
Does HTML Doc Loader accept .htm sites?

### ISSUE THREAD

**Issue by jimmy2933** [langchain-ai/langchain#14545]
### System Info

Langchain 0.0.331, macOS Monterey, Python 3.10.9

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import UnstructuredHTMLLoader
 
loader = UnstructuredHTMLLoader("https://www.sec.gov/ix?doc=/Archives/edgar/data/40987/000004098720000010/gpc-12312019x10k.htm")
documents = loader.load()
 
FileNotFoundError: [Errno 2] No such file or directory: 'https://www.sec.gov/ix?doc=/Archives/edgar/data/40987/000004098720000010/gpc-12312019x10k.htm

### Expected behavior

Success loading .htm file

**Comment by chyroc** [comment]
try:

```
import requests
from langchain.document_loaders import UnstructuredHTMLLoader

source_url = "https://www.sec.gov/ix?doc=/Archives/edgar/data/40987/000004098720000010/gpc-12312019x10k.htm"
r = requests.get(source_url)
with open("12312019x10k.htm", "w") as f:
    f.write(r.text)
loader = UnstructuredHTMLLoader("12312019x10k.htm")
documents = loader.load()
print(documents)

```
