### ISSUE TITLE
An output parsing error occurred. Could not parse LLM output create_csv_agent

### ISSUE THREAD

**Issue by mpiricsoftware** [langchain-ai/langchain#14580]
### System Info

Ubuntu 20.04
CUDA 12.1
NVIDIA RTX 4070 

### Who can help?

@hwchase17 
@eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chains import LLMChain
from langchain.llms import LlamaCpp
from langchain.prompts import PromptTemplate

template = """Question: {question} Answer: Your Answer"""
prompt = PromptTemplate(template=template, input_variables=["question"])
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
n_gpu_layers = 80  # Change this value based on your model and your GPU VRAM pool.
n_batch = 512  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.llm = LlamaCpp(model_path="/home/rtx-4070/Downloads/openorca-platypus2-13b.Q4_K_M.gguf",
                n_gpu_layers=n_gpu_layers,
                n_batch=n_batch,
                callback_manager=callback_manager,
                verbose=True,
               n_ctx=2048
                )
from langchain_experimental.agents.agent_toolkits import create_csv_agent
from langchain.agents.agent_types import AgentType
agent = create_csv_agent(
    llm,
    "/home/rtx-4070/git_brainyneurals/langchain_local/docs/SPY.csv",
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    handle_parsing_errors=True
)
agent.run("How many rows are there?")
```
I am running opeorca model which I have downloaded from HuggingFace. But I am facing this erros. Could you please help me with related solutions? Or Suggest any other ways or models. Would be grateful.

Thanks in advance. 

### Expected behavior

I want to make work simple csv agent that runs on my RTX 4070 Desktop GPU with any open source models.

**Comment by mitesh741** [comment]
Are there any open source model that works well with LangChain for CSV agent?
