### ISSUE TITLE
Issue: Getting error while integrating Confluence Spaces including attachments

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#14586]
### Issue you'd like to raise.

below is my code 
`        confluence_url = config.get("confluence_url", None)
        username = config.get("username", None)
        api_key = config.get("api_key", None)
        space_key = config.get("space_key", None)
        documents = []

        embedding = OpenAIEmbeddings()
        loader = ConfluenceLoader(
            url=confluence_url,
            username=username,
            api_key=api_key
        )
        for space_key in space_key:
            documents.extend(loader.load(space_key=space_key,include_attachments=True,limit=100))`
The error I am getting:
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.media.atlassian.com/file/UNKNOWN_MEDIA_ID/binary?token=sometoken&name=Invalid%20file%20id%20-%20UNKNOWN_MEDIA_ID&max-age=2940

**Comment by deepak-habilelabs** [comment]
by installing latest version of langchain, the problem resolved

**Comment by deepak-hl** [comment]
400 Client Error: Bad Request for url: https://api.media.atlassian.com/file/UNKNOWN_MEDIA_ID/binary?
