### ISSUE TITLE
QaWithSources default prompt is massive

### ISSUE THREAD

**Issue by joshy-deshaw** [langchain-ai/langchain#14596]
### System Info

Not relevant

### Who can help?

@hwchase17
@agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use the QA With Sources chain with the default prompt. If the chain type is `stuff` or `map_reduce` the default prompts used are [this](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/qa_with_sources/stuff_prompt.py) and [this](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/qa_with_sources/map_reduce_prompt.py) respectively. These files are massive, and easily adds a 1000+ tokens to every request. In models like PALM2, there's barely any tokens left for other questions.

### Expected behavior

These prompts should be much more short, even if as a sample input.

**Comment by PilotGFX** [comment]
I agree.  I suggest always constructing your own prompt, and use the templates for inspiration/guide. I appreciate the efforts done by the creators of this massive library, and will refrain from concluding anything on why the prompts are not of better quality. There isn't a one size fit all here, which is why i suggest making your own prompt

**Comment by sandee9** [comment]
You can overwrite the predefined prompts with your own custom prompts.
