### ISSUE TITLE
'Refine' issue with OpenAIChat  

### ISSUE THREAD

**Issue by sbc-max** [langchain-ai/langchain#1460]
When trying to use the refine chain with the ChatGPT API the result often comes back with "The original answer remains relevant and accurate...". Sometime the subsequent text will include components of the original answer but often it will just end there. 

```
    llm = OpenAIChat(temperature=0)
    qa_chain = load_qa_chain(llm, chain_type="refine")
    qa_document_chain = AnalyzeDocumentChain(combine_docs_chain=qa_chain)
    qa_document_chain.run(input_document=doc, question=prompt)
```

**Comment by fuushyn** [comment]
Facing the same issue. I believe it's something to do with the default prompt for refine. Trying to tweak the the prompt for chat rn.

**Comment by fuushyn** [comment]
Changed the refine template (refine_template) to this - 

`
    "The original question is as follows: {question}\n"
    "We have provided an existing answer, including sources (just the ones given in the metadata of the documents, don't make up your own sources): {existing_answer}\n"
    "We have the opportunity to refine the existing answer"
    "(only if needed) with some more context below.\n"
    "------------\n"
    "{context_str}\n"
    "------------\n"
    "Given the new context, add to the original answer to better "
    "answer the question"
    "If you do update it, please update the sources as well. "
    "If the context isn't useful, print the original answer."
    "The final answer should incorporate information from the original answer and the new context, but "
    "don't make use of phrases like 'additional context', 'original answer', 'new context', 'old answer' because "
    "we must hide this answer updation process from end users."

`

from
(default refine_template)
`    "The original question is as follows: {question}\n"
    "We have provided an existing answer, including sources: {existing_answer}\n"
    "We have the opportunity to refine the existing answer"
    "(only if needed) with some more context below.\n"
    "------------\n"
    "{context_str}\n"
    "------------\n"
    "Given the new context, refine the original answer to better "
    "answer the question"
    "If you do update it, please update the sources as well. "
    "If the context isn't useful, return the original answer."
`

**Comment by LukasMosser** [comment]
How do you get around this error?
`pydantic.error_wrappers.ValidationError: 1 validation error for StuffDocumentsChain
refine_prompt
  extra fields not permitted (type=value_error.extra)`
  
  Just changing the template doesn't fix the issue.

**Comment by fuushyn** [comment]
@LukasMosser I believe you are using the "stuff" chain. Try chain_type="refine" in the chain function call.

**Comment by sbc-max** [comment]
@fuushyn I see the error @LukasMosser is getting as well, the issue comes up when you try to pass-in a custom prompt using the chain_type_kwargs - which isn't supported by the 'refine' chain_type.

For example the below will cause the error:
`system_template="""Use the following pieces of context to answer the user's question. 
If you don't know the answer, just say that you don't know, don't try to make up an answer. 
----------------
{context}"""

messages = [
    SystemMessagePromptTemplate.from_template(system_template),
    HumanMessagePromptTemplate.from_template("{question}")
]

chat_prompt = ChatPromptTemplate.from_messages(messages)

chain_type_kwargs = {"prompt": chat_prompt}
qa = VectorDBQA.from_chain_type(llm=llm, chain_type="refine", vectorstore=vectorstore, **chain_type_kwargs=chain_type_kwargs**, return_source_documents=True)
`

Removing chain_type_kwargs fixes the error but than doesn't allow for custom prompts (and passing in a chat history?).

**Comment by fuushyn** [comment]
@sbc-max I see. I'm using the `load_qa_chain` function instead of `VectorDBQA.from_chain_type`. You can find some examples here - [Question Answering](https://langchain.readthedocs.io/en/latest/modules/indexes/chain_examples/question_answering.html?highlight=refine#the-refine-chain)
For Chat, I passed the chain to `ChatVectorDBChain` , here's an example - [Chat Vector DB](https://langchain.readthedocs.io/en/latest/modules/chat/examples/chat_vector_db.html?highlight=ChatVectorDBChain#chat-vector-db-with-streaming-to-stdout)
cc- @LukasMosser

**Comment by Arttii** [comment]
Hey @fuushyn do you maybe have a more complete example of how you are doing it? It is a bit tricky to figure what to pass where. Thanks!

**Comment by LukasMosser** [comment]
I agree with @Arttii, a more complete example could be useful, thanks!

**Comment by fuushyn** [comment]
Sure @Arttii @LukasMosser here's a quick example (will share an entire project soon)

```
base_embeddings = OpenAIEmbeddings()
basic_llm = OpenAI(temperature=0)
chat_llm = OpenAIChat(model_name="gpt-3.5-turbo")
docsearch= Pinecone(index, base_embeddings.embed_query, 'text')


question_generator = LLMChain(llm=basic_llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain_refine = load_qa_with_sources_chain(chat_llm, chain_type="refine",question_prompt=question_prompt, refine_prompt=refine_prompt)

qa_chain = ChatVectorDBChain(vectorstore=docsearch, combine_docs_chain=doc_chain_refine, question_generator=question_generator, return_source_documents=True, top_k_docs_for_context=10)

query= "What is the the composition of dopamine molecule?"
result = qa_chain({"question": query, "chat_history": []})


```

**Comment by Arttii** [comment]
@fuushyn thanks! @LukasMosser was related.
