### ISSUE TITLE
Dockerfile issues when trying to build the repo using .devcontainer

### ISSUE THREAD

**Issue by SavvasMohito** [langchain-ai/langchain#14631]
### System Info

Hello, after forking and cloning the repo on my machine, I tried to open it using docker and specifically in VS Code with the option to "Reopen in Container". While building, the final command of [dev.Dockerfile](https://github.com/langchain-ai/langchain/blob/ca7da8f7ef9bc7a613ff07279c4603cad5fd175a/libs/langchain/dev.Dockerfile#L44) resulted in the following error:

```logs
#0 1.241 Directory ../core does not exist
```

After investigating, I found out that the issue lies in [pyproject.toml](https://github.com/langchain-ai/langchain/blob/ca7da8f7ef9bc7a613ff07279c4603cad5fd175a/libs/langchain/pyproject.toml) which is using relative paths like `../core` and `../community` in some occasions. Additionally, even after replacing `../` with `libs/` (which I am not sure if it breaks something else), the actual `core` and `community` directories are never copied over in [dev.Dockerfile](https://github.com/langchain-ai/langchain/blob/ca7da8f7ef9bc7a613ff07279c4603cad5fd175a/libs/langchain/dev.Dockerfile). These should also be copied in the created docker container, similarly to [line 41](https://github.com/langchain-ai/langchain/blob/ca7da8f7ef9bc7a613ff07279c4603cad5fd175a/libs/langchain/dev.Dockerfile#L41).

After making these two changes, the container was successfully built. I'll check out whether the change of paths in pyproject.toml is affecting any other files, and if not I will create a PR for this.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:

1. Fork and clone the repo on your machine
2. Open it with VS Code (with Dev Containers extension installed)
3. Run the VS Code command: "Dev Containers: Rebuild Container"

### Expected behavior

Build the development docker container without errors

**Comment by aduston** [comment]
@SavvasMohito I just ran into the same issue. Are you planning on making a pull request? Thanks!

**Comment by SavvasMohito** [comment]
Hi @aduston, yes I'll have a look at it this week and try to come up with a PR. Thanks for reminding me 😄
