### ISSUE TITLE
ParentDocumentRetriever.get_relevant_documents() got empty result

### ISSUE THREAD

**Issue by wennycooper** [langchain-ai/langchain#14643]
I have two code.
The 1st code is to load PDF documents and use ParentDocumentRetriever to add_documents() and save vectorstore to local disk.
The 2nd code is to load vectorstore and call ParentDocumentRetriever.get_relevant_documents
The problem is, the ParentDocumentRetriever.get_relevant_documents() got empty result.
Any idea??
What is the inMemoryStore for??

Here are the two codes:

### the 1st code: LoadDocumentsAndSaveVectorstore.py
```
loader = DirectoryLoader('data/',
                         glob='**/*.pdf',
                         loader_cls=PyPDFLoader)
docs = loader.load()

store = InMemoryStore()
parent_splitter = RecursiveCharacterTextSplitter(chunk_size=1000)
child_splitter = RecursiveCharacterTextSplitter(chunk_size=128, chunk_overlap=64)

texts = [""]
vectorstore = FAISS.from_texts(texts, embedding_function)

retriever = ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
)

retriever.add_documents(docs, ids=None)
vectorstore.save_local("ppstore")

print("save data to ppstore")
```
The 1st code works fine.

The 2nd file is to load the vectorstore and query.
The strange thing is, the **retriever1.get_relevant_documents(query)** got empty result.

### the 2nd code: load vectorstore and use retriever to get relevant_documents
```
print("load ppstore")
store = InMemoryStore()
parent_splitter = RecursiveCharacterTextSplitter(chunk_size=1000)
child_splitter = RecursiveCharacterTextSplitter(chunk_size=128, chunk_overlap=64)

db = FAISS.load_local("ppstore", embedding_function)
retriever1 = ParentDocumentRetriever(
    vectorstore=db,
    docstore=store,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
)

query = "Please describe Sardina dataset"
print("query:", query)

sub_docs = db.similarity_search(query)
print("=== check small chunk ===")
print(sub_docs[0].page_content)
print(len(sub_docs[0].page_content))  ## this respond OK, the len is a little bit smaller than 128

retrieved_docs = retriever1.get_relevant_documents(query)   ## I got empty result
print("=== check larger chunk ===")
print(retrieved_docs[0].page_content)
print(len(retrieved_docs[0].page_content)) 
```

**Comment by wennycooper** [comment]
No.. the answer is not acceptable.
I already save the embeddings and contents into the vectore.
Now I just want to load it from the DB.

I don't want to add anymore data.

**Comment by madeofstardust** [comment]
Hey,
can you check out this answer:
https://stackoverflow.com/questions/77385587/persist-parentdocumentretriever-of-langchain

I think it might help.

**Comment by wennycooper** [comment]
Yes, thank you very much!

**Comment by gcheron** [comment]
This PR aims at adding support for document storage in a SQL database: https://github.com/langchain-ai/langchain/pull/15909
