### ISSUE TITLE
Bug in Text splitting while using langchain.text_splitter.split_text_on_tokens¶

### ISSUE THREAD

**Issue by MuhammadSaqib001** [langchain-ai/langchain#14649]
### System Info

Langchain Version = 0.0.311
Python Version = 3.9
Tried it on my local system as well on Company's hosted Jupyter Hub as well 

### Who can help?

@eyurtsev @agola11

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.text_splitter import TokenTextSplitter
token_splitter_model_name = "gpt-3.5-turbo"
SPLIT_CHUNK_SIZE = 1024
CHUNK_OVERLAP = 256
text_splitter = TokenTextSplitter.from_tiktoken_encoder(model_name=token_splitter_model_name, chunk_size=SPLIT_CHUNK_SIZE , chunk_overlap = CHUNK_OVERLAP)

blog_content= ' your text here'
blog_splits=text_splitter.split_text(blog_content)
```

### Expected behavior

The ways this token text splitter works , isn't how it is intended to work .

For Example :-
When specified chunk_size = 1024 and overlap = 256 with input text tokens = 991 , it made two chunks ;
first = token[0 : 991]
second = token[768 : 991]

but logically it should work this ways .

If input text token >1024 , there should be two chunks .
first = token[0 : 1024]
second = token[768 : ]
and so on ..............

If input text token <=1024 , there should be one chunk only .
first = token[ 0 : ]

More details on this issue raised previously :- https://github.com/langchain-ai/langchain/issues/5897

**Comment by sweetkane** [comment]
I am working on a PR for this issue. It should be up within 24 hours.

**Comment by MuhammadSaqib001** [comment]
@sweetkane nice . good to go . I have resolved this issue in my codebase .
