### ISSUE TITLE
(RedisSemanticCache + ChatOpenAI + OpenAIEmbeddings) - Not working as expected - Wanted to understand, if I am doing something wrong here.

### ISSUE THREAD

**Issue by mks-1001** [langchain-ai/langchain#14640]
### System Info

# Dependency Versions
langchain==0.0.349
langchain-community==0.0.1
langchain-core==0.0.13
openai==1.3.8

# Python Version
Python 3.11.4

# Redis Stack Version
redis-stack-server 6.2.0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.globals import set_llm_cache
from langchain.cache import RedisSemanticCache
from langchain.embeddings import OpenAIEmbeddings
from langchain_community.chat_models import ChatOpenAI
from redis import Redis
import time

llm = ChatOpenAI(openai_api_key='<OPENAI_API_KEY>', model_name='gpt-3.5-turbo')

cache = RedisSemanticCache(redis_url="redis://localhost:6379", 
                           embedding=OpenAIEmbeddings(openai_api_key='<OPENAI_API_KEY>'), 
                           score_threshold=0.95)
set_llm_cache(cache)

start = time.time()
response = llm.predict("""Tell me about USA in only two sentences""")
print(time.time()-start)
print(response)

start = time.time()
response = llm.predict("""Tell me about INDIA in only two sentences""")
print(time.time()-start)
print(response)

start = time.time()
response = llm.predict("""What is LLMs in the context of GEN AI ?""")
print(time.time()-start)
print(response)

### Expected behavior

As the score_threshold is set to 0.98, I expect all the three prompts to give three different responses. But we are getting one response for all the three prompts.

Output from running the script : 

4.252941131591797
The United States of America is a federal republic consisting of 50 states, a federal district, five major self-governing territories, and various possessions. It is a diverse and influential country known for its cultural and economic power on the global stage.
0.3903520107269287
The United States of America is a federal republic consisting of 50 states, a federal district, five major self-governing territories, and various possessions. It is a diverse and influential country known for its cultural and economic power on the global stage.
0.6625611782073975
The United States of America is a federal republic consisting of 50 states, a federal district, five major self-governing territories, and various possessions. It is a diverse and influential country known for its cultural and economic power on the global stage.

**Comment by antonum** [comment]
Try adjusting `score_threshold=0.05` 

The lower the threshold - the more similar requests must be to match the cached results.
