### ISSUE TITLE
Getting "object has no field "documents" error with extended BaseRetriever classs

### ISSUE THREAD

**Issue by paulfields** [langchain-ai/langchain#14659]
### Issue you'd like to raise.

I am attempting to call an instance of ConversationalRetrieverChain with a list of dictionary objects that I've pre-processed with a similarity search and cohere reranker. I've created an extension of BaseRetriever in order to pass my list of dictionary objects to the "retriever=" parameter. However when my extended class instantiates, I get an error saying "seai_retriever object has no field "documents".  My code is below. What am I doing wrong?

```
from langchain.schema.retriever import BaseRetriever
from langchain.schema.document import Document
from langchain.callbacks.manager import CallbackManagerForRetrieverRun
from typing import List

class seai_retriever(BaseRetriever):
    def __init__(self, documents):
        self.documents = documents

    def retrieve(self, query, top_n=10):
        retrieved_docs = [doc for doc in self.documents if query.lower() in doc['content'].lower()]
        retrieved_docs = sorted(retrieved_docs, key=lambda x: x['content'].find(query), reverse=True)[:top_n]        
        return retrieved_docs
    
    def _get_relevant_documents(self, query: str, *, run_manager: CallbackManagerForRetrieverRun) -> List[Document]:
        retrieved_docs = [doc for doc in self.documents if query.lower() in doc['content'].lower()]
        retrieved_docs = sorted(retrieved_docs, key=lambda x: x['content'].find(query), reverse=True)[:top_n]        
        return retrieved_docs
```

**Comment by paulfields** [comment]
With the code you gave me 
<class seai_retriever(BaseRetriever):
    def __init__(self, documents):
        self.documents_dict = documents> I am still getting the error below.
Exception has occurred: ValueError "seai_retriever" object has no field "documents_dict"

Basically I am just trying to satisfy the expected parameter <retriever=> in the call to ConversationalRetrieverChain (below). I already have a list of dictionary objects created by doing a semantic search from a user query and then re-ranking the results using Cohere. I just want the shortest path to providing that <retriever> object using my existing list of dictionary objects. What is the best overall solution?
<        qa = ConversationalRetrievalChain.from_llm(
            llm=ChatOpenAI(
                temperature=1,
                model_name='gpt-4',
                max_tokens=32000,
                openai_api_key=OPENAI_API_KEY
            ),
            chain_type="stuff",
            get_chat_history=lambda o: o,
            return_generated_question=True,
            verbose=False,
            retriever=retriever,
            return_source_documents=True,
            memory=memory
        )>

**Comment by pradhyumna85** [comment]
Please use the below class definition and it should work:
```python
from langchain.schema.retriever import BaseRetriever
from langchain.schema.document import Document
from langchain.callbacks.manager import CallbackManagerForRetrieverRun
from pydantic import BaseModel
from typing import List

class seai_retriever(BaseRetriever,BaseModel):
    documents: dict
    
    class Config:
        arbitrary_types_allowed = True

    def retrieve(self, query, top_n=10):
        retrieved_docs = [doc for doc in self.documents if query.lower() in doc['content'].lower()]
        retrieved_docs = sorted(retrieved_docs, key=lambda x: x['content'].find(query), reverse=True)[:top_n]        
        return retrieved_docs
    
    def _get_relevant_documents(self, query: str, *, run_manager: CallbackManagerForRetrieverRun) -> List[Document]:
        retrieved_docs = [doc for doc in self.documents if query.lower() in doc['content'].lower()]
        retrieved_docs = sorted(retrieved_docs, key=lambda x: x['content'].find(query), reverse=True)[:top_n]        
        return retrieved_docs
```

Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
