### ISSUE TITLE
Gemini not support SystemMessage and raise an error

### ISSUE THREAD

**Issue by Casper-Mars** [langchain-ai/langchain#14700]
### System Info

LangChain: 0.0.348
langchain-google-genai: 0.0.3
python: 3.11
os: macOS11.6

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

langchain_google_genai.chat_models.ChatGoogleGenerativeAIError: Message of 'system' type not supported by Gemini. Please only provide it with Human or AI (user/assistant) messages.

### Expected behavior

no error

**Comment by dheerajiiitv** [comment]
> ### System Info
> LangChain: 0.0.348 langchain-google-genai: 0.0.3 python: 3.11 os: macOS11.6
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [x]  My own modified scripts
> 
> ### Related Components
> * [x]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [ ]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> langchain_google_genai.chat_models.ChatGoogleGenerativeAIError: Message of 'system' type not supported by Gemini. Please only provide it with Human or AI (user/assistant) messages.
> 
> ### Expected behavior
> no error

+1

**Comment by Casper-Mars** [comment]
Is there a convenient, fast solution for adapting to Gemini?

**Comment by dheerajiiitv** [comment]
Instead of chat models ChatVertexAi use. VertexAi

**Comment by kientv** [comment]
>   # TODO: Gemini doesn't seem to have a concept of system messages yet.

**Comment by hinthornw** [comment]
Add the system message comment to a human/user message.

**Comment by AyushMaggu** [comment]
Use the below code as a basic workaround. This is basically adding both the system prompt and chat history in the human user prompt itself:

from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory()

query="xyz"
memory.chat_memory.add_user_message(query)

result=llm.invoke(f"This is the system message that provides general instructions regarding you(AI) and the nature of the conversation : {system_message}."
f"You are also given history of the current ongoing chat between you(AI) and Human : {memory.chat_memory.messages}."  
f"Respond to this new human question: "+ query)

memory.chat_memory.add_ai_message(result.content)
Markdown(result.content)

**Comment by AyushMaggu** [comment]
Use the below code as a basic workaround. This is basically adding both the system prompt and chat history in the human user prompt itself:

from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory()

system_message="abc"
query="xyz"
memory.chat_memory.add_user_message(query)

result=llm.invoke(f"This is the system message that provides general instructions regarding you(AI) and the nature of the conversation : {system_message}."
f"You are also given history of the current ongoing chat between you(AI) and Human : {memory.chat_memory.messages}."
f"Respond to this new human question: "+ query)

memory.chat_memory.add_ai_message(result.content)
Markdown(result.content)
