### ISSUE TITLE
Issue: Rephrased question in included in the on_llm_new_token method while streaming the response from the LLM

### ISSUE THREAD

**Issue by summer1704** [langchain-ai/langchain#14703]
### Issue you'd like to raise.

Hi, I am  trying to stream the response from the llm  back to the client by using a callback with a custom StreamHandler, but the on_llm_new_token also includes the output from the rephrase_question step. while the final response does not include the rephrased answer. I don't want the rephrased question to be present in the response  that is streaming.
the StreamHandler class is given below

`class StreamHandler(BaseCallbackHandler):
    def __init__(self):
        self.text = ""

    def on_llm_new_token(self, token: str, **kwargs):
        old_text = self.text
        self.text += token

        # Calculate the new content since the last emission
        new_content = self.text[len(old_text) :]
        socketio.emit("update_response", {"response": new_content})`

The qa-chain is defined as below:

qa_chain = ConversationalRetrievalChain.from_llm(
        llm=chat,
        retriever=MyVectorStoreRetriever(
            vectorstore=vectordb,
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": SIMILARITY_THRESHOLD, "k": 1},
        ),
        return_source_documents=True,
        rephrase_question=False)
 response = qa_chain(
        {
            "question": user_input,
            "chat_history":chat_history,
           
        },callbacks=[stream_handler] )

**Comment by summer1704** [comment]
> _🤖_
> 
> Hello @summer1704! 🖐️ I'm [Dosu](https://dosu.dev), a friendly bot here to help you out while waiting for a human maintainer. I can assist with bug fixes, answer queries, and guide you on becoming a contributor. So, what can I help you with today?
> 
> Based on your description, it seems like you want to exclude the rephrased question from the streaming response. You can achieve this by modifying the `on_llm_new_token` method in your `StreamHandler` class to check if the token is part of the prompts before adding it to the queue. Here's how you can do it:
> 
> ```python
> class StreamHandler(BaseCallbackHandler):
>     def __init__(self):
>         self.text = ""
>         self.prompts = []  # Store the prompts
> 
>     def on_llm_start(self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any) -> None:
>         self.prompts = prompts  # Update the prompts
> 
>     def on_llm_new_token(self, token: str, **kwargs):
>         # Check if the token is not part of the prompts before adding it to the queue
>         if token is not None and token != "" and token not in self.prompts:
>             old_text = self.text
>             self.text += token
> 
>             # Calculate the new content since the last emission
>             new_content = self.text[len(old_text) :]
>             socketio.emit("update_response", {"response": new_content})
> ```
> 
> In this modification, we store the prompts in the `on_llm_start` method and then check if the token is part of the prompts in the `on_llm_new_token` method. If the token is not part of the prompts, it is added to the queue. This way, the rephrased question (which is part of the prompts) will not be included in the streaming response.
> 
> Please note that this solution assumes that the `prompts` parameter in the `on_llm_start` method contains the rephrased question. If this is not the case, you might need to adjust the solution accordingly.
> 
> I hope this helps! If you have any further questions, feel free to ask.
> 
> Best regards, [Dosu](https://dosu.dev)
> 
> ## Sources
> * [libs/langchain/langchain/callbacks/streaming_aiter.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/callbacks/streaming_aiter.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot How will I get the rephrased question to check if the token is part of it in the on_llm_new_token method

**Comment by summer1704** [comment]
@dosu-bot Is there any way I can completely disable the rephrasing user input part

> ### Issue you'd like to raise.
> Hi, I am trying to stream the response from the llm back to the client by using a callback with a custom StreamHandler, but the on_llm_new_token also includes the output from the rephrase_question step. while the final response does not include the rephrased answer. I don't want the rephrased question to be present in the response that is streaming. the StreamHandler class is given below
> 
> `class StreamHandler(BaseCallbackHandler): def **init**(self): self.text = ""
> 
> ```
> def on_llm_new_token(self, token: str, **kwargs):
>     old_text = self.text
>     self.text += token
> 
>     # Calculate the new content since the last emission
>     new_content = self.text[len(old_text) :]
>     socketio.emit("update_response", {"response": new_content})`
> ```
> 
> The qa-chain is defined as below:
> 
> qa_chain = ConversationalRetrievalChain.from_llm( llm=chat, retriever=MyVectorStoreRetriever( vectorstore=vectordb, search_type="similarity_score_threshold", search_kwargs={"score_threshold": SIMILARITY_THRESHOLD, "k": 1}, ), return_source_documents=True, rephrase_question=False) response = qa_chain( { "question": user_input, "chat_history":chat_history,
> 
> ```
>     },callbacks=[stream_handler] )
> ```
> 
> ### Suggestion:
> _No response_

@dosu-bot Is there any way I can completely disable the rephrasing user input part

**Comment by pengkang1991** [comment]
> @dosu-bot有什么方法可以完全禁用改写用户输入部分
> 
> > ### 您想提出的问题。
> > 您好，我正在尝试使用带有自定义 StreamHandler 的回调将 llm 的响应流式传输回客户端，但 on_llm_new_token 还包括 rephrase_question 步骤的输出。而最终的回复不包括改写的答案。我不希望重新表述的问题出现在流式传输的响应中。下面给出了 StreamHandler 类
> > `class StreamHandler(BaseCallbackHandler): def **init** (self): self.text = ""
> > ```
> > def on_llm_new_token(self, token: str, **kwargs):
> >     old_text = self.text
> >     self.text += token
> > 
> >     # Calculate the new content since the last emission
> >     new_content = self.text[len(old_text) :]
> >     socketio.emit("update_response", {"response": new_content})`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > qa链定义如下：
> > qa_chain = ConversationalRetrievalChain.from_llm( llm=聊天，检索器=MyVectorStoreRetriever( vectorstore=vectordb, search_type="similarity_score_threshold", search_kwargs={"score_threshold": SIMILARITY_THRESHOLD, "k": 1}, ), return_source_documents=True, rephrase_question=False)响应 = qa_chain( { "问题": user_input, "聊天历史记录":聊天历史记录,
> > ```
> >     },callbacks=[stream_handler] )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 建议：
> > _没有反应_
> 
> @dosu-bot有什么方法可以完全禁用改写用户输入部分

你好，请问你解决这个问题了吗。我也遇到了同样的问题，使用ConversationalRetrievalChain.from_llm 做 异步的时候，当传入聊天记录的时候，异步回调的是重新表述的问题，并不是我想要的答案。

**Comment by pengkang1991** [comment]
好，请问你解决这个问题了吗。我也遇到了同样的问题，使用ConversationalRetrievalChain.from_llm 做异步的时候，当上传聊天记录的时候，异步回调是重新处理后的问题，不是我想要的的答案。

**Comment by prapul-kumar** [comment]
One solution that worked for me is to check the content of prompt in on_llm_start, So basically when the question is rephrased, The LLM uses a dirrerent prompt than what we give as input so we can use a if condition to avoid streaming those token

```
class QueueCallbackHandler(BaseCallbackHandler):
    rephrase_question: bool = False
    def __init__(self, queue):
        self.queue = queue
        self.prompts = []  # Store the prompts
        self.rephrase_question=False
        self.question = ""
        self.start_time=time.time()

    def on_llm_start(self, serialized, prompts, **kwargs):
        self.prompts = prompts  # Update the prompts
        if len(prompts):
            self.question = prompts[-1][:150]

    def on_llm_new_token(self, token: str, **kwargs) -> None:
           #this is where we are ignoring the tokens generated by the rephrased question part
            if "Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question" not in self.question:
                print("stream start ",time.time()-self.start_time)
                self.queue.put(
                    {
                        "event": "message",
                        "id": "message_id",
                        "retry": 1,
                        "data": token,
                    }
                )

    def on_llm_end(self, *args, **kwargs) :
        return self.queue.empty()

output_queue = Queue()
llm = Bedrock(
    model_id="some_model_id",
    model_kwargs=model_parameter,
    client=<some client>,
    streaming=True,
    callbacks=[QueueCallbackHandler(queue=output_queue)],
    )
```
