### ISSUE TITLE
CallbackHandler on_llm_new_token method not fire with ChatGoogleGenerativeAI(Gemini) but works fine with ChatOpenAI when streaming true

### ISSUE THREAD

**Issue by hasansustcse13** [langchain-ai/langchain#14709]
### System Info

aiohttp==3.9.1
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.1.0
attrs==23.1.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
colorama==0.4.6
dataclasses-json==0.6.3
frozenlist==1.4.0
google-ai-generativelanguage==0.4.0
google-api-core==2.15.0
google-auth==2.25.2
google-generativeai==0.3.1
googleapis-common-protos==1.62.0
greenlet==3.0.2
grpcio==1.60.0
grpcio-status==1.60.0
idna==3.6
jsonpatch==1.33
jsonpointer==2.4
langchain-community==0.0.3
langchain-core==0.1.0
langchain-google-genai==0.0.3
langsmith==0.0.70
marshmallow==3.20.1
multidict==6.0.4
mypy-extensions==1.0.0
numpy==1.26.2
packaging==23.2
Pillow==10.1.0
proto-plus==1.23.0
protobuf==4.25.1
pyasn1==0.5.1
pyasn1-modules==0.3.0
pydantic==2.5.2
pydantic_core==2.14.5
PyYAML==6.0.1
requests==2.31.0
rsa==4.9
sniffio==1.3.0
SQLAlchemy==2.0.23
tenacity==8.2.3
tqdm==4.66.1
typing-inspect==0.9.0
typing_extensions==4.9.0
urllib3==2.1.0
yarl==1.9.4

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from typing import Any, Optional
from uuid import UUID

from langchain.chains import LLMChain
from langchain_community.chat_models import ChatOpenAI
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.outputs import LLMResult
from langchain_core.prompts import PromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

prompt_template = "Tell me details about the Company {name} with 2 bullet point?"


class StreamingLLMCallbackHandler(BaseCallbackHandler):

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        print(token, end='')

    def on_llm_end(self, response: LLMResult, *, run_id: UUID, parent_run_id: Optional[UUID] = None, **kwargs: Any) -> Any:
        print('\n\n---------------------LLM_END--------------------------')
        print(response.generations[0][0].text)


def gemini_stream_with_cb():
    llm = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key='AIzaSPVggdfgerweselzbVCHH', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
    llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
    llm_chain.run(name="Google")


def openai_stream_with_cb():
    llm = ChatOpenAI(openai_api_key='sk-pSHx9qACbzdgsdgyuuyNCXpZ0', model='gpt-4', streaming=True, callbacks=[StreamingLLMCallbackHandler()])
    llm_chain = LLMChain(llm=llm, prompt=PromptTemplate.from_template(prompt_template), verbose=True)
    llm_chain.run(name="Open AI")


if __name__ == '__main__':
    gemini_stream_with_cb()
    # openai_stream_with_cb()

```

**ChatGoogleGenerativeAI:** on_llm_new_token not triggered, but on_llm_end triggered
**ChatOpenAI**: Both triggered

### Expected behavior

 **on_llm_new_token should trigger for ChatGoogleGenerativeAI**

**Comment by hasansustcse13** [comment]
```
llm = ChatGoogleGenerativeAI(model="gemini-pro")
for chunk in llm.stream("Write a limerick about LLMs."):
    print(chunk.content)
    print("---")
```

If I call the llm directly without `LLMChain` it provides streaming as expected.  So it supports streaming.
ChatGoogleGenerativeAI won't call `on_llm_new_token` at all (no exception) but it call the `on_llm_end` method after finished. 
So this is a bug I think of `LLMChain`

**Comment by hasansustcse13** [comment]
After further investigation, I have found the problem. LLMChain Call `_generate` method at some point of the corresponding llm. 
Gemini and OpenAI implementation is different. Gemini doesn't call the _stream same as OpenAI. That's why it doesn't call the `on_llm_new_token`. See the difference. 
**ChatGoogleGenerativeAI: (Not call _stream)** 

  ```
  def _generate(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> ChatResult:
        params = self._prepare_params(messages, stop, **kwargs)
        response: genai.types.GenerateContentResponse = _chat_with_retry(
            **params,
            generation_method=self._generation_method,
        )
        return _response_to_result(response)
```
**ChatOpenAI:**
   ```
 def _generate(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        stream: Optional[bool] = None,
        **kwargs: Any,
    ) -> ChatResult:
        should_stream = stream if stream is not None else self.streaming
        if should_stream:
            stream_iter = self._stream(
                messages, stop=stop, run_manager=run_manager, **kwargs
            )
            return generate_from_stream(stream_iter)
        message_dicts, params = self._create_message_dicts(messages, stop)
        params = {
            **params,
            **({"stream": stream} if stream is not None else {}),
            **kwargs,
        }
        response = self.completion_with_retry(
            messages=message_dicts, run_manager=run_manager, **params
        )
        return self._create_chat_result(response)
```

**Does anyone work on this issue?**

**Comment by lkuligin** [comment]
As you've correctly mentioned, I'm not sure streaming actually happens in your case. If you invoke `stream` method on the model itself, callback is working (since streaming happens).

According to @hinthornw , the new approach is that `streaming shouldn't be initialized on the LLM itself`. @hinthornw could you help to understand what's the proper way to use streaming with LLMChain, please?

**Comment by hasansustcse13** [comment]
@lkuligin Will you work on this issue? Without it LLMChain (Mybe No Chain) will work with streaming. Do you have any idea how to streaming with LLMChain and Gemini? It would be great help.

**Comment by hasansustcse13** [comment]
@lkuligin @hinthornw Is there any update to support the stream in Gemini and Chain?

**Comment by pseudotensor** [comment]
https://github.com/langchain-ai/langchain/pull/15459

**Comment by hadfield** [comment]
Is there an update on when this will be merged into a release?
