### ISSUE TITLE
Raise "Message of 'system' type not supported by Gemini" exception by ChatGoogleGenerativeAI with ConversationalRetrievalChain

### ISSUE THREAD

**Issue by hasansustcse13** [langchain-ai/langchain#14710]
### System Info

langchain==0.0.350
langchain-community==0.0.3
langchain-core==0.1.0
langchain-google-genai==0.0.3
google-ai-generativelanguage==0.4.0
google-api-core==2.15.0
google-auth==2.25.2
google-generativeai==0.3.1
googleapis-common-protos==1.62.0

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
class LangChainChatService(ChatBaseService):
    def __init__(self, model: LangchainChatModel, tool_query=None):
        super().__init__()
        self.model = model
        self.request_manager = api_request_manager_var.get()
        self.tool_query = tool_query

    async def http_chat_async(self) -> dict:
        formatted_chat_history = [] if self.tool_query else self.get_formatted_chat_history(self.model.chat_history)
        qa = self._get_qa_chain()
        qa.return_source_documents = self.model.return_source_documents
        qa.return_generated_question = True

        query_start = time.time()
        question = self.tool_query or self.model.query
        qa_response = await qa.ainvoke({"question": question, "chat_history": formatted_chat_history})
        query_end = time.time()

        result = {
            'query_result': qa_response.get("answer"),
            'query_time': int((query_end - query_start) * 1000),
            'generated_question': qa_response.get('generated_question'),
            'source_documents': [document.__dict__ for document in qa_response.get("source_documents", [])],
        }

        self._publish_chat_history(result)

        return result

    def _get_qa_chain(self, callbacks: Callbacks = None) -> BaseConversationalRetrievalChain:
        collection_name = get_langchain_collection_name(self.model.client_id)
        connection_args = {"host": AppConfig.vector_db_host, "port": AppConfig.vector_db_port}
        embeddings = LLMSelector(self.model).get_embeddings()
        vector_store = Milvus(embeddings, collection_name=collection_name, connection_args=connection_args)

        expression = get_expression_to_fetch_db_text_from_ids(**self.model.model_dump())
        # Instance of ChatGoogleGenerativeAI
        qa_llm = LLMSelector(self.model).get_language_model(streaming=self.model.stream_response, callbacks=callbacks)
        condense_question_llm = LLMSelector(self.model).get_language_model()

        qa = ConversationalRetrievalChain.from_llm(
            llm=qa_llm,
            retriever=vector_store.as_retriever(search_type="similarity", search_kwargs={"k": self.model.similarity_top_k, 'expr': expression}),
            condense_question_llm=condense_question_llm,
            verbose=True
        )
        return qa
```
The code use this prompt from langchain code base
```
prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Helpful Answer:"""
QA_PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)
```

I see that after fetching context document from vector database langchain generate `SystemMessage`  along with `HumanMessage` using the above prompt. And there is a validation in `ChatGoogleGenerativeAI` to prevent system message. 
This is the possible reason for producing the following error.

`langchain_google_genai.chat_models.ChatGoogleGenerativeAIError: Message of 'system' type not supported by Gemini. Please only provide it with Human or AI (user/assistant) messages.`

### Expected behavior

As I didn't provide any SystemMessage, ChatGoogleGenerativeAI should work without exception. 
This bug is related to Langchain.

**Comment by hasansustcse13** [comment]
As I have mentioned earlier langchain create the SystemMessage using a prompt. I didn't provide the prompt or any kind of system message. So the fix should available in langchain code base.

**Comment by kostyay** [comment]
Im facing the same problem

**Comment by lkuligin** [comment]
duplicate #14700

**Comment by kientv** [comment]
Do someone know that how to fix or workaround   
>   File "/home/kientv/Pictures/mitiga-lab/chat-langchain/venv/lib/python3.11/site-packages/langchain_google_genai/chat_models.py", line 189, in _get_role
>     raise ChatGoogleGenerativeAIError(
> langchain_google_genai.chat_models.ChatGoogleGenerativeAIError: Message of 'system' type not supported by Gemini. Please only provide it with Human or AI (user/assistant) messages.
>

**Comment by hinthornw** [comment]
You can set the prompt to not use a system message.

```
prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Helpful Answer:"""
my_prompt = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)


qa = ConversationalRetrievalChain.from_llm(
            llm=qa_llm,
            retriever=vector_store.as_retriever(search_type="similarity", search_kwargs={"k": self.model.similarity_top_k, 'expr': expression}),
            condense_question_llm=condense_question_llm,
            verbose=True,
            combine_docs_chain_kwargs={"prompt": my_prompt}
        )
```

**Comment by kientv** [comment]
> You can set the prompt to not use a system message.
> 
> ```
> prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.
> 
> {context}
> 
> Question: {question}
> Helpful Answer:"""
> my_prompt = PromptTemplate(
>     template=prompt_template, input_variables=["context", "question"]
> )
> 
> 
> qa = ConversationalRetrievalChain.from_llm(
>             llm=qa_llm,
>             retriever=vector_store.as_retriever(search_type="similarity", search_kwargs={"k": self.model.similarity_top_k, 'expr': expression}),
>             condense_question_llm=condense_question_llm,
>             verbose=True,
>             combine_docs_chain_kwargs={"prompt": my_prompt}
>         )
> ```

How it work with `ChatPromptTemplate.from_messages`
```
prompt = ChatPromptTemplate.from_messages(
            [
                ("system", response_template),
                MessagesPlaceholder(variable_name="chat_history"),
                ("human", "{question}"),
            ]
        )
```

Thank you
