### ISSUE TITLE
BingAI

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#1472]
It would be great to see BingAI integration with LangChain. For inspiration, check out [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/src/BingAIClient.js) by @waylaidwanderer.

**Comment by hwchase17** [comment]
this isn't an official api right? if its not, probably not a priority tbh

**Comment by louis-li** [comment]
Try using agent with BingSearchWrapper?

**Comment by slavakurilyak** [comment]
[Here](https://github.com/acheong08/EdgeGPT) is the reverse-engineered API of Microsoft's Bing Chat AI

**Comment by acheong08** [comment]
Not relevant as many of the reversed wrappers are no longer maintained
