### ISSUE TITLE
LlaMa

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#1473]
It would be great to see LangChain integrate with LlaMa, a collection of foundation language models ranging from 7B to 65B
parameters.

LlaMa is a language model that was developed to improve upon existing models such as ChatGPT and GPT-3. It has several advantages over these models, such as improved accuracy, faster training times, and more robust handling of out-of-vocabulary words. LlaMa is also more efficient in terms of memory usage and computational resources. In terms of accuracy, LlaMa outperforms ChatGPT and GPT-3 on several natural language understanding tasks, including sentiment analysis, question answering, and text summarization. Additionally, LlaMa can be trained on larger datasets, enabling it to better capture the nuances of natural language. Overall, LlaMa is a more powerful and efficient language model than ChatGPT and GPT-3.

Here's the official [repo](https://github.com/facebookresearch/llama) by @facebookresearch. Here's the research [abstract](https://arxiv.org/abs/2302.13971v1) and [PDF,](https://arxiv.org/pdf/2302.13971v1.pdf) respectively.

Note, this project is not to be confused with LlamaIndex (previously GPT Index) by @jerryjliu.

**Comment by hwchase17** [comment]
@conceptofmind i believe you said you were working on this?

**Comment by conceptofmind** [comment]
> @conceptofmind i believe you said you were working on this?

Yes actively working on this with a group of peers. We have successfully deployed inference with the 65B models. Working on a wrapper now.

**Comment by conceptofmind** [comment]
Would have to think about how to handle the sizes of different models though. I could see this becoming an issue for the end user.......

**Comment by Electomanic** [comment]
There is some ongoing work to use GPTQ to compress the models to 3 or 4 bits in this [repo](https://github.com/qwopqwop200/GPTQ-for-LLaMa). Also a discussion going on over at the oobabooga [repo](https://github.com/oobabooga/text-generation-webui/issues/177).

Not sure if this is going to work but might be something to keep an eye on. If it works out it could be possible to run the larger models on a single consumer grade GPU.

The original paper is available here on [arxiv](https://arxiv.org/abs/2210.17323).

**Comment by conceptofmind** [comment]
4 bit may be plausible. 8 bit should be fine. The weights are already in fp16 from my understanding. I would have to evaluate this further.

**Comment by jooray** [comment]
Yes, the weights are fp16. You can convert and run 4-bit using https://github.com/ggerganov/llama.cpp. I think 30B with full precision might be at least on par to 65B 4-bit in case of results. Llama.cpp runs on CPU, including Apple Silicon, which might be a good choice for developers with recent Macbooks, they could develop and run experiments locally with langchain without a need of GPUs.

**Comment by fblissjr** [comment]
FYI - alternative to the cpu-only one that works for many consumer-end gpu's - confirmed working on 13B llama locally with a 4090: https://github.com/qwopqwop200/GPTQ-for-LLaMa

**Comment by fblissjr** [comment]
> There is some ongoing work to use GPTQ to compress the models to 3 or 4 bits in this [repo](https://github.com/qwopqwop200/GPTQ-for-LLaMa). Also a discussion going on over at the oobabooga [repo](https://github.com/oobabooga/text-generation-webui/issues/177).
> 
> Not sure if this is going to work but might be something to keep an eye on. If it works out it could be possible to run the larger models on a single consumer grade GPU.
> 
> The original paper is available here on [arxiv](https://arxiv.org/abs/2210.17323).

Confirmed working on a single consumer grade 4090 here with 13B. Waiting on the 30B 4 bit weights - failed at trying to run them at fp16. :)

**Comment by conceptofmind** [comment]
I am aware of all these alternatives. We are waiting to hear back from Huggingface before the decision is made.

**Comment by gururise** [comment]
Using GPTQ 4-bit quantized 30B model, outputs are (as far as I can tell) very good.  Hope to see 4-bit support in LangChain.

**Comment by DamascusGit** [comment]
Any info on running 7B model with Langchain?

**Comment by niansa** [comment]
> Yes, the weights are fp16. You can convert and run 4-bit using https://github.com/ggerganov/llama.cpp. I think 30B with full precision might be at least on par to 65B 4-bit in case of results. Llama.cpp runs on CPU, including Apple Silicon, which might be a good choice for developers with recent Macbooks, they could develop and run experiments locally with langchain without a need of GPUs.

It'd be really neat if that's going to be an option :smile:
Sure it's slow but hey you can run it on a literal laptop.

**Comment by conceptofmind** [comment]
Llama has been added to Huggingface: https://github.com/huggingface/transformers/pull/21955

The only reason to add a specific wrapper would be to include the perf improvements from cpp or gptq

**Comment by linonetwo** [comment]
I think you are talking about a Pythion wrapper. So I'm going to write a TS wrapper for llama.cpp and alpaca.cpp for localhost private usage, if no one is working on this yet.

**Comment by linonetwo** [comment]
Here you are:

https://github.com/linonetwo/langchain-alpaca

https://www.npmjs.com/package/langchain-alpaca

It was very fast with my own `make` binary, and I'm using rebuild binary from https://github.com/antimatter15/alpaca.cpp/releases/latest , it become slower, I have asked this in https://github.com/antimatter15/alpaca.cpp/issues/88 , I will try address this if I got the reply.

For now, I will try to make a langchain-llama package.

**Comment by wiz64** [comment]
I'm eagerly waiting to try it for a project :D !!!

**Comment by asgeir** [comment]
If anyone's interested, I've made a pass at wrapping the llama.cpp shared library using ctypes and deriving a custom LLM class for it.
[https://gist.github.com/asgeir/3dd75109133b218bf62bab5ddfcbb387](url)

**Comment by rjadr** [comment]
FYI: I just submitted this pull request to integrate llama.cpp into langchain:
https://github.com/hwchase17/langchain/pull/2242

**Comment by juanps90** [comment]
> FYI: I just submitted this pull request to integrate llama.cpp into langchain: #2242

Thank you very much!!

Do you think it would be possible to run LLaMA on GPU as well somehow?

**Comment by conceptofmind** [comment]
> > FYI: I just submitted this pull request to integrate llama.cpp into langchain: #2242
> 
> Thank you very much!!
> 
> Do you think it would be possible to run LLaMA on GPU as well somehow?

You are able to load Llama in through Huggingface and use it in a GPU-accelerated environment. https://huggingface.co/docs/transformers/main/en/model_doc/llama

**Comment by kooshi** [comment]
I also added Kobold/text-generation-webui support so you can run Llama or whatever you want locally.
I only tested it a bit, but it worked well back when I made it. I didn't intend on making a PR or maintaining it though, so anyone can feel free to take it and hack on it:
https://github.com/hwchase17/langchain/compare/master...kooshi:langchain:kobold-api

**Comment by 1b5d** [comment]
I've written an app to run llama based models using docker here: https://github.com/1b5d/llm-api thanks to [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) and [llama-cpp](https://github.com/ggerganov/llama.cpp)
You can specify the model in the config file, and the app will download it automatically and expose it via an API
Additionally you can use https://github.com/1b5d/langchain-llm-api in order to use this exposed API with Langchain, it also supports streaming
My goal is to easily run different models locally (and also remote) and switch between them easily, then use these APIs to develop with Langchain

To run Alpaca:
- First configure and run `docker compose up` the API as described here: https://github.com/1b5d/llm-api 
- Then you can simply make requests to it 
```
curl --location 'localhost:8000/generate' \
--header 'Content-Type: application/json' \
--data '{
    "prompt": "What is the capital of France?",
    "params": {
        ...
    }
}'
```
- or you can play around with it using langchain via the lib 
```
pip install langchain-llm-api
```
```
from langchain_llm_api import LLMAPI

llm = LLMAPI()
llm("What is the capital of France?")
...
\nThe capital of France is Paris.
```
