### ISSUE TITLE
Langserve example from Quickstart tutorial not working

### ISSUE THREAD

**Issue by AvijeetPrasad** [langchain-ai/langchain#14757]
### System Info

Name                    Version                   Build  Channel
langchain                 0.0.350                  pypi_0    pypi
langchain-cli             0.0.19                   pypi_0    pypi
langchain-community       0.0.3                    pypi_0    pypi
langchain-core            0.1.1                    pypi_0    pypi
langchain-experimental    0.0.47                   pypi_0    pypi
python                    3.12.0          h47c9636_0_cpython    conda-forge

System: macOS 14.2 (Apple M1 chip)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Go to https://python.langchain.com/docs/get_started/quickstart
2. Do all the package installations as guided.
3. Copy the python code under the section 'Serving with Langserve' and save it to a file `serve.py`
4. Execute the file `python serve.py`
5. Open `http://localhost:8000` in browser

### Expected behavior

Expected to see Langserve UI. Got the following error instead.

---
LANGSERVE: Playground for chain "/category_chain/" is live at:
LANGSERVE:  │
LANGSERVE:  └──> /category_chain/playground/
LANGSERVE:
LANGSERVE: See all available routes at /docs/

LANGSERVE: ⚠️ Using pydantic 2.5.2. OpenAPI docs for invoke, batch, stream, stream_log endpoints will not be generated. API endpoints and playground should work as expected. If you need to see the docs, you can downgrade to pydantic 1. For example, `pip install pydantic==1.10.13`. See https://github.com/tiangolo/fastapi/issues/10360 for details.

INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     ::1:58516 - "GET / HTTP/1.1" 404 Not Found
INFO:     ::1:58516 - "GET /favicon.ico HTTP/1.1" 404 Not Found
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [91610]

**Comment by AvijeetPrasad** [comment]
Here's the code from the quickstart page for reference
```python
#!/usr/bin/env python
from typing import List

from fastapi import FastAPI
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI
from langchain.schema import BaseOutputParser
from langserve import add_routes

# 1. Chain definition


class CommaSeparatedListOutputParser(BaseOutputParser[List[str]]):
    """Parse the output of an LLM call to a comma-separated list."""

    def parse(self, text: str) -> List[str]:
        """Parse the output of an LLM call."""
        return text.strip().split(", ")


template = """You are a helpful assistant who generates comma separated lists.
A user will pass in a category, and you should generate 5 objects in that category in a comma separated list.
ONLY return a comma separated list, and nothing more."""
human_template = "{text}"

chat_prompt = ChatPromptTemplate.from_messages([
    ("system", template),
    ("human", human_template),
])
category_chain = chat_prompt | ChatOpenAI() | CommaSeparatedListOutputParser()

# 2. App definition
app = FastAPI(
    title="LangChain Server",
    version="1.0",
    description="A simple API server using LangChain's Runnable interfaces",
)

# 3. Adding chain route
add_routes(
    app,
    category_chain,
    path="/category_chain",
)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="localhost", port=8000)
```

**Comment by sishuoyang** [comment]
I had exactly the same problem.

```
INFO:     Started server process [55250]
INFO:     Waiting for application startup.

 __          ___      .__   __.   _______      _______. _______ .______     ____    ____  _______
|  |        /   \     |  \ |  |  /  _____|    /       ||   ____||   _  \    \   \  /   / |   ____|
|  |       /  ^  \    |   \|  | |  |  __     |   (----`|  |__   |  |_)  |    \   \/   /  |  |__
|  |      /  /_\  \   |  . `  | |  | |_ |     \   \    |   __|  |      /      \      /   |   __|
|  `----./  _____  \  |  |\   | |  |__| | .----)   |   |  |____ |  |\  \----.  \    /    |  |____
|_______/__/     \__\ |__| \__|  \______| |_______/    |_______|| _| `._____|   \__/     |_______|

LANGSERVE: Playground for chain "/agent/" is live at:
LANGSERVE:  │
LANGSERVE:  └──> /agent/playground/
LANGSERVE:
LANGSERVE: See all available routes at /docs/

LANGSERVE: ⚠️ Using pydantic 2.6.4. OpenAPI docs for invoke, batch, stream, stream_log endpoints will not be generated. API endpoints and playground should work as expected. If you need to see the docs, you can downgrade to pydantic 1. For example, `pip install pydantic==1.10.13`. See https://github.com/tiangolo/fastapi/issues/10360 for details.

INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     ::1:58755 - "GET /agent HTTP/1.1" 404 Not Found
INFO:     ::1:58756 - "GET /agent HTTP/1.1" 404 Not Found
```

**Comment by agirotra** [comment]
any solutions found for the above error ??

**Comment by trannhatquy** [comment]
any solutions please

**Comment by plpxsk** [comment]
Try following the suggestion in the error message, to downgrade `pydantic` from 2.x.x to 1.xx

Per above, this would be `pip install pydantic==1.10.13`

**Comment by Haydn-Mann** [comment]
I am still having issues wih this. Follow the tutorial from online also and still getting this issue

tutorial link: https://www.youtube.com/watch?v=OV2ZIWFBe0s&ab_channel=LangChain

**Comment by AnhDai1997** [comment]
change to
uvicorn.run(app, host="0.0.0.0", port=8000)

**Comment by wangzhuoya** [comment]
@sishuoyang 
😂It is not a mistake, you can open "http://localhost:8000/agent/playground/" in web.

**Comment by MohamedLahmeri01** [comment]
when you run your server.py , you need to configure in url to this path of your endpoint : 
`
# 1. the definition of our chain that we just built above
# 2. Our FastAPI app
# 3. definition of a route from which to serve the chain , which is done with "langserve.add_routes"

from typing import List

from fastapi import FastAPI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
# from langchain_openai import ChatOpenAI (for openai)
from langchain_groq import ChatGroq
from langserve import add_routes
import os

os.environ["GROQ_API_KEY"] = groq_api




# 1. Create prompt template
system_template = "Translate the following into {language}:"
prompt_template = ChatPromptTemplate.from_messages([
    ('system', system_template),
    ('user', '{text}')
])

# 2. Create model
model = ChatGroq(model="llama3-70b-8192")

# 3. Create parser
parser = StrOutputParser()

# 4. Create chain
chain = prompt_template | model | parser


# 4. App definition
app = FastAPI(
  title="LangChain Server",
  version="1.0",
  description="A simple API server using LangChain's Runnable interfaces",
)

# 5. Adding chain route

add_routes(
    app,
    chain,
    path="/chain", # add this endpoint to url in web-browser then add '/playground'
)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="localhost", port=8000)
`
so in the url write this : " http://localhost:8000/chain/playground/ " 
remember to replace '/chain' with what you wrote in add_route function in path attribute

**Comment by s1923** [comment]
the right website is localhost:8000/chain/playground/
