### ISSUE TITLE
ImportError: cannot import name 'GoogleGenerativeAI' from 'langchain_google_genai' ( from langchain_google_genai import GoogleGenerativeAI  )

### ISSUE THREAD

**Issue by vishal-chaudhary-ajmera** [langchain-ai/langchain#14753]
### System Info

- Python 3.11.7
- Windows 64bit
- langchain_google_genai==0.0.4
- langchain==0.0.350
- pymongo==4.6.0

### Who can help?

@sbusso
@jarib 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Install langchain_google_genai using `pip install -U langchain-google-genai`
2. Then, `from langchain_google_genai import GoogleGenerativeAI` 
3. This will produce error.

### Expected behavior

I want to use this model for Google AI, but not able to access it

**Comment by nyck33** [comment]
same problem trying to run  code on https://python.langchain.com/docs/integrations/llms/google_ai
```
google-ai-generativelanguage 0.4.0                    pypi_0    pypi
google-api-core           2.15.0                   pypi_0    pypi
google-auth               2.23.4                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
google-generativeai       0.3.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.62.0                   pypi_0    pypi
langchain-google-genai    0.0.4                    pypi_0    pypi
```
are in my conda env.

**Comment by lkuligin** [comment]
Please, try to import 
`from langchain_google_genai import ChatGoogleGenerativeAI`

or you need to install `langchain-google-genai` from github if you need a LLM (not a ChatModel) since it looks like the recent changes has not been released yet

**Comment by hinthornw** [comment]
Hi folks, thanks for your patience! Looks like we didn't cut the release before the docs were published. It should be present in 0.0.5

**Comment by mskovalova** [comment]
Hi. I have the same problem. Any suggestions?
