### ISSUE TITLE
Difference between the different search APIs

### ISSUE THREAD

**Issue by Syzygianinfern0** [langchain-ai/langchain#1476]
Whats the difference between using 
- https://langchain.readthedocs.io/en/latest/modules/utils/examples/google_search.html
- https://langchain.readthedocs.io/en/latest/modules/utils/examples/google_serper.html
- https://langchain.readthedocs.io/en/latest/modules/utils/examples/searx_search.html
- https://langchain.readthedocs.io/en/latest/modules/utils/examples/serpapi.html

for Google Search?

**Comment by gwc4github** [comment]
For the two Google searches, It looks like Serper is made for API access so should be easier to use and less expensive.
