### ISSUE TITLE
MiniMaxChat：AttributeError: 'str' object has no attribute 'generations'

### ISSUE THREAD

**Issue by jmaxzh** [langchain-ai/langchain#14796]
### System Info

Macos

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
# -*- coding: utf-8 -*-
from langchain.chat_models import MiniMaxChat
from langchain.schema import HumanMessage


if __name__ == "__main__":
    minimax = MiniMaxChat(
        model="abab5.5-chat",
        minimax_api_key="****",
        minimax_group_id="***",
    )

    resp = minimax(
        [
            HumanMessage(content="hello"),
        ]
    )
    print(resp)

```

error info
```base
Traceback (most recent call last):
  File "***", line 17, in <module>
    resp = minimax(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 634, in __call__
    generation = self.generate(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 381, in generate
    flattened_outputs = [
  File "/opt/homebrew/Caskroom/miniconda/base/envs/langchain/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 382, in <listcomp>
    LLMResult(generations=[res.generations], llm_output=res.llm_output)
AttributeError: 'str' object has no attribute 'generations'
```

### Expected behavior

no error

**Comment by keenborder786** [comment]
```python

# -*- coding: utf-8 -*-
from langchain.chat_models import MiniMaxChat
from langchain.schema import HumanMessage


if __name__ == "__main__":
    minimax = MiniMaxChat(
        model="abab5.5-chat",
        minimax_api_key="****",
        minimax_group_id="***",
    )

    resp = minimax(
        messages = [
            HumanMessage(content="hello"),
        ]
    )
    print(resp)

```

**Comment by keenborder786** [comment]
Try this.

**Comment by KirisameR** [comment]
> Try this.

The above code produced the same error. When inspecting the "results" variable's value (as shown in line 384-386 of the following screenshot), we can find the exact output of the model.

<img width="652" alt="image" src="https://github.com/langchain-ai/langchain/assets/60131395/73fa70fc-a7a1-4320-946a-3d498b698ff6">

 However, the type of the output is clearly "str" instead of 'ChatResult' type.

<img width="1029" alt="image" src="https://github.com/langchain-ai/langchain/assets/60131395/05d9689b-2852-41b5-b4e3-26905dcb0ed5">
