### ISSUE TITLE
ModuleNotFound error in using UnstructuredRSTLoader

### ISSUE THREAD

**Issue by maxscott** [langchain-ai/langchain#14801]
#### Virtualenv
Python:         3.11.6
Implementation: CPython
Path:           /Users/max/Library/Caches/pypoetry/virtualenvs/qa-oj4cEcx_-py3.11
Executable:     /Users/max/Library/Caches/pypoetry/virtualenvs/qa-oj4cEcx_-py3.11/bin/python
Valid:          True

#### System
Platform:   darwin
OS:         posix
Python:     3.11.6
Path:       /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11
Executable: /usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/bin/python3.11

### Who can help?

@eyurtsev @baskaryan (https://github.com/langchain-ai/langchain/pull/14463)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain_community.document_loaders import UnstructuredRSTLoader
loader = UnstructuredRSTLoader("example.rst", mode="elements", strategy="fast")
docs = loader.load()
```
In this case, "example.rst" is the downloaded rst from the lanchain source itself.

### Expected behavior

I would expect the document loader to result in a list of documents. Instead there is an error in referencing a module:

```
  File ".../virtualenvs/qa-oj4cEcx_-py3.11/lib/python3.11/site-packages/langchain_community/document_loaders/unstructured.py", line 14, in satisfies_min_unstructured_version
    from unstructured.__version__ import __version__ as __unstructured_version__
ModuleNotFoundError: No module named 'unstructured'
```

**Comment by keenborder786** [comment]
Make to sure to run the following two commands:

```bash
pip install "unstructured[all-docs]"
pip install pypandoc_binary
```

**Comment by keenborder786** [comment]
Hopefully this will resolve your error.

**Comment by maxscott** [comment]
Aha, I didn't realize "unstructured" was a 3p lib—I thought it was just a broken reference in the project or something.
Thank you!

**Comment by bit-scientist** [comment]
For those who are struggling to get it to work even after installing above, give a try to: `pip install "langchain-unstructured[local]"`
I came across to this error while following [langchain unstructured](https://python.langchain.com/docs/integrations/providers/unstructured/) where I ran `from langchain_unstructured import UnstructuredLoader`
