### ISSUE TITLE
Missing "Prompt" in Together ai

### ISSUE THREAD

**Issue by aadityamundhalia** [langchain-ai/langchain#14813]
### System Info

In this file: https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/llms/together.py

There is no variable Prompt, however it is available in the documentation: https://docs.together.ai/reference/inference

```python
if config.model == "together":
            return Together(
                    model="togethercomputer/StripedHyena-Nous-7B",
                    temperature=0.7,
                    max_tokens=128,
                    top_k=1,
                    together_api_key=config.together_api_key,
                    prompt="The capital of France is"
                )
```

error I get is:
```bash
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Together
prompt
  extra fields not permitted (type=value_error.extra)
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Try to run together Ai model and pass Prompt on model it will fail. My goal is to set a system Prompt.

### Expected behavior

Accept Prompt as the system Prompt.

**Comment by Yossef-Dawoad** [comment]
the rest of the request parameters in the inference docs can be passed with `LLM.call(..., **kwargs)`
that is why you can pass the `prompt`, list of `stop` keywords,...etc like this :
```python 

llm = Together(
    model="togethercomputer/StripedHyena-Nous-7B",
    temperature=0.1,
    top_k=50,
    max_tokens=512,
    together_api_key="25fe16e65b1763d168fd0b0e1f1a6da7bd01ed7c681ff49b658886f0e5578e58",
)

# llm call with the prompt
output = llm(prompt, stop=["[/INST]", "</s>", "##"])
```

**Comment by aigeek0x0** [comment]
> the rest of the request parameters in the inference docs can be passed with `LLM.call(..., **kwargs)` that is why you can pass the `prompt`, list of `stop` keywords,...etc like this :
> 
> ```python
> llm = Together(
>     model="togethercomputer/StripedHyena-Nous-7B",
>     temperature=0.1,
>     top_k=50,
>     max_tokens=512,
>     together_api_key="25fe16e65b1763d168fd0b0e1f1a6da7bd01ed7c681ff49b658886f0e5578e58",
> )
> 
> # llm call with the prompt
> output = llm(prompt, stop=["[/INST]", "</s>", "##"])
> ```

I think you forgot to delete that key.

**Comment by Yossef-Dawoad** [comment]
yeah, I think I did, and headed back to revoke it but I can see no option to turn it off or generate a new one,
 I edited my comment can you delete your comment @aigeek0x0 because it still shows it, at least until I try to revoke it
