### ISSUE TITLE
Gemini with ConversationalRetrievalChain

### ISSUE THREAD

**Issue by gpy1234** [langchain-ai/langchain#14819]
### Issue you'd like to raise.

Is there a similar method for using `gemini-pro` with `ConversationalRetrievalChain.from_llm`, as there is for utilizing models from VertexAI with `ChatVertexAI` or `VertexAI`, where you specify the `model_name`?

**Comment by lkuligin** [comment]
You can use gemini with `VertexAI` or `ChatVertexAI` by providing `model_name="gemini-pro"` argument during initialization.
