### ISSUE TITLE
When using the OpenAIFunctionsAgentOutputParser() to parse agent output meet an error.

### ISSUE THREAD

**Issue by 100sunnygirl** [langchain-ai/langchain#14816]

**Comment by qhNana7mi** [comment]
> _🤖_
> 
> Hello @qhNana7mi! I'm [Dosu](https://dosu.dev), a friendly bot here to assist you with bugs, answer your questions, and guide you in contributing to LangChain. While you're waiting for a human maintainer, feel free to ask me anything. Looking forward to helping you!
> 
> Based on the information provided, it seems like the error you're encountering is due to a change in the type of message returned by the ChatGeneration output in LangChain version 0.0.350. The OpenAIFunctionsAgentOutputParser()._parse_ai_message() method expects an instance of AIMessage but it received an instance of ChatMessage. This could be due to the update where the type of message returned might have changed.
> 
> Here is the relevant code causing the error:
> 
> ```python
> def _parse_ai_message(message: BaseMessage) -> Union[AgentAction, AgentFinish]:
>     """Parse an AI message."""
>     if not isinstance(message, AIMessage):
>         raise TypeError(f"Expected an AI message got {type(message)}")
> ```
> 
> (Source: [libs/langchain/langchain/agents/output_parsers/openai_functions.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/output_parsers/openai_functions.py))
> 
> To resolve this issue, you might need to update the _parse_ai_message() method to accept ChatMessage instances or ensure that the message returned by the ChatGeneration output is an AIMessage instance.
> 
> There are similar issues that have been resolved in the LangChain repository, such as [The agent run output parser cause error when run a simple quick start](https://github.com/langchain-ai/langchain/issues/7116). The suggested solution in these issues is to refer to the article on how to handle parsing errors in LangChain. The link to the article is: https://python.langchain.com/docs/modules/agents/how_to/handle_parsing_errors
> 
> Please let me know if this helps or if you need further assistance.
> 
> ## Sources
> * [The agent run output parser cause error when run a simple quick start](https://github.com/langchain-ai/langchain/issues/7116)
> * [libs/langchain/langchain/agents/output_parsers/openai_functions.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/agents/output_parsers/openai_functions.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.


Why I get a ChatMessage rather that an AIMessage? I never met this error in my agent before I update my langchain version.
