### ISSUE TITLE
PostgresChatHistory or any other database for storing history does not work with ConversationSummaryBufferMemory(or other memory taht produces 'system' massage type after summarisation

### ISSUE THREAD

**Issue by Vanekkk1** [langchain-ai/langchain#14822]
### System Info

mac os latest, latest LangChain

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [x] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

ConversationBufferWindowMemory(
            chat_memory=PostgresChatMessageHistory(
        session_id=session_id, connection_string=os.getenv("DB_URL")
    ),
            return_messages=True,
            memory_key=memory_key,
        )
  try to run a chat with this

### Expected behavior

I think it should save the massages as they are to SQL, but use the properties of the ConversationSummaryBufferMemory for the chat itself, but it reality it just uses SQL and history is jus tall the massages

**Comment by keenborder786** [comment]
Please make your instruction more verbose and clear. Otherwise it is too difficult to provide you with help.

**Comment by Vanekkk1** [comment]
So PostgresChatMessageHistory saves each message (only human and AI ones). I am trying to use it like this:

ConversationSummaryBufferMemory(
            chat_memory=PostgresChatMessageHistory(
        session_id=session_id, connection_string=os.getenv("DB_URL")
    ),
            return_messages=True,
            llm=llm,
            max_token_limit=2000,
            memory_key=memory_key,
        )

I would want the following behaviour. the maximum length of the chat_history should be 2000 as mentioned in max_token_limit=2000, during the conversation the history should be summarised when it reaches 2000, which is the behaviour of ConversationSummaryBufferMemory class, however, what actually happens is that history increases far beyond 2000, in fact it does not stop until it throws an error that history is longer than allowed in LLM context window, because each time history gets retrieved in raw format from Postgres, how would you suggest to tackle this, I wanna be able to get full chat history be session_id but also for the specific chat I want the memory to work as the underlying class implies, thanks !

**Comment by Vanekkk1** [comment]
Can I even combine them like this? In general how would you suggest to approach memory in production RAG applications?

**Comment by keenborder786** [comment]
I still do not understand what you exactly are asking for but the way `**ConversationSummaryBufferMemory**` work is as follow:
     - First it will load the **past conversation history** for the given session_id from the PostgreSQL
     - Once Past Conversation History is Loaded, then it is pruned to max token length of 2000.
     - After that a summary is created through LLM with the pruned message + the previous summary that was created.
    
  Let me know if this makes sense to you.

**Comment by Vanekkk1** [comment]
It does not work like this, it loads from PostgreS and then staffs all the loaded history to the condense question prompt, so it gets bigger and bigger, the functionality of Memory object itself is not applied at all

Best regards,
Ivan Tryskyba

**Comment by keenborder786** [comment]
@Vanekkk1 Nope, the memory functionality is applied when ConversationSummaryBufferMemory Loads memory from Postgres and prunes the loaded conversation + when it uses the llm to predict the next memory buffer using these loaded pruned messages & previous predicted buffer. I am sure of it as I have double checked the source code.

**Comment by keenborder786** [comment]
Actually you are right. When it loads memory variables, it keep the entire buffer as it is along with the summarized buffer. Though you are wrong about  memory functionality, it is applied as it first prunes conversation from postgresSQL and then summarizes those prune conversation along with previous summary. But the problem is duing the loading of memory variables, their needs to be way where we can limit the size of buffer with goes with predicted summarized buffer,

```python

    def load_memory_variables(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """Return history buffer."""
        buffer = self.buffer
        if self.moving_summary_buffer != "":
            first_messages: List[BaseMessage] = [
                self.summary_message_cls(content=self.moving_summary_buffer)
            ]
            buffer = first_messages + buffer # This needs to be changed and limited which keeps on building the memory variables
        if self.return_messages:
            final_buffer: Any = buffer
        else:
            final_buffer = get_buffer_string(
                buffer, human_prefix=self.human_prefix, ai_prefix=self.ai_prefix
            )
        return {self.memory_key: final_buffer}


```

**Comment by keenborder786** [comment]
@Vanekkk1 I have created a PR to fix this issue. Please have a look.

**Comment by Vanekkk1** [comment]
@keenborder786 It also does not work with other memory classes as well, such as these three on the image attached. It just uses all the massages without applying their functionality.
![Screenshot 2023-12-21 at 11 53 45](https://github.com/langchain-ai/langchain/assets/91801007/93ba3ca4-40ee-45a9-b3f1-c90bac98afae)

**Comment by keenborder786** [comment]
okay let me see. I will try to fix the bug in the same PR.
