### ISSUE TITLE
Add an OpentelemetryTracer in LangChain

### ISSUE THREAD

**Issue by npuichigo** [langchain-ai/langchain#14832]
### Feature request

There's already many tracers in LangChain (https://github.com/langchain-ai/langchain/tree/master/libs/langchain/langchain/callbacks/tracers).
I would like to ask for adding an OpentelemetryTracer.

### Motivation

Community tracing

### Your contribution

Would like to contribute

**Comment by debdhriti** [comment]
Hey, @npuichigo! Just found a solution to this in another related post: https://github.com/langchain-ai/langchain/issues/14594#issuecomment-1851951445 . Also noticed it doesn't use LangSmith, is this sufficient or, if not, could you point to some resources/repo code incase improvements are required?

**Comment by npuichigo** [comment]
@debdhriti I'm not sure the robot answer actually works. My point of view is that since we support wandb in addition to LangSmith, opentelemetry as a widely used community tracing component should be supported as well. So it's convenient for LangChain user to integrate with ZipKin/Jaeger/Grafana for telemetry.

**Comment by matthewgrossman** [comment]
I'm also interested in an opentelemetry tracing adapter for langchain. Happy to take a swing at the PR, likely will create another file in `langchain_community/callbacks/tracers/opentelemetry.py`

**Comment by timvw** [comment]
At [openinference](https://github.com/Arize-ai/openinference/tree/main/python/instrumentation/openinference-instrumentation-langchain) they have such OTEL (+ llm extension) instrumentation.. Works pretty neat..

**Comment by codefromthecrypt** [comment]
fyi there's a discussion I think if moved forward could ease some trouble-spots of tracing langchain. If any contributors have time to pipe in, much obliged! https://github.com/langchain-ai/langchain/discussions/27954
