### ISSUE TITLE
Async PGVector to make LangChain with Postgres more performant

### ISSUE THREAD

**Issue by Coding-Crashkurse** [langchain-ai/langchain#14836]
### Feature request

Currently we use PGVector as our Vector Database and do in combination with FastAPI. One issue is that in the indexing process, which happens over an API Endpoint, we found out that the current implementation of PgVector is blocking due to its synchronous implementation. FastAPI offers async/await and SQLAlchemy also allows using async sessions. I would like to add an Async Alternative for PGVector. 

### Motivation

Non-Blocking code execution prevents blocking the main thread of our execution and provides far superior performance compared to synchronous execution

### Your contribution

I already coded a prototype, which works so far and does not block the main thread of the API. I would fully implement this async solution. Currently I only have to discuss this with my boss, since I did this during worktime.

**Comment by danny-avila** [comment]
@Coding-Crashkurse any updates on this?

**Comment by danny-avila** [comment]
> @danny-avila : I froze implementing this, due to the addition of "run_in_executor" of the LangChain team. This solved the issue with the blocked main thread, but to be honest I will would like to make it async natively. But currently no time for that.

I see, thanks! Do you have any examples of using the Indexing API with PGVector asynchronously?

**Comment by pprados** [comment]
With a FastAPI, I need to expose a 'load()' method, to import data in the pgvector, with `index()` (and RecordManager, SQLDocStore, etc). I have a lot of documents, and it can take several tens of seconds.

**Comment by pprados** [comment]
I propose a [PR](https://github.com/langchain-ai/langchain-postgres/pull/32) for that

**Comment by RoQuasar** [comment]
@Coding-Crashkurse Can you give an example on how you used run_in_executor? If i use the driver asyncpg i always get this error: There is no current event loop in thread 'asyncio_0'.

**Comment by KD-TrendOn** [comment]
As you can see now, an asynchronous implementation has been added to langchain-postgres pgvector

**Comment by davidtheITguy** [comment]
Can you please point to this feature? I don't see it and all my attempts to use pgvector with either asyncpg or psycoppg2 in async mode fail.

**Comment by RoQuasar** [comment]
Try with "psycopg" (with no number)

**Comment by davidtheITguy** [comment]
Thank you will do


———————
David Eisner
240.994.5900
________________________________
