### ISSUE TITLE
safety_settings argument is missing with the ChatVertexAI mode

### ISSUE THREAD

**Issue by JamesLloydPartingtonSerendipityai** [langchain-ai/langchain#14841]
### Issue you'd like to raise.

safety_settings argument is missing with the `ChatVertexAI` model

### Suggestion:

Should be able to define the safety settings. For example:

```
safety_settings = {
  HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
  HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
  HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
  HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
}

llm = ChatVertexAI(safety_settings=safety_settings)
```

**Comment by HoussemDjeghri** [comment]
@blackslashcreative where you able to find a solution to the error, I'm facing the same error.

**Comment by blackslashcreative** [comment]
Unfortunately, no. No solution yet, I am using Gemini without langchain
until there’s a way to use safety settings properly through langchain…

Ross ("Ghosty") - Black Slash Creative

**Comment by HoussemDjeghri** [comment]
@blackslashcreative in my case I found the solution finaly, I turned out I was importing from the wrong package, here is the correct import
!pip install -q langchain_google_vertexai
 from langchain_google_vertexai import HarmCategory, HarmBlockThreshold

**Comment by blackslashcreative** [comment]
@HoussemDjeghri Are you not initiating a chat then? I was using ChatVertexAI because it's a chat scenario. If I switch that to VertexAI I'm not sure... I would love to see some of your code where the safety_settings are implemented if you don't mind sharing! This has been driving me crazy 🥴

**Comment by HoussemDjeghri** [comment]
@blackslashcreative, I was using `ChatVertexAI` at first but it didn't play well with `safety_settings` so I tried `VertexAI` and it worked. Here is the code that I used to use VertexAi as chat:
```
from langchain_google_vertexai import VertexAI, HarmCategory, HarmBlockThreshold
from google.colab import auth as google_auth
google_auth.authenticate_user()
import vertexai

PROJECT_ID = "project ID"
safety_settings = {
                HarmCategory.HARM_CATEGORY_UNSPECIFIED: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_ONLY_HIGH,
}
vertexai.init(project=PROJECT_ID)
chat = VertexAI(model_name="gemini-pro",
                    max_output_tokens=2048,
                    safety_settings=safety_settings
                    )
conversation = ConversationChain(llm=chat)


prompt1= """
Your MESSAGE 
"""

conversation.run(prompt1)
```

**Comment by blackslashcreative** [comment]
Gah, thank you for this, unfortunately I'm still getting KeyError:
'safety_settings'
:( :( :(

**Comment by kssua** [comment]
Sorry for my cut in.
I have same issue and can solve with below.

The problem may be that Langchain Official DOC dict format of safety_settings doesn't match the format of Vertex AI.
As per checking Google Official DOC, HarmCategory should be picked from **generative_models** from vertexai.

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/configure-safety-attributes?hl=ja

Please try below code.

from langchain_google_vertexai import ChatVertexAI
from langchain_google_vertexai import VertexAI, HarmCategory, HarmBlockThreshold
**from vertexai import generative_models**

safety_settings = {
    **generative_models**.HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
    **generative_models**.HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
    **generative_models**.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
    **generative_models**.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
}

**Comment by blackslashcreative** [comment]
@kssua thanks for sending this, unfortunately when I try that, it gives me: 
AttributeError: module 'vertexai.generative_models' has no attribute 'HarmCategory'

**Comment by kssua** [comment]
@blackslashcreative 

Kindly try below full code and whether same error happens.

Environment : Google Colaboratory



%%writefile requirements.txt
langchain==0.1.13
langchain-google-vertexai==0.1.2


%pip install -r requirements.txt


from langchain_google_vertexai import ChatVertexAI
from langchain_google_vertexai import VertexAI, HarmCategory, HarmBlockThreshold
from google.colab import auth as google_auth
google_auth.authenticate_user()
import vertexai
from vertexai import generative_models

PROJECT_ID = "Input your Coogle Cloud Project ID"

safety_settings = {
generative_models.HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
generative_models.HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
generative_models.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
generative_models.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
}

vertexai.init(project=PROJECT_ID)
chat = ChatVertexAI(model_name="gemini-pro",
                    max_output_tokens=2048,
                    safety_settings=safety_settings
                    )

message = chat.invoke("Teach me population of New York city.")
print(message.content)
