### ISSUE TITLE
Update 'add_texts' to create embeddings in batches

### ISSUE THREAD

**Issue by Rifur13** [langchain-ai/langchain#1486]
Pinecone currently creates embeddings serially when calling `add_texts`. It's slow and unnecessary because all embeddings classes have a `from_documents` method that creates them in batches. If no one is working on this I can create a PR, please let me know!

**Comment by racinger** [comment]
Hi, I would really like this update to speed it up, it is currently very slow. Happy to help too.

**Comment by jeanmw** [comment]
Hi! would also love this feature
