### ISSUE TITLE
(ChatLiteLLM - Together AI) AttributeError: 'ValueError' object has no attribute 'status_code'

### ISSUE THREAD

**Issue by ivandorte** [langchain-ai/langchain#14863]
### System Info

platform: Vagrant - Ubuntu 2204
python: 3.9.18
langchain: 0.0.350
langchain-core: 0.1.1
langchain-community: 0.0.3
litellm: 1.15.1

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Run the code:
``` python
from langchain.chat_models import ChatLiteLLM
from langchain.schema import HumanMessage

# Initialize ChatLiteLLM
chat = ChatLiteLLM(
    model="together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1",
    verbose=True,
    temperature=0.0,
)

text = "Write me a poem about the blue sky"
messages = [HumanMessage(content=text)]

print(chat(messages).content)
```

2: Error message:

``` bash
AttributeError: 'ValueError' object has no attribute 'status_code'
``` 

### Expected behavior

I can't get ChatLiteLLM to work with Together AI. I expect **ChatLiteLLM** to work correctly and to output the result.

**Comment by navicstein** [comment]
Having this issue too

i ended up using togetherai from langchain directly


```python
from langchain_community.llms.together import Together

llm = Together(
   model="mistralai/Mistral-7B-Instruct-v0.2",
   temperature=0.7,
   top_k=1,
)
```
