### ISSUE TITLE
gRPC index support for Pinecone

### ISSUE THREAD

**Issue by fuushyn** [langchain-ai/langchain#1488]
gRPC context : https://docs.pinecone.io/docs/performance-tuning

Presently, the method to initialize a Pinecone vectorstore from an existing index is as follows - 

`
index = pinecone.Index(index_name)`
`docsearch = Pinecone(index, hypothetical_embeddings.embed_query, 'text')`

gRPC offers performance enhancements, so we'd like to have support for it as follows - 

`
index = pinecone.GRPCIndex(index_name)`
`docsearch = Pinecone(index, hypothetical_embeddings.embed_query, 'text')
`

Apparently GRPCIndex is a different type from Index

> ValueError: client should be an instance of pinecone.index.Index, got <class 'pinecone.core.grpc.index_grpc.GRPCIndex'>

**Comment by ales29** [comment]
I have the same problem.

**Comment by lironezra** [comment]
I have also same problem

**Comment by LarryStewart2022** [comment]
pip3 install pinecone-client[grpc]

**Comment by AkshiMehra** [comment]
pip3 uninstall pinecone-client
pip3 install -U "pinecone-client[grpc]"

**Comment by XariZaru** [comment]
Following up on an issue with the current approach. Pinecone automatically converts metadata text to datetime objects if it is possible. This behavior is often more harmful than good. 

Pinecone forums recommend a GRPPCIndex implementation instead of the Index if we don't want a conversion issue.

@dosu-bot

**Comment by mmorzywolek** [comment]
@XariZaru Yes, but still when instantiating vectorestore with GRPCIndex there is still an error 
`ValueError: client should be an instance of pinecone.index.Index, got <class 'pinecone.core.grpc.index_grpc.GRPCIndex'>`

**Comment by javimp2003uma** [comment]
> [@XariZaru](https://github.com/XariZaru) Yes, but still when instantiating vectorestore with GRPCIndex there is still an error `ValueError: client should be an instance of pinecone.index.Index, got <class 'pinecone.core.grpc.index_grpc.GRPCIndex'>`

Did you solve it? I have the same problem
