### ISSUE TITLE
AIORpcError connection reset errors from Qdrant

### ISSUE THREAD

**Issue by orgroman** [langchain-ai/langchain#14891]
### System Info

Python:3.11-slim-bullseye base docker image
Langchain version: 0.0.348
qdrant-client: 1.7.0
Qdrant database 1.7.1 (deployed on AWS cluster)
Reproduces regardless of prefer grpc true or false

### Who can help?

@agola11 @hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

1. Use ConversationalRetrievalChain with Qdrant vectordb
2. Use async acall interface
3. Maybe wait some idle time (15 min?)

You will experience a lot of errors from Qdrant:
AioRpcError of RPC that terminated with: status = StatusCode.UNAVAILABLE details = "recvmsg:Connection reset by peer" debug_error_string = "UNKNOWN:Error received from peer {created_time}" >, type: AioRpcError

It's ok after retry of the request but this causes significant delay in response

### Expected behavior

Connection recovery for the vectordb should be handled by LangChain internally and ideally understand what causes the connection issues and resolve it

**Comment by orgroman** [comment]
@dosu-bot Response isn't handled properly as I except the connection to be recovered if needed automatically by LangChain and also inspect the source of the connection issues

**Comment by baskaryan** [comment]
cc @kacperlukawski any idea what's going on here?

**Comment by Anush008** [comment]
Hey @orgroman. Can we get some code snippets of Qdrant's instantiation or calls that you're performing, which could help reproduce this issue?
