### ISSUE TITLE
`convert_to_openai_function` drops `description` for each parameter

### ISSUE THREAD

**Issue by okapies** [langchain-ai/langchain#14899]
### System Info

The `description` attribute of the function parameters described in our Pydantic *v2* model are missing in the output of `convert_to_openai_function` because it does not recognize Pydantic v2 `BaseModel` as a valid v1 `BaseModel`.

https://github.com/langchain-ai/langchain/blob/16399fd61d7744c529cca46464489e467b4b7741/libs/langchain/langchain/chains/openai_functions/base.py#L156-L161

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.chains.openai_functions.base import convert_to_openai_function
from pydantic.v1 import BaseModel as BaseModelV1, Field as FieldV1
from pydantic import BaseModel as BaseModelV2, Field as FieldV2


class FuncV1(BaseModelV1):
  "Pydantic v1 model."
  output: str = FieldV1(description="A output text")


class FuncV2(BaseModelV2):
  "Pydantic v2 model."
  output: str = FieldV2(description="A output text")

print(convert_to_openai_function(FuncV1))
{'name': 'FuncV1', 'description': 'Pydantic v1 model.', 'parameters': {'title': 'FuncV1', 'description': 'Pydantic v1 model.', 'type': 'object', 'properties': {'output': {'title': 'Output', 'description': 'A output text', 'type': 'string'}}, 'required': ['output']}}

print(convert_to_openai_function(FuncV2))
{'name': 'FuncV2', 'description': 'Pydantic v2 model.', 'parameters': {'type': 'object', 'properties': {'output': {'type': 'string'}}, 'required': ['output']}}
```

### Expected behavior

Add `description` attribute appeared in Pydantic v2 model.

**Comment by jeremy886** [comment]
I think this is a similar problem.

I'm running this notebook https://github.com/Ryota-Kawamura/Functions-Tools-and-Agents-with-LangChain/blob/main/L4-tagging-and-extraction-student.ipynb

If you scrolled down the example at the bottom (extracting titles and authors), only authors will be extracted. I'm using: `convert_to_openai_function` instead of `convert_pydantic_to_openai_function` (but same results when I tested both)
from langchain_core.utils.function_calling import convert_to_openai_function

convert_to_openai_function(Info) outputs:
```json
{'name': 'Info',
 'description': 'Information to extract',
 'parameters': {'type': 'object',
  'properties': {'papers': {'type': 'array',
    'items': {'description': 'Information about papers mentioned.',
     'type': 'object',
     'properties': {'author': {'type': 'string'}},
     'required': ['title']}}},
  'required': ['papers']}}
```

If I edited the output as:
```json
openai_function_manual = {
    "name": "Info",
    "description": "Information to extract",
    "parameters": {
        "type": "object",
        "properties": {
            "papers": {
                "type": "array",
                "items": {
                    "description": "Information about papers mentioned.",
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "author": {"type": "string"},
                    },
                    "required": ["title", "author"],
                },
            }
        },
        "required": ["papers"],
    },
}
```

then the results will be correct with both titles and authors. here is the new notebook: https://github.com/jeremy886/LearnLangChain24/blob/main/L4-tagging-and-extraction-student.ipynb

**Comment by gladwig2** [comment]
agree.

convert_pydantic_to_openai_function(Tagging)
would include the descriptions. If you use this, you get a deprecation warning and are advised to use

convert_pydantic_to_openai_function(Tagging)
this does not include per field descriptons


convert_pydantic_to_openai_function(Tagging) output
```
{'name': 'Tagging',
 'description': 'Tag the piece of text with particular info.',
 'parameters': {'type': 'object',
  'properties': {'sentiment': {'type': 'string'},
   'technical_issue': {'type': 'string'},
   'instruction_issue': {'type': 'string'}},
  'required': ['sentiment', 'technical_issue', 'instruction_issue']}}
```

while
convert_pydantic_to_openai_function(Tagging) output is:
```
{'name': 'Tagging',
 'description': 'Tag the piece of text with particular info.',
 'parameters': {'properties': {'sentiment': {'description': 'sentiment of text, importantly should be one of exactly  `pos`, `neg`, or `neutral` only',
    'type': 'string'},
   'technical_issue': {'description': "If the text describes a technical problem or suggestion, include a summary of the issue in this field otherwise 'none' ",
    'type': 'string'},
   'instruction_issue': {'descrption': "If the text describes an instruction problem with the course, include a summary of the issue in this fieled, otherwise 'none'",
    'type': 'string'}},
  'required': ['sentiment', 'technical_issue', 'instruction_issue'],
  'type': 'object'}}

```

**Comment by baskaryan** [comment]
all langchain methods working with pydantic objects expect them to be instantiated using `langchain_core.pydantic_v1` instead of bare `pydantic`. This is so that we can support pydantic v1 and v2.

when defining a pydantic object you should do so with 
```python
from langchain_core.pydantic_v1 import BaseModel, Field


class Func(BaseModel):
  output: str = Field(description="A output text")
```

**Comment by baskaryan** [comment]
See here for more on [pydantic compatibility](https://python.langchain.com/docs/guides/pydantic_compatibility)

**Comment by okapies** [comment]
IMO the document should say _"pydantic v2 is incompatible with the current langchain."_ if you don't fix it at the moment.

**Comment by baskaryan** [comment]
> IMO the document should say _"pydantic v2 is incompatible with the current langchain"_ if you don't fix it at the moment.

that suggests you can't have pydantic v2 installed, which isn't the case. we do say "Internally LangChain will continue to [use V1](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features)" but we could make that more prominent, maybe move it to the top?

**Comment by okapies** [comment]
> As of `langchain>=0.0.267`, LangChain will allow users to install either Pydantic V1 or V2. 

Pydantic V2 is not supported yet, so this statement is misleading.

**Comment by baskaryan** [comment]
> > As of `langchain>=0.0.267`, LangChain will allow users to install either Pydantic V1 or V2.
> 
> Pydantic V2 is not supported yet, so this statement is misleading.

What do you mean by "Pydantic V2 is not supported"? To me that means you can't have it installed, which isn't the case. Perhaps would be more precise to say "Full Pydantic V2 functionality is not supported"?
