### ISSUE TITLE
How to embed the table data?

### ISSUE THREAD

**Issue by GoldenDragon0710** [langchain-ai/langchain#14911]
### Issue you'd like to raise.

I have a document, which contains general text and tables.
I embedded this document using LangChain to build a bot with Node.js.
The bot answers correctly for general text in the document, but gives incorrect answers for table data.
How do I update?

**Comment by hynky1999** [comment]
This is not really a question for langchain package.
Anyways when dealing with tables good idea is to create a chunk from each row of the table. Then add relevant chunks based on the query.

Not it's a bit harder to detect a table but https://github.com/Unstructured-IO/unstructured does pretty good job at that.
