### ISSUE TITLE
Issue: how to deploy gpt-4-turbo through langchain

### ISSUE THREAD

**Issue by Feya** [langchain-ai/langchain#14945]
### Issue you'd like to raise.

Hi, I can't find from how to deploy gpt-4-turbo in langchain. 
Could anyone please tell me throuhg which module gpt-4-turbo can be deployed? 
Seems that the langchain.llm has already been removed from new version of langchain.

**Comment by hinthornw** [comment]
```
from langchain_community.chat_models import ChatOpenAI(model="gpt-4-1106-preview")
```

**Comment by Pratikreddy** [comment]
from langchain_community.chat_models import ChatOpenAI
os.environ["OPENAI_API_KEY"] = ""
llm = ChatOpenAI(model="gpt-4-1106-preview")

yepp this 1 works 

the langchain documentation is getting a little messy lol
