### ISSUE TITLE
openai migrate

### ISSUE THREAD

**Issue by CalvinHMX** [langchain-ai/langchain#14946]
### System Info

loader1 = CSVLoader(file_path='/home/calvin/下载/test.csv')
Doc = loader1.load()
text_splitter = CharacterTextSplitter(chunk_size=100,chunk_overlap=0)
texts = text_splitter.split_documents(Doc)
embeddings = OpenAIEmbeddings()
db = Chroma.from_documents(texts, embeddings)
retriever = db.as_retriever()
qa = RetrievalQA.from_chain_type(llm=OpenAI(mode="gpt-3.5-turbo"), chain_type="stuff", retriever=retriever)
query = "1501475820"
print(qa.run(query))

I run this code,but i can not use chat-gpt-3.5-turbo，so i try to opanAI MIGRATE，but i exit it ,then i found 
![Screenshot_20231220_160320](https://github.com/langchain-ai/langchain/assets/108516348/cc3574ce-5fe8-4f10-bace-070ae4d41727)

then  always  tell me 
![Screenshot_20231220_160734](https://github.com/langchain-ai/langchain/assets/108516348/4f7b2e29-fb59-4c65-819b-a85f991b4f66)

@hwcha

### Who can help?

from langchain.chains import RetrievalQA

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

loader1 = CSVLoader(file_path='/home/calvin/下载/test.csv')
Doc = loader1.load()
text_splitter = CharacterTextSplitter(chunk_size=100,chunk_overlap=0)
texts = text_splitter.split_documents(Doc)
embeddings = OpenAIEmbeddings()
db = Chroma.from_documents(texts, embeddings)
retriever = db.as_retriever()
qa = RetrievalQA.from_chain_type(llm=OpenAI(mode="gpt-3.5-turbo"), chain_type="stuff", retriever=retriever)
query = "1501475820"
print(qa.run(query))

### Expected behavior

i want use gpt-3.5-turbo to query

**Comment by keenborder786** [comment]
Please make your code cleaner.
