### ISSUE TITLE
Embedding Function not properly passed to Chroma Collection

### ISSUE THREAD

**Issue by KMontag42** [langchain-ai/langchain#1494]
https://discord.com/channels/1038097195422978059/1038097349660135474/1082685778582310942

details are in the discord thread.

the code change [here](https://github.com/chroma-core/chroma/commit/aa2d006e4e93f8d5c4ebe73e0373d0dea6d1e83b) changed how chroma handles embedding functions and it seems like ours is being sent as None for some reason.

**Comment by keviddles** [comment]
Seeing this too. Version `0.0.102`.

Code: ```from langchain.document_loaders import TextLoader
from langchain.embeddings import TensorflowHubEmbeddings
loader = TextLoader('./state_of_the_union.txt')
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

embeddings = TensorflowHubEmbeddings()
docsearch = Chroma.from_documents(texts, embeddings)
```

Error:
```
File /usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py:67, in Chroma.__init__(self, collection_name, embedding_function, persist_directory)
     62     logger.warning(
     63         f"Collection {collection_name} already exists,"
     64         " Do you have the right embedding function?"
     65     )
     66 else:
---> 67     self._collection = self._client.create_collection(
     68         name=collection_name,
     69         embedding_function=self._embedding_function.embed_documents
     70         if self._embedding_function is not None
     71         else None,
     72     )

TypeError: LocalAPI.create_collection() got an unexpected keyword argument 'embedding_function'
```

**Comment by timothyasp** [comment]
I believe this should fix it. https://github.com/hwchase17/langchain/pull/1444

**Comment by harithzulfaizal** [comment]
> I believe this should fix it. #1444

This works, thank you!

**Comment by timothyasp** [comment]
#1444 was merged in - is this resolved in 0.0.107

**Comment by sedgar03** [comment]
I still seem to be having this issue, has it been resolved?

**Comment by KMontag42** [comment]
I haven't seen this issue since the aforementioned merge commit.

**Comment by eWizardII** [comment]
I still get the same error.

```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-26-13b99c9bccce>](https://localhost:8080/#) in <cell line: 5>()
      3 text_field = "text"
      4 index = pinecone.Index(index_name)
----> 5 vectorstore = Pinecone(
      6     index=index,
      7     embedding_function=embed.embed_query,

TypeError: Pinecone.__init__() got an unexpected keyword argument 'embedding_function'
```

for this code

```
from langchain.vectorstores import Pinecone

text_field = "text"
index = pinecone.Index(index_name)
vectorstore = Pinecone(
    index=index, 
    embedding_function=embed.embed_query, 
    text_key=text_field)
query = "foo"
top = vectorstore.similarity_search(query, k=3)
```
