### ISSUE TITLE
Issue: Getting an error while trying to run LLMChain with Custom LLM

### ISSUE THREAD

**Issue by arunpurohit3799** [langchain-ai/langchain#14951]
I am trying to run the LLMChain using `llm_chain = LLMChain(llm=llm, prompt=prompt)`, where `llm` is a custom LLM defined based on https://python.langchain.com/docs/modules/model_io/llms/custom_llm, 

While trying to run this I am getting the following error: `Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, predict, predict_messages (type=type_error)`

Can someone help me with this?

**Comment by Israr** [comment]
+1. I encountered same issue.

Same code us running fine on a Mac OS, but giving problem with Linux/Ubuntu. Perhaps something to do with package versions.

**Comment by SuperPauly** [comment]
Same thing is happening to me but im using a Agent imported from `from langchain.agents import Agent`
