### ISSUE TITLE
Issue with DynamoDBChatMessageHistory Not Respecting max_token_limit in ConversationTokenBufferMemory

### ISSUE THREAD

**Issue by samuelbaruffi** [langchain-ai/langchain#14957]
### System Info

Langchain Version: langchain 0.0.350, langchain-community 0.0.3, langchain-core 0.1.1
Python Version: 3.10.6
Operating System: macOs
Additional Libraries: boto 2.49.0, boto3 1.34.1

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to Reproduce:
- Create an instance of `DynamoDBChatMessageHistory` with a specified table name and session ID.
- Initialize `ConversationTokenBufferMemory` with a `max_token_limit`.
- Attach the memory to a `ConversationChain`.
- Call predict on the `ConversationChain` with some input.

Code sample:
```
import boto3
from langchain.llms import Bedrock
from langchain.memory.chat_message_histories import DynamoDBChatMessageHistory
from langchain.memory import ConversationTokenBufferMemory

session = boto3.Session(
    aws_access_key_id=os.environ.get('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.environ.get('AWS_SECRET_ACCESS_KEY'),
    aws_session_token=os.environ.get('AWS_SESSION_TOKEN'),  
    region_name='us-east-1'
)

dynamodb = session.resource('dynamodb')
chat_sessions_table = dynamodb.Table('SessionTable')

boto3_bedrock = session.client(service_name="bedrock-runtime")

max_tokens_to_sample = 100
temperature = 0
modelId = "anthropic.claude-instant-v1"
top_k = 250
top_p = 0.999

model_kwargs = {
    "temperature": temperature,
    "max_tokens_to_sample": max_tokens_to_sample,
    "top_k": top_k,
    "top_p": top_p
}

llm = Bedrock(
    client=boto3_bedrock,
    model_id=modelId,
    region_name='us-east-1',
    model_kwargs=model_kwargs,
    streaming=True,callbacks=[StreamingStdOutCallbackHandler()]
    )

message_history = DynamoDBChatMessageHistory(table_name="SessionTable", session_id="10", boto3_session=session)

memory = ConversationTokenBufferMemory(
    llm=llm,  # Use the Bedrock instance
    max_token_limit=100,  
    return_messages=True,
    chat_memory=message_history,
    ai_prefix="A",
    human_prefix="H"
)

#add the memory to the Chain
conversation = ConversationChain(
    llm=llm, verbose=True, memory=memory
)

conversation.predict(input="Hello!")

memory.load_memory_variables({})
```

### Expected behavior

Expected Behavior:
- The `DynamoDBChatMessageHistory` should respect the `max_token_limit` set in `ConversationTokenBufferMemory`, limiting the token count accordingly.

Actual Behavior:
The `DynamoDBChatMessageHistory` does not limit the token count as per the `max_token_limit` set in `ConversationTokenBufferMemory` and keeps saving all the items in memory on the DynamoDB table.

**Comment by keenborder786** [comment]
@samuelbaruffi The `BaseChatMessageHistory` will store the entire conversation without pruning the Human and AI messages. At runtime, the `ConversationTokenBufferMemory` will retrieve messages from `BaseChatMessageHistory`, which, in your case, is DynamoDB. Subsequently, it will prune the messages to the specified token limit in the prompt. Essentially, Memory and Storage are distinct components in Langchain. Memory determines how to construct the past context, while storage actually preserves the entire conversation history. In this scenario, the `ConversationTokenBufferMemory` prunes the messages obtained from DynamoDB at runtime.

**Comment by samuelbaruffi** [comment]
@keenborder786 thanks for the answer. In my tests that does not seem to be the case. I've tested multiple times and my `Current conversation:` that is the history of the chat keeps increasing without any limit of the tokens I set. In my example I have set `max_token_limit=100` and I can see my history being set to the LLM as `Current conversation:` much bigger than 100 tokens. 

Let me know if I could help providing my test scenarios.

**Comment by 954-Ivory** [comment]
https://github.com/langchain-ai/langchain/blob/9e95699277fe0db3bfee1654276a43bfba9ecc64/libs/langchain/langchain/memory/token_buffer.py#L49-L59

The problem happens here:

https://github.com/langchain-ai/langchain/blob/9e95699277fe0db3bfee1654276a43bfba9ecc64/libs/langchain/langchain/memory/token_buffer.py#L58

`buffer` is just a `list` map from history storage.
`chat_memory : BaseChatMessageHistory` isn't implemented the `pop` method.

**Comment by samuelbaruffi** [comment]
Thank you @954-Ivory. So are you saying it's not possible to use `max_token_limit` with DynamoDB as memory? Could you ellaborate a bit? I'd appreciate.

**Comment by 954-Ivory** [comment]
> Thank you @954-Ivory. So are you saying it's not possible to use `max_token_limit` with DynamoDB as memory? Could you ellaborate a bit? I'd appreciate.

Yes, I think it's a bug.

**Comment by 954-Ivory** [comment]
> Thank you! Once you have it working, could you paste the code for the workaround? Appreciate it!

I used Redis to storage history.
You can change it to DynamoDB.

```python
from langchain_community.chat_message_histories import RedisChatMessageHistory
from langchain_core.messages import BaseMessage


class MessageList(list):
    def __new__(cls, *args, history=None, **kwargs):
        cls.history = history
        return super().__new__(cls)

    def pop(self, __index=0):
        if __index == 0:
            self.history.redis_client.rpop(self.history.key)
        elif __index == -1:
            self.history.redis_client.lpop(self.history.key)
        else:
            raise IndexError("Redis doesn't support pop by index.")
        # pop the message from history storage.
        super().pop(__index)


class RedisChatMessageHistoryFixed(RedisChatMessageHistory):

    @property
    def messages(self) -> MessageList[BaseMessage]:  # type: ignore
        messages = MessageList(super().messages, history=self)
        return messages
```
