### ISSUE TITLE
ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings' (/opt/conda/lib/python3.10/site-packages/langchain/embeddings/__init__.py)

### ISSUE THREAD

**Issue by jdjayakaran** [langchain-ai/langchain#14950]
### System Info

unable to resolve below issue

![image](https://github.com/langchain-ai/langchain/assets/144101750/a7b75fce-bb32-4b13-ab3e-e122455e3213)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

![image](https://github.com/langchain-ai/langchain/assets/144101750/40a9ed30-0761-46b0-8bcc-acb9cceb1734)

### Expected behavior

ImportError: cannot import name 'AzureOpenAIEmbeddings' from 'langchain.embeddings' (/opt/conda/lib/python3.10/site-packages/langchain/embeddings/__init__.py)

**Comment by navjotmakkar** [comment]
Have you found any fix?

**Comment by jdjayakaran** [comment]
Unfortunately, did not work

**Comment by jdjayakaran** [comment]
any leads on the issue?

**Comment by bbonik** [comment]
I am also facing the same issue

**Comment by baskaryan** [comment]
Hey all! This class lives in the langchain-openai package and needs to be imported from there.

Install:
```bash
pip install -U langchain-openai
```

Use:
```python
from langchain_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(...)
```

More docs here: https://python.langchain.com/docs/integrations/text_embedding/azureopenai
