### ISSUE TITLE
getting the error "TypeError: Agent.plan() got multiple values for argument 'intermediate_steps'" with agent_executor

### ISSUE THREAD

**Issue by chowdary1209** [langchain-ai/langchain#14954]
### System Info

langchain:                            0.0.351
langchain-community:        0.0.4
langchain-core:                   0.1.1
langchain-experimental:     0.0.47
python:                                3.10.4

### Who can help?

@hwchase17 , @agola11 , @eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create an agent and which is working as expected.
2. create an agent_executor by using above agent.
3. If i try to use agent_execuor, getting error "TypeError: Agent.plan() got multiple values for argument 'intermediate_steps'"

**Below is the code:**

Create an agent:-

```
agent = initialize_agent(llm=llm,
                         tools=tools,
                         agent = AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
                         verbose=True,
                         agent_kwargs=agent_kwargs,
                         output_parser = output_parser,
                         output_key = "result",
                         handle_parsing_errors = True,
                         max_iterations=3,
                         early_stopping_method="generate", 
                         memory = memory,                         
                        )
```

Create an agent_executor:-

```
agent_executor = AgentExecutor(agent=agent,
                               tools=tools,
                               verbose=True,
                               memory = memory,                               
                                )

```

calling the agent_executor
`result = agent_executor.invoke({"input":"Tell me about yourself", "format_instructions": response_format})["output"]`

Getting below error:-

```
Entering new AgentExecutor chain...


> Entering new AgentExecutor chain...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 result = agent_executor.invoke({"input":"Tell me about yourself", "format_instructions": response_format})["output"]
      2 print(f"result: {result}")

TypeError: Agent.plan() got multiple values for argument 'intermediate_steps'



```

What I have observed from the above error is that the chain is executing multiple times, hence the 'Entering new AgentExecutor chain...' message is displaying twice. This could be the cause of the issue.

### Expected behavior

Should return proper output with thought and action

**Comment by keenborder786** [comment]
@chowdary1209 You don't need to call `AgentExecutor` again. The `initialize_agent` not only creates your agent but also starts the Agent Exectuor. See the example below:

```python


from langchain.agents import initialize_agent
from langchain.chat_models import ChatOpenAI
from langchain.tools.wikipedia.tool import WikipediaQueryRun
from langchain_community.utilities.wikipedia import WikipediaAPIWrapper
from langchain.memory import ConversationBufferMemory
from langchain.agents import AgentType

import os
os.environ["OPENAI_API_KEY"] = ""
llm = ChatOpenAI()
tools = [WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())]

agent = initialize_agent(llm=llm,
                         tools=tools,
                         agent = AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
                         verbose=True,
                         output_key = "result",
                         handle_parsing_errors = True,
                         max_iterations=3,
                         early_stopping_method="generate",
                         memory = ConversationBufferMemory(memory_key = 'chat_history')                    
                        )

agent.invoke({"input":"Hello How are you doing?"})


```

Since you are using CONVERSATIONAL_REACT_DESCRIPTION agent you need to pass in the `chat_history` as your memory key. Moreover I am not so sure what exactly is `format_instructions` that you are passing to agent  as input. If this is needs to be passed as an input then make sure to change your prompt accordingly and declare it as input variable in your prompt.

**Comment by khawja-ghouse** [comment]
Hey @chowdary1209 can I get your help on this, 

```python 
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain.agents import tool,initialize_agent,AgentType
from langchain.memory import ConversationBufferWindowMemory,ConversationBufferMemory

llm = ChatOpenAI(model="gpt-4-1106-preview", temperature=0)

@tool
def getSquareOfNumber(number: str) -> str:
    """Metod used to return the square of the provided input."""
    print("Inside method getSquareOfNumber")
    x= int(number)*int(number)
    return "The square of "+ str(number)+" is " + str(x)


tools = [getSquareOfNumber]



prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """You are very powerful assistant, use tools only when its required.
            1. You don't know how to calculate square of a number so you will use method getSquareOfNumber.
            """
        ),
        (
            "user","{userInput}"
        ),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
        MessagesPlaceholder(variable_name="chat_history")
    ]
)


agent = initialize_agent(tools=tools,
                         agent=AgentType.OPENAI_FUNCTIONS,
                         llm=llm, 
                         prompt=prompt,
                         memory=ConversationBufferMemory(memory_key = 'chat_history'),
                         verbose=True,
                         )

user_input =""
while user_input != 'exit':
        user_input = input('Ask > ')
        if user_input != 'exit':
            response = agent.invoke({"input": user_input})    
            print(response)

output of simple examples are 
--------------------------------
Ask > what is square of number 6


> Entering new AgentExecutor chain...

Invoking: `getSquareOfNumber` with `{'number': '6'}`


Inside method getSquareOfNumber
The square of 6 is 36The square of the number 6 is 36.

> Finished chain.
{'input': 'what is square of number 6', 'chat_history': '', 'output': 'The square of the number 6 is 36.'}
Ask > what is the result of previous question


> Entering new AgentExecutor chain...
It seems there was no previous question provided in our conversation. If you have a specific question in mind, please feel free to ask, and I'll do my best to assist you!

> Finished chain.
{'input': 'what is the result of previous question', 'chat_history': 'Human: what is square of number 6\nAI: The square of the number 6 is 36.', 'output': "It seems there was no previous question provided in our conversation. If you have a specific question in mind, please feel free to ask, and I'll do my best to assist you!"}

```

My question is why I am not able to access chat history from agent even after history getting stored?

**Comment by PersonalRec** [comment]
> @chowdary1209 You don't need to call `AgentExecutor` again. The `initialize_agent` not only creates your agent but also starts the Agent Exectuor. See the example below:
> 
> ```python
> from langchain.agents import initialize_agent
> from langchain.chat_models import ChatOpenAI
> from langchain.tools.wikipedia.tool import WikipediaQueryRun
> from langchain_community.utilities.wikipedia import WikipediaAPIWrapper
> from langchain.memory import ConversationBufferMemory
> from langchain.agents import AgentType
> 
> import os
> os.environ["OPENAI_API_KEY"] = ""
> llm = ChatOpenAI()
> tools = [WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())]
> 
> agent = initialize_agent(llm=llm,
>                          tools=tools,
>                          agent = AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
>                          verbose=True,
>                          output_key = "result",
>                          handle_parsing_errors = True,
>                          max_iterations=3,
>                          early_stopping_method="generate",
>                          memory = ConversationBufferMemory(memory_key = 'chat_history')                    
>                         )
> 
> agent.invoke({"input":"Hello How are you doing?"})
> ```
> 
> Since you are using CONVERSATIONAL_REACT_DESCRIPTION agent you need to pass in the `chat_history` as your memory key. Moreover I am not so sure what exactly is `format_instructions` that you are passing to agent as input. If this is needs to be passed as an input then make sure to change your prompt accordingly and declare it as input variable in your prompt.

But the `.initialize_agent() `doesn't have the `handle_parsing_errors = True `parameter according to [its documentation](https://api.python.langchain.com/en/latest/agents/langchain.agents.initialize.initialize_agent.html). I would like to use this parameter in my code as well.
