### ISSUE TITLE
Pydantic error: extra fields not permitted for chain_type_kwargs

### ISSUE THREAD

**Issue by keviddles** [langchain-ai/langchain#1497]
Version: `langchain-0.0.102`

[I am trying to run through the Custom Prompt guide here](https://langchain.readthedocs.io/en/latest/modules/indexes/chain_examples/vector_db_qa.html#custom-prompts). Here's some code I'm trying to run:

```
from langchain.prompts import PromptTemplate
from langchain import OpenAI, VectorDBQA
prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

{context}

Question: {question}
Answer in Italian:"""
PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)
chain_type_kwargs = {"prompt": PROMPT}
qa = VectorDBQA.from_chain_type(llm=OpenAI(), chain_type="stuff", vectorstore=docsearch, chain_type_kwargs=chain_type_kwargs)
```

I get the following error:

```
File /usr/local/lib/python3.10/dist-packages/langchain/chains/vector_db_qa/base.py:127, in VectorDBQA.from_chain_type(cls, llm, chain_type, **kwargs)
    125 """Load chain from chain type."""
    126 combine_documents_chain = load_qa_chain(llm, chain_type=chain_type)
--> 127 return cls(combine_documents_chain=combine_documents_chain, **kwargs)

File /usr/local/lib/python3.10/dist-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for VectorDBQA
chain_type_kwargs
  extra fields not permitted (type=value_error.extra)
```

**Comment by cheetah90** [comment]
+1 to this issue

**Comment by carterrees-entrata** [comment]
Seeing a similar error for ChatVectorDBChain

`   return cls(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatVectorDBChain
qa_prompt
  extra fields not permitted (type=value_error.extra)
`

**Comment by anyuese** [comment]
same error
`2 validation errors for ChatVectorDBChain
chain
  extra fields not permitted (type=value_error.extra)
retriever
  extra fields not permitted (type=value_error.extra`

**Comment by carterrees-entrata** [comment]
What I have found is that I need to run pip install -U langchain everyday. And then make sure my code reflects the changes in the Langchain classes. These guys are moving so fast that the source code changes regularly. What worked a week ago might not work today. Its an exciting ride.

**Comment by annabechang** [comment]
similar error: 

```
instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
                                                      model_kwargs={"device": "cuda"})
                                                      

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[25], line 1
----> 1 instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
      2                                                       model_kwargs={"device": "cuda"})

File ~/.conda/envs/py38/lib/python3.8/site-packages/langchain/embeddings/huggingface.py:102, in HuggingFaceInstructEmbeddings.__init__(self, **kwargs)
    100 def __init__(self, **kwargs: Any):
    101     """Initialize the sentence_transformer."""
--> 102     super().__init__(**kwargs)
    103     try:
    104         from InstructorEmbedding import INSTRUCTOR

File ~/.conda/envs/py38/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for HuggingFaceInstructEmbeddings
model_kwargs
  extra fields not permitted (type=value_error.extra)
```

**Comment by devosonder** [comment]
Worked for me.
`pip install -U langchain`
`pip install langchain`

**Comment by Amjad-AbuRmileh** [comment]
> Seeing a similar error for ChatVectorDBChain
> 
> ` return cls( File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for ChatVectorDBChain qa_prompt extra fields not permitted (type=value_error.extra)`

got any solution?

**Comment by Amjad-AbuRmileh** [comment]
> similar error:
> 
> ```
> instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
>                                                       model_kwargs={"device": "cuda"})
>                                                       
> 
> ---------------------------------------------------------------------------
> ValidationError                           Traceback (most recent call last)
> Cell In[25], line 1
> ----> 1 instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
>       2                                                       model_kwargs={"device": "cuda"})
> 
> File ~/.conda/envs/py38/lib/python3.8/site-packages/langchain/embeddings/huggingface.py:102, in HuggingFaceInstructEmbeddings.__init__(self, **kwargs)
>     100 def __init__(self, **kwargs: Any):
>     101     """Initialize the sentence_transformer."""
> --> 102     super().__init__(**kwargs)
>     103     try:
>     104         from InstructorEmbedding import INSTRUCTOR
> 
> File ~/.conda/envs/py38/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()
> 
> ValidationError: 1 validation error for HuggingFaceInstructEmbeddings
> model_kwargs
>   extra fields not permitted (type=value_error.extra)
> ```

Got any solution?

**Comment by Amjad-AbuRmileh** [comment]
similar error

pydantic.error_wrappers.ValidationError: 1 validation error for ChatVectorDBChain
qa_prompt
  extra fields not permitted (type=value_error.extra)
  
 updating langChain didn't help

**Comment by Amjad-AbuRmileh** [comment]
> Version: `langchain-0.0.102`
> 
> [I am trying to run through the Custom Prompt guide here](https://langchain.readthedocs.io/en/latest/modules/indexes/chain_examples/vector_db_qa.html#custom-prompts). Here's some code I'm trying to run:
> 
> ```
> from langchain.prompts import PromptTemplate
> from langchain import OpenAI, VectorDBQA
> prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.
> 
> {context}
> 
> Question: {question}
> Answer in Italian:"""
> PROMPT = PromptTemplate(
>     template=prompt_template, input_variables=["context", "question"]
> )
> chain_type_kwargs = {"prompt": PROMPT}
> qa = VectorDBQA.from_chain_type(llm=OpenAI(), chain_type="stuff", vectorstore=docsearch, chain_type_kwargs=chain_type_kwargs)
> ```
> 
> I get the following error:
> 
> ```
> File /usr/local/lib/python3.10/dist-packages/langchain/chains/vector_db_qa/base.py:127, in VectorDBQA.from_chain_type(cls, llm, chain_type, **kwargs)
>     125 """Load chain from chain type."""
>     126 combine_documents_chain = load_qa_chain(llm, chain_type=chain_type)
> --> 127 return cls(combine_documents_chain=combine_documents_chain, **kwargs)
> 
> File /usr/local/lib/python3.10/dist-packages/pydantic/main.py:342, in pydantic.main.BaseModel.__init__()
> 
> ValidationError: 1 validation error for VectorDBQA
> chain_type_kwargs
>   extra fields not permitted (type=value_error.extra)
> ```

Got any solution?

**Comment by Jblauvs** [comment]
Also having this problem with HuggingFaceInstructEmbeddings, trying to pass in model_kwargs to load it onto the gpu.  

```
HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", model_kwargs = {'device': 'cuda:0'})
```

```
  File "/miniforge3/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 102, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceInstructEmbeddings
model_kwargs
  extra fields not permitted (type=value_error.extra)
```
Any fixes yet?

**Comment by DennisPeeters** [comment]
same with ConversationalRetrievalChain

**Comment by JoelHJames1** [comment]
Anyone was able to get this resolved?

**Comment by adrinanou** [comment]
have the same issue but with retrievalQA.from_chain_type(llm=llm,chain_type="map_reduce"....etc)
validation error for map-reducedocumentschain extra fields not permitted(type=value_error.extra)

**Comment by levalencia** [comment]
Same here.

My code

```
  if 'chain' not in st.session_state:
        tfretriever = TFIDFRetriever.from_texts(
            ["My name is Luis Valencia",
            "I am 70 years old",
            "I like gardening, baking and hockey"])
        
        template = """
            Use the following context (delimited by <ctx></ctx>) and the chat history (delimited by <hs></hs>) to answer the question:
            ------
            <ctx>
            {context}
            </ctx>
            ------
            <hs>
            {chat_history}
            </hs>
            ------
            {question}
            Answer:
            """
        
        prompt = PromptTemplate(
            input_variables=["chat_history", "context", "question"],
            template=template,
            )
        
        st.session_state['chain'] = chain = ConversationalRetrievalChain.from_llm(llm, 
                                                                                vectordb.as_retriever(),
                                                                                memory=memory,
                                                                                  chain_type_kwargs={
                                                                                    "verbose": True,
                                                                                    "prompt": prompt,
                                                                                    "memory": ConversationBufferMemory(
                                                                                        memory_key="chat_history",
                                                                                        input_key="question"),
                                                                                })
```

Error:ValidationError: 1 validation error for ConversationalRetrievalChain chain_type_kwargs extra fields not permitted (type=value_error.extra)
Traceback:

**Comment by OmiWakode** [comment]
Same issue with ConversationRetrievalChain.from_llm(llm = .., chain_type="map_reduce", question_promt=..., combine_prompt=....)

**Comment by levalencia** [comment]
same here https://github.com/hwchase17/langchain/issues/6635

**Comment by dromema** [comment]
same with ConversationalRetrievalChain

**Comment by dromema** [comment]
extra fields not permitted (type=value_error.extra)

**Comment by plaban1981** [comment]
Same error
PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context","question"]
  )
  #
  chain_type_kwargs = {"prompt": PROMPT}

 qa = RetrievalQA.from_chain_type(llm=llm,
                                chain_type="stuff",
                                vectorstore=doc_store.as_retriever(),
                                #chain_type_kwargs=chain_type_kwargs,
                                return_source_documents=True)

##error
ValidationError: 2 validation errors for RetrievalQA
retriever
  field required (type=value_error.missing)
vectorstore
  extra fields not permitted (type=value_error.extra)

**Comment by levalencia** [comment]
> I think this is so bad library, no one care about to update the documents.

its open source, so you can actually contribute and write better documentation. Its a library with  over 55K stars for a reason. :)

**Comment by SquirrelYe** [comment]
> 为我工作。 `pip install -U langchain` `pip install langchain`

It works for me, thanks a lot.

**Comment by chartl-rancho** [comment]
This currently happens also when trying to pass a `PromptTemplate.partial()` result into an `LLMChain`:

```
self.thinker = LLMChain(
       template=thinker_template.partial(initial_prompt=base_prompt),
       llm=thinker_llm,
       memory=memory,
       verbose=True
    )


---

File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for LLMChain
prompt
  field required (type=value_error.missing)
template
  extra fields not permitted (type=value_error.extra)
  
```

**Comment by kennethwork101** [comment]
Can someone please provide the version of langchian that works? 
I tried it on version 0.0.340
and it still failed.

llm = Ollama(model="codellama:7b", temperature=0.1, callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]))
a_chain = RetrievalQA.from_chain_type(
    llm,
    chain_type="map_reduce",
    retriever=vectordb.as_retriever(),
    return_source_documents=True,
    chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
)

-------------------------------------------------------------------------------
    return MapReduceDocumentsChain(
  File "/home/kenneth/learning/venv/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MapReduceDocumentsChain
prompt
  extra fields not permitted (type=value_error.extra)

(venv) kenneth@kenneth-PC:~/learning/deeplearning/LangChain-Chat-with-Your-Data$ pip show langchain
Name: langchain
Version: 0.0.340

**Comment by AlexCapchase** [comment]
Any solutions on this? I am getting the same error with `BaseQAWithSourcesChain.from_chain_type(self.llm, retriever=pg_vector, **executor_config)`. Commenting the line of the configuration of the pydantic object to not have this line `extra = Extra.forbid` works, but I don't know if this is desired.

**Comment by siddhant250502** [comment]
> > similar error:
> > ```
> > instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
> >                                                       model_kwargs={"device": "cuda"})
> >                                                       
> > 
> > ---------------------------------------------------------------------------
> > ValidationError                           Traceback (most recent call last)
> > Cell In[25], line 1
> > ----> 1 instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl", 
> >       2                                                       model_kwargs={"device": "cuda"})
> > 
> > File ~/.conda/envs/py38/lib/python3.8/site-packages/langchain/embeddings/huggingface.py:102, in HuggingFaceInstructEmbeddings.__init__(self, **kwargs)
> >     100 def __init__(self, **kwargs: Any):
> >     101     """Initialize the sentence_transformer."""
> > --> 102     super().__init__(**kwargs)
> >     103     try:
> >     104         from InstructorEmbedding import INSTRUCTOR
> > 
> > File ~/.conda/envs/py38/lib/python3.8/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()
> > 
> > ValidationError: 1 validation error for HuggingFaceInstructEmbeddings
> > model_kwargs
> >   extra fields not permitted (type=value_error.extra)
> > ```
> 
> Got any solution?

were you able to solve this error? @Amjad-AbuRmileh

**Comment by isabellaaquino** [comment]
still getting the same error with RetrievalQA setting the chain_type as anything different than "stuff"

**Comment by Bella722** [comment]
It works for me that I used the most violent method possible. comment the error code line
C:\Users\xxx\.conda\envs\chatglm\Lib\site-packages\pydantic\v1\main.py line 341
`        values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
        # if validation_error:
        #     raise validation_error`
