### ISSUE TITLE
Where to import ChatMessageHistory?

### ISSUE THREAD

**Issue by gaoxiao** [langchain-ai/langchain#1499]
ModuleNotFoundError: No module named 'langchain.memory'

**Comment by hwchase17** [comment]
we recently reorg'd the imports, see https://langchain.readthedocs.io/en/latest/modules/memory/how_to_guides.html

**Comment by sopmacvan** [comment]
Hello, I have also encountered this problem. I the tried an example in the [link](https://langchain.readthedocs.io/en/latest/modules/memory/how_to_guides.html) you provided but I'm still not sure how to fix it. Can you help me?

`from langchain.memory import ConversationBufferMemory`
ModuleNotFoundError: No module named 'langchain.memory

`from langchain.schema import Memory `
ImportError: cannot import name 'Memory' from 'langchain.schema'

**Comment by lianqiao** [comment]
hi @hwchase17 , the document you posted still have code like following, but doesn't work
`from langchain.memory import ConversationBufferMemory`

**Comment by parrajeremy** [comment]
@lianqiao 
pip install langchain[all]

https://langchain.readthedocs.io/en/latest/reference/installation.html

**Comment by usersina** [comment]
```python
from langchain_community.chat_message_histories.in_memory import ChatMessageHistory
```
