### ISSUE TITLE
DOC: Document PAGE NOT FOUND

### ISSUE THREAD

**Issue by XinhhD** [langchain-ai/langchain#14998]
### Issue with current documentation:

404 page: https://python.langchain.com/docs/contributing/integration

referenced by: https://python.langchain.com/docs/contributing/

![image](https://github.com/langchain-ai/langchain/assets/33118163/360d1a67-0c2c-471a-aba1-2eef21bc8f9a)

**Comment by Yanni8** [comment]
You are probably looking for [this](https://python.langchain.com/docs/contributing/integrations), right?

**Comment by cyai** [comment]
If we look at the [index.mdx](https://github.com/langchain-ai/langchain/blob/master/docs/docs/contributing/index.mdx) file in line 17, we need to update the `./integration` to `./integrations`

**Comment by Yanni8** [comment]
> If we look at the [index.mdx](https://github.com/langchain-ai/langchain/blob/master/docs/docs/contributing/index.mdx) file in line 17, we need to update the `./integration` to `./integrations`

#14999

**Comment by XinhhD** [comment]
Thank you for the Expedient fix!
