### ISSUE TITLE
In Pypdf loader "/n " is not removed before creating documents

### ISSUE THREAD

**Issue by Eknathabhiram** [langchain-ai/langchain#15011]
### System Info

Everything is latest

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader("path/to/document")
pages = loader.load_and_split()

### Expected behavior

Documents should not have "/n"

**Comment by cyai** [comment]
Hey @Eknathabhiram , When I tried to reproduce this issue on my side, the output seemed to be a python list.
and the `Page Content` element of that list seemed to have the content/text without `\n`

Could you please specify all the details to reproduce this issue.

**Comment by VpkPrasanna** [comment]
When i tried also it returned with `\n` values from the text and tested the same with the original library and it returned the same.

**Comment by cyai** [comment]
@VpkPrasanna could you attach screenshots here?

**Comment by konradbjk** [comment]
It would be good to be able to intercept the loader, in a way, that we can modify the `page_content` of the document. 

I have a similar issue, though, mine requires regex, as there are some patterns in the text, due to footer on each page. I can modify the file as text, and then use `split_text` method. However, it automatically removes the metadata, so I need to add it manually back. I wont be able to i.e., replicate page numbers

**Comment by konradbjk** [comment]
any updates?

**Comment by Eknathabhiram** [comment]
> When i tried also it returned with `\n` values from the text and tested the same with the original library and it returned the same.

@VpkPrasanna If you are using terminal colab etc. next line is being showed with /n. That's not the problem with library but the way we are printing the output. Check once again to print in frontend interface or swagger.
