### ISSUE TITLE
AttributeError while executing VectorstoreIndexCreator & DocArrayInMemorySearch

### ISSUE THREAD

**Issue by maheshnampoothirikv123** [langchain-ai/langchain#15016]
### System Info

I am using below packages.
Python 3.12.1
langchain 0.0.352
pydantic 2.5.2
openai 1.4.0
huggingface-hub 0.19.4

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

While executing the below code from deeplearning.ai

from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.document_loaders import CSVLoader
from langchain.vectorstores import DocArrayInMemorySearch
from IPython.display import display, Markdown

file = 'OutdoorClothingCatalog_1000.csv'
loader = CSVLoader(file_path=file, encoding='utf8')

from langchain.indexes import VectorstoreIndexCreator

index = VectorstoreIndexCreator(
    vectorstore_cls=DocArrayInMemorySearch
).from_loaders([loader])

### Expected behavior

Code should successfully execute

**Comment by maheshnampoothirikv123** [comment]
VectorstoreIndexCreator & DocArrayInMemorySearch are correctly imported from the respective packages

**Comment by maheshnampoothirikv123** [comment]
**This is the complete error description below:**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 3
      1 index = VectorstoreIndexCreator(
      2     vectorstore_cls=DocArrayInMemorySearch
----> 3 ).from_loaders([loader])

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\indexes\vectorstore.py:83, in VectorstoreIndexCreator.from_loaders(self, loaders)
     81 for loader in loaders:
     82     docs.extend(loader.load())
---> 83 return self.from_documents(docs)

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain\indexes\vectorstore.py:88, in VectorstoreIndexCreator.from_documents(self, documents)
     86 """Create a vectorstore index from documents."""
     87 sub_docs = self.text_splitter.split_documents(documents)
---> 88 vectorstore = self.vectorstore_cls.from_documents(
     89     sub_docs, self.embedding, **self.vectorstore_kwargs
     90 )
     91 return VectorStoreIndexWrapper(vectorstore=vectorstore)

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_core\vectorstores.py:510, in VectorStore.from_documents(cls, documents, embedding, **kwargs)
    508 texts = [d.page_content for d in documents]
    509 metadatas = [d.metadata for d in documents]
--> 510 return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\vectorstores\docarray\in_memory.py:68, in DocArrayInMemorySearch.from_texts(cls, texts, embedding, metadatas, **kwargs)
     46 @classmethod
     47 def from_texts(
     48     cls,
   (...)
     52     **kwargs: Any,
     53 ) -> DocArrayInMemorySearch:
     54     """Create an DocArrayInMemorySearch store and insert data.
     55 
     56     Args:
   (...)
     66         DocArrayInMemorySearch Vector Store
     67     """
---> 68     store = cls.from_params(embedding, **kwargs)
     69     store.add_texts(texts=texts, metadatas=metadatas)
     70     return store

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\vectorstores\docarray\in_memory.py:39, in DocArrayInMemorySearch.from_params(cls, embedding, metric, **kwargs)
     21 @classmethod
     22 def from_params(
     23     cls,
   (...)
     28     **kwargs: Any,
     29 ) -> DocArrayInMemorySearch:
     30     """Initialize DocArrayInMemorySearch store.
     31 
     32     Args:
   (...)
     37         **kwargs: Other keyword arguments to be passed to the get_doc_cls method.
     38     """
---> 39     _check_docarray_import()
     40     from docarray.index import InMemoryExactNNIndex
     42     doc_cls = cls._get_doc_cls(space=metric, **kwargs)

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\vectorstores\docarray\base.py:19, in _check_docarray_import()
     17 def _check_docarray_import() -> None:
     18     try:
---> 19         import docarray
     21         da_version = docarray.__version__.split(".")
     22         if int(da_version[0]) == 0 and int(da_version[1]) <= 31:

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\docarray\__init__.py:5
      1 __version__ = '0.39.1'
      3 import logging
----> 5 from docarray.array import DocList, DocVec
      6 from docarray.base_doc.doc import BaseDoc
      7 from docarray.utils._internal.misc import _get_path_from_docarray_root_level

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\docarray\array\__init__.py:2
      1 from docarray.array.any_array import AnyDocArray
----> 2 from docarray.array.doc_list.doc_list import DocList
      3 from docarray.array.doc_vec.doc_vec import DocVec
      5 __all__ = ['DocList', 'DocVec', 'AnyDocArray']

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\docarray\array\doc_list\doc_list.py:51
     43 T = TypeVar('T', bound='DocList')
     44 T_doc = TypeVar('T_doc', bound=BaseDocWithoutId)
     47 class DocList(
     48     ListAdvancedIndexing[T_doc],
     49     PushPullMixin,
     50     IOMixinDocList,
---> 51     AnyDocArray[T_doc],
     52 ):
     53     """
     54      DocList is a container of Documents.
     55 
   (...)
    121 
    122     """
    124     doc_type: Type[BaseDocWithoutId] = AnyDoc

File ~\AppData\Local\Programs\Python\Python312\Lib\site-packages\docarray\array\any_array.py:54, in AnyDocArray.__class_getitem__(cls, item)
     51 @classmethod
     52 def __class_getitem__(cls, item: Union[Type[BaseDocWithoutId], TypeVar, str]):
     53     if not isinstance(item, type):
---> 54         return Generic.__class_getitem__.__func__(cls, item)  # type: ignore
     55         # this do nothing that checking that item is valid type var or str
     56     if not safe_issubclass(item, BaseDocWithoutId):

AttributeError: 'builtin_function_or_method' object has no attribute '__func__'

**Comment by 954-Ivory** [comment]
It seems to be caused here:
https://github.com/docarray/docarray/pull/1147#discussion_r1111618991

**Comment by maheshnampoothirikv123** [comment]
> It seems to be caused here: [docarray/docarray#1147 (comment)](https://github.com/docarray/docarray/pull/1147#discussion_r1111618991)

It means I need to upgrade docarray package or which version I need to use?

**Comment by 954-Ivory** [comment]
> > It seems to be caused here: [docarray/docarray#1147 (comment)](https://github.com/docarray/docarray/pull/1147#discussion_r1111618991)
> 
> It means I need to upgrade docarray package or which version I need to use?

I utilized conda to establish a Python 3.11 environment.
Here are the versions of my installed packages:
langchain 0.0.352
pydantic 1.10.12
docarray 0.39.1"

**Comment by maheshnampoothirikv123** [comment]
I am using same as below. Only change I can see is the pydantic version. 
Python 3.12.1
langchain 0.0.352
pydantic 2.5.2
docarray 0.39.1

**Comment by 954-Ivory** [comment]
> I am using same as below. Only change I can see is the pydantic version. Python 3.12.1 langchain 0.0.352 pydantic 2.5.2 docarray 0.39.1

Currently, there appears to be an issue with Python 3.12.
If I recall correctly, this stems from the introduction of a mechanism for pre-calculating annotations, a new feature in Python 3.12.

---

I changed the pydantic version to address another related problem.

**Comment by maheshnampoothirikv123** [comment]
Yes, Python 3.12 is creating this issue. I have down graded to 3.11 and its working now. Thank you for the suggestion.

**Comment by 954-Ivory** [comment]
> Yes, Python 3.12 is creating this issue. I have down graded to 3.11 and its working now. Thank you for the suggestion.

A few days ago, I commited a PR to fixed this for docarray.
You can check if the docarray master is working properly in Python 3.12.
