### ISSUE TITLE
Issue: not getting output as per my prompt template

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15014]
### Issue you'd like to raise.

# below is my code  
`def generate_custom_prompt(query):   
    # Create the custom prompt template
    custom_prompt_template = f"""You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
    User's Question: {query}    
    In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
    Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

    Your Helpful Answer:"""

    # Create the PromptTemplate
    custom_prompt = PromptTemplate(
        template=custom_prompt_template, input_variables=["query"]
    )

    # Format the prompt
    formatted_prompt = custom_prompt.format(query=query)

    return formatted_prompt`
    #below is the error i am getting
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hs/CustomBot/chatbot/views.py", line 360, in GetChatResponse
    custom_message=generate_custom_prompt(query)
  File "/home/hs/CustomBot/accounts/common_langcain_qa.py", line 40, in generate_custom_prompt
    formatted_prompt = custom_prompt.format(query=query)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/prompt.py", line 132, in format
    return DEFAULT_FORMATTER_MAPPING[self.template_format](self.template, **kwargs)
  File "/usr/lib/python3.8/string.py", line 163, in format
    return self.vformat(format_string, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 29, in vformat
    return super().vformat(format_string, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 168, in vformat
    self.check_unused_args(used_args, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 18, in check_unused_args
    raise KeyError(extra)
KeyError: {'query'}

**Comment by deepak-habilelabs** [comment]
> ```python
> def generate_custom_prompt(query):   
>     # Create the custom prompt template
>     custom_prompt_template = f"""You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
>     User's Question: {query}    
>     In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
>     Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.
> 
>     Your Helpful Answer:"""
> 
>     # Create the PromptTemplate
>     custom_prompt = PromptTemplate(
>         template=custom_prompt_template, input_variables=["query"]
>     )
> 
>     # Format the prompt
>     formatted_prompt = custom_prompt.format(query=query)
> 
>     return formatted_prompt
> ```

still getting the same error
 File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/prompt.py", line 132, in format
    return DEFAULT_FORMATTER_MAPPING[self.template_format](self.template, **kwargs)
  File "/usr/lib/python3.8/string.py", line 163, in format
    return self.vformat(format_string, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 29, in vformat
    return super().vformat(format_string, args, kwargs)
  File "/usr/lib/python3.8/string.py", line 168, in vformat
    self.check_unused_args(used_args, args, kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/utils/formatting.py", line 18, in check_unused_args
    raise KeyError(extra)
KeyError: {'query'}

**Comment by cyai** [comment]
@bhadane-vivek  is right, the prompt template will be multi-line string with no f-string formating. If you remove the `f` then it shoudl work.

Here your final code should look like this:
```python
def generate_custom_prompt(query):
# Create the custom prompt template
custom_prompt_template = """You are a chatbot designed to provide helpful answers to user questions. If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
User's Question: {query}
In your response, aim for clarity and conciseness. Provide information that directly addresses the user's query. If the answer requires additional details, feel free to ask clarifying questions.
Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

Your Helpful Answer:"""

# Create the PromptTemplate
custom_prompt = PromptTemplate(
    template=custom_prompt_template, input_variables=["query"]
)

# Format the prompt
formatted_prompt = custom_prompt.format(query=query)

return formatted_prompt
```

**Comment by deepak-habilelabs** [comment]
> ```python
> formatted_prompt = custom_prompt.format(query=query)
> ```
@cyai 
can you pls explain how memory will be implemented after wards using custom prompt
