### ISSUE TITLE
Error message when adhering to Agents Langchain documentation only substituting OpenAI with AzureOpenAI: "openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}"

### ISSUE THREAD

**Issue by madsffm** [langchain-ai/langchain#15012]
### Issue you'd like to raise.

I am following the documentation on https://python.langchain.com/docs/modules/agents/, but as I only have access to an Azure deployment of OpenAI, there is a small deviance from the tutorial. When running the code:

`from langchain.chat_models import AzureChatOpenAI
from langchain.agents import tool
from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser

import os
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"

# Define the AzureChatOpenAI model
llm = AzureChatOpenAI(
    azure_endpoint="https://ENDPOINT.openai.azure.com",
    deployment_name="NAME",
    api_key="KEY",
    temperature=0.5
)

### Create tool
from langchain.agents import tool

@tool
def get_word_length(word: str) -> int:
    """Returns the length of a word."""
    return len(word)

tools = [get_word_length]

### create prompt
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are very powerful assistant, but bad at calculating lengths of words.",
        ),
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)

### llm with tool
from langchain.tools.render import format_tool_to_openai_function

llm_with_tools = llm.bind(functions=[format_tool_to_openai_function(t) for t in tools])

#### create agent
from langchain.agents.format_scratchpad import format_to_openai_function_messages
from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser

agent = (
    {
        "input": lambda x: x["input"],
        "agent_scratchpad": lambda x: format_to_openai_function_messages(
            x["intermediate_steps"]
        ),
    }
    | prompt
    | llm_with_tools
    | OpenAIFunctionsAgentOutputParser()
)

agent.invoke({"input": "how many letters in the word educa?", "intermediate_steps": []})`

I get the following error message, which arises from agent.invoke(...):

openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by Percival-Chan** [comment]
exact problem here, any follow up solution?

**Comment by Percival-Chan** [comment]
> exact problem here, any follow up solution?

https://python.langchain.com/docs/integrations/toolkits/azure_cognitive_services
Maybe check this out...
