### ISSUE TITLE
AzureSearch Bug -- langchain.vectorstores.azuresearch 

### ISSUE THREAD

**Issue by RERobbins** [langchain-ai/langchain#15039]
### System Info

The example found  [here](https://python.langchain.com/docs/integrations/vectorstores/azuresearch) and in particular this code fragment
```
embeddings: OpenAIEmbeddings = OpenAIEmbeddings(deployment=model, chunk_size=1)
index_name: str = "langchain-vector-demo"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```
fails with a message that at the top is:
```
vector_search_configuration is not a known attribute of class <class 'azure.search.documents.indexes.models._index.SearchField'> and will be ignored
semantic_settings is not a known attribute of class <class 'azure.search.documents.indexes.models._index.SearchIndex'> and will be ignored
```
and culminates with:
```
HttpResponseError: (InvalidRequestParameter) The request is invalid. Details: definition : The vector field 'content_vector' must have the property 'vectorSearchConfiguration' set.
Code: InvalidRequestParameter
Message: The request is invalid. Details: definition : The vector field 'content_vector' must have the property 'vectorSearchConfiguration' set.
Exception Details:  (InvalidField) The vector field 'content_vector' must have the property 'vectorSearchConfiguration' set. Parameters: definition
    Code: InvalidField
    Message: The vector field 'content_vector' must have the property 'vectorSearchConfiguration' set. Parameters: definition
```
I am running with `python 3.10`, `openai 1.5.0`, `langchain 0.0.351` and `azure-search-documents 11.4.0`.  If I revert to `azure-search-documents 11.4.0b8` the code works.

This appears to be related to the November 2023 Microsoft API change which introduced the concept of a "profile" which aggregates various vector search settings under one name. As a result of this API change, the old "vector_search_configuration" was deprecated and a new "vector_search_profile" was added, along with a new "profiles" object.  It seems that the Langchain extension has not been updated for this change and expects the old "vector_search_configuration" property which doesn't exist on newer SDK releases.

See the discussion [here](https://stackoverflow.com/questions/77682544/vector-search-configuration-is-not-a-known-attribute-of-class-class-azure-sear/77694628#77694628).

### Who can help?

@hwchase17 
@bas

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The following sample code fragment from [here:(https://python.langchain.com/docs/integrations/vectorstores/azuresearch) fails.

```
import os

from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores.azuresearch import AzureSearch

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "YOUR_OPENAI_ENDPOINT"
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"
os.environ["OPENAI_API_VERSION"] = "2023-05-15"
model: str = "text-embedding-ada-002"

vector_store_address: str = "YOUR_AZURE_SEARCH_ENDPOINT"
vector_store_password: str = "YOUR_AZURE_SEARCH_ADMIN_KEY"

embeddings: OpenAIEmbeddings = OpenAIEmbeddings(deployment=model, chunk_size=1)
index_name: str = "langchain-vector-demo"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```

### Expected behavior

The code should run without failure and return a vector store.

**Comment by RERobbins** [comment]
I believe it to be a Microsoft issue. Sent from my iPhoneOn Feb 7, 2024, at 4:16 PM, Konrad Bujak ***@***.***> wrote:﻿
I am at langchain 0.1.5 and I have the same issue
I believe it is related to langchain_community not langchain itself..

**Comment by konradbjk** [comment]
It is a feature, as Microsoft updated their way of connecting to the Indexes. They have now Vector Profiles (as their error states). 

It is langchain's package fault. Check the linked Issues. They are working on it

**Comment by shivam-51** [comment]
still facing this issue even after using `azure-search-documents==11.4.0b8`
