### ISSUE TITLE
NVIDIA Triton+TRT-LLM connector needs to handle dynamic model parameters

### ISSUE THREAD

**Issue by fciannella** [langchain-ai/langchain#15045]
### System Info

LangChain 0.0.348
langchain-nvidia-trt 0.0.1rc0
Python 3.11

### Who can help?

@jdye64 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

You can set up the triton server as in the quick start guide here using a nemotron model:

https://github.com/fciannella/langchain-fciannella/blob/master/libs/partners/nvidia-trt/README.md

Then you can just try sending a request from the LangChain plugin and it will not work. 

Same thing if you follow the more complex setup.

The input and output parameters need to be discovered by the client. One option is to use pytriton as a client, or just pull the parameters from the server using an API call to get the triton configuration?

### Expected behavior

The client should provide a list of the mandatory parameters in the error code in case there is a missing parameter in the request.

**Comment by mkhludnev** [comment]
Here's an example of passing `max_tokens` via `sample_parameters` in one backend https://github.com/triton-inference-server/vllm_backend/pull/34
