### ISSUE TITLE
GraphQAChain not working when using Networkx graphs !!

### ISSUE THREAD

**Issue by tkmamidi** [langchain-ai/langchain#15046]
### System Info

Langchain==0.0.352
MacOS intel version
python==3.8.3
networkx==2.7.1

### Who can help?

@hwchase17 @agola11 I have an issue when initializing GraphQAChain using networkx graph.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I made a networkx graph and tried to initialize GraphQAChain but got the below error.

<img width="1010" alt="image" src="https://github.com/langchain-ai/langchain/assets/41593805/d4ba54bc-bf43-4303-8550-8ef75fb4b7e0">

<img width="1482" alt="image" src="https://github.com/langchain-ai/langchain/assets/41593805/c4286425-7df7-4c3a-bbc5-3e6e92a69786">

### Expected behavior

I would like to initialize GraphQAChain and chat with the network. 
Please help!

**Comment by tkmamidi** [comment]
Unfortunately, even DiGraph is giving the same error !

<img width="1416" alt="image" src="https://github.com/langchain-ai/langchain/assets/41593805/5099d39c-3f2d-4958-9534-773df4012a16">

**Comment by tkmamidi** [comment]
Is it because the type of graph is `networkx_graph.NetworkxEntityGraph` and not just `NetworkxEntityGraph` ?

**Comment by tkmamidi** [comment]
Looks like I've imported differently. It's type is supposed to say `langchain_community.graphs.networkx_graph.NetworkxEntityGraph`. It is working now!!

**Comment by nikhitaKanoj** [comment]
> Looks like I've imported differently. It's type is supposed to say `langchain_community.graphs.networkx_graph.NetworkxEntityGraph`. It is working now!!

I am running the same issue , how did u solve it ?
My object is : "langchain.graphs.network_graph.NetworkxEntityGraph" object
