### ISSUE TITLE
Make it possible to give credentials directly via parameter on GoogleDriveLoader

### ISSUE THREAD

**Issue by Yanni8** [langchain-ai/langchain#15058]
### Feature request

The `GoogleDriveLoader` currently supports 3 different ways to authenticate a user.
1. Via a Service Account File
2. Via a Token File
3. Via a Live server

All those ways work perfectly, but I'm missing a way to authenticate the user via an existing JWT. There is a workaround by saving the JWT into a token file and providing this file via the `token_path` parameter. But there should also be a way to provide exactly these credentials via a parameter.

### Motivation

Maybe there is a use case where multiple accounts are required, or the user wants to authenticate over a third-party website running on an external server (not localhost). I think it would be useful to have a parameter that allows the functionality to pass a JWT without having to store it first in a file.

### Your contribution

I'm willing to submit a PR.

**Comment by walterheck** [comment]
I would like to see this very much as well, a google credentials object should be able to be passed in. https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html

**Comment by walterheck** [comment]
Disappointing to see this not being planned. The current workaround is pretty bad in terms of security.
