### ISSUE TITLE
SQLDatabaseChain raising TypeError exception with SQLite

### ISSUE THREAD

**Issue by btbean1980** [langchain-ai/langchain#15077]
### Issue you'd like to raise.

SQLDatabaseChain is throwing a TypeError when executing the .run or .invoke functions. All arguments or kwargs passed to the class are valid, but the error persists. I have trapped back to the database and there is a valid connection. My code and error are below:

```python

 sqlite_db = SQLDatabase.from_uri(
                  "sqlite:///./sqlite/ibdss.sqlite3",
                   sample_rows_in_table_info=2,
                   include_tables=["colts"]
                   )
db_chain = SQLDatabaseChain.from_llm(
                               llm,
                               sqlite_db,
                               return_direct=True,
                               use_query_checker=True,
                               return_intermediate_steps=True,
                               verbose=True
                                                                  )
 sqlite_response = db_chain.invoke({"query": "How many generators have over 10,000 hours of operation?"})
```
The issue happens when using .run as well.

Error Output:

TypeError: must be real number, not str

The traceback points to the invocation of the chain as the error area.

**Comment by dschwalm** [comment]
Hi @btbean1980 ! Could you please include a small data sample from the 'colts' table? So that a database can be quickly set up and the issue to be reproduced?
Thanks.

**Comment by btbean1980** [comment]
I've added the CREATE TABLE and INSERT statemtns below:

CREATE TABLE colts (
                            on_mission NUMERIC,
                            site_name TEXT,
                            supplier TEXT,
                            uid TEXT,
                            uid_verified TEXT,
                            condition_code TEXT,
                            config_id TEXT,
                            indenture_lvl TEXT,
                            nomenclature TEXT,
                            model_num TEXT,
                            sys_seg TEXT,
                            part_num TEXT,
                            serial_num TEXT,
                            status TEXT,
                            qty INTEGER,
                            qty_available INTEGER,
                            unit_price REAL,
                            total_cost REAL,
                            type_cd TEXT,
                            gfp_listing TEXT,
                            op_hours REAL,
                            cool_hours REAL,
                            supply_cls INTEGER,
                            procure_status TEXT,
                            conf_procure_date NUMERIC,
                            conf_discontinue_date NUMERIC,
                            part_sys_cd TEXT,
                            id INTEGER
                            )

INSERT INTO colts VALUES (0, 'Site 1', 'ACME Inc', ,,'B','KIT 004', 1,'Computer, Generic', '(Discontinued)','IBD','X20-10-B','RC44-187-X','FMC',1,1,5710.11,5710.11,,,'1-GFP Asset',0,0,9,'Discontinued-Replacement Needed',,,'Site 1 | A',1),
(1, 'Site 17', 'RELWIN', ,,'B','KIT 31', 1,'Accessory Kit', '1321-01-1071','ECP','3710-1','NA','FMC',1,1,99.70,99.70,,,'1-GFP Asset',0,0,9,'Procurable',,,'Site 17 | D',1)

I have also included the complete stack trace below:

File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/app_v7.py", line 761, in <module>
    main()
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/app_v7.py", line 549, in main
    run_sqlite_query(llm_query)
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/app_v7.py", line 293, in run_sqlite_query
    sqlite_response = db_chain.run(llm_query)
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 507, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 312, in __call__
    raise e
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain/chains/base.py", line 306, in __call__
    self._call(inputs, run_manager=run_manager)
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain_experimental/sql/base.py", line 118, in _call
    table_info = self.database.get_table_info(table_names=table_names_to_use)
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain_community/utilities/sql_database.py", line 333, in get_table_info
    table_info += f"\n{self._get_sample_rows(table)}\n"
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/langchain_community/utilities/sql_database.py", line 358, in _get_sample_rows
    sample_rows = list(
File "/Users/brandon.bean/Documents/LLM Prototypes/IBDSS Query AI Project/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 383, in iterrows
    row = make_row(row) if make_row else row

**Comment by btbean1980** [comment]
@dosu-bot

This did not fix the error. The on_mission column is treated as a boolean field and can be any data type since sqlite does not have a boolean data type. The type affinity of boolean in sqlite treats the field as numeric and stores the values as integers. A number of data types can be used with boolean columns in sqlite. 

The error actually appears to come from sqlalchemy based on the last element in the stack trace, but I cannot figure out why it would require a real number in a query itterow output.

**Comment by btbean1980** [comment]
@dosu-bot,

That TypeError is specific and would not create the TypeError output generated. The only generalized exception that is raised is on Line 312 in the base class of langchain's chains module in the langchain library.

**Comment by dschwalm** [comment]
@btbean1980 Works for me with your sample data. I suspect some data type error in your table data. Check the op_hours column for any non-real entries for example.
For example your sample data contains 1 as an integer for the column: indenture_lvl TEXT. This works because numeric values can be handled as text but not vice versa. Maybe the same is the case for op_hours.

**Comment by KrypticCoconut** [comment]
Same issue occured for me with sqlite aswell. Mysterious trigger conditions - It throws me the same error when i try to select lines form a reflected table.
