### ISSUE TITLE
Issue: Getting error while using ChatPromptTemplate

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15089]
### Issue you'd like to raise.

`def generate_custom_prompt(new_project_qa,query,name,not_uuid):  
    check = query.lower() 
    result = new_project_qa(query)
    relevant_document = result['source_documents']
    context_text="\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""You are a chatbot designed to provide answers to User's Questions, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        # Create the custom prompt template
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers in details to User's Question: ```{check} ``` which is delimited by triple backticks.
        Generate your answer in points in the following format:

        1. Point no 1
            1.1 Its subpoint in details
            1.2 More information if needed.
        2. Point no 2
            2.1 Its subpoint in details
            2.2 More information if needed.
        …
        N. Another main point.

        If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
        However, if the answer is not present in the predefined points,then Provide comprehensive information related to the user's query.
        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

        User's Question: ```{check} ```  
        AI Answer:"""

    # Create the PromptTemplate
    custom_prompt = ChatPromptTemplate(
        template=custom_prompt_template, input_variables=["check","context_text"]
    )
    formatted_prompt = custom_prompt.format()
    return formatted_prompt
`
#below is the error I am getting
Traceback (most recent call last):
  File "/home/hs/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/hs/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hs/CustomBot/chatbot/views.py", line 366, in GetChatResponse
    custom_message=generate_custom_prompt(chat_qa,query,name,not_uuid)
  File "/home/hs/CustomBot/accounts/common_langcain_qa.py", line 70, in generate_custom_prompt
    custom_prompt = ChatPromptTemplate(
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1050, in pydantic.main.validate_model
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/chat.py", line 449, in validate_input_variables
    messages = values["messages"]
KeyError: 'messages'

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> Hello again, @deepak-habilelabs! Nice to see you back here. Let's tackle this issue together, shall we? 🚀
> 
> Based on the traceback you've provided, it seems like the `ChatPromptTemplate` class in the LangChain framework is expecting a `messages` attribute, which is not being provided in your `generate_custom_prompt` function.
> 
> In the LangChain framework, the `ChatPromptTemplate` class requires a `messages` attribute, which should be a list of messages. Each message can be a `BaseMessagePromptTemplate`, a `BaseMessage`, or a `BaseChatPromptTemplate`.
> 
> Here's an example of how to create a `ChatPromptTemplate`:
> 
> ```python
> template = ChatPromptTemplate.from_messages([
>     ("system", "You are a helpful AI bot. Your name is {name}."),
>     ("human", "Hello, how are you doing?"),
>     ("ai", "I'm doing well, thanks!"),
>     ("human", "{user_input}"),
> ])
> ```
> 
> In this example, the `from_messages` class method is used to create a `ChatPromptTemplate` from a list of tuples, where each tuple represents a message. The first element of the tuple is the role (e.g., "system", "human", "ai"), and the second element is the message content.
> 
> You can find more details about this in the [LangChain codebase](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/prompts/chat.py).
> 
> Please modify your `generate_custom_prompt` function to include the `messages` attribute when creating a `ChatPromptTemplate`. If you continue to experience issues, please provide more details about your use case and I'll be happy to assist further.
> 
> ## Sources
> * [libs/core/langchain_core/prompts/chat.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/prompts/chat.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

def generate_custom_prompt(new_project_qa,query,name,not_uuid):  
    check = query.lower() 
    result = new_project_qa(query)
    relevant_document = result['source_documents']
    context_text="\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    print(context_text,"context_text")
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""You are a chatbot designed to provide answers to User's Questions, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        # Create the custom prompt template
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers in details to User's Question: ```{check} ``` which is delimited by triple backticks.
        Generate your answer in points in the following format:

        1. Point no 1
            1.1 Its subpoint in details
            1.2 More information if needed.
        2. Point no 2
            2.1 Its subpoint in details
            2.2 More information if needed.
        …
        N. Another main point.

        If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
        However, if the answer is not present in the predefined points,then Provide comprehensive information related to the user's query.
        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

        User's Question: ```{check} ```  
        AI Answer:"""

    # Create the PromptTemplate
    custom_prompt = ChatPromptTemplate.from_template(custom_prompt_template)
    formatted_prompt = custom_prompt.format(context_text,check)
    return formatted_prompt



    #now i am getting these error
     File "/home/hs/CustomBot/accounts/common_langcain_qa.py", line 71, in generate_custom_prompt
    custom_prompt = ChatPromptTemplate.from_template(custom_prompt_template)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/chat.py", line 486, in from_template
    prompt_template = PromptTemplate.from_template(template, **kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/prompt.py", line 247, in from_template
    input_variables = get_template_variables(template, template_format)
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/string.py", line 142, in get_template_variables
    input_variables = {
  File "/home/hs/env/lib/python3.8/site-packages/langchain_core/prompts/string.py", line 142, in <setcomp>
    input_variables = {
ValueError: unmatched '{' in format spec

**Comment by deepak-habilelabs** [comment]
> Based on the error message you provided, it seems like the issue is related to the use of curly braces `{}` in your custom prompt template. In Python, curly braces are used for string formatting, and any `{` must be matched with a `}`. If you want to include literal curly braces in your string, you need to escape them by doubling them, like so: `{{` and `}}`.

now i am getting below error
  File "/home/hs/env/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/hs/env/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/hs/env/lib/python3.8/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/hs/env/lib/python3.8/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/hs/env/lib/python3.8/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5241 tokens. Please reduce the length of the messages.

**Comment by cyai** [comment]
@deepak-habilelabs seems like the context length of your prompt has increased the context window of the model you're using. If you are using `gpt-3.5-turbo` then it has a context window of 4,096 tokens (1 token ~= 4 chars in English. 1 token ~= ¾ words). 

You could try using `gpt-3.5-turbo-16k` model insted. This might help resolve the error you're getting.

**Comment by deepak-habilelabs** [comment]
> @deepak-habilelabs seems like the context length of your prompt has increased the context window of the model you're using. If you are using `gpt-3.5-turbo` then it has a context window of 4,096 tokens (1 token ~= 4 chars in English. 1 token ~= ¾ words).
> 
> You could try using `gpt-3.5-turbo-16k` model insted. This might help resolve the error you're getting. This particular model would give you aroudn 16k tokens insted of just 4k

@cyai I already using  `gpt-3.5-turbo-16k` since begining as gpt-3.5-turbo only provide 4k tokens.
