### ISSUE TITLE
Return similarity score ConversationalRetrievalChain

### ISSUE THREAD

**Issue by rangelrey** [langchain-ai/langchain#15097]
### Feature request

I am using langchain.vectorstores.redis and langchain.chains.ConversationalRetrievalChain.from_llm

I would like to get the scores of the matching documents with my query. 

I know you can filter with the `search_kwargs={"score_threshold": 0.8}`

But still I want to get the similarity scores in the output.

### Motivation

To be able to play with the similarity scores on my end and allow flexibility to the user

### Your contribution

The output should be a list (like now) of tupples (Doc, score). In fact this already exists in the similarity_search_with_relevance_scores in lanchain.schema.vectorstore so the implementation should be quite straightforward

Thanks!

**Comment by polooner** [comment]
Hey @rangelrey, could you please give me some example code you are using? I would like to start doing this

**Comment by rangelrey** [comment]
Sure, here you go:

`from langchain.chains import ConversationalRetrievalChain
from langchain.prompts.chat import (ChatPromptTemplate,
                                    HumanMessagePromptTemplate,
                                    SystemMessagePromptTemplate)

messages = [
            SystemMessagePromptTemplate.from_template("the prompt abc"),
            HumanMessagePromptTemplate.from_template("the question cdefg}"),
        ]

ChatPromptTemplate.from_messages(messages)

 ConversationalRetrievalChain.from_llm(
            llm=self.answering_llm,
            retriever=self.vector_store.as_retriever()
            chain_type="stuff",
            combine_docs_chain_kwargs={"prompt": qa_prompt},
            return_source_documents=True
        )

`

This returns a list of documents. [Document...]]

My proposal would be that returns a list of tuples [(Document, score)...]

Let me know if you need more info

**Comment by rangelrey** [comment]
@polooner let me know if you need more support

**Comment by polooner** [comment]
Hey @rangelrey thanks, I do actually! I submitted an issue because I am experiencing some weird error that others some to encounter too; #15210 basically stuck running the simplest example
