### ISSUE TITLE
Feature: No safety settings when using langchain_google_genai's ChatGoogleGenerativeAI

### ISSUE THREAD

**Issue by 7vansh7** [langchain-ai/langchain#15095]
### Feature request

The safety settings are there in the **google_generativeai** library are are **not** there in the **langchain_google_genai** library
The safety settings is an basically array of dictionaries passed when sending the prompt

### Motivation

The problem with not having this is that when we use the ChatGoogleGenerativeAI model, if there is some kind of prompt which violate the basic safety settings then the model won't return with your answer 

If we can change the safety settings and send it with the prompt to the model we could fix this issue 

### Your contribution

I am currently reading the code of the library and will raise a PR if i could fix the issue

**Comment by lrbmike** [comment]
I have a similar problem.
When I want to use genai.configure function to set something, but I don't know how to set these in the langchain_google_genai library. 
And I find that the source code only deals with the setting of api_key, ` genai.configure(api_key=google_api_key)`

**Comment by 7vansh7** [comment]
yes, it is quite frustrating because it triggers the safety warnings with most politics related text or pdfs, i am currently working on fixing it, will raise the PR once its done

**Comment by 7vansh7** [comment]
just added the PR, will close the issue once its merged

**Comment by Spritan** [comment]
Any updates?

**Comment by rayanfer32** [comment]
Any updates ?

**Comment by vinnyricciardi** [comment]
@Spritan and @rayanfer32 
From the [PR above](https://github.com/7vansh7/langchain/commit/0cddf9a473e8c0d3a34a6480a1a01f0852e97390), it looks like you can just add `safety_settings=None` when you initiate your `langchain` model. For example:

```
langchain_model = ChatGoogleGenerativeAI(
        model="gemini-pro", google_api_key=GOOGLE_API_KEY,
        safety_settings=None
    )
```

**Comment by baron** [comment]
Google GenerativeAI is still missing the safety_settings which were added to VertexAI. Without any default values set Google GenerativeAI is prone to silently fail.

https://github.com/langchain-ai/langchain/pull/15344

https://github.com/langchain-ai/langchain/blob/master/libs/partners/google-genai/langchain_google_genai/llms.py

**Comment by baron** [comment]
@ironerumi Thanks for letting me know! Yes, it seems fixed now. I can finally work with the official wrapper again 👍

**Comment by blackslashcreative** [comment]
It seems like this is still not working? I tried setting BLOCK_NONE for everything and it still won't invoke a proper response. It still returns "I am not able to answer that question... Would you like me to try something different?" I'm using below, which I think is close:

`llm = ChatGoogleGenerativeAI(
  model="gemini-pro",
  temperature=0.7,
  safety_settings={
    HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
  },
)`

**Comment by baron** [comment]
> It seems like this is still not working? I tried setting BLOCK_NONE for everything and it still won't invoke a proper response. It still returns "I am not able to answer that question... Would you like me to try something different?" I'm using below, which I think is close:
> 
> `llm = ChatGoogleGenerativeAI( model="gemini-pro", temperature=0.7, safety_settings={ HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE, HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE, HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE, HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE, }, )`

```        safety_settings={
            HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
            HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
        }       
```

That's basically what I have too and unfortunately Google will still flat out refuse some queries. I highly recommend you try Langsmith to trace these calls so you can precisely narrow down the server response and add a fallback mechanism within your chain so it doesn't stop the execution. If you increase debugging it should show more helpful errors (but sometimes it will just fail). You could also try using GoogleGenerativeAI instead.

**Comment by EthanNadler** [comment]
I am curious about this as well. I have tried using both 
`llm = ChatGoogleGenerativeAI(safety_settings=None,model="gemini-pro",temperature=0.7, top_p=0.85)`
and the enumerated values and both times is fails. If anyone has a solution to this please let us know

**Comment by ironerumi** [comment]
It's just my assumption that when lowering the threshold Google will response more sensitive contents, but even if when set to None it won't response truly harmful contents like describe how to create a bomb in the kitchen or something.

So while asking those truly harmful questions, the difference when setting the threshold or not, will be whether you will get an answer like "I cannot tell you that" or the return content will be empty.

**Comment by MaharshiYeluri02** [comment]
'BLOCK NONE' is restricted, try the following settings
import google.generativeai as genai

safety_settings={
genai.types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: genai.types.HarmBlockThreshold.BLOCK_ONLY_HIGH,
genai.types.HarmCategory.HARM_CATEGORY_HARASSMENT: genai.types.HarmBlockThreshold.BLOCK_ONLY_HIGH,
genai.types.HarmCategory.HARM_CATEGORY_HATE_SPEECH: genai.types.HarmBlockThreshold.BLOCK_ONLY_HIGH,
genai.types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: genai.types.HarmBlockThreshold.BLOCK_ONLY_HIGH
}

**Comment by marwan-elsafty** [comment]
Neither BLOC_NONE, nor BLOCK_ONLY_HIGH are working

**Comment by ChungNYCU** [comment]
![image](https://github.com/langchain-ai/langchain/assets/79520786/00164600-b1e6-45df-a5f4-21ad331bc670)
yea, even I set block only high it will still block the MEDIUM content
```
gemini_safety_setting: dict = {}
            for category in HarmCategory:
                gemini_safety_setting[category] = HarmBlockThreshold.BLOCK_ONLY_HIGH
            # Initialize the GoogleGenerativeAI instance with the API key
            self.ai = ChatGoogleGenerativeAI(
                google_api_key=google_api_key,
                model=os.environ.get('GEMINI_MODEL'),
                safety_settings=gemini_safety_setting
            )
```
return msg
```
google.generativeai.types.generation_types.StopCandidateException: index: 0
finish_reason: SAFETY
safety_ratings {
  category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  probability: MEDIUM
}
safety_ratings {
  category: HARM_CATEGORY_HATE_SPEECH
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_HARASSMENT
  probability: NEGLIGIBLE
}
safety_ratings {
  category: HARM_CATEGORY_DANGEROUS_CONTENT
  probability: NEGLIGIBLE
}
```

**Comment by ez945y** [comment]
we really want this setting work very urgent, thanks

**Comment by jfperusse-bhvr** [comment]
I also noticed the parameter on ChatGoogleGenerativeAI is ignored. However, you can pass safety_settings to your model invoke method (or using model.bind(...) when chaining with LCEL) and it works fine.

**Comment by PrajwalPrashanth** [comment]
Facing this issue too. Was getting empty responses even after passing necessary `safety_settings` to `ChatGoogleGenerativeAI` or its respective chain's invoke method. After some digging I figured the `kwargs` is lost somewhere in the propagation of calls, Resulting in None `safety_settings` at `ChatGoogleGenerativeAI._generate`

I'm patching this with a work around or now, will update if i get something better
```
# store the original method
og_generate = ChatGoogleGenerativeAI._generate

# patch
ChatGoogleGenerativeAI._generate = partial(self.llm._generate, safety_settings=self.safety_settings)

chain = RetrievalQAWithSourcesChain(...)
result = chain.invoke({"question": question, ...})

# revert the patch
ChatGoogleGenerativeAI._generate = og_generate
```

**Comment by madox2** [comment]
@PrajwalPrashanth brilliant, you saved my day!

**Comment by vitorecomp** [comment]
@PrajwalPrashanth brilliant, you saved my day too!

One thing, when using stream:

```
llm =  ChatGoogleGenerativeAI(...)
safety_settings = {
    HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE
}

# store the original method
og_stream = ChatGoogleGenerativeAI._stream

# patch
ChatGoogleGenerativeAI._generate = partial(llm._stream, safety_settings=safety_settings)

result = llm.stream({"question": question, ...})

# revert the patch
ChatGoogleGenerativeAI._stream = og_stream
```

**Comment by JunityZhan** [comment]
> Facing this issue too. Was getting empty responses even after passing necessary `safety_settings` to `ChatGoogleGenerativeAI` or its respective chain's invoke method. After some digging I figured the `kwargs` is lost somewhere in the propagation of calls, Resulting in None `safety_settings` at `ChatGoogleGenerativeAI._generate`我也遇到了这个问题。即使在将必要的 `safety_settings` 传递给 `ChatGoogleGenerativeAI` 或其相应链的调用方法后，也一直收到空响应。经过一番调查，我发现 `kwargs` 在调用传播过程中丢失了，导致 `ChatGoogleGenerativeAI._generate` 处的 `safety_settings` 为 None。
> 
> Work around for now, patching with explicit setting of `safety_settings`. Will update if I figure out better目前采用变通方法，通过显式设置 `safety_settings` 来修补。如果找到更好的方法，我会更新。
> 
> ```python
> llm =  ChatGoogleGenerativeAI(...)
> safety_settings = {
>             HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE
>         }
> 
> # store the original method
> og_generate = ChatGoogleGenerativeAI._generate
> 
> # patch
> ChatGoogleGenerativeAI._generate = partial(llm._generate, safety_settings=safety_settings)
> 
> chain = RetrievalQAWithSourcesChain(...)
> result = chain.invoke({"question": question, ...})
> 
> # revert the patch
> ChatGoogleGenerativeAI._generate = og_generate
> ```

Remember that the HarmCategory should be imported by 
```python
from google.generativeai.types import HarmCategory, HarmBlockThreshold
```
instead of 
```python
from langchain_google_vertexai import HarmBlockThreshold, HarmCategory
```

**Comment by Engineer-D** [comment]
@PrajwalPrashanth Thank so much, you saved my day!
