### ISSUE TITLE
add support for embedding models with adapters

### ISSUE THREAD

**Issue by antonkulaga** [langchain-ai/langchain#15112]
### Feature request

It would be great to have adapters support in huggingface embedding class 

### Motivation

Many really good embedding models have special adapters for retrieval, for example specter2 which is a leading embedding for scientific texts have many adapters, for example https://huggingface.co/allenai/specter2_aug2023refresh
and current huggingface embedding implementations does not allow using them

### Your contribution

so far I am just implementing it in ugly way in my projects, not sure if/when I will have time for proper PR

**Comment by mrvaruntandon** [comment]
Could you share some code snippets to explain this feature request more?
