### ISSUE TITLE
langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404

### ISSUE THREAD

**Issue by BharathKumarAI** [langchain-ai/langchain#15147]
### System Info

Langchain Version: 0.0.352
Langchain experimental Version: 0.0.47
Python : 3.10
Ubuntu : 22.04

Poetry is being used 

**Code: `test.py`**

```python
import json

from langchain.schema import HumanMessage
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chat_models import ChatOllama

chat_model = ChatOllama(model="mistral:instruct")
json_schema = {
    "title": "Person",
    "description": "Identifying information about a person.",
    "type": "object",
    "properties": {
        "name": {"title": "Name", "description": "The person's name", "type": "string"},
        "age": {"title": "Age", "description": "The person's age", "type": "integer"},
        "fav_food": {
            "title": "Fav Food",
            "description": "The person's favorite food",
            "type": "string",
        },
    },
    "required": ["name", "age"],
}

messages = [
    HumanMessage(
        content="Please tell me about a person using the following JSON schema:"
    ),
    HumanMessage(content=json.dumps(json_schema, indent=2)),
    HumanMessage(
        content="Now, considering the schema, tell me about a person named John who is 35 years old and loves pizza."
    ),
]

chat_model_response = chat_model(messages)
```
**Error:**

```sh
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    chat_model_response = chat_model(messages)
  File ".venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 636, in __call__
    generation = self.generate(
  File ".venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 382, in generate
    raise e
  File ".venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 372, in generate
    self._generate_with_cache(
  File ".venv/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 528, in _generate_with_cache
    return self._generate(
  File ".venv/lib/python3.10/site-packages/langchain_community/chat_models/ollama.py", line 209, in _generate
    final_chunk = self._chat_stream_with_aggregation(
  File ".venv/lib/python3.10/site-packages/langchain_community/chat_models/ollama.py", line 168, in _chat_stream_with_aggregation
    for stream_resp in self._create_chat_stream(messages, stop, **kwargs):
  File ".venv/lib/python3.10/site-packages/langchain_community/chat_models/ollama.py", line 155, in _create_chat_stream
    yield from self._create_stream(
  File ".venv/lib/python3.10/site-packages/langchain_community/llms/ollama.py", line 198, in _create_stream
    raise OllamaEndpointNotFoundError(
langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404.
```
checked if ollama is running on port 11434 it is working fine, but still seeing the issue.

@hwchase17 @agola11 
Need some help on this. 

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

run the file `test.py` 

### Expected behavior

model should complete the predication without any issue

**Comment by chyroc** [comment]
@BharathKumarAI Hello! Regarding your problem, I tried to reproduce it on my mac computer.
The problem is this, the model you specified may not exist on your computer, you need to pull the model first.
The script is like this:

```bash
ollama pull mistral:instruct
```

Then you can try running the code again.
Good luck.

**Comment by BharathKumarAI** [comment]
@chyroc ,

It was present the models list, I pulled it before I ran it
![image](https://github.com/langchain-ai/langchain/assets/104408802/e5e12518-e291-4321-b474-dd30b8ffe31c).

If I use the `ollama` instead of `chatollama` it working fine

```python
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.llms import Ollama

llm = Ollama(
    model="llama2", callback_manager=CallbackManager([StreamingStdOutCallbackHandler()])
)

llm("Tell me about the history of AI")
```

I tried with different models available in my model list using `chatollama` still the same issue

**Comment by BharathKumarAI** [comment]
@chyroc Attaching the notebook as pdf which I ran, used the same code in the langchain documentation

[test.pdf](https://github.com/langchain-ai/langchain/files/13770545/test.pdf)

**Comment by BharathKumarAI** [comment]
@chyroc  seems issues with ollama update, I have updated the ollama and retried the same, it is working fine now.

**Comment by BharathKumarAI** [comment]
**Resolution**:  Update Ollama

**Comment by ErikValle2** [comment]
Hello, 

I am still having the same issue even after updating ollama. I tried the same things @BharathKumarAI did and this is my current pip list.

langchain 0.0.322
langsmith 0.0.51
python 3.11.7
ubuntu 20.04.6 LTS
ollama list
```
NAME            ID              SIZE    MODIFIED    
llama2:latest   78e26419b446    3.8 GB  4 hours ago
```

Any suggestion?

> @chyroc ,
> 
> It was present the models list, I pulled it before I ran it ![image](https://private-user-images.githubusercontent.com/104408802/292841150-e5e12518-e291-4321-b474-dd30b8ffe31c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjI3NDEsIm5iZiI6MTcwNzkyMjQ0MSwicGF0aCI6Ii8xMDQ0MDg4MDIvMjkyODQxMTUwLWU1ZTEyNTE4LWUyOTEtNDMyMS1iNDc0LWRkMzBiOGZmZTMxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxNDU0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTkwNGQ5NDQxNzY3MmRhN2FiNTFlMTRmY2VjNTc4NTY2YWQ1MGViYWJlYjhiMTRlYmZjMGQ1NjZmYjJiNzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjcKEOyMR51wC1YEvu1p45zcmqXDu2nllLJdk4twaBE).
> 
> If I use the `ollama` instead of `chatollama` it working fine
> 
> ```python
> from langchain.callbacks.manager import CallbackManager
> from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
> from langchain.llms import Ollama
> 
> llm = Ollama(
>     model="llama2", callback_manager=CallbackManager([StreamingStdOutCallbackHandler()])
> )
> 
> llm("Tell me about the history of AI")
> ```
> 
> I tried with different models available in my model list using `chatollama` still the same issue

**Comment by 2861330454** [comment]
Hello !
I have similar  problem 
python 3.10
langchain 0.1.16
langsmith 0.1.51
ollama list 
‘’‘ ollama list
NAME            ID              SIZE    MODIFIED
llama3:8b       a6990ed6be41    4.7 GB  2 days ago

’‘’
from langchain_community.llms import Ollama
from langchain_community.embeddings.ollama import OllamaEmbeddings
from langchain_chroma import Chroma
llm = Ollama(
    base_url = 'http://localhost:11434/v1',
    model = "llama3:8b",
    temperature = 0.8
vectorstore = Chroma.from_documents(documents=all_splitter,embedding=OllamaEmbeddings(model="llama3:8b",))

langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404. Maybe your model is not found and you should pull the model with `ollama pull llama3:8b`.

Any suggestion?

**Comment by 2861330454** [comment]
Hello !
I have similar problem
python 3.10
langchain 0.1.16
langsmith 0.1.51
ollama list
```
 ollama list
NAME ID SIZE MODIFIED
llama3:8b a6990ed6be41 4.7 GB 2 days ago
```
langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404. Maybe your model is not found and you should pull the model with ollama pull llama3:8b.


```
from langchain_community.llms import Ollama
from langchain_community.embeddings.ollama import OllamaEmbeddings
from langchain_chroma import Chroma
llm = Ollama(
base_url = 'http://localhost:11434/v1',
model = "llama3:8b",
temperature = 0.8
vectorstore = Chroma.from_documents(documents=all_splitter,embedding=OllamaEmbeddings(model="llama3:8b",))
```
The error returned
```
Traceback (most recent call last):
  File "H:\pythonfile\pythonProject\demo.py", line 67, in <module>
    response = rag_chain.invoke({"query":query,"chat_history":chat_history})
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\runnables\base.py", line 2499, in invoke
    input = step.invoke(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\language_models\llms.py", line 276, in invoke
    self.generate_prompt(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\language_models\llms.py", line 633, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\language_models\llms.py", line 803, in generate
    output = self._generate_helper(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\language_models\llms.py", line 670, in _generate_helper
    raise e
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_core\language_models\llms.py", line 657, in _generate_helper
    self._generate(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_community\llms\ollama.py", line 417, in _generate
    final_chunk = super()._stream_with_aggregation(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_community\llms\ollama.py", line 326, in _stream_with_aggregation
    for stream_resp in self._create_generate_stream(prompt, stop, **kwargs):
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_community\llms\ollama.py", line 172, in _create_generate_stream
    yield from self._create_stream(
  File "H:\pythonfile\pythonProject\venv\lib\site-packages\langchain_community\llms\ollama.py", line 244, in _create_stream
    raise OllamaEndpointNotFoundError(
langchain_community.llms.ollama.OllamaEndpointNotFoundError: Ollama call failed with status code 404. Maybe your model is not found and you should pull the model with `ollama pull llama3:8b`.
```

Any suggestion?
