### ISSUE TITLE
Issue: Explain Memory and How it's implemented in my Case.

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15170]
### Issue you'd like to raise.

`def generate_custom_prompt(new_project_qa,query,name,not_uuid):  
    check = query.lower() 
    result = new_project_qa(query)
    relevant_document = result['source_documents']
    context_text="\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    # print(context_text,"context_text")
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers to User's Questions:```{check}```, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        # Create the custom prompt template
        custom_prompt_template = f"""Generate your response exclusively from the provided context: {{context_text}}. You function as a chatbot specializing in delivering detailed answers to the User's Question: ```{{check}} ```, enclosed within triple backticks.
            Generate your answer in points in the following format:
            1. Point no 1
                1.1 Its subpoint in details
                1.2 More information if needed.
            2. Point no 2
                2.1 Its subpoint in details
                2.2 More information if needed.
            …
            N. Another main point.

            If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
            However, if the answer is not present in the predefined points, then Provide comprehensive information related to the user's query.
            Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

            User's Question: ```{{check}} ```  
            AI Answer:"""

    # Create the PromptTemplate
    custom_prompt = ChatPromptTemplate.from_template(custom_prompt_template)
    formatted_prompt = custom_prompt.format(context_text=context_text, check=check)
    return formatted_prompt 

    def retreival_qa_chain(chroma_db_path):
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    llm = ChatOpenAI(temperature=0.1)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever,return_source_documents=True)
    return qa`

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> Hello @deepak-habilelabs! Nice to see you again. Let's dive into this issue together, shall we?
> 
> The memory in the provided code snippet is implemented using a Python dictionary. This is evident from the line `memories: Dict[str, Any] = dict()`. This dictionary, `memories`, is used to store context or other information that should not change between prompts.
> 
> The `SimpleMemory` class has several methods related to memory:
> 
> 1. `memory_variables`: This is a property method that returns a list of all keys in the `memories` dictionary. This represents all the variables stored in the memory.
> 2. `load_memory_variables`: This method returns the `memories` dictionary as it is. It takes an `inputs` parameter but does not use it, indicating that the memory is not influenced by external inputs.
> 3. `save_context`: This method is designed to save context into the memory. However, in this implementation, it does nothing. The docstring suggests that the memory is "set in stone", meaning it cannot be modified once set.
> 4. `clear`: This method is designed to clear the memory. However, in this implementation, it also does nothing. The docstring suggests that the memory is like a "vault", meaning it retains its contents indefinitely.
> 
> In summary, the memory in this code is a static dictionary that cannot be modified or cleared once set. You can find more details in the [libs/langchain/langchain/memory/simple.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/simple.py) file.
> 
> Regarding the `generate_custom_prompt` function, it is used to generate a custom prompt string based on the constraints, commands, resources, and performance evaluations that have been added to the `PromptGenerator` object. It formats the `response_format` dictionary into a JSON string with an indentation of 4 spaces using `json.dumps(self.response_format, indent=4)`. Then, it generates a string `prompt_string` that includes a numbered list of constraints, commands, resources, and performance evaluations. Finally, it returns the `prompt_string`. You can find more details in the [libs/experimental/langchain_experimental/autonomous_agents/autogpt/prompt_generator.py](https://github.com/langchain-ai/langchain/blob/master/libs/experimental/langchain_experimental/autonomous_agents/autogpt/prompt_generator.py) file.
> 
> As for the `UserExperience` object, I wasn't able to find an answer within the repository. It might be that the answer is available elsewhere or I could have missed it. Could you provide more context or details about the `UserExperience` object? This would help me provide a more accurate answer.
> 
> ## Sources
> * [libs/langchain/langchain/memory/simple.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/simple.py)
> * [libs/experimental/langchain_experimental/autonomous_agents/autogpt/prompt_generator.py](https://github.com/langchain-ai/langchain/blob/master/libs/experimental/langchain_experimental/autonomous_agents/autogpt/prompt_generator.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

how can i implement ConversationBufferMemory ?

**Comment by keenborder786** [comment]
Your code does not make any sense and so your question. Can you please better format your question and clarify what exactly are you asking for.
