### ISSUE TITLE
DOC: How to write my own short scripts within a fork to test some code?

### ISSUE THREAD

**Issue by polooner** [langchain-ai/langchain#15177]
### Issue with current documentation:

I want to contribute to one of the libs and started a fork. Here are the steps I took:

I am trying to add a new feature but first need to experiment with it. I am unsure on how to get started writing some short scripts to use the libs. 

1. I went into ```libs/experimental```, ```libs/core```, ```libs/community``` ```libs/langchain``` and ran ```poetry install``` in all of them.

2. I start an environment from ```libs/langchain``` with ```poetry shell```

3. I created a file inside of it, made some short code:

```from langchain.document_loaders import PyPDFLoader
from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Chroma

# load the document and split it into chunks
loader = PyPDFLoader("./llm_in_a_flash_apple.pdf")
documents = loader.load_and_split()

# create the open-source embedding function
embedding_function = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")

# load it into Chroma
db = Chroma.from_documents(documents, embedding_function)

# query it
query = "What did the president say about Ketanji Brown Jackson"
docs = db.similarity_search(query)

# print results
print(docs[0].page_content)
```

and got the following error:

```
Traceback (most recent call last):
  File "/Users/polo/langchain/libs/langchain/test.py", line 9, in <module>
    loader = PyPDFLoader("./llm_in_a_flash_apple.pdf")
  File "/Users/polo/langchain/libs/community/langchain_community/document_loaders/pdf.py", line 154, in __init__
    raise ImportError(
ImportError: pypdf package not found, please install it with `pip install pypdf`
```

This is my first time in a Python project like this. I am unsure how to get started using all the different packages while in a fork of the repository. If anyone can guide me I would love to make a PR on this, it is quite daunting for beginners to get around and start contributing!

**Comment by Armanasq** [comment]
I have the same problem here.
The pdf file is exist in the directory, but it is impossible to load it. I continuously get the error below.


ValueError                                Traceback (most recent call last)
Cell In[7], line 4
      1 from langchain.document_loaders import PyPDFLoader
      3 loaders = [
----> 4     PyPDFLoader("DSM5.pdf")
      5 ]
      6 pages = []
      7 for loader in loaders:

File /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/pdf.py:182, in PyPDFLoader.__init__(self, file_path, password, headers, extract_images)
    178 except ImportError:
    179     raise ImportError(
    180         "pypdf package not found, please install it with " "`pip install pypdf`"
    181     )
--> 182 super().__init__(file_path, headers=headers)
    183 self.parser = PyPDFParser(password=password, extract_images=extract_images)

File /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/pdf.py:116, in BasePDFLoader.__init__(self, file_path, headers)
    114         self.file_path = str(temp_pdf)
    115 elif not os.path.isfile(self.file_path):
--> 116     raise ValueError("File path %s is not a valid file or url" % self.file_path)

ValueError: File path DSM5.pdf is not a valid file or url



Any ideas?
