### ISSUE TITLE
pgvecto.rs: retriever filter not working

### ISSUE THREAD

**Issue by icp-lab-admin** [langchain-ai/langchain#15173]
### System Info

OS: Windows
Python: 3.9.10
Langchain version: 0.0.352
openai version: 1.6.1

### Who can help?

@BeautyyuYanli
@baskaryan 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.vectorstores.pgvecto_rs import PGVecto_rs
from langchain.embeddings import AzureOpenAIEmbeddings
from dotenv import dotenv_values
import os
```

```
config = dotenv_values(".env")
# os.environ["TIKTOKEN_CACHE_DIR"] = "./cache/tiktoken/"

embeddings = AzureOpenAIEmbeddings(
    max_retries=3,
    timeout=60,
    api_key=config["api_key"],
    model="text-embedding-ada-002",
    openai_api_type=config["api_type"],
    azure_endpoint=config["api_base"]
)

URL = "postgresql+psycopg://{username}:{password}@{host}:{port}/{db_name}".format(
    port=config["db_port"],
    host=config["db_host"],
    username=config["db_user"],
    password=config["db_pass"],
    db_name=config["db_name"],
)

db = PGVecto_rs(
    embedding=embeddings,
    db_url=URL,
    dimension=1536, # text-embedding-ada-002
    collection_name="test",
)
```

```
docs = ["a text about mathematics", "a text about physics"]
meta = [{"id": "1"}, {"id": "2"}]

db.add_texts(
    texts=docs,
    metadatas=meta
)

retr = db.as_retriever(
    search_kwargs = {
        "k": 1,
        "filter": {"id": "1"}
    }
)
```

```
retr.invoke("physics")
```
>[Document(page_content='a text about physics', metadata={'id': '2'})]

### Expected behavior

The search should only be performed on documents where the `metadata` field contains `{"id": "1"}`.

In this case, adding a filter makes no difference to the retrieval.

**Comment by BeautyyuYanli** [comment]
Can you provide the pgvecto_rs version you are using?

**Comment by BeautyyuYanli** [comment]
Currenty the pgvecto_rs in langchain does not support filter. I will make it later
