### ISSUE TITLE
Token Usage tracking doesn't seem to work for ChatGPT (with streaming off)

### ISSUE THREAD

**Issue by bent-verbiage** [langchain-ai/langchain#1519]
Using the callback method described here, the Token Usage tracking doesn't seem to work for ChatOpenAI. Returns "0" tokens. I've made sure I had streaming off, as I think I read that the combination is not supported at the moment.

https://langchain.readthedocs.io/en/latest/modules/llms/examples/token_usage_tracking.html?highlight=token%20count

**Comment by stephenleo** [comment]
I can work on this

**Comment by stephenleo** [comment]
just submitted a PR: https://github.com/hwchase17/langchain/pull/1748

**Comment by stephenleo** [comment]
submitted another PR: #1924
Would love to get some feedback as this is blocking for me :(
