### ISSUE TITLE
Issue: issue with pdfplumber

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15227]
### Issue you'd like to raise.

from langchain.document_loaders.parsers.pdf import PDFPlumberParser

def generate_embeddings(config: dict = None, urls = None, file_path = None, persist_directory=None):
    if file_path:
        parser = PDFPlumberParser()
        data = parser.load(file_path)
        processed_data = parser.process(data)
        print(processed_data,"processed_data is-----------------llllllllllllllllllllllllllllll")
#below is the error i'm getting
  data = parser.load(file_path)
AttributeError: 'PDFPlumberParser' object has no attribute 'load'

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> Hey there, @deepak-habilelabs! Long time no see, how's the coding universe treating you? 😆
> 
> Based on the context provided, it seems like the `PDFPlumberParser` class does not have a `load` method, which is causing the `AttributeError` you're encountering. The `PDFPlumberParser` class is designed to parse PDF documents using the PDFPlumber library, but it does not have a method to load the documents.
> 
> Instead, the `PDFPlumberParser` class has a `lazy_parse` method that takes a `Blob` object as an argument and yields a `Document` object for each page in the PDF. The `Blob` object should represent the PDF document you want to parse.
> 
> Here's an example of how you can use the `PDFPlumberParser` class to parse a PDF document:
> 
> ```python
> from langchain.document_loaders import Blob
> from langchain.document_loaders.parsers.pdf import PDFPlumberParser
> 
> # Create a Blob object for the PDF document
> blob = Blob.from_path("example.pdf")
> 
> # Create a PDFPlumberParser object
> parser = PDFPlumberParser()
> 
> # Use the lazy_parse method to parse the PDF document
> for document in parser.lazy_parse(blob):
>     print(document)
> ```
> 
> Please replace `"example.pdf"` with the path to your PDF file.
> 
> If you want to load a PDF file, you might want to use one of the loader classes, such as `PDFMinerLoader`, `PyMuPDFLoader`, or `AmazonTextractPDFLoader`. These classes have a `load` method that you can use to load a PDF file.
> 
> Here's an example of how you can use the `PDFMinerLoader` class to load a PDF file:
> 
> ```python
> from langchain.document_loaders import PDFMinerLoader
> 
> # Create a PDFMinerLoader object
> loader = PDFMinerLoader("example.pdf")
> 
> # Use the load method to load the PDF file
> docs = loader.load()
> ```
> 
> Please replace `"example.pdf"` with the path to your PDF file.
> 
> I hope this helps! If you have any other questions or need further clarification, please let me know.
> 
> For more information, you can refer to the source code of the `PDFPlumberParser` class in the [langchain.document_loaders.parsers.pdf](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/parsers/pdf.py) module and the `PDFMinerLoader` class in the [langchain.document_loaders](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/pdf.py) module.
> 
> ## Sources
> * [libs/langchain/langchain/document_loaders/pdf.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/pdf.py)
> * [libs/community/langchain_community/document_loaders/parsers/pdf.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/parsers/pdf.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

My Aim to extract Unstructured tables and images as well as text present in PDFs into some meaningful information.

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> You're correct in your understanding that the `PDFPlumberParser` class does not have a `load` method. Instead, you should use the `lazy_parse` method. This method is designed to lazily parse a PDF document and return an iterator of `Document` objects, each representing a page in the PDF document.
> 
> Here's how you can modify your `generate_embeddings` function to use the `lazy_parse` method:
> 
> ```python
> from langchain_community.document_loaders.blob_loaders import Blob
> from libs.community.langchain_community.document_loaders.parsers.pdf import PDFPlumberParser
> 
> def generate_embeddings(config: dict = None, urls = None, file_path = None, persist_directory=None):
>     if file_path:
>         # Create a Blob instance with the PDF data
>         with open(file_path, 'rb') as file:
>             blob = Blob(data=file.read(), source=file_path)
> 
>         # Create a PDFPlumberParser instance
>         parser = PDFPlumberParser(extract_images=True)
> 
>         # Use the lazy_parse method to extract text from the PDF
>         documents = parser.lazy_parse(blob)
> 
>         # Iterate over the documents to access the extracted text
>         for document in documents:
>             print(document.page_content)
> ```
> 
> In this code, `Blob` is a class that represents a blob of data. You create a `Blob` instance with the binary data of your PDF file and the source of the blob. The `extract_images` parameter is set to `True` to enable the extraction of text from images in the PDF. The `lazy_parse` method returns an iterator of `Document` instances, each representing a page in the PDF. The extracted text can be accessed through the `page_content` attribute of the `Document` instances.
> 
> Please note that this code assumes that the necessary packages are installed and the LangChain framework is properly set up. If you encounter any issues, please provide more specific details so I can give a more tailored solution.
> 
> For more information about the `lazy_parse` method and the `PDFPlumberParser` class, you can refer to the [PDFPlumberParser source code](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/parsers/pdf.py).
> 
> ## Sources
> * [libs/community/langchain_community/document_loaders/parsers/pdf.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/parsers/pdf.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Is this code is able to extract tables and Images from PDF?

**Comment by cyai** [comment]
> ### Issue you'd like to raise.
> from langchain.document_loaders.parsers.pdf import PDFPlumberParser
> 
> def generate_embeddings(config: dict = None, urls = None, file_path = None, persist_directory=None): if file_path: parser = PDFPlumberParser() data = parser.load(file_path) processed_data = parser.process(data) print(processed_data,"processed_data is-----------------llllllllllllllllllllllllllllll") #below is the error i'm getting data = parser.load(file_path) AttributeError: 'PDFPlumberParser' object has no attribute 'load'
> 
> ### Suggestion:
> _No response_

@deepak-habilelabs you have to pass the `file_path` when you create the object of `PDFPlumberParser()` as a constructor argument.

Here,

```python
from langchain.document_loaders.parsers.pdf import PDFPlumberParser

def generate_embeddings(config: dict = None, urls = None, file_path = None, persist_directory=None):
    if file_path:
        parser = PDFPlumberParser(file_path)
        data = parser.load()
        processed_data = parser.process(data)
        print(processed_data,"processed_data is-----------------llllllllllllllllllllllllllllll")
```


You can refer to the official document [here](https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf#using-pdfplumber)
