### ISSUE TITLE
HuggingFace Chat Wrapper - issue with HuggingFaceHub

### ISSUE THREAD

**Issue by netranga** [langchain-ai/langchain#15232]
### Issue with current documentation:

I am currently following the document to use a hugigngface LLM as a chat model: https://python.langchain.com/docs/integrations/chat/huggingface

I have setup my Huggingface API and am using Option 3 (HuggingFaceHub) to instantiate an LLM. 

After running this line: chat_model._to_chat_prompt(messages) 

I get the following error: ValueError: last message must be a HumanMessage

I am running the code the exactly the same as the documentation, including using the HuggingFaceH4/zephyr-7b-beta model.

Any help in resolving this issue is much appreciated.

**Comment by netranga** [comment]
Yes, thank you. The import statement in the article is outdated as it should be from langchain_core.messages import HumanMessage, SystemMessage and not from langchain.schema import (
    HumanMessage,
    SystemMessage,
)

After using this wrapper, would this model be compatible with the create_extraction_chain or is that only for OpenAI chat models?

Thank you.

**Comment by netranga** [comment]
@dosu-bot

**Comment by bigrobinson** [comment]
The problem I have with this is that some tool calling models (like some Nous Research models) expect a return from the tool call, with the 'tool' role and set off by `<tool_response>` tags to provide user friendly feedback. This categorical prohibition on last messages other than `HumanMessage`s seems heavy handed and is causing me problems. If I am misunderstanding something, or there is a workaround, please let me know. A switch to allow other message types could be nice. I tried to make changes in the source code to accommodate my case, but it seems that check exists in multiple places in the code, and I don't want to hunt down all those instances and break the code.
