### ISSUE TITLE
Callbacks for embeddings

### ISSUE THREAD

**Issue by lkNGAT** [langchain-ai/langchain#15253]
### Feature request

Similar to the way callbacks are implemented in BaseLLM the embedding class should also support callbacks.

### Motivation

When using embedding models in a RAG application it would be useful to track e.g. the number of tokens.
Callbacks can be used to log usage details to monitoring services (eg Langsmith).

### Your contribution

There is a closed PR adressing the same topic https://github.com/langchain-ai/langchain/pull/7920

**Comment by pmarchini** [comment]
Hey there, 

Any news regarding this issue?

This feature would greatly improve our use case!
