### ISSUE TITLE
[mistralai]: Don´t support stop sequence

### ISSUE THREAD

**Issue by DavidLMS** [langchain-ai/langchain#15269]
### System Info

Python: 3.11
Langchain: 0.0.352
mistralai: 0.0.8

### Who can help?

@efriis 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

If the ChatMistralAI model is used for an agent or similar, an error appears because the official Mistral API does not currently support the stop parameter (as other APIs such as OpenAI do).

### Expected behavior

Although this is something that should be fixed by Mistral in its official API, one of the following options should be done:
- Warn the user that this model cannot be used with a stop sequence before breaking execution due to the error.
- Implement an own solution for the stop sequence in the same package and do not send that parameter to the official client call.

**Comment by niels-garve** [comment]
Hi @DavidLMS and @efriis,

I fixed that in my pull request: https://github.com/langchain-ai/langchain/pull/15375. What do you think of my suggested solution?

Thanks and cheers, Niels
