### ISSUE TITLE
Manipulating database using chatgpt 

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#15266]
### System Info

Is there any way to manipulate the data in database like update, insert, delete through chatgpt chatbot with openai and langchain?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Is there any way to manipulate the data in database like update, insert, delete through chatgpt chatbot with openai and langchain?

### Expected behavior

possibility of  manipulate the data in database like update, insert, delete through chatgpt chatbot with openai and langchain?

**Comment by keenborder786** [comment]
Here you go, I have construct a Agent who have a tool that can execute DML queries on your underlying SQL database. 





```python

from langchain.sql_database import SQLDatabase
from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder,PromptTemplate
from langchain.tools import BaseTool
from langchain.tools.render import format_tool_to_openai_function
from langchain.schema.runnable import Runnable,RunnableLambda,RunnableParallel
from langchain.chat_models import ChatOpenAI
from langchain.agents.format_scratchpad import format_to_openai_function_messages
from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser
from langchain.agents import AgentExecutor
from pydantic import BaseModel, Field
import os

os.environ['OPENAI_API_KEY'] = 'sk-xxxxxxxxxxxx'
SQL_DML_CHAIN_PROMPT = """You are expert in SQLITE. Your main objective is to construct Data manipulation SQLITE query give the
user question: {user_question}.

You need to construct the Data manipulation SQLITE query for the following Database Schema:
{table_info}

Only Output the final SQL-Query and nothing else.

SQL-Query:"""

prompt = PromptTemplate(template = SQL_DML_CHAIN_PROMPT,input_variables = ['user_question','table_info'])
db =  SQLDatabase.from_uri("sqlite:///chinook.db")
sql_dml_chain = RunnableParallel ({"user_question":lambda x:x["user_question"],
                 "table_info":lambda _: db.get_table_info()}) |\
                prompt |\
                ChatOpenAI().bind(stop='SQL-Query:') |\
                RunnableLambda(lambda x:x.content.strip().replace('```sql',''))
agent_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", """
        You are expert in SQL whose main objective is to mainpulate the Chinook Database for which you have
        been given access. You can use the tool `sql_db_manipulation` to interact with  Chinook Database and
        mainpulate the database as per the user requirement.
"""),
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)

class SQLDBMANIPULATION(BaseModel):
    user_query: str = Field(description='User question which will be translated to a Data Manipulation SQL Query and will be executed on the underlying database')


class SQLDBMANIPULATIONTool(BaseTool):
    name = "sql_db_manipulation"
    description = "Use this tool to convert and execute DML queries given the user question"
    args_schema: type[SQLDBMANIPULATION] = SQLDBMANIPULATION
    sql_dml_chain: Runnable
    def _run(
        self, user_query: str
    ) -> str:
        """Use the tool."""
        query = sql_dml_chain.invoke({"user_question":user_query})
        db._execute(query)

tools = [SQLDBMANIPULATIONTool(sql_dml_chain = sql_dml_chain)]
llm_with_tools = ChatOpenAI().bind(functions=[format_tool_to_openai_function(t) for t in tools])
agent = (
    {
        "input": lambda x: x["input"],
        "agent_scratchpad": lambda x: format_to_openai_function_messages(
            x["intermediate_steps"]
        ),
    }
    | agent_prompt
    | llm_with_tools
    | OpenAIFunctionsAgentOutputParser()
)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input":"CREATE the invoices table with columns id,values"})

```

**Comment by jyoti194** [comment]
Hi MD Mohtashim,
thank you for the code, i see its specifically for modifying the DB, but i
have created a chatbot for interacting with the DB, so can i integrate this
code with it?

**Comment by keenborder786** [comment]
Yes you can but be careful since this chatbot can manipulate records in your DB.

**Comment by jyoti194** [comment]
Hi @dosubot, 
I'm able to modify the code with AgentExecutor but not with the SQLDatabaseChain
AgentExectore code
def chat(question):

    llm = OpenAI(temperature=0)
    tools = load_tools(["llm-math"], llm=llm)

    agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)


    
    db = SQLDatabase(engine, view_support=True, include_tables=['HRMSGPTAutomation'])
    llm = ChatOpenAI(model_name="gpt-3.5-turbo",
                    temperature=0, 
                    max_tokens=1000)

    # toolkit = SQLDatabaseToolkit(db=db)
    toolkit = SQLDatabaseToolkit(db=db, llm=llm)
    agent_executor = create_sql_agent(
        llm=llm,
        toolkit=toolkit,
        verbose=True,
        reduce_k_below_max_tokens=True,
    )

    mrkl = initialize_agent(
        tools,
        ChatOpenAI(temperature=0),
        agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True,
        handle_parsing_errors=True,
    )

    return agent_executor.run(question)

# answer= chat("modify shilpi deshmukh  name as Shilpi")
# answer= chat(" add a row with employee name Preeti, employee id AD2302011, contact number 959100712")
# answer= chat(" add designation of Preeti as software eng bngl")

answer= chat(" delete the row with employee name preeti")
# answer= chat("what are Rathakrishnan Ganesan designation")
print(answer) 

QLDatabaseChain code
def chat(question, sql_format):
    # Initialize variables
    model_name="gpt-3.5-turbo-16k"
    db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT', 'emp_attendance_query'])
    # db = SQLDatabase(engine, include_tables=[ 'emp_attendance_query'])
    llm = ChatOpenAI(temperature=0, verbose=False, model=model_name)
    answer = None
    
    # Check if the input is in SQL format or not
    if sql_format == False:
        # If not in SQL format, create a database chain and run the question
        db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
        answer = db_chain.run(question)
    else:
        # If in SQL format, create a database chain and get the SQL query
        db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, return_sql=True)
        sql_query = db_chain.run(question) 
        print("SQLQuery: " + str(sql_query))
        
        # Execute the SQL query and store the results in a DataFrame
        result_df = pd.read_sql(sql_query, engine)
        
        # Check if the DataFrame is empty and return a message if no results are found
        if result_df.empty:
            return "No results found"
        
        # Convert the DataFrame to a dictionary
        answer = result_df.to_dict()
        # result_df.plot(kind='bar', x='category', y='count')
        # result_df.plot(kind='bar')
        # # plt.pie(result_df)
        # plt.show()

    return answer
    
# Define a function named chain1 that uses the chat function without SQL format
def chain1(question):
    text = chat(question, False)
    return text

# Define a function named chain2 that uses the chat function with SQL format
def chain2(question):
    query = chat(question, True)
    return query

# chain2("give a count of employess joined in 2023 in each month")
# print(chain2)
chain1("add a row with employee name Preeti, employee id AD2302011, contact number 959100712")
print(chain1)

can we be able to integrate the agentExecutor or the one shared by [keenborder786] and SQLDatabaseChain, to obtain the output with chain and modify with agent?

**Comment by jyoti194** [comment]
hi @dosubot, 
here i'm trying to create plots using langchain, below is the code
import dotenv
import pandas as pd
from langchain import LLMChain, OpenAI, SQLDatabase
from langchain_experimental.sql import SQLDatabaseChain
from langchain.agents import (AgentExecutor, Tool, ZeroShotAgent,
                              initialize_agent, load_tools)

dotenv.load_dotenv(override=False)
from langchain.chat_models import ChatOpenAI 
from secret_key import openapi_key 
import os
os.environ['OPENAI_API_KEY'] = openapi_key
from urllib.parse import quote_plus
server_name = "########"
database_name = "#####"
username = "#####"
password = "######"
encoded_password = quote_plus(password)
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

import pandas as pd
import sqlalchemy as sal 
from sqlalchemy import create_engine

engine = create_engine(connection_uri)
model_name="gpt-3.5-turbo-16k"
db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT'])
llm = ChatOpenAI(temperature=0, verbose=False, model=model_name)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, return_direct=True)

from langchain_experimental.utilities import PythonREPL

# Add python_repl to our list of tools
# tools = load_tools(["python_repl"])
tools = []  # Create an empty list for tools

# Instantiate PythonREPL tool
python_repl_tool = PythonREPL()

# Define our voter_data tool

# Set a description to help the LLM know when and how to use it.
description = (
    "Useful for when you need to answer questions about voters. "
    "You must not input SQL. Use this more than the Python tool if the question "
    "is about voter data, like 'how many DEM voters are there?' or 'count the number of precincts'"
)

repl_tool = Tool(
    name="Data",  # We'll just call it 'Data'
    func=db_chain.run,
    description=description,
)

tools.append(repl_tool)

# Define tools
# tools = [PythonTool(), repl_tool]  # Use PythonTool
# Standard prefix
prefix = "Fulfill the following request as best you can. You have access to the following tools:"

# Remind the agent of the Data tool, and what types of input it expects
suffix = (
    "Begin! When looking for data, do not write a SQL query. "
    "Pass the relevant portion of the request directly to the Data tool in its entirety."
    "\n\n"
    "Request: {input}\n"
    "{agent_scratchpad}"
)

# The agent's prompt is built with the list of tools, prefix, suffix, and input variables
prompt = ZeroShotAgent.create_prompt(
    tools, prefix=prefix, suffix=suffix, input_variables=["input", "agent_scratchpad"]
)

# Set up the llm_chain
llm_chain = LLMChain(llm=llm, prompt=prompt)

# Specify the tools the agent may use
tool_names = [tool.name for tool in tools]
agent = ZeroShotAgent(llm_chain=llm_chain, allowed_tools=tool_names)

# Create the AgentExecutor
agent_executor = AgentExecutor.from_agent_and_tools(
    agent=agent, tools=tools, verbose=True
)


request = "Show a bar graph visualizing the answer to the following question:" \
    "give a count of employess joined in 2023 in each month"
        #"What are the count employess who joined in 2023 ?"
          

agent_executor.run(request)

so here, instead of agents, can i use SQLDatabaseChains like in my previous code, i want to integrate it to the main extraction code?

**Comment by jyoti194** [comment]
> Here you go, I have construct a Agent who have a tool that can execute DML queries on your underlying SQL database.
> 
> ```python
> from langchain.sql_database import SQLDatabase
> from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder,PromptTemplate
> from langchain.tools import BaseTool
> from langchain.tools.render import format_tool_to_openai_function
> from langchain.schema.runnable import Runnable,RunnableLambda,RunnableParallel
> from langchain.chat_models import ChatOpenAI
> from langchain.agents.format_scratchpad import format_to_openai_function_messages
> from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser
> from langchain.agents import AgentExecutor
> from pydantic import BaseModel, Field
> import os
> 
> os.environ['OPENAI_API_KEY'] = 'sk-xxxxxxxxxxxx'
> SQL_DML_CHAIN_PROMPT = """You are expert in SQLITE. Your main objective is to construct Data manipulation SQLITE query give the
> user question: {user_question}.
> 
> You need to construct the Data manipulation SQLITE query for the following Database Schema:
> {table_info}
> 
> Only Output the final SQL-Query and nothing else.
> 
> SQL-Query:"""
> 
> prompt = PromptTemplate(template = SQL_DML_CHAIN_PROMPT,input_variables = ['user_question','table_info'])
> db =  SQLDatabase.from_uri("sqlite:///chinook.db")
> sql_dml_chain = RunnableParallel ({"user_question":lambda x:x["user_question"],
>                  "table_info":lambda _: db.get_table_info()}) |\
>                 prompt |\
>                 ChatOpenAI().bind(stop='SQL-Query:') |\
>                 RunnableLambda(lambda x:x.content.strip().replace('```sql',''))
> agent_prompt = ChatPromptTemplate.from_messages(
>     [
>         ("system", """
>         You are expert in SQL whose main objective is to mainpulate the Chinook Database for which you have
>         been given access. You can use the tool `sql_db_manipulation` to interact with  Chinook Database and
>         mainpulate the database as per the user requirement.
> """),
>         ("user", "{input}"),
>         MessagesPlaceholder(variable_name="agent_scratchpad"),
>     ]
> )
> 
> class SQLDBMANIPULATION(BaseModel):
>     user_query: str = Field(description='User question which will be translated to a Data Manipulation SQL Query and will be executed on the underlying database')
> 
> 
> class SQLDBMANIPULATIONTool(BaseTool):
>     name = "sql_db_manipulation"
>     description = "Use this tool to convert and execute DML queries given the user question"
>     args_schema: type[SQLDBMANIPULATION] = SQLDBMANIPULATION
>     sql_dml_chain: Runnable
>     def _run(
>         self, user_query: str
>     ) -> str:
>         """Use the tool."""
>         query = sql_dml_chain.invoke({"user_question":user_query})
>         db._execute(query)
> 
> tools = [SQLDBMANIPULATIONTool(sql_dml_chain = sql_dml_chain)]
> llm_with_tools = ChatOpenAI().bind(functions=[format_tool_to_openai_function(t) for t in tools])
> agent = (
>     {
>         "input": lambda x: x["input"],
>         "agent_scratchpad": lambda x: format_to_openai_function_messages(
>             x["intermediate_steps"]
>         ),
>     }
>     | agent_prompt
>     | llm_with_tools
>     | OpenAIFunctionsAgentOutputParser()
> )
> 
> agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
> agent_executor.invoke({"input":"CREATE the invoices table with columns id,values"})
> ```

Hi @keenborder786 
I'm using this code but im facing an issue, while 

Invoking: `sql_db_manipulation` with `{'user_query': "UPDATE PAY_transaction_settingallow SET [euid] = (SELECT [employeeEuid] FROM employee_details WHERE [employeeName] = 'H#######'), [alw_id] = (SELECT [alw_id] FROM pay_mst_allowance WHERE [alw_desc] = 'Incentive - bt'), [amount] = 2001, [createDate] = GETDATE(), [effect_date] = '2024-03-01', [to_date] = '2024-03-31'"}` 

it generating a proper query where it's taking the proper [createDate] = GETDATE() 

but while executing the query ie. db._execute(query) its taking as 

[SQL: UPDATE PAY_transaction_settingallow
SET [euid] = (SELECT [employeeEuid] FROM employee_details WHERE [employeeName] = 'H#######'),
[alw_id] = (SELECT [alw_id] FROM PAY_mst_allowance WHERE [alw_desc] = ' Incentive - bt'),
[amount] = 2001,
[createDate] = DATETIME('now'),
[effect_date] = '2024-03-01',
[to_date] = '2024-03-31';]

because of which i'm gettiing error as "'DATETIME' is not a recognized built-in function name."

"sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'DATETIME' is not a recognized built-in function name."

can you please let me know how to solve this
