### ISSUE TITLE
AWS bedrock Claude v2 SQLDatabaseChain produces comments before the SQL Query

### ISSUE THREAD

**Issue by sbisen** [langchain-ai/langchain#15283]
### System Info

langchain Version: 0.0.348
python Version: Python 3.9.18
OS: Mac OS M2 (Ventura 13.6.2)

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

llm = Bedrock(
    credentials_profile_name= os.environ.get('profile_name'),
    model_id="anthropic.claude-v2",
    model_kwargs={"temperature": 0.1},
    endpoint_url="https://bedrock-runtime.us-east-1.amazonaws.com",
    region_name="us-east-1",
    verbose=True
)

db = SQLDatabase.from_uri(snowflake_url, sample_rows_in_table_info=3, include_tables=["table_name"])
output= SQLDatabaseChain.from_llm(
        llm,
        db, 
        prompt=few_shot_prompt,
        return_intermediate_steps=True,
        )
Gives the following error:
Error: syntax error line 1 at position 0 unexpected '**The**'.
[SQL: **The** query looks good to me, I don't see any of the common mistakes listed. Here is the original query again: SELECT *
FROM table]

### Expected behavior

the output should only produce SQL query outputted plainly, should not surround it in quotes or any comments prior to the SQL Query 
Desired output: 
[SQL: SELECT *
FROM table]

**Comment by sbisen** [comment]
@dosu-bot my question is specific to AWS bedrock's Claude v2 model and Snowflake SQL

**Comment by sbisen** [comment]
I am importing:
from langchain_experimental.sql import SQLDatabaseChain
And
from langchain.sql_database import SQLDatabase
Please explain in simple steps how to make these change after the import

**Comment by sbisen** [comment]
@dosu-bot the above solution worked but now gives comments after the SQL query (instead of before the SQL). How to remove any comments before and after the SQL Query and only return SQL query

**Comment by sbisen** [comment]
@dosu-bot the above changes in get_table_info did not work and the  SQL Query generated is still surrounded by comments

**Comment by sbisen** [comment]
@dosu-bot suggest modification in the 'get_table_info' function to remove the comments pre & post the SQL query. Only output the SQL query without any comments around it

**Comment by sbisen** [comment]
@dosu-bot suggest modification SQLDatabaseChain to remove the comments prefix & postfix the SQL query. Only output the SQL query without any comments around it for claude v2 model in AWS bedrock

**Comment by sbisen** [comment]
@dosu-bot the above approach od post processing does not work because comments by claude can start with anything letter (not just "The"). Is there any way to turn off the comments and only get SQL

**Comment by sbisen** [comment]
@dosu-bot postprocessing will not work because SQL output is just an intermediate step and the final output is in natural language. Also it is not possible to generalize the post processing because comments from claude model can start from any word

**Comment by udaysai50** [comment]
@sbisen I am also using claude v2 model from Bedrock and the only way to eliminate comments before SQL query is to use ```
`use_query_checker=False`
local_chain = SQLDatabaseChain.from_llm(bedrock_llm, db, prompt=few_shot_prompt, use_query_checker=False, 
                                        verbose=True, return_sql=False)
```

But still I am facing some intermittent errors.
