### ISSUE TITLE
Using chipper model with hi_res strategy gives an error

### ISSUE THREAD

**Issue by samer1977** [langchain-ai/langchain#15300]
### System Info

Hi,
I'm new to this, so I apologize if my lack of in-depth understanding to how this library works caused to me raise a false alarm. Im trying to an ocr on pdf image using the  UnstructuredPDFLoader, Im passing the following args:
`
loader = UnstructuredPDFLoader(file_path="myfile.pdf", mode="elements",include_page_break=True,infer_table_structure=False,languages=["Eng"],strategy="hi_res",include_metadata=True,model_name="chipper")`

However I keep getting the following error:

```
OSError: unstructuredio/chipper-v3 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
```

Not sure what Im missing here ?
Thanks

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.document_loaders import UnstructuredPDFLoader
loader = UnstructuredPDFLoader(file_path="myfile.pdf", mode="elements",include_page_break=True,infer_table_structure=False,languages=["Eng"],strategy="hi_res",include_metadata=True,model_name="chipper")
                           

documents = loader.load()

print(documents)
```

### Expected behavior

I should be getting the metadata similar to when I use other models like "yolox" which works fine. I heard chipper model is much better so I wanted to try it.

**Comment by majiayu000** [comment]
Hi, the "chipper" model is no longer public.

You can only use api to use the chipper while you need a api (maybe need some money?)for unstructured website.

Here is the code:
```
from unstructured.partition.api import partition_via_api


elements = partition_via_api(
    filename="my.pdf",
    strategy="hi_res",
    pdf_infer_table_structure=True,
    languages=["por"],
    hi_res_model_name="chipper",
    api_key="xxxx", # get your API in the unstructured site
    )
