### ISSUE TITLE
Add common mulit model support 

### ISSUE THREAD

**Issue by calvinweb** [langchain-ai/langchain#15316]
### Feature request

Presently, JSON can be utilized to enable the multimodal capability of GPT-4 series models within ChatOpenAI and OpenAI. However, this functionality lacks portability.

### Motivation

Using multimodal approaches lacks portability, and GPT-4 isn't the sole model employing multimodal capabilities. Therefore, it becomes imperative to establish a standardized method for accessing various multimodal models.

### Your contribution

I may submit a PR about this if I have spare time

**Comment by itsritiksingh** [comment]
Hi, @calvinweb 
can you explain in brief how we can achieve such outcome.
I would like to contribute on this.

**Comment by calvinweb** [comment]
> Hi, @calvinweb can you explain in brief how we can achieve such outcome. I would like to contribute on this.

I think it should like this:
```
print("tell me what is on the image"+Image.from_url("http"))
# -> <TextImageMessge at xxxxxxx>
```
done this via  `__iadd__` magic method
