### ISSUE TITLE
Self query retriever with Vector Store type <class 'langchain_community.vectorstores.faiss.FAISS'> not supported.

### ISSUE THREAD

**Issue by XariZaru** [langchain-ai/langchain#15331]
### System Info

I've been trying to create a self query retriever so that I can look at metadata field info. This issue comes up. Should I be using another vector store to make this work? I can only really work with FAISS. I cannot use ChromaDB since my Python environment is limited to a previous version.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a FAISS Vectorstore DB
2. Create a metadata_field_info object and pass it to a SelfQuery object
3. Create LLM with this retriever

```python
embedding_function = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY, model="text-embedding-ada-002")
    
    db = FAISS.load_local(input_dir + "/" + "storage/deploy/faiss-db", embedding_function)#, distance_strategy="COSINE", normalize_L2 = True)
    # retriever = KNNRetriever(vectorstore=db)
    
    llm = ChatOpenAI(
        temperature=0,
        verbose=False,
        openai_api_key=key,
        model_name="gpt-3.5-turbo"
    )       

    metadata_field_info = [
        AttributeInfo(
            name="source",
            description="The document this chunk is from.",
            type="string",
        ),
        AttributeInfo(
            name="origin",
            description="The origin the document came from. Comes from either scraped websites like TheKinection.org, Kinecta.org or database files like Bancworks. Bancworks is the higher priority.",
            type="string",
        ),
        AttributeInfo(
            name="date_day",
            description="The day the document was uploaded.",
            type="integer",
        ),
        AttributeInfo(
            name="date_month",
            description="The month the document was uploaded.",
            type="integer",
        ),
        AttributeInfo(
            name="date_year",
            description="The year the document was uploaded.",
            type="integer",
        ),
    ]

    # retriever = db.as_retriever(search_type="similarity", search_kwargs={'k': 6}, metadata_field_info=metadata_field_info)

    retriever = SelfQueryRetriever.from_llm(
        llm, db, "Information about where documents originated from and when they were published.", metadata_field_info, verbose=True
    )
```

### Expected behavior

Successfully create a SelfQuery retriever with FAISS vector store.

**Comment by keenborder786** [comment]
@XariZaru Unforunately FAISS  is currently not supported in `SelfQueryRetriever` but I am going to create a PR to integrate FAISS but for that you will have to wait.

**Comment by keenborder786** [comment]
Update: After Researching on the internet I realized FAISS does not have a internal query language like Chroma or Vectara therefore `SelfQueryRetriever` does not support FAISS. Remeber the flow of SelfQueryRetriever is as follow:

User_Question ---> LLM_Call --> Query_Language for Vector DB ---> Query_Executed ---> Document Returned.

Since the third part is missing, using FAISS with `SelfQueryRetriever` does not make any sense.

**Comment by keenborder786** [comment]
@XariZaru  I have created a PR for it's support.

**Comment by XariZaru** [comment]
I swapped to ChromaDB and Pinecone.

**Comment by Kags-09** [comment]
@keenborder786 Same Issue for Milvus

ValueError: Self query retriever with Vector Store type <class 'langchain_milvus.vectorstores.milvus.Milvus'> not supported.
