### ISSUE TITLE
DOC: Summarization 'map_reduce' - Can't load tokenizer for 'gpt2'

### ISSUE THREAD

**Issue by analyticsinsights** [langchain-ai/langchain#15347]
### Issue with current documentation:

The [documentation](https://python.langchain.com/docs/use_cases/summarization) describes the different options for summarizing a text, for longer texts the 'map_reduce' option is suggested. It is mentioned further under 'Go deeper' that it is possible to use different LLMs via the `llm` parameter. This seems to work well using the code below with the `chain_type='stuff'` parameter and, in particular, using a local model (in the example below [this model](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF) is used). 

```
from langchain.document_loaders import PyPDFLoader
from langchain.llms import CTransformers
from langchain.chains.summarize import load_summarize_chain

# load a PDF-file
loader = PyPDFLoader("C:/xyz.pdf")
docs = loader.load()

# use a local LLAMA2 model
llm = CTransformers(model='./models/llama-2-7b-chat.Q5_K_M.gguf', model_type='llama', config={'context_length': 4096, 'max_new_tokens': 256, 'temperature': 0}, local_files_only=True)

# summarise the text (this works only if it fits into the context length of ~4000 tokens)
chain = load_summarize_chain(llm, chain_type="stuff")
chain.run(docs)
```

However, surprisingly, it returns the following error when using the `chain_type='map_reduce'` parameter: 'OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.'

The suggestion [mentioned in this issue on Github](https://github.com/langchain-ai/langchain/issues/9273) doesn't work for the local model used above. It would be great to have more specific information in the LangChain documentation on (1) how to perform text summarization with LangChain using different LLMs, and (2) specifically for using local models that don't require an internet connection and/or require gpt2. Since the above code works with the parameter `chain_type='stuff'` but not with the parameter `chain_type='map_reduce'`, it would be important to explain what happens under the hood so users can make this work for local models.

**Comment by analyticsinsights** [comment]
Not sure how the bot's comment helps. Could someone please take a look?

The code below is another example which fully reproduces the error. The pipeline points to a specific tokenizer and model (using [t5-small](https://huggingface.co/t5-small) here as an example), but when running `summarization_chain.run(docs[20:23])` LangChain still tries to download the gpt2 model to work with that (as mentioned in my previous post, this appears not to happen with `chain_type='stuff'` but only with `chain_type='map_reduce'`). 

**The error message 'OSError: Can't load tokenizer for 'gpt2'...' is created when the internet connection is switched off before executing the last line of code. With an internet connection, LangChain downloads the gpt2 model and uses it to perform the text summarization task.**

The idea behind the code below is to perform a summarization of long texts using a specific model/tokenizer combination downloaded beforehand, so that the code can be executed offline. 

How can this be achieved? 

```
import requests
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline
from langchain.llms import HuggingFacePipeline
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains.summarize import load_summarize_chain

url = "https://www.gutenberg.org/cache/epub/71224/pg71224.txt"
response = requests.get(url)
if response.status_code == 200:
    data = response.text

text_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n"], chunk_size=1000, chunk_overlap=200)
docs = text_splitter.create_documents([data])

tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = AutoModelForSeq2SeqLM.from_pretrained("t5-small")

pipe_summary = pipeline("summarization", model=model, tokenizer=tokenizer)
llm = HuggingFacePipeline(pipeline=pipe_summary)

# if the internet connection is switched off here, then the following rows produce an error since the attempt to download the gpt2-model from Huggingface fails
summarization_chain = load_summarize_chain(llm=llm, chain_type='map_reduce')
summarization_chain.run(docs[20:23])
```

**Comment by analyticsinsights** [comment]
> It seems like this issue requires a deeper look, @baskaryan could you please lend your expertise?

Any reactions?

**Comment by AhmadHakami** [comment]
any updates?

**Comment by jsxyhelu** [comment]
any updates?why?

**Comment by YoloZyk** [comment]
any solusions? help!

**Comment by CVer2022** [comment]
This problem seems to have been encountered a long time ago, and I did not expect to find the answer today

**Comment by CVer2022** [comment]
This question seems to have been encountered a long time ago, but it is still unresolved and relevant

**Comment by SubrataSarkar32** [comment]
Replace
`llm = HuggingFacePipeline(pipeline=pipe_summary)`
with
`llm = HuggingFacePipeline(model_id="google-t5/t5-small",pipeline=pipe_summary, model_kwargs:{"pretrained_model_name_or_path":"google-t5/t5-small"})` 

OR

if you are using locally downloaded model files
`llm = HuggingFacePipeline(model_id="google-t5/t5-small",pipeline=pipe_summary, model_kwargs:{"pretrained_model_name_or_path":"/you/local/downloaded/path/models--google-t5--t5-small", "local_files_only": True})` 

This is happening because in the file `https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/llms/huggingface_pipeline.py`  the following value is set `DEFAULT_MODEL_ID = "gpt2"` and it is not getting updated.

**Comment by Civel-1** [comment]
Still encountering this problem when working with custom LLM class that is a openapi compatible vLLM server. 
Any lead?

**Comment by Enteee** [comment]
This happens because Ollama does not provide an tokenization API and langchain then falls back to trying openai calls.

You can avoid this by implementing a custom tokenizer and supplying it as `Ollama`'s `custom_get_token_ids` parameter. I do something like this in my code:


```python
    tokenizer = Lama3Tokenizer(model_path=str(LLAMA3_TOKENIZER_MODEL_PATH.resolve()))

    # Ollama does not provide an API for getting token ids before quering the llm
    # ref: https://github.com/ollama/ollama/issues/1716
    # This is why we here implement llama3 tokenization using copy&pasted
    # source code from the llama3 repository
    def llama3_get_token_ids(text: str) -> list[int]:
        return tokenizer.encode(s=text, bos=False, eos=False)


   llm = Ollama(
        ...
        custom_get_token_ids=llama3_get_token_ids,
    )
```

**Comment by Enteee** [comment]
this should be reopened...
