### ISSUE TITLE
ImportError: cannot import name 'GPT4ALL' from 'langchain.llms'

### ISSUE THREAD

**Issue by rkuo2000** [langchain-ai/langchain#15362]
### System Info

langchain 0.0.353
pygpt4all 1.1.0

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.llms import GPT4ALL, LlamaCpp

### Expected behavior

ImportError: cannot import name 'GPT4ALL' from 'langchain.llms' (/home/rkuo/.local/lib/python3.10/site-packages/langchain/llms/__init__.py)

**Comment by itsritiksingh** [comment]
@rkuo2000 

```
from langchain.llms.gpt4all import GPT4All
from langchain.llms.llamacpp import LlamaCpp
```

**Comment by rkuo2000** [comment]
> @rkuo2000
> 
> ```
> from langchain.llms.gpt4all import GPT4All
> from langchain.llms.llamacpp import LlamaCppfrom langchain.llms.gpt4all import GPT4All
from langchain.llms.llamacpp import LlamaCpp
> ```

gguf_init_from_file: invalid magic characters lmgg.
gguf_init_from_file: invalid magic characters lmgg.
gguf_init_from_file: invalid magic characters lmgg.
Traceback (most recent call last):
  File "/home/rkuo/llm/llm-langchain-wikipedia.py", line 26, in <module>
    llm = GPT4All(model=model_path, backend='gptj', callbacks=callbacks, verbose=False)
  File "/home/rkuo/.local/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "/home/rkuo/.local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Unable to instantiate model: code=95, Model format not supported (no matching implementation found) (type=value_error)
