### ISSUE TITLE
ValueError: 'lib/python3.11/site-packages/langchain/agents/agent_toolkits' is not in the subpath of 'lib/python3.11/site-packages/langchain_core' OR one path is relative and the other is absolute.

### ISSUE THREAD

**Issue by BrodyChung** [langchain-ai/langchain#15370]
### System Info

MacOS 14.0, Jupiter with Python 3.11.6

 (base) ➜  llm-env pip show langchain    
Name: langchain
Version: 0.0.353
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /lib/python3.11/site-packages
Requires: aiohttp, dataclasses-json, jsonpatch, langchain-community, langchain-core, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

when try to execute,
from langchain.agents.agent_toolkits import create_python_agent
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
from langchain.tools.python.tool import PythonREPLTool
from langchain.python import PythonREPL

Jupiter gave an error:
ValueError: 'lib/python3.11/site-packages/langchain/agents/agent_toolkits' is not in the subpath of 'lib/python3.11/site-packages/langchain_core' OR one path is relative and the other is absolute.

### Expected behavior

Import agent related thing correctly.

**Comment by BrodyChung** [comment]
It's confusing, and it works when i installed langchain_experimental.
and changed,

from langchain_experimental.agents.agent_toolkits import create_python_agent
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
from langchain_experimental.tools.python.tool import PythonREPLTool
from langchain.python import PythonREPL

Thank you!!

**Comment by ypearson** [comment]
I had this bug too

**Comment by artyomboyko** [comment]
> It's confusing, and it works when i installed langchain_experimental. and changed,
> 
> from langchain_experimental.agents.agent_toolkits import create_python_agent from langchain.agents import load_tools, initialize_agent from langchain.agents import AgentType from langchain_experimental.tools.python.tool import PythonREPLTool from langchain.python import PythonREPL
> 
> Thank you!!

Thank you. Today 11.07.2025 and need some edits:

```
from langchain_experimental.agents.agent_toolkits import create_python_agent
from langchain.agents import load_tools, initialize_agent
from langchain.agents import AgentType
from langchain_experimental.tools.python.tool import PythonREPLTool
from langchain_experimental.utilities import PythonREPL
from langchain.chat_models import ChatOpenAI
```
