### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.vectorstores.neo4j_vector'

### ISSUE THREAD

**Issue by casrhub** [langchain-ai/langchain#15383]
### Issue with current documentation:

from langchain.vectorstores.neo4j_vector import Neo4jVector

ModuleNotFoundError: No module named 'langchain.vectorstores.neo4j_vector'

### Idea or request for content:

The existing documentation for the Neo4J Vector Index incorrectly indicates the use of "Neo4jVector" from the "langchain.vectorstores" module. However, it appears that there is no implementation of "Neo4jVector" within the Vector stores.

**Comment by chyroc** [comment]
try:

```
from langchain_community.vectorstores.neo4j_vector import Neo4jVector
```
