### ISSUE TITLE
DynamoDBChatMessageHistory saved Human Message duplicate

### ISSUE THREAD

**Issue by JiaTingYefei** [langchain-ai/langchain#15385]
### System Info

Langchain version: 0.0.351
boto3==1.34.3
Python version: 3.11.7

### Who can help?

I use DynamoDBChatMessageHistory as the conversation_history,  seems duplicate Human messages saved to DynamoDB table every time, AI message saved once.
Here is the duplicate messages:

![image](https://github.com/langchain-ai/langchain/assets/13569268/a395a097-47b8-429a-8d6e-3d8eaa9e5d0a)

Below is my code: 

`    def ask_stream(
        self,
        input_text: str,
        conversation_history: ConversationBufferMemory = ConversationBufferMemory(
            ai_prefix="Assistant"
        ),
        verbose: bool = False,
        **kwargs,
    ):
        """Processes a stream of input by invoking the engine.

        Parameters
        ----------
        conversation_history: ConversationBufferMemory
            The conversation history
        input_text: str
            The input prompt or message.
        verbose: boolean
            if the langchain shall show the detailed logging
        kwargs: dict
            Additional keyword arguments to pass to the engine.
            For example, you can pass in temperature to control the model's
            creativity.
        Returns
        -------
        str
            The response generated by the engine.

        Raises
        ------
        Any exceptions raised by the engine.
        """

        temp_stop = kwargs.get("stop", self.stop)

        template = """The following is a friendly conversation between a human and an AI."""
        PROMPT = PromptTemplate(input_variables=["history", "input"], template=template)

        chain = ConversationChain(
            llm=self.engine,
            memory=conversation_history,
            verbose=verbose,
            prompt=PROMPT,
        )

        return chain.predict(input=input_text, stop=temp_stop)

`

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Start a new conversation with DynamoDBChatMessageHistory as memory.

### Expected behavior

Each HumanMessage should be saved once in DynamoDB table.

**Comment by JiaTingYefei** [comment]
I figured out the reason, is not a bug.

**Comment by AlcebiadesFilho** [comment]
What did you do to solve it, have you ever been in a situation where you have to edit these messages, putting timestamps for example?
