### ISSUE TITLE
Filter conditions are discarded when using multiple filter conditions in similarity_search_with_relevance_scores

### ISSUE THREAD

**Issue by Lue-C** [langchain-ai/langchain#15417]
### System Info

Windows 10
Python 3.11.5
langchain==0.0.331

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I want to do a similarity search on a vectorstore created beforehand and use multiple filtering conditions. The relevant part of the code is as follows:

```
from langchain.vectorstores import Chroma
from langchain.embeddings import SentenceTransformerEmbeddings
import chromadb

db_path = "my_db"

embeddings = SentenceTransformerEmbeddings(cache_folder='intfloat/multilingual-e5-large')
chroma_client = chromadb.PersistentClient(path=db_path)
    
db= Chroma(persist_directory=db_path, embedding_function=embeddings, client=chroma_client)

query = "My query"

filtered = db.similarity_search_with_relevance_scores(k=5, query=query, filter={"key1":value1, "key2":value2})
```

When using one filtering condition like
```
filtered = db.similarity_search_with_relevance_scores(k=5, query=query, filter={"key1":value1})
```
the filtering condtion is applied and it works fine. But when using multiple conditions, neither of the conditions is applied.

How can I use multiple filtering conditions?

### Expected behavior

I would expect, that both conditions are applied either connected by an "and" or an "or".

**Comment by sree1658** [comment]
@ dosubot can you help me with a query for 3 keys -  2keys with "and" and one key with "or"
