### ISSUE TITLE
FakeStreamingListLLM.astream() yields strings while ChatOpenAI yields AIMessageChunk

### ISSUE THREAD

**Issue by manuelmorales** [langchain-ai/langchain#15426]
### System Info

```
langchain==0.0.352
langchain-community==0.0.6
langchain-core==0.1.3
```

Python `3.12.1` running inside Docker from `python:3.12-bookworm` on Linux.

### Who can help?

I have a FastAPI app that streams the output of an LLM. The app uses `langchain.chat_models.ChatOpenAI` at runtime, but during test I mock the LLM with `langchain.llms.fake.FakeStreamingListLLM`. However, when my app calls `.astream()` on each of them I'm getting different results:

- While `ChatOpenAI` yields instances of `AIMessageChunk`...
- `FakeStreamingListLLM` yields instances of strings.

This mismatch between the fake and the real class makes the fake unsuitable for some mocking purposes as the interface of `AIMessageChunk` is different from a `str`.

@baskaryan @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

See an snippet below on how to reproduce the output of strings within `ipython`:

```python
from langchain.llms.fake import FakeStreamingListLLM
import asyncio

async def pp(llm):
    async for chunk in llm.astream('some input'):
        yield(f"{type(chunk)}: {chunk}")

async def consume():
    results = []
    async for item in pp(FakeStreamingListLLM(responses=['a'])):
        results.append(item)
    return results

asyncio.run(consume())

# OUTPUT:
["<class 'str'>: a"]
```

### Expected behavior

I'd expect `FakeStreamingListLLM` to return instances of `AIMessageChunk` as the real chat model.

**Comment by chyroc** [comment]
try:

```python
import asyncio

- from langchain.llms.fake import FakeStreamingListLLM
+ from langchain_community.chat_models import FakeListChatModel


async def pp(llm):
    async for chunk in llm.astream('some input'):
        yield (f"{type(chunk)}: {chunk}")


async def consume():
    results = []
-    async for item in pp(FakeStreamingListLLM(responses=['a'])):
+    async for item in pp(FakeListChatModel(responses=['a'])):
        print(item, type(item))
        results.append(item)
    return results


asyncio.run(consume())
```

**Comment by manuelmorales** [comment]
That worked perfectly @chyroc . Than you very much! 

I don't know if you intend to close this issue as there is a working solution, or do you intend to leave it open to update the behavior of`FakeStreamingListLLM`. Feel free to close it whenever you like.
