### ISSUE TITLE
Accessing Gemini though Vertex AI SDK

### ISSUE THREAD

**Issue by jaymon0703** [langchain-ai/langchain#15431]
### Feature request

Gemini API is not available in Canada, but i believe it is available through `vertexai.preview.generative_models` in pre-GA mode.

Would it be possible to add a feature using the Vertex AI SDK instead of Gemini API, which i assume is what it is using?

### Motivation

Canada access to Gemini through Langchain

### Your contribution

I could test?

**Comment by lkuligin** [comment]
You can try it with `VertexAI` model if you have a GCP project enabled.

Examples:
https://python.langchain.com/docs/integrations/llms/google_vertex_ai_palm#setting-up
https://python.langchain.com/docs/integrations/llms/google_vertex_ai_palm#multimodality

**Comment by jaymon0703** [comment]
Thank you @lkuligin that works...closing this issue
