### ISSUE TITLE
Allow bind variables in SQLDatabase queries

### ISSUE THREAD

**Issue by danb27** [langchain-ai/langchain#15449]
### Feature request

Allow using [bind parameters](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Connection.execute.params.parameters) in SQLDatabase's [run method](https://github.com/langchain-ai/langchain/blob/65afc13b8b53a1ca41a1a3998dad9eb8d83ca917/libs/community/langchain_community/utilities/sql_database.py#L426).

### Motivation

I don't see a way to use bind params in SQLDatabase queries.

### Your contribution

Happy to help out with a PR if needed (and if confirmed that this functionality doesn't exist and is wanted :) )

**Comment by jinuvarghese-cmd** [comment]
is binding possible now?
