### ISSUE TITLE
Support CHM files

### ISSUE THREAD

**Issue by DarkFox** [langchain-ai/langchain#15469]
### Feature request

Add document loader for CHM (Microsoft Compiled HTML Help) documents, possibly using pychm.

### Motivation

A lot of Windows applications provide documentation in the form of CHM files. Being able to directly load those into the language model, would greatly simplify the workflow of ingesting documentation.

### Your contribution

At this time, I'm unable to provide help with writing the loader.

**Comment by chyroc** [comment]
i will do for this, thanks.
