### ISSUE TITLE
Issue: How to customize prompt

### ISSUE THREAD

**Issue by pydaxing** [langchain-ai/langchain#15467]
### Issue you'd like to raise.

The following is the code I ran, referring to the official documentation. It looks like prompt_template is not effective and there is no explicit call of prompt_template in the code. How should I customize a prompt for initialize_agent.

```python
prompt_template = """  
Translate the sentence into English
{input}  
"""  
prompt_template = PromptTemplate.from_template(prompt_template)

llm = AzureOpenAI(
    model_name="gpt-4",
    engine="gpt-4"
)


@tool  
def get_word_length(word):  
    """get the length of a word"""  
    return len(word)  


tools = [get_word_length]  

agent = initialize_agent(  
    tools,  
    llm,  
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,  
    verbose=True,
    prompt = prompt_template
)  


answer = agent.run("今天天气怎么样")
```

The output is
```
> Entering new AgentExecutor chain...
This is a Chinese language query asking about the weather today. I don't have access to real-time weather data and besides, my provided actions are limited to getting the length of a word.
Final Answer: I'm sorry, I cannot answer that question.
```

**Comment by Yanni8** [comment]
https://github.com/langchain-ai/langchain/issues/4044#issuecomment-1585863266

Can you share a link to the documentation?

**Comment by Yanni8** [comment]
>
> ```python
> from langchain.agents.mrkl.prompt import FORMAT_INSTRUCTIONS, PREFIX, SUFFIX
> PREFIX = """Answer the following questions as best you can. You have access to the following tools:"""
> FORMAT_INSTRUCTIONS = """Use the following format:
> 
> Question: the input question you must answer
> Thought: you should always think about what to do
> Action: the action to take, should be one of [{tool_names}]
> Action Input: the input to the action
> Observation: the result of the action
> ... (this Thought/Action/Action Input/Observation can repeat N times)
> Thought: I now know the final answer
> Final Answer: the final answer to the original input question"""
> SUFFIX = """Begin!
> 
> Question: {input}
> Thought:{agent_scratchpad}"""
> 
> agent = initialize_agent(
>     agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
>     tools=tools,
>     llm=llm,
>     agent_kwargs={
>         'prefix':PREFIX,
>         'format_instructions':FORMAT_INSTRUCTIONS,
>         'suffix':SUFFIX
>     }
> )
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
He is right!
