### ISSUE TITLE
How long can I use Langchain to call the chatglm3 API

### ISSUE THREAD

**Issue by yoohhwz** [langchain-ai/langchain#15479]
### Feature request

Chatglm3 has added many new features compared to previous chatglm and chatglm2, which is particularly useful for users. So there will definitely be more user demands in using Langchain to build a knowledge base, and it's unclear how long it will take for the community to adapt.

chatglm3 github path ：https://github.com/THUDM/ChatGLM3

### Motivation

Chatglm3 has added many new features compared to previous chatglm and chatglm2, which is particularly useful for users. So there will definitely be more user demands in using Langchain to build a knowledge base, and it's unclear how long it will take for the community to adapt.

chatglm3 github path ：https://github.com/THUDM/ChatGLM3

### Your contribution

i am soryy.  i can not.

**Comment by DjangoPeng** [comment]
The ChatGLM class defined in LangChain can only be used for the API Server defined in ChatGLM2-6B (https://github.com/THUDM/ChatGLM2-6B/blob/main/api.py).

In ChatGLM3, this request method was abandoned and instead implemented a request method similar to OpenAI GPT API (https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/openai_api.py).

There is indeed some new compatibility work that needs to be promoted.

From an implementation perspective, ChatGLM2-6B is more like LLM in the abstraction of LangChain, while ChatGLM3-6B is closer to the Chat Model. Perhaps we can implement compatibility for multiple versions of the ChatGLM model according to this classification method.
