### ISSUE TITLE
S3FileLoader doesn't provide the way of passing extra (unstructured_kwargs) parameters

### ISSUE THREAD

**Issue by tivaliy** [langchain-ai/langchain#15472]
### System Info

python 3.11
langchain==0.0.350

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This is the current implementation of the `S3FileLoader` class (https://github.com/langchain-ai/langchain/blob/baeac23/libs/community/langchain_community/document_loaders/s3_file.py#L13-L30):

```
class S3FileLoader(UnstructuredBaseLoader):
    """Load from `Amazon AWS S3` file."""

    def __init__(
        self,
        bucket: str,
        key: str,
        *,
        region_name: Optional[str] = None,
        api_version: Optional[str] = None,
        use_ssl: Optional[bool] = True,
        verify: Union[str, bool, None] = None,
        endpoint_url: Optional[str] = None,
        aws_access_key_id: Optional[str] = None,
        aws_secret_access_key: Optional[str] = None,
        aws_session_token: Optional[str] = None,
        boto_config: Optional[botocore.client.Config] = None,
    ):
...
```

Existing `__init__()` method and current implementation of this class doesn't support extra arguments `unstructured_kwargs`. So there is no way to manage `partition` call through these extra arguments (https://github.com/langchain-ai/langchain/blob/baeac23/libs/community/langchain_community/document_loaders/s3_file.py#L126).

### Expected behavior

The implementation of `S3FileLoader` class should follow common approach used for all ancestors of `UnstructuredBaseLoader` which support passing through extra `**unstructured_kwargs` arguments to manage `partition` call in a more granular way.

**Comment by kulaone** [comment]
Any updates about this issue?
