### ISSUE TITLE
chat_history in ChatVectorDBChain needs specification on roles

### ISSUE THREAD

**Issue by bent-verbiage** [langchain-ai/langchain#1548]
Only after checking the code, did I realise that chat_history (in ChatVectorDBChain at least) assumes that every first message is a Human message, and the second one the Assistant, and actually assigns those roles as it is processing the history.

I think that concept (of automating the processing and assigning roles to the history) is great, but the assumption that every first message is from a Human, is not. At the very least, this can use some documentation.

**Comment by nathan-chappell** [comment]
For instance, you could add the type aliases 

```py
HumanChatHistoryMessage = str
MachineChatHistoryMessage = str
ChatHistoryItem = tuple[HumanChatHistoryMessage, MachineChatHistoryMessage]
ChatHistory = list[ChatHistoryItem]
```

Then there's a good chance that intellisense or "goto-definition" will expain everything
