### ISSUE TITLE
ModuleNotFoundError at import langchain.chains

### ISSUE THREAD

**Issue by yoch** [langchain-ai/langchain#15484]
### System Info

**Platform:**
Linux Ubuntu 22.04.1

**Python:** 
3.10.12

**Langchain:**
- langchain                0.0.353
- langchain-community      0.0.7
- langchain-core           0.1.5
- langsmith                0.0.77

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```py
from langchain.chains import *
```

### Expected behavior

I expect the import won't fail, but I got an exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain/chains/__init__.py", line 20, in <module>
    from langchain.chains.api.base import APIChain
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain/chains/api/base.py", line 11, in <module>
    from langchain.callbacks.manager import (
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
    from langchain_community.callbacks.aim_callback import AimCallbackHandler
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain_community/callbacks/__init__.py", line 24, in <module>
    from langchain_community.callbacks.manager import (
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain_community/callbacks/manager.py", line 14, in <module>
    from langchain_community.callbacks.tracers.wandb import WandbTracer
  File "/home/ubuntu/mychatassist-api/env/lib/python3.10/site-packages/langchain_community/callbacks/tracers/__init__.py", line 4, in <module>
    from langchain_core.tracers.langchain_v1 import LangChainTracerV1
ModuleNotFoundError: No module named 'langchain_core.tracers.langchain_v1'
```

**Comment by yoch** [comment]
FYI downgrade the 0.0.349 solved the issue for me.

Now I'm running with:
- langchain                0.0.349
- langchain-community      0.0.1
- langchain-core           0.0.13
- langsmith                0.0.77

**Comment by akash1118** [comment]
Hi @yoch  after downgrading it is throwing the error: ImportError: cannot import name 'ChainRun' from 'langchain_core.tracers.schemas

**Comment by hectorhernandezbabbel** [comment]
I am getting a similar error.

`from langchain.chains import create_tagging_chain`

and I get this Module Error

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-20-1e1c093c0704>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from langchain.chains import create_tagging_chain

5 frames
[/usr/local/lib/python3.10/dist-packages/langchain_community/callbacks/tracers/__init__.py](https://localhost:8080/#) in <module>
      2 
      3 from langchain_core.tracers.langchain import LangChainTracer
----> 4 from langchain_core.tracers.langchain_v1 import LangChainTracerV1
      5 from langchain_core.tracers.stdout import (
      6     ConsoleCallbackHandler,

ModuleNotFoundError: No module named 'langchain_core.tracers.langchain_v1'
```

**Comment by vikmaffia** [comment]
I've just ran into the same issue, downgrading to langchain-core 0.1.4 solved it:
pip install langchain-core==0.1.4

**Comment by mortanalexandru** [comment]
Same here, downgrading to 0.0.349 triggered another error:

**Comment by AemonAlgizAMA** [comment]
Just got the same error, downgrading the langchain core also resolved the error for me.

**Comment by smithi1** [comment]
Same error on import:

`from langchain.callbacks import get_openai_callback`

**Comment by mortanalexandru** [comment]
langchain==0.0.349 with a python notebook kernel restart fixed it for me. langchain-core also is 0.0.13

**Comment by ErikBorra** [comment]
Same here. downgrading to langchain-core==0.14 worked

**Comment by vyperid** [comment]
`from langchain import PromptTemplate, LLMChain`

ModuleNotFoundError: No module named 'langchain_core.tracers.langchain_v1'


Getting the same error :< can someone help please..?

**Comment by sweenejo** [comment]
Adding langchain-core==0.1.4 to requirements.txt worked for me.

**Comment by hamdan-27** [comment]
Downgrading to langchain==0.0.349 worked for me

**Comment by yoch** [comment]
@agola11 
This bug seems critical because it affects so many people, it seems strange to me that it wasn't caught by automated testing.
Could you take a look please?

**Comment by simjak** [comment]
<img width="1823" alt="image" src="https://github.com/langchain-ai/langchain/assets/20096648/43436b5b-61b4-4880-a218-c57e89875faa">

**Comment by Amankhan1009** [comment]
pip install langchain-classic
from langchain_classic.chains import create_retrieval_chain
