### ISSUE TITLE
PGVector method for HNSW

### ISSUE THREAD

**Issue by diegovalenzuelaiturra-latam** [langchain-ai/langchain#15496]
### Feature request

Provide a method to create the HNSW for the PGVector vectorstore

### Motivation

There is a similar method implemented for PGEmbedding but the embedding extension will be deprecated

### Your contribution

https://github.com/pgvector/pgvector?tab=readme-ov-file#hnsw

https://github.com/langchain-ai/langchain/blob/6e90b7a91bba16d84689d07d1016a941eddf4f64/libs/community/langchain_community/vectorstores/pgembedding.py#L184-L212

**Comment by YannikHinteregger** [comment]
Hi, did I get that right? Do you just want to add the functionality that is currently provided in `pgembedding.py` to be continuously present in another Class? 

I feel like I didn't quite get the issue. Can you please specify?

**Comment by pieterclaerhout** [comment]
I think the idea here is to allow the PGVector vectore store to be able to create a HNSW index. The PGEmbedding supported this, but afaik, it's no longer actively developed and they strongly suggest to migrate to pgvector ([see here](https://neon.tech/docs/extensions/pg_embedding#migrate-from-pg_embedding-to-pgvector).

As PGVector supports HNSW indexes, it would make sense to add a similar functionality to it.

**Comment by AmanRavan** [comment]
Any update on this?

**Comment by anmol-aidora** [comment]
Looking forward to have the ability to use HNSW indexing in pgvector
