### ISSUE TITLE
Can't Specify Top-K retrieved Documents in Multimodal Retrievers

### ISSUE THREAD

**Issue by mhendy25** [langchain-ai/langchain#15510]
### Issue you'd like to raise.

I've been playing around with the multimodal notebooks introduced in the [docs here.](https://blog.langchain.dev/semi-structured-multi-modal-rag/). However, the number of retrieved documents for every query is always 4. Specifically, for [cookbook 3](https://github.com/langchain-ai/langchain/blob/master/cookbook/Multi_modal_RAG.ipynb) the `limit` parameter is set to 6, but the number of retrieved documents is always 4 regardless of the value of `limit`. Is there another way to get `top_k`?

**Comment by sweetkane** [comment]
To limit the number of results when using the `MultiVectorRetriever` you can set 
```
myMultiVectorRetriever.search_kwargs['k'] = 2
```

**Comment by benjamin-meinhardt** [comment]
given that `_get_relevant_documents` has been deprecated since version` langchain-core==0.1.46: Use invoke instead,`

How can we use invoke to set number of results?
