### ISSUE TITLE
RuntimeError when calling asyncio.run() from a running event loop

### ISSUE THREAD

**Issue by hulk-yin** [langchain-ai/langchain#15523]
https://github.com/langchain-ai/langchain/blob/7a93356cbc5d89cc0f7dd746d8f1bb52666fd0f1/libs/community/langchain_community/document_loaders/chromium.py#L78C40-L78C44

Hello,

I encountered a RuntimeError when running the code that uses the AsyncChromiumLoader class. The error message is asyncio.run() cannot be called from a running event loop.

Here is the relevant part of the traceback:

```python
File ~/.../.venv/lib/python3.10/site-packages/langchain_community/document_loaders/chromium.py:78, in AsyncChromiumLoader.lazy_load(self)
     77 for url in self.urls:
---> 78     html_content = asyncio.run(self.ascrape_playwright(url))
```
It seems that asyncio.run() is being called inside a running event loop, which is not allowed. This happens in the lazy_load method of the AsyncChromiumLoader class.

I think the issue could be resolved by refactoring the code to ensure that asyncio.run() is not called from a running event loop. One possible solution could be to use await instead of asyncio.run() to run the self.ascrape_playwright(url) coroutine, and then use asyncio.run() to run the lazy_load method in the main program.

Could you please look into this issue and confirm if this is a bug or if there's something I'm missing in my usage of the AsyncChromiumLoader class?

Thank you for your time and help.

**Comment by keenborder786** [comment]
@hulk-yin having a look.

**Comment by keenborder786** [comment]
@hulk-yin I ran the following code and everything seems to be working:

```python


from langchain_community.document_loaders import AsyncChromiumLoader
loader = AsyncChromiumLoader(['https://en.wikipedia.org/wiki/LangChain',
                              'https://en.wikipedia.org/wiki/OpenAI'])
print(loader.load())
```

**Comment by keenborder786** [comment]
Can you make sure that you ran the following commands:

```bash
pip install pytest-playwright
playwright install

```

**Comment by laurauj** [comment]
Hello @keenborder786 , 

I'm also getting the same error from this thread. 

I've all my deps installed correctly but still. 

Currently I'm trying to use: https://python.langchain.com/docs/use_cases/web_scraping#scraping-with-extraction

**Comment by laurauj** [comment]
Actually, I just found another issue where if you run from a notebook you need to add this, as jupyter runs on its own loop. 

```
import nest_asyncio

nest_asyncio.apply()
```
