### ISSUE TITLE
INFORMATION_SCHEMA.VECTOR_INDEXES was not found in google big-query

### ISSUE THREAD

**Issue by rwaneyvin** [langchain-ai/langchain#15538]
### System Info

google-cloud-bigquery = "^3.14.1"
google-api-core = "^2.15.0"
google-cloud-core = "^2.4.1"
grpcio = "^1.60.0"
grpcio-tools = "^1.60.0"
langchain-google-genai = "^0.0.5"
langchain-core = "^0.1.5"
google-cloud-aiplatform = "^1.38.1"
langchain-community = "^0.0.8"

### Who can help?

when test the BigQuery Vector Search as website demo,https://python.langchain.com/docs/integrations/vectorstores/bigquery_vector_search
it caused Not found: Table xxx.xxx.INFORMATION_SCHEMA.VECTOR_INDEXES was not found in location US. in google big-query 

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

the procedures steps are in the page of https://python.langchain.com/docs/integrations/vectorstores/bigquery_vector_search
,official langchain demo page.

### Expected behavior

it was official langchain demo page. and result should be shown but error.
probably something went wrong with big-query, please help, thanks a lot!

**Comment by keenborder786** [comment]
Please make sure that the provided schema is in the region you are trying to connect. Your table might be in a different region as oppose to `US`

**Comment by AlexisVLRT** [comment]
I have the same issue, did a little digging and it seems the `CREATE VECTOR INDEX` just does not exist yet? At least not in GA.
<img width="942" alt="image" src="https://github.com/langchain-ai/langchain/assets/26208387/fee8fe4c-347a-449a-b75b-5f43d851fecc">

No mention of it in the BQ docs, or in the changelog that I can see.

If there is a private-access preview I'm happy to be invited 😄

**Comment by AlexisVLRT** [comment]
Hi @ashleyxuu! As you are the one who worked on `BigQueryVectorSearch`, maybe you have insider info on this?

Thanks for the feature by the way, looking forward to using it!

**Comment by ashleyxuu** [comment]
hi @AlexisVLRT, thanks for trying! This is private now, and BigQuery will launch BigQuery Vector Search by the end of this month. Stay tune for the PR update in LangChain and let me know if you have any further questions after the launch.
