### ISSUE TITLE
The ChatHuggingFace package cannot be found. "from langchain_community.chat_models.huggingface import ChatHuggingFace"，Has ChatHuggingFace changed paths？

### ISSUE THREAD

**Issue by ZHJ19970917** [langchain-ai/langchain#15530]
### System Info

langchain                 0.0.351
langchain-community       0.0.4
python 3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain_community.chat_models.huggingface import ChatHuggingFace

### Expected behavior

I was testing HuggingFace Chat Wrapper, but couldn't import the ChatHuggingFace。Has ChatHuggingFace changed paths？

**Comment by keenborder786** [comment]
@ZHJ19970917  Can you please update your langchain and langchain_community version
