### ISSUE TITLE
WARNING:pypdf._reader:incorrect startxref pointer(3)

### ISSUE THREAD

**Issue by SouSingh** [langchain-ai/langchain#15548]
### System Info

I try to load pdf in from langchain.document_loaders import PyPDFDirectoryLoader
got error this WARNING:pypdf._reader:incorrect startxref pointer(3)

from langchain.document_loaders import PyPDFDirectoryLoader
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFDirectoryLoader("/content/pdfs/Carina Lueschen Masterarbeit Ryan Trecartin (1).pdf")
pages = loader.load_and_split()

will return blank array and warning error

### Who can help?

@hwchase17 @agola11 @sbusso 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

just load the pdf which having images

### Expected behavior

output should be in array of pdf data

**Comment by RishavRanjan123** [comment]
i am also having the same problem, i've uploaded some 500 pdfs, i dont know which pdf file has the problem, is there a way to figure out ?, the code has a massive runtime though.

**Comment by RishavRanjan123** [comment]
> ### System Info
> I try to load pdf in from langchain.document_loaders import PyPDFDirectoryLoader got error this WARNING:pypdf._reader:incorrect startxref pointer(3)
> 
> from langchain.document_loaders import PyPDFDirectoryLoader from langchain_community.document_loaders import PyPDFLoader
> 
> loader = PyPDFDirectoryLoader("/content/pdfs/Carina Lueschen Masterarbeit Ryan Trecartin (1).pdf") pages = loader.load_and_split()
> 
> will return blank array and warning error
> 
> ### Who can help?
> @hwchase17 @agola11 @sbusso
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [x]  My own modified scripts
> 
> ### Related Components
> * [ ]  LLMs/Chat Models
> * [x]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [ ]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> just load the pdf which having images
> 
> ### Expected behavior
> output should be in array of pdf data

did your code run, or was stuck at this error and runtime was forever ?

**Comment by mathieugouin** [comment]
I have the same issue with my bank statements pdf.  Cannot share, sorry...

**Comment by iamade** [comment]
I am having the same issue with only pdfs that have alot of pictures you can check by inserting this code   st.warning(f"Warning: No text extracted from page {i + 1}")
