### ISSUE TITLE
How to specify a custom schema in PGVector.from_documents?

### ISSUE THREAD

**Issue by htcml** [langchain-ai/langchain#15553]
### Issue you'd like to raise.

```
from langchain.vectorstores.pgvector import PGVector

db = PGVector.from_documents(
    documents= docs,
    embedding = embeddings,
    collection_name= "blog_posts",
    distance_strategy = DistanceStrategy.COSINE,
    connection_string=CONNECTION_STRING
)
```
This code will create a table in public schema. How to specify a custom schema other than public?

**Comment by OmiWakode** [comment]
Hi @htcml . Did you figure this out? Did you have to override the PGvector class?

**Comment by Pratham-Jain-3903** [comment]
this is a much needed feature lets try to implement this :)

**Comment by Pratham-Jain-3903** [comment]
Right now, we can only use search_path in connection strings. I’m not certain how many of our internal conn.<functions> actually respect this setting or even consider it. The key question is whether they read and apply search_path when resolving internal table names.

From what I’ve observed:
- copy_records_to_table() does not support search_path.
- execute() does respect it.
- 
This suggests that support may vary across functions, and many of them might not handle search_path consistently.
