### ISSUE TITLE
Cannot import name 'URL' from 'sqlalchemy' 

### ISSUE THREAD

**Issue by vjeshwar** [langchain-ai/langchain#15579]
### Discussed in https://github.com/langchain-ai/langchain/discussions/5701

<div type='discussions-op-text'>

<sup>Originally posted by **rdhillbb** June  5, 2023</sup>

Newbie here.
I found an issue while importing 'VectorstoreIndexCreator'

ImportError: cannot import name 'URL' from 'sqlalchemy' (/Users/tst/anaconda3/lib/python3.10/site-packages/sqlalchemy/__init__.py)

Error Log:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[88], line 2
      1 from langchain.docstore.document import Document
----> 2 from langchain.indexes import VectorstoreIndexCreator
      3 from langchain_community.utilities import ApifyWrapper
      5 apify = ApifyWrapper()

File ~/anaconda3/lib/python3.10/site-packages/langchain/indexes/__init__.py:17
      1 """Code to support various indexing workflows.
      2 
      3 Provides code to:
   (...)
     14 documents that were derived from parent documents by chunking.)
     15 """
     16 from langchain.indexes._api import IndexingResult, aindex, index
---> 17 from langchain.indexes._sql_record_manager import SQLRecordManager
     18 from langchain.indexes.graph import GraphIndexCreator
     19 from langchain.indexes.vectorstore import VectorstoreIndexCreator

File ~/anaconda3/lib/python3.10/site-packages/langchain/indexes/_sql_record_manager.py:21
     18 import uuid
     19 from typing import Any, AsyncGenerator, Dict, Generator, List, Optional, Sequence, Union
---> 21 from sqlalchemy import (
     22     URL,
     23     Column,
     24     Engine,
     25     Float,
     26     Index,
     27     String,
     28     UniqueConstraint,
     29     and_,
     30     create_engine,
     31     delete,
     32     select,
     33     text,
     34 )
     35 from sqlalchemy.ext.asyncio import (
     36     AsyncEngine,
     37     AsyncSession,
     38     async_sessionmaker,
     39     create_async_engine,
     40 )
     41 from sqlalchemy.ext.declarative import declarative_base

Thank You
 Vj

**Comment by vjeshwar** [comment]
Hello I have the following version.
langchain - 0.0.339
sqlalchemy - 1.4.39

I have this langchain version for a reason of compatibility with one of the package. Kindly with this version of Langchain how to get rid of this "[import name 'URL' from 'sqlalchemy'](https://github.com/langchain-ai/langchain/issues/15579#top)"

**Comment by vjeshwar** [comment]
> Hello I have the following version. langchain - 0.0.339 sqlalchemy - 1.4.39
> 
> I have this langchain version for a reason of compatibility with one of the package. Kindly clarify that with this version of Langchain how to get rid of this import error "[import name 'URL' from 'sqlalchemy'](https://github.com/langchain-ai/langchain/issues/15579#top)"

Can you provide a fix for this issue ASAP pls. This is really critical for us.

**Comment by jirimoravcik** [comment]
Hey, can you give a link to the code example you're using? E.g. the URL in the docs

**Comment by andras-tim-wq** [comment]
There's not needed test code, just execute the `langchain`'s unit tests with **SQLAlchemy 1.X**:

e.g.: the `tests/unit_tests/storage/test_lc_store.py` will fail with similar issue, because it depends on a **v2.0**'s change:

https://github.com/sqlalchemy/sqlalchemy/commit/e545298e35ea9f126054b337e4b5ba01988b29f7#diff-1bb82f6a54a52b00f46fde263d6546b32a0c1445f4a6316a184544c8faff6ddcR46
