### ISSUE TITLE
Issue: Pypdf extract_image=True is not working on docker(production)

### ISSUE THREAD

**Issue by akash97715** [langchain-ai/langchain#15576]
### Issue you'd like to raise.

Hello Team,

we are trying to use pypdf to get the text out from the pdf use the chunk for embedding(details are there in attached code snippet. while using, i have installed all the required packages. its working fine in my local(windows 10). same code snippet and requirement.txt if i use on docker that uses ubuntu OS(its in prod), i am getting below error:

**Error while chunking the file: Error while chunking the file, Errored while loading the document: `rapidocr-onnxruntime` package not found, please install it with `pip install rapidocr-onnxruntime**`

The strage part here is this **rapidocr-onnxruntime** package is already installed on the ubuntu system**(i re-verified by seeing the github action runner logs where it installs all the packages from requirement.txt)**

Not able to understand why on prod it **pypdf package with extract_image=True** is throwing above error

It will be helpful, if you can provide any insight or workaround to this issue.
![process_pdff](https://github.com/langchain-ai/langchain/assets/34799343/d7a33465-d59d-438b-b6e2-3e68ab82fc9b)

**Comment by BYZANTINE26** [comment]
```
>>> from rapidocr_onnxruntime import RapidOCR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/rapidocr_onnxruntime/__init__.py", line 4, in <module>
    from .main import RapidOCR
  File "/usr/local/lib/python3.9/site-packages/rapidocr_onnxruntime/main.py", line 8, in <module>
    import cv2
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

I found OpenCV is trying to use OpenGL (libGL.so.1), but it's failing to find the necessary OpenGL library.

But I am unable to get OpenGL library on my docker container.

**Comment by MaisieHu8891** [comment]
I am facing the same issue, only error in docker ,  in my mac is correct:  

 self.loader = PyMuPDFLoader(self.file_path, extract_images=True)
024-03-15 13:43:42,811 - root - ERROR - `rapidocr-onnxruntime` package not found, please install it with `pip install rapidocr-onnxruntime`

please help me resolve it

**Comment by MaisieHu8891** [comment]
> I am facing the same issue, only error in docker , in my mac is correct:
> 
> and I'm sure docker has installed rapidocr-onnxruntime package
> 
> self.loader = PyMuPDFLoader(self.file_path, extract_images=True) 024-03-15 13:43:42,811 - root - ERROR - `rapidocr-onnxruntime` package not found, please install it with `pip install rapidocr-onnxruntime`
> 
> please help me resolve it

centos6 docker ," sudo yum install mesa-libGL"  can resolve it

**Comment by CIBIO-TropiBIO** [comment]
same issue

**Comment by box9527** [comment]
> in linux OS add this to you dockerfile.
> 
> ```
> RUN apt-get update && apt-get install -y --no-install-recommends \
>     libgl1-mesa-glx \  
>     libglib2.0-0 \
>     && rm -rf /var/lib/apt/lists/*
> ```

@bhargav-xponai 's solution is working perfectly for me. Thanks to save my day.
