### ISSUE TITLE
Chroma as_retriever function with kwargs leads to unexpected keyword argument 

### ISSUE THREAD

**Issue by 0xMatthieu** [langchain-ai/langchain#15585]
### System Info

langchain = 0.0.354
This problem appears since commit 62d32bd 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Comit 62d32bd allowed to pass kwarg to ChromaDb. This is really nice but I my case it leads to an error ...
I don't know if it is relevant or a workaround exists so I raise the issue

Here is how to reproduce

``` python
from langchain.vectorstores import Chroma

# load a simple Chroma DB
vectordb = Chroma(persist_directory=my_chroma_db_directory,
              embedding_function=my_embedding)

# init a retriever function
retriever = vectordb.as_retriever(search_kwargs={"k": retriever_output_number, "fetch_k": retriever_documents_used, "lambda_mult": retriever_diversity})

# call the retriever in a qa
qa_chain = RetrievalQA.from_chain_type(llm=llm,
                                          chain_type="stuff",
                                          retriever=retriever,
                                          return_source_documents=False,
                                          verbose=True)

# ask something
answer = qa_chain.run("find something in doc ...")
```

### Expected behavior

kwargs are needed by the `as_retriever` function, in the example above the argument `fetch_k` is mandatory

https://github.com/langchain-ai/langchain/blob/fd5fbb507dd3b1c189aa1e4b601b8669217b0f78/libs/core/langchain_core/vectorstores.py#L553

Since commit 62d32bd kwargs are passed up to Chroma `function similarity_search_with_score` which calls `__query_collection` leading to the error

https://github.com/langchain-ai/langchain/blob/fd5fbb507dd3b1c189aa1e4b601b8669217b0f78/libs/community/langchain_community/vectorstores/chroma.py#L408

TypeError: Collection.query() got an unexpected keyword argument 'fetch_k'

Is there a way to avoid that ?

**Comment by 0xMatthieu** [comment]
@dosu-bot sounds like a bug cause no parameters can be used instead of `k`
Does it means they should be considered as obsolete ?

**Comment by 0xMatthieu** [comment]
@dosu-bot, ok in my use case I can use and live with only `k`

**Comment by Catopham1702** [comment]
File "D:\Chatlocal\chatbotmsb\venv\Lib\site-packages\langchain_community\vectorstores\chroma.py", line 156, in __query_collection
    return self._collection.query(
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Collection.query() got an unexpected keyword argument 'distance_metric'

and then how to fix that bug
