### ISSUE TITLE
RAG chain response often includes "\n AI:" in front of actual response

### ISSUE THREAD

**Issue by mhyeonsoo** [langchain-ai/langchain#15586]
### System Info

google-cloud-aiplatform==1.35.0,
langchain-0.0.354

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
template = """
        **Role:**
        You are a helpful assistant.

        **Context:**
        You have to only use a reference stored document to generate a response.
        CONTEXT: {context}

        **Task:**
        1. task 1
            - some important requirements for task 1
        2. task 2
            - some important requirements for task 2  
        3. task 3 
            - some important requirements for task 3
            
        Question: {question}
        Helpful Answer:

        **Resource:** [reference source name]
    """
    
    qa_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", template),
        MessagesPlaceholder(variable_name="chat_history"),
        ("user", "{question}"),
    ]
    )
    
    rag_chain = (
        RunnablePassthrough.assign(
            context=contextualized_question | retriever | format_docs
        )
        | qa_prompt
        | llm
    )

    response = rag_chain.invoke({"question": message, "chat_history": memory.get_history()})
    
    print(response)
```

### Expected behavior

I expect to get the response which is composed of only a proper response sentence. Sometimes, it does well as I expected.
But frequently, it returns "\n AI:" in front of the actual response which is not suppose to do so.

For example,
```
"\n AI: The reference document says blah blah.", 
```

**Comment by mhyeonsoo** [comment]
Thanks,

It seems reasonable to have prefix_removal function as a last step of rag_chain, but I am bit concerning about the cases that is not returning fixed prefix like "\n AI:" as you mentioned.

I think it would be great if I can have more flexible way to handle these exceptions.
Thanks.

**Comment by mhyeonsoo** [comment]
Thanks @dosu-bot,

It seems reasonable to have prefix_removal function as a last step of rag_chain, but I am bit concerning about the cases that is not returning fixed prefix like "\n AI:" as you mentioned.

I think it would be great if I can have more flexible way to handle these exceptions. (I hope there would be another way such as adding more functions in chain or something)

Thanks.

**Comment by gianfrancodemarco** [comment]
I also had this problem when adding history.
History is usually formatted as something like

_Human:
AI:_

so the LLM thinks it has to use the AI: prefix.
If that's your case, you could rely on the replace method or play with the prompt to let the LLM understand better-
