### ISSUE TITLE
DOC: Lack of Documentation Versioning on Langchain Website

### ISSUE THREAD

**Issue by iambsk** [langchain-ai/langchain#15597]
### Issue with current documentation:

There is no way to view the old documentation on [the official site](https://python.langchain.com/). This makes it extremely difficult to develop. It seems as though every week there is another feature that is deleted, thus another page being deleted. 

How is this acceptable? It is becoming almost unusable in the Enterprise world due to the constant changes and lack of documentation. 

### Idea or request for content:

Implement a selector that lets you choose which langchain version you're on so that you can view the documentation for that specific version.

**Comment by hwchase17** [comment]
thanks for flagging @iambsk, and sorry for any confusion or trouble this has caused

As we move to langchain 0.1, we will start to keep a set of documentation for each minor version and try to only make large documentation changes when we change minor versions. Hopefully this should help. Also open to other ideas
