### ISSUE TITLE
AttributeError: module 'chromadb' has no attribute 'config'

### ISSUE THREAD

**Issue by XariZaru** [langchain-ai/langchain#15616]
### System Info

Python 3.11, Langchain 0.0.354, ChromaDB v0.4.22

### Who can help?

@agola11
@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.text_splitter import MarkdownTextSplitter, RecursiveCharacterTextSplitter
from langchain.document_loaders import DirectoryLoader
from langchain.storage import InMemoryStore
from langchain.retrievers import ParentDocumentRetriever
from langchain.vectorstores import Chroma
import chromadb
    
    
def load_chroma_db(collection_name: str):
    parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400)
    
    vectorstore = Chroma(
        collection_name=collection_name, 
        embedding_function=get_embedding_function(), 
        persist_directory="storage/deploy/chroma-db"
    )
    store = InMemoryStore()
    
    retriever = ParentDocumentRetriever(
        vectorstore=vectorstore,
        docstore=store,
        child_splitter=child_splitter,
        parent_splitter=parent_splitter
    )
    return retriever

retriever = load_chroma_db("full_docs")
retriever.add_documents(bancworks_docs)
```

### Expected behavior

Should be able to load ChromaDB and persist it.

**Comment by XariZaru** [comment]
this doesn't really help. This was working recently. I've tried downgrading both to an earlier version with no avail.

**Comment by XariZaru** [comment]
I resolved it. Full reinstall of both packages did the job.

**Comment by hwchase17** [comment]
> I resolved it. Full reinstall of both packages did the job.

glad to hear resolved!

**Comment by zhenzhenvlo** [comment]
which two packages  are reinstall？

**Comment by zhenzhenvlo** [comment]
same question😭

**Comment by XariZaru** [comment]
I reinstalled ChromaDB and pysqlite3. Since I am running on a Docker Container, I also imported pysqlite3 this way before importing chromadb.

```python
__import__('pysqlite3')
import pysqlite3
sys.modules['sqlite3'] = sys.modules["pysqlite3"]
import chromadb
```

Only in this way was I able to get it to work.

**Comment by budhewarvijay0407** [comment]
Add chromadb==0.4.4 and keep langchain at 0.1.9

**Comment by qingtian1771** [comment]
it seems still a problem with:
chromaDB: 0.5.20
LangChain: 0.3.9
langchain-chroma: 0.1.4
