### ISSUE TITLE
Issue: What docstore to use in ChromaDB that isn't in memory?

### ISSUE THREAD

**Issue by XariZaru** [langchain-ai/langchain#15633]
### Issue you'd like to raise.

I have the following ChromaDB setup:

```python
parent_splitter = RecursiveCharacterTextSplitter(chunk_size=2000)
    child_splitter = RecursiveCharacterTextSplitter(chunk_size=400)

    vectorstore = None
    try:
        vectorstore = Chroma(persist_directory="storage/deploy/chroma-db", embedding_function=get_embedding_function())        
        print("Loaded existing vector store")
    except:
        print("Creating new vector store")
        vectorstore = Chroma(
            collection_name=collection_name, 
            embedding_function=get_embedding_function(), 
            persist_directory="storage/deploy/chroma-db"
        )
        
    store = InMemoryStore()
    
    retriever = ParentDocumentRetriever(
        vectorstore=vectorstore,
        docstore=store,
        child_splitter=child_splitter,
        parent_splitter=parent_splitter
    )
    return retriever
```

The issue is if I add a bunch of documents to the retriever, the memory eventually can run out and crash the system. Is there a way for this to be done out of RAM instead? Or am I misunderstanding the usage of this.

### Suggestion:
Is there a non-inmemory docstore that can be used in the ParentDocumentRetriever or does it not make sense in the use case.

**Comment by XariZaru** [comment]
Is this really the alternative solution? I don't have any chat history. Can I get more help on this matter?

**Comment by gcheron** [comment]
This PR aims at adding support for document storage in a SQL database: https://github.com/langchain-ai/langchain/pull/15909

**Comment by misslapina123** [comment]
I have the same issue. I run out of memory and the system crashes when using InMemoryStore(). I do not have any chat history, I use this for document storage as I need it for the retriever.
