### ISSUE TITLE
Tracing is not working Apple M1 machines

### ISSUE THREAD

**Issue by sheikalthaf** [langchain-ai/langchain#1564]
If i try to run the tracing in Apple M1 laptop, It is throwing error for backend app

Error Message: **rosetta error: failed to open elf at**

**Comment by danielchalef** [comment]
The container images are only currently available for `amd64` and not `arm64`. Rosetta emulation is currently failing for `notlangchain/langchainplus:d01018146320` with the above error.

Are there plans to build `arm64` containers?

**Comment by hwchase17** [comment]
thanks for flagging. we're hoping to make some progress on tracing in the next few weeks, we'll look into alternative builds then.
