### ISSUE TITLE
Issue: how to resolve this warning "My code has a warning "D:\anaconda3\envs\py311\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing verbose from langchain root module is no longer supported. Please use langchain.globals.set_verbose() / langchain.globals.get_verbose() instead. warnings.warn(""

### ISSUE THREAD

**Issue by JianyaoChen** [langchain-ai/langchain#15647]
### Issue you'd like to raise.

I have a warning when I run my langchain code "how to resolve this warning "My code has a warning "D:\anaconda3\envs\py311\Lib\site-packages\langchain\__init__.py:34: UserWarning: Importing verbose from langchain root module is no longer supported. Please use langchain.globals.set_verbose() / langchain.globals.get_verbose() instead. warnings.warn(", how to resolve it?

**Comment by jackklika** [comment]
This might be a quick fix: Make sure the file is not named `langchain.py`. If it is it will try importing the file.

Check to see if you have a filename `langchain.py`, rename it, and see if it fixes the issue.

**Comment by AdovaX** [comment]
from langchain.globals import set_verbose
set_verbose(True)
