### ISSUE TITLE
Issue: __call__ was deprecated use invoke instead warning persists after switching to invoke

### ISSUE THREAD

**Issue by robert-mcdermott** [langchain-ai/langchain#15665]
### Issue you'd like to raise.

After upgrading to langchain 0.1.0, I received depreciation warnings and updated my imports to langchain_community which cleared that error, then received depreciation warnings about __call__ to Invoke:

The function `__call__` was deprecated in LangChain 0.1.0 and will be removed in 0.2.0. Use invoke instead.

I switched the invoke method on the call still get some of the same depreciation warnings. Not sure how to fix this or if it's a bug. code:

```python
    qachain = RetrievalQA.from_chain_type(ollama, retriever=vectorstore.as_retriever(search_kwargs={"k": args.top_matches}))
    res = (qachain.invoke({"query": args.question}))
``` 

How do I fix this?

**Comment by henrykohl** [comment]
Try the following code : 
qachain.invoke(input = args.question)
