### ISSUE TITLE
For New Contributors: Update Integration Documentation

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#15664]
### Issue you'd like to raise.

Hello LangChain community,

We're always happy to see more folks getting involved in contributing to the LangChain codebase.

This is a good first issue if you want to learn more about how to set up
for development in the LangChain codebase.

## Goal

Your contribution will make it easier for users to use integrations with the newest LangChain syntax

## Context

As you may have noticed, we’ve recently gone to LangChain 0.1. As part of this, we want to update integration pages to be consistent with new methods. These largely include: (a) new methods for invoking integrations and chains (`invoke`, `stream`), (b) new methods for creating chains (LCEL, `create_xyz_..`).

There are a lot of integrations, so we’d love community help! This is a great way to get started contributing to the library as it will make you familiar with best practices and various integrations.

## Set up for development

There are lots of integration notebooks in https://github.com/langchain-ai/langchain/tree/master/docs/docs/integrations. After making changes there, you should run `make format` from the root LangChain directory to run our formatter.

## Shall you accept

Shall you accept this challenge, please claim one (and only one) of the modules from the list
below as one that you will be working on, and respond to this issue.

Once you've made the required code changes, open a PR and link to this issue.

## Acceptance Criteria

- Uses new methods for calling chains (`invoke`, `stream`, etc)
- Uses LCEL where appropriate
- Follows the format outlined below

## Examples

We've gotten started with some examples to show how we imagine these integration pages should look like. The exact format may look different for each type of integration, so make sure to look at the type you are working on:

- LLMs:
    - https://python.langchain.com/docs/integrations/llms/cohere
- Chat Models:
    - https://python.langchain.com/docs/integrations/chat/cohere
- Vectorstores:
    - https://python.langchain.com/docs/integrations/vectorstores/faiss
- Retrievers:
    - https://python.langchain.com/docs/integrations/retrievers/tavily
    - https://python.langchain.com/docs/integrations/retrievers/ragatouille
- Tools:
    - https://python.langchain.com/docs/integrations/tools/tavily_search
- Toolkits:
    - https://python.langchain.com/docs/integrations/toolkits/gmail
- Memory:
    - https://python.langchain.com/docs/integrations/memory/sql_chat_message_history

## Your contribution

Please sign up by responding to this issue and including the name of the module.

**Comment by sweetkane** [comment]
I can take the Memory module

**Comment by DaveDeCaprio** [comment]
Claiming memory/mongodb_chat_message_history.ipynb

**Comment by DaveDeCaprio** [comment]
@hwchase17 `memory/sqlite.ipynb` uses the `ConversationEntityMemory` class, which only exists in the langchain package, not one of the new packages.  Does that mean it's dropped in 0.1?  What should happen with that notebook?

**Comment by marsmxm** [comment]
Claimin `memory/redis_chat_message_history.ipynb`

**Comment by OmarAly23** [comment]
Claiming [memory/streamlit_chat_message_history.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/memory/streamlit_chat_message_history.ipynb)

**Comment by bhadreshpsavani** [comment]
claiming [llms/ai21.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/llms/ai21.ipynb)

**Comment by Bigtable123** [comment]
claiming [chat/baichuan.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/chat/baichuan.ipynb)

**Comment by hwchase17** [comment]
> @hwchase17 `memory/sqlite.ipynb` uses the `ConversationEntityMemory` class, which only exists in the langchain package, not one of the new packages. Does that mean it's dropped in 0.1? What should happen with that notebook?

we should not use ConversationEntityMemory, and instead update to be more similar to the linked notebook about sql

**Comment by rshah98626** [comment]
Claiming [memory/postgres_chat_message_history.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/memory/postgres_chat_message_history.ipynb)

**Comment by mtmahe** [comment]
@hwchase17 are they all complete? I don't see the list the OP talks about.

**Comment by jzaldi** [comment]
Claiming `llms/google_vertex_ai_palm.ipynb`

**Comment by DaveDeCaprio** [comment]
Claiming memory/sqlite..ipynb

**Comment by seanmavley** [comment]
LLMs

Claiming Ollama

https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/llms/ollama.ipynb

**Comment by omaraly22** [comment]
> Claiming [memory/streamlit_chat_message_history.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/memory/streamlit_chat_message_history.ipynb)

Since the file I initially claimed was modified; I instead will claim [vectorstores/llm_rails.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/vectorstores/llm_rails.ipynb)

**Comment by OmarAly23** [comment]
> Claiming [memory/streamlit_chat_message_history.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/memory/streamlit_chat_message_history.ipynb)

Given that the file I initially claimed has already been modified with the new methods, I instead will claim another file

Claiming [vectorstores/llms_rails.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/vectorstores/llm_rails.ipynb)

**Comment by manokhina** [comment]
claiming chat/google_vertex_ai_palm.ipynb

**Comment by d1by** [comment]
claiming llms/octoai.ipynb

https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/llms/octoai.ipynb

**Comment by jmelot** [comment]
Claiming `tools/arxiv.ipynb`

**Comment by L-cloud** [comment]
Claiming `chat/anthropic.ipynb`

**Comment by rshah98626** [comment]
Has anyone had any issues with getting the docs to build? I continuously get this error when running poetry install:
```
The current project could not be installed: No file/folder found for package langchain-monorepo
If you do not want to install the current project use --no-root
```

Additionally, both `make docs_build` & `make api_docs_build` fail. The docs_build fails because of 
```
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- langgraph
```
The api_docs_build has quite a few errors. Not sure if I'm missing downloading something critical.

**Comment by baskaryan** [comment]
@rshah98626 these are bugs in local docs deployment script, it's gone out of date since we've made a few structural changes to the docs. Opened issue to fix #16677, thank you for flagging!

**Comment by rocky1405** [comment]
Claiming https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/llms/aleph_alpha.ipynb

**Comment by scottnath** [comment]
claiming https://python.langchain.com/docs/integrations/retrievers/you

**Comment by baskaryan** [comment]
Related issue #16911 for anyone looking to contribute!

**Comment by mtmahe** [comment]
claiming docs/docs/integrations/chat/mistralai.ipynb

**Comment by Mercurrent** [comment]
Claiming [docs/integrations/chat/bedrock](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/chat/bedrock.ipynb)

**Comment by johneckberg** [comment]
claiming `retrievers/pubmed.ipynb`

**Comment by Naveenkhasyap** [comment]
claiming [/integration/chat/anthropic_functions](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/chat/anthropic_functions.ipynb)

**Comment by CodingBeginner97** [comment]
Claiming [docs/integrations/tools/pubmed.ipynb](https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/tools/pubmed.ipynb)
