### ISSUE TITLE
class `AzureChatOpenAI` was deprecated in LangChain 0.1.0 and will be removed in 0.2.0. Use langchain_openai.AzureChatOpenAI instead. 

### ISSUE THREAD

**Issue by 3051360** [langchain-ai/langchain#15674]
### Issue with current documentation:

I created an app using AzureOpenAI, and initially, the import statement worked fine:
```
from langchain.chat_models import AzureChatOpenAI
```

My original version details were:

```
langchain==0.0.352
langchain-community==0.0.6
langchain-core==0.1.3
openai==1.6.1

```

Later, I upgraded to:

```
langchain==0.0.354
langchain-community==0.0.9
langchain-core==0.1.7
langchain-experimental==0.0.47
langchain-openai==0.0.2
openai==1.6.1

```

The upgrade led to a deprecation warning for `AzureChatOpenAI`. The suggestion was to use `langchain_openai.AzureChatOpenAI`, but trying to import it gave a `ModuleNotFoundError`. After some trial and error, I found that installing `langchain_openai` separately fixed the issue. Now, I can import `AzureOpenAI`, `AzureOpenAIEmbeddings`, and `AzureChatOpenAI`.

### Idea or request for content:

Despite my research, I couldn't find documentation mentioning the need to install `langchain_openai` separately, which wasted a lot of time and created unnecessary confusion. Sharing this issue here, hope it helps others facing a similar problem. Please add this to the documentation

**Comment by bstanie-qstar** [comment]
I've rxperienced a similar issue today. A simple upgrade of **openai** and **langchain** did not work out.
Had to separately install **langchain_openai** to make things work.
