### ISSUE TITLE
Add Dynamic Schema support for the Milvus vector store

### ISSUE THREAD

**Issue by ohbeep** [langchain-ai/langchain#15690]
### Feature request

I suggest supporting the Milvus vector database's new [Dynamic Schema](https://milvus.io/docs/dynamic_schema.md) feature.

### Motivation

According to Milvus:

> Dynamic schema enables users to insert entities with new fields into a Milvus collection without modifying the existing schema. This means that users can insert data without knowing the full schema of a collection and can include fields that are not yet defined.

I think it is good to allow Langchain to have this feature when multiple types or schema of documents are added to the database.

### Your contribution

I propose to add a "dynamic_schema" flag to the `__init__` and `from_texts` method of the Milvus class:

`__init__` method:

https://github.com/langchain-ai/langchain/blob/4c47f39fcb539fdeff6dd6d9b1f483cd9a1af69b/libs/community/langchain_community/vectorstores/milvus.py#L107-L125

Change to:

```python
    def __init__(
        self,
        embedding_function: Embeddings,
        collection_name: str = "LangChainCollection",
        collection_description: str = "",
        connection_args: Optional[dict[str, Any]] = None,
        consistency_level: str = "Session",
        index_params: Optional[dict] = None,
        search_params: Optional[dict] = None,
        drop_old: Optional[bool] = False,
        *,
        primary_field: str = "pk",
        text_field: str = "text",
        vector_field: str = "vector",
        metadata_field: Optional[str] = None,
        partition_names: Optional[list] = None,
        replica_number: int = 1,
        timeout: Optional[float] = None,
        dynamic_schema = False,
    ):
```

`from_texts` method:

https://github.com/langchain-ai/langchain/blob/4c47f39fcb539fdeff6dd6d9b1f483cd9a1af69b/libs/community/langchain_community/vectorstores/milvus.py#L839-L887

Change to:

```python
    def from_texts(
        cls,
        texts: List[str],
        embedding: Embeddings,
        metadatas: Optional[List[dict]] = None,
        collection_name: str = "LangChainCollection",
        connection_args: dict[str, Any] = DEFAULT_MILVUS_CONNECTION,
        consistency_level: str = "Session",
        index_params: Optional[dict] = None,
        search_params: Optional[dict] = None,
        drop_old: bool = False,
        dynamic_schema = False,
        **kwargs: Any,
    ) -> Milvus:
```

I may later submit a PR for this suggestion.

**Comment by lauradang** [comment]
I have opened a PR here: https://github.com/langchain-ai/langchain/pull/21172. Hopefully, it gets merged soon.
