### ISSUE TITLE
Issue: How to add chat history in prompt template

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15692]
### Issue you'd like to raise.

<pre>
```
def generate_custom_prompt(query=None, name=None, not_uuid=None, chroma_db_path=None):
    check = query.lower()
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    relevant_document = retriever.get_relevant_documents(query)
    print(relevant_document, "*****************************************")
    context_text = "\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers to User's Questions:```{check}```, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        custom_prompt_template = f"""Generate your response exclusively from the provided context: {{context_text}}. You function as a chatbot specializing in delivering detailed answers to the User's Question: ```{{check}} ```, enclosed within triple backticks.
            Generate your answer in points in the following format:
            1. Point no 1
                1.1 Its subpoint in details
                1.2 More information if needed.
            2. Point no 2
                2.1 Its subpoint in details
                2.2 More information if needed.
            …
            N. Another main point.

            If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
            However, if the answer is not present in the predefined points, then Provide comprehensive information related to the user's query.
            Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

            User's Question: ```{{check}} ```  
            AI Answer:"""

    custom_prompt = ChatPromptTemplate.from_template(template=custom_prompt_template)
    formatted_prompt = custom_prompt.format(context_text=context_text, check=check)
    llm = ChatOpenAI(temperature=0.1)
    memory = ConversationBufferMemory(llm=llm, output_key='answer', memory_key='chat_history', return_messages=True)
    qa = ConversationalRetrievalChain.from_llm(llm=llm, memory=memory, chain_type="stuff", retriever=retriever,
                                               return_source_documents=True, get_chat_history=lambda h: h, verbose=True,
                                               combine_docs_chain_kwargs={"prompt": PromptTemplate(
                                                   template=custom_prompt_template, input_variables=["context_text", "check"])})
    return qa
```
</pre>
How to add chat history in prompt template as well in above function

**Comment by deepak-habilelabs** [comment]
> ```python
> Chat History: ```{{history}}```
> ```



> _🤖_
> 
> Hello again, @deepak-habilelabs! Nice to see you working on LangChain. Let's dive into your issue.
> 
> To include the chat history in the prompt template, you can modify the `generate_custom_prompt` function to include a `history` parameter that stores the chat history. This `history` parameter can be a list of strings, where each string is a previous message in the chat.
> 
> You can then include this `history` in your `custom_prompt_template` by adding a placeholder for it, such as `{history}`. When you format the `custom_prompt_template`, you can pass in the `history` parameter to replace the `{history}` placeholder with the actual chat history.
> 
> Here's an example of how you can modify your function to include the chat history:
> 
> ```python
> def generate_custom_prompt(query=None, name=None, not_uuid=None, chroma_db_path=None, history=None):
>     # ... existing code ...
> 
>     if check in greetings:
>         custom_prompt_template = f"""
>         Just simply reply with "Hello {name}! How can I assist you today?"
>         """
>     elif check not in greetings and user_experience_inst.custom_prompt:
>         custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
>         You are a chatbot designed to provide answers to User's Questions:```{check}```, delimited by triple backticks.
>         Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}
> 
>         If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
>         - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.
> 
>         Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.
> 
>         User's Question: ```{check}```
>         AI Answer:
>         Chat History: ```{history}```"""
>     else:
>         custom_prompt_template = f"""Generate your response exclusively from the provided context: {{context_text}}. You function as a chatbot specializing in delivering detailed answers to the User's Question: ```{{check}} ```, enclosed within triple backticks.
>             Generate your answer in points in the following format:
>             1. Point no 1
>                 1.1 Its subpoint in details
>                 1.2 More information if needed.
>             2. Point no 2
>                 2.1 Its subpoint in details
>                 2.2 More information if needed.
>             …
>             N. Another main point.
> 
>             If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
>             However, if the answer is not present in the predefined points, then Provide comprehensive information related to the user's query.
>             Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.
> 
>             User's Question: ```{{check}} ```  
>             AI Answer:
>             Chat History: ```{{history}}```"""
> 
>     # ... existing code ...
> ```
> 
> In this example, I've added a `history` parameter to the `generate_custom_prompt` function and included a `{history}` placeholder in the `custom_prompt_template`. When you format the `custom_prompt_template`, you can pass in the `history` parameter to replace the `{history}` placeholder with the actual chat history.
> 
> Please note that this is a simplified example and the actual implementation may vary depending on the details of your application and the LangChain framework. For example, you may need to format the `history` parameter into a string before passing it to the `custom_prompt_template`.
> 
> I hope this helps! If you have any further questions, please let me know.
> 
> ## Sources
> * [libs/core/tests/unit_tests/prompts/test_chat.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/tests/unit_tests/prompts/test_chat.py)
> * [libs/langchain/langchain/chains/qa_generation/prompt.py](https://github.com/hwchase17/langchain/blob/master/libs/langchain/langchain/chains/qa_generation/prompt.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

How to use it in memory and conversational retreival chain?
<pre>
memory = ConversationBufferMemory(llm=llm,output_key='answer',memory_key='chat_history',return_messages=True)  
qa = ConversationalRetrievalChain.from_llm(llm=llm,memory=memory,chain_type="stuff",retriever=retriever,return_source_documents=True,get_chat_history=lambda h : h,verbose=True, combine_docs_chain_kwargs={"prompt": PromptTemplate(template=custom_prompt_template,input_variables=["context_text","check"])})
</pre>

**Comment by deepak-habilelabs** [comment]
> _🤖_
> 
> To incorporate the `history` parameter into the `ConversationBufferMemory` and `ConversationalRetrievalChain` objects in your modified `generate_custom_prompt` function in the LangChain application, you can follow the examples provided in the `RunnableWithMessageHistory` class.
> 
> Firstly, you need to create a `ChatPromptTemplate` that includes a `MessagesPlaceholder` for the history. This placeholder will be replaced with the actual history when the prompt is generated.
> 
> ```python
> from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
> 
> prompt = ChatPromptTemplate.from_messages([
>     ("system", "You're an assistant who's good at {ability}"),
>     MessagesPlaceholder(variable_name="history"),
>     ("human", "{question}"),
> ])
> ```
> 
> Then, you can create a `RunnableWithMessageHistory` object that wraps your `ConversationalRetrievalChain` (or any other `Runnable` object). This object will manage the chat history for the wrapped runnable.
> 
> ```python
> from langchain_core.runnables.history import RunnableWithMessageHistory
> 
> chain_with_history = RunnableWithMessageHistory(
>     chain,  # This should be your ConversationalRetrievalChain
>     get_session_history,  # This should be a function that returns a ConversationBufferMemory
>     input_messages_key="question",
>     history_messages_key="history",
> )
> ```
> 
> The `get_session_history` function should return a `ConversationBufferMemory` object for the given session. This function will be called with the `session_id` from the config.
> 
> Finally, you can invoke the `chain_with_history` with the `history` and `question` parameters in the input and the `session_id` in the config.
> 
> ```python
> chain_with_history.invoke(
>     {"ability": "math", "question": "What does cosine mean?"},
>     config={"configurable": {"session_id": "foo"}}
> )
> ```
> 
> This will generate a prompt that includes the history and the question, and then pass it to the `ConversationalRetrievalChain`. The `ConversationalRetrievalChain` should be designed to handle this kind of input.
> 
> You can find more details about this in the [RunnableWithMessageHistory class](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/runnables/history.py).
> 
> As for the `ConversationBufferMemory` class, it is used for storing conversation memory. It provides methods and properties to manage the conversation history. You can find more details about this in the [ConversationBufferMemory class](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer.py).
> 
> I hope this helps! If you have any more questions, feel free to ask.
> 
> ## Sources
> * [libs/core/langchain_core/runnables/history.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/runnables/history.py)
> * [libs/langchain/langchain/memory/buffer.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Modify my code according to above.

**Comment by mr-mainak** [comment]
@deepak-habilelabs Hi, did u solve the issue?
