### ISSUE TITLE
Add support for the Mistral AI Embedding Model

### ISSUE THREAD

**Issue by mohitnihalani** [langchain-ai/langchain#15702]
### Feature request

Feature request
They provide a [python client](https://docs.mistral.ai/platform/endpoints/) to access the embedding model

### Motivation

It would be great if we added the new embedding service from Mistral!

### Your contribution

I can work on this and submit a PR

**Comment by prise6** [comment]
I think it's currently in merging request : https://github.com/langchain-ai/langchain/pull/15282
Hope it will come fast :)
