### ISSUE TITLE
Connection error caused failure to post http://localhost:1984/runs  in LangSmith API.

### ISSUE THREAD

**Issue by millfields99** [langchain-ai/langchain#15739]
### System Info

From pyproject.toml:

python=3.11.5
crewai = "0.1.6"
langchain = '==0.0.335'
openai = '==0.28.1'
unstructured = '==0.10.25'
pyowm = '3.3.0'
tools = "^0.1.9"
wikipedia = "1.4.0"
yfinance = "0.2.33"
sec-api = "1.0.17"
tiktoken = "0.5.2"
faiss-cpu = "1.7.4"
python-dotenv = "1.0.0"

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Running any of the scripts in the crewAI (https://github.com/joaomdmoura/crewAI)

Running crewAI I get the following.

Connection error caused failure to patch http://localhost:1984/runs/7fdd9cf2-4f50-4ee1-8fef-9202b07cc756  in LangSmith API. Please confirm your LANGCHAIN_ENDPOINT. ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=1984): Max retries exceeded with url: /runs/7fdd9cf2-4f50-4ee1-8fef-9202b07cc756 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x130d51e10>: Failed to establish a new connection: [Errno 61] Connection refused'))"))

Connection error caused failure to post http://localhost:1984/runs  in LangSmith API. Please confirm your LANGCHAIN_ENDPOINT. ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=1984): Max retries exceeded with url: /runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x130d6b390>: Failed to establish a new connection: [Errno 61] Connection refused'))"))

I ma not running LangSmith nor do I have any access to it.  I have tried setting  in my .env to no effect. 

LANGCHAIN_TRACING=false
LANGCHAIN_TRACING_V2=false
LANGCHAIN_HANDLER=None

### Expected behavior

Dont expect to see the error reports. Note that not all users are seeing this error

**Comment by lekpeng** [comment]
Hello I encountered a similar issue, do make sure you load the env before running the langsmith client. 

```
from dotenv import load_dotenv
from langsmith import Client

load_dotenv()
client = Client()
```
