### ISSUE TITLE
DOC: <https://python.langchain.com/docs/integrations/chat/ollama_functions 'DOC: ' prefix>ollamafunctions not working at all

### ISSUE THREAD

**Issue by seyi33** [langchain-ai/langchain#15808]
### Issue with current documentation:

i have tried with several tests, even with the most basic e.g in the doc, nothing. Dissapointed because it got me superexcited at first:
from langchain_experimental.llms.ollama_functions import OllamaFunctions
from langchain.schema import HumanMessage

model = OllamaFunctions(model="dolphinmodel",)

model = model.bind(
    functions=[
        {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, " "e.g. San Francisco, CA",
                    },
                    "unit": {
                        "type": "string",
                        "enum": ["celsius", "fahrenheit"],
                    },
                },
                "required": ["location"],
            },
        }
    ],
    function_call={"name": "get_current_weather"},
)

model.invoke("what is the weather in Boston?")

**Comment by x-technik** [comment]
Hi There, I am also stuck at this point, I am using local llm= OllamaFunctions(model="mistral"),
I have two functions, looks like routing is working, If it needs to call the functions it calls and if no need to call, it continues regular conversation, But I have an issue with parsing the output to the functions,   

 File "/usr/local/lib/python3.10/dist-packages/langchain_experimental/llms/ollama_functions.py", line 110, in _generate
    raise ValueError(
ValueError: Failed to parse a function call from mistral output: {
  "tool": "check_calendar",
  "tool_input": {
    "date": "2023-03-24"
  }

or fails to parse search query   ValueError: Failed to parse a function call from mistral output: {
  "tool": "search",
  "tool_input": {
    "query": "Capital of Turkey"
  }
}


Here are my Functions
@tool
def check_calendar(date: str) -> list:
    """Check the user's calendar for meetings on the specified date (in iso format)."""
    date_time = parse(date)
    if date_time.weekday() == 4:  # Friday
        return [
            "8:30 : Team Standup",
            "9:00 : 1 on 1",
            "9:45 : Design review",
        ]
    return ["Focus time"]

search = TavilySearchResults(max_results=1)  
# tools = [check_calendar, search_tool]

tools = [
    Tool(
        name="search",
        func=search.run,
        description="useful for when you need to answer questions about current events",
    ),

        Tool(
        name="check_calendar",
        func=check_calendar.run,
        description="useful for when you need to answer questions about calendar event.heck the user's calendar for meetings on the specified date (in iso format).",
    )
]
