### ISSUE TITLE
Cannot combine an output parser and a conversation buffer memory

### ISSUE THREAD

**Issue by kevin-guimard-ext** [langchain-ai/langchain#15835]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation, with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from langchain.memory import ConversationBufferMemory

from langchain.prompts.chat import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate, MessagesPlaceholder
from langchain.chains import LLMChain


class TennisPlayer(BaseModel):
    age: int = Field(description="Age of the player")
    nb_victories: int = Field(description="Nb of victories in major tournaments")

llm = None # Instantiate the LLM here

parser = PydanticOutputParser(pydantic_object=TennisPlayer)

prompt = "You'll be asked information about a tennis player.\n" \
         "You'll answer with the following format:\n" \
         "{format_instructions}"

memory = ConversationBufferMemory(memory_key="chat_history", input_key="query", return_messages=True)
chat_prompt = ChatPromptTemplate.from_messages([SystemMessagePromptTemplate.from_template(prompt),
                                                MessagesPlaceholder(variable_name="chat_history"),
                                                HumanMessagePromptTemplate.from_template("{query}")])

chain = LLMChain(llm=llm, prompt=chat_prompt, memory=memory, output_parser=parser)

chain.invoke(input={"query": "Rafael Nadal", "format_instructions": parser.get_format_instructions()})
```

### Description

The previous code triggers an error while converting the output from the LLM to an AIMessage to place in the ConversationBufferMemory object. The problem is that it passes the constructed object (the output of PydanticOutputParser.parse) instead of the output message as a plain string.

### System Info

langchain 0.1.0
python 3.10.13
Windows 10

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by eyurtsev** [comment]
@kevin-guimard-ext `Memory` is out-of-date with some of the chat representation as far as I remember. We still haven't gotten around to doing a re-vamp of it. 

As a work-around you could try using `RunnableWithMessageHistory` and LCEL:

https://python.langchain.com/docs/expression_language/how_to/message_history

**Comment by kevin-guimard-ext** [comment]
Langchain's official documentation stills dedicates a page to ConversationBufferMemory, so I'm not aware of its being deprecated.

I'm not familiar with RunnableWithMessageHistory, and I don't understand what to put in the second parameter get_session_history.

If you think an equivalent code could work, could you please post it?
