### ISSUE TITLE
Intercepting the output message in a callback handler before it is sent to the output parser

### ISSUE THREAD

**Issue by kevin-guimard-ext** [langchain-ai/langchain#15830]
### System Info

langchain v0.1.0

### Who can help?

@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from typing import Any, Dict
from langchain_core.outputs.llm_result import LLMResult

from langchain.prompts.chat import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain.chains import LLMChain
from langchain.callbacks.base import BaseCallbackHandler


class CustomCallBack(BaseCallbackHandler):
    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> Any:
         print(f"on_llm_end => {response}")

    def on_chain_end(self, outputs: Dict[str, Any], **kwargs: Any) -> Any:
        print(f"on_chain_end => {outputs}")

    def on_text(self, text: str, **kwargs: Any) -> Any:
        print(f"on_text => {text}")

class TennisPlayer(BaseModel):
    age: int = Field(description="Age of the player")
    nb_victories: int = Field(description="Nb of victories in major tournaments")

# Instantiate the LLM here
llm = None

parser = PydanticOutputParser(pydantic_object=TennisPlayer)

prompt = "Give me some information about Rafael Nadal.\n" \
         "You'll answer with the following format:\n" \
         "{format_instructions}"

chat_prompt = ChatPromptTemplate.from_messages([HumanMessagePromptTemplate.from_template(prompt)])

chain = LLMChain(llm=llm, prompt=chat_prompt, callbacks=[CustomCallBack()], output_parser=parser)

chain.invoke(input={"format_instructions": parser.get_format_instructions()})
```

### Expected behavior

The custom callback handler makes it possible to intercept the prompt sent to the LLM (through _on_text_) and the output in _on_chain_end_. The problem is that when an output parser is involved, the _outputs_ dictionary of _on_chain_end_ associates the "text" key with the final constructed object and not the output message (containing the JSON data that has been marshalled to an object). And for an unknown reason, the _on_llm_end_ callback function isn't invoked...

When something goes wrong in the marshalling process, the analysis of the LLM's output message is mandatory. Well, it doesn't seem abnormal to get the final object produced by the chain in the _on_chain_end_ callback, but in that case I would expect the _on_llm_end_ callback to be called just before with the output message in parameter. But it is not. So, at this stage, it's not possible to intercept the raw LLM's output message for debugging purposes.

**Comment by eyurtsev** [comment]
```python
chain = LLMChain(llm=llm, prompt=chat_prompt, callbacks=[CustomCallBack()], output_parser=parser)
chain.invoke(input={"format_instructions": parser.get_format_instructions()})
```

Try:

```
chain = chat_prompt | llm | parser
chain.invoke(..., {'callbacks': [CustomCallback()])
```

`LLMChain` is a legacy object -- but we should take a look if there's a bug there in terms of callbacks not being used with .invoke

**Comment by eyurtsev** [comment]
OK not a bug. Unfortunately confusing legacy code -- callbacks that are passed to the constructor are LOCAL and are not inheritable, means that the callback will never be passed to the underlying LLM.

Callbacks should always be passed via `.invoke(..., {'callbacks': [callback_handler]})`  to avoid issues like these

**Comment by kevin-guimard-ext** [comment]
Your solution works. But I have several remarks:

- Conceptually, I think callbacks should rather be passed to the chain's constructor and not at invocation time, because they're fixed once for all
- But if you decide that they can only be passed at invocation time, please update the LLMChain's constructor and the documentation accordingly
- Now, I do receive the raw output sent by the LLM in the on_llm_end callback, but it's stored in a complex object called LLMResult. So, what is the right way to get the raw output, response.generations[0][0].text or response.generations[0][0].message.content? They are identical in my case.
