### ISSUE TITLE
Resource not found error trying to use chromadb with Azure Open AI

### ISSUE THREAD

**Issue by sameermahajan** [langchain-ai/langchain#15878]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

import os
import openai
import sys

import panel as pn  # GUI
pn.extension()

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv()) # read local .env file

import datetime
current_date = datetime.datetime.now().date()
if current_date < datetime.date(2023, 9, 2):
    llm_name = "gpt-3.5-turbo-0301"
else:
    llm_name = "gpt-3.5-turbo"
print(llm_name)

from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings

from langchain.document_loaders import PyPDFLoader

docs = PyPDFLoader("sameer_mahajan.pdf").load()

from langchain.text_splitter import TokenTextSplitter

text_splitter = TokenTextSplitter(chunk_size=1, chunk_overlap=0)
splits = text_splitter.split_documents(docs)

embedding = OpenAIEmbeddings(
        deployment = "embeddings",
        openai_api_key = os.environ['OPENAI_API_KEY'],
        openai_api_base = os.environ['OPENAI_ENDPOINT'],
        openai_api_version = os.environ['OPENAI_DEPLOYMENT_VERSION'],
        openai_api_type = "azure",
        chunk_size = 1)

vectordb = Chroma.from_documents(
    documents=splits,
    embedding=embedding,
    persist_directory=persist_directory
)

### Description

I expect vectordb to persist for my further chatbot however I get an exception of 

`NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`

### System Info

python 3.10.2
embedding model text-embedding-ada-002

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by leedtan** [comment]
Also having the same issue with @RyanSaxe

**Comment by sameermahajan** [comment]
@dosu-bot cannot be tagged. Hope this gets picked up however. I have tried everything that you have suggested without luck. here are additional things you have requested:
- model deployment name: embeddings
- azure endpoint: https://gavsgpt-openai.openai.azure.com/
Additionally
- model used in deployment: text-embedding-ada-002
- API version: 2023-06-01-preview 
Please let me know.

**Comment by sameermahajan** [comment]
I could address this using langchain.embeddings.azure_openai.AzureOpenAIEmbeddings

**Comment by Smfakhoury** [comment]
I ran into the same issue and I think this is a bug. Specifying `azure_endpoint` doesn't work but specifying the (now outdated) `openai_api_base` with the deployment url does work.

  I solved this by adding the deployment path "/openai/deployments/model-name" to the end of my endpoint url. e.g:

```
embeddings = AzureOpenAIEmbeddings(
                                openai_api_base='https://MY-ENDPOINT/openai/deployments/text-embedding-ada-002/',
...
)
```

**Comment by Avkashhirpara** [comment]
> I ran into the same issue and I think this is a bug. Specifying `azure_endpoint` doesn't work but specifying the (now outdated) `openai_api_base` with the deployment url does work.
> 
> I solved this by adding the deployment path "/openai/deployments/model-name" to the end of my endpoint url. e.g:
> 
> ```
> embeddings = AzureOpenAIEmbeddings(
>                                 openai_api_base='https://MY-ENDPOINT/openai/deployments/text-embedding-ada-002/',
> ...
> )
> ```

I was facing the same error and @Smfakhoury your solutions worked for me 
Thank you
