### ISSUE TITLE
 argument needs to be of type (SquadExample, dict)

### ISSUE THREAD

**Issue by tempdeltavalue** [langchain-ai/langchain#15884]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
model_name = "Intel/dynamic_tinybert"

tokenizer = AutoTokenizer.from_pretrained(model_name, padding=True, truncation=True, max_length=512)

question_answerer = pipeline(
    "question-answering",
    model=model_name,
    tokenizer=tokenizer,
    return_tensors='pt'
)


llm = HuggingFacePipeline(
    pipeline=question_answerer,
    model_kwargs={"temperature": 0.7, "max_length": 50},
)


prompt_template = """
As literature critic answer me

question: {question}

context: {context}
"""

prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])


chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    chain_type_kwargs = {"prompt": prompt})

question = "Who is Hamlet ?"
answer = chain.invoke({"query": question})  # issue here <--
print(answer)
```

### Description

I tried to implement simple RetrievalQA from with langchain_chain.faiss vector search but I've faced with such assert, 
 argument needs to be of type (SquadExample, dict)
 
Here, there is an issue.
 answer = chain.invoke({"query": question})

Thank you in advance.

 

### System Info

Windows 10, python 3.11, langchain    0.1.0

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by tempdeltavalue** [comment]
_🤖_

but this is exactly what I'm doing 
prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])


chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    chain_type_kwargs = {"prompt": prompt})

question = "Who is Hamlet ?"
answer = chain.invoke({"query": question})

What should I change ?

**Comment by eyurtsev** [comment]
@tempdeltavalue Could you see if you can produce a minimal running example including imports, and tracestack. It'll make it easier for another person to copy the code and run it to help resolve your issue

**Comment by tempdeltavalue** [comment]
@eyurtsev I'm not sure what you mean by a minimal example. 

here's I tried to make RetrievalQA using hugging face local models
https://github.com/tempdeltavalue/temp_l/blob/main/main.py 

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter, CharacterTextSplitter

embedding_model_id = "sentence-transformers/all-MiniLM-L6-v2"

embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_id,
)

def generate_embeddings():
    chunk_size = 2048

    with open("data/shakespeare.txt") as f:
        text = f.read()

        text_splitter = CharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=0)
        pages = text_splitter.split_text(text)

        text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=100)
        texts = text_splitter.create_documents(pages)

    print(len(texts))



    embeddings_db = FAISS.from_documents(texts, embeddings)
    embeddings_db.save_local("faiss_index")

print("start load embeddings")
embeddings_db = FAISS.load_local("faiss_index", embeddings)
print("finish load embeddings")

retriever = embeddings_db.as_retriever(search_kwargs={"k": 10})


### prompt generation
 # Define prompt template

from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQA
from transformers import pipeline
from langchain_community.llms.huggingface_pipeline import HuggingFacePipeline
from transformers import AutoTokenizer

model_name = "Intel/dynamic_tinybert"

# Load the tokenizer associated with the specified model
tokenizer = AutoTokenizer.from_pretrained(model_name, padding=True, truncation=True, max_length=512)

question_answerer = pipeline(
    "question-answering",
    model=model_name,
    tokenizer=tokenizer,
    return_tensors='pt'
)

# Create an instance of the HuggingFacePipeline, which wraps the question-answering pipeline
# with additional model-specific arguments (temperature and max_length)
llm = HuggingFacePipeline(
    pipeline=question_answerer,
    model_kwargs={"temperature": 0.7, "max_length": 50},
)


prompt_template = """
As literature critic answer me

question: {question}

context: {context}
"""

prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])


chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    chain_type_kwargs = {"prompt": prompt})

question = "Who is Hamlet ?"
answer = chain.invoke({"query": question})
print(answer)

**Comment by tempdeltavalue** [comment]
@dosubot 

any suggestions ?

**Comment by tempdeltavalue** [comment]
@dosu-bot 

Any suggestions ?

**Comment by christiancopeland** [comment]
New here, so apologies for any incorrect formatting in my comment. I'm trying to get 'tiiuae/falcon-7b-instruct/falcon-7b-instruct' to run and I've gotten one step past your trace. 

Here's my trace now: KeyError: 'You need to provide a dictionary with keys {question:..., context:...}'

Looks like your main issue is the format of your inputs going to the model. Make sure it's a dictionary with a question and context, then you should be good to go. I reformatted my input and got no errors, but also got no output from the model. 

Here's my code so far:

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from transformers import AutoTokenizer, AutoModelForCausalLM, FalconForQuestionAnswering, FalconConfig
import transformers
import torch

model = "tiiuae/falcon-7b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model)

model = FalconForQuestionAnswering.from_pretrained(model, 
cache_dir='./workspaceFalcon/', torch_dtype=torch.bfloat16, device_map="auto", offload_folder="offload") ## cache the model weights

model.eval()

config = FalconConfig()

pipeline = transformers.pipeline(
    "question-answering",
    model=model,
    config=config,
    tokenizer=tokenizer,
    device_map="auto",
    max_length=400,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id)

pipeline({'context': 'A man went to a shop and bought a car.',
    'question': 'What did the man buy?'})

**Comment by christiancopeland** [comment]
To be more direct, I think once you change the line : answer = chain.invoke({"query": question}) to answer = chain.invoke({"question": question, "context": context}), you should be good to go.

**Comment by ajeetkharel** [comment]
The HuggingFacePipeline API doesn't support "question-answering" pipelines. Please look for alternate methods.
![image](https://github.com/langchain-ai/langchain/assets/45057204/117a602a-670d-4498-8bd7-965b2f39f2bb)

**Comment by ajeetkharel** [comment]
> The HuggingFacePipeline API doesn't support "question-answering" pipelines. Please look for alternate methods.
> 
> ![image](https://private-user-images.githubusercontent.com/45057204/302002455-3ce01834-5be0-4b1b-b4d2-23f5ad7e9a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjIwMDAsIm5iZiI6MTcwNjkyMTcwMCwicGF0aCI6Ii80NTA1NzIwNC8zMDIwMDI0NTUtM2NlMDE4MzQtNWJlMC00YjFiLWI0ZDItMjNmNWFkN2U5YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAwNTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ODY1Y2FjMjFjN2RlMWYzYTlmMmE5ZjM0MzgxNDI2Y2Q4ZTRkZTk5ZTg5YmQ0YjhkNzliNjRjOGY3ZDczNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aVJLQi5x1tge9JrvMBS0A2fnnwadnE_jbB-vbuMDIFw)

Alternatively you can use a "text2text-generation" models to achieve the task.

**Comment by tempdeltavalue** [comment]
fyi, you can probably do it like that

```
service_context = ServiceContext.from_defaults(embed_model=embed_model, llm=None) # HuggingFaceEmbedding

index = VectorStoreIndex(
    nodes, 
    service_context=service_context, 
    show_progress=True
)

retriever = index.as_retriever(similarity_top_k=5)

new_query_engine = loaded_index.as_query_engine()
new_query_engine.query("Who am I?")  
```

**Comment by ajeetkharel** [comment]
@tempdeltavalue 
Won't this only return you the relevant documents and not the actual llm result that you wanted?

**Comment by SjoerdGn** [comment]
I ran into the same problem, as did this blogpost: https://medium.com/international-school-of-ai-data-science/implementing-rag-with-langchain-and-hugging-face-28e3ea66c5f7
The problem is - I think - that [`QuestionAnsweringArgumentHandler` from the HuggingFace _transformers_ package](https://github.com/huggingface/transformers/blob/fc37f38915372c15992b540dfcbbe00a916d4fc6/src/transformers/pipelines/question_answering.py#L150), and specifically its `normalize` function, wants either a `SquadExample` object (with the context and question as separate attributes if I'm correct) or , or a dict in the form of `{"context":"<<context>>", "question":"<<question>>"}`. However, the functions it goes through before it gets to this `QuestionAnsweringArgumentHandler`, [`self.llm.generate_prompt` in the class `LLMChain`](https://github.com/langchain-ai/langchain/blob/c1bb5fd498427bef3749dbba41d2483148f53f35/libs/langchain/langchain/chains/llm.py#L115), creates a prompt (first packaged in an object), i.e. a string, from the context and question.

It seems like it's not an easy fix in the _langchain_ package, so I'm now looking into a workaround in the _transformers_ package.

**Comment by SjoerdGn** [comment]
If you fix the problem mentioned in my previous answer:

> I ran into the same problem, as did this blogpost: https://medium.com/international-school-of-ai-data-science/implementing-rag-with-langchain-and-hugging-face-28e3ea66c5f7 The problem is - I think - that [`QuestionAnsweringArgumentHandler` from the HuggingFace _transformers_ package](https://github.com/huggingface/transformers/blob/fc37f38915372c15992b540dfcbbe00a916d4fc6/src/transformers/pipelines/question_answering.py#L150), and specifically its `normalize` function, wants either a `SquadExample` object (with the context and question as separate attributes if I'm correct) or , or a dict in the form of `{"context":"<<context>>", "question":"<<question>>"}`. However, the functions it goes through before it gets to this `QuestionAnsweringArgumentHandler`, [`self.llm.generate_prompt` in the class `LLMChain`](https://github.com/langchain-ai/langchain/blob/c1bb5fd498427bef3749dbba41d2483148f53f35/libs/langchain/langchain/chains/llm.py#L115), creates a prompt (first packaged in an object), i.e. a string, from the context and question.
> ....

by for example putting the following block of code 

```python
            if isinstance(item, str):
               # split the formatted prompts back into parts
               # to retrieve the context and question separately
                item_split = item\
                    .replace(
                        'answer the question:',
                        '\n------------\n'
                    )\
                    .split('\n------------\n')
                item = {
                    'context':item_split[1],
                    'question':item_split[3]
                }
```

between [line 218](https://github.com/huggingface/transformers/blob/fc37f38915372c15992b540dfcbbe00a916d4fc6/src/transformers/pipelines/question_answering.py#L218) and 219 of _question_answering.py_, you're back to the point @ajeetkharel mentioned (see quoted comment below); 'question-answering' pipelines are not supported: the error at [line 222 of _huggingface_pipeline.py_](https://github.com/langchain-ai/langchain/blob/8381f859b41f92f9bb172c59f98735ebc928ed4c/libs/community/langchain_community/llms/huggingface_pipeline.py#L222) is raised. It seems from the code that this is not some kind of 'just adding the word question-answering'-thing, but that the 'question-answering' pipeline really works differently from what is supported.

> The HuggingFacePipeline API doesn't support "question-answering" pipelines. Please look for alternate methods.
> 
> ![image](https://private-user-images.githubusercontent.com/45057204/302002455-3ce01834-5be0-4b1b-b4d2-23f5ad7e9a4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NDQ0OTksIm5iZiI6MTcwODU0NDE5OSwicGF0aCI6Ii80NTA1NzIwNC8zMDIwMDI0NTUtM2NlMDE4MzQtNWJlMC00YjFiLWI0ZDItMjNmNWFkN2U5YTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDE5MzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YTkwMjIyZWU0YzA0N2JiM2E4Nzg3YmMwNTc0NjA0N2VmZWVmZWQ3ZDhmNzYxYjJjNzQ3YzIzYzIzMmQ3NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3VyI2aZIaNJFHDC-DrXjCq6T8quZmguvY2kKO9TokII)

**Comment by Anushagudipati** [comment]
ValueError while running RetrievalQA.from_chain_type(llm=llm, chain_type="refine", retriever=retriever, return_source_documents=False)


# Specify the model name you want to use
model_name = "Intel/dynamic_tinybert"

# Load the tokenizer associated with the specified model
tokenizer = AutoTokenizer.from_pretrained(model_name, padding=True, truncation=True, max_length=512)

# Define a question-answering pipeline using the model and tokenizer
question_answerer = pipeline(
    "question-answering", 
    model=model_name, 
    tokenizer=tokenizer,
    return_tensors='pt'
)

# Create an instance of the HuggingFacePipeline, which wraps the question-answering pipeline
# with additional model-specific arguments (temperature and max_length)
llm = HuggingFacePipeline(
    pipeline=question_answerer,
    model_kwargs={"temperature": 0.7, "max_length": 512},
)
# Create a retriever object from the 'db' with a search configuration where it retrieves up to 4 relevant splits/documents.
retriever = db.as_retriever(search_kwargs={"k": 4})

# Create a question-answering instance (qa) using the RetrievalQA class.
# It's configured with a language model (llm), a chain type "refine," the retriever we created, and an option to not return source documents.
qa = RetrievalQA.from_chain_type(llm=llm, chain_type="refine", retriever=retriever, return_source_documents=False)

print(qa.input_keys)
question = "Who is  Julius Steele Barnes?"
# result = qa.invoke({"query": question})
result = qa({"query": question, "chat_history": ""})
print(result["result"])

ValueError                                Traceback (most recent call last)
<ipython-input-96-4568330b032e> in <cell line: 4>()
      2 # result = qa.invoke({"query": question})
      3 print(qa.input_keys)
----> 4 result = qa({"query": question, "chat_history": ""})
      5 print("hi")
      6 print(result,"*")

27 frames
/usr/local/lib/python3.10/dist-packages/transformers/pipelines/question_answering.py in normalize(self, item)
    170 
    171             return QuestionAnsweringPipeline.create_sample(**item)
--> 172         raise ValueError(f"{item} argument needs to be of type (SquadExample, dict)")
    173 
    174     def __call__(self, *args, **kwargs):

ValueError: Context information is below. 
------------
"Julius Steele Barnes (23 February 1792 \u2013 12 November 1870) was an American physician. Besides being a skillful practitioner, and devoted to his calling, he also labored heartily for the social good of the community. He served one term as Connecticut State Senator, and held for a time the office of Judge of Probate."
------------
Given the context information and not prior knowledge, answer the question: Who is  Julius Steele Barnes?
 argument needs to be of type (SquadExample, dict)

**Comment by tawhidwasik08** [comment]
Downgrading to `langchain==0.1.7` does not show this error for me (at least for now).

**Comment by VipulSingh2** [comment]
# Set up the RAG chain
# Corrected the import statement
output_parser = StrOutputParser()
retriever = vector_db.as_retriever()
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | output_parser     
)

# Query the RAG chain
response = rag_chain.invoke("What is RAG system?")
print(response)
 i am making chains like this but still getting error
