### ISSUE TITLE
Integration for OpenAI image gen with v1 sdk

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#15901]
### Feature request

Tool for OpenAI image generation API using openai's v1 sdk https://platform.openai.com/docs/guides/images

### Motivation

Useful for image-gen applications with language interfaces

**Comment by paulonasc** [comment]
@baskaryan 👋 can I pick this ticket up?

**Comment by baskaryan** [comment]
> @baskaryan 👋 can I pick this ticket up?

definitely! 🙏
