### ISSUE TITLE
OpenAI speech-to-text API integration

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#15900]
### Feature request

Tool for OpenAI speech-to-text (using openai v1)  https://platform.openai.com/docs/guides/speech-to-text

### Motivation

Useful for building voice interfaces

**Comment by h0rv** [comment]
Hi, I am starting to work on this feature!

**Comment by h0rv** [comment]
Hi @baskaryan, would you be able to review the open PR? Then I can do the Speech-to-Text (they'll be similar and I will model the API off of the Text-to-Speech). Thanks!
