### ISSUE TITLE
AzureOpenAI doesn't work with GPT 3.5 Turbo deployed models

### ISSUE THREAD

**Issue by sergeyk93** [langchain-ai/langchain#1591]
Looks like a similar issue as what OpenAI had when the model was introduced(arguments like best_of, logprobs weren't supported).

**Comment by XUWeijiang** [comment]
My solution is to subclass AzureOpenAPI (I also add stop parameter, as it is needed according to azure document.):
```python
class NewAzureOpenAI(AzureOpenAI):
    stop: List[str] = None
    @property
    def _invocation_params(self):
        params = super()._invocation_params
        # fix InvalidRequestError: logprobs, best_of and echo parameters are not available on gpt-35-turbo model.
        params.pop('logprobs', None)
        params.pop('best_of', None)
        params.pop('echo', None)
        params['stop'] = self.stop
        return params
```

**Comment by sergeyk93** [comment]
Thanks @XUWeijiang. The problem with that approach is that you'll have to know in advance if the model is gpt 3.5, and the azure deployment name doesn't state that. I'm trying to build something more generic that can work with any set of params. In the OpenAI scenario, the framework handles it(even if we use the OpenAI wrapper), just not in the Azure scenario.

**Comment by aj-dev-smith** [comment]
It's unclear to me whether or not #1673 fixed this issue.  From my tests it doesn't appear so.  Is there any worked planned to address this issue at the moment?

**Comment by ekzhu** [comment]
@aj-dev-smith for chat models I think it's better to use `AzureChatOpenAI` instead.  See the other comments in #1673 if that helps.

**Comment by geg00** [comment]
[https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html](https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html)
This link does not work if you attempt to use gpt-35-turbo 

Now if you use the @XUWeijiang  it is going to work but 

I'm glad that @ekzhu  is working on the AzureChatOpenAI solution but I don't see how this will help with the summarization of long documents.

**Comment by ekzhu** [comment]
Specifically what is the issue? Can you copy and paste the error?

**Comment by ekzhu** [comment]
This following code works for me:

```python
from langchain.chat_models import AzureChatOpenAI
from langchain.text_splitter import CharacterTextSplitter
from langchain.schema import HumanMessage

llm = AzureChatOpenAI(
    deployment_name="gpt-35-turbo",
    temperature=0,
    openai_api_version="2023-03-15-preview",
)

text_splitter = CharacterTextSplitter()

print(llm([HumanMessage(content="Tell me a joke")]))
```

It is `deployment_name` not `deployment_id`, which probably explains the error message you got. Also `AzureOpenAI` class doesn't work with the chat completion API. So you need to use the `AzureChatOpenAI` class.

**Comment by ekzhu** [comment]
See this doc: https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html

**Comment by nanditamohan** [comment]
@ekzhu this was working for me Monday, but this morning, I see this issue using gpt-35-turbo, due to the same naming discrepancy between AOAI and OpenAI.... looks like Langchain may be checking for the decimal somewhere in the on_llm_end callback:

```
File "generator.py", line 282, in _get_citations_and_result
    result = chain(
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/combine_documents/base.py", line 56, in _call
    output, extra_return_dict = self.combine_docs(docs, **other_keys)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/combine_documents/stuff.py", line 89, in combine_docs
    return self.llm_chain.predict(**inputs), {}
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 83, in generate_prompt
    self.callback_manager.on_llm_end(output, verbose=self.verbose)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/shared.py", line 47, in on_llm_end
    self._callback_manager.on_llm_end(response, **kwargs)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/base.py", line 159, in on_llm_end
    handler.on_llm_end(response)
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/openai_info.py", line 78, in on_llm_end
    completion_cost = get_openai_model_cost_per_1k_tokens(
  File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/openai_info.py", line 39, in get_openai_model_cost_per_1k_tokens
    raise ValueError(
ValueError: Unknown model: gpt-35-turbo. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-0314, gpt-4-completion, gpt-4-0314-completion, gpt-4-32k, gpt-4-32k-0314, gpt-4-32k-completion, gpt-4-32k-0314-completion, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-ada-001, ada, text-babbage-001, babbage, text-curie-001, curie, text-davinci-003, text-davinci-002, code-davinci-002
```
Do you know what the issue could be?

**Comment by ekzhu** [comment]
> @ekzhu this was working for me Monday, but this morning, I see this issue using gpt-35-turbo, due to the same naming discrepancy between AOAI and OpenAI.... looks like Langchain may be checking for the decimal somewhere in the on_llm_end callback:
> 
> ```
> File "generator.py", line 282, in _get_citations_and_result
>     result = chain(
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
>     raise e
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
>     outputs = self._call(inputs)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/combine_documents/base.py", line 56, in _call
>     output, extra_return_dict = self.combine_docs(docs, **other_keys)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/combine_documents/stuff.py", line 89, in combine_docs
>     return self.llm_chain.predict(**inputs), {}
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 151, in predict
>     return self(kwargs)[self.output_key]
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 116, in __call__
>     raise e
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/base.py", line 113, in __call__
>     outputs = self._call(inputs)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 57, in _call
>     return self.apply([inputs])[0]
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 118, in apply
>     response = self.generate(input_list)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chains/llm.py", line 62, in generate
>     return self.llm.generate_prompt(prompts, stop)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/chat_models/base.py", line 83, in generate_prompt
>     self.callback_manager.on_llm_end(output, verbose=self.verbose)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/shared.py", line 47, in on_llm_end
>     self._callback_manager.on_llm_end(response, **kwargs)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/base.py", line 159, in on_llm_end
>     handler.on_llm_end(response)
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/openai_info.py", line 78, in on_llm_end
>     completion_cost = get_openai_model_cost_per_1k_tokens(
>   File "/azureml-envs/model-eval-env/lib/python3.8/site-packages/langchain/callbacks/openai_info.py", line 39, in get_openai_model_cost_per_1k_tokens
>     raise ValueError(
> ValueError: Unknown model: gpt-35-turbo. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-0314, gpt-4-completion, gpt-4-0314-completion, gpt-4-32k, gpt-4-32k-0314, gpt-4-32k-completion, gpt-4-32k-0314-completion, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-ada-001, ada, text-babbage-001, babbage, text-curie-001, curie, text-davinci-003, text-davinci-002, code-davinci-002
> ```
> 
> Do you know what the issue could be? I believe this is langchain 0.0.128

For Azure Open AI the endpoint doesn't check for model name so you can just use one of the valid model name to pass langchain's validator. Just make sure you set `deployment_name` to match your deployment name on Azure Open AI portal.

**Comment by nanditamohan** [comment]
Ah I see - so when initializing the AzureChatOpenAI in langchain  - I should set deployment_name to match AOAI deployment name, but model_name to match OpenAI model naming (with decimal point included)? 

Wondering if it would be better if this translation should happen at the langchain validation layer, as I'd imagine AOAI customers assume model_name should be passed in to match whats in AOAI

**Comment by ekzhu** [comment]
> Ah I see - so when initializing the AzureChatOpenAI in langchain - I should set deployment_name to match AOAI deployment name, but model_name to match OpenAI model naming (with decimal point included)?

yes. 

> Wondering if it would be better if this translation should happen at the langchain validation layer, as I'd imagine AOAI customers assume model_name should be passed in to match whats in AOAI

Right. You can submit a PR to fix this -- I know @hwchase17  is quite fast in responding to PR.

**Comment by ww1126811502** [comment]
Just use ChatOpenAI, because gpt-3.5 is a chat_model:

```
chat = ChatOpenAI(deployment_id=gptmodel,
                  model_kwargs={"api_key": openai.api_key, "api_base": openai.api_base, "api_type": openai.api_type,
                                "api_version": openai.api_version, },
                  model_name="gpt-35-turbo")

print(chat([HumanMessage(content="Translate this sentence from English to French. I love programming.")]))
```

**Comment by Joldnine** [comment]
Here is how I make it work:

```
        AzureChatOpenAI(
            temperature=0.01,
            deployment_name="gpt-35-turbo",
            openai_api_version="2023-03-15-preview",
        )
```

**Comment by szelesaron** [comment]
> 

My issue was using `ChatOpenAI` instead of  `AzureChatOpenAI`, thank you.
