### ISSUE TITLE
add_texts function in OpenSearchVectorSearch class doesn't create embeddings as expected

### ISSUE THREAD

**Issue by neha52** [langchain-ai/langchain#1592]
`add_texts` function takes `texts` which are meant to be added to the OpenSearch vector domain.
These texts are then passed to compute the embeddings using following code,
```
embeddings = [
            self.embedding_function.embed_documents(list(text))[0] for text in texts
]
```
which doesn't create expected embeddings with OpenAIEmbeddings() because the text isn't passed correctly.

whereas, 
`embeddings = self.embedding_function.embed_documents(texts)` 
works as expected.

**Comment by naveentatikonda** [comment]
@neha52 I hope it is addressed now. Can you please take a look?
