### ISSUE TITLE
Please modify ChatOllama to allow the option to specify main_gpu

### ISSUE THREAD

**Issue by tourbut** [langchain-ai/langchain#15924]
### Feature request

When there are multiple GPUs available, the Ollama API provides the main_gpu option to specify which GPU to use as the main one. Please modify Langchain's ChatOllama to also include this feature.

![image](https://github.com/langchain-ai/langchain/assets/42790398/2c085dbf-0fe8-496f-b6d5-490d3a6b7571)

### Motivation

When running multiple tasks simultaneously on a server, it is necessary to designate specific processes for Ollama.

### Your contribution

None

**Comment by sweetkane** [comment]
It looks like the `_create_stream` function in `llms/ollama.py` will use "options" field in the kwargs of your function call if one is provided, so to specify the "main_gpu" option, something like the following might work.

```
options = chatOllama._default_params["options"]
options["main_gpu"] = 1
chatOllama.astream(..., kwargs={"options": options})
```
