### ISSUE TITLE
getting error while implementing memory

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#15938]
<code>
def set_custom_prompt():
    prompt_template = """Use the following pieces of information to answer the user's question.
    If you don't know the answer, just say that you don't know, don't try to make up an answer.
    Context: {context}
    Question: {question}
    Only return the helpful answer below and nothing else.
    Helpful answer:
    """
    prompt = PromptTemplate(template=prompt_template, input_variables=["context", "question"])
    return prompt
def retreival_qa_chain(chroma_db_path):
    prompt = set_custom_prompt() 
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    llm = ChatOpenAI(model="gpt-3.5-turbo-16k",temperature=0.1)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    memory = ConversationTokenBufferMemory(llm=llm, memory_key="chat_history", return_messages=True, input_key='question', output_key='answer')
    qa = RetrievalQA.from_chain_type(llm=llm,
                                       chain_type='stuff',
                                       retriever=retriever,
                                       return_source_documents=True,
                                       chain_type_kwargs={'prompt': prompt},
                                       memory=memory,
                                       )
    # qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever,return_source_documents=True)
    return qa
def create_global_qa_chain():
    chroma_db_path = "chroma-databases"
    folders = os.listdir(chroma_db_path)
    qa_chains = {}
    for index, folder in enumerate(folders):
        folder_path = f"{chroma_db_path}/{folder}"
        project = retreival_qa_chain(folder_path)
        qa_chains[folder] = project
    return qa_chains
def chat_langchain(new_project_qa, query):
    bot_response = new_project_qa({"query": query})
    result = bot_response['result']
   return result
qa_chains = create_global_qa_chain()
</code>
I am getting below error
    self.memory.save_context(inputs, outputs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain/memory/token_buffer.py", line 51, in save_context
    super().save_context(inputs, outputs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain/memory/chat_memory.py", line 37, in save_context
    input_str, output_str = self._get_input_output(inputs, outputs)
  File "/home/hs/env/lib/python3.8/site-packages/langchain/memory/chat_memory.py", line 33, in _get_input_output
    return inputs[prompt_input_key], outputs[output_key]
KeyError: 'question'

**Comment by keenborder786** [comment]
@deepak-habilelabs , change the the `ConversationTokenBufferMemory` input and output key to as follow:
```python
memory = ConversationTokenBufferMemory(llm=llm, memory_key="chat_history", return_messages=True, input_key='query', output_key='result')
```

This is because `RetrievalQA` input_key and output_key by default are `query` and `result` respectively. The ConversationTokenBufferMemory is used in conjuction with this main chain and not the `StuffDocumentsChain` that `RetrievalQA` is using it's call.
