### ISSUE TITLE
Allow encoding such as "encoding='utf8' " to be passed into TextLoader if the file is not the default system encoding.

### ISSUE THREAD

**Issue by lexsf** [langchain-ai/langchain#1593]

**Comment by AldawsariNLP** [comment]
any fix for this issue?

**Comment by jonosooty** [comment]
ah me too. German.

**Comment by allzero-kwon** [comment]
Korean, as well. :< Is there any update ?

**Comment by lexsf** [comment]
Yeah bot, still there.

**Comment by baskaryan** [comment]
Hi all, we do accept TextLoader(encoding=...) as of https://github.com/langchain-ai/langchain/pull/2250, is that what you're looking for?

Full [api reference here](https://api.python.langchain.com/en/latest/document_loaders/langchain_community.document_loaders.text.TextLoader.html#langchain_community.document_loaders.text.TextLoader)
