### ISSUE TITLE
Add the 'id' attribute to the Document class.

### ISSUE THREAD

**Issue by Casper-Mars** [langchain-ai/langchain#15982]
### Feature request

Add the 'id' attribute to the Document class. Or add a method to get id.

### Motivation

Adding an 'id' attribute makes data manipulation easier.
When using the Weaviate database, I need to manually set additional parameters to query the 'id', and it's not convenient to use.

### Your contribution

At the moment, there isn't one. I'd like to discuss this issue first.

**Comment by keenborder786** [comment]
@Casper-Mars You are suggesting that following class:

```python

class Document(Serializable):
    """Class for storing a piece of text and associated metadata."""

    page_content: str
    """String text."""
    metadata: dict = Field(default_factory=dict)
    """Arbitrary metadata about the page content (e.g., source, relationships to other
        documents, etc.).
    """

```

should have a additional attribute of id? Correct?
