### ISSUE TITLE
not able to use local llm endpoints in chains

### ISSUE THREAD

**Issue by sampratha28** [langchain-ai/langchain#15981]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

qa_chain = (
            RunnablePassthrough.assign(context=( lambda x: format_docs(x["context"])))
            | rag_prompt
            | local_llm_api()
            | StrOutputParser()
            )

### Description

I am trying to call my local api endpoint in the qa chain. 
The return type of the endpoint is a dict of list.
The error i am getting is  :
Expected a Runnable, callable or dict.Instead got an unsupported type: <class 'list'>

### System Info

python version - 3.11

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by keenborder786** [comment]
`local_llm_api` cannot be called as it you need it wrap it as a proper Runnable(BaseLanguageModel). Can you please send me more of your code related to `local_llm_api`, perhaps then I might be better able to help you.
