### ISSUE TITLE
Idea: A memory similar to ConversationBufferWindowMemory but utilizing token length

### ISSUE THREAD

**Issue by Aratako** [langchain-ai/langchain#1598]
In the current `ConversationBufferWindowMemory`, only the last `k` interactions are kept while the conversation history prior to that is deleted.
A memory similar to this, which keeps all conversation history below `max_token_limit` and deletes conversation history from the beginning when it exceeds the limit, could be useful.
This is similar to `ConversationSummaryBufferMemory`, but instead of summarizing the conversation history when it exceeds `max_token_limit`, it simply discards it.
It is a very simple memory, but I think it could be useful in some situations.

**Comment by hwchase17** [comment]
this is a great, hope to get it implemented soon! given the similarity with `ConversationSummaryBufferMemory`, shouldn't be that bad
