### ISSUE TITLE
The `dict` method is deprecated; use `model_dump` instead [pydantic]

### ISSUE THREAD

**Issue by lucas-labs** [langchain-ai/langchain#15997]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

The followiwng simple example will log the warning:

```python
from langchain_openai import AzureChatOpenAI
from langchain.schema import HumanMessage

chat_llm = AzureChatOpenAI()

chat_llm.invoke([HumanMessage(content='howdy!')])
```

### Description

I'm seeing a few warning logs saying that langchain-openai is using a deprecated method from pydantic: `dict`

```txt
.venv/Lib/site-packages/langchain_openai/chat_models/azure.py:199: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
    response = response.dict()

tests/test_zllm_completion.py::test_prompt
  .venv/Lib/site-packages/langchain_openai/llms/base.py:344: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
    response = response.dict()
```

Here:

https://github.com/langchain-ai/langchain/blob/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9/libs/partners/openai/langchain_openai/chat_models/azure.py#L199

And here:

https://github.com/langchain-ai/langchain/blob/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9/libs/partners/openai/langchain_openai/llms/base.py#L344

(There might me other cases)

### System Info

langchain==0.1.0
Microsoft Windows 11 Pro
Python 3.11.3

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by MusicOfWind** [comment]
> ### 查看了其他资源
> * [x] 我为这个问题添加了一个非常具有描述性的标题。[x] 我使用集成搜索搜索了 LangChain 文档。[x] 我使用 GitHub 搜索查找类似的问题，但没有找到。
> 
> ### 示例代码
> 以下简单示例将记录警告：
> 
> from langchain_openai import AzureChatOpenAI
> from langchain.schema import HumanMessage
> 
> chat_llm = AzureChatOpenAI()
> 
> chat_llm.invoke([HumanMessage(content='howdy!')])
> ### 描述
> 我看到一些警告日志表明 langchain-openai 正在使用 pydantic 中已弃用的方法：`dict`
> 
> .venv/Lib/site-packages/langchain_openai/chat_models/azure.py:199: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
>     response = response.dict()
> 
> tests/test_zllm_completion.py::test_prompt
>   .venv/Lib/site-packages/langchain_openai/llms/base.py:344: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
>     response = response.dict()
> 这里：
> 
> [langchain/libs/合作伙伴/openai/langchain_openai/chat_models/azure.py](https://github.com/langchain-ai/langchain/blob/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9/libs/partners/openai/langchain_openai/chat_models/azure.py#L199)
> 
> 199 行 [7b084b4](/langchain-ai/langchain/commit/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9)
> 
>  响应 = 响应. dict ()
> 还有这里：
> 
> [langchain/libs/合作伙伴/openai/langchain_openai/llms/base.py](https://github.com/langchain-ai/langchain/blob/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9/libs/partners/openai/langchain_openai/llms/base.py#L344)
> 
> 344 行 [7b084b4](/langchain-ai/langchain/commit/7b084b4cc768a8e5cddc29bfdfb6e5dc1003a5d9)
> 
>  响应 = 响应. dict ()
> （可能还有其他情况）
> 
> ### 系统信息
> langchain==0.1.0 微软 Windows 11 Pro Python 3.11.3
> 
> ### 相关组件
> * [x] 法学硕士/聊天模型[ ] 嵌入模型[ ] 提示 / 提示模板 / 提示选择器[ ] 输出解析器[ ] 文档加载器[ ] 向量存储/检索器[ ] 记忆[ ] 代理人/代理执行者[ ] 工具/工具包[ ] 链条[ ] 回调/跟踪[ ] 异步

请问这个报错你咋解决的
