### ISSUE TITLE
KeyError: 'intermediate_steps' when using Wikipedia tool within the create_react_agent function

### ISSUE THREAD

**Issue by belafdil-chakib** [langchain-ai/langchain#16006]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```
from langchain import hub

from langchain.agents import create_react_agent
from langchain.tools import Tool
from langchain_community.utilities.wikipedia import WikipediaAPIWrapper
from langchain_community.llms.openai import OpenAI

instructions = """You are an agent designed to write and execute python code to answer questions.
You have access to Wikipedia, which you can use to search informations.
Be smart and select the correct wikipedia for a specific search when several are available.
"""
base_prompt = hub.pull("langchain-ai/react-agent-template")
prompt = base_prompt.partial(instructions=instructions)

wiki = WikipediaAPIWrapper()
wiki_tool = Tool(
    name="wikipedia",
    description="A wikipedia tool that allow to search in it",
    func=wiki.run,
)

agent = create_react_agent(OpenAI(name="gpt-3.5-turbo", temperature=0), tools=[wiki_tool], prompt=prompt)
print(agent.invoke({"input":"What is Nostradamus know for"}) )
```

### Description

I was trying to use the Wikipedia tool in a ReAct agent. I thought it will run smoothly but a KeyError intermediate_step trigged

### System Info

langchain                                0.1.0
langchain-community            0.0.12
langchain-core                       0.1.10
langchain-experimental         0.0.49
langchainhub                         0.1.14
langsmith                               0.0.80
wikipedia                                1.4.0

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by keenborder786** [comment]
A Agent cannot work on its own, it needs to have an AgentExecutor to work. Therefore you need to wrap your code as follow:

```python
instructions = """You are an agent designed to write and execute python code to answer questions.
You have access to Wikipedia, which you can use to search informations.
Be smart and select the correct wikipedia for a specific search when several are available.
"""
base_prompt = hub.pull("langchain-ai/react-agent-template")
prompt = base_prompt.partial(instructions=instructions)
print(prompt)
wiki = WikipediaAPIWrapper()
wiki_tool = Tool(
    name="wikipedia",
    description="A wikipedia tool that allow to search in it",
    func=wiki.run,
)

agent = create_react_agent(OpenAI(name="gpt-3.5-turbo", temperature=0), tools=[wiki_tool], prompt=prompt)
agent_executor = AgentExecutor.from_agent_and_tools(agent = agent, tools=[wiki_tool]) # Add this line.


```

**Comment by belafdil-chakib** [comment]
Thank you it worked !
