### ISSUE TITLE
unclear docs for using existing Weaviate database

### ISSUE THREAD

**Issue by nick-youngblut** [langchain-ai/langchain#16007]
### Issue with current documentation:

The [Weaviate docs](https://python.langchain.com/docs/integrations/vectorstores/weaviate) just show examples of using `Weaviate.from_documents()` or `Weaviate.from_texts()`, but do not describe how to use an existing database with embedded documents already stored in the database. 

Moreover, the descriptions of the `index_name` or `text_key` that are required when calling `Weaviate()` are not described anywhere in the [Weaviate docs](https://python.langchain.com/docs/integrations/vectorstores/weaviate), and `index_name` seems to be very misleading, given that it should be the name of the Weaviate *class*. 

A naive attempt of:

```python
import os
import dotenv
import weaviate
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_community.vectorstores import Weaviate
from langchain_core.runnables import RunnablePassthrough

dotenv.load_dotenv()

llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo")

client = weaviate.Client(
    url="http://34.170.94.90",
    auth_client_secret=weaviate.AuthApiKey(os.environ["WEAVIATE_API_KEY"])
)

db = Weaviate(client, 'my_class_name', 'text')

retriever = db.as_retriever()

chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt 
    | llm 
    | output_parser
)

chain.invoke({"input" : "My particular query"})
```

Results in the error:

```
ValueError: Error during query: [{'locations': [{'column': 46, 'line': 1}], 'message': 'Syntax Error GraphQL request (1:46) Expected Name, found String "input"\n\n1: {Get{my_class_name(limit: 4 nearText: {concepts: [{"input": "My particular query"}]} ){text}}}\n                                                ^\n', 'path': None}]
```

...which isn't too helpful on understanding the issue. 

Note: I did actually use the correct class name instead of `my_class_name`. 

### Idea or request for content:

It would be very helpful to include an example of using an existing Weaviate database, which included inspecting the DB schema to determine the values to use for `index_name` and `text_key`.

**Comment by MXall0c** [comment]
@dosu-bot this helps, but does not illustrate how to incorporate embeddings into the query.

**Comment by nick-youngblut** [comment]
@pi-crust no, I was never able to use `db.as_retriever()` without an error.

**Comment by MkButterfingers** [comment]
@nick-youngblut I was hoping i would find the answer here. Apparently llamaindex allows you to use an existing weaviate vector store though.

**Comment by nick-youngblut** [comment]
> Apparently llamaindex allows you to use an existing weaviate vector store though

Thanks @MkButterfingers for the advice. I am currently using llama-index with Weaviate.

**Comment by Angular-ngmodel-showy** [comment]
I see the resolution



https://automapperfionn.github.io/uLi5NMLo8GweRgMeZiLazq6IyGHMsuHzEn/
