### ISSUE TITLE
trl-peft example scripts not visible to public

### ISSUE THREAD

**Issue by Lavenderjiang** [langchain-ai/langchain#1606]
The new [blog post](https://github.com/huggingface/blog/blob/main/trl-peft.md) for implementing LoRA + RLHF is great. Would appreciate if the example scripts are public! 

3 scripts mentioned in the blog posts:
[Script](https://github.com/lvwerra/trl/blob/peft-gpt-neox-20b/examples/sentiment/scripts/gpt-neox-20b_peft/s01_cm_finetune_peft_imdb.py) - Fine tuning a Low Rank Adapter on a frozen 8-bit model for text generation on the imdb dataset.
[Script](https://github.com/lvwerra/trl/blob/peft-gpt-neox-20b/examples/sentiment/scripts/gpt-neox-20b_peft/s02_merge_peft_adapter.py) - Merging of the adapter layers into the base model’s weights and storing these on the hub.
[Script](https://github.com/lvwerra/trl/blob/peft-gpt-neox-20b/examples/sentiment/scripts/gpt-neox-20b_peft/s03_gpt-neo-20b_sentiment_peft.py) - Sentiment fine-tuning of a Low Rank Adapter to create positive reviews.

cross-link [pr](https://github.com/huggingface/blog/pull/920)

**Comment by younesbelkada** [comment]
Hey @Lavenderjiang 
Thanks a mile for reporting! The links has been fixed and they are now public on the blogpost

**Comment by Lavenderjiang** [comment]
> 

Thank you @younesbelkada !
