### ISSUE TITLE
ElasticsearchStore does not accept proxy

### ISSUE THREAD

**Issue by Uranium2** [langchain-ai/langchain#16135]
### Feature request

We should be able to pass some extra parameters to `ElasticsearchStore` in form of kwargs or predefined parameters.
For example, to allow usage of `RequestsHttpNode` that takes `https_proxy` / `http_proxy` / `no_proxy` env variables.

### Motivation

In some cases, all the external calls to internet/ELK (on cloud) must use a proxy, else it will be rejected by the firewall of the company.
The default behavior of `Elasticsearch` class from https://github.com/elastic/elasticsearch-py does not take by default proxy env variable and you need to set a `node_class` to `RequestsHttpNode`

### Your contribution

Instead of calling `ElasticsearchStore` from langchain, I duplicated locally the file and hardcoded in the `Elasticsearch` init the `node_class`.

``` python
from elastic_transport import RequestsHttpNodes

# https://github.com/langchain-ai/langchain/blob/e5cf1e2414a22c7465f0f47bd661ece183e88924/libs/community/langchain_community/vectorstores/elasticsearch.py#L593

es_client = elasticsearch.Elasticsearch(
    **connection_params,
    node_class=RequestsHttpNode,
    headers={"user-agent": ElasticsearchStore.get_user_agent()},
)
```

I am sure there's a better way and more global way to pass parameters to `Elasticsearch()`

**Comment by maxjakob** [comment]
It is possible to set the `Elasticsearch` client for an `ElastcisearchStore` using the `es_connection` argument:
```py
import elasticsearch
from elastic_transport import RequestsHttpNode
from langchain_community.vectorstores import ElasticsearchStore

es_client = elasticsearch.Elasticsearch(
    hosts=["http://localhost:9200"],  # or cloud_id etc.
    node_class=RequestsHttpNode,
)

es_store = ElasticsearchStore(index_name="foo", es_connection=es_client)
```
This way you can set the `node_class` and you do not have to copy and modify the whole implementation.
