### ISSUE TITLE
Implement vector length definition at init time in PGVector for indexing

### ISSUE THREAD

**Issue by Frank995** [langchain-ai/langchain#16132]
### Feature request

Allow manual definition of embedding column length in PGVector

### Motivation

Right now embeddings stores in PGVector are initialised with:
`embedding: Vector = sqlalchemy.Column(Vector(None))`
This won't allow indexing of the DB ([https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/howto-optimize-performance-pgvector](url))

### Your contribution

I can open a PR shortly to fix it

**Comment by RobertHH-IS** [comment]
Please get this into the next release - langchain is a ways behind llamaindex when it comes to pgvector support.  They already support defining your own table names, correct column init,  both index based retrieval methods, as well as hybrid search.  Langchain support is not production ready without just using SQL.
