### ISSUE TITLE
Inference Component Name header is required  (SageMaker RedShift Flan T5)

### ISSUE THREAD

**Issue by jamontesg** [langchain-ai/langchain#16150]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

llm = SagemakerEndpoint(
    endpoint_name=endpoint_name,
    endpoint_kwargs={ "CustomAttributes": "accept_eula=true,InferenceComponentName="+inference_component_name }, 
    region_name = region_name,
    
    credentials_profile_name = profile_name,
    model_kwargs = parameters,
    content_handler = content_handler,

)
print(str( llm.endpoint_kwargs ))

db = SQLDatabase.from_uri(REDSHIFT_ENDPOINT)

db_chain = SQLDatabaseSequentialChain.from_llm(
    llm, db, verbose=True, use_query_checker=True
)
try:
    results = db_chain.run(QUESTION_01)
    print(results)
except (ProgrammingError, ValueError, DataError) as exc:
    print(f"\n\n{exc}")

### Description

I am using a Sagemaker Flan T5 Xl model to ask  model and is ok, 
but when try to use langchain to query RedShift DB.
I have this error.
----> " Error raised by inference endpoint: An error occurred (ValidationError) when calling the InvokeEndpoint operation: Inference Component Name header is required for endpoints to which you plan to deploy inference components. Please include Inference Component Name header or consider using SageMaker models."

### System Info

model jumpstart-dft-hf-text2text-flan-t5 xxl
Python 3.11.6
boto3 1.34.19
langchain 0.1.0
langchain-community 0.0.12
langchain-core 0.1.10
langchain-experimental 0.0.49
sentence-transformers 2.2.2
SQLAlchemy 1.4.48

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by jamontesg** [comment]
solved using
pip install boto3==1.34.23

**Comment by AlvinKimata** [comment]
To resolve the issue, you can pass the `endpoint_kwargs` in the SagemakerEndpoint class:

```python
llm=SagemakerEndpoint(
        endpoint_name=endpoint_name,
        client=client,
        model_kwargs={"temperature": 0.1, "InferenceComponentName": inferenceComponentName},
        endpoint_kwargs={"InferenceComponentName": inferenceComponentName},
        content_handler=content_handler,
        streaming = False
```
