### ISSUE TITLE
Geopandas and Langchain blocking issue. 

### ISSUE THREAD

**Issue by k-a-mendoza** [langchain-ai/langchain#16156]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

The bug was found by trying to install [jupyter-ai](https://github.com/jupyterlab/jupyter-ai) via conda-forge. 
```install -c conda-forge jupyter_ai```

Basically, there is an incompatibility with the latest version of langchain and geopandas. 

### Description

Based on the bug report posted on the jupyter-ai github https://github.com/jupyterlab/jupyter-ai/issues/557#issue-2062998660 , it looks like langchain enforces a version of geopandas below 0.14. Could this be relaxed to allow for >0.14? There are many features of modern geopandas that make GIS workflows so much easier, and the current enforcement version  prevents langchain-dependent repositories from making full use of GIS-adjacent stacks.  

### System Info

The incompatibility arose while using an M1 apple silicon laptop. 

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by scottyhq** [comment]
Hi! Just wanted to reopen this one because Geopandas 1.0 has been out since June 24. It would be great to set 1.0 as the minimum version

https://github.com/geopandas/geopandas/releases/tag/v1.0.0
