### ISSUE TITLE
 No file/folder found for package langchain-monorepo

### ISSUE THREAD

**Issue by zcw5116** [langchain-ai/langchain#16170]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

none

### Description

In the HOME directory of the langchain source code, execute the following command:
poetry install --with lint,typing,test

However, the following errors are thrown, and I have a few questions to ask:
(1) Why do we need to perform a downgrade operation on modules like langchain-core, and how to avoid downgrading?
(2) Why can't the module langchain-monorepo be found?
(3) How to compile the source code of langchain in order to understand the principles of langchain and contribute code to langchain?

My development environment:
Python: Built on conda, Python version 3.8.18
Langchain: The master branch on GitHub.

Error message:

(langchain) [xiaobai@xiaobai langchain-master]$ poetry install --with lint,typing,test
Installing dependencies from lock file

Package operations: 0 installs, 4 updates, 0 removals

  • Downgrading langchain-core (0.1.10 /home/xiaobai/data/pro/python/langchain-master/libs/core -> 0.1.3 /home/xiaobai/data/pro/python/langchain-master/libs/core)
  • Downgrading langchain-community (0.0.12 /home/xiaobai/data/pro/python/langchain-master/libs/community -> 0.0.6 /home/xiaobai/data/pro/python/langchain-master/libs/community)
  • Downgrading langchain (0.1.0 /home/xiaobai/data/pro/python/langchain-master/libs/langchain -> 0.0.352 /home/xiaobai/data/pro/python/langchain-master/libs/langchain)
  • Downgrading langchain-experimental (0.0.49 /home/xiaobai/data/pro/python/langchain-master/libs/experimental -> 0.0.47 /home/xiaobai/data/pro/python/langchain-master/libs/experimental)

Installing the current project: langchain-monorepo (0.0.1)
The current project could not be installed: No file/folder found for package langchain-monorepo
If you do not want to install the current project use --no-root

### System Info

Python: Built on conda, Python version 3.8.18
Langchain: The master branch on GitHub.

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by k8si** [comment]
Boosting because I'm running into the same issue. Using poetry v1.7.1.

**Comment by robert501128** [comment]
Same here
