### ISSUE TITLE
Allow unstructured loaders to accept in-memory text

### ISSUE THREAD

**Issue by jackHedaya** [langchain-ai/langchain#1618]
Hi!

Unstructured has support for providing in-memory text. Would be a great addition as currently, developers have to write and then read from a file if they want to load documents from memory. 

Wouldn't mind opening the PR myself but want to make sure its a wanted feature before I get on it.

**Comment by ptkinvent** [comment]
+1 on this feature. would be very helpful especially for those of us building web apps around LLMs. users may want to upload a document and have it loaded in-memory rather than written to disk first.

**Comment by Pitchlab** [comment]
+1 on this feature, it seems trivial to add and it is relevant since my pipeline creates md in memory and I don't want to first save it only to load it right after. That is a pain.

**Comment by hargathor** [comment]
:+1: 
+1 for this feature, would be very useful to avoid unnecessary and long write then read from disk

**Comment by junruxiong** [comment]
+1
