### ISSUE TITLE
Gemini-Pro : Safety attributes params are missing with VertexAI

### ISSUE THREAD

**Issue by snayan06** [langchain-ai/langchain#16186]
### Checked other resources

- [ ] I added a very descriptive title to this issue.
- [x] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```
from langchain_community.llms.vertexai import VertexAI

VertexAI(model_name=GEMINI_PRO_MODEL_NAME, credentials=credentials, project=project_id,
                               streaming=streaming, temperature=0.0, n=1,
                               max_output_tokens=1000)
```

### Description

I am using the langchain latest version , and I am not able to pass the safety attributes to override the safety categories for gemini pro

### System Info

```
langchain==0.1.1
langchain-community==0.0.13
langchain-core==0.1.12
langchain-google-genai==0.0.6

```

`Python 3.9.5
`

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by pascalwhoop** [comment]
drive-by comment: Feels like passing through `kwargs` object should be a simple?
