### ISSUE TITLE
ChromaDB does not support filtering when using ```similarity_search``` or ```similarity_search_by_vector```

### ISSUE THREAD

**Issue by StephaneBereux** [langchain-ai/langchain#1619]
Whereas it should be possible to filter by metadata : 
- ```langchain.vectorstores.chroma.similarity_search``` takes a ```filter``` input parameter but do not forward it to ```langchain.vectorstores.chroma.similarity_search_with_score```
- ```langchain.vectorstores.chroma.similarity_search_by_vector``` don't take this parameter in input, although it could be very useful, without any additional complexity - and it would thus be coherent with the syntax of the two other functions

**Comment by ejdb00** [comment]
Feel free to close my duplicate fix or incorporate the unit tests from that branch into the original fix PR.

In either case, any idea when this might make it into a release? The ability to search over a subset of documents in a Chroma store will be monumentally easier than maintaining many different stores for different search spaces.

**Comment by ItsJustSmellz** [comment]
Hello, do we now have the ability to search in chroma over a subset of docs? i.e. we want to allow user to select multiple docs and pass that back to the 'filter' to force retriever to only get answers from those docs selected by user.
saw another thread mentioned 'search_kwargs' being passed into a chain, but that seems to be quite old so not sure if it's still valid.
