### ISSUE TITLE
DOC: documentation missing for invoke method of AgentExecutor class

### ISSUE THREAD

**Issue by glejdis** [langchain-ai/langchain#16195]
### Issue with current documentation:

I need to have access to the invoke method of langchain.agents.agent.AgentExecutor class. In the documentation, I can see only the definition but not the source code (please see below). It would be super helpful to be able to see the source code. I am getting some errors from this method which I cannot resolve. 

async ainvoke(input: Dict[str, Any], config: Optional[[RunnableConfig](https://api.python.langchain.com/en/stable/runnables/langchain_core.runnables.config.RunnableConfig.html#langchain_core.runnables.config.RunnableConfig)] = None, **kwargs: Any) → Dict[str, Any]

Link to the documentation: https://api.python.langchain.com/en/stable/agents/langchain.agents.agent.AgentExecutor.html#langchain.agents.agent.AgentExecutor 

Thank you so much!

**Comment by bhumikaZysk** [comment]
AgentExecutor method doesn't work, it's been deprecated. What is another alternative to initialize an agent and invoke it?
