### ISSUE TITLE
How to add multiple tables from two different databases and schema using SQLDatabase?

### ISSUE THREAD

**Issue by sbisen** [langchain-ai/langchain#16249]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

Is there a way to add multiple tables from different databases and schema using SQLDatabase?
For example: DB-1 has these tables- "city_stats", "country_stats"
Presently these tables are from 1 database = SQLDatabase(engine, include_tables=["city_stats", "country_stats"])

if we have 2 different databases DB-1(tables- "city_stats", "country_stats") and DB-2(tables- "company_stats", "team_stats") , how to include tables from 2 different databases?

### Description

Is there a way to add multiple tables from different databases and schema using SQLDatabase?
For example: DB-1 has these tables- "city_stats", "country_stats"
Presently these tables are from 1 database = SQLDatabase(engine, include_tables=["city_stats", "country_stats"])

if we have 2 different databases DB-1(tables- "city_stats", "country_stats") and DB-2(tables- "company_stats", "team_stats") , how to include tables from 2 different databases?

### System Info

langchain Version: 0.0.348
python Version: Python 3.9.18
OS: Mac OS M2 (Ventura 13.6.2)

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by sbisen** [comment]
Okay but if I am using the following code:
 db1= SQLDatabase.from_uri(snowflake_url, sample_rows_in_table_info=3, include_tables=["table_db1"])
 db2 = SQLDatabase.from_uri(snowflake_url, sample_rows_in_table_info=3, include_tables=["table_db2"])
How can I use 2 db in the below SQLDatabaseChain function?
SQLDatabaseChain.from_llm(
        llm,
        db, 
        prompt=few_shot_prompt,
        use_query_checker=True
        verbose=True,
        return_intermediate_steps=True,
        )

**Comment by mandeep-singh-lab49** [comment]
> ce SQLDatabaseChain function takes only 1 db argument, is there a way to include tables from both DB-1, DB-2?
> SQLDatabaseChain.from_llm(
> llm,
> db1,

@sbisen  did you get answer for it , like how to pass multiple dbs to chain ?

**Comment by haje01** [comment]
I'm in the same situation and really curious to know the answer to this question.
This use case is not uncommon at all!
