### ISSUE TITLE
RetrievalQA and AzureOpenAIEmbeddings lead to TypeError: cannot pickle '_thread.lock' object 

### ISSUE THREAD

**Issue by pranay518** [langchain-ai/langchain#16267]
i am also facing same issue. Now since openai has updated it's API hence i need to use openai==1.7.1 and langchain ==0.1.0.
because of this not able to pickle to local.
![image](https://github.com/langchain-ai/langchain/assets/28382171/6a9bc63b-d3f0-4013-a9a7-2107add17984)

Do we have issue with store = FAISS.from_texts(docs, embeddings, metadatas=metadatas) also?
because when trying to directly access store by using chain = RetrievalQAWithSourcesChain.from_chain_type(llm=llm, retriever=store.as_retriever())

then it is giving answer in 5 to 8 words. why? And this is happening in latest version only.
any idea .

**Comment by gwd999** [comment]
just for reference I added some snippets here https://github.com/langchain-ai/langchain/issues/14581#issuecomment-2028905295 that might help with pickle errors in some cases.
