### ISSUE TITLE
Gemini integration fails when a list of messages starting with AIMessage is given as input

### ISSUE THREAD

**Issue by andrei-rusu** [langchain-ai/langchain#16288]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
from langchain.schema import HumanMessage, AIMessage
llm = ChatGoogleGenerativeAI(model="gemini-pro")
llm([
    AIMessage(role="model", content="Hi"),
    HumanMessage(role="user", content="Tell me a joke")
]) # gives the error
```

### Description

* Trying to use Langchain's Gemini integration to quickly process a chat history that starts with an AIMessage, as given by the example [here](https://github.com/langchain-ai/streamlit-agent/blob/main/streamlit_agent/basic_streaming.py).
* The model should return a response with no errors because the last message I have given as an input has the role of ``user``, but instead it gives the error: "ChatGoogleGenerativeAIError: Invalid argument provided to Gemini: 400 Please ensure that multiturn requests ends with a user role or a function response."

### System Info

langchain==0.1.1
langchain-community==0.0.13
langchain-core==0.1.12
langchain-experimental==0.0.49
langchain-google-genai==0.0.6

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by andrei-rusu** [comment]
No, the issue is not related to ``SystemMessages``. Instead, I believe that the integration does not support starting the chat history with an ``AIMessage``.

**Comment by eyurtsev** [comment]
@efriis

**Comment by lkuligin** [comment]
What's your actual use case? 
Yes, afaik Gemini doesn't support history starting from AIMessage, since a human message always comes first.

**Comment by hinthornw** [comment]
It's a restriction on the Google API level, rather than the LangChain integration.

I could see a use case where the bot leads in a conversation (system info gives background, AI introduces itself for instance), but you'll have to get around that using a human message right now

**Comment by andrei-rusu** [comment]
Yes @hinthornw , that was precisely the use case. In particular, I was trying to adapt the streaming agent example from [here](https://github.com/langchain-ai/streamlit-agent/blob/main/streamlit_agent/basic_streaming.py), which passes to OpenAI the entire history, including the first greeting message. Indeed, one can pass that configuration back, if needed, as a human message, just like the adaptation for ``SytemMessage``. Annoying that one cannot just replace one model with another with ease, but it is what it is. Thank you both!
