### ISSUE TITLE
GooglePalm - NotImplementedError: Need to determine which default deprecation schedule to use. within ?? minor releases

### ISSUE THREAD

**Issue by kesavan22** [langchain-ai/langchain#16308]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

While initializing GooglePalm  LLM encountering the below Not Implemented Error.

Using Langchain 0.1.1

### Description

![image](https://github.com/langchain-ai/langchain/assets/91103199/4b237964-68c5-417d-b4fd-e90c89e78b7d)

### System Info

Name: langchain
Version: 0.1.1
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT

Requires: aiohttp, dataclasses-json, jsonpatch, langchain-community, langchain-core, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: kor, langchain-experimental

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by DarshanJoshi981** [comment]
@kesavan22 did you found any solution to this?
