### ISSUE TITLE
upgrade to pydantic v2

### ISSUE THREAD

**Issue by deven298** [langchain-ai/langchain#16306]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

All the chat model responses inheriting `BaseModel` are converted into `dict` using `response.dict()`. This throws the warning in the console
```bash
PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
  response = response.dict()
```

### Description

Need to update the package to migrate to the new pydantic version - https://docs.pydantic.dev/2.0/migration/#changes-to-pydanticbasemodel

### System Info

langchain==0.0.336

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by KartikeyBartwal** [comment]
Starting to work on async

**Comment by ekalosak** [comment]
To piggyback here, there's more than the deprecation warning at hand. Consider this minimal example (runs as-is, after pip install langchain_core and pydantic v2):
```py
#/bin/bash python3
"""
The issue is, essentially, that the langchain toolchain does not support pytdantic v2 objects.
Here, I use the JsonOutputParser because that's my main exposure to the v1/v2 painpoint.
"""
from pydantic import BaseModel, Field, field_validator   # <- v2 namespace
from langchain_core.output_parsers import JsonOutputParser

class A(BaseModel):
    a: int

JsonOutputParser(pydantic_object=A)
```
It produces this error:
```
Traceback (most recent call last):
  File "minimum_6841_test.py", line 12, in <module>
    JsonOutputParser(pydantic_object=A)
  File "venv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for JsonOutputParser
pydantic_object
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

So, in short, the JsonOutputParser can't handle pydantic v2 objects.

**Comment by ereli-okami** [comment]
would this help https://github.com/pydantic/bump-pydantic ?

**Comment by nnWhisperer** [comment]
Hello, when is pydantic v2 upgrade planned? It would be handy to use without the fears of version mismatch. Is there anything we could contribute to expedite it? Thank you
