### ISSUE TITLE
NotImplementedError: Need to determine which default deprecation schedule to use. within ?? minor releases

### ISSUE THREAD

**Issue by yashsri0786** [langchain-ai/langchain#16312]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

from langchain.llms import OpenAI
from langchain.agents import initialize_agent
from langchain.agents.agent_toolkits import ZapierToolkit
from langchain.utilities.zapier import ZapierNLAWrapper
import os
from dotenv import load_dotenv

load_dotenv()
os.getenv('ZAPIER_NLA_API_KEY')
os.getenv('OPENAI_API_KEY')
llm = OpenAI(temperature=.3)

zapier = ZapierNLAWrapper()
toolkit = ZapierToolkit.from_zapier_nla_wrapper(zapier)

agent = initialize_agent(toolkit.tools, llm, agent="zero-shot-react-description", verbose=True)
for tool in toolkit.tools:
    print(tool.name)
    print(tool.description)
    print("\n\n")

agent.run('Send an email to xxx@gmail.com saying hello from Dr. sss')

### Description

Gmail: Send Email
A wrapper around Zapier NLA actions. The input to this tool is a natural language instruction, for example "get the latest email from my bank" or "send a slack message to the #general channel". Each tool will have params associated with it that are specified as a list. You MUST take into account the params when creating the instruction. For example, if the params are ['Message_Text', 'Channel'], your instruction should be something like 'send a slack message to the #general channel with the text hello world'. Another example: if the params are ['Calendar', 'Search_Term'], your instruction should be something like 'find the meeting in my personal calendar at 3pm'. Do not make up params, they will be explicitly specified in the tool description. If you do not have enough information to fill in the params, just say 'not enough information provided in the instruction, missing <param>'. If you get a none or null response, STOP EXECUTION, do not try to another tool!This tool specifically used for: Gmail: Send Email, and has params: ['Body', 'To', 'Subject', 'Cc']

LinkedIn: Create Share Update
A wrapper around Zapier NLA actions. The input to this tool is a natural language instruction, for example "get the latest email from my bank" or "send a slack message to the #general channel". Each tool will have params associated with it that are specified as a list. You MUST take into account the params when creating the instruction. For example, if the params are ['Message_Text', 'Channel'], your instruction should be something like 'send a slack message to the #general channel with the text hello world'. Another example: if the params are ['Calendar', 'Search_Term'], your instruction should be something like 'find the meeting in my personal calendar at 3pm'. Do not make up params, they will be explicitly specified in the tool description. If you do not have enough information to fill in the params, just say 'not enough information provided in the instruction, missing <param>'. If you get a none or null response, STOP EXECUTION, do not try to another tool!This tool specifically used for: LinkedIn: Create Share Update, and has params: ['Comment', 'Visible_To']

> Entering new AgentExecutor chain...
I need to use the Gmail: Send Email tool to complete this task.
Action: Gmail: Send Email
Action Input: {'Body': 'Hello from Dr. Khala', 'To': 'birbal.srivastava@gmail.com', 'Subject': 'Hello', 'Cc': ''}Traceback (most recent call last):
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/agents/agent.py", line 1245, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/agents/agent.py", line 1095, in _take_next_step
    observation = tool.run(
                  ^^^^^^^^^
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/base.py", line 365, in run
    raise e
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/base.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/zapier/tool.py", line 143, in _run
    warn_deprecated(
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/_api/deprecation.py", line 295, in warn_deprecated
    raise NotImplementedError(
NotImplementedError: Need to determine which default deprecation schedule to use. within ?? minor releases

### System Info

Macbook pro

  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/base.py", line 365, in run
    raise e
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/base.py", line 337, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/tools/zapier/tool.py", line 143, in _run
    warn_deprecated(
  File "/Users/ss/.pyenv/versions/demo311/lib/python3.11/site-packages/langchain/_api/deprecation.py", line 295, in warn_deprecated
    raise NotImplementedError(
NotImplementedError: Need to determine which default deprecation schedule to use. within ?? minor releases

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by DarshanJoshi981** [comment]
@yashsri0786 did you found any solution to this? Downgrading langchain versions doesn't seems to work for me.

**Comment by giuliotosato** [comment]
any news about this?

**Comment by i-am-jar** [comment]
@yashsri0786 did you find a solution?

**Comment by ammarmunir4567** [comment]
Any solutions?

**Comment by csd12380** [comment]
![9f6de3a9b7702c45fc7d1513db46de7](https://github.com/langchain-ai/langchain/assets/85327584/413cfb58-9827-4d94-ba04-98816ae364f5)
将deprecation.py中的代码注释掉即可，

**Comment by csd12380** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。如有问题我会尽快给您答复，谢谢~
