### ISSUE TITLE
PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH? 

### ISSUE THREAD

**Issue by KaifAhmad1** [langchain-ai/langchain#16315]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

Here is my issue in brief '''

``` Python 
import os

poppler_path = 'C:\\Users\\Mohd Kaif\\Downloads\\poppler-23.08.0\\Library\\bin'
os.environ["PATH"] += os.pathsep + poppler_path
```

``` Python
directory = '/content/drive/MyDrive/History_QA_dataset'
```

``` Python
from pathlib import Path

def load_files(directory):
    documents = list(Path(directory).iterdir())
    return documents

documents = load_files(directory)
print(len(documents))
```

``` Python
documents
```

``` Python 
from langchain_community.document_loaders import UnstructuredPDFLoader
loader = UnstructuredPDFLoader("/content/drive/MyDrive/History_QA_dataset/ncert_s_modern_india_bipan_chandra_old_edition-1566975158976.pdf")
pages = loader.load()
```

### Description

Rasing this Type Error: 
``` Python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pdf2image/pdf2image.py](https://localhost:8080/#) in pdfinfo_from_path(pdf_path, userpw, ownerpw, poppler_path, rawdates, timeout, first_page, last_page)
    580             env["LD_LIBRARY_PATH"] = poppler_path + ":" + env.get("LD_LIBRARY_PATH", "")
--> 581         proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
    582 

14 frames
FileNotFoundError: [Errno 2] No such file or directory: 'pdfinfo'

During handling of the above exception, another exception occurred:

PDFInfoNotInstalledError                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/pdf2image/pdf2image.py](https://localhost:8080/#) in pdfinfo_from_path(pdf_path, userpw, ownerpw, poppler_path, rawdates, timeout, first_page, last_page)
    605 
    606     except OSError:
--> 607         raise PDFInfoNotInstalledError(
    608             "Unable to get page count. Is poppler installed and in PATH?"
    609         )

PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

### System Info

System Information:
Python version:` 3.10.10`
Operating System: `Windows 11`
Windows: 11
pip == 23.3.1
python == 3.10.10
long-chain == 0.1.0
transformers == 4.36.2
sentence_transformers == 2.2.2
unstructured == 0.12.0

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by 2Yash8** [comment]
brother does this resolve the error....? becaue im doing this on colab and its not fixing

**Comment by memohib** [comment]
> brother does this resolve the error....? because im doing this on colab and its not fixing

You can try running  !sudo install poppler-utils  in the colab. That might fix your issue

**Comment by Khubaibakramshirani** [comment]
@2Yash8 > brother does this resolve the error....? because im doing this on colab and its not fixing
Running below command helped me fix the error
!apt-get install poppler-utils
