### ISSUE TITLE
Chaining Chat to Codex

### ISSUE THREAD

**Issue by irthomasthomas** [langchain-ai/langchain#1631]
Hi, first off, I just want to say that I have been following this from the start, almost, and I see the amazing work you put in. It's an awesome project, well done!

Now that I finally have some time to dive in myself I'm hoping someone can help me bootstrap an idea. I want to chain chatgpt to Codex so that Chat will pass the coding task to codex for more accurate code and incorporate the code into it's answer and history/context.

Is this doable?

Many thanks!

**Comment by sualehasif** [comment]
According to almost all evals, `gpt-3.5-turbo` is much better at code than codex. So I would recommend sticking to the new turbo model.

**Comment by irthomasthomas** [comment]
> According to almost all evals, `gpt-3.5-turbo` is much better at code than codex. So I would recommend sticking to the new turbo model.

Oh that's interesting. Would you mind linking me to the evals? I just spent 20 minutes googling and could not find them (thank god google will be irrelevant soon, just like RIM and Nokia!)

**Comment by batmanscode** [comment]
> > According to almost all evals, `gpt-3.5-turbo` is much better at code than codex. So I would recommend sticking to the new turbo model.
> 
> Oh that's interesting. Would you mind linking me to the evals? I just spent 20 minutes googling and could not find them (thank god google will be irrelevant soon, just like RIM and Nokia!)

RIP Nokia, gone too soon. What's RIM?
