### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'content'

### ISSUE THREAD

**Issue by chaserLX** [langchain-ai/langchain#16354]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

ask_chain = generate_ask_chain()
  ner_chain = generate_ner_chain()
  reasonable_chain = generate_resonable_chain()

 overall_chain = generate_sequen_chain(ner_chain, reasonable_chain, ask_chain) # use SequentialChain

for chunk in overall_chain.stream({"profile": profile, "dialogue": dialogue,
                                     "pair": pair, "question": question, "answer": answer}, return_only_outputs=True):
            print(chunk.content, end="", flush=True)
            

### Description

我希望流式返回SequentialChain中处理后的输出的结果，但是dict好像不能被流式输出
AttributeError: 'dict' object has no attribute 'content'

### System Info

python3.11

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by HazSyl1** [comment]
Hey , can u share the entire code , or provide more contex.
