### ISSUE TITLE
How to use RetrievalQAWithSourcesChain with a custom prompt

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#16356]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```
        prompt_template = """Use the following pieces of context to answer the question at the end.  Try to answer in a structured way. Write your answer in HTML format but do not include ```html ```. Put words in bold that directly answer your question.
        If you don't know the answer, just say 'I am sorry I dont know the answer to this question or you dont have access to the files needed to answer the question.' Don't try to make up an answer.

        {summaries}

     
        Question: {question}.
        """

        PROMPT = PromptTemplate(
            template=prompt_template, input_variables=["summaries", "question"]
        )

      
        memory = ConversationBufferWindowMemory(
            k=5, memory_key="chat_history", return_messages=True, output_key="answer"
        )

        for i in range(0, int(len(chat_history) / 2)):
            memory.save_context(
                {"input": chat_history[i * 2]}, {"answer": chat_history[(i * 2) + 1]}
            )

        chain = RetrievalQAWithSourcesChain.from_chain_type(llm=llm,
                                                            chain_type="stuff",
                                                            retriever=retriever,
                                                            memory= memory,
                                                            chain_type_kwargs={
                                                                "prompt": PromptTemplate(
                                                                    template=PROMPT,
                                                                    input_variables=["summaries", "question"],
                                                                ),
                                                            },
                                                        )
        
```

### Description

I want to use RetrievalQAWithSourcesChain to generate an answer and the relevant sources from the retriever. However with this code I am getting this error:

. System.Private.CoreLib: Result: Failure
Exception: KeyError: 'template'

prompt.py", line 146, in template_is_valid
    values["template"], values["template_format"]

### System Info

langchain==0.1.0
langsmith==0.0.80
langchainhub==0.1.14
langchain-community==0.0.12
openai==1.7.2
azure-identity == 1.13.0
azure-core ==1.28.0

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by yen111445** [comment]
system_message_prompt = SystemMessagePromptTemplate.from_template(
    "prompt. The context is:\n{context}"
)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "{question}"
)

qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.7,
            max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.5, "k": 8},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        ),
        memory=ConversationBufferMemory(memory_key="chat_history", return_messages=True),
        combine_docs_chain_kwargs={
            "prompt": ChatPromptTemplate.from_messages([
                system_message_prompt,
                human_message_prompt,
            ]),
        },
    )

USE ConversationalRetrievalChain.
