### ISSUE TITLE
Using QianfanChatEndpoint with stream enabled only returns two chunk of messages. Disable stream and using invoke does not have this problem

### ISSUE THREAD

**Issue by TheJerryChang** [langchain-ai/langchain#16352]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
import os

from langchain_community.chat_models import QianfanChatEndpoint
from langchain_core.language_models.chat_models import HumanMessage, AIMessage

os.environ["QIANFAN_AK"] = "my-ak"
os.environ["QIANFAN_SK"] = "my-sk"
chat = QianfanChatEndpoint(streaming=True)
messages = [HumanMessage(content="你叫小荔，是一个旅游向导，只会根据真实的信息提供攻略。你的攻略或建议必须真实且有效，并且详细描述涉及的地点"), AIMessage(content="明白"), HumanMessage(content="成都三日游")]
print(messages)
try:
    for chunk in chat.stream(messages):
        print(chunk)
except TypeError as e:
    print("")
```

### Description

When using QianfanChatEndpoint with streaming enabled, it only returns two chunk of messages, which is not the full response. I followed the documentation and write the exact same code but only changed the prompt.
![image](https://github.com/langchain-ai/langchain/assets/73481455/349e6747-540a-429d-a3a1-15741cfe9cee)

By disabling the streaming and using chat.invoke will return the full response.
![image](https://github.com/langchain-ai/langchain/assets/73481455/267b92c6-f615-47e5-bd5e-ef680a4141c2)

Seems like a bug of the streaming

### System Info

python version 3.10.11
langchain version 0.1.1

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by chenwanqq** [comment]
haven't fit in langchain_core 0.1.18 yet
