### ISSUE TITLE
'Response is not a valid tool, try one of [Retriever].'), when using OpenAIFunctionsAgentOutputParser()

### ISSUE THREAD

**Issue by glejdis** [langchain-ai/langchain#16355]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

The following code: 
'''
from langchain.agents.output_parsers import OpenAIFunctionsAgentOutputParser
from langchain.agents.agent import AgentOutputParser
from langchain.agents.chat.output_parser import ChatOutputParser

def creat_ai_search_new_agent(embeddings, llm, class_name_rich):
    
    ai_search_endpoint = get_ai_search_endpoint()
    ai_search_admin_key = get_ai_search_admin_key()

    vector_store = AzureSearch(
            azure_search_endpoint=xxx,
            azure_search_key=xxx,
            index_name=xxx,
            embedding_function=embeddings.embed_query,
            content_key=xxx
        )
        
    """Retriever that uses `Azure Cognitive Search`."""
        
    azure_search_retriever = AzureSearchVectorStoreRetriever(
            vectorstore=vector_store,
            search_type="hybrid", 
            k=4,
            top=10
        )

    retriever_tool = create_retriever_tool(
        azure_search_retriever,
        "Retriever",
        "Useful when you need to retrieve information from documents",
    )

    class Response(BaseModel):
        """Final response to the question being asked"""

        answer: str = Field(description="The final answer to respond to the user")
        )

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are a helpful assistant who retrieves information from documents"),
            ("user", "{input}"),
            MessagesPlaceholder(variable_name="agent_scratchpad"),
        ]
    )

    llm_with_tools = llm.bind(
        functions=[
            # The retriever tool
            format_tool_to_openai_function(retriever_tool),
            # Response schema
            convert_pydantic_to_openai_function(Response),
        ]
    )

        
    try:

        agent = (
            {
                "input": lambda x: x["input"],
                # Format agent scratchpad from intermediate steps
                "agent_scratchpad": lambda x: format_to_openai_function_messages(
                    x["intermediate_steps"]
                ),
            }
            | prompt
            | llm_with_tools
            | OpenAIFunctionsAgentOutputParser()
        )

        agent_executor = AgentExecutor(tools=[retriever_tool], agent=agent, verbose=True, return_intermediate_steps=True,        
                                       handle_parsing_errors=True, 
                                       max_iterations=15,
                                       )

    except Exception as e:
        print(e)
        print("error instanciating the agent")
        
    return agent_executor

'''

It gives you the error: Response is not a valid tool, try one of [Retriever]. and then after going into a loop reaches the agent limit. The final steps of the agent look like this: 

Invoking: `Response` with `{'answer': "XXXXXXX", 'sources': [58, 15, 57, 29]}`

Response is not a valid tool, try one of [Retriever].

### Description

langchain == 0.1.1
openai==1.7.0

### System Info

Using model GPT-4 32K

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by ZuzooVn** [comment]
@glejdis have you found the solution?

**Comment by glejdis** [comment]
@ZuzooVn no solution yet :(
