### ISSUE TITLE
early_stopping_method parameter of AgentExecutor doesn’t work in expected way

### ISSUE THREAD

**Issue by Aaalexyyy** [langchain-ai/langchain#16374]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
tools = [get_news, solve_math_problem]

agent = ZeroShotAgent()
agent_executor = AgentExecutor.from_agent_and_tools(
            agent=agent,
            tools=tools,
            verbose=False,
            max_iterations=1
            early_stopping_method="generate",
            return_intermediate_steps=True,
            handle_parsing_errors=True,
)
result = agent_executor.invoke(
                input={
                    "input": user_query,
                },
)
```

### Description

We find that if the agent reaches the maximum steps, but it still wants to use tools to solve question, then the final answer will become the input for the next step, rather than a real final answer. This problem cannot be solved just by setting the right parameters.

**e.g.
Input:**
```News Tesla? and root of 18376?```

**Output:**
```
('Action: solve_math_problem\nAction Input: square root of 18376',
 [{'input': 'Tesla',
   'output': "Tesla CEO Elon Musk has expressed ...",
   'tool': 'get_news'}])
```

We set ```max_iteration=1``` just because of easily reproducing this error.

### System Info

We check the function for generating the final answer and printed out the input and output.

![image](https://github.com/langchain-ai/langchain/assets/144175514/e082e143-dbd7-488a-bb18-4d31443281ac)

**new_inputs:**
```python
{
'agent_scratchpad': 
'Thought: The question has two parts: one is about the latest news on Tesla, and the other is about the root of 18376. I can use the get_news tool to find the latest news about Tesla, and the solve_math_problem tool to find the square root of 18376.\n
Action: get_news \nAction Input: Tesla\n
Observation: {
  \'input\': \'Tesla\', 
  \'output\': "Tesla\'s CEO Elon Musk has sparked speculation about his ownership stake in the company after expressing 
  his reluctance to develop Tesla into a leader in artificial intelligence (AI) and robotics …", 
}\n
Thought:\n\nI now need to return a final answer based on the previous steps:', 
'stop': ['\nObservation:', '\n\tObservation:']
}
```
**full_output:**
```python
: Action: solve_math_problem Action Input: root of 18376
```

My guess is that in agent_scratchpad prompt has clear information that ` The question has two parts ... ` and doesn’t include the actual `user query News Tesla? and root of 18376?` Therefore, LLM may be confused about the meaning of final answer. Is final answer for initial user query or for previous steps?

Please review this issue. Thank you!

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by hwchase17** [comment]
I believe this is an issue with the prompt engineering done here.

When using `generate` for the early_stopping_method, it appends a string to the prompt that says "I now need to return a final answer based on the previous steps". The model is not abiding by this though

What model are you using? its possible that with worse models this doesnt work

A more explicit fix would be to modify the execution logic. There's a few ways to do this. One would be to subclass the Agent class and modify how this is handled. Another would be to submit a PR with this change. A final (our preferred) would be to replace the agent executor with LangGraph (https://github.com/langchain-ai/langgraph/blob/main/examples/agent_executor/base.ipynb). LangGraph was specifically designed to make it easy to modify the looping logic
