### ISSUE TITLE
DOC: Document how to pass callbacks with Runnable methods (e.g., .invoke / .batch)

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#16379]
### Issue with current documentation:

https://python.langchain.com/docs/modules/callbacks/#when-do-you-want-to-use-each-of-these

### Idea or request for content:

Document how to pass callbacks via .invoke

**Comment by TheJagStudio** [comment]
Hi, I'd like to take a stab at this.

Proposed approach:

I'd add a module-level docstring to [libs/core/langchain_core/callbacks/manager.py](https://github.com/TheJagStudio/langchain/blob/claude/gifted-shannon-gbzgl4/libs/core/langchain_core/callbacks/manager.py) covering the three injection patterns with minimal runnable examples:

Constructor-level — ChatOpenAI(callbacks=[MyHandler()]) — applies to all calls on the object.
Invocation-level — config=RunnableConfig(callbacks=[...]) on .invoke(), .stream(), .batch() — scoped to one call.
Context-level — CallbackManager.configure(inheritable_callbacks=[...]) inside custom Runnables, forwarding to child runs via run_manager.get_child().
Purely additive documentation, no behaviour changes, only langchain-core imports in the examples. Could a maintainer assign me?
