### ISSUE TITLE
langchain.llms SelfHostedPipeline and SelfHostedHuggingFaceLLM

### ISSUE THREAD

**Issue by IMJONEZZ** [langchain-ai/langchain#1639]
Hey guys,

I'm trying to use langchain because the Tool class is so handy and initialize_agent works well with it, but I am having trouble finding any documentation that allows me to run this self-hosted locally. Everything seems to be remote, but I have a system that I know is capable of what I'm trying to do.

Is there any way to specify arguments to either SelfHosted class or even runhouse in order to specify that you want it running on the computer you're currently working on, on the gpu connected to that computer, instead of ssh-ing into a remote instance?

Thanks

**Comment by tensiondriven** [comment]
Only thing I've seen so far is this:

```
llm = SelfHostedHuggingFaceLLM(model_id="gpt2", hardware=gpu, model_reqs=["pip:./", "transformers", "torch"])
```
Found [here](https://python.langchain.com/en/latest/modules/models/llms/integrations/self_hosted_examples.html)

It looks like `SelfHostedHuggingFaceLLM` is the class to check out.  If you pass it `hardware=gpu` then it will target your local machine.  No idea how to set up the various requirements to stand up the model though; if anyone knows, please comment.

**Comment by oapandit** [comment]
Hi,

Were you able to do it?
I also have similar requirement?

thanks,
Onkar

**Comment by oapandit** [comment]
> Only thing I've seen so far is this:
> 
> ```
> llm = SelfHostedHuggingFaceLLM(model_id="gpt2", hardware=gpu, model_reqs=["pip:./", "transformers", "torch"])
> ```
> 
> Found [here](https://python.langchain.com/en/latest/modules/models/llms/integrations/self_hosted_examples.html)
> 
> It looks like `SelfHostedHuggingFaceLLM` is the class to check out. If you pass it `hardware=gpu` then it will target your local machine. No idea how to set up the various requirements to stand up the model though; if anyone knows, please comment.

I tried to do this, but got the following error:

ValueError: Cluster must have an ip address (i.e. be up) or have a reup_cluster method (e.g. OnDemandCluster).
