### ISSUE TITLE
AttributeError: module 'langchain' has no attribute 'debug'

### ISSUE THREAD

**Issue by yichengchenAnt** [langchain-ai/langchain#16406]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
class CustomLLM(LLM):
    n: int

    @property
    def _llm_type(self) -> str:
        return "custom"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        if stop is not None:
            raise ValueError("stop kwargs are not permitted.")
        return prompt[: self.n]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {"n": self.n}
```

### Description

following the code here: https://python.langchain.com/docs/modules/model_io/llms/custom_llm
get the following error:
AttributeError: module 'langchain' has no attribute 'debug'

### System Info

langchain-0.0.147

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by eyurtsev** [comment]
@yichengchenAnt could you upgrade to a newer langchain version? Your'e on a version that's 200+ releases out of date

**Comment by yichengchenAnt** [comment]
actually I tried using langchain-0.1.2, the same error happened

**Comment by yichengchenAnt** [comment]
> @yichengchenAnt could you upgrade to a newer langchain version? Your'e on a version that's 200+ releases out of date

actually I tried using langchain-0.1.2, the same error happened

**Comment by yichengchenAnt** [comment]
> @yichengchenAnt could you upgrade to a newer langchain version? Your'e on a version that's 200+ releases out of date

which version do you recommend?
