### ISSUE TITLE
neo4j-advanced-rag multiple documents

### ISSUE THREAD

**Issue by priamai** [langchain-ai/langchain#16412]
### Feature request

I would like to learn how to modify the ingest.py to load multiple text file and include their source url.

### Motivation

Currently only one file is indexed.

### Your contribution

I know well Neo4J, LangChain but not LangServe. I can help once I get the concept.
@efriis and @tomasonjo original author

**Comment by tomasonjo** [comment]
ChatyGPT can help you there. You need to pass source name as parameter in the query and store it as a node property or a separate node

**Comment by priamai** [comment]
I understand I am doing an experiment now. Will let you know.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by priamai** [comment]
I also see a lot of deprecation warnings, we need to upgrade everything to the latest version of LangChain.
The enumeration ID for the parents is also problematic, as I add more documents into the folder, the integer will be randomized based on the OS, I should replace that with the filename.
Also  I don't know in the UI, how should we present the source information with the response?
How do we propagate the source info into the stringified response?
```
chain = (
    RunnableParallel(
        {
            "context": itemgetter("question") | retriever,
            "question": itemgetter("question"),
        }
    )
    | prompt
    | model
    | StrOutputParser()
)
```

I am going to create a separate repo so you can see my attempts.

**Comment by priamai** [comment]
What a bunch of garbage that was, welcome to the era of code assisted garbage!
