### ISSUE TITLE
Tracing in langsmith not working for LLMChan

### ISSUE THREAD

**Issue by aviramroi** [langchain-ai/langchain#16429]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

I set up a chain and parser like following:
```

class Ticket(BaseModel):
    reply: str 
    reply_explanation: str

ticket_parser = PydanticOutputParser(pydantic_object=Ticket)
partial_ticket_prompt = ticket_prompt.partial(
    reply_schema=ticket_parser.get_format_instructions(), example=example_data.json()
)

ticket_chain = LLMChain(llm=llm, prompt=partial_ticket_prompt)
```

and than I use it following way:
```
async def generate_ai_suggestions(ticket, similar_docs, macro=""):
    ticket = await ticket_chain.apredict(ticket=ticket, similar_docs=similar_docs, macro=macro,configparser={})
    return await ticket_parser.aparse(ticket)
```

### Description

my problem is that the tracing not working for me for this convention ( it works for some basic exmaples with "invoke" ) , I tried mulitple ways, including 
@traceable(run_type="chain")

is there any solution?

### System Info

langchain==0.0.350
langchain-community==0.0.3
langchain-core==0.1.1

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [X] Async

**Comment by aviramroi** [comment]
thanks, I tried all of those, but it still not working
it might be a bug with the predict ?

**Comment by a868111817** [comment]
> thanks, I tried all of those, but it still not working it might be a bug with the predict ?

I'm facing the same issue too. I suppose LangSmith can't trace the async chain?

**Comment by abdullahmujahidali** [comment]
I am also getting this error any fix?

`os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_API_KEY"] = LANGSMITH_API_KEY
os.environ["LANGCHAIN_PROJECT"] = LANGSMITH_PROJECT


llm = ChatOpenAI(
    model="gpt-3.5-turbo",
    )

llm.invoke("Hello, world!")
`

Error:
`
[<ipython-input-27-44ed1802e9bb>](https://localhost:8080/#) in <cell line: 0>()
     56     api_key=os.getenv("PINECONE_API_KEY")
     57 )
---> 58 llm.invoke("Hello, world!")
     59 
[/usr/local/lib/python3.11/dist-packages/langchain_core/callbacks/manager.py](https://localhost:8080/#) in _configure(callback_manager_cls, inheritable_callbacks, local_callbacks, verbose, inheritable_tags, local_tags, inheritable_metadata, local_metadata)
   2341             "tracing instead."
   2342         )
-> 2343         raise RuntimeError(msg)
   2344 
   2345     tracer_project = _get_tracer_project()

RuntimeError: Tracing using LangChainTracerV1 is no longer supported. Please set the LANGCHAIN_TRACING_V2 environment variable to enable tracing instead.`

**Comment by sergeyklay** [comment]
`LANGCHAIN_TRACING` is deprecated. If set to true while `LANGCHAIN_TRACING_V2` is also true, LangChain will throw an error. While v1 tracing still works in some limited cases, it's recommended to use `LANGCHAIN_TRACING_V2=true` to enable tracing with the v2 API. If both variables are set to false, tracing will be disabled.

**Comment by abdullahmujahidali** [comment]
> `LANGCHAIN_TRACING` is deprecated. If set to true while `LANGCHAIN_TRACING_V2` is also true, LangChain will throw an error. While v1 tracing still works in some limited cases, it's recommended to use `LANGCHAIN_TRACING_V2=true` to enable tracing with the v2 API. If both variables are set to false, tracing will be disabled.

I did that as well LANGCHAIN_TRACING_V2 = true and removed LANGCHAIN_TRACING and even made LANGCHAIN_TRACING = false but I was still getting the same error
