### ISSUE TITLE
BM25 langchain retriever should have similarity score

### ISSUE THREAD

**Issue by himsgpt** [langchain-ai/langchain#16445]
### Feature request

I am using BM25 retriever from langchain.
After building the retriever from documents, how do I get score for relevant document for a query?

Retriever = BM25Retriever.from_documents(...)
result = retriever.get_relevant_documents("foo")

### Motivation

The documentation is not good with details of parameters missing. 
Actual BM25 python package has all functional ities including tokenizer options.

### Your contribution

Could try

**Comment by himsgpt** [comment]
is there a documentation on BM25 with vector store?

**Comment by drdsgvo** [comment]
I would also like to have a score for an ensemle retriever (BM25 + vector store).
For me, without score the ensemble retriever often is USELESS, as there is no way to determine a confidence.

**Comment by himsgpt** [comment]
@drdsgvo you should use python base package - rank_bm25 or use llamaindex or haystack.

**Comment by drdsgvo** [comment]
> @drdsgvo my suggestion as of today would be, use python base package - rank_bm25 or use llamaindex or haystack.

Thank you. I think you are referring to https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever.html
That would work, but I would love to see that in Langchain, too, as the current Langchain approach (without scoring) does not make a lot of sense to me.
