### ISSUE TITLE
ConversationBufferMemory does not work

### ISSUE THREAD

**Issue by whk6688** [langchain-ai/langchain#16448]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
from langchain.chains import LLMChain

from langchain.memory import ConversationSummaryMemory
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
    SystemMessagePromptTemplate,
)


prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(
            "You are a nice chatbot having a conversation with a human."
        ),
        # The `variable_name` here is what must align with memory
        MessagesPlaceholder(variable_name="chat_history"),
        HumanMessagePromptTemplate.from_template("{question}"),
    ]
)

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

memory.chat_memory.add_user_message("hi, i am Kevin")
memory.chat_memory.add_ai_message("hi, i am nan")

memory.chat_memory.add_user_message("i am late for school")
memory.chat_memory.add_ai_message("oh, sound bad, i hope you can be happier")

memory.chat_memory.add_user_message("in fact, because of mom's mistake, she forgot something always")
memory.chat_memory.add_ai_message("i see, it does not matter, little thing")

memory.chat_memory.add_user_message("ok, let's chat something ")
memory.chat_memory.add_ai_message("sure, i like chat too")

conversation = LLMChain(llm=llm, prompt=prompt, verbose=True, memory=memory)
conversation({"question": "can you tell me why i was late for school"})
```

### Description

response is :Sure, I believe that you might have missed the time to leave or forgotten something important during the preparation process. 

i hope response is: because of mom's mistake, she forgot something always

--------------------------------------------------------------
i wonder where is wrong?

thanks

### System Info

langchain                     0.0.354
langchain-community           0.0.10
langchain-core                0.1.8
langdetect                    1.0.9
langsmith                     0.0.78

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by jatinchawda1503** [comment]
Hello @whk6688,

You need to tune your prompt to get the expected result. Here is the example

```
prompt = ChatPromptTemplate(
messages=[
SystemMessagePromptTemplate.from_template(
"You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and aswer according to it."
),
# The variable_name here is what must align with memory
MessagesPlaceholder(variable_name="chat_history"),
HumanMessagePromptTemplate.from_template("{question}"),
]
)

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
# memory.load_memory_variables({})
memory.chat_memory.add_user_message("hi, i am Kevin")
memory.chat_memory.add_ai_message("hi, i am nan")

memory.chat_memory.add_user_message("i am late for school")
memory.chat_memory.add_ai_message("oh, sound bad, i hope you can be happier")

memory.chat_memory.add_user_message("in fact, because of mom's mistake, she forgot something always")
memory.chat_memory.add_ai_message("i see, it does not matter, little thing")

memory.chat_memory.add_user_message("ok, let's chat something ")
memory.chat_memory.add_ai_message("sure, i like chat too")

conversation = LLMChain(llm=llms, prompt=prompt, verbose=True, memory=memory)
conversation({"question": "can you tell me why i was late for school"})
```

Output
```
Entering new LLMChain chain...
Prompt after formatting:
System: You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and aswer according to it.
Human: hi, i am Kevin
AI: hi, i am nan
Human: i am late for school
AI: oh, sound bad, i hope you can be happier
Human: in fact, because of mom's mistake, she forgot something always
AI: i see, it does not matter, little thing
Human: ok, let's chat something 
AI: sure, i like chat too
Human: can you tell me why i was late for school

> Finished chain.
{'question': 'can you tell me why i was late for school',
 'chat_history': [HumanMessage(content='hi, i am Kevin'),
  AIMessage(content='hi, i am nan'),
  HumanMessage(content='i am late for school'),
  AIMessage(content='oh, sound bad, i hope you can be happier'),
  HumanMessage(content="in fact, because of mom's mistake, she forgot something always"),
  AIMessage(content='i see, it does not matter, little thing'),
  HumanMessage(content="ok, let's chat something "),
  AIMessage(content='sure, i like chat too'),
  HumanMessage(content='can you tell me why i was late for school'),
  AIMessage(content='Based on the chat history, it seems that you were late for school because your mom made a mistake and forgot something.')],
 'text': 'Based on the chat history, it seems that you were late for school because your mom made a mistake and forgot something.'}
```

**Comment by whk6688** [comment]
thanks a lot

**Comment by whk6688** [comment]
sorry,  i wonder how to modify the code if i want to use ConversationSummaryMemory  .

thanks

**Comment by jatinchawda1503** [comment]
@whk6688, you can replace it with ConversationSummaryMemory with relevant params. You can refer this doc: https://api.python.langchain.com/en/latest/memory/langchain.memory.summary.ConversationSummaryMemory.html

**Comment by whk6688** [comment]
first, thanks.
then i modified the code as you said:
-----------------------------

prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(
            "You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and answer according to it."
        ),
        # The `variable_name` here is what must align with memory
        MessagesPlaceholder(variable_name="chat_history"),
        HumanMessagePromptTemplate.from_template("{question}"),
    ]
)

memory = ConversationSummaryMemory(llm=llm,memory_key="chat_history", return_messages=True)


memory.chat_memory.add_user_message("hi, i am Kevin")
memory.chat_memory.add_ai_message("hi, i am nan")

memory.chat_memory.add_user_message("i am late for school")
memory.chat_memory.add_ai_message("oh, sound bad, i hope you can be happier")

memory.chat_memory.add_user_message("in fact, because of mom's mistake, she forgot something always")
memory.chat_memory.add_ai_message("i see, it does not matter, little thing")

memory.chat_memory.add_user_message("ok, let's chat something ")
memory.chat_memory.add_ai_message("sure, i like chat too")

conversation = LLMChain(llm=llm, prompt=prompt, verbose=True, memory=memory)
conversation({"question": "can you tell me why i was late for school"})
-------------------------------------------------
AI answer:
I do not have access to your personal information or context, so I cannot determine exactly why you were late for school. It is possible that there may be several reasons for tardiness such as traffic, transportation delays, or simply forgetting the time. Could you please provide more details about your situation?
----------------------------------
I hope AI can answer the question correctly.

Thanks

**Comment by jatinchawda1503** [comment]
@whk6688,
In previous code provided was for ConversationBufferMemory, but when you replaced it with ConversationSummaryMemory. 
The memory message doesn't save the message, memory.chat_memory.add_user_message("hi, i am Kevin") when passed to llm there was no history the ideal way to do this is to use ```ChatMessageHistory``` which helps you to store all the conversation and can be accessed easily.


```
from langchain.prompts import (
ChatPromptTemplate,
HumanMessagePromptTemplate,
MessagesPlaceholder,
SystemMessagePromptTemplate,
)
from langchain.memory import ConversationSummaryMemory, ChatMessageHistory

prompt = ChatPromptTemplate(
messages=[
SystemMessagePromptTemplate.from_template(
"You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and aswer according to it."
),
# The variable_name here is what must align with memory
MessagesPlaceholder(variable_name="chat_history"),
HumanMessagePromptTemplate.from_template("{question}"),
]
)
history = ChatMessageHistory()

# memory.load_memory_variables({})
history.add_user_message("hi, i am Kevin")
history.add_ai_message("hi, i am nan")

history.add_user_message("i am late for school")
history.add_ai_message("oh, sound bad, i hope you can be happier")

history.add_user_message("in fact, because of mom's mistake, she forgot something always")
history.add_ai_message("i see, it does not matter, little thing")

history.add_user_message("ok, let's chat something ")
history.add_ai_message("sure, i like chat too")

memory = ConversationSummaryMemory.from_messages(memory_key="chat_history",chat_memory=history,llm=llms, return_messages=True)

conversation = LLMChain(llm=llms, prompt=prompt, verbose=True, memory=memory)
conversation({"question": "can you tell me why i was late for school"})
```

```

> Entering new LLMChain chain...
Prompt after formatting:
System: You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and aswer according to it.
System: Kevin introduces himself as Nan and mentions that he is late for school because his mom often forgets things. Nan expresses sympathy and reassures Kevin that it doesn't matter, as it's just a little thing. They both agree to chat about something.
Human: can you tell me why i was late for school

> Finished chain.

{'question': 'can you tell me why i was late for school',
 'chat_history': [SystemMessage(content="Kevin introduces himself as Nan and mentions that he is late for school because his mom often forgets things. Nan expresses sympathy and reassures Kevin that it doesn't matter, as it's just a little thing. They both agree to chat about something.")],
 'text': 'Yes, you mentioned earlier that you were late for school because your mom often forgets things.'}
```


I recommend you to go through the docs and examples, they are pretty straightforward.

**Comment by whk6688** [comment]
thanks again

**Comment by fahim9778** [comment]
@jatinchawda1503 
Hello, thanks for showing the full code. My code is a bit different but I am having too much of errors. Can you please show me how to fix this? My project is stuck because of these silly mistakes. I have all the packages imported.

```
system_prompt_template= """Imagine you are a friendly and highly knowledgeable teacher specializing in {prog_language_to_teach} programming. 

Your student is a {user_age}-year-old {user_edu_scope} student interested in {user_interest}. They look up to you for clear, easy-to-understand explanations.


These activities should build on previous chat context, reinforcing learning and keeping the conversation interactive and engaging.
"""
human_query = input()

chat_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt_template),
        ("human", human_query),
    ]
)
 
messages = chat_prompt.format_messages(
    user_age = user_age,
    user_edu_scope = user_edu_scope,
    user_interest = user_interest,
    prog_language_to_teach = prog_language_to_teach,
    human_query=human_query
)

from langchain.chains.conversation.memory import ConversationSummaryMemory

memory = ConversationSummaryMemory(return_messages=True, llm=llm)

conversation_sum = ConversationChain(memory=memory, prompt=chat_prompt, llm=llm, verbose=True)
print(memory.load_memory_variables({}))
```
And then I am having errors which I can't fix:

> memory = ConversationSummaryMemory(return_messages=True, llm=llm)
----> 5 conversation_sum = ConversationChain(memory=memory, prompt=chat_prompt, llm=llm, verbose=True)
ValidationError: 1 validation error for ConversationChain
__root__
  **Got unexpected prompt input variables. The prompt expects ['prog_language_to_teach', 'user_age', 'user_edu_scope', 'user_interest'], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error)**

Can you please help me with this? It would be so much help!

**Comment by jatinchawda1503** [comment]
@fahim9778 
The issue is the mismapping of prompt variables, you can refer to [ChatPromptTemplate ](https://api.python.langchain.com/en/latest/prompts/langchain_core.prompts.chat.ChatPromptTemplate.html#langchain_core.prompts.chat.ChatPromptTemplate) docs, you can assign input_variables to get a better understanding of the template construction and pass the variables when use llm.invoke function.

**Comment by fahim9778** [comment]
> @fahim9778 The issue is the mismapping of prompt variables, you can refer to [ChatPromptTemplate ](https://api.python.langchain.com/en/latest/prompts/langchain_core.prompts.chat.ChatPromptTemplate.html#langchain_core.prompts.chat.ChatPromptTemplate) docs, you can assign input_variables to get a better understanding of the template construction and pass the variables when use llm.invoke function.

I ran these scope of code
```python
chat_prompt = ChatPromptTemplate(
    messages=[
        ("system", system_prompt_template),
        ("human", "{human_query}"),
    ]
)


prompt_value = chat_prompt.invoke(
    {
        "user_age" : user_age,
        "user_edu_scope" : user_edu_scope,
        "user_interest" : user_interest,
        "prog_language_to_teach" : prog_language_to_teach,
        "human_query" : human_query
    }
)
from langchain.chains.conversation.memory import ConversationSummaryMemory

memory = ConversationSummaryMemory(return_messages=True, llm=llm)

talk = LLMChain(memory=memory, prompt=chat_prompt, llm=llm, verbose=True)
print(memory.load_memory_variables({}))

response = talk({"human_query": input()})
print(response['text'])
```
An then getting the following errors:

> **ValueError: Missing some input keys: {'user_age', 'prog_language_to_teach', 'user_edu_scope', 'user_interest'}**

**Comment by jatinchawda1503** [comment]
@fahim9778, The issue is you are initiating LLMChain and passing only human_query you have to pass all the variables. I would recommend going through the docs of the function that you are using.
