### ISSUE TITLE
ValidationError field required (type=value_error.missing) while using react agent

### ISSUE THREAD

**Issue by DanielProkhorov** [langchain-ai/langchain#16456]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

I my ReAct agent, I'm trying to call a tool, that is defined as the following:

```python
@tool(args_schema=SliderInput)
def slider(object_name, value) -> str:
    return "Ok"
```

and the corresponding pydantic model:

```python
class SliderInput(BaseModel):
    object_name: str = Field(..., description="The name of the slider object")
    value: int = Field(..., description="The value of the slider object to set")
```

I get the following error when the tool is being called:

```python
object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for SliderInput
value
  field required (type=value_error.missing)
```

I started with this function definition:

```python
@tool
def slider(object_name: str, value: int) -> str:
    return "Ok"
```

and received the same error.

Additionally, I've also tried this one:

```python
@tool(args_schema=SliderInput)
def slider(object_name: str, value: int) -> str:
    return "Ok"
```

without success.

Why is my code failing.

### Description

I'm trying to use langchain library **Version: 0.1.1**

### System Info

langchain==0.1.1
langchain-cli==0.0.20
langchain-community==0.0.13
langchain-core==0.1.12
langchain-experimental==0.0.49
langchain-openai==0.0.2.post1
langchainhub==0.1.14

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by ccurme** [comment]
The agent type you're using doesn't currently support multi-input tools. See more alternatives here: https://python.langchain.com/docs/modules/agents/agent_types/

**Comment by DanielProkhorov** [comment]
@ccurme Thanks for clarification, I somehow missed this within the docs...
