### ISSUE TITLE
create_extraction_chain无法作为SequentialChain中的子链

### ISSUE THREAD

**Issue by chaserLX** [langchain-ai/langchain#16504]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

def generate_extract_chain(profile):
    template_ner_extract = """
   
    schema中的"职业"可能对应多个实体，都应全部提取，表述不清晰的应该要概括准确，比如“送外卖”是“外卖员”。
    schema中的“同行人”可以有多个，应该尽量把对应的姓名和与当事人的关系实体提取出来

    返回结果以json格式返回，包括：
    
    ner_result：
        updated_labels: 返回画像标签集所有有更新变动的key-value，如果没有更新则值为空
        profile: 更新后的{profile}，如果没有更新则值为空

    """

    ner_prompt = ChatPromptTemplate.from_template(template_ner_extract)

    # Schema
    schema = {
        "properties": {
            "姓名": {"type": "string"},
            "年龄": {"type": "integer"},
            "职业": {"type": "string"},
            "同行人": {"type": "string"},
            "常住地址": {"type": "string"},
            "工作地址": {"type": "string"},
        },
        "required": ["姓名", "年龄"],
    }

    # Run chain
    llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")
    chain = create_extraction_chain(schema, llm, ner_prompt, output_key='ner_result')
    return chain

def generate_sequen_chain(ner_chain, reasonable_chain, ask_chain):

    overall_chain = SequentialChain(
    chains=[ner_chain, reasonable_chain, ask_chain],
    input_variables=["profile", "dialogue", "pair", "question", "answer"],
    # Here we return multiple variables
    output_variables=["ask_result", "ner_result", "resonable_result"],
    # output_variables=["new_result"],
    verbose=True)

    return overall_chain

ask_chain = generate_ask_chain()
ner_chain = generate_ner_chain()
reasonable_chain = generate_resonable_chain()
overall_chain = SequentialChain(
    chains=[ner_chain, reasonable_chain, ask_chain]

### Description

TypeError: create_extraction_chain() got an unexpected keyword argument 'output_key'
请问如何将create_extraction_chain作为SequentialChain中的子链来运行。

### System Info

python3.11

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by chaserLX** [comment]
> _🤖_
> 
> 你好，@chaserLX！很高兴再次看到你的问题。希望你一切都好！
> 
> 根据您提供的代码和错误信息，问题出在`create_extraction_chain`函数不接受`output_key`参数，所以您在调用它时出现了`TypeError`。
> 
> 如果您想在`SequentialChain`中作为子链使用`create_extraction_chain`，您需要确保不向它传递`output_key`参数。
> 
> 以下是一个如何使用`create_extraction_chain`作为子链的示例：
> 
> ```python
> from langchain.chains import SequentialChain
> from langchain.chains.openai_functions.extraction import create_extraction_chain
> from langchain_core.language_models import BaseLanguageModel
> 
> # 假设您有一个语言模型和模式
> llm = BaseLanguageModel(...)
> schema = {...}
> 
> extraction_chain = create_extraction_chain(schema=schema, llm=llm)
> 
> # 现在您可以在SequentialChain中作为子链使用extraction_chain
> seq_chain = SequentialChain(chains=[extraction_chain])
> ```
> 
> 在这个例子中，`extraction_chain`是使用`create_extraction_chain`创建的，然后在`SequentialChain`中作为子链使用。注意，没有向`create_extraction_chain`传递`output_key`参数。
> 
> 关于`create_extraction_chain`函数的具体签名和参数，根据我在LangChain代码库中的查找，`create_extraction_chain_pydantic`函数有以下签名和参数：
> 
> ```python
> def create_extraction_chain_pydantic(
>     pydantic_schema: Any,
>     llm: BaseLanguageModel,
>     prompt: Optional[BasePromptTemplate] = None,
>     verbose: bool = False,
> ) -> Chain:
> ```
> 
> 参数：
> 
> * `pydantic_schema`：要提取的实体的pydantic模式。它可以是任何继承自`pydantic.BaseModel`的类。
> * `llm`：`BaseLanguageModel`的实例，即用于提取的语言模型。
> * `prompt`：用于提取的`BasePromptTemplate`的可选实例。如果未提供，将使用基于`_EXTRACTION_TEMPLATE`的默认提示。
> * `verbose`：一个布尔值，表示是否以详细模式运行，该模式将中间日志打印到控制台。默认为全局`verbose`值，可以通过`langchain.globals.get_verbose()`访问。
> 
> 该函数返回一个`Chain`对象，可以使用提供的pydantic模式从段落中提取信息。
> 
> 参考源码：
> 
> * [libs/langchain/langchain/chains/openai_functions/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_functions/base.py)
> * [libs/langchain/langchain/chains/openai_tools/extraction.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_tools/extraction.py)
> * [libs/langchain/langchain/chains/openai_functions/extraction.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_functions/extraction.py)
> 
> ## Sources
> * [libs/langchain/langchain/chains/openai_functions/extraction.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_functions/extraction.py)
> * [libs/langchain/langchain/chains/openai_functions/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_functions/base.py)
> * [libs/langchain/langchain/chains/openai_tools/extraction.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/openai_tools/extraction.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

那如果seq_chain = SequentialChain(chains=[extraction_chain])中除了extraction_chain之外，我还同时有其他的chains，其他的chain需要有output_key，应该怎么做

**Comment by chaserLX** [comment]
> _🤖_
> 
> 您好，@chaserLX！
> 
> 如果您在`SequentialChain`中有其他链，并且这些链需要`output_key`，您应确保这些`output_key`是唯一的，不会与`SequentialChain`中其他链的`output_key`重叠。
> 
> 这是因为在`SequentialChain`类中，每个链的`output_key`都会被验证并添加到`known_variables`集合中。如果一个链的`output_key`已经存在于`known_variables`中，就会引发`ValueError`。这意味着`SequentialChain`中的每个链必须有唯一的`output_key`。
> 
> 以下是验证`output_key`的相关代码片段：
> 
> ```python
> for chain in chains:
>     ...
>     overlapping_keys = known_variables.intersection(chain.output_keys)
>     if overlapping_keys:
>         raise ValueError(
>             f"Chain returned keys that already exist: {overlapping_keys}"
>         )
>     known_variables |= set(chain.output_keys)
> ```
> 
> 因此，您需要确保每个链的`output_key`都是唯一的。例如，如果您有一个名为`extraction_chain`的链和一个名为`other_chain`的链，您可以这样做：
> 
> ```python
> extraction_chain = create_extraction_chain(schema=schema, llm=llm, output_key='extraction_output')
> other_chain = create_other_chain(..., output_key='other_output')
> 
> seq_chain = SequentialChain(chains=[extraction_chain, other_chain])
> ```
> 
> 在这个例子中，`extraction_chain`和`other_chain`都有唯一的`output_key`，因此它们可以在`SequentialChain`中一起使用。
> 
> 参考源码：
> 
> * [libs/langchain/langchain/chains/sequential.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/sequential.py)
> 
> 这个回答旨在为您提供有用的信息并节省您的时间。它**并非精确的解决方案**，而是您自己研究的起点。
> 
> 帮助我变得更有用！如果这个回答对您有帮助，请给我一个👍。如果这个回答与您的问题无关，请给我一个👎。
> 
> 如果您想继续对话，请在回复的开头@dosu-bot。
> 
> ## Sources
> * [libs/langchain/langchain/chains/sequential.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/sequential.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

但是据你所说，“SequentialChain中作为子链使用create_extraction_chain，您需要确保不向它传递output_key参数”，那如何完成以下功能：seq_chain = SequentialChain(chains=[extraction_chain])中除了extraction_chain之外，我还同时有其他的chains，其他的chain需要有output_key，应该怎么做

**Comment by eyurtsev** [comment]
Extraction use case documentation: https://python.langchain.com/docs/use_cases/extraction
