### ISSUE TITLE
ChatVertexAI model - convert_system_message_to_human argument = True is ignored

### ISSUE THREAD

**Issue by peerdavid** [langchain-ai/langchain#16503]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
from langchain_google_vertexai import ChatVertexAI
from langchain_core.prompts import ChatPromptTemplate


llm = ChatVertexAI(
    model_name="gemini-pro",
    project="my_project",
    convert_system_message_to_human=True,
)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            (
                "You are a system that translates each input from english to german."
            ),
        ),
        ("user", "{question}"),
    ]
)

chain = prompt | llm
answer = chain.invoke({"question": "Hello, how are you?"})
print(answer)
```

This code raises the exception
```
...
env/lib/python3.11/site-packages/langchain_google_vertexai/chat_models.py", line 167, in _parse_chat_history_gemini
    raise ValueError(
ValueError: SystemMessages are not yet supported!
                
To automatically convert the leading SystemMessage to a HumanMessage,
set  `convert_system_message_to_human` to True. Example:

llm = ChatVertexAI(model_name="gemini-pro", convert_system_message_to_human=True)
```

### Description

The problem is, that the check in langchain_google_vertexai/chat_models.py line 165 always evaluates to True, independent on whether convert_system_message_to_human is True or False:
```python
[...]
for i, message in enumerate(history):
        if (
            i == 0
            and isinstance(message, SystemMessage)
            and not convert_system_message_to_human,
        ):
```
As can be seen, the ',' after `and not convert_system_message_to_human` must be removed, otherwise its interpreted as a tuple and evaluates to `True` always, independent on whether `convert_system_message_to_human` is True or False.

### System Info

langchain==0.1.3
langchain-community==0.0.15
langchain-core==0.1.15
langchain-google-vertexai==0.0.2
langchain-openai==0.0.3

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by peerdavid** [comment]
One more thing to mention: The reason why I'm not contributing a fix and PR right now is, that I'm really not sure whats the impact when I change this and on whether "non-chat" models must also be fixed etc. Still, I'm happy to provide a fix and PR if desired :)

**Comment by kulaone** [comment]
I tested your code and it appears to be working now.
