### ISSUE TITLE
LangSmith: Warning message does not disappear when unsetting LANGCHAIN_TRACING_V2

### ISSUE THREAD

**Issue by Hadi2525** [langchain-ai/langchain#16537]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
import os
os.unsetenv("LANGCHAIN_TRACING_V2")
os.unsetenv("LANGCHAIN_ENDPOINT")
os.unsetenv("LANGCHAIN_API_KEY")
os.unsetenv("LANGCHAIN_PROJECT")

### Error Message and Stack Trace (if applicable)

logger.warning(
Message: 'Unable to load requested LangChainTracer. To disable this warning, unset the LANGCHAIN_TRACING_V2 environment variables.'
Arguments: (LangSmithUserError('API key must be provided when using hosted LangSmith 
API'),)

### Description

I have already unset the `LANGCHAIN_TRACING_V2` variable. Bus I still get the warning message and it becomes hard for me to trace the error for other messages.

### System Info

langchain==0.1.3
langchain-community==0.0.15
langchain-core==0.1.15 
langchain-openai==0.0.3

**Comment by eyurtsev** [comment]
@Hadi2525 I am unable to reproduce. 

Could you expand the code snippet to include the imports you're using?

**Comment by Hadi2525** [comment]
Hi @eyurtsev ,

`from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import AzureChatOpenAI
from langchain_community.llms import LlamaCpp
from langchain.chains.llm import LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks import StreamingStdOutCallbackHandler
import streamlit as st

from dotenv import load_dotenv, find_dotenv
from langchain.chains import RetrievalQA`


These are the libraries I used.

**Comment by hinthornw** [comment]
Hi @Hadi2525 - this is because `os.unsetenv` doesn't actually delete it from the current process's environment. It applies to spawned subprocesses. 


From the [python docs](https://docs.python.org/3/library/os.html#os.unsetenv):

```
os.unsetenv(key, /)
Unset (delete) the environment variable named key. Such changes to the environment affect subprocesses started with [os.system()](https://docs.python.org/3/library/os.html#os.system), [popen()](https://docs.python.org/3/library/os.html#os.popen) or [fork()](https://docs.python.org/3/library/os.html#os.fork) and [execv()](https://docs.python.org/3/library/os.html#os.execv).

Deletion of items in [os.environ](https://docs.python.org/3/library/os.html#os.environ) is automatically translated into a corresponding call to [unsetenv()](https://docs.python.org/3/library/os.html#os.unsetenv); however, calls to [unsetenv()](https://docs.python.org/3/library/os.html#os.unsetenv) don’t update [os.environ](https://docs.python.org/3/library/os.html#os.environ), so it is actually preferable to delete items of [os.environ](https://docs.python.org/3/library/os.html#os.environ).

Raises an [auditing event](https://docs.python.org/3/library/sys.html#auditing) os.unsetenv with argument key.
```


Any of the following options should work for you:


```
if "LANGCHAIN_TRACING_V2" in os.environ:
    del os.enviorn["LANGCHAIN_TRACING_V2"]
```
```
os.environ.pop("LANGCHAIN_TRACING_V2", None)
```

```
os.environ["LANGCHAIN_TRACING_V2"] = "false"
```

etc.

**Comment by Hadi2525** [comment]
Thank you. I pretty much done these remedies already. But apparently the env variable was cleared (after a restart or cleared from memory). I'll close the issue and if it comes up again, I will reopen it.
