### ISSUE TITLE
AttributeError: 'VectorStoreIndexWrapper' object has no attribute 'similarity_search'

### ISSUE THREAD

**Issue by saxenarajat** [langchain-ai/langchain#1655]
I am trying to follow the example from this [URL](https://langchain.readthedocs.io/en/latest/modules/indexes/chain_examples/question_answering.html), but I am getting the above error. What might be wrong?

## Environment
OS: Windows 11
Python: 3.9

**Comment by Timber182** [comment]
I also face this issue. Have you found a solution?

**Comment by jeddieLee** [comment]
docsearch.query(query) ,
docsearch.query_with_sources(query) 
are available. 
"chain.run()" is executed within the query function.

**Comment by emanrow** [comment]
I am also running into this issue. `query` and `query_with_sources` don't seem to actually answer questions based on multiple sources passed to `VectorstoreIndexCreator.from_loaders([loader1, loader2, loader3...])`. Or at least, I ahve only been able to get answers sourced to the last loader passed to `from_loaders()`. The article @saxenarajat linked is for answering questions over multiple documents, so I don't think `docsearch.query` and `query_with_sources` will suffice for this.

**Comment by dawu76** [comment]
I noticed the `docsearch` object has a `vectorstore` attribute, so  I was able to get past the _"AttributeError: 'VectorStoreIndexWrapper' object has no attribute 'similarity_search'"_ error by substituting 

```
docsearch.similarity_search(query)
```

with

```
docsearch.vectorstore.similarity_search(query)
```

The docs returned appeared to be pulled from the multiple sources I passed in.
