### ISSUE TITLE
Proposal: Make OpenAI api key configurable at runtime

### ISSUE THREAD

**Issue by cvansteenburg** [langchain-ai/langchain#16567]
## Feature request
I'd like the option to pass the OpenAI api key to the `openai.Openai` client at runtime. 

- ConfigurableField ([docs](https://python.langchain.com/docs/expression_language/how_to/configure)) already supports passing this variable to the client, and in fact allows me to change any config except `openai_api_key`.
- I suspect the original intent may have been to make it configurable: if `openai_api_key` is defined with a `configurable_field` there is no warning or Exception raised.

I can submit a PR; I'm already using the proposed change in my code.

## Motivation
There are many scenarios where I'd like to change the API key depending on the task I'm performing. This is especially true when using Langchain in the context of a microservice or API with a high volume of requests: building "cloned" modules or re-initializing modules is impractical.

## Your contribution
I can submit a PR in short order but am soliciting input here first.

The proposed change is to the validation function found here [(source)](https://github.com/langchain-ai/langchain/blob/2b2285dac0d6ae0f6b7c09c33882a0d5be26c078/libs/partners/openai/langchain_openai/chat_models/base.py#L344):
*Proposed change at the bottom*
```python
    @root_validator()
    def validate_environment(cls, values: Dict) -> Dict:
        """Validate that api key and python package exists in environment."""
        if values["n"] < 1:
            raise ValueError("n must be at least 1.")
        if values["n"] > 1 and values["streaming"]:
            raise ValueError("n must be 1 when streaming.")

        values["openai_api_key"] = get_from_dict_or_env(
            values, "openai_api_key", "OPENAI_API_KEY"
        )
        # Check OPENAI_ORGANIZATION for backwards compatibility.
        values["openai_organization"] = (
            values["openai_organization"]
            or os.getenv("OPENAI_ORG_ID")
            or os.getenv("OPENAI_ORGANIZATION")
        )
        values["openai_api_base"] = values["openai_api_base"] or os.getenv(
            "OPENAI_API_BASE"
        )
        values["openai_proxy"] = get_from_dict_or_env(
            values,
            "openai_proxy",
            "OPENAI_PROXY",
            default="",
        )

        client_params = {
            "api_key": values["openai_api_key"],
            "organization": values["openai_organization"],
            "base_url": values["openai_api_base"],
            "timeout": values["request_timeout"],
            "max_retries": values["max_retries"],
            "default_headers": values["default_headers"],
            "default_query": values["default_query"],
            "http_client": values["http_client"],
        }

        ##### PROPOSAL: REMOVE MARKED IF STATEMENTS FROM THIS CODE #####
        if not values.get("client"): # <--- REMOVE
            values["client"] = openai.OpenAI(**client_params).chat.completions
        if not values.get("async_client"): # <--- REMOVE
            values["async_client"] = openai.AsyncOpenAI(
                **client_params
            ).chat.completions
        ##### END PROPOSAL #####
```

This would require no change in user behavior (putting OPENAI_API_KEY in the environment variables still works).

I'm not sure why these IF checks are here. If they're necessary to avoid re-defining `openai.OpenAI`, I'd suggest the benefit of a dynamic api key outweighs the cost of re-instantiation (and could be solved regardless by a quick check on whether the client_params changed).

Thanks for any input!

**Comment by cvansteenburg** [comment]
Looks like while I was writing this, the `feature` issue category was removed, leading to a blank submission when I finally hit send. I can't delete it, so I just edited the body. Happy to re-open elsewhere if needed. Thanks!

**Comment by eyurtsev** [comment]
@cvansteenburg what's the bottleneck with re-initializing the model?

**Comment by maspotts** [comment]
@cvansteenburg I hit this issue as well: did you end up submitting a PR?  I couldn't see it...

**Comment by cvansteenburg** [comment]
@maspotts I got slammed at work and had to go dark for a bit. Will return shortly with a more thoughtful response :).

**Comment by maspotts** [comment]
Thanks would be great: I'm currently reaching in and modifying chain.llm_chain.llm.openai_api_key, or index/embedding_function.openai_api_key, or whatever, just before I call a method that uses it, but that seems needlessly error-prone and not at all future proof!

**Comment by rarchitgupta** [comment]
@cvansteenburg @maspotts did you have any luck submitting a PR? If not, can you show me the code modification that needs to be done to get this to work? Currently stuck here

**Comment by maspotts** [comment]
In the end, I just modified my code so I create a list of OpenAI or ChatOpenAI instances at the beginning and then cycle through them at the point of use.

**Comment by rarchitgupta** [comment]
What if you want to pass in the API key from the client

**Comment by maspotts** [comment]
I think the easiest is to create a new OpenAI or ChatOpenAI instance using the specific API key when you receive it.

**Comment by cvansteenburg** [comment]
🪄✨**POOF**✨ I have reappeared!

It's been awhile since I worked this issue but I recall the pain-point being that there isn't a simple or performant way to achieve the desired API key change. Re-initializing the model wasn't performant (to very belatedly answer your question @eyurtsev), and I found the other solutions here, while valid, to be neither performant or simple. This may reflect my own inexperience.

As stated in the original proposal, the source code suggests the original intent may have been to make `openapi_api_key` configurable: if `openai_api_key` is defined with a `configurable_field` there is no warning or Exception raised. 

My proposed PR fixed the issue for me (at the time, anyway - I haven't checked for recent changes to source) by removing the `IF` checks that prevent re-defining `openai.OpenAI` and thus allowing the class to dynamically use `openai_api_key` when passed via `configurable_field`.

There may be an important reason the original author decided to prevent redefinition of the `openai.OpenAI` class. (safety related? Perhaps redefinition creates problems?) Git blame shows @efriis, a more experienced dev and certainly more familiar with the code base, so I propose a change only with trepidation ;).

**Comment by fhkingma** [comment]
@cvansteenburg another approach, which does not require changing the underlying class:

``` python
class CustomChatOpenAI(ChatOpenAI):
    @root_validator(pre=True)
    def validate_environment(cls, values: Dict) -> Dict:
        values["async_client"] = values["client"] = None
        return values
```

**Comment by MahmutAtia** [comment]
did they fix this ?
this code is from their server examples but still not working
https://github.com/langchain-ai/langserve/blob/main/examples/configurable_chain/server.py

dynamic_auth_model = ChatOpenAI(openai_api_key="placeholder").configurable_fields(
openai_api_key=ConfigurableField(
id="openai_api_key",
name="OpenAI API Key",
description=("API Key for OpenAI interactions"),
),
)

**Comment by FlorianOttenwaelder** [comment]
Has anyone tried this with the new Langchain V3 version? I'd love to know if there have been any changes to how API key configuration works with the update. Thanks in advance for sharing any experiences or insights!
