### ISSUE TITLE
DOC: Error in semantic similarity example selector documentation

### ISSUE THREAD

**Issue by SophieDC98** [langchain-ai/langchain#16570]
### Issue with current documentation:

I'm trying out this tutorial: https://python.langchain.com/docs/modules/model_io/prompts/example_selector_types/similarity

But I'm getting this error related to the Chroma vector store:
`vectorstore
  instance of VectorStore expected (type=type_error.arbitrary_type; expected_arbitrary_type=VectorStore)`

What is the correct way to do this?
I already tried:
- changing the import to `from langchain_community.vectorstores.chroma import Chroma`
- changing the import to `from langchain_community.vectorstores import chroma`
- trying out different versions of lanchain-community (0.0.15, 0.0.14, 0.0.13)

### Idea or request for content:

Please describe the correct way to set up the semantic similarity example selector and the cause of my bug

**Comment by SophieDC98** [comment]
@dosu-bot I specifically want to use Chroma as vectorstore. I currently changed the code to `from langchain_community.vectorstores import chroma`, but now I get an error: 'AttributeError: module 'langchain_community.vectorstores.chroma' has no attribute 'from_texts'

**Comment by SophieDC98** [comment]
fixed by using `from langchain.vectorstores import Chroma`

**Comment by Shoupadhyay** [comment]
i am also getting the error even daww i used the above mentioned library
