### ISSUE TITLE
ChromaDB: Cannot delete document from ParentDocumentRetriever 

### ISSUE THREAD

**Issue by XariZaru** [langchain-ai/langchain#16604]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain.docstore.document import Document

to_add =  Document(page_content="text", metadata={"document_name": "test.pdf"})
ids = to_add.metadata["document_name"]

print("BEFORE INSERT", retriever.vectorstore._collection.count())
retriever.add_documents([to_add], ids=[ids])
print("AFTER INSERT", retriever.vectorstore._collection.count())
retriever.vectorstore._collection.delete(ids=[ids])
retriever.docstore.mdelete(ids=[ids])
print(retriever.vectorstore._collection.count())
print("AFTER DELETE", retriever.vectorstore._collection.count())
```python

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 22
     20 print("AFTER INSERT", retriever.vectorstore._collection.count())
     21 retriever.vectorstore._collection.delete(ids=[ids])
---> 22 retriever.docstore.delete(ids=[ids])
     23 print(retriever.vectorstore._collection.count())
     24 print("AFTER DELETE", retriever.vectorstore._collection.count())
AttributeError: 'EncoderBackedStore' object has no attribute 'delete'

### Description

I added a document, checked the vectorstore size, deleted it, and nothing seems to be deleted.

### System Info

Chroma 0.4.22
Langchain 0.1.0
Lark 1.1.8
Python 3.11
Windows 10

**Comment by XariZaru** [comment]
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 22
     20 print("AFTER INSERT", retriever.vectorstore._collection.count())
     21 retriever.vectorstore._collection.delete(ids=[ids])
---> 22 retriever.docstore.mdelete(ids=[ids])
     23 print(retriever.vectorstore._collection.count())
     24 print("AFTER DELETE", retriever.vectorstore._collection.count())
TypeError: EncoderBackedStore.mdelete() got an unexpected keyword argument 'ids'
```

This is the following issue once I changed th command to mdelete from delete. Can I get someone else to look into this?

**Comment by baskaryan** [comment]
Hey @XariZaru, `DocStore.mdelete` doesn't take named param `ids=`. can you try
```python
retriever.docstore.mdelete([ids])
```

**Comment by XariZaru** [comment]
> Hey @XariZaru, `DocStore.mdelete` doesn't take named param `ids=`. can you try
> 
> ```python
> retriever.docstore.mdelete([ids])
> ```

Hi, no documents are being deleted. But there is no error at least. 


Also, after testing some more I found some additional issues concerning the ParentDocumentRetriever. My understanding of the ParentDocumentRetriever is that we take a document and split it down into X Children documents. These documents are the ones that get embedded.

The issue is that the ID I provide is not passed onto the children. Furthermore, in ChromaDB, it looks like only ONE document can have a unique ID at a time. What does this mean for our children documents? What IDs will they get? And how will I delete them in the future?

```python
retriever.add_documents([to_add], ids=["test.pdf"])
print(retriever.vectorstore._collection.get(ids=["test.pdf"]))

{'ids': [], 'embeddings': None, 'metadatas': [], 'documents': [], 'uris': None, 'data': None}
```

As you can see, the result of the ParentDocumentRetriever.add_documents does not associate an ID with my generated documents.

**Comment by baskaryan** [comment]
The documents aren't being deleted from the DocStore or the VectorStore, or both?

You're right that currently there's no way to delete child documents from the VectorStore. The id's you specify are used for the parent documents which are stored in the DocStore. The child documents are uploaded to the VectorStore without ids (we let the VectorStore integration handle id generation).

We could update `ParentDocumentRetriever.add_documents` to return the ids of the child documents in the vector store? I'm not sure if there's a good way to assign the ids for the child documents up front, since we don't know how many child documents there will be until after we've split the parent documents.

**Comment by XariZaru** [comment]
> The documents aren't being deleted from the DocStore or the VectorStore, or both?
> 
> You're right that currently there's no way to delete child documents from the VectorStore. The id's you specify are used for the parent documents which are stored in the DocStore. The child documents are uploaded to the VectorStore without ids (we let the VectorStore integration handle id generation).
> 
> We could update `ParentDocumentRetriever.add_documents` to return the ids of the child documents in the vector store? I'm not sure if there's a good way to assign the ids for the child documents up front, since we don't know how many child documents there will be until after we've split the parent documents.

Thank you so much for clearing this up. I needed a sanity check to make sure I was understood what was going on. To answer your first question, yes the documents are not being deleted from the vector store. But that was before I understood what was going on.

What would your recommendation be then if I wanted to also remove the children documents? My current issue is that I want to replace a document with a new version. This entails removing the previous parent and children documents.

**Comment by XariZaru** [comment]
@baskaryan 

I swapped over to Pinecone instead of Chroma.
Wanted to follow up on this. If I was able to handle deleting from the Vectorstore (querying by filter) and deleting it manually on my own, then would I only need to search the docstore for the corresponding document and delete it? That would take care of the issues, right?

**Comment by markoarnauto** [comment]
🆙  Adding a `ParentDocumentRetriever.delete` would be useful to make it compatible with langchain indexing also.
