### ISSUE TITLE
How to escape curly-braces "{}"  in a customized prompt?

### ISSUE THREAD

**Issue by tamil-acog** [langchain-ai/langchain#1660]
Hi. I am trying to generate a customized prompt where I need to escape the curly-braces. Whenever I use curly braces in my prompt, it is being taken as place holders.

So, can you please suggest how to escape the curly braces in the prompts?

**Comment by batmanscode** [comment]
They are f-strings; they can be escaped like this: `{{not a placeholder}}`

**Comment by nosas** [comment]
The solution is to use **double curly braces**, `{{}}`, as shown by @batmanscode.
I'd recommend using the Discord for quick questions as you'll receive a much quicker reply.


This issue can be closed.

**Comment by tamil-acog** [comment]
Hey, thanks for the reply. Will try that @batmanscode @nosas

**Comment by tkornuta-semiotic** [comment]
API entrypoint: check_content
- params
    content: str
    policy_type: str
- returns {response: a list of tuples/dicts {paragraph: ..., rule: ...}}

**Comment by lazyrong** [comment]
> They are f-strings; they can be escaped like this: `{{not a placeholder}}`
it is not work if my json objec is like this:
```
{
"book": "Jasmine Green Tea/Milk Tea",
"author": {
       "name": "Alex",
       "gender": "female"
}}
```

**Comment by not2technical** [comment]
if outputting JSON into the the history the issues still happens

**Comment by The-Inscrutable-X** [comment]
I vote for pursuing better ways to deal with JSON formatting in langchain. I am trying to write my custom formatting instructions without using the pydantic parser's auto generated formatting prompt, however I am unable to add it to the prompt because the prompt treats it as placeholders.

**Comment by MinLee0210** [comment]
My solution is to pass it as a `string`, then through lambda function. For instance, `json_data` is our json object and defined as a string: 

```
json_data = """
{
 ... some information here ....
}
"""
```

I define my prompt template consists of `json_data` and `question`. In my pipe, I pass the input like this:

```Python
rag_chain = (
    {"json_data": lambda x: json_data, "question": RunnablePassthrough()}
    | rag_prompt
    | llm
)
```

Hope it can help!

**Comment by VpkPrasanna** [comment]
> The solution is to use **double curly braces**, `{{}}`, as shown by @batmanscode. I'd recommend using the Discord for quick questions as you'll receive a much quicker reply.
> 
> This issue can be closed.

This method works 
If you are passing multiple objects , make sure each of the  object is enclosed with {{}}

**Comment by severfire** [comment]
Hi, seems like it is not working :-/

![image](https://github.com/user-attachments/assets/8696c8d3-c5c4-4a45-8ff1-06124c3d18d7)

**Comment by YoavTamir00** [comment]
Is there a solution for typescript? I have the same error

**Comment by hammadasad** [comment]
> My solution is to pass it as a `string`, then through lambda function. For instance, `json_data` is our json object and defined as a string:
> 
> ```
> json_data = """
> {
>  ... some information here ....
> }
> """
> ```
> 
> I define my prompt template consists of `json_data` and `question`. In my pipe, I pass the input like this:
> 
> ```python
> rag_chain = (
>     {"json_data": lambda x: json_data, "question": RunnablePassthrough()}
>     | rag_prompt
>     | llm
> )
> ```
> 
> Hope it can help!

This helped for me. Thanks!
