### ISSUE TITLE
Google Cloud PaLM API integration

### ISSUE THREAD

**Issue by einarbmag** [langchain-ai/langchain#1661]
Google has just announced the PaLM API [https://developers.googleblog.com/2023/03/announcing-palm-api-and-makersuite.html](https://developers.googleblog.com/2023/03/announcing-palm-api-and-makersuite.html)!!

**Comment by slavakurilyak** [comment]
The PaLM API will be released with a new tool called MakerSuite, which allows users to prototype ideas, do prompt engineering, synthetic data generation, and more.

**Comment by brotchie** [comment]
https://github.com/hwchase17/langchain/pull/3575 merged yesterday. Supports PaLM's Text, Chat, and Embeddings APIs.
