### ISSUE TITLE
Building document-based questions answer system with Lanchain, Python, FAISS like chat GPT-3 from multiple drug PDF files having same specs,different brand name,same symtoms,disease info

### ISSUE THREAD

**Issue by vinupardeshi** [langchain-ai/langchain#16617]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

def storefunction():
	loader=(r"dir path",loade_cs=Pypdfloader)
	documents=loader.load()
	text_splitter = RecursiveCharacterTextSplitter(chunk_size=10000, chunk_overlap=0)
	chunks = text_splitter.split_text(documents)
	embeddings = openAIEmbeddings(openai_api_key=os.environ["OPEN_API_KEY"])
	vector_store = FAISS.from_texts(documents=documents, embedding=embeddings)
	vector_store.save_local("faiss_index")
storefunction()
def question(query):
	store=Faiss.load_local("faiss_index",embeddings=openai_api_key=os.environ["OPEN_API_KEY"])

	llm=ChatOpenAI(openai_api_key=os.environ["OPEN_API_KEY"],model_name="gpt-3.5-turbo,temperature=0.5)
	prompt_template = """Do not give me any information about  procedure and service feature that are not mentioned in the provided context.
    		{context}
		Q:{question}

    		A:
    		"""
                           

    	prompt = PromptTemplate(template = prompt_template, input_variables = ["context", "question"])
	memory=ConversationBufferWindowMemory(k=1,returm_messges=True)
    	chain = ConverstionRetrievalqa(llm,memory=memory,chain_type="stuff",
		retreiver=store.as_retreiver(search_kwargs={'k':2},search_type="mmr"),chain_type_kwargs{"prompt":prompt})
	result=(qa_chain.run(query)
	print(result)

### Description

I am using  langchain,openai multiple medical drugs multiple brand products pdf files having same context (specification,dieaseses symptoms, doses . Help required to create conversationbufferwindowmemory using conversationretreivalqa chain and answering data from specific provided pdf documents and only one brand related info.

### System Info

python 3.11
windows 10
langchain 0.0.312
openai 1.8.0

**Comment by vinupardeshi** [comment]
Hi ,

Thanks for the response it has showing me error.
FAISS.from_embeddings() missing 1 required positional arguments :text_embeddings

**Comment by jatinchawda1503** [comment]
@vinupardeshi, 
Instead of this
```
store=Faiss.load_local("faiss_index",embeddings=openai_api_key=os.environ["OPEN_API_KEY"])
```
should be 
```
embeddings = openAIEmbeddings(openai_api_key=os.environ["OPEN_API_KEY"])
store=Faiss.load_local("faiss_index",embeddings=embeddings)
```
