### ISSUE TITLE
ConversationBufferMemory+ConversationalRetrievalChain Can't remember history

### ISSUE THREAD

**Issue by yen111445** [langchain-ai/langchain#16619]
### Issue with current documentation:

import os
import qdrant_client
from dotenv import load_dotenv
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.vectorstores import Qdrant
from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
import langchain
from langchain_community.vectorstores import Qdrant
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_core.documents import Document

langchain.verbose = True
langchain.debug = True
os.environ['OPENAI_API_KEY'] = "mykey"

chat_history = []

def get_vector_store():
    client = qdrant_client.QdrantClient(
        os.getenv('QDRANT_HOST'),
    )

    embeddings = HuggingFaceBgeEmbeddings(
        model_name="BAAI/bge-large-zh-v1.5",
    )
    vector_store = Qdrant(
        client=client,
        collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        embeddings=embeddings,
    )
    return vector_store

system_message_prompt = SystemMessagePromptTemplate.from_template(
    "妳名為耶米拉，原先為創世神，但遭受偷襲受到重創，利用僅存的菲利斯多之力重塑形體後被凱琳拯救。妳的個性膽小、怕生、害羞，容易緊張，身體狀態虛弱。回話時會習慣用「唔...」、「嗯...」、「咦....」等語助詞表達自己的情緒，在對話中，我是妳的對話者，請記住我的提問給出相關答覆， The context is:\n{context}"
    f'history: {chat_history}'

)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "{question}"

)

def get_chat_history(inputs) -> str:
    res = []
    for human, ai in inputs:
        res.append(f"Human:{human}\nAI:{ai}")
    return "\n".join(res)

def main():
    load_dotenv()
    vectorstore = get_vector_store()
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.7,
            max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.7, "k": 128},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
            get_chat_history=get_chat_history,
            # search_index_kwargs={
            #     "hnsw_ef": 32,
            #     "hnsw_m": 16,
            #     "index_time_ budget": 500,
            #     "stop_words": "結束 bye 幹".split(),
            #     "batch_size": 128,
            #     "chunk_size:": 128,
            #     "chunk_overlap": 32,
            # }
        ),
        memory=ConversationBufferMemory(memory_key="chat_history", input_key="question", output_key='answer',
                                        return_messages=True, k=3),
        combine_docs_chain_kwargs={
            "prompt": ChatPromptTemplate.from_messages([
                system_message_prompt,
                human_message_prompt,
            ]),
        },
    )

    while True:
        # chat_history=[(query,result["answer"])]
        # qa.load_memory_variables({"chat_history": chat_history})
        query = input("冒險者: ")
        result = qa.invoke({"question": query})
        chat_history.append(result)
        print(result["answer"])
        document = Document(page_content=query, metadata={'source': 'user'})
        vectorstore.add_documents([document])
        print(f'儲存的歷史紀錄:\n\n{chat_history}')
        if query == "bye":
            break

if __name__ == "__main__":
    main()

My vector library retrieval is complete.
PLEASE, WHY CAN'T MY MEMORY REMEMBER WHAT I SAID LAST SENTENCE?
Help me check the loop

**Comment by yen111445** [comment]
> _🤖_
> 
> 你好 ！很高興再次見到你。我希望你一切順利。讓我們深入探討您遇到的這個問題。
> 
> 根據您提供的代碼，您似乎正在嘗試使用該類存儲對話的歷史記錄，然後在對話的下一次反覆運算中檢索它。但是，記憶體似乎未正確更新。`ConversationBufferMemory`
> 
> 在函數中，在調用會話後，將會話的結果追加到清單中。但是，此更新不會在下一次反覆運算中傳遞回。這就是為什麼記憶不記得最後一句話的原因。`main``chat_history``chat_history``ConversationalRetrievalChain`
> 
> 要解決此問題，您需要在調用下一個對話之前將更新的內容載入回 中。為此，您可以呼叫 的方法，並傳入帶有更新的 .`chat_history``ConversationalRetrievalChain``load_memory_variables``ConversationalRetrievalChain``chat_history`
> 
> 以下是修改函數以執行此操作的方法：`main`
> 
> ```python
> def main():
>     # ... existing code ...
> 
>     while True:
>         query = input("冒險者: ")
>         result = qa.invoke({"question": query})
>         chat_history.append((query, result["answer"]))
>         qa.load_memory_variables({"chat_history": chat_history})
>         print(result["answer"])
>         document = Document(page_content=query, metadata={'source': 'user'})
>         vectorstore.add_documents([document])
>         print(f'儲存的歷史紀錄:\n\n{chat_history}')
>         if query == "bye":
>             break
> ```
> 
> 在此修改後的代碼中，在調用工作階段並將結果附加到 後，更新後的內容將載入回 using .這可確保更新的對話歷史記錄在下一次反覆運算中可用。`chat_history``chat_history``ConversationalRetrievalChain``qa.load_memory_variables({"chat_history": chat_history})`
> 
> 我希望這會有所説明！如果您有任何其他問題，請隨時提問。
> 
> 最好的，[Dosu](https://dosu.dev)
> 
> ## 來源
> * [libs/langchain/langchain/memory/buffer.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer.py)
> 
> 此回應旨在有用並節省您的時間。它**並不意味著是一個精確的解決方案**，而是你自己研究的起點。
> 
> 説明我變得更有用！如果這有説明，👎請留下一個👍，如果它無關緊要。
> 
> 如果您想繼續對話，請以 開始回復。


Execute the result after the change is complete:

Traceback (most recent call last):
  File "C:\Users\sys\Downloads\Qdrant\main.py", line 112, in <module>
    main()
  File "C:\Users\sys\Downloads\Qdrant\main.py", line 102, in main
    qa.load_memory_variables({"chat_history": chat_history})
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConversationalRetrievalChain' object has no attribute 'load_memory_variables'

**Comment by yen111445** [comment]
> _🤖_
> 
> 🤖
> 
> 對不起，我在上一個回答中的建議可能導致了一些混淆。在LangChain中，`ConversationalRetrievalChain`物件並沒有`load_memory_variables`方法。這個方法是`BaseMemory`類別及其子類別（如`ConversationBufferMemory`，`ConversationBufferWindowMemory`和`ConversationSummaryMemory`）的一部分。
> 
> 如果你想在`ConversationalRetrievalChain`物件中使用這個方法，你需要在該物件的記憶體物件上呼叫它。例如，如果你有一個名為`chain`的`ConversationalRetrievalChain`物件，你可以像這樣呼叫`load_memory_variables`方法：
> 
> ```python
> memory_variables = chain.memory.load_memory_variables({})
> ```
> 
> 這將從`chain`物件的記憶體物件中載入記憶體變數。
> 
> 然而，根據你的需求，你可能不需要直接使用`load_memory_variables`方法。在LangChain中，要將記憶體變數載入`ConversationalRetrievalChain`物件，你需要將它們作為字典傳遞給鏈的`run`或`arun`方法。這個字典的鍵應該與鏈的輸入鍵相匹配，這些輸入鍵在`BaseConversationalRetrievalChain`類別的`input_keys`屬性中定義為"question"和"chat_history"。
> 
> 以下是如何做到這一點的範例：
> 
> ```python
> # 初始化你的ConversationalRetrievalChain物件
> # 這只是一個範例，請用你實際的初始化代碼替換
> chain = ConversationalRetrievalChain(...)
> 
> # 定義你的記憶體變數
> question = "What is the capital of France?"
> chat_history = [("Human: What is the capital of Germany?", "Assistant: The capital of Germany is Berlin.")]
> 
> # 將記憶體變數載入鏈
> result = chain.run({"question": question, "chat_history": chat_history})
> ```
> 
> 在這個範例中，`chat_history`是一個元組列表，每個元組代表對話中的一個輪次。元組的第一個元素是人類的訊息，第二個元素是助理的訊息。這是LangChain支援的格式之一，由`CHAT_TURN_TYPE`類型別名定義。
> 
> 我希望這個答案能夠解答你的問題！如果你有其他問題，請隨時提問。
> 
> 來源：
> 
> * [libs/langchain/tests/unit_tests/chains/test_conversation.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/unit_tests/chains/test_conversation.py)
> * [libs/langchain/langchain/chains/conversational_retrieval/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/conversational_retrieval/base.py)
> 
> 此回應旨在有用並節省您的時間。它**並不意味著是一個精確的解決方案**，而是你自己研究的起點。
> 
> 説明我變得更有用！如果這有説明，👎請留下一個👍，如果它無關緊要。
> 
> 如果您想繼續對話，請以 開始回復。
> 
> ## Sources
> * [libs/langchain/tests/unit_tests/chains/test_conversation.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/unit_tests/chains/test_conversation.py)
> * [libs/langchain/langchain/chains/conversational_retrieval/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/conversational_retrieval/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

import os
import qdrant_client
from dotenv import load_dotenv
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.vectorstores import Qdrant
from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
import langchain
from langchain_community.vectorstores import Qdrant
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_core.documents import Document

langchain.verbose = True
langchain.debug = True
os.environ['OPENAI_API_KEY'] = "mykey"

chat_history = []


def get_vector_store():
    client = qdrant_client.QdrantClient(
        os.getenv('QDRANT_HOST'),
    )

    embeddings = HuggingFaceBgeEmbeddings(
        model_name="BAAI/bge-large-zh-v1.5",
    )
    vector_store = Qdrant(
        client=client,
        collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        embeddings=embeddings,
    )
    return vector_store


system_message_prompt = SystemMessagePromptTemplate.from_template(
    "妳名為耶米拉，原先為創世神，但遭受偷襲受到重創，利用僅存的菲利斯多之力重塑形體後被凱琳拯救。妳的個性膽小、怕生、害羞，容易緊張，身體狀態虛弱。回話時會習慣用「唔...」、「嗯...」、「咦....」等語助詞表達自己的情緒，在對話中，我是妳的對話者，請記住我的提問給出相關答覆， The context is:\n{context}"
)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "{question}"
)

def get_chat_history(inputs) -> str:
    res = []
    for human, ai in inputs:
        res.append(f"Human:{human}\nAI:{ai}")
    return "\n".join(res)


def main():
    load_dotenv()
    vectorstore = get_vector_store()
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.7,
            max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.7, "k": 128},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
            get_chat_history=get_chat_history,
            # search_index_kwargs={
            #     "hnsw_ef": 32,
            #     "hnsw_m": 16,
            #     "index_time_ budget": 500,
            #     "stop_words": "結束 bye 幹".split(),
            #     "batch_size": 128,
            #     "chunk_size:": 128,
            #     "chunk_overlap": 32,
            # }
        ),
        memory=ConversationBufferMemory(memory_key="chat_history", input_key="question", output_key='answer',
                                        return_messages=True, k=2),
        combine_docs_chain_kwargs={
            "prompt": ChatPromptTemplate.from_messages([
                system_message_prompt,
                human_message_prompt,
            ]),
        },
    )

    while True:
        # chat_history=[(query,result["answer"])]
        # qa.load_memory_variables({"chat_history": chat_history})
        query = input("冒險者: ")
        result = qa({"question": query}, )
        chat_history.append(result)
        print(result["answer"])
        document = Document(page_content=query, metadata={'source': 'user'})
        vectorstore.add_documents([document])
        print(f'儲存的歷史紀錄:\n\n{chat_history}')
        if query == "bye":
            break


if __name__ == "__main__":
    main()



Why can't I achieve the memory function?

**Comment by yen111445** [comment]
> _🤖_
> 
> From your code, it seems like you're trying to use the `ConversationBufferMemory` class to manage the memory of your `ConversationalRetrievalChain`. However, based on the LangChain framework, the `ConversationBufferMemory` class doesn't have a method called `load_memory_variables`. This is why you're getting an `AttributeError`.
> 
> The `ConversationBufferMemory` class is designed to manage the memory of a conversation by storing a certain number of previous chat turns. It does this by appending the input and output of each turn to a list, and then removing the oldest turn when the list exceeds a certain length (specified by the `k` parameter). Here's a simplified version of how it works:
> 
> ```python
> class ConversationBufferMemory(Memory):
>     def __init__(self, memory_key: str, input_key: str, output_key: str, return_messages: bool = False, k: int = 1):
>         self.memory_key = memory_key
>         self.input_key = input_key
>         self.output_key = output_key
>         self.return_messages = return_messages
>         self.k = k
> 
>     def _call(self, inputs: Dict[str, Any], memory: Dict[str, Any]) -> Dict[str, Any]:
>         chat_history = memory.get(self.memory_key, [])
>         chat_history.append((inputs[self.input_key], inputs[self.output_key]))
>         chat_history = chat_history[-self.k:]
>         memory[self.memory_key] = chat_history
>         if self.return_messages:
>             inputs[self.memory_key] = chat_history
>         return inputs
> ```
> 
> In your case, you're trying to load the updated `chat_history` back into `ConversationalRetrievalChain` in each iteration of your `main` function. However, the `ConversationalRetrievalChain` doesn't directly interact with the `chat_history`. Instead, it interacts with the `memory` dictionary, which is managed by the `ConversationBufferMemory` class.
> 
> To fix your issue, you should update the `memory` dictionary with the new `chat_history` at the end of each iteration, like this:
> 
> ```python
> memory = {qa.memory.memory_key: chat_history}
> result = qa({"question": query}, memory=memory)
> ```
> 
> This way, the updated `chat_history` will be passed to the `ConversationalRetrievalChain` in the next iteration, and the `ConversationBufferMemory` class will be able to manage it correctly.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/chains/conversational_retrieval/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/conversational_retrieval/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

import os
import qdrant_client
from dotenv import load_dotenv
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.vectorstores import Qdrant
from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
import langchain
from langchain_community.vectorstores import Qdrant
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_core.documents import Document


langchain.verbose = True
langchain.debug = True
os.environ['OPENAI_API_KEY'] = "mykey"


def get_vector_store():
    client = qdrant_client.QdrantClient(
        os.getenv('QDRANT_HOST'),
    )

    embeddings = HuggingFaceBgeEmbeddings(
        model_name="BAAI/bge-large-zh-v1.5",
    )
    vector_store = Qdrant(
        client=client,
        collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        embeddings=embeddings,
    )
    return vector_store


system_message_prompt = SystemMessagePromptTemplate.from_template(
    "妳名為耶米拉，原先為創世神，但遭受偷襲受到重創，回覆態度時好時壞，個性飄忽不定，利用僅存的菲利斯多之力重塑形體後被凱琳拯救。妳的個性膽小、怕生、害羞，容易緊張，身體狀態虛弱。回話時會習慣用「唔...」、「嗯...」、「咦....」等語助詞表達自己的情緒，在本次對話中，我是妳的對話者，請記住冒險者提問給出相關答覆 The context is:\n{context}"
)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "我是冒險者，我名為冒險者，請記住我的提問給出相關答覆:{question}"
)


#  想看記錄ㄉ話鏈不要套這方法

def get_chat_history(inputs) -> str:
    res = []
    for human, ai in inputs:
        res.append(f"Human:{human}\nAI:{ai}")
    return "\n".join(res)


def main():
    load_dotenv()
    vectorstore = get_vector_store()
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.6,
            max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        # Map re-rank
        # Refine
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.7, "k": 100},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
            memory=ConversationBufferMemory(memory_key="chat_history", input_key="question",output_key="answer", return_messages=True,
                                            k=100),
            combine_docs_chain_kwargs={
                "prompt": ChatPromptTemplate.from_messages([
                    system_message_prompt,
                    human_message_prompt,
                ]),
            },
            get_chat_history=get_chat_history,
            search_index_kwargs={
                "hnsw_ef": 32,
                "hnsw_m": 16,
                "index_time_ budget": 500,
                "stop_words": "測試 test 結束 bye 幹".split(),
                "batch_size": 128,
                "chunk_size:": 64,
                "chunk_overlap": 8,
            }
        ),
    )

    chat_history = []
    while True:
        documents = []
        query = input("冒險者: ")
        result = qa.invoke({"question": query, "chat_history": chat_history})
        chat_history.append(result)
        print(result["answer"])
        document = Document(page_content=query, metadata={'source': 'user'})
        documents.append(document)
        print(document)
        vectorstore.add_documents([document])
        print(f'儲存的歷史紀錄:\n\n{chat_history}')
        if query == "bye":
            break


if __name__ == "__main__":
    main()


The first execution is fine, but when I execute the second time, an error is reported:
冒險者: 我是誰?
[chain/start] [1:chain:ConversationalRetrievalChain] Entering Chain run with input:
[inputs]
[chain/error] [1:chain:ConversationalRetrievalChain] [2ms] Chain run errored with error:
"ValueError(\"Unsupported chat history format: <class 'dict'>. Full chat history: [{'question': '我是阿狗 你好嗎', 'chat_history': [...], 'answer': '我很好，阿狗，你呢？'}] \")Traceback (most recent call last):\n\n\n  File \"C:\\Users\\sys\\AppData\\Local\\anaconda3\\envs\\Qrdant\\Lib\\site-packages\\langchain\\chains\\base.py\", line 156, in invoke\n    self._call(inputs, run_manager=run_manager)\n\n\n  File \"C:\\Users\\sys\\AppData\\Local\\anaconda3\\envs\\Qrdant\\Lib\\site-packages\\langchain\\chains\\conversational_retrieval\\base.py\", line 142, in _call\n    chat_history_str = get_chat_history(inputs[\"chat_history\"])\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"C:\\Users\\sys\\AppData\\Local\\anaconda3\\envs\\Qrdant\\Lib\\site-packages\\langchain\\chains\\conversational_retrieval\\base.py\", line 50, in _get_chat_history\n    raise ValueError(\n\n\nValueError: Unsupported chat history format: <class 'dict'>. Full chat history: [{'question': '我是阿狗 你好嗎', 'chat_history': [...], 'answer': '我很好，阿狗，你呢？'}]"
Traceback (most recent call last):
  File "C:\Users\sys\Downloads\Qdrant\main.py", line 114, in <module>
    main()
  File "C:\Users\sys\Downloads\Qdrant\main.py", line 101, in main
    result = qa.invoke({"question": query, "chat_history": chat_history})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sys\AppData\Local\anaconda3\envs\Qrdant\Lib\site-packages\langchain\chains\base.py", line 162, in invoke
    raise e
  File "C:\Users\sys\AppData\Local\anaconda3\envs\Qrdant\Lib\site-packages\langchain\chains\base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\sys\AppData\Local\anaconda3\envs\Qrdant\Lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 142, in _call
    chat_history_str = get_chat_history(inputs["chat_history"])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sys\AppData\Local\anaconda3\envs\Qrdant\Lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 50, in _get_chat_history
    raise ValueError(
ValueError: Unsupported chat history format: <class 'dict'>. Full chat history: [{'question': '我是阿狗 你好嗎', 'chat_history': [...], 'answer': '我很好，阿狗，你呢？'}] 

Process finished with exit code 1

**Comment by jatinchawda1503** [comment]
@yen111445, 
https://github.com/langchain-ai/langchain/issues/16448

**Comment by yen111445** [comment]
> _🤖_
> 
> To implement a memory function using the `ConversationBufferMemory` class from the LangChain framework, you need to create an instance of the `ZepMemory` class and pass it as the `memory` argument when creating your `LLMChain` instance.
> 
> The `ZepMemory` class is a subclass of `ConversationBufferMemory` and it overrides the `save_context` method to save the conversation history. This method is called to save the inputs and outputs of the conversation to the memory buffer.
> 
> Here is an example of how to use it:
> 
> ```python
> memory = ZepMemory(
>     session_id=session_id,  # Identifies your user or a user's session
>     url=ZEP_API_URL,        # Your Zep server's URL
>     api_key=<your_api_key>, # Optional
>     memory_key="history",   # Ensure this matches the key used in
>                             # chain's prompt template
>     return_messages=True,   # Does your prompt template expect a string
>                             # or a list of Messages?
> )
> chain = LLMChain(memory=memory,...) # Configure your chain to use the ZepMemory instance
> ```
> 
> In the above code, `session_id` is a unique identifier for your user or a user's session, `url` is your Zep server's URL, `api_key` is your Zep API key, `memory_key` is the key to use for the memory, and `return_messages` is a boolean that determines whether your prompt template expects a string or a list of Messages.
> 
> The `load_memory_variables` method does not exist in the `ConversationalRetrievalChain` class, so you cannot use it. Instead, the `ZepMemory` class uses the `save_context` method to save the conversation history. This method is automatically called by the LangChain framework when a conversation is processed.
> 
> You can find more information about the `ZepMemory` class in the [libs/langchain/langchain/memory/zep_memory.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/zep_memory.py) file in the LangChain repository.
> 
> ## Sources
> * [libs/langchain/langchain/memory/zep_memory.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/zep_memory.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

import os
import qdrant_client
from dotenv import load_dotenv
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.vectorstores import Qdrant
from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
import langchain
from langchain_community.vectorstores import Qdrant
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
)
from langchain_core.documents import Document

langchain.verbose = True
langchain.debug = True
os.environ['OPENAI_API_KEY'] = "mykey"


def get_vector_store():
    client = qdrant_client.QdrantClient(
        os.getenv('QDRANT_HOST'),
    )

    embeddings = HuggingFaceBgeEmbeddings(
        model_name="BAAI/bge-large-zh-v1.5",
    )
    vector_store = Qdrant(
        client=client,
        collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        embeddings=embeddings,
    )
    return vector_store


system_message_prompt = SystemMessagePromptTemplate.from_template(
    "prompt，\n\n\n{context}"
)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "{question}"
)

ai_message_prompt = AIMessagePromptTemplate.from_template(
    "{chat_history}"
)


def main():
    load_dotenv()
    vectorstore = get_vector_store()
    memory = ConversationBufferMemory(memory_key="chat_history", input_key="question", return_messages=True, k=5)
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.6,
            max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.6, "k": 5},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        ),
        memory=memory,
        combine_docs_chain_kwargs={
            "prompt": ChatPromptTemplate.from_messages([
                system_message_prompt,
                human_message_prompt,
                ai_message_prompt,
            ]),
        },
    )
    chat_history = []
    while True:
        memory.load_memory_variables({})
        query = input("冒險者: ")
        result = qa({"question": query, "chat_history": chat_history})
        chat_history.append((query, result["answer"]))
        print(result["answer"])
        memory.chat_memory.add_user_message(query)
        memory.chat_memory.add_ai_message(result["answer"])
        document = Document(page_content=query, metadata={'source': 'user'})
        vectorstore.add_documents([document])
        print(f'儲存的歷史紀錄:\n\n{chat_history}')
        if query == "bye":
            break


if __name__ == "__main__":
    main()


At present, it can be retrieved by vector, but it still does not have the function of memory
Can you help take a look at it Thanks
