### ISSUE TITLE
ConversationalRetrievalChain.from  ConversationBufferMemory Unable to achieve memories

### ISSUE THREAD

**Issue by yen111445** [langchain-ai/langchain#16621]
### Issue with current documentation:

import os
import qdrant_client
from dotenv import load_dotenv
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
from langchain.vectorstores import Qdrant
from langchain_community.chat_models import ChatOpenAI
from langchain_community.embeddings import HuggingFaceBgeEmbeddings
import langchain
from langchain_community.vectorstores import Qdrant
from langchain.prompts import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_core.documents import Document

langchain.verbose = True
langchain.debug = True
os.environ['OPENAI_API_KEY'] = "mykey"

def get_vector_store():
    client = qdrant_client.QdrantClient(
        os.getenv('QDRANT_HOST'),
    )

    embeddings = HuggingFaceBgeEmbeddings(
        model_name="BAAI/bge-large-zh-v1.5",
    )
    vector_store = Qdrant(
        client=client,
        collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
        embeddings=embeddings,
    )
    return vector_store

system_message_prompt = SystemMessagePromptTemplate.from_template(
    "妳名為耶米拉，原先為創世神，但遭受偷襲受到重創，重塑形體後被凱琳拯救。妳的個性膽小、怕生、害羞，容易緊張，身體狀態虛弱。回話時會習慣用「唔...」、「嗯...」、「咦....」等語助詞表達自己的情緒，在對話中，我是妳的對話者，請記住我的提問給出相關答覆， The context is:\n{context}"
)

human_message_prompt = HumanMessagePromptTemplate.from_template(
    "{question}"
)

def get_chat_history(inputs) -> str:
    res = []
    for human, ai in inputs:
        res.append(f"Human:{human}\nAI:{ai}")
    return "\n".join(res)

def main():
    load_dotenv()
    vectorstore = get_vector_store()
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(
            temperature=0.7,
            # max_tokens=100,
            model=os.getenv('QDRANT_MODEL_NAME'),
        ),
        chain_type="stuff",
        retriever=vectorstore.as_retriever(
            search_type="similarity_score_threshold",
            search_kwargs={"score_threshold": 0.7, "k": 1500},
            collection_name=os.getenv('QDRANT_COLLECTION_NAME'),
            get_chat_history=get_chat_history,
        ),
        memory=ConversationBufferMemory(memory_key="chat_history", input_key="question", return_messages=True),
        combine_docs_chain_kwargs={
            "prompt": ChatPromptTemplate.from_messages([
                system_message_prompt,
                human_message_prompt,
            ]),
        },
    )
    chat_history = []
    while True:
        query = input("冒險者: ")
        result = qa({"question": query}, )
        chat_history.append(result)
        print(result["answer"])
        document = Document(page_content=query, metadata={'source': 'user'})
        vectorstore.add_documents([document])
        print(f'儲存的歷史紀錄:\n\n{chat_history}')
        if query == "bye":
            break

if __name__ == "__main__":
    main()

How do I read my chat history when I reply?

### Idea or request for content:

How do I read my chat_history when I reply?

**Comment by jatinchawda1503** [comment]
This issue is duplicate - https://github.com/langchain-ai/langchain/issues/16619

**Comment by yen111445** [comment]
@jatinchawda1503 Sorry, I will pay attention to the repeated questions. Thank you for the reminder. I am very sorry for the inconvenience

**Comment by eyurtsev** [comment]
@yen111445 No worries. I am wondering are you creating issues to be able to chat with dosu?
