### ISSUE TITLE
RecursiveCharacterTextSplitter.split_text can enter infinite recursive loop

### ISSUE THREAD

**Issue by SpaceCowboy850** [langchain-ai/langchain#1663]
I was attempting to split this volume:
https://terrorgum.com/tfox/books/introductionto3dgameprogrammingwithdirectx12.pdf

using

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size = 1000
        chunk_overlap  = 10,
        length_function = len,
        separators="\n\n"
    )

On page 289, it enters an infinite recursive loop where it only has one split and no seperators in the split.  It then keeps recursively calling self.split_text(s) until it errors out.

modifying to a chunk_size of 2000 with a chunk overlap of 100 makes this go away, but it seems there should be some detection of infinite recursion happening, as the error result wasn't immediately obvious.

**Comment by colinricardo** [comment]
can you paste the relevant text please? 

e.g.

text: 
output:
expected output:

**Comment by MacYang555** [comment]
I ran into the same issue, to work around the problem, please have `separators= ["\n\n", ""] `when creating the RecursiveCharacterTextSplitter, where the added separator "" acts as a "fallback"

if we check the source code of RecursiveCharacterTextSplitter, we can find:
`        self._separators = separators or ["\n\n", "\n", " ", ""]`

and this logic to select a separator is:
```
      separator = self._separators[-1]
      for _s in self._separators:
          if _s == "":
              separator = _s
              break
          if _s in text:
              separator = _s
              break
```

maybe prepending the user given separators to the default ones (["\n\n", "\n", " ", ""]) is a user-friend way to avoid potential infinite recursive loop.

**Comment by SpaceCowboy850** [comment]
Text that it chokes on is this:
"0 and 1. Direct3D will then use the elements from the different input slots to assemble the vertices. This can be used as an optimization. For example, in the shadow mapping algorithm, we need to draw our scene twice per frame: once from the perspective of the light source (shadow pass) and once from the perspective of the main camera (main pass). The shadow pass only requires the position data and texture coordinates (for alpha tested geometry). So we can split the vertex data into two slots: one slot contains position and texture coordinates, and the other slot contains the other vertex attributes (e.g., normal and tangent vectors). Now we can easily only stream in the vertex data the shadow pass needs (position and texture coordinates), thereby saving data bandwidth for the shadow pass. The main render pass would use both vertex input slots to get all the vertex data it needs. For performance, the advice is to minimize the number of input slots used to a small number less than or equal to 3."

**Comment by wiaa1234** [comment]
Not sure if this helps: https://python.langchain.com/en/latest/modules/indexes/text_splitters/examples/recursive_text_splitter.html
