### ISSUE TITLE
ImportError: cannot import name 'ensure_config' from 'langchain_core.runnables'

### ISSUE THREAD

**Issue by Ashu3984** [langchain-ai/langchain#16640]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain.chains.sql_database.base import SQLDatabaseChain
from langchain_experimental.sql import SQLDatabaseChain

### Error Message and Stack Trace (if applicable)

cannot import name 'ensure_config' from 'langchain_core.runnables' (C:\Users\ashut\anaconda3\lib\site-packages\langchain_core\runnables\__init__.py)

### Description

I am trying langchain.chains.sql_database.base and  langchain_experimental.sql  to import SQLDatabaseChain but i am getting same error after running !pip install -U langchain langchain_experimental

### System Info

##ImportError: cannot import name 'ensure_config' from 'langchain_core.runnables' (C:\Users\ashut\anaconda3\lib\site-packages\langchain_core\runnables\__init__.py)

**Comment by eyurtsev** [comment]
Could you include the full stack trace so we can see from which file this issue is raised. Also please include system information as was specified in the bug report. It's hard issues without knowing which versions of the packages are installed.

**Comment by eyurtsev** [comment]
If you update to a recent version of `langchain-core` this issue should resolve itself.

**Comment by eyurtsev** [comment]
Going to close since this does not look like a current issue with langchain.

**Comment by JanLeyva** [comment]
Hey, if someone find this issue what worked for me is uninstall `langchain-cor` and install `langchain`last version. Hope it is useful!

**Comment by hmonarola** [comment]
Thanks, JanLeyva. Your suggestion works for me. I have uninstalled `langchain-core` module and Installed `langchain` latest version.

**Comment by shubham4576** [comment]
Thanks @JanLeyva . It worked.
