### ISSUE TITLE
The interface documentation is not updated

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#16674]
### Issue with current documentation:

https://python.langchain.com/docs/expression_language/interface

In the above link, we have a code that has a deprecated function which is chain.input_schema.schema() 

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

model = ChatOpenAI()
prompt = ChatPromptTemplate.from_template("tell me a joke about {topic}")
chain = prompt | model

print(chain.input_schema.schema()) - This here shows deprecated.

### Idea or request for content:

Please update the documentation.

**Comment by hwchase17** [comment]
hm what version of langchain are you on? I dont think this should be deprecated

**Comment by rajib76** [comment]
I re-installed the package. I still see that .schema is striked out. Sharing a screenshot

<img width="630" alt="Screen Shot 2024-01-28 at 8 15 28 PM" src="https://github.com/langchain-ai/langchain/assets/16340036/29b60244-be53-430e-8f3d-b710c83f5e01">
