### ISSUE TITLE
infra: Fix local docs and api ref builds

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#16677]
Has anyone had any issues with getting the docs to build? I continuously get this error when running poetry install:
```
The current project could not be installed: No file/folder found for package langchain-monorepo
If you do not want to install the current project use --no-root
```

Additionally, both `make docs_build` & `make api_docs_build` fail. The docs_build fails because of 
```
[ERROR] Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- langgraph
```
The api_docs_build has quite a few errors. Not sure if I'm missing downloading something critical.

_Originally posted by @rshah98626 in https://github.com/langchain-ai/langchain/issues/15664#issuecomment-1913262415_

**Comment by k8si** [comment]
Any update on this?
