### ISSUE TITLE
DOC: Missing dependency installation steps

### ISSUE THREAD

**Issue by Naveenkhasyap** [langchain-ai/langchain#16703]
### Issue with current documentation:

FastAPI installation step is missing in documentation 

### Idea or request for content:

In this https://python.langchain.com/docs/get_started/quickstart#serving-with-langserve 
we need to add dependency installation step.

```pip install FastAPI```

**Comment by hwchase17** [comment]
this gets installed as part of `pip install "langserve[all]"`
