### ISSUE TITLE
DOC: Returning structured output from agent documentations not correct

### ISSUE THREAD

**Issue by weihong0827** [langchain-ai/langchain#16720]
### Issue with current documentation:

I have followed the documentations guide and create an agent with vector retriever with a Pydantic schema passed as function into the agent, but it seems that there is no information from. the retriever is passed to the schema function, the schema function will just give source [1] as output. I have also tried a exact replicate of the code in the documentation with my own data since I don't have the state_of_the_union text file and I got the same error as what I am getting in my own implementation
This is the documentation link https://python.langchain.com/docs/modules/agents/how_to/agent_structured
during my experiments
<img width="861" alt="image" src="https://github.com/langchain-ai/langchain/assets/48542562/26197d99-c0b3-4cc5-b2b3-9f83f1e619a1">
You can see that this piece of information containing capstone =. 5.5 is at page chuck 10
<img width="841" alt="image" src="https://github.com/langchain-ai/langchain/assets/48542562/1b98f72e-061f-482d-91cf-8d6ae808ef31">
In the response to what is my capstone grade, it gives source [] which is definitely not the right information

### Idea or request for content:

I am not too exactly sure about what is causing the problem, maybe I should flag this as a bug or maybe just some configuration error.
My suspicion is that after the creation of the retriever tool, it formats the document using a prompt which strip away the meta data information. I have tried passing an additional prompt when im creating the retriever tool so that it returns the meta data output together with the content.
<img width="629" alt="image" src="https://github.com/langchain-ai/langchain/assets/48542562/bfce8431-09a6-4c42-adbe-c04eb94cf418">
this will result in the answer formatted to be 
<img width="289" alt="image" src="https://github.com/langchain-ai/langchain/assets/48542562/a7828f65-0eff-4835-9580-5ef331f3b68b">
But it takes a lot of luck and tuning to get the final answer to get the correct source information (have succeeded before once in a while but not most of the time)

Please advise on what could be the potential solution to this, thank you very much

**Comment by weihong0827** [comment]
@dosu-bot my problem is mainly the agent is not getting the right meta data information from the retriever

**Comment by weihong0827** [comment]
@dosu-bot I understand that document type is return from a vector store retrieval, but we create a retriever tool from the vector store, it will convert the Document to be a string with out the meta data information through a prompt template which will then be passed to the next agent action

**Comment by weihong0827** [comment]
Yes this is what I have, but it seems like with the formatted string and the Pydantic openai function, it seems that the rate that the parsing function is called is very low and hence not returning the correct format

**Comment by zmartin1** [comment]
The example listed here demonstrates the bug: https://python.langchain.com/docs/modules/agents/how_to/agent_structured. The answer to the question asked, isn't in the 6th `page_chunk` document, which is what the API call returns:
```
{'answer': "President Biden nominated Ketanji Brown Jackson for the United States Supreme Court and described her as one of our nation's top legal minds who will continue Justice Breyer's legacy of excellence.",
 'sources': [6]}
```
Here is the `Document` that corresponds to `page_chunk=6` printed:

> Document(page_content='And I’m taking robust action to make sure the pain of our sanctions  is targeted at Russia’s economy. And I will use every tool at our disposal to protect American businesses and consumers. \n\nTonight, I can announce that the United States has worked with 30 other countries to release 60 Million barrels of oil from reserves around the world.  \n\nAmerica will lead that effort, releasing 30 Million barrels from our own Strategic Petroleum Reserve. And we stand ready to do more if necessary, unified with our allies.  \n\nThese steps will help blunt gas prices here at home. And I know the news about what’s happening can seem alarming. \n\nBut I want you to know that we are going to be okay. \n\nWhen the history of this era is written Putin’s war on Ukraine will have left Russia weaker and the rest of the world stronger. \n\nWhile it shouldn’t have taken something so terrible for people around the world to see what’s at stake now everyone sees it clearly.', metadata={'source': 'state_of_the_union.txt', 'page_chunk': 6})

**Comment by weihong0827** [comment]
> The example listed here demonstrates the bug: https://python.langchain.com/docs/modules/agents/how_to/agent_structured. The answer to the question asked, isn't in the 6th `page_chunk` document, which is what the API call returns:
> 
> ```
> {'answer': "President Biden nominated Ketanji Brown Jackson for the United States Supreme Court and described her as one of our nation's top legal minds who will continue Justice Breyer's legacy of excellence.",
>  'sources': [6]}
> ```
> 
> Here is the `Document` that corresponds to `page_chunk=6` printed:
> 
> > Document(page_content='And I’m taking robust action to make sure the pain of our sanctions  is targeted at Russia’s economy. And I will use every tool at our disposal to protect American businesses and consumers. \n\nTonight, I can announce that the United States has worked with 30 other countries to release 60 Million barrels of oil from reserves around the world.  \n\nAmerica will lead that effort, releasing 30 Million barrels from our own Strategic Petroleum Reserve. And we stand ready to do more if necessary, unified with our allies.  \n\nThese steps will help blunt gas prices here at home. And I know the news about what’s happening can seem alarming. \n\nBut I want you to know that we are going to be okay. \n\nWhen the history of this era is written Putin’s war on Ukraine will have left Russia weaker and the rest of the world stronger. \n\nWhile it shouldn’t have taken something so terrible for people around the world to see what’s at stake now everyone sees it clearly.', metadata={'source': 'state_of_the_union.txt', 'page_chunk': 6})

I have to pass a prompt template into the tool so that the responses from the retriever includes the source, and hence with a little more prompt engineering then my pydantic openai function is able to return in the correct response

**Comment by mzhadigerov** [comment]
is there anyone from Langchain team who can help with this issue?
