### ISSUE TITLE
not able to add few shots example to create_sql_agent

### ISSUE THREAD

**Issue by akashkumar398** [langchain-ai/langchain#16731]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

i want to add few shots example to make my prompts better to understand the complex questions to create_sql_agent

toolkit = SQLDatabaseToolkit(db=db, llm=llm)

agent_executor = create_sql_agent(
    prefix=MSSQL_AGENT_PREFIX,
    format_instructions = MSSQL_AGENT_FORMAT_INSTRUCTIONS,
    llm=llm,
    toolkit=toolkit,
    top_k=30,
    verbose=True
)

### Error Message and Stack Trace (if applicable)

i want to add few shots example to make my prompts better to understand the complex questions to create_sql_agent

toolkit = SQLDatabaseToolkit(db=db, llm=llm)

agent_executor = create_sql_agent(
    prefix=MSSQL_AGENT_PREFIX,
    format_instructions = MSSQL_AGENT_FORMAT_INSTRUCTIONS,
    llm=llm,
    toolkit=toolkit,
    top_k=30,
    verbose=True
)

### Description

i want to add FewShotPromptTemplate to my agent_executor 

examples = [
    {"input": "List all artists.", "query": "SELECT * FROM Artist;"},
    {
        "input": "Find all albums for the artist 'AC/DC'.",
        "query": "SELECT * FROM Album WHERE ArtistId = (SELECT ArtistId FROM Artist WHERE Name = 'AC/DC');",
    },
    {
        "input": "List all tracks in the 'Rock' genre.",
        "query": "SELECT * FROM Track WHERE GenreId = (SELECT GenreId FROM Genre WHERE Name = 'Rock');",
    }]

from langchain_core.prompts import FewShotPromptTemplate, PromptTemplate

agent_executor = create_sql_agent(
    prefix=MSSQL_AGENT_PREFIX,
    format_instructions = MSSQL_AGENT_FORMAT_INSTRUCTIONS,
    llm=llm,
    toolkit=toolkit,
    top_k=30,
    verbose=True
)

### System Info

langchain  version 0.0.352

**Comment by akashkumar398** [comment]
i am getting this error now: type object ‘PromptTemplate’ has no attribute ‘from_messages’

**Comment by jatinchawda1503** [comment]
@akashkumar398, 
You can try like this, 
```
example_prompt = PromptTemplate(
    input_variables=["question", "answer"], template="Question: {question}\n{answer}"
)

prompt = FewShotPromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
    suffix="Question: {input}",
    input_variables=["input"],
)

create_sql_agent(prompt=prompt)
```

Please refer : https://api.python.langchain.com/en/stable/agent_toolkits/langchain_community.agent_toolkits.sql.base.create_sql_agent.html#langchain_community.agent_toolkits.sql.base.create_sql_agent

**Comment by tombeteende** [comment]
@jatinchawda1503 unfortunately, this does not work as it expects to obtain `agent_scratchpad` variable
