### ISSUE TITLE
OutputParserException: This output parser can only be used with a chat generation.

### ISSUE THREAD

**Issue by AtmehEsraa** [langchain-ai/langchain#16743]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

model_id = "facebook/opt-2.7b"

tokenizer = AutoTokenizer.from_pretrained(model_id)

base_model = AutoModelForCausalLM.from_pretrained(
    model_id,
    load_in_8bit=True,
    device_map='auto'
)

pipe = pipeline("text-generation",
                model=base_model,
                tokenizer=tokenizer,
                max_length=256,
                temperature=0.6,
                top_p=0.95,
                repetition_penalty=1.2)

llm = HuggingFacePipeline(pipeline=pipe)

class Booking(BaseModel):

    date_of_arrival: str = Field(description="Time of check in")
    date_of_departure: str = Field(description="Time of check out")
    number_of_guests: int = Field(description="number of guests")
    room_type: str = Field(description="name of room")
    special_requests: list = Field(description="list of special requests")
    contact_information: list = Field(description="list of contanct information like email and phone")

booking_message = """Hi there! I'm interested in booking a meeting room for a small business conference. The dates I have in mind are February 5th to February 6th, 2024, and we expect around 6 guests to attend. We'll need a standard meeting room with basic amenities. However, we'll also require a projector and whiteboard for presentations. You can reach me at """

chain = create_extraction_chain_pydantic(pydantic_schema=Booking, llm=llm)
chain.run(booking_message)

### Error Message and Stack Trace (if applicable)

OutputParserException: This output parser can only be used with a chat generation.

### Description

OutputParserException: This output parser can only be used with a chat generation.

### System Info

.

**Comment by eyurtsev** [comment]
Please see https://python.langchain.com/docs/use_cases/extraction for more information about extraction.

**Comment by arad2022** [comment]
> ### Checked other resources
> * [x]  I added a very descriptive title to this issue.
> * [x]  I searched the LangChain documentation with the integrated search.
> * [x]  I used the GitHub search to find a similar question and didn't find it.
> * [x]  I am sure that this is a bug in LangChain rather than my code.
> 
> ### Example Code
> model_id = "facebook/opt-2.7b"
> 
> tokenizer = AutoTokenizer.from_pretrained(model_id)
> 
> base_model = AutoModelForCausalLM.from_pretrained( model_id, load_in_8bit=True, device_map='auto' )
> 
> pipe = pipeline("text-generation", model=base_model, tokenizer=tokenizer, max_length=256, temperature=0.6, top_p=0.95, repetition_penalty=1.2)
> 
> llm = HuggingFacePipeline(pipeline=pipe)
> 
> class Booking(BaseModel):
> 
> ```
> date_of_arrival: str = Field(description="Time of check in")
> date_of_departure: str = Field(description="Time of check out")
> number_of_guests: int = Field(description="number of guests")
> room_type: str = Field(description="name of room")
> special_requests: list = Field(description="list of special requests")
> contact_information: list = Field(description="list of contanct information like email and phone")
> ```
> 
> booking_message = """Hi there! I'm interested in booking a meeting room for a small business conference. The dates I have in mind are February 5th to February 6th, 2024, and we expect around 6 guests to attend. We'll need a standard meeting room with basic amenities. However, we'll also require a projector and whiteboard for presentations. You can reach me at """
> 
> chain = create_extraction_chain_pydantic(pydantic_schema=Booking, llm=llm) chain.run(booking_message)
> 
> ### Error Message and Stack Trace (if applicable)
> OutputParserException: This output parser can only be used with a chat generation.
> 
> ### Description
> OutputParserException: This output parser can only be used with a chat generation.
> 
> ### System Info
> .

Did you find any solution for this issue?
