### ISSUE TITLE
get_openai_callback not working when using Agent Executor after updating to latest version of Langchain

### ISSUE THREAD

**Issue by EduardoMM17** [langchain-ai/langchain#16798]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
class MyCustomAsyncHandler(AsyncCallbackHandler):
    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Run when chain ends running."""
        print("RESPONSE: ", response)
        print("Hi! I just woke up. Your llm is ending")


async def ask_assistant(input: str) -> str:
    prompt = PromptTemplate.from_template(prompt_raw)

    prompt = prompt.partial(
        language="Spanish",
        tools=render_text_description(tools),
        tool_names=", ".join([t.name for t in tools]),
    )

    llm = ChatOpenAI(
        temperature=0,
        model_name="gpt-4",
        openai_api_key=os.environ["OPENAI_API_KEY"],
        callbacks=[MyCustomAsyncHandler()],
    )
    llm_with_stop = llm.bind(stop=["\nObservation"])

    agent = (
        {
            "input": lambda x: x["input"],
            "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
            "chat_history": lambda x: x["chat_history"],
        }
        | prompt
        | llm_with_stop
        | ReActSingleInputOutputParser()
    )

    agent_executor = AgentExecutor(
        agent=agent,
        tools=tools,
        verbose=True,
        memory=memory,
        max_execution_time=60,
        handle_parsing_errors=True,
    )

    with get_openai_callback() as cb:
        clara_ai_resp = await agent_executor.ainvoke({"input": input})
        clara_ai_output = clara_ai_resp["output"]

        print("CB: ", cb)

        return clara_ai_output, input, cb
```

### Description

I'm trying to use the get_openai_callback from langchain_community.callbacks to get the number of token and costs incurred in using the agent but I am getting zero on everything, as you can see here when I print.

![image](https://github.com/langchain-ai/langchain/assets/46487685/d728843a-6191-4f97-97e5-65431c02f98e)

I have also set up a custom callback handler to go deep into the issue and what I found is that ChatOpenAI from langchain_openai does not call ainvoke as ChatOpenAI langchain.chat_models did.

THank you for your help

### System Info

python 3.11.5

**Comment by EduardoMM17** [comment]
@dosu-bot

Your solutions is not working and your sources appear as 404.

**Comment by devstein** [comment]
Hey @EduardoMM17 we are investigating why Dosu linked to a file that doesn't exist. Sorry for the confusion!

**Comment by EduardoMM17** [comment]
@dosu-bot
Hey dosubot, ok I am using the new OpenAI specific agents but the get_openai_callback is not working and I need to keep track of the tokens and costs of my usage.

**Comment by danieleratti** [comment]
Same issue here and no solution found

Even if I try to attach a callback to the llm, I get None as response.llm_output (so I can't access the number of tokens) and if I attach a callback to the AgentExecutor, I only get the on_agent_finish callback (which is useless for getting tokens and cost)...

**Comment by EduardoMM17** [comment]
@danieleratti 

I managed to make a workaround using tiktoken inside the CustomAsyncHandler class. Then you can just use a function like get_openai_cost_for_model in line 2 to calculate the costs.

I have also verified that the token count is the same or similar to what I get from Langsmith and to my surprise it is. In the input tokens I see a difference of ~10, which is not that much and in the completion I get a difference of ~1 or no difference. So I will be using this in the meantime until I come up with a more elegant solution or someone fixes the bug. Check the code below:

```python
from langchain.callbacks.base import AsyncCallbackHandler
from langchain_community.callbacks.openai_info import get_openai_token_cost_for_model

from app.services.llm.prompt import prompt_raw
from app.services.llm.tools.build_tools import tools
from app.classes.CustomBuffer import CustomConversationBufferMemory

memory = CustomConversationBufferMemory(memory_key="chat_history", return_messages=True)

# use get_openai_token_cost_for_model to calculate cost
class MyCustomAsyncHandler(AsyncCallbackHandler):
    async def on_llm_start(
        self,
        serialized: dict[str, Any],
        prompts: list[str],
        **kwargs: Any,
    ) -> None:
        encoding = tiktoken.get_encoding("cl100k_base")
        prompts_string = ''.join(prompts)
        num_tokens = len(encoding.encode(prompts_string))
        print("NUM TOKENS: ", num_tokens)


    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Run when chain ends running."""
        text_response = response.generations[0][0].text
        encoding = tiktoken.get_encoding("cl100k_base")
        response_string = len(encoding.encode(text_response))
        print("NUM TOKENS RESPONSE: ", response_string)

async def ask_assistant(input: str) -> str:
    prompt = PromptTemplate.from_template(prompt_raw)

    prompt = prompt.partial(
        language="Spanish",
        tools=render_text_description(tools),
        tool_names=", ".join([t.name for t in tools]),
    )

    llm = ChatOpenAI(
        temperature=0,
        model_name="gpt-4",
        openai_api_key=os.environ["OPENAI_API_KEY"],
        callbacks=[MyCustomAsyncHandler()],
    )
    llm_with_stop = llm.bind(stop=["\nObservation"])

    agent = (
        {
            "input": lambda x: x["input"],
            "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
            "chat_history": lambda x: x["chat_history"],
        }
        | prompt
        | llm_with_stop
        | ReActSingleInputOutputParser()
    )

    agent_executor = AgentExecutor(
        agent=agent,
        tools=tools,
        verbose=True,
        memory=memory,
        max_execution_time=60,
        handle_parsing_errors=True,
    )

    with get_openai_callback() as cb:
        clara_ai_resp = await agent_executor.ainvoke({"input": input})
        clara_ai_output = clara_ai_resp["output"]

        print("CB: ", cb)

        return clara_ai_output, input, cb
```

**Comment by eyurtsev** [comment]
The issue is:

1) Agent executor always executes models in streaming mode to support token by token streaming
2) OpenAI does not return token counts in streaming responses
3) get_openai_callback is not able to calculate token counts when streaming

**Comment by eyurtsev** [comment]
Introduced by this PR: https://github.com/langchain-ai/langchain/pull/15792

**Comment by EduardoMM17** [comment]
@eyurtsev 
Hey! Thank you for your answer. So is this a bug? Or was it a bug before? Because it used to work perfectly in previous openai versions

**Comment by eyurtsev** [comment]
It's a bug that I accidentally introduced while changing how agent executor works to make it easy to stream token by token output from the agent (e.g., https://python.langchain.com/docs/modules/agents/how_to/streaming#custom-streaming-with-events)  -- didn't occur to me that callbacks would be affected :(

I made the agent executor always invoke the open ai model in a streaming mode, so folks can get token by token streaming output from the agent, but because the OpenAI API never returns token counts when the model streams it breaks token counting callbacks.

Likely the best solution is to extend the existing openai callback to calculate tokens with tiktoken when the response from the open ai is missing token counts (as is the case when streaming). This will resolve both this issue as well as issues that folks face when streaming content from the openai api directly.

We just need to verify that the token counts are accurate and figure out mapping between tokenizer and specific models in OpenAI. 

I'll try to pick up work on this soon. For folks looking for a solution, the custom callback that you shared is a good workaround, since that's what the extension to the existing openai callbacks will do.

**Comment by EduardoMM17** [comment]
@eyurtsev 
Thanks for your answer. I did something similar to what you are saying here. And I also verified that the token count is correct using LangSmith (it almost is). I hope my solution can help you come up with a better one on how to fix this!

Thanks for your answer man :)

> @danieleratti
> 
> I managed to make a workaround using tiktoken inside the CustomAsyncHandler class. Then you can just use a function like get_openai_cost_for_model in line 2 to calculate the costs.
> 
> I have also verified that the token count is the same or similar to what I get from Langsmith and to my surprise it is. In the input tokens I see a difference of ~10, which is not that much and in the completion I get a difference of ~1 or no difference. So I will be using this in the meantime until I come up with a more elegant solution or someone fixes the bug. Check the code below:
> 
> ```python
> from langchain.callbacks.base import AsyncCallbackHandler
> from langchain_community.callbacks.openai_info import get_openai_token_cost_for_model
> 
> from app.services.llm.prompt import prompt_raw
> from app.services.llm.tools.build_tools import tools
> from app.classes.CustomBuffer import CustomConversationBufferMemory
> 
> memory = CustomConversationBufferMemory(memory_key="chat_history", return_messages=True)
> 
> # use get_openai_token_cost_for_model to calculate cost
> class MyCustomAsyncHandler(AsyncCallbackHandler):
>     async def on_llm_start(
>         self,
>         serialized: dict[str, Any],
>         prompts: list[str],
>         **kwargs: Any,
>     ) -> None:
>         encoding = tiktoken.get_encoding("cl100k_base")
>         prompts_string = ''.join(prompts)
>         num_tokens = len(encoding.encode(prompts_string))
>         print("NUM TOKENS: ", num_tokens)
> 
> 
>     async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
>         """Run when chain ends running."""
>         text_response = response.generations[0][0].text
>         encoding = tiktoken.get_encoding("cl100k_base")
>         response_string = len(encoding.encode(text_response))
>         print("NUM TOKENS RESPONSE: ", response_string)
> 
> async def ask_assistant(input: str) -> str:
>     prompt = PromptTemplate.from_template(prompt_raw)
> 
>     prompt = prompt.partial(
>         language="Spanish",
>         tools=render_text_description(tools),
>         tool_names=", ".join([t.name for t in tools]),
>     )
> 
>     llm = ChatOpenAI(
>         temperature=0,
>         model_name="gpt-4",
>         openai_api_key=os.environ["OPENAI_API_KEY"],
>         callbacks=[MyCustomAsyncHandler()],
>     )
>     llm_with_stop = llm.bind(stop=["\nObservation"])
> 
>     agent = (
>         {
>             "input": lambda x: x["input"],
>             "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
>             "chat_history": lambda x: x["chat_history"],
>         }
>         | prompt
>         | llm_with_stop
>         | ReActSingleInputOutputParser()
>     )
> 
>     agent_executor = AgentExecutor(
>         agent=agent,
>         tools=tools,
>         verbose=True,
>         memory=memory,
>         max_execution_time=60,
>         handle_parsing_errors=True,
>     )
> 
>     with get_openai_callback() as cb:
>         clara_ai_resp = await agent_executor.ainvoke({"input": input})
>         clara_ai_output = clara_ai_resp["output"]
> 
>         print("CB: ", cb)
> 
>         return clara_ai_output, input, cb
> ```

**Comment by danieleratti** [comment]
Thank you both @eyurtsev and @EduardoMM17 for the clarification and for the workaround proposed :)

**Comment by EngJean** [comment]
Having the same issue, thanks for reporting!

**Comment by pruthviraj90** [comment]
@hwchase17 any update?

**Comment by eyurtsev** [comment]
Any help on this issue will be appreciated. Getting the exact token counts isn't super trivial and will help power the streaming mode as well.

One work-around is to force the model to be invoked in a non streaming mode which will give you token counts from the OpenAI api:

```python

def invoke_model(prompt, callbacks):
    return llm_with_stop.invoke(prompt, {"callbacks": callbacks})


    agent = (
        {
            "input": lambda x: x["input"],
            "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
            "chat_history": lambda x: x["chat_history"],
        }
        | prompt
        | invoke_model
        | ReActSingleInputOutputParser()
    )
```

**Comment by mlamina** [comment]
I ran into the same problem and built a context manager that works much in the same way as the original, it just needs the model name as input:


```python
import threading
from contextlib import contextmanager
from typing import Any, Generator

import tiktoken
from langchain_community.callbacks.manager import openai_callback_var
from langchain_community.callbacks.openai_info import standardize_model_name, MODEL_COST_PER_1K_TOKENS, \
    get_openai_token_cost_for_model, OpenAICallbackHandler
from langchain_core.outputs import LLMResult


class CostTrackerCallback(OpenAICallbackHandler):

    def __init__(self, model_name: str) -> None:
        super().__init__()
        self.model_name = model_name
        self._lock = threading.Lock()

    def on_llm_start(
        self,
        serialized: dict[str, Any],
        prompts: list[str],
        **kwargs: Any,
    ) -> None:
        encoding = tiktoken.get_encoding("cl100k_base")
        prompts_string = ''.join(prompts)
        self.prompt_tokens = len(encoding.encode(prompts_string))

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Run when chain ends running."""
        text_response = response.generations[0][0].text
        encoding = tiktoken.get_encoding("cl100k_base")
        self.completion_tokens = len(encoding.encode(text_response))
        model_name = standardize_model_name(self.model_name)
        if model_name in MODEL_COST_PER_1K_TOKENS:
            completion_cost = get_openai_token_cost_for_model(
                model_name, self.completion_tokens, is_completion=True
            )
            prompt_cost = get_openai_token_cost_for_model(model_name, self.prompt_tokens)
        else:
            completion_cost = 0
            prompt_cost = 0

        # update shared state behind lock
        with self._lock:
            self.total_cost += prompt_cost + completion_cost
            self.total_tokens = self.prompt_tokens + self.completion_tokens
            self.successful_requests += 1


@contextmanager
def get_cost_tracker_callback(model_name) -> Generator[CostTrackerCallback, None, None]:
    cb = CostTrackerCallback(model_name)
    openai_callback_var.set(cb)
    yield cb
    openai_callback_var.set(None)

```

**Comment by rmanente** [comment]
Hi guys!

When using this workaround: 
```
    async def on_llm_start(
        self,
        serialized: dict[str, Any],
        prompts: list[str],
        **kwargs: Any,
    ) -> None:
        encoding = tiktoken.get_encoding("cl100k_base")
        prompts_string = ''.join(prompts)
        num_tokens = len(encoding.encode(prompts_string))
        print("NUM TOKENS: ", num_tokens)
```

The tokens used for the functions provided are not considered, right? Is there any way to get the full prompt being sent to the LLM? That is, including the part regarding the functions.

**Comment by jiangjun0105** [comment]
Thanks you @mlamina for your solution. I updated it a little bit so that the callback accumulate the tokens when being passed to multiple chains.

```python

class CostTrackerCallback(OpenAICallbackHandler):
    """Callback handler to track the cost of the model."""

    def __init__(self) -> None:
        super().__init__()
        self.model_name = None
        # NOTE: Using this way to calculate the token is just a rough estimate,
        # as the functions sent to the API is not counted. We have to wait for Langchain to fix it.
        self.encoding = tiktoken.get_encoding("cl100k_base")
        self._lock = threading.Lock()

    def on_llm_start(
        self,
        serialized: dict[str, Any],
        prompts: list[str],
        **kwargs: Any,
    ) -> None:
        """Calculates the prompt token number and cost."""
        prompts_string = ''.join(prompts)
        prompt_tokens = len(self.encoding.encode(prompts_string))
        model_name = serialized.get("kwargs", dict).get("model", "")
        self.model_name = standardize_model_name(model_name)
        if self.model_name in MODEL_COST_PER_1K_TOKENS:
            prompt_cost = get_openai_token_cost_for_model(self.model_name, prompt_tokens)
        else:
            # TODO: Pass a logger
            print(f"Model name {self.model_name} not found. Cannot calculate cost.")
            prompt_cost = 0

        with self._lock:
            self.prompt_tokens += prompt_tokens
            self.total_tokens += prompt_tokens
            self.total_cost += prompt_cost


    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        """Calculates the completion token number and cost."""
        text_response = response.generations[0][0].text
        completion_tokens = len(self.encoding.encode(text_response))
        if self.model_name in MODEL_COST_PER_1K_TOKENS:
            completion_cost = get_openai_token_cost_for_model(
                self.model_name, completion_tokens, is_completion=True
            )
        else:
            # TODO: Pass a logger
            print(f"Model {self.model_name} not found in cost per 1k tokens.")
            completion_cost = 0

        # update shared state behind lock in case async runs.
        with self._lock:
            self.total_cost += completion_cost
            self.total_tokens += completion_tokens
            self.completion_tokens += completion_tokens
            self.successful_requests += 1


@contextmanager
def get_cost_tracker_callback() -> Generator[CostTrackerCallback, None, None]:
    cb = CostTrackerCallback()
    openai_callback_var.set(cb)
    yield cb
    openai_callback_var.set(None)

```

**Comment by mlamina** [comment]
Thanks for that addition @jiangjun0105 ! I wasn't sure how to make it work with multiple chains. This is great

**Comment by salmanmashayekh** [comment]
> Any help on this issue will be appreciated. Getting the exact token counts isn't super trivial and will help power the streaming mode as well.
> 
> One work-around is to force the model to be invoked in a non streaming mode which will give you token counts from the OpenAI api:
> 
> ```python
> def invoke_model(prompt, callbacks):
>     return llm_with_stop.invoke(prompt, {"callbacks": callbacks})
> 
> 
>     agent = (
>         {
>             "input": lambda x: x["input"],
>             "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
>             "chat_history": lambda x: x["chat_history"],
>         }
>         | prompt
>         | invoke_model
>         | ReActSingleInputOutputParser()
>     )
> ```

In your workaround above @eyurtsev , where does the `callbacks` in `invoke_model ` come from? As @joselo85 pointed out, we get the `invoke_model() missing 1 required positional argument: 'callbacks'` error.

**Comment by eyurtsev** [comment]
Oh apologies had a typo the way to do this is this. Thanks for pinging again! it's using `config` rather than `callbacks` (the callbacks are inside the config)


```python
def invoke_model(prompt, config):
    return llm_with_stop.invoke(prompt, config)


    agent = (
        {
            "input": lambda x: x["input"],
            "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
            "chat_history": lambda x: x["chat_history"],
        }
        | prompt
        | invoke_model
        | ReActSingleInputOutputParser()
    )
```

play around with this to understand how it works. Despite the chain being in .stream() mode we're forcing the model to use .invoke() and propagating all the callbacks properly

```python
from langchain_openai.chat_models import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
model = ChatOpenAI()
def force_invoke(input, config):
    print('invoking model rather than streaming it!')
    return model.invoke(input, config)

prompt = ChatPromptTemplate.from_messages([('system', 'hello'), ('human', '{input}')])

chain = prompt | force_invoke

for chunk in chain.stream({'input': 'hello'}):
    print(chunk)
```

**Comment by eyurtsev** [comment]
The workaround ^ Above should work for most users. This PR https://github.com/langchain-ai/langchain/pull/18761 will also provide a solution by requiring that the agent executor run the agent in a non streaming fashion (which will allow token counts to appear).

**Comment by Nando-Mentu** [comment]
Thank you, @eyurtsev! That is great news!
I see the PR has been approved, but not sure the fix has been deployed. I tested calling my executor as the PR example, but still got 0 tokens. It does not throw an error, but no token count either.
Has the fix been made available? Am I missing something or messing up by using `ainvoke`?
```
agent_executor = AgentExecutor(agent=agent, tools=tools, stream_runnable=False)
costs = []
with get_openai_callback() as cb:
    result = await agent_executor.ainvoke({"input": user_prompt})
    costs.append(cb)

print(costs)
```
<img width="327" alt="image" src="https://github.com/langchain-ai/langchain/assets/151956090/9026b02f-09cb-46c2-a451-57d4f9f5dc47">

**Comment by axtsoi** [comment]
@eyurtsev The current workaround doesn't work for create_sql_agent which is a toolkit type. Can you please provide a fix for this as well? I agreed with most users - token counting is one of the fundamental and crucial features by LangChain but this doesn't seem to be treated as a high priority. @hwchase17 Thanks. Please help the community.

**Comment by matisidler** [comment]
For future travelers, this worked for me:
`agent_executor.agent.stream_runnable = False`

I checked the `cb.total_tokens` value with OpenAI's activity page and it's working fine.

**Comment by Sukitly** [comment]
Thanks! @matisidler
This achieves the same functionality:
```python
AgentExecutor(agent=agent, tools=tools, stream_runnable=False)
```

**Comment by EduardoMM17** [comment]
Thanks @matisidler and @Sukitly!! You guys got it done :)

**Comment by EliiseS** [comment]
Do you have a solution for counting token with a streaming chat model? What I have so far, but I'm not sure if that's account for everything sent to the model: 

```python
class TokenSummary:
    def __init__(self, total_tokens=0, prompt_tokens=0, completion_tokens=0):
        self.total_tokens = total_tokens
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens

    def __str__(self):
        return (
            f"Tokens Used: {self.total_tokens}\n"
            f"\tPrompt Tokens: {self.prompt_tokens}\n"
            f"\tCompletion Tokens: {self.completion_tokens}\n"
        )

    def add_prompt_tokens(self, prompt_tokens):
        self.prompt_tokens += prompt_tokens
        self.total_tokens += prompt_tokens

    def add_completion_tokens(self, completion_tokens):
        self.completion_tokens += completion_tokens
        self.total_tokens += completion_tokens


class TokenCalcCallbackHandler(AsyncCallbackHandler):
    def __init__(self, llm_chain_name: str, model_name: str, token_summary: TokenSummary, *args, **kwargs):
        self.encoding = tiktoken.encoding_for_model(model_name)
        self._logger: Logger = getLogger(__name__)
        self.token_summary = token_summary
        self.llm_chain_name = llm_chain_name
        self.current_span = trace.get_current_span()
        self.current_span.set_attribute("llm.chain.name", self.llm_chain_name)

        super().__init__(*args, **kwargs)

    async def on_llm_start(self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any) -> None:
        for prompt in prompts:
            self.token_summary.add_prompt_tokens(len(self.encoding.encode(prompt)))

    async def on_chat_model_start(
        self,
        serialized: Dict[str, Any],
        messages: List[List[BaseMessage]],
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        tags: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> None:
        for message_list in messages:
            for message in message_list:
                self.token_summary.add_prompt_tokens(len(self.encoding.encode(str(message.content))))
        self._logger.info(f"{self.llm_chain_name} prompt tokens: {self.token_summary.prompt_tokens}")
        self.current_span.set_attribute("openai.usage.prompt_tokens", self.token_summary.prompt_tokens)

    async def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        for generation_list in response.generations:
            for generation in generation_list:
                self.token_summary.add_completion_tokens(len(self.encoding.encode(generation.text)))


        self._logger.info(f"{self.llm_chain_name} completion tokens: {self.token_summary.completion_tokens}")
        self._logger.info(f"{self.llm_chain_name} total tokens: {self.token_summary.total_tokens}")

        self.current_span.set_attribute("openai.usage.completion_tokens", self.token_summary.completion_tokens)
        self.current_span.set_attribute("openai.usage.total_tokens", self.token_summary.total_tokens)
```

---

Unrelated to what I wrote above, but this issue I opened seems to be related to this whole thread too: [RunnableMultiActionAgent enable streaming by default even if disabled in the LLM · Issue #20782 · langchain-ai/langchain](https://github.com/langchain-ai/langchain/issues/20782)

**Comment by UsamaSaddiqu** [comment]
@EduardoMM17 I saw your code to count tokens using tiktoken. I also want to calculate cost associated with these. Can you help me with this?

**Comment by CrasCris** [comment]
@matisidler  For pandas_dataframe_agent dont work  :c

**Comment by EduardoMM17** [comment]
> @EduardoMM17 I saw your code to count tokens using tiktoken. I also want to calculate cost associated with these. Can you help me with this?

Hey! I am moving all our agent creation to the new way using Langgraph and there counting tokens works ok. I think its better if we keep up to date on the latest docs

**Comment by matisidler** [comment]
> @matisidler For pandas_dataframe_agent dont work :c

I tried this:
```
with get_openai_callback() as cb:
    agent = create_pandas_dataframe_agent(
        OpenAI(temperature=0),
        df=data,
        verbose=True,
    )
    agent.agent.stream_runnable = False
    agent.invoke(
        "Dame toda la información que tengas sobre cuál es el alimento hipoalergénico más barato?"
    )

    print(f"Total Tokens: {cb.total_tokens}")
    print(f"Prompt Tokens: {cb.prompt_tokens}")
    print(f"Completion Tokens: {cb.completion_tokens}")
    print(f"Total Cost (USD): ${cb.total_cost}")
```

and worked :D

**Comment by CrasCris** [comment]
> > @matisidler For pandas_dataframe_agent dont work :c
> 
> I tried this:
> 
> ```
> with get_openai_callback() as cb:
>     agent = create_pandas_dataframe_agent(
>         OpenAI(temperature=0),
>         df=data,
>         verbose=True,
>     )
>     agent.agent.stream_runnable = False
>     agent.invoke(
>         "Dame toda la información que tengas sobre cuál es el alimento hipoalergénico más barato?"
>     )
> 
>     print(f"Total Tokens: {cb.total_tokens}")
>     print(f"Prompt Tokens: {cb.prompt_tokens}")
>     print(f"Completion Tokens: {cb.completion_tokens}")
>     print(f"Total Cost (USD): ${cb.total_cost}")
> ```
> 
> and worked :D

THANKS Work for me

**Comment by dopc** [comment]
A note for the folks using custom cost handler. Note that, `on_llm_start` works even if the LLM fails, such as a token limit error. So you calculate a false cost even if the LLM fails.

**Comment by ImadSaddik** [comment]
Hi everyone,

I created an agent with LangGraph, here is how it looks like

![agent](https://github.com/user-attachments/assets/6d3993d6-e281-4bf7-9505-34f8f5821b52)

I am using the `astream_events` method to have full control of the data that I want to send back

```python
with get_openai_callback() as cb:
    ...
    messages = _get_messages(payload=payload)
    async for event in react_graph.astream_events(
        {"messages": messages},
        version="v1",
        config={"model_deployment": model_deployment},
    ):
        kind = event["event"]
        if kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                # Empty content in the context of OpenAI means
                # that the model is asking for a tool to be invoked.
                # So we only print non-empty content
                yield content
    
    print(cb)
```

In this case, `get_openai_callback` does not seem to count the number of tokens used. It always returns 0, but when I replace the `astream_events` with just `astream`, this time the callback counts the number of tokens correctly.

```bash
Tokens Used: 0
	Prompt Tokens: 0
	Completion Tokens: 0
Successful Requests: 0
Total Cost (USD): $0.0
```

I did not see anyone mention the problem with `astream_events` but I would love to see if there is any fix.

Thanks,

**Comment by lehic** [comment]
I'm facing the same issue: `get_openai_callback` is not functioning with Agent Executor. Here's my code:

```
with get_openai_callback() as cb:
    result = agent_executor.invoke({
        "account_id": account_id,
        "listing_id": listing_id,
        "guestname": params['guestname'],
        "reservation": params['reservation'],
        "data_rag": params['data_rag'],
        "instructions": params['instructions'],
    })
    print(cb)
```

The output I'm receiving is:

```
Tokens Used: 0
Prompt Tokens: 0
Completion Tokens: 0
Successful Requests: 0
Total Cost (USD): $0.0
```

I'm using `langchain-community` version 0.3.3. Any assistance would be appreciated.

**Comment by ImadSaddik** [comment]
Finally, I found the solution thanks to OpenAI's post, check it out [here](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options). @lehic go to any chat model like `AzureChatOpenAI` or `ChatOpenAI` and add this argument `stream_options={"include_usage": True}`.

In my case, I have a graph that I created with `LangGraph`, and I am using an `AzureChatOpenAI` model inside a node in the graph. I went to that node and added the argument, and thankfully it worked.

```python
chat_llm = AzureChatOpenAI(
    api_key=config.AZURE_OPENAI_API_KEY,
    azure_endpoint=config.AZURE_OPENAI_ENDPOINT,
    openai_api_version=config.OPENAI_API_VERSION,
    deployment_name=config.AZURE_GPT_4O_DEPLOYMENT_ID,
    temperature=0,
    max_retries=0,
    max_tokens=config.MAX_TOKENS_RESPONSE,
    callbacks=[token_count,],
    stream_options={"include_usage": True}
)
```

**Comment by kaaviya98** [comment]
@matisidler  Works🎊🎊🎊🎊
