### ISSUE TITLE
When I use ConversationalRetrievalChain.from_llm to implement a knowledge base with context, the resulting stream will carry questions, so how can I remove the questions?

### ISSUE THREAD

**Issue by whm233** [langchain-ai/langchain#16819]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

llm = ChatOpenAI(
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()],
    temperature=0,
    openai_api_key="xxx",
	openai_api_base="http://0.0.0.0:8000/v1/" ,)

qa_chain = ConversationalRetrievalChain.from_llm(
        llm= llm,
        retriever= compression_retriever,
        chain_type='stuff',
        combine_docs_chain_kwargs = chain_type_kwargs
    )
    a = qa_chain(
        {
            "question": question,
            "chat_history": chat_history,
            "output_key": 'answer',
        },
    )

### Error Message and Stack Trace (if applicable)

.

### Description

When I type in a question, it always repeats the question in the answer  like this :
question :'电子票据查验平台如何获取票据明细？'
answer:'电子票据查验平台如何获取票据明细？ 电子票据查验平台只能查验票据信息，没有票据明细，如需票据明细，请联系开票单位。'

### System Info

.0

**Comment by whm233** [comment]
> `rephrase_question``False``ConversationalRetrievalChain`

it not use

**Comment by woojuini** [comment]
I'm suffering from the same problem.
rephrase_question=False does not work.
'''
qa_chain = ConversationalRetrievalChain.from_llm(
                    llm=llm,
                    verbose=True,
                     ...
                    combine_docs_chain_kwargs={
                        "prompt": PROMPT
                        },
                    return_source_documents=True,
                    rephrase_question=False
                )
'''

**Comment by whm233** [comment]
> I'm suffering from the same problem. rephrase_question=False does not work.
> 
> ```
> qa_chain = ConversationalRetrievalChain.from_llm(
>                     llm=llm,
>                     verbose=True,
>                      ...
>                     combine_docs_chain_kwargs={
>                         "prompt": PROMPT
>                         },
>                     return_source_documents=True,
>                     rephrase_question=False
>                 )
> ```
> 
> `

you can do like this 
llm = ChatOpenAI(
    streaming=True,
    callbacks=[StreamingStdOutCallbackHandler()],
    temperature=0,
    openai_api_key="xxx",
    openai_api_base="http://0.0.0.0:8000/v1/", )
llm1 = ChatOpenAI(
    temperature=0,
    openai_api_key="xxx",
    openai_api_base="http://0.0.0.0:8000/v1/", )

question_generator = LLMChain(llm=llm1, prompt=CUSTOM_QUESTION_PROMPT)

doc_chain = load_qa_chain(llm, chain_type="stuff", prompt=QA_PROMPT)
qa_chain = ConversationalRetrievalChain(
    retriever=compression_retriever, combine_docs_chain=doc_chain, question_generator=question_generator)
You need to separate the chains for streaming output from those for non-streaming output, and then combine them together

**Comment by xxonyuk** [comment]
me too, still same problem occurs.
anyone reslove this problem?
