### ISSUE TITLE
HugginFaceHub LLM has a wrong parameters name

### ISSUE THREAD

**Issue by PavloFesenko** [langchain-ai/langchain#16849]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

``` python
import os
import requests
from langchain.llms import HuggingFaceHub
from langchain.chains import LLMChain

os.environ['HUGGINGFACEHUB_API_TOKEN'] = "your_token"
prompt = "The answer to universe is "

repo_id = "mistralai/Mistral-7B-v0.1"
llm = HuggingFaceHub(
    repo_id=repo_id,
    model_kwargs={
        "max_new_tokens": 10
    }
)
langchain_response = llm.invoke(prompt)

url = f"https://api-inference.huggingface.co/models/{repo_id}"
headers = {"Authorization": f"Bearer {os.environ['HUGGINGFACEHUB_API_TOKEN']}"}
def query(payload):
    response = requests.post(url, headers=headers, json=payload)
    return response.json()
huggingfacehub_response = query({
    "inputs": prompt,
    "parameters": {
        "max_new_tokens": 10
    }
})

print([{"generated_text": langchain_response}])
print(huggingfacehub_response)
```

### Error Message and Stack Trace (if applicable)

```
[{'generated_text': 'The answer to universe is 42.\n\nThe answer to life is 42.\n\nThe answer to everything is 42.\n\nThe answer to the question of why is 42.\n\nThe answer to the question of what is 42.\n\nThe answer to the question of how is 42.\n\nThe answer to the question of who is 42.\n\nThe answer to the question of when is 42.\n\nThe answer to'}]
[{'generated_text': 'The answer to universe is 42.\n\nThe answer to life is'}]
```

### Description

It looks like the `HuggingFaceHub` LLM sends `model_kwargs` with a wrong parameters name in the JSON payload. The correct name should be `parameters` instead of `params` according to the [HuggingFace API documentation](https://huggingface.co/docs/api-inference/en/detailed_parameters#text-generation-task).

https://github.com/langchain-ai/langchain/blob/2e5949b6f8bc340a992b9f9f9fb4751f87979e15/libs/community/langchain_community/llms/huggingface_hub.py#L133

As a result, `model_kwargs` has no effect on the model output as can be seen in the example above.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #56~20.04.1-Ubuntu SMP Tue Nov 28 15:43:31 UTC 2023
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.17
> langchain: 0.1.4
> langchain_community: 0.0.16
> langchainplus_sdk: 0.0.20

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by isayahc** [comment]
Working on a project now and dealing with the same bug.
