### ISSUE TITLE
Function calling not working with ConversationChain with Memory

### ISSUE THREAD

**Issue by rupalikaushik21** [langchain-ai/langchain#16917]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

the following code """

from langchain.chains import LLMChain
from langchain.chains import ConversationChain
my_functions = [
    {
        'name': 'raise_ticket',
        'description': 'Get the details for a ticket',
        'parameters': {
            'type': 'object',
            'properties': {
                'projectName':{
                    'type': 'string',
                    'description': "Project Name : (e.g. 'ABC', 'XYZ')"
                },
                'issueType':{
                    'type': 'string',
                    'description': "Issue Type : (e.g. 'Change Request', 'Service Request')"
                },
            },
            ...
            ...
            "required":["projectName","issueType"]
        }    
    }

]

llm = ChatOpenAI(temperature=0.0, model="gpt-3.5-turbo-0613")

memory = ConversationBufferMemory()

conversation = ConversationChain(
    llm=llm, 
    memory = memory,
    verbose=False
)

message= conversation.invoke([HumanMessage(content='What are the choices of the Issue Type')],
                              functions=my_functions,
                             memory=memory)

"""

### Error Message and Stack Trace (if applicable)

Not an error but Function call is not happening. I am always getting a generic response from the model. 

### Description

I was expecting the langchain library to recognize the function... but it is not recognizing it. 

Same function works with OpenAI

### System Info

langchain==0.1.4
langchain-community==0.0.16
langchain-core==0.1.17

**Comment by rupalikaushik21** [comment]
I am still facing issues..

Below is the complete code. I am using to implement openai function calling when leveraging chains

```

llm = ChatOpenAI(temperature=0.0, model="gpt-3.5-turbo-0613",openai_api_key="mykey")

from langchain.chains import LLMChain
from langchain.chains import ConversationChain
from langchain_core.utils.function_calling import convert_to_openai_tool


def misdoFormula(a: int, b: int) -> int:
    """Misdo formula two integers together.

    Args:
        a: First integer
        b: Second integer
    """
    return (a * b) / 3

import json 

print(json.dumps(convert_to_openai_tool(misdoFormula)))
memory = ConversationBufferMemory()

conversation = ConversationChain(
    llm=llm, 
    memory = memory,
    verbose=True
)

from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType


message= conversation.invoke(
    [SystemMessage(content="You are an AI model. Don't Assume information when not provided. Leverage tools passed as input.Ask required input one at a time"), 
     HumanMessage(content="can you help me claculate misdo formula for 10 and 3")],
                              tools=[convert_to_openai_tool(misdoFormula)],
    agent=AgentType.OPENAI_FUNCTIONS,
                             memory=memory)
message
```

**Comment by GIDDY269** [comment]
where you able to solve this issue?
