### ISSUE TITLE
Include attachments=True is not working in Confluence

### ISSUE THREAD

**Issue by deepak-habilelabs** [langchain-ai/langchain#16926]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Below is my code
``` python
def generate_embeddings(config: dict = None, urls = None, file_path = None, persist_directory=None):
    texts=None
    if file_path:
        _, file_extension = os.path.splitext(file_path)
        file_extension = file_extension.lower()
        image_types=['jpeg','jpg','png','gif']
        if file_path.lower().endswith(".pdf"):
            loader = PyPDFLoader(file_path)
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=300)
            texts = text_splitter.split_documents(documents=document)
        elif file_path.lower().endswith(".csv"):
            loader = CSVLoader(file_path, encoding="utf-8", csv_args={'delimiter': ','})
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=300)
            texts = text_splitter.split_documents(documents=document)
        elif file_path.lower().endswith(".xlsx") or file_path.lower().endswith(".xls"):
            loader = UnstructuredExcelLoader(file_path)
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
            texts = text_splitter.split_documents(documents=document)
        elif file_path.lower().endswith(".docx") or file_path.lower().endswith(".doc"):
            loader = UnstructuredWordDocumentLoader(file_path)
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=0)
            texts = text_splitter.split_documents(documents=document)
        elif any(file_path.lower().endswith(f".{img_type}") for img_type in image_types):
            loader=UnstructuredImageLoader(file_path)
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
            texts = text_splitter.split_documents(documents=document)
        elif file_path.lower().endswith(".txt"):
            loader=TextLoader(file_path)
            document = loader.load()
            text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
            texts = text_splitter.split_documents(documents=document)
            
    elif config is not None:
        confluence_url = config.get("confluence_url", None)
        username = config.get("username", None)
        api_key = config.get("api_key", None)
        space_key = config.get("space_key", None)
        documents = []

        embedding = OpenAIEmbeddings()
        loader = ConfluenceLoader(
            url=confluence_url,
            username=username,
            api_key=api_key
        )
        for space_key in space_key:
            try:
                if space_key[1] is True:
                    print('add attachment')
                    documents.extend(loader.load(space_key=space_key[0],include_attachments=True,limit=100))
                    text_splitter = CharacterTextSplitter(chunk_size=6000, chunk_overlap=50)
                    texts = text_splitter.split_documents(documents)
                    text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=10, encoding_name="cl100k_base")
                    texts = text_splitter.split_documents(texts)
                else:
                    print("without attachment")
                    documents.extend(loader.load(space_key=space_key[0],limit=100))
                    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=50)
                    texts = text_splitter.split_documents(documents)
                    text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=10, encoding_name="cl100k_base")
                    texts = text_splitter.split_documents(texts)
                        
            except:
                documents=[]
    elif urls:
        all_urls=[]
        for url in urls:           
          if url[1] is True:                
            crawl_data=crawl(url[0])
            all_urls.extend(crawl_data)
          if url[1] is False:  
            dummy = []
            dummy.append(url[0])   
            all_urls.extend(dummy)
        loader = UnstructuredURLLoader(urls=all_urls)
        urlDocument = loader.load()
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=50)
        texts = text_splitter.split_documents(documents=urlDocument)
    else:
        raise ValueError("Invalid source_type. Supported values are 'pdf', 'confluence', and 'url'.")

    if texts:
        embedding = OpenAIEmbeddings()
        Chroma.from_documents(documents=texts, embedding=embedding, persist_directory=persist_directory)
        file_crawl_status = True
        file_index_status = True
    else:
        file_crawl_status = False
        file_index_status = False

    return file_crawl_status, file_index_status



def retreival_qa_chain(chroma_db_path):
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    llm = ChatOpenAI(model="gpt-3.5-turbo-16k",temperature=0.1)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever,return_source_documents=True)
    return qa
    ```

### Error Message and Stack Trace (if applicable)

[02/Feb/2024 11:54:15] "GET /create-project/ HTTP/1.1" 200 19747
Bad Request: /create-project/
[02/Feb/2024 11:56:43] "POST /create-project/ HTTP/1.1" 400 45

### Description

# Confluence Project Issue

## Problem Description

I am working on a Confluence project where I have implemented an "include attachments=True" feature. The functionality works fine locally, and the code is deployed on two servers. However, on one of the servers, I am encountering a "Bad request" error. Despite having all the necessary dependencies installed, the issue persists.

## Dependency Information

Here are the dependencies installed on all servers:

- Django 4.0
- Django Rest Framework
- Langchain 0.1.1
- Markdownify
- Pillow
- Docx2txt
- Xlrd
- Pandas
- Reportlab
- Svglib
- Pdf2image
- Chromadb
- Unstructured
- OpenAI
- Pypdf
- Tiktoken
- Django-cors-headers
- Django-environ
- Pytesseract 0.3.10
- Beautifulsoup4 4.12.2
- Atlassian-python-api 3.41.9
- Lxml
- Langchain-community
- Langchain-openai
- Python-docx
- Unstructured-inference
- Unstructured[all-docs]
- Pydantic
- Langchainhub

## Additional Information

- The issue occurs specifically on one server.
- The "include attachments" feature is working fine on the local environment and another server.
- All dependencies are installed on the problematic server.
- The server where the issue occurs has Django 4.0 installed.

## Steps Taken

- Checked server logs for any specific error messages.
- Verified that all necessary dependencies are installed on the problematic server.
- Ensured that the codebase is the same across all servers.

## Error Message

On the problematic server, I am receiving a "Bad request" error.

## Request for Assistance

I would appreciate any guidance or suggestions on how to troubleshoot and resolve this issue. If anyone has encountered a similar problem or has insights into Confluence projects and attachment inclusion, your assistance would be invaluable.

Thank you!

### System Info

below is my server configuration
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
  
                 total        used        free      shared  buff/cache   available
Mem:           7.7Gi       5.4Gi       238Mi        20Mi       2.1Gi       2.1Gi
Swap:          8.0Gi       2.1Gi       5.9Gi

**Comment by RobertSelvam** [comment]
ModuleNotFoundError: No module named 'rlPyCairo'

During handling of the above exception, another exception occurred:

ModuleNotFoundError: No module named '_rl_renderPM'

During handling of the above exception, another exception occurred:

RenderPMError: cannot import desired renderPM backend rlPyCairo
Seek advice at the users list see
https://pairlist2.pair.net/mailman/listinfo/reportlab-users

i used this  `include_attachments=True` , then i got this error. I have install all required dependencies.

**Comment by Innsai** [comment]
@RobertSelvam I had this issue when trying to use renderPM from reportlab.graphics and try to write to memory (BytesIO) a Drawing generated by svglib through its svg2rlg from svglib.svglib and solve it by just installing the package first mentioned (rlPyCairo) with pip:

Example code:

from svglib.svglib
import svg2rlg
drawing = svg2rlg(path_logo)
if drawing:
    from io import BytesIO
    img_stream = BytesIO()
    from reportlab.graphics import renderPM
    renderPM.drawToFile(drawing, img_stream, 'PNG') <-- The same error you had occurs here

Just run: pip install prPyCairo

I hope this helps.
