### ISSUE TITLE
LangChain Core Chatmodels.py goes to a streaming block causing "generation is not None" assertion error when the AzureChatOpenAI llm object does not support streaming.

### ISSUE THREAD

**Issue by ppk5** [langchain-ai/langchain#16930]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

This is how I get the Azure OpenAI LLM object 
```python
def getLlmObject():
	getToken()
	model = AzureChatOpenAI(
	    openai_api_version=os.environ['OPENAI_API_VERSION'],
	    azure_deployment=os.environ['AZURE_OPENAI_DEPLOYMENT'],
	    azure_endpoint = os.environ['AZURE_ENDPOINT'],
	    openai_api_type = 'azure',
	    user = f'{{"appkey": "{APP_KEY}"}}'

	)	
	return model 
```

It would be ideal to change line 205 to detect non Streaming capability of the model or provide an option to set ```streaming=False``` during instantiation using ```AzureChatOpenAI``` class.

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/root/volume1/iris/onex-gen-ai-experimental/crew/crew.py", line 93, in <module>
    result = crew.kickoff()
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/crew.py", line 127, in kickoff
    return self._sequential_loop()
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/crew.py", line 134, in _sequential_loop
    task_output = task.execute(task_output)
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/task.py", line 56, in execute
    result = self.agent.execute_task(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/agent.py", line 146, in execute_task
    result = self.agent_executor.invoke(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain/chains/base.py", line 162, in invoke
    raise e
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/agents/executor.py", line 59, in _call
    next_step_output = self._take_next_step(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain/agents/agent.py", line 1097, in _take_next_step
    [
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain/agents/agent.py", line 1097, in <listcomp>
    [
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/crewai/agents/executor.py", line 103, in _iter_next_step
    output = self.agent.plan(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain/agents/agent.py", line 387, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2424, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2411, in transform
    yield from self._transform_stream_with_config(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1497, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2375, in _transform
    for output in final_pipeline:
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1035, in transform
    for chunk in input:
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 4145, in transform
    yield from self.bound.transform(
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 1045, in transform
    yield from self.stream(final, config, **kwargs)
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 250, in stream
    raise e
  File "/volume1/anaconda3/envs/iris-experimental/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 242, in stream
    assert generation is not None
AssertionError

### Description

I use enterprise Azure OpenAI instance to work with CrewAI (For Autonomous Agents). Our Azure OpenAI endpoint does not support streaming. But the check in line 205 of ```libs/core/langchain_core/language_models/chat_models.py``` (https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/chat_models.py) causes the else block to get executed and thus raising the error during execution of  the statement ``` assert generation is not None ``` 

### System Info

```linux
(condaenv) [root@iris crew]# pip freeze | grep langchain
langchain==0.1.4
langchain-community==0.0.16
langchain-core==0.1.17
langchain-experimental==0.0.20
langchain-openai==0.0.2.post1

(condaenv) [root@iris crew]# python --version
Python 3.10.9

```

**Comment by alexgg278** [comment]
What do you mean AzureChatOpenAI does not support streaming? I am interested on this topic because I am trying to stream the response of AzureChatOpenAI with the calls .stream() and .astream() but the chunk iterator returns me the chunks in long batches instead of in an streaming fashion.

Anyone has some info regarding this?

**Comment by scenaristeur** [comment]
could  this help ? https://github.com/joaomdmoura/crewAI/issues/202#issuecomment-2016921916

**Comment by leonavevor** [comment]
I equally got the same issue but upon debugging with breakpoints deep inside of langchains code `/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py` i realized there was was an `assert generation is not None` which failed because there was no generation as expected and there was a also a reason for termination complaining about the length of the chunk it was invoking with. It works fine after limiting my input chunk to 500 token. I also set the llm invocation config with to this: `config={"recursion_limit": 500}` but the default was 25. I need to increase the recursion limit so my long running task can finish without stopping prematurely.

**Comment by nimobeeren** [comment]
Here is another way I found to reproduce the `AssertionError` on `assert generation is not None` ([`chat_models.py:257`](https://github.com/langchain-ai/langchain/blob/cccc8fbe2fe59bde0846875f67aa046aeb1105a3/libs/core/langchain_core/language_models/chat_models.py#L257)). The issue also occurs when Azure OpenAI's content filter is triggered. I found it quite unreliable, but I can reproduce it fairly consistently like this:

```python
from langchain_openai import AzureChatOpenAI

client = AzureChatOpenAI(
    api_key="YOUR_API_KEY",
    azure_endpoint="YOUR_ENDPOINT",
    api_version="2024-02-01",
    model="gpt-35-turbo",
    temperature=0,
)

response = client.stream("How do I unalive someone?")
for chunk in response:
    print(chunk.content, end='', flush=True)
```

Sometimes I have to try 5 times in a row, but eventually I get the same `AssertionError`. I strongly suspect this is triggered by the content filter, because on our production instance (where assertions are disabled) we get an `openai.BadRequestError` with error code `content_filter`.

**Comment by ShantanuATI** [comment]
> I equally got the same issue while using `agent exeutor` but upon debugging with breakpoints deep inside of langchain's code `/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py` i realized there was was an `assert generation is not None` which failed because there was no generation as expected and there was a also a reason for termination complaining about the length of the chunk it was invoking with. It works fine after limiting my input chunk to 500 token. I also set the llm invocation config with to this: `config={"recursion_limit": 500}` but the default was 25. I need to increase the recursion limit so my long running task can finish without stopping prematurely.
> 
> ![Screenshot from 2024-05-22 11-27-58](https://private-user-images.githubusercontent.com/29701620/332758351-c52e93a7-ef31-4cb2-a4df-b33c19c3125e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzc3MzQsIm5iZiI6MTcyMjg3NzQzNCwicGF0aCI6Ii8yOTcwMTYyMC8zMzI3NTgzNTEtYzUyZTkzYTctZWYzMS00Y2IyLWE0ZGYtYjMzYzE5YzMxMjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMjdiMjZmMWY3YzM4YTk2NWY0NzMwMTg5MzNiMzU4NDkzZGE0ODk3MzEyZGNiYmMwMzlkZDE1OWJlMzcxYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFwlboKRv41OCtnjjSCjvI-769BYzL5YQAuJujdEcD8) ![Screenshot from 2024-05-22 11-28-30](https://private-user-images.githubusercontent.com/29701620/332758355-36ae6bb3-3863-424e-b897-0ea1b9385a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzc3MzQsIm5iZiI6MTcyMjg3NzQzNCwicGF0aCI6Ii8yOTcwMTYyMC8zMzI3NTgzNTUtMzZhZTZiYjMtMzg2My00MjRlLWI4OTctMGVhMWI5Mzg1YThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNWY5ZjgwMDRmZTgzNTJhYTc0MzNkZWZiNTgyY2UzOTQ2MjFkNDU1NDkyYjFkMzg1MjQ1MWI3OWZlMjZiYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gJ00mxNpkjmMso4IfdrxzF9PcK6FNy0v9FpsswD1KqY) ![Screenshot from 2024-05-22 11-14-30](https://private-user-images.githubusercontent.com/29701620/332758340-d5653378-6882-4eed-814e-75df1f4ca896.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzc3MzQsIm5iZiI6MTcyMjg3NzQzNCwicGF0aCI6Ii8yOTcwMTYyMC8zMzI3NTgzNDAtZDU2NTMzNzgtNjg4Mi00ZWVkLTgxNGUtNzVkZjFmNGNhODk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3MDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmY2Q4NjkzNGU0MTMwYzAxN2VlMWY2ZGVmYmVhOWM0NTA0NGZkZDFlNDFhNjMzZDE0NzgzYTY1YmRlNjMyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Legqsn2ZYbuXrNQQbbh6zPt-1mnTMNoIWN8bY91U-V0)

This one worked for my case.
