### ISSUE TITLE
No local GPU for self hosted embeddings

### ISSUE THREAD

**Issue by DHOFM** [langchain-ai/langchain#1695]
This won't work, because your class needs runhouse. I would like to use it on my GPU Server so ist should not log in via ssh to it's own:

```
embeddings = SelfHostedEmbeddings(
    model_load_fn=get_pipeline, 
    hardware="cuda",
    model_reqs=["./", "torch", "transformers"],
    inference_fn=inference_fn
)
```

So here cuda would not work...

**Comment by htang2012** [comment]
Strongly agree!!! I am asking for the same thing. I would like to use it on my local GPU server directly. Please expedite this request.

**Comment by IMJONEZZ** [comment]
When Harrison Chase was asked about when they'll support truly self-hosted embeddings, he said:
"great Q - we already do! We have specific integrations with gpt4all (https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html), llama cpp (https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html), and generally support writing a custom LLM wrapper (within which you can do anything you please! ) (https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html)
