### ISSUE TITLE
HuggingFaceHub still needs leading characters removal 

### ISSUE THREAD

**Issue by lin-calvin** [langchain-ai/langchain#16972]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_community.llms import HuggingFaceHub
HuggingFaceHub(repo_id="gpt2")("Linux is")
#Exprcted: "a opensource operate system"
#Real: "Linux is a opensource operate system"
```

### Description

Some text-generation models on huggingface repeat the prompt in their generated response

### System Info

langchain==0.1.4
langchain-community==0.0.17
langchain-core==0.1.18
langchain-experimental==0.0.29
langchain-google-genai==0.0.6
langchainhub==0.1.14

**Comment by calvinweb** [comment]
Found the problem, `{"return_full_text":False}` should be added to parameters,
