### ISSUE TITLE
Streaming Agent responses

### ISSUE THREAD

**Issue by yahyaakli** [langchain-ai/langchain#16980]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
from langchain.chat_models import ChatOpenAI
from langchain.tools import Tool
from src.utils.search import SearchUtil
from langchain.agents import AgentExecutor, create_openai_tools_agent, AgentExecutorIterator
from langchain.schema import SystemMessage
from langchain import hub

prompt = hub.pull("hwchase17/openai-tools-agent")
llm = ChatOpenAI()
multiply_tool = Tool(
    name="multiply",
    description="Multiply two numbers",
    func=lambda x, y: x * y,
)
    
tools = [multiply_tool]
agent = create_openai_tools_agent(llm, tools,  prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

async for chunk in agent_executor.astream({'input': 'write a long text'}):
    print(chunk, end="|", flush=True)
```

### Description

I am having an issue with streaming chunks from an instance of an AgentExecutor, Here is a very simple high level example of what I am doing
```
from langchain.chat_models import ChatOpenAI
from langchain.tools import Tool
from src.utils.search import SearchUtil
from langchain.agents import AgentExecutor, create_openai_tools_agent, AgentExecutorIterator
from langchain.schema import SystemMessage
from langchain import hub

prompt = hub.pull("hwchase17/openai-tools-agent")
llm = ChatOpenAI()
multiply_tool = Tool(
    name="multiply",
    description="Multiply two numbers",
    func=lambda x, y: x * y,
)
    
tools = [multiply_tool]
agent = create_openai_tools_agent(llm, tools,  prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

async for chunk in agent_executor.astream({'input': 'write a long text'}):
    print(chunk, end="|", flush=True)

```

When I apply the same chunk loop on a llm or a chain, their implementation of astream seems to be fine. but when I do it on an agent, I get everything back in an object such as:

{'output': 'llm response', intermediate_steps=[],  .. } |

I found some recent discussions with people facing the same issue and it seems to be a bug with the AgentExecutor implementation.

### System Info

langchain==0.1.5
langchain-community==0.0.17
langchain-core==0.1.18
langchain-openai==0.0.5
langchainhub==0.1.14

**Comment by ccurme** [comment]
Hi @yahyaakli, I'm not a maintainer but noticed that the [agents/how_to/streaming](https://python.langchain.com/docs/modules/agents/how_to/streaming#custom-streaming-with-events) documentation says:
> Use the astream_events API in case the default behavior of stream does not work for your application (e.g., if you need to stream individual tokens from the agent or surface steps occuring within tools).

If streaming individual tokens in the final output is what you are after, you could implement something like the following:
```python
async for event in agent_executor.astream_events({"input": input_string}, version="v1"):
    if event["event"] == "on_chat_model_stream":
        chunk = event["data"]["chunk"]
        print(chunk.content, end="")
```
Note that this is a beta API. Not sure if this is a robust or good solution.

**Comment by yahyaakli** [comment]
Hi @ccurme thank you so much for your help, your suggestion worked for me !!

**Comment by eyurtsev** [comment]
Not a bug, but arguably a bad API since it doesn't behave like folks expect it to. The `stream` api of agent executor is designed to stream action/observation pairs, and will *NOT* stream tokens. Use `astream_events` like @ccurme suggested.

**Comment by himalay-aipxperts** [comment]
> Hi @yahyaakli, I'm not a maintainer but noticed that the [agents/how_to/streaming](https://python.langchain.com/docs/modules/agents/how_to/streaming#custom-streaming-with-events) documentation says:
> 
> > Use the astream_events API in case the default behavior of stream does not work for your application (e.g., if you need to stream individual tokens from the agent or surface steps occuring within tools).
> 
> If streaming individual tokens in the final output is what you are after, you could implement something like the following:
> 
> ```python
> async for event in agent_executor.astream_events({"input": input_string}, version="v1"):
>     if event["event"] == "on_chat_model_stream":
>         chunk = event["data"]["chunk"]
>         print(chunk.content, end="")
> ```
> 
> Note that this is a beta API. Not sure if this is a robust or good solution.

thank you this helps a lot

**Comment by SethTurin** [comment]
I burned 3 hours thinking there was something wrong in my code, then not being able to find correct agent streaming code, and then finally I found this thread. This should either be better documented, or it should be properly implemented in a way that is consistent with other streaming functions, or preferably both.
