### ISSUE TITLE
An error occurred while adding a document to the Zilliz vectorstore 

### ISSUE THREAD

**Issue by Aye10032** [langchain-ai/langchain#17006]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python


embedding = HuggingFaceBgeEmbeddings(
    model_name=model,
    model_kwargs={'device': 'cuda'},
    encode_kwargs={'normalize_embeddings': True}
)

connection_args = {
    'uri': milvus_cfg.REMOTE_DATABASE['url'],
    'user': milvus_cfg.REMOTE_DATABASE['username'],
    'password': milvus_cfg.REMOTE_DATABASE['password'],
    'secure': True,
}

vector_db = Milvus(
    embedding,
    collection_name=collection,
    connection_args=connection_args,
    drop_old=True,
    auto_id=True,
)

# I omitted some document split part here
md_docs = r_splitter.split_documents(head_split_docs)

vector_db.add_documents(md_docs)

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "D:\program\python\KnowledgeBot\InitDatabase.py", line 100, in <module>
    load_md(config.MD_PATH)
  File "D:\program\python\KnowledgeBot\utils\TimeUtil.py", line 8, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\program\python\KnowledgeBot\InitDatabase.py", line 82, in load_md
    vector_db.add_documents(md_docs)
  File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_core\vectorstores.py", line 119, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_community\vectorstores\milvus.py", line 586, in add_texts
    insert_list = [insert_dict[x][i:end] for x in self.fields]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_community\vectorstores\milvus.py", line 586, in <listcomp>
    insert_list = [insert_dict[x][i:end] for x in self.fields]
                   ~~~~~~~~~~~^^^
KeyError: 'pk'


### Description

This is how my original code looked like：
```python
vector_db = Milvus(
    embedding,
    collection_name=collection,
    connection_args=connection_args,
    drop_old=True
)
```
It was able to run successfully. 
The version information at that time was:
- python: 3.11
- langchain==0.1.4
- langchain_community==0.0.16
- pymilvus==2.3.5

However, when I updated the version information and tried to run it directly, an error occurred:
_A list of valid ids are required when auto_id is False_
By checking, I found that a new parameter called `auto_id` was added. And after I modified the Milvus setting to the code like this:
```python
vector_db = Milvus(
    embedding,
    collection_name=collection,
    connection_args=connection_args,
    drop_old=True,
    auto_id=True
)
```
the error has changed to the current one.

### System Info

- python: 3.11
- langchain==0.1.5
- langchain_community==0.0.17
- pymilvus==2.3.6

**Comment by 948024326** [comment]
do you fix that problems?
i have the same problem

**Comment by 948024326** [comment]
> ### Checked other resources
> * [x]  I added a very descriptive title to this issue.
> * [x]  I searched the LangChain documentation with the integrated search.
> * [x]  I used the GitHub search to find a similar question and didn't find it.
> * [x]  I am sure that this is a bug in LangChain rather than my code.
> 
> ### Example Code
> ```python
> embedding = HuggingFaceBgeEmbeddings(
>     model_name=model,
>     model_kwargs={'device': 'cuda'},
>     encode_kwargs={'normalize_embeddings': True}
> )
> 
> connection_args = {
>     'uri': milvus_cfg.REMOTE_DATABASE['url'],
>     'user': milvus_cfg.REMOTE_DATABASE['username'],
>     'password': milvus_cfg.REMOTE_DATABASE['password'],
>     'secure': True,
> }
> 
> vector_db = Milvus(
>     embedding,
>     collection_name=collection,
>     connection_args=connection_args,
>     drop_old=True,
>     auto_id=True,
> )
> 
> # I omitted some document split part here
> md_docs = r_splitter.split_documents(head_split_docs)
> 
> vector_db.add_documents(md_docs)
> ```
> 
> ### Error Message and Stack Trace (if applicable)
> Traceback (most recent call last): File "D:\program\python\KnowledgeBot\InitDatabase.py", line 100, in load_md(config.MD_PATH) File "D:\program\python\KnowledgeBot\utils\TimeUtil.py", line 8, in wrapper result = func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "D:\program\python\KnowledgeBot\InitDatabase.py", line 82, in load_md vector_db.add_documents(md_docs) File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_core\vectorstores.py", line 119, in add_documents return self.add_texts(texts, metadatas, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_community\vectorstores\milvus.py", line 586, in add_texts insert_list = [insert_dict[x][i:end] for x in self.fields] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\miniconda3\envs\KnowledgeBot\Lib\site-packages\langchain_community\vectorstores\milvus.py", line 586, in insert_list = [insert_dict[x][i:end] for x in self.fields] ~~~~~~~~~~~^^^ KeyError: 'pk'
> 
> ### Description
> This is how my original code looked like：
> 
> ```python
> vector_db = Milvus(
>     embedding,
>     collection_name=collection,
>     connection_args=connection_args,
>     drop_old=True
> )
> ```
> 
> It was able to run successfully. The version information at that time was:
> 
> * python: 3.11
> * langchain==0.1.4
> * langchain_community==0.0.16
> * pymilvus==2.3.5
> 
> However, when I updated the version information and tried to run it directly, an error occurred: _A list of valid ids are required when auto_id is False_ By checking, I found that a new parameter called `auto_id` was added. And after I modified the Milvus setting to the code like this:
> 
> ```python
> vector_db = Milvus(
>     embedding,
>     collection_name=collection,
>     connection_args=connection_args,
>     drop_old=True,
>     auto_id=True
> )
> ```
> 
> the error has changed to the current one.
> 
> ### System Info
> * python: 3.11
> * langchain==0.1.5
> * langchain_community==0.0.17
> * pymilvus==2.3.6

do you fix that problems?
i have the same problem

**Comment by 948024326** [comment]
ok解决了

**Comment by Aye10032** [comment]
> ok解决了

我现在是降级回原来版本了，你是用什么方法解决的？

**Comment by luguoyixiazi** [comment]
？maybe there is still something not good enough，because I got “langchain_community.vectorstores.milvus.Milvus() got multiple values for keyword argument 'auto_id'” when I set it by using from_doc，

> _🤖_
> 
> Hey @Aye10032, great to see you here again! Hope everything's going well on your side.
> 
> The `KeyError: 'pk'` you're encountering is likely due to the fact that you're not providing a primary key ('pk') when adding documents to the Zilliz vector store, while the `auto_id` parameter is set to False.
> 
> In the LangChain v0.1.5, the `auto_id` parameter was introduced in the `Zilliz` class. This parameter determines whether Milvus should automatically generate unique integers as primary keys. If `auto_id` is set to False, you need to provide text ids (string less than 65535 bytes) as primary keys when adding documents.
> 
> If you don't provide these ids and `auto_id` is set to False, you'll encounter a KeyError: 'pk' because the system is expecting a primary key for each document but isn't finding one.
> 
> To resolve this issue, you can either provide a list of ids when adding documents or set `auto_id` to True to let Milvus generate the ids automatically. Here's how you can do it:
> 
> ```python
> # Providing ids
> vector_db.add_texts(texts=texts, metadatas=metadatas, ids=my_ids)
> 
> # Or setting auto_id to True
> vector_db = Zilliz(
>     embedding_function=embedding,
>     collection_name=collection_name,
>     connection_args=connection_args or {},
>     consistency_level=consistency_level,
>     index_params=index_params,
>     search_params=search_params,
>     drop_old=drop_old,
>     auto_id=True,  # Set auto_id to True
>     **kwargs,
> )
> vector_db.add_texts(texts=texts, metadatas=metadatas)
> ```
> 
> Please replace `my_ids` with your list of ids. Each id should be a string less than 65535 bytes.
> 
> The `auto_id` parameter was introduced in the `Milvus` class in LangChain v0.1.5 as an argument in the class's `__init__` method. It is a boolean value that defaults to `False`.
> 
> ```python
> def __init__(
>     ...
>     auto_id: bool = False,
>     ...
> ):
>     ...
>     self.auto_id = auto_id
>     ...
> ```
> 
> This parameter is used when creating the primary key field in the `_create_collection` method. If `auto_id` is `True`, Milvus will generate unique integers as primary keys. If `False`, the user needs to provide text ids (string less than 65535 bytes).
> 
> ```python
> def _create_collection(
>     ...
> ) -> None:
>     ...
>     # Create the primary key field
>     if self.auto_id:
>         fields.append(
>             FieldSchema(
>                 self._primary_field, DataType.INT64, is_primary=True, auto_id=True
>             )
>         )
>     else:
>         fields.append(
>             FieldSchema(
>                 self._primary_field,
>                 DataType.VARCHAR,
>                 is_primary=True,
>                 auto_id=False,
>                 max_length=65_535,
>             )
>         )
>     ...
> ```
> 
> This change allows users to choose whether they want to manually provide unique identifiers for their data or have Milvus automatically generate them. You can find more details in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py).
> 
> ## Sources
> * [libs/community/langchain_community/vectorstores/zilliz.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/zilliz.py)
> * [libs/community/langchain_community/vectorstores/milvus.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.



> _🤖_
> 
> Hey @Aye10032, great to see you here again! Hope everything's going well on your side.
> 
> The `KeyError: 'pk'` you're encountering is likely due to the fact that you're not providing a primary key ('pk') when adding documents to the Zilliz vector store, while the `auto_id` parameter is set to False.
> 
> In the LangChain v0.1.5, the `auto_id` parameter was introduced in the `Zilliz` class. This parameter determines whether Milvus should automatically generate unique integers as primary keys. If `auto_id` is set to False, you need to provide text ids (string less than 65535 bytes) as primary keys when adding documents.
> 
> If you don't provide these ids and `auto_id` is set to False, you'll encounter a KeyError: 'pk' because the system is expecting a primary key for each document but isn't finding one.
> 
> To resolve this issue, you can either provide a list of ids when adding documents or set `auto_id` to True to let Milvus generate the ids automatically. Here's how you can do it:
> 
> ```python
> # Providing ids
> vector_db.add_texts(texts=texts, metadatas=metadatas, ids=my_ids)
> 
> # Or setting auto_id to True
> vector_db = Zilliz(
>     embedding_function=embedding,
>     collection_name=collection_name,
>     connection_args=connection_args or {},
>     consistency_level=consistency_level,
>     index_params=index_params,
>     search_params=search_params,
>     drop_old=drop_old,
>     auto_id=True,  # Set auto_id to True
>     **kwargs,
> )
> vector_db.add_texts(texts=texts, metadatas=metadatas)
> ```
> 
> Please replace `my_ids` with your list of ids. Each id should be a string less than 65535 bytes.
> 
> The `auto_id` parameter was introduced in the `Milvus` class in LangChain v0.1.5 as an argument in the class's `__init__` method. It is a boolean value that defaults to `False`.
> 
> ```python
> def __init__(
>     ...
>     auto_id: bool = False,
>     ...
> ):
>     ...
>     self.auto_id = auto_id
>     ...
> ```
> 
> This parameter is used when creating the primary key field in the `_create_collection` method. If `auto_id` is `True`, Milvus will generate unique integers as primary keys. If `False`, the user needs to provide text ids (string less than 65535 bytes).
> 
> ```python
> def _create_collection(
>     ...
> ) -> None:
>     ...
>     # Create the primary key field
>     if self.auto_id:
>         fields.append(
>             FieldSchema(
>                 self._primary_field, DataType.INT64, is_primary=True, auto_id=True
>             )
>         )
>     else:
>         fields.append(
>             FieldSchema(
>                 self._primary_field,
>                 DataType.VARCHAR,
>                 is_primary=True,
>                 auto_id=False,
>                 max_length=65_535,
>             )
>         )
>     ...
> ```
> 
> This change allows users to choose whether they want to manually provide unique identifiers for their data or have Milvus automatically generate them. You can find more details in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py).
> 
> ## Sources
> * [libs/community/langchain_community/vectorstores/zilliz.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/zilliz.py)
> * [libs/community/langchain_community/vectorstores/milvus.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

?it doens't work for me, even I set metadatas to pass 
""" if metadatas is not None:
                for d in metadatas:
                    for key, value in d.items():
                        keys = (
                            [x for x in self.fields if x != self._primary_field]
                            if self.auto_id
                            else [x for x in self.fields]
                        )
                        for key in keys:
                            insert_dict.setdefault(key, []).append(value)"""

**Comment by luguoyixiazi** [comment]
> _🤖_
> 
> Hey @Aye10032, great to see you here again! Hope everything's going well on your side.
> 
> The `KeyError: 'pk'` you're encountering is likely due to the fact that you're not providing a primary key ('pk') when adding documents to the Zilliz vector store, while the `auto_id` parameter is set to False.
> 
> In the LangChain v0.1.5, the `auto_id` parameter was introduced in the `Zilliz` class. This parameter determines whether Milvus should automatically generate unique integers as primary keys. If `auto_id` is set to False, you need to provide text ids (string less than 65535 bytes) as primary keys when adding documents.
> 
> If you don't provide these ids and `auto_id` is set to False, you'll encounter a KeyError: 'pk' because the system is expecting a primary key for each document but isn't finding one.
> 
> To resolve this issue, you can either provide a list of ids when adding documents or set `auto_id` to True to let Milvus generate the ids automatically. Here's how you can do it:
> 
> ```python
> # Providing ids
> vector_db.add_texts(texts=texts, metadatas=metadatas, ids=my_ids)
> 
> # Or setting auto_id to True
> vector_db = Zilliz(
>     embedding_function=embedding,
>     collection_name=collection_name,
>     connection_args=connection_args or {},
>     consistency_level=consistency_level,
>     index_params=index_params,
>     search_params=search_params,
>     drop_old=drop_old,
>     auto_id=True,  # Set auto_id to True
>     **kwargs,
> )
> vector_db.add_texts(texts=texts, metadatas=metadatas)
> ```
> 
> Please replace `my_ids` with your list of ids. Each id should be a string less than 65535 bytes.
> 
> The `auto_id` parameter was introduced in the `Milvus` class in LangChain v0.1.5 as an argument in the class's `__init__` method. It is a boolean value that defaults to `False`.
> 
> ```python
> def __init__(
>     ...
>     auto_id: bool = False,
>     ...
> ):
>     ...
>     self.auto_id = auto_id
>     ...
> ```
> 
> This parameter is used when creating the primary key field in the `_create_collection` method. If `auto_id` is `True`, Milvus will generate unique integers as primary keys. If `False`, the user needs to provide text ids (string less than 65535 bytes).
> 
> ```python
> def _create_collection(
>     ...
> ) -> None:
>     ...
>     # Create the primary key field
>     if self.auto_id:
>         fields.append(
>             FieldSchema(
>                 self._primary_field, DataType.INT64, is_primary=True, auto_id=True
>             )
>         )
>     else:
>         fields.append(
>             FieldSchema(
>                 self._primary_field,
>                 DataType.VARCHAR,
>                 is_primary=True,
>                 auto_id=False,
>                 max_length=65_535,
>             )
>         )
>     ...
> ```
> 
> This change allows users to choose whether they want to manually provide unique identifiers for their data or have Milvus automatically generate them. You can find more details in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py).
> 
> ## Sources
> * [libs/community/langchain_community/vectorstores/zilliz.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/zilliz.py)
> * [libs/community/langchain_community/vectorstores/milvus.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/milvus.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

if use auto_id, maybe not use```
        for i in range(0, total_count, batch_size):
            # Grab end index
            end = min(i + batch_size, total_count)
            # Convert dict to list of lists batch for insertion
            insert_list = [insert_dict[x][i:end] for x in self.fields]
            # Insert into the collection.
            try:
                res: Collection
                res = self.col.insert(insert_list, timeout=timeout, **kwargs)
                pks.extend(res.primary_keys)
            except MilvusException as e:
                logger.error(
                    "Failed to insert batch starting at entity: %s/%s", i, total_count
                )
                raise e
```
because pk is in self.fields, and auto_id may add pk when actually adding to db just like some other orm……
it maybe need  ```insert_list = [insert_dict[x][i:end] for x in self.fields if not (x == 'pk' and self.auto_id)]```?

**Comment by axiangcoding** [comment]
related to my issue #17147 , downgrade to `langchain-community = "0.0.16"` with fix the problem
和我的问题相似，降级到 `langchain-community = "0.0.16"`可以修复这个问题

**Comment by jaelgu** [comment]
This issue has been fixed in the latest version:

https://github.com/langchain-ai/langchain/issues/17147#issuecomment-2121634913
