### ISSUE TITLE
Pandas agent got error:Prompt missing required variables: {'tool_names', 'tools'}

### ISSUE THREAD

**Issue by Xls1994** [langchain-ai/langchain#17019]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

import pandas as pd
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from typing import Any, List, Mapping, Optional
from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from langchain_core.language_models.llms import LLM
class CustomLLM(LLM):
    n: int

    @property
    def _llm_type(self) -> str:
        return "custom"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        if stop is not None:
            raise ValueError("stop kwargs are not permitted.")
        return prompt[: self.n]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {"n": self.n}

df = pd.read_csv("./titanic.csv")
llm=CustomLLM(n=10)
agent = create_pandas_dataframe_agent(llm,df,verbose=True)

result = agent.run("这艘船上存活的男性有多少人")

print(result)

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/langchain_demos.py", line 30, in <module>
    agent = create_pandas_dataframe_agent(llm,df,verbose=True,input_variables=input_vars)
  File "/Users/yyl/opt/anaconda3/envs/ragpy310/lib/python3.10/site-packages/langchain_experimental/agents/agent_toolkits/pandas/base.py", line 264, in create_pandas_dataframe_agent
    runnable=create_react_agent(llm, tools, prompt),  # type: ignore
  File "/Users/yyl/opt/anaconda3/envs/ragpy310/lib/python3.10/site-packages/langchain/agents/react/agent.py", line 97, in create_react_agent
    raise ValueError(f"Prompt missing required variables: {missing_vars}")
ValueError: Prompt missing required variables: {'tool_names', 'tools'}

### Description

I'm trying to use the pandas agent function from Langchain and encountering this error.

### System Info

langchain              0.1.5
langchain-community    0.0.17
langchain-core         0.1.18
langchain-experimental 0.0.50

macos
python 3.10.13

**Comment by Xls1994** [comment]
This should be caused by code not being updated or missed. between the langchain_core and langchain_experimental

**Comment by alvaradojl** [comment]
I have exactly the same problem when creating the agent with create_pandas_dataframe_agent and Azure Open AI

**Comment by tadeodonegana** [comment]
Same problem here

**Comment by hulk66** [comment]
also, as a terrible ugly hack, in langchain_experimental/agents/agent_toolkits/pandas/base.py in `create_pandas_dataframe_agent `adding the two lines
```
        prompt.input_variables.append("tools")
        prompt.input_variables.append("tool_names")
```
before
```
        agent: Union[BaseSingleActionAgent, BaseMultiActionAgent] = RunnableAgent(
            runnable=create_react_agent(llm, tools, prompt),  # type: ignore
            input_keys_arg=["input"],
            return_keys_arg=["output"],
        )
````
overcomes the symptom but most likely not the cause.

**Comment by Jaw-stark** [comment]
it all about how you define the agent adding (agent_type="openai-tools") as an input parameter solved my issue...
 agent_executor = create_pandas_dataframe_agent(
            llm,
            df,
            agent_type="openai-tools",
            verbose=True
        )

**Comment by UUssAAmmA** [comment]
Brother I am having a same issue while calling create_csv_agent(create_csv_agent(llm, user_csv, verbose=True)) 
Please tell me how you fixed it ?

**Comment by RobertSelvam** [comment]
agent_chain = create_csv_agent(
  File "/home/user/.local/lib/python3.10/site-packages/langchain_experimental/agents/agent_toolkits/csv/base.py", line 66, in create_csv_agent
    return create_pandas_dataframe_agent(llm, df, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/langchain_experimental/agents/agent_toolkits/pandas/base.py", line 264, in create_pandas_dataframe_agent
    runnable=create_react_agent(llm, tools, prompt),  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/langchain/agents/react/agent.py", line 97, in create_react_agent
    raise ValueError(f"Prompt missing required variables: {missing_vars}")
ValueError: Prompt missing required variables: {'tool_names', 'tools'}

**Comment by Maple195** [comment]
Having the same issue. Please help!!

**Comment by UUssAAmmA** [comment]
> ```
> agent_chain = create_csv_agent(
> ```
> 
> File "/home/user/.local/lib/python3.10/site-packages/langchain_experimental/agents/agent_toolkits/csv/base.py", line 66, in create_csv_agent return create_pandas_dataframe_agent(llm, df, **kwargs) File "/home/user/.local/lib/python3.10/site-packages/langchain_experimental/agents/agent_toolkits/pandas/base.py", line 264, in create_pandas_dataframe_agent runnable=create_react_agent(llm, tools, prompt), # type: ignore File "/home/user/.local/lib/python3.10/site-packages/langchain/agents/react/agent.py", line 97, in create_react_agent raise ValueError(f"Prompt missing required variables: {missing_vars}") ValueError: Prompt missing required variables: {'tool_names', 'tools'}

Same like my issue.

**Comment by broepke** [comment]
Watching

**Comment by benstager** [comment]
same issue. OP response does not help. what's going on

**Comment by elkanjeremy** [comment]
I think the latest version has this bug. I have solved this by downgrading langchain packages. Here are the package combination that works:
```
langchain==0.1.3
langchain-core==0.1.15
langchain-google-vertexai
langchain-google-genai
langchain-community
langchain-experimental==0.0.49
```

**Comment by ibarrien** [comment]
@elkanjeremy: langchain-experimental==0.0.49 seems to do the trick.
Versions that helped me so far:

`openai==1.12.0
langchain==0.1.3
langhchain-core==0.1.22
langchain_experimental==0.1.3`

**Comment by avisionh** [comment]
I think this might help:
https://github.com/langchain-ai/langchain/issues/17939#issuecomment-2081660241

**Comment by YinSonglin1997** [comment]
I think another solution. I write the `template` and use `prompt = PromptTemplate.from(template=template)`.

**Comment by sarikapatil181** [comment]
is there anyone get solution for above mentioned error ?
