### ISSUE TITLE
how to add prompt template to RetrivealQA function?

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17029]
### Issue with current documentation:

below's the code

```
import os
os.environ["OPENAI_API_KEY"] = ""

from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import DirectoryLoader
from langchain.embeddings import OpenAIEmbeddings
import pickle
import faiss
from langchain.vectorstores import FAISS
# InstructorEmbedding
from InstructorEmbedding import INSTRUCTOR
from langchain.embeddings import HuggingFaceInstructEmbeddings
# OpenAI Embedding
from langchain.embeddings import OpenAIEmbeddings
from langchain.embeddings import HuggingFaceInstructEmbeddings
# from langchain_community.embeddings import HuggingFaceInstructEmbeddings
from InstructorEmbedding import INSTRUCTOR
import textwrap

root_dir = "/content/data"

pdf_files = ['/content/documents/11.pdf', '10.pdf', '12.pdf']

instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl",
                                                      model_kwargs={"device": "cuda"})

def store_embeddings(docs, embeddings, sotre_name, path):

    vectorStore = FAISS.from_documents(docs, embeddings)

    with open(f"{path}/faiss_{sotre_name}.pkl", "wb") as f:
        pickle.dump(vectorStore, f)

def load_embeddings(sotre_name, path):
    with open(f"{path}/faiss_{sotre_name}.pkl", "rb") as f:
        VectorStore = pickle.load(f)
    return VectorStore

embeddings = OpenAIEmbeddings()

def wrap_text_preserve_newlines(text, width=110):
    # Split the input text into lines based on newline characters
    lines = text.split('\n')

    # Wrap each line individually
    wrapped_lines = [textwrap.fill(line, width=width) for line in lines]

    # Join the wrapped lines back together using newline characters
    wrapped_text = '\n'.join(wrapped_lines)

    return wrapped_text

# def process_llm_response(llm_response):
#     print(wrap_text_preserve_newlines(llm_response['result']))
#     print('\nSources:')
#     for source in llm_response["source_documents"]:
#         print(source.metadata['source'])

def process_llm_response(llm_response):
    print(wrap_text_preserve_newlines(llm_response['result']))
    print('\nSources:')

    if llm_response["source_documents"]:
        # Access the first source document
        first_source = llm_response["source_documents"][0]
        source_name = first_source.metadata['source']
        # row_number = first_source.metadata.get('row', 'Not specified')

        # Print the first source's file name and row number
        print(f"{source_name}")
        print("\n")
    else:
        print("No sources available.")

query = 'how many are injured and dead in christchurch Mosque?'

# Assuming `pdf_files` is a list of your PDF files
for pdf_file in pdf_files:
    # Load the PDF file
    loader = PyPDFLoader(pdf_file)
    document = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(
                                               chunk_size=1000,
                                               chunk_overlap=200)

    # Split the document into chunks
    texts = text_splitter.split_documents(document)

    # Create a vector database for the document
    # vectorStore = FAISS.from_documents(texts, instructor_embeddings)

    vectorStore = FAISS.from_documents(texts, embeddings)

    # Create a retriever for the vector database
    retriever = vectorStore.as_retriever(search_kwargs={"k": 5})

    # Create a chain to answer questions
    qa_chain = RetrievalQA.from_chain_type(llm=OpenAI(temperature=0.2),
                                           chain_type="stuff",
                                           retriever=retriever,
                                           return_source_documents=True)

    # Use the chain to answer a question
    llm_response = qa_chain(query)
    process_llm_response(llm_response)
```

and below's the prompt_template

```
prompt_template = """Use the following pieces of information to answer the user's question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else. If no context, then no answer.
Helpful Answer:"""
```

Can you assist me in how to integrate prompt_template to th existing code?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey @nithinreddyyyyyy! Great to see you diving into LangChain again. How's everything going on your end?
> 
> Based on the context provided, it seems like you want to use a custom prompt template with the `RetrievalQA` function in LangChain. However, as per the current design of LangChain, there isn't a direct way to pass a custom prompt template to the `RetrievalQA` function.
> 
> The `RetrievalQA` function in LangChain uses the `OpenAI` language model to generate responses. The `OpenAI` language model doesn't take a prompt template as an argument. Instead, it takes a string as the prompt and generates a response based on that.
> 
> However, you can modify your code to use the prompt template before passing the prompt to the `RetrievalQA` function. Here's an example of how you can do it:
> 
> ```python
> # Define your prompt template
> prompt_template = """Use the following pieces of information to answer the user's question.
> If you don't know the answer, just say that you don't know, don't try to make up an answer.
> 
> Context: {context}
> Question: {question}
> 
> Only return the helpful answer below and nothing else. If no context, then no answer.
> Helpful Answer:"""
> 
> # Format the prompt using the template
> context = "Your context here"
> question = "Your question here"
> formatted_prompt = prompt_template.format(context=context, question=question)
> 
> # Pass the formatted prompt to the RetrievalQA function
> llm_response = qa_chain(formatted_prompt)
> process_llm_response(llm_response)
> ```
> 
> In this code, the `format` method is used to replace `{context}` and `{question}` in the prompt template with the actual context and question. The formatted prompt is then passed to the `RetrievalQA` function.
> 
> Please note that this is a workaround and might not work as expected if the `RetrievalQA` function or the `OpenAI` language model expects a specific format for the prompt. If you encounter any issues with this approach, please provide more details so I can assist you further.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/prompt.py](https://github.com/hwchase17/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/prompt.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.



> _🤖_
> 
> Hey @nithinreddyyyyyy! Great to see you diving into LangChain again. How's everything going on your end?
> 
> Based on the context provided, it seems like you want to use a custom prompt template with the `RetrievalQA` function in LangChain. However, as per the current design of LangChain, there isn't a direct way to pass a custom prompt template to the `RetrievalQA` function.
> 
> The `RetrievalQA` function in LangChain uses the `OpenAI` language model to generate responses. The `OpenAI` language model doesn't take a prompt template as an argument. Instead, it takes a string as the prompt and generates a response based on that.
> 
> However, you can modify your code to use the prompt template before passing the prompt to the `RetrievalQA` function. Here's an example of how you can do it:
> 
> ```python
> # Define your prompt template
> prompt_template = """Use the following pieces of information to answer the user's question.
> If you don't know the answer, just say that you don't know, don't try to make up an answer.
> 
> Context: {context}
> Question: {question}
> 
> Only return the helpful answer below and nothing else. If no context, then no answer.
> Helpful Answer:"""
> 
> # Format the prompt using the template
> context = "Your context here"
> question = "Your question here"
> formatted_prompt = prompt_template.format(context=context, question=question)
> 
> # Pass the formatted prompt to the RetrievalQA function
> llm_response = qa_chain(formatted_prompt)
> process_llm_response(llm_response)
> ```
> 
> In this code, the `format` method is used to replace `{context}` and `{question}` in the prompt template with the actual context and question. The formatted prompt is then passed to the `RetrievalQA` function.
> 
> Please note that this is a workaround and might not work as expected if the `RetrievalQA` function or the `OpenAI` language model expects a specific format for the prompt. If you encounter any issues with this approach, please provide more details so I can assist you further.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/prompt.py](https://github.com/hwchase17/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/prompt.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

but what should i insert in context?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> In the context of using the `RetrievalQA` function in LangChain, the "context" would typically refer to the background information or the source documents that the language model should consider when generating an answer to the provided question.
> 
> In your case, you're using the `PyPDFLoader` to load PDF files and then splitting the loaded documents into chunks using the `RecursiveCharacterTextSplitter`. These chunks of text are then used to create a `FAISS` vector store, which is used as a retriever for the `RetrievalQA` function. This entire process essentially forms the "context" for your `RetrievalQA` function.
> 
> However, when you're using a custom prompt template, the "context" would typically be a string of text that provides some background information related to the question. This "context" is then inserted into the prompt template before the prompt is passed to the `RetrievalQA` function.
> 
> Here's an example:
> 
> ```python
> # Define your prompt template
> prompt_template = """Use the following pieces of information to answer the user's question.
> If you don't know the answer, just say that you don't know, don't try to make up an answer.
> 
> Context: {context}
> Question: {question}
> 
> Only return the helpful answer below and nothing else. If no context, then no answer.
> Helpful Answer:"""
> 
> # Define your context and question
> context = "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France."
> question = "Where is the Eiffel Tower located?"
> 
> # Format the prompt using the template
> formatted_prompt = prompt_template.format(context=context, question=question)
> 
> # Pass the formatted prompt to the RetrievalQA function
> llm_response = qa_chain(formatted_prompt)
> process_llm_response(llm_response)
> ```
> 
> In this example, the "context" is a string of text that provides some information about the Eiffel Tower. This "context" is then used to answer the question "Where is the Eiffel Tower located?".
> 
> Please note that this is a workaround and might not work as expected if the `RetrievalQA` function or the `OpenAI` language model expects a specific format for the prompt. If you encounter any issues with this approach, please provide more details so I can assist you further.
> 
> For more information on how the `RetrievalQA` function uses context, you can refer to the [test_retrieval_qa_with_sources.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/integration_tests/chains/test_retrieval_qa_with_sources.py) file in the LangChain repository. This file contains an example of how the `RetrievalQA` function is used with a context formed from a set of source documents.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/prompt.py](https://github.com/hwchase17/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/prompt.py)
> * [libs/langchain/tests/integration_tests/chains/test_retrieval_qa_with_sources.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/integration_tests/chains/test_retrieval_qa_with_sources.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

but is context required for zero-shot?

**Comment by VpkPrasanna** [comment]
hi @nithinreddyyyyyy  you can use the below code to pass the prompt template in your retrieval QA CHAIN 
`qa_chain = RetrievalQA.from_chain_type(
                    llm=llm,
                    chain_type="stuff",
                    retriever=final_retriever,
                    chain_type_kwargs={"prompt": prompt_template},
                    return_source_documents=True)`
