### ISSUE TITLE
how to add self query retrieval?

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17031]
### Issue with current documentation:

below's the code

```
import os
os.environ["OPENAI_API_KEY"] = ""

from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders.csv_loader import CSVLoader
from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import DirectoryLoader
from langchain.embeddings import OpenAIEmbeddings
import pickle
import faiss
from langchain.vectorstores import FAISS
# InstructorEmbedding
from InstructorEmbedding import INSTRUCTOR
from langchain.embeddings import HuggingFaceInstructEmbeddings
# OpenAI Embedding
from langchain.embeddings import OpenAIEmbeddings
from langchain.embeddings import HuggingFaceInstructEmbeddings
# from langchain_community.embeddings import HuggingFaceInstructEmbeddings
from InstructorEmbedding import INSTRUCTOR
import textwrap

root_dir = "/content/data"

pdf_files = ['11.pdf', '12.pdf', '13.pdf']

instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl",
                                                      model_kwargs={"device": "cuda"})

def store_embeddings(docs, embeddings, sotre_name, path):

    vectorStore = FAISS.from_documents(docs, embeddings)

    with open(f"{path}/faiss_{sotre_name}.pkl", "wb") as f:
        pickle.dump(vectorStore, f)

def load_embeddings(sotre_name, path):
    with open(f"{path}/faiss_{sotre_name}.pkl", "rb") as f:
        VectorStore = pickle.load(f)
    return VectorStore

embeddings = OpenAIEmbeddings()

def wrap_text_preserve_newlines(text, width=110):
    # Split the input text into lines based on newline characters
    lines = text.split('\n')

    # Wrap each line individually
    wrapped_lines = [textwrap.fill(line, width=width) for line in lines]

    # Join the wrapped lines back together using newline characters
    wrapped_text = '\n'.join(wrapped_lines)

    return wrapped_text

# def process_llm_response(llm_response):
#     print(wrap_text_preserve_newlines(llm_response['result']))
#     print('\nSources:')
#     for source in llm_response["source_documents"]:
#         print(source.metadata['source'])

def process_llm_response(llm_response):
    print(wrap_text_preserve_newlines(llm_response['result']))
    print('\nSources:')

    if llm_response["source_documents"]:
        # Access the first source document
        first_source = llm_response["source_documents"][0]
        source_name = first_source.metadata['source']
        # row_number = first_source.metadata.get('row', 'Not specified')

        # Print the first source's file name and row number
        print(f"{source_name}")
        print("\n")
    else:
        print("No sources available.")

# query = 'how many are injured and dead in christchurch Mosque?'

# Define your prompt template
prompt_template = """Use the following pieces of information to answer the user's question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else. If no context, then no answer.
Helpful Answer:"""

# Assuming `pdf_files` is a list of your PDF files
for pdf_file in pdf_files:
    # Load the PDF file
    loader = PyPDFLoader(pdf_file)
    document = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(
                                               chunk_size=1000,
                                               chunk_overlap=200)

    # Split the document into chunks
    texts = text_splitter.split_documents(document)

    # Create a vector database for the document
    # vectorStore = FAISS.from_documents(texts, instructor_embeddings)

    vectorStore = FAISS.from_documents(texts, embeddings)

    # Create a retriever for the vector database
    retriever = vectorStore.as_retriever(search_kwargs={"k": 5})

    # Create a chain to answer questions
    qa_chain = RetrievalQA.from_chain_type(llm=OpenAI(temperature=0.2),
                                           chain_type="stuff",
                                           retriever=retriever,
                                           return_source_documents=True)

    # # Use the chain to answer a question
    # llm_response = qa_chain(query)
    # process_llm_response(llm_response)

    # Format the prompt using the template
    context = ""
    question = "how many are injured and dead in christchurch Mosque?"
    formatted_prompt = prompt_template.format(context=context, question=question)

    # Pass the formatted prompt to the RetrievalQA function
    llm_response = qa_chain(formatted_prompt)
    process_llm_response(llm_response)
```

in the above code, how to add the self query retrieval?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey @nithinreddyyyyyy, great to see you back! Hope you're doing well.
> 
> To incorporate self query retrieval into your LangChain code, you can use the `SelfQueryRetriever` class. This class uses a vector store and a language model to generate vector store queries. Here's a basic example of how you can use it:
> 
> ```python
> from langchain_core.language_models import YourLanguageModel
> from langchain_core.vectorstores import YourVectorStore
> from libs.langchain.langchain.retrievers.self_query.base import SelfQueryRetriever
> 
> # Initialize your language model and vector store
> llm = YourLanguageModel()
> vectorstore = YourVectorStore()
> 
> # Define the document contents and metadata field info
> document_contents = "Your document contents"
> metadata_field_info = [{"name": "field1", "type": "string"}]  # example metadata
> 
> # Create a SelfQueryRetriever instance
> retriever = SelfQueryRetriever.from_llm(
>     llm,
>     vectorstore,
>     document_contents,
>     metadata_field_info,
> )
> 
> # Now you can use the retriever to get relevant documents for a query
> query = "Your query"
> relevant_docs = retriever._get_relevant_documents(query)
> ```
> 
> In this example, replace `YourLanguageModel` and `YourVectorStore` with the actual language model and vector store you're using. The `document_contents` and `metadata_field_info` should be replaced with your actual document contents and metadata field information.
> 
> The `from_llm` method is used to create a `SelfQueryRetriever` instance. It takes a language model, a vector store, document contents, and metadata field info as arguments. It also takes an optional `structured_query_translator` argument, which is a translator for turning internal query language into vector store search params. If this argument is not provided, a built-in translator will be used based on the type of the vector store.
> 
> The `_get_relevant_documents` method is used to get documents relevant for a query. It generates a structured query using the query constructor, prepares the query, and then retrieves the documents from the vector store.
> 
> You can find more information about the `SelfQueryRetriever` class in the [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py) file in the LangChain repository.
> 
> Please replace the `YourLanguageModel`, `YourVectorStore`, `Your document contents`, and `Your query` with the actual values you're using in your project. If you have any further questions or need more clarification, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

But i'm already using qa_chain which will call RetrievalQA, which is useful for question and answering. How to add Self query retrieval?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> > _🤖_
> > To incorporate Self Query Retrieval into your existing code that uses RetrievalQA, you can create a new retriever that uses the `SelfQueryRetriever` class and pass it to the `RetrievalQA` chain. Here's an example of how you can do this:
> > ```python
> > from langchain.retrievers.self_query import SelfQueryRetriever
> > 
> > # Initialize your language model and vector store
> > llm = YourLanguageModel()
> > vectorstore = YourVectorStore()
> > 
> > # Define the document contents and metadata field info
> > document_contents = "Your document contents"
> > metadata_field_info = [{"name": "field1", "type": "string"}]  # example metadata
> > 
> > # Create a SelfQueryRetriever instance
> > self_query_retriever = SelfQueryRetriever.from_llm(
> >     llm,
> >     vectorstore,
> >     document_contents,
> >     metadata_field_info,
> > )
> > 
> > # Create a chain to answer questions
> > qa_chain = RetrievalQA.from_chain_type(llm=OpenAI(temperature=0.2),
> >                                        chain_type="stuff",
> >                                        retriever=self_query_retriever,
> >                                        return_source_documents=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this example, replace `YourLanguageModel` and `YourVectorStore` with the actual language model and vector store you're using. The `document_contents` and `metadata_field_info` should be replaced with your actual document contents and metadata field information.
> > The `from_llm` method is used to create a `SelfQueryRetriever` instance. It takes a language model, a vector store, document contents, and metadata field info as arguments. It also takes an optional `structured_query_translator` argument, which is a translator for turning internal query language into vector store search params. If this argument is not provided, a built-in translator will be used based on the type of the vector store.
> > The `RetrievalQA` chain is then created with the `self_query_retriever` as the retriever. This will allow the chain to use self query retrieval when answering questions.
> > Please replace the `YourLanguageModel`, `YourVectorStore`, `Your document contents`, and `Your query` with the actual values you're using in your project. If you have any further questions or need more clarification, feel free to ask.
> > ## Sources
> > 
> > * [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> > 
> > This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> > Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> > If you want to continue the conversation, start your reply with @dosu-bot.
> 
> ## Sources
> * [libs/langchain/langchain/chains/retrieval_qa/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/retrieval_qa/base.py)
> * [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

But i've already uploaded my pdf files. Then what should i insert in document_contents and metadata_field_info variables?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> To add self query retrieval to your existing code using the LangChain framework, you need to initialize an instance of the `SelfQueryRetriever` class. The `document_contents` and `metadata_field_info` parameters are crucial for this process.
> 
> The `document_contents` parameter should be a string that represents the contents of the document you want to search. This could be a single document or a collection of documents. In your case, you might want to use the text content of your PDF files.
> 
> The `metadata_field_info` parameter should be a sequence of `AttributeInfo` instances or dictionaries. Each `AttributeInfo` or dictionary should describe a metadata field in the document. This could include the field's name, type, and other properties.
> 
> Here is an example of how you might use the `from_llm` method:
> 
> ```python
> from langchain_core.language_models import BaseLanguageModel
> from langchain_core.vectorstores import VectorStore
> from langchain.retrievers.self_query.base import SelfQueryRetriever
> from langchain.chains.query_constructor.schema import AttributeInfo
> 
> # Assuming you have an instance of a language model and a vector store
> llm: BaseLanguageModel = ...
> vectorstore: VectorStore = ...
> 
> # Define the document contents and metadata field info
> document_contents = "This is the content of the document."
> metadata_field_info = [
>     AttributeInfo(name="title", type="string"),
>     AttributeInfo(name="author", type="string"),
>     # Add more fields as needed
> ]
> 
> # Create the self query retriever
> retriever = SelfQueryRetriever.from_llm(
>     llm,
>     vectorstore,
>     document_contents,
>     metadata_field_info,
>     # Add other parameters as needed
> )
> ```
> 
> In this example, `document_contents` is a simple string, and `metadata_field_info` is a list of `AttributeInfo` instances. You would replace the `...` with your actual instances of a language model and a vector store. You can also add other parameters to the `from_llm` method as needed.
> 
> For more details, you can refer to the source code of the `SelfQueryRetriever` class in the LangChain repository: [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> 
> Please note that the exact structure and data type of the `document_contents` parameter might depend on the specific requirements of your project. If you have more specific questions about how to use the `SelfQueryRetriever` class in your project, please provide more details about your use case.
> 
> ## Sources
> * [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Ok, so basically we're just giving some examples of the data to metadata_field_info right? But what if i've uploaded random pdf files and i want to ask questions? I can't enter metadata right?

**Comment by tyatabe** [comment]
Was this solved? I ended up here after reading [this tutorrial ](https://python.langchain.com/v0.2/docs/how_to/self_query/), and see they mention this:
The next key element is the structured query translator. This is the object responsible for translating the generic StructuredQuery object into a metadata filter in the syntax of the vector store you're using. LangChain comes with a number of built-in translators. To see them all head to the [Integrations section](https://python.langchain.com/v0.2/docs/integrations/retrievers/self_query/).
In the above page FAISS is not present, so I'm left wondering if this can be done with FAISS at all
