### ISSUE TITLE
Exracting images from PDF Error "pypdf.errors.PdfReadError: Not encrypted file" 

### ISSUE THREAD

**Issue by luke1212** [langchain-ai/langchain#17134]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
pdf_loader = PyPDFLoader("docs\conda-cheatsheet.pdf", True)
pages = pdf_loader.load()
```

### Error Message and Stack Trace (if applicable)

 File "C:\Users\luke8\Desktop\chatagent\app.py", line 26, in <module>
    pages = pdf_loader.load()
  File "D:\Anaconda3\envs\env39\lib\site-packages\langchain\document_loaders\pdf.py", line 161, in load
    return list(self.lazy_load())
  File "D:\Anaconda3\envs\env39\lib\site-packages\langchain\document_loaders\pdf.py", line 168, in lazy_load
    yield from self.parser.parse(blob)
  File "D:\Anaconda3\envs\env39\lib\site-packages\langchain\document_loaders\base.py", line 95, in parse
    return list(self.lazy_parse(blob))
  File "D:\Anaconda3\envs\env39\lib\site-packages\langchain\document_loaders\parsers\pdf.py", line 26, in lazy_parse
    pdf_reader = pypdf.PdfReader(pdf_file_obj, password=self.password)
  File "D:\Anaconda3\envs\env39\lib\site-packages\pypdf\_reader.py", line 345, in __init__
    raise PdfReadError("Not encrypted file")
pypdf.errors.PdfReadError: Not encrypted file

### Description

Trying to extract image from pft to text, got error above. I also tried to follow the syntax in this [Extracting images in Langchain doc](https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf#extracting-images) got this error instead ```Traceback (most recent call last):
  File "C:\Users\luke8\Desktop\chatagent\app.py", line 25, in <module>
    pdf_loader = PyPDFLoader("docs\TaskWaver.pdf", extract_images=True)
TypeError: __init__() got an unexpected keyword argument 'extract_images'```

### System Info

# packages in environment at D:\Anaconda3\envs\env39:
#
# Name                    Version                   Build  Channel
aiohttp                   3.9.0            py39h2bbff1b_0
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
anyio                     3.5.0            py39haa95532_0    anaconda
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               20.1.0           py39h2bbff1b_1    anaconda
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0           py39haa95532_0    anaconda
babel                     2.11.0           py39haa95532_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
beautifulsoup4            4.12.2           py39haa95532_0    anaconda
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0    anaconda
blinker                   1.7.0                    pypi_0    pypi
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotli-python             1.0.9            py39hd77b12b_7    anaconda
ca-certificates           2023.12.12           haa95532_0
cachetools                5.3.2              pyhd8ed1ab_0    conda-forge
certifi                   2024.2.2         py39haa95532_0
cffi                      1.16.0           py39h2bbff1b_0    anaconda
charset-normalizer        2.0.4              pyhd3eb1b0_0    anaconda
click                     8.1.7            py39haa95532_0
colorama                  0.4.6            py39haa95532_0
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.1.2            py39haa95532_0    anaconda
contourpy                 1.2.0            py39h59b6b97_0
cryptography              41.0.3           py39h89fc84f_0    anaconda
cycler                    0.11.0             pyhd3eb1b0_0
dataclasses-json          0.5.7              pyhd8ed1ab_0    conda-forge
debugpy                   1.6.7            py39hd77b12b_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
defusedxml                0.7.1              pyhd3eb1b0_0    anaconda
distro                    1.9.0                    pypi_0    pypi
docker-pycreds            0.4.0              pyhd3eb1b0_0
entrypoints               0.4              py39haa95532_0    anaconda
et_xmlfile                1.1.0            py39haa95532_0
exceptiongroup            1.0.4            py39haa95532_0    anaconda
executing                 0.8.3              pyhd3eb1b0_0    anaconda
filelock                  3.13.1           py39haa95532_0
flask                     3.0.2                    pypi_0    pypi
flask-sqlalchemy          3.1.1                    pypi_0    pypi
flatbuffers               23.5.26                  pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               ha860e81_0
frozenlist                1.4.0            py39h2bbff1b_0
gitdb                     4.0.7              pyhd3eb1b0_0
gitpython                 3.1.37           py39haa95532_0
gmpy2                     2.1.2            py39h7f96b67_0
google-api-core           2.16.1             pyhd8ed1ab_0    conda-forge
google-auth               2.27.0             pyhca7485f_0    conda-forge
googleapis-common-protos  1.62.0             pyhd8ed1ab_0    conda-forge
greenlet                  3.0.3                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
humanfriendly             10.0             py39haa95532_1
icc_rt                    2022.1.0             h6049295_2
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.4              py39haa95532_0    anaconda
importlib-metadata        7.0.1            py39haa95532_0
importlib_resources       6.1.1            py39haa95532_1
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.25.0           py39h9909e9c_0    anaconda
ipython                   8.15.0           py39haa95532_0    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
ipywidgets                8.0.4            py39haa95532_0    anaconda
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1           py39haa95532_1    anaconda
jinja2                    3.1.3            py39haa95532_0
joblib                    1.2.0            py39haa95532_0
jpeg                      9e                   h2bbff1b_1    anaconda
json5                     0.9.6              pyhd3eb1b0_0    anaconda
jsonschema                4.19.2           py39haa95532_0    anaconda
jsonschema-specifications 2023.7.1         py39haa95532_0    anaconda
jupyter                   1.0.0            py39haa95532_8    anaconda
jupyter_client            7.4.9            py39haa95532_0    anaconda
jupyter_console           6.6.3            py39haa95532_0    anaconda
jupyter_core              5.5.0            py39haa95532_0    anaconda
jupyter_server            1.23.4           py39haa95532_0    anaconda
jupyterlab                3.3.2              pyhd3eb1b0_0    anaconda
jupyterlab_pygments       0.2.2            py39haa95532_0    anaconda
jupyterlab_server         2.25.1           py39haa95532_0    anaconda
jupyterlab_widgets        3.0.9            py39haa95532_0    anaconda
kiwisolver                1.4.4            py39hd77b12b_0
krb5                      1.20.1               h5b6d351_1    anaconda
langchain                 0.0.291            pyhd8ed1ab_0    conda-forge
langsmith                 0.0.86             pyhd8ed1ab_0    conda-forge
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  14.0.6          default_hb5a9fac_1    anaconda
libclang13                14.0.6          default_h8e68704_1    anaconda
libdeflate                1.17                 h2bbff1b_1
libpng                    1.6.39               h8cc25b3_0    anaconda
libpq                     12.15                h906ac69_1    anaconda
libprotobuf               3.20.3               h23ce68f_0
libsodium                 1.0.18               h62dcd97_0    anaconda
libtiff                   4.5.1                hd77b12b_0
libuv                     1.44.2               h2bbff1b_0
libwebp-base              1.3.2                h2bbff1b_0
lz4-c                     1.9.4                h2bbff1b_0    anaconda
markupsafe                2.1.3            py39h2bbff1b_0
marshmallow               3.20.2             pyhd8ed1ab_0    conda-forge
marshmallow-enum          1.5.1              pyh9f0ad1d_3    conda-forge
matplotlib-base           3.8.0            py39h4ed8f06_0
matplotlib-inline         0.1.6            py39haa95532_0    anaconda
mistune                   2.0.4            py39haa95532_0    anaconda
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py39h2bbff1b_1
mkl_fft                   1.3.8            py39h2bbff1b_0
mkl_random                1.2.4            py39h59b6b97_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.3.0            py39haa95532_0
multidict                 6.0.4            py39h2bbff1b_0
munkres                   1.1.4                      py_0
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclassic                 0.5.5            py39haa95532_0    anaconda
nbclient                  0.8.0            py39haa95532_0    anaconda
nbconvert                 7.10.0           py39haa95532_0    anaconda
nbformat                  5.9.2            py39haa95532_0    anaconda
nest-asyncio              1.5.6            py39haa95532_0    anaconda
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
notebook                  6.5.4            py39haa95532_0    anaconda
notebook-shim             0.2.3            py39haa95532_0    anaconda
numexpr                   2.8.7            py39h2cd9be0_0
numpy                     1.26.3           py39h055cbcc_0
numpy-base                1.26.3           py39h65a83cf_0
onnxruntime               1.17.0          py39he3bb845_0_cpu    conda-forge
openai                    1.11.1                   pypi_0    pypi
openapi-schema-pydantic   1.2.4              pyhd8ed1ab_0    conda-forge
opencv-python             4.9.0.80                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openpyxl                  3.0.10           py39h2bbff1b_0
openssl                   3.0.13               h2bbff1b_0
packaging                 23.1             py39haa95532_0    anaconda
pandas                    2.2.0            py39h32e6231_0    conda-forge
pandas-stubs              2.1.4.231227     py39haa95532_0
pandocfilters             1.5.0              pyhd3eb1b0_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
pathtools                 0.1.2              pyhd3eb1b0_1
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    10.0.1                   pypi_0    pypi
pip                       23.3.1           py39haa95532_0
platformdirs              3.10.0           py39haa95532_0    anaconda
plotly                    5.9.0            py39haa95532_0
pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
ply                       3.11             py39haa95532_0    anaconda
prometheus_client         0.14.1           py39haa95532_0    anaconda
prompt-toolkit            3.0.36           py39haa95532_0    anaconda
prompt_toolkit            3.0.36               hd3eb1b0_0    anaconda
protobuf                  3.20.3           py39hcbf5309_1    conda-forge
psutil                    5.9.0            py39h2bbff1b_0    anaconda
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
pyasn1                    0.5.1              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.3.0              pyhd8ed1ab_0    conda-forge
pyclipper                 1.3.0.post5              pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    anaconda
pydantic                  1.10.12          py39h2bbff1b_1
pygments                  2.15.1           py39haa95532_1    anaconda
pyopenssl                 23.2.0           py39haa95532_0    anaconda
pyparsing                 3.0.9            py39haa95532_0
pypdf                     4.0.1                    pypi_0    pypi
pyqt                      5.15.10          py39hd77b12b_0    anaconda
pyqt5-sip                 12.13.0          py39h2bbff1b_0    anaconda
pyreadline3               3.4.1            py39haa95532_0
pysocks                   1.7.1            py39haa95532_0    anaconda
pytest                    8.0.0              pyhd8ed1ab_0    conda-forge
pytest-subtests           0.11.0             pyhd8ed1ab_0    conda-forge
python                    3.9.18               h1aa4202_0
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-dotenv             1.0.1              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2           py39haa95532_0    anaconda
python-flatbuffers        2.0                pyhd3eb1b0_0
python-tzdata             2023.3             pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytorch                   2.2.0               py3.9_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2023.3.post1     py39haa95532_0    anaconda
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywin32                   305              py39h2bbff1b_0    anaconda
pywinpty                  2.0.10           py39h5da7b33_0    anaconda
pyyaml                    6.0.1            py39h2bbff1b_0
pyzmq                     25.1.0           py39hd77b12b_0    anaconda
qt-main                   5.15.2               h879a1e9_9    anaconda
qtconsole                 5.5.0            py39haa95532_0    anaconda
qtpy                      2.4.1            py39haa95532_0    anaconda
rapidocr-onnxruntime      1.3.11                   pypi_0    pypi
referencing               0.30.2           py39haa95532_0    anaconda
requests                  2.31.0           py39haa95532_0    anaconda
rpds-py                   0.10.6           py39h062c2fa_0    anaconda
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scikit-learn              1.3.0            py39h4ed8f06_1
scipy                     1.11.4           py39h309d312_0
send2trash                1.8.2            py39haa95532_0    anaconda
sentry-sdk                1.9.0            py39haa95532_0
setproctitle              1.2.2           py39h2bbff1b_1004
setuptools                68.2.2           py39haa95532_0
shapely                   2.0.2                    pypi_0    pypi
sip                       6.7.12           py39hd77b12b_0    anaconda
six                       1.16.0             pyhd3eb1b0_1    anaconda
smmap                     4.0.0              pyhd3eb1b0_0
sniffio                   1.2.0            py39haa95532_1    anaconda
soupsieve                 2.5              py39haa95532_0    anaconda
sqlalchemy                2.0.25                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
stringcase                1.2.0                      py_0    conda-forge
sympy                     1.12             py39haa95532_0
tbb                       2021.8.0             h59b6b97_0
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
terminado                 0.17.1           py39haa95532_0    anaconda
threadpoolctl             2.2.0              pyh0d69192_0
tinycss2                  1.2.1            py39haa95532_0    anaconda
tomli                     2.0.1            py39haa95532_0    anaconda
tornado                   6.3.3            py39h2bbff1b_0    anaconda
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.7.1            py39haa95532_0    anaconda
types-pytz                2022.4.0.0       py39haa95532_1
typing-extensions         4.9.0            py39haa95532_1
typing_extensions         4.9.0            py39haa95532_1
typing_inspect            0.9.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023d                h04d1e81_0
ucrt                      10.0.20348.0         haa95532_0
urllib3                   1.26.18          py39haa95532_0    anaconda
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wandb                     0.16.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1            py39haa95532_1    anaconda
websocket-client          0.58.0           py39haa95532_4    anaconda
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39haa95532_0
widgetsnbextension        4.0.5            py39haa95532_0    anaconda
win_inet_pton             1.1.0            py39haa95532_0    anaconda
winpty                    0.4.3                         4    anaconda
xz                        5.4.2                h8cc25b3_0    anaconda
yaml                      0.2.5                he774522_0
yarl                      1.7.2            py39hb82d6ee_2    conda-forge
zeromq                    4.3.4                hd77b12b_0    anaconda
zipp                      3.17.0           py39haa95532_0
zlib                      1.2.13               h8cc25b3_0    anaconda
zstd                      1.5.5                hd43e919_0    anaconda

**Comment by luke1212** [comment]
Hi bot :), I tried to used all the other suggested pdf loader but still have the same error ```  File "C:\Users\luke8\Desktop\chatagent\app.py", line 25, in <module>
    pdf_loader = PyMuPDFLoader("docs\TaskWaver.pdf", extract_images=True)
TypeError: __init__() got an unexpected keyword argument 'extract_images'``` and ```File "C:\Users\luke8\Desktop\chatagent\app.py", line 25, in <module>
    pdf_loader = PyPDFDirectoryLoader("docs\TaskWaver.pdf", extract_images=True)
TypeError: __init__() got an unexpected keyword argument 'extract_images'```

**Comment by lxyoutlook** [comment]
I encountered the same error. My langchain version is 0.0.267. 
TypeError: PyPDFLoader.__init__() got an unexpected keyword argument 'extract_images'
