### ISSUE TITLE
No stop sequneces supported for OpenAI

### ISSUE THREAD

**Issue by JoelKronander** [langchain-ai/langchain#1717]
I noticed there is no support for stop sequences in the langchain API, 

Is this some deliberate choice, or should I make a PR to add support for it?

**Comment by sheikalthaf** [comment]
@hwchase17 any plan to integrate this one?

**Comment by klyap** [comment]
+1 would love to have this supported

**Comment by sebastianseck** [comment]
Yes, same here. I can't seem to stop my ChatBots (local LLMs with huggingface_pipelines) from generating my parts of the conversation and haven't found any way to declare a stop sequence, so either it's not in there or I'm just blind.

**Comment by byrnehollander** [comment]
In case this helps anyone, I was able to get stop sequences working by using `model_kwargs`:

```
    llm = OpenAI(
        model=model,
        model_kwargs={"stop": ["###"]},
    )
```
