### ISSUE TITLE
community: [MongoDBAtlasVectorSearch] Fix KeyError 'embedding'

### ISSUE THREAD

**Issue by cjpark-data** [langchain-ai/langchain#17177]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
class MongoHandler:
...
    @error_logging
    def setup_vector_search(
        self,
        search_index_name: str,
        text_key: str,
        embedding_key: str
    ) -> None:
        self._search_index_name = search_index_name
        try:
            self._vector_search = MongoDBAtlasVectorSearch(
                collection=self._collection,
                embedding=self._embedding_model,
                index_name=search_index_name,
                text_key=text_key,
                embedding_key=embedding_key,
            )
        
        except Exception as e:
            logging.error('Mongo Atlas에서 먼저 Search Index 세팅을 해주세요.')
            logging.error(e)
            raise e
    
    @error_logging
    def vector_search(
        self,
        query: str,
        k: int=5,
        pre_filter: dict=None,
    ) -> List[Document]:
        assert self._vector_search, 'vector search 세팅을 먼저 해주세요.'
        
        results = self._vector_search.similarity_search(
            query=query,
            k=k,
            pre_filter=pre_filter
        )
        return results

def search_documents(company_name, question_dict, num_docs=2):
    search_result = {}
    for key, value in question_dict.items():
        for query in value:
            contents = ''
            pre_filter = {"$and": [{"stock_name": company_name}, {'major_category': key}]}
            search = MONGODB_COLLENTION.vector_search(
                query=query, 
                pre_filter=pre_filter, 
                k=num_docs
            )
            search_contents = [content.page_content for content in search]
            # reference_data = [content.metadata for content in search]
            contents += '\n\n'.join(search_contents)
            search_result[query] = contents

    return search_result

def run(model="gpt-3.5-turbo-0125"):
    stock_name_list = get_company_name()

    company_info = {}
    for company_name in tqdm(stock_name_list[:2]):
        question_dict = make_questions(company_name)
        search_result = search_documents(company_name, question_dict)
        total_answers = get_answers(company_name, search_result, model)
        company_info.update(total_answers)

    return company_info

company_info_1 = run(model="gpt-3.5-turbo-1106")
for key, value in company_info_1.items():
    print(f"{key}:\n{value}\n\n")
```

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[5], line 1
----> 1 company_info_1 = run(model="gpt-3.5-turbo-1106")
      2 for key, value in company_info_1.items():
      3     print(f"{key}:\n{value}\n\n")

Cell In[4], line 7
      5 for company_name in tqdm(stock_name_list[:2]):
      6     question_dict = make_questions(company_name)
----> 7     search_result = search_documents(company_name, question_dict)
      8     total_answers = get_answers(company_name, search_result, model)
      9     company_info.update(total_answers)

Cell In[3], line 24
     22 contents = ''
     23 pre_filter = {"$and": [{"stock_name": company_name}, {'major_category': key}]}
---> 24 search = MONGODB_COLLENTION.vector_search(
     25     query=query, 
     26     pre_filter=pre_filter, 
     27     k=num_docs
     28 )
     29 search_contents = [content.page_content for content in search]
     30 # reference_data = [content.metadata for content in search]

File ~/work/team_project/contents-generate-ai/baseLogger.py:210, in error_logging.<locals>.wrapper(*args, **kwargs)
    208 except Exception as e:
    209     logging.error(e)
--> 210     raise e

File ~/work/team_project/contents-generate-ai/baseLogger.py:206, in error_logging.<locals>.wrapper(*args, **kwargs)
    204 def wrapper(*args, **kwargs):
    205     try:
--> 206         return func(*args, **kwargs)
    208     except Exception as e:
    209         logging.error(e)

File ~/work/team_project/contents-generate-ai/src/modules/my_mongodb.py:247, in MongoHandler.vector_search(self, query, k, pre_filter)
    238 @error_logging
    239 def vector_search(
    240     self,
   (...)
    243     pre_filter: dict=None,
    244 ) -> List[Document]:
    245     assert self._vector_search, 'vector search 세팅을 먼저 해주세요.'
--> 247     results = self._vector_search.similarity_search(
    248         query=query,
    249         k=k,
    250         pre_filter=pre_filter
    251     )
    252     return results

File ~/work/team_project/contents-generate-ai/.venv/lib/python3.10/site-packages/langchain_community/vectorstores/mongodb_atlas.py:273, in MongoDBAtlasVectorSearch.similarity_search(self, query, k, pre_filter, post_filter_pipeline, **kwargs)
    256 """Return MongoDB documents most similar to the given query.
    257 
    258 Uses the vectorSearch operator available in MongoDB Atlas Search.
   (...)
    270     List of documents most similar to the query and their scores.
    271 """
    272 additional = kwargs.get("additional")
--> 273 docs_and_scores = self.similarity_search_with_score(
    274     query,
    275     k=k,
    276     pre_filter=pre_filter,
    277     post_filter_pipeline=post_filter_pipeline,
    278 )
    280 if additional and "similarity_score" in additional:
    281     for doc, score in docs_and_scores:

File ~/work/team_project/contents-generate-ai/.venv/lib/python3.10/site-packages/langchain_community/vectorstores/mongodb_atlas.py:240, in MongoDBAtlasVectorSearch.similarity_search_with_score(self, query, k, pre_filter, post_filter_pipeline)
    223 """Return MongoDB documents most similar to the given query and their scores.
    224 
    225 Uses the vectorSearch operator available in MongoDB Atlas Search.
   (...)
    237     List of documents most similar to the query and their scores.
    238 """
    239 embedding = self._embedding.embed_query(query)
--> 240 docs = self._similarity_search_with_score(
    241     embedding,
    242     k=k,
    243     pre_filter=pre_filter,
    244     post_filter_pipeline=post_filter_pipeline,
    245 )
    246 return docs

File ~/work/team_project/contents-generate-ai/.venv/lib/python3.10/site-packages/langchain_community/vectorstores/mongodb_atlas.py:212, in MongoDBAtlasVectorSearch._similarity_search_with_score(self, embedding, k, pre_filter, post_filter_pipeline)
    210     text = res.pop(self._text_key)
    211     score = res.pop("score")
--> 212     del res["embedding"]
    213     docs.append((Document(page_content=text, metadata=res), score))
    214 return docs

KeyError: 'embedding'

### Description

<Situation>
1. Set up the embedding field name, "doc_embedding"
2. Run `MongoDBAtlasVectorSearch(**kwargs).similarity_search(**params)`
3. Raise KeyError: 'embedding'

I think `del res["embedding"]` is hard code.
So I suggest that fix that line to `del res[self._embedding_key]`.

### System Info

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.7.0"
langchain = "^0.1.0"
langchain-openai = "^0.0.2"
langchain-community = "^0.0.15"

**Comment by jaymon0703** [comment]
I still get this `KeyError: 'embedding'`. @cjpark-data can you confirm whether or not you still get this error, and which version of pymongo you are using? Thanks!
