### ISSUE TITLE
SqlDatabaseToolkit should have custom llm_chain for QueryCheckerTool

### ISSUE THREAD

**Issue by ekzhu** [langchain-ai/langchain#1719]
https://github.com/hwchase17/langchain/blob/master/langchain/agents/agent_toolkits/sql/toolkit.py#L38

SqlDatabaseToolkit should have custom llm_chain field for QueryCheckerTool. This is causing issues when OpenAI is not available, as the QueryCheckerTool will automatically use OpenAI.

**Comment by rushout09** [comment]
Hi @ekzhu, I am picking up this issue.
