### ISSUE TITLE
SQLDatabaseChain, SQLDatabase max_string_length not working

### ISSUE THREAD

**Issue by sbisen** [langchain-ai/langchain#17212]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

@dosu-bot I am getting the error with SQLDatabase and SQLDatabaseChain. The output tokens of SQL command gets truncated max at 128 even after using max_string_length parameter in SQLDatabase set to 32000.

Here is the code:

db_connection = SQLDatabase.from_uri(
        snowflake_url,
        sample_rows_in_table_info=1,
        include_tables=["table1"],
        view_support=True,
        max_string_length=32000,
    )
    return_op = SQLDatabaseChain.from_llm(
        llm,
        db_connection,
        prompt=few_shot_prompt,
        verbose=True,
        return_intermediate_steps=True,
    )

### Error Message and Stack Trace (if applicable)

ProgrammingError: (snowflake.connector.errors.ProgrammingError) 001003 (42000): SQL compilation error: parse error line 1 at position 300 near '<EOF>. [SQL: SELECT DESTINATION_DATA, SUM(CASE WHEN LOWER(TRIM(TVENA_CANE)) = 'skpettion' THEN 1 ELSE 0 END) AS skpettion, SUM(CASE WHEN LOWER(TRIM(TVENA_CANE)) = 'tickk' THEN 1 ELSE 0 END) AS CLICKS FROM TABT_COURS_KBSPBIGN_CIDORT WHERE DIRQANE = 'buj' AND TVENA_CANE >= '2023-12-01' AND TVENA_CANE <= '2023] 

### Description

Generated SQL command gets truncated max at 128

### System Info

boto3==1.34.29
chromadb==0.4.22
huggingface-hub==0.20.3
langchain==0.1.4
langchain-experimental==0.0.49
python-dotenv==1.0.1
sentence_transformers==2.3.0
snowflake-connector-python==3.7.0
snowflake-sqlalchemy==1.5.1
SQLAlchemy==1.4.51
streamlit==1.30.0

**Comment by sbisen** [comment]
@dosu-bot.
Here is few_shot_prompt=
```
few_shot_prompt = FewShotPromptTemplate(
        example_selector=example_selector,
        example_prompt=example_prompt,
        prefix=_postgres_prompt + 'Provide no preamble' + ' Here are some examples:',
        suffix=PROMPT_SUFFIX,
        input_variables=['table_info', 'input', 'top_k'],
    )
Parameters for few_shot_prompt are as follows:
example_selector = SemanticSimilarityExampleSelector.from_examples(
        examples,
        local_embeddings,
        Chroma,
        k=min(4, len(examples)),
    )

```
```
example_prompt = PromptTemplate(
        input_variables=[
            'table_info',
            'input',
            'snowflake_sql_cmd',
            'snowflake_sql_result',
            'answer',
        ],
        template=(
            '{table_info}\n\nQuestion: {input}\nSQLQuery: {snowflake_sql_cmd}\nSQLResult:'
            ' {snowflake_sql_result}\nAnswer: {answer}'
        ),
    )
```
    
there are 10 example are in a yaml file and goes as input to example_selector looks like below-
```
- answer: There are 5806 rows in the data table.
  input: How many rows are in the data table?
  sql_cmd: SELECT count(*) FROM data;
  sql_result: '[(5806,)]'
  table_info: |
    CREATE TABLE DATA(
    title VARCHAR,
    type VARCHAR,
    release_year INT,
    age_certification VARCHAR,
    runtime INT,
    genres VARCHAR,
    production_countries VARCHAR,
    seasons INT,
    imdb_id VARCHAR,
    imdb_score INT,
    imdb_votes INT
    );
```

**Comment by sbisen** [comment]
1. Issue is happening with longer SQL query
2. not sure, maybe then there is date time period involved in the query
3. example for SQL getting truncted=

- SQL: SELECT TESTINOTION_DATA, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'tepression' THEN 1 ELSE 0 END) AS TEPRESSIONS, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'clock' THEN 1 ELSE 0 END) AS CLOCK FROM tamps_coute_samtaigm_deport WHERE IRELAND = 'car' AND event_date >= '2024-12-01' AND event_date <= '2024-01-0]
- 
SQL: SELECT TESTINOTION_DATA, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'tepression' THEN 1 ELSE 0 END) AS TEPRESSIONS, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'clock' THEN 1 ELSE 0 END) AS CLOCK, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'satination' THEN 1 ELSE 0 END) AS satination FROM tamps_coute_samtaigm_deport WHERE IRELAND = "

4. Snowflake version = 8.5.1

**Comment by sbisen** [comment]
@dosu-bot.

Issue is happening with longer SQL query
not sure, maybe then there is date time period involved in the query
example for SQL getting truncted=
SQL: SELECT TESTINOTION_DATA, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'tepression' THEN 1 ELSE 0 END) AS TEPRESSIONS, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'clock' THEN 1 ELSE 0 END) AS CLOCK FROM tamps_coute_samtaigm_deport WHERE IRELAND = 'car' AND event_date >= '2024-12-01' AND event_date <= '2024-01-0]
SQL: SELECT TESTINOTION_DATA, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'tepression' THEN 1 ELSE 0 END) AS TEPRESSIONS, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'clock' THEN 1 ELSE 0 END) AS CLOCK, SUM(CASE WHEN LOWER(TRIM(TVENT_MAIN)) = 'satination' THEN 1 ELSE 0 END) AS satination FROM tamps_coute_samtaigm_deport WHERE IRELAND = "

Snowflake version = 8.5.1

**Comment by sbisen** [comment]
@dosu-bot.
4. It is full error message. It seems to be cut off because SQL code generated was cut off (This is the main issue)
5. llm_parameter = Bedrock(
    client=client,
    model_id='amazon.titan-text-express-v1',
    model_kwargs={'temperature': 0.1},
    endpoint_url='https://bedrock-runtime.us-east-1.amazonaws.com',
    region_name='us-east-1',
    verbose=True,
)
6. I used from langchain_community.vectorstores import Chroma

**Comment by sbisen** [comment]
@dosu-bot. show which class has truncate_word function?

**Comment by keenborder786** [comment]
@sbisen given the error that you have posted , I doubt it has anything to do with `max_string_length`. Because I have tested this in multiple flows and it works fine for me. From your error trace it seems, the error is with the connector that  you are using:
``bash
snowflake-connector-python==3.7.0
snowflake-sqlalchemy==1.5.1
```

**Comment by sbisen** [comment]
@keenborder786 thanks for reply. did you use snowflake as well. what version worked for you?snowflake-connector-python==?
snowflake-sqlalchemy==?

**Comment by keenborder786** [comment]
Yes same version.
