### ISSUE TITLE
The  pip install for  langchain-pinecone shows error.

### ISSUE THREAD

**Issue by nidhinpd-YML** [langchain-ai/langchain#17221]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```%pip install --upgrade --quiet  langchain-pinecone langchain-openai langchain```

### Error Message and Stack Trace (if applicable)

ERROR: Could not find a version that satisfies the requirement langchain-pinecone (from versions: none)

ERROR: No matching distribution found for langchain-pinecone

### Description

To install the new pinecone vector store library LangChain suggests to install the **langchain-pinecone** library through pip install. But the pip install says that such a package does not exist. This is the [document page](https://python.langchain.com/docs/integrations/vectorstores/pinecone) I'm referring to.

### System Info

langchain==0.1.5
langchain-community==0.0.19
langchain-core==0.1.21
pinecone-client==3.0.2

Platform: linux and Google colab

**Comment by nidhinpd-YML** [comment]
@dosubot The issue is that the LangChain docs and README mention `pip install langchain-pinecone` and the pip install is not working.

**Comment by nidhinpd-YML** [comment]
`langchain-pinecone` is available on pypi now. This issue is fixed.

**Comment by jeremydiba** [comment]
> `langchain-pinecone` is available on pypi now. This issue is fixed.

Investigating but I think the following changes have introduced a change in behavior. 

When importing
`from langchain_pinecone import PineconeVectorStore`

`pinecone.deprecated_plugins.DeprecatedPluginError: The `pinecone-plugin-inference` package has been deprecated. The features from that plugin have been incorporated into the main `pinecone` package with no need for additional plugins. Please remove the `pinecone-plugin-inference`

**Comment by jgx02c** [comment]
> > `langchain-pinecone` is available on pypi now. This issue is fixed.
> 
> Investigating but I think the following changes have introduced a change in behavior.
> 
> When importing `from langchain_pinecone import PineconeVectorStore`
> 
> `pinecone.deprecated_plugins.DeprecatedPluginError: The `pinecone-plugin-inference`package has been deprecated. The features from that plugin have been incorporated into the main`pinecone`package with no need for additional plugins. Please remove the`pinecone-plugin-inference`

Having lots of issues now where none of it seems available.

**Comment by ashutosh3060** [comment]
I am getting below error for 'from langchain_pinecone import PineconeVectorStore'
ModuleNotFoundError: No module named 'langchain_pinecone'
