### ISSUE TITLE
Update documentation for sitemap loader to use correct URL

### ISSUE THREAD

**Issue by Alexandro027** [langchain-ai/langchain#17236]
### Issue with current documentation:

The function sitemap doesn't fetching, it gives me a empty list.

Code: 
```
from langchain_community.document_loaders.sitemap import SitemapLoader

sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml")

sitemap_loader.requests_per_second = 2

sitemap_loader.requests_kwargs = {"verify": False}

docs = sitemap_loader.load()

print(docs)

```

Output:
Fetching pages: 0it [00:00, ?it/s]
[]

### Idea or request for content:

The example of documentation doesn't work

**Comment by eyurtsev** [comment]
Use:  https://api.python.langchain.com/sitemap.xml

If you know how to submit a PR and willing to fix the docs, would appreciate it: )
