### ISSUE TITLE
can i use FAISS isntead of Chroma for ParentDocumentRetriver?

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17237]
### Issue with current documentation:

below's the code

```
child_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=50)
parent_splitter = RecursiveCharacterTextSplitter(chunk_size=1200, chunk_overlap=300)

vectorstore = Chroma(
  collection_name="full_documents", embedding_function=embeddings)

store = InMemoryStore()

retriever = ParentDocumentRetriever(
  vectorstore=vectorstore,
  docstore=store,
  child_splitter=child_splitter,
  parent_splitter=parent_splitter
)

retriever.add_documents(document, ids=None)
```

above is the code which uses chroma as vectordb, can i use FAISS for child_splitter and parent_splitter like below code

```
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500,
                                               chunk_overlap=50)

texts = text_splitter.split_documents(documents)

# Create a vector database for the document
# vectorStore = FAISS.from_documents(texts, instructor_embeddings)

vectorStore = FAISS.from_documents(texts, embeddings)
```

if yes, ca you please help me with the code?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey there, @nithinreddyyyyyy! Long time no see in the virtual realms of issue boards. Hope you're coding away to glory! 🚀 Let's dive into your FAISS quest, shall we?
> 
> Yes, it is possible to use FAISS instead of Chroma for the `ParentDocumentRetriever` in the LangChain framework. The FAISS class in the provided context is a subclass of VectorStore, which means it can be used as a vector store for the `ParentDocumentRetriever`.
> 
> Here is a general example of how you can adjust your code:
> 
> ```python
> from langchain_community.embeddings.openai import OpenAIEmbeddings
> from langchain_community.vectorstores import FAISS
> 
> # Initialize the embeddings and FAISS
> embeddings = OpenAIEmbeddings()
> texts = ["FAISS is an important library", "LangChain supports FAISS"]
> faiss = FAISS.from_texts(texts, embeddings)
> 
> # Initialize the ParentDocumentRetriever with FAISS
> parent_document_retriever = ParentDocumentRetriever(vector_store=faiss)
> ```
> 
> Please replace `ParentDocumentRetriever` with the actual class name and adjust the parameters as needed. You can find more information about the FAISS class in the [FAISS file](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py) in the LangChain repository.
> 
> Regarding the `ParentDocumentRetriever` class, it is a subclass of `MultiVectorRetriever` designed to retrieve small chunks of data and then look up the parent ids for those chunks and return those larger documents. The class has two main attributes: `child_splitter` and `parent_splitter`. The `child_splitter` is a `TextSplitter` used to create child documents, while the `parent_splitter` is an optional `TextSplitter` used to create parent documents. If `parent_splitter` is not provided, then the parent documents will be the raw documents passed in. You can find more details about the `ParentDocumentRetriever` class in the [ParentDocumentRetriever file](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/parent_document_retriever.py) in the LangChain repository.
> 
> I hope this helps! If you have any more questions, feel free to ask.
> 
> ## Sources
> * [libs/community/langchain_community/vectorstores/faiss.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py)
> * [libs/langchain/langchain/retrievers/parent_document_retriever.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/parent_document_retriever.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

but in the code you gave, you're not considering child_splitter and parent_splitter. Can you please return the code with child_splitter and parent_splitter as well?

**Comment by rocky1405** [comment]
claiming this issue

**Comment by rocky1405** [comment]
take

**Comment by rocky1405** [comment]
@nithinreddyyyyyy may I know why this change is required? Is the current example not working as expected? Asking in order to get the context.

**Comment by jaideep11061982** [comment]
@eyurtsev @rocky1405 @sbusso @jarib  do you guys know how to fit pinecone. If suppose I have serveral thousands document,how do i add one by one
