### ISSUE TITLE
Enhancement: Add ability to pass local cache to chat models

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#17242]
Feature request discussed  in https://github.com/langchain-ai/langchain/discussions/17176

Expand `cache` to accept a cache implementation in addition to a bool value:

https://github.com/langchain-ai/langchain/blob/00a09e1b7117f3bde14a44748510fcccc95f9de5/libs/core/langchain_core/language_models/chat_models.py#L106-L106

If provided, will use the given cache.

# Acceptance Criteria

- [ ] Documentation to the cache variable to explain how it can be used
- [ ] Update https://python.langchain.com/docs/modules/model_io/chat/chat_model_caching
- [ ] Include unit tests to test given functionality

PR can include implementation for caching of LLMs in addition to chat models.

**Comment by alhridoy** [comment]
Hi @eyurtsev Could you check my PR? Thanks!
