### ISSUE TITLE
Temperature for NVIDIA Cloud Function (NVCF) endpoint could not be set to 0

### ISSUE THREAD

**Issue by psgundecha-nv** [langchain-ai/langchain#17257]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_nvidia_ai_endpoints import ChatNVIDIA
 
llm = ChatNVIDIA(model="playground_mixtral_8x7b",
                 temperature=0.0,
                 top_p=0,
                 max_tokens=500,
                 seed=42,
                 callbacks = callbacks
              )

### Error Message and Stack Trace (if applicable)

ValidationError                           Traceback (most recent call last)
Cell In[62], line 11      5     pass      9 from langchain_nvidia_ai_endpoints import ChatNVIDIA---> 11 llm = ChatNVIDIA(model="playground_mixtral_8x7b",     12                  temperature=0.0,     13                  top_p=0,     14                  max_tokens=500,     15                  seed=42,     16                  callbacks = callbacks     17               )
File /usr/local/lib/python3.10/site-packages/langchain_core/load/serializable.py:107, in Serializable.__init__(self, **kwargs)    106 def __init__(self, **kwargs: Any) -> None:--> 107     super().__init__(**kwargs)    108     self._lc_kwargs = kwargs

File /usr/local/lib/python3.10/site-packages/pydantic/v1/main.py:341, in BaseModel.__init__(__pydantic_self__, **data)    339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)    340 if validation_error:--> 341     raise validation_error    342 try:    343     object_setattr(__pydantic_self__, '__dict__', values)
ValidationError: 1 validation error for ChatNVIDIA
temperature
  ensure this value is greater than 0.0 (type=value_error.number.not_gt; limit_value=0.0)

### Description

The latest NVCF endpoint now allows the temperature to be 0.  However, this wrapper does not allow this to happen, because of the pydantic default validator on the temperature field. 

### System Info

langchain==0.1.5
langchain-community==0.0.17
langchain-core==0.1.18
langchain-nvidia-ai-endpoints==0.0.1
langchain-openai==0.0.5

platform mac 
Python 3.11

**Comment by VKudlay** [comment]
@psgundecha-nv Thanks so much for bringing this up! 
- Issue resolved by #17290 
- Published to v0.0.3 by #17345 
Should be good to close.
