### ISSUE TITLE
handling context length in chromadb

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17298]
### Issue with current documentation:

below's the code

```
class MyTextSplitter(RecursiveCharacterTextSplitter):
    def split_documents(self, documents):
        chunks = super().split_documents(documents)
        for document, chunk in zip(documents, chunks):
            chunk.metadata['source'] = document.metadata['source']
        return chunks

text_splitter = MyTextSplitter(chunk_size=500,
                                chunk_overlap=50)

texts = text_splitter.split_documents(documents)

vectorstore = Chroma.from_documents(texts, embeddings)
```

I'm looking for assistance in utilizing the MyTextSplitter function specifically for cases where the text surpasses OpenAI's maximum character limit. The objective is to divide the text into smaller segments when it's too lengthy, and subsequently, if any segment includes or constitutes an answer, these segments should be reassembled into a cohesive response before being delivered.  I want to check if each document's page_content exceeds the maximum context length allowed by OpenAI Embeddings. For documents where page_content is longer than this limit, I intend to use a function named MyTextSplitter to divide the page_content into smaller sections. After splitting, these sections should be incorporated back into the respective documents, effectively replacing the original, longer page_content with the newly segmented texts. Can you provide code for me?

**Comment by eyurtsev** [comment]
Please use QA discussions to ask usage questions
