### ISSUE TITLE
unable to apply the same code on Chroma db which i've used for FAISS

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17292]
### Issue with current documentation:

below's the FAISS code which i tried to run on for chromadb too, but its not working

```
# Instantiate the OpenAIEmbeddings class
openai = OpenAIEmbeddings(openai_api_key="")

# Generate embeddings for your documents
embeddings = openai.embed_documents([doc.page_content for doc in documents])

# Create tuples of text and corresponding embedding
text_embeddings = list(zip([doc.page_content for doc in documents], embeddings))

# Create a FAISS vector store from the embeddings
vectorStore = FAISS.from_embeddings(text_embeddings, openai)
```

below's the code for chromadb

```
# Instantiate the OpenAIEmbeddings class
openai = OpenAIEmbeddings(openai_api_key="")

# Generate embeddings for your documents
embeddings = openai.embed_documents([doc.page_content for doc in documents])

# Create tuples of text and corresponding embedding
text_embeddings = list(zip([doc.page_content for doc in documents], embeddings))

# Create a FAISS vector store from the embeddings
vectorstore = Chroma.from_embeddings(text_embeddings, openai)
```

the error is below

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-57-81938d77957d>](https://localhost:8080/#) in <cell line: 11>()
      9 
     10 # Create a FAISS vector store from the embeddings
---> 11 vectorstore = Chroma.from_embeddings(text_embeddings, openai)

AttributeError: type object 'Chroma' has no attribute 'from_embeddings'
```

can you help me out on how to resolve this issue which i'm facing with chromadb?

**Comment by nithinreddyyyyyy** [comment]
> embed_documents

but the code which you gave is not utlizing embed_documents function which will overcome the texts longer than the maximum context. will you update the code which will utilize embed_documents function as well?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey @nithinreddyyyyyy, great to see you back! Ran into another challenge, I see? Let's take a look at what's going on with your ChromaDB issue.
> 
> Based on the error message you provided, it seems like you're trying to use a method `from_embeddings` that doesn't exist in the `Chroma` class. The `Chroma` class in LangChain does not have a `from_embeddings` method like the `FAISS` class does.
> 
> However, the `Chroma` class does provide methods to create a vector store from raw texts or documents. You can use the `from_texts` and `from_documents` class methods to achieve this. If an embedding function is provided, these methods will generate embeddings for the given texts or documents and add them to the vector store.
> 
> Here's an example of how you can use these methods:
> 
> ```python
> from langchain.vectorstores import Chroma
> from langchain.embeddings.openai import OpenAIEmbeddings
> 
> # Instantiate the OpenAIEmbeddings class
> openai = OpenAIEmbeddings(openai_api_key="")
> 
> # Generate embeddings for your documents
> documents = [doc.page_content for doc in documents]
> 
> # Create a Chroma vector store from the documents
> vectorstore = Chroma.from_documents(documents, openai)
> ```
> 
> In this example, the `from_documents` method is used to create a Chroma vector store from the documents. The `openai` instance is passed as the embedding function, which will be used to generate embeddings for the documents.
> 
> Please note that the `from_documents` method expects the documents to be instances of the `Document` class from the `langchain.documents` module. If your documents are raw texts, you can use the `from_texts` method instead.
> 
> I hope this helps! If you have any other questions or run into any issues, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/vectorstores/chroma.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/chroma.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

but the code which you gave is not utlizing embed_documents function which will overcome the texts longer than the maximum context. will you update the code which will utilize embed_documents function as well?

**Comment by nithinreddyyyyyy** [comment]
> ```python
> embed_documents
> ```

it is returning below error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-81-029281717453>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Create a Chroma vector store from the documents
----> 8 vectorstore = Chroma.from_documents(documents, openai.embed_documents)

2 frames
[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in from_documents(cls, documents, embedding, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    776         texts = [doc.page_content for doc in documents]
    777         metadatas = [doc.metadata for doc in documents]
--> 778         return cls.from_texts(
    779             texts=texts,
    780             embedding=embedding,

[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in from_texts(cls, texts, embedding, metadatas, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    734                 documents=texts,
    735             ):
--> 736                 chroma_collection.add_texts(
    737                     texts=batch[3] if batch[3] else [],
    738                     metadatas=batch[2] if batch[2] else None,

[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in add_texts(self, texts, metadatas, ids, **kwargs)
    273         texts = list(texts)
    274         if self._embedding_function is not None:
--> 275             embeddings = self._embedding_function.embed_documents(texts)
    276         if metadatas:
    277             # fill metadatas with empty dicts if somebody

AttributeError: 'function' object has no attribute 'embed_documents'
```

Can you help me out with this? Else there any way you can manually write a function which will handle the context length?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> I see your concern about handling texts longer than the maximum context. The `embed_documents` function in LangChain is designed to handle this by splitting the text into chunks that fit within the model's maximum token limit, embedding each chunk separately, and then averaging the embeddings to get a single vector for the entire text.
> 
> However, the `from_documents` method in the `Chroma` class does not directly use the `embed_documents` function. Instead, it uses the `add_texts` method, which in turn uses the `embed` function from the `Embeddings` class. This function does not handle texts longer than the maximum context.
> 
> To handle texts longer than the maximum context, you can modify the `add_texts` method in the `Chroma` class to use the `embed_documents` function. Here's how you can do it:
> 
> ```python
> from langchain.vectorstores import Chroma
> from langchain.embeddings.openai import OpenAIEmbeddings
> 
> # Instantiate the OpenAIEmbeddings class
> openai = OpenAIEmbeddings(openai_api_key="")
> 
> # Generate embeddings for your documents
> documents = [doc.page_content for doc in documents]
> 
> # Create a Chroma vector store from the documents
> vectorstore = Chroma.from_documents(documents, openai.embed_documents)
> ```
> 
> In this updated code, the `embed_documents` function is passed as the embedding function when creating the Chroma vector store. This function will be used by the `add_texts` method to generate embeddings for the texts, handling texts longer than the maximum context.
> 
> Please note that this modification requires changing the `add_texts` method in the `Chroma` class, which might not be ideal if you want to keep the original functionality of the class. Also, keep in mind that the `embed_documents` function has a maximum context length of 8191 tokens, as specified in the `OpenAIEmbeddings` class.
> 
> I hope this helps! If you have any other questions or run into any issues, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/vectorstores/chroma.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/chroma.py)
> * [libs/community/langchain_community/embeddings/openai.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/embeddings/openai.py)
> 
> #### About [Dosu](https://dosu.dev)
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> ## Sources
> * [ Issue: from_documents error  ](https://github.com/langchain-ai/langchain/issues/7119)
> * [libs/community/langchain_community/vectorstores/chroma.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/chroma.py)
> * [libs/community/langchain_community/embeddings/openai.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/embeddings/openai.py)
> 
> #### About Dosu

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-81-029281717453>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 # Create a Chroma vector store from the documents
----> 8 vectorstore = Chroma.from_documents(documents, openai.embed_documents)

2 frames
[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in from_documents(cls, documents, embedding, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    776         texts = [doc.page_content for doc in documents]
    777         metadatas = [doc.metadata for doc in documents]
--> 778         return cls.from_texts(
    779             texts=texts,
    780             embedding=embedding,

[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in from_texts(cls, texts, embedding, metadatas, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    734                 documents=texts,
    735             ):
--> 736                 chroma_collection.add_texts(
    737                     texts=batch[3] if batch[3] else [],
    738                     metadatas=batch[2] if batch[2] else None,

[/usr/local/lib/python3.10/dist-packages/langchain_community/vectorstores/chroma.py](https://localhost:8080/#) in add_texts(self, texts, metadatas, ids, **kwargs)
    273         texts = list(texts)
    274         if self._embedding_function is not None:
--> 275             embeddings = self._embedding_function.embed_documents(texts)
    276         if metadatas:
    277             # fill metadatas with empty dicts if somebody

AttributeError: 'function' object has no attribute 'embed_documents'
```

Can you help me out with this? Else there any way you can manually write a function which will handle the context length?

**Comment by eyurtsev** [comment]
Please use QA discussions to ask usage questions
