### ISSUE TITLE
handle context length in chroma db

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17299]
### Issue with current documentation:

below's the code

```
class MyTextSplitter(RecursiveCharacterTextSplitter):
    def split_documents(self, documents):
        chunks = super().split_documents(documents)
        for document, chunk in zip(documents, chunks):
            chunk.metadata['source'] = document.metadata['source']
        return chunks

text_splitter = MyTextSplitter(chunk_size=500,
                                chunk_overlap=50)

texts = text_splitter.split_documents(documents)

vectorstore = Chroma.from_documents(texts, embeddings)
```

I'm looking for assistance in utilizing the MyTextSplitter function specifically for cases where the text surpasses OpenAI's maximum character limit. Note: i want to use MyTextSplitter function only for documents page_content which are surpassing OpenAI's maximum character limit, not for all the document page_content data. The objective is to divide the text into smaller segments when it's too lengthy, and subsequently, if any segment includes or constitutes an answer, these segments should be reassembled into a cohesive response before being delivered. I want to check if each document's page_content exceeds the maximum context length allowed by OpenAI Embeddings. For documents where page_content is longer than this limit, I intend to use a function named MyTextSplitter to divide the page_content into smaller sections. After splitting, these sections should be incorporated back into the respective documents, effectively replacing the original, longer page_content with the newly segmented texts. Can you provide code for me?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey there, @nithinreddyyyyyy! Great to see you back with another intriguing challenge. Let's dive into it.
> 
> Based on your requirements, you can modify the `MyTextSplitter` class to only split documents whose `page_content` exceeds OpenAI's maximum token limit. Here's how you can do it:
> 
> ```python
> from langchain.text_splitter import RecursiveCharacterTextSplitter, Document
> from typing import Iterable, List
> 
> class MyTextSplitter(RecursiveCharacterTextSplitter):
>     def split_documents(self, documents: Iterable[Document]) -> List[Document]:
>         chunks = []
>         for document in documents:
>             if len(document.page_content) > OPENAI_MAX_TOKEN_LIMIT:  # Add this condition
>                 chunks.extend(super().split_documents([document]))
>             else:
>                 chunks.append(document)
>         return chunks
> ```
> 
> In the above code, `OPENAI_MAX_TOKEN_LIMIT` is the maximum token limit defined by OpenAI. You need to replace it with the actual limit. As per the LangChain framework, the maximum number of tokens to embed at once is set to 8191. So, you can set `OPENAI_MAX_TOKEN_LIMIT` to 8191.
> 
> To reassemble the split segments into a cohesive response, you can create a new function that takes a list of documents (split segments) and joins their `page_content` with a specified separator:
> 
> ```python
> def reassemble_segments(self, documents: List[Document], separator: str = ' ') -> str:
>     return separator.join(doc.page_content for doc in documents)
> ```
> 
> In the above code, `documents` is a list of split segments and `separator` is the string that separates the segments. The function returns the reassembled text.
> 
> Please note that the number of characters in a token can vary, so the maximum character limit can vary depending on the text being processed. You might need to adjust the `OPENAI_MAX_TOKEN_LIMIT` based on your specific use case.
> 
> You can find more details about the `TextSplitter` class and its methods in the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/text_splitter.py).
> 
> I hope this helps! If you have any further questions, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/text_splitter.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/text_splitter.py)
> * [libs/partners/openai/langchain_openai/embeddings/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/partners/openai/langchain_openai/embeddings/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Can you give an example of code how to utilize the functions MyTextSplitter and reassemble_segments which you've given and index the data into Chromadb?

**Comment by eyurtsev** [comment]
Please use QA discussions to ask usage questions
