### ISSUE TITLE
Include ChatGPT Turbo model in the Chain (Summarization)

### ISSUE THREAD

**Issue by nsankar** [langchain-ai/langchain#1730]
Please include  ChatGPT Turbo's ChatOpenAI  object to be passed as an LLM completion in the Summarizer chain.
_(from langchain.chat_models.openai import ChatOpenAI)_

for the following usage
`summary_chain = load_summarize_chain(llm, chain_type="map_reduce")
summarize_document_chain = AnalyzeDocumentChain(combine_docs_chain=summary_chain)`

**Comment by hwchase17** [comment]
im assuming you mean update the typing?

**Comment by FergusFettes** [comment]
If you are desperate to get this working, you can cherrypick the commit I made here: https://github.com/hwchase17/langchain/pull/1826

Then you can use turbo and gpt4 for chains etc.
