### ISSUE TITLE
Async generator function fails when wrapped in a Runnable Lambda and used in streaming

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#17315]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

The following code fails during iteration if the custom_parser is explicitly wrapped in a RunnableLambda.

```python
from langchain_openai import ChatOpenAI
from langchain.pydantic_v1 import BaseModel, Field
from typing import List, Optional
from langchain_core.runnables import RunnableLambda

model = ChatOpenAI()

class UserInfo(BaseModel):
    """Information to extract from the user's input"""
    name: Optional[str] = Field(description = "Name of user")
    facts: List[str] = Field(description="List of facts about the user")


model_with_tools = model.bind_tools([UserInfo])

async def custom_parser(chunk_stream):
    aggregated_message = None
    async for chunk in chunk_stream:
        if aggregated_message is None:
            aggregated_message = chunk
        else:
            aggregated_message += chunk
            
        yield aggregated_message.additional_kwargs['tool_calls'][0]['function']
custom_parser = RunnableLambda(custom_parser)
chain = model_with_tools | custom_parser


async for chunk in chain.astream('my name is eugene and i like cats and dogs'):
    print(chunk)
```

Need to investigate if this is a bug or bad UX

**Comment by eyurtsev** [comment]
Another related issue: 

```
from langchain_core.output_parsers import JsonOutputParser

def stream_json(inputs):
    import json
    s = json.dumps({'a': 'b', 'c': 5})
    yield from s
    

chain = stream_json | JsonOutputParser()

for c in chain.stream({}):
    print(c)


## Breaks

async for c in chain.astream({}):
    print(c)
```

**Comment by ccurme** [comment]
For the first issue, I think this comes down to how RunnableLambda behaves with streaming input, which is to immediately consume the input before calling its function on the result:
https://github.com/langchain-ai/langchain/blob/1d2aa19aeeca94f21b01c1f3ada6eb5e2defca23/libs/core/langchain_core/runnables/base.py#L3618-L3633
So here the generator that comes into `_atransform` gets accumulated into an AIMessageChunk, which can no longer be iterated through. In this particular case, you could leave it as a generator to keep the desired behavior.

Whether this is made clear to users is another question. It's documented somewhat under the `_extract_country_names` examples [here](https://python.langchain.com/docs/expression_language/streaming#working-with-input-streams). Wrapping a generator in a RunnableLambda is also discussed more explicitly in the API reference [here](https://api.python.langchain.com/en/latest/runnables/langchain_core.runnables.base.RunnableGenerator.html#) (see also associated discussion in the [PR](https://github.com/langchain-ai/langchain/pull/16672) for that reference).

One option could be to raise a warning based on introspection of the input type, or to make this more explicit in the streaming documentation. Let me know what you think.
