### ISSUE TITLE
returning duplicates while retrieving the top k documents

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17310]
### Issue with current documentation:

below's the code

```
llm = OpenAI(temperature=0.2)

# Create a retriever for the vector database
document_content_description = "Description of a corporate document."

metadata_field_info = [
    {
        "name": "document_type",
        "description": "The type of document, such as policy statement, modern slavery statement, human rights due diligence manual.",
        "type": "string",
    },
    {
        "name": "company_name",
        "description": "The name of the company that the document pertains to.",
        "type": "string",
    },
]

retriever = SelfQueryRetriever.from_llm(
llm,
vectorstore,
document_content_description,
metadata_field_info,
use_original_query=False,
enable_limit=True,
verbose=True
)

structured_query = StructuredQuery(
    query="related to BCCI company",
    # query = "data related to ABinbev",
    limit=3  # Set the number of documents to retrieve
)

docs = retriever.get_relevant_documents(structured_query)

print(docs)
```

below's the output

```
[Document(page_content='BCCI is a cricket board that controls and manages the activities in India', metadata={'row': 0, 'source': '/content/files/19.csv'}),
 Document(page_content='BBCI is a cricket board in India', metadata={'row': 36, 'source': '/content/files/23.csv'}),
 Document(page_content='BCCI is a cricket board that controls and manages the activities in India.', metadata={'row': 14, 'source': '/content/files/11.csv'})]
```

1st and 3rd output page_content is same, how to do deduplication and make sure its retrieving top k unique documents?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hey @nithinreddyyyyyy! Great to see you back here 🚀. How's everything going with your coding adventures? 🧙‍♂️
> 
> Based on the code you've shared, it seems like the `get_relevant_documents` method in the `SelfQueryRetriever` class is returning the top k documents based on their relevance to the query, without checking for uniqueness. This could be why you're seeing duplicates in the results.
> 
> To ensure that the retriever is returning the top k unique documents, you can modify the `get_relevant_documents` method in your local copy of the LangChain code. Here's how you can do it:
> 
> ```python
> def get_relevant_documents(self, query: str) -> List[Document]:
>     from sklearn.metrics.pairwise import cosine_similarity
> 
>     # Ip -- (n_docs,x), Op -- (n_docs,n_Feats)
>     query_vec = self.vectorizer.transform([query])
>     # Op -- (n_docs,1) -- Cosine Sim with each doc
>     results = cosine_similarity(self.tfidf_array, query_vec).reshape((-1,))
> 
>     # Initialize a set to keep track of unique documents
>     unique_docs = set()
>     # Initialize a list to store the unique documents
>     unique_results = []
> 
>     # Iterate over the documents in descending order of similarity
>     for i in results.argsort()[::-1]:
>         doc = self.docs[i]
>         # Only add the document to the result if it's not already in the set
>         if doc not in unique_docs:
>             unique_results.append(doc)
>             unique_docs.add(doc)
>         # Stop when we have found k unique documents
>         if len(unique_results) == self.k:
>             break
> 
>     return unique_results
> ```
> 
> This modification ensures that the `get_relevant_documents` method returns the top k unique documents. It first checks if a document is in the `unique_docs` set before adding it to the `unique_results` list. If the document is already in the set, it skips to the next document. It stops when it has found k unique documents.
> 
> Please note that this is a workaround and might not be the most efficient solution. It would be better if the LangChain library itself provided a way to handle duplicate documents. You might want to consider opening an issue in the LangChain repository to suggest this feature.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> [Source](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> 
> ## Sources
> * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Can you also return the code how to utilize the function which you gave?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Sure, I can help with that. Here's how you can utilize the modified `get_relevant_documents` function:
> 
> First, you need to create a new class that inherits from `SelfQueryRetriever` and overrides the `get_relevant_documents` method with the modified version:
> 
> ```python
> from langchain_core.retrievers import SelfQueryRetriever
> from typing import List
> from langchain_core.documents import Document
> from sklearn.metrics.pairwise import cosine_similarity
> 
> class UniqueSelfQueryRetriever(SelfQueryRetriever):
>     def get_relevant_documents(self, query: str) -> List[Document]:
>         # Ip -- (n_docs,x), Op -- (n_docs,n_Feats)
>         query_vec = self.vectorizer.transform([query])
>         # Op -- (n_docs,1) -- Cosine Sim with each doc
>         results = cosine_similarity(self.tfidf_array, query_vec).reshape((-1,))
> 
>         # Initialize a set to keep track of unique documents
>         unique_docs = set()
>         # Initialize a list to store the unique documents
>         unique_results = []
> 
>         # Iterate over the documents in descending order of similarity
>         for i in results.argsort()[::-1]:
>             doc = self.docs[i]
>             # Only add the document to the result if it's not already in the set
>             if doc not in unique_docs:
>                 unique_results.append(doc)
>                 unique_docs.add(doc)
>             # Stop when we have found k unique documents
>             if len(unique_results) == self.k:
>                 break
> 
>         return unique_results
> ```
> 
> Then, you can use this new class `UniqueSelfQueryRetriever` instead of `SelfQueryRetriever` when creating the retriever:
> 
> ```python
> retriever = UniqueSelfQueryRetriever.from_llm(
>     llm,
>     vectorstore,
>     document_content_description,
>     metadata_field_info,
>     use_original_query=False,
>     enable_limit=True,
>     verbose=True
> )
> ```
> 
> The rest of your code can remain the same. Now, when you call `retriever.get_relevant_documents(structured_query)`, it should return the top k unique documents.
> 
> Please note that this is a workaround and might not be the most efficient solution. It would be better if the LangChain library itself provided a way to handle duplicate documents. You might want to consider opening an issue in the LangChain repository to suggest this feature.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> [Source](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> 
> ## Sources
> * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> 
> #### About [Dosu](https://dosu.dev)
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
> 
> ## Sources
> * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> * [libs/core/langchain_core/documents/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/documents/base.py)
> 
> #### About Dosu

below's the error which i got

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-12-a378fe4299ae>](https://localhost:8080/#) in <cell line: 9>()
      7 print(structured_query)
      8 
----> 9 docs = retriever.get_relevant_documents(structured_query)

2 frames
[/usr/local/lib/python3.10/dist-packages/langchain_core/retrievers.py](https://localhost:8080/#) in get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    222         except Exception as e:
    223             run_manager.on_retriever_error(e)
--> 224             raise e
    225         else:
    226             run_manager.on_retriever_end(

[/usr/local/lib/python3.10/dist-packages/langchain_core/retrievers.py](https://localhost:8080/#) in get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    219                 )
    220             else:
--> 221                 result = self._get_relevant_documents(query, **_kwargs)
    222         except Exception as e:
    223             run_manager.on_retriever_error(e)

[<ipython-input-10-3f1bff2ffc6d>](https://localhost:8080/#) in get_relevant_documents(self, query)
     17     def get_relevant_documents(self, query: str) -> List[Document]:
     18         # Ip -- (n_docs,x), Op -- (n_docs,n_Feats)
---> 19         query_vec = self.vectorizer.transform([query])
     20         # Op -- (n_docs,1) -- Cosine Sim with each doc
     21         results = cosine_similarity(self.tfidf_array, query_vec).reshape((-1,))

AttributeError: 'UniqueSelfQueryRetriever' object has no attribute 'vectorizer'
```

can you help me out with this?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> > _🤖_
> > I apologize for the confusion. It seems like the `vectorizer` and `tfidf_array` attributes are not available in the `SelfQueryRetriever` class. My previous suggestion was based on a misunderstanding of the LangChain codebase.
> > The `SelfQueryRetriever` class in LangChain does not use a TF-IDF vectorizer to transform the queries and documents into vectors. Instead, it uses a language model to generate the vector store queries and a vector store to retrieve the documents. Therefore, the `vectorizer` and `tfidf_array` attributes do not exist in the `SelfQueryRetriever` class.
> > Unfortunately, without access to the internal workings of the `SelfQueryRetriever` class and the vector store, it's not possible to modify the `get_relevant_documents` method to return unique documents as I previously suggested.
> > However, you can perform a post-processing step to remove duplicates from the retrieved documents based on their content. Here's how you can do it:
> > ```python
> > def remove_duplicates(documents):
> >     seen = set()
> >     unique_docs = []
> >     for doc in documents:
> >         if doc.page_content not in seen:
> >             unique_docs.append(doc)
> >             seen.add(doc.page_content)
> >     return unique_docs
> > 
> > # Use the remove_duplicates function to remove duplicates from the retrieved documents
> > unique_docs = remove_duplicates(docs)
> > print(unique_docs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This function iterates over the retrieved documents and only adds a document to the `unique_docs` list if its content is not already in the `seen` set. This ensures that the `unique_docs` list only contains unique documents.
> > I hope this helps! If you have any other questions, feel free to ask.
> > [Source](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> > ## Sources
> > 
> > * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> > * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> > 
> > #### About [Dosu](https://dosu.dev)
> > This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> > Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> > If you want to continue the conversation, start your reply with @dosu-bot.
> > ## Sources
> > 
> > * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> > * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> > * [libs/core/langchain_core/documents/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/documents/base.py)
> 
> ## Sources
> * [SelfQueryRetriever returns duplicate document data using with chromaDB](https://github.com/langchain-ai/langchain/issues/9532)
> * [libs/langchain/langchain/retrievers/self_query/base.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py)
> * [libs/langchain/langchain/chains/query_constructor/ir.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/query_constructor/ir.py)
> 
> #### About Dosu

In the code above, it'll just remove the duplicates and returns the unique data. I need a script that fetches the top k documents in a way that avoids these duplications. For example, if we request the top 5 documents (k=5) and find that there are 2 duplicates among them, the script should discard the duplicates and instead retrieve additional unique documents to ensure we still receive a total of 5 unique documents. Essentially, if duplicates are found within the initially requested top documents, the script should continue to fetch the next highest-ranked document(s) until we have 5 unique page_contents. Can you provide a code that accomplishes this?

**Comment by kanzyai-emirarditi** [comment]
I think this issue needs to stay open and needs further attention. The solution provided by dosubot does not work and getting unique documents is an important functionality. If Chroma does not provide it, we should have the option to do it on self retriever with a code like dosubot suggested

**Comment by Adefioye** [comment]
![image](https://github.com/langchain-ai/langchain/assets/47661641/1ee8e774-8981-4120-b58a-7c8be6bed0da)

This continues to be a problem. the top k documents from the retriever is generating non-unique document objects. It will be nice to fix this issue.

**Comment by parsa-pico** [comment]
Haven't they fixed this yet?

**Comment by ysinsane** [comment]
> ### Issue with current documentation:
> below's the code
> 
> ```
> llm = OpenAI(temperature=0.2)
> 
> # Create a retriever for the vector database
> document_content_description = "Description of a corporate document."
> 
> metadata_field_info = [
>     {
>         "name": "document_type",
>         "description": "The type of document, such as policy statement, modern slavery statement, human rights due diligence manual.",
>         "type": "string",
>     },
>     {
>         "name": "company_name",
>         "description": "The name of the company that the document pertains to.",
>         "type": "string",
>     },
> ]
> 
> retriever = SelfQueryRetriever.from_llm(
> llm,
> vectorstore,
> document_content_description,
> metadata_field_info,
> use_original_query=False,
> enable_limit=True,
> verbose=True
> )
> 
> structured_query = StructuredQuery(
>     query="related to BCCI company",
>     # query = "data related to ABinbev",
>     limit=3  # Set the number of documents to retrieve
> )
> 
> docs = retriever.get_relevant_documents(structured_query)
> 
> print(docs)
> ```
> 
> below's the output
> 
> ```
> [Document(page_content='BCCI is a cricket board that controls and manages the activities in India', metadata={'row': 0, 'source': '/content/files/19.csv'}),
>  Document(page_content='BBCI is a cricket board in India', metadata={'row': 36, 'source': '/content/files/23.csv'}),
>  Document(page_content='BCCI is a cricket board that controls and manages the activities in India.', metadata={'row': 14, 'source': '/content/files/11.csv'})]
> ```
> 
> 1st and 3rd output page_content is same, how to do deduplication and make sure its retrieving top k unique documents?
> 
> ### Idea or request for content:
> _No response_

how did you save data to your vector store? It is likely that you save dulplicates to the DB by invoking this too many times while debuging:
vectordb = Chroma.from_documents(documents=all_splits, embedding=hf, persist_directory="./chroma_db")
