### ISSUE TITLE
list index out of range error if similarity search gives 0 docs

### ISSUE THREAD

**Issue by sheikalthaf** [langchain-ai/langchain#1733]
https://github.com/hwchase17/langchain/blob/276940fd9babf8aec570dd869cc84fbca1c766bf/langchain/vectorstores/milvus.py#L319

I'm using milvus where for my question I'm getting 0 documents and so index out of range error occurs

Error line:
https://github.com/hwchase17/langchain/blob/276940fd9babf8aec570dd869cc84fbca1c766bf/langchain/chains/llm.py#L95

**Comment by rchanggogogo** [comment]
> 19

Hi what's your input for llm and how do you build your chain, could you offer more information

**Comment by morganmcg1** [comment]
+1 getting this using the following:

```
from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI


llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)
chroma_retriever = db.as_retriever(k=3)

qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="map_reduce", 
                                    retriever=chroma_retriever,
```

**Comment by akash-ravikumar** [comment]
+1 on this error

**Comment by Jason-YCX** [comment]
> +1 on this error. I don't seem to be getting the error when the chain_type = 'stuff'. It comes up for map_reduce, map_rerank and refine.

Hello, is this problem solved?

**Comment by Sharvin26** [comment]
Is this fix available on the latest release?
