### ISSUE TITLE
Question about the Cosine distance strategy

### ISSUE THREAD

**Issue by rnyak** [langchain-ai/langchain#17333]
@eyurtsev hello. I'd like to ask a follow up question. the `COSINE` distance strategy is resulting in scores >1.. from this [code](https://github.com/langchain-ai/langchain/blob/023cb59e8aaf3dfaad684b3fcf57a1c363b9abd1/libs/core/langchain_core/vectorstores.py#L184C2-L188C1), it looks like scores returned are calculated from `1-distance`, meaning they are similarity scores, and cosine sim scores should be in [-1, 1] range. but I get scores >1.

is there a reason for that?  am I missing something in my implementation? thanks.

this is my code snippet

```
embedder = NVIDIAEmbeddings(model="nvolveqa_40k")
store = FAISS.from_documents(docs_split, embedder, distance_strategy=DistanceStrategy.COSINE)
query = "Who is the director of the Oppenheimer movie?"
docs_and_scores = store.similarity_search_with_score(query)
```

_Originally posted by @rnyak in https://github.com/langchain-ai/langchain/discussions/16224#discussioncomment-8413281_

**Comment by rnyak** [comment]
@dosubot thank you for your response. you are referring a different piece of code, where as I am referring this code:

```
    @staticmethod
    def _cosine_relevance_score_fn(distance: float) -> float:
        """Normalize the distance to a score on a scale [0, 1]."""

        return 1.0 - distance
```

This tells me what is returned as relevance score is `similarity score` already. How come a similarity score can be >1?

**Comment by WbaN314** [comment]
I just stumbled upon this and indeed, the LangChain implementation of _cosine_relevance_score_fn is mathematically wrong.

```Typescript
@staticmethod
def _cosine_relevance_score_fn(distance: float) -> float:
    """Normalize the distance to a score on a scale [0, 1]."""
    return 1.0 - distance
```

Cosine similarity is defined as the dot product of two vectors divided by the product of their lengths.

Therefore the cosine similarity of two vectors can range from -1 (vectors point in exactly opposite directions, i.e. (-1, 0) and (2, 0)) over 0 (vectors are orthogonal to each other, i.e. (1, 0) and (0, 2)) to 1 (vectors point in exactly the same direction, i.e. (1, 0) and (2, 0)).

Thus, the correct normalisation to the interval [0, 1] where 0 means most similar and 1 means least similar should be `1.0 - (distance + 1.0) / 2.0`.

In practice, this bug does probably not occur very often, as current embedding models often only use a small part of the available vectorspace for all embeddings where all used vectors have positive cosine similarity https://community.openai.com/t/some-questions-about-text-embedding-ada-002-s-embedding/35299/3. 

If future models use more of the available vectorspace, this bug will start to occur more frequently.

**Comment by SaschaStoll** [comment]
I just stumbled upon this and indeed, the LangChain implementation of _cosine_relevance_score_fn is mathematically wrong.

```Typescript
@staticmethod
def _cosine_relevance_score_fn(distance: float) -> float:
    """Normalize the distance to a score on a scale [0, 1]."""
    return 1.0 - distance
```

Cosine similarity is defined as the dot product of two vectors divided by the product of their lengths.

Therefore the cosine similarity of two vectors can range from -1 (vectors point in exactly opposite directions, i.e. (-1, 0) and (2, 0)) over 0 (vectors are orthogonal to each other, i.e. (1, 0) and (0, 2)) to 1 (vectors point in exactly the same direction, i.e. (1, 0) and (2, 0)).

Thus, the correct normalisation to the interval [0, 1] where 0 means most similar and 1 means least similar should be `1.0 - (distance + 1.0) / 2.0`.

In practice, this bug does probably not occur very often, as current embedding models often only use a small part of the available vectorspace for all embeddings where all used vectors have positive cosine similarity https://community.openai.com/t/some-questions-about-text-embedding-ada-002-s-embedding/35299/3. 

If future models use more of the available vectorspace, this bug will start to occur more frequently.
