### ISSUE TITLE
How to get IDs of documents stored in postgres pgvector 

### ISSUE THREAD

**Issue by deepak-hl** [langchain-ai/langchain#17361]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
pgvector = PGVector(...)  # Initialize PGVector with necessary parameters
ids_to_delete = [...]  # List of ids to delete
pgvector.delete(ids_to_delete)
```

### Description

I want to fetch ID's of a document stored in Postgres pgvector db to delete the particular document embeddings 

### System Info

I am using Postgres pgvector

**Comment by deepak-hl** [comment]
> _🤖_
> 
> Hey there @deepak-hl! 👋 Great to see you back. How have things been on your end? Let's take a look at what's going on with your pgvector query.
> 
> 
> Based on the information provided, it seems you're trying to retrieve the IDs of documents stored in a Postgres pgvector database using the LangChain framework. Unfortunately, there isn't a built-in method in LangChain to directly fetch these IDs. However, you can achieve this by using SQLAlchemy ORM session to query the `EmbeddingStore` model.
> 
> Here's a sample code snippet to retrieve all document IDs:
> 
> ```python
> from sqlalchemy.orm import Session
> from langchain_community.vectorstores.pgembedding import EmbeddingStore
> 
> def get_all_document_ids(self) -> List[str]:
>     with Session(self._conn) as session:
>         collection = self.get_collection(session)
>         if not collection:
>             raise ValueError("Collection not found")
>         document_ids = session.query(EmbeddingStore.custom_id).filter(EmbeddingStore.collection_id == collection.uuid).all()
>         return [id[0] for id in document_ids]
> ```
> 
> This function opens a new session, retrieves the current collection, and then queries the `EmbeddingStore` model for all `custom_id` values that belong to the current collection. The result is a list of tuples, so we use a list comprehension to extract the IDs into a list of strings.
> 
> To delete a specific document embedding, you can use the `session.delete()` method with the specific `EmbeddingStore` instance you want to delete. Here is a sample code snippet to delete a document by its ID:
> 
> ```python
> def delete_document_by_id(self, document_id: str) -> None:
>     with Session(self._conn) as session:
>         collection = self.get_collection(session)
>         if not collection:
>             raise ValueError("Collection not found")
>         document = session.query(EmbeddingStore).filter(EmbeddingStore.collection_id == collection.uuid, EmbeddingStore.custom_id == document_id).first()
>         if document:
>             session.delete(document)
>             session.commit()
> ```
> 
> This function opens a new session, retrieves the current collection, and then queries the `EmbeddingStore` model for the document with the given `custom_id` that belongs to the current collection. If such a document is found, it is deleted from the session and the session is committed to save the changes.
> 
> Please note that this is a workaround and not a built-in feature of LangChain. You might want to encapsulate these functions in a utility class or module in your application for better organization and reusability.
> 
> For more information, you can refer to the [LangChain repository](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/pgembedding.py) and the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/14/orm/session_basics.html).
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> ## Sources
> - [libs/community/langchain_community/vectorstores/pgembedding.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/pgembedding.py)
> 
> 
> <details open>
> <summary>
> 
> #### About Dosu
> </summary>
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
> </details>

Can I get the ID's using pyschopg2 by writing query??

**Comment by rarchitgupta** [comment]
@deepak-hl were you able to find a way to fetch the id's of the vector embeddings you want to delete based on the documents?

**Comment by jntsouza** [comment]
> > @deepak-hl were you able to find a way to fetch the id's of the vector embeddings you want to delete based on the documents?
> 
> Yes

How?

**Comment by rarchitgupta** [comment]
@jntsouza I'm not sure what worked for him, personally I added a vector ID to the metadata of each chunk using uuid, then stored the associated vector ID's with that particular document in a database. So every time I have to delete a document, I would fetch the associated vector IDs and delete them all from the vector store

**Comment by jntsouza** [comment]
> @jntsouza I'm not sure what worked for him, personally I added a vector ID to the metadata of each chunk using uuid, then stored the associated vector ID's with that particular document in a database. So every time I have to delete a document, I would fetch the associated vector IDs and delete them all from the vector store

I had the same idea, but my vector database already has a lot of data, so it would be better if I could retrieve them by metadata filter and get their IDs.
But it seems too hard to accomplish.
Thanks

**Comment by jntsouza** [comment]
> > @jntsouza I'm not sure what worked for him, personally I added a vector ID to the metadata of each chunk using uuid, then stored the associated vector ID's with that particular document in a database. So every time I have to delete a document, I would fetch the associated vector IDs and delete them all from the vector store
> 
> I had the same idea, but my vector database already has a lot of data, so it would be better if I could retrieve them by metadata filter and get their IDs. But it seems too hard to accomplish. Thanks

I could solve it, ex.:

Overriding PGVector
```

class CustomPGVector(PGVector):
    def get_all_document_ids(self, process_oid) -> List[str]:
        with Session(self._bind) as session:  # Use self._bind to create a session
            collection = self.get_collection(session)
            if not collection:
                raise ValueError("Collection not found")
            document_ids = session.query(self.EmbeddingStore.custom_id).filter(
                self.EmbeddingStore.collection_id == collection.uuid,
                self.EmbeddingStore.cmetadata['process_oid'].astext.cast(sqlalchemy.Integer) == process_oid
            ).all()
            return [id[0] for id in document_ids]
 
def get_pgvector_retriver3(context, collection_name: str) -> CustomPGVector:
    embeddings = ai.get_embeddings(context)
    connection = get_connection_string_vetordb()
    return CustomPGVector(
            embedding_function=embeddings,
            collection_name=collection_name,
            connection_string=connection,
            distance_strategy=DistanceStrategy.COSINE
        )
```

```
store = get_pgvector_retriver3(context, collection_name)
ids = store.get_all_document_ids(process_oid)
if len(ids):
      store.delete(ids)
```
