### ISSUE TITLE
Chain Serialization Support with Azure OpenAI LLMs

### ISSUE THREAD

**Issue by LaxmanSinghTomar** [langchain-ai/langchain#1736]
It's really useful to move away the prompts etc. from the main codebase. Currently, from the documentation and my own testing, seems that only those chains can be serialized that have OpenAI LLM (only `text-davinci-003`). But, no such support is available for Azure-based OpenAI LLMs (`text-davinci-003` and `gpt-3.5-turbo`).

Is my understanding correct? If yes, any plans on adding it soon?

**Comment by BaymaxBei** [comment]
I have the same question.
