### ISSUE TITLE
merge_dicts in _merge can't merge different values of instance float and raises a type error

### ISSUE THREAD

**Issue by rowanamgad** [langchain-ai/langchain#17376]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_google_vertexai import ChatVertexAI, VertexAI, VertexAIEmbeddings

llm_chain = LLMChain(llm=llm, prompt=prompt_template)
res = llm_chain.predict(user_prompt=user_prompt)

### Error Message and Stack Trace (if applicable)

Prompted _[llm/error] [1:chain:LLMChain > 2:llm:VertexAI] [4.64s] LLM run errored with error: "TypeError(\"Additional kwargs key Finance already exists in left dict and value has unsupported type <class 'float'>.\")Traceback (most  recent call last):

### Description

I'm trying to use text-unicorn model through vertex ai while setting the stream parameter to true. With every chunk generated by the llm, the generation_info dict contains key-value pairs where the key is the same but the value is different with every returned generation. Acoordingly a runtime error is raised and no propeper answer is returned from the llm.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.15
> langchain: 0.0.354
> langchain_community: 0.0.15
> langchain_benchmarks: 0.0.10
> langchain_experimental: 0.0.47
> langchain_google_genai: 0.0.2
> langchain_google_vertexai: 0.0.2
> langchainhub: 0.1.14

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by leonard-bc** [comment]
I am having similar issue but with the streaming functionality of ChatVertexAI. If I enable the streaming functionality in ChatVertexAI, I get the TypeError below:

TypeError: Additional kwargs key Finance already exists in left dict and value has unsupported type <class 'float'>.

**Comment by leomensah** [comment]
I am getting a similar TypeError message when I enable the streaming function in ChatVertexAI.

TypeError: Additional kwargs key Finance already exists in left dict and value has unsupported type <class 'float'>.

**Comment by skozlovf** [comment]
The same issue with `ChatVertexAI`. It fails on merging `ChatGenerationChunk` where `generation_info["'safety_attributes"]` has the same keys but different values - sometimes VertexAI returns different values for the same `safety_attributes`.

How to reproduce:
```python
from langchain_core.utils._merge import merge_dicts

chunk1_gen_info = {"is_blocked": False, "safety_attributes": {"Health": 0.5, "Illicit Drugs": 0.1, "Legal": 0.1}}
chunk2_gen_info = {"is_blocked": False, "safety_attributes": {"Health": 0.5, "Illicit Drugs": 0.2, "Legal": 0.1}}
merge_dicts(chunk1_gen_info, chunk2_gen_info)
```
Note that `Illicit Drugs` has different values.

Simplified version:
```python
from langchain_core.utils._merge import merge_dicts
merge_dicts({"a": 1}, {"a": 2})
```

`merge_dicts` works incorrectly in other cases too:
```python
assert merge_dicts({"a": None}, {"a": 0}) == {"a": 0}  # TypeError
```

**Comment by skozlovf** [comment]
[Looks like](https://cloud.google.com/vertex-ai/docs/generative-ai/learn/streaming#sdk) `VertexAI` generates safety attributes for each chunk and `ChatGenerationChunk/merge_dicts` doesn't support that.
Also @baskaryan wrote https://github.com/langchain-ai/langchain/pull/16605#pullrequestreview-1876893433:
> we intentionally don't support ints as it's not clear how to merge them. in this case you would just be overwriting past ints. a better solution would be to update the dicts that are streaming to return something mergeable, like a list of ints

Related issues: #16605, #17105.
