### ISSUE TITLE
gRPC error with Milvus retriever

### ISSUE THREAD

**Issue by Moeinmn** [langchain-ai/langchain#17371]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_community.vectorstores import Milvus

vector_db = Milvus.from_texts(
    texts=str_list,
    embedding=embeddings,
    connection_args={
        "uri": "zilliz_cloud_uri",
        "token": "zilliz_cloud_token"
    },
)
```

### Error Message and Stack Trace (if applicable)

E0210 23:13:44.149694000 8088408832 hpack_parser.cc:993]               Error parsing 'content-type' metadata: invalid value
[__internal_register] retry:4, cost: 0.27s, reason: <_InactiveRpcError: StatusCode.UNKNOWN, Stream removed>
<img width="1440" alt="Screenshot 1402-11-21 at 23 20 28" src="https://github.com/langchain-ai/langchain/assets/69215813/22e7e225-848f-4689-a413-e2ef8e9998b2">

### Description
OS== macOS 14

pymilvus==2.3.4
langchain==0.1.3
langchain-community==0.0.15
pyarrow>=12.0.0

NOTE: pyarrow must be installed manually .otherwise code will throw error
=========================

I am using Milvus module from langchain_community as vector database. Code seem to have gRPC related errors in local environment. moreover , within colab environment I'am facing this error : 

```python
    584             end = min(i + batch_size, total_count)
    585             # Convert dict to list of lists batch for insertion
--> 586             insert_list = [insert_dict[x][i:end] for x in self.fields]
    587             # Insert into the collection.
    588             try:

KeyError: 'year'
```

Error is from :
  File "/Users/moeinmn/anaconda3/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 904, in from_texts
    vector_db = cls(
                ^^^^
  File "/Users/moeinmn/anaconda3/lib/python3.11/site-packages/langchain_community/vectorstores/milvus.py", line 179, in __init__
    self.alias = self._create_connection_alias(connection_args)

### System Info

langchain==0.1.3
langchain-community==0.0.15
pymilvus==2.3.4

**Comment by ohbeep** [comment]
@Moeinmn Use `user` and `password` instead of the `token` field should fix your issue:
```python
vector_db = Milvus.from_texts(
    texts=str_list,
    embedding=embeddings,
    connection_args={
        "uri": "zilliz_cloud_uri",
        "user": "zilliz_cloud_user",
        "password": "zilliz_cloud_password",
    },
)
```
