### ISSUE TITLE
MultiQueryRetriever with bedrock claude

### ISSUE THREAD

**Issue by HannaHUp** [langchain-ai/langchain#17382]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain.llms.bedrock import Bedrock
temperature = 0.0
model_id="anthropic.claude-v2"
model_params={
                        "max_tokens_to_sample": 2000,
                        "temperature": temperature,
                        "stop_sequences": ["\n\nHuman:"]}

llm  = Bedrock(model_id=model_id,
                   client=boto3_bedrock,
                   model_kwargs=model_params
                  )

retriever = MultiQueryRetriever.from_llm(
    retriever=db.as_retriever(), llm=llm
)

question = "tell me about llama 2?"

docs = retriever.get_relevant_documents(query=question)
len(docs)

### Error Message and Stack Trace (if applicable)

--------------------------------------------------------------------------
ValidationException                       Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:121, in BedrockEmbeddings._embedding_func(self, text)
    120 try:
--> 121     response = self.client.invoke_model(
    122         body=body,
    123         modelId=self.model_id,
    124         accept="application/json",
    125         contentType="application/json",
    126     )
    127     response_body = json.loads(response.get("body").read())

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:535, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    534 # The "self" in this scope is referring to the BaseClient.
--> 535 return self._make_api_call(operation_name, kwargs)

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:980, in BaseClient._make_api_call(self, operation_name, api_params)
    979     error_class = self.exceptions.from_code(error_code)
--> 980     raise error_class(parsed_response, operation_name)
    981 else:

ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: expected minLength: 1, actual: 0, please reformat your input and try again.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[17], line 3
      1 question = "tell me about llama 2?"
----> 3 docs = retriever.get_relevant_documents(query=question)
      4 len(docs)

File /opt/conda/lib/python3.10/site-packages/langchain/schema/retriever.py:211, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    209 except Exception as e:
    210     run_manager.on_retriever_error(e)
--> 211     raise e
    212 else:
    213     run_manager.on_retriever_end(
    214         result,
    215         **kwargs,
    216     )

File /opt/conda/lib/python3.10/site-packages/langchain/schema/retriever.py:204, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    202 _kwargs = kwargs if self._expects_other_args else {}
    203 if self._new_arg_supported:
--> 204     result = self._get_relevant_documents(
    205         query, run_manager=run_manager, **_kwargs
    206     )
    207 else:
    208     result = self._get_relevant_documents(query, **_kwargs)

File /opt/conda/lib/python3.10/site-packages/langchain/retrievers/multi_query.py:163, in MultiQueryRetriever._get_relevant_documents(self, query, run_manager)
    154 """Get relevant documents given a user query.
    155 
    156 Args:
   (...)
    160     Unique union of relevant documents from all generated queries
    161 """
    162 queries = self.generate_queries(query, run_manager)
--> 163 documents = self.retrieve_documents(queries, run_manager)
    164 return self.unique_union(documents)

File /opt/conda/lib/python3.10/site-packages/langchain/retrievers/multi_query.py:198, in MultiQueryRetriever.retrieve_documents(self, queries, run_manager)
    196 documents = []
    197 for query in queries:
--> 198     docs = self.retriever.get_relevant_documents(
    199         query, callbacks=run_manager.get_child()
    200     )
    201     documents.extend(docs)
    202 return documents

File /opt/conda/lib/python3.10/site-packages/langchain/schema/retriever.py:211, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    209 except Exception as e:
    210     run_manager.on_retriever_error(e)
--> 211     raise e
    212 else:
    213     run_manager.on_retriever_end(
    214         result,
    215         **kwargs,
    216     )

File /opt/conda/lib/python3.10/site-packages/langchain/schema/retriever.py:204, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    202 _kwargs = kwargs if self._expects_other_args else {}
    203 if self._new_arg_supported:
--> 204     result = self._get_relevant_documents(
    205         query, run_manager=run_manager, **_kwargs
    206     )
    207 else:
    208     result = self._get_relevant_documents(query, **_kwargs)

File /opt/conda/lib/python3.10/site-packages/langchain/schema/vectorstore.py:585, in VectorStoreRetriever._get_relevant_documents(self, query, run_manager)
    581 def _get_relevant_documents(
    582     self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    583 ) -> List[Document]:
    584     if self.search_type == "similarity":
--> 585         docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
    586     elif self.search_type == "similarity_score_threshold":
    587         docs_and_similarities = (
    588             self.vectorstore.similarity_search_with_relevance_scores(
    589                 query, **self.search_kwargs
    590             )
    591         )

File /opt/conda/lib/python3.10/site-packages/langchain/vectorstores/pgvector.py:335, in PGVector.similarity_search(self, query, k, filter, **kwargs)
    318 def similarity_search(
    319     self,
    320     query: str,
   (...)
    323     **kwargs: Any,
    324 ) -> List[Document]:
    325     """Run similarity search with PGVector with distance.
    326 
    327     Args:
   (...)
    333         List of Documents most similar to the query.
    334     """
--> 335     embedding = self.embedding_function.embed_query(text=query)
    336     return self.similarity_search_by_vector(
    337         embedding=embedding,
    338         k=k,
    339         filter=filter,
    340     )

File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:156, in BedrockEmbeddings.embed_query(self, text)
    147 def embed_query(self, text: str) -> List[float]:
    148     """Compute query embeddings using a Bedrock model.
    149 
    150     Args:
   (...)
    154         Embeddings for the text.
    155     """
--> 156     return self._embedding_func(text)

File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:130, in BedrockEmbeddings._embedding_func(self, text)
    128     return response_body.get("embedding")
    129 except Exception as e:
--> 130     raise ValueError(f"Error raised by inference endpoint: {e}")

ValueError: Error raised by inference endpoint: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: expected minLength: 1, actual: 0, please reformat your input and try again.

### Description

I'm using MultiQueryRetriever with bedrock claude model.
I got ValueError: Error raised by inference endpoint: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: expected minLength: 1, actual: 0, please reformat your input and try again.

Please take a look. Thank you

### System Info

!pip show langchain

Name: langchain
Version: 0.0.318
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: /opt/conda/lib/python3.10/site-packages
Requires: aiohttp, anyio, async-timeout, dataclasses-json, jsonpatch, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: jupyter_ai, jupyter_ai_magics

**Comment by IceKickr** [comment]
I got what looks to be the same error.
```
unique_docs = retriever_from_llm.get_relevant_documents(query="Captain Nemo's story")
```

This is the INFO logging:

INFO:langchain.retrievers.multi_query:Generated queries: ['Here are three alternative versions of the original question "Captain Nemo\'s story":', '', 'What is the narrative of Captain Nemo from the novels of Jules Verne?', 'Describe the background and character development of the enigmatic Captain Nemo in the literary works he appears in.', 'Explore the life and adventures of the mysterious Captain Nemo as portrayed in the writings of Jules Verne.']

**Comment by bjoernoest** [comment]
any news?
