### ISSUE TITLE
Support for Pinecone Hybrid Search (Sparse-dense embeddings)

### ISSUE THREAD

**Issue by sbc-max** [langchain-ai/langchain#1743]
I have found that the OpenAI embeddings are decent, but suffer when you want specific names or keywords to be included. I've found that the [sparse-dense approach](https://www.pinecone.io/learn/sparse-dense) produces better results, but not supported by the current implementation of the Vectorstore or the chains. 

Has anyone else implemented a workaround or is there any planned support for this?

**Comment by mzhadigerov** [comment]
@sbc-max Have you found a workaround? I wanted to use hybrid search too. Haystack has such a functionality tho. So I'm thinking to use haystack for document retrieval and langchain to get answer from chatgpt.

**Comment by sbc-max** [comment]
@mzhadigerov working on it - will post in the next day or two once I have a working example. But my current solution isn’t great, it’s just

**Comment by sbc-max** [comment]
@mzhadigerov  where did you see Haystack’s support for pinecone hybrid search - just took at their pinecone vectorstore class and didn’t see it.

**Comment by mzhadigerov** [comment]
@sbc-max sorry for missclarification, it is not about pinecone explicitly, but about combining multiple Retrievers (e.g. dense + sparse). Here is the docs:

[](https://haystack.deepset.ai/tutorials/11_pipelines#:~:text=Copy-,Custom%20Pipelines,-Now%20we%20are)

**Comment by mzhadigerov** [comment]
@sbc-max isn't that what you are looking for?

**Comment by sbc-max** [comment]
@mzhadigerov decided to try [Weaviate for their hybrid search](https://weaviate.io/developers/weaviate/api/graphql/vector-search-parameters#hybrid). Found it way easier to implement than hybrid with Pinecone, since the BM25 and OpenAI embeddings are built-in directly into the vector db query tool. LangChain support for Weaviate is lacking, but I think it's worth the trade off.
