### ISSUE TITLE
TavilySearchResults in Agents Quick Start always return empty result

### ISSUE THREAD

**Issue by wanwe** [langchain-ai/langchain#17447]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_community.tools.tavily_search import TavilySearchResults, TavilyAnswer

search = TavilySearchResults()
print(search.invoke("what is the weather in SF"))
# output: []

tans = TavilyAnswer()
print(tans.invoke("What is the weather in SF?"))
# output: The current weather in San Francisco is partly cloudy with a temperature of 51.1°F (10.6°C). The wind is coming from the west-northwest at 8.1 mph (13.0 km/h), and the humidity is at 86%. The visibility is 9.0 miles (16.0 km), and the UV index is 1.0. The highest temperature recorded in San Francisco in 2024 was 73°F (23°C) on January 29.

```

### Description

# Issue:

I'm trying the [Agents Quickstart example on Tavily](https://python.langchain.com/docs/modules/agents/quick_start).
As shown above, "TavilySearchResults" is returning empty response. Upon checking, I found "TavilyAnswer" can return results correctly. Digging further, I found the difference is due to Tavily rest API param "search_depth". 
"TavilySearchResults" defaults to "advanced" while "TavilyAnswer" defaults to "basic".

I tried on https://app.tavily.com/playground, same behavior, search_depth="basic" can return results while "advanced" does not have result.

# Possible Solution
I'm on Tavily free tier, hope the API tier does not make a difference.

I propose either to change default search_depth to "basic" or expose search_depth as variable in TavilySearchResults.
let me know any option is preferred, I can create a pull request

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
> Python Version:  3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:35:41) 
[Clang 16.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.16
> langchain: 0.1.5
> langchain_community: 0.0.17
> langchain_experimental: 0.0.50
> langchain_openai: 0.0.5
> langchainhub: 0.1.14

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by rotemweiss57** [comment]
hi @wanwe I'm here from Tavily. Can you check if the issue is still happening?

**Comment by wanwe** [comment]
@rotemweiss57 issue resolved, thank you !

**Comment by TomTom101** [comment]
I do encounter it now. The Playground returns a result as expected with `TavilySearchResults` from `langchain_community.tools.tavily_search` the result is empty. I did get results for exactly the same query yesterday.

**Comment by RubenGres** [comment]
I'm having the same issue with the TavilySearchAPIRetriever that is unreliable. It sometimes returns an empty array for the exact same input

**Comment by wulucxy** [comment]
I'm having the same issue too. 

```json
 // ===tavily response===
 {
  query: '"{\\"input\\":\\"2023 NBA final winner\\"}"',
  follow_up_questions: null,
  answer: null,
  images: null,
  results: [],
  response_time: 1.28
}
```
