### ISSUE TITLE
unable to extract/return metadata while retrieving the relevant documents

### ISSUE THREAD

**Issue by wayfarer01** [langchain-ai/langchain#17455]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

below is the code how documents[0] look like

`Document(page_content='Text: This e Australian  Act (Cth).', metadata={'source': '/content/excel_data/2.csv', 'row': 0, 'x1': '296.707803875208', 'y1': '211.071329072118', 'x2': '1436.41797742248', 'y2': '276.853476041928', 'Block Type': 'LAYOUT_TEXT', 'Block ID': '42c93696619b409b80ddc71df32580f2', 'page_num': '1', 'Company': 'BBCI', 'Year': '2020', 'is_answer': '0'})`

below's the code which returns the topk unique documents using retriever

```
def fetch_unique_documents_with_metadata(query, initial_limit, desired_count):
    unique_docs_with_metadata = []
    seen_contents = set()
    current_limit = initial_limit

    while len(unique_docs_with_metadata) < desired_count:
        retriever = vectorStore.as_retriever(search_kwargs={"k": current_limit})

        docs = retriever.get_relevant_documents(query)

        # Keep track of whether we found new unique documents in this iteration
        found_new_unique = False

        for doc in docs:
            if doc.page_content not in seen_contents:
                # Add both page_content and metadata to the unique document list
                doc_with_metadata = {
                    "page_content": doc.page_content,
                    "metadata": doc.metadata
                }
                unique_docs_with_metadata.append(doc_with_metadata)
                seen_contents.add(doc.page_content)
                found_new_unique = True

                if len(unique_docs_with_metadata) == desired_count:
                    break

        if not found_new_unique or len(unique_docs_with_metadata) == desired_count:
            break  # Exit if no new unique documents are found or if we've reached the desired count

        # Increase the limit more aggressively if we are still far from the desired count
        current_limit += desired_count - len(unique_docs_with_metadata)

    return unique_docs_with_metadata

# Example usage with the updated function
query = "Does  or concerns, including in relation?"
desired_count = 10  # The number of unique documents you want
unique_documents_with_metadata = fetch_unique_documents_with_metadata(query, initial_limit=desired_count, desired_count=desired_count)

# Print the unique documents or handle them as needed
# for doc in unique_documents_with_metadata:
#     print(f"Row {doc['metadata']['row']}: {doc['page_content']}")
#     print(f"Metadata: {doc['metadata']}")

len(unique_documents_with_metadata)
```

the output is below

```
{'page_content': 'Text: 5. esources departments or the \n.',
 'metadata': {}}
```

unable to extract/return metadata while retrieving the relevant documents. It is not returning metadata present inside the documents, it is only returning page_content. I want to return all the medata which looks like metadata={'source': '/content/excel_data/2.csv', 'row': 0, 'x1': '296.707803875208', 'y1': '211.071329072118', 'x2': '1436.41797742248', 'y2': '276.853476041928', 'Block Type': 'LAYOUT_TEXT', 'Block ID': '42c93696619b409b80ddc71df32580f2', 'page_num': '1', 'Company': 'BBCI', 'Year': '2020', 'is_answer': '0'}) but it is only returning page_content. Can you look into it and help me with the code?

**Comment by wayfarer01** [comment]
> _🤖_
> 
> Hey @wayfarer01, great to see you back! Diving into document adventures again, I see. Let's crack this metadata mystery together.
> 
> Based on the code you've provided, it seems like you're correctly adding the metadata to your `unique_docs_with_metadata` list. The issue might be with the `get_relevant_documents` method of your `vectorStore` object. It's possible that the documents it's returning don't have any metadata associated with them.
> 
> To debug this, you could try printing out the documents returned by `get_relevant_documents` to see if they have metadata:
> 
> ```python
> docs = retriever.get_relevant_documents(query)
> for doc in docs:
>     print(doc.metadata)
> ```
> 
> If the metadata is empty for all documents, then the issue is likely with how the documents are being loaded into your `vectorStore`. You might need to check the part of your code where you're loading the documents to ensure the metadata is being included.
> 
> If the metadata is not empty, then the issue might be with how you're adding the metadata to your `unique_docs_with_metadata` list. But based on the code you've provided, it seems like you're doing this correctly.
> 
> Also, please ensure that the `Document` objects in your `vectorStore` are instances of the `Document` class from the LangChain framework, and that they have a `metadata` attribute. If they're instances of a different `Document` class, they might not have a `metadata` attribute, or the `metadata` attribute might work differently.
> 
> If you're still having trouble, could you provide more information about how you're loading the documents into your `vectorStore`, and what the `vectorStore` object is? This would help in identifying the issue.
> 
> ## Sources
> * [libs/langchain/langchain/document_loaders/snowflake_loader.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/snowflake_loader.py)
> * [libs/core/langchain_core/vectorstores.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/vectorstores.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

```
for doc in docs:
    print(doc.metadata)
```
it is returning completely empty like below

```
{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
```
but when i normally ran the below code

`documents[11].metadata`

it has returned below output

```
{'source': '/content/excel_data/2.csv',
 'row': 0,
 'x1': '296.707803875208',
 'y1': '211.071329072118',
 'x2': '1436.41797742248',
 'y2': '276.853476041928',
 'Block Type': 'LAYOUT_TEXT',
 'Block ID': '42c93696619b409b80ddc71df32580f2',
 'page_num': '1',
 'Company': 'Amcor',
 'Year': '2020',
 'is_answer': '0'}
```

but it is returning empty while retrieving the snippets. Is there any way to get all the components page_content along with the metadata while retrieving?

**Comment by baskaryan** [comment]
duplicate of #17459.
