### ISSUE TITLE
unable to retrieve metadata while retrieving the documents

### ISSUE THREAD

**Issue by wayfarer01** [langchain-ai/langchain#17458]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

below is the code which will retrieve the documents

```
# Create a retriever for the vector database
retriever = vectorStore.as_retriever(search_kwargs={"k": 10})

docs = retriever.get_relevant_documents("data related to cricket")
```
then below's the output when i tried to return the metadata

```
for doc in docs:
    print(doc.metadata)

{}
{}
{}
{}
{}
{}
{}
{}
{}
{}
```

it is not returning metadata, but it is returning page_content. How to also return the metadata along with page_content?

**Comment by wayfarer01** [comment]
> _🤖_
> 
> Hey @wayfarer01, nice to see you delving into the depths of LangChain again! How's the coding journey treating you this time?
> 
> Based on the code you've provided, it seems like you're trying to retrieve metadata from documents using the `get_relevant_documents` method from the `BaseRetriever` class in the LangChain framework. However, you're getting empty dictionaries as output, which indicates that no metadata is being returned.
> 
> The `get_relevant_documents` method is designed to retrieve documents relevant to a given query. It returns a list of `Document` objects, each of which has a `metadata` attribute. This attribute should contain the metadata associated with the document.
> 
> If the `metadata` attribute of the `Document` objects is empty, it could mean that the documents in your vector database do not have any metadata associated with them. When the documents were created and added to the vector database, the `metadata` attribute might not have been set.
> 
> To ensure that the `metadata` attribute is set when creating a `Document`, you can use the `Document` class's constructor, which accepts a `metadata` parameter. Here's an example:
> 
> ```python
> doc = Document(page_content="some content", metadata={"source": "some source"})
> ```
> 
> In this example, the `metadata` attribute of the `Document` object is set to `{"source": "some source"}`.
> 
> If you're using a custom document loader to load your documents into the vector database, make sure that the loader sets the `metadata` attribute of the `Document` objects it creates. Here's an example of how you can do this in a custom document loader:
> 
> ```python
> class MyDocumentLoader(BaseLoader):
>     def load(self) -> List[Document]:
>         # Load your documents here
>         docs = []
>         for data in my_data:
>             doc = Document(page_content=data["content"], metadata=data["metadata"])
>             docs.append(doc)
>         return docs
> ```
> 
> In this example, `my_data` is a list of dictionaries, each of which has a `"content"` key and a `"metadata"` key. The `"content"` key's value is used as the `page_content` of the `Document`, and the `"metadata"` key's value is used as the `metadata` of the `Document`.
> 
> If you're still having issues, please provide more information about how you're creating and adding your documents to the vector database, and I'll be happy to help further.
> 
> ## Sources
> * [libs/langchain/langchain/document_loaders/facebook_chat.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/document_loaders/facebook_chat.py)
> * [libs/core/langchain_core/retrievers.py](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/retrievers.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

No, listen, we're loading the documents through CSVLoader, at that time i'm mentioning the metadata fields. Now, i'm only adding page_content data to the FAISS vector store as below

```
# Instantiate the OpenAIEmbeddings class
openai = OpenAIEmbeddings(openai_api_key="")

# Generate embeddings for your documents
embeddings = openai.embed_documents([doc.page_content for doc in documents])

# Create tuples of text and corresponding embedding
text_embeddings = list(zip([doc.page_content for doc in documents], embeddings))

# Create a FAISS vector store from the embeddings
vectorStore = FAISS.from_embeddings(text_embeddings, openai)

# Create a retriever for the vector database
retriever = vectorStore.as_retriever(search_kwargs={"k": 10})

docs = retriever.get_relevant_documents("Data related to cricket")
```

is there any way to also add metadata, so that while retrieving the documents i.e. page_content, it'll also retrieve it's respective metadata?

**Comment by baskaryan** [comment]
duplicate of #17459

**Comment by nyck33** [comment]
@baskaryan ya but neither really offers any conclusive solution so making a new issue
