### ISSUE TITLE
how to also add metadata along with the page_content to the vector store?

### ISSUE THREAD

**Issue by wayfarer01** [langchain-ai/langchain#17459]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

below is the code which will add only page_content to the embeddings

```
# Instantiate the OpenAIEmbeddings class
openai = OpenAIEmbeddings(openai_api_key="")

# Generate embeddings for your documents
embeddings = openai.embed_documents([doc.page_content for doc in documents])

# Create tuples of text and corresponding embedding
text_embeddings = list(zip([doc.page_content for doc in documents], embeddings))

# Create a FAISS vector store from the embeddings
vectorStore = FAISS.from_embeddings(text_embeddings, openai)

# Create a retriever for the vector database
retriever = vectorStore.as_retriever(search_kwargs={"k": 10})

docs = retriever.get_relevant_documents("Data related to cricket")
```

while retrieving the document and printing the output, it'll only return page_content and doesn't return metadata. So, is there any to also add metadata to the vector store and return metadata along with the page_content output?

**Comment by wayfarer01** [comment]
> _🤖_
> 
> Based on the context provided, it seems like you want to add metadata to the vector store and retrieve it along with the page_content. In the current LangChain framework, the `SurrealDBStore` class supports adding metadata to the vector store. The `add_texts` and `aadd_texts` methods of this class accept an optional `metadatas` argument, which is a list of dictionaries containing the metadata for each text. This metadata is then stored in the vector store along with the text and its embedding.
> 
> When you perform a similarity search using methods like `asimilarity_search_by_vector_with_score`, `asimilarity_search_with_relevance_scores`, `asimilarity_search_with_score`, or `asimilarity_search`, the returned `Document` objects include the metadata in their `metadata` attribute. This is done in the `_asimilarity_search_by_vector_with_score` method, where the metadata is included in the `Document` object as follows:
> 
> ```python
> Document(
>     page_content=result["text"],
>     metadata={"id": result["id"], **result["metadata"]},
> )
> ```
> 
> Here, `result["metadata"]` is the metadata that was stored in the vector store. The `metadata` attribute of the `Document` object is a dictionary that includes the ID of the document and the metadata that was stored with it.
> 
> So, to add metadata to the vector store and return it along with the page_content output, you can simply pass the metadata when adding texts to the vector store, and it will be returned when you perform a similarity search.
> 
> You can refer to the [libs/community/langchain_community/vectorstores/surrealdb.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/surrealdb.py) for more details.
> 
> Regarding the `OpenAIEmbeddings` class, I couldn't find any specific information about it in the repository. If you could provide more details about this class or its methods, I might be able to provide a more accurate answer.
> 
> ## Sources
> * [libs/community/langchain_community/vectorstores/surrealdb.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/surrealdb.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

but i'm working on FAISS, i need solution for FAISS. Can you please help me with the code?

**Comment by baskaryan** [comment]
use `FAISS.from_documents(documents, openai)` instead of from_embeddings. for future reference, please post usage questions as discussions not issues.

**Comment by Anash-EB** [comment]
> use `FAISS.from_documents(documents, openai)` instead of from_embeddings. for future reference, please post usage questions as discussions not issues.

FAISS.from_documents(documents, openai)` this wont work if the you have huge data (eg: 1GB file)

**Comment by TomSOWI** [comment]
Still facing the same issue. To deal with large data I want to embed documents in batches but still keep the metadata. FAISS.from_embedding only accepts string, embedding pairs. It would be nice if it would accepts documents, embedding pairs as well and sustains the metadata from the documents.

I want to run the following:

```
loader = DataFrameLoader(df, page_content_column="text")
documents = loader.load()
embedding_func = HuggingFaceEmbeddings(model_name=embedding_model_path)
 # Embed in batches
  embeddings = []
  for start in range(0, len(documents), batch_size):
      batch_docs = documents[start:start + batch_size]
      texts = [doc.page_content for doc in batch_docs]

      # This will embed just the batch
      batch_embs = embedding_func.embed_documents(texts)
      embeddings.extend(batch_embs)

  # Build FAISS index 
  text_embedding_pairs = zip(documents, embeddings)
  db = FAISS.from_embeddings(doc_embedding_pairs, embedding_func)
```
