### ISSUE TITLE
Issue with chain output_schema when a runnableparrallel is invoked with assign.

### ISSUE THREAD

**Issue by sayan** [langchain-ai/langchain#17460]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

The following code
```
from langchain_core.runnables import RunnableParallel
from langchain.prompts import ChatPromptTemplate

chain1 = ChatPromptTemplate.from_template("tell me a joke about {topic}")
chain2 =   ChatPromptTemplate.from_template("write a short (2 line) poem about {topic}")

def test(input) -> int:
    print(input)
    return(3)
combined = RunnableParallel(joke=chain1, poem=chain2).assign(x=RunnableLambda(test))
```

The output is correct if you do `combined.invoke({'topic':"love"})` you correctly get

```
{'joke': ChatPromptValue(messages=[HumanMessage(content='tell me a joke about love')]),
 'poem': ChatPromptValue(messages=[HumanMessage(content='write a short (2 line) poem about love')]),
 'x': 3}
 ```
 
 however if you check the output schema as follows
 ```
combined.output_schema.schema()
````

Output is
```
{'title': 'RunnableSequenceOutput',
 'type': 'object',
 'properties': {'topic': {'title': 'Topic', 'type': 'string'},
  'x': {'title': 'X', 'type': 'integer'}}}
```

`joke ` field is missing in the output schema. This is impacting the langserve api output for the chain as well. 

### Description

Output schema of the runnable is missing field when RunnableParallel is used in conjunction with assign.

### System Info

langchain = "0.1.6"
python = "^3.11"

**Comment by lmurawsk** [comment]
So in case of the question, fixing the problem requires sth. like this:

```python
# class that defines expected output types:
class OutputType(BaseModel):
    joke: str
    poem: str
    x: str

combined = RunnableParallel(joke=chain1, poem=chain2).assign(x=RunnableLambda(test)).with_types(output_type=OutputType)
```
Then `combined.output_schema.schema()` is as it should be:

```
{'title': 'OutputType',
 'type': 'object',
 'properties': {'joke': {'title': 'Joke', 'type': 'string'},
  'poem': {'title': 'Poem', 'type': 'string'},
  'x': {'title': 'X', 'type': 'string'}},
 'required': ['joke', 'poem', 'x']}
```

and most importantly chain responses when served by langserve will be correct!!! 

I spent tooo much time trying to figure this out. That should be mentioned on the main doc page: https://python.langchain.com/docs/expression_language/primitives/assign/
