### ISSUE TITLE
AzureOpenAI gpt-3.5-turbo doesn't support best_of parameter

### ISSUE THREAD

**Issue by starcrafter** [langchain-ai/langchain#1747]
AzureOpenAI seems not work for gpt-3.5-turbo due to this issue

**Comment by fchenGT** [comment]
Same, got this error:

openai.error.InvalidRequestError: logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346.

**Comment by fchenGT** [comment]
Actually in the openai.py, the BaseOpenAI's initializer there is this warning message:
`python
            warnings.warn(
                "You are trying to use a chat model. This way of initializing it is "
                "no longer supported. Instead, please use: "
                "`from langchain.chat_models import ChatOpenAI`"
            )
`

**Comment by ww1126811502** [comment]
Just use ChatOpenAI, because gpt-3.5 is a chat_model:

```
chat = ChatOpenAI(deployment_id=gptmodel,
                  model_kwargs={"api_key": openai.api_key, "api_base": openai.api_base, "api_type": openai.api_type,
                                "api_version": openai.api_version, },
                  model_name="gpt-35-turbo")

print(chat([HumanMessage(content="Translate this sentence from English to French. I love programming.")]))
```

**Comment by SWHL** [comment]
- I have met the same problem, and solved by @ww1126811502.
- Give the whole code:
```python
import os

import openai
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage

openai.api_type = "azure"
openai.api_base = os.getenv("OPENAI_API_BASE")
openai.api_version = "your_api_version"
openai.api_key = os.getenv("OPENAI_API_KEY")

chat = ChatOpenAI(deployment_id="gpt35xxxxx",
                  model_kwargs={"api_key": openai.api_key,
                                "api_base": openai.api_base,
                                "api_type": openai.api_type,
                                "api_version": openai.api_version, },
                  model_name="gpt-35-turbo")

print(chat([HumanMessage(
    content="Translate this sentence from English to French. I love programming.")]))

```

**Comment by dciborow** [comment]
I fixed this locally by creating this new class.

https://github.com/hwchase17/langchain/pull/4017
