### ISSUE TITLE
Expand docker-compose with common dependencies used in integration tests

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#17505]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

The goal is to make it easier to run integration tests.

Acceptance Criteria:

- [ ] Update docker compose file here: https://github.com/langchain-ai/langchain/blob/master/docker/docker-compose.yml to include a database that is used during integration tests and can be spun up locally via docker compose.
- [ ] Use non standard port -- just increment by 1 from the previous service in that file
- [ ] Update any integration tests that use the given service to use a matching port

This is a good first issue for folks with experience in dev ops.

Consider git-grepping for existing yml files that contain service configuration.

**Comment by rachana-uniyal** [comment]
I would like to work on this issue.
