### ISSUE TITLE
import pwd on windows

### ISSUE THREAD

**Issue by vorel99** [langchain-ai/langchain#17514]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain.retrievers.multi_query import MultiQueryRetriever

MultiQueryRetriever()

### Error Message and Stack Trace (if applicable)

venv\Lib\site-packages\langchain\retrievers\__init__.py:37: in <module>
    from langchain.retrievers.web_research import WebResearchRetriever
venv\Lib\site-packages\langchain\retrievers\web_research.py:5: in <module>
    from langchain_community.document_loaders import AsyncHtmlLoader
venv\Lib\site-packages\langchain_community\document_loaders\__init__.py:163: in <module>
    from langchain_community.document_loaders.pebblo import PebbloSafeLoader
venv\Lib\site-packages\langchain_community\document_loaders\pebblo.py:5: in <module>
    import pwd
E   ModuleNotFoundError: No module named 'pwd'

### Description

There is no `pwd` on windows. 

### System Info

python 3.11.2

langchain==0.1.7

**Comment by AIAnytime** [comment]
Very bad response by the Dosubot.... Langchain creators need to do better when it comes to the automated bot responses.

**Comment by Rakib-hosen** [comment]
This issue is caused by pwd library, which is not available in windows.
this issue can be fixed with importing the pwd library in the try block at 263 number line.
this is the code before:
```python
        try:
            file_owner_uid = os.stat(file_path).st_uid
            file_owner_name = pwd.getpwuid(file_owner_uid).pw_name
        except Exception:
            file_owner_name = "unknown"
        return file_owner_name
```
this will be the code after
```python
        try:
            import pwd
            file_owner_uid = os.stat(file_path).st_uid
            file_owner_name = pwd.getpwuid(file_owner_uid).pw_name
        except Exception:
            file_owner_name = "unknown"
        return file_owner_name
```

**Comment by GAI-Eng-MohamedAbdelmawla** [comment]
%pip install langchain==0.1.6
this solved my same problem

**Comment by asilverstein** [comment]
Installing langchain 0.1.6 or 0.1.7 does NOT solve this problem on Windows 11

**Comment by akashchaudhary-git** [comment]
following version of langchain are working

langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23

when trying to load document loader or any modules from the langchain_community it throws error ModuleNotFoundError: No module named 'pwd'

**Comment by xxxmuzart** [comment]
> following version of langchain are working
> 
> langchain==0.1.6 langchain-community==0.0.19 langchain-core==0.1.23
> 
> the langchain==0.1.7 and langchain-community==0.0.20 ❌ has issue when trying to load document loader or any modules from the langchain_community it throws error ModuleNotFoundError: No module named 'pwd'

so? what I should to do? how can I uninstall it and install it like for the right version? I have the same problem as author of topic

**Comment by xxxmuzart** [comment]
> following version of langchain are working
> 
> langchain==0.1.6 langchain-community==0.0.19 langchain-core==0.1.23
> 
> the langchain==0.1.7 and langchain-community==0.0.20 ❌ has issue when trying to load document loader or any modules from the langchain_community it throws error ModuleNotFoundError: No module named 'pwd'

I had same as author tells. 
`pip install langchain==0.1.6
pip install langchain-community==0.0.19
pip install langchain-core==0.1.23` worked cool, thanks mate upper

**Comment by vorel99** [comment]
will be fixed in next release

**Comment by DIMKA4621** [comment]
> Installing langchain 0.1.6 or 0.1.7 does NOT solve this problem on Windows 11

answered below
https://github.com/langchain-ai/langchain/issues/17514#issuecomment-1946264804

**Comment by Nibalee** [comment]
I ran into the same issue. I didn't understand what was the problem is since this is my first time trying to build a simple RAG chatbot. I followed your recommended solutions and I managed to fix the issue. Thank you guys for your guidance!

**Comment by DIMKA4621** [comment]
> I ran into the same issue. I didn't understand what was the problem is since this is my first time trying to build a simple RAG chatbot. I followed your recommended solutions and I managed to fix the issue. Thank you guys for your guidance!

`pip install langchain==1.0.6`
`pip install langchain-community=0.0.19`

**Comment by codlocker** [comment]
> pip install langchain==0.1.6

**Comment by niranjan-kt** [comment]
langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23

I tried the above. But I am still getting No module named 'pwd'. Is there any other solution to this problem? 😥

**Comment by DIMKA4621** [comment]
> langchain==0.1.6
> langchain-community==0.0.19
> langchain-core==0.1.23
> 
> I tried the above. But I am still getting No module named 'pwd'. Is there any other solution to this problem? 😥

Try remove this 3 packages and install only first 2.

**Comment by joao-santillo** [comment]
Downgrading the version worked fine for me, using CSVLoader import

**Comment by niranjan-kt** [comment]
> > langchain==0.1.6
> > langchain-community==0.0.19
> > langchain-core==0.1.23
> > I tried the above. But I am still getting No module named 'pwd'. Is there any other solution to this problem? 😥
> 
> Try remove this 3 packages and install only first 2.

Thank you. This solved the issue that I had 😊

**Comment by Schaekermann** [comment]
> > > langchain==0.1.6
> > > langchain-community==0.0.19
> > > langchain-core==0.1.23
> > > I tried the above. But I am still getting No module named 'pwd'. Is there any other solution to this problem? 😥
> > 
> > 
> > Try remove this 3 packages and install only first 2.
> 
> Thank you. This solved the issue that I had 😊

This was helpful for me too, but I needed one step in addition.
Along with langchain 0.1.6 also langchain-community 0.0.20 became installed
Testrun => The Problem was not solved. 
I guess the reason was somehow a cached version of  the package as in mentioned in the prompt:
 "Using cached langchain_community-0.0.20-py3-none-any.whl"
So I added an uninstall for langchain-community and installed langchain-community 0.0.19  after that:

pip install langchain==0.1.6
pip uninstall langchain-community
pip install langchain-community==0.0.19

Problem solved! For me too!
Thanks to all others

**Comment by nsw2022** [comment]
My development environment is Windows 11 and I solved it with the following commands
pip install langchain==0.1.6
pip uninstall langchain-community
pip install langchain-community==0.0.19
pip install pypdf

**Comment by rishabkumar7** [comment]
> following version of langchain are working
> 
> langchain==0.1.6 langchain-community==0.0.19 langchain-core==0.1.23
> 
> the langchain==0.1.7 and langchain-community==0.0.20 ❌ has issue when trying to load document loader or any modules from the langchain_community it throws error ModuleNotFoundError: No module named 'pwd'

This was helpful, thanks. Worked for me (Windows 11)

**Comment by YueZhengMeng** [comment]
> My development environment is Windows 11 and I solved it with the following commands pip install langchain==0.1.6 pip uninstall langchain-community pip install langchain-community==0.0.19 pip install pypdf
Thank you! I got the same problem and solved it by this!

**Comment by Jainu-s** [comment]
still after following above libraries version I'm get pwd error "ModuleNotFoundError: No module named 'pwd' " 

langchain           0.1.6
langchain-community 0.0.19
langchain-core      0.1.23
langchain-openai    0.0.6

Any solution ?

**Comment by Jainu-s** [comment]
ERROR: No matching distribution found for langchain==1.0.6

**Comment by DIMKA4621** [comment]
> 
> 
> ERROR: No matching distribution found for langchain==1.0.6

I was wrong `langchain==0.1.6`
(NOT `1.0.6`)

**Comment by Jainu-s** [comment]
again I'm getting  
" import pwd "
" ModuleNotFoundError: No module named 'pwd' "

**Comment by Jainu-s** [comment]
Here is my code 

from dotenv import load_dotenv
from langchain_community.document_loaders import UnstructuredFileLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain_community.llms import AzureOpenAI
import pwd


import os
OPENAI_API_TYPE = "Azure"
OPENAI_API_VERSION = "2023-07-01-preview"
OPENAI_API_BASE = "https://project.openai.azure.com/"
OPENAI_API_KEY = "key value"
DEPLOYMENT_NAME = "gpt-35-turbo" #Both Deployment and Model is same


os.environ["OPENAI_API_TYPE"] = OPENAI_API_TYPE
os.environ["OPENAI_API_VERSION"] = OPENAI_API_VERSION
os.environ["OPENAI_API_BASE"] = OPENAI_API_BASE
os.environ["OPENAI_API_KEY"] = OPENAI_API_KEY
load_dotenv()


loader = UnstructuredFileLoader(r'C:\Users\JainmiahShaik\Downloads\project.pdf')
documents = loader.load()

text_splitter = CharacterTextSplitter(chunk_size=800, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
doc_search = Chroma.from_documents(texts,embeddings)
chain = RetrievalQA.from_chain_type(llm=AzureOpenAI(model_kwargs={'engine':'text-davinci-002'}),chain_type='stuff', retriever = doc_search.as_retriever())

query = 'What are the effects of homelessness?'
chain.run(query)


Here are the packages I have installed:

Package             Version
------------------- ----------
aiohttp             3.9.3     
aiosignal           1.3.1     
annotated-types     0.6.0     
anyio               4.2.0     
async-timeout       4.0.3     
attrs               23.2.0    
certifi             2024.2.2  
charset-normalizer  3.3.2     
click               8.1.7     
colorama            0.4.6     
dataclasses-json    0.6.4     
distro              1.9.0     
exceptiongroup      1.2.0     
fastapi             0.109.2
frozenlist          1.4.1
greenlet            3.0.3
h11                 0.14.0
httpcore            1.0.3
httpx               0.26.0
idna                3.6
jsonpatch           1.33
jsonpointer         2.4
langchain           0.1.6
langchain-community 0.0.19
langchain-core      0.1.23
langchain-openai    0.0.6
langsmith           0.0.87
marshmallow         3.20.2
multidict           6.0.5
mypy-extensions     1.0.0
numpy               1.26.4
openai              1.12.0
packaging           23.2
pip                 24.0
pydantic            2.6.1
pydantic_core       2.16.2
PyMySQL             1.1.0
pypdf               4.0.2
python-dotenv       1.0.1
PyYAML              6.0.1
regex               2023.12.25
requests            2.31.0
setuptools          49.2.1
sniffio             1.3.0
SQLAlchemy          2.0.27
starlette           0.36.3
tenacity            8.2.3
tiktoken            0.5.2
tqdm                4.66.2
typing_extensions   4.9.0
typing-inspect      0.9.0
urllib3             2.2.1
uvicorn             0.27.1
yarl                1.9.4


I'm not getting what I have missed. It would be great if anyone suggest me. Thank You.

**Comment by Schaekermann** [comment]
> again I'm getting below error after installing langchain==0.1.6 " import pwd " " ModuleNotFoundError: No module named 'pwd' "

@Jainu-s
Perhaps it is because along with langchain==0.1.6 the package langchain-community==0.0.20 becomes installed, as it was in my case.
You can check that yourself with the command:
pip freeze
after installing langchain.
If you find langchain-community==0.0.20
You can uninstall it and then
pip install langchain-community==0.0.19
That should solve the problem.

All in one you could try this:

pip uninstall langchain langchain-community langchain-core langchain-openai

pip install langchain==0.1.6
pip uninstall langchain-community
pip install langchain-community==0.0.19
pip install langchain-core==0.1.23
pip install langchain-openai==0.0.6

At the end control it with:
pip freeze

**Comment by Jainu-s** [comment]
No luck getting same "pwd" error

after pip freeze:

aiohttp==3.9.3
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.2.0
async-timeout==4.0.3
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
dataclasses-json==0.6.4
distro==1.9.0
exceptiongroup==1.2.0
fastapi==0.109.2
frozenlist==1.4.1
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.3
httpx==0.26.0
idna==3.6
jsonpatch==1.33
jsonpointer==2.4
langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23
langchain-openai==0.0.6
langsmith==0.0.87
marshmallow==3.20.2
multidict==6.0.5
mypy-extensions==1.0.0
numpy==1.26.4
openai==1.12.0
packaging==23.2
pydantic==2.6.1
pydantic_core==2.16.2
PyMySQL==1.1.0
pypdf==4.0.2
python-dotenv==1.0.1
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
sniffio==1.3.0
SQLAlchemy==2.0.27
starlette==0.36.3
tenacity==8.2.3
tiktoken==0.5.2
tqdm==4.66.2
typing-inspect==0.9.0
typing_extensions==4.9.0
urllib3==2.2.1
uvicorn==0.27.1
yarl==1.9.4

**Comment by vishal91-hub** [comment]
> This issue is caused by pwd library, which is not available in windows. this issue can be fixed with importing the pwd library in the try block at 263 number line in langchain_community\document_loaders\pebblo.py. this is the code before:
> 
> ```python
>         try:
>             file_owner_uid = os.stat(file_path).st_uid
>             file_owner_name = pwd.getpwuid(file_owner_uid).pw_name
>         except Exception:
>             file_owner_name = "unknown"
>         return file_owner_name
> ```
> 
> this will be the code after
> 
> ```python
>         try:
>             import pwd
>             file_owner_uid = os.stat(file_path).st_uid
>             file_owner_name = pwd.getpwuid(file_owner_uid).pw_name
>         except Exception:
>             file_owner_name = "unknown"
>         return file_owner_name
> ```
> 
> also delete the import
> 
> ```python
> import pwd
> ```
> 
> from line number 5.

thanks a ton for the help. It works

**Comment by SumiranLohani** [comment]
NOTE: I got the same error with Langchain 0.0.339 and Langchain-community 0.0.20. And downgrading Langchain-community to 0.0.19 solved my issue too. Hence, the suggestions above are in the right direction.

**Comment by tariksghiouri** [comment]
I had the same issue today , and 
switching :
``` langchain==0.1.0 ```
```
langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23

```
solved the issue but still not sure i it will cause some issues for other collaborators,  in my project

**Comment by tariksghiouri** [comment]
note : my project was running fine before, I deleted the VEVN folder and  did ``` pip install -r requirements.txt ``` and that created the issue with the PWD , I didn't change my requirements.

**Comment by parthiv297** [comment]
> following version of langchain are working
> 
> langchain==0.1.6 langchain-community==0.0.19 langchain-core==0.1.23
> 
> the langchain==0.1.7 and langchain-community==0.0.20 ❌ has issue when trying to load document loader or any modules from the langchain_community it throws error ModuleNotFoundError: No module named 'pwd'



#  These versions worked. Thanks buddy.
