### ISSUE TITLE
how to set custom prompt for SelQueryRetrieval?

### ISSUE THREAD

**Issue by wayfarer01** [langchain-ai/langchain#17517]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

Below is the code which tries to the return the information what's happening within SelfQueryRetrieval and return the relevant documents

```
from langchain.globals import set_debug

set_debug(True)


query = "what's the one thing that cricketers to do while they're bowling?"

structured_query = StructuredQuery(query=query_template, limit=5)
# print(structured_query)

docs = retriever.get_relevant_documents(structured_query)
```
```

when i saw the debug output, it's completing changing the query to just 'cricket' instead of the complete query which i gave like below

```
chain/start] [1:retriever:Retriever > 2:chain:RunnableSequence > 5:parser:StructuredQueryOutputParser] Entering Parser run with input:
{
  "input": "```json\n{\n    \"query\": \"cricket\",\n    \"filter\": \"NO_FILTER\",\n    \"limit\": 5\n}\n```"
}
[chain/end] [1:retriever:Retriever > 2:chain:RunnableSequence > 5:parser:StructuredQueryOutputParser] [1ms] Exiting Parser run with output:
{
  "lc": 1,
  "type": "not_implemented",
  "id": [
    "langchain",
    "chains",
    "query_constructor",
    "ir",
    "StructuredQuery"
  ],
  "repr": "StructuredQuery(query='cricket', filter=None, limit=5)"
}
[chain/end] [1:retriever:Retriever > 2:chain:RunnableSequence] [476ms] Exiting Chain run with output:
[outputs]
```

if you see above it completely changed the query which will return irrelevant results. Now, I want to set my own prompt to the SelfQueryRetrieval. Can you return the code of how to do it with example?

**Comment by wayfarer01** [comment]
> query = "what's the one thing that cricketers to do while they're bowling?"

Can you give an example of CustomSelfRetrieval code and how to use it and enter a query and get relevant documents?

**Comment by llealgt** [comment]
@wayfarer01 hi, were you able to do it? I need to do some customizations similar to yours.
