### ISSUE TITLE
how to set custom prompt for SelfQueryRetriever?

### ISSUE THREAD

**Issue by wayfarer01** [langchain-ai/langchain#17521]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

below is the data

```
from langchain.globals import set_debug
set_debug(True)

query = "what's the one thing that cricketers to do while they're bowling?"

structured_query = StructuredQuery(query=query_template, limit=5)
# print(structured_query)

docs = retriever.get_relevant_documents(structured_query)
```

when i saw the debug output, it's completing changing the query to just 'cricket' instead of the complete query which i gave like below

```
[chain/end] [1:retriever:Retriever > 2:chain:RunnableSequence > 5:parser:StructuredQueryOutputParser] [1ms] Exiting Parser run with output:
{
  "lc": 1,
  "type": "not_implemented",
  "id": [
    "langchain",
    "chains",
    "query_constructor",
    "ir",
    "StructuredQuery"
  ],
  "repr": "StructuredQuery(query='Cricket', filter=None, limit=5)"
}
[chain/end] [1:retriever:Retriever > 2:chain:RunnableSequence] [476ms] Exiting Chain run with output:
[outputs]
```

i want to change the prompt which is already present inside the SelfQueryRetriever. Can you help me with that code?

**Comment by sandesh0202** [comment]
did you get the answer for this

**Comment by Shambhuraj11** [comment]
final_prompt = ChatPromptTemplate.from_messages(
     [
         ("system", "You are a MySQL expert. Given an input question, create a syntactically correct MySQL query to run. Unless otherwise specificed.\n\nHere is the relevant table info: {table_info}\n\nBelow are a number of examples of questions and their corresponding SQL queries."),
         few_shot_prompt,
         ("human", "{input}"),
     ]
 )
generate_query = create_sql_query_chain(llm,db,final_prompt)

generate_query.invoke(input={"question":"some query"})
ValueError: Prompt must have input variables: 'input', 'top_k', 'table_info'

can anyone help me?
