### ISSUE TITLE
Import error in language_parser.py during "from langchain.langchain.text_splitter import Language"

### ISSUE THREAD

**Issue by corbinklett** [langchain-ai/langchain#17536]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Try the following code:

```python 
from langchain.text_splitter import Language
from langchain_community.document_loaders.parsers import LanguageParser

parser=LanguageParser(language=Language.PYTHON)
```

### Error Message and Stack Trace (if applicable)

```sh
Traceback (most recent call last):
  File "/development/test.py", line 4, in <module>
    parser=LanguageParser(language=Language.PYTHON)
  File "/development/env/lib/python3.9/site-packages/langchain_community/document_loaders/parsers/language/language_parser.py", line 162, in __init__
    raise Exception(f"No parser available for {language}")
Exception: No parser available for python
```

### Description

Lines 30 and 33 of `langauge_parser.py` are `from langchain.langchain.text_splitter import Language` which causes an import error. I think these lines should just be `from langchain.text_splitter import Language`

### System Info

langchain==0.1.7
langchain-community==0.0.20
langchain-core==0.1.23
langchain-openai==0.0.6
langchainhub==0.1.14

Platform: Mac
Python 3.9.6

**Comment by corbinklett** [comment]
Might also have to add the following to the `class Language`:
```python
C = "c"
LUA = "lua"
PERL = "perl"
'''

I'm getting slightly different results on a local fork of langchain than when I import it into another project (local fork seems to accept `from langchain.langchain.text_splitter import Language`), so I'm not opening up a PR at the moment.

**Comment by SomanathSankaran** [comment]
still facing this error with langchain 0.16 and 0.1.7
