### ISSUE TITLE
docs: Make sure all partner packages have README

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#17545]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Add a good README to each of the `libs/partners` packages. See [langchain-google-vertexai](https://github.com/langchain-ai/langchain/blob/master/libs/partners/google-vertexai/README.md) for a good reference.

**Comment by benfrstr** [comment]
I'd be happy to contribute to this.

**Comment by MokshitSurana** [comment]
I'd also like to contribute to this!

**Comment by amanlai** [comment]
I'd be happy to contribute. I checked some of them and looks like nvidia-trt is missing a readme but has docs/. OpenAI only has no example usage but links to comprehensive examples. Should these be expanded or are they OK as is?

**Comment by williamdevena** [comment]
Happy to contribute to this.
