### ISSUE TITLE
partial_variables not working with ChatPromptTemplate (langchain v0.1.9)

### ISSUE THREAD

**Issue by hasansustcse13** [langchain-ai/langchain#17560]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
   async def partial_test(self):
        prompt_template = "Tell me details about {name}. The output should be in {lang}"
        llm = LLMSelector(self.model).get_language_model()
        prompt = ChatPromptTemplate.from_messages([
            HumanMessagePromptTemplate.from_template(prompt_template, partial_variables={"lang": "Spanish"}),
        ])
        chain = prompt | llm | StrOutputParser()
        result = await chain.ainvoke({'name': 'Open AI'})
        print(result)
```

### Error Message and Stack Trace (if applicable)

Errror: `Input to ChatPromptTemplate is missing variables {'lang'}.  Expected: ['lang', 'name'] Received: ['name']\"`

### Description

But this works with `PromptTemplate` also work with `ChatPromptTemplate` in previous version

### System Info

langchain v0.1.7

**Comment by keenborder786** [comment]
@hasansustcse13 Can you please tell what `LLMSelector` is, as in where are you importing it from?

**Comment by hasansustcse13** [comment]
This is an internal class. Just replace it with any chat model (ChatOpenAI)
`llm  = ChatOpenAI(model="gpt-4", openai_api_key="key")`

**Comment by baskaryan** [comment]
great catch, thank you for flagging @hasansustcse13! as a workaround while we fix, the following should still work (and is hopefully a bit simpler)
```python
from langchain_core.prompts import ChatPromptTemplate

prompt_template = "Tell me details about {name}. The output should be in {lang}"
prompt = ChatPromptTemplate.from_messages([("human", prompt_template)])
prompt = prompt.partial(lang="Spanish")
prompt.invoke({"name": "foo"})
```

**Comment by hasansustcse13** [comment]
@baskaryan Thanks for the workaround. I know there are couple of workaround for the problem. The problem is that I have to change in lots of file which I don't want. And I have just demonstrated the bug using simple example. In my case it little bit more complex. Is there any plan to fix this bug in next release? If you share your planning (how to solve it) I can give it a try though I am new to open-source contribution.

**Comment by rahilvora** [comment]
Hey @baskaryan 

Does this bug still need help? If yes, I would like to contribute (I am a first time contributor). Let me know if it is a good fit for first time contributor and how I can get started :). Thanks

Best,
Rahil

**Comment by DmitriyLeybel** [comment]
Same case with `SystemMessagePromptTemplate.from_template`

```python
graph_creator_content = \
"""
Your instructions are:
{instructions}
History:
{history}
"""
graph_analyst_template = SystemMessagePromptTemplate.from_template(template=graph_creator_content,
                                                    input_variables=['history'],
                                                    partial_variables={'instructions': json_prompt_instructions})
graph_analyst_template.format(history='history')
```

```
KeyError: 'instructions'
```

**Comment by liugddx** [comment]
> Same case with `SystemMessagePromptTemplate.from_template`
> 
> ```python
> graph_creator_content = \
> """
> Your instructions are:
> {instructions}
> History:
> {history}
> """
> graph_analyst_template = SystemMessagePromptTemplate.from_template(template=graph_creator_content,
>                                                     input_variables=['history'],
>                                                     partial_variables={'instructions': json_prompt_instructions})
> graph_analyst_template.format(history='history')
> ```
> 
> ```
> KeyError: 'instructions'
> ```

#20711 You can try this.

**Comment by zeki-kadiroglu-aifa** [comment]
> great catch, thank you for flagging @hasansustcse13! as a workaround while we fix, the following should still work (and is hopefully a bit simpler)
> 
> ```python
> from langchain_core.prompts import ChatPromptTemplate
> 
> prompt_template = "Tell me details about {name}. The output should be in {lang}"
> prompt = ChatPromptTemplate.from_messages([("human", prompt_template)])
> prompt = prompt.partial(lang="Spanish")
> prompt.invoke({"name": "foo"})
> ```

Where should be used chain object in there?
