### ISSUE TITLE
how to use FAISS for ParentDocumentRetriever for retrieving the documents?

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#17576]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

-

### Idea or request for content:

below is the code, which will add the data into chroma and define the retriever

%%time
# query = 'how many are injured and dead in christchurch Mosque?'

# Define your prompt template
prompt_template = """Use the following pieces of information to answer the user's question.
If you don't know the answer, just say that you don't know, don't try to make up an answer.

Context: {context}
Question: {question}

Only return the helpful answer below and nothing else. If no context, then no answer.
Helpful Answer:"""

```
child_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
parent_splitter = RecursiveCharacterTextSplitter(chunk_size=1200, chunk_overlap=300)

vectorstore = Chroma(
  collection_name="full_documents", embedding_function=embeddings)

store = InMemoryStore()

retriever = ParentDocumentRetriever(
  vectorstore=vectorstore,
  docstore=store,
  child_splitter=child_splitter,
  parent_splitter=parent_splitter
)

retriever.add_documents(documents, ids=None)
```

how to use FAISS db instead of Chroma and use retriever to get relevant documents like below?

```
vectorstore = FAISS.from_documents(documents, openai)
retriever = vectorstore.as_retriever(search_kwargs={"k": 10})
docs = retriever.get_relevant_documents("data related to cricket?")
```

can you help me with the code?

**Comment by eyurtsev** [comment]
Hi @nithinreddyyyyyy, please use QA discussions to ask questions.
