### ISSUE TITLE
Latest langchain_community is giving an error "No MODULE PWD" while using TEXTLOADER

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#17585]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

na

### Description

The latest version of langchain_coomunity 0.0.20 is giving an error "NO MODEUL PWD" while using TEXTLOADER()

### System Info

Running on windows and using TEXTLOADER

**Comment by eickeBuecking** [comment]
Same happens with GenericLoader...
