### ISSUE TITLE
SQL connection remains active on the server

### ISSUE THREAD

**Issue by JRMNfrtcm** [langchain-ai/langchain#17628]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

``` python 
from langchain.sql_database import SQLDatabase
from langchain_experimental.sql import SQLDatabaseChain
from langchain.chat_models import AzureChatOpenAI

DB = SQLDatabase.from_uri(SQLCONNECTION, schema=SQLSCHEMA, include_tables=[SQL_TBL1, SQL_TBL2])

LLM = AzureChatOpenAI(model=OPENAI_MODEL_NAME, temperature=0, openai_api_key=OPENAI_API_KEY, 
                      openai_api_version=OPENAI_DEPLOYMENT_VERSION, azure_endpoint=OPENAI_DEPLOYMENT_ENDPOINT, 
                      deployment_name=OPENAI_DEPLOYMENT_NAME)

db_chain = SQLDatabaseChain(llm=LLM, database=DB, verbose=True)

db_chain.run(USERQUESTION)
```

### Error Message and Stack Trace (if applicable)

N/A

### Description

Each time a question is asked, the SQL query is created and remains pending on the server even after the answer is returned to the user. The SQL query is only discarded after killing the console where the script runs.

### System Info

langchain==0.1.7
langchain-experimental==0.0.51

Windows 11 Pro

Python 3.11.4

**Comment by JRMNfrtcm** [comment]
Hi @keenborder786 ! 

SQLCONNECTION= "mssql+pyodbc://USER:PASSWORD@SERVER:1433/DATABASENAME?&driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=yes&Authentication=SqlPassword"

SQLAlchemy==2.0.27

Thanks!

**Comment by annavianelli** [comment]
any update?
