### ISSUE TITLE
AzureOpenAIEmbeddings gives an error if pymilvus is imported before

### ISSUE THREAD

**Issue by Yashar78** [langchain-ai/langchain#17646]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from pymilvus import connections , utility

import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["AZURE_OPENAI_ENDPOINT"] = "set this to end point"
os.environ["AZURE_OPENAI_API_KEY"] = "azure openai api key"
os.environ["OPENAI_API_VERSION"] = "2023-05-15"

from langchain_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(
    azure_deployment="text-embedding-ada-002",
    openai_api_version="2023-05-15"
)
text = "This is a test query."
query_result = embeddings.embed_query(text)
               
print(query_result)

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    embeddings = AzureOpenAIEmbeddings(
  File "../lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
__root__
  As of openai>=1.0.0, if `deployment` (or alias `azure_deployment`) is specified then `openai_api_base` (or alias `base_url`) should not be. Instead use `deployment` (or alias `azure_deployment`) and `azure_endpoint`. (type=value_error)

### Description

I am trying to use the langchain_openai library for embedding but I also need to import and use pymilvus. When doing so the embedding doesn't work. see the error. I use the exact code from the langchain library website.

### System Info

Name: langchain-openai
Version: 0.0.6

Name: pymilvus
Version: 2.3.6

**Comment by konradbjk** [comment]
@Yashar78  I do not have `pymilvus` and experience the same error.

https://github.com/langchain-ai/langchain/issues/18099

They have seriously messed something up. Unfortunately, I cannot recon which version I should migrate back to. I tried multiple python versions from 3.8 to 3.11. Same error
