### ISSUE TITLE
[Elasticsearch VectorStore] Could not find trained model

### ISSUE THREAD

**Issue by llermaly** [langchain-ai/langchain#17665]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain_community.vectorstores.elasticsearch import ElasticsearchStore
from langchain_community.document_loaders import DirectoryLoader
from elasticsearch import Elasticsearch

loader = DirectoryLoader('../', glob="**/*.pdf", show_progress=True)
docs = loader.load()

print(docs[0])

es_connection = Elasticsearch(
    hosts=['https://XXXXXXX.es.us-central1.gcp.cloud.es.io'], 
    basic_auth=('XXXXX', 'XXXXX')
)

vector_store = ElasticsearchStore(
            index_name="test-elser",
            es_connection=es_connection,
            strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(
                model_id=".elser_model_2_linux-x86_64"
            ),
        )

vector_store.add_documents(docs)
```

### Error Message and Stack Trace (if applicable)

> First error reason: Could not find trained model [.elser_model_1]
> Traceback (most recent call last):
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/langchain_elser/vector_store.py", line 23, in <module>
>     vector_store.add_documents(docs)
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/langchain_core/vectorstores.py", line 119, in add_documents
>     return self.add_texts(texts, metadatas, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 1040, in add_texts
>     return self.__add(
>            ^^^^^^^^^^^
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 998, in __add
>     raise e
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 981, in __add
>     success, failed = bulk(
>                       ^^^^^
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
>     for ok, item in streaming_bulk(
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
>     for data, (ok, info) in zip(
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
>     yield from gen
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/langchain-elser/.venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
>     raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
> elasticsearch.helpers.BulkIndexError: 2 document(s) failed to index.

### Description

The ELSER ingestion is not working if I use a different elser model id than the default. 

I tried with both `ElasticsearchStore.from_documents` and `ElasticsearchStore.add_documents` with no luck 

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000
> Python Version:  3.11.6 (main, Nov  2 2023, 04:39:43) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Package Information
-------------------
> langchain_core: 0.1.23
> langchain: 0.1.7
> langchain_community: 0.0.20
> langsmith: 0.0.87

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by maxjakob** [comment]
It is possible to get into an inconsistent state when the index was first created with the default model ID (`strategy=ElasticsearchStore.SparseVectorRetrievalStrategy()`) because `. elser_model_1` is then set in the index settings. If you then change only the model ID but you keep the index, it still tries to use the previous model.

@llermaly Was this possibly your situation? Did you try deleting the `test-elser` index and then re-running the code above with `.from_documents`?

**Comment by TommyBark** [comment]
I had the same issue as OP and the suggestion by maxjakob solved the issue :). Thank you.

**Comment by Gupta-Anubhav12** [comment]
Thanks @maxjakob you've been a lifesaver, this issue gave a deep migraine before I hit your comment here
