### ISSUE TITLE
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by abdellahiheiballa** [langchain-ai/langchain#1767]
When using the chat application, I encountered an error message stating "openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens" when I asked a question like "Did he mention Stephen Breyer?". 
![image](https://user-images.githubusercontent.com/25929712/226149401-8de39f47-6cd6-4ba4-9a74-f1a1eb389779.png)

**Comment by mattCLN2023** [comment]
I got the same error message today. It suggested the following.  

InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4245 tokens (1745 in the messages, 2500 in the completion). Please reduce the length of the messages or completion.  Clearly I will need a text request or response clipping approach to reduce seeing this error.

**Comment by mattCLN2023** [comment]
It was preceded by this warning - openai.py:608: UserWarning: You are trying to use a chat model. This way of initializing it **is no longer supported.** Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(. _ I will check and see if calling using this new style performs better and report back

**Comment by Jeru2023** [comment]
> It was preceded by this warning - openai.py:608: UserWarning: You are trying to use a chat model. This way of initializing it **is no longer supported.** Instead, please use: `from langchain.chat_models import ChatOpenAI` warnings.warn(. _ I will check and see if calling using this new style performs better and report back

I already used ChatOpenAI for instead but not helping, still got this error.

**Comment by pradosh-abd** [comment]
```
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(temperature=0)
```
use this llm where you were calling. I was getting "ChatOpenAI" error but moving to the current version of langchain and use the ChatOpenAI fixed the issue.

**Comment by ZohaibRamzan** [comment]
I faced the same issue, but initializing the index again solved my problem. What is the right solution to the problem?

**Comment by Bdl-1989** [comment]
Me too.

    681         stream_error = stream and "error" in resp.data
    682         if stream_error or not 200 <= rcode < 300:
--> 683             raise self.handle_error_response(
    684                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    685             )

InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4833 tokens. Please reduce the length of the messages.

How to split the response?

**Comment by murasz** [comment]
> ```
> from langchain.chat_models import ChatOpenAI
> llm = ChatOpenAI(temperature=0)
> ```
> 
> use this llm where you were calling. I was getting "ChatOpenAI" error but moving to the current version of langchain and use the ChatOpenAI fixed the issue.

I encountered a similar issue with langchain's FAISS code, but changing the temperature to '0' resolved it. This suggests that there may be a bug in the code that needs to be addressed by @hwchase17. In my experience, FAISS appears to be the most efficient local vector database for use with langchain. I experienced loading index issues with ChromaDB so I decided to abandon it for now. The only issue is the longer answers with temperature = 0, which may require creativity and creating new ideas from the given pdf file(s)

**Comment by murasz** [comment]
> initializing the index

@ZohaibRamzan How did you do that? Would you share some details? I would like to know if there is any alternative of temperature = 0.

**Comment by MYMEILE** [comment]
我也遇到了同样的问题
![image](https://user-images.githubusercontent.com/104415931/235063776-3462e673-a197-4ceb-88d5-0c4c3ae30d3a.png)
解决问题的方法是什么？

**Comment by sunlin-xiaonai** [comment]
> When using the chat application, I encountered an error message stating "openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens" when I asked a question like "Did he mention Stephen Breyer?". ![image](https://user-images.githubusercontent.com/25929712/226149401-8de39f47-6cd6-4ba4-9a74-f1a1eb389779.png)

i solve it by delete the ChatOpenAI args max_token ， i use langchain version 0.0.176 latest

**Comment by clemlesne** [comment]
Seems related to https://github.com/langchain-ai/langchain/issues/1349.
