### ISSUE TITLE
LangChain does not work with AzureSearch anymore due to ImportError

### ISSUE THREAD

**Issue by Coding-Crashkurse** [langchain-ai/langchain#17679]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

When I run the following code:

```
embeddings: OpenAIEmbeddings = OpenAIEmbeddings(deployment="text-embedding-ada-002", chunk_size=1)
index_name: str = "langchain-example"
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=os.environ.get("SEARCH_ENDPOINT"),
    azure_search_key=os.environ.get("SEARCH_API_KEY"),
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```
I get the following Error. 

```
Traceback (most recent call last):
  File "D:\pythonProject2\main.py", line 11, in <module>
    vector_store: AzureSearch = AzureSearch(
                                ^^^^^^^^^^^^
  File "D:\pythonProject2\.venv\Lib\site-packages\langchain_community\vectorstores\azuresearch.py", line 268, in __init__
    self.client = _get_search_client(
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\pythonProject2\.venv\Lib\site-packages\langchain_community\vectorstores\azuresearch.py", line 84, in _get_search_client
    from azure.search.documents.indexes.models import (
ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models' (D:\pythonProject2\.venv\Lib\s
ite-packages\azure\search\documents\indexes\models\__init__.py)

```
ExhaustiveKnnAlgorithmConfiguration was removed as it seems.

I used `azure-search-documents==11.4.0b8`. 

Downgrading and upgrading will result in a warning:

```
Successfully installed azure-search-documents-11.4.0
PS D:\pythonProject2> python .\main.py                            
vector_search_configuration is not a known attribute of class <class 'azure.search.documents.indexes.models._index.SearchField'> and will be igno
red
```
I tried different versions of LangChain from 0.1.0 to 0.1.7 and all resulted in the same issue. Any ideas for a workaround or a solution? It´s probably not a known issue yet.

### Description

I expect to be able to instantiate AzureSearch without any errors or warnings.

### System Info

langchain-openai==0.0.6
azure-identity==1.15.0
azure-search-documents==11.4.0
langchain==0.1.7
langchain-community==0.0.20
langchain-core==0.1.23
langchain-openai==0.0.6
langsmith==0.0.87

**Comment by artemvk7** [comment]
Same issue here. Upgrading Langchain to version 0.1.7 resulted in the same error for me, so I've downgraded Langchain to 0.1.6

**Comment by shwetalodha** [comment]
I'm facing the same problem: ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models'

**Comment by andreadeldegan** [comment]
Same problem: ImportError: cannot import name 'ExhaustiveKnnAlgorithmConfiguration' from 'azure.search.documents.indexes.models'

**Comment by Yahya-cap** [comment]
Hello I am have the same issue, has it been fixed?

**Comment by csnarain** [comment]
Facing the same issue. Has anyone found a fix?
