### ISSUE TITLE
Fix regex for map_rerank_prompt.py

### ISSUE THREAD

**Issue by Knight1997** [langchain-ai/langchain#1779]
https://github.com/hwchase17/langchain/blob/3701b2901e76f2f97239c2152a6a7d01754fb666/langchain/chains/question_answering/map_rerank_prompt.py#L6

This regex is not handling the case where if answer text contains something like: `\n Helpful Score: 100` and the parsing fails even if the score is 100. 

It should be something like: `(.*?)\n((.?)*)Score: (.*)` to resolve the use case

**Comment by rishabh-ti** [comment]
Can confirm
![Screenshot 2023-03-28 at 1 18 27 AM](https://user-images.githubusercontent.com/110235735/228050581-616d9ba1-8590-4031-8f14-c65bd9ccf88a.png)
