### ISSUE TITLE
DOC: https://docs.smith.langchain.com/overview -> 404

### ISSUE THREAD

**Issue by yamz8** [langchain-ai/langchain#17799]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://python.langchain.com/docs/modules/agents/quick_start#retriever
https://python.langchain.com/docs/use_cases/chatbots/retrieval#creating-a-retriever
https://python.langchain.com/docs/use_cases/chatbots/quickstart#retrievers
https://python.langchain.com/docs/get_started/quickstart#server

**Comment by Savombre** [comment]
Got the same issue, while reading the documentation too. 

To fix it you just have to use https://docs.smith.langchain.com/ instead of https://docs.smith.langchain.com/overview in your code
