### ISSUE TITLE
Add support for selfhost models like ChatGLM or transformer models

### ISSUE THREAD

**Issue by imClumsyPanda** [langchain-ai/langchain#1780]
Is there any chance to add support for selfhost models like ChatGLM or transformer models.
Tried to use runhouse with model “ChatGLM-6B”, but not working.

**Comment by imClumsyPanda** [comment]
Is there any chance to add support for selfhost models like ChatGLM or transformer models.
Tried to use runhouse with model “ChatGLM-6B”, but not working.

**Comment by nameless0704** [comment]
Same. Looking forward to it!

**Comment by imClumsyPanda** [comment]
@nameless0704 I've found a solution in LangChain's documentation, and this may help you: https://python.langchain.com/en/latest/modules/llms/examples/custom_llm.html

**Comment by nameless0704** [comment]
> @nameless0704 I've found a solution in LangChain's documentation, and this may help you: https://python.langchain.com/en/latest/modules/llms/examples/custom_llm.html

This link no longer exists😭

**Comment by nameless0704** [comment]
> @nameless0704 how about this one https://python.langchain.com/en/latest/modules/models/llms/examples/custom_llm.html

Thank you, looking into it!

**Comment by imClumsyPanda** [comment]
I've just worked it out and here comes the repo link:
[langchain-ChatGLM](https://github.com/imClumsyPanda/langchain-ChatGLM)
