### ISSUE TITLE
ReduceDocumentsChain: token_max has not effect on chunk length

### ISSUE THREAD

**Issue by AntoineDubois** [langchain-ai/langchain#17869]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

``` python
from langchain.chains.combine_documents.stuff import StuffDocumentsChain
from langchain.chains import MapReduceDocumentsChain, ReduceDocumentsChain

text_splitter = RecursiveCharacterTextSplitterRegroup( # custom RecursiveCharacterTextSplitter
            model_name = self.name,
            chunk_size = max_input_tokens, # 2048
            chunk_overlap = 0,
            length_function = text_tokenized_length,
            separators = ["\nFile name:", "\n\n", "\n"]#PATCH_SEPARATORS
        )

map_chain = LLMChain(llm=self.llm, prompt=self._prompt("patch", "explain"))
reduce_chain = LLMChain(llm=self.llm, prompt=self._prompt("patch", "summarize"))
      
combine_documents_chain = StuffDocumentsChain(llm_chain=reduce_chain, document_variable_name="patch_explain")

reduce_documents_chain = ReduceDocumentsChain(combine_documents_chain=combine_documents_chain,
                                                      collapse_documents_chain=combine_documents_chain,
                                                      token_max=max_input_tokens, # 2048
                                                      collapse_max_retries=1
                                                      )
    
map_reduce_chain = MapReduceDocumentsChain(llm_chain=map_chain, 
                                                   reduce_documents_chain=reduce_documents_chain,
                                                   document_variable_name="patch",
                                                   return_intermediate_steps=False,
                                                   )

texts = text_splitter.split_text(text)
input_dict = {
            "input_documents": [Document( page_content = text ) for text in texts],
            "text_name": text_name,
        }
map_reduce_chain.invoke(input=input_dict)
```

### Error Message and Stack Trace (if applicable)

Token indices sequence length is longer than the specified maximum sequence length for this model (6589 > 2048). Running this sequence through the model will result in indexing errors

### Description

I'm working with the **MapReduceDocumentsChain** class, following the instructions in the LangChain tutorial on [Summarization](https://python.langchain.com/docs/use_cases/summarization). According to what I've gathered from the documentation, the output documents produced by the ReduceDocumentChain are restricted to not exceed a maximum token length, referred to as **token_max**. 
Searching online, I've come across others facing the same issue, yet no solutions provided seem adequate. 
I'm eager for any assistance you can offer.

### System Info

Platform: macOS 14.2.1 (23C71)
Python version: 3.11
langchain==0.1.8
langchain-community==0.0.21
langchain-core==0.1.2

**Comment by AntoineDubois** [comment]
Unfortunately, this post does not solve the problem.
May I need to precise that my model is imported from HuggingFace with the classe langchain_community.llms.HuggingFacePipeline?

**Comment by CREESTL** [comment]
I'm currently facing the exact same issue. The code is very similar to the OP's. And I'm also trying to summarize large texts. 
The model I'm using is Mixtral8x7B-Instruct-v0.1. So its token window is 32k according to official documents. But I just can't get rid of the warning:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (4412 > 1024) ...
```

I've been trying to solve this issue for past 2 days, but no solution for now...
