### ISSUE TITLE
Missing first class pydantic objects support by `XMLOutputParser`

### ISSUE THREAD

**Issue by sansmoraxz** [langchain-ai/langchain#17862]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Take the following Pydantic class:

```python
from langchain_core.pydantic_v1 import BaseModel, Field

class Joke(BaseModel):
    setup: str = Field(description="question to set up a joke")
    punchline: str = Field(description="answer to resolve the joke")
```

When used with `JsonOutputParser` we can generate pydantic schema as follows:-

```python
from langchain_core.output_parsers import JsonOutputParser
instructions = JsonOutputParser(pydantic_object=Joke).get_format_instructions()
```

### Description

The given example steps are not replicable with `XMLOutputParser`. Although it does have the `tags` field, there is no way to pass the pydantic object directly. Passing JSON schema can result in transient errors in generated outputs.

Ideally an XML schema or something similar should be injected, which would be dynamically generated from the Pydantic object.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.25
> langchain: 0.1.8
> langchain_community: 0.0.21
> langsmith: 0.1.5
> langchainhub: 0.1.14

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by konradbjk** [comment]
Looks like there is no more `langchain_core.pydantic_v1` :(
