### ISSUE TITLE
The functions `save_context` and `asave_context` are experiencing problems when trying to store output messages, specifically when `output_str` is of the `AIMessage` type

### ISSUE THREAD

**Issue by ww-jermaine** [langchain-ai/langchain#17867]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

I think there's an issue with `save_context` and `asave_context` after introducing this [change](https://github.com/langchain-ai/langchain/pull/16728).

Here's the minimal example:

```python

from langchain.agents import AgentExecutor, create_react_agent
from langchain import hub
import os
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain.tools import Tool
from langchain.chains.conversation.memory import ConversationBufferWindowMemory

load_dotenv()

llm = ChatOpenAI(
    openai_api_key=os.getenv("OPENAI_API_KEY"),
    model="gpt-3.5-turbo",
)

tools = [
    Tool.from_function(
        name="General Chat",
        description="For general chat not covered by other tools",
        func=llm.invoke,
        return_direct=True
    )
]



memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=5,
    return_messages=True,
)

agent_prompt = hub.pull("hwchase17/react-chat")
agent = create_react_agent(llm, tools, agent_prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    memory=memory,
    verbose=True
)

def generate_response(prompt):
    """
    Create a handler that calls the Conversational agent
    and returns a response to be rendered in the UI
    """

    response = agent_executor.invoke({"input": prompt})

    return response['output']

generate_response(input("Write: "))
```

### Error Message and Stack Trace (if applicable)

```
> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: General Chat
Action Input: help me writecontent='Sure, I can help you write. What would you like to write about?'

Traceback (most recent call last):
  File "D:\Development\WW\langchain-minimal\demo.py", line 53, in <module>
    generate_response(input("Write: "))
  File "D:\Development\WW\langchain-minimal\demo.py", line 49, in generate_response
    response = agent_executor.invoke({"input": prompt})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain\chains\base.py", line 168, in invoke
    raise e
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    final_outputs: Dict[str, Any] = self.prep_outputs(
                                    ^^^^^^^^^^^^^^^^^^
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain\chains\base.py", line 460, in prep_outputs
    self.memory.save_context(inputs, outputs)
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain\memory\chat_memory.py", line 40, in save_context
    [HumanMessage(content=input_str), AIMessage(content=output_str)]
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain_core\messages\base.py", line 37, in __init__
    return super().__init__(content=content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "D:\Development\WW\langchain-minimal\venv\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for AIMessage
content
  str type expected (type=type_error.str)
content
  value is not a valid list (type=type_error.list)
```

### Description
[See related line](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/chat_memory.py#L40)

I am encountering this error when creating reAct agents. I looked into the possible cause and I think it has something to do with `save_context` and `asave_context` functions:

```python
    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        """Save context from this conversation to buffer."""
        input_str, output_str = self._get_input_output(inputs, outputs)
        self.chat_memory.add_messages(
            [HumanMessage(content=input_str), AIMessage(content=output_str)]
        )
```

It happens when `output_str` is already of type `AIMessage`. The error message also suggests that validation fails because `AIMessage(content=output_str)` is not `str`. 

Removing the cast `AIMessage` seems to resolve the issue. But I think we really need to address the pydantic error and make the validation more flexible in this part (like `Any` instead of `str`? Or Union of types). 

### System Info

langchain==0.1.8
platform: windows
python version: 3.11.4

**Comment by keenborder786** [comment]
@ww-jermaine I have been able to replicate your issue. Your PR does not make any sense, since you have just removed the AIMessage from being saved. The error is more oriented towards the parsing and how the AIMessage is stored in the output dict being used in `saved_context`

**Comment by keenborder786** [comment]
This is not an issue. It is a problem with the way you have created your tool, just do this:

```python

@tool
def general_tool(query: str) -> str:
    """Look up things online."""
    return LLM.invoke(query).content
tools = [general_tool]

```

**Comment by ww-jermaine** [comment]
> @ww-jermaine I have been able to replicate your issue. Your PR does not make any sense, since you have just removed the AIMessage from being saved. The error is more oriented towards the parsing and how the AIMessage is stored in the output dict being used in `saved_context`

Sorry about that, my first time looking into the Langchain's internals upon raising this issue and not really familiar with the codebase. I am seeing this issue in other sites though and figured it has something to do with this, so I thought narrowing down and giving a replicable example would help. But yeah thanks for addressing it quickly!
