### ISSUE TITLE
How to use openai new embedding model such as :  text-embedding-3-small?

### ISSUE THREAD

**Issue by WuYanZhao107** [langchain-ai/langchain#17903]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
import os
import openai
openai.api_key = os.getenv("OPENAI_API_KEY")

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")
# embeddings = OpenAIEmbeddings(model="text-embedding-ada-002")
db = FAISS.from_documents(split_document, embeddings)
# db.save_local("qa_faiss_index")
db.save_local("qa_faiss_test_index")
```

### Error Message and Stack Trace (if applicable)

Warning: model not found. Using cl100k_base encoding.

### Description

I want to use the new embedding model, but after running, the result is :Warning: model not found. Using cl100k_base encoding.
I have upgrade langchain,But the problem still occurs. 
So, I do not how to address this issue

### System Info

platform(windows)
python version: 3.11.5(anaconda)

**Comment by Rakib-hosen** [comment]
@WuYanZhao107 it is using the text-embedding-3-small model. C100k is encoding model not embedding model. Its ok to get the warning.

**Comment by WuYanZhao107** [comment]
> @WuYanZhao107 it is using the text-embedding-3-small model. Cl100k is encoding model not embedding model. Its ok to get the warning.

Sorry, I don't get your meaning. Do you mean that the model now defaults to text-embedding-3-small？
Because, I want to to test the model: text-embedding-3-small, so I manually set the model to "text-embedding-3-small", but after running my code the results is ：Warning: model not found. Using cl100k_base encoding.

**Comment by Rakib-hosen** [comment]
I mean you are using the model you specified. Encoding model and embedding models are two different things. To use new embedding model you have to use cl100k encoding model.

**Comment by liugddx** [comment]
update tiktoken to 0.6.0. `pip install tiktoken==0.6.0`

**Comment by liugddx** [comment]
> update tiktoken to 0.6.0. `pip install tiktoken==0.6.0`

https://github.com/openai/tiktoken/blob/1b9faf2779855124f05174adf1383e53689ed94b/tiktoken/model.py#L30

**Comment by alm0ra** [comment]
@WuYanZhao107 

hey did you find out how to use `text-embedding-3-small`??

in the document they just say `text-embedding-3-larg` and `text-embedding-3` with specific dimension
