### ISSUE TITLE
Vllm not able to set max_model_len

### ISSUE THREAD

**Issue by shivrajjadhav733** [langchain-ai/langchain#17906]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

https://python.langchain.com/docs/integrations/llms/vllm

### Description

I am trying to use langchain VLLM for mistral v2.

for that I went to this documentation and tried to run first sample code.

from langchain_community.llms import VLLM

llm = VLLM(
    model="mistralai/Mistral-7B-Instruct-v0.2",
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=128,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
)

print(llm.invoke("What is the capital of France ?"))

however I ended up getting error -
The model’s max sew len (32768) is larger than the maximum number of tokens that can be stored in KV cache (18896). Try increasing ‘gpu_memory_utilization’ or decreasing ‘max_model_len’ when initializing the engine.

I tried to update VLLM constructor code like this-

from langchain_community.llms import VLLM

llm = VLLM(
    model="mosaicml/mpt-7b",
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=128,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
    max_model_len=4096,
)

print(llm.invoke("What is the capital of France ?"))

This change also it didn’t pick up. 
when I look at log I can see LLM engine gets initialized with config - max_seq_len=32768

I also tried to add 
model_kwargs={“max_model_len”:4096}

None of the changes made to VLLM constructor are it getting picked up.

This seems to be bug.

### System Info

Langchain==0.1.8

python version 3.10.12

platform ubuntu22

**Comment by liugddx** [comment]
use max_new_tokens

**Comment by ajay-f22** [comment]
This worked for me.
# requirements
langchain==0.1.11
vllm==0.3.0

# model
llm = VLLM(model=MODEL, vllm_kwargs={"max_model_len": 4096})
