### ISSUE TITLE
in a chatbot which interact with sql db, how can it return a user friendly answer/based on user question, instead of executing query to return the 1st row of db

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#17926]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

os.environ['OPENAI_API_KEY'] = openapi_key

# Define connection parameters using constants
from urllib.parse import quote_plus
server_name = constants.server_name
database_name = constants.database_name
username = constants.username 
password = constants.password
encoded_password = quote_plus(password)
connection_uri = f"mssql+pyodbc://{username}:{encoded_password}@{server_name}/{database_name}?driver=ODBC+Driver+17+for+SQL+Server"

# Create an engine to connect to the SQL database
engine = create_engine(connection_uri)

model_name="gpt-3.5-turbo-16k"
db = SQLDatabase(engine, view_support=True, include_tables=['EGV_emp_departments_ChatGPT','egv_employee_attendance'])

llm = ChatOpenAI(temperature=0, verbose=False, model=model_name) #, n=2, best_of=2) 

PROMPT_SUFFIX = """Only use the following tables:
{table_info}
Previous Conversation:
{history}
Question: {input}"""

_DEFAULT_TEMPLATE = """Given an input question, first create a syntactically correct {dialect} query to run, 
then look at the results of the query and return the answer. 
Given an input question, create a syntactically correct MSSQL query by considering only the matching column names from the question, 
then look at the results of the query and return the answer.
If a column name is not present, refrain from writing the SQL query. column like UAN number, PF number are not not present do not consider such columns.
Write the query only for the column names which are present in view. 
Execute the query and analyze the results to formulate a response. 
Return the answer in sentence form.

Use the following format:

Question: "Question here"
SQLQuery: "SQL Query to run"
SQLResult: "Result of the SQLQuery"
Answer: "Final answer here"

"""

PROMPT = PromptTemplate.from_template(_DEFAULT_TEMPLATE + PROMPT_SUFFIX)
    
memory = None
    
     if memory == None:
        
        memory = ConversationBufferMemory()
        
    db_chain = SQLDatabaseChain.from_llm(llm, db, prompt=PROMPT, verbose=True, memory=memory)
        

        answer = db_chain.run(question)
        
        print(memory.load_memory_variables({}))

        return answer
        
     here is my code with interact with sql database in natural language , it uses langchain SQLDatabaseChain 

### Description

here if an user ask a question like hi, hello, welcome or they simply type any thing, that time it is executing some query and just returning the 1st employee details, instead if it greeting can the model return something like  hello or how can i help you, in short can the model try to understand the question and give response based on the question or if it doesn't understand the question instead of writing query to give 1st employee details or irrelevant answer can it respond like invalid question or something.

can we integrate some other functionality or model which will interact with user if the question is not related to the database.

### System Info

python: 3.11
langchain: latest

**Comment by RadhikaBansal97** [comment]
Hi @jyoti194,

Yes, You can restrict your model from answering irrelevant questions.

Add this line in your template and check->  If the question doesn't seem related to database, just return "I don't know" as the answer

**Comment by jyoti194** [comment]
@RadhikaBansal97 thank you for the response, i have figured it out and now its working fine, but now i'm trying to add multiple views to interact with but its not performing proper joins and rather giving incorrect results, is there any way to connect multiple views and also get a accurate answers? 

https://github.com/langchain-ai/langchain/issues/18120
here i have shared my code as well
