### ISSUE TITLE
Query on existing index

### ISSUE THREAD

**Issue by mzhadigerov** [langchain-ai/langchain#1792]
How to query from an existing index?

I filled up an index in Pinecode using:

```
docsearch = Pinecone.from_texts([t.page_content for t in texts], embeddings, index_name=index_name)
```

Now, I'm creating a separate `.py` file, where I need to use the existing index to query. As I understand I need to use the following function:

```
    @classmethod
    def from_existing_index(
        cls,
        index_name: str,
        embedding: Embeddings,
        text_key: str = "text",
        namespace: Optional[str] = None,
    ) -> Pinecone:
        """Load pinecone vectorstore from index name."""
        try:
            import pinecone
        except ImportError:
            raise ValueError(
                "Could not import pinecone python package. "
                "Please install it with `pip install pinecone-client`."
            )

        return cls(
            pinecone.Index(index_name), embedding.embed_query, text_key, namespace
        )
```

but what are the arguments there? I know only my `index_name` . What are the rest arguments? Embeddings are embeddings from OpenAI, right?
e.g.:
```
embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)
```

 What is the `text_key`? And what `name_space` ?

**Comment by mzhadigerov** [comment]
Okay, seems like sending `index_name` and `embedding` is enough.

**Comment by hwchase17** [comment]
text_key is the key in the metadata where the text associated with the embeddings is stored. namespace is optional, depends if you are using it or not

**Comment by gbhall** [comment]
Could we have an example for this please?

**Comment by cycloner2020** [comment]
Hi there. I am looking for an example for querying an existing index without populating more records. Anybody happen to know how this is done? Thanks in advance!

**Comment by cycloner2020** [comment]
I actually figured it out if anyone needs the code.

docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

**Comment by siddhantdante** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

Bravo....Mr. [cycloner2020](https://github.com/cycloner2020)

**Comment by RobAdkerson** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

How are you re-associating the documents themselves?

**Comment by jamesbuchanan27** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

Bless you. Where did you find the docs to help you riddle that one out?

**Comment by ogmios2** [comment]
Should anyone need help, you can create an "ingest" file where you create your embeddings, etc. and then create a query file. In that query file, re-init Pinecone and then use something like:

```
embeddings = OpenAIEmbeddings()
docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings, namespace="your_namespace_name")
```

**Comment by tandemloop** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

Thanks, these wrappers have the worst documentation I've ever seen... half the parameters aren't explained at all. The examples are all over the place.

**Comment by jamesbuchanan27** [comment]
I ended up with a variation of this to go a level deeper into namespaces, which I use to cache my document in slices of different sizes:

# see if we have populated this namespace of the index
index = pinecone.Index(index_name)
extant_namespaces = index.describe_index_stats()['namespaces']

if not name_space in extant_namespaces:
    # Build a new namespace ...

**Comment by michaelnagy** [comment]
> text_key is the key in the metadata where the text associated with the embeddings is stored. namespace is optional, depends if you are using it or not

isn't pageContent the property with the text? is this needed if we add just texts to Pinecone instead of a Document?

I can't find any information on the difference between text and Document when saving to Pinecone, it's confusing.

**Comment by amuhareb** [comment]
> > I actually figured it out if anyone needs the code.
> > docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)
> 
> Thanks, these wrappers have the worst documentation I've ever seen... half the parameters aren't explained at all. The examples are all over the place.

honestly though, you'd expect a team with some of the most powerful AI tools ever known to the common man might be able to drum something up... with AI for instance. The docs are written in parable form. I deeply respect the work and i'm very impressed by the diversity, reach, and output of the teams working on this project, but these notes need a lot of work. often the tutorials are incomplete, broken from an update, or otherwise not working. My embeddings were made elsewhere but fully functional with openai in that purpose - why wouldn't they be usable here?

**Comment by monkeydust** [comment]
> Should anyone need help, you can create an "ingest" file where you create your embeddings, etc. and then create a query file. In that query file, re-init Pinecone and then use something like:
> 
> ```
> embeddings = OpenAIEmbeddings()
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings, namespace="your_namespace_name")
> ```

Thanks for this, was driving me nuts. You would think this would be in a 101 tutorial somewhere.

**Comment by sohaybmelgendy** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

Was searching for hours,
Thanks!

**Comment by arsentievalex** [comment]
lol glad to see that I'm not the only was who was searching all over the docs for this simple piece of code

**Comment by tigerinus** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

I did this, but the RetrievalQA returns text other than what's indexed, which is driving me nuts:

```python
# imports

from dotenv import load_dotenv
from IPython.display import display
from langchain.chains import RetrievalQA
from langchain.embeddings import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.vectorstores import Pinecone
import ipywidgets as widgets
import os
import pinecone

load_dotenv()

pinecone.init(api_key=os.environ["PINECONE_API_KEY"], environment=os.environ["PINECONE_ENV"])

index_name = "langchain-demo"

embeddings = OpenAIEmbeddings()

docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

qa = RetrievalQA.from_chain_type(
    llm=OpenAI(), 
    chain_type="stuff", 
    retriever=docsearch.as_retriever(),
    return_source_documents=True
)

status_text = widgets.Output()

output_text = widgets.Output(
    style={'description_width': 'initial', 'font_size': '20px'}
)

def demo(query):
    with status_text:
        print("thinking...")

    result = qa(
        {
            "query": query['new']
        }
    )

    with output_text:
        if result["result"]:
            print(result["result"])
        else:
            print("I'm sorry I don't have any idea about this ask. Try a different question?")

    status_text.clear_output(wait=False)


input_text = widgets.Text(
    continuous_update=False, 
    layout=widgets.Layout(width='62%'), placeholder='What do you want to know?',
    style={'description_width': 'initial', 'font_size': '24px'}
)

# Display widget
display(
    input_text, 
    status_text,
    widgets.Label(value="Summary", style={'font_size': '24px'}), 
    output_text
    )

input_text.observe(demo, names='value')
```

Any help?

**Comment by dmakwana** [comment]
> text_key is the key in the metadata where the text associated with the embeddings is stored. namespace is optional, depends if you are using it or not

Just to highlight for future readers, it seems that Pinecone indexes all metadata by default, so make sure you enable [selective metadata indexing](https://docs.pinecone.io/docs/manage-indexes#selective-metadata-indexing).

**Comment by iPanchalShubham** [comment]
For js/node/nextjs guys, 
//intialise pineconeClient
const pineconeIndex = client.Index(process.env.PINECONE_INDEX_NAME);
const vectorStore = await PineconeStore.fromExistingIndex(
  new OpenAIEmbeddings(),//embeddings
  { pineconeIndex }
);

**Comment by iPanchalShubham** [comment]
For JS/Node/Nextjs guys, 

//intialise pineconeClient
const pineconeIndex = client.Index(process.env.PINECONE_INDEX_NAME);
const vectorStore = await PineconeStore.fromExistingIndex(
  new OpenAIEmbeddings(),//embeddings
  { pineconeIndex }
);

**Comment by sssssmike** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

you are a life saver

**Comment by pmespresso** [comment]
Whenever I do 
```
docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings, namespace=namespace)
query = "My query blah blah?"

output = vectorstore.similarity_search(query, k=6)

```

I get an error saying
```
ApiAttributeError                         Traceback (most recent call last)
[/var/folders/2k/8pygwk417nx88ph1cch271kr0000gn/T/ipykernel_17491/1263193631.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/2k/8pygwk417nx88ph1cch271kr0000gn/T/ipykernel_17491/1263193631.py) in 
     27 query = "What did Balaji say about fiat currency?"
     28 
---> 29 output = vectorstore.similarity_search(query, k=6)
     30 
     31 # retrieval_chain.run(input_documents=docs, question=query)

[~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py](https://file+.vscode-resource.vscode-cdn.net/Users/yj/Developer/Dreamteam/embeddings/notebooks/~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py) in similarity_search(self, query, k, filter, namespace, **kwargs)
    160             List of Documents most similar to the query and score for each
    161         """
--> 162         docs_and_scores = self.similarity_search_with_score(
    163             query, k=k, filter=filter, namespace=namespace, **kwargs
    164         )

[~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py](https://file+.vscode-resource.vscode-cdn.net/Users/yj/Developer/Dreamteam/embeddings/notebooks/~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py) in similarity_search_with_score(self, query, k, filter, namespace)
    130         )
    131         for res in results["matches"]:
--> 132             metadata = res["metadata"]
    133             if self._text_key in metadata:
    134                 text = metadata.pop(self._text_key)

[~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/pinecone/core/client/model_utils.py](https://file+.vscode-resource.vscode-cdn.net/Users/yj/Developer/Dreamteam/embeddings/notebooks/~/opt/anaconda3/envs/generative/lib/python3.9/site-packages/pinecone/core/client/model_utils.py) in __getitem__(self, name)
    500             return self.get(name)
...
--> 502         raise ApiAttributeError(
    503             "{0} has no attribute '{1}'".format(
    504                 type(self).__name__, name),

ApiAttributeError: ScoredVector has no attribute 'metadata' at ['['received_data', 'matches', 0]']['metadata']
```
No idea what that's supposed to mean, but it only occurs when I add the namespace argument...

**Comment by nishasharma149** [comment]
i have saved the documents in one namespace.Now I dont know how do i extract the vectors of my documents. I need it because my usecase is to find the difference between two documents and summarize it with LLM help. Seeking your support here.

**Comment by AMRedichkina** [comment]
In my situation, I encountered an issue due to the metadata associated with the vectors, specifically the need to include a key labeled "text" (e.g., "text": text). I found the solution to this problem in the comment at this https://github.com/langchain-ai/langchain/issues/3460#issuecomment-1583471622, which proved to be extremely helpful for me.

**Comment by yrraadi-io** [comment]
> text_key is the key in the metadata where the text associated with the embeddings is stored. namespace is optional, depends if you are using it or not

@dmakwana What is it used for? if the embedding associated with the text_key is a closest match does it return the text_key's value from the metadata?

**Comment by bqmackay** [comment]
> > I actually figured it out if anyone needs the code.
> > docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)
> 
> I did this, but the RetrievalQA returns text other than what's indexed, which is driving me nuts:
> 
> ```python
> # imports
> 
> from dotenv import load_dotenv
> from IPython.display import display
> from langchain.chains import RetrievalQA
> from langchain.embeddings import OpenAIEmbeddings
> from langchain.llms import OpenAI
> from langchain.vectorstores import Pinecone
> import ipywidgets as widgets
> import os
> import pinecone
> 
> load_dotenv()
> 
> pinecone.init(api_key=os.environ["PINECONE_API_KEY"], environment=os.environ["PINECONE_ENV"])
> 
> index_name = "langchain-demo"
> 
> embeddings = OpenAIEmbeddings()
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)
> 
> qa = RetrievalQA.from_chain_type(
>     llm=OpenAI(), 
>     chain_type="stuff", 
>     retriever=docsearch.as_retriever(),
>     return_source_documents=True
> )
> 
> status_text = widgets.Output()
> 
> output_text = widgets.Output(
>     style={'description_width': 'initial', 'font_size': '20px'}
> )
> 
> def demo(query):
>     with status_text:
>         print("thinking...")
> 
>     result = qa(
>         {
>             "query": query['new']
>         }
>     )
> 
>     with output_text:
>         if result["result"]:
>             print(result["result"])
>         else:
>             print("I'm sorry I don't have any idea about this ask. Try a different question?")
> 
>     status_text.clear_output(wait=False)
> 
> 
> input_text = widgets.Text(
>     continuous_update=False, 
>     layout=widgets.Layout(width='62%'), placeholder='What do you want to know?',
>     style={'description_width': 'initial', 'font_size': '24px'}
> )
> 
> # Display widget
> display(
>     input_text, 
>     status_text,
>     widgets.Label(value="Summary", style={'font_size': '24px'}), 
>     output_text
>     )
> 
> input_text.observe(demo, names='value')
> ```
> 
> Any help?

I'm having the same experience. Pinecone seems to be referencing a movie index instead of my own index. I'm not sure what's going on, and I'm tempted to try the paid version of Pinecone to see if that fixes it.

**Comment by naveenfaclon** [comment]
anyone faced this error

Error: type object 'Pinecone' has no attribute 'Index'

**Comment by dnyanugarule** [comment]
docsearch=Pinecone.from_existing_index(index_name, embeddings)

query = "What are Allergies"

docs=docsearch.similarity_search(query, k=3)

print("Result", docs)



---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[132], [line 1](vscode-notebook-cell:?execution_count=132&line=1)
----> [1](vscode-notebook-cell:?execution_count=132&line=1) docsearch=Pinecone.from_existing_index(index_name, embeddings)
      [3](vscode-notebook-cell:?execution_count=132&line=3) query = "What are Allergies"
      [5](vscode-notebook-cell:?execution_count=132&line=5) docs=docsearch.similarity_search(query, k=3)

NameError: name 'Pinecone' is not defined

**Comment by naveenfaclon** [comment]
from pinecone import Pinecone

**Comment by naveenfaclon** [comment]
> docsearch=Pinecone.from_existing_index(index_name, embeddings)
> 
> query = "What are Allergies"
> 
> docs=docsearch.similarity_search(query, k=3)
> 
> print("Result", docs)
> 
> NameError Traceback (most recent call last) Cell In[132], line 1 ----> 1 docsearch=Pinecone.from_existing_index(index_name, embeddings) 3 query = "What are Allergies" 5 docs=docsearch.similarity_search(query, k=3)
> 
> NameError: name 'Pinecone' is not defined

try from pinecone import Pinecone

**Comment by sc272t** [comment]
It seems from_existing_index is not supported anymore? How to load the index?

pc = Pinecone(
api_key = PINECONE_API_KEY
)
data = pc.from_existing_index(index_name, embeddings) 

returns
AttributeError: 'Pinecone' object has no attribute 'from_existing_index'

**Comment by KhushiGilhotra** [comment]
docsearch=Pinecone.from_existing_index(index_name, embeddings)

query = "What are Allergies"

docs=docsearch.similarity_search(query, k=3)

print("Result", docs)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[159], [line 1](vscode-notebook-cell:?execution_count=159&line=1)
----> [1](vscode-notebook-cell:?execution_count=159&line=1) docsearch=Pinecone.from_existing_index(index_name, embeddings)
      [3](vscode-notebook-cell:?execution_count=159&line=3) query = "What are Allergies"
      [5](vscode-notebook-cell:?execution_count=159&line=5) docs=docsearch.similarity_search(query, k=3)

AttributeError: type object 'PineconeGRPC' has no attribute 'from_existing_index'

**Comment by Sr1l1kh1ta** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

not working

**Comment by Rits1818** [comment]
> I actually figured it out if anyone needs the code.
> 
> docsearch = Pinecone.from_existing_index(index_name=index_name, embedding=embeddings)

 Pinecone.from_existing_index(index_name=index_name, embedding=embeddings, namespace=namespace)
AttributeError: type object 'Pinecone' has no attribute 'from_existing_index'
