### ISSUE TITLE
Langchain document loaders give read only file system error on AWS lambda while loading the document

### ISSUE THREAD

**Issue by santoshsg1308** [langchain-ai/langchain#17936]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_community.document_loaders import S3FileLoader
from langchain_community.document_loaders import UnstructuredWordDocumentLoader

  # loader = S3FileLoader(s3_bucket, s3_key)
  # docs = loader.load()  
  
  s3.download_file(s3_bucket, s3_key, f"/tmp/{s3_key}")                                                         
 
  with open(f"/tmp/{s3_key}", "rb") as f:
      loader = UnstructuredWordDocumentLoader(f"/tmp/{s3_key}")
      docs = loader.load()

### Error Message and Stack Trace (if applicable)

[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/task/aws_lambda_powertools/logging/logger.py", line 449, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/lambda_handler.py", line 54, in handler
    docs = loader.load()
  File "/var/task/langchain_community/document_loaders/unstructured.py", line 87, in load
    elements = self._get_elements()
  File "/var/task/langchain_community/document_loaders/word_document.py", line 124, in _get_elements
    return partition_docx(filename=self.file_path, **self.unstructured_kwargs)
  File "/var/task/unstructured/documents/elements.py", line 526, in wrapper
    elements = func(*args, **kwargs)
  File "/var/task/unstructured/file_utils/filetype.py", line 619, in wrapper
    elements = func(*args, **kwargs)
  File "/var/task/unstructured/file_utils/filetype.py", line 574, in wrapper
    elements = func(*args, **kwargs)
  File "/var/task/unstructured/chunking/__init__.py", line 69, in wrapper
    elements = func(*args, **kwargs)
  File "/var/task/unstructured/partition/docx.py", line 228, in partition_docx
    return list(elements)
  File "/var/task/unstructured/partition/lang.py", line 397, in apply_lang_metadata
    elements = list(elements)
  File "/var/task/unstructured/partition/docx.py", line 305, in _iter_document_elements
    yield from self._iter_paragraph_elements(block_item)
  File "/var/task/unstructured/partition/docx.py", line 541, in _iter_paragraph_elements
    yield from self._classify_paragraph_to_element(item)
  File "/var/task/unstructured/partition/docx.py", line 361, in _classify_paragraph_to_element
    TextSubCls = self._parse_paragraph_text_for_element_type(paragraph)
  File "/var/task/unstructured/partition/docx.py", line 868, in _parse_paragraph_text_for_element_type
    if is_possible_narrative_text(text):
  File "/var/task/unstructured/partition/text_type.py", line 78, in is_possible_narrative_text
    if exceeds_cap_ratio(text, threshold=cap_threshold):
  File "/var/task/unstructured/partition/text_type.py", line 274, in exceeds_cap_ratio
    if sentence_count(text, 3) > 1:
  File "/var/task/unstructured/partition/text_type.py", line 223, in sentence_count
    sentences = sent_tokenize(text)
  File "/var/task/unstructured/nlp/tokenize.py", line 29, in sent_tokenize
    _download_nltk_package_if_not_present(package_category="tokenizers", package_name="punkt")
  File "/var/task/unstructured/nlp/tokenize.py", line 23, in _download_nltk_package_if_not_present
    nltk.download(package_name)
  File "/var/task/nltk/downloader.py", line 777, in download
    for msg in self.incr_download(info_or_id, download_dir, force):
  File "/var/task/nltk/downloader.py", line 642, in incr_download
    yield from self._download_package(info, download_dir, force)
  File "/var/task/nltk/downloader.py", line 699, in _download_package
    os.makedirs(download_dir)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs

### Description

I am trying to load a file from S3 bucket using AWS lambda using langchain document loaders

I first tried using S3FileLoader when it gave the read-only file error.

So I tried downloading the docx file first from the S3 bucket and then used the specific document loader "UnstructuredWordDocumentLoader" as it was the word document I uploaded. but it still gave the same error.

Eventually I want to load any type of document in S3 bucket and generate embeddings to store in an opensearch vector database.

Also if I try to deploy my lambda with  docker using image public.ecr.aws/lambda/python:3.11
I get a error "FileNotFoundError: soffice command was not found. Please install libreoffice"

### System Info

python version 3.11
langchain==0.1.6
opensearch-py==2.4.2
langchain-community==0.0.19
tiktoken==0.6.0
unstructured
unstructured[docx]
aws_lambda_powertools==2.33.1

**Comment by sudeep-mishra** [comment]
Any updates? 

I am facing a similar issue with AzureBlobStorageFileLoader.

python version Python 3.9.7

**Comment by yukikubo** [comment]
This issue stems from the downloading of nltk data dependencies within the unstructured package. Since /home/sbx_user1051 is a read-only location, it triggers an error.

Therefore, if you download the necessary nltk data to a writable location and set the path accordingly, you can avoid this issue.

For instance, if you need the punkt data, you can do the following at runtime:

```
import os
import nltk

nltk.data.path.append("/tmp/nltk_data")
if not os.path.exists("/tmp/nltk_data/punkt"):
    nltk.download("punkt", download_dir="/tmp/nltk_data")
```

**Comment by luisramirez7** [comment]
Whaaaaaaaaaaaaat. I'm fighting a very similar error, S3Reader from llamaindex was working not too long ago : 

<img width="902" alt="Screenshot 2024-04-02 at 5 53 39 PM" src="https://github.com/langchain-ai/langchain/assets/23367464/6ce35b9c-eb8e-461a-bdc4-8015b7f6a801">

<img width="842" alt="Screenshot 2024-04-02 at 6 25 24 PM" src="https://github.com/langchain-ai/langchain/assets/23367464/86f4e558-8cac-4469-937a-0dc58bae47dc">

> This issue stems from the downloading of nltk data dependencies within the unstructured package. Since /home/sbx_user1051 is a read-only location, it triggers an error.
> 
> Therefore, if you download the necessary nltk data to a writable location and set the path accordingly, you can avoid this issue.
> 
> For instance, if you need the punkt data, you can do the following at runtime:
> 
> ```
> import os
> import nltk
> 
> nltk.data.path.append("/tmp/nltk_data")
> if not os.path.exists("/tmp/nltk_data/punkt"):
>     nltk.download("punkt", download_dir="/tmp/nltk_data")
> ```

**Comment by cloudlier** [comment]
Same issue, tried setting:

`ENV NLTK_DATA='/tmp/nltk_data'`

As suggested here:
https://stackoverflow.com/questions/64038735/nltk-does-not-find-path-even-though-i-downloaded-the-directory-to-the-path-list

Using `S3FileLoader` 

But it still fails as trying to write to a non-writable root directory, does not seem to pick up the ENV for NLTK_DATA

**Comment by luisramirez7** [comment]
Seems like I had a method mismatch, switched to using `S3DirectoryLoader` but I'm still getting the nltk error from above

**Comment by luisramirez7** [comment]
Replaced with: 

```def load_data(self, bucket, prefix):
        endpoint_url = None  # use this line if you are using real AWS S3
        s3_fs = S3FileSystem(anon=False, endpoint_url=endpoint_url)
        reader = SimpleDirectoryReader(
            input_dir=f'{bucket}/{prefix}',
            fs=s3_fs,
            recursive=True,  # recursively searches all subdirectories
        )
        print("Loading data from S3 from: ", bucket, prefix)
        docs = reader.load_data()
        print(f"Loaded {len(docs)} docs")
        return docs```
