### ISSUE TITLE
[BUG] Chroma DB - similarity_search - chromadb.errors.NotEnoughElementsException

### ISSUE THREAD

**Issue by ventz** [langchain-ai/langchain#1793]
Within the Chroma DB, similarity_search has a default "k" of 4.
However, if there are less than 4 results to return to the query, it will crash instead of returning whatever is available.

```similarity_search(query: str, k: int = 4, filter: Optional[Dict[str, str]] = None, **kwargs: Any) → List[langchain.docstore.document.Document][[source]](https://langchain.readthedocs.io/en/latest/_modules/langchain/vectorstores/chroma.html#Chroma.similarity_search)
Run similarity search with Chroma.

Parameters
query (str) – Query text to search for.

k (int) – Number of results to return. Defaults to 4.

filter (Optional[Dict[str, str]]) – Filter by metadata. Defaults to None.

Returns
List of documents most simmilar to the query text.

Return type
List[Document]
```

```
  raise NotEnoughElementsException(
chromadb.errors.NotEnoughElementsException: Number of requested results 4 cannot be greater than number of elements in index 1
```

I believe a check is needed to return whatever is available whenever the results are < k.

Edit: You can set `k=1` for the search, but then you are artificially limiting yourself, without knowing what is available.
It really should check if the N results returned are <= K, and if so, instead of crashing it should return whatever is availab.e.

**Comment by big-Bong** [comment]
Facing the same issue. Is it possible to pass the minimum number of query results it can return from our end?

**Comment by iyjian** [comment]
Facing the same issue

**Comment by devimprevia** [comment]
Facing the same issue.

**Comment by geg00** [comment]
I'm having the same issue.
Here is the code to show
File1.txt
This is a file with only one line

``
from langchain.document_loaders import TextLoader
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
embeddings = OpenAIEmbeddings(chunk_size=1)
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=0)
loader = TextLoader('file1.txt')
documents = loader.load()
file_text = text_splitter.split_documents(documents)
print(file_text)
col_name = 'file1'
file_db = Chroma.from_documents(file_text, embeddings)
#file_returns= VectorDBQA.from_chain_type(llm=AzureOpenAI(deployment_name="text-davinci-003", temperature=0), chain_type="stuff", vectorstore=file_db)
vector1 = embeddings.embed_documents("file")
print(file_db.similarity_search_by_vector(vector1))
``

Error Message
(base) C:\Users\hbb9279\OpenAI>C:/Users/hbb9279/AppData/Local/mambaforge/python.exe c:/Users/hbb9279/OpenAI/code/test.py
[Document(page_content='This is a file with only one line', lookup_str='', metadata={'source': 'C:\\Users\\hbb9279\\OpenAI\\Files\\file1.txt'}, lookup_index=0)]
Running Chroma using direct local API.
Using DuckDB in-memory for database. Data will be transient.
Traceback (most recent call last):
  File "c:\Users\OpenAI\code\test.py", line 25, in <module>
    print(file_db.similarity_search_by_vector(vector1))
  File "C:\Users\AppData\Local\mambaforge\lib\site-packages\langchain\vectorstores\chroma.py", line 149, in similarity_search_by_vector
    results = self._collection.query(query_embeddings=embedding, n_results=k)
  File "C:\Users\AppData\Local\mambaforge\lib\site-packages\chromadb\api\models\Collection.py", line 199, in query
    return self._client._query(
  File "C:\Users\AppData\Local\mambaforge\lib\site-packages\chromadb\api\local.py", line 237, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "C:\Users\AppData\Local\mambaforge\lib\site-packages\chromadb\db\clickhouse.py", line 492, in get_nearest_neighbors
    raise NotEnoughElementsException(
chromadb.errors.NotEnoughElementsException: Number of requested results 4 cannot be greater than number of elements in index 1

Any alternatives???

**Comment by geg00** [comment]
The issue 
this is the next line after 
The file_db is going to be part of VecotrDBQA 
file_returns= VectorDBQA.from_chain_type(llm=llm, chain_type="stuff", vectorstore=file_db)

And since I have a bunch of files all of them with unknown size until processed.

Any advice?

**Comment by jeffchuber** [comment]
Hi everyone, we are tracking this issue over on Chroma's end https://github.com/chroma-core/chroma/issues/225 

hope to have it fixed up soon!

**Comment by laveshnk-crypto** [comment]
Is the problem with the chunk size being too large for the document that was given? It worked for me when I reduced my chunk size from 1000 to 200

**Comment by jeffchuber** [comment]
@laveshnk-crypto smaller chunks will create more documents - same thing.

**Comment by laveshnk-crypto** [comment]
@jeffchuber Oh I see. Thanks for the tip! Im also facing an issue where it is not chunking the entire documents given (they are paragraphs with about 20-30 lines). Any help on that?

**Comment by ventz** [comment]
This was fixed - closing.
