### ISSUE TITLE
Integration of LangChain with Oracle SQL developer DB

### ISSUE THREAD

**Issue by AJAYM888** [langchain-ai/langchain#17933]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

import cx_Oracle
from sqlalchemy import create_engine
import openai
from langchain.agents.agent_types import AgentType
from langchain.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent
from langchain_openai import ChatOpenAI
from langchain import OpenAI, SQLDatabase
import cx_Oracle
import openai
from langchain_openai import OpenAIEmbeddings 
from langchain.llms import OpenAI
from langchain_community.agent_toolkits import create_sql_agent
from langchain_openai import ChatOpenAI
from langchain.sql_database import SQLDatabase
from langchain_experimental.sql import SQLDatabaseChain
from langchain_openai import ChatOpenAI
from langchain.chains import create_sql_query_chain
from langchain_community.vectorstores import FAISS
from langchain_core.example_selectors import SemanticSimilarityExampleSelector
from langchain_openai import OpenAIEmbeddings
from langchain_core.prompts import (
    ChatPromptTemplate,
    FewShotPromptTemplate,
    MessagesPlaceholder,
    PromptTemplate,
    SystemMessagePromptTemplate,
)

# Database credentials
username = ""
password = ""
hostname = ""
port = ""
service_name = ""
# Oracle connection string
oracle_connection_string_fmt = (
    'oracle+cx_oracle://{username}:{password}@' +
    cx_Oracle.makedsn('{hostname}', '{port}', service_name='{service_name}')
)
url = oracle_connection_string_fmt.format(
    username=username, password=password,
    hostname=hostname, port=port,
    service_name=service_name,
)

# Create SQLAlchemy engine
engine = create_engine(url, echo=False)

# Create SQLDatabase instance
db = SQLDatabase(engine)
print(db.dialect)
print(db.get_usable_table_names())

db.run("SELECT * FROM our_oracle_table")

import getpass
import os
#os.environ["OPENAI_API_KEY"] = getpass.getpass()

openai.api_type = "azure"
openai.api_base = "oururl"

# Create OpenAI Completion instance with the 'ChatOpenAI' class
llm = OpenAI(temperature=0, openai_api_key='xxxxxxxxxxxxxxxxxxx', engine='gpt-35-turbo')

# Create SQL agent
agent_executor = create_sql_agent(llm, db=db, verbose=True, handle_parsing_errors=True, agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,)

# Invoke the agent with a specific input
agent_executor.invoke({
   "input": ""
})

### Error Message and Stack Trace (if applicable)

I have the following questions and errors:

1. Is the above code is the right way of connecting langchain to oracle sql developer because it wont fetch the right table name, also it is not straight forward as using sqllite
2. If i run certain prompts it provides me this error: DatabaseError: ORA-01805: possible error in date/time operation
3. For certain prompts: i get this error ValueError: An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: ` I should check the list of tables to see if there is a table called MINI_FACTORY
Action: sql_db_list_tables, ""`
4. Please recommend the right way of connecting to the oracle sql developer database

### Description

I'm trying to query the oracle SQL developer DB for getting answer in the natural language. But, going into lots of issues as mentioned above.

Please help me out :)

### System Info

Name: langchain
Version: 0.1.8
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author: 
Author-email: 
License: MIT
Location: C:\Users\ajm1nh3\AppData\Local\anaconda3\envs\sample\Lib\site-packages
Requires: aiohttp, dataclasses-json, jsonpatch, langchain-community, langchain-core, langsmith, numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: langchain-experimental
Note: you may need to restart the kernel to use updated packages.

Name: openai
Version: 0.28.0
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
Required-by: langchain-openai

**Comment by liugddx** [comment]
agent_type="openai-tools" and try again. You can refer to  https://python.langchain.com/docs/use_cases/sql/agents#agent

**Comment by cjbj** [comment]
@AJAYM888 A late comment: [python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) replaced cx_Oracle two years ago.  It is natively supported in SQLAlchemy 2, but can also be used in SQLAlchemy 1.4.  See [Using SQLAlchemy 2.0 with python-oracledb for Oracle Database](https://medium.com/oracledevs/using-the-development-branch-of-sqlalchemy-2-0-with-python-oracledb-d6e89090899c).

Install with `python -m pip install oracledb` and then use:

```
engine = create_engine(
    f'oracle+oracledb://:@',
        thick_mode=False,
        connect_args={
            "user": username,
            "password": password,
            "host": host,
            "port": port,
            "service_name": service_name
    })
```
