### ISSUE TITLE
Langsmith: Getting random "Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"..." is longer than 128 characters"}\')')

### ISSUE THREAD

**Issue by ldorigo** [langchain-ai/langchain#17950]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

Making a repro will be a *lot* of work for what is likely a fairly simple server-side issue of langsmith. If it isn't, let me know and I'll try to do a repro.

### Error Message and Stack Trace (if applicable)

Failed to batch ingest runs: LangSmithError('Failed to post https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'422 Client Error: unknown for url: [https://api.smith.langchain.com/runs/batch\](https://api.smith.langchain.com/runs/batch/)', \'{"detail":"[\\\'post\\\', \\\'items\\\', \\\'properties\\\', \\\'name\\\', \\\'maxLength\\\']: \\\\"ChannelRead<[\\\'raw_conversation\\\', \\\'messages\\\', \\\'query\\\', \\\'assistant_id\\\', \\\'assistant_nickname\\\', \\\'user_name\\\', \\\'user_roles\\\', \\\'organization_name\\\']>\\\\" is longer than 128 characters"}\')')

### Description

I started having these errors from langsmith when using it to trace langgraph runs. It ran fine until a couple of days ago, might be an issue with the latest version of langsmith?

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 ZEN SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:37 +0000
> Python Version:  3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]

Package Information
-------------------
> langchain_core: 0.1.19
> langchain: 0.1.4
> langchain_community: 0.0.16
> langsmith: 0.0.84
> langchain_openai: 0.0.5
> langchainhub: 0.1.14
> langgraph: 0.0.21

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by ldorigo** [comment]
Sorry, moving this to the langsmith repo (I think it belongs there)

**Comment by rpgoldman** [comment]
@ldorigo would you mind adding a link from this issue to the one on LangSmith? Thanks!
