### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 55: illegal multibyte sequence

### ISSUE THREAD

**Issue by Nilljsp** [langchain-ai/langchain#17995]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

langchain_core->prompts->loading.py->load_template  line46
with open(template_path) as f:

### Error Message and Stack Trace (if applicable)

UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 55: illegal multibyte sequence

### Description

The default encoding mode of the Windows system is 'gbk', and you need to specify the decoding mode as 'utf-8'.
langchain_core->prompts->loading.py->load_template  line46
with open(template_path) as f:  ->  with open(template_path, encoding="utf-8") as f:

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.25
> langchain: 0.1.8
> langchain_community: 0.0.21
> langsmith: 0.1.5
> langchain_experimental: 0.0.51
> langchain_openai: 0.0.6

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by xishengping** [comment]
langchain_community\document_loaders\directory.py中修改221行，加上utf-8

loader = self.loader_cls(str(item), **self.loader_kwargs,encoding='utf-8')
