### ISSUE TITLE
BadRequest Error on Simple Query to NotionDB Database Using notion_db_secret and database_id, due to passing empty dict in json for filter by default

### ISSUE THREAD

**Issue by adorabledev** [langchain-ai/langchain#18009]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
from getpass import getpass

NOTION_TOKEN = getpass()
DATABASE_ID = getpass()

········
········

from langchain_community.document_loaders import NotionDBLoader

loader = NotionDBLoader(
    integration_token=NOTION_TOKEN,
    database_id=DATABASE_ID,
    request_timeout_sec=30,  # optional, defaults to 10
)

docs = loader.load()

print(docs)

```
### Error Message and Stack Trace (if applicable)

b'{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one:\\nbody.filter.or should be defined, instead was `undefined`.\\nbody.filter.and should be defined, instead was `undefined`.\\nbody.filter.title should be defined, instead was `undefined`.\\nbody.filter.rich_text should be defined, instead was `undefined`.\\nbody.filter.number should be defined, instead was `undefined`.\\nbody.filter.checkbox should be defined, instead was `undefined`.\\nbody.filter.select should be defined, instead was `undefined`.\\nbody.filter.multi_select should be defined, instead was `undefined`.\\nbody.filter.status should be defined, instead was `undefined`.\\nbody.filter.date should be defined, instead was `undefined`.\\nbody.filter.people should be defined, instead was `undefined`.\\nbody.filter.files should be defined, instead was `undefined`.\\nbody.filter.url should be defined, instead was `undefined`.\\nbody.filter.email should be defined, instead was `undefined`.\\nbody.filter.phone_number should be defined, instead was `undefined`.\\nbody.filter.relation should be defined, instead was `undefined`.\\nbody.filter.created_by should be defined, instead was `undefined`.\\nbody.filter.created_time should be defined, instead was `undefined`.\\nbody.filter.last_edited_by should be defined, instead was `undefined`.\\nbody.filter.last_edited_time should be defined, instead was `undefined`.\\nbody.filter.formula should be defined, instead was `undefined`.\\nbody.filter.unique_id should be defined, instead was `undefined`.\\nbody.filter.rollup should be defined, instead was `undefined`.","request_id":"a251ecce-5757-44bf-a5f1-c4d7582d72dd"}'

### Description

getting 400, Bad Request

### System Info

langchain==0.1.9
langchain-community==0.0.22
langchain-core==0.1.26

**Comment by adorabledev** [comment]
hmm, seems it's actually there... https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/document_loaders/notiondb.py#L55

**Comment by gagip** [comment]
I am also experiencing the same issue as described above. The behavior does not work as expected for me either.

**Comment by Carr1005** [comment]
Same here:

```
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.notion.com/v1/databases/{database-id}/query
```

**Comment by rivamarco** [comment]
Exactly the same issue here even with latest version
