### ISSUE TITLE
Error when overriding default prompt template of ConversationChain 

### ISSUE THREAD

**Issue by universe6666** [langchain-ai/langchain#1800]
Hi, does anyone know how to override the prompt template of ConversationChain? I am creating a custom prompt template that takes in an additional input variable 
```
PROMPT_TEMPLATE = """ {my_info}
{history}
Human: {input}
AI:"""

PROMPT = PromptTemplate(
    input_variables=["history", "input", "my_info"], template=PROMPT_TEMPLATE
)

conversation_chain = ConversationChain(
    prompt=PROMPT,
    llm=OpenAI(temperature=0.7), 
    verbose=True, 
    memory=ConversationBufferMemory()
)
```

but got the following error:
```
Got unexpected prompt input variables. The prompt expects ['history', 'input', 'my_info'], but got ['history'] as inputs from memory, and input as the normal input key. (type=value_error)
```

Is my understanding correct that currently ConversationChain can only support prompt template that takes in "history" and "input" as the input variables?

**Comment by hwchase17** [comment]
yes you're correct - conversation chain only currently allows for a single input, that being the input key, and then also history (coming from memory)

**Comment by tezer** [comment]
How should I handle this situation if I want to add _context_?

```
system_template="""Use the following pieces of context to answer the users question. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.
----------------
{context}"""
messages = [
    SystemMessagePromptTemplate.from_template(system_template),
    MessagesPlaceholder(variable_name="history"),
    HumanMessagePromptTemplate.from_template("{input}")
]
```

**Comment by mrbende** [comment]
I'm looking into this issue as well. Is it possible to add additional context and to the systemprompt for ConversationChain?

**Comment by SoulEvill** [comment]
I am facing the similar issue. There are use cases when we need customization for prompt in ConversationChain. Current implementation does not support that and really hope langchain can support customize prompt and make conversationchain more flexible and even better to consider different prompt as conversation goes. To some extent, it sounds more like Agent instead of Chain, is there a agent class that is capable of similar thing?

**Comment by ulucinar** [comment]
I've opened a [PR]() that I believe addresses this issue. My understanding is that currently [Conversation chain's memory](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/chains/conversation/base.py#L23) does not inherit the conversation chains [`input_key`](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/chains/conversation/base.py#L28) and we try to deduce it with [`get_prompt_input_key`](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/memory/utils.py#L10) assuming it there are only memory, input and `stop` variables. The PR suggests that the memory of the conversation chain inherits the conversation chains `input_key`. 
As exemplified in the PR, with the proposed change we can use a system prompt such as the following:
```python
system_msg_template = SystemMessagePromptTemplate.from_template(template="You are a translator helping me in translating from {input_language} to {output_language}. " + 
    "Please translate the messages I type.")
```

What do you think @hwchase17?

**Comment by notedit** [comment]
I'm looking into this issue as well,

**Comment by firaskudsy** [comment]
any update on this issue

**Comment by GianottiGustavo** [comment]
I need this case too.

**Comment by Gogoboy123** [comment]
Same for me, it would be a lot easier to get good results for other language than English and improve the first response

**Comment by Bonobo791** [comment]
Fix please!

**Comment by hussainwali74** [comment]
??

**Comment by edmondop** [comment]
What's the current work around for this? Using a single prompt template that has an input putting the SystemMessage and the HumanMessage there?

**Comment by ragzman** [comment]
This is very weird. I can get ConversationChain to work with multiple inputs in the JS library, but it fails in python. 
I moved my whole app to python to make it faster.. and now this. :-(

**Comment by usamimeri** [comment]
I also encounter the same problem.It seems that you can't use customized variable to replace the "input" placeholder.

**Comment by edugargar** [comment]
Do we have any updates on this one?

**Comment by Bonobo791** [comment]
@hwchase17

**Comment by unmotivatedgene** [comment]
I too am waiting on this.

**Comment by zxdream64230** [comment]
same here :)

**Comment by Hallimede** [comment]
Same here

**Comment by vickwv** [comment]
Same here

**Comment by Bananenfraese** [comment]
As a workaround I'm just subclassing the memory and use that instead like this...

```
class ExtendedConversationBufferMemory(ConversationBufferMemory):
    extra_variables:List[str] = []

    @property
    def memory_variables(self) -> List[str]:
        """Will always return list of memory variables."""
        return [self.memory_key] + self.extra_variables

    def load_memory_variables(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """Return buffer with history and extra variables"""
        d = super().load_memory_variables(inputs)
        d.update({k:inputs.get(k) for k in self.extra_variables})        
        return d
```

...then initialize the chain with an instance of that memory class

```
    llm_chain = ConversationChain(
        llm=llm,
        prompt=prompt,
        memory=ExtendedConversationBufferMemory(extra_variables=["context"]) 
    )

```

After that I just add the "context" (and any other extra variables) by passing them via the input when calling the chain:

`result = llm_chain({"input": "some input", "context": "whatever context"})`

I'm not sure whether this is a good way to do it, but it works fine in my case, so maybe it will also work for others.

**Comment by njc-ai** [comment]
Hi!

Is this what you all are looking for?

https://github.com/hwchase17/langchain/issues/5462

I was able to use this to set a new system message

**Comment by ColinTitahi** [comment]
Glad I found this though I must have been missing something obvious. 
Seems a very strange limitation given it's a template. Looks like I'll basically have to add my own templating for my own vars ( I just want to add the date at the top) and then have a horrid string in my code to turn it into a magical langchain template with the two allowed variables for this chain.

**Comment by ColinTitahi** [comment]
Glad I saw this though I was missing something obvious.
My horrid kludge is to add what I need to the beginning of the template 
e.g PROMPT.template  = f'The current date is {todayFormat}.' + PROMPT.template

**Comment by wnmurphy** [comment]
> How should I handle this situation if I want to add _context_?
> 
> ```
> system_template="""Use the following pieces of context to answer the users question. 
> If you don't know the answer, just say that you don't know, don't try to make up an answer.
> ----------------
> {context}"""
> messages = [
>     SystemMessagePromptTemplate.from_template(system_template),
>     MessagesPlaceholder(variable_name="history"),
>     HumanMessagePromptTemplate.from_template("{input}")
> ]
> ```

For what it's worth I use this pattern, but I inject contextual data into my main prompt, and then make that the initial system message. Then you have the interaction frame and instructions, any contextual data, the chat history, then the next input.

**Comment by isaacsbox** [comment]
> Hi! Even though @Bananenfraese 's solution might work, I'd let template classes do template things. As someone said above, ConversationChain only allows to use 'history', and 'input' as input variables for the PromptTemplate, nothing more, nothing less. In you're interested in the related code, (and understand why @Bananenfraese 's solution works), check this: method:https://github.com/hwchase17/langchain/blob/fcb3a647997c6275e3d341abb032e5106ea39cac/langchain/chains/conversation/base.py#L44
> 
> However, you can just pass those values to the PromptTemplate and let it use them. Here is the example from @universe6666 modified:
> 
> ```
> PROMPT_TEMPLATE = """ {my_info}
> {history}
> Human: {input}
> AI:"""
> 
> 
> # define a custom PromptTemplate that supports your new variables
> class CustomPromptTemplate(StringPromptTemplate):
>    my_info: str
> 
>   def format(self, **kwargs) -> str:
>     kwargs['my_info']=self.my_info
>     return self.template.format(**kwargs)
> 
> 
> # make sure you feed the PromptTemplate with the new variables
> PROMPT = CustomPromptTemplate(
>     input_variables=["history", "input"], template=PROMPT_TEMPLATE, my_info="whatever"
> )
> 
> 
> conversation_chain = ConversationChain(
>     prompt=PROMPT,
>     llm=OpenAI(temperature=0.7), 
>     verbose=True, 
>     memory=ConversationBufferMemory()
> )
> ```
> 
> Disclaimer: not tested but enough for you to know a clean way to solve this

I got "AttributeError: 'CustomPromptTemplate' object has no attribute 'template'"

**Comment by fitlemon** [comment]
> extra_variables=["context"]

It's worked for me. Anybody know, do they fix this issue? (putting context in ConversationChain prompt at every run)

**Comment by fahim9778** [comment]
> I've opened a [PR](https://github.com/hwchase17/langchain/pull/2515) that I believe addresses this issue. My understanding is that currently [Conversation chain's memory](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/chains/conversation/base.py#L23) does not inherit the conversation chain's [`input_key`](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/chains/conversation/base.py#L28) and we try to deduce it with [`get_prompt_input_key`](https://github.com/hwchase17/langchain/blob/f240651bd8275c3380fefc335473bf7b0a07673e/langchain/memory/utils.py#L10) assuming there are only memory, input and `stop` variables in the prompt. The PR suggests that the memory of the conversation chain inherits the conversation chain's `input_key`. As exemplified in the PR, with the proposed change we can use a system prompt template such as the following:
> 
> ```python
> system_msg_template = SystemMessagePromptTemplate.from_template(template="You are a translator helping me in translating from {input_language} to {output_language}. " + 
>     "Please translate the messages I type.")
> ```
> 
> What do you think @hwchase17?

@ulucinar it isn't fixed yet. I am using this for my project and getting the same error if I have anything as placeholder other than those `history` and `input`. Can you suggest any workaround please? I saw your PR but passing the placeholders at each `predict()` might not a feasible case. @hwchase17 any chance we will get  an updated fix on this please?

**Comment by zeki-kadiroglu-aifa** [comment]
Is the issue that solved that @universe6666 asked?
