### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'int' and 'simsimd.OutputDistances'

### ISSUE THREAD

**Issue by mborho** [langchain-ai/langchain#18022]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
print("?")
```

### Error Message and Stack Trace (if applicable)

```
  File "/home/martin/dev/mlki/langchain/llmaa/env/lib/python3.10/site-packages/langchain_community/utils/math.py", line 29, in cosine_similarity
    Z = 1 - simd.cdist(X, Y, metric="cosine")
TypeError: unsupported operand type(s) for -: 'int' and 'simsimd.OutputDistances'
```

### Description

Error came up after installing langchain [v0.1.9](https://github.com/langchain-ai/langchain/releases/tag/v0.1.9) and the python bindings for [simsimd v3.8.1](https://pypi.org/project/simsimd/3.8.1/).

After switching the python package to [simsimd v3.7.7](https://github.com/ashvardanian/SimSIMD/releases/tag/v3.7.7), the error disappeared.

Seems to be related to this change https://github.com/ashvardanian/SimSIMD/commit/819a40666faf038613b2368d1810e2563fb9d422

### System Info

langchain==0.1.9
langchain-community==0.0.22
langchain-core==0.1.26
langchain-openai==0.0.7
langchainhub==0.1.14

**Comment by andy-tmpt-me** [comment]
Confirming that in my setup (which generally picks up langchain latest), pinning simsimd == 3.7.7 resolved the issue.

**Comment by ravi-bhanabhai** [comment]
Still an issue with the newest simsimd.

```
>>> simsimd.__version__
'4.0.0'
>>> import langchain
>>> langchain.__version__
'0.1.13'
>>>
```

**Comment by ashvardanian** [comment]
Hey! To convert to NumPy, you simply need to wrap the output tensor with `np.array` 🤗 

We couldn't continue returning the NumPy array directly, because surprisingly to us, NumPy doesn't support most platforms. [They only ship 35 binaries](https://pypi.org/project/numpy/#files), while [SimSIMD ships 105](https://pypi.org/project/simsimd/#files)... and on some platforms, they don't even pass compilation.

**Comment by yaoyuansheng0403** [comment]
> Confirming that in my setup (which generally picks up langchain latest), pinning simsimd == 3.7.7 resolved the issue.

it is helpful,my problem has solved. thank you
