### ISSUE TITLE
ChatOpenAI' object has no attribute 'bind_tools'

### ISSUE THREAD

**Issue by nimakhajehzadeh** [langchain-ai/langchain#18088]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

before i updated my langchain i have this code without any issue : 
llm=ChatOpenAI(temperature=0.0,model="gpt-4")
sql_toolkit=SQLDatabaseToolkit(db=db,llm=llm)
llm_with_tool = llm.bind_tools(analyze_tool)
sql_toolkit.get_tools()

but after updating my langchain i have got this error : 
'ChatOpenAI' object has no attribute 'bind_tools'

### Idea or request for content:

can anyone guide me how can i solve this issue ?

**Comment by keenborder786** [comment]
Can you try `bind_functions` instead of `bind_tools` please.

**Comment by RadhikaBansal97** [comment]
Hi @nimakhajehzadeh ,

I think you are importing ` langchain.chat_models import ChatOpenAI`

Langchain has refactored its structure and all the partner have their open package now 
1. Install langchain_openai `pip install langchain_openai`
2. And  use this `langchain_openai import ChatOpenAI`

**Comment by trujicata** [comment]
Same issue here! Following [this](https://python.langchain.com/docs/modules/agents/how_to/custom_agent#define-tools) tutorial, gives me the error `AttributeError: 'ChatOpenAI' object has no attribute 'bind_tools'`. langchain version is `0.1.9`

**Comment by trujicata** [comment]
Had the same issue and it got it fixed when:
1. Uninstalled `langchain`, `langchain-openai`, `langchain-community`, `langchain_experimental` 
2. Installed them again, specifying `langchain=0.1.9`.

**Comment by okwinds** [comment]
> ### Checklist
> * [x]  I added a very descriptive title to this issue.
> * [x]  I included a link to the documentation page I am referring to (if applicable).
> 
> ### Issue with current documentation:
> before i updated my langchain i have this code without any issue : llm=ChatOpenAI(temperature=0.0,model="gpt-4") sql_toolkit=SQLDatabaseToolkit(db=db,llm=llm) llm_with_tool = llm.bind_tools(analyze_tool) sql_toolkit.get_tools()
> 
> but after updating my langchain i have got this error : 'ChatOpenAI' object has no attribute 'bind_tools'
> 
> ### Idea or request for content:
> can anyone guide me how can i solve this issue ?

I encountered the same issue as you and resolved it in the following way:

Firstly, I uninstalled the packages:
`pip uninstall langchain langchain-openai langchain-community langchain_experimental
`
Then, I installed the specific versions:

`pip install langchain==0.1.12 langchain-openai==0.0.8
`

Now, my versions are as follows:

langchain: 0.1.12
langchain-openai: 0.0.8
Please note the difference between ”langchain-openai“ and ”langchain_openai“.

**Comment by okwinds** [comment]
> ### Checklist
> * [x]  I added a very descriptive title to this issue.
> * [x]  I included a link to the documentation page I am referring to (if applicable).
> 
> ### Issue with current documentation:
> before i updated my langchain i have this code without any issue : llm=ChatOpenAI(temperature=0.0,model="gpt-4") sql_toolkit=SQLDatabaseToolkit(db=db,llm=llm) llm_with_tool = llm.bind_tools(analyze_tool) sql_toolkit.get_tools()
> 
> but after updating my langchain i have got this error : 'ChatOpenAI' object has no attribute 'bind_tools'
> 
> ### Idea or request for content:
> can anyone guide me how can i solve this issue ?

I encountered the same issue as you and resolved it in the following way:

Firstly, I uninstalled the packages:
`pip uninstall langchain langchain-openai langchain-community langchain_experimental
`
Then, I installed:

`pip install langchain langchain_openai
`
Now, my versions are as follows:
langchain: 0.1.12
langchain-openai: 0.0.8
Please note the difference between ”langchain-openai“ and ”langchain_openai“.
