### ISSUE TITLE
DOC: Possible mistake in property's docstring of ConversationBufferWindowMemory

### ISSUE THREAD

**Issue by lgabs** [langchain-ai/langchain#18080]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Readiing `ConversationBufferWindowMemory` class, it seems that the property `buffer` returns `self.buffer_as_messages` if `self.return_messages` is `True`, otherwise it returns `self.buffer_as_str`.

https://github.com/langchain-ai/langchain/blob/7fc903464a753ac10e9b671906c2e9889e4d598e/libs/langchain/langchain/memory/buffer_window.py#L17-L21

However, the docstrings of these properties `buffer_as_str` and `return_messages` seem inverted when they say `True` and `False` respectively:

https://github.com/langchain-ai/langchain/blob/7fc903464a753ac10e9b671906c2e9889e4d598e/libs/langchain/langchain/memory/buffer_window.py#L22-L30

https://github.com/langchain-ai/langchain/blob/7fc903464a753ac10e9b671906c2e9889e4d598e/libs/langchain/langchain/memory/buffer_window.py#L32-L35

**Comment by keenborder786** [comment]
@lgabs nice catch ,created a PR for the fix.

**Comment by lgabs** [comment]
@keenborder786 am I mistaken or there is still a change to make in `buffer_as_messages`?

https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer_window.py#L22-L36

I've updated this in this new PR: https://github.com/langchain-ai/langchain/pull/18136
