### ISSUE TITLE
issue with pinecone similarity_search function

### ISSUE THREAD

**Issue by butzhang** [langchain-ai/langchain#1809]
While I am trying to rebuild chat_pdf based on mayo's example.
I noticed that vector store with pinecone doesn't respond with similar docs when it performs similarity_search function.
I test it against other vector provider like faiss and chroma. In both cases, those all works.
Here is the [code link](https://github.com/butzhang/simple_chat_pdf/blob/main/simple_chat_pdf/components/question_handler.py#L28-L30)

Steps to reproduce.
"""
from simple_chat_pdf.components.question_handler import QuestionHandler
question = 'what is this legal case about'
r = QuestionHandler().get_answer(question=question, chat_history=[])
"""
You can switch from different vector and see only pinecone provide failed and didn't find similar docs
you need to switch to your open_api key because mine might expire

**Comment by websperoops** [comment]
Did you find any solution for this
