### ISSUE TITLE
AzureOpenAIEmbedding raises errors due to deprication of openai_api_base

### ISSUE THREAD

**Issue by konradbjk** [langchain-ai/langchain#18099]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

code

```python
from langchain_openai import AzureOpenAIEmbeddings
from dotenv import load_dotenv


load_dotenv()


azure_embeddings = AzureOpenAIEmbeddings(
    azure_deployment="<model_deployment>",
    openai_api_version="2023-05-15",
)
```

and envs
```
AZURE_OPENAI_ENDPOINT=https://<MY PROJECT>.openai.azure.com/
AZURE_OPENAI_API_KEY=...
```

I can see while debugging that the azure_deployment is set properly, though the error still makes it impossible to run

I have tried setting `validate_base_url = False` but then it throws an error that base_url and azure_deployment and exclusive

### Error Message and Stack Trace (if applicable)
```
1 validation error for AzureOpenAIEmbeddings
__root__
  As of openai>=1.0.0, Azure endpoints should be specified via the `azure_endpoint` param not `openai_api_base` (or alias `base_url`).  (type=value_error)
  File "/<REDACTED>, line 12, in <module>
    azure_embeddings = AzureOpenAIEmbeddings(
pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
__root__
  As of openai>=1.0.0, Azure endpoints should be specified via the `azure_endpoint` param not `openai_api_base` (or alias `base_url`).  (type=value_error)
```

### Description

pydantic should not throw an error

### System Info

```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64
> Python Version:  3.8.18 | packaged by conda-forge | (default, Dec 23 2023, 17:23:49) 
[Clang 15.0.7 ]

Package Information
-------------------
> langchain_core: 0.1.26
> langchain: 0.1.9
> langchain_community: 0.0.24
> langsmith: 0.1.8
> langchain_openai: 0.0.7
```

**Comment by konradbjk** [comment]
After trial and error I can make it work with:
`python==3.9.18` and `langchain_openai==0.0.6`

**Comment by Yashar78** [comment]
In my case the problem was that the OPENAI_API_KEY was present in .env file and somehow pymilvus sources that file without me knowing it. So try to find where you have OPENAI_API_KEY and rename or remove it.
