### ISSUE TITLE
AttributeError on opentelemetry when initializing Chroma from documents

### ISSUE THREAD

**Issue by duarte-sardao** [langchain-ai/langchain#18093]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings
from chromadb.config import Settings

db = Chroma.from_documents(texts, OpenAIEmbeddings(disallowed_special=()), client_settings= Settings( anonymized_telemetry=False))
retriever = db.as_retriever(
    search_type="mmr",  # Also test "similarity"
    search_kwargs={"k": 8},
)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "lchain.py", line 26, in <module>
    from chromadb.config import Settings
  File "/home/duarte/.local/lib/python3.8/site-packages/chromadb/__init__.py", line 5, in <module>
    from chromadb.auth.token import TokenTransportHeader
  File "/home/duarte/.local/lib/python3.8/site-packages/chromadb/auth/token/__init__.py", line 26, in <module>
    from chromadb.telemetry.opentelemetry import (
  File "/home/duarte/.local/lib/python3.8/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 11, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
  File "/home/duarte/.local/lib/python3.8/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 24, in <module>
    from opentelemetry.exporter.otlp.proto.common.trace_encoder import (
  File "/home/duarte/.local/lib/python3.8/site-packages/opentelemetry/exporter/otlp/proto/common/trace_encoder.py", line 16, in <module>
    from opentelemetry.exporter.otlp.proto.common._internal.trace_encoder import (
  File "/home/duarte/.local/lib/python3.8/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/trace_encoder/__init__.py", line 44, in <module>
    SpanKind.INTERNAL: PB2SPan.SpanKind.SPAN_KIND_INTERNAL,
AttributeError: 'EnumTypeWrapper' object has no attribute 'SPAN_KIND_INTERNAL'

### Description

Trying to follow the Code understanding tutorial (https://python.langchain.com/docs/use_cases/code_understanding#use-case), find myself with an AttributeError related to opentelemetry. Tried reinstall the appropriate packages and turning off the usage of telemetry when initializing chroma but the issue persists.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Apr 2 22:23:49 UTC 2021
> Python Version:  3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0]

Package Information
-------------------
> langchain_core: 0.1.26
> langchain: 0.1.9
> langchain_community: 0.0.24
> langsmith: 0.1.7
> langchain_openai: 0.0.7

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by liugddx** [comment]
What version of opentelemetry

**Comment by timtensor** [comment]
@liugddx i have the same issue i have opentelemetry-sdk version 1.23.0

**Comment by Bavalpreet** [comment]
I am running the very first notebook of your tutorial - https://github.com/langchain-ai/rag-from-scratch/blob/main/rag_from_scratch_1_to_4.ipynb

![Screenshot from 2024-03-28 11-51-41](https://github.com/langchain-ai/langchain/assets/42736937/1ad57dbb-6650-46ca-a504-7cf5811b3153)


AttributeError: 'EnumTypeWrapper' object has no attribute 'SPAN_KIND_INTERNAL'

**Comment by scriplit** [comment]
this fixed it for me:
pip install opentelemetry-exporter-otlp --upgrade
