### ISSUE TITLE
AzureChatOpenAI failed to accept openai_api_base, throwing error 

### ISSUE THREAD

**Issue by sheikalthaf** [langchain-ai/langchain#1810]
Error Message:
![image](https://user-images.githubusercontent.com/22526247/226255025-23efc899-74f6-4050-aac0-b1dc08dc298b.png)

Usage:

I currently using **AzureChatOpenAI** with below parameters
![image](https://user-images.githubusercontent.com/22526247/226255310-8b28a2eb-6ea6-428d-b818-72776135f721.png)

But it is not taking the value from parameter and throwing error.

**Comment by masta-g3** [comment]
I think you need to add them directly as environment variables. I.e.:

```
import os

os.environ["OPENAI_API_TYPE"] = "azure"
...
```
etc...
