### ISSUE TITLE
Neo4jVector.from_documents doesn't set the index_name and keyword_index_name

### ISSUE THREAD

**Issue by younes-io** [langchain-ai/langchain#18126]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
index_name = f"vector_{index_suffix}"
keyword_index_name = f"keyword_{index_suffix}"

print(f"Setup with indices: {index_name} and {keyword_index_name} ")

hybrid_db = Neo4jVector.from_documents(
            docs,
            embeddings,
            url=url,
            username=username,
            password=password,            
            search_type="hybrid",
            pre_delete_collection=True,
            index_name=index_name,
            keyword_index_name=keyword_index_name,
        )
        
        print(f"\nLoaded hybrid_db {hybrid_db.search_type} with indices: {hybrid_db.index_name} and {hybrid_db.keyword_index_name} ")
        print(f"Embedded {index_suffix}\nsize of docs: {len(docs)}\n")
```

### Error Message and Stack Trace (if applicable)

Setup with indices: vector_data and keyword_data 

Loaded hybrid_db hybrid with indices: vector and keyword 
Embedded data
size of docs: 543

### Description

* `Neo4jVector.from_documents` does not seem to set up the values of `index_name` and `keyword_index_name`
* They should be set as I do explicitly in the code

### System Info

$ python -m langchain_core.sys_info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Thu Oct 5 21:02:42 UTC 2023
> Python Version:  3.12.2 (main, Feb  7 2024, 21:49:26) [GCC 10.2.1 20210110]

Package Information
-------------------
> langchain_core: 0.1.26
> langchain: 0.1.9
> langchain_community: 0.0.24
> langsmith: 0.1.7
> langchain_openai: 0.0.7

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by younes-io** [comment]
Hi @baskaryan: any thoughts on this one, like a workaround, please?

Thank you!

**Comment by baskaryan** [comment]
cc @tomasonjo

**Comment by tomasonjo** [comment]
Can you post `SHOW INDEXES` command results using the `query` method. You have created some indexes previously, and there are some limitations of Neo4j that you can't have two vector indexes on the same node label and property, which we do not handle atm. Better yet, can you show the code that you used to create all the indexes?
