### ISSUE TITLE
During the tracing of ChatVectorDBChain, even though it shows source_documents but when clicked on Explore, source_documents suddenly becomes [object Object],[object Object]

### ISSUE THREAD

**Issue by srithedesigner** [langchain-ai/langchain#1815]
During the tracing of ChatVectorDBChain, even though it shows source_documents but when clicked on Explore, source_documents suddenly becomes [object Object],[object Object].

Here is an example:

![image](https://user-images.githubusercontent.com/59601228/226320060-a1adf3c5-01d7-4d2b-a978-5ba505749d7b.png)

and then after clicking on explore button:
![image](https://user-images.githubusercontent.com/59601228/226320223-b41cbd06-6f91-4dd9-a2aa-8d7b80812ea1.png)

**Comment by hwchase17** [comment]
are you using ChatOpenAI model? or normal OpenAI model?

**Comment by srithedesigner** [comment]
Currently, we are using AzureOpenAI **text-davinci-003** model
