### ISSUE TITLE
Can not import langchain and langchain_openai

### ISSUE THREAD

**Issue by kashyap-aditya** [langchain-ai/langchain#18228]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

from langchain_openai import AzureChatOpenAI

or go to pdb, and simply run: import langchain_openai

### Error Message and Stack Trace (if applicable)

ImportError: cannot import name 'PydanticOutputParser' from 'langchain_core.output_parsers' (/mnt/.venv/lib/python3.8/site-packages/langchain_core/output_parsers/__init__.py)

### Description

Simply importing langchain_openai based on the recommendation from : https://python.langchain.com/docs/integrations/chat/azure_chat_openai

breaks the code.

I can see that langchain_openai is trying to import 'PydanticOutputParser' from 'langchain_core.output_parsers' but no such export exists.

I uninstalled everything and reinstalled all the packages.

### System Info

langchain==0.1.9
langchain-community==0.0.24
langchain-core==0.1.27
langchain-openai==0.0.8

**Comment by konradbjk** [comment]
Try with python 3.9.18. This part work for me, though FAISS is not working ;/

**Comment by HRUSHI1212** [comment]
Did you get resolution for this ?

**Comment by Amin5434** [comment]
> @kashyap-aditya Did you get resolution for this ?

I have the same issue, so if you have any piece of solution..

**Comment by HRUSHI1212** [comment]
i tried restarting the session and it worked for me

**Comment by konradbjk** [comment]
For me, a new repo helped. Also, keep an eye if one of the files is not called "langchain.py" or "faiss" or any other public package name
