### ISSUE TITLE
Bedrock llm fails with invoke endpoint in LangServe

### ISSUE THREAD

**Issue by clarkebishop** [langchain-ai/langchain#18224]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python
bedrock_client = boto3_session.client("bedrock-runtime")
model = "anthropic.claude-v2:1"  
model_kwargs = { #AI21
    "max_tokens_to_sample": 4096,
    "temperature": 0.2,
    "top_p": 1,
    "top_k": 250,
    "stop_sequences": [],
}

llm = Bedrock(
    model_id=model,
    client = bedrock_client,
    model_kwargs=model_kwargs
    )

prompt = ChatPromptTemplate.from_template("Tell me about {topic}. Explain your reasoning.")

output_parser = StrOutputParser()

joke_chain = (
    prompt
    | llm
    | output_parser
)
```

### Error Message and Stack Trace (if applicable)

    raise ValueError("Streaming must be set to True for async operations. ")
ValueError: Streaming must be set to True for async operations.

### Description

I have the chain above wrapped in a LangServe endpoint.

The **stream** endpoint works correctly. The **invoke** endpoint fails with a 500 Internal Server error and with the error shown above in the logs.

But, invoke, is supposed to be a synchronous operation.

### System Info

pip freeze
langchain==0.1.9
langchain-community==0.0.24
langchain-core==0.1.27

langserve==0.0.43

platform AWS Linux

python version 3.11.6

**Comment by kinivi** [comment]
@clarkebishop same, did you solve it?

**Comment by clarkebishop** [comment]
I did not solve it directly @kinivi. I am planning to try a work around. Here's the idea. Use a RunnableLambda and call Bedrock via boto3. That removes the dependency on the Bedrock LangChain integration.

I'll let you know how that works out.

Also, streaming does work. Just not INVOKE. Depending on your use case, you could just use the STREAM endpoint.
