### ISSUE TITLE
max_token limit is not followed when using chain

### ISSUE THREAD

**Issue by pranjaldoshi96** [langchain-ai/langchain#18248]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.

### Example Code

```python3
import os
from langchain_core.prompts import PromptTemplate, ChatPromptTemplate
from langchain_nvidia_ai_endpoints import ChatNVIDIA, NVIDIAEmbeddings
from langchain_core.output_parsers import StrOutputParser

os.environ["NVIDIA_API_KEY"] = "nvapi-*"

prompt_template = "You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Please ensure that your responses are positive in nature."
llm = ChatNVIDIA(model="mixtral_8x7b", max_tokens=32)
pt = PromptTemplate.from_template(prompt_template)
chain = pt | llm | StrOutputParser()
resp = chain.stream({"context_str": "", "query_str": "What is nvlink"})
count = sum(1 for _ in (print(chunk) for chunk in resp))
print("Token count:", count)
```

### Description

I am using ChatNvidia to build a chain. I have specified `max_tokens` to 32 and trying to generate response. But number of tokens generated are more than that. In above example it's around 78, even though max_tokens limit is already set. 

Point to note is when I simply create object of ChatNvidia and invoke it works as expected. 
```python3
llm = ChatNVIDIA(model="mixtral_8x7b", max_tokens=32)
llm.invoke("Hi")
```

### System Info

Version details are added below
```
$ pip3 freeze | grep langchain
langchain==0.0.352
langchain-community==0.0.7
langchain-core==0.1.3
langchain-nvidia-ai-endpoints==0.0.1
langchain-nvidia-trt==0.0.1rc0
```

I am using ubuntu 22.04

**Comment by mattf** [comment]
i can reproduce this with langchain-nvidia-ai-endpoints==0.0.1, token count of 50

i cannot reproduce this with langchain-nvidia-ai-endpoints==0.0.6

@pranjaldoshi96 will you confirm this is fixed?

**Comment by pranjaldoshi96** [comment]
Thanks.. yes it seems to be resolved with latest version.
