### ISSUE TITLE
DOC: https://python.langchain.com/docs/expression_language/streaming Document correction

### ISSUE THREAD

**Issue by liyangwd** [langchain-ai/langchain#18247]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

[Document correction](https://python.langchain.com/docs/expression_language/streaming)
The tips
An LCEL chain constructed using using non-streaming components, will still be able to stream in a lot of cases, with streaming of partial output starting after the last non-streaming step in the chain.

repeat word "using"

**Comment by sepiatone** [comment]
Fixed by https://github.com/langchain-ai/langchain/pull/18249, this could be closed.
