### ISSUE TITLE
Validation  error- Metadata should not be empty or None

### ISSUE THREAD

**Issue by Abonia1** [langchain-ai/langchain#1825]
I am experiencing an issue with Chroma:

`Chroma.from_texts(texts=chunks, embedding=embeddings, persist_directory=config.PERSIST_DIR, metadatas=None)`

opt/anaconda3/lib/python3.8/site-packages/langchain/vectorstores/chroma.py", line 27, in <listcomp>
    (Document(page_content=result[0], metadata=result[1]), result[2])
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document
metadata
  none is not an allowed value (type=type_error.none.not_allowed)
  
  Thanks for all the help!

**Comment by jeffchuber** [comment]
@Abonia1 this PR may help! https://github.com/hwchase17/langchain/pull/1714

can you try upgrading to the latest version of langchain? tag me if it doesnt work!
