### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by tomsib2001** [langchain-ai/langchain#1827]
The current documentation https://langchain.readthedocs.io/en/latest/modules/agents/getting_started.html seems to not be up to date with version 0.0.117:

```shell
 UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
 ```
 
 EDIT: to be more precise, this only happens if I try to change model_name to "gpt-3.5-turbo"

**Comment by Rammstein-1994** [comment]
I have the same warning.

```python
bot = VectorDBQA.from_llm(
        k=4,
        llm=OpenAI(model_name="gpt-3.5-turbo", temperature=0),
        vectorstore=db,
        return_source_documents=True,
    )
```

**Comment by msti** [comment]
Try using 
```python
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
```

**Comment by lethe3000** [comment]
I want to create `GPTSimpleVectorIndex.query` with `llm_predictor`.
But I met warning:
You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: 
`from langchain.chat_models import ChatOpenAI`

so how to I modify my code to supress this warning
```from llama_index import PromptHelper, LLMPredictor, SimpleDirectoryReader, GPTSimpleVectorIndex
from langchain import OpenAI
from langchain.chat_models import ChatOpenAI
args = dict(
        temperature=0.5,
        model_name='gpt-3.5-turbo',
        max_tokens=2000,
    )
llm = LLMPredictor(llm=OpenAIChat(**args))

GPTSimpleVectorIndex(SimpleDirectoryReader('/path').load_data(), llm_predictor=llm, ...).query('some questiongs')
```

**Comment by ismaelc** [comment]
It also throws that error for [LLMMathChain](https://langchain.readthedocs.io/en/latest/modules/agents/examples/custom_tools.html?highlight=llm_math_chain.run#tool-dataclass) when I had to use `OpenAI()` as llm parameter

**Comment by NickDatLe** [comment]
I did the same thing:

```
from langchain import OpenAI
# from langchain.chat_models import ChatOpenAI

llm = OpenAI(model_name="gpt-4", temperature=0.9)
# llm = ChatOpenAI(model_name="gpt-4", temperature=0.9)
```

I still get the same errors:
```

[/Users/nick/Library/Caches/pypoetry/virtualenvs/chatmfl-wJULhpjL-py3.10/lib/python3.10/site-packages/langchain/llms/openai.py:169](https://file+.vscode-resource.vscode-cdn.net/Users/nick/Library/Caches/pypoetry/virtualenvs/chatmfl-wJULhpjL-py3.10/lib/python3.10/site-packages/langchain/llms/openai.py:169): UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
[/Users/nick/Library/Caches/pypoetry/virtualenvs/chatmfl-wJULhpjL-py3.10/lib/python3.10/site-packages/langchain/llms/openai.py:608](https://file+.vscode-resource.vscode-cdn.net/Users/nick/Library/Caches/pypoetry/virtualenvs/chatmfl-wJULhpjL-py3.10/lib/python3.10/site-packages/langchain/llms/openai.py:608): UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
  warnings.warn(
```

**Comment by Wanyi9988** [comment]
> ```python
> llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
> ```


As a novice, I wonder how to pass vectorstore into this function

**Comment by eh-dub** [comment]
> Try using
> 
> ```python
> from langchain.chat_models import ChatOpenAI
> llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
> ```

How does memory work with the `ChatOpenAI` constructor? With the LLMChain, it was a constructor parameter:

```
chatgpt_chain = LLMChain(
        llm=OpenAI(temperature=0, model_name="gpt-3.5-turbo", streaming=False, callback_manager=callback_manager), 
        prompt=prompt, 
        verbose=True, 
        memory=memory,
        callback_manager=callback_manager
    )
```

**Comment by SamMakesThings** [comment]
Why is the chat model warning set to go off for gpt-4? Isn't GPT-4 a completion model?

**Comment by MALathon** [comment]
I was under the impression that GPT-4 was a text completion model.

**Comment by marcellsimon** [comment]
As this issue is still open:
gpt-3.5-turbo is a Chat model, not a completion model. Same for gpt-4.
OpenAI llm is a completion model, not a Chat model, that's why you get this warning. 
The currently most advanced available completion model is text-davinci-003.

`llm = OpenAI(model_name="text-davinci-003")`

**Comment by aaryaman11** [comment]
> The current documentation https://langchain.readthedocs.io/en/latest/modules/agents/getting_started.html seems to not be up to date with version 0.0.117:
> 
> ```shell
>  UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI`
> ```
> 
> EDIT: to be more precise, this only happens if I try to change model_name to "gpt-3.5-turbo"

I used that i still have the same issue that it's not resolved

**Comment by felipeary91** [comment]
I'm currently getting this issue:
![image](https://github.com/langchain-ai/langchain/assets/46670671/362af56c-72e8-40ec-aefb-f3b26c6e1b35)

And the python script was working correctly literally two days ago. My importing is like this:
```
from gpt_index import SimpleDirectoryReader, GPTListIndex, GPTSimpleVectorIndex,LLMPredictor, PromptHelper
from langchain.chat_models import ChatOpenAI
import gradio as gr
import sys, time
import os
```
In the current documentation it doesn't seem to be a new way of importing.
