### ISSUE TITLE
DOC: documentation page for `BigQueryVectorSearch` is broken

### ISSUE THREAD

**Issue by ashleyxuu** [langchain-ai/langchain#18296]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The documentation page for BigQueryVectorSearch is broken: https://python.langchain.com/docs/integrations/vectorstores/bigquery_vector_search.

Anything I can help fix it?

**Comment by amanlai** [comment]
I believe the link is https://python.langchain.com/docs/integrations/vectorstores/google_bigquery_vector_search

**Comment by ashleyxuu** [comment]
> I believe the link is https://python.langchain.com/docs/integrations/vectorstores/google_bigquery_vector_search

Yes, this works, but we provide the previous link to Google customer. Is there any way we can direct the broken link to this one? @efriis 
<img width="977" alt="Screenshot 2024-03-02 at 9 52 23 AM" src="https://github.com/langchain-ai/langchain/assets/139821907/0cdcc815-3c36-4cb7-9dbd-9ecf5e762fb4">


If I google search this, it still directs me to the broken link:
