### ISSUE TITLE
ConversationTokenBufferMemory with RedisChatMessageHistory doesn't work, as it crashes due to exceeding the context limit.

### ISSUE THREAD

**Issue by audrito** [langchain-ai/langchain#18303]
### Checked other resources

- [X] I searched the LangChain documentation with the integrated search.
- [X] I added a very descriptive title to this issue.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

Here is a simple version of the code I'm trying to use.
```
llm = LlamaCpp(model_path=MODEL_PATH, n_ctx=2048, n_batch=512, max_tokens=-1)

history = RedisChatMessageHistory(session_id=session_id, url="redis://localhost:6379")

memory = ConversationTokenBufferMemory(llm=llm, max_token_limit=2048, chat_memory=history)

conversation = LLMChain(llm=llm, prompt=prompt, memory=memory)
```

### Description

While developing a chatbot, I used `ConversationTokenBufferMemory` with `RedisChatMessageHistory` to provide support for different users. It is aimed for storing and retrieving history as needed and loading it into memory to pass into the chain. But when it reaches `max_token_limit`, instead of forgetting the left most history to maintain the context length window, the app crashes because context length exceeded the limit.

What's wrong? `ConversationTokenBufferMemory` is supposed to automatically keep track of total tokens used in history and only keep the latest `n` number of tokens to avoid crashes, right?

### It might be a bug or a lack of support in the `ConversationTokenBufferMemory` class.

Expecting a solution that might sound something like this :

> If `chat_memory` = an object of `RedisChatMessageHistory`, then it should have a feature where it retrieves the entire history data from Redis as it is supposed to, but cleans up the history data to keep the last `max_token_limit` number of tokens before passing it as history in the chain. This way, when Langchain is used in production and has to juggle between multiple different users, this might come in handy.

### System Info

Platform : Windows
Python : 3.10.9
Langchain : Latest while posting this.

**Comment by codemee** [comment]
It didn't update the underlying Radis db so that the program would indeed pass all the messages to llm. See the code [here](https://github.com/langchain-ai/langchain/blob/8af4425abd3cbe890a365cec6eac9c0ba69ee282/libs/langchain/langchain/memory/token_buffer.py#L49)

```python
    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        """Save context from this conversation to buffer. Pruned."""
        super().save_context(inputs, outputs)
        # Prune buffer if it exceeds max token limit
        buffer = self.chat_memory.messages
        curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
        if curr_buffer_length > self.max_token_limit:
            pruned_memory = []
            while curr_buffer_length > self.max_token_limit:
                pruned_memory.append(buffer.pop(0))
                curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
```

**Comment by audrito** [comment]
@codemee Thanks for commenting. Now I know the source of the issue. **Any idea how to fix it in the most optimized way?** I was thinking about creating a modified version of the class to fix this issue in my application. I'd appreciate it if you had the time to mention the steps or code changes that can lead to the correct solution. (I'm a beginner.)

Also, which one might be a better approach?

1. `ConversationTokenBufferMemory` gets the functionality to directly remove the oldest messages from the Redis database when the history data is close to context length limit?
2. `ConvesationTokenBufferMemory` retrieves all the history data from the Redis database, removes the oldest messages until it fits the `max_token_limit` then pass it in the llm?

**Comment by codemee** [comment]
This should work arround the problem

```python
from typing import Any, Dict
from langchain.memory.chat_memory import BaseChatMemory

class MyMemory(ConversationTokenBufferMemory):
    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        """Save context from this conversation to buffer. Pruned."""
        BaseChatMemory.save_context(self, inputs, outputs)
        # Prune buffer if it exceeds max token limit
        buffer = self.chat_memory.messages
        curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
        if curr_buffer_length > self.max_token_limit:
            pruned_memory = []
            while curr_buffer_length > self.max_token_limit:
                pruned_memory.append(buffer.pop(0))
                curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
            self.chat_memory.clear()
            self.chat_memory.add_messages(buffer)
```

**Comment by audrito** [comment]
>         if curr_buffer_length > self.max_token_limit:
>             pruned_memory = []
>             while curr_buffer_length > self.max_token_limit:
>                 pruned_memory.append(buffer.pop(0))

Why do we need `pruned_memory` though? What's the purpose? Thanks for the code, but it didn't work, I tried to fix it myself for the past seven hours and don't know what's wrong exactly.

**Comment by audrito** [comment]
@codemee
>         if curr_buffer_length > self.max_token_limit:
>             pruned_memory = []
>             while curr_buffer_length > self.max_token_limit:
>                 pruned_memory.append(buffer.pop(0))

Why do we need `pruned_memory` though? What's the purpose? Thanks for the code, but it didn't work, I tried to fix it myself for the past seven hours and don't know what's wrong exactly.

**Comment by codemee** [comment]
I've test the code with this 

```python
from langchain.memory import ConversationTokenBufferMemory
from langchain_openai import ChatOpenAI
from typing import Any, Dict
from langchain.memory.chat_memory import BaseChatMemory
from langchain.memory import RedisChatMessageHistory

client = ChatOpenAI()

class MyMemory(ConversationTokenBufferMemory):
    def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
        """Save context from this conversation to buffer. Pruned."""
        BaseChatMemory.save_context(self, inputs, outputs)
        # Prune buffer if it exceeds max token limit
        buffer = self.chat_memory.messages
        curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
        if curr_buffer_length > self.max_token_limit:
            pruned_memory = []
            while curr_buffer_length > self.max_token_limit:
                pruned_memory.append(buffer.pop(0))
                curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
            self.chat_memory.clear()
            self.chat_memory.add_messages(buffer)

mem = MyMemory(
    chat_memory=RedisChatMessageHistory(
        session_id='test', 
        url="redis://localhost:6379"
    ),
    max_token_limit=30,
    return_messages=True,
    llm=client
)
    
mem.save_context(
    {'input': 'Hi'},
    {'output': 'Hi, is there anything I can help you with?'}
)
mem.save_context(
    inputs={'input': "I'm hungry"},
    outputs={'output': 'What do you want to eat?'}
)
mem.save_context(
    inputs={'input': 'I want to eat noodles'},
    outputs={'output': 'What kind of noodles do you want to eat?'}
)

print(mem.load_memory_variables({}))
```

Here's the result

```
{'history': [HumanMessage(content='I want to eat noodles'), AIMessage(content='What kind of noodles do you want to eat?')]}
```

You can see the messages exceed the max token limit have been removed.

Maybe you can paste your code and the error message here. Thanks.

**Comment by audrito** [comment]
@codemee Thank you so much. Yes,  it is working now. I appreciate your efforts 🩷

**Comment by corbenicai** [comment]
@audrito Thanks for the workaround back in 2024 — the custom `save_context` pruning does help in simple cases.

However, the **root problem still exists in 2026** for real-world usage.

I just ran a stress test with two large real dependency lockfiles (facebook/react yarn.lock + vercel/next.js pnpm-lock.yaml = **2.04 MB / ~1.006 M tokens** per turn) against a 1M-token model (Gemini 3.1 class).

- Vanilla `ConversationTokenBufferMemory` (even with pruning) → **crashes on turn 2** (2.01 M tokens)
- **MerlinBufferMemory** (new drop-in) → survives **all 6 turns** at stable ~797 k tokens

I even sent the actual rendered buffers to the live Gemini API:
- Vanilla → HTTP 400 (over limit)
- Merlin → **HTTP 200 OK**

Full reproducible benchmark + PDF + `pip install merlin-langchain` here:

→ https://github.com/corbenicai/merlin-community/tree/main/integrations/langchain

This is a general-purpose byte-level deduplication layer (1.10 µs per call) that works as a true drop-in without having to maintain custom pruning logic.

Happy to share more details or help anyone still hitting this in production.
