### ISSUE TITLE
Breaking pydantic v2 compatibility in output parsers from 0.1.6

### ISSUE THREAD

**Issue by Itinte** [langchain-ai/langchain#18322]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel


class TestModel(BaseModel):
    test_attribute: str


if __name__ == '__main__':
    pydantic_output_parser = PydanticOutputParser(pydantic_object=TestModel)
    print(pydantic_output_parser)
```

### Error Message and Stack Trace (if applicable)

```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for PydanticOutputParser
pydantic_object
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

### Description

Hello,

Starting from version 0.1.6, there arises an issue with existing pydantic v2 `BaseModel` child classes triggering an error. This problem is directly associated with a particular [commit](https://github.com/langchain-ai/langchain/commit/852973d6169fee3e80f3b361453dd14980dd8797#diff-f86ea1cb10fcab7e1a505fab4aad6b8e4ad3fc33128f7d0c74474166c66bb608):

In the file `pydantic.py` (now relocated to core), the attribute `pydantic_object` of the `PydanticOutputParser` class underwent a change from a generic type variable `T = TypeVar("T", bound=BaseModel)` to `Type[BaseModel]`. Consequently, this alteration shifted the validator used in constructors from `any_class_validator` to `make_class_validator`. Thus, all child BaseModel classes are checked whether they are subclass of pydantic v1 `BaseModel`

It worked on 0.1.5.

I am aware that  [Example 2 in the documentation](https://python.langchain.com/docs/guides/pydantic_compatibility) advises against using pydantic v2 BaseModels. 
However, **I find it unfortunate that upgrading to version 0.1.6 breaks compatibility with pydantic v2.**

Thank you.

### System Info

python 3.10
langchain >= 0.1.6
mac Sonoma 14.1.2

**Comment by navjot-arcs** [comment]
Also its break when we use 'create_structured_output_runnable' since it also use 'PydanticOutputParser' under the hood when we pass output_schema of Type[BaseModel].

### Code:
```python
  runnable = create_structured_output_runnable(
      output_schema=FunctionCallModel,
      llm=llm,
      prompt=_prompt,
  )
 ```
 ### Error:  
 "no validator found for <class 'FunctionCallModel'>, see `arbitrary_types_allowed` in Config"
