### ISSUE TITLE
SQL query checker tool doesn't respect prompt template passed when creating default LLMChain 

### ISSUE THREAD

**Issue by oogetyboogety** [langchain-ai/langchain#18351]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I would expect to be able to pass a template to QuerySQLCheckerTool when constructing it for my own custom toolkit, as such:
```python
query_sql_checker_tool = QuerySQLCheckerTool(
   db=sqldb,
   llm=model, 
   description=new_description, 
   template=new_prompt_template
)
```
however, this is not the case.

### Description

I would like to rewrite the template  this tool uses for its Query checker for my certain use case. I would like to do this by composing it into the existing tool from the library, and not have to create my own custom tool based on the given tool for this purpose. 
It appears template is already able to be passed as an argument, but it is not being used. This is especially confusing as there is no other use of this argument but it is hardcoded to the same value no matter what we pass for this argument when constructing this tool from the library for our own custom toolkits.

### System Info

This is a code issue as you can see:
https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/tools/sql_database/tool.py#L99

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/tools/sql_database/tool.py#L116

**Comment by liugddx** [comment]
Do you want to customize prompt template?
