### ISSUE TITLE
 Error in agentexecutor with memory: One output key expected, got dict_keys(['output', 'messages'])

### ISSUE THREAD

**Issue by makoit** [langchain-ai/langchain#18388]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python

class Agent:
    def __init__(self, connection_id: str, chat_id: str, user_id: str):
        self.chat_id = chat_id
        self.user_id = user_id
        self.connection_id = connection_id

        self._llm = AzureChatOpenAI(
             azure_endpoint=OPENAI_AZURE_ENDPOINT,
             openai_api_version=OPENAI_API_VERSION,
             azure_deployment=OPENAI_AZURE_DEPLOYMENT,
             openai_api_key=OPENAI_AZURE_API_KEY,
             openai_api_type=OPENAI_API_TYPE,
             temperature=0.4,
             streaming=True,
         )

        self._tools = [
            CodeInterpreter(),
        ]

        message_history = DynamoDBChatMessageHistory(
            table_name=DYNAMODB_HISTORY_TABLE_NAME,
            session_id=self.chat_id,
            key={
                "PK": self.chat_id,
                "SK": self.user_id,
            },
        )

        self.memory = ConversationSummaryBufferMemory(
            memory_key="chat_memory",
            llm=self._llm,
            max_token_limit=2000,
            return_messages=True,
            chat_memory=message_history
        )


        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", AGENT_SYSTEM_MESSAGE),
                MessagesPlaceholder("chat_memory", optional=True),
                ("human", "{input}"),
                MessagesPlaceholder("agent_scratchpad"),
            ]
        )

        agent = cast(
            BaseMultiActionAgent,
            create_openai_tools_agent(self._llm, self._tools, prompt),
        )
        self.agent_executor = AgentExecutor(
            agent=agent, tools=self._tools, verbose=True, memory=self.memory,
        ).with_config({"run_name": "Agent"})

    async def arun(self, query: str, callback: AgentCallbackHandler):
        output = None
        try:
            async for event in self.agent_executor.astream_events(
                {"input": query}, version="v1"
            ):
                await callback.handle_event(event)

        except Exception as e:
            logger.error(traceback.format_exc())
            logger.error("astream_events error %s", e)

```

### Error Message and Stack Trace (if applicable)

`
[ERROR] 2024-02-29T14:51:07.594Z        functions::handle_message:118   Traceback (most recent call last):  
  File "<placeholder>\logic\functions.py", line 112, in handle_message  
    await agent.arun(message, callback)  
  File "<placeholder>\logic\agent.py", line 107, in arun  
    async for event in self.agent_executor.astream_events(  
  File "<placeholder>\langchain_core\runnables\base.py", line 4157, in astream_events  
    async for item in self.bound.astream_events(  
  File "<placeholder>\langchain_core\runnables\base.py", line 889, in astream_events  
    async for log in _astream_log_implementation(  # type: ignore[misc]  
  File "<placeholder>\langchain_core\tracers\log_stream.py", line 612, in _astream_log_implementation  
    await task  
  File "<placeholder>\langchain_core\tracers\log_stream.py", line 566, in consume_astream  
    async for chunk in runnable.astream(input, config, **kwargs):  
  File "<placeholder>\langchain\agents\agent.py", line 1551, in astream  
    async for step in iterator:  
  File "<placeholder>\langchain\agents\agent_iterator.py", line 265, in __aiter__    
    output = await self._aprocess_next_step_output(  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "<placeholder>\langchain\agents\agent_iterator.py", line 328, in _aprocess_next_step_output  
    return await self._areturn(next_step_output, run_manager=run_manager)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "<placeholder>\langchain\agents\agent_iterator.py", line 392, in _areturn     
    return self.make_final_outputs(returned_output, run_manager)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "<placeholder>\langchain\agents\agent_iterator.py", line 142, in make_final_outputs  
    self.agent_executor.prep_outputs(  
  File "<placeholder>\langchain\chains\base.py", line 440, in prep_outputs  
    self.memory.save_context(inputs, outputs)  
  File "<placeholder>\langchain\memory\summary_buffer.py", line 59, in save_context    super().save_context(inputs, outputs)  
  File "<placeholder>\langchain\memory\chat_memory.py", line 38, in save_context     
    input_str, output_str = self._get_input_output(inputs, outputs)  
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "<placeholder>\langchain\memory\chat_memory.py", line 30, in _get_input_output  
    raise ValueError(f"One output key expected, got {outputs.keys()}")  
ValueError: One output key expected, got dict_keys(['output', 'messages'])
`

### Description

When using agentexecutor with memory, an error occurs in the save_context method of chat_memory.py. The error is raised because the expected number of output keys is one, but the actual number of output keys is more than one.

### System Info

    Python version: 3.11
    Libraries used:
        openai==1.10.0
        langchain==0.1.6
        langchain-community==0.0.19
        langchain-openai==0.0.5
        langchainhub==0.1.14
        pyshorteners==1.0.1
        tiktoken==0.5.2
        python-multipart==0.0.6
        httpx==0.25.0
        azure-core==1.29.4
        azure-identity==1.14.1
        azure-search-documents==11.4.0b8
        requests==2.31.0
        requests-aws4auth==1.2.3

**Comment by Joshua-Shepherd** [comment]
Also running into this issue. If you happen to find a workaround, other than handling the memory manually, please let us know!

**Comment by Joshua-Shepherd** [comment]
Oh actually @makoit  could this be the issue?
https://github.com/langchain-ai/langchain/pull/18117

**Comment by xiaohuanshu** [comment]
my pr #18117 fixed it, but not merged.
Can be temporarily repaired by adding output_key field to Memory object `ConversationBufferMemory(output_key="output")`

**Comment by makoit** [comment]
> Oh actually @makoit could this be the issue? #18117

This could be the issue

**Comment by xiaohuanshu** [comment]
> @xiaohuanshu I tried to set the output_key to value "output" and then I receive the error that this key is not known or not found.

That's weird. Can you show me the error message with stack trace

**Comment by Mansko** [comment]
@xiaohuanshu, I've implemented your suggestions, and with the output_key set to "output," it worked as expected. Do you know when these changes will be merged into the codebase and made available?

**Comment by xiaohuanshu** [comment]
> @xiaohuanshu, I've implemented your suggestions, and with the output_key set to "output," it worked as expected. Do you know when these changes will be merged into the codebase and made available?

I don't know, waiting for maintainer review
