### ISSUE TITLE
GitHub agent throwing TypeError: GitHubAction._run() Unexpected Keyword Argument 'issue_number'

### ISSUE THREAD

**Issue by ajhous44** [langchain-ai/langchain#18406]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:

``` python
import os

from langchain.agents import AgentType, initialize_agent
from langchain_community.agent_toolkits.github.toolkit import GitHubToolkit
from langchain_community.utilities.github import GitHubAPIWrapper
from langchain_openai import ChatOpenAI

# Set your environment variables using os.environ
os.environ["GITHUB_APP_ID"] = ""
os.environ["GITHUB_APP_PRIVATE_KEY"] = "pemfile"
os.environ["GITHUB_REPOSITORY"] = ""
os.environ["GITHUB_BRANCH"] = ""
os.environ["GITHUB_BASE_BRANCH"] = "main"

# This example also requires an OpenAI API key
os.environ["OPENAI_API_KEY"] = "####"

llm = ChatOpenAI(temperature=0, model="gpt-4-1106-preview")
github = GitHubAPIWrapper()
toolkit = GitHubToolkit.from_github_api_wrapper(github)
tools = toolkit.get_tools()

# STRUCTURED_CHAT includes args_schema for each tool, helps tool args parsing errors.
agent = initialize_agent(
	tools,
	llm,
	agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
	verbose=True,
)
print("Available tools:")
for tool in tools:
	print("\t" + tool.name)

agent.run(
    "You have the software engineering capabilities of a Google Principle engineer. You are tasked with completing issues on a github repository. Please look at the existing issues and complete them."
)
```

### Error Message and Stack Trace (if applicable)

```

> Entering new AgentExecutor chain...
Action:
```json
{
  "action": "Get Issues",
  "action_input": {}
}
```

Observation: Found 1 issues:
[{'title': 'Create a new html file', 'number': 1, 'opened_by': 'ajhous44'}]
Thought:To proceed with the task of completing the issue found in the repository, I need to first understand the details of the issue. I will fetch the title, body, and comment thread of the specific issue with number 1.

Action:
```json
{
  "action": "Get Issue",
  "action_input": {
    "issue_number": 1
  }
}
```Traceback (most recent call last):

Traceback (most recent call last):
  File "c:\Users\[username]\Documents\Git\[project_name]\[script_name].py", line 34, in <module>
    agent.run(
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain\chains\base.py", line 545, in run 
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain_core\_api\deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain\chains\base.py", line 378, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain\chains\base.py", line 163, in invoke
    raise e
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain\agents\agent.py", line 1391, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[username]\Documents\Git\[project_name]\.venv\Lib\site-packages\langchain_core\tools.py", line 376, in run  
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
TypeError: GitHubAction._run() got an unexpected keyword argument 'issue_number'
```

### Description

When attempting to run a simple agent example integrating LangChain with GitHub, following the documentation provided at https://python.langchain.com/docs/integrations/toolkits/github, I encountered a TypeError during the execution of the agent.run() method. The error message indicates that the GitHubAction._run() method received an unexpected keyword argument issue_number. This issue arises despite closely following the example provided, which suggests there might be a discrepancy between the documented example and the current implementation or expectations of the GitHubAction._run() method. The environment is set up as instructed, with environment variables for GitHub integration and the OpenAI API key configured. The error occurs in the final step, where the agent is expected to process tasks related to GitHub issue management through natural language commands. This suggests a possible mismatch in the expected arguments or an oversight in the documentation.

### System Info

langchain==0.1.9
langchain-community==0.0.24
langchain-core==0.1.28
langchain-openai==0.0.8

**Comment by ajhous44** [comment]
FYI, I Get a deprecation warning saying to use agent.invoke and not agent..run -- however same issue when using .invoke

**Comment by keenborder786** [comment]
@ajhous44  It was an bug in the [GitHubAction](https://github.com/keenborder786/langchain/blob/a4fa643f000267a4fe02713a2edaf92cccd8cfde/libs/community/langchain_community/tools/github/tool.py#L19) tool parametr which I have fixed in the PR.

**Comment by jrgriffiniii** [comment]
Thank you very much for your PR @keenborder786! Was your work ever merged into `master`? The PR seems to have been closed, and I do not see your changes: https://github.com/langchain-ai/langchain/blame/master/libs/community/langchain_community/tools/github/tool.py#L37

**Comment by ademait** [comment]
Hi @keenborder786 , thanks for the fix! I am awaiting the changes to be applied too.

**Comment by jrgriffiniii** [comment]
I apologize for tagging, however, @baskaryan might this have been resolved with a separate PR and subsequent release? No one means to impose if you are actively committed to other priorities; if there are any tasks which can be addressed by us we would be most grateful. Thank you!

**Comment by jrgriffiniii** [comment]
I am sorry for tagging you directly @cbornet, however you seem to be recently active in modifying the code base. Might there be anywhere to direct questions for this please?

**Comment by cbornet** [comment]
Hi @jrgriffiniii , I don't know the GitHubAction tool.
Have you tried @keenborder786 's fix ? The PR was indeed closed without merge. Maybe you could open it back if it fixes the issue ?

**Comment by Victorivus** [comment]
I get the same error but with `unexpected keyword argument 'branch_name'` instead
