### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_text_splitters'

### ISSUE THREAD

**Issue by EdIzaguirre** [langchain-ai/langchain#18409]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

See the Colab link: https://colab.research.google.com/drive/1vNVBmE15pAPJjOukfIB4Gs7ilygbLb5k?usp=sharing

'''
!pip install -q langchain

import langchain
print(f'Langchain Version: {langchain.__version__}')
import sys
print(f'Python Version: {sys.version}')
from langchain_text_splitters import RecursiveCharacterTextSplitter
'''

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-9070a936598a>](https://localhost:8080/#) in <cell line: 7>()
      5 import sys
      6 print(f'Python Version: {sys.version}')
----> 7 from langchain_text_splitters import RecursiveCharacterTextSplitter

ModuleNotFoundError: No module named 'langchain_text_splitters'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Description

I was following the Quickstart Guide, and noticed that when trying to import from langchain_text_splitters import RecursiveCharacterTextSplitter, the error above is received. I made sure all dependencies are included, tried uninstalling and reinstalling LangChain.

### System Info

langchain==0.1.9
langchain-community==0.0.25
langchain-core==0.1.28

Langchain Version: 0.1.9
Python Version: 3.10.12

**Comment by sepiatone** [comment]
langchain_text_splitters is in the langchain-experimental package. You'll have to install that.

See https://api.python.langchain.com/en/latest/experimental_api_reference.html#module-langchain_experimental.text_splitter

**Comment by efriis** [comment]
Upgrade to langchain 0.1.10! This should be included there

**Comment by LaoK263** [comment]
This looks like a typo in the post, after change it to :
**from langchain.text_splitter import RecursiveCharacterTextSplitter**
the issue was disappear.

**Comment by EdIzaguirre** [comment]
Both solutions given worked, in case anyone else comes to this post.

**Comment by KansaiUser** [comment]
Does anybody have a solution to this other than using an old version? 
This works with 0.1.10  but not with the current 1.1.0

**Comment by KansaiUser** [comment]
I found the solution.

https://api.python.langchain.com/en/latest/character/langchain_text_splitters.character.RecursiveCharacterTextSplitter.html#langchain-text-splitters-character-recursivecharactertextsplitter

**Comment by taisiya006** [comment]
just got the same problem, fixed replacing the imoprt with:
`from langchain_text_splitters import RecursiveCharacterTextSplitter`

**Comment by atifwattoo** [comment]
langchain move `RecursiveCharacterTextSplitter` this to `langchain-text-splitters `
Please install this pagkage
`pip install langchain-text-splitters`
and then
`from langchain-text-splitters import RecursiveCharacterTextSplitter`

**Comment by Oguama77** [comment]
pip install langchain-text-splitters
from langchain_text_splitters import RecursiveCharacterTextSplitter
