### ISSUE TITLE
Validation Error Encountered When Connecting Google AI Model with LangChain

### ISSUE THREAD

**Issue by chethanhn29** [langchain-ai/langchain#18425]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

When attempting to connect the Google AI model with LangChain using a provided API key, the following error is encountered:

```python
ValidationError                           Traceback (most recent call last)
Cell In[52], line 2
      1 from langchain_google_genai import GoogleGenerativeAI
----> 2 llm = GoogleGenerativeAI(model="gemini-pro", google_api_key=api_key)
      3 print(
      4     llm.invoke(
      5         "What are some of the pros and cons of Python as a programming language?"
      6     )
      7 )

File /opt/conda/lib/python3.10/site-packages/langchain_core/load/serializable.py:120, in Serializable.__init__(self, **kwargs)
    119 def __init__(self, **kwargs: Any) -> None:
--> 120     super().__init__(**kwargs)
    121     self._lc_kwargs = kwargs

File /opt/conda/lib/python3.10/site-packages/pydantic/v1/main.py:341, in BaseModel.__init__(__pydantic_self__, **data)
    339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340 if validation_error:
--> 341     raise validation_error
    342 try:
    343     object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for GoogleGenerativeAI
__root__
  'NoneType' object does not support item assignment (type=type_error)
```

this is my code 

```python

from getpass import getpass

api_key = getpass()

from langchain_google_genai import GoogleGenerativeAI
llm = GoogleGenerativeAI(model="gemini-pro", google_api_key=api_key)
print(
    llm.invoke(
        "What are some of the pros and cons of Python as a programming language?"
    )
)

```

### Description

I am trying use Google LLM model using langchian but its giving validation error , but if i am using that same key in [default llm model methods ](https://ai.google.dev/tutorials/python_quickstart) the LLM model is generating Content

### System Info

i am using Kaggle and GPU T-100 as GPU

**Comment by gunjak** [comment]
This issue is from kaggle side . you can use the model in colab. I raised the issue but did not get response.
