### ISSUE TITLE
SQL Database Agent - 'Is not a valid tool' error

### ISSUE THREAD

**Issue by problemxl** [langchain-ai/langchain#18439]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:

```python
from langchain_community.utilities import SQLDatabase

from langchain.agents import create_sql_agent
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain.agents.agent_types import AgentType
from langchain_groq import ChatGroq

llm = ChatGroq(temperature=0.5, groq_api_key="<api-key>", model_name="mixtral-8x7b-32768")
db = SQLDatabase.from_uri("sqlite:///Chinook.db")

agent_executor_kwargs = {
        "handle_parsing_errors": True,
    }

agent_executor = create_sql_agent(
        llm=llm,
        toolkit=SQLDatabaseToolkit(db=db, llm=llm),
        # db=db,
        verbose=True,
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        agent_executor_kwargs=agent_executor_kwargs,
    )

agent_executor.invoke(
    {"input": "List the total sales per country. Which country's customers spent the most?"}
)
```

### Error Message and Stack Trace (if applicable)

```
> Entering new SQL Agent Executor chain...
I need to query the database to get the total sales per country. After that, I can identify the country whose customers spent the most.

Action: sql\_db\_query
Action Input: SELECT country, SUM(sales) FROM orders GROUP BY country ORDER BY SUM(sales) DESC;
sql\_db\_query is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I apologize for the confusion. You are correct that the action should be "sql\_db\_query". However, it seems that I made a mistake in the input for the action. I will try again.

Action: sql\_db\_query
Action Input: SELECT country, SUM(sales) FROM orders GROUP BY country ORDER BY SUM(sales) DESC;
sql\_db\_query is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I apologize for the confusion. It seems I need to use the `sql_db_query_checker` tool first to ensure that my query is correct before executing it with `sql_db_query`.

Action: sql\_db\_query\_checker
Action Input: SELECT country, SUM(sales) FROM orders GROUP BY country ORDER BY SUM(sales) DESC;
sql\_db\_query\_checker is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I apologize for the confusion. It seems I need to check the table schema first to ensure that my query is correct. I will use `sql_db_schema` tool to get the schema of the `orders` table.

Action: sql\_db\_schema
Action Input: orders
sql\_db\_schema is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I apologize for the confusion. It seems I made a mistake in the input for the action. The correct tool to use is `sql_db_list_tables` to get the list of tables in the database.

Action: sql\_db\_list\_tables
Action Input: 
sql\_db\_list\_tables is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I apologize for the confusion. I realize now that I made a mistake in my previous inputs. The correct tool to use is `sql_db_list_tables` to get the list of tables in the database. I will try again.
...
Action Input: 
sql\_db\_list\_tables is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:Invalid Format: Missing 'Action:' after 'Thought:

> Finished chain.
```

### Description

When attempting to use the SQL Database agent with LLMs that aren't from OpenAI, it produces this loop caused by back slash escape sequences.

I have included groq utilizing the mixtral model but I have also experienced this using ollama, llama.cpp testing a number of different LLM models including but not limited to mixtral, mistral, llama, phi, codellama, etc.

I do not experience this bug when using gpt-3.5-turbo and gpt-4

### System Info

langchain: 0.1.9
python: 3.11.3
OS: Windows

**Comment by keenborder786** [comment]
Can you please update your langchain version to latest and try again.  That will resolve the issue.

**Comment by problemxl** [comment]
I updated to langchain 0.1.10 and I'm experiencing the same issue.

**Comment by codeloki15** [comment]
Same issue , what I would suggest is the usage of agent type..
When I am using gpt3.5 turbo with open ai function on same db .. it is retrieving the results
When I am using groq, we canyt use this function and looks like  zero shot is not the way forwards

**Comment by codeloki15** [comment]
```
#llm = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
agent_executor = create_sql_agent(llm, db=db, agent_type="zero-shot-react-description", verbose=True)
```



> Entering new SQL Agent Executor chain...
To answer this question, I need to first understand the structure of the "anime\_reviwes" table. I will use the "sql\_db\_schema" tool to get the schema and sample rows of the table.

Action: sql\_db_schema
Action Input: anime\_reviews
sql\_db_schema is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I made a mistake in using the tool's name. I should use "sql\_db\_schema" to get the schema of the "anime\_reviews" table.

Action: sql\_db\_schema
Action Input: anime\_reviews
sql\_db\_schema is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I made a mistake in the tool name, it should be "sql\_db\_schema". I will try again.

Action: sql\_db\_schema
Action Input: anime\_reviews
sql\_db\_schema is not a valid tool, try one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker].I am facing an issue where the provided tool "sql\_db\_schema" is not being recognized. I will inform the user about this issue so they can take appropriate action.

Final Answer: It seems there is an issue with the provided tools as "sql\_db\_schema" is not being recognized. Please check the tool availability or notify the system administrator.

> Finished chain.
{'input': 'List the top animes in anime_reviwes table ?',
 'output': 'It seems there is an issue with the provided tools as "sql\\_db\\_schema" is not being recognized. Please check the tool availability or notify the system administrator.'}

**Comment by spagliarini** [comment]
Did anyone found a solution to this issue?

I updated to langchain 0.1.12 and I'm experiencing the same issue.

**Comment by linuxmanju** [comment]
Looks mostly to do with Mixtral escaping "_" with "\_" causing the issue. in my local llama I tried system prompt 'Do not escape "_" OR underscores' Works many times not always, may be you can give it a try.

**Comment by machuck** [comment]
version 0.1.13 same issue here

**Comment by michaelgloeckner** [comment]
As a workaround you can make a copy of the SQLDatabaseToolkit and use it with modified names.


- copy lib\python\site-package\langchain_community\agen_toolkits\sql\toolkit.py and lib\python\site-package\langchain_community\tools\sql_database\tool.py in workspace.

- use tool.py copy in toolkit.py

```
from tool import (
    InfoSQLDatabaseTool,
    ListSQLDatabaseTool,
    QuerySQLCheckerTool,
    QuerySQLDataBaseTool,
)
```

- change names of the tool names in tool.py

eg.: 
`    name: str = "sqldbschema" # instead of sql_db_schema
`

- in your implementation use:

`from toolkit import SQLDatabaseToolkit `

**Comment by yalvhe2009** [comment]
> As a workaround you can make a copy of the SQLDatabaseToolkit and use it with modified names.
> 
> * copy lib\python\site-package\langchain_community\agen_toolkits\sql\toolkit.py and lib\python\site-package\langchain_community\tools\sql_database\tool.py in workspace.
> * use tool.py copy in toolkit.py
> 
> ```
> from tool import (
>     InfoSQLDatabaseTool,
>     ListSQLDatabaseTool,
>     QuerySQLCheckerTool,
>     QuerySQLDataBaseTool,
> )
> ```
> 
> * change names of the tool names in tool.py
> 
> eg.: ` name: str = "sqldbschema" # instead of sql_db_schema`
> 
> * in your implementation use:
> 
> `from toolkit import SQLDatabaseToolkit `

Thanks, your method works.

**Comment by Yasser-shrief** [comment]
i am encountring similar issue but the groq agent dosn't Invoking: `sql_db_query` tool , so the output seems like : 

`> Entering new AgentExecutor chain...

Invoking: `sql_db_query` with `{'query': "SELECT DISTINCT university \n                    FROM additional_data_tmp_programs_table\n                    WHERE Program_Name ILIKE '%Business%' AND Country = 'Turkey' AND Degree = 'Bachelor'\n                    ORDER BY CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,\n                    RANDOM() \n                    LIMIT 3 ;"}`


Error: (psycopg2.errors.InvalidColumnReference) for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 4:                     ORDER BY CASE priority WHEN 'high' THEN ...
                                     ^

[SQL: SELECT DISTINCT university 
                    FROM additional_data_tmp_programs_table
                    WHERE Program_Name ILIKE '%%Business%%' AND Country = 'Turkey' AND Degree = 'Bachelor'
                    ORDER BY CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
                    RANDOM() 
                    LIMIT 3 ;]
(Background on this error at: https://sqlalche.me/e/20/f405)It seems like there's an issue with the query I tried to execute. The error message indicates that the ORDER BY expressions must appear in the SELECT list. I'll need to adjust the query to resolve this issue.

> Finished chain.
It seems like there's an issue with the query I tried to execute. The error message indicates that the ORDER BY expressions must appear in the SELECT list. I'll need to adjust the query to resolve this issue.`


Code :

`from langchain_community.vectorstores import FAISS
from langchain_core.example_selectors import SemanticSimilarityExampleSelector
from langchain_openai import OpenAIEmbeddings
from langchain.agents import create_openai_tools_agent
from langchain.agents.agent_types import AgentType
from langchain.agents.agent import AgentExecutor
from langchain_community.chat_message_histories import SQLChatMessageHistory
from langchain_core.messages import AIMessage
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.prompts import (
    ChatPromptTemplate,
    FewShotPromptTemplate,
    MessagesPlaceholder,
    PromptTemplate,
    SystemMessagePromptTemplate,
)
from langchain_groq import ChatGroq

llm = ChatGroq(
    temperature=0.1,
    model="llama3-groq-70b-8192-tool-use-preview"
    api_key="api_key" 
)
toolkit = SQLDatabaseToolkit(db=db, llm=llm)
tools = toolkit.get_tools()

# examples selectors
example_selector = SemanticSimilarityExampleSelector.from_examples(
    examples,
    OpenAIEmbeddings(),
    FAISS,
    k=4,
    input_keys=["input"],
)

# system prompt
system_prefix =""" prompt.......

    Here are some examples of user inputs and their corresponding SQL queries:"""

few_shot_prompt = FewShotPromptTemplate(
    example_selector=example_selector,
    example_prompt=PromptTemplate.from_template(
        "User input: {input}\nSQL query: {query}"
    ),
    input_variables=["input", "dialect", "top_k"],
    prefix=system_prefix,
    suffix="",
)

full_prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate(prompt=few_shot_prompt),
        MessagesPlaceholder(variable_name="chat_history"),
        ("human", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
)

# create agent from tools and full prompt
agent = create_openai_tools_agent(llm, tools, full_prompt)
agent_executor4 = AgentExecutor(
    agent=agent,
    tools=toolkit.get_tools(),
    verbose=True,
    max_execution_time=60,
    top_k=20
)


# Summury memory 
def get_session_history(session_id):
    return SQLChatMessageHistory(session_id, "sqlite:///database.db") 

#execute agent

SQLagent_executor4 = RunnableWithMessageHistory(
    agent_executor4,
    get_session_history,
    input_messages_key="input",
    output_messages_key="output",
    history_messages_key="chat_history"
)
`

anyone face it before ?

**Comment by amriosmo** [comment]
This is already fixed?
