### ISSUE TITLE
when using qianfan chat streaming occurs TypeError: Additional kwargs key sentence_id already exists in left dict and value has unsupported type <class 'int'>.

### ISSUE THREAD

**Issue by Tangent-90C** [langchain-ai/langchain#18441]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
qianfan_model = QianfanChatEndpoint(model='ERNIE-Bot', qianfan_ak=...... ,
                                    qianfan_sk=......)

for chunk in qianfan_model.stream(input_prompt):
    all_output += chunk.content
    print(chunk.content, end="", flush=True)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "E:\JMIT\JMIT3\code\ans.py", line 247, in <module>
    print(retrieve_ans_chat_stream('我想離婚，孩子該怎麼判？', history=[('你好', '你好呀')]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\JMIT\JMIT3\code\ans.py", line 236, in retrieve_ans_chat_stream
    for chunk in qianfan_model.stream(input_prompt):
  File "E:\envs\JMIT\Lib\site-packages\langchain_core\language_models\chat_models.py", line 250, in stream
    raise e
  File "E:\envs\JMIT\Lib\site-packages\langchain_core\language_models\chat_models.py", line 241, in stream
    generation += chunk
  File "E:\envs\JMIT\Lib\site-packages\langchain_core\outputs\chat_generation.py", line 57, in __add__
    generation_info = merge_dicts(
                      ^^^^^^^^^^^^
  File "E:\envs\JMIT\Lib\site-packages\langchain_core\utils\_merge.py", line 38, in merge_dicts
    raise TypeError(
TypeError: Additional kwargs key created already exists in left dict and value has unsupported type <class 'int'>.

### Description

This bug occurs when the langchain_core>0.1.12
Downgrading to langchain_core==0.1.12 is bug-free

### System Info

langchain==0.1.10
langchain-community==0.0.25
langchain-core==0.1.28
langchain-text-splitters==0.0.1

windows

Python 3.11.7

**Comment by liugddx** [comment]
The logic of chunk merging is relatively complicated. I think it is possible to formulate some keys that need to be merged.

<img width="1071" alt="image" src="https://github.com/langchain-ai/langchain/assets/48236177/b66a7a69-bd8f-4fe7-ba9d-210fcca81bfd">
<img width="724" alt="image" src="https://github.com/langchain-ai/langchain/assets/48236177/a7511cd6-abba-4ddf-b245-e3aeb0940a11">

@baskaryan Please give me some suggestions and I will fix it.

**Comment by axiangcoding** [comment]
Same issue. any update on this error?

**Comment by liugddx** [comment]
> Same issue. any update on this error?

It has been solved, please see the associated PR.https://github.com/langchain-ai/langchain/pull/18889

**Comment by axiangcoding** [comment]
> > Same issue. any update on this error?
> 
> It has been solved, please see the associated PR.#18889

Thanks. Update to the latest langchain can fix this issue.
