### ISSUE TITLE
JsonOutputKeyToolsParser return_single=True doesn't work

### ISSUE THREAD

**Issue by lesong36** [langchain-ai/langchain#18455]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from typing import List

from langchain.output_parsers.openai_tools import JsonOutputKeyToolsParser

parser = JsonOutputKeyToolsParser(key_name="Joke")

chain = prompt | model | parser

chain.invoke({"input": "tell me a joke"})
-----
[{'setup': "Why couldn't the bicycle stand up by itself?",
  'punchline': 'Because it was two tired!'}]
we got a list which is correct, but when we add return_single=True, we still got a list, which is unexpected.

The same is true when we call tool in the chain (code from the document).

from operator import itemgetter

# Note: the `.map()` at the end of `multiply` allows us to pass in a list of `multiply` arguments instead of a single one.
chain = (
    model_with_tools
    | JsonOutputKeyToolsParser(key_name="multiply", return_single=True)
    | multiply
)
chain.invoke("What's four times 23")

it would failed at pydantic validation, because it pipe a list to mulltiply.

we have to get the first item in the list. like below

# You would need to add a step in the chain to convert the list to a dictionary
def extract_arguments_from_list(input_list):
    if isinstance(input_list, list) and len(input_list) == 1:
        return input_list[0]
    else:
        raise ValueError("Expected a list with a single dictionary")

from operator import itemgetter

# Note: the `.map()` at the end of `multiply` allows us to pass in a list of `multiply` arguments instead of a single one.
chain = (
    model_with_tools
    | JsonOutputKeyToolsParser(key_name="multiply", return_single=True)
    # | extract_arguments_from_list  # This is the new step in the chain
    | multiply
)
chain.invoke("What's four times 23")

then it works.

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[71], line 10
      3 # Note: the `.map()` at the end of `multiply` allows us to pass in a list of `multiply` arguments instead of a single one.
      4 chain = (
      5     model_with_tools
      6     | JsonOutputKeyToolsParser(key_name="multiply", return_single=True)
      7     # | extract_arguments_from_list  # This is the new step in the chain
      8     | multiply
      9 )
---> 10 chain.invoke("What's four times 23")

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/runnables/base.py:2075](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/runnables/base.py#line=2074), in RunnableSequence.invoke(self, input, config)
   2073 try:
   2074     for i, step in enumerate(self.steps):
-> 2075         input = step.invoke(
   2076             input,
   2077             # mark each step as a child run
   2078             patch_config(
   2079                 config, callbacks=run_manager.get_child(f"seq:step:{i+1}")
   2080             ),
   2081         )
   2082 # finish the root run
   2083 except BaseException as e:

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py:240](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py#line=239), in BaseTool.invoke(self, input, config, **kwargs)
    233 def invoke(
    234     self,
    235     input: Union[str, Dict],
    236     config: Optional[RunnableConfig] = None,
    237     **kwargs: Any,
    238 ) -> Any:
    239     config = ensure_config(config)
--> 240     return self.run(
    241         input,
    242         callbacks=config.get("callbacks"),
    243         tags=config.get("tags"),
    244         metadata=config.get("metadata"),
    245         run_name=config.get("run_name"),
    246         **kwargs,
    247     )

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py:382](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py#line=381), in BaseTool.run(self, tool_input, verbose, start_color, color, callbacks, tags, metadata, run_name, **kwargs)
    380 except ValidationError as e:
    381     if not self.handle_validation_error:
--> 382         raise e
    383     elif isinstance(self.handle_validation_error, bool):
    384         observation = "Tool input validation error"

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py:373](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py#line=372), in BaseTool.run(self, tool_input, verbose, start_color, color, callbacks, tags, metadata, run_name, **kwargs)
    360 run_manager = callback_manager.on_tool_start(
    361     {"name": self.name, "description": self.description},
    362     tool_input if isinstance(tool_input, str) else str(tool_input),
   (...)
    370     **kwargs,
    371 )
    372 try:
--> 373     parsed_input = self._parse_input(tool_input)
    374     tool_args, tool_kwargs = self._to_args_and_kwargs(parsed_input)
    375     observation = (
    376         self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
    377         if new_arg_supported
    378         else self._run(*tool_args, **tool_kwargs)
    379     )

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py:280](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/langchain_core/tools.py#line=279), in BaseTool._parse_input(self, tool_input)
    278 else:
    279     if input_args is not None:
--> 280         result = input_args.parse_obj(tool_input)
    281         return {
    282             k: getattr(result, k)
    283             for k, v in result.dict().items()
    284             if k in tool_input
    285         }
    286 return tool_input

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/pydantic/main.py:526](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/pydantic/main.py#line=525), in pydantic.main.BaseModel.parse_obj()

File [~/miniconda3/envs/LLMV2/lib/python3.10/site-packages/pydantic/main.py:341](http://localhost:33435/home/coty/miniconda3/envs/LLMV2/lib/python3.10/site-packages/pydantic/main.py#line=340), in pydantic.main.BaseModel.__init__()

ValidationError: 2 validation errors for multiplySchema
first_int
  value is not a valid integer (type=type_error.integer)
second_int
  field required (type=value_error.missing)

### Description

from typing import List

from langchain.output_parsers.openai_tools import JsonOutputKeyToolsParser

parser = JsonOutputKeyToolsParser(key_name="Joke")

chain = prompt | model | parser

chain.invoke({"input": "tell me a joke"})
-----
[{'setup': "Why couldn't the bicycle stand up by itself?",
  'punchline': 'Because it was two tired!'}]
we got a list which is correct, but when we add return_single=True, we still got a list, which is unexpected.

The same is true when we call tool in the chain (code from the document).

from operator import itemgetter

# Note: the `.map()` at the end of `multiply` allows us to pass in a list of `multiply` arguments instead of a single one.
chain = (
    model_with_tools
    | JsonOutputKeyToolsParser(key_name="multiply", return_single=True)
    | multiply
)
chain.invoke("What's four times 23")

it would failed at pydantic validation, because it pipe a list to mulltiply.

we have to get the first item in the list. like below

# You would need to add a step in the chain to convert the list to a dictionary
def extract_arguments_from_list(input_list):
    if isinstance(input_list, list) and len(input_list) == 1:
        return input_list[0]
    else:
        raise ValueError("Expected a list with a single dictionary")

from operator import itemgetter

# Note: the `.map()` at the end of `multiply` allows us to pass in a list of `multiply` arguments instead of a single one.
chain = (
    model_with_tools
    | JsonOutputKeyToolsParser(key_name="multiply", return_single=True)
    # | extract_arguments_from_list  # This is the new step in the chain
    | multiply
)
chain.invoke("What's four times 23")

then it works.

### System Info

Name: langchain
Version: 0.1.10
Name: langchain-core
Version: 0.1.28
Name: langgraph
Version: 0.0.26
Name: langchain-community
Version: 0.0.25
Name: langchain-experimental
Version: 0.0.53
Name: langchain-openai
Version: 0.0.8
Name: langserve
Version: 0.0.46
Name: langchain-cli
Version: 0.0.21
Name: langsmith
Version: 0.1.13
Name: langgraph
Version: 0.0.26
Name: openai
Version: 1.13.3
Name: httpx
Version: 0.25.2
Name: pydantic
Version: 1.10.14
python=3.10.13

**Comment by Sinnaeve** [comment]
I got same issue when running "Pandas" section from https://python.langchain.com/docs/use_cases/csv. 

It works on version 0.1.9 of langchain but not for later versions, due to return_single argument not working properly

**Comment by liugddx** [comment]
Use ```first_tool_only=True```

``` chain = (
model_with_tools
| JsonOutputKeyToolsParser(key_name="multiply", first_tool_only=True)
| multiply
)
chain.invoke("What's four times 23") ```

**Comment by wofeishenling** [comment]
update to new version and use first_tool_only=True, will work
