### ISSUE TITLE
mistrial is supported by bedrock, by its langchain wrapper will throw exception

### ISSUE THREAD

**Issue by ybalbert001** [langchain-ai/langchain#18451]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

def get_langchain_llm_model(llm_model_id, params, region):
    '''
        params keys should be in [temperature, max_tokens, top_p, top_k, stop]
    '''
    llm = None
    parameters = { item[0]:item[1] for item in params.items() if item[0] in ['temperature', 'max_tokens', 'top_p', 'top_k', 'stop']}

    if llm_model_id in bedrock_llms:
        boto3_bedrock = boto3.client(
            service_name="bedrock-runtime",
            region_name=region
        )
        llm = Bedrock(model_id=llm_model_id, client=boto3_bedrock, streaming=False, model_kwargs=parameters) 
        return llm

INVOKE_MODEL_ID = 'mistral.mistral-7b-instruct-v0:2'
llm4 = get_langchain_llm_model(INVOKE_MODEL_ID, params, REGION)
llmchain = LLMChain(llm=llm4, verbose=False, prompt=prompt_templ)
answer = llmchain.run({})

### Description

As mistrial was support on Mar.1, i guess langchain have not adapted with this update. Look forwarding to the upgrade for this. 

### System Info

Linux, python3.10

**Comment by AnisZakari** [comment]
I've made a [PR](https://github.com/langchain-ai/langchain/pull/18756) to adress this issue
