### ISSUE TITLE
Dockerfile issues when trying to build the repo using .devcontainer

### ISSUE THREAD

**Issue by arnaupv** [langchain-ai/langchain#18465]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

_NO_CODE_EXAMPLE_

### Error Message and Stack Trace (if applicable)

```
Directory ../text-splitters does not exist
```

### Description

After forking and cloning the repo on my machine, I tried to open it using docker and specifically in VS Code with the option to "Reopen in Container". While building, the final command of [dev.Dockerfile](https://github.com/langchain-ai/langchain/blob/b051bba1a9f3f2c6020d7c8dbcc792d14b3cbe17/libs/langchain/dev.Dockerfile#L50) resulted in the following error:
```
Directory ../text-splitters does not exist
```

After investigating, I found out that this [commit](https://github.com/langchain-ai/langchain/commit/5efb5c099f6ced0b752306c4cb1c45370c2a6920) created a new packaged called `text-splitters` but this was never added in the [dev.Dockerfile](https://github.com/langchain-ai/langchain/blob/b051bba1a9f3f2c6020d7c8dbcc792d14b3cbe17/libs/langchain/dev.Dockerfile) file.

### System Info

_NO_SYSTEM_INFO_

**Comment by mdrxy** [comment]
Give new updates a try
