### ISSUE TITLE
I would like to provide an entry for role=system

### ISSUE THREAD

**Issue by ly-wenli** [langchain-ai/langchain#1848]
The role attribute in line 616 of openai.py under the llms package of langchain is expected to provide an external modification entry or parameter.
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/29686094/226600002-ba0a89fd-c65a-4d8c-92a0-73e7a44dfdb9.png">

Here are the parameter values of role when calling the model from the openai website.
<img width="239" alt="1774af7245061cda5320201e6529484e" src="https://user-images.githubusercontent.com/29686094/226600059-a6ae29d8-ac78-47ad-9542-9bf60cacd018.png">

**Comment by Aratako** [comment]
So, you mean you want to pass the user input with a role other than "user"?
I think you can achieve this by using the PromptTemplate with ChatOpenAI class.
https://langchain.readthedocs.io/en/latest/modules/chat/getting_started.html

I think the OpenAIChat class have been planned to be deprecated and no longer supported, if I remember correctly.

**Comment by Aratako** [comment]
I'm sorry, I'm not sure what you mean by "openai website."
Are you referring to the web version of ChatGPT? Are you saying that the user input is passed with the system role there?
Also, when you use it like `llm = OpenAI(temperature=0)`, it should be using the `text-davinci-003` model, and I would expect the output to be different.
