### ISSUE TITLE
where is "evaluation"  package

### ISSUE THREAD

**Issue by vicmeng** [langchain-ai/langchain#18480]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

![image](https://github.com/langchain-ai/langchain/assets/48348224/54a96eb4-f6cd-4013-ad6c-4c5a52431619)

### Description

where is "evaluation"  package

### System Info

langchain 0.1.10
python 3.8

**Comment by hinthornw** [comment]
Change your file from `langchain.py` to anything else.
