### ISSUE TITLE
Tex to SQL , facing hallucination problem

### ISSUE THREAD

**Issue by saikumarveera** [langchain-ai/langchain#18495]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
db = SQLDatabase.from_databricks(catalog=catalog, schema=database,include_tables=table_names )
 llm=ChatDatabricks(endpoint="databricks-mixtral-8x7b-instruct", model_kwargs={"temperature": 0.5, "max_tokens": 1000
,'top_p': 0.7,'error_behaviour':'truncate_input_end','num_return_sequences':1} )
 agent = create_sql_query_chain(llm=llm, prompt=prompt, db=db )
 response=agent.invoke({"question":q ,"top_k":3,"table_info":table_info,"catalog":catalog,"database":database,"dialect":db.dialect})
print(response)
```

### Error Message and Stack Trace (if applicable)

Its not throwing any error but it comes with its own column names or tables which doesnt event exist

### Description

Am using the above code to convert NLP to SQL  project ,where am using databricks hosted mixtral instruct 7B  model and passed the catalog,database  and selected list of the tables names , and pass the NLP question to model ,the model is coming up with columns/table names which aren't part of my tables list input and also in addition to that its appending the special chars  to column names.

Note-
1. i want only the Databricks  SQL as an output response not the results which is why i didn't go thru the SQL agent approach
2. Also since its Databricks the tables doesn't have Primary keys and foreign keys , so how does the langchain db session assumes about relationships?
3. Am using fewshot template and even passing the table names along with its column name,datatype corresponding tables event though sql query used will show incorrect tables/columns  in SQL response

### System Info

langchain ,databricks-sql-connector,mlflow==2.9.0 are libraries which am using as part of my code.

**Comment by keenborder786** [comment]
It's very difficult to help you without you giving additional details about prompt that you are using.
