### ISSUE TITLE
Bedrock integration with Claude3 fails with ValidationException "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.

### ISSUE THREAD

**Issue by Barneyjm** [langchain-ai/langchain#18513]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import boto3
from langchain_community.llms import Bedrock

bedrock = boto3.client('bedrock-runtime' , 'us-east-1')

MODEL_KWARGS = {
"anthropic.claude-3-sonnet-20240229-v1:0": {
        "temperature": 0, 
        "top_k": 250, 
        "top_p": 1, 
        "max_tokens_to_sample": 2**10 
}}

model_id = 'anthropic.claude-3-sonnet-20240229-v1:0'
llm = Bedrock(model_id=model_id, model_kwargs=MODEL_KWARGS[model_id])
llm('tell me a joke')
```

### Error Message and Stack Trace (if applicable)

```
.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The function `__call__` was deprecated in LangChain 0.1.7 and will be removed in 0.2.0. Use invoke instead.
  warn_deprecated(
Traceback (most recent call last):
  File ".venv/lib/python3.11/site-packages/langchain_community/llms/bedrock.py", line 444, in _prepare_input_and_invoke
    response = self.client.invoke_model(**request_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 991, in __call__
    self.generate(
  File ".venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 741, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 605, in _generate_helper
    raise e
  File ".venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 592, in _generate_helper
    self._generate(
  File ".venv/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 1177, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File ".venv/lib/python3.11/site-packages/langchain_community/llms/bedrock.py", line 718, in _call
    return self._prepare_input_and_invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/langchain_community/llms/bedrock.py", line 451, in _prepare_input_and_invoke
    raise ValueError(f"Error raised by bedrock service: {e}")
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.
```

### Description

obviously claude3 is brand new, but initial testing with existing capabilities seems to indicate a change in how these models need to be invoked. 

I'd expect that these new models would work with existing langchain capabilities as drop-in improvements.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #50~20.04.1-Ubuntu SMP Wed Sep 6 17:29:11 UTC 2023
> Python Version:  3.11.4 (main, Aug  9 2023, 21:54:01) [GCC 10.2.1 20210110]

Package Information
-------------------
> langchain_core: 0.1.28
> langchain: 0.1.10
> langchain_community: 0.0.25
> langsmith: 0.1.14
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.14

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by efunneko** [comment]
Not too surprisingly, this same issue occurs going through the BedrockChat interface.

**Comment by Barneyjm** [comment]
i guess we just add a "if v3" step within that anthropic code block in LLMInputOutputAdapter to allow this to work?

**Comment by Barneyjm** [comment]
this might be an issue with Bedrock itself, the API endpoint is expecting a `prompt` keyword in the body, but the Anthropic Messaging API expects `content`. 

When you pass `content` you get an unexpected keyword error but if you format the `prompt` in the messaging format, you get `prompt must start with Human:` errors

```python 
langchain_community/llms/bedrock.py:415
...
input_body = LLMInputOutputAdapter.prepare_input(provider, prompt, params)
input_body['content'] = input_body['prompt']
```
with `content` key:
```
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #: extraneous key [content] is not permitted, please reformat your input and try again.
```
with `prompt` formatted to messages api spec:
```
ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: prompt must start with "\n\nHuman:" turn after an optional system prompt
```

**Comment by Barneyjm** [comment]
talked with AWS support about the new format of Claude requests. here's the input body that works from boto3==1.34.54

```
{
  "max_tokens": 1024, 
  "system": "Today is January 1, 2024. Only respond in Haiku", 
  "messages": [{"role": "user", "content": "Hello, Claude"}], 
  "anthropic_version": "bedrock-2023-05-31"
}
```

**Comment by jobcase-plebedev** [comment]
It would be very helpful if Claude 3 worked with `RetrievalQA` - I can use the same code with Claude 2.1 or OpenAI as long as I get LLMs appropriately (i.e. `Bedrock(model_id="anthropic.claude-v2:1..."` or `ChatOpenAI` but I can't use the same approach with Claude 3.

**Comment by Barneyjm** [comment]
starting to take a swing at it here https://github.com/langchain-ai/langchain/pull/18548

**Comment by Mantej-Singh** [comment]
`retrieveAndGenerate` is also not supported with `anthropic.claude-3-sonnet-20240229-v1:0`

Error:
ValidrationException: An error occurred (ValidationException) when calling the RetrieveAndGenerate operation: The model arn provided is not supported. Please check your configuration and retry the request.
