### ISSUE TITLE
AttributeError: module 'sqlalchemy' has no attribute 'Select' when importing AmazonTextractPDFLoader 

### ISSUE THREAD

**Issue by ajfiala** [langchain-ai/langchain#18528]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

# Refactored document processing and text extraction
import io
from typing import List
from langchain_community.document_loaders import AmazonTextractPDFLoader

class DocumentProcessor:
    def __init__(self):
        pass

    def convert_to_text(self, s3_url: str) -> List[str]:
        """Downloads the PDF from S3, processes it, and returns the text as a list of strings."""
        print(f"Processing S3 URL: {s3_url}")
        try:
            loader = AmazonTextractPDFLoader(s3_url)
            pages = loader.load_and_split()
            text = [page.page_content for page in pages if page.page_content is not None]
            return text
        except Exception as e:
            print(f"Error processing {s3_url}: {e}")
            return []

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[16], line 10
      5 get_ipython().system('pip install SQLAlchemy==1.3')
      6 # from sqlalchemy import select
      7 # import sqlalchemy as sa
      8 # sa.Select
---> 10 from langchain_community.document_loaders import AmazonTextractPDFLoader
     12 class DocumentProcessor:
     13     def __init__(self):

File /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/__init__.py:190
    188 from langchain_community.document_loaders.snowflake_loader import SnowflakeLoader
    189 from langchain_community.document_loaders.spreedly import SpreedlyLoader
--> 190 from langchain_community.document_loaders.sql_database import SQLDatabaseLoader
    191 from langchain_community.document_loaders.srt import SRTLoader
    192 from langchain_community.document_loaders.stripe import StripeLoader

File /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/sql_database.py:10
      6 from langchain_community.document_loaders.base import BaseLoader
      7 from langchain_community.utilities.sql_database import SQLDatabase
---> 10 class SQLDatabaseLoader(BaseLoader):
     11     """
     12     Load documents by querying database tables supported by SQLAlchemy.
     13 
   (...)
     17     Each document represents one row of the result.
     18     """
     20     def __init__(
     21         self,
     22         query: Union[str, sa.Select],
   (...)
     30         include_query_into_metadata: bool = False,
     31     ):

File /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/sql_database.py:22, in SQLDatabaseLoader()
     10 class SQLDatabaseLoader(BaseLoader):
     11     """
     12     Load documents by querying database tables supported by SQLAlchemy.
     13 
   (...)
     17     Each document represents one row of the result.
     18     """
     20     def __init__(
     21         self,
---> 22         query: Union[str, sa.Select],
     23         db: SQLDatabase,
     24         *,
     25         parameters: Optional[Dict[str, Any]] = None,
     26         page_content_mapper: Optional[Callable[..., str]] = None,
     27         metadata_mapper: Optional[Callable[..., Dict[str, Any]]] = None,
     28         source_columns: Optional[Sequence[str]] = None,
     29         include_rownum_into_metadata: bool = False,
     30         include_query_into_metadata: bool = False,
     31     ):
     32         """
     33         Args:
     34             query: The query to execute.
   (...)
     49               expression into the metadata dictionary. Default: False.
     50         """
     51         self.query = query

AttributeError: module 'sqlalchemy' has no attribute 'Select'

### Description

I'm trying to use the latest version of langchain_community so that I can use Amazon Textract to get text from PDFs. It was working last week but now I am seeing an error from sqlalchemy in the /opt/conda/lib/python3.10/site-packages/langchain_community/document_loaders/sql_database.py file. I tried downgrading sqlalchemy to 1.3 and saw the same error.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Jan 12 09:58:17 UTC 2024
> Python Version:  3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.1.28
> langchain: 0.1.10
> langchain_community: 0.0.25
> langsmith: 0.1.16
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by better629** [comment]
`pip3 install sqlalchemy==2.0.0` will fix this.

**Comment by better629** [comment]
`pip3 install sqlalchemy==2.0.0` will fix this.

**Comment by harrysalmon** [comment]
So has the migration been made to SQLalchermy 2 but the requirements not updated or are there different parts of the code which still need migrating?

**Comment by 10-OASIS-01** [comment]
Did you fix this？ I had the same issue.

**Comment by QipengZhou** [comment]
`pip list` check your SQLAlchemy version. If SQLAlchemy 2 not conflict with other packages, you may upgrade SQLAlchemy by `pip install -U 'SQLAlchemy>=1.4,<3'`.

**Comment by ajfiala** [comment]
> `pip3 install sqlalchemy==2.0.0` will fix this.

Thanks, this fixed it!

**Comment by ADaozz** [comment]
> `pip3 install sqlalchemy==2.0.0`会解决这个问题。

thanks a lot

**Comment by harsh-kr512** [comment]
Thanks 🎉🎉🎉
