### ISSUE TITLE
ValueError when using Azure and chat-zero-shot-react-description agent

### ISSUE THREAD

**Issue by damosuzuki** [langchain-ai/langchain#1852]
I am trying to follow the [MRKL chat example](https://langchain.readthedocs.io/en/latest/modules/agents/implementations/mrkl_chat.html) but with AzureOpenAI (`text-davinci-003`) and AzureChatOpenAI (`gpt-3.5-turbo`). However, I am running into this error:
```
ValueError: `stop` found in both the input and default params.
```

I have confirmed that AzureOpenAI and AzureChatOpenAI work independently from the agent:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/404062/226631921-e1c85c76-0bdf-4415-9cae-7149eced7f0f.png">

I am using langchain version 0.0.117.

Seems related to this WIP PR: https://github.com/hwchase17/langchain/pull/1817

**Comment by gd1m3y** [comment]
you can quick fix that by commenting line 266 on openai.py chatmodels i wont recommend it but its working after doing that
