### ISSUE TITLE
AttributeError: module 'sqlalchemy' has no attribute 'Select' when using SQLDatabaseLoader in langchain_community

### ISSUE THREAD

**Issue by 10-OASIS-01** [langchain-ai/langchain#18552]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os
from langchain_community.document_loaders import TextLoader
loader = TextLoader("state_of_the_union.txt")
loader.load()

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 2
      1 import os
----> 2 from langchain_community.document_loaders import TextLoader
      3 loader = TextLoader("state_of_the_union.txt")
      4 loader.load()

File ~\AppData\Roaming\Python\Python310\site-packages\langchain_community\document_loaders\__init__.py:190
    188 from langchain_community.document_loaders.snowflake_loader import SnowflakeLoader
    189 from langchain_community.document_loaders.spreedly import SpreedlyLoader
--> 190 from langchain_community.document_loaders.sql_database import SQLDatabaseLoader
    191 from langchain_community.document_loaders.srt import SRTLoader
    192 from langchain_community.document_loaders.stripe import StripeLoader

File ~\AppData\Roaming\Python\Python310\site-packages\langchain_community\document_loaders\sql_database.py:10
      6 from langchain_community.document_loaders.base import BaseLoader
      7 from langchain_community.utilities.sql_database import SQLDatabase
---> 10 class SQLDatabaseLoader(BaseLoader):
     11     """
     12     Load documents by querying database tables supported by SQLAlchemy.
     13 
   (...)
     17     Each document represents one row of the result.
     18     """
     20     def __init__(
     21         self,
     22         query: Union[str, sa.Select],
   (...)
     30         include_query_into_metadata: bool = False,
     31     ):

File ~\AppData\Roaming\Python\Python310\site-packages\langchain_community\document_loaders\sql_database.py:22, in SQLDatabaseLoader()
     10 class SQLDatabaseLoader(BaseLoader):
     11     """
     12     Load documents by querying database tables supported by SQLAlchemy.
     13 
   (...)
     17     Each document represents one row of the result.
     18     """
     20     def __init__(
     21         self,
---> 22         query: Union[str, sa.Select],
     23         db: SQLDatabase,
     24         *,
     25         parameters: Optional[Dict[str, Any]] = None,
     26         page_content_mapper: Optional[Callable[..., str]] = None,
     27         metadata_mapper: Optional[Callable[..., Dict[str, Any]]] = None,
     28         source_columns: Optional[Sequence[str]] = None,
     29         include_rownum_into_metadata: bool = False,
     30         include_query_into_metadata: bool = False,
     31     ):
     32         """
     33         Args:
     34             query: The query to execute.
   (...)
     49               expression into the metadata dictionary. Default: False.
     50         """
     51         self.query = query

---------------------------------------------------------------------------
AttributeError: module 'sqlalchemy' has no attribute 'Select'

### Description

I am new to Langchain and I am stuck at an issue. My end goal is to read the contents of a file and create a vectorstore of my data which I can query later. I'm encountering an error while trying to use the SQLDatabaseLoader from the langchain_community package. 

It seems to be referencing an attribute 'Select' from the 'sqlalchemy' module, but it's unable to find it. I'm not sure why this error is occurring, especially since I haven't directly used 'sqlalchemy. Select' in my code. I've tried using versions 1.3, 1.4, and 2.0 of SQLAlchemy, but I still encounter the same error.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.29
> langchain: 0.1.10
> langchain_community: 0.0.25
> langsmith: 0.1.18
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by 10-OASIS-01** [comment]
AttributeError: module 'sqlalchemy' has no attribute 'Select', is encountered when attempting to use the SQLDatabaseLoader from the langchain_community package in the LangChain framework. The issue arises while executing the code, specifically within the SQLDatabaseLoader class, referencing an attribute Select from the sqlalchemy module, which cannot be found.

**Comment by Rakib-hosen** [comment]
@10-OASIS-01  I am seeing that your python environment is 3.10 in
`  :File ~\AppData\Roaming\Python\**Python310**\site-packages\langchain_community\document_loaders\sql_database.py:22, `
are you sure you are using right environment?

**Comment by better629** [comment]
`pip3 install sqlalchemy==2.0.0` will fix this.

**Comment by 10-OASIS-01** [comment]
> `pip3 install sqlalchemy==2.0.0` will fix this.
I tried it but it didn't work

**Comment by saifmahin44** [comment]
> I experienced similar symptom. If you use Jupyter extention in VSC, reinstall or update it. it works in my case!

Thanks Man, this suggestion works.

**Comment by wubbyweb** [comment]
Reinstalling Jupyter  VSC extension worked for me too.
