### ISSUE TITLE
Input is empty string in ConsoleCallBackHandler outputs

### ISSUE THREAD

**Issue by YogeshBalasubramaniyam** [langchain-ai/langchain#18567]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

async for token in retrieval_chain().astream(
                {
                    "question": question,
                    "history": [],
                },
                config={"callbacks": [ConsoleCallbackHandler()]},
            ):  # type: ignore
                yield ChatSSEResponse(type="streaming", value=token).model_dump_json()

### Error Message and Stack Trace (if applicable)

<img width="1779" alt="image" src="https://github.com/langchain-ai/langchain/assets/79570011/4b231a27-5328-41b1-8c2a-92758eb85cc3">

### Description

With the given code, we are using ConsoleCallbackHandler form langchain_core.tracers to print all the inputs, outputs and all the api calls that are going behind the scenes.
But with this setup, we are not getting the inputs and the inputs are logged as empty strings but this is working and inputs are logged when we don't use streaming instead use normal invoke method while invoking the chain.

### System Info

python version - 3.11
langchain_core version - 0.1.23
langchain version - 0.1.3

**Comment by wodadehencou** [comment]
Got the same bug.

langchain_core.runnables.base.py
```python
def _transform_stream_with_config(
...
        run_manager = callback_manager.on_chain_start(
            dumpd(self),
            {"input": ""},
            run_type=run_type,
            name=config.get("run_name") or self.get_name(),
...
```

Why input is **`{"input": ""}`** when call on_chain_start, but when using invoke, input is just `input`. Any special considerations?

**Comment by hourliert** [comment]
I am having the same bug. 

```
for chunk in chain.stream({"input": "test"}
  print(chunk)
```

In one of my callback:
```

    def on_chain_start(
        self, serialized: Dict[str, Any], inputs: Dict[str, Any], run_id, parent_run_id, **kwargs: Any
    ) -> Any:
      print(inputs)

    end
```

outputs: `{"input": ""}`
