### ISSUE TITLE
Token count is not reported for openai tools agent

### ISSUE THREAD

**Issue by salmanmashayekh** [langchain-ai/langchain#18617]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain import hub
from langchain.agents import (
    AgentExecutor,
    create_openai_tools_agent,
)
from langchain.tools import tool
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI


llm = AzureChatOpenAI(
    api_key="...",
    azure_deployment="...",
    azure_endpoint="...",
    api_version="2024-02-15-preview",
    streaming=False,
)

@tool
def multiply(a: int, b: int) -> int:
    """Multiply two numbers."""
    return a * b

prompt = hub.pull("hwchase17/openai-tools-agent")
tools = [multiply]
agent = create_openai_tools_agent(llm, tools, prompt)
agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
)

with get_openai_callback() as cb:
    resp = agent_executor.invoke({"input": "What's 3 multiplied by 4?"})
    print(cb)

assert cb.total_tokens > 0
```

### Error Message and Stack Trace (if applicable)

The assertion in the minimum working example fails as the token count is zero. 

### Description

I am trying to track token usage with an azure openai tools agent. But the token count always returns zero. 

### System Info

```
langchain==0.1.11
langchain-community==0.0.25
langchain-core==0.1.29
langchain-openai==0.0.6
langchain-text-splitters==0.0.1
langchainhub==0.1.15
langchain-openai==0.0.6
openai==1.13.3
```

**Comment by eyurtsev** [comment]
Duplicate

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langchain/issues/16798
