### ISSUE TITLE
Integration with TogetherAI does not work properly, unable to import

### ISSUE THREAD

**Issue by aabor** [langchain-ai/langchain#18612]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
from langchain_together.llms import Together
from langchain_together.embeddings import TogetherEmbeddings as LangchainTogetherEmbeddings
```

### Error Message and Stack Trace (if applicable)

  File "/Users/aabor/projects/rag/llm_select.py", line 7, in <module>
    from langchain_together.llms import Together
  File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/langchain_together/__init__.py", line 1, in <module>
    from langchain_together.embeddings import TogetherEmbeddings
  File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/langchain_together/embeddings.py", line 10, in <module>
    class TogetherEmbeddings(BaseModel, Embeddings):
  File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/langchain_together/embeddings.py", line 23, in TogetherEmbeddings
    _client: together.Together
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'together' has no attribute 'Together'

### Description

Example code from langchain documentation provokes error. 
I just want to import classes from langchain_together package.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
> Python Version:  3.11.6 (v3.11.6:8b6ee5ba3b, Oct  2 2023, 11:18:21) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.1.28
> langchain: 0.1.11
> langchain_community: 0.0.24
> langsmith: 0.1.21
> langchain_text_splitters: 0.0.1
> langchain_together: 0.0.2.post1

**Comment by AyushModi123** [comment]
Hi @aabor, check the version of together package 
`pip show together`
and try updating it by running
`pip install --upgrade together` 

This should resolve the issue.

**Comment by aabor** [comment]
I did as suggested, but the problem remained the same. I have the most recent version of together==0.2.11 package.

  File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/langchain_together/embeddings.py", line 10, in <module>
    class TogetherEmbeddings(BaseModel, Embeddings):
  File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/langchain_together/embeddings.py", line 23, in TogetherEmbeddings
    _client: together.Together
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'together' has no attribute 'Together'

**Comment by AyushModi123** [comment]
Do you some other module named 'together.py' in your project('/rag')?

**Comment by aabor** [comment]
Yes, I had the file /rag/together.py in my project root directory and this was the problem. I deleted it and now it works.
I appreciate your help.
