### ISSUE TITLE
ElasticSearch retreiver issue based on score_threshold

### ISSUE THREAD

**Issue by TanzeelAbbas** [langchain-ai/langchain#18623]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

retriever = elastic_search_db.as_retriever(
    search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.5}
)
docs = retriever.get_relevant_documents(query)

### Description

why similarity_score_threshold is not working. When i changed search_type to similarity then it is worked but retreiverdocument not based on score threshold.

### System Info

version latest
python 3.10

**Comment by iuliaferoli** [comment]
same answer as on Discuss for visibility: 
Hi!

Do you have some more information about your example and how it's not working? 

I just tested it in one of my projects and it seems to run for me. 

When the threshold is 0.5 I get the same results with the threshold as with the normal similarity. With a higher threshold, some results are omited, and for example, if I increase the threshold too much I get this back: `UserWarning: No relevant docs were retrieved using the relevance score threshold 0.8` so it seems to be taking the threshold into account.

This is the rest of my code FYI:

```
db = ElasticsearchStore(
    index_name=index_name,
    es_connection=es_connection,
    query_field="text_field",
    vector_query_field="vector_query_field.predicted_value",
    strategy=ElasticsearchStore.ApproxRetrievalStrategy(
        query_model_id=model_id
    ),
)

db.client.indices.refresh(index=index_name)

retriever = db.as_retriever(
search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.7}
)

docs = retriever.get_relevant_documents(query)
```

**Comment by TanzeelAbbas** [comment]
@iuliaferoli    
Here is code

elastic_vector_search = ElasticsearchStore(
                es_url=es_config.HOST,
                index_name=LLMConfig.EMBEDDING_INDEX_NAME(),
                embedding=self.bgeEmbeddings,
            )

retriever = self.elastic_vector_search.as_retriever(search_types = "similarity_score_threshold", search_kwargs {'score_threshold': 0.7})
 docs = retriever.get_relevant_documents(query)
