### ISSUE TITLE
KeyError: 'openai_api_version'

### ISSUE THREAD

**Issue by yidasanqian** [langchain-ai/langchain#18632]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os
from langchain_openai import AzureChatOpenAI
api_base = os.getenv("AZURE_OPENAI_ENDPOINT")
api_key= os.getenv("AZURE_OPENAI_API_KEY")
api_version=os.getenv("OPENAI_API_VERSION"),
model_name = 'gpt-4' #Replace with model deployment name

llm = AzureChatOpenAI(  
    api_key=api_key,
    azure_endpoint=api_base, 
    azure_deployment=model_name,
    openai_api_version = api_version,
    temperature=0
    )

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "d:\Develop\CodeProjects\chatgpt4v-demo\langchainApp.py", line 11, in <module>
    llm = AzureChatOpenAI(
  File "D:\Develop\anaconda3\lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1100, in pydantic.main.validate_model
  File "D:\Develop\anaconda3\lib\site-packages\langchain_openai\chat_models\azure.py", line 125, in validate_environment
    values["openai_api_version"] = values["openai_api_version"] or os.getenv(
KeyError: 'openai_api_version'

### Description

I want to instantiate AzureChatOpenAI correctly

### System Info

libs:
langchain                     0.1.11
langchain-community           0.0.25
langchain-core                0.1.29
langchain-openai              0.0.8
langchain-text-splitters      0.0.1

openai                        1.12.0

platform:
Windows

python version: 3.9.16

**Comment by efriis** [comment]
Hey there! I tried reproducing your issue in a unit test to no avail. Maybe one of the environment variables you're populating isn't actually there? This seems to be happening in a part that should be getting populated by pydantic though...

Another suggestion is to update your pydantic version. 

https://github.com/langchain-ai/langchain/pull/18703

**Comment by yidasanqian** [comment]
> Hey there! I tried reproducing your issue in a unit test to no avail. Maybe one of the environment variables you're populating isn't actually there? This seems to be happening in a part that should be getting populated by pydantic though...
> 
> Another suggestion is to update your pydantic version.
> 
> #18703

I am sure that the value of the environment variable exists.
my .env
```
OPENAI_API_VERSION=2024-02-15-preview
AZURE_OPENAI_API_KEY=XXXX
AZURE_OPENAI_ENDPOINT=https://XXX.openai.azure.com
```
and
pydantic version=2.6.3
