### ISSUE TITLE
anthropic error 400 "claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead.

### ISSUE THREAD

**Issue by BioStarr** [langchain-ai/langchain#18646]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.chat_models import ChatAnthropic

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True,output_key="answer")
            callback = StreamHandler(st.empty())
            llm = ChatAnthropic(temperature=0.5, max_tokens=1000, model_name= "claude-3-opus-20240229",streaming=True,callbacks=[callback])
            qa = ConversationalRetrievalChain.from_llm(llm=llm, retriever=vector_store.as_retriever(),memory=memory,verbose=True)
            result = qa.invoke({"question": prompt, "chat_history": [(message["role"], message["content"]) for message in st.session_state.messages]})
            full_response = result["answer"]

### Error Message and Stack Trace (if applicable)

anthropic error 400 "claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead.

### Description

Once I switch mode_namel from claude-2 to: claude-3-opus-2024022 I get following error:

anthropic error 400 "claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead.

I tried updating langchain to latest but it did not resolve the issue.

### System Info

langchain==0.1.6
langchain-community==0.0.19
langchain-core==0.1.23
langchain-experimental==0.0.50
langchain-openai==0.0.5
langchainhub==0.1.13
anthropic==0.10.0
Windows11

**Comment by shroominic** [comment]
having the same issue i think its because the ChatAnthropic wrapper is generating chat messages based on compleations and not from the messages api 
`response = self.client.completions.create(**params)`

**Comment by shroominic** [comment]
got fixed here we just need to wait for the release https://github.com/langchain-ai/langchain/pull/18630

**Comment by maxwellstrome** [comment]
It will not work if you do the import as from langchain_community.chat_models import ChatAnthropic
, but if you do from langchain_anthropic.experimental import ChatAnthropic it works

**Comment by baskaryan** [comment]
langchain-community version of ChatAnthropic is deprecated and not up to date with the latest endpoints. please use the langchain-anthropic version
```bash
pip install -U langchain-anthropic
```
and
```python
from langchain_anthropic import ChatAnthropic

llm = ChatAnthropic(temperature=0.5, max_tokens=1000, model_name= "claude-3-opus-20240229")
```

integration docs: https://python.langchain.com/docs/integrations/chat/anthropic

**Comment by Sameera2001Perera** [comment]
same here.
Claude 3 models works with "from langchain_anthropic import ChatAnthropic". But in that case it is not compatible with my code base, I mean I cant pass the "streaming=True".

    def __create_llm(self, llm_type: LLMTypes, callback_handler: StreamingHandler):
        if llm_type == LLMTypes.OPENAI:
            return ChatOpenAI(
                callbacks=[callback_handler],
                temperature=0,
                model_name=config.GPT4_MODEL,
                streaming=True,
            )
        elif llm_type == LLMTypes.PALM:
            return ChatVertexAI(
                model_name=config.PALM_MODEL,
                temperature=0,
                callbacks=[callback_handler],
                streaming=True,
                max_output_tokens=2048,
            )
        elif llm_type == LLMTypes.GEMINI:
            return ChatVertexAI(
                model=config.GEMINI_MODEL,
                temperature=0,
                streaming=True,
                verbose=config.VERBOSE,
                callbacks=[callback_handler],
                max_output_tokens=2048,
                convert_system_message_to_human=True,
            )
        elif llm_type == LLMTypes.CLAUDE:
            return ChatAnthropic(
                model_name=config.CLAUDE_MODEL,
                temperature=0,
                streaming=True,
                verbose=config.VERBOSE,
                callbacks=[callback_handler],
                max_tokens=2048,
            )
        else:
            raise ValueError("Unsupported LLM type")

**Comment by BioStarr** [comment]
@baskaryan Hey your solution works, but there is no support for streaming and that is very important to me.

**Comment by efriis** [comment]
https://github.com/langchain-ai/langchain/pull/18819
