### ISSUE TITLE
ElasticVectorSearch constructor to support Elastic Cloud

### ISSUE THREAD

**Issue by brandco** [langchain-ai/langchain#1865]
The current constructor for ElasticVectorSearch does not support connecting to Elastic Cloud.

```
>>> db = ElasticVectorSearch.from_documents(docs, embeddings,
...                                         cloud_id = CLOUD_ID,
...                                         basic_auth=(USER_NAME, PASSWORD))Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "c:\Users\bcollingsworth\code\langchain_testing\.venv\lib\site-packages\langchain\vectorstores\base.py", line 113, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "c:\Users\bcollingsworth\code\langchain_testing\.venv\lib\site-packages\langchain\vectorstores\elastic_vector_search.py", line 161, in from_texts
    elasticsearch_url = get_from_dict_or_env(
  File "c:\Users\bcollingsworth\code\langchain_testing\.venv\lib\site-packages\langchain\utils.py", line 17, in get_from_dict_or_env
    raise ValueError(
ValueError: Did not find elasticsearch_url, please add an environment variable `ELASTICSEARCH_URL` which contains it, or pass  `elasticsearch_url` as a named parameter.
``` 
It looks like the current implementation would only support an instance of Elastic Search on localhost without security enabled, which is not recommended. 

I can connect with the elasticsearch python client like this:
```
from elasticsearch import Elasticsearch

es = Elasticsearch(cloud_id=CLOUD_ID, http_auth=(USER_NAME, PASSWORD))
es.info()
```

See the documentation at [Connecting to Elastic Cloud](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connect-ec)

An alternative constructor to the ElasticVectorSearch that takes a elasticsearch client instance, index name and embedding object would allow the user to deal with all the possible authentication set ups before using langchain.

**Comment by vibha0411** [comment]
I still have an issue.
**I am trying to use ElasticVectorSearch.from_documents and it is creating a random index name and not using the index_name provided.**
Is there any reason for this?

**Comment by brandco** [comment]
Thank you all. I'm sorry I was not able to test this fix because I had to spin down my cloud instance.
