### ISSUE TITLE
NotImplementedError in ConversationSummaryBufferMemory.save_context with get_num_tokens_from_messages

### ISSUE THREAD

**Issue by AymaneHan1** [langchain-ai/langchain#18650]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

When attempting to use the ConversationSummaryBufferMemory.save_context method in the LangChain library, I encountered a NotImplementedError. This error occurs specifically when calling get_num_tokens_from_messages() for the model gpt-35-turbo-16k. I am trying to integrate the AzureChatOpenAI model with a custom memory buffer to manage conversation states but faced this issue during implementation.

To reproduce the error 
```
from langchain.chat_models.azure_openai import AzureChatOpenAI
from langchain.memory import ConversationSummaryBufferMemory

llm = AzureChatOpenAI(
    openai_api_version=constant.OPENAI_API_VERSION,
    azure_endpoint=constant.OPENAI_API_BASE,
    api_key=constant.OPENAI_API_KEY,
    model=constant.OPENAI_GPT_MODEL_NAME,
    azure_deployment=constant.OPENAI_GPT_DEPLOYMENT_NAME,
    temperature=0,
)

memory = ConversationSummaryBufferMemory(llm=llm, max_token_limit=10)
memory.save_context({"input": "hi"}, {"output": "whats up"})
```

### Error Message and Stack Trace (if applicable)

NotImplementedError: get_num_tokens_from_messages() is not presently implemented for model gpt-35-turbo-16k.
See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.

### Description

Initialize AzureChatOpenAI with the model gpt-35-turbo-16k.
Create an instance of ConversationSummaryBufferMemory with a small max_token_limit (e.g., 10 tokens).
Attempt to save a context using memory.save_context({"input": "hi"}, {"output": "whats up"}).

### System Info

- langchain==0.1.11
- Python version: 3.11
- Operating System: Windows

**Comment by keenborder786** [comment]
Yeap this is expected, since this is not yet implemented in langchain. Please see [this](https://github.com/keenborder786/langchain/blob/ea141511d896ab52b49cca097f85bb5e1f18846b/libs/community/langchain_community/chat_models/openai.py#L629)

**Comment by npuichigo** [comment]
@keenborder786 The `get_num_tokens_from_messages` is called by `ConversationSummaryBufferMemory` with the passed `llm`, actually an option can be added to it to customize the way to calculate the number of tokens.

In  `OpenAIEmbedding`, the implementation would also try to calculate the tokens before sending request, `tiktoken_enabled` and `model` can be configured to use even huggingface tokenizer to do that.

**Comment by SanthanaMano** [comment]
Hi @AymaneHan1
Did you try to find solution for that error ?
Thanks in advance
