### ISSUE TITLE
NotFoundError: Error code: 404 - {'detail': 'Not Found'}

### ISSUE THREAD

**Issue by KHRMNKY** [langchain-ai/langchain#18652]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

'''  
!pip -q install langchain openai tiktoken  pypdf InstructorEmbedding faiss-cpu

!pip install sentence-transformers==2.2.2

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import DirectoryLoader
from InstructorEmbedding import INSTRUCTOR
from langchain.embeddings import HuggingFaceInstructEmbeddings

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/MyDrive"

path = "/content/gdrive/MyDrive/Documents/inek"
loader = DirectoryLoader(path , glob="./*.pdf", loader_cls=PyPDFLoader)
documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
                                               chunk_size=1000,
                                               chunk_overlap=200)

texts = text_splitter.split_documents(documents)

len(texts)

texts[3]

import pickle
import faiss
from langchain.vectorstores import FAISS

from langchain.embeddings import HuggingFaceInstructEmbeddings

instructor_embeddings = HuggingFaceInstructEmbeddings(model_name="asafaya/kanarya-750m"
                                                         )
db_instructEmbedd = FAISS.from_documents(texts, instructor_embeddings)

retriever = db_instructEmbedd.as_retriever(search_kwargs={"k": 3})

docs = retriever.get_relevant_documents("Ketosiz hastalığı nedir kimlerde görülür?")

api_key= "sk-ac2d3761ef1e42e2aa18c4fc9cb381ec"
base_url = "https://api.deepseek.com/v1"

client = OpenAI(api_key=api_key, base_url=base_url)

qa_chain_deepseek = RetrievalQA.from_chain_type(
    llm=client,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True
)

query = "Ketosiz hastalığı nedir kimlerde görülür?"
llm_response = qa_chain_deepseek(query)
print(llm_response["result"])

'''

### Error Message and Stack Trace (if applicable)

NotFoundError                             Traceback (most recent call last)
[<ipython-input-26-792341640681>](https://localhost:8080/#) in <cell line: 16>()
     14 
     15 query = "Ketosiz hastalığı nedir kimlerde görülür?"
---> 16 llm_response = qa_chain_deepseek(query)
     17 print(llm_response["result"])

30 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in _request(self, cast_to, options, remaining_retries, stream, stream_cls)
    978 
    979             log.debug("Re-raising status error")
--> 980             raise self._make_status_error_from_response(err.response) from None
    981 
    982         return self._process_response(

NotFoundError: Error code: 404 - {'detail': 'Not Found'}

### Description

* I'm getting NotFoundError: Error code: 404 - {'detail': 'Not Found'}
* Please help me that why I'm getting this error.

### System Info

*

**Comment by aman-cpu** [comment]
I m also getting the same error.
Can you tell me whether this issue is fixed or not??

**Comment by alokkrsahu** [comment]
File "/anaconda3/lib/python3.11/site-packages/openai/_base_client.py", line 1013, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'detail': 'Not Found'}


I am also getting the same error. Please help.

**Comment by jddao** [comment]
try change base_url = "https://api.deepseek.com/v1" to  base_url = "https://api.deepseek.com"

**Comment by jockeyyan** [comment]
Maybe is your llm endpoint setting error, you should use "http://<ip>:<port>/api/v1/chat/completions" as parameter of llm.

**Comment by alm0ra** [comment]
@KHRMNKY @jockeyyan 

can you use langchain with deepseek ? i could not found any document

**Comment by texasdave2** [comment]
Fixed mine by changing the URL as suggested above, changed to:

http://api/v1
