### ISSUE TITLE
Use human input as a tool

### ISSUE THREAD

**Issue by ekzhu** [langchain-ai/langchain#1871]
We should add human input as a tool. Human is AGI and can step in when the model is confused or lost, or need some help.

**Comment by gwc4github** [comment]
This tool is really interesting.  I had a problem using it in a notebook running inside PyCharm in that it would not show the question you were asked. Instead it just asked for input.
How is this meant to be run?  A web-based notebook, a py file, or ?

**Comment by gwc4github** [comment]
@dosu-beta My note does not say that this is fixed.  I think there are more enhancements that would be useful.  My comment only informs a compatibility issue with a particular IDE.

**Comment by omprakashnarayan** [comment]
Hi team is there a way to get input from frontend via websocket endpoint using this tool and also send the response to API as a query

**Comment by sbangariGIT** [comment]
@omprakashnarayan , not sure if this helps but you can modify the prompt_func and change it to getting the input from elsewhere not just the command line.  
https://github.com/langchain-ai/langchain/pull/1879/files#diff-f22ff4826ad65c638983e0d3c121e002c24d87657ccdf72977a675fba6481453R30
