### ISSUE TITLE
using OpenAIEmbeddings popup exception say please use AzureOpenAIEmbeddings

### ISSUE THREAD

**Issue by shaojun** [langchain-ai/langchain#18727]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_core.documents import Document
from langchain_pinecone import PineconeVectorStore
from langchain_openai import AzureOpenAIEmbeddings, OpenAIEmbeddings

# os.environ["PINECONE_API_KEY"] = "xxxxxxxxxxxxx-xxxxx-4c9f-99a0-42b2e5922ba0"
# os.environ["PINECONE_INDEX_NAME"] = "zzzzzzzzz"
doc = Document("hello world")
raw_documents: list[Document] = [doc]
text_splitter = CharacterTextSplitter(
    chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(raw_documents)
embeddings = OpenAIEmbeddings()

docsearch = PineconeVectorStore.from_documents(
    docs, embeddings, index_name=os.environ["PINECONE_INDEX_NAME"])
```

throw an exception say:
> Exception has occurred: ValidationError
1 validation error for OpenAIEmbeddings
__root__
  If you are using Azure, please use the `AzureOpenAIEmbeddings` class. (type=value_error)
  File "D:\src\lang-serve-fastapi-v3-proxy-ai\code\test2_index.py", line 48, in <module>
    embeddings = OpenAIEmbeddings()
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAIEmbeddings
__root__
  If you are using Azure, please use the `AzureOpenAIEmbeddings` class. (type=value_error)]

at:
![image](https://github.com/langchain-ai/langchain/assets/3241829/dd53ae06-d0e9-4e86-bd80-80f8ec55a3b7)

### Description

use vector database.

### System Info

langchain==0.1.11
langchain-community==0.0.27
langchain-core==0.1.30
langchain-openai==0.0.8
langchain-pinecone==0.0.3
langchain-text-splitters==0.0.1
langchainhub==0.1.14
langserve==0.0.41
langsmith==0.1.22

**Comment by liugddx** [comment]
Please check the value of variable `openai_api_type`

**Comment by shaojun** [comment]
> Please check the value of variable `openai_api_type`

thanks, it works by `embeddings = OpenAIEmbeddings(openai_api_type="openai")`, please help to update to doc.
