### ISSUE TITLE
使用QAGenerateChain产生问答对，一个问答只能生成一个问答对吗？

### ISSUE THREAD

**Issue by yysturdy** [langchain-ai/langchain#18737]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

使用QAGenerateChain产生问答对，一个问答只能生成一个问答对吗？

### Idea or request for content:

使用QAGenerateChain产生问答对，一个问答只能生成一个问答对吗？如果我想某个文档产生自己想要数量的问答对，可以通过修改代码实现吗？

**Comment by eyurtsev** [comment]
Please use the QA section rather than issues

**Comment by yysturdy** [comment]
> Please use the QA section rather than issues
具体怎么操作呢，万分感谢，我没有看到哪个地方可以传入参数使得一个文档可以生成自己想要的问答对
