### ISSUE TITLE
How about pip install instructions that are formed correctly

### ISSUE THREAD

**Issue by AussieCog** [langchain-ai/langchain#18747]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

%pip install –upgrade –quiet langchain langchain-openai. 
fails . This is across just about every page.
Also, There are incomplete pip installs.   Especially in the cookbook.  What is there should be dirt simple to get running.

https://python.langchain.com/docs/expression_language/cookbook/multiple_chains

### Idea or request for content:

Also, you mention Runnables all over the place.  Not really any formal docs on it.  Same for chains.

**Comment by eyurtsev** [comment]
The instructions are hard to get right for every single page in the documentation since there are a lot of variations betwen environments. Feel free to update install instructions that you think are incorrect. This is an open source project and we welcome any contributions!
