### ISSUE TITLE
PGVector advanced filtering operators (e.g. `gte`) do not seem to work

### ISSUE THREAD

**Issue by orestxherija** [langchain-ai/langchain#18758]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am using a `PGVector` vector store and running the following code to retrieve relevant docs:

```python
retriever = pg_vs.as_retriever(
    search_kwargs = {
        "k" : 10,
        "filter" : {
            "year" : {"gte" : 2022}
        }
    }
)
```
When running `retriever.get_relevant_documents(query)` I get results that have a `year` field of less than 2022. I have tried different variations of the operator, such as `$gte` as well as other similar operators but they are all leading to the same result. The `year` column type is `int`.

### Description

I am trying to do metadata filtering using a "greater-than-or-equal-to" operator `gte` with a `PGVector` vector store, using a metadata field that is of type `int`. The filter does not work and the retriever returns results that do not adhere to the filter restriction.

### System Info

```
langchain==0.1.7
langchain_community==0.0.2.0
pgvector==0.2.5
```

**Comment by Robs-Git-Hub** [comment]
Have you got other comporators to work, like $eq?  I am struggling just with $eq at the moment.  

This retrieves appropriate results:
```
db.as_retriever(search_kwargs={
    'k': 2, 
    'filter': {'topic':'foo'}
}).get_relevant_documents(query)
```

While this retrieves nothing when I would expect it to retrieve the same result as above.
```
db.as_retriever(search_kwargs={
    'k': 2, 
    'filter': {'topic':{'$eq':'foo'}}
}).get_relevant_documents(query)
```
