### ISSUE TITLE
Update tool callbacks to send the actual response from the tool

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#18760]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Reproducible issue. on_tool_end logs the string representation of the tool. All tool callbacks need to be updated to accommodate

```python
from langchain_core.tools import tool
from langchain_core.documents import Document

def foo(x):
    return {
        'x': 5
    }

@tool
def get_docs(x: int):
    """Hello"""
    return [Document(page_content='hello')]

chain = foo | get_docs

async for event in chain.astream_events({}, version='v1'):
    if event['event'] == 'on_tool_end':
        print(event)
```

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langchain/discussions/18694

**Comment by eyurtsev** [comment]
This is a bug in the astream_events API and an enhancement for existing tool callback handlers

**Comment by keenborder786** [comment]
@eyurtsev I am taking this and working on it.

**Comment by eyurtsev** [comment]
@keenborder786 thanks for taking a look at this! The fix is actually more involved since it needs to be backwards compatible with existing callback handlers. I'm going to scope it out today

**Comment by keenborder786** [comment]
@eyurtsev oh okay. Can you please explain a little about the backwards compatibility in this case so I can help you as well. All the existing handlers that are using `on_tool_end` need to work properly??? Correct.

**Comment by eyurtsev** [comment]
Any code that relies on the output from the handlers should not break

**Comment by keenborder786** [comment]
Okay.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eyurtsev** [comment]
I'm looking through to figure out what can be affected. For example, one thing is BaseTracer which is used to power both astream_log and astream_events. If we change the output of the `on_tool_end`, we will fix the output from astream_events, but we also might cause an unexpected breaking change (e.g., if they're relying on those APIs and sending the content from the backend to the frontend the content will suddenly stop serializing).

it's a bit tricky in some of these cases to figure out whether to make a breaking change (and keep the code simple) or make a more involved change so that we don't break user code

**Comment by eyurtsev** [comment]
OK @keenborder786 I think we can proceed with the PR that you made! I'm going to outline a few places to propagate information to so that we break the minimum amount of code

**Comment by eyurtsev** [comment]
PR merged will be available in next release

**Comment by alex-dreo-persefoni** [comment]
@eyurtsev I don't see this issue (#18760) referenced in the latest release: https://github.com/langchain-ai/langchain/releases/tag/v0.1.12

When I test the original code that output a str(Document), I still see the same problematic output:
<img width="282" alt="Screenshot 2024-03-13 at 11 38 16" src="https://github.com/langchain-ai/langchain/assets/134342629/472cd81d-5ca5-434d-95ab-e97e7182f8e8">


Can you confirm that this issue was **_not_** fixed by the latest release?

**Comment by alex-dreo-persefoni** [comment]
It looks like [this PR](https://github.com/langchain-ai/langchain/pull/18932/files) might have to be merged before this issue can actually be corrected in a release. Is that correct?
