### ISSUE TITLE
Entity memory + ChatVectorDB ?

### ISSUE THREAD

**Issue by portkeys** [langchain-ai/langchain#1876]
Love Langchain library, so obsessed with it lately!

I've using ChatVectorDBChain which retrieves answers from Pinecone vectorstore and it's been working very well.

But one thing I noticed is that for normal `ConversationChain`, you can add `memory` argument, which provides nice user experience because it remembers the discussed entities. 

Question: can we add `memory` argument to `ChatVectorDBChain`? If it is already existed, could you point me whether below code is the right way to use it?

Thanks again so much!!😊

```
from langchain.chains import ChatVectorDBChain
from langchain.memory import ConversationEntityMemory

chat_with_sources = ChatVectorDBChain.from_llm(
    llm=llm,
    chain_type="stuff",
    vectorstore=vectorstore,
    return_source_documents=True
    #memory=ConversationEntityMemory(llm=llm, k=5)
)
```

**Comment by lorepieri8** [comment]
Related: https://github.com/hwchase17/langchain/issues/1448

**Comment by casualcomputer** [comment]
Same question. Thanks!

**Comment by phiweger** [comment]
Same.

**Comment by phiweger** [comment]
@portkeys seems doable using `llama_index` + tooling from `langchain`:

```python
memory = ConversationBufferMemory(memory_key="chat_history")
llm=OpenAI(temperature=0)
agent_chain = create_llama_chat_agent(
    toolkit,
    llm,
    memory=memory,
    verbose=True
)
```

source: https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb

**Comment by portkeys** [comment]
Thanks for sharing this solution! @phiweger
