### ISSUE TITLE
RecursiveCharacterTextSplitter  for Chinese sentence

### ISSUE THREAD

**Issue by changyunke** [langchain-ai/langchain#18770]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

for the example sentence "天青色等烟雨，而我在等你。哈哈哈....."
when I use RecursiveCharacterTextSplitter  split it by ["\n\n", "\n", "。"]，the result shows that the "。"will be appended in the beginning of the sub-sentence.for example:[Document(page_content="。哈哈哈...")]

### Description

for the example sentence "天青色等烟雨，而我在等你。哈哈哈....."
when I use RecursiveCharacterTextSplitter  split it by ["\n\n", "\n", "。"]，the result shows that the "。"will be appended in the beginning of the sub-sentence.for example:[Document(page_content="。哈哈哈...")]

### System Info

langchain 0.1.0

**Comment by ccurme** [comment]
Text splitters have a [keep_separator](https://api.python.langchain.com/en/latest/base/langchain_text_splitters.base.TextSplitter.html) kwarg. I was able to reproduce your issue, but if I set this kwarg it appears to be fixed:
```python
from langchain_text_splitters import RecursiveCharacterTextSplitter

input_string = "天青色等烟雨，而我在等你。哈哈哈....."

splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", "。"],
    chunk_size=20,
    chunk_overlap=0,
    keep_separator=False,
)
splitter.split_text(input_string)
```
```
['天青色等烟雨，而我在等你', '哈哈哈.....']
```
Please provide a minimal example reproducing the issue if this doesn't fix your problem.
