### ISSUE TITLE
OpenAIEmbeddings relies on hardcoded names 

### ISSUE THREAD

**Issue by surak** [langchain-ai/langchain#18800]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

When using langchain pointing to Mistral, for example, 
```
from langchain_openai import OpenAIEmbeddings
embedding = OpenAIEmbeddings(model="Mistral-7B-Instruct-v0.2")
```

one gets a `openai.InternalServerError: Internal Server Error`

But when using 
```
embedding = OpenAIEmbeddings(model="text-embedding-ada-002")
```

It works. The thing is that the server is using an alias to mistral called `text-embedding-ada-002`, so it's literally the same model as above, but there are assumptions on langchain's code about it.

### Description

The use of embeddings on my own inference server would fail if using names which are not the ones provided by openAi. But if one aliases the names : for example,  `text-embedding-ada-002` is just an alias to `Mistral-7B-Instruct-v0.2`, then it just works. 

So it seems that there are assumptions on langchain's code about hardcoded models' names.

### System Info

```
langchain==0.1.11
langchain-community==0.0.27
langchain-core==0.1.30
langchain-openai==0.0.8
langchain-text-splitters==0.0.1
```

Similar behavior on mac os and on linux
Python 3.8, 3.9 and 3.11.7

**Comment by rgupta2508** [comment]
I guess you can use HuggingFaceHubEmbeddings object
Something like this:-
```
 from langchain_community.embeddings import HuggingFaceHubEmbeddings
 embedding = HuggingFaceHubEmbeddings(model="http://host:port")
```
host and port where your "Mistral-7B-Instruct-v0.2" model is deployed.
