### ISSUE TITLE
Add in code documentation to core Runnable methods

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#18804]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Hi all!

Core Runnable methods are not documented well enough yet. It would be great to have each of the method include a self-contained usage example that folks can use as a reference. 

Documenting these methods well will have a fairly high value impact by making is easier for LangChain users to use core LangChain primitives.

Runnable (https://github.com/langchain-ai/langchain/blob/bc6249c889a4fe208f8f145e80258eb3de20d2d4/libs/core/langchain_core/runnables/base.py#L103-L103):

* assign
* with_fallbacks
* with_retry
* pick
* pipe
* map
* with_listeners

RunnableSerializable (https://github.com/langchain-ai/langchain/blob/bc6249c889a4fe208f8f145e80258eb3de20d2d4/libs/core/langchain_core/runnables/base.py#L1664-L1664):

* configurable_fields
* configurable_alternatives

## Acceptance criteria

- Documentation includes context
- Documentation includes a self contained example in python (including all imports).
- Example uses ..code-block: python syntax (see other places in the code as reference).

Please document only on method per PR to make it easy to review and get PRs merged quickly!

**Comment by liugddx** [comment]
@eyurtsev Hi ,assign to me, thanks~

**Comment by eyurtsev** [comment]
Claim a method :)

Ideally the or only documents one method -- it's much faster to review and merge

**Comment by liugddx** [comment]
`assign` method.

**Comment by liugddx** [comment]
`with_fallbacks` method.

**Comment by balachidam21** [comment]
`with_retry` method

**Comment by liugddx** [comment]
This issue has been completed, please close it cc @eyurtsev

**Comment by spike-spiegel-21** [comment]
Hi @eyurtsev is this issue still open? All the methods mentioned above have already been documented I guess. If there are some more, please mention them.
