### ISSUE TITLE
ChatVectorDBChain vs. agent + ConversationBufferMemory for chat

### ISSUE THREAD

**Issue by phiweger** [langchain-ai/langchain#1883]
Hi,

I am a bit confused as to what is the best approach to implement the "chatting with a document store". There seem to be two approaches to do this:

- ChatVectorDBChain -- https://github.com/mayooear/gpt4-pdf-chatbot-langchain
- agent + ConversationBufferMemory -- https://github.com/jerryjliu/llama_index/blob/main/examples/chatbot/Chatbot_SEC.ipynb

Is there an advantage to using ChatVectorDBChain?

Thank you very much!

**Comment by ankitbko** [comment]
Jumping on this and adding another question - 
- How do you use `ChatVectorDBChain` with an agent? If we create a function wrapper over ChatVectorDBChain and use it as tool, won't we loose the `source_document` that it returns?

**Comment by cver** [comment]
`ChatVectorDBChain` was deprecated as mentioned here https://github.com/hwchase17/langchain/blob/master/langchain/chains/conversational_retrieval/base.py#L192

**Comment by wangdong2023** [comment]
@cver where can I find the reasoning behind deprecating `ChatVectorDBChain`? `ChatVectorDBChain` appears in a lot of tutorials from hwchase17, and I think it's the first thing a lot of people is using because of that.

**Comment by cver** [comment]
> @cver where can I find the reasoning behind deprecating `ChatVectorDBChain`? `ChatVectorDBChain` appears in a lot of tutorials from hwchase17, and I think it's the first thing a lot of people is using because of that.

I have no idea but I think it's just a matter of naming
https://github.com/hwchase17/langchain/blob/v0.0.150/langchain/chains/conversational_retrieval/base.py#L211
just replace to `ConversationalRetrievalChain`, it would be fine
