### ISSUE TITLE
 validation error for ConversationalRetrievalChain retriever instance of BaseRetriever expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseRetriever)

### ISSUE THREAD

**Issue by yashwant43** [langchain-ai/langchain#18852]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

def get_vectorstore(text_chunks):
    embeddings = OpenAIEmbeddings()

    ## Vector Search DB In Pinecone
    Pinecone(api_key=os.environ.get('PINECONE_API_KEY'))

    index_name="langchainvector"

    vectorstore=PineconeVectorStore.from_documents(text_chunks,embeddings,index_name=index_name)

    #vectorstore = FAISS.from_texts(texts=text_chunks, embedding=embeddings)

    return vectorstore

def get_conversation_chain(vectorstore):

    llm = ChatOpenAI()
    # llm = HuggingFaceHub(repo_id="google/flan-t5-xxl", model_kwargs={"temperature":0.5, "max_length":512})

    memory = ConversationBufferMemory(
        memory_key='chat_history', return_messages=True)
    

    conversation_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=vectorstore.as_retriever(),
        memory=memory,

    )
    return conversation_chain
    
    
    
    
                # create conversation chain
                st.session_state.conversation = get_conversation_chain(
                    vectorstore)

if __name__ == '__main__':
    main()

    
    

### Description

  File "D:\LLM projects\ask-multiple-pdfs-main\ask-multiple-pdfs-main\app.py", line 128, in <module>
    main()
  File "D:\LLM projects\ask-multiple-pdfs-main\ask-multiple-pdfs-main\app.py", line 123, in main
    st.session_state.conversation = get_conversation_chain(
  File "D:\LLM projects\ask-multiple-pdfs-main\ask-multiple-pdfs-main\app.py", line 67, in get_conversation_chain
    conversation_chain = ConversationalRetrievalChain.from_llm(
  File "d:\llm projects\ask-multiple-pdfs-main\ask-multiple-pdfs-main\llm\lib\site-packages\langchain\chains\conversational_retrieval\base.py", line 212, in from_llm
    return cls(
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
retriever
  instance of BaseRetriever expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseRetriever)

### System Info

NA

**Comment by vaishali18lalit** [comment]
I am facing the same issue . Can you tell how to resolve this error ?
