### ISSUE TITLE
Support for Rotary Embeddings for Llama

### ISSUE THREAD

**Issue by bradleat** [langchain-ai/langchain#1885]
It looks like Llama uses an unsupported embedding scheme:

https://nn.labml.ai/transformers/rope/index.html

I'm opening this thread so we can have a conversation about how to support these embeddings within langchain. I'm happy to help, but my knowledge is limited.

**Comment by pachacamac** [comment]
I got the [recently merged embeddings pr](https://github.com/ggerganov/llama.cpp/pull/282) of llama working. Outputting a 5121 element long vector. What would be the best way to go about plugging this output to langchain? Take one of the existing embedding classes and base it of that or am I missing something?

**Comment by A-ML-ER** [comment]
How to convert Llama structure into Faster transformer sturcture ?
it seem has 32 layers with LlamaRotaryEmbedding ?
