### ISSUE TITLE
Support for Google BARD API?

### ISSUE THREAD

**Issue by ibehnam** [langchain-ai/langchain#1889]

**Comment by adumont** [comment]
Help needed for this?

**Comment by jsalsman** [comment]
https://github.com/acheong08/Bard is pretty easy, but obtaining the API key from cookies is an extra step which may be frowned upon in an official model integration, and Google is probably going to open their PaLM API today.

**Comment by jsalsman** [comment]
I'm considering writing this, because it would certainly be useful. It's free, faster than GPT-3.5 and 4, has no rate limits, has a large and apparently expanding (but undocumented) context window, always gives two alternate answers, and they're adding capabilities weekly. However, it's a little behind GPT-3.5 in question answering performance, as far as I can tell. 

However, before I start, I want to ask @hwchase17: would you accept a model integration which requires users to copy their API key out of their browser cookies?

**Comment by gudlyf** [comment]
https://github.com/dsdanielpark/Bard-API

**Comment by jsalsman** [comment]
> https://github.com/dsdanielpark/Bard-API

Still needs the ```__Secure-1PSID``` key from browser cookies. Everyone is waiting for the PaLM API to be generally available, which was promised more than a week ago.

**Comment by charanhu** [comment]
hey, langchain with Google Bard is it working for you?

**Comment by wuzimi** [comment]
Hi, any update? I am trying to combine bard api and langchain summarization-refine method, but didn't work.

**Comment by HAL9KKK** [comment]
why no update?, no possible to use Bard with Langchain?

**Comment by jsalsman** [comment]
I think Google prefers people use PaLM directly because Bard has several chatbot-only features. https://developers.generativeai.google/tutorials/text_quickstart

**Comment by kientv** [comment]
I think that bard is generate text better than palm in some languages not English

**Comment by andreprawira** [comment]
Any updates if langchain supports Bard? or Amazon Bedrock?

**Comment by naveenrk7** [comment]
Hey guys ! I have been working on a project which basically involves integrating Bard with langChain but I couldn't find a solution. It works fine with other HuggingFace models, but when i tried to integrate it with the langChain, it doesn't  works ? any Suggestions

**Comment by kientv** [comment]
> Hey guys ! I have been working on a project which basically involves integrating Bard with langChain but I couldn't find a solution. It works fine with other HuggingFace models, but when i tried to integrate it with the langChain, it doesn't works ? any Suggestions

I think that BARD don't have API yet, You can try PaLM 2 on makersuite.google.com

**Comment by NeevrajKB** [comment]
Yeah, mainly because bard is also free but chatgpt is not, any updates? I really want to use langchain.

**Comment by NeevrajKB** [comment]
Yeah, mainly because bard is also free but chatgpt is not, any updates? I really want to use langchain.

**Comment by PavanKalisetti** [comment]
is it still not working?
