### ISSUE TITLE
Could not find trained model [.elser_model_1] for ElasticsearchStore

### ISSUE THREAD

**Issue by liu-xiao-guo** [langchain-ai/langchain#18917]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
url = f"https://{ES_USER}:{ES_PASSWORD}@localhost:9200"
client = Elasticsearch(url, ca_certs = "./http_ca.crt", verify_certs = True)
print(client.info())

import elastic_transport
elastic_transport.debug_logging()

es = ElasticsearchStore.from_documents( 
                            docs,
                            strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(),
                            es_url = url, 
                            es_connection = client,
                            index_name = elastic_index_name, 
                            es_user = ES_USER,
                            es_password = ES_PASSWORD)
```

### Error Message and Stack Trace (if applicable)

Error adding texts: 116 document(s) failed to index.
First error reason: Could not find trained model [.elser_model_1]

### Description

The reason for this is because I deployed .elser_mode_2 on my Elasticsearch cluster. Later on, I used the following version of the code:

url = f"https://{ES_USER}:{ES_PASSWORD}@localhost:9200"
client = Elasticsearch(url, ca_certs = "./http_ca.crt", verify_certs = True)
print(client.info())

```
import elastic_transport
elastic_transport.debug_logging()

es = ElasticsearchStore.from_documents( 
                            docs,
                            strategy=ElasticsearchStore.SparseVectorRetrievalStrategy(model_id=".elser_model_2"),
                            es_url = url, 
                            es_connection = client,
                            index_name = elastic_index_name, 
                            es_user = ES_USER,
                            es_password = ES_PASSWORD)
```

This time, I set the model_id correctly to .elser_model_2. After I run the above code, I still got the same error message. It is still looking for .elser_model_1.

After consulting it with our colleague, and we found the root cause of the problem: In the first step, "elastic_index_name" index has already been created, and changing the model_id without deleting the created index in the first step won't work for the updated model_id.

The solution to this problem is:
1) delete the created index in the first step
2) run the code again with the updated model_id parameter.

Improvement:
This error correct cannot be easily resolved without looking into the code. Can we add some comments into the function? or can we recreate the pipeline when model_id is change?

Thanks

### System Info

$ pip freeze | grep langchain
langchain==0.1.11
langchain-community==0.0.27
langchain-core==0.1.30
langchain-text-splitters==0.0.1

**Comment by eyurtsev** [comment]
https://www.elastic.co/guide/en/machine-learning/current/ml-nlp-elser.html

Not super familiar with the code, so can't help in more detail, but read over the instructions above. You likely need to configure a model for elasticsearch

**Comment by eyurtsev** [comment]
(Likely not a langchain issue)
