### ISSUE TITLE
pip install -U langchain    is the best thing that you can do before you start your day 

### ISSUE THREAD

**Issue by geg00** [langchain-ai/langchain#1892]
This is the message

![image](https://user-images.githubusercontent.com/10646838/226973055-168f1120-93e2-4648-88a8-1c8a04f71796.png)

**Comment by carterrees-entrata** [comment]
This literally just fixed a "problem" for me. This is the way.

**Comment by yamyamyuo** [comment]
yeah, it changing too fast

**Comment by marianaferreiraQB** [comment]
This just fixed this error for me ((:
ModuleNotFoundError: No module named 'langchain.utils.openai_functions'

**Comment by bgdnvk** [comment]
this should be pinned

**Comment by vlasvlasvlas** [comment]
nice.

**Comment by ArthurBrioche** [comment]
Thank you - just fix a problem for me as well
