### ISSUE TITLE
Allow LLMs async streaming to fallback on sync streaming

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#18920]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

# Goal

When using `astream()`, LLMs should fallback to sync streaming if an async streaming implementation is not available.

# Context

Implementation of LLMs often include a sync implementation of streaming, but are missing an async implementation.

LLMs currently do not fallback on the sync streaming implementation.

For reference here's the [BaseLLM](https://github.com/langchain-ai/langchain/blob/43db4cd20e0e718f368267528706f92bf604bac9/libs/core/langchain_core/language_models/llms.py#L464-L464) implementation.

The current fallback sequence is:
1) If _astream is defined use it
2) if _astream is not defined fallback on ainvoke

The fallback sequence should be:
1) if _astream is defined use it
2) if _stream is defined fallback to it
3) Finally if neither _astream or _stream are defined, fallback to ainvoke

This PR shows how the same problem was fixed for chat models: https://github.com/langchain-ai/langchain/pull/18748

## Acceptance criteria

* Fallback sequence is correctly implemented
* Unit-tests confirm that the fallback sequence works correctly (see the PR for the unit-tests)

This PR will not be accepted without unit-tests since this is critical functionality!

**Comment by devkan** [comment]
Is closed? I've been diligently learning Langchain recently ..

**Comment by maximeperrindev** [comment]
> Is closed? I've been diligently learning Langchain recently ..

@devkan the PR is opened #18960 and waiting for a review. Feel free to check the code and tell me what you think

**Comment by devkan** [comment]
thank you.. I'm off to code right now.

**Comment by eyurtsev** [comment]
Changed are merged now with nice simplification done in:  https://github.com/langchain-ai/langchain/pull/19332
