### ISSUE TITLE
DOC: Typo error in "https://github.com/langchain-ai/langchain/blob/master/docs/docs/get_started/quickstart.mdx", line 289.

### ISSUE THREAD

**Issue by nithinv-27** [langchain-ai/langchain#18981]
### Checklist

- [x] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

There is a spelling mistake in line 289.

### Idea or request for content:

I can correct this error. Please assign this issue to me.

**Comment by baskargopinath** [comment]
can close this? @nithinv-27
