### ISSUE TITLE
UnstructuredFileLoader loads wrong "page number" metadata of word documents

### ISSUE THREAD

**Issue by ttais2017** [langchain-ai/langchain#19029]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.document_loaders import UnstructuredFileLoader
import json
import os

msFiles = ["BV24-006-0_BV_Laufbahnmodell.docx"]

for filename in msFiles:
  loader = UnstructuredFileLoader(filename, mode='elements')  # elements | single
  docs = loader.load() # Document
  
  # Convert each document to a dictionary
  data = [doc.dict() for doc in docs]
  print(f"document will be serialized with {len(data)} elements!")

  with open(f"{filename}.txt", 'w', encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False)

### Description

The page number of returned list of documents is wrong:

View of DOC File - page 55 of 70

![image](https://github.com/langchain-ai/langchain/assets/26426283/fd6b3d19-0d69-4fbb-a776-d4898197bcce)

View of parsed Document:  page 16

![image](https://github.com/langchain-ai/langchain/assets/26426283/29b43b6c-f7d8-43c9-9995-d3bd5d0e10ad)

### System Info

windows
python 11

**Comment by christellejulias** [comment]
I am reinsured: it's Langchain's bug rather than the code

**Comment by eyurtsev** [comment]
This is a question of semantics about what a page number means.

In most extraction applications, one keeps track of the index of the page (which is what the page number you're seeing likely corresponds to) and there's a separate metadata field for the page number as is visible on the page.

The former is needed by code (e.g., to be able to scroll to the correct page in the PDF), the latter is needed by humans.

**Comment by ttais2017** [comment]
semantics ?.  what a page number means ?.    The page number is clear in context of the ms word document. The Document has 70 pages and the user can navigate in Word by pages. If he goes to the page number 12, the editor show him the page number 12 and show also the number there. if the user navigates to the last page, word show  him the page number 70...and so on. If the user wants to reuse the page_number as source (I think it's the sense of that flag), then the page_number must be selecteed properly for all "loaded/parsed pages".

the UnstructuredFileLoader class selects properly the page_number metadata for the first 30 pages (which are equivalent to the ms word pages). After the number page 30 or 33 the page_number metadata will not be more incremented.  So my guest is that UnstructuredFileLoader has a bug by parsing the Word Document.

Best Regards,
