### ISSUE TITLE
DOC: RFE - Extend the discussion of Partial Prmpts with Pipeline example

### ISSUE THREAD

**Issue by rpgoldman** [langchain-ai/langchain#19033]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

In [the discussion of partial prompts](https://python.langchain.com/docs/modules/model_io/prompts/) the examples are all given in terms of `format`, and there is no discussion of partial prompts in the context of pipelines.

### Idea or request for content:

I can easily imagine a pipeline in which a prompt is first partialed, then filled, and then passed to an LLM.  But it's not at all clear how to do that, and this page only discusses `format`, not `invoke`.

It would be very helpful to add an example (or, if an example exists elsewhere, a link) that shows how to put partial filling of a prompt into a pipeline.  If this is not possible, then it would save programmers lots of time if the documentation would say so.

**Comment by keenborder786** [comment]
Do you mean something like this:

```python

from langchain.prompts import PromptTemplate
from langchain_core.runnables import RunnableLambda,RunnablePassthrough
prompt = PromptTemplate.from_template(
    template = "Langchain is really good. It have {number_of_user} users. It was released in year {year_released}")


partial_prompt = prompt.partial(year_released='2023')
chain = RunnableLambda(func = lambda x: {"number_of_user":x["number_of_user"]})\
        | partial_prompt
print(chain.invoke({"number_of_user":23}))

```

**Comment by rpgoldman** [comment]
That's helpful, but I was assuming that there might be an example where the `prompt.partial` is part of the chain.  Something like:

    (retriever2 | ( retriever1 | prompt ) | llm)

I'm not claiming that is right!  I don't believe that feeding the retriever to the prompt would yield a new prompt as with `prompt.partial()` 

But that's what I was looking for -- it seems like one should be able to partially instantiate a prompt with one retrieval, then finish instantiating with another, and then pump the result to the LLM.  Perhaps a document stuffer would be involved.

**Comment by rpgoldman** [comment]
Maybe

    partial_it = RunnableLambda(func = lambda x: prompt.partial(x))
    
and then

    retriever2 | ( retriever1 | partial_it) | llm

But I can't determine if those grouping parentheses will do what I expect or if there's some pass-through or something that I need to do.
