### ISSUE TITLE
ConstitutionalChain cannot be composed with SimpleSequentialChain

### ISSUE THREAD

**Issue by chutcheson** [langchain-ai/langchain#1904]
Code to create a ConstitutionalChain from an LLM:

```
 @classmethod
    def from_llm(
        cls,
        llm: BaseLanguageModel,
        chain: LLMChain,
        critique_prompt: BasePromptTemplate = CRITIQUE_PROMPT,
        revision_prompt: BasePromptTemplate = REVISION_PROMPT,
        **kwargs: Any,
    ) -> "ConstitutionalChain":
        """Create a chain from an LLM."""
        critique_chain = LLMChain(llm=llm, prompt=critique_prompt)
        revision_chain = LLMChain(llm=llm, prompt=revision_prompt)
        return cls(
            chain=chain,
            critique_chain=critique_chain,
            revision_chain=revision_chain,
            **kwargs,
        )
```

It requires an LLMChain.

SimpleSequentialChain doesn't inherit from LLMChain. It inherits from Chain.

```
class SimpleSequentialChain(Chain, BaseModel):
    """Simple chain where the outputs of one step feed directly into next."""

    chains: List[Chain]
    strip_outputs: bool = False
    input_key: str = "input"  #: :meta private:
    output_key: str = "output"  #: :meta private:

```

Therefore we cannot pass a SimpleSequentialChain to the ConstitutionalChain.

This disrupts the workflow where we create a pipeline and want to pass it to a constitutional chain for checks.

I would be happy to submit a PR to fix this : )

Presumably there should be no issue as a ConstitutionalChain shouldn't require anything more than a run method from the input chain, as it contains it's own LLM and prompts (in the form of principles).

**Comment by amanvirmundra** [comment]
Trying to do something similar, and hit a wall with chaining ConstitutionalChain with RetrievalQA chain.
```
chain = load_qa_with_sources_chain(OpenAI(temperature=0), chain_type="map_reduce", return_intermediate_steps=True)
constitutional_chain = ConstitutionalChain.from_llm(
    chain=chain,
    constitutional_principles=principles,
    llm=OpenAI(temperature=0),
    verbose=True,
)
overall_chain = SequentialChain(
    chains=[chain, constitutional_chain],
    -- params
    verbose=True)

```
Would be great if ConstitutionalChain can take in any chain derived from Chain class. Is there any workaround to add ConstitutionalChains to the pipeline. Would really appreciate the help.

**Comment by wnmurphy** [comment]
Similar issue, `ConstitutionalChain` only supports a single `LLMChain`, making it non-composable in other architectures.

Would be ideal to support something like:
* MultiPromptRouter
  * SequentialChain[LLMChain, ConstitutionalChain]
  * SequentialChain[LLMChain, ConstitutionalChain]
  * SequentialChain[LLMChain, ConstitutionalChain]

**Comment by vaidehiu** [comment]
need  this support on retrival qa
