### ISSUE TITLE
openai-python 1.13.4 with custom http_client breaks OpenAI clients in langchain

### ISSUE THREAD

**Issue by masquare** [langchain-ai/langchain#19116]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Minimum working example:
```python
from langchain_openai import AzureChatOpenAI
import httpx

http_client = httpx.Client()

model = AzureChatOpenAI(
    http_client=http_client,
    api_key="foo",
    api_version="2023-07-01-preview",
    azure_endpoint="https://example.com",
)

```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/home/ec2-user/environment/test/test-openai.py", line 7, in <module>
    model = AzureChatOpenAI(http_client=http_client, api_key="foo", api_version="2023-07-01-preview", azure_endpoint="https://example.com")
  File "/home/ec2-user/.local/share/virtualenvs/test/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/home/ec2-user/.local/share/virtualenvs/test/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for AzureChatOpenAI
__root__
  Invalid `http_client` argument; Expected an instance of `httpx.AsyncClient` but got <class 'httpx.Client'> (type=type_error)
```

### Description

Due to recent changes in openai-python the way langchain passes custom instances of `http_client` does not work anymore. The example code shows this behavior for `AzureChatOpenAI` but it holds for all instances where OpenAI clients are used. 

See [here](https://github.com/langchain-ai/langchain/blob/9e569d85a45fd9e89f85f5c93e61940e36176076/libs/partners/openai/langchain_openai/chat_models/azure.py#L190-L191) for one example of how the custom `http_client` gets passed to openai-python. LangChain would need to ensure to properly pass an instance of `httpx.AsyncClient` or `httpx.Client`.

The reason for the exception are some new type checks in openai-python v1.13.4 (see [here](https://github.com/openai/openai-python/compare/v1.13.3...v1.13.4#diff-aca4f4354075e3c75151a8de08daeb25d4db0af2564381c26aba33a49c9dc829R783-R1334)).

PS: As a temporary solution, I pinned openai-python to an older version. It is not pinned in langchain_openai (see [here](https://github.com/langchain-ai/langchain/blob/9e569d85a45fd9e89f85f5c93e61940e36176076/libs/partners/openai/pyproject.toml#L16)).

### System Info

```
System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Sat Feb 24 09:50:35 UTC 2024
> Python Version:  3.10.12 (main, Nov 10 2023, 12:43:56) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]

Package Information
-------------------
> langchain_core: 0.1.31
> langchain: 0.1.11
> langchain_community: 0.0.28
> langsmith: 0.1.25
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by liugddx** [comment]
This problem shouldn't exist anymore, you can try the latest version

**Comment by baskaryan** [comment]
believe it will still happen because of how we instantiate the AsyncAzureOpenAI client under the hood, will open a fix

**Comment by marufaytekin** [comment]
I updated to the latest versions but still having this issue when we invoke a chain.
fastapi==0.110.0
httpx==0.27.0
langchain==0.1.12
langchain_community==0.0.28
langchain_core==0.1.32
langchain_openai==0.0.8

**Comment by npuichigo** [comment]
Same issue here with latest versions.

**Comment by derino** [comment]
It seems that @baskaryan 's patch didn't end up in [pypi](https://pypi.org/project/langchain-openai/0.0.8/)  Maybe missing a version bump?

**Comment by jland-redhat** [comment]
This issue is also happening when we try to set up a VLLM OpenAI model

```
    self.model = VLLMOpenAI(
        openai_api_key="EMPTY",
        openai_api_base=config["vLLM_URL"],
        model_name=config["MODEL_NAME"],
        temperature=temperature,
        verbose=True,
        callbacks=[QueueCallback(q)],
        streaming=True,
        http_client=client
      )
```

```
langchain-weaviate==0.0.2
langchain-openai==0.1.7
langchain_community==0.2.0
langchain_core==0.2.0
langchain==0.2.0
```

Looks like the patch may have been azure specific?
