### ISSUE TITLE
PGVector distance_strategy methods seems to be not working

### ISSUE THREAD

**Issue by ankitagrawal648** [langchain-ai/langchain#19129]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

1. Fetched documents similar to my query using below code using 

> staff_knowledge_base.similarity_search(user_question, k=10)

```

staff_knowledge_base = PGVector(
                    embedding_function=embeddings,
                    connection_string=conn,
                    collection_name=collection)
```
**NOTE:** here default distance_strategy is used, i.e., COSINE (as per documentation) 

2. Fetched documents similar to my query using below code using 

> staff_knowledge_base.similarity_search(user_question, k=10)

```
from langchain_community.vectorstores.pgvector import DistanceStrategy
staff_knowledge_base = PGVector(
                    embedding_function=embeddings,
                    connection_string=conn,
                    collection_name=collection,
                    distance_strategy= DistanceStrategy.MAX_INNER_PRODUCT 
                   )
```

                    
                    

### Description

**Observation:** There is no change in list of fetched documents

**Expected Result:** Documents fetched should have been changed with change in distance_strategy

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22621
> Python Version:  3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.31
> langchain: 0.1.12
> langchain_community: 0.0.28
> langsmith: 0.1.25
> langchain_openai: 0.0.6
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by pranjaldoshi96** [comment]
Did you checked the embeddings generated for document and and tried to calculate their score. It may be that documents retrieved are same given document and query pair. 

It's good to add reference document and query, chunk size, embedding model you've used, splitting strategy tokenizer.
