### ISSUE TITLE
OpenAI Tokens and Cost are inaccurate

### ISSUE THREAD

**Issue by ArslanKAS** [langchain-ai/langchain#19120]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

        with get_openai_callback() as cb:
            output_parser = StrOutputParser()
            llm_chain = prompt_main | llm | output_parser

            all_text =  str(prompt) + str(topics)
            threshold = (llm.get_num_tokens(text=all_text) + tokens)

            chatgpt_output = llm_chain.invoke({"prompt": prompt, "topics": topics})
            chatgpt_output = chatgpt_output.replace("```", "").strip()                
            # Parse the string as a dictionary
            data_dict = parse_json_output(chatgpt_output)
            # Extract the categories list
            subcat_list = data_dict.get('Sub-Categories', [])
            total_cost = round(cb.total_cost, 5)
            total_tokens = cb.total_tokens
            
            print(f"Topics Tokens: {llm.get_num_tokens(text=''.join(topics))}") 
            print(f"Sub-Categories Tokens: {llm.get_num_tokens(text=''.join(subcat_list))}") 
            print(f"Estimated Total Tokens: {threshold}")
            print(f"Total Tokens: {cb.total_tokens}")
            print(f"Prompt Tokens: {cb.prompt_tokens}")
            print(f"Completion Tokens: {cb.completion_tokens}")
            print(f"Total Cost (USD): ${cb.total_cost}")

### Description

I've successfully calculated the Input Tokens as well as individual tokens for a list called Topics (contains 4000 topics).

According to the OpenAI Tokenizer Web Tool and my calculated tokens using llm.get_num_tokens the Tokens for the Topics should be at least ~8K meanwhile all the Total tokens (including Input and Output) should be around 13K but LangChain shows it simply as 815 Tokens.

Also the Cost should be different too but it shows Total Cost to be 0.00134 USD. I'm using gpt-3.5-turbo. Please look at the code and image attached and you'd understand something's wrong here.

![image](https://github.com/langchain-ai/langchain/assets/43797457/82d7c00d-dfee-4cc3-8456-ab6691373080)

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Tue Jan 30 20:59:52 UTC 2024
> Python Version:  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.1.32
> langchain: 0.1.12
> langchain_community: 0.0.28
> langsmith: 0.1.26
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by axiangcoding** [comment]
Same issue here.
