### ISSUE TITLE
React Agent stops at first observation

### ISSUE THREAD

**Issue by joao-ferreira-dc** [langchain-ai/langchain#19149]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
 tools = [CorrelationTool(), DataTool()]
llm = Llm().azure_openai
prompt = hub.pull("hwchase17/react")

agent = create_react_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True, handle_parsing_errors=True, max_iterations = 5, early_stopping_method="generate")
                               
with tracing_v2_enabled(project_name="default"):
    ans = agent_executor.invoke({"input": "Present me some conclusions on data of criminality"})
```
    

### Description

The following code only executes once, presenting me with the data from the first action but not going after it, not writing a final answer. I feel like it's missing some loop in langchain code.

### System Info

```
> Entering new AgentExecutor chain...
 I should use the Correlation Calculator to find some correlations
Action: Correlation Calculator
Action Input: "criminality in Brazil"
              Roubo     Furto  Homicídio
Roubo      1.000000  0.984111   0.936390
Furto      0.984111  1.000000   0.983135
Homicídio  0.936390  0.983135   1.000000

> Finished chain.
```

**Comment by joao-ferreira-dc** [comment]
@baskaryan

**Comment by tamago-digitech** [comment]
I encountered a similar issue. In my environment, it worked fine.

### before
@tool("mytool", args_schema=my_schema, **return_direct=True**)
def mytool...

### after
@tool("mytool", args_schema=my_schema)
def mytool...

**Comment by joao-ferreira-dc** [comment]
> I encountered a similar issue. It worked fine for my environment.
> 
> ### before
> @tool("mytool", args_schema=my_schema, **return_direct=True**) def mytool...
> 
> ### after
> @tool("mytool", args_schema=my_schema, **return_direct=False**) def mytool...

I love you, you the man

**Comment by joao-ferreira-dc** [comment]
> I encountered a similar issue. It worked fine for my environment.
> 
> ### before
> @tool("mytool", args_schema=my_schema, **return_direct=True**) def mytool...
> 
> ### after
> @tool("mytool", args_schema=my_schema, **return_direct=False**) def mytool...

I love you, YOU THE MAN!
