### ISSUE TITLE
astream_event produces redundant tokens and breaks graph streams

### ISSUE THREAD

**Issue by mingxuan-he** [langchain-ai/langchain#19211]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from typing import Annotated, List, Tuple, Union

from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_core.tools import tool
from langchain_experimental.tools import PythonREPLTool

tavily_tool = TavilySearchResults(max_results=5)

# This executes code locally, which can be unsafe
python_repl_tool = PythonREPLTool()

from langchain.agents import AgentExecutor, create_openai_tools_agent
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_openai import ChatOpenAI



def create_agent(
    llm: ChatOpenAI, tools: list, system_prompt: str
):
    # Each worker node will be given a name and some tools.
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                system_prompt,
            ),
            MessagesPlaceholder(variable_name="messages"),
            MessagesPlaceholder(variable_name="agent_scratchpad"),
        ]
    )
    agent = create_openai_tools_agent(llm, tools, prompt)
    executor = AgentExecutor(agent=agent, tools=tools)
    return executor

########
# Async agent nodes
########
async def agent_node(state, agent, name):
    result = await agent.ainvoke(state)
    return {"messages": [HumanMessage(content=result["output"], name=name)]}


from langchain.output_parsers.openai_functions import JsonOutputFunctionsParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

members = ["Researcher", "Coder"]
system_prompt = (
    "You are a supervisor tasked with managing a conversation between the"
    " following workers:  {members}. Given the following user request,"
    " respond with the worker to act next. Each worker will perform a"
    " task and respond with their results and status. When finished,"
    " respond with FINISH."
)
# Our team supervisor is an LLM node. It just picks the next agent to process
# and decides when the work is completed
options = ["FINISH"] + members
# Using openai function calling can make output parsing easier for us
function_def = {
    "name": "route",
    "description": "Select the next role.",
    "parameters": {
        "title": "routeSchema",
        "type": "object",
        "properties": {
            "next": {
                "title": "Next",
                "anyOf": [
                    {"enum": options},
                ],
            }
        },
        "required": ["next"],
    },
}
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="messages"),
        (
            "system",
            "Given the conversation above, who should act next?"
            " Or should we FINISH? Select one of: {options}",
        ),
    ]
).partial(options=str(options), members=", ".join(members))

llm = ChatOpenAI(model="gpt-3.5-turbo", streaming=True) # allow streaming

supervisor_chain = (
    prompt
    | llm.bind_functions(functions=[function_def], function_call="route")
    | JsonOutputFunctionsParser()
)

import operator
from typing import Annotated, Any, Dict, List, Optional, Sequence, TypedDict
import functools

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.graph import StateGraph, END


# The agent state is the input to each node in the graph
class AgentState(TypedDict):
    # The annotation tells the graph that new messages will always
    # be added to the current states
    messages: Annotated[Sequence[BaseMessage], operator.add]
    # The 'next' field indicates where to route to next
    next: str


research_agent = create_agent(llm, [tavily_tool], "You are a web researcher.")
research_node = functools.partial(agent_node, agent=research_agent, name="Researcher")

# NOTE: THIS PERFORMS ARBITRARY CODE EXECUTION. PROCEED WITH CAUTION
code_agent = create_agent(llm, [python_repl_tool], "You may generate safe python code to analyze data and generate charts using matplotlib.")
code_node = functools.partial(agent_node, agent=code_agent, name="Coder")

workflow = StateGraph(AgentState)
workflow.add_node("Researcher", research_node)
workflow.add_node("Coder", code_node)
workflow.add_node("supervisor", supervisor_chain)

for member in members:
    # We want our workers to ALWAYS "report back" to the supervisor when done
    workflow.add_edge(member, "supervisor")
# The supervisor populates the "next" field in the graph state
# which routes to a node or finishes
conditional_map = {k: k for k in members}
conditional_map["FINISH"] = END
workflow.add_conditional_edges("supervisor", lambda x: x["next"], conditional_map)
# Finally, add entrypoint
workflow.set_entry_point("supervisor")

graph = workflow.compile()

#######
# streaming events
#######
inputs = {'messages':[HumanMessage(content="write a research report on pikas.")]}
#inputs = {"messages": [HumanMessage(content="What is 1+1?")]}

async for event in graph.astream_events(inputs, version="v1"):
    kind = event["event"]
    if kind == "on_chat_model_stream":
        content = event["data"]["chunk"].content
        if content:
            # Empty content in the context of OpenAI means
            # that the model is asking for a tool to be invoked.
            # So we only print non-empty content
            print(content, end="|")
    elif kind == "on_tool_start":
        print("--")
        print(
            f"Starting tool: {event['name']} with inputs: {event['data'].get('input')}"
        )
    elif kind == "on_tool_end":
        print(f"Done tool: {event['name']}")
        print(f"Tool output was: {event['data'].get('output')}")
        print("--")
```

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[14], line 4
      1 inputs = {'messages':[HumanMessage(content="write a research report on pikas.")]}
      2 #inputs = {"messages": [HumanMessage(content="What is 1+1?")]}
----> 4 async for event in graph.astream_events(inputs, version="v1"):
      5     kind = event["event"]
      6     if kind == "on_chat_model_stream":

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:1063, in Runnable.astream_events(self, input, config, version, include_names, include_types, include_tags, exclude_names, exclude_types, exclude_tags, **kwargs)
   1059 root_name = config.get("run_name", self.get_name())
   1061 # Ignoring mypy complaint about too many different union combinations
   1062 # This arises because many of the argument types are unions
-> 1063 async for log in _astream_log_implementation(  # type: ignore[misc]
   1064     self,
   1065     input,
   1066     config=config,
   1067     stream=stream,
   1068     diff=True,
   1069     with_streamed_output_list=True,
   1070     **kwargs,
   1071 ):
   1072     run_log = run_log + log
   1074     if not encountered_start_event:
   1075         # Yield the start event for the root runnable.

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\tracers\log_stream.py:616, in _astream_log_implementation(runnable, input, config, stream, diff, with_streamed_output_list, **kwargs)
    613 finally:
    614     # Wait for the runnable to finish, if not cancelled (eg. by break)
    615     try:
--> 616         await task
    617     except asyncio.CancelledError:
    618         pass

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\tracers\log_stream.py:570, in _astream_log_implementation.<locals>.consume_astream()
    567 prev_final_output: Optional[Output] = None
    568 final_output: Optional[Output] = None
--> 570 async for chunk in runnable.astream(input, config, **kwargs):
    571     prev_final_output = final_output
    572     if final_output is None:

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\pregel\__init__.py:872, in Pregel.astream(self, input, config, output_keys, input_keys, interrupt_before_nodes, interrupt_after_nodes, debug, **kwargs)
    869 async def input_stream() -> AsyncIterator[Union[dict[str, Any], Any]]:
    870     yield input
--> 872 async for chunk in self.atransform(
    873     input_stream(),
    874     config,
    875     output_keys=output_keys,
    876     input_keys=input_keys,
    877     interrupt_before_nodes=interrupt_before_nodes,
    878     interrupt_after_nodes=interrupt_after_nodes,
    879     debug=debug,
    880     **kwargs,
    881 ):
    882     yield chunk

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\pregel\__init__.py:896, in Pregel.atransform(self, input, config, output_keys, input_keys, interrupt_before_nodes, interrupt_after_nodes, debug, **kwargs)
    884 async def atransform(
    885     self,
    886     input: AsyncIterator[Union[dict[str, Any], Any]],
   (...)
    894     **kwargs: Any,
    895 ) -> AsyncIterator[Union[dict[str, Any], Any]]:
--> 896     async for chunk in self._atransform_stream_with_config(
    897         input,
    898         self._atransform,
    899         config,
    900         output_keys=output_keys,
    901         input_keys=input_keys,
    902         interrupt_before_nodes=interrupt_before_nodes,
    903         interrupt_after_nodes=interrupt_after_nodes,
    904         debug=debug,
    905         **kwargs,
    906     ):
    907         yield chunk

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:1783, in Runnable._atransform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   1781 while True:
   1782     if accepts_context(asyncio.create_task):
-> 1783         chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
   1784             py_anext(iterator),  # type: ignore[arg-type]
   1785             context=context,
   1786         )
   1787     else:
   1788         chunk = cast(Output, await py_anext(iterator))

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\tracers\log_stream.py:237, in LogStreamCallbackHandler.tap_output_aiter(self, run_id, output)
    233 async def tap_output_aiter(
    234     self, run_id: UUID, output: AsyncIterator[T]
    235 ) -> AsyncIterator[T]:
    236     """Tap an output async iterator to stream its values to the log."""
--> 237     async for chunk in output:
    238         # root run is handled in .astream_log()
    239         if run_id != self.root_id:
    240             # if we can't find the run silently ignore
    241             # eg. because this run wasn't included in the log
    242             if key := self._key_map_by_run_id.get(run_id):

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\pregel\__init__.py:697, in Pregel._atransform(self, input, run_manager, config, **kwargs)
    690 done, inflight = await asyncio.wait(
    691     futures,
    692     return_when=asyncio.FIRST_EXCEPTION,
    693     timeout=self.step_timeout,
    694 )
    696 # panic on failure or timeout
--> 697 _panic_or_proceed(done, inflight, step)
    699 # apply writes to channels
    700 _apply_writes(
    701     checkpoint, channels, pending_writes, config, step + 1
    702 )

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\pregel\__init__.py:922, in _panic_or_proceed(done, inflight, step)
    920             inflight.pop().cancel()
    921         # raise the exception
--> 922         raise exc
    923         # TODO this is where retry of an entire step would happen
    925 if inflight:
    926     # if we got here means we timed out

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\pregel\__init__.py:1071, in _aconsume(iterator)
   1069 async def _aconsume(iterator: AsyncIterator[Any]) -> None:
   1070     """Consume an async iterator."""
-> 1071     async for _ in iterator:
   1072         pass

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:4435, in RunnableBindingBase.astream(self, input, config, **kwargs)
   4429 async def astream(
   4430     self,
   4431     input: Input,
   4432     config: Optional[RunnableConfig] = None,
   4433     **kwargs: Optional[Any],
   4434 ) -> AsyncIterator[Output]:
-> 4435     async for item in self.bound.astream(
   4436         input,
   4437         self._merge_configs(config),
   4438         **{**self.kwargs, **kwargs},
   4439     ):
   4440         yield item

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:3920, in RunnableLambda.astream(self, input, config, **kwargs)
   3917 async def input_aiter() -> AsyncIterator[Input]:
   3918     yield input
-> 3920 async for chunk in self.atransform(input_aiter(), config, **kwargs):
   3921     yield chunk

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:3903, in RunnableLambda.atransform(self, input, config, **kwargs)
   3897 async def atransform(
   3898     self,
   3899     input: AsyncIterator[Input],
   3900     config: Optional[RunnableConfig] = None,
   3901     **kwargs: Optional[Any],
   3902 ) -> AsyncIterator[Output]:
-> 3903     async for output in self._atransform_stream_with_config(
   3904         input,
   3905         self._atransform,
   3906         self._config(config, self.afunc if hasattr(self, "afunc") else self.func),
   3907         **kwargs,
   3908     ):
   3909         yield output

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:1783, in Runnable._atransform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   1781 while True:
   1782     if accepts_context(asyncio.create_task):
-> 1783         chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
   1784             py_anext(iterator),  # type: ignore[arg-type]
   1785             context=context,
   1786         )
   1787     else:
   1788         chunk = cast(Output, await py_anext(iterator))

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\tracers\log_stream.py:237, in LogStreamCallbackHandler.tap_output_aiter(self, run_id, output)
    233 async def tap_output_aiter(
    234     self, run_id: UUID, output: AsyncIterator[T]
    235 ) -> AsyncIterator[T]:
    236     """Tap an output async iterator to stream its values to the log."""
--> 237     async for chunk in output:
    238         # root run is handled in .astream_log()
    239         if run_id != self.root_id:
    240             # if we can't find the run silently ignore
    241             # eg. because this run wasn't included in the log
    242             if key := self._key_map_by_run_id.get(run_id):

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:3872, in RunnableLambda._atransform(self, input, run_manager, config, **kwargs)
   3870                 output = chunk
   3871 else:
-> 3872     output = await acall_func_with_variable_args(
   3873         cast(Callable, afunc), cast(Input, final), config, run_manager, **kwargs
   3874     )
   3876 # If the output is a runnable, use its astream output
   3877 if isinstance(output, Runnable):

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:3847, in RunnableLambda._atransform.<locals>.f(*args, **kwargs)
   3845 @wraps(func)
   3846 async def f(*args, **kwargs):  # type: ignore[no-untyped-def]
-> 3847     return await run_in_executor(config, func, *args, **kwargs)

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\config.py:493, in run_in_executor(executor_or_config, func, *args, **kwargs)
    480 """Run a function in an executor.
    481 
    482 Args:
   (...)
    489     Output: The output of the function.
    490 """
    491 if executor_or_config is None or isinstance(executor_or_config, dict):
    492     # Use default executor with context copied from current context
--> 493     return await asyncio.get_running_loop().run_in_executor(
    494         None,
    495         cast(Callable[..., T], partial(copy_context().run, func, *args, **kwargs)),
    496     )
    498 return await asyncio.get_running_loop().run_in_executor(
    499     executor_or_config, partial(func, **kwargs), *args
    500 )

File c:\ProgramData\Anaconda3\envs\llm\Lib\concurrent\futures\thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\base.py:3841, in RunnableLambda._atransform.<locals>.func(input, run_manager, config, **kwargs)
   3835 def func(
   3836     input: Input,
   3837     run_manager: AsyncCallbackManagerForChainRun,
   3838     config: RunnableConfig,
   3839     **kwargs: Any,
   3840 ) -> Output:
-> 3841     return call_func_with_variable_args(
   3842         self.func, input, config, run_manager.get_sync(), **kwargs
   3843     )

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langchain_core\runnables\config.py:326, in call_func_with_variable_args(func, input, config, run_manager, **kwargs)
    324 if run_manager is not None and accepts_run_manager(func):
    325     kwargs["run_manager"] = run_manager
--> 326 return func(input, **kwargs)

File c:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\langgraph\graph\graph.py:37, in Branch.runnable(self, input)
     35 result = self.condition(input)
     36 if self.ends:
---> 37     destination = self.ends[result]
     38 else:
     39     destination = result

KeyError: 'ResearchResearcher'

### Description

This is a follow up to the recent updates to astream_events in #18743 and #19051. The discussion originally started in [langchain-ai/langgraph#136](https://github.com/langchain-ai/langgraph/issues/136).

I'm testing `astream_event` method on [this langgraph example notebook](https://github.com/langchain-ai/langgraph/blob/main/examples/multi_agent/agent_supervisor.ipynb). I modified several lines of code to allow LLM streaming and convert the nodes to async functions. Without `astream_events`, the supervisor node will output "next: Researcher", however it returns "next: ResearchResearcher", which breaks graph streaming since the name is not recognized as a graph node. Another example is "next: FINFINISH". The only scenario it's working is when router outputs "next: Coder" (one token). 

My suspicion is the recently updated AddableDict logic in stream_events has a problem with `JSONOutputFunctionParser` in the supervisor chain. Any help from @eyurtsev or other team members would be greatly appreciated!

Here's the full Langsmith Trace: https://smith.langchain.com/public/e09b671b-325d-477e-bd29-e017d30c6741/r

### System Info

langchain=0.1.12
langchain-core=0.1.33rc1
langgraph=0.0.28

**Comment by mingxuan-he** [comment]
I put together a fix using the new `with_structured_outputs` method with a custom pydantic class. In the docs and examples, I'd recommend swapping out the openai functions defined by json since they are deprecating.

```
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.pydantic_v1 import BaseModel, Field
from typing import Literal

members = ["Researcher", "Coder"]
system_prompt = (
    "You are a supervisor tasked with managing a conversation between the"
    " following workers:  {members}. Given the following user request,"
    " respond with the worker to act next. Each worker will perform a"
    " task and respond with their results and status. When finished,"
    " respond with FINISH."
)
# Our team supervisor is an LLM node. It just picks the next agent to process
# and decides when the work is completed
options = ["FINISH"] + members

class NextAgent(BaseModel):
    next: Literal["FINISH", "Researcher", "Coder"]

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        MessagesPlaceholder(variable_name="messages"),
        (
            "system",
            "Given the conversation above, who should act next?"
            " Or should we FINISH? Select one of: {options}",
        ),
    ]
).partial(options=str(options), members=", ".join(members))

llm = ChatOpenAI(model="gpt-3.5-turbo", streaming=True)

supervisor_chain = (
    prompt
    | llm.with_structured_output(NextAgent)
    | lambda x: x.dict() # convert pydantic to dict for graph update
)
```

Caveat is that at the end I had to convert from pydantic back to dict (because graph state is a typeddict). Not sure if there's a convenient solution.

**Comment by MoMoWongHK** [comment]
> I put together a fix using the new `with_structured_outputs` method with a custom pydantic class. In the docs and examples, I'd recommend swapping out the openai functions defined by json since they are deprecating.
> 
> ```
> from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
> from langchain_core.pydantic_v1 import BaseModel, Field
> from typing import Literal
> 
> members = ["Researcher", "Coder"]
> system_prompt = (
>     "You are a supervisor tasked with managing a conversation between the"
>     " following workers:  {members}. Given the following user request,"
>     " respond with the worker to act next. Each worker will perform a"
>     " task and respond with their results and status. When finished,"
>     " respond with FINISH."
> )
> # Our team supervisor is an LLM node. It just picks the next agent to process
> # and decides when the work is completed
> options = ["FINISH"] + members
> 
> class NextAgent(BaseModel):
>     next: Literal["FINISH", "Researcher", "Coder"]
> 
> prompt = ChatPromptTemplate.from_messages(
>     [
>         ("system", system_prompt),
>         MessagesPlaceholder(variable_name="messages"),
>         (
>             "system",
>             "Given the conversation above, who should act next?"
>             " Or should we FINISH? Select one of: {options}",
>         ),
>     ]
> ).partial(options=str(options), members=", ".join(members))
> 
> llm = ChatOpenAI(model="gpt-3.5-turbo", streaming=True)
> 
> supervisor_chain = (
>     prompt
>     | llm.with_structured_output(NextAgent)
>     | lambda x: x.dict() # convert pydantic to dict for graph update
> )
> ```
> 
> Caveat is that at the end I had to convert from pydantic back to dict (because graph state is a typeddict). Not sure if there's a convenient solution.

I got `Unexpected expression syntax` for `| lambda x: x.dict()`

**Comment by usersina** [comment]
@MoMoWongHK missing parantheses in `(lambda x: x.dict())` if I see correctly.
