### ISSUE TITLE
Not able to utilize flashrank reranker in langchain and getting error "HTTPError('403 Client Error: Forbidden for url: https://storage.googleapis.com/flash-rank/ms-marco-MultiBERT-L-12.zip')" 

### ISSUE THREAD

**Issue by chowdary1209** [langchain-ai/langchain#19241]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Bellow is the code where i am getting  "HTTPError('403 Client Error: Forbidden for url: https://storage.googleapis.com/flash-rank/ms-marco-MultiBERT-L-12.zip')" 

        compressor = FlashrankRerank()
        compressor_retriever = ContextualCompressionRetriever(base_compressor=compressor,
                                                              base_retriever= base_retriever
                                                              )
        compressed_docs = compressor_retriever.get_relevant_documents(query)
        return compressed_docs

### Error Message and Stack Trace (if applicable)

Tool run errored with error:
HTTPError('403 Client Error: Forbidden for url: https://storage.googleapis.com/flash-rank/ms-marco-MultiBERT-L-12.zip')Traceback (most recent call last):

### Description

1. I  have developed an LLM app with chromadb and its working
2. I am integrating FlashRank Retriever using langchain, but i am getting the error

### System Info

python==3.10.4
langchain==0.1.9
FlashRank==0.1.69

**Comment by ankurkumarz** [comment]
It seems the problem is not in LangChain - the underlying flashrank library uses Models from Google Stroage bucket (https://storage.googleapis.com/flashrank/ms-marco-MultiBERT-L-12.zip) and the public access has been disabled for these models.
Hence flashrank need to fix their code. For now, you can download these models and store in /tmp folder
