### ISSUE TITLE
SQL_database Trino dialect - wrong usage of USE to set catalog, as Trino does not use parameters for identifiers

### ISSUE THREAD

**Issue by Je-Cp** [langchain-ai/langchain#19261]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Impacted code is https://github.com/langchain-ai/langchain/blob/514fe807784f520449914a64ffc983538fa6743d/libs/community/langchain_community/utilities/sql_database.py#L426

```
 elif self.dialect == "trino":
                    connection.exec_driver_sql(
                        "USE ?",
                        (self._schema,),
                        execution_options=execution_options,
```

Trino cannot use parameterized syntax for USE

Generated SQL statement to Trino should be
`EXECUTE IMMEDIATE 'USE mycatalog';`
instead of 
`EXECUTE IMMEDIATE 'USE ?' USING 'mycatalog';`

### Error Message and Stack Trace (if applicable)

On Trino side, we got
```
io.trino.sql.parser.ParsingException: line 1:24: mismatched input '?'. Expecting: <identifier>
	at io.trino.sql.parser.SqlParser.lambda$invokeParser$1(SqlParser.java:183)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
```

### Description

Without patching Trino dialect for SQL prompts, Trino cannot be used as a SQL source for LangChain

### System Info

langchain==0.1.12
langchain-community==0.0.28
langchain-core==0.1.31
langchain-experimental==0.0.54
langchain-openai==0.0.8
langchain-text-splitters==0.0.1

**Comment by Je-Cp** [comment]
Proposed patch 
```
elif self.dialect == "trino":
                    connection.exec_driver_sql(
                        f"USE {self._schema}",
                        execution_options=execution_options,
                    )
```

**Comment by tzach-upstream** [comment]
Hi, is this issue resolved?
