### ISSUE TITLE
langchain-core: Allow passing local cache to language models

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#19276]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

# Goal

Allow instantiating language models with specific caches provided as an init parameter. This will bring language models on feature parity with chat models w/ respect to caching behavior.

This is the `cache` parameter: https://github.com/langchain-ai/langchain/blob/50f93d86ec56a92e1d0f5b390514d9a67a95d083/libs/core/langchain_core/language_models/base.py#L82-L82

Implementation is required in BaseLLM for both sync and async paths: https://github.com/langchain-ai/langchain/blob/50f93d86ec56a92e1d0f5b390514d9a67a95d083/libs/core/langchain_core/language_models/llms.py#L737-L737

Here's a reference implementation for chat models: https://github.com/langchain-ai/langchain/pull/17386

## Acceptance criteria

* The PR must include unit tests that provide coverage of the various caching configurations. You can look at the reference PR for Chat Models which covers the relevant scenarios.

**Comment by liugddx** [comment]
i want try.

**Comment by liugddx** [comment]
Is this test case runnable? If it works fine, what exactly is this issue?
https://github.com/langchain-ai/langchain/blob/40f846e65da37a1c00d72da9ea64ebb0f295b016/libs/core/tests/unit_tests/language_models/chat_models/test_cache.py#L43

**Comment by ccurme** [comment]
> Is this test case runnable? If it works fine, what exactly is this issue?
> 
> https://github.com/langchain-ai/langchain/blob/40f846e65da37a1c00d72da9ea64ebb0f295b016/libs/core/tests/unit_tests/language_models/chat_models/test_cache.py#L43

As I understand this test is testing a chat model, and the intent of the issue is to extend the capability to LLMs. There is an analogous [FakeListLLM](https://github.com/langchain-ai/langchain/blob/8609afbd100a055e32b3b5ff7e3ad8788e64e64d/libs/core/langchain_core/language_models/fake.py#L14) class that could be useful for the test here.
