### ISSUE TITLE
Improvement: MapReduce summarization chains executes a map step on a single document

### ISSUE THREAD

**Issue by TomTom101** [langchain-ai/langchain#1937]
When feeding the map_reduce summarization chain with a single document, the doc is run through an unnecessary map step before running a combine prompt on it. 
The combine prompt would imo be sufficient to avoid summarizing a single summary which then is very lossy. Great project, hope this thrives!

**Comment by ShantanuNair** [comment]
@TomTom101 when you say single document, do you mean that the entire document fits in the context? Because it could be a long document and need that map step, even though it's a single document. Correct me if I misinterpreted what you're saying.

**Comment by TomTom101** [comment]
Closed as I can no more observe that behavior. There was no chain in LC, so must have been my fault.

**Comment by TomTom101** [comment]
I already did patch langchain, that's why this problem was gone ;) Will provide a PR soon

**Comment by TomTom101** [comment]
This behavior is actually totally legit, map reduce is just not a good choice if one has a single document.
