### ISSUE TITLE
RunnableParallel does not correctly pass through **kwargs to child Runnables

### ISSUE THREAD

**Issue by npuichigo** [langchain-ai/langchain#19386]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

call `ainvoke` with `**kwargs` has no effect

### Description

https://github.com/langchain-ai/langchain/blob/b20c2640dac79551685b8aba095ebc6125df928c/libs/core/langchain_core/runnables/base.py#L2984-2995

```
results = await asyncio.gather(
                *(
                    step.ainvoke(
                        input,
                        # mark each step as a child run
                        patch_config(
                            config, callbacks=run_manager.get_child(f"map:key:{key}")
                        ),
                    )
                    for key, step in steps.items()
                )
            )
```
does not correctly pass through `**kwargs` to child `Runnable`s

### System Info

langchian 0.1.13

**Comment by aditya02acharya** [comment]
Is there any fix for this issues?
