### ISSUE TITLE
ChatGPT Plugins vs. LangChain agent

### ISSUE THREAD

**Issue by marialovesbeans** [langchain-ai/langchain#1940]
I'm wondering how does [ChatGPT plugin](https://platform.openai.com/docs/plugins/) work under-the-hood? Are they using the same techique as Langchain agent? Basically sending prompt and manually parse out the result -> and feed result back to another plugin in subsequential steps if necessary. 

Or is it using a superior technique than LangChain agent? I can't find a mention of LangChain in their doc.

Any thoughts are welcome!

**Comment by Ynng** [comment]
In comparing ChatGPT plugins to Langchain, it appears that ChatGPT's support for third-party plugins is relatively limited.

Developers using ChatGPT are restricted to defining specific actions or HTTP endpoints for the language model to call. This makes it challenging, if not impossible, for third-party developers to create tools that needs a LLM, such as Palmath. (Although ChatGPT does offer an official equivalent called "Code Interpreter")

**Comment by diemus** [comment]
It seems that Langchain has a competitor now.

**Comment by zachschillaci27** [comment]
![Screenshot 2023-03-24 at 10 50 38](https://user-images.githubusercontent.com/40636930/227487257-7a4e9d1c-b4fe-4355-b1d4-89a6ab02cbc0.png)

It looks similar at least in how the plugins (i.e. Langchain tools) are described to the model, which allows ChatGPT to choose which tool to use for a particular problem. I'm not sure if there's a possibility of chaining together multiple tools in a single agent call, but I assume it would have this capability

**Comment by kennethleungty** [comment]
![image](https://user-images.githubusercontent.com/16691614/227492531-7c159dbe-fbba-488f-a867-e31b2dd77236.png)

From the above video on their blog post (https://openai.com/blog/chatgpt-plugins), it seems like the multiple tools were called upon based on a single agent call. This is a demo, so I am sure they are displaying their smoothest/most accurate example. Based on that demo alone, it does seem very impressive compared to Langchain agent.

Anyone with insights on what they do different compared to Langchain's agents?

**Comment by zachschillaci27** [comment]
> ![image](https://user-images.githubusercontent.com/16691614/227492531-7c159dbe-fbba-488f-a867-e31b2dd77236.png)
> 
> From the above video on their blog post (https://openai.com/blog/chatgpt-plugins), it seems like the multiple tools were called upon based on a single agent call. This is a demo, so I am sure they are displaying their smoothest/most accurate example. Based on that demo alone, it does seem very impressive compared to Langchain agent.
> 
> Anyone with insights on what their agent does differently compared to Langchain's agents?

As of now, perhaps they're doing some zero-shot type decision capability using a ReACT/MRKL framework. But given they also cite the toolformer paper, I wouldn't be surprised if they fine-tune later versions of GPT-4 to use some of the more tightly integrated tools (e.g. Wolfram Alpha)

**Comment by ericwangqing** [comment]
Actually, IMO, the most interesting things here are 

1.  how ChatGPT figure out the steps and the order of execution these plugins, 
2.  and how ChatGPT pass the result of a plugin to the next , is there anything like the output parser of LangChain implicitly working behind the scene?

> ![image](https://user-images.githubusercontent.com/16691614/227492531-7c159dbe-fbba-488f-a867-e31b2dd77236.png)

**Comment by ericwangqing** [comment]
> The order is determined in the fly just like langchain agent does

@tonyabracadabra does that mean for users enable some plugins, before really answer a message user sent, OpenAI inserts a planning conversation to LLM?

**Comment by ericwangqing** [comment]
>  That’s one possible way (unarguably the simplest way) but I do believe OpenAI may come up with something beyond that to achieve better performance and lower cost.        

according to the official doc of OpenAI, I guess currently they are doing the simplest way, and may collecting training data for the next stage to cut down cost.              
![image](https://user-images.githubusercontent.com/364773/227762892-51321c99-5713-437f-8309-e0b4d31c81b4.png)      
       
![image](https://user-images.githubusercontent.com/364773/227763055-58b60f39-e8bd-4024-96e5-002d94efb931.png)

**Comment by biedanian** [comment]
From my understanding, langchain allows LLM to use tools through pre-set prompt templates. I don’t know if the chatgpt plug-in is also done in the same way.
Hypothetically, what is the difference between the plugin model and langchain? Has openai done training for the plugin to make its own method work better?

**Comment by ericwangqing** [comment]
Technically speaking, they are the same. However, commercially speaking, LangChain allows us to choose LLM and master business logic while OpenAI controls everything without choice.

**Comment by dosatos** [comment]
How does it differ from token usage point of view? Do I understand right that the OpenAI Plugins provide the context related token usage for free?

**Comment by stephenasuncionDEV** [comment]
Can someone explain how OpenAI manages to wait for the API request result before generating the final answer? Are they separate calls?

**Comment by yeagob** [comment]
But there is a way to use gpt plugins from an api call?
