### ISSUE TITLE
Issue when trying to install chatgpt-wrapper with this module.

### ISSUE THREAD

**Issue by Yoity3625** [langchain-ai/langchain#1941]
When presented with intalling chatgpt-wrapper, I have the issue "C:\Users\BigB\Documents\Yeet>pip install git+https://github.com/mmabrouk/chatgpt-wrapper
Collecting git+https://github.com/mmabrouk/chatgpt-wrapper
  Cloning https://github.com/mmabrouk/chatgpt-wrapper to c:\users\refddfea~1\appdata\local\temp\pip-req-build-h89ta3sh
  Running command git clone --filter=blob:none -q https://github.com/mmabrouk/chatgpt-wrapper 'C:\Users\RCfDfEA~1\AppData\Local\Temp\pip-req-build-h89ta3sh'
  Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit df1725d7fbbff27e36bc22e4eb73cf5fea887dc1
  Preparing metadata (setup.py) ... done
Requirement already satisfied: email-validator in c:\users\redfdeaffdspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (1.3.1)
Requirement already satisfied: Flask in c:\users\refdfdeafdspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (2.0.3)
Requirement already satisfied: Jinja2 in c:\users\reddefadspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (3.0.3)
ERROR: Could not find a version that satisfies the requirement langchain>=0.0.115 (from chatgpt) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27)
ERROR: No matching distribution found for langchain>=0.0.115".

**Comment by Cabuxos** [comment]
> When presented with intalling chatgpt-wrapper, I have the issue "C:\Users\BigB\Documents\Yeet>pip install git+https://github.com/mmabrouk/chatgpt-wrapper Collecting git+https://github.com/mmabrouk/chatgpt-wrapper Cloning https://github.com/mmabrouk/chatgpt-wrapper to c:\users\refddfea~1\appdata\local\temp\pip-req-build-h89ta3sh Running command git clone --filter=blob:none -q https://github.com/mmabrouk/chatgpt-wrapper 'C:\Users\RCfDfEA~1\AppData\Local\Temp\pip-req-build-h89ta3sh' Resolved https://github.com/mmabrouk/chatgpt-wrapper to commit df1725d7fbbff27e36bc22e4eb73cf5fea887dc1 Preparing metadata (setup.py) ... done Requirement already satisfied: email-validator in c:\users\redfdeaffdspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (1.3.1) Requirement already satisfied: Flask in c:\users\refdfdeafdspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (2.0.3) Requirement already satisfied: Jinja2 in c:\users\reddefadspc\appdata\local\programs\python\python36\lib\site-packages (from chatGPT==0.6.5) (3.0.3) ERROR: Could not find a version that satisfies the requirement langchain>=0.0.115 (from chatgpt) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27) ERROR: No matching distribution found for langchain>=0.0.115".

You are probably using Python 3.8. It works with 3.8.1 or 3.11
