### ISSUE TITLE
DOC: <Add PDF versions of the API documentation back 'DOC: ' prefix>

### ISSUE THREAD

**Issue by adelshaaban** [langchain-ai/langchain#19484]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

No download option available at https://readthedocs.org/projects/langchain/downloads/

### Idea or request for content:

Add download to the API documentation from readthedocs. It existed in the past but it no longer exists

**Comment by sepiatone** [comment]
@TCDAdel I think the devs are working on it, see this [discussion](https://github.com/langchain-ai/langchain/discussions/9097)

**Comment by TCDAdel** [comment]
Thanks @sepiatone, yeah #16550 sadly didn't fix it when it got merged afaik. Tried to fork the docs myself to fix the .yml but the docs are configured in a really weird way
