### ISSUE TITLE
DOC: How to use summarize chain and LangChain Expression Language together

### ISSUE THREAD

**Issue by Lufffya** [langchain-ai/langchain#19501]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

![image](https://github.com/langchain-ai/langchain/assets/49063302/72c1301c-479c-4db5-bbd8-fdbc13583197)
![image](https://github.com/langchain-ai/langchain/assets/49063302/9bd87a6b-2ede-4ece-8fa5-17164493f2d3)

Which Parser should I use, is there any documentation?

**Comment by sepiatone** [comment]
@Lufffya 

Looking at the example for chain_type="stuff" in the [documentation](https://python.langchain.com/docs/use_cases/summarization), we can rewrite it for LCEL very simply:

```
from langchain_community.document_loaders.web_base import WebBaseLoader
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
docs = loader.load()

llm = ChatOpenAI(temperature=0, model_name="gpt-3.5-turbo-1106")

prompt = PromptTemplate.from_template("Write a concise summary of the following: {text}")

# chain = load_summarize_chain(llm, chain_type="stuff")
chain = prompt | llm | StrOutputParser()

print(chain.invoke({"text": docs}))
```
