### ISSUE TITLE
APIChain InvalidSchema: No connection adapters were found

### ISSUE THREAD

**Issue by duotangx** [langchain-ai/langchain#19512]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

pip install langchain langchain-anthropic

api_docs = """
Using the API
- apiUrl=https://discountingcashflows.com
- No API key is required.
- To fetch annual income statements, use get_income_statement() at /api/income-statement/AAPL/.
- For quarterly income statements, get_income_statement_quarterly() is available at /api/income-statement/quarterly/AAPL/.
- Use get_income_statement_ltm() for income statements over the last twelve months (LTM) at /api/income-statement/ltm/AAPL/.
- Annual balance sheet statements can be retrieved with get_balance_sheet_statement() via /api/balance-sheet-statement/AAPL/.
- For quarterly balance sheet data, there's get_balance_sheet_statement_quarterly() at /api/balance-sheet-statement/quarterly/AAPL/.
- Annual cash flow statements are accessible through get_cash_flow_statement() at /api/cash-flow-statement/AAPL/.
- get_cash_flow_statement_quarterly() at /api/cash-flow-statement/quarterly/AAPL/ fetches quarterly cash flow statements.
- LTM cash flow data is obtainable with get_cash_flow_statement_ltm() at /api/cash-flow-statement/ltm/AAPL/.
- Stock market quotes can be accessed using get_quote() at /api/quote/AAPL/.
- Company profiles are available via get_profile() at /api/profile/AAPL/.
- For the latest treasury rates, use get_treasury() at /api/treasury/.
- Daily treasury rates (full history) can be fetched with get_treasury_daily() at /api/treasury/daily/.
- get_treasury_monthly() at /api/treasury/monthly/ provides monthly treasury rates (full history).
- Annual treasury rates (full history) are accessible through get_treasury_annual() at /api/treasury/annual/.
- Annual financial ratios can be retrieved using get_ratios() at /api/ratios/AAPL/.
- For quarterly financial ratios, there's get_ratios_quarterly() at /api/ratios/quarterly/AAPL/.
- LTM financial ratios are available with get_ratios_ltm() at /api/ratios/ltm/AAPL/.
- To access annually adjusted dividends, use get_dividends_annual() at /api/dividends/AAPL/.
- Quarterly adjusted dividends can be fetched with get_dividends_quarterly() at /api/dividends/quarterly/AAPL/.
- Dividends as reported are available through get_dividends_reported() at /api/dividends/reported/AAPL/.
- For a full history of daily market prices, use get_prices_daily() at /api/prices/daily/AAPL/.
- Annual market share prices (full history) are accessible via get_prices_annual() at /api/prices/annual/AAPL/.
- Annual CPI data can be retrieved using get_cpi_annual() at /api/economic/annual/CPI/.
- FX market prices for all currencies are available through get_fx() at /api/fx/.
- Equity risk premium for all countries can be accessed with get_risk_premium() at /api/risk-premium/.

Other Available API Endpoints
Certain API endpoints without a specific "get" function are also accessible:

- Revenue Breakdown (requires subscription) through /api/revenue-analysis/<ticker>/<type>/<period>/ with ticker options like AAPL, MSFT, etc., type as geographic or product, and period as annual or quarter.
- Transcripts are available at /api/transcript/<ticker>/<quarter>/<year>/ with ticker options and specific quarter/year.
- SEC Filings can be accessed via /api/sec-filings/<ticker>/.
- Institutional Holders information is retrievable through /api/institutional-holders/<ticker>/<date>/, with date indicating the filing report date.
- Stock News is available at /api/news/<ticker>/<limit>/, with an optional limit parameter (defaults to 10).

Request Rate Limiting
API usage is subject to request limits per hour as follows:

- Unauthenticated users are limited to 500 requests.
- Authenticated users have a 1,000 request limit.
- Essential users can make 15,000 requests.
- Ultimate users enjoy unlimited requests.
Exceeding these limits will result in an HTTP 403 Forbidden Response for further requests.
"""

from langchain.chains import APIChain
from langchain_anthropic import ChatAnthropic

llm = ChatAnthropic(
    anthropic_api_key=<hidden for privacy>,
    model="claude-3-haiku-20240307",
    temperature=0
)

chain = APIChain.from_llm_and_api_docs(
    llm,
    api_docs,
    verbose=True,
    limit_to_domains=None
)

chain.run(
    "Get Microsoft's income statement."
)

### Error Message and Stack Trace (if applicable)

> Entering new APIChain chain...
To get Microsoft's income statement, the appropriate API endpoint is:

/api/income-statement/MSFT/

This URL will fetch the annual income statement for Microsoft (ticker symbol MSFT) using the `get_income_statement()` function.

The full API URL would be:

https://discountingcashflows.com/api/income-statement/MSFT/

This URL is the most concise way to retrieve Microsoft's income statement data, as it directly targets the relevant endpoint without any unnecessary parameters.
---------------------------------------------------------------------------
InvalidSchema                             Traceback (most recent call last)
[<ipython-input-23-cefb16deeb59>](https://localhost:8080/#) in <cell line: 17>()
     15 )
     16 
---> 17 chain.run(
     18     "Get Microsoft's income statement."
     19 )

13 frames
[/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py](https://localhost:8080/#) in warning_emitting_wrapper(*args, **kwargs)
    143                 warned = True
    144                 emit_warning()
--> 145             return wrapped(*args, **kwargs)
    146 
    147         async def awarning_emitting_wrapper(*args: Any, **kwargs: Any) -> Any:

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in run(self, callbacks, tags, metadata, *args, **kwargs)
    543             if len(args) != 1:
    544                 raise ValueError("`run` supports only one positional argument.")
--> 545             return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    546                 _output_key
    547             ]

[/usr/local/lib/python3.10/dist-packages/langchain_core/_api/deprecation.py](https://localhost:8080/#) in warning_emitting_wrapper(*args, **kwargs)
    143                 warned = True
    144                 emit_warning()
--> 145             return wrapped(*args, **kwargs)
    146 
    147         async def awarning_emitting_wrapper(*args: Any, **kwargs: Any) -> Any:

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs, callbacks, tags, metadata, run_name, include_run_info)
    376         }
    377 
--> 378         return self.invoke(
    379             inputs,
    380             cast(RunnableConfig, {k: v for k, v in config.items() if v is not None}),

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in invoke(self, input, config, **kwargs)
    161         except BaseException as e:
    162             run_manager.on_chain_error(e)
--> 163             raise e
    164         run_manager.on_chain_end(outputs)
    165 

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in invoke(self, input, config, **kwargs)
    151             self._validate_inputs(inputs)
    152             outputs = (
--> 153                 self._call(inputs, run_manager=run_manager)
    154                 if new_arg_supported
    155                 else self._call(inputs)

[/usr/local/lib/python3.10/dist-packages/langchain/chains/api/base.py](https://localhost:8080/#) in _call(self, inputs, run_manager)
    162                 f"{api_url} is not in the allowed domains: {self.limit_to_domains}"
    163             )
--> 164         api_response = self.requests_wrapper.get(api_url)
    165         _run_manager.on_text(
    166             str(api_response), color="yellow", end="\n", verbose=self.verbose

[/usr/local/lib/python3.10/dist-packages/langchain_community/utilities/requests.py](https://localhost:8080/#) in get(self, url, **kwargs)
    150     def get(self, url: str, **kwargs: Any) -> Union[str, Dict[str, Any]]:
    151         """GET the URL and return the text."""
--> 152         return self._get_resp_content(self.requests.get(url, **kwargs))
    153 
    154     def post(

[/usr/local/lib/python3.10/dist-packages/langchain_community/utilities/requests.py](https://localhost:8080/#) in get(self, url, **kwargs)
     28     def get(self, url: str, **kwargs: Any) -> requests.Response:
     29         """GET the URL and return the text."""
---> 30         return requests.get(url, headers=self.headers, auth=self.auth, **kwargs)
     31 
     32     def post(self, url: str, data: Dict[str, Any], **kwargs: Any) -> requests.Response:

[/usr/local/lib/python3.10/dist-packages/requests/api.py](https://localhost:8080/#) in get(url, params, **kwargs)
     71     """
     72 
---> 73     return request("get", url, params=params, **kwargs)
     74 
     75 

[/usr/local/lib/python3.10/dist-packages/requests/api.py](https://localhost:8080/#) in request(method, url, **kwargs)
     57     # cases, and look like a memory leak in others.
     58     with sessions.Session() as session:
---> 59         return session.request(method=method, url=url, **kwargs)
     60 
     61 

[/usr/local/lib/python3.10/dist-packages/requests/sessions.py](https://localhost:8080/#) in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    587         }
    588         send_kwargs.update(settings)
--> 589         resp = self.send(prep, **send_kwargs)
    590 
    591         return resp

[/usr/local/lib/python3.10/dist-packages/requests/sessions.py](https://localhost:8080/#) in send(self, request, **kwargs)
    695 
    696         # Get the appropriate adapter to use
--> 697         adapter = self.get_adapter(url=request.url)
    698 
    699         # Start time (approximately) of the request

[/usr/local/lib/python3.10/dist-packages/requests/sessions.py](https://localhost:8080/#) in get_adapter(self, url)
    792 
    793         # Nothing matches :-/
--> 794         raise InvalidSchema(f"No connection adapters were found for {url!r}")
    795 
    796     def close(self):

InvalidSchema: No connection adapters were found for "To get Microsoft's income statement, the appropriate API endpoint is:\n\n/api/income-statement/MSFT/\n\nThis URL will fetch the annual income statement for Microsoft (ticker symbol MSFT) using the `get_income_statement()` function.\n\nThe full API URL would be:\n\nhttps://discountingcashflows.com/api/income-statement/MSFT/\n\nThis URL is the most concise way to retrieve Microsoft's income statement data, as it directly targets the relevant endpoint without any unnecessary parameters."

### Description

Trying to request API data from discountingcashflows.com free API (no key required). When I set limit_to_domains=None I get the above error and when I set limit_to_domains=["https://discountingcashflows.com/"] I get a ValueError: {api_url} is not in the allowed domains.

### System Info

langchain==0.1.13
langchain-anthropic==0.1.4
langchain-community==0.0.29
langchain-core==0.1.33
langchain-text-splitters==0.0.1
Linux-6.1.58+-x86_64-with-glibc2.35
Python 3.10.12

@dosu-bot

**Comment by duotangx** [comment]
@dosu-bot thoughts?

**Comment by duotangx** [comment]
@dosu-bot any thoughts?

**Comment by duotangx** [comment]
@dosu-bot is there a better way to format/structure the api_docs to make it easier for 'from_llm_and_api_docs' to parse?

**Comment by ronidas39** [comment]
my code:
`from langchain_openai import ChatOpenAI
from langchain.chains import APIChain
import json

llm=ChatOpenAI(model="gpt-4o")

api_docs={
    "endpoint": "https://api.coinap.io/v2/assets/{name}",
    "method": "GET",
    "description": "Retrieves information of a crypto token.",
    "parameters": [
      {
        "name": "name",
        "type": "string",
        "required": True,
        "description": "The name of the crypto token in lowercase."
      }
    ]
}
chain=APIChain.from_llm_and_api_docs(
    llm,
    api_docs=json.dumps(api_docs),
    verbose=True,
    limit_to_domains=["https://api.coincap.io/v2/assets/"]
)
response=chain.invoke("give information on bitcoin")`





error getting:
https://api.coinap.io/v2/assets/bitcoin
``` is not in the allowed domains: ['https://api.coincap.io/v2/assets/']

  please help I have followed your suggestion

**Comment by ronidas39** [comment]
i have fixed it if you are also having same issue try to use 
from langchain_openai import OpenAI
dont use 
from langchain_openai import ChatOpenAI
ChatOpenAI has some problem  with request module .
Langchai_openai team should fix it
