### ISSUE TITLE
why  report TypeError?

### ISSUE THREAD

**Issue by estuday** [langchain-ai/langchain#19553]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

..

### Description

hi,
I had an error running the following code ：
```python
add_routes(
    app,
    chat_model,
    path="/chat",
)
uvicorn.run(app, host="", port=8005)

chat_chain = RemoteRunnable("http://:8005/chat/")

prompt=ChatPromptTemplate.from_template("写一段关于超人的故事")

chain= prompt | RunnableMap(
    {
        "chat":chat_chain
    }
)
print(chain.invoke(prompt))
```
it report:  `Expected mapping type as input to ChatPromptTemplate. Received <class 'langchain_core.prompts.chat.ChatPromptTemplate'>.
`
is` ChatPromptTemplate` different from `langchain_core.prompts.chat.ChatPromptTemplate`

### System Info

langchain                     0.1.13
langchain-community           0.0.29
langchain-core                0.1.33
langchain-experimental        0.0.55
langchain-text-splitters      0.0.1
langcodes                     3.3.0
langserve                     0.0.51
langsmith                     0.1.31

**Comment by liugddx** [comment]
Let me see.

**Comment by wenxianhui** [comment]
> Expected mapping type as input to ChatPromptTemplate

i think the param should be the input of ChatPromptTemplate? like this:

chat_chain = RemoteRunnable("http://:8005/chat/")
prompt=ChatPromptTemplate.from_template("写一段关于{input}的故事")

chain= prompt | RunnableMap(
    {
        "chat":chat_chain
    }
)
print(chain.invoke({"input":"超人"}))

**Comment by estuday** [comment]
> > Expected mapping type as input to ChatPromptTemplate
> 
> i think the param should be the input of ChatPromptTemplate? like this:
> 
> chat_chain = RemoteRunnable("http://:8005/chat/") prompt=ChatPromptTemplate.from_template("写一段关于{input}的故事")
> 
> chain= prompt | RunnableMap( { "chat":chat_chain } ) print(chain.invoke({"input":"超人"}))

hi,
Your code works, but it limits prompt. I want to implement a free conversation, which means prompt can be any text.

**Comment by liugddx** [comment]
> > > Expected mapping type as input to ChatPromptTemplate
> > 
> > 
> > i think the param should be the input of ChatPromptTemplate? like this:
> > chat_chain = RemoteRunnable("http://:8005/chat/") prompt=ChatPromptTemplate.from_template("写一段关于{input}的故事")
> > chain= prompt | RunnableMap( { "chat":chat_chain } ) print(chain.invoke({"input":"超人"}))
> 
> hi, Your code works, but it limits prompt. I want to implement a free conversation, which means prompt can be any text.

Refer to https://python.langchain.com/docs/modules/model_io/prompts/quick_start#chatprompttemplate
