### ISSUE TITLE
Error while running a simple ainvoke from a chain

### ISSUE THREAD

**Issue by KosPsych** [langchain-ai/langchain#19595]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

prompt = PromptTemplate.from_template(template)

llm = Anyscale(
                    model_name='mistralai/Mixtral-8x7B-Instruct-v0.1', 
                    )

chain = LLMChain(
                            prompt = prompt, 
                            llm=llm
                            )

result = await chain.ainvoke({"chat_history": chat_history, "question": question}, config={"callbacks":[callback]})

### Error Message and Stack Trace (if applicable)

[llm/error] [1:chain:LLMChain > 2:llm:Anyscale] [1.26s] LLM run errored with error:
"TypeError('additional_kwargs[\"logprobs\"] already exists in this message, but with a different type.')Traceback (most recent call last):\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 806, in _agenerate_helper\n    await self._agenerate(\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_community/llms/anyscale.py\", line 287, in _agenerate\n    generation += chunk\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/outputs/generation.py\", line 44, in __add__\n    generation_info = merge_dicts(\n                      ^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/utils/_merge.py\", line 27, in merge_dicts\n    raise TypeError(\n\n\nTypeError: additional_kwargs[\"logprobs\"] already exists in this message, but with a different type."
[chain/error] [1:chain:LLMChain] [1.27s] Chain run errored with error:
"TypeError('additional_kwargs[\"logprobs\"] already exists in this message, but with a different type.')Traceback (most recent call last):\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain/chains/base.py\", line 203, in ainvoke\n    await self._acall(inputs, run_manager=run_manager)\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain/chains/llm.py\", line 275, in _acall\n    response = await self.agenerate([inputs], run_manager=run_manager)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain/chains/llm.py\", line 142, in agenerate\n    return await self.llm.agenerate_prompt(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 579, in agenerate_prompt\n    return await self.agenerate(\n           ^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 965, in agenerate\n    output = await self._agenerate_helper(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 822, in _agenerate_helper\n    raise e\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/language_models/llms.py\", line 806, in _agenerate_helper\n    await self._agenerate(\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_community/llms/anyscale.py\", line 287, in _agenerate\n    generation += chunk\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/outputs/generation.py\", line 44, in __add__\n    generation_info = merge_dicts(\n                      ^^^^^^^^^^^^\n\n\n  File \"/home/.../anaconda3/envs/llm-doc/lib/python3.11/site-packages/langchain_core/utils/_merge.py\", line 27, in merge_dicts\n    raise TypeError(\n\n\nTypeError: additional_kwargs[\"logprobs\"] already exists in this message, but with a different type."
additional_kwargs["logprobs"] already exists in this message, but with a different type.

### Description

Running the code above (minimal example) I see the error below which is an internal langchain error.
What is the reason and how should i fix it?

### System Info

langchain==0.1.13

**Comment by KosPsych** [comment]
@dosu-bot please reply to the above

**Comment by KosPsych** [comment]
@dosu-bot Based on your response modify my code so that it is correct.

**Comment by liugddx** [comment]
`langchain_core/utils/_merge.py",in merge_dicts`. The exception is here, maybe your return cannot be merged
