### ISSUE TITLE
Langchain CSV Agent not Returning Relevant Data 

### ISSUE THREAD

**Issue by loyal812** [langchain-ai/langchain#19621]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
self.agent = create_csv_agent(
            ChatOpenAI(temperature=0, streaming=True, max_tokens=4000, model_name="gpt-3.5-turbo-16k"),
            path=os.path.join(os.path.abspath(""), "test", "regression", "4", "finance.csv"),
            verbose=True,
            agent_type=AgentType.OPENAI_FUNCTIONS,
            pandas_kwargs={
                # 'decode':'latin-1',
                'encoding':'latin-1'
            },
            reduce_k_below_max_tokens=True,
            handle_parsing_errors=True
        )
```

### Description

I have been working on creating a CSV agent using Langchain, but unfortunately, the results are not as expected. The data returned is not relevant and seems to be of poor quality. I am unable to extract any meaningful information from it, causing a setback in my project development.

### Steps to Reproduce
1. Implementing a CSV agent using Langchain.
2. Retrieving data from a CSV file.
3. Analyzing the returned data for relevance.

### Expected Behavior
The Langchain CSV agent should return relevant and accurate data extracted from the CSV file, suitable for further processing and analysis.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.1.33
> langchain: 0.1.13
> langchain_community: 0.0.29
> langsmith: 0.1.31
> langchain_experimental: 0.0.55
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by CrasCris** [comment]
Try to use a custome prefix and sufix, and add context of csv (like the name of the columns or what the data is talking about/ summary) , the csv agent convert the data into a dataframe
