### ISSUE TITLE
Is there a non-prompt way to stop ChatVectorDBChain from answering when no vectors are found?

### ISSUE THREAD

**Issue by phiweger** [langchain-ai/langchain#1963]
Say I query my vector database with a minimum distance threshold and no documents ("sources") are returned, how can I stop ChatVectorDBChain from answering the question without using prompts? 

I observe that even though it finds no sources, it will answer based on chat history or overwrite the prompt instructions. I would like to have a deterministic switch like:

```python
if no_documents:
    raise ValueError()
```

and then catch this error to print some message and continue.

**Comment by malcolmosh** [comment]
There should be a way to stop a chain or a sequence based on certain criteria too, such as a similarity threshold or the result of a moderation chain.

**Comment by veedeo** [comment]
How do you control the threshold?
I'm using a pinecone and it always returns some document
