### ISSUE TITLE
Bedrock Mistral not working as agent

### ISSUE THREAD

**Issue by WaterKnight1998** [langchain-ai/langchain#19647]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain import hub
from langchain_community.chat_models.bedrock import BedrockChat
from langchain.agents import AgentExecutor, create_structured_chat_agent

from langchain_community.tools.tavily_search import TavilySearchResults

prompt = hub.pull("hwchase17/structured-chat-agent")

llm_model = BedrockChat(
        region_name="us-east-1",
        model_id="mistral.mistral-7b-instruct-v0:2",
    )

tools = [TavilySearchResults()]
agent = create_structured_chat_agent(llm_model, tools, prompt)

agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    handle_parsing_errors=True,
    return_intermediate_steps=True,
)

agent.invoke({"input": "What is the president of USA?"})
```

### Error Message and Stack Trace (if applicable)

Exception: ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: Malformed input request: #: extraneous key [stop_sequences] is not permitted, please reformat your input and try again.

### Description

* I am using Mistral model of AWS Bedrock as an agent
* It doesn't work

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020
> Python Version:  3.10.0 (default, Nov 11 2023, 18:46:15) [Clang 15.0.0 (clang-1500.0.40.1)]

Package Information
-------------------
> langchain_core: 0.1.34
> langchain: 0.1.13
> langchain_community: 0.0.29
> langsmith: 0.1.33
> langchain_google_vertexai: 0.1.2
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by BasemRizk** [comment]
Hello , I have the same issue , do you find a solution ?

**Comment by hasansustcse13** [comment]
You can try this
`agent = create_structured_chat_agent(llm_model, tools, prompt, stop_sequence=False)`
