### ISSUE TITLE
pgvector.py has created a dependency on  sqlalchemy v2, breaking apps using sqlalchemy v1

### ISSUE THREAD

**Issue by gibson3659** [langchain-ai/langchain#19681]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.retrievers.multi_query import MultiQueryRetriever

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/site-packages/langchain/retrievers/__init__.py", line 33, in <module>
    from langchain.retrievers.self_query.base import SelfQueryRetriever
  File "/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/site-packages/langchain/retrievers/self_query/base.py", line 5, in <module>
    from langchain_community.vectorstores import (
  File "/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/site-packages/langchain_community/vectorstores/__init__.py", line 115, in __getattr__
    module = importlib.import_module(_module_lookup[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/site-packages/langchain_community/vectorstores/pgvector.py", line 23, in <module>
    from sqlalchemy import SQLColumnExpression, delete, func
ImportError: cannot import name 'SQLColumnExpression' from 'sqlalchemy' (/home/ubuntu/miniconda3/envs/nettalk/lib/python3.12/site-packages/sqlalchemy/__init__.py)

### Description

My app uses sqlalchemy v1 due to my db dialect not supporting v2.  The above change breaks MultiQueryRetriever in 0.1.13.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023
> Python Version:  3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.1.33
> langchain: 0.1.13
> langchain_community: 0.0.29
> langsmith: 0.1.31
> langchain_experimental: 0.0.55
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.1
> langgraph: 0.0.25

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by shelpuk** [comment]
Please suggest a workaround or a proper langchain downgrade version. This is really critical.

**Comment by gibson3659** [comment]
> Please suggest a workaround or a proper langchain downgrade version. This is really critical.

The following works:
langchain - 0.1.12
langchain-community - 0.0.28

**Comment by gibson3659** [comment]
Any update.  The commit that added the dependency is https://github.com/langchain-ai/langchain/commit/6cdca4355d095e39813b003c68786a38e4cbda5b.

**Comment by marcsalesgrid** [comment]
> > Please suggest a workaround or a proper langchain downgrade version. This is really critical.
> 
> The following works: langchain - 0.1.12 langchain-community - 0.0.28

This still is not resolved in langchain 0.1.20. I downgraded as described above, but that didn't resolve the issue either:
langchain==0.1.12
langchain-community==0.0.28
langchain-core==0.1.52
langchain-text-splitters==0.0.1
langsmith==0.1.57

**Comment by krassowski** [comment]
@gibson3659 and anyone interested - I opened https://github.com/langchain-ai/langchain/pull/22546 a week ago to address this issue, hopefully it will be accepted :crossed_fingers:
