### ISSUE TITLE
ConversationalRetrievalChain returns answers outside context of retriever

### ISSUE THREAD

**Issue by Subhadra95** [langchain-ai/langchain#19694]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k":2})
    QUESTION_PROMPT = PromptTemplate.from_template("""Answer the question in your own words from the 
    context given to you. If questions are asked where there is no relevant context available, please say you donot know. Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

    Chat History:
    {chat_history}
    Follow Up Input: {question}
    Standalone question:""")
    qa = ConversationalRetrievalChain.from_llm(llm=llm,
                                            retriever=retriever,
                                            condense_question_prompt=QUESTION_PROMPT,
                                            return_source_documents=True,
                                            verbose=False)

### Description

I am using ConversationalRetrievalChain to answer questions based on the knowledge added to embeddings. But it answers any generic questions which are not part of embeddings. How can I make sure that model doesn't use its pre-trained knowledge but just stick to the knowledge base stored in vector db embeddings, and say "I dot know" for the questions outside of the context

### System Info

langchain 0.1.2

**Comment by shobhitagnihotri69** [comment]
Please install latest version of langchain , pip install langchain --upgrade . Please give more information about embeddings

**Comment by Subhadra95** [comment]
used azure openai embeddings and stored in pinecone.
