### ISSUE TITLE
How to do RAG + Conversational Memory?

### ISSUE THREAD

**Issue by RakeshMahendran** [langchain-ai/langchain#19697]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_core.runnables import RunnablePassthrough
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context": retriever | format_docs, "input": RunnablePassthrough()}
    | custom_rag_prompt
    | llm
    | output_parser
)

response = rag_chain.invoke("How LCNC is disrupting the development market ? Is it for real ? ")

This has a custom prompt template , vector store and rag, but I need to add a conversation buffer to it, is that possible?

### Description

I am currently working in RAG + Vectorstore + Langchain . In this method I need to add conversational memory, which will help me to answer with the context of the previous response. Is there any method to do it?

### System Info

Linux
Langchain

**Comment by swapnilwagh2204** [comment]
I am working on the RAG+SQL+Langchain combination.
Its very similar to what you are doing here.

This is my SQL generation prompt:

        template = """
        You are a helpful and clever data analyst at a company. You are interacting with a user who is asking you questions about the company's database.
        Based on the table schema below, write a SQL query that would answer the user's question. Take the conversation history into account.
        
        <SCHEMA>{schema}</SCHEMA>
        
        Conversation History: {chat_history}
        
        Write only the SQL query and nothing else. Do not wrap the SQL query in any other text, not even backticks.
        
        For example:
        Question: which 3 artists have the most tracks?
        SQL Query: SELECT ArtistId, COUNT(*) as track_count FROM Track GROUP BY ArtistId ORDER BY track_count DESC LIMIT 3;
        Question: Name 10 artists
        SQL Query: SELECT Name FROM Artist LIMIT 10;
        
        Your turn:
        
        Question: {question}
        SQL Query:
        """

This is my response generation prompt.

        template = """
        You are a data analyst at a company. You are interacting with a user who is asking you questions about the company's database.
        Based on the table schema below, question, sql query, and sql response, write a natural language response.strictly use the underlying database for the answers.If answer is not from the database..then say i dont know the answer. If you don't know the answer, just say that you don't know, don't try to make up an answer.dont mention 'sql' in the answer.

        <SCHEMA>{schema}</SCHEMA>

        Conversation History: {chat_history}
        SQL Query: <SQL>{query}</SQL>
        User question: {question}
        SQL Response: {response}"""

Prompt generation and chain creation

       prompt = ChatPromptTemplate.from_template(template)

       chain = (
        RunnablePassthrough.assign(query=sql_chain).assign(
            schema=lambda _: db.get_table_info(),
            response=lambda vars: print(f"\n\nExecuting SQL query: {vars['query']}") or db.run(vars["query"]) if 
      is_runnable_query(vars["query"],db) else "Sorry, i cant get this data right now",
        )   
        | prompt
        | llm
        | StrOutputParser()
    )
   
# Last step:
    return chain.invoke({
        "question": user_query,
        "chat_history": chat_history,
    })

Can you please share some more info about your application? 
Give me more info like what vectorstore you are using (chroma or FAISS or pinecone ?)  So that i can go into specific details

**Comment by RakeshMahendran** [comment]
Thanks swapnil for your reply 
I am using qdrant 
`
from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_openai import  OpenAIEmbeddings
from langchain_community.vectorstores import Qdrant
from langchain import hub
from langchain_openai import ChatOpenAI
import qdrant_client

# loader = CSVLoader("/content/Data/fivehundreddatafortesting.csv",encoding="latin-1")

# docs = loader.load()

# text_splitter = RecursiveCharacterTextSplitter(
#     chunk_size=1000,
#     chunk_overlap=200,
#    )
# splits = text_splitter.split_documents(docs)
# url = "Your qdrant url"
#api_key = "your api key"

# vectorstore = Qdrant.from_documents(
#     documents=docs,
#     embedding=OpenAIEmbeddings(),
#     url=url,
#     prefer_grpc=True,
#     api_key=api_key,
#     collection_name="final_chunk",
#   )

llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

        # Initialize QdrantClient
client = qdrant_client.QdrantClient(
     "Your qdrant url,
     api_key="your qdrant api key",
   )

        # Initialize Qdrant Vector Store
vectorstore = Qdrant(
client=client,
collection_name="equal_chunk",
embeddings=OpenAIEmbeddings(),
        )

        # Initialize retriever
retriever = vectorstore.as_retriever()
`
In the above code,  i have initialized an existing collection , but also i have attached the code to create a collection
 
```

from langchain_core.prompts import (
    ChatPromptTemplate,
    FewShotChatMessagePromptTemplate
)

examples = [
   #Your examples for few shot prompt goes here
]

example_prompt = ChatPromptTemplate.from_messages(
    [
        ("human", "{input}"),
        ("ai", "{output}"),
    ]
)

few_shot_prompt = FewShotChatMessagePromptTemplate(
    example_prompt=example_prompt,
    examples=examples,
)
```

I have added few shot prompting technique, i have a doubt as this is working or not , please provide  insights on this too.

```

from langchain.output_parsers import CommaSeparatedListOutputParser
from langchain_openai import ChatOpenAI

custom_rag_prompt = ChatPromptTemplate.from_messages(
            [
                ("system", """
          Your system prompt here
    """),
                few_shot_prompt,
                ("human", "{input}"),
            ]
        )

print(custom_rag_prompt)


llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

output_parser = CommaSeparatedListOutputParser()

from langchain_core.runnables import RunnablePassthrough
def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

rag_chain = (
    {"context": retriever | format_docs, "input": RunnablePassthrough()}
    | custom_rag_prompt
    | llm
    | output_parser
)

response = rag_chain.invoke("Question here")

```

For this code , I need to make this particular thing as conversational can you please provide insights on this
