### ISSUE TITLE
Langchain version greater than 0.1.7 results in pip error involving Cargo/Rust

### ISSUE THREAD

**Issue by Zhongzhou** [langchain-ai/langchain#19719]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

pip install --upgrade langchain==0.1.8

### Error Message and Stack Trace (if applicable)

Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.2.0,>=0.1.0->langchain==0.1.8)
  Using cached orjson-3.10.0.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Description

I'm trying to install langchain. I'm using Python 3.12.2 64 bit on Windows, and installing in .venv.
Versions higher than 0.1.7 will cause an error in pip installer. Versions lower than 0.1.7 (including 0.1.7) installs fine. Strangely the same issue didn't happen last week.

### System Info

platform: Windows 11
python 3.12.2 64 bit

**Comment by Zhongzhou** [comment]
Installing orjson version 3.9.15 manually seems to solve the issue. orjson's latest version is causing the problem. 
``` python
!pip install orjson==3.9.15
```

**Comment by juanDataDGC** [comment]
I fixed this problem by intalling rust on my machine. I have a mac so 
```brew install rust``` 
did the trick for me. 
for windows, I guess you could follow these [instructions](https://forge.rust-lang.org/infra/other-installation-methods.html)

**Comment by lamaplays** [comment]
i had python 3.14 and i downgraded it to 3.10 
 the command 
`pip install langchain-openai` 
ran smoothly
