### ISSUE TITLE
ChatOpenAI.get_num_tokens_from_messages: use self.model_name and support GPT-4

### ISSUE THREAD

**Issue by asadovsky** [langchain-ai/langchain#1972]
A couple problems:

- `ChatOpenAI.get_num_tokens_from_messages()` takes a `model` parameter that is not included in the [base class method signature](https://github.com/hwchase17/langchain/blob/master/langchain/schema.py#L208). Instead, it should use `self.model_name`, similar to how the `BaseOpenAI.get_num_tokens()` does.
- `ChatOpenAI.get_num_tokens_from_messages()` does not support GPT-4. See here for the updated formula: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by Aratako** [comment]
There is already a PR to fix this issue at #1858.
Is this fix acceptable?

**Comment by asadovsky** [comment]
Yes, looks like it would fix this issue, thanks!

One minor suggestion is to link to the official documentation from the code:
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb

That way anyone reading the code would know where it came from and can verify that it's up to date.

**Comment by Aratako** [comment]
Thanks! I added the link to code.
