### ISSUE TITLE
DOC: broken ChatOllama API reference link 

### ISSUE THREAD

**Issue by rajaboja** [langchain-ai/langchain#19753]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

ChatOllama API reference link on [this](https://python.langchain.com/docs/integrations/chat/ollama#usage) page is broken.

### Idea or request for content:

New ref should be `https://api.python.langchain.com/en/latest/llms/langchain_community.llms.ollama.Ollama.html`

**Comment by baskargopinath** [comment]
issue seems to be fixed

**Comment by rajaboja** [comment]
No, still throws 404.
