### ISSUE TITLE
sqlalchemy dependency in pyproject.toml still needs to be bumped to *

### ISSUE THREAD

**Issue by tback** [langchain-ai/langchain#1975]
I think the sqlalchemy dependency in pyproject.toml still needs to be bumped.

_Originally posted by @sliedes in https://github.com/hwchase17/langchain/issues/1272#issuecomment-1473683519_

**Comment by MrSalman333** [comment]
please

**Comment by MrSalman333** [comment]
any update on this?? 

should be very minor team,, 
do u need us to open a PR?

**Comment by shanifdhanani** [comment]
Also a blocker for me... in case it helps :)
