### ISSUE TITLE
Latency/CPU usage: core's dumpd function used by callback system is inefficient and add important latency during chain invocation

### ISSUE THREAD

**Issue by nbondoux** [langchain-ai/langchain#19756]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Any invocation of any chain will trigger calls to langchain_core.load.dump.dumpd

### Description

I observe that, during the invocation of a chain doing rag+reranking, and with a function call, between 300 and 700 ms are spent into langchain_core; most of the cpu usage comes from the function langchain_core.load.dump.dumpd, which is used for each callback events (eg on_chain_start, on_chain_end) to transform the input and output of the chains into json-like object. If dumpd is changed to fo nothing and return {}, the time spent in langchain goes down to a few ms.

This is not surprising, as callback can be triggered dozen of times within one complex chain calls, and considering that the implementation of dumpd is inefficient: return json.loads(json.dumps(obj)).

What makes the problem worse is that dumpd is called whether there is or not callback handlers.

Naturally, the usage of dumpd worsen with bigger context sizes, and bigger input/output of chains.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Wed Apr 27 20:34:34 UTC 2022
> Python Version:  3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.32
> langchain: 0.1.8
> langchain_community: 0.0.21
> langsmith: 0.1.27
> langchain_openai: 0.0.6

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by xuehanbing1** [comment]
+1. We also met this problem. Please fix.

**Comment by Arthur-Bi** [comment]
+1. We also met this problem. Please fix.
