### ISSUE TITLE
Need clarification on model specific prompt conversion

### ISSUE THREAD

**Issue by bibhas2** [langchain-ai/langchain#19763]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Page: https://python.langchain.com/docs/modules/model_io/prompts/quick_start

LLM models are very sensitive to the format of the input text. They expect special markers like ``[INST]`` and ``<|assistant|>`` in specific places as they have been trained with. The document needs to make it clear that Langchain's higher level abstraction of prompt (like ``ChatPromptTemplate``) eventually gets converted into the model specific format.

This will be reassuring for the users of Langchain.

### Idea or request for content:

It will be beneficial if the sentence:

```
LangChain strives to create model agnostic templates to make it easy to reuse existing 
templates across different language models.
```

Is followed by something like this:

```
Model agnostic templates are eventually converted to model specific input in a 
format as expected by the model. 
```

**Comment by eyurtsev** [comment]
Great idea for improving the docs (and yes that's correct model implementations are able to apply the appropriate syntax so users don't have to worry about it)

**Comment by TS-Lee** [comment]
Where does this happen though? I see ChatMistralAI prepares a dictionary and post it to an endpoint. But for a self hosted LLM that takes just a string (e.g., `_call` takes `prompt`), where does this conversion happen?
