### ISSUE TITLE
StructuredOutputParser - Allow users to get multiple items from response.

### ISSUE THREAD

**Issue by keremnalbant** [langchain-ai/langchain#1976]
* Allow users to choose the type in the schema (string | List[string])
* Allow users to get multiple json objects (get JSON array) in the response. I achieved it by replacing the {{ }} -> [[ ]] as follows: `prompt.replace("""{{
	"ID": string  // IDs which refers to the sentences.
	"Text": string  // Sentences that contains the answer to the question.
}}""", """[[
	"ID": string  // IDs which refers to the sentences.
	"Text": string  // Sentences that contains the answer to the question.
]]""")` And got a list of json objects with this method.

**Comment by berengamble** [comment]
Very hacky, but this is what I did to have it return an array of objects.

```
output_parser = StructuredOutputParser.from_response_schemas(
    response_schemas=[
        ResponseSchema(
            name="country_code", description="two letter country code"
        ),
        ResponseSchema(name="city", description="city name"),
        ResponseSchema(
            name="places",
            description="""array of of 10 places in the following format: [
    {{ "name": string // name of the place',  "types": [string] // types of the place' }}
]
""",
        ),
    ]
)

format_instructions =output_parser.get_format_instructions()
format_instructions =format_instructions.replace(
    '"places": string', '"places": array of objects'
)
```
Which generates:
```
```json
{
        "country_code": string  // two letter country code
        "city": string  // city name
        "places": array of objects  // array of of 10 places in the following format: [
            { "name": string // name of the place',  "types": [string] // types of the place' }
        ]
        
}
```
```

**Comment by IbraheemAlSaady** [comment]
I managed to achieve this by passing `type` to the ResponseSchema. Something like this 

```
ResponseSchema(
            name="someList", description="description to model with the example: [{name: string, other: string}]", type="array(objects)"
        )
````

**Comment by patrick-ve** [comment]
> I managed to achieve this by passing `type` to the ResponseSchema. Something like this
> 
> ```
> ResponseSchema(
>   name="someList", description="description to model with the example: [{name: string, other: string}]", 
>   type="array(objects)"
> )
> ```

Is there a TypeScript equivalent of `ResponseSchema` for Langchain.js? It doesn't look like so, but it would be greatly helpful for the JS/TS community.
