### ISSUE TITLE
Extend @tool to work with methods

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#19783]
It looks like a number of users are trying to use @tool with methods. This is likely helpful in binding state to the tools for users that do not want to make a tool factory.

### Discussed in https://github.com/langchain-ai/langchain/discussions/9404

<div type='discussions-op-text'>

<sup>Originally posted by **rlnasuti** August 17, 2023</sup>
Hello everyone!

I'm trying to create an Agent with access to some tools where the Agent and the tools themselves are part of a class. This is pretty standard stuff outside of a class, but I'm running into issues when I try to use it as part of a custom class.

Specifically, I'm trying to use the `@tool` decorator on a member function. Here's an example:

``` 
@tool
 def summarize_document(self) -> str:
    """Useful for retrieving a summary of the document."""
    return "No summary available"
```

The problem I'm running into is that the Agent will supply the `self` parameter:

```
> Entering new AgentExecutor chain...
Invoking: `summarize_document` with `{'self': {}}`
```

which causes an error:
`TypeError: _run() got multiple values for argument 'self'`

So my question - has anyone encountered this issue and figured out a way to work around it? I tried giving it an arg_schema that was an empty class along with `infer_schema=False`, but it still tried to send in that `self` parameter. I'd like it to call the member function like this:

```
> Entering new AgentExecutor chain...

Invoking: `self.summarize_document` with `{}`
```</div>

**Comment by wenxianhui** [comment]
> It looks like a number of users are trying to use @tool with methods. This is likely helpful in binding state to the tools for users that do not want to make a tool factory.
> 
> ### Discussed in #9404
> Originally posted by **rlnasuti** August 17, 2023 Hello everyone!
> 
> I'm trying to create an Agent with access to some tools where the Agent and the tools themselves are part of a class. This is pretty standard stuff outside of a class, but I'm running into issues when I try to use it as part of a custom class.
> 
> Specifically, I'm trying to use the `@tool` decorator on a member function. Here's an example:
> 
> ```
> @tool
>  def summarize_document(self) -> str:
>     """Useful for retrieving a summary of the document."""
>     return "No summary available"
> ```
> 
> The problem I'm running into is that the Agent will supply the `self` parameter:
> 
> ```
> > Entering new AgentExecutor chain...
> Invoking: `summarize_document` with `{'self': {}}`
> ```
> 
> which causes an error: `TypeError: _run() got multiple values for argument 'self'`
> 
> So my question - has anyone encountered this issue and figured out a way to work around it? I tried giving it an arg_schema that was an empty class along with `infer_schema=False`, but it still tried to send in that `self` parameter. I'd like it to call the member function like this:
> 
> ```
> > Entering new AgentExecutor chain...
> 
> Invoking: `self.summarize_document` with `{}`
> ```</div>
> ```

Hi, I tried to solve this feature, but I found that invoking class member function(not static) required instance in args, cause self is the first arg of class member function. However, we can use static member function instead, following is the test code:


from typing import Any, Callable, Optional

class Tool:
    func: Optional[Callable[..., str]]

    def __init__(self, func: Optional[Callable]) -> None:
        self.func = func

    def run(self, *args: Any) -> Any:
        return self.func(*args)


def tool(func) -> Tool:
    return Tool(func)


class classMethod:
    @staticmethod
    @tool
    def staticFunc(word: str) -> str:
        return str(len(word))

    @tool
    def memberFunc(self, word: str) -> str:
        return str(len(word))


if __name__ == "__main__":
    staticTest = classMethod.staticFunc
    print(staticTest.run("test"))

    testClass = classMethod()
    testRun = testClass.memberFunc
    print(testRun.run(testClass, "test"))

**Comment by wenxianhui** [comment]
`from typing import Any, Callable, Optional


class Tool:
    func: Optional[Callable[..., str]]

    def __init__(self, func: Optional[Callable]) -> None:
        self.func = func

    def run(self, *args: Any) -> Any:
        return self.func(*args)


def tool(func) -> Tool:
    return Tool(func)


class classMethod:
    @staticmethod
    @tool
    def staticFunc(word: str) -> str:
        return str(len(word))

    @tool
    def memberFunc(self, word: str) -> str:
        return str(len(word))


if __name__ == "__main__":
    staticTest = classMethod.staticFunc
    print(staticTest.run("test"))

    testClass = classMethod()
    testRun = testClass.memberFunc
    print(testRun.run(testClass, "test"))
`

**Comment by lucas-tucker** [comment]
Hello. I experimented with this a bit and found something similar -- methods that do not reference attributes work just fine when using `AgentExecutor` and `create_structured_chat_agent`. However, if an attribute, say `x`, is referenced in the tool-decorated method, then you get an error such as `AttributeError: 'str' object has no attribute 'x'`. In the following example, 
```
class Days():
	def __init__(self, x):
		self.x = x
		return
	@tool
	def time(self):
		"""Returns the current date and time concatenated with x “””
		print(str(self))
		return str(date.today()) + str(self.x)

```
if I instantiate the class as 
`test_day = Days("abc")`
then do we want an agent created as 
`agent = create_structured_chat_agent(llm, [Tool("time", test_day.time, "returns current date and time")], prompt)`
(for some pre-determined prompt and llm) to be able to reference the attributes of test_day? I am trying to understand what functionality we want from this. Thanks
