### ISSUE TITLE
No documentation on how to get the source documents

### ISSUE THREAD

**Issue by bibhas2** [langchain-ai/langchain#19800]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Example documentation: https://python.langchain.com/docs/expression_language/get_started#rag-search-example

When using the new LCEL syntax, we can easily get the response from the LLM as text.

```
chain = setup_and_retrieval | prompt | model | output_parser
```

But none of the documentation I have seen shows how to get a list of the source document IDs.

A [stackoverflow question](https://stackoverflow.com/questions/77759685/how-to-return-source-documents-when-using-langchain-expression-language-lcel) deals with this issue. The accepted solution seems extremely verbose.

### Idea or request for content:

In the RAG examples that use LCEL we need to show how to get the source document list. This is a primary requirement that is not being met.

**Comment by liugddx** [comment]
Please refer to this https://python.langchain.com/docs/use_cases/question_answering/sources
