### ISSUE TITLE
Error in Chroma Vectore Store example. 

### ISSUE THREAD

**Issue by raulalhena** [langchain-ai/langchain#19807]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://python.langchain.com/docs/integrations/vectorstores/chroma

This line, should be:
from langchain_community.vectorstores import Chroma

from langchain_community.vectorstores.chroma import Chroma

**Comment by AssetDK** [comment]
This seems to solve my problem - thanks @raulalhena. Only I don't see the problem specified, so it would be hard for others to figure this out... ?

My problem was that **persist_directory** was not defined as a parameter nor was **collection_name**, I found that problem raised several times where the suggest solution was to specify the paramters separately  ... this solution (or rather correction of a bug in the documentation is naturally much much better...!)   

I dont know how to better describe this issue and I am rather new to Python.
