### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error

### ISSUE THREAD

**Issue by PRAJINPRAKASH** [langchain-ai/langchain#1986]
Am refereing to this documentaion [here](https://langchain.readthedocs.io/en/latest/modules/chat/examples/chat_vector_db.html) created a file

test.py
```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import ConversationalRetrievalChain

from langchain.chat_models import ChatOpenAI
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)


from langchain.document_loaders import TextLoader


loader = TextLoader('test.txt')
documents = loader.load()

text_splitter = CharacterTextSplitter(chunk_size=200, chunk_overlap=0)
documents = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
vectorstore = Chroma.from_documents(documents, embeddings)


system_template="""Use the following pieces of context to answer the users question. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.
----------------
{context}"""
messages = [
    SystemMessagePromptTemplate.from_template(system_template),
    HumanMessagePromptTemplate.from_template("{question}")
]
prompt = ChatPromptTemplate.from_messages(messages)


qa = ConversationalRetrievalChain.from_llm(ChatOpenAI(temperature=0), vectorstore, qa_prompt=prompt)


chat_history = []
query = "Who is the CEO?"
result = qa({"question": query, "chat_history": chat_history})

print(result)
```

Which throws 
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    qa = ConversationalRetrievalChain.from_llm(ChatOpenAI(temperature=0), vectorstore, qa_prompt=prompt)
  File "/home/prajin/works/ults/gpt/lamda-openai-chat-python/venv/lib/python3.8/site-packages/langchain/chains/conversational_retrieval/base.py", line 140, in from_llm
    return cls(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
retriever
  instance of BaseRetriever expected (type=type_error.arbitrary_type; expected_arbitrary_type=BaseRetriever)

**Comment by leonardonhesi** [comment]
`vectordb = Chroma(
    persist_directory=persist_directory, 
    collection_name=collection_name, 
    embedding_function=embeddings).as_retriever()`

**Comment by sohamok** [comment]
Getting error:
pydantic.error_wrappers.ValidationError: 1 validation error for AIMessage
none is not an allowed value (type=type_error.none.not_allowed)

Code:
def run_agent(question:str, agent_chain: AgentExecutor) -> str:
    """Function to run the brain agent and deal with potential parsing errors"""
    
    try:
        logging.info(f"Received question: {question}")
        x=agent_chain.run(input=question)
        logging.info(f"Agent output: {x}")
        return x

    except OutputParserException as e:
    #     # If the agent has a parsing error, we use OpenAI model again to reformat the error and give a good answer
        chatgpt_chain = LLMChain(
                llm=agent_chain.agent.llm_chain.llm, 
                    prompt=PromptTemplate(input_variables=["error"],
                        template='''
                        Reformat your response in beautiful Markdown. \n
                          Text: {error}''', 
               
            ) ,verbose=True)
        response = chatgpt_chain.run(str(e))
        return response

class DocSearchTool(BaseTool):
    """Tool for Azure GPT Smart Search Engine"""
    
    name = "@docsearch"
    description = "useful when the questions includes the term: @docsearch.\n"

    llm: AzureChatOpenAI
    indexes: List[str] = []
    # vector_only_indexes: List[str] = []
    # k: int = 10
    # reranker_th: int = 1
    # similarity_k: int = 3
    # sas_token: str = ""   
    # embedding_model: str = "text-embedding-ada-002"
    
    def _run(self, tool_input: Union[str, Dict],) -> str:
        try:
            tools = [DocSearchResults(indexes=self.indexes)]

            parsed_input = self._parse_input(tool_input)

            agent_executor = initialize_agent(tools=tools, 
                                              llm=self.llm, 
                                              agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, 
                                              agent_kwargs={'prefix':DOCSEARCHPREFIX},
                                              callback_manager=self.callbacks,
                                              verbose=self.verbose)

            
            for i in range(2):
                try:

                    response = run_agent(parsed_input, agent_executor)
                    break
                except Exception as e:
                    response = str(e)
                    continue

            return response
        
        except Exception as e:
            print(e)

**Comment by arthisri14** [comment]
Traceback (most recent call last):
  File "d:\linkedin_post_generator\data\llm_helper.py", line 6, in <module>
    llm = ChatGroq(groq_api_key=os.getenv("GROQ_API_KEY"), model_name="llama-3.2-90b-text-preview")
  File "C:\Users\arthi\AppData\Roaming\Python\Python38\site-packages\langchain_core\load\serializable.py", line 113, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\arthi\AppData\Roaming\Python\Python38\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatGroq
__root__
  __init__() got an unexpected keyword argument 'proxies' (type=type_error)

**Comment by YVWagter** [comment]
Getting the same issue

File "/app/chatbot.py", line 64, in initialize_models
    self.embedding_model = AzureOpenAIEmbeddings(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AzureOpenAIEmbeddings
__root__
  Client.__init__() got an unexpected keyword argument 'proxies' (type=type_error)

**Comment by ltadjou** [comment]
I have the same error but only on my EC2 app instance.
MY code is working well locally.

**Comment by manojkumarp-24** [comment]
It may be because you're using existing langchain modules that you have already downloaded to your local machine. If you reinstall the langchain-openai module, it will bring the same problem

**Comment by arthisri14** [comment]
i also tried reinstalling the langchain but still facing the same issues

**Comment by YVWagter** [comment]
https://community.openai.com/t/azureopenai-client-typeerror-client-init-got-an-unexpected-keyword-argument-proxies/1035218/8 upgrading to version 1.55.3 works to resolve this issue
