### ISSUE TITLE
Error in apache doris insert

### ISSUE THREAD

**Issue by jose1003** [langchain-ai/langchain#19886]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
The error is in the filer apache_doris.py, folder vectorstores.
The following code ```                        else f"array<float>{str(_n)}"
```, 
need to be chage to 
```
                        else f"{str(_n)}"
```

### Error Message and Stack Trace (if applicable)

Error <class 'pymysql.err.OperationalError'> (1105, "ParseException, ms....

### Description

If we remove the sring "array<float>" it will work. I have tested with apache doris 2.1.0

### System Info

Apache doris 2.1.0
Last version of langchain

**Comment by liugddx** [comment]
Thank you for your feedback. I will fix it.

**Comment by liugddx** [comment]
@jose1003 #19989 PTAL
