### ISSUE TITLE
Pubmed Tool SSL Cert Error when running code https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/tools/pubmed.ipynb getting 'PubMed exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)>' 

### ISSUE THREAD

**Issue by keithrich98** [langchain-ai/langchain#19916]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

%pip install -U xmltodict
from langchain_community.tools.pubmed.tool import PubmedQueryRun
tool = PubmedQueryRun()
tool.invoke("What causes lung cancer?")

### Error Message and Stack Trace (if applicable)

'PubMed exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)>'

### Description

I'm running your notebook and getting a certificate failure when hitting pubmed. https://github.com/langchain-ai/langchain/blob/master/docs/docs/integrations/tools/pubmed.ipynb

### System Info

platform mac
Python 3.11.7
Langchain Version: 0.1.14

**Comment by keithrich98** [comment]
Same error is happening when I run the retriever and document loader notebooks

**Comment by kundan1974** [comment]
I am also getting the same errors

I am using Mac M2
python 3.10
certifi                       2023.7.22
langchain                     0.1.8

**Comment by liugddx** [comment]
Let me see.
