### ISSUE TITLE
GithubFileLoader only imports repositories with main branch 

### ISSUE THREAD

**Issue by AlvaroRaul7** [langchain-ai/langchain#19934]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

loader = GithubFileLoader(
        repo="hotgluexyz/tap-netsuite",
        access_token=gh_token,
        github_api_url="https://api.github.com",
        file_filter=lambda file_path: file_path.endswith(
        ".py"
      ), # retrieves all python files
    )

documents = loader.load()

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-7-5f7842728e5f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 documents = loader.load()

3 frames
[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://localhost:8080/#) in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/hotgluexyz/tap-netsuite/git/trees/main?recursive=1

### Description

 I am trying to use langchain to load a github repository according to the documentation

### System Info

langchain==0.1.14
langchain-community==0.0.31
langchain-core==0.1.38
langchain-openai==0.1.1
langchain-text-splitters==0.0.1
langcodes==3.3.0
langsmith==0.1.38

**Comment by sepiatone** [comment]
The `branch` parameter is set by default to "main" in the `GithubFileLoader` API. Change it to "master" (or whichever branch of your GitHub repo you want)

**Comment by AlvaroRaul7** [comment]
Thanks @sepiatone will fix it
