### ISSUE TITLE
DOC: How to use stream output while calling batch

### ISSUE THREAD

**Issue by Lufffya** [langchain-ai/langchain#19944]
### Checklist

- [x] I added a very descriptive title to this issue.
- [x] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

![image](https://github.com/langchain-ai/langchain/assets/49063302/97f681db-b16d-492f-8201-baa4e6cd9dc4)

Currently, calling batch will output the results all at once.
How can I obtain streaming output while calling batch?
For example, my input has 10 lines, and each time I get the first few words in the 10 lines 
until each line is completed.

**Comment by eyurtsev** [comment]
Cannot be done right now and not planned to be supported. If you need to stream from multiple inputs, the way to do it is to manage the tasks or threads yourself.
