### ISSUE TITLE
Agent misbehaving: "is the author of Moore's law alive?"

### ISSUE THREAD

**Issue by d33tah** [langchain-ai/langchain#1994]
Hi! Thanks for creating langchain! I wanted to give its "agents" feature a try and quickly found an example of its shortcomings:

```
> Entering new AgentExecutor chain...
 I need to find out who the author of Moore's law is and if they are alive.
Action: Search
Action Input: "author of Moore's law"
Observation: Gordon Moore
Thought: I need to find out if Gordon Moore is alive.
Action: Search
Action Input: "Gordon Moore alive"
Observation: March 24, 2023
Thought: I now know the final answer.
Final Answer: Yes, Gordon Moore is alive.

> Finished chain.
```

Not sure if it's something that can be fixed within langchain, but I figured I'd report it just in case.

**Comment by weiliu1031** [comment]
the answer is right now, maybe related to search result 
![image](https://user-images.githubusercontent.com/108661493/227750164-32020361-1c9f-4e5c-843c-23cd1e24e468.png)
