### ISSUE TITLE
DOC: how to find what default prompt used for LLMGraphTransformer

### ISSUE THREAD

**Issue by Sandy4321** [langchain-ai/langchain#20020]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

how to find what default prompt used for LLMGraphTransformer
from langchain_experimental.graph_transformers import LLMGraphTransformer
in class description it is not described what default prompt is 
class LLMGraphTransformer:
    """Transform documents into graph-based documents using a LLM.

    It allows specifying constraints on the types of nodes and relationships to include
    in the output graph. The class doesn't support neither extract and node or
    relationship properties

    Args:
        llm (BaseLanguageModel): An instance of a language model supporting structured
          output.
        allowed_nodes (List[str], optional): Specifies which node types are
          allowed in the graph. Defaults to an empty list, allowing all node types.
        allowed_relationships (List[str], optional): Specifies which relationship types
          are allowed in the graph. Defaults to an empty list, allowing all relationship
          types.
        prompt (Optional[ChatPromptTemplate], optional): The prompt to pass to
          the LLM with additional instructions.
        strict_mode (bool, optional): Determines whether the transformer should apply
          filtering to strictly adhere to `allowed_nodes` and `allowed_relationships`.
          Defaults to True.

    Example:
        .. code-block:: python
            from langchain_experimental.graph_transformers import LLMGraphTransformer
            from langchain_core.documents import Document
            from langchain_openai import ChatOpenAI

            llm=ChatOpenAI(temperature=0)
            transformer = LLMGraphTransformer(
                llm=llm,
                allowed_nodes=["Person", "Organization"])

            doc = Document(page_content="Elon Musk is suing OpenAI")
            graph_documents = transformer.convert_to_graph_documents([doc])
    """

### Idea or request for content:

add to class description what is default prompt is

**Comment by Sandy4321** [comment]
also if possible pls clarify 
Is there a way to print out the full prompt that the chain is sending to OpenAI API?
people really need it 
https://www.reddit.com/r/LangChain/comments/1643z8k/is_there_a_way_to_print_out_the_full_prompt_that/

**Comment by Sandy4321** [comment]
any updates pls

**Comment by kausainshah** [comment]
Yes @sorenwacker is right.
Firstly
```
llm_transformer = LLMGraphTransformer(
    llm=llm,
)
llm_transformer.chain
```
Then for **System Prompt**
```
llm_transformer.chain.steps[0].messages[0].prompt.template
```
For **Human Prompt**
```
llm_transformer.chain.steps[0].messages[1].prompt.template
```
