### ISSUE TITLE
feat: parquet file support for SQL agent

### ISSUE THREAD

**Issue by vinliao** [langchain-ai/langchain#2002]
I'd like to run query against `parquet` files with `duckdb`. I see some `duckdb` stuffs on the docs when I search it up, also there's this PR: https://github.com/hwchase17/langchain/pull/1991, which seems to be a nice addition. What are the missing pieces to make this work?

One workaround I've found is turning the `parquet` files into a SQLite db, make an agent out of it, then proceed from there.

**Comment by morsamatias** [comment]
Can you please tell more about how to do the workaround?

**Comment by vinliao** [comment]
Load the parquet data to SQLite then use the SQLite agent.
