### ISSUE TITLE
Standardized model init arg names

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#20085]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

There's some discrepancies in the init args different models use to set the same params. It'd be a much nicer UX if common params could be set with a common set of init args

Suggesting that if a param in this list is present in a model integration, the below name should either be the actual attribute name or an init arg that can be used to set the attribute:

```python
model: str  # model name
api_key: str  # api key
temperature: float  # temperature sampling
timeout: ...  # request timeout
max_tokens: int  # max tokens
stop: ...  # stop sequences
max_retries: int  # max num retries
base_url: str # base URL to send requests to
```

Importantly we should also use the above init args in the docs

**Comment by baskaryan** [comment]
> Do we need to refactor every llm?

Ideally yes but we can do so incrementally, doesn't need to be all at once

**Comment by liugddx** [comment]
> > Do we need to refactor every llm?
> 
> 
> 
> Ideally yes but we can do so incrementally, doesn't need to be all at once

I see.

**Comment by sepiatone** [comment]
@baskaryan

Do you think it's worth to set the above names as the actual attribute name (and have an alias for the current one)? eg., for OpenAI we have 
```
param openai_api_key: Optional[SecretStr] = None (alias 'api_key')
```

which could be changed to
```
param api_key: Optional[SecretStr] = None (alias 'openai_api_key')
```

This will bring a common look and feel to the API references since sphinx(I think) arranges them in alphabetical order.

**Comment by sepiatone** [comment]
Also perhaps `base_url` -

Cohere
```
param base_url: Optional[str] = None
```
Anthropic
```
param anthropic_api_url: str = 'https://api.anthropic.com'
```
OpenAI
```
param openai_api_base: Optional[str] = None (alias 'base_url')
```

**Comment by liugddx** [comment]
> @baskaryan @liugddx
> 
> Do you think it's worth to set the above names as the actual attribute name (and have an alias for the current one)? eg., for OpenAI we have
> 
> ```
> param openai_api_key: Optional[SecretStr] = None (alias 'api_key')
> ```
> 
> which could be changed to
> 
> ```
> param api_key: Optional[SecretStr] = None (alias 'openai_api_key')
> ```
> 
> This will bring a common look and feel to the API references since sphinx(I think) arranges them in alphabetical order.

We need to be compatible, we try not to modify the original code.

**Comment by baskaryan** [comment]
> @baskaryan @liugddx
> 
> Do you think it's worth to set the above names as the actual attribute name (and have an alias for the current one)? eg., for OpenAI we have
> 
> ```
> param openai_api_key: Optional[SecretStr] = None (alias 'api_key')
> ```
> 
> which could be changed to
> 
> ```
> param api_key: Optional[SecretStr] = None (alias 'openai_api_key')
> ```
> 
> This will bring a common look and feel to the API references since sphinx(I think) arranges them in alphabetical order.

issue with this is it's a breaking change (unless we add some explicit properties) since the field name is the actual attribute by which the param is accessible. so if you switched got eg openai then `ChatOpenAI.openai_api_key` would stop working

**Comment by sepiatone** [comment]
> issue with this is it's a breaking change (unless we add some extra explicit properties) since the field name is the actual attribute by which the param is accessible. so if you switched eg openai then `ChatOpenAI.openai_api_key` would stop working

yes, you're right, should've put in some more thought

**Comment by sepiatone** [comment]
@baskaryan is there any plan to make this change from 0.1 to 0.2? also how is this going to be enforced going forwards (perhaps through the standard tests that @efriis is preparing?)

**Comment by sepiatone** [comment]
@baskaryan the `invoke` method has a `stop` parameter, so perhaps `stop_sequences` in the init args to the model should also be named as `stop`?
