### ISSUE TITLE
DOC: missing backtick around RunnablePassthrough on LCEL getting started

### ISSUE THREAD

**Issue by akshay-bharadva** [langchain-ai/langchain#20094]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

While reading and learning from the [LCEL - Getting Started](https://python.langchain.com/docs/expression_language/get_started/#rag-search-example) docs, I found one minor issue in the documentation.

In RAG Search Example, ` (backtick) is missing around the keyword RunnablePassthrough - [GitHub Code](https://github.com/langchain-ai/langchain/blob/de496062b3e740aed2c7097424749d1145e4aaab/docs/docs/expression_language/get_started.ipynb#L443).

Solution:
RunnablePassthrough -> `RunnablePassthrough`

**Comment by eyurtsev** [comment]
merged
