### ISSUE TITLE
langchain_openai.chat_models.base.ChatOpenAI[source] bind_tools.tool_choice="auto" is not working.

### ISSUE THREAD

**Issue by dbruner23** [langchain-ai/langchain#20103]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature = 0)
    llm_with_tools = llm.bind_tools(
        tools=tools,
        tool_choice="auto",
    )
    
    tools = [
    {
        "type": "function",
        "function": {
            "name": "answer_queries_with_citations",
            "description": "useful for answering questions about article or document content.",
            "parameters": {},
            "required": [],
        }
    },
    {
        "type": "function",
        "function": {
            "name": "miscellaneous_question_answerer",
            "description": "useful for answering miscellaneous questions.",
            "parameters": {},
            "required": [],
        }
    },
    {
        "type": "function",
        "function": {
            "name": "summarize_document",
            "description": "useful when very specifically asked for a summary of the document.",
            "parameters": {},
            "required": [],
        }
    }
] 

### Error Message and Stack Trace (if applicable)

[2024-04-06 09:55:56,359] ERROR in app: Exception on /docquery [POST]
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/render/project/src/app.py", line 108, in test
    llm_with_tools = llm.bind_tools(
                     ^^^^^^^^^^^^^^^
  File "/opt/render/project/src/.venv/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 746, in bind_tools
    raise ValueError(
ValueError: When specifying `tool_choice`, you must provide exactly one tool. Received 3 tools.

### Description

I'm trying to let chatgpt decide between 3 custom functions by setting tool_choice equal to "auto" (as per the documentation), but it is falling into the error block for when the length of the functions list is != 1. This means the "auto" setting by which the ai chooses from more than 1 function is unreachable.

Interestingly it works fine in my local environment in which I installed the libraries several weeks ago, but not in my cloud environment deployed today. I suspect it may have been a recent breaking change. Thanks guys, appreciate any help on this! 

### System Info

developed on mac OS, deployed to Render web service. 
Python 3.9.13

**Comment by spike-spiegel-21** [comment]
Please update your packages.

**Comment by tim-watcha** [comment]
When we set the openai api's tool_choice as 'auto' they pick tool from one or more tools.

But the implementation here raises error when there are more than one tool [link](https://github.com/langchain-ai/langchain/blob/cd4c54282ae25f5435dd09f44d3e5eb8bb2ef994/libs/partners/openai/langchain_openai/chat_models/base.py#L789)

I think it should be fixed

**Comment by tim-watcha** [comment]
Oh it is updated
