### ISSUE TITLE
DOC: <Please write a comprehensive title after the 'DOC: ' prefix>TypeError: 'FAISS' object is not callable Traceback: File "C:\Users\Jashu\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script     exec(code, module.__dict__) File "C:\Medi_LLM\Llama-2-7B-Chat-GGML\app.py", line 34, in <module>     retriever = vector_store(search_kwargs=["k: 2"]),                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by jashu9142** [langchain-ai/langchain#20112]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

TypeError: 'FAISS' object is not callable
Traceback:
File "C:\Users\Jashu\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
File "C:\Medi_LLM\Llama-2-7B-Chat-GGML\app.py", line 34, in <module>
    retriever = vector_store(search_kwargs=["k: 2"]),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by eyurtsev** [comment]
Not reproducible -- please follow instructions to file an issue properly
