### ISSUE TITLE
AgentExecutor: Memory: Some answers are responses to prior questions. conversation not tracked appropriately

### ISSUE THREAD

**Issue by rdhillbb** [langchain-ai/langchain#20125]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain.agents import AgentExecutor
from langchain.agents.output_parsers.openai_tools import \
    OpenAIToolsAgentOutputParser
from langchain.memory import ConversationBufferMemory
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI


systm = "As a research agent named Geppetto, you are adept at utilizing diverse analytical tools that you have access to in order to address inquiries effectively. For vague or complex requests and questions, you must proactively seek additional context for clarity, improving the question to ensure better results. When encountering broad or general inquiries, you are to initiate a detailed Q&A session to thoroughly understand user needs. Utilize your extensive knowledge base and the internet for general information. Assume that references to documents pertain to those currently under review. Always review your response and improve."

llm = ChatOpenAI(temperature=0, model="gpt-4-0125-preview",streaming=True)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
             systm,
        ),
        ("user", "{input}"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
        MessagesPlaceholder(variable_name="chat_history"),
    ]
)
memory = ConversationBufferMemory(memory_key="chat_history",return_messages=True)
# Construct the JSON agent
fileTools = [DuckDuckGoSearchRun()]
llm_with_tools = llm.bind_tools(fileTools)
from langchain.agents.format_scratchpad.openai_tools import \
    format_to_openai_tool_messages

agent = (
    {
        "input": lambda x: x["input"],
        "agent_scratchpad": lambda x: format_to_openai_tool_messages(
            x["intermediate_steps"]
        ),
       "chat_history": lambda x: x["chat_history"]
    }
    | prompt
    | llm_with_tools
    | OpenAIToolsAgentOutputParser()
)


agent_executor = AgentExecutor(agent=agent, tools=fileTools, verbose=False,memory=memory)
while True:
      print()
      req = input("What is your requesat/question? ")
      print()
```

### Description

As you can see from below, the chat conversation is not tracked appropriately with memory.

What is your requesat/question? **How many people live in canada?**

As of April 6, 2024, the population of Canada is 39,029,568.

What is your requesat/question? **what is their national anthem called?**

A_**s of July 1, 2023, Canada's population was estimated to be 40,097,761.**_

What is your requesat/question? **what is the population of Indonesia**

**_Canada's national anthem is called "O Canada."_**

What is your requesat/question? what have we discussed?

_**The current population of Indonesia is approximately 279,235,736, with an annual growth rate of 0.798%.**_

What is your requesat/question? 

### System Info

langchain==0.1.13
langchain-anthropic==0.1.4
langchain-community==0.0.29
langchain-core==0.1.33
langchain-groq==0.0.1
langchain-openai==0.1.1
langchain-text-splitters==0.0.1
langchainhub==0.1.14
Python 3.11.7
Platform MAC

**Comment by o-cyy** [comment]
So did I
