### ISSUE TITLE
how to get openai usage through code

### ISSUE THREAD

**Issue by jyoti194** [langchain-ai/langchain#20139]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

nil

### Description

is there any way to get the Openai API key usage and balance through langchain in python code?

### System Info

python: 3.11
langchain: latest

**Comment by jyoti194** [comment]
@dosubot

**Comment by deepak-hl** [comment]
@jyoti194 We can count the number of tokens used per query through langchain
from langchain.callbacks import get_openai_callback

def count_tokens(chain, query):
    with get_openai_callback() as cb:
        result = chain.run(query)
        print(f'Spent a total of {cb.total_tokens} tokens')

    return result

**Comment by eyurtsev** [comment]
For usage questions please use Q&A discussions rather than issues.
