### ISSUE TITLE
Error raised in utils.py get_prompt_input_key when AgentExecutor.run verbose=True

### ISSUE THREAD

**Issue by bseddon** [langchain-ai/langchain#2013]
When verbose=True and the agent executor is run, then in get_prompt_input_key() an error is raised:

```python
raise ValueError(f"One input key expected got {prompt_input_keys}")
```

This is because there are two entries [verbose, input] not just one [input].  It may be that setting verbose=True is not relevant.  However, if it is, then a possible solution is to change utils.py line 10:

```python
    if len(prompt_input_keys) != 1:
```
to 

```python
    if ~len(prompt_input_keys) in [1,2]:
```

**Comment by JayZeeDesign** [comment]
thanks for the tip, is there a PR for this fix already? got the same error when turn on memory and passing 2 variables, the above works

**Comment by abhijeethp** [comment]
I believe the solution is not to allow multiple input keys, but rather specify which is the correct input key by passing the "input_key" arg into the memory object. 
Let me try to make the error message more clear
