### ISSUE TITLE
Parsing of generated SPARQL via langchain rdflib always gives "pyparsing.exceptions.ParseException"

### ISSUE THREAD

**Issue by harshpundhir** [langchain-ai/langchain#20150]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

the following code:

```
metaqa_path = pathlib.Path(__file__).parent.absolute() / 'mydata' / 'metaQA'
metaqa_rdf = metaqa_path / 'knowledge_graph.rdf'
metaqa_ttl = metaqa_path / 'kb_wo_parse.ttl'

graph = RdfGraph(
    source_file=str(metaqa_ttl),
    standard="rdf",
)

chain = GraphSparqlQAChain.from_llm(
    ChatOpenAI(temperature=0), graph=graph, verbose=True
)

print(chain.run(r'which movies starred the actor Gert Fröbe'))
```

### Error Message and Stack Trace (if applicable)

 line 1200, in parse_string    
raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected {SelectQuery | ConstructQuery | DescribeQuery | AskQuery}, found '`'  (at char 0), (line:1, col:1)

### Description

- It should be eliminitaing the ``` (triple quotes) generated by the LLM, that cannot be parsed by RDFLIB.
- Should generate
```
PREFIX metaQAKB: <http://metaQAKB.org/>
SELECT ?movie
WHERE {
    ?movie metaQAKB:starred_actors "Gert Fröbe" .
}
```

Instead of 
```
```
PREFIX metaQAKB: <http://metaQAKB.org/>
SELECT ?movie
WHERE {
    ?movie metaQAKB:starred_actors "Gert Fröbe" .
}
```
```

### System Info

langchain-0.1.14
rdflib-7.0.0
langchain-openai-0.1.1

**Comment by harshpundhir** [comment]
Adding this in the langchain sourcecode
\venv\Lib\site-packages\langchain\chains\graph_qa\sparql.py

generated_sparql = generated_sparql.strip()[3:-3] -> eliminates the first and last set of the triple quotes and makes SPARQL parsable

**Comment by hsekol-hub** [comment]
Will this bug be merged into master branch anytime soon?
