### ISSUE TITLE
Open Assistant by LAION-AI

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#2015]
It would be great to see integration with [OpenAssistant](https://github.com/LAION-AI/Open-Assistant) by @LAION-AI, which aims to become the [largest and most open alternative to ChatGPT](https://projects.laion.ai/Open-Assistant/blog/we-need-your-help#:~:text=largest%20and%20most%20open%20alternative%20to%20ChatGPT).

> OpenAssistant is a chat-based assistant that understands tasks, can interact with third-party systems, and retrieve information dynamically to do so

Here's the [Open Assistant architecture](https://projects.laion.ai/Open-Assistant/blog/2023-02-11-architecture):

<img width="504" alt="screen" src="https://user-images.githubusercontent.com/6625584/227813941-3c77f348-8874-409a-9e8f-2ee1604a8611.png">

**Comment by Lyfenne** [comment]
I believe support for langchain was already confirmed, i'll try to find the source.

**Comment by antonkulaga** [comment]
Yes, it will be super-useful!
