### ISSUE TITLE
Updating the Qdrant index with new documents raises error

### ISSUE THREAD

**Issue by mallahyari** [langchain-ai/langchain#2016]
If you want to create a Qdrant index and keep adding documents (i.e. adding new documents to existing qdrant), when your embedding is sentence transformers `qdrant_index.add_documents(docs)` gives error.

Because the `embedding_function` which is `model.encode()` is returning either `numpy` or `tensor` array and has to be converted to `list[float]`. Therefore, this line

`vectors=[self.embedding_function(text) for text in texts]`

 needs to updated to:

`vectors=[self.embedding_function(text).tolist() for text in texts]`

To allow updating the collection.

https://github.com/hwchase17/langchain/blob/b83e8265102514d1722b2fb1aad29763c5cad62a/langchain/vectorstores/qdrant.py#L83

**Comment by gulatisukaran** [comment]
Hey @mallahyari please assign this to me :)

**Comment by wawaks** [comment]
In the case of OpenAIEmbeddings I get tuple (vectors,). So I had to change to
`
vectors=[self.embedding_function(text)[0] for text in texts]
`

**Comment by mallahyari** [comment]
Yes the issue is resolved later in the updates in Langchain. So I am going to close the issue!
