### ISSUE TITLE
RFC: add `bind_tools` to BaseLanguageModel

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#20178]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Only some function/tool-calling models have a bind_tools method. Others have a bind_functions method, and others still don't have any special bind methods. This is in part due to different api parameter names, in part due to differences in model parallel tool/function calling abilities, in part because we were waiting to see if function/tool-calling would become widespread.

It seems like it has become widespread and the name we're converging on for parallel function/tool calling (which is the more common and more generic interface than single function calling) is just "tool calling".  So proposing that we standardize the bind_tools interface and have all capable models implement it.

Standard interface would be something like 

```python
class BaseLanguageModel(...):

      def bind_tools(
        self,
        tools: Sequence[Union[Dict[str, Any], Type[BaseModel], Callable, BaseTool]],
        **kwargs: Any,
    ) -> Runnable[LanguageModelInput, BaseMessage]:
        ...
```

**Comment by liugddx** [comment]
At present, only the interface of some llms is supported, so most models cannot implement this method, right?

**Comment by lucas-tucker** [comment]
I am working on this. It seems that while OpenAI and Anthropic tool conversion methods (`convert_to_openai_tool` and `convert_to_anthropic_tool`) differ in that the OpenAI tool has a "type" key, and its "name", "description" and "parameters" (same as Anthropic's "input_schema") keys are nested under a "function" key. For example, this is an OpenAI tool:

`{'type': 'function', 'function': {'name': 'get_time', 'description': 'Returns the current date and time', 'parameters': {'type': 'object', 'properties': {}}}}`

and this is an Anthropic tool (for the same function get_time):

`{'name': 'get_time', 'description': 'Returns the current date and time', 'input_schema': {'type': 'object', 'properties': {}}}
`

Would you suggest implementing a tool conversion method in BaseLanguageModel and simply lengthening the tool to include all those keys from various other tools? Something else? Note as well that other models such as ChatGroq and ChatHuggingFace use OpenAI's tool conversion method.

**Comment by nnWhisperer** [comment]
hello, will you provide a bind_tools for LLMs that don't have tools support? In all the ones that support, currently bind_tools return something like super().bind(tools=formatted_tools, **kwargs). In models that don't support function calling/tool use(meta's new llama3.1 405b etc), I guess a bind_tools would be handy that instructs the model accordingly.
