### ISSUE TITLE
JsonOutputParser returns empty json when text ends with "\"

### ISSUE THREAD

**Issue by KiewanVillatel** [langchain-ai/langchain#20204]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Code

```
from langchain.schema import Generation
from langchain_core.output_parsers import JsonOutputParser

print(JsonOutputParser().parse_result([Generation(text='{"key":"value\\')]))
```

Actual result:

```{}```

Expected result: not sure

### Description

This problem occurred when I was streaming a JSON response containing new lines "\n". The chunk stopped right after the backslash, leading to an empty json after the parser.

### System Info

langchain==0.1.14
langchain-core==0.1.40

plaform: linux

Python 3.11.0rc1

**Comment by liugddx** [comment]
Let me see.
