### ISSUE TITLE
#error: ValidationError: 1 validation error for SQLDatabaseToolkit

### ISSUE THREAD

**Issue by ankitk074** [langchain-ai/langchain#20213]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

model = genai.GenerativeModel(model_name='gemini-pro')
#llm = OpenAI(temperature=0)
mydb = SQLDatabase.from_uri('sqlite:///test.db')

llm = {'model': model}
toolkit=SQLDatabaseToolkit(db=mydb)
agent_executer = create_sql_agent(
llm=llm,
toolkit=toolkit,
handle_parsing_error=True,
verbose=True
)

### Description

Getting same issue ,
in my case issue is not getting resolved , is it because i am using gemini or different model from OpenAI, even i have followed all the recomendations from the chat , but still it is same, how to resolve the same issue using gemini pro model?
genai.configure(api_key='my Api key')

### System Info

import streamlit as st
import pandas as pd
import google.generativeai as genai
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain.agents.agent_types import AgentType
from langchain.sql_database import SQLDatabase

i have used above imoorts

**Comment by mkennedy-clgx** [comment]
I am having the same issue using ```toolkit = SQLDatabaseToolkit(db=db, llm=GenerativeModel(
            "gemini-1.0-pro",
            generation_config={"temperature": 0},
        ))```

**Comment by Oak-Techie-Git** [comment]
I am facing the same issue, Is it supported or you guys are working on the updates?
