### ISSUE TITLE
How to use Serp only for current events related searches and use GPT for regular info

### ISSUE THREAD

**Issue by Anil-matcha** [langchain-ai/langchain#2023]
I am building an agent which answer user questions and I have plugged it with two tool, the regular llm and search tool like this

llm = OpenAI(temperature=0)
search = GoogleSerperAPIWrapper()

template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])

llm_chain = LLMChain(llm=llm, prompt=prompt, verbose=True)
tools = [
    Tool(
        name = "Search",
        func=search.run,
        description="useful for when you need to answer questions about current events."
    ),
    Tool(
        name="LLM",
        func=llm_chain.run,
        description="useful for when you need to answer questions about anything in general."
    )
]
mrkl = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)

Now when I ask it a general question like "Who is Sachin", it still is trying to invoke the search action although the LLM can answer that question as it is not based on a recent event. How to make sure LLM answers any questions except questions on recent events to reduce the SERP usage ?

**Comment by gambastyle** [comment]
I tried telling it '''You do not have access to this tool by yourself. You can only be allowed to use this tool when the human message specifically says "search online".
still doesn't work..

**Comment by Anil-matcha** [comment]
@gambastyle Tried different approaches by asking it to give priority to LLM over Serp but it always goes to Serp api first. Not sure how to deal with this

**Comment by Anil-matcha** [comment]
@hkaraoguz Thanks for the support, this will definitely help as a short term hack. Meanwhile direct support for this will be great to have

**Comment by oleg-yaroshevskiy** [comment]
Hey. Have anyone one succeeded here?

**Comment by crystal0112** [comment]
how about initialize two tools (search wrapper, and completion model with chat completiion) and  create template to distinguish between these tools? 
i am also trying to figure out this problem

**Comment by robertsw22** [comment]
Just prepend the question with "In general," I found that it will prioritize the LLM but resort to search when needed. @Anil-matcha

**Comment by amrynsky** [comment]
Does anyone have a good solution for it? I tried to use it with `ChatOpenAI` and forced to use `llm_chain` over search but it is causing some "endless loop" for questions like "give me some productivity tips".
