### ISSUE TITLE
Intuition for selecting optimal chunk_size and chunk_overlap for RecursiveCharacterTextSplitter

### ISSUE THREAD

**Issue by thisisandreeeee** [langchain-ai/langchain#2026]
I am using `RecursiveCharacterTextSplitter` to split my documents for ingestion into a vector db. What is the intuition for selecting optimal chunk parameters? 

It seems to me that chunk_size influences the size of documents being retrieved. Does that mean I should select the largest possible chunk_size to ensure maximum context retrieved? 

What about chunk_overlap? This seems like a parameter that can be arbitrarily set i.e. select something that's not too big, not too small. Is that the right understanding?

**Comment by pevogam** [comment]
I generally think it would be great to improve the documentation a bit in this direction by including the exact units. For instance looking at this code
```python
splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n"], chunk_size=256, chunk_overlap=0)
docs = splitter.split_documents(documents)
print(f"Number of tokens of first document: {llm.get_num_tokens(docs[0].page_content)}")
# -> Number of tokens of first document: 38

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
print(f"Maximum embedded sequence length: {embeddings.client.get_max_seq_length()}")
# -> Maximum embedded sequence length: 256
```
I have ssumed that `chunk_size` is in tokens, the maximum sequence length is in tokens, and I could match the two to avoid truncating text, yet I cannot easily confirm this is correct understanding anywhere in the documentation and the included outputs end up with tiny token sizes like 38 making me wonder if chunk_size does not mean characters or something else.

**Comment by gshubham533** [comment]
Thanks for the explanation @mofahad @thisisandreeeee 

I was also looking for an explaination of chunk_size and chunk_overlap **kwargs in split_documents(*args) function.

Here's modified explanation that might help you understand.

Suppose document has a text that you have loaded intro  a variable.

```
# text.txt = "Madam Speaker, Madam Vice President, our First Lady and Second Gentleman. Members of Congress and of Congress and the Cabinet. Justices of the Supreme Court. My fellow Americans."

from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

filename_path = 'test.txt'
loader = TextLoader(filename_path)
doc = loader.load()
print (f"You have {len(doc)} document")
print (f"You have {len(doc[0].page_content)} characters in that document")

text_splitter = RecursiveCharacterTextSplitter(chunk_size=40, chunk_overlap=10)
docs = text_splitter.split_documents(doc)
for i in docs:
    page_con = i.page_content
    print(len(page_con))
    print(page_con)
```
Ouput:  
You have 1 document
You have 178 characters in that document
6
40
Madam Speaker, Madam Vice President, our
36
our First Lady and Second Gentleman.
39
Members of Congress and of Congress and
32
and the Cabinet. Justices of the
31
of the Supreme Court. My fellow
20
My fellow Americans.


Notice in the output above that chunk_size has created chunks of almost 40 characters and chuk_overlap had used almost 10 charcters of same words at the End and Start of next chunk

Chunk1: Madam Speaker, Madam Vice President, our
Chunk2: our First Lady and Second Gentleman.

In above 2 chunks "our" has been used at the End of Chunk1 and at the Start of chunk2 to maintain the meaning of all chunks

**Comment by migalv** [comment]
chunk_size for the RecursiveCharacterTextSplitter is the maximum length of the text that can be split. The token size of that chunk can vary depending on its content, but an eyeball estimate is usually 750 tokens for 1000 words. 

If you want to split your text by tokens you can use other text splitters like `from langchain.text_splitter import TokenTextSplitter`

```python
text_splitter = TokenTextSplitter(chunk_size=100, chunk_overlap=20)
texts = text_splitter.split_text(state_of_the_union)
llm = OpenAI(temperature=0)
num_tokens = llm.get_num_tokens(texts[10])
print(f'Token length = {num_tokens} tokens')
```

For this piece of code, you would get Token length = 100. As you can see the `chunk_overlap` does not add to the max chunk size, so you are certain that your docs are no longer than 100 tokens. 

Be sure to check the [Text splitters](https://python.langchain.com/en/latest/modules/indexes/text_splitters.html) docs to see what text splitter fits your needs.

**Comment by thiswillbeyourgithub** [comment]
Hi,

Can anyone tell me what happens if I use a token text splitter to have documents of 500 tokens long but then use a hugging face embedder that only has 256 tokens of "max sequence length"?

My intuition is that the embedder silently ignores all tokens after 256. In which cas this makes the embeddings practically useless.

Looking at [the list of pretrained sentence transformers](https://www.sbert.net/docs/pretrained_models.html) I see that the multilingual models only have 126 max length tokens! That would explain why my search result are so bad...

Can anyone explain to me what happens if the embedders accepts less tokens than the splitter?

Thanks!

**Comment by vowelparrot** [comment]
Sentence Transformers apply a truncation strategy. I believe the default is to take the first N tokens and use that, though it can be configured. Sometimes this can be enough (e.g., for news articles or other content where information is frontloaded). Other times, it warrants smaller chunk sizes or averaging / using multiple embeddings.

**Comment by thiswillbeyourgithub** [comment]
I think this is a major drawback to using embeddings and should be mentionned explicitly in the langchain examples.

My reasonning is that quite a few people are interested in langchain and such after reading about how you can do qa with documents or library of documents. Having such a small limitation to input sizes (128 for some multilingual models!) is a very hard constraint, and it happens silently!

Is it doable to implement averaging of embeddings if the max length size if below the input document? I read a few issues of the sentence-transformers github that mentionned it worked okay. This would at least limit the damage IMHO.

I get it that it's obvious for some that most embedding models have short sequence length but it's surprisingly rarely mentionned so to me it is an **unexpected behavior** for langchain (as a framework) to not take care of at least averaging the embeddings. For me the promise of langchain is to smoothly plug lots of tools together and I certainly didn't expect that **most input text would be ignored by the retriever** (as the default text splitter value are way higher than embeddings lengths).

Or is there something I'm missing?

**Comment by SID262000** [comment]
Looks like an ever ongoing discussion without any proper mention in the official documentation which is leading to a lot of confusion.

**Comment by thiswillbeyourgithub** [comment]
(copying my message from [there](https://github.com/simonw/llm-sentence-transformers/issues/8#issuecomment-1732618592) )

I'm sharing my own 'rolling' sbert script to avoid clipping the sentences. It's seemingly functionnal but not very elegent, a class would be better of course but I just hope it helps someone : 

```
from sentence_transformers import SentenceTransformer


model = SentenceTransformer("all-mpnet-base-v2")

# sbert silently crops any token above the max_seq_length,
# so we do a windowing embedding then sum. The normalization happens
# afterwards.
def encode_sentences(sentences):
    n = model.max_seq_length  # max length supported by the model
    n23 = (n * 2) // 3  # overlap each 2/3 of n

    add_sent = []  # split long sentences go there
    add_sent_idx = []  # indices to keep track of sub sentences

    # check the length of each sentence
    for i, s in enumerate(sentences):
        # skip if the sentence is short enough
        length = len(model.tokenizer.encode(s))
        if length <= n:
            continue

        # otherwise, split the sentence at regular interval
        # then do the embedding of each
        # and finally add those sub embeddings together
        sub_sentences = []
        j = 1
        while length >= n23 * j:
            sub_sentences.append(s[n23 * j: n23 * j + n])
            j += 1

        # remove empty text just in case
        if "" in sub_sentences:
            while "" in sub_sentences:
                sub_sentences.remove("")
        add_sent.extend(sub_sentences)
        add_sent_idx.extend([i] * len(sub_sentences))


    # sanity check that sentences contains only valid lengths
    assert sum([
            len(model.tokenizer.encode(s)) > model.max_seq_length
            for s in sentences + add_sent
            ]) == 0, (
            "Some sentences are too long for the "
            "transformer and are cropped. The rolling average "
            "failed apparently.")

    # note that normalization is turned off, the idea is to avoid cascading
    # approximations by summing normalized embeddings and instead normalize
    # at the end
    vectors = cached_encoder(
            sentences=sentences + add_sent,
            show_progress_bar=True,
            output_value="sentence_embedding",
            convert_to_numpy=True,
            normalize_embeddings=False,
            )

    if add_sent:  # reconstitute the vector
        # at the position of the original sentence (not split)
        # add the vectors of the corresponding sub_sentence
        # then return only the 'summed' section
        assert len(add_sent) == len(add_sent_idx), (
            "Invalid add_sent length")
        offset = len(sentences)
        for sid in list(set(add_sent_idx)):
            id_range = [i for i, j in enumerate(add_sent_idx) if j == sid]
            add_sent_vec = vectors[
                    offset + min(id_range): offset + max(id_range),:]
            vectors[sid] += add_sent_vec.sum(axis=0)
        return vectors[:offset]
    else:
        return vectors

```

**Comment by abusufyanvu** [comment]
I have total 78375 PDF files which contain a total of 121612 pages. please guide me what I should choose the chunk_size and chunk_overlap.

# Initialize the text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=?,
    chunk_overlap=?
    # separators=["\n\n", "\n", "\. ", " ", ""]
)

**Comment by Anushagudipati** [comment]
Im using openAi gpt-3.5-turbo model. Im trying to give json data of more than 15000 lines to the model(RAG).
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=2200, chunk_overlap=100)
    
 when I ask questions regarding the json data, for few questions the chunk_size=2000 is working fine i.e getting acuurate results,for few questions that chunk_size not working fine I have changed it to 2200 or 2500 then it is giving correct answers. But we won't give multiple chunk_sizes right?
 finally we need fix one chunk_size value.
 Can any one sort out this
