### ISSUE TITLE
DOC: JsonOutputParser does not mention that input is not validated against schema.

### ISSUE THREAD

**Issue by florianlaws** [langchain-ai/langchain#20266]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The documentation at https://python.langchain.com/docs/modules/model_io/output_parsers/types/json/
seems to imply that the generated output is validated against the Pydantic schema and only JSON objects that conform to the schema are returned.
However, as I understand the source code, this does not seem to be the case.

Please consider adding a note to the JSON parser documentation that one should use PydanticOutputParser, if validation against the schema is desired.

**Comment by liugddx** [comment]
Refer to https://python.langchain.com/docs/modules/model_io/output_parsers/types/pydantic/

**Comment by Essoz** [comment]
The JsonOutputParser class documentation explicitly states that the pydantic_object is used for validation... 

<img width="1232" height="502" alt="Image" src="https://github.com/user-attachments/assets/99b581cb-1cda-4621-807b-55e4c61eebf0" />

Just incredible...
