### ISSUE TITLE
Adding tools to ConversationalRetrievalChain.from_llm causes Pydantic error

### ISSUE THREAD

**Issue by NasserAAA** [langchain-ai/langchain#20276]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code: ''' tools = load_tools(["llm-math"],llm=llm)
    chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        tools=tools, '''

### Error Message and Stack Trace (if applicable)

causes this error: \venv\lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
tool
  extra fields not permitted (type=value_error.extra)

### Description

I'm trying to use tools with ConversationalRetrievalChain.from_llm and this error occurs pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalRetrievalChain
tool

### System Info

aiohttp==3.8.4
aiosignal==1.3.1
altair==5.0.1
anyio==3.7.0
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
beautifulsoup4==4.12.2
blinker==1.6.2
bs4==0.0.1
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
chromadb==0.3.26
click==8.1.3
clickhouse-connect==0.6.4
colorama==0.4.6
coloredlogs==15.0.1
cryptography==41.0.2
dataclasses-json==0.5.9
decorator==5.1.1
distro==1.9.0
dnspython==2.3.0
docopt==0.6.2
document-utils==1.8.1
duckdb==0.8.1
et-xmlfile==1.1.0
exceptiongroup==1.1.2
faiss-cpu==1.7.4
fastapi==0.99.1
filetype==1.2.0
flatbuffers==23.5.26
frozenlist==1.3.3
gitdb==4.0.10
GitPython==3.1.31
greenlet==2.0.2
h11==0.14.0
hnswlib==0.7.0
httpcore==1.0.3
httptools==0.5.0
httpx==0.26.0
humanfriendly==10.0
idna==3.4
importlib-metadata==6.7.0
Jinja2==3.1.2
joblib==1.3.1
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.17.3
langchain==0.1.15
langchain-community==0.0.32
langchain-core==0.1.41
langchain-experimental==0.0.47
langchain-text-splitters==0.0.1
langchainplus-sdk==0.0.20
langsmith==0.1.43
libmagic==1.0
loguru==0.7.0
lxml==4.9.3
lz4==4.3.2
Markdown==3.4.4
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
mdurl==0.1.2
monotonic==1.6
mpmath==1.3.0
msg-parser==1.2.0
multidict==6.0.4
mypy-extensions==1.0.0
nltk==3.8.1
numexpr==2.8.4
numpy==1.25.0
olefile==0.46
onnxruntime==1.15.1
openai==0.27.8
openapi-schema-pydantic==1.2.4
openpyxl==3.1.2
orjson==3.10.0
overrides==7.3.1
packaging==23.2
pandas==2.0.3
pdf2image==1.16.3
pdfminer.six==20221105
Pillow==9.5.0
pinecone-client==2.2.2
pipreqs==0.4.13
posthog==3.0.1
protobuf==4.23.3
pulsar-client==3.2.0
pyarrow==12.0.1
pycparser==2.21
pycryptodome==3.18.0
pydantic==1.10.10
pydeck==0.8.1b0
Pygments==2.15.1
Pympler==1.0.1
pypandoc==1.11
pypdf==3.12.0
pyreadline3==3.4.1
pyrsistent==0.19.3
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
python-magic==0.4.27
python-magic-bin==0.4.14
python-pptx==0.6.21
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
rich==13.4.2
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.5
SQLAlchemy==2.0.17
starlette==0.27.0
streamlit==1.24.0
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
tiktoken==0.4.0
tokenizers==0.13.3
toml==0.10.2
toolz==0.12.0
tornado==6.3.2
tqdm==4.65.0
typing-inspect==0.9.0
typing_extensions==4.9.0
tzdata==2023.3
tzlocal==4.3.1
unstructured==0.8.1
urllib3==2.0.3
uvicorn==0.22.0
validators==0.20.0
vectorhub==1.8.3
watchdog==3.0.0
watchfiles==0.19.0
websockets==11.0.3
win32-setctime==1.1.0
xlrd==2.0.1
XlsxWriter==3.1.2
yarg==0.1.9
yarl==1.9.2
zipp==3.15.0
zstandard==0.21.0

**Comment by liugddx** [comment]
Does ConversationalRetrievalChain have tools attribute?

**Comment by spike-spiegel-21** [comment]
ConversationalRetrievalChain does not have any tools attribute. Could you please specify your use case (with full code)?
