### ISSUE TITLE
PGVector filter $eq

### ISSUE THREAD

**Issue by demattosanthony** [langchain-ai/langchain#20293]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Code that doesn't work:

```
retriever = self.vector_store.as_retriever(search_kwargs={
        'k': 1, 
        'filter': {'portfolio_uri':{'$eq': params.portfolio_uri}}
      })
      docs = retriever.get_relevant_documents(query=query)
```

Code that works:

```
retriever = self.vector_store.as_retriever(search_kwargs={
        'k': limit, 
        'filter': {'portfolio_uri':{'$in': [params.portfolio_uri]}}
      })
      docs = retriever.get_relevant_documents(query=query)
```

### Error Message and Stack Trace (if applicable)

 File "/Users/anthonydemattos/syyclops/open-operator/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/anthonydemattos/syyclops/open-operator/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function jsonb_path_match(json, unknown, unknown) does not exist
LINE 3: ...2edf-c5b6-4a08-9a06-c841d8c6dab9'::uuid::UUID AND jsonb_path...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[SQL: SELECT langchain_pg_embedding.collection_id AS langchain_pg_embedding_collection_id, langchain_pg_embedding.embedding AS langchain_pg_embedding_embedding, langchain_pg_embedding.document AS langchain_pg_embedding_document, langchain_pg_embedding.cmetadata AS langchain_pg_embedding_cmetadata, langchain_pg_embedding.custom_id AS langchain_pg_embedding_custom_id, langchain_pg_embedding.uuid AS langchain_pg_embedding_uuid, langchain_pg_embedding.embedding <=> %(embedding_1)s AS distance 
FROM langchain_pg_embedding JOIN langchain_pg_collection ON langchain_pg_embedding.collection_id = langchain_pg_collection.uuid 
WHERE langchain_pg_embedding.collection_id = %(collection_id_1)s::UUID AND jsonb_path_match(langchain_pg_embedding.cmetadata, %(jsonb_path_match_1)s, %(jsonb_path_match_2)s) ORDER BY distance ASC 
 LIMIT %(param_1)s]
[parameters: {'embedding_1': '[-0.010107061089572959,-0.013629535476347075,-0.0012468165027500532,-0.024999106785678033,-0.03649423341900812,0.012025240109652443,-0.03317403857405 ... (32593 characters truncated) ... .024217885455325203,-0.029881744291334902,0.015178028787260737,-0.01019773838247912,-0.006612486799366736,-0.02557107296798936,-0.019600304222168217]', 'collection_id_1': UUID('622b2edf-c5b6-4a08-9a06-c841d8c6dab9'), 'jsonb_path_match_1': '$.portfolio_uri == $value', 'jsonb_path_match_2': '{"value": "https://syyclops.com/example"}', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)

### Description

I am trying to do a vector store similarity search with pg vector and provide a filter of the metadata. 

For some reason when i do $eq it doesn't work but if I do $in: [.. then it does work

### System Info

python -m langchain_core.sys_info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000
> Python Version:  3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]

Package Information
-------------------
> langchain_core: 0.1.41
> langchain: 0.1.12
> langchain_community: 0.0.32
> langsmith: 0.1.43
> langchain_openai: 0.1.2
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by eyurtsev** [comment]
Try this:  https://github.com/langchain-ai/langchain-postgres/

https://github.com/langchain-ai/langchain-postgres/blob/main/examples/vectorstore.ipynb

**Comment by eyurtsev** [comment]
For context, we're going to deprecate the pgvector the abstraction in `langchain_community` -- it's moved to langchain-postgres

**Comment by demattosanthony** [comment]
@eyurtsev thats working better thank you

**Comment by talhaFayyazfolio** [comment]
@eyurtsev  Hi do we have langchain js package for this ?
