### ISSUE TITLE
Not able to use gemini from langchain in kaggle

### ISSUE THREAD

**Issue by ankush-003** [langchain-ai/langchain#20317]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

![image](https://github.com/langchain-ai/langchain/assets/94037471/129119dd-172e-4160-a3c6-b980199f0bc7)

### Description

i am trying to use gemini model from langchain CHatGoogleGenerativeAi, but i am getting this error
```
'NoneType' object does not support item assignment (type=type_error)
```

### System Info

kaggle

**Comment by ankush-003** [comment]
> Did you use google api key ??

yeah i have set it as an environment variable

**Comment by gunjak** [comment]
I found some mistake in code so I have raised [issue ](https://github.com/langchain-ai/langchain-google/issues/158) .Soon it will be resolved.
