### ISSUE TITLE
Highly inconsistent output using PydanticOutputParser

### ISSUE THREAD

**Issue by abhishekc-bhs** [langchain-ai/langchain#20369]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

class AnalyzeResume(BaseModel):
    """As a professional HR agent that helps users analyze and generate a comprehensive report about the resume.\n
    Use the following pieces of context from a resume to answer the question at the end."""

    issues: list = Field(
        description="List down all issues detected in the resume with **title, description, solution format** with description & solution of atleast 600 words"
    )
    suggestions: list = Field(
        description="List down all suggestions to improve the resume in **title, description format** with description of atleast 600 words"
    )
    summary: str = Field(description="Summary of the of the resume.")
    negotiations: list = Field(
        description="List down all insightful points for resume negotiations in **title, description format** with description of atleast 600 words"
    )
    companies: list = Field(
        description="List down all Names and descriptions of the companies involved in the resume in **title, description format**"
    )

### Error Message and Stack Trace (if applicable)

![image](https://github.com/langchain-ai/langchain/assets/115447569/0149cc22-10a7-47b0-832b-b8427a0e4e33)

### Description

I want the output should be consistent, sometimes the output list is having data, sometimes just completely blank. Below is the prompt code I am using

```
resume_parser = PydanticOutputParser(pydantic_object=AnalyzeResume)

template = """
                As a professional HR agent that helps users analyze and generate a comprehensive report about the resume.\
                Use the following pieces of context from a resume to answer the question at the end.\
                \n
                {context}\n
                \n{format_instructions}\n
                Question: {question}
            """
    rag_prompt_custom = PromptTemplate(
    template=template,
    input_variables=["context", "question"],
    partial_variables={"format_instructions": resume_parser.get_format_instructions()},
)

chroma_client = chromadb.HttpClient(host="chromadb", port=8000)

document_analysis_client = DocumentAnalysisClient(
            endpoint=os.environ["AZURE_DI_SERVICE_ENDPOINT"],
            credential=AzureKeyCredential(os.environ["AZURE_DI_API_KEY"]),
            mode="page",
            analysis_features=["ocrHighResolution"],
        )
        loader = DocumentIntelligenceLoader(
            file_path=contract_obj.file_input.path, client=document_analysis_client, model="prebuilt-document"
        )
        documents = loader.load()

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=14500,
            chunk_overlap=100,
            add_start_index=True,
            strip_whitespace=True,
            separators=MARKDOWN_SEPARATORS,
        )
        docs = text_splitter.split_documents(documents)
collection_id = str(uuid.uuid4())

        chroma_db = Chroma.from_documents(docs, azure_embeddings, client=chroma_client, collection_name=collection_id)
        contract_obj.collection_id = collection_id
        contract_obj.save()

        vectorstore = Chroma(client=chroma_client, collection_name=collection_id, embedding_function=azure_embeddings)
        retriever = vectorstore.as_retriever()

rag_chain = {"context": retriever, "question": RunnablePassthrough()} | rag_prompt_custom | azure_llm

with get_openai_callback() as cb:
            result = rag_chain.invoke("Generate answers in provided format")
            total_rag_tokens = cb.total_tokens
```
Just point me to the issue, I will try my best to fix it. (Might be chroma or Azure OpenAI or the text splitter)

### System Info

langchain
langchain-community
langchain-core
langchain-google-genai==0.0.8
langchain-openai==0.0.5
langchainhub
langsmith
azure-ai-documentintelligence==1.0.0b1
azure-ai-formrecognizer==3.3.2
chroma-hnswlib==0.7.3
chromadb == 0.4.22

**Comment by eyurtsev** [comment]
Please review guidelines for extraction here: https://python.langchain.com/docs/use_cases/extraction/

**Comment by eyurtsev** [comment]
Closing this issue as this is not really a PydanticOutputParser issue, but has to do with the application that's written, the LLMs used etc etc.
