### ISSUE TITLE
create openai assistant object failed when I use AsyncOpenAI client

### ISSUE THREAD

**Issue by zkhCreator** [langchain-ai/langchain#20436]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
client = AsyncOpenAI(
    # Defaults to os.environ.get("OPENAI_API_KEY")
    # Otherwise use: api_key="Your_API_Key",
    api_key=settings.OPENAI_API_KEY,
)

async def acreate_assistant(**kwargs: Any, ):
    return await OpenAIAssistantRunnable.acreate_assistant(async_client=client, **kwargs)
```

when I run `await acreate_assistant()` it shows `Unexpected error occurred: OpenAIError - The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`

### Description

Here is the code of `client` property in `OpenAIAssistantRunnable`
```
    client: Any = Field(default_factory=_get_openai_client)
```
Because of using `AsyncClient`, the `client` value is None as default. So it will create by `_get_openai_client`.

```
class OpenAI(SyncAPIClient):
    def __init__(...):
        if api_key is None:
            api_key = os.environ.get("OPENAI_API_KEY")
        if api_key is None:
            raise OpenAIError(
                "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable"
            )
        self.api_key = api_key
```

but the `OpenAI` will check the `api_key` automaticlly.
So it will always failed when I use AsyncOpenAIClient to create the `OpenAIAssistantRunnable` object.

I don't know if it's Ok to remove the `default_factory` of `client`. If it's ok, I'll create a PR to fix this problem.

### System Info

```
langchain==0.1.16
langchain-community==0.0.32
langchain-core==0.1.42
langchain-openai==0.1.0
langchain-text-splitters==0.0.1
langsmith==0.1.31
```

**Comment by baskaryan** [comment]
does this work?
```python
async_client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY,)
client = OpenAI(api_key=settings.OPENAI_API_KEY,)

async def acreate_assistant(**kwargs: Any, ):
    return await OpenAIAssistantRunnable.acreate_assistant(async_client=client, client=client, **kwargs)
```

**Comment by zkhCreator** [comment]
maybe not, because OpenAI provide different client object for sync and async.
