### ISSUE TITLE
NotFoundError for OpenAI with gpt-3.5-turbo model

### ISSUE THREAD

**Issue by shashankdeshpande** [langchain-ai/langchain#20441]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Getting error for this code -

```python
from langchain_openai import OpenAI
llm = OpenAI(model='gpt-3.5-turbo', temperature=0, streaming=True)
llm('how are you?')
```

### Error Message and Stack Trace (if applicable)

NotFoundError: Error code: 404 - {'error': {'message': 'This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?', 'type': 'invalid_request_error', 'param': 'model', 'code': None}}

### Description

Getting above specified error when configuring `gpt-3.5-turbo` model with `OpenAI`
However, this model works as expected with `ChatOpenAI`

On the other hand, `gpt-3.5-turbo-instruct` model also works as expected with `OpenAI`, code is mentioned below -  
```python
from langchain_openai import OpenAI
llm = OpenAI(model='gpt-3.5-turbo-instruct',temperature=0, streaming=True)
llm('how are you?')
```
Here is the screenshot for reference - 
<img width="1193" alt="Screenshot 2024-04-15 at 12 02 51 AM" src="https://github.com/langchain-ai/langchain/assets/47742503/50cbe4de-9b94-4569-85d3-f92137aacbe4">

I believe this issue is due to configuring non-supported model with `OpenAI` instead of `ChatOpenAI`

**Observation 🔍** 
I referred the codebase of [openai python package](https://github.com/openai/openai-python) and observed that there are some set of models which has only support of `v1/chat/completions` (`ChatOpenAI` as implemented within langchain). Check these files for more details -
- `v1/chat/completions`: [src/openai/resources/chat/completions.py](https://github.com/openai/openai-python/blob/595e6b834fe26e08e9ac5415ab15bc19b8661f2c/src/openai/resources/chat/completions.py#L46) (list of specific models mentioned here)
- `v1/completions`: [src/openai/resources/completions.py](https://github.com/openai/openai-python/blob/595e6b834fe26e08e9ac5415ab15bc19b8661f2c/src/openai/resources/completions.py#L39)

**Potential Fix 🤔**
Should we validate the model name by referring to the same list when handling parameters for OpenAI, and raise an error accordingly?

**I can work on this, please check and let me know**

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64
> Python Version:  3.11.8 (main, Feb 26 2024, 15:43:17) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.42
> langchain: 0.1.16
> langchain_community: 0.0.32
> langsmith: 0.1.47
> langchain_openai: 0.1.3
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15
> openai: 1.17.0

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by shashankdeshpande** [comment]
@hwchase17 @baskaryan @efriis Can you please check this?

**Comment by SzymonSt** [comment]
Bump I have the same problem latest langchain-openai==0.1.3

**Comment by baskaryan** [comment]
gpt-3.5 and gpt-4 are chat models so you must use `from langchain_openai import ChatOpenAI`. See https://python.langchain.com/docs/integrations/chat/openai/ for more

**Comment by shashankdeshpande** [comment]
@baskaryan Yeah, I got this. However, the problem is lack of documentation regarding which model serves as the chat model which might cause confusion. It might be beneficial to either clarify this in the documentation or implement an explicit error message. What are your thoughts on this?
