### ISSUE TITLE
Langchain text splitters need a functionality to store chunk metadata

### ISSUE THREAD

**Issue by bhargav-11** [langchain-ai/langchain#20470]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```def load_documents():
    texts = []
    all_items = os.listdir("files/")
    for _, item in enumerate(all_items):
        print("Processing file: {}".format(item))

        # Generate a unique id for each document
        unique_id = str(uuid.uuid4())
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=0, add_start_index=True)
        loader = PDFMinerLoader("files/{}".format(item), extract_images=True)
        docs = loader.load_and_split(text_splitter)

        # Add unique id and line range to each document
        for doc in docs:
            doc.metadata["unique_id"] = unique_id

        texts.extend(docs)

    return texts
```

### Description

Langchain text splitters needs a functionality to store chunk metadata. Either a start and end line number in pdf or coordinates in pdf. 
Currently its not possible in the text splitters.

There are 2 options for this to store the chunk information.

1. Store from and to line.
 {
                "chunk": "reversible llowing ......",
                "pageNumber": 1,
                "fromLine": 27,
                "toLine": 40,
                "documentId": "8a385d38-63ed-4821-a5c2-2e7309d5a256"
    },

2. storing the coordinates of a chunk

 {
            "text": "\n Coach : the ai chatbot - We will have several coaches with different names, each with a unique",
            "coordinates": [
              {
                "x": 54,
                "y": 130.7924798925
              },
              {
                "x": 512.654318754038,
                "y": 141.7924801425
              }
            ],
            "pageSize": {
              "width": 612,
              "height": 792
            },
            "pageNumber": 1
          },

Looking for some help here. Thanks!

### System Info

$ pip freeze | grep langchain
langchain==0.1.9
langchain-community==0.0.24
langchain-core==0.1.40
langchain-openai==0.0.8

windows
python 3.11

**Comment by helena75** [comment]
I am also interested in the answer. 
I split my documents with RecursiveCharacterTextSplitter and want to add the start and end line of the chunk in the metadata for each chunk. 
How can I do so?
