### ISSUE TITLE
Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"Forbidden"}\')')

### ISSUE THREAD

**Issue by ArmaanSeth** [langchain-ai/langchain#20479]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Failed to batch ingest runs: LangSmithError('Failed to POST https://api.smith.langchain.com/runs/batch in LangSmith API. HTTPError(\'403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/batch\', \'{"detail":"Forbidden"}\')')

### Description

I am using crewai along with langsmith and the error looks like a server side error.

### System Info

platform windows
python 3.11.4

**Comment by eyurtsev** [comment]
have set LangSmith API keys? This says it's a 403

**Comment by ArmaanSeth** [comment]
> have set LangSmith API keys? This says it's a 403

Yes, I have added them in the .env file like this LANGCHAIN_API_KEY=<MY_API_KEY>

**Comment by ArmaanSeth** [comment]
The issue is solved, I reinstalled the packages in the environment, and it worked smoothly afterwards.

**Comment by eyurtsev** [comment]
OK great! Going to close the issue!

**Comment by apisani1** [comment]
I have the same issue when I am running my app on a local server (a Flask app) but not using the same environment and API Key on Jupiter Notebook.

**Comment by jmugan** [comment]
I'm getting the error as well. I'm getting it when I run in streamlit, but I don't know if that is relevant. I set the environment variables the same way I set them in other places.

**Comment by SnigdhaDev** [comment]
Same issue here! I have set all the envs correct  but still getting that 403 error, even I reinstalled all the packages and also  used new API key.

**Comment by pbackx** [comment]
The issue for me was that I needed to set the endpoint. This was not obvious to me.

    os.environ["LANGCHAIN_ENDPOINT"] = "https://eu.api.smith.langchain.com/"

**Comment by andrebeu** [comment]
I have this issue sporadically. maybe too much data?

**Comment by amartya-k** [comment]
Having the same issue

**Comment by Blaqadonis** [comment]
Same issue.

**Comment by Heiden133** [comment]
Same issue encountered today

**Comment by rposg** [comment]
I'm facing a similar issue (authentication failure), but I don't want to send any telemetry to the API, so I tried to disable the tracing by seeing it false (3 different ways): 
`tracing_v2_enabled = lambda: False`

on my env variable..: 
`export LANGCHAIN_TRACING="false"`

..and
`import os
os.environ["LANGCHAIN_TRACING"] = "false"
`

even though, none of then worked. 
=[

**Comment by apisani1** [comment]
The name of the environment variable hou have to set to false is LANGCHAIN_TRACING_V2

**Comment by rposg** [comment]
> The name of the environment variable hou have to set to false is LANGCHAIN_TRACING_V2

Thank you @apisani1!

**Comment by akpaop** [comment]
I resolved the issue by commenting out os.environ['LANGCHAIN_ENDPOINT'] = "https://api.smith.langchain.com". I'm surprised. I'm writing from Japan. I apologize if the translation is incorrect.

**Comment by ggiordann** [comment]
Hi all, the simple fix for me was disabling the built-in telemetry:

os.environ["LANGCHAIN_TRACING_V2"] = "false"

**Comment by jannichorst** [comment]
Hi all, I ran into the same issue. It worked at first but after i changed  embedding and generation model for my RAG pipeline it gave me this error. Creating a new project and API key on the langsmith platform did the trick.

**Comment by alfredorguez** [comment]
Hello,

I am trying to use the langsmith platform for tracing a project but I cannot trace even a simple hello world. I explicitly followed the instructions for creating a project but I have this error:

```
Failed to multipart ingest runs: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Forbidden"}\n')

AIMessage(content='Hello! How can I assist you today?', additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 9, 'prompt_tokens': 11, 'total_tokens': 20, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_name': 'gpt-3.5-turbo-0125', 'system_fingerprint': None, 'id': 'chatcmpl-BwUDKdGTdWmQ798JeAC3wL0T4wSKS', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='run--430543e9-273c-4c7c-8a94-a3070edb01eb-0', usage_metadata={'input_tokens': 11, 'output_tokens': 9, 'total_tokens': 20, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

Failed to send compressed multipart ingest: langsmith.utils.LangSmithError: Failed to POST https://api.smith.langchain.com/runs/multipart in LangSmith API. HTTPError('403 Client Error: Forbidden for url: https://api.smith.langchain.com/runs/multipart', '{"error":"Forbidden"}\n')

```

Can anyone tell me why it is impossible to use the API?

Here it is my code (it is the sample one given on the tool)

```
>>> LANGSMITH_TRACING="true"
>>> LANGSMITH_ENDPOINT="https://eu.api.smith.langchain.com"
>>> LANGSMITH_API_KEY="..."
>>> LANGSMITH_PROJECT="pr-internal-mining-16"
>>> OPENAI_API_KEY="..."
>>> from langchain_openai import ChatOpenAI
>>> 
>>> llm = ChatOpenAI()
>>> llm.invoke("Hello, world!")
```
