### ISSUE TITLE
Qdrant `from_documents` does not load existing collection

### ISSUE THREAD

**Issue by a172166** [langchain-ai/langchain#20514]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.vectorstores import Qdrant
from langchain_openai import AzureOpenAIEmbeddings

embeddings = AzureOpenAIEmbeddings(model="text-embedding-3-small",
                                   azure_endpoint="",
                                   api_key="")

qdrant = Qdrant.from_documents(
    docs,
    embeddings,
    path="local_qdrant",
    collection_name="my_documents",
)

### Description

When using `Qdrant.from_documents` to create a collection of documents. It seems that the collection is being recreated each time
```
from langchain_community.vectorstores import Qdrant

qdrant = Qdrant.from_documents(
    docs,
    embeddings,
    path="local_qdrant",
    collection_name="my_documents",
)
```

On  the first run, the embeddings are saving correctly, to a local file.
However, when running again, I had assumed the collection would be reused, but it seems that the collection is be recreated.

My collection is very large, and takes about 10 minutes to complete. If i run the add_documents call again, it still takes the same time to complete, so my assumtion is that it is not being read from the collection on disk

### System Info

langchain==0.1.16
langchain-community==0.0.32
langchain-core==0.1.42
langchain-openai==0.1.2
langchain-text-splitters==0.0.1
Platform: OSX
Python Version: 3.11

**Comment by spike-spiegel-21** [comment]
The collection is not recreated but, every time you run, `Qdrant.from_documents(...)` it will re-create embeddings. If you want to reuse your collection, create a Qdrant client like this, in a separate script:

```
from qdrant_client import QdrantClient, models
client = QdrantClient(path="local_qdrant")
```
Ref: [Qdrant docs](https://qdrant.tech/documentation/)

**Comment by spike-spiegel-21** [comment]
@a172166 more example

```from qdrant_client import QdrantClient, models
from langchain_community.vectorstores import Qdrant
from langchain_cohere import CohereEmbeddings

client = QdrantClient(path="local_qdrant")
embeddings = CohereEmbeddings(model="embed-english-light-v3.0", cohere_api_key = "<api_key>")
collection_name = "my_documents"
qdrant =  Qdrant(client, collection_name, embeddings)

query = "What did the president say about Ketanji Brown Jackson"
found_docs = qdrant.similarity_search(query)

print(found_docs[0].page_content)

**Comment by a172166** [comment]
just was i was looking for!! thank you so much
