### ISSUE TITLE
MAX_TOKENS in MistralAIEmbeddings is incorrect

### ISSUE THREAD

**Issue by ReinforcedKnowledge** [langchain-ai/langchain#20523]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_mistralai.embeddings import MistralAIEmbeddings

```python
embeddings = MistralAIEmbeddings()

pass_test_str = "hello world" * 4094
embedded_pass_test_str = embeddings.embed_documents([pass_test_str])

print(f"Maximum number of tokens that pass: {len(embeddings.tokenizer.encode(pass_test_str))}")  # 8190
print(f"Embedding dimension: {len(embedded_pass_test_str[0])}")  # 1024

fail_test_str = "hello world" * 4095

print(f"Number of tokens: {len(embeddings.tokenizer.encode(fail_test_str))}")  # 8192

embedded_fail_test_str = embeddings.embed_documents([fail_test_str])
```

### Error Message and Stack Trace (if applicable)

An error occurred with MistralAI: 'data'
Traceback (most recent call last):
  File "/Users/y.tahtah/test_langchain_mistralai_embeddings/test.py", line 15, in <module>
    embedded_fail_test_str = embeddings.embed_documents([fail_test_str])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/y.tahtah/test_langchain_mistralai_embeddings/venv/lib/python3.12/site-packages/langchain_mistralai/embeddings.py", line 135, in embed_documents
    for embedding_obj in response.json()["data"]
                         ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

### Description

I'm trying to embed some text using `MistralAIEmbeddings` and I have split my text according to the `MAX_TOKENS` variable in `libs/partners/mistralai/langchain_mistralai` but it's not working. Further investigation with the example code provided with this issue led me to find that the embedding models fails to embed a document way before the 16k token indicated by `MAX_TOKENS`.

[MistralAI's official page on endpoints](https://docs.mistral.ai/platform/endpoints/) doesn't specify a context window size for the embedding model.

Either there is an issue with how langchain hits the endpoint, but I couldn't find any issue in the code in that regard and I doubt it is the case since it works for strings of token count less than $8190$ (as the provided example code shows), or the MistralAI's embedding model has a context length of $8190$ and in which case we should update the `MAX_TOKENS` variable.

### System Info

Python 3.12.2

langchain-core==0.1.43
langchain-mistralai==0.1.2

MacOS 14.4.1 (M1)

**Comment by ReinforcedKnowledge** [comment]
Printing the usage for each example in the example code gives: `'usage': {'prompt_tokens': 8191, 'total_tokens': 8191, 'completion_tokens': 0}` and `{'object': 'error', 'message': 'Input is too long. Max length is 8192 got 8193', 'type': 'invalid_request_error', 'param': None, 'code': None}` respectively.

I'm not sure if the tokenizer is missing a special token or it's the encoding part that doesn't add it (since we respectively get $8190$ and $8192$ tokens with the `encode` method), or if it's MistralAI's endpoint that adds a special token before feeding everything to the embedding model.

**Comment by codenamics** [comment]
It is always good to set it lower, i do not why but still set it for 7000
