### ISSUE TITLE
Standardized token usage information

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#20524]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

A number of model's provide token usage stats as part of generation response. Should we provide a standardized interface to these stats? Would unblock downstream usage in e.g. tracers.

RFC proposal: #20522

**Comment by liugddx** [comment]
What are the specific next steps for this proposal? Will every llms adapt to this part of the response?

**Comment by sepiatone** [comment]
> ... Should we provide a standardized interface to these stats? ...

There definitely is demand for it - see attempts / requests for [fireworks](https://github.com/langchain-ai/langchain/pull/16607), [ollama](https://github.com/langchain-ai/langchain/discussions/19422), [bedrock](https://github.com/langchain-ai/langchain/pull/19127), [embeddings](https://github.com/langchain-ai/langchain/issues/945) and [model agnostic](https://github.com/langchain-ai/langchain/pull/13212).

What about costs? For OpenAI there is the callback. Would it make sense to include this in this interface (or perhaps a model agnostic callback handler)?

**Comment by sepiatone** [comment]
@baskaryan would there be any interest in developing a callback handler to determine token count while using embeddings, similar in functionality to `get_openai_callback`? there has been some discussion on this earlier [here](https://github.com/langchain-ai/langchain/issues/945) and there is definitely [demand](https://github.com/langchain-ai/langchain/issues/20799)

I could do this (unless you think it may be too involved for a non-maintainer).

**Comment by lvisdd** [comment]
I'm wondering because OpenAI now supports stream_options, but Azure OpenAI Service doesn't support stream_options.
https://github.com/langchain-ai/langchain/pull/9249#issuecomment-2126629222

**Comment by baskaryan** [comment]
currently our in rc: #21944

**Comment by baskaryan** [comment]
landed in https://github.com/langchain-ai/langchain/pull/21944
