### ISSUE TITLE
Problem when using ChatAnthropic bind_tools/with_structured_output with an agent: "x is not a valid tool".

### ISSUE THREAD

**Issue by arose26** [langchain-ai/langchain#20530]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
ExtractData = 	{
	"name": "ExtractData",
	"description": "ExtractData",
	"input_schema": {
		"type": "object", "description":"schema components for getting data",
		"properties": data_schema,
		"required": ["x","y']
		}
	  }

llm = ChatAnthropic(model=MODEL_NAME, verbose=True)
llm_with_tools = llm.bind_tools([ExtractData ]) # OR llm.with_structured_output(ExtractData)
agent= initialize_agent(
	[OtherTool]
	llm_with_tools,
	agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION)

agent.invoke(query)
```

### Error Message and Stack Trace (if applicable)

Observation: ExtractData is not a valid tool, try one of [OtherTool].
Thought:Apologies, let me try this again using the valid tools:

### Description

I am attempting to get structured output from an agent. While the above code DOES work, I always get this error message when the agent attempts to look for its llm bound tool inside the agent's tools. (Nevertheless it returns the right output in the end, but it sometimes does a few loops of the same operation first).
The correct behavior should be that the agent does NOT look for llm tools in its own tools, because the input it is trying to feed to the tool is ALREADY the correctly formatted input.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Thu Jan 11 04:09:03 UTC 2024
> Python Version:  3.12.3 (main, Apr 14 2024, 13:07:33) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.1.42
> langchain: 0.1.16
> langchain_community: 0.0.32
> langsmith: 0.1.47
> langchain_anthropic: 0.1.8
> langchain_chroma: 0.1.0
> langchain_openai: 0.0.5
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15

**Comment by eyurtsev** [comment]
Follow tutorial here https://python.langchain.com/docs/modules/agents/agent_types/tool_calling/


Use `with_structured_output` if you need a one time interaction with an LLM that returns a pydantic object -- don't use it for agents.

**Comment by eyurtsev** [comment]
This is a usage question rather than a bug, so closing
