### ISSUE TITLE
> Looks like I've imported differently. It's type is supposed to say `langchain_community.graphs.networkx_graph.NetworkxEntityGraph`. It is working now!!

### ISSUE THREAD

**Issue by nikhitaKanoj** [langchain-ai/langchain#20541]
> Looks like I've imported differently. It's type is supposed to say `langchain_community.graphs.networkx_graph.NetworkxEntityGraph`. It is working now!!

I am running the same issue , how did u solve it ?
My object is : "langchain.graphs.network_graph.NetworkxEntityGraph" object

_Originally posted by @nikhitaKanoj in https://github.com/langchain-ai/langchain/issues/15046#issuecomment-2060214876_

**Comment by eyurtsev** [comment]
This is a usage question not a bug, please use Q&A for usage questions. Also the answer to the question was in the issue use `langchain_community`
