### ISSUE TITLE
Dynamic Few Shot Prompt - SemanticSimilarityExampleSelector - Unknown encoding cl100k_base

### ISSUE THREAD

**Issue by Naperk** [langchain-ai/langchain#20567]
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

This is the code I am trying to run:
```
python 
from langchain.prompts.example_selector import (
    MaxMarginalRelevanceExampleSelector,
    SemanticSimilarityExampleSelector,
)

SemanticSimilarityExampleSelector.from_examples(
    query_examples,
    OpenAIEmbeddings(),
    FAISS,
    k=5,
    input_keys=["input"],
)
```

### Error Message and Stack Trace (if applicable)

Below the full error:

example_selector = SemanticSimilarityExampleSelector.from_examples(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5f12176cc20a/antenv/lib/python3.11/site-packages/langchain_core/example_selectors/semantic_similarity.py", line 133, in from_examples
vectorstore = vectorstore_cls.from_texts(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5f12176cc20a/antenv/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 930, in from_texts
embeddings = embedding.embed_documents(texts)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/3.11.7/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 517, in embed_documents
return self._get_len_safe_embeddings(texts, engine=engine)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/3.11.7/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 300, in _get_len_safe_embeddings
encoding = tiktoken.encoding_for_model(model_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5f12176cc20a/antenv/lib/python3.11/site-packages/tiktoken/model.py", line 75, in encoding_for_model
File "/tmp/8dc5f12176cc20a/antenv/lib/python3.11/site-packages/tiktoken/registry.py", line 60, in get_encoding
ValueError: Unknown encoding cl100k_base

### Description

I have an issue when trying to use SemanticSimilarityExampleSelector in an app hosted in Azure App Services. When running locally it works, I get the following error:
Unknown encoding cl100k_base.

### System Info

python version: 3.11
platform: linux

aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.6.0
anyio==4.3.0
asn1crypto==1.5.1
async-timeout==4.0.3
attrs==23.2.0
azure-ai-contentsafety==1.0.0
azure-core==1.30.1
banal==1.0.6
beartype==0.18.2
beautifulsoup4==4.12.3
binaryornot==0.4.4
boolean.py==4.0
botbuilder-core==4.14.8
botbuilder-integration-aiohttp==4.14.8
botbuilder-schema==4.14.8
botframework-connector==4.14.8
botframework-streaming==4.14.8
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
commoncode==31.0.3
container-inspector==32.0.1
cryptography==42.0.5
dataclasses-json==0.6.4
debian_inspector==31.1.0
distro==1.9.0
dockerfile-parse==2.0.1
dparse2==0.7.0
extractcode==31.0.0
extractcode-7z==16.5.210531
extractcode-libarchive==3.5.1.210531
faiss-cpu==1.8.0
fasteners==0.19
filelock==3.13.3
fingerprints==1.2.3
frozenlist==1.4.1
ftfy==6.2.0
gemfileparser2==0.9.3
greenlet==3.0.3
h11==0.14.0
html5lib==1.1
httpcore==1.0.4
httpx==0.27.0
idna==3.6
importlib_metadata==7.1.0
intbitset==3.1.0
isodate==0.6.1
jaraco.functools==4.0.0
javaproperties==0.8.1
Jinja2==3.1.3
jsonpatch==1.33
jsonpickle==1.4.2
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jsonstreams==0.6.0
langchain==0.1.13
langchain-community==0.0.29
langchain-core==0.1.40
langchain-openai==0.1.1
langchain-text-splitters==0.0.1
langsmith==0.1.40
license-expression==30.3.0
lxml==5.2.1
MarkupSafe==2.1.5
marshmallow==3.21.1
more-itertools==10.2.0
msal==1.27.0
msrest==0.7.1
multidict==6.0.5
mypy-extensions==1.0.0
normality==2.5.0
numpy==1.26.4
oauthlib==3.2.2
openai==1.13.3
orjson==3.10.0
packageurl-python==0.15.0
packaging==23.2
packvers==21.5
pandas==2.2.1
parameter-expansion-patched==0.3.1
pdfminer.six==20231228
pefile==2023.2.7
pip-requirements-parser==32.0.1
pkginfo2==30.0.0
platformdirs==3.11.0
pluggy==1.4.0
plugincode==32.0.0
ply==3.11
publicsuffix2==2.20191221
pyahocorasick==2.1.0
pyarrow==15.0.2
pycparser==2.21
pydantic==2.6.3
pydantic_core==2.16.3
pygmars==0.8.0
Pygments==2.17.2
PyJWT==2.8.0
pymaven-patch==0.3.2
pyOpenSSL==24.1.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
pytz==2024.1
PyYAML==6.0.1
rdflib==7.0.0
referencing==0.33.0
regex==2023.12.25
requests==2.31.0
requests-oauthlib==1.3.1
rpds-py==0.18.0
saneyaml==0.6.0
scancode-toolkit==32.1.0
semantic-version==2.10.0
six==1.16.0
sniffio==1.3.1
snowflake-connector-python==3.7.1
snowflake-sqlalchemy==1.5.1
sortedcontainers==2.4.0
soupsieve==2.5
spdx-tools==0.8.2
SQLAlchemy==1.4.52
teams-ai==1.0.0
tenacity==8.2.3
text-unidecode==1.3
tiktoken==0.6.0
toml==0.10.2
tomlkit==0.12.4
tqdm==4.66.2
typecode==30.0.1
typecode-libmagic==5.39.210531
types-PyYAML==6.0.12.12
typing-inspect==0.9.0
typing_extensions==4.10.0
tzdata==2024.1
Unidecode==1.3.8
uritools==4.0.2
urllib3==1.26.18
urlpy==0.5
wcwidth==0.2.13
webencodings==0.5.1
xmltodict==0.13.0
yarl==1.9.4
zipp==3.18.1

**Comment by spike-spiegel-21** [comment]
Try upgrading `langchain_community` `langchain_core` `langchain_openai` using:
`pip install --upgrade [package-name]`

**Comment by Naperk** [comment]
@spike-spiegel-21 
I have just installed the latest versions:
langchain==0.1.16
langchain-community==0.0.33
langchain-core==0.1.44
langchain-openai==0.1.3
langchain-text-splitters==0.0.1

But I still have the same error:

example_selector = SemanticSimilarityExampleSelector.from_examples(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5fa2fae7724d/antenv/lib/python3.11/site-packages/langchain_core/example_selectors/semantic_similarity.py", line 133, in from_examples
vectorstore = vectorstore_cls.from_texts(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5fa2fae7724d/antenv/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py", line 930, in from_texts
embeddings = embedding.embed_documents(texts)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/3.11.7/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 517, in embed_documents
return self._get_len_safe_embeddings(texts, engine=engine)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/python/3.11.7/lib/python3.11/site-packages/langchain_openai/embeddings/base.py", line 300, in _get_len_safe_embeddings
encoding = tiktoken.encoding_for_model(model_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/8dc5fa2fae7724d/antenv/lib/python3.11/site-packages/tiktoken/model.py", line 75, in encoding_for_model
File "/tmp/8dc5fa2fae7724d/antenv/lib/python3.11/site-packages/tiktoken/registry.py", line 60, in get_encoding
ValueError: Unknown encoding cl100k_base
