### ISSUE TITLE
DOC: Code Copy is not working inside of sql/agents in the python page 

### ISSUE THREAD

**Issue by goyalpramod** [langchain-ai/langchain#20584]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://python.langchain.com/docs/use_cases/sql/agents/

The copy mechanism for code does not seem to be working. 

### Idea or request for content:

When I click on the copy button, the code should be copied.

**Comment by code-inhub** [comment]
On the provided link where is the issue. can you tell me ?

**Comment by goyalpramod** [comment]
@code-inhub I believe someone fixed it, it seems to work now.
