### ISSUE TITLE
Alpaca-LoRA

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#2063]
### Alpaca-LoRA

[Alpaca-LoRA](https://github.com/tloen/alpaca-lora) and Stanford Alpaca are NLP models that use the GPT architecture, but there are some critical differences between them. Here are three:

- **Training data**: Stanford Alpaca was trained on a larger dataset that includes a variety of sources, including webpages, books, and more. Alpaca-LoRA, on the other hand, was trained on a smaller dataset (but one that has been curated for quality) and uses low-rank adaptation (LoRA) to fine-tune the model for specific tasks.
- **Model size**: Stanford Alpaca is a larger model, with versions ranging from 774M to 1.5B parameters. Alpaca-LoRA, on the other hand, provides a smaller, 7B parameter model that is specifically optimized for low-cost devices such as the Raspberry Pi.
- **Pretrained models**: Both models offer pre-trained models that can be used out-of-the-box, but the available options are slightly different. Stanford Alpaca provides several models with different sizes and degrees of finetuning, while Alpaca-LoRA provides an Instruct model of similar quality to `text-davinci-003`.

### Similar To

https://github.com/hwchase17/langchain/issues/1777

### Resources

-   [alpaca.cpp](https://github.com/antimatter15/alpaca.cpp), a native client for running Alpaca models on the CPU
-   [Alpaca-LoRA-Serve](https://github.com/deep-diver/Alpaca-LoRA-Serve), a ChatGPT-style interface for Alpaca models
-   [AlpacaDataCleaned](https://github.com/gururise/AlpacaDataCleaned), a project to improve the quality of the Alpaca dataset
-   Various adapter weights (download at own risk):
    -   7B:
        -   <https://huggingface.co/tloen/alpaca-lora-7b>
        -   <https://huggingface.co/samwit/alpaca7B-lora>
        -   🇧🇷 <https://huggingface.co/22h/cabrita-lora-v0-1>
        -   🇨🇳 <https://huggingface.co/qychen/luotuo-lora-7b-0.1>
        -   🇯🇵 <https://huggingface.co/kunishou/Japanese-Alapaca-LoRA-7b-v0>
        -   🇫🇷 <https://huggingface.co/bofenghuang/vigogne-lora-7b>
        -   🇹🇭 <https://huggingface.co/Thaweewat/thai-buffala-lora-7b-v0-1>
        -   🇩🇪 <https://huggingface.co/thisserand/alpaca_lora_german>
        -   🇮🇹 <https://huggingface.co/teelinsan/camoscio-7b-llama>
    -   13B:
        -   <https://huggingface.co/chansung/alpaca-lora-13b>
        -   <https://huggingface.co/mattreid/alpaca-lora-13b>
        -   <https://huggingface.co/samwit/alpaca13B-lora>
        -   🇯🇵 <https://huggingface.co/kunishou/Japanese-Alapaca-LoRA-13b-v0>
        -   🇰🇷 <https://huggingface.co/chansung/koalpaca-lora-13b>
        -   🇨🇳 <https://huggingface.co/facat/alpaca-lora-cn-13b>
    -   30B:
        -   <https://huggingface.co/baseten/alpaca-30b>
        -   <https://huggingface.co/chansung/alpaca-lora-30b>
        -   🇯🇵 <https://huggingface.co/kunishou/Japanese-Alapaca-LoRA-30b-v0>
-   [alpaca-native](https://huggingface.co/chavinlo/alpaca-native), a replication using the original Alpaca code

**Comment by lughino** [comment]
Is there a way to run this model with langchain?

**Comment by larawehbe** [comment]
> Is there a way to run this model with langchain?

Did you get any solution?

**Comment by afnanhabib787** [comment]
following
