### ISSUE TITLE
"HTMLSectionSplitter" is not accessible in latest langchain-text-splitters package

### ISSUE THREAD

**Issue by HaoqingCai** [langchain-ai/langchain#20644]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

pip install langchain
pip install langchain-text-splitters

from langchain_text_splitters import HTMLSectionSplitter

### Description

Since i noticed that "HTMLSectionSplitter" was released in [v0.1.15](https://github.com/langchain-ai/langchain/releases/tag/v0.1.15), i upgraded/reinstalled "Langchain" & "langchain-text-splitters" for introducing this new splitter into my project followed by the instruction in [here](https://python.langchain.com/docs/modules/data_connection/document_transformers/). But the new splitter is not found in new package. I checked the latest package of "langchain-text-splitters" in [pypi](https://pypi.org/project/langchain-text-splitters/), the files in package are not the latest version in github.

init file in downloaded pypi package: 
![Snipaste_2024-04-19_14-27-59](https://github.com/langchain-ai/langchain/assets/120713349/213bd069-07ab-47eb-b790-894b6a276ec3)

same file in github:
![Snipaste_2024-04-19_14-29-14](https://github.com/langchain-ai/langchain/assets/120713349/60c9b42d-e160-456f-9a09-f89f82a6b6ff)

How can i use this splitter now?

### System Info

platform: windows 10
python version: 3.12.3

**Comment by qingdengyue** [comment]
try 
`pip install -qU langchain-text-splitters`

**Comment by HaoqingCai** [comment]
> try `pip install -qU langchain-text-splitters`

I've tried it. Still not working.

**Comment by chosh0615** [comment]
I'm having the same issue. Is there a plan for fix?

**Comment by HaoqingCai** [comment]
is there any update for this issue?

**Comment by arinbjornk** [comment]
Also facing this issue. 

Was it removed by accident?

**Comment by jasonkurohara** [comment]
Having the same issue. Any way we can get around this?

**Comment by littlebox692** [comment]
any update?

**Comment by david101-hunter** [comment]
anyone explain why?
