### ISSUE TITLE
DB Tools - Allow to reference also views thru custom_table_info

### ISSUE THREAD

**Issue by zzy9v4** [langchain-ai/langchain#2066]
I tried to map my db that have a lot of views that can leverage the whoole work. But the initial check does not allow this, also by having custom_table_info that describe the view structure.

**Comment by wadihpazos** [comment]
I missed this issue and added the following [issue](https://github.com/hwchase17/langchain/issues/2356) as a duplicate today. I fixed this problem in [this](https://github.com/hwchase17/langchain/pull/2355) pull request.
