### ISSUE TITLE
Langchain self query weaviate

### ISSUE THREAD

**Issue by eav-solution** [langchain-ai/langchain#20726]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

self.vectorstore = Weaviate(
                client=self.dbClient,
                index_name=collectionName,
                text_key=self.embeddingProperty,
                embedding=self.embedding,
                by_text=False,
            )
SelfQueryRetriever.from_llm(
            self.llm, self.vectorstore, documentContentDescription, metadataFieldInfo, verbose=True, 
            # enable_limit=True,
        )

### Error Message and Stack Trace (if applicable)

Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'invalid \'where\' filter: child operand at position 0: data type filter cannot use "valueInt" on type "number", use "valueNumber" instead', 'path': ['Get', 'LKT_ASSISTANT_Product']}]

### Description

Maybe weaviate changed api recently.

### System Info

python 3.11, linux
langchain                    0.1.16
langchain-community          0.0.33
langchain-core               0.1.43
langchain-experimental       0.0.49
langchain-google-genai       1.0.2
langchain-openai             0.1.3
langchain-text-splitters     0.0.1
langchainhub                 0.1.14

**Comment by ygao2-woolworthslimited** [comment]
any updates on this issue? I am facing the same issue
