### ISSUE TITLE
Langchain FilemanagementToolkit incorrectly writes python code to files

### ISSUE THREAD

**Issue by Eklavya17** [langchain-ai/langchain#20721]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

  file_management = FileManagementToolkit(
    # If you don't provide a root_dir, operations will default to the current working directory
    root_dir=root_dir
  ).get_tools()

using this tool to write data to a python file writes the data as a string and the \n is interpreted as a character not as \n itself and the rest of the code is not moved to the new line

### Description

Trying to use the filemanagementtoolkit to write python code in a new line but it fails in correctly doing so as it should

### System Info

windows,
python -11.4

**Comment by Eklavya17** [comment]
Yeah that is the version on the venv I'm using

**Comment by qingdengyue** [comment]
can you provide you venv comand or provide mini reproduce repos. i‘ not familiar with venv,i use a conda environment locally

**Comment by Eklavya17** [comment]
The venv isn't the problem the issue is that the toolkit is not correctly writing the files even without the venv

**Comment by qingdengyue** [comment]
just want to have a try. 😄 
in linux. i find the \n is worked. open the file that is a new line.if read file using 'read_tool',yes.it is a '\n' character in the string.i think this is normal.
