### ISSUE TITLE
Value Error: Redis failed to connect : Port could not be cast to integer value as 'Test'. 

### ISSUE THREAD

**Issue by SwapnaMadhu570** [langchain-ai/langchain#20729]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os
import google.generativeai as genai
from langchain_google_genai import GoogleGenerativeAIEmbeddings
import langchain
from langchain_community.vectorstores.redis import Redis as lc_redis
from tqdm import tqdm
os.environ['GOOGLE_API_KEY'] = 'your-Google-api-key'
genai.configure(api_key='GOOGLE_API_KEY')
sample_1=["""Azure Key Vault is a cloud service for securely storing and accessing secrets.A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, or cryptographic keys."""]
embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")
url="redis://default:test#2024@redis-14876.c400.eu-central-1-1.ec2.cloud.redislabs.com:14876"
rds = lc_redis.from_texts(
    sample_1,
    embeddings,
    redis_url=url,
    index_name="sample_index",)
results = rds.similarity_search('network')
print(results)

### Error Message and Stack Trace (if applicable)

Value Error: Redis failed to connect : Port could not be cast to integer value as 'Test'. 

### Description

we are facing issue while using Langchain Redis to connect we were not able to connect to redis instance. The error is as follows: 

Value Error: Redis failed to connect : Port could not be cast to integer value as 'Welcome'

for example url="redis://default:Test#2024@redis-14876.c400.eu-central-1-1.ec2.cloud.redislabs.com:14876"

Facing the Issue when password contains '#'. But works in case of other password like Test@2024

### System Info

**This is pip freeze langchain output:**
langchain==0.1.16
langchain-community==0.0.33
langchain-core==0.1.42
langchain-google-genai==1.0.2
langchain-text-splitters==0.0.1

**Version of redis database using:**
redis_version:6.2.10
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:0000000000000000000000000000000000000000
redis_mode:standalone
os:Linux 5.15.0-1051-gcp x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:9.4.0

**Python version:**
python version :3.12.2

**Comment by liugddx** [comment]
Let me see

**Comment by liugddx** [comment]
Please refer to this code.
```
password = url_quote("test#2024", safe="")
url = "redis://default:{password}@redis-14876.c400.eu-central-1-1.ec2.cloud.redislabs.com:14876"
```

**Comment by SwapnaMadhu570** [comment]
Hi @liugddx , Thank you for responding, I have tried the code you have provided but got another error saying,  
                                                               
NoPermissionError: this user has no permissions to run the 'module' command or its subcommand

I'm using the following line to import url_quote. 

from urllib.parse import quote as url_quote

**Comment by liugddx** [comment]
> Hi @liugddx , Thank you for responding, I have tried the code you have provided but got another error saying,
> 
> NoPermissionError: this user has no permissions to run the 'module' command or its subcommand
> 
> I'm using the following line to import url_quote.
> 
> from urllib.parse import quote as url_quote

Do you have detailed error stack information?

**Comment by abhiram-ds** [comment]
Hello @liugddx 

Please find below the entire error stack

----> 4 new_rds =  lc_redis.from_existing_index(
      5     embeddings,
      6     index_name="new_index",
      7     redis_url=url,
      8     schema="new_schema.yaml")

File c:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\langchain_community\vectorstores\redis\base.py:552, in Redis.from_existing_index(cls, embedding, index_name, schema, key_prefix, **kwargs)
    548     kwargs.pop("redis_url")
    550 # Create instance
    551 # init the class -- if Redis is unavailable, will throw exception
--> 552 instance = cls(
    553     redis_url,
    554     index_name,
    555     embedding,
    556     index_schema=schema,
    557     key_prefix=key_prefix,
    558     **kwargs,
    559 )
    561 # Check for existence of the declared index
    562 if not check_index_exists(instance.client, index_name):
...
--> 536         raise response
    537     finally:
    538         del response  # avoid creating ref cycles

NoPermissionError: this user has no permissions to run the 'module' command or its subcommand
