### ISSUE TITLE
Ollama running Llama3 does not terminate.

### ISSUE THREAD

**Issue by GullyBurns** [langchain-ai/langchain#20765]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code will endlessly print multiple poems and revisions of poems about fish :

```python 
from langchain_community.chat_models.ollama import ChatOllama
llm = ChatOllama(model='llama3:70b')
for chunk in llm.stream('Write a poem about fish'):
    print(chunk.content)
   ```
  
 This can be solved by adding an explicit stop condition:
 
```python
llm = ChatOllama(model='llama3:70b', stop=["<|eot_id|>"])
```

Can you please update the `Ollama` and `ChatOllama` elements to include this stop condition for Llama3? 

### Description

See example code. Generations under Llama3 never terminate

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
> Python Version:  3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.1.45
> langchain: 0.1.16
> langchain_community: 0.0.32
> langsmith: 0.1.43
> langchain_google_vertexai: 0.0.5
> langchain_openai: 0.0.8
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.14
> langserve: 0.0.34

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph

**Comment by abhiksark** [comment]
I was facing the same, updated to `langchain==0.1.16` resolved now

**Comment by captainst** [comment]
> I was facing the same, updated to `langchain==0.1.16` resolved now

The problem persisted, with `langchain==0.1.16`. I am using the following config:

```
langchain                                0.1.16
langchain-anthropic                      0.1.8
langchain-astradb                        0.1.0
langchain-cli                            0.0.21
langchain-cohere                         0.1.3rc0
langchain-community                      0.0.33
langchain-core                           0.1.43
langchain-experimental                   0.0.57
langchain-google-genai                   1.0.2
langchain-openai                         0.1.3
langchain-text-splitters                 0.0.1
```

**Comment by ventz** [comment]
The same is an issue for the `ChatBedrock` -- it looks like it requires a new prompt template for Llama3 which adheres to:

https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/

**Comment by DiazBejaranoD** [comment]
updating the langchain-community package helped me overcome the never-ending issue.

![image](https://github.com/langchain-ai/langchain/assets/5337376/2b9e8dc9-c8d2-4953-b08a-4db0814f0fa3)

**Comment by ventz** [comment]
@DiazBejaranoD Did not work on my end.
```
langchain                     0.1.16
langchain-aws                 0.1.2
langchain-community           0.0.34
langchain-core                0.1.46
langchain-google-vertexai     1.0.2
langchain-openai              0.1.4
langchain-text-splitters      0.0.1
langsmith                     0.1.51
```

I just added the stop sequence manually however and that seems to work.

```
prompt_template = ChatPromptTemplate.from_messages([
            ("system", "You are a helpful assistant. Answer all questions to the best of your ability."),
            MessagesPlaceholder(variable_name="messages"),
        ])


...


chain = prompt_template | llm | output_parser


response = chain.invoke({
            "messages": [
                HumanMessage(content="<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n"+prompt+"<|eot_id|><|start_header_id|>assistant<|end_header_id|>"),
            ],
        })
```

^ Hopefully that helps others.

**Comment by GullyBurns** [comment]
Repeating the note from the original post. Fixing the error is easy, instantiate the ChatModel with an explicit stop condition.  

`llm = ChatOllama(model='llama3:70b', stop=["<|eot_id|>"])`

The goal in posting this was to have someone update the ChatOllama source code to include the fix.
