### ISSUE TITLE
Getting the Issue with the New Langchain version

### ISSUE THREAD

**Issue by KeyanatGiggso** [langchain-ai/langchain#20778]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

--> 248 result = chain({"question": question_with_region, "chat_history": chat_history})
    249 sources = "\n".join(set(map(lambda x: x.metadata["source"], result['source_documents'])))
    251 container_sas = self.blob_client.get_container_sas()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\_api\deprecation.py:148, in deprecated.<locals>.deprecate.<locals>.warning_emitting_wrapper(*args, **kwargs)
    146     warned = True
    147     emit_warning()
--> 148 return wrapped(*args, **kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py:378, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, run_name, include_run_info)
    346 """Execute the chain.
    347 
    348 Args:
   (...)
    369         `Chain.output_keys`.
    370 """
    371 config = {
    372     "callbacks": callbacks,
    373     "tags": tags,
    374     "metadata": metadata,
    375     "run_name": run_name,
    376 }
--> 378 return self.invoke(
    379     inputs,
    380     cast(RunnableConfig, {k: v for k, v in config.items() if v is not None}),
    381     return_only_outputs=return_only_outputs,
    382     include_run_info=include_run_info,
    383 )

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py:163, in Chain.invoke(self, input, config, **kwargs)
    161 except BaseException as e:
    162     run_manager.on_chain_error(e)
--> 163     raise e
    164 run_manager.on_chain_end(outputs)
    166 if include_run_info:

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\base.py:153, in Chain.invoke(self, input, config, **kwargs)
    150 try:
    151     self._validate_inputs(inputs)
    152     outputs = (
--> 153         self._call(inputs, run_manager=run_manager)
    154         if new_arg_supported
    155         else self._call(inputs)
    156     )
    158     final_outputs: Dict[str, Any] = self.prep_outputs(
    159         inputs, outputs, return_only_outputs
    160     )
    161 except BaseException as e:

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\conversational_retrieval\base.py:155, in BaseConversationalRetrievalChain._call(self, inputs, run_manager)
    151 accepts_run_manager = (
    152     "run_manager" in inspect.signature(self._get_docs).parameters
    153 )
    154 if accepts_run_manager:
--> 155     docs = self._get_docs(new_question, inputs, run_manager=_run_manager)
    156 else:
    157     docs = self._get_docs(new_question, inputs)  # type: ignore[call-arg]

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\chains\conversational_retrieval\base.py:317, in ConversationalRetrievalChain._get_docs(self, question, inputs, run_manager)
    309 def _get_docs(
    310     self,
    311     question: str,
   (...)
    314     run_manager: CallbackManagerForChainRun,
    315 ) -> List[Document]:
    316     """Get docs."""
--> 317     docs = self.retriever.get_relevant_documents(
    318         question, callbacks=run_manager.get_child()
    319     )
    320     return self._reduce_tokens_below_limit(docs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\retrievers.py:321, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    319 except Exception as e:
    320     run_manager.on_retriever_error(e)
--> 321     raise e
    322 else:
    323     run_manager.on_retriever_end(
    324         result,
    325     )

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\retrievers.py:314, in BaseRetriever.get_relevant_documents(self, query, callbacks, tags, metadata, run_name, **kwargs)
    312 _kwargs = kwargs if self._expects_other_args else {}
    313 if self._new_arg_supported:
--> 314     result = self._get_relevant_documents(
    315         query, run_manager=run_manager, **_kwargs
    316     )
    317 else:
    318     result = self._get_relevant_documents(query, **_kwargs)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_core\vectorstores.py:696, in VectorStoreRetriever._get_relevant_documents(self, query, run_manager)
    692 def _get_relevant_documents(
    693     self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    694 ) -> List[Document]:
    695     if self.search_type == "similarity":
--> 696         docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
    697     elif self.search_type == "similarity_score_threshold":
    698         docs_and_similarities = (
    699             self.vectorstore.similarity_search_with_relevance_scores(
    700                 query, **self.search_kwargs
    701             )
    702         )

File C:\codespaces\chatbot\stable-code\portal-api\utilities\azuresearch.py:353, in AzureSearch.similarity_search(self, query, k, **kwargs)
    340 def similarity_search(
    341     self, query: str, k: int = 4, **kwargs: Any
    342 ) -> List[Document]:
    343     """
    344     Returns the most similar indexed documents to the query text.
    345 
   (...)
    351         List[Document]: A list of documents that are most similar to the query text.
    352     """
--> 353     docs_and_scores = self.similarity_search_with_score(
    354         query, k=k, filters=self.filters)
    355     return [doc for doc, _ in docs_and_scores]

File C:\codespaces\chatbot\stable-code\portal-api\utilities\azuresearch.py:372, in AzureSearch.similarity_search_with_score(self, query, k, filters)
    360 """Return docs most similar to query.
    361 
    362 Args:
   (...)
    367     List of Documents most similar to the query and score for each
    368 """
    369 if self.index_name == "embeddings":
    370     results = self.client.search(
    371         search_text="",
--> 372         vector=Vector(value=np.array(self.embedding_function(
    373             query), dtype=np.float32).tolist(), k=k, fields=FIELDS_CONTENT_VECTOR),
    374         select=[f"{FIELDS_TITLE},{FIELDS_CONTENT},{FIELDS_METADATA}"],
    375         filter=filters
    376     )
    377     # Convert results to Document objects
    378     docs = [
    379         (
    380             Document(
   (...)
    386         for result in results
    387     ]

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_community\embeddings\openai.py:697, in OpenAIEmbeddings.embed_query(self, text)
    688 def embed_query(self, text: str) -> List[float]:
    689     """Call out to OpenAI's embedding endpoint for embedding query text.
    690 
    691     Args:
   (...)
    695         Embedding for the text.
    696     """
--> 697     return self.embed_documents([text])[0]

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_community\embeddings\openai.py:668, in OpenAIEmbeddings.embed_documents(self, texts, chunk_size)
    665 # NOTE: to keep things simple, we assume the list may contain texts longer
    666 #       than the maximum context and use length-safe embedding function.
    667 engine = cast(str, self.deployment)
--> 668 return self._get_len_safe_embeddings(texts, engine=engine)

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_community\embeddings\openai.py:494, in OpenAIEmbeddings._get_len_safe_embeddings(self, texts, engine, chunk_size)
    492 batched_embeddings: List[List[float]] = []
    493 for i in _iter:
--> 494     response = embed_with_retry(
    495         self,
    496         input=tokens[i : i + _chunk_size],
    497         **self._invocation_params,
    498     )
    499     if not isinstance(response, dict):
    500         response = response.dict()

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain_community\embeddings\openai.py:116, in embed_with_retry(embeddings, **kwargs)
    114 """Use tenacity to retry the embedding call."""
    115 if is_openai_v1():
--> 116     return embeddings.client.create(**kwargs)
    117 retry_decorator = _create_retry_decorator(embeddings)
    119 @retry_decorator
    120 def _embed_with_retry(**kwargs: Any) -> Any:

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\resources\embeddings.py:113, in Embeddings.create(self, input, model, dimensions, encoding_format, user, extra_headers, extra_query, extra_body, timeout)
    107         embedding.embedding = np.frombuffer(  # type: ignore[no-untyped-call]
    108             base64.b64decode(data), dtype="float32"
    109         ).tolist()
    111     return obj
--> 113 return self._post(
    114     "/embeddings",
    115     body=maybe_transform(params, embedding_create_params.EmbeddingCreateParams),
    116     options=make_request_options(
    117         extra_headers=extra_headers,
    118         extra_query=extra_query,
    119         extra_body=extra_body,
    120         timeout=timeout,
    121         post_parser=parser,
    122     ),
    123     cast_to=CreateEmbeddingResponse,
    124 )

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py:1233, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1219 def post(
   1220     self,
   1221     path: str,
   (...)
   1228     stream_cls: type[_StreamT] | None = None,
   1229 ) -> ResponseT | _StreamT:
   1230     opts = FinalRequestOptions.construct(
   1231         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1232     )
-> 1233     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py:922, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    913 def request(
    914     self,
    915     cast_to: Type[ResponseT],
   (...)
    920     stream_cls: type[_StreamT] | None = None,
    921 ) -> ResponseT | _StreamT:
--> 922     return self._request(
    923         cast_to=cast_to,
    924         options=options,
    925         stream=stream,
    926         stream_cls=stream_cls,
    927         remaining_retries=remaining_retries,
    928     )

File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\_base_client.py:1013, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
   1010         err.response.read()
   1012     log.debug("Re-raising status error")
-> 1013     raise self._make_status_error_from_response(err.response) from None
   1015 return self._process_response(
   1016     cast_to=cast_to,
   1017     options=options,
   (...)
   1020     stream_cls=stream_cls,
   1021 )

NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**Comment by eyurtsev** [comment]
@KeyanatGiggso would you be able to file a standard issue that has environment information etc so we can help you? The issue that you filed is for maintainers only and it's not for bug reporting

**Comment by vimmedis-analog** [comment]
@KeyanatGiggso   how is this issue resolved ? i am running into the same issue now
