### ISSUE TITLE
OpenAI assistant new version seems not compatible 

### ISSUE THREAD

**Issue by jjehl** [langchain-ai/langchain#20780]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
interpreter_assistant = OpenAIAssistantRunnable.create_assistant(
    name="langchain assistant",
    instructions="You are a personal math tutor. Write and run code to answer math questions.",
    tools=[{"type": "code_interpreter"}],
    model="gpt-4-1106-preview",
)
```

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[24], line 1
----> 1 interpreter_assistant = OpenAIAssistantRunnable.create_assistant(
      2     name="langchain assistant",
      3     instructions="You are a personal math tutor. Write and run code to answer math questions.",
      4     tools=[{"type": "code_interpreter"}],
      5     model="gpt-4-1106-preview",
      6 )

File [~/python3.11/lib/python3.11/site-packages/langchain/agents/openai_assistant/base.py:247](https://notebook.aratech.cloud/lab/tree/LLM/python3.11/lib/python3.11/site-packages/langchain/agents/openai_assistant/base.py#line=246), in OpenAIAssistantRunnable.create_assistant(cls, name, instructions, tools, model, client, **kwargs)
    233 """Create an OpenAI Assistant and instantiate the Runnable.
    234 
    235 Args:
   (...)
    244     OpenAIAssistantRunnable configured to run using the created assistant.
    245 """
    246 client = client or _get_openai_client()
--> 247 assistant = client.beta.assistants.create(
    248     name=name,
    249     instructions=instructions,
    250     tools=[_get_assistants_tool(tool) for tool in tools],  # type: ignore
    251     model=model,
    252     file_ids=kwargs.get("file_ids"),
    253 )
    254 return cls(assistant_id=assistant.id, client=client, **kwargs)

TypeError: Assistants.create() got an unexpected keyword argument 'file_ids'

### Description

Probably the new OpenAi assistant V2 is not accpeting the file_ids argument.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #112~20.04.1-Ubuntu SMP Thu Mar 14 14:28:24 UTC 2024
> Python Version:  3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 9.4.0]

Package Information
-------------------
> langchain_core: 0.1.44
> langchain: 0.1.16
> langchain_community: 0.0.33
> langsmith: 0.1.48
> langchain_experimental: 0.0.57
> langchain_openai: 0.1.3
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by jjehl** [comment]
From openAI doc : 

```python
from openai import OpenAI
client = OpenAI()
  
assistant = client.beta.assistants.create(
  name="Math Tutor",
  instructions="You are a personal math tutor. Write and run code to answer math questions.",
  tools=[{"type": "code_interpreter"}],
  model="gpt-4-turbo",
)
```
So this seems like langchain code should be updated.
I can do the job and pull request if it helps.

**Comment by jjehl** [comment]
I confirm. The code doesn't work on v2 assistant:

Here the changes:
https://platform.openai.com/docs/assistants/migration/what-has-changed

Is is always possible to use assistant v1 by installing an old version of openai<=1.20
But v1 will be drop by openai, so I don't think this is necessary to maintain v1 with langchain.

**Comment by Surya-Kanta** [comment]
I have already created an pull request (PR) pproposin an update to this issue. Please verify if you can.
https://github.com/langchain-ai/langchain/pull/21484

Thanks
Surya
