### ISSUE TITLE
Langchain  ConversationChain.apply 没有加载memory 中的key导致了key error

### ISSUE THREAD

**Issue by huangheLee** [langchain-ai/langchain#20785]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os
from common import constants
from langchain.chat_models import ChatOpenAI
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory

chat = ChatOpenAI(
    base_url=constants.BASE_URL,
    openai_api_key=constants.API_KEY
)

# 创建 Memory
memory = ConversationBufferMemory(return_messages=True)

# 将 Memory 封装到 ConversationChain
conversation = ConversationChain(llm=chat, memory=memory)
print(conversation.prompt.template)

# response = conversation.predict(input="请问中国的首都是哪里？")
# print(response)
response = conversation.apply([{"input": "请问中国的首都是哪里？"}])
print(response)

### Error Message and Stack Trace (if applicable)

Current conversation:
{history}
Human: {input}
AI:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/syxy/lib/python3.8/site-packages/langchain/chains/llm.py", line 157, in apply
    raise e
  File "/opt/anaconda3/envs/syxy/lib/python3.8/site-packages/langchain/chains/llm.py", line 154, in apply
    response = self.generate(input_list, run_manager=run_manager)
  File "/opt/anaconda3/envs/syxy/lib/python3.8/site-packages/langchain/chains/llm.py", line 78, in generate
    prompts, stop = self.prep_prompts(input_list, run_manager=run_manager)
  File "/opt/anaconda3/envs/syxy/lib/python3.8/site-packages/langchain/chains/llm.py", line 105, in prep_prompts
    selected_inputs = {k: inputs[k] for k in self.prompt.input_variables}
  File "/opt/anaconda3/envs/syxy/lib/python3.8/site-packages/langchain/chains/llm.py", line 105, in <dictcomp>
    selected_inputs = {k: inputs[k] for k in self.prompt.input_variables}
KeyError: 'history'
python-BaseException

### Description

调用predict方法可以正常执行
调用apply方法报错，没有history key 
history key 是memory 的key

apply方法 没有经过chain的 __call__方法
直接调用llm 的generate_prompt方法
导致了报错

### System Info

langchain @ file:///home/conda/feedstock_root/build_artifacts/langchain_1685957913682/work
langchain-core @ file:///home/conda/feedstock_root/build_artifacts/langchain-core_1703029179104/work

macos
python 3.8.5

**Comment by liugddx** [comment]
Use ```conversation.invoke``` instead

**Comment by huangheLee** [comment]
ConversationChain 的提示词有2个变量  input , history 
字段input为用户输入
字段history 是基类Chain中__call__方法自动添加的memory_key


但是ConversationChain.apply 其实是调用的基类LLMChain.apply, 
因为LLMChain.apply没有走__call__方法，所以产生了报错

**Comment by huangheLee** [comment]
使用batch方法替代apply 后没有问题
