### ISSUE TITLE
Issuw with passing two prompts as input to `conversationchain`

### ISSUE THREAD

**Issue by rajveer43** [langchain-ai/langchain#20797]
Hi

**Comment by CD-rajveer** [comment]
closse  this issue

**Comment by CD-rajveer** [comment]
@dosubot close this issue

**Comment by CD-rajveer** [comment]
hey @sbusso I want to close this issue

**Comment by sbusso** [comment]
> hey @sbusso I want to close this issue

@CD-rajveer, why are you tagging me?

**Comment by CD-rajveer** [comment]
I am not able to close it from my side, it does not showing the button

**Comment by sbusso** [comment]
@CD-rajveer I can't help you about that, please stop tagging randonly.

**Comment by sbusso** [comment]
@CD-rajveer also you may have more chances connecting with the user who created the issue @rajveer43
