### ISSUE TITLE
BedrockChat is using GPT2 Tokenzier rather than LlamaTokenizer

### ISSUE THREAD

**Issue by jameschanx** [langchain-ai/langchain#20807]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
model_id = "meta.llama2-70b-chat-v1"
llm = BedrockChat(model_id=model_id, model_kwargs={"temperature": 0.5})
llm.get_num_tokens("this is a text")
```

### Error Message and Stack Trace (if applicable)

'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f55346aa800>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: *****')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json

### Description

I noticed BedrockChat is using GPT2 Tokenizer rather than LlamaTokenizer for the meta.llama2-70b-chat-v1 model

I first found this out when using Langchain in a network-isolated environment and was getting this error, where it's try to download gpt2 tokenizer_config,

The network error itself is not the problem but rather BedRockChat is not using the right tokenizer when doing token count.   The code snippet I was executing was this.

I traced back to to the parent class [BaseLanguageModel](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/language_models/base.py) and noticed it is in fact using GPT2 Tokenizer. 

### System Info

`!pip freeze | grep langchain`
```
langchain==0.1.16
langchain-community==0.0.33
langchain-core==0.1.45
langchain-text-splitters==0.0.1
langchainplus-sdk==0.0.20
```

**Comment by qingdengyue** [comment]
may `langchain-aws` 
[https://github.com/langchain-ai/langchain-aws](https://github.com/langchain-ai/langchain-aws)
