### ISSUE TITLE
DOC:  example code, docs, and other spots involving invoking an anthropic model object can be confusing

### ISSUE THREAD

**Issue by TheOriginalSujay** [langchain-ai/langchain#20865]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Examples: https://github.com/search?q=repo%3Alangchain-ai%2Flangchain+%22model+%3D+chatAnthropic%22&type=code

In several places, we start using an Anthropic model likes this: `model = ChatAnthropic(model='claude-3-opus-20240229')`

This is confusing for someone reading the code/docs for 2 reasons:

1. The pattern we typically use elsewhere (sometimes even for using `ChatAnthropic`, is by assigning it to "llm" instead of "model"
2. "model" is a parameter that the downstream user often assigns a particular argument (the specific Anthropic model).  This is the primary opportunity for confusion IMO.  We are working with a "model" parameter, and also creating an object that is called "model".  

This is by no means a major issue, but it's something that I came across, and it might be worth addressing for consistency and communication reasons.

I am happy to open a PR to address this throughout the repo.

### Idea or request for content:

Where possible with reasonable effort (so not messing with too many downstream stuff), change `model = ChatAnthropic(model='...')` to `llm = ChatAnthropic(model='...')` or similar.

**Comment by sepiatone** [comment]
Another suggestion would be to use it as ```model = ChatAnthropic(model_name="...", ...)```

@TheOriginalSujay As you mention, consistency and clarity are important. There is already an effort underway to standardize initializing arguments. Please head over to #20085 to discuss and possibly help!
