### ISSUE TITLE
cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)

### ISSUE THREAD

**Issue by tejasingle19** [langchain-ai/langchain#20885]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

**import asyncio
from semantic_kernel import Kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion, AzureChatCompletion
from semantic_kernel.prompt_template import PromptTemplateConfig
from semantic_kernel.utils.settings import openai_settings_from_dot_env, azure_openai_settings_from_dot_env**

### Error Message and Stack Trace (if applicable)

Exception has occurred: ImportError
cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)
  File "C:\Users\TINGLE\Downloads\1\import asyncio.py", line 4, in <module>
    from semantic_kernel.prompt_template import PromptTemplateConfig
ImportError: cannot import name 'PromptTemplateConfig' from 'semantic_kernel.prompt_template' (unknown location)

### Description

Getting this error while trying to import the below libraries:

### System Info

NA

**Comment by eyurtsev** [comment]
wrong library
