### ISSUE TITLE
Is langchain able to process batch prompt?

### ISSUE THREAD

**Issue by Bookraint** [langchain-ai/langchain#209]
Sorry to disturb,I wonder if langchain could process a batch of prompts or it just process each text by calling llm(text)?

**Comment by hwchase17** [comment]
Currently just goes text by text. Should be easy to expose a batch method though.

what’s the use case? Is it just to add it onto the LLM class or do you want it as part of a chain as well?

**Comment by Bookraint** [comment]
> 

Every text in a batch is independent with the same prompt templet, but it is slow to call llm() text by text now.So I wonder if there exits better method to get all the results faster :)

**Comment by hwchase17** [comment]
there is now a generate endpoint, which LLMs can use to batch requests: https://langchain.readthedocs.io/en/latest/examples/prompts/llm_functionality.html

the batching is implemented only for openai at the moment

what LLM provider are you using?
