### ISSUE TITLE
On the latest version 0.0.123 i get   No module named 'langchain.chains.chat_index'

### ISSUE THREAD

**Issue by fatjoni** [langchain-ai/langchain#2090]
I am using the latest version and i get this error message while only trying to:
from langchain.chains.chat_index.prompts import CONDENSE_QUESTION_PROMPT

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 3
      1 from langchain.chains import LLMChain
      2 from langchain.chains.question_answering import load_qa_chain
----> 3 from langchain.chains.chat_index.prompts import CONDENSE_QUESTION_PROMPT

ModuleNotFoundError: No module named 'langchain.chains.chat_index'

**Comment by Wzy210121** [comment]
I also encountered this problem

**Comment by mofahad** [comment]
can you try this from langchain.chains.conversational_retrieval.prompts import CONDENSE_QUESTION_PROMPT

**Comment by Wzy210121** [comment]
Thanks! got it from the default config     "ConversationalRetrievalChain.from_llm()"

**Comment by ValtersJZ** [comment]
I get a similar issue:

After installing pip install langchain[all]

These two imports don't work:
from langchain.chains.**question_answering** import load_qa_chain
from langchain.**callbacks** import get_openai_callback


Traceback (most recent call last):
  File "C:\Users\valte\PycharmProjects\ChatWithPDF\main.py", line 1, in <module>
    from langchain.chains.question_answering import load_qa_chain
ModuleNotFoundError: No module named 'langchain.chains.question_answering'

Any advice would be much appreciated.

**Comment by Safakan** [comment]
I noticed it today. I have an exact problem with the above, I can't import these two anymore:
from langchain.chains.question_answering import load_qa_chain
from langchain.callbacks import get_openai_callback

I've tried what is suggested above and installed langchain with conda with this command:
conda install -c conda-forge langchain


still not working. Any suggestions?

**Comment by AnkitBasrur** [comment]
I faced the same issue today. Corrected it by updating the python version to 3.11.2

**Comment by Safakan** [comment]
This is probably due to some conflict in other packages in your environment.
I've set up a fresh environment from scratch and it worked again.

**Comment by jawndiego** [comment]
resolved the issue by running a pip install 'langchain[all]' which seems to be overkill. when i have a bit more time ill try to isolate which particular package corresponds to:

from langchain.chains.question_answering import load_qa_chain

**Comment by abdul12022skipq** [comment]
I am facing the problem with this import 
`from langchain.chains.openai_functions import create_qa_with_structure_chain`

it is giving an error 
No module named 'langchain.chains.openai_functions'

**Comment by SchlackBoles** [comment]
I am trying to do it on a server I rent but the server has Python 3.7.3. Is there a way to downgrade langchain?

**Comment by MannJadwani** [comment]
have the same issue there not able to import anything from openai_functions
