### ISSUE TITLE
Langfuse was not able to parse the LLM model.

### ISSUE THREAD

**Issue by marco-introvigne** [langchain-ai/langchain#20915]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
langfuse_handler = CallbackHandler(
    secret_key="sk-lf-...",
    public_key="pk-lf-...",
    host="host.."
    ...
)

prompt_template = ChatPromptTemplate.from_template(
    template=prompt,
)

llm = BedrockChat(
        credentials_profile_name=profile,
        model_id=model_id,
        client=client,
        model_kwargs=model_kwargs,
        verbose=verbose,
        callbacks=[langfuse_handler],
    )

output_parser = StrOutputParser()

chain = prompt_template | llm | output_parser

output = chain.invoke(
    input={"color": "red"},
    config={"callbacks": [langfuse_handler]},
)
```

### Description

I’ve encountered a persistent issue with the latest versions of langchain, langchain-core, and langchain community. The problem arises when the system fails to recognize the model, which results in the following warning message:

`WARNING:langfuse:Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration.`

This issue prevents the correct tracing of model usage and pricing on Langfuse.

Interestingly, when I revert to older versions of the packages (langchain v0.1.13, langchain community v0.0.31, and langchain-core v0.1.39), the warning no longer appears, and Langfuse operates as expected.

### System Info

langchain-core==0.1.46
langchain-community==0.0.34
langchain==0.1.16

**Comment by juan-abia** [comment]
Any news on this bug? This is blocking me from upgrading langchain:(

**Comment by axiangcoding** [comment]
I think you should open an issue in the Langfuse repository. The `langfuse_handler ` maintained by the Langfuse community, not Langchain.
