### ISSUE TITLE
`SQLDatabase.from_databricks` seems to hang indefinitely

### ISSUE THREAD

**Issue by gwenwindflower** [langchain-ai/langchain#20910]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Other values like `DATABRICKS_TOKEN` and `DATABRICKS_HOST` are set in env vars.
```python
from langchain_community.utilities.sql_database import SQLDatabase

db = SQLDatabase.from_databricks(
    catalog="samples", schema="nyctaxi", warehouse_id="<redacted>"
)
result = db.run("SELECT 1")
print(result)
```

### Error Message and Stack Trace (if applicable)

No error message, just hangs indefinitely, I can't find a way to introspect what's going on.

### Description

I'm trying to create an instance of SQLDatabase from Databricks configs, would expect to get an error or for there to be some type of output. I've pared the code down from a more expansive agent workflow to just this and pinned it down to the `from_databricks` call that's just hanging. Super appreciate any insight. I don't see anybody else having this problem, but I also can't see anything wrong in my configs after hours of troubleshooting. Thanks in advance 🙏🏻 .

### System Info

```
System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:
22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112
> Python Version:  3.11.8 (main, Apr  7 2024, 16:30:13) [Clang
 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.1.46
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.51
> langchain_experimental: 0.0.57
> langchain_openai: 0.1.3
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by harrytran001** [comment]
Do you have any idea on this. I faced the same problem

**Comment by sakibccr** [comment]
I am also getting the same issue with the following versions:

```
langchain==0.2.15
langchain-community==0.2.14
langchain-core==0.2.36
langchain-google-vertexai==1.0.10
langchain-openai==0.1.23
langchain-text-splitters==0.2.2
```

**Comment by harrytran001** [comment]
> I am also getting the same issue with the following versions:
> 
> ```
> langchain==0.2.15
> langchain-community==0.2.14
> langchain-core==0.2.36
> langchain-google-vertexai==1.0.10
> langchain-openai==0.1.23
> langchain-text-splitters==0.2.2
> ```

I think it does not hang indefinitely. It just hang for so long. It took me like 10-minutes to finish. I think it is probably the issue from DataBricks.

**Comment by sakibccr** [comment]
@harrytran001 I tried keeping it running for a long time. I also think it could be an issue on the Databricks. I will dig from that side now.

**Comment by sakibccr** [comment]
It seems to be hanging for a long time. I could get it working passing the `lazy_table_reflection` param found [here](https://api.python.langchain.com/en/latest/utilities/langchain_community.utilities.sql_database.SQLDatabase.html).

```python
db = SQLDatabase.from_databricks(
    catalog="samples",
    schema="nyctaxi",
    warehouse_id="<redacted>",
    lazy_table_reflection=True
)
```

**Comment by borja-rojo-ilvento** [comment]
Hello! Reviving this as I get the same issue, with the same solution. Seems unintuitive. I'd like to know a way to make this work "cleanly".

```
langchain>=0.3,<0.4
langchain-core>=0.3,<0.4
langchain-openai>=0.2,<0.3
langchain-community>=0.3.2
langgraph>=0.2.22
langgraph-checkpoint-postgres==2.0.1
```

Might this community feature be moved to the new langchain-databricks package?
