### ISSUE TITLE
Multiple openai keys

### ISSUE THREAD

**Issue by zainabalthafeeri1** [langchain-ai/langchain#2091]
Hello i'm trying to provide a diifferent API key for each profile, but it seems that the last profile API key i set is the one used by all the profiles, is there a way to force use each profile its dedicated key?

**Comment by Tanmay3132** [comment]
can you explain more about the issue

**Comment by zainabalthafeeri1** [comment]
I have a use case in which I have multiple profiles (profile 'a' profile 'b', profile 'c'). Each profile must have its key to use embedding and completion models; the issue is when I tried to set the API key for each profile using `OpenAI(openai_api_key=self.api_key)` and then tried to query anything for profile 'a' the API key used was the one set for profile 'c'.

**Comment by zainabalthafeeri1** [comment]
I think the API keys traversed, but it changed each time I add a new profile

**Comment by leonnewton** [comment]
> Hello i'm trying to provide a diifferent API key for each profile, but it seems that the last profile API key i set is the one used by all the profiles, is there a way to force use each profile its dedicated key?

It seems that each time you initalize a chains or llm object, it will set openai.api_key. So finally you will get the last api_key. The solution is to set openai.api_key before you conduct a query.

**Comment by parulekarmihir** [comment]
How can I do that if I am using different api_base and api_key for embedding and completion endpoint? How can I run a coversationalRetrivalChain as either of the embedding or completion model fails with a resource not found error?

**Comment by FlowerWrong** [comment]
I have the same problem. I have multi api keys with different model support, some gpt-3.5-turbo and some gpt-4, I can not use it alone, eg: in one agent with embedding and chat completion.

**Comment by vlerenc** [comment]
Same thing, but does the OpenAI API even support that? It's module-static, so it's pretty hopeless unless you do not use it and switch to ReST/`requests` directly or is there another way?
