### ISSUE TITLE
openai:error_code=None error_message='Too many inputs for model None. The max number of inputs is 1.

### ISSUE THREAD

**Issue by ShubhamVerma16** [langchain-ai/langchain#2096]
while using llama_index GPTSimpleVectorIndex
I am reading a pdf file using SimpleDirectoryReader.

I am unable to create index for the file and it is generating the below error:

 **INFO:openai:error_code=None error_message='Too many inputs for model None. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False**

The code works for some files and fails for others with the above error.

Please suggest what does it mean by **Too many inputs for model** that comes as a error only for some files.

**Comment by mofahad** [comment]
can you provide code snippets

**Comment by ShubhamVerma16** [comment]
Please find the below code snippet

max_input_size = 500
num_output = 48
max_chunk_overlap = 20


llm = AzureOpenAI(deployment_name=engine)
llm_predictor = LLMPredictor(llm=llm)

# prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)


documents = SimpleDirectoryReader('data').load_data()



index = GPTSimpleVectorIndex(documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper)

# response = index.query(<query>)

**Comment by mofahad** [comment]
I think this is the issue of llama index lib

**Comment by ddxgz** [comment]
Hi, I face the same error when I'm using only `langchain` modules. 

Related issues in `llama-index`:
- https://github.com/jerryjliu/llama_index/issues/947
- https://github.com/jerryjliu/llama_index/issues/823

Code snippet:
```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.chat_models import AzureChatOpenAI
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
from langchain.document_loaders import TextLoader

documents_folder = "text.txt"

loader = TextLoader(documents_folder)
documents = loader.load()

text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(documents)

llm = AzureChatOpenAI(
    deployment_name="gpt-35-turbo-0301",
    temperature=0,
)

embeddings = OpenAIEmbeddings(
    deployment="text-embedding-ada-002",
)

vectorstore = Chroma.from_documents(documents, embeddings)
qa = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever()
)

query = "How many vacation days do I have?"
print(qa.run(query))
```

**Comment by alisalih1** [comment]
Good afternoon, I am hitting the same. Any updates?

**Comment by mingjun1120** [comment]
> Hi, I face the same error when I'm using only `langchain` modules.
> 
> Related issues in `llama-index`:
> 
> * [openai:error_code=None error_message='Too many inputs for model None. The max number of inputs is 1. jerryjliu/llama_index#947](https://github.com/jerryjliu/llama_index/issues/947)
> * [Azure OpenAI : Token indices sequence length is longer than the specified maximum sequence length for this model jerryjliu/llama_index#823](https://github.com/jerryjliu/llama_index/issues/823)
> 
> Code snippet:
> 
> ```
> from langchain.embeddings.openai import OpenAIEmbeddings
> from langchain.vectorstores import Chroma
> from langchain.chat_models import AzureChatOpenAI
> from langchain.text_splitter import CharacterTextSplitter
> from langchain.chains import RetrievalQA
> from langchain.document_loaders import TextLoader
> 
> documents_folder = "text.txt"
> 
> loader = TextLoader(documents_folder)
> documents = loader.load()
> 
> text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> documents = text_splitter.split_documents(documents)
> 
> llm = AzureChatOpenAI(
>     deployment_name="gpt-35-turbo-0301",
>     temperature=0,
> )
> 
> embeddings = OpenAIEmbeddings(
>     deployment="text-embedding-ada-002",
> )
> 
> vectorstore = Chroma.from_documents(documents, embeddings)
> qa = RetrievalQA.from_chain_type(
>     llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever()
> )
> 
> query = "How many vacation days do I have?"
> print(qa.run(query))
> ```

You are required to **assign 1** to the `chunk_size` parameter in the `OpenAIEmbeddings()` function. By default, the `chunk_size` was assigned to 1000.

Meanwhile, the `deployment` parameter in the `OpenAIEmbeddings()` function is the deployment name of your model in Azure and the `deployment_name` parameter in the `AzureChatOpenAI()` function is the deployment name of your model in Azure as well. For example:

**<u>Azure OpenAI:</u>**
![image](https://github.com/hwchase17/langchain/assets/54136320/bd4ed3fc-14f1-4339-a39c-d97ab1d9b62b)

**<u>Google Colab Code:</u>**
![image](https://github.com/hwchase17/langchain/assets/54136320/f20d9235-ef66-49d7-aa6b-58e2135b55ac)
