### ISSUE TITLE
DOC: HuggingFaceEndpoint documentation incorrect for importing

### ISSUE THREAD

**Issue by hdvsarm** [langchain-ai/langchain#20977]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The documentation here: https://python.langchain.com/docs/integrations/llms/huggingface_endpoint/ has incorrect import code (not sure if recent change caused it to not work). 

Currently states: from langchain_community.llms import HuggingFaceEndpoint
Correct: from langchain_community.llms**.huggingface_endpoint** import HuggingFaceEndpoint

Found while trying to follow the documentation

### Idea or request for content:

A minor change needs to be made to first code block on page

**Comment by jandevel** [comment]
@hdvsarm please, close the issue.
The import is correct, check the [discussion for the related PR](https://github.com/langchain-ai/langchain/pull/21569#discussion_r1597488679)
