### ISSUE TITLE
Problem with using DDG as search tool

### ISSUE THREAD

**Issue by barshag** [langchain-ai/langchain#21045]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

### Error Message and Stack Trace (if applicable)

    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DuckDuckGoSearchAPIWrapper
__root__
  deprecated() got an unexpected keyword argument 'name' (type=type_error)

### Description

trying to use with crewai

### System Info

can't

**Comment by qingdengyue** [comment]
Can the complete code be provided？

**Comment by barshag** [comment]
It stuck at this stage... you can see it as complete code

**Comment by Sachin-Bhat** [comment]
Please ensure that you have updated to the latest version of `langchain-community` and `duckduckgo-search`.

```
pip install -U langchain-community duckduckgo-search
```

Maybe try this out:

```python
from langchain_community.tools import DuckDuckGoSearchRun

search_tool = DuckDuckGoSearchRun()

print(search_tool.run("who is the current prime minister of India"))
```

Cheers,
Sachin

**Comment by TkTakaro** [comment]
> Please ensure that you have updated to the latest version of `langchain-community` and `duckduckgo-search`.
> 
> ```
> pip install -U langchain-community duckduckgo-search
> ```
> 
> Maybe try this out:
> 
> ```python
> from langchain_community.tools import DuckDuckGoSearchRun
> 
> search_tool = DuckDuckGoSearchRun()
> 
> print(search_tool.invoke("who is the current prime minister of India"))
> ```
> 
> Cheers, Sachin

Just to follow-up with OP's issue, this code is not currently functional:
![image](https://github.com/langchain-ai/langchain/assets/149630336/dd791998-2546-4d40-beba-8a6f53afe938)

Here's the other end of the traceback:
![image](https://github.com/langchain-ai/langchain/assets/149630336/89cf0b8e-613f-4358-b31b-9aba46c53493)

**Comment by qingdengyue** [comment]
> > Please ensure that you have updated to the latest version of `langchain-community` and `duckduckgo-search`.
> > ```
> > pip install -U langchain-community duckduckgo-search
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe try this out:
> > ```python
> > from langchain_community.tools import DuckDuckGoSearchRun
> > 
> > search_tool = DuckDuckGoSearchRun()
> > 
> > print(search_tool.invoke("who is the current prime minister of India"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Cheers, Sachin
> 
> Just to follow-up with OP's issue, this code is not currently functional: ![image](https://private-user-images.githubusercontent.com/149630336/329688732-dd791998-2546-4d40-beba-8a6f53afe938.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTUyNjIsIm5iZiI6MTcxNTM5NDk2MiwicGF0aCI6Ii8xNDk2MzAzMzYvMzI5Njg4NzMyLWRkNzkxOTk4LTI1NDYtNGQ0MC1iZWJhLThhNmY1M2FmZTkzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMjM2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjQ1MjUyN2MyNDMxZmIzZDRkYjU5YWZmOWFlYzE2YTZiOWFmOWNmNDc1ZmMwNGJlMjNlZjE5YzZjMDJkODA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xw46NGbac2o3Yw1TKrrZOS09nqlkCeXEH7u0gHuebQE)
> 
> Here's the other end of the traceback: ![image](https://private-user-images.githubusercontent.com/149630336/329688922-89cf0b8e-613f-4358-b31b-9aba46c53493.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzOTUyNjIsIm5iZiI6MTcxNTM5NDk2MiwicGF0aCI6Ii8xNDk2MzAzMzYvMzI5Njg4OTIyLTg5Y2YwYjhlLTYxM2YtNDM1OC1iMzFiLTlhYmE0NmM1MzQ5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwMjM2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWEyZjA5ZGE3MWI1MDI1MGRjYWNjN2FlZjA3Y2ZjMjdhYmNhMzI0Y2IyYzg0NjE5M2RiNzExOTE2ZDc1ZTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cTdIhklGJoVsHJT1-gSMFzT9uU9X58Y1H7k5K72fPvM)
> 
> Thanks for your help!
> 
> * Tyler

Windows ?
