### ISSUE TITLE
Azure AI Studio Llama3 Models incompatible with `AzureMLChatOnlineEndpoint`

### ISSUE THREAD

**Issue by StefanB7** [langchain-ai/langchain#21060]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
from langchain_community.chat_models.azureml_endpoint import AzureMLChatOnlineEndpoint, CustomOpenAIChatContentFormatter, AzureMLEndpointApiType
from langchain_core.messages import HumanMessage

chat = AzureMLChatOnlineEndpoint(endpoint_url="https://Meta-Llama-3-70B-Instruct-pixvc-serverless.swedencentral.inference.ai.azure.com", 
                                 deployment_name="Meta-Llama-3-70B-Instruct-pixvc", 
                                 endpoint_api_type=AzureMLEndpointApiType.serverless, 
                                 endpoint_api_key="<your-api-key>",
                                 content_formatter=CustomOpenAIChatContentFormatter())

response = chat.invoke([HumanMessage("Hello, how are you?")])
print(response)
```

### Error Message and Stack Trace (if applicable)

``` console
ValidationError: 2 validation errors for AzureMLOnlineEndpoint
endpoint_api_type
  Endpoints of type `serverless` should follow the format `[https://<your-endpoint>.<your_region>.inference.ml.azure.com/v1/chat/completions`](https://%3Cyour-endpoint%3E.%3Cyour_region%3E.inference.ml.azure.com/v1/chat/completions%60) or `[https://<your-endpoint>.<your_region>.inference.ml.azure.com/v1/chat/completions`](https://%3Cyour-endpoint%3E.%3Cyour_region%3E.inference.ml.azure.com/v1/chat/completions%60) (type=value_error)
content_formatter
  Content formatter f<class 'langchain_community.chat_models.azureml_endpoint.CustomOpenAIChatContentFormatter'> is not supported by this endpoint. Supported types are [<AzureMLEndpointApiType.dedicated: 'dedicated'>, <AzureMLEndpointApiType.serverless: 'serverless'>] but endpoint is None. (type=value_error)
```

### Description

I'm attempting to use the llama3 70B model via Azure AI Studio with langchain. However, the target I receive from Azure AI Studio for the model is https://Meta-Llama-3-70B-Instruct-pixvc-serverless.swedencentral.inference.ai.azure.com. I encounter an error stating that my endpoint is not in the correct format.

### System Info

```
System Information
------------------
> OS:  Linux
> OS Version:  #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024
> Python Version:  3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]

Package Information
-------------------
> langchain_core: 0.1.46
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.51
> langchain_openai: 0.1.4
> langchain_text_splitters: 0.0.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve
```

**Comment by StefanB7** [comment]
My mistake. I needed to add `v1/chat/completions` to the end of my endpoint url.
In the snippet above: `https://Meta-Llama-3-70B-Instruct-pixvc-serverless.swedencentral.inference.ai.azure.com/v1/chat/completions/`

**Comment by matibarrivera** [comment]
I get an ssl.SSLCertVerificationError. Is your code working?

**Comment by matibarrivera** [comment]
Is anyone is facing the SSL error, what resolves the issue for me was a missing configuration in my mac. This is the link to the stackoverflow thread that helped me (I used the second answer) https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
