### ISSUE TITLE
Installation of langchain on miniconda with the conda install langchain -c conda-forge fails

### ISSUE THREAD

**Issue by vmahdev** [langchain-ai/langchain#21084]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

conda install langchain -c conda-forge

### Error Message and Stack Trace (if applicable)

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - langchain

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

### Description

Installation problem 

### System Info

 pip freeze | grep langchain as expected none 
Python 3.7.3
miniconda on linux

**Comment by eyurtsev** [comment]
Python 3.7.3 is no longer supported. Please upgrade to a more recent version of python.

**Comment by eyurtsev** [comment]
Closing as likely not an issue. Feel free to re-open if unable to install with newer version of python
