### ISSUE TITLE
NotImplementedError where using LangChain create_tool_calling_agent without further details

### ISSUE THREAD

**Issue by Waelaburezeq** [langchain-ai/langchain#21102]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

tool_n = [BingSearchAPIWrapper()]

system_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful assistant. Make sure to use the tavily_search_results_json tool for information.",
        ),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

# Construct the Tools agent

agent = create_tool_calling_agent(llm=llm_langchain_ChatOpenAI, 
                                  tools = tool_n,
                                  prompt = system_prompt)

agent_executor = AgentExecutor(agent=agent,tools=tools,verbose=True)
agent_executor.invoke({"input":"What is 2*2"})

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-12-fe75faac265c>](https://localhost:8080/#) in <cell line: 18>()
     16 
     17 
---> 18 agent = create_tool_calling_agent(llm=llm_langchain_ChatOpenAI, 
     19                                   tools = tool_n,
     20                                   prompt = system_prompt)

1 frames
[/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py](https://localhost:8080/#) in bind_tools(self, tools, **kwargs)
    910         **kwargs: Any,
    911     ) -> Runnable[LanguageModelInput, BaseMessage]:
--> 912         raise NotImplementedError()
    913 
    914 

NotImplementedError:

### Description

I am trying to use create_tool_calling_agent

### System Info

google colab : !pip install -q langchain

**Comment by ccurme** [comment]
Hi @Waelaburezeq, can you share what is `llm_langchain_ChatOpenAI`?

OpenAI chat models should be imported from `langchain_openai`. You will need to `pip install --upgrade langchain-openai` to use it if you have not already.

Then you can `from langchain_openai import ChatOpenAI`.

**Comment by Waelaburezeq** [comment]
It is just an instance name of LangCha8n OpenAI, 

The issue is not there anymore,  I re installed the library

**Comment by eyurtsev** [comment]
Closing issue in that case!

**Comment by codingBuddh** [comment]
> Hi [@Waelaburezeq](https://github.com/Waelaburezeq), can you share what is `llm_langchain_ChatOpenAI`?
> 
> OpenAI chat models should be imported from `langchain_openai`. You will need to `pip install --upgrade langchain-openai` to use it if you have not already.
> 
> Then you can `from langchain_openai import ChatOpenAI`.

Thanks this was helpfull
