### ISSUE TITLE
Empty Embeddings propertie when returning from Indexing a document

### ISSUE THREAD

**Issue by jabrPromtior** [langchain-ai/langchain#21119]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
embeddings = AzureOpenAIEmbeddings(
    model="text-embedding-3-small",
    azure_deployment="text-embedding-3-small",
    openai_api_version="2024-02-01",
)

vectorstore = Chroma(
    collection_name="cv_collection",
    embedding_function=embeddings,
)

st.session_state.record_manager = SQLRecordManager(
      db_url="sqlite:///:memory:",
      namespace="chroma/cv_collection",
  )

def add_document_to_vectorStore(vectorStore, document, record_manager):
  # Index the new document in the vector store with incremental cleanup
  index(
      [document],  # Pass a list of documents
      record_manager,
      vectorStore,
      cleanup="incremental",
      source_id_key="source",
  )
```

### Description

Hi, im trying to embed a document in a Chroma vector store, my issue is that when i call the Index function it does index it but it adds it as documents and not their corresponding embeddings, also when i call the function i can see the Embeddings request to openAI going out, but then the dump returns and  "embeddings": null followed by the whole document like this:

```json
{
  "ids": [
    "a68dbda2-06bf-50df-b460-f2d1cd8dc8c0"
  ],
  "embeddings": null,
  "metadatas": [
    {
      "departamento": "Artigas",
      "idioma": "Inglés, Portugues",
      "nivel_educativo": "TERCERIA_SUPERIOR",
      "source": "Laura Texeira._.pdf"
    }
  ],
  "documents": [
    "Text"
  ],
  "uris": null,
  "data": null
}
```

I have tried from creating a small proyect with only this to already reading all the chromadb and langchain indexing documentation, to changing from embeddings to the client for AzureOpenAI and the embeddings are being computed perfectly everytime, i also can see the request coming back as 200 OK, so i dont really know where else to look outside de Index function and thats why i think is a bug.

### System Info

Im in a docker container with the latest versions of this packages:
- streamlit
- pdfplumber
- openai
- pydantic
- langchain
- langchain-community
- langchain-core
- langchain-openai
- chromadb
- pysqlite3-binary 
- lark

and a base image of python:3.9-slim-buster

**Comment by rsk2327** [comment]
@jabrPromtior Are you simply trying to add a new document into the chroma database? Im not sure what is the index function that you are referring to, but why not use the vectorstore's `add_texts` method to include your document?

And the reason the dump shows embeddings as null is because the `get` method of Chroma by default doesnt return embeddings. You have to provide 'embeddings' as an input to the include `argument` to retrieve the embeddings as well

**Comment by jabrPromtior** [comment]
Hi, thank you for the reply, im using de Index method since is the standard way of indexing in the vectorstore with a record manager according to the langchain documentation: https://python.langchain.com/docs/modules/data_connection/indexing/

Using the add_texts AND using the include i can see the embeddings now, but my issue is that doesnt manage a record manager like de index function, and im going to be uploading several documents and new versions of older documents to the vectorstore, thats why i needed the cleanup="incremental" from Index:
```python
def add_document_to_vectorStore(vectorStore, document):
    # Add the new document to the vector store
    vectorStore.add_texts([document.page_content])
```
Thank you for the help
