### ISSUE TITLE
Unable save embeddings in Redis vectorstore

### ISSUE THREAD

**Issue by arunasujith** [langchain-ai/langchain#2113]
I'm trying to save embeddings in Redis vectorstore and when I try to execute getting the following error. Any idea if this is a bug or if anything is wrong with my code? Any help is appreciated.

langchain version - both 0.0.123 and 0.0.124
Python 3.8.2

File "/Users/aruna/PycharmProjects/redis-test/database.py", line 16, in init_redis_database
  rds = Redis.from_documents(docs, embeddings, redis_url="redis://localhost:6379", index_name='link')
File "/Users/aruna/PycharmProjects/redis-test/venv/lib/python3.8/site-packages/langchain/vectorstores/base.py", line 116, in from_documents
  return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
File "/Users/aruna/PycharmProjects/redis-test/venv/lib/python3.8/site-packages/langchain/vectorstores/redis.py", line 224, in from_texts
  if not _check_redis_module_exist(client, "search"):
File "/Users/aruna/PycharmProjects/redis-test/venv/lib/python3.8/site-packages/langchain/vectorstores/redis.py", line 23, in _check_redis_module_exist
  return module in [m["name"] for m in client.info().get("modules", {"name": ""})]
File "/Users/aruna/PycharmProjects/redis-test/venv/lib/python3.8/site-packages/langchain/vectorstores/redis.py", line 23, in <listcomp>
  return module in [m["name"] for m in client.info().get("modules", {"name": ""})]
**TypeError: string indices must be integers**

Sample code as follows.

REDIS_URL = 'redis://localhost:6379'

def init_redis_database(docs):
    embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)
    rds = Redis.from_documents(docs, embeddings, redis_url=REDIS_URL, index_name='link')

**Comment by arunasujith** [comment]
Update on this, I debugged the client.info().get("modules", {"name": ""}) in line langchain.vectorstores.redis.py file line 23 and I found there are no modules returned though I have 5 redis modules installed.  So I edit the library source code as follows and was able to store the embeddings in redis db. Not sure exact reason why modules are not returned for the client instance.

def _check_redis_module_exist(client: RedisType, module: str) -> bool:
    return True

**Comment by hx23840** [comment]
Please confirm that you are using the Redis Stack,Below is the official documentation
[https://redis.io/docs/stack/about/](url)

**Comment by tylerhutcherson** [comment]
Will take a look at improving this error handling.

**Comment by chrischjh** [comment]
Got same error

`
//...
    loader = PyPDFLoader(fpath)
    pages = loader.load_and_split()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=20)
    docs = text_splitter.split_documents(pages)
    embeddings = OpenAIEmbeddings()
    rds = Redis.from_documents(docs, embeddings, redis_url="redis://localhost:6379", index_name='link')
`

**Comment by Smyja** [comment]
> Got same error
> 
> ```
>     loader = PyPDFLoader(fpath)
>     pages = loader.load_and_split()
>     text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=20)
>     docs = text_splitter.split_documents(pages)
>     embeddings = OpenAIEmbeddings()
>     rds = Redis.from_documents(docs, embeddings, redis_url="redis://localhost:6379", index_name='link')
> ```

Have you resolved it?

**Comment by chrischjh** [comment]
> > Got same error
> > 
> > ```
> >     loader = PyPDFLoader(fpath)
> >     pages = loader.load_and_split()
> >     text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=20)
> >     docs = text_splitter.split_documents(pages)
> >     embeddings = OpenAIEmbeddings()
> >     rds = Redis.from_documents(docs, embeddings, redis_url="redis://localhost:6379", index_name='link')
> > ```
> 
> Have you resolved it? 

No, I had to turn to PGVector which works well

**Comment by DvirDukhan** [comment]
@arunasujith which redis-py version are you using?

**Comment by arunasujith** [comment]
@DvirDukhan its redis==4.5.3 library version.

**Comment by DanielCollins** [comment]
I had this error because I had done `brew install redis` but `brew install redis-stack` was needed (otherwise, redis has no modules installed)

**Comment by mmoraisTRT** [comment]
I still having this error and I think I know why.
I'm using Redis Cloud and, after create a redis stack database, the module name for search is "searchlight", but in langchain Redis.py searches for a module called "search".  

Do I have to rebuild langchain, changing it, to make it work? Is there a way to make the code more robust?

**Comment by tylerhutcherson** [comment]
@mmoraisTRT can you share the full output of MODULES LIST command?

**Comment by nathanmeth** [comment]
> I still having this error and I think I know why. I'm using Redis Cloud and, after create a redis stack database, the module name for search is "searchlight", but in langchain Redis.py searches for a module called "search".
> 
> Do I have to rebuild langchain, changing it, to make it work? Is there a way to make the code more robust?

This was my issue as well. I changed search to searchlight in the required modules

**Comment by bern4rdelli** [comment]
@tylerhutcherson We are encountering a similar issue. Please find below the list of packages involved:

```bash
1) 1) "name"
   2) "searchlight"
   3) "ver"
   4) (integer) 20606
2) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 20406
3) 1) "name"
   2) "bf"
   3) "ver"
   4) (integer) 20405
4) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 10809
5) 1) "name"
   2) "graph"
   3) "ver"
   4) (integer) 21009
```

Ps: We are utilizing the free subscription tier of Redis Cloud for our current operations:

![image](https://user-images.githubusercontent.com/11928589/234840379-0eb454f7-b42b-4877-9e06-8292b93c67bb.png)

**Comment by Soleitconsultant** [comment]
Hi, yes still have the same error :(

**Comment by tylerhutcherson** [comment]
@Spartee @baskaryan I believe we need to extend the module check for `searchlight`.

**Comment by mindxblend** [comment]
> I still having this error and I think I know why. I'm using Redis Cloud and, after create a redis stack database, the module name for search is "searchlight", but in langchain Redis.py searches for a module called "search".
> 
> Do I have to rebuild langchain, changing it, to make it work? Is there a way to make the code more robust?

Could you solve it? I'm getting same error
