### ISSUE TITLE
UnicodeEncodeError Using Chat Vector and My Own Data

### ISSUE THREAD

**Issue by yma8888** [langchain-ai/langchain#2121]
I keep getting this error every time I try to ask my data a question using the code from "[chat_vector_db.ipynb](https://github.com/hwchase17/langchain/blob/f356cca1f278ac73f8e59f49da39854e1e47a205/docs/modules/chat/examples/chat_vector_db.ipynb)" notebook, so how can I fix this and is this from my stored data and if it is how can I encode it, also I'm using the UnstructuredFileLoader for a text file:

UnicodeEncodeError                        Traceback (most recent call last)
Cell In[97], line 3
      1 chat_history = []
      2 query = "who are you?"
----> 3 result = qa({"question": query, "chat_history": chat_history})

File [c:\Users\yousef\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\chains\base.py:116](file:///C:/Users/yousef/AppData/Local/Programs/Python/Python39/lib/site-packages/langchain/chains/base.py:116), in Chain.__call__(self, inputs, return_only_outputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116     raise e
    117 self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118 return self.prep_outputs(inputs, outputs, return_only_outputs)

File [c:\Users\yousef\AppData\Local\Programs\Python\Python39\lib\site-packages\langchain\chains\base.py:113](file:///C:/Users/yousef/AppData/Local/Programs/Python/Python39/lib/site-packages/langchain/chains/base.py:113), in Chain.__call__(self, inputs, return_only_outputs)
    107 self.callback_manager.on_chain_start(
    108     {"name": self.__class__.__name__},
    109     inputs,
    110     verbose=self.verbose,
    111 )
    112 try:
--> 113     outputs = self._call(inputs)
    114 except (KeyboardInterrupt, Exception) as e:
    115     self.callback_manager.on_chain_error(e, verbose=self.verbose)
...
-> 1258         values[i] = one_value.encode('latin-1')
   1259     elif isinstance(one_value, int):
   1260         values[i] = str(one_value).encode('ascii')

UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 7: ordinal not in range(256)

**Comment by mofahad** [comment]
To fix this error, you can either change the encoding method to one that supports a wider range of characters, such as UTF-8, or remove the non-ASCII characters from your string. Here's an example code snippet that demonstrates how to encode a string using UTF-8:

such as 
my_string = "Hello “world”"
encoded_string = my_string.encode('utf-8')
print(encoded_string)

**Comment by yma8888** [comment]
> To fix this error, you can either change the encoding method to one that supports a wider range of characters, such as UTF-8, or remove the non-ASCII characters from your string. Here's an example code snippet that demonstrates how to encode a string using UTF-8:
> 
> such as my_string = "Hello “world”" encoded_string = my_string.encode('utf-8') print(encoded_string)

I have already encoded my text file with utf-8 encoding when I scraped it from the PDF file so I'm not sure how to fix this so if you have any insight please let me know.

**Comment by Dayton2028** [comment]
I met same problem, have you solved it? Thanks

**Comment by shinichi-takayanagi** [comment]
I was able to solve this problem by updating Python version(from 3.9.10 to 3.10.10).
I think that the root cause of this problem is due to urllib3 or http module's version (and/or the combination with langchain).

I hope that you find this information useful.

**Comment by yma8888** [comment]
I ran the code on Python 3.10.9 but it shows me the same error message, do you think I should upgrade it to 3.10.10 or it still will not work?

**Comment by shinichi-takayanagi** [comment]
Maybe it's a library version issue, I got it working with in Python 3.10:
- langchain = 0.0.135
- requests = 2.28.2
- urllib3 = 1.26.15

```bash
❯ cat pyproject.toml
[tool.poetry]
name = "jupyter"
version = "0.1.0"
description = ""
authors = ["It's me"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "^3.6.3"
openai = "^0.27.4"
langchain = "^0.0.135"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

```bash
❯ ls /home/.../site-packages | grep -e urllib -e requests
requests
requests-2.28.2.dist-info
urllib3
urllib3-1.26.15.dist-info
```
