### ISSUE TITLE
MoonshotChat moonshot_api_key is invaild for api key

### ISSUE THREAD

**Issue by tears743** [langchain-ai/langchain#21237]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

MoonshotChat(api_key=model.api_key,streaming=True,model=model.name)

### Error Message and Stack Trace (if applicable)

openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Invalid Authentication', 'type': 'invalid_authentication_error'}}

### Description

```
class MoonshotCommon(BaseModel):

    _client: _MoonshotClient

    base_url: str = MOONSHOT_SERVICE_URL_BASE

    moonshot_api_key: Optional[SecretStr] = Field(default=None, alias="api_key")

    model_name: str = Field(default="moonshot-v1-8k", alias="model")

    max_tokens = 1024

    temperature = 0.3
```

The moonshot_api_key type is SecretStr ,when MoonshotChat class build openai client params ,it still use secret string ,

```
client_params = {
            "api_key": values["moonshot_api_key"],

            "base_url": values["base_url"]

            if "base_url" in values

            else MOONSHOT_SERVICE_URL_BASE,

        }
```

 cause the request error: 
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Invalid Authentication', 'type': 'invalid_authentication_error'}}

```
client_params = {
            "api_key": values["moonshot_api_key"]._secret_value, # this will be work

            "base_url": values["base_url"]

            if "base_url" in values

            else MOONSHOT_SERVICE_URL_BASE,

        }
```

### System Info

openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Invalid Authentication', 'type': 'invalid_authentication_error'}}

**Comment by liugddx** [comment]
Let me see.
