### ISSUE TITLE
Retrieving the standalone question from ConversationalRetrievalChain

### ISSUE THREAD

**Issue by nkov** [langchain-ai/langchain#2125]
Is there any way to retrieve the "standalone question" generated during the summarization process of the `ConversationalRetrievalChain`? I was able to print it for debugging [here in base.py](https://github.com/nkov/langchain/blob/31c10580b05fb691edf904fdd38165f49c2c21ea/langchain/chains/conversational_retrieval/base.py#L81) but it would be nice to access it in a more structured way

**Comment by longgui0318** [comment]
you can try promptlayer!

**Comment by lsvt-olivier** [comment]
> you can try promptlayer!

That was a rather unhelpful response and not bringing any value at all. There are tons of reasons why OP may not want/need to add another service into the fold.

**Comment by lsvt-olivier** [comment]
> Is there any way to retrieve the "standalone question" generated during the summarization process of the `ConversationalRetrievalChain`? I was able to print it for debugging [here in base.py](https://github.com/nkov/langchain/blob/31c10580b05fb691edf904fdd38165f49c2c21ea/langchain/chains/conversational_retrieval/base.py#L81) but it would be nice to access it in a more structured way

Would you mind to share how you were able to get the info? Thanks!
