### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by musakhawaja** [langchain-ai/langchain#21269]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_community.graphs import Neo4jGraph
url = "neo4j+s://..."
username ="neo4j"
password = ""
graph = Neo4jGraph(
    url=url,
    username=username,
    password=password
)
```

### Error Message and Stack Trace (if applicable)

Exception ignored in: <function Driver.__del__ at 0x7dee71153b00>
Traceback (most recent call last):
  File "/home/musa/anaconda3/lib/python3.11/site-packages/neo4j/_sync/driver.py", line 525, in __del__
  File "/home/musa/anaconda3/lib/python3.11/site-packages/neo4j/_sync/driver.py", line 609, in close
TypeError: catching classes that do not inherit from BaseException is not allowed

### Description

I am trying to connect to my neo4j aura database but can't seem to get it to work. Any help will be appreciated

### System Info

langchain==0.1.17
langchain-community==0.0.36
langchain-core==0.1.50
langchain-experimental==0.0.57
langchain-openai==0.1.6
langchain-pinecone==0.0.3
langchain-text-splitters==0.0.1
langchainhub==0.1.15

OS: Ubuntu

**Comment by sgautam666** [comment]
I am experiencing the same issue. I am running a simple vector retriever with langchain. 
In the jupyter notebook it runs fine. When I execute with a script, it's throwing this error.

**Comment by JayLiu7319** [comment]
> I am experiencing the same issue. I am running a simple vector retriever with langchain. In the jupyter notebook it runs fine. When I execute with a script, it's throwing this error.

same.

**Comment by musakhawaja** [comment]
Managed to fix this. It was caused due to a dependency clash. Create a fresh conda environment and install the requirements needed

**Comment by pigeongcc** [comment]
@musakhawaja hi! could you share your requirements.txt? thanks

**Comment by mikeallen39** [comment]
> I am experiencing the same issue. I am running a simple vector retriever with langchain. In the jupyter notebook it runs fine. When I execute with a script, it's throwing this error.

I am experiencing this too

**Comment by mikeallen39** [comment]
> Managed to fix this. It was caused due to a dependency clash. Create a fresh conda environment and install the requirements needed

I installed a new virtual environment but it didn't solve the problem
