### ISSUE TITLE
Ollama does not work with ChatModel ollama version 0.1.32 and Langchain 

### ISSUE THREAD

**Issue by rajpdus** [langchain-ai/langchain#21293]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
# LangChain supports many other chat models. Here, we're using Ollama
from langchain_community.chat_models import ChatOllama
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

# supports many more optional parameters. Hover on your `ChatOllama(...)`
# class to view the latest available supported parameters
llm = ChatOllama(model="llama3")
prompt = ChatPromptTemplate.from_template("Tell me a short joke about {topic}")

# using LangChain Expressive Language chain syntax
# learn more about the LCEL on
# /docs/expression_language/why
chain = prompt | llm | StrOutputParser()

# for brevity, response is printed in terminal
# You can use LangServe to deploy your application for
# production
print(chain.invoke({"topic": "Space travel"}))
```

### Description

Unable to get response from Ollama server locally when using ChatOllama. 

### System Info

platform - mac

langchain==0.1.16
langchain-anthropic==0.1.8
langchain-community==0.0.32
langchain-core==0.1.42
langchain-groq==0.1.2
langchain-openai==0.1.3
langchain-text-splitters==0.0.1
langchainhub==0.1.15
langgraph==0.0.37
langsmith==0.1.40

python - 3.10

**Comment by mao3267** [comment]
Are there any error messages in your terminal?

**Comment by umairgillani93** [comment]
**Working totally fine for me with below configurations and version. Try with the following versions of langchain-core and langchain-community: Heres' the output.** 

> (langchain) umairgillani@fcp contrib$ python test.py 
> Why did the astronaut break up with his girlfriend before going to Mars?
> 
> Because he needed space!


> (langchain) umairgillani@fcp contrib$ pip show langchain
> Name: langchain
> Version: 0.1.16
> Summary: Building applications with LLMs through composability
> Home-page: https://github.com/langchain-ai/langchain
> Author: 
> Author-email: 
> License: MIT
> Location: /home/umairgillani/anaconda3/envs/langchain/lib/python3.12/site-packages
> Requires: aiohttp, dataclasses-json, jsonpatch, langchain-community, langchain-core, langchain-text-splitters, langsmith, > numpy, pydantic, PyYAML, requests, SQLAlchemy, tenacity
> Required-by: langchain-experimental
> 
> 
> (langchain) umairgillani@fcp contrib$ python --version
> Python 3.12.3
> 
> (langchain) umairgillani@fcp contrib$ pip list | grep 'langchain*'
> langchain                0.1.16
> langchain-community      0.0.34
> langchain-core           0.1.46
> langchain-experimental   0.0.57
> langchain-text-splitters 0.0.1
> langchainhub             0.1.15
