### ISSUE TITLE
Discrepancy in API Key Parameter Name in ValidationError Message

### ISSUE THREAD

**Issue by VirajDeshwal** [langchain-ai/langchain#21312]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Summary:
I've noticed an inconsistency in the parameter name for the API key in the OpenAI Embeddings library. 

The error message indicates a different parameter name than what the library code expects.

Detailed Explanation:
Upon failing to initialize OpenAI Embeddings due to a missing API key, the following error is generated:

`ValidationError: 1 validation error for OpenAIEmbeddings
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
`

This error message requests openai_api_key either as an environment variable or a direct parameter. 

However, the library seems to require the API key under the parameter name api_key. 

This mismatch could lead to configuration errors and confusion among users.

Steps to Reproduce:

Attempt to initialize the OpenAI Embeddings without setting the API key.
Note the error message requesting openai_api_key.

Expected Behavior:
The error message should reflect the correct parameter name (api_key) as expected by the library.

Suggested Solution:
To enhance clarity and prevent confusion, I recommend either:

- Adjusting the error message to correctly ask for api_key.
- Modifying the code to accept openai_api_key as indicated by the error message.
Environment:

OpenAI version: 1.12.0
Python version: 3.10

Thank you for your attention to this matter and for your continued support in improving the library.

Best regards,
https://github.com/VirajDeshwal

**Comment by qingdengyue** [comment]
#20160
