### ISSUE TITLE
GitLoader Not working

### ISSUE THREAD

**Issue by PrashantDixit0** [langchain-ai/langchain#21331]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.document_loaders import GitLoader

docs = GitLoader(
        clone_url=query_path,
        repo_path=temp_repo_dir,
        file_filter=lambda file_path: file_path.endswith(".py")
        or file_path.endswith(".md")
        or file_path.endswith(".js"),
    )
    docs = docs.load()

### Error Message and Stack Trace (if applicable)

GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://github.com/antar-ai/yolo-examples.git ./example_data/test_repo1/ stderr: 'Cloning into './example_data/test_repo1'... POST git-upload-pack (175 bytes) POST git-upload-pack (217 bytes) error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8) error: 3507 bytes of body are still expected fetch-pack: unexpected disconnect while reading sideband packet fatal: early EOF fatal: fetch-pack: invalid index-pack output '

### Description

I am using GitLoader, to load all the files which are of Python, JS and Markdown but not able to load because of package

### System Info

langchain==0.1.2
langchain-community==0.0.14
langchain-core==0.1.14

Platform-Linux
Python 3.11.4

**Comment by jonppe** [comment]
I decided to try your code and it works after adding argument branch="master" for GitLoader().
Perhaps you could double check that it wasn't just a network issue, full disk or something similar.

Just in case you still think its a but, here's the versions I used
Python 3.10.12

gitdb                     4.0.11
GitPython                 3.1.43
langchain                 0.1.20
langchain-community       0.0.38
langchain-core            0.1.52
langchain-text-splitters  0.0.1
langsmith                 0.1.57

**Comment by PrashantDixit0** [comment]
@jonppe Thank you, I have solved this issue. Its just that by default it takes `main` branch if not present manually we have to specify branch
