### ISSUE TITLE
llms

### ISSUE THREAD

**Issue by tkone2018** [langchain-ai/langchain#2138]
hello,can you share the ways how to use other llm not the openAI,thanks

**Comment by Tanmay3132** [comment]
hello @tkone2018 , 
to change the modal you need to specify  the model name ,
Their might be different model like OpenAI, HuggingFaceModel, etc
to specify the model you can provide the llm with 
llm = OpenAI(model_name="text-ada-001", n=2, best_of=2)
here OpenAi text-ada-001 model is used for large language model , you can change the model here 

Hope This may Help you , Thank you

**Comment by tkone2018** [comment]
@Tanmay3132 ok,thank you, i also can use my local model to replace openai?

**Comment by tkone2018** [comment]
@Tanmay3132 example, the  A  model is a llm i trained in my local, how i can use A model to replace openai?

**Comment by Tanmay3132** [comment]
Can you elaborate more ?
