### ISSUE TITLE
Unnecessary need to pass vectordbkwargs multiple times in new retrieval class?

### ISSUE THREAD

**Issue by phiweger** [langchain-ai/langchain#2139]
My aim is to chat with a vector index, so I tried to port code to the new retrieval abstraction. In addition, I pass arguments to the pinecone vector store eg to filter by metadata or specify the collection/ namespace needed. However, I only get the chain to work if I specify `vectordbkwargs` twice, once in the retriever definition and once for the actual model call. Is this intended behaviour?

```python
vectorstore = Pinecone(
    index=index,
    embedding_function=embed.embed_query,
    text_key=text_field,
    namespace=None  # not setting a namespace, for testing
)

# have to set vectordbkwargs here
vectordbkwargs = {"namespace": 'foobar', "filter": {}, "include_metadata": True}
retriever = vectorstore.as_retriever(search_kwargs=vectordbkwargs)

chat = ConversationalRetrievalChain(
    retriever=retriever,
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
)

chat_history = []
query = 'some query I know is answerable from the vector store'

# oddly, I have to pass vectordbkwargs here too
result = chat({"question": query, "chat_history": chat_history, 'vectordbkwargs': vectordbkwargs})
```

Leaving out either of the two vectordbkwargs passings to the respective function does not pass the "foobar" vector store namespace for pinecone and results in an empty result. My guess is that this might be a bug due to the newness of the retrieval abstraction? If not, how is one supposed to pass vector store-specific arguments to the chain?

**Comment by astro313** [comment]
I encountered a similar issue, another way to call this appears to be 
https://github.com/hwchase17/langchain/issues/2038
