### ISSUE TITLE
Model's maximum context length error with ChatGPT plugins

### ISSUE THREAD

**Issue by Anil-matcha** [langchain-ai/langchain#2140]
I am testing out the newly released support for ChatGPT plugins with langchain. Below I am doing a sample test with Wolfram Alpha but it throws the below error 

"openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 127344 tokens. Please reduce the length of the messages." 

What is the best way to deal with this ? Attaching below the code I executed

`import os
from langchain.chat_models import ChatOpenAI
from langchain.agents import load_tools, initialize_agent
from langchain.tools import AIPluginTool
tool = AIPluginTool.from_plugin_url("https://www.wolframalpha.com/.well-known/ai-plugin.json")
llm = ChatOpenAI(temperature=0,)
tools = load_tools(["requests"] )
tools += [tool]

agent_chain = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
agent_chain.run("How many calories are in Chickpea Salad?")`

**Comment by mofahad** [comment]
The message you are pushing into the OPenai model has len more then it context length (4097) tokens , chunks your request into small length lesser then 4096 tokens

**Comment by Anil-matcha** [comment]
@sergerdn The error is caused as the plugin response is larger than context window of GPT-3. GPT-4 can probably overcome it but that would be just a workaround. Looking for a better solution which can work with GPT-3 too
