### ISSUE TITLE
DOC: The tool calling agent doesn't work on retrievers: create_tool_calling_agent

### ISSUE THREAD

**Issue by ramaiyaKushal** [langchain-ai/langchain#21411]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Cannot run the agent_executor.invoke function , it works for other tools but not retrievers: https://python.langchain.com/docs/modules/agents/quick_start/

Keep getting this error in last line of error code :  
`BadRequestError: Error code: 400 - {'error': {'message': "Invalid 'tools[0].function.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.", 'type': 'invalid_request_error', 'param': 'tools[0].function.name', 'code': 'invalid_value'}}`

**Comment by usamabjw** [comment]
We need to add retriever through a function where we include when to use this retriever tool.
retriever_tool = create_retriever_tool(
    retriever,
    "langsmith_search",
    "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!",
)

**Comment by leo-gan** [comment]
@ramaiyaKushal  It seems the issue is discussed and the proposed solutions work. Please, reopen if there is still a problem

**Comment by ramaiyaKushal** [comment]
Hi, I am using the following code blocks
`
from langchain_community.document_loaders import TextLoader
loader = TextLoader("data.txt")
documents = loader.load()

`
Then
`
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(documents)
embeddings = OpenAIEmbeddings()
db = FAISS.from_documents(texts, embeddings)
retriever = db.as_retriever()
`
Followed by creating a tool 

`
from langchain.tools.retriever import create_retriever_tool

tool = create_retriever_tool(
    retriever,
    "search Data",
    "Searches and returns excerpts from the Data information.",
)
tools = [tool]
`
Creating Prompts 
`
from langchain import hub
prompt = hub.pull("hwchase17/openai-tools-agent")
`
Setting ChatOpenAI and Agent
`
from langchain_openai import ChatOpenAI
llm = ChatOpenAI(temperature=0)

from langchain.agents import AgentExecutor, create_openai_tools_agent
agent = create_openai_tools_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools)
`
When I run this invoke function it gives me an error:
`
result = agent_executor.invoke({"input": "hi, im bob"})
`

**Comment by ramaiyaKushal** [comment]
Hi, I understood my mistake, the search DATA that I was calling the name of the function should have been Search_data or something along those lines without any spaces!
Thanks a lot!
@kannansingaravelu @usamabjw

**Comment by DekkaSridhar** [comment]
> [@ramaiyaKushal](https://github.com/ramaiyaKushal) The error message you're encountering suggests that there's an issue with the value of 'tools[0].function.name'. The value you're providing doesn't match the expected pattern. The tool name should only contain alphanumeric characters, hyphens, and underscores and should be without spaces.

Thanks a lot!! i was getting this error again and again, then i was you answer then i got to know that in the tool name i was passing "DuckDuckGo websearch" instead of "DuckDuckGo_websearch", such a silly mistake😅
