### ISSUE TITLE
DOC: import create_sql_query_chain is incorrectly imported in SQL + CSV document 

### ISSUE THREAD

**Issue by sam1231ui** [langchain-ai/langchain#21421]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://python.langchain.com/docs/use_cases/sql/quickstart/

this is link to the document with incorrect import statement for create_sql_query_chain
In chain section of above document the correct import statement should be `from langchain.chains.sql_database.query import create_sql_query_chain`
but is incorrect in document, provided the ss of same the 1st statement of code area
![Screenshot from 2024-05-08 17-13-05](https://github.com/langchain-ai/langchain/assets/64959366/abc6a5ba-8406-409c-9d7d-2c7f84a5e2e6)

**Comment by leo-gan** [comment]
@sam1231ui  Actually, this link is OK. It works fine.
It works because the namespace is flattened in the `langchain/chains/__init__.py` file, line 82.
You can use the `langchain.chains` namespace for this symbol.
