### ISSUE TITLE
Docs UI

### ISSUE THREAD

**Issue by desh-woes** [langchain-ai/langchain#2143]
The contrast used for the documentation on this UI (https://python.langchain.com/en/latest/getting_started/getting_started.html), makes the docs hard to read. Can this be improved? I can take a stab if pointed towards the UI code.

**Comment by desh-woes** [comment]
<img width="785" alt="Screenshot 2023-03-29 at 12 42 37 PM" src="https://user-images.githubusercontent.com/32124172/228525111-29eb30b5-c497-43a0-ad45-075c11a18254.png">

**Comment by desh-woes** [comment]
> <img alt="Screenshot 2023-03-29 at 12 42 37 PM" width="785" src="https://user-images.githubusercontent.com/32124172/228525111-29eb30b5-c497-43a0-ad45-075c11a18254.png">

Pretty unreadable

**Comment by Azeirah** [comment]
<img width="1387" alt="Screenshot 2023-03-29 at 14 04 50" src="https://user-images.githubusercontent.com/4040870/228529920-0e0d8428-15c8-4984-a030-a21c83b52d00.png">

It looks perfectly readable for me. What browser do you have, what OS are you running, and you have any css or light/dark theme plugins for your browser?

**Comment by desh-woes** [comment]
> <img alt="Screenshot 2023-03-29 at 14 04 50" width="1387" src="https://user-images.githubusercontent.com/4040870/228529920-0e0d8428-15c8-4984-a030-a21c83b52d00.png">
> 
> It looks perfectly readable for me. What browser do you have, what OS are you running, and you have any css or light/dark theme plugins for your browser?

Ah the issue seems to only occur in dark mode. I did not think to try out light mode. Nice catch. 

Would be nice to still fix the issue occurring in dark mode.

**Comment by Azeirah** [comment]
My dark mode is also perfectly ok

![afbeelding](https://user-images.githubusercontent.com/4040870/228536721-0bc6add2-7b56-438c-b134-732e52498358.png)

Again, what browser, os and potential plugins altering any css do you have?

**Comment by desh-woes** [comment]
Browser: Chrome
os: Mac os
Potential Plugins: Chrome dark theme

<img width="1792" alt="Screenshot 2023-03-29 at 1 57 00 PM" src="https://user-images.githubusercontent.com/32124172/228542452-7704aef1-8de8-44c9-a925-ddf59ff441d1.png">

Can you confirm this specific section works for you?

**Comment by Azeirah** [comment]
Ahh, yeah those sections do have terrible contrast.

![afbeelding](https://user-images.githubusercontent.com/4040870/228542936-049abf17-354d-4be7-85a5-5e6abad06181.png)

**Comment by Azeirah** [comment]
I assume this problem would be fixed if the sphinx-book-theme would be updated to version 1.0.0, langchain is still on version 0.3.4 which is from july last year. v1.0.0 is from the 1st of march this year.
