### ISSUE TITLE
bug(sql_agent): Optimise token usage for user questions which require information from more than one table

### ISSUE THREAD

**Issue by ajndkr** [langchain-ai/langchain#2150]
## Bug description

Hello! I've been using the SQL agent for some time now and I've noticed that it burns tokens unnecessarily in certain cases, leading to slower LLM responses and hitting token limits. This happens usually when the user's question requires information from more than one table.

Unlike `SQLDatabaseChain`, the SQL agent uses multiple tools to list tables, describe tables, generate queries, and validate generated queries. However, except for the generate query tool, all other tools are relevant only until the agent is required to generate a query. As mentioned in the scenario above, if the agent needs to fetch information from two tables, it first makes an LLM call to list the tables, selects the most appropriate table, and generates a query based on the selected table description to fetch information. Then, the agent generates a second SQL query to fetch information from a different table and goes through the exact same process.

The problem is that all the context from the first SQL query is retained, leading to unnecessary token burn and slower LLM responses.

## Proposed solution

To resolve this issue, we should update the SQL agent to update the context once the information is fetched from the first query generation. Only the output from the first query should be taken forward for the next query generation. This will prevent the agent from running into token limits and speed up the LLM response time.

**Comment by br3nr** [comment]
@ajndkr Did you happen to find any ways of working around this? I am also using the sequel agent, and pretty much all reasonable calls are hitting the token limit.
