### ISSUE TITLE
New Document loader request for Sharepoint , OneDrive and Documentum

### ISSUE THREAD

**Issue by amitmukh** [langchain-ai/langchain#2153]
Many customers has their knowledge base sitting on either in SharePoint , OneDrive and Documentum. Can we have a new document loader for all these?

**Comment by tvigouroux** [comment]
Totally with you! A loader for SharePoint and OneDrive would be great!

**Comment by netoferraz** [comment]
I'll try to work on this one.

**Comment by ugoborghetti** [comment]
hey @netoferraz are by any chance working on sharepoint?

**Comment by laveshnk-crypto** [comment]
@netoferraz Any news on the SharePoint Loader?

**Comment by netoferraz** [comment]
Hi @laveshnk-crypto and @ugoborghetti I'll try to work on this in the following week.

**Comment by laveshnk-crypto** [comment]
Thank you @netoferraz ! That would be fantastic

**Comment by laveshnk-crypto** [comment]
Hi @netoferraz , is there any update on this?

**Comment by netoferraz** [comment]
We're waiting for a review [here](https://github.com/hwchase17/langchain/pull/4284).

**Comment by HoiDam** [comment]
Cool!

**Comment by laveshnk-crypto** [comment]
Hi @netoferraz , thanks a lot for your contribution to the LangChain package! its extremely invaluable for developers such as me.

Temporarily, till your SharePoint Loader gets approved, I have gone ahead and cloned your version of langchain and im using that in my project instead. However, I had a few hiccups while following the documentation.

My sharepoint site doesnt have subsites, hence I am not able to retrieve the subsite ID as specified in the docs. What do I do in this case? My document library is located in the main site itself

**Comment by joybrotodey-clousufi** [comment]
Hi Folks, So as of today are we having any Git Repo which has used langchain document loader from SharePoint.

**Comment by hsravidatta** [comment]
Thanks how do we get Sharepoint Loader working with Client Context and Site Tenant specific URL. the current sharepoint loader developed in LC does not allow for O365 authentication it is giving below error error_description=Application is not configured as a multi-tenant application.  Please help

**Comment by Jasper-Rowan** [comment]
@hsravidatta did you ever solve this? I am getting the same error when following the steps [here](https://python.langchain.com/docs/integrations/document_loaders/microsoft_sharepoint), in the langchain docs. Thank you!

**Comment by ericvaillancourt** [comment]
I know that I'm late but here is an article that I wrote on the subject: https://medium.com/@eric_vaillancourt/filling-the-gap-developing-a-custom-solution-for-sharepoint-integration-with-langchain-d961f7a06c96
