### ISSUE TITLE
DOC: OracleDB 23ai demo link brokern 

### ISSUE THREAD

**Issue by barjinders** [langchain-ai/langchain#21563]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Oracle AI Vector Search End-to-End Demo Guide is broken and throws 404. 
(https://github.com/langchain-ai/langchain/tree/master/cookbook/oracleai_demo.md)

**Comment by keenborder786** [comment]
okay I am fixing it.

**Comment by keenborder786** [comment]
This has been fixed....

**Comment by barjinders** [comment]
When is this getting pushed? I still the link is broken
