### ISSUE TITLE
DOC: Oracle AI Vector Search DB Connection Error 

### ISSUE THREAD

**Issue by barjinders** [langchain-ai/langchain#21587]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The instructions given at https://python.langchain.com/v0.1/docs/integrations/document_loaders/oracleai/
Section: Connect to Oracle Database
conn = oracledb.connect(user=username, password=password, dsn=dsn)
**doesn't work with DBCS 23ai.** The default installation is deployed with Native Network Encryption (NNE) enabled. NNE is only supported in python-oracledb Thick mode.
For this to work the instructions need to be updated to use the thick mode, with a link to download the thick mode driver.
oracledb.init_oracle_client(lib_dir="/<PATH>/instantclient_19_16")

**Comment by luigisaetta** [comment]
@barjinders one quick solution, good for a test environment, is to disable NNE. Go to $ORACLE_HOME/network/admin and in sqlnet.ora remove all the lines related to encryption. Then restart the DB node. This way DB won't require Native Encryption. It is ok in a test environment, I would say.

**Comment by barjinders** [comment]
I understand we can do some workarounds to disable NNE and force TCPS but are we expecting all the users to do that? If yes, we should have this process documented before they start connecting. If not, we need to list the supported process i.e. use a thick client. The document in its current form doesn't help users connect to the DB.
