### ISSUE TITLE
'RunnableSequence' object has no attribute 'input_keys'

### ISSUE THREAD

**Issue by chenjiehao** [langchain-ai/langchain#21597]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    summarizing_prompt_template=PromptTemplate(input_variables=["content"], template="Summarize the following content into a sentence less than 20 words: --- {content}")
    summarchain = summarizing_prompt_template| llm | {"summary": StrOutputParser()}

    translating_prompt_template = PromptTemplate(input_variables=["summary"],
    template="""translate "{summary}" into Chinese:""")
    transchain = translating_prompt_template | llm | {"translated": StrOutputParser()}
 
    sequential_chain = SequentialChain(chains=[summarchain, transchain], input_variables=["content"],
    output_variables=[ "summary","translated"])

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/chenjiehao/PycharmProjects/test/main.py", line 52, in <module>
    sequential_chain = SequentialChain(chains=[summarchain, transchain], input_variables=["content"],
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/pydantic/v1/main.py", line 1050, in validate_model
    input_data = validator(cls_, input_data)
  File "/opt/anaconda3/envs/test/lib/python3.10/site-packages/langchain/chains/sequential.py", line 64, in validate_chains
    missing_vars = set(chain.input_keys).difference(known_variables)
AttributeError: 'RunnableSequence' object has no attribute 'input_keys'

### Description

  for chain in chains:
            missing_vars = set(chain.input_keys).difference(known_variables)
            if chain.memory:
                missing_vars = missing_vars.difference(chain.memory.memory_variables)

            if missing_vars:
                raise ValueError(
                    f"Missing required input keys: {missing_vars}, "
                    f"only had {known_variables}"
                )
            overlapping_keys = known_variables.intersection(chain.output_keys)
            if overlapping_keys:
                raise ValueError(
                    f"Chain returned keys that already exist: {overlapping_keys}"
                )

            known_variables |= set(chain.output_keys)
==========================================================================
There really is no input_keys in this chain,The langchain version is 0.1.20.

### System Info

langchain @ file:///home/conda/feedstock_root/build_artifacts/langchain_1715394120542/work
langchain-community @ file:///home/conda/feedstock_root/build_artifacts/langchain-community_1715223770788/work
langchain-core @ file:///home/conda/feedstock_root/build_artifacts/langchain-core_1715060411785/work
langchain-openai==0.1.6
langchain-text-splitters @ file:///home/conda/feedstock_root/build_artifacts/langchain-text-splitters_1709389732771/work

platform is mac

python version is  3.10.13

**Comment by keenborder786** [comment]
Sequential Chain is the old Langchain Style of combining Chains. You might want to combine chains using the following LCEL syntax:

```python
combined_chain = summarchain | transchain
```

And then call the chain as follow:

```python
combined_chain.invoke({'content':'Hello How are you doing?'})
```

**Comment by chenjiehao** [comment]
Thanks！I have another question, how do I get the output of summaarchain?

**Comment by eyurtsev** [comment]
@chenjiehao usage questions should be asked in discussions rather than issues!

**Comment by axsaenz** [comment]
@chenjiehao  do you know how to access to the output of summaarchain?
