### ISSUE TITLE
Error while importing RedisChatMessageHistory 

### ISSUE THREAD

**Issue by areeb1501** [langchain-ai/langchain#2163]
I am facing this issue when trying to import the following.

    from langchain.agents import ZeroShotAgent, Tool, AgentExecutor
    
    from langchain.memory import ConversationBufferMemory
    
    from langchain.memory.chat_memory import ChatMessageHistory
    
    from langchain.memory.chat_message_histories import RedisChatMessageHistory
    
    from langchain import OpenAI, LLMChain
    
    from langchain.utilities import GoogleSearchAPIWrapper
    
   

 Here's the error message:

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    [<ipython-input-55-e9f2f4d46ecb>](https://localhost:8080/#) in <cell line: 4>()
          2 from langchain.memory import ConversationBufferMemory
          3 from langchain.memory.chat_memory import ChatMessageHistory
    ----> 4 from langchain.memory.chat_message_histories import RedisChatMessageHistory
          5 from langchain import OpenAI, LLMChain
          6 from langchain.utilities import GoogleSearchAPIWrapper
    
    1 frames
    [/usr/local/lib/python3.9/dist-packages/langchain/memory/chat_message_histories/dynamodb.py](https://localhost:8080/#) in <module>
          2 from typing import List
          3 
    ----> 4 from langchain.schema import (
          5     AIMessage,
          6     BaseChatMessageHistory,
    
    ImportError: cannot import name 'BaseChatMessageHistory' from 'langchain.schema' (/usr/local/lib/python3.9/dist-packages/langchain/schema.py)
    
    ---------------------------------------------------------------------------
    NOTE: If your import is failing due to a missing package, you can
    manually install dependencies using either !pip or !apt.
    
    To view examples of installing some common dependencies, click the
    "Open Examples" button below.
    ---------------------------------------------------------------------------

Currently running this on google colab. Is there anything I am missing? How can this be rectified?

**Comment by mofahad** [comment]
Hi @areeb1501  which python version , langchain version are you using. I am successfully able  to do imports on collab
![Screenshot (104)](https://user-images.githubusercontent.com/19353524/228697555-d4369479-4118-4288-b741-e4fa872f2ec1.png)
