### ISSUE TITLE
[BUG] FAISS.from_embeddings doesn't seem to exist

### ISSUE THREAD

**Issue by fhooton** [langchain-ai/langchain#2165]
I am trying to use the FAISS class to initialize an index using pre-computed embeddings, but it seems that the method is not being recognized. However, I found the function in both the [source code](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/faiss.py#L348) and documentation. Details in screenshot below:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/20560167/228670417-c468ce42-29dc-4d07-a494-d942ec96232a.png">

**Comment by mofahad** [comment]
which langchain version are you using. Same code is running in my case.
