### ISSUE TITLE
Streaming with RunnableWithMessageHistory fails to work

### ISSUE THREAD

**Issue by BrianMwas** [langchain-ai/langchain#21664]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am using the following code to get a response asynchronously and it works fine
```
conversational_rag_chain = RunnableWithMessageHistory(
                rag_chain,
                get_session_history=self.get_message_history,
                input_messages_key="input",
                history_messages_key="chat_history",
                output_messages_key="answer",
            )
            self.message_history.add_user_message(search)
           
            answer = conversational_rag_chain.invoke({
                "input": search
            }, 
                config={
                    "configurable": {
                        "session_id": self.session_id
                    }
                }
            )["answer"]```

But when I change the invoke to stream as I did before, I don't get an input at all

```
answer = conversational_rag_chain.stream({
                "input": search
            }, 
                config={
                    "configurable": {
                        "session_id": self.session_id
                    }
                }
            )["answer"]```
            
            
            

### Error Message and Stack Trace (if applicable)

Am not getting an exception but a weird response, 
Am getting a response and its only giving the input data only
{
 "input": {the_question_I_asked}
}

This is exactly what I get in the response, followed the documentation and got nothing no different

### Description

I am trying to get the responses to be streamed back to me as they come from OpenAI, with that I will get lower latency and a much better feel compared to waiting for the entire data to be generated, am also working on voice which requires the data to come as a stream

### System Info

Package Information
-------------------
> langchain_core: 0.1.46
> langchain: 0.1.16
> langchain_community: 0.0.34
> langsmith: 0.1.52
> langchain_chroma: 0.1.0
> langchain_openai: 0.1.4
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15
> langgraph: 0.0.39

**Comment by ging-dev** [comment]
> ### Checked other resources
> * [x]  I added a very descriptive title to this issue.
> * [x]  I searched the LangChain documentation with the integrated search.
> * [x]  I used the GitHub search to find a similar question and didn't find it.
> * [x]  I am sure that this is a bug in LangChain rather than my code.
> * [x]  The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
> 
> ### Example Code
> I am using the following code to get a response asynchronously and it works fine
> 
> ```
> conversational_rag_chain = RunnableWithMessageHistory(
>                 rag_chain,
>                 get_session_history=self.get_message_history,
>                 input_messages_key="input",
>                 history_messages_key="chat_history",
>                 output_messages_key="answer",
>             )
>             self.message_history.add_user_message(search)
>            
>             answer = conversational_rag_chain.invoke({
>                 "input": search
>             }, 
>                 config={
>                     "configurable": {
>                         "session_id": self.session_id
>                     }
>                 }
>             )["answer"]```
> 
> But when I change the invoke to stream as I did before, I don't get an input at all
> ```
> 
> answer = conversational_rag_chain.stream({ "input": search }, config={ "configurable": { "session_id": self.session_id } } )["answer"]```
> 
> ### Error Message and Stack Trace (if applicable)
> Am not getting an exception but a weird response, Am getting a response and its only giving the input data only { "input": {the_question_I_asked} }
> 
> This is exactly what I get in the response, followed the documentation and got nothing no different
> 
> ### Description
> I am trying to get the responses to be streamed back to me as they come from OpenAI, with that I will get lower latency and a much better feel compared to waiting for the entire data to be generated, am also working on voice which requires the data to come as a stream
> 
> ### System Info
> ## Package Information
> > langchain_core: 0.1.46
> > langchain: 0.1.16
> > langchain_community: 0.0.34
> > langsmith: 0.1.52
> > langchain_chroma: 0.1.0
> > langchain_openai: 0.1.4
> > langchain_text_splitters: 0.0.1
> > langchainhub: 0.1.15
> > langgraph: 0.0.39

You must check key 'answer' exist in chunk first: https://python.langchain.com/v0.1/docs/use_cases/question_answering/streaming/#streaming-final-outputs
