### ISSUE TITLE
DOC: Open in Colab option not working for certain document pages

### ISSUE THREAD

**Issue by theAnshulGupta** [langchain-ai/langchain#21690]
### Checklist

- [x] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I'm having an issue opening the Colab notebooks for certain pages. Clicking the button gives me an error "Notebook not found" – I linked a few pages below. Not sure if this has to do with my personal settings or something else.

[Web Scraping Page](https://python.langchain.com/v0.1/docs/use_cases/web_scraping/)
[Code Understanding Page](https://python.langchain.com/v0.1/docs/use_cases/code_understanding/)

**Comment by keenborder786** [comment]
I have created a PR for fixing this in v0.1 branch.
