### ISSUE TITLE
DOC: SurrealDB docs use `await` in code examples. Copy and pasting code does not work.

### ISSUE THREAD

**Issue by JohannesDienst-askui** [langchain-ai/langchain#21708]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Page: https://python.langchain.com/v0.1/docs/integrations/vectorstores/surrealdb/

Source: https://github.com/langchain-ai/langchain/blob/f2f970f93de9a51bccc804dd7745f6b97f6cb419/docs/docs/integrations/vectorstores/surrealdb.ipynb#L168

### Idea or request for content:

As an inexperienced Python developer, I do not know how to make the code work without researching Python's co-routines and the `async/await` pattern.

The code in the docs shows me the following error which does not explain how to go about it the correct way:
`"await" allowed only within async function`

**Comment by eyurtsev** [comment]
Thanks! You can run it within the jupyter notebook which is async by default.

I'll close this issue for now since it's not specific to surrealdb -- we probably need sync versions present in more places in the docs or a bit of an explanation about sync / async.
