### ISSUE TITLE
AZURE_OPENAI_ENDPOINT env var conflicts with OPENAI_API_BASE, while OPENAI_API_BASE is being used in MLFlow to point to Azure OpenAI endpoint.

### ISSUE THREAD

**Issue by loomlike** [langchain-ai/langchain#21726]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Environment variables:
```
# for langchain
OPENAI_API_VERSION='...'
AZURE_OPENAI_API_KEY='my-key'
AZURE_OPENAI_ENDPOINT='my-azure-openai-endpoint'

# for mlflow -- this conflicts
OPENAI_API_BASE='my-azure-openai-endpoint'
```
Code to cause the error:
```
from langchain_openai import AzureOpenAIEmbeddings, AzureChatOpenAI

model = AzureChatOpenAI(
    azure_deployment="my-deployment-name",
)

# or 
model = AzureOpenAIEmbeddings(
    azure_deployment="my-deployment-name",
)
```

### Error Message and Stack Trace (if applicable)

```
ValidationError: 1 validation error for AzureChatOpenAI
__root__
  As of openai>=1.0.0, Azure endpoints should be specified via the `azure_endpoint` param not `openai_api_base` (or alias `base_url`). (type=value_error)
```

### Description

`AzureOpenAIEmbeddings` and `AzureChatOpenAI` automatically pick up the env vars and throwing errors complaining about having both `azure_endpoint` param and `openai_api_base`. 

`OPENAI_API_BASE` env var is being used in other packages, like MLFlow.

### System Info

```
#pip freeze | grep 'langchain\|mlflow'
langchain==0.1.20
langchain-community==0.0.38
langchain-core==0.1.52
langchain-openai==0.1.6
langchain-text-splitters==0.0.1
mlflow==2.12.2
```

**Comment by chip-davis** [comment]
Have you tried specifying everything when you create the model? 
For example:
```
model = AzureChatOpenAI(
            openai_api_version="2023-05-15",
            azure_deployment=os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME"),
            temperature=0,
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
        )
```

Not sure if this would work but give it a try.

**Comment by Zuber139** [comment]
I have the exact same problem as OP, and no, that does not work.

```python
import os
from langchain_openai import AzureOpenAIEmbeddings

from dotenv import load_dotenv
from pathlib import Path

load_dotenv('azure.env')

embeddings = AzureOpenAIEmbeddings(
    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
    api_key=os.environ["AZURE_OPENAI_API_KEY"],
    azure_deployment=os.environ["AZURE_OPENAI_EMBEDDINGS"])

text = "Hello, world!"
query_result = embeddings.embed_query(text)             
print(query_result)
```

In azure.env, if I don't set OPEN_API_BASE at all, the code works. If I do (even with the same value as the AZURE_OPENAPI_ENDPOINT), I get the same exact error that OP sees. So no, adding the endpoint to the arguments does not fix this problem.

**Comment by chip-davis** [comment]
Just submitted a PR with a fix
