### ISSUE TITLE
get_bedrock_anthropic_callback does not return token values correctly

### ISSUE THREAD

**Issue by cis-hotta** [langchain-ai/langchain#21732]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
from langchain_aws import ChatBedrock
from langchain_community.callbacks.manager import get_bedrock_anthropic_callback

llm = ChatBedrock(model_id="anthropic.claude-3-haiku-20240307-v1:0")
# llm = ChatBedrock(model_id="anthropic.claude-v2")

with get_bedrock_anthropic_callback() as cb:
    result = llm.invoke("Tell me a joke")
    result2 = llm.invoke("Tell me a joke")
    print(cb)
```

### Error Message and Stack Trace (if applicable)

This is not an error, but rather the actual behavior.
As shown on the referenced page -> [Tracking token usage](https://python.langchain.com/v0.1/docs/modules/model_io/chat/token_usage_tracking/).
```
Tokens Used: 0
	Prompt Tokens: 0
	Completion Tokens: 0
Successful Requests: 2
Total Cost (USD): $0.0
```

### Description

Description:
I encountered an issue with the get_bedrock_anthropic_callback function in Langchain. According to the [documentation](https://python.langchain.com/v0.2/docs/how_to/chat_token_usage_tracking/#openai), the function should provide token usage details, but it returns all token values as 0.

Steps to Reproduce:

Use get_bedrock_anthropic_callback as described in the documentation.
Observe that token values are returned as 0.
Expected Behavior:
The function should return the correct token usage values.

Actual Behavior:
The function returns all token values as 0.

Considering the use of Claude 3 Opus, it would be beneficial to include Opus (anthropic.claude-3-opus-20240229-v1:0) in the model cost mapping. Here are the current values for reference:

langchain_community.callbacks.bedrock_anthropic_callback
``` python
MODEL_COST_PER_1K_INPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0008,
    "anthropic.claude-v2": 0.008,
    "anthropic.claude-v2:1": 0.008,
    "anthropic.claude-3-opus-20240229-v1:0": 0.015,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.003,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00025,
}

MODEL_COST_PER_1K_OUTPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0024,
    "anthropic.claude-v2": 0.024,
    "anthropic.claude-v2:1": 0.024,
    "anthropic.claude-3-opus-20240229-v1:0": 0.075,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.015,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00125,
}
```

### System Info

Langchain:
langchain==0.2.0rc2
langchain-anthropic==0.1.12
langchain-aws==0.1.3
langchain-chroma==0.1.0
langchain-community==0.2.0rc1
langchain-core==0.1.52
langchain-openai==0.1.6
langchain-text-splitters==0.0.1

OS:
windows10

Python:
3.10.4

**Comment by OSS-GR** [comment]
I am facing the same issue. All token and cost values are returned as 0. Only value that displays something is the successful requests line.

**Comment by cis-hotta** [comment]
Thank you for fixing the token counting logic! This is a great improvement.

I'd like to suggest an additional update that would make this even more useful. Specifically, updating the model cost mappings in `langchain_community.callbacks.bedrock_anthropic_callback` to include the latest Claude 3 models would allow for accurate token counting for Claude 3.0 Opus and Claude 3.5 Sonnet.

Here are the current values:

```python
MODEL_COST_PER_1K_INPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0008,
    "anthropic.claude-v2": 0.008,
    "anthropic.claude-v2:1": 0.008,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.003,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00025,
}

MODEL_COST_PER_1K_OUTPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0024,
    "anthropic.claude-v2": 0.024,
    "anthropic.claude-v2:1": 0.024,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.015,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00125,
}
```

And here are the proposed updated values:

```python
MODEL_COST_PER_1K_INPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0008,
    "anthropic.claude-v2": 0.008,
    "anthropic.claude-v2:1": 0.008,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.003,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00025,
    "anthropic.claude-3-opus-20240229-v1:0": 0.015,
    "anthropic.claude-3-5-sonnet-20240620-v1:0": 0.003,
}

MODEL_COST_PER_1K_OUTPUT_TOKENS = {
    "anthropic.claude-instant-v1": 0.0024,
    "anthropic.claude-v2": 0.024,
    "anthropic.claude-v2:1": 0.024,
    "anthropic.claude-3-sonnet-20240229-v1:0": 0.015,
    "anthropic.claude-3-haiku-20240307-v1:0": 0.00125,
    "anthropic.claude-3-opus-20240229-v1:0": 0.075,
    "anthropic.claude-3-5-sonnet-20240620-v1:0": 0.015,
}
```

This update would enable accurate token counting for Claude 3.0 Opus and Claude 3.5 Sonnet models. Would it be possible to incorporate these changes in a future update?
