### ISSUE TITLE
AttributeError: module 'fitz' has no attribute 'fitz'

### ISSUE THREAD

**Issue by alimgh** [langchain-ai/langchain#21750]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import ArxivLoader

docs = ArxivLoader(query="2403.10131").load()
```

### Error Message and Stack Trace (if applicable)

lib/python3.10/site-packages/langchain_community/utilities/arxiv.py:227, in ArxivAPIWrapper.lazy_load(self, query)
    225     with fitz.open(doc_file_name) as doc_file:
    226         text: str = "".join(page.get_text() for page in doc_file)
--> 227 except (FileNotFoundError, fitz.fitz.FileDataError) as f_ex:
    228     logger.debug(f_ex)
    229     continue

AttributeError: module 'fitz' has no attribute 'fitz'

### Description

You just simply need to change the `fitz.fitz.FileDataError` to `fitz.FileDataError`.

### System Info

langchain==0.1.20
langchain-community==0.0.38
langchain-core==0.1.52
langchain-text-splitters==0.0.1

platform linux

python 3.10.13

**Comment by utsumi-fj** [comment]
I have the same error. Is this fixed? Is there a workaround?

**Comment by utsumi-fj** [comment]
Sorry, this was my installation problem. The following commands resolved this.
```
pip uninstall fitz
pip install pymupdf
```
