### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/tools_prompting/> fix import in example code

### ISSUE THREAD

**Issue by maccam912** [langchain-ai/langchain#21814]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The first code block on https://python.langchain.com/v0.2/docs/how_to/tools_prompting/#creating-our-prompt has
`from langchain.tools.render import render_text_description`
this did not work for me, I got an error that I didn't have the module "langchain". I fixed it by changing that line to
`from langchain_core.tools import render_text_description`
instead.

### Idea or request for content:

Change `from langchain.tools.render import render_text_description` to `from langchain_core.tools import render_text_description` on https://python.langchain.com/v0.2/docs/how_to/tools_prompting/#creating-our-prompt

**Comment by maccam912** [comment]
https://github.com/langchain-ai/langchain/blob/master/docs/docs/how_to/tools_prompting.ipynb?short_path=f4ea763#L165

**Comment by baskaryan** [comment]
thank you for flagging and fixing @maccam912!
