### ISSUE TITLE
DOC: "set_llm_cache" API documentation page shows 404 on /v0.2/docs/how_to/chat_model_caching/

### ISSUE THREAD

**Issue by vimalgorasiya** [langchain-ai/langchain#21811]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://api.python.langchain.com/en/latest/globals/langchain.globals.set_llm_cache.html

API documentation for `set_llm_cache` is broken on above page.

![image](https://github.com/langchain-ai/langchain/assets/12136812/3efa69d6-0bf4-49fb-a7d5-a7b53830da92)

Thanks for improving documentation!

**Comment by baskargopinath** [comment]
in the latest version of the code i cant even find the link

**Comment by vimalgorasiya** [comment]
@baskargopinath 

Here is link:

https://python.langchain.com/v0.2/docs/how_to/chat_model_caching/

You can find following API function reference which redirects to 404

`API Reference:set_llm_cache`

Thanks.

**Comment by baskargopinath** [comment]
@vimalgorasiya thats a older vversion of the website are u able to find that link in the github codebase

**Comment by vimalgorasiya** [comment]
@baskargopinath 

Isn't version 0.2 the latest version of the doc?

If not then could you please send here latest link doc with above reference?

Thanks
