### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/chat/openai/>

### ISSUE THREAD

**Issue by Mathiyazhagan-A** [langchain-ai/langchain#21810]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

An error occurred: module 'langchain' has no attribute 'verbose'.
An error occurred: module 'langchain' has no attribute 'debug'.

How do I solve these attribute errors?

**Comment by eyurtsev** [comment]
Thanks for letting us know!

You can use set_verbose and set_debug: https://python.langchain.com/v0.2/docs/how_to/debugging/

Keeping issue open as we need to roll out an update to documentation
