### ISSUE TITLE
Is there any way to combine chatbot and question answering over docs?

### ISSUE THREAD

**Issue by derekhsu** [langchain-ai/langchain#2185]
Hi, I read the docs and examples then tried to make a chatbot and a qustion answering bot over docs. I wonder is there any way to combine there two function together?

From my point of view, I mean basically it's chatbot which uses memory module to carry on conversation with users. If the user asking a question, then the chatbot rertives docs based on embeddings and get the answer.

Then I change the prompt of the conversation and add the answer to it, asking the chatbot response based on the memory and the answer. Will it work? Or there is another conventient way or chain to combine there two types of bots?

**Comment by punitvara** [comment]
I am working to make this work. I will update in case if it works.

**Comment by punitvara** [comment]
No need to use memory @sergerdn ? We just need to use CONDENSE_PROMPT only ? I am trying above task with QA_with_source chain

**Comment by zakkl13** [comment]
I have been working on this as well. I have something which *technically* works but isn't very good right now. The agent gets kind of wacky, often retrieves good data but doesn't share it or summarizes it too much. In theory this approach should work and you should be able to add arbitrary tools (search etc.)

I don't have  a fully working code sample to share yet but essentially:
1. RetrievalQA chain on top of a vector DB is used as a Tool. Description "useful for when you need to answer questions about your_topic." Note: no memory is added to this chain.
2. A ZeroShotAgent with chat_history  in its prompt and memory added to it. This is created using the `AgentExecutor.from_agent_and_tools(`

Code (doesn't compile but gives an idea)
```
llm = OpenAI(temperature=0, model_name='gpt-3.5-turbo')
vectordb = <create your vectordb>
memory = ConversationBufferMemory(memory_key='chat_history')
chain = RetrievalQA.from_chain_type(llm=llm, retriever=vectordb.as_retriever())

tools = [
    Tool(
        name = "Topic QA System",
        func=chain.run,
        description="useful for when you need to answer questions about <Topic>. This could include questions about <specific things related to Topic>, and more. Input should be a fully formed question."
    )
  ]

prefix = """Have a conversation with a human, answering the following questions as best you can. You have access to the following tools:"""
suffix = """Begin!"

{chat_history}
Question: {input}
{agent_scratchpad}"""

prompt = ZeroShotAgent.create_prompt(
    tools, 
    prefix=prefix, 
    suffix=suffix, 
    input_variables=["input", "chat_history", "agent_scratchpad"]
)

llm_chain = LLMChain(llm=llm, prompt=prompt)
agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True)
agent_exe = AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=True, memory=memory)
```
So far I have found gpt3.5-turbo to be more effective than the default. 

Cheers and looking forward to other's contributing! This seems like a major use case.

**Comment by derekhsu** [comment]
https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html

Actually, I guess this is the answer that mix chat history and knowledge base. When did this come up?

**Comment by eddiesaltaccount** [comment]
Perhaps not the most valuable input to this conversation, but 

For non-agent, non-server approach. I think the simple solution is:

- have chatbot form a chat history memory for whatever topic the user is interested in
- when the time comes for utilizing the vector db to answer a precise question, extract the chat history memory and feed it into the qa retrieval in the form of a question + chat history context

That's how I'm dealing with this problem at least. I think the chat_vector_db approach that derekHsu posted is probably the closest thing to my simple use case. The problem with that for me is that the chat history is tied to the retrieval mechanism, whereas in my case, the chat history should be tied to the chat sequence portion of the application.

Anyway, again, maybe not super relevant, but can't find where else to discuss this.

**Comment by derekhsu** [comment]
Thanks for your effort. I think this should be enough for my request.
