### ISSUE TITLE
Incorrect model version on Langsmith

### ISSUE THREAD

**Issue by rmadrewar** [langchain-ai/langchain#21898]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_openai import ChatOpenAI, AzureChatOpenAI
llm = AzureChatOpenAI(
    azure_endpoint=azure_endpoint,
    openai_api_version="2024-02-01",
    deployment_name=deployment_name,
    openai_api_key=openai_api_key,
    openai_api_type=openai_api_type,
    temperature=0, model_kwargs={"seed": 42}
)
```

### Description

I am using langchain to run completions using AzureOpenAI **gpt-4-0125-preview** model. But I am seeing incorrect model version on Langsmith trace.  i.e. **gpt-3.5-turbo** as shown in below screenshot.

<img src="https://github.com/langchain-ai/langchain/assets/145645028/5c8462a7-ad00-4c39-aa5c-52fb757e8c61" width="400"> 

### System Info

langchain==0.1.9
langchain-community==0.0.24
langchain-core==0.1.26
langchain-openai==0.0.7
langsmith==0.1.8

**Comment by shreyas-shinde** [comment]
[rmadrewar](https://github.com/rmadrewar)
I am guessing based on similar experience, it might be related to this default value of `model` parameter in AzureChatOpenAI class. Can you try setting model paramater to `gpt-4-0125-preview` and check langsmith again? 

<img width="577" alt="Screenshot 2024-05-20 at 22 36 40" src="https://github.com/langchain-ai/langchain/assets/4473162/0e8b7a08-d4d5-4f77-ae94-db04e0b2b96a">

**Comment by 77philosophia** [comment]
> [rmadrewar](https://github.com/rmadrewar) I am guessing based on similar experience, it might be related to this default value of `model` parameter in AzureChatOpenAI class. Can you try setting model paramater to `gpt-4-0125-preview` and check langsmith again?
> 
> <img alt="Screenshot 2024-05-20 at 22 36 40" width="577" src="https://private-user-images.githubusercontent.com/4473162/332082451-0e8b7a08-d4d5-4f77-ae94-db04e0b2b96a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMTQ3ODQsIm5iZiI6MTcyMTIxNDQ4NCwicGF0aCI6Ii80NDczMTYyLzMzMjA4MjQ1MS0wZThiN2EwOC1kNGQ1LTRmNzctYWU5NC1kYjA0ZTBiMmI5NmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMTEwODA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI1MGNhYjIyOTNlZjNmYjQzOWNlZmYyYzdjMTlkOWU0MzA0NzAzZWRlYjM2Nzc4YTQwMWIyYWEwYTQ2M2IyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8_R2zwUOWilBn5iWSMoOwhbZfDEPWlKLQx8D8hL1oX0">

It works! Thanks!
