### ISSUE TITLE
DOC: `langchain-community` will be not installed with `pip install langchain`

### ISSUE THREAD

**Issue by OpenVINO-dev-contest** [langchain-ai/langchain#21905]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

`pip install langchain-community`

### Description

as my test on LangChain 0.2, `langchain-community` will be not installed with `pip install langchain`, which is conflicted with [document](https://python.langchain.com/v0.2/docs/how_to/installation/#langchain-community)

### System Info

Ubuntu

**Comment by eyurtsev** [comment]
This is an intentional change. Please review the release notes: https://python.langchain.com/v0.2/docs/versions/overview/#what-changed

langchain should not dependency on langchain-community going forward.

**Comment by eyurtsev** [comment]
fixing docs 
https://github.com/langchain-ai/langchain/pull/21920
