### ISSUE TITLE
Runnables have `astream_events`, but no synchronous `stream_events`

### ISSUE THREAD

**Issue by straygar** [langchain-ai/langchain#21918]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

n/a

### Description

I would like to stream response tokens from an `AgentExecutor`. Based on [these docs](https://python.langchain.com/v0.1/docs/modules/agents/how_to/streaming/#custom-streaming-with-events), the default event of `stream` is different from other runnables, and to stream tokens of the response, we're expected to use `astream_events`.

My codebase is currently not async, as it doesn't need to be (running on AWS Lambda, which just processes 1 request at a time). I see that most of the standard runnable methods come in sync and async pairs:
- `invoke` and `ainvoke`
- `stream` and `astream`

etc. However, `astream_events` does not have a sync alternative `stream_events`. Is there a reason for it or was it a mistake?

### System Info

```
langchain==0.1.15
langchain-community==0.0.32
langchain-core==0.1.42rc1
langchain-openai==0.1.3rc1
langchain-text-splitters==0.0.1
langchainhub==0.1.15
```
platform: MacOS
Python 3.10

**Comment by keenborder786** [comment]
@eyurtsev I am working on this one!!!

**Comment by keenborder786** [comment]
@eyurtsev I am going to first create a series of steps needed for this enhancement since it will require major changes in the `event_stream` in tracers.

**Comment by eyurtsev** [comment]
I'm not sure yet if we want to support it

**Comment by keenborder786** [comment]
@eyurtsev oh okay, so I should not work on it then???

**Comment by keenborder786** [comment]
Given the nature of the enhancement, it will require to add a new callback `_StreamEventsCallbackHandler` which means alot of new lines of code. LMK if you want it and if yes , I will be happy to take it's implementation.

**Comment by eyurtsev** [comment]
You could try to spec out with just on_chain_x events and separate implementation of the underlying callback handler. I'd want to check how much overhead the sync variant introduces over the async version

**Comment by keenborder786** [comment]
Ok

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by straygar** [comment]
OK, then it sounds like I should just refactor my codebase to expose streams as async, if I wanna make use of this?
