### ISSUE TITLE
KeyError: `chains` error when SimpleSequentialChain initialisation with RunnableSequence

### ISSUE THREAD

**Issue by MateuszOssGit** [langchain-ai/langchain#21962]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
watsonxllm = WatsonxLLM(
    model_id=MODEL_ID,
    url="https://us-south.ml.cloud.ibm.com",
    project_id=WX_PROJECT_ID,
)
from langchain_core.prompts import PromptTemplate

prompt_template = "Tell me a {adjective} joke"
prompt = PromptTemplate(
    input_variables=["adjective"], template=prompt_template
)
chain = prompt | watsonxllm
chain_2 = prompt | watsonxllm

from langchain.chains.sequential import SimpleSequentialChain

simple_chain = SimpleSequentialChain(chains=[chain, chain_2], verbose=True)
```

### Error Message and Stack Trace (if applicable)

KeyError: `chains`

Stacktrace
```
Traceback (most recent call last):
  File "/***/envs/langchain/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-54819a7b479b>", line 1, in <module>
    simple_chain = SimpleSequentialChain(chains=[chain, chain_2], verbose=True)
  File "/***/envs/langchain/lib/python3.10/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/***/envs/langchain/lib/python3.10/site-packages/pydantic/v1/main.py", line 1100, in validate_model
    values = validator(cls_, values)
  File "/***/Documents/GitHub/watsonxllm/libs/langchain/langchain/chains/sequential.py", line 158, in validate_chains
    for chain in values["chains"]:
KeyError: 'chains'
```

### Description

When i used LLMChain everything goes well 
```python
watsonxllm = WatsonxLLM(
    model_id=MODEL_ID,
    url="https://us-south.ml.cloud.ibm.com",
    project_id=WX_PROJECT_ID,
)
from langchain_core.prompts import PromptTemplate

prompt_template = "Tell me a {adjective} joke"
prompt = PromptTemplate(
    input_variables=["adjective"], template=prompt_template
)
from langchain.chains.llm import LLMChain

chain = LLMChain(prompt=prompt, llm=watsonxllm)
chain_2 = LLMChain(prompt=prompt, llm=watsonxllm)

from langchain.chains.sequential import SimpleSequentialChain

simple_chain = SimpleSequentialChain(chains=[chain, chain_2], verbose=True)
```

I noticed that LLMChain is deprecated so i changed `chain = LLMChain(prompt=prompt, llm=watsonxllm)` into `chain = prompt | watsonxllm` and i am getting error

### System Info

langchain                                0.2.0
langchain-community                      0.0.31
langchain-core                           0.2.0      
langchain-ibm                            0.1.7
langchain-text-splitters                 0.2.0

platform mac
Python 3.10.13

**Comment by HuAngchping** [comment]
https://github.com/langchain-ai/langchain/blob/8e1aeb8ad58392f502b997a3db797cfb5fbba33d/docs/docs/changes/changelog/langchain.mdx#L81

**Comment by MateuszOssGit** [comment]
@HuAngchping Thanks, with LCEL working fine.

**Comment by redserversh** [comment]
@HuAngchping @MateuszOssGit Can you please share a snippet of your code

**Comment by jpinzonc** [comment]
@redserversh  you can check my example to this answer: https://stackoverflow.com/questions/78508462/keyerror-in-simplesequentialchain/78562683#78562683

**Comment by redserversh** [comment]
Thankyou
