### ISSUE TITLE
Standardize docstrings and improve coverage

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#21983]
# Issue
Every public module, class, method and attribute should have a docstring. 

# Requirements
- All docstrings should follow the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods).
- Examples should use [RST code-block format](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block) so that they render in the API reference correctly.

### NOTE!
RST code block must have a newline between `.. code-block:: python` and the code example, and code example must be tabbed, to render correctly!

# Examples
## Module
`langchain/foo/__init__.py`
```python
""""One line summary.

More detailed paragraph.
"""
```

### Not Pydantic class
```python
class Foo:
  """One line summary.

  More detailed paragraph.
  
  Attributes:
    first_attr: does first thing.
    second_attr: does second thing.

  Example:
    .. code-block:: python
    
      from langchain.foo import Foo
  
      f = Foo(1, 2, "bar")
      ...
  """
  
  def __init__(self, a: int, b: int, c: str) -> None:
    """Initialize using a, b, c.
   
    Args:
      a: ...
      b: ...
      c: ...
   """
    self.first_attr = a + b
    self.second_attr = c
```

#### NOTE
If the object attributes and init args are the same then you can just document the init args for non-Pydantic classes and just document the attributes for Pydantic classes.

### Pydantic class
```python
from typing import Any

from langchain_core.base_models import BaseModel

class FooPydantic(BaseModel):
  """One line summary.

  More detailed paragraph.

  Example:
    .. code-block:: python
    
      from langchain.foo import Foo
  
      f = Foo(1, 2, "bar")
      ...
  """

  first_attr: int
  """Does first thing."""
  second_attr: str
  """Does second thing.

  Additional info if needed.
  """

    def __init__(self, a: int, b: int, c: str, **kwargs: Any) -> None:
    """Initialize using a, b, c.
   
    Args:
      a: ...
      b: ...
      c: ...
      **kwargs: ...
   """
    first_attr = a + b
    second_attr = c
    super().__init__(first_attr=first_attr, second_attr=second_attr, **kwargs)
```

## Function/method
```python
def bar(a: int, b: str) -> float:
  """One line description.

  More description if needed.

  Args:
    a: ...
    b: ...

  Returns:
    A float of ...

  Raises:
    ValueError: If a is negative.

  Example:
    .. code-block:: python
      
      from langchain.foo import bar

      bar(1, "foo")
      # -> 14.381
  """
```

**Comment by klaudialemiec** [comment]
I will start!

**Comment by harshamoole** [comment]
Hi, I would like to work on this docstring standardization issue and will open a PR shortly.

**Comment by ARYANBHAT-eng** [comment]
Hi, I’d like to work on improving docstrings in the output_parsers module (json, list, string). I’ve already prepared a PR for this. Could you please assign this issue to me?

**Comment by ramkumar27072006** [comment]
"I have prepared a docstring format fix for json.py to align with the Google-style guidelines mentioned here. Could you please assign this issue to me so my PR can be processed?"
