### ISSUE TITLE
Improve import statement for `create_retrieval_chain` to enhance code editor navigation

### ISSUE THREAD

**Issue by Omar-Eses** [langchain-ai/langchain#22009]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The current import statement in the ``` qa_chat_history.ipynb ``` tutorial uses dynamic import handling via a dictionary in the ``` langchain.chains ``` module called ``` _module_lookup ```. While this works at runtime, it might affect the development experience in code editors, as developers won't navigate to ``` create_retrieval_chain ``` function on click.
### Steps to check
1. Go to the [QA Chat History tutorial](https://github.com/langchain-ai/langchain/blob/master/docs/docs/tutorials/qa_chat_history.ipynb)
2. Check the import statement: ``` from langchain.chains import create_retrieval_chain ```.
3. Attempt to navigate to `create_retrieval_chain` in the code editor.

### Expected Behavior
Developers should be able to navigate to `create_retrieval_chain` definition on click in the code editor

### Current Behavior
Developers can't navigate to ` create_retrieval_chain` on click.

### Suggested Improvement

Consider updating the import statement to: 
```python
from langchain.chains.retrieval import create_retrieval_chain
```
### Image attached to show pov:
<img width="662" alt="Screenshot 2024-05-22 at 3 42 50 AM" src="https://github.com/langchain-ai/langchain/assets/71525113/8c669204-970e-4596-90d2-95a62371af6d">

**Comment by Fadil1710** [comment]
Nanba I m also suffering from same, how did you resolve

**Comment by basapuram-kumar** [comment]
imports are failing

From 

```
 from langchain.chains.retrieval import create_retrieval_chain 
from langchain.chains.combine_documents import create_stuff_documents_chain
```

> 
`ErrorModuleNotFoundError: No module named 'langchain.chains'`

To

```

from langchain_classic.chains.retrieval import  create_retrieval_chain 
from langchain_classic.chains.combine_documents import create_stuff_documents_chain 
```

I believe these are equivalent to above failings/
