### ISSUE TITLE
DOC: wrong prompt hub link

### ISSUE THREAD

**Issue by tjuwhy** [langchain-ai/langchain#22014]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

>  reduce_prompt = hub.pull("rlm/map-prompt")  
  reduce_prompt

https://python.langchain.com/v0.1/docs/use_cases/summarization/#option-2-map-reduce

`hub.pull("rlm/map-prompt")`  should be `hub.pull("rlm/reduce-prompt")`

**Comment by artemd24** [comment]
I'd like to tackle this!
