### ISSUE TITLE
ChromaDB/VectorStore Problem: "NotEnoughElementsException: Number of requested results 4 cannot be greater than number of elements in index 1"

### ISSUE THREAD

**Issue by pmcray** [langchain-ai/langchain#2205]
I am using langchain in CoLab and have come across this ChromaDB/VectorStore problem a few times, mostly recently with the code below. The piece of text I am importing is only a few hundred characters. I found this issue on the ChromaDB repository: https://github.com/chroma-core/chroma/issues/225, which is the same or similar issue. This made be think it might be that I didn't need to split the text, but it makes no difference when hashed out the text splitter lines. Any thoughts on what might the issue here?

loader = TextLoader('./report.txt')
documents = loader.load()
#text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
#texts = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()
report_store = Chroma.from_documents(documents, embeddings, collection_name="report")

llm = OpenAI(temperature=0)

vectorstore_info = VectorStoreInfo(name="report", description="the most recent weekly API report", vectorstore=report_store)

toolkit = VectorStoreToolkit(vectorstore_info=vectorstore_info)
agent_executor = create_vectorstore_agent(llm=llm, toolkit=toolkit, verbose=True)

agent_executor.run("How many APIs were in the Red Zone this week?")

> Entering new AgentExecutor chain...
 I need to find out the answer from the report
Action: report
Action Input: How many APIs were in the Red Zone this week?
---------------------------------------------------------------------------
NotEnoughElementsException                Traceback (most recent call last)
[<ipython-input-21-22938c4f7204>](https://localhost:8080/#) in <cell line: 1>()
----> 1 agent_executor.run("How many APIs were in the Red Zone this week?")

18 frames
[/usr/local/lib/python3.9/dist-packages/chromadb/db/index/hnswlib.py](https://localhost:8080/#) in get_nearest_neighbors(self, query, k, ids)
    226 
    227         if k > self._index_metadata["elements"]:
--> 228             raise NotEnoughElementsException(
    229                 f"Number of requested results {k} cannot be greater than number of elements in index {self._index_metadata['elements']}"
    230             )

NotEnoughElementsException: Number of requested results 4 cannot be greater than number of elements in index 1

**Comment by croze97** [comment]
Same problem here, had to do some funky things to my List[Document] after pulling from YoutubeLoader to get past a JSON serialization TypeError, converted every page_content to utf-8 and reconstructed the list. Was curious if that was causing this error, but thinking not after seeing your post, commenting for visibility.

**Comment by croze97** [comment]
I managed to get past this one myself in a pretty strange way.
First, I had a TypeError to resolve, a Document in my List[Document] contained a metadata entry of type DateTime which threw a JSONSerialization error. I solved this my creating a new List[Document] and reconstructing it with only types JSON supports.

Then I reached the error you mentioned, which I solved by manually adding 3 more entries to the List[Document] (I noticed I was only reconstructing 1 entry)

for i in range(3):
    utf8_list_documents.append(Document(page_content="null", metadata={}))

**Comment by EAYoshi** [comment]
A very similar question is answered here which might be of use: https://github.com/hwchase17/langchain/issues/2255

**Comment by svk-cu-nlp** [comment]
This is the solution if you use Langchain and ChromaDB

qa = ChatVectorDBChain.from_llm(ChatOpenAI(openai_api_key=OPENAI_API_KEY, temperature=0), docsearch, qa_prompt=prompt, top_k_docs_for_context=1)
