### ISSUE TITLE
error with VectorstoreIndexCreator initiation

### ISSUE THREAD

**Issue by jitvimol** [langchain-ai/langchain#22063]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain.indexes import VectorstoreIndexCreator
from langchain_community.document_loaders.hugging_face_dataset import (
    HuggingFaceDatasetLoader,
)
dataset_name = "tweet_eval"
page_content_column = "text"
name = "stance_climate"

loader = HuggingFaceDatasetLoader(dataset_name, page_content_column, name)
index = VectorstoreIndexCreator().from_loaders([loader])
```

### Error Message and Stack Trace (if applicable)

```
339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
340 if validation_error:
--> 341     raise validation_error
342 try:
343     object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for VectorstoreIndexCreator
embedding
field required (type=value_error.missing)
```

### Description

index = VectorstoreIndexCreator().from_loaders([loader])

The above code cause error.

I following code at https://github.com/Ryota-Kawamura/LangChain-for-LLM-Application-Development

In addition,  at Langchain docs at [langchain docs](https://python.langchain.com/v0.1/docs/integrations/document_loaders/hugging_face_dataset/) it show that we can run the code but we run with error 

### System Info

```
[packages]
langchain = "*"
python-dotenv = "*"
openai = "==0.28"
langchain-community = "*"
langchain-core = "*"
tiktoken = "*"
docarray = "*"
```

**Comment by jitvimol** [comment]
update:  if change package version as per below , the code will work.

[packages]
langchain = "==0.0.179"
python-dotenv = "==1.0.0"
openai = "==0.27.7"
langchain-community = "*"
langchain-core = "*"
tiktoken = "==0.4.0"
docarray = "==0.37.0"

**Comment by eyurtsev** [comment]
https://python.langchain.com/v0.2/docs/versions/v0_2/deprecations/

**Comment by eyurtsev** [comment]
Closing issue as this was an intentional breaking change in 0.2

@jitvimol please you can review versioning here: https://python.langchain.com/v0.2/docs/versions/release_policy/
