### ISSUE TITLE
When use Ollama model (llama3) with RunnableWithMessageHistory I got error `Error in RootListenersTracer.on_llm_end callback: KeyError('message')`

### ISSUE THREAD

**Issue by dmytrovskyi** [langchain-ai/langchain#22060]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.llms import Ollama
from langchain_core.messages import HumanMessage
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory

model = Ollama(model="llama3")

store = {}

def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

with_message_history = RunnableWithMessageHistory(model, get_session_history)

config = {"configurable": {"session_id": "abc2"}}

response = with_message_history.invoke(
  [HumanMessage(content="Hi! I`m Bob")],
  config=config
)
```

### Error Message and Stack Trace (if applicable)

Error in RootListenersTracer.on_llm_end callback: KeyError('message')

### Description

I'm trying to implement a basic tutorial [Build a Chatbot]( https://python.langchain.com/v0.2/docs/tutorials/chatbot/) with a local Ollama llama3 model. 
But I got the error `Error in RootListenersTracer.on_llm_end callback: KeyError('message')` and the functionality with history didn't work.
I made a debug and found that in RunnableWithMessageHistory class on [line 413](https://github.com/langchain-ai/langchain/blob/37cfc003107ea800953be912f2eebfbf069c9587/libs/core/langchain_core/runnables/history.py#L413) code expected that response from model will be in `message` field but this response is in `text` field. 
Also, current implementation of lib doesn't allow to pass the complex key like `["generations"][0][0]["text"]`.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000
> Python Version:  3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.2.1
> langchain: 0.2.0
> langchain_community: 0.2.0
> langsmith: 0.1.60
> langchain_text_splitters: 0.2.0

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by cdmazhicheng** [comment]
May I ask if a brother has solved this problem?

**Comment by xitong-0629** [comment]
I'm also wondering.

**Comment by cdmazhicheng** [comment]
我已经收到您的邮件！

**Comment by sharoningithub** [comment]
+1

**Comment by tarikhagustia** [comment]
+1 using GoogleGenerativeAI

**Comment by CrazyOn** [comment]
You could try replacing from `langchain_community.llms import Ollama` with `from langchain_community.chat_models import ChatOllama` and see if the error is resolved.

``` python
# from langchain_community.llms import Ollama
from langchain_community.chat_models import ChatOllama
```

**Comment by dmytrovskyi** [comment]
> You could try replacing from `langchain_community.llms import Ollama` with `from langchain_community.chat_models import ChatOllama` and see if the error is resolved.
> 
> ```python
> # from langchain_community.llms import Ollama
> from langchain_community.chat_models import ChatOllama
> ```

Thank @CrazyOn this works for me! 
And it looks logical to use `ChatOllama` in a chat with the history instead of `Ollama`.

**Comment by snowblow07** [comment]
> > You could try replacing from `langchain_community.llms import Ollama` with `from langchain_community.chat_models import ChatOllama` and see if the error is resolved.
> > ```python
> > # from langchain_community.llms import Ollama
> > from langchain_community.chat_models import ChatOllama
> > ```
> 
> Thank @CrazyOn this works for me! And it looks logical to use `ChatOllama` in a chat with the history instead of `Ollama`.

I have been 2 days looking for a solution to this issue, thank you so much!!
replacing the whole thing it looks something like this:
`# ! pip install langchain langchain_community
#from langchain.llms import Ollama
from langchain_community.chat_models import ChatOllama
model = ChatOllama(model="llama3")`
Thank you @CrazyOn and @dmytrovskyi ; I am just wondering if there is any other difference between ChatOllama and Ollama in the langchain_community.llms library?

**Comment by folushooladipo** [comment]
Thank you, oh thank you @CrazyOn ! Not only did you help me resolve this issue, your fix also led to me fixing my implementation of [this tutorial](https://python.langchain.com/v0.2/docs/tutorials/chatbot/#message-history) from LangChain! The tutorial didn't use Ollama directly, so I didn't know I had to import it from somewhere else. Thank you so much!

**Comment by cdmazhicheng** [comment]
我已经收到您的邮件！
