### ISSUE TITLE
Plugin chat gpt

### ISSUE THREAD

**Issue by feyhero** [langchain-ai/langchain#2208]

**Comment by LaloLalo1999** [comment]
You mean this? [ChatGPT Plugins](https://python.langchain.com/en/latest/modules/agents/tools/examples/chatgpt_plugins.html?highlight=plugin), [ChatGPT Plugin Retriever](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/chatgpt-plugin-retriever.html?highlight=plugin)
