### ISSUE TITLE
ChatOllama does not support bind_tools

### ISSUE THREAD

**Issue by Harsh-Kesharwani** [langchain-ai/langchain#22165]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

ChatOllama does not support bind_tools

### Description

ChatOllama does not support bind_tools

### System Info

ChatOllama does not support bind_tools

**Comment by keenborder786** [comment]
You can use `OllamaFunctions` from `langchain_experimental.llms.ollama_functions`

**Comment by Harsh-Kesharwani** [comment]
@keenborder786 But i have to use function calling along with chat messages as open ai support in there API v1/completion.

**Comment by noshila** [comment]
nothing except for openai, mistral, google or others like that work. I tried with llama.cpp (original, python and server), ollama, kobold but now I am certain no opensource model or library works exactly like openai api.

**Comment by keenborder786** [comment]
I am afraid that is not possible because `Function Calling` is a special capability offered only by [OpenAI](https://platform.openai.com/docs/guides/function-calling)

**Comment by keenborder786** [comment]
But you can always use tool calling by any llm using [React](https://python.langchain.com/v0.1/docs/modules/agents/agent_types/react/) agent.

**Comment by lalanikarim** [comment]
Take a look at #22339 which should have addressed this issue.
The PR was approved and merged yesterday but a release is yet to be cut from it and should happen in the next few days.

In the meantime, you may try and install `langchain-experimental` directly from langchain's source like this:

```bash
pip install git+https://github.com/langchain-ai/langchain.git\#egg=langchain-experimental\&subdirectory=libs/experimental
```

I hope this helps.
