### ISSUE TITLE
Failed to decide which tool to use.

### ISSUE THREAD

**Issue by SDADSWws** [langchain-ai/langchain#2217]
> Entering new AgentExecutor chain...
Thought: Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input:  Wolfram Alpha 222+222
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha 222+222
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha what is the solution to 222+222?
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha "what is 222+222?"
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha "solve 222+222"
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha "what is the sum of 222 and 222?"
Observation: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha] is not a valid tool, try another one.
Thought:Do I need to use a tool? Yes
Action: the action to take, should be one of [Time, TODO List, Python Execute, Wolfram Alpha]
Action Input: Wolfram Alpha "what is 222+222"

**Comment by ZhangHanwen96** [comment]
code?

**Comment by cfddb** [comment]
Have you solved this problem yet
