### ISSUE TITLE
FAISS - Incorrect relevance score with MAX_INNER_PRODUCT distance metric.

### ISSUE THREAD

**Issue by habanoz** [langchain-ai/langchain#22209]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I used notebook in official faiss page for reference. Here is the reference code.
https://python.langchain.com/v0.1/docs/integrations/vectorstores/faiss/

To show the issue, I modified it to use max_inner_product distance strategy. Here is the modified code section.
db = FAISS.from_documents(docs, embeddings, distance_strategy=DistanceStrategy.MAX_INNER_PRODUCT)

### Description

Reference code which uses l2 distance by default generates following output:

![image](https://github.com/langchain-ai/langchain/assets/6825980/658d80a1-9657-453a-a119-dff29a2c5b04)

Modified code which uses max_inner_product distance generates the following output:

![image](https://github.com/langchain-ai/langchain/assets/6825980/75fee62b-97e2-4b38-8dff-4e866790de93)

Relevance score by definition is between 0-1. 0 is dissimilar, 1 is most similar. See reference 1.

Reference code output produces valid relevance score, in which most similar document have relevant score closest to 1.

Modified code using MAX_INNER_PRODUCT, produces invalid relevance score, in which most similar document have relevant score most distant to 1. This contradicts with the definition of relevance score. 

References:
1- https://api.python.langchain.com/en/latest/vectorstores/langchain_core.vectorstores.VectorStore.html  

### System Info

langchain==0.2.1
langchain-community==0.2.1
langchain-core==0.2.1
langchain-openai==0.1.7
langchain-text-splitters==0.2.0
faiss-cpu==1.8.0

**Comment by keenborder786** [comment]
Yes it is supposed to be in that way, try to understand the metrics:

- For L2/euclidean distance, the more the similar vector are the lesser their distance will be therefore higher the normalized score will be since it is calculated in langchain using the following formula
```python
1.0 - distance / math.sqrt(2)
```
- However, for inner product, the more the similar vector are the higher the dot product will be therefore the lower the normalized score will be since it is calculated in langchain using the following formula:

```python
if distance > 0:
    return 1.0 - distance
return -1.0 * distance
```

**Comment by habanoz** [comment]
> Yes it is supposed to be in that way, try to understand the metrics:
> 
>     * For L2/euclidean distance, the more the similar vector are the lesser their distance will be therefore higher the normalized score will be since it is calculated in langchain using the following formula
> 
> 
> ```python
> 1.0 - distance / math.sqrt(2)
> ```
> 
>     * However, for inner product, the more the similar vector are the higher the dot product will be therefore the lower the normalized score will be since it is calculated in langchain using the following formula:
> 
> 
> ```python
> if distance > 0:
>     return 1.0 - distance
> return -1.0 * distance
> ```

Thanks @keenborder786 . I do not understand how normalized score is related to our discussion. My concern is about relevance score. Here is the definition of relevance score from official langchain faiss documentation. 

![image](https://github.com/langchain-ai/langchain/assets/6825980/01a19dbc-8f4b-406f-b60e-b15ef92a61b9)

And here is a more detailed output from MAX_INNER_PRODUCT case. As it is clearly visible, most similar document has the lowest relevance score (0.184) which is in contradiction to the definition of the relevance score. It should have had the greatest relevance score, compared to less similar documents. 

The definition of relevance score does not mention any distance metric, thus I assume it is distance metric agnostic. Even if it is not agnostic the issue is still valid. 

![image](https://github.com/langchain-ai/langchain/assets/6825980/671ce44e-e18e-4f3a-9a48-089d3c95f848)

**Comment by keenborder786** [comment]
@habanoz Please see this [line](https://github.com/langchain-ai/langchain/blob/8332a36f6937a78d3b1aec8d7b7e5bd60072a46f/libs/community/langchain_community/vectorstores/faiss.py#L1166),  the scores are always normalized after `similarity_search_with_relevance_scores` has been called.

**Comment by habanoz** [comment]
> @habanoz Please see this [line](https://github.com/langchain-ai/langchain/blob/8332a36f6937a78d3b1aec8d7b7e5bd60072a46f/libs/community/langchain_community/vectorstores/faiss.py#L1166), the scores are always normalized after `similarity_search_with_relevance_scores` has been called.

Yes it is. I have debugged the code and have some idea of how it works.

But i did not mention the code so far. I am trying to articulate documentation and behaviour is different. (What happens in the code matters less. Maybe there is  bug in the code. Maybe it should not be normalized, maybe it should be normalized in a different way.)

@keenborder786 Do you think my understanding on the definition of relevance score is wrong, if so in what ways?

Thanks
