### ISSUE TITLE
Chatbot using HuggingFace model, not working

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#2224]
I am trying to create a chatbot using your documentation from here:
https://python.langchain.com/en/latest/modules/agents/agent_executors/examples/chatgpt_clone.html

However, in order to reduce costs, instead of using ChatGPT I want to use a HuggingFace Model.
I tried to use a conversational model, but I got an error that this task is not implemented yet and that it only supports TextGeneration and Tex2TextSequence.

So, I went to the hub and got the model ID with the most likes/downloads and I am testing it:

```
from langchain import PromptTemplate, HuggingFaceHub, LLMChain
from langchain.llms import HuggingFacePipeline
from langchain.llms import HuggingFaceHub
import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "x"
from langchain.chat_models import ChatOpenAI
from langchain import PromptTemplate, LLMChain
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)
from langchain import PromptTemplate, HuggingFaceHub, LLMChain
from langchain.memory import ConversationBufferWindowMemory

template = """Assistant is a large language model trained by OpenAI.

Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.

Assistant is constantly learning and improving, and its capabilities are constantly evolving. It is able to process and understand large amounts of text, and can use this knowledge to provide accurate and informative responses to a wide range of questions. Additionally, Assistant is able to generate its own text based on the input it receives, allowing it to engage in discussions and provide explanations and descriptions on a wide range of topics.

Overall, Assistant is a powerful tool that can help with a wide range of tasks and provide valuable insights and information on a wide range of topics. Whether you need help with a specific question or just want to have a conversation about a particular topic, Assistant is here to assist.

{history}
Human: {human_input}
Assistant:"""

prompt = PromptTemplate(
    input_variables=["history", "human_input"], 
    template=template
)

llm = HuggingFaceHub(repo_id="facebook/mbart-large-50", model_kwargs={"temperature":0, "max_length":64})
llm_chain = LLMChain(prompt=prompt, llm=llm, memory=ConversationBufferWindowMemory(k=2))
output = llm_chain.predict(human_input="Whats the weather like?")
print(output)
```

However in the Google Colab output, all I get is this:
`Assistant is a large language model trained by OpenAI. Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. As a language model, Assistant is able to generate
`

And no prediction is in the output.

What am I missing?

**Comment by alexiri** [comment]
Wild guess, but could it be because of the `max_length` you've set?

**Comment by levalencia** [comment]
I increased the length to 8000 and now I got this:

AI: Assistant is a large language model trained by OpenAI. Assistant is designed to be able to assist with a wide range of tasks, from answering simple questions to providing in-depth explanations and discussions on a wide range of topics. Human: Whats the weather like? Assistant:

So the answer from Assistant is still empty

**Comment by levalencia** [comment]
anyone has any additional idea of what am I missing?

**Comment by bmwas** [comment]
Thanks for sharing this ...looking for a similar solution to cut costs as well. It looks like the issue here is the repo type ---if you change repo to  repo_id="google/flan-t5-xl" - you should get a somewhat relevant response. Off course, I'm also trying with more advanced models (esp. dolly-v2) but it's not working for me as well.

**Comment by Wamy-Dev** [comment]
Apparently Langchain does not support conversation bots yet? I really don't know why that would be though.
