### ISSUE TITLE
DOC: Azure OpenAI users should be counseled to specify 2024-02-01 as the API version, otherwise streaming support will be buffered

### ISSUE THREAD

**Issue by chrislrobert** [langchain-ai/langchain#22252]
### URL

https://python.langchain.com/v0.1/docs/integrations/llms/azure_openai/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

[A recent Microsoft announcement](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/announcing-key-updates-to-responsible-ai-features-and-content/ba-p/4142730) revealed that they made [the Azure OpenAI asynchronous filtering](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/content-filter?tabs=warning%2Cpython#content-streaming) generally available, which is fantastic. However, when I tried to use it, I continued to experience buffering in streamed responses and therefore a poor UX from Azure's endpoints (vs. OpenAI's direct endpoints).

### Idea or request for content:

After [the journey discussed here](https://github.com/langchain-ai/langchain/discussions/22246), I discovered that the issue was the API version I was passing to `AzureChatOpenAI`: I was passing `2023-05-15`, which was previously the last stable version, whereas I needed to update to `2024-02-01` instead.

[The current LangChain documentation page](https://python.langchain.com/v0.1/docs/integrations/llms/azure_openai/) suggests `2023-12-01-preview` as the version to use — but Microsoft has been sunsetting these preview API releases and it doesn't seem wise to depend on them in production. Rather, `2024-02-01` is the current recommended GA API version, and it seems to work well. I recommend updating the documentation accordingly.

**Comment by chaityacshah** [comment]
I would like to work on this
