### ISSUE TITLE
ConversationalRetrievalChain does not correctly answer some questions in the document

### ISSUE THREAD

**Issue by brent0126** [langchain-ai/langchain#22255]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

embeddings = OpenAIEmbeddings()
    vectorstore = FAISS.load_local(f"{directory_path}", embeddings)
    retriever_list = vectorstore.as_retriever(search_kwargs={"score_threshold": 0.65, "k": 6 })
    
    
    model = "gpt-3.5-turbo-0125"
    llm = ChatOpenAI(model=model, temperature=0)
    streaming_llm = ChatOpenAI(
        model=model,
        streaming=True,
        callbacks=[callback],
        temperature=0
    )

    question_generator = LLMChain(llm=llm, prompt=QA_PROMPT)
    doc_chain = load_qa_chain(streaming_llm, chain_type="stuff", prompt=QA_PROMPT)

    conversation_chain = ConversationalRetrievalChain(
        retriever=retriever_list,
        return_source_documents=True,
        # verbose=True,
        combine_docs_chain=doc_chain,
        question_generator=question_generator
    )

### Description

Hello all. 
I am experiencing an issue when using ConversationalRetrievalChain with multiple vectorstores and merging them. I notice that when querying, the content returned is not complete. Upon checking, I found that the content is divided into two parts, but the query only retrieves the first part. How can I resolve this issue? and ConversationalRetrievalChain does not correctly answer some questions in the document

### System Info

langchain==0.0.327

**Comment by keenborder786** [comment]
For `Question Generator` you are using the wrong prompt. You need to use the following prompt or something similar:

```python

template = (
                "Combine the chat history and follow up question into "
                "a standalone question. Chat History: {chat_history}"
                "Follow up question: {question}"
            )
  prompt = PromptTemplate.from_template(template)

```

**Comment by hoangsonsky** [comment]
> For `Question Generator` you are using the wrong prompt. You need to use the following prompt or something similar:
> 
> ```python
> template = (
>                 "Combine the chat history and follow up question into "
>                 "a standalone question. Chat History: {chat_history}"
>                 "Follow up question: {question}"
>             )
>   prompt = PromptTemplate.from_template(template)
> ```

I am using langchain's own prompt.
```

from langchain.chains.conversational_retrieval.prompts import (
    CONDENSE_QUESTION_PROMPT, QA_PROMPT
)
```

```
prompt_template = """Use the following pieces of context to answer the question at the end. Requests must be made to answer in full detail without leaving out any content in context. If you don't know the answer, just say you don't know, don't try to make up an answer.

{context}

Question: {question}
Helpful Answer:"""
QA_PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)
```
