### ISSUE TITLE
similarity Search Issue 

### ISSUE THREAD

**Issue by mohitraj** [langchain-ai/langchain#2225]
We are using Chroma for storing the records in vector form. When searching the query, the return documents do not give accurate results.  
c1 = Chroma('langchain', embedding, persist_directory)
qa = ChatVectorDBChain(vectorstore=c1,  combine_docs_chain=doc_chain, question_generator=question_generator,top_k_docs_for_context=12, return_source_documents=True)
 
What is the solution to get accurate results?

**Comment by mofahad** [comment]
can tuke chucksize and overlaping paramter when you splitting the text and see will it improve acc. In my case it actually work

**Comment by mohitraj** [comment]
What is your chunk size and overlapping parameter?

**Comment by khimaros** [comment]
for me, when using LlamaCppEmbedding, chunk and overlap was not helpful. the results returned are almost in reverse order of what they should be with the best results almost dead last.
