### ISSUE TITLE
Add on_agent_observation method to BaseCallbackHandler for custom observation logic

### ISSUE THREAD

**Issue by sostholmwork** [langchain-ai/langchain#2226]
Hello!

I've noticed that when creating a custom CallbackHandler in LangChain, there is currently no method for dealing with the Observation step. Specifically, in the agent.py file, the Agent and AgentExecutor class does not call any on_agent_observation function, and this function is not present in the BaseCallbackHandler base class.

I propose adding an on_agent_observation method to the BaseCallbackHandler, and calling this method at the end of both the _take_next_step and _atake_next_step functions in the Agent and AgentExecutor. This would enable developers to run custom logic for this step, such as streaming the observation to a frontend client.

I think usefulness of this feature cannot be understated, especially for scaling applications based on LangChain where multiple people will be involved in debugging.

I hope this proposal makes sense and will be useful for other developers. Please let me know if you have any feedback or concerns.

**Comment by mperezjodal** [comment]
Hi @sostholmwork I am using a Custom Agent and wanted to stream *just the final response*, do you know if that is supported already? and how to do it?

Thank you!
