### ISSUE TITLE
Unable to use asynchronous argument with FAISS.load_local

### ISSUE THREAD

**Issue by DarrenChiang** [langchain-ai/langchain#22299]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import boto3
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import BedrockEmbeddings

class Document():
    def __init__(self, content, source):
        self.page_content = content
        self.metadata = { 'source': source }

def data_ingestion():
    documents = [
        Document('Contents1', 'Doc1'),
        Document('Contents2', 'Doc2')
    ]

    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=10000,
        chunk_overlap=1000
    )

    return text_splitter.split_documents(documents)

def store_vectors(embeddings, documents, directory):
    vectorstore_faiss = FAISS.from_documents(
        documents,
        embeddings
    )

    vectorstore_faiss.save_local(directory)

INDEX_DIR = 'test_index'
bedrock = boto3.client(service_name='bedrock-runtime', region_name='us-west-2')
bedrock_embeddings = BedrockEmbeddings(model_id='amazon.titan-embed-text-v2:0', client=bedrock)

# Store documents
docs = data_ingestion()
store_vectors(bedrock_embeddings, docs, INDEX_DIR)

# Load documents
vector_store = FAISS.load_local(
    INDEX_DIR,
    bedrock_embeddings,
    allow_dangerous_deserialization=True,
    asynchronous=True
)

```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/root/aws-doc-sdk-examples/python/example_code/bedrock-runtime/models/mistral_ai/example_code.py", line 41, in <module>
    vector_store = FAISS.load_local(
  File "/root/aws-doc-sdk-examples/python/example_code/bedrock-runtime/rag/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py", line 1098, in load_local
    return cls(embeddings, index, docstore, index_to_docstore_id, **kwargs)
TypeError: FAISS.__init__() got an unexpected keyword argument 'asynchronous'
```

### Description

In the documentation here: https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.faiss.FAISS.html#langchain_community.vectorstores.faiss.FAISS.load_local

It says that I can use the asynchronous argument to use the async version. However, when I try it, I get the stack trace such that FAISS.__init__() got an unexpected keyword argument 'asynchronous'.

It is possible I am misunderstanding the usage of this feature. In the example code, I am simply trying to call load_local with this argument.

### System Info

"pip freeze | grep langchain"
langchain==0.2.1
langchain-aws==0.1.4
langchain-community==0.2.0
langchain-core==0.2.0
langchain-text-splitters==0.2.0
langchainhub==0.1.15

Platform: Ubuntu 20.04.6 LTS

Python Version: 3.10.14

**Comment by wulifu2hao** [comment]
After reading the code in faiss.py, I suspect that the documentation about the parameter "asynchronous: whether to use async version or not" is an error and should be removed. 

the functions "save_local" and "load_local" themselves do not have an async version, but once you get an instance of the FAISS object, you can do most of the things using "await vector_store.<async version of the function>" like 
`await vector_store.aadd_texts(<arguments>)`
