### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/qa_chat_history/>

### ISSUE THREAD

**Issue by amersheikh** [langchain-ai/langchain#22400]
### URL

https://python.langchain.com/v0.2/docs/tutorials/qa_chat_history/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

How do you limit the number of previous conversations for the checkpoint memory ? As it is shown in the documentation, The checkpoint just grows and grows which eventually exceeds the LLM input token limit.

https://python.langchain.com/v0.2/docs/tutorials/qa_chat_history/

### Idea or request for content:

Please add a section on how to limit the the number of previopus conversations that go into a checkpoint.

https://python.langchain.com/v0.2/docs/tutorials/qa_chat_history/

**Comment by wulifu2hao** [comment]
I suspect it's not just an issue with documentation. The react agent is created by using 
`from langgraph.prebuilt import create_react_agent`
and its implementation in langgraph keeps the message in [AgentState](https://github.com/langchain-ai/langgraph/blob/e1e502acfde2d2dd8bee199b6656df9fd302f0f2/langgraph/prebuilt/chat_agent_executor.py#L32) and currently there is no implementation to provide some kind of buffer window memory to manage these messages like [ConversationBufferWindowMemory](https://python.langchain.com/v0.1/docs/modules/memory/types/buffer_window/)

**Comment by amersheikh** [comment]
The workaround is to use place a create_react_agent with tools. Then place it in a LCEL chain with a prompt and then to wrap all of it with RunnableWithMessageHistory. See:- https://python.langchain.com/v0.2/docs/tutorials/chatbot/
The message list can be limited quite easily.

**Comment by wulifu2hao** [comment]
Thanks @amersheikh it does work as a workaround

`# create agent executor without checkpointer
agent_executor = chat_agent_executor.create_tool_calling_executor(
    llm, tools
)

# manage message history limit
from langchain_core.runnables import RunnablePassthrough
def filter_messages(messages, k=3):
    return messages[-k:]

chain = (
    RunnablePassthrough.assign(messages=lambda x: filter_messages(x["messages"]))
    | agent_executor
)

# manage message history using a store
store = {}
def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]
with_message_history = RunnableWithMessageHistory(
    chain,
    get_session_history,
    input_messages_key="messages",
)


config = {"configurable": {"session_id": "abc20"}}  
# 1st run: tell AI my name
response = with_message_history.invoke(
    {
        "messages": [HumanMessage(content="hi, I'm Bob")],
    },
    config=config,
)
print(response)

# 2nd run: give AI some non-sense information
response = with_message_history.invoke(
    {
        "messages": [HumanMessage(content="what is 1+1?")],
    },
    config=config,
)
print(response)

# 3rd run: ask AI what's my name, it should have forgeten
response = with_message_history.invoke(
    {
        "messages": [HumanMessage(content="what's my name?")],
    },
    config=config,
)
print(response)`

However I'm not sure if it is a idiomatic way of using the StateGraph. It seems to be a desirable feature for it to provide a way of limiting message history
