### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/retrievers/>

### ISSUE THREAD

**Issue by arupsarkar** [langchain-ai/langchain#22412]
### URL

https://python.langchain.com/v0.2/docs/tutorials/retrievers/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I am using Mac Silicon M1, 
When I am executing 
```
from langchain_chroma import Chroma
from langchain_openai import OpenAIEmbeddings

vectorstore = Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings(),
)
```
I am getting the error

> ImportError: dlopen(/Users/arupsarkar/miniconda3/envs/llm_env/lib/python3.12/site-packages/hnswlib.cpython-312-darwin.so, 0x0002): tried: '/Users/arupsarkar/miniconda3/envs/llm_env/lib/python3.12/site-packages/hnswlib.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/arupsarkar/miniconda3/envs/llm_env/lib/python3.12/site-packages/hnswlib.cpython-312-darwin.so' (no such file), '/Users/arupsarkar/miniconda3/envs/llm_env/lib/python3.12/site-packages/hnswlib.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

### Idea or request for content:

How can I make this compatible with my Apple Silicon M1.
I am also using conda (miniconda) environment

**Comment by hwchase17** [comment]
This is an issue with hnswlib, which is a dependency of chromadb. I would open up issues there. You can always use a different vectorstore
