### ISSUE TITLE
Support native HuggingFace env vars

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#22448]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

huggingface_hub has its own environment variables that it reads from: https://huggingface.co/docs/huggingface_hub/main/en/package_reference/environment_variables. Langchain x HuggingFace integrations should be able to read from these, too.

**Comment by liugddx** [comment]
i want try

**Comment by liugddx** [comment]
<img width="1201" alt="image" src="https://github.com/langchain-ai/langchain/assets/48236177/0bd0d864-aae5-4903-9b98-d3f32b2966aa">

I found that the parameters for environment variables have been specified here. Do we still need to specify them separately?

**Comment by wenngong** [comment]
@baskaryan Please review #23309. Let me know if I miss any part, Thx.

**Comment by zk1tty** [comment]
@wenngong I think you might also need to mention @liugddx !

**Comment by wenngong** [comment]
> @wenngong I think you might also need to mention @liugddx !

Loop @liugddx. 

Hi liugddx, please review this PR: #23309 related to this issue.
