### ISSUE TITLE
Tavily Search Results ainvoke not working

### ISSUE THREAD

**Issue by isahers1** [langchain-ai/langchain#22445]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code: 
```
from langchain_community.tools.tavily_search import TavilySearchResults

search = TavilySearchResults(max_results=2)
await search.ainvoke("what is the weather in SF")
```

### Error Message and Stack Trace (if applicable)

"ClientConnectorCertificateError(ConnectionKey(host='api.tavily.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))"

### Description

invoke does work

### System Info

Running off master

**Comment by baskaryan** [comment]
seems to be ssl issue, unrelated to Tavily

**Comment by ltoniazzi** [comment]
@baskaryan Sorry how does one solve it? (other api calls work in my app but not Tavily's)

**Comment by romanh24** [comment]
@isahers1 I have the same error. Did you fix it? How?

**Comment by WendyX94** [comment]
same error. any help?

**Comment by lldxflwb** [comment]
是的 当我尝试这么做的时候。他稳定复现
```python
from langchain_community.tools.tavily_search import TavilySearchResults

async def main():
    search = TavilySearchResults(max_results=2)
    print(await search.ainvoke("what is the weather in SF"))
```

输出
```shell
ClientConnectorCertificateError(ConnectionKey(host='api.tavily.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)'))
```
或许是需要使用异步客户端的原因？

**Comment by lldxflwb** [comment]
我最后的解决方案是
```python
from langchain_core.tools import tool
@tool
def SearchResult(question :str)->Any:
    """网络检索工具"""
    search = TavilySearchResults(max_results=5)
    return search.invoke(question)
```
强行使用工具将其包装为同步方法

这个问题在异步图调用中常见
