### ISSUE TITLE
LCEL not working, compared to identical invoke() call sequence

### ISSUE THREAD

**Issue by knodlagc** [langchain-ai/langchain#22459]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I have to following chain defined:
```python
chain = prompt | llm_openai | parser
chain_result = chain.invoke({"number": number, "topics": topicList})
result = chain_result[0]
```
This causes my test to fail, whereas calling the invoke() methods one is working fine:
```python
promt_result = prompt.invoke({"number": number, "topics": topicList})
llm_result = llm_openai.invoke(promt_result)
parser_result = parser.invoke(llm_result)
result = parser_result[0]
```

### Error Message and Stack Trace (if applicable)

Pydantic validation error

### Description

IMHO using a LCEL chain should work exactly like calling the invoke() methods one by one. In my case I am unable to use LCEL because it does not work.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Fri May 17 21:20:54 UTC 2024
> Python Version:  3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 14.0.1 20240411 (Red Hat 14.0.1-0)]

Package Information
-------------------
> langchain_core: 0.1.52
> langchain: 0.1.14
> langchain_community: 0.0.38
> langsmith: 0.1.67
> langchain_openai: 0.1.1
> langchain_text_splitters: 0.0.2

**Comment by eyurtsev** [comment]
@knodlagc could you provide a minimal reproducible example? (i.e., could you include the parser definition) (https://stackoverflow.com/help/minimal-reproducible-example)
