### ISSUE TITLE
langchain_community.chat_models ChatHunyuan had a bug JSON parsing error

### ISSUE THREAD

**Issue by mrhbj** [langchain-ai/langchain#22452]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import langchain
from langchain_community.chat_models import ChatHunyuan
from langchain_core.messages import HumanMessage

print(langchain.__version__)
hunyuan_app_id = "******"
hunyuan_secret_id = "********************"
hunyuan_secret_key = "*******************"
llm_tongyi = ChatHunyuan(streaming=True, hunyuan_app_id=hunyuan_app_id,
                         hunyuan_secret_id=hunyuan_secret_id,
                         hunyuan_secret_key=hunyuan_secret_key)
print(llm_tongyi.invoke("how old are you"))

### Error Message and Stack Trace (if applicable)

def _stream(
        self,
        messages: List[BaseMessage],
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> Iterator[ChatGenerationChunk]:
        res = self._chat(messages, **kwargs)

        default_chunk_class = AIMessageChunk
        for chunk in res.iter_lines():
            response = json.loads(chunk)
            if "error" in response:
                raise ValueError(f"Error from Hunyuan api response: {response}")

            for choice in response["choices"]:
                chunk = _convert_delta_to_message_chunk(
                    choice["delta"], default_chunk_class
                )
                default_chunk_class = chunk.__class__
                cg_chunk = ChatGenerationChunk(message=chunk)
                if run_manager:
                    run_manager.on_llm_new_token(chunk.content, chunk=cg_chunk)
                yield cg_chunk
![Uploading langchainb
![langchainbug2](https://github.com/langchain-ai/langchain/assets/11306049/e8703d3e-8026-4675-8a7b-f121adb80098)
ug1.png…]()

### Description

langchain_community.chat_models ChatHunyuan had a bug JSON parsing error
  it is not a json!

### System Info

langchain version 0.1.9
windows
3.9.13

**Comment by mrhbj** [comment]
![Uploading langchainbug1.png…]()

**Comment by mrhbj** [comment]
![企业微信截图_1717410490747](https://github.com/langchain-ai/langchain/assets/11306049/2a0888d6-9d86-4bd5-a00f-c8cb07d690a8)

**Comment by wxg0103** [comment]
Hello, I would like to ask how the parameters of the docking hybrid model are defined. No matter how I write it, I get an error JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Can you provide an example? It is best to include the 
model.name 
thanks

**Comment by mrhbj** [comment]
like this,here is the example,model use default model


import langchain
from langchain_community.chat_models import ChatHunyuan


print(langchain.version)
hunyuan_app_id = ""
hunyuan_secret_id = ""
hunyuan_secret_key = "**********"
llm_tongyi = ChatHunyuan(streaming=True, hunyuan_app_id=hunyuan_app_id,
hunyuan_secret_id=hunyuan_secret_id,
hunyuan_secret_key=hunyuan_secret_key)
print(llm_tongyi.invoke("hello"))





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langchain-ai/langchain"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月26日(星期五) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langchain-ai/langchain] langchain_community.chat_models ChatHunyuan had a bug JSON parsing error (Issue #22452)





 
Hello, I would like to ask how the parameters of the docking hybrid model are defined. No matter how I write it, I get an error JSONDecodeError('Expecting value: line 1 column 1 (char 0)'). Can you provide an example? It is best to include the
 model.name
 thanks
