### ISSUE TITLE
`load_chain` uses incorrect class when loading `LLMChain` with `HuggingFacePipeline`

### ISSUE THREAD

**Issue by harupy** [langchain-ai/langchain#22520]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_huggingface import HuggingFacePipeline
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain.chains.loading import load_chain

# import LLM
hf = HuggingFacePipeline.from_model_id(
    model_id="gpt2",
    task="text-generation",
    pipeline_kwargs={"max_new_tokens": 10},
)
prompt = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)

chain = LLMChain(llm=hf, prompt=prompt)
chain.save("chain.json")
chain = load_chain("chain.json")

assert isinstance(chain.llm, HuggingFacePipeline), chain.llm.__class__
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "a.py", line 21, in <module>
    assert isinstance(chain.llm, HuggingFacePipeline), chain.llm.__class__
AssertionError: <class 'langchain_community.llms.huggingface_pipeline.HuggingFacePipeline'>
```

### Description

`load_chain` uses `langchain_community.llms.huggingface_pipeline.HuggingFacePipeline` when loading a `LLMChain` with `langchain_huggingface.HuggingFacePipeline`.

### System Info

```
% pip freeze | grep langchain
langchain==0.2.0
langchain-community==0.2.2
langchain-core==0.2.0
langchain-experimental==0.0.51
langchain-huggingface==0.0.2
langchain-openai==0.0.5
langchain-text-splitters==0.2.0
langchainhub==0.1.15
```

**Comment by harupy** [comment]
Is https://github.com/langchain-ai/langchain/blob/1e748a6d406fc4ed5c3ca1218f4990e6a45530f3/libs/community/langchain_community/llms/__init__.py#L268 the function that needs a fix?

**Comment by sangam0406** [comment]
try importing the module HuggingFacePipeline by upgrading or depreciating to a stable langchain vesion.

**Comment by harupy** [comment]
@sangam0406 Thanks for the comment.

> upgrading or depreciating to a stable langchain vesion.

Which version should I try?

**Comment by sangam0406** [comment]
trying upgrading to latest version

**Comment by harupy** [comment]
@sangam0406 the same error.

**Comment by sangam0406** [comment]
Try using 0.2.2

**Comment by harupy** [comment]
@sangam0406 the same result.
