### ISSUE TITLE
The FAISS.from_documents function called many times, It'll cause memory leak. How to destroy the object?

### ISSUE THREAD

**Issue by BigGan** [langchain-ai/langchain#22602]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
def test():
    ....
    for text_items in all_list:
        doc_db = FAISS.from_documents(text_items, EMBEDDINGS_MODEL)
        doc_db.save_local(vector_database_path)
    ...
```

### Description

When call `doc_db = FAISS.from_documents(text_items, EMBEDDINGS_MODEL)`, the memory is not released.

I want to know is there a function can release the `doc_db` object.

### System Info

langchain==0.2.2
langchain-community==0.2.3
faiss-cpu==1.8.0

**Comment by efriis** [comment]
https://github.com/facebookresearch/faiss/issues/1883#issuecomment-841792529

you can try `import gc; gc.collect()`
