### ISSUE TITLE
MM-ReAct (Multimodal Reasoning and Action)

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#2262]
For GPT-4, image inputs are still in [limited alpha](https://openai.com/research/gpt-4#:~:text=image%20inputs%20are%20still%20in%20limited%20alpha). 

For GPT-3.5, it would be great to see LangChain use the MM-ReAct agent.

- Repo: [github.com/microsoft/MM-REACT](https://github.com/microsoft/MM-REACT)
- Website: [multimodal-react.github.io](https://multimodal-react.github.io/)
- Demo: [huggingface.co/spaces/microsoft-cognitive-service/mm-react](https://huggingface.co/spaces/microsoft-cognitive-service/mm-react)
- Paper Abstract: [arxiv.org/abs/2303.11381](https://arxiv.org/abs/2303.11381)
- Paper PDF: [arxiv.org/pdf/2303.11381.pdf](https://arxiv.org/pdf/2303.11381.pdf)

**Comment by aryansid** [comment]
Is it available on langchain now?

**Comment by slavakurilyak** [comment]
GPT-4(Vision) is now available which unlocks multi-modal reasoning and action.

According to OpenAI:

> We’re excited to roll out these capabilities to other groups of users, including developers, soon after.

This model is currently available using the web UI but API access is inevitable.

**Comment by alifanov** [comment]
llava (multimodal llama) is open sourced now

**Comment by slavakurilyak** [comment]
Llava is now merged into Llama.cpp [here](https://github.com/ggerganov/llama.cpp/pull/3436)

LangChain provides bindings to Llama.cpp [here](https://python.langchain.com/docs/integrations/providers/llamacpp) and [here](https://python.langchain.com/docs/integrations/llms/llamacpp)

As a result, I'm closing this issue

**Comment by rlancemartin** [comment]
We need multi-modal integration w/ l`lama-cpp-python`: 
https://github.com/abetlen/llama-cpp-python/issues/813

Worth keeping this open until that is in place.

I merged a notebook that runs LLaVA (bash script) w/o the py integration:
https://github.com/langchain-ai/langchain/pull/11582

**Comment by Se-Hun** [comment]
Now, we can use `gpt-4-vision-preview` model.

[https://platform.openai.com/docs/guides/vision](https://platform.openai.com/docs/guides/vision)

**Comment by slavakurilyak** [comment]
According to [OpenAI](https://platform.openai.com/docs/guides/vision):

> GPT-4 with vision is currently available to all [developers who have access to GPT-4](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4) via the `gpt-4-vision-preview` model and the Chat Completions API which has been updated to support image inputs

Since multimodal LLMs like GPT-4V are now generally available, I'm closing this issue
