### ISSUE TITLE
Prompt engineering for ConversationalRetrievalChain

### ISSUE THREAD

**Issue by cwfparsonson** [langchain-ai/langchain#2264]
Does anyone have an example of how to use `condense_question_prompt` and `qa_prompt` with `ConversationalRetrievalChain`? I have some information which I want to always be included in the context of a user's question (e.g. 'You are a bot whose name is Bob'), but this context information is seemingly lost when I ask a question (e.g. 'What is your name?').

If anyone has an example of how to include a pre-defined context in the prompt for `ConversationalRetrievalChain`, I would be extremely grateful!

**Comment by rohan-uiuc** [comment]
You can do this using an agent. You can add your context in prefix
`prefix = """Have a conversation with a human, answering the following questions as best you can. Your name is Bob because your knowledge base is vectorstore. You have access to the following tools:"""`

**Comment by ogmios2** [comment]
@rohan-uiuc Any chance you could point us into right direction in docs on how to implement a prefix? Thanks!

**Comment by mingjun1120** [comment]
This is something I am looking for! But I still cannot find any relevant examples from LangChain documentation.
