### ISSUE TITLE
DOC: Tutorial - Build a Chatbot - Gemini error 400 Please ensure that multiturn requests alternate between user and model

### ISSUE THREAD

**Issue by ofrivera** [langchain-ai/langchain#22651]
### URL

https://python.langchain.com/v0.2/docs/tutorials/chatbot/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

When following tutorial Build a Chatbot - Gemini in https://python.langchain.com/v0.2/docs/tutorials/chatbot/ in the section of https://python.langchain.com/v0.2/docs/tutorials/chatbot/#managing-conversation-history 

```
from langchain_core.runnables import RunnablePassthrough


def filter_messages(messages, k=10):
    return messages[-k:]


chain = (
    RunnablePassthrough.assign(messages=lambda x: filter_messages(x["messages"]))
    | prompt
    | model
)

messages = [
    HumanMessage(content="hi! I'm bob"),
    AIMessage(content="hi!"),
    HumanMessage(content="I like vanilla ice cream"),
    AIMessage(content="nice"),
    HumanMessage(content="whats 2 + 2"),
    AIMessage(content="4"),
    HumanMessage(content="thanks"),
    AIMessage(content="no problem!"),
    HumanMessage(content="having fun?"),
    AIMessage(content="yes!"),
]

response = chain.invoke(
    {
        "messages": messages + [HumanMessage(content="what's my name?")],
        "language": "English",
    }
)
response.content
```
It throws an error `Retrying langchain_google_vertexai.chat_models._completion_with_retry.<locals>._completion_with_retry_inner in 4.0 seconds as it raised InvalidArgument: 400 Please ensure that multiturn requests alternate between user and model..`

The solution here seems to be changing `def filter_messages(messages, k=10)` to `def filter_messages(messages, k=9)` the reason for this is described https://github.com/langchain-ai/langchain/issues/16288
Gemini doesn't support history starting from AIMessage changing value from 10 to 9 ensure that the first message list is always HumanMessage

**Comment by ivan-sparq** [comment]
I have resolved myself by changing filter_messages:
```
def filter_messages(messages, k=10):
    while not isinstance(messages[-k], HumanMessage):
        k -=1
    return messages[-k:]
```
to always start with a HumanMessage
