### ISSUE TITLE
`AzureAIDocumentIntelligenceLoader` throws 404 Resource not found error

### ISSUE THREAD

**Issue by baniasbaabe** [langchain-ai/langchain#22679]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import AzureAIDocumentIntelligenceLoader
import os

endpoint = "<endpoint>"
key = "<key>"
mode= "markdown"

path = os.path.join('path', 'to', 'pdf')
loader = AzureAIDocumentIntelligenceLoader(
file_path="path_to_local_pdf.pdf", api_endpoint=endpoint, api_key=key, api_model="prebuilt-layout", mode = mode
)

documents = loader.load()
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "/Users/Code/tools-chatbot-backend/dataproduct/test_langchain.py", line 13, in <module>
    documents = loader.load()
                ^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 29, in load
    return list(self.lazy_load())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/doc_intelligence.py", line 96, in lazy_load
    yield from self.parser.parse(blob)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 125, in parse
    return list(self.lazy_parse(blob))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/doc_intelligence.py", line 80, in lazy_parse
    poller = self.client.begin_analyze_document(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 3627, in begin_analyze_document
    raw_result = self._analyze_document_initial(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 516, in _analyze_document_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/baniasbaabe/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/core/exceptions.py", line 161, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (404) Resource not found
Code: 404
Message: Resource not found
```

### Description

I am trying to run the `AzureAIDocumentIntelligenceLoader` but it always throws an error that the resource to the PDF could not be found. When I run the [azure-ai-formrecognizer](https://pypi.org/project/azure-ai-formrecognizer/) manually, it works.

### System Info

```
langchain==0.2.0
Python 3.11
MacOS 14
```

**Comment by coltraneyan** [comment]
> ### Checked other resources
> * [x]  I added a very descriptive title to this issue.
> * [x]  I searched the LangChain documentation with the integrated search.
> * [x]  I used the GitHub search to find a similar question and didn't find it.
> * [x]  I am sure that this is a bug in LangChain rather than my code.
> * [x]  The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
> 
> ### Example Code
> ```python
> from langchain_community.document_loaders import AzureAIDocumentIntelligenceLoader
> import os
> 
> endpoint = "<endpoint>"
> key = "<key>"
> mode= "markdown"
> 
> path = os.path.join('path', 'to', 'pdf')
> loader = AzureAIDocumentIntelligenceLoader(
> file_path="path_to_local_pdf.pdf", api_endpoint=endpoint, api_key=key, api_model="prebuilt-layout", mode = mode
> )
> 
> documents = loader.load()
> ```
> 
> ### Error Message and Stack Trace (if applicable)
> ```
> Traceback (most recent call last):
>   File "/Users/Code/tools-chatbot-backend/dataproduct/test_langchain.py", line 13, in <module>
>     documents = loader.load()
>                 ^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 29, in load
>     return list(self.lazy_load())
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/doc_intelligence.py", line 96, in lazy_load
>     yield from self.parser.parse(blob)
>                ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 125, in parse
>     return list(self.lazy_parse(blob))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/langchain_community/document_loaders/parsers/doc_intelligence.py", line 80, in lazy_parse
>     poller = self.client.begin_analyze_document(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 3627, in begin_analyze_document
>     raw_result = self._analyze_document_initial(  # type: ignore
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/ai/documentintelligence/_operations/_operations.py", line 516, in _analyze_document_initial
>     map_error(status_code=response.status_code, response=response, error_map=error_map)
>   File "/Users/baniasbaabe/Code/tools-chatbot-backend/dataproduct/.venv/lib/python3.11/site-packages/azure/core/exceptions.py", line 161, in map_error
>     raise error
> azure.core.exceptions.ResourceNotFoundError: (404) Resource not found
> Code: 404
> Message: Resource not found
> ```
> 
> ### Description
> I am trying to run the `AzureAIDocumentIntelligenceLoader` but it always throws an error that the resource to the PDF could not be found. When I run the [azure-ai-formrecognizer](https://pypi.org/project/azure-ai-formrecognizer/) manually, it works.
> 
> ### System Info
> ```
> langchain==0.2.0
> Python 3.11
> MacOS 14
> ```

Have you satisfied this ? From the langchain docs. It worked for me after I deployed again to one of these regions. `Prerequisite: An Azure AI Document Intelligence resource in one of the 3 preview regions: East US, West US2, West Europe`

**Comment by ambodiam** [comment]
+1 for this.
