### ISSUE TITLE
AttributeError: 'AzureOpenAI' object has no attribute 'bind_tools'

### ISSUE THREAD

**Issue by vladfeigin** [langchain-ai/langchain#22670]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_openai import AzureOpenAI
.....
model = AzureOpenAI(deployment_name=os.getenv("OPENAI_DEPLOYMENT_ENDPOINT"), temperature=0.3, openai_api_key=os.getenv("OPENAI_API_KEY"))

model.bind_tools([tool])

### Error Message and Stack Trace (if applicable)

AttributeError: 'AzureOpenAI' object has no attribute 'bind_tools'

### Description

I create AzureOpenAI instance in langchain and when trying to bind tools getting the error.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
> Python Version:  3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.2.5
> langchain: 0.2.3
> langchain_community: 0.2.4
> langsmith: 0.1.75
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.1
> langgraph: 0.0.64
> langserve: 0.2.1

**Comment by ahmadhatahet** [comment]
Try using ´from langchain_openai import AzureChatOpenAI´ instead of ´AzureOpenAI´
