### ISSUE TITLE
DOC: NameError due to Incorrect Variable Name in PDF QA Tutorial Documentation

### ISSUE THREAD

**Issue by pChitral** [langchain-ai/langchain#22689]
### URL

https://python.langchain.com/v0.2/docs/tutorials/pdf_qa/#question-answering-with-rag

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

**URL**: [PDF QA Tutorial](https://python.langchain.com/v0.2/docs/tutorials/pdf_qa/#question-answering-with-rag)

**Checklist**:
- [x] I added a very descriptive title to this issue.
- [x] I included a link to the documentation page I am referring to.

**Issue with current documentation**:
There is a variable name error in the PDF QA Tutorial on the LangChain documentation. The code snippet incorrectly uses `llm` instead of `model`, which causes a `NameError`.

**Error Message**:
```plaintext
NameError: name 'llm' is not defined
```

**Correction**:
The variable `llm` should be replaced with `model` in the code snippet for it to work correctly. Here is the corrected portion of the code:

```python
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

system_prompt = (
    "You are an assistant for question-answering tasks. "
    "Use the following pieces of retrieved context to answer "
    "the question. If you don't know the answer, say that you "
    "don't know. Use three sentences maximum and keep the "
    "answer concise."
    "\n\n"
    "{context}"
)

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        ("human", "{input}"),
    ]
)

question_answer_chain = create_stuff_documents_chain(model, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

results = rag_chain.invoke({"input": "What was Nike's revenue in 2023?"})

results
```

Please make this update to prevent confusion and errors for users following the tutorial.

**Comment by baskargopinath** [comment]
this has been fixed from what i can see

**Comment by mirnawong1** [comment]
I've opened a small pr to fix this up: https://github.com/langchain-ai/langchain/pull/23280
