### ISSUE TITLE
Fix stop list of string in VLLM generate

### ISSUE THREAD

**Issue by NikitaKlichko** [langchain-ai/langchain#22717]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
def _generate(
    self,
    prompts: List[str],
    stop: Optional[List[str]] = None,
    run_manager: Optional[CallbackManagerForLLMRun] = None,
    **kwargs: Any,
) -> LLMResult:
    """Run the LLM on the given prompt and input."""

    from vllm import SamplingParams
    # build sampling parameters
    params = {**self._default_params, **kwargs, "stop": stop}
    sampling_params = SamplingParams(**params)
    # call the model
    outputs = self.client.generate(prompts, sampling_params)

    generations = []
    for output in outputs:
        text = output.outputs[0].text
        generations.append([Generation(text=text)])

    return LLMResult(generations=generations)
```

### Description

Problem #15921 still not fixed. Pls fix it. Maybe init 'stop'  by default from SamplingParams.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023
> Python Version:  3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]

Package Information
-------------------
> langchain_core: 0.2.3
> langchain: 0.2.1
> langchain_community: 0.2.1
> langsmith: 0.1.69
> langchain_chroma: 0.1.1
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.17

**Comment by keenborder786** [comment]
okay I am checking it

**Comment by keenborder786** [comment]
Can you please share your code and prompt as well and the output which shows how the stop word is not working?

**Comment by keenborder786** [comment]
Because I double checked the code, everything seems to be functional.

**Comment by NikitaKlichko** [comment]
> Because I double checked the code, everything seems to be functional.
When specifying stops in the config and calling the list of stop tokens  does not work, because in this case the stop list will be None in generate params (see code above in description issue)
```python
generation_config = {
    'temperature':0.01,
    'top_p':0.9,
    'top_k':30,
    'max_tokens':1024,
    'repetition_penalty':1.1,
    'stop': ['.']
    }
    llm = VLLM(model=llm_name, dtype='float16', **generation_config)
    llm.invoke('question')
```
if we do that 
```python 
llm.invoke('question', stop=['...'])
```
it works.
For the same reason, if we run, for example, rag_chain stop list don't work
```python
rag_chain = (
    {"context": retriever, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)
```

**Comment by keenborder786** [comment]
No it won't be None because when you pass `stop` to the instance of `VLLM` i.e during the initialization,  the `self.stop` is passed to the VLLM client by using the `_default_params` [attribute](https://github.com/keenborder786/langchain/blob/28e956735c918450109b03416924cac359ce457a/libs/community/langchain_community/llms/vllm.py#L100). This is passed [here](https://github.com/keenborder786/langchain/blob/28e956735c918450109b03416924cac359ce457a/libs/community/langchain_community/llms/vllm.py#L129), so it cannot be None regardless of whether you pass the `stop` during initialization or during invoking.

**Comment by NikitaKlichko** [comment]
> No it won't be None because when you pass `stop` to the instance of `VLLM` i.e during the initialization, the `self.stop` is passed to the VLLM client by using the `_default_params` [attribute](https://github.com/keenborder786/langchain/blob/28e956735c918450109b03416924cac359ce457a/libs/community/langchain_community/llms/vllm.py#L100). This is passed [here](https://github.com/keenborder786/langchain/blob/28e956735c918450109b03416924cac359ce457a/libs/community/langchain_community/llms/vllm.py#L129), so it cannot be None regardless of whether you pass the `stop` during initialization or during invoking.

if do like this stop token won't work in current _generate implementation
```python
generation_config = {
    'temperature':0.01,
    'top_p':0.9,
    'top_k':30,
    'max_tokens':1024,
    'repetition_penalty':1.1,
    'stop': ['.']
    }
    
    llm = VLLM(model=llm_name, dtype='float16', **generation_config)
    
    SYSTEM = "You are an astronomer scientist. Explain step by step"
question = "How does the Moon differ from Earth?"
template = [{"role": "system", "content": f"{SYSTEM}"}, 
            {"role": "user", "content": "Вопрос: {}".format(question)}]

llm_tokenizer = AutoTokenizer.from_pretrained(llm_name)
prompt = llm_tokenizer.apply_chat_template(template, tokenize=False, add_generation_prompt=True)

ANSWER:
The Moon and Earth are two celestial bodies that are closely related yet distinct in many ways. Here's a step-by-step explanation of the main differences between them:

1. **Origin**: The Moon is thought to have formed about 4.5 billion years ago, shortly after the formation of the Earth. One theory is that the Moon was created when a massive object collided with the Earth, causing debris to be thrown into orbit and eventually coalesce into the Moon.

2. **Size and Mass**: The Moon is significantly smaller than Earth. It has a diameter of about 3,474 kilometers (2,159 miles), which is about one-quarter of Earth's diameter. The Moon's mass is about one-eighteenth of Earth's mass.
 and so on.
 ```
 
 Check #15921
 
 """In the line params = {**self._default_params, **kwargs, "stop": stop}, the "stop" parameter from the "_default_params" method is overwritten by the local "stop" parameter. If no "stop" parameter is passed to the "_generate" method, it defaults to None, effectively ignoring the "stop" parameter set in the VLLM class"""

**Comment by CREESTL** [comment]
@keenborder786 

I agree with @NikitaKlichko.

I faced the same issue:
1. I've passed the `stop` parameter when initializing the VLLM instance like this:
```
llm = VLLM(
    model=MODEL_NAME, 
    max_new_tokens=NUM_OUTPUT_TOKENS,
    temperature=TEMPERATURE,
    top_p=TOP_P,
    top_k=TOP_K,
    dtype="float16",
    stop=["[END]"],
    tensor_parallel_size=4, 
    trust_remote_code=True, 
    vllm_kwargs={
        "gpu_memory_utilization": 0.90, 
        "seed": 42,
        "device": "cuda",
        "max_model_len": CONTEXT_SIZE,
    },
)
 ```
 
 So I want the model to stop generating after reaching the "[END]" sequence. 
 Next, I've printed the details about the llm like so:
 ```
for el in llm:
    print(el)
```
And it said: `..... ('stop', ['[END]']) ....`. 
So the "stop" attribute of the class is actually set correctly.

Next, I've tried 2 different ways to invoke the llm:

The first one:
```
SYSTEM = "Always surround your answer with [START] and [END] tags."
question = "Who is Notch?"
template = [{"role": "system", "content": f"{SYSTEM}"}, 
            {"role": "user", "content": "Question: {}".format(question)}]

prompt = self.tokenizer.apply_chat_template(template, tokenize=False, add_generation_prompt=False)
res = self.llm.invoke(prompt) # <--- This does not stop generation on [END]
self.logger.info(f"\n\n\nRESULT IS: {res}")
```
       
The second one:
```
SYSTEM = "Always surround your answer with [START] and [END] tags."
question = "Who is Notch?"
template = [{"role": "system", "content": f"{SYSTEM}"}, 
            {"role": "user", "content": "Question: {}".format(question)}]

prompt = self.tokenizer.apply_chat_template(template, tokenize=False, add_generation_prompt=False)
res = self.llm.invoke(prompt, stop=["[END]"]) # <--- This works. The LLM stops at [END] and does not include it in the output.
self.logger.info(f"\n\n\nRESULT IS: {res}")
```

As you can see, the only difference is that I passed the `stop=["[END]"]` explicitly the second time.

Result:
- In the first try, the LLM output **contained** the "[END]" tag
- In the second try, the LLM output **DID NOT contain** the "[END]" tag.

I'm pretty sure the reason for this is that in [this line](https://github.com/langchain-ai/langchain/blob/e40a2b8bbfe1c08947e1f6deab2274283c59bd4f/libs/community/langchain_community/llms/vllm.py#L130) the `stop` parameter from `_default_params` is overwritten to `None` if no `stop` parameter was passed to the `_generate` method.
