### ISSUE TITLE
File Not Closed in OutlookMessageLoader of langchain_community Library

### ISSUE THREAD

**Issue by MatanelAbayof** [langchain-ai/langchain#22729]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import OutlookMessageLoader
import os

file_path = "example.msg"

loader = OutlookMessageLoader(file_path)
documents = loader.load()
print(documents)
try:
    os.remove(file_path)
except Exception as e:
    print(e)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    os.remove(file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'example.msg'

### Description

**Describe the bug**
It seems that the `OutlookMessageLoader` does not close the file after extracting the text from the `.msg` file.

**To Reproduce**
1. Use the following example code:

```python
from langchain_community.document_loaders import OutlookMessageLoader
import os

file_path = "example.msg"

loader = OutlookMessageLoader(file_path)
documents = loader.load()
print(documents)
try:
    os.remove(file_path)
except Exception as e:
    print(e)
```

2. Run the code and observe the error.

**Expected behavior**
The file should be closed after processing, allowing it to be deleted without errors.

**Error**
```
[WinError 32] The process cannot access the file because it is being used by another process: 'example.msg'
```

**Additional context**
I looked into the `email.py` file of `langchain_community.document_loaders` and found the following code in the `lazy_load` function:

```python
import extract_msg

msg = extract_msg.Message(self.file_path)
yield Document(
    page_content=msg.body,
    metadata={
        "source": self.file_path,
        "subject": msg.subject,
        "sender": msg.sender,
        "date": msg.date,
    },
)
```

It seems like the file is not being closed properly. Adding `msg.close()` should resolve the issue.

### System Info

**Langchain libraries**:
langchain==0.2.2
langchain-community==0.2.3
langchain-core==0.2.4
langchain-openai==0.1.8
langchain-text-splitters==0.2.1

**Platform**: windows

**Python**: 3.12.3

**Comment by keenborder786** [comment]
@MatanelAbayof please close this issue as this has been fixed.
