### ISSUE TITLE
DOC: inconsistency with similarity_search_with_score()

### ISSUE THREAD

**Issue by pprados** [langchain-ai/langchain#22732]
### URL

https://api.python.langchain.com/en/latest/vectorstores/langchain_chroma.vectorstores.Chroma.html#langchain_chroma.vectorstores.Chroma.similarity_search_with_score

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The documentation for lanchain_core.vectorstore._similarity_search_with_relevance_scores()

> states: 0 is dissimilar, 1 is most similar.

The documentation for chroma.similarity_search_with_score() states:

> Lower score represents more similarity.

What is the correct interpretation?

**Comment by eyurtsev** [comment]
One is distance the other is similarity (which goes in the opposite direction)

**Comment by eyurtsev** [comment]
I don't know if the implementations are consistent in terms of which score should be used (even for the same method)
