### ISSUE TITLE
"Elevenlabs has no attribute "generate (only older versions of elevenlabs work with this wrapper)

### ISSUE THREAD

**Issue by majumba** [langchain-ai/langchain#22736]
### URL

https://python.langchain.com/v0.2/docs/integrations/tools/eleven_labs_tts/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

"Elevenlabs has no attribute "generate

This doesnt seem to work with latest elevenlabs package

**Comment by keenborder786** [comment]
Can you please share your code and also your logs as well. Plus some more info about your langchain versions will be helpful as well.

**Comment by Nachoeigu** [comment]
Hi @keenborder786 I have the same issue:
```

from langchain_community.tools import ElevenLabsText2SpeechTool

text_to_speak = "Hello world! I am the real slim shady"

tts = ElevenLabsText2SpeechTool()


speech_file = tts.run(text_to_speak)
tts.play(speech_file)

```


<img width="384" alt="image" src="https://github.com/user-attachments/assets/3b1a6715-0c1c-45ec-8acc-d461b32635a8">
<img width="328" alt="image" src="https://github.com/user-attachments/assets/eb1b8f4c-9139-4eff-827b-c5463ce93355">

**Comment by Nachoeigu** [comment]
> Hi @keenborder786 I have the same issue. Literally, I paste the code in the [docs](https://python.langchain.com/v0.2/docs/integrations/tools/eleven_labs_tts/)
> 
> ```
> 
> from langchain_community.tools import ElevenLabsText2SpeechTool
> 
> text_to_speak = "Hello world! I am the real slim shady"
> 
> tts = ElevenLabsText2SpeechTool()
> 
> 
> speech_file = tts.run(text_to_speak)
> tts.play(speech_file)
> ```
> 
> <img alt="image" width="384" src="https://private-user-images.githubusercontent.com/82097362/357931937-3b1a6715-0c1c-45ec-8acc-d461b32635a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODAxNzUsIm5iZiI6MTcyNDc3OTg3NSwicGF0aCI6Ii84MjA5NzM2Mi8zNTc5MzE5MzctM2IxYTY3MTUtMGMxYy00NWVjLThhY2MtZDQ2MWIzMjYzNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE3MzExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4OTgzOTYxMzcwYThmYTU3N2E4YWRhNjQ3MTdhYzU4YmNhNjVhY2Y5ZmNmYzk5N2FjZDcwMjkxOTdjNmU1YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RD297dF2ay3vmH081wKlIGrYtVrImi__8q6NzvU1WBU"> <img alt="image" width="328" src="https://private-user-images.githubusercontent.com/82097362/357932002-eb1b8f4c-9139-4eff-827b-c5463ce93355.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODAxNzUsIm5iZiI6MTcyNDc3OTg3NSwicGF0aCI6Ii84MjA5NzM2Mi8zNTc5MzIwMDItZWIxYjhmNGMtOTEzOS00ZWZmLTgyN2ItYzU0NjNjZTkzMzU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE3MzExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NjRmNjY4YTc4MTJjMjNjNzhhYWM1ZGZiZmY2MTc1ZWRjNmY4OWVlZDFkMTRiM2U5MDFmYzhmY2VjMWNmZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3fdAMo4Q76ajyBI-phSWr0vX_oxdj1cgIreJvMbBFko">

Could someone see this?
