### ISSUE TITLE
MarkdownHeaderTextSplitter for header such like "**New Header 5**"

### ISSUE THREAD

**Issue by km5ar** [langchain-ai/langchain#22738]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter


# Updated markdown_document with a new header 5 using **
markdown_document = """
# Intro

## History

Markdown[9] is a lightweight markup language for creating formatted text using a plain-text editor. John Gruber created Markdown in 2004 as a markup language that is appealing to human readers in its source code form.[9]

Markdown is widely used in blogging, instant messaging, online forums, collaborative software, documentation pages, and readme files.

## Rise and divergence

As Markdown popularity grew rapidly, many Markdown implementations appeared, driven mostly by the need for additional features such as tables, footnotes, definition lists,[note 1] and Markdown inside HTML blocks.

#### Standardization

From 2012, a group of people, including Jeff Atwood and John MacFarlane, launched what Atwood characterized as a standardisation effort.

## Implementations

Implementations of Markdown are available for over a dozen programming languages.

**New Header 5**

This is the content for the new header 5.
"""

# Headers to split on, including custom header 5 with **
headers_to_split_on = [
    ('\*\*.*?\*\*', "Header 5")
]

# Create the MarkdownHeaderTextSplitter
markdown_splitter = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on, strip_headers=False
)

# Split text based on headers
md_header_splits = markdown_splitter.split_text(markdown_document)

# Create the RecursiveCharacterTextSplitter
chunk_size = 250
chunk_overlap = 30
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=chunk_size, chunk_overlap=chunk_overlap
)

# Split documents
splits = text_splitter.split_documents(md_header_splits)
print(splits)

```

### Error Message and Stack Trace (if applicable)

<img width="1157" alt="image" src="https://github.com/langchain-ai/langchain/assets/54015474/70e95ca0-d9f8-41ef-b35a-0f851f9edbcb">

### Description

1. I try to use MarkdownHeaderTextSplitter for split the text on "**New Header 5**"
2. I was able to use r'\*\*.*?\*\*' to do the work with package re
3. but I failed it with langchain and I wasn't able to find any example regarding similar Header in langchain's documentation

### System Info

langchain-core==0.2.3
langchain-text-splitters==0.2.0

**Comment by km5ar** [comment]
I also tried to just use "\*\*" and "**" but did not work

**Comment by coolbeevip** [comment]
The current judgment logic is that there is no text in the title or there is a space after the title. headers_to_split_on 
 Matches the beginning character

```
# Foo

foo()

** Bar

bar()
```

headers_to_split_on = [("**", "Header 1")]

doc1

```
# Foo

foo()
```

doc2

```
** Bar

bar()
```

**Comment by skocan** [comment]
hello @km5ar, did you find any solution ?

**Comment by km5ar** [comment]
@skocan no......better just using split()

**Comment by ccyen8358** [comment]
In source code it counts the number of '#' characters to determine the current header level.
So I guess you can only use conventional headers such as '#', '##', '###', '####' , etc., and you can't use custom header like "\*\*New Header 5\*\*".
Bummer, the tutorial makes it look like you can use custom header but you actually couldn't.
