### ISSUE TITLE
PydanticOutputParser Doesn't Parse Dates in Unions

### ISSUE THREAD

**Issue by ElliotAtKlaviyo** [langchain-ai/langchain#22740]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Here's a Pydantic model with a date in a union-typed attribute.

```python
from datetime import date
from pydantic import BaseModel

class Example(BaseModel):
    attribute: date | str
```

Given a JSON string that contains a date, Pydantic discriminates the type and returns a `datetime.date` object.

```python
json_string = '{"attribute": "2024-01-01"}'
Example.model_validate_json(json_string)

# returns Example(attribute=datetime.date(2024, 1, 1))
```

However, PydanticOutputParser unexpectedly returns a string on the same JSON.

```python
from langchain.output_parsers import PydanticOutputParser
parser = PydanticOutputParser(pydantic_object=Example)
parser.parse(json_string)

# returns Example(attribute="2024-01-01")
```

### Description

`PydanticOutputParser` isn't converting dates in union types (e.g. `date | str`) to `datetime.date` objects. The parser should be able to discriminate these types by working left-to-right. See Pydantic's approach in https://docs.pydantic.dev/latest/concepts/unions/.

### System Info

I'm on macOS with Python 3.10. I can reproduce this issue with both LangChain `0.1` and `0.2`.

**Comment by eyurtsev** [comment]
Do you reproduce also with pydantic.v1 ?

**Comment by ElliotAtKlaviyo** [comment]
> Are you able to reproduce also with pydantic.v1 ?

No! Looks like this issue does not appear with v1 models:

```python
from datetime import date
from langchain.output_parsers import PydanticOutputParser
from pydantic.v1 import BaseModel

class Example(BaseModel):
    attribute: date | str

parser = PydanticOutputParser(pydantic_object=Example)
parser.parse('{"attribute": "2024-01-01"}')
# returns Example(attribute=datetime.date(2024, 1, 1))
```

**Comment by eyurtsev** [comment]
I suspect you'll need to be more explicit about type coercion for this to work

```python
from pydantic import __version__, BaseModel
from typing import Union
from datetime import date

import json

class A(BaseModel):
    foo: Union[int, date, str]

json_str = '{"foo": "2024-01-01"}'
print(A.model_validate_json(json_str))
obj = json.loads(json_str)
print(A.model_validate(obj))
```

**Comment by eyurtsev** [comment]
OK you can do this: 

```python

from pydantic import __version__, BaseModel, Field
from typing import Union
from datetime import date

class A(BaseModel):
    foo: Union[int, date, str] = Field(union_mode='left_to_right')

print(A.model_validate_json('{"foo": "2024-01-01"}'))
print(A.model_validate({'foo': '2024-01-01'}))
```
