### ISSUE TITLE
_InactiveRpcError of RPC 

### ISSUE THREAD

**Issue by chamal-afk** [langchain-ai/langchain#22762]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

result=multimodal_search(query)

### Error Message and Stack Trace (if applicable)

/usr/local/lib/python3.10/dist-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
   1004             return state.response
   1005     else:
-> 1006         raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
   1007 
   1008 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for :10000: unparseable host:port"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-06-10T19:02:57.93240468+00:00", grpc_status:14, grpc_message:"DNS resolution failed for :10000: unparseable host:port"}"

### Description

I'm to call a vector_search function that I wrote to retrieve embeddings and give response to the query, but I'm facing this error message.

### System Info

python

**Comment by efriis** [comment]
Howdy! There isn't enough information in this issue to help debug or even tell if this is relevant to langchain. If you want to re-submit, please submit a complete codeblock that I could run on its own and reproduce the error :)
