### ISSUE TITLE
 No module named 'langchain_community.document_loaders'; 'langchain_community' is not a package

### ISSUE THREAD

**Issue by zyc1128** [langchain-ai/langchain#22763]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.document_loaders import pdf

### Error Message and Stack Trace (if applicable)

ModuleNotFoundError: No module named 'langchain_community.document_loaders'; 'langchain_community' is not a package

### Description

我的python环境里确实有langchain_community这个包，其他包都没问题就这个有问题

### System Info

windows ,python 3.9.8

**Comment by martinohanlon** [comment]
Have you installed the `langchain_community` package?

https://pypi.org/project/langchain-community/

```
pip install langchain_community
```

**Comment by Musbell** [comment]
I am still encountering the same issue despite having installed `langchain_community`.
