### ISSUE TITLE
DocumentDBVectorSearch and metadata filtering

### ISSUE THREAD

**Issue by andreadisimone** [langchain-ai/langchain#22770]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

not applicable

### Error Message and Stack Trace (if applicable)

not applicable

### Description

The DocumentDBVectorSearch docs mention it supports metadata filtering:

https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.documentdb.DocumentDBVectorSearch.html#langchain_community.vectorstores.documentdb.DocumentDBVectorSearch.as_retriever

However, unless I misunderstand the code, I really don't think it does.

I see that VectorStoreRetriever._get_relevant_documents passes search_kwargs to the similarity search of the underlying vector store.
And nothing in the code of DocumentDBVectorSearch is using search_kwargs at all.

In my project we need to review relevant parts of opensource softwares to make sure they really meet the requirements. So if this is not a bug, and the feature is indeed implemented somewhere else, could anybody please clarify how metadata filtering in DocumentDBVectorSearch is implemented?

### System Info

not applicable

**Comment by keenborder786** [comment]
Nope you are wrong, vectorstore retriever  unzips the `search_kwargs` [here](https://github.com/keenborder786/langchain/blob/27b9ea14a51398e8ff2a4972026178778f85134b/libs/core/langchain_core/vectorstores.py#L797) therefore using the passed parameter such as `k` and `ef_search` [here](https://github.com/keenborder786/langchain/blob/27b9ea14a51398e8ff2a4972026178778f85134b/libs/community/langchain_community/vectorstores/documentdb.py#L353). The `filter` parameter that you are suggesting is not supported in current implementation of `DocumentDB`. Their is no bug whatsoever.

**Comment by andreadisimone** [comment]
@keenborder786 thanks for the quick reply.
so you are saying the docs are wrong when they say DocumentDBVectorSearch supports filtering?

**Comment by andreadisimone** [comment]
re: DocumentDB not supporting the "filter" parameter, that seems to me like an internal (LangChain's) implementation detail.

In the aggregation pipeline that DocumentDBVectorSearch builds [here](https://github.com/keenborder786/langchain/blob/27b9ea14a51398e8ff2a4972026178778f85134b/libs/community/langchain_community/vectorstores/documentdb.py#L326), LangChain should be prepending a $match step to the vectorsearch. Or, update the documentation to mention that it does not support filtering (for no particular reason, though). 

Unless, again, I am misunderstanding the code, in which case I apologize for the noise :) and ask again to kindly be pointed to where the filtering is implemented, so I can document it for our internal processes.

**Comment by keenborder786** [comment]
@andreadisimone done, I have added the filter support.

**Comment by keenborder786** [comment]
@andreadisimone  please close this issue

**Comment by andreadisimone** [comment]
thanks for the quick implementation @keenborder786 !

I am no mongo expert myself, but I tested in my setup a code similar to yours and it fails. I think the pipeline should look like 

`[{"$match": filter}, {"$search": search_config}]
`
instead of what you implemented:
`[{"$match": filter, "$search": search_config}]`

As it is now, it fails with
`OperationFailure: A pipeline stage specification object must contain exactly one field.`

But as I said I am no expert and I may have done something else wrong. if you are sure your new code runs I am happy to close this.

**Comment by keenborder786** [comment]
You are right, I am creating a Patch fixed PR.

**Comment by andreadisimone** [comment]
thanks @keenborder786 looks good, closing.
