### ISSUE TITLE
Kindly add support for  databricks-sql-connector (databricks library) via sqlalchemy in langchain

### ISSUE THREAD

**Issue by kf-himpunetha** [langchain-ai/langchain#2277]
I am getting some issues while trying to connect from langchain to databricks via sqlalchemy.
It works fine when I connect directly via sqlalchemy.

I think the issue is  in the below lines
https://github.com/hwchase17/langchain/blob/09f94642543b23d7c9db81aa15ef54a1b6e13840/langchain/sql_database.py#L32-L33

the variable self._include_tables in line 33 is is set with values after calling get_table_names function (in line 32) which in turn uses self._include_tables and hence it will have None value at that time which causes some errors for databricks connection.

![image](https://user-images.githubusercontent.com/84923079/229308813-5adfb74d-8961-4369-b609-2f33802b898f.png)

There are few more such issues while connecting to databricks using langchain and  databricks-sql-connector library. It works fine with just sqlalchemy and  databricks-sql-connector. 
Could you add support for databricks?

**Comment by kamtingtsoi** [comment]
I encountered the same issue but it was actually a problem of how databricks-sql-connector handles parameters in the URL. In order to get it to work you could construct the URL as below:
```
from sqlalchemy.engine import URL


host = "xxx.cloud.databricks.com"
port = 443
path = "xxx"
token = "xxx"
catalog = "xxx"  # Databrick's default is hive_metastore
database = "xxx"

url = URL.create(
    "databricks",
    username="token",
    password=token,
    host=host,
    port=port,
    database=database,
    query={
        "http_path": path,
        "catalog": catalog,
        "schema": database,
    }
)
```
