### ISSUE TITLE
with_structured_output format depends on whether we're using pydantic proper or pydantic.v1 namespace

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#22782]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

```python

from pydantic.v1 import BaseModel
from pydantic import BaseModel as BaseModelV2

class Answer(BaseModel):
    answer: str


class Answer2(BaseModelV2):
    """"The answer."""
    answer: str


from langchain_openai import ChatOpenAI

model = ChatOpenAI()

model.with_structured_output(Answer).invoke('the answer is foo') # <-- Returns pydantic object

model.with_structured_output(Answer2).invoke('the answer is foo') # <--- Returns dict
```

**Comment by eyurtsev** [comment]
There's a bug in the chat model when checking whether a pydantic model  (`from pydantic import BaseModel`) ends up being classified as not a pydantic model. 

But if we fix that logic, we get stuck here: 

https://github.com/langchain-ai/langchain/blob/232908a46d6371ff3d65381966ffe4831545cb25/libs/core/langchain_core/output_parsers/openai_tools.py#L177-L177

The code 

```
class PydanticToolsParser(JsonOutputToolsParser):
    """Parse tools from OpenAI response."""

    tools: List[Type[BaseModel]]
```


Which will not work since JsonOutputToolsParser inherits from BaseModel as well

**Comment by hinthornw** [comment]
It also emits the wrong schema  in general for nested objects
