### ISSUE TITLE
Spec out API for all required vs. all possible input variables

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#22832]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Context: 

* MessagePlaceholder can be optional or non optional 
* Current LangChain API for input variables doesn't distinguish between possible input variables vs. required input variables

See: https://github.com/langchain-ai/langchain/pull/21640

## Requirements

* get_input_schema() should reflect optional and required inputs
* Expose another property to either fetch all required or all possible input variables (with explanation about why this is the correct approach) alternatively delegate to `get_input_schema()`, and make semantics of input_variables clear (e.g., all possible values)

```python
from langchain import LLMChain
prompt = ChatPromptTemplate.from_messages([MessagesPlaceholder("history", optional=True), ('user', '${input}')])
model = ChatOpenAI()
chain = LLMChain(llm=model, prompt=prompt)
chain({'input': 'what is your name'})
prompt.get_input_schema()
```

**Comment by keenborder786** [comment]
@eyurtsev  since I was already working on this issue in #21640, I can tackle this issue.

**Comment by eyurtsev** [comment]
Merged! Closing this issue!
