### ISSUE TITLE
RedisChatMessageHistory encountering issues in Redis standalone mode on Windows.

### ISSUE THREAD

**Issue by arian360** [langchain-ai/langchain#22845]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

  from langchain_community.chat_message_histories.redis import RedisChatMessageHistory

try:
            message_history = RedisChatMessageHistory(
                session_id="12345678", url="redis://localhost:6379", ttl=600
            )
        except Exception as e:
            abort(500, f'Error occurred: {str(e)}')
        retriever = pdf_docsearch.as_retriever(search_type="similarity", search_kwargs={"k": 4})
        memory = ConversationBufferWindowMemory(memory_key="chat_history", chat_memory=message_history,
                                                input_key='question', output_key='answer',
                                                return_messages=True, k=20)

### Error Message and Stack Trace (if applicable)

Error occurred: 'cluster_enabled'"

### Description

I'm working on implementing long-term memory for a chatbot using Langchain and a Redis database. However, I'm facing issues with the Redis client connection, particularly with the `redis.py` file where `cluster_info` seems to be empty in standalone mode

### System Info

Python 3.10
langchain-core 0.1.43
langchain-community 0.0.32

**Comment by sebatinoco** [comment]
any updates on this? I am facing the same issue
