### ISSUE TITLE
ReAct vs MRKL

### ISSUE THREAD

**Issue by clayoneil** [langchain-ai/langchain#2284]
Sorry if this is a dumb question:

Why is the ZeroShotAgent called "zero-shot-react-description" instead of "zero-shot-mrkl-description" or something like that? It is implemented to follow the MRKL design, not the reAct design. I am misunderstanding something?

Here is the code:

```
AGENT_TO_CLASS = {
    "zero-shot-react-description": ZeroShotAgent,
    "react-docstore": ReActDocstoreAgent,
    "self-ask-with-search": SelfAskWithSearchAgent,
    "conversational-react-description": ConversationalAgent,
    "chat-zero-shot-react-description": ChatAgent,
    "chat-conversational-react-description": ConversationalChatAgent,
}
```

permalink: https://github.com/hwchase17/langchain/blob/acfda4d1d8b3cd98de381ff58ba7fd6b91c6c204/langchain/agents/loading.py#L21

**Comment by yousefamar** [comment]
I'm not an expert on this, but isn't ReAct a kind of MRKL system that is able to reason? ZeroShotAgent looks quite ReAct-y to me, with thoughts, observations, etc. Is there something there that indicates otherwise?

**Comment by zuojie** [comment]
check this out:
**Agent Types
Agents use an LLM to determine which actions to take and in what order. An action can either be using a tool and observing its output, or returning a response to the user. Here are the agents available in LangChain.

zero-shot-react-description
This agent uses the ReAct framework to determine which tool to use based solely on the tool’s description. Any number of tools can be provided. This agent requires that a description is provided for each tool.

react-docstore
This agent uses the ReAct framework to interact with a docstore. Two tools must be provided: a Search tool and a Lookup tool (they must be named exactly as so). The Search tool should search for a document, while the Lookup tool should lookup a term in the most recently found document. This agent is equivalent to the original [ReAct paper](https://arxiv.org/pdf/2210.03629.pdf), specifically the Wikipedia example.**

According to my understanding, MRKL is implemented by using ReAct framework in langchain ,which is called zero-shot-react-description. The original ReAct is been implemented in react-docstore agent type.
ps. MRKL is published in 1 May 2022, earlier than ReAct, which is published 6 Oct 2022.

**Comment by g-votte** [comment]
I suspect that the gap between LangChain's MRKL implementation (`zero-shot-react-description`) and what is outlined in the [original MRKL paper](https://arxiv.org/pdf/2205.00445.pdf) is causing some confusion. To elaborate, the original MRKL paper is quite abstract and does not provide detailed implementation information. As such, the "MRKL system” is open to a wide range of interpretations, and ReAct could be associated as one instance of MRKL.

In my understanding, MRKL itself is not a zero-shot version of ReAct but is rather "_**implemented by using ReAct framework in langchain**_," as mentioned by @zuojie in a previous comment.

If those points are correct, I think it would be beneficial to specify them somewhere under `langchain.agents.mrkl` or in other documentation. It appears that some people are confused about the relationship between MRKL and ReAct.

**Comment by LangDaoAI** [comment]
I am also confused about the relationship between MRKL and ReAct.
