### ISSUE TITLE
Standardize DocumentLoader docstrings and integration docs

### ISSUE THREAD

**Issue by isahers1** [langchain-ai/langchain#22866]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

## Issue

To make our document loader integrations as easy to use as possible we need to make sure the docs for them are thorough and standardized. There are two parts to this: updating the document loader docstrings and updating the actual integration docs.

This needs to be done for each DocumentLoader integration, ideally with one PR per DocumentLoader.

Related to broader issues https://github.com/langchain-ai/langchain/issues/21983 and https://github.com/langchain-ai/langchain/issues/22005.

## Docstrings

Each DocumentLoader class docstring should have the sections shown in the [Appendix](#appendix) below. The sections should have input and output code blocks when relevant. See RecursiveUrlLoader [docstrings](https://github.com/langchain-ai/langchain/blob/869523ad728e6b76d77f170cce13925b4ebc3c1e/libs/community/langchain_community/document_loaders/recursive_url_loader.py#L54) and [corresponding API reference](https://api.python.langchain.com/en/latest/document_loaders/langchain_community.document_loaders.recursive_url_loader.RecursiveUrlLoader.html) for an example.

## Doc Pages

Each DocumentLoader [docs page](https://python.langchain.com/v0.2/docs/integrations/document_loaders/) should follow [this template](https://github.com/langchain-ai/langchain/blob/master/libs/cli/langchain_cli/integration_template/docs/document_loaders.ipynb). See [RecursiveUrlLoader](https://python.langchain.com/v0.2/docs/integrations/document_loaders/recursive_url/) for an example.

You can use the `langchain-cli` to quickly get started with a new document loader integration docs page (run from root of repo):

```bash
poetry run pip install -e libs/cli
poetry run langchain-cli integration create-doc --name "foo-bar" --name-class FooBar --component-type "DocumentLoader" --destination-dir ./docs/docs/integrations/document_loaders/
```

where `--name` is the integration package name without the "langchain-" prefix and `--name-class` is the class name without the "Loader" suffix. This will create a template doc with some autopopulated fields at docs/docs/integrations/document_loaders/foo_bar.ipynb.

To build a preview of the docs you can run (from root):

```bash
make docs_clean
make docs_build
cd docs/build/output-new
yarn
yarn start
```

## Appendix

"""
    __ModuleName__ document loader integration
    
    # TODO: Replace with relevant packages, env vars.
    Setup:
        Install ``__package_name__`` and set environment variable ``__MODULE_NAME___API_KEY``.

        .. code-block:: bash

            pip install -U __package_name__
            export __MODULE_NAME___API_KEY="your-api-key"

    # TODO: Replace with relevant init params.
    Instantiate:
        .. code-block:: python

            from __module_name__ import __ModuleName__Loader

            loader = __ModuleName__Loader(
                url = "https://docs.python.org/3.9/",
                # otherparams = ...
            )

    Load:
        .. code-block:: python

            docs = loader.load()
            print(docs[0].page_content[:100])
            print(docs[0].metadata)

        .. code-block:: python

            TODO: Example output

    # TODO: Delete if async load is not implemented
    Async load:
        .. code-block:: python

            docs = await loader.aload()
            print(docs[0].page_content[:100])
            print(docs[0].metadata)

        .. code-block:: python

            TODO: Example output

    Lazy load:
        .. code-block:: python

            docs = []
            docs_lazy = loader.lazy_load()

            # async variant:
            # docs_lazy = await loader.alazy_load()

            for doc in docs_lazy:
                docs.append(doc)
            print(docs[0].page_content[:100])
            print(docs[0].metadata)

        .. code-block:: python

            TODO: Example output  
    """

**Comment by lucas-tucker** [comment]
I will work on this today

**Comment by liugddx** [comment]
Is this approach to document checking too strict? And the error message is not clear enough. For example, here I can't find why the verification failed. https://github.com/langchain-ai/langchain/pull/25734. My title order is the same as in the example.
