### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/chat/> Ollama JSON mode seems to be marked incorrectly as NO

### ISSUE THREAD

**Issue by piotrekz79** [langchain-ai/langchain#22910]
### URL

https://python.langchain.com/v0.2/docs/integrations/chat/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The webpage https://python.langchain.com/v0.2/docs/integrations/chat/#advanced-features says ChatOllama has no JSON mode (red cross) while https://python.langchain.com/v0.2/docs/concepts/#structured-output says: Some models, such as (...) Ollama support a feature called JSON mode. Also examples here support JSON mode existence https://python.langchain.com/v0.2/docs/integrations/chat/ollama/#extraction

### Idea or request for content:

Insert green checkbox for Ollama/JSON on https://python.langchain.com/v0.2/docs/integrations/chat/#advanced-features

**Comment by efriis** [comment]
appreciate the report!
