### ISSUE TITLE
It will occurred error if a dependent library `tenacity` is upgraded to `8.4.0`.

### ISSUE THREAD

**Issue by itok01** [langchain-ai/langchain#22972]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
import tenacity
```

### Error Message and Stack Trace (if applicable)

> ```
> > import tenacity
> ...
> lib/python3.11/site-packages/tenacity/__init__.py", line 653, in <module>
>      from tenacity.asyncio import AsyncRetrying  # noqa:E402,I100
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  ModuleNotFoundError: No module named 'tenacity.asyncio'
> ```

### Description

Tenacity 8.4.0 has error.

https://github.com/langchain-ai/langchain/blob/892bd4c29be34c0cc095ed178be6d60c6858e2ec/libs/core/pyproject.toml#L15

https://github.com/jd/tenacity/issues/471

### System Info

- Python 3.11
- tenacity 8.4.0

**Comment by Bondify** [comment]
me too, exactly the same error when I try to use `plotly.scatter`.

**Comment by koritsky** [comment]
`tenacity` just released `8.4.0`, so just downgrading to `8.3.0` solves an issue.

`pip install tenacity==8.3.0`

**Comment by kennethpgreen** [comment]
Same error here too

**Comment by JosephP91** [comment]
Same error here

**Comment by Kaiohz** [comment]
i put in my pipfile tenacity = "<8.4.0" and the error is gone

**Comment by tangos974** [comment]
Yeah the latest tenacity update breaks langchain but setting tenacity==8.3.0 fixes.

**Comment by RashmiDeshpande21** [comment]
> Yeah the latest tenacity update breaks langchain but setting tenacity==8.3.0 fixes.

Thank you so much! Been breaking my head coz of this for the past hour....

**Comment by gpiyush2532** [comment]
Thank you, changing version of tenacity fix it.

**Comment by adrienohana** [comment]
I can't believe how unreliable this library is... Thanks for the fix

**Comment by ryilkici** [comment]
Thank you all friends for the solution. It's good to see you.

**Comment by Kszemi** [comment]
Thanks!

**Comment by gsinh** [comment]
Thank you. I have a critical demo coming up and this saved my life!

**Comment by pawankumar94** [comment]
I face the same occuring, apparently our production release is failing due to this

**Comment by levalencia** [comment]
> I can't believe how unreliable this library is... Thanks for the fix

but its actually an issue in tenacity, not in langchain.

**Comment by adrienohana** [comment]
> > I can't believe how unreliable this library is... Thanks for the fix
> 
> but its actually an issue in tenacity, not in langchain.

I might be wrong here, but langchain should have version locked the package. There is nothing wrong with package updates that are not backward compatible.

**Comment by tClelford** [comment]
> > > I can't believe how unreliable this library is... Thanks for the fix
> > 
> > 
> > but its actually an issue in tenacity, not in langchain.
> 
> I might be wrong here, but langchain should have version locked the package. There is nothing wrong with package updates that are not backward compatible.

Yes and no :) If tenacity were doing semver properly they'd bump the major version number when they made the breaking change

**Comment by adrienohana** [comment]
> > > > I can't believe how unreliable this library is... Thanks for the fix
> > > 
> > > 
> > > but its actually an issue in tenacity, not in langchain.
> > 
> > 
> > I might be wrong here, but langchain should have version locked the package. There is nothing wrong with package updates that are not backward compatible.
> 
> Yes and no :) If tenacity were doing semver properly they'd bump the major version number when they made the breaking change

indeed

**Comment by ycjcl868** [comment]
same issue

**Comment by pankajkrastogi** [comment]
same issue

**Comment by LelViLamp** [comment]
Wow, 2 hours ago. Many thanks for your help. 😎

**Comment by bvdr** [comment]
Same here! Does anyone know how to manage the version when it's used by another library? 🤔

**Comment by mr-v-v-v** [comment]
aaaaa!!!

**Comment by mr-v-v-v** [comment]
why they did this? it's crazy. thanks for fix

**Comment by bvdr** [comment]
I found the solution and wanted to share it here for anyone interested. 😊

Make sure to add the contained version before the library that uses it.
```
tenacity==8.3.0
klaviyo_api==7.0.0
```

**Comment by tangos974** [comment]
`klaviyo_api==7.0.0` not needed
Just do `tenacity==8.3.0` or any tenacity thats not 8.4.0 really. As stated above, its the latest update to tenacity that's causing problems.

**Comment by bvdr** [comment]
@tangos974 Do you say it should work either way?

**Comment by pauljaspersahr** [comment]
thanks!

**Comment by mlatysh** [comment]
Wow guys! I've just faced this issue a couple of hours ago and couldn't find anything and now I saw this. I love OS AI community ❤️

**Comment by dakilasera** [comment]
thanks guys! Community FTW!

**Comment by palewire** [comment]
This hit me too. Thanks for the help.

**Comment by Greg-Tarr** [comment]
Thanks!

**Comment by UlyanaGno** [comment]
Thanks guys!

**Comment by nb-programmer** [comment]
> why they did this? it's crazy. thanks for fix

I think they just tried to refactor something and that was not done properly? Just guessing

**Comment by AntFMoJ** [comment]
Thank you! Pinning to `tenacity==8.3.0` worked!

**Comment by lgosselin** [comment]
For information tenacity 8.4.1 has been released. Maybe it fixes your problem. (It does for me in an unrelated project).
