### ISSUE TITLE
langchain-milvus  install error

### ISSUE THREAD

**Issue by qingcelei** [langchain-ai/langchain#22976]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

pip install --upgrade --quiet pymilvus[model] langchain-milvus

### Error Message and Stack Trace (if applicable)

![image](https://github.com/langchain-ai/langchain/assets/119028382/895bc83e-a774-4528-b14b-d6950ba6224d)

### Description

can not install langchain-milvus

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.5
> langchain: 0.2.3
> langchain_community: 0.2.4
> langsmith: 0.1.77
> langchain_cli: 0.0.23
> langchain_google_cloud_sql_mysql: 0.2.2
> langchain_google_vertexai: 1.0.5
> langchain_openai: 0.1.6
> langchain_text_splitters: 0.2.1
> langchainhub: 0.1.17
> langserve: 0.2.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph

**Comment by spike-spiegel-21** [comment]
Use `pip install --upgrade langchain_milvus`
