### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/tool_calling/>

### ISSUE THREAD

**Issue by BellaBe** [langchain-ai/langchain#22989]
### URL

https://python.langchain.com/v0.2/docs/how_to/tool_calling/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The following example should not be included in this page. The llm_with_tools instantiation examples use different LLMs that are not compatible with PydanticToolsParser. This creates confusion and wastes time

`from langchain_core.output_parsers.openai_tools import PydanticToolsParser

chain = llm_with_tools | PydanticToolsParser(tools=[Multiply, Add])
chain.invoke(query)`

**Comment by ccurme** [comment]
Thanks for this, what LLM(s) are you running into issues with?

**Comment by BellaBe** [comment]
I am using mistral and llama3 through Groq, the point is the mentioned example could be used only with OpenAI

**Comment by ccurme** [comment]
Thanks for raising this.

`PydanticToolsParser` will work with any model that supports the standardized tool calling feature described in that doc. To your point, it can definitely be misleading to have to import those from a module named `openai_tools`, so I've opened a PR to address that: https://github.com/langchain-ai/langchain/pull/23305

I double-checked with Mistral and Groq. Please let me know if you're still running into issues and ensure your package versions are up to date. Closing for now but will re-open if I've misunderstood something or issues remain.
```python
from langchain_core.output_parsers.openai_tools import PydanticToolsParser
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_groq import ChatGroq
from langchain_mistralai import ChatMistralAI

class Multiply(BaseModel):
    """Multiply two integers together."""

    a: int = Field(..., description="First integer")
    b: int = Field(..., description="Second integer")

mistral = (
    ChatMistralAI(model="mistral-large-latest").bind_tools([Multiply])
    | PydanticToolsParser(tools=[Multiply])
)
groq = (
    ChatGroq(model="llama3-8b-8192").bind_tools([Multiply])
    | PydanticToolsParser(tools=[Multiply])
)

query = "What is 3 * 12?"

print(mistral.invoke(query))
print(groq.invoke(query))
```
