### ISSUE TITLE
DOC: wrong link URL

### ISSUE THREAD

**Issue by cannuri** [langchain-ai/langchain#22992]
### URL

https://github.com/langchain-ai/langchain/blob/c6b7db6587c5397e320b84cbd7cd25c7c4b743e5/docs/docs/how_to/toolkits.mdx#L4

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The Link "Integration" points to [a wrong url](https://github.com/langchain-ai/langchain/blob/c6b7db6587c5397e320b84cbd7cd25c7c4b743e5/docs/integrations/toolkits).
[this is](https://github.com/langchain-ai/langchain/tree/c6b7db6587c5397e320b84cbd7cd25c7c4b743e5/docs/docs/integrations/toolkits) the Correct URL (/docs/docs instead of /docs/)

**Comment by baskargopinath** [comment]
its intended to not work on github but work on langchain website @cannuri
