### ISSUE TITLE
Add image token counting to ChatOpenAI

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#23000]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

**Comment by bengladwell** [comment]
One possible approach:
Update `langchain_openai.chat_models.base.BaseChatOpenAI.get_num_tokens_from_messages` to look for `list` value of the `content` field. If found, look for `type` == `image_url` and use an algorithm similar to what is described [here](https://community.openai.com/t/how-do-i-calculate-image-tokens-in-gpt4-vision/492318).

**Comment by baskaryan** [comment]
to ChatOpenAI.get_num_tokens_from_messages specifically

see image token counting here https://openai.com/api/pricing/

**Comment by Etelis** [comment]
I will take this one
