### ISSUE TITLE
DOC: Azure Cosmos DB No SQL

### ISSUE THREAD

**Issue by Hela-Masri-shift** [langchain-ai/langchain#23018]
### URL

https://python.langchain.com/v0.2/docs/integrations/vectorstores/azure_cosmos_db_no_sql/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The current code does not work, it fails on document insertion with the following error
TypeError: AzureCosmosDBNoSqlVectorSearch._from_kwargs() missing 1 required keyword-only argument: 'cosmos_database_properties'

**Comment by AnuragSa** [comment]
I am facing same issue

**Comment by DamirZelenic** [comment]
Looks like we need to define:

`cosmos_database_properties = {"id": cosmos_database_name}`

and then:

`
...
vector_search = AzureCosmosDBNoSqlVectorSearch.from_documents(
        documents=docs,
        embedding=openai_embeddings,
        cosmos_client=cosmos_client,
        database_name=cosmos_database_name,
        container_name=cosmos_container_name,
        vector_embedding_policy=vector_embedding_policy,
        indexing_policy=indexing_policy,
        cosmos_container_properties=cosmos_container_properties,
        cosmos_database_properties=cosmos_database_properties,)`

Regards, Damir
