### ISSUE TITLE
ValueError: `tool_calls` missing from AIMessage: {message}

### ISSUE THREAD

**Issue by baskargopinath** [langchain-ai/langchain#23065]
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_core.prompts import PromptTemplate
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_experimental.llms.ollama_functions import OllamaFunctions

# Schema for structured response
class Person(BaseModel):
    name: str = Field(description="The person's name", required=True)
    height: float = Field(description="The person's height", required=True)
    hair_color: str = Field(description="The person's hair color")

# Prompt template
prompt = PromptTemplate.from_template(
    """Alex is 5 feet tall. 
Claudia is 1 feet taller than Alex and jumps higher than him. 
Claudia is a brunette and Alex is blonde.

Human: {question}
AI: """
)

# Chain
llm = OllamaFunctions(model="phi3", format="json", temperature=0)
structured_llm = llm.with_structured_output(Person)
chain = prompt | structured_llm
alex = chain.invoke("Describe Alex")

### Description

Trying to extract structured output

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
> Python Version:  3.9.6 (default, Feb  3 2024, 15:58:27) 
[Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.2.8
> langchain: 0.2.5
> langchain_community: 0.2.5
> langsmith: 0.1.79
> langchain_experimental: 0.0.61
> langchain_google_genai: 1.0.5
> langchain_google_vertexai: 1.0.4
> langchain_mistralai: 0.1.8
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.16

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by apfister** [comment]
@baskargopinath curious if/how this was resolved? I'm seeing the same thing when changing the question in that example to someone not Alex or Claudia. I've tried setting None to the default Field values and also `required=False` for each but the errors remains.

**Comment by baskargopinath** [comment]
@apfister still not fixed up, i ended up using PydanticOutputParser manually to get structured output

**Comment by uzairlatif90** [comment]
I am currently having the same error with mistral-nemo. Is there any timeline of when this might be fixed?
