### ISSUE TITLE
Add stream method for HuggingFacePipeline Objet

### ISSUE THREAD

**Issue by sam-h-bean** [langchain-ai/langchain#2309]
Probably use this

https://huggingface.co/docs/transformers/main/en/generation_strategies#streaming

**Comment by sam-h-bean** [comment]
We probably want to expose the raw generator objects so that people can create streaming APIs w/ SSE

**Comment by PyroGenesis** [comment]
Please don't keep this issue closed I'm facing the same problem: https://stackoverflow.com/questions/77197723/how-do-i-stream-huggingfacepipeline-output-to-a-langchain-dataframe-agent

**Comment by laudanum123** [comment]
@PyroGenesis @sam-h-bean I created a pull request which implements the streaming for the HuggingFacePipeline by implementing the _astream method. It is still a bit hacky I think but it works very well. Here is the link to the PR: https://github.com/langchain-ai/langchain/pull/14090

I am currently using the streaming in a chainlit app. It should work with other frontends but I haven't tested it. Below is my chainlit app:

```python
from langchain.llms.huggingface_pipeline import HuggingFacePipeline
from transformers import AutoTokenizer, TextIteratorStreamer
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers.string import StrOutputParser
from langchain_core.runnables.config import RunnableConfig
from langchain_core.runnables.base import Runnable

import transformers
import torch

import chainlit as cl
from chainlit.playground.config import add_llm_provider
from chainlit.playground.providers.langchain import LangchainGenericProvider

template = """
GPT4 Correct User: {question}<|end_of_turn|>GPT4 Correct Assistant:
"""

# Load model and tokenizer


@cl.cache
def load_llama():
    model_name = "berkeley-nest/Starling-LM-7B-alpha"
    model_path = "./model"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
    pipeline = transformers.pipeline(
        "text-generation",
        model=model_path,
        tokenizer=tokenizer,
        trust_remote_code=True,
        device_map="auto",
        max_length=10000,
        do_sample=True,
        num_return_sequences=1,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id,
        streamer=streamer
    )

    llm = HuggingFacePipeline(
        pipeline=pipeline,
        model_kwargs={"temperature": 0.8}
    )
    return llm


llm = load_llama()

# add_llm_provider(
#     LangchainGenericProvider(
#         id=llm._llm_type, name="starling7b", llm=llm, is_chat=False
#     )
# )

@cl.on_chat_start
async def on_chat_start():
    model = load_llama()
    prompt = PromptTemplate(template=template, input_variables=["GPT4 Correct User"])
    runnable = prompt | model | StrOutputParser()
    cl.user_session.set("runnable", runnable)

@cl.on_message
async def on_message(message: cl.Message):
    runnable = cl.user_session.get("runnable")

    msg = cl.Message(content="")

    async for chunk in runnable.astream(
        {"question": message.content},
        config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await msg.stream_token(chunk)

    await msg.send()
```

**Comment by viobert** [comment]
> @PyroGenesis @sam-h-bean I created a pull request which implements the streaming for the HuggingFacePipeline by implementing the _astream method. It is still a bit hacky I think but it works very well. Here is the link to the PR: #14090
> 
> I am currently using the streaming in a chainlit app. It should work with other frontends but I haven't tested it. Below is my chainlit app:
> 
> ```python
> from langchain.llms.huggingface_pipeline import HuggingFacePipeline
> from transformers import AutoTokenizer, TextIteratorStreamer
> from langchain.prompts import PromptTemplate
> from langchain_core.output_parsers.string import StrOutputParser
> from langchain_core.runnables.config import RunnableConfig
> from langchain_core.runnables.base import Runnable
> 
> import transformers
> import torch
> 
> import chainlit as cl
> from chainlit.playground.config import add_llm_provider
> from chainlit.playground.providers.langchain import LangchainGenericProvider
> 
> template = """
> GPT4 Correct User: {question}<|end_of_turn|>GPT4 Correct Assistant:
> """
> 
> # Load model and tokenizer
> 
> 
> @cl.cache
> def load_llama():
>     model_name = "berkeley-nest/Starling-LM-7B-alpha"
>     model_path = "./model"
>     tokenizer = AutoTokenizer.from_pretrained(model_name)
>     streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
>     pipeline = transformers.pipeline(
>         "text-generation",
>         model=model_path,
>         tokenizer=tokenizer,
>         trust_remote_code=True,
>         device_map="auto",
>         max_length=10000,
>         do_sample=True,
>         num_return_sequences=1,
>         pad_token_id=tokenizer.pad_token_id,
>         eos_token_id=tokenizer.eos_token_id,
>         streamer=streamer
>     )
> 
>     llm = HuggingFacePipeline(
>         pipeline=pipeline,
>         model_kwargs={"temperature": 0.8}
>     )
>     return llm
> 
> 
> llm = load_llama()
> 
> # add_llm_provider(
> #     LangchainGenericProvider(
> #         id=llm._llm_type, name="starling7b", llm=llm, is_chat=False
> #     )
> # )
> 
> @cl.on_chat_start
> async def on_chat_start():
>     model = load_llama()
>     prompt = PromptTemplate(template=template, input_variables=["GPT4 Correct User"])
>     runnable = prompt | model | StrOutputParser()
>     cl.user_session.set("runnable", runnable)
> 
> @cl.on_message
> async def on_message(message: cl.Message):
>     runnable = cl.user_session.get("runnable")
> 
>     msg = cl.Message(content="")
> 
>     async for chunk in runnable.astream(
>         {"question": message.content},
>         config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
>     ):
>         await msg.stream_token(chunk)
> 
>     await msg.send()
> ```

Thank you for your guidance. I've been experimenting with the code you provided, integrating it into a chainlit app. However, I was curious whether this refers to the output being streamed (word by word) as LangChain intermediate steps, or as the final answer streamed word by word.
In my trials, neither streaming scenario occurred in my Chainlit.
