### ISSUE TITLE
Can't Specify Top-K retrieved Documents in Multimodal Retrievers using Invoke()

### ISSUE THREAD

**Issue by benjamin-meinhardt** [langchain-ai/langchain#23158]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
# Check retrieval
query = "What are the EV / NTM and NTM rev growth for MongoDB, Cloudflare, and Datadog?"
docs = retriever_multi_vector_img.invoke(query, limit=6)

# We get 4 docs
len(docs)
```

### Description

`retriever_multi_vector_img.invoke(query)` no longer has a method to limit or increase the amount of docs returned and subsequently passed to the LLM. This is defaulted at 4 and no information can be found on the issue.

You can see the incorrect use in this cookbook: https://github.com/langchain-ai/langchain/blob/master/cookbook/Multi_modal_RAG.ipynb

```
# Check retrieval
query = "What are the EV / NTM and NTM rev growth for MongoDB, Cloudflare, and Datadog?"
docs = retriever_multi_vector_img.invoke(query, limit=6)

# We get 4 docs
len(docs)
```

Where 6 was the limit and 4 is returned. How can we enforce more docs to be returned?

### System Info

Using langchain_core 0.2.8

**Comment by WithFoxSquirrel** [comment]
try following, get the top k result
retriever_multi_vector_img = vectorstore.as_retriever(
                    search_type="mmr",
                search_kwargs={'k': 3, 'fetch_k': 5}
)

then,
retriever_multi_vector_img.invoke(question)
