### ISSUE TITLE
MultiQuery Retriever Using AzureSearch vector store always returns a invalid json format error

### ISSUE THREAD

**Issue by mdubeyAnsys** [langchain-ai/langchain#23171]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code using AzureSearch as vectorstore for Azure Cognitive Search always gives me invalid json format: 

import os
from langchain_openai import AzureChatOpenAI
from langchain.retrievers.multi_query import MultiQueryRetriever
from langchain_openai import AzureOpenAIEmbeddings
from typing import List
from langchain.chains import LLMChain
from langchain.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from langchain_community.vectorstores.azuresearch import AzureSearch

api_key = os.getenv("AZURE_OPENAI_API_KEY")
api_version = os.getenv("AZURE_API_VERSION")
azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
vector_store_password = os.getenv("AZURE_SEARCH_ADMIN_KEY")
vector_store_address = os.getenv("AZURE_SEARCH_ENDPOINT")
service_name = os.getenv("AZURE_SERVICE_NAME")
azure_deployment="text-embedding-ada-002"
azure_openai_api_version=api_version
azure_endpoint=azure_endpoint
azure_openai_api_key=api_key

embeddings: AzureOpenAIEmbeddings = AzureOpenAIEmbeddings(
    azure_deployment=azure_deployment,
    openai_api_version=azure_openai_api_version,
    azure_endpoint=azure_endpoint,
    api_key=azure_openai_api_key,
)

index_name: str = "test-index"

vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)

model= os.getenv('modelName')
# Output parser will split the LLM result into a list of queries
class LineList(BaseModel):
    # "lines" is the key (attribute name) of the parsed output
    lines: List[str] = Field(description="Lines of text")

class LineListOutputParser(PydanticOutputParser):
    def __init__(self) -> None:
        super().__init__(pydantic_object=LineList)

    def parse(self, text: str) -> LineList:
        lines = text.strip().split("\n")
        return LineList(lines=lines)

output_parser = LineListOutputParser()

QUERY_PROMPT = PromptTemplate(
    input_variables=["question"],
    template="""You are an AI language model assistant. Your task is to generate five 
    different versions of the given user question to retrieve relevant documents from a vector 
    database. By generating multiple perspectives on the user question, your goal is to help
    the user overcome some of the limitations of the distance-based similarity search. 
    Provide these alternative questions separated by newlines.
    Original question: {question}""",
)

llm = AzureChatOpenAI(temperature=0,api_key=api_key,api_version=api_version,model=model)

llm_chain = LLMChain(llm=llm, prompt=QUERY_PROMPT, output_parser=output_parser)

retriever = MultiQueryRetriever(
    retriever=vector_store.as_retriever(), llm_chain=llm_chain, parser_key="lines"
)  
print(type(retriever.llm_chain.output_parser))  
print(retriever.llm_chain.output_parser)  

unique_docs = retriever.invoke(query="What is Llama-2?")
print(unique_docs)

### Error Message and Stack Trace (if applicable)

Exception has occurred: OutputParserException 
langchain_core.exceptions.OutputParserException: Invalid json output: Can you provide information on Llama-2?
Could you explain the concept of Llama-2?
What does Llama-2 refer to?

  File Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
StopIteration: 0

During handling of the above exception, another exception occurred:

  File "Python\Python312\Lib\site-packages\langchain_core\output_parsers\json.py", line 66, in parse_result
    return parse_json_markdown(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File \Python\Python312\Lib\site-packages\langchain_core\utils\json.py", line 147, in parse_json_markdown
    return _parse_json(json_str, parser=parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \Python\Python312\Lib\site-packages\langchain_core\utils\json.py", line 160, in _parse_json
    return parser(json_str)
           ^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain_core\utils\json.py", line 120, in parse_partial_json
    return json.loads(s, strict=strict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \Python\Python312\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File \Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

  File Python\Python312\Lib\site-packages\langchain_core\output_parsers\json.py", line 69, in parse_result
    raise OutputParserException(msg, llm_output=text) from e
  File Python\Python312\Lib\site-packages\langchain_core\output_parsers\pydantic.py", line 60, in parse_result
    json_object = super().parse_result(result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain\chains\llm.py", line 284, in create_outputs
    self.output_key: self.output_parser.parse_result(generation),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain\chains\llm.py", line 127, in _call
    return self.create_outputs(response)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain\chains\base.py", line 166, in invoke
    raise e
  File Python\Python312\Lib\site-packages\langchain\chains\base.py", line 166, in invoke
    raise e
  File Python\Python312\Lib\site-packages\langchain\retrievers\multi_query.py", line 182, in generate_queries
    response = self.llm_chain.invoke(
               ^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain\retrievers\multi_query.py", line 165, in _get_relevant_documents
    queries = self.generate_queries(query, run_manager)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain_core\retrievers.py", line 221, in invoke
    raise e
  File Python\Python312\Lib\site-packages\langchain_core\retrievers.py", line 221, in invoke
    raise e
  File Python\Python312\Lib\site-packages\langchain_core\retrievers.py", line 355, in get_relevant_documents
    return self.invoke(query, config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File Python\Python312\Lib\site-packages\langchain_core\_api\deprecation.py", line 168, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
    unique_docs = retriever.get_relevant_documents(query="What is Llama-2")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File Python\Python312\Lib\site-packages\langchain_core\output_parsers\json.py", line 69, in parse_result
    raise OutputParserException(msg, llm_output=text) from e
langchain_core.exceptions.OutputParserException: Invalid json output: Can you provide information on Llama-2?
Could you explain the concept of Llama-2?
What does Llama-2 refer to?

### Description

I'm trying to use MultiQuery Retriver using vector store of Azure Cognitive Search. I'm following the example explained in Langchain documentation, https://python.langchain.com/v0.1/docs/modules/data_connection/retrievers/MultiQueryRetriever/ and used the vector store AzureSearch, Is there anything I miss using the vector_store for MultiQuery Retriever?  I always see an error, langchain_core.exceptions.OutputParserException: Invalid json output. 

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.9
> langchain: 0.2.5
> langchain_community: 0.0.13
> langsmith: 0.1.80
> langchain_chroma: 0.1.1
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.1
> langgraph: 0.0.69

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by sameemqureshi** [comment]
Any fix/updates on this issue ?

**Comment by spike-spiegel-21** [comment]
@mdubeyAnsys @sameemqureshi  The above documentation code is deprecated. Use this:

```
# Build a sample vectorDB
from langchain_chroma import Chroma
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.embeddings import FakeEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Load blog post
loader = WebBaseLoader("https://lilianweng.github.io/posts/2023-06-23-agent/")
data = loader.load()

# Split
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=0)
splits = text_splitter.split_documents(data)

# VectorDB
embedding = FakeEmbeddings(size=1352)
vectordb = Chroma.from_documents(documents=splits, embedding=embedding)

# replace with your llm
from langchain_community.llms.fake import FakeListLLM
# expected results from llm
responses = ["What methods are used for decomposing tasks?\nCan you describe different strategies for task decomposition?"]
# replace with your llm
llm = FakeListLLM(responses=responses)



from langchain.retrievers.multi_query import MultiQueryRetriever
retriever = MultiQueryRetriever.from_llm(llm=llm,retriever=vectordb.as_retriever())

# Results
unique_docs = retriever.invoke("What does the course say about regression?")
print(len(unique_docs))
```
