### ISSUE TITLE
Crash due to circular dependency on BaseChatMessageHistory

### ISSUE THREAD

**Issue by cbornet** [langchain-ai/langchain#23175]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_core.chat_history import BaseChatMessageHistory
```

### Error Message and Stack Trace (if applicable)

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/christophebornet/Library/Caches/pypoetry/virtualenvs/ragstack-ai-langchain-F6idWdWf-py3.9/lib/python3.9/site-packages/langchain_core/chat_history.py", line 29, in <module>
    from langchain_core.runnables import run_in_executor
  File "/Users/christophebornet/Library/Caches/pypoetry/virtualenvs/ragstack-ai-langchain-F6idWdWf-py3.9/lib/python3.9/site-packages/langchain_core/runnables/__init__.py", line 39, in <module>
    from langchain_core.runnables.history import RunnableWithMessageHistory
  File "/Users/christophebornet/Library/Caches/pypoetry/virtualenvs/ragstack-ai-langchain-F6idWdWf-py3.9/lib/python3.9/site-packages/langchain_core/runnables/history.py", line 16, in <module>
    from langchain_core.chat_history import BaseChatMessageHistory
ImportError: cannot import name 'BaseChatMessageHistory' from partially initialized module 'langchain_core.chat_history' (most likely due to a circular import) (/Users/christophebornet/Library/Caches/pypoetry/virtualenvs/ragstack-ai-langchain-F6idWdWf-py3.9/lib/python3.9/site-packages/langchain_core/chat_history.py)
```

### Description

On latest master, importing BaseChatMessageHistory fails because of a circular dependency. (it works with the very recent langchain-core 0.2.9)
I suspect this is caused by : https://github.com/langchain-ai/langchain/pull/23136

### System Info

langchain==0.2.5
langchain-astradb==0.3.3
langchain-community==0.2.5
langchain-core @ git+https://github.com/langchain-ai/langchain.git@4fe8403bfbb81e7780179a3b164aa22c694e2ece#subdirectory=libs/core
langchain-openai==0.1.8
langchain-text-splitters==0.2.1

**Comment by eyurtsev** [comment]
@ccurme looking into resolving

**Comment by ccurme** [comment]
@cbornet this should be resolved on master, closing but lmk if you still run into an issue. Thanks for flagging!
