### ISSUE TITLE
Misleading logs

### ISSUE THREAD

**Issue by 954-Ivory** [langchain-ai/langchain#23239]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import os

from dotenv import load_dotenv
from langchain_core.globals import set_debug
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

set_debug(True)
load_dotenv()
model = ChatOpenAI(
    api_key=os.getenv('OPENAI_API_KEY'),
    base_url=os.getenv('OPENAI_BASE_URL'),
    model="gpt-3.5-turbo"
)

messages = [
    SystemMessage(content="Translate the following from English into Italian"),
    HumanMessage(content="hi!"),
]

if __name__ == "__main__":
    print(model.invoke(messages))
```

### Error Message and Stack Trace (if applicable)

```
[llm/start] [llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: Translate the following from English into Italian\nHuman: hi!"
  ]
}
```

### Description

Shouldn't it be like this?

```
[llm/start] [llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System": "Translate the following from English into Italian",
    "Human": "hi!"
  ]
}
```

### System Info

I have tried it in two conda envs:

---

langchain 0.2.5
windows 11
python Python 3.11.9

---

langchain 0.1.10
windows 11
python Python 3.11.7

**Comment by wenngong** [comment]
The terminal output u see is just intermediate logs by ***CallBackHandler，and the handler function flatten the chat prompt messages into single string for logging.

so, it's not a bug I believe.

![image](https://github.com/langchain-ai/langchain/assets/76683249/6acdbe4e-055f-48ce-b82e-fa53b7cf707a)

**Comment by 954-Ivory** [comment]
> The terminal output u see is just intermediate logs by ***CallBackHandler，and the handler function flatten the chat prompt messages into single string for logging.你看到的终端输出只是 ***CallBackHandler 的中间日志，处理程序函数将聊天提示消息扁平化为单个字符串进行记录。
> 
> so, it's not a bug I believe.所以，我相信这不是一个错误。
> 
> ![image](https://private-user-images.githubusercontent.com/76683249/341611507-6acdbe4e-055f-48ce-b82e-fa53b7cf707a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MzUwOTksIm5iZiI6MTcxODkzNDc5OSwicGF0aCI6Ii83NjY4MzI0OS8zNDE2MTE1MDctNmFjZGJlNGUtMDU1Zi00OGNlLWI4MmUtZmE1M2I3Y2Y3MDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDAxNTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMDg3ZWE1ZWJjYjk3ZGNiZDdmYmVlNDA2ZGU1MTUxOTg5MjFlY2Q2YzE3N2E4ZmIzM2Q5OGM2OWY1MjM5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6wnjXB_Ly1VtTQPAp-GgIAVsIor_Rh_-m0aagHvDTk)

Yes, I have checked the network request and there is no problem. But such output will cause misunderstandings.
