### ISSUE TITLE
Error in llm-math tool causes a loop

### ISSUE THREAD

**Issue by swimleftproducts** [langchain-ai/langchain#2323]
When running the code shown below I ended up with what seemed like an endless agent loop. I stopped the code and repeated the code, but the error did not repeat. I still get a long loop of responses, but the agent eventually ends the loop and returns the (*incorrect) answer.
![image](https://user-images.githubusercontent.com/13142177/229385046-a0353677-6fce-43fa-94f3-4273e4ee0da0.png)

**Comment by ColinTitahi** [comment]
FYI. I'm getting loops occasionally on other tools as well. For me its search which blows the token limit out.
Maybe a symptom of a more fundamental issue.

**Comment by dxv2k** [comment]
I have the the same problem, but it doesn't stop with `llm-math` but also with many different tools like google search. 
My temporary fix is that you include something like `do not use this tool with the same input/query`.

**Comment by Blackkadder** [comment]
> It seems to me that there should be a parameter to set the max number of calls to a tool in a row. Or at least code to handle the same input to the tool occurring twice.
> 
> Nice temp fix though dxv2k

This would be amazing!

**Comment by 2sick2speak** [comment]
I've added a param to `initialize_agent` call `max_iterations=len(tools)` and it tries every tool only once. Worked for me
