### ISSUE TITLE
Cancelling Llama CPP Generation Using Agent's astream_events

### ISSUE THREAD

**Issue by Spider-netizen** [langchain-ai/langchain#23282]
> @TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain

Did you solve this? It seems I'm facing the same issue.

> > @TheJerryChang will it also stop the llm`s completion process? I am using langchain llama cpp with conversationalretrievalchain
> 
> For my use case, Im using Chat model and did not try with completion process. How do you do the streaming? Did you use chain.stream()? I personally think as long as it supports calling chain.stream() to proceed the streaming, it then could be interrupted by raising an exception during the iteration

I'm using the .astream_events method of AgentExecutor. I'm trying to figure out how to stream an agent response but also be able to cancel it before it finishes generating.

_Originally posted by @Spider-netizen in https://github.com/langchain-ai/langchain/issues/11959#issuecomment-1975388015_

Hi,

Can this be achieved?

Thanks.

**Comment by edwardzjl** [comment]
Hi langchain team, any update on this?
