### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/multimodal_prompts/> Image message structure is incorrect for OpenAI

### ISSUE THREAD

**Issue by bbest31** [langchain-ai/langchain#23294]
### URL

https://python.langchain.com/v0.2/docs/how_to/multimodal_prompts/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The examples in this page show the image as part of the message as:
```json
{"type" : "image_url", "image_url" : "data:image/jpeg;base64,{image_data}"}
```

However, this will result in a 400 response from OpenAI because the `image_url` value must be an object and not a string. This is the proper schema:

```json
{"type" : "image_url", "image_url" : {"url" : "data:image/jpeg;base64,{image_data}"}}
```

### Idea or request for content:

Rewrite the documentation examples to have the proper schema. I believe the other [multi modal page](https://python.langchain.com/v0.2/docs/how_to/multimodal_inputs/) has the correct one.

[OpenAI  documentation reference](https://platform.openai.com/docs/guides/vision/quick-start)

**Comment by baskargopinath** [comment]
@bbest31 can u take a look 
https://github.com/langchain-ai/langchain/pull/23301/files

**Comment by bbest31** [comment]
@baskargopinath changes look good. thank you :)
