### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/chatbot/>

### ISSUE THREAD

**Issue by sagism** [langchain-ai/langchain#23307]
### URL

https://python.langchain.com/v0.2/docs/tutorials/chatbot/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

would be nice to understand what those "Parent run 181a1f04-9176-4837-80e8-ce74866775a2 not found for run ad402c5a-8341-4c62-ac58-cdf923b3b9ec. Treating as a root run." messages mean...
Are they harmless?

**Comment by ccurme** [comment]
Yes. Warnings suppressed by default in https://github.com/langchain-ai/langchain/pull/23363.
