### ISSUE TITLE
SQL problem in langchain-community `langchain_community.vectorstores.duckdb`:194

### ISSUE THREAD

**Issue by NewJerseyStyle** [langchain-ai/langchain#23308]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:
```python
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import DuckDB

db = DuckDB.from_texts(
    ['a', 'v', 'asdfadf', '893yhrfa'],
    HuggingFaceEmbeddings())
```

### Error Message and Stack Trace (if applicable)

```
CatalogException                          Traceback (most recent call last)
Cell In[3], line 2
      1 texts = ['a', 'v', 'asdfadf', '893yhrfa']
----> 2 db = DuckDB.from_texts(texts,
      3                        HuggingFaceEmbeddings())
      4 db.similarity_search('ap', k=5)

File /opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/duckdb.py:287, in DuckDB.from_texts(cls, texts, embedding, metadatas, **kwargs)
    278 instance = DuckDB(
    279     connection=connection,
    280     embedding=embedding,
   (...)
    284     table_name=table_name,
    285 )
    286 # Add texts and their embeddings to the DuckDB vector store
--> 287 instance.add_texts(texts, metadatas=metadatas, **kwargs)
    289 return instance

File /opt/conda/lib/python3.10/site-packages/langchain_community/vectorstores/duckdb.py:194, in DuckDB.add_texts(self, texts, metadatas, **kwargs)
    191 if have_pandas:
    192     # noinspection PyUnusedLocal
    193     df = pd.DataFrame.from_dict(data)  # noqa: F841
--> 194     self._connection.execute(
    195         f"INSERT INTO {self._table_name} SELECT * FROM df",
    196     )
    197 return ids

CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_am"?
LINE 1: INSERT INTO embeddings SELECT * FROM df
```

### Description

* I am trying to use DuckDB as vector storage
* I expect to get a vector storage instance connected to DuckDB
* Instead it throw error on initialization

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Tue Dec 19 13:14:11 UTC 2023
> Python Version:  3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.2.9
> langchain: 0.2.5
> langchain_community: 0.2.5
> langsmith: 0.1.81
> langchain_text_splitters: 0.2.1

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by timvw** [comment]
I am seeing this issue as well (when I have pandas installed).

Without pandas a database/vector_store is happily created (using DuckDB.from_documents)

**Comment by timvw** [comment]
@NewJerseyStyle I see you have created an MR to fix this issue. How about fixing it as following instead?

```python
            df = pd.DataFrame.from_dict(data)  # noqa: F841
            self._connection.register("df", df)
            self._connection.execute(
                f"INSERT INTO {self._table_name} SELECT * FROM df",
            )
```

**Comment by NewJerseyStyle** [comment]
@timvw Good idea, you can submit the solution through MR and I will withdraw mine.
