### ISSUE TITLE
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 11836 tokens (11580 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

### ISSUE THREAD

**Issue by wen020** [langchain-ai/langchain#2333]
this is my code for hooking up an LLM to answer questions over a database(remote pg).
![image](https://user-images.githubusercontent.com/54690997/229476251-547d91b8-39a1-4f43-812b-ea01688a1261.png)

but find error:
![image](https://user-images.githubusercontent.com/54690997/229476819-bfd96216-2b41-496c-9f24-ac36e787205f.png)

Can anyone give me some advice to solve this problem？

**Comment by wen020** [comment]
> Take a look [#2133 (comment)](https://github.com/hwchase17/langchain/issues/2133#issuecomment-1491522064)

this a good job，but i dont know how to set reduce_k_below_max_tokens=True？Can you give me some examples

**Comment by FahriKhalid** [comment]
same issue here, have you solved ?

**Comment by Laisky** [comment]
> > Take a look [#2133 (comment)](https://github.com/hwchase17/langchain/issues/2133#issuecomment-1491522064)
> 
> this a good job，but i dont know how to set reduce_k_below_max_tokens=True？Can you give me some examples

here is a example:

```
chain_type_kwargs = {"prompt": prompt}
llm = ChatOpenAI(
    model_name="gpt-3.5-turbo", 
    temperature=0, 
    max_tokens=1000)  
chain = VectorDBQAWithSourcesChain.from_chain_type(
    llm=llm,
    vectorstore=index.store,
    return_source_documents=True,
    chain_type_kwargs=chain_type_kwargs,
    reduce_k_below_max_tokens=True,
)
```

<https://github.com/Laisky/HelloWorld/blob/master/py3/ailangchain/security.ipynb>

**Comment by MarabhaTheGreat** [comment]
> > > Take a look [#2133 (comment)](https://github.com/hwchase17/langchain/issues/2133#issuecomment-1491522064)
> > 
> > 
> > this a good job，but i dont know how to set reduce_k_below_max_tokens=True？Can you give me some examples
> 
> here is an example:
> 
> ```
> chain_type_kwargs = {"prompt": prompt}
> llm = ChatOpenAI(
>     model_name="gpt-3.5-turbo", 
>     temperature=0, 
>     max_tokens=1000)  
> chain = VectorDBQAWithSourcesChain.from_chain_type(
>     llm=llm,
>     vectorstore=index.store,
>     return_source_documents=True,
>     chain_type_kwargs=chain_type_kwargs,
>     reduce_k_below_max_tokens=True,
> )
> ```
> 
> https://github.com/Laisky/HelloWorld/blob/master/py3/ailangchain/security.ipynb

God Bless You

**Comment by shuvracse03** [comment]
f you are getting this error: openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4638 tokens (4382 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.   The solution is bellow[change your host port accordingly]. The trick is to include only tables that you want. I have given bellow an actual code snippet
================================================================
from langchain import SQLDatabaseChain
from sqlalchemy import create_engine
import os

os.environ["OPENAI_API_KEY"] = 'XXXXXX'

engine=create_engine('mysql+pymysql://admin:admin@localhost:3307/wordpress1')
include_tables=['wp_greetings']

db = SQLDatabase(engine, include_tables=include_tables) #This will only include a list of tables you want!!!
llm = OpenAI(temperature=0, verbose=True,max_tokens=1000)
db_chain = SQLDatabaseChain(llm=llm, database=db, verbose=True)

db_chain.run("Describe wp_greetings table")

**Comment by davidfan168** [comment]
I tried to limit the content length by using the following code:

```
llm = OpenAI(temperature=0, verbose=True, max_tokens=2000)

toolkit = SQLDatabaseToolkit(db=db, llm=llm, max_tokens_limit = 2000)

agent_executor = create_sql_agent(
    llm=OpenAI(temperature=0),
    toolkit=toolkit,
    verbose=True,
    reduce_k_below_max_tokens=True,
    max_tokens_limit = 2000
)
```

But that didn't seem to work. I still got the following error:

> InvalidRequestError: This model's maximum context length is 4097 tokens, however you requested 4151 tokens (3895 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.

Is this something wrong with the way I'm using the agent, or is this a bug in langchain? I am using sql agent on a large database so something may be wrong with how I'm using it.

**Comment by shuvracse03** [comment]
David, you can try including only the necessary table as I shown above. This will definitely decrease number of tokens

**Comment by davidfan168** [comment]
> David, you can try including only the necessary table as I shown above. This will definitely decrease number of tokens

Thanks for the suggestion!

I only have two tables in my database, but the tables have a ton of columns in them. In this case should I try to build my own agent with the ability to summarize tables?

**Comment by foshesss** [comment]
Hi! I'm encountering the same issue as David. Is there a method to track token usage as the program runs? I think it'd be very beneficial for me to monitor what is actually being used as a token and potentially finding reductions that way.
