### ISSUE TITLE
Langchain hallucinates and responds without actually calling the tool 

### ISSUE THREAD

**Issue by vivekojharhino** [langchain-ai/langchain#23365]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain.callbacks.base import BaseCallbackHandler

class CustomCallbackHandler(BaseCallbackHandler):
    def on_agent_finish(self, finish, **kwargs):
        if "Agent stopped due to iteration limit or time limit" in finish.return_values.get('output', ''):
            finish.return_values['output'] = "I'm having difficulty finding an answer. Please rephrase your question."

class ChatBot:
    def __init__(self, llm, tasks):
        self.llm = llm
        self.tasks = tasks
        self.agent = self._init_agent()

    def _init_agent(self):
        tools = get_tools()  # Function to get the tools
        agent = create_tool_calling_agent(llm=self.llm, tools=tools, callback_handler=CustomCallbackHandler())
        return agent

    def send_message(self, message):
        if not message.strip():
            return "You didn't ask a question. How can I assist you further?"

        response = self.agent.run(message)
        if "tool was called" in response:
            # Logically verify if the tool was actually called
            # This is where the inconsistency occurs
            print("Tool call indicated but not verified")
        return response

# Usage
llm = "mock_llm_instance"  # Replace with actual LLM instance
tasks = ["task1", "task2"]
chatbot = ChatBot(llm, tasks)
response = chatbot.send_message("Trigger tool call")
print(response)
```

### Description

The chatbot sometimes responds with a message indicating that a tool was called, even though the tool was not actually executed. This inconsistency suggests an issue within the Langchain library, particularly in the agent's tool-calling mechanism.
**Steps to Reproduce:**

1. Initiate a session with the chatbot.
2. Send a message that should trigger a tool call.
3. Observe the response: it sometimes indicates the tool was called, but in reality, it wasn't.

**Expected Behavior:**

1. When the chatbot indicates that a tool was called, the tool should actually be executed and return a result.

**Actual Behavior:**

1. The chatbot occasionally indicates that a tool was called without actually executing it.

### System Info

langchain==0.2.3
langchain-community==0.0.33
langchain-core==0.2.4
langchain-openai==0.1.8
langchain-text-splitters==0.2.0
langchainhub==0.1.15

**Comment by matteosantama** [comment]
How do you know the tool was not actually called?

**Comment by ccurme** [comment]
Hi @vivekojharhino, it looks like you imported `AgentExecutor` but did not use it in your example. `create_tool_calling_agent` will generate tool calls but does not execute the tools themselves. Please see the docs [here](https://python.langchain.com/v0.2/docs/how_to/agent_executor/#create-the-agent) for AgentExecutor, or check out our guide on pre-built langgraph agents [here](https://python.langchain.com/v0.2/docs/tutorials/agents/).

Closing but will re-open if I've misunderstood something.
