### ISSUE TITLE
DOC:Some questions about Execute SQL query

### ISSUE THREAD

**Issue by eshine996** [langchain-ai/langchain#23378]
### URL

https://python.langchain.com/v0.2/docs/tutorials/sql_qa/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

```python
from langchain_community.tools.sql_database.tool import QuerySQLDataBaseTool

execute_query = QuerySQLDataBaseTool(db=db)
write_query = create_sql_query_chain(llm, db)
chain = write_query l execute_query
chain.invoke({"question": "How many employees are there"})
```

The result generated by write_query is not entirely SQL, so execute_query will report an error.
My way :
```python
chain = write_query | extract_sql |execute_query
def extract_sql(txt: str) -> str:
    code_block_pattern = r'```sql(.*?)```'
    code_blocks = re.findall(code_block_pattern, txt, re.DOTALL)
    if code_blocks:
        return code_blocks[0]
    else:
        return ""
```

At the same time, prompt words will also be modified
Use the following format to return:
"""
```sql
write sql here
```
"""

**Comment by letcabound** [comment]
> ### URL
> https://python.langchain.com/v0.2/docs/tutorials/sql_qa/
> 
> ### Checklist
> * [x]  I added a very descriptive title to this issue.
> * [x]  I included a link to the documentation page I am referring to (if applicable).
> 
> ### Issue with current documentation:
> ```python
> from langchain_community.tools.sql_database.tool import QuerySQLDataBaseTool
> 
> execute_query = QuerySQLDataBaseTool(db=db)
> write_query = create_sql_query_chain(llm, db)
> chain = write_query l execute_query
> chain.invoke({"question": "How many employees are there"})
> ```
> 
> The result generated by write_query is not entirely SQL, so execute_query will report an error. My way :
> 
> ```python
> chain = write_query | extract_sql |execute_query
> def extract_sql(txt: str) -> str:
>     code_block_pattern = r'```sql(.*?)```'
>     code_blocks = re.findall(code_block_pattern, txt, re.DOTALL)
>     if code_blocks:
>         return code_blocks[0]
>     else:
>         return ""
> ```
> 
> At the same time, prompt words will also be modified Use the following format to return: """
> 
> ```sql
> write sql here
> ```
> 
> """
> 
> ### Idea or request for content:
> _No response_

modify your “extract_sql” method:
```
def extract_sql(txt: str) -> str:
    if "SQLQuery" in txt:
        code_block_pattern = r'```sql(.*?)```'
        code_blocks = re.findall(code_block_pattern, txt, re.DOTALL)
        if code_blocks:
            return code_blocks[0]
        else:
            return ""
    else:
        return txt
```
