### ISSUE TITLE
RecursiveCharacterTextSplitter uses regex value instead of original separator when merging and keep_separator is false

### ISSUE THREAD

**Issue by loperamos** [langchain-ai/langchain#23394]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain.text_splitter import RecursiveCharacterTextSplitter


if __name__ == "__main__":
    # Wrong behaviour, using \s instead of regular space
    splitter_keep = RecursiveCharacterTextSplitter(
        separators=[r"\s"],
        keep_separator=False,
        is_separator_regex=True,
        chunk_size=15,
        chunk_overlap=0,
        strip_whitespace=False)
    assert splitter_keep.split_text("Hello world")[0] == r"Hello\sworld"

    # Expected behaviour, keeping regular space
    splitter_no_keep = RecursiveCharacterTextSplitter(
        separators=[r"\s"],
        keep_separator=True,
        is_separator_regex=True,
        chunk_size=15,
        chunk_overlap=0,
        strip_whitespace=False)
    assert splitter_no_keep.split_text("Hello world")[0] == r"Hello world"
```

### Description

I am trying to use the `langchain` library to split a test using regex separators. I expect the output strings to contain the original separators, but what happens is that when using the `keep_separator` flag as `False` it uses the regex value instead of the original separator.

Possible code pointer where the problem might be coming from: [libs/text-splitters/langchain_text_splitters/character.py#L98](https://github.com/langchain-ai/langchain/blob/master/libs/text-splitters/langchain_text_splitters/character.py#L98)

### System Info

langchain==0.2.5
langchain-core==0.2.9
langchain-text-splitters==0.2.1

Platform: Apple M1 Pro
macOS: 14.5 (23F79)

python version: Python 3.12.3

**Comment by loperamos** [comment]
Adding some post clarification, I believe that the expected behaviour should be as the following code snippet, since I would expect we want to keep the chunk exactly as the original text. The keep separator flag should only affect when the separator is at the begining of a chunk.
```python
if __name__ == "__main__":
    # Wrong behaviour, using \s instead of regular space
    splitter_keep = RecursiveCharacterTextSplitter(
        separators=[r"\s"],
        keep_separator=False,
        is_separator_regex=True,
        chunk_size=15,
        chunk_overlap=0,
        strip_whitespace=False)
    assert splitter_keep.split_text("Hello world")[0] == r"Hello world"
```

**Comment by wulifu2hao** [comment]
I drafted a [fix](https://github.com/langchain-ai/langchain/compare/master...wulifu2hao:langchain:fix_separators) for it and will open an MR once I have the time to add some test cases tomorrow

**Comment by akshatsabavat** [comment]
Hey there, so I had a question regarding the text splitters I choose, 
I am working on making a policy ingestion pipeline that will specifically first classify chunks and then move a head to create rules out of it, using some prompts and pydantic objects I defined

Since I am kind of dealing with a lot of natural language documents what would be your reommendation

        recursive_splitter = RecursiveCharacterTextSplitter(
            chunk_size=800,   # max chars per chunk before splitting, bigger chunks better for rules
            chunk_overlap=0,  # No context preservation this is designed for rules
            separators=["\n\n", "\n", "●", ". "]  # splitting at paragraphs, new lines, bullets, sentences
        )

these are my settings right now

thanks a ton, in advance !!
