### ISSUE TITLE
openai.APIError: The model produced invalid content.

### ISSUE THREAD

**Issue by chrisyang-menos** [langchain-ai/langchain#23407]
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
@tool
def request_bing(query : str) -> str:
    """
    Searches the internet for additional information.
    Specifically useful when you need to answer questions about current events or the current state of the world.
    Prefer Content related to finance.
    """
    url = "https://api.bing.microsoft.com/v7.0/search"
    headers = {"Ocp-Apim-Subscription-Key": os.getenv("AZURE_KEY")}
    params = {"q": query}
    response = requests.get(url, headers=headers, params=params)
    response.raise_for_status()
    data = response.json()
    snippets_list = [result['snippet'] for result in data['webPages']['value']]
    snippets = "\n".join(snippets_list)
    return snippets
```

### Error Message and Stack Trace (if applicable)

```openai.APIError: The model produced invalid content.```

### Description

I'm using langchain ReAct agent + tools and starting from Jun 23rd seems to receive lots of exceptions.

```openai.APIError: The model produced invalid content.```

Suspecting that openai side changed something on function calling? Could you please shed some lights on it? 

I'm using gpt-4o as the llm. Bing search tool defined as above.

### System Info

langchain==0.2.4
langchain-community==0.2.4
langchain-core==0.2.6
langchain-openai==0.1.8
langchain-text-splitters==0.2.1

**Comment by ccurme** [comment]
Thanks @chrisyang-menos. Are you able to provide additional snippets to help debug? Ideally there is code a developer can run that immediately reproduces the error and does not require Azure credentials.

Would suggest the following:

- run `request_bing.invoke({"query": query})` to see what exactly is output by the tool.
- make a dummy/mock tool that hard-codes that output and returns it.
- incorporate that tool into whatever code you are using (e.g., ChatOpenAI, AgentExecutor, etc.) and paste it here.

**Comment by chrisyang-menos** [comment]
Thanks @ccurme. 

After digging into this a bit more and leveraging LangSmith, I found the following cause:

**Comment by CGamesPlay** [comment]
I also noticed this today, when using `gpt-4o`. I was using a stop sequence, and I found that removing the stop sequence fixed the error for me. This error does not happen with `gpt-3.5-turbo`. I suspect the problem is on openai's end.

**Comment by krishnakumar18** [comment]
I'm facing this issue too and the other threads where this issue is being discussed does not solve the issue for me. Any help is much appreciated. Thanks!

**Comment by brainframe-me** [comment]
Same here, randomly: openai.APIError: The model produced invalid content. Consider modifying your prompt if you are seeing this error persistently.

**Comment by chrisyang-menos** [comment]
Btw in my case, I was able to resolve the above issue by revising the tool definitions. In my experience, the following way would work well fairly consistently:

```
class SomeSearchTool(BaseTool):
    name = "..."
    description = "xxx"
    args_schema: Type[BaseModel] = SearchInput

    def _run()
        ...
```

**Comment by Lakshmi-Myestro** [comment]
Hi I recently faced the same error. I had a search tool associated with a researcher agent that is tasked with searching the vector database for a key phrase and then writing analysis based on the search results. I was able to get rid of it by changing the expected output from markdown format to json format :/
