### ISSUE TITLE
Token Size Limit Issue While calling FLAN-U2L using Langchain!

### ISSUE THREAD

**Issue by karndeepsingh** [langchain-ai/langchain#2347]
Hi,
I have been trying to use flan-u2l for my usecase using sequential chains. However, I am getting following token limit error even though FLAN-U2L has receptive of 2048 token size according to paper:
```ValueError: Error raised by inference API: Input validation error: `inputs` must have less than 1000 tokens. Given: 1112```
Please help me to resolve this issue. 
Is their anything I am missing to change the input token size of FLAN-U2L.?

**Comment by Veeeetzzzz** [comment]
It might be the API provider rate limiting you - you are correct, the model does have a token size of 2048 but there could still be a rate limit set by the provider. Are you running locally or are you able to share the end point you're using here?

Also worth posting the complete script you're using so we can debug/replicate.
