### ISSUE TITLE
ImportError: cannot import name '_set_config_context' from 'langchain_core.runnables.config'

### ISSUE THREAD

**Issue by Lin-jun-xiang** [langchain-ai/langchain#23517]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain.agents import AgentExecutor, create_openai_tools_agent
```

### Error Message and Stack Trace (if applicable)

```
ImportError: cannot import name '_set_config_context' from 'langchain_core.runnables.config'
```

### Description

Following the [streaming agent document](https://python.langchain.com/v0.1/docs/modules/agents/how_to/streaming/) code.

I get the error when import the modules.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.10
> langchain: 0.2.6
> langchain_community: 0.2.1
> langsmith: 0.1.82
> langchain_text_splitters: 0.2.0
> langchainhub: 0.1.20

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by Lin-jun-xiang** [comment]
After **update** the `langchain-core` to latest, the problem was fixed.

**Comment by FRAMEEE17** [comment]
> After **update** the `langchain-core` to latest, the problem was fixed.

Which version?
