### ISSUE TITLE
langchain_community.utilities.SQLDatabase: include_tables {...} not found in database

### ISSUE THREAD

**Issue by nick-youngblut** [langchain-ai/langchain#23672]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.utilities import SQLDatabase

host = config["DEFAULT"]["DB_HOST"]
port = config["DEFAULT"]["DB_PORT"]
db_name = config["DEFAULT"]["DB_NAME"]
username = config["DEFAULT"]["DB_USERNAME"]
password = os.getenv(config["DEFAULT"]["DB_PASSWORD"])

url = f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{db_name}"

include_tables = [
    "schema",
    "schema_field"
]

db = SQLDatabase.from_uri(url, include_tables=include_tables)
```

### Error Message and Stack Trace (if applicable)

```console
{
	"name": "ValueError",
	"message": "include_tables {'schema_field', 'schema'} not found in database",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[15], line 16
      9 url = f\"postgresql+psycopg2://{username}:{password}@{host}:{port}/{db_name}\"
     11 include_tables = [
     12     \"schema\",
     13     \"schema_field\"
     14 ]
---> 16 db = SQLDatabase.from_uri(url, include_tables=include_tables)

File ~/mambaforge/envs/langchain/lib/python3.12/site-packages/langchain_community/utilities/sql_database.py:135, in SQLDatabase.from_uri(cls, database_uri, engine_args, **kwargs)
    133 \"\"\"Construct a SQLAlchemy engine from URI.\"\"\"
    134 _engine_args = engine_args or {}
--> 135 return cls(create_engine(database_uri, **_engine_args), **kwargs)

File ~/mambaforge/envs/langchain/lib/python3.12/site-packages/langchain_community/utilities/sql_database.py:82, in SQLDatabase.__init__(self, engine, schema, metadata, ignore_tables, include_tables, sample_rows_in_table_info, indexes_in_table_info, custom_table_info, view_support, max_string_length, lazy_table_reflection)
     80     missing_tables = self._include_tables - self._all_tables
     81     if missing_tables:
---> 82         raise ValueError(
     83             f\"include_tables {missing_tables} not found in database\"
     84         )
     85 self._ignore_tables = set(ignore_tables) if ignore_tables else set()
     86 if self._ignore_tables:

ValueError: include_tables {'schema_field', 'schema'} not found in database"
}
```

### Description

Using:

```python
include_tables = [
    "schema$raw",
    "schema_field$raw"
]
```

instead of the fields without the `$raw` suffix works.

In this postgresql database, there are `$raw` version of each schema (e.g., `schema$raw` and `schema`). The `$raw` version includes all records, while the non-raw version contains the "cleaned up" tables.

It appears that `langchain_community.utilities.SQLDatabase` is not properly handling this situation. It only seems to detect the `$raw` schemas. 

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
> Python Version:  3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:35:20) [Clang 16.0.6 ]

Package Information
-------------------
> langchain_core: 0.2.1
> langchain: 0.2.1
> langchain_community: 0.0.38
> langsmith: 0.1.77
> langchain_groq: 0.1.5
> langchain_openai: 0.1.8
> langchain_text_splitters: 0.2.0
> langgraph: 0.0.69

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by keenborder786** [comment]
Have you double checked that tables: "schema", "schema_field" exists in your database

**Comment by nick-youngblut** [comment]
This issue appears to be caused by the use of `sqlalchemy.inspect` to list all of the tables. 

```python
from sqlalchemy import (
    create_engine,
    inspect
)

engine = create_engine(url)
inspector = inspect(engine)
inspector.get_table_names()
```

...only lists the `$raw` tables. All of the tables (raw and non-raw) are in the same database schema, so that is not the issue.

**Comment by nick-youngblut** [comment]
The issue is due to the fact that the non `$raw` versions of the tables are actually views (filtered versions of each `$raw` table). 

It would be helpful if `langchain_community.utilities.SQLDatabase` included support for table views. For instance, here's the SQLAlchemy code to list views:

```python
# Create SQLAlchemy engine
engine = create_engine(url)
 
# Create inspector
inspector = inspect(engine)
 
# Get all view names
view_names = inspector.get_view_names()
```
