### ISSUE TITLE
replace openai

### ISSUE THREAD

**Issue by tkone2018** [langchain-ai/langchain#2369]
can you tell me how to use local llm to replace the openai model,thanks, i can not find related codes

**Comment by Howardqlz** [comment]
Nice work and i have the same question. Is there a way to override  LLM function to use customize llms?

**Comment by 9cento** [comment]
+1

**Comment by 20001LastOrder** [comment]
I guess that you can inherit the base LLM model and implement the `_call` function. You can check an example [here](https://github.com/hwchase17/langchain/blob/c9ae0c58083bc5b26cea8510afd856b70457d5f4/langchain/llms/fake.py#L9) (This is a fake LLM used for testing purpose I believe )
