### ISSUE TITLE
'ChatGoogleGenerativeAI wrapper class doesn't work with google chat models such as 'chat-bison@002

### ISSUE THREAD

**Issue by Sayeenath** [langchain-ai/langchain#23714]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.agents import AgentExecutor, create_react_agent

from langchain.memory import ConversationBufferMemory

from langchain_core.tools import Tool

from langchain_core.prompts import PromptTemplate

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_community.tools import WikipediaQueryRun

from langchain_community.utilities import WikipediaAPIWrapper

from langchain_community.tools import YouTubeSearchTool

 

youtube =  YouTubeSearchTool()

wiki  = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())

tools = [

    Tool(

        name="youtube",

        func=youtube.run,

        description="Helps in getting youtube videos",

    ),

    Tool(

        name="wiki",

        func=wiki.run,

        description="Useful to search about a popular entity",

    )

]
tool_names = ["youtube","wiki"]
template = '''Answer the following questions as best you can. You have access to the following tools: 
{tools} 

Begin! 

Question: {input} 

Thought:{agent_scratchpad}

Action: the action to take, should be one of [{tool_names}]
'''

prompt = PromptTemplate (input_variables = ["tools","tool_names","input"] , template = template)

memory = ConversationBufferMemory(memory_key="chat_history")

llm= ChatGoogleGenerativeAI (model="chat-bison@002") 

agent=create_react_agent(llm=llm, tools=tools, prompt = prompt)

agent_chain = AgentExecutor(agent=agent, tools=tools, verbose=True, memory=memory)

agent_chain.invoke({"input": "Tell me something about USA"})

### Error Message and Stack Trace (if applicable)

> Entering new AgentExecutor chain...
---------------------------------------------------------------------------
InvalidArgument                           Traceback (most recent call last)
File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_google_genai/chat_models.py:178, in _chat_with_retry.<locals>._chat_with_retry(**kwargs)
    177 try:
--> 178     return generation_method(**kwargs)
    179 # Do not retry for these errors.

File ~/opt/anaconda3/lib/python3.11/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py:1122, in GenerativeServiceClient.stream_generate_content(self, request, model, contents, retry, timeout, metadata)
   1121 # Send the request.
-> 1122 response = rpc(
   1123     request,
   1124     retry=retry,
   1125     timeout=timeout,
   1126     metadata=metadata,
   1127 )
   1129 # Done; return the response.

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py:131, in _GapicCallable.__call__(self, timeout, retry, compression, *args, **kwargs)
    129     kwargs["compression"] = compression
--> 131 return wrapped_func(*args, **kwargs)

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py:293, in Retry.__call__.<locals>.retry_wrapped_func(*args, **kwargs)
    290 sleep_generator = exponential_sleep_generator(
    291     self._initial, self._maximum, multiplier=self._multiplier
    292 )
--> 293 return retry_target(
    294     target,
    295     self._predicate,
    296     sleep_generator,
    297     timeout=self._timeout,
    298     on_error=on_error,
    299 )

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py:153, in retry_target(target, predicate, sleep_generator, timeout, on_error, exception_factory, **kwargs)
    151 except Exception as exc:
    152     # defer to shared logic for handling errors
--> 153     _retry_error_helper(
    154         exc,
    155         deadline,
    156         sleep,
    157         error_list,
    158         predicate,
    159         on_error,
    160         exception_factory,
    161         timeout,
    162     )
    163     # if exception not raised, sleep before next attempt

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/retry/retry_base.py:212, in _retry_error_helper(exc, deadline, next_sleep, error_list, predicate_fn, on_error_fn, exc_factory_fn, original_timeout)
    207     final_exc, source_exc = exc_factory_fn(
    208         error_list,
    209         RetryFailureReason.NON_RETRYABLE_ERROR,
    210         original_timeout,
    211     )
--> 212     raise final_exc from source_exc
    213 if on_error_fn is not None:

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/retry/retry_unary.py:144, in retry_target(target, predicate, sleep_generator, timeout, on_error, exception_factory, **kwargs)
    143 try:
--> 144     result = target()
    145     if inspect.isawaitable(result):

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/timeout.py:120, in TimeToDeadlineTimeout.__call__.<locals>.func_with_timeout(*args, **kwargs)
    118     kwargs["timeout"] = max(0, self._timeout - time_since_first_attempt)
--> 120 return func(*args, **kwargs)

File ~/opt/anaconda3/lib/python3.11/site-packages/google/api_core/grpc_helpers.py:174, in _wrap_stream_errors.<locals>.error_remapped_callable(*args, **kwargs)
    173 except grpc.RpcError as exc:
--> 174     raise exceptions.from_grpc_error(exc) from exc

InvalidArgument: 400 Request contains an invalid argument.

The above exception was the direct cause of the following exception:

ChatGoogleGenerativeAIError               Traceback (most recent call last)
Cell In[30], line 70
     66 agent=create_react_agent(llm=llm, tools=tools, prompt = prompt)
     68 agent_chain = AgentExecutor(agent=agent, tools=tools, verbose=True, memory=memory)
---> 70 agent_chain.invoke({"input": "Tell me something about USA"})

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/chains/base.py:166, in Chain.invoke(self, input, config, **kwargs)
    164 except BaseException as e:
    165     run_manager.on_chain_error(e)
--> 166     raise e
    167 run_manager.on_chain_end(outputs)
    169 if include_run_info:

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/chains/base.py:156, in Chain.invoke(self, input, config, **kwargs)
    153 try:
    154     self._validate_inputs(inputs)
    155     outputs = (
--> 156         self._call(inputs, run_manager=run_manager)
    157         if new_arg_supported
    158         else self._call(inputs)
    159     )
    161     final_outputs: Dict[str, Any] = self.prep_outputs(
    162         inputs, outputs, return_only_outputs
    163     )
    164 except BaseException as e:

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py:1433, in AgentExecutor._call(self, inputs, run_manager)
   1431 # We now enter the agent loop (until it returns something).
   1432 while self._should_continue(iterations, time_elapsed):
-> 1433     next_step_output = self._take_next_step(
   1434         name_to_tool_map,
   1435         color_mapping,
   1436         inputs,
   1437         intermediate_steps,
   1438         run_manager=run_manager,
   1439     )
   1440     if isinstance(next_step_output, AgentFinish):
   1441         return self._return(
   1442             next_step_output, intermediate_steps, run_manager=run_manager
   1443         )

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py:1139, in AgentExecutor._take_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
   1130 def _take_next_step(
   1131     self,
   1132     name_to_tool_map: Dict[str, BaseTool],
   (...)
   1136     run_manager: Optional[CallbackManagerForChainRun] = None,
   1137 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
   1138     return self._consume_next_step(
-> 1139         [
   1140             a
   1141             for a in self._iter_next_step(
   1142                 name_to_tool_map,
   1143                 color_mapping,
   1144                 inputs,
   1145                 intermediate_steps,
   1146                 run_manager,
   1147             )
   1148         ]
   1149     )

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py:1139, in <listcomp>(.0)
   1130 def _take_next_step(
   1131     self,
   1132     name_to_tool_map: Dict[str, BaseTool],
   (...)
   1136     run_manager: Optional[CallbackManagerForChainRun] = None,
   1137 ) -> Union[AgentFinish, List[Tuple[AgentAction, str]]]:
   1138     return self._consume_next_step(
-> 1139         [
   1140             a
   1141             for a in self._iter_next_step(
   1142                 name_to_tool_map,
   1143                 color_mapping,
   1144                 inputs,
   1145                 intermediate_steps,
   1146                 run_manager,
   1147             )
   1148         ]
   1149     )

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py:1167, in AgentExecutor._iter_next_step(self, name_to_tool_map, color_mapping, inputs, intermediate_steps, run_manager)
   1164     intermediate_steps = self._prepare_intermediate_steps(intermediate_steps)
   1166     # Call the LLM to see what to do.
-> 1167     output = self.agent.plan(
   1168         intermediate_steps,
   1169         callbacks=run_manager.get_child() if run_manager else None,
   1170         **inputs,
   1171     )
   1172 except OutputParserException as e:
   1173     if isinstance(self.handle_parsing_errors, bool):

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain/agents/agent.py:398, in RunnableAgent.plan(self, intermediate_steps, callbacks, **kwargs)
    390 final_output: Any = None
    391 if self.stream_runnable:
    392     # Use streaming to make sure that the underlying LLM is invoked in a
    393     # streaming
   (...)
    396     # Because the response from the plan is not a generator, we need to
    397     # accumulate the output into final output and return that.
--> 398     for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
    399         if final_output is None:
    400             final_output = chunk

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:2882, in RunnableSequence.stream(self, input, config, **kwargs)
   2876 def stream(
   2877     self,
   2878     input: Input,
   2879     config: Optional[RunnableConfig] = None,
   2880     **kwargs: Optional[Any],
   2881 ) -> Iterator[Output]:
-> 2882     yield from self.transform(iter([input]), config, **kwargs)

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:2869, in RunnableSequence.transform(self, input, config, **kwargs)
   2863 def transform(
   2864     self,
   2865     input: Iterator[Input],
   2866     config: Optional[RunnableConfig] = None,
   2867     **kwargs: Optional[Any],
   2868 ) -> Iterator[Output]:
-> 2869     yield from self._transform_stream_with_config(
   2870         input,
   2871         self._transform,
   2872         patch_config(config, run_name=(config or {}).get("run_name") or self.name),
   2873         **kwargs,
   2874     )

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1867, in Runnable._transform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   1865 try:
   1866     while True:
-> 1867         chunk: Output = context.run(next, iterator)  # type: ignore
   1868         yield chunk
   1869         if final_output_supported:

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:2831, in RunnableSequence._transform(self, input, run_manager, config, **kwargs)
   2828     else:
   2829         final_pipeline = step.transform(final_pipeline, config)
-> 2831 for output in final_pipeline:
   2832     yield output

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1163, in Runnable.transform(self, input, config, **kwargs)
   1160 final: Input
   1161 got_first_val = False
-> 1163 for ichunk in input:
   1164     # The default implementation of transform is to buffer input and
   1165     # then call stream.
   1166     # It'll attempt to gather all input into a single chunk using
   1167     # the `+` operator.
   1168     # If the input is not addable, then we'll assume that we can
   1169     # only operate on the last chunk,
   1170     # and we'll iterate until we get to the last chunk.
   1171     if not got_first_val:
   1172         final = ichunk

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:4784, in RunnableBindingBase.transform(self, input, config, **kwargs)
   4778 def transform(
   4779     self,
   4780     input: Iterator[Input],
   4781     config: Optional[RunnableConfig] = None,
   4782     **kwargs: Any,
   4783 ) -> Iterator[Output]:
-> 4784     yield from self.bound.transform(
   4785         input,
   4786         self._merge_configs(config),
   4787         **{**self.kwargs, **kwargs},
   4788     )

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1181, in Runnable.transform(self, input, config, **kwargs)
   1178             final = ichunk
   1180 if got_first_val:
-> 1181     yield from self.stream(final, config, **kwargs)

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:265, in BaseChatModel.stream(self, input, config, stop, **kwargs)
    258 except BaseException as e:
    259     run_manager.on_llm_error(
    260         e,
    261         response=LLMResult(
    262             generations=[[generation]] if generation else []
    263         ),
    264     )
--> 265     raise e
    266 else:
    267     run_manager.on_llm_end(LLMResult(generations=[[generation]]))

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:245, in BaseChatModel.stream(self, input, config, stop, **kwargs)
    243 generation: Optional[ChatGenerationChunk] = None
    244 try:
--> 245     for chunk in self._stream(messages, stop=stop, **kwargs):
    246         if chunk.message.id is None:
    247             chunk.message.id = f"run-{run_manager.run_id}"

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_google_genai/chat_models.py:833, in ChatGoogleGenerativeAI._stream(self, messages, stop, run_manager, tools, functions, safety_settings, tool_config, generation_config, **kwargs)
    811 def _stream(
    812     self,
    813     messages: List[BaseMessage],
   (...)
    822     **kwargs: Any,
    823 ) -> Iterator[ChatGenerationChunk]:
    824     request = self._prepare_request(
    825         messages,
    826         stop=stop,
   (...)
    831         generation_config=generation_config,
    832     )
--> 833     response: GenerateContentResponse = _chat_with_retry(
    834         request=request,
    835         generation_method=self.client.stream_generate_content,
    836         **kwargs,
    837         metadata=self.default_metadata,
    838     )
    839     for chunk in response:
    840         _chat_result = _response_to_result(chunk, stream=True)

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_google_genai/chat_models.py:196, in _chat_with_retry(generation_method, **kwargs)
    193     except Exception as e:
    194         raise e
--> 196 return _chat_with_retry(**kwargs)

File ~/opt/anaconda3/lib/python3.11/site-packages/tenacity/__init__.py:289, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    287 @functools.wraps(f)
    288 def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289     return self(f, *args, **kw)

File ~/opt/anaconda3/lib/python3.11/site-packages/tenacity/__init__.py:379, in Retrying.__call__(self, fn, *args, **kwargs)
    377 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378 while True:
--> 379     do = self.iter(retry_state=retry_state)
    380     if isinstance(do, DoAttempt):
    381         try:

File ~/opt/anaconda3/lib/python3.11/site-packages/tenacity/__init__.py:314, in BaseRetrying.iter(self, retry_state)
    312 is_explicit_retry = fut.failed and isinstance(fut.exception(), TryAgain)
    313 if not (is_explicit_retry or self.retry(retry_state)):
--> 314     return fut.result()
    316 if self.after is not None:
    317     self.after(retry_state)

File ~/opt/anaconda3/lib/python3.11/concurrent/futures/_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/opt/anaconda3/lib/python3.11/concurrent/futures/_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File ~/opt/anaconda3/lib/python3.11/site-packages/tenacity/__init__.py:382, in Retrying.__call__(self, fn, *args, **kwargs)
    380 if isinstance(do, DoAttempt):
    381     try:
--> 382         result = fn(*args, **kwargs)
    383     except BaseException:  # noqa: B902
    384         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File ~/opt/anaconda3/lib/python3.11/site-packages/langchain_google_genai/chat_models.py:190, in _chat_with_retry.<locals>._chat_with_retry(**kwargs)
    187         raise ValueError(error_msg)
    189 except google.api_core.exceptions.InvalidArgument as e:
--> 190     raise ChatGoogleGenerativeAIError(
    191         f"Invalid argument provided to Gemini: {e}"
    192     ) from e
    193 except Exception as e:
    194     raise e

ChatGoogleGenerativeAIError: Invalid argument provided to Gemini: 400 Request contains an invalid argument.

### Description

I also tried with different langchain wrapper classes for google models. Also tried with different models. When I tried the same with 'GoogleGenerativeAI' class, I get the following error 

AttributeError                            Traceback (most recent call last)
[<ipython-input-7-a2422220c061>](https://ogjiokqjqun-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240627-060121_RC00_647236509#) in <cell line: 70>()
     68 agent_chain = AgentExecutor(agent=agent, tools=tools, verbose=True, memory=memory)
     69 
---> 70 agent_chain.invoke({"input": "Tell me something about SRK"})

25 frames
[/usr/local/lib/python3.10/dist-packages/langchain_google_genai/llms.py](https://ogjiokqjqun-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240627-060121_RC00_647236509#) in _completion_with_retry(prompt, is_gemini, stream, **kwargs)
     82         try:
     83             if is_gemini:
---> 84                 return llm.client.generate_content(
     85                     contents=prompt,
     86                     stream=stream,

AttributeError: module 'google.generativeai' has no attribute 'generate_content'

### System Info

python version 3.11.8
langchain -0.2.5
langchain_community-0.2.5
langchain_core-0.2.9
langchain-google-gen-ai-1.0.7

**Comment by etveritas** [comment]
how to use
