### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.agents.agent_types'

### ISSUE THREAD

**Issue by ddkwing** [langchain-ai/langchain#2379]
when I follow the guide of agent part to run the code below:
---------------------------------------------------------------------------
from langchain.agents import load_tools
from langchain.agents import initialize_agent
**from langchain.agents.agent_types import AgentType**
from langchain.llms import OpenAI

...
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
...

---------------------------------------------------------------------------
I encounted the error of:
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)
[/var/folders/bv/x8bqw0hd5hz7fdsvcdl9f43r0000gn/T/ipykernel_83990/3945525270.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/bv/x8bqw0hd5hz7fdsvcdl9f43r0000gn/T/ipykernel_83990/3945525270.py) in 
      1 from langchain.agents import load_tools
      2 from langchain.agents import initialize_agent
----> 3 from langchain.agents.agent_types import AgentType
      4 from langchain.llms import OpenAI
      5 

ModuleNotFoundError: No module named 'langchain.agents.agent_types'

**Comment by ddkwing** [comment]
remove 'from langchain.agents.agent_types import AgentType' and change to 'zero-shot-react-description', solved. 
maybe the guide is outdated?

**Comment by FrankChu0229** [comment]
same here, langchain version:0.0.130

code:

```
from langchain import OpenAI, SerpAPIWrapper
from langchain.agents import initialize_agent, Tool
from langchain.agents.agent_types import AgentType

llm = OpenAI(temperature=0)
search = SerpAPIWrapper()
tools = [
    Tool(
        name="Intermediate Answer",
        func=search.run,
        description="useful for when you need to ask with search"
    )
]

self_ask_with_search = initialize_agent(tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True)
self_ask_with_search.run("What is the hometown of the reigning men's U.S. Open champion?")
```

error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 3
      1 from langchain import OpenAI, SerpAPIWrapper
      2 from langchain.agents import initialize_agent, Tool
----> 3 from langchain.agents.agent_types import AgentType
      5 llm = OpenAI(temperature=0)
      6 search = SerpAPIWrapper()

ModuleNotFoundError: No module named 'langchain.agents.agent_types'

```

**Comment by theMistletoe** [comment]
I've also encountered the same error.

**Comment by yicixin** [comment]
Try using Python 3.10 as the project interpreter.

**Comment by alexxriv** [comment]
> > Try using Python 3.10 as the project interpreter.
> 
> This fixed the issue! Thank you :)

Im using python 3.10.10 ans still not working

**Comment by alexxriv** [comment]
I upgraded the library and it got fixed. Forgot there are updates like every hour  🤦‍♂️. `pip3 install --upgrade langchain`

**Comment by Zerolzj** [comment]
You can check if the version of langchain >= 0.0.131, which add the `AgentType`

**Comment by Zerolzj** [comment]
> ## when I follow the guide of agent part to run the code below:
> from langchain.agents import load_tools from langchain.agents import initialize_agent **from langchain.agents.agent_types import AgentType** from langchain.llms import OpenAI
> 
> ... agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True) ...
> 
> ## I encounted the error of:
> ModuleNotFoundError Traceback (most recent call last) [/var/folders/bv/x8bqw0hd5hz7fdsvcdl9f43r0000gn/T/ipykernel_83990/3945525270.py](https://file+.vscode-resource.vscode-cdn.net/var/folders/bv/x8bqw0hd5hz7fdsvcdl9f43r0000gn/T/ipykernel_83990/3945525270.py) in 1 from langchain.agents import load_tools 2 from langchain.agents import initialize_agent ----> 3 from langchain.agents.agent_types import AgentType 4 from langchain.llms import OpenAI 5
> 
> ModuleNotFoundError: No module named 'langchain.agents.agent_types'

You can check if the version of langchain >= 0.0.131, which add the `AgentType`
