### ISSUE TITLE
partner[chroma]: Not able to load persisted collection without calling `from_documents`  

### ISSUE THREAD

**Issue by spike-spiegel-21** [langchain-ai/langchain#23797]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

If I create a vectorstore with:
```python
from langchain_community.embeddings import FakeEmbeddings
from langchain_chroma.vectorstores import Chroma
vectorstore = Chroma.from_documents(documents=splits, embedding = FakeEmbeddings(size=1352), collection_name="colm", persist_directory="my_dir")
```
The only way to retrieve the persisted collection from `my_dir` is:
```python
vectorstore = Chroma.from_documents(documents=splits, embedding = FakeEmbeddings(size=1352), collection_name="colm")
```
OR

```python
vectorstore = Chroma.from_text(text=..., embedding = FakeEmbeddings(size=1352), collection_name="colm")
```
Related issues:
https://github.com/langchain-ai/langchain/issues/22361
https://github.com/langchain-ai/langchain/issues/20866
https://github.com/langchain-ai/langchain/issues/19807#issuecomment-2028610882

### Description

I want dedicated `classmethod` just like this:
https://github.com/langchain-ai/langchain/blob/27aa4d38bf93f3eef7c46f65cc0d0ef3681137eb/libs/partners/qdrant/langchain_qdrant/vectorstores.py#L1351
that returns me an instance of `Chroma` without inserting any texts

### System Info

langchain-chroma                         0.1.1

**Comment by RafaelXokito** [comment]
From my understanding, you are trying to reload a persisted Chroma collection without the need of having the documents.
If so, you can get a VectorStore instance from the persisted directory like this:
```python
vectorstore = Chroma(
        collection_name="colm",
        embedding_function=FakeEmbeddings(),
        persist_directory="my_dir",
    )
```

Take into account that all these attributes are optional.

**Comment by spike-spiegel-21** [comment]
> From my understanding, you are trying to reload a persisted Chroma collection without the need of having the documents. If so, you can get a VectorStore instance from the persisted directory like this:
> 
> ```python
> vectorstore = Chroma(
>         collection_name="colm",
>         embedding_function=FakeEmbeddings(),
>         persist_directory="my_dir",
>     )
> ```
> 
> Take into account that all these attributes are optional.

Hi @RafaelXokito , Sorry I have missed your comment on the issue before raising PR. Yes, you are right, user can create a client from a persisted directory by directly instantiating the `class Chroma`. But my attempt is to give the user a dedicated function, and since you have mentioned that attributes are optional, `from_existing_collection` method #23854 will prompt user to provide the necessary attributes. 

Do quote me If I am wrong on this, will appreciate your feedback :) Thank you!

**Comment by RafaelXokito** [comment]
> Hi @RafaelXokito , Sorry I have missed your comment on the issue before raising PR. Yes, you are right, user can create a client from a persisted directory by directly instantiating the `class Chroma`. But my attempt is to give the user a dedicated function, and since you have mentioned that attributes are optional, `from_existing_collection` method #23854 will prompt user to provide the necessary attributes.
> 
> Do quote me If I am wrong on this, will appreciate your feedback :) Thank you!

I see your point about offering users a dedicated class method to create a vectorstore from an existing collection.

However, this scenario is already well-documented in the LangChain documentation. Specifically, the process of creating a Chroma vectorstore from an existing collection, including saving to disk, is covered in detail [here](https://python.langchain.com/v0.2/docs/integrations/vectorstores/chroma/#basic-example-including-saving-to-disk).

Given that this use case is documented, users can follow the provided examples to achieve the desired outcome without the need for an additional method. By leveraging the existing documentation, we can maintain a streamlined API and avoid potential redundancy.

Please let me know your feedback on this.
