### ISSUE TITLE
Get warning about browser instead of real info in WebBaseLoader

### ISSUE THREAD

**Issue by loveis98** [langchain-ai/langchain#23813]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.document_loaders import WebBaseLoader

loader = WebBaseLoader('https://m.vk.com/support?category_id=2')
data = loader.load()
print(data[0])

### Error Message and Stack Trace (if applicable)

Your browser is out of dateThis may cause VK to work slowly or experience errors.Update your browser or install one of the following:ChromeOperaFirefox

### Description

I'm trying to parse all data from "'https://m.vk.com/support" (including info from sublinks, to construct RAG). But see the output with the content: "Your browser is out of dateThis may cause VK to work slowly or experience errors.Update your browser or install one of the following:ChromeOperaFirefox"

### System Info

langchain==0.2.6
langchain-community==0.2.6
langchain-core==0.2.11
langchain-text-splitters==0.2.2
windows 
python 3.10

**Comment by wenngong** [comment]
I have tried to add UA header, but still the same error.

`from langchain_community.document_loaders import WebBaseLoader

loader = WebBaseLoader('https://m.vk.com/support?category_id=2', 
                       header_template={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
                                        "Sec-Ch-Ua-Mobile":"?0",
                                        "Sec-Ch-Ua-Platform":"macOS"})
data = loader.load()
print(data)`
