### ISSUE TITLE
DOC: remove_node typo in runnables/ graph

### ISSUE THREAD

**Issue by mathias-aparicio** [langchain-ai/langchain#23861]
### URL

https://api.python.langchain.com/en/latest/runnables/langchain_core.runnables.graph.Graph.html

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The code of the remove_node in https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/runnables/graph.py is as follow 
```python
 def remove_node(self, node: Node) -> None:
        """Remove a node from the graphm and all edges connected to it."""
        self.nodes.pop(node.id)
        self.edges = [
            edge
            for edge in self.edges
            if edge.source != node.id and edge.target != node.id
        ]
``` graph is spelled graphm

### Idea or request for content:

```python
 def remove_node(self, node: Node) -> None:
        """Remove a node from the **graph** and all edges connected to it."""
        self.nodes.pop(node.id)
        self.edges = [
            edge
            for edge in self.edges
            if edge.source != node.id and edge.target != node.id
        ]
``` 
Should replace *graphm* with *graph*

**Comment by gsreejith123** [comment]
**URL:** 
https://github.com/langchain-ai/langchain/pull/23910#event-13407839115

Typo has been fixed(grahm-->graph)
