### ISSUE TITLE
LangChain x HuggingFace - Using ChatHuggingFace requires hf token for local TGI using locally saved model

### ISSUE THREAD

**Issue by SMAntony** [langchain-ai/langchain#23872]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace

# This part works like a charm
llm = HuggingFaceEndpoint(
    name="mistral",
    endpoint_url=classifier_agent_config.endpoint_url,
    task="text-generation",
    **classifier_agent_config.generation_config
)

# This part raises error
chat_llm = ChatHuggingFace(llm=llm, verbose=True)
```

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
\.venv\Lib\site-packages\huggingface_hub\utils\_errors.py:304, in hf_raise_for_status(response, endpoint_name)
    303 try:
--> 304     response.raise_for_status()
    305 except HTTPError as e:

\.venv\Lib\site-packages\requests\models.py:1024, in Response.raise_for_status(self)
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/whoami-v2

The above exception was the direct cause of the following exception:

HfHubHTTPError                            Traceback (most recent call last)
\.venv\Lib\site-packages\huggingface_hub\hf_api.py:1397, in HfApi.whoami(self, token)
   1396 try:
-> 1397     hf_raise_for_status(r)
   1398 except HTTPError as e:

\.venv\Lib\site-packages\huggingface_hub\utils\_errors.py:371, in hf_raise_for_status(response, endpoint_name)
    369 # Convert `HTTPError` into a `HfHubHTTPError` to display request information
    370 # as well (request id and/or server error message)
--> 371 raise HfHubHTTPError(str(e), response=response) from e

HfHubHTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/whoami-v2 (Request ID: Root=1-66869944-058281c36301f9472614deeb;255a1059-9b6e-47ab-bcfc-3c0bced7baa0)

Invalid username or password.

The above exception was the direct cause of the following exception:

HTTPError                                 Traceback (most recent call last)
Cell In[31], line 1
----> 1 chat_llm = ChatHuggingFace(llm=llm)

\.venv\Lib\site-packages\langchain_huggingface\chat_models\huggingface.py:169, in ChatHuggingFace.__init__(self, **kwargs)
    165 super().__init__(**kwargs)
    167 from transformers import AutoTokenizer  # type: ignore[import]
--> 169 self._resolve_model_id()
    171 self.tokenizer = (
    172     AutoTokenizer.from_pretrained(self.model_id)
    173     if self.tokenizer is None
    174     else self.tokenizer
    175 )

\.venv\Lib\site-packages\langchain_huggingface\chat_models\huggingface.py:295, in ChatHuggingFace._resolve_model_id(self)
    291 """Resolve the model_id from the LLM's inference_server_url"""
    293 from huggingface_hub import list_inference_endpoints  # type: ignore[import]
--> 295 available_endpoints = list_inference_endpoints("*")
    296 if _is_huggingface_hub(self.llm) or (
    297     hasattr(self.llm, "repo_id") and self.llm.repo_id
    298 ):
    299     self.model_id = self.llm.repo_id

\.venv\Lib\site-packages\huggingface_hub\hf_api.py:7081, in HfApi.list_inference_endpoints(self, namespace, token)
   7079 # Special case: list all endpoints for all namespaces the user has access to
   7080 if namespace == "*":
-> 7081     user = self.whoami(token=token)
   7083     # List personal endpoints first
   7084     endpoints: List[InferenceEndpoint] = list_inference_endpoints(namespace=self._get_namespace(token=token))

\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py:114, in validate_hf_hub_args.<locals>._inner_fn(*args, **kwargs)
    111 if check_use_auth_token:
    112     kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=has_token, kwargs=kwargs)
--> 114 return fn(*args, **kwargs)

\.venv\Lib\site-packages\huggingface_hub\hf_api.py:1399, in HfApi.whoami(self, token)
   1397     hf_raise_for_status(r)
   1398 except HTTPError as e:
-> 1399     raise HTTPError(
   1400         "Invalid user token. If you didn't pass a user token, make sure you "
   1401         "are properly logged in by executing `huggingface-cli login`, and "
   1402         "if you did pass a user token, double-check it's correct.",
   1403         request=e.request,
   1404         response=e.response,
   1405     ) from e
   1406 return r.json()

HTTPError: Invalid user token. If you didn't pass a user token, make sure you are properly logged in by executing `huggingface-cli login`, and if you did pass a user token, double-check it's correct.

### Description

* I am trying to use langchain_huggingface library to connect to a TGI instance locally and as expected it connects and I am able to infer the same. But when converting HuggingFaceEndpoint to ChatHuggingFace, it raises error requesting user token to be provided.

### System Info

langchain-huggingface = "0.0.3"
langchain-core=="0.2.11"
platform: windows (TGI is run in a ec2 linux instance)
Python 3.12.2

**Comment by keenborder786** [comment]
you need to provide `huggingfacehub_api_token` to the `HuggingFaceEndpoint` or set up the following environment variable: `HUGGINGFACEHUB_API_TOKEN`

**Comment by SMAntony** [comment]
Why is it required if I am hosting a local model using TGI docker container?

**Comment by SMAntony** [comment]
I am closing this issue as I was able to fix it by providing "model_id" when wrapping llm as chat llm. 

llm = HuggingFaceEndpoint(
    name="mistral",
    endpoint_url=classifier_agent_config.endpoint_url,
    task="text-generation",
    **classifier_agent_config.generation_config
)

chat_llm = ChatHuggingFace(llm=llm, model_id=model_id, verbose=True)
