### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/chatbot/> Missing documentation.

### ISSUE THREAD

**Issue by aliasgar-m** [langchain-ai/langchain#23892]
### URL

https://python.langchain.com/v0.2/docs/tutorials/chatbot/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The documentation refers to "ChatMessageHistory" while this particular page does not exist in the documentation.
![Screenshot from 2024-07-04 20-54-25](https://github.com/langchain-ai/langchain/assets/56577852/34e9b560-9dfe-4637-a6cf-c4f1d9c7d407)

The documentation referred to here is present in the prompt section: https://python.langchain.com/v0.2/docs/tutorials/chatbot/#prompt-templates

**Comment by robert-cronin** [comment]
I could be mistaken but it looks like ChatMessageHistory is a named export of the InMemoryChatMessageHistory class. The latter exists in the API documentation: https://api.python.langchain.com/en/latest/chat_history/langchain_core.chat_history.InMemoryChatMessageHistory.html

We might fix this and related issues by changing the examples to use this class.

**Comment by eyurtsev** [comment]
best import is here:  `from langchain_core.chat_history import InMemoryChatMessageHistory`
