### ISSUE TITLE
DOC: <Issue related to /v0.1/docs/modules/memory/chat_messages/> 404 on ChatMessageHistory link

### ISSUE THREAD

**Issue by robert-cronin** [langchain-ai/langchain#23902]
### URL

https://python.langchain.com/v0.1/docs/modules/memory/chat_messages/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

![Screenshot from 2024-07-05 19-48-46](https://github.com/langchain-ai/langchain/assets/8540764/8fccce5c-7b7e-488d-b0e2-f71da736bbfa)

Similar to: https://github.com/langchain-ai/langchain/issues/23892

### Idea or request for content:

N/A

**Comment by YassinNouh21** [comment]
this should be solved @robert-cronin

**Comment by YassinNouh21** [comment]
i checked the website and it works

**Comment by robert-cronin** [comment]
> i checked the website and it works 

HI @YassinNouh21,

It is this link in particular that is 404: https://api.python.langchain.com/en/latest/chat_history/langchain_core.chat_history.ChatMessageHistory.html

It is from the ChatMessageHistory link below the code snippets. I think it's because the name is just an alias for InMemoryChatMessageHistory and the auto linking will try to link the name directly
