### ISSUE TITLE
when run method “with_structured_output”, output print nothing??  code was copied from langchain doc.

### ISSUE THREAD

**Issue by letcabound** [langchain-ai/langchain#23901]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
```
from langchain_openai import ChatOpenAI
from typing import Optional
from langchain_core.pydantic_v1 import BaseModel, Field

class Joke(BaseModel):
    """Joke to tell user."""

    setup: str = Field(description="The setup of the joke")
    punchline: str = Field(description="The punchline to the joke")
    rating: Optional[int] = Field(description="How funny the joke is, from 1 to 10")

llm = ChatOpenAI(model="gpt-3.5-turbo")
structured_llm = llm.with_structured_output(Joke)

result = structured_llm.invoke("Tell me a joke about cats")
print(result)  # result: None
```
### Error Message and Stack Trace (if applicable)

Nothing

### Description

i try to langchain's method: with_structured_output(), https://python.langchain.com/v0.2/docs/how_to/structured_output/,
but find the output is None.

### System Info

python == 3.9.19
langchain == 0.2.6
langchain_core == 0.2.10
langchain-openai == 0.1.13

**Comment by eyurtsev** [comment]
Unable to reproduce with the following environment


System Information
------------------
> OS:  Linux
> OS Version:  #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2
> Python Version:  3.9.6 (default, Sep 26 2023, 21:46:56) 
[GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.2.10
> langchain_openai: 0.1.13
