### ISSUE TITLE
ggml-alpaca-7b-q4.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])

### ISSUE THREAD

**Issue by ShoufaChen** [langchain-ai/langchain#2392]
When loading the converted `ggml-alpaca-7b-q4.bin` model, I met the error:

```
>>> llm = LlamaCpp(model_path="ggml-alpaca-7b-q4.bin")
llama_model_load: loading model from 'ggml-alpaca-7b-q4.bin' - please wait ...
ggml-alpaca-7b-q4.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])
        you most likely need to regenerate your ggml files
        the benefit is you'll get 10-100x faster load times
        see https://github.com/ggerganov/llama.cpp/issues/91
        use convert-pth-to-ggml.py to regenerate from original pth
        use migrate-ggml-2023-03-30-pr613.py if you deleted originals
llama_init_from_file: failed to load model
```

**Comment by ShoufaChen** [comment]
Hi @abetlen 

Thanks for your help.  I believe https://github.com/hwchase17/langchain/pull/2393 could help.

**Comment by akash-ravikumar** [comment]
migrate-ggml-2023-03-30-pr613.py does not seem to exist on this repo: https://github.com/ggerganov/llama.cpp.git

**Comment by jav-ed** [comment]
I also can't find it

**Comment by Diyago** [comment]
doest start converting 
```
> PS C:\Users\dex\Desktop\gpt4free\voice_chatbot\migrate_models\llama.cpp> python3 convert.py ggml-vic7b-uncensored-q5_1.bin ggml-vic7b-uncensored-q5_1_new.bin

Python
```

**Comment by am0oma** [comment]
python convert x.bin --outfile x_new.bin
or 
python3 convert x.bin --outfile x_new.bin

> doest start converting
> 
> ```
> > PS C:\Users\dex\Desktop\gpt4free\voice_chatbot\migrate_models\llama.cpp> python3 convert.py ggml-vic7b-uncensored-q5_1.bin ggml-vic7b-uncensored-q5_1_new.bin
> 
> Python
> ```

**Comment by AlekzNet** [comment]
I'm having the same issue. Converting did not help. 

```
./main -m models/7B/ggml-model-q4_0_new.bin
main: seed = 1686525413
llama_model_load: loading model from 'models/7B/ggml-model-q4_0_new.bin' - please wait ...
llama_model_load: invalid model file 'models/7B/ggml-model-q4_0_new.bin' (bad magic)
main: failed to load model from 'models/7B/ggml-model-q4_0_new.bin'
```

**Comment by vinitran** [comment]
i met the same bug like @AlekzNet , anyone has solution ? i've run convert.py successfully then i run ./main -m models/7B/ggml-model-q4_0_new.bin but it show bad magic
