### ISSUE TITLE
Validation error for FastEmbedEmbeddings - extra fields not permitted

### ISSUE THREAD

**Issue by saikaryekar** [langchain-ai/langchain#24039]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
%pip install --upgrade --quiet  fastembed
%pip install --upgrade --quiet langchain_community
%pip install --upgrade --quiet langchain 

from langchain_community.embeddings.fastembed import FastEmbedEmbeddings 
embeddings = FastEmbedEmbeddings()
```

### Error Message and Stack Trace (if applicable)

`---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[<ipython-input-8-152b947eb52c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 embeddings = FastEmbedEmbeddings()

[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for FastEmbedEmbeddings
_model
  extra fields not permitted (type=value_error.extra)

### Description

Unable to Instantie FastEmbed model. It raises validation error for extra fields while none are provided. Issue seems to be arising from pydantic. 

Code was working well on langchain == 0.2.6 and langchain-core == 0.2.11. Tried installing older versions but still getting the error.

Followed the tutorial here: https://python.langchain.com/v0.2/docs/integrations/text_embedding/fastembed/

### System Info

langchain==0.2.7
langchain-community==0.2.7
langchain-core==0.2.12
langchain-text-splitters==0.2.2

Google-colab
Python 3.10.12

**Comment by eyurtsev** [comment]
Could you check if downgrading to  `langchain-community==0.2.6`  helps solve the issue?

**Comment by saikaryekar** [comment]
Nope, downgrading to ```langchain-community==0.2.6``` does not solve the issue.

**Comment by JonathanLoscalzo** [comment]
Same here, on colab
```
!pip -q install langchain langchain_community pypdf fastembed chromadb

from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
# supported models: https://qdrant.github.io/fastembed/examples/Supported_Models/
model_name = "thenlper/gte-large"
embedding_model = FastEmbedEmbeddings(model_name=model_name)

langchain_community.__version__, fastembed.__version__ # ('0.2.7', '0.3.3')
```

**Comment by JonathanLoscalzo** [comment]
For versions
`langchain_community.__version__, fastembed.__version__ # ('0.2.6', '0.3.2')`
it works, just a workaround @saikaryekar

**Comment by saikaryekar** [comment]
@JonathanLoscalzo downgrading both lanchain_community==0.2.6 and fastembed==0.3.2 worked, Thanks! I
They should fix issues for compatibility with newer version as well!

**Comment by wenngong** [comment]
same issue.

**Comment by eyurtsev** [comment]
Could someone help isolate whether the issue comes from a change in langchain_community or from fastembed?

**Comment by saikaryekar** [comment]
@eyurtsev the issue comes from the new release of langchain_community v0.2.7 which was released 2 days ago.

**Comment by Likhith904** [comment]
> For versions `langchain_community.__version__, fastembed.__version__ # ('0.2.6', '0.3.2')` it works, just a workaround @saikaryekar

thanks for that it works 
i dont know why there is no proper documentation when they release a new version

**Comment by Shyamnath-Sankar** [comment]
th

> For versions `langchain_community.__version__, fastembed.__version__ # ('0.2.6', '0.3.2')` it works, just a workaround @saikaryekar

Thanks Man This finally works thanks very much

**Comment by Anush008** [comment]
Hey @eyurtsev. Could you please take a look at #24462 that resolves this?

**Comment by Fernando7181** [comment]
weird, im getting the same error here

**Comment by Anush008** [comment]
@Fernando7181, can you update the Langchain community package to the latest version?

**Comment by Fernando7181** [comment]
> @Fernando7181, can you update the Langchain community package to the latest version?
![error](https://github.com/user-attachments/assets/791d1efd-d670-473c-ba32-4c6f3491cf6c)
sorry, its not the right topic im just new to it. Im getting this issue but not sure how to solve it
