### ISSUE TITLE
community: AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'

### ISSUE THREAD

**Issue by ZhangShenao** [langchain-ai/langchain#24053]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os

import dotenv
from langchain_community.chat_message_histories import PostgresChatMessageHistory
from langchain_core.messages import AIMessage, HumanMessage
from zhipuai import ZhipuAI

SYSTEM_PROMPT_TEMPLATE = '''你是一个具有记忆功能的AI助手，请根据结合用户的当前提问，和之前的历史聊天记录，生成准确的回答。你们的对话全部采用中文。
下面是你们的历史聊天记录：
[历史聊天记录开始]

{chat_history}

[历史聊天记录结束]
'''

MODEL_NAME = 'glm-4-air'
dotenv.load_dotenv()
client = ZhipuAI(api_key=os.getenv("ZHIPUAI_API_KEY"))

chat_message_history = PostgresChatMessageHistory(
    connection_string='postgresql://root:12345678@127.0.0.1:5432/llm_ops',
    table_name='llm_ops_chat_history',
    session_id="llm_ops")

while True:
    query = input('Human：')
    if 'bye' == query:
        print('bye bye~')
        break

    system_prompt = SYSTEM_PROMPT_TEMPLATE.format(chat_history=chat_message_history)

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {'role': 'system', 'content': system_prompt},
            {"role": "user", "content": query},
        ],
        stream=True,
    )

    output = ''
    print('AI：', end='', flush=True)
    for chunk in response:
        content = chunk.choices[0].delta.content
        print(content, end='', flush=True)
        output += content
    print()

    # save chat message 
    chat_message_history.add_messages([HumanMessage(query), AIMessage(output)])

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/zhangshenao/Desktop/llm-ops/llm-ops-backend/langchain_study/7-记忆功能实现/3.使用PostgresChatMessageHistory组件保存聊天历史.py", line 35, in <module>
    chat_message_history = PostgresChatMessageHistory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/_api/deprecation.py", line 203, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_community/chat_message_histories/postgres.py", line 44, in __init__
    import psycopg
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/__init__.py", line 9, in <module>
    from . import pq  # noqa: F401 import early to stabilize side effects
    ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 118, in <module>
    import_from_libpq()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/psycopg/pq/__init__.py", line 104, in import_from_libpq
    PGcancelConn = module.PGcancelConn
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'psycopg_binary.pq' has no attribute 'PGcancelConn'
Exception ignored in: <function PostgresChatMessageHistory.__del__ at 0x1038f4900>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_community/chat_message_histories/postgres.py", line 97, in __del__
    if self.cursor:
       ^^^^^^^^^^^
AttributeError: 'PostgresChatMessageHistory' object has no attribute 'cursor'

### Description

I want to use `PostgresChatMessageHistory` to persist my chat message history into postgresql, but it occurs errors! 

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
> Python Version:  3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.2.12
> langchain: 0.2.7
> langchain_community: 0.2.7
> langsmith: 0.1.82
> langchain_openai: 0.1.14
> langchain_text_splitters: 0.2.2

**Comment by WittmannF** [comment]
The header of this class mentions that it is deprecated and to use https://github.com/langchain-ai/langchain-postgres instead:

```

class PostgresChatMessageHistory(BaseChatMessageHistory):
    """Chat message history stored in a Postgres database.

    **DEPRECATED**: This class is deprecated and will be removed in a future version.

    Use the `PostgresChatMessageHistory` implementation in `langchain_postgres`.
    """

    def __init__(
        self,
        session_id: str,
        connection_string: str = DEFAULT_CONNECTION_STRING,
        table_name: str = "message_store",
...
```

**Comment by ZhangShenao** [comment]
> The header of this class mentions that it is deprecated and to use https://github.com/langchain-ai/langchain-postgres instead:
> 
> ```python
> class PostgresChatMessageHistory(BaseChatMessageHistory):
>     """Chat message history stored in a Postgres database.
> 
>     **DEPRECATED**: This class is deprecated and will be removed in a future version.
> 
>     Use the `PostgresChatMessageHistory` implementation in `langchain_postgres`.
>     """
> 
>     def __init__(
>         self,
>         session_id: str,
>         connection_string: str = DEFAULT_CONNECTION_STRING,
>         table_name: str = "message_store",
> ...
> ```

Got it. Thanks for answering.
