### ISSUE TITLE
How to know which tool(s) been used on `agent_chain.run`?

### ISSUE THREAD

**Issue by mzhadigerov** [langchain-ai/langchain#2407]
Hi! After I create an agent using `initialize_agent` , I can call the agent using `agent.run`. 

I can see the steps on the terminal e.g.:

```
Thought: Do I need to use a tool? Yes
Action: Index A,
Action Input: ....
```

but in the end, the `run` function returns only a final output (string). How can I get the intermediate steps as well? Especially, whether the agent used a tool or not?

**Comment by dxv2k** [comment]
+1, I'm still trying to figure out a nice way to do this

**Comment by dxv2k** [comment]
Wow, really nice approach. Do you have any output that I can see? Thanks a lot.

> Hi @dxv2k ! Can you check out this thread? I was able to implement the functionality using the method proposed in the thread:
> 
> [2068](https://github.com/hwchase17/langchain/issues/2068)

**Comment by mzhadigerov** [comment]
@dxv2k Sorry man, I'm out of my pc now, but can send an example output later.

**Comment by dxv2k** [comment]
Thanks, man, I'll try to implement it tomorrow. 
I have a side question, does it also store the input of each tool used?

**Comment by mzhadigerov** [comment]
@dxv2k you mean context from documents? I don't think so. At least, I could not find it

**Comment by KeshavSingh29** [comment]
I was trying to have the same functionality as well. 
Why dont you try to get the raw response from agent (its a dict) and parse its intermediate steps to know the tool as well as tool_input.

**Comment by tajpouria** [comment]
+1
