### ISSUE TITLE
core: Fix @tool typing

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#24089]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Type hints for `@tool` decorator are incorrect, which causes downstream type-checking errors. For example:
```python
from langchain_core.tools import tool, StructuredTool

@tool
def multiply(a: int, b: int) -> int:
    """multiply two ints"""
    return a * b

tool_: StructuredTool = multiply
```

leads to the following mypy errors:
```pycon
error: Incompatible types in assignment (expression has type "Callable[..., Any]", variable has type "StructuredTool")  [assignment]
```

**Comment by eyurtsev** [comment]
This can just be BaseTool
