### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/text_embedding/baidu_qianfan_endpoint/>

### ISSUE THREAD

**Issue by macoli** [langchain-ai/langchain#24104]
### URL

https://python.langchain.com/v0.2/docs/integrations/text_embedding/baidu_qianfan_endpoint/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I run the sample code and get an error.How to solve it？

Operating environment:
python 3.10
langchain-community      0.2.7
qianfan                  0.4.0.1

Run the code:
`import os

from langchain_community.embeddings import QianfanEmbeddingsEndpoint

os.environ["QIANFAN_AK"] = "xxx"
os.environ["QIANFAN_SK"] = "xxx"

embed = QianfanEmbeddingsEndpoint()
res = embed.embed_documents(["hi", "world"])
print(res)`

Error message:
`Traceback (most recent call last):
  File "/llm-example/langchain/test.py", line 9, in <module>
    embed = QianfanEmbeddingsEndpoint()
  File "/llm-example/langchain/.venv/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for QianfanEmbeddingsEndpoint
qianfan_ak
  str type expected (type=type_error.str)
qianfan_sk
  str type expected (type=type_error.str)
`

**Comment by Qiuzizhao** [comment]
the same problem!!! but, my conda have many virtual environment, if i change to a special old one, it can run, i do not know why. although the same python version3.10.11, it can not run. i guess that is the version problem between baidu.qianfan and langchain

**Comment by HrOice** [comment]
+1
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1537, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/prisoner/PycharmProjects/llm/langchain/start_pdf.py", line 36, in <module>
    embeddings = QianfanEmbeddingsEndpoint()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for QianfanEmbeddingsEndpoint
qianfan_ak
  str type expected (type=type_error.str)
qianfan_sk
  str type expected (type=type_error.str)
