### ISSUE TITLE
OutputFixingParser,KeyError

### ISSUE THREAD

**Issue by LoveStory-TS** [langchain-ai/langchain#24105]
### URL

https://python.langchain.com/v0.2/docs/how_to/output_parser_fixing/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

langchain 0.2.6
from langchain.output_parsers import (OutputFixingParser)
fixing_parser = OutputFixingParser.from_llm(parser= parser, llm= ChatOpenAI())

an error：
KeyError: "Input to PromptTemplate is missing variables {'completion'}.  Expected: ['completion', 'error', 'instructions'] Received: ['instructions', 'input', 'error']"

**Comment by ancherl** [comment]
I also faced same issue as above with langchain version = 0.3.12, is there anyone could help here?
