### ISSUE TITLE
Maximum Context Length Exceeded Due to Base64-Encoded Image in Prompt

### ISSUE THREAD

**Issue by tusharraskar** [langchain-ai/langchain#24107]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

llm = VLLMOpenAI(
    openai_api_key="EMPTY",
    openai_api_base=api_base,
    model_name="microsoft/Phi-3-vision-128k-instruct",
    model_kwargs={"stop": ["."]}
)

image_path = "invoice_data_images/Screenshot 2024-05-02 160946_page_1.png"
with open(image_path, "rb") as image_file:
    image_base64 = base64.b64encode(image_file.read()).decode("utf-8")

prompt_1 = "Give me the invoice date from the given image."
messages = [
    HumanMessage(
        content=[
            {"type": "text", "text": prompt_1},
            {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{image_base64}"}}
        ]
    )
]

response = llm.invoke(messages)
print(response)

### Error Message

{
    "name": "BadRequestError",
    "message": "Error code: 400 - {'object': 'error', 'message': 'This model's maximum context length is 8192 tokens. However, you requested 254457 tokens (254201 in the messages, 256 in the completion). Please reduce the length of the messages or completion.', 'type': 'BadRequestError', 'param': None, 'code': 400}"
}

### Description

I hosted VLLM on an EC2 instance to extract text data from images using the Phi-3 Vision model. The model is hosted with the following command:

python3 -m vllm.entrypoints.openai.api_server --port 8000 --model microsoft/Phi-3-vision-128k-instruct --trust-remote-code --dtype=half --max_model_len=8192

When running the code, I encounter a BadRequestError due to exceeding the maximum context length. The error message indicates that the total number of tokens requested is 254457, which far exceeds the model's limit of 8192 tokens.

The base64-encoded image is being considered part of the prompt, significantly increasing the token count and leading to the context length issue. 
Even if the model's context length were 128k tokens, including a base64-encoded image in the prompt would always exceed the model's limit.

# Expected Behavior
The model should process the image without considering the base64 string as part of the prompt token count, thereby avoiding the context length issue.

### System Info

langchain==0.2.7
langchain-community==0.2.7
langchain-core==0.2.12
langchain-text-splitters==0.2.2

**Comment by lizaibeim** [comment]
same problem there

**Comment by killian-mahe** [comment]
Hi, I have the same problem. When I use the OpenAI SDK, my request works without a context length error, but when I use the Langchain VLLMOpenAI class, I get a maximum length error too.
