### ISSUE TITLE
DOC: Page Not Found

### ISSUE THREAD

**Issue by Nano-base** [langchain-ai/langchain#24112]
### URL

https://python.langchain.com/v0.2/docs/concepts/#tools

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Document says: 
To use an existing pre-built tool, see [here](https://python.langchain.com/v0.2/docs/concepts/docs/integrations/tools/) for a list of pre-built tools.

But the link page does not exist.

**Comment by RafaelXokito** [comment]
I'm not into the langchain docs, neither to mdx files.
But from my understanding the current code redirects to "https://python.langchain.com/v0.2/docs/concepts/docs/integrations/tools/" which should redirect to "https://python.langchain.com/v0.2/docs/integrations/tools/".

The code bellow might work, but I was not able to test it

```mdx
To use an existing pre-built tool, see [here](../../docs/integrations/tools/) for a list of pre-built tools.
```

**Comment by RafaelXokito** [comment]
@ccurme please give your feedback on this.

**Comment by RafaelXokito** [comment]
Check the PR preview [here](https://langchain-git-fork-rafaelxokito-fix-resolve-in-8558c4-langchain.vercel.app/v0.2/docs/concepts/#tools)
