### ISSUE TITLE
Milvus fails on `add_documents()` with new `VectorStore.upsert()` method

### ISSUE THREAD

**Issue by amiigas** [langchain-ai/langchain#24116]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import logging
logging.basicConfig(level=logging.DEBUG)

from langchain_core.documents import Document
from langchain_core.embeddings import FakeEmbeddings
from langchain_milvus import Milvus


milvus_vector_store = Milvus(
    index_params = {
        "metric_type": "COSINE",
        "index_type": "HNSW",
        "params": {"M": 8, "efConstruction": 64},
    },
    embedding_function=FakeEmbeddings(size=100),
    collection_name="test_langchain",
    connection_args={...}
)

docs = [
    Document(page_content='First document content.'),
    Document(page_content='Second document content.'),
]
ids = [
    "id_1",
    "id_2"
]

result = milvus_vector_store.add_documents(ids=ids, documents=docs)
print(result)
```

### Error Message and Stack Trace (if applicable)

```bash
DEBUG:langchain_milvus.vectorstores.milvus:No documents to upsert.
Traceback (most recent call last):
  File "/Users/amiigas/langchain_milvus_test.py", line 32, in <module>
    result = milvus_vector_store.add_documents(ids=ids, documents=docs)
  File "/Users/amiigas/.venv/lib/python3.10/site-packages/langchain_core/vectorstores/base.py", line 463, in add_documents
    return self.upsert(documents_, **kwargs)["succeeded"]
TypeError: 'NoneType' object is not subscriptable
```

### Description

 * Trying to add documents to Milvus vector store using `add_documents()` method.
 * Expecting to successfully add documents and see returned ids `["id_1", "id_2"]` as a method result
 * Instead method returns `None` which then throws `TypeError` after trying to access `succeeded` key
 

`VectorStore` passes `documents_` to `Milvus.upsert()` as a positional arg, which results in `documents=None` and returning `None` early

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:13:18 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6030
> Python Version:  3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.2.13
> langchain: 0.2.7
> langsmith: 0.1.84
> langchain_milvus: 0.1.1
> langchain_text_splitters: 0.2.2

**Comment by radheradhe01** [comment]
The solution for this issue is that you can update the langchain_milvus package to version 0.1.2 or later.

The bug you encountered was fixed in version 0.1.2 of langchain_milvus, which was released on July 7, 2024. You can update the package using pip:
           pip install langchain_milvus==0.1.2
Or, if you want to get the latest version:
           pip install langchain_milvus --upgrade

After updating the package, your code should work as expected, and the add_documents method should return the expected result instead of None.

**Comment by AaaCabbage** [comment]
@radheradhe01 I encountered the same problem, but I used `pdm update langchain_milvus` and it told me that 0.1.1 was the latest version.

**Comment by 50ajmalkhan** [comment]
Add this langchain-core==0.2.5 in your package and see magic

**Comment by eyurtsev** [comment]
Created by a change I made in the base astraction. I'll patch langchain_milvus in a bit for now please revert `langchain-core <= 0.2.10`

**Comment by LukaszCmielowski** [comment]
Is there any ETA to have new release with that fix ?. Thanks.

**Comment by efriis** [comment]
released!
