### ISSUE TITLE
QianfanLLMEndpoint ak/sk SecretStr ERROR

### ISSUE THREAD

**Issue by freshchen** [langchain-ai/langchain#24126]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
QianfanLLMEndpoint(qianfan_ak="xxx",qianfan_sk="xxx")
```

### Error Message and Stack Trace (if applicable)

pydantic.v1.error_wrappers.ValidationError: 2 validation errors for QianfanLLMEndpoint
qianfan_ak
  str type expected (type=type_error.str)
qianfan_sk

### Description

qianfan_ak qianfan_sk pydantic check error SecretStr ！= str

### System Info

langchain==0.2.7
langchain-community==0.2.7
langchain-core==0.2.13
langchain-mongodb==0.1.6
langchain-openai==0.1.15
langchain-text-splitters==0.2.2

python 3.11
mac m3

**Comment by eyurtsev** [comment]
Should be fixed in next release, feel free to verify the test on master

**Comment by pegasus2004** [comment]
make the same erro

**Comment by pegasus2004** [comment]
Traceback (most recent call last):
  File "shuju.py", line 69, in <module>
    embedding = QianfanEmbeddingsEndpoint(qianfan_ak=wenxin_api_key, qianfan_sk=wenxin_secret_key)
  File "/home/zhangmeng/.conda/envs/llm/lib/python3.8/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for QianfanEmbeddingsEndpoint
qianfan_ak
  str type expected (type=type_error.str)
qianfan_sk
  str type expected (type=type_error.str) why? i still confused

**Comment by scutlzc** [comment]
I have same problem on it

**Comment by zxjhellow2** [comment]
怎么解决的？
