### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/text_embedding/google_generative_ai/>

### ISSUE THREAD

**Issue by Ziadabdelsalam** [langchain-ai/langchain#24148]
### URL

https://python.langchain.com/v0.2/docs/integrations/text_embedding/google_generative_ai/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

the documentation states that i can use GoogleGenerativeAIEmbeddings from langchain-google-genai but i got an error that i can not import it form the library 
link for documentation page:
https://python.langchain.com/v0.2/docs/integrations/text_embedding/google_generative_ai/

**Comment by sahilkumarvaghasiya** [comment]
Ensure that the langchain-google-genai package is installed correctly.Sometimes, packages may not have the modules you expect. Check the contents of the langchain-google-genai package to see if GoogleGenerativeAIEmbeddings is actually included.
