### ISSUE TITLE
LlamaCpp Streaming Support

### ISSUE THREAD

**Issue by abetlen** [langchain-ai/langchain#2415]
Hi all, just wanted to see if there was anyone interested in helping me integrate streaming completion support for the new `LlamaCpp` class.

The base `Llama` class supports streaming at the moment and I purposely designed it to behave almost identically to `openai.Completion.create(..., stream=True)` [see docs](https://abetlen.github.io/llama-cpp-python/#llama_cpp.llama.Llama.__call__). I took a look at the `OpenAI` class for reference but was a little overwhelmed trying to see how I would adapt that to the `LlamaCpp` class (probably because of all the network code).

**Comment by winglian** [comment]
the llama cpp python bindings doesn't return back until the response has finished generating. short of modifying the underlying llama.cpp and python bindings, you could pass the prompt to the llama.cpp binary and parse the streamed text from stdout and then make sure to use yield and not return when using a generator.

**Comment by abetlen** [comment]
> the llama cpp python bindings doesn't return back until the response has finished generating. short of modifying the underlying llama.cpp and python bindings, you could pass the prompt to the llama.cpp binary and parse the streamed text from stdout and then make sure to use yield and not return when using a generator.

Hey @winglian have you tried `stream=True`, that should give you an iterator of tokens that starts as soon as the prompt is processed (may take some time), if that's not working please [open an issue](https://github.com/abetlen/llama-cpp-python)

**Comment by Richielly** [comment]
Tente streaming=True

**Comment by muhammadfhadli1453** [comment]
I think now we can do this
```
llm = LlamaCpp(
        model_path=model_path,
        n_gpu_layers=59,
        n_batch=512,
        max_tokens=512,
        n_ctx=2048,
        f16_kv=True
    )
for text in llm.stream(prompt, stop=["Q:"]):
        print(text)
```

**Comment by weissenbacherpwc** [comment]
any experiences on how to enable Streaming with llamacpp and FastAPI/Langserve?
