### ISSUE TITLE
llm_chain generates answers for questions I did not ask

### ISSUE THREAD

**Issue by soleimanian** [langchain-ai/langchain#2418]
I use this HF pipeline and **vicuna** or **alpaca** as a model:
`pipe = pipeline(
    "text-generation",
    model=model, 
    tokenizer=tokenizer, 
    max_length=256,
    temperature=1.0,
    top_p=0.95,
    repetition_penalty=1.2
)

llm = HuggingFacePipeline(pipeline=pipe)

from langchain import PromptTemplate, LLMChain

template = """Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction: 
{instruction}

Answer:"""

prompt = PromptTemplate(template=template, input_variables=["instruction"])

llm_chain = LLMChain(prompt=prompt, 
                     llm=llm
                     )

question = "What is the capital of England?"

print(llm_chain.run(question))`

**Here is the answer:**
London
### Assistant: The capital of

**What is wrong with my codes?**

**Comment by iRanadheer** [comment]
which model are you using?

**Comment by TobyGE** [comment]
> which model are you using?

From the output, it should be alpaca or even llama.

**Comment by soleimanian** [comment]
I tried vicuna and alpaca
