### ISSUE TITLE
OllamaEmbeddings returns error 400 Bad Request when embedding documents 

### ISSUE THREAD

**Issue by rafheros** [langchain-ai/langchain#24190]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
 const loader = new PDFLoader("./sample-docs/layout-parser-paper-fast.pdf");
    
    const docs = await loader.load();
  
    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 200,
    });
    
    const splits = await textSplitter.splitDocuments(docs);

    const model = new ChatOllama({
      model: 'mistral',
      temperature: 0,
      baseUrl: 'http://localhost:11433',
      useMMap: true,
    });
  
    const embeddings = new OllamaEmbeddings({model:"mxbai-embed-large", baseUrl: 'http://localhost:11434', onFailedAttempt: e => {throw e}, requestOptions: {
      useMMap: false,
      
    }});
  
    const vectorstore = await ElasticVectorSearch.fromDocuments(
      splits,
      embeddings,
      clientArgs,
    );
    
    const retriever = vectorstore.asRetriever();

    const prompt = await pull<ChatPromptTemplate>("rlm/rag-prompt");
    
    
    const ragChainFromDocs = RunnableSequence.from([
      {
        context: retriever.pipe(formatDocumentsAsString),
        question: new RunnablePassthrough(),
      },
      prompt,
      model,
      new StringOutputParser(),
    ]);

    const stream = await ragChainFromDocs.stream(
      messages.map(message =>
        message.role == 'user'
          ? new HumanMessage(message.content)
          : new AIMessage(message.content),
      ),
    )
```

### Error Message and Stack Trace (if applicable)

DEBUG [update_slots] slot released | n_cache_tokens=211 n_ctx=512 n_past=211 n_system_tokens=0 slot_id=0 task_id=217 tid="139849943545728" timestamp=1720804402 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=36972 status=200 tid="139849797445184" timestamp=1720804402
[GIN] 2024/07/12 - 14:13:22 | 200 |  1.418235476s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:22.804-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:22.804-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:22.804-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:22.808-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=220 tid="139849943545728" timestamp=1720804402
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=221 tid="139849943545728" timestamp=1720804402
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=222 tid="139849943545728" timestamp=1720804402
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=222 tid="139849943545728" timestamp=1720804402
DEBUG [update_slots] slot released | n_cache_tokens=189 n_ctx=512 n_past=189 n_system_tokens=0 slot_id=0 task_id=222 tid="139849943545728" timestamp=1720804404 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=36976 status=200 tid="139849789052480" timestamp=1720804404
[GIN] 2024/07/12 - 14:13:24 | 200 |  1.277078941s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:24.084-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:24.084-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:24.084-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:24.087-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=225 tid="139849943545728" timestamp=1720804404
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=226 tid="139849943545728" timestamp=1720804404
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=227 tid="139849943545728" timestamp=1720804404
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=227 tid="139849943545728" timestamp=1720804404
DEBUG [update_slots] slot released | n_cache_tokens=165 n_ctx=512 n_past=165 n_system_tokens=0 slot_id=0 task_id=227 tid="139849943545728" timestamp=1720804405 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=36976 status=200 tid="139849789052480" timestamp=1720804405
[GIN] 2024/07/12 - 14:13:25 | 200 |  1.116597159s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:25.203-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:25.203-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:25.203-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:25.206-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=230 tid="139849943545728" timestamp=1720804405
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=231 tid="139849943545728" timestamp=1720804405
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=232 tid="139849943545728" timestamp=1720804405
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=232 tid="139849943545728" timestamp=1720804405
DEBUG [update_slots] slot released | n_cache_tokens=202 n_ctx=512 n_past=202 n_system_tokens=0 slot_id=0 task_id=232 tid="139849943545728" timestamp=1720804406 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=36982 status=200 tid="139849780659776" timestamp=1720804406
[GIN] 2024/07/12 - 14:13:26 | 200 |  1.398312778s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:26.604-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:26.604-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:26.604-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:26.607-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=235 tid="139849943545728" timestamp=1720804406
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=236 tid="139849943545728" timestamp=1720804406
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=237 tid="139849943545728" timestamp=1720804406
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=237 tid="139849943545728" timestamp=1720804406
DEBUG [update_slots] slot released | n_cache_tokens=187 n_ctx=512 n_past=187 n_system_tokens=0 slot_id=0 task_id=237 tid="139849943545728" timestamp=1720804407 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=33576 status=200 tid="139849935148608" timestamp=1720804407
[GIN] 2024/07/12 - 14:13:27 | 200 |  1.235134467s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:27.842-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:27.842-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:27.842-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:27.846-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=240 tid="139849943545728" timestamp=1720804407
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=241 tid="139849943545728" timestamp=1720804407
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=242 tid="139849943545728" timestamp=1720804407
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=242 tid="139849943545728" timestamp=1720804407
DEBUG [update_slots] slot released | n_cache_tokens=205 n_ctx=512 n_past=205 n_system_tokens=0 slot_id=0 task_id=242 tid="139849943545728" timestamp=1720804409 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=33576 status=200 tid="139849935148608" timestamp=1720804409
[GIN] 2024/07/12 - 14:13:29 | 200 |  1.439000676s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:29.284-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:29.284-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:29.284-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
time=2024-07-12T14:13:29.287-03:00 level=DEBUG source=sched.go:507 msg="evaluating already loaded" model=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=245 tid="139849943545728" timestamp=1720804409
DEBUG [process_single_task] slot data | n_idle_slots=1 n_processing_slots=0 task_id=246 tid="139849943545728" timestamp=1720804409
DEBUG [launch_slot_with_data] slot is processing task | slot_id=0 task_id=247 tid="139849943545728" timestamp=1720804409
DEBUG [update_slots] kv cache rm [p0, end) | p0=0 slot_id=0 task_id=247 tid="139849943545728" timestamp=1720804409
DEBUG [update_slots] slot released | n_cache_tokens=202 n_ctx=512 n_past=202 n_system_tokens=0 slot_id=0 task_id=247 tid="139849943545728" timestamp=1720804410 truncated=false
DEBUG [log_server_request] request | method="POST" params={} path="/embedding" remote_addr="127.0.0.1" remote_port=33590 status=200 tid="139849918363200" timestamp=1720804410
[GIN] 2024/07/12 - 14:13:30 | 200 |  1.358210814s |       127.0.0.1 | POST     "/api/embeddings"
time=2024-07-12T14:13:30.645-03:00 level=DEBUG source=sched.go:348 msg="context for request finished"
time=2024-07-12T14:13:30.645-03:00 level=DEBUG source=sched.go:281 msg="runner with non-zero duration has gone idle, adding timer" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d duration=5m0s
time=2024-07-12T14:13:30.645-03:00 level=DEBUG source=sched.go:299 msg="after processing request finished event" modelPath=/home/rafheros/.ollama/models/blobs/sha256-819c2adf5ce6df2b6bd2ae4ca90d2a69f060afeb438d0c171db57daa02e39c3d refCount=0
[GIN] 2024/07/12 - 14:13:33 | 400 |      65.664µs |       127.0.0.1 | POST     "/api/embeddings"

### Description

I'm trying to embend PDF splited documents on a vector store but the embeddings from OllamaEmbedding only returns 400 Bad Request on it's final request, thas a strage behaviour because counting the requests we have plus 1 final requests that always return this status even if the others are 200.

### System Info

langchain v0.2.18
npm 20
wsl
next.js

**Comment by D4RK5IDE** [comment]
I have the same bug. Is there any solution ?
