### ISSUE TITLE
Add a template for Issues and PRs

### ISSUE THREAD

**Issue by letmerecall** [langchain-ai/langchain#2424]
## Describe the issue

Right now we don't have any template for PR and Issues to provide a structure for their description.

## Expected behaviour

Have a template for PR and Issues.

## What are the benefits of having a template for PR and Issues?

- Provides consistency in the description.
- It saves time of a contributor by providing a starting point to fill up the description.
- With a good template, it's clear for the reader to understand about the issue and the work which has been done in a PR.
- It'll improve the process of triaging for maintainers.

**Comment by rosedalerk** [comment]
This is a good idea. I was thinking the same thing.
