### ISSUE TITLE
No module named 'langchain.transformers'

### ISSUE THREAD

**Issue by mustangs0786** [langchain-ai/langchain#24251]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am trying to use LLMGraphTransformer
Despite upgrading everything still facing this issue
`from langchain.transformers import LLMGraphTransformer
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 2
      1 from langchain.llms import OpenAI
----> 2 from langchain.transformers import LLMGraphTransformer
      3 import getpass
      4 import os

ModuleNotFoundError: No module named 'langchain.transformers'`

### Description

I am trying to use LLMGraphTransformer
Despite upgrading everything still facing this issue
`from langchain.transformers import LLMGraphTransformer
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 2
      1 from langchain.llms import OpenAI
----> 2 from langchain.transformers import LLMGraphTransformer
      3 import getpass
      4 import os

ModuleNotFoundError: No module named 'langchain.transformers'`

### System Info

I am trying to use LLMGraphTransformer
Despite upgrading everything still facing this issue
`from langchain.transformers import LLMGraphTransformer
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[6], line 2
      1 from langchain.llms import OpenAI
----> 2 from langchain.transformers import LLMGraphTransformer
      3 import getpass
      4 import os

ModuleNotFoundError: No module named 'langchain.transformers'`

**Comment by tibor-reiss** [comment]
Hi @mustangs0786, I assume you read some docs about an earlier version. In v0.2: 
`from langchain_experimental.graph_transformers import LLMGraphTransformer`, see https://python.langchain.com/v0.2/docs/how_to/graph_constructing/#llm-graph-transformer

**Comment by tibor-reiss** [comment]
Using Python 3.11.9 (ubuntu 22.04), with below packages (pip install langchain-experimental), there are no errors with the line I gave above:
`from langchain_experimental.graph_transformers import LLMGraphTransformer`

langchain                0.2.8
langchain-community      0.2.7
langchain-core           0.2.19
langchain-experimental   0.0.62
langchain-text-splitters 0.2.2
