### ISSUE TITLE
  raise ValueError( ValueError: OpenAIChat currently only supports single prompt, got

### ISSUE THREAD

**Issue by aldwnesx** [langchain-ai/langchain#24268]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

.

### Description

Getting
  raise ValueError(
ValueError: OpenAIChat currently only supports single prompt, got .

```

llm = AzureOpenAI(
    azure_endpoint="https://.....openai.azure.com/",
    deployment_name="....",
    model_name="...",
    openai_api_version="....",
)

def summarize(pdf):

    loader = PyPDFLoader(pdf)
    docs = loader.load_and_split()
    chain = load_summarize_chain(llm=llm, chain_type="map_reduce", verbose=False)
    summary = chain.run(docs)
    print(summary)
    print("\n")
    return summary
```

### System Info

.

**Comment by eyurtsev** [comment]
Closing issue as the report is not complete
