### ISSUE TITLE
AzureSearch vector store does not support access token authentication. FIX Suggested

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#24263]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

n/a

### Error Message and Stack Trace (if applicable)

n/a

### Description

AzureOpenAIEmbeddings and AzureChatOpenAI classes accept an azure_ad_token parameter instead of  an api_key

However AzureSearch does not support it in the langchan community library. I was able to hack it, by Copy Paste the AzureSearch from the langchain community and make some modifications:

BearerTokenCredential.py

from azure.core.credentials import TokenCredential
from azure.core.credentials import AccessToken
import time

```
class BearerTokenCredential(TokenCredential):
    def __init__(self, token):
        self._token = token

    def get_token(self, *scopes, **kwargs):
        # The AccessToken expects the token and its expiry time in seconds.
        # Here we set the expiry to an hour from now.
        expiry = int(time.time()) + 3600
        return AccessToken(self._token, expiry)
```

In AzureSearch.py

```
def _get_search_client(
    endpoint: str,
    key: str,
    azure_ad_access_token:  Optional[str],
    index_name: str,
    semantic_configuration_name: Optional[str] = None,
    fields: Optional[List[SearchField]] = None,
    vector_search: Optional[VectorSearch] = None,
    semantic_configurations: Optional[
        Union[SemanticConfiguration, List[SemanticConfiguration]]
    ] = None,
    scoring_profiles: Optional[List[ScoringProfile]] = None,
    default_scoring_profile: Optional[str] = None,
    default_fields: Optional[List[SearchField]] = None,
    user_agent: Optional[str] = "langchain",
    cors_options: Optional[CorsOptions] = None,
    async_: bool = False,
) -> Union[SearchClient, AsyncSearchClient]:
    from azure.core.credentials import AzureKeyCredential
    from azure.core.exceptions import ResourceNotFoundError
    from azure.identity import DefaultAzureCredential, InteractiveBrowserCredential
    from azure.search.documents import SearchClient
    from azure.search.documents.aio import SearchClient as AsyncSearchClient
    from azure.search.documents.indexes import SearchIndexClient
    from azure.search.documents.indexes.models import (
        ExhaustiveKnnAlgorithmConfiguration,
        ExhaustiveKnnParameters,
        HnswAlgorithmConfiguration,
        HnswParameters,
        SearchIndex,
        SemanticConfiguration,
        SemanticField,
        SemanticPrioritizedFields,
        SemanticSearch,
        VectorSearch,
        VectorSearchAlgorithmKind,
        VectorSearchAlgorithmMetric,
        VectorSearchProfile,
    )

    default_fields = default_fields or []
    if key is None:
        if azure_ad_access_token:
            credential = BearerTokenCredential(azure_ad_access_token)
        else:
            credential = DefaultAzureCredential()
    elif key.upper() == "INTERACTIVE":
        credential = InteractiveBrowserCredential()
        credential.get_token("https://search.azure.com/.default")
    else:
        credential = AzureKeyCredential(key)
    index_client: SearchIndexClient = SearchIndexClient(
        endpoint=endpoint, credential=credential, user_agent=user_agent
    )
```

WOuld it be possible to include it in the next version of langchain community?

### System Info

n/a

**Comment by PjCnuddelement** [comment]
we also need this feature for a project

**Comment by e61-KL** [comment]
Facing same issue at at project, would be nice to have this feature!

**Comment by loperamos** [comment]
Hello, just wanted to mention that I think the fix of this issue introduces a breaking change since it is adding a new optional parameter to the `AzureSearch` constructor without defaulting it to `None`: https://github.com/langchain-ai/langchain/commit/99f9a664a5381d4bcd0d38397b604cd562d4452c#diff-b691fd57bb6a6d89396c11c8d198f361be2f53e19ef4059904232cd3b5698b77R268

**Comment by efriis** [comment]
great catch https://github.com/langchain-ai/langchain/pull/25818

**Comment by levalencia** [comment]
so my PR was reverted? but it passed all the unit tests, so whats the issue then?

**Comment by efriis** [comment]
backwards compatibility issue

**Comment by levalencia** [comment]
I checked master, it was fixed by adding None and changing the order, the PR was not reverted.

**Comment by efriis** [comment]
yep correct. Issue is that changing the order of positional / required params is a breaking change. Simple example would be a user using
```
def my_function(a: int, c: int):
  return a+c

my_function(1,2)
```
trying to use the following version after upgrading
```
def my_function(a: int, message: str, c: int)
  print(message)
  return a+c
```

this is breaking because now python would interpret the `2` param as `message` instead of `c`

Was fixed in that PR by adding a default and redefining the param as a kwarg
