### ISSUE TITLE
`ConversationalRetrievalChain.from_llm()` does not work with `chain_type` of `"map_reduce"`

### ISSUE THREAD

**Issue by samuelwcm** [langchain-ai/langchain#2435]
The value of `qa_prompt` is passed to `load_qa_chain()` as `prompt`, with no option for kwargs. 
https://github.com/hwchase17/langchain/blob/4d730a9bbcd384da27e2e7c5a6a6efa5eac55838/langchain/chains/conversational_retrieval/base.py#L164-L168

`_load_map_reduce_chain()` expects multiple prompt templates as kwargs, none of which are named `prompt`, so this throws a pydantic validation error in `MapReduceDocumentsChain`.
https://github.com/hwchase17/langchain/blob/4d730a9bbcd384da27e2e7c5a6a6efa5eac55838/langchain/chains/question_answering/__init__.py#L218-L220

Perhaps we should make the use of these kwargs more generic?

**Comment by alexandermariduena** [comment]
Facing the same issue.

**Comment by harshil21** [comment]
Yes same thing happened to me as well. They should either remove the `chain_type` argument in `from_llm()`, or actually fix it so it's properly mapped to the appropriate chain type function.

A workaround is to manually create and pass `load_qa_chain` as described here: https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html#conversationalretrievalchain-with-map-reduce
