### ISSUE TITLE
AIMessageChunk merge is failing

### ISSUE THREAD

**Issue by 3coins** [langchain-ai/langchain#24377]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_core.messages import AIMessageChunk

chunks = [
    AIMessageChunk(content="Hello", response_metadata={'prompt_token_count': 12, 'generation_token_count': 1, 'stop_reason': None}, id='1'),
    AIMessageChunk(content="!", response_metadata={'prompt_token_count': None, 'generation_token_count': 2, 'stop_reason': None}, id='1')               
]

response = AIMessageChunk("")
for chunk in chunks:
    response += chunk
```

### Error Message and Stack Trace (if applicable)

TypeError: Additional kwargs key generation_token_count already exists in left dict and value has unsupported type <class 'int'>.

### Description

Chunk addition is failing with streaming use cases that generate AIMessageChunk. This root cause seems to be a failure in the [merge_dict](https://github.com/langchain-ai/langchain/blob/master/libs/core/langchain_core/utils/_merge.py#L6) function. 

```python
from langchain_aws import ChatBedrock

chat = ChatBedrock( 
    model_id="meta.llama3-8b-instruct-v1:0",
    streaming=True
)

response = AIMessageChunk("")
for chunk in model.stream(message):
    response += chunk
```

### System Info

langchain-core = 0.2.21

### Related Issues
https://github.com/langchain-ai/langchain/issues/23891
https://github.com/langchain-ai/langchain-aws/issues/107

**Comment by baskaryan** [comment]
this is the expected behavior, there's no universal way to merge dicts with overlapping keys and int values (do you sum, max, turn into a list, overwrite, etc the int values?)

**Comment by 3coins** [comment]
@baskaryan 
Thanks for the clarification. Closing this, will fix this on the model.
