### ISSUE TITLE
Country specific searches using the Serper API ?

### ISSUE THREAD

**Issue by TestCode2080** [langchain-ai/langchain#2438]
I have just started experimenting with OpenAI & Langchain and very new to this field. Is there a way to do country specific searches using the Serper API ? I am in Australia, and the Serper API keep returning US based results. I tried to use the "gl" parameter, but no success

```
from langchain.utilities import GoogleSerperAPIWrapper
from langchain.llms.openai import OpenAI
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType

params = {
    "gl": "au",
    "hl": "en",
}
search = GoogleSerperAPIWrapper(params=params)

llm = OpenAI(temperature=0)
tools = [
    Tool(
        name="Intermediate Answer",
        func=search.run,
        description="useful for when you need to ask with search"
    )
]

self_ask_with_search = initialize_agent(tools, llm, agent=AgentType.SELF_ASK_WITH_SEARCH, verbose=True)
self_ask_with_search.run("Which bank in Australia is offering the highest interest rate on deposits?")
```

Example:
Q: Which bank in Australia is offering the highest interest rate on deposits?
A: UFB Direct

UFB Direct is a bank based in the US, not Australia.

Can someone help?

**Comment by rogerserper** [comment]
Hi @SattuLal!

You were very close to solving it. To set the location and language pass the parameters directly:
```python
search = GoogleSerperAPIWrapper(gl='au', hl='en')
```
This query will correctly send the request to the [serper.dev](https://serper.dev/) API, specifying Australia as the country and English as the language.
