### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/text_embedding/baidu_qianfan_endpoint/>

### ISSUE THREAD

**Issue by 1sunxiaoshou** [langchain-ai/langchain#24392]
### URL

https://python.langchain.com/v0.2/docs/integrations/text_embedding/baidu_qianfan_endpoint/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

无法调用接口
![image](https://github.com/user-attachments/assets/fa9e528f-0761-4070-80e9-78fa32396451)

### Idea or request for content:

直接使用千帆的api可以成功，但是用langchain的接口会报错

**Comment by keenborder786** [comment]
请更新您的LangChain版本。
