### ISSUE TITLE
docs: get_num_tokens - default tokenizer

### ISSUE THREAD

**Issue by nikitajz** [langchain-ai/langchain#2439]
Hi!

1. Upd: Fixed in https://github.com/hwchase17/langchain/pull/2641
~I've noticed in the `Models -> LLM` [documentation](https://python.langchain.com/en/latest/modules/models/llms/getting_started.html) the following note about `get_num_tokens` function:~
> Notice that by default the tokens are estimated using a HuggingFace tokenizer.

~It looks not exactly correct since Huggingface is used only in legacy versions (< 3.8),  so it probably outdated.~

2. There is also a mapping in `tiktoken` package that can be reused in the function [get_num_tokens](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L437-L462):
https://github.com/openai/tiktoken/blob/46287bfa493f8ccca4d927386d7ea9cc20487525/tiktoken/model.py#L13-L53

**Comment by AlexTs10** [comment]
I took a look at the repo and [here](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L427) the wrapper for openai uses the tiktoken library. If this doesn't help could you provide the exact files you saw this since you doc link doesn't show the exact code ?

**Comment by nikitajz** [comment]
> I took a look at the repo and [here](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L427) the wrapper for openai uses the tiktoken library. If this doesn't help could you provide the exact files you saw this since you doc link doesn't show the exact code ?

I've added a PR with a tiny fix https://github.com/hwchase17/langchain/pull/2641
Hopefully, everything is correct.
