### ISSUE TITLE
Moonshot 0.2.7 has problem : AttributeError: 'Moonshot' object has no attribute '_client', When I back to 0.2.6 is OK!

### ISSUE THREAD

**Issue by zhanxiaokai** [langchain-ai/langchain#24390]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.llms.moonshot import Moonshot
import os

kimi_llm = Moonshot(model="moonshot-v1-8k")
output = kimi_llm.invoke("hello")

print(output)

### Error Message and Stack Trace (if applicable)

AttributeError: 'Moonshot' object has no attribute '_client'

### Description

Moonshot 0.2.7 has problem : AttributeError: 'Moonshot' object has no attribute '_client', When I back to 0.2.6 is OK!

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Tue Jun 4 14:43:51 UTC 2024
> Python Version:  3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:12:24) [GCC 11.2.0]

Package Information
-------------------
> langchain_core: 0.2.20
> langchain: 0.2.8
> langchain_community: 0.2.7
> langsmith: 0.1.88
> langchain-moonshot-chat: Installed. No version info available.
> langchain-prompt-chain: Installed. No version info available.
> langchain-prompt-template: Installed. No version info available.
> langchain-test: Installed. No version info available.
> langchain_text_splitters: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------

**Comment by qhy991** [comment]
I also met this bug. I hope it gets solved as soon as possible.

**Comment by zdxpan** [comment]
any one solve this?

**Comment by hucorz** [comment]
I met the same bug

**Comment by wangboo** [comment]
I have the same bug too!
