### ISSUE TITLE
Similarity search not working well when number of ingested documents is great, say over one hundred.

### ISSUE THREAD

**Issue by Jeru2023** [langchain-ai/langchain#2442]
When few documets embedded into vector db everything works fine, with similarity search I can always find the most relevant documents on the top of results. But when it comes to over hundred, searching result will be very confusing, given the same query I could not find any relevant documents. I've tried Chroma, Faiss, same story.

Anyone has any idea? thanks.
btw, the documents are in Chinese...

**Comment by 20001LastOrder** [comment]
Yeah, I experience the same. I think it's related to the embedding method used. In my experience, OpenAI embedding seems to work better than the ones from HuggingFace.

**Comment by Jeru2023** [comment]
@20001LastOrder Thanks, it must be embedding issue for Chinese content, I've tried ada-embedding, huggingface sententce embedding, and chromadb default embedding, among these three solutions ada-embedding seems outperforms a little, but still missing accuracy as the number of documents increased.

**Comment by Jeru2023** [comment]
I would like to know if anyone having similar expierence when using English document?

**Comment by mozzipa** [comment]
189 pages pdf document of mine with FOR loop similarity with score takes poor result. It does not return response even a page having same words as my query. for this trial, HuggingfaceEmbeddings with FAISS or Chroma was utilized.

**Comment by Jeru2023** [comment]
> 189 pages pdf document of mine with FOR loop similarity with score takes poor result. It does not return response even a page having same words as my query. for this trial, HuggingfaceEmbeddings with FAISS or Chroma was utilized.

English content?

**Comment by mozzipa** [comment]
Yes, it is written in English.

**Comment by khimaros** [comment]
i'm having similar issues with English content using LlamaCppEmbedding

**Comment by khimaros** [comment]
testing with the default embedding function `SentenceTransformerEmbeddingFunction` and i'm getting far more predictable and reasonable output from `similarity_search` with `Chroma`.

it's surprising to me that `LlamaCppEmbeddings` is doing such a poor job. i'll be filing a ticket with llama-cpp-python because i don't see how the problem could be with the very simple implementation in langchain -- it is doing almost nothing itself.

**Comment by khimaros** [comment]
filed https://github.com/abetlen/llama-cpp-python/issues/105

**Comment by Jeru2023** [comment]
> Yes, it is written in English.

For English content I believed that ada-embedding will be your best choise, the higher demenion of the vector the better performance.

**Comment by vowelparrot** [comment]
Thanks for creating this issue! It touches on a very important point that generic pre-trained embeddings  usually don't provide the best recall for retrieval on your particular domain.

**Comment by mozzipa** [comment]
> > Yes, it is written in English.
> 
> For English content I believed that ada-embedding will be your best choise, the higher demenion of the vector the better performance.

Thanks for advice. I agree that openAI will provide good result. But I would like to have suitably useful result from other models such as HuggingfaceEmbedding.

**Comment by Jeru2023** [comment]
I see, I have a friend who tested over 100 embedding models, he ranked top
performed models, I will ask him which one is best alternative of ada, will
get back to you once I have his reply.

**Comment by melbarra88** [comment]
> I see, I have a friend who tested over 100 embedding models, he ranked top performed models, I will ask him which one is best alternative of ada, will get back to you once I have his reply.

Hello, I was just wondering if you've had a chance to hear back from your friend regarding the best alternative to ada. If you have any information, I would appreciate it if you could share it with us :)
.

**Comment by Jeru2023** [comment]
> > I see, I have a friend who tested over 100 embedding models, he ranked top performed models, I will ask him which one is best alternative of ada, will get back to you once I have his reply.
> 
> Hello, I was just wondering if you've had a chance to hear back from your friend regarding the best alternative to ada. If you have any information, I would appreciate it if you could share it with us :).

distiluse-base-multilingual-cased-v1 and distiluse-base-multilingual-cased-v1, shibing624/text2vec-base-chinese

**Comment by asadabbas09** [comment]
I'm also facing a similar problem. Is there a way to fine-tune embedding models on custom datasets (e.g. text from 100 PDFs)? For this purpose, do I need to label the data manually into sentence pairs?

**Comment by vowelparrot** [comment]
For OAI https://github.com/openai/openai-cookbook/blob/main/examples/Customizing_embeddings.ipynb
For Huggingface - https://huggingface.co/blog/how-to-train-sentence-transformers

**Comment by thiswillbeyourgithub** [comment]
I posted a question to another thread but think this might be useful here too. The sentence transformers have a truncation length and I suspect that if the text splitter creates document that are larger that what the embedding model can ingest, the embeddings will be of poor quality.

Sadly, the multilingual sentence transformers all have a truncation length of 128 tokens !

**Comment by pixeldu** [comment]
Same here. example 25057b

**Comment by thiswillbeyourgithub** [comment]
(copying my message from [there](https://github.com/simonw/llm-sentence-transformers/issues/8#issuecomment-1732618592) )

I'm sharing my own 'rolling' sbert script to avoid clipping the sentences. It's seemingly functionnal but not very elegent, a class would be better of course but I just hope it helps someone : 

```
from sentence_transformers import SentenceTransformer


model = SentenceTransformer("all-mpnet-base-v2")

# sbert silently crops any token above the max_seq_length,
# so we do a windowing embedding then sum. The normalization happens
# afterwards.
def encode_sentences(sentences):
    n = model.max_seq_length  # max length supported by the model
    n23 = (n * 2) // 3  # overlap each 2/3 of n

    add_sent = []  # split long sentences go there
    add_sent_idx = []  # indices to keep track of sub sentences

    # check the length of each sentence
    for i, s in enumerate(sentences):
        # skip if the sentence is short enough
        length = len(model.tokenizer.encode(s))
        if length <= n:
            continue

        # otherwise, split the sentence at regular interval
        # then do the embedding of each
        # and finally add those sub embeddings together
        sub_sentences = []
        j = 1
        while length >= n23 * j:
            sub_sentences.append(s[n23 * j: n23 * j + n])
            j += 1

        # remove empty text just in case
        if "" in sub_sentences:
            while "" in sub_sentences:
                sub_sentences.remove("")
        add_sent.extend(sub_sentences)
        add_sent_idx.extend([i] * len(sub_sentences))


    # sanity check that sentences contains only valid lengths
    assert sum([
            len(model.tokenizer.encode(s)) > model.max_seq_length
            for s in sentences + add_sent
            ]) == 0, (
            "Some sentences are too long for the "
            "transformer and are cropped. The rolling average "
            "failed apparently.")

    # note that normalization is turned off, the idea is to avoid cascading
    # approximations by summing normalized embeddings and instead normalize
    # at the end
    vectors = cached_encoder(
            sentences=sentences + add_sent,
            show_progress_bar=True,
            output_value="sentence_embedding",
            convert_to_numpy=True,
            normalize_embeddings=False,
            )

    if add_sent:  # reconstitute the vector
        # at the position of the original sentence (not split)
        # add the vectors of the corresponding sub_sentence
        # then return only the 'summed' section
        assert len(add_sent) == len(add_sent_idx), (
            "Invalid add_sent length")
        offset = len(sentences)
        for sid in list(set(add_sent_idx)):
            id_range = [i for i, j in enumerate(add_sent_idx) if j == sid]
            add_sent_vec = vectors[
                    offset + min(id_range): offset + max(id_range),:]
            vectors[sid] += add_sent_vec.sum(axis=0)
        return vectors[:offset]
    else:
        return vectors

```

**Comment by luozixuan** [comment]
Met the same issue
The way our team handled it is to first reduce search space/document number by labeling the docs(by the "abstract" or something) in advance and do vector similarity search for those labels, and then do the similarity search in the reduced space. 
Also the way you split documentation is very important, the longer the chunks the more difficult to match that key word. So we have tried to split the chunks by fixed number of characters to make the chunks smaller.

Hope this helps!

**Comment by jerem99** [comment]
> I would like to know if anyone having similar expierence when using English document?

Yes I have the same issue over 100 docs.

**Comment by arafat0007** [comment]
> Met the same issue The way our team handled it is to first reduce search space/document number by labeling the docs(by the "abstract" or something) in advance and do vector similarity search for those labels

@luozixuan Hi, May I know how do you guys label? For large document, the similarity search could not find the right matched chunk or even if it found the right chunk, throwing too much chunks to gpt make gpt inable to make right answer. I was thinking to create metadata of each chunk such as keywords but I do not know how to create keywords of chunk. So i am interested how you are labeling the documents.

**Comment by Jeru2023** [comment]
> > Met the same issue The way our team handled it is to first reduce search space/document number by labeling the docs(by the "abstract" or something) in advance and do vector similarity search for those labels
> 
> @luozixuan Hi, May I know how do you guys label? For large document, the similarity search could not find the right matched chunk or even if it found the right chunk, throwing too much chunks to gpt makes gpt unable to make right answer. I was thinking to create metadata of each chunk such as keywords but I do not know how to create keywords of chunk. So i am interested how you are labeling the documents.

 I will share my scenario, say I want to infer the customer typical opinion from million customer reviews, the content of the reviews are somewhat similar, I want to have LLM thoroughly skim all the trunks of reviews(let's say 200 reviews per trunk), the only solution I can think of so far is map-reduce, I'm not sure if you guys have any better thought?

**Comment by vskritsk** [comment]
Vector representation works great with frequent entries but provides poor at the tail of query distribution. In such cases, a simple keyword yields better IR.

**Comment by eshaanrathi2** [comment]
Workaround I found is to purge vector db from memory and create a new vectorstore each time for a new doc in a loop. Not time efficient but guarantees high precision.

**Comment by hinthornw** [comment]
While I'm glad you are satisfied with your code, I must note that if you are resetting your index for each vectorstore on the fly then you have no need for a vectorstore in the first place. It also does nothing to address the OP's issue of low retriever recall on larger corpora, which is improved through a mixture of better feature representation and better querying.

**Comment by eshaanrathi2** [comment]
@hinthornw agreed, that's a valid point. However splitting documents and doing similarity search is easy and precise with Langchain chroma vectorstore. I couldn't find better alternatives without creating a vector store.

**Comment by klst-haribabu** [comment]
Ok, I am having a same scenario. Using Azure OpenAI with Ada embedding and storing in Milvus db. There is only 13 pages in the PDF. There is a relative text in page 8, whatever or however I ask a relevant in question in that page, it is not returning the content. It is same when is used Similarity check using Open AI recommended function. Can some recommend a better solution?

**Comment by eshaanrathi2** [comment]
@klst-haribabu even I have over 1000 PDFs with each over 20 pages and I use [these](https://docs.gpt4all.io/gpt4all_python_embedding.html) Open Source embedding models. 
For 1 or few retrievals per PDF, @hinthornw 's elegant and short vector similarity solution works for me. One can play with that in a loop for multiple PDFs, focus on 1 PDF at a time, rather than storing everything in a vector store, as he suggested.
For multiple PDFs and multiple queries in each PDF, above solution + using a NoSQL type store to cache the retrieved content for each query in a PDF makes sense. You will have everything in one pace but isolated, for repeated querying. You can set the keys as PDF names/ID and values as a dictionary of queries and corresponding retrieved content in each PDFs. This is a scalable as well. Basically extract and store content out of each PDF for all queries, in an isolated manner.

Second approach, use vector store, as you did. But when you move to different PDF, it is wise to purge the embeddings out of memory, else you will be doing similarity search in older cached embeddings. Otherwise, follow [this ](https://github.com/langchain-ai/langchain/issues/17410)

Secondly, after you extract texts out of PDFs, I suggest you to experiment with size of split / partitions of the texts. Making the split size similar to size of text to be retrieved, can help. Experiment with increased overlapping as well (incase of big size of text to be retrieved). Forming the query with closest match to that text can help too (if this has to be generalized, such as in a chatbot, you might want to come up with a smarter way of writing queries).
