### ISSUE TITLE
Huggingface tool-calling is not working

### ISSUE THREAD

**Issue by hadifar** [langchain-ai/langchain#24430]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_huggingface import ChatHuggingFace
from langchain_huggingface import HuggingFacePipeline
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain.pydantic_v1 import BaseModel, Field


class Calculator(BaseModel):
    """Multiply two integers together."""

    a: int = Field(..., description="First integer")
    b: int = Field(..., description="Second integer")


tools = [Calculator]

llm = HuggingFacePipeline.from_model_id(
    model_id="microsoft/Phi-3-mini-4k-instruct",
    task="text-generation",
    device_map="auto",
    pipeline_kwargs={
        "max_new_tokens": 1024,
        "do_sample": False,
        "repetition_penalty": 1.03,
    }
)
chat_model = ChatHuggingFace(llm=llm)

print(chat_model.invoke("How much is 3 multiplied by 12?"))
```

### Error Message and Stack Trace (if applicable)

Here is the output:
`
content='<|user|>\nHow much is 3 multiplied by 12?<|end|>\n<|assistant|>\n To find the product of 3 and 12, you simply multiply the two numbers together:\n\n3 × 12 = 36\n\nSo, 3 multiplied by 12 equals 36.' id='run-9270dbaa-9edd-4ca4-bb33-3dec0de34957-0'`

### Description

Hello, according to the [documentation](https://python.langchain.com/v0.2/docs/integrations/chat/) ChatHuggingFace supports tool-calling. However, when I run the example from the documentation, it returns the LLM output rather than a function call.

### System Info

langchain==0.2.9
langchain-community==0.2.7
langchain-core==0.2.21
langchain-huggingface==0.0.3
langchain-text-splitters==0.2.2

Ubuntu 22.04.3 LTS

Python 3.10.12

**Comment by Dheeraj2002** [comment]
Got the same. I'm using SmolLM-1.7B with langchain create_react_agent and bind_tools, but no matter what, it won't do function call, It'll just return the AIMessage. I tried the same with smolagents from huggingface and it works.

**Comment by tomsummerfield** [comment]
Has this been fixed yet?

**Comment by james5635** [comment]
Please, fix this issue
