### ISSUE TITLE
ChatBedrock not creating graph documents with LLMGraphTransformer

### ISSUE THREAD

**Issue by anusabbineni** [langchain-ai/langchain#24444]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_aws import ChatBedrock
from langchain_mistralai.chat_models import ChatMistralAI
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain.text_splitter import TokenTextSplitter
from langchain_community.document_loaders import UnstructuredURLLoader

urls =["https://aws.amazon.com/message/061323/"]
loader = UnstructuredURLLoader(urls=urls)
raw_data = loader.load()

text_splitter = TokenTextSplitter(chunk_size=256, chunk_overlap=24)
documents = text_splitter.split_documents(raw_data)

llm = ChatBedrock(
        model_id="mistral.mistral-large-2402-v1:0",
        model_kwargs={"temperature": 0.0},
    )

llm_transformer = LLMGraphTransformer(llm=llm)

graph_documents = llm_transformer.convert_to_graph_documents(documents)

graph_documents[0]

#### GraphDocument(nodes=[], relationships=[], source=Document(metadata={'source': 'https://aws.amazon.com/......

llm2 = ChatMistralAI(model='mistral-large-latest')
llm_transformer2 = LLMGraphTransformer(llm=llm2)

graph_documents2 = llm_transformer2.convert_to_graph_documents(documents)

graph_documents2[0]
### Description

I am trying to build a GraphRAG application using LangChain. I am getting desired output (graph documents) when using LLMGraphTransformer with an LLM object created using ChatMistralAI. But if I try to use an LLM object created with ChatBedrock I am not getting desired output. The code itself is not failing but it is not recognizing entities (nodes) and relations. This means that I can't use the output to create a GraphDatabase. Being able to process the data via Bedrock is an absolute must for me to proceed.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Tue May 21 16:52:24 UTC 2024
> Python Version:  3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.2.19
> langchain: 0.2.8
> langchain_community: 0.2.7
> langsmith: 0.1.85
> langchain_aws: 0.1.11
> langchain_experimental: 0.0.62
> langchain_mistralai: 0.1.10
> langchain_openai: 0.1.16
> langchain_text_splitters: 0.2.2

> python -m langchain_core.sys_info

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by titopuertolara** [comment]
Same situation here, i had to use `from langchain_community.chat_models import BedrockChat` but i noticed that this function will be deprecated
