### ISSUE TITLE
Server-Side Request Forgery (SSRF)

### ISSUE THREAD

**Issue by edson679** [langchain-ai/langchain#24442]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

async def inference_openai(self, user_prompt: Dict[str, str], chat_history: List[Dict[str, Any]] = []):
        jolt_prompt = ChatPromptTemplate.from_messages([
                            ("system", system),
                            MessagesPlaceholder("chat_history"),
                            ("user", prompt)
                            ]
                            )

        model_kwargs = {
                        "top_p": 1.0,
                        "presence_penalty": 0.0}
        
        question_answer_chain = prompt | ChatOpenAI(model="gpt-4o", 
                                                         max_tokens=2048,
                                                         temperature=1.0
                                                         model_kwargs=model_kwargs)
        
        ai_msg = await question_answer_chain.ainvoke({"input": str(question_answer_chain), "chat_history": chat_history})
        ai_msg = json.loads(ai_msg.content.replace("```json", "").replace("```", ""))
        return ai_msg

### Error Message and Stack Trace (if applicable)

Issues with no direct upgrade or patch:
  ✗ Server-Side Request Forgery (SSRF) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-7217837] in langchain@0.2.6
    introduced by langchain@0.2.6 and 1 other path(s)
  No upgrade or patch available

### Description

During the snix scanning it raised a SSRF
<img width="1004" alt="vulnerability" src="https://github.com/user-attachments/assets/033f6100-88b0-4f4e-b43a-8be73796ab2f">
vulnerabilty

### System Info

macOS Sonoma 14.5

**Comment by eyurtsev** [comment]
https://github.com/langchain-ai/langchain/pull/24451

**Comment by eyurtsev** [comment]
Merged and will be available during the next community release.
