### ISSUE TITLE
Use gpt-4o-mini ChatOpenAI, but gpt-3.5-turbo-0125 used

### ISSUE THREAD

**Issue by saaspeter** [langchain-ai/langchain#24461]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I am trying to use 'gpt-4o-mini' in ChatOpenAI, code like below:
```
from langchain_openai import ChatOpenAI
       OPENAI_MODEL_4oMini = "gpt-4o-mini"
      chatmodel = ChatOpenAI(model=OPENAI_MODEL_4oMini, temperature=0, max_tokens=500)
```

### Error Message and Stack Trace (if applicable)

The api called successfully, but when I review openAI response:
response_metadata={‘token_usage’: …, ‘model_name’: ‘gpt-3.5-turbo-0125’, }

### Description

The openAI result shows the model_name is ‘gpt-3.5-turbo-0125’, but I pass ‘gpt-4o-mini’, why it use gpt3.5 ?
I know if there is no 'model' parameter in ChatOpenAI, it will use gpt-3.5-turbo,  but I pass a model,  I think if the input model is unknown, the langchain should throw an exception instead of using a different model, which may lead to different response result.

### System Info

MacOS, langchain version: 0.2.10

**Comment by ccurme** [comment]
I'm unable to reproduce this, could you share more information about your environment, or else double-check that the response is being generated from the right `chatmodel` instance?
```python
from langchain_openai import ChatOpenAI

OPENAI_MODEL_4oMini = "gpt-4o-mini"
chatmodel = ChatOpenAI(model=OPENAI_MODEL_4oMini, temperature=0, max_tokens=500)
response = chatmodel.invoke("hi")
response.response_metadata
```
```
{'token_usage': {'completion_tokens': 9,
  'prompt_tokens': 8,
  'total_tokens': 17},
 'model_name': 'gpt-4o-mini-2024-07-18',
 'system_fingerprint': 'fp_661538dc1f',
 'finish_reason': 'stop',
 'logprobs': None}
```
This is with
```
langchain-openai==0.1.17
openai==1.36.0
```

**Comment by saaspeter** [comment]
@ccurme , Thank you for the reminder.  I checked my code again, I wrap invoke in another function, which didn't use the input parameter chatmodel, which is default ChatOpenAI, so it uses gpt3.5.  I am sorry :(

def answerByAI_model(chat_model, chat_prompt, **kwargs):
    chain = chat_prompt | ChatOpenAI()
    answer = chain.invoke(kwargs)

Thank you for the reminder.

**Comment by panquequelol** [comment]
in the js version of langchain this does happen, i still can't fix it

**Comment by jacoblee93** [comment]
Share your code? Can't repro.

**Comment by fsultani** [comment]
Similar problem here.  I'm using `gpt-4o-mini`, but my dashboard is still showing API requests to `GPT-3.5-turbo-1106`.

```
import { ChatOpenAI } from '@langchain/openai';

const openai = new ChatOpenAI({
  openAIApiKey: process.env.OPENAI_API_KEY,
  modelName: 'gpt-4o-mini',
});
```
