### ISSUE TITLE
Chat with pandas df string length BadRequestError

### ISSUE THREAD

**Issue by dprokhorov17** [langchain-ai/langchain#24473]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

When I try to execute a custom pandas dataframe agent (https://python.langchain.com/v0.2/docs/integrations/toolkits/pandas/)
I encounter this error:

```
"name": "BadRequestError",
	"message": "Error code: 400 - {'error': {'message': \"Invalid 'messages[0].content': string too long. Expected a string with maximum length 1048576, but got a string with length 1316712 instead.\", 'type': 'invalid_request_error', 'param': 'messages[0].content', 'code': 'string_above_max_length'}}"
```

### Description

I'm expecting to run the agent.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024
> Python Version:  3.10.13 (main, Sep 11 2023, 13:21:10) [GCC 11.2.0]

Package Information
-------------------
> langchain_core: 0.2.22
> langchain: 0.1.20
> langchain_community: 0.0.38
> langsmith: 0.1.92
> langchain_chroma: 0.1.0
> langchain_experimental: 0.0.55
> langchain_huggingface: 0.0.3
> langchain_openai: 0.1.17
> langchain_qdrant: 0.1.1
> langchain_text_splitters: 0.0.1
> langchainhub: 0.1.15
> langgraph: 0.1.9

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langserve

**Comment by trinhvanminh** [comment]
Same issue

**Comment by FahriBilici** [comment]
I have same problem
