### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/custom_tools/>

### ISSUE THREAD

**Issue by owaist37** [langchain-ai/langchain#24475]
### URL

https://python.langchain.com/v0.2/docs/how_to/custom_tools/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://python.langchain.com/v0.2/docs/how_to/custom_tools/ Using any of the code for the tools on this page leads to a TypeError. For example using the code from https://python.langchain.com/v0.2/docs/how_to/custom_tools/#tool-decorator will give a TypeError: args_schema must be a subclass of pydantic BaseModel. Got: <class 'pydantic.v1.main.multiplySchema'> error. The same will happen for the rest of the functions that have been defined in the documentation.

**Comment by baskaryan** [comment]
What versions of `langchain-core`, `pydantic`, and python are you using? Unable to reproduce with latest `langchain-core`, `pypdantic==1.10.17`, and py3.11

**Comment by owaist37** [comment]
pydantic==1.10.2
langchain==0.2.9
angchain-aws==0.1.11
langchain-community==0.2.7

**Comment by keenborder786** [comment]
Please your langchain version `0.2.1.0`

**Comment by owaist37** [comment]
Hi updating langchain to 0.2.1.0 did not fix the issue but upgrading to python3.11 did

**Comment by eyurtsev** [comment]
@owaist37 include the output of: ```python -m langchain_core.sys_info```. We're missing the langchain-core version from your report.
