### ISSUE TITLE
ImportError: cannot import name 'LangSmithParams' from 'langchain_core.language_models.chat_models'(import langchain_google_genai) in collab environment

### ISSUE THREAD

**Issue by AkashBais** [langchain-ai/langchain#24533]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import langchain_google_genai raise ImportError

### Error Message and Stack Trace (if applicable)

ImportError                               Traceback (most recent call last)
[<ipython-input-34-26070003cb78>](https://localhost:8080/#) in <cell line: 6>()
      4 # !pip install --upgrade langchain
      5 # from langchain_google_genai import GoogleGenerativeAI
----> 6 import langchain_google_genai# import GoogleGenerativeAI
      7 
      8 # llm = ChatGoogleGenerativeAI(model="gemini-pro")

1 frames
[/usr/local/lib/python3.10/dist-packages/langchain_google_genai/__init__.py](https://localhost:8080/#) in <module>
     57 
     58 from langchain_google_genai._enums import HarmBlockThreshold, HarmCategory
---> 59 from langchain_google_genai.chat_models import ChatGoogleGenerativeAI
     60 from langchain_google_genai.embeddings import GoogleGenerativeAIEmbeddings
     61 from langchain_google_genai.genai_aqa import (

[/usr/local/lib/python3.10/dist-packages/langchain_google_genai/chat_models.py](https://localhost:8080/#) in <module>
     54 )
     55 from langchain_core.language_models import LanguageModelInput
---> 56 from langchain_core.language_models.chat_models import BaseChatModel, LangSmithParams
     57 from langchain_core.messages import (
     58     AIMessage,

ImportError: cannot import name 'LangSmithParams' from 'langchain_core.language_models.chat_models' (/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py)

### Description

I am am trying to use the GoogleGenerativeAI wrapper for a project of mine.  

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
> Python Version:  3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.2.22
> langchain: 0.2.10
> langchain_community: 0.0.38
> langsmith: 0.1.93
> langchain_google_genai: 1.0.8
> langchain_openai: 0.1.7
> langchain_text_splitters: 0.2.2

**Comment by eyurtsev** [comment]
cc @ccurme

**Comment by ccurme** [comment]
Can you confirm the kernel that is raising the error has `langchain-core==0.2.22`, as you specify in your package information?

I cannot reproduce this error in a fresh environment:
```
pip install --upgrade langchain_google_genai -i https://pypi.org/simple
pip freeze | grep langchain
```
```
langchain-core==0.2.22
langchain-google-genai==1.0.8
```

**Comment by MohamedLahmeri01** [comment]
restart kernel

**Comment by AkashBais** [comment]
The issue was due to version conflicts within environments. Thanks for your responces

**Comment by matheusft** [comment]
> The issue was due to version conflicts within environments. Thanks for your responses

Can you specify what was the conflict?

**Comment by Mustafa-Shoukat1** [comment]
ImportError: cannot import name 'LangSmithParams' from 'langchain_core.language_models.chat_models' (/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py)

**Comment by pepoo20** [comment]
This happened to me when I tried:
`pip install ragatouille`
Then fixed it with:
`pip install --upgrade langchain langchain-community langchain-core`

**Comment by RamziRebai** [comment]
Go to my Mongodb >> Clusters >> Connect >> Drivers >> Then choose : "python.3.12" and update your Atlas_connection_string with the new one (same old username and password)
