### ISSUE TITLE
Tool selection is case sensitive

### ISSUE THREAD

**Issue by achammah** [langchain-ai/langchain#2453]
Currently, tool selection is case sensitive. So if you make a tool "email" and the Agent request the tool "Email" it will say that it is not a valid tool. As there is a lot of variability with agents, we should make it so that the tool selection is case insensitive (with potential additional validation to ensure there are no tools called exactly the same in the allowed tools)

**Comment by aristsakpinis93** [comment]
[This](https://github.com/hwchase17/langchain/blob/e63f9a846be7a85de7d3e3a1b277a4521b42808d/langchain/agents/agent.py#L707) is essentially where fuzzy matching could be applied through embeddings instead of using static string matching of dict keys.

**Comment by aristsakpinis93** [comment]
Why would you close the issue instead of implementing a solution for it?
