### ISSUE TITLE
Clickhouse langchain agent?

### ISSUE THREAD

**Issue by azhard4int** [langchain-ai/langchain#2454]
Hi there,

Going through the docs, and it seems there is only SQLAgent available that works for the Postgres/MySQL databases. Is there any support for the Clickhouse database?

**Comment by UmerHA** [comment]
Seems to be done in https://github.com/hwchase17/langchain/pull/5650!

**Comment by RadientBrain** [comment]
created a discussion around this, as I am also wanting this clickhouse agent to query clickhouse just like it does for sql_agent: https://github.com/langchain-ai/langchain/discussions/19691
