### ISSUE TITLE
ChatOllama & Ollama from langchain_ollama partner package does not provide support to pass base_url

### ISSUE THREAD

**Issue by ksachdeva** [langchain-ai/langchain#24555]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_ollama import ChatOllama

MODEL_NAME = "some_local_model"
MODEL_API_BASE_URL = "http://<some_host>:11434"

# there is no possibility to supply base_url
# as it is done in `from langchain_community.llms.ollama import Ollama` package
llm = ChatOllama(model=MODEL_NAME)

```

### Error Message and Stack Trace (if applicable)

Since the underlying `ollama` client ends up using `localhost` the API call fails with connection refused

### Description

I am trying to use the partner package langchain_ollama. My ollama server is running on another machine. The API does not provide a way to specify the `base_url`

The `from langchain_community.llms.ollama import Ollama` does provide that support 

### System Info

langchain==0.2.10
langchain-community==0.2.9
langchain-core==0.2.22
langchain-experimental==0.0.62
langchain-ollama==0.1.0
langchain-openai==0.1.17
langchain-text-splitters==0.2.2
langchainhub==0.1.20

**Comment by MasterAssailant** [comment]
Have tried the langchain_ollama package, and is great that ChatOllama can now support features such as tool calling as it will be much more friendly to use than the existing community package. Would appreciate it if passing in custom base_url could be supported and not lead to a Connection Refused error!

**Comment by amir1m** [comment]
Facing the same issue. Tried setting the OLLAMA_HOST=http://<some_host>:<some_port> however getting 

`ResponseError: {"detail":"Method Not Allowed"}`

I am running remotely behind Open Web UI. 
`OLLAMA_HOST=http://<some_host>:<some_port>/**ollama**`

@ksachdeva did you find the solution? Can you post what did you use?

**Comment by ksachdeva** [comment]
@amir1m you have to set OLLAMA_HOST as an `environment variable` on your machine

or if you want to do it in Python you would do 

import os
os.environ["OLLAMA_HOST"] = "http://some_host:some_port"

Above setting *MUST* be done before you import langchain_ollama package in your code.

Make sure to replace `some_host` and `some_port` with the values specific to where your ollama server is running

**Comment by amir1m** [comment]
Oh yes tried all the steps and even restarted the Jupyter kernel, no luck so far.

**Comment by ksachdeva** [comment]
@amir1m works for me by setting the environment variable ... 

If possible share the notebook and let me see if I can reproduce it on my end or perhaps I will be able to spot what may be incorrect.

**Comment by chriss1245** [comment]
Thanks for the help. Setting the OLLAMA_HOST variable actually worked for me. But I'd like to know whether it is planned to add this as a parameter. Personally, I need to change this param dynamically. For me, creating new instances with different base_urls was quite useful.
