### ISSUE TITLE
TypeError: 'VectorParams' object is not subscriptable

### ISSUE THREAD

**Issue by alexander-schmidt-mf** [langchain-ai/langchain#24558]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_openai import OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore

openai_api_key = ''
qdrant_api_key = ''
qdrant_url = ''
qdrant_collection = ''
query = ''

embeddings = OpenAIEmbeddings(api_key=openai_api_key, )

qdrant = QdrantVectorStore.from_existing_collection(
    embedding=embeddings,
    url=qdrant_url,
    api_key=qdrant_api_key,
    collection_name=qdrant_collection,
)

retriever = qdrant.as_retriever()

print(retriever.invoke(query)[0])

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/Users/alexanderschmidt/Projects/qdrant_issue/main.py", line 10, in <module>
    qdrant = QdrantVectorStore.from_existing_collection(
  File "/Users/alexanderschmidt/.local/share/virtualenvs/qdrant_issue-MiqCFk3H/lib/python3.9/site-packages/langchain_qdrant/qdrant.py", line 286, in from_existing_collection
    return cls(
  File "/Users/alexanderschmidt/.local/share/virtualenvs/qdrant_issue-MiqCFk3H/lib/python3.9/site-packages/langchain_qdrant/qdrant.py", line 87, in __init__
    self._validate_collection_config(
  File "/Users/alexanderschmidt/.local/share/virtualenvs/qdrant_issue-MiqCFk3H/lib/python3.9/site-packages/langchain_qdrant/qdrant.py", line 924, in _validate_collection_config
    cls._validate_collection_for_dense(
  File "/Users/alexanderschmidt/.local/share/virtualenvs/qdrant_issue-MiqCFk3H/lib/python3.9/site-packages/langchain_qdrant/qdrant.py", line 978, in _validate_collection_for_dense
    vector_config = vector_config[vector_name]  # type: ignore
TypeError: 'VectorParams' object is not subscriptable

### Description

I am not able to get Qdrant as_retriver working and always receiving the error message:
 TypeError: 'VectorParams' object is not subscriptable

### System Info

❯ python -m langchain_core.sys_info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.3.0: Thu Dec 21 02:29:41 PST 2023; root:xnu-10002.81.5~11/RELEASE_ARM64_T8122
> Python Version:  3.9.6 (default, Feb  3 2024, 15:58:27)
[Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.2.22
> langchain: 0.2.10
> langsmith: 0.1.93
> langchain_openai: 0.1.17
> langchain_qdrant: 0.1.2
> langchain_text_splitters: 0.2.2

Packages not installed (Not Necessarily a Problem)
--------------------------------------------------
The following packages were not found:

> langgraph
> langserve

**Comment by sankarpa** [comment]
I am getting the same error with same scenario.  Let me know how do we fix this?

**Comment by EtienneFerrandi** [comment]
It's not the best solution, but for the time being, it's still possible to use the Qdrant class rather than QdrantVectorStore :

https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.qdrant.Qdrant.html

**Comment by alexander-schmidt-mf** [comment]
@EtienneFerrandi: Yes sure, but it is deprecated.

LangChainDeprecationWarning: The class `Qdrant` was deprecated in LangChain 0.1.2 and will be removed in 0.5.0. Use QdrantVectorStore instead.

**Comment by EtienneFerrandi** [comment]
Yes, that's why I said it wasn't the best solution

**Comment by Anush008** [comment]
Please update to `0.1.3` of `langchain-qdrant`.

**Comment by alexander-schmidt-mf** [comment]
@Anush008: Thanks, is fixed.
