### ISSUE TITLE
reduce_openapi_spec removes https: from url

### ISSUE THREAD

**Issue by ar-mccabe** [langchain-ai/langchain#2456]
In following the docs for Agent ToolKits, specifically for OpenAPI, I encountered a bug in `reduce_openapi_spec` where the url has `https:` trunc'd off leading to errors when the Agent attempts to make a request.

I'm able to correct it by hardcoding the value for the url in `servers`:
- `api_spec.servers[0]['url'] = 'https://api.foo.com`

I looked through `reduce_openapi_spec` but don't obviously see where the bug is being introduced.

**Comment by diegoasua** [comment]
Adding to this since I think I found a related issue. I am parsing [this](https://api.apis.guru/v2/specs/schooldigger.com/v1/swagger.yaml) OpenAPI spec with `reduce_openapi_spec` and getting 
```bash
servers=spec["servers"],
KeyError: 'servers'
```

My code is 

```python
import os, yaml
from langchain.agents.agent_toolkits.openapi.spec import reduce_openapi_spec

with open("schooldigger_openapi.yaml") as f:
    raw_schooldigger_api_spec = yaml.load(f, Loader=yaml.Loader)
schooldigger_api_spec = reduce_openapi_spec(raw_schooldigger_api_spec)
```

With python `3.10.10` and langchain `0.0.134`

**Comment by diegoasua** [comment]
In my case I think it is because it is a `"swagger":"2.0"` spec. Is this format supported? Does it have to be updated to `OpenAPI 3.x`?

**Comment by dash7ou** [comment]
Any one fix this problem ?
