### ISSUE TITLE
Adding async support for reduce step in MapReduceDocumentsChain

### ISSUE THREAD

**Issue by MaksymPetyak** [langchain-ai/langchain#2464]
Hey!
First things first, I just want to say thanks for this amazing project :) 

In MapReduceDocumentsChain class, when you call it asynchronously, i.e. with `acombine_docs`, it still calls the same `self.process_results` method as it does when calling the regular `combine_docs`. I expected, that when you use async, it would do both map and reduce (self.process_results is basically the reduce step, if I understand correctly) steps async.

The relevant parts in [map_reduce.py](https://github.com/hwchase17/langchain/blob/master/langchain/chains/combine_documents/map_reduce.py):
```python
class MapReduceDocumentsChain(BaseCombineDocumentsChain, BaseModel):
    async def acombine_docs(
        self, docs: List[Document], **kwargs: Any
    ) -> Tuple[str, dict]:
        ...
        results = ...
        return self._process_results(results, docs, **kwargs)

    def _process_results(
        self,
        results: List[Dict],
        docs: List[Document],
        token_max: int = 3000,
        **kwargs: Any,
    ) -> Tuple[str, dict]:
    ....
    output, _ = self.combine_document_chain.combine_docs(result_docs, **kwargs) # this should be acombine_docs
    return output, extra_return_dict
```

This could be fixed by, for example, adding the async version for processing results `_aprocess_results` and using that instead when doing async calls. 

I would be happy to write a fix for this, just wanted to confirm if it's indeed a problem and I'm not missing something (the reason I stumbled on this is because I am working on a task similar to summarization and was looking for ways to speed things up).

**Comment by jiyuanq** [comment]
+1 
seems that the part calling _collapse_chain in _process_results also has the same issue

**Comment by Balthus1989** [comment]
Looking forward for this feature in future versions of Langchain
