### ISSUE TITLE
Astream Events not working for AzureMLChatOnlineEndpoint

### ISSUE THREAD

**Issue by weissenbacherpwc** [langchain-ai/langchain#24659]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
```

llm =build_llm(load_model_from="azure")
type(llm)# Outputs: langchain_community.chat_models.azureml_endpoint.AzureMLChatOnlineEndpoint
llm.invoke("Hallo") # Outputs: BaseMessage(content='Hallo! Wie kann ich Ihnen helfen?', type='assistant', id='run-f606d912-b21f-4c0c-861d-9338fa001724-0')

from backend_functions.langgraph_rag_workflow import create_workflow_app
from backend_functions.rag_functions import serialize_documents
from langchain_core.messages import HumanMessage
import json

question = "Hello, who are you?"
thread_id = "id_1"
model_type_for_astream_event = "chat_model"
    
chain = create_workflow_app(retriever=retriever, model=llm)
input_message = HumanMessage(content=question)
config = {
        "configurable": {"thread_id": thread_id}, #for every user, a different thread_id should be selected
    }
    #print(f"Updated State from previous question: {chain.get_state(config).values}")
async for event in chain.astream_events(
    #{"messages":  [input_message]},
     {"messages":  question}, #test für azure
    version="v1",
    config=config
):
    print(event)
    if event["event"] == f"on_{model_type_for_astream_event}_start" and event.get("metadata", {}).get("langgraph_node") == "generate":
        print("Stream started...")
        if model_type_for_astream_event == "llm":
            prompt_length = len(event["data"]["input"]["prompts"][0])
        else:
            prompt_length= len(event["data"]["input"]["messages"][0][0].content)
        print(f'data: {json.dumps({"type": "prompt_length_characters", "content": prompt_length})}\n\n')
        print(f'data: {json.dumps({"type": "prompt_length_tokens", "content": prompt_length / 4})}\n\n')
    if event["event"] == f"on_{model_type_for_astream_event}_stream" and event.get("metadata", {}).get("langgraph_node") == "generate":
        if model_type_for_astream_event == "llm":
            chunks = event["data"]['chunk']
        else:
            chunks = event["data"]['chunk'].content
        print(f'data: {json.dumps({"type": "chunk", "content": chunks})}\n\n')
    elif event["event"] == "on_chain_end" and event.get("metadata", {}).get("langgraph_node") == "format_docs" and event["name"] == "format_docs":
        retrieved_docs = event["data"]["input"]["raw_docs"]
        serialized_docs = serialize_documents(retrieved_docs)
        print(f'data: {{"type": "docs", "content": {serialized_docs}}}\n\n')
```

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
APIStatusError                            Traceback (most recent call last)
[/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb) Zelle 49 line 1
     [12](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=11) config = {
     [13](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=12)         "configurable": {"thread_id": thread_id}, #for every user, a different thread_id should be selected
     [14](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=13)     }
     [15](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=14)     #print(f"Updated State from previous question: {chain.get_state(config).values}")
---> [16](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=15) async for event in chain.astream_events(
     [17](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=16)     #{"messages":  [input_message]},
     [18](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=17)      {"messages":  question}, #test für azure
     [19](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=18)     version="v1",
     [20](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=19)     config=config
     [21](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=20) ):
     [22](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=21)     print(event)
     [23](vscode-notebook-cell:/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/test.ipynb#Y211sZmlsZQ%3D%3D?line=22)     if event["event"] == f"on_{model_type_for_astream_event}_start" and event.get("metadata", {}).get("langgraph_node") == "generate":

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1246](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1246), in Runnable.astream_events(self, input, config, version, include_names, include_types, include_tags, exclude_names, exclude_types, exclude_tags, **kwargs)
   1241     raise NotImplementedError(
   1242         'Only versions "v1" and "v2" of the schema is currently supported.'
   1243     )
   1245 async with aclosing(event_stream):
-> 1246     async for event in event_stream:
   1247         yield event

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py:778](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py:778), in _astream_events_implementation_v1(runnable, input, config, include_names, include_types, include_tags, exclude_names, exclude_types, exclude_tags, **kwargs)
    774 root_name = config.get("run_name", runnable.get_name())
    776 # Ignoring mypy complaint about too many different union combinations
    777 # This arises because many of the argument types are unions
--> 778 async for log in _astream_log_implementation(  # type: ignore[misc]
    779     runnable,
    780     input,
    781     config=config,
    782     stream=stream,
    783     diff=True,
    784     with_streamed_output_list=True,
    785     **kwargs,
    786 ):
    787     run_log = run_log + log
    789     if not encountered_start_event:
    790         # Yield the start event for the root runnable.

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:670](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:670), in _astream_log_implementation(runnable, input, config, stream, diff, with_streamed_output_list, **kwargs)
    667 finally:
    668     # Wait for the runnable to finish, if not cancelled (eg. by break)
    669     try:
--> 670         await task
    671     except asyncio.CancelledError:
    672         pass

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:624](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:624), in _astream_log_implementation.<locals>.consume_astream()
    621 prev_final_output: Optional[Output] = None
    622 final_output: Optional[Output] = None
--> 624 async for chunk in runnable.astream(input, config, **kwargs):
    625     prev_final_output = final_output
    626     if final_output is None:

File [~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/__init__.py:1336](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/__init__.py:1336), in Pregel.astream(self, input, config, stream_mode, output_keys, input_keys, interrupt_before, interrupt_after, debug)
   1333         del fut, task
   1335 # panic on failure or timeout
-> 1336 _panic_or_proceed(done, inflight, step)
   1337 # don't keep futures around in memory longer than needed
   1338 del done, inflight, futures

File [~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/__init__.py:1540](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/__init__.py:1540), in _panic_or_proceed(done, inflight, step)
   1538             inflight.pop().cancel()
   1539         # raise the exception
-> 1540         raise exc
   1542 if inflight:
   1543     # if we got here means we timed out
   1544     while inflight:
   1545         # cancel all pending tasks

File [~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/retry.py:117](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langgraph/pregel/retry.py:117), in arun_with_retry(task, retry_policy, stream)
    115 # run the task
    116 if stream:
--> 117     async for _ in task.proc.astream(task.input, task.config):
    118         pass
    119 else:

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3278](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3278), in RunnableSequence.astream(self, input, config, **kwargs)
   3275 async def input_aiter() -> AsyncIterator[Input]:
   3276     yield input
-> 3278 async for chunk in self.atransform(input_aiter(), config, **kwargs):
   3279     yield chunk

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3261](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3261), in RunnableSequence.atransform(self, input, config, **kwargs)
   3255 async def atransform(
   3256     self,
   3257     input: AsyncIterator[Input],
   3258     config: Optional[RunnableConfig] = None,
   3259     **kwargs: Optional[Any],
   3260 ) -> AsyncIterator[Output]:
-> 3261     async for chunk in self._atransform_stream_with_config(
   3262         input,
   3263         self._atransform,
   3264         patch_config(config, run_name=(config or {}).get("run_name") or self.name),
   3265         **kwargs,
   3266     ):
   3267         yield chunk

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:2160](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:2160), in Runnable._atransform_stream_with_config(self, input, transformer, config, run_type, **kwargs)
   2158 while True:
   2159     if accepts_context(asyncio.create_task):
-> 2160         chunk: Output = await asyncio.create_task(  # type: ignore[call-arg]
   2161             py_anext(iterator),  # type: ignore[arg-type]
   2162             context=context,
   2163         )
   2164     else:
   2165         chunk = cast(Output, await py_anext(iterator))

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:258](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:258), in LogStreamCallbackHandler.tap_output_aiter(self, run_id, output)
    246 async def tap_output_aiter(
    247     self, run_id: UUID, output: AsyncIterator[T]
    248 ) -> AsyncIterator[T]:
    249     """Tap an output async iterator to stream its values to the log.
    250 
    251     Args:
   (...)
    256         T: The output value.
    257     """
--> 258     async for chunk in output:
    259         # root run is handled in .astream_log()
    260         if run_id != self.root_id:
    261             # if we can't find the run silently ignore
    262             # eg. because this run wasn't included in the log
    263             if key := self._key_map_by_run_id.get(run_id):

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3231](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:3231), in RunnableSequence._atransform(self, input, run_manager, config, **kwargs)
   3229     else:
   3230         final_pipeline = step.atransform(final_pipeline, config)
-> 3231 async for output in final_pipeline:
   3232     yield output

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1313](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1313), in Runnable.atransform(self, input, config, **kwargs)
   1310 final: Input
   1311 got_first_val = False
-> 1313 async for ichunk in input:
   1314     # The default implementation of transform is to buffer input and
   1315     # then call stream.
   1316     # It'll attempt to gather all input into a single chunk using
   1317     # the `+` operator.
   1318     # If the input is not addable, then we'll assume that we can
   1319     # only operate on the last chunk,
   1320     # and we'll iterate until we get to the last chunk.
   1321     if not got_first_val:
   1322         final = ichunk

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1331](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:1331), in Runnable.atransform(self, input, config, **kwargs)
   1328             final = ichunk
   1330 if got_first_val:
-> 1331     async for output in self.astream(final, config, **kwargs):
   1332         yield output

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:874](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/runnables/base.py:874), in Runnable.astream(self, input, config, **kwargs)
    856 async def astream(
    857     self,
    858     input: Input,
    859     config: Optional[RunnableConfig] = None,
    860     **kwargs: Optional[Any],
    861 ) -> AsyncIterator[Output]:
    862     """
    863     Default implementation of astream, which calls ainvoke.
    864     Subclasses should override this method if they support streaming output.
   (...)
    872         The output of the Runnable.
    873     """
--> 874     yield await self.ainvoke(input, config, **kwargs)

File [~/anaconda3/lib/python3.11/site-packages/langgraph/utils.py:117](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langgraph/utils.py:117), in RunnableCallable.ainvoke(self, input, config, **kwargs)
    115     kwargs["config"] = config
    116 if sys.version_info >= (3, 11):
--> 117     ret = await asyncio.create_task(
    118         self.afunc(input, **kwargs), context=context
    119     )
    120 else:
    121     ret = await self.afunc(input, **kwargs)

File [~/Documents/GitHub/fastapi_rag_demo/backend_functions/langgraph_rag_workflow.py:264](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/Documents/GitHub/fastapi_rag_demo/backend_functions/langgraph_rag_workflow.py:264), in create_workflow_app.<locals>.generate(state)
    262 system_message = state["system_prompt"]
    263 state["prompt_length"] = len(system_message)
--> 264 response = await model.ainvoke([SystemMessage(content=system_message)] + messages)
    265 state["generation"] = response
    266 if isinstance(model, OllamaLLM):

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:291](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:291), in BaseChatModel.ainvoke(self, input, config, stop, **kwargs)
    282 async def ainvoke(
    283     self,
    284     input: LanguageModelInput,
   (...)
    288     **kwargs: Any,
    289 ) -> BaseMessage:
    290     config = ensure_config(config)
--> 291     llm_result = await self.agenerate_prompt(
    292         [self._convert_input(input)],
    293         stop=stop,
    294         callbacks=config.get("callbacks"),
    295         tags=config.get("tags"),
    296         metadata=config.get("metadata"),
    297         run_name=config.get("run_name"),
    298         run_id=config.pop("run_id", None),
    299         **kwargs,
    300     )
    301     return cast(ChatGeneration, llm_result.generations[0][0]).message

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:713](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:713), in BaseChatModel.agenerate_prompt(self, prompts, stop, callbacks, **kwargs)
    705 async def agenerate_prompt(
    706     self,
    707     prompts: List[PromptValue],
   (...)
    710     **kwargs: Any,
    711 ) -> LLMResult:
    712     prompt_messages = [p.to_messages() for p in prompts]
--> 713     return await self.agenerate(
    714         prompt_messages, stop=stop, callbacks=callbacks, **kwargs
    715     )

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:673](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:673), in BaseChatModel.agenerate(self, messages, stop, callbacks, tags, metadata, run_name, run_id, **kwargs)
    660     if run_managers:
    661         await asyncio.gather(
    662             *[
    663                 run_manager.on_llm_end(
   (...)
    671             ]
    672         )
--> 673     raise exceptions[0]
    674 flattened_outputs = [
    675     LLMResult(generations=[res.generations], llm_output=res.llm_output)  # type: ignore[list-item, union-attr]
    676     for res in results
    677 ]
    678 llm_output = self._combine_llm_outputs([res.llm_output for res in results])  # type: ignore[union-attr]

File [~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:846](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py:846), in BaseChatModel._agenerate_with_cache(self, messages, stop, run_manager, **kwargs)
    827 if (
    828     type(self)._astream != BaseChatModel._astream
    829     or type(self)._stream != BaseChatModel._stream
   (...)
    843     ),
    844 ):
    845     chunks: List[ChatGenerationChunk] = []
--> 846     async for chunk in self._astream(messages, stop=stop, **kwargs):
    847         chunk.message.response_metadata = _gen_info_and_msg_metadata(chunk)
    848         if run_manager:

File [~/anaconda3/lib/python3.11/site-packages/langchain_community/chat_models/azureml_endpoint.py:386](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/langchain_community/chat_models/azureml_endpoint.py:386), in AzureMLChatOnlineEndpoint._astream(self, messages, stop, run_manager, **kwargs)
    383 params = {"stream": True, "stop": stop, "model": None, **kwargs}
    385 default_chunk_class = AIMessageChunk
--> 386 async for chunk in await async_client.chat.completions.create(
    387     messages=message_dicts, **params
    388 ):
    389     if not isinstance(chunk, dict):
    390         chunk = chunk.dict()

File [~/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py:1159](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/openai/resources/chat/completions.py:1159), in AsyncCompletions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
   1128 @required_args(["messages", "model"], ["messages", "model", "stream"])
   1129 async def create(
   1130     self,
   (...)
   1157     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
   1158 ) -> ChatCompletion | AsyncStream[ChatCompletionChunk]:
-> 1159     return await self._post(
   1160         "[/chat/completions](https://file+.vscode-resource.vscode-cdn.net/chat/completions)",
   1161         body=await async_maybe_transform(
   1162             {
   1163                 "messages": messages,
   1164                 "model": model,
   1165                 "frequency_penalty": frequency_penalty,
   1166                 "function_call": function_call,
   1167                 "functions": functions,
   1168                 "logit_bias": logit_bias,
   1169                 "logprobs": logprobs,
   1170                 "max_tokens": max_tokens,
   1171                 "n": n,
   1172                 "presence_penalty": presence_penalty,
   1173                 "response_format": response_format,
   1174                 "seed": seed,
   1175                 "stop": stop,
   1176                 "stream": stream,
   1177                 "temperature": temperature,
   1178                 "tool_choice": tool_choice,
   1179                 "tools": tools,
   1180                 "top_logprobs": top_logprobs,
   1181                 "top_p": top_p,
   1182                 "user": user,
   1183             },
   1184             completion_create_params.CompletionCreateParams,
   1185         ),
   1186         options=make_request_options(
   1187             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
   1188         ),
   1189         cast_to=ChatCompletion,
   1190         stream=stream or False,
   1191         stream_cls=AsyncStream[ChatCompletionChunk],
   1192     )

File [~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1790](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1790), in AsyncAPIClient.post(self, path, cast_to, body, files, options, stream, stream_cls)
   1776 async def post(
   1777     self,
   1778     path: str,
   (...)
   1785     stream_cls: type[_AsyncStreamT] | None = None,
   1786 ) -> ResponseT | _AsyncStreamT:
   1787     opts = FinalRequestOptions.construct(
   1788         method="post", url=path, json_data=body, files=await async_to_httpx_files(files), **options
   1789     )
-> 1790     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)

File [~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1493](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1493), in AsyncAPIClient.request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1484 async def request(
   1485     self,
   1486     cast_to: Type[ResponseT],
   (...)
   1491     remaining_retries: Optional[int] = None,
   1492 ) -> ResponseT | _AsyncStreamT:
-> 1493     return await self._request(
   1494         cast_to=cast_to,
   1495         options=options,
   1496         stream=stream,
   1497         stream_cls=stream_cls,
   1498         remaining_retries=remaining_retries,
   1499     )

File [~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1584](https://file+.vscode-resource.vscode-cdn.net/Users/mweissenba001/Documents/GitHub/fastapi_rag_demo/~/anaconda3/lib/python3.11/site-packages/openai/_base_client.py:1584), in AsyncAPIClient._request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1581         await err.response.aread()
   1583     log.debug("Re-raising status error")
-> 1584     raise self._make_status_error_from_response(err.response) from None
   1586 return await self._process_response(
   1587     cast_to=cast_to,
   1588     options=options,
   (...)
   1591     stream_cls=stream_cls,
   1592 )

APIStatusError: Error code: 424 - {'detail': 'Not Found'}

### Description

Hi,

I want to use a Model from Azure ML in my Langgraph Pipeline. The provided code works for several model loaders like OllamaLLM or ChatGroq. However I am getting an error if I switch to an Azure model loaded with: AzureMLChatOnlineEndpoint. General responses work with it, but not the `astream_events`.
When running the code with a Azure LLM I am getting this error: `APIStatusError: Error code: 424 - {'detail': 'Not Found'}`.

I observed the events in astream_events and saw that the event "on_chat_model_start" starts but in the next step "on_chat_model_end" occurs and the genration is ofd type None. I tried `model_type_for_astream_event = "chat_model"` and `model_type_for_astream_event = "llm"`

I think this is a bug or do I have an error on my implementation? 

### System Info

langchain                 0.2.7                    pypi_0    pypi
langchain-chroma          0.1.0                    pypi_0    pypi
langchain-community       0.2.7                    pypi_0    pypi
langchain-core            0.2.23                   pypi_0    pypi
langchain-experimental    0.0.63                   pypi_0    pypi
langchain-groq            0.1.5                    pypi_0    pypi
langchain-huggingface     0.0.3                    pypi_0    pypi
langchain-ollama          0.1.0                    pypi_0    pypi
langchain-openai          0.1.7                    pypi_0    pypi
langchain-postgres        0.0.3                    pypi_0    pypi
langchain-text-splitters  0.2.1                    pypi_0    pypi

**Comment by eyurtsev** [comment]
Could you check what happens if you invoke the modelin async streaming?

```python
model = ... instantiate the model
async for chunk in model.astream('hello'):
   print(chunk)
```

**Comment by weissenbacherpwc** [comment]
This results in the same error. It might be worth to note that I changed "azureml_endpoint.py" to make it work with a Azure dedicated endpoint. Without it, a dedicated endpoint did not work at all. See here: https://github.com/langchain-ai/langchain/issues/23899#issuecomment-2222261632
