### ISSUE TITLE
DOC: Templates/neo4j-advanced-rag assumes index already exists

### ISSUE THREAD

**Issue by miaomiaocui** [langchain-ai/langchain#24688]
### URL

https://python.langchain.com/v0.1/docs/templates/neo4j-advanced-rag/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

When setting this template up for the first time, and before ingesting data, running into the error:
`ValueError: The specified vector index name does not exist. Make sure to check if you spelled it correctly`.

Is existing index a prerequisite, can the doc clarify this?

**Comment by wulifu2hao** [comment]
would changing the `python ingest.py` to point to the url of [ingest.py](https://github.com/langchain-ai/langchain/blob/master/templates/neo4j-advanced-rag/ingest.py) help?

I tried following the doc, it works well for me
