### ISSUE TITLE
AttributeError: 'Collection' object has no attribute 'model_fields'

### ISSUE THREAD

**Issue by WuYanZhao107** [langchain-ai/langchain#24696]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import WebBaseLoader
from langchain_community.vectorstores import Chroma
from langchain_openai import OpenAIEmbeddings

urls = [
    "https://lilianweng.github.io/posts/2023-06-23-agent/",
    "https://lilianweng.github.io/posts/2023-03-15-prompt-engineering/",
    "https://lilianweng.github.io/posts/2023-10-25-adv-attack-llm/",
]

docs = [WebBaseLoader(url).load() for url in urls]
docs_list = [item for sublist in docs for item in sublist]

text_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=250, chunk_overlap=0
)
doc_splits = text_splitter.split_documents(docs_list)

# Add to vectorDB
vectorstore = Chroma.from_documents(
    documents=doc_splits,
    collection_name="rag-chroma",
    embedding=OpenAIEmbeddings(),
)
retriever = vectorstore.as_retriever()

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 21
     18 doc_splits = text_splitter.split_documents(docs_list)
     20 # Add to vectorDB
---> 21 vectorstore = Chroma.from_documents(
     22     documents=doc_splits,
     23     collection_name="rag-chroma",
     24     embedding=OpenAIEmbeddings(),
     25 )
     26 retriever = vectorstore.as_retriever()

File ~\AppData\Roaming\Python\Python311\site-packages\langchain_community\vectorstores\chroma.py:878, in Chroma.from_documents(cls, documents, embedding, ids, collection_name, persist_directory, client_settings, client, collection_metadata, **kwargs)
    876 texts = [doc.page_content for doc in documents]
    877 metadatas = [doc.metadata for doc in documents]
--> 878 return cls.from_texts(
    879     texts=texts,
    880     embedding=embedding,
    881     metadatas=metadatas,
    882     ids=ids,
    883     collection_name=collection_name,
    884     persist_directory=persist_directory,
    885     client_settings=client_settings,
    886     client=client,
    887     collection_metadata=collection_metadata,
...
---> 99 if key in self.model_fields:
    100     return getattr(self, key)
    101 return None

AttributeError: 'Collection' object has no attribute 'model_fields'

### Description

I just copy the Self-RAG document

### System Info

OS: Windows
OS Version: 10.0.22631
Python Version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]

langchain_core: 0.2.23
langchain: 0.2.11
langchain_community: 0.2.10
langsmith: 0.1.82
langchain_cohere: 0.1.9
langchain_experimental: 0.0.59
langchain_openai: 0.1.17
langchain_text_splitters: 0.2.0
langchainhub: 0.1.20
langgraph: 0.1.14

**Comment by hwchase17** [comment]
what is your chromadb version? Can you try upgrading that?

**Comment by hwchase17** [comment]
see this thread: https://github.com/langchain-ai/langchain/issues/24163

**Comment by chozillla** [comment]
Same issue and no downgrading does not work.

**Comment by singh523** [comment]
Setting chromadb==0.5.3 works.

**Comment by Mu-Waleed** [comment]
> Setting chromadb==0.5.3 works.

Thanks, this is working for me!
