### ISSUE TITLE
ChatOllama is missing the parameters seed and base_url

### ISSUE THREAD

**Issue by chriss1245** [langchain-ai/langchain#24703]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

When running:
```python
from langchain_ollama import ChatOllama
llm = ChatOllama(
    model=MODEL_NAME,
    base_url=BASE_URL,
    seed=42
)
```
The parameters base_url and seed get ignored. Reviewing the code of this instance, I see that the class definition is missing these attributes.   

### Description

Regarding seed, in [PR 249](https://github.com/rasbt/LLMs-from-scratch/issues/249) in ollama, this feature was added to allow reproducibility of the experiments. 
Regarding base_url, since ollama allow us to host llms in our own servers, we need to be able to specify the url of the server. 

Plus in OllamaFunctions from the package langchain_experimental does provide support to this.

### System Info

langchain==0.2.11
langchain-chroma==0.1.2
langchain-community==0.2.10
langchain-core==0.2.23
langchain-experimental==0.0.63
langchain-groq==0.1.6
langchain-ollama==0.1.0
langchain-text-splitters==0.2.2

**Comment by noggynoggy** [comment]
I'm looking into it. I'll PR if I come to a nice solution

**Comment by noggynoggy** [comment]
There are actually more Options missing. 
If you compare [whats available](https://github.com/ollama/ollama/blob/f2a96c7d778249a7f911471b6a1532339e42fcf5/docs/api.md?plain=1#L333-L361) with [what is implemented](https://github.com/langchain-ai/langchain/blob/9be6b5a20ffa996a15f537ccf071fc9da6e344a0/libs/partners/ollama/langchain_ollama/chat_models.py#L325-L339), you  can see that there are way more options. I have to be honest though, I don't know what half of the options even do. So I'll focus on the `base_url` and the `seed` for now. The URL part i have working already.

**Comment by chriss1245** [comment]
Sounds good. Yo be honest me neither. I mentioned seed and base_url cause i use those. Thanks a lot!

**Comment by Talhavaival1** [comment]
@noggynoggy I also use Base URL , would appreciate if you could create a PR and get it merged.

**Comment by noggynoggy** [comment]
The base_url functionality was added by #24719. Maybe ill add the other Parameters later with a PR

**Comment by michaelgfeldman** [comment]
Can you please add **seed** parameters. It's also kind of an essential one.

**Comment by noggynoggy** [comment]
@chriss1245 you can close this issue. Both have been implemented.

**Comment by chriss1245** [comment]
Sure, thanks a lot!

**Comment by Steffanic** [comment]
Thanks for doing this, I've been so confused!

**Comment by preston** [comment]
In the JavaScript library, is ChatOllama's baseUrl still being ignored? And if so, is there a workaround to set it to something other than the default?

**Comment by preston** [comment]
After much frustration I discovered that the OllamaEmbeddings object also needs to be passed in the same baseUrl. Not sure why, but if you don't it'll always use localhost/127.0.0.1! 🤷‍♂️

**Comment by salvatore-cipolla** [comment]
I think this issue is still open.
