### ISSUE TITLE
Get AttributeError: 'Llama' object has no attribute '_lora_adapter' with llama cpp

### ISSUE THREAD

**Issue by DdavidC** [langchain-ai/langchain#24718]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain_community.llms import LlamaCpp

model_path = "/AI/language-models/Llama-3-Taiwan-8B-Instruct.Q5_K_M.gguf"

llm = LlamaCpp(
    model_path=model_path,
    n_gpu_layers=100,
    n_batch=512,
    n_ctx=2048,
    f16_kv=True,
    max_tokens=2048,
    callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),
    verbose=True
)
```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "d:\program\python\ddavid-langchain\ddavid_langchain\start.py", line 15, in <module>
    llm = LlamaCpp(
          ^^^^^^^^^
  File "D:\miniconda3\envs\ddavid-langchain\Lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /AI/language-models/Llama-3-Taiwan-8B-Instruct.Q5_K_M.gguf. Received error exception: access violation reading 0x0000000000000000 (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x00000247FF061120>
Traceback (most recent call last):
  File "D:\miniconda3\envs\ddavid-langchain\Lib\site-packages\llama_cpp\llama.py", line 2089, in __del__
AttributeError: 'Llama' object has no attribute '_lora_adapter'

### Description

I install brand new LangChain + llama-cpp-python under Python 3.10.14, Windows 11. Several days ago it works well, until I try to upgrade llama-cpp-python from 0.2.82 -> 0.2.83. After upgrade the error "AttributeError: 'Llama' object has no attribute '_lora_adapter'" happened.
I try to install again under new env under Python 3.11.9, but still encounter the same error.
I'm not 100% sure that the version of llama-cpp-python leads to this error, because currently I haven't tried python-llama-cpp 0.2.82 again.

### System Info

langchain==0.2.11
langchain-community==0.2.10
langchain-core==0.2.23
langchain-text-splitters==0.2.2
llama_cpp_python==0.2.83

Windows 11
Python 3.10.14 / Python 3.11.9

Install options:
$Env:CMAKE_ARGS="-DGGML_CUDA=on"
$Env:FORCE_CMAKE=1

**Comment by shamitv** [comment]
This seems to be an upstream issue with llama-cpp-python (Specific to Llama 3.1 models) .

**Comment by shamitv** [comment]
Submitted PR : https://github.com/abetlen/llama-cpp-python/pull/1630

**Comment by fdutenho** [comment]
same here
I do have an `out of memory` a few lines before in the log:
```
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 47193.83 MiB on device 0: cudaMalloc failed: out of memory
```
