### ISSUE TITLE
[langchain-ollama] `.astream` does not extract model response content

### ISSUE THREAD

**Issue by pawelkopaniecki** [langchain-ai/langchain#24737]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import asyncio

from langchain_core.language_models.base import LanguageModelInput
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_ollama import OllamaLLM

model = OllamaLLM(model="qwen2:0.5b", repeat_penalty=1.1, top_k=10, temperature=0.8, top_p=0.5)

input = [
    SystemMessage(content="Some system content..."),
    HumanMessage(content="Some user content..."),
]


async def stream_response(input: LanguageModelInput):
    async for chunk in model.astream(input):
        print(f"{chunk=}")


asyncio.run(stream_response(input))
```

### Error Message and Stack Trace (if applicable)

Every response chunk is empty.

```python

chunk=''
chunk=''
chunk=''
...
chunk=''

```

### Description

Asynchronous streaming via`.astream(...)` instance method always returns empty string for each chunk of model response. It's because response content is contained within unexpected key, thus is not being extracted.

Checked for models: `qwen2:0.5b`, `qwen2:1.5b`, `llama3.1:8b` using Ollama 0.3.0.

Changing [.astream source code](https://github.com/langchain-ai/langchain/blob/152427eca13da070cc03f3f245a43bff312e43d1/libs/partners/ollama/langchain_ollama/llms.py#L332) from

```python
chunk = GenerationChunk(
    text=(
        stream_resp["message"]["content"]
        if "message" in stream_resp
        else ""
    ),
    generation_info=(
        dict(stream_resp) if stream_resp.get("done") is True else None
    ),
)
````

to

```python

chunk = GenerationChunk(
    text=(
        stream_resp["message"]["content"]
        if "message" in stream_resp
        else stream_resp.get("response", "")
    ),
    generation_info=(
        dict(stream_resp) if stream_resp.get("done") is True else None
    ),
)
````

resolves this issue.

Synchronous version of this method works fine.

### System Info

langchain==0.2.11
langchain-core==0.2.23
langchain-ollama==0.1.0
langchain-openai==0.1.17
langchain-text-splitters==0.2.2

**Comment by isahers1** [comment]
https://github.com/langchain-ai/langchain/pull/24785

**Comment by isahers1** [comment]
Merged now, should be fixed in the next langchain-ollama release, thank you for pointing this out
