### ISSUE TITLE
Langchain agent with tools generates "StructuredTool is not JSON serializable"

### ISSUE THREAD

**Issue by smolavipour** [langchain-ai/langchain#24766]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The code is picked up from LangChain documentations
[https://python.langchain.com/v0.2/docs/how_to/tools_chain/](https://python.langchain.com/v0.2/docs/how_to/tools_chain/)

```Python
from langchain import hub
from langchain.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.tools import tool


model = # A mistral model

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful assistant"),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

@tool
def multiply(first_int: int, second_int: int) -> int:
    """Multiply two integers together."""
    return first_int * second_int

@tool
def add(first_int: int, second_int: int) -> int:
    "Add two integers."
    return first_int + second_int


@tool
def exponentiate(base: int, exponent: int) -> int:
    "Exponentiate the base to the exponent power."
    return base**exponent


tools = [multiply, add, exponentiate]

# Construct the tool calling agent
agent = create_tool_calling_agent(model,tools, prompt)

# Create an agent executor by passing in the agent and tools
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

result = agent_executor.invoke(
    {
        "input": "Take 3 to the fifth power and multiply that by the sum of twelve and three, then square the whole result"
    }
)
```

### Error Message and Stack Trace (if applicable)

TypeError: Object of type StructuredTool is not JSON serializable

### Description

I am trying to run the sample code in [https://python.langchain.com/v0.2/docs/how_to/tools_chain/](https://python.langchain.com/v0.2/docs/how_to/tools_chain/) to call an agent equipped with tools. I see two problems:
- If I run the code as it is, it generates the error that "Object of type StructuredTool is not JSON serializable". 
- If I create the agent with empty tools list (i.e., tools=[]) it generates the response. However, it is not supposed to be the right way of creating agents, as far as I understand. Besides the answer with mistral7b model is very inaccurate. Even in the example provided in the link above, the answer seems to be different and wrong when checking the [langSmith run](https://smith.langchain.com/public/eeeb27a4-a2f8-4f06-a3af-9c983f76146c/r?runtab=0).

### System Info

langchain-core==0.1.52
langchain==0.1.16

**Comment by smolavipour** [comment]
The problem seems to be resolved if we use `dumps` function in LangChain:
```Python
from langchain.load.dump import dumps

tools = [multiply, add, exponentiate]
tools_ = [dumps(multiply), dumps(add), dumps(exponentiate)]

agent = create_tool_calling_agent(model,tools_, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
```

**Comment by baskaryan** [comment]
hm im not able to recreate. could you post the full stack trace and share how you're instantiating the model? could you also try bumping to langchain and langchain-core >=0.2?

![Screenshot 2024-07-29 at 2 29 24 PM](https://github.com/user-attachments/assets/2d019493-dab1-43de-90b0-393c5067eddc)
