### ISSUE TITLE
gpt4o in azure returning empty content when using tools

### ISSUE THREAD

**Issue by magical-l** [langchain-ai/langchain#24765]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` python
llm = AzureChatOpenAI(
	azure_endpoint=api_base,
	deployment_name=engine,
	model_name=engine,
	api_key=key,
	api_version=api_version,
	temperature=0
)  # it's a chat-gpt4o deployed in Azure

def multiply2(a: int, b: int) -> int:
	"""Multiplies a and b."""
	print('----in multi---')
	return a * b


tools = [multiply2]

llm_with_tools = llm.bind_tools(tools)

query = "what's the next integer after 109382*381001？"

r1=llm.invoke(query)  # not using tools
print(r1)

print('1------------------')

r2=llm_with_tools.invoke(query)
print(r2)
```

### Error Message and Stack Trace (if applicable)

None

### Description

the content of r1 is

```
To find the next integer after the product of 109382 and 381001, we first need to calculate the product:\n\n\\[ 109382 \\times 381001 = 41632617482 \\]\n\nThe next integer after 41632617482 is:\n\n\\[ 41632617482 + 1 = 41632617483 \\]\n\nSo, the next integer after \\( 109382 \\times 381001 \\) is 41632617483.
```

while r2 is:

```
content='' additional_kwargs={'tool_calls': [{'id': '……', 'function': {'arguments': '{"a":109382,"b":381001}', 'name': 'multiply2'}, 'type': 'function'}]} response_metadata={'token_usage': {'completion_tokens': 20, 'prompt_tokens': 61, 'total_tokens': 81}, 'model_name': 'gpt-4o-2024-05-13', 'system_fingerprint': '……', 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'jailbreak': {'filtered': False, 'detected': False}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}], 'finish_reason': 'tool_calls', 'logprobs': None, 'content_filter_results': {}} id='……' tool_calls=[{'name': 'multiply2', 'args': {'a': 109382, 'b': 381001}, 'id': '……', 'type': 'tool_call'}] usage_metadata={'input_tokens': 61, 'output_tokens': 20, 'total_tokens': 81}
```

the content is empty, why?

and the log inside the multiply2() is not printed.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.24
> langchain: 0.2.6
> langchain_community: 0.2.6
> langsmith: 0.1.77
> langchain_experimental: 0.0.63
> langchain_openai: 0.1.14
> langchain_text_splitters: 0.2.1
> langchainhub: 0.1.20
> langgraph: 0.1.11
> langserve: 0.2.2

**Comment by efriis** [comment]
This is expected behavior!

In the first example, the llm is hallucinating an answer to the math problem because it doesn't have access to a tool to call.

In the second example, the llm is taking a first step of returning a tool call, which it will expect you to respond with a ToolMessage, such that it can then generate a plain text response in content.

Would recommend giving LangGraph a try to compose this agent! You'll want the basic agent with access to your multiply tool! https://langchain-ai.github.io/langgraph/tutorials/introduction/#part-2-enhancing-the-chatbot-with-tools

**Comment by magical-l** [comment]
@efriis so the agent is waiting for me to answer its request? I think I have given it tools so it can use them automaticly. am I missunderstanding some configs or steps?

**Comment by efriis** [comment]
You're just invoking the `llm`, which isn't wrapped in an agent yet! Would recommend following that linked tutorial!

**Comment by paulp-o** [comment]
@vishnu1729 did you manage to make it working?

**Comment by vishnu1729** [comment]
@paulp-o ya. it came down to state management.

**Comment by Darshan2104** [comment]
<img width="791" alt="Image" src="https://github.com/user-attachments/assets/64d32087-e3a5-4ff8-a2df-1587cc3ffc61" />

Code : 
```
from langchain_groq import ChatGroq
llm=ChatGroq(model="llama-3.3-70b-versatile")

search = DuckDuckGoSearchRun()
tools = [
    Tool(name="search", func=search.invoke, description="Useful for answering questions about current events or up-to-date information"),
    Tool(name="add", func=add, description="Useful for addition"),
    Tool(name="multiply", func=multiply, description="Useful for multiplication"),
    Tool(name="divide", func=divide, description="Useful for division")
]


llm_with_tools=llm.bind_tools(tools)

def reasoner(state: MessagesState):
   return {"messages": [llm_with_tools.invoke([SystemMessage(content="You are a helpful assistant tasked with using search and performing arithmetic on a set of inputs.")] + state["messages"])]}

# Graph
builder = StateGraph(MessagesState)
builder.add_node("reasoner", reasoner)
builder.add_node("tools", ToolNode(tools)) # for the tools
builder.add_edge(START, "reasoner")

builder.add_conditional_edges(
    "reasoner",
    # If the latest message (result) from node reasoner is a tool call -> tools_condition routes to tools
    # If the latest message (result) from node reasoner is a not a tool call -> tools_condition routes to END
    tools_condition,
)

builder.add_edge("tools", "reasoner")
react_graph = builder.compile()

messages = react_graph.invoke({"messages": messages})
```

Why Am i not getting proper full response ?
I've tried with 
```llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash")```
```llm = ChatGroq(model="gemma2-9b-it")```

But I was getting Empty content from below code even though search tool is working find independtly.
```llm_with_tools.invoke("Current weather in Bangalore?")```

@efriis  Can anyone help me here

Thanks
