### ISSUE TITLE
Passing data from tool to agent

### ISSUE THREAD

**Issue by pkuashi** [langchain-ai/langchain#2478]
For example, I want to build an agent with a Q&A tool (wrap the [Q&A with source chain](https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html) ) as private knowledge base, together with several other tools to produce the final answer

What's the suggested way to pass the "sources" information to the agent and return in the final answer? For the end user, the experience is similar as what new bing does.

![截屏2023-04-06 16 08 18](https://user-images.githubusercontent.com/10143326/230315007-f6692a87-6e62-4f77-be26-82dd23b7b6aa.png)

**Comment by jakesteelman** [comment]
I've also been searching for a way to achieve this -- have you found anything out yet?
