### ISSUE TITLE
Error in trace, Trace for AzureChatOpenAI with gpt-4-turbo-2024-04-09 is not correct 

### ISSUE THREAD

**Issue by mindful-time** [langchain-ai/langchain#24838]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import os 

from langchain_openai import AzureChatOpenAI
from langchain.callbacks import get_openai_callback
from langchain_core.tracers.context import collect_runs

from dotenv import load_dotenv
load_dotenv()

with get_openai_callback() as cb:
    result = model.invoke(["Hi"])
    print(result.response_metadata['model_name'])

print("\n")

with collect_runs() as cb:
    result = model.invoke(["Hi"])
    print(result.response_metadata['model_name'],"\n")
    print(cb.traced_runs[0].extra['invocation_params'])

output
```
gpt-4-turbo-2024-04-09


gpt-4-turbo-2024-04-09 

{'model': 'gpt-3.5-turbo', 'azure_deployment': 'gpt-4', 'model_name': 'gpt-3.5-turbo', 'stream': False, 'n': 1, 'temperature': 0.0, '_type': 'azure-openai-chat', 'stop': None}

```

### Description

Following is the screenshot of the issue 
![image](https://github.com/user-attachments/assets/af6f07ae-c802-4df3-b20b-145fc12db635)

### System Info

langchain = "^0.2.5"
langchain-community = "^0.2.5"
langchain-openai = "^0.1.9"

**Comment by baskaryan** [comment]
With AzureChatOpenAI you must explicitly set the model= and model_version= init params when instantiating the model, since these cannot be inferred from your azure deployment name. See docs on these params here https://api.python.langchain.com/en/latest/chat_models/langchain_openai.chat_models.azure.AzureChatOpenAI.html#langchain_openai.chat_models.azure.AzureChatOpenAI

**Comment by mindful-time** [comment]
@baskaryan thanks.
