### ISSUE TITLE
optional_variables argument in ChatPromptTemplate is not effective

### ISSUE THREAD

**Issue by BhujayKumarBhatta** [langchain-ai/langchain#24884]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### the code breaks. partial_variables works as intended. 
template = ChatPromptTemplate([
    ("system", "You are a helpful AI bot. Your name is {bot_name}."),
    ("human", "Hello, how are you doing?"),
    ("ai", "{greetings}, I'm doing well, thanks!"),
    ("human", "{user_input}"),
    ],
    input_variables=['user_input'],
    optional_variables=["greetings"],
    partial_variables={"bot_name": "Monalisa"}                            

)
print(template)
final_input = {            
            "user_input": "What is your name?"
        }
try:
    prompt_value = template.invoke(final_input)
except Exception as e:
    print(e)
    
   input_variables=['greetings', 'user_input'] optional_variables=['greetings'] partial_variables={'bot_name': 'Monalisa'} messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=['bot_name'], template='You are a helpful AI bot. Your name is {bot_name}.')), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='Hello, how are you doing?')), AIMessagePromptTemplate(prompt=PromptTemplate(input_variables=['greetings'], template="{greetings}, I'm doing well, thanks!")), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['user_input'], template='{user_input}'))]
"Input to ChatPromptTemplate is missing variables {'greetings'}.  Expected: ['greetings', 'user_input'] Received: ['user_input']"

### Error Message and Stack Trace (if applicable)

"Input to ChatPromptTemplate is missing variables {'greetings'}.  Expected: ['greetings', 'user_input'] Received: ['user_input']"

### Description

as shown in the  above section 
[opt-vars-chat-template.pdf](https://github.com/user-attachments/files/16444392/opt-vars-chat-template.pdf)

### System Info

langchain                 0.2.11
langchain-community       0.2.10
langchain-core            0.2.25
langchain-experimental    0.0.63
langchain-openai          0.1.17
langchain-text-splitters  0.2.2

**Comment by baskaryan** [comment]
greetings should be a partial_variable not an optional_variable in this case. optional_variables are only for MessagesPlaceholders

**Comment by BhujayKumarBhatta** [comment]
Thanks for clarification.
I understand, that serves the purpose. 
However, optional_variables as per documentation seems to be have a different meaning. 
Let me know if this pull request make any sense  or should I close it .

**Comment by baskaryan** [comment]
Yep, i think 1 would be great! Could think about 2 as well but will need to think about backwards compatibility / not making any breaking changes

**Comment by BhujayKumarBhatta** [comment]
Modified the doc string of base.py and chat.py as follows : 
"""optional_variables: A list of the names of the variables for placeholder
       or MessagePlaceholder that are optional. These variables are  auto inferred 
       from the prompt and user need not provide them."""

pull request #25017   - if you can please check and guide if any further change is required. 

Thanks for your time again.
