### ISSUE TITLE
I want to extend ChatGPTPluginRetriever to support filters for chatGptRetrievalPlugin.

### ISSUE THREAD

**Issue by st-Taku** [langchain-ai/langchain#2501]
I would like to create a new issue on GitHub regarding the extension of ChatGPTPluginRetriever to support filters for metadata in chatGptRetrievalPlugin. With the ability to extend metadata using chatGptRetrievalPlugin, I believe there will be an increased need to consider filters for metadata as well. In fact, I myself have this need and have implemented the filter feature by extending ChatGPTPluginRetriever and RetrievalQA. While I have made limited extensions for specific use cases, I hope this feature will be supported throughout the entire library. Thank you.

**Comment by AgeOfMarcus** [comment]
Hi, I'm having issues implementing ChatGPT Retrieval Plugin, can you show me how you got it working in your code?
