### ISSUE TITLE
The tool schema can't apply `min_items` or `max_items` when using BaseModel Field in Pydantic V1.

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langchain#25036]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from pydantic.v1 import BaseModel, Field

load_dotenv()


class SampleModel(BaseModel):
    numbers: list[int] = Field(min_items=2, max_items=4)


@tool(args_schema=SampleModel)
def foo() -> None:
    """bar"""
    return


ChatOpenAI().bind_tools([foo])
```

### Error Message and Stack Trace (if applicable)

ValueError: On field "numbers" the following field constraints are set but not enforced: min_items, max_items.

### Description

In from langchain_core.utils.pydantic import _create_subset_model_v1

```py
def _create_subset_model_v1(
    name: str,
    model: Type[BaseModel],
    field_names: list,
    *,
    descriptions: Optional[dict] = None,
    fn_description: Optional[str] = None,
) -> Type[BaseModel]:
    """Create a pydantic model with only a subset of model's fields."""
    from langchain_core.pydantic_v1 import create_model

    fields = {}

    for field_name in field_names:
        field = model.__fields__[field_name]
        t = (
            # this isn't perfect but should work for most functions
            field.outer_type_
            if field.required and not field.allow_none
            else Optional[field.outer_type_]
        )
        if descriptions and field_name in descriptions:
            field.field_info.description = descriptions[field_name]
        fields[field_name] = (t, field.field_info)

    rtn = create_model(name, **fields)  # type: ignore
    rtn.__doc__ = textwrap.dedent(fn_description or model.__doc__ or "")
    return rtn
```

As the comment explains, the issue lies in the process of obtaining t.

The pydantic v2 version has the issue raised in #25031 .

### System Info

langchain==0.2.12
langchain-core==0.2.28
langchain-openai==0.1.20
pydantic==2.8.2

platform==windows
python-version==3.12.4

**Comment by keenborder786** [comment]
No, it is being serialized, you just need to specify the constraint as following and it should work:

```python

class SampleModel(BaseModel):
    numbers: conlist(int,min_items=2,max_items=4)  = Field(description="Favorite numbers")

@tool(args_schema=SampleModel)
def choose_numbers():
    """Choose your favorite numbers"""
    pass


```

**Comment by gbaian10** [comment]
@keenborder786, Thanks for your reply, it can work.

But the original writing method is feasible only using pydantic v1.
So I must use `conlist` under langchain?

```py
from pydantic.v1 import BaseModel, Field, ValidationError


class SampleModel(BaseModel):
    numbers: list[int] = Field(min_items=2, max_items=4)


SampleModel(numbers=[1, 2, 3, 4])
try:
    SampleModel(numbers=[1])
except ValidationError as e:
    print(e)
```

**Comment by efriis** [comment]
Believe this is being discussed in #25031 if you scroll down
