### ISSUE TITLE
Pydantic field metadata not being serialized in tool calls

### ISSUE THREAD

**Issue by gramliu** [langchain-ai/langchain#25031]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from pydantic import BaseModel, Field
from typing import List
from langchain_core.tools import tool
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import AIMessage
from dotenv import load_dotenv

load_dotenv()

class SampleModel(BaseModel):
    numbers: List[int] = Field(description="Favorite numbers", min_length=10, max_length=15)

@tool(args_schema=SampleModel)
def choose_numbers():
    """Choose your favorite numbers"""
    pass

model = ChatAnthropic(model_name="claude-3-haiku-20240307", temperature=0)
model = model.bind_tools([choose_numbers], tool_choice="choose_numbers")

result: AIMessage = model.invoke("Hello world!")
print(result.tool_calls[0]["args"])
# Output: {'numbers': [7, 13, 42]}
```

### Description

When additional metadata is specified on Pydantic fields, e.g. `min_length` or `max_length`, these aren't serialized into the final output that's sent out to the model. In the attached screenshot from Langsmith, although it carries over the description, the `length` params are missing.

https://smith.langchain.com/public/62060327-e5be-4156-93cb-6960078ec7fb/r

<img width="530" alt="image" src="https://github.com/user-attachments/assets/4fa2a6b6-105b-43c2-957f-f56b84fef10b">

### System Info

```
langchain==0.2.11
langchain-anthropic==0.1.21
langchain-community==0.2.10
langchain-core==0.2.24
langchain-google-genai==1.0.8
langchain-google-vertexai==1.0.7
langchain-openai==0.1.19
langchain-text-splitters==0.2.2
````

**Comment by keenborder786** [comment]
No, it is being serialized, you just need to specify the constraint as following and it should work:

```python

class SampleModel(BaseModel):
    numbers: conlist(int,min_items=2,max_items=4)  = Field(description="Favorite numbers")

@tool(args_schema=SampleModel)
def choose_numbers():
    """Choose your favorite numbers"""
    pass


```

**Comment by gramliu** [comment]
@keenborder786 Thanks for showing this! I wasn't aware of `conlist` and other similar type constraining utilities on Pydantic. It's great to know we can already support the use-case using those.

That being said, I think it still makes sense to add support for `Field` metadata. Given the other linked issue (#25036) as well, it's clear that many new users will attempt to use the additional metadata for type constraining, since the [docs](https://docs.pydantic.dev/2.8/api/fields/) show them as options and make no mention of `conlist`, at least for the latest version of the docs.

**Comment by gbaian10** [comment]
In v1 it works fine, but in v2 it must use min_length or max_length in `conlist`, otherwise a TypeError will occur.

Even so, it still didn't properly impose the restrictions on tool.
Is this way of writing feasible without importing version v1?

**Comment by baskaryan** [comment]
as mentioned above, min_length and max_length are constraints that are only supported on string types: https://docs.pydantic.dev/latest/concepts/fields/#string-constraints

when specified on string types they are included as part of the tool schema (trace generated by screenshot below): https://smith.langchain.com/public/1134f484-2794-4a17-aa50-82ffdcf1bc22/r

![Screenshot 2024-08-05 at 10 34 40 AM](https://github.com/user-attachments/assets/82e951c6-1acf-4e8a-8c64-4e4f044a318b)

similarly, when using conlist and min/max_items they are getting passed through for me: https://smith.langchain.com/public/7cad58dd-96f5-48ba-8284-b9e574f5842d/r

![Screenshot 2024-08-05 at 10 38 55 AM](https://github.com/user-attachments/assets/a6b34192-b077-4e77-a8f2-22891aa1913a)

this is all with pydantic v1. i'm actually not sure how you're supposed to specify list constraints using pydantic v2, not seeing any docs on that. are we sure this is supported?

re supporting arbitrary metadata: i think this probably makes sense, though i am a little worried about including unvalidated metadata. seems like it'd be very easy for users to introduce invalid params. For example the proper way to specify array length in json schema is via [minItems/maxItems](https://json-schema.org/understanding-json-schema/reference/array#length) not min/max_length.  should langchain be validating this if pydantic isn't? should we be converting snake case to camel case automatically for users? will model providers throw errors on invalid json schema? will the behavior be uniform across model providers?

**Comment by baskaryan** [comment]
> ![image](https://private-user-images.githubusercontent.com/34255899/355202193-f4d38387-d8a2-4d07-9c16-12956308c195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTExMjEsIm5iZiI6MTcyMjg5MDgyMSwicGF0aCI6Ii8zNDI1NTg5OS8zNTUyMDIxOTMtZjRkMzgzODctZDhhMi00ZDA3LTljMTYtMTI5NTYzMDhjMTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIwNDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMTNkYTA1NTFiNDcyODcxODY1Mjc5ZjFkMWNlM2NkZmE3ZmI4MTgzODQxNDczNDRhOWViODczMjMwNDA0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P2qBXUy0ukSvYblUIDmjgB3HUNPvE-7VLgK3KTyBnpY)
> 
> In v2, when using min_length and max_length on a list, the generated JSON schema is indeed converted to minItems and maxItems.
> 
> ![image](https://private-user-images.githubusercontent.com/34255899/355202662-e2a7e4dd-aec5-4218-9ead-9d1f52523305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTExMjEsIm5iZiI6MTcyMjg5MDgyMSwicGF0aCI6Ii8zNDI1NTg5OS8zNTUyMDI2NjItZTJhN2U0ZGQtYWVjNS00MjE4LTllYWQtOWQxZjUyNTIzMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDIwNDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOWJkODc5NTExODIyNTRhZmJlN2ZkZTYzOGUxZmI3NGU1YTJlZjRiN2M0NGRkMDdmMzkwMDVlZGVlZGM5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpVlDsZfuKnc7S6AwnDUeXAkyc4sOVAOGl5bv6JrdAc)
> 
> Pydantic will indeed validate it as well.

Ooh great, in that case i'm all for updating to include metadata

**Comment by eyurtsev** [comment]
Closing as original PR was merged
