### ISSUE TITLE
DOC: HuggingFaceEmbeddings support for HF_HOME environment variable

### ISSUE THREAD

**Issue by falk0n** [langchain-ai/langchain#25038]
### URL

https://api.python.langchain.com/en/latest/embeddings/langchain_huggingface.embeddings.huggingface.HuggingFaceEmbeddings.html#langchain_huggingface.embeddings.huggingface.HuggingFaceEmbeddings

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Currently, the documentation of the cache_folder keyword only mentions the SENTENCE_TRANSFORMERS_HOME environment variable. It appears that the HF_HOME variable is also considered and takes precedence over SENTENCE_TRANSFORMERS_HOME if no cache_folder keyword is provided. I tested this on Linux with current versions of all involved modules.

### Idea or request for content:

 The documentation should be amended to include handling of HF_HOME.

**Comment by efriis** [comment]
@Jofthomas is this coming from within huggingface sdk?
