### ISSUE TITLE
Unable to set authenticiation (headers or auth) like I used to do in the community ollama integration

### ISSUE THREAD

**Issue by turbopape** [langchain-ai/langchain#25055]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_ollama import ChatOllama
from langchain_ollama.embeddings import  OllamaEmbeddings

llama3_1 = ChatOllama(

   headers=headers,
   base_url="some_host",

    model="llama3.1",
    temperature=0.001,
)
from langchain.prompts import ChatPromptTemplate
chat_prompt = ChatPromptTemplate.from_messages([
    ("system", "you are a helpful search assistant"),
])
chain = chat_prompt | llama3_1
chain.invoke({})

# embeddings

embeddings = (
    OllamaEmbeddings(
    headers=headers,
    base_url="my_public_host",
    model="mxbai-embed-large",
)
)

### Error Message and Stack Trace (if applicable)

# for chat
Error 401
# for embeddings

ValidationError: 2 validation errors for OllamaEmbeddings
base_url
  extra fields not permitted (type=value_error.extra)
headers
  extra fields not permitted (type=value_error.extra)

### Description

After I migrated to the new ChatOllama module (langchain-chatollama), I am unable to set headers or auth.
I am hosting ollama behind ngrok publicly, and I need to authenticate the calls.
When using the langchain_community ChatOllama integration, I was able to set those.
This seems to be like base_url, which was added in the latest version. 
If you know of any env var that I can use to fix this (like OLLAMA_HOST) to set auth headers, I'd be very thankful :)

### System Info

langchain==0.2.12
langchain-community==0.2.11
langchain-core==0.2.28
langchain-ollama==0.1.1
langchain-openai==0.1.19
langchain-postgres==0.0.9
langchain-text-splitters==0.2.2
langchainhub==0.1.20

platform: mac
python: 3.12.3

**Comment by isahers1** [comment]
@turbopape Thank you for bringing this up! Does this PR fix your issues: https://github.com/langchain-ai/langchain/pull/25078? (feel free to edit as needed)

**Comment by turbopape** [comment]
Hey guys, I was able to pass the headers using client_kwargs - chich will be passed to the underlying httpx client making requests to my ngrok / ollama endpoint:

heders = headers = {
    'Authorization': f'Basic {encoded_credentials}'
}

llama3_1 = ChatOllama(
    client_kwargs={'headers': headers},
    base_url=os.getenv("OLLAMA_BASE_URL"),
    model="llama3.1",
    max_tokens=64000,
    temperature=0.001,
)
I think this settles it, thanks :)

**Comment by mdrxy** [comment]
@mottolini @turbopape take a look at #32328 and let me know if that seems suitable for basic auth
