### ISSUE TITLE
`openai` has no `ChatCompletion` attribute

### ISSUE THREAD

**Issue by ChuckJonas** [langchain-ai/langchain#2505]
Trying to initialize a `ChatOpenAI` is resulting in this error:

```
from langchain.chat_models import ChatOpenAI
chat = ChatOpenAI(temperature=0)
```

> `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package.

I've upgraded all my packages to latest...

```
pip3 list 
Package                  Version
------------------------ ---------
langchain                0.0.133
openai                    0.27.4
```

**Comment by bkamapantula** [comment]
I can't replicate this, here's a minimal example from the [docs](https://python.langchain.com/en/latest/modules/chains/getting_started.html?highlight=chatopenai#query-an-llm-with-the-llmchain):

```py
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)
chat = ChatOpenAI(temperature=0)
chain = LLMChain(llm=chat, prompt=prompt)
print(chain.run('colorful socks'))
```

langchain version -> 0.0.133 and openai -> 0.27.4

**Comment by shirubei** [comment]
> 

Same here with openai version 0.27.4 and langchain 0.0.134.
Everything was OK 4 hours before. Can't remember what I had done.

**Comment by shirubei** [comment]
> > 
> 
> Same here with openai version 0.27.4 and langchain 0.0.134. Everything was OK 4 hours before. Can't remember what I had done.

My bad.  I put openai.py to the current directory and run the python script that import openai which lead to the error.
Removed openai.py and everything is OK.

**Comment by tys203831** [comment]
I also faced similar issues, but it's not because accidentally putting openai.py into current directory.

I suspect that openai change their code from `ChatCompletion` to `Completion` already, and causing this error... 

![image](https://user-images.githubusercontent.com/64836390/235369855-9a598214-41ed-47c1-abd4-cb32539142e8.png)

**Comment by janzheng** [comment]
the langchain docs have changed to:
```
llm.predict("say hi!")
'\n\nHi there!'
chat_model.predict("say hi!")
'Hello there!'
```

which is now causing this issue... what openai package do we have to lock to (not indicated in docs), but the getting started page is failing miserably

**Comment by marcjulianschwarz** [comment]
For a temporary fix/workaround I was able to remove the `try ... except` block here:

https://github.com/hwchase17/langchain/blob/dcee8936c120aa0037d82713b10e43411cedcf09/langchain/chat_models/azure_openai.py#L93C1-L100

The new code snippet would look like this 
```python
        openai.api_key = openai_api_key
        if openai_organization:
            openai.organization = openai_organization
        if openai_api_base:
            openai.api_base = openai_api_base

        values["client"] = openai.ChatCompletion

        if values["n"] < 1:
            raise ValueError("n must be at least 1.")
        if values["n"] > 1 and values["streaming"]:
            raise ValueError("n must be 1 when streaming.")
        return values
      
```

**Comment by marcjulianschwarz** [comment]
For a temporary fix/workaround I was able to remove the `try ... except` block here:

https://github.com/hwchase17/langchain/blob/dcee8936c120aa0037d82713b10e43411cedcf09/langchain/chat_models/azure_openai.py#L93C1-L100

The new code snippet would look like this 
```python
        openai.api_key = openai_api_key
        if openai_organization:
            openai.organization = openai_organization
        if openai_api_base:
            openai.api_base = openai_api_base

        values["client"] = openai.ChatCompletion

        if values["n"] < 1:
            raise ValueError("n must be at least 1.")
        if values["n"] > 1 and values["streaming"]:
            raise ValueError("n must be 1 when streaming.")
        return values
      
```
