### ISSUE TITLE
DOC: Could not reproduce notebook output

### ISSUE THREAD

**Issue by colorfuldarkgray** [langchain-ai/langchain#25068]
### URL

langchain/cookbook /baby_agi.ipynb

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Is it really possible to reproduce results with an empty vectore as proposed?
I tried with an empty and with a populated vectorstore but I still cant reproduce or get some results at all !!
Tried langchain 0.2 latest and 0.1.10 but required version is not specified. 
[baby_agi_help.md](https://github.com/user-attachments/files/16501356/baby_agi_help.md)

Thank you!

**Comment by efriis** [comment]
These cookbooks are very old! Would recommend checking out the langgraph plan and execute agent if you were interested in baby agi: https://langchain-ai.github.io/langgraph/tutorials/plan-and-execute/plan-and-execute/

Will chat with the team about removing these from the repo to reduce confusion.
