### ISSUE TITLE
Outdated Bedrock LLM when using load model from config

### ISSUE THREAD

**Issue by felipemonroy** [langchain-ai/langchain#25086]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code raise LLM not supported:

```python
from langchain_aws.chat_models.bedrock import ChatBedrock
from langchain_community.llms.loading import load_llm_from_config

llm = ChatBedrock(
    model_id='anthropic.claude-3-5-sonnet-20240620-v1:0',
    model_kwargs={"temperature": 0.0}
)

config = llm.dict()
load_llm_from_config(config)
```

Something similar happens with `langchain_aws.chat_models.bedrock.ChatBedrockConverse`

### Error Message and Stack Trace (if applicable)

ValueError: Loading amazon_bedrock_chat LLM not supported

### Description

I am trying to use `load_llm_from_config` for a `ChatBedrock` LLM.  It seems that `langchain_community.llms.get_type_to_cls_dict` does not include `amazon_bedrock_chat`. Moreover the dictionary representation does not allows the initialization of the class as it is.

```python
from langchain_aws.chat_models.bedrock import ChatBedrock

llm = ChatBedrock(
    model_id='anthropic.claude-3-5-sonnet-20240620-v1:0',
    model_kwargs={"temperature": 0.0}
)

config = llm.dict()
llm_cls = config.pop("_type")
ChatBedrock(**config)
```

Raises
```
ValidationError: 5 validation errors for ChatBedrock
guardrailIdentifier
  extra fields not permitted (type=value_error.extra)
guardrailVersion
  extra fields not permitted (type=value_error.extra)
stream
  extra fields not permitted (type=value_error.extra)
temperature
  extra fields not permitted (type=value_error.extra)
trace
  extra fields not permitted (type=value_error.extra)
```

# Possible solutions
Change dict representation of ChatBedrock and implement `amazon_bedrock_chat` in `get_type_to_cls_dict`.

Moreover, it seems that langchain-aws is moving to `ChatBedrockConverse`, which will need an additional implementation.

### System Info

Python 3.10.14
langchain-community: 0.2.10
langchain-aws: 0.1.13

**Comment by efriis** [comment]
Would recommend using the `langchain_core.load` module instead! I'll chat with the team about what we want to do with these old community functions, which only work with community implementations. Thanks for calling out!

**Comment by felipemonroy** [comment]
Thanks @efriis. According to what I have seen, mlflow langchain serialization/loading relies on those functions.
