### ISSUE TITLE
AzureAIDocumentIntelligenceLoader analysis feature ocrHighResolution not making any difference

### ISSUE THREAD

**Issue by TahaMunir1** [langchain-ai/langchain#25081]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

loader = AzureAIDocumentIntelligenceLoader(api_endpoint=endpoint, api_key=key, file_path=file_path, 
                                            api_model="prebuilt-layout", api_version=api_version, analysis_features = ["ocrHighResolution"]
)
documents = loader.load()

for document in documents:
    print(f"Page Content: {document.page_content}")

### Description

While trying the same document on Azure portal (https://documentintelligence.ai.azure.com/studio/layout) with ocrHighResolution enabled, I am getting the correct OCR result. When the feature is disabled, I am seeing obvious mistakes in result. In case of langchain, I am getting the same mistakes whether I pass the analysis feature or not with ocrHighResolution.

### System Info

langchain==0.2.11
langchain-community==0.2.10
langchain-core==0.2.23
langchain-text-splitters==0.2.2

Platform: MacBook Pro (M2 Pro)
Python version: 3.11.5

**Comment by efriis** [comment]
Could you try reproducing with using their sdk directly?

```
from azure.ai.documentintelligence import DocumentIntelligenceClient
from azure.core.credentials import AzureKeyCredential
from azure.ai.documentintelligence.models import AnalyzeDocumentRequest

client = DocumentIntelligenceClient(
    endpoint=api_endpoint,
    credential=AzureKeyCredential(api_key),
    features=["ocrHighResolution"],
)

client.begin_analyze_document(
    "prebuilt-layout", # maybe you're using something different here?
    AnalyzeDocumentRequest(url_source=url),
    output_content_format="markdown", # or "text"
)
```
if I had to guess, the model or config you're using in the portal is different than in your code. If you can get the high quality one with ^, you should be able to pass the equivalent params to the langchain document loader as well!

**Comment by TahaMunir1** [comment]
@efriis The code you provided did bring the same content as langchain. But on Azure website, the following code was provided and it is bringing the content matching the portal:

`from azure.ai.formrecognizer import DocumentAnalysisClient

document_analysis_client = DocumentAnalysisClient(
    endpoint=endpoint, credential=AzureKeyCredential(key)
)
    
poller = document_analysis_client.begin_analyze_document("prebuilt-layout", file_bytes)
result = poller.result()`
