### ISSUE TITLE
An error might occur during execution in _is_field_useful within Serializable

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langchain#25095]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
import pandas as pd
from langchain_core.messages import ToolMessage


class Foo:
    def __init__(self, bar: str) -> None:
        self.bar = bar


foo = Foo("bar")
msg = ToolMessage(content="OK", artifact=foo, tool_call_id="123")
py_dict = msg.to_json()  # ok, it's a dictionary,

data_frame = pd.DataFrame({"name": ["Alice", "Bob"], "age": [17, 19]})
msg = ToolMessage(content="Error", artifact=data_frame, tool_call_id="456")
py_dict = msg.to_json()  # error, because DataFrame cannot be evaluated as a bool().
```

### Error Message and Stack Trace (if applicable)

```plain
Traceback (most recent call last):
  File "/home/gbaian10/work/my_gpt/issue.py", line 16, in <module>
    py_dict = msg.to_json()  # error, because DataFrame cannot be evaluated as a bool().
  File "/home/gbaian10/.local/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 182, in to_json
    lc_kwargs = {
  File "/home/gbaian10/.local/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 186, in <dictcomp>
    and _is_field_useful(self, k, v)
  File "/home/gbaian10/.local/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 260, in _is_field_useful
    return field.required is True or value or field.get_default() != value
  File "/home/gbaian10/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

### Description

![image](https://github.com/user-attachments/assets/7c67cd41-2761-4899-9b7a-fb5d751f4db3)

The issue is caused by directly evaluating the truth value of the object, leading to an exception.

I think pandas df should be a rare exception, as most objects should be able to be evaluated for their value using bool().

But I think it should be possible to access Python objects within the ToolMessage artifact. Right?

### System Info

langchain==0.2.12
langchain-core==0.2.28

pandas==2.2.2

platform==linux
python-version==3.10.12

**Comment by gbaian10** [comment]
Maybe replacing it with `value is not None` would work?

**Comment by hepbc** [comment]
Hi @baskaryan. See this issue as closed but still getting the same error.

```
data_frame = pd.DataFrame({"name": ["Alice", "Bob"], "age": [17, 19]})
msg = ToolMessage(content="Error", artifact=data_frame, tool_call_id="456")
py_dict = msg.to_json()  # error, because DataFrame cannot be evaluated as a bool().
```

@gbaian10 any further thoughts? Thanks

**Comment by gbaian10** [comment]
@hepbc 

I think it's just because the new code has been merged but not yet released.
The current version is 0.2.37. If you're downloading from PyPI, you might need to wait for the next update that includes this PR to be released.

Another solution is to directly pull the current master branch source code to use.

![image](https://github.com/user-attachments/assets/c39a39f8-a290-4e1c-999c-b48f7449081b)
⬆️ The latest released version does not yet include the PR code that resolves this issue.

**Comment by gbaian10** [comment]
It is already working properly in version 0.2.38.
