### ISSUE TITLE
DOC: Guide for Implementing Tool Calling with Message History in LangChain

### ISSUE THREAD

**Issue by gokuljs** [langchain-ai/langchain#25099]
### URL

https://js.langchain.com/v0.2/docs/how_to/message_history/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

There is currently no documentation available on how to implement tool calling with message history in LangChain, or it cannot be found. The existing documentation(https://js.langchain.com/v0.2/docs/how_to/message_history/) provides examples of adding message history, but it does not cover integrating tool calling.

I suggest adding a section that demonstrates how to:

Implement tool calling within the context of a message history.
Configure tools to work seamlessly with historical messages.
Use practical examples to illustrate the setup and usage.
This addition would be highly beneficial for users looking to leverage both features together.

**Comment by shauryat97** [comment]
Any updates on this @gokuljs
