### ISSUE TITLE
SelfQueryRetriever alloowed operators does not allow contain Chroma

### ISSUE THREAD

**Issue by codenamics** [langchain-ai/langchain#25120]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

retriever = SelfQueryRetriever.from_llm(
    llm, vectorstore, document_content_description, metadata_field_info, verbose=True
)

### Error Message and Stack Trace (if applicable)

contain also doesn't work

ValueError: Received disallowed comparator contain. Allowed comparators are [<Comparator.EQ: 'eq'>, <Comparator.NE: 'ne'>, <Comparator.GT: 'gt'>, <Comparator.GTE: 'gte'>, <Comparator.LT: 'lt'>, <Comparator.LTE: 'lte'>]

### Description

Allowed operators in SelfQueryRetriever not allowing contain and in.

### System Info
Python 3.12
langchain 0.2.12
chroma 0.5.5

**Comment by justi** [comment]
@codenamics @dosubot The problem still exists, the problematic chroma definition is in that file: https://github.com/langchain-ai/langchain/blob/a0534ae62a3a9022a8ec7148ea6b63e9f5487d02/libs/community/langchain_community/query_constructors/chroma.py

I see the 'in' and 'nin' operators have not been implemented yet, and the 'contain' operator is not allowed in the Chroma engine.

**Comment by philippelauzier** [comment]
same problem,  how can we limit SelfQueryRetriever to use the allowed comparator.

**Comment by ChellShort** [comment]
I have the same question
