### ISSUE TITLE
Not possible to import 'InjectedToolArg' from langchain_core.tools

### ISSUE THREAD

**Issue by ivar-os** [langchain-ai/langchain#25144]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python

from langgraph.prebuilt import create_react_agent

agent_executor = create_react_agent(model, tools)
```

### Error Message and Stack Trace (if applicable)

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[10], line 1
----> 1 from langgraph.prebuilt import create_react_agent
      3 agent_executor = create_react_agent(model, tools)

File ~/Documents/courses/Langchain0_2/.venv/lib/python3.12/site-packages/langgraph/prebuilt/__init__.py:2
      1 """langgraph.prebuilt exposes a higher-level API for creating and executing agents and tools."""
----> 2 from langgraph.prebuilt.chat_agent_executor import create_react_agent
      3 from langgraph.prebuilt.tool_executor import ToolExecutor, ToolInvocation
      4 from langgraph.prebuilt.tool_node import InjectedState, ToolNode, tools_condition

File ~/Documents/courses/Langchain0_2/.venv/lib/python3.12/site-packages/langgraph/prebuilt/chat_agent_executor.py:28
     26 from langgraph.managed import IsLastStep
     27 from langgraph.prebuilt.tool_executor import ToolExecutor
---> 28 from langgraph.prebuilt.tool_node import ToolNode
     31 # We create the AgentState that we will pass around
     32 # This simply involves a list of messages
     33 # We want steps to return messages to append to the list
     34 # So we annotate the messages attribute with operator.add
     35 class AgentState(TypedDict):

File ~/Documents/courses/Langchain0_2/.venv/lib/python3.12/site-packages/langgraph/prebuilt/tool_node.py:20
     18 from langchain_core.runnables import RunnableConfig
     19 from langchain_core.runnables.config import get_config_list, get_executor_for_config
---> 20 from langchain_core.tools import BaseTool, InjectedToolArg
     21 from langchain_core.tools import tool as create_tool
     22 from typing_extensions import get_args

ImportError: cannot import name 'InjectedToolArg' from 'langchain_core.tools'
```

### Description

When executing the following import from langgraph it fails as it can't find the 'InjectedToolArg' from 'langchain_core.tools'.

Based on searches in the Docs, I have tried to 
* reinstall langchain, l
* langchain_core, and 
* langgraph, 

but the same error keeps appearing.

Note: when installing langgraph, langchain_core is upgraded to 0.2.18, however, that gives an error already during installation. To resolve that, I downgrade to 0.2.13.

### System Info

langchain_core.sys_info:
> langsmith: 0.1.85
> langchain_chroma: 0.1.2
> langchain_groq: 0.1.6
> langchain_objectbox: 0.1.0
> langchain_openai: 0.1.15
> langchain_text_splitters: 0.2.2
> langchainhub: 0.1.20
> langgraph: 0.2.1
> langserve: 0.2.2

pip freeze | grep langchain:
langchain==0.2.7
langchain-chroma==0.1.2
langchain-community==0.2.7
langchain-core==0.2.13
langchain-groq==0.1.6
langchain-objectbox==0.1.0
langchain-openai==0.1.15
langchain-text-splitters==0.2.2
langchainhub==0.1.20

System:
macOS Sonoma 14.5

Python:
3.12.4

**Comment by eyurtsev** [comment]
Which version of langgraph are you on?

**Comment by baskaryan** [comment]
hm `langgraph==0.2.1` requires `langchain-core >=0.2.27`. wonder why a compatible version of langchain-core wasn't automatically installed. if you upgrade to `langchain-core >=0.2.27` do you still see the issue?

**Comment by ivar-os** [comment]
Hi @baskaryan after removing langchain-core manually from the venv and installing the latest version (0.2.29) the error is gone, though I get the warning:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-objectbox 0.1.0 requires langchain-core<0.2.0,>=0.1.45, but you have langchain-core 0.2.29 which is incompatible.
Successfully installed langchain-core-0.2.29

I can move forward for now. Thanks!!!!

**Comment by baskaryan** [comment]
> Hi @baskaryan after removing langchain-core manually from the venv and installing the latest version (0.2.29) the error is gone, though I get the warning:
> 
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. langchain-objectbox 0.1.0 requires langchain-core<0.2.0,>=0.1.45, but you have langchain-core 0.2.29 which is incompatible. Successfully installed langchain-core-0.2.29
> 
> I can move forward for now. Thanks!!!!

not familiar with langchain-objectbox (not built/maintained by the langchain team) but would ask them to update them langchain-core dependency!

**Comment by baskaryan** [comment]
issue seems to be resolved, let me know if anything else pops up
