### ISSUE TITLE
Integrating Memory with Vectorstore

### ISSUE THREAD

**Issue by 20001LastOrder** [langchain-ai/langchain#2518]
I'm wondering if there is a way to use memory in combination with a vector store. For example in a chatbot, for every message, the context of the conversation is the last few hops of the conversation plus some relevant older conversations that are out of the buffer size retrieved from the vector store.

Thanks in advance!

**Comment by ksingh7** [comment]
@20001LastOrder  so when you refer Memory , do you mean "once we are feeding external knowledge to LLMs via langchain, we want LLM to memorise this for certain time (higher than the current session) and this new knowledge is also fetch able from a different account (say someone else querying from same question to ChatGPT)"

I am trying to understand what "integrating memory to langchain really mean here"

**Comment by 20001LastOrder** [comment]
@ksingh7 No, I think it's still the same session. If the conversation goes on very long, then it will become longer than the context size of the LLM at some point. From my experience, both buffer memory and summarization-based memory lose information about the conversation, and I'm thinking if there is a way to better retain conversation information. One example would be that say I'm chatting about topic A with the LLM, and then switch to topic B and talk about it for a long time and then switch back to topic A.

**Comment by ksingh7** [comment]
@20001LastOrder  thanks for clarification, make sense what you are going after.
(not to digress from this issue, just a question as a novice) If LLMs are combined with external knowledge sources via langchain, for how long LLM retain this new knowledge ? and if multiple users asking LLM questions about same knowledge base, would LLM respond to all of them with answers from the new knowledge.

**Comment by 20001LastOrder** [comment]
@ksingh7 Hmmm, this is an interesting point. I'm primarily interested in single-user conversations and haven't looked into multi-user setup yet. In my opinion, the LLM does not retain anything, but the external data store does (this can be a vector store, knowledge graph, or some other databases). And what LLM does is really take a relevant part of this data store (context) and execute some task (in my case, continue chatting with the user). So I guess how long the new knowledge is retained depends on the specific use case.

**Comment by fritzprix** [comment]
I have noticed that the memory management in this project is chaotic. There is no appropriate structuring for memory and persistent storage, and the concepts of memory and storage are being mixed up. Although I wanted to reflect these characteristics in the project, it would require significant modifications starting from the chat_history. This could cause a major issue as many implementations of memory and chat_history would need to be modified. Currently, new ideas are being added rapidly, so it may not be feasible to make such modifications at this time. I would like to add this as a response to the PR discussion.

**Comment by ibndias** [comment]
> I'm wondering if there is a way to use memory in combination with a vector store. For example in a chatbot, for every message, the context of the conversation is the last few hops of the conversation plus some relevant older conversations that are out of the buffer size retrieved from the vector store.
> 
> Thanks in advance!

It is possible with [combined memory](https://python.langchain.com/en/latest/modules/memory/examples/multiple_memory.html), you just need to change one memory to VectorStoreMemory and the other to ConversationBufferWindowMemory

```
vectorstore_memory = VectorStoreRetrieverMemory(input_key="input", memory_key="related_conv", retriever=retriever)
conv_memory = ConversationBufferWindowMemory(input_key="input", memory_key="previous_conv", k=1)
memory = CombinedMemory(memories=[ conv_memory, vectorstore_memory])
```

**Comment by Searcherr** [comment]
Hello guys!

I'm not sure that it's the right branch for describing my issue, but still ))

I've got the following error while implementing the @ibndias approach:
_InvalidRequestError: The model `sk-<my api key>` does not exist_

Maybe someone met this issue? :)
