### ISSUE TITLE
Getting issues when pip installing langchain modules

### ISSUE THREAD

**Issue by njt1980** [langchain-ai/langchain#25215]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Hi - I am trying to pip install langchain but am getting the below error. This error starting coming from today morning. Please let me know how I can get this resolved? Cargo, the Rust package manager, is not installed or is not on PATH.
  This package requires Rust and Cargo to compile extensions. Install it through
  the system's package manager or via https://rustup.rs/

  Checking for Rust toolchain....
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpcq29s8av
  cwd: /tmp/pip-install-2ldceiwf/orjson_4e150d9758f64d94abda37bb761d1916
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

### Error Message and Stack Trace (if applicable)

 Cargo, the Rust package manager, is not installed or is not on PATH.
  This package requires Rust and Cargo to compile extensions. Install it through
  the system's package manager or via https://rustup.rs/

  Checking for Rust toolchain....
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpcq29s8av
  cwd: /tmp/pip-install-2ldceiwf/orjson_4e150d9758f64d94abda37bb761d1916
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

### Description

I am getting errors when trying to pip install langchain modules. The error seems to be related to Rust being required but even after trying to install the packages related to Rust , the same error persists.

### System Info

Windows, Python 3.10

**Comment by phatjkk** [comment]
I have the same issue too, I tried to install this on Google Colab.

**Comment by bellkjtt** [comment]
I have same issue too In Kaggle. It just happend 20 minutes ago.

**Comment by phatjkk** [comment]
Try pip install orjson==3.10.6 you can fix it :D

**Comment by hwchase17** [comment]
@baskaryan how did you resolve and should we do anything more broad?
