### ISSUE TITLE
Syntax Error is getting generated in all queries  made using "SQLDatabaseChain.from_llm"

### ISSUE THREAD

**Issue by akshayg147** [langchain-ai/langchain#25278]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

db = SQLDatabase.from_uri(f"mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}",sample_rows_in_table_info=3)
db_chain = SQLDatabaseChain.from_llm(llm,db,verbose=True)
db_chain("quantity of nike shirts of white colour?")

### Error Message and Stack Trace (if applicable)

sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '```sql\nSELECT \n    `stock_quantity`\nFROM \n    `t_shirts`\nWHERE \n    `brand` = 'N' at line 1")

### Description

I encountered a problem when using the langchain-google-genai package to generate and execute SQL queries using SQLDatabasechain package against a MySQL database. The generated SQL query contains Markdown-style code block delimiters , which are causing a syntax error when executed.
Output query generated:
\```sql
SELECT 
    `stock_quantity`
FROM 
    `t_shirts`
WHERE 
    `brand` = 'Nike'
    AND `color` = 'White'
LIMIT 
    5;
 \```
 
 #### **Expected Behavior:**
The generated SQL query should not include Markdown-style code block delimiters or any other non-SQL syntax elements. It should produce a clean SQL query that can be executed without errors.

Please advise on how to handle this or if there is a fix that can be applied to prevent this issue.

### System Info

langchain-experimental==0.0.64
google-generativeai==0.7.2
langchain==0.2.12

**Comment by keenborder786** [comment]
I would recommend to use the LCEL based SQL chain rather the experimental SQL Chain:

```sql

from langchain.chains import create_sql_query_chain
from langchain_community.utilities import SQLDatabase

db = SQLDatabase.from_uri(f"mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}",sample_rows_in_table_info=3)
llm = <Your LLM Model>
chain = create_sql_query_chain(llm, db)
response = chain.invoke({"question": "quantity of nike shirts of white colour?"})


```

This would solve your issue for sure

**Comment by akshayg147** [comment]
Yup this works, though it does not execute query on the db to retrive the data bt still lot better than SQLDatabaseChain. Thanks for the help.
