### ISSUE TITLE
No notification when exceeding Anthropic rate limit

### ISSUE THREAD

**Issue by albint3r** [langchain-ai/langchain#25309]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.chat_models import ChatAnthropic
from langchain.schema import HumanMessage

chat = ChatAnthropic()

# Simulate exceeding rate limit by making multiple rapid requests
for _ in range(100):
    messages = [HumanMessage(content="Hello, how are you?")]
    response = chat(messages)
    print(response.content)

# No clear error or notification is raised when rate limit is exceeded

### Error Message and Stack Trace (if applicable)

No exeption display

### Description

Description

Problem: When the API rate limit of Anthropic is exceeded while using LangChain, no notification or clear error is received, and the application just stays connected, causing the entire API to crash.

Expected Behavior: LangChain should throw a specific exception (e.g., AnthropicRateLimitExceeded) or provide a clear error message when the Anthropic rate limit is reached.

Current Behavior: The application continues running without any indication of the rate limit issue, making it difficult to implement proper error handling and manage API usage effectively. When switching to OpenAI, the API functioned perfectly, and this issue never occurred. The problem seems to be specific to Anthropic. Upon investigation, I found that the issue occurred after exceeding 40k tokens within a 1-minute period. However, there is no alert or error to handle this, the connection to the endpoint remains active, and the program continues running but stops responding. This is a critical issue in my opinion.

### System Info

aiohttp==3.9.5
aiohttp-retry==2.8.3
aiomysql==0.2.0
aiosignal==1.3.1
aiosqlite==0.20.0
annotated-types==0.6.0
anthropic==0.31.2
anyio==4.3.0
asttokens==2.4.1
attrs==23.2.0
bcrypt==4.1.2
Brotli==1.1.0
CacheControl==0.14.0
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
click-spinner==0.1.10
cloudpathlib==0.18.1
colorama==0.4.6
croniter==1.4.1
cryptography==41.0.7
cssselect2==0.7.0
dataclasses-json==0.6.5
defusedxml==0.7.1
Deprecated==1.2.14
distro==1.9.0
dnspython==2.6.1
email_validator==2.1.1
executing==2.0.1
fastapi==0.111.0
fastapi-cli==0.0.2
fastapi-utilities==0.2.0
filelock==3.15.4
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.6.1
greenlet==3.0.3
grpcio==1.64.1
grpcio-status==1.62.2
h11==0.14.0
html5lib==1.1
httpcore==1.0.5
httplib2==0.22.0
httptools==0.6.1
httpx==0.27.0
hubspot-api-client==9.0.0
huggingface-hub==0.23.5
icecream==2.1.3
idna==3.7
importlib_resources==6.4.0
Jinja2==3.1.4
jiter==0.5.0
jsonpatch==1.33
jsonpointer==2.4
langchain==0.2.0
langchain-anthropic==0.1.20
langchain-community==0.2.0
langchain-core==0.2.20
langchain-experimental==0.0.59
langchain-openai==0.1.7
langchain-pinecone==0.1.1
langchain-text-splitters==0.2.0
langchainhub==0.1.15
langdetect==1.0.9
langgraph==0.1.7
langsmith==0.1.85
marisa-trie==1.2.0
markdown-it-py==3.0.0
markdown2==2.4.13
MarkupSafe==2.1.5
marshmallow==3.21.2
mdurl==0.1.2
msgpack==1.0.8
multidict==6.0.5
mypy-extensions==1.0.0
mysql==0.0.3
mysql-connector==2.2.9
mysql-connector-python==8.4.0
mysqlclient==2.2.4
numpy==1.26.4
openai==1.25.2
orjson==3.10.3
packaging==23.2
pandas==2.2.2
pdfkit==1.0.0
pillow==10.3.0
pinecone-client==3.2.2
proto-plus==1.24.0
protobuf==4.25.3
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.7.1
pydantic_core==2.18.2
pydyf==0.10.0
Pygments==2.18.0
PyJWT==2.8.0
PyMySQL==1.1.1
pyOpenSSL==24.1.0
pyparsing==3.1.2
pyphen==0.15.0
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-multipart==0.0.9
pytz==2024.1
PyYAML==6.0.1
regex==2024.4.28
reportlab==4.2.2
requests==2.31.0
rich==13.7.1
rsa==4.9
setuptools==70.2.0
shellingham==1.5.4
six==1.16.0
smart-open==7.0.4
sniffio==1.3.1
SQLAlchemy==2.0.30
starlette==0.37.2
StrEnum==0.4.15
tabulate==0.9.0
tenacity==8.2.3
tiktoken==0.7.0
tinycss2==1.3.0
token-bucket==0.3.0
tokenizers==0.19.1
tqdm==4.66.4
typer==0.12.3
types-requests==2.31.0.20240406
typing-inspect==0.9.0
typing_extensions==4.11.0
tzdata==2024.1
ujson==5.9.0
Unidecode==1.3.8
uritemplate==4.1.1
urllib3==2.2.1
uvicorn==0.29.0
watchfiles==0.21.0
weasel==0.4.1
weasyprint==62.3
webencodings==0.5.1
websockets==12.0
wrapt==1.16.0
yarl==1.9.4
zopfli==0.2.3

**Comment by eyurtsev** [comment]
Are you seeing any useful messages from the underlying client or from anthropic?

You can avoid the issue partially by specifying a rate limiter: https://python.langchain.com/v0.2/docs/how_to/chat_model_rate_limiting/

**Comment by albint3r** [comment]
After that, the next step would be sending a string to Anthropic, which acts as the master model or controller for my other agents. This is where the issue occurs, but no error is displayed in the terminal. The program doesn’t crash; it just gets stuck, which means I can no longer send any requests to my endpoint. The only solution is to restart the server to get it working again.

I decided to reproduce the error on my local server to rule out any misconfiguration in NGINX. Upon testing locally, I found that the issue could be replicated there as well, so I ruled out NGINX as the cause. (Although I did increase the timeout response on my server, thinking it might be related to the response time.)

I added several debug statements to track down the error and noticed that all the information is processed correctly. However, in the final step, when the system should deliver the final response, the server freezes, waiting indefinitely. At this point, nothing can recover the situation; the server must be restarted.

Considering possible causes, I suspected it might be due to Anthropic’s service tier being lower than OpenAI's concerning the workload I’m handling. After trying to force the error again, I was able to reproduce it and concluded:

After spending a considerable amount of time investigating, I am almost certain that this is a rate limit issue. However, it occurs silently and leaves the server waiting indefinitely.



![image](https://github.com/user-attachments/assets/5abab2df-d164-4260-bfb5-6f32a8beed3d)

**Comment by albint3r** [comment]
**Update:**

After further investigation, I’ve discovered that the issue isn’t limited to Anthropic—it also occurs with OpenAI. However, the problem is more easily reproducible with Anthropic. It typically takes no more than 2 or 3 attempts for the error to occur. The specific line where the issue arises is:

```python
response = await llm_with_tools.ainvoke({"messages": final_result})
```

Here’s the relevant part of my code where I create the LLM chain:

```python
if user_agent.is_anthropic():
    llm = ChatAnthropic(model=model, temperature=temperature)  # noqa
else:
    llm = ChatOpenAI(model=model, temperature=temperature)  # noqa
primary_assistant_prompt = ChatPromptTemplate.from_messages(
    [
        SystemMessage(content=f"<today>\nToday is: {get_mex_time()}\n</today>\n" + user_agent.assistant_prompt),
        MessagesPlaceholder(variable_name="messages")
    ]
)
llm_with_tools = primary_assistant_prompt | llm.bind_tools(tools)
```

The models I’m using are Anthropic Claude v3.5 and GPT-4, with the temperature set to 0.

To aid in debugging, I’ve temporarily modified my code to include additional prints:

```python
async def _chatbot(state: State):
    messages = state['messages']
    final_result = messages if user_agent.is_anthropic() else self._custom_filter(messages)
    try:
        ic(final_result)
        response = await llm_with_tools.ainvoke({"messages": final_result})
        return ic({"messages": [response]})
    except Exception as e:
        ic(f'FATAL ERROR: {e}')
        raise Exception('BIG ERROR HERE with the quoter')
```

This issue persists and causes the server to hang indefinitely, requiring a restart. It seems likely that this is related to rate limits, but the error occurs silently and without any clear indication in the logs.

Here are the final logs before the server hangs:

```plaintext
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
ic| str(ai_message): ('Lo siento, no encontré ningún producto relacionado. Por favor, proporcione '
                      'el producto exacto que está buscando para que pueda ayudarle mejor.')
ic| final_result: [HumanMessage(content='hola'),
                   AIMessage(content='Hola! Bienvenido a Power Depot. Soy AquaExpert, 
```

**Comment by simoroma** [comment]
Was this solved? Unfortunately I get the same issue.

**Comment by albint3r** [comment]
From my experimentation @simoroma, I suspect it might be a memory leak. One hypothesis I came up with after months of troubleshooting this issue is that when making several calls to the Anthropic API, for example, in my case, I was validating whether each document in the RAG was relevant to the query by classifying each as YES/NO. This is where I encountered the error we discussed. My hypothesis is that, at some point, a memory leak occurs.

Now, Langgraph provides a concurrency option, where a step can be concurrent. Here, you could use a for loop to create this concurrency and execute the process. Let me show you an example where I do this without using a for loop, but the idea is the same—I use concurrency:

```python
# Select LLM Model Company
llm = ChatOpenAI(model=model, temperature=temperature) 

chain_summary = self._assemble_structure_chain(CustomerExperienceAnalysis,
                                               "***************", llm)
chain_contact_extractor = self._assemble_structure_chain(UserInformationJsonOutput2,
                                                         "******************", llm)
prompt_memories = hub.pull("***************")

chain_memories = prompt_memories | llm

json_data = self.default_contact_key_detail
json_data.update(project_contact_properties)

chain_contact_key_details = self._assemble_json_chain("*****************", llm, json_data)

class State(TypedDict):
    messages: Annotated[list[AnyMessage], operator.add]
    summary: CustomerExperienceAnalysis
    contact: UserInformationJsonOutput2
    contact_key_details: dict[str, Any]
    memories: str

graph_builder = StateGraph(State)
chat_summary = functools.partial(self._chatbot_summary, chain_summary=chain_summary)
chat_contact_extractor = functools.partial(self._chatbot_contact_extractor,
                                           chain_contact_extractor=chain_contact_extractor)
chat_contact_key_details = functools.partial(self._chatbot_contact_key_details,
                                             chain_contact_extractor=chain_contact_key_details,
                                             json_data=json_data)
chat_memories = functools.partial(self._chatbot_extract_memories, chain_memories=chain_memories)
# Nodes
graph_builder.add_node("chatbot_summary", chat_summary)
graph_builder.add_node("chatbot_contact_extractor", chat_contact_extractor)
graph_builder.add_node("chatbot_contact_key_details", chat_contact_key_details)
graph_builder.add_node("chat_memories", chat_memories)
# Edges
graph_builder.add_edge(START, 'chatbot_summary')
graph_builder.add_edge(START, 'chatbot_contact_extractor')
graph_builder.add_edge(START, 'chatbot_contact_key_details')
graph_builder.add_edge(START, 'chat_memories')
graph_builder.add_edge("chatbot_summary", END)
graph_builder.add_edge("chatbot_contact_extractor", END)
graph_builder.add_edge("chatbot_contact_key_details", END)
graph_builder.add_edge("chat_memories", END)
```

**Comment by simoroma** [comment]
Thanks @albint3r very useful. So you think it is a memory leak and not a rate limit issue?

I get this error with Langchain when I use batch processing. Sometimes some batches might hang indefinitely. The issue is that it seems I am not able to capture this even with timeouts.

I was thinking it could be related to rate limits. Because the script runs smoothly many times till it happens to hang. Then subsequent runs hangs more often. If I wait a day, it is smooth again.

But yeah. I am not sure.
