### ISSUE TITLE
global callbacks in 'invoke' not executed when 'with_config' Is followed by 'with_fallbacks' (started in langchain_core 0.2.29)

### ISSUE THREAD

**Issue by maozguttman** [langchain-ai/langchain#25337]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from uuid import UUID
from typing import Any, Dict, List, Optional

from langchain_community.llms.fake import FakeListLLM
from langchain_core.prompts import PromptTemplate
from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.outputs import LLMResult
from langchain_core.messages import BaseMessage
from langchain_core.runnables import Runnable, RunnableLambda, RunnableConfig


class MyCallbackHandler(BaseCallbackHandler):
    def __init__(self, keyword: str) -> None:
        self._keyword: str = keyword

    @property
    def always_verbose(self) -> bool:
        return True

    def on_llm_start(
        self,
        serialized: Dict[str, Any],
        prompts: List[str],
        *,
        run_id: UUID,
        tags: Optional[List[str]] = None,
        parent_run_id: Optional[UUID] = None,
        metadata: Optional[Dict[str, Any]] = None,
        name: Optional[str] = None,
        **kwargs: Any,
    ) -> Any:
        print(f"{self._keyword}->on_llm_start")

    def on_chat_model_start(
        self,
        serialized: Dict[str, Any],
        messages: List[List[BaseMessage]],
        *,
        run_id: UUID,
        parent_run_id: Optional[UUID] = None,
        tags: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> Any:
        print(f"{self._keyword}->on_chat_model_start")

    def on_llm_end(self, response: LLMResult, *, run_id: UUID, **kwargs: Any) -> Any:
        print(f"{self._keyword}->on_llm_end")


def fallback(response: Any) -> str:
    print(f"fallback: response={response}")
    return "error, using fallback"


def main() -> None:
    fake_llm = FakeListLLM(responses=["I am a fake LLM"])
    prompt = PromptTemplate(template="Tell me someting", input_variables=[])
    config1: RunnableConfig = {"callbacks": [MyCallbackHandler("WITH_CONFIG")]}
    config2: RunnableConfig = {"callbacks": [MyCallbackHandler("INVOKE")]}

    print("----- 1 Bug: with_config followed by with_fallbacks -----")
    chain1: Runnable = prompt | fake_llm.with_config(config1).with_fallbacks(
        [RunnableLambda(lambda x: fallback(x))]
    )
    response1: Any = chain1.invoke({}, config=config2)
    print(response1)

    print("----- 2 Fine: with_fallbacks followed by with_config -----")
    chain2: Runnable = prompt | fake_llm.with_fallbacks(
        [RunnableLambda(lambda x: fallback(x))]
    ).with_config(config1)
    response2: Any = chain2.invoke({}, config=config2)
    print(response2)

    print("----- 3 Fine: with_config only -----")
    chain3: Runnable = prompt | fake_llm.with_config(config1)
    response3: Any = chain3.invoke({}, config=config2)
    print(response3)


main()
```

### Description

The example code provided is a simplified reproduction of a bug I've encountered in my codebase.
I have global callbacks that are passed through the `invoke`.
In my chain, I use `with_config` to incorporate additional local callbacks.
However, I've discovered a problem: when `with_config` is followed by `with_fallbacks`, as in `llm.with_config(...).with_fallbacks(...)`, the global callbacks are not triggered.

The example details three different cases:
* Bug present: `with_config` is followed by `with_fallbacks`, as shown by `llm.with_config(...).with_fallbacks(...)`.
* No bug: `with_fallbacks` is followed by `with_config`, as shown by `llm.with_fallbacks(...).with_config(...)`.
* No bug: Only `with_config` is used, as shown by `llm.with_config(...)`.

This issue first appeared in `langchain_core` version **0.2.29**. The previous version, **0.2.28**, did not exhibit this problem. It also happens in version **0.2.40**

The output when utilizing Langchain_core version 0.2.29, which contains this bug. Please observe that there are two instances listed under the section "1 Bug":
```
----- 1 Bug: with_config followed by with_fallbacks -----
WITH_CONFIG->on_llm_start
WITH_CONFIG->on_llm_end
I am a fake LLM
----- 2 Fine: with_fallbacks followed by with_config -----
INVOKE->on_llm_start
WITH_CONFIG->on_llm_start
INVOKE->on_llm_end
WITH_CONFIG->on_llm_end
I am a fake LLM
----- 3 Fine: with_config only -----
INVOKE->on_llm_start
WITH_CONFIG->on_llm_start
INVOKE->on_llm_end
WITH_CONFIG->on_llm_end
I am a fake LLM
```

The output when utilizing Langchain_core version 0.2.28, which does not contain this bug. Please observe that there are four instances listed under the section "1 Bug" (as expected):
```
----- 1 Bug: with_config followed by with_fallbacks -----
INVOKE->on_llm_start
WITH_CONFIG->on_llm_start
INVOKE->on_llm_end
WITH_CONFIG->on_llm_end
I am a fake LLM
----- 2 Fine: with_fallbacks followed by with_config -----
INVOKE->on_llm_start
WITH_CONFIG->on_llm_start
INVOKE->on_llm_end
WITH_CONFIG->on_llm_end
I am a fake LLM
----- 3 Fine: with_config only -----
INVOKE->on_llm_start
WITH_CONFIG->on_llm_start
INVOKE->on_llm_end
WITH_CONFIG->on_llm_end
I am a fake LLM
```

### System Info

OS: SLES12
Python version: 3.9.6

**First Langchain version with that bug**
* langchain==0.2.13
* langchain-community==0.2.7
* langchain-core==0.2.29
* langchain-text-splitters==0.2.2

**Latest Langchain version without that bug**
* langchain==0.2.13
* langchain-community==0.2.7
* langchain-core==0.2.28
* langchain-text-splitters==0.2.2

**Comment by maozguttman** [comment]
Not an expert in Langchain code, it appears that `child_config` needs to be included as an argument in the `RunnableWithFallbacks.invoke` function when calling `context.run` (in `langchain_core/runnables/fallbacks.py` file):

```python
output = context.run(
    runnable.invoke,
    input,
    child_config, ##### <==== ADDED THIS LINE
    **kwargs,
)

**Comment by avinashkz** [comment]
Blocked by the same issue. Any estimates on when this will be fixed?
