### ISSUE TITLE
ToolException("Too many arguments to single-input tool Calculator.\n Consider using StructuredTool instead. Args: [['5*3'], {}]")

### ISSUE THREAD

**Issue by rhlarora84** [langchain-ai/langchain#25353]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from datetime import datetime

from langchain.chains.llm_math.base import LLMMathChain
from langchain_community.chat_models import ChatOpenAI
from langchain_core.tools import tool, Tool
from langgraph.prebuilt import create_react_agent

model = ChatOpenAI(
    ...
)


@tool
def check_weather(location: str, at_time: datetime) -> str:
    """Return the weather forecast for the specified location."""
    return f"It's always sunny in {location}"


llm_math_chain = LLMMathChain.from_llm(llm=model,
                                       verbose=True)
tools = [check_weather, Tool(
    name="Calculator",
    func=llm_math_chain.run,
    description="Useful for when you need to answer questions about math. This tool is only for math "
                "questions and nothing else. Only input math expressions.",
)]
graph = create_react_agent(model, tools=tools)

if __name__ == "__main__":
    inputs = {"messages": [("user", "Calculate 5*3")]}
    for s in graph.stream(inputs, stream_mode="values"):
        message = s["messages"][-1]
        if isinstance(message, tuple):
            print(message)
        else:
            message.pretty_print()
 ```

### Error Message and Stack Trace (if applicable)

================================ Human Message =================================

Calculate 5*3
================================== Ai Message ==================================
Tool Calls:
  Calculator (call_O5H3HHhTlul8kea3pvHj8FSN)
 Call ID: call_O5H3HHhTlul8kea3pvHj8FSN
  Args:
    args: ['5*3']
    config: {}
================================= Tool Message =================================
Name: Calculator

Error: ToolException("Too many arguments to single-input tool Calculator.\n                Consider using StructuredTool instead. Args: [['5*3'], {}]")
 Please fix your mistakes.
================================== Ai Message ==================================
Tool Calls:
  Calculator (call_U0B84wfj0pwZuZCsP5rUtcsN)
 Call ID: call_U0B84wfj0pwZuZCsP5rUtcsN
  Args:
    args: ['5*3']
    config: {}
================================= Tool Message =================================
Name: Calculator

Error: ToolException("Too many arguments to single-input tool Calculator.\n                Consider using StructuredTool instead. Args: [['5*3'], {}]")
 Please fix your mistakes.
================================== Ai Message ==================================
Tool Calls:
  Calculator (call_wF4MlZXTmnpRiauaHp1IZmZt)
 Call ID: call_wF4MlZXTmnpRiauaHp1IZmZt
  Args:
    args: ['5*3']
    config: {}
================================= Tool Message =================================
Name: Calculator

Error: ToolException("Too many arguments to single-input tool Calculator.\n                Consider using StructuredTool instead. Args: [['5*3'], {}]")
 Please fix your mistakes.
================================== Ai Message ==================================
Tool Calls:
  Calculator (call_aBw92kXhfEJkrzFCwbEbaAFT)
 Call ID: call_aBw92kXhfEJkrzFCwbEbaAFT
  Args:
    args: ['5*3']
    config: {}
================================= Tool Message =================================
Name: Calculator

Error: ToolException("Too many arguments to single-input tool Calculator.\n                Consider using StructuredTool instead. Args: [['5*3'], {}]")
 Please fix your mistakes.

### Description

The code works fine when using the check_weather tool, but does not work when using the Calculator. This may have to do with the RunnableConfig changes done for Tool calls !

I also believe that specifying Pydantic model using args_schema prevents this issue from happening. Issue is causing the legacy stuff to break !

### System Info

langchain==0.2.12
langchain-anthropic==0.1.22
langchain-aws==0.1.16
langchain-community==0.2.11
langchain-core==0.2.29
langchain-experimental==0.0.64
langchain-ollama==0.1.0rc0
langchain-openai==0.1.21
langchain-text-splitters==0.2.1
langdetect==1.0.9
langgraph==0.2.3
langgraph-checkpoint==1.0.2
langserve==0.2.2
langsmith==0.1.84

**Comment by ccurme** [comment]
Instead of `LLMMathChain`, would it work to use a simple calculator tool? Here is one that uses similar code as `LLMMathChain`:
```python
@tool
def calculator(expression: str) -> str:
    """Calculate expression using Python's numexpr library.

    Useful for when you need to answer questions about math.
    This tool is only for math questions and nothing else.
    Only input math expressions.

    Expression should be a single line mathematical expression
    that solves the problem.

    Examples:
        "37593 * 67" for "37593 times 67"
        "37593**(1/5)" for "37593^(1/5)"
    """
    import math
    import numexpr

    local_dict = {"pi": math.pi, "e": math.e}
    return str(
        numexpr.evaluate(
            expression.strip(),
            global_dict={},  # restrict access to globals
            local_dict=local_dict,  # add common mathematical functions
        )
    )
```
This works in your snippet for me, although I believe you need to import `ChatOpenAI` from langchain-openai to use its tool calling features:
```
pip install --upgrade langchain-openai
```
```python
from langchain_openai import ChatOpenAI
```

**Comment by rhlarora84** [comment]
Sorry I should have been more clear here. The snippet was an example to highlight the issue that extending from BaseTool does not work anymore without specifying args_schema. Is that model of specifying tool going away?

**Comment by jinec** [comment]
@rhlarora84 Has this problem been solved now? How was it resolved? Online waiting

**Comment by rhlarora84** [comment]
I ended up moving to Langgraph based AgentExecutor where this wasn't an issue !
