### ISSUE TITLE
ChatOpenAI.with_structured_output(..., , method="json_schema")  does not support pydantic.v1.

### ISSUE THREAD

**Issue by gbaian10** [langchain-ai/langchain#25371]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```py
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from pydantic import BaseModel
from pydantic.v1 import BaseModel as BaseModelV1

load_dotenv()


class AddV1(BaseModelV1):
    """add two numbers"""

    a: int
    b: int


class AddV2(BaseModel):
    """add two numbers"""

    a: int
    b: int


model = ChatOpenAI(model="gpt-4o-2024-08-06")
v2_tool = model.with_structured_output(AddV2)  # work
v1_tool = model.with_structured_output(AddV1)  # work
v2_schema = model.with_structured_output(AddV2, method="json_schema")  # work
v1_schema = model.with_structured_output(AddV1, method="json_schema")  # not work

for m in [v2_tool, v1_tool, v2_schema, v1_schema]:
    print(m.invoke("What is 42 + 87?"))
```

### Error Message and Stack Trace (if applicable)

```plain
TypeError: Unsupported response_format type - <class '__main__.AddV1'>
```

### Description

`function_calling` supports pydantic.v1, but `json_schema` does not support pydantic.v1.

### System Info

langchain==0.2.13
langchain-core==0.2.30
langchain-openai==0.1.21

platform==linux
python-version==3.10.12

**Comment by baskaryan** [comment]
ah this is a limitation of the openai python sdk, it only accepts pydantic v2 in the new [`parse` method](https://platform.openai.com/docs/guides/structured-outputs/introduction?lang=python)

will think about best way to solve this. may just raise a warning and convert pydantic v1 objects to json schema
