### ISSUE TITLE
Weird results when making a serpapi chain with llama or gpt4all

### ISSUE THREAD

**Issue by hershkoy** [langchain-ai/langchain#2538]
Same code with OpenAI works. 

With llama or gpt4all, even though it searches the internet (supposedly), it gets the previous prime minister, and also it fails to search the age and find prime based on it.

Is it possible that there is something wrong with the converted model? 

![image](https://user-images.githubusercontent.com/13259380/230609352-d6ffd8c9-7ca8-4462-96c0-0dc8fef45819.png)

**Comment by captainst** [comment]
Got similar issues, with langchain version 0.0.136, 0.0.137, and the latest 0.0.138.
It seems that the model is not able to perform correct reasoning.
I feel it might be have something to do with the prompt generated by langchain library.
