### ISSUE TITLE
Check for OpenAI chat model is wrong due to different names in Azure

### ISSUE THREAD

**Issue by jnmarti** [langchain-ai/langchain#2540]
The `__new__` method of `BaseOpenAI` returns a `OpenAIChat` instance if the model name starts with `gpt-3.5-turbo` or `gpt-4`. 
https://github.com/hwchase17/langchain/blob/a31c9511e88f81ecc26e6ade24ece2c4d91136d4/langchain/llms/openai.py#L168

However, if you deploy the model in Azure OpenAI Service, the name does not include the period. The name instead is [gpt-35-turbo](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models), so the check above passes and returns the wrong class.

The check should consider the names on Azure.

**Comment by hwchase17** [comment]
for Azure, you should be using https://python.langchain.com/en/latest/modules/models/chat/integrations/azure_chat_openai.html

**Comment by jnmarti** [comment]
@hwchase17 thanks. I guess if you use that class you can avoid the casting that `BaseOpenAI` performs depending on the model name, but still the behavior of that class is confusing.
If you instantiate `OpenAI` with `gpt-3.5-turbo` it returns an instance of `OpenAIChat`, but if you instantiate from `AzureOpenAI` (which extends `BaseOpenAI`) with `gpt-35-turbo` it does not return an instance of `AzureOpenAIChat`.

Furthermore, the name of `gpt-4` is the same for both the standard OpenAI API and for Azure, so you need to check the class  in order to return the correct OpenAIChat class.

**Comment by shirkey** [comment]
Just to add a +1 for this issue as gpt-35-turbo supports both Completions and ChatCompletions interface. There are legitimate use cases for the Completions interface, such as returning multiple completion options, that this model can and does support when accessing directly from the Azure OpenAI API and openai library.
