### ISSUE TITLE
Password in cleartext was committed into the repo 😮

### ISSUE THREAD

**Issue by chrisle** [langchain-ai/langchain#25415]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

n/a

### Description

Recent commit includes hardcoded username and password for a MongoDB instance. 
I was able to connect to it and view the names of the collections.

See `CONNECTION_STRING` on line 28 here: https://github.com/langchain-ai/langchain/blob/0f45ac4088126746575d40959dabaadd787faeb6/libs/community/tests/integration_tests/vectorstores/test_azure_cosmos_db.py

### System Info

n/a

**Comment by chrisle** [comment]
@aayush3011

**Comment by ccurme** [comment]
Thank you @chrisle for the call out. I've updated the master branch, at least.

@aayush3011 I would consider that secret compromised.
