### ISSUE TITLE
Unstructured Markdown Loader object which requires also NLTK package

### ISSUE THREAD

**Issue by ENUMERA8OR** [langchain-ai/langchain#25473]
### URL

https://python.langchain.com/v0.2/docs/how_to/document_loader_markdown/

### Issue with current documentation:

Unstructured Markdown Loader object which requires the Unstructured package also requires NLTK package not mentioned in documentation page of Unstructured Markdown Loader object with title: How to load Markdown 

Error:

---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
[<ipython-input-4-ab71168dec69>](https://localhost:8080/#) in <cell line: 4>()
      2 loader = UnstructuredMarkdownLoader(markdown_path)
      3 
----> 4 data = loader.load()
      5 assert len(data) == 1
      6 assert isinstance(data[0], Document)

31 frames
[/usr/local/lib/python3.10/dist-packages/nltk/data.py](https://localhost:8080/#) in find(resource_name, paths)
    581     sep = "*" * 70
    582     resource_not_found = f"\n{sep}\n{msg}\n{sep}\n"
--> 583     raise LookupError(resource_not_found)
    584 
    585 

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

code example used mentioned on the documentation page:

%%time
import time

%pip install "unstructured[md]"
%pip install langchain_community

from langchain_community.document_loaders import UnstructuredMarkdownLoader
from langchain_core.documents import Document

markdown_path = "/content/README.md"
loader = UnstructuredMarkdownLoader(markdown_path)

data = loader.load()
assert len(data) == 1
assert isinstance(data[0], Document)
readme_content = data[0].page_content
print(readme_content[:250])

loader = UnstructuredMarkdownLoader(markdown_path, mode="elements")

data = loader.load()
print(f"Number of documents: {len(data)}\n")

for document in data[:2]:
    print(f"{document}\n")

### Idea or request for content:

Mention of NLTK package in the requisite documentation page

**Comment by paradiseHIT** [comment]
After I installed NLTK，run the code following the  https://python.langchain.com/v0.2/docs/how_to/document_loader_markdown/ 

it reports this error
OSError: No such file or directory: '/home/xxx/nltk_data/tokenizers/punkt/PY3_tab'

**Comment by ENUMERA8OR** [comment]
Yes, documentation needs to be updated.

**Comment by chaoStart** [comment]
> After I installed NLTK，run the code following the https://python.langchain.com/v0.2/docs/how_to/document_loader_markdown/
> 
> it reports this error OSError: No such file or directory: '/home/xxx/nltk_data/tokenizers/punkt/PY3_tab'

me too."NO such file ....PY_3tab"
