### ISSUE TITLE
AzureChatOpenAI's JSON mode fails with AttributeError: 'NoneType' object has no attribute 'beta'

### ISSUE THREAD

**Issue by danieldekay** [langchain-ai/langchain#25479]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Code from [langchain_openai v 0.1.20 documentation](https://api.python.langchain.com/en/latest/chat_models/langchain_openai.chat_models.azure.AzureChatOpenAI.html)

```python
from langchain_openai import AzureChatOpenAI
from pydantic.v1 import SecretStr

model = "gpt-4o"

llm = AzureChatOpenAI(
    azure_deployment=model,
    model=model,
    api_key=SecretStr(os.getenv("AZURE_OPENAI_API_KEY")),
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    openai_api_type="azure",
)

from typing import Optional

from langchain_core.pydantic_v1 import BaseModel, Field


class Joke(BaseModel):
    """Joke to tell user."""

    setup: str = Field(description="The setup of the joke")
    punchline: str = Field(description="The punchline to the joke")
    rating: Optional[int] = Field(description="How funny the joke is, from 1 to 10")


structured_llm = llm.with_structured_output(Joke)
structured_llm.invoke("Tell me a joke about cats")
```
This works: `Joke(setup='Why was the cat sitting on the computer?', punchline='Because it wanted to keep an eye on the mouse!', rating=7)`

```python
json_llm = llm.with_structured_output(method="json_mode")

ai_msg = json_llm.invoke(
    "Return a JSON object with key 'random_ints' and a value of 10 random ints in [0-99]"
)
ai_msg.content
```
This does not work: `AttributeError: 'NoneType' object has no attribute 'beta'
`

### Error Message and Stack Trace (if applicable)

```
File ~/Envs/gpt-researcher/lib/python3.11/site-packages/langchain_openai/chat_models/base.py:629, in BaseChatOpenAI._generate(self, messages, stop, run_manager, **kwargs)
             warnings.warn(
                 "Cannot currently include response headers when response_format is "
                 "specified."
             )
         payload.pop("stream")
-->      response = self.root_client.beta.chat.completions.parse(**payload)
     elif self.include_response_headers:
         raw_response = self.client.with_raw_response.create(**payload)

**AttributeError: 'NoneType' object has no attribute 'beta'**
```

### Description

* I am trying to use the AzureChatOpenAI in **JSON mode**
* When trying the code listed in the documentation
* It fails

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Fri Mar 29 23:14:13 UTC 2024
> Python Version:  3.12.4 (main, Jun  8 2024, 18:29:57) [GCC 11.4.0]

Package Information
-------------------
> langchain_core: 0.2.32
> langchain: 0.2.14
> langchain_community: 0.2.12
> langsmith: 0.1.99
> langchain_openai: 0.1.21
> langchain_text_splitters: 0.2.2
> langgraph: 0.2.3

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.3
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.2
> numpy: 1.26.4
> openai: 1.40.8
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by baskaryan** [comment]
fix landed and release in langchain-openai==0.1.22. Thank you for flagging!
