### ISSUE TITLE
TypeError: Got unknown type 'ToolMessage'.

### ISSUE THREAD

**Issue by Liberation-happy** [langchain-ai/langchain#25480]
### URL

https://langchain-ai.github.io/langgraph/tutorials/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

when I use ChatZhipuAI and langgraph, I meet this mistake, it seems that ChatZhipuAI do not support the ToolMessage. How can I solve this problem?

### Idea or request for content:

I think that make the class ChatZhipuAI support ToolMessage can solve the problem

**Comment by baskaryan** [comment]
consolidating discussion in #25490
