### ISSUE TITLE
TypeError: Got unknown type 'ToolMessage'.

### ISSUE THREAD

**Issue by Liberation-happy** [langchain-ai/langchain#25490]
### Issue with current documentation:

when use the ChatZhipuAi in langchain_community with langgraph to build a agent, the class ChatZhipuAi unkown the ToolMessage, this make the zhipuai can not use in langgraph.

### Idea or request for content:

to add the ToolMessage in ChatZhipuAI, I think this can solve this problem.

**Comment by maang-h** [comment]
@Liberation-happy  Can you paste your running code?
