### ISSUE TITLE
"from langchain_anthropic import ChatAnthropic" fails

### ISSUE THREAD

**Issue by BlakeQG** [langchain-ai/langchain#25507]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

After installing `!pip show langchain_anthropic`, I try to use it, but `from langchain_anthropic import ChatAnthropic` fails with

 `error: ImportError: cannot import name 'UsageMetadata' from 'langchain_core.messages.ai' (/home/bg/.local/lib/python3.10/site-packages/langchain_core/messages/ai.py)`

### Error Message and Stack Trace (if applicable)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[35], line 1
----> 1 from langchain_anthropic import ChatAnthropic

File ~/.local/lib/python3.10/site-packages/langchain_anthropic/__init__.py:1
----> 1 from langchain_anthropic.chat_models import ChatAnthropic, ChatAnthropicMessages
      2 from langchain_anthropic.llms import Anthropic, AnthropicLLM
      4 __all__ = ["ChatAnthropicMessages", "ChatAnthropic", "Anthropic", "AnthropicLLM"]

File ~/.local/lib/python3.10/site-packages/langchain_anthropic/chat_models.py:45
     30 from langchain_core.language_models.chat_models import (
     31     BaseChatModel,
     32     LangSmithParams,
     33     agenerate_from_stream,
     34     generate_from_stream,
     35 )
     36 from langchain_core.messages import (
     37     AIMessage,
     38     AIMessageChunk,
   (...)
     43     ToolMessage,
     44 )
---> 45 from langchain_core.messages.ai import UsageMetadata
     46 from langchain_core.messages.tool import tool_call_chunk as create_tool_call_chunk
     47 from langchain_core.output_parsers import (
     48     JsonOutputKeyToolsParser,
     49     PydanticToolsParser,
     50 )

ImportError: cannot import name 'UsageMetadata' from 'langchain_core.messages.ai' (/home/bg/.local/lib/python3.10/site-packages/langchain_core/messages/ai.py)

### Description

I am trying to explore langchain-anthropic https://pypi.org/project/langchain-anthropic/, but fail to import it.

### System Info

langchain==0.2.1
langchain-anthropic==0.1.23
langchain-chroma==0.1.1
langchain-cli==0.0.23
langchain-community==0.2.1
langchain-core==0.2.33
langchain-openai==0.1.7
langchain-text-splitters==0.2.0
langchainhub==0.1.16

platform (windows / linux / mac)

python: 3.10.12

**Comment by BlakeQG** [comment]
![Screenshot from 2024-08-16 12-51-24](https://github.com/user-attachments/assets/ce561a7b-a016-4c44-8a4b-3cd3e689af1d)

**Comment by isahers1** [comment]
Can you please try updating your langchain version by running `pip install -qU langchain`? Let me know if that doesn't work.

**Comment by efriis** [comment]
Could you also run 
```
import langchain_core
langchain_core.__version__
```
in your notebook? Based on the error, it seems your notebook kernel isn't actually using langchain core 0.2.33, which has this class :(

**Comment by efriis** [comment]
To resolve, I would recommend running
```
%pip install -U langchain-anthropic langchain-core
```
then restart your kernel and try again

will mark as resolved, and let me know if you are still getting this on core 0.2.33! I was unable to reproduce it with these versions.

**Comment by BlakeQG** [comment]
> Can you please try updating your langchain version by running `pip install -qU langchain`? Let me know if that doesn't work.

It works. Thanks
