### ISSUE TITLE
Ollama Model support For tool calling

### ISSUE THREAD

**Issue by jivaniyash** [langchain-ai/langchain#25555]
### URL

https://python.langchain.com/v0.2/docs/integrations/chat/ollama/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

DOC: <Issue related to /v0.2/docs/integrations/chat/ollama/>

Is it just one model [https://ollama.com/library/llama3-groq-tool-use] available for tool-calling for Ollama?

https://python.langchain.com/v0.2/docs/integrations/chat/ollama/#tool-calling

**Comment by gbaian10** [comment]
This mainly depends on whether the model itself supports it. You can check the models card on Ollama to find which models support tools.

Related blog: [Tool Support](https://ollama.com/blog/tool-support)
Card: [Model with Tools](https://ollama.com/search?c=tools)
