### ISSUE TITLE
create_tool_calling_agent only return tool result in json instead of a straightfoward answer

### ISSUE THREAD

**Issue by renyuantime** [langchain-ai/langchain#25568]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
```python
from langchain.agents import AgentExecutor, create_tool_calling_agent
prompt = ChatPromptTemplate.from_messages(
    [("system", "You are a helpful Finance/Investment AI assistant."),
        ("placeholder", "{chat_history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),]
)
tools = [get_income_statement_tool]
agent = create_tool_calling_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is apple's revenue on 2022? give me a short answer"})
```
### Error Message and Stack Trace (if applicable)

![屏幕截图 2024-08-20 144741](https://github.com/user-attachments/assets/87329e02-dc8d-4ad2-95c0-df5c7edcc788)

### Description

I built a create_tool_calling_agent that has the get_income_statement tool, which takes in company ticker,start_date, end_date and returns corresponding income statement data. when I asked "What is apple's revenue in 2022? ", the agent only returned me the data from the tools in JSON format instead of a text like' Apple's revenue in 2022 is xxxx'.( see picture) what went wrong, why can't the agent observer the tool result and return me a text with the answer of my question in it.   

### System Info

linux

**Comment by tanruixing88** [comment]
where is get_income_statement_tool in your example code comes from ?

**Comment by renyuantime** [comment]
> where is get_income_statement_tool in your example code comes from ?

it is my customized tool, takes in ticker, start_date, end_date, period and returns the income statement.

**Comment by keenborder786** [comment]
@renyuantime Do two things:
- early_stopping_method = 'generate' # force the agent to generate a human readable output.
- max_iterations = 25 # increase the number of iteration

**Comment by renyuantime** [comment]
> @renyuantime Do two things:
> 
> * early_stopping_method = 'generate' # force the agent to generate a human readable output.
> * max_iterations = 25 # increase the number of iteration

Thanks for the help! I tried the twos thing you pointed out,but it did not seem to work so far.  I honestly did not understand why the agent would just return the tool result in JSON instead having the llm look at the result and send an answer in text back, this is the trace on Langsimith [https://smith.langchain.com/public/a6c6054f-47da-409e-9fdb-d30884d6b310/r](url), seems like the observation part of an agent is missing here, let me know if you know how to fix this, thanks.   
![image](https://github.com/user-attachments/assets/6958f04d-30bc-40b2-b08c-f50c8a608bc2)

**Comment by renyuantime** [comment]
I  found out where I got wrong, I set
`return_direct=True`

when I build the tool.
'''python
get_income_statement_tool = StructuredTool.from_function(
    func=get_income_statement,
    name="get_income_statement_tool",
    description="Returns complete income statement of a company and shows the company’s revenues and expenses during a period (annual or quarter).",
    args_schema=IncomeStatementInput,
    return_direct=True,
    # coroutine= ... <- you can specify an async method if desired as well
)
'''

 it will send back tool result to user directly.
