### ISSUE TITLE
create_tool_calling_agent is not working for AzureChatOpenAI

### ISSUE THREAD

**Issue by thiyagu19841** [langchain-ai/langchain#25564]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_community.chat_models import AzureChatOpenAI
from langchain.agents import AgentExecutor,create_tool_calling_agent,tool

 self.llm: AzureChatOpenAI = AzureChatOpenAI(temperature=temperature,deployment_name=OPEN_API_DEPLOYMENT,model_name=OPEN_API_MODEL,openai_api_key=openai_api_key,
                                               openai_api_base=OPEN_API_BASE,openai_api_version=OPEN_API_VERSION)
                                               
   self.agent = create_tool_calling_agent(
                llm=self.llm,
                tools=[self.custom_tools],
                prompt=self.prompt
                )
        
        self.executor = AgentExecutor(agent=self.agent)

### Error Message and Stack Trace (if applicable)

  File "Python/3.10/lib/python/site-packages/langchain/agents/tool_calling_agent/base.py", line 99, in create_tool_calling_agent
    llm_with_tools = llm.bind_tools(tools)
  File "3.10/lib/python/site-packages/langchain_core/language_models/chat_models.py", line 1080, in bind_tools
    raise NotImplementedError()

### Description

I am trying to use create_tool_calling_agent with AzureChatOpenAI LLM; but i am always getting NotImplementedError from chat_models.py.   It seems bind_tools is not impelemented with langchain-core 0.2.27 or higher version.  Can you please help me how to solve this issue or any reference for custom impelementation for AzureOpenAI LLM for tools binding. 

### System Info

langchain-core==0.2.27

**Comment by ccurme** [comment]
Hello,

The `langchain_community` implementation of AzureChatOpenAI is deprecated. When I run your code locally it generates a warning:

> LangChainDeprecationWarning: The class `AzureChatOpenAI` was deprecated in LangChain 0.0.10 and will be removed in 1.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import AzureChatOpenAI`.

Installing `langchain-openai` and updating your import should resolve your issue. See associated AzureChatOpenAI docs [here](https://python.langchain.com/v0.2/docs/integrations/chat/azure_chat_openai/). Closing but will re-open if this does not resolve your issue.

Thanks!

**Comment by deepthireddyb** [comment]
agent = create_tool_calling_agent(llm, tools, prompt)  throwing NotImplementedError:  when llm is OpenAI gpt3.5
Can someone fix the issue?

**Comment by ccurme** [comment]
> agent = create_tool_calling_agent(llm, tools, prompt) throwing NotImplementedError: when llm is OpenAI gpt3.5 Can someone fix the issue?

Hello, can you please provide a minimal reproducible example and confirm whether you are using the chat model implemented in `langchain-community` or `langchain-openai`?
