### ISSUE TITLE
Could not parse LLM output when model changed from gpt-3.5-turbo to gpt-4

### ISSUE THREAD

**Issue by tanmayh-fg** [langchain-ai/langchain#2564]
Code: 
```
llm = ChatOpenAI(temperature=0, model_name='gpt-4')
tools = load_tools(["serpapi", "llm-math", "python_repl","requests_all","human"], llm=llm)
agent = initialize_agent(tools, llm, agent='zero-shot-react-description', verbose=True)
agent.run("When was eiffel tower built")
```
Output:

> _File [env/lib/python3.8/site-packages/langchain/agents/agent.py:365], in Agent._get_next_action(self, full_inputs)
>     363 def _get_next_action(self, full_inputs: Dict[str, str]) -> AgentAction:
> ...
> ---> 48     raise ValueError(f"Could not parse LLM output: `{llm_output}`")
>      49 action = match.group(1).strip()
>      50 action_input = match.group(2)
> 
> ValueError: Could not parse LLM output: `I should search for the year when the Eiffel Tower was built.`_

Same code with gpt 3.5 model:
```
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(temperature=0, model_name='gpt-3.5-turbo')
tools = load_tools(["serpapi", "llm-math", "python_repl","requests_all","human"], llm=llm)
agent = initialize_agent(tools, llm, agent='zero-shot-react-description', verbose=True)
agent.run("When was eiffel tower built")
```

Output:
> Entering new AgentExecutor chain...
I should search for this information
Action: Search
Action Input: "eiffel tower build date"
Observation: March 31, 1889
Thought:That's the answer to the question
Final Answer: The Eiffel Tower was built on March 31, 1889.

> Finished chain.
'The Eiffel Tower was built on March 31, 1889.'

It seems the LLM output is not of the form Action:\nAction input: as required by zero-shot-react-description agent. 

My langchain version is 0.0.134 and i have access to gpt4.

**Comment by kartikbhardwaj2000** [comment]
@tanmayh-fogteams  Your reasoning is absolutely right, LLM here is not spiting out content in the right format. 
This problem is expected out of LLMS since they were not trained to think in that format (Action: ,Action Input:) 
It tends to deviate from its instructions. To reduce the frequency of such issues, I recommend you to add a couple of examples in the prompt of zero-shot-react-agent, add min of 2 and  max of 4 examples.

Hope it helps

**Comment by tanmayh-fogteams** [comment]
@kartikbhardwaj2000 thanks a lot, this method worked and now gpt4 is working with multiple tools but another issue that popped up is
`Thought:I need the user to open the OAuth URL and grant permission
Action: Human
Action Input: Please authenticate using this url {url}
Observation: Human is not a valid tool, try another one.`
It is generating the correct oauth url but then deciding itself for some reason that the tool it selected is not valid even though it is a valid tool. 
Appreciate any help or ideas

**Comment by kartikbhardwaj2000** [comment]
@tanmayh-fogteams  
Again the same issue here, you have mentioned human tool as with small h in the tools. But in its output its capital H, Human.

**Comment by tanmayh-fogteams** [comment]
@kartikbhardwaj2000 yes changing that solved the issue, thanks again!

**Comment by saxoji** [comment]
agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION  solved the errors, my case

**Comment by engperini** [comment]
> @tanmayh-fogteams Your reasoning is absolutely right, LLM here is not spiting out content in the right format. This problem is expected out of LLMS since they were not trained to think in that format (Action: ,Action Input:) It tends to deviate from its instructions. To reduce the frequency of such issues, I recommend you to add a couple of examples in the prompt of zero-shot-react-agent, add min of 2 and max of 4 examples.
> 
> Hope it helps
Hi! I have this issue, but now when I use 'gpt-3.5-turbo', i have tested with 'gpt-4' model and it's working. Could please help me with how to add prompt example at @tanmayh-fg code? I really want to use gpt-3.5-turbo
