### ISSUE TITLE
docs: expand cache integrations

### ISSUE THREAD

**Issue by ccurme** [langchain-ai/langchain#25670]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Right now navigating to "Model caches" in the integration docs sidebar brings you to a [monolithic page](https://python.langchain.com/v0.2/docs/integrations/llm_caching/).

https://github.com/langchain-ai/langchain/pull/25113 introduced a caches/ folder and added detailed documentation for Redis there. It is currently not represented in the sidebar and is only discoverable via a link to it in the monolithic page.

We need to determine a sensible organization for the cache integration docs (e.g., split the monolithic page out into individual pages?).

**Comment by baskaryan** [comment]
related https://github.com/langchain-ai/langchain/issues/22618
