### ISSUE TITLE
"Unhashable Type: Tool" when using custom tool

### ISSUE THREAD

**Issue by aeturneus** [langchain-ai/langchain#2569]
The following custom tool definition triggers an "TypeError: unhashable type: 'Tool'"

@tool
def gender_guesser(query: str) -> str:
    """Useful for when you need to guess a person's gender based on their first name. Pass only the first name as the query, returns the gender."""
    d = gender.Detector()
    return d.get_gender(str)

llm = ChatOpenAI(temperature=5.0)
math_llm = OpenAI(temperature=0.0)
tools = load_tools(
    ["human", "llm-math", gender_guesser], 
    llm=math_llm,
)

agent_chain = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
)

**Comment by kimlage** [comment]
I'm having the same thing trying load this:

bash_tool = Tool(
        name="Bash",
        func=BashProcess().run,
        description="""A Bash shell. Use this to execute bash commands.
        Input should be a valid bash command.
        If you expect output it should be printed out.""",
    )
print("loading tools...")
# Next, let's load some tools to use. Note that the `llm-math` tool uses an LLM, so we need to pass that in.
tools = load_tools([bash_tool], llm=llm)

**Comment by aeturneus** [comment]
The issue appears to be that load_tools() isn't compatible with custom tools.

It's unclear from the documentation how to use custom tool definitions at the same time as existing tools.

**Comment by aeturneus** [comment]
This seemed to work:

`tools = load_tools(
    ["human", "llm-math"], 
    llm=math_llm,
)
tools = tools + [gender_guesser]`

**Comment by samuelbarbosaa** [comment]
Initializing an empty tools list first, then adding a custom tool worked for me:

tools = load_tools([], llm=math_llm)
tools = tools + [gender_guesser]

**Comment by iagobrandaowt** [comment]
> Initializing an empty tools list first, then adding a custom tool worked for me:
> 
> tools = load_tools([], llm=math_llm) tools = tools + [gender_guesser]

It helped for me

**Comment by dimaelzeinstudeo** [comment]
I used tools = tools + [custom_tool]
and had this error 'list' object has no attribute 'is_single_input' on the initialize_agent level 
Any potential solutions ?

**Comment by iagobrandaowt** [comment]
I was using version 0.0.195

**Comment by dimaelzeinstudeo** [comment]
@iagobrandaowt  thanks for the detail. That did not work
Is it maybe because my custom_tool doesn't use any LLM ?
tools = load_tools(["tool1","tool2"], llm=llm)
tools = tools + [custom_tool]
