### ISSUE TITLE
OllamaEmbeddings cannot be configured for external provider adding base_url and auth as documentation said

### ISSUE THREAD

**Issue by ClaReQurv** [langchain-ai/langchain#25697]
### URL

https://python.langchain.com/v0.2/docs/integrations/providers/ollama/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

As documentation here: [Ollama Embeddings](https://api.python.langchain.com/en/latest/embeddings/langchain_community.embeddings.ollama.OllamaEmbeddings.html) I would like to add base_url and auth as paramenter to the class. 
Here my configuration:
```python
from langchain_ollama import OllamaEmbeddings

class ReQurvEmbedder:
    """The ReQurv Embedder Module"""

    def __init__(self, embedder_model: str):
        self.embedder_model = embedder_model

    def ollama_embeddings(self):
        return OllamaEmbeddings(model="nomic-embed-text", base_url="[THE_URL]", auth="[THE_AUTH]")
```

but when I run the code it triggers error:
```
...    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for OllamaEmbeddings
base_url
  extra fields not permitted (type=value_error.extra)
```

is there a way to properly configure external OllamaEmbedding instance?

Thank you!

**Comment by zysoong** [comment]
Would it work if you write a child class extending the OllamaEmbeddings and then add the properties? (Do not use __init__ there. Use the pedantic style to define new properties)

**Comment by hwchase17** [comment]
I think this is because we haven't released the ollama package since this functionality was added @efriis

**Comment by CartierPierre** [comment]
OMG I really need this (I need to use No_Proxy=localhost)

**Comment by CartierPierre** [comment]
@efriis patch works for env loading, thanks !
Now I have a second problem with InMemoryVectorStore.from_texts(...)
```
File "/.venv/ollama_lanchain/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes) 
```
stuck in pending (cause it goes to proxy or something like this)

**Comment by fdojose** [comment]
Mean time, you can use LlamaIndex class:
https://docs.llamaindex.ai/en/stable/examples/embeddings/ollama_embedding/
It works for me.
