### ISSUE TITLE
prompty: Superfluous f-string templating causes prompt templaing to fail

### ISSUE THREAD

**Issue by matthieucx** [langchain-ai/langchain#25703]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Use a barebone `.prompty` file such as:

```yaml
---
name: IssuePrompt
description: A prompt used to infer the intent of a user's query
model:
  api: chat
---

user:
Tell me about {templating issues}.
````

And the following script in the same folder:

```python
from langchain_prompty import create_chat_prompt
from pathlib import Path

root_path = Path(__file__).parent
prompt_path = root_path / "issue.prompty"

templated_prompt = create_chat_prompt(prompt_path)
templated_prompt.invoke(inputs={})
```

### Error Message and Stack Trace (if applicable)

```log
Traceback (most recent call last):
  File "issue.py", line 8, in <module>
    templated_prompt.invoke({})
  File ".venv\Lib\site-packages\langchain_core\runnables\base.py", line 4475, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\runnables\base.py", line 1785, in _call_with_config
    context.run(
  File ".venv\Lib\site-packages\langchain_core\runnables\config.py", line 397, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\runnables\base.py", line 4341, in _invoke
    output = output.invoke(
             ^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\prompts\base.py", line 179, in invoke
    return self._call_with_config(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\runnables\base.py", line 1785, in _call_with_config
    context.run(
  File ".venv\Lib\site-packages\langchain_core\runnables\config.py", line 397, in call_func_with_variable_args
    return func(input, **kwargs)  # type: ignore[call-arg]
           ^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\prompts\base.py", line 153, in _format_prompt_with_error_handling
    _inner_input = self._validate_input(inner_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\langchain_core\prompts\base.py", line 145, in _validate_input     
    raise KeyError(
KeyError: "Input to ChatPromptTemplate is missing variables {'templating issues'}.  Expected: ['templating issues'] Received: []"
```

### Description

Hello everyone! Thank you for your work.

I am playing around with `langchain_prompty` and noticed that messages are rendered two times, once by Prompty using Mustache, and once by langchain by treating messages as f-strings.

So you have to process all inputs to your prompts to escape brakcets for them to be ignored by the f-string templating (so `{{ }}`instead of `{ }`, which could cause issues with Mustache if the content is a key in your inputs). This is a bit hacky and brittle. Would there be a way to avoid this sedonc templating? Below is a detailled explanation of how the templating(s) happens.

 `langchain_prompty` uses Mustache templates, as discussed in this [PR introducing the package](https://github.com/langchain-ai/langchain/pull/21346#discussion_r1596035508).

This templating happens like this:
- [Prompt creation using the prompty file](https://github.com/langchain-ai/langchain/blob/99f9a664a5381d4bcd0d38397b604cd562d4452c/libs/partners/prompty/langchain_prompty/langchain.py#L16) (call to `langchain_prompty.create_chat_prompt()`)
	- Which leads to the [processing of the prompty file](https://github.com/langchain-ai/langchain/blob/99f9a664a5381d4bcd0d38397b604cd562d4452c/libs/partners/prompty/langchain_prompty/utils.py#L142)
		- Which triggers the [Mustache templating](https://github.com/langchain-ai/langchain/blob/99f9a664a5381d4bcd0d38397b604cd562d4452c/libs/partners/prompty/langchain_prompty/renderers.py#L15)

After this initial templating, [the messages are processed by Langchain](https://github.com/langchain-ai/langchain/blob/99f9a664a5381d4bcd0d38397b604cd562d4452c/libs/partners/prompty/langchain_prompty/langchain.py#L28), which by default treats them as f-strings templates ([see source code](https://github.com/langchain-ai/langchain/blob/30f1bf24ac5f62b17dd71bc341fd3dfadd03893f/libs/core/langchain_core/prompts/chat.py#L1147)). Hence the issue.

Tagging you @wayliums as I saw you worked on the prompty integration into langchain.

Thanks!

### System Info

Happens on all systems and configurations.

**Comment by keenborder786** [comment]
@matthieucx I have created a PR which handles the issue that you are fixing.

**Comment by matthieucx** [comment]
@keenborder786 Thanks for taking so time to work on this.

I think here the issue lies in the double templating, which will always lead to issues because it's super hacky to process your inputs expecting it to be interpreted as a template when it does not need to be.

I think we would need to either remove [the Prompty templating](https://github.com/langchain-ai/langchain/blob/master/libs/partners/prompty/langchain_prompty/renderers.py#L15), or find another way to [create the prompt for LangChain
](https://github.com/langchain-ai/langchain/blob/master/libs/partners/prompty/langchain_prompty/langchain.py#L26) (so the call you modified), that templates the messages a second time.

I'll look into it
