### ISSUE TITLE
BlobLoader.yield_blobs returns Iterable, it should be Iterator like in BaseLoader

### ISSUE THREAD

**Issue by gabayben** [langchain-ai/langchain#25718]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

class BlobLoader(ABC):
    """Abstract interface for blob loaders implementation.

    Implementer should be able to load raw content from a storage system according
    to some criteria and return the raw content lazily as a stream of blobs.
    """

    @abstractmethod
    def yield_blobs(
        self,
    ) -> Iterable[Blob]:
        """A lazy loader for raw data represented by LangChain's Blob object.

        Returns:
            A generator over blobs
        """

### Description

BlobLoader.yield_blobs returns Iterable, it should be Iterator like in BaseLoader

### System Info

BlobLoader.yield_blobs returns Iterable, it should be Iterator like in BaseLoader

**Comment by gbaian10** [comment]
I tried it, and it does indeed return an Iterable object instead of an Iterator.

```py
from collections.abc import Iterable, Iterator

from langchain_community.document_loaders.blob_loaders.youtube_audio import (
    YoutubeAudioLoader,
)
from langchain_core.documents.base import Blob

urls = ["https://www.youtube.com/watch?v=xxxxx"]
save_dir = r"your_save_dir"
loader = YoutubeAudioLoader(urls, save_dir)
for x in loader.yield_blobs():
    print(isinstance(x, Iterator))  # False
    print(isinstance(x, Iterable))  # True
    print(isinstance(x, Blob))  # True
    for i in x:
        print(i)  # ok
    next(x)  # TypeError: 'Blob' object is not an iterator
```

**Comment by gbaian10** [comment]
I see. I mistakenly thought `Blob` needed to be an `Iterator`.
It is indeed an `Iterator` because it's a generator.

![image](https://github.com/user-attachments/assets/2b6f85df-2519-4cf2-841c-35012b5f7151)

If it's explicitly a generator, I'd prefer it to be written as `Generator[Blob, None, None]`.

However, it seems that LangChain often writes generators as `Iterator[...]`?
