### ISSUE TITLE
Can you assist \ provide an example how to stream response when using an agent?

### ISSUE THREAD

**Issue by moraneden** [langchain-ai/langchain#2577]

**Comment by tbscode** [comment]
Also curious on this one, I think it's just not possible at the moment right?

I mean streaming intermediate steps doesn't make that much sense, and you can already get feedback on the steps being executed using `return_intermediate_step = True` ( which I also haven't been able to use yet see https://github.com/hwchase17/langchain/issues/2431 ).

But getting a stream response for the final answer would be great. Or somehow receiving token callbacks for the final response?

**Comment by jakesteelman** [comment]
+1 for this. As @tbscode said, I don't really care about sending intermediate steps, I just want to reduce the perceived latency by my end user when they ask things that take awhile.

**Comment by pelyhe** [comment]
Any updates on this?

**Comment by sarulnat** [comment]
i thought this was possible using callbacks? see my response for chains here https://github.com/hwchase17/langchain/discussions/4444#discussioncomment-5893732

I think the langchain docs cover it for agents here https://python.langchain.com/en/latest/modules/callbacks/getting_started.html#using-multiple-handlers-passing-in-handlers
