### ISSUE TITLE
CSV Agent: ValueError: Could not parse LLM output: 

### ISSUE THREAD

**Issue by bleso-a** [langchain-ai/langchain#2581]
I am using the CSV agent to analyze transaction data. I keep getting `ValueError: Could not parse LLM output: ` for the prompts. The agent seems to know what to do.

Any fix for this error?

```
> Entering new AgentExecutor chain...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-27-bf3698669c48>](https://localhost:8080/#) in <cell line: 1>()
----> 1 agent.run("Analyse how the debit transaction has changed over the months")

8 frames
[/usr/local/lib/python3.9/dist-packages/langchain/agents/mrkl/base.py](https://localhost:8080/#) in get_action_and_input(llm_output)
     46     match = re.search(regex, llm_output, re.DOTALL)
     47     if not match:
---> 48         raise ValueError(f"Could not parse LLM output: `{llm_output}`")
     49     action = match.group(1).strip()
     50     action_input = match.group(2)

ValueError: Could not parse LLM output: `Thought: To analyze how the debit transactions have changed over the months, I need to first filter the dataframe to only include debit transactions. Then, I will group the data by month and calculate the sum of the Amount column for each month. Finally, I will observe the results.

```

**Comment by tbscode** [comment]
Looking at the code the issue seems to be that the output doesn't have the expected format which is prob an issue with using `gpt3.5-turbo` it just doesn't produce the expected `r"Action: (.*?)[\n]*Action Input:[\s]*(.*)"`.

Using `gpt-4` works for me in all examples that it failed before.

**Comment by bleso-a** [comment]
Thanks for this. But I am using `gpt-4` and I still got the error

**Comment by bleso-a** [comment]
@tbscode `davinci-003` seems to work though. But I am not getting the right out

**Comment by tbscode** [comment]
I think this really also depends on the prompt. I have some question that work also fine with `git3.5-turbo`.

Did you try different prompts & questions yet?

This might also depend on the agents / tools.

I'm testing this currently using the `Conversation Agent` with `GoogleSearchAPIWrapper` it works some times with `gpt3.5-turbo` & almost all of the time with `gpt-4`, I does sometimes seem to depend on the question if it works or doesn't.

**Comment by rafaelquintanilha** [comment]
Happens occasionally for me as well, both with `gpt-3.5-turbo` and `gpt-4`. One thing that seems to help is to include in the prompt some direct instructions like:

```
query = """ Analyse how the debit transaction has changed over the months
Don't forget to use the structure of Action, Action Input, etc.
""
```

**Comment by bleso-a** [comment]
@rafaelquintanilha Thank you for the tips. I will try it out

**Comment by manish-andankar** [comment]
Yes, I am also experiencing this issue quite frequently with csv agent. It appears to me that it's not related to model per se (gpt-3.5-turbo/davinci. I am not sure why the agent is unable to parse LLM output. I tried both ChatOpenAI and OpenAI model wrappers, but the issue exists in both. This issue is opened since April, and I am not sure if there are any workarounds for this or fixes in pipeline. Any help or suggestion is highly appreciated.

**Comment by Dessix** [comment]
The problem is lack of a grammar constraint on the outputs. It's not stale, and it's one of a class of issues of this shape. The introduction of Guidance or LMQL would solve this issue and, in many cases, improve energy efficiency of evaluation.
