### ISSUE TITLE
Issue with authenticating Azure National Cloud using token (RBAC)

### ISSUE THREAD

**Issue by green999** [langchain-ai/langchain#25823]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

vector_store = AzureSearch(
        azure_search_endpoint=AZURE_SEARCH_ENDPOINT,
        azure_search_key=None,
        index_name=AZURE_SEARCH_INDEX_NAME,
        embedding_function=embeddings.embed_query,
        additional_search_client_options={"audience":"https://search.azure.us"}
    )    

I get authentication error, when I try to use with GovCloud & RBAC. I temporarily fixed it locally by modifying the code as mentioned in the description below. 

### Error Message and Stack Trace (if applicable)

N/A

### Description

To authenticate in a [National Cloud](https://learn.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud), the audience must be passed. 

The line 124  in azuresearch.py should be added with **additional_search_client_options parameter. 

In line 226, SearchClient is accepting the **additional_search_client_options parameter properly, but missed for SearchIndexClient on line 124. 

### System Info

Windows. 
Python                                    3.11
langchain                                0.2.14
langchain-cli                            0.0.29
langchain-community              0.2.12
langchain-core                         0.2.33

**Comment by ccurme** [comment]
@green999 thanks for reporting this and for your suggested fix. Regarding passing `additional_search_client_options` into `SearchIndexClient`-- a naive reading of the code suggests that these params are specifically for the `SearchClient`. If there is a single parameter in `additional_search_client_options` that `SearchIndexClient` does not accept, would this break? Are they guaranteed to accept the same params? Or do we need a new field for the index params?

**Comment by green999** [comment]
I dont think so, it is applicable to 3 libraries. As per this document keyword Arguments has to set for SearchClient, SearchIndexClient, or SearchIndexerClient
https://github.com/langchain-ai/langchain/issues/25823

[SearchClient ](https://github.com/langchain-ai/langchain/issues/25823)and [SearchIndexClient](https://github.com/langchain-ai/langchain/issues/25823) and SearchIndexerClient, all accepts the same kwArgs. 

It has been implemented correctly with "additional_search_client_options" parameter in SearchClient, but needs to added on other places as well. May be the "additional_search_client_options" can be changed to "additional_search_options" to avoid any confusion with client libraries.

**Comment by green999** [comment]
Basically I modified the code in two places in azuresearch.py

**In line 124,** modified to like this

 index_client: SearchIndexClient = 

SearchIndexClient(

        endpoint=endpoint, credential=credential, user_agent=user_agent,**additional_search_client_options,
)

**Line 318**, in _get_search_client I added this line at the end (additional_search_client_options=additional_search_client_options,)

      user_agent = "langchain"
        if "user_agent" in kwargs and kwargs["user_agent"]:
            user_agent += " " + kwargs["user_agent"]
        self.client = _get_search_client(
            azure_search_endpoint,
            azure_search_key,
            index_name,
            semantic_configuration_name=semantic_configuration_name,
            fields=fields,
            vector_search=vector_search,
            semantic_configurations=semantic_configurations,
            scoring_profiles=scoring_profiles,
            default_scoring_profile=default_scoring_profile,
            default_fields=default_fields,
            user_agent=user_agent,
            cors_options=cors_options,
            **additional_search_client_options=additional_search_client_options**,
        )
