### ISSUE TITLE
Receiving a "node:internal/errors:490" error when running the streaming example code from the langchain docs

### ISSUE THREAD

**Issue by jg26396** [langchain-ai/langchain#2590]
Good afternoon, I am having a problem when it comes to streaming responses. I am trying to use the example provided by the langchain docs and I can't seem to get it working without editing the package.json file from langchain lol. 

Here is the code I ran
`import * as env from "dotenv"
import { OpenAI } from "langchain/llms"
import { CallbackManager } from "langchain/dist/callbacks"
env.config()

//const apiKey = process.env.OPEN_API_KEY
const chat = new OpenAI({
    streaming: true,
    callbackManager: CallbackManager.fromHandlers({
      async handleLLMNewToken(token) {
        console.log(token);
      },
    }),
  });
  
  const response = await chat.call("Write me a song about sparkling water.");
  console.log(response);`

And the error I received when running it: 

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/callbacks' is not defined by "exports" in home/jg//Langchain_Test_Programs/LLM_Quickstart/node_modules/langchain/package.json imported from home/jg//Langchain_Test_Programs/LLM_Quickstart/app.js
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:266:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:602:9)
    at packageResolve (node:internal/modules/esm/resolve:777:14)
    at moduleResolve (node:internal/modules/esm/resolve:843:20)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:309:30)
    at ESMLoader.resolve (node:internal/modules/esm/loader:312:26)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:172:38) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

I searched for awhile to find a solution and I eventually did by renaming the ./callbacks in the export section of the langchain package.json to ./dist/calbacks 

i.e. I changed 
`"./callbacks": {
      "types": "./callbacks.d.ts",
      "import": "./callbacks.js",
      "require": "./callbacks.cjs"
    },` 
to 
`"./dist/callbacks": {
      "types": "./callbacks.d.ts",
      "import": "./callbacks.js",
      "require": "./callbacks.cjs"
    },`

This worked for me but then I ran into two more issues: A. The text takes forever to be streamed and B. when the text is streamed, it is returned at an extremely fast paced. So fast that I cant keep up with it when trying to read. I don't know if that is how it's supposed to be but I was hoping for the text to be returned slow, like it is done through the chatgpt official site. 

I know there is probably a much simpler fix but I can't seem to find it. Any help will be appreciated it, thanks!

**Comment by jg26396** [comment]
After walking away and coming back, I realized I caused my own problems... :| 

I added "dist/" to the import function , when it should only be import { CallbackManager } from "langchain/callbacks"

I knew it had to be something simple but I am still having trouble with the speed at which the stream is being returned so any help there would be greatly appreciated.

**Comment by alejandromicheloud** [comment]
Try change import.
From `import { CallbackManager } from "langchain/dist/callbacks"`
To `import { CallbackManager } from "langchain/callbacks";`
Regards!
