### ISSUE TITLE
Feature Request: Allow VectorStoreIndexCreator to retrieve stored vector indexes

### ISSUE THREAD

**Issue by Joldnine** [langchain-ai/langchain#2591]
The foundational chain and ChromaDB possess the capacity for persistence.

 It would be beneficial to make this persistence feature accessible to the higher-level VectorstoreIndexCreator. 

By doing so, we can repurpose saved indexes, making the service more easily scalable, particularly for handling extensive documents.

**Comment by Satish-Barnala** [comment]
This feature will really help as we have a big knowledge base (documents). We would like to create and save the Vector Index to be used later in a QnA bot.

**Comment by UmerHA** [comment]
@Joldnine Can you provide a code example of how this feature would be used?

Then, I'll be on it 🫡
