### ISSUE TITLE
AssertionError in LlamaCpp

### ISSUE THREAD

**Issue by soleimanian** [langchain-ai/langchain#2592]
Hi,
When I run this:
from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])

llm = LlamaCpp(model_path="models/gpt4all-lora-quantized.bin", n_ctx=2048)

llm_chain = LLMChain(prompt=prompt, llm=llm)
print(llm_chain("tell me about Japan"))

I got the below error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13664/3459006187.py in <module>
     11 
     12 llm_chain = LLMChain(prompt=prompt, llm=llm)
---> 13 print(llm_chain("tell me about Japan"))

f:\python39\lib\site-packages\langchain\chains\base.py in __call__(self, inputs, return_only_outputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116             raise e
    117         self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118         return self.prep_outputs(inputs, outputs, return_only_outputs)

f:\python39\lib\site-packages\langchain\chains\base.py in __call__(self, inputs, return_only_outputs)
    111         )
    112         try:
--> 113             outputs = self._call(inputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)

f:\python39\lib\site-packages\langchain\chains\llm.py in _call(self, inputs)
     55 
     56     def _call(self, inputs: Dict[str, Any]) -> Dict[str, str]:
---> 57         return self.apply([inputs])[0]
     58 
     59     def generate(self, input_list: List[Dict[str, Any]]) -> LLMResult:

f:\python39\lib\site-packages\langchain\chains\llm.py in apply(self, input_list)
    116     def apply(self, input_list: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    117         """Utilize the LLM generate method for speed gains."""
--> 118         response = self.generate(input_list)
    119         return self.create_outputs(response)
    120 

f:\python39\lib\site-packages\langchain\chains\llm.py in generate(self, input_list)
     60         """Generate LLM result from inputs."""
     61         prompts, stop = self.prep_prompts(input_list)
---> 62         return self.llm.generate_prompt(prompts, stop)
     63 
     64     async def agenerate(self, input_list: List[Dict[str, Any]]) -> LLMResult:

f:\python39\lib\site-packages\langchain\llms\base.py in generate_prompt(self, prompts, stop)
    105     ) -> LLMResult:
    106         prompt_strings = [p.to_string() for p in prompts]
--> 107         return self.generate(prompt_strings, stop=stop)
    108 
    109     async def agenerate_prompt(

f:\python39\lib\site-packages\langchain\llms\base.py in generate(self, prompts, stop)
    138             except (KeyboardInterrupt, Exception) as e:
    139                 self.callback_manager.on_llm_error(e, verbose=self.verbose)
--> 140                 raise e
    141             self.callback_manager.on_llm_end(output, verbose=self.verbose)
    142             return output

f:\python39\lib\site-packages\langchain\llms\base.py in generate(self, prompts, stop)
    135             )
    136             try:
--> 137                 output = self._generate(prompts, stop=stop)
    138             except (KeyboardInterrupt, Exception) as e:
    139                 self.callback_manager.on_llm_error(e, verbose=self.verbose)

f:\python39\lib\site-packages\langchain\llms\base.py in _generate(self, prompts, stop)
    322         generations = []
    323         for prompt in prompts:
--> 324             text = self._call(prompt, stop=stop)
    325             generations.append([Generation(text=text)])
    326         return LLMResult(generations=generations)

f:\python39\lib\site-packages\langchain\llms\llamacpp.py in _call(self, prompt, stop)
    182 
    183         """Call the Llama model and return the output."""
--> 184         text = self.client(
    185             prompt=prompt,
    186             max_tokens=params["max_tokens"],

f:\python39\lib\site-packages\llama_cpp\llama.py in __call__(self, prompt, suffix, max_tokens, temperature, top_p, logprobs, echo, stop, repeat_penalty, top_k, stream)
    525             Response object containing the generated text.
    526         """
--> 527         return self.create_completion(
    528             prompt=prompt,
    529             suffix=suffix,

f:\python39\lib\site-packages\llama_cpp\llama.py in create_completion(self, prompt, suffix, max_tokens, temperature, top_p, logprobs, echo, stop, repeat_penalty, top_k, stream)
    486             chunks: Iterator[CompletionChunk] = completion_or_chunks
    487             return chunks
--> 488         completion: Completion = next(completion_or_chunks)  # type: ignore
    489         return completion
    490 

f:\python39\lib\site-packages\llama_cpp\llama.py in _create_completion(self, prompt, suffix, max_tokens, temperature, top_p, logprobs, echo, stop, repeat_penalty, top_k, stream)
    303         stream: bool = False,
    304     ) -> Union[Iterator[Completion], Iterator[CompletionChunk],]:
--> 305         assert self.ctx is not None
    306         completion_id = f"cmpl-{str(uuid.uuid4())}"
    307         created = int(time.time())

AssertionError:

**Comment by beingPurple** [comment]
I am having the same issue, have you made any progress?

**Comment by abetlen** [comment]
@beingPurple @soleimanian sorry guys, the error is confusing (I'll fix in the next release), self.ctx == None usually means the path to the model file is wrong or the model file needs to be converted to a newer version of the llama.cpp ggml format.
