### ISSUE TITLE
DOC: Bulleted list doesn't render correctly in new UX

### ISSUE THREAD

**Issue by cab938** [langchain-ai/langchain#25935]
### URL

https://python.langchain.com/v0.2/api_reference/core/runnables/langchain_core.runnables.base.RunnableBinding.html

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

As shown in the image, the RunnableBinding has an itemized list which doesn't render nicely, as it puts all bullets in one paragraph.

![image](https://github.com/user-attachments/assets/92596acc-eec4-4fbb-9dc0-f3581829eb2d)

### Idea or request for content:

A pretty rendering :)

**Comment by baskaryan** [comment]
should be fixed, thank you for flagging @cab938!
