### ISSUE TITLE
[BUG]: TypeError: unhashable type: 'list' - "Meta-Llama-3.1-8B-Instruct" HuggingFacePipeline

### ISSUE THREAD

**Issue by kklivil** [langchain-ai/langchain#25931]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_huggingface.llms import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
import torch

model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

pipeline(
        task="text-generation",
        model=model_id,
        model_kwargs={"torch_dtype": torch.bfloat16},
        device_map="auto",
        use_fast=True,
        do_sample=True,
        top_k=3,
        max_new_tokens=40,
        token="XXXXX" # Replace with your token.
    )

hf = HuggingFacePipeline(pipeline=pipeline)

template = """Question: {question}

Answer: Let's think step by step."""
prompt = PromptTemplate.from_template(template)

chain = prompt | hf

question = "What is electroencephalography?"

print(chain.invoke({"question": question}))

```

### Error Message and Stack Trace (if applicable)

Traceback (most recent call last):
  File "/home/ec2-user/test_models/smart_reply/langchain_llama3_1_8b.py", line 35, in <module>
    print(chain.invoke({"question": question}))
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2878, in invoke
    input = context.run(step.invoke, input, config)
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 385, in invoke
    self.generate_prompt(
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 750, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 944, in generate
    output = self._generate_helper(
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 787, in _generate_helper
    raise e
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 774, in _generate_helper
    self._generate(
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/langchain_huggingface/llms/huggingface_pipeline.py", line 269, in _generate
    responses = self.pipeline(
  File "/home/ec2-user/test_models/smart_reply/env/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 831, in pipeline
    if task in custom_tasks:
TypeError: unhashable type: 'list'

### Description

I am trying to experiment with `llama3.1-8b-instruct` model. I used the reference code given in the doc here:
https://python.langchain.com/v0.2/docs/integrations/llms/huggingface_pipelines/

I am not able to generate the inference and getting error as shown above.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Mon Jul 29 19:52:29 UTC 2024
> Python Version:  3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]

Package Information
-------------------
> langchain_core: 0.2.37
> langchain: 0.2.15
> langsmith: 0.1.108
> langchain_huggingface: 0.0.3
> langchain_llama3_1_8b: Installed. No version info available.
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.3
> async-timeout: 4.0.3
> httpx: 0.27.2
> huggingface-hub: 0.24.3
> jsonpatch: 1.33
> numpy: 1.26.4
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 1.10.18
> PyYAML: 6.0.2
> requests: 2.32.3
> sentence-transformers: 3.0.1
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tokenizers: 0.19.1
> transformers: 4.44.2
> typing-extensions: 4.12.2

**Comment by NotShrirang** [comment]
Hey @kklivil!

You can use the code given below!

```python
from langchain_huggingface.llms import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
import torch

model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

pipeline = pipeline (
            task="text-generation",
            model=model_id,
            model_kwargs={"torch_dtype": torch.bfloat16},
            device_map="auto",
            use_fast=True,
            do_sample=True,
            top_k=3,
            max_new_tokens=40,
            token="XXXXX" # Replace with your token.
          )

hf = HuggingFacePipeline(pipeline=pipeline)

template = """Question: {question}

Answer: Let's think step by step."""
prompt = PromptTemplate.from_template(template)

chain = prompt | hf

question = "What is electroencephalography?"

print(chain.invoke({"question": question}))
```

An even better version would be:
```python
from langchain_huggingface.llms import HuggingFacePipeline
from langchain_core.prompts import PromptTemplate
import torch

model_id = "meta-llama/Meta-Llama-3.1-8B-Instruct"

hf = HuggingFacePipeline.from_model_id(
    model_id=model_id,
    task="text-generation",
)

template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate.from_template(template)

chain = prompt | hf

question = "What is electroencephalography?"

print(chain.invoke({"question": question}))
```

**Comment by kklivil** [comment]
Thanks, Guys it worked!
