### ISSUE TITLE
ChromaDB Vectorstore: Customize distance calculations

### ISSUE THREAD

**Issue by rkeshwani** [langchain-ai/langchain#2595]
Right now the langchain chroma vectorstore doesn't allow you to adjust the metadata attribute on the create collection method of the ChromaDB client so you can't adjust the formula for distance calculations. 

Chroma DB introduced the ability to add metadata to collections to tell the index which distance calculation is used in release https://github.com/chroma-core/chroma/releases/tag/0.3.15

Specifically in this pull request: https://github.com/chroma-core/chroma/pull/245

Langchain doesn't provide a way to adjust this vectorstore's distance calculation formula.
Referenced here: https://github.com/hwchase17/langchain/blob/2f49c96532725fdb48ea11417270245e694574d1/langchain/vectorstores/chroma.py#L84

**Comment by rkeshwani** [comment]
Created Pull request to add this ability. Tests appeared to pass but I didn't see a test specific for ChromaDB to fully test this functionality.

**Comment by jasonslyvia** [comment]
ping, would love to use different distance methods other than the defaulted 'l2'
