### ISSUE TITLE
PyPDFLoader introduces additional white spaces before umlauts in the middle of the word

### ISSUE THREAD

**Issue by nataliia-obraztsova** [langchain-ai/langchain#25968]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader(self.file_name)
self.data = loader.load_and_split()
```

### Description

I'm loading data from pdf.

**the original pdf text:**
 
Änderungen, Ergänzungen und Nebenabreden bedürfen der Schriftform, dies gilt auch für die
Aufhebung der Schriftform selbst. Sollten einzelne Bestimmungen dieses Vertrags unwirksam

**is processed by PyPDFLoader as:**
 
Änderungen, Erg änzungen und Nebenabreden bedürfen der Schriftform, dies gilt auch f ür die 
Aufhebung der Schriftform selbst. Sollten einzelne Bestimmungen dieses Vertrags unwirksam

Additional white spaces were introduced: Ergänzungen -> Erg änzungen and für -> f ür

## Expected behaviour:
**loaded text is:**
Änderungen, Ergänzungen und Nebenabreden bedürfen der Schriftform, dies gilt auch für die
Aufhebung der Schriftform selbst. Sollten einzelne Bestimmungen dieses Vertrags unwirksam

PDF file (page 3):
[Extraction_Demo_Vertrag_Darth_Vder Galt.pdf](https://github.com/user-attachments/files/16849967/Extraction_Demo_Vertrag_Darth_Vder.Galt.pdf)

### System Info

langchain==0.2.15
langchain-community==0.2.15
langchain-core==0.2.37
langchain-openai==0.1.23
langchain-text-splitters==0.2.2

**Comment by venkatram-dev** [comment]
PyMuPDFLoader works better

```
from langchain_community.document_loaders import PyMuPDFLoader
file_name = 'm.pdf'
loader = PyMuPDFLoader(file_name)
data = loader.load_and_split()
print ('data',data)

```

Attached is result from it 
![Screenshot 2024-09-03 at 1 14 46 PM](https://github.com/user-attachments/assets/24f1d34e-7c4a-4158-b84d-7a270986839e)
