### ISSUE TITLE
Feature request: conversation agent (chat mode) to support in-house (http) service

### ISSUE THREAD

**Issue by MichaelChen1234** [langchain-ai/langchain#2598]
Many use-cases are companies (in different industries) integrating chatgpt api with calling their own in-house services (via http, etc), and LLMs(ChatGPT) have no knowledge of these services.

Just wanted to check current prompts for agents (e.g https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational_chat/prompt.py), do they work for in-house services?

Read the [doc](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/openapi.html) for OpenAPI agents, it supports APIs conformant to the OpenAPI/Swagger specification, does it support in-house API as well (suppose in-house APIs also conformant to the OpenAPI/Swagger specification)?

Or maybe like how `langchain` supports ChatGPT plugins (https://python.langchain.com/en/latest/modules/agents/tools/examples/chatgpt_plugins.html?highlight=chatgpt%20plugin#chatgpt-plugins), providing in-house API provides detailed API spec.

**Comment by philipk19238** [comment]
I think your use case is represented by the Agent Tools. You can define a Tool, give it a description, and have it accept input from the LLM. Langchain will automatically execute the code powering the tool.

More: https://python.langchain.com/en/latest/modules/agents/tools.html

**Comment by MichaelChen1234** [comment]
1. I forgot mentioning another scenario : chatbot mode - i.e hold a conversation in addition to call in-house services
    e.g user : "hi", chatbot : "hi!", user : "I want to book a ticket on Sep 6, 2023". chatbot: (calling ticket service)
2. In addition to tool description, would it help to also inject tool's specific API schema (e.g OpenAPI schema), into prompt, so that ChatGPT API can automatically figure out passing what values to which parameters of the tool's API.
