### ISSUE TITLE
Supabase vectorstore uses different schema from docs

### ISSUE THREAD

**Issue by tristanbob** [langchain-ai/langchain#26017]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

N/A

### Error Message and Stack Trace (if applicable)

Error Building Component
Error building Component Supabase: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "e6ab58f8-c30b-44a7-b1d7-708a9650e6e7"'}

### Description

The Langchain Supabase vectorstore is expecting a `uuid` primary key for documents:

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/supabase.py

However, both the Langchain and Supabase docs use a `bigserial` for the data type.

Langchain:
https://js.langchain.com/v0.2/docs/integrations/vectorstores/supabase/

Supabase:
https://supabase.com/docs/guides/ai/langchain?queryGroups=database-method&database-method=sql

When I changed my schema to use the `uuid`, I was able to use the Supabase vectorstore (via Langflow).

The long-term fix is to change Langchain from `uuid` to `bigserial`.

### System Info

N/A

**Comment by tristanbob** [comment]
I also discovered Supabase under Retriever, which tells the user to use UUID as the primary key.

We should probably pick one data type for all Langchain interactions with Supabase.

https://python.langchain.com/v0.1/docs/integrations/retrievers/self_query/supabase_self_query/#setup-supabase-database

**Comment by gregnr** [comment]
Good find @tristanbob, thanks for uncovering this. We're definitely inconsistent between languages which is confusing. At the moment it is basically:
- Python [docs](https://python.langchain.com/docs/integrations/vectorstores/supabase/) and [code](https://github.com/langchain-ai/langchain/blob/a47b33284152d85d2233f069f993f9c0ef4da0d7/libs/community/langchain_community/vectorstores/supabase.py#L117-L128) expect `uuid` IDs
- JS [docs](https://js.langchain.com/docs/integrations/vectorstores/supabase/) and [code](https://github.com/langchain-ai/langchainjs/blob/3bb7bce33ab3f482f870ddf709515d5840b2f7a0/libs/langchain-community/src/vectorstores/supabase.ts#L214-L224) expect `bigint` IDs (the linked Supabase docs assume JS)

I agree the best long term solution is `bigint` (auto-generated) everywhere which is more consistent with typical Postgres tables, or at least using this by default (with option to pass custom IDs if you really want). This is likely a breaking change on the Python side, unless you can think of a way to do this without breaking existing users.

@baskaryan is there any sort of semver contract on langchain-community, or is it pretty much expected to never have breaking changes?
