### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'acall' with PropertyGraphIndex

### ISSUE THREAD

**Issue by luisramosbosch** [langchain-ai/langchain#26030]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

With the following code I try to create an index from docs:
# Extract graph from documents
index = PropertyGraphIndex.from_documents(
    documents,
    embed_model=OpenAIEmbedding(model_name="text-embedding-3-small"),
    kg_extractors=kg_extractor,
    property_graph_store=graph_store,
    show_progress=True,
)

based in [example](https://neo4j.com/labs/genai-ecosystem/llamaindex/#_neo4jpropertygraphstore)

However, I get the error indicated below

### Error Message and Stack Trace (if applicable)

Parsing nodes: 100%
 2/2 [00:00<00:00, 64.50it/s]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[31], line 3
      1 #filling out graph
      2 # Extract graph from documents
----> 3 index = PropertyGraphIndex.from_documents(
      4     documents,
      5     embed_model=OpenAIEmbedding(model_name="text-embedding-3-small"),
      6     kg_extractors=kg_extractor,
      7     property_graph_store=graph_store,
      8     show_progress=True,
      9 )

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\base.py:119, in BaseIndex.from_documents(cls, documents, storage_context, show_progress, callback_manager, transformations, **kwargs)
    110     docstore.set_document_hash(doc.get_doc_id(), doc.hash)
    112 nodes = run_transformations(
    113     documents,  # type: ignore
    114     transformations,
    115     show_progress=show_progress,
    116     **kwargs,
    117 )
--> 119 return cls(
    120     nodes=nodes,
    121     storage_context=storage_context,
    122     callback_manager=callback_manager,
    123     show_progress=show_progress,
    124     transformations=transformations,
    125     **kwargs,
    126 )

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\property_graph\base.py:134, in PropertyGraphIndex.__init__(self, nodes, llm, kg_extractors, property_graph_store, vector_store, use_async, embed_model, embed_kg_nodes, callback_manager, transformations, storage_context, show_progress, **kwargs)
    128 self._embed_kg_nodes = embed_kg_nodes
    129 self._override_vector_store = (
    130     vector_store is not None
    131     or not storage_context.property_graph_store.supports_vector_queries
    132 )
--> 134 super().__init__(
    135     nodes=nodes,
    136     callback_manager=callback_manager,
    137     storage_context=storage_context,
    138     transformations=transformations,
    139     show_progress=show_progress,
    140     **kwargs,
    141 )

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\base.py:77, in BaseIndex.__init__(self, nodes, objects, index_struct, storage_context, callback_manager, transformations, show_progress, **kwargs)
     75 if index_struct is None:
     76     nodes = nodes or []
---> 77     index_struct = self.build_index_from_nodes(
     78         nodes + objects,
     79         **kwargs,  # type: ignore
     80     )
     81 self._index_struct = index_struct
     82 self._storage_context.index_store.add_index_struct(self._index_struct)

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\base.py:185, in BaseIndex.build_index_from_nodes(self, nodes, **build_kwargs)
    183 """Build the index from nodes."""
    184 self._docstore.add_documents(nodes, allow_update=True)
--> 185 return self._build_index_from_nodes(nodes, **build_kwargs)

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\property_graph\base.py:328, in PropertyGraphIndex._build_index_from_nodes(self, nodes)
    326 def _build_index_from_nodes(self, nodes: Optional[Sequence[BaseNode]]) -> IndexLPG:
    327     """Build index from nodes."""
--> 328     nodes = self._insert_nodes(nodes or [])
    330     # this isn't really used or needed
    331     return IndexLPG()

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\indices\property_graph\base.py:198, in PropertyGraphIndex._insert_nodes(self, nodes)
    196 # run transformations on nodes to extract triplets
    197 if self._use_async:
--> 198     nodes = asyncio.run(
    199         arun_transformations(
    200             nodes, self._kg_extractors, show_progress=self._show_progress
    201         )
    202     )
    203 else:
    204     nodes = run_transformations(
    205         nodes, self._kg_extractors, show_progress=self._show_progress
    206     )

File ~\AppData\Local\anaconda3\lib\site-packages\nest_asyncio.py:30, in _patch_asyncio.<locals>.run(main, debug)
     28 task = asyncio.ensure_future(main)
     29 try:
---> 30     return loop.run_until_complete(task)
     31 finally:
     32     if not task.done():

File ~\AppData\Local\anaconda3\lib\site-packages\nest_asyncio.py:98, in _patch_loop.<locals>.run_until_complete(self, future)
     95 if not f.done():
     96     raise RuntimeError(
     97         'Event loop stopped before Future completed.')
---> 98 return f.result()

File ~\AppData\Local\anaconda3\lib\asyncio\futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception.with_traceback(self._exception_tb)
    202 return self._result

File ~\AppData\Local\anaconda3\lib\asyncio\tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File ~\AppData\Local\anaconda3\lib\site-packages\llama_index\core\ingestion\pipeline.py:137, in arun_transformations(nodes, transformations, in_place, cache, cache_collection, **kwargs)
    135             cache.put(hash, nodes, collection=cache_collection)
    136     else:
--> 137         nodes = await transform.acall(nodes, **kwargs)
    139 return nodes

AttributeError: 'tuple' object has no attribute 'acall'

### Description

The graph is not generated as expected. 

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.36
> langchain: 0.2.15
> langchain_community: 0.2.14
> langsmith: 0.1.107
> langchain_experimental: 0.0.64
> langchain_openai: 0.1.23
> langchain_text_splitters: 0.2.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: 4.0.3
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.43.0
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.32
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by baskaryan** [comment]
this is an issue with `llama-index` not langchain:

```
File ...\llama_index\core\indices\base.py:119, in BaseIndex.from_documents(cls, documents, storage_context, show_progress, callback_manager, transformations, **kwargs)
```
