### ISSUE TITLE
Model not found on Summarization - Following instructions form documentation

### ISSUE THREAD

**Issue by JuanSandino** [langchain-ai/langchain#2605]
When running the following command there is an error related to the non existence of a module. 
Command: from langchain.chains.summarize import load_summarize_chain
Error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-d212b56df87d> in <module>
----> 1 from langchain.chains.summarize import load_summarize_chain
      2 chain = load_summarize_chain(llm, chain_type="map_reduce")
      3 chain.run(docs)

ModuleNotFoundError: No module named 'langchain.chains.summarize'

I am following the instructions in this notebook: https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html 
I am new to this and reading some help I found this so I have installed langchain as follows: 
pip install langchain == 0.0.135

**Comment by JuanSandino** [comment]
Thanks for the help.

**Comment by vyakhir** [comment]
I am having the same issue as well.

**Comment by vyakhir** [comment]
I think I figured out, you'll have to have Python3 version >= 3.8.1
I had 3.8.0.

I think it's needed to be explicitly mentioned on the documentation website.

**Comment by JuanSandino** [comment]
Thanks, will try it out.
