### ISSUE TITLE
retry_min_seconds and retry_max_seconds is not work in OpenAIEmbeddings of langchain_openai

### ISSUE THREAD

**Issue by dpneko** [langchain-ai/langchain#26084]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The `retry_max_seconds` and `retry_min_seconds` don't work in langchain_openai.OpenAIEmbeddings

``` python
from langchain_openai import OpenAIEmbeddings

embedding_function = OpenAIEmbeddings(
    model="text-embedding-ada-002",
    retry_max_seconds=40,
    retry_min_seconds=60,
    max_retries=10,
)
```

### Description

I checked the source code of langchain_openai.OpenAIEmbeddings but didn't find `retry_max_seconds` and `retry_min_seconds` used anywhere. In the deprecated class [langchain_community.embeddings.openai.OpenAIEmbeddings](https://github.com/langchain-ai/langchain/blob/de97d5064437c98f34dae0b0afa3b61162790726/libs/community/langchain_community/embeddings/openai.py#L44), ther are used in `@retry_decorator`. 

### System Info

langchain                                0.2.0rc2         
langchain-community                      0.2.0rc1        
langchain-core                           0.2.0rc1         
langchain-openai                         0.1.7          
langchain-text-splitters                 0.0.2

**Comment by efriis** [comment]
discussion in #26092

**Comment by efriis** [comment]
closing, built into openai sdk
