### ISSUE TITLE
Confluence Loader does not add any distinction between multiple lines of text that are inside a cell in a table when using 'keep_markdown_format = True'

### ISSUE THREAD

**Issue by MonoMarkor** [langchain-ai/langchain#26089]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

hello, when i load a conflunce page using the confluence loader, i have noticed a wierd formatting that happens inside a cell of a table when there is a text on multiple lines. when using 'keep_markdown_format = True'

That is, when there are multiple p tags inside a cell of a table <p></p>, there is nothing seperating the information that is present inside the tags. No space or new line.

When I tried using keep_markdown_format = False, then the texts inside the table was formatted with a space in between which is good.

I want to keep 'keep_markdown_format = True', is there a way to solve this?

### Description

<p>This is a piece of text</p>
<p>This is the second line inside the cell of a table</p>

When using keep_markdown_format = True i get;
This is a piece of textThis is the second line inside the cell of a table

When using keep_markdown_format = False i get;
This is a piece of text This is the second line inside the cell of a table

As you can see when i set it to True there is nothing seperating multiple lines inside a table

### System Info

langchain==0.2.12
langchain-community==0.2.11
Windows 11
Python 3.11.0

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by MonoMarkor** [comment]
i just found the exact same issue that was closed, but i cant get the solution to work it is here: https://github.com/langchain-ai/langchain/issues/11853
