### ISSUE TITLE
Invalid type NoneType for attribute 'gen_ai.request.model' and 'gen_ai.response.model' when instrumenting telemetry with openlit

### ISSUE THREAD

**Issue by ercucchiaio** [langchain-ai/langchain#26090]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

openlit.init()

### Error Message and Stack Trace (if applicable)

```
Invalid type NoneType for attribute 'gen_ai.request.model' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
Invalid type NoneType for attribute 'gen_ai.response.model' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
Invalid type list in attribute 'gen_ai.prompt' value sequence. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or None
```

### Description

Using openLit 1.22.0 for instrumenting for injecting telemetry in our services, produces error in retrieving gen_ai.request.model, gen_ai.response.model and gen_ai.prompt when using langchain-openai >=1.19.0
langchain-openai 1.17.0 is not affected by this problem

### System Info

```
langchain==0.2.14
langchain-community==0.2.12
langchain-core==0.2.36
langchain-openai==0.1.22
langchain-postgres==0.0.6
langchain-text-splitters==0.2.2
```

**Comment by tastopesato** [comment]
The same here

**Comment by ercucchiaio** [comment]
Solved the issue!
It is necessary to fill the optional parameter 'model' of the AzureChatOpenAI class
