### ISSUE TITLE
What units to use for threshold amount? 

### ISSUE THREAD

**Issue by mvirag2000** [langchain-ai/langchain#26171]
### URL

https://python.langchain.com/v0.2/docs/how_to/semantic-chunker/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

It seems that units for threshold-type = "percentage" are out of a hundred, i.e., 85.0 not 0.85, and this is also unclear for the other threshold types, "gradient," and "interquartile." 

### Idea or request for content:

Also, Semantic Chunker really needs a min and max chunk size. I am getting chunks of a single word, and chunks that exceed the OpenAI limit. Thanks for all the great work on LangChain.

**Comment by tibor-reiss** [comment]
@mvirag2000 What do you think about the linked PR?
Re your idea/request: I only introduced min_chunk_size, because the max size of chunks can be adjusted by tuning breakpoint_threshould_amount to a reasonable value.

**Comment by mvirag2000** [comment]
Min_chunk_size sounds great. Thanks for following up. 

 

Mark Virag

Virag Consulting, LLC

 

954-854-3852

Follow @ViragConsulting <https://twitter.com/ViragConsulting>  on Twitter
