### ISSUE TITLE
Redis: can not check if index exists and can not create index if it does not

### ISSUE THREAD

**Issue by ayalpani** [langchain-ai/langchain#2618]
I really really love langchain. But you are moving too fast, releasing integration after integration without documenting the existing stuff enough or explaining how to implement real life use cases. 

Here is what I am failing to do, probably one of the most basic tasks:

If my Redis server does not have a specific index, create one. Otherwise load from the index. There is a `_check_index_exists` method in the lib. There is also a call to `create_index` but it is burried inside `from_texts`. 

Not sure how to proceed from here

**Comment by tylerhutcherson** [comment]
About to address this in a [PR](https://github.com/hwchase17/langchain/pull/3610) for a few other improvements and fixes. This exposes the create_index functionality.

Easiest way to do this now is with:
```python

try:
    vectorstore = Redis.from_existing_index(...)
except:
    pass

vectorstore = Redis.from_texts(...)
```
