### ISSUE TITLE
Share client between LlamaCpp LLM and LlamaCpp Embedding

### ISSUE THREAD

**Issue by adriacabeza** [langchain-ai/langchain#2630]
Currently when using any chain that has as a llm `LlamaCpp` and a vector store that was created using a `LlamaCppEmbeddings`, it requires to have in memory two models (due to how both objects are created and those two clients are created). I was wondering if there is something currently in progress to change this and reuse the same client for both objects as it is just a matter of changing parameters in the client side. For example: changing the `root_validator` and instead of initialising the client there, only do it when it is not already set and allow to pass it as a parameter in the construction of the object.

**Comment by abhay-psr** [comment]
+1. 
same issue. would be great saving some memory.

**Comment by createchange** [comment]
+1. Interestingly enough, the AI that lives on the LangChain Discord states that this is already possible via the following:

```
```

**Comment by Betai18n** [comment]
> +1. Interestingly enough, the AI that lives on the LangChain Discord states that this is already possible via the following:
> 
> ```python
> llm = LlamaCpp(model_path="./models/llama-7b/ggml-model-q4_0.bin")
> embeddings = LlamaCppEmbeddings(model=llm)
> ```
> 
> Link: https://discord.com/channels/1038097195422978059/1098372830112010240/1098379448102965278
> 
> But this doesn't work. For us plebs with limited RAM, this would be a nice-to-have.

Yes, LlamaCppEmbeddings can create a new embeddings, and this embedding can used by FAISS, but it doesn't be able to do the similarity search.

**Comment by sameera14** [comment]
+1. I was facing the same issue. I resolved it by adding a new parameter `model` to accept the `LlamaCpp` Instance and modifying the rootvalidator of `LllamaCppEmbeddings` class. 
`model : LlamaCpp = Field(None, alias="model")` 
```
from llama_cpp import Llama
            if model_path is None:
                values["client"] = values["model"].client
            else:
                values["client"] = Llama(model_path, embedding=True, **model_params)
```
When I create an instance of this, I pass the LlamaCpp instance by initializing it with embeddings=True
```
llm = LlamaCpp(model_path = './models/llama-7b-model-q4_0.gguf',embeddings=True)
embeddings = LlamaCppEmbeddings(model=llm)
```

**Comment by matthewj-t6** [comment]
This should probably not be closed. In this use case, you must still use a redundant llm just to embed.

**Comment by atuleu** [comment]
@dosubot I think this issue should be re-open as @sameera14 usggests a code modification to allow the sharing between model and embeddings. I will open a PR to add this simple snippets

**Comment by suiluj** [comment]
i would like to do the same thing but did not really understand the changes described in this comment by @sameera14  :
https://github.com/langchain-ai/langchain/issues/2630#issuecomment-1734865461

Is there a best practice code example in the meantime?

**Comment by suiluj** [comment]
oh I noticed that RAM usage does not go up when I load a `LlamaCpp` first and afterwards a  `LlamaCppEmbeddings` of the same model file. This means I just load both as usual without having any issues:

So for example I run this first:

```python
n_gpu_layers = 1  # I am using apple silicon mac gpu
use_mlock = True

callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])

llm = LlamaCpp(
    model_path=os.getenv("MODEL_PATH"),
    n_gpu_layers=n_gpu_layers,
    use_mlock=use_mlock,
    callback_manager=callback_manager,
    verbose=False,
)
```

In the activity monitor the ram usage goes up.

But then later when I load the embedding one (e. g. after waiting some time before running another jupyter notebook cell):

```python
embeddings = LlamaCppEmbeddings(
    model_path=os.getenv("MODEL_PATH"),
    # model=llm,
    n_gpu_layers=n_gpu_layers,
    use_mlock=use_mlock,
    verbose=False,
)
```

There is no additional ram usage and GPU usage only goes up when calling a text generation or embedding method.

I am able to run text generation and embedding methods alternately without additional ram usage.

```python
# use llm to generate text
response = llm("Hello world").strip()
```

```python
# embed text
text = "This is a test document."
query_result = embeddings.embed_query(text)
```

**Comment by wedobetter** [comment]
I have a similar issue trying to use LlamaCppEmbeddings + ChatLlamaCpp, memory usage is doubled, tried the hack above and nothing works
