### ISSUE TITLE
Can't instantiate abstract class BaseLanguageModel

### ISSUE THREAD

**Issue by cvarrichio** [langchain-ai/langchain#2636]
I'm receiving this error when I try to call:

`OutputFixingParser.from_llm(parser=parser, llm=ChatOpenAI())`

Where parser is a class that I have built to extend BaseOutputParser.  I don't think that class can be the problem because of the error I am receiving:
```
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, generate_prompt (type=type_error)
```

**Comment by saifmode** [comment]
Did you instantiate the `parser`, or just pass in a raw class?

If so, did you remember to write overrides for `agenerate_prompt` and `generate_prompt`?

**Comment by sahanesaei** [comment]
I am receiving this error when using langchain as chatbot and memory management:
ValidationError: 1 validation error for ConversationChain
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, predict, predict_messages (type=type_error)

**Comment by adiigeek** [comment]
i'm receiving the same error too.

**Comment by joergister** [comment]
@adiigeek there are two versione of the chatPromptTemplate and one throws this error. Use ` from langchain.prompts import ChatPromptTemplate` if you want to avois this error.

**Comment by adiigeek** [comment]
from langchain.prompts import ChatPromptTemplate I don't have any use of ChatPromptTemplate in my code. Basically this line 
from langchain_community.chat_models import ChatOpenAI is giving me error.

**Comment by adiigeek** [comment]
I solved my error just by importing from langchain.chat_models import ChatOpenAI correctly.

**Comment by Axentar16** [comment]
I'm having that problem when trying to use the SQL agent.

I'm trying to replicate the example on their page. There's a difference to their approach, and it is that I'm using the AzureOpenAI chat and not only the OpenAI, Idk if maybe is because of this?

`from langchain.chat_models.azure_openai import AzureChatOpenAI
from langchain.chains.conversation.memory import ConversationBufferMemory
from langchain.chains import ConversationChain

llm = AzureChatOpenAI(
    deployment_name="gtp35turbo-latest",
    openai_api_key='xxxxxxxxx',
    openai_api_base='xxxxxxx',
    openai_api_version="xxxxx"

)
from langchain_community.utilities import SQLDatabase
from langchain_experimental.sql import SQLDatabaseChain

db = SQLDatabase.from_uri("sqlite:///Chinook.db")
SQLDatabaseToolkit(db = db, llm = llm)
`

Has anyone sorted this out?

**Comment by almariscal** [comment]
Hi! I am having this issue too with SQLDatabaseChain and only works with OpeanAI but not Ollama or GGUF models:

from langchain.agents import create_sql_agent
from langchain.agents.agent_types import AgentType
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.utilities import SQLDatabase
from langchain_community.llms import Ollama

llm = Ollama(
    model="llama2",
    temperature=0
)

db = SQLDatabase.from_uri("postgresql://XXXXXXXXXXXXXX")

agent_executor = create_sql_agent(
    llm=llm,
    toolkit=SQLDatabaseToolkit(db=db, llm=llm),
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)

ValidationError: 2 validation errors for QuerySQLCheckerTool
__root__ -> prompt
  Can't instantiate abstract class BasePromptTemplate with abstract methods format, format_prompt (type=type_error)
__root__ -> llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)

**Comment by gvhlth** [comment]
I am facing same issue when using fastapi 

` def generate_summery_from_text_with_ollama(self,texts):

        try:
            # llm = ChatOllama(
            #     model="llama2",
            #     callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),
            #     )
            # llm = Ollama(model="llama2")
            llm = ChatOllama(model="mistral")
            
            print(llm)
            # Define prompt
            prompt_template = """Write a concise summary of the following:
            "{text}"
            CONCISE SUMMARY:"""
            prompt = PromptTemplate.from_template(prompt_template)

            # Define LLM chain
            llm_chain = LLMChain(llm=llm, prompt=prompt)

            text_splitter = CharacterTextSplitter( 
                                    separator="\n",
                                chunk_size=2000,
                                chunk_overlap=100,
                                length_function = len
                                )
            docs = text_splitter.create_documents([texts])
            # Define StuffDocumentsChain
          
            stuff_chain = StuffDocumentsChain(llm_chain=llm_chain, document_variable_name="text")
            summary = stuff_chain.invoke(docs)
        
            return summary
        except Exception as e:
             print(e)
            #  return e`
<img width="583" alt="Screenshot 2024-01-16 at 00 13 57" src="https://github.com/langchain-ai/langchain/assets/124993936/497e853f-485c-43d3-b576-7795fbc410af">

**Comment by Muthusivam-saip** [comment]
> I'm having that problem when trying to use the SQL agent.
> 
> I'm trying to replicate the example on their page. There's a difference to their approach, and it is that I'm using the AzureOpenAI chat and not only the OpenAI, Idk if maybe is because of this?
> 
> ``from langchain.chat_models.azure_openai import AzureChatOpenAI from langchain.chains.conversation.memory import ConversationBufferMemory from langchain.chains import ConversationChain
> 
> llm = AzureChatOpenAI( deployment_name="gtp35turbo-latest", openai_api_key='xxxxxxxxx', openai_api_base='xxxxxxx', openai_api_version="xxxxx"
> 
> ) from langchain_community.utilities import SQLDatabase from langchain_experimental.sql import SQLDatabaseChain
> 
> db = SQLDatabase.from_uri("sqlite:///Chinook.db") SQLDatabaseToolkit(db = db, llm = llm) ``
> 
> Has anyone sorted this out?

Did you get the solution??? I m still facing the issue

**Comment by vishnusureshperumbavoor** [comment]
> use this instead: from langchain.chat_models import ChatOpenAI you probably get another error after this! you can solve it with installing these specific version of these two libraries: langchain == 0.0.343 Openai == 1.3.6

heii I'm building project based on langchain and ollama mistral. what should I do? I'm getting the same error

**Comment by raminmardani** [comment]
> > use this instead: from langchain.chat_models import ChatOpenAI you probably get another error after this! you can solve it with installing these specific version of these two libraries: langchain == 0.0.343 Openai == 1.3.6
> 
> heii I'm building project based on langchain and ollama mistral. what should I do? I'm getting the same error

just install langchain == 0.0.343

**Comment by AmarirNaima** [comment]
I am receiving this error when using Chainlit and langchain as chatbot and memory management:
1 validation error for LLMChain
llm
Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, predict, predict_messages (type=type_error)

**Comment by GHIhack** [comment]
the correction in my case facing the saame error message is the following : 
install langchain == 0.0.343
