### ISSUE TITLE
Unable to reuse Chat Models for Anthropic Claude

### ISSUE THREAD

**Issue by samching** [langchain-ai/langchain#2638]
## Problem

Langchain currently doesn't support chat format for Anthropic (e.g. being able to use `HumanMessage` and `AIMessage` classes)

Currently, when testing the same prompt across both Anthropic and OpenAI chat models, it requires rewriting the same prompt, although they fundamentally use the same `Human:... AI:....` structure. 

This means duplicating `2 * n chains` prompts (and more if you write separate prompts for `turbo-3.5` and `4` (likewise for `instant` and `v1.2` for Claude), making it very unwieldy to test and scale the number of chains.

## Potential Solution

1. Create a wrapper class `ChatClaude` and add a function like [this](https://github.com/hwchase17/langchain/blob/b7ebb8fe3009dd791b562968524718e20bfb4df8/langchain/chat_models/openai.py#L78) to translate both `AIMessage` and `HumanMessage` to `anthropic.AI_PROMPT` and `anthropic.HUMAN_PROMPT` respectively.

But, definitely also open to other solutions which could work here.

**Comment by supreetkt** [comment]
Have you tried [ChatAnthropic](https://python.langchain.com/docs/modules/model_io/models/chat/integrations/anthropic)?

**Comment by evolate-tim** [comment]
Working with ConversationBufferWindowMemory and anthropic LLM's will also throw a lot of warnings since the Base template "_DEFAULT_SUMMARIZER_TEMPLATE" has "AI:" examples in it.
The summarization will however work in the end.
