### ISSUE TITLE
New strawberry models don't support `stop` parameter `o1-mini` and `o1-preview`

### ISSUE THREAD

**Issue by hagope** [langchain-ai/langchain#26433]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
def run_chain(prompt):
    from langchain_openai import ChatOpenAI
    llm = ChatOpenAI(temperature=1, model_name=AI_MODEL) # o1 models only support temp 1

    # from langchain import SQLDatabaseChain
    from langchain_experimental.sql import SQLDatabaseChain
    db = connect_to_db(
        "hive_metastore", DB_SCHEMA, DB_TABLES
    )

    db_chain = SQLDatabaseChain.from_llm(
        llm,
        db,
        verbose=True,
        return_intermediate_steps=True,
        top_k=20,
        # return_direct=True,
        # use_query_checker=True,
    )
    db_chain.invoke(prompt)
```

### Error Message and Stack Trace (if applicable)

```{'error': {'message': "Unsupported parameter: 'stop' is not supported with this model.", 'type': 'invalid_request_error', 'param': 'stop', 'code': 'unsupported_parameter'}}```

### Description

When using langchain SQLchain i notice that the `o1` class models have a new API and do not accept `stop` parameter. Also, temperature should always be 1.

### System Info

MacOS, Python 3.11
langchain==0.2.16
langchain-community==0.2.16
langchain-core==0.2.39
langchain-experimental==0.0.64
langchain-openai==0.1.24
langchain-text-splitters==0.2.2

**Comment by hrshdhgd** [comment]
Experiencing the same error. Could this be because the new `o1-X` does not support function calling? Just curios.

**Comment by hiteshagarwal-blitz** [comment]
did anyone find how to solve this ? was using gpt-4.1 so far but getting the issue as mentioned above with gpt-5.

**Comment by salvaKaraka** [comment]
> did anyone find how to solve this ? was using gpt-4.1 so far but getting the issue as mentioned above with gpt-5.

Same here. did you solve it?
