### ISSUE TITLE
RCI (Recursively Criticizes and Improves) Agent

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#2646]
As per suggestion [here](https://github.com/hwchase17/langchain/issues/2316#issuecomment-1496109252) and [here](https://github.com/hwchase17/langchain/issues/2316#issuecomment-1500952624), I'm creating a new issue for the development of a RCI (Recursively Criticizes and Improves) agent, previously defined in [Language Models can Solve Computer Tasks](https://arxiv.org/abs/2303.17491).

[Here](https://github.com/posgnu/rci-agent)'s a solid implementation by @posgnu.

**Comment by slavakurilyak** [comment]
See related agent here: https://github.com/hwchase17/langchain/issues/2316

**Comment by feffy380** [comment]
It looks like this is already doable as a ConstitutionalChain with:
Critique request: "Review your previous answer and find problems with your answer"
Revision request: "Based on the problems you found, improve your answer."

**Comment by austin362667** [comment]
> It looks like this is already doable as a ConstitutionalChain with: Critique request: "Review your previous answer and find problems with your answer" Revision request: "Based on the problems you found, improve your answer."

What about using tools? in ConstitutionalChain?
