### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/integrations/tools/google_scholar/>

### ISSUE THREAD

**Issue by kimou6055** [langchain-ai/langchain#26482]
### URL

https://python.langchain.com/v0.2/docs/integrations/tools/google_scholar/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

ImportError: cannot import name 'GoogleScholarAPIWrap' from 'langchain_community.utilities.google_scholar' (/usr/local/lib/python3.10/dist-packages/langchain_community/utilities/google_scholar.py)

### Idea or request for content:

how to fix this issue

**Comment by hwchase17** [comment]
hm what version are you on? i tried this on the most recent version and it seems to work fine for m
