### ISSUE TITLE
After upgrade  to 0.3.0 and pydantic 2 I get - Arguments: (NameError("name 'ClassVar' is not defined"),)

### ISSUE THREAD

**Issue by multib0t** [langchain-ai/langchain#26506]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

    def get_graph(self):
        workflow = StateGraph(self.get_state_class()) <---- issue here
        
casued by:

ann = {dict: 1} {'model_config': 'ClassVar[ConfigDict]'}
base = {ModelMetaclass} <class 'openai.BaseModel'>

class BaseModel(_models.BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(extra="ignore", arbitrary_types_allowed=True)
    else:

        class Config(pydantic.BaseConfig):  # type: ignore
            extra: Any = pydantic.Extra.ignore  # type: ignore
            arbitrary_types_allowed: bool = True
---

### Error Message and Stack Trace (if applicable)

.....
workflow = StateGraph(MyStateClass)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "my_src_path/venv/lib/python3.12/site-packages/langgraph/graph/state.py", line 153, in __init__
    self._add_schema(state_schema)
  File "my_src_path/venv/lib/python3.12/site-packages/langgraph/graph/state.py", line 168, in _add_schema
    channels, managed = _get_channels(schema)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "my_src_path/venv/lib/python3.12/site-packages/langgraph/graph/state.py", line 694, in _get_channels
    for name, typ in get_type_hints(schema, include_extras=True).items()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 2244, in get_type_hints
    value = _eval_type(value, base_globals, base_locals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 414, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/typing.py", line 924, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'ClassVar' is not defined
.....
Arguments: (NameError("name 'ClassVar' is not defined"),)
------------

### Description

After upgrading to the following packages I when I set state on langgraph object ie:

I get the following error
```
    def get_graph(self):
        workflow = StateGraph(self.get_state_class()) <---- issue here
```

**my current langchain packages are:**        

langchain==0.3.0
langchain_core==0.3.0
langgraph==0.2.21
langchain-openai==0.2.0
langchain-anthropic==0.2.0
langchain-community==0.3.0
langchain-experimental==0.3.0
langgraph-checkpoint-postgres==1.0.6
langchain-postgres==0.0.12
openai==1.45.0

seems like the issue is with openai lib

I would appreciate some help as I would like to upgrade to most recent versions successfully

### System Info

langchain==0.3.0
langchain-anthropic==0.2.0
langchain-community==0.3.0
langchain-core==0.3.0
langchain-experimental==0.3.0
langchain-openai==0.2.0
langchain-postgres==0.0.12
langchain-text-splitters==0.3.0

+

langchain==0.3.0
langchain_core==0.3.0
langgraph==0.2.21
langchain-openai==0.2.0
langchain-anthropic==0.2.0
langchain-community==0.3.0
langchain-experimental==0.3.0
langgraph-checkpoint-postgres==1.0.6
langchain-postgres==0.0.12
openai==1.45.0

**Comment by gbaian10** [comment]
What is the content of `self.get_state_class()`?

**Comment by multib0t** [comment]
> 
    def get_state_class(self):
        return MyAgentState

**Comment by gbaian10** [comment]
Could you provide a `minimal reproducible example`?

**Comment by multib0t** [comment]
[example-classvar.zip](https://github.com/user-attachments/files/17013752/example-classvar.zip)

**Comment by gbaian10** [comment]
@multib0t  You incorrectly imported `BaseModel` from `openai`; it should be imported from `pydantic`.

```py
import operator
from typing import Annotated

from langchain_core.messages import AnyMessage
from langgraph.graph import StateGraph
from pydantic import BaseModel  # Not `from openai import BaseModel`


class MyState(BaseModel):
    messages: Annotated[list[AnyMessage], operator.add]


print(StateGraph(MyState))
```

**Comment by eyurtsev** [comment]
Thank for your help @gbaian10 . I'll close the issue for now as resolved.

**Comment by multib0t** [comment]
Thanks for spotting that for me :) MUCH APPRECIATED!
