### ISSUE TITLE
langchain_milvus versioning failing

### ISSUE THREAD

**Issue by kanzyai-emirarditi** [langchain-ai/langchain#26564]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

poetry add langchain_milvus 
pip3 install langchain_milvus

### Description

langchain_milvus package on PyPi is currently version 0.1.4, the 2 latest releases(0.1.5 and 0.1.6) seems to be failing during release. It is a breaking change for migrating to langchain 0.3.0

### System Info

Package Information
-------------------
> langchain_core: 0.3.0
> langchain: 0.3.0
> langsmith: 0.1.121
> langchain_anthropic: 0.2.0
> langchain_openai: 0.2.0
> langchain_text_splitters: 0.3.0
> langchain_voyageai: 0.1.2

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> anthropic: 0.34.2
> async-timeout: Installed. No version info available.
> defusedxml: 0.7.1
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.45.1
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.1
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2
> voyageai: 0.2.3

**Comment by ccurme** [comment]
Hello,

`langchain-milvus` 0.1.5 was released today and should be compatible with `langchain-core >= 0.3`. Please shout if you run into any issues!
