### ISSUE TITLE
DOC: A few broken "latest" urls point to langchain 0.2x

### ISSUE THREAD

**Issue by cab938** [langchain-ai/langchain#26577]
### URL

https://api.python.langchain.com/en/latest/langchain_api_reference.html

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I expected this URL to take me to a langchain 0.3x API page based on the word "latest" in the URL:

![image](https://github.com/user-attachments/assets/e62ebee7-5ef6-4156-b121-88f10ca3d95a)

**Comment by eyurtsev** [comment]
API reference moved to here: https://python.langchain.com/api_reference/reference.html


cc @efriis should we do a re-direct?
