### ISSUE TITLE
Ability to pass instantiated Chroma into VectorStoreIndexCreator

### ISSUE THREAD

**Issue by avinoth** [langchain-ai/langchain#2658]
Is there a way to pass in an already instantiated VectorStore into VectorStoreIndexCreator? As far as I checked, the creator accepts the class and initializes the class internally via `from_documents`.  But this doesn't allow to use persisted Chroma from the loaded index.

I might be misunderstanding the intention, but VectorStoreIndexCreator is not for pre-existing indices, correct? If that's the case the only option then to use `load_qa_with_sources_chain` directly instead or is there other public classes available that provides the convenience of the IndexCreator? (similar to VectorStoreIndexWrapper)

Thanks in advance!

**Comment by christianhellsten** [comment]
You could use something like this to load the index from disk:

```python
from langchain.indexes.vectorstore import VectorStoreIndexWrapper

def load_index():
    vectorstore = Chroma(persist_directory='db', embedding_function=OpenAIEmbeddings())
    return VectorStoreIndexWrapper(vectorstore=vectorstore)
```

See:
https://github.com/hwchase17/langchain/blob/master/langchain/indexes/vectorstore.py#L74
