### ISSUE TITLE
Issue with callback manager for verbose output

### ISSUE THREAD

**Issue by eyurtsev** [langchain-ai/langchain#26588]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Following this tutorial: https://python.langchain.com/v0.1/docs/modules/agents/quick_start/#create-the-agent

![image](https://github.com/user-attachments/assets/8e789de5-8774-44cf-a6c3-1b2b6bcdf356)

**Comment by keenborder786** [comment]
@eyurtsev I can take this.

**Comment by eyurtsev** [comment]
identical to: https://github.com/langchain-ai/langchain/issues/26773
