### ISSUE TITLE
DOC: typo in /v0.2/docs/integrations/vectorstores/clickhouse/

### ISSUE THREAD

**Issue by sanjay920** [langchain-ai/langchain#26597]
### URL

https://python.langchain.com/v0.2/docs/integrations/vectorstores/clickhouse/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The cell towards the bottom references `AstraDBVectorStore` when it should be `Clickhouse`:
```
For detailed documentation of all `AstraDBVectorStore` features and configurations head to the API reference:https://python.langchain.com/api_reference/community/vectorstores/langchain_community.vectorstores.clickhouse.Clickhouse.html
```

### Idea or request for content:

Change `AstraDBVectorStore` to `Clickhouse`

**Comment by sTomerG** [comment]
shouldn't this Issue be closed due to #26598?
