### ISSUE TITLE
FAISS.add_texts is calling the embedding function without batching

### ISSUE THREAD

**Issue by raphaelmerx** [langchain-ai/langchain#2660]
Contrary to `from_texts` which batch computes embeddings through `embed_documents`, the `add_texts` method calls `self.embedding_function` for each document that is beind added. If using `OpenAIEmbeddings`, this means one API call per added document, which can take a long time when there are many documents:

https://github.com/hwchase17/langchain/blob/e63f9a846be7a85de7d3e3a1b277a4521b42808d/langchain/vectorstores/faiss.py#L109

To do: Make use of `embed_documents` in `FAISS.add_texts`, so that documents are embedded in chunks. Maybe this will require changing the `embedding_function` init argument to use an `Embeddings` object instead of a callable?

**Comment by raphaelmerx** [comment]
Related for pinecone: https://github.com/hwchase17/langchain/pull/2657

**Comment by EmbraceTomorrow** [comment]
I think you can use `embed_documents` first to get the embeddings, then use `add_embeddings` method.
