### ISSUE TITLE
AttributeError("'FieldInfo' object has no attribute 'raw_results'")

### ISSUE THREAD

**Issue by chinmay0722** [langchain-ai/langchain#26630]
### Issue with current documentation:

from langchain_community.tools.tavily_search import TavilySearchResults
tool = TavilySearchResults(max_results=2)
tools = [tool]
response = tool.invoke("whats a node in langgraph?")
response

**Comment by MarcusT96** [comment]
I get this error as well with the same code

**Comment by tibor-reiss** [comment]
Can confirm, works without error with latest both for v0.2 and v0.3.
