### ISSUE TITLE
config is passed in as a positional argument in RunnableSequence.invoke, should be passed in as a keyword argument.

### ISSUE THREAD

**Issue by gabayben** [langchain-ai/langchain#26669]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

class SomeRunnable(Runnable[str, list[str]]):
    def invoke(input: str, **kwargs) -> list[str]:
        return [input] * 5

class SomeOtherRunnable(Runnable[list[str], str]):
    def invoke(input: list[str], **kwargs) -> str:
        return input [-1]

some_runnable = SomeRunnable()
some_other_runnable = SomeOtherRunnable()
chained = some_runnable | some_other_runnable
chained.invoke('This will raise a positional argument exception.')

### Error Message and Stack Trace (if applicable)

File ~\langchain_core\runnables\base.py:3011, in RunnableSequence.invoke(self, input, config, **kwargs)
   3009 context.run(_set_config_context, config)
   3010 if i == 0:
-> 3011     input = context.run(step.invoke, input, config, **kwargs)
   3012 else:
   3013     input = context.run(step.invoke, input, config)

### Description

config is passed in as a positional argument in RunnableSequence.invoke, should be passed in as a keyword argument.
This means that you have to include the config in your invoke implementation, even though you don't need it, and even though it is an optional argument in Runnable.invoke.

I suggest also checking the other methods in RunnableSequence as well (ainvoke, batch, abatch, stream, astream, transform, atransform). As it is probably an issue there too.

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.1
> langsmith: 0.1.122
> langgraph: 0.2.22

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> httpx: 0.27.2
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.10
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> PyYAML: 6.0.2
> requests: 2.32.3
> tenacity: 8.5.0
> typing-extensions: 4.12.2

**Comment by eyurtsev** [comment]
please include config in the signature in the way it's included in the existing abstractions. 

It's used as either positional or named argument currently, and we do not expect to change this behavior.
