### ISSUE TITLE
pip Installation of only LangChain failing due to Hash mismatch (other packages are installing no issues) 

### ISSUE THREAD

**Issue by prasannguruprasad** [langchain-ai/langchain#26664]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

!pip install langchain 
!pip install langchain==0.2.15
!pip install -e . (within the libs\langchain folder of the cloned github repository) 

### Error Message and Stack Trace (if applicable)

# METHOD 1 - trying to install from cloned langchain GitHub repo: 

C:\Users\pguruprasad\Desktop\langchain\libs\langchain\.venv>pip cache purge 
Files removed: 262

(.venv) C:\Users\pguruprasad\Desktop\langchain\libs\langchain>pip install -e .
Obtaining file:///C:/Users/pguruprasad/Desktop/langchain/libs/langchain
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting PyYAML>=5.3 (from langchain==0.3.0)
  Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting SQLAlchemy<3,>=1.4 (from langchain==0.3.0)
  Downloading SQLAlchemy-2.0.35-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain==0.3.0)
  Downloading aiohttp-3.10.5-cp311-cp311-win_amd64.whl.metadata (7.8 kB)
Collecting langchain-core<0.4.0,>=0.3.0 (from langchain==0.3.0)
  Downloading langchain_core-0.3.1-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain==0.3.0)
  Downloading langchain_text_splitters-0.3.0-py3-none-any.whl.metadata (2.3 kB)
Collecting langsmith<0.2.0,>=0.1.17 (from langchain==0.3.0)
  Downloading langsmith-0.1.123-py3-none-any.whl.metadata (13 kB)
Collecting numpy<2,>=1 (from langchain==0.3.0)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain==0.3.0)
  Downloading pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting requests<3,>=2 (from langchain==0.3.0)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity!=8.4.0,<9.0.0,>=8.1.0 (from langchain==0.3.0)
  Downloading tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading aiohappyeyeballs-2.4.0-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading frozenlist-1.4.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading multidict-6.1.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0.0,>=3.8.3->langchain==0.3.0)
  Downloading yarl-1.11.1-cp311-cp311-win_amd64.whl.metadata (49 kB)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.4.0,>=0.3.0->langchain==0.3.0)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting packaging<25,>=23.2 (from langchain-core<0.4.0,>=0.3.0->langchain==0.3.0)
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting typing-extensions>=4.7 (from langchain-core<0.4.0,>=0.3.0->langchain==0.3.0)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting httpx<1,>=0.23.0 (from langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading orjson-3.10.7-cp311-none-win_amd64.whl.metadata (51 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain==0.3.0)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.4 (from pydantic<3.0.0,>=2.7.4->langchain==0.3.0)
  Downloading pydantic_core-2.23.4-cp311-none-win_amd64.whl.metadata (6.7 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2->langchain==0.3.0)
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2->langchain==0.3.0)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2->langchain==0.3.0)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2->langchain==0.3.0)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy<3,>=1.4->langchain==0.3.0)
  Downloading greenlet-3.1.0-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting anyio (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading anyio-4.5.0-py3-none-any.whl.metadata (4.7 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
Collecting sniffio (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.3.0)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.0->langchain==0.3.0)
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Downloading aiohttp-3.10.5-cp311-cp311-win_amd64.whl (379 kB)
Downloading langchain_core-0.3.1-py3-none-any.whl (405 kB)
Downloading langchain_text_splitters-0.3.0-py3-none-any.whl (25 kB)
Downloading langsmith-0.1.123-py3-none-any.whl (290 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 1.9 MB/s eta 0:00:00
Downloading pydantic-2.9.2-py3-none-any.whl (434 kB)
Downloading pydantic_core-2.23.4-cp311-none-win_amd64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 3.8 MB/s eta 0:00:00
Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading SQLAlchemy-2.0.35-cp311-cp311-win_amd64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.3 MB/s eta 0:00:00
Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Downloading aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)
Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Downloading frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
Downloading greenlet-3.1.0-cp311-cp311-win_amd64.whl (293 kB)
Downloading httpx-0.27.2-py3-none-any.whl (76 kB)
Downloading httpcore-1.0.5-py3-none-any.whl (77 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading multidict-6.1.0-cp311-cp311-win_amd64.whl (28 kB)
Downloading orjson-3.10.7-cp311-none-win_amd64.whl (137 kB)
Downloading packaging-24.1-py3-none-any.whl (53 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Downloading yarl-1.11.1-cp311-cp311-win_amd64.whl (110 kB)
Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Downloading anyio-4.5.0-py3-none-any.whl (89 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 e10ce637b18caea04431ce14fabcf5c64a1c61ec9c56b071a4b7ca131ca52d44
             Got        e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
             
-------------------------------------------------------------------------------------------------------------------------------------------

#METHOD 2: simple pip install 

(.venv) C:\Users\pguruprasad\Desktop\langchain\libs\langchain>pip install langchain
Collecting langchain
  Downloading langchain-0.3.0-py3-none-any.whl.metadata (7.1 kB)
Collecting PyYAML>=5.3 (from langchain)
  Using cached PyYAML-6.0.2-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting SQLAlchemy<3,>=1.4 (from langchain)
  Using cached SQLAlchemy-2.0.35-cp311-cp311-win_amd64.whl.metadata (9.9 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain)
  Using cached aiohttp-3.10.5-cp311-cp311-win_amd64.whl.metadata (7.8 kB)
Collecting langchain-core<0.4.0,>=0.3.0 (from langchain)
  Using cached langchain_core-0.3.1-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain-text-splitters<0.4.0,>=0.3.0 (from langchain)
  Using cached langchain_text_splitters-0.3.0-py3-none-any.whl.metadata (2.3 kB)
Collecting langsmith<0.2.0,>=0.1.17 (from langchain)
  Using cached langsmith-0.1.123-py3-none-any.whl.metadata (13 kB)
Collecting numpy<2,>=1 (from langchain)
  Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting requests<3,>=2 (from langchain)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity!=8.4.0,<9.0.0,>=8.1.0 (from langchain)
  Using cached tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached multidict-6.1.0-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0.0,>=3.8.3->langchain)
  Using cached yarl-1.11.1-cp311-cp311-win_amd64.whl.metadata (49 kB)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.4.0,>=0.3.0->langchain)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting packaging<25,>=23.2 (from langchain-core<0.4.0,>=0.3.0->langchain)
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Collecting typing-extensions>=4.7 (from langchain-core<0.4.0,>=0.3.0->langchain)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting httpx<1,>=0.23.0 (from langsmith<0.2.0,>=0.1.17->langchain)
  Using cached httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.2.0,>=0.1.17->langchain)
  Using cached orjson-3.10.7-cp311-none-win_amd64.whl.metadata (51 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.23.4 (from pydantic<3.0.0,>=2.7.4->langchain)
  Using cached pydantic_core-2.23.4-cp311-none-win_amd64.whl.metadata (6.7 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2->langchain)
  Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2->langchain)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2->langchain)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2->langchain)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy<3,>=1.4->langchain)
  Using cached greenlet-3.1.0-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting anyio (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain)
  Using cached anyio-4.5.0-py3-none-any.whl.metadata (4.7 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain)
  Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
Collecting sniffio (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.0->langchain)
  Using cached jsonpointer-3.0.0-py2.py3-none-any.whl.metadata (2.3 kB)
Downloading langchain-0.3.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 46.3 MB/s eta 0:00:00
Using cached aiohttp-3.10.5-cp311-cp311-win_amd64.whl (379 kB)
Using cached langchain_core-0.3.1-py3-none-any.whl (405 kB)
Using cached langchain_text_splitters-0.3.0-py3-none-any.whl (25 kB)
Using cached langsmith-0.1.123-py3-none-any.whl (290 kB)
Using cached numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
Using cached pydantic-2.9.2-py3-none-any.whl (434 kB)
Using cached pydantic_core-2.23.4-cp311-none-win_amd64.whl (1.9 MB)
Downloading PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached SQLAlchemy-2.0.35-cp311-cp311-win_amd64.whl (2.1 MB)
Using cached tenacity-8.5.0-py3-none-any.whl (28 kB)
Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl (12 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
Using cached greenlet-3.1.0-cp311-cp311-win_amd64.whl (293 kB)
Using cached httpx-0.27.2-py3-none-any.whl (76 kB)
Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached multidict-6.1.0-cp311-cp311-win_amd64.whl (28 kB)
Using cached orjson-3.10.7-cp311-none-win_amd64.whl (137 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
Using cached yarl-1.11.1-cp311-cp311-win_amd64.whl (110 kB)
Using cached jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Using cached anyio-4.5.0-py3-none-any.whl (89 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 e10ce637b18caea04431ce14fabcf5c64a1c61ec9c56b071a4b7ca131ca52d44
             Got        e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

### Description

I am trying to install LangChain to a virtual environment behind a corporate network - this has not been an issue in the past but over the last couple of days we have been getting hash mismatch errors while trying to run this. I purged my pip cache, reinstalled and updated pip and even tried downloading it from the GitHub source code. Please let me know how this issue may be resolved and if this is an issue at the source end or user end. 

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.19045
> Python Version:  3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.1
> langchain: 0.3.0
> langchain_community: 0.2.7
> langsmith: 0.1.123
> langchain_openai: 0.1.20
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.0
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.35.14
> orjson: 3.10.6
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.1
> requests: 2.32.3
> SQLAlchemy: 2.0.31
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

(Please note this is the result of calling py -m langchain_core.sys_info outside my virtual environment using a previous local installation of langchain - this is working fine but it is not working when I am trying to add it to a virtual environment)

**Comment by saurabhkansal635** [comment]
I am facing the same issue from yesterday, Thanks @prasannguruprasad for explaining this in detail. Tried most of the approches.

**Comment by sayantan16** [comment]
Hi, I am facing the same issue and at the moment waiting for any hint to resolve. Thanks for sharing this in detail.

**Comment by efriis** [comment]
wasn't able to reproduce in linux python 3.11.2 in docker :(. Are you all on windows machines? Might be windows-specific with some underlying package.

```
cd libs/langchain
pip install langchain
pip install langchain==0.2.15
pip install -e .
```

Could you try `pip install h11` from your log and see if you get the same output? Or clearing your pip cache because a lot of them are coming from cache?

**Comment by prasannguruprasad** [comment]
Issue was resolved but exact reason for the fix is unknown.
