### ISSUE TITLE
Cant import create_retrieval_chain on new version of langchain==0.3.0

### ISSUE THREAD

**Issue by Pochomo** [langchain-ai/langchain#26692]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```from fastapi import APIRouter, HTTPException, UploadFile, File
from app.services.document_loader import PDFLoader
from app.services.vector_store import VectorStore
from langchain_community.chat_models import ChatOpenAI
from langchain.chains import create_retrieval_chain 
from langchain.memory import ConversationBufferMemory
from pydantic import BaseModel
from typing import List

router = APIRouter()

pdf_loader = PDFLoader()
vector_store = VectorStore()

class ChatRequest(BaseModel):
    message: str


@router.post("/upload-pdf")
async def upload_pdf(files: List[UploadFile] = File(...)):



@router.post("/chat")
async def chat(request: ChatRequest):

@router.get("/check-vector-store")
async def check_vector_store(is_law_related: bool = False):

```

### Error Message and Stack Trace (if applicable)

"create_retrieval_chain" is unknown import symbol

### Description

I have an error here "from langchain.chains import create_retrieval_chain"
, the contents of the error are as follows ""create_retrieval_chain" is unknown import symbol". my version of langchains are 

[langchain                                0.3.0
langchain-anthropic                      0.2.1
langchain-chroma                         0.1.4
langchain-community                      0.3.0
langchain-core                           0.3.2
langchain-openai                         0.2.0
langchain-text-splitters                 0.3.0]

can window cause an error?? I really need to fix this, please help. 

### System Info

python 3.12.6
langchain                                0.3.0
langchain-anthropic                      0.2.1
langchain-chroma                         0.1.4
langchain-community                      0.3.0
langchain-core                           0.3.2
langchain-openai                         0.2.0
langchain-text-splitters                 0.3.0

**Comment by Pochomo** [comment]
when i used "from langchain.chains import ConversationalRetrievalChain" it was working, but not now lanchain let me change to create_retrieval_chain

**Comment by binhnguyen-eh** [comment]
@Pochomo can you use this instead?
`from langchain.chains.retrieval import create_retrieval_chain 
`

**Comment by binhnd102** [comment]
@Pochomo Could you use this instead?
`from langchain.chains.retrieval import create_retrieval_chain `

**Comment by Pochomo** [comment]
> @Pochomo Could you use this instead? `from langchain.chains.retrieval import create_retrieval_chain `

I I solved it using venv thx:)

**Comment by shankhanraman** [comment]
I still got the missing import 
from langchain.chains import create_retrieval_chain

**Comment by conscious-code-dev** [comment]
I ran into the same confusion while researching how to use memory in v0.3

I made a walkthrough video on v0.3 upgrade errors, including:
- Modular import changes
- LCEL chaining with invoke()
- RAG pipeline rewrites

🎥 LangChain v0.3 Upgrade Fixes (YouTube): https://youtu.be/3L6W-C7Km7Y
 
💻 GitHub: https://github.com/conscious-code-dev/LangChain-v0.3-Crash-Course-Build-Real-Agents-Deploy-Production-Ready-Apps

Still learning this myself, but hope this clears it up for someone else running into the same thing.

**Comment by Saurav2OO2** [comment]
Facing issues while import create_retrieval_chain  from langchain.chains

ModuleNotFoundError: No module named 'langchain.chains'

**Comment by palanivigneshwar** [comment]
Try using `from langchain_classic.chains.retrieval import create_retrieval_chain`
