### ISSUE TITLE
Exactly one of file, filename and url must be specified.

### ISSUE THREAD

**Issue by ukihsoroy** [langchain-ai/langchain#26697]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

# https://python.langchain.com/docs/integrations/document_loaders/unstructured_file/#loading-web-pages
from langchain_unstructured import UnstructuredLoader

loader = UnstructuredLoader(web_url="https://www.example.com")
docs = loader.load()

for doc in docs:
    print(f"{doc}\n")

### Description

Following the sample code in the document will directly report an error. version=0.1.4

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
> Python Version:  3.9.6 (default, Feb  3 2024, 15:58:27) 
[Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.2
> langsmith: 0.1.125
> langchain_unstructured: 0.1.4

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> httpx: 0.27.2
> jsonpatch: 1.33
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> PyYAML: 6.0.2
> requests: 2.32.3
> tenacity: 8.5.0
> typing-extensions: 4.12.2
> unstructured-client: 0.25.9
> unstructured[all-docs]: Installed. No version info available.

**Comment by hardchor** [comment]
Got caught by this as well! It was implemented [here](https://github.com/langchain-ai/langchain/pull/26670) and the docs were built, but the `langchain-unstructured` package hasn't been released yet.

@ccurme @Coniferish could you trigger a release, please?

**Comment by adderbyte** [comment]
Has this error been resolved ?

**Comment by Coniferish** [comment]
Sorry for the delay! Will get right on this

**Comment by hardchor** [comment]
@adderbyte Looks like it, as of today: https://pypi.org/project/langchain-unstructured/#history

**Comment by hardchor** [comment]
@Coniferish I upgraded and can confirm that this solved it for me. Thanks for your awesome work!
