### ISSUE TITLE
on_chain_start callbacks crash with `serialized=None` in v0.3

### ISSUE THREAD

**Issue by whimo** [langchain-ai/langchain#26773]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Any callback manager includes default callbacks such as `StdOutCallbackHandler`, so we can simply instantiate an agent:
```python
from langchain import hub
from langchain.agents import AgentExecutor, create_react_agent
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_openai import OpenAI

llm = OpenAI()

prompt = hub.pull("hwchase17/react")
search = DuckDuckGoSearchRun()

tools = [search]
agent = create_react_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)
agent_executor.invoke({"input": "what is LangChain?"})
```

### Error Message and Stack Trace (if applicable)

Error in StdOutCallbackHandler.on_chain_start callback: AttributeError("'NoneType' object has no attribute 'get'")

### Description

Starting with Langchain v0.3, on_chain_start callbacks started receiving `serialized` argument as None. This causes callback handlers, including the default ones, to crash. 

I doubt that this is intended, but if so, the built-in callbacks should be updated, as well as the docs.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:19:05 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8112
> Python Version:  3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:38) [Clang 13.0.0 (clang-1300.0.29.30)]

Package Information
-------------------
> langchain_core: 0.3.5
> langchain: 0.3.0
> langchain_community: 0.3.0
> langsmith: 0.1.125
> langchain_callbacks_bug: Installed. No version info available.
> langchain_openai: 0.2.0
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.47.0
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by eyurtsev** [comment]
Fix merged will be resolved in the next langchain-core release

**Comment by whimo** [comment]
The issue is fixed in the new release, thank you!

I'll add to clarify, that the removal of `serialized` argument is indeed intended. Here's the relevant PR: https://github.com/langchain-ai/langchain/pull/26270
So the fix here included only the switch to the `name` argument in `StdOutCallbackHandler`.

**Comment by danielkerwin** [comment]
@whimo @eyurtsev this is still an issue - `serialized` is coming through as `None` in `on_chain_start`, and `on_retriever_start`
