### ISSUE TITLE
Support concurrent usage of OpenAI API and Azure OpenAI

### ISSUE THREAD

**Issue by kjwong** [langchain-ai/langchain#2683]
I would like to make requests to both Azure OpenAI and the OpenAI API in my app using the `AzureChatOpenAI` and `ChatOpenAI` classes respectively. 

The issue I'm running into is it seems both classes depend on the same environment variables/global OpenAI variables (`openai.api_key`, `openai.api_type`, etc). For example, if I create an `AzureChatOpenAI` instance, the variables will be set to Azure config, and this will cause any subsequent OpenAI calls to fail. 

I also have two instances of Azure OpenAI that I want to hit (e.g. I have text-davinci-003 running in EU and gpt-3.5-turbo running in US as gpt-3.5-turbo isn't supported in EU yet), so it would be nice if I could have separate instances of `AzureChatOpenAI` with different configs. 

A workaround is to set these environment variables manually before every call, which `AzureChatOpenAI` kind of does, but this seems susceptible to race conditions if concurrent requests are made to my app since these variables aren't directly passed into the request and there's no locking mechanism. 

Would it be possible to have multiple instances of these classes and not have these instances obscurely share state? Or is this just a limitation of the way OpenAI's python package is setup? 

Thank you!

**Comment by TSPereira** [comment]
Another issue is that after instantiating an `AzureOpenAI` llm and those variables get set in the `openai` module, if we want to then instantiate a `OpenAI` llm it won't set the `api_type`, `api_base` and `api_version` back to the `openai` defaults.
This happens cause the `BaseOpenAI` object only accepts, validates and sets the `api_key`

**Comment by TSPereira** [comment]
Also the `AzureOpenAI` model don't support these keys as well. Only the chat version (`AzureChatOpenAI`) does

**Comment by parulekarmihir** [comment]
Any update on this? Is there a way to set multiple environments for different models, right now it is overwriting as mentioned in the above comments.

**Comment by TSPereira** [comment]
Not sure if everyone noticed it but this should now be solved since https://github.com/hwchase17/langchain/pull/5792 🎉
