### ISSUE TITLE
Error from using ChromaDB - ValueError: Could not connect to tenant default_tenant. Are you sure it exists?

### ISSUE THREAD

**Issue by piyushyadav0191** [langchain-ai/langchain#26884]
### URL

https://python.langchain.com/v0.2/docs/integrations/vectorstores/chroma/

### Checklist

- [x] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I followed proper documentation for langchain_chroma but still getting this error -> ValueError: Could not connect to tenant default_tenant. Are you sure it exists?

This is my small code - 

```py

import streamlit as st
from langchain.chains import create_history_aware_retriever, create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_chroma import Chroma
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_groq import ChatGroq
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
import os




from dotenv import load_dotenv
load_dotenv()

os.environ['HF_TOKEN']=os.getenv("HF_TOKEN")
embeddings=HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

vector_store = Chroma(
    collection_name="example_collection",
    embedding_function=embeddings,
    persist_directory="./chroma_langchain_db",  # Where to save data locally, remove if not neccesary
)

## set up Streamlit 
st.title("Conversational RAG With PDF uplaods and chat history")
st.write("Upload Pdf's and chat with their content")

## Input the Groq API Key
api_key=st.text_input("Enter your Groq API key:",type="password")

## Check if groq api key is provided
if api_key:
    llm=ChatGroq(groq_api_key=api_key,model_name="Gemma2-9b-It")

    ## chat interface

    session_id=st.text_input("Session ID",value="default_session")
    ## statefully manage chat history

    if 'store' not in st.session_state:
        st.session_state.store={}

    uploaded_files=st.file_uploader("Choose A PDf file",type="pdf",accept_multiple_files=True)
    ## Process uploaded  PDF's
    if uploaded_files:
        documents=[]
        for uploaded_file in uploaded_files:
            temppdf=f"./temp.pdf"
            with open(temppdf,"wb") as file:
                file.write(uploaded_file.getvalue())
                file_name=uploaded_file.name

            loader=PyPDFLoader(temppdf)
            docs=loader.load()
            documents.extend(docs)

    # Split and create embeddings for the documents
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=5000, chunk_overlap=500)
        splits = text_splitter.split_documents(documents)
        vectorstore = vector_store.from_documents(documents=splits, embedding=embeddings)
        retriever = vectorstore.as_retriever()    

        contextualize_q_system_prompt=(
            "Given a chat history and the latest user question"
            "which might reference context in the chat history, "
            "formulate a standalone question which can be understood "
            "without the chat history. Do NOT answer the question, "
            "just reformulate it if needed and otherwise return it as is."
        )
        contextualize_q_prompt = ChatPromptTemplate.from_messages(
                [
                    ("system", contextualize_q_system_prompt),
                    MessagesPlaceholder("chat_history"),
                    ("human", "{input}"),
                ]
            )
        
        history_aware_retriever=create_history_aware_retriever(llm,retriever,contextualize_q_prompt)

        ## Answer question

        # Answer question
        system_prompt = (
                "You are an assistant for question-answering tasks. "
                "Use the following pieces of retrieved context to answer "
                "the question. If you don't know the answer, say that you "
                "don't know. Use three sentences maximum and keep the "
                "answer concise."
                "\n\n"
                "{context}"
            )
        qa_prompt = ChatPromptTemplate.from_messages(
                [
                    ("system", system_prompt),
                    MessagesPlaceholder("chat_history"),
                    ("human", "{input}"),
                ]
            )
        
        question_answer_chain=create_stuff_documents_chain(llm,qa_prompt)
        rag_chain=create_retrieval_chain(history_aware_retriever,question_answer_chain)

        def get_session_history(session:str)->BaseChatMessageHistory:
            if session_id not in st.session_state.store:
                st.session_state.store[session_id]=ChatMessageHistory()
            return st.session_state.store[session_id]
        
        conversational_rag_chain=RunnableWithMessageHistory(
            rag_chain,get_session_history,
            input_messages_key="input",
            history_messages_key="chat_history",
            output_messages_key="answer"
        )

        user_input = st.text_input("Your question:")
        if user_input:
            session_history=get_session_history(session_id)
            response = conversational_rag_chain.invoke(
                {"input": user_input},
                config={
                    "configurable": {"session_id":session_id}
                },  # constructs a key "abc123" in `store`.
            )
            st.write(st.session_state.store)
            st.write("Assistant:", response['answer'])
            st.write("Chat History:", session_history.messages)
else:
    st.warning("Please enter the GRoq API Key")


```

**Comment by Devparihar5** [comment]
I'm also getting Same error

```python
vectorstore = Chroma.from_texts(to_vectorize, RagSamples.embedding_function, metadatas=examples)
```

I have been using this code for over 10 days, and it works fine. However, today it suddenly started giving me the following error:

```
ValueError: Could not connect to tenant default_tenant. Are you sure it exists?
```

This issue has appeared unexpectedly, and I haven’t changed the configuration.

**Comment by piyushyadav0191** [comment]
Yes, It worked 2 days ago but not working since yesterday

**Comment by Devparihar5** [comment]
If you're encountering the error, you might want to try the following solution:

```python
chromadb.api.client.SharedSystemClient.clear_system_cache()
```

You can use this after each request. For me, this worked and resolved the issue.

**Comment by piyushyadav0191** [comment]
@Devparihar5 How to create this chromedb?

because We can create only with Chroma function provided from langchain_chroma

**Comment by piyushyadav0191** [comment]
Thanks it worked

```py
import chromadb.api

chromadb.api.client.SharedSystemClient.clear_system_cache()
```

**Comment by aymenkrifa** [comment]
It doesn't work for me, though this error only occurs when I deploy the app and database with K8S. Also, the exception is raised at the beginning of the app when instantiating a `HttpClient` object

**Comment by Devparihar5** [comment]
@aymenkrifa can you provide more details like how's your code

**Comment by piyushyadav0191** [comment]
Reopened the issue because this error occurs on production even clear_system_cache enabled

**Comment by Devparihar5** [comment]
@piyushyadav0191 it worked for me locally and also on production, I'm a docker container for this

**Comment by piyushyadav0191** [comment]
Can you share some pieces of code for understanding how you configured this on docker

**Comment by SaadAsgharAli** [comment]
> If you're encountering the error, you might want to try the following solution:
> 
> ```python
> import chromadb
> 
> chromadb.api.client.SharedSystemClient.clear_system_cache()
> ```
> 
> You can use this after each request. For me, this worked and resolved the issue.
</br>
Thank You!

**Comment by argueddd** [comment]
> If you're encountering the error, you might want to try the following solution:
> 
> ```python
> import chromadb
> 
> chromadb.api.client.SharedSystemClient.clear_system_cache()
> ```
> 
> You can use this after each request. For me, this worked and resolved the issue.
It woks！ You deserve the best！ Have a nice day，my freind！

**Comment by wdcnuwan** [comment]
its worked bro

**Comment by AnirbanG-git** [comment]
> If you're encountering the error, you might want to try the following solution:
> 
> ```python
> import chromadb
> 
> chromadb.api.client.SharedSystemClient.clear_system_cache()
> ```
> 
> You can use this after each request. For me, this worked and resolved the issue.

Yes, this worked. Thanks a ton!
Is this a bug in langchain_chroma? Is it being worked on?

**Comment by ppanja** [comment]
> If you're encountering the error, you might want to try the following solution:
> 
> ```python
> import chromadb
> 
> chromadb.api.client.SharedSystemClient.clear_system_cache()
> ```
> 
> You can use this after each request. For me, this worked and resolved the issue.

Saved my day. Thank you.

**Comment by Eknathabhiram** [comment]
> It doesn't work for me, though this error only occurs when I deploy the app and database with K8S. Also, the exception is raised at the beginning of the app when instantiating a `HttpClient` object

I am facing the same issue in the same scenario

**Comment by piergiuseppepezzoli** [comment]
@Devparihar5 I get the same problem with this simple code.
I'm working inside a devcontainer using docker-compose 

The docker compose file looks like this
`vector-database:
    container_name: ${COMPOSE_PROJECT_NAME}-vector-database
    image: chromadb/chroma:0.5.19.dev62
    environment:
      CHROMA_HOST_PORT: 8000
      CHROMA_SERVER_AUTHN_PROVIDER: chromadb.auth.token_authn.TokenAuthenticationServerProvider
      CHROMA_SERVER_AUTHN_CREDENTIALS: mypassword
     `

`import os
from langchain_chroma import Chroma
import chromadb
from chromadb.config import Settings

chromadb.api.client.SharedSystemClient.clear_system_cache()
CHROMA_HOST = os.getenv("CHROMA_HOST")
CHROMA_SERVER_AUTHN_PROVIDER = os.getenv("CHROMA_SERVER_AUTHN_PROVIDER")
CHROMA_SERVER_AUTHN_CREDENTIALS = os.getenv("CHROMA_SERVER_AUTHN_CREDENTIALS")

chroma_client = chromadb.HttpClient(
    host=CHROMA_HOST,
    port=8000,
    settings=Settings(
        chroma_client_auth_provider=CHROMA_SERVER_AUTHN_PROVIDER,
        chroma_client_auth_credentials=CHROMA_SERVER_AUTHN_CREDENTIALS),
)
`

**Comment by Devparihar5** [comment]
@piergiuseppepezzoli 

according to my code, you need to put `chromadb.api.client.SharedSystemClient.clear_system_cache()` this after each chromadb request like:

after inserting vector data
```
to_vectorize = [" ".join(example.values()) for example in examples]
            vectorstore = Chroma.from_texts(to_vectorize, RagSamples.embedding_function, metadatas=examples)
            example_selector = SemanticSimilarityExampleSelector(
                vectorstore=vectorstore,
                k=1,
            )


chromadb.api.client.SharedSystemClient.clear_system_cache()

```

**Comment by piergiuseppepezzoli** [comment]
> @Devparihar5 I get the same problem with this simple code. I'm working inside a devcontainer using docker-compose
> 
> The docker compose file looks like this
> 
> ```
> vector-database:
>     container_name: ${COMPOSE_PROJECT_NAME}-vector-database
>     image: chromadb/chroma:0.5.19.dev62
>     environment:
>       CHROMA_HOST_PORT: 8000
>       CHROMA_SERVER_AUTHN_PROVIDER: chromadb.auth.token_authn.TokenAuthenticationServerProvider
>       CHROMA_SERVER_AUTHN_CREDENTIALS: mypassword
> ```
> 
> and this is my python file
> 
> ```
> import os
> from langchain_chroma import Chroma
> import chromadb
> from chromadb.config import Settings
> 
> chromadb.api.client.SharedSystemClient.clear_system_cache()
> CHROMA_HOST = os.getenv("CHROMA_HOST")
> CHROMA_SERVER_AUTHN_PROVIDER = os.getenv("CHROMA_SERVER_AUTHN_PROVIDER")
> CHROMA_SERVER_AUTHN_CREDENTIALS = os.getenv("CHROMA_SERVER_AUTHN_CREDENTIALS")
> 
> chroma_client = chromadb.HttpClient(
>     host=CHROMA_HOST,
>     port=8000,
>     settings=Settings(
>         chroma_client_auth_provider=CHROMA_SERVER_AUTHN_PROVIDER,
>         chroma_client_auth_credentials=CHROMA_SERVER_AUTHN_CREDENTIALS),
> )
> ```

thanks @Devparihar5  for the suggestions, I however found another bug in my code, which is now fixed:

I used 
`CHROMA_SERVER_AUTHN_PROVIDER = chromadb.auth.token_authn.TokenAuthenticationServerProvider `
while I should have used 
`chromadb.auth.token_authn.TokenAuthClientProvider`


I also rolled back to chromadb image version to 0.5.6.dev75  to fix an additional bug that I got afterwards

**Comment by ekkkkki** [comment]
Same problem with @aymenkrifa when using HttpClient
I have two chroma & two backend instance (as `dev1` & `dev2` environment seperately) deployed in a same PaaS, and the error occurs at only one of them.

```
# utils.py
from chromadb import HttpClient
from langchain_chroma import Chroma

from chromadb.api.client import SharedSystemClient as SSC
SSC.clear_system_cache()

def init_chroma_database():
    SSC.clear_system_cache()
    chroma_client = HttpClient(host=CHROMA_HOST, port=CHROMA_PORT)
    return Chroma(
        client=chroma_client,
        collection_name=CHROMA_COLLECTION,
        embedding_function=OpenAIEmbeddings(
            model=Config.OPENAI_EMBEDDINGS_MODEL_NAME, api_key=Config.OPENAI_API_KEY
        ),
    )
```

And during initializing the backend app, 
```
# __init__.py
def create_app():
  ...
  vectorstore = init_chroma_database()
  # do something with vectorstore
  SSC.clear_system_cache()
```

**Comment by Jashwanthallenki** [comment]
> > If you're encountering the error, you might want to try the following solution:
> > ```python
> > import chromadb
> > 
> > chromadb.api.client.SharedSystemClient.clear_system_cache()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can use this after each request. For me, this worked and resolved the issue.
> > It woks！ You deserve the best！ Have a nice day，my freind！

Yeah it is working!!

**Comment by twjameschen** [comment]
I'm facing the same issue, and i still get the same error message with using : chromadb.api.client.SharedSystemClient.clear_system_cache()

I simpley use Streamlit and Chroma , the error happend on this line:
vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddingmodel)

Here's the codes:
.........
data = loader.load()
text_splitter = RecursiveCharacterTextSplitter(
	chunk_size=400, 
	chunk_overlap=100,
)
chunks = text_splitter.split_documents(data)
vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddingmodel) => error happened.
chromadb.api.client.SharedSystemClient.clear_system_cache() => seems not working.

Langchain 0.3.13
chromadb 0.5.23
langchain-chroma 0.1.4

Please help ><

**Comment by PSWindows** [comment]
thi worked
import chromadb
chromadb.api.client.SharedSystemClient.clear_system_cache()

**Comment by naicud** [comment]
**Solution: Use Explicit EphemeralClient**

I encountered the same issue and found a robust solution. The root cause is that 
Chroma()
 without an explicit 
client
 parameter tries to connect to a ChromaDB server with default_tenant, which fails if no server is running.


✅ Fix
Pass an explicit chromadb.EphemeralClient() to the 
client
 parameter when instantiating 
Chroma
:

python
import chromadb
from langchain_chroma import Chroma
client = chromadb.EphemeralClient()
vector_store = Chroma(
    collection_name="my_collection",
    embedding_function=embeddings,
    client=client,  # ← This is the key fix
)
For Chroma.from_documents():

python
vector_store = Chroma.from_documents(
    documents,
    embeddings,
    client=chromadb.EphemeralClient(),
)

**Why this works**
EphemeralClient is a fully in-memory client that doesn't require any server or tenant configuration
It explicitly tells langchain-chroma to use in-memory storage instead of trying to connect to a server
No workarounds like SharedSystemClient.clear_system_cache() needed


**Environment**
chromadb ~0.5.18
langchain-chroma ^0.2.2


This is the proper architectural fix. The issue is that the default behavior of 
Chroma()
 without a client is ambiguous - it should probably default to EphemeralClient for simpler local usage.
