### ISSUE TITLE
Beartype Forward Ref Exception when trying to create simple custom BaseRetriever

### ISSUE THREAD

**Issue by rgallardone** [langchain-ai/langchain#26898]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_core.retrievers import BaseRetriever
from langchain_core.callbacks import CallbackManagerForRetrieverRun
from langchain_core.documents import Document

class CustomRetriever(BaseRetriever):


    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> list[Document]:
        """Get documents relevant to a query.

        Parameters
        ----------
        query : str
            Query to find relevant documents for.
        run_manager : CallbackManagerForRetrieverRun
            Callbacks handler to use.

        Returns
        -------
        list[Document]
            List of relevant documents.
        """
        
        return []
```

### Error Message and Stack Trace (if applicable)

```
>>> from mypackage.test_tool import CustomRetriever
>>> CustomRetriever()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 110, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/pydantic/main.py", line 211, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "<@beartype(pydantic._internal._model_construction.ModelMetaclass.__new__.wrapped_model_post_init) at 0x118bfacb0>", line 17, in wrapped_model_post_init
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefmeta.py", line 149, in __instancecheck__
    return cls.__is_instance_beartype__(obj)
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefabc.py", line 111, in __is_instance_beartype__
    return isinstance(obj, cls.__type_beartype__)  # type: ignore[arg-type]
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_check/forward/reference/fwdrefmeta.py", line 279, in __type_beartype__
    referee = import_module_attr(
  File "/Users/toti/workspace/.venv/lib/python3.10/site-packages/beartype/_util/module/utilmodimport.py", line 295, in import_module_attr
    raise exception_cls(exception_message)
beartype.roar.BeartypeCallHintForwardRefException: Forward reference "BaseModel" unimportable from module "pydantic._internal._model_construction".
```

### Description

I'm using `beartype` to type-check my custom package, called `mypackage`. I'm trying to create a custom `BaseRetriever`, but when I try to instantiate my `CustomRetriever`, `beartype` throws the following exception:

`beartype.roar.BeartypeCallHintForwardRefException: Forward reference "BaseModel" unimportable from module "pydantic._internal._model_construction".`

I believe the exception is also tied to `pydantic`.

I attach some very minimal code that will trigger this error.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
> Python Version:  3.10.14 (main, Sep 18 2024, 09:45:07) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.5
> langchain: 0.3.0
> langchain_community: 0.3.0
> langsmith: 0.1.128
> langchain_openai: 0.2.0
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.6
> async-timeout: 4.0.3
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.48.0
> orjson: 3.10.7
> packaging: 21.3
> pydantic: 2.9.0
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by eyurtsev** [comment]
This looks like a bug in beartype rather than pydantic or langchain. Perhaps file an issue with that repo directly?

**Comment by eyurtsev** [comment]
Going to close for now since it doesn't look related to langchain code
