### ISSUE TITLE
Blocking sync code is used when using rate limiting in async code

### ISSUE THREAD

**Issue by esciara** [langchain-ai/langchain#26913]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Not applicable as current code runs but is blocked by non async code.

### Error Message and Stack Trace (if applicable)

N/A

### Description

Async code is using sync (blocking code) when using rate limiting in two places:

In `BaseChatModel.astream()`:
https://github.com/langchain-ai/langchain/blob/02f5962cf17459350d0b546c3fba5a458e587848/libs/core/langchain_core/language_models/chat_models.py#L465-L466

In `BaseChatModel._agenerate_with_cache()`:
https://github.com/langchain-ai/langchain/blob/02f5962cf17459350d0b546c3fba5a458e587848/libs/core/langchain_core/language_models/chat_models.py#L907-L908

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
> Python Version:  3.12.2 (main, Feb 27 2024, 16:53:46) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Package Information
-------------------
> langchain_core: 0.3.6
> langchain: 0.3.1
> langchain_community: 0.3.1
> langsmith: 0.1.128
> langchain_openai: 0.2.1
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.6
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.48.0
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by eyurtsev** [comment]
Closing as this was fixed with your PR! thank you
