### ISSUE TITLE
This code file: scripts/update_mypy_ruff.py needs few changes in it to run the code smoothly.

### ISSUE THREAD

**Issue by vignesh1507** [langchain-ai/langchain#26945]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

In the code file scripts/update_mypy_ruff.py some changes are required that are as follows:

1. tomllib Import Compatibility:

- The tomllib module is only available starting from Python 3.11. If you're using a Python version older than 3.11, this will raise an ImportError. If compatibility with older versions of Python is important, consider using the toml package (which you're already importing) instead.
- Fix: Use the toml package for reading as well:
```
import toml  # Already imported

with open(path, "r") as f:
    pyproject = toml.load(f)
 
```

### Error Message and Stack Trace (if applicable)

The code will raise an ImportError as the code is compatible to for python 3.11 and above only.

### Description

I'm trying to make the code compatible to all python version possible.

### System Info

python version: 3.12
OS: macOS
langchain version: v0.2

**Comment by eyurtsev** [comment]
Hi @vignesh1507 thank you for the report, but these are internal scripts for maintainers rather than user or even developer facing. We should document them better as such and explain what they do, but most of the content in `scripts` is for some CI purposes
