### ISSUE TITLE
Issue with ChatBedrockConverse and Bedrock Claude Model: ValidationException on Blank Text Field

### ISSUE THREAD

**Issue by rpgeddam** [langchain-ai/langchain#26968]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

- Use Langchain to create a conversation with the Bedrock Claude model via the Converse API.
- Implement a flow that involves tool usage, leading to empty content messages.
- Observe the error: ValidationException due to a blank text field in the ContentBlock object.

### Error Message and Stack Trace (if applicable)

```
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ConverseStream operation: The content field in the Message object at messages.3 is empty. Add a ContentBlock object to the content field and try again.
```

It is the exact same issue as this one: https://github.com/langchain-ai/langchainjs/issues/5960
Except that one is in the js library, this report is for python.

### Description

This issue does not occur in BedrockChat. It is specific to ChatBedrockConverse.

### System Info

```
langchain-community = "^0.3.1"
langchain-aws = "^0.2.1"
```

**Comment by keenborder786** [comment]
@rpgeddam  can you please share the code snippet which is causing this error...

**Comment by rpgeddam** [comment]
I think this issue needs to be in https://github.com/langchain-ai/langchain-aws

I'll close this one and open another there with a code snippet.

**Comment by rpgeddam** [comment]
New Issue here: https://github.com/langchain-ai/langchain-aws/issues/219
