### ISSUE TITLE
The nGQL statements generated by querying the Nebula map database will have  “```”

### ISSUE THREAD

**Issue by wuhu6** [langchain-ai/langchain#26981]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain.chains import NebulaGraphQAChain
from langchain_community.graphs import NebulaGraph
from langchain_openai import ChatOpenAI
from langchain_community.chat_models import ChatZhipuAI

graph = NebulaGraph(space="langchain",username="**",password="**",address="**",port=**,session_pool_size=30)
os.environ["ZHIPUAI_API_KEY"] = "**"

chat = ChatZhipuAI(
    model="glm-4-0520",
    temperature=0.5,
)

chain = NebulaGraphQAChain.from_llm(
    chat, graph=graph, verbose=True,allow_dangerous_requests = True
)

result = chain.run("Who acted in The Godfather Coda: The Death of Michael Corleone?")
print(result)

### Error Message and Stack Trace (if applicable)

![企业微信截图_17275722445474](https://github.com/user-attachments/assets/1ebf4538-aaad-4cbb-b06e-da3239687639)
![企业微信截图_17275722586752](https://github.com/user-attachments/assets/269d3bcc-7cb9-4657-a59b-232343b87fe3)

### Description

Sometimes the generated statements do not have exceptions, and sometimes there are exceptions

### System Info

a

**Comment by yixuanpenn** [comment]
这个问题如何解决？
