### ISSUE TITLE
generation_info for ChatOpenAI model

### ISSUE THREAD

**Issue by vickyliin** [langchain-ai/langchain#2702]
I noticed llm `OpenAI` returns `finish_reason` in `generation_info` https://github.com/hwchase17/langchain/pull/526
But chat_model `ChatOpenAI`'s `generation_info` is `None`

```python
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage

chat = ChatOpenAI(temperature=0)
messages = [
    SystemMessage(
        content="You are a helpful assistant that translates English to French."
    ),
    HumanMessage(
        content="Translate this sentence from English to French. I love programming."
    ),
]
result = chat.generate([messages])
result.generations[0][0]
```
```
ChatGeneration(text="J'aime programmer.", generation_info=None, message=AIMessage(content="J'aime programmer.", additional_kwargs={}))
```

Should we just add `generation_info` to the `ChatGeneration` of `ChatOpenAI` like `OpenAI`? I can help to create a PR if needed.

https://github.com/hwchase17/langchain/blob/955bd2e1db8d008d628963cb8d2bad5c1d354744/langchain/chat_models/openai.py#L284

https://github.com/hwchase17/langchain/blob/1f557ffa0e6c4c2137109d6a014b0617e9885b02/langchain/llms/openai.py#L170-L173

**Comment by bgoosmanviz** [comment]
Please do!

**Comment by tabacof** [comment]
Hey @vickyliin, any news? Having finish_reason for chat completions would be great!

**Comment by vickyliin** [comment]
Hi, sorry that because our use cases for now are relatively simple, we decided to build a light-weight solution by ourselves instead of using langchain.
https://github.com/livingbio/gpt-fn
