### ISSUE TITLE
having some trouble when linking to MySQL

### ISSUE THREAD

**Issue by yaohongfenglove** [langchain-ai/langchain#2705]
Hi, I'm having some trouble when **linking to MySQL**. Does it only support connecting to sqlite? There seems to be **no introduction to connecting to MySQL in the document**

**Comment by timothepearce** [comment]
Maybe you need to install `mysqlclient` before using it?

**Comment by skdjoy** [comment]
`from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms import OpenAI
from langchain.agents import AgentExecutor
from langchain.agents import create_sql_agent
import pymysql
db = SQLDatabase.from_uri("mysql+pymysql://<username>:<password>@<host>/<dbname>[?<options>]"
)
toolkit = SQLDatabaseToolkit(db=db)
llm=OpenAI(temperature=0)

agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True
)`

I am facing the following error, ignore the uri string

AttributeError                            Traceback (most recent call last)
Cell In[70], line 9
      6 toolkit = SQLDatabaseToolkit(db=db)
      7 llm=OpenAI(temperature=0)
----> 9 agent_executor = create_sql_agent(
     10     llm=llm,
     11     toolkit=toolkit,
     12     verbose=True
     13 )
     14 def create_sql_agent(
     15     llm: BaseLLM,
     16     toolkit: SQLDatabaseToolkit,
   (...)
     26     **kwargs: Any,
     27 ) -> AgentExecutor:
     28     """Construct a sql agent from an LLM and tools."""
---> 29     tools = toolkit.get_tools()
     30     prefix = prefix.format(dialect=toolkit.dialect, top_k=top_k)
     31     prompt = ZeroShotAgent.create_prompt(
     32         tools,
     33         prefix=prefix,
   (...)
...
     94 Use this tool to double check if your query is correct before executing it.
     95 Always use this tool before executing a query with query_sql_db!
     96 """

AttributeError: type object 'QueryCheckerTool' has no attribute 'llm'

**Comment by xuanloct4** [comment]
How can I use the password with some special characters like the one ends with a `@` character 
For example `mysql+pymysql://<username>:password@@localhost/dbname`
