### ISSUE TITLE
max_tokens is set to 1024 by default in ChatAnthropic, instead of being omitted

### ISSUE THREAD

**Issue by antonioalegria** [langchain-ai/langchain#27067]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
class ChatAnthropic(BaseChatModel):
    ...
    max_tokens: int = Field(default=1024, alias="max_tokens_to_sample")
    """Denotes the number of tokens to predict per generation."""
    ...
```

### Description

* ChatOpenAI allows you to not set max_tokens, so that it uses the model's maximum.
* ChatAnthropic sets 1024 by default and you have no way to tell it to use the model's maximum.
* The documentation https://python.langchain.com/api_reference/anthropic/chat_models/langchain_anthropic.chat_models.ChatAnthropic.html says (wrongly) at the top that max_tokens is Optional[int] = None.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
> Python Version:  3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.3.7
> langchain: 0.3.1
> langchain_community: 0.3.1
> langsmith: 0.1.129
> langchain_anthropic: 0.2.1
> langchain_openai: 0.2.1
> langchain_text_splitters: 0.3.0
> langchainhub: 0.1.21
> langgraph: 0.2.32
> langserve: 0.3.0

Other Dependencies
------------------
> aiohttp: 3.10.0
> anthropic: 0.34.2
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> defusedxml: 0.7.1
> fastapi: 0.115.0
> httpx: 0.27.0
> jsonpatch: 1.33
> langgraph-checkpoint: 2.0.0
> numpy: 1.26.4
> openai: 1.51.0
> orjson: 3.10.6
> packaging: 24.1
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> PyYAML: 6.0.1
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> sse-starlette: 2.1.3
> tenacity: 8.5.0
> tiktoken: 0.7.0
> types-requests: 2.32.0.20240712
> typing-extensions: 4.12.2

**Comment by arindam-giri** [comment]
As per I know, you can pass it as model kwargs
For example in bedrock like this below. Similar you pass via ChatAnthropic API call

```
max_tokens_to_sample = 4000
llm = Bedrock(client=bedrock_runtime, model_id="anthropic.claude-v2")
llm.model_kwargs = {"temperature": 0.7, "max_tokens_to_sample": max_tokens_to_sample}
```

**Comment by antonioalegria** [comment]
Yes, we can, but I'd like to not have to pass it so that it uses the underlying model's maximum, just like we can do with OpenAI.

**Comment by krillinkills** [comment]
so if you dont pass max tokens then it should be whatever model's maximum is it? @antonioalegria instead of that it is set to 1024?

**Comment by baskaryan** [comment]
@antonioalegria i hear you but unfortunately the Anthropic sdk currently requires max_tokens be specified as an int, so there is no option to pass in None. from their sdk:

```python
    @required_args(["max_tokens", "messages", "model"], ["max_tokens", "messages", "model", "stream"])
    def create(
        self,
        *,
        max_tokens: int,
        messages: Iterable[MessageParam],
        model: ModelParam,
        metadata: message_create_params.Metadata | NotGiven = NOT_GIVEN,
        stop_sequences: List[str] | NotGiven = NOT_GIVEN,
        stream: Literal[False] | Literal[True] | NotGiven = NOT_GIVEN,
        system: Union[str, Iterable[TextBlockParam]] | NotGiven = NOT_GIVEN,
        temperature: float | NotGiven = NOT_GIVEN,
        tool_choice: message_create_params.ToolChoice | NotGiven = NOT_GIVEN,
        tools: Iterable[ToolParam] | NotGiven = NOT_GIVEN,
        top_k: int | NotGiven = NOT_GIVEN,
        top_p: float | NotGiven = NOT_GIVEN,
        # Use the following arguments if you need to pass additional parameters to the API that aren't available via kwargs.
        # The extra values given here take precedence over values defined on the client or passed to this method.
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    ) -> Message | Stream[RawMessageStreamEvent]:
```

**Comment by baskaryan** [comment]
and good catch on the docstring, that should be typed as int: https://github.com/langchain-ai/langchain/pull/27166

**Comment by antonioalegria** [comment]
Got it, makes sense. Then it's just a matter of fixing the docstring.

**Comment by baskaryan** [comment]
docs updated. closing issue, let me know if im missing something
