### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain' (Even though LangChain is installed)

### ISSUE THREAD

**Issue by aodrasa** [langchain-ai/langchain#2707]
Running from the same environment and have tried uninstalling/reinstalling - still getting this error.

Anyone have a fix or know what I could be doing wrong?

<img width="632" alt="Screenshot 2023-04-11 at 7 05 40 pm" src="https://user-images.githubusercontent.com/121209163/231112960-f55b80dc-93ae-4a96-abc2-33efa7b8cee1.png">

**Comment by lv-alex** [comment]
if virtual environment, try
%which python
and run your program with it

**Comment by joeljerushan** [comment]
Im using render.com im facing the same error here - 
![image](https://user-images.githubusercontent.com/10111309/231342660-16f05c90-a92b-4585-9297-019f8ed3972c.png)
