### ISSUE TITLE
"cannot pickle 'classmethod' object error" in ChatGroq

### ISSUE THREAD

**Issue by VamshiKrsna** [langchain-ai/langchain#27144]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code : 
```python
from langchain_groq import ChatGroq
```
It is giving me this error every time :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 2
      1 import os
----> 2 from langchain_groq import ChatGroq
      3 from langchain_openai import OpenAIEmbeddings
      4 from langchain.text_splitter import RecursiveCharacterTextSplitter

File C:\Python312\Lib\site-packages\langchain_groq\__init__.py:1
----> 1 from langchain_groq.chat_models import ChatGroq
      3 __all__ = ["ChatGroq"]

File C:\Python312\Lib\site-packages\langchain_groq\chat_models.py:89
     79 from pydantic import (
     80     BaseModel,
     81     ConfigDict,
   (...)
     84     model_validator,
     85 )
     86 from typing_extensions import Self
---> 89 class ChatGroq(BaseChatModel):
     90     """`Groq` Chat large language models API.
     91 
     92     To use, you should have the
   (...)
    298             'logprobs': None}
    299     """
    301     client: Any = Field(default=None, exclude=True)  #: :meta private:

File C:\Python312\Lib\site-packages\pydantic\v1\main.py:221, in ModelMetaclass.__new__(mcs, name, bases, namespace, **kwargs)
    219 elif is_valid_field(var_name) and var_name not in annotations and can_be_changed:
    220     validate_field_name(bases, var_name)
--> 221     inferred = ModelField.infer(
    222         name=var_name,
    223         value=value,
    224         annotation=annotations.get(var_name, Undefined),
    225         class_validators=vg.get_validators(var_name),
    226         config=config,
    227     )
    228     if var_name in fields:
    229         if lenient_issubclass(inferred.type_, fields[var_name].type_):

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:504, in ModelField.infer(cls, name, value, annotation, class_validators, config)
    501     required = False
    502 annotation = get_annotation_from_field_info(annotation, field_info, name, config.validate_assignment)
--> 504 return cls(
    505     name=name,
    506     type_=annotation,
    507     alias=field_info.alias,
    508     class_validators=class_validators,
    509     default=value,
    510     default_factory=field_info.default_factory,
    511     required=required,
    512     model_config=config,
    513     field_info=field_info,
    514 )

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:434, in ModelField.__init__(self, name, type_, class_validators, model_config, default, default_factory, required, final, alias, field_info)
    432 self.shape: int = SHAPE_SINGLETON
    433 self.model_config.prepare_field(self)
--> 434 self.prepare()

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:544, in ModelField.prepare(self)
    537 def prepare(self) -> None:
    538     """
    539     Prepare the field but inspecting self.default, self.type_ etc.
    540 
    541     Note: this method is **not** idempotent (because _type_analysis is not idempotent),
    542     e.g. calling it it multiple times may modify the field and configure it incorrectly.
    543     """
--> 544     self._set_default_and_type()
    545     if self.type_.__class__ is ForwardRef or self.type_.__class__ is DeferredType:
    546         # self.type_ is currently a ForwardRef and there's nothing we can do now,
    547         # user will need to call model.update_forward_refs()
    548         return

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:568, in ModelField._set_default_and_type(self)
    563         raise errors_.ConfigError(
    564             f'you need to set the type of field {self.name!r} when using `default_factory`'
    565         )
    566     return
--> 568 default_value = self.get_default()
    570 if default_value is not None and self.type_ is Undefined:
    571     self.type_ = default_value.__class__

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:437, in ModelField.get_default(self)
    436 def get_default(self) -> Any:
--> 437     return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()

File C:\Python312\Lib\site-packages\pydantic\v1\utils.py:693, in smart_deepcopy(obj)
    689 except (TypeError, ValueError, RuntimeError):
    690     # do we really dare to catch ALL errors? Seems a bit risky
    691     pass
--> 693 return deepcopy(obj)

File C:\Python312\Lib\copy.py:162, in deepcopy(x, memo, _nil)
    160                 y = x
    161             else:
--> 162                 y = _reconstruct(x, memo, *rv)
    164 # If is its own copy, don't memoize.
    165 if y is not x:

File C:\Python312\Lib\copy.py:259, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    257 if state is not None:
    258     if deep:
--> 259         state = deepcopy(state, memo)
    260     if hasattr(y, '__setstate__'):
    261         y.__setstate__(state)

File C:\Python312\Lib\copy.py:136, in deepcopy(x, memo, _nil)
    134 copier = _deepcopy_dispatch.get(cls)
    135 if copier is not None:
--> 136     y = copier(x, memo)
    137 else:
    138     if issubclass(cls, type):

File C:\Python312\Lib\copy.py:221, in _deepcopy_dict(x, memo, deepcopy)
    219 memo[id(x)] = y
    220 for key, value in x.items():
--> 221     y[deepcopy(key, memo)] = deepcopy(value, memo)
    222 return y

File C:\Python312\Lib\copy.py:151, in deepcopy(x, memo, _nil)
    149 reductor = getattr(x, "__reduce_ex__", None)
    150 if reductor is not None:
--> 151     rv = reductor(4)
    152 else:
    153     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle 'classmethod' object

### Description

The following code : 
```python
from langchain_groq import ChatGroq
```
It is giving me this error every time :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 2
      1 import os
----> 2 from langchain_groq import ChatGroq
      3 from langchain_openai import OpenAIEmbeddings
      4 from langchain.text_splitter import RecursiveCharacterTextSplitter

File C:\Python312\Lib\site-packages\langchain_groq\__init__.py:1
----> 1 from langchain_groq.chat_models import ChatGroq
      3 __all__ = ["ChatGroq"]

File C:\Python312\Lib\site-packages\langchain_groq\chat_models.py:89
     79 from pydantic import (
     80     BaseModel,
     81     ConfigDict,
   (...)
     84     model_validator,
     85 )
     86 from typing_extensions import Self
---> 89 class ChatGroq(BaseChatModel):
     90     """`Groq` Chat large language models API.
     91 
     92     To use, you should have the
   (...)
    298             'logprobs': None}
    299     """
    301     client: Any = Field(default=None, exclude=True)  #: :meta private:

File C:\Python312\Lib\site-packages\pydantic\v1\main.py:221, in ModelMetaclass.__new__(mcs, name, bases, namespace, **kwargs)
    219 elif is_valid_field(var_name) and var_name not in annotations and can_be_changed:
    220     validate_field_name(bases, var_name)
--> 221     inferred = ModelField.infer(
    222         name=var_name,
    223         value=value,
    224         annotation=annotations.get(var_name, Undefined),
    225         class_validators=vg.get_validators(var_name),
    226         config=config,
    227     )
    228     if var_name in fields:
    229         if lenient_issubclass(inferred.type_, fields[var_name].type_):

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:504, in ModelField.infer(cls, name, value, annotation, class_validators, config)
    501     required = False
    502 annotation = get_annotation_from_field_info(annotation, field_info, name, config.validate_assignment)
--> 504 return cls(
    505     name=name,
    506     type_=annotation,
    507     alias=field_info.alias,
    508     class_validators=class_validators,
    509     default=value,
    510     default_factory=field_info.default_factory,
    511     required=required,
    512     model_config=config,
    513     field_info=field_info,
    514 )

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:434, in ModelField.__init__(self, name, type_, class_validators, model_config, default, default_factory, required, final, alias, field_info)
    432 self.shape: int = SHAPE_SINGLETON
    433 self.model_config.prepare_field(self)
--> 434 self.prepare()

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:544, in ModelField.prepare(self)
    537 def prepare(self) -> None:
    538     """
    539     Prepare the field but inspecting self.default, self.type_ etc.
    540 
    541     Note: this method is **not** idempotent (because _type_analysis is not idempotent),
    542     e.g. calling it it multiple times may modify the field and configure it incorrectly.
    543     """
--> 544     self._set_default_and_type()
    545     if self.type_.__class__ is ForwardRef or self.type_.__class__ is DeferredType:
    546         # self.type_ is currently a ForwardRef and there's nothing we can do now,
    547         # user will need to call model.update_forward_refs()
    548         return

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:568, in ModelField._set_default_and_type(self)
    563         raise errors_.ConfigError(
    564             f'you need to set the type of field {self.name!r} when using `default_factory`'
    565         )
    566     return
--> 568 default_value = self.get_default()
    570 if default_value is not None and self.type_ is Undefined:
    571     self.type_ = default_value.__class__

File C:\Python312\Lib\site-packages\pydantic\v1\fields.py:437, in ModelField.get_default(self)
    436 def get_default(self) -> Any:
--> 437     return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()

File C:\Python312\Lib\site-packages\pydantic\v1\utils.py:693, in smart_deepcopy(obj)
    689 except (TypeError, ValueError, RuntimeError):
    690     # do we really dare to catch ALL errors? Seems a bit risky
    691     pass
--> 693 return deepcopy(obj)

File C:\Python312\Lib\copy.py:162, in deepcopy(x, memo, _nil)
    160                 y = x
    161             else:
--> 162                 y = _reconstruct(x, memo, *rv)
    164 # If is its own copy, don't memoize.
    165 if y is not x:

File C:\Python312\Lib\copy.py:259, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    257 if state is not None:
    258     if deep:
--> 259         state = deepcopy(state, memo)
    260     if hasattr(y, '__setstate__'):
    261         y.__setstate__(state)

File C:\Python312\Lib\copy.py:136, in deepcopy(x, memo, _nil)
    134 copier = _deepcopy_dispatch.get(cls)
    135 if copier is not None:
--> 136     y = copier(x, memo)
    137 else:
    138     if issubclass(cls, type):

File C:\Python312\Lib\copy.py:221, in _deepcopy_dict(x, memo, deepcopy)
    219 memo[id(x)] = y
    220 for key, value in x.items():
--> 221     y[deepcopy(key, memo)] = deepcopy(value, memo)
    222 return y

File C:\Python312\Lib\copy.py:151, in deepcopy(x, memo, _nil)
    149 reductor = getattr(x, "__reduce_ex__", None)
    150 if reductor is not None:
--> 151     rv = reductor(4)
    152 else:
    153     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle 'classmethod' object

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.2.41
> langchain: 0.2.16
> langchain_community: 0.2.17
> langsmith: 0.1.129
> langchain_experimental: 0.0.65
> langchain_groq: 0.2.0
> langchain_openai: 0.1.25
> langchain_pinecone: 0.1.3
> langchain_text_splitters: 0.2.1

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.5
> async-timeout: Installed. No version info available.
> beautifulsoup4: 4.12.3
> dataclasses-json: 0.5.14
> groq: 0.9.0
> httpx: 0.27.0
> jsonpatch: 1.33
> lxml: 5.3.0
> numpy: 1.26.4
> openai: 1.51.0
> orjson: 3.10.3
> packaging: 23.2
> pinecone-client: 5.0.1
> pydantic: 2.7.3
> PyYAML: 6.0.1
> requests: 2.32.2
> SQLAlchemy: 2.0.30
> tenacity: 8.3.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.1

**Comment by ccurme** [comment]
Hi, thanks for this.

You have `langchain_groq==0.2.0` installed, which [requires langchain-core >= 0.3](https://github.com/langchain-ai/langchain/blob/59bbda9ba3651435dd30a96503436b84fb410d06/libs/partners/groq/pyproject.toml#L23), but you are running `langchain-core==0.2.41`. Re-installing `langchain-groq` should fix this for you, or you can also `pip install --upgrade langchain-core`.

Let me know if this does not solve your issue. You can find a table of what integration packages require langchain-core 0.3 here: https://python.langchain.com/docs/versions/v0_3/.

**Comment by lanaramsak** [comment]
I have the same issue and upgrading langchain doesn't seem to help:
I have: `langchain-core-0.3.11` and `langchain-groq-0.2.0` but still get the error `cannot pickle 'classmethod' object` when running the code `from langchain_groq import ChatGroq`.
