### ISSUE TITLE
FastEmbedEmbeddings is  broken

### ISSUE THREAD

**Issue by Jaid844** [langchain-ai/langchain#27161]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
embeddings = FastEmbedEmbeddings()
document_embeddings = embeddings.embed_documents(
    ["This is a document", "This is some other document"]
) 
```

### Error Message and Stack Trace (if applicable)

```
AttributeError 
else:
--> 117     embeddings = self._model.embed(
    118         texts, batch_size=self.batch_size, parallel=self.parallel
    119     )
    120 return [e.tolist() for e in embeddings]

AttributeError: 'NoneType' object has no attribute 'embed'
```

### Description

I am using langchain FastEmbedEmbeddings class to convert into embedding but I am getting an issue of the none type has no attribute embed, possibly because of 
```
_model: Any = None  # : :meta private:

```

### System Info

System Information
------------------
> OS:  Windows
> OS Version:  10.0.22631
> Python Version:  3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]

Package Information
-------------------
> langchain_core: 0.3.9
> langchain: 0.3.2
> langchain_community: 0.3.1
> langsmith: 0.1.131
> langchain_anthropic: 0.1.11
> langchain_aws: 0.1.3
> langchain_chroma: 0.1.1
> langchain_cohere: 0.1.0
> langchain_experimental: 0.3.0
> langchain_fireworks: 0.1.3
> langchain_google_community: 2.0.0
> langchain_google_genai: 0.0.9
> langchain_google_vertexai: 1.0.6
> langchain_groq: 0.1.3
> langchain_huggingface: 0.1.0
> langchain_mongodb: 0.1.3
> langchain_openai: 0.2.0
> langchain_qdrant: 0.1.3
> langchain_text_splitters: 0.3.0
> langchain_voyageai: 0.1.0
> langchainhub: 0.1.15
> langgraph: 0.2.28

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.9.3
> anthropic: 0.31.0
> anthropic[vertexai]: Installed. No version info available.
> async-timeout: 4.0.3
> beautifulsoup4: 4.12.3
> boto3: 1.34.144
> chromadb: 0.4.24
> cohere: 5.2.2
> dataclasses-json: 0.5.14
> db-dtypes: Installed. No version info available.
> defusedxml: 0.7.1
> fastapi: 0.110.0
> fastembed: 0.3.6
> fireworks-ai: 0.14.0
> gapic-google-longrunning: Installed. No version info available.
> google-api-core: 2.17.1
> google-api-python-client: 2.147.0
> google-auth-httplib2: 0.2.0
> google-auth-oauthlib: 0.4.6
> google-cloud-aiplatform: 1.59.0
> google-cloud-bigquery: 3.18.0
> google-cloud-bigquery-storage: Installed. No version info available.
> google-cloud-contentwarehouse: Installed. No version info available.
> google-cloud-core: 2.4.1
> google-cloud-discoveryengine: Installed. No version info available.
> google-cloud-documentai: Installed. No version info available.
> google-cloud-documentai-toolbox: Installed. No version info available.
> google-cloud-speech: Installed. No version info available.
> google-cloud-storage: 2.17.0
> google-cloud-texttospeech: Installed. No version info available.
> google-cloud-translate: Installed. No version info available.
> google-cloud-vision: Installed. No version info available.
> google-generativeai: 0.3.2
> googlemaps: Installed. No version info available.
> groq: 0.4.2
> grpcio: 1.66.1
> httpx: 0.27.0
> huggingface-hub: 0.23.4
> jsonpatch: 1.33
> langgraph-checkpoint: 1.0.10
> numpy: 1.26.1
> openai: 1.47.1
> orjson: 3.10.6
> packaging: 23.2
> pandas: 2.0.0
> pillow: 10.4.0
> pyarrow: 13.0.0
> pydantic: 2.9.2
> pydantic-settings: 2.5.2
> pymongo: 4.9.1
> PyYAML: 6.0.1
> qdrant-client: 1.11.1
> requests: 2.31.0
> requests-toolbelt: 1.0.0
> sentence-transformers: 3.0.1
> SQLAlchemy: 2.0.28
> tenacity: 8.3.0
> tiktoken: 0.7.0
> tokenizers: 0.19.1
> transformers: 4.42.4
> types-requests: 2.31.0.20240406
> typing-extensions: 4.12.2
> voyageai: 0.2.1
​

**Comment by Anush008** [comment]
Hi @Jaid844. This should be resolved with https://github.com/langchain-ai/langchain/pull/26764
Please update the `langchain_community` package to latest.

**Comment by Jaid844** [comment]
Thanks @Anush008 !
