### ISSUE TITLE
DOC: Incorrect API Reference Link in /docs/how_to/vectorstore_retriever/

### ISSUE THREAD

**Issue by PPraneesh** [langchain-ai/langchain#27196]
### URL

https://python.langchain.com/docs/how_to/vectorstore_retriever/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

There is an incorrect URL in the anchor tag for the VectorStoreRetriever class in the "How to use a vectorstore as a retriever" documentation page.
Location of the Issue : 
The problematic link can be found in this section of the documentation:
https://python.langchain.com/docs/how_to/vectorstore_retriever/#:~:text=VectorStoreRetriever
Current (Incorrect) URL:
https://python.langchain.com/api_reference/core/vectorstores/langchain_core.vectorstores.VectorStoreRetriever.html
Correct URL:
https://python.langchain.com/api_reference/core/vectorstores/langchain_core.vectorstores.base.VectorStoreRetriever.html
The correct URL includes .base in the path, which is missing in the current documentation.

### Idea or request for content:

Please update the markdown cell in the Jupyter notebook to use the correct URL for the VectorStoreRetriever class. The markdown should be modified as follows:
```
This creates a retriever (specifically a [VectorStoreRetriever](https://python.langchain.com/api_reference/core/vectorstores/langchain_core.vectorstores.base.VectorStoreRetriever.html)), which we can use in the usual way:
```

**Comment by connorpark24** [comment]
I can fix this.

**Comment by PPraneesh** [comment]
This issue is resolved and merged
https://github.com/langchain-ai/langchain/pull/27477
