### ISSUE TITLE
The JsonOutputParser cannot use UTF characters.

### ISSUE THREAD

**Issue by drxsx** [langchain-ai/langchain#27256]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from pydantic import BaseModel, Field
from langchain_core.output_parsers import JsonOutputParser
from langchain.prompts import PromptTemplate
    
context="anything"
class Article(BaseModel):
  title: str = Field(description="科学文章的标题")
output_data_structure=Article
parser = JsonOutputParser(pydantic_object=output_data_structure)
    
    
prompt = PromptTemplate(
  template="",
  partial_variables={"format_instructions": parser.get_format_instructions()},
)
print(prompt)

### Description

I changed line 121 in langchain_core/output_parsers/json.py from 

        schema_str == json.dumps(reduced_schema) 
to 

        schema_str == json.dumps(reduced_schema, ensure_ascii=False)
and that fixed the issue. I’m not sure if this helps.

in the example,it should output:

        ... "title": {"description": "科学文章的标题", "title": "Title", "type": "string"}} ...

but it output:

        ... "title": {"description": "\\u79d1\\u5b66\\u6587\\u7ae0\\u7684\\u6807\\u9898", "title": "Title", "type": "string"}} ...

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023
> Python Version:  3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]

Package Information
-------------------
> langchain_core: 0.3.0
> langchain: 0.3.0
> langsmith: 0.1.129
> langchain_openai: 0.2.0
> langchain_text_splitters: 0.3.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: 4.0.3
> httpx: 0.27.2
> jsonpatch: 1.33
> numpy: 1.26.4
> openai: 1.45.0
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.8.2
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.35
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2

**Comment by Harsimran-19** [comment]
Can I work on this issue?

**Comment by drxsx** [comment]
> 我可以处理这个问题吗？

sure
