### ISSUE TITLE
Question. OpenAI completion api returns 400

### ISSUE THREAD

**Issue by aladevlearning** [langchain-ai/langchain#2727]
Hi,

I tried several loaders (GitHub 
, selenium, cheerio,etc) and they retrieve correctly certain data. 

I then use splitters to split the text in multiple documents, and pass it to the open ai api with high max token.

I consistently get 400, which I believe is due to the document size. Is a legit guess? Is there some other steps I need to do in order to avoid a 400 request?

**Comment by alancamillo** [comment]
Are you trying to use two different languages on your prompt? I already have that problem when I try to mix Portuguese and English on the same prompt. 

If it is a problem, try instructing your prompt about the other language. Use most English on your prompt, and when you have to use or receive other languages as input, warn the prompt.
