### ISSUE TITLE
Custom Function Streaming in BaseTool Not Working with `astream_events`

### ISSUE THREAD

**Issue by sharrajesh** [langchain-ai/langchain#27299]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb

## Description
I'm trying to create a custom function within a tool (derived from `BaseTool`) that generates tokens after talking to a web service and streams events to `astream_events` on the agent. However, I'm encountering issues with the streaming behavior.

## Current Behavior
- Streaming works fine when using a standard LangChain chain.
- When using a custom variation, despite calling `run_manager.on_text`, the events are not received by the agent until all tokens are collected by the tool.

## Expected Behavior
- The custom function should stream events in real-time, similar to how standard LangChain chains work.
- Ideally, convert the custom function to a `RunnableLambda` so that the callback boilerplate is handled automatically, just like in standard LangChain chains.

## Code Example
I've created a minimal example demonstrating the issue: [https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb](https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb)

Key parts of the code:

```python
class StreamingExampleTool(BaseTool):
    # ... (tool setup)

    async def _arun(
        self, query: str, run_manager: Optional[AsyncCallbackManagerForToolRun] = None
    ) -> str:
        response = ""
        async for token in self._generate_tokens({"topic": query}):
            response += token
            if run_manager:
                await run_manager.on_text(token, verbose=True)
        return response

    async def _generate_tokens(self, input: dict) -> AsyncIterator[str]:
        # ... (token generation logic)
        yield full_token
        await asyncio.sleep(0.1)  # Sleep for 100ms between tokens

# ... (agent setup and execution)
```

## Questions
1. What am I missing in my custom function implementation to ensure proper streaming?
2. How can I convert my custom function to a `RunnableLambda` to handle callbacks automatically?
3. Are there any specific considerations when implementing streaming in a custom tool derived from `BaseTool`?

## Additional Context
- Environment details:
  - Python version: 3.11.3
  - langchain: 0.2.16
  - langchain-core: 0.2.41
  - langchain-openai: 0.1.25
  - openai: 1.51.2
- This functionality is crucial for my application's real-time interaction with a web service.

Any guidance or pointers to relevant documentation would be greatly appreciated. Thank you for your time and assistance!

### System Info

Python version: 3.11.3
langchain: 0.2.16
langchain-core: 0.2.41
langchain-openai: 0.1.25
openai: 1.51.2

**Comment by keenborder786** [comment]
@sharrajesh I don't think so you will be able to use streaming with the tool as it is since the `Agent` needs complete response from the tool output to make it's decision. Since I am completely aware of the conext, but if you want to stream I would recommend you break your problem into step and use multiple chains which are then using streaming.

**Comment by sharrajesh** [comment]
Thanks for the response. 

It works for a standard langchain chain as i provided in the example. This chain stream to the agent in astream_events while it's still running. 

Issue only happens with a custom function which i suspect is missing something to become good langchain "runnable " citizen 

I am possibly missing some langchain boilerplate callback that's needed for those tokens to show in the agent astream_events to be streamed back to frontend.

**Comment by sharrajesh** [comment]
@keenborder786 Apologies I was wrong. I double confirmed streaming from tools to agents does not work with langchain created chains either =[

I am going to update this issue for my mistake or intent to stream tokens from a long running tool to astream_events.

FWIW I have updated my gist to prove that tokens dont stream from tools to atream events with original langchain chain or custom Runnable or despite calling run_manager.on_text

https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb/17e6535fee28715377700681266e9850dc91c9a3

**Comment by sharrajesh** [comment]
It's odd that this code streams successfully:

```python
async def _arun(self, query: str) -> str: 
    global trace_in_astream_events
    print("begin trace in astream events")
    trace_in_astream_events = True
    chain = self._create_standard_langchain_chain()
    response = await chain.ainvoke({"topic": query})
    print("\n====Finished running ainvoke===\n")
    return response

def _create_standard_langchain_chain(self):
    prompt = ChatPromptTemplate.from_template(
        """Can you repeat this text 50 times with counter - "{topic}""""
    )
    model = ChatOpenAI()
    chain = prompt | model
    return chain
```

But this code does not stream and instead finishes within the tool:

```python
async def _arun(self, query: str) -> str:
    global trace_in_astream_events
    print("begin trace in astream events")
    trace_in_astream_events = True
    chain = self._create_custom_runnable()
    response = await chain.ainvoke({"topic": query})
    print("\n====Finished running ainvoke===\n")
    return response

def _create_custom_runnable(self):
    return RunnableLambda(self._agenerate_tokens)

async def _agenerate_tokens(self, input: dict) -> AsyncIterator[str]:
    query = input.get("topic", "")
    for i in range(50):
        full_token = f"[{i}] {query}\n"
        print(f"in _agenerate_tokens {full_token}", end="", flush=True)
        yield full_token
        await asyncio.sleep(0.1)
```

I’ve updated my gist with the latest revision showing this behavior:  
[https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb/c15bfa7c28535596a4fb3c3cfc4135255fc1b2e2](https://gist.github.com/sharrajesh/98238425679e648d3b15bb025c36ebeb/c15bfa7c28535596a4fb3c3cfc4135255fc1b2e2)

**Comment by sharrajesh** [comment]
Found a solution to enable asynchronous streaming with specific event types.

The key change is in `_arun`, where `RunnableGenerator` is used to process and yield tokens in real-time, providing a smoother, step-by-step streaming output. This implementation also incorporates an additional type, `"chain"`, in `include_types`, allowing for more granular control over the kinds of events processed within `astream_events`.

Here’s the core code update:

```python
async def _arun(self, query: str) -> str:
    global trace_in_astream_events
    print("begin trace in astream events")
    trace_in_astream_events = True
    chain = RunnableGenerator(self._transform_generate_tokens)
    response = await chain.ainvoke({"topic": query})
    print("\n====Finished running ainvoke===\n")
    return response
```

An additional for-loop and event handling logic to handle `on_chain_stream` and `on_chain_end` types for `"chain"` events was added, enabling more detailed trace logging. For more details, see the full gist [here](https://gist.github.com/sharrajesh/4dea3e32a3320d3569f702503c487839).

Let me know if this works for you!

**Comment by sharrajesh** [comment]
Found a solution as mentioned in this comment.

https://github.com/langchain-ai/langchain/issues/27299#issuecomment-2439786338
