### ISSUE TITLE
`convert_to_openai_tool` not working as intended

### ISSUE THREAD

**Issue by isahers1** [langchain-ai/langchain#27446]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
from pydantic import BaseModel
from langchain_core.tools import BaseTool
rom langchain_core.callbacks import (
     CallbackManagerForToolRun,
 )
from typing import Optional
from langchain_core.utils.function_calling import convert_to_openai_tool

 class CustomArgsSchema(BaseModel):
     a: int = Field(..., description="The first argument")
     b: str = Field(..., description="The second argument")

 class CustomBaseTool(BaseTool):
     name: str = "my_base_tool"
     description: str = "My custom base tool"
     args_schema: Type[BaseModel] = CustomArgsSchema
     return_direct: bool = True

     def _run(
         self, a: int, b: int, run_manager: Optional[CallbackManagerForToolRun] = None
     ) -> int:
         """Use the tool."""
         return a * b

convert_to_openai_tool(CustomBaseTool)
```

### Error Message and Stack Trace (if applicable)

PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'langchain_core.callbacks.base.BaseCallbackManager'>)

### Description

Doesn't work for pydantic classes, works fine for other cases

### System Info

latest versions

**Comment by ethanglide** [comment]
Hello, I was able to reproduce your issue and am interested in working on this. There seems to be trouble with inputs to this function that are `BaseTool` or derive from `BaseTool`. Do you have any other information that may help with solving this?

**Comment by ethanglide** [comment]
Looking closer into it, I believe you actually have to pass in an instance of a tool rather than the metaclass. Consider this code:

```py
from langchain_core.utils.function_calling import convert_to_openai_tool
from langchain_core.tools import BaseTool

class TestTool(BaseTool):
    name: str = "test"
    description: str = "test"
    def _run(self) -> None:
        pass

convert_to_openai_tool(TestTool())
```

It runs without errors.
