### ISSUE TITLE
Hallucination with Ollama vision models (Llava, Bakllava)

### ISSUE THREAD

**Issue by ahmedkooli** [langchain-ai/langchain#27485]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
import base64
from io import BytesIO

from IPython.display import HTML, display
from PIL import Image
from langchain_ollama import OllamaLLM


def convert_to_base64(pil_image):
    """
    Convert PIL images to Base64 encoded strings

    :param pil_image: PIL image
    :return: Re-sized Base64 string
    """

    buffered = BytesIO()
    pil_image.save(buffered, format="JPEG")  # You can change the format if needed
    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")
    return img_str


def plt_img_base64(img_base64):
    """
    Display base64 encoded string as image

    :param img_base64:  Base64 string
    """
    # Create an HTML img tag with the base64 string as the source
    image_html = f'<img src="data:image/jpeg;base64,{img_base64}" />'
    # Display the image by rendering the HTML
    display(HTML(image_html))


file_path = "./test.jpg"
pil_image = Image.open(file_path)
image_b64 = convert_to_base64(pil_image)
plt_img_base64(image_b64)


llm = OllamaLLM(model="llava")
llm_with_image_context = llm.bind(images=[image_b64])
res = llm_with_image_context.invoke("Describe this image")
```

### Description

Hey, I was trying to use vision models with Ollama and I based myself on [this tutorial](https://python.langchain.com/docs/integrations/llms/ollama/#multi-modal) found on an official Langchain page.

Unfortunately, it seems that the model is not seeing the image that I'm passing as it is hallucinating every time and outputting a very different result at each run (for example: _**The image depicts a vibrant and colorful scene, featuring a tree with lush green leaves. The tree is adorned with various decorations, including what appears to be colorful baubles and lights [...]**_ for the image of food provided below).

I tried with multiple models (Llava and Bakllava), images and prompts, but the result is always wrong. 

Note that when I try using Ollama directly in the CLI it works:
```bash
ollama run llava "describe this image ./test.jpg"
```
results in "_**Added image './test.jpg'
The image presents a vibrant display of fresh produce on a blackboard. Dominating the scene is a bundle of yellow spaghetti [...]**_"

Here's the test image 
![test](https://github.com/user-attachments/assets/af8f41c2-73f8-4732-b889-859bebbe8a97)

Thanks for the help.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:12 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6020
> Python Version:  3.11.10 | packaged by conda-forge | (main, Oct 16 2024, 01:26:25) [Clang 17.0.6 ]

Package Information
-------------------
> langchain_core: 0.3.12
> langsmith: 0.1.136
> langchain_ollama: 0.2.0

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> httpx: 0.27.2
> jsonpatch: 1.33
> ollama: 0.3.3
> orjson: 3.10.7
> packaging: 24.1
> pydantic: 2.9.2
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> tenacity: 9.0.0
> typing-extensions: 4.12.2

**Comment by JamieHvizdos** [comment]
Hi! I represent a team of students from the University of Toronto and we would like to take a look at this issue!

**Comment by ahmedkooli** [comment]
Hey @JamieHvizdos sure thanks a lot ! :)

**Comment by flashcol** [comment]
I encountered the same issue.

**Comment by liuch37** [comment]
+1 on this issue. Direct using LLaVA from ollama works great.

**Comment by VedatAlpGoktepe** [comment]
Hey everyone, I'm a part of the team working on this issue, and I wanted to let you guys know about the solution we have in mind.

We noticed that the `OllamaLLM` class, from `langchain_ollama`, didn't contain any way to pass images. The `.bind()` function didn't effect anything and there was no way to pass images through the `.invoke()` method.

For our solution, we plan to add an `images` property that can be set when defining the model or by using `.bind()`. This property will be passed to every invocation made with the model. We are also adding a prompt parser that would allow for another input type, a list of dictionaries, similar to how the `ChatOllama` class functions. Passing images in this second way would only attach them to the current prompt along with any images introduced while defining the model or attached using `.bind()`.

Please let us know what you think about our solution!

**Comment by ahmedkooli** [comment]
sounds good to me, thanks for investigating :)

**Comment by nlsferrara** [comment]
> I'm facing a similar issue. I try to use `llama3.2-vision:11b`, which is running in a ollama docker container, with langchain but I did not find a way how to pass the image in my `ChatPromptTemplate`.
> 
> This was my try:
> 
> ```python
> from langchain_ollama.llms import OllamaLLM
> 
> template = """
> [
>     (
>         "user",
>         [
>             {{"text": "{question}"}},
>             {{
>                 "type": "text",
>                 "image_url": {{
>                     "url": "data:image/jpeg;base64,{image}"
>                 }}
>             }}
>         ]
>     )
> ]
> """
> 
> prompt = ChatPromptTemplate.from_template(template)
> 
> try:
>     model = OllamaLLM(model="llama3.2-vision:11b", base_url="http://ollama:11434")
>     chain = prompt | model
>     response = chain.invoke(input={"question": question, "image": image})
>     print(response)
> 
> except Exception as e:
>     print("Failed to connect to the Ollama model:", e)
> ```
> 
> Output:
> 
> `I don't see an image. This is a text-based conversation and I'm not capable of visually seeing images. If you'd like to describe the image or provide more context, I'd be happy to try and help! `
> 
> But this is not working (when using models like gpt4-o it works fine).
> 
> The only way was using the native ollama python library like this:
> 
> ```python
> from ollama import Client
> 
> client = Client(host="http://ollama:11434")
> 
> response = client.chat(
>     model="llama3.2-vision:11b",
>     messages=[
>         {
>             "role": "user",
>             "content": "What is in this image?",
>             "images": ["/workspaces/imageanalyzer/tests/test_assets/chicoree.jpeg"],
>         }
>     ],
> )
> 
> print(response)
> ```
> 
> Output:
> 
> `{'model': 'llama3.2-vision:11b', 'created_at': '2024-11-11T08:43:42.584246665Z', 'message': {'role': 'assistant', 'content': 'The image features two endive leaves, commonly known as Belgian endive. This type of endive is distinguished from its cousin, the chicory, by not having a bitter flavor and being much more mild. Endives are often used in salads or served with a variety of sauces for added flavor.'}, 'done_reason': 'stop', 'done': True, 'total_duration': 4841011927, 'load_duration': 21252190, 'prompt_eval_count': 18, 'prompt_eval_duration': 2417000000, 'eval_count': 61, 'eval_duration': 2023000000}`

The llama3.2-vision doesn't see the image neither with both methods for me.

**Comment by nlsferrara** [comment]
I follow this tuto and I have this error: 
```
PydanticSerializationError: Error calling function `serialize_model`: OSError: [Errno 36] File name too long
```
I don't know if it's working for one of you. I use llama3.2-vision.

**Comment by ahmedkooli** [comment]
Thanks for all the work guys, I'm closing the issue :)
