### ISSUE TITLE
Chat prompt for Anthropic

### ISSUE THREAD

**Issue by p-christ** [langchain-ai/langchain#2752]
Hey,

Does the way of prompting Open AI Chat with SystemMessage, HumanMessage and AIMessage work for Anthropic models aswell?

Or must Anthropic models be prompted in the non-chat way?

thanks

**Comment by Xmaster6y** [comment]
As stated in the [documentation](https://console.anthropic.com/docs/api), you should try making the prompt as a chat. As it's not strongly enforced, you can still use it with raw prompting.

**Comment by supreetkt** [comment]
@Xmaster6y - it would be helpful to point out where in the documentation it says so..

**Comment by Xmaster6y** [comment]
@supreetkt - Not sure what you're asking since I already pointed to the documentation. Here is another link to the [API reference](https://docs.anthropic.com/claude/reference/getting-started-with-the-api).

**Comment by danny-avila** [comment]
@supreetkt did you ever get an answer on how the best technique for "prompting" a system Message, or how it works when using anthropic with langchain? I may circle back by looking at the chain output with a system message

**Comment by supreetkt** [comment]
@danny-avila: I ended up doing was using the [ChatAnthropic model](https://python.langchain.com/docs/modules/model_io/models/chat/integrations/anthropic), which supported my use-case.

**Comment by supreetkt** [comment]
@Xmaster6y: its useful to point where in the documentation you are implying certain things. Your first link pointed to the generic documentation. " you should try making the prompt as a chat" - your second link is more helpful. 
Also, Langchain has ChatAnthropic models, so that would fulfill this cause and we don't need to send prompts as chat.
