### ISSUE TITLE
[Q] Does langchain implement any prompt+response token calculation to prevent hitting max limit

### ISSUE THREAD

**Issue by mahmoudajawad** [langchain-ai/langchain#2753]
When I'm using `RetrievalQA` with `OpenAI` and `QDrant`, I sometimes hit the limit of OpenAI `gpt-3.5-turbo` of 4097 token limit. Is this expected behaviour, or does `langchain` implement a tokens calculator that prevents such events?

For the record, I'm hitting this problem with Arabic text, and so far didn't with English, though I don't know if this is correlated or not.

I want to add that in another project I'm working on I have a 100% working token calculator that didn't fail for me in all of my tests (with the focus group working on the project) so far. The way my calculator work is by limiting the initial prompt to max tokens count, then instruct `openai` SDK to set limit of response to some pre-defined limit (good for three sentences approx.) or the difference between initial prompt tokens count and model tokens limit, whichever is lower.

If this is needed in `langchain` I'm more than happy to re-implement it for this project with little guidance on where is the best part of the codebase to add this in.

**Comment by petmar2017** [comment]
same here
