### ISSUE TITLE
KeyError: '1; 2; 3; 4; 5; 6; 8; 10'

### ISSUE THREAD

**Issue by Nduy2k** [langchain-ai/langchain#2757]
When i use FewShotPromptTemplate function, if the examples contain "{" and "}" characters, I get this error.
Like this: {"question": "A = {1; 2; 3; 4; 5; 6; 8; 10}; B = {1; 3; 5; 7; 9; 11}"}
How can i fix it. Thank you!!!

**Comment by ladlestein** [comment]
You can escape the braces - use "{{" and "}}".
