### ISSUE TITLE
Calculate Embedding Cost

### ISSUE THREAD

**Issue by dheerajiiitv** [langchain-ai/langchain#2762]
Hey, with `openai_callback`. I am able to calculate cost to generate text, but this does not work while calculating embedding cost.

**Comment by ggcaponetto** [comment]
I am looking for the same functionality.

As a temporary workaround I am doing the following at the moment.

```js
function getRoughEmbeddingCost(text){
    // based on https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
    const charsPerPage = 1800;
    let pages = text.length / charsPerPage;
    let dollarCost = pages/3000;
    return dollarCost;
}
```

**Comment by kessl** [comment]
You can count tokens using a tokenizer: https://platform.openai.com/docs/guides/embeddings/how-can-i-tell-how-many-tokens-a-string-has-before-i-embed-it

`gpt-3-encoder` produced reliable results for me for models using `cl100k_base` encoding

```typescript
import { encode } from 'gpt-3-encoder'

export function countTokens(input: string) {
  const encoded = encode(input)
  return encoded.length
}
```
