### ISSUE TITLE
Deployments names on Azure need to match model names 

### ISSUE THREAD

**Issue by adrianomartinelli** [langchain-ai/langchain#2764]
# Problem
As far as I know, it is not possible to use certain classes like `OpenAIEmbeddings` with deployment names that are not exactly the same as the original model name. In the case of `OpenAIEmbeddings` the `document_model_name` is used to [retrieve the tokenizer from tiktoken](https://github.com/hwchase17/langchain/blob/b92a89e29f85d6b90796c24cdd952be76fb64a23/langchain/embeddings/openai.py#L206) and thus fails if the deployment name is not the same as the original model name.

# Proposal
I propose to introduce a new attribute `deployment_name` and use this along with the `model` attribute to retrieve the model deployment and encoding independently.

**Comment by Buckler89** [comment]
The same problem just happened to me. @adrianomartinelli's proposal sounds good.
