### ISSUE TITLE
Model using internal knowledge to answer the question when it is not supposed to in GraphSparqlQAChain

### ISSUE THREAD

**Issue by nadgeri14** [langchain-ai/langchain#27669]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

when i try to use the following code to answer the question: Where was barak obama born?
```
graph = RdfGraph(
    source_file="https://dbpedia.org/data/Barack_Obama.ttl",
    standard="rdf",
    local_copy="test.ttl",
)

graph.load_schema()

graph.get_schema

import os

if "OPENAI_API_KEY" not in os.environ:
    os.environ["OPENAI_API_KEY"] = ''

chain = GraphSparqlQAChain.from_llm(
    ChatOpenAI(temperature=0), graph=graph, verbose=True, allow_dangerous_requests=True
)
instruction = "ADDITIONAL INSTRUCTION: When you make the final query, remove these ``` quotes and only have the query \n"
query = "QUERY: Where was barak obama born?"
prompt = instruction + query
print(chain.run(prompt))
```

### Description

This is the SPARQL Query generated 
```
PREFIX dbp: <http://dbpedia.org/ontology/>
SELECT ?birthPlace
WHERE {
    dbp:Barack_Obama dbp:birthPlace ?birthPlace .
}```
Query execution answer: []

Final answer from **print(chain.run(prompt))** : **Barack Obama was born in Honolulu, Hawaii.**

I assume this is because of the [qa prompt](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chains/graph_qa/prompts.py#L192)

My suggestion would be to add one line  especially after:  Question: {prompt} to only answer from the available information as it would further reinforce the instructions. 

### System Info

I first noted the problem on google collab, but i faced the same problem while testing it on my local machine.

**Comment by Googlogogo** [comment]
Hi, we are a group of 4 students from University of Toronto, could we take a look at this issue? Thanks!

**Comment by nadgeri14** [comment]
Hi, thanks for the help, I already have a solution. I am waiting for the bug to be assigned to me so that i can create a pull request.

**Comment by Googlogogo** [comment]
Hi Abhishek,

Thank you for telling me that! In this case, good luck moving forward!

Best,
Gogo
