### ISSUE TITLE
DOC: `How to split text by tokens` guide links to wrong `TokenTextSplitter` page

### ISSUE THREAD

**Issue by inclinedadarsh** [langchain-ai/langchain#27748]
### URL

https://python.langchain.com/docs/how_to/split_by_token/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

In the start of the documentation, the line (just above the first codeblock) specifies:
> [CharacterTextSplitter](https://python.langchain.com/api_reference/text_splitters/character/langchain_text_splitters.character.CharacterTextSplitter.html), [RecursiveCharacterTextSplitter](https://python.langchain.com/api_reference/text_splitters/character/langchain_text_splitters.character.RecursiveCharacterTextSplitter.html), and [TokenTextSplitter](https://python.langchain.com/api_reference/langchain_text_splitters/base/langchain_text_splitters.base.TokenTextSplitter.html) can be used with tiktoken directly.

The `TextTokenSplitter` links to the wrong the page (non-existent)

The correct redirect should be to this page: https://python.langchain.com/api_reference/text_splitters/base/langchain_text_splitters.base.TokenTextSplitter.html

**Comment by DangerousPotential** [comment]
Proposed changes in #27824

**Comment by inclinedadarsh** [comment]
This issue has been fixed and merged in #27824.
