### ISSUE TITLE
Does langchain support Huggingface models for chat task ? 

### ISSUE THREAD

**Issue by complete-dope** [langchain-ai/langchain#2777]
If not, if you know some other similar open source project please recommend !!

**Comment by Ganryuu** [comment]
Yes, LangChain Does support HF models 

Patrick Loeber has a great introductory video about how to use both OpenAI models and HF models: 
Link for the video : https://www.youtube.com/watch?v=LbT1yp6quS8&t=314s 
and this is a Link for the notebook done in the video, it has an example with HF models ( "google/flan-t5-xl" in this case ) : https://colab.research.google.com/drive/1VOwJpcZqOXag-ZXi-52ibOx6L5Pw-YJi?usp=sharing
