### ISSUE TITLE
Langchain Azure create_pandas_dataframe_agent Issue

### ISSUE THREAD

**Issue by CharlieEvert** [langchain-ai/langchain#2790]
Below is the code i'm using to explore a CSV on Pokemon. I'm trying to plug in Azure credentials to get it to work but i'm running into some issues. 

from langchain.agents import create_pandas_dataframe_agent
from langchain.llms import OpenAI
import pandas as pd
import os

os.environ["OPENAI_API_KEY"] = 'sk-xxx' 

df = pd.read_csv('pokemon.csv')

agent = create_pandas_dataframe_agent(OpenAI(temperature=0), df, verbose=True)

agent.run("What is the name of the gen 5 pokemon has the highest speed?")

Here is what I've been trying to do to get Azure OpenAI to work with this: 
 os.environ["OPENAI_API_TYPE"] = "azure"
 os.environ["OPENAI_API_KEY"] = "xx"
 os.environ["OPENAI_API_BASE"] = "https://xx.openai.azure.com"
 os.environ["OPENAI_API_VERSION"] = "2022-12-01"

When I try to run the above, I get the error that the API key is incorrect. More specifically:
AuthenticationError: Incorrect API key provided: ****************************. You can find your API key at https://platform.openai.com/account/api-keys.

Has anyone dealt with this before?

**Comment by masta-g3** [comment]
Maybe try setting the environment variables before importing the langchain items, since the openai library automatically reads them upon initialization.
