### ISSUE TITLE
AIMessage enforces ToolCall model incompatible with OpenAI

### ISSUE THREAD

**Issue by yildirimgoks** [langchain-ai/langchain#27938]
### Checked other resources

- [X] I added a very descriptive title to this question.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python

from langchain.messages import AIMessage, ToolCall

# OpenAI compatible tool call format
tool_call = {
   "id":"tc1",
   "type":"function",
   "function":{
      "name":"SomeTool",
      "arguments":"{\"some_argument\": \"some_value\"}"
   }
}

# line below works fine
ToolCall(**tool_call)

# line below returns an error
AIMessage(content="", tool_calls=[ToolCall(**tool_call)])

# error message:
# pydantic.v1.error_wrappers.ValidationError: 1 validation error for AIMessage
# tool_call() got an unexpected keyword argument 'function' (type=type_error)
```

### Description

When you provide a value for the '_tool_calls_' argument of the _AIMessage_, _root_validator_ tries to parse the values in it to a _ToolCall_ object using the _langchain_core.messages.tool.tool_call_ function. Although instancing _ToolCall_ by calling it directly with OpenAI compatible tool_calls model is possible, the _tool_call_() function expects a specific set of variables to build the _ToolCall_, and does not accept extra keyword variables. This enforces a very specific data model when tool_calls is provided with _AIMessage_ and makes it impossible to create an AIMessage object with the desired _tool_calls_ formatting.

Is this intended or could this be a bug? IIs there a different way of creating an AI message with tool_calls that I'm missing? 

### System Info

langchain==0.2.14
langchain-community==0.2.12
langchain-core==0.2.33
langchain-openai==0.1.22
langchain-text-splitters==0.2.2

Checked the latest source code & documentation and the issue persists in the most recent version as well.

_Originally posted by @yildirimgoks in https://github.com/langchain-ai/langchain/discussions/27919_

**Comment by keenborder786** [comment]
@yildirimgoks, this is intentional. `ToolCall` is an internal way for representation of AI Tool Call Message. At the end Tool Calling API for OpenAI is invoked with the compatible schema. But if you want to achieve the desire result:
```python



from langchain_core.messages import AIMessage, ToolCall

tool_call = {
   "id":"tc1",
   "type":"function",
   "name":"some_function",
   "args":{"some_argument": "some_value"}
}

# line below works fine
ToolCall(**tool_call)

# line below returns an error
AIMessage(content="", tool_calls=[ToolCall(**tool_call)])


```

**Comment by yildirimgoks** [comment]
When I initially did it like your suggestion I had received a BadRequest error from OpenAI complaining the tool call format was wrong - which was what actually prompted me to look into the data model LangChain was enforcing and all that.

Today we had the opportunity to migrate the project to Langchain 0.3 and I can confirm your suggestion now works. I had looked into relevant parts of the codebase beforehand to check if 0.3 would make a difference and thought it wouldn't, must have overlooked something. 

Thanks for the guidance & I'll mark this as resolved.
