### ISSUE TITLE
GCSDirectoryLoader error: Unable to get page count. Is poppler installed and in PATH?

### ISSUE THREAD

**Issue by ejstembler** [langchain-ai/langchain#27999]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
text_splitter = RecursiveCharacterTextSplitter()

gcs_directory_loader = GCSDirectoryLoader(
    project_name='project_name',
    bucket='bucket_name',
    loader_func=None
)

documents = gcs_directory_loader.load_and_split(text_splitter=self.state.text_splitter)
```

### Error Message and Stack Trace (if applicable)

Unable to get page count. Is poppler installed and in PATH?

### Description

* This pytest unit test is running on macOS 14.7.1 (23H222)

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_X86_64
> Python Version:  3.9.19 (main, May  1 2024, 22:24:35) 
[Clang 15.0.0 (clang-1500.3.9.4)]

Package Information
-------------------
> langchain_core: 0.2.41
> langchain: 0.2.9
> langchain_community: 0.2.10
> langsmith: 0.1.137
> langchain_google_cloud_sql_pg: 0.6.1
> langchain_google_community: 1.0.8
> langchain_google_vertexai: 1.0.6
> langchain_text_splitters: 0.2.4

Optional packages not installed
-------------------------------
> langgraph
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> anthropic[vertexai]: Installed. No version info available.
> async-timeout: 4.0.3
> beautifulsoup4: 4.12.3
> black[jupyter]: Installed. No version info available.
> cloud-sql-python-connector[asyncpg]: Installed. No version info available.
> dataclasses-json: 0.6.7
> db-dtypes: Installed. No version info available.
> gapic-google-longrunning: Installed. No version info available.
> google-api-core: 2.22.0
> google-api-python-client: 2.149.0
> google-auth-httplib2: 0.2.0
> google-auth-oauthlib: Installed. No version info available.
> google-cloud-aiplatform: 1.70.0
> google-cloud-bigquery: 3.26.0
> google-cloud-bigquery-storage: Installed. No version info available.
> google-cloud-contentwarehouse: Installed. No version info available.
> google-cloud-discoveryengine: Installed. No version info available.
> google-cloud-documentai: Installed. No version info available.
> google-cloud-documentai-toolbox: Installed. No version info available.
> google-cloud-speech: Installed. No version info available.
> google-cloud-storage: 2.18.2
> google-cloud-texttospeech: Installed. No version info available.
> google-cloud-translate: Installed. No version info available.
> google-cloud-vision: 3.8.0
> googlemaps: Installed. No version info available.
> grpcio: 1.67.1
> httpx: 0.27.2
> isort: 5.13.2
> jsonpatch: 1.33
> mypy: 1.10.1
> numpy: 1.26.4
> orjson: 3.10.10
> packaging: 24.1
> pandas: 2.2.3
> pgvector: 0.3.1
> pyarrow: Installed. No version info available.
> pydantic: 2.9.2
> pytest: 8.3.3
> pytest-asyncio: Installed. No version info available.
> pytest-cov: Installed. No version info available.
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> SQLAlchemy[asyncio]: Installed. No version info available.
> tenacity: 8.3.0
> typing-extensions: 4.12.2

**Comment by keenborder786** [comment]
Just install the following:

```
pip install python-poppler
```

**Comment by keenborder786** [comment]
Since the `loader_func` is None and langchain by default uses `UnstructuredFileLoader` to load your pdf which might be requiring the above dependency!!!

**Comment by cat-sun** [comment]
brew install poppler
