### ISSUE TITLE
Hugging Face Hub example is factually incorrect

### ISSUE THREAD

**Issue by JasonWeill** [langchain-ai/langchain#2802]
On the [Hugging Face Hub example page](https://github.com/hwchase17/langchain/blob/0e763677e4c334af80f2b542cb269f3786d8403f/docs/modules/models/llms/integrations/huggingface_hub.ipynb), the question is, "What NFL team won the Super Bowl in the year Justin Beiber *[sic]* was born?" The answer is, "The Seattle Seahawks won the Super Bowl in 2010. Justin Beiber was born in 2010. The final answer: Seattle Seahawks."

This is factually incorrect; Justin **Bieber** was born in 1994, and in that year, the Dallas Cowboys won Super Bowl XXVIII. 

In addition, the Indianapolis Colts won Super Bowl XLIV in 2010; the Seahawks did not win their first Super Bowl until 2014.

**Comment by cnhhoang850** [comment]
This was also the resulst I got from running the example: "The Seattle Seahawks won the Super Bowl in 2010. Justin Beiber was born in 2010. The final answer: Seattle Seahawks."

**Comment by azamiftikhar1000** [comment]
https://github.com/hwchase17/langchain/pull/2810
It appears that Google's Flan model may not perform as well as other models, I have used a simple example to get  factually correct answer.

**Comment by Majboor** [comment]
I have used MPT-7 and it tells me the same
` In 2014, The Seattle Seahawks defeated the Denver Broncos at MetLife Stadium`

**Comment by vowelparrot** [comment]
Yeah the Huggingface model isn't as reliable!

**Comment by Majboor** [comment]
are there any other open source models, I have tried all of the ones on gpt4all many commercial on hugging face none are as good as compared to text davinchi or gpt-3

**Comment by vowelparrot** [comment]
You could try the falcon ones on huggingface. It really depends on your use case.

While some models are fine for certain tasks, in general, we haven't seen a serious open source competitor yet over all possible use cases. OpenAI's raison d'etre is to make models that are better than other providers and has a head start.

**Comment by Majboor** [comment]
I was having fun trying them out I was going to fine-tune some but now that
loangchain Is there it is not quite a problem, I have played around with
many models and I find that the best one is MPT-7 it is the best one for me
according to my testing.(my testing means simply checking if the model can
generate a tweet)
