### ISSUE TITLE
Get the conversation logs in ConversationalRetrievalChain

### ISSUE THREAD

**Issue by CreationLee** [langchain-ai/langchain#2813]
How to get the conversation logs in ConversationalRetrievalChain

such as the condensed standalone question

**Comment by anh** [comment]
Suppose you are trying out https://github.com/hwchase17/chat-langchain 

* Run your langchain-server locally its api port will be 8000, its default ui is http://localhost:4173/
* Enable tracing=true in get_chain() in main.py 
* Start service like this 

```bash
$ LANGCHAIN_HANDLER=langchain LANGCHAIN_ENDPOINT=http://localhost:8000  uvicorn main:app --port 9000 --reload
```
* Do some chats at http://localhost:9000
* Look up tracing (explore) at http://localhost:4173, there will be some child runs that contains standalone question 

You can read more about tracing here: https://python.langchain.com/en/latest/tracing.html

HTH,

**Comment by CreationLee** [comment]
> Suppose you are trying out https://github.com/hwchase17/chat-langchain
> 
> * Run your langchain-server locally its api port will be 8000, its default ui is http://localhost:4173/
> * Enable tracing=true in get_chain() in main.py
> * Start service like this
> 
> ```shell
> $ LANGCHAIN_HANDLER=langchain LANGCHAIN_ENDPOINT=http://localhost:8000  uvicorn main:app --port 9000 --reload
> ```
> 
> * Do some chats at http://localhost:9000
> * Look up tracing (explore) at http://localhost:4173, there will be some child runs that contain standalone question
> 
> You can read more about tracing here: https://python.langchain.com/en/latest/tracing.html
> 
> HTH,

TKS!

I need to record some inputs and outputs to our own log system, so is three any way to get the inputs and outputs during the  ConversationalRetrievalChain,  especially, the condensed question from chat history, i have tried lots of ways, but they all didn't work for me, what i tried:

- call back manager, didn't work with the AzureChatOpenAI

**Comment by alex-stellar** [comment]
I'm sorry, but tracing the network doesn't seem to be the proper way of logging in this case
