### ISSUE TITLE
Having token limit issue while using sql agents when the data returned by the agent query on the database is too large

### ISSUE THREAD

**Issue by imanuj07** [langchain-ai/langchain#2817]

**Comment by imanuj07** [comment]
Attaching code image for reference.

**Comment by imanuj07** [comment]
<img width="1512" alt="Screenshot 2023-04-14 at 11 25 53 AM" src="https://user-images.githubusercontent.com/19492361/231954200-f81059a0-0020-4a7e-9c55-541559e6fe33.png">
<img width="1512" alt="Screenshot 2023-04-14 at 11 26 11 AM" src="https://user-images.githubusercontent.com/19492361/231954215-137dccb0-0bf2-40ec-95fc-a3dbd3208754.png">

Attaching image for referrence

**Comment by Rsdv13** [comment]
I am getting the same issue. Any help would be appreciated.
