### ISSUE TITLE
`v.0.0.138` does not create a `Pinecone` index when initiating a vectorstore. 

### ISSUE THREAD

**Issue by homanp** [langchain-ai/langchain#2822]
In previous versions of LC running the following code would create an index in Pinecone:

```
loader = TextLoader(join('data', 'ad.txt'))
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

pinecone.init(
    api_key="cc7f8b80-2cc9-4d72-8c0d-0e2d287977d5", 
    environment="asia-southeast1-gcp"
)

index_name = "langchain-demo"
vectorstore = Pinecone.from_documents(docs, embeddings, index_name=index_name)
```

This would create an index in `v.0.0.123`, instead I'm seeing this error:

`ValueError: No active indexes found in your Pinecone project, are you sure you're using the right API key and environment?`

Are there any breaking changes to this implementation we should be aware of?

**Comment by nepalprabin** [comment]
As far as I know, you need to create index, either from pinecone dashboard or using code 
```python 
pinecone.create_index(index_name, dimension=1536,
                          metric="cosine", pods=1, pod_type="p1.x1")
```
Let me know if this works.

**Comment by natasha-savic-msft** [comment]
@nepalprabin provided the answer. Created the index in the UI and it worked.
