### ISSUE TITLE
`Marqo.add_texts()` throws exception when using Marqo >= v2.0.0

### ISSUE THREAD

**Issue by tad1** [langchain-ai/langchain#28323]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

run container:
```sh
docker pull marqoai/marqo:2.13 # or latest
docker rm -f marqo
docker run --name marqo -it -p 8882:8882 marqoai/marqo:2.13
```

run script:
```python
from langchain_community.vectorstores import Marqo
from langchain_core.documents import Document
import marqo

marqo_url = "http://localhost:8882"
marqo_api_key = ""
client = marqo.Client(url=marqo_url, api_key=marqo_api_key)

index_name = "langchain-demo"
docsearch = Marqo.from_texts(["test"], index_name=index_name)
result = docsearch.similarity_search("test")
print(result)
```

### Error Message and Stack Trace (if applicable)

```
Index langchain-demo exists.
Traceback (most recent call last):
  File "./src.py", line 13, in <module>
    docsearch = Marqo.from_documents(docs, index_name=index_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./pyenv/lib/python3.12/site-packages/langchain_community/vectorstores/marqo.py", line 364, in from_documents
    return cls.from_texts(texts, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./pyenv/lib/python3.12/site-packages/langchain_community/vectorstores/marqo.py", line 452, in from_texts
    instance.add_texts(texts, metadatas)
  File "./pyenv/lib/python3.12/site-packages/langchain_community/vectorstores/marqo.py", line 112, in add_texts
    if self._client.index(self._index_name).get_settings()["index_defaults"][
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'index_defaults'
```

### Description

I'm following an example from: https://python.langchain.com/docs/integrations/vectorstores/marqo/.  Trying to create a vectorstore with some data on Marqo docker instance.

**Expected behavior:**
vector store gets created, with populated data

**Actual behavior:**
LangChain creates index and throws an exception in `add_texts()` (without populating data)

**Reason:**
since Marqo 2.0 `index_defaults` is removed from index settings and `settings.index_defaults.treat_urls_and_pointers_as_images` should be referred in new version as `settings.treatUrlsAndPointersAsImages` (see https://docs.marqo.ai/latest/reference/api/indexes/create-index/#body-parameters and breaking changes in https://github.com/marqo-ai/marqo/blob/mainline/RELEASE.md#release-200)

### System Info

Marqo image version: 2.13.2

`python -m langchain_core.sys_info`
```
System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP PREEMPT_DYNAMIC Tue Oct  8 03:24:49 UTC 2024
> Python Version:  3.12.6 (main, Sep  8 2024, 13:18:56) [GCC 14.2.1 20240805]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.8
> langchain_community: 0.3.8
> langsmith: 0.1.145
> langchain_text_splitters: 0.3.2

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.7
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> numpy: 1.26.4
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.10.1
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.35
> tenacity: 9.0.0
> typing-extensions: 4.12.2
```

**Comment by keenborder786** [comment]
@tad1 `get_setting` was still accounting for v1.5.x API but in the above PR accounted for later 2.x versions
