### ISSUE TITLE
MarkdownTextSplitter removes formatting and line breaks

### ISSUE THREAD

**Issue by vbelius** [langchain-ai/langchain#2836]
I was trying to use MarkdownTextSplitter to translate a document and maintain formatting, but I noticed that the splitter removed formatting from the markdown when splitting it.

As an example, the following markdown example when split with chunk_size=200 removes the "## " from the features line, as well as the line breaks preceding and following that line.

```markdown
# Dillinger

- Type some Markdown on the left
- See HTML in the right
- ✨Magic ✨

## Features

- Import a HTML file and watch it magically convert to Markdown
- Drag and drop images (requires your Dropbox account be linked)
- Import and save files from GitHub, Dropbox, Google Drive and One Drive
--
```
When split using this code:
```python
markdown_splitter = MarkdownTextSplitter(chunk_size=200, chunk_overlap=0)
docs = markdown_splitter.create_documents([markdown_document])

for doc in docs:
    print(doc.page_content)
````

The output becomes:

```markdown
# Dillinger

- Type some Markdown on the left
- See HTML in the right
- ✨Magic ✨
Features
- Import a HTML file and watch it magically convert to Markdown
- Drag and drop images (requires your Dropbox account be linked)
- Import and save files from GitHub, Dropbox, Google Drive and One Drive
--
```

The formatting and line breaks around the "Features" line are removed. Expected behavior would be that each split doc, when combined, would be the original text.

Solution would be to never have formatting and line breaks removed, or, add the removed prefix/suffix  in metadata or other keys so they could be used to re-construct the document with intact formatting.

[Full code example](https://gist.github.com/vbelius/993e3031dc825aa7a9c7b38af54de4d2)

```bash
~: pip show langchain
Name: langchain
Version: 0.0.138
```

**Comment by kroggen** [comment]
It is even worst for the [PythonCodeTextSplitter](https://github.com/hwchase17/langchain/blob/16099505972e9f34e751b6ffbed5b7837a87e515/langchain/text_splitter.py#L389). The `class` and `def` keywords are removed:

```python
class PythonCodeTextSplitter(RecursiveCharacterTextSplitter):
    """Attempts to split the text along Python syntax."""

    def __init__(self, **kwargs: Any):
        """Initialize a MarkdownTextSplitter."""
        separators = [
            # First, try to split along class definitions
            "\nclass ",
            "\ndef ",
            "\n\tdef ",
            # Now split by the normal type of lines
            "\n\n",
            "\n",
            " ",
            "",
        ]
        super().__init__(separators=separators, **kwargs)
```

**Comment by vbelius** [comment]
Wouldn't mind giving fixing this a try but would like to have some feedback/go-ahead from a maintainer for my solution proposal first!

Thinking split_text could be refractored to return the separator used as well, and this could be stored in the list of documents returned (should maybe be a custom class SplitDocument? with key separator/prefix).

**Comment by kroggen** [comment]
In my opinion each separator should contain the position to be re-added

It can be using:

* a list
* a dictionary
* an additional character at the beginning of the separator string

## List

```python
  separators = [
      ["\n## ", START],
      ["\n```", START],
      ["\n\n", END],
      [".", END],
      ["\n", END],
      [" ", END],
      ["", nil],
  ]
```

## Dict

```python
  separators = {
      "\n## ": START,
      "\n```": START,
      "\n\n": END,
      ".": END,
      "\n": END,
      " ": END,
      "": END,
  }
```

## First Character

* `S` = Start || `B` = Before
* `E` = End || `A` = After
* `X` = Exclude || `O` = Omit

```python
  separators = [
      "S\n## ",
      "S\n```",
      "E\n\n",
      "E.",
      "E\n",
      "E ",
      "",
  ]
```

**Comment by vbelius** [comment]
Not sure I understand.. So in your opinion the separators should be returned separately from the docs? A bit strange..

**Comment by kroggen** [comment]
No, the above would be in the configuration of separators for the MarkdownTextSplitter

Check [here](https://github.com/hwchase17/langchain/blob/16099505972e9f34e751b6ffbed5b7837a87e515/langchain/text_splitter.py#L327-L355)

Then the [RecursiveCharacterTextSplitter](https://github.com/hwchase17/langchain/blob/16099505972e9f34e751b6ffbed5b7837a87e515/langchain/text_splitter.py#L234) should deal with the new format for the separators list

**Comment by kroggen** [comment]
If the solution should be backwards compatible, then only the option with the list above would fit

The separators list could contain both strings and lists of string and a constant

In this example we have both:

```python
  separators = [
      ["\n## ", START],
      ["\n### ", START],
      ["\n```", START],
      "\n\n",
      [".", END],
      "\n",
      " ",
      ""
  ]
```

So the code must identify the type of each element and act accordingly

**Comment by kroggen** [comment]
In the case of markdown, code blocks should be returned with the "```" both at the start and at the end

So maybe we will need another constant (`BOTH`) to deal with it

**Comment by hwchase17** [comment]
definitely in favor of this

would be great to add a bunch of test cases for this when doing

**Comment by ifsheldon** [comment]
+1. Besides, would be great to have something like splitting by headings only mode, which only splits by headings, not by code blocks etc. This will be very helpful to build an assistant that looks up code documentation.

**Comment by tcapelle** [comment]
I am also interested on a fix for this. I am using LangChain to translate md files, and right now it's not possible due to this.

**Comment by kroggen** [comment]
It is not easy do deal with Markdown.

Code should be split by functions or code blocks or at least entire lines. In python the function decorators and comments should be together with the functions. And other languages have their own peculiarities. Code blocks should be properly split for the model to be able to understand the code.

Tables should be split keeping entire rows of content.

Similar applies to Jupiter notebooks.

It would be better to have a model to do this job, either a general purpose model (using proper prompt) or one trained/fine-tuned specifically for this task

**Comment by tcapelle** [comment]
I actually just want the same behavior from the `MarkdownTextSplitter`, but putting back the separators. My test is that if I create a identity chain:
```python
class IdentityChain:
    def __init__(self): pass
    def run(self, text=None, **kwargs): return text
```
and I stack the documents back I should get the "almost" same input.

**Comment by fylls** [comment]
What is the best and safest way to split markdown? Is this the best implementation online?

**Comment by pseudotensor** [comment]
@kroggen I'm confused by this issue.  This has nothing to do  with markdown, it seems like `keep_separator` is never respected for any case.

**Comment by cktang88** [comment]
@pseudotensor yep universal for all recursive text splitters i think

**Comment by Kefan-pauline** [comment]
I am also interested in a solution to this issue. 
I would like to split markdown recursively and then correctly render the markdown chunks (so the formatting needs to be maintained).

**Comment by hanhcode** [comment]
Hello, what is the current solution to this problem?

**Comment by hanhcode** [comment]
Hello, what is the current solution to this problem?
