### ISSUE TITLE
Deprecated argument(s) removed when using `httpx==0.28.0`

### ISSUE THREAD

**Issue by riccardogabellone** [langchain-ai/langchain#28406]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [ ] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_openai import ChatOpenAI

chat_oai = ChatOpenAI()
```

### Description

As for today, new `SyncAPIClient` class instances throw the exception:

`TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`

As stated [here](https://github.com/encode/httpx/releases/tag/0.28.0), some deprecated args, like `proxies`, has been removed.

So, a temporary override of `httpx<0.28.0` in project dependencies will work as expected.

### System Info

System Information
------------------
> OS:  Linux
> OS Version:  #1 SMP Tue Jan 16 18:29:00 UTC 2024
> Python Version:  3.11.2 (main, Mar 23 2023, 02:57:04) [GCC 10.2.1 20210110]

Package Information
-------------------
> langchain_core: 0.3.21
> langchain: 0.3.9
> langchain_community: 0.3.4
> langsmith: 0.1.147
> langchain_openai: 0.2.10
> langchain_text_splitters: 0.3.2

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.11.8
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.28.0
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.55.3
> orjson: 3.10.12
> packaging: 24.2
> pydantic: 2.10.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 9.0.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by hibana2077** [comment]
I also encounter same problem.

And I found this code section on path : libs/partners/groq/langchain_groq/chat_models.py
![image](https://github.com/user-attachments/assets/58d49d54-cc4e-4264-b29a-84b1b03477e1)
It's clear that langchain_groq doesn't pass any arugment call proxies.

Therefore, I take a look into groq python library : _base_client.py
![image](https://github.com/user-attachments/assets/d80d9b0d-9245-4d79-ac81-0e7e9aedf0d4)
In this section it passed proxies parameter to httpx.client

![image](https://github.com/user-attachments/assets/8d13caae-afdb-4182-8e1f-cf525e5921fa)
But since 28th November, 2024 new release of httpx package (0.28.0) that "proxies"  has been removed.

So If you change to previous version of httpx, this bug should be resolved.

**Comment by ccurme** [comment]
@riccardogabellone would you mind sharing a full stack trace to help identify the problem?

From what I can tell `ChatOpenAI` specifies `proxy` (not `proxies`) when creating the httpx client: https://github.com/langchain-ai/langchain/blob/2813e8640703b8066d8dd6c739829bb4f4aa634e/libs/partners/openai/langchain_openai/chat_models/base.py#L549

**Comment by artpods56** [comment]
downgrading to httpx==0.27.0 fixed the problem for me

**Comment by riccardogabellone** [comment]
> @riccardogabellone would you mind sharing a full stack trace to help identify the problem?
> 
> From what I can tell `ChatOpenAI` specifies `proxy` (not `proxies`) when creating the httpx client:
> 
> https://github.com/langchain-ai/langchain/blob/2813e8640703b8066d8dd6c739829bb4f4aa634e/libs/partners/openai/langchain_openai/chat_models/base.py#L549

After depth investigating stack trace I found out issue was indeed the OpenAI lib, but a [new recent version](https://github.com/openai/openai-python/releases/tag/v1.55.3) fixed that, so, no need for manual downgrade anything. All last versions work normally, at least, for my use case.
