### ISSUE TITLE
ollama: support streaming tool calls

### ISSUE THREAD

**Issue by ccurme** [langchain-ai/langchain#28543]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Ollama now supports streaming tool calls, we should update `langchain-ollama` to support as well

https://github.com/ollama/ollama/releases/tag/v0.4.6

**Comment by keenborder786** [comment]
@ccurme I am working on this

**Comment by keenborder786** [comment]
@ccurme Isn't this already implemented if you see the [following](https://github.com/langchain-ai/langchain/blob/18386c16c7201e54dfaacbc18eed51da7965a7a5/libs/partners/ollama/langchain_ollama/chat_models.py#L724). The tool call is being returned in streaming response. I also tested it with the following on Ollama 0.4.7:

```python
from langchain_ollama.chat_models import ChatOllama
from langchain_openai.chat_models import ChatOpenAI
from pydantic import BaseModel
class AdditionTool(BaseModel):
    int_1:int
    int_2:int

llm = ChatOllama(model="llama3.1")
llm = llm.bind_tools(tools = [AdditionTool])
result = llm.stream("Add the two numbers: 1,2")

for r in result:
    print(r)

```

And it returned me the following response:


```
content='' additional_kwargs={} response_metadata={'model': 'llama3.1', 'created_at': '2024-12-06T01:08:45.445958544Z', 'message': {'role': 'assistant', 'content': '', 'tool_calls': [{'function': {'name': 'AdditionTool', 'arguments': {'int_1': '1', 'int_2': '2'}}}]}, 'done_reason': 'stop', 'done': True, 'total_duration': 116583623721, 'load_duration': 64097729072, 'prompt_eval_count': 176, 'prompt_eval_duration': 26549000000, 'eval_count': 28, 'eval_duration': 25890000000} id='run-abd152a9-2d2f-47bf-92dd-08a560e9fc0a' tool_calls=[{'name': 'AdditionTool', 'args': {'int_1': 1, 'int_2': 2}, 'id': 'f6051a75-9315-45d1-abe8-62d04b786931', 'type': 'tool_call'}] usage_metadata={'input_tokens': 176, 'output_tokens': 28, 'total_tokens': 204} tool_call_chunks=[{'name': 'AdditionTool', 'args': '{"int_1": 1, "int_2": 2}', 'id': 'f6051a75-9315-45d1-abe8-62d04b786931', 'index': None, 'type': 'tool_call_chunk'}]

```

**Comment by ccurme** [comment]
@keenborder786 current behavior is to override the `stream` parameter if tools are included. Updating this in https://github.com/langchain-ai/langchain/pull/28654.
