### ISSUE TITLE
Validation Error: __init__() got an unexpected keyword argument 'proxies' in OpenAIEmbeddings

### ISSUE THREAD

**Issue by HernanOsorio** [langchain-ai/langchain#28560]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

from langchain_openai import OpenAIEmbeddings

try:
    embeddings = OpenAIEmbeddings(openai_api_key="sk-...")
    print("Embeddings initialized successfully!")
except Exception as e:
    print("Error initializing OpenAIEmbeddings:", e)

### Error Message and Stack Trace (if applicable)

Error initializing OpenAIEmbeddings: 1 validation error for OpenAIEmbeddings
__root__
  __init__() got an unexpected keyword argument 'proxies' (type=type_error)

### Description

I encountered a ValidationError when initializing OpenAIEmbeddings from the langchain-openai package. The error indicates that an unexpected keyword argument proxies is being passed during initialization, even though I am not explicitly providing it.

### System Info

Provide details about your environment:

OS: Windows 10 64-bit
Python Version: 3.9.0
LangChain Version: 0.2.2
LangChain-OpenAI Version: 0.1.8
OpenAI Version: 1.31.1
Pydantic Version: 1.10.12

**Comment by ccurme** [comment]
Last week `httpx` [removed a deprecated proxies argument](https://github.com/encode/httpx/releases/tag/0.28.0).

The `openai` SDK then released [1.56.1](https://github.com/openai/openai-python/releases/tag/v1.56.1) to remove the use of `proxies`.

You will need to either update your OpenAI SDK to the latest version or install `httpx==0.27`.

Let me know if this does not resolve your issue.

**Comment by UtkuBulkan** [comment]
No it does not solve the issue.
