### ISSUE TITLE
Loading Multiple PDF error

### ISSUE THREAD

**Issue by Kashif-Raza6** [langchain-ai/langchain#2860]
I am using Directory Loader to load my all the pdf in my data folder.
`
from langchain.document_loaders import DirectoryLoader
`
`
loader = DirectoryLoader("data", glob = "**/*.pdf")
`
`
documents = loader.load()
`
`
print(documents)
`
This throw error while when I load txt files this is working fine.

**Comment by digitake** [comment]
What's the error?

**Comment by Kashif-Raza6** [comment]
Error:
ImportError: `cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.9/dist-packages/PIL/_util.py)`

**Comment by digitake** [comment]
Try restart runtime after install the `Pillow` package. Let me know if that helps.

**Comment by Kashif-Raza6** [comment]
I have restarted the run time as well as installed the `pillow` package again, but this even did not solve the problem.

**Comment by digitake** [comment]
It seems like a classic case _it's work on my machine_.

I have tried your code and it works fine.

![Uploading image.png…]()

I'd suggest you to check your `Langchain` and `Pillow` version. You can fresh install in your new virtualenv.

**Comment by Kashif-Raza6** [comment]
Did you try with multiple PDF files in the directory?
For a single PDF file it's working on my end as well, but with multiple PDFs it's creating the error.

**Comment by digitake** [comment]
Yes. I have three files.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/3163988/232045834-88c0c3ea-c6f5-4e2f-9668-d4e15343fbee.png">

**Comment by Kashif-Raza6** [comment]
When I install the `chromadb` in virtual env am getting following error:

`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/`

how can I resolve it?

**Comment by nhtkid** [comment]
I had this problem yesterday. It's the Pillow version mismatch. 
Try a different version which worked for me.
`# !pip uninstall Pillow
# !pip install Pillow==9.1.0`

**Comment by grv805** [comment]
I'm getting below error:-
PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

**Comment by grv805** [comment]
I'm running it on GCP Vertex AI Workbench. How to overcome it?

**Comment by sistecno** [comment]
> Cuando instalo `chromadb`en virtual env obtengo el siguiente error:
> 
> `error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/` Incluso he instalado Microdoft C++ Build Tools en mi sistema.
> 
> ¿Cómo puedo resolverlo?
Try this solution, it worked for me.
https://stackoverflow.com/questions/73969269/error-could-not-build-wheels-for-hnswlib-which-is-required-to-install-pyprojec
