### ISSUE TITLE
langchain_ollama: ChatOllama default value of `format` causes error

### ISSUE THREAD

**Issue by LogCreative** [langchain-ai/langchain#28607]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="qwen2.5:72b-instruct",
    base_url="http://127.0.0.1:11434",
    temperature=0,
    num_ctx=32000,  # increased max characters, otherwise system prompts will be ignored
    num_predict=2048,
)

result = llm.invoke("hello")
print(result.content)
```

### Error Message and Stack Trace (if applicable)

```
Traceback (most recent call last):
  File "ollama-bug.py", line 11, in <module>
    result = llm.invoke("hello")
             ^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 643, in generate
    raise e
  File "lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 691, in _generate
    final_chunk = self._chat_stream_with_aggregation(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 592, in _chat_stream_with_aggregation
    for stream_resp in self._create_chat_stream(messages, stop, **kwargs):
  File "lib/python3.11/site-packages/langchain_ollama/chat_models.py", line 579, in _create_chat_stream
    yield from self._client.chat(**chat_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/ollama/_client.py", line 336, in chat
    json=ChatRequest(
         ^^^^^^^^^^^^
  File "lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ChatRequest
format.literal['json']
  Input should be 'json' [type=literal_error, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
format.dict[str,any]
  Input should be a valid dictionary [type=dict_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/dict_type
```

### Description

I used the default value of `format` for `ChatOllama` from the newest `langchain_ollama`, I found that the default value "" defined below

https://github.com/langchain-ai/langchain/blob/dd0085a9ff3ced8dcf904369ad394eb71d726ac0/libs/partners/ollama/langchain_ollama/chat_models.py#L388

will cause the error above.

If I use the `format="json"` option, it could work, but it will lead to json result in a high probability which is not what I expected.

I think the correct way to declare this parameter should be
```python
format: Optional[Literal["json"]] = None
```
which could give me the correct plain text response.

### System Info

System Information
------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
> Python Version:  3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.3.22
> langchain: 0.3.10
> langchain_community: 0.3.10
> langsmith: 0.1.129
> langchain_experimental: 0.3.2
> langchain_ollama: 0.2.1
> langchain_openai: 0.2.11
> langchain_text_splitters: 0.3.0
> langgraph_api: 0.0.6
> langgraph_cli: 0.1.61
> langgraph_license: Installed. No version info available.
> langgraph_sdk: 0.1.43
> langgraph_storage: Installed. No version info available.
> langserve: 0.3.0

Other Dependencies
------------------
> aiohttp: 3.10.5
> async-timeout: 4.0.3
> click: 8.1.7
> cryptography: 43.0.3
> dataclasses-json: 0.6.7
> fastapi: 0.115.6
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> jsonschema-rs: 0.25.1
> langgraph: 0.2.56
> langgraph-checkpoint: 2.0.8
> numpy: 1.26.4
> ollama: 0.4.3
> openai: 1.52.1
> orjson: 3.10.11
> packaging: 24.1
> pydantic: 2.10.3
> pydantic-settings: 2.5.2
> pyjwt: 2.10.1
> python-dotenv: 1.0.1
> PyYAML: 6.0.2
> requests: 2.32.3
> SQLAlchemy: 2.0.34
> sse-starlette: 2.1.3
> starlette: 0.41.3
> structlog: 24.4.0
> tenacity: 8.5.0
> tiktoken: 0.7.0
> typing-extensions: 4.12.2
> uvicorn: 0.32.1
> watchfiles: 1.0.0

**Comment by samyIO** [comment]
Omg thanks! I have the same issue. I'm debugging my python environment since hours! Which version is free of this bug?

**Comment by LogCreative** [comment]
> Omg thanks! I have the same issue. I'm debugging my python environment since hours! Which version is free of this bug?

It seems the code has not been fixed yet👀, the referenced code is the latest.

**Comment by samyIO** [comment]
Yea.. i thought maybe i could use an older version. But i don't know when the bug started.

**Comment by LogCreative** [comment]
> Yea.. i thought maybe i could use an older version. But i don't know when the bug started.

I changed the package file directly😁.

The `ChatOllama` from `langchain_ollama` is new; and the one from `langchain_community.chat_models` has been marked as deprecated and does not support tool calling.

**Comment by edmcman** [comment]
How does langchain not test for this before shipping a new release?

**Comment by juliojm13** [comment]
@samyIO Thank you for oppening this issue!

---
I have the same problem since yesterday after your latest release.
Any estimation to resolve this bug?

**Comment by edmcman** [comment]
I have not looked at the problem, but `pip install ollama==0.4.2` avoids it for now.  This suggests to me that this is an Ollama bug.

**Comment by edmcman** [comment]
https://github.com/ollama/ollama-python/issues/366

**Comment by polinanechaeva25** [comment]
OMG, i have absolutely the same error. I'm waiting for this issue to be solved

**Comment by juliojm13** [comment]
> I have not looked at the problem, but `pip install ollama==0.4.2` avoids it for now. This suggests to me that this is an Ollama bug.

Downloading to ollama==0.4.2 helps, thanks! @edmcman

**Comment by varun-d** [comment]
Thanks @LogCreative I've observed the same bug.

Ollama (0.5.1) Llama 3 on Localhost:11434
I am not going to downgrade my local installation.

``` python

# Notebook block to setup messages
from pprint import pprint
from langchain_core.messages import AIMessage, HumanMessage

messages = [AIMessage(content=f"So you said you were researching ocean mammals?", name="Model")]
messages.append(HumanMessage(content=f"Yes, that's right.",name="Lance"))
messages.append(AIMessage(content=f"Great, what would you like to learn about.", name="Model"))
messages.append(HumanMessage(content=f"I want to learn about the best place to see Orcas in the US.", name="Lance"))

for m in messages:
    m.pretty_print()


# Notebook block for Ollama invoke. Also tried with plain "string".
from langchain_ollama import ChatOllama

ollm = ChatOllama(model="llama3")
print(ollm)
result = ollm.invoke("Who are you?")
type(result)
```

## ERROR:

```
ValidationError: 2 validation errors for ChatRequest
format.literal['json']
  Input should be 'json' [type=literal_error, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
format.dict[str,any]
  Input should be a valid dictionary [type=dict_type, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/dict_type

```

## A warning for httpx while installing langchain-ollama:

``` bash
Installing collected packages: httpx, ollama, langchain-ollama
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.0
    Uninstalling httpx-0.28.0:
      Successfully uninstalled httpx-0.28.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab 4.3.2 requires httpx~=0.28.0, but you have httpx 0.27.2 which is incompatible.
Successfully installed httpx-0.27.2 langchain-ollama-0.2.1 ollama-0.4.3
```

**Comment by nadeemcite** [comment]
The issue stems from a recent update in the ollama-python package, where the [BaseGenerateRequest class only allows 'json' as a valid value](https://github.com/ollama/ollama-python/blob/4b10dee2b2a73242bb3ac89332f634cda2b6f633/ollama/_types.py#L154) for the format field. Previously, an empty string was also permitted, but this support was removed in the latest update. To resolve this, we can modify the _types.py file in the ollama-python package to allow an empty string alongside 'json'. I've also added a PR to address this issue [here](https://github.com/ollama/ollama-python/pull/368).

**Comment by ParthSareen** [comment]
Hey! We've just cut a release to fix this. I would making updates on the langchain end to defaulting to `None` instead. There can be unintended consequences to setting as an empty string once the request hits the server so would like to avoid that pattern. Thanks!

**Comment by jmorganca** [comment]
To add: sorry this happened. For those who are hitting the error, updating to the newest version of the `ollama` package should fix it:

```
pip install -U ollama
```

**Comment by cogitojayant** [comment]
Still issue persists

**Comment by jmorganca** [comment]
@cogitojayant Sorry about that – do you have a code snippet to reproduce? OP's code now runs with `ollama==0.4.4`

**Comment by infiniteAppsUG** [comment]
ollama==0.4.4 did the job in an environment with langchain. thank you!

**Comment by FangKQ** [comment]
ollama==0.4.4 still doesn't work

**Comment by Pacman1984** [comment]
Still not working

```python
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

# Define a Pydantic class as the tool schema
class WeatherData(BaseModel):
    city: str = Field(..., description="Name of the city.")
    temperature: str = Field(..., description="The temperature in degrees Celsius.")
    condition: str = Field(..., description="The weather condition.")

# Initialize ChatOllama and bind the schema as a tool
llm = ChatOllama(model="qwen2.5:14b-instruct",
    base_url="http://SERVERIP:11434",)
structured_llm = llm.with_structured_output(WeatherData, method="json_schema")

# Define input
messages = [
    ("system", "You are a weather assistant."),
    ("human", "Provide weather details for Tokyo.")
]

# Invoke the model
response = structured_llm.invoke(messages)

# Print the structured output
print(response)
```

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[15], [line 13](vscode-notebook-cell:?execution_count=15&line=13)
>      [10](vscode-notebook-cell:?execution_count=15&line=10) # Initialize ChatOllama and bind the schema as a tool
>      [11](vscode-notebook-cell:?execution_count=15&line=11) llm = ChatOllama(model="qwen2.5:14b-instruct",
>      [12](vscode-notebook-cell:?execution_count=15&line=12)     base_url="http://SERVERIP:11434/",)
> ---> [13](vscode-notebook-cell:?execution_count=15&line=13) structured_llm = llm.with_structured_output(WeatherData, method="json_schema")
>      [15](vscode-notebook-cell:?execution_count=15&line=15) # Define input
>      [16](vscode-notebook-cell:?execution_count=15&line=16) messages = [
>      [17](vscode-notebook-cell:?execution_count=15&line=17)     ("system", "You are a weather assistant."),
>      [18](vscode-notebook-cell:?execution_count=15&line=18)     ("human", "Provide weather details for Tokyo.")
>      [19](vscode-notebook-cell:?execution_count=15&line=19) ]
> 
> File i:\Coding\\.venv\Lib\site-packages\langchain_core\language_models\chat_models.py:1228, in BaseChatModel.with_structured_output(self, schema, include_raw, **kwargs)
>   
> 
> ValueError: Received unsupported arguments {'method': 'json_schema'}


Ollama server is 0.51
local:
pip list | findstr -i "langchain ollama"
langchain                 0.3.11
langchain-community       0.3.11
langchain-core            0.3.25
langchain-experimental    0.3.3
langchain-ollama          0.2.1
langchain-text-splitters  0.3.2
ollama                    0.4.4
