### ISSUE TITLE
ArxivRetriever from langchain_community returning wrong number of documents 

### ISSUE THREAD

**Issue by katyachemistry** [langchain-ai/langchain#28614]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

1 and 2 differ in **get_ful_documents argument**

1. 
``` python
from langchain_community.retrievers import ArxivRetriever
retriever = ArxivRetriever(
    load_max_docs=10,
    get_full_documents=True,
)
query = 'Artificial intelligence'
docs = retriever.invoke(query)
len(docs)
# 3
```
2.
``` python
from langchain_community.retrievers import ArxivRetriever
retriever = ArxivRetriever(
    load_max_docs=10,
    get_ful_documents=True,
)
query = 'Artificial intelligence'
docs = retriever.invoke(query)
# 3
```

### Description

I was trying to use ArxivRetriever from langchain-community lib. 

I've run these code cells first in colab. Initially I copypasted the code from langchain documentation you can find [here](https://python.langchain.com/api_reference/community/retrievers/langchain_community.retrievers.arxiv.ArxivRetriever.html#langchain_community.retrievers.arxiv.ArxivRetriever.get_full_documents). The retriever is called with get_**ful**\_documents and not get_**full**_documents argument. Which I believe is not a typo in documentation, because no exceptions were raised. 

Still, there was an issue. Whatever number I put in the load_max_docs argument, 1, 5 or 100, it gave only 3 documents when called. 
Correcting get_**ful**\_documents to get_**full**\_documents did not help when working in _colab_, I still got len(docs) = 3.
However, when run _locally_, with different versions of libs than those from colab, the retriever yielded a correct number of docs with argument get_**full**\_documents. But with get_**ful**_documents it still gave 3 docs. 

### System Info

**colab**: 
langchain==0.3.10
langchain-community==0.3.10
langchain-core==0.3.22
langchain-text-splitters==0.3.2
arxiv==2.1.3

**local machine**:
langchain==0.2.1
langchain-community==0.2.4
langchain-core==0.2.41
langchain-text-splitters==0.2.4
arxiv==2.1.3

**Comment by EMIDY643** [comment]
DeepNude AI offers advanced tools for generating high-quality AI-powered imagery. With features like precision, ease of use, and seamless integration, it caters to beginners and professionals alike. Users can enjoy: https://5454.us/

## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/)
3- Best undress ai for free without sing up :**https://5454.us/**
4- surprise For an iPhone at a surprising price :**https://installchecker.com/sl/7dr1n**
No cost: Completely free with no hidden charges.
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
DeepNude AI offers advanced tools for generating high-quality AI-powered imagery. With features like precision, ease of use, and seamless integration, it caters to beginners and professionals alike. Users can enjoy: https://installchecker.com/sl/7dr1n
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/)
3- Best undress ai for free without sing up : https://5454.us/
4- surprise For an iPhone at a surprising price : https://installchecker.com/sl/7dr1n
No cost: Completely free with no hidden charges.
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>][(https://5454.us/?tdsId=s0331aes_r&tds_campaign=s0331aes&utm_sub=opnfnl&s1=ps&utm_source=int&subid={subid}&clickid={clickid}&subid2={subid2}&affid=181c7b69)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
## [👉🔴 Click HERE >>](https://5454.us/)
Accessibility: Available on various platforms.
Advanced results: Crisp and accurate outputs.
Why Choose DeepNude AI? https://installchecker.com/sl/7dr1n
Trusted worldwide for its efficiency, DeepNude AI combines simplicity with reliability, making it an ideal choice for users seeking fast, effective AI solutions

_Originally posted by @comtthe in https://github.com/tidys/CocosCreatorPlugins/issues/33#issuecomment-2525654463_

**Comment by keenborder786** [comment]
@katyachemistry, you need to use `top_k_results` which basically is how many documents do you need to fetch which you want (minimum number of documents). On the other hand, `load_max_docs ` is bascially if you are fetching more than x docs, this will act as a upper limit meaning query will never fetch more than this amount (maximum number of docs)

**Comment by keenborder786** [comment]
@katyachemistry check this: https://python.langchain.com/api_reference/community/utilities/langchain_community.utilities.arxiv.ArxivAPIWrapper.html

**Comment by katyachemistry** [comment]
> Their is a slight issue where `load_max_docs` is not being used but you want `top_k_results` regardless

I see. top_k_results works, thank you.
