### ISSUE TITLE
core: make docstring parsing more robust

### ISSUE THREAD

**Issue by ccurme** [langchain-ai/langchain#28628]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

Valid Google-style docstrings with descriptions > 1 paragraph are not supported.

Example failure:

```python
from langchain_core.tools import tool


@tool(parse_docstring=True)
def search(query: str) -> None:
  """Searches for information based on the query.

  Use this tool to look up factual information or search for relevant content.

  Args:
    query: The search query. A good query is a clear and concise question or statement.

  Returns:
    A list of documents that match the query.
  """
  pass
```

Root cause is raising an error when second `\n\n`-delimited block does not start with `Args`: https://github.com/langchain-ai/langchain/blob/ec9b41431ea8bccccc3b9f1679c1e1e16c26e23e/libs/core/langchain_core/utils/function_calling.py#L618

**Comment by isatyamks** [comment]
@ccurme Could you please review my PR #28730? I am encountering a couple of issues with the linting process
![image](https://github.com/user-attachments/assets/1b96cf09-f65d-43eb-b135-95fe0bde72b7)
