### ISSUE TITLE
Pandas Dataframe Agent Issue with Multiple sheets of xlsx file

### ISSUE THREAD

**Issue by Kashif-Raza6** [langchain-ai/langchain#2862]
When I tries to read the all the sheets from the `.xlsx` file and pass it to the `create_pandas_dataframe_agent` it creates error.
`
from langchain.agents import create_pandas_dataframe_agent
`
`
df = pd.read_excel('data.xlsx', sheet_name= none)
`
`
agent = create_pandas_dataframe_agent(OpenAI(temperature=0), df, verbose=True)
`

**Comment by azamiftikhar1000** [comment]
@Kashif-Raza6 
`pd.read_excel()` Returns dictionary of dataframes but `create_pandas_dataframe_agent` only accepts dataFrame.
