### ISSUE TITLE
Dataset Loaders: HuggingFace

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#2864]
While LangChain has already explored [using Hugging Face Datasets to evaluate models](https://python.langchain.com/en/latest/use_cases/evaluation/huggingface_datasets.html), it would be great to see loaders for [HuggingFace Datasets](https://huggingface.co/datasets).

I see several benefits to creating a loader for [steaming-enabled](https://huggingface.co/docs/datasets/stream) HuggingFace datasets:

**1. Integration with Hugging Face models:** Hugging Face datasets are designed to work seamlessly with Hugging Face models, such as Transformers and Tokenizers. This means that you can easily use streaming datasets to provide context for your LangChain-powered LLMs or other Hugging Face models.

**2. Customization:** Hugging Face datasets provide a flexible and customizable way to process and transform data. You can apply custom functions or transformations to the prompts as they are streamed. For example, you can preprocess the prompts by removing stop words or punctuation, or you can extract features from the prompts using a feature extraction model.

**3. Compatibility with different data formats:** Hugging Face datasets support a wide range of data formats, including CSV, JSON, and Parquet. This means that you can easily stream prompts from different sources and formats.

**4. Dynamic updating:** Streaming datasets can be updated in real-time, which can enable you to add new prompts or remove outdated prompts from the dataset without having to reload the entire dataset.

**5. Real-time processing:** Streaming datasets can enable real-time processing of user prompts, which can be useful in applications that require fast response times.

**Comment by AIWithShrey** [comment]
Can you also implement setting the split size for the dataset? Some datasets are humongous but I just want 1/10th of it for experimentation. I tried to edit the present LangChain HuggingFaceDatasetLoader class to accommodate the split size but it threw errors. I would really appreciate if this implemented.
