### ISSUE TITLE
sqlagent doesn't work when using Cohere LLM

### ISSUE THREAD

**Issue by shahrier** [langchain-ai/langchain#2866]
Here's what I tried:
`import os
os.environ["COHERE_API_KEY"] = ""
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms import Cohere
from langchain.agents import AgentExecutor

db = SQLDatabase.from_uri("sqlite:///Chinook.db")
toolkit = SQLDatabaseToolkit(db=db)

agent_executor = create_sql_agent(
    llm=Cohere(temperature=0, model="xlarge"),
    toolkit=toolkit,
    verbose=True
)
agent_executor.run("Give me the most popular artist and the dollar amount the customers spent on this artist")`

The error I received:

`File "/usr/local/lib/python3.9/site-packages/langchain/tools/sql_database/tool.py", line 85, in <lambda>
    llm=OpenAI(temperature=0),
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)`

**Comment by chintan-donda** [comment]
> SQLDatabaseToolkit use openai in its QueryChecker. You should have OPEN_API_KEY set to your openai api key for this to work

Can't we use the local LLM to work with SQLDatabaseToolkit?
Or is there any way to create the SQL agent that works with local LLM?

**Comment by vowelparrot** [comment]
Yes. You can specify any  LLM when creating the SQLDatabaseToolkit

**Comment by jdellag** [comment]
> Yes. You can specify any LLM when creating the SQLDatabaseToolkit https://python.langchain.com/en/latest/reference/modules/agent_toolkits.html?highlight=sqldatabasetoolkit#langchain.agents.agent_toolkits.SQLDatabaseToolkit

Broken link should be https://python.langchain.com/docs/modules/agents/toolkits/sql_database
