### ISSUE TITLE
Link is note avilable

### ISSUE THREAD

**Issue by amandafanny** [langchain-ai/langchain#28822]
### URL

https://blog.langchain.dev/implementing-advanced-retrieval-rag-strategies-with-neo4j/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://github.com/langchain-ai/langchain/tree/master/templates/neo4j-advanced-rag?ref=blog.langchain.dev
is note avilable.

**Comment by efriis** [comment]
thanks! fixed to point to 0.2 branch
