### ISSUE TITLE
C:\Windows\system32>LANGCHAIN_TRACING_V2=true 'LANGCHAIN_TRACING_V2' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by gandhidakshina** [langchain-ai/langchain#28870]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

C:\Windows\system32>LANGCHAIN_TRACING_V2=true
'LANGCHAIN_TRACING_V2' is not recognized as an internal or external command,
operable program or batch file.

### Idea or request for content:

C:\Windows\system32>LANGCHAIN_TRACING_V2=true
'LANGCHAIN_TRACING_V2' is not recognized as an internal or external command,
operable program or batch file.

**Comment by keenborder786** [comment]
Sorry Can you elaborate your issue?

**Comment by ccurme** [comment]
I think this issue is regarding how to set environment variables on Windows machines and is unrelated to LangChain.
