### ISSUE TITLE
How GraphQL?

### ISSUE THREAD

**Issue by alexec** [langchain-ai/langchain#2891]
Can do REST with OpenAPI? But what about GQL? Possible even?

**Comment by simonfranzen** [comment]
You could try to make a start from API Chain.
GQL endpoints are great because you get the whole schema + api doc in once

**Comment by axiomofjoy** [comment]
Also wondering this myself.

**Comment by iyinoluwaayoola** [comment]
Exactly same question brought me here. Happy to share your findings, @alexec ?

**Comment by axiomofjoy** [comment]
> [GraphQL Tool](https://python.langchain.com/en/latest/modules/agents/tools/examples/graphql.html) | [Code](https://github.com/hwchase17/langchain/blob/master/langchain/tools/graphql/tool.py)
> 
> GraphQL tool seems to be the way, but it isn't working for me.
> 
> * missing dependencies (requests_toolbelt)
> * pydantic validation error for two fields

Interesting, will have to take a look.

**Comment by ramapalani** [comment]
Try this out, a simple use case when you are given a graphql query, execute it through an Langchain LLM agent

```
def gql_executor(llm, gql_endpoint, gql_query, headers=None):
    # make sure graphql query is properly formatted
    # replace multiple spaces with single space
    # replace tabs with \t
    # escape double quotes with \"
    gql_query_escaped = ' ' \
        .join(gql_query.split()) \
        .replace('\n', '\t') \
        .replace("\t", "\\t") \
        .replace("\"", "\\\"")
    input = f"""\
    {{
        "url": "{gql_endpoint}",
        "data": {{
            "query": "{gql_query_escaped}"
        }}
    }}
    """
    gql_request = TextRequestsWrapper(headers=headers)
    request_post_tool = RequestsPostTool(requests_wrapper=gql_request)
    tools = [request_post_tool]
    agent_executor = initialize_agent(
        tools,
        llm,
        agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
        verbose=True,
        max_iterations=3)
    return agent_executor.run(input)



####################################################################################
# An example query using a public GraphQL endpoint
countries_gql_endpoint = "https://countries.trevorblades.com/graphql"
countries_gql_query = """query Query {
  country(code: "IN") {
    name
    native
    capital
    emoji
    currency
    languages {
      code
      name
    }
  }
}"""
gql_executor(llm, countries_gql_endpoint, countries_gql_query)
```

**Comment by aerrober** [comment]
The graphql support is expanded in this PR which should make this process easier with introspection queries built in: https://github.com/langchain-ai/langchain/pull/8187
