### ISSUE TITLE
community: Raise KeyError: 'request' in module langchain_community.llms.tongyi 

### ISSUE THREAD

**Issue by Coolgiserz** [langchain-ai/langchain#28933]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```python
        content = None
        err = None
        try:
            content = self.chain.invoke(input=dict(topic=topic,
                                         section=section,
                                         topic_description=topic_description.strip(),
                                         section_description=section_description.strip(),
                                         formatted_text=formatted_text
                                         ))
        except Exception as e:
            logger.error(f"{self.__class__} run error: {repr(e)}")
            logger.error(traceback.format_exc())
            err = e
```

### Error Message and Stack Trace (if applicable)

<img width="988" alt="image" src="https://github.com/user-attachments/assets/529ff319-80f7-451b-a4a8-7aab477cb4ce" />

<img width="975" alt="image" src="https://github.com/user-attachments/assets/0c63e7d8-840b-443d-9dca-78bc24aecbec" />

### Description

1. I'm trying to use Tongyi llm model implemented in langchain_community.llms to do sth.
2. When I call chain.invoke(*arg, **kwargs), Sometimes it raise Error: KeyError: 'request' for unknown reason. 
4. It seems like the api_base_url by default is not stable., but I'm not sure.

### System Info

------------------
> OS:  Darwin
> OS Version:  Darwin Kernel Version 24.2.0: Fri Dec  6 18:56:34 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6020
> Python Version:  3.11.10 (main, Oct  3 2024, 02:26:51) [Clang 14.0.6 ]

Package Information
-------------------
> langchain_core: 0.3.22
> langchain: 0.3.10
> langchain_community: 0.3.10
> langsmith: 0.1.147
> langchain_openai: 0.2.11
> langchain_text_splitters: 0.3.2

Optional packages not installed
-------------------------------
> langserve

Other Dependencies
------------------
> aiohttp: 3.10.10
> async-timeout: Installed. No version info available.
> dataclasses-json: 0.6.7
> httpx: 0.27.2
> httpx-sse: 0.4.0
> jsonpatch: 1.33
> langsmith-pyo3: Installed. No version info available.
> numpy: 1.26.4
> openai: 1.54.3
> orjson: 3.10.12
> packaging: 23.2
> pydantic: 2.9.2
> pydantic-settings: 2.6.1
> PyYAML: 6.0.2
> requests: 2.32.3
> requests-toolbelt: 1.0.0
> SQLAlchemy: 2.0.36
> tenacity: 8.5.0
> tiktoken: 0.8.0
> typing-extensions: 4.12.2

**Comment by keenborder786** [comment]
@Coolgiserz this might be a problem `dashscope` package itself.

**Comment by Coolgiserz** [comment]
Thanks for your reply. 
After conducting some debugging, I’ve discovered that the dashscope package seems to be masking actual user-related errors. Instead of exposing the specific issues related to the user’s actions or environment, it throws a generic internal processing exception.
![image](https://github.com/user-attachments/assets/94d4f5f4-cc89-40df-a512-f555d76deb50)

I will further investigate this behavior and provide more details if needed.

**Comment by Coolgiserz** [comment]
![image](https://github.com/user-attachments/assets/d2a05c49-31da-4ffd-8e00-c79b0b9fd2fd)
Sometimes raise KeyError while reaching request rate limit.

**Comment by safa1018** [comment]
so how to solve it

**Comment by Endorphins20** [comment]
so how to solve it

**Comment by Coolgiserz** [comment]
This issue is actually caused by insufficient access permissions to the Qwen model or exceeding the request rate limit. You can confirm that you have the model access permission on the Alibaba Cloud official website. Refer to the QPS constraints of the service and reduce concurrent requests. If you need to handle exceptions, capture the status_code in the GenerationResponse.
