### ISSUE TITLE
regex in langchain/agents/mrkl/base.py

### ISSUE THREAD

**Issue by captainst** [langchain-ai/langchain#2898]
When use agent to answer question **"Who is Leo DiCaprio's current girlfriend? What is her current age raised to the 0.43 power?"**
I saw openAI gives the following initial reply:
```
I should use Google Search to find out who is Leo DiCaprio's current girlfriend. For the second part of the question, I should use the calculator to calculate her age raised to the 0.43 power.
Action 1: Google Search
Action 1 Input: "Leo DiCaprio current girlfriend"
```
Instead of **"Action"** and **"Action Input"** keywords, we have **"Action 1"** and **"Action 1 Input"** instead. 

The regex in langchain/agents/mrkl/base.py:
**regex = r"Action: (.*?)[\n]*Action Input:[\s]*(.*)"**
is better to be changed to
**regex = r"Action.*?: (.*?)[\n]*Action.*? Input:[\s]*(.*)"**

In order to avoid tool not found error.

**Comment by azamiftikhar1000** [comment]
@captainst Could you please provide the example  where its `Action 1 Input and  Action 1` instead of  `Action and Action Input`. I tested with openAI its giving correct results. Thanks!

**Comment by captainst** [comment]
hi @azamiftikhar1000 The test code I used is the following snippet:
```
from langchain.llms import OpenAI
from langchain.agents import load_tools
from langchain.agents import initialize_agent
import json
import os

os.environ["GOOGLE_CSE_ID"] = "xxxxxx"
os.environ["GOOGLE_API_KEY"] = "xxxxxx"
openai_api_key = "xxxxxx"

llm = OpenAI(model_name="gpt-3.5-turbo", openai_api_key=openai_api_key, temperature=0.8)

toolkit = load_tools(["google-search", "llm-math"], llm=llm)

agent = initialize_agent(toolkit, llm, agent="zero-shot-react-description", verbose=True)

agent.run("Who is Leo DiCaprio's current girlfriend? What is her current age raised to the 0.43 power?")
```

**Comment by azamiftikhar1000** [comment]
@captainst  Thank you for that, It seems that when we use `gpt-3.5-turbo` it is giving 
`Action 1:` in the output.

<img width="935" alt="Screenshot 2023-04-15 at 12 30 35 PM" src="https://user-images.githubusercontent.com/55012400/232193990-84a84504-c5cd-44bf-b559-88ecfa0087bc.png">

Where as gpt-4 is giving `Action:` 


<img width="838" alt="Screenshot 2023-04-15 at 12 33 24 PM" src="https://user-images.githubusercontent.com/55012400/232194110-1c8c0b59-ddb4-4b4a-803e-c035a3018a0a.png">

I will shortly create the PR with the solution.

Thanks!
