### ISSUE TITLE
Connect a GPT model to cloud cost calculators

### ISSUE THREAD

**Issue by danielpatrickhug** [langchain-ai/langchain#292]
Hey, I'm looking to create an open-source tool that can be used to have conversations about pricing out different cloud services. Does anyone want to help out? or does anyone have any thoughts?

**Comment by fblissjr** [comment]
Good idea. You can make this work at a basic level by chaining together search and PAL. See example below:

`# Get the cost of an EC2 instance per hour from search and run some math experiments, using all tools
# agent="zero-shot-react-description"
import re

# Get the cost per hour and regex the $ out
agent.run("What is the price per hour for running an AWS EC2 instance type of T5") # search API
agent_output = agent.run("What is the price per hour for running an AWS EC2 instance type of T5") # Question for price lookup
regex_currency = r"^[0-9]+(\.[0-9]{1,2})?$
cost_per_hour = re.findall(regex_currency, agent_output, re.I)

# Math experiments on total cost based on assumptions
agent.run("What is the annual cost of the EC2 instance, assuming it only runs 8 hours a day on weekdays and 0 hours on weekends, and the hourly cost is " + str(cost_per_hour[0]) + "?")`

The output looks like this:

> > Entering new AgentExecutor chain...
 I need to find out the cost of running an EC2 instance
Action: Search
Action Input: "AWS EC2 instance type T5 cost per hour"
Observation: $0.096 per vCPU-Hour for Windows and Windows with SQL Web. The CPU Credit pricing is the same for all instance sizes, for On-Demand, Spot, and Reserved ...
Thought: I now know the final answer
Final Answer: The cost per hour for running an AWS EC2 instance type of T5 is $0.096 per vCPU-Hour for Windows and Windows with SQL Web. The CPU Credit pricing is the same for all instance sizes, for On-Demand, Spot, and Reserved.
> Finished AgentExecutor chain.


> Entering new AgentExecutor chain...
 I need to find out the cost of running an EC2 instance
Action: Search
Action Input: "AWS EC2 instance type T5 cost per hour"
Observation: $0.096 per vCPU-Hour for Windows and Windows with SQL Web. The CPU Credit pricing is the same for all instance sizes, for On-Demand, Spot, and Reserved ...
Thought: I now know the final answer
Final Answer: The cost per hour for running an AWS EC2 instance type of T5 is $0.096 per vCPU-Hour for Windows and Windows with SQL Web. The CPU Credit pricing is the same for all instance sizes, for On-Demand, Spot, and Reserved.
> Finished AgentExecutor chain.
