### ISSUE TITLE
LlamaCpp model needs streaming support

### ISSUE THREAD

**Issue by peter-ch** [langchain-ai/langchain#2948]
Streaming is supported by llama-cpp-python and works in Jupyter notebooks outside langchain code, but I can't get it to work with langchain. I didn't see any code for streaming in llms/llamacpp.py. I tried to do calls to self.callback_manager..on_llm_new_token() but nothing worked.

**Comment by vowelparrot** [comment]
It's being worked on https://github.com/hwchase17/langchain/pull/2775
