### ISSUE TITLE
Support long-term and short-term memory in Conversation chain

### ISSUE THREAD

**Issue by shoelsch** [langchain-ai/langchain#296]
The current `Memory` objects allow a user to store the [entire conversation history](https://github.com/hwchase17/langchain/blob/master/langchain/chains/conversation/memory.py#L22), a [subset of history](https://github.com/hwchase17/langchain/blob/master/langchain/chains/conversation/memory.py#L50), and a [summary of history](https://github.com/hwchase17/langchain/blob/master/langchain/chains/conversation/memory.py#L79).

Users might want to store a summary of the conversation in addition to a fixed-size history.

You could imagine the following algorithm:
```
1. Check if current conversation history has reached maximum size
2. If so, generate a conversation summary.
3. Optionally, merge the prior summary with the new summary.
4. Trim the conversation history
5. Append new exchange to conversation history
```

If the user wants to maintain a fixed-size conversation history as well as a summary, a simpler approach might be to create a more general `MemoryBank` container. There would need to be validation that the memory key is unique.

```
class MemoryBank(Memory, BaseModel):
    resources: list[Memory]
    
    def load_memory_variables(self, inputs: Dict[str, Any]) -> Dict[str, str]:
        """Return history buffer."""
        return {r.memory_key: r.buffer for r in self.resources}
     
     ...
```

**Comment by hwchase17** [comment]
i love both the specific memory algorithm you desribed as well as the general MemoryBank abstraction! i think both are worth doing. probably two separate PRs/issues. any idea which one you want to do first?
