### ISSUE TITLE
ChatOpenai (gpt3-turbo) isn't compatible with create_pandas_dataframe_agent, create_csv_agent etc

### ISSUE THREAD

**Issue by Architectshwet** [langchain-ai/langchain#2967]
I tried creating a pandas dataframe agent (using create_dataframe_agent) with ChatOpenai (gpt3-turbo) as the LLM! But langchain isn't able to parse the LLM's output code. Ofcoure when I use davince model it works 

### This is the code:

from langchain.llms import OpenAIChat
openaichat = OpenAIChat(model_name="gpt-3.5-turbo")
agent = create_csv_agent(openaichat, 'fishfry-locations.csv', verbose=True)
x = agent.run("How many rows for church?")

### This is the output and error

> Entering new AgentExecutor chain...
Thought: We need to filter the dataframe to only include rows where the venue_type is "Church" and then count the number of rows.
Action: python_repl_ast
Action Input:
```
len(df[df['venue_type'] == 'Church'])
```
Observation: invalid syntax (<unknown>, line 1)
Thought:I need to fix the syntax error by adding a closing parenthesis at the end of the input.
Action: python_repl_ast
Action Input:
```
len(df[df['venue_type'] == 'Church']) 

```
Observation: invalid syntax (<unknown>, line 1)
Thought:

> Finished chain.

**Comment by engma-linguistics** [comment]
I have seen lots of parsing errors with gpt-3.5-turbo and gpt-4 as well.

**Comment by tevslin** [comment]
ditto with the pandas agent. often the syntax is actually correct.
