### ISSUE TITLE
CHAT_CONVERSATIONAL_REACT_DESCRIPTION vs CONVERSATIONAL_REACT_DESCRIPTION 

### ISSUE THREAD

**Issue by leewsimpson** [langchain-ai/langchain#2968]
using CHAT_CONVERSATIONAL_REACT_DESCRIPTION the agent does not chain together tools - only the first iteration, then stops. The other AgenTypes work as expected.

```
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

llm = AzureChatOpenAI(
    temperature=0, 
    deployment_name="gpt4", 
    model_name="gpt-4")
    
tools = load_tools(["google-search", "requests_all", "llm-math", "wolfram-alpha", "wikipedia", "pal-math"], llm=llm)

agent_zero_shot = initialize_agent(
    tools, 
    llm,
    agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    memory=memory,
    verbose=True)

response = agent_zero_shot.run(input="Who is Leo DiCaprio's girlfriend? What is her current age raised to the 0.43 power?")
print(response)
# returns: Eden Polani's age raised to the 0.43 power is approximately 3.55.

# agent_conversational = initialize_agent(
#     tools, 
#     llm,
#     agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
#     memory=memory,  # I think it ignores this
#     verbose=True)

# response = agent_conversational.run(input="Who is Leo DiCaprio's girlfriend? What is her current age raised to the 0.43 power?")
# print(response) 
# returns: Finished chain. Leonardo DiCaprio's most recent girlfriend is rumored to be Eden Polani, who is 19 years old. To calculate her age raised to the 0.43 power, I'll need to use a calculator.
```

CONVERSATIONAL_REACT_DESCRIPTION works as expected. However given I'm using Azure and GPT4 I only have the chat interface.

**Comment by GiovanniGrotto** [comment]
I have the same problem, the agent choose one tool and then give the final answer without trying other tools(where the right answer was)

**Comment by lironezra** [comment]
I have the same problem too

**Comment by blackwitch** [comment]
me too. Try reverting to version 0.0.189

**Comment by mb52089** [comment]
I have the same problem too.  Had to switch to CONVERSATIONAL_REACT_DESCRIPTION but that agent type has its own problems too.

**Comment by guidorietbroek** [comment]
I tried to solve this by changing the FORMAT_INSTRUCTIONS but it seems that this is not a variable but loaded via the '''get_format_instructions''' which are loaded from '''from langchain.agents.conversational_chat.prompt import FORMAT_INSTRUCTIONS'''

To me this looks like a wrong prompt, because it's not following the ReAct logic.

**Comment by guidorietbroek** [comment]
> me too. Try reverting to version 0.0.189

What's different in that version?

**Comment by guidorietbroek** [comment]
I was able to solve this issue by using a modified prompt. The current prompt is not initiating a possible iterating loop to get more information to answer the question. Also by creating a custom output_parser the ```format_instructions``` can be adjusted.

**Comment by axen2u** [comment]
@guidorietbroek Can you post the prompt as well? I'm facing the same issue right now.

**Comment by Siddhijain16** [comment]
> I was able to solve this issue by using a modified prompt. The current prompt is not initiating a possible iterating loop to get more information to answer the question. Also by creating a custom output_parser the `format_instructions` can be adjusted.
> 
> @hwchase17 this needs a fix.

Hi, Can you provide a sample code, for this ?
Thanks

**Comment by guidorietbroek** [comment]
I need to change the method get_format_instructions but it is not accepting it.

```
agent_chain.agent.output_parser.get_format_instructions = FORMAT_INSTRUCTIONS
```
Gives me this error:

````
ValueError: "ConvoOutputParser" object has no field "get_format_instructions"
```

**Comment by axen2u** [comment]
@guidorietbroek @Siddhijain16  Try this.

```
class CustomConvoOutputParser(AgentOutputParser):
        """Output parser for the conversational agent."""

        ai_prefix: str = "AI"
        """Prefix to use before AI output."""

        def get_format_instructions(self) -> str:
            return CUSTOM_FORMAT_INSTRUCTIONS

        def parse(self, text: str) -> Union[AgentAction, AgentFinish]:
            if f"{self.ai_prefix}:" in text:
                return AgentFinish(
                    {"output": text.split(f"{self.ai_prefix}:")[-1].strip()}, text
                )
            regex = r"Action: (.*?)[\n]*Action Input: (.*)"
            match = re.search(regex, text)
            if not match:
                return AgentFinish(
                    {"output": text.split(f"{self.ai_prefix}:")[-1].strip()}, text
                )
            action = match.group(1)
            action_input = match.group(2)
            return AgentAction(action.strip(), action_input.strip(" ").strip('"'), text)

        @property
        def _type(self) -> str:
            return "conversational"
```

And pass this to the agent when initializing 
agent_kwargs={'prefix':PREFIX,'format_instructions':CUSTOM_FORMAT_INSTRUCTIONS,'output_parser':CustomConvoOutputParser()}

**Comment by guidorietbroek** [comment]
@axen2u did you try this out? Because I also tried to point towards a custom output parser (copy of the Convo one) and because of the agentType it was not working correctly (also pointing to the standard ConvoOutputParser).

**Comment by axen2u** [comment]
@guidorietbroek That is working for me. Output parser should change as well not only the instructions.

**Comment by guidorietbroek** [comment]
Tx, I created a subclass and that's also working.
