### ISSUE TITLE
Tool agents should not try to use a tool on their last iteration

### ISSUE THREAD

**Issue by alexiri** [langchain-ai/langchain#2970]
When you set a max_iterations on a tool agent and it is down to its last iteration, it doesn't make sense for it to try to use a tool. Using a tool would require another iteration, which will be blocked.

There should be some way for the agent to realize it's out of iterations and just return a `Final answer` with whatever information its managed to get.

**Comment by alexiri** [comment]
FYI, my current best solution is to pass `max_iterations` to the prompt and do something like this:

```python
class MyPromptTemplate(StringPromptTemplate):
    tools: List[Tool]
    max_iterations: int
    
    def format(self, **kwargs) -> str:
        ...
        intermediate_steps = kwargs.pop("intermediate_steps")
        ...
        template = PREFIX
        if len(intermediate_steps) < self.max_iterations - 1:
            template += TOOLS
        else:
            template += NO_TOOLS
        template += SUFFIX
        
        return template.format(**kwargs)
        
prompt = MyPromptTemplate(
    tools=tools,
    max_iterations=MAX_ITERATIONS,
    # This omits the `agent_scratchpad`, `tools`, and `tool_names` variables because those are generated dynamically
    # This includes the `intermediate_steps` variable because that is needed
    input_variables=["input", "intermediate_steps", "history"],
)
```

**Comment by alexiri** [comment]
I think this is still relevant.

**Comment by bgreal5** [comment]
I think this makes a lot of sense. Im struggling with this, along with a seemingly related issue that utilizing ```max_iterations``` with ```early_stopping_method="generate"``` results in this:

```ValueError: variable agent_scratchpad should be a list of base messages, got {
    "action": MY_TOOL_NAME,
    "action_input": MY_TOOL_INPUT
}```
