### ISSUE TITLE
Support for Vertex AI Matching Engine as a Vector Store

### ISSUE THREAD

**Issue by olaf-hoops** [langchain-ai/langchain#2971]
Would be really nice to have support for Googles Vertex AI Matching Engine as a Vector Store:
[Google Cloud Vector Store](https://cloud.google.com/vertex-ai/docs/matching-engine/overview?hl=en)

I'm currently building an AI application with langchain agents using Google Cloud as my backend.
So im trying not to use to many third party services to keep everything as tidy as possible. 
Using a Google solution for the vector store would be a huge plus.

**Comment by Jflick58** [comment]
Some Google folks mentioned in #2892 that they are working on it. I'd monitor that issue for progress.
