### ISSUE TITLE
Question: RetrievalQA.from_chain_type - logging the full prompt

### ISSUE THREAD

**Issue by DrorSegev** [langchain-ai/langchain#2975]
Hi,
I'm using RetrievalQA.from_chain_type to query local index.
I'm using Custom Prompt as input (query and context)
Is there a way to log or inspect the actual prompt that is sent to OpenAI API including the query, and the context?
Also 
How to control the number of documents the retriever returns? 
Is there an option to see the accuracy score of each doc in the source_documents returned by the query?

Thanks
Dror

**Comment by KanhnaDT** [comment]
Would love to know how to control the number of documents the retriever returns!
"k" and "top_k_docs_for_context" don't seem to work!

I need that as i am using it in an Agent

**Comment by DSgUY** [comment]
> 

Can you explain a bit more?
I have this:
```
chain_type_kwargs = {"prompt": PROMPT}
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0.8)
retriever = vectordb.as_retriever()
qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever, chain_type_kwargs=chain_type_kwargs, return_source_documents=True)
response = qa({"query": query})
```
I want to:
1)debug the score of the search
2)debug the final prompt send to OpenAI

Regards

**Comment by SnoozingSimian** [comment]
Hey is there a solution for this yet? I have been trying to solve the same problem.

**Comment by DSgUY** [comment]
> Hey is there a solution for this yet? I have been trying to solve the same problem.
You can force k parameter with:
`chain_type_kwargs = {"prompt": PROMPT, "k": 2}`

**Comment by vanhopex** [comment]
Sorry, when I set verbose=True, I just got  this:
```
> Entering new RetrievalQA chain...

> Finished chain.
```
How can I get the full prompt ?
