### ISSUE TITLE
Parsing issue when using Python client

### ISSUE THREAD

**Issue by vinay-k12** [langchain-ai/langchain#2978]
I'm using this output parser. But when the agent is passing this to the action state, I'm getting parsing error. 

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/19322429/232312291-41effe19-0c95-4bb3-8528-ffe9f6571f89.png">

Here is the parser: 

class CustomOutputParser(AgentOutputParser):
    
    def parse(self, llm_output: str) -> Union[AgentAction, AgentFinish]:
        print(f"Input to parse function: {llm_output}")  # Print the input
        # Check if agent should finish
        if "Final Answer:" in llm_output:
            return AgentFinish(
                # Return values is generally always a dictionary with a single `output` key
                # It is not recommended to try anything else at the moment :)
                return_values={"output": llm_output.split("Final Answer:")[-1].strip()},
                log=llm_output,
            )
        # Parse out the action and action input
        regex = r"Action: (.*?)[\n]*Action Input:([\s\S]*?)(?=\n\n|$)"
        match = re.search(regex, llm_output, re.DOTALL)
        if not match:
            raise ValueError(f"Could not parse LLM output: `{llm_output}`")
        action = match.group(1).strip()
        action_input = match.group(2).strip()
        # Return the action and action input
        return AgentAction(tool=action, tool_input=action_input.strip(" ").strip('"'), log=llm_output)

**Comment by captainst** [comment]
The potential cause is that your parser is expecting the Action, and Action Input, something like 
```
Action: the action to take, should be xxx
Action Input: xxxx
```
While it received as input the Thought. This could be caused by some reasons, including the stop phrase you are using. It would be benificial to post the complete code for people to investigate.
