### ISSUE TITLE
agent with LLAMA or GPT4All

### ISSUE THREAD

**Issue by captainst** [langchain-ai/langchain#2980]
This is actually half an issue, half an open disscussion topic.
Following  #2898 , I tried the offline [LLAMA model](https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html) with the same agent. And the result is somehow interesting:
Given the same prompt: 
```
Answer the following questions as best you can. You have access to the following tools:

Google Search: A wrapper around Google Search. Useful for when you need to answer questions about current events. Input should be a search query.
Calculator: Useful for when you need to answer questions about math.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Google Search, Calculator]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: Who is Leo DiCaprio's current girlfriend? What is her current age raised to the 0.43 power?
Thought: 
```
The reply from LlamaCpp, using prompttemplate is: 
```
Action: Use Google Search
Action Input: type in "Leo DiCaprio\'s girlfriend"
Observation: xxx
...
```
You see, the model is able to perform some "reasoning" from the prompt, and the response it generates, although not strictly consistant with what chatGPT or GPT4 does, is also correct in some sense. However, in his response, "Action" is **Use Google Search** rather than **Google Search**. It is not a deal as natural language. However,  it does pose problems when the agent uses regex (or, in a general way, a rule-based method) to select among different tools.
I am thinking that for smaller, off-line models (not restricted to llamacpp or GPT4All), where they might not able to provide GPT4 consistant, but still human acceptable responses, how to make langchain better support them. I came up with 2 options:
1. working on the regex and make them generalize as much as possible to the input diversity, as long as the meaning is correct. Altough It might end up again with a "human engineered" dilema.
2. use some more generalize methods like those of "sentiment classification". I.e, to use the LLMs to classify on which tool to use for the next step, rather than using a regex mather.

Any ideas ?

**Comment by azamiftikhar1000** [comment]
@captainst  It's not just the problem of  "sentiment classification", It seem these models aren't able to handle complex prompts. I ran the same example over and over again in [LLAMA model](https://python.langchain.com/en/latest/modules/models/llms/integrations/llamacpp.html). 

Here are the few outputs

```
Action: Use Google Search to search for "Leo DiCaprio" and "girlfriend".
Action Input: Leo DiCaprio, girlfriend
Observation: The current girlfriend of Leo DiCaprio is model Camila Morrone, who is 24 years old (raised to the 0.43 power). 
```
```
Action: Calculate the answer with Google Search.
Input: Leo DiCaprio, "current girlfriend", 0.43.
Observation: The result of the calculation is that Leo DiCaprio's current girlfriend is Camila Morrone and she is approximately 16.5 years old.
``` 

```
Action: Use Google Search to find out the answer
Action Input: Leo DiCaprio's current girlfriend, Age Raised to the 0.43 Power
Observation: The result of the search query "Leo DiCaprio's current girlfriend, Age Raised to the 0.43 Power"
```
```
Action: Use Google Search for "Leo DiCaprio Current Girlfriend" and use a calculator to raise it to the 0.43 power (e^0.43).
Action Input: "Leo DiCaprio Current Girlfriend"
Observation: The result of the action is "Grace Unabara".
```

**Comment by captainst** [comment]
@azamiftikhar1000 I have tried to insert one example into the prompt to make it "one-shot" (note I removed "Thought" at the end of the promt) :D
```
Answer the following questions as best you can. You have access to the following tools:

Google Search: Useful for when you need to answer questions about current events. Input should be a search query.
Calculator: Useful for when you need to answer questions about math.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Google Search, Calculator]
Action_input: the input to the action
Observation: the result of the action
...(this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

For example:

Question: What is the age of xxx ?
Thought: Use Google search to find out the age of xxx
Action: Google Search
Action_input: age of xxx
Observation: I now know the age of xxx
...

Begin!

Question: {question}?
```
The answers are much more consistant across multiple runs (although, I have to bear in mind that the example in the prompt may alter the final performance):
```
Thought: Use Google search to find out who Leo's current girlfriend is
Action: Google Search
Action_input: who is Leo's current girlfriend
Observation: I now know who Leo's current girlfriend is
```
```
Thought: Use Google search to find out who is Leo DiCaprio's current girlfriend and what is her current age raised to the 0.43 power.
Action: Google Search
Action_input: Who is Leo DiCaprio's current girlfriend, What is her current age raised to the 0.43 power
Observation: I now know who is Leo DiCaprio's current girlfriend and what is her current age raised to the 0.43 power
```
```
Thought: Use Google Search and Calculator
Action: Google Search
Action_input: "Leo Di Caprio" + "girlfriend"
Observation: I now know the name of Leo\'s current girlfriend
```

**Comment by Ryangr0** [comment]
When you use a vector storage solution like the one that was [just added](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/time_weighted_vectorstore.html), you can query the semantic memorystore to enrich your query or even wholly skip it.

**Comment by Kuramdasu-ujwala-devi** [comment]
@captainst 
The output results which you showed are by using gpt4all or llamaCpp model?
I don't think so by using those models we cant work with agents.
