### ISSUE TITLE
embedding function not passed properly to Chroma

### ISSUE THREAD

**Issue by meal** [langchain-ai/langchain#2982]
Hi,
I'm running official docker image from Chroma and using it via rest API (I need it in server mode for persistent storage in production deployment)

When inserting documents (I'm loading pdfs) I'm getting 

`chromadb.api.models.Collection No embedding_function provided, using default embedding function: SentenceTransformerEmbeddingFunction`  
even though I'm passing OpenAIEmbeddings() as embedding parameter

```
embeddings = OpenAIEmbeddings()
    chroma_settings = Settings(
        chroma_api_impl="rest",
        chroma_server_host="localhost",
        chroma_server_http_port=8000,
        anonymized_telemetry=False,
    )

    
    loader = PyPDFLoader(pdf_url)
    pages = loader.load_and_split()
    Chroma.from_documents(
        documents=pages, embedding=embeddings, client_settings=chroma_settings
    )
```

**Comment by skeretna** [comment]
in your definition to OpenAIEmbeddings, you need to specify an embeddings model name
model=your_embedding_deployment_name

**Comment by baseplate77** [comment]
I am experience the same issue, I tried specifying the embedding function on the chroma client as well, but still the same issue

**Comment by akeybl** [comment]
I'm seeing the same issue.

**Comment by mlorenzon** [comment]
I have the same issue. The embedding function is defined and was running fine before I dockerized chromadb.

**Comment by tonisives** [comment]
chromadb has an issue where it's `list_collections` logs this error while it shouldn't. https://github.com/chroma-core/chroma/issues/484

**Comment by h3clikejava** [comment]
I have the same issue. 

db = Chroma(persist_directory='./db', embedding_function=OpenAIEmbeddings())
No embedding_function provided, using default embedding function: DefaultEmbeddingFunction https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

**Comment by sedgar03** [comment]
Any updates?

**Comment by cfa532** [comment]
I had a similar problem whereas I am using default embedding function of Chroma. After days of struggle, I found a partial solution. At first, I was using "from chromadb.utils import embedding_functions" to import SentenceTransformerEmbeddings, which produced the problem mentioned in the thread.

I happend to find a post which uses "from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings", a langchain package to get the embedding function and the problem is solved.

However, I want to use InstructorEmbeddingFunction recommened by Chroma, I am still looking for the solution.

**Comment by sanjayporwal02** [comment]
> I had a similar problem whereas I am using default embedding function of Chroma. After days of struggle, I found a partial solution. At first, I was using "from chromadb.utils import embedding_functions" to import SentenceTransformerEmbeddings, which produced the problem mentioned in the thread.
> 
> I happend to find a post which uses "from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings", a langchain package to get the embedding function and the problem is solved.
> 
> However, I want to use InstructorEmbeddingFunction recommened by Chroma, I am still looking for the solution.

facing the same issue, tried this import method but no luck

**Comment by alyhafez95** [comment]
Facing this issue as well

**Comment by vanessailana** [comment]
I have having this issue as well.

**Comment by nitinnat** [comment]
Facing the same issue with OllamaEmbeddings("llama2")

**Comment by tnguyenqh** [comment]
Are there any updates about this issue? I am still experienced this problem

**Comment by darrenrahnemoon** [comment]
Same issue here
