### ISSUE TITLE
Bug : could not parse LLM output: `{llm_output}`") when I run the same question several times

### ISSUE THREAD

**Issue by taweijm** [langchain-ai/langchain#2985]
I'm using these code :

llm=ChatOpenAI(temperature=0)
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
agent_chain = initialize_agent(tools, llm, agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION, verbose=True, memory=memory)

I run this line several times 

agent_chain.run(input="Hi, how are you today ?")

then these errors are show up

[agents/conversational/base.py](https://localhost:8080/#) in _extract_tool_and_input(self, llm_output)
     83         match = re.search(regex, llm_output)
     84         if not match:
---> 85             raise ValueError(f"Could not parse LLM output: `{llm_output}`")

**Comment by ProxyCausal** [comment]
Duplicate of #1707
