### ISSUE TITLE
CSV/Pandas Dataframe agent replying to questions irrelevant to data

### ISSUE THREAD

**Issue by AlvinNg89** [langchain-ai/langchain#3000]
CSV/Pandas Dataframe agent actually replies to question irrelevant to the data, this can be easily resolved by including an extra line in the prompt to not reply to questions irrelevant to the dataframe.

**Comment by azamiftikhar1000** [comment]
@AlvinNg89 Could you please share the code snippet or example of such case?

**Comment by AlvinNg89** [comment]
Hi @azamiftikhar1000,

I attach two image, one where the agent work as suppose when asked a relevant question. The other where it still replied with the right answer despite the information not being part of the data. When we added an extra line "Do not reply if the question is irrelevant" together with the question, it complied. However, this should be resolved on a prompt level instead of us having to reframe the context via the question.

Relevant question: 
![Relevant](https://user-images.githubusercontent.com/45703815/232394472-4df22d4a-1860-40c7-ac8e-7275683828cb.png)

Irrelevant question:
![Irrelevant](https://user-images.githubusercontent.com/45703815/232394527-30aafafe-f68f-49c2-b854-4c14e073db70.png)

**Comment by azamiftikhar1000** [comment]
@AlvinNg89  I tested using Chat GPT-4 and  It's not replying to questions irrelevant to data.
<img width="860" alt="Screenshot 2023-04-18 at 4 02 15 AM" src="https://user-images.githubusercontent.com/55012400/232624592-3f87406a-2ca7-4ac7-9c72-216437ab202f.png">
