### ISSUE TITLE
YoutubeLoader : Error: Exception while accessing title of https://youtube.com/watch?v=XXX. Please file a bug report at https://github.com/pytube/pytube

### ISSUE THREAD

**Issue by Gptify** [langchain-ai/langchain#3040]
The error is random, it only occurs sometimes.
`loader = YoutubeLoader.from_youtube_url(vidurl, add_video_info=True, language=lang)`

**Comment by Gptify** [comment]
Update : the problem is in : add_video_info=True

**Comment by KasunAb** [comment]
did you find a way to fix this ?

**Comment by sailor723** [comment]
some error. is there any fix? thanks

**Comment by cygkichi** [comment]
The cause appears to be pytube.https://github.com/pytube/pytube/issues/1586

You need modify
`yt = YouTube(f"https://www.youtube.com/watch?v={self.video_id}")`
to
`yt = YouTube(f"https://www.youtube.com/watch?v={self.video_id}", use_oauth=True, allow_oauth_cache=True)`

But, this requires browser authentication.

**Comment by shawnesquivel** [comment]
@cygkichi 
Thanks that fixed it. But I'm still getting a NoTranscript Error.

Is there a way to pass the language into the YoutubeLoader?

```
No transcripts were found for any of the requested language codes: ['en']

```

**Comment by cygkichi** [comment]
@shawnesquivel 


It looks like there are no English subtitles.
If you want to get non-English subtitles, you can do it by specifying them in from_youtube_url.

```
loader = YoutubeLoader.from_youtube_url('https://www.youtube.com/watch?v=xxxxx', language='ja')
```

**Comment by shawnesquivel** [comment]
Thanks @cygkichi !!
