### ISSUE TITLE
pinecone_hybrid_search doesn't work by following the documents.

### ISSUE THREAD

**Issue by ccccherrie** [langchain-ai/langchain#3043]
retriever = PineconeHybridSearchRetriever(embeddings=embeddings, index=index, tokenizer=CharacterTextSplitter)
result = retriever.get_relevant_documents(given_str)

gives TypeError: init() got an unexpected keyword argument 'padding'

with bm25_encoder
retriever = PineconeHybridSearchRetriever(embeddings=embeddings, index=index, tokenizer=CharacterTextSplitter , sparse_encoder=bm25_encoder)

it gives

ValidationError: 1 validation error for PineconeHybridSearchRetriever
sparse_encoder
extra fields not permitted (type=value_error.extra)

**Comment by Santiagowwi** [comment]
@lbsnrs  I saw that you fixed it, but
 is there a solution for langchain version==0.0.134 ??
