### ISSUE TITLE
Axios dependency forcing a downgrade on nextJS build. 

### ISSUE THREAD

**Issue by sachio222** [langchain-ai/langchain#3065]
Axios is at v 1.3.5, why does langchain set the dependency to major version 0? 

It is set to "axios": "^0.26.0",

Do we want: "axios": ">=0.26.0" ?

Does the whole world need to downgrade in order to use Langchain?

Or is this just me and my setup is screwed up somehow. I don't see anyone else making noise about it, so i'm a little concerned I have something wrong with what i'm working on. 

![image](https://user-images.githubusercontent.com/9384977/232681086-8eb28a33-c0e7-4ff1-b0e1-783efecbcd54.png)

**Comment by jpamorgan** [comment]
I'm having the same issue and cannot get it to work with nestjs

**Comment by m-p-d** [comment]
+1

If it helps get you part of the way you can override in package.json, e.g.:
```
  "overrides": {
    "langchain@^0.0.59": {
      "axios": "^1.3.3"
    }
  }
```
May help building projects that need a more recent axios version and some langchain functionality still works, but as soon as you run something that depends on an outdated axios interface it'll error..

**Comment by sachio222** [comment]
Also heard it is tied to the openai dependency which is also ^0.26. With the suggested override, you’ll still need to deal with openai as well.
