### ISSUE TITLE
Issue with ConversationSummaryBufferMemory pruning messages for non-in-memory chat message histories

### ISSUE THREAD

**Issue by joybro** [langchain-ai/langchain#3072]
https://github.com/hwchase17/langchain/blob/894c272a562471aadc1eb48e4a2992923533dea0/langchain/memory/summary_buffer.py#L57-L70

The ```ConversationSummaryBufferMemory``` class in ```langchain/memory/summary_buffer.py``` currently prunes chat_memory's messages using the ```List.pop()``` method (line 66). This approach works as expected for the in-memory implementation ```ChatMessageHistory```, where messages are stored as a simple List.

However, this method of pruning messages is not suitable for other implementations where messages are calculated output Lists, such as ```DynamoDBChatMessageHistory``` or ```RedisChatMessageHistory```. In these cases, the current implementation fails to prune messages as intended.

To address this issue, we may need to modify the ```BaseChatMessageHistory``` class to provide a unified interface for pruning messages, which can then be overridden as needed by specific implementations.

**Comment by k1ng** [comment]
Я так же сталкиваюсь с проблемой использования ConversationSummaryBufferMemory с FileChatMessageHistory. Саммари для истории никак не сохраняется и нигде не используется.

Так же я столкнулся с похожей проблемой при использовании ConversationTokenBufferMemory с FileChatMessageHistory и RedisChatMessageHistory описанной в   #5053 

Я новачок, но полагаю эти проблемы как-то связаны.

**Comment by k1ng** [comment]
I'm also facing the issue of using ConversationSummaryBufferMemory with FileChatMessageHistory. The summary for the history is not saved anywhere or used.

I also encountered a similar issue when using ConversationTokenBufferMemory with FileChatMessageHistory and RedisChatMessageHistory described in #5053 

I'm a newbie but I assume these issues are somehow related.

**Comment by Sameera2001Perera** [comment]
Im facing the similar issue with "MongoDBChatMessageHistory". [#21610](https://github.com/langchain-ai/langchain/issues/21610)
