### ISSUE TITLE
[feat] Create Memory, Chain and Agent Classes for Generative Characters

### ISSUE THREAD

**Issue by BeautyyuYanli** [langchain-ai/langchain#3087]
After reviewing the work done on https://github.com/hwchase17/langchain/pull/2859 and its accompanying examples, I propose creating Generative Characters as a set of langchain components. These components would include Memory, Chain, and Agent Classes.

- Memory: This includes the ability to retrieve documents from VectorStore using TimeWeightedVectorStoreRetriever, calculate their score, summarize them, add memory and fetch memory.
- Chain: This involves generating reactions and dialogue responses.
- Agent: I'm not entirely sure about this one. Since the chain can generate reactions, it may be able to use tools as well.

I would like to work on this. Any suggestions or help would be greatly appreciated.

@vowelparrot

**Comment by Ryangr0** [comment]
I'm watching this right now, maybe I can help?

**Comment by vowelparrot** [comment]
Thanks for opening this! If you have any drafts, I'd be happy to check them out. We're working on landing some changes in `langchain/experimental` to make them easier to build on while we distill the components into their appropriate locations.

We want to strike a proper balance of sharing the latest systems to use while ensuring the abstractions are suffiently reusable

See: https://github.com/hwchase17/langchain/pull/2878#issuecomment-1512410698 for a related comment
