### ISSUE TITLE
Agent SELF_ASK_WITH_SEARCH  does not work with ChatOpenAI models

### ISSUE THREAD

**Issue by rubensmau** [langchain-ai/langchain#3090]
Got a loop when asking for "What's the best BBQ in Kansas City"  . When added to the prompt - "say cannot answer,if you don´t know the answer " did not stop the loop.
The loop only stopped after blowing up the context length

On the other hand, if using OpenAI old models, it worked fine . Using  SerpAPIWrapper

**Comment by oliverjarvis** [comment]
I agree, I just stumbled into the very same issue. Also using SerpAPIWrapper.

**Comment by djpecot** [comment]
I think this may require some tuning to the chat prompt to work effectively

**Comment by nkov** [comment]
I've experienced the infinite loop, as well as `Could not parse output: Yes.` multiple times, which seems to be the first response from the SELF_ASK_WITH_SEARCH agent when it decides it will proceed with a search. Retrying the same prompt works eventually, it's kind of hit or miss.

**Comment by mykytamykhailenko** [comment]
I have a similar issue, but it throws `OutputParserException: Could not parse output:  No.`
