### ISSUE TITLE
Is Google PaLM integration in the pipeline? 

### ISSUE THREAD

**Issue by kailash-anantha** [langchain-ai/langchain#3101]
Is there any ETA on this new LLM integration?

**Comment by vowelparrot** [comment]
PRS are welcome if you'd like to make a suggestion!

**Comment by brotchie** [comment]
https://github.com/hwchase17/langchain/pull/3575 merged yesterday.

**Comment by THULiusj** [comment]
Hi, @brotchie, any samples of how to use the Google Cloud PaLM functions, like a chatbot sample ? And what's the Google API key? In Google Cloud, I only have the access token and the service account key?
