### ISSUE TITLE
Allow custom retry_decorator to be passed to the LLM

### ISSUE THREAD

**Issue by AnishPimpley** [langchain-ai/langchain#3109]
The retry decorator for ChatOpenAI is hardcoded [here](https://github.com/hwchase17/langchain/blob/d54c88aa2140f27c36fa18375f942e5b239799ee/langchain/chat_models/openai.py#L39)

Allow the user to supply a custom retry_decorator.

**Comment by AnishPimpley** [comment]
Users many want specific types of exceptions to be handled in specific ways, the current retry_decorator is limiting especially when different LLM hosts have different rate limits and exponential decay for subsequent requests.

**Comment by ShantanuNair** [comment]
@AnishPimpley Any update regarding this? Has this been addressed in future versions? I'm running through the codebase now to check myself
