### ISSUE TITLE
Missing new lines or empty spaces in refine default prompt.

### ISSUE THREAD

**Issue by Qualzz** [langchain-ai/langchain#3117]
I'm not sure if it's a typo or not but the default prompt in [langchain](https://github.com/hwchase17/langchain/tree/master/langchain)/[langchain](https://github.com/hwchase17/langchain/tree/master/langchain)/[chains](https://github.com/hwchase17/langchain/tree/master/langchain/chains)/[summarize](https://github.com/hwchase17/langchain/tree/master/langchain/chains/summarize)/[refine_prompts.py](https://github.com/hwchase17/langchain/tree/master/langchain/chains/summarize/refine_prompts.py) seems to miss a empty string or a `\n `

```
REFINE_PROMPT_TMPL = (
    "Your job is to produce a final summary\n"
    "We have provided an existing summary up to a certain point: {existing_answer}\n"
    "We have the opportunity to refine the existing summary"
    "(only if needed) with some more context below.\n"
    "------------\n"
    "{text}\n"
    "------------\n"
    "Given the new context, refine the original summary"
    "If the context isn't useful, return the original summary."
)
```

It will produce `refine the original summaryIf the context isn't useful` and `existing summary(only if needed)`

I could proabbly fix it with a PR ( if it's unintentionnal), but I prefer to let someone more competent to do it as i'm not used to create PR's in large projects like this.

**Comment by kwilson21** [comment]
Hmmm, this seems unintentional. I will spin up a PR to fix this

**Comment by Qualzz** [comment]
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/summarize/refine_prompts.py

I don't actively use langchain right now, but by looking at the file itself, it seems to miss a new line or an empty space

    "We have the opportunity to refine the existing summary"
    "(only if needed) with some more context below.\n"
    
    will result in " refine the existing summary(only if needed) [...] "
