### ISSUE TITLE
InvalidRequestError Must provide an engine ( gpt 4 azure open ai )

### ISSUE THREAD

**Issue by balaji-arun-s** [langchain-ai/langchain#3134]
<br>
I'm trying to integrate gpt 4 azure open ai with Langchain but when i try to use it inside ConversationalRetrievalChain it is throwing some error <be>

```
raise error.InvalidRequestError(\\n *~* 
openai.error.InvalidRequestError: Must provide an \'engine\' or
 \'deployment_id\' parameter to create a <class 
\'openai.api_resources.chat_completion.ChatCompletion\
```
<br>
but if I run standalone openai instance with Azure openai config it is working, I'm confused about whether langchain supports gpt 4 or if am I missing anything

**Comment by HelpNow-jaehyeong** [comment]
I have same error
