### ISSUE TITLE
Not able to use GPT4 model with AzureOpenAI from from langchain.llms

### ISSUE THREAD

**Issue by srithedesigner** [langchain-ai/langchain#3137]
### Discussed in https://github.com/hwchase17/langchain/discussions/3132

<div type='discussions-op-text'>

<sup>Originally posted by **srithedesigner** April 19, 2023</sup>
We used to use AzureOpenAI llm from langchain.llms with the text-davinci-003 model but after deploying GPT4 in Azure when trying to use GPT4, this error is being thrown: 
`Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>`

This is how we are initializing the model: 
```python
model = AzureOpenAI(
        streaming=streaming,
        client=openai.ChatCompletion(),
        callback_manager=callback,
        deployment_name= "gpt4",
        model_name="gpt-4-32k",
        openai_api_key=env.cloud.openai_api_key,
        temperature=temperature,
        max_tokens=max_tokens,
        verbose=verbose,
    )
```
How do we use GPT4 withe the AzureOpenAI chain? Is it currently being supported? or are we initializing it wrong?
</div>

**Comment by itaim** [comment]
Did you set?
```
openai.api_version = "2022-12-01"
openai.api_base = "https://your-domain.openai.azure.com"
openai.api_type = "azure"
```

**Comment by srithedesigner** [comment]
Yes, @itaim, We did set the following, 
```
    openai.api_base = our_openai_api_base
    openai.api_type = "azure"
    openai.api_version = "2023-03-15-preview"
 ```

**Comment by itaim** [comment]
Have you tried with curl? Could indicate whether the issue is with the deployment or API usage.

```
url https://example.openai.azure.com/openai/deployments/gpt-4/completions\?api-version\=2023-03-15-preview\\n  -H "Content-Type: application/json" \\n  -H "api-key: your_api_key" \\n  -d "{\n  \"prompt\": \"hello GPT\"\n}"\n
```

**Comment by srithedesigner** [comment]
It is throwing this error

```json
{
  "error": {
    "code": "OperationNotSupported",
    "message": "The completion operation does not work with the specified model, gpt-4-32k. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."
  }
}
```

But using the openai.chatCompletion() is working on the GPT4 model.

This works with the GPT3 deployment, but GPT4 is throwing this error. I should reach out to Azure support I guess, I don't think is an issue with langchain now.

**Comment by itaim** [comment]
chatgpt-3.5 on Azure supported the `prompt` argument regular text completions but could be that gpt4 requires the messages argument of chat endpoints:
Try:
```
curl https://example.openai.azure.com/openai/deployments/gpt-4-32k/completions?api-version=2023-03-15-preview \
  -H "Content-Type: application/json" \
  -H "api-key: your_api_key" \
  -d '{
  "messages": [
    {"role": "system", "content": "Assistant is a large language model trained by OpenAI."},
    {"role": "user", "content": "What's the difference between garbanzo beans and chickpeas?"}
  ]
}'
```

**Comment by jean1190** [comment]
Is gpt-4-32k model available yet?

**Comment by sheikalthaf** [comment]
@MakikoNomuraJTP yes when I use AzureChatOpenAI, it is working fine. Thanks for the suggestion.

**Comment by YanDav78** [comment]
Instead of using deployment_name parameter, change it to deployment_id

i.e. AzureOpenAI(deployment_id="######", model_name="gpt-4-32k", temperature=0)

and put there your deployment name value.

If you have the 8k model put model_name="gpt-4"

**Comment by sweetlilmre** [comment]
With Version: 0.0.165 and `AzureChatOpenAI` the minimal call that works for me is:

```
    llm = AzureChatOpenAI(
        deployment_name=os.getenv("DEPLOYMENT_ID_CHAT"),
        temperature=0,
    )
```

with a properly configured .env and `load_dotenv()`. `temperature` is obviously for user preference.

```
OPENAI_API_BASE="...."
OPENAI_API_TYPE="azure"
OPENAI_API_VERSION="2023-03-15-preview"
OPENAI_API_KEY="...."
DEPLOYMENT_ID_CHAT="...."
DEPLOYMENT_ID_EMBEDDING="...."
```

Replace ... with your appropriate base url, key and deployment ids.

**Comment by aidin-zadeh** [comment]
With version `0.0.315` this works for me:

```PYTHON
llm = AzureOpenAI(
    model_name="gpt-4",
    engine="gpt4",

)
```
