### ISSUE TITLE
RetrievalQA costs long time to get the answer

### ISSUE THREAD

**Issue by hifiveszu** [langchain-ai/langchain#3202]
I use vectore_db `Chroma` and langchain `RetrievalQA ` to build my docs bot, but every question costs about 16 ~ 17 seconds. 
someboby has any ideas? Thanks

here is my code

```python
embeddings = OpenAIEmbeddings()
vector_store = Chroma(persist_directory="docs_db", embedding_function=embeddings)

qa = RetrievalQA.from_chain_type(
    llm=ChatOpenAI(),
    chain_type="stuff",
    retriever=vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 1}),
    return_source_documents=True,
    verbose=True,
)

result = qa({"query": keyword})
```

I searched in langchain's docs but find no way. and I try count every step

```python

%%time
docs = vector_store.similarity_search(keyword, k=1)
db costs: 2.204489231109619s

%%time
chain = load_qa_with_sources_chain(ChatOpenAI(temperature=0), chain_type="stuff")
llm costs: 5.171542167663574s 
```

**Comment by alifanov** [comment]
I had a similar issue
The biggest delay was in response from OpenAI API coz it waits the whole answer (whole generation)
You could try to use stream=True to get first results faster

**Comment by hifiveszu** [comment]
> I had a similar issue The biggest delay was in response from OpenAI API coz it waits the whole answer (whole generation) You could try to use stream=True to get first results faster

Thanks for reply ：）
I have a self host chatgpt-web.Each time I send my message directly to openai, the server will reply almost within one second. 

So I don't know the details run in langchain's function when run in the following code
```python
result = llm_chain.run(context=context, question=question)
```
Is there any differences from directly request openai's API?

Now I will prefer to request openai's API ...

**Comment by alifanov** [comment]
I've tried to use OpenAI API from scratch - it was also slow for big texts in response

**Comment by hifiveszu** [comment]
> I've tried to use OpenAI API from scratch - it was also slow for big texts in response

using `stream=True` the call openai and response stream data out is the right answer : )

**Comment by sebacarabajal** [comment]
Where should the "stream=True" option be put? I can't find it in the langchain documentation

**Comment by alifanov** [comment]
https://python.langchain.com/en/latest/reference/modules/chat_models.html?highlight=streaming#langchain.chat_models.ChatOpenAI.streaming

**Comment by xiongwn** [comment]
> Where should the "stream=True" option be put? I can't find it in the langchain documentation

ChatOpenAI(temperature=0,streaming=True)
