### ISSUE TITLE
No module named 'langchain.document_loaders'

### ISSUE THREAD

**Issue by sssdjj** [langchain-ai/langchain#3210]
oduleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_13968\1686623477.py in <module>
----> 1 from langchain.document_loaders import UnstructuredFileLoader
      2 from langchain.embeddings.huggingface import HuggingFaceEmbeddings
      3 from langchain.vectorstores import FAISS

ModuleNotFoundError: No module named 'langchain.document_loaders'

**Comment by nassersaazi** [comment]
try 'pip install langchain'.

or you can clone the repo and install from source as indicated in the docs

**Comment by Anirudh257** [comment]
I was able to resolve this issue. Just update your python version to >= 3.10. Follow the instructions here: https://stackoverflow.com/questions/75907516/langchain-no-module-named-langchain-document-loaders

**Comment by Mike4Ellis** [comment]
In my case, updating python3 version to 3.8 is the only effective solution, and versions >=3.10 will conflict with faiss-gpu.

**Comment by nobodyme** [comment]
I have version `3.11.4` and still have this issue.

**Comment by dimaelzein** [comment]
Any alternative for Python 3.9 ?

**Comment by Sandeep-madhyastha** [comment]
> In my case, updating python3 version to 3.8 is the only effective solution, and versions >=3.10 will conflict with faiss-gpu.

I face the same issue as well, due to fiass-gpu I had to port down to Python3.10, Now I face langchain_community issue. Can you please assist on which Python version should be used to address these issues so that all the packages can be consumed

**Comment by QuynhTaVo** [comment]
> I was able to resolve this issue. Just update your python3 version to >= 3.10. Follow the instructions here: https://stackoverflow.com/questions/75907516/langchain-no-module-named-langchain-document-loaders

Mine was resolved using this solution

**Comment by mmoralesIG** [comment]
Hi. using python 3.13.9
same problem
