### ISSUE TITLE
Adding Time To Live on Redis Vector Store Index

### ISSUE THREAD

**Issue by Octforce** [langchain-ai/langchain#3213]
Is there a way we can add Time To live when storing vectors in Redis? If there isn't is there a plan to add it in the future?

**Comment by tylerhutcherson** [comment]
This is definitely possible (given Redis was first and foremost a cache)!

We are working on something like this. Would be interested in talking to you about dev UX for this feature.

**Comment by Octforce** [comment]
Yes I am available to chat!

**Comment by tylerhutcherson** [comment]
Shoot me a note at tyler.hutcherson@redis.com and let's discuss

**Comment by Octforce** [comment]
> Shoot me a note at [tyler.hutcherson@redis.com](mailto:tyler.hutcherson@redis.com) and let's discuss

I sent you an email via my personal mail. Richard.

**Comment by hatemalimam** [comment]
I see this feature very handy, after all redis revolves after caching, why is it marked as "not planned"?

**Comment by tylerhutcherson** [comment]
Future work on the Redis vector store implementation is happening here FYI:
https://github.com/langchain-ai/langchain-redis

Definitely NOT off the table!
