### ISSUE TITLE
Standardize input args for `conversational` and `conversational_chat` agents

### ISSUE THREAD

**Issue by tylermaran** [langchain-ai/langchain#3234]
The [conversational_chat](https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational_chat/base.py#L58) agent takes the following args for `create_prompt`
```py
def create_prompt(
        cls,
        tools: Sequence[BaseTool],
        system_message: str = PREFIX,
        human_message: str = SUFFIX,
        input_variables: Optional[List[str]] = None,
        output_parser: Optional[BaseOutputParser] = None,
    ) -> BasePromptTemplate:
```

While the [conversational](https://github.com/hwchase17/langchain/blob/master/langchain/agents/conversational/base.py#L46) agent takes the following:
```py
def create_prompt(
        cls,
        tools: Sequence[BaseTool],
        prefix: str = PREFIX,
        suffix: str = SUFFIX,
        format_instructions: str = FORMAT_INSTRUCTIONS,
        ai_prefix: str = "AI",
        human_prefix: str = "Human",
        input_variables: Optional[List[str]] = None,
    ) -> PromptTemplate:
```

Given the similarities in these agents, I would expect to pass the same args for initializing them. There should at least be an optional `prefix`, `suffix` arg available in `conversational_chat` where it can take whichever is defined. 

Ex:
```py
prefix_arg = prefix || system_message
suffix_arg = suffix || human_message
```

**Comment by bitnom** [comment]
I'm trying to use `ai_prefix` and `human_prefix` in a chat agent, which doesn't work/do anything.
