### ISSUE TITLE
`similarity_search` for OpenSearchVectorSearch does not pass authorization header to opensearch

### ISSUE THREAD

**Issue by aarora79** [langchain-ai/langchain#3270]
I am able to connect to Amazon OpenSearch cluster that has a username and password and ingest embeddings into but when I do a `docsearch.similarity_search` it fails with a 401 unauthorized error. I am able to connect to the cluster by passing the username and password as `http_auth` tuple.

I verified by putting traces in `opensearchpy/connection/http_urllib3.py` that the `authorization` field in the header is indeed not being sent and so the open search cluster returns a 401 unauthorized error.
Here is the trace:
```headers={'connection': 'keep-alive', 'content-type': 'application/json', 'user-agent': 'opensearch-py/2.2.0 (Python 3.10.8)'}```

I verified that a opensearch client created in the same notebook is able to query the opensearch cluster without any problem and also that it does sent the authorization field in the HTTP header.
Langchain version is 0.0.144
opensearch-py version is 2.2.0

**Comment by naveentatikonda** [comment]
@aarora79 Thank you for creating this github issue. Will check and get back to you.

**Comment by yunfeilu92** [comment]
potential fix as following https://github.com/hwchase17/langchain/pull/3416

**Comment by aarora79** [comment]
Verified that this was fixed in 0.0.149.
