### ISSUE TITLE
Timeout when running hugging face LLMs for ConversationRetrivalChain

### ISSUE THREAD

**Issue by parzival1l** [langchain-ai/langchain#3275]
I am getting the following error when trying to query from a ConversationalRetrievalChain using HuggingFace. 
` ( a ValueError: Error raised by inference API: Model stabilityai/stablelm-tuned-alpha-3b time out `

I am query the model using a simple LLMChain, but querying on documents seems to be the issue, any idea ? 

This is the code : 

```
from langchain import HuggingFaceHub
llm = HuggingFaceHub(repo_id="stabilityai/stablelm-tuned-alpha-3b" , model_kwargs={"temperature":0, "max_length":64})
qa2 = ConversationalRetrievalChain.from_llm(llm,
                                    vectordb.as_retriever(search_kwargs={"k": 3}), return_source_documents=True)
chat_history = []
query = "How do I load users from a thumb drive."
result = qa2({"question": query, "chat_history": chat_history})
```

vectordb is coming from Chroma.from_documents (using OpenAI embeddings on a custom pdf) .

**Comment by ygorbalves** [comment]
Hi!
I have this problem too and I can solve this with increasing the chunk size on the model:
llm=HuggingFaceHub(repo_id="google/flan-t5-xl", model_kwargs={"temperature":0, "max_length":512})

With chunksize = 5000 in the VectorstoreIndexCreator() the model can run.

Depending on the LLM this length limit is different, so is important take care in this sizes.
I recommend use others LLM's or adjust the chunksize for run the 'stabilityai/stablelm-tuned-alpha-3b'.

**Comment by YHOYO** [comment]
HI, 

actually i have the same issue. 

I change the chunksize and also the llm to 

`HuggingFaceHub(repo_id="togethercomputer/GPT-NeoXT-Chat-Base-20B", model_kwargs={"temperature":0, "max_length":500})`

I got the same Timeout  or Service Unavailable

thanks for any helf

**Comment by bcrestel** [comment]
I don't think this is related to `ConversationRetrivalChain` as I'm seeing the same issue when directly prompting a `HuggingFaceHub` object. For instance, when I do:
```
repo_id = "google/flan-t5-xl"
llm_hf = HuggingFaceHub(repo_id=repo_id, model_kwargs={"temperature":0, "max_length":128})
print(llm_hf(text))
```
It hangs for a while then returns the timeout error. 
I'll ping HuggingFace's API directly to check whether the issue comes from HuggingFace or `HuggingFaceHub`.

**Comment by andymiller-og** [comment]
This is happening with me... I was able to get `stabilityai/stablelm-base-alpha-3b` to return something. But everything else is stuck
just keep on getting `ValueError: Error raised by inference API: Model stabilityai/stablelm-tuned-alpha-7b time out`

Here is my basic code to test that simply times out: 
```
import os

from langchain import HuggingFaceHub
from langchain import PromptTemplate, LLMChain

from utilities import load_api_key

os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

repo_id = "stabilityai/stablelm-tuned-alpha-7b"
# repo_id = "stabilityai/stablelm-tuned-alpha-3b"
# repo_id = "stabilityai/stablelm-base-alpha-3b"
# repo_id = "google/flan-t5-xl"
llm = HuggingFaceHub(repo_id=repo_id, model_kwargs={"temperature": 0, "max_length": 64},
                     huggingfacehub_api_token=load_api_key("HUGGINGFACEHUB_API_TOKEN"))

template = """Question: {question}

Answer: """
prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=llm)

question = "Who won the FIFA World Cup in the year 1994? "

print(llm_chain.run(question))
```

**Comment by tjb4578** [comment]
This is happening for me as well.  [This Colab notebook for question answers](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbElRLUZXRUR0RkFESjhhOXV5dWREZEtKYVA5UXxBQ3Jtc0tuSjVfUTZndUxiTnJVbS1OcE1fSWlIQUxOZ1VUOUM3dVFuU3VINVRvUGM1Rkk1Wlp4ZTJyZUpDbTNFT2Vrbzh0YzZMZHV6eGV3RWFzYndocV9rWl9jQWh5VFdYWllEUzl2b3VWUHJPQURaRmRJMFBCaw&q=https%3A%2F%2Fcolab.research.google.com%2Fdrive%2F1NaEyuFWCkDtkufHIsWQhfgPLHybXeYA1%3Fusp%3Dsharing&v=wrD-fZvT6UI) worked for me a few days ago, but now when I enter a new query in cell 14 and run it, it will result in a timeout.

**Comment by phdykd** [comment]
is there any solution yet?

from langchain.chains import RetrievalQA
chain = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=index.vectorstore.as_retriever(search_kwargs={"k": 1}), 
                                    input_key="question")

ValueError: Error raised by inference API: Model google/flan-t5-xl time out

**Comment by ecekvlci** [comment]
Having the same issue too

# repo_id = "stabilityai/stablelm-tuned-alpha-3b"
# repo_id = "stabilityai/stablelm-base-alpha-3b"
# repo_id = "google/flan-t5-xl"

llm = HuggingFaceHub(repo_id=repo_id, 
                      huggingfacehub_api_token = HUGGINGFACEHUB_API_TOKEN, 
                      model_kwargs={"temperature":0, "max_length":64})

chain = load_qa_chain(llm, chain_type="stuff")
chain.run(input_documents=docs, question=query, raw_response=True)

**Comment by pradosh-abd** [comment]
+1

**Comment by phdykd** [comment]
Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).

**Comment by chaitanya2593** [comment]
Even I am having the same issue. Thanks @phdykd for the workaround , But do we know the root cause of this issue.
Thanks

**Comment by nkrefman** [comment]
I think I am having the same problem, but I'm not getting a timeout message.  It's just hanging for a long time.  I'm using Replit.

**Comment by pradosh-abd** [comment]
flan-small is working but as expected output is not great. Flan-XXL is working but max_length of 512 makes it harder to pass few shot template difficult and without this answers aren't that good. 

I observed call is getting stuck in ssl.py. Will update if anything is found. Also appreciate any help on this.

**Comment by spinning27** [comment]
> This is happening for me as well. [This Colab notebook for question answering](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbElRLUZXRUR0RkFESjhhOXV5dWREZEtKYVA5UXxBQ3Jtc0tuSjVfUTZndUxiTnJVbS1OcE1fSWlIQUxOZ1VUOUM3dVFuU3VINVRvUGM1Rkk1Wlp4ZTJyZUpDbTNFT2Vrbzh0YzZMZHV6eGV3RWFzYndocV9rWl9jQWh5VFdYWllEUzl2b3VWUHJPQURaRmRJMFBCaw&q=https%3A%2F%2Fcolab.research.google.com%2Fdrive%2F1NaEyuFWCkDtkufHIsWQhfgPLHybXeYA1%3Fusp%3Dsharing&v=wrD-fZvT6UI) worked for me a few days ago, but now when I enter a new query in cell 14 and run it, it will result in a timeout.

Yes. I got the same error:

`ValueError: Error raised by inference API: Model google/flan-t5-xl time out`

Tried other LLMs as well, same error.

**Comment by iriscortex** [comment]
I also had similar errors with various flan llm's. Adding max length sorted out timeout errors.

```python
llm_hf = HuggingFaceHub(
        repo_id="google/flan-t5-xxl",
        model_kwargs={"temperature":0.9,"max_length":64 }
)
```

**Comment by elvinagam** [comment]
for some reason, ```max_length``` does not make difference with t5-xl time-out. Anyways, t5-xxl works for now.

**Comment by philmui** [comment]
I have the same issue for a variety of models with various temperatures & max_length.  I wonder if it has to do with HuggingFace limiting API calls from a single IP?

**Comment by elvinagam** [comment]
@philmui I don't think this error is intentional to limit the usage or anything. Obviously, handling LLMs in scale might potentially bring resource problems. Better to open the same issue in HF repo as well so that they are aware.

**Comment by AlexRoman938** [comment]
I got the same problem with "google/flan-t5-xl" :/

**Comment by Abe410** [comment]
Getting same issue for StableLM, FLAN, or any model basically.

I utilized the HuggingFacePipeline to get the inference done locally, and that works as intended, but just cannot get it to run from HF hub.

Any idea how to solve this?

If I get a dedicated endpoint, can that be used with Langchain? If so, how? There does not seem to be a URL parameter that I can enter, only `repo_id` or model name.

**Comment by yomhb** [comment]
google/flan-t5-xxl is working for me, although i had to also set temprature to a minimum of 0.1 to get it to work.
`llm=HuggingFaceHub(repo_id="google/flan-t5-xxl", 
                                        model_kwargs={"temperature":0.1, 
                                                      "max_length":64}))`

**Comment by yitao416** [comment]
You need to upgrade your hugging face account to Pro version to host the LLM for inference.

**Comment by UserHIJ** [comment]
@yitao416  wins. All problems I had with these LLMS vanished with this . 
But to be clear, the answers it gives you are super short . But it WORKS. 
Bad on HF for not making the Pro requirement clearer.

**Comment by Abe410** [comment]
To not get truncated answers, you have to change the call method in the
relevant class in langchain

**Comment by kuxall** [comment]
ValueError: Error raised by inference API: Input validation error: `inputs` tokens + `max_new_tokens` must be <= 1512. Given: 3476 `inputs` tokens and 20 `max_new_tokens`

This happens when i upload pdf file of size 1 MB. How to resolve this issue?

**Comment by HashemAlsaket** [comment]
Salesforce XGen model hangs for me as well as all Stability AI LLMs. Perhaps limits should be printed?

**Comment by Wauplin** [comment]
Hi everyone, maintainer of `huggingface_hub`'s library here :wave:

Langchain's [current implementation](https://github.com/hwchase17/langchain/blob/master/langchain/llms/huggingface_hub.py#L54) relies on [InferenceAPI](https://huggingface.co/docs/api-inference/index). This is a free service from Huggingface to help folks quickly test and prototype things using ML models hosted on the Hub. It is not specific to LLM and is able to run a large variety of models from `transformers`, `diffusers`, `sentence-transformers`,.... While this service is free for everyone, different rate limits apply to unregistered, registered  and PRO users. However, the execution time is supposed to be the same no matter the plan (i.e. either you get a HTTP 429 Rate limit, either the request is processed correctly).

That being said, InferenceAPI is NOT meant to be a production-ready product. As said before, its primary goal is to allow users to quickly test models. Only models of a "small-enough" size can be hosted on-demand in the InferenceAPI infrastructure. In the context of LLMs, this constraint makes most models unavailable. We still support a manually curated list of first-class open source LLMs (`bigcode/santacoder`, `OpenAssistant/oasst-sft-1-pythia-12b`, `tiiuae/falcon-7b-instruct`, `timdettmers/guanaco-33b-merged` to name a few). The list of running LLMs can be found [here](https://api-inference.huggingface.co/framework/text-generation-inference). In the backend LLMs are running on our [text-generation-inference framework](https://github.com/huggingface/text-generation-inference/tree/main).

If one need a production-ready environment, they would need to run on our [Inference Endpoints](https://huggingface.co/docs/inference-endpoints/index) solution. This is a paid service to run models (including LLMs) on a dedicated auto-scaling infrastructure managed by Huggingface. Any model from the Hub can be loaded. 

---

Now that the difference between InferenceAPI and Inference Endpoints is more clear, let's dig in this issue more specifically. Langchain depends on the `InferenceAPI` client from `huggingface_hub`. This client will soon be deprecated in favor of `InferenceClient`. This later client is more recent and can handle both InferenceAPI, Inference Endpoint or even AWS Sagemaker solutions. Implementation is meant to be easier to use for end users, especially with automatic parsing of input/output for each task.

What I would suggest is to rewrite the [`HuggingFaceHub(LLM)`](https://github.com/hwchase17/langchain/blob/master/langchain/llms/huggingface_hub.py#L54) class in langchain to use the new [`text-generation`](https://huggingface.co/docs/huggingface_hub/package_reference/inference_client#huggingface_hub.InferenceClient.text_generation) task. A migration guide can be found [here](https://huggingface.co/docs/huggingface_hub/guides/inference). The advantage for the end user would be a better handling of timeouts, a better handling of inputs and the possibility to switch from InferenceAPI to InferenceEndpoint (or any url-based) solutions depending on the use case (prototyping vs production-ready).

If anyone wants to pick this topic, please let me know. I'd happy to answer questions and review a PR if requested! :hugs:

**Comment by MatousEibich** [comment]
@Wauplin Hello, thanks for a great answer! I want to play around with llama-2, not creating a production grade app (yet). Is it possible without setting up cloud compute and/or Inference Endpoints?

**Comment by Wauplin** [comment]
@MatousEibich Best way to test the 70B llama2 without setting anything is to go to https://hf.co/chat/ and select `meta-llama/Llama-2-70b-chat-hf` model :)

**Comment by angel-luis** [comment]
@Wauplin I’ve ended up here because I’m having troubles using the inference API, just for following the first tutorial provided in the LangChain handbook that can be find from the official documentation: https://python.langchain.com/docs/additional_resources/tutorials

The code provided in the handbook is not working anymore. Google Colab throws an error.
```python
from langchain import HuggingFaceHub, LLMChain

# initialize Hub LLM
hub_llm = HuggingFaceHub(
    repo_id='google/flan-t5-xl',
    model_kwargs={'temperature':1e-10}
)

# create prompt template > LLM chain
llm_chain = LLMChain(
    prompt=prompt,
    llm=hub_llm
)

# ask the user question about NFL 2010
print(llm_chain.run(question))

So it would be nice to fix this just for all the people following the handbook, I think.

**Comment by Wauplin** [comment]
@angel-luis Not familiar with the codebase here but would be happy to review a PR if someone wants to fix it :) I described in [this comment](https://github.com/langchain-ai/langchain/issues/3275#issuecomment-1630855785) the main steps to follow from a Hugging Face side :)

**Comment by angel-luis** [comment]
@jamescalam I quote you because it's related about your tutorial: https://www.pinecone.io/learn/series/langchain/langchain-intro/ (that currently isn't working)

**Comment by SID262000** [comment]
Can someone please help me understand the difference between max_length vs max_token. There seems to be a lot of biased opinions over the internet.

I would also like to know in case there's a way by which we can increase the number of words returned using RetrievalQA.
Many Thanks for your inputs!

**Comment by leofab** [comment]
> Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).

This one worked out really fine! Thx a lot!!

**Comment by SID262000** [comment]
> > Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).
> 
> This one worked out really fine! Thx a lot!!

Just out of curiosity, does this model work well for Retrieval purposes

**Comment by leofab** [comment]
> > > Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).
> > 
> > 
> > This one worked out really fine! Thx a lot!!
> 
> Just out of curiosity, does this model work well for Retrieval purposes

There are some repos specifically designed to retrievals

**Comment by SID262000** [comment]
> > > > Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).
> > > 
> > > 
> > > This one worked out really fine! Thx a lot!!
> > 
> > Just out of curiosity, does this model work well for Retrieval purposes
> 
> There are some repos specifically designed to retrievals

Thanks for the update. Can you please help me with a couple of free ones available for retrieval purposes

**Comment by xsqian** [comment]
ValueError: Error raised by inference API: Model *** time out
I got this error message with many models from HF. Is there any workaround for this issue?

**Comment by SID262000** [comment]
@xsqian I would be more than happy to discuss and brainstorm potential alternatives and solutions around the same

**Comment by xsqian** [comment]
@ SID262000 
may be caused by the size of the model since it takes a long time to download a large-sized model. There is an option of 
`cache=True`
but I wonder if we can download the model to a cache dir beforehand. I will be happy to direct message you for discussion.

**Comment by SID262000** [comment]
I agree with you, @xsqian regarding the extra time it takes to download the model but that's just for the very first time, even if we don't provide the cache flag.

Yes, please feel free to DM me in whichever way possible, appreciate it!

**Comment by avestamh** [comment]
> Use this one: google/flan-t5-xxl and temperature more than 0. (Such as 0.7, 0.5, 1).

Thank you, this worked for me.

**Comment by Niyi1974** [comment]
When running the following code, SSL Certification Verification Failed was returned:

from langchain.llms import HuggingFaceHub
import os

os.environ[“HUGGINGFACEHUB_API_TOKEN”] = “API_key_here”

llm = HuggingFaceHub(repo_id = “google/flan-t5-large”)

our_query = “What is the currency of Nigeria?”

completion = llm(our_query)

print(completion)
