### ISSUE TITLE
Question: How to save index created using VectorstoreIndexCreator from 3 loaders

### ISSUE THREAD

**Issue by daxeel** [langchain-ai/langchain#3278]
Here is my simple code

```master_index = VectorstoreIndexCreator().from_loaders([csv_loader, casestudy_loader, web_loader])```
```query = "what was the location of adani case study"```
```r = master_index.query_with_sources(query, llm=OpenAI(model_name="gpt-3.5-turbo", temperature=0.7))```
```print(r)```

I want to save this index to disk like llma-index and load this from disk make queries. 

Whats the best way to achieve this?

**Comment by blackhu** [comment]
save index:

`index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory":"./custom_save_dir_path"}).from_loaders([loader])`


but i don't know,how to loader this index.

**Comment by daxeel** [comment]
Thanks for helping. I ll check and respond to this thread accordingly

**Comment by daxeel** [comment]
@blackhu Sving works. How to load from disk and use it for querying?
