### ISSUE TITLE
use openaicallback with ChatOpenAI

### ISSUE THREAD

**Issue by artt28** [langchain-ai/langchain#3283]
I'm trying to track openai usage. but this is not working for ChatOpenAI class, 

I guess  using OpenAI class(which is subclass of llm) might be a solution,

but bit worried because of the depreciation warning 

`UserWarning: You are trying to use a chat model. This way of initializing it is no longer supported. Instead, please use: `from langchain.chat_models import ChatOpenAI``

**Comment by KindYAK** [comment]
One alternative for now is
chat = ChatOpenAI(...)
messages = [...]
result = chat.generate([messages])
result.llm_output # this will contain usage information
