### ISSUE TITLE
'ConnectionTimeout: Connection timed out' error while using elasticsearch vectorstore in ConversationalRetrievalChain chain.

### ISSUE THREAD

**Issue by bharadwaj-kg** [langchain-ai/langchain#3292]
Most of the times it works fine and gives answers to questions. But, sometimes it raises the following error.

File ~\Anaconda3\envs\nlp_env\lib\site-packages\elastic_transport\_node\_http_urllib3.py:199, in Urllib3HttpNode.perform_request(self, method, target, body, headers, request_timeout)
    191         err = ConnectionError(str(e), errors=(e,))
    192     self._log_request(
    193         method=method,
    194         target=target,
   (...)
    197         exception=err,
    198     )
--> 199     raise err from None
    201 meta = ApiResponseMeta(
    202     node=self.config,
    203     duration=duration,
   (...)
    206     headers=response_headers,
    207 )
    208 self._log_request(
    209     method=method,
    210     target=target,
   (...)
    214     response=data,
    215 )

ConnectionTimeout: Connection timed out

**Comment by blazickjp** [comment]
Elastic has a default timeout of 30 seconds. I think we need to add **kwargs to calls to enable changing this input.

**Comment by mirodrr** [comment]
Is it possible to change this timeout value?
