### ISSUE TITLE
Installing takes wayyyyyy to long for some reason

### ISSUE THREAD

**Issue by shroominic** [langchain-ai/langchain#3302]
![Screenshot 2023-04-21 at 16 38 34](https://user-images.githubusercontent.com/34897716/233664176-29189983-ed8f-46ae-953c-8fcf0fa37a5c.png)

**Comment by Ryangr0** [comment]
It needs to build a lot of things for this to work. It's normal behavior. Looking at this you seem to be using docker so this step should get cached anyway.
