### ISSUE TITLE
Integration with Azure Cognitive Search

### ISSUE THREAD

**Issue by dev2049** [langchain-ai/langchain#3317]

**Comment by lppier** [comment]
This would be great - I'm building an enterprise chat but want to extrapolate on this eventually to add agents, etc. using langchain.

**Comment by UmerHA** [comment]
Hey people, I'm working on this - see: https://github.com/hwchase17/langchain/compare/master...UmerHA:langchain:master
Will open a PR when I've added integration tests.

@vowelparrot iiuc, you're the maintainer for tools/toolkits and therefore receivers. Could you assign this issue to me?

Thanks!

**Comment by finnless** [comment]
This can be closed since #4406 was merged

**Comment by UmerHA** [comment]
fyi @leo-gan This issue can be closed as it's completed
