### ISSUE TITLE
"from langchain.cache import SQLiteCache" not working after migrating from OpenAI to ChatOpenAI

### ISSUE THREAD

**Issue by GeiserX** [langchain-ai/langchain#3325]
Hey, 

I'm trying to get the cache to work after swapping the following code:
```python
from langchain.llm import OpenAI
```
to
```python
from langchain.chat_models import ChatOpenAI
```
And using the new object in the code. But it's not working. I haven't modified my caching code:
```python
from langchain.cache import SQLiteCache
langchain.llm_cache = SQLiteCache(database_path="../dbs/langchain.db")
```
I updated the code because I saw some warnings that OpenAI was deprecated.

**Comment by czuo0303** [comment]
> Hey,
> 
> I'm trying to get the cache to work after swapping the following code:
> 
> ```python
> from langchain.llm import OpenAI
> ```
> 
> to
> 
> ```python
> from langchain.chat_models import ChatOpenAI
> ```
> 
> And using the new object in the code. But it's not working. I haven't modified my caching code:
> 
> ```python
> from langchain.cache import SQLiteCache
> langchain.llm_cache = SQLiteCache(database_path="../dbs/langchain.db")
> ```
> 
> I updated the code because I saw some warnings that OpenAI was deprecated.

I found a possible solution from the release note of gptcache.
`
from langchain.chat_models import ChatOpenAI
from gptcache import cache
from gptcache.adapter.langchain_models import LangChainChat

def get_msg(data, **_):
    return data.get("messages")[-1].content

cache.init(
    pre_embedding_func=get_msg,
)
chat = LangChainChat(chat=ChatOpenAI(temperature=0))
`

**Comment by czuo0303** [comment]
> Hey,
> 
> I'm trying to get the cache to work after swapping the following code:
> 
> ```python
> from langchain.llm import OpenAI
> ```
> 
> to
> 
> ```python
> from langchain.chat_models import ChatOpenAI
> ```
> 
> And using the new object in the code. But it's not working. I haven't modified my caching code:
> 
> ```python
> from langchain.cache import SQLiteCache
> langchain.llm_cache = SQLiteCache(database_path="../dbs/langchain.db")
> ```
> 
> I updated the code because I saw some warnings that OpenAI was deprecated.

I found a possible solution from the release note of gptcache.
```
from langchain.chat_models import ChatOpenAI
from gptcache import cache
from gptcache.adapter.langchain_models import LangChainChat

def get_msg(data, **_):
    return data.get("messages")[-1].content

cache.init(
    pre_embedding_func=get_msg,
)
chat = LangChainChat(chat=ChatOpenAI(temperature=0))
```

**Comment by ChasakisD** [comment]
Same issue here

**Comment by tho-nguyen-amili** [comment]
Same here

**Comment by Erliz** [comment]
Deprication note is because you use chat model like `gpt-3.5-turbo` with BaseModel instead of text model like `text-davinci-003`.
This issue is dulpicate of #1644, comments there have workaround of caching ChatModel
