### ISSUE TITLE
(windows) LlamaCpp model keeps running without returning nothing

### ISSUE THREAD

**Issue by fcalabrow** [langchain-ai/langchain#3330]
Hello. I'm using LlamaCpp in Windows 10 and I'm having the following problem.

Whenever I try to prompt a model (no mather if I do it throughout langchain or directly, with the `generate` method), although the model seems to load correctly, it stays running without returning nothing, not even an error (and I'm forced to restart the kernel). This happens when running the code on a Jupyter Notebook and also on a py file.
```
from langchain.llms import LlamaCpp
llm = LlamaCpp(model_path="models/ggml-model-q4_1.bin")
# output:
# AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 

from langchain import PromptTemplate, LLMChain
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=llm)
question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"

llm_chain.run(question)
# nothing happens
```
I tried with several models and it is the same. Also setting `f16_kv` to True.

Any ideas?

**Comment by shayneoneill** [comment]
Llama has a tiny buffer (2048 I think) so it pretty rapidly runs out of space.
