### ISSUE TITLE
set the temperature value to 0, but the response results are different for each run

### ISSUE THREAD

**Issue by yaohongfenglove** [langchain-ai/langchain#3343]
Hi, I set the temperature value to 0, but the response results are different for each run. If I use the native openai SDK, the result of each response is the same.

```
import os

from langchain import OpenAI


def main():
    os.environ["OPENAI_API_KEY"] = config.get('open_ai_api_key')

    llm = OpenAI(temperature=0)

    answer = llm("给小黑狗取个名字").strip()

    print(f"{answer}")

if __name__ == '__main__':
    main()
```

output:

![image](https://user-images.githubusercontent.com/71106576/233771082-635c4900-1d40-4bd0-8ba8-10dfcf8d3044.png)

![image](https://user-images.githubusercontent.com/71106576/233771117-7da8c017-1643-4090-8010-809c1f108718.png)

**Comment by nlassaux** [comment]
Hi there, this is expected from LLM, you should check that [thread](https://community.openai.com/t/a-question-on-determinism/8185) to learn more about this unavoidable issue.

**Comment by zeyger** [comment]
No, this is not expected from openai gpt.


Here's a code snippet that you could possibly try to and see for yourself:
```
def run(query):
    template = f"""
    Answer the following: {query}
    """
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": template}
        ],
        temperature=0
    )
    return completion.choices[0].message["content"]

query = 'why is the sky blue'
run(query)
```

It provides the same output every time for the same input.

The reason for having different output values for langchain was a bug that temperature was set on langchain side, but was not passed to openai api. This behavior can be observed in version 0.0.131

```
DEBUG:openai:message='Request to OpenAI API' method=post path=https://api.openai.com/v1/chat/completions
DEBUG:openai:api_version=None data='{"messages": [{"role": "user", "content": "Why is the sky blue?"}], "model": "gpt-3.5-turbo", "max_tokens": null, "stream": false, "n": 1}' message='Post details'
DEBUG:urllib3.util.retry:Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
```

**Comment by chrislrobert** [comment]
I'm observing similar behavior: with temperature set to 0 in the OpenAI API, results are reasonably consistent — but not with temperature=0 in langchain. Is the issue that 0 is being interpreted as "default"? If so, is 0.00001, e.g., a reasonable work-around?

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。

**Comment by simonedstrom96** [comment]
Is there a fix for this @zeyger ?

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。

**Comment by zeyger** [comment]
@simonedstrom96 temperature not being passed was fixed [in this PR](https://github.com/langchain-ai/langchain/pull/2558). Using any langchain version above [v0.0.135](https://github.com/langchain-ai/langchain/releases/tag/v0.0.135) should solve this issue

**Comment by yaohongfenglove** [comment]
姚宏锋已收到您的来信，谢谢。
