### ISSUE TITLE
Add update method on vectorstores

### ISSUE THREAD

**Issue by vyeevani** [langchain-ai/langchain#3354]
I am building a chain to analyze codebases. This involves documents that's constantly changing as the user modifies the files. As far as I can see, there doesn't seem to be a way to update the embeddings that are saved in vector stores once they have been embedded and submitted to the backing vectorstore.

This appears to be possible at least for chromaDB based on: (https://docs.trychroma.com/api-reference) and (https://github.com/chroma-core/chroma/blob/79c891f8f597dad8bd3eb5a42645cb99ec553440/chromadb/api/models/Collection.py#L258).

**Comment by vyeevani** [comment]
Wrote the following to address this specifically for chromaDB: https://github.com/vyeevani/langchain/tree/vyeevani/update-vectorstore-entry-chromadb

**Comment by trancethehuman** [comment]
I think you might be able to query your documents, embed a new one, and add it back into the database.

**Comment by rick2047** [comment]
I have been working on something similar. But I was taking a more low level approach like file tools. Can the chroma db function insert the code in the right place? That would be awe

**Comment by AvikantSrivastava** [comment]
Hey folks, I am also working on a similar problem
@vyeevani did you get a solution?

**Comment by sd3ntato** [comment]
is this dead? not optimal to delete the old vector store object everytime a refresh is needed...
