### ISSUE TITLE
Wolfram Alpha wasn't able to answer it for valid inputs

### ISSUE THREAD

**Issue by gigagiova** [langchain-ai/langchain#3357]
Hi, I am building my agent, and I would like to make this query to wolfram alpha "Action Input: √68,084,217 + √62,390,364", but I always get "Wolfram Alpha wasn't able to answer it".

Why is that? When I use the Wolfram app, it can easily solve it.
Thanks in advance, 
Giovanni

**Comment by prateekkeshari** [comment]
+ 1 is tehre a solution to this?

**Comment by cfddb** [comment]
Agreed! Same thing for me. Is there a solution to this?

**Comment by MrGNSS** [comment]
Agreed! Same thing for me. Is there a solution to this?

**Comment by kashirin-dm** [comment]
Same

**Comment by nqthiep** [comment]
Agreed! Same thing for me.
