### ISSUE TITLE
QA chain is not working properly

### ISSUE THREAD

**Issue by tron19920125** [langchain-ai/langchain#3373]
Hello everyone, 
I have implemented my project using the Question Answering over Docs example provided in the tutorial. I designed a long custom prompt using load_qa_chain with chain_type set to stuff mode. However, when I call the function "chain.run", the output is incomplete. 
Does anyone know what might be causing this issue?
Is it because the token exceed the max size ?
`llm=ChatOpenAI(streaming=True,callback_manager=CallbackManager([StreamingStdOutCallbackHandler()]),verbose=True,temperature=0,openai_api_key=OPENAI_API_KEY)`
`chain = load_qa_chain(llm,chain_type="stuff")`
`docs=docsearch.similarity_search(query,include_metadata=True,k=10)`
`r= chain.run(input_documents=docs, question=fq)`

**Comment by nikunjy** [comment]
I have the same problem.  I think the documents are chunked properly. But this chain probably merges all the text from the docs all in one call.

**Comment by nikunjy** [comment]
Yup. I tested it. 
I only included docs and part of the last doc upto the content limit.

**Comment by SherL0cked** [comment]
Check https://docs.langchain.com/docs/components/chains/index_related_chains

## For stuff:
Cons: Most LLMs have a context length, and for large documents (or many documents) this will not work as it will result in a prompt larger than the context length.

Try other types like map_reduce might work

**Comment by pybergonz** [comment]
same problem here.

I get empty output even if i pass a single small document to the chain. Have tried also with map_reduce.

```
chain = load_qa_chain(local_llm, chain_type="map_reduce")
chain.run(input_documents=[docs[0]], question=query)
```

output:

`Out[69]: ''`

**Comment by luoqingming110** [comment]
same question
