### ISSUE TITLE
How to action when output isn't finished

### ISSUE THREAD

**Issue by wenfengwang** [langchain-ai/langchain#3386]
sometimes, when we ask LLMs a question like writing a document  or a piece of code for a specified problem, the output may be too long, when we use a UI interface like ChatGPT, we can use the prompt like 
```bash
...
if you have given all content, please add the 'finished' at the end of the response. 
if not, I will say 'continue', then please continue to give me the reaming content.
```
to get all content by seeing if we should let LLMs continue to print content. **Does anyone know how to achieve this by LangChain?** 

I'm not sure if LangChain supports this, if not, and if someone is willing to give me some guides on how to do this in LangChain, I'll be happy to create a PR to solve it.

**Comment by wenfengwang** [comment]
I have looked into history issues and official docs, but still know how to do it.

**Comment by MichalDulemba** [comment]
It works in similar way:
output = chatgpt_chain.predict(human_input="continue") and in the template
prompt = PromptTemplate(
    input_variables=["history", "human_input"], 
    template=template
)

**Comment by MichalDulemba** [comment]
Just have no idea how to verify if necessary. I mean I have not found a way to verify that output was truncated

**Comment by weiminw** [comment]
@wenfengwang Do you get the solution at last. or Is there way to get full content when user input word "continue"?

**Comment by betoDavila86** [comment]
Has anyone found a good solution for this issue? Dealing with something similar atm.

**Comment by betoDavila86** [comment]
Hi team! Any new insight with regards to the truncated output issue?

We have tried the "continue" workaround with very random results and none of them correct when it comes to the required output.

Please, anyone can shed some light in this regard?

Thanks!

**Comment by onepointconsulting** [comment]
You can run the query in a loop and then check the finish reason. If the finish reason is not "stop" then keep on going with a "continue" message.

Here is some code to illustrate this strategy:
```python

from openai_experiments.config import cfg
from langchain_openai import ChatOpenAI

def long_query(system_message: str, human_message: str) -> list:
    messages = [
        (
            "system",
            system_message,
        ),
        ("human", human_message),
    ]
    client = ChatOpenAI(api_key=cfg.openai_api_key, model_name=cfg.model)
    ai_msg = client.invoke(messages)
    messages.append(("assistant", ai_msg.content))
    while not ai_msg.response_metadata['finish_reason'] == 'stop':
        messages.append(("human", "continue"))
        ai_msg = cfg.client.invoke(messages)
        messages.append(("assistant", ai_msg.content))
    return messages
```

Let me know your thoughts about this.
