### ISSUE TITLE
Connection with mongo db

### ISSUE THREAD

**Issue by nikhilkotiya** [langchain-ai/langchain#3399]
Can you please help me with connecting my LangChain agent to a MongoDB database? I know that it's possible to directly connect to a SQL database using this resource [https://python.langchain.com/en/latest/modules/agents/toolkits/examples/sql_database.html](url) but I'm not sure if the same approach can be used with MongoDB. If it's not possible, could you suggest other ways to connect to MongoDB?

**Comment by BriskyGates** [comment]
> Can you please help me with connecting my LangChain agent to a MongoDB database? I know that it's possible to directly connect to a SQL database using this resource [https://python.langchain.com/en/latest/modules/agents/toolkits/examples/sql_database.html](url) but I'm not sure if the same approach can be used with MongoDB. If it's not possible, could you suggest other ways to connect to MongoDB?

hi, have you found some solutions to connect to mongodb?

**Comment by PaulDiTi** [comment]
Would also be interested. Any updates?

**Comment by sknightq** [comment]
what's more, the MySQL too

**Comment by PaulDiTi** [comment]
Found a "workaround": Have gpt translate the prompt to a mongodb pipeline and then just execute the pipeline that gpt provided. 

I just used the normal OpenAI api and in the system message, provided my mongodb database schema and the format in which the model should respond (told it to respond with a dictionary that includes the pipeline and the name of the collection to execute the pipeline on). 

I then provided it with some few-shot examples to understand more complex pipelines and get mapping between the collections right (e.g. with $lookup). 

As gpt responds with a string, the response needs to be parsed to json, such that the pipeline can be executed on the database. 

The results are pretty good so far.

**Comment by prameela1610** [comment]
Hello @nikhilkotiya
have you found some solutions to connect to mongodb?

**Comment by nikhilkotiya** [comment]
@prameela1610  No, but there is an indirect solution for MongoDB where we save the data in JSON files and then pass it to LangChain.

**Comment by prameela1610** [comment]
Thank you for your response @nikhilkotiya 
you said that json agent right ???
 I need the DB connection only bec every time the data will update, If i am using json agent that time i get only past data 
 so the reason i need the connection of mongoDB .
 If you find something helps to connect the DB please share me 
 Thank you !!!!

**Comment by nikhilkotiya** [comment]
@prameela1610  you can use the sync of mongo db with sql and then use connection of sql. Bit complicated

**Comment by Gisellew10** [comment]
Hi @nikhilkotiya , I will take this one. 👍
