### ISSUE TITLE
marathon_times.ipynb: InvalidRequestError: This model's maximum context length is 4097 tokens. 

### ISSUE THREAD

**Issue by chunhualiao** [langchain-ai/langchain#3405]
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-26-5eed72c1ccb8>](https://localhost:8080/#) in <cell line: 3>()
          2 
----> 3 agent.run(["What were the winning boston marathon times for the past 5 years? Generate a table of the names, countries of origin, and times."])

31 frames
[/usr/local/lib/python3.9/dist-packages/langchain/experimental/autonomous_agents/autogpt/agent.py](https://localhost:8080/#) in run(self, goals)
    109                 tool = tools[action.name]
    110                 try:
--> 111                     observation = tool.run(action.args)
    112                 except ValidationError as e:
    113                     observation = f"Error in args: {str(e)}"

[/usr/local/lib/python3.9/dist-packages/langchain/tools/base.py](https://localhost:8080/#) in run(self, tool_input, verbose, start_color, color, **kwargs)
    105         except (Exception, KeyboardInterrupt) as e:
    106             self.callback_manager.on_tool_error(e, verbose=verbose_)
--> 107             raise e
    108         self.callback_manager.on_tool_end(
    109             observation, verbose=verbose_, color=color, name=self.name, **kwargs

[/usr/local/lib/python3.9/dist-packages/langchain/tools/base.py](https://localhost:8080/#) in run(self, tool_input, verbose, start_color, color, **kwargs)
    102         try:
    103             tool_args, tool_kwargs = _to_args_and_kwargs(tool_input)
--> 104             observation = self._run(*tool_args, **tool_kwargs)
    105         except (Exception, KeyboardInterrupt) as e:
    106             self.callback_manager.on_tool_error(e, verbose=verbose_)

[<ipython-input-12-79448a1343a1>](https://localhost:8080/#) in _run(self, url, question)
     33             results.append(f"Response from window {i} - {window_result}")
     34         results_docs = [Document(page_content="\n".join(results), metadata={"source": url})]
---> 35         return self.qa_chain({"input_documents": results_docs, "question": question}, return_only_outputs=True)
     36 
     37     async def _arun(self, url: str, question: str) -> str:

[/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116             raise e
    117         self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118         return self.prep_outputs(inputs, outputs, return_only_outputs)

[/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs)
    111         )
    112         try:
--> 113             outputs = self._call(inputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)

[/usr/local/lib/python3.9/dist-packages/langchain/chains/combine_documents/base.py](https://localhost:8080/#) in _call(self, inputs)
     73         # Other keys are assumed to be needed for LLM prediction
     74         other_keys = {k: v for k, v in inputs.items() if k != self.input_key}
---> 75         output, extra_return_dict = self.combine_docs(docs, **other_keys)
     76         extra_return_dict[self.output_key] = output
     77         return extra_return_dict

[/usr/local/lib/python3.9/dist-packages/langchain/chains/combine_documents/stuff.py](https://localhost:8080/#) in combine_docs(self, docs, **kwargs)
     81         inputs = self._get_inputs(docs, **kwargs)
     82         # Call predict on the LLM.
---> 83         return self.llm_chain.predict(**inputs), {}
     84 
     85     async def acombine_docs(

[/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py](https://localhost:8080/#) in predict(self, **kwargs)
    149                 completion = llm.predict(adjective="funny")
    150         """
--> 151         return self(kwargs)[self.output_key]
    152 
    153     async def apredict(self, **kwargs: Any) -> str:

[/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)
--> 116             raise e
    117         self.callback_manager.on_chain_end(outputs, verbose=self.verbose)
    118         return self.prep_outputs(inputs, outputs, return_only_outputs)

[/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs)
    111         )
    112         try:
--> 113             outputs = self._call(inputs)
    114         except (KeyboardInterrupt, Exception) as e:
    115             self.callback_manager.on_chain_error(e, verbose=self.verbose)

[/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py](https://localhost:8080/#) in _call(self, inputs)
     55 
     56     def _call(self, inputs: Dict[str, Any]) -> Dict[str, str]:
---> 57         return self.apply([inputs])[0]
     58 
     59     def generate(self, input_list: List[Dict[str, Any]]) -> LLMResult:

[/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py](https://localhost:8080/#) in apply(self, input_list)
    116     def apply(self, input_list: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    117         """Utilize the LLM generate method for speed gains."""
--> 118         response = self.generate(input_list)
    119         return self.create_outputs(response)
    120 

[/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py](https://localhost:8080/#) in generate(self, input_list)
     60         """Generate LLM result from inputs."""
     61         prompts, stop = self.prep_prompts(input_list)
---> 62         return self.llm.generate_prompt(prompts, stop)
     63 
     64     async def agenerate(self, input_list: List[Dict[str, Any]]) -> LLMResult:

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py](https://localhost:8080/#) in generate_prompt(self, prompts, stop)
     80         except (KeyboardInterrupt, Exception) as e:
     81             self.callback_manager.on_llm_error(e, verbose=self.verbose)
---> 82             raise e
     83         self.callback_manager.on_llm_end(output, verbose=self.verbose)
     84         return output

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py](https://localhost:8080/#) in generate_prompt(self, prompts, stop)
     77         )
     78         try:
---> 79             output = self.generate(prompt_messages, stop=stop)
     80         except (KeyboardInterrupt, Exception) as e:
     81             self.callback_manager.on_llm_error(e, verbose=self.verbose)

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py](https://localhost:8080/#) in generate(self, messages, stop)
     52     ) -> LLMResult:
     53         """Top Level call"""
---> 54         results = [self._generate(m, stop=stop) for m in messages]
     55         llm_output = self._combine_llm_outputs([res.llm_output for res in results])
     56         generations = [res.generations for res in results]

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/base.py](https://localhost:8080/#) in <listcomp>(.0)
     52     ) -> LLMResult:
     53         """Top Level call"""
---> 54         results = [self._generate(m, stop=stop) for m in messages]
     55         llm_output = self._combine_llm_outputs([res.llm_output for res in results])
     56         generations = [res.generations for res in results]

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/openai.py](https://localhost:8080/#) in _generate(self, messages, stop)
    264             )
    265             return ChatResult(generations=[ChatGeneration(message=message)])
--> 266         response = self.completion_with_retry(messages=message_dicts, **params)
    267         return self._create_chat_result(response)
    268 

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/openai.py](https://localhost:8080/#) in completion_with_retry(self, **kwargs)
    226             return self.client.create(**kwargs)
    227 
--> 228         return _completion_with_retry(**kwargs)
    229 
    230     def _combine_llm_outputs(self, llm_outputs: List[Optional[dict]]) -> dict:

[/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in wrapped_f(*args, **kw)
    287         @functools.wraps(f)
    288         def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289             return self(f, *args, **kw)
    290 
    291         def retry_with(*args: t.Any, **kwargs: t.Any) -> WrappedFn:

[/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    377         retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378         while True:
--> 379             do = self.iter(retry_state=retry_state)
    380             if isinstance(do, DoAttempt):
    381                 try:

[/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in iter(self, retry_state)
    312         is_explicit_retry = fut.failed and isinstance(fut.exception(), TryAgain)
    313         if not (is_explicit_retry or self.retry(retry_state)):
--> 314             return fut.result()
    315 
    316         if self.after is not None:

[/usr/lib/python3.9/concurrent/futures/_base.py](https://localhost:8080/#) in result(self, timeout)
    437                     raise CancelledError()
    438                 elif self._state == FINISHED:
--> 439                     return self.__get_result()
    440 
    441                 self._condition.wait(timeout)

[/usr/lib/python3.9/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    389         if self._exception:
    390             try:
--> 391                 raise self._exception
    392             finally:
    393                 # Break a reference cycle with the exception in self._exception

[/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    380             if isinstance(do, DoAttempt):
    381                 try:
--> 382                     result = fn(*args, **kwargs)
    383                 except BaseException:  # noqa: B902
    384                     retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

[/usr/local/lib/python3.9/dist-packages/langchain/chat_models/openai.py](https://localhost:8080/#) in _completion_with_retry(**kwargs)
    224         @retry_decorator
    225         def _completion_with_retry(**kwargs: Any) -> Any:
--> 226             return self.client.create(**kwargs)
    227 
    228         return _completion_with_retry(**kwargs)

[/usr/local/lib/python3.9/dist-packages/openai/api_resources/chat_completion.py](https://localhost:8080/#) in create(cls, *args, **kwargs)
     23         while True:
     24             try:
---> 25                 return super().create(*args, **kwargs)
     26             except TryAgain as e:
     27                 if timeout is not None and time.time() > start + timeout:

[/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py](https://localhost:8080/#) in create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    151         )
    152 
--> 153         response, _, api_key = requestor.request(
    154             "post",
    155             url,

[/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    224             request_timeout=request_timeout,
    225         )
--> 226         resp, got_stream = self._interpret_response(result, stream)
    227         return resp, got_stream, self.api_key
    228 

[/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response(self, result, stream)
    618         else:
    619             return (
--> 620                 self._interpret_response_line(
    621                     result.content.decode("utf-8"),
    622                     result.status_code,

[/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    681         stream_error = stream and "error" in resp.data
    682         if stream_error or not 200 <= rcode < 300:
--> 683             raise self.handle_error_response(
    684                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    685             )

InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4665 tokens. Please reduce the length of the messages.

**Comment by filip-michalsky** [comment]
@chunhualiao this is not an issue with the `langchain` library, but rather the underlying model you are using. You simply cannot pass a larger context vector into your LLM than 4097 tokens with what you are using (I suspect that's gpt-3.5 turbo?). You could try to apply for access to GPT-4 which allows you a larger token window (I think up to 32K tokens).

It would be cool to add a feature to synthesize/compress the previous context, but that is more of a research question.

**Comment by vowelparrot** [comment]
Auto-handling context is on the roadmap. Doing so automatically across all use cases could lead to undesired side effects (e.g., extreme hallucination) so we don't want to rush an implementation that causes silent errors

**Comment by filip-michalsky** [comment]
@vowelparrot sounds powerful! happy to contribute/help if I can. I am at filipmichalsky@gmail.com

**Comment by jaded0** [comment]
This issue occurs when running the example in the docs here: https://python.langchain.com/en/latest/use_cases/question_answering.html
