### ISSUE TITLE
memory_key as a variable

### ISSUE THREAD

**Issue by ravi160822** [langchain-ai/langchain#3406]
In the agent tutorials the memory_key is set as a fixed string, "chat_history", how do I make it a variable, that is different for each session_id, that is memory_key=str(session_id)?

**Comment by vowelparrot** [comment]
Could you elaborate on your use case?

**Comment by ravi160822** [comment]
I need to pass session_id as per the session in the chat frontend, so the memory_key would be different for each session. I create a fastapi to get session_id as a variable

**Comment by ravi160822** [comment]
still facing issues maintaining session_ids for different fastapi api calls
