### ISSUE TITLE
Azure OpenAI - Exception has occurred: InvalidRequestError Resource not found

### ISSUE THREAD

**Issue by micuentadecasa** [langchain-ai/langchain#3444]
Hi, I'm trying to use the examples for Azure OpenAI with langchain, for example this notebook in https://python.langchain.com/en/harrison-docs-refactor-3-24/modules/models/llms/integrations/azure_openai_example.html , but I always find this error:

Exception has occurred: InvalidRequestError Resource not found

I have tried multiple combinations with the environment variables, but nothing works, I have also tested it in a python script with the same results.

Regards.

**Comment by micuentadecasa** [comment]
Hi @eavanvalkenburg ,the deployment_name parameter is filled, but it doesn't works, I think that a proper documentation with a working sample should be in the langchain documentation.

**Comment by micuentadecasa** [comment]
> > Hi @eavanvalkenburg ,the deployment_name parameter is filled, but it doesn't works, I think that a proper documentation with a working sample should be in the langchain documentation.
> 
> #1942 You can refer to this

Dear @xinj7 , I confirm that the #1942 fixes the AzureChatOpenAI function, but it doesn't fix the AzureOpenAI function that is used by me, and it is used in the documentation page I was refering to.

**Comment by ruckc** [comment]
same error, trying to use a deployment named `gpt-35-turbo'.

**Comment by metazool** [comment]
`AzureOpenAI` takes a [deployment_name](https://github.com/hwchase17/langchain/blob/681ba6d520585503ab5c0b8af0a95c35be7e26b6/langchain/llms/openai.py#L611) parameter - this resolved it for me
