### ISSUE TITLE
Encapsulate API keys

### ISSUE THREAD

**Issue by amir-bio** [langchain-ai/langchain#3446]
I'm building a flow where I'm using both gpt-3.5 and gpt-4 based chains and I need to use different API keys for each (due to API access + external factors)

Both `ChatOpenAI` and `OpenAI` set `openai.api_key = openai_api_key` which is a global variable on the package.

This means that if I instantiate multiple ChatOpenAI instances, the last one's API key will override the other ones and that one will be used when calling the OpenAI endpoints.

Based on https://github.com/openai/openai-python/issues/233#issuecomment-1464732160 there's an undocumented feature where we can pass the api_key on each openai client call and that key will be used. 

As a side note, I've also noticed `ChatOpenAI` and a few other classes take in an optional `openai_api_key` as part of initialisation which is correctly used over the env var but the docstring says that the `OPENAI_API_KEY` env var should be set, which doesn't seem to be case. Can we confirm if this env var is needed elsewhere or if it's possible to just pass in the values when instantiating the chat models.

Thanks!

**Comment by xxb0120** [comment]
I also encountered this problem. Is there a solution?

**Comment by parulekarmihir** [comment]
Same, can anyone look into this issue.

**Comment by FlowerWrong** [comment]
the same with https://github.com/hwchase17/langchain/issues/2091
