### ISSUE TITLE
Broken intermediate output / parsing is grossly unreliable

### ISSUE THREAD

**Issue by Kav-K** [langchain-ai/langchain#3448]
```
Traceback (most recent call last):
  File "/home/gptbot/cogs/search_service_cog.py", line 322, in on_message
    response, stdout_output = await capture_stdout(
  File "/home/gptbot/cogs/search_service_cog.py", line 79, in capture_stdout
    result = await func(*args, **kwargs)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/agent.py", line 807, in _call
    output = self.agent.return_stopped_response(
  File "/usr/local/lib/python3.9/dist-packages/langchain/agents/agent.py", line 515, in return_stopped_response
    full_output = self.llm_chain.predict(**full_inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 151, in predict
    return self(kwargs)[self.output_key]
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 61, in generate
    prompts, stop = self.prep_prompts(input_list)
  File "/usr/local/lib/python3.9/dist-packages/langchain/chains/llm.py", line 79, in prep_prompts
    prompt = self.prompt.format_prompt(**selected_inputs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/prompts/chat.py", line 127, in format_prompt
    messages = self.format_messages(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/langchain/prompts/chat.py", line 186, in format_messages
    message = message_template.format_messages(**rel_params)
  File "/usr/local/lib/python3.9/dist-packages/langchain/prompts/chat.py", line 43, in format_messages
    raise ValueError(
ValueError: variable agent_scratchpad should be a list of base messages, got {
    "action": "Search-Tool",
    "action_input": "Who is Harald Baldr?"
}

```
Most of the time the agent can't parse it's own tool usage.

**Comment by jpzhangvincent** [comment]
I got the same error. not sure whether it's a new bug introduced.

**Comment by pressoholics** [comment]
I think it was this commit that caused the issue, namely the concept of message lists. When i roll back to before the PR was committed the error is gone.

https://github.com/hwchase17/langchain/pull/2310

**Comment by jpzhangvincent** [comment]
@hwchase17 any insights on how to fix the bug to make it compatible with the current version?

**Comment by sahil-lalani** [comment]
facing this exact same issue using chat conversational react description

**Comment by Kav-K** [comment]
Have this same issue. this needs to be prioritized, conversational agents are absolutely broken for any sort of robust use case.

**Comment by axenov** [comment]
I have the same error in the ConversationalChatAgent with most of my inputs.

**Comment by treppers** [comment]
Just re-read the original issue and recalled that when fixing this, I may have done more than just update the output_parser.  

Refer to my other [PR](https://github.com/hwchase17/langchain/pull/4411) for a new chat agent.

**Comment by KeshavSingh29** [comment]
I'm facing exactly the same issue. If the max_iterations is greater than 1, the agent raises ValueError 
```python 
raise ValueError(
ValueError: variable agent_scratchpad should be a list of base messages, got {
    "action": "Conversation Knowledgebase",
    "action_input": "Can you please be more specific about what you need help with in the game?"
}
```

**Comment by Kav-K** [comment]
still exists

**Comment by MichalQU** [comment]
I can confirm the issue still exists in version 0.0.302

**Comment by Kav-K** [comment]
I think this has been fixed now.

**Comment by armmarov** [comment]
i don't think it has been fixed. Tried out latest version 0.1.0. Still getting the same error when using early_stopping_method="generate" and max_iteration. Can anybody help with the patch ?

**Comment by a-fatah** [comment]
I am using 0.1.14 and still facing this issue. 
`agent_scratchpad` is being constructed as string but a list of messages is expected.

**Comment by Kav-K** [comment]
yeah this is still super disgusting and absolutely broken

**Comment by iharsuvorau** [comment]
Having the same issue. @Kav-K have you closed the issue?

**Comment by the-promised-LAN** [comment]
Also still seeing the issue with v0.1.19 when following the [agents quickstart tutorial](https://python.langchain.com/v0.1/docs/modules/agents/quick_start/):

```
ValueError: variable agent_scratchpad should be a list of base messages, got
```

**Comment by jsemrau** [comment]
> Also still seeing the issue with v0.1.19 when following the [agents quickstart tutorial](https://python.langchain.com/v0.1/docs/modules/agents/quick_start/):
> 
> ```
> ValueError: variable agent_scratchpad should be a list of base messages, got
> ```

I initiated my agent as following which seems to have fixed it for me

```
from langchain.agents.format_scratchpad import format_log_to_str

agent = (
                {
                    "input": lambda x: x["input"],
                    "agent_scratchpad": lambda x: format_log_to_str(x["intermediate_steps"]),
                }
                | prompt
                | chat_model_with_stop
                | output_parser
        )
```

**Comment by jsemrau** [comment]
Also what I noticed is that the error occurs when I pull the prompt from the hub.

```
prompt = hub.pull("hwchase17/react-chat-json")
```
and not when i hand copy/paste from the site manually and do this.

```
prompt = PromptTemplate.from_template(definition_prompts)
        prompt = prompt.partial(
            tools=render_text_description(tools),
            tool_names=", ".join([t.name for t in tools]),
        )
```

**Comment by mrtj** [comment]
If you face this error when creating your agent with `create_react_agent`, note that the chain in this function formats the agent_scratchpad as a string. If you construct your prompt manually, pay attention to define this variable as a simple prompt template variable and not as a message placeholder, i.e. use something like `("human", "{agent_scratchpad")` instead of `MessagesPlaceholder(variable_name="agent_scratchpad")`.

**Comment by Cristhianzl** [comment]
Hi,

I was able to get it working by instantiating the messages like this, passing the agent_scratchpad as "ai":

```
messages = [
    ("system", self.system_prompt),
    ("placeholder", "{chat_history}"),
    HumanMessagePromptTemplate(
        prompt=PromptTemplate(input_variables=["input"], template=self.user_prompt)
    ),
    ("ai", "{agent_scratchpad}"),
]

prompt = ChatPromptTemplate.from_messages(messages)
create_xml_agent(self.llm, self.tools, prompt)
```

or


```
const prompt = ChatPromptTemplate.fromMessages([
  ["human", template],
  ["ai", "{agent_scratchpad}"],
]);

const outputParser = new XMLAgentOutputParser();
```

and don't forget to add the in the end of your prompt so the agent can create a recursion on that:

> const template = `You are a helpful assistant. Help the user answer any questions.
> 
> You have access to the following tools:
> 
> {tools}
> 
> In order to use a tool, you can use <tool></tool> and <tool_input></tool_input> tags. \
> You will then get back a response in the form <observation></observation>
> For example, if you have a tool called 'search' that could run a google search, in order to search for the weather in SF you would respond:
> 
> <tool>search</tool><tool_input>weather in SF</tool_input>
> <observation>64 degrees</observation>
> 
> When you are done, respond with a final answer between <final_answer></final_answer>. For example:
> 
> <final_answer>The weather in SF is 64 degrees</final_answer>
> 
> Begin!
> 
> Question: {input}
> 
> **{agent_scratchpad}**
> `;

I was following this documentation: [Link](https://js.langchain.com/v0.1/docs/expression_language/cookbook/agents/)
