### ISSUE TITLE
Conversational Chat Agent: json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by djpecot** [langchain-ai/langchain#3455]
I get this error occasionally when running the calculator tool, and seems like lots of other people are dealing with weird outputs from agents [like here](https://github.com/hwchase17/langchain/issues/2276). I'm seeing just random junk on the end of my objects returned from agents:

```
File "c:\Users\djpec\Documents\GitHub\project\venv\lib\site-packages\langchain\agents\conversational_chat\output_parser.py", line 32, in parse
    response = json.loads(cleaned_output)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 94)
```

Inspecting the `cleaned_output` yields this when preparing for final answer (I'm not sure how to wrap this in backticks, sorry lol):

![image](https://user-images.githubusercontent.com/8185181/234075261-82e290fe-2452-404a-93f5-60ba30d04e51.png)

I fixed it by importing the `regex` library and searching recursively for the largest "object" in the string in my `venv\lib\site-packages\langchain\agents\conversational_chat\output_parser.py` function
```
import regex
...
if cleaned_output.endswith("```"):
            cleaned_output = cleaned_output[: -len("```")]
        if not cleaned_output.endswith("""\n}"""):
            pattern = r"(\{(?:[^{}]|(?R))*\})"
            cleaned_output = regex.search(pattern, text).group(0)
        cleaned_output = cleaned_output.strip()
...
```

**Comment by voulkon** [comment]
Hi, it happened to me as well. 
It appears that some times ChatGPT doesn't return its response as instructed (wrapped in 3 backticks).
In your attached image, you can notice the **two backticks** in the cleaned cleaned_output. 
If it were cleaned, it would have no backticks in the end.
As of now, there is a parse_json_markdown function that does this job and it's using regex (insted of multiple if statements). 
I changed the regex expression to **match** with **responses that have from 1-3 backticks**.

**Comment by trojrobert** [comment]
I am facing the same problem but my delimiter is not 3 backticks, my delimiter is <>. How should I clean my output?

**Comment by trojrobert** [comment]
> pattern



> I get this error occasionally when running the calculator tool, and seems like lots of other people are dealing with weird outputs from agents [like here](https://github.com/hwchase17/langchain/issues/2276). I'm seeing just random junk on the end of my objects returned from agents:
> 
> ```
> File "c:\Users\djpec\Documents\GitHub\project\venv\lib\site-packages\langchain\agents\conversational_chat\output_parser.py", line 32, in parse
>     response = json.loads(cleaned_output)
>   File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Program Files\Python39\lib\json\decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 94)
> ```
> 
> Inspecting the `cleaned_output` yields this when preparing for final answer (I'm not sure how to wrap this in backticks, sorry lol):
> 
> ![image](https://user-images.githubusercontent.com/8185181/234075261-82e290fe-2452-404a-93f5-60ba30d04e51.png)
> 
> I fixed it by importing the `regex` library and searching recursively for the largest "object" in the string in my `venv\lib\site-packages\langchain\agents\conversational_chat\output_parser.py` function
> 
> ```
> import regex
> ...
> if cleaned_output.endswith("```"):
>             cleaned_output = cleaned_output[: -len("```")]
>         if not cleaned_output.endswith("""\n}"""):
>             pattern = r"(\{(?:[^{}]|(?R))*\})"
>             cleaned_output = regex.search(pattern, text).group(0)
>         cleaned_output = cleaned_output.strip()
> ...
> ```

@djpecot What is the variable "text" in line 6
"""cleaned_output = regex.search(pattern, text).group(0)"""
