### ISSUE TITLE
Pinecone retriever throwing: KeyError: 'text'

### ISSUE THREAD

**Issue by kindbuds** [langchain-ai/langchain#3460]
My query code is below:
```
pinecone.init(
    api_key=os.environ.get('PINECONE_API_KEY'),  # app.pinecone.io
    environment=os.environ.get('PINECONE_ENV')  # next to API key in console
)
index = pinecone.Index(index_name)
embeddings = OpenAIEmbeddings(openai_api_key=os.environ.get('OPENAI_API_KEY'))

vectordb = Pinecone(
    index=index,
    embedding_function=embeddings.embed_query,
    text_key="text",
)
llm=ChatOpenAI(
    openai_api_key=os.environ.get('OPENAI_API_KEY'),
    temperature=0,
    model_name='gpt-3.5-turbo'
)
retriever = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectordb.as_retriever()
)
tools = [Tool(
    func=retriever.run,
    description=tool_desc,
    name='Product DB'
)]
memory = ConversationBufferWindowMemory(
    memory_key="chat_history",  # important to align with agent prompt (below)
    k=5,
    return_messages=True
)
agent = initialize_agent(
    agent='chat-conversational-react-description', 
    tools=tools, 
    llm=llm,
    verbose=True,
    max_iterations=3,
    early_stopping_method="generate",
    memory=memory,
)
```

If I run:
`agent({'chat_history':[], 'input':'What is a product?'})`

It throws: 

> File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\vectorstores\pinecone.py", line 160, in similarity_search
> text = metadata.pop(self._text_key)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: 'text'

This is the offending block in site-packages/pinecone.py:

```
 for res in results["matches"]:
            # print('metadata.pop(self._text_key) = ' + metadata.pop(self._text_key))
            metadata = res["metadata"]
            text = metadata.pop(self._text_key)
            docs.append(Document(page_content=text, metadata=metadata))
```

If I remove my tool like the line below, everything executes (just not my tool):

`tools = []`

Can anyone help me fix this KeyError: 'text' issue?  My versions of langchain, pinecone-client and python are 0.0.147, 2.2.1 and 3.11.3 respectively.

**Comment by christianwarmuth** [comment]
From having a first look (without knowing more about the setup): 
Might it be that the PineconeDB is empty?
Depending on your setup, you (having documents locally or already a Pinecone index created), you might want to try

```
vectordb = Pinecone.from_existing_index(
    index_name=index,
    embedding=embeddings,
)
```

Or ```Pinecone.from_documents```.  What you are currently doing is initializing Pinecone. If however the pinecone client tries to perform a similarity search, there is nothing to be found?

**Comment by alarcon7a** [comment]
same problem here, any solution?

**Comment by aringer117** [comment]
+1 here. Subscribing.

**Comment by verveguy** [comment]
+1 PInecone retrieval seems broken. It either flips out with 'text' error or hangs indefinitely.

**Comment by PlatosTwin** [comment]
Pinecone doesn't store documents explicitly; it only stores ids, embeddings, and metadata. So, if when querying Pinecone you'd like to have access to the documents themselves, you should add them to the metadata, as illustrated [here](https://docs.pinecone.io/docs/langchain#indexing). If you add them under a `text` key in the metadata, the `KeyError` should resolve.

Alternatively, you can specify your own key name when you initialize `Pinecone`, via `text_str`. Code reference is [here](https://github.com/hwchase17/langchain/blob/a6ebffb69504576a805f3b9f09732ad344751b89/langchain/vectorstores/pinecone.py#LL39C9-L39C17).

**Comment by PeakProsperityDotCom** [comment]
This explains a lot - thank you.  However, wouldn't storing the entire text of a document in addition to the vector drastically increase the storage requirements?  I believe Pinecone also suggests avoiding pieces of metadata that are very unique, which this certainly would be.

Is it not possible to use the vector data itself as an input to ChatGPT for answering questions on the data?  From above, it sounds like you need to do as follows:

1. Embed the text and store both the vector and original text at Pinecone.
2. Perform a similarity search on the Pinecone index to find relevant documents.
3. Take text from Pinecone metadata and feed that back into the LLM for QA.

Appreciate any additional ideas.  Thanks.

**Comment by verveguy** [comment]
Your alternative is to store the document text elsewhere and then store a
reference / URL to it in the pinecone metadata. This is what I do with Tana
notes, for example. Pinecone is the search index - Tana is the content
repository.

**Comment by PeakProsperityDotCom** [comment]
Thanks, @verveguy .  I created a table in our SQL database that references the vector ID and it seems to be working well.

**Comment by kishorgujjar** [comment]
same problem here, any solution?


text = metadata.pop(self._text_key)
KeyError: 'text'

**Comment by AMRedichkina** [comment]
In my situation, I encountered an issue due to the metadata associated with the vectors, specifically the need to include a key labeled "text" (e.g., "text": text). I found the solution to this problem in the comment at this [GitHub link](https://github.com/langchain-ai/langchain/issues/3460#issuecomment-1583471622), which proved to be extremely helpful for me.

**Comment by rpalsaxena** [comment]
Is there any update about the issue. I am also getting this error:
```
from langchain.vectorstores import Pinecone
​
text_field = "text"
​
# switch back to normal index for langchain
​
vectorstore = Pinecone(
    index, embed.embed_query, text_key='text'
)
query = "when "
​
vectorstore.similarity_search(
    query,  # our search query
    k=3  # return 3 most relevant docs
)
Found document with no `text` key. Skipping.
Found document with no `text` key. Skipping.
Found document with no `text` key. Skipping.
[]
```

**Comment by zubairahmed-ai** [comment]
Same issue, any updates?

**Comment by CessarGL** [comment]
I solve the problem. Here is a detailed explanation and for last a question for @langchainTeam. 
When you create a record on pinecone by yourself for example ([pinecone documentation](https://docs.pinecone.io/guides/getting-started/quickstart)): 
```
pc = Pinecone(api_key='YOUR_API_KEY')
index_name = "docs-quickstart-index"

pc.create_index(
    name=index_name,
    dimension=8,
    metric="cosine",
    spec=ServerlessSpec(
        cloud='aws', 
        region='us-east-1'
    ) 
) 

index = pc.Index(index_name)

index.upsert(
    vectors=[
        {"id": "vec1", "values": [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], "metadata": {"type": "doc1"}},
        {"id": "vec2", "values": [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2], "metadata": {"type": "doc2"}},
        {"id": "vec3", "values": [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3], "metadata": {"type": "doc3"}},
        {"id": "vec4", "values": [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]}
    ],
    namespace="ns1"
)
```
It doesnt add the metadata field "text", only your custon metadata in case you put one, and you can do a similarity search to that vectors with no problem ([pinecone documentation](https://docs.pinecone.io/guides/getting-started/quickstart))
```
index.query(
    namespace="ns2",
    vector=[0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7],
    top_k=3,
    include_values=True
)
```
When you create a vector on pinecone by langchain for example ([langchain documentation](https://python.langchain.com/docs/integrations/vectorstores/pinecone/)): 
```
vectorstore = PineconeVectorStore(index_name=index_name, embedding=embeddings)

vectorstore.add_texts(["More text!"])
```
It adds to the vector a metadata field named "text" that is the actual text embeded.
![textProblem](https://github.com/langchain-ai/langchain/assets/32230910/32cf103e-ad26-4337-b33a-ee4a0651b6ba)

And then, with that metadata field, you can do: 

`vectorstore.similarity_search(query="More Text")`

Or alternatively, with the retriver interface: 
```
retriver = vectorstore.as_retriever()
results = retriver.invoke("More Text")
```
My question is, Which concept im missing ? Why have a vectorstore with the vector values (the vector representation of the text) if I have to run the querys on the "text" metadata field with te actual text ? Thank you for your time, and I appreciate your response to help resolve my doubt. In summary, why maintain a vectorstore with vector values if queries ultimately need to be run on the 'text' metadata field with the actual text?

**Comment by Mizuki8783** [comment]
@CessarGL I had the same issue since I stored vectors as shown on the pinecone website. I think the point of including "text" as a metadata is for the language model to interpret the context. Vector search only retrieves the similar vectors but vector itself are jusyt bunch of numbers. In order for the LLMs to understand the semantic meanings of each vector I think you need to attach content under text to the vectors.

**Comment by PradipPoriya** [comment]
i also faced the same error.   as @Mizuki8783 said, add text content 

> @CessarGL I had the same issue since I stored vectors as shown on the pinecone website. I think the point of including "text" as a metadata is for the language model to interpret the context. Vector search only retrieves the similar vectors but vector itself are jusyt bunch of numbers. In order for the LLMs to understand the semantic meanings of each vector I think you need to attach content under text to the vectors.

exactly, add text content in metadata along with vector embedding. i solved the error by doing so.
