### ISSUE TITLE
The from_documents in opensensearch may not be working as expected.

### ISSUE THREAD

**Issue by engineer-matsuo** [langchain-ai/langchain#3473]
Name: langchain
Version: 0.0.146

Name: opensearch-py
Version: 2.2.0

Even if I build opensearch in docker and run it as per langchain's official documentation, the index is randomly numbered and data is created.
I am not sure if this is how it is supposed to work.
I was imagining that multiple documents are usually added to a single index.

Also, I get the following error when I specify index_name.

File "/usr/local/lib/python3.10/site-packages/opensearchpy/connection/base.py", line 301, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
opensearchpy.exceptions.RequestError: RequestError(400, 'resource_already_exists_exception', 'index [test_index/GEdIKgfrRO24XoRbcJCeVg ] already exists')

There seems to be a duplicate index, as client.indices.create(index=index_name, body=mapping) in the from_texts function of opensearch_vector_search.py is always executed. I assume this is because the client.indices.create(index=index_name, body=mapping) is always executed.

![スクリーンショット 2023-04-25 9 07 45](https://user-images.githubusercontent.com/95115586/234141078-da4c7d97-d39a-41fd-85f1-41d4c2d6ea84.png)

**Comment by engineer-matsuo** [comment]
I copied and customized opensearch_vector_search to use as a temporary fix.
I eliminated the process of trying to create a new index each time in the from_texts function and modified the _bulk_ingest_embeddingsk function with reference to elastic_vector_search.py.
It seems that this is probably opensearch-specific and has been fixed in elastic_vector_search.

**Comment by russellballestrini** [comment]
I ran into the same issue, I cannot push new documents into a previously created index because `from_text` always tries to create the index which throws an exception if it already exists.
