### ISSUE TITLE
Llamacpp.py _call returns both prompt and generation

### ISSUE THREAD

**Issue by sergedc** [langchain-ai/langchain#3478]
The _call function returns result["choices"][0]["text"]
For me result["choices"][0]["text"] includes both the prompt and the answer.

My use case: document summary: 
llm = LlamaCpp(model_path=r"D:\AI\Model\vicuna-13B-1.1-GPTQ-4bit-128g.GGML.bin",n_ctx=4000, f16_kv=True)
chain = load_summarize_chain(llm, chain_type="map_reduce", verbose = True)
myoutput = chain.run(docs)

Well, obviously this does not work, because in llms>base.py, in the _generate function, we call _call like this: 
        generations = []
        for prompt in prompts:
            text = self._call(prompt, stop=stop)
            generations.append([Generation(text=text)])

This chain is supposed to create summury, but what comes back from the LLM (prompt+output) is longer than the input (the prompt). 
So this chain goes into a loop. 

FYI, this works totally fine.
llm = OpenAI(temperature=0)
chain = load_summarize_chain(llm, chain_type="map_reduce", verbose = True)
myoutput = chain.run(docs)
And in this case I can confirm that text = self._call(prompt, stop=stop)  has only the output (no prompt). 

I will look into what result["choices"][0]["text"] should be changed to.

**Comment by sergedc** [comment]
I added this line in llamacpp.py (just before return text["choices"][0]["text"] ) and it seems resolved: 
text["choices"][0]["text"] = text["choices"][0]["text"].replace(prompt, "")

I am not sure if the problem is with llama-cpp-python or with the llamacpp.py file of langchain. 
In anycase, the code above wont hurt even when the solution is fixed.

**Comment by jiangbossB** [comment]
in my case:
langchain/llms/base.py:
text = self._call(prompt, stop=stop) has only the output (no prompt).  It returns a generator type，But this parameter requires a str：generations.append([Generation(text=text)])
Error occured bellow：
pydantic.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

**Comment by jiangbossB** [comment]
in my case:
langchain/llms/base.py:
text = self._call(prompt, stop=stop) has only the output (no prompt).  It returns a generator type，But this parameter requires a str：generations.append([Generation(text=text)])
Error occured bellow：
pydantic.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)

Any answer is appreciated.
