### ISSUE TITLE
Add batching support to all LLMs

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#348]
Currently only done for OpenAI, but should be done for all

**Comment by NirantK** [comment]
in OpenAI implementation, this is done by adding `sub_prompts` in the `BaseOpenAI` class → `_generate`. The other option would be to move this logic to `BaseLLM`, and let others continue to inherit from there — including OpenAI.

Do you've a preference? Moving this logic to `BaseLLM` seems doable to me. Is there a tradeoff I am not seeing?

PS: Happy to pick this up and contribute, might need some getting started pointers like above

**Comment by hwchase17** [comment]
the default logic is to do it sequential, rather than the batching with sub_prompts that open ai does

sequential is nice because it is easy to think about and easy to add custom classes

the best place to start here would be to pick one provider, Cohere, and add batching support for it, similar to how is done for OpenAI. We can do that for a few more providers, THEN factor out any common code
