### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by anudit** [langchain-ai/langchain#3486]
I'm running langchain on a 4xV100 rig on AWS. Currently it only utilizes a single GPU. I was able to get it to run on all GPUs by changing,

https://github.com/hwchase17/langchain/blob/a14d1c02f87d23d9ff5ab36a4c68aeb724499455/langchain/embeddings/huggingface.py#L71
to
```python
print('Using MultiGPU')
pool = self.client.start_multi_process_pool()
embeddings = self.client.encode_multi_process(texts, pool)
self.client.stop_multi_process_pool(pool)
```
as `sentence-transformers` does support multi-GPU encoding under the hood.

I am sure there is a more elegant way of achieving this, although this duct-taped solution seems to work for now.

**Comment by DhavalThkkar** [comment]
@anudit There should be some in-built way in langchain that should support this!

**Comment by oubeichen** [comment]
+1

**Comment by Taeuk-Jang** [comment]
+111

**Comment by manbehindthemadness** [comment]
It would also be prudent to allow specification of a preferred single GPU other than device 0.
