### ISSUE TITLE
text-generation-webui api

### ISSUE THREAD

**Issue by atisharma** [langchain-ai/langchain#3499]
oobabooga/text-generation-webui/ is a popular method of running various models including llama variants on GPU and via llama.cpp. It would be useful to be abl to call its api as it can run and configure LLaMA, llama.cpp, GPT-J, Pythia, OPT, and GALACTICA in various quantisations with LoRA etc.

I know you have just added llama.cpp directly but I could not find any way to call the api of oobabooga/text-generation-webui/. I recall I saw someone trying to wrap kobold but I can't find their work, which I expect would be similar.

Is anyone working on this? If not I will fork and have a go - it doesn't seem too difficult to wrap llm apis given the examples provided.

**Comment by matatonic** [comment]
oobabooga/text-generation-webui#1475 is mine, I just wanted to mention that I've updated it and done some testing with langchain... Frankly, It doesn't work well yet. Things like assuming zero shot json format and code gen are pretty hit or miss with the smaller models, also the context sizes are also typically much smaller (2k). The text completion (as opposed to the chat interface) is also very poor at answering questions for most models - that's just what I found from working through some examples from the langchain quickstart. I haven't implemented batched input yet either, so nice things like document loading are still not working well.

**Comment by mix1009** [comment]
Here's my implementation. It only supports blocking api for now.

https://github.com/mix1009/langchain-text-generation-webui/blob/main/TextGenerationWebUI.ipynb

**Comment by atisharma** [comment]
> Here's my implementation. It only supports blocking api for now.
> 
> https://github.com/mix1009/langchain-text-generation-webui/blob/main/TextGenerationWebUI.ipynb

Cool. Mine is at https://github.com/hwchase17/langchain/pull/3553

**Comment by atisharma** [comment]
> I just wanted to mention that I've updated it and done some testing with langchain... Frankly, It doesn't work well yet

According to https://www.reddit.com/r/LocalLLaMA/comments/13kzubz/i_made_a_simple_agent_demo_with_guidance_and/ Microsoft's Guidance helps with this.
