### ISSUE TITLE
BaseChatModel.__call__() doesn't trigger any callback

### ISSUE THREAD

**Issue by liusida** [langchain-ai/langchain#3519]
We define some callback manager and a chatbot:
```
from langchain.callbacks import OpenAICallbackHandler
from langchain.callbacks.base import CallbackManager

manager = CallbackManager([OpenAICallbackHandler()])
chatbot = ChatOpenAI(temperature=1, callback_manager=manager)
messages = [SystemMessage(content="")]
```
Now if we use `result = chatbot(messages)` to call OpenAI API for result, it won't trigger any callback.
But if we use `chat.generate_prompt()` or `chat.agenerate_prompt()`, it will trigger callbacks.
I suppose this is a bug not a feature, right?

https://github.com/hwchase17/langchain/blob/bee59b4689fe23dce1450bde1a5d96b0aa52ee61/langchain/chat_models/base.py#L125

**Comment by cipher982** [comment]
I am encountering this as well. I see in [BaseLLM](https://github.com/hwchase17/langchain/blob/e6c8cce05040fd5b45aa25cbf03d660a95c78294/langchain/llms/base.py#L133) a call for `on_llm_start`, while in [BaseChatModel](https://github.com/hwchase17/langchain/blob/e6c8cce05040fd5b45aa25cbf03d660a95c78294/langchain/chat_models/base.py#L81) it is outside of `generate` and used in `generate_prompt`. So when I just use `agent_exec(inputs)` they do not get triggerd.
