### ISSUE TITLE
ValueError: Number of columns in X and Y must be same. ( in Faiss maximal marginal search )

### ISSUE THREAD

**Issue by lucinex** [langchain-ai/langchain#3529]
![image](https://user-images.githubusercontent.com/54734925/234318510-527f0cfe-a856-4e8e-85c1-e2f7d760833f.png)
Getting this error While using faiss vector store methods. 
Found that in code , the query embedding is wrapped around a List ,
![image](https://user-images.githubusercontent.com/54734925/234319458-e97257af-a7ef-4a09-9df4-d183a62d945d.png)
And then again it is wrapped in list inside the maximal_marginal_method
![image](https://user-images.githubusercontent.com/54734925/234325721-82bb19d7-1465-40f8-ab45-67ca9a39c93c.png)

I hope this gets fixed !

**Comment by iamaziz** [comment]
I had a similar error that was resolved after I upgraded to the [latest release](https://github.com/hwchase17/langchain/releases/tag/v0.0.157) `v0.0.157`.
