### ISSUE TITLE
VectorstoreIndexCreator cannot load data from WebBaseLoader

### ISSUE THREAD

**Issue by youshikyou** [langchain-ai/langchain#3542]
Hello,
I am trying to use webbaseloader to ingest content from a list of urls.
```
from langchain.indexes import VectorstoreIndexCreator
from langchain.document_loaders import WebBaseLoader

loader = WebBaseLoader(urls)
index = VectorstoreIndexCreator().from_loaders([loader])
```

But I got an error like , 
`ValueError: Expected metadata value to be a str, int, or float, got None`

**Comment by usai-dns** [comment]
I have the same error while trying to load from a list of urls with WebBaseLoader, but didnt get the error when adding

`index = VectorstoreIndexCreator().from_loaders([loader]).**vectorstore**`

**Comment by wasabiih** [comment]
> Hello, I am trying to use webbaseloader to ingest content from a list of urls.
> 
> ```
> from langchain.indexes import VectorstoreIndexCreator
> from langchain.document_loaders import WebBaseLoader
> 
> loader = WebBaseLoader(urls)
> index = VectorstoreIndexCreator().from_loaders([loader])
> ```
> 
> But I got an error like , `ValueError: Expected metadata value to be a str, int, or float, got None`

Hi [youshikyou], were you able to solve the problem?

**Comment by youshikyou** [comment]
whoever ends up here. I didn't solve this issue. But I use
```
loader = WebBaseLoader(urls)
docs = loader.load()
for doc in docs:
  doc.page_content = doc.page_content
  doc.metadata = {"url": doc.metadata["source"]}
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(docs)
....
```
When I replied this message, I haven't tried usai's solution.

**Comment by pccross** [comment]
> I have the same error while trying to load from a list of urls with WebBaseLoader, but didnt get the error when adding
> 
> `index = VectorstoreIndexCreator().from_loaders([loader]).**vectorstore**`

Hi, I'm still fighting with this issue.    Can you share a bit more of the code where you used this to fix the error?
I'm not sure where I would fit this into my code snippet below:
    for can_url in canopy_url_list:        
        loader = WebBaseLoader(can_url)
       # print(can_url)
        scrape_data = loader.load()
        #scrape_data.metadata = fix_metadata(scrape_data.metadata)
        #scrape_data.metadata = {"url": scrape_data.metadata["source"]}
        documents.extend(scrape_data)

**Comment by karimouda** [comment]
> whoever ends up here. I didn't solve this issue. But I use
> 
> ```
> loader = WebBaseLoader(urls)
> docs = loader.load()
> for doc in docs:
>   doc.page_content = doc.page_content
>   doc.metadata = {"url": doc.metadata["source"]}
> text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> texts = text_splitter.split_documents(docs)
> ....
> ```
> 
> When I replied this message, I haven't tried usai's solution.

doc.page_content = doc.page_content
doc.metadata = {"url": doc.metadata["source"]}

Solved it for me

**Comment by montyevans** [comment]
Fixed in #8175 - can close now.

**Comment by montyevans** [comment]
@baskaryan Would you mind closing this issue per the above? I don't have triage perms :)

**Comment by okoliechykwuka** [comment]
The error occurs because a Key in the metadata has a value set to None.

To fix the error, set the key-value to an empty string or int.

for doc in docs:
    for key, value in doc.metadata.items():
        if value is None:
            print('Metadata key and Value: ', key, value)
            doc.metadata[key]= ''

**Comment by JahangirJadi** [comment]
from langchain.document_loaders import WebBaseLoader
from langchain.indexes import VectorstoreIndexCreator

 url = 'https://lilianweng.github.io/posts/2023-06-23-agent/'
loader = WebBaseLoader(URL)

This made me crazy.

loader.load not working. Please fix it.
