### ISSUE TITLE
Support for model router pattern for chains to allow for dynamic routing to right chains based on vector store semantics 

### ISSUE THREAD

**Issue by keshy** [langchain-ai/langchain#3555]
We need a model gateway pattern support for Chains for following reasons:

- We may have external decision making elements that would help route which LLM model would need to handle a request. E.g. vector store. 
- Agents don't always cut it with the customization that'd be needed. We will need custom tool building etc which is overkill for a simple routing use case. 
- Downstream LLMs can also be any of the numerous chain types that can be supported. This allows for a scalable LLM orchestration model with chaining beyond what's supported today which is mainly Sequential chains.

**Comment by lifan0127** [comment]
I agree model routing is a better terminology than agent/tool for such use cases.

**Comment by Medeirox** [comment]
Does anyone knows why the chains.router package in Langchain isn't available? I had to download the source code and enable it by myself. The documentation talks about it in a way that it seems to be available.
