### ISSUE TITLE
Issue with using LlamaCpp LLM in Pandas Dataframe Agent 

### ISSUE THREAD

**Issue by serena-mafinancial** [langchain-ai/langchain#3569]
I am trying to use the Pandas Agent create_pandas_dataframe_agent, but instead of using OpenAI I am replacing the LLM with LlamaCpp. I am running this in Python 3.9 on a SageMaker notebook, with a ml.g4dn.xlarge instance size. I am having trouble with running this agent and produces a weird error. 

The code is as follows:
![image](https://user-images.githubusercontent.com/129805157/234446661-a5fb5ed5-e632-4c63-b850-9e384b024f32.png)

This is the error log: 
![image](https://user-images.githubusercontent.com/129805157/234446223-499e2ef2-5df8-433d-ba05-9fbed08ce91c.png)
![image](https://user-images.githubusercontent.com/129805157/234446269-ab7ba7e5-3b68-411d-b051-08763a95df0b.png)
![image](https://user-images.githubusercontent.com/129805157/234446303-5bc807ce-747c-4b75-a2d0-7df2921ef550.png)

Detailed error log below: 
![image](https://user-images.githubusercontent.com/129805157/234474222-fd863554-b8d6-4db5-bba6-3edfa031d94a.png)
![image](https://user-images.githubusercontent.com/129805157/234474261-9ace2d31-809b-4b7e-a893-53f1edabacac.png)
![image](https://user-images.githubusercontent.com/129805157/234474284-0e22d4e8-b8df-4498-b963-bb275353d88c.png)
![image](https://user-images.githubusercontent.com/129805157/234474317-2297aec6-4821-45d0-8db3-6e9a81ba8eb6.png)
![image](https://user-images.githubusercontent.com/129805157/234474350-9952596c-a47e-490d-87ad-e7ed418f79fe.png)
![image](https://user-images.githubusercontent.com/129805157/234474376-a222688c-eca9-47f4-9701-b0926dfe4f1c.png)

**Comment by serena-mafinancial** [comment]
Update: I added n_ctx=1024 in LlamaCpp to load Vicuna model and got a new error. 
![image](https://user-images.githubusercontent.com/129805157/234486341-720d92bb-e21d-4afb-87e7-8572922d076e.png)

Error:
![image](https://user-images.githubusercontent.com/129805157/234486381-d644a831-a49b-4b2f-808d-3e4da9d18e28.png)
![image](https://user-images.githubusercontent.com/129805157/234486404-580a109b-e8b6-4a52-b95e-91f448d36268.png)

**Comment by AlexHuang2** [comment]
Hi all,

Commenting here for reach instead of starting new issue as it is also just an issue withLlamaCpp LLM and `create_pandas_dataframe_agent`. This is the code:

```
from langchain.llms import LlamaCpp
llm = LlamaCpp(model_path=r"C:\models\7B\llama-7b.ggml.q4_0.bin")
agent = create_pandas_dataframe_agent(llm, df, verbose=True, n_ctx=2048) # I have tried setting n_ctx astronomically large as well to see if that is the true issue; it is not
agent.run('What is the profit figure for 2013?')
```

Commenting here for reach as it fits the title. I get `ValueError: Requested tokens exceed context window of 512` when running that last line.

**Comment by Aditya701** [comment]
Have you got any solutions?

**Comment by Ralphchahwan** [comment]
I'm facing the same issue here

**Comment by kvnsng** [comment]
Just some general observations I've seen the pandas agent is that it doesn't work well with models other than chatgpt. For your `could not parse LLM` error. Try passing in this output parser:

```
from langchain.agents.mrkl.output_parser import MRKLOutputParser

agent = create_pandas_dataframe_agent(llm, 
                                      df, 
                                      verbose=True,
                                      output_parser=MRKLOutputParser())
```

This should help with parsing the output to be fed to the agent. However, I've noticed the outputs generated by models other than chatgpt doesn't really work well.

Hope this helps

**Comment by deepthi97midasala** [comment]
Entering new AgentExecutor chain...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-32-68cfd5a40627>](https://localhost:8080/#) in <cell line: 2>()
      1 # results = agent("how many records are there? Give me rows and columns")
----> 2 agent1.run("what is the shape of dataframe")

18 frames
[/usr/local/lib/python3.10/dist-packages/langchain/llms/llamacpp.py](https://localhost:8080/#) in _get_parameters(self, stop)
    249         # Raise error if stop sequences are in both input and default params
    250         if self.stop and stop is not None:
--> 251             raise ValueError("`stop` found in both the input and default params.")
    252 
    253         params = self._default_params

ValueError: `stop` found in both the input and default params.

**Comment by deepthi97midasala** [comment]
i get this error i am using pandas data frame

**Comment by deepthi97midasala** [comment]
> Entering new AgentExecutor chain...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-16-67fb461b3cc1>](https://localhost:8080/#) in <cell line: 1>()
----> 1 agent.run(" What are the applications where high volume of tickets are reported in the last 6 months?")

18 frames
[/usr/local/lib/python3.10/dist-packages/llama_cpp/llama.py](https://localhost:8080/#) in _create_completion(self, prompt, suffix, max_tokens, temperature, top_p, logprobs, echo, stop, frequency_penalty, presence_penalty, repeat_penalty, top_k, stream, tfs_z, mirostat_mode, mirostat_tau, mirostat_eta, model, stopping_criteria, logits_processor, grammar)
    898 
    899         if len(prompt_tokens) >= llama_cpp.llama_n_ctx(self.ctx):
--> 900             raise ValueError(
    901                 f"Requested tokens ({len(prompt_tokens)}) exceed context window of {llama_cpp.llama_n_ctx(self.ctx)}"
    902             )

ValueError: Requested tokens (9064) exceed context window of 4096

**Comment by deepthi97midasala** [comment]
getting this i have dataframe with 2047 records
 i have given prompt as agent.run(" What are the applications where high volume of tickets are reported in the last 6 months?") please help me
