### ISSUE TITLE
import error ContextualCompressionRetriever

### ISSUE THREAD

**Issue by mikelval82** [langchain-ai/langchain#3585]
Hi,

I have installed langchain-0.0.149 using pip. When trying to run the folloging code I get an import error.

from langchain.retrievers import ContextualCompressionRetriever

Traceback (most recent call last):
File ".../lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
from langchain.retrievers import ContextualCompressionRetriever
ImportError: cannot import name 'ContextualCompressionRetriever' from 'langchain.retrievers' (.../lib/python3.10/site-packages/langchain/retrievers/init.py)

Thanks in advance,
Mikel.

**Comment by jpdus** [comment]
Works for me. Did you maybe install 0.0.149 in a different environment?

```python
import langchain
langchain.__version__
```
?
