### ISSUE TITLE
OpenAPI agents did not execute tools

### ISSUE THREAD

**Issue by bjcodereview3** [langchain-ai/langchain#3588]
I'm using OpenAPI agents to access my own APIs. and the LLM I'm using is OpenAI's GPT-4.

When I queried something, LLM just answered not only `Action` and `Action Input`, but also `Observation` and even `Final Answer` with fake data under API_ORCHESTRATOR_PROMPT. 
So the agent did not work with `api_planner` and `api_controller` tools.

I am wondering is `API_ORCHESTRATOR_PROMPT` or `FORMAT_INSTRUCTIONS` prompt stable? 
I tested the [Agent Getting Started](https://python.langchain.com/en/latest/modules/agents/getting_started.html), and got bad answer from llm directly without tools sometimes, ether.

or am i missing something important?

or should i rewrite the prompt?

thanks

**Comment by wangqiang-kubota** [comment]
@dosu-beta I faced the similar issue, I was connect to IBM watsonx with langchain agent. In the past, it worked fine, but I tried to update langchain to the latest version, the tool was not triggered. And the answer is coming from big language model. Please let me know what I missed? Thank you!

**Comment by devstein** [comment]
Hey @wangqiang-kubota as of now Dosu only responds to the author of issues. Can you share a code snippet? In general, the downside of agents are that they are probabilistic. It's not uncommon for tool use to fail even with larger models. I suggest modifying the prompts (or tool descriptions) if possible
