### ISSUE TITLE
UnstructuredMarkdownLoader strips Markdown formatting from documents, rendering MarkdownTextSplitter non-functional

### ISSUE THREAD

**Issue by bluesheep** [langchain-ai/langchain#3591]
I am using the DirectoryLoader, with the relevant loader class defined
```
DirectoryLoader('.\\src', glob="**/*.md", loader_cls=UnstructuredMarkdownLoader)`
```

I couldn't understand why the following step didn't chunk text into the relevant markdown sections:

```
markdown_splitter = MarkdownTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = markdown_splitter.split_documents(docs)
```

After digging into it a bit, the UnstructuredMarkdownLoader strips the Markdown formatting from the documents. This means that the Splitter has nothing to guide it and ends up chunking into 1000 text character sizes.

**Comment by tcapelle** [comment]
What "kind of" works for me is doing:

```python
from langchain.document_loaders import TextLoader
from langchain.text_splitter import MarkdownTextSplitter

# just ingest the Markdown file raw
data = TextLoader(one_file)

# split using Markdown rules
markdown_splitter = MarkdownTextSplitter(chunk_size=500, chunk_overlap=0)
split_docs = markdown_splitter.split_documents(docs)

```

My issue is that the splitter strips the markdown afterward, so we get a title with the same relevance as a paragraph. It also destroy code blocks sometimes.

**Comment by starpause** [comment]
Have you since tried [MarkdownHeaderTextSplitter](https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/markdown_header_metadata) which preserves all of the headings in metadata of each page/chunk?

**Comment by paolomainardi** [comment]
I have the same issue now and opened a discussion: https://github.com/langchain-ai/langchain/discussions/26976

I didn't understand if i've just misinterpreted what UnstructuredMarkdownLoader should do, at the moment passing in a markdown file, i get just raw text, that is very bad cause I want to keep formatting as I am building a RAG app using markdown files.

What @tcapelle works but as he said, it is quite dangerous.
