### ISSUE TITLE
Unable to create opensearch index.

### ISSUE THREAD

**Issue by msinha251** [langchain-ai/langchain#3595]
Hi Team, I am using opensearch as my vectorstore and trying to create index for documents vectors. but unable to create index:

Getting error:

`ERROR - The embeddings count, 501 is more than the [bulk_size], 500. Increase the value of [bulk_size]`

Can someone please advice ?

Thanks

**Comment by naveentatikonda** [comment]
@msinha251 we are setting a default max limit for bulk_size as 500 and [validating the embeddings count](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/opensearch_vector_search.py#L60-L68) with this max limit. So, if you need to ingest embeddings more than 500 then, increase the limit by sending it as an argument like `bulk_size=1000`
