### ISSUE TITLE
Non OpenAI models

### ISSUE THREAD

**Issue by darth-veitcher** [langchain-ai/langchain#3622]
It would be good to get some more documentation and examples of using models other than OpenAI. Currently the docs are really heavily skewed and in some areas such as conversation only offer an OpenAI option. 

Thanks

**Comment by charbull** [comment]
@darth-veitcher I tried gpt4all but sometimes crashes my session,
https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html
