### ISSUE TITLE
Document Loaders: GoogleDriveLoader hidden option to load spread sheets

### ISSUE THREAD

**Issue by adrianlzt** [langchain-ai/langchain#3637]
In the [docs](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/googledrive.html) of the GoogleDriveLoader says ``Currently, only Google Docs are supported``, but then, in the  [code](https://github.com/hwchase17/langchain/blob/8e10ac422e4e6b193fc35e1d64d7f0c5208faa8d/langchain/document_loaders/googledrive.py#L100), there is a function ``_load_sheet_from_id``.

That function is only used for folder loading.

Accessing the _private_ method of the class is it possible, and works perfectly, to load spread sheets:
```
from langchain.document_loaders import GoogleDriveLoader
spreadsheet_id = "122tuu4r-yYng8Lj7XXXUgb-basdbk"
loader = GoogleDriveLoader(file_ids=[spreadsheet_id])
docs = loader._load_sheet_from_id(spreadsheet_id)
```

Probably ``_load_documents_from_ids`` needs some refactor to work based on the mimeType, as ``_load_documents_from_folder`` does.

**Comment by IanRogers-101Ways** [comment]
This seems to have been fixed in https://github.com/langchain-ai/langchain/pull/4926 ?

**Comment by lumenintellects** [comment]
@IanRogers-101Ways Seems that `file_types` attribute is supported only when for folder loading, when loading a list of files by id, the following error occurs: ```
pydantic.error_wrappers.ValidationError: 1 validation error for GoogleDriveLoader
__root__
  file_types can only be given when folder_id is given, (not when document_ids or file_ids are given). (type=value_error)
```
