### ISSUE TITLE
Sequential chains vs multiple LLMChains (Why prefer one over the other?)

### ISSUE THREAD

**Issue by KeshavSingh29** [langchain-ai/langchain#3638]
Brief summary: 
Need to solve multiple tasks in sequence (eg: translate an input -> use it to answer question -> translate to different language) 
Previously was making multiple LLMChain objects with different prompts and passing outputs of one chain into another.
Came across sequential chains, tried it. 

I didnt find any big difference on why I should use one over the other. Moreover, sequential chains seem to be slower than just calling multiple LLMChains. 

Anything I'm missing, or if anyone can elaborate the need of sequential chains.
Thanks!!

**Comment by codeananda** [comment]
One reason must be that a SequentialChain encapsulates the logic into a single class you can move around and use however you like. If you are using multiple individual chains, you need to wrap them in *something* in order to, say, load the code into multiple files and use it across your codebase.

**Comment by prosa-trebu** [comment]
Hi @codeananda,  thanks for sharing your knowledge.
You know, I have a problem related to this topic.
I am in doubt about whether to use SequentialChain or multiple LLMChains because I am solving a task where, if the result of the first link is False, I need it to brake.
What would you recommend me? Currently, i am using LLMChains, because I can't find any docs about how to solve my problem.

**Comment by prosa-trebu** [comment]
Thanks, @codeananda ! 
I've been using the first suggestion you mentioned. I'll read more about RouterChain later.
I think SequentialChains is intended to solve problems related to chatbots (not my field right now).

I recently solved a problem with SequentialChain, here's an example in case you need.

```

first_tamplate = """ this is a prompt bla bla bla  ####{message}#### """
first_prompt_tamplate = PromptTemplate(input_variables=["message"], template=first_tamplate)
first_chain = LLMChain(llm=llm, prompt=first_prompt_tamplate, output_key="output_first_chain")


second_tamplate = """ this is the second template prompt bla bla bla  ####{output_first_chain}#### """
second_prompt_tamplate = PromptTemplate(input_variables=["output_first_chain"], template=second_tamplate)
second_chain = LLMChain(llm=llm, prompt=second_prompt_tamplate, output_key="output_second_chain")

overall_chain = SequentialChain(
    chains=[first_chain,
            second_chain],
    input_variables=["message"],
    # Here we return multiple variables
    output_variables=["output_first_chain","output_second_chain",],
    verbose=True)

```
