### ISSUE TITLE
Langchain connection to remote DB takes a lot of time

### ISSUE THREAD

**Issue by maby200** [langchain-ai/langchain#3645]
I am using Langchain package to connect to a remote DB. The problem is that it takes a lot of time (sometimes more than 3 minutes) to run the SQLDatabase class. To avoid that long time I am specifying just to load a table but still is taking up to a minute to do that work. Here the code:

```python
from langchain import OpenAI
from langchain.sql_database import SQLDatabase
from sqlalchemy import create_engine

# already loaded environment vars 

llm = OpenAI(temperature=0)

engine = create_engine("postgresql+psycopg2://{user}:{passwd}@{host}:{port}/chatdatabase")

include_tables=['table_1']

db = SQLDatabase(engine, include_tables=include_tables)

...
```

As in the documentation, Langchain uses SQLAlchemy in the background for making connections and loading tables. That is why I tried to make a connection with pure SQLAlchemy and not using langchain:

```python
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://{user}:{passwd}@{host}:{port}/chatdatabase")

with engine.connect() as con:

  rs = con.execute('select * from table_1 limit 10')
  for row in rs:
    print(row)
```

And surprisingly it takes just few seconds to do so.

Is there any way or documentation to read (I've searched but not lucky) so that this process can be faster?

**Comment by Veeeetzzzz** [comment]
How big is your table, how many rows and what size?

It looks like the main issue is with the fact that table_1 is taking a while to import or there is performance issue with the SQL Database Agent itself.

Just a note on your code - the second snippet will naturally be faster as your SELECT query is only returning 10 rows - on the other hand the first snippet is importing a table. Two different functions being performed.

It might be worth logging some other details on here so we can try replicate - would be interesting to know if you're using localhost or if the DB is hosted somewhere else.

**Comment by maby200** [comment]
Thank you for answering.

Table_1 has 8 rows and 2 columns. It is used for tests or as a playground. So it also means limit wont affect.
One question I have about SQLDatabase is: when I specify _**include_tables**_ , will it only load that table? The database actually has 466 tables.

**Comment by Veeeetzzzz** [comment]
Thanks for the additional detail and it's good to rule out a large dataset/unoptimized DB being the issue. 

You are correct - by specifying table_1 as a flag you're telling it to only import table 1 and ignore the other 465.

I think it's worth us trying to replicate the issue - I will run some further tests and report back. The documentation doesn't seem to go into much detail about mySQL other than what format the connection string needs to be - https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html - I wonder if it's to do with how LangChain is using sqlalchemy  - that seems more likely than there being an issue with the create_engine function

**Comment by maby200** [comment]
Yes it seems more related to LangChain given the both cases (connecting to the same database using pure SQLAchemy and using LangChain) the latter takes way to much time than the first.

Thank you @Veeeetzzzz :)

**Comment by Veeeetzzzz** [comment]
I did some further testing with your code to see if I could replicate the timing:

![image](https://user-images.githubusercontent.com/40268197/235323941-07ac7d85-7802-46ca-88c5-d9956449ad87.png)

I'm using localhost so I'm now wondering if your remote DB might be a factor? Perhaps some latency issues are at play here?

It's weird that it would run faster when using just SQLAlchemy but I'm not able to replicate the performance issues

I will see if the same happens with a remote DB

**Comment by maby200** [comment]
Thank you for your time trying to replicate this.
That would be great if you connect to a big database(either in amount of
tables or columns per table) and try the same.

**Comment by tdnueve** [comment]
I have the same problem, the line `db = SQLDatabase.from_uri(XXXX)` takes more than 5 minutes to connect to a database with more than 200 tables.

**Comment by maby200** [comment]
That is a lot of time. What would be making this happen

**Comment by Veeeetzzzz** [comment]
I initially thought network latency might be at play here but I can't seem to replicate - I tested this with a remote PostgreSQL DB on Vercel - 100 rows with data:

![image](https://user-images.githubusercontent.com/40268197/235884944-65400ff7-f23f-4ec8-a1de-5b6a1fbf881b.png)

Took longer but nothing out of the ordinary: 

![image](https://user-images.githubusercontent.com/40268197/235885266-5f285641-eefc-432f-b8cf-b9e0cac9a8ef.png)

Can either of you connect to the DB using pgAdmin? It may be worth looking at the SQL DB performance to see if there's any delay on that side.

![image](https://user-images.githubusercontent.com/40268197/235887518-07778c1c-24f5-4f0c-afba-a54fd3ee41d3.png)

**Comment by caffreyN** [comment]
This is not exactly related to this conversation subject but I can't find a better place to ask this question.

I have my tables in a different schema and not in the public schema. The SQLDatabase agent from langchain is able to fetch the tables from the public schema but not from the the other schema I have created. Does any of you know a solution to this?

Thanks in advance!

**Comment by dongzeli95** [comment]
I can confirm this issue, I tested langchain from_uri function vs using pure sqlalchemy. The langchain function takes 10 more seconds for connecting to the same database. Could someone take a look?

**Comment by Veeeetzzzz** [comment]
@caffreyN @dongzeli95 It might be worth opening a new issue - post your code and replication steps as bug, might need a PR here.

**Comment by nirav0999** [comment]
Its taking a much longer time to connect via the langchain API  as well compared to the SQL Alchemy an SQLlite APIs.

**Comment by naam-nrj** [comment]
I am using `db = SQLDatabase.from_uri(conn_str)` function to connect to the database. It's taking around 13 minutes to connect.
There are 140 tables in the database and each table has many columns. May be the size of database affects the connection time? Did anyone find the solution to this?

**Comment by Veeeetzzzz** [comment]
I think there's other factors at play - I connect to a local/remote DB from both local and an hosted environment and my DB has 100+ rows. All operations were completed within 5 seconds but other users said they could only see the delay when Langchain was invoked.

**Comment by samsingh12** [comment]
I had the same issue. The langchain SQLDatabase Class has these lines at the end which inspects every table in the database irrespective of "include_tables" list. These lines don't assign anything to anything. Commenting these out made the connection < 0.5 sec. 

        self._max_string_length = max_string_length
        self._metadata = metadata or MetaData()
        # including view support if view_support = true
        # self._metadata.reflect(
        #     views=view_support,
        #     bind=self._engine,
        #     only=list(self._usable_tables),
        #     schema=self._schema,
        # )

**Comment by josebarrueta** [comment]
Thanks to @samsingh12  for the hint, this must be fixed. 

Trying the following and seems to have no effect in the execution:

```
class NoReflectMetadata(MetaData):
    def reflect(
        self,
        bind=None,
        schema=None,
        views=False,
        only=None,
        extend_existing=False,
        autoload_replace=True,
        resolve_fks=True,
        **dialect_kwargs,
    ):
        pass
```

```
```

**Comment by Ali-Raza12** [comment]
Inside SQLDatabase class, `self._metadata.reflect()` loads information about the specified tables and views, and stores that information in the MetaData object associated with the current SQLAlchemy session. If you comment out this function as mentioned by @samsingh12  then you won't be able to use class methods such as `db.get_table_info()`. So if you want to use these methods then assign `self.include_tables` to `only` in `self._metadata.reflect()` as follows;
```
self._metadata.reflect(
    views=view_support,
    bind=self._engine,
    only=self._include_tables,
    schema=self._schema,
)
```

In this way you can use class methods for the tables included without get delayed response.

**Comment by tmbluth** [comment]
@Veeeetzzzz I have been having the same issue and followed the advice here:

https://stackoverflow.com/questions/76525263/langchains-sqldatabasesequentialchain-to-query-database

However, it seems I cannot query any views

**Comment by josebarrueta** [comment]
Sharing the way we worked around this issue, in case it helps anyone. As @Ali-Raza12 mentioned the suggested approach was not complete. In our case we don't know what tables are we going to be fetching ahead of time, so instead of not allowing to fetch metadata we deferred the initialization of them to be loaded on demand. 

```
from langchain.sql_database import SQLDatabase as BaseSQLDatabase

class SQLDatabase(BaseSQLDatabase):
    """
    This class takes the Langchain SQLDatabase class and overrides the
    get_table_info method to allow lazy loading of metadata tables.
    """

    def __init__(self, *args, **kwargs):
        super(SQLDatabase, self).__init__(*args, **kwargs)

    def get_table_info(self, table_names: Optional[List[str]] = None) -> str:
        if table_names is None:
            return ""

        loaded_tables = self._metadata.tables

        tables_to_load = []

        for table_name in table_names:
            if table_name not in loaded_tables:
                tables_to_load.append(table_name)

        if len(tables_to_load) > 0:
            self._metadata.reflect(bind=self._engine, only=tables_to_load)

        return super().get_table_info(table_names)


class LazyReflectMetadata(MetaData):
    def __init__(self):
        super().__init__()
        self._initial_reflect = True

    def reflect(
        self,
        bind=None,
        schema=None,
        views=False,
        only=None,
        extend_existing=False,
        autoload_replace=True,
        resolve_fks=True,
        **dialect_kwargs,
    ):
        if self._initial_reflect:
            logging.debug("Ignoring _initial_reflect due to initialization.")
            self._initial_reflect = False
        else:
            logging.debug("Calling reflect with tables=%s", only)
            return super().reflect(
                bind,
                schema,
                views,
                only,
                extend_existing,
                autoload_replace,
                resolve_fks,
                **dialect_kwargs,
            )
```

A little hacky on the way we initialize `LazyReflectMetadata` but it worked for us to fetch the tables on demand and sped up the db initialization.

**Comment by maby200** [comment]
Hi, It is ok now. The problem did not appeared again. Thank you :)

**Comment by NisaarAgharia** [comment]
> @Veeeetzzzz I have been having the same issue and followed the advice here:
> 
> 
> 
> https://stackoverflow.com/questions/76525263/langchains-sqldatabasesequentialchain-to-query-database
> 
> 
> 
> However, it seems I cannot query any views


Were you able to query the view

**Comment by Veeeetzzzz** [comment]
> > @Veeeetzzzz I have been having the same issue and followed the advice here:
> > https://stackoverflow.com/questions/76525263/langchains-sqldatabasesequentialchain-to-query-database
> > However, it seems I cannot query any views
> 
> Were you able to query the view

Hello @NisaarAgharia 

I've never had any issues with the initial import taking longer than 5s and I've never had to modify the init function so I'm not entirely sure what the issue was here, I'm guessing it will depend on the data in your DB + other factors like remote db latency etc.

Given that the OP's issue's resolved itself - I can only assume OP's issue was down to the remote DB connection

Would recommend opening a new issue + posting your code for a review

**Comment by Adyansh-RCRM** [comment]
> Hi, It is ok now. The problem did not appeared again. Thank you :)

@maby200
Can you please tell how did you fix this? I am also facing similar issue while connecting redshift db cluster to langchain.

**Comment by TinyCalf** [comment]
> > Hi, It is ok now. The problem did not appeared again. Thank you :)
> 
> @maby200 Can you please tell how did you fix this? I am also facing similar issue while connecting redshift db cluster to langchain.

like https://stackoverflow.com/questions/76525263/langchains-sqldatabasesequentialchain-to-query-database mentioned

we dont need to comment source code of SQLDatabase but pass "lazy_table_reflection" will also achieve the same thing：
```
from sqlalchemy import create_engine
engine = create_engine("mysql://{user}:{pass}@{url}/database")
from langchain_community.utilities import SQLDatabase
DB= SQLDatabase(engine=engine, lazy_table_reflection=True)
```

**Comment by thematica** [comment]
anyone tried this fix with 1TB+ database? 
i tried lazy_table_reflection=True but the connection still very slow (tried waiting 10min but still not connected)

using the same code, i can connect just fine with new database contain only 1 table with 1 column and 30 rows data

sorry, should i open new thread or i can use this one?
