### ISSUE TITLE
logging Generation text type error

### ISSUE THREAD

**Issue by dinggege1024** [langchain-ai/langchain#3654]
![image](https://user-images.githubusercontent.com/109070189/234898722-419457e3-335c-45ea-bd15-c75227f4ee5c.png)

if return text is not str, there is nothing helpful info

**Comment by dinggege1024** [comment]
https://github.com/hwchase17/langchain/pull/3657

**Comment by vowelparrot** [comment]
@dinggege1024 could you provide example code to reproduce?
