### ISSUE TITLE
pgvector embedding length error

### ISSUE THREAD

**Issue by walker83** [langchain-ai/langchain#3660]
When i use other embedding model,the vector dimensions  is always wrong.  So i use 'None' to replace ADA_TOKEN_COUNT.
It will be auto compute how many dimensions when first time to use an embedding model.

I use 'GanymedeNil/text2vec-large-chinese' test and success.

so i change this :

embedding: Vector = sqlalchemy.Column(Vector(ADA_TOKEN_COUNT))

to this 

embedding: Vector = sqlalchemy.Column(Vector(None))

**Comment by SeriyVol4ishe** [comment]
#4203

**Comment by Tostino** [comment]
Just want to mention that this is still something that I am hitting now a few months later. Any chance one of the branches that have fixed it will be merged in soon?

**Comment by slix88** [comment]
Any possibility of fixing the code in the repo? Still an issue...
