### ISSUE TITLE
Error creating AgentExecutor with custom Toolkit

### ISSUE THREAD

**Issue by Punisheroot** [langchain-ai/langchain#3680]
Hi, I am in the process of developing an agent and a toolkit to query mongodb databases, and to do this I simulated SQL Database Agent code with implementations for mongodb, I created this function to create the agent:

```
def create_mongodb_agent(
    llm: BaseLLM,
    toolkit: MongoDBDatabaseToolkit,
    callback_manager: Optional[BaseCallbackManager] = None,
    prefix: str = MONGODB_PREFIX,
    suffix: str = MONGODB_SUFFIX,
    format_instructions: str = FORMAT_INSTRUCTIONS,
    input_variables: Optional[List[str]] = None,
    top_k: int = 10,
    max_iterations: Optional[int] = 15,
    max_execution_time: Optional[float] = None,
    early_stopping_method: str = "force",
    verbose: bool = False,
    **kwargs: Any,
) -> AgentExecutor:
    """Construct a MongoDB agent from an LLM and tools."""
    tools = toolkit.get_tools()
    prefix = prefix.format(top_k=top_k)
    prompt = ZeroShotAgent.create_prompt(
        tools,
        prefix=prefix,
        suffix=suffix,
        format_instructions=format_instructions,
        input_variables=input_variables,
    )
    llm_chain = LLMChain(
        llm=llm,
        prompt=prompt,
        callback_manager=callback_manager,
    )
    tool_names = [tool.name for tool in tools]
    agent = ZeroShotAgent(llm_chain=llm_chain, allowed_tools=tool_names, **kwargs)
    return AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        verbose=verbose,
        max_iterations=max_iterations,
        max_execution_time=max_execution_time,
        early_stopping_method=early_stopping_method,
    )
```
and this is my ToolKit:

```
class MongoDBDatabaseToolkit(BaseToolkit):
    """Toolkit for interacting with MongoDB databases."""

    db: MongoDBDatabase = Field(exclude=True)
    llm: BaseLLM = Field(default_factory=lambda: OpenAIChat(temperature=0))

    class Config:
        """Configuration for this pydantic object."""

        arbitrary_types_allowed = True

    def get_tools(self) -> List[BaseTool]:
        """Get the tools in the toolkit."""
        return [
            QueryMongoDBDatabaseTool(db=self.db),
            InfoMongoDBDatabaseTool(db=self.db),
            ListMongoDBDatabaseTool(db=self.db),
            QueryCheckerTool(db=self.db, llm=self.llm),
        ]
```
but I get the error from the AgentExecutor validator:
```
File "..\env\lib\site-packages\langchain\agents\initialize.py", line 64, in initialize_agent
    return AgentExecutor.from_agent_and_tools(
  File "..\env\lib\site-packages\langchain\agents\agent.py", line 557, in from_agent_and_tools
    return cls(
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "..\env\lib\site-packages\langchain\agents\agent.py", line 565, in validate_tools
    tools = values["tools"]
KeyError: 'tools'
```
I did some debugging and verified that the tools are passed correctly to the AgentExecutor.from_agent_and_tools function. Can anyone help me with this?

**Comment by jeromeku** [comment]
Ran into similar problem.  

The issue seems to be that `BaseTool` class subclasses pydantic `BaseModel`: 
- During root validation phase of pydantic, the tool is not passing its check and therefore is not being passed to any methods marked `@root_validator()` in `AgentExecutor`, e.g., `validate_tools`, hence the `KeyError`.  See here for more details on [root validation](https://docs.pydantic.dev/latest/usage/validators/#root-validators).
- If you remove or comment out the `@root_validator()` decorators, you'll probably get a more informative message as to why pydantic validation is failing.
- For me, it was because my tool had an internal object that pydantic was complaining couldn't be pickled.  Haven't figured out fix yet, but my guess is that you'll have to customize the `Config` of `BaseTool`.

**Comment by jeromeku** [comment]
@Punisheroot 

Issue resolved for me.  Try running your custom tool with the following env:

```
langchain==0.0.162
openapi-schema-pydantic==1.2.4
pydantic==1.10.7
```

**Comment by Punisheroot** [comment]
> @Punisheroot
> 
> Issue resolved for me. Try running your custom tool with the following env:
> 
> ```
> langchain==0.0.162
> openapi-schema-pydantic==1.2.4
> pydantic==1.10.7
> ```

Hi @jeromeku i tried but still the same error 😢

**Comment by Zhreyu** [comment]
@Punisheroot How well did your custom chain work?
