### ISSUE TITLE
TimeWeightedVectorStoreRetriever (TWVSR) and ChromaDb  vector store  - base.py

### ISSUE THREAD

**Issue by isdsava** [langchain-ai/langchain#3685]
Hi there. 

Realise there is a lot happening and this this looks to be something that has been missed. When trying to use TWVSR with ChromaDb it errors because of the lack of implementation of the following, namely __similarity_search_with_relevance_scores, inside of base.py

    `def _similarity_search_with_relevance_scores(
        self,
        query: str,
        k: int = 4,
        **kwargs: Any,
    ) -> List[Tuple[Document, float]]:
        """Return docs and relevance scores, normalized on a scale from 0 to 1.
        0 is dissimilar, 1 is most similar.
        """
        raise NotImplementedError`

Trying to make a work-around now
Many thanks
Ian

**Comment by vowelparrot** [comment]
Open to PR's implementing it for Chroma!

**Comment by isdsava** [comment]
I'll try and give it a go.
