### ISSUE TITLE
Enable to skip the reduce step of the MapReduce mode of `MapReduceDocumentsChain`

### ISSUE THREAD

**Issue by yu-iskw** [langchain-ai/langchain#3694]
## Motivation
The Map step is scalable as long as we split documents into chunks. Meanwhile, as far as I know, the Reduce step has a weak point on the limitation of max tokens of a LLM model, since the Reduce step tries to put all summaries generated in the Map step into a prompt of the Reduce step. So, if all summaries generated in the Map step is too large to put in a request to a LLM model, it meets the max tokens quota. 

So, it would be good to enable to skip the Reduce step and to get outputs of the intermediate steps. By doing so, we can deal with the outputs with the Refine mode and so on.

```python
chain = load_summarize_chain(chain_type="map_reduce", skip_reduce=True)
```

**Comment by yu-iskw** [comment]
I came up with a workaround idea. The LLM for the reduce step receives a parameterized prompt with `{text}` by default. So, if we don't put the parameter `{text}` to the prompt of the reduce step, we can technically get intermediate outputs of the map step without the issue of max token exceeded.

**Comment by crudalex** [comment]
This would be a very useful feature to have.

**Comment by maheshbansod** [comment]
I'm looking for a way to just concatenate the outputs of the map calls, instead of having a reduce step.
I think this is something which would allow me to do it.

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/blob/b5c9663bb0d358020ba29c8a346f9b0d0477edf2/src/utils_langchain.py#L163-L321
