### ISSUE TITLE
Missing key title in metadata with UnstructuredFileLoader

### ISSUE THREAD

**Issue by olivierb2** [langchain-ai/langchain#3704]
I'm trying to store vector in Milvus with the following code

~~~
from os import environ

MILVUS_HOST = "xxx"
MILVUS_PORT = "xxx"
OPENAI_API_KEY = "xxx"

## Set up environment variables
environ["OPENAI_API_KEY"] = OPENAI_API_KEY

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Milvus
from langchain.document_loaders import UnstructuredMarkdownLoader
from langchain.text_splitter import MarkdownTextSplitter

# Use the WebBaseLoader to load specified web pages into documents
loader = UnstructuredMarkdownLoader("./content.md", mode="elements")

docs = loader.load()

# Split the documents into smaller chunks
text_splitter = MarkdownTextSplitter(chunk_size=1024, chunk_overlap=0)

docs = text_splitter.split_documents(docs)

# print(docs[0])

# Set up an embedding model to covert document chunks into vector embeddings.
embeddings = OpenAIEmbeddings(model="ada")

# Set up a vector store used to save the vector embeddings. Here we use Milvus as the vector store.
vector_store = Milvus.from_documents(
    docs,
    embedding=embeddings,
    connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT}
)
~~~

But I'm getting an error

~~~
Traceback (most recent call last):
  File "/home/olivierb/Developments/experiments/openai/import_lang.py", line 35, in <module>
    vector_store = Milvus.from_documents(
  File "/home/olivierb/Developments/experiments/openai/venv/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 272, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/home/olivierb/Developments/experiments/openai/venv/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 804, in from_texts
    vector_db.add_texts(texts=texts, metadatas=metadatas)
  File "/home/olivierb/Developments/experiments/openai/venv/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 436, in add_texts
    insert_list = [insert_dict[x][i:end] for x in self.fields]
  File "/home/olivierb/Developments/experiments/openai/venv/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 436, in <listcomp>
    insert_list = [insert_dict[x][i:end] for x in self.fields]
KeyError: 'title'
~~~

It seems that Document have missing metadata.title

~~~
page_content='xxx' metadata={'source': './content.md, 'page_number': 1, 'category': 'Title'}
~~~

**Comment by ah-kim** [comment]
Have you resolved this issue?

**Comment by 631068264** [comment]
Similar  error when use  `TextLoader`  and  `Milvus `

```
Traceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 59, in <module>
    load()
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 33, in load
    qa.add_docs(doc)
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/vector/qa.py", line 97, in add_docs
    pks = self.vectorstore.add_documents(docs)
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 104, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in add_texts
    insert_list = [insert_dict[x][i:end] for x in self.fields]
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in <listcomp>
    insert_list = [insert_dict[x][i:end] for x in self.fields]
KeyError: 'filename'
```


```
Traceback (most recent call last):
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 59, in <module>
    load()
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 33, in load
    qa.add_docs(doc)
  File "/data/home/yaokj5/dl/apps/intell-chat-backend/vector/qa.py", line 96, in add_docs
    pks = self.vectorstore.add_documents(docs)
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 104, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in add_texts
    insert_list = [insert_dict[x][i:end] for x in self.fields]
  File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in <listcomp>
    insert_list = [insert_dict[x][i:end] for x in self.fields]
KeyError: 'filename'
```

**Comment by olivierb2** [comment]
I artifically fixed the issue with the following code

~~~
docs = text_splitter.split_documents(docs)

new_doc = []
for doc in docs:
    met = doc.metadata
    met['title'] = "test"
    met['description'] = "test"
    met['language'] = 'us'
    new_doc.append(Document(
        page_content=doc.page_content,
        metadata=met
        )
    )

# Set up an embedding model to covert document chunks into vector embeddings.
embeddings = OpenAIEmbeddings(model="ada")
~~~

Of course, it should be better to replace test by better value.

**Comment by 631068264** [comment]
In my solution ,  I inheritance the Milvus class and rewrite the `_create_collection` method  to limit the schema 

Example 
```python
class MyMILVUS(Milvus, VectorStore):

    def __init__(
            self,
            embedding_function: Embeddings,
            collection_name: str = "LangChainCollection",
            connection_args: Optional[dict[str, Any]] = None,
            consistency_level: str = "Session",
            index_params: Optional[dict] = None,
            search_params: Optional[dict] = None,
            drop_old: Optional[bool] = False,
    ):
        super().__init__(
            embedding_function=embedding_function,
            collection_name=collection_name,
            connection_args=connection_args,
            consistency_level=consistency_level,
            index_params=index_params,
            search_params=search_params,
            drop_old=drop_old,
        )
        self.score_threshold = VECTOR_SEARCH_SCORE_THRESHOLD
        self.chunk_size = CHUNK_SIZE
        self.logger = None
        self.metadata_field = ['doc_id', 'source']
        self.partition_key_field = 'category_id'

    def _create_collection(
            self, embeddings: list, metadatas: Optional[list[dict]] = None
    ) -> None:
        from pymilvus import (
            Collection,
            CollectionSchema,
            DataType,
            FieldSchema,
            MilvusException,
        )
        from pymilvus.orm.types import infer_dtype_bydata

        # Determine embedding dim
        dim = len(embeddings[0])
        fields = []
        # Determine metadata schema
        if metadatas:
            # Create FieldSchema for each entry in metadata.
            for key, value in metadatas[0].items():
                if self.metadata_field and key not in self.metadata_field:
                    # limit the meta field for  schema  about https://github.com/langchain-ai/langchain/issues/3704
                    continue
```

**Comment by chandrakalagowda** [comment]
> Document

Hello were you able to resolve this I have the same issue.

**Comment by chandrakalagowda** [comment]
> Similar error when use `TextLoader` and `Milvus `
> 
> ```
> Traceback (most recent call last):
>   File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 59, in <module>
>     load()
>   File "/data/home/yaokj5/dl/apps/intell-chat-backend/load_file.py", line 33, in load
>     qa.add_docs(doc)
>   File "/data/home/yaokj5/dl/apps/intell-chat-backend/vector/qa.py", line 97, in add_docs
>     pks = self.vectorstore.add_documents(docs)
>   File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 104, in add_documents
>     return self.add_texts(texts, metadatas, **kwargs)
>   File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in add_texts
>     insert_list = [insert_dict[x][i:end] for x in self.fields]
>   File "/data/home/yaokj5/anaconda3/envs/intell/lib/python3.10/site-packages/langchain/vectorstores/milvus.py", line 458, in <listcomp>
>     insert_list = [insert_dict[x][i:end] for x in self.fields]
> KeyError: 'filename'
> ```
> 
> page_content='xxx' metadata={'source': './content.md'}
> 
> metadata only get the 'source'

Hello were you able to resolve this I have the same issue.

**Comment by 631068264** [comment]
@chandrakalagowda 
<img width="720" alt="image" src="https://github.com/langchain-ai/langchain/assets/8144089/162fd307-25f1-4872-98fc-132035bcb78f">


just add this

**Comment by chandrakalagowda** [comment]
> @chandrakalagowda <img alt="image" width="720" src="https://user-images.githubusercontent.com/8144089/262942990-162fd307-25f1-4872-98fc-132035bcb78f.png">
> 
> just add this

Thank you. I will check and update later.

**Comment by sanjay-raj5** [comment]
@631068264 
After adding the MyMILVUS class, how to call it in this line? 
vector_store = Milvus.from_documents(
    docs,
    embedding=embeddings,
    connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT}
)

**Comment by 631068264** [comment]
> @631068264 After adding the MyMILVUS class, how to call it in this line? vector_store = Milvus.from_documents( docs, embedding=embeddings, connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT} )
> 
> After I called MyMILVUS, I am still getting the same error. Traceback (most recent call last): File "C:\Users\0010IN744\Desktop\Acharya OPS\LangChainProj\milvuslangchain.py", line 96, in vector_db = MyMILVUS.from_documents( ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\0010IN744.virtualenvs\LangChainProj-osz8HcFn\Lib\site-packages\langchain\vectorstores\base.py", line 417, in from_documents return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\0010IN744.virtualenvs\LangChainProj-osz8HcFn\Lib\site-packages\langchain\vectorstores\milvus.py", line 827, in from_texts vector_db.add_texts(texts=texts, metadatas=metadatas) File "C:\Users\0010IN744.virtualenvs\LangChainProj-osz8HcFn\Lib\site-packages\langchain\vectorstores\milvus.py", line 463, in add_texts insert_list = [insert_dict[x][i:end] for x in self.fields] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\0010IN744.virtualenvs\LangChainProj-osz8HcFn\Lib\site-packages\langchain\vectorstores\milvus.py", line 463, in insert_list = [insert_dict[x][i:end] for x in self.fields] ~~~~~~~~~~~^^^ KeyError: 'description'
> 
> Process finished with exit code 1
> 
> Can you please let me know how you resolved this error?

@sanjay-raj5  read this https://github.com/langchain-ai/langchain/issues/3704#issuecomment-1668817324  and you will know why get this error  and how to solve it.

If your data is not important , just reinsert  your data after delete the collection.  My solution  only fit this.  Just use MyMILVUS to replace Milvus  .

If important ,  just filled value for the metadata.    You can follow this https://github.com/langchain-ai/langchain/issues/3704#issuecomment-1669014307

**Comment by LarryStewart2022** [comment]
use a different loader: UnstructuredPDFLoader

**Comment by LarryStewart2022** [comment]
https://python.langchain.com/docs/modules/data_connection/document_loaders

**Comment by shrawani92** [comment]
I created the same mymilvus class but I am using Milvus.from_documents method, how do I use that class here? I tried replacing mymilvus but it does not get called.

I have the below issue-

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain_community/vectorstores/milvus.py:484, in <listcomp>(.0)
    482 end = min(i + batch_size, total_count)
    483 # Convert dict to list of lists batch for insertion
--> 484 insert_list = [insert_dict[x][i:end] for x in self.fields]
    485 # Insert into the collection.
    486 try:

KeyError: 'source'
