### ISSUE TITLE
Errors with DirectoryLoader

### ISSUE THREAD

**Issue by tanayvarshney** [langchain-ai/langchain#3726]
```
from langchain.document_loaders import DirectoryLoader
loader = DirectoryLoader('./server', glob="**/*.md")
data = loader.load()
```

Error
```
    from pdfminer.utils import open_filename
ImportError: cannot import name 'open_filename' from 'pdfminer.utils' (/usr/local/lib/python3.8/dist-packages/pdfminer/utils.py)
```
Langchain version: '0.0.152'

**Comment by ysato** [comment]
Ran into the same issue this morning. I had to downgrade `unstructured` to version 0.6.1.

**Comment by botchagalupe** [comment]
> ```
> from langchain.document_loaders import DirectoryLoader
> loader = DirectoryLoader('./server', glob="**/*.md")
> data = loader.load()
> ```
> 
> Error
> 
> ```
>     from pdfminer.utils import open_filename
> ImportError: cannot import name 'open_filename' from 'pdfminer.utils' (/usr/local/lib/python3.8/dist-packages/pdfminer/utils.py)
> ```
> 
> Langchain version: '0.0.152'

I have the same problem with loading certain pdfs. Is there a way to turn on a trace/debug option when the loader is running so I can see what file if fails on?

**Comment by eminmtas** [comment]
```
from getpass import getpass
from langchain.document_loaders import GitHubIssuesLoader
ACCESS_TOKEN = getpass()
```
```
loader = GitHubIssuesLoader(
    repo="eminmtas/check-license",
    access_token=ACCESS_TOKEN,
    creator="eminmtas",
)
```
Error

```
from langchain.document_loaders import GitHubIssuesLoader
ImportError: cannot import name 'GitHubIssuesLoader' from 'langchain.document_loaders'
```

I am getting this error too. I have the required libraries on my venv.  What to do?

**Comment by advaithgit** [comment]
ImportError: cannot import name 'open_filename' from 'pdfminer.utils'
Tried all the mentioned methods in the net but still getting the same issue.

**Comment by lakshman-11** [comment]
# # Install package
pip install "unstructured[all-docs]"

this worked for me

**Comment by usernameandme** [comment]
Just upgrade your pdfminer.six package. See [here](https://stackoverflow.com/a/77685068/5597718)
