### ISSUE TITLE
Strange document similarity results

### ISSUE THREAD

**Issue by akbaramed** [langchain-ai/langchain#3731]
Hello,

my code is reading "state_of_the_union" text which I converted to a PDF
chromadb.__version__
'0.3.21'

my code is 
##################
# LLM model 
model_path = f"{model_dir}gpt-neo-2.7B"

generate_text = pipeline('text-generation', model = model_path,\
                         max_new_tokens = 100, temperature = 0.99, top_p=0.99,\
                             repetition_penalty=1.4, use_cache=True, do_sample = True)
hf_pipeline = HuggingFacePipeline(pipeline=generate_text)

# embedding model
model_path = f"{model_dir}all-mpnet-base-v2"
hf_embed = HuggingFaceEmbeddings(model_name = model_path)

# load data
data_path = f"{data_dir}state_of_the_union.pdf"
loader = PyPDFLoader(data_path) 
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

db = Chroma.from_documents(texts, hf_embed)

query = "Who is Michael Jackson?" # out of context

retriever = db.as_retriever(search_type="similarity", search_kwargs={"k":2})
# retriever = db.as_retriever() 

# create a chain to answer questions 
qa = RetrievalQA.from_chain_type(
    llm = hf_pipeline, chain_type="stuff", retriever=retriever,\
        return_source_documents=True)
# tried with other chain types as well
    
result = qa({"query": query})

print(result)
########################
My question why is the function returning me results from the source document that dont even match my query 

Results 
{'query': 'Who is Michael Jackson?', 'result': ' We can thank him again.  \nHe was the man who saved us from bankruptcy four times.   \n \nIn 1983, he went to Washington and worked with Congress to enact the Gramm-Leach-Bliley Act creating \nthe Federal Home Loan Mortgage Corporation and the Community Reinvestment Act.  \n \nThese two laws allowed banks to start bringing into the mortgage lending market products that \nwould not have made sense ten years earlier.  ', 'source_documents': [Document(page_content='And I did that 4 days ago, when I nominated ....', metadata={'source': 'LLM_Learnings\\data\\state_union.pdf', 'page': 22}), Document(page_content='Just last year, 55 Fortune 500 corporations earned $40 billion in profits and paid zero dollars in federal \nincome tax.   \n \nThat’s simply not fair. That’s why I’ve proposed a 15% minimum .....', metadata={'source': 'LLM_Learnings\\data\\state_union.pdf', 'page': 14})]}

Other options such as load_qa_chain or FAISS, seem to be working ok 

docs = db.as_retriever().get_relevant_documents(query)
# docs = db.similarity_search_with_score(query)

chain = load_qa_chain(llm = hf_pipeline, chain_type="stuff", prompt = PROMPT)
# gives error when no embedding for the given query are found in the hf_embed
try:
    result = chain({"input_documents": docs, "question": query}, return_only_outputs=False)
except IndexError:
    result = chain({"input_documents": '', "question": query}, return_only_outputs=False)

#### OR using FAISS

try:
    docs_db = faiss.similarity_search_with_relevance_scores(query, k=2)
    docs_db = [x[0] for x in docs_db]
except ValueError:
    docs_db = ""

chain = load_qa_chain(hf_pipeline, chain_type="stuff", prompt = PROMPT)
result = chain({"input_documents": docs_db, "question": query}, return_only_outputs=False)

Any help or advise would be greatly appreciated.

Regards
Akbar

**Comment by mssalvatore** [comment]
The most relevant docs will be returned. In this case, the most relevant docs aren't very relevant. You can use 

```python
my_score_threshold = 0.7  # Set this between [0,1] to your desired threshold, 1 is more similar and 0 is less similar
faiss.similarity_search_with_relevance_scores(query, k=2, score_threshold=my_score_threshold)
```
