### ISSUE TITLE
Serializing Prompts with Partial Variables

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langchain#3735]
I am interested in making use of Prompt serialization in order to allow for more modular use of models / chains.

I noticed when partial variables were initially added in [this PR](https://github.com/hwchase17/langchain/pull/1308), there was some discussion about their interaction with serialized prompts, which resulted in [these lines](https://github.com/hwchase17/langchain/blob/e3b7a20454cea592fc6d0a0d91c36206e8ad6790/langchain/prompts/base.py#L203-L204) being added to disable serialization of prompts with partial variables.

In my testing I found that partial variables seem to work well as is, if those lines are removed, as done in [this PR](https://github.com/hwchase17/langchain/pull/3734).
- https://github.com/hwchase17/langchain/pull/3734

I'm happy to help with developing this feature, but would be interested to hear more about what the reasoning was for initially disabling it, as I am sure there are edge cases I am missing. Thanks!

Cases to be investigated:
- [ ] Partial Variable needs to be redefined after the PROMPT is loaded back from serialization

**Comment by trancethehuman** [comment]
Interested as well!
