### ISSUE TITLE
DOCS: Typo on Components/Schema/Text page

### ISSUE THREAD

**Issue by ruankie** [langchain-ai/langchain#3784]
# Description
There is a typo on the [Components/Schema/Text documentation page](https://docs.langchain.com/docs/components/schema/text). The third sentence starts with:
```
Therefor, a lot of the interfaces...
```

It should be changed to:
```
Therefore, a lot of the interfaces...
```

**Comment by ruankie** [comment]
Please assign this issue to me. I'll start working on it so long... 🙂

**Comment by ruankie** [comment]
I can't seem to find the source code for [these Lnagchain docs](https://docs.langchain.com/docs/). Which repo do they live in?

**Comment by loganthomas** [comment]
+1

**Comment by ruankie** [comment]
The typo is still there at `https://docs.langchain.com/docs/components/schema/text`

However, it looks like the docs have migrated to `https://python.langchain.com/`

Not sure if the aforementioned docs are still in use?
