### ISSUE TITLE
Is not a valid tool, try another one.

### ISSUE THREAD

**Issue by InfinitySoftware-House** [langchain-ai/langchain#3785]
Hi!
I am using GPT4All with agents and Wikipedia as a tool.
I'm getting this error: `is not a valid tool, try another one.`.

I have noticed that in the action there is that: `Action: Use Wikipedia to confirm the accuracy of this information.`
I think it should be `Action: wikipedia`.

**Comment by PawelFaron** [comment]
Please provide working code that can reproduce this issue.

**Comment by kevinhelvig** [comment]
+1

**Comment by InfinitySoftware-House** [comment]
Seems like that LLaMA 7B parameters is not enough to generate a correct output with the real Action name.
I tried OpenAI models and they works as expected.

**Comment by mingfang** [comment]
Doesn't work with `vicuna-13b` either.

**Comment by mikeyang01** [comment]
> Doesn't work with `vicuna-13b` either.

Why

**Comment by mikeyang01** [comment]
as issue as https://github.com/hwchase17/langchain/issues/1559
