### ISSUE TITLE
Pinecone.from_texts() added 'text' metadata field modifies data object passed in as argument AND errors if text size exceeds Pinecone metadata limit per vector

### ISSUE THREAD

**Issue by andrewreece** [langchain-ai/langchain#3800]
The `Pinecone.from_documents()` embeddings-creation/upsert ([based on this example](https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/pinecone.html)) produces two unexpected behaviors:  
1. Mutates the original `docs` object inplace, such that each entry's `Document.metadata` dict now has a 'text' key that is assigned the value of `Document.page_content`.  
2. Does not check whether the addition of this `metadata['text']` entry exceeds the maximum allowable metadata bytes per vector set by Pinecone (40960 bpv), allowing the API call to throw an error in cases where this value is exceeded.  

I was sending a batch of documents to Pinecone using `Pinecone.from_documents()`, and was surprised to see the operation fail on this error:
```
ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Sat, 29 Apr 2023 04:19:35 GMT', 'x-envoy-upstream-service-time': '5', 'content-length': '115', 'server': 'envoy'})
HTTP response body: {"code":3,"message":"metadata size is 41804 bytes, which exceeds the limit of 40960 bytes per vector","details":[]}
```

Because there was just minimal metadata per each record and I'd already sent about 50,000 successfully to Pinecone in the same call.  Then, when I inspected the `docs` list of `Documents` (compiled from `DataFrameLoader().load()`), I was surprised to see the extra `'text'` field in the metadata.  It wasn't until I went poking around in [**pinecone.py**](https://github.com/hwchase17/langchain/blob/adcad98bee03ac8486f328b4f316017a6ccfc808/langchain/vectorstores/pinecone.py#L242) that I found this was an added field that was updating the passed-in `Document.metadata` dicts in-place (because of Python's pass-by-sharing rules about mutability).

Suggestions:  
* If `metadata['text']` is required (I'm not sure it is for Pinecone upserts?), then make the user do that (error and refuse to upsert if it's not there) rather than modify silently in `.from_texts()`.  
* The metadata limit issue would be great to test ahead of the API's HTTP request, could do a quick check on user metadata input to make sure it's not going to get rejected by Pinecone (otherwise warn the user).  In my case, I don't want to make smaller chunks of text (my use case involves a certain number of turns of dialogue in each embedded chunk), but I may just write in a check for overflow and truncate the `'text'` metadata accordingly.  
* Fail gracefully by catching all `ApiException` errors so that the embeddings-creation and upsert process isn't interrupted.
* Maybe consider something like an `add_text_metadata` flag in the call to `from_documents()` so users have the option to have it done automatically for them?

I'm pretty new to LangChain and Pinecone, so if I'm missing something or doing it wrong, apologies - otherwise, hope this is useful feedback!

**Comment by andrewreece** [comment]
One other item to consider: Because [`ids_batch`](https://github.com/hwchase17/langchain/blob/adcad98bee03ac8486f328b4f316017a6ccfc808/langchain/vectorstores/pinecone.py#LL233C34-L233C46) assigns a random UUID, if the upsert fails then I'm not sure how to restart at the right spot (or how to ensure no collisions if I try to restart in the middle)

**Comment by FayZ676** [comment]
I'm having the same issue, thanks for bringing this up

**Comment by andrewreece** [comment]
I used this filter, based on byte length, which helped prevent the API error.
```
byte_max = 30000

def utf8len(s):
    return len(s.encode('utf-8'))

screened_docs = list()

for i, doc in enumerate(loaded_docs):
    if utf8len(doc.page_content) <= byte_max:
        screened_docs.append(doc)
```

**Comment by asidapara** [comment]
+1 all of this, had to truncate the upsert documents.

**Comment by ipriyam26** [comment]
Happens because of this line
`
        for j, line in enumerate(lines_batch):
                metadata[j][text_key] = line
`
in langchain.vectorstores.Pinecone from_texts class method

From what I can see in the docs its in intentional behaviour, so that one can have there text along with embeddings, but I think it should be optional, as vector stores impose a limit and it not needed all the times to have the text that was embedded with you on retrieval. The retrievers use it for ease of access.

**Comment by Charlz91108112** [comment]
I managed it by first checking the size of the text chunk and then split the text further using the splitter to get the text chunks. Here is the rough implementation:

`EMBEDDING_CTX_LENGTH=8192`
`if cleaned_chum_size > 35*1024: # 35KB`
`    embeddings.chunk_size = int(int(EMBEDDING_CTX_LENGTH)/6)`
`    splitter_low = SemanticChunker(embeddings, 
                                       breakpoint_threshold_type="percentile")`
`chunks = splitter_low.split_text(cleaned_chum)`
