### ISSUE TITLE
ConversationalRetrievalChain gives different answers than Retrieval QA when searching docs

### ISSUE THREAD

**Issue by haritiruna** [langchain-ai/langchain#3809]
I'm trying to implement a basic chatbot that searches over PDFs documents. I've been following the examples in the Langchain docs and I've noticed that the answers I get back from different methods are inconsistent.

When I use `RetrievalQA` I get better answers than when I use `ConversationalRetrievalChain`.

I want a chat over a document that contains memory of the conversation so I have to use the latter. I've tried increasing the `search_kwargs` argument to include more context, but it makes no difference.

Any ideas as to why I'm getting inconsistent answers? And how can I make this chatbot more accurate?

## Here is my code: 

Initialising pinecone vector store:
```
pinecone.init(
    api_key="....",  
    environment="us-east1-gcp" 
)
index_name = "test-index"
namespace = "test-namespace"

vectorstore = Pinecone.from_texts(
    [t.page_content for t in texts], 
    embeddings, 
    index_name=index_name, 
    namespace=namespace
)
```

Using retrieval QA chain: 
```
chain = load_qa_chain(OpenAI(temperature=0), chain_type="stuff")

query = "Tell me about the role management for grades"
docs = docsearch.similarity_search(query)

chain.run(input_documents=docs, question=query)
```
Gives an acceptable answer: 
```
" The role management for grades involves..."
```
Using ConversationalRetrievalChain: 
```
llm = ChatOpenAI(temperature=0)
question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain = load_qa_chain(
    llm, 
    chain_type="stuff", 
    prompt=QA_PROMPT
)
retriever = docsearch.as_retriever()
chain = ConversationalRetrievalChain(
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    retriever=vectorstore.as_retriever()
)
```
Gives an answer that indicates no context:

```
I'm sorry, I cannot provide an answer to this question as there is no mention of a "role management" in the provided context. Can you please provide more information or context for me to assist you better?
```

**Comment by friahi65** [comment]
did you find an answer for this problem? I am facing similar issue, where ConversationalRetrievalChain add too many useless text to the answer.

**Comment by RajaSaluja** [comment]
what about using a SimpleSequentialChain. You can combine the RetrievalQA and ConversationalRetrievalChain to get the better output as an chat response. [https://python.langchain.com/docs/modules/chains/foundational/sequential_chains](url)

**Comment by maziyarpanahi** [comment]
@haritiruna you can add any memory to `RetrievalQA` and it works, is there a specific reason your prefer the memory feature in `ConversationalRetrievalChain`?

**Comment by maziyarpanahi** [comment]
Just answering my question, the difference between having chat_history in `RetrievalQA` is this in `ConversationalRetrievalChain`

>It first combines the chat history (either explicitly passed in or retrieved from the provided memory) and the question into a standalone question, then looks up relevant documents from the retriever, and finally passes those documents and the question to a question answering chain to return a response.

I guess if you need static chat_history without them turning into a new query to be retrieved you can go with `RetrievalQA`, if the chat history needs to be merged with the question into a new question to retrieve documents then `ConversationalRetrievalChain`. (I myself can't say which one makes more sense specially if the questions in one conversation are not related - the ConversationalRetrievalChain will be very wrong)
