### ISSUE TITLE
Tiktoken import bug?

### ISSUE THREAD

**Issue by sudowoodo200** [langchain-ai/langchain#3811]
https://github.com/hwchase17/langchain/blob/adcad98bee03ac8486f328b4f316017a6ccfc808/langchain/embeddings/openai.py#L159

Getting "no attribute" error for `tiktoken.model`. Believe that this is because tiktoken has changed their import model, per code [here](https://github.com/openai/tiktoken/blob/main/tiktoken/__init__.py). Change to `tiktoken.encoding_for_model(self.model)`?

**Comment by shawnesquivel** [comment]
Having this issue as well.

**Comment by shawnesquivel** [comment]
Changing to `tiktoken.encoding_for_model(self.model)` as you recommended gave me this error:

AttributeError: module 'tiktoken' has no attribute 'encoding_for_model'

tiktoken                 0.1.2

**Comment by shawnesquivel** [comment]
Here is the constructor `__init__.py ` for tiktoken

```
from .core import Encoding as Encoding
from .registry import get_encoding as get_encoding
from .registry import list_encoding_names as list_encoding_names
```

Thus we can see that if we use `list_encoding_names` we can get the list of good encoding names.
So in `langchain/embeddings/openai.py`
Old:
```
            # encoding = tiktoken.model.encoding_for_model(self.model)

```
New:
```
     print(tiktoken.list_encoding_names()) # prints ['gpt2', 'r50k_base', 'p50k_base', 'cl100k_base']
     encoding = tiktoken.get_encoding(self.model)
```


In your project directory, e.g., `main.py`, you must use one of the embeddings models from the `list_encoding_names` output. I changed it to GPT2 and it worked. 

As you can see in the [source code](https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py#L107), the model defaults to `model: str = "text-embedding-ada-002"`. But that doesn't seem to work.

```
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tiktoken/registry.py", line 60, in get_encoding
    raise ValueError(f"Unknown encoding {encoding_name}")
ValueError: Unknown encoding text-embedding-ada-002
```

So I changed it to GPT2 (one of the outputs of `list_encoding_names`), and it worked.


```
    embeddings = OpenAIEmbeddings(
        model="gpt2", openai_api_key=os.environ.get("OPENAI_API_KEY")
    )
```

**Comment by shawnesquivel** [comment]
In summary, my proposed changes that made it work for me are:

https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py#L188
Change:
`encoding = tiktoken.model.encoding_for_model(self.model)`

https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py#L107
Change:
`model: str = "GPT2"`

**Comment by dmytrokarpovych** [comment]
@shawnesquivel did you create PR with this fix?

**Comment by shawnesquivel** [comment]
@dmytrokarpovych 

There is an open PR  that is somewhat related #3819 

I don't think it incorporates the default model that I used though.

**Comment by rahdor** [comment]
I had this issue and was able to resolve it by installing faiss-cpu

pip install faiss-cpu

**Comment by heavenkiller2018** [comment]
I have the same problem, and @rahdor ,your suggestion can't effect🤡

**Comment by Avigin** [comment]
I also received the this message with more details: "most likely due to a circular import"

After tracking the packages I found that the my local py file is the same as the file name being used: "token.py"
After I changed the local name it worked without problems

**Comment by pepijnolivier** [comment]
I named my python script `tiktoken.py` which is what gave the error.
I renamed it and it works now
