### ISSUE TITLE
Invalid tool using Llama.cpp

### ISSUE THREAD

**Issue by Hugo-Matias** [langchain-ai/langchain#3815]
While the agent seems to find the correct function, I keep getting `Observation: "... is not a valid tool, try another one."` and it struggles to iterate over the other similar solutions from there. Here is an output using the [docs example](https://python.langchain.com/en/latest/modules/agents/tools/multi_input_tool.html).

![](https://i.imgur.com/I68i1bf.png)

Environment: Windows 11 WSL
LLM: Llama.cpp
Model: TheBloke/wizardLM-7B-GGML

I don't have a ChatGPT key so I can't say for sure if this is strictly related to Llama.cpp, the model I'm using or something else in my installation. I also haven't tried other models but since this an instruction based model and the agent actually acknowledges the action it must perform I'm don't think that's the root of the problem.

I'm still learning the library but I can provide additional information if you need.

Edit: Not sure how much the built-in tools differ from the Multi-Input tool in terms of agent implementation but I seem to be experiencing the same behavior with the "wikipedia" tool as well.

![](https://i.imgur.com/HPXsrhx.png)

**Comment by jonmach** [comment]
Please reopen this - I am having the same issue using a llama.cpp based server.
