### ISSUE TITLE
getting error while running poetry install -E all

### ISSUE THREAD

**Issue by harshachopra507** [langchain-ai/langchain#3821]
I am new to contributing to open-source. I have installed poetry 1.4.0 version and setup new conda environment.
While running ```poetry install -E all```, I am getting error as such:

```
Command ['python', '-I', '-W', 'ignore', '-'] errored with the following return code 2

Error output:
Unknown option: -I
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.


Input:
import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)
````

How to resolve this issue? @hwchase17

**Comment by Cameronwood611** [comment]
This isn't related to the project at all; you probably won't get an answer. Additionally, you don't need to use both poetry and anaconda, they serve the same purpose.
