### ISSUE TITLE
[Feature] supported java sdk

### ISSUE THREAD

**Issue by laglangyue** [langchain-ai/langchain#3829]
Most web applications are developed using Java, and may we need Java SDK

**Comment by ljubarskij** [comment]
I am currently working on a Java version of langchain. It is currently only MVP: only PDF loader, splitting, pinecone store/retrieval, openai embeddings, openai chat api, prompt templates, conversation history, etc... Will make repo public tomorrow and continue working on it in the coming days.

**Comment by deep-learning-dynamo** [comment]
@laglangyue @quxiucheng https://github.com/ai-for-java/ai4j
Please feel free to use and/or contribute and suggest improvements and request features

**Comment by HamaWhiteGG** [comment]
In Java, you can use LangChain: https://github.com/HamaWhiteGG/langchain-java
@laglangyue
