### ISSUE TITLE
Use of matplotlib or seaborn with csv agent or Pandas Dataframe Agent?

### ISSUE THREAD

**Issue by marcello-calabrese** [langchain-ai/langchain#3844]
Hi, i am wondering if using the csv agent or the pandas dataframe agent I can also query and visualize charts with a chart library (seaborn, matplotlib or others..) when analysing a csv file/dataframe? thanks, Marcello

**Comment by charanhu** [comment]
hey you got any solution?

**Comment by marcello-calabrese** [comment]
@charanhu hi, not with langchain csv agent but there is another library called pandasai that lets you also have charts if you ask question to the chat bot :-) https://youtu.be/cGA9Yabg0Yc

**Comment by sxaxmz** [comment]
I believe LangChain agent is capable of doing so, as far as I know it's lacking the ability to store or save the generated charts. On the other hand, Pandas AI is capable of saving the graphs by adding the parameter 'save_chart' to the agent it shall be saved in the library base directory as per their documentation. 

Try asking langchain pandas agent to plot or generate a graph when using jupyter notebook or google collab and you shall be able to see the generated graph in the output of the code snippet.

**Comment by sxaxmz** [comment]
Hi, 

As an update, I believe we are able to do similar tasks with LangChain. I have put together this repo that gives a UI to LangChan PandasAgent. The user is able to visualize data in tabular format, access the chain of thoughts, access created charts/plots, and more. 

You can access it here -->  [PandasGPTAgent](https://github.com/sxaxmz/PandasGPTAgent)

**Comment by sxaxmz** [comment]
Hi @marcello-calabrese, that sounds fantastic! Feel free to explore and reach-out for any inquiries. I appreciate your intention to feature it in the article, kindly keep me updated. Cheers!

**Comment by Sreekiranar** [comment]
> PandasGPTAgent
Thanks a lot for this repo! Saved me a lot of time and effort! Appreciate your contribution! :D
