### ISSUE TITLE
arxiv is not recognized in tools

### ISSUE THREAD

**Issue by Troyanovsky** [langchain-ai/langchain#3865]
From the [official doc](https://python.langchain.com/en/latest/modules/agents/tools/examples/arxiv.html), to run an agent with arxiv, you can arxiv as a tool

`from langchain.chat_models import ChatOpenAI
from langchain.agents import load_tools, initialize_agent, AgentType

llm = ChatOpenAI(temperature=0.0)
tools = load_tools(
    ["arxiv"], 
)

agent_chain = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
)`

But it's not recognized
`[/usr/local/lib/python3.10/dist-packages/langchain/agents/load_tools.py](https://localhost:8080/#) in load_tools(tool_names, llm, callback_manager, **kwargs)
    329             tools.append(tool)
    330         else:
--> 331             raise ValueError(f"Got unknown tool {name}")
    332     return tools
    333 

ValueError: Got unknown tool arxiv`

**Comment by FrancescoSaverioZuppichini** [comment]
same here, can't we just import the tool from the package instead of relying on untyped string in `load_tools`?

**Comment by qadro87** [comment]
+1

**Comment by Yan2013** [comment]
+1, langchain version 0.0.187
