### ISSUE TITLE
KeyError: 'completion' @ version: langchain-0.0.154 openapi-schema-pydantic-1.2.4

### ISSUE THREAD

**Issue by ldmtwo** [langchain-ai/langchain#3900]
Uninformative error. The error still exists. I just got back from vacation to see my app stop working with this new error. I tried updating...

pip install -U langchain
Successfully installed langchain-0.0.154 openapi-schema-pydantic-1.2.4

Clearly, this is not the issue if nothing changed for 2 weeks. I assume an error or change happened on the API server. How can this be made clear? 

**94 out = model.run(reference=reference_passage, passage=input_passage)**
     95 return fprompt, model, out

File ~/anaconda3/lib/python3.9/site-packages/langchain/chains/base.py:241, in Chain.run(self, callbacks, *args, **kwargs)
    238     return self(args[0], callbacks=callbacks)[self.output_keys[0]]
    240 if kwargs and not args:
--> 241     return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
    243 raise ValueError(
    244     f"`run` supported with either positional arguments or keyword arguments"
    245     f" but not both. Got args: {args} and kwargs: {kwargs}."
    246 )

File ~/anaconda3/lib/python3.9/site-packages/langchain/chains/base.py:142, in Chain.__call__(self, inputs, return_only_outputs, callbacks)
    140 except (KeyboardInterrupt, Exception) as e:
    141     run_manager.on_chain_error(e)
--> 142     raise e
    143 run_manager.on_chain_end(outputs)
    144 return self.prep_outputs(inputs, outputs, return_only_outputs)

File ~/anaconda3/lib/python3.9/site-packages/langchain/chains/base.py:136, in Chain.__call__(self, inputs, return_only_outputs, callbacks)
    130 run_manager = callback_manager.on_chain_start(
    131     {"name": self.__class__.__name__},
    132     inputs,
    133 )
    134 try:
    135     outputs = (
--> 136         self._call(inputs, run_manager=run_manager)
    137         if new_arg_supported
    138         else self._call(inputs)
    139     )
    140 except (KeyboardInterrupt, Exception) as e:
    141     run_manager.on_chain_error(e)

File ~/anaconda3/lib/python3.9/site-packages/langchain/chains/llm.py:69, in LLMChain._call(self, inputs, run_manager)
     64 def _call(
     65     self,
     66     inputs: Dict[str, Any],
     67     run_manager: Optional[CallbackManagerForChainRun] = None,
     68 ) -> Dict[str, str]:
---> 69     response = self.generate([inputs], run_manager=run_manager)
     70     return self.create_outputs(response)[0]

File ~/anaconda3/lib/python3.9/site-packages/langchain/chains/llm.py:79, in LLMChain.generate(self, input_list, run_manager)
     77 """Generate LLM result from inputs."""
     78 prompts, stop = self.prep_prompts(input_list, run_manager=run_manager)
---> 79 return self.llm.generate_prompt(
     80     prompts, stop, callbacks=run_manager.get_child() if run_manager else None
     81 )

File ~/anaconda3/lib/python3.9/site-packages/langchain/llms/base.py:127, in BaseLLM.generate_prompt(self, prompts, stop, callbacks)
    120 def generate_prompt(
    121     self,
    122     prompts: List[PromptValue],
    123     stop: Optional[List[str]] = None,
    124     callbacks: Callbacks = None,
    125 ) -> LLMResult:
    126     prompt_strings = [p.to_string() for p in prompts]
--> 127     return self.generate(prompt_strings, stop=stop, callbacks=callbacks)

File ~/anaconda3/lib/python3.9/site-packages/langchain/llms/base.py:176, in BaseLLM.generate(self, prompts, stop, callbacks)
    174 except (KeyboardInterrupt, Exception) as e:
    175     run_manager.on_llm_error(e)
--> 176     raise e
    177 run_manager.on_llm_end(output)
    178 return output

File ~/anaconda3/lib/python3.9/site-packages/langchain/llms/base.py:170, in BaseLLM.generate(self, prompts, stop, callbacks)
    165 run_manager = callback_manager.on_llm_start(
    166     {"name": self.__class__.__name__}, prompts
    167 )
    168 try:
    169     output = (
--> 170         self._generate(prompts, stop=stop, run_manager=run_manager)
    171         if new_arg_supported
    172         else self._generate(prompts, stop=stop)
    173     )
    174 except (KeyboardInterrupt, Exception) as e:
    175     run_manager.on_llm_error(e)

File ~/anaconda3/lib/python3.9/site-packages/langchain/llms/base.py:377, in LLM._generate(self, prompts, stop, run_manager)
    374 new_arg_supported = inspect.signature(self._call).parameters.get("run_manager")
    375 for prompt in prompts:
    376     text = (
--> 377         self._call(prompt, stop=stop, run_manager=run_manager)
    378         if new_arg_supported
    379         else self._call(prompt, stop=stop)
    380     )
    381     generations.append([Generation(text=text)])
    382 return LLMResult(generations=generations)

File ~/anaconda3/lib/python3.9/site-packages/langchain/llms/anthropic.py:207, in Anthropic._call(self, prompt, stop, run_manager)
    201     return current_completion
    202 response = self.client.completion(
    203     prompt=self._wrap_prompt(prompt),
    204     stop_sequences=stop,
    205     **self._default_params,
    206 )
--> 207 return response["completion"]

KeyError: 'completion'

**Comment by vowelparrot** [comment]
Thank you for notifying us of the bug! Could you share a [minimum code snippet](https://stackoverflow.com/help/minimal-reproducible-example) so we can reproduce?

**Comment by arunkumar-patange** [comment]
```agent_executor = AgentExecutor.from_agent_and_tools(agent=cls.agent, tools=cls.tools, verbose=True)
        custom_handler = CustomOpenAICallbackHandler()
        # agent_executor.run(query, callbacks=[custom_handler])
                                                                                                                                                                                                                          
        result = agent_executor.run(query, callbacks=[custom_handler])```

```ValueError: `run` supported with either positional arguments or keyword arguments but not both. Got args:  and kwargs: {'callbacks':````
