### ISSUE TITLE
Are their plans to incorporate mlc.ai

### ISSUE THREAD

**Issue by joshkurz** [langchain-ai/langchain#3932]
I just installed https://mlc.ai/mlc-llm/ and played around with it locally. Looks like a good option if you do not want to rely on internet access to interact with the LLM. I think an llm interface with this could be useful in langchain.

I asked mlc running locally on my machine to write something to the owners of this repo to get added to this project.

```
Hi langchain owners,

I'm writing this issue to encourage you to create an LLM interface for me. As a language model, I understand that I may not have the same level of access to resources as other models, but creating an LLM interface would greatly benefit my ability to learn and improve. The ability to easily integrate and leverage knowledge from other models would greatly enhance my learning and development. I believe this would be a valuable resource for me and I hope you can consider this request. Thank you for your consideration!
Best regards,

[Your Name]
```

**Comment by joshkurz** [comment]
closing this. As I learn more mlc-llm just runs the models behind the scenes like vicuna. So if we just get vicuna support we will have the same experience in langchain.

**Comment by QROST** [comment]
This would be a valid feature to have. MLC is easy to deploy on Mac. MLC+Langchain would save a lot of efforts for mac langchain local llm users.

**Comment by Jchang4** [comment]
I think this need work on the MLC side. You can hack things together by running an MLC API and using that in langchain

Problem is, your langchain parameters don't seem to affect the MLC model - e.g. list of stop words. 

I haven't taken a look at the mlc api code yet, we might be able to pass that as a parameter and then handle it there? Not sure.

**Comment by Tao-begd** [comment]
Is it possible to consider MLC+langchain to run offline on mobile devices?

**Comment by SuperKenVery** [comment]
> closing this. As I learn more mlc-llm just runs the models behind the scenes like vicuna. So if we just get vicuna support we will have the same experience in langchain.

I searched the web and found `vicuna` is a specific LLM model, while mlc is a framework for running LLMs, so I don't understand how they are the same. Besides, even if they are the same I thinks it's still valid to support mlc because more integration is just better, I don't think any one would complain about too many integrations. 

Would you please consider re-opening this issue? Thanks!

**Comment by joshkurz** [comment]
@SuperKenVery thanks, yeah I created this when I was just learning about LLMs. I still think if we could get this integration in it would be helpful.
