### ISSUE TITLE
Make Pandas Agent return DataFrame object?

### ISSUE THREAD

**Issue by ArchieLuxton** [langchain-ai/langchain#3968]
Currently I'm using a specific prompt suffix (`". Assign the printed dataframe to a variable and return it as the final answer."`) in the Pandas agent, which sometimes gives the result I'm looking for as a printed DataFrame. I've then written an output parser that turns this into a JSON which can then be loaded as a DataFrame. 

The problem with this is the Pandas agent often doesn't output the DataFrame, instead printing the variable name or the last command used to get to that result, and also critically the output parser uses many tokens for the kinds of data I'm working with. 

Is it possible to force the Pandas agent to return the output of its analysis as a Pandas DataFrame object?

**Comment by jiyer2016** [comment]
@ArchieLuxton - Quick Question - How did you customize the prompt for the pandas agent ? Might sharing any code snippets ? Trying to figure this out for a while now.

**Comment by PawelFaron** [comment]
Please provide a working code snipped for reproduction.

**Comment by PJBentham** [comment]
@jiyer2016 You can amend the prompt by adding / amending a prefix. 
The default is here: https://github.com/hwchase17/langchain/blob/master/langchain/agents/agent_toolkits/pandas/prompt.py

**Comment by ivanmasf** [comment]
I'm also interested in this. It's opaque to the point I'm considering coding a whole new agent just to have access to the objects that the agents are manipulating.

**Comment by mobrien-caprx** [comment]
> @jiyer2016 You can amend the prompt by adding / amending a prefix. The default is here: https://github.com/hwchase17/langchain/blob/master/langchain/agents/agent_toolkits/pandas/prompt.py

linkrot :(
