### ISSUE TITLE
Get intermediate_steps with SQLDatabase Agent

### ISSUE THREAD

**Issue by pnd-rdestratis** [langchain-ai/langchain#3969]
When using the SQL Chain I can return the intermediate steps so that I can output the Query. For the SQL Agent this seems not to be an option without modifying the tool itself. How can I see the actual queries used (not only in the verbose, but save it in a variable e.g.)?

Alternatively is there a way to save the verbose output in a dict?

**Comment by cachatj** [comment]
Also curious about this?

**Comment by DishenWang2023** [comment]
Instead of using `create_sql_agent`, you can initialize the sql agent with `initialize_agent` and use the argument `return_intermediate_steps=true` to get the intermediate steps.

**Comment by cachatj** [comment]
So, I'm attempting to do this so I can dry_run BQ queries before doing full send. 

I was able to get just the SQL query used by: 

```py
sqlchain = SQLDatabaseSequentialChain.from_llm(llm, db, verbose=True, return_intermediate_steps=True, callbacks=None, tags=None)

results = sqlchain("How many distinct tag values do we have for deviceid actors?")

print(results["intermediate_steps"][1])
```
--
You can display it with or without the print() in a jNB. 

essentially "results["intermediate_steps"][1]" is your SQL statement.

**Comment by pnd-rdestratis** [comment]
Hmm I don't want to use a chain but the agent. I would like to display the thoughts, observations, queries and results separately in a web app. Initializing the agent did not work.

**Comment by vinayemmadi** [comment]
I working on a similar use case @pnd-rdestratis. Unable to get sql as a result

**Comment by AlejandroGil** [comment]
@pnd-rdestratis Did you get any progress on this? I'm facing the same issue

**Comment by nikitacorp** [comment]
@pnd-rdestratis @AlejandroGil @vinayemmadi I also would like to know, have you found any solution to your problem?

**Comment by ankitvays6657** [comment]
same issue, did anyone find a workaround?

**Comment by andrewhinh** [comment]
Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`. 

This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.

Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.

**Comment by GB-x2** [comment]
One quick fix can be prompt the LLM to attach SQL query to the response and apply some post processing

**Comment by jaxphuchanlmht1999** [comment]
> Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`.
> 
> This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.
> 
> Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.

I ran successfully, thank you so much.

**Comment by atulpareek31** [comment]
> Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`.
> 
> This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.
> 
> Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.

hi
How can I stop execution of agent.__call__() right after query is generated?
thanks

**Comment by madhubandru** [comment]
> Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`.
> 
> This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.
> 
> Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.

This helped, Thank you :)

**Comment by mfernandezsidn** [comment]
> Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`.
> 
> This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.
> 
> Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.

I don't understand what I should do.


I have my agent:

`agent_executor = create_sql_agent(
    llm=vertex_llm,
    db=db,
    verbose=True,
    top_k=1000,
    handle_parsing_errors=True,
)`

Then, I am executing __call__ instead of the invoke function as I was doing.

`test = agent_executor.__call__(prompt_4)`


How do I recover the SQL query now?

**Comment by prashant268** [comment]
> > Using `create_sql_agent()`, specify `agent_executor_kwargs` like so: `agent_executor_kwargs={"return_intermediate_steps": True}`.
> > This works because in [this file](https://api.python.langchain.com/en/latest/_modules/langchain/agents/agent_toolkits/sql/base.html#create_sql_agent), it's apparent that `AgentExecutor.from_agent_and_tools()` doesn't use `kwargs`, but rather `agent_executor_kwargs`.
> > Then, make sure you don't use `.run()` when calling the agent, as it currently doesn't support intermediate steps. Use something else like `__call__()`.
> 
> I don't understand what I should do.
> 
> I have my agent:
> 
> `agent_executor = create_sql_agent( llm=vertex_llm, db=db, verbose=True, top_k=1000, handle_parsing_errors=True, )`
> 
> Then, I am executing **call** instead of the invoke function as I was doing.
> 
> `test = agent_executor.__call__(prompt_4)`
> 
> How do I recover the SQL query now?
agent_executor = create_sql_agent( llm=vertex_llm, 
agent_executor_kwargs={"return_intermediate_steps": True}.
db=db, verbose=True, top_k=1000, handle_parsing_errors=True, ), it will give all steps and generated query you need to do post processing
