### ISSUE TITLE
Chatbot memory integration

### ISSUE THREAD

**Issue by zigax1** [langchain-ai/langchain#3977]
Hello everyone!

I am using Langchain and I want to implement chatbot memory. I am doing everything according to the docs and my bot doesn't remember anything I tell him.

**Code snippet:**
```
llm = ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.3, openai_api_key=OPENAI_API_KEY)

memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
rqa = ConversationalRetrievalChain.from_llm(llm, docsearch.as_retriever(), memory=memory)

def retrieve_answer(query, chat_history):
    memory.chat_memory.add_user_message(query)
    res = rqa({"question": query})
    retrieval_result = res["answer"]

    if "The given context does not provide" in retrieval_result:
        base_result = llm.generate([query])
        return base_result.generations[0][0].text
    else:
        return retrieval_result

messages = []

print("Welcome to the chatbot. Enter 'quit' to exit the program.")
while True:
    user_message = input("You: ")
    answer = retrieve_answer(user_message, messages)
    print("Assistant:", answer)

    messages.append((user_message, answer))
```

**Whole python script is located here:** https://github.com/zigax1/chat-with-pdf.git

Does anyone have any idea, what am I doing wrong?

Thanks to everyone for help.

![image](https://user-images.githubusercontent.com/80093733/235705133-b8ff5d11-88bd-408a-a03e-c596ffb2fde7.png)

**Comment by rchatham** [comment]
Also seeing the same. The ConversationalMemoryBuffer is not giving the bot access to previous messages.

**Comment by bconrad98** [comment]
Yes I think memory is broken specifically for the ChatOpenAI model. The OpenAI LLM seems to do fine
