### ISSUE TITLE
Is updating collection possible

### ISSUE THREAD

**Issue by ragvendra3898** [langchain-ai/langchain#3984]
Hi,
I am using below function create_collection() for creating collection and it is working fine , like it is creating a collection and storing it into my persist directory and also I am able to perform question answering using this collection.
def create_collection(openai_api_key, embedding_path, persist_directory, collection_name):
    if not openai_api_key == 'None':
        if collection_name!=None:
            if persist_directory!=None:
                global vectordb
                if embedding_path!=None:
                    
                    for i in embedding_path:
                        i = str(i)
                        logging.info('Processing files in directory: ' +i)
                        loader = DirectoryLoader(i, show_progress=True)  
                        docs = loader.load()                                                         #DE5-T31

                        #text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)   #DE5-T31
                        #texts = text_splitter.split_documents(docs)                                        #DE5-T31
                        text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
                        texts = text_splitter.split_documents(docs)
                        embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)                                                    #DE5-T31
                        vectordb = Chroma.from_documents(texts, embedding=embeddings, persist_directory = persist_directory, collection_name=collection_name)
                        vectordb.persist()    
                        vectordb = None                           #DE5-T31
                    
                elif web_urls_path!=None:
                    web_urls = web_urls_path.split(',')
                    url_list = web_urls
                    logging.info(f"URL List: {url_list}")
                    urls = []
                    for url in url_list:
                        logging.info(f"Processing data in url: {url}")
                        reqs = requests.get(url)
                        soup = BeautifulSoup(reqs.text, 'html.parser')
                        for link in soup.find_all('a'):
                            urllink=link.get('href')
                            if (urllink != None) and (urllink.startswith('http')):
                                urls.append(urllink)
                                #print(link.get('href'))

                        loader = UnstructuredURLLoader(urls=urls)
                        docs = loader.load()
                        logging.info(f'You have {len(docs)} document(s) in your data')
                        text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
                        texts = text_splitter.split_documents(docs)
                        embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
                        vectordb = Chroma.from_documents(texts, embedding=embeddings, persist_directory=persist_directory, collection_name=collection_name)
                        vectordb.persist()
                        vectordb = None
                        
                else:
                    logging.error("Please provide the directory or web path to create the collection!")
                    sys.exit(0)   
            else:
                logging.error("Please provide the path to store the vector database!") 
                sys.exit(0)   
        else:
            logging.error("Please provide a collection name!") 
            sys.exit(0)    
    else:
        logging.error("Please configure the openai_api_key in the json file at the following path:\n" + "file:///" + pathconf)
        sys.exit(0)    
    return

but while I am trying to update the existing collection using update collection function, it is not working for me, like I am not able to update the existing collection. 

def update_collection(openai_api_key, persist_directory, collection_name):
    if not openai_api_key == 'None':
        if persist_directory!=None:
            if collection_name!=None:
                if os.path.isdir(persist_directory + '\index') and os.path.isfile(persist_directory + "\chroma-collections.parquet") and os.path.isfile(persist_directory + "\chroma-embeddings.parquet"):
                    try:
                        embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key) 
                        client = chromadb.Client(Settings(chroma_db_impl="duckdb+parquet", persist_directory=persist_directory)) # Optional, defaults to .chromadb/ in the current directory
                        collection = client.get_collection(name = collection_name, embedding_function=embeddings)
                    except Exception as e:
                        logging.error("An error occured: " + str(e))
                        sys.exit(0)
                    global vectordb    
                    if embedding_path!=None:
                        #calling persisted db
                        vectordb = Chroma(embedding_function = embeddings, persist_directory = persist_directory, collection_name=collection_name)
                        for i in embedding_path:
                            i = str(i)
                            logging.info('Processing files in directory: ' +i)
                            # load the documents you want to add to the collection
                            loader = DirectoryLoader(i, show_progress=True)
                            docs = loader.load()
                            text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
                            texts = text_splitter.split_documents(docs)

                            # add the documents to the collection
                            #vectordb = Chroma(embedding_function=embeddings, persist_directory=persist_directory, collection_name=collection_name)
                            vectordb.add_documents(documents=texts)
                            #vectordb = Chroma.from_documents(texts, collection_name=collection_name, persist_directory=persist_directory, embedding=embeddings)
                            vectordb.persist()
                            vectordb =None      
                            #collection.update(documents=texts)                                                 
                            #text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=0)   #DE5-T31
                            #texts = text_splitter.split_documents(docs)                                        #DE5-T31
                            
                            #vectordb = vectordb.add_documents(texts, collection_name=collection_name)                                              
                            #vectordb.from_documents(documents=texts,embedding=embeddings, collection_name=collection_name)
                            
                        
                    elif web_urls_path!=None:
                        #vectordb = Chroma(embedding_function=embeddings, persist_directory = persist_directory, collection_name=collection_name)
                        web_urls = web_urls_path.split(',')
                        url_list = web_urls
                        logging.info(f"URL List: {url_list}")
                        urls = []
                        for url in url_list:
                            logging.info(f"Processing data in url: {url}")
                            reqs = requests.get(url)
                            soup = BeautifulSoup(reqs.text, 'html.parser')
                            for link in soup.find_all('a'):
                                urllink=link.get('href')
                                if (urllink != None) and (urllink.startswith('http')):
                                    urls.append(urllink)
                                    #print(link.get('href'))

                            loader = UnstructuredURLLoader(urls=urls)
                            docs = loader.load()
                            logging.info(f'You have {len(docs)} document(s) in your data')
                            text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
                            texts = text_splitter.split_documents(docs)
                            embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
                            vectordb.from_documents(texts, embedding=embeddings, persist_directory=persist_directory, collection_name=collection_name)
                            vectordb.persist()
                            vectordb = None    
                        
                    else:
                        logging.error("Please provide directory path(s) or web url(s) to update existing collection!")
                        sys.exit(0)
                else:
                    logging.error("The path provided does not contain a chroma vectordb!")  
                    sys.exit(0)              
            else:
                logging.error("Please provide a valid collection name to update the existing collection!")
                sys.exit(0)   
        else:
            logging.error("Please provide the path where vector database is stored!") 
            sys.exit(0)     
    else:
        logging.error("Please configure the openai_api_key in the json file at the following path:\n" + "file:///" + pathconf) 
        sys.exit(0)   
    
    return

can anyone please help me that what mistake I am doing or it is not possible to update existing collection in persisted database?
Thank You

**Comment by scottstables** [comment]
Would also love to see the ability to 'add' documents to an existing Chroma DB (e.g. to support multiple embedding over days) without deleting the current db (which seems to be the default behaviour. Is it possible to pass a Chroma client confif through Chroma.from_documents ?
