### ISSUE TITLE
Pydantic output parser assumes JSON object

### ISSUE THREAD

**Issue by jmif** [langchain-ai/langchain#3985]
With a schema such as:

```
class JsonList(BaseModel):
    __root__: List[str]
```

We can validate a JSON string in the form:

```
[ 'xxx', 'yyy', 'zzz' ]
```

But the Pydantic parser [assumes the input is an object](https://github.com/hwchase17/langchain/blob/71a337dac6aa8c5a7f472e3e7fd0a61ca2a4eefb/langchain/output_parsers/pydantic.py#L20) in its greedy search, so it fails with a validation error.

**Comment by edwardzjl** [comment]
I've encountered a similar situation, and I customized the regex pattern of `PydanticOutputParser` to be:

```python
r"[\[\{].*[\]\}]"
```

It is not a graceful regex, but it works in my case.
