### ISSUE TITLE
Feature Request: Reinforcement Learning with Human Feedback

### ISSUE THREAD

**Issue by zlapp** [langchain-ai/langchain#399]
Feature request:
Support Reinforcement Learning with Human Feedback

Example 

https://github.com/lucidrains/PaLM-rlhf-pytorch

**Comment by fblissjr** [comment]
updated repo here: https://github.com/yangkevin2/doc-story-generation

**Comment by JohnNay** [comment]
how would this be incorporated into LangChain? it seems orthogonal.

**Comment by zlapp** [comment]
Was thinking as an agent which learns

**Comment by creatorrr** [comment]
AFAIK, not really possible to do at the generation level but might be a good idea to tune a classifier on top of vector data stores. Openai cookbook includes some examples but it could also be done atop other llm providers:

[Classification using the embeddings](https://github.com/openai/openai-cookbook/blob/main/examples/Classification_using_embeddings.ipynb)

@zlapp  - this won't be something like RLHF used for ChatGPT but it could still improve and learn preferences for documents searched.

Thoughts, @hwchase17 ?
