### ISSUE TITLE
OpenAIEmbeddings can not take headers

### ISSUE THREAD

**Issue by aakashrshah** [langchain-ai/langchain#3992]
Module: `embeddings/openai.py`

Preface: While using the AzureOpenAI or a custom model deployment on Azure, I am unable to use the OpenAIEmbeddings as `pydantic` forbids passing extra arguments. Whereas this works perfectly fine with ChatOpenAI or OpenAI models.

Environment Variables I am using - 

```
OPENAI_LOG=info
OPENAI_API_KEY=somestring
OPENAI_API_TYPE=azure
OPENAI_API_VERSION=2023-03-15-preview
OPENAI_API_BASE=some-url
```

My code to reproduce the error - 

```{python}
DEPLOYMENT_FROM_MODEL = {
    'text-embedding-ada-002': 'custom_embeddings'
}
model='text-embedding-ada-002'
llm = OpenAIEmbeddings(
    deployment=DEPLOYMENT_FROM_MODEL.get(model),
    model=model,
    headers={
        "azure-account-uri": f"https://{AZURE_ACCOUNT}.openai.azure.com",
        "Authorization": f"Bearer {BEARER_TOKEN}",
    }
)

llm.embed_query(input_prompt)
```

Errors thrown:

```
pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAIEmbeddings
deployment
  none is not an allowed value (type=type_error.none.not_allowed)
headers
  extra fields not permitted (type=value_error.extra)
```

I tried changing the `embeddings/openai.py` and got them working by passing it as kwargs. Hopefully I can create a MR for it.

**Comment by TomHavy** [comment]
> Module: `embeddings/openai.py`
> 
> Preface: While using the AzureOpenAI or a custom model deployment on Azure, I am unable to use the OpenAIEmbeddings as `pydantic` forbids passing extra arguments. Whereas this works perfectly fine with ChatOpenAI or OpenAI models.
> 
> Environment Variables I am using -
> 
> ```
> OPENAI_LOG=info
> OPENAI_API_KEY=somestring
> OPENAI_API_TYPE=azure
> OPENAI_API_VERSION=2023-03-15-preview
> OPENAI_API_BASE=some-url
> ```
> 
> My code to reproduce the error -
> 
> ```
> DEPLOYMENT_FROM_MODEL = {
>     'text-embedding-ada-002': 'custom_embeddings'
> }
> model='text-embedding-ada-002'
> llm = OpenAIEmbeddings(
>     deployment=DEPLOYMENT_FROM_MODEL.get(model),
>     model=model,
>     headers={
>         "azure-account-uri": f"https://{AZURE_ACCOUNT}.openai.azure.com",
>         "Authorization": f"Bearer {BEARER_TOKEN}",
>     }
> )
> 
> llm.embed_query(input_prompt)
> ```
> 
> Errors thrown:
> 
> ```
> pydantic.error_wrappers.ValidationError: 2 validation errors for OpenAIEmbeddings
> deployment
>   none is not an allowed value (type=type_error.none.not_allowed)
> headers
>   extra fields not permitted (type=value_error.extra)
> ```
> 
> I tried changing the `embeddings/openai.py` and got them working by passing it as kwargs. Hopefully I can create a MR for it.

Can you show how you did it? I still have the same error.
