### ISSUE TITLE
[Feature] Augment SelfQueryRetriever to support Vespa

### ISSUE THREAD

**Issue by filippo82** [langchain-ai/langchain#4008]
As of `0.0.155`, the `SelfQueryRetriever ` class supports Pinecone only.

I wanted to extend it myself to support Vespa too but, after reviewing the current implementation, I discovered that `SelfQueryRetriever` ["wraps around a vector store" instead of a retriever](https://github.com/hwchase17/langchain/blob/18f9d7b4f6209632a02ed6e53a663e98d372f3da/langchain/retrievers/self_query/base.py#L33).

Currently, there is no `VectorStore` implementation for Vespa. Hence, I believe it is not possible to augment `SelfQueryRetriever` to support Vespa.

After thinking about it for a couple of days, I think that a valid solution to this problem would require to rethink the implementation of the `SelfQueryRetriever` by making it wrap a retriever instead of a vector store. This sounds reasonable because each vector sore can act as a retriever thanks to the `as_retriever` method.

The `search` method added as part of the #3607 is a wrapper around either the `similarity_search` or `max_marginal_relevance_search` method which are also wrapped by the `get_relevant_documents` method of a retriever. Hence, refactoring `SelfQueryRetriever` to wrap a retriever instead of a vector store seems reasonable to me.

Obviously, mine is a fairly narrow point of view given that I mainly looked at the code related to the implementation of the `SelfQueryRetriever` class and I might miss key implications of such a proposed change.

I would be happy to have a go a the `SelfQueryRetriever` refactoring but first it would be great of someone from the code developers team could comment on this.

Tagging here @dev2049 because you were the author of #3607

**Comment by dev2049** [comment]
How were you imagining to use the self-querying retriever with another retriever? Would it be rephrasing the original query string?

I ask because the main method exposed by the Retriever abstraction is
```python
def get_relevant_documents(self, query: str) -> List[Document]
```
This only takes a single string query as input. the motivation for the SelfQueryRetriever is to be able to create complex, structured queries against a data store. Since Retrievers don't expose such a method, it's not particularly interesting to wrap the self-querying functionality around a Retriever. VectorStores on the other hand support arbitrary kwargs. 
```python
def search(self, query: str, search_type: str, **kwargs: Any) -> List[Document]:
```
Many vector stores for example support metadata filtering, and the self-querying retriever can auto-generate those filtering conditions.

My intuition is if we just want a retriever that takes a query, passes it to an LLM to rephrase it, and then applies the rephrased query to a base retriever it's wrapped around, it's probably cleaner/easier to just introduce a new Retriever class. What do you think?

cc @hwchase17

**Comment by filippo82** [comment]
To answer your first question: yes, that is what I thought. My idea would be to rephrase the original query string which is then passed to a downstream retriever.

You raise all valid points of course.

Here some thoughts (in no specific order):

* modifying `def get_relevant_documents(self, query: str)` to accept an additional `**kwargs` argument would most likely solve this issue.
* (this is a very opinionated point) referring to vector stores, I think that the various search (retrieval) capabilities should be exposed through their "retriever interface" only. This would work as some kind of "separation of concerns" mechanism. Everything which has to do with creation/maintenance/storing of indices happens within the `VectorStore` subclass of the specific vector store. However, retrieving documents should happen using methods exposed by the `as_retriever` interface of the vector store. All of this is to support my idea that the `SelfQueryRetriever` class should only be aware of the retriever capabilities of an object.
* Ideally, one would create a `SelfQueryRetriever` object from an LLM and retriever `SelfQueryRetriever.from_llm(llm, retriever, ...)` and not from a vector store `SelfQueryRetriever.from_llm(llm, vectorstore, ...)`. Then the `get_relevant_documents` of `SelfQueryRetriever` would just call the `get_relevant_documents` of the specific retriever with `kwargs` (filters) (this would require the modification described in the first bullet point obviously).
* If the general idea for a retriever in LangChain is to have an interface to simply perform text based queries, then yes one might think about introduce an `RetrieverWithFilters` class (or something like that). This class could expose a `get_relevant_documents_with_filters` method for example. However I still think that adding a `**kwargs` to `get_relevant_documents` might be a leaner solution (maybe even without breaking anything 🤞🏻) which does not require creating a new class.

P.S. These are comments from my 2 AM tired brain. Hopefully they still make some kind of sense. Happy to rephrase if needed.

**Comment by hwchase17** [comment]
making this work with vespa should be a priority

i think what makes sense is to add a method to vespa like "retrieve with metadata filter" or something (better named). this can be a new method that takes in a query + a filter

we can add that method in its own pr, that should be pr #1

after that, we can figure out the right abstraction to allow to use that in self-query

**Comment by srivatsanv1** [comment]
I am using redis and would love it if both redis hybrid search as well as SelfQueryRetriever  would be available for redis.

More importantly, SelfQueryRetriever  could be made independent of the vectorstore which is used though. I mean the LLM which returns the filter and the value could be made a separate entity which can then be used in any vectorstore.

**Comment by filippo82** [comment]
More thoughts:

---

Unfortunately, adding a new method to the Vespa retriever might not do the trick. Looking at the [implementation of the Vespa retriever](https://github.com/hwchase17/langchain/blob/master/langchain/retrievers/vespa_retriever.py), the query structure needs to be provided when creating the `VespaRetriever` object, as shown in the [docs](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/vespa_retriever.html):

```python
from langchain.retrievers.vespa_retriever import VespaRetriever

vespa_query_body = {
    "yql": "select content from paragraph where userQuery()",  # <- THIS PART
    "hits": 5,
    "ranking": "documentation",
    "locale": "en-us"
}
vespa_content_field = "content"
retriever = VespaRetriever(vespa_app, vespa_query_body, vespa_content_field)
``` 

When using the `SelfQueryRetriever` upstream, then this would require a modification of the value of the `yql` key. For example, with the query `What's a movie about toys after 1990`, the `yql` value would become:

```python
vespa_query_body = {
    "yql": "select content from paragraph where userQuery() AND year > 1990",  # <- THIS PART
    "hits": 5,
    "ranking": "documentation",
    "locale": "en-us",
    "query": "What's a movie about toys"
}
```

It should be possible to implement a clever logic to handle this modification but it can quickly become a daunting task because the definition of the `yql` entry is entirely left to the user. I think that it should be wise to add constraints to which kind of query one can build for Vespa (**if** its retriever must work with the `SelfQueryRetriever`).

I believe it is necessary to review how a `VespaRetriever` object is created.

---
@dev2049 I think that the recently introduced [`search` method](https://github.com/hwchase17/langchain/blob/ea64b1716d48050433c9815a40a69aee18b2690a/langchain/vectorstores/base.py#L78) could be removed (this is true if it is used by the `SelfQueryRetriever` only though).

For example, in the [`retrievers/self_query/base.py`](https://github.com/hwchase17/langchain/blob/ea64b1716d48050433c9815a40a69aee18b2690a/langchain/retrievers/self_query/base.py#L78), one could replace this:

```python
        search_kwargs = {**self.search_kwargs, **new_kwargs}
        docs = self.vectorstore.search(query, self.search_type, **search_kwargs)
``` 

with this:

```python
        kwargs = {
            "search_kwargs": {**self.search_kwargs, **new_kwargs},
            "search_type": self.search_type,
        }
        retriever = self.vectorstore.as_retriever(**kwargs)
        docs = retriever.get_relevant_documents(query)
```

---

I will have a go at a draft PR to (try to) tackle the issues discussed here.

**Comment by jobergum** [comment]
Hey, I'm with the Vespa team. 

The Vespa [query](https://docs.vespa.ai/en/reference/query-api-reference.html#model.querystring) API request parameter accepts queries expressed with [Vespa simple query syntax](https://docs.vespa.ai/en/reference/simple-query-language-reference.html), which is a typical search syntax you expect from web search engines (Well, except when Google launched G+ and they changed the way to search for an exact term). 

```
What's a +movie about +toys +year:>1990 
```

So there is still some flexibility with that, but I do think that we should a find a way to override the request body further as there are a lot of parameters that could be used, for example, [native Vespa embedders](https://docs.vespa.ai/en/embedding.html#embedding-a-query-text)

**Comment by filippo82** [comment]
Hi @jobergum 👋 thanks for joining the discussion.

Question: with your comment "we should a find a way to override the request body further", are you specifically referring to the `SelfQueryRetriever`? Or is it a more general comment for the `VespaRetriever`?

**Comment by filippo82** [comment]
Hi @jobergum, would you consider this a meaningful query?

```python
        {
            "yql": "select content from paragraph where userQuery() or {targetHits: 100}nearestNeighbor(embedding, first_query)",
            "query": "Where is Waldo?",
            "input.query(first_query)": "embed(bertModel, Where is Waldo?)",
            "type": "weakAnd",
            "hits": 5,
            "ranking": "documentation",
            "locale": "en-us"
        }
``` 

Or would you push for allowing a variable number of `input.query()` entries?

**Comment by filippo82** [comment]
> What we hope to add soon is support for referencing native request parameters in the embed function.

That would be indeed a nice improvement!

I am moving this conversation to the discussion of the PR #4546. I like what Davis has done but I will now suggest modifications to be able to leverage the `input.query`.
