### ISSUE TITLE
How can we set a limit for max tokens in ConversationSummaryMemory

### ISSUE THREAD

**Issue by m-ali-awan** [langchain-ai/langchain#4033]
Hi all,
One major benefit of using Summary method for context in Conversation is to save cost. But with increasing chat iterations, no of token keeps on increasing, significantly. 
Is there any parameter, by which I can set the max limit of Summary?

**Comment by giuice** [comment]
I think the solution is use [ConversationSummaryBufferMemory ](https://python.langchain.com/en/latest/modules/memory/types/summary_buffer.html)
```python
from langchain.chains import ConversationChain
conversation_with_summary = ConversationChain(
    llm=llm, 
    # We set a very low max_token_limit for the purposes of testing.
    memory=ConversationSummaryBufferMemory(llm=OpenAI(), max_token_limit=40),
    verbose=True
)
conversation_with_summary.predict(input="Hi, what's up?")
```

**Comment by m-ali-awan** [comment]
Thanks @giuice
