### ISSUE TITLE
llm.generate([query]) return ValueError: Got unknown type w

### ISSUE THREAD

**Issue by zigax1** [langchain-ai/langchain#4037]
Hello everyone! I am developing simple chat with pdf bot.

I am facing strange error. I and facing an error 
_raise ValueError(f"Got unknown type {message}")
ValueError: Got unknown type w_

Code snippet is:

```
from langchain.document_loaders import UnstructuredPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Pinecone
from langchain.embeddings.openai import OpenAIEmbeddings
import pinecone
from langchain.chat_models import ChatOpenAI
from langchain.chains.question_answering import load_qa_chain

OPENAI_API_KEY = ''
PINECONE_API_KEY = ''
PINECONE_API_ENV = ''

loader = UnstructuredPDFLoader('./field-guide-to-data-science.pdf')
data = loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=300)
texts = text_splitter.split_documents(data)

embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY, model='text-embedding-ada-002')

pinecone.init(
    api_key=PINECONE_API_KEY,
    environment=PINECONE_API_ENV
)
index_name = ""

docsearch = Pinecone.from_texts([t.page_content for t in texts], embeddings, index_name=index_name)

llm = ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.3, openai_api_key=OPENAI_API_KEY)

from langchain.memory import ConversationBufferMemory
from langchain.chains import ConversationalRetrievalChain


memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
rqa = ConversationalRetrievalChain.from_llm(llm, docsearch.as_retriever(), memory=memory)


def retrieve_answer(query, chat_history):
    memory.chat_memory.add_user_message(query)
  
    res = rqa({"question": query})
    retrieval_result = res["answer"]

    if "The given context does not provide" in retrieval_result:
        print(query)
        print([query])

        base_result = llm.generate([query])

        return base_result.generations[0][0].text
    else:
        return retrieval_result


messages = []

print("Welcome to the chatbot. Enter 'quit' to exit the program.")
while True:
    user_message = input("You: ")

    if user_message.lower() == "quit":
        break

    answer = retrieve_answer(user_message, messages)
    print("Assistant:", answer)
    memory.chat_memory.add_ai_message(answer)
    messages.append((user_message, answer))

```

           
This is really strange

**Comment by aakashrshah** [comment]
You probably need to pass it as llm.generate([HumanMessage(content=query)])

**Comment by MichaelCro** [comment]
Hello! Do you solve this error? When I use my fine-tuned fastchat model in langchain to do document QA, I got same error.

Here is my code,

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain import OpenAI,VectorDBQA
from langchain.document_loaders import DirectoryLoader
from langchain.chains import RetrievalQA

from langchain.chat_models import ChatOpenAI
import os


os.environ[ "OPENAI_API_KEY" ] = "EMPTY"
os.environ[ "OPENAI_API_BASE" ] = "http://localhost:8002/v1"

llm = ChatOpenAI(model="gpt-3.5-turbo")
embeddings = OpenAIEmbeddings(model="text-embedding-ada-002")

llm('hello')


----------------------------------------------------------------------------------------
And this is value error,
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[10], line 1
----> 1 llm("hello, what's your name")

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\base.py:208, in BaseChatModel.__call__(self, messages, stop, callbacks, **kwargs)
    201 def __call__(
    202     self,
    203     messages: List[BaseMessage],
   (...)
    206     **kwargs: Any,
    207 ) -> BaseMessage:
--> 208     generation = self.generate(
    209         [messages], stop=stop, callbacks=callbacks, **kwargs
    210     ).generations[0][0]
    211     if isinstance(generation, ChatGeneration):
    212         return generation.message

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\base.py:102, in BaseChatModel.generate(self, messages, stop, callbacks, tags, **kwargs)
    100 except (KeyboardInterrupt, Exception) as e:
    101     run_manager.on_llm_error(e)
--> 102     raise e
    103 llm_output = self._combine_llm_outputs([res.llm_output for res in results])
    104 generations = [res.generations for res in results]

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\base.py:94, in BaseChatModel.generate(self, messages, stop, callbacks, tags, **kwargs)
     90 new_arg_supported = inspect.signature(self._generate).parameters.get(
     91     "run_manager"
     92 )
     93 try:
---> 94     results = [
     95         self._generate(m, stop=stop, run_manager=run_manager, **kwargs)
     96         if new_arg_supported
     97         else self._generate(m, stop=stop)
     98         for m in messages
     99     ]
    100 except (KeyboardInterrupt, Exception) as e:
    101     run_manager.on_llm_error(e)

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\base.py:95, in <listcomp>(.0)
     90 new_arg_supported = inspect.signature(self._generate).parameters.get(
     91     "run_manager"
     92 )
     93 try:
     94     results = [
---> 95         self._generate(m, stop=stop, run_manager=run_manager, **kwargs)
     96         if new_arg_supported
     97         else self._generate(m, stop=stop)
     98         for m in messages
     99     ]
    100 except (KeyboardInterrupt, Exception) as e:
    101     run_manager.on_llm_error(e)

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\openai.py:324, in ChatOpenAI._generate(self, messages, stop, run_manager, **kwargs)
    317 def _generate(
    318     self,
    319     messages: List[BaseMessage],
   (...)
    322     **kwargs: Any,
    323 ) -> ChatResult:
--> 324     message_dicts, params = self._create_message_dicts(messages, stop)
    325     params = {**params, **kwargs}
    326     if self.streaming:

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\openai.py:364, in ChatOpenAI._create_message_dicts(self, messages, stop)
    362         raise ValueError("`stop` found in both the input and default params.")
    363     params["stop"] = stop
--> 364 message_dicts = [_convert_message_to_dict(m) for m in messages]
    365 return message_dicts, params

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\openai.py:364, in <listcomp>(.0)
    362         raise ValueError("`stop` found in both the input and default params.")
    363     params["stop"] = stop
--> 364 message_dicts = [_convert_message_to_dict(m) for m in messages]
    365 return message_dicts, params

File D:\Anaconda3\envs\langchain1\lib\site-packages\langchain\chat_models\openai.py:131, in _convert_message_to_dict(message)
    125     message_dict = {
    126         "role": "function",
    127         "content": message.content,
    128         "name": message.name,
    129     }
    130 else:
--> 131     raise ValueError(f"Got unknown type {message}")
    132 if "name" in message.additional_kwargs:
    133     message_dict["name"] = message.additional_kwargs["name"]

ValueError: Got unknown type h
