### ISSUE TITLE
Make DirectoryLoader to read file in parallel to reduce file reading time

### ISSUE THREAD

**Issue by talhaanwarch** [langchain-ai/langchain#4041]
How can I read the files in parallel to speed up the process https://github.com/hwchase17/langchain/blob/f3ec6d2449f3fe0660e4452bd4ce98c694dc0638/langchain/document_loaders/directory.py#L74

**Comment by N-E-W-T-O-N** [comment]
How big are you files

**Comment by PawelFaron** [comment]
I will try to add multithreading for it.
