### ISSUE TITLE
How do I customize the prompt for the zero shot agent ?

### ISSUE THREAD

**Issue by jiyer2016** [langchain-ai/langchain#4044]
I create an agent using:

```
zero_shot_agent = initialize_agent(
    agent="zero-shot-react-description",
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=3
)
```

I now want to customize the content of the default prompt used by the agent.
I wasn't able to locate any documented input parameters to initialize_agent() to do so.
Is there a way to accomplish this ?

**Comment by berkedilekoglu** [comment]
You can see the already defined prompt on your agent by using: 

`print(zero_shot_agent.agent.llm_chain.prompt.template)
`

Also you can define a message and change it like that:

```
sys_message = "YOUR NEW PROMPT IS HERE"
zero_shot_agent.agent.llm_chain.prompt.template = sys_message
```

**Comment by jiyer2016** [comment]
Thank you @berkedilekoglu  - I tried it and this works for me.

However, I suspect this solution bypasses the prompt validation that happens when the PromptTemplate is constructed. Do you agree ?

Was hoping for a solution where the custom prompt could be set via the call to initialize_agent()
Let me know.

**Comment by s-1-n-t-h** [comment]
@berkedilekoglu hi, can u help me out on how to change prompt with lang chain JS, cuz it seems like not available on the documentation too!

**Comment by s-1-n-t-h** [comment]
@berkedilekoglu no problem, thanks for replying out !

**Comment by felipeff** [comment]
> Thank you @berkedilekoglu - I tried it and this works for me.
> 
> However, I suspect this solution bypasses the prompt validation that happens when the PromptTemplate is constructed. Do you agree ?
> 
> Was hoping for a solution where the custom prompt could be set via the call to initialize_agent() Let me know.

Old thread, but I found it while searching how to do the same thing, so here it goes: 

```from langchain.agents.mrkl.prompt import FORMAT_INSTRUCTIONS, PREFIX, SUFFIX
PREFIX = """Answer the following questions as best you can. You have access to the following tools:"""
FORMAT_INSTRUCTIONS = """Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question"""
SUFFIX = """Begin!

Question: {input}
Thought:{agent_scratchpad}"""

agent = initialize_agent(
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    tools=tools,
    llm=llm,
    agent_kwargs={
        'verbose':VERBOSE,
        'prefix':PREFIX,
        'format_instructions':FORMAT_INSTRUCTIONS,
        'suffix':SUFFIX
    }
)
```

**Comment by runninghare** [comment]
I was facing the same issue.

Love the answer about using agent_kwargs. In my case, replacing PREFIX is enough. FORMAT_INSTRUCTIONS requires duplicating a lot of existing contents and variables which are not necessary.

You can find the entire built-in prompts in /langchain/agents/<agent type>/prompt.py

**Comment by geriang** [comment]
you can add prefix in langchainjs like this:

    const executor = await initializeAgentExecutorWithOptions(tools, llm, {
        agentType: "structured-chat-zero-shot-react-description",
        verbose: true,
        memory: new BufferMemory({
            chatHistory: new ChatMessageHistory(pastMessages),
            returnMessages: true,
            memoryKey: "chat_history"
        }),
        agentArgs: {
            inputVariables: ["input", "agent_scratchpad", "chat_history"],
            memoryPrompts: [new MessagesPlaceholder("chat_history")],
            **prefix: "you are a chat bot. Your priority is to chat with enquirers and use tools when necessary.",**
        },

    });

**Comment by jonra1993** [comment]
If you are looking for how to customize prompts of other agents also it is a good idea to check these paths

<img width="1254" alt="image" src="https://github.com/langchain-ai/langchain/assets/23468720/c0acb935-4280-4a2b-ac6f-506149b76e2e">
<img width="1254" alt="image" src="https://github.com/langchain-ai/langchain/assets/23468720/61a19e2b-d112-470a-b384-98abdfc24697">

**Comment by Boopalanoptisol** [comment]
@berkedilekoglu  Is it possible to add memory in the zero-shot-react-description agent. If yes Please Give me some explanation. I tried a lot can't able to add.

**Comment by jonra1993** [comment]
Hi @Boopalanoptisol you can do that with something like this on AgentExecutor

```py
    message_history = PostgresChatMessageHistory(
        connection_string=f"postgresql://{settings.DATABASE_USER}:{settings.DATABASE_PASSWORD}@{settings.DATABASE_HOST}/alita_chat",
        session_id=str(user_id),
    )

    memory = ConversationBufferMemory(
        memory_key="chat_history", return_messages=True, chat_memory=message_history
    )
  
  ...........
  Agent code and tools  
  ...........
  agent_executor = AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        verbose=False,
        handle_parsing_errors=True,
        memory=memory,
    )
```

**Comment by aryansid** [comment]
This is useful: https://python.langchain.com/docs/modules/agents/how_to/custom_llm_agent

**Comment by vishnua2j** [comment]
> @berkedilekoglu Is it possible to add memory in the chat-zero-shot-react-description agent. If yes Please Give me some explanation. I tried a lot can't able to add.

I am also facing the same issue ....Kindly help me if you were able to find the solution.
