### ISSUE TITLE
Question: System messages with AgentExecutors

### ISSUE THREAD

**Issue by pelyhe** [langchain-ai/langchain#4048]
Hi!

I am working with AgentExecutors, which are being created with the create_llama_chat_agent() function.
The relevant part of the code looks like this:
```
llm = OpenAI(temperature=0, model_name="gpt-3.5-turbo")

return create_llama_chat_agent(
        toolkit,
        llm,
        memory=memory,
        verbose=True
)
```
It works perfectly, but I want to add system messages to every request. Can you help me with this? Every answer is appreciated, if you have an alternative for system messages, that could be useful as well.
My use-case is that I have a document describing how should I handle different type of users. I am trying to pass the type of the user in system messages so the AI can response according to the system message and the description provided in context.

Thanks in advance!

**Comment by whitead** [comment]
Here's an example for using a [custom system message](https://github.com/whitead/robust-mrkl/blob/main/rmrkl/agent.py)


Here's the relevant snippet for your own custom agent:
```py
class ChatZeroShotAgent(ZeroShotAgent):
    @classmethod
    def create_prompt(
        cls,
        tools: Sequence[BaseTool]
    ) -> PromptTemplate:
        tool_strings = "\n".join(
            [f"    {tool.name}: {tool.description}" for tool in tools]
        )
        tool_names = ", ".join([tool.name for tool in tools])
        format_instructions = FORMAT_INSTRUCTIONS.format(
            tool_names=tool_names, tool_strings=tool_strings
        )
        human_prompt = PromptTemplate(
            template=QUESTION_PROMPT,
            input_variables=["input"],
            partial_variables={"tool_strings": tool_strings},
        )
        human_message_prompt = HumanMessagePromptTemplate(prompt=human_prompt)
        ai_message_prompt = AIMessagePromptTemplate.from_template(SUFFIX)
        system_message_prompt = SystemMessagePromptTemplate.from_template(
            format_instructions
        )

        return ChatPromptTemplate.from_messages(
            [system_message_prompt, human_message_prompt, ai_message_prompt]
        )
```
