### ISSUE TITLE
Tools with partials (Partial functions not yet supported in tools)

### ISSUE THREAD

**Issue by whitead** [langchain-ai/langchain#4053]
We commonly used this pattern to create tools:

```py
from langchain.tools import Tool
from functools import partial

def foo(x, y):
    return y

Tool.from_function(
    func=partial(foo, "bar"),
    name = "foo",
    description="foobar"
)
```

which as of 0.0.148 (I think) gives a pydantic error "Partial functions not yet supported in tools." We must use instead this format:

```py
from langchain.tools import Tool
from functools import partial

def foo(x, y):
    return y

Tool.from_function(
    func=lambda y: foo(x="bar",y=y),
    name = "foo",
    description="foobar"
)
```

It would be nice to again support partials.

**Comment by vowelparrot** [comment]
Thanks for issuing this bug, and for your patience with all the restructuring!  This should be re-permitted in our next release.
