### ISSUE TITLE
Multiple combine prompts when using Map-Reduce

### ISSUE THREAD

**Issue by sebderhy** [langchain-ai/langchain#4054]
Hi, 

Maybe this is already doable today, but I didn't manage to, so I'll try to ask it here as a feature request... I'd like to do a map-reduce chain, but with 2 different reductions happening in parallel (therefore, I want to have 2 final outputs).

I managed to do it by doing the 2 reductions sequentially, and re-using the intermediary output of the map-reduce summarize chain. But this adds complexity and runtime, so ideally, I would like to be able to give an array of `combine_prompt` to the `load_summarize_chain` function. Is that feasible?

**Comment by sandeep-datamatics** [comment]
Even I am looking for this feature too.  Would be of great help if we get it.

**Comment by aeronesto** [comment]
@sebderhy Thanks for opening this issue. I don't have a need for running the chains in parallel; I just needed to get the output of the map step and I saw that it's possible in this post. For anyone like me:

"To get the output of the map step in Langchain's map reduce, you can use the `return_intermediate_steps` parameter in the MapReduceDocumentsChain class. By setting `return_intermediate_steps=True`, the chain will return the results of the map step in the output. This allows you to access the individual summaries generated for each document during the map step."

How to do it in python:
https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps
