### ISSUE TITLE
No Pinecone filter support to fromExistingIndex

### ISSUE THREAD

**Issue by kulaone** [langchain-ai/langchain#4057]
When using PineconeStore.fromExistingIndex with JS there is a way to add Pinecone filter to store.
```
  const vectorStore = await PineconeStore.fromExistingIndex(
      new OpenAIEmbeddings(),
      { pineconeIndex, filter, namespace: NAMESPACE}
    );
```
However, when using Pinecone.from_existing_index with Python, there is no way to add the filter to the store. Therefore, I cannot use a filter in ConversationalRetrievalChain.

**Comment by Vasilije1990** [comment]
Top of the morning to you! I added support and opened a PR here: https://github.com/hwchase17/langchain/pull/4663
