### ISSUE TITLE
Model Limitations

### ISSUE THREAD

**Issue by XaviscoB** [langchain-ai/langchain#4075]
I would like to give a simple suggestion. There could be support or some way to add custom models instead of just using the OpenAI model. There are projects that use third-party platforms that use the Chat-GPT model and can be accessed via API. The reason for this is the cost of the API from the platforms offered, especially from OpenAI. This option would provide a cost-free and more accessible path.
Here is a list of some projects with this theme:

[OpenGPT](https://github.com/uesleibros/OpenGPT)
[GPT4FREE](https://github.com/xtekky/gpt4free)

**Comment by vowelparrot** [comment]
Have you tried any of the other LLM integrations yet? https://python.langchain.com/en/latest/modules/models/llms/integrations.html

Huggingface, llama, anthropic, cohere , and gpt4all are all popular models people use

**Comment by leo-gan** [comment]
Yeap. Now it is 26? integrations with different LLM providers. Several of them provide many LLM. Several others use popular OS or SaaS models.
Examples: 
- https://docs.cohere.com/docs/models
- https://docs.ai21.com/docs/jurassic-2-models
etc.

But maybe you mean something different?
