### ISSUE TITLE
FAISS similarity search with score issue

### ISSUE THREAD

**Issue by Chetan-Yeola** [langchain-ai/langchain#4086]
Hi.
I am trying to find out the similarity search score. but I got the score In 3 digits.
![image](https://user-images.githubusercontent.com/72593205/236118690-eed8fdf0-3e6d-4466-9cdb-9a15ddb3aefc.png)

**Comment by PawelFaron** [comment]
Please provide working code that can reproduce this issue.

**Comment by vowelparrot** [comment]
You ahve to specify a normalization function that works with your embeddings. In this case your HuggingFaceEmbeddings aren't at unit norm, so the default one won't suffice.

The default is

```python
def _default_relevance_score_fn(score: float) -> float:
    """Return a similarity score on a scale [0, 1]."""
    # The 'correct' relevance function
    # may differ depending on a few things, including:
    # - the distance / similarity metric used by the VectorStore
    # - the scale of your embeddings (OpenAI's are unit normed. Many others are not!)
    # - embedding dimensionality
    # - etc.
    # This function converts the euclidean norm of normalized embeddings
    # (0 is most similar, sqrt(2) most dissimilar)
    # to a similarity function (0 to 1)
    return 1.0 - score / math.sqrt(2)
```

You could try instead to use

```python
def score_normalizer(val: float) -> float:
    return 1 - 1 / (1 + np.exp(val))
```

And initialize Faiss with `relevance_score_fn=score_normalizer`

**Comment by Jeffwan** [comment]
@vowelparrot 
 
A few questions

1. Seems this is for relevance score, is it same as the score defined in `similarity_search_with_score`?  I notice it only invoked here https://github.com/hwchase17/langchain/blob/f0cfed636f37ea7c5171541e0df3f814858f1550/langchain/vectorstores/faiss.py#L475-L488.  `similarity_search_with_score_by_vector` used by `similarity_search_with_score` doesn't have any post processing https://github.com/hwchase17/langchain/blob/f0cfed636f37ea7c5171541e0df3f814858f1550/langchain/vectorstores/faiss.py#L180 If that should be fixed, I can help on it

2. I change to your normalizer but after that, all scores become 1.. Did you see similar issues? 

```
score : 68.8683853149414, result : 1.0
score : 74.28987121582031, result : 1.0
score : 77.00814056396484, result : 1.0
score : 79.08580017089844, result : 1.0
```

**Comment by hwchase17** [comment]
@Jeffwan its a good question whether its huggingface embeddings or FAISS. i like your PR, but im going to add it as an optional parameter probably, both for backwards compatability and flexilibty

**Comment by lmz0506** [comment]
你好，我遇到了同样的问题。
可以告诉我你是怎样解决的吗？

**Comment by lmz0506** [comment]
Hello, I have encountered the same problem.
Can you tell me how you solved it?

**Comment by Yanni8** [comment]
Hey @lmz0506 

It looks like this is due to the fact, that the Hugging Face model doesn't work with the default normalize function. I resolved this by writing my own normalize function. It works by mapping the range `0` - `∞` on to the range `0` - `1`. There are [different ways](https://math.stackexchange.com/questions/3116137/convert-numbers-between-0-and-infinity-to-numbers-between-0-0-and-1-0
) to map the range  `0` - `∞` on to the range `0` - `1`. One of those functions already got mentioned by [vowelparrot](https://github.com/langchain-ai/langchain/issues/4086#issuecomment-1535262345)

**Comment by AlvinAi96** [comment]
You could turn ``normalize_L2 = True`` manually on the path of ``/your_envs/langchain-chatchat-qwen/lib/python3.10/site-packages/langchain/vectorstores/faiss.py`` as below:
![image](https://github.com/langchain-ai/langchain/assets/42187008/71be2132-32c9-4c81-9ede-420db01dc199)

**Comment by LXlearning** [comment]
> 您可以按照以下方式`normalize_L2 = True`手动打开路径：`/your_envs/langchain-chatchat-qwen/lib/python3.10/site-packages/langchain/vectorstores/faiss.py` ![图像](https://private-user-images.githubusercontent.com/42187008/312681027-71be2132-32c9-4c81-9ede-420db01dc199.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjczMjEsIm5iZiI6MTcxNjg2NzAyMSwicGF0aCI6Ii80MjE4NzAwOC8zMTI2ODEwMjctNzFiZTIxMzItMzJjOS00YzgxLTllZGUtNDIwZGIwMWRjMTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMzAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMzA0MWY2NjExNzUzMmZiZGM5NjAxMWRjY2Y1MjExZTgyYzlhOTFkMjRlZjg3MmRiZTNjZWRhZTJhMmM3YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MSAMhok43ep9ShGmCrzX0neHZKVA76QfGq4XObKprtM)

If you use FAISS.from_text, you should also set  ```__from(normalize_L2 = True)``` to solve the promblem
