### ISSUE TITLE
fail to user ”mmr“ retriever for chroma DB

### ISSUE THREAD

**Issue by ddsky2023** [langchain-ai/langchain#4098]
code as following：
retriever = vectordb.as_retriever(search_type="mmr")
docs = retriever.get_relevant_documents(question)
it failed with follow error：
TypeError: __query_collection() got an unexpected keyword argument 'include'

I check the source code，it really no include param for __query_collection() function in langchain/vectorstores/chroma.py

**Comment by kmi98** [comment]
I have this question as well. Are you able to fix it?
