### ISSUE TITLE
docs: non-working code for Serper API tool

### ISSUE THREAD

**Issue by alexcg1** [langchain-ai/langchain#4105]
The code block [here](https://python.langchain.com/en/latest/modules/agents/tools/examples/google_serper.html#obtaining-results-with-metadata) doesn't run:

```python
search = GoogleSerperAPIWrapper()
results = search.results("Apple Inc.")
pprint.pp(results)
```

Doing so results in:

```
AttributeError: 'GoogleSerperAPIWrapper' object has no attribute 'results'
```

This seems to be the only way I can get search engine metadata (like URLs for results). Would love to know if there are other methods too

**Comment by rick2047** [comment]
This is confusing because results does exist

https://github.com/hwchase17/langchain/blob/624554a43a1ab0113f3d79ebcbc9e726faecb339/langchain/utilities/google_serper.py#L51

**Comment by alexcg1** [comment]
Yup. I just checked the API reference too, and I see it there. I'm assuming the reference is auto-generated so this is a real headscratcher

**Comment by rick2047** [comment]
you should probably check the usual things like if you have langchain installed properly. If you are using VS code you can ctrl+click on the class name and it will take you to your local file. See if you have results func there.

**Comment by alexcg1** [comment]
So:
- I cleared my env and re-installed langchain
- Checked the local file. No `results` method

To narrow it down, I also tried on [Google Colab](https://colab.research.google.com/drive/1Jofji2a53xLlxTBj6rQd-Nv2WcDzknyH#scrollTo=UCKBg49Wsewx). Same result :/

Langchain version is 0.0.157

**Comment by alexcg1** [comment]
I see the code was updated just a few hours ago:
![image](https://user-images.githubusercontent.com/4182659/236202943-ab1019b7-37d9-4c67-9ebb-64e891b65a1c.png)

And last release was yesterday. So I guess I just have to wait for next release

**Comment by faisal-saddique** [comment]
Hi, did someone manage to find a way around it?

**Comment by faisal-saddique** [comment]
I think I found a possible fix to this:

`search = GoogleSerperAPIWrapper()
results = search._google_serper_search_results("Coca cola",gl="us",hl="en")`

It seems to give me back the results.

**Comment by lamaranelson** [comment]
It looks like it depends on the Python version. 

In my case, in 3.9 it works with `results = search._google_serper_search_results("Coca cola", gl="us", hl="en")`
and 3.10 it works using `results = search._google_serper_api_results("Coca cola", gl="us", hl="en")`

**Comment by faisal-saddique** [comment]
@lamaranelson could you please confirm which version of Langchain you are using?

**Comment by rzykov** [comment]
Hey, I've got the same problem after 
pip install  compress-gpt

Then I did
pip uninstall compress-gpt
pip install --force langchain

Now it works!
