### ISSUE TITLE
Unknown Agent: "structured-chat-zero-shot-react-description" Error

### ISSUE THREAD

**Issue by crabmun** [langchain-ai/langchain#4108]
Getting a value error when trying to use the structured agent.

ValueError: Got unknown agent type: structured-chat-zero-shot-react-description. Valid types are: dict_keys([<AgentType.ZERO_SHOT_REACT_DESCRIPTION: 'zero-shot-react-description'>, <AgentType.REACT_DOCSTORE: 'react-docstore'>, <AgentType.SELF_ASK_WITH_SEARCH: 'self-ask-with-search'>, <AgentType.CONVERSATIONAL_REACT_DESCRIPTION: 'conversational-react-description'>, <AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION: 'chat-zero-shot-react-description'>, <AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION: 'chat-conversational-react-description'>]).

**Comment by PawelFaron** [comment]
Please provide working code that can reproduce this issue.

**Comment by crabmun** [comment]
import os
os.environ["OPENAI_API_KEY"] = "XXXXXXXXXXX"

from langchain.llms import OpenAI

import os
os.environ["LANGCHAIN_TRACING"] = "true" # If you want to trace the execution of the program, set to "true"

from langchain.agents import AgentType  # Replace this import statement according to your project structure

from langchain.agents import AgentType
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent

from langchain.agents.agent_toolkits import PlayWrightBrowserToolkit
from langchain.tools.playwright.utils import (
    create_async_playwright_browser,
    create_sync_playwright_browser, # A synchronous browser is available, though it isn't compatible with jupyter.
)

# This import is required only for jupyter notebooks, since they have their own eventloop
import nest_asyncio
nest_asyncio.apply()



async_browser = create_async_playwright_browser()
browser_toolkit = PlayWrightBrowserToolkit.from_browser(async_browser=async_browser)
tools = browser_toolkit.get_tools()

llm = ChatOpenAI(temperature=0) # Also works well with Anthropic models
agent_chain = initialize_agent(tools, llm, agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

response = agent_chain.arun(input="Hi I'm Erica.")
print(response)

**Comment by crabmun** [comment]
i'm using the latest version of langchain. 

yes it's the newest agent i'm wanting to test out. 

When i print out agent types it shows the new structured tool agent is there. 

to get await working in put it in that function down the bottom of the code.

any ideas?

**Comment by crabmun** [comment]
tried multiple fixes, still getting "AttributeError: STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION"

**Comment by jolawre** [comment]
did you get the fix, am also getting same problem
