### ISSUE TITLE
AsyncCallbackManager Class from base.py gone after version 0.0.154 referenced from chat-langchain query_data.py

### ISSUE THREAD

**Issue by robstoof** [langchain-ai/langchain#4109]
This is a part of the error I get back when running the chat-langchain uvicorn server. The base.py file doesn't have the AsyncCallbackManager class anymore since version 0.0.154.

from query_data import get_chain
File "/home/user/Documents/Langchain/chat-langchain/./query_data.py", line 2, in
from langchain.callbacks.base import AsyncCallbackManager
ImportError: cannot import name 'AsyncCallbackManager' from 'langchain.callbacks.base' (/home/user/Documents/Langchain/callbacks/base.py)

**Comment by liebscher** [comment]
Same issue. Changed to `from langchain.callbacks.manager import AsyncCallbackManager` but that just introduces further errors, e.g.:

```
Error in on_llm_start callback: 'StreamingLLMCallbackHandler' object has no attribute 'ignore_llm'
```

**Comment by MChorfa** [comment]
Same here the callback events are not picked up even after implementing the llm_ignore within the callback handler

**Comment by nadavcohe** [comment]
same here, please assist

**Comment by HaroldNelson** [comment]
It is very much an issue as of September 23, 2023.
