### ISSUE TITLE
langchain.retrievers.document_compressors.CohereRerank issue

### ISSUE THREAD

**Issue by cnevelle-blueprint** [langchain-ai/langchain#4125]
Thanks for the recent updates. I am getting the following issue on CohereRerank:

I am getting this error when following [This documentation](https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/cohere-reranker.html) exactly:

`pydantic.error_wrappers.ValidationError: 1 validation error for CohereRerank client field required (type=value_error.missing)`

**Comment by cnevelle-blueprint** [comment]
Unsure if this is correct, but a quick fix that worked for my use case is commenting out
`client: Client`
in **cohere_rerank.py**

**Comment by adivik2000** [comment]
+1

**Comment by averma12** [comment]
> Unsure if this is correct, but a quick fix that worked for my use case is commenting out `client: Client` in **cohere_rerank.py**

I think you need to initalize the client and pass the client object

**Comment by averma12** [comment]
> > Unsure if this is correct, but a quick fix that worked for my use case is commenting out `client: Client` in **cohere_rerank.py**
> 
> I think you need to initalize the client and pass the client object

An update so there is an issue caused by Forward refs I solved it by using the following lines of code
from typing import ForwardRef
from pydantic import BaseModel

class CustomCohereRerank(CohereRerank):
    class Config(BaseModel.Config):
        arbitrary_types_allowed = True

CustomCohereRerank.update_forward_refs()


llm = OpenAI(temperature=0)
compressor = CustomCohereRerank(client=co)
compression_retriever = ContextualCompressionRetriever(base_compressor=compressor, base_retriever=retriever)

**Comment by averma12** [comment]
I raised a PR for the fix. I fixed the type for the client. Need to add a change in the example docs where you need to initialize the cohere client and pass that to the rerank class.not sure where you change that

**Comment by aijdsofttech** [comment]
> > > Unsure if this is correct, but a quick fix that worked for my use case is commenting out `client: Client` in **cohere_rerank.py**
> > 
> > 
> > I think you need to initalize the client and pass the client object
> 
> An update so there is an issue caused by Forward refs I solved it by using the following lines of code from typing import ForwardRef from pydantic import BaseModel
> 
> class CustomCohereRerank(CohereRerank): class Config(BaseModel.Config): arbitrary_types_allowed = True
> 
> CustomCohereRerank.update_forward_refs()
> 
> llm = OpenAI(temperature=0) compressor = CustomCohereRerank(client=co) compression_retriever = ContextualCompressionRetriever(base_compressor=compressor, base_retriever=retriever)
> 
> where co is co = Client(key) Also this solution is a workaround. The issue is the type hinting for the client variable.

###  for me below  code is working
`from langchain.retrievers.document_compressors import CohereRerank
from langchain.retrievers import ContextualCompressionRetriever
import cohere
from cohere import Client
class CustomCohereRerank(CohereRerank):
    class Config(CohereRerank.Config):
        arbitrary_types_allowed = True
        
CustomCohereRerank.update_forward_refs()
compressor=CustomCohereRerank(cohere_api_key="",client=Client,top_n=50)`
