### ISSUE TITLE
OpenAI chain crashes due to missing content key

### ISSUE THREAD

**Issue by venatir** [langchain-ai/langchain#4140]
To replicate:
Make hundreds of simultaneous calls to AzureAI using gpt-3.5-turbo. I was using about 60 requests per minute.
About once every 3 minute you get a response that is empty that has no `content` key. There is an easy fix for this. I pushed a PR that solves the problem: https://github.com/hwchase17/langchain/pull/4139

**Comment by shreyabhadwal** [comment]
What error do you get when it crashes?
