### ISSUE TITLE
Issue: ValueError: Redis failed to connect: You must add the RediSearch (>= 2.4) module from Redis Stack. Please refer to Redis Stack docs: https://redis.io/docs/stack/

### ISSUE THREAD

**Issue by live4fun** [langchain-ai/langchain#4161]
### Issue you'd like to raise.

I'd like to use Redis as vector database and  installed redis-4.5.4. 

An error occurred after executing the code.
**Redis.from_documents(split_docs, embeddings, redis_url="redis://10.110.80.158:6379")**

How can I fix this issue.

**Comment by zjmvwb1** [comment]
Make sure you installed redis in correct version , uninstalled redisearch, and the split_docs's format is correct. 

If it still not work , go to langchains->vectorstore->redis, find function "_check_redis_module_exist", print the if condition to see why it not fit. If you are sure your redis version actually fit the condition but still not work, comment the condition and always pass it, sometimes it works, but it is very risky , as you changed langchain source code and might fail in following steps. The is the last way to solve it.
