### ISSUE TITLE
How to pass multiple arguments to tool? 

### ISSUE THREAD

**Issue by mzhadigerov** [langchain-ai/langchain#4197]
### Issue you'd like to raise.

Hi I want to pass multiple arguments to a tool, that was created using `@tool` decorator. E.g.:

```python
@tool
def test(query: str, smth: str) -> str:
  """description"""
   return "test"


tools = [
   lambda query, smth: test(query, smth)
]

initialize_agent(tools...)
```

I'm getting an error. In the example [in the docs](https://python.langchain.com/en/latest/modules/agents/tools/multi_input_tool.html) , it is shown that agent decides what to pass, but I don't want such a behavior, I want ability to pass arguments myself along with a query.

**Comment by abhinav-rafa** [comment]
We have a similar need to be able to be able to load a document from a vector store based on your user input in one of the tools. Unable to find any docs on if an agent can be configured to have Tools that have multiple input PromptTemplates.

**Comment by mzhadigerov** [comment]
@abhinav-rafa Hi! For anyone who is interested, I was be able to pass a custom arguments using `Tool` class, like this:

```python
    tools = [
        Tool(
            name="Internet search",
            func=lambda query, custom=custom: str(search_from_internet(query, custom)),
            description="useful when user's query was not answered by database and performing Internet search is necessary"
        )
    ]
   ```

**Comment by abhinav-rafa** [comment]
@mzhadigerov Thank you for the pointer!

**Comment by shuvracse03** [comment]
Still there is an issue. For example, 
Let say my custom tool takes 3 input parameters:
bool, str, int

How to feed these inputs to the agent who is using the inputs? Usually we run agent like agent.run('string'). But is there any way to do like agent.run({'input1: input1, 'input2': input2, 'input3': input3}) ?

**Comment by rdhillbb** [comment]
where you able to get this to work ?

**Comment by rambabusure** [comment]
what about passing as single array of inputs ?

**Comment by rdhillbb** [comment]
I used StructuredTool.from_function for single and multi parameters.
You will need to use
agent = initialize_agent(
    tools,
    llm2,
    agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    memory=memory,
    verbose=True,
)
Reference Documentation:
https://python.langchain.com/docs/modules/agents/tools/multi_input_tool

**Comment by ozkit** [comment]
`description = 'Use this tool with arguments like "{{"start_date": "yyyy-mm-dd", "max_results": int}}" when you need to retrieve events"`

**Comment by shubhamofbce** [comment]
@ozkit Thanks your comment helped me. I am getting inputs and string and now i can change it to dict and read keys.

**Comment by Ortega-Dan** [comment]
Such a saver! Thank you @ozkit
