### ISSUE TITLE
:pray: Code sample to tun a csv agent locally (no OpenAI)

### ISSUE THREAD

**Issue by adriens** [langchain-ai/langchain#4206]
### Issue with current documentation:

Almost all documentations I found to build a chain are using OpenAPI.

### Idea or request for content:

Create an equivalent of the excellent [CSV Agent](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/csv.html) but that could be used : 

- :100: locally (no API calls, only local models)
- :money_with_wings:  **Free** huggingchat API calls

**Comment by susen-mym** [comment]
Hi, 
I can't seem to access the code sample, is it removed? I would like to find out more on this.
