### ISSUE TITLE
Unable to add qa_prompt to ConversationalRetrievalChain.from_llm

### ISSUE THREAD

**Issue by yvann-ba** [langchain-ai/langchain#4225]
### System Info

since the new version i can't add qa_prompt, i would like to customize the prompt how to do?

Error: 1 validation error for ConversationalRetrievalChain qa_prompt extra fields not permitted (type=value_error.extra)

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

        llm = ChatOpenAI(model_name=self.model_name, temperature=self.temperature)

       
        retriever = self.vectors.as_retriever(search_kwargs={"k": 5})
        chain = ConversationalRetrievalChain.from_llm(
            llm=llm,
            qa_prompt = self.QA_PROMPT,

            chain_type=self.chain_type,
            retriever=retriever,
            verbose=True,
            return_source_documents=True
        )

### Expected behavior

Use qa_prompt

**Comment by hanqing-blend** [comment]
I'm facing the same issue. I guess it might because the current version of langchain doesn't have this parameter anymore.
0.0162
```python
    @classmethod
    def from_llm(
        cls,
        llm: BaseLanguageModel,
        retriever: BaseRetriever,
        condense_question_prompt: BasePromptTemplate = CONDENSE_QUESTION_PROMPT,
        chain_type: str = "stuff",
        verbose: bool = False,
        combine_docs_chain_kwargs: Optional[Dict] = None,
        **kwargs: Any,
    ) -> BaseConversationalRetrievalChain:
        """Load chain from LLM."""
        combine_docs_chain_kwargs = combine_docs_chain_kwargs or {}
        doc_chain = load_qa_chain(
            llm,
            chain_type=chain_type,
            verbose=verbose,
            **combine_docs_chain_kwargs,
        )
        condense_question_chain = LLMChain(
            llm=llm, prompt=condense_question_prompt, verbose=verbose
        )
        return cls(
            retriever=retriever,
            combine_docs_chain=doc_chain,
            question_generator=condense_question_chain,
            **kwargs,
        )
```

Here is a version I found someone posted in April:
```python
@classmethod
    def from_llm(
        cls,
        llm: BaseLanguageModel,
        retriever: BaseRetriever,
        condense_question_prompt: BasePromptTemplate = CONDENSE_QUESTION_PROMPT,
        qa_prompt: Optional[BasePromptTemplate] = None,
        chain_type: str = "stuff",
        **kwargs: Any,
    ) -> BaseConversationalRetrievalChain:
        """Load chain from LLM."""
        doc_chain = load_qa_chain(
            llm,
            chain_type=chain_type,
            prompt=qa_prompt,
        )
        condense_question_chain = LLMChain(llm=llm, prompt=condense_question_prompt)
        return cls(
            retriever=retriever,
            combine_docs_chain=doc_chain,
            question_generator=condense_question_chain,
            **kwargs,
        )
```

**Comment by init5god** [comment]
I figure it out. Its exactly that the problem use langchain==0.0.123 and it will work again.

**Comment by haymaicc** [comment]
`combine_docs_chain_kwargs={'prompt': qa_prompt}`
it works for me

**Comment by TechnoRahmon** [comment]
> `combine_docs_chain_kwargs={'prompt': qa_prompt}` it works for me

this worked for me, thnaks @haymaicc

**Comment by the-radar** [comment]
I'm so glad I came here, this helped me a lot. 

> `combine_docs_chain_kwargs={'prompt': qa_prompt}` 

But I can't figure out how to make this work in an async context. Has anyone had to tackle that yet?

**Comment by ShantanuNair** [comment]
@haymaicc does it set a system prompt though?

**Comment by fritol** [comment]
> 

wondering the same

**Comment by fritol** [comment]
> @haymaicc does it set a system prompt though?
ive been wondering the same

i still keep getting 

`ValidationError: 1 validation error for LLMChain
prompt
  value is not a valid dict (type=type_error.dict)`
for
combine_docs_chain_kwargs
