### ISSUE TITLE
Chroma VectorStore document cannot be updated

### ISSUE THREAD

**Issue by adieyal** [langchain-ai/langchain#4229]
### System Info

Given how chroma results are converted to Documents, I don't think it's possible to update those documents  since the id is not stored, 

[Here is the current implementation](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py#L27-L37)

Would it make sense to add the id into the document metadata?

### Who can help?

@jeffchuber 
@claust

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This is a design question rather than a bug. Any request such as [similarity_search](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py#LL164C9-L164C26) returns List[Document] but these documents don't contain the original chroma uuid.

### Expected behavior

Some way to be able to change the metadata of a document and store the changes in chroma, even if it isn't part of the VectorStore interface.

**Comment by jeffchuber** [comment]
@adieyal  - this would be great! it would also allow easy updates, deletions, etc. 

@hwchase17 what are your thoughts?

**Comment by adieyal** [comment]
Based on that comment, I think I was referring to user-ids - I didn't realise there was a difference.

**Comment by jeffchuber** [comment]
@adieyal there are the ids the user provides to the database (for tracking purposes) and then chroma also generates a `uuid` for each embedding - https://github.com/chroma-core/chroma/blob/main/chromadb/db/clickhouse.py#L31

i think the user provided ids (in the langchain case, if not provided are autogenerated) make the most sense to store LangChain side
