### ISSUE TITLE
[Feature Request] Fallback from one provider to another

### ISSUE THREAD

**Issue by TSPereira** [langchain-ai/langchain#4230]
### Feature request

Being able to pass fallback (already initialised) LLMs at the LLM initialisation and have the `generate` and `agenerate` methods using those fallbacks if the main LLM fails.

### Motivation

In production we often might need to fallback from one provider to another without raising errors and stopping the code in between. Having that logic embedded in the package would be great to avoid complex coding directly on services.

One possible issue I just found is when falling back from `OpenAI` to `AzureOpenAI`, where we still need to reset the variables in the `openai` module.

### Your contribution

I am currently hacking this by wrapping the LLMs in a custom class where I added a decorator to allow for this behaviour.
Notice that the `set_environment` is defined just on some other wrapping classes just for `OpenAI` and `AzureOpenAI`.

I am aware this is super hacky and I am sure there is a better way to do it!

wrapper cls:
```python
    class CustomLLM(class_to_inherit, BaseModel):
        fallback_llms: Sequence[Union[LLM_TYPE]] = Field(default_factory=list)

        def set_environment(self):
            with suppress(AttributeError):
                super().set_environment()

        @run_with_fallback_llms()
        def generate(self, prompt: List[str], **kwargs) -> LLMResult:
            return super().generate(prompt=prompt, **kwargs)

        @arun_with_fallback_llms()
        async def agenerate(self, prompt: List[str], **kwargs) -> LLMResult:
            return await super().agenerate(prompt=prompt, **kwargs)
```

decorators
```python
def run_with_fallback_llms():
    @decorator
    def wrapper(method, self, *args, **kwargs) -> Any:
        llms = [self] + list(self.fallback_llms or [])
        for i, llm in enumerate(llms):
            try:
                self.set_environment()
                method = getattr(super(type(llm), llm), method.__name__)
                return method(*args, **kwargs)
            except Exception as e:
                if i != len(llms) - 1:
                    logger.warning(f"LLM {llm.__class__.__qualname__} failed to run method {method.__name__}. "
                                   f"Retrying with next fallback LLM.")
                else:
                    logger.error(f"Last fallback LLM ({llm.__class__.__qualname__}) failed to "
                                 f"run method {method.__name__}.")
                    raise e

    return wrapper


def arun_with_fallback_llms():
    @decorator
    async def wrapper(method, self, *args, **kwargs) -> Any:
        llms = [self] + list(self.fallback_llms or [])
        for i, llm in enumerate(llms):
            try:
                self.set_environment()
                method = getattr(super(type(llm), llm), method.__name__)
                return await method(*args, **kwargs)
            except Exception as e:
                if i != len(llms) - 1:
                    logger.warning(f"LLM {llm.__class__.__qualname__} failed to run method {method.__name__}. "
                                   f"Retrying with next fallback LLM.")
                else:
                    logger.error(f"Last fallback LLM ({llm.__class__.__qualname__}) failed to "
                                 f"run method {method.__name__}.")
                    raise e

    return wrapper
```

example of `set_environment` for `OpenAI` LLM

```python
class CustomOpenAI(OpenAI):
    def set_environment(self) -> None:
        """Set the environment for the model."""
        openai.api_type = self.openai_api_type
        openai.api_base = self.openai_api_base
        openai.api_version = self.openai_api_version
        openai.api_key = self.openai_api_key
        if self.openai_organization:
            openai.organization = self.openai_organization
```

**Comment by adumont** [comment]
@TSPereira Hi, I'm interested in trying this mechanism to provide fallback from a main Azure OpenAI deployment to a second deployment. I'm not very familiar with custom classes and decorators though, and I can't make sense of your example.

For example, if I have two LLM, llm1 and llm2, both instances of langchain.chat_models.AzureChatOpenAI, how do I use your method in a simple LLMChain call, like this?

```
llm1 = AzureChatOpenAI(...)
llm2 = AzureChatOpenAI(...)

LLMChain(
        llm = XXXX,
        prompt=ChatPromptTemplate.from_template(query_classifier_prompt_template),
        verbose=False,
    )

```

Is there any repo where I could look how you use that?

**Comment by TSPereira** [comment]
> @TSPereira Hi, I'm interested in trying this mechanism to provide fallback from a main Azure OpenAI deployment to a second deployment. I'm not very familiar with custom classes and decorators though, and I can't make sense of your example.
> 
> For example, if I have two LLM, llm1 and llm2, both instances of langchain.chat_models.AzureChatOpenAI, how do I use your method in a simple LLMChain call, like this?
> 
> ```
> llm1 = AzureChatOpenAI(...)
> llm2 = AzureChatOpenAI(...)
> 
> LLMChain(
>         llm = XXXX,
>         prompt=ChatPromptTemplate.from_template(query_classifier_prompt_template),
>         verbose=False,
>     )
> ```
> 
> Is there any repo or some gist where I could look how you use that? If not, would you mind sharing a more elaborate example along those lines? Your way seems very interesting and I'm sure lots of people would benefit from it.

#
So we are not using them in Chains, although I think it should be able to make them work as "callbacks" in case of failure.
The way we are currently using this is that we created a factory to wrap Langchain LLMs at import time, where we add this fallbacks functionality. Then if a request fails it will try any fallbacks you have passed (of the same type of LLM, so you can't set a Completion LLM to be a fallback of a ChatLLM and viceversa, because the prompts are of different formats.


Here is most of our current implementation. The `FallbackErrorManager` you see inside is something we use to stack tracebacks so we can examine why requests might be failing. Implementation is exactly the same for async and sync versions.

What the code actually does is just:
- Validate the Fallbacks are valid for this LLM (at init time)
- Run a for loop with [self] + fallbacks
- If something fails the error_manager deals with stacking the exceptions (just so if all fail we can provide the full traceback)
- Try another llm in the list

I know there are a lot of things in this code that could be improved but we just needed something fast that would work with this fallback concept. 
The code is not in a public repo as it is close with other proprietary code. Sorry.

```python
def llm_factory(class_to_inherit: Type[T], factory_prefix: str = 'Custom') -> Type[T]:
    class CustomLLM(class_to_inherit, BaseModel):
        fallback_llms: Sequence[LLM_TYPE] = Field(default_factory=list)

        @validator('fallback_llms', pre=True, always=True, allow_reuse=True)
        def validate_fallback_llms(cls, v):
            main_type = BaseChatModel if issubclass(cls, BaseChatModel) else BaseLLM
            v = v or []
            if not isinstance(v, Sequence):
                v = [v]

            valid, invalid = [], []
            for llm in v:
                valid.append(llm) if issubclass(llm.__class__, main_type) else invalid.append(llm)

            if invalid:
                names = [llm_.__class__.__name__ for llm_ in invalid]
                warnings.warn(f"The following llms provided are invalid and were discarded: {names}.")

            return valid

        def generate(self, *args, **kwargs) -> LLMResult:
            method_name = 'generate'
            fallback_error_manager = FallbackErrorManager(method_name)

            llms = [self] + list(self.fallback_llms or [])  # type: ignore
            for i, llm in enumerate(llms):
                with fallback_error_manager(llm.__class__.__qualname__, is_last=i == len(llms) - 1):
                    method = getattr(super(type(llm), llm), method_name)
                    output = method(*args, **kwargs)

                    # add which llm was used to generate the output
                    if output.llm_output is None:
                        output.llm_output = {}

                    output.llm_output['llm'] = llm.__class__.__name__
                    return output

        async def agenerate(self, *args, **kwargs) -> LLMResult:
            method_name = 'agenerate'
            fallback_error_manager = FallbackErrorManager(method_name)

            llms = [self] + list(self.fallback_llms or [])  # type: ignore
            for i, llm in enumerate(llms):
                with fallback_error_manager(llm.__class__.__qualname__, is_last=i == len(llms) - 1):
                    method = getattr(super(type(llm), llm), method_name)
                    output = await method(*args, **kwargs)

                    # add which llm was used to generate the output
                    if output.llm_output is None:
                        output.llm_output = {}

                    output.llm_output['llm'] = llm.__class__.__name__
                    return output

    name = class_to_inherit.__qualname__

    CustomLLM.__qualname__ = f'{factory_prefix}{name}'
    CustomLLM.__name__ = f'{factory_prefix}{name}'
    return CustomLLM
```

**Comment by adumont** [comment]
Thanks @TSPereira . That looks too complex for me to grasp it and be able to do that in my code. Thanks anyway, I'm sure it can be useful for others anyway.

I have found this in LC documentation, so apparently they have added this kind of support into Langchain:

[Fallbacks | 🦜️🔗 Langchain](https://python.langchain.com/docs/guides/fallbacks)

**Comment by TSPereira** [comment]
That is wonderful, thanks for sharing that link @adumont!
Curious that they closed this feature request as "not planned" and then they did it 😅
