### ISSUE TITLE
Add more index methods to faiss.

### ISSUE THREAD

**Issue by PhilipMay** [langchain-ai/langchain#4232]
### Feature request

At the moment faiss is hard wired to `IndexFlatL2`.

See here:

https://github.com/hwchase17/langchain/blob/423f497168e3a8982a4cdc4155b15fbfaa089b38/langchain/vectorstores/faiss.py#L347

I would like to set other index methods. For example `IndexFlatIP`. This should be configurable.

Also see more index methods here: https://github.com/facebookresearch/faiss/wiki/Faiss-indexes

### Motivation

If I have dot product as the distance for my embedding I must change this...

### Your contribution

I can provide a PR if wanted.

**Comment by prathmeshranaut** [comment]
Can you use:

```python
from langchain import FAISS

index = fais.IndexFlatIP()
faiss = FAISS(embedding_function, index, docstore, index_to_docstore_id)
```

Then use the `add_texts ` and `add_embeddings` method.

**Comment by afdezt** [comment]
Yep, it is a pitty that the the FAISS LangChain utility for creating vectorestores is hardcoded to use L2 indexes... Especially considering how popular is FAISS as an open-source vectorstore and how relevant the inner product / cosine similarity is for text similarity (used by Azure OpenAI: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/understand-embeddings).

At least, cosine similarity (i.e. `IndexFlatIP ` with the already inplace `normalize_L2 ` flag set to True) would be a great addition to the `.from_text()` or ` .from_documents() ` wrappers, imho...

**Comment by AlexHuang2** [comment]
Cosine similarity would be great--in addition, I would also propose sliding window maximum cosine similarity as outlined in Section 3.2.1 (Sliding Window with Average Weighted Word Vectors) of [Sentence Similarity Techniques for Short vs Variable Length Text using Word Embeddings](https://www.cys.cic.ipn.mx/ojs/index.php/CyS/article/view/3273)--as I've found it to be empirically useful for retrieval when the prompt is very short but the relevant document is much longer.
