### ISSUE TITLE
Can’t use QA with sources chain together with a conversation agent

### ISSUE THREAD

**Issue by olaf-hoops** [langchain-ai/langchain#4235]
### Issue you'd like to raise.

Working with a conversation agent and the standard QA chain works fine but you can’t use the QA with sources chain in combination with an agent.

The QA with sources chain gives us  ['answer', 'sources'] which the ‚run‘ function of the ‚Chain‘ class can’t handle.

### Suggestion:

I think the ‚run‘ function in the ‚Chain‘ class needs to handle ‚Dict[str, Any]‘ instead of just ‚str‘ in order to use the QA with sources chain together with agents.

**Comment by xzhang8g** [comment]
I'm facing the same issue and still not about to find the solution.

**Comment by sahilkumarjsr21** [comment]
I'm also facing the same issue and still not able to find the solution.

**Comment by brerdem** [comment]
You need to write custom handlers and pass along to QA chain
