### ISSUE TITLE
Callbacks stopped outputting anything

### ISSUE THREAD

**Issue by vanillechai** [langchain-ai/langchain#4278]
### System Info

langchain==0.0.161
Python 3.11.2
MacOS 13.3

### Who can help?

@agola11

### Information

- [X] The official example notebooks/scripts
- [X] The official documentation

### Related Components

- [X] Callbacks/Tracing

### Reproduction

Model output is not seen any more. Up to langchain 0.0.152, I could see the output with multiple approaches.

This behaviour does not depend on the Llm - I've tried it with Llama, gpt4all and OpenAi.

Example code from https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html:
```python
from langchain.callbacks import StdOutCallbackHandler
from langchain.chains import LLMChain
from langchain.llms import OpenAI
from langchain.prompts import PromptTemplate

handler = StdOutCallbackHandler()
llm = OpenAI()
prompt = PromptTemplate.from_template("1 + {number} = ")

# First, let's explicitly set the StdOutCallbackHandler in `callbacks`
chain = LLMChain(llm=llm, prompt=prompt, callbacks=[handler])
chain.run(number=2)

# Then, let's use the `verbose` flag to achieve the same result
chain = LLMChain(llm=llm, prompt=prompt, verbose=True)
chain.run(number=2)

# Finally, let's use the request `callbacks` to achieve the same result
chain = LLMChain(llm=llm, prompt=prompt)
chain.run(number=2, callbacks=[handler])
```

Example output:
```
> Entering new LLMChain chain...
Prompt after formatting:
1 + 2 = 

> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:
1 + 2 = 

> Finished chain.


> Entering new LLMChain chain...
Prompt after formatting:
1 + 2 = 

> Finished chain.
```

### Expected behavior

I had expected to see the prompt + the model output printed 3 times, as it was with langchain 0.0.152:

    1 + 2 = 3

The output is returned from the chain, so everything (except writing the output) is working.

As of the current behaviour, I see no way to print the model output while it is generated. However, this feature is important to me (escpecially for longer outputs). Everything works as expected (i.e. model output printed while generated) if I downgrade langchain to 0.0.152 or 0.0.153, but fails to print anything using 0.0.154 or higher.

Strangely enough, the official documentation shows the same thing as I see on my local: Only the prompt is printed, but not the model output. Which makes me think if I may have misunderstood the usage of callbacks and the `verbose` flag?!

**Comment by liuyuchen0504** [comment]
```
from langchain.input import get_colored_text

class MyStdOutCallbackHandler(StdOutCallbackHandler):
    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
        texts = "\n".join([" ".join([l.text for l in lst]) for lst in response.generations])
        self.on_text(get_colored_text(texts, "green"))
```
try this

`StdOutCallbackHandler` not implement `on_llm_end` method

**Comment by robatwilliams** [comment]
I did it by adding a callback handler that extends StdOut/FileCallbackHandler/etc. and overriding `on_chain_end()` to print the outputs map.

**Comment by YesEnd99** [comment]
> ```
> from langchain.input import get_colored_text
> 
> class MyStdOutCallbackHandler(StdOutCallbackHandler):
>     def on_llm_end(self, response: LLMResult, **kwargs: Any) -> None:
>         texts = "\n".join([" ".join([l.text for l in lst]) for lst in response.generations])
>         self.on_text(get_colored_text(texts, "green"))
> ```
> 
> 
>     
>   
> 
> try this
> 
> 
> `StdOutCallbackHandler` not implement `on_llm_end` method

Hey @liuyuchen0504 , unfortunately this does not work, can you show how you implemented it in your chain/agent?

**Comment by YesEnd99** [comment]
> I did it by adding a callback handler that extends StdOut/FileCallbackHandler/etc. and overriding `on_chain_end()` to print the outputs map.

Hey @robatwilliams, can you share your solution? My whole project relies on this problem :(

**Comment by robatwilliams** [comment]
Hi. The solution I already described is the same as the previous poster's, just overriding a different method. I can't share code but it's very small, and as it sounds important for you, it's worth getting a good grip of how & why the solution works.

This is the class https://api.python.langchain.com/en/latest/_modules/langchain/callbacks/stdout.html#StdOutCallbackHandler

This is how to use callbacks https://python.langchain.com/docs/modules/callbacks/

**Comment by GCP20** [comment]
Do you have any solution @vanillechai ?

**Comment by davivc** [comment]
Hi @vanillechai, I don't know if this is to late but I've run into a similar problem where my callback for `on_llm_end` wasn't working as well. For me, what have workes was putting the callback handler into the model as well.

Try something like this:
```
from langchain_core.callbacks import CallbackManager

callback_handler = MyCustomCallbackHandler()

model = OpenAI(
    callback_manager=CallbackManager([callback_handler]),
)

chain = LLMChain(llm=llm, prompt=prompt, callbacks=[callback_handler ])
chain.run(number=2)
```
