### ISSUE TITLE
PALChain generates code that uses math and np libraries, but those aren't imported in PythonREPL

### ISSUE THREAD

**Issue by JavaFXpert** [langchain-ai/langchain#430]
The PALChain generates code that uses math and np libraries, but those aren't imported in PythonREPL. Here is the output of a recent run:
> Entering new PALChain chain...
def solution():
    """A particle moves so that it is at (3 sin (t/4), 3 cos (t/4)) at time t. Find the speed of the particle, measured in unit of distance per unit of time."""
    x = 3 * np.sin(t / 4)
    y = 3 * np.cos(t / 4)
    dx = 3 * np.cos(t / 4) / 4
    dy = -3 * np.sin(t / 4) / 4
    speed = np.sqrt(dx ** 2 + dy ** 2)
    result = speed
    return result

> Finished PALChain chain.

==== date/time: 2022-12-26 17:21:25.817242 ====
calc_gpt_pal math problem: A particle moves so that it is at (3 sin (t/4), 3 cos (t/4)) at time t. Find the speed of the particle, measured in unit of distance per unit of time.
calc_gpt_pal answer: name 'np' is not defined

**Comment by thepok** [comment]
maybe in the prompt tell gpt what libraries are available

**Comment by hwchase17** [comment]
or tell it that it needs to import any libraries it plans to use?

**Comment by hwchase17** [comment]
or an agent like thing, where if it errors you let it try again (so hopefully it learsn to import)? 

whats the example you're using to get this behavior? would love to play around

**Comment by JavaFXpert** [comment]
The example is in the OP: “ A particle moves so that it is at (3 sin (t/4), 3 cos (t/4)) at time t. Find the speed of the particle, measured in unit of distance per unit of time.Regards,James (Jim) WeaverOn Dec 26, 2022, at 6:12 PM, Harrison Chase ***@***.***> wrote:﻿
or an agent like thing, where if it errors you let it try again (so hopefully it learsn to import)?
whats the example you're using to get this behavior? would love to play around
