### ISSUE TITLE
import error ContextualCompressionRetriever

### ISSUE THREAD

**Issue by youminxue** [langchain-ai/langchain#4316]
### System Info

m1 mac

### Who can help?

@hwchase17 @agola11 @eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.retrievers import ContextualCompressionRetriever

NameError: name 'v_args' is not defined

### Expected behavior

![image](https://user-images.githubusercontent.com/3829455/236725738-18243030-52e6-45b5-b585-47a0ef554573.png)

**Comment by yetilfx** [comment]
i had the same problem

**Comment by ruyiluo** [comment]
> i had the same problem

+1

**Comment by tasansal** [comment]
This is because the `lark` dependency is not installed. If you look at where `v_args` is coming from it is from `lark`. It is an optional dependency for some reason. Installing it will fix your issue.

**Comment by jpdus** [comment]
+1.

The decorated func should probably be wrapped in some import/exception clause like for other optional libraries.

**Comment by tasansal** [comment]
Yea; it does have a try except but I think it has a bug. If it doesn't exist it just doesn't import it hence import error happens.

**Comment by eyurtsev** [comment]
cc @hwchase17 is this related to the fix you pushed yesterday if not, I'm happy to take a look let me know

**Comment by dev2049** [comment]
> cc @hwchase17 is this related to the fix you pushed yesterday if not, I'm happy to take a look let me know

think it's unrelated, taking look now
