### ISSUE TITLE
S3DirectoryLoader throws S3DirectoryLoader exception when prefix is a directory

### ISSUE THREAD

**Issue by markeste** [langchain-ai/langchain#4326]
### System Info

In langchain 0.0.161, if I call 
`S3DirectoryLoader(bucket, prefix)` where `prefix` is a "folder name" e.g. "documents/" you get a IsADirectoryError: [Errno 21] Is a directory exception.

It looks like the code is doing a filter on the bucket objects and the filter returns the files as well as the folder itself. The S3FileLoader tries to download the folder and that's what causes the exception

```
        s3 = boto3.resource("s3")
        bucket = s3.Bucket(self.bucket)
        docs = []
        for obj in bucket.objects.filter(Prefix=self.prefix):
            loader = S3FileLoader(self.bucket, obj.key)
            docs.extend(loader.load())
```

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Call S3DirectoryLoader(bucket, prefix) using a prefix that is a directory
2. See the exception being thrown 

### Expected behavior

The documents inside the folder should be loaded. The folder itself should be ignored.

**Comment by PawelFaron** [comment]
The filtering comes from boto3 library that langchain has anything to do with. 
You check check in your loop if the obs has size 0 or ends with /.

**Comment by markeste** [comment]
Please see the pull request I generated that mitigates this problem.
I can't check in the loop, since I'm calling S3DirectoryLoader and the loop is inside langchain code. If a folder prefix is provided, the loader will throw an exception.

**Comment by bensaine** [comment]
This issue is still relevant today

**Comment by VpkPrasanna** [comment]
Hi @hwchase17 this issue still exist
