### ISSUE TITLE
Langchain isn't verbose any more [run_manager gets dropped]

### ISSUE THREAD

**Issue by h3ndrik** [langchain-ai/langchain#4329]
### System Info

Python 3.11.2
Langchain 0.0.161
Debian GNU/Linux 12 (bookworm)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [X] Async

### Reproduction

How does verbosity work? I had my python scripts output verbose information, i mean all that green prompt-text when executing chains. All the constructors of LLMs and Chains have verbose=True in their constructors. But somewhat recently langchains behaviour changed and after doing a `pip install --upgrade langchain` my verbose output completely disappeared.
Do you have some sort of changelog or documentation on this? I didn't find any.
A small script still produces verbose output. But my project doesn't. I'm not sure what i'm doing differently.

EDIT: Maybe i should add that i'm doing async calls. And feeding it my own prompts from a PromptTemplate.from_template("..."). Could be related to any of that?!

EDIT2: Where does the green text even come from? I can see the chain calls a StdoutCallbackHandler. This fires and prints "Entering new ConversationChain chain..." as it's supposed to. But how do i debug the missing green text after that? It's not in the on_chain_start()...

### Expected behavior

Verbose output is produced when setting verbose=True

**Comment by PawelFaron** [comment]
Please provide example code for reproduction.

**Comment by h3ndrik** [comment]
Unfortunately i can't just rip it out of the project. Isn't there some documentation on how verbose is supposed to work or what to do with langchain.verbose? Or a changelog to make it easier for me to start bisecting somewhere, when langchain's behaviour changed?

**Comment by h3ndrik** [comment]
Okay. The issue seems to be related to the async code. If i call chain.arun() the verbose output isn't there.

@PawelFaron here's some example code:

```
import asyncio

from fakellm import FakeListLLM
from langchain import LLMChain
from langchain.prompts import PromptTemplate


async def main():
    responses=[
        "foo",
        "bar"
    ]
    llm = FakeListLLM(responses=responses)

    prompt_summary = PromptTemplate.from_template(
    """Instruction: Write a concise summary of the following:
    {text}

    ### Response:
    """
    )

    chain = LLMChain(llm=llm, prompt=prompt_summary, verbose=True)

    chain.run("hello sync")

    await chain.arun("hello async")

asyncio.run(main())
```

The fake llm in langchain is also missing an _acall method. i just copy-pasted the _call to make it work:

```
"""Fake LLM wrapper for testing purposes."""
import asyncio
from typing import Any, List, Mapping, Optional

from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM


class FakeListLLM(LLM):
    """Fake LLM wrapper for testing purposes."""

    responses: List
    i: int = 0

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "fake-list"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
    ) -> str:
        """First try to lookup in queries, else return 'foo' or 'bar'."""
        response = self.responses[self.i]
        self.i += 1
        return response

    async def _acall(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
    ) -> str:
        """First try to lookup in queries, else return 'foo' or 'bar'."""
        response = self.responses[self.i]
        self.i += 1
        return response

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {}
```

The call to chain.run() produces verbose output.
The call to chain.arun() doesn't.

**Comment by blob42** [comment]
I think this is related to the fix to #4130 where `run_manager` param is not passed.

**Comment by h3ndrik** [comment]
@blob42 Thank you. I had a look at the LLMChain and also there, the run_manager is passed to other functions inside generate() but not inside agenerate()

Happened in PR #3256 I'm not sure if deliberate, PR merged, 45 commits, 209 files changed, "No description provided."

**Comment by jppaolim** [comment]
HI  I do the following and it doesn't verbose, any way to see what happens under the hood other than using promptlayer ? 


```
PROMPT = some custom prompt 

chain_type_kwargs = {"prompt": PROMPT}

qa = RetrievalQA.from_chain_type(llm=OpenAI(openai_api_key=OPENAI_KEY, temperature=0., max_tokens=1024, verbose=True), chain_type="stuff", retriever=querybase, return_source_documents=True, verbose = True, chain_type_kwargs=chain_type_kwargs)

qa.combine_documents_chain.verbose = True
...
query = input("\nEnter a query: ")
res = qa(query)    
print(res)
```

**Comment by HiddenMachine3** [comment]
This still happens in the latest version of langchain, when i try to use SelfQueryRetriever : 
```python
retriever = SelfQueryRetriever.from_llm(
    llm=llm,
    vectorstore=vectorstore,
    document_contents=document_content_description,
    metadata_field_info=metadata_field_info,
    verbose=True
)
retriever.get_relevant_documents(query)
```
It doesn't show any verbose output

**Comment by aasthavar** [comment]
+1 on the issue with verbose=True not helping with printing the Query generated.

Although line 175 in [code](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/retrievers/self_query/base.py#L175) clearly shows it should output the query generated, I am not entirely sure how to fix it.

As I wanted to quickly see query as well as what's happening under the hood, below helped - 

```
from langchain.callbacks.tracers import ConsoleCallbackHandler

handler = ConsoleCallbackHandler()
docs = self_query_retriever.get_relevant_documents(
        query =  "top 5 best selling sofas for living room below 500k", 
        callbacks=[handler]
)
```

**Comment by HiddenMachine3** [comment]
@aasthavar You can temporarily fix it by changing the actual library code to not check for verbose=True flag, and directly show the debug statement instead. Also, check if you python logging level is set to INFO first

**Comment by Mizuki8783** [comment]
@HiddenMachine3 I was having the same issue with SelfQueryRetriever. Much appreciate your solution

**Comment by justi** [comment]
For different interface (used by not-deprecated method invoke) it should looks like that:
```
self_query_retriever.invoke(
    query,
    config={"callbacks": [handler]}
)
```

**Comment by swarmdog** [comment]
set_verbose does not work as described in the langchain docs: https://python.langchain.com/docs/how_to/debugging/

If you use set_verbose by itself, there is no output.  If you use set_debug and set_verbose you get some output.
