### ISSUE TITLE
Empty API token in HuggingFaceEndpoint unless explicitly passed to Constructor

### ISSUE THREAD

**Issue by gil-frenkel-marpai** [langchain-ai/langchain#4334]
### System Info

System: Linux
Kernel: Linux version 5.15.0-1026-aws (buildd@lcy02-amd64-088) ( gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 )
Python version: 3.8.16
LangChain version: 0.0.157

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Upon constructing the HuggingFaceEndpoint, when the API token is set as an environment variable (not passing to the constructor), the attribute ```huggingface_api_token``` will always be empty, causing a missing token in the request headers:

```
from dotenv import load_dotenv
load_dotenv()

llm = HuggingFaceEndpoint(
    endpoint_url="togethercomputer/RedPajama-INCITE-Instruct-7B-v0.1",
    task="text-generation"
)

print(llm.huggingfacehub_api_token)
print("What is the capital of France?")

```

Output:

```
None
Traceback (most recent call last):
  File "research/red_pajama.py", line 58, in <module>
    print(llm("What is the capital of France?"))
  File "/home/ubuntu/miniconda3/envs/marpai_llm/lib/python3.8/site-packages/langchain/llms/base.py", line 281, in __call__
    self.generate([prompt], stop=stop, callbacks=callbacks)
  File "/home/ubuntu/miniconda3/envs/marpai_llm/lib/python3.8/site-packages/langchain/llms/base.py", line 176, in generate
    raise e
  File "/home/ubuntu/miniconda3/envs/marpai_llm/lib/python3.8/site-packages/langchain/llms/base.py", line 170, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "/home/ubuntu/miniconda3/envs/marpai_llm/lib/python3.8/site-packages/langchain/llms/base.py", line 377, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "/home/ubuntu/miniconda3/envs/marpai_llm/lib/python3.8/site-packages/langchain/llms/huggingface_endpoint.py", line 133, in _call
    raise ValueError(
ValueError: Error raised by inference API: Authorization header is correct, but the token seems invalid
```

ValueError exception raised here:
[https://github.com/hwchase17/langchain/blob/65c95f9fb2b86cf3281f2f3939b37e71f048f741/langchain/llms/huggingface_endpoint.py#L118](https://github.com/hwchase17/langchain/blob/65c95f9fb2b86cf3281f2f3939b37e71f048f741/langchain/llms/huggingface_endpoint.py#L118)

### Expected behavior

huggingFaceEndpoint should send a valid POST request to inference API.

**Comment by Smartking1** [comment]
How can I fix this issue

**Comment by erlebach** [comment]
Any news on this issue? I work on a Mac with M2 check and have a similar error. The last line of my stack trace is: 
```
Error raised by inference API: Authorization header is correct, but the token seems invalid
```

**Comment by AnujaDilrukshiHerath** [comment]
I work on a Mac with M1 check and have a similar error i'm getting. The last line of my stack trace is:

Error raised by inference API: Authorization header is correct, but the token seems invalid

**Comment by devshi3** [comment]
this issue still prevails.
