### ISSUE TITLE
map_reduce summarizer errors when using LLM with smaller context window

### ISSUE THREAD

**Issue by randywreed** [langchain-ai/langchain#434]
I tried to do a map-reduce summary using curie instead a davinci.  
Code:  
```
llm=OpenAI(model_name="text-curie-001",temperature=0)
summary_chain = load_summarize_chain(llm, chain_type="map_reduce")
summary=summary_chain.run(docs)
```
Error:  
```
Token indices sequence length is longer than the specified maximum sequence length for this model (2741 > 1024). Running this sequence through the model will result in indexing errors
---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-72-4ced0b77973e>](https://localhost:8080/#) in <module>
----> 1 summary=summary_chain.run(docs)

16 frames
[/usr/local/lib/python3.8/dist-packages/openai/api_requestor.py](https://localhost:8080/#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    427         stream_error = stream and "error" in resp.data
    428         if stream_error or not 200 <= rcode < 300:
--> 429             raise self.handle_error_response(
    430                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    431             )

InvalidRequestError: This model's maximum context length is 2049 tokens, however you requested 2997 tokens (2741 in your prompt; 256 for the completion). Please reduce your prompt; or completion length.
```
NB: Error doesn't occur if I use "refine" instead (though the summary does something weird and doesn't summarize the whole document)

**Comment by hwchase17** [comment]
you should specify the max document to construct with something like `summary_chain.run(input_documents=docs, token_max=2000)` or so

does this fix it?

**Comment by randywreed** [comment]
Yes, the error doesn't occur if I add the token_max parameter.

**Comment by thepok** [comment]
you should be able to use -1. that automatically uses max context size

**Comment by vertinski** [comment]
Why this error on davinci-003 tho? API access allows for 2048 token context.

`Token indices sequence length is longer than the specified maximum sequence length for this model (1201 > 1024). Running this sequence through the model will result in indexing errors`

**Comment by nqbao** [comment]
I have the same problem with `load_qa_chain`

```
chain = load_qa_chain(OpenAI(temperature=0), chain_type="map_reduce")
# chain({"input_documents": docs, "question": query,})
chain.run(input_documents=docs, question=query, token_max=2000)
```

Where does the limit come from?

**Comment by happysalada** [comment]
I get the same error from another chain
```
chain = VectorDBQAWithSourcesChain.from_llm(llm=OpenAI(temperature=0), vectorstore=store)
result = chain({"question": "コースの一位になりそうな馬は？"})
```

I thought at first I might have to change something because I'm using japanese maybe ? Also I couldn't find any token_max parameter in the query I'm giving. Not sure what I forgot.

**Comment by happysalada** [comment]
Thanks a lot! There is probably somewhere they set a template prompt, do you know where that is ?

**Comment by yunyu** [comment]
I had to explicitly call `MapReduceDocumentsChain.combine_docs` for this to work. Also the async version `acombine_docs` doesn't work – needed to wrap it in `asyncio.run_in_thread` to simulate async.

**Comment by adumont** [comment]
When I do

```
chat_model = AzureChatOpenAI(
    openai_api_base=openai_instance["api_base"],
    openai_api_version=openai_instance["api_version"],
    deployment_name=chat_model_deployment,
    openai_api_key=openai_instance["api_key"],
    openai_api_type = openai_instance["api_type"],
    temperature=0.5,
    verbose=True,
    max_tokens=2048,
)

chain = load_summarize_chain(
    llm=chat_model,
    chain_type="map_reduce",
    return_intermediate_steps=True,
)

res = chain({"input_documents": docs}, token_max=2000)
```

I get unexpected keyword argument 'token_max':
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[31], line 18
      1 chat_model = AzureChatOpenAI(
      2     openai_api_base=openai_instance["api_base"],
      3     openai_api_version=openai_instance["api_version"],
   (...)
      9     max_tokens=2048,
     10 )
     12 chain = load_summarize_chain(
     13     llm=chat_model,
     14     chain_type="map_reduce",
     15     return_intermediate_steps=True,
     16 )
---> 18 res = chain({"input_documents": docs}, token_max=2000)

TypeError: __call__() got an unexpected keyword argument 'token_max'
```

**Comment by ShantanuNair** [comment]
I want to clear something up which I think a lot of people are confusing - token_max vs max_token.

- `token_max`: The threshold token limit which the maps step need to drop below so that the reduce step can run on them. Think of it as the context size the reduce prompt allows. If set to 4k, that means your maps steps should together be no more than 4k tokens for proceeding to reduce step. 
- `max_tokens`: This is a model parameter that tells it how many tokens it can generate.

**Comment by ShantanuNair** [comment]
If you want to be able to set `token_max` until then here is how you can do that :) I see this hasn't been suggested elsewhere and no one else has trawled through the chain's code to figure out how to pass in the kwargs for token_max so here it is:

```
res = await chain(inputs={'input_documents': texts, 'token_max': 12000}, return_only_outputs=True)
```
