### ISSUE TITLE
Materialized Views not accessible 

### ISSUE THREAD

**Issue by BenjiWilson** [langchain-ai/langchain#4349]
### System Info

When specifying a materialized view in include_tables, the following error occurs:

include_tables {'table_name'} not found in database

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

include_tables=['table1', 'table2']

db = SQLDatabase.from_uri("postgresql://xxx:xxx@xxx:5432/xxx", include_tables=include_tables)

### Expected behavior

Materialized views should be accessible.

**Comment by kittenkill** [comment]
Hi!.

I noticed this as well.
It looks like there [is a change](https://docs.sqlalchemy.org/en/20/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_view_names) in the sql-alchemy

```Changed in version 2.0: For those dialects that previously included the names of materialized views in this list (currently PostgreSQL), this method no longer returns the names of materialized views. the [Inspector.get_materialized_view_names()](https://docs.sqlalchemy.org/en/20/core/reflection.html#sqlalchemy.engine.reflection.Inspector.get_materialized_view_names)method should be used instead.```

So maybe near [here](https://github.com/hwchase17/langchain/blob/master/langchain/sql_database.py#L55), one could make a change like this:


```diff
diff --git a/langchain/sql_database.py b/langchain/sql_database.py
index fc0a5098..f193cf0c 100644
--- a/langchain/sql_database.py
+++ b/langchain/sql_database.py
@@ -53,6 +53,7 @@ class SQLDatabase:
         self._all_tables = set(
             self._inspector.get_table_names(schema=schema)
             + (self._inspector.get_view_names(schema=schema) if view_support else [])
+            + (self._inspector.get_materialized_view_names(schema=schema) if view_support else [])
         )

         self._include_tables = set(include_tables) if include_tables else set()
```

**Comment by CadisERaizel** [comment]
Hi, 

I faced the same issue initially, it seems you need to send a flag view_support as True (defaults to False) , if you want it to check for materialized views. 

<img width="758" alt="Screenshot 2023-07-17 at 11 17 43 AM" src="https://github.com/hwchase17/langchain/assets/22761955/73c9cafb-a1ca-4413-ac70-031a3d2deec9">

Try adding one more parameter (view_support = True) and see if this solves the issue in your case as it did in mine.

`db = SQLDatabase.from_uri(
"postgresql://xxx:xxx@xxx:5432/xxx",` include_tables=include_tables, view_support = True)`

**Comment by micaelarg** [comment]
Hi, 

I have a similar issue. 'one_all' is a materialized view. When I run: 
db = SQLDatabase(engine, schema='one',  include_tables=['one_all'], view_support = True)
I get no errors, yet it actually brings all the tables, and even excludes the materialized view one_all, when I am actually telling to bring only the materialized view. Any suggestion¿?

**Comment by micaelarg** [comment]
anyone here?

**Comment by jyoti194** [comment]
Hi @micaelarg ,
in db = SQLDatabase(engine, schema='one', include_tables=['one_all'], view_support = True)
what is the schema= 'one' ? and are we giving the view name in include_tables?

**Comment by Bod1** [comment]
psycopg2.errors.UndefinedTable

**Comment by Ayhm-Tenderd** [comment]
Any changes this will be merged anytime soon?
