### ISSUE TITLE
Azure OpenAIEmbeddings(chunk_size=1) is changing the API version of the openai

### ISSUE THREAD

**Issue by geg00** [langchain-ai/langchain#4352]
### System Info

(.venv) C:\Users\hbb9279\OpenAI\Files\10K\2019>python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

langchain-0.0.162

import os
import openai
openai.api_type = "azure"
openai.api_base = "https://<<deployment_id>>.openai.azure.com/"
openai.api_version = "2023-03-15-preview"

vectorstore = FAISS.from_documents(documents=documents, embedding = emb )
emb = OpenAIEmbeddings(chunk_size=1)

openai.api_base, openai.api_version
('https://<<deployment_id>>.openai.azure.com/', '2022-12-01')

Then when you try to use the functionality, it will fail with resource not found. 

because the api_version with 2022-12-01 doesn't include the GPT-35-Turbo and GPT-4

😐

### Who can help?

@hwchase17 @vowelparrot @eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import os
import openai
openai.api_type = "azure"
openai.api_version = "2023-03-15-preview"
emb = OpenAIEmbeddings(chunk_size=1)

openai.api_version
>> '2022-12-01'

### Expected behavior

The expectation is to keep the environmental variable the same way that I defined them without modifying them.

**Comment by floleuerer** [comment]
Did you try setting the environment variables instead of `openai.api_version`?

```
OPENAI_API_TYPE=azure
OPENAI_API_VERSION=2023-03-15-preview
OPENAI_API_BASE=xxx
OPENAI_API_KEY=xxx
```

**Comment by geg00** [comment]
> Did you try setting the environment variables instead of `openai.api_version`?
> 
> ```
> OPENAI_API_TYPE=azure
> OPENAI_API_VERSION=2023-03-15-preview
> OPENAI_API_BASE=xxx
> OPENAI_API_KEY=xxx
> ```

Yes those are set but OpenAiEmbeddings is changing the openai settings and that’s wrong

Langchain is changing a user defined setting 
The function shouldn’t do that

**Comment by floleuerer** [comment]
Could you remove `import openai`? I had trouble when importing the openai package directly in the past.

**Comment by geg00** [comment]
Please go ahead and close it

**Comment by geg00** [comment]
close it
