### ISSUE TITLE
Could not use load_summarize_chain with Azure API.

### ISSUE THREAD

**Issue by Mgz-97** [langchain-ai/langchain#4384]
### System Info

chain = load_summarize_chain(llm, chain_type="refine", verbose=True)
when llm use AzureOpenAI， it will fail to send request, and will get this error

  File "C:\Users\\.conda\envs\captionSummary\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\\.conda\envs\captionSummary\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\\.conda\envs\captionSummary\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found

### Who can help?

@hwchase17 @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

chain = load_summarize_chain(llm, chain_type="refine", verbose=True)
when llm use AzureOpenAI， it will fail to send request, and will get this error

### Expected behavior

Work well with the azure API call.

**Comment by qianzehao0819** [comment]
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
os.environ["OPENAI_API_BASE"] = "https://xxxx.openai.azure.com"
os.environ["OPENAI_API_KEY"] = "xxxxxxxx"

openai.api_type = "azure"
openai.api_base = "https://xxxx.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = "xxxxx"
 llm = AzureChatOpenAI(deployment_name= "your_deployment_name")

**Comment by qianzehao0819** [comment]
> @qianzehao0819 Thanks for the reply, load_summarize_chain could not use the AzureChatOpenAI...

it works for me,you can try

**Comment by Mgz-97** [comment]
thanks!

**Comment by aldwnesx** [comment]
> AzureChatOpenAI

I keep getting 404 error.
If I use `AzureOpenAI`, it works but I get ` OpenAIChat currently only supports single prompt, got....`

**Comment by aldwnesx** [comment]
> os.environ["OPENAI_API_TYPE"] = "azure" os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview" os.environ["OPENAI_API_BASE"] = "https://xxxx.openai.azure.com" os.environ["OPENAI_API_KEY"] = "xxxxxxxx"
> 
> openai.api_type = "azure" openai.api_base = "https://xxxx.openai.azure.com/" openai.api_version = "2023-03-15-preview" openai.api_key = "xxxxx" llm = AzureChatOpenAI(deployment_name= "your_deployment_name")

AzureChatOpenAI

I keep getting 404 error.
If I use AzureOpenAI, it works but I get  OpenAIChat currently only supports single prompt, got....
