### ISSUE TITLE
Weaviate Vectorstore not initialized with Azure OpenAI embeddings

### ISSUE THREAD

**Issue by sudhanshu746** [langchain-ai/langchain#4395]
### System Info

Weaviate vectorstore not getting initialized with Azure OpenAI embeddings.

Code:
```
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Weaviate
from langchain.embeddings.base import Embeddings



auth_config = weaviate.auth.AuthApiKey(api_key=WEAVIATE_API)
client = weaviate.Client(url=WEAVIATE_HOST, auth_client_secret=auth_config)
embeddings_model: Embeddings = OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1)
vectorstore = Weaviate(client=client, index_name="chatbot_dev", text_key="content", embedding=embeddings_model)
```
Error:
```
TypeError: Weaviate.__init__() got an unexpected keyword argument 'embedding'
```

Also, tried to initialize with Weaviate.from_texts() 

```
from langchain.vectorstores import Weaviate
qa = Weaviate.from_texts(texts=['here is a sample'], embedding=embeddings_model, index_name="content", weaviate_url="your Weaviate URL")
```
Error:
```
NotImplementedError: weaviate does not currently support `from_texts`
```

### Who can help?

@ruanwz @vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Weaviate
from langchain.embeddings.base import Embeddings



auth_config = weaviate.auth.AuthApiKey(api_key=WEAVIATE_API)
client = weaviate.Client(url=WEAVIATE_HOST, auth_client_secret=auth_config)
embeddings_model: Embeddings = OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1)
vectorstore = Weaviate(client=client, index_name="chatbot_dev", text_key="content", embedding=embeddings_model)
```

### Expected behavior

Weaviate vector store library should be generic to support multiple use cases.

**Comment by parth-patel97** [comment]
Same error I am getting.

**Comment by parth-patel97** [comment]
I am thinking that can I use Weaviate implementation direct from weaviate package without using langchain.vectorstores , anyone have any comment on this ?

If I got success I will post it here the approach.

**Comment by yassinsws** [comment]
is this solved already ? I am getting the same error !

**Comment by sudhanshu746** [comment]
@yassinsws, you can do Weaviate implementation directly from the Weaviate package without using langchain.vectorstores. if you need I can provide working code.

**Comment by yassinsws** [comment]
Yes that would be helpful thank you
