### ISSUE TITLE
[Feature Request] update and delete index operation on Weaviate vectorstore  

### ISSUE THREAD

**Issue by sudhanshu746** [langchain-ai/langchain#4399]
### Feature request

Currently, Weaviate vectorstore doesn't provide option for updation of vector embeddings on existing index and deletion of index.

 

### Motivation

This feature request is related to an experiment project for which we need CRUD operations on Weaviate vectorstore.

### Your contribution

I can provide my contribution if no one is currently working on this request.

**Comment by marcesengel** [comment]
Not sure if I should write this or if it's considered spam, but I'd love to have this included in the library as well.

**Comment by sudhanshu746** [comment]
@Ryangr0  Are you or someone else working on this issue?  
or, do you want my contribution to this feature?
