### ISSUE TITLE
Issue: <Model google/flan-t5-xxl does not exist>

### ISSUE THREAD

**Issue by phdykd** [langchain-ai/langchain#4404]
### Issue you'd like to raise.

I have this code running smoothly before,

llm=HuggingFaceHub(repo_id="google/flan-t5-xxl", model_kwargs={"temperature":0.7, "max_length":512}).

Bu today, it says "HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/google/flan-t5-xxl (Request ID: Root=1-645a5b93-4a130f591edbbc965dc50e6b)

Sorry, we can't find the page you are looking for.".

Any idea?

**Comment by hp0404** [comment]
Your error was likely related to the technical issues that the Hugging Face Hub experienced today; see [here](https://twitter.com/julien_c/status/1656001632612622341)
