### ISSUE TITLE
I wonder for embedding, we can allow passing other than page_content for embedding service

### ISSUE THREAD

**Issue by QingsongYao** [langchain-ai/langchain#4425]
### Feature request

I like to add more metadata, such as keywords, highlights, questions to be answered together when building an embedding for a document, other than only page_content,  I wonder how can it be achieved today? 

### Motivation

allow to annotate source document to better embedding. but without changing the document.

### Your contribution

n/a

**Comment by 9akashnp8** [comment]
You can pass those in the `metadata` attribute.

`Document(page_content=comment, metadata={"index": index, "keywords": "hello, world"})`

**Comment by QingsongYao** [comment]
Will the metadata field be used for embedding?
