### ISSUE TITLE
Add support for regular expression in CharacterTextSplitter

### ISSUE THREAD

**Issue by frequena** [langchain-ai/langchain#4429]
### Feature request

The current version of CharacterTextSplitter does not provide support for a regular expression in the separator argument.

### Motivation

Many documents can be split by slightly different patterns that can be handled by regular expression

### Your contribution

-

**Comment by frequena** [comment]
Thanks for the quick reply! For instance, a document has the tag "Page X" in the footnote and the word "Page" is commonly also referenced in the body text. In that case, "Page" cannot be used as a separator.

**Comment by 9akashnp8** [comment]
okay, understood. 

Below should've been possible but we might have issues in the _merge_split method as it takes the separator and uses it to join into bigger chunks.

Eg:
```
import re
from langchain.text_splitter import TextSplitter

class RegexTextSplitter(TextSplitter):

    def __init__(self, pattern: str, **kwargs):
        super().__init__(**kwargs)
        self.pattern = pattern

    def split_text(self, text: str):
         if self.pattern:
            splits = re.split(self.pattern, text)
        else:
            splits = list(text)
        return self._merge_splits(splits, self.pattern)
```

**Comment by felixthekraut** [comment]
The offered solution does not work. While it doesn't fail, the _merge_splits method is unable to handle regex correctly.

```
    splitter = RegexTextSplitter("\d", chunk_size=30,chunk_overlap=0)
    splits = splitter.split_text("hello world 123 asdf")
    print(splits)

    splitter = RegexTextSplitter("\d+", chunk_size=30,chunk_overlap=0)
    splits = splitter.split_text("hello world 123 asdf")
    print(splits)

    splitter = RegexTextSplitter("[12]", chunk_size=30,chunk_overlap=0)
    splits = splitter.split_text("hello world 123 asdf")
    print(splits)
```

```
['hello world \\d\\d\\d asdf']
['hello world \\d+ asdf']
['hello world [12][12]3 asdf']
```
