### ISSUE TITLE
Run locally google flan t5 large issue with local embeddings

### ISSUE THREAD

**Issue by axeljeremy7** [langchain-ai/langchain#4438]
### System Info

langchainversion: 0.0.163
llama_index version: 0.6.4
PyTorch version: 2.0.0+cu118
Transformers version: 4.30.0.dev0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [x] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run: 

```python

from llama_index import LLMPredictor, PromptHelper, ServiceContext, SimpleDirectoryReader, GPTVectorStoreIndex, GPTListIndex

model_id = 'google/flan-t5-large'
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
pipe = pipeline(
    "text2text-generation",
    model=model, 
    tokenizer=tokenizer, 
    max_length=512
)

local_llm_g_flan_t5_large = HuggingFacePipeline(pipeline=pipe)
print(local_llm_g_flan_t5_large('What is the capital of Germany? '))
print(local_llm_g_flan_t5_large('What is the capital of Spain? '))
print(local_llm_g_flan_t5_large('What is the capital of Canada? '))
# all is working untill here

from llama_index import GPTListIndex, SimpleDirectoryReader, GPTVectorStoreIndex
from langchain.embeddings import SentenceTransformerEmbeddings 
from llama_index import LangchainEmbedding, ServiceContext

directory_path_ = '/content/dir'
 documents = SimpleDirectoryReader(directory_path_).load_data()

llm_predictor = LLMPredictor(llm=local_llm_g_flan_t5_large)
embed_model = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
service_context = ServiceContext.from_defaults(embed_model=embed_model, llm_predictor=llm_predictor)
index = GPTListIndex.from_documents(documents, service_context=service_context)

```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-7d7e68b85aa2> in <cell line: 1>()
----> 1 index = GPTListIndex.from_documents(documents, service_context=service_context)

5 frames
/usr/local/lib/python3.10/dist-packages/llama_index/token_counter/token_counter.py in wrapper_logic(_self)
     48 
     49             start_token_ct = llm_predictor.total_tokens_used
---> 50             start_embed_token_ct = embed_model.total_tokens_used
     51 
     52             yield

AttributeError: 'HuggingFaceEmbeddings' object has no attribute 'total_tokens_used'
```

### Expected behavior

if try by using huggiface hub , it works fine but locally the same it does not work, my idea is to do context learning locally using this model

**Comment by jbottum** [comment]
I found this issue to be in this line:
service_context = ServiceContext.from_defaults(embed_model=embed_model, llm_predictor=llm_predictor)

which I modified to this (and it ran): 
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

The modification removes the embed_model reference, which was generating a failure message. This parameter appears not be required for these models and removing it enables the program to run successfully.

For reference here is the error message with the original code

Traceback (most recent call last):
  File "/Users/xxxx/t5pat/t5pat.py", line 32, in <module>
    service_context = ServiceContext.from_defaults(embed_model=embed_model, llm_predictor=llm_predictor)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxxx/t5/.env/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 147, in from_defaults
    embed_model.callback_manager = callback_manager
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "HuggingFaceEmbeddings" object has no field "callback_manager"
which we traced to this program and found this NOTE that states "the embed_model is not needed for all indices". Based on this note, we removed it from the original call and the code executed to completion.

/Users/xxxx/t5/.env/lib/python3.11/site-packages/llama_index/indices/service_context.py

         # NOTE: the embed_model isn't used in all indices
146         embed_model = embed_model or OpenAIEmbedding()
147         embed_model.callback_manager = callback_manager
