### ISSUE TITLE
Issue: Multi input tools do not work consistently with conversational agent

### ISSUE THREAD

**Issue by radsrigari** [langchain-ai/langchain#4439]
### Issue you'd like to raise.

We are unable to make multi input tools work consistently with conversational agent.

Here is the scenario: User asks a question. Based on the question the agent needs to extract two inputs from the question and route it to the right tool for answer. If the user has not provided the two inputs, the agent needs to ask the user for those inputs, before using the tool. Finally it also needs to remember the inputs and not ask for those inputs again in subsequent messages from the user. I've tried various methods ranging from structured tool, structured agent, even regex matching, and nothing is producing consistent results.

Could anyone please suggest any other ideas to solve this? Thank You!

**Comment by ccwanghui** [comment]
Hello, I come from China and I also want to do the same thing. Have you achieved it

**Comment by radsrigari** [comment]
Hi, We solved it temporarily, by using a chain of LLMs and business logic. We have [1] Main chat LLM, [2] Input checking tool, [3] Single input tool. Here the main chat LLM, passes it to different input checking tools based on the question, this input checking tool has business logic to check state variables. If the state variable is empty, then it calls the specific single input tool to get the variable, and store it in state. There are prompts for [1], and [3]....and then if else business logic in [2]. Hope that helps.
