### ISSUE TITLE
Import error from official example (documentation)

### ISSUE THREAD

**Issue by ugoborghetti** [langchain-ai/langchain#4448]
### System Info

Latest version of langchain.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Why if I try to follow this example here:

https://python.langchain.com/en/latest/modules/ agents/plan_and_execute.html

I get an import error!
ImportError: cannot import name
'PlanAndExecute' from 'langchain.agents'
1 have the latest langchain version 0.0.163 and tried to uninstall and reinstall but the error remains.
Thanks!

### Expected behavior

Like in the documentation

**Comment by 9akashnp8** [comment]
I believe, the pr has for that particular feature has not been merged yet:  #4422

**Comment by 9akashnp8** [comment]
The pr for this new feature was merged only 7 hours ago, I believe it will be available in next release. See: #4422
