### ISSUE TITLE
`SmartGPT` workflow

### ISSUE THREAD

**Issue by leo-gan** [langchain-ai/langchain#4463]
### Feature request

@hwchase17   Can we implement this [**SmartGPT** workflow](https://youtu.be/wVzuvf9D9BU)? 
Probably, it is also implemented but I didn't find it.
Thi method looks like something simple but very effective.

### Motivation

Improving the quality of the prompts and the resulting generation quality.

### Your contribution

I can try to implement it but need direction.

**Comment by kochmaxence** [comment]
> I can try to implement it but need direction.

You can have a look in `experimental` to get started.

Mainly the new (from today) [PlanAndExecute](https://github.com/hwchase17/langchain/tree/9231143f91863ffbe0542bc69a90b723a40e165d/langchain/experimental/plan_and_execute) and then the [AutoGPT implementation](https://github.com/hwchase17/langchain/tree/9231143f91863ffbe0542bc69a90b723a40e165d/langchain/experimental/autonomous_agents/autogpt) and [BabyAGI implementation](https://github.com/hwchase17/langchain/tree/9231143f91863ffbe0542bc69a90b723a40e165d/langchain/experimental/autonomous_agents/baby_agi).

This is very similar.

**Comment by UmerHA** [comment]
Hey @leo-gan! Have you started already? If not, I'd also like to do it, this sounds interesting :)

I recently implemented Reflexion, so have a lot of xp in LangChain agents now.

If you want, message me on Discord and we can collaborate: RicChilligerDude#7589

**Comment by leo-gan** [comment]
> Hey @leo-gan! Have you started already? If not, I'd also like to do it, this sounds interesting :)
> 
> I recently implemented Reflexion, so have a lot of xp in LangChain agents now.
> 
> If you want, message me on Discord and we can collaborate: RicChilligerDude#7589

Hey @UmerHA Feel free to implement it.
