### ISSUE TITLE
Return Intermediate Steps for Plan and Execute

### ISSUE THREAD

**Issue by davidmcomfort** [langchain-ai/langchain#4485]
### System Info

LangChain version 0.0.164

### Who can help?

@hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Add `return_intermediate_steps=True ` to 
```
agent = PlanAndExecute(
  planner=planner, 
  executer=executor, 
  verbose=True,
  max_iterations=10)
```

### Expected behavior

Be able `print(response["intermediate_steps"])` to get intermediate steps. 

The Plan and Execute agent appears to work really well, but there is a lot of useful information in the intermediate steps, which can be utilized by other agents. Can the Plan and Execute agent output intermediate steps?

**Comment by maparla-cognizant** [comment]
Is there any news?
