### ISSUE TITLE
[Urgent] Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by ruai0511** [langchain-ai/langchain#4491]
### System Info

Langchain version: 0.0.72
Next.js version: v13.4.1

### Who can help?

@hwchase17 @vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm using next.js and want to integrate langchain with Chroma. The error happened when I try to import { Chroma } from "langchain/vectorstores" in a my next.js file.

When I run npm run dev, the error message is in the screenshot below:
<img width="922" alt="截屏2023-05-10 17 42 35" src="https://github.com/hwchase17/langchain/assets/67210127/8ec6a8d2-8753-4990-af2f-f2e66af7db6d">

These are all the imports I'm doing:
<img width="797" alt="截屏2023-05-10 17 43 14" src="https://github.com/hwchase17/langchain/assets/67210127/57d0fb2f-416b-479e-9a15-1412afce4459">
I checked and the error message is caused by the first line. 

Below is my next.config.js
<img width="691" alt="截屏2023-05-10 17 45 00" src="https://github.com/hwchase17/langchain/assets/67210127/47fc9dc6-56a3-4d06-b454-c2474af6eb2f">

### Expected behavior

I only expect it to compile successfully

**Comment by altechzilla** [comment]
Same here, doesn't let me use a TextLoader on a Next.js server function. Do document loaders work with Next.js at all?

**Comment by altechzilla** [comment]
I confirm this when using edge runtime on Next.js. Works without it.

**Comment by ludibel** [comment]
This config worked for me in next.config.js

`/** @type {import('next').NextConfig} */
const nextConfig = {
    reactStrictMode: true,
    swcMinify: true,
    webpack: (config, { webpack }) => {
      config.experiments = { ...config.experiments, topLevelAwait: true };
      config.externals["node:fs"] = "commonjs node:fs";
      config.resolve.fallback = {
        ...config.resolve.fallback,
        fs: false,
    };
      config.plugins.push(

        new webpack.NormalModuleReplacementPlugin(
          /^node:/,
          (resource) => {
            resource.request = resource.request.replace(/^node:/, '');
          },
        ),
      );
  
      return config;
    }
  }
  
  module.exports = nextConfig;`

**Comment by vowelparrot** [comment]
Thank you for raising this issue! @dev2049 linked this issue to the JS package issues board: https://github.com/hwchase17/langchainjs/issues/1211

**Comment by jacoblee93** [comment]
Hey @ruai0511, we've deprecated importing from `langchain/vectorstores` and `langchain/embeddings` in favor of new entrypoints to avoid issues like this (some other vector stores are Node only and use `fs`).

In your case the imports would be `import { Chroma } from "langchain/vectorstores/chroma"` and `import { OpenAIEmbeddings} from "langchain/embeddings/openai"` - can you try changing to that (and perhaps updating your LangChainJS version)?

**Comment by sarmstead** [comment]
> This config worked for me in next.config.js
> 
> ```js
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>     reactStrictMode: true,
>     swcMinify: true,
>     webpack: (config, { webpack }) => {
>       config.experiments = { ...config.experiments, topLevelAwait: true };
>       config.externals["node:fs"] = "commonjs node:fs";
>       config.resolve.fallback = {
>         ...config.resolve.fallback,
>         fs: false,
>     };
>       config.plugins.push(
> 
>         new webpack.NormalModuleReplacementPlugin(
>           /^node:/,
>           (resource) => {
>             resource.request = resource.request.replace(/^node:/, '');
>           },
>         ),
>       );
>   
>       return config;
>     }
>   }
>   
>   module.exports = nextConfig;
> /
> ```

I'm working on a Next.js project and this config worked for me as well. Thank you, @ludibel!

In case anyone is wondering what's going on here...
- The `config.externals` key tells Webpack to skip bundling a particular package. Basically, at the time of writing, Webpack can't figure out how to handle the new `node:` URI scheme. So we are bypassing bundling those imports altogether.
  - [According to the docs](https://webpack.js.org/configuration/externals/): "The `externals` configuration option provides a way of excluding dependencies from the output bundles. Instead, the created bundle relies on that dependency to be present in the consumer's (any end-user application) environment"
- `config.resolve.fallback` is yet another bypassing measure. 
  - [According to the docs](https://webpack.js.org/configuration/resolve/#resolvefallback), here we are telling Webpack to "redirect module requests when normal resolving fails." So, don't keep trying to resolve and thereby fail at the build step. Instead, move along, Webpack, and continue with our build!
- Finally, the `config.plugins.push` key is adding a specific plugin to our Webpack config. 
  - The plugin we are using here is the `NormalModuleReplacementPlugin` which allows us to take over module resolution behavior. `NormalModuleReplacementPlugin()` takes two parameters: `resourceRegExp` and `newResource`.
  - The `resourceRegExp` is a regular expression to match the resource we are looking for (in this case we are looking for resources that start with `node:`, as would be the case, for example, with a file that contains `import { readFile } from "node:fs/promises";`). 
  - `newResource` is being used here as a function. As such, we can "overwrite the request attribute of the supplied resource". [See the plugin docs](https://webpack.js.org/plugins/normal-module-replacement-plugin/) for more on this.

Hope this helps somebody!

**Comment by mariosknl** [comment]
I'm having the same issue and the next.config provided doesn't solve it. I'm working on a NextJS 14.0.3 project using PayloadCMS. My Node version is 18.19.0. I'm seeing this error when I'm trying to initialize Mailtrap for my email system. Any idea how to solve this error please?

![Screenshot 2024-02-10 at 08 33 49](https://github.com/langchain-ai/langchain/assets/50610396/401cc29f-baf2-4db8-9dea-b60711bfd204)

**Comment by noszczynski** [comment]
thank You @ludibel
