### ISSUE TITLE
Let Agent use Tool chains

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#451]
tool chains...so that a agent can direcly funnel the returns of a webrequest to a summerization tool

that would save a lot of context

so the agent can call something like summerizeAndanwser(Webrequest("gpt provided url"), "gpt provided question")

**Comment by thepok** [comment]
maybe we should skip that, and go directly to some kind of pseudocode

I made some great working examples:
Following is a list of sophisticated Functions you can use to solve your orders.

Web(url) returns text of webpage , use it for example to get wiki pages or google searchresults. All of the internet is accessable.
Summerize(text, question) -> returns the answer to the question if it can be found in the text or returns "not found"
print(text) -> Prints the text to the output, so you can see it in the {Result}

if you use a = sign you can save stuff in variables
you can chain funcions like A(B(input1, input2),input3)

Use the following structure to query the system:

>>>
{Code to evaluate}
===
{Result}
<<<

>>>
myText="The Ball is red."
answer=Summerize(myText, "What color is the ball?")
print(answer)
===
red
<<<

Now find out with this tools what are the biggest animals. Work step by step and use variables.

>>>
url="https://en.wikipedia.org/wiki/List_of_the_largest_known_organisms"
webpage=Web(url)
answer=Summerize(webpage, "What are the biggest animals?")
print(answer)
===
The largest animals are the blue whale, the giant African land snail, the giant clam, the giant tortoise, the great white shark, the saltwater crocodile, and the giant oarfish.
