### ISSUE TITLE
Can't use gpt-4-32k model with ChatOpenAI

### ISSUE THREAD

**Issue by sagardspeed2** [langchain-ai/langchain#4511]
### System Info

I am trying to use latest gpt-4-32k model with langchain ChatOpenAI

but I am getting the error 

``` The model: `gpt-4-32k` does not exist```.

so can we use other models except base model of openai ?

### Information

- [x] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from flask_socketio import emit
from urllib.parse import urlparse
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Pinecone
from langchain.chat_models import ChatOpenAI
from langchain.chains import LLMChain
from langchain.chains.question_answering import load_qa_chain
from langchain.prompts import PromptTemplate
import openai
import pinecone
import os
import shutil
import uuid
import time
import json
import store.main as store
from controller.scrape import ScrapeSite
import services.calltype as CalltypeService
import services.organization as OrganizationService

# create completion process chain
def create_completion_llm_chain(self):
    llm = ChatOpenAI(temperature=0, model_name='gpt-4-32k', max_tokens=2048, request_timeout=120)
    chain = load_qa_chain(llm, chain_type='stuff')
    return chain
    
# generate llm chain
chain = self.create_completion_llm_chain()

query = 'here I added my query'

# process prompt with sources on gpt
response = chain.run(question=query, input_documents=sourceDocs)
```

using this token, you will get the error,
``` The model: `gpt-4-32k` does not exist```

### Expected behavior

It should work with the any model that provides by the openAI

**Comment by dev2049** [comment]
could you post the full error message

**Comment by AlpriElse** [comment]
Similar to https://community.openai.com/t/gpt-4-32k-the-model-gpt-4-32k-does-not-exist/160459

Are you sure you access to that OpenAI model? It's still in limited beta

You can check if you access by hitting their models endpoint:
https://platform.openai.com/docs/api-reference/models

**Comment by paralin** [comment]
@AlpriElse is right, that model is not available yet.

**Comment by dmyoung9** [comment]
This should be closed. The model isn't available to all users, but works fine for those who do have access.
