### ISSUE TITLE
Get response from my training data using a GPT-based chatbot

### ISSUE THREAD

**Issue by webdev-rohit** [langchain-ai/langchain#4512]
I have developed a chatbot using **Langchain's OpenAI LLM (text-davinci)** model and added my own contextual data using the **llama index (GPT index)** on top of GPT's existing data.

I'm facing an issue with a specific scenario in my chatbot. I have included the following FAQ in my training data, which consists of a large list of questions:

*Q: Who is the Prime Minister of India?
A: The Prime Minister of India is John Doe.*

However, when I ask the bot this question, I want it to consistently provide this specific answer. While it does give the desired answer sometimes, most of the time it retrieves the answer from the internet or its own corpus, stating that the Prime Minister of India is Narendra Modi. 

Essentially, I want complete control over the response generated by GPT when I ask questions from my training dataset. However, I also want GPT to utilize its own corpus to answer questions that are not part of my training dataset. For instance, if I ask a question like "Tell me something about European culture," which is not in my training dataset, GPT should provide a response based on its own knowledge. But when I enquire about the "PM of India," it should always respond with "John Doe."

It is important to note that this is **not a typical fine-tuning scenario**, as we are not looking to identify patterns in the questions. Fine-tuning fails when we ask questions like "Who is the wife of the PM?" since it provides the same answer as "Who is the PM?"

I would greatly appreciate any suggestions or assistance regarding this matter.

**Comment by 9akashnp8** [comment]
hey rohit, can you show us your prompt/query?

**Comment by webdev-rohit** [comment]
Hey @9akashnp8 my training data consists of questions in the following format -
Q: Who is the Prime Minister of India? 
A: The Prime Minister of India is John Doe. 
Q: Who is the IT minister of India?
A: The IT minister of India is Jane Doe.

My code for querying and creating vector embeddings from the above training data is as follows -

def construct_index(directory_path):
    # set maximum input size
    max_input_size = 4096
    # set number of output tokens
    num_outputs = 2000
    # set maximum chunk overlap
    max_chunk_overlap = 20
    # set chunk size limit
    chunk_size_limit = 600 

    # define LLM
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.0, model_name="text-davinci-003", max_tokens=num_outputs))
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    
    documents = SimpleDirectoryReader(directory_path).load_data()
    
    index = GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper
    )

    index.save_to_disk('index.json')
    
construct_index("context_data/data")

# code to query the index.json file (which contains the embeddings) is -
message = "Who is the PM?"
index = GPTSimpleVectorIndex.load_from_disk('./index.json')
response = index.query(message, response_mode="compact")
result = response.response

**Comment by shreyabhadwal** [comment]
I think it might be helpful to add additional instructions in the prompt along these lines

Use the following pieces of context to answer the users question. 
If you don't know the answer, just say that you don't know, don't try to make up an answer.
----------------
{context}

Something similar to the prompts in the qa_chain (https://github.com/hwchase17/langchain/blob/master/langchain/chains/question_answering/stuff_prompt.py
