### ISSUE TITLE
Adding mlflow tests

### ISSUE THREAD

**Issue by akshaya-a** [langchain-ai/langchain#4527]
@agola11 + @hwchase17 + @dev2049  thanks for the review and pushing the PR over the finish line!

I'd like to add a few more tests in a follow up - are you willing to add mlflow + azureml-mlflow packages as test dependencies or should we explore some other options?

_Originally posted by @akshaya-a in https://github.com/hwchase17/langchain/issues/4150#issuecomment-1540983848_

**Comment by dev2049** [comment]
test dependencies should be ok!

**Comment by akshaya-a** [comment]
Sorry for not following up in this thread, for anyone that ends up here later, there are tests being added for the most important part (serialization) here, so decided not to duplicate efforts in this repo for now while things are moving quickly: https://github.com/mlflow/mlflow/tree/master/tests/langchain
