### ISSUE TITLE
UnstructuredWordDocumentLoader can not  load .docx file

### ISSUE THREAD

**Issue by expresschen** [langchain-ai/langchain#4543]
### System Info

langchain:0.0.163
python:3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

"There is no item named 'word/footnotes.xml' in the archive"

### Expected behavior

can load .docx

**Comment by UmerHA** [comment]
Hey @expresschen, can you post 1) the exact code that resulted in this error and 2) (if possible) the docx file? Then I'll take a look :)

**Comment by UmerHA** [comment]
![image](https://github.com/hwchase17/langchain/assets/40663591/03dba66d-9614-4caa-a9c9-cfb11d17c3aa)

It seems to work for up-to-date langchain & python versions

**Comment by nithinreddyyyyyy** [comment]
> ![image](https://user-images.githubusercontent.com/40663591/238129139-03dba66d-9614-4caa-a9c9-cfb11d17c3aa.png)
> 
> It seems to work for up-to-date langchain & python versions

how to load multiple docx at a time? Like we can do for pdf's with DirectoryLoader

**Comment by UmerHA** [comment]
> > ![image](https://user-images.githubusercontent.com/40663591/238129139-03dba66d-9614-4caa-a9c9-cfb11d17c3aa.png)
> > It seems to work for up-to-date langchain & python versions
> 
> how to load multiple docx at a time? Like we can do for pdf's with DirectoryLoader

Hey, see my answer in https://github.com/hwchase17/langchain/issues/4856 :)
