### ISSUE TITLE
我翻译了中文文档，希望对中国开发者有用

### ISSUE THREAD

**Issue by kangyiwen** [langchain-ai/langchain#4548]
### Issue with current documentation:

I have translated a Chinese document and hope it is useful for Chinese developers.

在中国的 langchain 开发者，可以看中文了。
[www.langchain.com.cn](https://www.langchain.com.cn/)

**Comment by chen1tian** [comment]
good work! You always pick up money when you go out.

**Comment by Einholz-Gao** [comment]
十分感谢您的贡献！！

**Comment by kangyiwen** [comment]
最新版中文文档： v0.0.291     https://python.langchain.com.cn/
谢谢支持。本话题关闭
