### ISSUE TITLE
Wolfram Alpha connection as tool

### ISSUE THREAD

**Issue by thepok** [langchain-ai/langchain#455]
API seams easy
https://wolframalpha.readthedocs.io/en/latest/?badge=latest

**Comment by thepok** [comment]
Mr Wolfram thinks about something like that it self

https://writings.stephenwolfram.com/2023/01/wolframalpha-as-the-way-to-bring-computational-knowledge-superpowers-to-chatgpt/

**Comment by nickscamara** [comment]
I can start on this today. If anyone is interested in helping, I will link a PR here soon.

**Comment by justanotherlad** [comment]
Is this issue Resolved, or is there something left to be worked on? I could help.

**Comment by nickscamara** [comment]
@dosu-beta issue was resolved and merged on #578
