### ISSUE TITLE
Any ideas on making input and output languages consistent?

### ISSUE THREAD

**Issue by realgump** [langchain-ai/langchain#4550]
### Issue you'd like to raise.

When I using agent with a llm of gpt-3.5 and a search tool of google, the AI's response is always in English, regardless of my input being in Chinese. Are there any ideas on how to ensure that the input and output languages are consistent?

**Comment by KeshavSingh29** [comment]
@andreakiro It doesnt work with agents because they change the question to english in `action_input` and response is always in english.

**Comment by oskrocha** [comment]
I have the same problem using "ConversationalAgent", gpt-3 and a set of tools. Agent always translates questions to english and puts it in the `action_input` thus answer is in English.
Is this the expected behavior of the agents or is it a just bug? Is there any workaround?
Thanks in advance for your suggestions

**Comment by realgump** [comment]
> I have the same problem using agent=ConversationalAgent, llm=OpenAI and a set of tools. I confirm the Agent always translate the question to english and puts it in the `action_input` thus the output answer is in English. Is this the expected behavior of the agents or is it a just bug? Is there any workaround? Thanks in advance for your suggestions

This question only arises when I use GPT-3.5, not GPT-3. I have debugged the code step by step and identified a possible reason. When using GPT-3.5, some tool descriptions are sent after the user's input and are not shown in the final response. However, when using GPT-3, all tool descriptions are requested together with the user's input. Therefore, I had to add my language command in the prompt, and it worked. I hope this information is helpful to you.

**Comment by KeshavSingh29** [comment]
Here is a solution that works pretty well (tested on multiple languages as input)
I have only tested it for `conversational-react-description` agent type, but it requires you to tweak the tool as well as agent prompt. 
```python 
# For Tool have a pre-defined format
class KnowledgeTool(BaseTool):
    request_format = '{{"USER": "<input_question>"}}'
    name = 'Knowledge Tool'
    description = f"""
    Tool to answer something knowledgeable. Input should be JSON in the following format: {request_format}
        """
    return_direct = False
# define your methods etc.....

conversational_agent = initialize_agent(
        agent='conversational-react-description',
        tools=[KnowledgeTool()])

# You can identify the language with any modules like lingua or fasttext       
prompt_prefix = f""" Your description similar to system message. Use only  {language} language to reply"""

# Now the magic part 
conversational_agent.agent.llm_chain.prompt = prompt_prefix
```
Let me know if doesnt work, I can help.

**Comment by PeterTF656** [comment]
> Here is a solution that works pretty well (tested on multiple languages as input) I have only tested it for `conversational-react-description` agent type, but it requires you to tweak the tool as well as agent prompt.
> 
> ```python
> # For Tool have a pre-defined format
> class KnowledgeTool(BaseTool):
>     request_format = '{{"USER": "<input_question>"}}'
>     name = 'Knowledge Tool'
>     description = f"""
>     Tool to answer something knowledgeable. Input should be JSON in the following format: {request_format}
>         """
>     return_direct = False
>     
>     # define your tool methods etc.....
> 
> # Initialize agent 
> conversational_agent = initialize_agent(
>         agent='conversational-react-description',
>         tools=[KnowledgeTool()])
> 
> # You can identify the language with any modules like lingua or fasttext       
> prompt_prefix = f"""<Your description similar to system message> Use only {language} language to reply"""
> 
> # Now the magic part 
> conversational_agent.agent.llm_chain.prompt = prompt_prefix
> ```
> 
> Let me know if doesnt work, I can help.

Hi, Thank you for sharing your code. I gave it a try, but it showed this error for me: 
```
File [/Applications/anaconda3/envs/testing_chat/lib/python3.9/site-packages/langchain/chains/base.py:239](https://file+.vscode-resource.vscode-cdn.net/Applications/anaconda3/envs/testing_chat/lib/python3.9/site-packages/langchain/chains/base.py:239), in Chain.run(self, callbacks, *args, **kwargs)
    236     return self(args[0], callbacks=callbacks)[self.output_keys[0]]
    238 if kwargs and not args:
--> 239     return self(kwargs, callbacks=callbacks)[self.output_keys[0]]
    241 if not kwargs and not args:
    242     raise ValueError(
    243         "`run` supported with either positional arguments or keyword arguments,"
    244         " but none were provided."
    245     )

File [/Applications/anaconda3/envs/testing_chat/lib/python3.9/site-packages/langchain/chains/base.py:123](https://file+.vscode-resource.vscode-cdn.net/Applications/anaconda3/envs/testing_chat/lib/python3.9/site-packages/langchain/chains/base.py:123), in Chain.__call__(self, inputs, return_only_outputs, callbacks)
    106 def __call__(
    107     self,
    108     inputs: Union[Dict[str, Any], Any],
    109     return_only_outputs: bool = False,
    110     callbacks: Callbacks = None,
    111 ) -> Dict[str, Any]:
    112     """Run the logic of this chain and add to output if desired.
    113 
    114     Args:
...
     52     :meta private:
     53     """
---> 54     return self.prompt.input_variables

AttributeError: 'str' object has no attribute 'input_variables'
```
My code was: 
```
agent_chain = initialize_agent(tools, fast_chat, agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION, verbose=True, memory=memory)
agent_chain.agent.llm_chain.prompt = prompt_prefix
agent_chain.run(input=some_input)
```
Could you please take a look?

**Comment by KeshavSingh29** [comment]
@PeterTF656 
Like the error says: 
`"`run` supported with either positional arguments or keyword arguments,"
 244         " but none were provided."`
 Can you show how you set up the memory? Seems like the keys are not setup.

**Comment by PeterTF656** [comment]
> @PeterTF656 Like the error says: `"`run` supported with either positional arguments or keyword arguments," 244 " but none were provided."` Can you show how you set up the memory? Seems like the keys are not setup.

@KeshavSingh29 Thank you for your swift response! I set up memory the normal way: ```memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)```

**Comment by KeshavSingh29** [comment]
I cant replicate it. 
Can you share the working code to replicate the issue? 
And what exactly is `fast_chat`

**Comment by MrRace** [comment]
> > I have the same problem using agent=ConversationalAgent, llm=OpenAI and a set of tools. I confirm the Agent always translate the question to english and puts it in the `action_input` thus the output answer is in English. Is this the expected behavior of the agents or is it a just bug? Is there any workaround? Thanks in advance for your suggestions
> 
> This question only arises when I use GPT-3.5, not GPT-3. I have debugged the code step by step and identified a possible reason. When using GPT-3.5, some tool descriptions are sent after the user's input and are not shown in the final response. However, when using GPT-3, all tool descriptions are requested together with the user's input. Therefore, I had to add my language command in the prompt, and it worked. I hope this information is helpful to you.

@realgump Could  you show an code  example  that used to solve the problem？

**Comment by bug2203** [comment]
> > > I have the same problem using agent=ConversationalAgent, llm=OpenAI and a set of tools. I confirm the Agent always translate the question to english and puts it in the `action_input` thus the output answer is in English. Is this the expected behavior of the agents or is it a just bug? Is there any workaround? Thanks in advance for your suggestions
> > 
> > 
> > This question only arises when I use GPT-3.5, not GPT-3. I have debugged the code step by step and identified a possible reason. When using GPT-3.5, some tool descriptions are sent after the user's input and are not shown in the final response. However, when using GPT-3, all tool descriptions are requested together with the user's input. Therefore, I had to add my language command in the prompt, and it worked. I hope this information is helpful to you.
> 
> @realgump Could you show a code snippet that used to solve the problem？


Try to modify the prompt word template in the langchain file instead of setting prompt in your code through PromptTemplate

**Comment by wnose** [comment]
Thanks, I can work with this.
language="Chinese"

# Finally, let's initialize an agent with the tools, the language model, and the type of agent we want to use.
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

# You can identify the language with any modules like lingua or fasttext       
prompt_prefix = f"""<Your description similar to system message> Use only {language} language to reply:"""

# Now the magic part 
agent.agent.llm_chain.prompt.template = prompt_prefix + agent.agent.llm_chain.prompt.template

# Now let's test it out!
agent.invoke(input ="答案用中文回答:最流行的编程语言有哪些，列出最流行的5个？")

**Comment by wnose** [comment]
thanks! I can work like this.
```python
language="Chinese"

# Finally, let's initialize an agent with the tools, the language model, and the type of agent we want to use.
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

# You can identify the language with any modules like lingua or fasttext       
prompt_prefix = f"""<Your description similar to system message> Use only {language} language to reply:"""

# Now the magic part 
agent.agent.llm_chain.prompt.template = prompt_prefix + agent.agent.llm_chain.prompt.template

# Now let's test it out!
agent.invoke(input ="答案用中文回答:最流行的编程语言有哪些，列出最流行的5个？")
```
