### ISSUE TITLE
我的提问被langchain修改了（langchain change my question）

### ISSUE THREAD

**Issue by huanghb1021** [langchain-ai/langchain#4555]
### Issue you'd like to raise.

我通过langchain向openai进行提问，langchain会将我的提问与我的聊天历史记录合并为一个新的问题，然后再向openai进行提问。但是新的提问有时候与我旧的提问相差不小。
比如说我问langchain：你好
langchain提问openai：How can I assist you today? 
所以我有的时候会得到一些奇怪的回答。为什么会这样以及我该怎么处理呢？
(
i talk to openai by langchain, but langchain will trans my question to a new question by my question and chat history. sometimes i got strange answer! for example
i talk to langchain: hello
langchian talk to openai: How can I assist you today?  
so, i got strange answer semms unrelated to my origin question. why langchain do this,and how can i fix this ?
)

ConversationalRetrievalChain（BaseConversationalRetrievalChain._call）
![image](https://github.com/hwchase17/langchain/assets/38252232/217a7169-5dc1-435b-b5da-fda9eaf0fa12)

**Comment by huanghb1021** [comment]
![image](https://github.com/hwchase17/langchain/assets/38252232/38cf8b4b-5a82-4575-bcf4-31cf4376618c)

**Comment by lingfengchencn** [comment]
合并是肯定的，gpt应该会结合上下文回复最后一个问题。

**Comment by huanghb1021** [comment]
> 合并是肯定的，gpt应该会结合上下文回复最后一个问题。

为什么要合并生成新的问题呢？ 有的时候生成的新的问题，与我的提问完全不相干，导致对话错乱了。为何不把历史记录原样的传给openai，而是要造一个新的问题

**Comment by hycao** [comment]
> > 合并是肯定的，gpt应该会结合上下文回复最后一个问题。
> 
> 为什么要合并生成新的问题呢？ 有的时候生成的新的问题，与我的提问完全不相干，导致对话错乱了。为何不把历史记录原样的传给openai，而是要造一个新的问题


I think the merging of conversations has created new problems because you are using ConversationalRetrievalChain to query vector databases based on question similarity. 

example:
```
human： I want to buy
ai:            What do you want to buy?       
human:   A car
```

If you search using all historical records, it is easy to get incorrect answers. 

The results obtained from searching in the vector database will be worse as your search history becomes more and more.

If you use the merge history and generate new issues from it, like this:

```
new question: I want to buy a car.
```

You can easily and accurately find similar paragraphs from the vector database.


I also encountered a similar problem once before, but it seems some error from openai and I haven't encountered it again.

**Comment by huanghb1021** [comment]
> > > 合并是肯定的，gpt应该会结合上下文回复最后一个问题。
> > 
> > 
> > 为什么要合并生成新的问题呢？ 有的时候生成的新的问题，与我的提问完全不相干，导致对话错乱了。为何不把历史记录原样的传给openai，而是要造一个新的问题
> 
> I think the merging of conversations has created new problems because you are using ConversationalRetrievalChain to query vector databases based on question similarity.
> 
> example:
> 
> ```
> human:  I want to buy
> ai:  what do you want to buy?       
> human:   a car
> ```
> 
> If you search using all historical records, it is easy to get incorrect answers.
> 
> The results obtained from searching in the vector database will be worse as your search history becomes more and more.
> 
> If you use the merge history and generate new issues from it, like this:
> 
> ```
> new question: I want to buy a car.
> ```
> 
> You can easily and accurately find similar paragraphs from the vector database.
> 
> I also encountered a similar problem once before, but it seems some error from openai and I haven't encountered it again.

为了提高准确率而去改变用户的提问，这个感觉有点奇怪。
![image](https://github.com/hwchase17/langchain/assets/38252232/1c7941ee-131b-47a5-af4d-7f03f1422b7f)
每次对话没开始多久就会变得很无法理解

**Comment by shaowin16** [comment]
同感，体感确实很不好

**Comment by shaowin16** [comment]
已收到，谢谢！
