### ISSUE TITLE
ConversationalRetrievalChain with Custom Agent is not returning source documents

### ISSUE THREAD

**Issue by sanasz91mdev** [langchain-ai/langchain#4562]
### System Info

Hi i am using ConversationalRetrievalChain with agent and agent.run function is not returning source documents.
Is this by functionality or is it a missing feature?

```
def llm_answer(query):
   chat_history = []
   result = qa({"question": query, "chat_history": chat_history})
   print('result is')
   print(result)
   print('-----------------------------')
   print(result['source_documents'][0])
   print('-----------------------------')
   #populateHistory(query, result)
   return result


qa = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), db.as_retriever(), return_source_documents=True)

class requestModel(BaseModel):
    question: str

app = FastAPI()
tools = [
    Tool.from_function(
        func=llm_answer,
        name = "Email knowledge base",
        description="useful for when you need to answer questions from emails in knowledge base",
        args_schema=requestModel    
        )
#more tools
]

agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

# Define API endpoint for querying the model
@app.post('/answer')
async def answer(request: requestModel):
    print('request received')
    source_documents = []
    # Get data from request
    print("Query is " + request.question)
    q_answer2 = agent.run(request.question)
    print("answer is ")
    print(q_answer2)
    #construct a json object to return answer and sources to the client
    reply = {'answer' : str(q_answer2), 'sources' : []}
    # for x in q_answer2["source_documents"]:
    #     reply['sources'].append(x.metadata["source"])
    return reply

```

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

use code sample provided

### Expected behavior

agent.run should provide with both answers and source_documents

**Comment by tevslin** [comment]
with 
`dochistory  = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever(search_kwargs={"k": 6}), return_source_documents=True)
...
tools = [

    Tool(
        name = "Document Cache",
        func=dochistory.run,
        description="Useful for when you need to answer questions about the aspects asked. Input may be a partial or fully formed question." 
        ),
...
llm_chain=LLMChain(llm=llm,prompt=prompt)


agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True,return_source_documents=True,prompt=prompt)

agent_chain = AgentExecutor.from_agent_and_tools(
                agent=agent, tools=tools, verbose=True, memory=memory,return_source_documents=True
            )
result=agent_chain.run(query)
`
get error 
ValueError: `run` not supported when there is not exactly one output key. Got ['result', 'source_documents'].
code runs if I don't ask for source documents but I want them.

**Comment by sanasz91mdev** [comment]
> with `dochistory = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever(search_kwargs={"k": 6}), return_source_documents=True) ... tools = [
> 
> ```
> Tool(
>     name = "Document Cache",
>     func=dochistory.run,
>     description="Useful for when you need to answer questions about the aspects asked. Input may be a partial or fully formed question." 
>     ),
> ```
> 
> ... llm_chain=LLMChain(llm=llm,prompt=prompt)
> 
> agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True,return_source_documents=True,prompt=prompt)
> 
> agent_chain = AgentExecutor.from_agent_and_tools( agent=agent, tools=tools, verbose=True, memory=memory,return_source_documents=True ) result=agent_chain.run(query) ` get error
> 
> "ValueError: `run` not supported when there is not exactly one output key. Got ['result', 'source_documents']" code runs if I don't ask for source documents but I want them.

yes i also need source_documents

**Comment by sanasz91mdev** [comment]
@tevslin  So i found  a way where we can extract the source documents 

while initializing agent set following to true:

`return_intermediate_steps=True, return_source_documents=True`
 
Then invoke agent like below

```
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True,return_intermediate_steps=True,return_source_documents=True)
q_answer2 = agent({request.question})
```
`q_answer2  `would return a key "intermediate_steps" that contains source docs and you can extract them as below:

```

qa = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), db.as_retriever(), return_source_documents=True) #condense_question_prompt=prompt


tools = [
#...
]

agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True,return_intermediate_steps=True,return_source_documents=True)

# Define API endpoint for querying the model
@app.post('/answer')
async def answer(request: requestModel):
    print('request received')
    # Get data from request
    print("Query is " + request.question)
    q_answer2 = agent({request.question})
    print(q_answer2)
    reply = {'answer' : str(q_answer2["output"]), 'sources' : []}
    intermediate_steps = q_answer2["intermediate_steps"]
    try:
        if(intermediate_steps):
            source_docs = intermediate_steps[0][1]['source_documents']
            print(source_docs)
            for x in source_docs:
                if x.metadata["source"] not in reply['sources']:
                    reply['sources'].append(x.metadata["source"])
    except Exception as err:
        print("Error fetching source documents: {}".format(err))
    return reply

```

**Comment by tevslin** [comment]
Thank for working on this. I am using an agent executor. If I put return_intermediate_steps=True in the agent definiton, it seems to be ignored. If I put it in AgentExecutor.from_agent_and_tools I get `run` not supported when there is not exactly one output key. Got ['output', 'intermediate_steps']. "run" refers to the entry point to the search tool I've provided as a retriever. I think I may be overloading the langchain apis by wanting to have a retriever, and agent executor, a chat model, and also get sources - but this is what I'd like to do.

**Comment by joeyhsiung** [comment]
Please refer to this issue: https://github.com/hwchase17/langchain/issues/3523#issuecomment-1540239594

**Comment by Sadaf-Syeda** [comment]
> @tevslin So i found a way where we can extract the source documents
> 
> while initializing agent set following to true:
> 
> `return_intermediate_steps=True, return_source_documents=True`
> 
> Then invoke agent like below
> 
> ```
> agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True,return_intermediate_steps=True,return_source_documents=True)
> q_answer2 = agent({request.question})
> ```
> 
> `q_answer2 `would return a key "intermediate_steps" that contains source docs and you can extract them as below:
> 
> ```
> 
> qa = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0), db.as_retriever(), return_source_documents=True) #condense_question_prompt=prompt
> 
> 
> tools = [
> #...
> ]
> 
> agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True,return_intermediate_steps=True,return_source_documents=True)
> 
> # Define API endpoint for querying the model
> @app.post('/answer')
> async def answer(request: requestModel):
>     print('request received')
>     # Get data from request
>     print("Query is " + request.question)
>     q_answer2 = agent({request.question})
>     print(q_answer2)
>     reply = {'answer' : str(q_answer2["output"]), 'sources' : []}
>     intermediate_steps = q_answer2["intermediate_steps"]
>     try:
>         if(intermediate_steps):
>             source_docs = intermediate_steps[0][1]['source_documents']
>             print(source_docs)
>             for x in source_docs:
>                 if x.metadata["source"] not in reply['sources']:
>                     reply['sources'].append(x.metadata["source"])
>     except Exception as err:
>         print("Error fetching source documents: {}".format(err))
>     return reply
> ```

This also does not Work

**Comment by tevslin** [comment]
I am using similar logic and it does work.

**Comment by Mennaaah** [comment]
> 

it does not work with me either. I am using the following:
```
qa_chain = RetrievalQAWithSourcesChain.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=db.as_retriever(),
        chain_type_kwargs=chain_type_kwargs,
        return_source_documents=True,
        verbose=True
        )
    tools = [
    Tool(  
        name="QA",    
        func=qa_chain,
        description="easy to answer"
        
    ),
    ]
    agent = initialize_agent(tools, llm, agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION, verbose=True,
    return_intermediate_steps=True,return_source_documents=True)
    #answer = agent_chain.run(input=question)
    answer =  agent({question})
```

I am getting the following error:
```
ValueError: A single string input was passed in, but this chain expects multiple inputs ({'chat_history', 'input'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`
```
even when I changed the answer into:
```
answer =  agent({"input":question})
```
I got the following error:
```
ValueError: Missing some input keys: {'chat_history'}
```
what should I add for this? I am just using RetrievalQAWithSourcesChain

**Comment by shiv-pratap2002** [comment]
did anyone resolve this?
