### ISSUE TITLE
Issue: PlanAndExecute agent fails in chat mode when a simple chat interaction is required.

### ISSUE THREAD

**Issue by pretidav** [langchain-ai/langchain#4582]
### Issue you'd like to raise.

PlanAndExecute agent is rising errors when no questions are asked (e.g. a greeting interaction). 
Is there any Chat implementation where a simple LLM chat interaction is available among the available tools? 

Thank you in advance.

**Comment by zvadaadam** [comment]
_**🤖 AI-generated response by [Steercode](https://steercode.com/) - chat with Langchain codebase**_
_Disclaimer: SteerCode Chat may provide inaccurate information about the Langchain codebase._

In the Langchain codebase, you can use the ConversationalChatAgent class to handle simple chat interactions. You can create an instance of this class using the from_llm_and_tools() method, which takes a language model and a sequence of tools as its arguments.

Here's an example of how to create a chat agent using the ConversationalChatAgent class:
```
from langchain.agents.conversational_chat.base import ConversationalChatAgent
from langchain.llm.base import BaseLanguageModel
from langchain.tools.base import BaseTool

# Initialize your language model and tools
llm = BaseLanguageModel()
tools = [BaseTool()]

# Create a ConversationalChatAgent instance
chat_agent = ConversationalChatAgent.from_llm_and_tools(llm=llm, tools=tools)
```

Once you have a ConversationalChatAgent instance, you can use it to handle chat interactions without raising errors when receiving non-question inputs like greetings.

**You can continue the conversation at https://steercode.com/**

**Comment by firaskudsy** [comment]
is there an example ?
