### ISSUE TITLE
langchain OpenSearchVectorSearch similarity_search error

### ISSUE THREAD

**Issue by akgv04** [langchain-ai/langchain#4597]
### Issue you'd like to raise.

When I try to perform a similarity_search on an opensearch index on AWS of size 50GB (approx 2 million documents with vectors for each), i sometimes get this error. It does not happen all the time. Usually the first time when I make a request the response is successful, subsequent calls immediately result in this error. Is this error, because langchain is doing a similarity search over lot of vectors and open search ran out of memory? - 

```
embeddings = OpenAIEmbeddings()
docsearch = OpenSearchVectorSearch(index_name="xxxxxxxx", embedding_function=embeddings, opensearch_url=opensearch_url)

query = "Whats the xxxxxxx"
docs = docsearch.similarity_search(query, k=1, search_type = "approximate_search", vector_field="sentence_embedding")
```

TransportError                            Traceback (most recent call last)
Cell In[100], line 2
      1 query = "Whats the warranty on labor and materials for the work performed by V.A.M.P. L.L.C."
----> 2 docs = docsearch.similarity_search(query, k=1, search_type = "approximate_search", vector_field="sentence_embedding")
      3 docs

File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/langchain/vectorstores/opensearch_vector_search.py:426](https://file+.vscode-resource.vscode-cdn.net/Users/AXG143/ananth/training/semantic-search-elasticsearch-openai-langchain/~/ananth/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/langchain/vectorstores/opensearch_vector_search.py:426), in OpenSearchVectorSearch.similarity_search(self, query, k, **kwargs)
    423 else:
    424     raise ValueError("Invalid `search_type` provided as an argument")
--> 426 response = self.client.search(index=self.index_name, body=search_query)
    427 hits = [hit["_source"] for hit in response["hits"]["hits"][:k]]
    428 documents = [
    429     Document(
    430         page_content=hit[text_field],
   (...)
    435     for hit in hits
    436 ]

File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/utils.py:178](https://file+.vscode-resource.vscode-cdn.net/training/semantic-search-elasticsearch-openai-langchain/~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/utils.py:178), in query_params.._wrapper.._wrapped(*args, **kwargs)
    176     if p in kwargs:
    177         params[p] = kwargs.pop(p)
--> 178 return func(*args, params=params, headers=headers, **kwargs)

File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/__init__.py:1551](https://file+.vscode-resource.vscode-cdn.net/training/semantic-search-elasticsearch-openai-langchain/~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/__init__.py:1551), in OpenSearch.search(self, body, index, params, headers)
...
--> 301 raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
    302     status_code, error_message, additional_info
    303 )

TransportError: TransportError(500, 'search_phase_execution_exception')

### Suggestion:

Expected response - langchain Opensearch similarity_search should work consistently on multiple calls.

**Comment by aerickson-clt** [comment]
From your description of the error, being intermittend and including the code `search_phase_execution_exception` I would think this is an issue with OpenSearch or with your resource provisioning for your instance, and not an issue with Langchain.

Are you still able to reproduce it?

**Comment by AnishMachamasi** [comment]
> ### Issue you'd like to raise.
> When I try to perform a similarity_search on an opensearch index on AWS of size 50GB (approx 2 million documents with vectors for each), i sometimes get this error. It does not happen all the time. Usually the first time when I make a request the response is successful, subsequent calls immediately result in this error. Is this error, because langchain is doing a similarity search over lot of vectors and open search ran out of memory? -
> 
> ```
> embeddings = OpenAIEmbeddings()
> docsearch = OpenSearchVectorSearch(index_name="xxxxxxxx", embedding_function=embeddings, opensearch_url=opensearch_url)
> 
> query = "Whats the xxxxxxx"
> docs = docsearch.similarity_search(query, k=1, search_type = "approximate_search", vector_field="sentence_embedding")
> ```
> 
> TransportError Traceback (most recent call last) Cell In[100], line 2 1 query = "Whats the warranty on labor and materials for the work performed by V.A.M.P. L.L.C." ----> 2 docs = docsearch.similarity_search(query, k=1, search_type = "approximate_search", vector_field="sentence_embedding") 3 docs
> 
> File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/langchain/vectorstores/opensearch_vector_search.py:426](https://file+.vscode-resource.vscode-cdn.net/Users/AXG143/ananth/training/semantic-search-elasticsearch-openai-langchain/~/ananth/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/langchain/vectorstores/opensearch_vector_search.py:426), in OpenSearchVectorSearch.similarity_search(self, query, k, **kwargs) 423 else: 424 raise ValueError("Invalid `search_type` provided as an argument") --> 426 response = self.client.search(index=self.index_name, body=search_query) 427 hits = [hit["_source"] for hit in response["hits"]["hits"][:k]] 428 documents = [ 429 Document( 430 page_content=hit[text_field], (...) 435 for hit in hits 436 ]
> 
> File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/utils.py:178](https://file+.vscode-resource.vscode-cdn.net/training/semantic-search-elasticsearch-openai-langchain/~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/utils.py:178), in query_params.._wrapper.._wrapped(*args, **kwargs) 176 if p in kwargs: 177 params[p] = kwargs.pop(p) --> 178 return func(*args, params=params, headers=headers, **kwargs)
> 
> File [~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/**init**.py:1551](https://file+.vscode-resource.vscode-cdn.net/training/semantic-search-elasticsearch-openai-langchain/~/training/semantic-search-elasticsearch-openai-langchain/vevn/lib/python3.9/site-packages/opensearchpy/client/__init__.py:1551), in OpenSearch.search(self, body, index, params, headers) ... --> 301 raise HTTP_EXCEPTIONS.get(status_code, TransportError)( 302 status_code, error_message, additional_info 303 )
> 
> TransportError: TransportError(500, 'search_phase_execution_exception')
> 
> ### Suggestion:
> Expected response - langchain Opensearch similarity_search should work consistently on multiple calls.

How do you store embeddings in opensearch?
what configuration did you make in opensearch?
