### ISSUE TITLE
RWKV

### ISSUE THREAD

**Issue by alienatorZ** [langchain-ai/langchain#4604]
### System Info

Langchain ver 0.0.167, MacBook Pro 2018, Mac OS Ventura.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1.) Download a model.
2.) Download the tokens file.
3.) Run code.

from langchain.llms.rwkv import RWKV

# Test the model

def generate_prompt(instruction, input=None):
    if input:
        return f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

# Instruction:
{instruction}

# Input:
{input}

# Response:
"""
    else:
        return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

# Instruction:
{instruction}

# Response:
"""

model = RWKV(model="~/Downloads/Q8_0RWKV.bin", strategy="cpu 8bit", tokens_path="./rwkv.tokens")
response = model(generate_prompt("Once upon a time, "))

### Expected behavior

I expect the sample to produce some text. 

What I get is an error. It appears that the rwkv library is not installed, but it is...

Traceback (most recent call last):
  File "/Users/John/Documents/Projects/langchainstufff/rwkv.py", line 29, in <module>
    model = RWKV(model="~/Downloads/Q8_0RWKV.bin", strategy="cpu 8bit", tokens_path="./rwkv.tokens")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
    vectorstore: VectorStore,

pydantic.error_wrappers.ValidationError: 1 validation error for RWKV
__root__ -> __root__
  Could not import rwkv python package. Please install it with `pip install rwkv`. (type=value_error)

**Comment by Hopping-Rabbit** [comment]
I encountered the same error when using it, and I printed out the error message on line 124 of the rwkv.py file. This error indicates that the torch library is not installed. You can try installing the torch library.

**Comment by Hopping-Rabbit** [comment]
@alienatorZ I have successfully resolved my issue.

**Comment by wajihullahbaig** [comment]
> I encountered the same error when using it, and I printed out the error message on line 124 of the rwkv.py file. This error indicates that the torch library is not installed. You can try installing the torch library.

Was this the solution?
