### ISSUE TITLE
GooglePalm `author` is returned as "1" but code is expecting "ai"

### ISSUE THREAD

**Issue by craigsdennis** [langchain-ai/langchain#4606]
https://github.com/hwchase17/langchain/blob/ed0d557ede8776921cc3c5ca1f3aef81d3d0c7b5/langchain/chat_models/google_palm.py#L65

Fix: `if author == "ai or author == "1":` seems to do the trick. 

Happy to submit a patch if y'all agree!

The [Google Palm Chat API](https://developers.generativeai.google/tutorials/chat_quickstart#conversation_history) returns a "1" for the AI response (and a "0" for the human).

**Comment by Jflick58** [comment]
I had to fix this for the Vertex AI PaLM integration, can confirm that this corrects the issue.

**Comment by Jflick58** [comment]
Needs to be added to the "straight-up" google palm integration though.
