### ISSUE TITLE
Support for new Hugging Face models like Cerebras-GPT, Dolly and others.

### ISSUE THREAD

**Issue by Bakar31** [langchain-ai/langchain#4617]
### Feature request

It would be great if LangChain could support more HuggingFace embedding models. Prompt techniques don't work very well with currently available sentence transformer models.  Open-source-powered technology could benefit from the adoption of updated models like Cerebras-GPT and Dolly.

### Motivation

While creating a QA model with HuggingFace embedding and models, I find out that its performance could be with new models like Cerebras-GPT and Dolly.

### Your contribution

Yes, if someone guides me.

**Comment by Bennoo** [comment]
Hello, I am also interested in this, @Bakar31 what did you try ?
Is it possible to run Dolly2 as LLM and use embedding model (which one?) to query own documents and make vector search on these?
I tried with OpenAIs embeddings and GPT api endpoints, everything is working well but I would like to do the same with open models.. Is this your goal too?
