### ISSUE TITLE
Polars Dataframe Agent Needed

### ISSUE THREAD

**Issue by ekolawole** [langchain-ai/langchain#4620]
Knowing that Pandas and spark cannot be compared to the speed of Polars, please can you create a Polars Dataframe Agent? It is 15x faster than Pandas.

**Comment by devinhenkel** [comment]
I also agree that a Polars agent would be helpful and probably not too much work since the syntax is so similar to Pandas.

**Comment by JailsonS** [comment]
Agree. Polars agent would be amazing!

**Comment by ultrasonex** [comment]
Polars agent will be great addition t due to its faster speed and GPU support. Latest benchmark test shows the comparisons. https://pola.rs/posts/benchmarks/
