### ISSUE TITLE
Issue: Free Vector Database?

### ISSUE THREAD

**Issue by fading-bit** [langchain-ai/langchain#4621]
### Issue you'd like to raise.

Hi. I have used an integration of langchain with Pinecone, as well as ChromaDB. My question is whether you recommend any alternative vector database that is free?

**Comment by ofey404** [comment]
I tried Redisearch, but there are some issues.

Example see:

https://github.com/ofey404/WalkingShadows/blob/c1d87410bad5a365227aa26d083952f73219d48d/src/backend/services/world/internal/memory/test/test_memory_stream.py#L18-L20

**Comment by aws-avocado** [comment]
ChromaDB is free.

**Comment by lohithreddy2002** [comment]
quadrant also has a free version
