### ISSUE TITLE
`chromadb.errors.InvalidDimensionException` introduced somewhere between v0.0.123 and 0.0.167

### ISSUE THREAD

**Issue by emilesilvis** [langchain-ai/langchain#4627]
### System Info

v.0.0.167
MacOS 13.3.1 (a) (22E772610a)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.llms import AzureOpenAI
from langchain.chains import RetrievalQAWithSourcesChain
from flask import Flask, request, jsonify, render_template

embeddings = OpenAIEmbeddings(model="text-search-davinci-query-001",chunk_size=1)

persist_directory = "db"
db = Chroma(persist_directory=persist_directory, embedding_function=embeddings)

retriever = db.as_retriever()

llm = AzureOpenAI(deployment_name="foo")

chain = RetrievalQAWithSourcesChain.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

while True:
  question = input(f"Ask a question: ")
  answer = chain({"question": question}, return_only_outputs=True)
  print(answer)
```

### Expected behavior

In 0.0.123 the above snippet works. In 0.0.167, I get the following:

```
swlib.py", line 119, in _check_dimensionality
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Dimensionality of (1536) does not match index dimensionality (12288)
```

**Comment by czb154** [comment]
I have also encountered the same issue. It seems that the problem arises from the mismatch in the internal vector length between the previously stored database Chroma and the current one. Perhaps we can try creating a new database called Chroma to address this.

![impicture_20230630_155238](https://github.com/hwchase17/langchain/assets/56294230/e701e57b-8db5-4f9a-8128-1b1c05b68932)

**Comment by joefiorini** [comment]
@czb154 I also ran into this issue. I can confirm that deleting the database fixed it. I'm guessing it was caused by me changing the format of the input data, as I was testing an LLMs accuracy against the same texts in PDF and plain text.
