### ISSUE TITLE
GPT4All Python Bindings out of date [move to new multiplatform bindings]

### ISSUE THREAD

**Issue by AndriyMulyar** [langchain-ai/langchain#4628]
### Feature request

The official gpt4all python bindings now exist in the `gpt4all` pip package. [Langchain](https://python.langchain.com/en/latest/modules/models/llms/integrations/gpt4all.html) currently relies on the no-longer maintained pygpt4all package. Langchain should use the `gpt4all` python package with source found here: https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-bindings/python

### Motivation

The source at https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-bindings/python supports multiple OS's and platforms (other bindings do not). Nomic AI will be officially maintaining these bindings.

### Your contribution

I will be happy to review a pull request and ensure that future changes are PR'd upstream to langchains :)

**Comment by senbihan** [comment]
PR #4567 
Credit: [@Chae4ek](https://github.com/Chae4ek)
