### ISSUE TITLE
Rule based chatbot using LangChain

### ISSUE THREAD

**Issue by daiangan** [langchain-ai/langchain#4634]
### Issue you'd like to raise.

What is the best approach to create a rule based chatbot with LangChain?

Context: I need to create a chatbot that needs to collect some basic user's info at the beginning (things like name, email, phone) and then continue providing some general responses based on custom information.

Thanks in advance.

**Comment by delip** [comment]
@daiangan check out [`VectorStoreRetrieverMemory`](https://python.langchain.com/en/latest/modules/memory/types/vectorstore_retriever_memory.html)
