### ISSUE TITLE
langchain chroma vectorstore calls ChromaDB API incorrectly when ChromaDB is running in Docker

### ISSUE THREAD

**Issue by MattiPaivike** [langchain-ai/langchain#4674]
### System Info

```
langchain==0.0.168
chromadb==0.3.22
```

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Clone official ChromaDB repository and run their docker-compose environment.
```
git clone git@github.com:chroma-core/chroma.git
docker-compose up
```

Create a folder called `my_data` and create a `test.txt` file into it with some random text.
```
mkdir my_data
cd my_data
echo "testingtestingtesting" > test.txt
```

Script to reproduce issue:

```
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from chromadb.config import Settings

with open('my_data/test.txt', 'r', encoding="utf-8") as file:
    raw_text = file.read()

text_splitter = RecursiveCharacterTextSplitter(        
    chunk_size = 1000,
    chunk_overlap  = 0,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)

embeddings = OpenAIEmbeddings()

client_settings = Settings(
        chroma_api_impl="rest",
        chroma_server_host="localhost",
        chroma_server_http_port="8000"
    )

collection_name = "chroma_test"

vectorstore = Chroma.from_texts(embedding=embeddings, texts=texts, client_settings=client_settings, collection_name=collection_name)
```

Set necessary `OPENAI_API_KEY` environment variables and run the script.

This will result in an error:
`Exception: {"error":"InvalidUUID","message":"Could not parse chroma_test as a UUID"}`

The same issue will not happen if you run ChromaDB locally like this. Only when calling the actual API you then run in to the issue.
```
vectorstore = Chroma.from_texts(embedding=embeddings, texts=texts, persist_directory="db")
```

### Expected behavior

The expected behaviour would be that Langchain would call the ChromaDB API correctly with the `UUID` instead of the plaintext name of the collection.

See chromaDB sourcecode and their API `chromadb\server\fastapi\__init__.py`

Line `105`
```
self.router.add_api_route(
            "/api/v1/collections/{collection_id}/add",
            self.add,
            methods=["POST"],
            status_code=status.HTTP_201_CREATED,
        )
```

Line `196`

```
def add(self, collection_id: str, add: AddEmbedding) -> None:
        try:
            result = self._api._add(
                collection_id=_uuid(collection_id),
                embeddings=add.embeddings,
                metadatas=add.metadatas,
                documents=add.documents,
                ids=add.ids,
                increment_index=add.increment_index,
            )
        except InvalidDimensionException as e:
            raise HTTPException(status_code=500, detail=str(e))
        return result
```

Line `67`

```
def _uuid(uuid_str: str) -> UUID:
    try:
        return UUID(uuid_str)
    except ValueError:
        raise InvalidUUIDError(f"Could not parse {uuid_str} as a UUID")
```

**Comment by PhNyx** [comment]
Was having the same issue, this seems to happen if you are using the latest version of the docker image/server, but an older python module. 

<pre>pip install -U chromadb</pre>

And going to chromadb-0.3.23 fixed this issue.

For good measure I also created my own UUID 

<pre>
import uuid

# Generate a random UUID
random_uuid = uuid.uuid4()
print(random_uuid)
</pre>

and used that with collection_name=<UUID>

ie:

<pre>
vectordb = Chroma.from_documents(collection_name="******-********-******-*****", ....)
</pre>

**Comment by yunduancompany** [comment]
> Was having the same issue, this seems to happen if you are using the latest version of the docker image/server, but an older python module.
> 
> pip install -U chromadb
> And going to chromadb-0.3.23 fixed this issue.
> 
> For good measure I also created my own UUID
> 
> import uuid
> 
> # Generate a random UUID
> random_uuid = uuid.uuid4()
> print(random_uuid)
> and used that with collection_name=
> 
> ie:
> 
> vectordb = Chroma.from_documents(collection_name="******-********-******-*****", ....)

run "pip install -U chromadb" in the container or a venv?

**Comment by yunduancompany** [comment]
i saw the chromadb's version is 0.3.26

**Comment by Simone-98** [comment]
Remember:
when update your ChromaDB reload the Fastapi file at **http://localhost:8000/openapi.json** because there are small difference that can give you problem!
