### ISSUE TITLE
Issue: Set up a Chroma retriever for client-server configuration of Chroma

### ISSUE THREAD

**Issue by zigax1** [langchain-ai/langchain#4676]
### Issue you'd like to raise.

I am using Chroma's client-server configuration and I have trouble setting up a retriever for ConversationalRetrievalChain.from_llm() function.

I can't find anything related to this. Can someone guide me on how can I do that or if someone has any solution?

For the locally stored database you cust called db.as_retriever() and that was it.

But now, I can't find a solutionf or passing a retriever to from_llm() function.

My code snippet is:

```
`def askQuestion(self, thread_id, question):
        collection = self.chroma_client.get_collection(name="my_collection5", embedding_function=self.embedding)
        self.llm = ChatOpenAI(model_name=self.model_name, temperature=self.temperature, 
        openai_api_key=os.environ.get('OPENAI_API_KEY'))
        self.memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True,  
        output_key='answer')
        self.chain = ConversationalRetrievalChain.from_llm(self.llm, collection.as_retriever(),return_source_documents=True,verbose=VERBOSE, memory=self.memory)
       
        result = self.chain({"question": question})
        res_dict = {
            "answer": result["answer"],
        }

        res_dict["source_documents"] = []

        # add source docs
        for source in result["source_documents"]:
            res_dict["source_documents"].append({
                "page_content": source.page_content,
                "metadata":  source.metadata
            })

        return res_dict`
```

**Comment by tyatabe** [comment]
@zigax1 , have you found a solution for this? I'm, facing similar issues when using chroma in server/client mode

**Comment by bheather** [comment]
Hi dosubot, I'm also looking at this and trying to move from a local vectorstore or persistant vectorstor to a vectorstor created remotely and accessed through the chromadb.HttpClient() call.  The langchain vectorstore contains interfaces for from_documents() and from_texts() and there is documentation that refers to fromExistingCollection() but this last is not present in the code.  Can you point me at the approach to create an Retriever interface from the HttpClient?
