### ISSUE TITLE
Issue: TypeError: string indices must be integers when retrieving messages from PostgreSQL

### ISSUE THREAD

**Issue by lordskyzw** [langchain-ai/langchain#4684]
### Issue you'd like to raise.

I encountered a `TypeError: string indices must be integers` error when using the library to retrieve chat messages from a PostgreSQL database. This error occurs specifically in the `messages_from_dict` function.

Upon further investigation, it appears that the error arises when trying to access the "type" field of a message dictionary. The `messages_from_dict` function is expected to convert a list of dictionaries into a list of `BaseMessage` objects, but it fails to handle the dictionary properly.

To reproduce the issue, follow these steps:
1. Set up the library to use a PostgreSQL database as the chat message history storage.
2. Start a conversation and exchange messages.
3. Retrieve the chat history using the `messages` property of the `PostgresChatMessageHistory` class.

The error occurs when the `messages` property executes the following code snippet:

```python
items = [record["message"] for record in self.cursor.fetchall()]
messages = messages_from_dict(items)
The messages_from_dict function attempts to convert each dictionary in the items list to a BaseMessage object. However, it fails to properly handle the dictionary structure, resulting in the TypeError.



Environment:

    Library version: [Specify library version]
    Python version: [Specify Python version]
    PostgreSQL version: [Specify PostgreSQL version]
    Operating system: [Specify operating system]

### Suggestion:

To resolve this issue, the implementation of the messages_from_dict function needs to be reviewed and updated accordingly. It should correctly handle the structure of each message dictionary and create BaseMessage objects with the expected attributes.

Additionally, it would be helpful to provide clearer documentation or examples on how to set up the PostgreSQL chat message history and ensure the expected structure of the messages stored in the message_store table.

**Comment by brandonhresko** [comment]
have you found a fix for this? running into the same issue.

**Comment by brandonhresko** [comment]
nvm the error was with how i was storing messages in my database, fixed.

**Comment by xbreid** [comment]
Can i ask how you ended up storing messages in Postgres? facing the same issue
