### ISSUE TITLE
Qdrant filtering methods

### ISSUE THREAD

**Issue by dagthomas** [langchain-ai/langchain#4718]
### Feature request

The qdrant vector store has "must" in filter, is it possible to add "must_not" and/or "should" as well? 

Ref: https://qdrant.tech/documentation/filtering/

### Motivation

Having a filter is really nice, but its hard to use row level authorization without "must_not" 

So we can say "must" include ID and "must_not" include ID2

To be able to filter correctly

### Your contribution

I am a front-end developer, and hoping someone with python competance can handle this.

**Comment by hp0404** [comment]
What if you changed the API so a user passes the `rest.Filter` directly (instead of `MetadataFilter`)? This way, you won't need to implement different filtering options (must, must_not, nested, etc.)
Qdrant documentation shows how to do that and gives Python examples anyways...

**Comment by YLFxGen** [comment]
I also faced an issue when trying to do filtering with qdrant. Here is how I solved it temporarily. (#5073 ) It should allow you to pass any filters provided by qdrant. Just copy paste their python examples.

**Comment by kacperlukawski** [comment]
@dagthomas @hp0404 @YLFxGen This has been implemented in #5446.
