### ISSUE TITLE
Summarization Notebook: No module named 'tiktoken'

### ISSUE THREAD

**Issue by garystafford** [langchain-ai/langchain#4728]
### System Info

langchain: 0.0.169
Python: 3.10.10
MacOS: 12.6.5 (21G531)

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When running the notebook featured here: [https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html](https://python.langchain.com/en/latest/modules/chains/index_examples/summarize.html), the following cell will fail.

```python
chain = load_summarize_chain(llm, chain_type="map_reduce")
chain.run(docs)
```

Unless you have pre-installed `tiktoken`, you will receive an error:
```text
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File [/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py:464](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.10/site-packages/langchain/llms/openai.py:464), in BaseOpenAI.get_num_tokens(self, text)
    463 try:
--> 464     import tiktoken
    465 except ImportError:

ModuleNotFoundError: No module named 'tiktoken'
```

Installing `tiktoken` solves the immediate issue.

```python
%pip install tiktoken
```

### Expected behavior

The notebook runs without errors.

**Comment by someshnaman** [comment]
Hello @garystafford, according to the project requirements, Python 3.9 is the appropriate version. By using Python 3.9, the problem would be resolved.
![image](https://github.com/hwchase17/langchain/assets/66522077/bebef4d3-742c-4d58-943a-bc4203854c79)
