### ISSUE TITLE
How to stop the stream? and does it stop the openai charging?

### ISSUE THREAD

**Issue by mysteriousHerb** [langchain-ai/langchain#4743]
### Issue you'd like to raise.

How do I stop the stream when using callbacks like async callback?

When I stop the stream, does the openAI still charges the remainders of the generation?

**Comment by AlayaQQ** [comment]
I'm also curious, have you found a solution?

**Comment by stevenmilstein** [comment]
I just came across these:

- [Streaming | 🦜️🔗 Langchain](https://js.langchain.com/docs/modules/model_io/models/chat/how_to/streaming)
- [Cancelling requests | 🦜️🔗 Langchain](https://js.langchain.com/docs/modules/model_io/models/chat/how_to/cancelling_requests)

Happy Streaming :-)

**Comment by sandywk** [comment]
@stevenmilstein How to cancel in Python

**Comment by calls9-amirbraham** [comment]
any solutions. ?

**Comment by 4skinSkywalker** [comment]
Anything on this? My chat app has a stop button that unsubscribes the user from the completion call and it would be nice to prevent any more token to be generated (to save money obviously)
