### ISSUE TITLE
如何修改langchain包默认访问api.openai.com请求地址，我需要通过代理访问api.openai.com 

### ISSUE THREAD

**Issue by liuyang77886** [langchain-ai/langchain#4759]
### Feature request

本地局域网网络受限，需要通过反向代理访问api.openai.com地址，请问如何修改langchain包访问chatgpt的地址为我的代理地址

### Motivation

本地局域网网络受限，需要通过反向代理访问api.openai.com地址，请问如何修改langchain包访问chatgpt的地址为我的代理地址

### Your contribution

我使用的项目是gpt4-pdf-chatbot-langchain

**Comment by liaokongVFX** [comment]
You can set the openai API environment variable "OPENAI_API_BASE".

Related codes: https://github.com/openai/openai-python/blob/d6fa3bfaae69d639b0dd2e9251b375d7070bbef1/openai/__init__.py#L48

**Comment by FlowerWrong** [comment]
Just pass this parameter openai_api_base see https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py#L148

**Comment by zerrymore11** [comment]
The `gpt4-pdf-chatbot-langchain` project is an applicataion of langchian's typescript version. I have not found the interface to modify the host, i.e., the attribute `openai_api_base`.

**Comment by harveymx** [comment]
> The `gpt4-pdf-chatbot-langchain` project is an application of langchian's typescript version. I have not found the interface to modify the host, i.e., the attribute `openai_api_base`.

with langchainjs,It can be :

`const model = new ChatOpenAI({
    configuration: { baseURL:"YOUR PROXY URL "},
    apiKey: "YOUR API KEY",
    model:"XXX"
});`

**Comment by OldDream** [comment]
> > The `gpt4-pdf-chatbot-langchain` project is an application of langchian's typescript version. I have not found the interface to modify the host, i.e., the attribute `openai_api_base`.
> 
> with langchainjs,It can be :
> 
> `const model = new ChatOpenAI({ configuration: { baseURL:"YOUR PROXY URL "}, apiKey: "YOUR API KEY", model:"XXX" });`

In "@langchain/openai": "^0.3.16",  it is :
` configuration:{
    basePath: "YOUR PROXY URL "
  },`
