### ISSUE TITLE
The exception 'SQLDatabaseSequentialChain or SQLDatabaseChain configuration parameter use_query_checker=True' occurred.

### ISSUE THREAD

**Issue by liutizhong** [langchain-ai/langchain#4768]
### System Info

env python == 3.10.10
langchain==0.0.170
mysql==5.7

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
`
db_chain = SQLDatabaseSequentialChain.from_llm(llm,
                            db,
                            verbose=True,
                            return_direct=True,
                            use_query_checker=True,
                            return_intermediate_steps=True)

with get_openai_callback() as cb:
    restult=db_chain("New energy vehicle sales in 2022?")

print(restult)
print(cb)

`

Expected behavior
Entering new SQLDatabaseSequentialChain chain...
Table names to use:
['t_passenger_car_monthly_sales']

Entering new SQLDatabaseChain chain 
New energy vehicle sales in 2022?
SQLQuery:The original query seems correct and does not contain any of the common mistakes listed. Therefore, the original query is:
SELECT SUM(monthly_retail_sales) AS total_sales FROM t_passenger_car_monthly_sales WHERE passenger_car_type = 'passenger_car' AND yearly = 2022
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
File [~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1900] in Connection._execute_context(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)
   1899     if not evt_handled:
-> 1900         self.dialect.do_execute(
   1901             cursor, statement, parameters, context
   1902         )
   1904 if self._has_events or self.engine._has_events:

File [~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/sqlalchemy/engine/default.py:736], in DefaultDialect.do_execute(self, cursor, statement, parameters, context)
    735 def do_execute(self, cursor, statement, parameters, context=None):
--> 736     cursor.execute(statement, parameters)

File [~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pymysql/cursors.py:158], in Cursor.execute(self, query, args)
    156 query = self.mogrify(query, args)
--> 158 result = self._query(query)
    159 self._executed = query

File [~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pymysql/cursors.py:325] in Cursor._query(self, q)
    324 self._clear_result()
--> 325 conn.query(q)
    326 self._do_get_result()

File [~/opt/anaconda3/envs/py310/lib/python3.10/site-packages/pymysql/connections.py:549], in Connection.query(self, sql, unbuffered)
    548 self._execute_command(COMMAND.COM_QUERY, sql)
...
ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'The original query seems correct and does not contain any of the common mistakes' at line 1")
[SQL: The original query seems correct and does not contain any of the common mistakes listed. Therefore, the original query is:

SELECT SUM(monthly_retail_sales) AS total_sales FROM t_passenger_car_monthly_sales WHERE passenger_car_type = 'passenger_car' AND yearly = 2022]
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by liutizhong** [comment]
I have identified the issue. In the base.py file,
```
sql_cmd = self.llm_chain.predict(
                callbacks=_run_manager.get_child(),
                **llm_inputs,
            ).strip()
```
the sql_cmd variable is not returning only SQL code, but also some descriptive information:
SQLQuery: 
"""
 SELECT t1.monthly, t1.new_energy_vehicles_retail_sales, t2.new_energy_vehicles_retail_sales AS 'last_year_sales', 
((t1.new_energy_vehicles_retail_sales - t2.new_energy_vehicles_retail_sales) / t2.new_energy_vehicles_retail_sales) * 100 AS 'YoY_growth'
FROM t_passenger_car_monthly_sales t1
JOIN t_passenger_car_monthly_sales t2 ON t1.monthly = t2.monthly AND t1.yearly = 2023 AND t2.yearly = 2022
WHERE t1.new_energy_vehicles_retail_sales IS NOT NULL AND t2.new_energy_vehicles_retail_sales IS NOT NULL
ORDER BY t1.monthly

Results:
monthly new_energy_vehicles_retail_sales  last_year_sales Yoy_growth
1 2 19.6  -89.79591836734694
2 2 - -
10  2 33.2  -93.99397590361446
"""

When use_query_checker=True, the checked_sql_command variable is also returning additional information:

```
checked_sql_command: str = query_checker_chain.predict(
                    callbacks=_run_manager.get_child(), **query_checker_inputs
                ).strip()
```

print checked_sql_command: 
"""
The original query looks correct and does not contain any of the common mistakes listed. Therefore, the original query is reproduced below:

SELECT t1.monthly, t1.new_energy_vehicles_retail_sales, t2.new_energy_vehicles_retail_sales AS 'last_year_sales', 
((t1.new_energy_vehicles_retail_sales - t2.new_energy_vehicles_retail_sales) / t2.new_energy_vehicles_retail_sales) * 100 AS 'YoY_growth'
FROM t_passenger_car_monthly_sales t1
JOIN t_passenger_car_monthly_sales t2 ON t1.monthly = t2.monthly AND t1.yearly = 2023 AND t2.yearly = 2022
WHERE t1.new_energy_vehicles_retail_sales IS NOT NULL AND t2.new_energy_vehicles_retail_sales IS NOT NULL
ORDER BY t1.monthly
"""

A temporary solution is to split the strings using specific delimiters, such as "Results:" and ":".

if "Result" in sql_cmd:
                sql_cmd = sql_cmd.split("Results:", 1)[0] 


if ":" in checked_sql_command:
                    checked_sql_command=checked_sql_command.split(':',1)[1]

However, it would be beneficial to find a more robust solution. Thank you for bringing this to the community's attention.

**Comment by RickMartian** [comment]
> I have identified the issue. In the base.py file,
> 
> ```
> sql_cmd = self.llm_chain.predict(
>                 callbacks=_run_manager.get_child(),
>                 **llm_inputs,
>             ).strip()
> ```
> 
> the sql_cmd variable is not returning only SQL code, but also some descriptive information: SQLQuery: """ SELECT t1.monthly, t1.new_energy_vehicles_retail_sales, t2.new_energy_vehicles_retail_sales AS 'last_year_sales', ((t1.new_energy_vehicles_retail_sales - t2.new_energy_vehicles_retail_sales) / t2.new_energy_vehicles_retail_sales) * 100 AS 'YoY_growth' FROM t_passenger_car_monthly_sales t1 JOIN t_passenger_car_monthly_sales t2 ON t1.monthly = t2.monthly AND t1.yearly = 2023 AND t2.yearly = 2022 WHERE t1.new_energy_vehicles_retail_sales IS NOT NULL AND t2.new_energy_vehicles_retail_sales IS NOT NULL ORDER BY t1.monthly
> 
> Results: monthly new_energy_vehicles_retail_sales last_year_sales Yoy_growth 1 2 19.6 -89.79591836734694 2 2 - - 10 2 33.2 -93.99397590361446 """
> 
> When use_query_checker=True, the checked_sql_command variable is also returning additional information:
> 
> ```
> checked_sql_command: str = query_checker_chain.predict(
>                     callbacks=_run_manager.get_child(), **query_checker_inputs
>                 ).strip()
> ```
> 
> print checked_sql_command: """ The original query looks correct and does not contain any of the common mistakes listed. Therefore, the original query is reproduced below:
> 
> SELECT t1.monthly, t1.new_energy_vehicles_retail_sales, t2.new_energy_vehicles_retail_sales AS 'last_year_sales', ((t1.new_energy_vehicles_retail_sales - t2.new_energy_vehicles_retail_sales) / t2.new_energy_vehicles_retail_sales) * 100 AS 'YoY_growth' FROM t_passenger_car_monthly_sales t1 JOIN t_passenger_car_monthly_sales t2 ON t1.monthly = t2.monthly AND t1.yearly = 2023 AND t2.yearly = 2022 WHERE t1.new_energy_vehicles_retail_sales IS NOT NULL AND t2.new_energy_vehicles_retail_sales IS NOT NULL ORDER BY t1.monthly """
> 
> A temporary solution is to split the strings using specific delimiters, such as "Results:" and ":".
> 
> if "Result" in sql_cmd: sql_cmd = sql_cmd.split("Results:", 1)[0]
> 
> if ":" in checked_sql_command: checked_sql_command=checked_sql_command.split(':',1)[1]
> 
> However, it would be beneficial to find a more robust solution. Thank you for bringing this to the community's attention.

Really appreciated your help!! I think you could open a PR to implement this solution for everyone since we are currently in July and it's not fixed yet.

**Comment by Huwj-Ones** [comment]
@liutizhong @RickMartian 

Good find. PR this?!

**Comment by Huwj-Ones** [comment]
https://github.com/langchain-ai/langchain/pull/8100#issue-1816406854

**Comment by ishansmishra** [comment]
Is there any chance this can be solved with invoking?
