### ISSUE TITLE
KeyError: 'tools' when initialize_agent with python_repl tool

### ISSUE THREAD

**Issue by xulicong** [langchain-ai/langchain#4769]
### System Info

windows 10 

### Who can help?

@vowelparrot @hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I just follow the fake llm toturial:
https://python.langchain.com/en/latest/modules/models/llms/examples/fake_llm.html
my code is as flowing:

from langchain.llms.fake import FakeListLLM
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.agents import AgentType
tools = load_tools(["python_repl"])
responses=[
    "Action: Python REPL\nAction Input: print(2 + 2)",
    "Final Answer: 4"
]
llm = FakeListLLM(responses=responses)
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
agent.run("whats 2 + 2")

### Expected behavior

code works like the official toturial

**Comment by imeckr** [comment]
Update the langchain version to latest version. This issue was resolved in a recent commit https://github.com/hwchase17/langchain/pull/4137

**Comment by imeckr** [comment]
It seems to working with `0.0.170` for me. Could you provide the exception trace again ?
<img width="851" alt="image" src="https://github.com/hwchase17/langchain/assets/7942293/0c02a3b1-4944-4257-a05e-ebf90574e540">

**Comment by xulicong** [comment]
@imeckr 
Traceback (most recent call last):
  File "D:\TestScript\TestScript\search\search_engine\langchain_demo\test.py", line 11, in <module>
    agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
  File "D:\Python310\lib\site-packages\langchain\agents\initialize.py", line 64, in initialize_agent
    return AgentExecutor.from_agent_and_tools(
  File "D:\Python310\lib\site-packages\langchain\agents\agent.py", line 639, in from_agent_and_tools
    return cls(
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1064, in pydantic.main.validate_model
  File "D:\Python310\lib\site-packages\langchain\agents\agent.py", line 647, in validate_tools
    tools = values["tools"]
KeyError: 'tools'

**Comment by vowelparrot** [comment]
Thank you for raising this issue! I'm having trouble reproducing. The error comes when running this exact code?

```
from langchain.llms.fake import FakeListLLM
from langchain.agents import load_tools
from langchain.agents import initialize_agent
from langchain.agents import AgentType
tools = load_tools(["python_repl"])
responses=[
"Action: Python REPL\nAction Input: print(2 + 2)",
"Final Answer: 4"
]
llm = FakeListLLM(responses=responses)
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
agent.run("whats 2 + 2")
```
