### ISSUE TITLE
Improve Airbyte loader to help LLM differentiate entities

### ISSUE THREAD

**Issue by flash1293** [langchain-ai/langchain#4776]
### Feature request

The Airbyte loader should place some separator token between attributes from different records in the final document to help the LLM associating the right attributes with each other

### Motivation

The Airbyte loaders loads data from the Airbyte local JSON destination into documents. As Airbyte's atomic unit is a record in the form of a JSON object, the Airbyte loader is stringifying these into the form of `key: value\n`. However, if there are a lot of records, the final document looks like this:

Raw data
```
{"_airbyte_ab_id":"f0bcb1da-baaa-4f09-b210-68fa5747ad7c","_airbyte_emitted_at":1684226166938,"_airbyte_data":{"id":91,"make":"Pontiac","model":"Vibe","year":2006,"price":12134,"created_at":"2021-01-11T22:30:14+00:00"}}
{"_airbyte_ab_id":"cde6ea19-3f93-4f7a-9042-f5836ca752ac","_airbyte_emitted_at":1684226166938,"_airbyte_data":{"id":92,"make":"Volkswagen","model":"Eos","year":2011,"price":53128,"created_at":"2021-01-12T23:25:06+00:00"}}
{"_airbyte_ab_id":"dfbc15a5-bcb7-4676-8615-6341d29b21d3","_airbyte_emitted_at":1684226166939,"_airbyte_data":{"id":93,"make":"Mazda","model":"Mazdaspeed6","year":2007,"price":90902,"created_at":"2021-12-29T14:29:03+00:00"}}
```

Document:
```
id: 91
make: Pontiac
model: Vibe
year: 2006
price: 12134
created_at: 2021-01-11T22:30:14+00:00
id: 92
make: Volkswagen
model: Eos
year: 2011
price: 53128
created_at: 2021-01-12T23:25:06+00:00
id: 93
make: Mazda
model: Mazdaspeed6
year: 2007
price: 90902
created_at: 2021-12-29T14:29:03+00:00
```

Running a `RetrievalQA` on this document asking for `How much is a Volkswagen Eos?`, the final answer is `The price of a Volkswagen Eos is 12134` which is wrong (it's the price of the Pontiac right above it, but that's hard to tell from the list of attributes)

Adding a separator between the records, the document would look like this:

```
id: 91
make: Pontiac
model: Vibe
year: 2006
price: 12134
created_at: 2021-01-11T22:30:14+00:00
-end of record-
id: 92
make: Volkswagen
model: Eos
year: 2011
price: 53128
created_at: 2021-01-12T23:25:06+00:00
-end of record-
id: 93
make: Mazda
model: Mazdaspeed6
year: 2007
price: 90902
created_at: 2021-12-29T14:29:03+00:00
```

The same chain and question now gives the final answer `The price of a Volkswagen Eos is 53128.` which is correct.

Alternatively we could completely change the stringification strategy here and instead of producing key-value pairs serializing the array of records as YAML:
* Simple to do as there are libs for that
* Still little overhead for structural tokens (way less than JSON)
* Also has record-separators (the `-` and indentation)
* LLMs know how YAML works so it's probably beneficial for interpreting structure in complex nested records

### Your contribution

Happy to put together a PR for this, both options explained above are simple to do.

**Comment by hwchase17** [comment]
make sense - i think either sounds good! Another option would be to have the document loader actually load each record as a separate document. this is similar to what we do for the csv loader (https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/csv_loader.py). i think it has the added benefit of basically encapulating each one as its own thing, and allowing some of the fields to be metadata to filter on

**Comment by flash1293** [comment]
Thinking about it a bit more, this should probably be configurable. Depending on the source a single record can be a lot of things - sometimes it’s more like a wiki page and retrieving them individually makes the most sense, sometimes it’s something like a chat message and which makes more sense in context and the existing approach is better suited. I guess the user should be able to choose
