### ISSUE TITLE
ChatOpenAI: Number of parallel jobs in the MapReduce chain

### ISSUE THREAD

**Issue by swersig** [langchain-ai/langchain#4782]
### Issue you'd like to raise.

Hi guys,

it is my understanding that for GPT4 we have to use the ChatOpenAI api. Due to the more restrictive rate limit for GPT4 the use of map_reduce chains seems very limited. 

### Suggestion:

Provide a configurable batch_size - like in #1073 - for the ChatOpenAI api

**Comment by alberto-bracci** [comment]
should this be reopened? batch_size doesn't work as argument as of 0.0.313
