### ISSUE TITLE
Making the chain more robust (self-correct)

### ISSUE THREAD

**Issue by assassin808** [langchain-ai/langchain#4835]
### Feature request

Wrong outputs of the model will raise some exception. So, it may be better to provide clear feedback to the LLM on the specific issue (i.e. incorrect formatting). This would allow the LLM to do self-adjustments and retry, making it robust.

### Motivation

Since when I was using the chain to test my own searching tool, if the result is in other language (not english), the model fail to exactly follow the "thought-action" pattern.

### Your contribution

Not yet

**Comment by egeres** [comment]
I think this should be a core langchain feature but I can't find any info about it...
