### ISSUE TITLE
SQLDatabaseChain returned for more than just the expected answer

### ISSUE THREAD

**Issue by duyixian1234** [langchain-ai/langchain#4840]
### System Info

- Python 3.11.3 on Windows 11
-  langchain==0.0.171

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. create llm, SQLDatabase and the SQLDatabaseChain instances;
2. query database with natural language
3. the SQLDatabaseChain would return more content (Normally it would add a new quesition below the anwser)
![image](https://github.com/hwchase17/langchain/assets/3953615/eba89b5d-0744-4339-a1fb-26265b716a1f)

### Expected behavior

It seem that if we modify the 111 line  of  `langchain\chains\sql_database\base.py` add add `"\nQuestion:"` as another stop phase, SQLDatabase Chain would works well.
![image](https://github.com/hwchase17/langchain/assets/3953615/043d1c4e-65ea-483e-9939-8f3bdfbf58fe)
![image](https://github.com/hwchase17/langchain/assets/3953615/5be9376b-635e-4336-a578-29d527e87aea)

**Comment by levalencia** [comment]
same here
