### ISSUE TITLE
Support for https://github.com/microsoft/guidance

### ISSUE THREAD

**Issue by paplorinc** [langchain-ai/langchain#4843]
### Feature request

The [Microsoft Guidance Repository](https://github.com/microsoft/guidance/blob/main/README.md) is a tool designed to enhance the control over modern language models. It allows for a more effective and efficient control than traditional prompting or chaining. It offers features like simple, intuitive syntax based on Handlebars templating, rich output structure with multiple generations, selections, conditionals, tool use, etc.

### Motivation

Based on the description and examples (templating, hidden response parts, well-formed response variables), integration of `guidance` with `langchain` would be very useful addition.

### Your contribution

Given some guidance (pun, intended), I can imagine contributing with a PR myself.

**Comment by alonroth** [comment]
I agree it seems like it could be very useful

**Comment by tybalex** [comment]
It'd be nice to use guidance to further improve the prompting in `Chain` or `Agent`.
