### ISSUE TITLE
Is APIPropertyLocation.HEADER supported?

### ISSUE THREAD

**Issue by ManeshNarayan** [langchain-ai/langchain#4854]
[SUPPORTED_LOCATIONS](https://github.com/hwchase17/langchain/blob/720ac49f4237e8c177ac65a27903da6215fe91c8/langchain/tools/openapi/utils/api_models.py#L46) does not list APIPropertyLocation.HEADER as supported. However the comments under APIPropertyLocation next to [COOKIE](https://github.com/hwchase17/langchain/blame/720ac49f4237e8c177ac65a27903da6215fe91c8/langchain/tools/openapi/utils/api_models.py#L28) seems to indicate that HEADER is supported as it explicitly states that Cookie is not supported. Any clarifications on this?

**Comment by balvisio** [comment]
Reopening this issue. Is there any specific reason HEADERS is not a supported location when generating the openai function definition

**Comment by balvisio** [comment]
Created PR to fix this: https://github.com/langchain-ai/langchain/pull/21946
