### ISSUE TITLE
Langchain agent is not continuing the entire flow of execution

### ISSUE THREAD

**Issue by gs-vkrishnasrujan** [langchain-ai/langchain#4865]
### Issue you'd like to raise.

I am using custom tools. I used zero shot react description agent and it was not giving the final answer. It stopped after using 1st tool. 

So, I created a custom agent with custom examples in the prompt. It is still behaving the same way.

This is the output of the agent executer for one of the examples:
statement = 'a query to get the average outcome variable score of all the CSAT responses'
agent_executor.run(statement)
Output:
> Entering new AgentExecutor chain...
Thought : I need to paraphrase the statement to add more context.
Action : StatementFormattingTool[a query to get the average outcome variable score of all the CSAT responses]
Observation : Get the average outcome variable score for all CSAT responses from the kda_distribution_log_02c581c9912a4ca1af7a67cd46324cf1_llm_test table.

Its has to use SQLGenerationTool to get the query. It stopped after using the first tool. It is happening every time with other statemennts as well.

**Comment by gs-vkrishnasrujan** [comment]
System info : python: 3.11.3 langchain: 0.0.128

**Comment by erikriverson** [comment]
Were you ever able to resolve this? I face the same issue.

**Comment by cyclux** [comment]
I am having the same issue. Do you happen to have any updates on a solution?

**Comment by omiguelpinheiro** [comment]
Bump

**Comment by daniel-quiroga** [comment]
bump

**Comment by DLOVRIC2** [comment]
bump
