### ISSUE TITLE
PythonREPL agent toolkit does not recognize PythonREPL as a valid tool

### ISSUE THREAD

**Issue by ethanjevvell** [langchain-ai/langchain#4889]
### System Info

Langchain version: 0.0.172
Platform: Linux (Ubuntu)

### Who can help?

@vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When trying to use a python agent for simple queries, the agent often does not recognize Python REPL as a valid tool:

```
> Entering new AgentExecutor chain...
I can write a function to generate the nth fibonacci number and then call it with n=4.
Action: [Python REPL]
Action Input:

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)

print(fibonacci(4))

Observation: [Python REPL] is not a valid tool, try another one.
```

My instantiation of the agent:

```
custom_prefix = PREFIX + "When writing a code block, do not include the word 'python' after the first three ticks. You must graph your findings and save a .png of the graph on the local file system at [a path on my local machine]. The corpus consists of .txt files at this directory: [another path on my machine]."

python_agent = create_python_agent(llm=llm, tool=PythonREPLTool(), verbose=True, max_tokens=1000, prefix=custom_prefix)

python_agent("What are the top 10 bi-grams in the corpus? Only parse the .txt files. Translate the final n-grams to English for the chart.")
```

Model then gets stuck in a loop trying to use Python REPL. I included instructions in `custom_prefix` because the model repeatedly got this error, too:

```
> Entering new AgentExecutor chain...
I need to read in all the .txt files in the corpus and tokenize them into bi-grams. Then I need to count the frequency of each bi-gram and return the top 10.
Action: Python REPL
Action Input:
```python
import os
import nltk
from collections import Counter
from nltk import word_tokenize
from nltk.util import ngrams

corpus_dir = a directory on my machine
files = [os.path.join(corpus_dir, f) for f in os.listdir(corpus_dir) if f.endswith('.txt')]

bi_grams = []
for file in files:
    with open(file, 'r') as f:
        text = f.read()
        tokens = word_tokenize(text)
        bi_grams += ngrams(tokens, 2)

bi_gram_freq = Counter(bi_grams)
top_10_bi_grams = bi_gram_freq.most_common(10)
...
print(top_10_bi_grams)
```NameError("name 'python' is not defined")
```

### Expected behavior

I expect the Python agent to recognize PythonREPL as a valid tool. In fact, sometimes it does! But more often than not, it does not recognize PythonREPL as a tool. The query I included in the above code snippet worked maybe once in every 50 tries.

**Comment by vowelparrot** [comment]
Thanks for flagging. The model being used isn't outputting the expected format. 

In the first case, it's adding brackets `[]` aruond the name. You could relax the output parser of the agent to account for this.

In the second case, it's adding the `python` word in the markdown, which can be handled in the parser as well.

**Comment by ethanjevvell** [comment]
Thanks @vowelparrot. This appears to be an issue with the base Python agent toolkit, then, as I am not using any customization (aside from changing the prefix in an attempt to fix the bugs I mentioned).

**Comment by vowelparrot** [comment]
What LLM are you using?

**Comment by ethanjevvell** [comment]
@vowelparrot gpt-3.5-turbo

Apologies for not mentioning this sooner

**Comment by vowelparrot** [comment]
Ya we have to tune everything for chat models. Turbo doesn't work well with a lot of the older prompts . Thanks for flagging

**Comment by nai-kon** [comment]
>it's adding brackets [] aruond the name. You could relax the output parser of the agent to account for this.

I'm using create_pandas_dataframe_agent() with GPT3.5 turbo  and same problem happened.
I debugged the Agent prompt. I found below instruction in prompt.
`Action: the action to take, should be one of [python_repl_ast]`

I think it caused the problem of "[] aruond the name". 
If there is only one tool, the prompt should be more simple like below.
`Action: should be python_repl_ast`

**Comment by catskytw** [comment]
I'm not sure what I've met is same or not.
The console keeps showing: 

```
Observation: <A sentence of AI's thought> is not a valid tool, try another one.
Thought:
```

appreciate if providing any suggestion or work around.

**Comment by javedafrozpwc** [comment]
I am also facing the same issue. Any updates on this issue?

**Comment by K-Jadeja** [comment]
> > it's adding brackets [] aruond the name. You could relax the output parser of the agent to account for this.
> 
> I'm using create_pandas_dataframe_agent() with GPT3.5 turbo and same problem happened. I debugged the agent prompt and found below instruction. `Action: the action to take, should be one of [python_repl_ast]`
> 
> I think this caused the problem of "[] aruond the name". If there is only one tool, the agent prompt should be more simple like below. `Action: the action to take, should be python_repl_ast`

How do i change the prompt? Thanks

**Comment by dushyantnagarhumanli** [comment]
Use python_repl_ast to solve the equation for \( x \). is not a valid tool, try one of [python_repl_ast]
