### ISSUE TITLE
Redis Vectorstore: Redis.from_texts_return_keys() got multiple values for argument 'cls'

### ISSUE THREAD

**Issue by iamadhee** [langchain-ai/langchain#4896]
### System Info

```
Python 3.10.4
langchain==0.0.171
redis==3.5.3
redisearch==2.1.1
```

### Who can help?

@tylerhutcherson

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I was able to override issue #3893 by temporarily disabling the ` _check_redis_module_exist`, post which I'm getting the below error when calling the `from_texts_return_keys` within the `from_documents` method in Redis class. Seems the argument `cls` is not needed in the `from_texts_return_keys` method, since it is already defined as a classmethod.

```
File "/workspaces/chatdataset_backend/adapters.py", line 96, in load
    vectorstore = self.rds.from_documents(documents=documents, embedding=self.embeddings)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/base.py", line 296, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/redis.py", line 448, in from_texts
    instance, _ = cls.from_texts_return_keys(
TypeError: Redis.from_texts_return_keys() got multiple values for argument 'cls'
```

### Expected behavior

Getting rid of cls argument from all the `Redis` class methods wherever required. Was able to solve the issue with this fix.

**Comment by tylerhutcherson** [comment]
This is a high priority issue. I ran into this myself yesterday. 

Thanks for creating the issue.

**Comment by iamadhee** [comment]
Thanks, @tylerhutcherson If you could assign this to me, I can solve it along with #4899 and merge it.

**Comment by tylerhutcherson** [comment]
Yes, please do. Tag me in the PR review!

**Comment by tylerhutcherson** [comment]
@iamadhee FYI https://github.com/hwchase17/langchain/pull/4

**Comment by iamadhee** [comment]
@tylerhutcherson Have added #4932
