### ISSUE TITLE
Breaking Changes | OpenAI Callback

### ISSUE THREAD

**Issue by jordanparker6** [langchain-ai/langchain#4897]
### System Info

langchain="^0.0.172"

The `from langchain.callbacks import get_openai_callback` callback seems to have broken in a new release. It was working when I was on "^0.0.158". The callback is working but no token or costs are appearing. 

```
2023-05-18T02:41:37.844174Z [info     ] openai charges                 [service.openai] completion_tokens=0 prompt_tokens=0 request_id=4da70135655b48d59d7f1e7528733f61 successful_requests=1 total_cost=0.0 total_tokens=0 user=user_2PkD3ZUhCdmBHiFPNP9tPZr7OLA
```

I was experiencing another breaking change with #4717 that seems to have been resolved. 

### Who can help?

@agola11  @vowelparrot 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

```py
import structlog
from langchain.callbacks import get_openai_callback

log = structlog.getLogger("main")

with get_openai_callback() as cb:
    result = await agent.acall({ "input": body.prompt }, return_only_outputs=True)
openai_logger.info(
    "openai charges", 
    prompt_tokens=cb.prompt_tokens, 
    completion_tokens=cb.completion_tokens, 
    total_tokens=cb.total_tokens,
    total_cost=cb.total_cost, 
    successful_requests=cb.successful_requests,
    user=user_id
)
```

### Expected behavior

I was expecting tokens and costs to token counts to appear.

**Comment by jonosooty** [comment]
Also ran into this today.

**Comment by jordanparker6** [comment]
Reproduced it with the following

```py
import asyncio
import os
from pydantic import BaseModel
from dotenv import load_dotenv
from langchain.tools import StructuredTool
from langchain.chat_models import ChatOpenAI
from langchain.callbacks import get_openai_callback
from langchain.llms import OpenAI
from langchain.memory import ConversationBufferWindowMemory
from langchain.memory import ChatMessageHistory
from langchain.agents import StructuredChatAgent
from langchain.agents import AgentExecutor
from langchain.prompts import MessagesPlaceholder

load_dotenv()

def print_cost(cb):
    print(
        dict(
        prompt_tokens=cb.prompt_tokens, 
        completion_tokens=cb.completion_tokens, 
        total_tokens=cb.total_tokens,
        total_cost=cb.total_cost, 
        successful_requests=cb.successful_requests,
            )
    )

def load_tools():
    def every(*args, **kwargs):
        return "Use me for everything!"
    async def aevery(*args, **kwargs):
        return "Use me for everything!"
    
    class Schema(BaseModel):
        question: str

    return [
        StructuredTool(
            name="everything_tool",
            func=every,
            coroutine=aevery,
            args_schema=Schema,
            description="Use me for everything!"
        )
    ]

def load_structured_chat_agent(memory, tools, model_name="gpt-3.5-turbo", verbose=False, stream=False):
    memory_prompt = MessagesPlaceholder(variable_name="chat_history")
    agent = StructuredChatAgent.from_llm_and_tools(
        llm=OpenAI(temperature=0, model_name=model_name, streaming=stream, verbose=verbose),
        tools=tools,
        memory=memory,
        memory_prompts=[memory_prompt] if memory else None,
        return_intermediate_steps=True,
        input_variables=["input", "agent_scratchpad", "chat_history"] if memory else ["input", "agent_scratchpad"],
        verbose=verbose,
    )
    return AgentExecutor.from_agent_and_tools(agent=agent, tools=tools, verbose=verbose, memory=memory)
    
async def main():
    tools = load_tools()
    history = ChatMessageHistory()
    memory = ConversationBufferWindowMemory(
        memory_key="chat_history",
        output_key="output",
        chat_memory=history,
        return_messages=True,
        k=3,
    )
    agent = load_structured_chat_agent(memory, tools, verbose=True, stream=True)

    with get_openai_callback() as cb:
        result = await agent.acall({ "input": "Respond with the Final Answer of 2 + 2.", "chat_history": []}, return_only_outputs=True)
    print_cost(cb)
        

if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by vowelparrot** [comment]
The costs aren't being counted in streaming mode. If I set  `stream=False` then it gives:

```
{'prompt_tokens': 640, 'completion_tokens': 94, 'total_tokens': 734, 'total_cost': 0.0014680000000000001, 'successful_requests': 2}
```

Was this working before? cc @agola11 

It's definitely something we should add, but this code snippet seems different than the original poster's issue

**Comment by jordanparker6** [comment]
> The costs aren't being counted in streaming mode. If I set `stream=False` then it gives:
> 
> ```
> {'prompt_tokens': 640, 'completion_tokens': 94, 'total_tokens': 734, 'total_cost': 0.0014680000000000001, 'successful_requests': 2}
> ```
> 
> Was this working before? cc @agola11
> 
> It's definitely something we should add, but this code snippet seems different than the original poster's issue

Yeah i had streaming and the callback working last week. I am not sure why it has changed.

Sorry, didn't post the full code in the original issue as I had to clean things up from other imports.

**Comment by EyeOfHorus396** [comment]
I removed streaming from Langchain Version: 0.0.250, and it still returns zeros for token cost and count. Has this been resolved?

**Comment by ujaved** [comment]
this is also not working in 0.0.268

**Comment by EyeOfHorus396** [comment]
If you guys add ConversationBufferMemory to your chain, it will make your Openai callback work. When you have streaming enabled, it can't calculate the token cost, but if you store it in memory, it will be able to calculate the token cost.

**Comment by jjshab** [comment]
This is most definitely still an issue and has been driving me crazy for 3 days now. Please fix this as there doesn't seem to be any other way to count tokens that works with LangChain and OpenAI APi.
