### ISSUE TITLE
Redis Vectorstore: Did not find redis_url, please add an environment variable `REDIS_URL` which contains it, or pass  `redis_url` as a named parameter.

### ISSUE THREAD

**Issue by iamadhee** [langchain-ai/langchain#4899]
### System Info

```
Python 3.10.4
langchain==0.0.171
redis==4.5.5
redisearch==2.1.1
```

### Who can help?

@tylerhutcherson 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I was able to override #4896 by getting rid of the extra `cls` from the mentioned method. Post which, I'm getting this below error. Ideally `from_texts_return_keys` method should not be expecting `redis_url` to be passed in as a kwarg since the `redis_url` is defined during the initialization of the `Redis` class and is a mandatory argument.

```
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/redis.py", line 448, in from_texts
    instance, _ = cls.from_texts_return_keys(
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/vectorstores/redis.py", line 389, in from_texts_return_keys
    redis_url = get_from_dict_or_env(kwargs, "redis_url", "REDIS_URL") 
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/utils.py", line 17, in get_from_dict_or_env
    return get_from_env(key, env_key, default=default)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/langchain/utils.py", line 27, in get_from_env
    raise ValueError(
ValueError: Did not find redis_url, please add an environment variable `REDIS_URL` which contains it, or pass  `redis_url` as a named parameter.
```

### Expected behavior

The method `from_texts_return_keys` should not expect the `redis_url` to be passed in as a kwarg.

**Comment by tylerhutcherson** [comment]
Hey @iamadhee the issue here is:

https://github.com/hwchase17/langchain/blob/a8ded21b6963b0041e9931f6e397573cb498cbaf/langchain/vectorstores/redis.py#L456

should be `**kwargs`

I am working with LC team on a fix now.

**Comment by iamadhee** [comment]
Great. Thanks

**Comment by jtmigowski** [comment]
I updated the langchain today, version 0.177 and the problem is already solved
