### ISSUE TITLE
How to enable precise formatting for the input of a tools utility class, such as accepting data of type list[str]? Is this achievable?

### ISSUE THREAD

**Issue by jhrsya** [langchain-ai/langchain#4918]
### System Info

How to enable precise formatting for the input of a tools utility class, such as accepting data of type list[str]? Is this achievable?
```python
class QueryTokenAssetsInput(BaseModel):
    addresses: str = Field(description="like 'address1,address2,address3',should be a list of addresses")

@tool("query_token_assets", return_direct=True, args_schema=QueryTokenAssetsInput)
def query_prices(addresses: str):
    """query the prices of tokens"""
    addresses = re.findall(r'"([^"]*)', addresses)[0].split(',')
    addresses = [address.replace(" ",'') for address in addresses]
    data = fetcher.query_tokens_price(addresses=addresses)
    return data
```
Just like the code snippet provided above, when the input "addresses" is a string and the question posed to the large model is about `the price of "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599, 0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84, 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"`, it interprets "addresses" as `'addresses = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599,0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84'"`. This requires me to use regular expressions to parse the string and convert it into `['0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599', '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84']`, but sometimes "addresses" is not very consistent, leading to bugs in my regular expression parsing. How can I make the input for "addresses" more stable? Is it possible to directly convert "addresses" into a list[str]?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.tools.base import tool, BaseModel, Field
import os
from typing import List
import re

class QueryTokenAssetsInput(BaseModel):
    addresses: str = Field(description="like 'address1,address2,address3',should be a list of addresses")

@tool("query_token_assets", return_direct=True, args_schema=QueryTokenAssetsInput)
def query_prices(addresses: str):
    """query the prices of tokens"""
    addresses = re.findall(r'"([^"]*)', addresses)[0].split(',')
    addresses = [address.replace(" ",'') for address in addresses]
    return data

if __name__ == "__main__":
    import json
    with open("langchain/api_key.json", "r") as f:
        api_key = json.load(f)
    os.environ["OPENAI_API_KEY"] = api_key["OPANAI_API_KEY"]
    from langchain.agents import AgentType, initialize_agent
    from langchain.chat_models import ChatOpenAI
    llm = ChatOpenAI(temperature=0)
    agent = initialize_agent([query_prices, get_file_sizes], llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
    data = agent.run("the price of 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599, 0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84, 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
    print(data)

### Expected behavior

How can I ensure that the input for "addresses" remains stable and directly becomes a list[str] type?

**Comment by Lukashab** [comment]
**🤖 AI-generated response by [Steercode](https://steercode.com/) - chat with Langchain codebase**
_Disclaimer: SteerCode Chat may provide inaccurate information about the Langchain codebase._

To make the input for "addresses" more stable and directly accept a list of strings, you can change the addresses field type in the QueryTokenAssetsInput class to List[str]. Here's the modified code:

```
from typing import List
from langchain.tools.base import tool, BaseModel, Field

class QueryTokenAssetsInput(BaseModel):
    addresses: List[str] = Field(description="A list of addresses")

@tool("query_token_assets", return_direct=True, args_schema=QueryTokenAssetsInput)
def query_prices(addresses: List[str]):
    """query the prices of tokens"""
    data = fetcher.query_tokens_price(addresses=addresses)
    return data
```

Now, when you call the query_prices function, the "addresses" input will be a list of strings, and you won't need to use regular expressions to parse it.

**You can continue the conversation at [https://steercode.com/](https://steercode.com/)**

**Comment by jhrsya** [comment]
> **🤖 AI-generated response by [Steercode](https://steercode.com/) - chat with Langchain codebase** _Disclaimer: SteerCode Chat may provide inaccurate information about the Langchain codebase._
> 
> To make the input for "addresses" more stable and directly accept a list of strings, you can change the addresses field type in the QueryTokenAssetsInput class to List[str]. Here's the modified code:
> 
> ```
> from typing import List
> from langchain.tools.base import tool, BaseModel, Field
> 
> class QueryTokenAssetsInput(BaseModel):
>     addresses: List[str] = Field(description="A list of addresses")
> 
> @tool("query_token_assets", return_direct=True, args_schema=QueryTokenAssetsInput)
> def query_prices(addresses: List[str]):
>     """query the prices of tokens"""
>     data = fetcher.query_tokens_price(addresses=addresses)
>     return data
> ```
> 
> Now, when you call the query_prices function, the "addresses" input will be a list of strings, and you won't need to use regular expressions to parse it.
> 
> **You can continue the conversation at https://steercode.com/**

I got this bug: 
```python
File "C:\cpp_java_go_python_notes\langchain\common_tools.py", line 56, in <module>
    data = agent.run("the price of 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599, 0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84, 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\chains\base.py", line 236, in run
    return self(args[0], callbacks=callbacks)[self.output_keys[0]]
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\chains\base.py", line 140, in __call__
    raise e
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\chains\base.py", line 134, in __call__
    self._call(inputs, run_manager=run_manager)
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\agents\agent.py", line 905, in _call
    next_step_output = self._take_next_step(
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\agents\agent.py", line 783, in _take_next_step      
    observation = tool.run(
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\tools\base.py", line 230, in run
    parsed_input = self._parse_input(tool_input)
  File "C:\Users\jhrsya\Anaconda3\envs\python39\lib\site-packages\langchain\tools\base.py", line 169, in _parse_input
    input_args.validate({key_: tool_input})
  File "pydantic\main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for QueryTokenAssetsInput
addresses
  value is not a valid list (type=type_error.list)
```

**Comment by wuxudong** [comment]
@jhrsya Do you have any solutions?
