### ISSUE TITLE
GraphQL example notebook not working

### ISSUE THREAD

**Issue by cgrotz** [langchain-ai/langchain#4946]
### System Info

Colab standard Python 3 backend

### Who can help?

@O-Roma

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Open GraphQL example notebook in colab
2. Add langchain and openai to the pip install statement
3. add environment variable for OPENAI_API_KEY
4. Run the notebook

Got the following error
```
ValidationError: 3 validation errors for GraphQLAPIWrapper
gql_client
  field required (type=value_error.missing)
gql_function
  field required (type=value_error.missing)
__root__
  Could not import gql python package. Please install it with `pip install gql`. (type=value_error)
```

### Expected behavior

The example should probably work.

**Comment by dev2049** [comment]
gql isn't a core dependency so you have to install it separately

**Comment by cgrotz** [comment]
gql is installed via pip in the notebook along httpx

**Comment by cgrotz** [comment]
I think the issue can be closed now.
