### ISSUE TITLE
Issue: Very long runtimes for RetrievalQA chain with GPT4All

### ISSUE THREAD

**Issue by sidharthrajaram** [langchain-ai/langchain#5016]
### RetrievalQA chain with GPT4All takes an extremely long time to run (doesn't end) 

I encounter massive runtimes when [running a RetrievalQA chain](https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa.html) with a locally downloaded GPT4All LLM. Unsure what's causing this.

I pass a GPT4All model (loading [ggml-gpt4all-j-v1.3-groovy.bin](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin) model that I downloaded locally) to the RetrievalQA Chain. I have one source text document and use sentence-transformers from HuggingFace for embeddings (I'm using a fairly small model: [all-MiniLM-L6-v2](https://www.sbert.net/docs/pretrained_models.html)).

```python
llm = GPT4All(model=model_path, n_ctx=model_n_ctx, backend='gptj', callbacks=callbacks, verbose=True)
qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=docsearch.as_retriever())
query = "How did the pandemic affect businesses"
ans = qa.run(query)
```

For some reason, the running the chain on a query takes an extremely long time to run (>25 minutes). 

Is this due to hardware limitations or something else? I'm able to run queries directly against the GPT4All model I downloaded locally fairly quickly (like the example shown [here](https://docs.gpt4all.io/gpt4all_python.html)), which is why I'm unclear on what's causing this massive runtime.

Hardware: M1 Mac, macOS 12.1, 8 GB RAM, Python 3.10.11

**Comment by sidharthrajaram** [comment]
Note: I also tried using the `load_qa_chain` chain instead, same outcome (hangs indefinitely)

**Comment by PavelAgurov** [comment]
Hi! I have exactly the same issue.
Windows 10, 16GB RAM, NVidea GPU, Python 3.10

And as I see GPU is not used and I can't find way how to run GPT4All on GPU.

**Comment by poojatambe** [comment]
Hi, I have used ConversationalRetrievalChain and load_qa_chain with gpt4all ggml-gpt4all-j-v1.3-groovy.bin model. Facing same issue. Any solution to tackle this long response time?

**Comment by poojatambe** [comment]
Hi, try to change n_threads parameter in GPT4All(model=local_path, backend='gptj',  verbose=True, temp=0.1, n_threads=4).
For n_threads=4, took 10-15 mins to generate response.

**Comment by sujata-appiot** [comment]
This is still an issue, the number of threads a system can run depends on number of CPU available.  n_threads=4 giving 10-15 minutes response time will not be expected response time for any real-world practical use case.
Is increasing number of CPUs the only solution to this?
Are there any other alternatives to get faster responses from GPT4All models with langchain?
I believe any real-world use case can allow only a few seconds of delay to get responses.

**Comment by RNubla** [comment]
This is still an issue. It takes roughly 5min for my system on Windows 11.
