### ISSUE TITLE
AttributeError: 'Collection' object has no attribute 'update_document'

### ISSUE THREAD

**Issue by martinholecekmax** [langchain-ai/langchain#5031]
### System Info

aiohttp==3.8.4
aiosignal==1.3.1
aniso8601==9.0.1
anyio==3.6.2
async-timeout==4.0.2     
attrs==23.1.0
backoff==2.2.1
blinker==1.6.2
certifi==2023.5.7        
charset-normalizer==3.1.0
chromadb==0.3.23
click==8.1.3
clickhouse-connect==0.5.24
colorama==0.4.6
dataclasses-json==0.5.7
duckdb==0.8.0
environs==9.5.0
fastapi==0.95.2
filelock==3.12.0
Flask==2.3.2
Flask-RESTful==0.3.9
frozenlist==1.3.3
fsspec==2023.5.0
greenlet==2.0.2
grpcio==1.53.0
h11==0.14.0
hnswlib==0.7.0
httptools==0.5.0
huggingface-hub==0.14.1
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.2.0
langchain==0.0.174
lz4==4.3.2
MarkupSafe==2.1.2
marshmallow==3.19.0
marshmallow-enum==1.5.1
monotonic==1.6
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.1
nltk==3.8.1
numexpr==2.8.4
numpy==1.24.3
openai==0.27.6
openapi-schema-pydantic==1.2.4
packaging==23.1
pandas==2.0.1
Pillow==9.5.0
posthog==3.0.1
protobuf==4.23.1
pydantic==1.10.7
pymilvus==2.2.8
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.30.0
scikit-learn==1.2.2
scipy==1.10.1
sentence-transformers==2.2.2
sentencepiece==0.1.99
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.13
starlette==0.27.0
sympy==1.12
tenacity==8.2.2
threadpoolctl==3.1.0
tiktoken==0.4.0
tokenizers==0.13.3
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.0
transformers==4.29.2
typing-inspect==0.8.0
typing_extensions==4.5.0
tzdata==2023.3
ujson==5.7.0
urllib3==2.0.2
uvicorn==0.22.0
watchfiles==0.19.0
websockets==11.0.3
Werkzeug==2.3.4
yarl==1.9.2
zstandard==0.21.0

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Reproduction Steps:

1. Create an instance of the Collection class.
2. Initialize the LangChain object and make sure it is properly configured.
3. Create a Document object and set its page_content and metadata attributes appropriately.
4. Call the update_document method on the LangChain object, passing the document_id and document as arguments.

Expected Result:
The update_document method should update the specified document in the collection with the provided text and metadata.

Actual Result:
An AttributeError is raised with the following traceback:

```plain
File "E:\AI Projects\flask-backend\venv\lib\site-packages\langchain\vectorstores\chroma.py", line 351, in update_document
    self._collection.update_document(document_id, text, metadata)
AttributeError: 'Collection' object has no attribute 'update_document'
```

Note that the error occurs in the chroma.py file, specifically in the update_document method of the Collection class.

### Expected behavior

The update_document method should update the specified document in the collection with the provided text and metadata.

**Comment by 2796gaurav** [comment]
Having same issue in my side too.

**Comment by ethanyys** [comment]
Installed langchain 0.0.177, still having the same issue...

**Comment by martinholecekmax** [comment]
I've just created a PR for this issue which can be found here https://github.com/hwchase17/langchain/pull/5359.
