### ISSUE TITLE
Reproducible NameError with recursive function in PythonREPL()

### ISSUE THREAD

**Issue by vanillechai** [langchain-ai/langchain#5035]
### System Info

MacOS, Python 3.11.2, langchain 0.0.174

### Who can help?

@vowelparrot 

### Information

- [X] My own modified scripts

### Related Components

- [X] Tools / Toolkits

### Reproduction

I hit a strange error when using PythonREPL in an agent. It happens with this **recursive** Python function. It was written by gpt-3.5-turbo and is valid Python:
```python
def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n-1) + fibonacci(n-2)  # <-- this line will trigger the NameError
print(fibonacci(10))
```

Note that everything works as expected for non-recursive functions.

Using this function as string input, I reduced the issue to this minimal example:

```python
from langchain.utilities import PythonREPL

python_repl = PythonREPL()
cmd = "def fibonacci(n):\n    if n <= 1:\n        return n\n    else:\n        return fibonacci(n-1) + fibonacci(n-2)\nprint(fibonacci(10))"
python_repl.run(cmd)
```
> $ python t.py
> NameError("name 'fibonacci' is not defined")

When executed with `exec(cmd)`, it runs as expected. I found that `PythonREPL` runs the command with `exec(command, self.globals, self.locals)`.

Setting globals & locals in this `python_repl` instance makes the fragment work as expected:
```python
# [... as before ...]
python_repl.globals = globals()
python_repl.locals = locals()
python_repl.run(cmd)
```
This hack solves it only in the context of this simple example, but not if `python_repl` added as a tool to an `AgentExecutor`.

At the core, the issue seems to be caused by Python scopes, but my knowledge of this is not profound enough to fully understand what's happening.

### Expected behavior

I would have expected `PythonREPL` to accept recursive functions.

**Comment by CurryYuan** [comment]
Same question here.
