### ISSUE TITLE
Issue: Accessing Dolly-v2-3b via HuggingFaceHub and langchain

### ISSUE THREAD

**Issue by aero-girl** [langchain-ai/langchain#5040]
### Issue you'd like to raise.

I am trying to access dolly-v2-3b using Langchain and HuggingFaceHub using the tutorial provided on the [website](https://python.langchain.com/en/latest/modules/models/llms/integrations/huggingface_hub.html).

However I am facing a few issues.
1. The instruction to `!pip install huggingface_hub > /dev/null` does not work. The error output is: The system cannot find the path specified.
2. Second, when using the example code to access dolly-v2-3b from Hugging Face Hub, the following code only provides a single word as output.

The code is shown below:
from langchain import HuggingFaceHub
repo_id = "databricks/dolly-v2-3b"
llm = HuggingFaceHub(repo_id=repo_id, model_kwargs={"temperature":0, "max_length":64})

I have also tried changing the max_length and temperature, but this makes no difference.

**Comment by Fabianlanger** [comment]
I faced the same issues... regarding 1, this might be some useful information:

`/dev/null` is a special file in Unix-based systems that discards all data written to it (it's often called the "null device"). So, in effect, `!pip install huggingface_hub > /dev/null` is installing the huggingface_hub package and discarding all the output messages that pip usually shows, resulting in a silent installation. This is often done to avoid cluttering the console with unnecessary information. I removed the `> /dev/null` as I don't care about cluttering my console.

I'm still looking for a solution to your second question.
