### ISSUE TITLE
Agent answer questions that is not related to my custom data

### ISSUE THREAD

**Issue by lironezra** [langchain-ai/langchain#5044]
### Issue you'd like to raise.

Hi All,

I'm developing a chatbot that run over PDF documents that stored on Pinecone.
I have an agent that use one tool (in my case it's `ConversationalRetrievalChain`) the chain works perfect when I'm asking any question.
But when I move forward and pass this chain as a tool I'm getting unexpected results. 
For example when I asked "Who is Leo Messi?" (of course I don't have any info on him in my PDF file), I got real answer to the question "Leo Messi is Argentinian soccer player......"

I noticed that the agent search by himself answer to that question and don't run the tool I provided for him.
I have tried to edit the prompt of the agent that will not search data by himself, but without success.

Anyone face it too?

Thanks for help!

**Comment by PavelAgurov** [comment]
Try to add into prompt something like "Use only provided data and not prior knowledge".

**Comment by lironezra** [comment]
Thanks @PavelAgurov , I have tried it already without success too.
I need to limit somehow the agent do not answer himself.

**Comment by PavelAgurov** [comment]
I decided do not use agents in my apps yet. So can't answer if it's a case now.
