### ISSUE TITLE
poetry install -E all` fails because `torch` undetected

### ISSUE THREAD

**Issue by startakovsky** [langchain-ai/langchain#5048]
### System Info

MacOS Ventura, zshell
`pyenv virtualenv 3.11 langchain`, clean environment
`pyenv local langchain`, automatically activate environment
`curl -sSL https://install.python-poetry.org | python -`, install poetry
`export PATH="/Users/steven/.local/bin:$PATH`, added this to allow for poetry to be accessible
`pip install --upgrade pip`
`pip install torch`
`poetry install -E all` 

yields the following output. Strange.

```bash
 • Installing torch (1.13.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (1.13.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│
       73│             links.append(link)
       74│
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       80│

```

### Who can help?

@hwchase17 This is install related and while I have langchain running fine from pip in another virtual environment running the same python version (3.11.3), things with poetry are not working well.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

MacOS Ventura, zshell
`pyenv virtualenv 3.11 langchain`, clean environment
`pyenv local langchain`, automatically activate environment
`curl -sSL https://install.python-poetry.org | python -`, install poetry
`export PATH="/Users/steven/.local/bin:$PATH`, added this to allow for poetry to be accessible
`pip install --upgrade pip`
`pip install torch`
`poetry install -E all` 

### Expected behavior

```bash
 • Installing torch (1.13.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (1.13.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│
       73│             links.append(link)
       74│
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       80│

```

**Comment by AvikantSrivastava** [comment]
Hi @startakovsky 
can you take a look at https://github.com/hwchase17/langchain/issues/2991
It looks like a duplicate issue

hope it helps, thanks

**Comment by startakovsky** [comment]
@AvikantSrivastava you are correct, I just deleted my virtual environment and built on top of python 3.9(latest) instead of 3.11.

**Comment by AvikantSrivastava** [comment]
Cool @startakovsky 
I think we can close this issue now

**Comment by jcf** [comment]
PyTorch supports Python 3.11 as of [last month](https://github.com/pytorch/pytorch/issues/86566#issuecomment-1614227063).

Is it possible to relax the version constraint on PyTorch to enable the use of Python 3.11 in projects dependent on LangChain?

**Comment by startakovsky** [comment]
@AvikantSrivastava go for it, thank you

**Comment by yordis** [comment]
Hey peeps, any updates on this one? I am a first-timer in python development, so I am unsure how to deal with the situation.

**Comment by trancethehuman** [comment]
If anyone still runs into this issue, it's because the PyTorch version in langchain isn't supported in Python version >=3.9.

To fix this, assuming you want to contribute to `libs/langchain`, and you're on Mac:

1. Download Python 3.9 from [official source](https://www.python.org/downloads/release/python-390/) and install it.
2. Open your langchain's root directory.

```bash
cd ~/langchain
```

3. Create a new virtual environment using Python 3.9 (if you've already had one, might be best to just delete it and start over by running `rm -r NAME_OF_ENVIRONMENT_FOLDER`

```bash
python3.9 -m venv langchain
```

4. Activate that virtual environment

```bash
source langchain/bin/activate
```

5. Make sure you're running Python 3.9 in that virtual environment

```bash
python3 --version
```

This should say `Python 3.9`

6. Continue with installing dependencies

**Comment by nilsbunger** [comment]
I hit this issue last week. I think it's a valid issue for python 3.10+
