### ISSUE TITLE
The problem that ConversationTokenBufferMemory cannot be trimmed normally due to the use of persistent messages

### ISSUE THREAD

**Issue by alex14dark** [langchain-ai/langchain#5053]
### Issue you'd like to raise.

By way of example from the official docs,
memory = ConversationTokenBufferMemory(llm=llm, max_token_limit=10)
memory. save_context({"input": "hi"}, {"ouput": "what's up"})
memory. save_context({"input": "not much you"}, {"ouput": "not much"})
memory. load_memory_variables({})
If it is the memory method, when the number of memories exceeds the given token limit, it will trim the memory normally, but if persistent messages are added, the memory will not be trimmed, for example
history = RedisChatMessageHistory(
         url=redis_url, ttl=600, session_id='id') memory = ConversationTokenBufferMemory(llm=llm, max_token_limit=10, chat_memory=history)
memory. save_context({"input": "hi"}, {"ouput": "what's up"})
memory. save_context({"input": "not much you"}, {"ouput": "not much"})
memory. load_memory_variables({})
You will find that the limit of the token exceeded in time, or it will print out all the historical memory
This will cause your code to fail to work properly for a certain period of time until the ttl that triggers redis expires

At present, my approach is to redefine a TokenMemory class. The following code is for reference only. If you have a better way to implement it, you are welcome to discuss it

`class CustomTokenMemory(BaseChatMemory):

     new_buffer: List = []

     human_prefix: str = "Human"
     ai_prefix: str = "AI"
     llm:BaseLanguageModel
     memory_key: str = "history"
     max_token_limit: int = 2000

     @property
     def buffer(self) -> List[BaseMessage]:
         """String buffer of memory."""
         if not self. new_buffer:
             self. prune_memory()
         return self. new_buffer
    
     @property
     def memory_variables(self) -> List[str]:
         """Will always return list of memory variables.

         :meta private:
         """
         return [self. memory_key]

     def load_memory_variables(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
         """Return history buffer."""
         buffer: Any = self.buffer
         if self. return_messages:
             final_buffer: Any = buffer
         else:
             final_buffer = get_buffer_string(
                 buffer,
                 human_prefix=self.human_prefix,
                 ai_prefix=self.ai_prefix,
             )
         return {self. memory_key: final_buffer}
    
     def save_context(self, inputs: Dict[str, Any], outputs: Dict[str, str]) -> None:
         """Save context from this conversation to buffer. Pruned."""
         super(). save_context(inputs, outputs)
         self. prune_memory()
        
     def prune_memory(self):
         # Prune buffer if it exceeds max token limit
         buffer = self.chat_memory.messages
         curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
         if curr_buffer_length > self.max_token_limit:
             while curr_buffer_length > self.max_token_limit:
                 buffer. pop(0)
                 curr_buffer_length = self.llm.get_num_tokens_from_messages(buffer)
             self.new_buffer = buffer`

Here I newly define a new_buffer array to point to the pruned memory, because in ConversationTokenBufferMemory, his self.buffer always gets all the messages in redis, so even if the memory is pruned in save_context, but All the historical messages obtained through load_memory_variables. My change here is that when the new_buffer is empty, the historical messages are first obtained from redis. Here, it needs to be trimmed once to ensure that the obtained messages must be within the Token limit, so The main purpose is to deal with rare scenarios, such as when your service is down or restarted, and the messages in the memory disappear. Although this is not necessary in most cases, then after new messages enter, the buffer will be deleted. new_buffer instead, then the pruned memory is obtained through load_memory_variables

**Comment by k1ng** [comment]
The same problem occurs when using FileChatMessageHistory with ConversationTokenBufferMemory.

**Comment by timxieICN** [comment]
@dosubot
Yes, above issue is still relevant in latest LangChain version

**Comment by Sameera2001Perera** [comment]
I think this is somehow related to [#21610](https://github.com/langchain-ai/langchain/issues/21610)
