### ISSUE TITLE
Issue: How do I fix the prompt length error in any agent that uses LLMCHAIN ? 

### ISSUE THREAD

**Issue by tejeshbhalla** [langchain-ai/langchain#5057]
### Issue you'd like to raise.

I am using the babyagi with the zeroshotagent the prompt length error is persistent , how can we fix it possibly summarise the agent_scratchpad and if someone could explain how does it work by default ? does It keep appending the bot and human response in it or just the previous ones?

**Comment by lingfengchencn** [comment]
show your codes and logs , please.
