### ISSUE TITLE
[Bug] MMR ordering is not preserved for the Chroma Vectorstore

### ISSUE THREAD

**Issue by MrinalJain17** [langchain-ai/langchain#5061]
https://github.com/hwchase17/langchain/blob/424a573266c848fe2e53bc2d50c2dc7fc72f2c15/langchain/vectorstores/chroma.py#L275

The line above would only select the candidates based on MMR, and not reorder them based on MMR's ranking.

This is not the case for any other vectorstores that support MMR.

cc @hwchase17

**Comment by AvikantSrivastava** [comment]
There is an MMR reordering happening on this line, the results should be ordered
https://github.com/hwchase17/langchain/blob/424a573266c848fe2e53bc2d50c2dc7fc72f2c15/langchain/vectorstores/chroma.py#LL266C4-L271C10

```python
            mmr_selected = maximal_marginal_relevance(
            np.array(embedding, dtype=np.float32),
            results["embeddings"][0],
            k=k,
            lambda_mult=lambda_mult,
        )
```

@MrinalJain17 can you attach some data/logs to further explain this issue or give us a way to replicate?

**Comment by MrinalJain17** [comment]
Hi @AvikantSrivastava 

The `maximal_marginal_relevance` just returns the indices (in the required order, yes). However, **the `candidates` are not ordered by that ranking.**

Something like this would be the right way to do it:

```python
selected_results = [candidates[idx] for idx in mmr_selected]
```

**The bug is not there for any other vectorstore, except Chroma**. For instances, FAISS - https://github.com/hwchase17/langchain/blob/424a573266c848fe2e53bc2d50c2dc7fc72f2c15/langchain/vectorstores/faiss.py#L289
