### ISSUE TITLE
DOC: SQL Database Agent

### ISSUE THREAD

**Issue by er77** [langchain-ai/langchain#5068]
### Issue with current documentation:

Hello 
 I was trying to reproduce an example from that documentation 

https://python.langchain.com/en/latest/modules/agents/toolkits/examples/sql_database.html?highlight=SQLDatabaseToolkit# 

and got error 

toolkit = SQLDatabaseToolkit(db=db )
--
ValidationError: 1 validation error for SQLDatabaseToolkit
llm
  field required (type=value_error.missing)
--

**Comment by xiaohui-gsv** [comment]
Same issue here
![image](https://github.com/hwchase17/langchain/assets/38554198/71976523-6ae8-468a-9b18-601d72d285a3)

**Comment by mradul-kanugo** [comment]
@er77 @xiaohui-gsv 

llm = OpenAI(temperature=0)
toolkit = SQLDatabaseToolkit(db=db, llm=llm)

Pass llm and it should work.

**Comment by Ajithprasath08** [comment]
@mradul-kanugo 

Hi, even after trying the above code, I am still facing the error.
![image](https://github.com/hwchase17/langchain/assets/41677669/914f2f88-67d3-43bb-9265-9f6c20f0505f)

**Comment by hordaway** [comment]
me too

**Comment by Apashrov16** [comment]
> Using this one: from langchain.chat_models import ChatOpenAI llm = ChatOpenAI(model_name="gpt-3.5-turbo")
> 
> toolkit = SQLDatabaseToolkit(db=db,llm=llm)
> 
> agent_executor = create_sql_agent( llm=llm, toolkit=toolkit, verbose=True )
> 
> and it works for me

It works for me too

**Comment by ChelcieDeAlmeida** [comment]
> 

The suggestions works for me. General assumption but are you on a paid account with openAI? Once I paid for API access, the code everyone here recommended began to work for me
