### ISSUE TITLE
Issue: Create way to do filters using VectorStore 

### ISSUE THREAD

**Issue by rogerioesteves** [langchain-ai/langchain#5076]
### Issue you'd like to raise.

I'm seeing the official documentation  vectorstore Chromadb and I found way to do query using filters where or where_documents.
I tried to use filter using the langchain chromadb wrapper by examples and I don't see how to do query using filters.
Exists any way to do filters if no, We could implement new features to do this!

https://docs.trychroma.com/usage-guide#querying-a-collection

**Comment by francisjervis** [comment]
See https://github.com/chroma-core/chroma/issues/560#issuecomment-1554996688
