### ISSUE TITLE
CosmosDBChatMessageHistory.load_messages return None

### ISSUE THREAD

**Issue by F2EVarMan** [langchain-ai/langchain#5077]
When I use CosmosDBChatMessageHistory, the conversation history is stored in DB, but every time load message returns None, and each time I run add_user_message, I perform a replace operation, not an increment on the original record.

![image](https://github.com/hwchase17/langchain/assets/10355060/de8edb58-206a-4531-a584-797e1ff6ef58)
![image](https://github.com/hwchase17/langchain/assets/10355060/be068f76-742e-469a-8818-e821b996de32)
![image](https://github.com/hwchase17/langchain/assets/10355060/44189bc0-17e4-410f-9994-66eaf88764bf)
![image](https://github.com/hwchase17/langchain/assets/10355060/6053659c-09dd-4cbd-9584-315c9080c250)

**Comment by F2EVarMan** [comment]
I found that every time I initialized CosmosDBChatMessageHistory, the content was reset.

Unless I start only one instance of CosmosDBChatMessageHistory, I can get the history later through .messages, or I can append it through add.

But as long as I run CosmosDBChatMessageHistory once, executing add again becomes a replace operation

**Comment by F2EVarMan** [comment]
I tested according to the test case here, and I found that the problem is that once CosmosDBChatMessageHistory is called again, it will overwrite the previously saved conversation history, resulting in no historical conversation and no data insertion from the historical conversation.

https://github.com/hwchase17/langchain/pull/3525/commits/a1b663017bc84bba1af79bed5833c830517b10fd

**Comment by miggytrinidad** [comment]
@F2EVarMan , any luck on this issue?
