### ISSUE TITLE
llmchain not work as expect in multiple thread scenario

### ISSUE THREAD

**Issue by vincent-pli** [langchain-ai/langchain#5084]
### System Info

langchain==0.0.165
Python 3.10.8
macos m2

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
    def __init__(self, prompt_template: PromptTemplate):
        self.llmchainList = []
        key_list = self.__getAPIKeys()
        for key in key_list:
            llm = ChatOpenAI(model_name="gpt-3.5-turbo", openai_api_key=key, max_tokens = 1500)
            llm_chain = LLMChain(
                llm=llm,
                prompt=prompt_template)
            self.llmchainList.append(llm_chain)

    def __pickupLlm(self):
        chain = self.llmchainList.pop(0)
        self.llmchainList.append(chain)

        return chain

    def send(self, **kwargs):
        chain = self.__pickupLlm()
        print("send message to chatgpt...")
        res = {}
        with get_openai_callback() as cb:
            res = chain.run(**kwargs)
            print(cb)
        print("chatgpt said...")
        print(res)
```

The code is very straight forward, I have a api token list, when init, create a `llmchain` list. 
when request to `chatgpt`, I pop up one `llmchain` in the list (simple load balance for rate limit) .

But, when I start request with multiple thread, I got many `rate limit` exception event I sleep enough ms between request.
and I found all `rate limit` exception point to one api token(`Rate limit reached for default-gpt-3.5-turbo in organization org-WN9k0BUSqN4pNvlU5N6T74Yq on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.`), also the api token on the end of my list. that's weird.  My simple load balance will never pick on one "api token" in one batch request.

Even I print `key` of each `llmchain`, it'a correct, for example, one batch, I send 3 request, and each `llmchian` with different `apikey`, but I still get `rate limit` with one specific organization which is exactly in the end of my `api token` list.

So I have to suspect there must be some wrong with `LLMCHAIN`,  expect reply, thanks

### Expected behavior

By design, no rate limit exception

**Comment by vincent-pli** [comment]
Any comments? @hwchase17

**Comment by vincent-pli** [comment]
I have no idea seems others not hit the issue? a more simple example here:
```
from langchain import PromptTemplate, LLMChain
from langchain.chat_models import ChatOpenAI
import time

prompt_template = "What is a good name for a company that makes {product}?"
keys = "key-1,key-2,key-3"

# llm = OpenAI(temperature=0)
llmchains = []
for key in keys.split(","):
    time.sleep(1)
    llm = ChatOpenAI(model_name="gpt-3.5-turbo", openai_api_key=key, max_tokens = 2500, request_timeout = 60)
    llm_chain = LLMChain(
        llm=llm,
        prompt=PromptTemplate.from_template(prompt_template)
    )
    llmchains.append(llm_chain)

print(llmchains[0]("colorful socks"))
print(llmchains[1]("colorful socks"))
print(llmchains[2]("colorful socks"))
print(llmchains[0]("colorful socks"))
```

we know the ratelimit of "gpt-3.5-turbo" is 3/min, so based on the code, will never hit the ratelimit exception, but:
```
{'product': 'colorful socks', 'text': 'Rainbow Socks Co.'}
{'product': 'colorful socks', 'text': 'Rainbow Footwear Co.'}
{'product': 'colorful socks', 'text': 'Rainbow Socks Co.'}
Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-WN9k0BUSqN4pNvlU5N6T74Yq on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method..
```

**Comment by Jack-Collins** [comment]
+1
