### ISSUE TITLE
Integration with Google Docs

### ISSUE THREAD

**Issue by pruksmhc** [langchain-ai/langchain#509]
What is the best way to build an agent that can read from Google docs and perform inference based on it (and an input)? I see there are a lot of Search functionality, but it seems to be general search (versus search over a particular source).

**Comment by hwchase17** [comment]
Good q! Do you know if there’s a good google docs api? If there’s one of those, should be pretty easy to hook up to langchain

**Comment by pruksmhc** [comment]
This is the standard one: https://github.com/googleapis/google-api-python-client
Usage example: https://developers.google.com/docs/api/samples/extract-text#python
