### ISSUE TITLE
I am still struggling. It does not remember anything in the chat history. What am I doing wrong? Here is my code:

### ISSUE THREAD

**Issue by yysturdy** [langchain-ai/langchain#5099]
def load_chain():
    global j
    os.environ["OPENAI_API_KEY"] =api_key[j%3]
    print(api_key[j%3])
    j=j+1
   #global chain
    print("模型加载开始")
    #loader = DirectoryLoader('./langchian_gpt/yuliaoku', glob='**/*.txt')
    loader = DirectoryLoader('./yuliaoku', glob='**/*.txt')
    docs = loader.load()
    # 文档切块
    text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=0)
    doc_texts = text_splitter.split_documents(docs)
    # 调用openai Embeddings
    embeddings = OpenAIEmbeddings(openai_api_key=os.environ["OPENAI_API_KEY"])
    # 向量化
    vectordb = Chroma.from_documents(doc_texts, embeddings)#
     vectordb = Chroma.from_documents(doc_texts, embeddings, persist_directory="./yuliaoku")
    vectordb.persist()
    ll=ChatOpenAI(temperature=0.3, model_name="gpt-3.5-turbo", max_tokens=1024)
    memory = ConversationBufferWindowMemory(memory_key="chat_history",k=3, output_key='answer',return_messages=True)
    # 创建聊天机器人对象chain
    chain = ConversationalRetrievalChain.from_llm(
        retriever=vectordb.as_retriever(search_type="similarity",search_kwargs={"k": 1}),
                                                  llm=ll
                                                  verbose=True,
                                                  memory=memory,
                                                  get_chat_history=lambda h: h,
                                                   #map_reduce,map_rerank ,refine
                                                  return_source_documents=False)
    print("模型加载结束")
    return chain#,memory
def embedding(require_text):
    chain=load_chain()
    ans = chain({"question": require_text})
    return ans['answer']
无法实现上下文功能，请问我哪里有问题，我的langchain是0.0161的版本

**Comment by VionaWang** [comment]
Probably you can try to update that to a newer version of langchain?
