### ISSUE TITLE
How to use SQL Database chain with an opensource LLM?

### ISSUE THREAD

**Issue by hussnainahmed** [langchain-ai/langchain#5121]
### Issue you'd like to raise.

I have been trying to use SQL Database Chain with open-source LLM but have not succeeded.
`from langchain import HuggingFaceHub`
`repo_id = "google/flan-t5-xl"`
`db = SQLDatabase.from_uri(db_url)`
`llm = HuggingFaceHub(repo_id=repo_id)`
`db_chain = SQLDatabaseSequentialChain.from_llm(llm, db, verbose=True)`

Please help. Refer to any examples available online.
I have already tried gpt4all and llama.cpp

**Comment by dharma610** [comment]
Use Google/flan-ul2. It is working fine with SQL database chain. Is there anyone tried any other model ?

**Comment by kb-shiva** [comment]
@dharma610  - Is it possible for you to share a sample snippet which worked fine with Google/flan-ul2 ? I am noticing dict[] conversion error when i use flan model in sql chain..

**Comment by marouahamdi** [comment]
hello any help/ news with this topic?

**Comment by s-basant** [comment]
any updates ?
Most the examples I find on internet uses openAI. None of them uses opensource LLM. The examples that uses opensource LLM does not work anymore
