### ISSUE TITLE
Slow response time with `ConversationalRetrievalQAChain`

### ISSUE THREAD

**Issue by gzimh** [langchain-ai/langchain#5123]
### Issue you'd like to raise.

Hello,

I am facing slow response times (25 - 30 second) per question with `ConversationalRetrievalQAChain` and pinecone. 

```
    const chain = ConversationalRetrievalQAChain.fromLLM(
      this.llm,
      vectorStore.asRetriever(),
    );

    const res = await chain.call({ question, chat_history: [''] });
```

95% of that time is spent from the time the chain.call is executed. I have tried both gpt-3.5-turbo and gpt-4 models and I face similar response times. 

I've also tried to turn on streaming, and I can see that for gtp-3.5-turbo there is nothing being streamed on the first 20 seconds or so. And once it starts streaming, it is faster compared to gpt-4. But, gpt-4 takes much less time to start streaming, but then it is slower to complete the answer.  

Any help would be appreciated, thank you!

**Comment by DevOtts** [comment]
@dosubot let's reopen this issue as the PR https://github.com/langchain-ai/langchain/pull/5066 aren't merge yet.

**Comment by yuanpusheng** [comment]
The problem is not solved
