### ISSUE TITLE
Can't pickle the faiss vector store object in langchain

### ISSUE THREAD

**Issue by jpzhangvincent** [langchain-ai/langchain#5145]
### Issue you'd like to raise.

I got the error `OSError: [Errno 22] Invalid argument` when trying to pickle the faiss vector store. with the following code

```
merge_file_path = "combined_hf_faiss_vectorstore.pkl"
with open(merge_file_path, "wb") as f:
    pickle.dump(csfaq_index, f)
```
It works on mac local laptop but not on the linux machine in the Databricks cloud.

Here is the system info:
sysname='Linux',  release='5.15.0-1035-aws', version='#39~20.04.1-Ubuntu SMP Wed Apr 19 15:34:33 UTC 2023', machine='x86_64'

Any suggestion?

**Comment by adiigeek** [comment]
I'm getting this error while trying to dump my vectorstore ,here is the error  File "C:\chatbot_new\api\routers\pdf\multiple_pdf_router.py", line 148, in upload_files
    serialized_document_search = gzip.compress(pickle.dumps(document_search))
TypeError: cannot pickle '_thread.RLock' object

**Comment by steve-barnard** [comment]
Similar issue here to @adiigeek. Simple text file split and embedded via `langchain.text_splitter import RecursiveCharacterTextSplitter`  and `langchain.embeddings import OpenAIEmbeddings`

```from langchain.vectorstores.faiss import FAISS
import pickle

vectorstore = FAISS.from_documents(documents, embeddings)

with open("vectorstore.pkl", "wb") as f:
    pickle.dump(vectorstore, f)
```

Leads to this error:

```
[4](vscode-notebook-cell:?execution_count=13&line=4) vectorstore = FAISS.from_documents(documents, embeddings)
[6](vscode-notebook-cell:?execution_count=13&line=6) with open("vectorstore.pkl", "wb") as f:
----> [7](vscode-notebook-cell:?execution_count=13&line=7)     pickle.dump(vectorstore, f)

TypeError: cannot pickle '_thread.RLock' object

**Comment by adiigeek** [comment]
@steve-barnard  installing  langchain==0.0.316 and openai==0.28.1 may resolve your issue. Please check.

**Comment by steve-barnard** [comment]
Thank you @adiigeek, seems to be a simple version issue that is no longer supported in openai and langchain installs as of 1-11-2024.

This was the workaround I used and hopefully, this is helpful for someone else:

```
from langchain.vectorstores.faiss import FAISS
from langchain.embeddings import OpenAIEmbeddings

embeddings = OpenAIEmbeddings()

vectorstore = FAISS.from_documents(documents, embeddings)

vectorstore.save_local("vectorstore")

x = FAISS.load_local("vectorstore", OpenAIEmbeddings())

retriever = x.as_retriever()

```

**Comment by now-youre-gittin-it** [comment]
Hi @steve-barnard, thanks for your suggestion! There do seem to be a few versioning issues with langchain and openai. Your approach worked for me, and didn't even need to create the retriever object.

**Comment by MadhumithaKolkar** [comment]
Try this :

embeddings = OpenAIEmbeddings()

vectorstore = FAISS.from_documents(docs, embeddings)

vectorstore.save_local("vectorstore")

x = FAISS.load_local("vectorstore", OpenAIEmbeddings(), allow_dangerous_deserialization=True)

retriever = x.as_retriever()

**Comment by Heteshsk97** [comment]
Thank you I will give it a try and let you know

Regards
Hetesh

**Comment by Mrzjk** [comment]
> x = FAISS.load_local("vectorstore", OpenAIEmbeddings())



> Try this :
> 
> embeddings = OpenAIEmbeddings()
> 
> vectorstore = FAISS.from_documents(docs, embeddings)
> 
> vectorstore.save_local("vectorstore")
> 
> x = FAISS.load_local("vectorstore", OpenAIEmbeddings(), allow_dangerous_deserialization=True)
> 
> retriever = x.as_retriever()

Thank！！！！
