### ISSUE TITLE
It would be nice to make the SQL helper consider the table and column comments

### ISSUE THREAD

**Issue by kittenkill** [langchain-ai/langchain#5158]
### Feature request

There are some tables out there with comments.
It would be nice if the sql agent could read them.

### Motivation

Sometimes, column names do not describe perfectly well what they contain.
If sql agent can consider the table and column comments, it will be able to better respond to queries.

### Your contribution

Maybe something like this could work for the table comments:

```diff
--- sql_database.py.orig        2023-05-23 20:34:09.877909913 -0400
+++ sql_database.py     2023-05-23 20:34:13.857925528 -0400
@@ -268,11 +268,14 @@
             # add create table command
             create_table = str(CreateTable(table).compile(self._engine))
             table_info = f"{create_table.rstrip()}"
+            table_comment = table.comment
             has_extra_info = (
-                self._indexes_in_table_info or self._sample_rows_in_table_info
+                self._indexes_in_table_info or self._sample_rows_in_table_info or table_comment
             )
             if has_extra_info:
                 table_info += "\n\n/*"
+            if table_comment:
+                table_info += f"\nTable comment: {table_comment}\n"
             if self._indexes_in_table_info:
                 table_info += f"\n{self._get_table_indexes(table)}\n"
             if self._sample_rows_in_table_info:
```

**Comment by shadyelgewily-slimstock** [comment]
Would be helfpul for us too.

**Comment by KonstantinSDev** [comment]
This would be helpful for my project!

**Comment by willsmithorg** [comment]
I am deliberately adding table comments to my databases so that an AI can understand them better.  This PR would be perfect for that.  @kittenkill I'm also not clear whether foreign keys are extracted.  If not, this would be useful too.

**Comment by sivavishnubramma** [comment]
I +1 this request. 

Scenario:
Sql queries generated by langchain sqlagent are good to answer simple questions. But for complex scenarios, majority of queries end-up wrong. For example, the Sql agent used product_price column instead of payment_amount column to calculate sales revenue per product. Similar problem when joining tables with multi-level association (eg: movies, rentals, payment, inventory). 

Temp fix: 
These problems were resolved by providing a few extra lines of details as context followed by the actual question (prompt engineering). Then it was able to return valid sql-queries and answers. 

Question:
Is there a better way to address this Sqlagent issue? If not, please add a mechanism to input schema glossary to train the model instead of prompt engineering.

Much appreciate your support!

**Comment by Aden-Kurmanov** [comment]
@dosu-beta
No, we need to add our comments from tables and columns to request for improve creating sql request

**Comment by hagope** [comment]
I'm planning to look into this issue, something I've been thinking about as well ....it is very useful to add additional comments from the table metadata, which will give a much better response from the llm. In addition to the table comments, the column level comments can be included in the prompt as well.

**Comment by shadyelgewily-slimstock** [comment]
This is still relevant for us, we have managed to improve slightly by creating a view of our database tables with very clear names, but to us allowing to add additional comments to the schema would help bring our application to production.

**Comment by hagope** [comment]
@kittenkill it looks like this approach of setting the table comment will not work using sqlalchemy, it's only used to set the table comment when the SQL is [compiled](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/sql/compiler.py#L6681).  sqlalchemy cannot fetch any of the column or table level comments, as far as I can tell from browsing the code. 

I'm thinking the best approach here is to include another parameter `additional_context_sql` to allow the user to fetch metadata for any other relevant data... this does kind of defeat the purpose of avoiding SQL though :)
