### ISSUE TITLE
Invalid Output Parser Format for "Router Chain"

### ISSUE THREAD

**Issue by anapple00** [langchain-ai/langchain#5163]
### System Info

langchain version: 0.0.170
python: 3.8

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here I came across an issue related to the output of **router chain**.
When I ran the tutorial of "router chain" in [langchain website](https://python.langchain.com/en/stable/modules/chains/generic/router.html), the input query is: "What is black body radiation?" and the output of LLM is: 
```
'{
    "destination": "physics",
    "next_inputs": "What is black body radiation?"
}'
```
Use the class **RouterOutputParser** to parse the output then I got the error: 

> {OutputParserException}Got invalid return object. Expected markdown code snippet with JSON object, but got:
> {
>     "destination": "physics",
>     "next_inputs": "What is black body radiation?"
> }

When I debug step by step I found the error raised in this function: **parse_json_markdown**
```python
def parse_json_markdown(text: str, expected_keys: List[str]) -> Any:
    if "```json" not in text:
        raise OutputParserException(
            f"Got invalid return object. Expected markdown code snippet with JSON "
            f"object, but got:\n{text}"
        )

    json_string = text.split("```json")[1].strip().strip("```").strip()
    try:
        json_obj = json.loads(json_string)
    except json.JSONDecodeError as e:
        raise OutputParserException(f"Got invalid JSON object. Error: {e}")
    for key in expected_keys:
        if key not in json_obj:
            raise OutputParserException(
                f"Got invalid return object. Expected key `{key}` "
                f"to be present, but got {json_obj}"
            )
    return json_obj
```
You can see there is no "```json" string in the output of LLM, so it will step into the "if" in the first row of this function and raise the bug.

### Expected behavior

Can anyone give me some solutions? thanks.

**Comment by anapple00** [comment]
a bug about router chain

**Comment by 4kk11** [comment]
I have the same problem.
When I use "text-davinci-003" it works, but with "gpt-3.5-turbo" I get an error.

**Comment by jan-schaeffer** [comment]
Although `parse_json_markdown` seems to have been reworked since 0.0.170 (I'm on 0.0.191) I still get the same error:

`OutputParserException: Got invalid return object. Expected markdown code snippet with JSON object, but got:

{
 "destination": "physics",
 "next_inputs": "What is black body radiation?"
}

A: JavaScript (ES6),  72  72 bytes
Saved 1 byte thanks to @Neil
Saved 1 byte thanks to @Neil
S
`

Does anyone have any idea whats going wrong?

**Comment by shubham184** [comment]
+1

**Comment by tarasowski** [comment]
The parser fails with gtp-3.5-turbo.

**Comment by simicvm** [comment]
> I have the same problem.
> When I use "text-davinci-003" it works, but with "gpt-3.5-turbo" I get an error.

I can confirm that this is still an issue. However, if you use `gpt-4-0613`, the system works fine. It might be that `gpt-3.5-turbo` model just doesn't follow the template well and does not output  `"```json"`

**Comment by vowelparrot** [comment]
gpt-3.5-turbo is optimized for chat rather than schema generation, so it is less reliable. Recommend trying out the openai functions agent or use a different model.

**Comment by maifeng** [comment]
To get through the tutorial, I had to create a new class:

```` python
import json
import langchain
from typing import Any, Dict, List, Optional, Type, cast

class RouterOutputParser_simple(langchain.schema.BaseOutputParser[Dict[str, str]]):
    """Parser for output of router chain int he multi-prompt chain."""

    default_destination: str = "DEFAULT"
    next_inputs_type: Type = str
    next_inputs_inner_key: str = "input"

    def parse(self, text: str) -> Dict[str, Any]:
        try:
            expected_keys = ["destination", "next_inputs"]
            parsed = json.loads(text) ### this line is changed
            if not isinstance(parsed["destination"], str):
                raise ValueError("Expected 'destination' to be a string.")
            if not isinstance(parsed["next_inputs"], self.next_inputs_type):
                raise ValueError(
                    f"Expected 'next_inputs' to be {self.next_inputs_type}."
                )
            parsed["next_inputs"] = {self.next_inputs_inner_key: parsed["next_inputs"]}
            if (
                parsed["destination"].strip().lower()
                == self.default_destination.lower()
            ):
                parsed["destination"] = None
            else:
                parsed["destination"] = parsed["destination"].strip()
            return parsed
        except Exception as e:
            raise OutputParserException(
                f"Parsing text\n{text}\n raised following error:\n{e}"
            )
````

Then use this class as the output_parser
```` python
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser_simple(), ### replaced RouterOutputParser()
)

router_chain = LLMRouterChain.from_llm(llm, router_prompt)
````

**Comment by LifeBringer** [comment]
> To get through the tutorial, I had to create a new class:
> 
> ```python
> import json
> import langchain
> from typing import Any, Dict, List, Optional, Type, cast
> 
> class RouterOutputParser_simple(langchain.schema.BaseOutputParser[Dict[str, str]]):
>     """Parser for output of router chain int he multi-prompt chain."""
> 
>     default_destination: str = "DEFAULT"
>     next_inputs_type: Type = str
>     next_inputs_inner_key: str = "input"
> 
>     def parse(self, text: str) -> Dict[str, Any]:
>         try:
>             expected_keys = ["destination", "next_inputs"]
>             parsed = json.loads(text) ### this line is changed
>             if not isinstance(parsed["destination"], str):
>                 raise ValueError("Expected 'destination' to be a string.")
>             if not isinstance(parsed["next_inputs"], self.next_inputs_type):
>                 raise ValueError(
>                     f"Expected 'next_inputs' to be {self.next_inputs_type}."
>                 )
>             parsed["next_inputs"] = {self.next_inputs_inner_key: parsed["next_inputs"]}
>             if (
>                 parsed["destination"].strip().lower()
>                 == self.default_destination.lower()
>             ):
>                 parsed["destination"] = None
>             else:
>                 parsed["destination"] = parsed["destination"].strip()
>             return parsed
>         except Exception as e:
>             raise OutputParserException(
>                 f"Parsing text\n{text}\n raised following error:\n{e}"
>             )
> ```
> 
> Then use this class as the output_parser
> 
> ```python
> router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
>     destinations=destinations_str
> )
> router_prompt = PromptTemplate(
>     template=router_template,
>     input_variables=["input"],
>     output_parser=RouterOutputParser_simple(), ### replaced RouterOutputParser()
> )
> 
> router_chain = LLMRouterChain.from_llm(llm, router_prompt)
> ```

I get an 'OutputParserException' not defined error when running: chain.run("what is 2 + 2")

**Comment by LyndonZhao** [comment]
I met the same problem.
And I wonder why this problem has not been resolved after more than one month since it occours.

**Comment by LyndonZhao** [comment]
I resolved the problem by adding an example at the end of the MULTI_PROMPT_ROUTER_TEMPLATE.
Please check it as below.

eg:
<< INPUT >>
"What is black body radiation?"
<< OUTPUT >>
```json
{{{{
    "destination": "physics",
    "next_inputs": "What is black body radiation?"
}}}}
```

FYI(the complete  content of MULTI_PROMPT_ROUTER_TEMPLATE ):

MULTI_PROMPT_ROUTER_TEMPLATE = """Given a raw text input to a \
language model select the model prompt best suited for the input. \
You will be given the names of the available prompts and a \
description of what the prompt is best suited for. \
You may also revise the original input if you think that revising\
it will ultimately lead to a better response from the language model.

<< FORMATTING >>
Return a markdown code snippet with a JSON object formatted to look like:
```json
{{{{
    "destination": string \ name of the prompt to use or "DEFAULT"
    "next_inputs": string \ a potentially modified version of the original input
}}}}
```

REMEMBER: "destination" MUST be one of the candidate prompt \
names specified below OR it can be "DEFAULT" if the input is not\
well suited for any of the candidate prompts.
REMEMBER: "next_inputs" can just be the original input \
if you don't think any modifications are needed.

<< CANDIDATE PROMPTS >>
{destinations}

<< INPUT >>
{{input}}

<< OUTPUT (remember to include the ```json)>>
**_eg:
<< INPUT >>
"What is black body radiation?"
<< OUTPUT >>
```json
{{{{
    "destination": "physics",
    "next_inputs": "What is black body radiation?"
}}}}_**
```
"""

**Comment by aaalexlit** [comment]
@LyndonZhao, Thanks!
The solution worked for me

**Comment by Nghiauet** [comment]
It fixed in version langchain 0.0.222. Just upgraded langchain and it work

**Comment by Boopalanoptisol** [comment]
> ### eg:
> << INPUT >> "What is black body radiation?" << OUTPUT >> ```json {{{{ "destination": "physics", "next_inputs": "What is black body radiation?" }}}}

**Am getting the below mentioned error.**
**OutputParserException:** Parsing text ```json { "destination": "response_format", "next_inputs": "What is backbody radiation?" } ``` raised following error: Expecting value: line 1 column 1 (char 0)

**Comment by Boopalanoptisol** [comment]
> I resolved the problem by adding an example at the end of the MULTI_PROMPT_ROUTER_TEMPLATE. Please check it as below.
> 
> ### eg:
> << INPUT >> "What is black body radiation?" << OUTPUT >> ```json {{{{ "destination": "physics", "next_inputs": "What is black body radiation?" }}}} ```

When iadded the above example 
![image](https://github.com/langchain-ai/langchain/assets/105263483/e925e2fa-36f6-425d-a2dc-f508f2316a46)
**Also getting the error as 
OutputParserException: Parsing text raised following error: Expecting value: line 1 column 1 (char 0)**

**Comment by hueiyuan** [comment]
@SimasJan 
After adjusted based on your suggestion, we found the problem still have occurred in `MultiRetrievalQAChain`. 
Whether other solution can solve?
```
python: 3.9
Langchain: 0.0249
Azure Open AI: gpt-3.5-turbo
```

**Comment by bilalansar3** [comment]
> I resolved the problem by adding an example at the end of the MULTI_PROMPT_ROUTER_TEMPLATE. Please check it below.
> 
> ### eg:
> << INPUT >> "What is black body radiation?" << OUTPUT >> ```json {{{{ "destination": "physics", "next_inputs": "What is black body radiation?" }}}} ```

**THIS HELPS FOR ME**

**Comment by mpduarte** [comment]
@hueiyuan 
Having the same issue as you, did you find a way to fix this?

**Comment by hueiyuan** [comment]
@mpduarte 
I do not fix this, still have this issue..

**Comment by lucarp** [comment]
This solution worked for me:

```UPDATED_MULTI_ROUTER_TEMPLATE = MULTI_PROMPT_ROUTER_TEMPLATE + '\n<< OUTPUT (must end with ```) >>\n'```

Then I used UPDATED_MULTI_ROUTER_TEMPLATE instead.

**Comment by giftednewbie** [comment]
> > I resolved the problem by adding an example at the end of the MULTI_PROMPT_ROUTER_TEMPLATE. Please check it as below.
> > ### eg:
> > << INPUT >> "What is black body radiation?" << OUTPUT >> `json {{{{ "destination": "physics", "next_inputs": "What is black body radiation?" }}}} `
> 
> In addition, to suggested solution, found out that the following worked just as well.
> 
> ```
> << OUTPUT (must include ```json at the start of the response) >>
> ```

Combining the above answer and the answer from @lucarp, helped in my case. Updating the << OUTPUT >> on the MULTI_PROMPT_ROUTER_TEMPLATE as below worked:

<< OUTPUT (must include \`\`\`json at the start of the response and must end with ```) >>
