### ISSUE TITLE
Tips for speeding up OpenAI API answers?

### ISSUE THREAD

**Issue by DennisPeeters** [langchain-ai/langchain#5169]
Hi,

I've seen applications that are able to give fast responses using the Langchain & OpenAI (chat with own data).

However, in my case responses on simple questions seem to take a long time. I've been playing around with settings but I am wondering if there is anything else I can do to increase speed.

Current settings:
- Chunk Size: 700
- Chunk Overlap: 100
- Max tokens: 150
- Streaming enabled

What am I missing?

thanks!

**Comment by DennisPeeters** [comment]
I use GPT-3.5-Turbo. I also tried with the davinci 003 and 002 models, and they are very fast but GPT-3.5-Turbo is better for my use case.

I see online tools that use Langchain and GPT-4 with a very fast response time so I guess it is possible.

**Comment by jamesjohnson1025** [comment]
Hi, facing similar issue even though streaming is enabled. Any ideas on how to speed up.

**Comment by DennisPeeters** [comment]
It is not an issue anymore. 

Just a suggestion: Count the tokens & price you have. With me I made the mistake of sending too much tokens

**Comment by jamesjohnson1025** [comment]
I agree with you that it's not an issue at all. LLM take plenty of time to compute the query. When you  enabled streaming, did you notice any change in computing the query. Hasn't the time taken to compute the query.
