### ISSUE TITLE
Bug in openapi agent planner

### ISSUE THREAD

**Issue by Srajangpt1** [langchain-ai/langchain#5186]
### System Info

Latest, macOS ventura, 3.8/11

It seems to be a bug when calling the server in create_openapi_agent. This is returning only the first letter of the server. Please see attached. 
<img width="616" alt="image" src="https://github.com/hwchase17/langchain/assets/10047986/11b95d67-e05b-406e-a1f1-c35ef3da6abe">

### Who can help?

@vowelparrot 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a new openapi_spec
2. Edit the server field
3. Create new openapi agent --> planner.create_openapi_agent(new_spec, requests_wrapper, llm)
4. I am also using gpt-3.5-turbo model (although it doesn't matter)
5. You could also just printout `spec.servers[0]["url"]`

### Expected behavior

The openapi agent should be initialized with the url as `base_url`

Removing `[0]["url"]` from `spec.servers[0]["url"]` should fix it

**Comment by Srajangpt1** [comment]
Oh my bad. I was referring to v2 spec.yml. With v3 openapi specs it works fine. Thaks for looking into it. Although at times it would be necessary to change that server name from time to time. but currently its not supported once the ReducedAPISpec   object is created. 
Also, how would an agent be able to use these specs from a vector store? Since the specs can be very large and we may hit token limit(which I am already hitting).

**Comment by vowelparrot** [comment]
For very large specs you'd probably get better performance by selecting the subset that's relevant for a set of functions. 

For putting them in a vector store -> it really depends on what you mean or want to do. If you want to use embedding distances for routing, you could do something like in these demo notebooks:
- https://python.langchain.com/en/latest/modules/agents/agents/custom_agent_with_tool_retrieval.html
- https://python.langchain.com/en/latest/use_cases/agents/custom_agent_with_plugin_retrieval.html
