### ISSUE TITLE
Answer from the SQLDatabaseChain does not output when using the Agent 'conversational-react-description'

### ISSUE THREAD

**Issue by pressembrero** [langchain-ai/langchain#5188]
### System Info

**MacOS Ventura Version 13.3.1
LangChain==0.0.178**

**When querying the database, the answer does not show in the terminal. Instead, the AI response is always: "Is there anything else I can help you with?". The response seems fine when not using the SQL tool.** 

```
db_chain = SQLDatabaseChain.from_llm(llm=llm, db=sql_database, verbose=True)
sql_tool = Tool(
    name='Student DB',
    func=db_chain.run,
    description="Useful for when you need to answer questions regarding the students, their information, attendance, and anything regarding the database. "
)

tools = load_tools(
    ["llm-math"],
    llm=llm
)

tools.append(sql_tool)

memory = ConversationBufferMemory(memory_key="chat_history")

conversational_agent = initialize_agent(
    agent='conversational-react-description',
    tools=tools,
    llm=llm,
    verbose=True,
    memory=memory
    
)
conversational_agent.run(input="Who were sick last May 22, 2023?")
```
Here is the output in the terminal:

<img width="1480" alt="Screenshot 2023-05-24 at 17 50 14" src="https://github.com/hwchase17/langchain/assets/108784595/47a86e82-f7d3-4a46-9a8f-5a9ec1d1d17a">

I always get the AI response instead that of the answer in 'Observation'. 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. create sqldatabasechain
2. create custom too for sql querying
3. use agent type conversational-react-description
4. output answer

### Expected behavior

I would like that the output of the chain, when using the sql tool, is the Query output and not the "Is there anything else I can help you with?" AI response.

**Comment by skippy107** [comment]
I have been able to solve this problem by setting return_direct = True when creating the SQLDatabaseChain.

**Comment by agenthunt007** [comment]
Were you able to get the query used?

**Comment by punsoca** [comment]
December 30, 2024

I am having a similar issue  - please see the screenshot provided -  my llm and db are set up correctly.
<img width="1044" alt="Screenshot 2024-12-30 at 1 36 25 PM" src="https://github.com/user-attachments/assets/2cd65487-f901-49a4-8105-2042468e7e3d" />


I am passing verbose=True parameter and return_direct=True parameters to my SQLDatabaseChain.invoke() statement.   As the screenshot shows,  the verbose result is showing the SQLResult correctly - e.g.,  (a single tuple in a list with a value of (59,) which is the expected count of my query.  But I am expecting Answer = '59' but it just regurgitated the generated SQL query.     How do I fix this?    All tutorials online (including Youtube) all show the "Answer" with the final statement.
