### ISSUE TITLE
openai.api_key in OpenAIEmbeddings  is unsafe  on  concurrency

### ISSUE THREAD

**Issue by richweng001** [langchain-ai/langchain#5195]
### System Info

like:
import openai
openai.api_key = openai_api_key

problem:
api_key is a global variable, it is not safe on concurrency  if we have different api_keys to be used concurrency.  api_key will out of control.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

use local variable

### Expected behavior

to be fix

**Comment by axiangcoding** [comment]
you should move this issue to https://github.com/openai/openai-python
