### ISSUE TITLE
Issue: Customizing 'structured_format_instructions' for Non-English Languages

### ISSUE THREAD

**Issue by luc-kalaora** [langchain-ai/langchain#5203]
HI, I have a requirement to customize the format instructions for multiple languages.

Specifically, I need to make modifications to the output_parser.get_format_instructions() string. This function currently utilizes the following structured format instructions:

```
STRUCTURED_FORMAT_INSTRUCTIONS = """The output should be a markdown code snippet formatted in the following schema, including the leading and trailing "

json" and "

":

{{
{format}
}}
```
To modify this value, I have considered the following approach:

> langchain.output_parsers.structured.STRUCTURED_FORMAT_INSTRUCTIONS = """traduction of the string below"""

However, please note that this approach is not thread-safe. If multiple users are simultaneously using my application with different languages, there is a risk of interference between their settings.

Could you please advise on the appropriate solution for this issue?

How i can do? May i miss something?

Thanks for your help

### Suggestion:

A solution could be to change  get_format_instructions(self) -> str function by adding a string params def get_format_instructions(self, cust_str_format_instructions) -> str:

Another solution is to create a class inherited from  StructuredOutputParser

```
from langchain.output_parsers.structured import _get_sub_string
from langchain.output_parsers.format_instructions import STRUCTURED_FORMAT_INSTRUCTIONS
from typing import List, Any



from pydantic import Field

class CustomStructuredOutputParser(StructuredOutputParser):
    language: str = Field(default=None)
    cust_struct_format_instructions: str = Field(default=None)

    def __init__(self, response_schemas: List[ResponseSchema], **data: Any):
        super().__init__(response_schemas=response_schemas, **data)
        if self.language == "fr_FR":
            self.cust_struct_format_instructions = """La sortie doit être un extrait de code au format markdown, formaté selon le schéma suivant, en incluant le début et la fin "\`\`\`json" et "\`\`\`":

            ```json
            {{
            {format}
            }}
            ```"""

    @classmethod
    def from_response_schemas(
        cls, response_schemas: List[ResponseSchema], language: str = None, cust_struct_format_instructions: str = None
    ) -> 'CustomStructuredOutputParser':
        return cls(response_schemas=response_schemas, language=language, cust_struct_format_instructions=cust_struct_format_instructions)

    def get_format_instructions(self) -> str:
        schema_str = "\n".join(
                [_get_sub_string(schema) for schema in self.response_schemas]
            )
        if self.cust_struct_format_instructions:
            return self.cust_struct_format_instructions.format(format=schema_str)
        return STRUCTURED_FORMAT_INSTRUCTIONS.format(format=schema_str)



summary_response_schemas = [
    ResponseSchema(name="resumé", description="Fournissez un résumé en une ou deux phrases."),
    ResponseSchema(name="types_réponses", description="Fournissez un objet JSON contenant jusqu'à 4 types de réponses distincts en tant que clés, et une description pour chaque type de réponse en tant que valeurs."),
]

summary_output_parser = CustomStructuredOutputParser.from_response_schemas(summary_response_schemas, language='EN_US')

summary_output_parser.get_format_instructions()
```

The problem is that if you are modifying the code, I have to maintain it.

**Comment by luc-kalaora** [comment]
Yes this issue is still relevant.

**Comment by guidorietbroek** [comment]
I need to change the format instructions to fix the ReAct prompt. So I think it will be really helpful if this can be customized. I also don't understand why you want to hardcode this, format instructions are so important for the good working of your total prompt.

**Comment by guidorietbroek** [comment]
We've created a subclass of the ConvoOutputParser and that way it is possible to edit the get_format_instructions() method to load your custom format instructions.

**Comment by luc-kalaora** [comment]
Thanks

Le mer. 11 oct. 2023, 20:38, Guido Rietbroek ***@***.***> a
écrit :

**Comment by DominiquePaul** [comment]
Is there any guide on how to do this? I also have this problem. Wouldn't it be possible to add something like a language code when the parser is defined?
