### ISSUE TITLE
I don't think Self-querying with Chroma is right

### ISSUE THREAD

**Issue by Badrul-Goomblepop** [langchain-ai/langchain#5205]
### System Info

Here is the link to the tutorial: https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/chroma_self_query.html

You can see on the page that the results do not seem to correlate to the question.  First question about dinosaurs brings back two movies that are nothing to do with dinosaurs. Then last question asking about 2 movies about dinosaurs brings back 3 movies - 2 of which are nothing to do with dinosaurs.

In fact I found I can type "What are some movies about cabbages?" and get back 3 random movie results.

This tutorial doesn't seem to work.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Follow the tutorial - in fact just read the the tutorial.

### Expected behavior

It should either bring back only movies matching your query, or if it brings back more than one it should give a score as to how confident it is. Right now it seems almost pointless.

**Comment by metenev** [comment]
@Badrul-Goomblepop I have a similar task (searching in Chroma and retrieve only relevant results), but without LLM and chains. The only workaroud I found at this moment is to do a `chroma.similarity_search_with_score`, loop through result tuples list and skip results with too high score (for example if `score > 1`). You can try to extend the `SelfQueryRetriever`.

**Comment by Badrul-Goomblepop** [comment]
@metenev Thanks, I'll try that!

**Comment by Badrul-Goomblepop** [comment]
Yes this can now be closed
