### ISSUE TITLE
Chroma integration .from_documents() isn't working

### ISSUE THREAD

**Issue by grumpyp** [langchain-ai/langchain#5207]
### System Info

langchain==0.0.178
Python 3.11.2

### Who can help?

@agola11 @hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`chroma.from_documents(texts, embeddings, persist_directory="chroma_db", collection_name="x")`

```   
query_texts = "tell me about whatsmyserp policy"
        res = collection.query(
                query_texts=query_texts,
                n_results=n_results,
                where=where or None,
                where_document=where_document or None
            )
```

printing res 
`{'ids': [[]], 'embeddings': None, 'documents': [[]], 'metadatas': [[]], 'distances': [[0.3748544454574585]]}` 

I believe it doesn't create the collection itself or something related to that, cause if I create the collection myself before it seems to work.

More information and our discussion in the thread of the Chroma discord: 
https://discord.com/channels/1073293645303795742/1110965198904369374

### Expected behavior

It should at least return the related documents,..

**Comment by dev2049** [comment]
is texts a list of strings? if so should use `Chroma.from_texts`

**Comment by francisjervis** [comment]
See https://github.com/imartinez/privateGPT/pull/318
