### ISSUE TITLE
Issue:How to use callback functions in a Langchain sequential chain

### ISSUE THREAD

**Issue by vencent-debug** [langchain-ai/langchain#5225]
### Issue you'd like to raise.

How to use callback functions in a Langchain sequential chain, such as 1->2->3. I want to loop through the 2 function n times in the middle, where the output of the 2 function is its input. At the end of the loop, the output of the 2 function is input to the 3 function, and the final result is obtained

**Comment by vencent-debug** [comment]
There are two types of sequential chains in LangChain:

SimpleSequentialChain: This is the simplest form of a sequential chain, in which each step has a single input/output, and the output of one step becomes the input of the next -1SimpleSequentialChain: The simplest form of sequential chains, where each step has a singular input/output,  and the output of one step is the input to the next.\n\n * SequentialChain:  A more general form of sequential chains, allowing for multiple inputs/outputs"}}.

SequentialChain: This is the more general form of sequential chain, which allows for multiple inputs/outputs -1SimpleSequentialChain: The simplest form of sequential chains, where each step has a singular input/output,  and the output of one step is the input to the next.\n\n * SequentialChain:  A more general form of sequential chains, allowing for multiple inputs/outputs"}}.

Here is an example of a SimpleSequentialChain:

python
Copy code
from langchain.llms import OpenAI
from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate

# This is an LLMChain to write a synopsis given a title of a play.
llm = OpenAI(temperature=.7)
template = """You are a playwright. Given the title of play, it is your job to write a synopsis for that title.

Title: {title}
Playwright: This is a synopsis for the above play:"""
prompt_template = PromptTemplate(input_variables=["title"], template=template)
synopsis_chain = LLMChain(llm=llm, prompt=prompt_template)

# This is an LLMChain to write a review of a play given a synopsis.
llm = OpenAI(temperature=.7)
template = """You are a play critic from the New York Times. Given the synopsis of play,  it is your job to write a review for that play.

Play Synopsis:
{synopsis}
Review from a New York Times play critic of the above play:"""
prompt_template = PromptTemplate(input_variables=["synopsis"], template=template)
review_chain = LLMChain(llm=llm, prompt=prompt_template)

# This is the overall chain where we run these two chains in sequence.
from langchain.chains import SimpleSequentialChain
overall_chain = SimpleSequentialChain(chains=[synopsis_chain, review_chain], verbose=True)

review = overall_chain.run("Tragedy at sunset on the beach")
In this example, we create two LLmchains, one for writing a script outline and one for writing a script review, and then we execute the two chains in sequence 1 in the SimpleSequentialChain.

**Comment by samueli** [comment]
i have the same question, when i split chain and run in a SequentialChain, the customized local function calling tool can't be used.

**Comment by DanielChuDC** [comment]
+1

**Comment by aleksanderhan** [comment]
I want to use different callbacks on different chains in the SequentialChain, but when i add those to the chains, the callback is not beeing called. Is there a way to get different chains to use different callbacks?

**Comment by rt-jar** [comment]
Why is it closed? Not solved yet.Please provide solution or reopen it.
