### ISSUE TITLE
Write File action_input issues. How to handle when action input is large

### ISSUE THREAD

**Issue by abhaybhargav** [langchain-ai/langchain#5226]
### System Info

I am trying to use the File System tools to generate some boilerplate source code using OpenAI's APIs, and the chain works, but does not write the file to the file-system. 

I think it is because there's an issue with the size of the text that needs to be written to the file, the agent fails to execute

My code is as follows

```python

import os
from langchain.tools.file_management import *
from langchain.agents.agent_toolkits import FileManagementToolkit
from langchain.llms.openai import OpenAI
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType
from dotenv import load_dotenv

load_dotenv()

toolkit = FileManagementToolkit()
write_files = toolkit.get_tools()[5]
list_files = toolkit.get_tools()[6]
read_files = toolkit.get_tools()[4]
llm = OpenAI(temperature=0)
tools = [
    Tool(
        name="Write Files to directory",
        func = write_files.run,
        description = "useful for when you need to write files to a local file system"
    ),
    Tool(
        name="List Files in directory",
        func = list_files.run,
        description = "useful for when you need to list files in a local file system"
    ),
    Tool(
        name="Read Files in directory",
        func = read_files.run,
        description = "useful for when you need to read files in a local file system"
    )
]

self_write_files_git = initialize_agent(
    tools,
    llm,
    agent = AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose = True
)
self_write_files_git.run("Generate a source code for a boilerplate Python Flask Application")

```

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce

1. My original source code is this

```python

import os
from langchain.tools.file_management import *
from langchain.agents.agent_toolkits import FileManagementToolkit
from langchain.llms.openai import OpenAI
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType
from dotenv import load_dotenv

load_dotenv()

toolkit = FileManagementToolkit()
write_files = toolkit.get_tools()[5]
list_files = toolkit.get_tools()[6]
read_files = toolkit.get_tools()[4]
llm = OpenAI(temperature=0)
tools = [
    Tool(
        name="Write Files to directory",
        func = write_files.run,
        description = "useful for when you need to write files to a local file system"
    ),
    Tool(
        name="List Files in directory",
        func = list_files.run,
        description = "useful for when you need to list files in a local file system"
    ),
    Tool(
        name="Read Files in directory",
        func = read_files.run,
        description = "useful for when you need to read files in a local file system"
    )
]

self_write_files_git = initialize_agent(
    tools,
    llm,
    agent = AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose = True
)
self_write_files_git.run("Generate a source code for a boilerplate Python Flask Application")

```

2. You can use it with a Jupyter Notebook/etc to run it you'll see the following

AgentExecutor creates the right action input, but the action_input seems cut off (JSON not properly formatted) and as a result, likely doesnt write to the filesystem 

### Expected behavior

Based on the plan, which shows up, I would assume that it would write it to the file-system

**Comment by domalbert** [comment]
Hello, 

I was facing the same issue. I think that maybe this query might help you more. My assumption why you were getting the error might also be related to how you define the description and your prompt. The question `Generate a source code for a boilerplate Python Flask Application` might not relate well to the agent being chosen. Here is an example that worked for me:

`import os
from langchain.tools.file_management import *
from langchain.agents.agent_toolkits import FileManagementToolkit
from langchain.llms.openai import OpenAI
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType

toolkit = FileManagementToolkit()
write_files = toolkit.get_tools()[5]
list_files = toolkit.get_tools()[6]
read_files = toolkit.get_tools()[4]
llm = OpenAI(temperature=0)
tools = [
    Tool(
        name="Write Files to directory",
        func = write_files.run,
        description = "useful for when you need to write files to a local file system"
    ),
    Tool(
        name="List Files in directory",
        func = list_files.run,
        description = "useful for when you need to list files in a local file system"
    ),
    Tool(
        name="Read Files in directory",
        func = read_files.run,
        description = "useful for when you need to read files in a local file system"
    )
]


conversational_memory = ConversationBufferWindowMemory(
        memory_key='chat_history',
        k=5,
        return_messages=True
)

agent = initialize_agent(
    agent='chat-conversational-react-description',
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=3,
    early_stopping_method='generate',
    memory=conversational_memory
)

#agent.run("How old is Madonna.")
agent.run("List all the files in the `directory.")``

**Comment by LarryStanley** [comment]
I add () fix problem, for example

```
tools = [
    Tool(name="read_file", description="Read file from disk", func=ReadFileTool().run),
    Tool(
        name="write_file", description="Write file from disk", func=WriteFileTool().run
    ),
    Tool(
        name="list_directory",
        description="List files and directories in a specified folder",
        func=ListDirectoryTool().run,
    ),
]

```

**Comment by mrhimanshu** [comment]
Too many arguments to single-input tool Write Files to directory. Args: ['data/hello.txt', 'hello world']

**Comment by Rishiguin** [comment]
> I'm getting Too many arguments to single-input tool Write Files to directory. Args: ['data/hello.txt', 'hello world']

same

**Comment by z791483920** [comment]
same
