### ISSUE TITLE
Issue: Dataframe with conversation agent for chat models

### ISSUE THREAD

**Issue by Rashie** [langchain-ai/langchain#5227]
I want to build a langchain which can
• can chat with human on greetings etc
And
• can do what the create_csv_agent does 
And 
• has a memory.

So i was using a conversational agent for chat models to do this with memory buffer

It is able to perform 1 and 3 from the things i want. I also gave 
tools = [PythonAstREPLTool(locals={"df": df})] as the tools to this agent. 

 But i am confused where i should give the dataframe df for the chat model similar to how we give for create_csv_agent. 

I tried giving it in the prompt by doing prompt.partial but i got an error saying partial method not implemented for chatprompttemplate.

I want the chat model to know that it has access to the df dataframe and questions like "what are top 2 issues " should be answered using that dataframe. 

Right now, it outputs saying that, sure i can provide top 2 issues, but please provide information on what data you want me to work on.

Can you help on this? Please let me know if you need additional information

**Comment by imeckr** [comment]
You can add [pandas agent](https://python.langchain.com/en/latest/modules/agents/toolkits/examples/pandas.html) as a tool to your CoversationalAgent, this tool takes pd.DataFrame as an argument where you can specify your dataframe.
