### ISSUE TITLE
Make Redis Vector database operations Asynchronous

### ISSUE THREAD

**Issue by Octforce** [langchain-ai/langchain#5234]
### Feature request

There are other vector database that support the use of async in Langchain, adding Redis to those list would be better for programmers who use asynchronous programming in python. I believe with package like aioredis, this should be easily achievable.

### Motivation

The motivation to to be able to support python async programmers with this feature and also to boost performance when querying from the vector store and inserting data into the vector store.

### Your contribution

I can contribute by opening a PR or by testing the code once it is done.

**Comment by Octforce** [comment]
cc: @tylerhutcherson

**Comment by jbkoh** [comment]
https://github.com/hwchase17/langchain/pull/2849
