### ISSUE TITLE
Support for ttl in DynamoDBChatMessageHistory

### ISSUE THREAD

**Issue by Benyuel** [langchain-ai/langchain#5235]
### Feature request

Allow a user to specify a record ttl for messages/sessions persisted to dynamodb in https://github.com/hwchase17/langchain/blob/5cfa72a130f675c8da5963a11d416f553f692e72/langchain/memory/chat_message_histories/dynamodb.py#L17-L20.

### Motivation

This will allow automated purging of chat history after a specified time period.  

### Your contribution

Maybe, depends on my available time.

**Comment by faradri** [comment]
Hi!

I think that it's still relevant to the latest version of LangChain repository. 
I could work on it if it's possible to re-open this issue.

Thank you
