### ISSUE TITLE
'numpy._DTypeMeta' object is not subscriptable

### ISSUE THREAD

**Issue by prashantkanuru** [langchain-ai/langchain#5242]
### System Info

I am using langchain version of 0.0.176 and hitting the error of 'numpy._DTypeMeta' object is not subscriptable while using Chroma DB for carrying out any operation. 

### Who can help?

@hwchase17  - please help me out with this error -- do I need to upgrade the version of Langchain to overcome this problem

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Code snippets producing this behavior
1. docsearch=Chroma.from_texts(texts,embeddings,metadatas=[{"source":str(i)} for i in range(len(texts))]).as_retriever()
2. docsearch=Chroma.from_texts(texts,embeddings)
query="...."
docs=docsearch.similarity_search(query)
3. db1=Chroma.from_documents(docs_1,embeddings)

### Expected behavior

Should be able to use ChromaDb as a retriever without hitting any error.

**Comment by lfoppiano** [comment]
Same issue with 0.0.187
