### ISSUE TITLE
Issue: import 'LLMContentHandler' from 'langchain.llms.sagemaker_endpoint failing

### ISSUE THREAD

**Issue by shridhars** [langchain-ai/langchain#5245]
### Issue you'd like to raise.

`!pip3 install langchain==0.0.179 boto3`

After installing langchain using the above command and trying to run the example mentioned in

[](https://python.langchain.com/en/latest/modules/models/llms/integrations/sagemaker.html)

Getting the below error.

`ImportError:` cannot import name 'LLMContentHandler' from 'langchain.llms.sagemaker_endpoint' `(/opt/conda/lib/python3.10/site-packages/langchain/llms/sagemaker_endpoint.py)`

Am I missing something

**Comment by dev2049** [comment]
hm can't seem to reproduce

**Comment by shridhars** [comment]
> hm can't seem to reproduce https://colab.research.google.com/drive/1Z_pzF674PKU_1VZFFg3Y0f9NOWR9Qle9#scrollTo=k5AMMExkoWyY

Entire Script Seems to be working fine in Standalone Containers, problem occurs while running in sagemaker notebook cells. Let me look further, if not will connect back.
