### ISSUE TITLE
how to monitoring the new files after directory loader class used

### ISSUE THREAD

**Issue by jamsnrihk** [langchain-ai/langchain#5252]
### Feature request

I am using langchain + openai api to create a chatbot for private data, i can use langchain directory loader class to load files from a directory, but if any new files added to that directory, how to automatically load it?

### Motivation

https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/file_directory.html

### Your contribution

if can solve the problem, it will be good for company to use it for internal knowdege base share.

**Comment by YLFxGen** [comment]
I don't feel that it's within the scope of langchain. If you want to achieve this feature, you can 
- Use libraries such as watchdog to monitor your file system and trigger ingestion once detect any file addition/deletion.
- Have a button to call API to scan the folder and ingest/remove changed files.
- Schedule a task to periodically scan the folder and ingest/remove changed files.

**Comment by jamsnrihk** [comment]
Thanks for your advice.
