### ISSUE TITLE
Issue: <Streaming mode not work for Sequential Chains>

### ISSUE THREAD

**Issue by SaaS1973** [langchain-ai/langchain#5254]
### Issue you'd like to raise.

hi, team:

I created Chain_A and Chain_B and set streaming=True for both of them.

overall_chain = SequentialChain(
    chains=[chain_A, chain_B],
    input_variables=["era", "title"],
    output_variables=["synopsis", "review"],
    verbose=True)

However, the streaming does not work.

**Comment by dev2049** [comment]
could you provide full code snippet to reproduce (ie what're chain_A and chain_B in this case)
