### ISSUE TITLE
Inconsistent documentation for langchain.chains.FlareChain

### ISSUE THREAD

**Issue by james-310110** [langchain-ai/langchain#5255]
### Question
Will there be future updates where we are allowed to customize answer_gen_llm when using FlareChain?

### Context
In the [documentation](https://python.langchain.com/en/latest/modules/chains/examples/flare.html) it says that:

In order to set up this chain, we will need three things:
- An LLM to generate the answer
- An LLM to generate hypothetical questions to use in retrieval
- A retriever to use to look up answers for

However, the example code only allows specification for the question_gen_llm, not the answer_gen_llm. 

After referencing the [code](https://github.com/hwchase17/langchain/blob/9c0cb90997db9eb2e2a736df458d39fd7bec8ffb/langchain/chains/flare/base.py) for FlareChain, it seems that the answer_gen_llm is initialized as `OpenAI(max_tokens=32, model_kwargs={"logprobs": 1}, temperature=0)`, which default to `"text-davinci-003"` as no model_name is specified.

**Comment by dev2049** [comment]
hey @james-310110, thanks for flagging! that is confusing wording, we should update

`from_llm` is just a helper constructor. you're correct in that if you use that, you can only set the question_gen_llm. To customize you'd want to instantiate the FlareChain directly using `FlareChain(question_generator_chain=..., response_chain=..., ...)`. When doing that you initialize the question_generator_chain yourself, and within that you can use whatever LLM you want. See here for the full set of instantiation params https://github.com/hwchase17/langchain/blob/9c0cb90997db9eb2e2a736df458d39fd7bec8ffb/langchain/chains/flare/base.py#L99
