### ISSUE TITLE
Add integration for LocalAI

### ISSUE THREAD

**Issue by mudler** [langchain-ai/langchain#5256]
### Feature request

Integration with LocalAI and with its extended endpoints to download models from the gallery.

### Motivation

LocalAI is a self-hosted OpenAI drop-in replacement with support for multiple model families: https://github.com/go-skynet/LocalAI

### Your contribution

Not a python guru, so might take few cycles away here.

**Comment by pratham-saraf** [comment]
Hey I would like to take upon this task and would be willing to contribute 
can this be assigned to me 
regards

**Comment by l4b4r4b4b4** [comment]
I would highly appreciate this issue being picked up again! 

The issue with the current state of affairs is that AzureChatOpenAI and ChatOpenAI both send requests to `/v1/openai/deployments/MODEL_NAME/chat/completions` but LocalAI expects completion requests to hit `/v1/chat/completions`.

**Comment by benm5678** [comment]
> I would highly appreciate this issue being picked up again!
> 
> The issue with the current state of affairs is that AzureChatOpenAI and ChatOpenAI both send requests to `/v1/openai/deployments/MODEL_NAME/chat/completions` but LocalAI expects completion requests to hit `/v1/chat/completions`.

We have the same issue... is there some workaround to point it at LocalAI w/o too many code changes?

**Comment by l4b4r4b4b4** [comment]
> > I would highly appreciate this issue being picked up again!
> > The issue with the current state of affairs is that AzureChatOpenAI and ChatOpenAI both send requests to `/v1/openai/deployments/MODEL_NAME/chat/completions` but LocalAI expects completion requests to hit `/v1/chat/completions`.
> 
> We have the same issue... is there some workaround to point it at LocalAI w/o too many code changes?

use another backend :sweat_smile:

**Comment by mudler** [comment]
> I would highly appreciate this issue being picked up again!
> 
> The issue with the current state of affairs is that AzureChatOpenAI and ChatOpenAI both send requests to `/v1/openai/deployments/MODEL_NAME/chat/completions` but LocalAI expects completion requests to hit `/v1/chat/completions`.

I'm wondering what openai client version are you using? `/v1/chat/completions` is actually what is used currently https://platform.openai.com/docs/api-reference/chat/create

**Comment by benm5678** [comment]
> both send requests to `/v1/openai/deployments/MODEL_NAME/chat/completions` but LocalAI expects completi

From my experience, when you have OPENAI_API_TYPE set to 'azure' latest Langchain (v0.0.354) ChatOpenAI goes to `/v1/openai/deployments/MODEL_NAME/chat/completions`, but if you switch OPEN_AI_TYPE to 'open_ai' it goes to `/v1/engines/MODEL_NAME/chat/completions` -- but LocalAI is not implementing this endpoint.
