### ISSUE TITLE
Issue: RetrievalQA -> ConversationalChatAgent -> AgentExecutor gives no response if document-related

### ISSUE THREAD

**Issue by ronasuti** [langchain-ai/langchain#5266]
### Issue you'd like to raise.

Hi everybody,

I'm working with an LLM setup inspired from @pelyhe 's implementation #4573 .
It uses a RetrievalQA that queries a persistent embedded ChromaDB, then feeds it into a ConversationalChatAgent and then an AgentExecutor.

Currently, this setup works for only basic situations which definitely have nothing to do with documents. Once I ask it something document relevant, it gives an empty response. I have a nagging suspicion I've simply wired things up incorrectly, but it's not clear how to fix it.
```
@st.cache_resource
def load_agent():
    vectorstore = Chroma(persist_directory=CHROMA_DIR)

    basic_prompt_template = """If the context is not relevant, 
    please answer the question by using your own knowledge about the topic.
    
    ###Context:
    {context}
    ###Human:
    {question}
    ###Assistant:
    """

    prompt = PromptTemplate(
        template=basic_prompt_template, input_variables=["context", "question"]
    )

    system_msg = "You are a helpful assistant."

    chain_type_kwargs = {"prompt": prompt}
    # Time to initialize the LLM, as late as possible so everything not requiring the LLM instance to fail fast
    llm = GPT4All(
        model=MODEL,
        verbose=True,
    )

    # Initialise QA chain for document-relevant queries
    qa = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=vectorstore.as_retriever(),
        chain_type_kwargs=chain_type_kwargs,
    )

    tools = [
        Tool(
            name="Document tool",
            func=qa.run,
            description="useful for when you need to answer questions from documents.",
        ),
    ]

    agent = ConversationalChatAgent.from_llm_and_tools(
        llm=llm, tools=tools, system_message=system_msg, verbose=True
    )

    return AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        verbose=True,
        memory=ConversationBufferMemory(
            memory_key="chat_history", return_messages=True
        ),
    )


agent = load_agent()

###########################
# Streamlit UI operation. #
###########################
if "generated" not in st.session_state:
    st.session_state["generated"] = []

if "past" not in st.session_state:
    st.session_state["past"] = []


def get_text():
    input_text = st.text_input(label="", key="question")
    return input_text


user_input = get_text()

if user_input:
    try:
        output = agent.run(input=user_input)
    except ValueError as e:
        output = str(e)
        if not output.startswith("Could not parse LLM output: "):
            raise Exception(output)
        output = output.removeprefix("Could not parse LLM output: ").removesuffix("`")
    st.session_state.past.append(user_input)
    st.session_state.generated.append(output)

if st.session_state["generated"]:
    for i in range(len(st.session_state["generated"]) - 1, -1, -1):
        message(st.session_state["generated"][i], key=str(i))
        message(st.session_state["past"][i], is_user=True, key=str(i) + "_user")
```

**Comment by ronasuti** [comment]
@praneetreddy017 Hi Praneet, mind taking a quick poke at this? My main issue is I'm trying to feed the related data to a GPT4All LLM. In theory, that LLM should be powerful enough to accomplish the given task (mpt-7b-instruct, arguably the best performing model at its size). If there's any tricks you may know for improving this (better specialized LLMs for QA and ConversationalChatAgent, prompt tricks, etc) I'd love that :)

**Comment by praneetreddy017** [comment]
Hey friend @ronasuti
Is it okay if I experiment with this code by yanking out the streamlit portion of the code and making it simpler for my debugging purposes or is there anything in there which is essential to your pipeline.

My goal was to simplify and debug so that you can take a look and scale up.
If we find an error in the internal implementation, we could possibly try to fix/issue a PR

**Comment by praneetreddy017** [comment]
Hey friend @ronasuti

I looked into the issue and I am not sure I have enough time to debug the current implementation. Would it be okay with you if I provided you an alternate implementation within 2 days?

Are you very particular about using a ConversationalChatAgent and an AgentExecutor

**Comment by ronasuti** [comment]
Oh okay, I was excited to try agents as they are really good at doing multi-step operations, but I guess that might not be feasible with locally hosted models like this as they're less sophisticated. I guess the alternative is a RouterChain setup, ie. MultiRetrievalQAChain.

**Comment by ronasuti** [comment]
Specifically, I wanted a system that could eventually do multiple things, ie. pull from a Chroma vectorstore and issue commands to the AWS API, but as I'll be merging codebases with another team eventually I'm not particularly attached to this implementation.

**Comment by praneetreddy017** [comment]
I'll work an alternative with an agent soon and send you the code man. I'm
currently in the middle of a ton of job interviews and I'm very exhausted.
Otherwise I usually make it a point to help a lot of people here having
issues on the Langchain git. Will definitely help you soon.

**Comment by ronasuti** [comment]
Thank you so much! No need to rush :)
I saw the last time you got it to work, OpenAI was being used which I imagine is much more capable, so it's more likely a limitation of the models I'm using, they're simply not up to the task of agent based operation I guess. Could a traditional ConversationalRetrievalChain be made to answer questions even if they're not covered in ChromaDB?

**Comment by praneetreddy017** [comment]
What do you mean by "not covered in ChromaDB". Btw you're right about the
model capability part.

**Comment by ronasuti** [comment]
I mean that if I give a ConversationalRetrievalChain a question that isn't relevant to documents in ChromaDB, it should answer as if it were just a normal LLM without document retrieval.
