### ISSUE TITLE
ZeroShotAgent fails with ShellTool due to quotes in llm output

### ISSUE THREAD

**Issue by bmcclanahan** [langchain-ai/langchain#5271]
https://github.com/hwchase17/langchain/blob/7652d2abb01208fd51115e34e18b066824e7d921/langchain/agents/mrkl/output_parser.py#L47

Due to the line above the `ShellTool` fails when using it with the `ZeroShotAgent`. In using `langchain.OpenAI` as the `llm` I encountered a scenario where ChatGPT provides a string surrounded by single quotes for `Action Input:`. This causes the ShellTool not to recognize the input command because it is surrounded by single quotes which aren't stripped (I get a command not found error). This could easily be fixed by stripping single quotes from `action_input`. 

```
return AgentAction(action, action_input.strip(" ").strip('"').strip("'"), text) 
```

**Comment by mehradans92** [comment]
Hi @bmcclanahan. Has this issue been solved?

**Comment by bmcclanahan** [comment]
I have solved it for my personal use by just updating the code on my machine to strip single quotes (as described above) but it isn't resolved in the repository.
