### ISSUE TITLE
When initializing ChatVertexAI fastapi thread pool becomes unaccessible 

### ISSUE THREAD

**Issue by bjk95** [langchain-ai/langchain#5275]
### System Info

When I initialise ChatVeretexAI in a fastAPI app the thread pool never returns to idle blocking the server returning the below error.

E0526 10:18:51.289447000 4300375424 thread_pool.cc:230]                Waiting for thread pool to idle before forking

on langchain 0.180

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Initialise ChatVertexAI in a fastapi app. ChatOpenAI works fine.

### Expected behavior

Don't error

**Comment by lkuligin** [comment]
Could you share more context on how you app looks like, please?
