### ISSUE TITLE
change tuple sql result to dict sql result

### ISSUE THREAD

**Issue by BriskyGates** [langchain-ai/langchain#5284]
### Feature request

Hey guys,thanks for your amazing work, if I want to get a dictionary SQL result instead of the default tuple in SQLDatabaseChain, what settings do I need to change?

### Motivation

Without database table header fields, the articles generated by LLM may contain errors.

### Your contribution

I am currently diving into the codes and see how to deal with it

**Comment by yutakobayashidev** [comment]
Langchain seems to use sqlalchemy, so if we could implement code like this, it might solve the problem
```
# Connect to the database
con = ENGINE.connect()

# Prepare the SQL query
query = text("SELECT * FROM Member WHERE name = :name")

# Execute the query with the given parameters
result = con.execute(query, {"name": "Joe Doe"})

# Fetch all rows from the result
rows = result.fetchall()

diet = [r._asdict() for r in rows]
```

or

```
diet = result.mappings().all()
```
