### ISSUE TITLE
Get the source document info with result 

### ISSUE THREAD

**Issue by Sadaf-Syeda** [langchain-ai/langchain#5295]
### System Info

ValueError: `run` not supported when there is not exactly one output key. Got ['result', 'source_documents'
]

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

qa = RetrievalQA.from_chain_type(
    llm=OpenAI(),
    chain_type = "stuff",
    retriever=db.as_retriever(),
return_source_documents=True
)

agent = ZeroShotAgent(llm_chain=llm_chain, tools=tools, verbose=True)#, output_keys=['result','source_documents'])
agent_chain = AgentExecutor.from_agent_and_tools(
  agent=agent, tools=tools, verbose=True, memory=memory)# return_intermediate_steps=True)#, output_keys=['result','source_documents']
 
#)

### Expected behavior

Returns the answer and source doc as well

**Comment by vermaat** [comment]
Same error message here when using a `VectorDBQAWithSourcesChain` as tool in combination with an agent. 

Using the following workaround I got it to work (adding the lambda).
```
tool_data_source = Tool(
                    name = data_source_name,
                    func=lambda question: chain({"question": question}, return_only_outputs=False),
                    description="data set description",
                    return_direct=True, # Finish the chain directly after using this tool.
                )
```

It returns the 'answer' 'question, and 'sources' nested in the 'output' key

**Comment by sagardesai-ml-mlops** [comment]
faced same issue work with 

`result = chain(query)`

`result = chain.run(query) `
throws error

**Comment by paluchasz** [comment]
It seems you have to call qa directly with `qa({"query": query})` see https://python.langchain.com/docs/modules/chains/popular/vector_db_qa.
