### ISSUE TITLE
Difference among various ways to query database and return source information? (Question Answering with Sources, Retrieval Question Answering with Sources, index.query_with_sources, etc.)

### ISSUE THREAD

**Issue by cyberjj999** [langchain-ai/langchain#5328]
### Issue you'd like to raise.

What are the key differences between these methods of trying to query/ask a database, then return the answer along with its relevant sources?

My main objective is to have a Chatbot that has knowledge from a knowledge base, and can still maintain conversation history. Their answer must return me the source document as well. Which option is the best among so many choices?

There are

1. [Question Answering with Sources](https://python.langchain.com/en/latest/modules/chains/index_examples/qa_with_sources.html), 
```
chain = load_qa_with_sources_chain(OpenAI(temperature=0), chain_type="stuff")
query = "What did the president say about Justice Breyer"
chain({"input_documents": docs, "question": query}, return_only_outputs=True)
```

2. [Retrieval Question Answering with Sources](https://python.langchain.com/en/latest/modules/chains/index_examples/vector_db_qa_with_sources.html)
```
from langchain import OpenAI

chain = RetrievalQAWithSourcesChain.from_chain_type(OpenAI(temperature=0), chain_type="stuff", retriever=docsearch.as_retriever())

chain({"question": "What did the president say about Justice Breyer"}, return_only_outputs=True)
```

3. [Question Answering over Docs](https://python.langchain.com/en/latest/use_cases/question_answering.html)
```
from langchain.indexes import VectorstoreIndexCreator
index = VectorstoreIndexCreator().from_loaders([loader])

query = "What did the president say about Ketanji Brown Jackson"
index.query_with_sources(query)
```

++ probably quite a few more examples I could find if I dig through the documentation.

**Comment by imeckr** [comment]
All of them differ basis how the information is retrieved from sources and how it is passed in the context to the LLM. For e.g.

- `load_qa_with_sources_chain` (are type of `CombineDocumentsChain`): Puts all the docs in the context window directly using method various methods, it doesn't uses a document retriever.
  - `stuff` the default method - which puts the docs as is in prompt
  - `map_reduce` method summarizes each docs w.r.t the question and then `stuff` it in the context.
- `RetrievalQAWithSourcesChain` (uses `QAWithSourcesChain`) : This chain uses a retriever to first figure out the relevant docs that might help answering the question. It then uses a `CombineDocumentsChain` to put these relevant docs in the context.
- `VectorStoreIndexWrapper.query_with_sources` is just a wrapper around `RetrievalQAWithSourcesChain` and works the same.

Given that you need QA over knowledge base with history, you should use `ConversationalRetrievalChain` https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html

**Comment by cyberjj999** [comment]
Thank you for your very helpful comment. I tried experimenting with the code you shared, and eventually came up with this.
```
llm = OpenAI(temperature=0)
    doc_chain = load_qa_with_sources_chain(llm, chain_type="map_reduce")


    question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)
    chain = ConversationalRetrievalChain(
        retriever=vectorstore.as_retriever(),
        question_generator=question_generator,
        combine_docs_chain=doc_chain,
        memory=memory,
        return_source_documents=True,
    )
```

Now I have a surface-level understanding of how this works, but I'd appreciate a clearer explanation.

Correct me if I'm wrong, but in this code, we're using the `load_qa_with_sources_chain` which uses the `map_reduce` method as the main chain to combine different documents together.

If my understanding is correct, what the qa chain does is that it splits the list of documents into text chunks, then runs an initial prompt on each chunk of data, then runs a final prompt to combine all the output.

**Question**: What exactly is the "initial prompt" in this case since I didn't pass in anything? Is it hardcoded in the source code? Can and should I modify it to improve the performance?

This is where I get a little confused; if the qa chain is already combining all the documents, what is the `retriever` used for since the docs are already summarized? Isn't a retriever used as part of the similarity search algo (i.e. convert text chunks to vectors, then do similarity search based on a prompt to find documents that may be relevant)? OR, is the similarity search done FIRST, then when we get a list of, say 10 similar docs out of 100 docs, then we run the qa chain to combine the 10 docs together?

Now that the documents aspect is settled, I presume the chat history is settled by the `memory` argument and `question_generator` prompt which has a prompt that passes in both the context and the memory to get the best output possible.

I hope my question isn't too confusing haha. I am merely curious if

1. My understanding is correct
2. If my current code implementation for my usecase (i.e. ability to chat over knowledge base with memory) is correct/ideal.

Thank you so much and im looking forward to your response @imeckr!

**Comment by imeckr** [comment]
> Question: What exactly is the "initial prompt" in this case since I didn't pass in anything? Is it hardcoded in the source code? Can and should I modify it to improve the performance?

You can specify your initial prompt (prompt used in the map chain) via the `question_prompt` kwarg in the `load_qa_with_sources_chain` function. In case you don't pass, it defaults to `langchain.chains.qa_with_sources.map_reduce_prompt.QUESTION_PROMPT`. IMO, one should try with different prompt phrasing, it could have a lot of impact on the output.

> is the similarity search done FIRST, then when we get a list of, say 10 similar docs out of 100 docs, then we run the qa chain to combine the 10 docs together?

Yes

>Now that the documents aspect is settled, I presume the chat history is settled by the memory argument and question_generator prompt which has a prompt that passes in both the context and the memory to get the best output possible.

Yes, `question_generator`chain takes the current question and memory(previous chat) to create a "new question" that is passed to the `combine_docs_chain`

You can see the source code below to see how it works.
https://github.com/hwchase17/langchain/blob/e2742953a6ff2f9cce771164d012bf9af0fc04e5/langchain/chains/conversational_retrieval/base.py#L89-L116
