### ISSUE TITLE
Using OpenLM example giving error: "ValueError: OPENAI_API_KEY is not set or passed as an argument"

### ISSUE THREAD

**Issue by pst2154** [langchain-ai/langchain#5347]
### System Info

Running latest versions of langchain, openai, openlm, python 3.10, mac M1, trying this example I saw on Twitter

https://python.langchain.com/en/latest/modules/models/llms/integrations/openlm.html?highlight=openlm

```
from langchain.llms import OpenLM
from langchain.llms import OpenAI
from langchain.llms import openai
from langchain import PromptTemplate, LLMChain

openai.api_key = os.getenv("OPENAI_API_KEY")

question = "What is the capital of France?"
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])


llm1 = OpenAI()

llm2 = OpenLM(model="text-davinci-003")
llm_chain1 = LLMChain(prompt=prompt, llm=llm1)
llm_chain2 = LLMChain(prompt=prompt, llm=llm2)
result1 = llm_chain1.run(question)
result2 = llm_chain2.run(question)
```

result 1 runs, result 2 gives ValueError: OPENAI_API_KEY is not set or passed as an argument

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.llms import OpenLM
from langchain.llms import OpenAI
from langchain.llms import openai
from langchain import PromptTemplate, LLMChain

openai.api_key = os.getenv("OPENAI_API_KEY")

question = "What is the capital of France?"
template = """Question: {question}

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["question"])


llm1 = OpenAI()

llm2 = OpenLM(model="text-davinci-003")
llm_chain1 = LLMChain(prompt=prompt, llm=llm1)
llm_chain2 = LLMChain(prompt=prompt, llm=llm2)
result1 = llm_chain1.run(question)
result2 = llm_chain2.run(question)
```

### Expected behavior

Run without error

**Comment by ninjapenguin** [comment]
Can you confirm this is still an issue with the latest version? 

I am unable to replicate this on 0.0.184
