### ISSUE TITLE
DOC: SteamshipImageGenerationTool returns Config Error in multi_modal_output_agent.ipynb

### ISSUE THREAD

**Issue by panyi121** [langchain-ai/langchain#5358]
### Issue with current documentation:

When running multi_modal_output_agent.ipynb: https://python.langchain.com/en/latest/use_cases/agents/multi_modal_output_agent.html, I get ConfigError: field "steamship" not yet prepared so type is still a ForwardRef, you might need to call SteamshipImageGenerationTool.update_forward_refs().

tools = [
    SteamshipImageGenerationTool(model_name= "dall-e")
]
---------------------------------------------------------------------------
ConfigError                               Traceback (most recent call last)
Cell In[7], line 2
      1 tools = [
----> 2     SteamshipImageGenerationTool(model_name= "dall-e")
      3 ]

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/main.py:339, in pydantic.main.BaseModel.__init__()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/main.py:1076, in pydantic.main.validate_model()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/fields.py:860, in pydantic.fields.ModelField.validate()

ConfigError: field "steamship" not yet prepared so type is still a ForwardRef, you might need to call SteamshipImageGenerationTool.update_forward_refs().

After I call SteamshipImageGenerationTool.update_forward_refs(), I get another error. 

SteamshipImageGenerationTool.update_forward_refs()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[10], line 1
----> 1 SteamshipImageGenerationTool.update_forward_refs()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/main.py:815, in pydantic.main.BaseModel.update_forward_refs()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/typing.py:562, in pydantic.typing.update_model_forward_refs()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/typing.py:528, in pydantic.typing.update_field_forward_refs()

File ~/miniconda3/envs/langchain/lib/python3.11/site-packages/pydantic/typing.py:66, in pydantic.typing.evaluate_forwardref()

File ~/miniconda3/envs/langchain/lib/python3.11/typing.py:864, in ForwardRef._evaluate(self, globalns, localns, recursive_guard)
    859 if self.__forward_module__ is not None:
    860     globalns = getattr(
    861         sys.modules.get(self.__forward_module__, None), '__dict__', globalns
    862     )
    863 type_ = _type_check(
--> 864     eval(self.__forward_code__, globalns, localns),
    865     "Forward references must evaluate to types.",
    866     is_argument=self.__forward_is_argument__,
    867     allow_special_forms=self.__forward_is_class__,
    868 )
    869 self.__forward_value__ = _eval_type(
    870     type_, globalns, localns, recursive_guard | {self.__forward_arg__}
    871 )
    872 self.__forward_evaluated__ = True

File <string>:1

NameError: name 'Steamship' is not defined

**Comment by PAndreew** [comment]
I've encountered the same issue. The source for the SteamShipGenerationTool class be found here: [https://python.langchain.com/en/latest/_modules/langchain/tools/steamship_image_generation/tool.html]. I redefined the class without the "try: from steamship import Steamship" block and imported Steamship outside of the class' scope. It seems to work.

**Comment by rajib76** [comment]
I am still getting this error

**Comment by MatrixA** [comment]
> I am still getting this error

Same here, so what's wrong?

**Comment by doudou-itachi** [comment]
Is there a solution to this problem, the above link seems to be invalid

**Comment by YoloZyk** [comment]
I'm facing the same error, so what's wrong?
