### ISSUE TITLE
DOC: the example on setting model_kwrgs in HuggingFaceEmbeddings does not work

### ISSUE THREAD

**Issue by chanansh** [langchain-ai/langchain#5363]
### Issue with current documentation:

The example in https://python.langchain.com/en/latest/reference/modules/embeddings.html 
```
from langchain.embeddings import HuggingFaceEmbeddings

model_name = "sentence-transformers/all-mpnet-base-v2"
model_kwargs = {'device': 'cpu'}
hf = HuggingFaceEmbeddings(model_name=model_name, model_kwargs=model_kwargs)
```
does not work.
I get an error: 
> pydantic.error_wrappers.ValidationError: 1 validation error for HuggingFaceEmbeddings
model_kwargs
  extra fields not permitted (type=value_error.extra)

### Idea or request for content:

fixed example

**Comment by imeckr** [comment]
This should work, I think you might have an old version.

**Comment by heweapon** [comment]
> 

Have you solved this problem yet? I also met

**Comment by chanansh** [comment]
Upgrade worked

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
