### ISSUE TITLE
Formatter chain

### ISSUE THREAD

**Issue by pors** [langchain-ai/langchain#5374]
### Feature request

Creation of a chain or wrapper that uses two LLMs with different models to force correct formatting:
- do the "difficult" work with a model like GPT-4: output format is free text.
- have a second LLM (davinci-003 or a specialized model for this purpose) that is good at following formatting instructions to convert the output of the first model into (say) JSON.

### Motivation

When a model is set up to be creative, or the use case demands that the output is consistently formatted correctly, we are often out of luck, and the output breaks an app.  This proposed use of two models will most likely increase the accuracy of the output a lot.

### Your contribution

If maintainers think this is a good idea, please add your input, and I will be happy to provide a PR.

**Comment by murari-goswami** [comment]
Can we not do formatting with the same model. I am curious why we need a different model to do that ?

**Comment by pors** [comment]
Yes we can, but in case the model doesn't follow the formatting
instructions, which it sometimes doesn't, a non-chat model can do that more
reliably.

**Comment by sofi444** [comment]
This would be useful imo. Formatting instructions change the prompt and therefore the generation. In some cases you might want the formatting to happen separately from the main call (either with the same model or another). For example, if one wants to analyse the original generation but also benefit from the ease of having the output formatted nicely. Correct me if I am wrong or if there is already a way to do this..
