### ISSUE TITLE
FLARE | Azure open Ai doesn't work

### ISSUE THREAD

**Issue by waadarsh** [langchain-ai/langchain#5414]
### System Info

Langchain 0.0.182, python 3.11.3, mac os 

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [x] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

FLARE with azure open ai causes this issue.

InvalidRequestError Traceback (most recent call last)
in <cell line: 1>()
----> 1 flare.run(query)

20 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py](https://localhost:8080/#) in __prepare_create_request(cls, api_key, api_base, api_type, api_version, organization, **params)
81 if typed_api_type in (util.ApiType.AZURE, util.ApiType.AZURE_AD):
82 if deployment_id is None and engine is None:
---> 83 raise error.InvalidRequestError(
84 "Must provide an 'engine' or 'deployment_id' parameter to create a %s"
85 % cls,

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>

### Expected behavior

> Entering new FlareChain chain...
Current Response: 
Prompt after formatting:
Respond to the user message using any relevant context. If context is provided, you should ground your answer in that context. Once you're done responding return FINISHED.

>>> CONTEXT: 
>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> RESPONSE: 

> Entering new QuestionGeneratorChain chain...
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " decentralized platform for natural language processing" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " uses a blockchain" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " distributed ledger to" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " process data, allowing for secure and transparent data sharing." is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " set of tools" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " help developers create" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " create an AI system" is:
Prompt after formatting:
Given a user input and an existing partial response as context, ask a question to which the answer is the given term/entity/phrase:

>>> USER INPUT: explain in great detail the difference between the langchain framework and baby agi
>>> EXISTING PARTIAL RESPONSE:  
The Langchain Framework is a decentralized platform for natural language processing (NLP) applications. It uses a blockchain-based distributed ledger to store and process data, allowing for secure and transparent data sharing. The Langchain Framework also provides a set of tools and services to help developers create and deploy NLP applications.

Baby AGI, on the other hand, is an artificial general intelligence (AGI) platform. It uses a combination of deep learning and reinforcement learning to create an AI system that can learn and adapt to new tasks. Baby AGI is designed to be a general-purpose AI system that can be used for a variety of applications, including natural language processing.

In summary, the Langchain Framework is a platform for NLP applications, while Baby AGI is an AI system designed for

The question to which the answer is the term/entity/phrase " NLP applications" is:

**Comment by lingfengchencn** [comment]
just set  'engine' or 'deployment_id' 

```
#deployment_id or engine you can get from azure
AzureOpenai(deployment_name="gpt-3.5-turbo") 
```

**Comment by lingfengchencn** [comment]
#5345 same issue
try code:
```python
openai.api_type = "azure"
openai.api_key = API_KEY
openai.api_base = RESOURCE_ENDPOINT
openai.api_version = '2023-03-15-preview'
url = openai.api_base + f"/openai/deployments?api-version={openai.api_version }" 
r = requests.get(url, headers={"api-key": API_KEY})
print(r.text)
```

```
{
  "data": [
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "gpt-35-turbo",
      "owner": "organization-owner",
      "id": "gpt-35-turbo",  #deployment_id 
      "status": "succeeded",
      "created_at": "",
      "updated_at": "",
      "object": "deployment"
    },
]
}
```

**Comment by waadarsh** [comment]
> #5345 same issue try code:
> 
> ```python
> openai.api_type = "azure"
> openai.api_key = API_KEY
> openai.api_base = RESOURCE_ENDPOINT
> openai.api_version = '2023-03-15-preview'
> url = openai.api_base + f"/openai/deployments?api-version={openai.api_version }" 
> r = requests.get(url, headers={"api-key": API_KEY})
> print(r.text)
> ```
> 
> ```
> {
>   "data": [
>     {
>       "scale_settings": {
>         "scale_type": "standard"
>       },
>       "model": "gpt-35-turbo",
>       "owner": "organization-owner",
>       "id": "gpt-35-turbo",  #deployment_id 
>       "status": "succeeded",
>       "created_at": "",
>       "updated_at": "",
>       "object": "deployment"
>     },
> ]
> }
> ```

WARNING:langchain.chat_models.openai:WARNING! deployment_id is not default parameter.
                    deployment_id was transferred to model_kwargs.
                    Please confirm that deployment_id is what you intended.

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>

llm = AzureOpenAI(
  deployment_name="text-davanci",
  model_name="text-davinci-003",
  temperature=0.8
)

**Comment by lingfengchencn** [comment]
show your deployments  result,plz.

make sure your deployment_name is "text-davanci".

**Comment by waadarsh** [comment]
> show your deployments result,plz.
> 
> make sure your deployment_name is "text-davanci".

{
  "data": [
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "text-davinci-003",
      "owner": "organization-owner",
      "id": "Otext-davanci",
      "status": "succeeded",
      "created_at": "",
      "updated_at": "",
      "object": "deployment"
    },
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "gpt-35-turbo",
      "owner": "organization-owner",
      "id": "gpt-35-turbo",
      "status": "succeeded",
      "created_at": "",
      "updated_at": "",
      "object": "deployment"
    },
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "text-embedding-ada-002",
      "owner": "organization-owner",
      "id": "text-embedding-ada-002",
      "status": "succeeded",
      "created_at": "",
      "updated_at": "",
      "object": "deployment"
    }
  ],
  "object": "list"
}

**Comment by lingfengchencn** [comment]
ids are your deployment_name

"model": "text-davinci-003",
"owner": "organization-owner",
**"id": "Otext-davanci",**

"model": "gpt-35-turbo",
"owner": "organization-owner",
**"id": "gpt-35-turbo",**

"model": "text-embedding-ada-002",
"owner": "organization-owner",
**"id": "text-embedding-ada-002",**


you can try :

```python
llm = AzureOpenAI(
deployment_name="gpt-35-turbo",
model_name="gpt-35-turbo",
temperature=0.8
)
```
or 
```python
llm = AzureOpenAI(
deployment_name="Otext-davanci",
model_name="text-davinci-003",
temperature=0.8
)
```

**Comment by waadarsh** [comment]
> ids are your deployment_name
> 
> "model": "text-davinci-003", "owner": "organization-owner", **"id": "Otext-davanci",**
> 
> "model": "gpt-35-turbo", "owner": "organization-owner", **"id": "gpt-35-turbo",**
> 
> "model": "text-embedding-ada-002", "owner": "organization-owner", **"id": "text-embedding-ada-002",**
> 
> you can try :
> 
> ```python
> llm = AzureOpenAI(
> deployment_name="gpt-35-turbo",
> model_name="gpt-35-turbo",
> temperature=0.8
> )
> ```
> 
> or
> 
> ```python
> llm = AzureOpenAI(
> deployment_name="Otext-davanci",
> model_name="text-davinci-003",
> temperature=0.8
> )
> ```

Done that still getting the error. Here is the full error

---------------------------------------------------------------------------
InvalidRequestError                       Traceback (most recent call last)
[<ipython-input-45-f877209e86e7>](https://localhost:8080/#) in <cell line: 1>()
----> 1 flare.run(query)

20 frames
[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in run(self, callbacks, *args, **kwargs)
    234             if len(args) != 1:
    235                 raise ValueError("`run` supports only one positional argument.")
--> 236             return self(args[0], callbacks=callbacks)[self.output_keys[0]]
    237 
    238         if kwargs and not args:

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs, callbacks)
    138         except (KeyboardInterrupt, Exception) as e:
    139             run_manager.on_chain_error(e)
--> 140             raise e
    141         run_manager.on_chain_end(outputs)
    142         return self.prep_outputs(inputs, outputs, return_only_outputs)

[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in __call__(self, inputs, return_only_outputs, callbacks)
    132         try:
    133             outputs = (
--> 134                 self._call(inputs, run_manager=run_manager)
    135                 if new_arg_supported
    136                 else self._call(inputs)

[/usr/local/lib/python3.10/dist-packages/langchain/chains/flare/base.py](https://localhost:8080/#) in _call(self, inputs, run_manager)
    181             )
    182             _input = {"user_input": user_input, "context": "", "response": response}
--> 183             tokens, log_probs = self.response_chain.generate_tokens_and_log_probs(
    184                 _input, run_manager=_run_manager
    185             )

[/usr/local/lib/python3.10/dist-packages/langchain/chains/flare/base.py](https://localhost:8080/#) in generate_tokens_and_log_probs(self, _input, run_manager)
     37         run_manager: Optional[CallbackManagerForChainRun] = None,
     38     ) -> Tuple[Sequence[str], Sequence[float]]:
---> 39         llm_result = self.generate([_input], run_manager=run_manager)
     40         return self._extract_tokens_and_log_probs(llm_result.generations[0])
     41 

[/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py](https://localhost:8080/#) in generate(self, input_list, run_manager)
     77         """Generate LLM result from inputs."""
     78         prompts, stop = self.prep_prompts(input_list, run_manager=run_manager)
---> 79         return self.llm.generate_prompt(
     80             prompts, stop, callbacks=run_manager.get_child() if run_manager else None
     81         )

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in generate_prompt(self, prompts, stop, callbacks)
    132     ) -> LLMResult:
    133         prompt_strings = [p.to_string() for p in prompts]
--> 134         return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
    135 
    136     async def agenerate_prompt(

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in generate(self, prompts, stop, callbacks)
    189             except (KeyboardInterrupt, Exception) as e:
    190                 run_manager.on_llm_error(e)
--> 191                 raise e
    192             run_manager.on_llm_end(output)
    193             return output

[/usr/local/lib/python3.10/dist-packages/langchain/llms/base.py](https://localhost:8080/#) in generate(self, prompts, stop, callbacks)
    183             try:
    184                 output = (
--> 185                     self._generate(prompts, stop=stop, run_manager=run_manager)
    186                     if new_arg_supported
    187                     else self._generate(prompts, stop=stop)

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in _generate(self, prompts, stop, run_manager)
    322                 choices.extend(response["choices"])
    323             else:
--> 324                 response = completion_with_retry(self, prompt=_prompts, **params)
    325                 choices.extend(response["choices"])
    326             if not self.streaming:

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in completion_with_retry(llm, **kwargs)
    104         return llm.client.create(**kwargs)
    105 
--> 106     return _completion_with_retry(**kwargs)
    107 
    108 

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in wrapped_f(*args, **kw)
    287         @functools.wraps(f)
    288         def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289             return self(f, *args, **kw)
    290 
    291         def retry_with(*args: t.Any, **kwargs: t.Any) -> WrappedFn:

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    377         retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378         while True:
--> 379             do = self.iter(retry_state=retry_state)
    380             if isinstance(do, DoAttempt):
    381                 try:

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in iter(self, retry_state)
    312         is_explicit_retry = fut.failed and isinstance(fut.exception(), TryAgain)
    313         if not (is_explicit_retry or self.retry(retry_state)):
--> 314             return fut.result()
    315 
    316         if self.after is not None:

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in result(self, timeout)
    449                     raise CancelledError()
    450                 elif self._state == FINISHED:
--> 451                     return self.__get_result()
    452 
    453                 self._condition.wait(timeout)

[/usr/lib/python3.10/concurrent/futures/_base.py](https://localhost:8080/#) in __get_result(self)
    401         if self._exception:
    402             try:
--> 403                 raise self._exception
    404             finally:
    405                 # Break a reference cycle with the exception in self._exception

[/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py](https://localhost:8080/#) in __call__(self, fn, *args, **kwargs)
    380             if isinstance(do, DoAttempt):
    381                 try:
--> 382                     result = fn(*args, **kwargs)
    383                 except BaseException:  # noqa: B902
    384                     retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

[/usr/local/lib/python3.10/dist-packages/langchain/llms/openai.py](https://localhost:8080/#) in _completion_with_retry(**kwargs)
    102     @retry_decorator
    103     def _completion_with_retry(**kwargs: Any) -> Any:
--> 104         return llm.client.create(**kwargs)
    105 
    106     return _completion_with_retry(**kwargs)

[/usr/local/lib/python3.10/dist-packages/openai/api_resources/completion.py](https://localhost:8080/#) in create(cls, *args, **kwargs)
     23         while True:
     24             try:
---> 25                 return super().create(*args, **kwargs)
     26             except TryAgain as e:
     27                 if timeout is not None and time.time() > start + timeout:

[/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py](https://localhost:8080/#) in create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    147             url,
    148             params,
--> 149         ) = cls.__prepare_create_request(
    150             api_key, api_base, api_type, api_version, organization, **params
    151         )

[/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py](https://localhost:8080/#) in __prepare_create_request(cls, api_key, api_base, api_type, api_version, organization, **params)
     81         if typed_api_type in (util.ApiType.AZURE, util.ApiType.AZURE_AD):
     82             if deployment_id is None and engine is None:
---> 83                 raise error.InvalidRequestError(
     84                     "Must provide an 'engine' or 'deployment_id' parameter to create a %s"
     85                     % cls,

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.completion.Completion'>

**Comment by lingfengchencn** [comment]
Sorry, I have no idea.
can you use openai's sdk to test whether the engine / deployment_id / deployment_name(in langchain) is valid?

```python
import openai
openai.api_key = '...'
openai.api_base =  'https://.....openai.azure.com/'
openai.api_type = 'azure'
openai.api_version = '2023-03-15-preview'

response = openai.ChatCompletion.create(
        temperature=0.1,
        engine="gpt-35-turbo", # engine = deployment_name 
        messages=[
          { 
            "role": "system", "content": """
                   You are a  translate
           """},
         { 
            "role": "user", "content": """
                      something need to translate
              """},   
       ]
    )
```
if so , you can use it in langchain. if not show your codes about this plz.😂

**Comment by tomassommareqt** [comment]
The issue seems to be that the flare implementation is hardcoded to use: `response_llm = OpenAI(
            max_tokens=max_generation_len, model_kwargs={"logprobs": 1}, temperature=0
        )`

so using AzureOpenAI is not at possibility at this point.

**Comment by vidosuba** [comment]
> The issue seems to be that the flare implementation is hardcoded to use: `response_llm = OpenAI( max_tokens=max_generation_len, model_kwargs={"logprobs": 1}, temperature=0 )`
> 
> so using AzureOpenAI is not at possibility at this point.

Any update on this, please? Can someone confirm that this is the case?
I was also not able to run FLARE with AzureOpenAI.
