### ISSUE TITLE
Is it possible to return similarity score from RetrievalQA/docsearch

### ISSUE THREAD

**Issue by PavelAgurov** [langchain-ai/langchain#5416]
### Feature request

It will be very nice to have similarity score from docsearch.
Now I have list of documents even if model says "I'm sorry, but I don't have enough information to answer your question".

```
from langchain.chains import RetrievalQA

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type= "stuff", 
    retriever = docsearch.as_retriever(
        search_type="similarity",
        search_kwargs={"k":3}
    ),
    return_source_documents=True
)
```

### Motivation

Now it returns list of documents even if model says "I'm sorry, but I don't have enough information to answer your question."
And also I got list of not really relevant documents.

### Your contribution

Not sure here. For example in `chroma.py`  I can add output of similarity:

```
    def similarity_search(
        self,
        query: str,
        k: int = DEFAULT_K,
        filter: Optional[Dict[str, str]] = None,
        **kwargs: Any,
    ) -> List[Document]:
        docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
        result = []
        for doc, score in docs_and_scores:
          doc.metadata['score'] = score
          result.append(doc)
        return result
```

**BUT** it's not relevant to the output - I got similarity 0.3-0.4 for correct answers and at the same time - for "he context does not provide any information about what...". So this method is good to return score, but not good to solve all my questions.

**Comment by ChinmayBH** [comment]
The simple answer to this is different models which create embeddings have different ranges of numbers to judge the similarity. If you are using OpenAI's model for creating embeddings then it will surely have a different range for relevant and irrelevant questions than any hugging face-based model. So first check your model, check a few relevant and irrelevant questions, and on that basis check ranges. On that basis you can use score in you code.

**Comment by PavelAgurov** [comment]
> The simple answer to this is different models which create embeddings have different ranges of numbers to judge the similarity. If you are using OpenAI's model for creating embeddings then it will surely have a different range for relevant and irrelevant questions than any hugging face-based model. So first check your model, check a few relevant and irrelevant questions, and on that basis check ranges. On that basis you can use score in you code.


Sorry, I do not understand your proposal. I know what is embeddings. But I want to see score in output. See my code above.

**Comment by ChinmayBH** [comment]
Can you tell me explicitly? Do you want a similarity score? or do you want to relate the similarity score with the correct answer? you you want to perform anything on the top of Similarity score?

**Comment by PavelAgurov** [comment]
In fact I have 2 questions. Fist is main one, second is just note.

First - I want to see similarity in output. I have it solved by code above. It works for me.

```
for doc, score in docs_and_scores:
          doc.metadata['score'] = score
```

Second question - I see similarity 0.3-0.4 even when result is not relevant at all. It's just note, not directly related to the this feature. In fact I see `similarity_search_with_score`, but looks like development is in progress here.

**Comment by ChinmayBH** [comment]
similarity score is just the number which is representing how relevant your question is to the document you have provided. But it is not a rule that if the score is nearer to 0 means less relevant or towards one means more relevant. the similarity score does not always range between 0 and 1. That's what I was telling. If you test the similarity score with hugging face-based models then the scores will be in the range of 100 to 1000. the solution steps will be:
1. Finallize your embedding model
2. Check similarity_search_with_score for 10-20 relevant and irrelevant questions
3. Document similarity scores
4. Check the min-max range of both relevant and irrelevant questions 
5. Then you can judge what is the score of most relevant question and how the range of similarity scores is varying

**Comment by PavelAgurov** [comment]
ok, I will do with examples, but it will be other ticket. Let's save this one as request to add score into output.

**Comment by pedrojrv** [comment]
Hi, I would love to see if it is possible to do this.

We explicitly throw them away and I don't see that it would be possible to return them without modifying the code. See here:

https://github.com/langchain-ai/langchain/blob/2b06792c8183105edffbcb03e77326743e6a0618/libs/langchain/langchain/vectorstores/base.py#L593

Any advice?

**Comment by Knight1997** [comment]
I shared a snipped here which works great for weavaite vdb: https://github.com/langchain-ai/langchain/issues/4710#issuecomment-1710917800

**Comment by adwilson99** [comment]
Would really appreciate this feature adding if possible.    Having the similarity score available as part of RetrievalQA would help in identifying the accuracy of the responses being provided.

**Comment by PavelAgurov** [comment]
> Would really appreciate this feature adding if possible. Having the similarity score available as part of RetrievalQA would help in identifying the accuracy of the responses being provided.

Just use code that I wrote above and you will have it.

**Comment by abernardini0** [comment]
> > Would really appreciate this feature adding if possible. Having the similarity score available as part of RetrievalQA would help in identifying the accuracy of the responses being provided.
> 
> Just use code that I wrote above and you will have it.

Could you post the entire code please?

**Comment by PavelAgurov** [comment]
```
def similarity_search(
        self,
        query: str,
        k: int = DEFAULT_K,
        filter: Optional[Dict[str, str]] = None,
        **kwargs: Any,
    ) -> List[Document]:
        docs_and_scores = self.similarity_search_with_score(query, k, filter=filter)
        result = []
        for doc, score in docs_and_scores:
          doc.metadata['score'] = score
          result.append(doc)
        return result
```
