### ISSUE TITLE
`RetrievalQA` and `HuggingFacePipeline` lead to `TypeError: cannot pickle '_thread.lock' object`

### ISSUE THREAD

**Issue by jgsch** [langchain-ai/langchain#5431]
### System Info

Ubuntu 20.04.6
Python 3.8.5
Langchain 0.0.184

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python

import torch
from langchain.vectorstores import Qdrant
from langchain.embeddings import HuggingFaceInstructEmbeddings
from langchain.chains import RetrievalQA
from langchain.llms import HuggingFacePipeline
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    pipeline,
    TextIteratorStreamer,
)

# embeddings 

embeddings_model_name = "hkunlp/instructor-base"

embeddings_model = HuggingFaceInstructEmbeddings(
    model_name=embeddings_model_name,
    model_kwargs={"device": "cuda"},
)

contents = ["bla", "blabla", "blablabla"]

vector_store = Qdrant.from_texts(
    contents,
    embeddings_model,
    location=":memory:",
    collection_name="test",
)

retriever = vector_store.as_retriever()

# llm

chatbot_model_name = ""togethercomputer/RedPajama-INCITE-Chat-3B-v1"

model = AutoModelForCausalLM.from_pretrained(
    chatbot_model_name,
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map="auto",
)

tokenizer = AutoTokenizer.from_pretrained(chatbot_model_name)

streamer = TextIteratorStreamer(
    tokenizer,
    timeout=10.0,
    skip_prompt=True,
    skip_special_tokens=True,
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    streamer=streamer,
    max_length=1024,
    temperature=0,
    top_p=0.95,
    repetition_penalty=1.15,
)

pipe = HuggingFacePipeline(pipeline=pipe)

# qa

qa = RetrievalQA.from_chain_type(
    llm=pipe,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=False,
)

qa.run("What is the capital of France")
```
which lead to 

```python
TypeError: cannot pickle '_thread.lock' object
````

### Expected behavior

I should be able to get the `streamer` outputs

**Comment by jgsch** [comment]
After reinstalling the package, no more `TypeError` but the iterator get stuck. If I use the model `TheBloke/vicuna-7B-1.1-HF`, everything is working well. It seems there is something with `GPTNeoXTokenizer` tokenizer.

**Comment by cyrusgeyer** [comment]
Hi, 
I ran into the same error. 
Where you able to solve this?

**Comment by carlesonielfa** [comment]
I had the same issue, A bandaid fix that helped me is to change line 245 of text_generation.py on your transformers library.

Here is how to do it:

1. Open the file `text_generation.py` of the transformers library, which will be located in your local pip packages path, usually `site-packages/transformers/pipelines/text_generation.py`

2. Go to line 245 and change `deepcopy` to `copy`
` generate_kwargs = copy.deepcopy(generate_kwargs) ` -> `generate_kwargs = copy.copy(generate_kwargs)`

As a warning, I do not know if this change has any downsides. But until a permanent fix is found, this seems to be good enough :)

**Comment by parkitny** [comment]
> ```python
> run
> ```

This is about the only solution that's worked so far. @hwchase17 do you know whether there's plans to add this functionality in the near future? thanks for the help

**Comment by parkitny** [comment]
> 



> [#5431 (comment)](https://github.com/langchain-ai/langchain/issues/5431#issuecomment-1629501709)
> 
> This is about the only solution that's worked so far. @hwchase17 do you know whether there's plans to add this functionality in the near future? thanks for the help

Actually it seems to be working without this change as of version 4.31.0

**Comment by hendryman** [comment]
Same error here. Is there a fix that doesn't include patching libraries?

**Comment by CatsNipYummy** [comment]
Facing a similar issue myself
