### ISSUE TITLE
Issue: Get the verbose messages from chain

### ISSUE THREAD

**Issue by KanaSukita** [langchain-ai/langchain#5448]
### Issue you'd like to raise.

We can get the intermediate messages printed when the verbose is set to True in the chains. But is there a way we can get the intermediate messages from the chain as a return value?

### Suggestion:

Take the code below as example.

```
from langchain import OpenAI, ConversationChain
from langchain.llms import OpenAI
llm = OpenAI(engine="text-davinci-003", temperature=0.9)
conversation = ConversationChain(llm=llm, verbose=True)
conversation.predict(input="How are you?")
conversation.predict(input="I am Ricardo Kaka, what is your name?")
conversation.predict(input="What is the first thing I said to you?")
```
We get the messages below printed in the shell. But I am wondering if there is a way I can get the messages as an return value, something like conversation.verbose_message, or conversation.get_verbose_message()?

**Comment by fire17** [comment]
Hi there ! Can someone please address this?
I also want to be able use the verbose debug output and feed it to my pipeline,
for example:

```python
def logger_hook(verbose_output, *args, **kwargs):
    print(" ### Handling Verbose ### \n", verbose_output )
    ...

conversation = ConversationChain(llm=llm, verbose=True, verbose_hook=logger_hook)
# The verbose output should be sent to hook function
```
this simple hook should be simple to implement, please add this feature to langchain!🙏

**Comment by fire17** [comment]
I took the time to provide a solution, checkout PR #10195 

Adding a Verbose Hook, so verbose output wont only be printed, but also handled if chosen to

Usage:
```python
def handle_verbose(verbose_output, *args, **kwargs):
    print("$$$$$$$ HANDLEING VERBOSE OUTPUT $$$$$$")
    print(verbose_output) # Handle verbose here
    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$", args, kwargs)

worker = LLMChain(prompt=prompt,llm=llm, verbose=verbose, verbose_hook=handle_verbose)
# Verbose messages will be sent to hook
```
Usefull when you want to include verbose output, for example in a custom debugger gui, logger, or for any other usage.
( I've only changed the on_text event, which includes the final (green) prompt before it is sent to the llm, if you like it you can extend to use in other places. )

Hope you find it useful as I do
Have a good one and all the best!
