### ISSUE TITLE
Why raise an error in conversation retrieval chain if the chat history is a string?

### ISSUE THREAD

**Issue by ogabrielluiz** [langchain-ai/langchain#5452]
https://github.com/hwchase17/langchain/blob/64b4165c8d9b8374295d4629ef57d4d58e9af7c8/langchain/chains/conversational_retrieval/base.py#L34

It seems the `_get_chat_history` is building the chat_history string but if the history is already a string then it should.
The check might even be in the BaseConversationalRetrievalChain `_call` methods.

What would be the correct way of using this if the chat_history is already a string?

**Comment by YLFxGen** [comment]
Append chat history string to a List and use it like this:
`get_chat_history=lambda chat_history: "\n".join(chat_history)`

**Comment by supreetkt** [comment]
I was able to do:
```
ConversationalRetrievalChain.from_llm(
            llm=llm,
            retriever=knowledge_base.retriever,
            chain_type="stuff",
            verbose=verbose,
            memory=chat_memory,
            return_source_documents=True,
            combine_docs_chain_kwargs={"prompt": system_prompt},
            get_chat_history=lambda chat_history: chat_history
        )
```
Used the answer provided above - note that using `"\n".join(chat_history)` added the chat history with one character in a newline.
