### ISSUE TITLE
Cannot build a file agent

### ISSUE THREAD

**Issue by Undertone0809** [langchain-ai/langchain#5454]
### Issue you'd like to raise.

As we know, we can build a agent with tool by following way:

```python

llm = OpenAI(temperature=0)

tools = load_tools(["serpapi", "llm-math"], llm=llm)
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

```

We can also use `FileManagementToolKit` to manage the file system. But I want to know, how to build a agent of file management of file system. `Langchain` still not provide agent for file management. So I want to know how to build agent with file system. I tried to use `load_tools` as follows, but failed. `FileManagementToolKit` can not be imported to `load_tools()`  because `load_tools` does not provider file-related options.

```python
import os
from langchain.agents.agent_toolkits import FileManagementToolkit
from tempfile import TemporaryDirectory
from langchain.agents import load_tools

working_directory = TemporaryDirectory(dir=os.getcwd())
toolkit = FileManagementToolkit(root_dir=str(working_directory.name))
tool_names = list(map(lambda item: item.name,toolkit.get_tools()))
tools = load_tools(tool_names)
```

```
ValueError                                Traceback (most recent call last)
Cell In[27], line 3
      1 from langchain.agents import load_tools
      2 tool_names = list(map(lambda item: item.name,toolkit.get_tools()))
----> 3 tools = load_tools(tool_names)

File E:\Programming\anaconda\lib\site-packages\langchain\agents\load_tools.py:341, in load_tools(tool_names, llm, callback_manager, **kwargs)
    339         tools.append(tool)
    340     else:
--> 341         raise ValueError(f"Got unknown tool {name}")
    342 return tools

ValueError: Got unknown tool copy_file
```

the tools of `FileManagementToolkit`:

```python
list(map(lambda item: item.name,toolkit.get_tools()))
```

```
['copy_file',
 'file_delete',
 'file_search',
 'move_file',
 'read_file',
 'write_file',
 'list_directory']
```

### Suggestion:

Maybe we can build a like `create_file_agent()` like `create_sql_agent()`. As we all know, we can build sql agent as follows:

```python
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI

def create_mysql_kit():
    db = SQLDatabase.from_uri("sqlite:///../../../../notebooks/Chinook.db")
    llm = OpenAI(temperature=0.3)

    toolkit = SQLDatabaseToolkit(db=db, llm=llm)
    agent_executor = create_sql_agent(
        llm=OpenAI(temperature=0),
        toolkit=toolkit,
        verbose=True
    )
    # agent_executor.run("Who are the users of sysuser in this system? Tell me the username of all users")
    agent_executor.run("How many people are in this system?")


if __name__ == '__main__':
    create_mysql_kit()
```

I think we can build the `file agent` in the same way.

### More

- There may be some way to achieve the same functionality as the file agent, but I don't know. If so, please tell to how to use it.

- Can we provide a method to make an agent use all tools, including tools in toolkit and tools of `load_tools()`

**Comment by engperini** [comment]
Hi, it would be great to solve this: 
'ValueError: ZeroShotAgent does not support multi-input tool write_file'
It works when I use STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION agent.

**Comment by engperini** [comment]
> @baskaryan Could you please help @engperini with the issue they are facing? They are experiencing a `ValueError` when using the `STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION` agent and would like to solve it. Thank you!

the problem is when use ZERO_SHOT_REACT_DESCRIPTION agent
