### ISSUE TITLE
conversationalRetrievalChain - how to set the template

### ISSUE THREAD

**Issue by DennisPeeters** [langchain-ai/langchain#5462]
### Issue you'd like to raise.

I am using conversationalRetrievalChain. I cannot seem to change the system template. Any suggestion how to do this? 

`retriever = vectorstore.as_retriever(search_kwargs={"k": source_amount},  qa_template=QA_PROMPT, question_generator_template=CONDENSE_PROMPT)`

`qa = ConversationalRetrievalChain.from_llm(llm=model, retriever=retriever, return_source_documents=True)`

When printing QA:
[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context'], output_parser=None, partial_variables={}, template="Use the following pieces of context to answer the users question. \nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\n{context}", template_format='f-string', validate_template=True), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question'],

Whatever I try, I seem to be unable to change the template "Use the following pieces of context to answer..."

**Comment by shelltea** [comment]
```
QA_PROMPT = PromptTemplate()
combine_docs_chain_kwargs={'prompt': QA_PROMPT}
```

**Comment by DennisPeeters** [comment]
Indeed, just figured it out 5 minutes ago
`        system_template = """End every answer with "Ahoi Matey I love you". Use the following pieces of context to answer the users question. 
        If you cannot find the answer from the pieces of context, just say that you don't know, don't try to make up an answer.
        ----------------
        {context}"""

        # Create the chat prompt templates
        messages = [
        SystemMessagePromptTemplate.from_template(system_template),
        HumanMessagePromptTemplate.from_template("{question}")
        ]
        qa_prompt = ChatPromptTemplate.from_messages(messages)`

and then

`
qa = ConversationalRetrievalChain.from_llm(llm=model, retriever=retriever, return_source_documents=True,combine_docs_chain_kwargs={"prompt": qa_prompt})
`

**Comment by zigax1** [comment]
> Author

I am facing similar error. Can you share a little bit more of a code, please?

What is st.write here?

**Comment by SajalRandhar** [comment]
I am not able to use memory in the above piece of code. Can someone suggest any ideas?

**Comment by Srishti2002-jai** [comment]
@DennisPeeters  can you tell me what will go inside the context? please as I  got suck there for 2 days If can response early I would be greatful

**Comment by Srishti2002-jai** [comment]
@DennisPeeters Can you what should be the syntax to get the prompt of conversational retrieval chain

**Comment by DennisPeeters** [comment]
Hi sorry for not replying, been very busy and as I said above, I am not a developer.

So lets try @Srishti2002-jai - do you get any error? Can you share some of your code? What are you trying to do?

**Comment by DennisPeeters** [comment]
The context is loaded automatically from qa I think. The st.write is because i am using streamlit

**Comment by yudhoom** [comment]
You can custom the prompt, this is the reference
https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval

**Comment by TinaHage** [comment]
general_user_template = "Question:```{question}```"
messages = [
            SystemMessagePromptTemplate.from_template(prompt),
            HumanMessagePromptTemplate.from_template(general_user_template)
]
qa_prompt = ChatPromptTemplate.from_messages( messages )
qa = ConversationalRetrievalChain.from_llm(
    model,
    vectordb.as_retriever(),
    memory=memory,
    chain_type="stuff",
    return_source_documents = True,
    combine_docs_chain_kwargs={'prompt': qa_prompt}
)
PLEASE CAN SOMEONE HELP ME START THE CONVERSATION? I'm getting this error when using qa.run(question) : run` not supported when there is not exactly one output key. Got ['answer', 'source_documents'].
