### ISSUE TITLE
Ability to access provider specific information from with Chains or Agents

### ISSUE THREAD

**Issue by maruthiprithivi** [langchain-ai/langchain#547]
Hi LangChain Team!! Thank you for this awesome library. Hands down one of the best projects I have seen so far. 

It would be helpful if there is a way to access provider-specific information when they're loaded as tools as part of an Agent or a Chain. For Example:

LLMs
After running this:
`llm_result = llm.generate(["Tell me a joke", "Tell me a poem"]*15)`
One can run this:
`llm_result.llm_output`

But if the above LLM was added as tools like the following, is there a way to access the `some_result.llm_output`?
`tools = load_tools(["serpapi", "llm-math"], llm=llm)`

**Comment by hwchase17** [comment]
hmm interesting idea - can i ask what the use case is? is it to just see it? or to use it in some programmatic way downstream?

**Comment by maruthiprithivi** [comment]
Hi @hwchase17,

It's to use it programmatically downstream. Keeping the above-mentioned example, by having access to the `total_tokens=x`, we can keep track of the usage of requests by a user or application.

Another use case will be the following issue when the search wrapper is extended to provide the snippet and source URL. Building a personal assistant and being able to do fact checks by referencing the original snippets and information sources will become very powerful:
https://github.com/hwchase17/langchain/issues/522

I'm exploring a couple of use cases to build a commercial app, so some of the above-mentioned will tie back to the services and how they will set the initial depth of their capability. I just started going through the docs, so I will also be looking at building custom tools to be used as part of the agents, and being able to access the custom tool provider's info in the Chain/Agent will become very powerful.

**Comment by hwchase17** [comment]
got it. ive got some initial ideas that may be easier to explain offline. are you on the discord by any chance?
