### ISSUE TITLE
the text splitter adds metadata by itself

### ISSUE THREAD

**Issue by etherious1804** [langchain-ai/langchain#5489]
### Issue you'd like to raise.

I cant find any way to add custom metadata with the character splitter, it adds source as metadata but I cant seem to change it or define what kind of metadata I want

**Comment by YLFxGen** [comment]
Can you add like this:
```
content_str = "YOUR TEXT"  # Your content to be ingested
docs = []  # List holding all the documents
# Define character splitter
splitter = RecursiveCharacterTextSplitter(chunk_size=1024, chunk_overlap=32, length_function=len)
# Split text into chunks
for chunk in splitter.split_text(content_str):
  # Generate documents
  docs.append(Document(page_content=chunk, metadata={"source": "source", "path":"path", "others":"others"}))
```

**Comment by WaleedAlfaris** [comment]
I found a solution to this. There may be a more elegant way to accomplish this task, but the following worked for me.

```
text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(text_documents)
for idx, text in enumerate(texts):
    texts[idx].metadata['key'] = value
```

here I am adding to the metadata of the doc a new key and setting the value. I used this to sucessfully add a country key to the metadata which indicates what country the data is related to.
