### ISSUE TITLE
Error while importing Langchain 

### ISSUE THREAD

**Issue by armaandhar** [langchain-ai/langchain#5490]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 import langchain

File ~\anaconda3\lib\site-packages\langchain\__init__.py:6, in <module>
      3 from importlib import metadata
      4 from typing import Optional
----> 6 from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
      7 from langchain.cache import BaseCache
      8 from langchain.chains import (
      9     ConversationChain,
     10     LLMBashChain,
   (...)
     18     VectorDBQAWithSourcesChain,
     19 )

File ~\anaconda3\lib\site-packages\langchain\agents\__init__.py:2, in <module>
      1 """Interface for agents."""
----> 2 from langchain.agents.agent import (
      3     Agent,
      4     AgentExecutor,
      5     AgentOutputParser,
      6     BaseMultiActionAgent,
      7     BaseSingleActionAgent,
      8     LLMSingleActionAgent,
      9 )
     10 from langchain.agents.agent_toolkits import (
     11     create_csv_agent,
     12     create_json_agent,
   (...)
     21     create_vectorstore_router_agent,
     22 )
     23 from langchain.agents.agent_types import AgentType

File ~\anaconda3\lib\site-packages\langchain\agents\agent.py:13, in <module>
     10 from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple, Union
     12 import yaml
---> 13 from pydantic import BaseModel, root_validator
     15 from langchain.agents.agent_types import AgentType
     16 from langchain.agents.tools import InvalidTool

File ~\anaconda3\lib\site-packages\pydantic\__init__.py:2, in init pydantic.__init__()

File ~\anaconda3\lib\site-packages\pydantic\dataclasses.py:48, in init pydantic.dataclasses()

File ~\anaconda3\lib\site-packages\pydantic\main.py:120, in init pydantic.main()

TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

**Comment by djpecot** [comment]
which versions of Python and LangChain are you using?

**Comment by scm1210** [comment]
I also got this error. I'm using python 3.9 and `langchain` 0.0.189
