### ISSUE TITLE
Tracking of time to generate text

### ISSUE THREAD

**Issue by dheerajiiitv** [langchain-ai/langchain#5498]
### Feature request

Hey Team,
I would like to propose a new feature that will enhance the visibility of the LLM's response time. In addition to providing information about token usage and cost, I suggest incorporating the time taken to generate the text. This additional metric will offer valuable insights into the efficiency and performance of the system.

### Motivation

By including the response time, we can provide a comprehensive picture of the different LLM's API's performance, ensuring that we have a more accurate measure of its capabilities. This information will be particularly useful for evaluating and optimizing different LLMs, as it will shed light on the latency of the system.

### Your contribution

We can easily implement this by adding additional variables in callbacks of LLM's. I would like to implement this feature.

Here the example code:

```
class BaseCallbackHandler:
    """Base callback handler that can be used to handle callbacks from langchain."""
    time_take_by_llm_to_generate_text: float = 0
    start_time: float = 0
    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> Any:
        """Run when LLM starts running."""
        self.start_time = datetime.now()
   

    def on_llm_end(self, response: LLMResult, **kwargs: Any) -> Any:
        """Run when LLM ends running."""
        self.end_time = datetime.now()
        self.time_take_by_llm_to_generate_text += end_time - start_time
```

**Comment by Rasmnev** [comment]
I am trying to use something like this to track the execution time of a chain and it's individual components and I'm trying to use tags to identify the components. This is what it looks like
```
class TimerCallbackHandler(BaseCallbackHandler):
    time_table = {}

    def _start_timer(self, tags):
        for tag in tags:
            self.time_table[tag] = time.time()

    def _end_timer(self, tags):
        for tag in tags:
            self.time_table[tag] = time.time() - self.time_table[tag]
    def on_chain_start(
        self,
        serialized: Dict[str, Any],
        inputs: Dict[str, Any],
        *,
        run_id,
        parent_run_id= None,
        tags= None,
        **kwargs: Any,
    ) -> Any:
        if tags:
            self._start_timer(tags)

    def on_chain_end(
            self,
            outputs: Dict[str, Any],
            *,
            run_id,
            parent_run_id= None,
            tags= None,
            **kwargs: Any,
    ) -> Any:
        if tags:
            self._end_timer(tags)
```

my problem is the Handler does not have access to the tags. Those are in the Callback Manager. Is there a default way to access the manager/component tags or do I need to patch the Manager to pass the tags to each callback handler?

**Comment by dheerajiiitv** [comment]
@Rasmnev I'll suggest you to pass tags while initializing the callback handler 
Here:
`
class TimerCallbackHandler(BaseCallbackHandler):
        def __init__(self, tags):
                 self.time_table = {} # Make sure to initialise your variables here otherwise your class variable will get shared across your different callback handler objects.
                 self.tags = tags
`

**Comment by Rasmnev** [comment]
My idea was to pass it to the chain and then the chain would pass the same object to all components. The end result would be to have the time_table like this:
```
time_table = {
"component1": time,
"component2": time,
"component3":time,
...
}

**Comment by DrewGalbraith** [comment]
Did this get solved, or did the bot just close it down? I would also like this functionality!
