### ISSUE TITLE
Chroma: Constructor takes wrong embedding function (document vs query)

### ISSUE THREAD

**Issue by jrinder42** [langchain-ai/langchain#5519]
### System Info

Most recent version of Langchain
Python: 3.10.8
MacOS 13.4 - M1

### Who can help?

@hwchase17 
@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The Chroma constructor in the vectorstore section uses the document function when it should be the query function for embeddings. As a result, if the documents parameter is blank when using Chroma, Langchain will error out with a ValidationError. Please change line 95 to be embed_query instead of embed_documents [here](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py) in order for this to work / be consistent with the rest of the vectorstore wrappers

### Expected behavior

Use the query function instead of the documents function for use with embeddings in Chroma

**Comment by hanifaudah** [comment]
Could you provide sample code to reproduce this?

**Comment by jrinder42** [comment]
You can follow [this](https://www.pinecone.io/learn/langchain-retrieval-augmentation/) tutorial and just swap out Pinecone for Chroma (doesn't matter if it persists to disk or not). When upserting vectors, if you leave out the documents parameter, using Chroma from Langchain as a vectorstore and running the `similarity_seach` function will throw a ValidationError.

I am using OpenAI embeddings along with passing the `client` parameter. 
--> client = Chroma(name='some name', embedding_function=embeddings.embed_query) 
The above is consistent with what is in the docstrings for the `Chroma` class and similar to other vector dbs like Pinecone. To be fair, a lot of the docstrings through this codebase (especially the vectorstore folder) seem to be out of date.

**Comment by adolkhan** [comment]
@jrinder42 hope you're doing well! Have you tried deeplake? It is very convenient, easy-to-use tool. It shouldn't have such problem that you mentioned. To get started, you can take a look at: https://github.com/hwchase17/langchain/blob/master/docs/extras/use_cases/code/twitter-the-algorithm-analysis-deeplake.ipynb or https://github.com/hwchase17/langchain/blob/master/docs/extras/use_cases/code/code-analysis-deeplake.ipynb
