### ISSUE TITLE
Issue: previous message condensing time on `ConversationalRetrievalChain`

### ISSUE THREAD

**Issue by Rijoanul-Shanto** [langchain-ai/langchain#5542]
### Issue you'd like to raise.

I got a scenario where I'm using the `ConversationalRetrievalChain` with chat history. The problem is, it was streaming the condensed output of the question. Not the actual answer. So I separated the models, one for condensing the question and one for answering with streaming. But as I suspected, the condensing chain is eating up a time to generate the condensed output of the question, and the actual streaming of the answer is waiting for the condensed question generator. 

some of my implementations:

```python
callback = AsyncIteratorCallbackHandler()

q_generator_llm = ChatOpenAI(
    openai_api_key=settings.openai_api_key,
)

streaming_llm = ChatOpenAI(
    openai_api_key=settings.openai_api_key,
    streaming=True,
    callbacks=[callback],
)

question_generator = LLMChain(llm=q_generator_llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain = load_qa_chain(llm=streaming_llm, chain_type="stuff", prompt=prompt)

qa_chain = ConversationalRetrievalChain(
    retriever=collection_store.as_retriever(search_kwargs={"k": 3}),
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    return_source_documents=True,
)

history = []

task = asyncio.create_task(
    qa_chain.acall({
        "question": q,
        "chat_history": history
    }),
)
```
___

**Comment by PNBnag007** [comment]
Hi @Rijoanul-Shanto....I am also facing the same issue. Did you find any workaround?

**Comment by Rijoanul-Shanto** [comment]
> Hi @Rijoanul-Shanto....I am also facing the same issue. Did you find any workaround?

Hey @PNBnag007! I didn't have a chance to continue work on this as I got involved in some other tasks :) But here is a discussion with @ninely that might help you a bit: https://gist.github.com/ninely/88485b2e265d852d3feb8bd115065b1a?permalink_comment_id=4586216#gistcomment-4586216

It seems this chain work in that way so we might need to try some other chain or another way.
