### ISSUE TITLE
Guanaco 65B model support

### ISSUE THREAD

**Issue by Bec-k** [langchain-ai/langchain#5548]
### Feature request

Please add support for the model Guanaco 65B, which is trained via qLoRA method. To be able to swap OpenAI model to Guanaco and perform same operations over it.

### Motivation

The best performance and free model out there up to date 01.06.2023.

### Your contribution

-

**Comment by dev2049** [comment]
seems to be on huggingface (https://huggingface.co/TheBloke/guanaco-65B-HF), could you not access using HuggingFacePipeline?
