### ISSUE TITLE
Query With Multiple Collections

### ISSUE THREAD

**Issue by ragvendra3898** [langchain-ai/langchain#5555]
Hi,
I am  using langchain to create collections in my local directory after that I am persisting it using below code 

from langchain.vectorstores import Chroma                                   
from langchain.embeddings import OpenAIEmbeddings                               
from langchain.text_splitter import RecursiveCharacterTextSplitter , TokenTextSplitter            
from langchain.llms import OpenAI                                             
from langchain.chat_models import ChatOpenAI                             
from langchain.chains import VectorDBQA, RetrievalQA                                        
from langchain.document_loaders import TextLoader, UnstructuredFileLoader, DirectoryLoader

loader = DirectoryLoader("D:/files/data")  
docs = loader.load()                            
text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)                                 
vectordb = Chroma.from_documents(texts, embedding=embeddings, persist_directory = persist_directory, collection_name=my_collection)    
vectordb.persist()                           
vectordb = None

I am using above code for creating different different collection in the same persist_directory by just changing the collection name and the data files path, now lets say I have 5 collection in my persist directory
my_collection1
my_collection2
my_collection3
my_collection4
my_collection5

Now If I want to perform querying to my data then I have to call my persist_directory with collection_name
vectordb = Chroma(persist_directory=persist_directory, embedding_function=embeddings, collection_name=my_collection3)
qa = RetrievalQA.from_chain_type(llm=ChatOpenAI(openai_api_key=openai_api_key), chain_type="stuff", retriever=vectordb.as_retriever(search_type="mmr"), return_source_documents=True)
qa("query")

so the issue is if I am using above code then I can perform only querying for my_collection3 but I want to perform querying to all my five collections, so can anyone please suggest, how can I do this or if it is not possible, I will be thankful to you.

I had tried without collection name for ex-
vectordb = Chroma(persist_directory=persist_directory, embedding_function=embedding)
qa = RetrievalQA.from_chain_type(llm=ChatOpenAI(openai_api_key=openai_api_key), chain_type="stuff", retriever=vectordb.as_retriever(search_type="mmr"), return_source_documents=True)
qa("query")

but in this case I am getting 
NoIndexException: Index not found, please create an instance before querying

**Comment by GDrupal** [comment]
Hi! What I do is to use one chroma object per collection. Not only you can use diff collection but also keep diff collection using diff embeddings.
```Python
client_settings = chromadb.config.Settings(
    chroma_db_impl="duckdb+parquet",
    persist_directory=DB_DIR,
    anonymized_telemetry=False,
)
vxsumall = Chroma(
    collection_name="project_store_all",
    persist_directory=DB_DIR,
    client_settings=client_settings,
    embedding_function=emall,
)
vxsummulti = Chroma(
    collection_name="project_store_multi",
    persist_directory=DB_DIR,
    client_settings=client_settings,
    embedding_function=emmulti,
)
vnosumall = Chroma(
    collection_name="project_store_nosum",
    persist_directory=DB_DIR,
    client_settings=client_settings,
    embedding_function=emall,
)

#Then you can get diff retrievals per object
ret0 = vnosumall.as_retriever(
    search_type="similarity", search_kwargs={"k": 5, "include_metadata": True}
)
ret1 = vxsumall.as_retriever(
    search_type="similarity", search_kwargs={"k": 10, "include_metadata": True}
)
ret2 = vxsummulti.as_retriever(
    search_type="mmr", search_kwargs={"k": 10, "include_metadata": True}
)
```

**Comment by ragvendra3898** [comment]
Great!, Thank You so much GDrupal.

**Comment by Fulladorn** [comment]
> Hi! What I do is to use one chroma object per collection. Not only you can use diff collection but also keep diff collection using diff embeddings.
> 
> ```python
> client_settings = chromadb.config.Settings(
>     chroma_db_impl="duckdb+parquet",
>     persist_directory=DB_DIR,
>     anonymized_telemetry=False,
> )
> vxsumall = Chroma(
>     collection_name="project_store_all",
>     persist_directory=DB_DIR,
>     client_settings=client_settings,
>     embedding_function=emall,
> )
> vxsummulti = Chroma(
>     collection_name="project_store_multi",
>     persist_directory=DB_DIR,
>     client_settings=client_settings,
>     embedding_function=emmulti,
> )
> vnosumall = Chroma(
>     collection_name="project_store_nosum",
>     persist_directory=DB_DIR,
>     client_settings=client_settings,
>     embedding_function=emall,
> )
> 
> #Then you can get diff retrievals per object
> ret0 = vnosumall.as_retriever(
>     search_type="similarity", search_kwargs={"k": 5, "include_metadata": True}
> )
> ret1 = vxsumall.as_retriever(
>     search_type="similarity", search_kwargs={"k": 10, "include_metadata": True}
> )
> ret2 = vxsummulti.as_retriever(
>     search_type="mmr", search_kwargs={"k": 10, "include_metadata": True}
> )
> ```

Is there a better way of doing this in being able to create multiple collections under a single ChromDB instance?

**Comment by GDrupal** [comment]
> > Hi! What I do is to use one chroma object per collection. Not only you can use diff collection but also keep diff collection using diff embeddings.
> > ```python
> > client_settings = chromadb.config.Settings(
> >     chroma_db_impl="duckdb+parquet",
> >     persist_directory=DB_DIR,
> >     anonymized_telemetry=False,
> > )
> > vxsumall = Chroma(
> >     collection_name="project_store_all",
> >     persist_directory=DB_DIR,
> >     client_settings=client_settings,
> >     embedding_function=emall,
> > )
> > vxsummulti = Chroma(
> >     collection_name="project_store_multi",
> >     persist_directory=DB_DIR,
> >     client_settings=client_settings,
> >     embedding_function=emmulti,
> > )
> > vnosumall = Chroma(
> >     collection_name="project_store_nosum",
> >     persist_directory=DB_DIR,
> >     client_settings=client_settings,
> >     embedding_function=emall,
> > )
> > 
> > #Then you can get diff retrievals per object
> > ret0 = vnosumall.as_retriever(
> >     search_type="similarity", search_kwargs={"k": 5, "include_metadata": True}
> > )
> > ret1 = vxsumall.as_retriever(
> >     search_type="similarity", search_kwargs={"k": 10, "include_metadata": True}
> > )
> > ret2 = vxsummulti.as_retriever(
> >     search_type="mmr", search_kwargs={"k": 10, "include_metadata": True}
> > )
> > ```
> 
> Is there a better way of doing this in being able to create multiple collections under a single ChromaDB instance?

It depends on what do want to achieve. If you have a relatively small source of information but noisy, creating multiple embedding and running diff search types could help you extract the most while cleaning noise.
If you have a big source of information from several places you can use another methods. The merger retriever just allows you to merge all the results together to do something with that later.

**Comment by AIApprentice101** [comment]
Hi @GMartin-dev thank you for the suggestion.

In my application, I have a very large number of collections. Do I ever need to worry about the memory usage, if all of them are specified? thank you.

For example
```
n = 2 ** 20
for i in range(n):
    vdb[str(i)] = Chroma(
        collection_name=str(i),
        persist_directory=DB_DIR,
        client_settings=client_settings,
        embedding_function=emall,
    )
    ret[str(i)] = vdb[str(i)].as_retriever(
        search_type="similarity", search_kwargs={"k": 5, "include_metadata": True}
    )
```

**Comment by GMartin-dev** [comment]
@AIApprentice101 
If you are running Chroma locally, that's for sure. But it will depend more on the size of collections no so much in how many. If you have a really big collection you are probably better with other embeddings dbs or using Chroma as a service.

**Comment by namp** [comment]
So if say, for example, you want to parse a directory of documents and define multiple collections because you want different embeddings, do you need to separately add the documents to each collection with its .add_documents method? 

But if so, each collection will have its own doc_id for the same retrieved document, so how will you be able to combine them together?

**Comment by GMartin-dev** [comment]
> So if say, for example, you want to parse a directory of documents and define multiple collections because you want different embeddings, do you need to separately add the documents to each collection with its .add_documents method?
> 
> But if so, each collection will have its own doc_id for the same retrieved document, so how will you be able to combine them together?

You could add an unique id per document / document section into metadata and use that metadata field for deduplication

**Comment by gotkd21** [comment]
I'm actually having same issue.  In my context, I'm building an app supporting multiple people that may want to store data with totally separate retrieval for each person.  Chroma handles the storing of multiple collections just fine by passing collection_name.

`vectordb = Chroma.from_documents(texts, embeddings,
            client=self.client, 
            collection_name=collection_id
        )`

The problem I'm having is the retrieval doesn't seem to want to switch collections based on collection name.  It retrieves only from the the original collection that initialized it.  I may be doing something wrong, or have not found a way to pass the collection_name as a parameter to the retriever:

`RetrievalQA.from_chain_type(llm=self.llm, chain_type="stuff", retriever=self.vectordb.as_retriever())`

there may be a way, but I've not found doc yet on how to do it.

**Comment by GMartin-dev** [comment]
> I'm actually having same issue. In my context, I'm building an app supporting multiple people that may want to store data with totally separate retrieval for each person. Chroma handles the storing of multiple collections just fine by passing collection_name.
> 
> `vectordb = Chroma.from_documents(texts, embeddings, client=self.client, collection_name=collection_id )`
> 
> The problem I'm having is the retrieval doesn't seem to want to switch collections based on collection name. It retrieves only from the the original collection that initialized it. I may be doing something wrong, or have not found a way to pass the collection_name as a parameter to the retriever:
> 
> `RetrievalQA.from_chain_type(llm=self.llm, chain_type="stuff", retriever=self.vectordb.as_retriever())`
> 
> there may be a way, but I've not found doc yet on how to do it.

Precisely you need to instantiate a retriever per user using an unique collection, the collection key could have user id or unique hash. And you add ; remove documents per collection in a separate step.
Here an example in pseudocode:

```Python
 collection = user_id + "collection-name"
        vector_db = Chroma(
            collection_name=collection,
            persist_directory=path + collection,
            embedding_function=embeddings_model,
        )
        retriever = vector_db.as_retriever(
            search_type="mmr", search_kwargs={"k": 10, "include_metadata": True}
        )
        
        added = vector_db.add_documents(
                documents=docs,
                ids=ids,
         )
        vector_db.persist()
 ```
