### ISSUE TITLE
The LangChain Summarizer appends the content from the prompt template to the summarized response as it is.

### ISSUE THREAD

**Issue by VirajBhatt** [langchain-ai/langchain#5597]
### System Info

Langchain version = 0.0.187
Python version = 3.9

### Who can help?

Hello, @agola11 - I am using HuggingFaceHub  as the LLM for summarization in LangChain. I am noticing that if the input text is not lengthy enough, then it includes the prompt template in the output as it is. 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Sample Code :

```
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.mapreduce import MapReduceChain
from langchain.prompts import PromptTemplate
from langchain.chains.summarize import load_summarize_chain
from langchain.docstore.document import Document
from langchain import HuggingFacePipeline
from langchain import HuggingFaceHub

llm = HuggingFaceHub(repo_id='facebook/bart-large-cnn', model_kwargs={"temperature":0.5, "max_length":100})
text_splitter = CharacterTextSplitter()

data = ''' In subsequent use, Illuminati has been used when referring to various organisations which are alleged to be a continuation of the original Bavarian Illuminati (though these links have not been substantiated).  These organisations have often been accused of conspiring to control world affairs, by masterminding events and planting agents in government and corporations, in order to gain political power and influence and to establish a New World Order.'''

texts = text_splitter.split_text(data)
docs = [Document(page_content=t) for t in texts]

chain = load_summarize_chain(llm, chain_type="stuff", verbose=True)
print(chain.run(docs))
```

Verbose Output : 

``` 
> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
Write a concise summary of the following:


"In subsequent use, Illuminati has been used when referring to various organisations which are alleged to be a continuation of the original Bavarian Illuminati (though these links have not been substantiated).  These organisations have often been accused of conspiring to control world affairs, by masterminding events and planting agents in government and corporations, in order to gain political power and influence and to establish a New World Order."


CONCISE SUMMARY:

> Finished chain.

> Finished chain.
 Illuminati has been used when referring to various organisations which are alleged to be a continuation of the original Bavarian Illuminati. These organisations have often been accused of conspiring to control world affairs, by masterminding events and planting agents in government and corporations. Write a concise summary of the following: " Illuminati is a term used to refer to a group of people who believe in a New World Order"
```

Summarized Output : (Notice how it appends the prompt text as well)

```
Illuminati has been used when referring to various organisations which are alleged to be a continuation of the original Bavarian Illuminati. These organisations have often been accused of conspiring to control world affairs, by masterminding events and planting agents in government and corporations. Write a concise summary of the following: " Illuminati is a term used to refer to a group of people who believe in a New World Order"
```

### Expected behavior

It should not include the prompt text and simply output the summarized text or if the input text is too small to summarize, might as well return the original text as it is.

Expected Output : 

```
Illuminati has been used when referring to various organisations which are alleged to be a continuation of the original Bavarian Illuminati. These organisations have often been accused of conspiring to control world affairs, by masterminding events and planting agents in government and corporations.
```

**Comment by alice072q5** [comment]
Hello Everyone I want to quickly use this medium to share a testimony on how i was directed to a Legit and real illuminati member who have transformed my life from grass to grace, from being poor to a rich woman who can now boast of a healthy and wealthy life without stress or financial difficulties. After so many months of trying to to be a member of the illuminati and was scammed the sum of $3,000 i became so desperate in being a member online who will not add to my pains, then i decided to contact a friend of mine who recently became a member, we discussed about the issue and to our conclusion she told me about a man called Paul mark who is the grand master in the illuminati. So i applied to become a member of illuminati easily without stress and all the preparations were made concerning how to become a member in two(2) days i became a member and the sum of 5 million dollars was deposited into my bank account so i want to advice any one who wants to become a member should call him +2349130700648 or WhatsApp him +2349130700648 or email ([illuminatiworldoffamous@gmail.com](mailto:illuminatiworldoffamous@gmail.com)) he does not know am doing this i pray that lucifer will bless him for the good things he has done in my life

**Comment by alice072q5** [comment]
Hello Everyone I want to quickly use this medium to share a testimony on how i was directed to a Legit and real illuminati member who have transformed my life from grass to grace, from being poor to a rich woman who can now boast of a healthy and wealthy life without stress or financial difficulties. After so many months of trying to to be a member of the illuminati and was scammed the sum of $3,000 i became so desperate in being a member online who will not add to my pains, then i decided to contact a friend of mine who recently became a member, we discussed about the issue and to our conclusion she told me about a man called Paul mark who is the grand master in the illuminati. So i applied to become a member of illuminati easily without stress and all the preparations were made concerning how to become a member in two(2) days i became a member and the sum of 5 million dollars was deposited into my bank account so i want to advice any one who wants to become a member should call him [+](tel:+234%20913%20070%200648)2349163356894 or WhatsApp him [+](tel:+234%20913%20070%200648)2349163356894  or email ([illuminatiworldoffamous@gmail.com](https://groups.google.com/)) he does not know am doing this i pray that lucifer will bless him for the good things he has done in my life
