### ISSUE TITLE
Issue: .doc files are not supported by DirectoryLoader and ask to download LibreOffice

### ISSUE THREAD

**Issue by ragvendra3898** [langchain-ai/langchain#5598]
### Issue you'd like to raise.

Hi,
Whenever I am trying to upload a directory containing multiple files using DirectoryLoader, It is loading files properly.

from langchain.vectorstores import Chroma                                  
from langchain.embeddings import OpenAIEmbeddings                                 
from langchain.text_splitter import RecursiveCharacterTextSplitter , TokenTextSplitter             
from langchain.llms import OpenAI                                             
from langchain.chat_models import ChatOpenAI                                  
from langchain.chains import VectorDBQA, RetrievalQA                                        
from langchain.document_loaders import TextLoader, UnstructuredFileLoader, DirectoryLoader

loader = DirectoryLoader("D:/files/data", show_progress=True)  
docs = loader.load()                                                   
text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)                                             
vectordb = Chroma.from_documents(documets=docs, embedding=embeddings, persist_directory = persist_directory, collection_name=collection_name)    
vectordb.persist()                      
vectordb = None

but if my loaded directory is containing .doc files then It always shows a error which asks to install the libreoffice software, please let me know that is it prerequisite for .doc types file or there is any other way to fix this issue.

Thank You

**Comment by six5532one** [comment]
@ragvendra3898 `libreoffice` is a prerequisite for MS Office docs. On Mac, it can be installed with `brew install --cask libreoffice`.
