### ISSUE TITLE
Issue: How to let Agent act in a more consistent way, e.g., not jumping from a tool to another before a task is finished

### ISSUE THREAD

**Issue by jasonliu119** [langchain-ai/langchain#5607]
### Issue you'd like to raise.

Hi,

I am using Langchain to implement a customer service agent. I am using AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION and ConversationBufferMemory.

Findings:

1. the Agent works very well with lookup & retrieve QA, e.g., what is the material of a t-shirt, how long does it take to ship...

2. However, the Agent failed to process a task consistently.

- For example, Image the agent has two tools: [cancel-order-tool] & [size-lookup-tool]. 
- Now the user wants to cancel an order.
- User says: "I want to cancel the order of the XYZ t-shirt."
- Agent using [cancel-order-tool]: "Sorry to hear that. May I know why you want to cancel the order?"
- User: "The size is too big"
- Agent using [size-question-tool]: Please look up the size in the website size chart. 
                    ---> this is a wrong answer. The agent switched from [cancel-order-tool] to [size-lookup-tool].

How can I implement the consistency here? So that the Agent will continue to process the cancel-order issue instead of jumping into the size QA.

I think consistency is very important to the customer service application where we have kind of strict SOPs.

### Suggestion:

Maybe I should overwrite the plan function of the agent so that it can plan & act in a more consistent way? E.g., implement a state transit machine

**Comment by Xushanbo** [comment]
Do you have any solution yet? I met the same question.

**Comment by jasonliu119** [comment]
I have 2 solutions for this:
1. I have explicitly let the tool output a sentence, e.g., Next Tool to use <cancel-order-tool>, this can improve the consistency.
2. I am implementing a new Agent with a better plan method. So that it is more likely to choose the same action as the next action in a more consistent way.
