### ISSUE TITLE
Opensearch for Indexing and Retrieval 

### ISSUE THREAD

**Issue by finch986** [langchain-ai/langchain#5615]
### System Info

I am using Python for INdexing Document to OpenELastic search 

Python for Indexing---->
 documents = loader.load()
 text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
 docs = text_splitter.split_documents(documents)
vs = OpenSearchVectorSearch.from_documents(
            docs, 
            embeddings,
            opensearch_url="https://search-bterai-opensearch-gmtgf5ukflbg77xlwenvwko4gm.us-west-2.es.amazonaws.com", 
            http_auth=("XXXX", "XXXX"),     
            use_ssl = False,
            verify_certs = False,
            ssl_assert_hostname = False,
            ssl_show_warn = False,
            index_name="test_sidsfarm")

NodejS for Querying

const client = new Client({
    nodes: [process.env.OPENSEARCH_URL ?? "https://X:X@search-bterai-opensearch-gmtgf5ukflbg77xlwenvwko4gm.us-west-2.es.amazonaws.com"],        
});

const vectorStore = new OpenSearchVectorStore(new OpenAIEmbeddings(), {
    client,
    indexName: "test_sidsfarm"
});
const chain = VectorDBQAChain.fromLLM(model, vectorStore, {
    returnSourceDocuments: true,
  });

res = await chain.call({ query: input });

Its Giving me error below , Please help!!

failed to create query: Field 'embedding' is not knn_vector type.

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

ALready mentioned steps above

### Expected behavior

It should work out of the box irrespective of platforms

**Comment by finch986** [comment]
Fixed it by providing vector_field as embedding while indexing

**Comment by antoniordz96** [comment]
Ditto to this question. Is it possible to set the vector_field ?

**Comment by DantasB** [comment]
Yes! Inside the python code, while adding the documents to the vectorstore object, you can pass a parameter with kwargs called vector_field. 

By default this parameter is read as "vector_field" but in this case (using nodejs for querying) you need to change this to "embedding".

Example:
```python
vectorstore.add_documents(splits, bulk_size=bulk_size, vector_field="embedding")
```

So you can avoid this error on node.js
