### ISSUE TITLE
I want ssh tunnel support in SQLDatabaseChain

### ISSUE THREAD

**Issue by hukuhuku-matsuo** [langchain-ai/langchain#5645]
### Feature request

Due to security reasons, it is not always possible to connect directly to the DB. I want SQLDatabaseChain to support ssh tunnel because I have to connect to a specific kind of stepping stone server before I can connect to the DB.

If there is already a way to accomplish this, I apologize.

### Motivation

I want to use llm with all our own data to create an innovative experience, and SQLDatabaseChain makes that possible.

### Your contribution

I can contribute with testing. I do not yet have a good understanding of langchain's source code structure and inner workings, so coding contributions would not be appropriate.

**Comment by Jflick58** [comment]
It might be interesting to include some args to support this in the SQLDatabase class, but doing this is relatively straightforward so I don't know if it really nesseciates adding complexity to the SQLDatabase class.

Per [this SO answer](https://stackoverflow.com/questions/31506958/sqlalchemy-through-paramiko-ssh) it looks like you could use the `sshtunnel` library to use Python to port forward a ssh connection to your db server, and then just refer to localhost when you connect to the db. 

```
from sshtunnel import SSHTunnelForwarder
from langchain import OpenAI, SQLDatabase, SQLDatabaseChain

server = SSHTunnelForwarder(
    ('10.0.0.101', 22),
    ssh_username="my_username",
    ssh_password="my_password",
    remote_bind_address=('127.0.0.1', 5432)
    )

postgres_user = "user"
postgres_pswd = "password" 
db_name = "db"

server.start()
local_port = str(server.local_bind_port)

db = SQLDatabase.from_uri(f"postgresql://{postgres_user}:{postgres_pswd}@127.0.0.1:{local_port}/{db_name}')
llm = OpenAI(temperature=0, verbose=True)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
```
