### ISSUE TITLE
Issue: When using agent_chain.run to query documents, I want to return both the LLM answer and Source documents, however agent_chain.run only allows for exactly 1 output

### ISSUE THREAD

**Issue by ShinySylveonn** [langchain-ai/langchain#5656]
### Issue you'd like to raise.

agent_chain.run does not allow for more than a single output, when calling RetrievalQA.from_chain_type directly with the same query it has no issues returning multiple outputs, however agent_chain is where all of my custom tools and configurations are.

agent_chain.run in my code at the moment refers to AgentExecutor.from_agents_and_tools

Is there a current workaround for this or is there a strong reason why .run can only support a single output?

**Comment by OlajideOgun** [comment]
use it like this `agent_executor({"input": user_prompt})`

**Comment by malinphy** [comment]
> use it like this `agent_executor({"input": user_prompt})`

Can you explain how to do it?

**Comment by OlajideOgun** [comment]
`prompt = " your prompt here"`
instead of 
`agent_chain.run(prompt)`

you can use agent_chain like this

`agent_chain({"input": prompt})`

which will return a dictionary.
