### ISSUE TITLE
Conversational Agent ignored correct answer from Search

### ISSUE THREAD

**Issue by JavaFXpert** [langchain-ai/langchain#566]
When using a conversational agent, a correct answer from a search tool was ignored. The search was for "who is the monarch of England?" Here's the output:

```
> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: Search
Action Input: monarch of England
Observation: Charles III
Thought: Do I need to use a tool? No
AI: The current monarch of England is Queen Elizabeth II.

> Finished chain.
```

Here's the chain relevant code:

```
    llm = OpenAI(temperature=0)

    search = GoogleSearchAPIWrapper()
    tools = [
        Tool(
            "Search",
            SerpAPIWrapper().run,
            "A search engine. Useful for when you need to answer questions about current events. Input should be a search query.",
        ),
        Tool(
            "PAL-MATH",
            PALChain.from_math_prompt(llm).run,
            "A language model that is really good at solving complex word math problems. Input should be a math problem.",
        ),
    ]

    memory = ConversationBufferMemory(memory_key="chat_history")

    chain = initialize_agent(tools, llm, agent="conversational-react-description", verbose=True, memory=memory)
```

**Comment by commissarster** [comment]
I installed the latest version 0.0.126 of Langchain, but encountered an error when running the program. 
```
ValueError: "ConversationBufferMemory" object has no field "buffer"
```
However, installed to version 0.0.101, I still encountered the same issue as the original poster.

**Comment by honemleysm** [comment]
> original

I have the same issue when running visualGPT at the line:
File "...\visual-chatgpt\visual_chatgpt.py", line 1030, in run_text
    self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "ConversationBufferMemory" object has no field "buffer"

Anyone can help on this issue? Why the property "buffer" can't be recognized at this mement?

**Comment by honemleysm** [comment]
> > original
> 
> I have the same issue when running visualGPT at the line: File "...\visual-chatgpt\visual_chatgpt.py", line 1030, in run_text self.agent.memory.buffer = cut_dialogue_history(self.agent.memory.buffer, keep_last_n_words=500) File "pydantic\main.py", line 357, in pydantic.main.BaseModel.**setattr** ValueError: "ConversationBufferMemory" object has no field "buffer"
> 
> Anyone can help on this issue? Why the property "buffer" can't be recognized at this mement?

This issue only happens on 0.0.126, while for version 0.0.101, it is OK.
