### ISSUE TITLE
UnstructuredURLLoader hangs on some URLs

### ISSUE THREAD

**Issue by jawMeister** [langchain-ai/langchain#5670]
### System Info

Python 3.10.6

Win 11 WSL running:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

AMD 5950x CPU w/128GB mem

Python packages installed:

Package                 Version
----------------------- -----------
aiohttp                 3.8.4
aiosignal               1.3.1
altair                  4.2.2
anyio                   3.7.0
appdirs                 1.4.4
argilla                 1.8.0
asttokens               2.2.1
async-timeout           4.0.2
attrs                   23.1.0
backcall                0.2.0
backoff                 2.2.1
beautifulsoup4          4.12.2
blinker                 1.6.2
cachetools              5.3.0
certifi                 2023.5.7
cffi                    1.15.1
chardet                 5.1.0
charset-normalizer      3.1.0
click                   8.1.3
comm                    0.1.3
commonmark              0.9.1
contourpy               1.0.7
cryptography            40.0.2
cvxpy                   1.3.1
cycler                  0.11.0
dataclasses-json        0.5.7
debugpy                 1.6.7
decorator               5.1.1
Deprecated              1.2.14
ecos                    2.0.12
empyrical               0.5.5
entrypoints             0.4
et-xmlfile              1.1.0
exceptiongroup          1.1.1
executing               1.2.0
fastjsonschema          2.17.1
fonttools               4.39.4
fredapi                 0.5.0
frozendict              2.3.8
frozenlist              1.3.3
gitdb                   4.0.10
GitPython               3.1.31
greenlet                2.0.2
h11                     0.14.0
html5lib                1.1
httpcore                0.16.3
httpx                   0.23.3
idna                    3.4
importlib-metadata      6.6.0
inflection              0.5.1
install                 1.3.5
ipykernel               6.23.1
ipython                 8.13.2
jedi                    0.18.2
Jinja2                  3.1.2
joblib                  1.2.0
jsonschema              4.17.3
jupyter_client          8.2.0
jupyter_core            5.3.0
kaleido                 0.2.1
kiwisolver              1.4.4
langchain               0.0.174
lxml                    4.9.2
Markdown                3.4.3
markdown-it-py          2.2.0
MarkupSafe              2.1.2
marshmallow             3.19.0
marshmallow-enum        1.5.1
matplotlib              3.7.1
matplotlib-inline       0.1.6
mdurl                   0.1.2
monotonic               1.6
more-itertools          9.1.0
msg-parser              1.2.0
multidict               6.0.4
multitasking            0.0.11
mypy-extensions         1.0.0
Nasdaq-Data-Link        1.0.4
nbformat                5.9.0
nest-asyncio            1.5.6
nltk                    3.8.1
numexpr                 2.8.4
numpy                   1.23.5
olefile                 0.46
openai                  0.27.7
openapi-schema-pydantic 1.2.4
openpyxl                3.1.2
osqp                    0.6.2.post9
packaging               23.1
pandas                  1.5.3
pandas-datareader       0.10.0
parso                   0.8.3
pdf2image               1.16.3
pdfminer.six            20221105
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.5.0
pip                     22.0.2
platformdirs            3.5.1
plotly                  5.14.1
prompt-toolkit          3.0.38
protobuf                3.20.3
psutil                  5.9.5
ptyprocess              0.7.0
pure-eval               0.2.2
pyarrow                 12.0.0
pycparser               2.21
pydantic                1.10.7
pydeck                  0.8.1b0
pyfolio                 0.9.2
Pygments                2.15.1
Pympler                 1.0.1
pypandoc                1.11
pyparsing               3.0.9
pyportfolioopt          1.5.5
pyrsistent              0.19.3
pytesseract             0.3.10
python-dateutil         2.8.2
python-docx             0.8.11
python-dotenv           1.0.0
python-magic            0.4.27
python-pptx             0.6.21
pytz                    2023.3
PyYAML                  6.0
pyzmq                   25.1.0
qdldl                   0.1.7
Quandl                  3.7.0
regex                   2023.5.5
requests                2.30.0
rfc3986                 1.5.0
rich                    13.0.1
scikit-learn            1.2.2
scipy                   1.10.1
scs                     3.2.3
seaborn                 0.12.2
setuptools              67.7.2
six                     1.16.0
smmap                   5.0.0
sniffio                 1.3.0
soupsieve               2.4.1
SQLAlchemy              2.0.14
stack-data              0.6.2
stqdm                   0.0.5
streamlit               1.22.0
ta                      0.10.2
TA-Lib                  0.4.26
tabulate                0.9.0
tenacity                8.2.2
threadpoolctl           3.1.0
tiktoken                0.4.0
toml                    0.10.2
toolz                   0.12.0
tornado                 6.3.2
tqdm                    4.65.0
traitlets               5.9.0
typer                   0.9.0
typing_extensions       4.5.0
typing-inspect          0.8.0
tzdata                  2023.3
tzlocal                 5.0.1
unstructured            0.7.1
urllib3                 2.0.2
validators              0.20.0
watchdog                3.0.0
wcwidth                 0.2.6
webencodings            0.5.1
wikipedia               1.4.0
wrapt                   1.14.1
xlrd                    2.0.1
XlsxWriter              3.1.2
yarl                    1.9.2
yfinance                0.2.18
zipp                    3.15.0

### Who can help?

@MthwRobinson

https://github.com/hwchase17/langchain/commits?author=MthwRobinson

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

url = "https://www.nasdaq.com/articles/apple-denies-surveillance-claims-made-by-russias-fsb"

loader = UnstructuredURLLoader(urls=[url], continue_on_failure=False)
data = loader.load()

stopping the process shows this stack:

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[2], line 4
      1 url = "https://www.nasdaq.com/articles/apple-denies-surveillance-claims-made-by-russias-fsb"
      3 loader = UnstructuredURLLoader(urls=[url], continue_on_failure=False)
----> 4 data = loader.load()

File [~/development/public/portfolio-analysis-app/.venv/lib/python3.10/site-packages/langchain/document_loaders/url.py:90](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/jaws/development/public/portfolio-analysis-app/notebooks/~/development/public/portfolio-analysis-app/.venv/lib/python3.10/site-packages/langchain/document_loaders/url.py:90), in UnstructuredURLLoader.load(self)
     88 if self.__is_non_html_available():
     89     if self.__is_headers_available_for_non_html():
---> 90         elements = partition(
     91             url=url, headers=self.headers, **self.unstructured_kwargs
     92         )
     93     else:
     94         elements = partition(url=url, **self.unstructured_kwargs)

File [~/development/public/portfolio-analysis-app/.venv/lib/python3.10/site-packages/unstructured/partition/auto.py:96](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/jaws/development/public/portfolio-analysis-app/notebooks/~/development/public/portfolio-analysis-app/.venv/lib/python3.10/site-packages/unstructured/partition/auto.py:96), in partition(filename, content_type, file, file_filename, url, include_page_breaks, strategy, encoding, paragraph_grouper, headers, ssl_verify, ocr_languages, pdf_infer_table_structure, xml_keep_tags)
     93 exactly_one(file=file, filename=filename, url=url)
     95 if url is not None:
---> 96     file, filetype = file_and_type_from_url(
     97         url=url,
     98         content_type=content_type,
     99         headers=headers,
    100         ssl_verify=ssl_verify,
    101     )
...
-> 1130         return self._sslobj.read(len, buffer)
   1131     else:
   1132         return self._sslobj.read(len)

KeyboardInterrupt:

### Expected behavior

expect that it does not hang

**Comment by MthwRobinson** [comment]
@jawMeister - Thanks for flagging, will take a look at this as soon as I can.

**Comment by naazweb** [comment]
The issue still persists. Requesting to reopen.

``` 
 File "/app/./framework/langchain/loader_manager.py", line 848, in load
    documents = loader.load()
                │      └ <function UnstructuredURLLoader.load at 0x7f3cbbfe9e10>
                └ <langchain_community.document_loaders.url.UnstructuredURLLoader object at 0x7f3c9e85cc40>

  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/url.py", line 148, in load
    raise e
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/url.py", line 131, in load
    elements = partition(
               └ <function partition at 0x7f3c9c701870>
  File "/usr/local/lib/python3.10/site-packages/unstructured/partition/auto.py", line 275, in partition
    file, filetype = file_and_type_from_url(
    │                └ <function file_and_type_from_url at 0x7f3c9c0aef80>
    └ None
  File "/usr/local/lib/python3.10/site-packages/unstructured/partition/auto.py", line 566, in file_and_type_from_url
    response = requests.get(url, headers=headers, verify=ssl_verify, timeout=request_timeout)
               │        │   │            │               │                   └ None
               │        │   │            │               └ True
               │        │   │            └ {}
               │        │   └ 'https://www.monexgroup.jp/jp/news_release.html'
               │        └ <function get at 0x7f3cef935a20>
               └ <module 'requests' from '/usr/local/lib/python3.10/site-packages/requests/__init__.py'>
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           │              │           │         └ {'headers': {}, 'verify': True, 'timeout': None}
           │              │           └ None
           │              └ 'https://www.monexgroup.jp/jp/news_release.html'
           └ <function request at 0x7f3cef9889d0>
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {}, 'verify': True, 'timeout': None}
           │       │              │           └ 'https://www.monexgroup.jp/jp/news_release.html'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7f3cef9351b0>
           └ <requests.sessions.Session object at 0x7f3c9e85cbb0>
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': None, 'allow_redirects': True, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7f3cef935630>
           └ <requests.sessions.Session object at 0x7f3c9e85cbb0>
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'timeout': None, 'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7f3cef934af0>
        └ <requests.adapters.HTTPAdapter object at 0x7f3c9c08e830>
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
          │                            └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.ConnectionError'>
```
