### ISSUE TITLE
Index not found when trying to use ChromaDB instead of FAISS in the AutoGPT example

### ISSUE THREAD

**Issue by ibagur** [langchain-ai/langchain#5683]
### System Info

Python 3.10.10 (virtual env) on macos 11.7.6

langchain               0.0.187
duckdb                  0.7.1
duckduckgo-search       3.7.1
chromadb                0.3.21
tiktoken                0.3.3
torch                   2.0.0

### Who can help?

@hwchase17 @eyur

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Dear community,

 I am now playing a bit with the AutoGPT example notebook found in the Langchain documentation, in which I already replaced the search tool for `DuckDuckGoSearchRun()` instead `SerpAPIWrapper()`. So far this works seamlessly. I am now trying to use ChromaDB as vectorstore (in persistent mode), instead of FAISS..however I cannot find how to properly initialize Chroma in this case. I have seen plenty of examples with ChromaDB for documents and/or specific web-page contents, using the `loader` class and then the `Chroma.from_documents()` method. But in the AutoGPT example, they actually use FAISS in the following way, just initializing as an empty vectorstore with fixed embedding size:
```
# Define your embedding model
embeddings_model = OpenAIEmbeddings()
# Initialize the vectorstore as empty
import faiss
FAISS()
embedding_size = 1536
index = faiss.IndexFlatL2(embedding_size)
vectorstore = FAISS(embeddings_model.embed_query, index, InMemoryDocstore({}), {})
```
I have tried the following approach without success (after creating the `chroma` subdirectory). Apparently both `chroma-collections.parquet` and `chroma-embeddings.parquet` are created, and I get the confirmation message `Using embedded DuckDB with persistence: data will be stored in: chroma`, but when doing `agent.run(["[here goes my query"])`, I get the error `NoIndexException: Index not found, please create an instance before querying`. The code I have used in order to create the Chroma vectorstore is:

```
persist_directory = "chroma"
embeddings_model = OpenAIEmbeddings()

chroma_client = chromadb.Client(
            settings=chromadb.config.Settings(
                chroma_db_impl="duckdb+parquet",
                persist_directory=persist_directory,
            )
        )

vectorstore = Chroma(persist_directory=persist_directory, embedding_function=embeddings_model, client=chroma_client, collection_metadata={})
vectorstore.persist()
```

I also cannot find how to replicate the same approach used with FAISS, i.e. initializing as an empty store with a given `embedding_size` (1536 in this case).

Any suggestions, or maybe I am overdoing things? It was just a matter of playing that particular example but using a different vectorstore, so to get familiar with the use of Indexes and so.

Many thanks!

### Expected behavior

Being able to reproduce the [AutoGPT Tutorial](https://python.langchain.com/en/latest/use_cases/autonomous_agents/autogpt.html) , making use of LangChain primitives but using ChromaDB (in persistent mode) instead of FAISS

**Comment by albinjosep** [comment]
Based on your description, it seems you are trying to replace the FAISS vector store in the AutoGPT tutorial with ChromaDB in persistent mode. However, you're facing some issues initializing ChromaDB properly. Here's a suggested approach to initialize ChromaDB as a vector store in the AutoGPT:

from chromadb.vectorstore import Chroma
from langchain.vectorstores.faiss import FAISS
from langchain.embeddings.openai_embeddings import OpenAIEmbeddings
import chromadb

# Initialize the ChromaDB client
persist_directory = "chroma"
chroma_client = chromadb.Client(
    settings=chromadb.config.Settings(
        chroma_db_impl="duckdb+parquet",
        persist_directory=persist_directory,
    )
)

# Define your embedding model
embeddings_model = OpenAIEmbeddings()

# Initialize the vectorstore as empty
vectorstore = Chroma(
    persist_directory=persist_directory,
    embedding_function=embeddings_model,
    client=chroma_client,
    collection_metadata={}
)
vectorstore.persist()

# Optionally, you can add documents to the ChromaDB vectorstore
# vectorstore.add_documents(documents)

# Now you can use the vectorstore for querying

In this code snippet, we first import the necessary modules and classes from ChromaDB and Langchain. Then, we initialize the ChromaDB client with the desired settings, including the persistence directory. Next, we define the embedding model, which is OpenAIEmbeddings in your case.

Finally, we create an instance of the Chroma vector store, passing the persistence directory, embedding function, ChromaDB client, and an empty dictionary for collection metadata. We call the persist() method on the vector store to ensure the data is stored persistently.

You can optionally add documents to the vector store using the add_documents() method if you have any. Finally, you can use the vector store for querying as needed.

**Comment by ibagur** [comment]
Hi, many thanks for you reply. However I have not fully understand the solution. You suggest me to add documents to the ChromaDB I just created:

`vectorstore.add_documents(documents)`

But what would be those `documents`? In the AutoGPT tutorial with FAISS, no actual documents are being added, as once you initialize FAISS, I guess it is temporarily storing in memory the results of the internet searches the agent is doing.

What would be the case then when using Chroma instead of FAISS in this particular tutorial? How can I initialize the chroma vectorstore without documents whatsoever, in the same way that it is done with FAISS?

Many thanks

**Comment by wmbutler** [comment]
@ibagur I'm going down the same path as you. I am trying to use weighted vectors as shown in this example. Ideally, instead of passing a document in with FAISS, I'd rather use the content in my ChromaDB as the vector store. I'll monitor this issue and let you know if I make any headway.

https://python.langchain.com/en/latest/modules/indexes/retrievers/examples/time_weighted_vectorstore.html

**Comment by ibagur** [comment]
@wmbutler I actually managed to get it work...or at least it is running and generating a written report with the results.

I first create a chroma client:

```
# Define chroma client
persist_directory = "chroma"
metric = "cosine"

embeddings_model = OpenAIEmbeddings()

chroma_client = chromadb.Client(
    settings=chromadb.config.Settings(
                chroma_db_impl="duckdb+parquet",
                persist_directory=persist_directory,
            )
)
```

Then I define a Chroma vectorstore...and add an empty text so it creates an `index` subfolder under `/chroma` folder. I use also `vectorstore.persist()` to actually create the parquet files for persistent storage.

```
# Define vectorstore
vectorstore = Chroma(persist_directory=persist_directory, embedding_function=embeddings_model, client=chroma_client, collection_metadata={})
# Add empty text (this actua
vectorstore.add_texts([""])
# Use persist so it creates the parquet files
vectorstore.persist()
```

The rest is exactly the same as in the original tutorial, and the agent seems to run and generate some .txt files with the results.

I did also tried same as above but defining `collection_metadata` to use a 'cosine' metric, but I do not know whether it makes any difference:

```
vectorstore = Chroma(persist_directory=persist_directory, embedding_function=embeddings_model, client=chroma_client, collection_metadata={"hnsw:space": metric})

vectorstore.add_texts([""])
vectorstore.persist()
```

In any case, during running, I get these warnings at the beginning of the verbose output:

```
Chroma collection langchain contains fewer than 4 elements.
Chroma collection langchain contains fewer than 3 elements.
Chroma collection langchain contains fewer than 2 elements.
```

**Comment by summer-silence** [comment]
How can I interact with autogpt？For example，adding human feedback？
