### ISSUE TITLE
support local GPU server without runhouse !!!

### ISSUE THREAD

**Issue by htang2012** [langchain-ai/langchain#5689]
### Feature request

Hi guys, can we just launch SelfHostedEmbedding without runhouse, as a matter of fact, runhouse its self is still in the early development stage and has some issues, why does langchain depends on it for selfhosted instead of call cuda directly?

for example:

device = torch.device('cuda')

embeddings = SelfHostedEmbeddings(
    model_load_fn=get_pipeline, 
    hardware=device,
    model_reqs=["./", "torch", "transformers"],
    inference_fn=inference_fn
)

### Motivation

use GPU local server directly instead of through runhouse.

### Your contribution

*

**Comment by Xmaster6y** [comment]
If by local you mean directly on your machine, the is `SelfHostedHuggingFaceLLM`. If you mean on a local server, maybe this PR #2830 solves your problem. (Feel free to review, contribute)

**Comment by oapandit** [comment]
Hi,

I am trying to do similar thing but still getting error.

```python
from langchain.llms import SelfHostedHuggingFaceLLM
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import runhouse as rh


def get_pipeline(model_id = "decapoda-research/llama-7b-hf"):
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(model_id)
    pipe = pipeline(
        "text-generation", model=model, tokenizer=tokenizer
    )
    return pipe

gpu = rh.cluster(name="rh-a10x", instance_type="A100:1")

hf = SelfHostedHuggingFaceLLM(
    model_load_fn=get_pipeline, hardware=gpu)
``` 

So the setup is that I have reserved a GPU and there I want to run this code.
But I get the following error
```typescript
ValueError: Cluster must have an ip address (i.e. be up) or have a reup_cluster method (e.g. OnDemandCluster).
``` 




I just want to use the local GPU to load the model and get response from the model. This exercise is to understand how it works for me.

If you can provide some pointers it will be really great!

thanks,
Onkar

**Comment by htang2012** [comment]
> 
I believe that this is the big defect inside Langchain, and there is no one takes care of it. 

Setup up Runhouse and make it working is a nightmare for me over and over. I spent almost 90% of my efforts to setup runhouse server and client and make langchain code running on our accelerator only took less than 10%. 
 
Hi guys: Stop bond Runhouse and provide direct access to the local HPU/GPU accelerator !!!

**Comment by htang2012** [comment]
> Hi,
> 
> I am trying to do similar thing but still getting error.
> 
> ```python
> from langchain.llms import SelfHostedHuggingFaceLLM
> from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
> import runhouse as rh
> 
> 
> def get_pipeline(model_id = "decapoda-research/llama-7b-hf"):
>     tokenizer = AutoTokenizer.from_pretrained(model_id)
>     model = AutoModelForCausalLM.from_pretrained(model_id)
>     pipe = pipeline(
>         "text-generation", model=model, tokenizer=tokenizer
>     )
>     return pipe
> 
> gpu = rh.cluster(name="rh-a10x", instance_type="A100:1")
> 
> hf = SelfHostedHuggingFaceLLM(
>     model_load_fn=get_pipeline, hardware=gpu)
> ```
> 
> So the setup is that I have reserved a GPU and there I want to run this code. But I get the following error
> 
> ```ts
> ValueError: Cluster must have an ip address (i.e. be up) or have a reup_cluster method (e.g. OnDemandCluster).
> ```
> 
> I just want to use the local GPU to load the model and get response from the model. This exercise is to understand how it works for me.
> 
> If you can provide some pointers it will be really great!
> 
> thanks, Onkar

I believe that this is the big defect inside Langchain, and there is no one takes care of it.

Setup up Runhouse and make it working is a nightmare for me over and over. I spent almost 90% of my efforts to setup runhouse server and client and make langchain code running on our accelerator only took less than 10%.

Hi guys: Stop bond Runhouse and provide direct access to the local HPU/GPU accelerator !!!

**Comment by mantrakp2004** [comment]
+1, did you figure out how to run embeddings locally using run house?
