### ISSUE TITLE
Regular Expression Fails to Match Newline-Starting Action Inputs

### ISSUE THREAD

**Issue by dpoulopoulos** [langchain-ai/langchain#5717]
### System Info

LangChain version: `0.0.189`
OS: Ubuntu `22.04.2`
Python version: `3.10.7`

### Who can help?

@vowelparrot

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Reproducing this issue can be challenging as it hinges on the action input generated by the LLM. Nevertheless, the issue occurs when using an agent of type `CONVERSATIONAL_REACT_DESCRIPTION`. The agent's output parser attempts to [extract](https://github.com/hwchase17/langchain/blob/d0d89d39efb5f292f72e70973f3b70c4ca095047/langchain/agents/conversational/output_parser.py#L21) both the tool's name that the agent needs to utilize for its task and the input to that tool based on the LLM prediction.

In order to accomplish this, the agent's output parser employs the following regular expression on the LLM prediction: `Action: (.*?)[\n]*Action Input: (.*)`. This expression divides the LLM prediction into two components: i) the tool that needs to be utilized (Action) and ii) the tool's input (Action Input).

However, the action input generated by an LLM is an arbitrary string. Hence, if the action input initiates with a newline character, the regular expression's search operation fails to find a match, resulting in the action input defaulting to an empty string. This issue stems from the fact that the `.` character in the regular expression doesn't match newline characters by default. Consequently, `(.*)` stops at the end of the line it started on.

This behavior aligns with the default functionality of the Python `re` library. To rectify this corner case, we must include the [`re.S`](https://docs.python.org/3/library/re.html#:~:text=in%20version%203.11.-,re.S,-%C2%B6) flag in the `re.search()` method. This will allow the `.` special character to match any character, including a newline.

> re.S
> re.DOTALL
> Make the '.' special character match any character at all, including a newline; without this flag, '.' will match anything except a newline. Corresponds to the inline flag (?s).

### Expected behavior

The `re.search()` method correctly matches the action input section of the LLM prediction and sets it to the relevant string, even if it starts with the new line character.

I am prepared to open a new Pull Request (PR) to address this issue. The change involves modifying the following [line](https://github.com/hwchase17/langchain/blob/d0d89d39efb5f292f72e70973f3b70c4ca095047/langchain/agents/conversational/output_parser.py#L21):

From:

```python

match = re.search(regex, text)
```

To:

```python

match = re.search(regex, text, re.S)
```

**Comment by zscgeek** [comment]
Hi - I am running into this as well. Any news on a fix/
