### ISSUE TITLE
DOC: How to install from source?

### ISSUE THREAD

**Issue by sagar-spkt** [langchain-ai/langchain#5722]
### Issue with current documentation:

I might've not noticed but I didn't see anywhere in the document instructions to install langchain from source so developers can work/test latest updates.the 

### Idea or request for content:

Add setup instructions from the source in the installation section in README.md.

**Comment by Gordon-BP** [comment]
There's install from source instructions in the docs here https://python.langchain.com/en/latest/reference/installation.html#installing-from-source You basically clone the repo then run `pip install -e .`

**Comment by jsjolund** [comment]
The actual commands are:

```sh
git clone https://github.com/langchain-ai/langchain.git
pip install -e langchain/libs/langchain
```

The documentation does not make that clear atm.
