### ISSUE TITLE
Issue: Getting total_tokens for each chain in sequential chains

### ISSUE THREAD

**Issue by gskrypka** [langchain-ai/langchain#5724]
### Issue you'd like to raise.

Hello guys,

I'm wondering how can I get total_tokens for each chain in sequential chain. I'm working on optimisation of sequential chains and want to check how much does each step cost. Unfortunately get_openai_callback returns total_tokens for the whole sequential chain rather then each one.

**Comment by KeshavSingh29** [comment]
I think its explicitly stated in the documentation and you can get it for each chain. 
https://python.langchain.com/en/latest/modules/models/llms/examples/token_usage_tracking.html?highlight=token

**Comment by gskrypka** [comment]
Yeah. However it calculates for the whole sequential chain or multiple chains nested in manager. However I need to calculate each step separately so that I can optimise token spending for each step individually. 

I believe it is possible with making custom callback handler.

**Comment by stefangeneralao** [comment]
@gskrypka Did you manage to solve it with a custom callback? I'm facing a similar issue.

**Comment by antti-ngp** [comment]
I have a similar issue. I'd like to call runnable.batch() with multiple inputs and then store the token usage separately for each input.
