### ISSUE TITLE
Issue: Correctness of generated SQL queries

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#5726]
### Issue you'd like to raise.

I have a huge database hosted in BigQuery. The recommended approach to querying this via natural language is using agents. However, this diminishes the control I have over the intermediate steps, and that leads to many problems.
- The generated query isn't correct, and this cannot be reinforced at any intermediate step
- Clauses like "ORDER BY" brings _NULL_ to the top, and no amount of prompt engineering can retrieve the top non-null value

Are there any workarounds for this? Or is there any other approach recommended for handling databases of this scale?

**Comment by cachatj** [comment]
Any progress made here getting more control before queries get full send over to BQ??
