### ISSUE TITLE
DOC: PrompTemplate format with docs

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#5756]
### Issue with current documentation:

Hi, how can I see what my final prompt looks like when retrieving docs? For example, I'm not quite sure how this will end up looking:

```python
prompt_template = """Answer based on context:\n\n{context}\n\n{question}"""

PROMPT = PromptTemplate(template=prompt_template, input_variables=["context", "question"])

qa = RetrievalQA.from_chain_type(
  llm=sm_llm,
  chain_type="stuff",
  retriever=docsearch.as_retriever(),
  chain_type_kwargs={"prompt": PROMPT},
)

result = qa.run(question)
```

**Comment by KeshavSingh29** [comment]
print qa object or look at its attributes/methods and you will know.

**Comment by austinmw** [comment]
That doesn't give me a final prompt formatted with included documents.

**Comment by KeshavSingh29** [comment]
What do you mean by final prompt here? 
This is the qa object that you get when not changing the prompt: 
```python 
RetrievalQA(memory=None, callback_manager=<langchain.callbacks.shared.SharedCallbackManager object at 0x107684550>, verbose=False, combine_documents_chain=StuffDocumentsChain(memory=None, callback_manager=<langchain.callbacks.shared.SharedCallbackManager object at 0x107684550>, verbose=False, input_key='input_documents', output_key='output_text', llm_chain=LLMChain(memory=None, callback_manager=<langchain.callbacks.shared.SharedCallbackManager object at 0x107684550>, verbose=False, prompt=ChatPromptTemplate(input_variables=['context', 'question'], output_parser=None, partial_variables={}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context'], output_parser=None, partial_variables={}, template="Use the following pieces of context to answer the users question. \nIf you don't know the answer, just say that you don't know, don't try to make up an answer.\n----------------\n{context}", template_format='f-string', validate_template=True), additional_kwargs={}), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['question'], output_parser=None, partial_variables={}, template='{question}', template_format='f-string', validate_template=True), additional_kwargs={})]), llm=ChatOpenAI(verbose=False, callback_manager=<langchain.callbacks.shared.SharedCallbackManager object at 0x107684550>, client=<class 'openai.api_resources.chat_completion.ChatCompletion'>, model_name='gpt-3.5-turbo', temperature=0.05, model_kwargs={}, openai_api_key=None, openai_organization=None, request_timeout=60, max_retries=6, streaming=False, n=1, max_tokens=None), output_key='text'), document_prompt=PromptTemplate(input_variables=['page_content'], output_parser=None, partial_variables={}, template='{page_content}', template_format='f-string', validate_template=True), document_variable_name='context'), input_key='query', output_key='result', return_source_documents=False, retriever=VectorStoreRetriever(vectorstore=<bot.database.vectorstores.milvus.Milvus object at 0x13851e6e0>, search_type='similarity', search_kwargs={'k': 1}))
```

**Comment by austinmw** [comment]
Yes, but I'd like to see exactly how each document is formatted into the prompt by printing out the final fully formed string into to the LLM

**Comment by Ayenem** [comment]
None of the replies actually answered OP. Came here for the same question.

How can we see the *actual* *final* prompt that the llm acts upon for generation. Not the templates to put together, the *final* prompt with all formatting placeholders filled.

It's a bit absurd that such a basic sanity check functionality isn't readily available.

**Comment by austinmw** [comment]
I think the answer ended up being to put `verbose=True` in nearly every langchain object 😅

**Comment by Ayenem** [comment]
That had a bug (idk if fixed now) where the work around is to `set.verbose.on.the.object.yourself=True` and I'm not sure that actually shows the final prompt.

Currently I'm looking at:
https://github.com/langchain-ai/langchain/blob/15f650ae8cfb7d45bd9f50c086d2b8cfb0182a40/libs/langchain/langchain/chains/llm.py#L144
and:
https://github.com/langchain-ai/langchain/blob/15f650ae8cfb7d45bd9f50c086d2b8cfb0182a40/libs/langchain/langchain/chains/llm.py#L101

These actually work and show the final prompt that the llm sees. But I'm not very happy with having to inject print statements there.
