### ISSUE TITLE
Improving Custom Agent Speed?

### ISSUE THREAD

**Issue by Radvian** [langchain-ai/langchain#5763]
### Discussed in https://github.com/hwchase17/langchain/discussions/5730

<div type='discussions-op-text'>

<sup>Originally posted by **Radvian** June  5, 2023</sup>

Hello, not sure if I should ask this in Discussion or Issue, so apologies beforehand.

I'm doing a passion project in which I try to create a knowledge base for a website, and create a Conversational Retrieval QA Chain so we can ask questions about the knowledge base. 

This is very much akin to this: https://python.langchain.com/en/latest/modules/chains/index_examples/chat_vector_db.html 

And I have no problem to implement it. 

Now, I want to go to the next step. Instead of creating a chain, I want to create an agent.

I want to do something like this:
- First, always ask the user for their name.
- If the user asks a particular question that is not in the knowledge base, don't reply with "I don't know", but search Wikipedia about it
- If the user asks about X, send an image link (from google search images) of 'X' item
- and few other custom tools

And, I also don't have any problem in creating tools and combining them into a unified agent.

However, my problem is this (and this is expected): the agent performs slower, much slower than if I just use the chain.

If I only use Retrieval QA Chain, and enables _streaming_, it can start typing the output in less than 5 seconds.

If I use the complete agent, with a few custom tools, it starts to type the answer / output within 10-20 seconds.

I know this is to be expected, since the agent needs to think about which tools to use. But any ideas on how to make this faster? In the end, I want to deploy this whole project in a streamlit and wants this to perform like a 'functional' chatbot, with almost-instant reply, and not having to wait 10-20 seconds before the 'agent' starts typing.

Any ideas are welcome, apologies if this is a stupid question. Thank you!</div>

**Comment by KeshavSingh29** [comment]
I have been working on something similar so here are my finding that might help you. 
1. If you set verbose and streaming to true, you can see the agent writing the thought process as well (thats the part that takes time). Before deciding what action to take, the agent or CHATgpt needs to write a response which makes things slow if your agent keeps using multiple tools. 
2. One thing you can do to speed up is by using only the top similar knowledge retrieved from KB and refine your prompt and set max_interactions to 2-3 depending on your application.

**Comment by PNBnag007** [comment]
Hey @Radvian, I am also facing the same issue. Did you find any workaround to increase the agent speed?

**Comment by guidorietbroek** [comment]
When I'm looking at the output with verbose=True I do see that it takes some time to take all the steps. So I'm very curious if there are ways to speed up the proces. 

But combining multiple chains will give delay (I think), especially when I ask more complex questions. So maybe it's also a good thing you need to catch in the front end. Using an indication that the question is being answered or something so the user knows that the bot is still working on it.
