### ISSUE TITLE
Dynamic loading of tools and custom tools

### ISSUE THREAD

**Issue by skye0402** [langchain-ai/langchain#5774]
### Feature request

Maybe I didn't get the idea: Some tools can be loaded like 'google-search' other tools can't be loaded like duckduckgo-search by the load_tools: langchain/agents/load_tools.py
E.g. specified in _EXTRA_OPTIONAL_TOOLS.
As for custom tools they can't be loaded at all it seems in that way. It would be great to register custom tools so that they can be loaded by load_tools as well.

I've done something like this for the moment, so I have Class-Names for my own tools and the lower-case would be standard:

```
        standard_tools = []
        for toolStr in tool_names:
            if toolStr[0].islower():
                standard_tools.append(toolStr)
        self.tools = load_tools(standard_tools, **tool_kwargs)
        for toolStr in tool_names:
            if toolStr[0].isupper():
                toolClass = globals()[toolStr]
                toolObject = toolClass()            
                self.tools.append(copy.deepcopy(toolObject))
```

### Motivation

When assigning agents a set of tools it's very handy to do it through a list.

### Your contribution

I'm not familiar enough with the architecture of langchain so I'd better not. But I'm happy to test it.

**Comment by happinessbaby** [comment]
having this feature would be a nice addtion
