### ISSUE TITLE
Issue: How to do the recursivley summarization with the summarize_chain?

### ISSUE THREAD

**Issue by nicolasH1027** [langchain-ai/langchain#5785]
### Issue you'd like to raise.

For the code of class`MapReduceDocumentsChain`, there is a comment in `combine_docs` saying that
        
        """Combine documents in a map reduce manner.

        Combine by mapping first chain over all documents, then reducing the results.
        This reducing can be done recursively if needed (if there are many documents).
        """

My questioin is how to build the recursively manner? I didn't see any specific API that allow me to implement it? Do I need to build this functionality by myself? Suppose I have a book-length document to summarize.

**Comment by ShantanuNair** [comment]
This should be doable now thanks to https://github.com/hwchase17/langchain/pull/6994

I cannot get into the details right now, but go through the new implementation of MapReduce and it should be clear
