### ISSUE TITLE
Enable the use of Unstructured loaders with Google drive loader

### ISSUE THREAD

**Issue by MthwRobinson** [langchain-ai/langchain#5791]
### Feature request

The goal of this issue is to enable the use of Unstructured loaders in conjunction with the Google drive loader.

### Motivation

This would enable the use of the GoogleDriveLoader with document types other than the standard Google Drive documents/spreadsheets/presentations.

### Your contribution

I can create a PR for this issue as soon as I have bandwidth. If another community member picks this up first, I'd be happy to review.

**Comment by pprados** [comment]
I've been offering a [pull-request 5135](https://github.com/langchain-ai/langchain/pull/5135) with this functionality for several weeks now.
