### ISSUE TITLE
using MongoDBChatMessageHistory with agent and  RetrievalQA throws value is not a valid dict  error

### ISSUE THREAD

**Issue by ali-faiz-brainx** [langchain-ai/langchain#5834]
### System Info

I want to develop a chatbot that answer questions to user based on the Pinecone vectors. And I want to save the chat history in MongoDB. The history part works well with buffer memory but gives value is not a valid dict error with MongoDB memory.

Here is the Code I'm using

```
def run_openai_llm_chain(vectorstore, query):
  # chat completion llm
  llm = ChatOpenAI()

  conversational_memory = ConversationBufferMemory(
      memory_key='chat_history',
      return_messages=True,
      # output_key="answer"
  )

  mongo_history = MongoDBChatMessageHistory(
        connection_string="mongodb+srv://alifaiz:database@cluster0.eq70b.mongodb.net", 
        session_id="new_session"
  )
  
  qa = RetrievalQA.from_chain_type(
    llm=llm, 
    chain_type='stuff',
    retriever=vectorstore.as_retriever(),
    # memory=mongo_history
  )

  tools = [
      Tool.from_function(
          func=qa.run,
          name="Reader",
          description="useful for when we need to answer question from context"
      )
  ]

  agent = initialize_agent(
      tools,
      llm,
      agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
      verbose=True,
      memory=mongo_history
  )

  answer = agent.run(input=query)

  return answer
 ```

Error:
```
ValidationError: 1 validation error for AgentExecutor
memory
  value is not a valid dict (type=type_error.dict)
```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce the issue:
1. Use MongoDB as a memory in agents.

### Expected behavior

Chat history should be saved in my database.

**Comment by wellCh4n** [comment]
Hi, I have the same problem as you. 
Put mongo_history in the chat_memory parameter of conversational_memory.
```
mongo_history = MongoDBChatMessageHistory(
      connection_string="mongodb+srv://alifaiz:database@cluster0.eq70b.mongodb.net", 
      session_id="new_session"
)
conversational_memory = ConversationBufferMemory(
    chat_memory=mongo_history
    memory_key='chat_history',
    return_messages=True,
    # output_key="answer"
)
```
It worked for me.

**Comment by iiitmahesh** [comment]
How can I store additional fields in a session, such as user ID, to track user conversation history using session IDs?

**Comment by wellCh4n** [comment]
> @wellCh4n How can I store additional fields in a session, such as user ID, to track user conversation history using session IDs?

Hi! @iiitmahesh, A little late in answer, but your requirement is difficult to implement, in my mind.
Cuz save history in db, used `langchain.memory.chat_memory.BaseChatMemory.save_context`, it will add a user_message and ai_message, and we don't have more parameters to control what's inside the `message` object.
```
def add_user_message(self, message: str) -> None:
    self.add_message(HumanMessage(content=message))

def add_ai_message(self, message: str) -> None:
    self.add_message(AIMessage(content=message))
```

So, you need override the method that named `save_context` to a add additional fields.
Keep the discussion going if you have any ideas.

**Comment by ya-smin20** [comment]
@induumez did you find a solution ?
