### ISSUE TITLE
Issue: How to debug langchain speed issues?

### ISSUE THREAD

**Issue by cssndrx** [langchain-ai/langchain#5840]
### Issue you'd like to raise.

I have a simple_qa_with_sources chain - it uses unstructured library for PDF parsing, OpenAI embeddings, and FAISS vector DB. It takes about 10 seconds per query over a short 1 page document. 

I would like to speed this up - but is this performance expected? 

I profiled it and got this flamegraph where the majority of the time seems to be in a SSL socket read triggered by `generate_prompt`. It is mysterious to me why `generate_prompt` would be using the majority of the runtime. 

![no_cache](https://github.com/hwchase17/langchain/assets/1688894/9841433c-9b92-4915-847a-a8fa55f564f3)

### Suggestion:

I would like help understanding why `generate_prompt` takes so long doing SSL reads. I would also appreciate performance optimization documentation on langchain, thanks!

**Comment by hwchase17** [comment]
generate_prompt is a bit of a misnomer - that is the function where a response to the prompt is generated by the LLM. so this is where its actively calling the LLM. so that it is doing SSL reads

How exactly did you construct the chain? what chain type are you using?

**Comment by cssndrx** [comment]
Thanks Harrison, this was `chain = load_qa_with_sources_chain(OpenAI(temperature=0), chain_type="stuff")`
