### ISSUE TITLE
Issue: Retrieval Chain

### ISSUE THREAD

**Issue by mykytamykhailenko** [langchain-ai/langchain#5845]
### Issue you'd like to raise.

Is there a chain, which can only retrieve relevant documents from the vector store?
Or do I need to create a custom one?

**Comment by KeshavSingh29** [comment]
A chain means you are using a LLM (vaguely saying). 
Do you need a LLM for retrieving relevant documents from vector store ? NO 
Then how? 
Assuming you have a vectordb initialized, just call `get_relevant_documents` method if its a retriever. 
```python
        docs = db_retriever.get_relevant_documents(query=query)
```
And you have your docs.

**Comment by mykytamykhailenko** [comment]
@KeshavSingh29 I actually have a use case where I need it, so there's no need to jump to a conclusion so quickly:wink:
Basically, I have got an index containing summaries, but I don't want to do question-answering on it, I just want to get relevant documents. Besides, I have a long chain and I need that piece, which does the retrieval, right in the middle of the chain. `RetrievalQA` won't do because it immediately answers the question while I don't need it, I only need relevant documents.

**Comment by KeshavSingh29** [comment]
@mykytamykhailenko Aaah I see. 
True that, I jumped to conclusion quickly assuming what you asked was the only use case. 
In that case, you can try to parse the LLM chain prompt to get the relevant documents.
