### ISSUE TITLE
Issue: How to do token streaming for other LLMs on Streamlit or Gradio 

### ISSUE THREAD

**Issue by eshaanagarwal** [langchain-ai/langchain#5851]
### Issue you'd like to raise.

Hi i was trying to create a chatbot using LLM and langchain. It would be great if you could point me to any function or method or way to implement token streaming for my chatbot.

I am developing the UI using Streamlit but I can change to gradio too. Is there any specific way to do that? Please tell me.

I need to do it urgently so I would appreciate anybody help.

**Comment by LoveFishoO** [comment]
Maybe you can rewrite StreamingStdOutCallbackHandler class
```python
import time
import streamlit as st
from typing import Any, List, Dict
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
class MyStream(StreamingStdOutCallbackHandler):
    
    def __init__(self) -> None:
        super().__init__()
        self.o = st.empty()
        self.s = ''
    
    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> None:
        """Run when LLM starts running."""
        del self.o
        self.s = ''
        self.o = st.empty()
        
    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Run on new LLM token. Only available when streaming is enabled."""
        self.s += token
        self.o.info(self.s)
        time.sleep(0.05)

```
And then use custom class in the callbacks args
```python
LLM = ChatOpenAI(
        temperature = 0,
        streaming=True, 
        callbacks=[MyStream()], 
        )
```

Hope this demo could give your some inspiration.

**Comment by samthedataman** [comment]
this solution worked perfectly you are a god! 

[LoveFishoO](https://github.com/LoveFishoO)

**Comment by Saigenix** [comment]
> Maybe you can rewrite StreamingStdOutCallbackHandler class
> 
> ```python
> import time
> import streamlit as st
> from typing import Any, List, Dict
> from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
> class MyStream(StreamingStdOutCallbackHandler):
>     
>     def __init__(self) -> None:
>         super().__init__()
>         self.o = st.empty()
>         self.s = ''
>     
>     def on_llm_start(
>         self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
>     ) -> None:
>         """Run when LLM starts running."""
>         del self.o
>         self.s = ''
>         self.o = st.empty()
>         
>     def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
>         """Run on new LLM token. Only available when streaming is enabled."""
>         self.s += token
>         self.o.info(self.s)
>         time.sleep(0.05)
> ```
> 
> And then use custom class in the callbacks args
> 
> ```python
> LLM = ChatOpenAI(
>         temperature = 0,
>         streaming=True, 
>         callbacks=[MyStream()], 
>         )
> ```
> 
> Hope this demo could give your some inspiration.

this does not work with gradio chatInterface, Is there any generator function that langchain provides for streaming
