### ISSUE TITLE
Improve python repl tool

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#586]
It would be convenient if perhaps the PythonREPL returned the last output of the REPL if there's no stdout

Also, improve the tool description to note that All Python outputs must use print().

**Comment by xanderdunn** [comment]
Another nice feature here would be a timeout on the Python REPL responses. It's possible for the LLM to give the REPL input that never halts. For example, calling `input()`

**Comment by jon-chuang** [comment]
> Another nice feature here would be a timeout on the Python REPL responses. It's possible for the LLM to give the REPL input that never halts. For example, calling input()

Let's make the timeout relatively high (10s), and make the timeout configurable.

**Comment by willsmithorg** [comment]
> Another nice feature here would be a timeout on the Python REPL responses. It's possible for the LLM to give the REPL input that never halts. For example, calling `input()`

Or generating an infinite loop that never exits.
