### ISSUE TITLE
Issue: The 'chain' field of ConstitutionalChain is limited to 'LLM'

### ISSUE THREAD

**Issue by MeowLake** [langchain-ai/langchain#5881]
### Issue you'd like to raise.

Failed to pass in an `AgentExecutor` as `chain` field in a `ConsitutionalChain` like this:

```python
constitutional_chain = ConsitutionalChain.from_llm(chain = intialize_agent(<some inputs>), <other inputs>)
```

Digging into the source code, I noticed that `AgentExecutor` is a `Chain` type, but the parameter `chain` requires `LLMChain`, which is also a child of `Chain`. 

Any suggestions for this situation?

**Comment by wnmurphy** [comment]
Similar issue. Would like to pass output from several `MultiRouterChain` destination chains through a `ConstitutionalChain`, but `MultiRouterChain.destination_chains` must be `List[LLMChain]`, and `ConstitutionalChain` takes a single `chain` that must be an `LLMChain`.

Would be ideal to:
* Make `MultiRouterChain` support destination chains that can be `SimpleSequentialChain` or `SequentialChain`
* Allow `ConstitutionalChain` to be tacked on to the end of either of the sequential chains.
