### ISSUE TITLE
Issue: ConversationalRetrievalChain - issue with passing the CONDENSE_QUESTION_PROMPT for working chat history

### ISSUE THREAD

**Issue by zigax1** [langchain-ai/langchain#5890]
### Issue you'd like to raise.

Hello everyone! I can't successfully pass the CONDENSE_QUESTION_PROMPT to `ConversationalRetrievalChain`, while basic QA_PROMPT I can pass.
I also need the CONDENSE_QUESTION_PROMPT because there I will pass the chat history, since I want to achieve a converstional chat over documents with working chat history, and later possibly some summary memories to prevent halucinations.

I am using LangChain v0.0.191 with Chrom vectorstore v0.0.25

What I want to achieve is that the model will know about chat history.

My code looks like that for now:

```
self.llm = ChatOpenAI(model_name=self.model_name, temperature=self.temperature, openai_api_key=settings.OPENAI_API_KEY,
                                  streaming=True, verbose=True, callback_manager=CallbackManager([ChainStreamHandler(generator)]))
            self.memory = ConversationBufferMemory(
                memory_key="chat_history", return_messages=True,  output_key='answer')

QA_PROMPT = PromptTemplate(input_variables=["context", "question"], template=QA_PROMP_ALL_KNOWLEDGE)

                retriever = chroma_Vectorstore.as_retriever(qa_template=QA_PROMP_ALL_KNOWLEDGE
                            ,search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.2}
                                                            )

                self.chain = ConversationalRetrievalChain.from_llm(self.llm, retriever=retriever,
                                                                    return_source_documents=True,verbose=True, 
                                                                    memory=self.memory,
                                                                    combine_docs_chain_kwargs={'prompt': QA_PROMPT})
                
                result = self.chain({"question": question})
                res_dict = {
                    "answer": result["answer"],
                }
                res_dict["source_documents"] = []

                for source in result["source_documents"]:
                    res_dict["source_documents"].append({
                        "page_content": source.page_content,
                        "metadata":  source.metadata
                    })
               
                return res_dict
```
But where can I than pass the CONDENSE_QUESTION_PROMPT?
` CONDENSEprompt = PromptTemplate(input_variables=["chat_history", "question"], template=CONDENSE_QUESTION_PROMPT)`

My exact CONDENSE_QUESTION_PROMPT is:

```
CONDENSE_PROMPT = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:"""
```

and 

My exact QA_PROMPT_DOCUMENT_CHAT is
```
QA_PROMPT_DOCUMENT_CHAT = """You are a helpful AI assistant. Use the following pieces of context to answer the question at the end.
If the question is not related to the context, politely respond that you are teached to only answer questions that are related to the context.
If you don't know the answer, just say you don't know. DO NOT try to make up an answer. Try to make the title for every answer if it is possible. Answer in markdown.
Use as much detail as possible when responding and try to make answer in markdown format as much as possible.

{context}

Question: {question}
Answer in markdown format:"""
```
 

With my current code, the history doesn't work.

### Suggestion:

Maybe @hwchase17 or @agola11 can help. Thanks

**Comment by talhaanwarch** [comment]
try this
```
qa = ConversationalRetrievalChain.from_llm(
                                        ChatOpenAI(model_name='gpt-3.5-turbo',temperature=0),
                                        retriever=..., 
                                        memory=...,
                                        verbose=...,
                                        condense_question_prompt = CONDENSEprompt,
                                        get_chat_history=...,
                                        combine_docs_chain_kwargs={"prompt": ....})
                                        ```

**Comment by zigax1** [comment]
> try this
> 
> ```
> qa = ConversationalRetrievalChain.from_llm(
>                                         ChatOpenAI(model_name='gpt-3.5-turbo',temperature=0),
>                                         retriever=..., 
>                                         memory=...,
>                                         verbose=...,
>                                         condense_question_prompt = CONDENSEprompt,
>                                         get_chat_history=...,
>                                         combine_docs_chain_kwargs={"prompt": ....})
>                                         ```
> ```

Thanks! Works

**Comment by shubhgithubrit** [comment]
I have a query like if I ask some question it will give me a answer but again if my question is like " Give me the above answer in a paragraph format " then it did not recognize it and in a prompt after formatting it will make some different question so how to handle it
