### ISSUE TITLE
Issue: TokenTextSplitter processes passages less than chunk_size and creates duplicate overlaps

### ISSUE THREAD

**Issue by c3-YuelingWu** [langchain-ai/langchain#5897]
### Issue you'd like to raise.

**Observation:** TokenTextSplitter processes passages smaller than specified chunk_size, and creates a lot more smaller chunks with duplicated overlaps.

**Impact:** The smaller chunks with duplicated overlaps may be harmful to storage size, computation time, and it may confuse the retrieval model.

**For example:** The second TokenTextSplitter creates 366 more small chunks, even if new_chunks1 doesn't have any passages longer than chunk_size=500.
<img width="950" alt="Screen Shot 2023-06-08 at 10 58 52 AM" src="https://github.com/hwchase17/langchain/assets/103061109/d05c28a9-b6dc-4e44-ad00-c892457055d8">

### Suggestion:

In source code for langchain.text_splitter, split_text_on_tokens function, can we add the check for

`If len(input_ids) <= tokenizer.tokens_per_chunk:  splits.append(tokenizer.decode(input_ids)) `

**Comment by AntiMoron** [comment]
`TokenTextSplitter` in nodejs also takes up too much CPU usage.

**Comment by prasadpilla** [comment]
I am waiting for this too. This chunk sizes are not predictable

**Comment by MuhammadSaqib001** [comment]
Yes , I faced the same issue @c3-YuelingWu  . The ways this token text splitter works , isn't how it is intended to work . 

**For Example :-**
   When specified chunk_size = 1024 and overlap = 256  with input text tokens = 991 , it made two chunks ; 
                 first = token[0 : 991]
                 second = token[768 : 991]

but logically it should work this ways .
1. If input text token >1024 , there should be two chunks .
                 first = token[0 : 1024]
                 second = token[768 : ]
                 and so on ..............

2. If input text token <=1024 , there should be one chunk only .
                  first = token[ 0 : ]
