### ISSUE TITLE
Issue: <RetrievalQA.from_chain_type with custom prompt template>

### ISSUE THREAD

**Issue by MachineLearning4Work** [langchain-ai/langchain#5899]
### Issue you'd like to raise.

Hello everyone! I'm having trouble setting up the successful usage of a custom QA prompt template that includes input variables with my RetrievalQA.from_chain_type.

This issue  is similar to https://github.com/hwchase17/langchain/pull/3425

I am using LangChain v0.0.192 with FAISS vectorstore.  

As below my custom prompt has three input 

**My_loader_
made_corrections_
output_format_instructions_**

My code looks like that for now:

pdf_template_stuff = """
You are a Contract Review Specialist. You have been given a dataloader as 
langchain.document_loaders.directory.DirectoryLoader: {my_loader_}.
Use the following pieces of context to answer the question at the end.
If you don't know the answer, just say that you don't know, don't try to make up an answer.
Use as much detail as possible when responding and try to make answer in markdown format as much as possible.
Based on this data do the following:
1-    Read the input PDFs and extract the relevant information.
2-    Answer the question using the extracted information.
3-    Cross-reference the answer with other PDF files to ensure accuracy.
4-    Based on the historic corrections: {made_corrections_} make corrections to the extracted answers
5-    provide the answer in alignment with the {output_format_instructions_} format.

Context: {context}
Question:{question}

Helpful Answer:
"""

pdf_prompt_template = PromptTemplate( input_variables=
["context","question","my_loader_", "made_corrections_","output_format_instructions_"],
    template=pdf_template_stuff
)

my_chain_type='stuff'

my_qa_chain = RetrievalQA.from_chain_type(llm=my_specific_llm, 
                                  chain_type=my_chain_type, 
                                  retriever=my_retriever, 
                                  return_source_documents=False,
                                  chain_type_kwargs={"prompt": pdf_prompt_template}
                                                                                  
                                         )

final_result=my_qa_chain(query="MY SAMPLE QUESTION",my_loader_=my_loader, made_corrections_=made_corrections , Output_format_instructions_=output_format_instructions)

ValueError: Missing some input keys: {'output_format_instructions_', 'my_loader_', 'made_corrections_'}

Thanks for your help

**Comment by MachineLearning4Work** [comment]
@hwchase17  your comments are helpful here- Thanks

**Comment by danqroz** [comment]
Did you manage that? i'm with the same problem, i think retrievalQA doesn't support others variables in prompt. The docs says:

`qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="map_reduce", retriever=docsearch.as_retriever())`
"The above way allows you to really simply change the chain_type, but it doesn't provide a ton of flexibility over parameters to that chain type. If you want to control those parameters, you can load the chain directly (as you did in [this notebook](https://python.langchain.com/docs/modules/chains/additional/question_answering.html)) and then pass that directly to the the RetrievalQA chain with the combine_documents_chain parameter."


unfortunately, the link don't work anymore.
