### ISSUE TITLE
PubmedQueryRun not working

### ISSUE THREAD

**Issue by IyadSultan** [langchain-ai/langchain#5906]
### System Info

langchain               0.0.194
langchainplus-sdk       0.0.6

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. code from langchain.tools import PubmedQueryRun
2. Error:

ImportError: cannot import name 'PubmedQueryRun' from 'langchain.tools' (C:\Users\USER\anaconda3\lib\site-packages\langchain\tools\__init__.py)
Traceback:
File "C:\Users\USER\anaconda3\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\USER\Dropbox\AI\Cloned Repis\Langchain-Crash-Course\pubmed.py", line 31, in <module>
    from langchain.tools import PubmedQueryRun

### Expected behavior

It seems PubmedQueryRun is not defined.

**Comment by ChaseRichardsonGit** [comment]
It appears there was a typo when creating the tool. What worked for me was calling "pupmed".

@hwchase17

**Comment by urbanscribe** [comment]
yeah here it is 

def _get_pupmed(**kwargs: Any) -> BaseTool:
    return PubmedQueryRun(api_wrapper=PubMedAPIWrapper(**kwargs))

in 

[langchain](https://github.com/langchain-ai/langchain/tree/8a8917e0d97b3853796a23fb867faea38ffc6e46)/[libs](https://github.com/langchain-ai/langchain/tree/8a8917e0d97b3853796a23fb867faea38ffc6e46/libs)/[langchain](https://github.com/langchain-ai/langchain/tree/8a8917e0d97b3853796a23fb867faea38ffc6e46/libs/langchain)/[langchain](https://github.com/langchain-ai/langchain/tree/8a8917e0d97b3853796a23fb867faea38ffc6e46/libs/langchain/langchain)/[agents](https://github.com/langchain-ai/langchain/tree/8a8917e0d97b3853796a23fb867faea38ffc6e46/libs/langchain/langchain/agents)
/load_tools.py
