### ISSUE TITLE
chroma.from_documents AuthenticationError

### ISSUE THREAD

**Issue by Peereasil** [langchain-ai/langchain#5910]
### System Info

In Google Collab

What I have installed
%pip install requests==2.27.1
%pip install chromadb==<compatible version>
%pip install langchain duckdb unstructured chromadb openai tiktoken

MacBook M1

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. from langchain.embeddings import OpenAIEmbeddings
embeddings = OpenAIEmbeddings() << PASS

create a vector database and use it to index the embeddings
2. class Document:
    def __init__(self, text, metadata):
        self.page_content = text
        self.metadata = metadata << PASS

3.documents = [Document(text, metadata) for text, metadata in zip(texts, metadata_list)] << PASS

4.from langchain.vectorstores import Chroma

db = Chroma.from_documents(documents, embeddings, model='davinci') << AuthenticationError: <empty message>

---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
[<ipython-input-87-ea7b035908f9>](https://rzac4prlyba-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in <cell line: 3>()
      1 from langchain.vectorstores import Chroma
      2 
----> 3 db = Chroma.from_documents(documents, embeddings, model='davinci')

17 frames
[/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py](https://rzac4prlyba-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230606-060135-RC00_538140384#) in _interpret_response_line(self, rbody, rcode, rheaders, stream)
    761         stream_error = stream and "error" in resp.data
    762         if stream_error or not 200 <= rcode < 300:
--> 763             raise self.handle_error_response(
    764                 rbody, rcode, resp.data, rheaders, stream_error=stream_error
    765             )

AuthenticationError: <empty message>

What should I do?

FYI. I try to follow this link https://medium.com/mlearning-ai/using-chatgpt-for-question-answering-on-your-own-data-afa33d82fbd0
seems like he has no issue TT

### Expected behavior

pass

**Comment by Peereasil** [comment]
I also connect API successfully

**Comment by talhaanwarch** [comment]
@Peereasil if still not solved, let me know, i will help

**Comment by aravish-github** [comment]
Following the demo
https://learn.deeplearning.ai/langchain/lesson/2/models,-prompts-and-parsers
customer_response = chat(customer_messages)

returns AuthenticationError: <empty message>


AuthenticationError                       Traceback (most recent call last)
File <command-4297698795014435>:1
----> 1 customer_response = chat(customer_messages)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/base.py:194, in BaseChatModel.__call__(self, messages, stop, callbacks)
    188 def __call__(
    189     self,
    190     messages: List[BaseMessage],
    191     stop: Optional[List[str]] = None,
    192     callbacks: Callbacks = None,
    193 ) -> BaseMessage:
--> 194     generation = self.generate(
    195         [messages], stop=stop, callbacks=callbacks
    196     ).generations[0][0]
    197     if isinstance(generation, ChatGeneration):
    198         return generation.message

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/base.py:95, in BaseChatModel.generate(self, messages, stop, callbacks, **kwargs)
     93 except (KeyboardInterrupt, Exception) as e:
     94     run_manager.on_llm_error(e)
---> 95     raise e
     96 llm_output = self._combine_llm_outputs([res.llm_output for res in results])
     97 generations = [res.generations for res in results]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/base.py:87, in BaseChatModel.generate(self, messages, stop, callbacks, **kwargs)
     83 new_arg_supported = inspect.signature(self._generate).parameters.get(
     84     "run_manager"
     85 )
     86 try:
---> 87     results = [
     88         self._generate(m, stop=stop, run_manager=run_manager, **kwargs)
     89         if new_arg_supported
     90         else self._generate(m, stop=stop)
     91         for m in messages
     92     ]
     93 except (KeyboardInterrupt, Exception) as e:
     94     run_manager.on_llm_error(e)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/base.py:88, in <listcomp>(.0)
     83 new_arg_supported = inspect.signature(self._generate).parameters.get(
     84     "run_manager"
     85 )
     86 try:
     87     results = [
---> 88         self._generate(m, stop=stop, run_manager=run_manager, **kwargs)
     89         if new_arg_supported
     90         else self._generate(m, stop=stop)
     91         for m in messages
     92     ]
     93 except (KeyboardInterrupt, Exception) as e:
     94     run_manager.on_llm_error(e)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/openai.py:329, in ChatOpenAI._generate(self, messages, stop, run_manager, **kwargs)
    325     message = _convert_dict_to_message(
    326         {"content": inner_completion, "role": role}
    327     )
    328     return ChatResult(generations=[ChatGeneration(message=message)])
--> 329 response = self.completion_with_retry(messages=message_dicts, **params)
    330 return self._create_chat_result(response)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/openai.py:288, in ChatOpenAI.completion_with_retry(self, **kwargs)
    284 @retry_decorator
    285 def _completion_with_retry(**kwargs: Any) -> Any:
    286     return self.client.create(**kwargs)
--> 288 return _completion_with_retry(**kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/tenacity/__init__.py:289, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    287 @functools.wraps(f)
    288 def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289     return self(f, *args, **kw)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/tenacity/__init__.py:379, in Retrying.__call__(self, fn, *args, **kwargs)
    377 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378 while True:
--> 379     do = self.iter(retry_state=retry_state)
    380     if isinstance(do, DoAttempt):
    381         try:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/tenacity/__init__.py:314, in BaseRetrying.iter(self, retry_state)
    312 is_explicit_retry = fut.failed and isinstance(fut.exception(), TryAgain)
    313 if not (is_explicit_retry or self.retry(retry_state)):
--> 314     return fut.result()
    316 if self.after is not None:
    317     self.after(retry_state)

File /usr/lib/python3.9/concurrent/futures/_base.py:438, in Future.result(self, timeout)
    436     raise CancelledError()
    437 elif self._state == FINISHED:
--> 438     return self.__get_result()
    440 self._condition.wait(timeout)
    442 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /usr/lib/python3.9/concurrent/futures/_base.py:390, in Future.__get_result(self)
    388 if self._exception:
    389     try:
--> 390         raise self._exception
    391     finally:
    392         # Break a reference cycle with the exception in self._exception
    393         self = None

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/tenacity/__init__.py:382, in Retrying.__call__(self, fn, *args, **kwargs)
    380 if isinstance(do, DoAttempt):
    381     try:
--> 382         result = fn(*args, **kwargs)
    383     except BaseException:  # noqa: B902
    384         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/langchain/chat_models/openai.py:286, in ChatOpenAI.completion_with_retry.<locals>._completion_with_retry(**kwargs)
    284 @retry_decorator
    285 def _completion_with_retry(**kwargs: Any) -> Any:
--> 286     return self.client.create(**kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/openai/api_resources/chat_completion.py:25, in ChatCompletion.create(cls, *args, **kwargs)
     23 while True:
     24     try:
---> 25         return super().create(*args, **kwargs)
     26     except TryAgain as e:
     27         if timeout is not None and time.time() > start + timeout:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py:153, in EngineAPIResource.create(cls, api_key, api_base, api_type, request_id, api_version, organization, **params)
    127 @classmethod
    128 def create(
    129     cls,
   (...)
    136     **params,
    137 ):
    138     (
    139         deployment_id,
    140         engine,
   (...)
    150         api_key, api_base, api_type, api_version, organization, **params
    151     )
--> 153     response, _, api_key = requestor.request(
    154         "post",
    155         url,
    156         params=params,
    157         headers=headers,
    158         stream=stream,
    159         request_id=request_id,
    160         request_timeout=request_timeout,
    161     )
    163     if stream:
    164         # must be an iterator
    165         assert not isinstance(response, OpenAIResponse)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/openai/api_requestor.py:298, in APIRequestor.request(self, method, url, params, headers, files, stream, request_id, request_timeout)
    277 def request(
    278     self,
    279     method,
   (...)
    286     request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    287 ) -> Tuple[Union[OpenAIResponse, Iterator[OpenAIResponse]], bool, str]:
    288     result = self.request_raw(
    289         method.lower(),
    290         url,
   (...)
    296         request_timeout=request_timeout,
    297     )
--> 298     resp, got_stream = self._interpret_response(result, stream)
    299     return resp, got_stream, self.api_key

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/openai/api_requestor.py:700, in APIRequestor._interpret_response(self, result, stream)
    692     return (
    693         self._interpret_response_line(
    694             line, result.status_code, result.headers, stream=True
    695         )
    696         for line in parse_stream(result.iter_lines())
    697     ), True
    698 else:
    699     return (
--> 700         self._interpret_response_line(
    701             result.content.decode("utf-8"),
    702             result.status_code,
    703             result.headers,
    704             stream=False,
    705         ),
    706         False,
    707     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aa9856cc-f479-4c24-bf5c-39ed99999621/lib/python3.9/site-packages/openai/api_requestor.py:763, in APIRequestor._interpret_response_line(self, rbody, rcode, rheaders, stream)
    761 stream_error = stream and "error" in resp.data
    762 if stream_error or not 200 <= rcode < 300:
--> 763     raise self.handle_error_response(
    764         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    765     )
    766 return resp

AuthenticationError: <empty message>
