### ISSUE TITLE
Gorilla examples

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#5941]
### Feature request

Hi, I'd love to request examples/documentation for how to use [Gorilla](https://github.com/ShishirPatil/gorilla#faqs) with LangChain.

### Motivation

This looks like a great model to serve correct API calls.

### Your contribution

🤷🏻‍♂️

**Comment by sonal994** [comment]
Hi @austinmw , Did you got any clue?

**Comment by scenaristeur** [comment]
could be a starting point https://github.com/scenaristeur/Gorilla-LLM-Demo-App/blob/main/app.py

**Comment by nyck33** [comment]
@scenaristeur why are you getting Gorilla to output Python code?  Am I reading that correctly?  @austinmw seems to want to use it to generate api calls which is what Gorilla is good at.  I would like to see an example more along the lines of https://python.langchain.com/docs/use_cases/apis and asking Gorilla something like "How do I order xyz from abc food service in Seattle, WA?"
