### ISSUE TITLE
Not able to set k top documents in Chroma DB based Retriever

### ISSUE THREAD

**Issue by eshaanagarwal** [langchain-ai/langchain#5944]
### System Info

I7 32 GBRAM , ASUS dynabook protege 

### Who can help?

@hwchase17 @agola11 @vow

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
db = Chroma.from_texts(chunks, embeddings, persist_directory='db', client_settings=CHROMA_SETTINGS)
chat_llm = ChatOpenAI(model_name = 'gpt-3.5-turbo',
                          callbacks=callbacks, 
                          verbose=True, 
                          temperature=0,
                          streaming = True
                         )
    
    question_generator = LLMChain(llm=chat_llm, prompt=CONDENSE_QUESTION_PROMPT)
    prompt = load_prompt(model_name='gpt')
    doc_chain = load_qa_chain(llm=chat_llm,chain_type="stuff",prompt=prompt) 
    chain = ConversationalRetrievalChain(retriever=vectorstore.as_retriever(search_kwargs={"k": 2}), 
                                     question_generator=question_generator, 
                                     combine_docs_chain=doc_chain, 
                                     memory=memory, 
                                     return_source_documents=True, 
                                     get_chat_history=lambda h :h)
```

### Expected behavior

I wish to change the `search_kwargs` more specifically `top k` relevant documents which are retrieved but I am not able to change it ! it is repeatedly providing the default 4 documents. I have tried all the required method. 

I am using Chroma DB as retriever on bunch of pdfs.

**Comment by aronweiler** [comment]
`vectorstore.as_retriever(search_kwargs={"k": 6})` works for me.  Not sure if this was updated recently or not, but I was running into the same issues, but turns out I was passing `top_k` as the name instead of just `k`.
