### ISSUE TITLE
Add Proxy to GoogleSearchAPIWrapper

### ISSUE THREAD

**Issue by timxieICN** [langchain-ai/langchain#5964]
### Feature request

Need to add proxy to GoogleSearchAPIWrapper()

Perhaps using this [approach](https://github.com/googleapis/google-api-python-client/issues/1078#issuecomment-718919158) and/or this [approach](https://github.com/googleapis/google-api-python-client/issues/1260#issuecomment-802728649)?

```
import httplib2
import google_auth_httplib2

http = httplib2.Http(proxy_info=httplib2.ProxyInfo(
            httplib2.socks.PROXY_TYPE_HTTP, PROXY_IP, PROXY_PORT
))

authorized_http = google_auth_httplib2.AuthorizedHttp(credentials, http=http)

service = discovery.build(http=authorized_http)
```

### Motivation

Add Proxy to GoogleSearchAPIWrapper

### Your contribution

I can write a PR but perhaps with some additional help

**Comment by hahazei** [comment]
You can use a global proxy like this:
`import os

# GLOBAL HTTP PROXY
os.environ['HTTP_PROXY'] = 'http://your_proxy_server:your_proxy_port'
os.environ['HTTPS_PROXY'] = 'http://your_proxy_server:your_proxy_port'`

**Comment by hahazei** [comment]
You can use a global proxy like this:
```python
import os

#GLOBAL HTTP PROXY
os.environ['HTTP_PROXY'] = 'http://your_proxy_server:your_proxy_port'
os.environ['HTTPS_PROXY'] = 'http://your_proxy_server:your_proxy_port'
