### ISSUE TITLE
SQLiteCache does not cache logprobs

### ISSUE THREAD

**Issue by aabdullah-getguru** [langchain-ai/langchain#5965]
### System Info

Langchain version: 0.0.192, Python: 3.10

```
from langchain.cache import SQLiteCache
langchain.llm_cache = SQLiteCache(database_path='.langchain.db')
from langchain.llms import OpenAI

my_llm = OpenAI(model_name='text-davinci-003', temperature=0, max_tokens=1, logprobs=5)
result=my_llm.generate(['2+2='])
result.generations[0][0]
```

In the above, the logprobs will only be generated the first time and never again. Interestingly, the InMemoryCache does successfully persist the logprobs (and other generation_info) upon a cache hit.

@hwchase17 @yuert

### Who can help?

Any contributor.

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.cache import SQLiteCache
langchain.llm_cache = SQLiteCache(database_path='.langchain.db')
from langchain.llms import OpenAI

my_llm = OpenAI(model_name='text-davinci-003', temperature=0, max_tokens=1, logprobs=5)
result=my_llm.generate(['2+2='])
result.generations[0][0]
```

### Expected behavior

I expect the following output every time I run this

```
Generation(text='4', generation_info={'finish_reason': 'length', 'logprobs': <OpenAIObject at 0x7fbcb6ab1710> JSON: {
  "tokens": [
    "4"
  ],
  "token_logprobs": [
    -0.5794853
  ],
  "top_logprobs": [
    {
      "4": -0.5794853,
      "\n": -1.6557268,
      "5": -2.264629,
      "?": -3.518741,
      "3": -4.042759
    }
  ],
  "text_offset": [
    4
  ]
}})
```

But instead (upon the second or more times I run this), I get this:
Generation(text='4', generation_info=None)

**Comment by liaojianqi** [comment]
I think it's caused by different implementation in InMemoryCache and SQLiteCache,
in [InMemoryCache](https://github.com/hwchase17/langchain/blob/master/langchain/cache.py#LL110C6-L110C6):
`self._cache[(prompt, llm_string)] = return_val`
we cached the whole return value,
while in the [SQLiteCache](https://github.com/hwchase17/langchain/blob/master/langchain/cache.py#LL156C87-L156C87),
we only cached return.text.
I was wondering is this difference by design or just a typo? @hwchase17
