### ISSUE TITLE
Issue: Is there some detail documents about chroma.from_documents args?

### ISSUE THREAD

**Issue by sunlongjian** [langchain-ai/langchain#5973]
### Issue you'd like to raise.

I was trying to store different vectorstore to chroma with different ids like "vectorstore = Chroma.from_documents(documents, embeddings, ids="test1",)", but it keeps telling Number of embeddings 9 must match number of ids 1
and how i can erase some of vectorstore inside chroma, if i can store many into it?

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

Hello! I'm sorry to hear that you're having trouble finding detailed documentation about the chroma.from_documents arguments. I tried searching for more information on this, but unfortunately, I wasn't able to find any specific documentation that addresses your question.

Regarding your issue with storing different vector stores with different IDs, it seems like the error message you're receiving is indicating that the number of embeddings you're passing in doesn't match the number of IDs you're providing. Can you confirm that you're passing in the same number of embeddings as IDs?

To use the `Chroma.from_documents` method with multiple ids, you can pass a list of `Document` objects and a list of corresponding ids as arguments. Here's an example:

```python
documents = [doc1, doc2, doc3]
ids = ['id1', 'id2', 'id3']

chroma_instance = Chroma.from_documents(
    documents=documents,
    ids=ids,
    embedding=my_embedding,
    collection_name="my_collection"
)
```

However, the provided context does not include information on how to remove specific vector stores from Chroma in LangChain.

### Sources

- [langchain/vectorstores/chroma.py](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/chroma.py)

---

This response is meant to be useful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by sunlongjian** [comment]
What I trying to do is storing different documents into different chromadb. I'm using persist_directory to separate  different chromadb, I was thinking maybe there's a better way.
