### ISSUE TITLE
pydantic.error_wrappers.ValidationError for args_schema

### ISSUE THREAD

**Issue by louria** [langchain-ai/langchain#5974]
### System Info

Latest langchain & openai 0.27.5

https://python.langchain.com/en/latest/modules/agents/tools/custom_tools.html

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

 https://python.langchain.com/en/latest/modules/agents/tools/custom_tools.html

class CalculatorInput(BaseModel):
    question:str = Field()

tools.append(
    Tool.from_function(
        func=llm_math_chain.run,
        name="Calculator",
        description="useful for when you need to answer questions about math",
        args_schema=CalculatorInput
        # coroutine= ... <- you can specify an async method if desired as well
    )

Got this error msg: 

File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Tool
args_schema extra fields not permitted (type=value_error.extra)

### Expected behavior

Should enter Agent excution

**Comment by try-agaaain** [comment]
I had the same problem.

**Comment by albarsil** [comment]
Same problem here

**Comment by DulsaraDhanuka** [comment]
I think there is some change in the pydantic code base

`from pydantic.v1 import BaseModel, Field` 

Check this for more information #9441
