### ISSUE TITLE
STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION with gpt-4 doesn't follow through the tasks, while gpt-3.5-turbo does.

### ISSUE THREAD

**Issue by parisetflorian** [langchain-ai/langchain#5978]
### System Info

langchain 0.0.195

### Who can help?

@vowelparrot
@hwchase17

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
SendEmail = StructuredTool.from_function(sendEmail)
    UpdateClientProfile = StructuredTool.from_function(updateClientProfile)
    tools = [SendEmail, UpdateClientProfile]

    #llm=ChatOpenAI(openai_api_key=os.environ['OPENAI_API_KEY_GPT4'], model=pd.steps["code"]["$return_value"]["model"], temperature=0.8)
    llm=ChatOpenAI(openai_api_key=os.environ['OPENAI_API_KEY_GPT4'], model="gpt-4", temperature=0.8)

    prompt = pd.steps["code"]["$return_value"]["prompt"]

    gpt3 = initialize_agent(tools, llm, agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
    res = gpt3.run(prompt)


    gpt4 = initialize_agent(tools, llm, agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)
    res = gpt4.run(prompt)
```

Here's the prompt:
<img width="714" alt="prompt" src="https://github.com/hwchase17/langchain/assets/7931903/2d15bbdf-a81d-4742-beae-0664acce53bc">

gpt-3.5-turbo correctly handle the tasks:
<img width="884" alt="gpt3 5" src="https://github.com/hwchase17/langchain/assets/7931903/0599f839-4a2e-44b5-9978-df758ea8e69c">

gpt-4 only do the first one:
<img width="880" alt="gpt4" src="https://github.com/hwchase17/langchain/assets/7931903/1f6017a4-a31c-48b6-b06b-0bf6214cddf5">

### Expected behavior

Both agents should complete two tasks :
1 - Send an email
2 - Update the customer profile

gpt-3.5-turbo correctly completes the tasks, while gpt-4 stops after the first one and outputs what it should do next:
"Now I will update the customer profile..."

**Comment by okradze** [comment]
I have the same issue. It finishes chain after first action.

**Comment by Leo777** [comment]
Same for me. Also noticed that model can remember previous steps and trying to execute it even when it was't asked about it.
