### ISSUE TITLE
Get number of vectors in Vector Store

### ISSUE THREAD

**Issue by taimurshaikh** [langchain-ai/langchain#5980]
### Feature request

What the title says. A method in the `VectorStore` class that allows the size of the store to be retrieved.

### Motivation

This could be useful for certain applications of continuous storage.

### Your contribution

Happy to contribute with some guidance.

**Comment by mirodrr** [comment]
Would also like this

**Comment by rhubarb** [comment]
Seems obvious - subscribing in the hope this gets resolved.

**Comment by LinasKo** [comment]
Working with `QDrant Cloud`, it has an `ensureCollection` function that checks if the collection exists. However, that's very much insufficient - it passes happily with completely empty collections. Having a `count()` function would save a great deal of time.

**Comment by YannDubs** [comment]
I think it's still relevant, would be great to have

**Comment by chandradharrao** [comment]
Hi. I would like to work on this. Once I add this property to the vectorstore class, should i then implement this in all the vectorstores like nucliadb, chromadb etc?
