### ISSUE TITLE
UnstructuredUrlLoader or SeleniumUrlLoader are not able to upload the pdf's consisting by urls.

### ISSUE THREAD

**Issue by ragvendra3898** [langchain-ai/langchain#6000]
### System Info

Hi,

I am using UnstructureUrlLoader to upload the urls into Chroma vector database but it is only uploading the html content of the url, not uploading the pdfs available on this url that's why it is not giving the answer for query related to pdf files while performing querying using RetrievalQA chain
I also tried with SeleniumUrlLoader but still no results.

from langchain.vectorstores import Chroma                                
from langchain.embeddings import OpenAIEmbeddings                            
from langchain.text_splitter import RecursiveCharacterTextSplitter , TokenTextSplitter      
from langchain.llms import OpenAI                                           
from langchain.chat_models import ChatOpenAI                                  
from langchain.chains import VectorDBQA, RetrievalQA                                      
from langchain.document_loaders import TextLoader, UnstructuredFileLoader, DirectoryLoader,UnstructuredURLLoader,SeleniumURLLoader  
from langchain.indexes import VectorstoreIndexCreator
from langchain.prompts import PromptTemplate
import chromadb
import wx
import os
import requests
from bs4 import BeautifulSoup

openai_api_key = my_openai_key
persist_directory = "Zdb_directory"
collection_name = 'my collection'
temperature = 0
max_tokens = 200
llm=ChatOpenAI(openai_api_key=openai_api_key)

urls = ['url1,'url2','url3']
#loader = UnstructuredURLLoader(urls)
loader = SeleniumURLLoader(urls)

text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
vectordb = Chroma.from_documents(texts, embedding=embeddings, persist_directory=persist_directory)
vectordb.persist()
vectordb = None

vectodb = Chroma(persist_directory=persist_directory, embedding_function=embeddings, collection_name='my_collection)
qa = RetrievalQA.from_chain_type(llm=ChatOpenAI(openai_api_key=openai_api_key), chain_type="stuff", retriever=vectordb.as_retriever(search_type="mmr"), return_source_documents=True)
ques = 'my_question'
ans = qa(ques)

Can anyone please help me that how can I upload all the pdf files consisting by a url into the chroma vector database using UnstructuredUrlLoader or SeleniumUrlLoader, I will be thankful to you.

Thank You

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.vectorstores import Chroma                                
from langchain.embeddings import OpenAIEmbeddings                            
from langchain.text_splitter import RecursiveCharacterTextSplitter , TokenTextSplitter      
from langchain.llms import OpenAI                                           
from langchain.chat_models import ChatOpenAI                                  
from langchain.chains import VectorDBQA, RetrievalQA                                      
from langchain.document_loaders import TextLoader, UnstructuredFileLoader, DirectoryLoader,UnstructuredURLLoader,SeleniumURLLoader  
from langchain.indexes import VectorstoreIndexCreator
from langchain.prompts import PromptTemplate
import chromadb
import wx
import os
import requests
from bs4 import BeautifulSoup

openai_api_key = my_openai_key
persist_directory = "Zdb_directory"
collection_name = 'my collection'
temperature = 0
max_tokens = 200
llm=ChatOpenAI(openai_api_key=openai_api_key)

#all url are consisting pdf files inside it or in sub url
urls = ['url1,'url2','url3']
#loader = UnstructuredURLLoader(urls)
loader = SeleniumURLLoader(urls)

text_splitter = TokenTextSplitter(chunk_size=1000, chunk_overlap=200)
texts = text_splitter.split_documents(docs)
embeddings = OpenAIEmbeddings(openai_api_key=openai_api_key)
vectordb = Chroma.from_documents(texts, embedding=embeddings, persist_directory=persist_directory)
vectordb.persist()
vectordb = None

vectodb = Chroma(persist_directory=persist_directory, embedding_function=embeddings, collection_name='my_collection)
qa = RetrievalQA.from_chain_type(llm=ChatOpenAI(openai_api_key=openai_api_key), chain_type="stuff", retriever=vectordb.as_retriever(search_type="mmr"), return_source_documents=True)
ques = 'my_question'
ans = qa(ques)

### Expected behavior

while I am uploading a url to chroma vector database using Unstructured or SeleniumUrlLoader so rather than just uploading the html website it should also upload the content of all sub urls and the content of all files which are available in this url.

Thank You

**Comment by jamiequint** [comment]
That's not the expected behavior. You have to write the code to do that.

**Comment by ragvendra3898** [comment]
Okay, Thanks Jamiequint
