### ISSUE TITLE
 Issue with retrieving the chunk number from similarity search in lang chain

### ISSUE THREAD

**Issue by 106AbdulBasit** [langchain-ai/langchain#6004]
### Issue you'd like to raise.

Description:
I am currently using the lang chain repository for my project, specifically the functionality related to similarity search. I have encountered an issue when attempting to retrieve the chunk number from the search results.

To provide some context, I have already performed the necessary steps to generate embeddings for each chunk using the provided functions in lang chain. Here is the relevant code snippet:
```
embeddings = OpenAIEmbeddings()
knowledge_base = FAISS.from_texts(chunks, embeddings)
```

After creating the knowledge base, I utilize the similarity_search function to find the most similar chunk to a given query:

`docs = knowledge_base.similarity_search(query)`

The docs object returned contains information about the search results, but I am struggling to access the specific chunk number associated with the most similar result.

My question is: Is there a method or property available in lang chain that allows me to retrieve the chunk number from the docs object?

I would greatly appreciate any assistance or guidance in resolving this issue. Thank you for your support!

### Suggestion:

I could not able to find any documentation, Once I know how to do it I can add it to the documentation

**Comment by laotycoon** [comment]
Do you have resolve the issue? I have met the same question. I use OpenSearchVector, and filter data by OpenSearch.similarity_search, how to construct filtered documents to retriever?

**Comment by 106AbdulBasit** [comment]
I was trying t utilize the Fassi similarity index  to get the chunk, by doing some reverse engineering to get the source,  I think we can not directly get the chunk number if we use the 

docs = knowledge_base.similarity_search(query)

You can use the   lang chain retrieval to get the source 

https://www.youtube.com/watch?v=UCORs4FauFM&t=18s

above is the video in which I have implemented this.


But in order to implement the Fassi library that thing can also be done but you have to map the embeddings into Fassi by using own your custom function
