### ISSUE TITLE
How to use Output parser with LLM Chain

### ISSUE THREAD

**Issue by ZohaibRamzan** [langchain-ai/langchain#6013]
###Use of Output parser with LLM Chain

I want to use the sequential chain of two LLm chains. The first chain is coded as below. I want to get the output of this chain as a Python list of aspects.

```
# This is an LLMChain for Aspects Extraction.

examples =[ {
"review": '''Improve the communication updates to families. Improve consistency, with housekeeping it was supposed to be weekly but now it is every 2 or 3 weeks. There is no consistency in the staff either due to the high turnover rate. Improve the services in the dining room along with meal options.''',
"aspects": '''Relevant Aspects are communication on updates, housekeeping consistency, staff turnover, and dining services.'''
},
            
{"review": '''On paper they do, but my wife has not been brought to them. I have not had a meeting to set up a plan for her. No one wheels her to partake in the activities. They need somebody there that could take them to activities if they wanted. They should bring them to activities where other people will watch over them. The people that are in charge, like the head nurse and activities director, are good about getting ahold of and answering your questions. Once you get down to the next level, they are overwhelmed. They could use another set of eyes and hands. In the memory care area, a lot of people need care at the same time.''',
"aspects": '''Relevant Aspects are Staff Attitude, Care Plan Setup, Staff Involvement in Activities, Oversight during Activities, Memory Care Area'''}
]

#Configure a formatter that will format the few shot examples into a string. This formatter should be a PromptTemplate object.
prompt_template='''
Review: {review}
{aspects}
'''
example_prompt = PromptTemplate(input_variables=["review", "aspects"], template= prompt_template, output_parser=output_parser )

final_prompt = FewShotPromptTemplate(
    examples=examples, 
    example_prompt=example_prompt, 
    suffix="Review: {review}", 
    input_variables=["review"],
    prefix="We are extracting the aspects from the review given by the residents of nursing homes. Take the Review as input and extract the different aspects about the the staff, food, \
building, activities, management, cost of the the nuursing home."
)

output=aspect_extraction_chain.predict_and_parse(review="The community has popcorn days, church, birthday celebrations, holiday parties, therapy dogs, and so much more. My mother is very happy here, and she is kept active. They do a great job of keeping the elderly minds active and involved. The dining program is great as well. My mother tends to eat slow, but the dining program always lets my mother stay to finish her food. Any residents that want to practice religion, this is also offered here! More outings have been added, they just went to Walmart recently.")
```

The current result is a string like 
'Relevant Aspects are Activities, Elderly Minds Engagement, Dining Program, Religious Offerings, Outings.'

I want the result as: ['\nActivities', 'Elderly Minds Engagement', 'Dining Program', 'Religious Offerings', 'Outings.']

### Suggestion:

Kindly guide me on How to use langchain output parser for it.

**Comment by PavanSETTEM-003** [comment]
I hope this should work for you 

<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <h2>Code Snippet</h2>
  <pre><code>  import langchain

    # Input string
    result_string = "Relevant Aspects are Activities, Elderly Minds Engagement, Dining Program, Religious Offerings, Outings."

    # Define the output parser pattern
    pattern = r"Relevant Aspects are (.*)\."

    # Use the output parser to extract the aspects
    aspects = langchain.extract(result_string, pattern)

    # Convert the extracted aspects into a list
    aspect_list = aspects[0].split(", ")

    # Print the result
    print(aspect_list)
  </code></pre>
</body>
</html>

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer
To use LangChain's output parser to convert the result into a list of aspects instead of a single string, create an instance of the CommaSeparatedListOutputParser class and use the predict_and_parse method with the appropriate prompt. 

Here's an example:
```python
from langchain.output_parsers import CommaSeparatedListOutputParser
from langchain.chains import LLMChain, PromptTemplate

output_parser = CommaSeparatedListOutputParser()
template = """List all the colors in a rainbow"""
prompt = PromptTemplate(template=template, input_variables=[], output_parser=output_parser)
llm_chain = LLMChain(prompt=prompt, llm=llm)

llm_chain.predict_and_parse()
```

### Source

- [docs/modules/chains/generic/llm_chain.ipynb](https://github.com/hwchase17/langchain/blob/master/docs/modules/chains/generic/llm_chain.ipynb)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by talhaanwarch** [comment]
@ZohaibRamzan if i am not wrong there is an example where output from first chain is used as input in second chain
https://python.langchain.com/en/latest/modules/chains/generic/sequential_chains.html
``
synopsis_chain = LLMChain(llm=llm, prompt=prompt_template, output_key="synopsis")
```
```
prompt_template = PromptTemplate(input_variables=["synopsis"], template=template)
review_chain = LLMChain(llm=llm, prompt=prompt_template, output_key="review")
```
synopsis_chain output is synopsis which is input in review_chain

**Comment by ZohaibRamzan** [comment]
> @ZohaibRamzan if i am not wrong there is an example where output from first chain is used as input in second chain https://python.langchain.com/en/latest/modules/chains/generic/sequential_chains.html `` synopsis_chain = LLMChain(llm=llm, prompt=prompt_template, output_key="synopsis")
> 
> prompt_template = PromptTemplate(input_variables=["synopsis"], template=template) review_chain = LLMChain(llm=llm, prompt=prompt_template, output_key="review")
> 
> ```
> synopsis_chain output is synopsis which is input in review_chain
> ```

You are right, but this does does not ensure the first chain output as a list.

**Comment by AvengerMoJo** [comment]
I'm using GPT4ALL but it should work as well for other models. The follow get_format_instructions() basically is creating a prompt to tell the llm to reply e.g. one,two,three,four,five 
So my guess is it is not 100% sure the answer will be returning as a list but it should. 
```
from langchain.output_parsers import CommaSeparatedListOutputParser 

output_parser = CommaSeparatedListOutputParser()
format_instructions = output_parser.get_format_instructions()

template = "Questions: Please list five different {subject}.\n{format_instructions}\n\nAnswer:"  
prompt = PromptTemplate(
              template=template,
              input_variables=["subject"],
              partial_variables={"format_instructions": format_instructions})
callbacks = [StreamingStdOutCallbackHandler()]
llm = GPT4All(model=MODEL_PATH, backend="gptj", n_threads=6, callbacks=callbacks, verbose=True)
print("Subject that you want to see in a list of 5?")
while True:
    next_subject = input()
    if not next_subject:
        break
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    answer = llm_chain.run(subject=next_subject)
    print(answer)
    print(output_parser.parse(answer))

```

**Comment by oresttokovenko** [comment]
I'm looking for a little help using the Pydantic parser please. I can output the results but I'm not able to parse successfully. 
```python
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage
from langchain.output_parsers import PydanticOutputParser
from langchain.prompts.few_shot import FewShotPromptTemplate
from langchain.prompts import (
    ChatPromptTemplate,
    PromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
    HumanMessagePromptTemplate,
)

from pydantic import BaseModel, Field, conlist
from dotenv import load_dotenv
from typing import List
import pandas as pd
import json
import os

# loading api key
load_dotenv("../.env")
openai_api_key = os.environ.get("OPENAI_API_KEY")
model = 'gpt-4'
temperature = 0.0

# importing input text
with open("input.txt", "r") as f:
    input = f.read()

# importing prompt
with open("prompt.txt", "r") as f:
    user_prompt = f.read()

class FlashCard(BaseModel):
    question: str = Field(description="The question for the flashcard")
    answer: str = Field(description="The answer for the flashcard")

llm = ChatOpenAI(openai_api_key=openai_api_key, model=model, temperature=temperature)

pydantic_parser = PydanticOutputParser(pydantic_object=FlashCard)

format_instructions = pydantic_parser.get_format_instructions()

prompt = ChatPromptTemplate.from_template(template=user_prompt)

messages = prompt.format_messages(input_text=input, format_instructions=format_instructions)

output = llm(messages)

flashcards = pydantic_parser.parse(output.content)

print(flashcards)
```

Here is the output:
````bash
Traceback (most recent call last):
  File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/anki-env/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 25, in parse
    json_object = json.loads(json_str, strict=False)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 4 column 4 (char 112)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/src/gpt_v4.py", line 50, in <module>
    flashcards = pydantic_parser.parse(output.content)
  File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/anki-env/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 31, in parse
    raise OutputParserException(msg)
langchain.schema.output_parser.OutputParserException: Failed to parse FlashCard from completion Here are the flashcards created from the text:

```
[
  {
    "question": "Who was a contributor to the ABC language before creating Python?",
    "answer": "Guido"
  },
  {
    "question": "What was the purpose of the ABC language project?",
    "answer": "To design a programming environment for beginners"
  },
  {
    "question": "What are some of the ideas introduced by ABC that are now considered 'Pythonic'?",
    "answer": "Generic operations on different types of sequences, built-in tuple and mapping types, structure by indentation, strong typing without variable declarations, and more"
  },
  {
    "question": "What did Python inherit from ABC?",
    "answer": "The uniform handling of sequences"
  },
  {
    "question": "What are some of the common operations shared by sequences in Python?",
    "answer": "Iteration, slicing, sorting, and concatenation"
  },
  {
    "question": "What is the benefit of understanding the variety of sequences available in Python?",
    "answer": "It saves us from reinventing the wheel, and their common interface inspires us to create APIs that properly support and leverage existing and future sequence types"
  },
  {
    "question": "What types of sequences does this chapter discuss?",
    "answer": "Sequences in general, from the familiar list to the str and bytes types added in Python 3"
  },
  {
    "question": "What are some of the specific topics covered in this chapter?",
    "answer": "Lists, tuples, arrays, and queues"
  },
  {
    "question": "Where can you find specifics of Unicode strings and byte sequences?",
    "answer": "In Chapter 4"
  },
  {
    "question": "What is the subject of Chapter 12?",
    "answer": "Creating your own sequence types"
  }
]
```
Got: Extra data: line 4 column 4 (char 112)
````


I think the `List` type from the `typing` library might solve it, but I'm not sure

**Comment by oresttokovenko** [comment]
> I'm looking for a little help using the Pydantic parser please. I can output the results but I'm not able to parse successfully.
> 
> ```python
> from langchain.chat_models import ChatOpenAI
> from langchain.schema import HumanMessage, SystemMessage
> from langchain.output_parsers import PydanticOutputParser
> from langchain.prompts.few_shot import FewShotPromptTemplate
> from langchain.prompts import (
>     ChatPromptTemplate,
>     PromptTemplate,
>     SystemMessagePromptTemplate,
>     AIMessagePromptTemplate,
>     HumanMessagePromptTemplate,
> )
> 
> from pydantic import BaseModel, Field, conlist
> from dotenv import load_dotenv
> from typing import List
> import pandas as pd
> import json
> import os
> 
> # loading api key
> load_dotenv("../.env")
> openai_api_key = os.environ.get("OPENAI_API_KEY")
> model = 'gpt-4'
> temperature = 0.0
> 
> # importing input text
> with open("input.txt", "r") as f:
>     input = f.read()
> 
> # importing prompt
> with open("prompt.txt", "r") as f:
>     user_prompt = f.read()
> 
> class FlashCard(BaseModel):
>     question: str = Field(description="The question for the flashcard")
>     answer: str = Field(description="The answer for the flashcard")
> 
> llm = ChatOpenAI(openai_api_key=openai_api_key, model=model, temperature=temperature)
> 
> pydantic_parser = PydanticOutputParser(pydantic_object=FlashCard)
> 
> format_instructions = pydantic_parser.get_format_instructions()
> 
> prompt = ChatPromptTemplate.from_template(template=user_prompt)
> 
> messages = prompt.format_messages(input_text=input, format_instructions=format_instructions)
> 
> output = llm(messages)
> 
> flashcards = pydantic_parser.parse(output.content)
> 
> print(flashcards)
> ```
> 
> Here is the output:
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/anki-env/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 25, in parse
>     json_object = json.loads(json_str, strict=False)
>   File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 359, in loads
>     return cls(**kw).decode(s)
>   File "/opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 4 column 4 (char 112)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/src/gpt_v4.py", line 50, in <module>
>     flashcards = pydantic_parser.parse(output.content)
>   File "/Users/oresttokovenko/Desktop/miscellaneous/projects/anki/anki-env/lib/python3.10/site-packages/langchain/output_parsers/pydantic.py", line 31, in parse
>     raise OutputParserException(msg)
> langchain.schema.output_parser.OutputParserException: Failed to parse FlashCard from completion Here are the flashcards created from the text:
> 
> ```
> [
>   {
>     "question": "Who was a contributor to the ABC language before creating Python?",
>     "answer": "Guido"
>   },
>   {
>     "question": "What was the purpose of the ABC language project?",
>     "answer": "To design a programming environment for beginners"
>   },
>   {
>     "question": "What are some of the ideas introduced by ABC that are now considered 'Pythonic'?",
>     "answer": "Generic operations on different types of sequences, built-in tuple and mapping types, structure by indentation, strong typing without variable declarations, and more"
>   },
>   {
>     "question": "What did Python inherit from ABC?",
>     "answer": "The uniform handling of sequences"
>   },
>   {
>     "question": "What are some of the common operations shared by sequences in Python?",
>     "answer": "Iteration, slicing, sorting, and concatenation"
>   },
>   {
>     "question": "What is the benefit of understanding the variety of sequences available in Python?",
>     "answer": "It saves us from reinventing the wheel, and their common interface inspires us to create APIs that properly support and leverage existing and future sequence types"
>   },
>   {
>     "question": "What types of sequences does this chapter discuss?",
>     "answer": "Sequences in general, from the familiar list to the str and bytes types added in Python 3"
>   },
>   {
>     "question": "What are some of the specific topics covered in this chapter?",
>     "answer": "Lists, tuples, arrays, and queues"
>   },
>   {
>     "question": "Where can you find specifics of Unicode strings and byte sequences?",
>     "answer": "In Chapter 4"
>   },
>   {
>     "question": "What is the subject of Chapter 12?",
>     "answer": "Creating your own sequence types"
>   }
> ]
> ```
> Got: Extra data: line 4 column 4 (char 112)
> ```
> 
> It has to do with how the JSON is outputted, I guess it’s not ‘clean’ enough, but i’m not sure how to change that. Maybe format_instructions?

I figured it out, I just needed to adjust the Pydantic class

```python
class FlashCard(BaseModel):
    question: str = Field(description="The question for the flashcard")
    answer: str = Field(description="The answer for the flashcard")

class FlashCardArray(BaseModel):
    flashcards: List[FlashCard]
```
