### ISSUE TITLE
extra semicolon with SQLDatabaseChain when used with Oracle

### ISSUE THREAD

**Issue by yogeshb369** [langchain-ai/langchain#6016]
### System Info

SQLDatabaseChain is appending a semicolon to created SQL. which is not liked by cx_oracle (or Oracle database by implication) - since it appends another semicolon in the end. making two semicolons in effect and causing error 

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00933: SQL command not properly ended

https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html

Need a way to control this behavior.

https://python.langchain.com/en/latest/modules/chains/examples/sqlite.html#

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps:

from langchain import OpenAI, SQLDatabase, SQLDatabaseChain
import cx_Oracle

db = SQLDatabase.from_uri("oracle://ora-user-name:ora-user-password@ora-host-name:1521/service")
llm = OpenAI(temperature=0, verbose=True)

db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)
db_chain.run("How many employees are there?")

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00933: SQL command not properly ended
[SQL: SELECT COUNT(*) FROM YOUR_TABLE_NAME;]
(Background on this error at: https://sqlalche.me/e/20/4xp6)

### Expected behavior

Need a way to optionally suppress a semicolon being appended. or if it could be avoided in favor of cx_oracle - since it doesnt like a semicolon anyways in SQL

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer
To prevent LangChain's `SQLDatabaseChain` from appending an extra semicolon when used with Oracle and cx_Oracle, you can modify the `_call` method of the SQLDatabaseChain class. In the `_call` method, after generating the SQL command, you can remove the extra semicolon before executing the query. Here's the modified code snippet:

```python
sql_cmd = self.llm_chain.predict(
    callbacks=_run_manager.get_child(),
    **llm_inputs,
).strip()

# Remove extra semicolon if using Oracle and cx_Oracle
if self.database.dialect == "oracle":
    sql_cmd = sql_cmd.rstrip(";")

# Continue with the rest of the code
```

Add this code snippet right after the `sql_cmd` is generated in the `_call` method of the SQLDatabaseChain class. This will remove the extra semicolon when using Oracle and cx_Oracle.

### Source

- [langchain/chains/sql_database/base.py](https://github.com/hwchase17/langchain/blob/master/langchain/chains/sql_database/base.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by yogeshb369** [comment]
Thank you for a quick response.
I used a workaround in the interim. Worked for me since I am strictly Oracle based.

`sqlchain\Lib\site-packages\sqlalchemy\engine\default.py
def do_execute(self, cursor, statement, parameters, context=None):
        new_statement = statement.rstrip(';')
        cursor.execute(new_statement, parameters)`

Your solution is much safer.

`sqlchain\Lib\site-packages\langchain\chains\sql_database\base.py

if self.database.dialect == "oracle":
                sql_cmd = sql_cmd.rstrip(";")

`
