### ISSUE TITLE
Add clearer API for defining `k` (number of documents retrieved) in VectorStore/retriever defining functions

### ISSUE THREAD

**Issue by ROMEEZHOU** [langchain-ai/langchain#6033]
### Feature request

Let users easily define the value of `k`, which is the number of documents retrieved, when specifying a VectorStore.

### Motivation

When working with documents, users typically need to specify VectorStore, and users may often want to define the specific number of documents being retrieved, i.e., the `k`, when similarity search runs behind the scene. For example, I am doing
```
docsearch = Chroma.from_documents(texts1 + texts3, embeddings)
retriever=docsearch.as_retriever(search_kwargs = {'k':1})
```
However, there is no easy way or clear documentation for this. I have to go through the source code all the ways to find that I can do it with adding `search_kwargs = {'k':1}` when I specify the retriever. This is not user-friendly, especially noticing that this is a common feature that users need.

### Your contribution

I would love to open a PR for this. I am willing to either change the code or writing a clearer documentation for this feature.

**Comment by Iana-Kasimova-TR** [comment]
It will be also nice to get this value maybe from env var or from config file
