### ISSUE TITLE
TypeError("Requests.apost() missing 1 required positional argument: 'data'")

### ISSUE THREAD

**Issue by WanderAG** [langchain-ai/langchain#6034]
### System Info

langchain = "^0.0.197"

### Who can help?

@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [X] Async

### Reproduction

``` python
import asyncio

from langchain.utilities import TextRequestsWrapper

requests = TextRequestsWrapper()


async def fun():
    ret = await requests.apost("http://127.0.0.1:8080", data={"data": 123})


if __name__ == '__main__':
    asyncio.run(fun())

```

### Expected behavior

![image](https://github.com/hwchase17/langchain/assets/7575944/e4ff4dc1-54e2-43ce-999e-9c233c2a6752)

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

Update the `apost` method in the `TextRequestsWrapper` class to use the `data` parameter:

```python
async def apost(self, url: str, data: Dict[str, Any], **kwargs: Any) -> str:
    """POST to the URL and return the text asynchronously."""
    async with self.requests.apost(url, data=data, **kwargs) as response:
        return await response.text()
```

### Sources
- [langchain/requests.py](https://github.com/hwchase17/langchain/blob/master/langchain/requests.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by dmvtmn** [comment]
Hi! Any news on this, I am also gettting the same error even in the vanilla post request:
`requests_lgc_post_resp = requests_lg.post(url=launch_agent_url, data=data)`

Thanks

**Comment by nfcampos** [comment]
This has been fixed
