### ISSUE TITLE
When using MongoDBAtlasVectorSearch i get KeyError: 'text' despite having the collection populated

### ISSUE THREAD

**Issue by greenomy-matteo** [langchain-ai/langchain#6055]
### System Info

Python version: 3.10.11 (main, May 17 2023, 14:30:36) [Clang 14.0.6 ]
pymongo                  4.3.3
langchain                0.0.190

### Who can help?

@eyurtsev @agola11  

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [x] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I followed religiously the following tutorial:

https://python.langchain.com/en/stable/modules/indexes/vectorstores/examples/mongodb_atlas_vector_search.html

Despite that I get the following error.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[14], line 12
     10 # perform a similarity search between the embedding of the query and the embeddings of the documents
     11 query = "my query?"
---> 12 docs = vectorStore.similarity_search(query)

File ~/opt/miniconda3/envs/LLM_langchain_exploration/lib/python3.10/site-packages/langchain/vectorstores/mongodb_atlas.py:222, in MongoDBAtlasVectorSearch.similarity_search(self, query, k, pre_filter, post_filter_pipeline, **kwargs)
    194 def similarity_search(
    195     self,
    196     query: str,
   (...)
    200     **kwargs: Any,
    201 ) -> List[Document]:
    202     """Return MongoDB documents most similar to query.
    203 
    204     Use the knnBeta Operator available in MongoDB Atlas Search
   (...)
    220         List of Documents most similar to the query and score for each
    221     """
--> 222     docs_and_scores = self.similarity_search_with_score(
    223         query,
    224         k=k,
    225         pre_filter=pre_filter,
    226         post_filter_pipeline=post_filter_pipeline,
    227     )
    228     return [doc for doc, _ in docs_and_scores]

File ~/opt/miniconda3/envs/LLM_langchain_exploration/lib/python3.10/site-packages/langchain/vectorstores/mongodb_atlas.py:189, in MongoDBAtlasVectorSearch.similarity_search_with_score(self, query, k, pre_filter, post_filter_pipeline)
    187 docs = []
    188 for res in cursor:
--> 189     text = res.pop(self._text_key)
    190     score = res.pop("score")
    191     docs.append((Document(page_content=text, metadata=res), score))

KeyError: 'text'
```

### Expected behavior

should get the docs back

**Comment by Tsadoq** [comment]
I think I've found the problem:

it is sufficent to access the _text_key value and set it to the one that is used for text in your database, e.g.

```
vectorStore._text_key = 'some_sort_of_text'
docs = vectorStore.similarity_search(query)
```

I think it might be a good idea to add this `MongoDBAtlasVectorSearch` init.
I'll propose a PR if you guys are fine @hwchase17

**Comment by P-E-B** [comment]
You can already pass the text_key in the init
