### ISSUE TITLE
Issue: ModuleNotFoundError: No module named 'langchain.callbacks.shared'

### ISSUE THREAD

**Issue by Arvind-4** [langchain-ai/langchain#6058]
### Issue you'd like to raise.

Hello,

I am having trouble running my code due to an error that I encountered. The error message that I received is "ModuleNotFoundError: No module named 'langchain.callbacks.shared'". I am not sure how to resolve this issue and would appreciate any help or guidance.

This line of code is using the `pickle` module to load data from a file. The `pickle.load(file)` function reads the pickled representation of an object from the open file object `file` and returns the reconstituted object hierarchy specified therein.

In this case, the returned object is expected to be a tuple with two elements, which are assigned to the variables `self.chain` and `self.vectorstore`, respectively. This means that the first element of the tuple is assigned to `self.chain`, and the second element is assigned to `self.vectorstore`.

Here is some information about my environment that may be helpful:
- OS: Ubuntu
- Python version: 3.10
- Langchain Version: 0.0.198

Issue Screen Shot:

<br />

![Screenshot from 2023-06-12 23-55-27](https://github.com/hwchase17/langchain/assets/81419892/33e0bdd1-2fd0-4570-ab6e-6100c1211eb7)

Thank you in advance for your help and support in resolving this issue.

**Comment by fielding** [comment]
Sounds like whatever you pickled is holding onto something that doesn't exist ... anymore. Based on what it is complaining about, is there any chance you recently went from an LLM that supported async to one that didn't? Either way, I'd be wiling to bet if you stepped back through your commits you'll find one that will deserialize your data properly without any missing properties or referencing anything that isn't there anymore
