### ISSUE TITLE
Issue: LangChain Plus Api Key

### ISSUE THREAD

**Issue by dsantiago** [langchain-ai/langchain#6059]
### Issue you'd like to raise.

Started a local server just to learn more about with `langchain plus start`. It says that I can generate a new api as it appears to have an endpoint in port 1984. But when I click the menu there's no **Settings** option there.

---

<img width="1787" alt="Screenshot 2023-06-12 at 16 32 31" src="https://github.com/hwchase17/langchain/assets/3484029/e42ef803-f216-486a-84f3-6c4026a37a8f">

**Comment by mcapitanio** [comment]
Hi, @dsantiago how can you use the "langchain" command?

I installed langchain with:

`pip install langchain[all]`

but I don't have any "langchain" command available:

`langchain: command not found`
