### ISSUE TITLE
Issue: chroma where_document parameter passed in search_kwargs is invalid

### ISSUE THREAD

**Issue by wyirtrytpz003** [langchain-ai/langchain#6073]
### Issue you'd like to raise.

I want to use the chroma where_document parameter to do precise filtering of the content during data retrieval, but I found that the where_document parameter is not passed after the similarity_search_by_vector method is finally called in the source code
![image](https://github.com/hwchase17/langchain/assets/122618171/acada970-0432-465b-9541-a6214c50f773)

### Suggestion:

I hope that I can generate where_document in the retrieval parameter of the retriever, just like the existing filter will be passed to where, the code is as follows：

```py
search_kwargs = {
    "k": k,
    "filter": filter,
    "where_document": {"$contains": "1000001"}
}
retriever = vectordb.as_retriever(
    search_kwargs=search_kwargs
)
```

**Comment by PTTrazavi** [comment]
any solution to this issue?
I can't use "where_document" filter in chroma db retreiver either.
