### ISSUE TITLE
unknown command `MODULE`, with args beginning with: `LIST`, 

### ISSUE THREAD

**Issue by denisa-ms** [langchain-ai/langchain#6075]
### System Info

when trying to connect to azure redis I get the following error:
unknown command `MODULE`, with args beginning with: `LIST`, 
Here is the code:

fileName = "somefile.pdf"
loader = PyPDFLoader(fileName)
docs = loader.load_and_split()
redis_conn = f"rediss://:{utils.REDIS_PWD}@{utils.REDIS_HOST}:{utils.REDIS_PORT}"
rds = Redis.from_documents(docs, embeddings, redis_url=redis_conn, index_name='link')

Important:
Connecting to redis like this, works!
r = redis.StrictRedis(host=utils.REDIS_HOST,port=utils.REDIS_PORT, db=0, password=utils.REDIS_PWD, ssl=True)
r.set('foo', 'bar')
r.get('foo')

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This works:
import redis
r = redis.StrictRedis(host=utils.REDIS_HOST,port=utils.REDIS_PORT, db=0, password=utils.REDIS_PWD, ssl=True)
r.set('foo', 'bar')
r.get('foo')

This does not:

from langchain.document_loaders import PyPDFLoader # for loading the pdf
from langchain.vectorstores.redis import Redis
from langchain.embeddings import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model=OPENAI_EMBEDDING_MODEL_NAME, chunk_size=1)
fileName = "somefile.pdf"
loader = PyPDFLoader(fileName)
docs = loader.load_and_split()
redis_conn = f"rediss://:{utils.REDIS_PWD}@{utils.REDIS_HOST}:{utils.REDIS_PORT}"
rds = Redis.from_documents(docs, embeddings, redis_url=redis_conn, index_name='link')

### Expected behavior

save embeddings into REdis

**Comment by Vishal240699** [comment]
I am facing the same issue and found that Azure Redis has version 6.0.0 as the latest version. Thus unable to use the Azure Redis and langchain together. Is there a workaround for langchain to work with Redis server version 6.0.0 ?

**Comment by timxieICN** [comment]
Have the same issue with Elasticache (Redis Cluster) running on engine v7.0 and `redis==4.5.3`

**Comment by SherL0cked** [comment]
For ElasticCache it's more like restriction from AWS side that MODULE LIST command isn't supported. I've created my own vectorstore for Redis especially overwrite _check_redis_module_exist function and which works fine.
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/RestrictedCommands.html
https://github.com/hwchase17/langchain/blob/a6b40b73e5f93e44df668272aaa672ea096db9ff/langchain/vectorstores/redis.py#L48

**Comment by faynburd** [comment]
@SherL0cked - can you give an example of how you overwrote the _check_redis_module_exist ?
It looks like Redis Labs also restricts the MODULE LIST command

**Comment by SherL0cked** [comment]
@faynburd I have to create my own customize Redis VectorStore which is similar to existing langchain logic only changed the validations on 
https://github.com/hwchase17/langchain/blob/a6b40b73e5f93e44df668272aaa672ea096db9ff/langchain/vectorstores/redis.py#L48
https://github.com/hwchase17/langchain/blob/a6b40b73e5f93e44df668272aaa672ea096db9ff/langchain/vectorstores/redis.py#L139

**Comment by faynburd** [comment]
Actually managed with monkey patching this function to always return True 
```
from langchain.vectorstores import redis

# command MODULE LIST is not supported by Redis Labs - monkey patch it
redis._check_redis_module_exist = lambda *args: True
```

**Comment by DavidArenburg** [comment]
@faynburd, @SherL0cked  That's solves the error in the title, thanks!
 
Though, it introduces a new error when running `redis.Redis.from_documents` (which is the command OP is trying to execute) of:
 '_**ResponseError: unknown command 'FT.CREATE', with args beginning with: 'test' 'ON' 'HASH' 'PREFIX' '1' 'doc:test' 'SCORE' '1.0' 'SCHEMA' 'content' 'TEXT' 'WEIGHT' '1.0' 'metadata' 'TEXT' 'WEIGHT' '1.0'**_ '

Have you solved it somehow?

The code I've tried (redis version is 4.6.0 and I'm running Redis on AWS ElasticCache):
```python
from langchain.vectorstores import redis
redis._check_redis_module_exist = lambda *args: True
rds = redis.Redis.from_documents(documents = docs[:10], embedding = embeddings, redis_url="redis://localhost:6000", index_name="test")
```

Thanks!

**Comment by DavidArenburg** [comment]
FYI, `Redis.from_documents` won't work on AWS Elasticache because the there is no RediSearch installed on it, see [here](https://stackoverflow.com/questions/75875078/how-do-i-install-redisearch-into-aws-elasticache-or-amazon-memorydb)

**Comment by Spartee** [comment]
@faynburd, @DavidArenburg is right, AWS doesn't have, and will never have RediSearch support. Elasticache is a wrapper around OSS redis.

For the actual redis with redisearch, you can run in docker

```bash
❯ docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
```

or start a free tier on redis cloud.

**Comment by Spartee** [comment]
Ok and for those for Microsoft 

Azure Redis != Azure CAche for REdis Enterprise (ACRE)

and those from Google

MemoryStore != Redis Enteprise

-----

Redis cloud supports all these clouds, theres marketplace offerings on all of them, and theres also just the docker I mentioned above.

**Comment by fovi-com** [comment]
Seems to be the problem when trying to use Google's Memorystore version of Redis.  I was trying to run LangChain OpenGPTs (https://github.com/langchain-ai/opengpts) on Google Cloud Run using the integrated Redis feature of Run but I get this error:

redis.exceptions.ResponseError: unknown command 'MODULE', with args beginning with: 'LIST'

**Comment by aboscus** [comment]
Using RedisSemanticCache with an Azure Redis Service, getting same error. Anyone found the solution?

**Comment by Jayantkhandebharad** [comment]
version 7.0+ of azure redis is only avilable in Enterprice plans, I don't need that much storage

<img width="964" height="379" alt="Image" src="https://github.com/user-attachments/assets/34c07e79-158e-48a5-89fc-15e76e67405f" />


anyone found workaround? other than that monkey patch?
