### ISSUE TITLE
Conversational Retriever Chain - condense_question_prompt parameter is not being considered.

### ISSUE THREAD

**Issue by varuntejay** [langchain-ai/langchain#6087]
### System Info

Langchain 0.0.198,
Python 3.10
AWS Sagemaker environment

### Who can help?

@agola11, @hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`from langchain.chains import ConversationalRetrievalChain
import json
from langchain.prompts.prompt import PromptTemplate
prompt_template =  """Answer based on context

Context: {context}

Question: {question}"""
TEST_PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"]
)

question = 'How do I bake cake?'

chain = ConversationalRetrievalChain.from_llm(llm=llm, condense_question_prompt=TEST_PROMPT, retriever=retriever, return_source_documents=True, verbose=True)
chat_history = []

chain({ "chat_history": chat_history, "question": question})

`

### Expected behavior

Expected behavior is that it should take the given TEST_PROMPT, while sending the PROMPT to LLM, which is not doing in the original behavior

**Comment by ibizabroker** [comment]
This snippet should work:

```
prompt_template = """Answer based on context

{context}

Question: {question}"""
TEST_PROMPT = PromptTemplate(input_variables=["context", "question"], template=prompt_template)

chain = ConversationalRetrievalChain.from_llm(
  llm=llm, 
  combine_docs_chain_kwargs={"prompt": TEST_PROMPT},
  retriever=retriever, 
  return_source_documents=True, 
  verbose=True
)
```
