### ISSUE TITLE
'ValueError: "SQLiteEntityStore" object has no field "conn"' error for tutorial "Entity Memory with SQLite storage"

### ISSUE THREAD

**Issue by labdmitriy** [langchain-ai/langchain#6091]
### System Info

LangChain version: 0.0.198
Platform: Ubuntu 20.04 LTS
Python version: 3.10.4

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Reproduce tutorial ["Entity Memory with SQLite storage"](https://python.langchain.com/en/latest/modules/memory/examples/entity_memory_with_sqlite.html)
2. While executing the following code: ```entity_store = SQLiteEntityStore()```,
get the error: ValueError: "SQLiteEntityStore" object has no field "conn"

### Expected behavior

SQLiteEntityStore() must be executed correctly.

**Comment by Shrest4647** [comment]
`
class SQLiteEntityStore(BaseEntityStore):
    """SQLite-backed Entity store"""

    session_id: str = "default"
    table_name: str = "memory_store"

    def __init__(
        self,
        session_id: str = "default",
        db_file: str = "entities.db",
        table_name: str = "memory_store",
        *args: Any,
        **kwargs: Any,
    ):
        try:
            import sqlite3
        except ImportError:
            raise ImportError(
                "Could not import sqlite3 python package. "
                "Please install it with `pip install sqlite3`."
            )
        super().__init__(*args, **kwargs)

        # Error seems to be thrown from here
        self.conn = sqlite3.connect(db_file)

        self.session_id = session_id
        self.table_name = table_name
        self._create_table_if_not_exists()

    @property
    def full_table_name(self) -> str:
        return f"{self.table_name}_{self.session_id}"

    def _create_table_if_not_exists(self) -> None:
        create_table_query = f"""
            CREATE TABLE IF NOT EXISTS {self.full_table_name} (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        """
        with self.conn:
            self.conn.execute(create_table_query)

[[docs]](https://python.langchain.com/en/latest/reference/modules/memory.html#langchain.memory.SQLiteEntityStore.get)    def get(self, key: str, default: Optional[str] = None) -> Optional[str]:
        query = f"""
            SELECT value
            FROM {self.full_table_name}
            WHERE key = ?
        """
        cursor = self.conn.execute(query, (key,))
        result = cursor.fetchone()
        if result is not None:
            value = result[0]
            return value
        return default


[[docs]](https://python.langchain.com/en/latest/reference/modules/memory.html#langchain.memory.SQLiteEntityStore.set)    def set(self, key: str, value: Optional[str]) -> None:
        if not value:
            return self.delete(key)
        query = f"""
            INSERT OR REPLACE INTO {self.full_table_name} (key, value)
            VALUES (?, ?)
        """
        with self.conn:
            self.conn.execute(query, (key, value))


[[docs]](https://python.langchain.com/en/latest/reference/modules/memory.html#langchain.memory.SQLiteEntityStore.delete)    def delete(self, key: str) -> None:
        query = f"""
            DELETE FROM {self.full_table_name}
            WHERE key = ?
        """
        with self.conn:
            self.conn.execute(query, (key,))


[[docs]](https://python.langchain.com/en/latest/reference/modules/memory.html#langchain.memory.SQLiteEntityStore.exists)    def exists(self, key: str) -> bool:
        query = f"""
            SELECT 1
            FROM {self.full_table_name}
            WHERE key = ?
            LIMIT 1
        """
        cursor = self.conn.execute(query, (key,))
        result = cursor.fetchone()
        return result is not None


[[docs]](https://python.langchain.com/en/latest/reference/modules/memory.html#langchain.memory.SQLiteEntityStore.clear)    def clear(self) -> None:
        query = f"""
            DELETE FROM {self.full_table_name}
        """
        with self.conn:
            self.conn.execute(query)
`

**Comment by talhaanwarch** [comment]
facing same error

**Comment by andremattosferraz** [comment]
Adding it to entity.py file fix (langchain/memory/entity.py):
<img width="423" alt="image" src="https://github.com/hwchase17/langchain/assets/133804167/7b0e64af-1dbc-4e35-a932-b1d1343ea680">

**Comment by Meghansh-Maurya** [comment]
> Adding it to entity.py file fix (langchain/memory/entity.py): <img alt="image" width="423" src="https://user-images.githubusercontent.com/133804167/247216390-7b0e64af-1dbc-4e35-a932-b1d1343ea680.png">

This is not working.

**Comment by slavakurilyak** [comment]
Here's how you can modify the SQLiteEntityStore class:

```py
from pydantic import Field, Any

class SQLiteEntityStore(BaseEntityStore):
    """SQLite-backed Entity store"""

    session_id: str = "default"
    table_name: str = "memory_store"
    conn: Any = Field(None)  # Add this line
```

For instance-specific connections, you might need to bypass pydantic's restriction on attribute assignment. This can be done by setting the __dict__ attribute directly:

```py
class SQLiteEntityStore(BaseEntityStore):
    """SQLite-backed Entity store"""

    session_id: str = "default"
    table_name: str = "memory_store"

    def __init__(
        self,
        session_id: str = "default",
        db_file: str = "entities.db",
        table_name: str = "memory_store",
        *args: Any,
        **kwargs: Any,
    ):
        try:
            import sqlite3
        except ImportError:
            raise ImportError(
                "Could not import sqlite3 python package. "
                "Please install it with `pip install sqlite3`."
            )
        super().__init__(*args, **kwargs)

        self.__dict__["conn"] = sqlite3.connect(db_file)  # Change this line
```

**Comment by sorenwacker** [comment]
Seems, I am missing a step:

> TypeError: Can't instantiate abstract class SQLiteEntityStore with abstract methods clear, delete, exists, get, set

**Comment by sorenwacker** [comment]
```

from pydantic import Field
from typing import Any, Optional

class SQLiteEntityStore(BaseEntityStore):
    """SQLite-backed Entity store"""

    session_id: str = "default"
    table_name: str = "memory_store"
    conn: Any = Field(None)  # Add this line
    
    def __init__(
        self,
        session_id: str = "default",
        db_file: str = "entities.db",
        table_name: str = "memory_store",
        *args: Any,
        **kwargs: Any,
    ):
        try:
            import sqlite3
        except ImportError:
            raise ImportError(
                "Could not import sqlite3 python package. "
                "Please install it with `pip install sqlite3`."
            )
        super().__init__(*args, **kwargs)

        self.conn = sqlite3.connect(db_file)
        self.session_id = session_id
        self.table_name = table_name
        self._create_table_if_not_exists()

    @property
    def full_table_name(self) -> str:
        return f"{self.table_name}_{self.session_id}"

    def _create_table_if_not_exists(self) -> None:
        create_table_query = f"""
            CREATE TABLE IF NOT EXISTS {self.full_table_name} (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        """
        with self.conn:
            self.conn.execute(create_table_query)

    def get(self, key: str, default: Optional[str] = None) -> Optional[str]:
        query = f"""
            SELECT value
            FROM {self.full_table_name}
            WHERE key = ?
        """
        cursor = self.conn.execute(query, (key,))
        result = cursor.fetchone()
        if result is not None:
            value = result[0]
            return value
        return default

    def set(self, key: str, value: Optional[str]) -> None:
        if not value:
            return self.delete(key)
        query = f"""
            INSERT OR REPLACE INTO {self.full_table_name} (key, value)
            VALUES (?, ?)
        """
        with self.conn:
            self.conn.execute(query, (key, value))

    def delete(self, key: str) -> None:
        query = f"""
            DELETE FROM {self.full_table_name}
            WHERE key = ?
        """
        with self.conn:
            self.conn.execute(query, (key,))

    def exists(self, key: str) -> bool:
        query = f"""
            SELECT 1
            FROM {self.full_table_name}
            WHERE key = ?
            LIMIT 1
        """
        cursor = self.conn.execute(query, (key,))
        result = cursor.fetchone()
        return result is not None

    def clear(self) -> None:
        query = f"""
            DELETE FROM {self.full_table_name}
        """
        with self.conn:
            self.conn.execute(query)

entity_store = SQLiteEntityStore()

llm = OpenAI(temperature=0)

memory = ConversationEntityMemory(llm=llm, entity_store=entity_store)

conversation = ConversationChain(
    llm=llm,
    prompt=ENTITY_MEMORY_CONVERSATION_TEMPLATE,
    memory=memory,
    verbose=True,
)
```

**Comment by bachi76** [comment]
Bug still exists.

> Here's how you can modify the SQLiteEntityStore class:
>         self.__dict__["conn"] = sqlite3.connect(db_file)  # Change this line
> ```

We surely can't modify vendor library code? I mean we can, but it will break on the next update and is a total no-no. I am just wondering, do people here do this in projects? And, are PRs not the better way?

**Comment by leobenkel** [comment]
Any update or workaround on this that do not involved modifying inner library code ?
