### ISSUE TITLE
A change in the output format of documents loaded with CSVLoader: (+ weird redundancy in the output)

### ISSUE THREAD

**Issue by mohamedjihedriahi** [langchain-ai/langchain#6096]
### System Info

from this format (example):
[Document(page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0), Document(page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0), 
Document(page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0)]

To this:
[Document(**lc_kwargs**={page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0),
page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0),

Document(**lc_kwargs**={page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0),page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0), 

Document(**lc_kwargs**={page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0),
page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0)]

### Who can help?

@hwchase17 @eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Check out my colab notebook for better understanding:
https://colab.research.google.com/drive/1w8ZTAkapRev8KHI9w4IAk37T9GfFGWW2?usp=drive_link#scrollTo=tl502z9-RRJC

### Expected behavior

expected output (as you can see in the official doc: [https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/csv.html] ) : 

[Document(page_content='Team: Nationals\n"Payroll (millions)": 81.34\n"Wins": 98', lookup_str='', metadata={'source': './example_data/mlb_teams_2012.csv', 'row': 0}, lookup_index=0), 
Document(page_content='Team: Reds\n"Payroll (millions)": 82.20\n"Wins": 97', lookup_str='', metadata={'source': './example_data/mlb_teams_2012.csv', 'row': 1}, lookup_index=0)]

**Comment by zanghu** [comment]
same

> ### System Info
> from this format (example): [Document(page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0), Document(page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0), Document(page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0)]
> 
> To this: [Document(**lc_kwargs**={page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0), page_content='Team: **Athletics**'', metadata={'source': '**my source1**', 'row': **0**}, lookup_index=0),
> 
> Document(**lc_kwargs**={page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0),page_content='Team: **Rangers**', lookup_str='', metadata={'source': '**my source2**', 'row': **1**}, lookup_index=0),
> 
> Document(**lc_kwargs**={page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0), page_content='Team: **Yankees**', lookup_str='', metadata={'source': '**my source3**', 'row': **2**},lookup_index=0)]
> 
> ### Who can help?
> @hwchase17 @eyurtsev
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [x]  My own modified scripts
> 
> ### Related Components
> * [ ]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [x]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> Check out my colab notebook for better understanding: https://colab.research.google.com/drive/1w8ZTAkapRev8KHI9w4IAk37T9GfFGWW2?usp=drive_link#scrollTo=tl502z9-RRJC
> 
> ### Expected behavior
> expected output (as you can see in the official doc: [https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/csv.html] ) :
> 
> [Document(page_content='Team: Nationals\n"Payroll (millions)": 81.34\n"Wins": 98', lookup_str='', metadata={'source': './example_data/mlb_teams_2012.csv', 'row': 0}, lookup_index=0), Document(page_content='Team: Reds\n"Payroll (millions)": 82.20\n"Wins": 97', lookup_str='', metadata={'source': './example_data/mlb_teams_2012.csv', 'row': 1}, lookup_index=0)]

got same problem, bro
