### ISSUE TITLE
awadb and azure-ai-vision Version issue

### ISSUE THREAD

**Issue by lorenzom222** [langchain-ai/langchain#6125]
### System Info

Upon the `poetry install -E all ` command, I'm unable to install awadb version or azure-ai-vision specified in pyproject.toml 
awadb = {version = "^0.3.2", optional = true}
azure-ai-vision = {version = "^0.11.1b1", optional = true}

```
Package operations: 1 install, 1 update, 0 removals

  • Updating awadb (0.3.1 -> 0.3.2): Failed

  RuntimeError

  Unable to find installation candidates for awadb (0.3.2)

  at ~/opt/anaconda3/envs/langchain/lib/python3.9/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│ 
       73│             links.append(link)
       74│ 
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│ 
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       80│ 

  • Installing azure-ai-vision (0.11.1b1): Failed

  RuntimeError

  Unable to find installation candidates for azure-ai-vision (0.11.1b1)

  at ~/opt/anaconda3/envs/langchain/lib/python3.9/site-packages/poetry/installation/chooser.py:76 in choose_for
       72│ 
       73│             links.append(link)
       74│ 
       75│         if not links:
    →  76│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       77│ 
       78│         # Get the best link
       79│         chosen = max(links, key=lambda link: self._sort_key(package, link))
```

However I was able to install the  awadb 0.3.1 version.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Freshly install poetry via: curl -sSL https://install.python-poetry.org | python3 -. In Conda venv.
2. After it's installation, Poetry (version 1.5.1), attemped `poetry install -E all ` command
3. Received errors

### Expected behavior

After I installed Poetry, I tried to run poetry install -E all within the langchain directory, however I receive dependencies errors.

**Comment by lnavarette** [comment]
I'm getting the same, did you end up finding a solution? I've tried a few different versions of poetry, all the same error.

**Comment by lorenzom222** [comment]
No, I haven't found any solution unfortunate :/

**Comment by doliawu** [comment]
I encounter the same issue on macOS, but not reproing on Windows WSL.

**Comment by doliawu** [comment]
It seems azure-ai-vision does not support macOS, as mentioned [here].(https://github.com/hwchase17/langchain/blob/560c4dfc98287da1bc0cfc1caebbe86d1e66a94d/docs/extras/modules/agents/toolkits/azure_cognitive_services.ipynb#L12)
