### ISSUE TITLE
getting error: while implementing chatopenai module with gpt-4-0613

### ISSUE THREAD

**Issue by siddhant01** [langchain-ai/langchain#6140]
### System Info

ubuntu
python 3.10.16
langchain 0.0.200

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

ChatOpenAI(
                model_name="gpt-4-0613",
                temperature=self.temperature,
                model_kwargs={
                    "frequency_penalty": self.frequency_penalty,
                    "top_p": self.top_p,
                    "headers": conf.PORTKEY_HEADERS,
                    "user": user_id,
                },
                max_tokens=self.max_tokens,
            )
            
we get error
Error -  Unknown model: gpt-4-0613. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-ada-001, ada, text-babbage-001, babbage, text-curie-001, curie, davinci, text-davinci-003, text-davinci-002, code-davinci-002, code-davinci-001, code-cushman-002, code-cushman-001.

### Expected behavior

it should work

**Comment by Ooho1997** [comment]
![image](https://github.com/hwchase17/langchain/assets/38323944/82243375-a2da-4c49-9169-d44493bfba1e)
You can try to add 0613 model in langchain openai.py
