### ISSUE TITLE
LlamaCpp loading time

### ISSUE THREAD

**Issue by reddiamond1234** [langchain-ai/langchain#6160]
Can I improve loading time of Llama Cpp 7b/13b? I am using LlamaCpp function with LLMChain and RetrievalQA.from_chain_type in my python code.

**Comment by 1b5d** [comment]
I wrote a lib [llm-api](https://github.com/1b5d/llm-api) that you can use to run and tune LlamaCpp (or other models) then integrate with langchain using this lib [langchain-llm-api](https://github.com/1b5d/langchain-llm-api)
