### ISSUE TITLE
TypeError: FAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'score_threshold'

### ISSUE THREAD

**Issue by mitkodi** [langchain-ai/langchain#6167]
### System Info

LnagChain v0.0.200

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create `FAISS` vectorstore
2. Call `as_retriever(search_type='similarity_score_threshold', k=4, search_kwargs={'score_threshold': 0.6})`

### Expected behavior

To not raise error

**Comment by simonfromla** [comment]
Hey there, give #6070 a try to see if it works for you.
