### ISSUE TITLE
Trying to initialize an agent with Cohere and LLM-requiring tool causes a ValidationError

### ISSUE THREAD

**Issue by bair82** [langchain-ai/langchain#617]
This simple piece of code:
```
from langchain.agents import load_tools, initialize_agent
from langchain.llms import Cohere
llm = Cohere(model="xlarge",temperature=0)
tools = load_tools(["serpapi", "llm-math"], llm=llm)
agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
```
Returns this error:
> Traceback (most recent call last):
  File "main.py", line 41, in <module>
    agent = initialize_agent(tools, llm, agent="zero-shot-react-description", verbose=True)
  File "/home/runner/TestLangChain/venv/lib/python3.8/site-packages/langchain/agents/loading.py", line 54, in initialize_agent
    return AgentExecutor.from_agent_and_tools(
  File "/home/runner/TestLangChain/venv/lib/python3.8/site-packages/langchain/agents/agent.py", line 214, in from_agent_and_tools
    return cls(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AgentExecutor
tools -> 1
  cannot pickle '_queue.SimpleQueue' object (type=type_error)

If I initialize an agent with a list of tools which don't require an LLM, there is no error.

**Comment by hwchase17** [comment]
hmm, i tried to replicate but couldnt seem to

heres the google collab i used to try to replicate: https://colab.research.google.com/drive/1xwWxtQkLpzvSsT25KlokRwRHFj2VW8BC?usp=sharing

what's your environment setup? (os, langchain version, pydantic version)

**Comment by bair82** [comment]
Thanks for looking at this!
I'm trying it on Replit. Langchain 0.0.63, pydantic-1.9.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
I tried to update pydantic to 1.10.4, but it's incompatible with replit currently (replit requires typing_extensions >=3.7.4,<4.0.0, pydantic 1.10.4 requires typing_extensions >=4.2.0). Maybe that's the reason.
