### ISSUE TITLE
KeyError: 'content' using `AzureCognitiveSearchRetreiver`

### ISSUE THREAD

**Issue by na-stewart** [langchain-ai/langchain#6171]
### System Info

langchain=0.0.199
Python=3.9.13

### Who Can Help

@eyurtsev
@hwchase17

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [x] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
import os

from langchain.retrievers import AzureCognitiveSearchRetriever

cognitive_search_name = os.environ["AZURE_COGNITIVE_SEARCH_SERVICE_NAME"]
vector_store_address: str = f"https://{cognitive_search_name}.search.windows.net/"
index_name: str = os.environ["AZURE_COGNITIVE_SEARCH_INDEX_NAME"]
vector_store_password: str = os.environ["AZURE_COGNITIVE_SEARCH_API_KEY"]

retriever = AzureCognitiveSearchRetriever(content_key="content")
retriever.get_relevant_documents("what is langchain")
```

### Expected behavior

I am attempting to use `AzureCognitiveSearchRetriever` to no avail. There is little guidance or documentation that I could find to make this functionality work. I don't know what value I'm supposed to set the parameter `content_key` to in order to make this work.

My overall goal is to retrieve data from Azure Cognitive Search and use it to determine the output served by the chatbot based on user query.

Thanks!

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

The `content_key` parameter in the `AzureCognitiveSearchRetriever` is used to specify the key in the retrieved result that should be set as the `Document`'s `page_content`. In your case, you should set the `content_key` parameter to the key in your Azure Cognitive Search index that corresponds to the content you want to retrieve.

For example, if your Azure Cognitive Search index has a field named "text" that contains the content you want to use as `page_content`, you should initialize the `AzureCognitiveSearchRetriever` with `content_key="text"`:

```python
retriever = AzureCognitiveSearchRetriever(content_key="text")
retriever.get_relevant_documents("what is langchain")
```

Make sure to replace "text" with the appropriate key from your Azure Cognitive Search index.

### Sources
- [langchain/retrievers/azure_cognitive_search.py](https://github.com/hwchase17/langchain/blob/master/langchain/retrievers/azure_cognitive_search.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant
