### ISSUE TITLE
Only using GPU:0 for vector embedding.

### ISSUE THREAD

**Issue by Taeuk-Jang** [langchain-ai/langchain#6174]
### System Info

torch.__version__ '2.0.1+cu117'
langchain.__version__ '0.0.199'
transformers.__version__ '4.30.2'

### Who can help?

@hwchase17
@agola11
@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`source_dir = $DIRNAME
splitter = 'tiktoken'
num_similar = 4

emb_name = 'hkunlp/instructor-xl'
encode_kwargs = {'normalize_embeddings': True}

embeddings = HuggingFaceInstructEmbeddings(
    model_name=emb_name,
    model_kwargs={'device':'cuda'},
)

txt_loader = DirectoryLoader(source_dir, glob="**/*.txt")
documents = txt_loader.load()

text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, 
                                             chunk_overlap=max_chunk_overlap,
                                            length_function = len)

documents = text_splitter.split_documents(documents)

vectorstore = Chroma.from_documents(documents, embeddings)
vectorstore.similarity_search(query)
`
or after loading vectorstore

`
retriever = vectorstore.as_retriever(search_type="mmr", search_kwargs={"k":num_similar} )

qa = ConversationalRetrievalChain.from_llm(
    hf_pipeline,
    retriever,
    # condense_question_llm = hf_pipeline, #this can be simpler
    return_source_documents=return_source_documents,
    return_generated_question=True,
    combine_docs_chain_kwargs = {'prompt': QA_PROMPT},
    condense_question_prompt = CONDENSE_QUESTION_PROMPT,
)
`
When we do something like this, even with device_map = 'auto' or 'balanced', we see much higher GPU consumption on GPU:0.

### Expected behavior

So I expect to load vectorDB balanced over all available GPUs like LLM pipelines. But, it only use GPU:0 which makes inefficient usage of VRAM of multiple GPUs.

**Comment by Bongomannn** [comment]
I have a similar problem. With the nearly the same code. 100% of vram used and cuda uses also 100 % of the GPU part 
![grafik](https://github.com/langchain-ai/langchain/assets/145395912/70de7727-979f-4ce3-85c6-c2565871209c)

**Comment by reddiamond1234** [comment]
any progress?

**Comment by dantaninecz** [comment]
Any word on this? I have a similar issue where only one GPU is being utilized.
