### ISSUE TITLE
following contributing.md results in being unable to run make

### ISSUE THREAD

**Issue by kylrth** [langchain-ai/langchain#6182]
### System Info

OS: Ubuntu 20.04 LTS
branch: master
Python: 3.9

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I followed the steps as described in .github/contributing.md:

1. fork the repo
2. clone the fork
3. `conda create -n langchain python=3.9`
4. `conda activate langchain`
5. `pip install -U pip setuptools`
6. `pip install poetry`
7. `poetry completions bash >> ~/.bash_completion`
8. `poetry config virtualenvs.prefer-active-python true`
9. `poetry install -E all` <-- this command failed to unlock the gnome keyring, so I reran according to [poetry#1917](https://github.com/python-poetry/poetry/issues/1917) below:
10. `PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring poetry install -E all`
11. `make format`

Running `make format` results in the following:

```
Traceback (most recent call last):
  File "/home/kyle/.miniconda3/envs/langchain/bin/make", line 5, in <module>
    from scripts.proto import main
ModuleNotFoundError: No module named 'scripts'
```

`which make` returns a `make` script installed in my conda env bin, with the following contents:

```
#!/home/kyle/.miniconda3/envs/langchain/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from scripts.proto import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

I'm not sure what this is. I'm pretty sure I followed the directions correctly.

### Expected behavior

I should be able to run `make format` without a problem at this point.

**Comment by ChrKahl** [comment]
Same here

**Comment by abhinavbh08** [comment]
Same here

**Comment by xznhj8129** [comment]
I installed langchain's requirements on my system instead of a virtual environment. I shouldn't have done that. Everything is broken now...

**Comment by kylrth** [comment]
@hwchase17 sorry to ping but this is probably going to keep a lot of people from contributing. Any idea what's wrong?

**Comment by jedi4ever** [comment]
It seems that the module `tigrisdb` installs make and this is the one confusing it.

`pip list | tail -n +3 | cut -d" " -f1 | xargs pip show -f ` and then grep for bin/make 

```
Name: tigrisdb
Version: 1.0.0b6
Summary: Python SDK for Tigris <http://www.tigrisdata.com>
Home-page: https://www.github.com/tigrisdata/tigris-client-python
Author: Tigris team
Author-email: support@tigrisdata.com
License: Apache-2.0
Location: /opt/homebrew/anaconda3/envs/langchain-repo/lib/python3.9/site-packages
Requires: grpcio-tools, protobuf
Required-by: 
Files:
  ../../../bin/make
  api/generated/google/api/__pycache__/annotations_pb2.cpython-39.pyc
  api/generated/google/api/__pycache__/annotations_pb2_grpc.cpython-39.pyc
  api/generated/google/api/__pycache__/field_behavior_pb2.cpython-39.pyc
  api/generated/google/api/__pycache__/field_behavior_pb2_grpc.cpython-39.pyc
```

doing a simple  `pip uninstall tigrisdb` makes `make` work again :)
Not the permanent solution, but maybe a workaround for now. 
And one step closer to the fix ?

**Comment by jedi4ever** [comment]
related issues:
-  https://github.com/hwchase17/langchain/issues/6915#issuecomment-1613339712
- https://github.com/hwchase17/langchain/issues/6915

**Comment by jedi4ever** [comment]
In the docs is says to do ` export PATH="/Users/some.user/.local/bin:$PATH"`
this would mean it will find the `make` binary of poe env first , we could change it to appending it at the end (which is the usual I guess ?)

` export PATH="$PATH:/Users/some.user/.local/bin"` ?

**Comment by adilansari** [comment]
@jedi4ever @kylrth would removing `tigrisdb` from [dependencies](https://github.com/hwchase17/langchain/blob/master/pyproject.toml#L317) solve the issue?

https://github.com/hwchase17/langchain/blob/931e68692e75ae22ab245c4d8d24b62c1f95cc59/pyproject.toml#L317

**Comment by kylrth** [comment]
I haven't tested it but it sounds like it will, but if that dependency is important for development then it needs to be present, correct? Whatever we do, we need to make the instructions in contributing.md work out of the box.

**Comment by balnarendrasapa** [comment]
I tried uninstalling tigrisdb. It is removing the make. and when i try running make 'no such file or directory' is coming up.

![image](https://github.com/hwchase17/langchain/assets/61614290/ada84833-77a9-447c-9786-60d2723209fa)

**Comment by kylrth** [comment]
The development environment and instructions have changed substantially since this issue, so I'm closing.
