### ISSUE TITLE
AzureChatOpenAI.get_num_tokens_from_messages  does not work

### ISSUE THREAD

**Issue by yoooyle** [langchain-ai/langchain#6200]
### System Info

langchain==0.0.198 and current HEAD

AzureChat inherits from OpenAIChat
![image](https://github.com/hwchase17/langchain/assets/877883/11b94aef-6dd0-4f75-882a-9558b6550c1b)

Which throws on Azure's model name
![image](https://github.com/hwchase17/langchain/assets/877883/fa995f5c-ba8b-4a3b-a877-9981484893dd)

Azure's model name is gpt-35-turbo, not 3.5
![image](https://github.com/hwchase17/langchain/assets/877883/72d716e6-3402-47a3-a3cc-262b3720d8ed)

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. deploy private GPT3.5 on Azure
2. Initialize an AzureChatOpenAI object
3. call get_num_tokens_from_messages
4. observe the exception

### Expected behavior

no exception

**Comment by Hchyeria** [comment]
I encountered the same issue.
`OPENAI_MODEL_NAME = os.getenv("OPENAI_MODEL_NAME", "gpt-35-turbo")`
![image](https://github.com/langchain-ai/langchain/assets/30401991/d3d7980a-f30f-4ed3-9aa4-3e6eba67520d)

**Comment by ellemcfarlane** [comment]
Hi, I ran into this issue with the latest version of langchain (v0.0.335). Please unmark as stale.

**Comment by Hemario** [comment]
This issue still persists in version 0.1.11 of langchain.

**Comment by ties-freeday** [comment]
This issue still exists in version 0.1.45 of langchain:
model "gpt-35-turbo" won't match if statement `elif model.startswith("gpt-3.5-turbo") or model.startswith("gpt-4"):`

**Comment by efriis** [comment]
Hey team! I don't think the `model` parameter gets passed in Azure OpenAI because the hosted model is determined by what is hosted in your azure deployment (specified with deployment_name).

If you pass `model='gpt-3.5-turbo'` instead, I believe it should fix token counting and not impact the azure connection.

Let me know if you experience something different!
