### ISSUE TITLE
On API base URL change, underlying connection doesn't always change.

### ISSUE THREAD

**Issue by berlogb** [langchain-ai/langchain#6202]
### System Info

Version: 0.0.188 (but I don't see any change in the latest master that would fix that)
Python: 3.10
Linux
Problem description:
In one of our environments we have multiple Azure OpenAPI base URLs and have to change them on a fly. We do it by changing LLM within the Chain, basically recreating LLM with the new Base URL, Deployment name and so on, something like this:
   
 ```
llm = AzureChatOpenAI(
        openai_api_base=api_base,
        openai_api_version=api_version,
        deployment_name=deployment_name,
        openai_api_key=api_key,
        openai_api_type="azure",)
```

Unfortunately it doesn't always have an effect, as, apparently most of those parameters are not passed correctly to the OpenAI API, here: https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/openai.py#L294 (def completion_with_retry and def acompletion_with_retry) kwargs don't contain things like base endpoint and so on. It seems to be from some legacy openai implementation when it had to be declared as environmental variable. And basically leads to a situation (time to time, depending on how fast the change is, if concurrently different users use different models, etc.) that base URL will remain the same, while deployment name changes.

To fix this,  I simply added:
```
...
     retry_decorator = _create_retry_decorator(llm)
    try:
        kwargs['api_base'] = llm.openai_api_base
        kwargs['api_key'] = llm.openai_api_key
        kwargs['api_type'] = llm.openai_api_type
        kwargs['api_version'] = llm.openai_api_version
        kwargs['organization'] = llm.openai_organization if llm.openai_organization else None
    except:
        pass
    @retry_decorator
...
```

As it's inside chat_models and openai supports those arguments for chat models, haven't had any problems with it.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce:
1. Have 2 different API Base URLs with different deployment names
2. Create many CoversationChain with AzureChatOpenAI (one per "user" from step#4)
3. Have multiple threads/asyncio (in my specific case, it's behind FastAPI)
4. emulate multiple, parallel calls of CoversationChain.run and then start randomly changing for some user AzureChatOpenAI model pointing to different Base URL and deployment name
5. You will see that some calls will fail, cause deployment name would change but base URL won't (easy to observe by setting logging level to DEBUG)

### Expected behavior

Change of base URL and deployment name should be propagated to the "caller" deterministically and reliably.

**Comment by anderl80** [comment]
I'm experiencing the same issue. @berlogb did you make any progress on the issue, that you could share?

**Comment by anderl80** [comment]
Seems like this works now with the latest release regarding the PR mentioned above. @berlogb can you confirm as well?
