### ISSUE TITLE
No Documentation for constructor parameter client

### ISSUE THREAD

**Issue by sriramr98** [langchain-ai/langchain#6217]
I just started a new project in langchain and when I try to create a OpenAIEmbeddings object, I'm asked for a client which has a type Any. This is not in documentation anywhere and it's hard to figure out what client is required.

It would be amazing if someone can clarify the use-case for this. I would be happy to raise a PR to document this.

## Error Screenshot
![Error Screenshot](https://github.com/hwchase17/langchain/assets/21296041/f992fe12-c541-4fc0-9722-895626a9ac4e)

## Version
![Versions](https://github.com/hwchase17/langchain/assets/21296041/b69b5de7-84bf-4a64-9d5e-208e95b705b6)
s/21296041/7155ffef-acdf-4a21-80d7-4b60484fab93)

https://github.com/hwchase17/langchain/blob/7ad13cdbdbd45b1348f199419da836bdbcbc02e2/langchain/embeddings/openai.py#L108

**Comment by devstein** [comment]
_Generated by a 🤖_ 

I found related issues that might be helpful. I did my best to summarize the solutions, but I recommend looking at the related issues yourself.

## Related Issues
### Open Issues
#### [DOC: client required but not in example code](https://github.com/hwchase17/langchain/issues/5105)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant
