### ISSUE TITLE
Map Reduce in Document Chain within a Conversational Retrieval Chains: Allow a way to determine if sources are relevant in output

### ISSUE THREAD

**Issue by quillan86** [langchain-ai/langchain#6240]
### Feature request

Allow a way within the source documents to determine if identified text in the map step has relevant information that was extracted or not, as well as find the text that was extracted from the sources.

### Motivation

Currently, when the output returns the source documents, it identifies all of the documents for a retriever. However, in map reduce chain, the map step identifies if the source has any relevant text within the source before the reduce step. This information isn't captured anywhere in the final output. I tried mapping a map_reduce chain which included intermediate steps to identify the map steps so I could process to find if the result is relevant or not, but there was a bug because call/acall used run on the document chain, preventing an input.

I'd like to use this information to reduce the number of sources when I cite what information was captured (e.g. if out of 4 sources, 3 sources had relevant information, only cite those sources.) This will help the reliability of the lineage.

### Your contribution

Willing to contribute in this; identified the code necessary to change it

**Comment by sagardesai-ml-mlops** [comment]
I would be willing to contribute. can you add more details?
