### ISSUE TITLE
For AzureOpenAI() wrapper deafault model_name is text-davinci-003

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#6259]
### System Info

If we do not pass the model_name in the AzureOpenAI() wrapper, it picks up text-davinci-003 as the default model which in turn makes the cost calculation of tokens incorrect. Should model_name be made mandatory parameter for AzureOpenAI()

### Who can help?

@hwchase17 
@agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use the AzureOpenAI() wrapper without passing model_name and then do a get_openai_callback() to get the cost

### Expected behavior

It should calculate the cost based on the model name

**Comment by TomTom101** [comment]
For some reason, a LLMChain, that uses AzureOpenAI as llm and is provided with ChatMessages, creates a request that sends a prompt string to the endpoint instead of a list of `messages`.  Still trying to figure out myself what is going on.

**Comment by rajib76** [comment]
This will still be an issue, I see that the default model name now changed to model_name: str = "gpt-3.5-turbo" . So if we do not explicitly pass the model name, cost calculations will be wrong. There is no way to check if deployment name and model name matches.
