### ISSUE TITLE
load_summarize_chain with Pydantic format instructions return cut at the end output (as it stops writing in the middle of the sentence)

### ISSUE THREAD

**Issue by vera2pm** [langchain-ai/langchain#6288]
### System Info

langchain==0.0.201
Python 3.10.8

### Who can help?

@hwchase17, @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I use load_summarize_chain with my own map and reduce prompts to process video transcript and receive chapters of the video and json format. In the intermediate steps there is no problem - all documents are processed well as I can see in created chapters. However after reduce last few chapters are missed and cut off like it suddenly stops writing output.

- The bug often appears when processing long videos: 50 minutes and longer (however rarely they processed without problems). 
- Without output parser (format instructions) it often don't cut off, but can have problems with format.
- Number of tokens after map in my example fewer than 3000 (e.g. 2462, 2704, 2704) so collapse prompt doesn't help.
- Number of tokens of output after reduce is not that big (e.g. 1057, 755). I have examples of bigger results from smaller videos that worked well.

So it is not that output or input for reduce are too big for prompt, because no error about too many values occurs. 
I could not find any other possible reasons for such behavior.

Here the code example:
```
output_parser = PydanticOutputParser(pydantic_object=Chapters)
format_instructions = output_parser.get_format_instructions()
# Unload dict
map_prompt = prompt_config["map_prompt"]
reduce_prompt = prompt_config["reduce_prompt"]
# Initialize templates
map_temp = PromptTemplate(input_variables=["text"], template=map_prompt, partial_variables={"format_instructions": format_instructions})
reduce_temp = PromptTemplate(input_variables=["text"], template=reduce_prompt, partial_variables={"format_instructions": format_instructions})

chain_mapreduce = load_summarize_chain(
        llm,
        chain_type="map_reduce",
        return_intermediate_steps=True,
        map_prompt=map_temp,
        combine_prompt=reduce_temp,
 )
res = chain_mapreduce({"input_documents": docs}, return_only_outputs=True)
```

### Expected behavior

I expect the well formed json output without information loss

**Comment by devstein** [comment]
_Generated by a 🤖_

## Answer

I found related issues that might be helpful. I did my best to summarize the solutions, but I recommend looking at the related issues yourself.
### Related Issues

#### [SummaryChain output cutoff](https://github.com/hwchase17/langchain/issues/1044)
The suggested solution is: Increase max_tokens in the LangChain code.


--- 

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant
