### ISSUE TITLE
Langchain running on 8000 port (and colliding with my API server)

### ISSUE THREAD

**Issue by mhb11** [langchain-ai/langchain#6294]
### System Info

Version: 0.0.170
Platform: Ubuntu 20.04
Python: 3.8.10

### Who can help?

@agol

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

1) Start a uvicorn server at `127.0.0.1:8000` (with your langchain python endpoint).

2) Initialize an agent via the following:
```
agent_chain = initialize_agent(
            tools,
            self.llm,
            agent="conversational-react-description",
            verbose=True,
            memory=self.memory,
            return_intermediate_steps=True,
        )
```

3) Call the agent via `agent_chain(inputs={"input": "sample text"})` through the aforementioned endpoint.

4) The agent gets stuck and never responds back. I have not defined a time out.

5) Upon examination, it seems it got stuck inside `_load_session()` in `LangChainTracerV1()` in `/langchain/callbacks/tracers/langchain_v1.py`. It seems the port for localhost being sent by `get_endpoint()` is `8000` (which collides with our `localhost`)?

### Expected behavior

An output from the agent

**Comment by NijsTom** [comment]
@mhb11 I ran into a similar issue when enabling Langchain tracing with `os.environ['LANGCHAIN_TRACING'] = 'true'` which seems to spawn a server on port 8000. I was using a Django server - also on port 8000, causing an issue.

My solution was to change Django's default port, but another could be to change langchain's tracing server.
