### ISSUE TITLE
Qdrant from LangChain failed

### ISSUE THREAD

**Issue by zhugexinxin** [langchain-ai/langchain#6298]
### System Info

langchain==0.0.202
qdrant-client==1.2.0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
#pip install qdrant-client

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Qdrant
from langchain.document_loaders import TextLoader

loader = TextLoader('../../../state_of_the_union.txt')
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)
payload = {
    'openai_api_base': 'https://xxxxx',
    'openai_api_key': 'xxxx',
    'model': 'text-embedding-ada-002',
}
embeddings = OpenAIEmbeddings(**payload)
qdrant = Qdrant.from_documents(
    docs, embeddings,
    path="./vectorstores/qdrant/storage",
    collection_name="MyCollection",
)
```

get errors:
<img width="1722" alt="image" src="https://github.com/hwchase17/langchain/assets/42615243/2148b8b6-a5a5-487f-8498-8f3d92bd9457">

### Expected behavior

I thought it would be fine, but this error report makes me wonder how to debug

**Comment by devstein** [comment]
_Generated by a 🤖_

## Answer

I found related issues that might be helpful. I did my best to summarize the solutions, but I recommend looking at the related issues yourself.
## Related Issues
### Closed Issues
#### [Qdrant Document object is not behaving correct](https://github.com/hwchase17/langchain/issues/5473)
The suggested solution is: To use the following payload structure for Qdrant:
json
{
    "content_payload_key": "page content from the document",
    "metadata_payload_key": {
        "meta 1": "something",
        "meta 2": "something",
        etc
    }
}
This structure is different from other vector stores like Pinecone and Chroma, but it reflects the structure of the Document in LangChain. The documentation will be improved to state this clearly.
### Open Issues
#### [False "Index not found" messages](https://github.com/hwchase17/langchain/issues/4944)
The suggested solution is: Upgrade chromadb from 0.3.23 to 0.3.25 as it fixed the "Index not found" error for another user. The related commit is [here](https://github.com/chroma-core/chroma/commit/55ae764bf55475560a24c272bb11917b33d68869).

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by kacperlukawski** [comment]
@zhugexinxin The problem seems related to OpenAI embeddings, not Qdrant itself. Are you able to obtain the embeddings without using Qdrant?
