### ISSUE TITLE
DOC: langchain py docs broken fulling on latest

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [langchain-ai/langchain#6312]
### Issue with current documentation:

https://python.langchain.com/en/latest/ gives 404

**Comment by eoriont** [comment]
I get redirected to https://python.langchain.com/docs/get_started/introduction.html which is okay, not sure if this is just me

**Comment by stephenleo** [comment]
> I get redirected to https://python.langchain.com/docs/get_started/introduction.html which is okay, not sure if this is just me

There seems to be many missing functionalities and broken links in these docs. Can we pls bring back the old docs?
