### ISSUE TITLE
Azure OpenAI with deployment_id is not working.

### ISSUE THREAD

**Issue by rennanvoa2** [langchain-ai/langchain#6336]
### System Info

It seems that the library is only supported when the deployment type on AzureOpenAI is an engine. When I try to use a deployment_id which is the new way to deploy models on Azure I can't make it work. 

This code works well outside of long-chain. Note that I am not using an engine here, but the deployment_id :
```
openai.api_type = "azure"
openai.api_key = "MYAPIHERE"
openai.api_base = "https://eastus.api.cognitive.microsoft.com/"
openai.api_version = "2023-05-15"

response = openai.ChatCompletion.create(
    deployment_id="gpt35",
    model="gpt-3.5",
    messages=[
        {"role": "system", "content": "Assistant is a large language model trained by OpenAI."},
        {"role": "user", "content": "Tell me a Joke."}
    ],
    temperature=0.0,
    max_tokens=4000,
    api_key="MYAPIHERE",
    request_timeout=15,
)

print(response['choices'][0]['message']['content'])
```

When I try to use that on langchain AzureOpenAI it doesn't work. I don't know if me doing something wrong or if its the library that doesn't support that. 

Here is the code I am using to test langchain on and that doesn't work:

```
from langchain.llms import AzureOpenAI

import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-03-15"
os.environ["OPENAI_API_BASE"] = "https://eastus.api.cognitive.microsoft.com/"
os.environ["OPENAI_API_KEY"] = "MYAPIKEYHERE"
# Create an instance of Azure OpenAI


# Replace the deployment name with your own
llm = AzureOpenAI(
    model_name="gpt-3.5",
    deployment_id = "gpt35"
)

print(llm("Tell me a joke"))

```

The error is:
```
Exception has occurred: InvalidRequestError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Resource not found
```

Thanks in advance.

### Who can help?

@hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I've sent the code in the question to reproduce the error.

### Expected behavior

I would expect the code to return the response but all I have is an error.

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

It seems that the LangChain's AzureOpenAI class does not support the `deployment_id` parameter out of the box. You can create a custom class that inherits from `AzureOpenAI` and overrides the necessary methods to support the `deployment_id` parameter. Here's an example of how you can do that:

```python
from langchain.llms import AzureOpenAI
from langchain.schema import HumanMessage
import os

os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-03-15-preview"
os.environ["OPENAI_API_BASE"] = "https://eastus.api.cognitive.microsoft.com/"
os.environ["OPENAI_API_KEY"] = "MYAPIKEYHERE"

class CustomAzureOpenAI(AzureOpenAI):
    def __init__(self, model_name: str, deployment_id: str, **kwargs):
        super().__init__(model_name=model_name, **kwargs)
        self.deployment_id = deployment_id

    def __call__(self, *args: Any, **kwargs: Any) -> ChatResult:
        kwargs["deployment_id"] = self.deployment_id
        return super().__call__(*args, **kwargs)

llm = CustomAzureOpenAI(
    model_name="gpt-3.5",
    deployment_id="gpt35"
)

response = llm(
    [
        HumanMessage(content="Tell me a joke")
    ]
)

print(response[0].content)
```

This should resolve the issue and allow you to use the `deployment_id` with LangChain's AzureOpenAI 

### Sources
- [langchain/chat_models/azure_openai.py](https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/azure_openai.py)
- [langchain/embeddings/openai.py](https://github.com/hwchase17/langchain/blob/master/langchain/embeddings/openai.py)
- [langchain/llms/openai.py](https://github.com/hwchase17/langchain/blob/master/langchain/llms/openai.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by mwinterde** [comment]
Hi @rennanvoa2,

Should work if you use `deployment_name` instead of `deployment_id` (which is not supported) as parameter name. See [the API reference](https://api.python.langchain.com/en/latest/modules/llms.html#langchain.llms.AzureOpenAI)  for more details.

**Comment by rennanvoa2** [comment]
@devstein 
Thanks for answering. It seems that I cannot add any attribute to AzureOpenAI class that is not there.
I can modify the Parent class but would it be the best way? 

ValueError: "CustomAzureOpenAI" object has no field "deployment_id"

**Comment by namgizlat** [comment]
thanks, that was helpfull
my issue got resolved once i added the model_name as follow:
llm = AzureChatOpenAI(
        deployment_name="gpt-35-turbo",
        **model_name="GPT3.5",**
        temperature=0,
        verbose=True
    )

**Comment by namgizlat** [comment]
issue  can be closed
