### ISSUE TITLE
Issue: langchain pandas df agent, not taking full df in context

### ISSUE THREAD

**Issue by m-ali-awan** [langchain-ai/langchain#6348]
### Issue you'd like to raise.

HI all,
As can be seen in this screenshot
![SCR-20230617-uajg](https://github.com/hwchase17/langchain/assets/62832721/8bca1a16-4c8d-47a3-8e40-22bd88b3bac8)

I am using pandas_df_agent, but instead of taking whole dataframe, which is around 27000 lines, it is creating itself a Sample data, and doing operations on that.
Isn't it weird, ? Kindly help me with this..

Thanks

**Comment by vowelparrot** [comment]
probably improve the prompt

**Comment by Mumbo-Jumbo-3** [comment]
same issue, have u found a fix?

**Comment by CrasCris** [comment]
Did you find the solution ?
