### ISSUE TITLE
Docusaurus Document Loader

### ISSUE THREAD

**Issue by slavakurilyak** [langchain-ai/langchain#6353]
### Feature request

I propose the integration of a **Docusaurus Document Loader** for the LangChain Python repository. By integrating a **[Docusaurus](https://docusaurus.io/) Document Loader**, we can extend the documentation capabilities of LangChain and provide a more comprehensive resource for developers who use Docusaurus (similar to ReadTheDocs).

### Motivation

My motivation for this feature request is to enhance and extend the document loading functionalities of LangChain. Currently, LangChain [integrates with ReadTheDocs](https://python.langchain.com/docs/modules/data_connection/document_loaders/integrations/readthedocs_documentation), and while this is a powerful tool, incorporating a **Docusaurus Document Loader** can offer an alternative loader. Plus, LangChain docs ([Python](https://python.langchain.com/docs) and [JavaScript)](https://js.langchain.com/docs) are already hosted on Docusaurus.

### Your contribution

As the one initiating this feature request, I am willing to help by creating this issue and providing initial suggestions for the implementation of the **Docusaurus Document Loader**.

**Comment by hwchase17** [comment]
this is a great idea! would love to see this

**Comment by slavakurilyak** [comment]
The [ingest](https://github.com/langchain-ai/chat-langchain/blob/master/ingest.py) pipeline of [chat-langchain](https://github.com/langchain-ai/chat-langchain/) already uses [SitemapLoader](https://python.langchain.com/docs/integrations/document_loaders/sitemap) to load HTML from Docusaurus.

As a result, [Docusaurus](https://github.com/facebook/docusaurus) document loader would make a meaningful impact on LangChain and unlock new doc-focused workflows.

As a result, I'm re-opening this issue.

**Comment by slavakurilyak** [comment]
Merged via https://github.com/langchain-ai/langchain/pull/9138
