### ISSUE TITLE
DOC: Updating documentation relating to Models->llms->integrations->*

### ISSUE THREAD

**Issue by bhashithe** [langchain-ai/langchain#6356]
### Issue with current documentation:

The page I am referring with this issue is [Llama.cpp](https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp.html). I am hoping to update the documentation regarding some windows specific instructions which others might find useful.

I've forked the repo and my working changes I would push there and make a pull request here.

I understand that to do this; `langchain/docs/_dist/docs_skeleton/docs/modules/model_io/models/llms/integrations/llamacpp.ipynb` needs to be updated.

It also appears that `docs/_dist` is now ignored by `.gitignore`.

Could you please let me know if I am looking in the wrong place? If so please correct me.

**Comment by dev2049** [comment]
could you check to see if the page is updated now? there was a sep bug a week ago

**Comment by bhashithe** [comment]
It is not updated yet.

Did you check the pull request? It seems like the vercel deployment is broken.

**Comment by bhashithe** [comment]
@dev2049 If you can grant me write access, I would be able to clean up the documentation around many model integrations. This is why pull request is not passing.
