### ISSUE TITLE
The cost calculation of tokens for open ai models looks like is only considering output tokens

### ISSUE THREAD

**Issue by rajib76** [langchain-ai/langchain#6358]
### System Info

I am using gpt-3.5-turbo for which the price of the tokens are as below

4K Context
0.0015/1K tokens - for input
0.002/1k tokens - output

From the call back I get the below

Cost and token usage :Tokens Used: 222
	Prompt Tokens: 171
	Completion Tokens: 51
Successful Requests: 1
Total Cost (USD): $0.00044400000000000006

Going by the pricing, it should be 0.000375942

It looks like the program is only looking at output cost

### Who can help?

@agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

run the LLM with callback using any of the open ai models

        with get_openai_callback() as cb:
            response = chat_chain.predict(input=_input.to_string())

            print(response)
            resp_json = out_parser.parse(response)

            print("Cost and token usage :{cb}".format(cb=cb))

            return resp_json

### Expected behavior

The cost calculation should consider the input tokens also

**Comment by Danny-Hoang** [comment]
Nice

**Comment by stephenleo** [comment]
I think the fix is relatively straightforward. Shall I submit a PR for it?

**Comment by rajib76** [comment]
I see that a fix has been pushed into the repo for this

**Comment by stephenleo** [comment]
The latest release probably included the fix..!

**Comment by kyle-cheung** [comment]
sorry semi-related, how do i get the tokens input output from using llm.predict?

**Comment by manuel-84** [comment]
there are also open issues for counting tokens when embeddings is called for indexing and for when streaming=true

tried any workaround mentioned, for indexing is working fine, but for ConversationalRetrievalChain with streaming enabled and custom condense_question_llm still haven't found a solution that matches the openai usage log

**Comment by rajib76** [comment]
This can be closed
