### ISSUE TITLE
Support for Redis Cluster

### ISSUE THREAD

**Issue by ankushbbbr** [langchain-ai/langchain#6361]
### Feature request

The current python client `langchain.vectorstores.redis` lacks support for RedisCluster. Handling redirection with try-expect on receiving `MOVED` error also doesn't work in this case because the code `Redis.from_documents(docs, llmembeddings, redis_url=redis_url, index_name=index_name)` internally makes more calls to Redis, which eventually throw MOVED error because the client is not configured for RedisCluster.

### Motivation

As users of Redis Cluster at Salesforce, we aim to integrate it seamlessly and develop a chatbot powered by LLM. Enabling Redis API support in the Vector Redis Client would enhance performance, streamline development workflows, and provide a unified client library for interacting with Redis databases. We believe this addition would greatly benefit our organization and the wider community utilizing Redis in their applications.

### Your contribution

We will look at adding RedisCluster support in langchain vector client.

**Comment by haldes** [comment]
Hi @ankushbbbr - Any high level ETA on this ?

**Comment by Spartee** [comment]
@ankushbbbr as a former (self-proclaimed haha) redis cluster power user (https://github.com/CrayLabs/SmartSim) I can totally understand wanting cluster support. However, using both in the same library can also bring in a whole bunch of headaches. It's better now that redis-py-cluster is built into redis-py, but the coordinator, replica, and client logic is entirely different for OSS cluster. Don't even get me started on testing. Starting a redis cluster in a github action is a gigantic pain. We're trying to move to stability of this interface, and this would greatly complicate things.

This all said, this is why people use Redis Cloud. It has a built in proxy for dealing with the clustered commands so you only ever need a single shard python client. It just makes life (development) significantly easier. 

Feel free to contact me if you want some help. sam(dot)partee(at)redis(dot)com
