### ISSUE TITLE
The chatCompletion operation does not work with the specified model appears when I use AzureChatOpenAI, but it does exist

### ISSUE THREAD

**Issue by biao-lvwan** [langchain-ai/langchain#6363]
### Issue you'd like to raise.

openai.error.InvalidRequestError: The chatCompletion operation does not work with the specified model, text-embedding-ada-002. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.

**Comment by devstein** [comment]
_Answer generated by a 🤖_

### Answer
The error message you received indicates that you are trying to use the `text-embedding-ada-002` model with the chatCompletion operation, which is not supported. The chatCompletion operation currently supports only `gpt-3.5-turbo` and `gpt-3.5-turbo-0301` models.
To fix the issue, you should change the model in your code to one of the supported models. For example, you can replace `"model": "text-embedding-ada-002"` with `"model": "gpt-3.5-turbo"` in your code.

Here's the corrected code snippet:
```javascript
const completion = await openai.createChatCompletion({
  model: "gpt-3.5-turbo",
  messages: [{role: "user", content: "Hello world"}],
});
console.log(completion.data.choices[0].message);
```

### Sources

- [docs/extras/modules/chains/additional/openai_openapi.yaml](https://github.com/hwchase17/langchain/blob/master/docs/extras/modules/chains/additional/openai_openapi.yaml)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by biao-lvwan** [comment]
My model is usable in completion, but it is no longer usable when integrating with Langchain. I am not sure if Azure cannot use text embedding ada-002, as I have read the official statement


![image](https://github.com/hwchase17/langchain/assets/66588660/344ec91e-fa58-48c9-8213-4751444ca4c0)

**Comment by bpkapkar** [comment]
Even we are getting the error with  gpt35 InvalidRequestError: The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.  

Running below code:
from langchain.agents import create_csv_agent, create_pandas_dataframe_agent
llm=AzureOpenAI(deployment_name="XXX",model_name="gpt-35-turbo",openai_api_version="2023-05-15",openai_api_base="https://{name}.openai.azure.com/", openai_api_key=token.token,openai_api_type = "azure_ad")
agent = create_pandas_dataframe_agent(llm, df, verbose=False)
agent.run("Question")
