### ISSUE TITLE
Issue:current not support gpt-3.5-turbo-0613 model

### ISSUE THREAD

**Issue by mz100814** [langchain-ai/langchain#6368]
### Issue you'd like to raise.

execute method modelname_to_contextsize had an exception~! online 546 "Unknown model: gpt-3.5-turbo-0613. Please provide a valid OpenAI model name."

source code location:langchain/llms/openai.py(BaseOpenAI.modelname_to_contextsize)

**Comment by Ooho1997** [comment]
You can update it

`pip install --upgrade langchain`

**Comment by mz100814** [comment]
> You can update it
> 
> `pip install --upgrade langchain`

![image](https://github.com/hwchase17/langchain/assets/22016077/7979f142-8927-47a6-85a4-973bde76823a)
already update ,but not work.and the langchain source code is not contain the model"gpt-3.5-turbo-0613";

**Comment by mz100814** [comment]
ValueError: Unknown model: gpt-3.5-turbo-0613. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-0301, text-ada-001, ada, text-babbage-001, babbage, text-curie-001, curie, davinci, text-davinci-003, text-davinci-002, code-davinci-002, code-davinci-001, code-cushman-002, code-cushman-001

**Comment by Ooho1997** [comment]
![image](https://github.com/hwchase17/langchain/assets/38323944/a2698a3b-bc5a-4406-9abc-6ede1ffa0123)
I also see that the 0613 model is not included in openai.py, I solved this problem after updating langchain
