### ISSUE TITLE
Text Chunks are 1/2 the token length specified when using split text with CharacterTextSplitter.from_tiktoken_encoder and separator=" "

### ISSUE THREAD

**Issue by StarXR** [langchain-ai/langchain#6373]
### System Info

langchain-0.0.202
Python 3.11.0
Windows 10 Pro

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Use `CharacterTextSplitter.from_tiktoken_encoder` and set the separator to `" "`, and the chunk size to anything
2. Split some text using `split_text`
3. Notice that the resulting chunked text is nearly half the token length specified by the chunk size
```py
import tiktoken
from langchain.text_splitter import CharacterTextSplitter

lorem_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Integer quis auctor elit sed vulputate. Quis blandit turpis cursus in hac. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et."

text_splitter = CharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=100, chunk_overlap=0, separator=" ", model_name="gpt-3.5-turbo"
)

texts = text_splitter.split_text(lorem_text)

encoding = tiktoken.encoding_for_model("gpt-3.5-turbo")
print(len(encoding.encode(texts[0]))) # 44 Tokens ; expected around 100
```

### Expected behavior

I would expect the resulting text chunks after splitting to be around 100 tokens.

I think the issue arises from text_splitter.py, commit #1511 : lines 135 and 160. `total += _len + (separator_len if len(current_doc) > 1 else 0)` assumes that the separator (in this case " ") is it's own token, but I think " " is often combined with the characters next to it. From the tokenizer webpage from OpenAI : 
![image](https://github.com/hwchase17/langchain/assets/16768177/f6f4a856-c7fb-40d5-bf95-5b7761b81524)

You can see that for the " " and "d" from "dolor" are combined into one token, instead of always being separate as assumed by the above `total`.

**Comment by vowelparrot** [comment]
Good catch. Ya tokenization frequently gloms whitespace and adjacent chars. I could review a PR if you have a fix out.

**Comment by SDcodehub** [comment]
how will be knowing for which character it will combine with whitespace and which wont, e.g. " " and "i" are not combined in single token.

so are there any rules for it?

**Comment by blacksmithop** [comment]
Issue still persists in the current version of langchain. Split documents are off from actual token count by a noticeable count

**Comment by atastats** [comment]
> Same issue working with .from_huggingface_tokenizer method

Issue occurs when using instructor embeddings tokenizer. If I use GPT2 embeddings as mentioned [here](https://python.langchain.com/docs/modules/data_connection/document_transformers/split_by_token#hugging-face-tokenizer) it works.
