### ISSUE TITLE
deeplake version should be = 3.6.3, but you've installed 3.6.4. Consider changing deeplake version to 3.6.3 

### ISSUE THREAD

**Issue by mwaikul** [langchain-ai/langchain#6379]
### System Info

Hello,
I am trying to connect to Deeplake to add documents  but am tting the error.
ValueError: deeplake version should be = 3.6.3, but you've installed 3.6.4. Consider changing deeplake version to 3.6.3 

username = "myuser"
db = DeepLake(dataset_path=f"hub://myuser/mydb", embedding_function=embeddings)
db.add_documents(texts)

I am executing this from a collab note book. Code was working fine until yesterday.
I ran this code this morning that might have updated deeplake.
!pip install --upgrade langchain deeplake

Thanks
-Milind 

### Who can help?

@eyurtsev  and @hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Update you deeplake package to 3.6.4
2. Try to create a new db in deeplake with some smaple docs

### Expected behavior

you will get the error:
ValueError: deeplake version should be = 3.6.3, but you've installed 3.6.4. Consider changing deeplake version to 3.6.3

**Comment by eeveepp** [comment]
if version != "3.6.2":
            raise ValueError(
                "deeplake version should be = 3.6.3, but you've installed"
                f" {version}. Consider changing deeplake version to 3.6.3 ."
            )
@hwchase17 I think there's a bug in the code.

**Comment by mwaikul** [comment]
Does it need to be (logically) 
if version < "3.6.2":
            raise ValueError(
                "deeplake version should be > 3.6.2, but you've installed"
                f" {version}. Consider changing to latest stable build > 3.6.2 ."
            )

**Comment by mwaikul** [comment]
Quick updated
I installed version 3.6.3 of deeplake and I am still getting a error 
ValueError: deeplake version should be = 3.6.3, but you've installed 3.6.3. Consider changing deeplake version to 3.6.3 
I think we need to use a utility like packaging.version.parse to compare versions.
https://packaging.pypa.io/en/latest/version.html#packaging.version.parse

**Comment by davidbuniat** [comment]
Apologize for the error, it has been addressed in the PR https://github.com/hwchase17/langchain/pull/6383
