### ISSUE TITLE
Azure OpenAI token authenticate issue.

### ISSUE THREAD

**Issue by Hotomoderato** [langchain-ai/langchain#6412]
### System Info

Hi, I try to use my comany's token as api key for initializing AzureOpenAI, but it seems like token contains an invalid number of segments, have you encountered the same problem before?

`python
# authenticate to Azure
credentials = ClientSecretCredential(const.TENANT_ID, const.SERVICE_PRINCIPAL, const.SERVICE_PRINCIPAL_SECRET)
token = credentials.get_token(const.SCOPE_NON_INTERACTIVE)

openai.api_type = "azure_ad"
openai.api_key = token.token
openai.api_base = f"{const.OPENAI_API_BASE}/{const.OPENAI_API_TYPE}/{const.OPENAI_ACCOUNT_NAME}"
openai.api_version = const.OPENAI_API_VERSION

llm = AzureOpenAI(deployment_name=dep.GPT_35_TURBO, openai_api_version=const.OPENAI_API_VERSION, openai_api_key=openai.api_key)

llm("Tell me a joke")`
openai.error.AuthenticationError: invalid token provided: token contains an invalid number of segments

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

credentials = ClientSecretCredential(const.TENANT_ID, const.SERVICE_PRINCIPAL, const.SERVICE_PRINCIPAL_SECRET)
token = credentials.get_token(const.SCOPE_NON_INTERACTIVE)

openai.api_type = "azure_ad"
openai.api_key = token.token
openai.api_base = f"{const.OPENAI_API_BASE}/{const.OPENAI_API_TYPE}/{const.OPENAI_ACCOUNT_NAME}"
openai.api_version = const.OPENAI_API_VERSION

llm = AzureOpenAI(deployment_name=dep.GPT_35_TURBO, openai_api_version=const.OPENAI_API_VERSION, openai_api_key=openai.api_key)

llm("Tell me a joke")

### Expected behavior

I hope llm can correctly invoke the Azure OpenAI service.

**Comment by dmenini** [comment]
The api key is a 30ish char-long string that you can find on your company's azure platform, where the deployment is. The JWT token is something different required for personal auth

**Comment by ab6995** [comment]
I am facing the same issue when I change openai.api_type from "azure" to "azure_ad" it throws back authentication error.

For me its working with direct call using openai with below snippet:
variables:
# openai.api_key =  token
openai.api_type = "azure_ad"
openai.api_base = api_base
openai.api_version = "2023-05-15"


response = openai.Completion.create(
            engine="gpt-35-turbo",
            prompt='tell me a joke'
        )

But getting authentication error with :
  from langchain.llms import OpenAI
  openai_llm = OpenAI(engine="text-davinci-003", temperature=0.9, verbose=True)
  openai_llm("tell me a joke")


How can we resolve authentication error when using azure_ad as the api_type?

**Comment by ab6995** [comment]
setting these variable and code below solved the authentication error for me:

os.environ["OPENAI_API_KEY"] = token
os.environ["OPENAI_API_VERSION"] = "2023-05-15"

from langchain.llms import AzureOpenAI
openai_llm = AzureOpenAI(engine="text-davinci-003",
                         api_type="azure_ad",
                         temperature=0.9, verbose=True)
openai_llm("tell me a joke")
