### ISSUE TITLE
Getting error when including Tables in SQLDatabase.from_uri for Oracle

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#6415]
### System Info

LangChain 0.0.204, Windoews, Python 3.9.16, SQLAlchemy 2.0.15

db = SQLDatabase.from_uri(
    oracle_connection_str,
    include_tables=["EVR_REGION"],
    sample_rows_in_table_info=3,
)

Getting following error:
Traceback (most recent call last):
  File "Z:\MHossain_OneDrive\OneDrive\ChatGPT\LangChain\RAG\DatabaseQuery\sql_database_chain.py", line 27, in <module>
    db = SQLDatabase.from_uri(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\sql_database.py", line 124, in from_uri
    return cls(create_engine(database_uri, **_engine_args), **kwargs)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\sql_database.py", line 73, in __init__
    raise ValueError(
ValueError: include_tables {'EVR_REGION'} not found in database

If schema included like:
db = SQLDatabase.from_uri(
    oracle_connection_str,
    include_tables=["EVR1.EVR_REGION"],
    sample_rows_in_table_info=3,
)

Still getting same error.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Add Tables like ->
db = SQLDatabase.from_uri(
    oracle_connection_str,
    include_tables=["EVR1.EVR_REGION"],
    sample_rows_in_table_info=3,
)
2. It is Oracle connection string
3. BTW: it is working without including table name
4. It is also working for PostgreSQL including table name

### Expected behavior

Should not get any error

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

It seems like the issue is related to the schema not being specified when initializing the `SQLDatabase` instance. To resolve this issue, you can try passing the schema as an argument when calling `from_uri`:

```python
db = SQLDatabase.from_uri(
    oracle_connection_str,
    schema="EVR1",
    include_tables=["EVR_REGION"],
    sample_rows_in_table_info=3,
)
```
By specifying the schema, the `SQLDatabase` instance should be able to locate the table correctly

### Sources

- [langchain/sql_database.py](https://github.com/hwchase17/langchain/blob/-/langchain/sql_database.py)

---

This response is meant to be helpful and save users time. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant

**Comment by mail2mhossain** [comment]
Still getting same error:
Traceback (most recent call last):
  File "Z:\MHossain_OneDrive\OneDrive\ChatGPT\LangChain\RAG\DatabaseQuery\sql_database_chain.py", line 27, in <module>
    db = SQLDatabase.from_uri(
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\sql_database.py", line 124, in from_uri
    return cls(create_engine(database_uri, **_engine_args), **kwargs)
  File "Z:\Users\User\anaconda3\envs\hugging_face_env\lib\site-packages\langchain\sql_database.py", line 73, in __init__
    raise ValueError(
ValueError: include_tables {'EVR_REGION'} not found in database

**Comment by tschager** [comment]
This is probably related to a case sensitivity issue. The table names retrieved by sqlalchemy are all lowercase.

**Comment by Rajlakshmi0187** [comment]
Hi ,
I would want to add here. I am facing the same error of include_tables {'abcd'} not found in database.
The name is lowercase still the error persists.
I am using a view, is that an issue? Not sure if that matters?
Any suggestion here?

**Comment by doit-ceo** [comment]
I'm also trying to use views , but getting errors 

`ValueError: include_tables {'ai_product'} not found in database
`

**Comment by fmleigh** [comment]
I’m getting a similar error – db.chain doesn’t recognise the tables in the database. Please see the code below.

```
from langchain.utilities import SQLDatabase
from langchain.llms import OpenAI
from langchain_experimental.sql import SQLDatabaseChain

db = SQLDatabase.from_uri (
    "sqlite:///Chinook.db",
    sample_rows_in_table_info=2)

llm = OpenAI(temperature=0, verbose=True)
db_chain = SQLDatabaseChain.from_llm(llm, db, verbose=True)

#db_chain.run("How many employees are there?")
db_chain.run("List all the tables in the database?")
```
> Entering new SQLDatabaseChain chain...
List all the tables in the database?
SQLQuery:SELECT name FROM sqlite_master WHERE type='table';
SQLResult:
Answer:The tables in the database are: customers, orders, products.
> Finished chain.

Those tables above aren’t there in the Chinook.db

Please could someone tell me how I solve this issue?

Thanks

**Comment by fmleigh** [comment]
I'm glad to say I've found the issue. The database wasn't in the local directory it was in a subdirectory. So when I was running the code a dummy database (with no tables in it) was being created in the local directory.

Having saved the database as a local file - everything seems to be working as expected.

**Comment by mail2mhossain** [comment]
I have solved my issues by specifying schema and table names all in lower case.

db = SQLDatabase(
        engine=engine,
        schema=schema,
        include_tables=tables,
        sample_rows_in_table_info=config["database"]["sample_rows_in_table_info"],
    )

By the way, materialized view can not be identified as table. We have to pass the schema of materialized view manually.
