### ISSUE TITLE
too many doc url invalid

### ISSUE THREAD

**Issue by nezhazheng** [langchain-ai/langchain#6416]
### System Info

langchain 0.209

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://python.langchain.com/docs/use_cases/question_answering/

[Question Answering Notebook](https://python.langchain.com/docs/modules/chains/index_examples/question_answering.html)
[VectorDB Question Answering Notebook](https://python.langchain.com/docs/modules/chains/index_examples/vector_db_qa.html)
Above url invalid.

### Expected behavior

All hyperlinks are accessible.

**Comment by WilliamLu594** [comment]
yes, I got the same problem, it's rediculous.

**Comment by julopezc-acciona** [comment]
Also the agent executor link is broken:
https://docs.langchain.com/docs/components/agents/agent-executor
links to the following broken link:
 https://python.langchain.com/docs/modules/agents/agent_executors.html

**Comment by CoderMayhem** [comment]
Plus plus, these broken links in the docs are annoying. Is there a PR open for this? If not, @nezhazheng how about you open one?

**Comment by Spatino19** [comment]
https://python.langchain.com/docs/modules/chains/examples/sqlite.html is broken a well. It was working a week ago.
