### ISSUE TITLE
gpt-3.5-turbo-0613 is not following the instructions of agents

### ISSUE THREAD

**Issue by nithinjp1997** [langchain-ai/langchain#6418]
### System Info

Langchain == 0.0.205
Python == 3.10.7
openai == 0.27.8

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [x] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use gpt-3.5-turbo-0613 
In a chat-conversational-react-description agent ask "could you tell me more about the tools you have ?"

### Expected behavior

The Human message instructs the llm to give the output in a json format but that is not followed.
Here is the output with gpt-3.5-turbo:
![image](https://github.com/hwchase17/langchain/assets/61446944/df830023-99f0-4833-aa85-c283459cbe41)

Here is the output with gpt-3.5-turbo-0613:
![image](https://github.com/hwchase17/langchain/assets/61446944/8fbc2778-41d6-413f-b39c-c4835ef7488a)

**Comment by agokrani** [comment]
Did you find the solution for this? I am having same problem with conversational agent

**Comment by nithinjp1997** [comment]
I think if the format instructions are passed as a system message rather than a human message it should work . I am not so sure on how to do that . Was hoping someone from langchain would help out @hwchase17

**Comment by agokrani** [comment]
I think they are passing this as a system message, if I am not wrong. I added an extra line below the format: 

"Remember this format is important!!!" 
It works for specific prefixes, but if I modify the prefix, it's going back to its behavior. 

@hwchase17, can you help? Also, is it a good idea to have a custom tool designed just for formatting lists in the output? For example, the output might contain a prefix, a list of recommendations, and a suffix. Is it okay to have a tool that just formats the list in python format?

**Comment by geriang** [comment]
Hi everyone, 

i am facing the exact same issue too. Need help.
The agent only followed the system prompt message for the first run only. For 2nd and subsequent runs, it stopped following the required format of Question => Thought => Action => Auction Input => Observation => Thought => Final Answer.
Please see the console.log below: 

<First Run that followed the above mentioned format>
Jun 29 12:35:14 PM  [llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:ChatOpenAI] [3.25s] Exiting LLM run with output: {
Jun 29 12:35:14 PM    "generations": [
Jun 29 12:35:14 PM      [
Jun 29 12:35:14 PM        {
**Jun 29 12:35:14 PM          "text": "Question: What can I help you with today?\nThought: The user has greeted me, so I should respond politely and ask how I can assist them.\nAction:\n```json\n{\n  \"action\": \"chatting_tool\",\n  \"action_input\": {\n    \"input\": \"Hello! How can I assist you today?\"\n  }\n}\n```",**
Jun 29 12:35:14 PM          "message": {
Jun 29 12:35:14 PM            "type": "ai",
Jun 29 12:35:14 PM            "data": {
Jun 29 12:35:14 PM              "content": "Question: What can I help you with today?\nThought: The user has greeted me, so I should respond politely and ask how I can assist them.\nAction:\n```json\n{\n  \"action\": \"chatting_tool\",\n  \"action_input\": {\n    \"input\": \"Hello! How can I assist you today?\"\n  }\n}\n```",
Jun 29 12:35:14 PM              "additional_kwargs": {}
Jun 29 12:35:14 PM            }
Jun 29 12:35:14 PM          }
Jun 29 12:35:14 PM        }
Jun 29 12:35:14 PM      ]
Jun 29 12:35:14 PM    ],

<Second run which did not follow the specified format in the system prompt>
Jun 29 12:37:25 PM  [llm/end] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:ChatOpenAI] [1.41s] Exiting LLM run with output: {
Jun 29 12:37:25 PM    "generations": [
Jun 29 12:37:25 PM      [
Jun 29 12:37:25 PM        {
**Jun 29 12:37:25 PM          "text": "I am an AI assistant designed to help answer questions and provide assistance. How can I assist you today?",**
Jun 29 12:37:25 PM          "message": {
Jun 29 12:37:25 PM            "type": "ai",
Jun 29 12:37:25 PM            "data": {
Jun 29 12:37:25 PM              "content": "I am an AI assistant designed to help answer questions and provide assistance. How can I assist you today?",
Jun 29 12:37:25 PM              "additional_kwargs": {}
Jun 29 12:37:25 PM            }
Jun 29 12:37:25 PM          }
Jun 29 12:37:25 PM        }
Jun 29 12:37:25 PM      ]
Jun 29 12:37:25 PM    ],

**Comment by geriang** [comment]
Just an update on a discovery...when I remove memory feature from the "structured-chat-zero-shot-react-description" type of agent, it follows instructions correctly.

**Comment by agokrani** [comment]
I can confirm this. However, I am not really sure why this is the case and what could be done to make it work. For my case, memory is quite important to hold the context of the conversation. 
Any ideas on improving prompts?
