### ISSUE TITLE
cannot import name 'create_citation_fuzzy_match_chain' from 'langchain.chains'

### ISSUE THREAD

**Issue by MMMKKK888** [langchain-ai/langchain#6439]
### System Info

ImportError: cannot import name 'create_citation_fuzzy_match_chain' from 'langchain.chains'

Python=3.11.4
Langchain=0.0.129

The code:
`from langchain.chains import create_citation_fuzzy_match_chain`

The error

> ImportError: cannot import name 'create_citation_fuzzy_match_chain' from 'langchain.chains'

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chains import create_citation_fuzzy_match_chain

### Expected behavior

ImportError: cannot import name 'create_citation_fuzzy_match_chain' from 'langchain.chains

**Comment by kdcokenny** [comment]
do `pip install langchain==0.0.205` and it will import correctly. Your version of langchain is outdated.
