### ISSUE TITLE
Can't use SQLdatabasechain with Multipromptchain

### ISSUE THREAD

**Issue by kami41** [langchain-ai/langchain#6444]
### System Info

Can't use sqldatabasechains with multipromptchain like this
`

facing this error
`ValidationError: 20 validation errors for MultiPromptChain
destination_chains -> table_format -> prompt
  none is not an allowed value (type=type_error.none.not_allowed)
destination_chains -> table_format -> llm
  none is not an allowed value (type=type_error.none.not_allowed)
destination_chains -> table_format -> database
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> input_key
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> llm_chain
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> query_checker_prompt
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> return_direct
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> return_intermediate_steps
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> top_k
  extra fields not permitted (type=value_error.extra)
destination_chains -> table_format -> use_query_checker
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> prompt
  none is not an allowed value (type=type_error.none.not_allowed)
destination_chains -> ans_format -> llm
  none is not an allowed value (type=type_error.none.not_allowed)
destination_chains -> ans_format -> database
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> input_key
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> llm_chain
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> query_checker_prompt
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> return_direct
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> return_intermediate_steps
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> top_k
  extra fields not permitted (type=value_error.extra)
destination_chains -> ans_format -> use_query_checker
  extra fields not permitted (type=value_error.extra)`

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`table_template = """template 2"""
ans_template = """ template 1"""

prompt_infos = [
    {
        "name": "table_format",
        "description": "Good for answering questions if user asks to generate a table",
        "prompt_template": table_template
    },
    {
        "name": "ans_format",
        "description": "Good for answering questions if user don't asks for any specific format",
        "prompt_template": ans_template
    }
]

llm = OpenAI(temperature=0, model="text-davinci-003", max_tokens=1000)
sqlalchemy_url = f'sqlite:///../../../../notebooks/Chinook.db'
db = SQLDatabase.from_uri(sqlalchemy_url, view_support=True)

destination_chains = {}
for p_info in prompt_infos:
    name = p_info["name"]
    prompt_template = p_info["prompt_template"]
    prompt = PromptTemplate(template=prompt_template, input_variables=["input"], validate_template=False)
    chain = SQLDatabaseChain.from_llm(llm, db, verbose=True, prompt=prompt, use_query_checker=True, top_k=20)
    destination_chains[name] = chain
default_chain = ConversationChain(llm=llm, output_key="text")

destinations = [f"{p['name']}: {p['description']}" for p in prompt_infos]
destinations_str = "\n".join(destinations)
router_template = MULTI_PROMPT_ROUTER_TEMPLATE.format(
    destinations=destinations_str
)
router_prompt = PromptTemplate(
    template=router_template,
    input_variables=["input"],
    output_parser=RouterOutputParser(),
    validate_template=False
)
router_chain = LLMRouterChain.from_llm(llm, router_prompt)
chain = MultiPromptChain(router_chain=router_chain, destination_chains=destination_chains, default_chain=default_chain, verbose=True)
print(chain.run("Give me top 5 stock codes in a table format"))

### Expected behavior

While compiling above code SQLdatabasechain returning this payload at the end `llm=None database=<langchain.sql_database.SQLDatabase object at 0x7f5842b369e0> prompt=None top_k=20 input_key='query' output_key='result' return_intermediate_steps=False return_direct=False use_query_checker=True query_checker_prompt=None`  which raising error when Multipromptchain line executes

**Comment by aduchon** [comment]
See if this works for you and let me know.

 `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain`

`router_chain = MultiSqlChain.from_prompts(llm=llm, db=db, prompt_infos=prompt_infos, verbose=True)`

**Comment by AnnKatrineGC** [comment]
Hi @aduchon,

I encountered a similar issue as kami41 mentioned earlier. I attempted to access the extension you developed for MultiSqlChain by following the github link, but unfortunately, I couldn't locate the documentation.

Could you please assist me in finding the documentation for the MultiSqlChain extension? 

I would greatly appreciate it.

**Comment by Boopalanoptisol** [comment]
> pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain

When i try to execute this getting error

**Comment by rymoore** [comment]
Same issue here

**Comment by aduchon** [comment]
Sorry I haven't had more time to work on this.   I merged master back into my fork.  So maybe now it will work.
From the first comment, replace `MultiPromptChain` with `MultiSqlChain`. There is no documentation as yet, it just mimics the format of the MultiPromptChain.

**Comment by rymoore** [comment]
what namespace is this in? 
`cannot import name 'MultiSQLChain' from 'langchain.chains.router'`

**Comment by kami41** [comment]
> what namespace is this in? `cannot import name 'MultiSQLChain' from 'langchain.chains.router'`

I think it should be 
`from langchain.chains.router.multi_sql import MultiSQLChain`

**Comment by rymoore** [comment]
got `ModuleNotFoundError: No module named 'langchain.chains.router.multi_sql'`

**Comment by kami41** [comment]
Bro install this `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain` before running above

**Comment by Boopalanoptisol** [comment]
If Suppose User enters the general question instead of querying database how can we check the intermediate steps or Print the Logs in which prompt template it gives the result?
Any help would be appreciated.

**Comment by rymoore** [comment]
> Bro install this `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain` before running above

Have done this, @kami41  same result 
<img width="1247" alt="2023-07-20_07-12-19" src="https://github.com/hwchase17/langchain/assets/13695135/6f010351-0198-4bb4-9cfd-b02c7c3b4be9">

**Comment by Boopalanoptisol** [comment]
> See if this works for you and let me know.
> 
> `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain`
> 
> `router_chain = MultiSqlChain.from_prompts(llm=llm, db=db, prompt_infos=prompt_infos, verbose=True)`

Bro If the User enters the genreal Question insted of questions related to database  how can we route them to the LLM chain instead of the sql database chain

**Comment by kami41** [comment]
> > Bro install this `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain` before running above
> 
> Have done this, @kami41 same result <img alt="2023-07-20_07-12-19" width="1247" src="https://user-images.githubusercontent.com/13695135/254879347-6f010351-0198-4bb4-9cfd-b02c7c3b4be9.png">

go to this link "https://github.com/aduchon/langchain.git" change branch from master to 6444-multisqlchain. Goto langchain>chains>router there you see multi_sql.py and multi_sql_prompt.py. download both and place in the same directory  where your langchain installed in your local pc

**Comment by Boopalanoptisol** [comment]
> See if this works for you and let me know.
> 
> `pip install -e git+https://github.com/aduchon/langchain.git@6444-multiSQLchain#egg=langchain`
> 
> `router_chain = MultiSqlChain.from_prompts(llm=llm, db=db, prompt_infos=prompt_infos, verbose=True)`

Hi @aduchon 

Can we pass destination_chains: Mapping[str, SQLDatabaseChain,LLMChain]   like this.

I need to Check if the name is empty the need to Check in the LLMchain as in multiprompt . Can we acheive like this or anyother Suggestions, for acheiving that.

**Comment by janimeet** [comment]
Hi @aduchon Getting this error while running MultiSqlChain.

File ~\Anaconda3\envs\myenv\lib\site-packages\langchain\chains\base.py:389, in Chain.prep_inputs(self, inputs)
    387     external_context = self.memory.load_memory_variables(inputs)
    388     inputs = dict(inputs, **external_context)
--> 389 self._validate_inputs(inputs)
    390 return inputs

File ~\Anaconda3\envs\myenv\lib\site-packages\langchain\chains\base.py:147, in Chain._validate_inputs(self, inputs)
    145 missing_keys = set(self.input_keys).difference(inputs)
    146 if missing_keys:
--> 147     raise ValueError(f"Missing some input keys: {missing_keys}")

ValueError: Missing some input keys: {'query'}
