### ISSUE TITLE
DOC: Is it possible to access older documentation UI?

### ISSUE THREAD

**Issue by sbarman-mi9** [langchain-ai/langchain#6452]
### Issue with current documentation:

I had links for the older documentation and now all those links are broken. It was easy to figure out version as well. It would be great if we could access the older UI.

Thanks.

**Comment by Darshan2104** [comment]
True, I also got confused a bit after UI update.
@hwchase17  if it is possible, can you please proved the option to switch to the old UI?

Also, I'm not able to see all the reference Researcher papers used by Langchain :(  
They were placed properly, section-wise, in the old UI.

**Comment by mirodrr** [comment]
Also wondering this
