### ISSUE TITLE
Issue: how to load csv without headers

### ISSUE THREAD

**Issue by MIMI180306** [langchain-ai/langchain#6460]
### Issue you'd like to raise.

There may be no header in my csv. CSVLoader seems to take the first row of data as a header, resulting in the missing of the first row of data. How to solve this problem

**Comment by abhinavbh08** [comment]
You can specify the headers of the CSV like this `csv_args={'fieldnames': ['column1', 'column2', 'column3']}` depending on the number of columns in your file. By default, it takes the first row as headers but if we specify the field names, then it takes the field names as headers and your first row will not be missed.
