### ISSUE TITLE
Issue: <Some problems when using ChatOpenAI>

### ISSUE THREAD

**Issue by Isfate** [langchain-ai/langchain#6461]
### Issue you'd like to raise.

When using ChatOpenAI, will ChatOpenAI save the conversation history? When I use the same data many times to call a service built with langchain, after a fixed number of times, a langchain.schema.OutputParserException error occurs, which seems to be The answer returned by OpenAI is incomplete. Based on my experience of using other GPT models, it tells me that this is because the dialogue history recorded by the model is too long, causing the answer and the token of the dialogue history to exceed the length of the model limit. How should I avoid this problem? , or how should I start a new conversation or clear the conversation history after the ChatOpenAI conversation ends.

**Comment by Avinash-Raj** [comment]
You could just do `memory.clear()` for clearing message history.

**Comment by dmenini** [comment]
I'm not sure that the context is the problem. My understanding is that when the context window is exceeded, OpenAI returns InvalidRequestError with code 'context_length_exceeded'.

**Comment by jimkaselouris** [comment]
Or you could use ConversationBufferWindowMemory and specify how many past messages are passed to memory (default is 5), so you somehow control the memory token length. 

from langchain.memory import ConversationBufferWindowMemory
memory = ConversationBufferWindowMemory(memory_key="chat_history", return_messages=True)
