### ISSUE TITLE
pdf-parse.d.ts not found when using PDFLoader

### ISSUE THREAD

**Issue by RitvikShandilya** [langchain-ai/langchain#6471]
### System Info

{
  "name": "server-chatgpt",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "dist/app.js",
  "scripts": {
    "start": "tsc & node dist/app.js",
    "dev": "tsc -w & nodemon -x 'node dist/app.js || touch dist/app.js'",
    "dev2": "tsc -w & pm2 start dist/app.js --watch",
    "log": "pm2 log",
    "stop": "pm2 stop app",
    "lint": "eslint . --ext .ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/cors": "^2.8.13",
    "@types/express": "^4.17.17",
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.59.6",
    "eslint": "^8.41.0",
    "nodemon": "^2.0.22",
    "pm2": "^5.3.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  },
  "dependencies": {
    "@types/node": "^20.3.1",
    "@types/pdf-parse": "^1.1.1",
    "body-parser": "^1.20.2",
    "chatgpt": "^5.2.4",
    "chromadb": "^1.5.2",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "hnswlib-node": "^1.4.2",
    "langchain": "^0.0.95",
    "openai": "^3.2.1",
    "pdfjs-dist": "^3.7.107",
    "pg": "^8.11.0",
    "typeorm": "^0.3.16",
    "uuid": "^9.0.0"
  }
}

### Who can help?

@eyurtsev @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When "npm run dev" is executed, I get an error saying node_modules/langchain/dist/document_loaders/fs/pdf.d.ts:1:22 - error TS6053: /node_modules/langchain/src/types/pdf-parse.d.ts' not found.

/// <reference path="../../../src/types/pdf-parse.d.ts" />

This error comes when I try to import { PDFLoader } from "langchain/document_loaders/fs/pdf";

tsconfig:
{
    "compilerOptions": {
      "module": "NodeNext",
      "esModuleInterop": true,
      "target": "es6",
      "moduleResolution": "nodenext",
      "sourceMap": true,
      "outDir": "dist",
      "resolveJsonModule": true,
      "allowJs": true
    },
    "lib": ["es2015"]
  }
  

### Expected behavior

no error is expected as pdf-parse is already installed, similar issue with pdfjs-dist

**Comment by kdcokenny** [comment]
This repo is for python. This is the js/ts library -> https://github.com/hwchase17/langchainjs

**Comment by glenchao** [comment]
`"skipLibCheck": true` in tsconfig should get you unblocked
