### ISSUE TITLE
Missing GPU support? HuggingFace model too slow

### ISSUE THREAD

**Issue by billy-mosse** [langchain-ai/langchain#648]
Hi! Amazing work :). I was trying to use this library to test a LLM called GPT-JT but I got a timeout error:
> ValueError: Error raised by inference API: Model togethercomputer/GPT-JT-6B-v1 time out

I'm running this in a quite powerful server, and resources shouldn't be an issue. The code is probably not using GPU, but I haven't found a way for making `langchain` use GPU. Could you please tell me if this is automatic, and if I'm missing something?

Code for reproducibility:
```
from langchain import PromptTemplate, HuggingFaceHub, LLMChain

template = """Question: {question}

Answer: Let's think step by step."""
prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=HuggingFaceHub(repo_id="togethercomputer/GPT-JT-6B-v1"))

question = "Is an apple a fruit?"
print(llm_chain.run(question))
```

**Comment by nafizh** [comment]
I am actually facing the same problem. Sentencebert models are not using local GPU. I did not see any option to enable GPU in the API.

**Comment by thepok** [comment]
i have a working prototype with gpu support

https://github.com/hwchase17/langchain/pull/410

**Comment by RobinSrimal** [comment]
Hi Team, I discovered your work yesterday and it looks really cool. Have you considered integrating Haystack (https://haystack.deepset.ai/overview/intro) into your project? It seems like they are solving some of the issues that you are are working on.

**Comment by billy-mosse** [comment]
@thepok, would you mind pasting a sample snippet for using gpu? I want to checkout your branch and start using it

**Comment by thepok** [comment]
```
 from langchain.llms import Accelerate
 model_name = "facebook/opt-30b"
 FastLLM = Accelerate.from_model_name(model_name=model_name)
 print(FastLLM("Hello World"))
```

**Comment by francistotle** [comment]
I get errors when running the code above
```
Traceback (most recent call last):
  File "/home/francis/langchain/langchain/llms/accelerate.py", line 110, in from_model_name
    model = cls.get_accelerated_gpt(model_name)
  File "/home/francis/langchain/langchain/llms/accelerate.py", line 54, in get_accelerated_gpt
    from accelerate import (
ModuleNotFoundError: No module named 'accelerate'
```

**Comment by thepok** [comment]
chatgtp could have solved that one! "No module named 'accelerate'" you have to install accelerate.

**Comment by annabechang** [comment]
> chatgtp could have solved that one! "No module named 'accelerate'" you have to install accelerate.

could you show/ point me to where i can find how to install accelerate? thank you

**Comment by dusvyat** [comment]
@annabechang https://huggingface.co/docs/accelerate/basic_tutorials/install
