### ISSUE TITLE
`get_relevant_documents` of Chroma retriever uses cosine distance instead of cosine similarity as similarity score

### ISSUE THREAD

**Issue by labdmitriy** [langchain-ai/langchain#6481]
### System Info

LangChain version: 0.0.205
Platform: Ubuntu 20.04 LTS
Python version: 3.10.4

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

**Steps to reproduce**
- Reproduce section in Similarity Score Threshold Retrieval in tutorial [Vector store-backed retriever](https://python.langchain.com/docs/modules/data_connection/retrievers/how_to/vectorstore) with Chroma instead of FAISS as vector store, then we will get incorrect results and get only less relevant documents instead of the most ones.

**Possible reason**
- `db.get_relevant_documents()` [calls](https://github.com/hwchase17/langchain/blob/df40cd233f0690c1fc82d6fc0a1d25afdd7fdd42/langchain/vectorstores/base.py#L393-L398) `db.similarity_search_with_relevance_scores()` for `search_type="similarity_score_threshold"`.

- In `db.similarity_search_with_relevance_scores()` we can see the following [description](https://github.com/hwchase17/langchain/blob/df40cd233f0690c1fc82d6fc0a1d25afdd7fdd42/langchain/vectorstores/base.py#L127-L129):
> Return docs and relevance scores, normalized on a scale from 0 to 1.
> **0 is dissimilar, 1 is most similar.**

- `db.similarity_search_with_relevance_scores()` finally calls `db.similarity_search_with_score()`, which has the following [description](https://github.com/hwchase17/langchain/blob/df40cd233f0690c1fc82d6fc0a1d25afdd7fdd42/langchain/vectorstores/chroma.py#L201-L211C51):
> Run similarity search with Chroma with distance.
> ...
> **Lower score represents more similarity.**

- So when `score_threshold` is [used](https://github.com/hwchase17/langchain/blob/df40cd233f0690c1fc82d6fc0a1d25afdd7fdd42/langchain/vectorstores/base.py#LL155-L159) in `db.similarity_search_with_relevance_scores()`:
``` python
docs_and_similarities = [
    (doc, similarity)
    for doc, similarity in docs_and_similarities
    if similarity >= score_threshold
]
```
Then the filter will retain only the **less** relevant docs, not the most ones, because cosine distance is used as similarity score, which is not correct.

**Related issues**
- #4517
- #6046

### Expected behavior

Cosine similarity instead of cosine distance must be used as similarity score.

**Comment by hanit-com** [comment]
I will open a PR that fixes that.

**Comment by batmanscode** [comment]
Great catch! Perhaps there's an opportunity to create a new function to return the least relevant docs

**Comment by olegshirokikh** [comment]
Similar issue with Pinecone Cosine Similarity, which is converted back to distance - filtering out relevant documents when using score_threshold -- https://github.com/langchain-ai/langchain/issues/8207

**Comment by dsantiago** [comment]
It seems that for Chroma, you should set the distance metric when creating a colllecion: https://docs.trychroma.com/usage-guide#changing-the-distance-function

The default distance in Chroma is `l2`. I use this function in my toy project:

```python
# Save to Chroma
def save_chroma(db_name, docs, embeddings, path="./chroma_db"):
  db = Chroma.from_documents(collection_name=db_name, 
                             documents=docs, 
                             embedding=embeddings, 
                             persist_directory=path, 
                             collection_metadata={"hnsw:space": "cosine"})
  db.persist()
  return db
```

**Comment by adrienohana** [comment]
The default distance metric is indeed 'l2' which is often not suitable for many top-performing models.

Unfortunately @dsantiago's solution does not work currently (collection_metadata is not used anywhere in the code)

#6570 left some unimplemented sub class functions and we need to update them for Chroma (exactly like it is done for FAISS here : https://github.com/langchain-ai/langchain/blob/8c35fcb571eeedcb9edf82e0cdc48e072e322205/libs/langchain/langchain/vectorstores/faiss.py#L719C2-L746) 

I might work on a PR at some point

**Comment by dsantiago** [comment]
> Unfortunately @dsantiago's solution does not work currently (collection_metadata is not used anywhere in the code)

Seriously! Omg.

**Comment by adrienohana** [comment]
> @adrienohana
> 
> > Unfortunately @dsantiago's solution does not work currently (collection_metadata is not used anywhere in the code)
> 
> Seriously! Omg.

Actually after digging the docs for a couple hours I realised your solution works ! When working with jupyter notebooks, re-running Chroma.from_documents many times without restarting the Kernel often leads to a corrupted database. 

My bad and thanks for sharing !

**Comment by dsantiago** [comment]
Ohh ok, but i really didn't dig it. In my mind if there was collection_metadata option, it was being sent to Chroma's collection object.
