### ISSUE TITLE
DOC: Documentation links for the ClickHouse integration is broken

### ISSUE THREAD

**Issue by kellytoole** [langchain-ai/langchain#6484]
### Issue with current documentation:

https://t.co/QcsorxSzSG

https://twitter.com/LangChainAI/status/1666093323780767746

The sections in docs where the ClickHouse integration is covered (as a vector db) no longer load properly. The links (above) are broken, and you can no longer navigate to the ClickHouse section from docs directly.

**Comment by haoch** [comment]
@hwchase17 May we know why the clickhouse vector store documentation and notebook were gone in master branch?

**Comment by kellytoole** [comment]
Original ticket: https://github.com/hwchase17/langchain/pull/5650

**Comment by haoch** [comment]
@kellytoole It seems resolved now: https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/clickhouse.html
