### ISSUE TITLE
sitemap loader : got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by heikog** [langchain-ai/langchain#6521]
### System Info

langchain-0.0.207, osx, python 3.11

Hi @eyurtsev

I am using this example from the docs
and get the error below .
Any idea ? im kind of stuck.

Seems to work with version 202 - everything above seems broken

`TypeError: ClientSession._request() got an unexpected keyword argument 'verify'
`

```
from langchain.document_loaders.sitemap import SitemapLoader
sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml")

docs = sitemap_loader.load()

sitemap_loader.requests_per_second = 2
# Optional: avoid `[SSL: CERTIFICATE_VERIFY_FAILED]` issue
sitemap_loader.requests_kwargs = {"verify": True}
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

run code mentioned above

### Expected behavior

the sitemap loader should return a list of documents

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

The issue seems to be caused by the use of the `verify` keyword argument in the `requests_kwargs` dictionary. The aiohttp library, which is used by LangChain, does not use the `verify` keyword argument for SSL verification. Instead, it uses `ssl` keyword argument.

To fix the issue, you can change the `verify` keyword to `ssl` in the `requests_kwargs` dictionary:

```python
from langchain.document_loaders.sitemap import SitemapLoader
sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml")

docs = sitemap_loader.load()

sitemap_loader.requests_per_second = 2
# Optional: avoid `[SSL: CERTIFICATE_VERIFY_FAILED]` issue
sitemap_loader.requests_kwargs = {"ssl": True}
```

This should resolve the `TypeError` you are encountering.

### Sources
- [langchain/document_loaders/sitemap.py](https://github.com/hwchase17/langchain/blob/-/langchain/document_loaders/sitemap.py)

---

This response is meant to be helpful and give you a place to start. It is not meant to be a precise solution.

Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

**Comment by heikog** [comment]
thanks for the quick response. Appreciate you looking into it @devstein but it seems not to fix it.
Different keyword - same error :-)
Any other suggestion ?

Traceback (most recent call last):
  File "/Users/heiko/Documents/GitHub/SiteSavvy/createIndexFromSitemap.py", line 61, in <module>
    docs = loader.load()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/sitemap.py", line 120, in load
    soup = self.scrape("xml")
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/web_base.py", line 198, in scrape
    return self._scrape(self.web_path, parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/langchain/document_loaders/web_base.py", line 188, in _scrape
    html_doc = self.session.get(url, verify=self.verify, **self.requests_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.request() got an unexpected keyword argument 'ssl'

**Comment by heikog** [comment]
thanks @devstein I will try this out in the coming days and come back. right now it somehow worked for me to downgrade langchain and I want to finish some work before digging deeper into it. Appreciate you feedback

**Comment by arunchinnachamy** [comment]
Hi, I am also facing the same issue. I tried your suggestions,
```
    sitemap_loader = SitemapLoader(web_path="https://langchain.readthedocs.io/sitemap.xml", verify=False)
TypeError: __init__() got an unexpected keyword argument 'verify'
```

I tried the following to fix the error. I edited the file `venv/lib/python3.9/site-packages/langchain/document_loaders/web_base.py` and removed `verify=self.verify` from lines 113 and 188

Looks like session.get does not take the paramter verify anymore. I am not sure about the right way to fix this.

**Comment by arunchinnachamy** [comment]
This issue is caused by the latest commit - https://github.com/hwchase17/langchain/commit/2eec687474252cd8083da09ccc5ac5bf89a59611

Can you help me if this has something to do with requests version? I do not see the session.get having verify option in latest requests lib as well.

**Comment by arunchinnachamy** [comment]
The fix is being discussed here. https://github.com/hwchase17/langchain/pull/6519

**Comment by JustinXre2020** [comment]
![image](https://github.com/hwchase17/langchain/assets/66919694/661a4695-8ee2-4d3e-b183-14f8f3513202)
I still have this error when running the instruction code from LangChain document in my Jupyter Notebook.
