### ISSUE TITLE
Issue: <Please write a comprehensive title after the 'Issue: ' prefix>

### ISSUE THREAD

**Issue by marcomameli1992** [langchain-ai/langchain#6543]
### Issue you'd like to raise.

I try to use this code:

`from langchain.agents import create_csv_agent
from langchain.llms import AzureOpenAI

agent = create_csv_agent(AzureOpenAI(temperature=0,  deployment_name="text-davinci-003"), 'data.csv', sep='|', on_bad_lines='skip', verbose=True)

print(agent.run("how many rows are there?"))`

but when I execute them I obtain a ParserError: 

pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 679, saw 2

but if I try to open the same file with pandas.read_csv function I do not have any error.

Can you help me please?

Thank you

**Comment by TomTom101** [comment]
It's an error in your CSV data, in row 679. Try a simpler CSV with only few lines that you can easily verify to be correct.
