### ISSUE TITLE
Pre-built tool list

### ISSUE THREAD

**Issue by florence26** [langchain-ai/langchain#6586]
### Issue with current documentation:

I haven't been able to find any documentation on a comprehensive list of pre-built tools available on Langchain, for example, there is nothing in the documentation that suggests we're able to load the "llm-math" tool?

### Idea or request for content:

It would be good to have a list of all pre-built tools!

**Comment by ayushrathore111** [comment]
hii @florence26 I want to work on this please assign this to me 
thank you...
