### ISSUE TITLE
DOC: RecursiveTextSplitter function doesn't exist

### ISSUE THREAD

**Issue by ubernion** [langchain-ai/langchain#6589]
### Issue with current documentation:

https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter

this function isn't to be found in the text_splitter.py file :

from langchain.text_splitter import RecursiveCharacterTextSplitter

this returns an error.

**Comment by ChrisWangSJ** [comment]
Hello, I got the same problem, did you fix it?
