### ISSUE TITLE
RetrievalQA.from_chain_type does not release GPU memory when given ChromaDB context

### ISSUE THREAD

**Issue by JasonMaggard** [langchain-ai/langchain#6608]
### System Info

When querying with no context (emptyStore below) GPU memory goes up to 8GB and after the chain completes, GPU memory goes back down to 630MB.

When using a ChromaDB to provide vector context, GPU memory is never released. Memory usage goes up to 8GB and stays there. Once enough calls have been made, the program will crash with an out of memory error.

I have tried manually deleting the variables associated with the DB and langchain, running garbage collection... I am unable to free this GPU memory. Is there a manual method to free this memory that I could employ or some other workaround?

I started with using langchain 201 and noticed the issue. The issue persists when using the latest 209.

```
def queryGpt(query):
    # Get our llm and embeddings
    llm = get_llm()
    embeddings = get_embeddings()
    # Even if the user does not specify a vector store to use, it is necessary
    # to pass in a retriever to the RetrievalQA chain.
    docs = [
        Document(page_content=""),
        Document(page_content=""),
        Document(page_content=""),
        Document(page_content=""),
    ]
    emptyStore = Chroma.from_documents(docs)
    retriever = emptyStore.as_retriever()

    if request.content_type == "application/json":
        data = request.get_json()
        store_id = data.get("store_id")
        store_collection = data.get("store_collection")
        if store_id and store_collection:
            vector_stores = load_vector_stores()
            found: VectorStore | None = None
            for store in vector_stores:
                if store["id"] == store_id:
                    found = store
            if not found:
                print(f"Warning: vector store not found id:{store_id}")
            else:
                # print(f"Using vector store '{found['name']}' id:{found['id']} collection {store_collection}")
                client = get_chroma_instance(found["dirname"])
                # embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                db = Chroma(
                    client=client,
                    embedding_function=embeddings,
                    collection_name=store_collection,
                )
                retriever = db.as_retriever()
    print('Answering question')
    qa = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=retriever)

    # Get the answer from the chain
    res = qa(query)
```

We are using the latest Vicuna 13b. With `all-MiniLM-L6-v2` used for the embeddings.

We are in Azure using Tesla GPU's. Ubuntu 20.04. Cuda 12.1.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run a QA chain with a ChromaDB enabled.

### Expected behavior

I would expect the memory to be freed upon completion of the chain.

**Comment by AgentJ-WR** [comment]
Can confirm this is happening to me as well.

**Comment by gsachdev-adeptia** [comment]
I am also facing the same. Replacing ChromaDb with FAISS did fix the issue. It seems that it is specific to ChromaDB usage only.

**Comment by scottpatrickwright** [comment]
I haven’t replicated this however it seems important. It appears to make ChromaDB a non starter for gpu accelerated apps. A comment from the team on priority for this issue would be helpful.

Chroma looks great I’d rather leverage it than not but it would be good to know there is a solve in the works.

**Comment by Dmfama20** [comment]
> I am also facing the same. Replacing ChromaDb with FAISS did fix the issue. It seems that it is specific to ChromaDB usage only.

Can confirm that it happens with Chroma but for me it also happens with FAISS. 
I.e. i switched to the FAISS DB via
db = FAISS.from_documents(docs, embeddings)
but the used GPU memory still rises by every query I do.

@gsachdev-adeptia : How do you manage to solve this?

**Comment by ahmadmehrbod** [comment]
I tested both Chroma and FIASS using CPU, and still the same problem. Should be somewhere else

**Comment by zShanCS** [comment]
I have used both Chroma and Faiss-cpu.

Both never free up RAM.

I tried deleting the documents manually using the langchain vector store's delete(ids) method, and it does appear to delete the documents but RAM isnt freed.

Any help would be appreciated.

**Comment by pingusix** [comment]
I'm seeing the same thing with Chromadb.

Deleting the model object, calling torch.cuda.empty_cache() and gc.collect() doesn't seem to do anything.

Trying to use a hacky call to numba to free the GPU memory works using the code below  but then triggers a pytorch error the next time torch  I try to load the a model (CUDA error: invalid argument)

Any ideas greatly appreciated as this is causing me to pull out my few remaining hairs.

device = numbacuda.get_current_device()
device.reset()
numbacuda.close()

**Comment by nordanz** [comment]
Same problem here with FAISS, anybody found a solution?

**Comment by SunYong0821** [comment]
anyone found a solution？？？
