### ISSUE TITLE
Critical Vulnerability Blocking Deployment

### ISSUE THREAD

**Issue by lppier** [langchain-ai/langchain#6627]
### System Info

Langchain 0.0.209, Python 3.8.17
https://security.snyk.io/vuln/SNYK-PYTHON-LANGCHAIN-5725807

Hi, we are deploying an app in our environment to production with langchain as one of the packages. 
Today, on Snyk this critical vulnerability showed up, and as a result we're blocked from deploying as Snyk flagged this out as critical. 

Are there any plans to fix this soon? 

Thank you very much. 
<img width="1383" alt="image" src="https://github.com/hwchase17/langchain/assets/1635202/81aa2179-7c10-4f3c-9fa4-11042f43a9be">

### Who can help?
@hwchase17 @dev2049 @vowelparrot  @bborn @Jflick58 @duckdoom4 @verm

_No response_

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

My requirements.txt

#
# This file is autogenerated by pip-compile with Python
# by the following command:
#
#    pip-compile --allow-unsafe --output-file=requirements.txt --resolver=backtracking requirements.in
#
aioboto3==11.2.0
    # via python-commons
aiobotocore[boto3]==2.5.0
    # via aioboto3
aiohttp==3.8.4
    # via
    #   aiobotocore
    #   langchain
    #   openai
aioitertools==0.11.0
    # via aiobotocore
aiosignal==1.3.1
    # via aiohttp
alembic==1.10.4
    # via -r requirements.in
anyio==3.7.0
    # via
    #   httpcore
    #   starlette
    #   watchfiles
async-timeout==4.0.2
    # via
    #   aiohttp
    #   langchain
asyncpg==0.27.0
    # via -r requirements.in
attrs==23.1.0
    # via
    #   aiohttp
    #   pytest
boto3==1.26.76
    # via aiobotocore
botocore==1.29.76
    # via
    #   aiobotocore
    #   boto3
    #   s3transfer
certifi==2023.5.7
    # via
    #   httpcore
    #   httpx
    #   python-commons
    #   requests
cffi==1.15.1
    # via cryptography
charset-normalizer==3.1.0
    # via
    #   aiohttp
    #   python-commons
    #   requests
click==8.1.3
    # via uvicorn
coverage==7.2.7
    # via pytest-cov
cryptography==41.0.1
    # via
    #   pyopenssl
    #   python-commons
dataclasses-json==0.5.8
    # via langchain
dnspython==2.3.0
    # via email-validator
email-validator==1.3.1
    # via -r requirements.in
exceptiongroup==1.1.1
    # via anyio
fastapi==0.95.2
    # via -r requirements.in
frozenlist==1.3.3
    # via
    #   aiohttp
    #   aiosignal
greenlet==2.0.2
    # via sqlalchemy
gunicorn==20.1.0
    # via python-commons
h11==0.14.0
    # via
    #   httpcore
    #   uvicorn
httpcore==0.17.2
    # via httpx
httptools==0.5.0
    # via uvicorn
httpx==0.24.1
    # via python-commons
idna==3.4
    # via
    #   anyio
    #   email-validator
    #   httpx
    #   requests
    #   yarl
iniconfig==2.0.0
    # via pytest
jmespath==1.0.1
    # via
    #   boto3
    #   botocore
langchain==0.0.209
    # via -r requirements.in
langchainplus-sdk==0.0.16
    # via langchain
loguru==0.7.0
    # via python-commons
mako==1.2.4
    # via alembic
markdown-it-py==3.0.0
    # via rich
markupsafe==2.1.3
    # via mako
marshmallow==3.19.0
    # via
    #   dataclasses-json
    #   marshmallow-enum
marshmallow-enum==1.5.1
    # via dataclasses-json
mdurl==0.1.2
    # via markdown-it-py
multidict==6.0.4
    # via
    #   aiohttp
    #   yarl
mypy-extensions==1.0.0
    # via typing-inspect
numexpr==2.8.4
    # via langchain
numpy==1.24.3
    # via
    #   -r requirements.in
    #   langchain
    #   numexpr
openai==0.27.8
    # via -r requirements.in
openapi-schema-pydantic==1.2.4
    # via langchain
packaging==23.1
    # via
    #   marshmallow
    #   pytest
pluggy==1.2.0
    # via pytest
py==1.11.0
    # via pytest
pycparser==2.21
    # via cffi
pydantic==1.10.9
    # via
    #   fastapi
    #   langchain
    #   langchainplus-sdk
    #   openapi-schema-pydantic
    #   python-commons
pygments==2.15.1
    # via rich
pyopenssl==23.2.0
    # via python-commons
pytest==6.2.5
    # via
    #   -r requirements.in
    #   pytest-asyncio
    #   pytest-cov
    #   pytest-mock
pytest-asyncio==0.18.3
    # via -r requirements.in
pytest-cov==2.12.1
    # via -r requirements.in
pytest-mock==3.6.1
    # via -r requirements.in
python-commons @ ## masked internal repo ## 
    # via -r requirements.in
python-dateutil==2.8.2
    # via botocore
python-dotenv==1.0.0
    # via
    #   -r requirements.in
    #   uvicorn
pyyaml==6.0
    # via
    #   langchain
    #   uvicorn
regex==2023.6.3
    # via tiktoken
requests==2.31.0
    # via
    #   langchain
    #   langchainplus-sdk
    #   openai
    #   tiktoken
rich==13.4.2
    # via python-commons
s3transfer==0.6.1
    # via boto3
six==1.16.0
    # via python-dateutil
sniffio==1.3.0
    # via
    #   anyio
    #   httpcore
    #   httpx
sqlalchemy[asyncio]==2.0.16
    # via
    #   -r requirements.in
    #   alembic
    #   langchain
sse-starlette==1.6.1
    # via -r requirements.in
starlette==0.27.0
    # via
    #   fastapi
    #   python-commons
    #   sse-starlette
tenacity==8.2.2
    # via
    #   langchain
    #   langchainplus-sdk
tiktoken==0.4.0
    # via -r requirements.in
toml==0.10.2
    # via
    #   pytest
    #   pytest-cov
tqdm==4.65.0
    # via openai
typing-extensions==4.6.3
    # via
    #   aioitertools
    #   alembic
    #   pydantic
    #   sqlalchemy
    #   starlette
    #   typing-inspect
typing-inspect==0.9.0
    # via dataclasses-json
urllib3==1.26.16
    # via
    #   botocore
    #   python-commons
    #   requests
uvicorn[standard]==0.21.1
    # via
    #   -r requirements.in
    #   python-commons
uvloop==0.17.0
    # via uvicorn
watchfiles==0.19.0
    # via uvicorn
websockets==11.0.3
    # via uvicorn
wrapt==1.15.0
    # via aiobotocore
yarl==1.9.2
    # via aiohttp

# The following packages are considered to be unsafe in a requirements file:
setuptools==68.0.0
    # via
    #   gunicorn
    #   python-commons

### Expected behavior

Critical vulnerability would have to be fixed for us to deploy, thanks.

**Comment by inpaner** [comment]
Related issue: https://github.com/hwchase17/langchain/issues/4849

**Comment by JohnsonKoh1110** [comment]
I'm experiencing this too, pls help.

**Comment by spashii** [comment]
https://github.com/hwchase17/langchain/blob/980c8651743b653f994ad6b97a27b0fa31ee92b4/langchain/prompts/loading.py#L144C2-L155

The use of `exec()` allows Arbitrary Code Execution in the above file

My recommendation to mitigate this vulnerability:
1. Disabling the execution of arbitrary Python code from prompts. Use only JSON or YAML. 
2. Implementing a strict whitelist or validation mechanism for external prompts.

**Comment by bongtavas** [comment]
Facing the same issue. Hope this gets resolved soon!

**Comment by Jflick58** [comment]
PR created. Hopefully this gets resolved soon!

**Comment by lppier** [comment]
> PR created. Hopefully this gets resolved soon!

Pinging @hwchase17 for your attention/discussion!

**Comment by JamalRahman** [comment]
Related issue: #4833

**Comment by aiakubovich** [comment]
same problem

**Comment by obi1kenobi** [comment]
Hi all! The linked vulnerability is resolved as of `langchain v0.0.225` and I can see the snyk database entry has been updated to show that information as well.

Sorry for the delayed response. We're working on improving the way we approach making and publishing security fixes so that critical communication like this flows better and is more reliably propagated to security advisory databases as well. Otherwise, it can often incorrectly seem like some issues haven't been fixed even though the fix has been published and available for a long time already. For example, the fix for this issue went live in `v0.0.225` on July 5, nearly two months ago.

Thanks for bearing with us on this!
