### ISSUE TITLE
'ConversationSummaryMemory' has no attribute 'from_messages'

### ISSUE THREAD

**Issue by jbkoh** [langchain-ai/langchain#6636]
### System Info

Ubuntu 20.04
Python 3.10
langchain 0.0.166

### Who can help?

@hwchase17 @agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

This code is retrieved from the official website
https://python.langchain.com/docs/modules/memory/how_to/summary#initializing-with-messages

```python

from langchain.memory import ConversationSummaryMemory, ChatMessageHistory
from langchain.llms import OpenAI
from dotenv import load_dotenv

load_dotenv()

history = ChatMessageHistory()
history.add_user_message("hi")
history.add_ai_message("hi there!")
memory = ConversationSummaryMemory.from_messages(llm=OpenAI(temperature=0), chat_memory=history, return_messages=True)
```

The above code will throw out an exception
```
AttributeError: type object 'ConversationSummaryMemory' has no attribute 'from_messages'
```

I guess the class method has been deprecated?

### Expected behavior

It passes.

**Comment by devstein** [comment]
_Generated by a 🤖_

### Answer

It seems like there is a mismatch between the provided code and the context. The from_messages class method is present in the ConversationSummaryMemory class in the provided context. You can try the following code:

```python
from langchain.memory import ConversationSummaryMemory, ChatMessageHistory
from langchain.llms import OpenAI
from dotenv import load_dotenv

load_dotenv()

history = ChatMessageHistory()
history.add_user_message("hi")
history.add_ai_message("hi there!")
memory = ConversationSummaryMemory.from_messages(llm=OpenAI(temperature=0), chat_memory=history, summarize_step=2, return_messages=True)
```

If you still encounter the same error, please ensure that you have the correct version of LangChain installed and that there are no conflicts with other packages.

### Sources

- [langchain/memory/summary.py](https://github.com/hwchase17/langchain/blob/master/langchain/memory/summary.py)

---

This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
