### ISSUE TITLE
how to pass additional variables using kwargs to CustomLLM

### ISSUE THREAD

**Issue by shrinath-suresh** [langchain-ai/langchain#6638]
### System Info

langchain - 0.0.198
platform - ubuntu
python - 3.10.11

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Objective is to pass additional variables to `_call` method in CustomLLM.

Colab Link - https://colab.research.google.com/drive/19VSmSEBq5D0MDXQ3CF0rrmOdGjdaELUj?usp=sharing 

Sample code:

```
from langchain import PromptTemplate, LLMChain
from langchain.llms.base import LLM
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer

model_name = "facebook/opt-350m"
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer = AutoTokenizer.from_pretrained(model_name)


class CustomLLM(LLM):
    def _call(self, prompt, stop=None, **kwargs) -> str:
        print("Kwargs: ", kwargs)
        inputs = tokenizer([prompt], return_tensors="pt")

        response = model.generate(**inputs, max_new_tokens=128)
        response = tokenizer.decode(response[0])
        return response

    @property
    def _identifying_params(self):
        return {"name_of_model": model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"


llm = CustomLLM()

prompt_template = "Answer the question - {question}"

prompt = PromptTemplate(template=prompt_template, input_variables=["question"])

llm_chain = LLMChain(prompt=prompt, llm=llm)
```

### Scenario1

passing additional parameter `foo=123`
```
result = llm_chain.run({"question":"What is the weather in LA and SF"},  foo=123)
```
Following error is thrown
```
ValueError: `run` supported with either positional arguments or keyword arguments but not both. Got args: ({'question': 'What is the weather in LA and SF'},) and kwargs: {'foo': 123}.
```

### Scenario2
if we pass it as a dictionary - `{'foo': 123}`
```
result = llm_chain.run({"question":"What is the weather in LA and SF"},  {"foo":123})
```
Following error is thrown

```
ValueError: `run` supports only one positional argument.
```

### Scenario3
if we pass everything together
```
result = llm_chain.run({"question":"What is the weather in LA and SF", "foo":123})
```

The code works, but the kwargs in CustomLLM - `_call` is still empty. i guess, the chain is safely ignoring the variables which are not part of prompt template.

Is there any way to pass the additional parameter to the kwargs of CustomLLM - `_call` method without changing the prompt template?

**Comment by 100gle** [comment]
I have a similar requirement. 

For example, I would like to add some tracking parameters, such as UUID and timestamp, before each call to ConversationRetrievalChain, and persist them through ConversationBufferWindowMemory to local json file. 

However, it seems that LangChain does not currently support this yet. :(

**Comment by shrinath-suresh** [comment]
Unfortunately, yes. I came across a workaround. If you are not utilizing the stop generation, you can pass the parameters through the stop argument. Although this solution may not be ideal, it seems to be the only option until the issue is resolved.

**Comment by liuyijiang1994** [comment]
+1，want set parameters dynamically every turn it runs

**Comment by mkecera** [comment]
Another option is to instantiate the CustomLLM with some parameters:
`llm = CustomLLM(n=512, messageId='test')`
