### ISSUE TITLE
sql_db_list_tables returning different order each time making caching impossible

### ISSUE THREAD

**Issue by phihung** [langchain-ai/langchain#6640]
### System Info

langchain==0.0.207

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.sql_database import SQLDatabase

db = SQLDatabase.from_uri("sqlite:///sample.db",)
db.get_usable_table_names()  # Change table names order each time the application is retarted
```

Current implementation
```python
class SQLDatabase:
    def get_usable_table_names(self) -> Iterable[str]:
        if self._include_tables:
              return self._include_tables
        return self._all_tables - self._ignore_tables  # THIS IS A SET

class ListSQLDatabaseTool(BaseSQLDatabaseTool, BaseTool):
    def _run(self, tool_input: str = "", ...) -> str:
        return ", ".join(self.db.get_usable_table_names())  # ORDER CHANGES EACH RUN
```

### Expected behavior

```python
class ListSQLDatabaseTool(BaseSQLDatabaseTool, BaseTool):
    def _run(self, tool_input: str = "", ...) -> str:
        return ", ".join(sorted(self.db.get_usable_table_names()))
```

**Comment by sumanthdonthula** [comment]
Hey @phihung, good observation I have Update sql_database.py to return the tables in sorted order and created a pull request.

#6692
