### ISSUE TITLE
[AzureChatOpenAI] openai_api_type can't be changed from the default 'azure' value

### ISSUE THREAD

**Issue by gerlaxrex** [langchain-ai/langchain#6650]
### System Info

Hello,

during the development of an application that needs to authenticate to Azure services and use the wrapper [AzureChatOpenAi](https://github.com/hwchase17/langchain/blob/master/langchain/chat_models/azure_openai.py), we encountered an error due to the fact that the model could not use the 'azure_ad' type.

It seems that this class sets the openai_api_type always to the set default value of 'azure' even if we have an environment variable called 'OPENAI_API_TYPE' specifying 'azure_ad'.

Why is it so?

### Who can help?

@hwchase17 
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

answering_llm=AzureChatOpenAI(
        deployment_name=ANSWERING_MODEL_CONFIG.model_name,
        model_name=ANSWERING_MODEL_CONFIG.model_type, #"gpt-3.5-turbo"
        openai_api_type="azure_ad", # IF THIS IS NOT EXPLICITLY PASSED IT FAILS
        openai_api_key=auth_token,
        temperature=ANSWERING_MODEL_CONFIG.temperature,
        max_tokens=ANSWERING_MODEL_CONFIG.max_tokens
    )

### Expected behavior

We expect the wrapper to take the value of the environmental variable correctly.

**Comment by vmansolas** [comment]
Related PR: #8622
