### ISSUE TITLE
Issue: ConversationalRetrievalChain Fails to Distinguish User's Intention for Chat History Only or Chat History + Vector Store Answer

### ISSUE THREAD

**Issue by ShaneYuTH** [langchain-ai/langchain#6677]
### Issue you'd like to raise.

In my application, I am using the ConversationalRetrievalChain with "stuff" chain type, FAISS as the vector store and ConversationBufferMemory. I have noticed that when I ask a question related to a previous response (i.e. a request that is only looking for answers from chat history, such as a summarization request), the system still searches for answers from both the vector store and chat history. This often leads to incorrect or irrelevant answers (the summarization will include data from chat history as well as data that is never presented in previous conversation from vector store).

I've tried to address this issue by passing a custom prompt using combine_docs_chain_kwargs to specify whether a response should be generated based on the chat history only, or the chat history and the vector store. However, this approach hasn't been effective.

It seems that the system is currently unable to correctly discern the user's intention to exclusively use the chat history for generating a response. It's crucial that the system can accurately determine this to provide relevant and accurate responses.

### Suggestion:

I propose that the system should be enhanced with a mechanism to first detect the user's intention to either:

Select a response from the chat history only, or
Select a response from the chat history in combination with the vector store.

This could possibly be achieved by conditionally including or excluding certain parts of a prompt, such as {context} (from stuff_prompt.py, this is the default prompt used by stuff chain type), based on user input or intentions. However, this logic would need to be implemented during the data preparation for the template.

I haven't figured out a way to do so. Looking forward to your help!

**Comment by ShantanuNair** [comment]
Can you not use a router chain to facilitate this?

**Comment by ShaneYuTH** [comment]
> Can you not use a router chain to facilitate this?

After a quick glance through the router chain, this might be a pretty good solution to the above problem. Thanks for your info!

**Comment by heweapon** [comment]
> After a quick glance through the router chain, this might be a pretty good solution to the above problem. Thanks for your info!

Have you solved the problem in this way？

**Comment by pribadihcr** [comment]
+1
