### ISSUE TITLE
Issue: Can an LLM be used as a tool?

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#6687]
### Issue you'd like to raise.

I have a use case where the agent is supposed to perform certain activities (going over the metadata and telling if the currently selected column is fit for querying). This would need a `zero-shot-react-agent` to use several LLMs as tools instead of the present ones (like search being shown everywhere). The [documentation](https://python.langchain.com/docs/modules/agents/how_to/custom_mrkl_agent#multiple-inputs) shows that this is possible but is in itself quite ambiguous. 
How do I create an LLMChain as a tool if it always needs a prompt while initialisation? And the prompt can be created only after mentioning this LLMChain as a tool in the `create_prompt` function?

**Comment by vowelparrot** [comment]
https://python.langchain.com/docs/modules/agents/tools/how_to/custom_tools#tool-dataclass

**Comment by miandai** [comment]
```

from langchain.chains import LLMChain
from langchain import PromptTemplate

execute_task_prompt = PromptTemplate(
    template="""Given the following overall question `{input}`.

    Perform the task by understanding the problem, extracting variables, and being smart
    and efficient. Write a detailed response that address the task.
    When confronted with choices, make a decision yourself with reasoning.
    """,
    input_variables=["input"],
)

llm = ChatOpenAI(streaming=True)
llm_chain = LLMChain(llm=llm, prompt=execute_task_prompt)

tools = [
    Tool(
        name="Reason",
        func=llm_chain.run,
        description="Reason about task via existing information or understanding. Make decisions / selections from options.",
    ),
]

```
