### ISSUE TITLE
Chroma.from_documents(...persist_directory=db_path) has no effect

### ISSUE THREAD

**Issue by vsraptor** [langchain-ai/langchain#6696]
### System Info

$ pip freeze | grep langchain
langchain==0.0.197
langchainplus-sdk==0.0.10

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

For some reason : 

db = Chroma.from_documents(texts, self.embeddings, persist_directory=db_path, client_settings=settings)

persist_directory=db_path, has no effect ... upon db.persist() it stores into the default directory 'db', instead of using db_path.

Only if you explicitly set Settings(persist_directory=db_path, ... ) it works.

Probable reason is that in langchain chroma.py  if you pass client_settings and 'persist_directory' is not part of the settings, it will not add 'persist_directory' as it is done in the ELSE case, but ...:

(line 77 ++)
```
        if client is not None:
            self._client = client
        else:
            if client_settings:
                self._client_settings = client_settings  <<< .... here ..........
            else:
                self._client_settings = chromadb.config.Settings()
                if persist_directory is not None:
                    self._client_settings = chromadb.config.Settings(
                        chroma_db_impl="duckdb+parquet",
                        persist_directory=persist_directory,
                    )
            self._client = chromadb.Client(self._client_settings)

        self._embedding_function = embedding_function
        self._persist_directory = persist_directory
``` 

but ... chromadb.__init__.py expects 'persist_directory' in settings i.e. (line 44), otherwise it will use the default : 

```
   elif setting == "duckdb+parquet":
        require("persist_directory")
        logger.warning(
            f"Using embedded DuckDB with persistence: data will be stored in: {settings.persist_directory}"
        )
```

### Expected behavior

db = Chroma.from_documents(texts, self.embeddings, persist_directory=db_path, client_settings=settings)

should use db_path instead of 'db'

**Comment by nopa12** [comment]
Same here. 0.3.26 works for now
