### ISSUE TITLE
Memory seems not to be supported in create_pandas_dataframe_agent

### ISSUE THREAD

**Issue by matt7salomon** [langchain-ai/langchain#6699]
### Feature request

I am trying to add memory to create_pandas_dataframe_agent to perform post processing on a model that I trained using Langchain. I am using the following code at the moment.
```
from langchain.llms import OpenAI
import pandas as pd

df = pd.read_csv('titanic.csv')
agent = create_pandas_dataframe_agent(OpenAI(temperature=0), [df], verbose=True)
```
I tried adding memory = ConversationBufferMemory(memory_key="chat_history") but that didnt help. Tried many other methods but seems like the memory for create_pandas_dataframe_agent is not implemented

### Motivation

There is a major need in pandas processing to save models as pickle files along with adding new features to the studied dataset which alters the original dataset for the next step. It seems like langchain currently doesnt support that.

### Your contribution

I can help with the implementation if necessary.

**Comment by Sulomus** [comment]
I have created a working example for adding a memory into `pandas_agent`.

The whole code is on stackoverflow:
https://stackoverflow.com/questions/76500981/how-to-add-conversational-memory-to-pandas-toolkit-agent/76562847#76562847

**Comment by Sulomus** [comment]
You need to change the `prompt.py` file - it seems like you didn't add the memory keys into the prompt.

> Thanks @Sulomus. When I try to run this using the following command: pd_agent.run('the shape of the dataset?') I get this error: ValueError: A single string input was passed in, but this chain expects multiple inputs ({'chat_history', 'input'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`
> 
> I tried
> 
> ```
> pd_agent.run({'df_head':df.head(), 'input':'get the number of nulls in each column and print it', 'agent_scratchpad':"", 'chat_history_buffer':chat_history_buffer, 'chat_history_summary':chat_history_summary,'chat_history_KG':chat_history_KG})
> ```
> 
> which seems to work but doesnt keep a memory of the previous output.

You need to change the `prompt.py` file - it seems like you didn't add the memory keys into the prompt.

**Comment by fuwentay** [comment]
@Sulomus thanks for working on this!

i've implemented your change to prompt.py, but it's still not working. i get the following error:

  File "C:\Users\fuwen\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent_toolkits\pandas\base.py", line 285, in create_pandas_dataframe_agent
    prompt, tools = _get_prompt_and_tools(
  File "C:\Users\fuwen\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent_toolkits\pandas\base.py", line 133, in _get_prompt_and_tools
    return _get_multi_prompt(
  File "C:\Users\fuwen\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\agent_toolkits\pandas\base.py", line 58, in _get_multi_prompt
    prompt = ZeroShotAgent.create_prompt(
  File "C:\Users\fuwen\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\agents\mrkl\base.py", line 86, in create_prompt
    return PromptTemplate(template=template, input_variables=input_variables)
  File "C:\Users\fuwen\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input parameters. 'num_dfs' (type=value_error)

hope you would be able to assist me!
