### ISSUE TITLE
ChatOpenAI.get_num_tokens_from_messages raises TypeError with function call response

### ISSUE THREAD

**Issue by nyanp** [langchain-ai/langchain#6706]
### System Info

- LangChain version: 0.0.214
- tiktoken version: 0.4.0

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Executing following code raises `TypeError: expected string or buffer`.

```python
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage

llm = ChatOpenAI(model_name="gpt-3.5-turbo-0613", temperature=0)

functions = [
    {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": ["celsius", "fahrenheit"]
          }
        },
        "required": ["location"]
      }
    }  
]

response = llm([HumanMessage(content="What is the weather like in Boston?")], functions=functions)

llm.get_num_tokens_from_messages([response])
```

`get_num_tokens_from_messages` internally converts messages to dict with `_convert_message_to_dict` and then interates all key-value pairs to count the number of tokens.
The code expects value to be a string, but when a function call is included, an exception seems to be raised because value contains a dictionary.

### Expected behavior

As far as I know, there is no officially documented way to calculate the exact token count consumption when using function call.

Someone on the OpenAI forum has [posted](https://community.openai.com/t/how-to-calculate-the-tokens-when-using-function-call/266573/10) a method for calculating the tokens, so perhaps that method could be adopted.

**Comment by yaoquanxin** [comment]
maybe your model not in the autogen\token_count_utils.py.  bro ,you see the function :_num_token_from_messages
make sure your model in else branch, then the funcation is truely called.
in my case : I use deekseek-reasoner model .so i do it like this : 



 def _num_token_from_messages(messages: Union[List, Dict], model="gpt-3.5-turbo-0613"):
    """Return the number of tokens used by a list of messages.

    retrieved from https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb/
    """
    if isinstance(messages, dict):
        messages = [messages]

    try:
        encoding = tiktoken.encoding_for_model(model)
    except KeyError:
        logger.warning(f"Model {model} not found. Using cl100k_base encoding.")
        encoding = tiktoken.get_encoding("cl100k_base")
    if model in {
        "gpt-3.5-turbo-0613",
        "gpt-3.5-turbo-16k-0613",
        "gpt-4-0314",
        "gpt-4-32k-0314",
        "gpt-4-0613",
        "gpt-4-32k-0613",

    }:
        tokens_per_message = 3
        tokens_per_name = 1
    elif model == "deepseek-reasoner": 
        logger.info("deepseek may update over time. Returning num tokens assuming deepSeek-reasoner")
        token_per_message = 4 # 表示每条消息的基本格式需要4个token
        '''
            1.<|start|> 标记消息开始.
            2.角色/名称 (role/name)
            3.<|end|> 标记消息结束.
            4.\n 表示换行符.
        '''
        token_per_name = -1

**Comment by IgorFZ** [comment]
This problem still exists in version `langchain=1.0.5`

**Comment by IrhilOussama** [comment]
yes and also for models like qwen
