### ISSUE TITLE
search specific vector by tag or key

### ISSUE THREAD

**Issue by easonktsai** [langchain-ai/langchain#6720]
Hi teams,

Can I make the embedding with tag or any key, I want to make user with different auth. to query specific vector of document.

I was trying to use Redis as vectorstore.Would it recommend to be my vectorstore if I want to implement something authentication.

I'll embed my document into vectorstore and each embedding has its permission. And then I'll have users with different permission. The user who be granted the permission of document can query that vector of document.

For example, Embed three docuemnts into vectorstore and there are two user with different permission.
| Docs   | key | 
| :----- | :--: | 
| Docs_A |  A  | 
| Docs_B |  B  | 
| Docs_C |  C |

| User| permission | 
| :----- | :--: | 
| User_A |  A, C |  
| User_B |  B | 

At this use case, User_A can query the vector of Docs_A and Docs_C, and User_B just Docs_B

**Comment by easonktsai** [comment]
How performance it is? If I have lots of document about thousands upon thousands. Doing filter at similarity search function would have clear bottleneck?

**Comment by earonesty** [comment]
this works for supabase and is very performant if you modify the stored procedure to filter on the metadata and you index the fields you are filtering on .  https://github.com/hwchase17/langchain/pull/7721

**Comment by tylerhutcherson** [comment]
@easonktsai
This can be performed with Redis out-of-the-box using filterable Tag fields. In fact, this is one of the primary benefits of a vector index that can perform filtering in addition to KNN/ANN/Range vector queries.

See an example schema and set up below.

Sample Data with 3 Docs:
```python
texts = ["document A content", "document B content", "document C content"]
metadata = [
    {
        "permission": "A",
    },
    {
        "permission": "B",
    },
    {
        "permission": "C"
    },
]
```
Using the basic redis vectorstore [guide](https://python.langchain.com/docs/integrations/vectorstores/redis), we can build a schema to represent this data:

```python
index_schema = {
    "tag": [{"name": "permission"}],
}
```

And lastly, let's create the Redis vector search index:
```python
from langchain.vectorstores.redis import Redis
from langchain.embeddings import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(openai_api_key="YOUR OPENAI API KEY")
rds = Redis.from_texts(
    texts,
    embeddings,
    metadatas=metadata,
    redis_url="redis://localhost:6379",
    index_name="docs",
    index_schema=index_schema
)
```

Query time!
```python
from langchain.vectorstores.redis import RedisTag

has_A_access = RedisTag("permission") == "A"
results = rds.similarity_search("document search query", k=2, filter=has_A_access)

has_A_B_access = RedisTag("permission") == ["A", "B"]
results = rds.similarity_search("document search query", k=2, filter=has_A_B_access)
```
More examples here: https://python.langchain.com/docs/integrations/vectorstores/redis#hybrid-filtering
