### ISSUE TITLE
Handling larger responses in the API chain

### ISSUE THREAD

**Issue by FluffyKebab** [langchain-ai/langchain#6722]
### Feature request

Currently, the API chain takes the result from the API and gives it directly to a LLM chain. If the result is larger then the context length of the LLM, the chain will give an error. To address this issue I propose that the chain should split the API result using a text splitter, then give the result to combine documents chain that answers the question. 

### Motivation

I have found that certain question given to the API chain gives results from the API that exede the context length of the standard openai model. For example:  
```python
from langchain.chains import APIChain
from langchain.prompts.prompt import PromptTemplate
from langchain.llms import OpenAI

llm = OpenAI(temperature=0)

from langchain.chains.api import open_meteo_docs
chain_new = APIChain.from_llm_and_api_docs(llm, open_meteo_docs.OPEN_METEO_DOCS, verbose=True)

chain_new.run('What is the weather of [latitude:52.52, longitude:13.419998]?')
```
The LLM creates the this URL: https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.419998&hourly=temperature_2m,weathercode,snow_depth,freezinglevel_height,visibility.  The content from this URL is kind of large. This causes the prompt to have 6382 tokens and be lager then the max context length. I think the chain should be able to handle larger responses. 

### Your contribution

I can try to submit a PR to implement this solution.

**Comment by asagarw** [comment]
> ### Feature request
> Currently, the API chain takes the result from the API and gives it directly to a LLM chain. If the result is larger then the context length of the LLM, the chain will give an error. To address this issue I propose that the chain should split the API result using a text splitter, then give the result to combine documents chain that answers the question.
> 
> ### Motivation
> I have found that certain question given to the API chain gives results from the API that exede the context length of the standard openai model. For example:
> 
> ```python
> from langchain.chains import APIChain
> from langchain.prompts.prompt import PromptTemplate
> from langchain.llms import OpenAI
> 
> llm = OpenAI(temperature=0)
> 
> from langchain.chains.api import open_meteo_docs
> chain_new = APIChain.from_llm_and_api_docs(llm, open_meteo_docs.OPEN_METEO_DOCS, verbose=True)
> 
> chain_new.run('What is the weather of [latitude:52.52, longitude:13.419998]?')
> ```
> 
> The LLM creates the this URL: https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.419998&hourly=temperature_2m,weathercode,snow_depth,freezinglevel_height,visibility. The content from this URL is kind of large. This causes the prompt to have 6382 tokens and be lager then the max context length. I think the chain should be able to handle larger responses.
> 
> ### Your contribution
> I can try to submit a PR to implement this solution.

@FluffyKebab were you able to find any workaround to this problem? return_Direct also does not work it seems.

**Comment by sundaraa-deshaw** [comment]
Was this taken up? Curious to know if using embeddings and similarity search from vector DB will reduce the context window.
