### ISSUE TITLE
Getting "ValueError: Unsupported chat history format:" while using ConversationalRetrievalChain with memory type VectorStoreRetrieverMemory

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#6741]
### System Info

LangChain-0.0.207, Windows, Python-3.9.16

Memory (VectorStoreRetrieverMemory) Settings:

dimension = 768
index = faiss.IndexFlatL2(dimension)

embeddings = HuggingFaceEmbeddings()

vectorstore = FAISS(embeddings.embed_query, index, InMemoryDocstore({}), {})
retriever = vectorstore.as_retriever(search_kwargs=dict(k=3))
memory = VectorStoreRetrieverMemory(
    memory_key="chat_history",
    return_docs=True,
    retriever=retriever,
    return_messages=True,
)

ConversationalRetrievalChain Settings:

_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.\
Make sure to avoid using any unclear pronouns.

Chat History:
{chat_history}
(You do not need to use these pieces of information if not relevant)
Follow Up Input: {question}
Standalone question:"""
CONDENSE_QUESTION_PROMPT = PromptTemplate(
    input_variables=["chat_history", "question"], template=_template
)

question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain = load_qa_with_sources_chain(
    llm, chain_type="refine"
)  # stuff  map_reduce  refine

qa = ConversationalRetrievalChain(
    retriever=chroma.as_retriever(search_kwargs=dict(k=5)),
    memory=memory,
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    return_source_documents=True,
    # verbose=True,
)

responses = qa({"question": user_input})

ISSUE: At first cal, it is giving results. BUT in second call, it is throwing an error as follows:

ValueError: Unsupported chat history format: <class 'langchain.schema.Document'>. Full chat history:

What am I doing wrong here?

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Memory (VectorStoreRetrieverMemory) Settings:

dimension = 768
index = faiss.IndexFlatL2(dimension)

embeddings = HuggingFaceEmbeddings()

vectorstore = FAISS(embeddings.embed_query, index, InMemoryDocstore({}), {})
retriever = vectorstore.as_retriever(search_kwargs=dict(k=3))
memory = VectorStoreRetrieverMemory(
    memory_key="chat_history",
    return_docs=True,
    retriever=retriever,
    return_messages=True,
)

2. ConversationalRetrievalChain Settings:

_template = """Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.\
Make sure to avoid using any unclear pronouns.

Chat History:
{chat_history}
(You do not need to use these pieces of information if not relevant)
Follow Up Input: {question}
Standalone question:"""
CONDENSE_QUESTION_PROMPT = PromptTemplate(
    input_variables=["chat_history", "question"], template=_template
)

question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain = load_qa_with_sources_chain(
    llm, chain_type="refine"
)  # stuff  map_reduce  refine

qa = ConversationalRetrievalChain(
    retriever=chroma.as_retriever(search_kwargs=dict(k=5)),
    memory=memory,
    combine_docs_chain=doc_chain,
    question_generator=question_generator,
    return_source_documents=True,
    # verbose=True,
)

responses = qa({"question": user_input})

ISSUE: At first cal, it is giving results. BUT in second call, it is throwing an error as follows:

ValueError: Unsupported chat history format: <class 'langchain.schema.Document'>. Full chat history:

What am I doing wrong here?

### Expected behavior

Chat history should be injected in chain

**Comment by mail2mhossain** [comment]
Now getting following error:

ValueError: Unsupported chat history format: <class 'str'>

**Comment by ShantanuNair** [comment]
@mail2mhossain did you figure this out?

**Comment by mail2mhossain** [comment]
Not Yet

**Comment by jan-schaeffer** [comment]
+1 

```
from langchain.memory import VectorStoreRetrieverMemory
from langchain.vectorstores import Qdrant
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.llms import OpenAI
from langchain.chains import ConversationalRetrievalChain
from langchain.retrievers.multi_query import MultiQueryRetriever

llm = OpenAI(openai_api_key=OPEN_AI_API_KEY)

class AnswerMachine:
    def __init__(self):
        self.embeddings = SentenceTransformerEmbeddings(model_name="sentence-transformers/msmarco-distilbert-dot-v5")
        self.qdrant_client = QdrantClient(QDRANT_URL)
        self.qdrant = Qdrant(embeddings=self.embeddings,
                                client=self.qdrant_client,
                                collection_name='history',
                                vector_name='text')
        self.retriever = self.qdrant.as_retriever()
        self.memory = VectorStoreRetrieverMemory(retriever=self.retriever, memory_key="chat_history", return_docs=False, return_messages=True)
    
    def answer(self, text):
        retriever = MultiQueryRetriever.from_llm(retriever=self.qdrant.as_retriever(search_type='mmr'), llm=llm)
 
        qa_chain = ConversationalRetrievalChain.from_llm(llm, retriever=retriever, memory=self.memory, return_source_documents=True)
        answer = qa_chain({"question": text})

        return answer
```

Also returns `ValueError: Unsupported chat history format:` when called the second time.

**Comment by jan-schaeffer** [comment]
Following some examples in #2303 

I used: `qa_chain = ConversationalRetrievalChain.from_llm(llm, retriever=retriever, memory=self.memory, return_source_documents=True, get_chat_history=lambda h : h)`

and it works now.
