### ISSUE TITLE
Issue: Entity extraction using custom rules

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#6747]
### Issue you'd like to raise.

I would like to perform a query on a database using natural language. However, running direct queries is not possible, and I have to do it via an API. For that, given a sentence, I'd like to extract some custom entities from it. 

For example, if the sentence is: "How many more than 20 years old male users viewed a page or logged in in the last 30 days?"
The entities are:
```
<gender, equals, male>,
<age, greater than, 20>,
<event name, equals, view page>,
<event name, equals, login>,
<event timestamp, more than, 30 days>
```

The first element of each entity (triplet) comes from the list of columns
The second element is inferred from context (nature of the operator if it's a single value or array to compare with)
The third element is also inferred from the context and must belong to the chosen column (first element)

I'm not able to restrict either of these elements for the entity. I'd like an agent first to check all the columns that are available, choose one and view their unique values. Once it gets that, either choose that column (first element) and value (third element) or look again and repeat these steps.

Any help on this would be great!

**Comment by shashankdeshpande** [comment]
Not sure whether I interpreted it correctly or not, but this is what I tried out - 
```python
import json
from pprint import pprint
from langchain.llms import OpenAI
from langchain import PromptTemplate

llm = OpenAI(temperature=0, verbose=True)

template = """You need to extract entities from the user query in specified format.
Extracted entities always should have valid json format, if you don't find any entities then respond with empty list.

Entity Format: List of dict, where each dict having format as {{"entity":"{{entity key}}", "operator":"{{valid sql operator}}", "value":"{{value of entity}}"}}

You need to extract below mentioned entities:
gender: str or list, possible values = [male, female]
age: int, represent age in years
event_name: str or list, possible values = [login, view_page, home_page, contact_us]
event_timestamp: int, represents days for comparing with current date

Use the following format:
User Query: Question here
Entities: Extracted entities in valid json format here

User Query: {query}
Entities:
"""

prompt_template = PromptTemplate(
    input_variables=["query"],
    template=template
)
```
Example 1:
```python
query = "How many more than 20 years old male users viewed a page or logged in in the last 30 days?"

resp = llm(prompt_template.format(query=query))
pprint(json.loads(resp))
```
```
[{'entity': 'gender', 'operator': '=', 'value': 'male'},
 {'entity': 'age', 'operator': '>', 'value': '20'},
 {'entity': 'event_name', 'operator': 'IN', 'value': ['login', 'view_page']},
 {'entity': 'event_timestamp', 'operator': '<', 'value': '30'}]
```
Example 2:
```python
query = "How many users have visited home page in last week?"

resp = llm(prompt_template.format(query=query))
pprint(json.loads(resp))
```
```
[{'entity': 'event_name', 'operator': '=', 'value': 'home_page'},
 {'entity': 'event_timestamp', 'operator': '<=', 'value': '7'}]
```
You can modify the prompt by updating possible values for each of the entity. 
You can create agent with custom tools as specified below: 
- Tool 1 - Wrap this logic as a initial entity extraction tool
- Tool 2 - API integration to get actual result

Hope this helps!
Let me know your thoughts

**Comment by saswat0** [comment]
@shashankdeshpande 
Thanks for this elaborate response. It definitely does work as expected.

However, what I've not mentioned clearly (my bad:() is that the number of columns can be variable, and so can the values in them. Hence, whenever a prompt comes, one agent should find the entities and iterate over them. A second agent should look at all the columns, and a third agent should look at agent2's chosen column's unique values. Together by feedback passing, they should concur at a correct column name and the value (i.e., first and third values of the triplet, respectively).

**Comment by shashankdeshpande** [comment]
Thanks for your response.
Can you handle it using below custom tools? 
1. **Columns Identifier** - Custom function which will retrieve all possible columns and respective values
2. **Entity Extraction** - Make use of above mentioned prompt after modify it by using output of column identifier tool
3. **API call** - Use output of entity extraction to call relevant api and get desired results

Ultimately answer will be derived by calling an API (internally database query), so columns and values can be identify initially is what I thought.

**Comment by saswat0** [comment]
@shashankdeshpande 
I see. Yes, this is exactly what I thought of doing. So there are two tools as of now
- **Get column names** - A custom function which gets all the column names
- **Get all values** - A custom function that gets all the unique values of a particular column

Thanks to your answer, I'll add your prompt as a separate agent (LLM based). I was previously using it in the agent's prompt.

The problem with this is that the agent is not able to iterate across the discovered entities. It takes a single pass through the whole dataset, never calls the second tool (get all values) and returns as is.

Some novice questions
1. Say I add an LLM (your approach) and get all the entities. How do I use the other tools (schema and unique values) to solidify the selections that are made
2. Can I get the entities first (by using the knowledge of the database i.e., column names and unique values) and then iterate on these entities for a second time to refine them?

**Comment by shashankdeshpande** [comment]
@saswat0 I understand your perspective.

Here is my proposed approach. Follow these steps sequentially:
1. Retrieve all available columns and their corresponding possible values at once.
2. Update the entity extraction prompt with all these details and extract all entities.
3. Utilize the extracted entities to call the API and obtain the desired result.

It seems like you are considering extracting each entity individually and refining them by matching with possible values. However, an alternative approach would be to provide all the information to LLM at once, allowing it to make decisions and extract the entities. Further refinement may not be necessary.

To implement this, you can modify the agent prompt to instruct the LLM to consistently invoke the specified tools (Column & Values Identifier, Entity Extractor, API) sequentially.

**Comment by saswat0** [comment]
@shashankdeshpande 
If I provide all the column names and their unique values, I'm afraid that might exceed the input token length. Also, when/where will these tools be used then? Or am I not understanding you correctly?

**Comment by shashankdeshpande** [comment]
@saswat0 
I understand your concern about number of tokens.
However if you want to experiment with proposed approach, below mentioned resources might be helpful - 
- Create custom agent - https://python.langchain.com/docs/modules/agents/how_to/custom_agent.html
- Create custom tools - https://python.langchain.com/docs/modules/agents/tools/how_to/custom_tools.html
