### ISSUE TITLE
Issue: ConversationBufferMemory stopped working

### ISSUE THREAD

**Issue by Dave86ch** [langchain-ai/langchain#6748]
Hello everyone. 
Oddly enough, I've recently run into a problem with memory. 
In the first version, I had no issues, but now it has stopped working. It's as though my agent has Alzheimer's disease. 
Does anyone have any suggestions as to why it might have stopped working? 
There doesn't seem to be any error message or any apparent reason. Thank you!

I already tried reinstalling chromedb.

```
def agent(tools):
    llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613")
    agent_kwargs = {
    "user name is bob": [MessagesPlaceholder(variable_name="chat_history")],
    }
    template = """This is a conversation between a human and a bot:

    {chat_history}

    Write a summary of the conversation for {input}:
    """

    prompt = PromptTemplate(input_variables=["input", "chat_history"], template=template)
    memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
    #agent_chain = initialize_agent(tools, llm, agent=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION, verbose=True, memory=memory)
    agent_chain=initialize_agent(tools, llm, agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, prompt = prompt, verbose=True, agent_kwargs=agent_kwargs, memory=memory, max_iterations=5, early_stopping_method="generate")
    return agent_chain
```

Perhaps this error is realated

´´´
WARNING:root:Failed to load default session, using empty session: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Failed to load default session, using empty session: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

´´´

´´´
WARNING:root:Failed to persist run: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /chain-runs (Caused by NewConnectionError('<urllib3.connectio
n.HTTPConnection object at 0x7f1458a82770>: Failed to establish a new connection: [Errno 111] Connection refused'))                                                              Failed to persist run: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /chain-runs (Caused by NewConnectionError('<urllib3.connection.HTTPConnect
ion object at 0x7f1458a82770>: Failed to establish a new connection: [Errno 111] Connection refused'))                                                                           I'm sorry, but I don't have access to personal information.

´´´

**Comment by Dave86ch** [comment]
I resolved the warning, but I still don't understand why the ConversationBufferMemory stopped functioning. Oddly, it doesn't appear to create any files in the chromeDB folder of the project. It's as if it doesn't operate at all, which is strange, especially since it functioned in the past.

**Comment by Dave86ch** [comment]
I have already tried reinstalling the libraries anew. Even though I provided personal information about myself when I asked them again, the response was that they don't know personal information. The "chromadb" folder appears to be creating its memory files.

**Comment by okradze** [comment]
Hey. How did you resolved the warnings? @Dave86ch

**Comment by Dave86ch** [comment]
> Hey. How did you resolved the warnings? @Dave86ch 

Hello, removing
```os.environ["LANGCHAIN_HANDLER"] = "langchain"```

**Comment by prodineeritecht** [comment]
I am doing almost the exact same thing, initializing a structured chat agent with a conversation buffer memory, and it doesn't work:
```
if self.additional_tools:
            self.tools.extend(self.additional_tools)

        self.llm = ChatOpenAI(temperature=self.temperature, model_name=self.llm_model)

        convo_memory = ConversationBufferMemory(memory_key="history",return_messages=True)
        chat_history = MessagesPlaceholder(variable_name="history") 
        self.executor = initialize_agent(
            tools=self.tools,
            llm=self.llm,
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            memory=convo_memory,
            verbose=True,
            prefix=prefix,
            suffix=suffix,
            memory_prompts=[chat_history],
            agent_kwargs={
                'history': [chat_history],
                'input_variables': input_variables,
            }

        )
```
I've looked through the code and I can't actually see where the memory is actually being read from or written to during the agent's loop.

**Comment by prodineeritecht** [comment]
I have noticed in the StructuredChatAgent class that the LLMChain is instantiated without any memory being passed in https://github.com/hwchase17/langchain/blob/8f5eca236fa399bab81ee7a533cc37efd27a257d/langchain/agents/structured_chat/base.py#L125

```
 llm_chain = LLMChain(
            llm=llm,
            prompt=prompt,
            callback_manager=callback_manager,
        )
```
I am going to try updating the from_llm_and_tools class method to accept a memory type so we can explicitly pass in the memory we want to use.  If that works, I will put up a PR.

**Comment by prodineeritecht** [comment]
@Dave86ch I actually was able to get it working.  It looks like you have to pass everything you need for the memory in the kwargs dictionary.  This snippet below is what started working for me:
```
convo_memory = ConversationBufferMemory(memory_key="history",return_messages=True)
        chat_history = MessagesPlaceholder(variable_name="history") 
        self.executor = initialize_agent(
            tools=self.tools,
            llm=self.llm,
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            memory=convo_memory,
            verbose=True,
            agent_kwargs={
                'history': [chat_history],
                'prefix' : prefix,
                'suffix' : suffix,
                'memory_prompts': [chat_history],
                'input_variables': ["input", "agent_scratchpad", "history"],
            }
        )
```
And now my chats look more like this:
<img width="765" alt="image" src="https://github.com/hwchase17/langchain/assets/101597833/a4eddf2d-d5b8-4488-8370-a00c7090b3de">

**Comment by prodineeritecht** [comment]
> I have noticed in the StructuredChatAgent class that the LLMChain is instantiated without any memory being passed in
> 
> https://github.com/hwchase17/langchain/blob/8f5eca236fa399bab81ee7a533cc37efd27a257d/langchain/agents/structured_chat/base.py#L125
> 
> ```
>  llm_chain = LLMChain(
>             llm=llm,
>             prompt=prompt,
>             callback_manager=callback_manager,
>         )
> ```
> 
> I am going to try updating the from_llm_and_tools class method to accept a memory type so we can explicitly pass in the memory we want to use. If that works, I will put up a PR.

I just confirmed that the "memory_prompts" kwarg is needed.  I went back and commented that line out and I got this error when my service started up:
```
Got mismatched input_variables. Expected: {'input', 'agent_scratchpad'}. Got: ['input', 'agent_scratchpad', 'history'] (type=value_error)
```
So, yeah, this looks like the minimal set of kwargs to pass into initialize_agent to get the memory working:

```
convo_memory = ConversationBufferMemory(memory_key="history",return_messages=True)
        chat_history = MessagesPlaceholder(variable_name="history") 
        self.executor = initialize_agent(
            tools=self.tools,
            llm=self.llm,
            agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
            memory=convo_memory,
            verbose=True,
            agent_kwargs={
                'history': [chat_history],
                'memory_prompts': [chat_history],
                'input_variables': ["input", "agent_scratchpad", "history"],
            }
        )
```

**Comment by Dave86ch** [comment]
> I just confirmed that the "memory_prompts" kwarg is needed. I went back and commented that line out and I got this error when my service started up:
> 
> ```
> Got mismatched input_variables. Expected: {'input', 'agent_scratchpad'}. Got: ['input', 'agent_scratchpad', 'history'] (type=value_error)
> ```
> 
> So, yeah, this looks like the minimal set of kwargs to pass into initialize_agent to get the memory working:
> 
> ```
> convo_memory = ConversationBufferMemory(memory_key="history",return_messages=True)
>         chat_history = MessagesPlaceholder(variable_name="history") 
>         self.executor = initialize_agent(
>             tools=self.tools,
>             llm=self.llm,
>             agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
>             memory=convo_memory,
>             verbose=True,
>             agent_kwargs={
>                 'history': [chat_history],
>                 'memory_prompts': [chat_history],
>                 'input_variables': ["input", "agent_scratchpad", "history"],
>             }
>         )
> ```

That's fantastic, it's finally working now. Thank you so much!
