### ISSUE TITLE
Weaviate.from_documents throws PosixPath is not JSON serializable when documents loaded via Pathlib

### ISSUE THREAD

**Issue by Robbie-Palmer** [langchain-ai/langchain#6751]
### System Info

Ubuntu 22.04.2
Python 3.10.11
langchain 0.0.215

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from pathlib import Path

from langchain.document_loaders import UnstructuredMarkdownLoader
from langchain.embeddings import LlamaCppEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import Weaviate

model_dir = Path.home() / 'models'
llama_path = model_dir / 'llama-7b.ggmlv3.q4_0.bin'
encoder = LlamaCppEmbeddings(model_path=str(llama_path))
readme_path = Path(__file__).parent.parent / 'README.md'
loader = UnstructuredMarkdownLoader(readme_path)
data = loader.load()
text_splitter = CharacterTextSplitter(
    separator="\n\n",
    chunk_size=10,
    chunk_overlap=2,
    length_function=len,
)
texts = text_splitter.split_documents(data)
db = Weaviate.from_documents(texts, encoder, weaviate_url='http://localhost:8080', by_text=False)
```

### Expected behavior

The `UnstructuredMarkdownLoader` loads the metadata as a `PosixPath` object
`Weaviate.from_documents` then throws an error because it can't post this metadata, as `PosixPath` is not serializable
If I change `loader = UnstructuredMarkdownLoader(readme_path)` to `loader = UnstructuredMarkdownLoader(str(readme_path))` then the metadata is loaded as a string, and the posting to Weaviate works

I would expect `UnstructuredMarkdownLoader` to have the same behaviour when I pass it a string or a path like object
I would expect Weaviate to handle serialising a path like object to a string

**Comment by hp0404** [comment]
`UnstructuredMarkdownLoader` uses an external library (`from unstructured.partition.md import partition_md`). The easiest fix would be to change this line:
https://github.com/hwchase17/langchain/blob/d84a3bcf7ab3edf8fe1d49083e066d51c9b5f621/langchain/document_loaders/markdown.py#L25

to this:
```python
return partition_md(filename=str(self.file_path), **self.unstructured_kwargs)
```
