### ISSUE TITLE
vectorstores/faiss.py load_local can't set normalize_L2

### ISSUE THREAD

**Issue by dylanwwang** [langchain-ai/langchain#6758]
https://github.com/hwchase17/langchain/blob/1742db0c3076772db652c747df1524cd07695f51/langchain/vectorstores/faiss.py#L458
this from method can set 'normalize_L2' for un-norm embeddings

https://github.com/hwchase17/langchain/blob/1742db0c3076772db652c747df1524cd07695f51/langchain/vectorstores/faiss.py#L588

but load_local no 'normalize_L2' argument, so cache&load cant't work as expected

please add 'normalize_L2'，or cache 'normalize_L2' to cache_file and restore it when load_local

**Comment by umarbutler** [comment]
+1. I decided to use this quick workaround until a fix is pushed:
```python
import faiss, pickle
index = faiss.read_index(f'{PATH_TO_FAISS_INDEX}.faiss')
with open(f'{PATH_TO_PICKLE_DOCSTORE}.pkl', 'rb') as file:
    docstore, index_to_docstore_id = pickle.load(file)
vectors = FAISS(EMBEDDINGS.embed_query, index, docstore, index_to_docstore_id, normalize_L2=True)
```

**Comment by dylanwwang** [comment]
> +1. I decided to use this quick workaround until a fix is pushed:
> 
> ```python
> import faiss, pickle
> index = faiss.read_index(f'{PATH_TO_FAISS_INDEX}.faiss')
> with open(f'{PATH_TO_PICKLE_DOCSTORE}.pkl', 'rb') as file:
>     docstore, index_to_docstore_id = pickle.load(file)
> vectors = FAISS(EMBEDDINGS.embed_query, index, docstore, index_to_docstore_id, normalize_L2=True)
> ```

You can also forcibly set the _normalize_L2 attribute of the FAISS object.

**Comment by umarbutler** [comment]
l

> > +1. I decided to use this quick workaround until a fix is pushed:
> > ```python
> > import faiss, pickle
> > index = faiss.read_index(f'{PATH_TO_FAISS_INDEX}.faiss')
> > with open(f'{PATH_TO_PICKLE_DOCSTORE}.pkl', 'rb') as file:
> >     docstore, index_to_docstore_id = pickle.load(file)
> > vectors = FAISS(EMBEDDINGS.embed_query, index, docstore, index_to_docstore_id, normalize_L2=True)
> > ```
> 
> You can also forcibly set the '_normalize_L2' attribute of the FAISS object.

Even better.
