### ISSUE TITLE
AzureChatOpenAI: InvalidRequestError

### ISSUE THREAD

**Issue by UlrikWKoren** [langchain-ai/langchain#6759]
### System Info

Windows 11,
python==3.10.5
langchain==0.0.215
openai==0.27.8
faiss-cpu==1.7.4

### Who can help?
@zeke 
@sbusso 
@deepblue 
when run this example code: 
https://python.langchain.com/docs/modules/model_io/models/chat/integrations/azure_chat_openai
I get the following error...

"InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."

The code works if you downgrade langchain to 0.0.132

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Follow the instructions in the notebook.
https://python.langchain.com/docs/modules/model_io/models/chat/integrations/azure_chat_openai

### Expected behavior

Get a response.

**Comment by hanit-com** [comment]
Note that the deployment name in your Azure account may not necessarily correspond to the standard name of the model. For instance, the model "get-35-turbo" could be deployed using the name "get-35". Make sure you are providing the Azure name.

**Comment by UlrikWKoren** [comment]
> Note that the deployment name in your Azure account may not necessarily correspond to the standard name of the model. For instance, the model "get-35-turbo" could be deployed using the name "get-35". Make sure you are providing the Azure name.

I have changed the model name to correspond with the azure deployment. I know the deployment works since when i downgrade langchain to 0.0.132 the code works as intended.

**Comment by UlrikWKoren** [comment]
> Note that the deployment name in your Azure account may not necessarily correspond to the standard name of the model. For instance, the model "get-35-turbo" could be deployed using the name "get-35". Make sure you are providing the Azure name.

I made sure to use the correct model name so it corresponds with the azure deployment. I know the azure deployment works since when I downgrade langchain to 0.0.132 the code works as intended.

**Comment by hanit-com** [comment]
I work with 0.0.215 and same openai version as you and it works...
Can you share some of your code? BTW there is langchain 0.0.218 so maybe try to upgrade again.
