### ISSUE TITLE
Streaming Support For AzureOpenAI

### ISSUE THREAD

**Issue by YuvalBogachev** [langchain-ai/langchain#6760]
### System Info

There is a lack of support for the streaming option with AzureOpenAI.  As you can see from the following article (https://thivy.hashnode.dev/streaming-response-with-azure-openai) official API support on Azure's side is present. 

Specifically, when trying to utilize the streaming argument with AzureOpenAI, we recieve the following error (with gpt-35-turbo model, which is possible on direct Azure interfacing):
`InvalidRequestError: logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346.`

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Run the following code in a notebook:
```
from langchain.callbacks.base import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.chains import (
    ConversationalRetrievalChain,
    LLMChain
)
from langchain.chains.question_answering import load_qa_chain
from langchain.prompts.prompt import PromptTemplate
from langchain.llms import AzureOpenAI
from langchain.chat_models import AzureChatOpenAI

template = """Given the following chat history and a follow up question, rephrase the follow up input question to be a standalone question.
Or end the conversation if it seems like it's done.

Chat History:\"""
{chat_history}
\"""

Follow Up Input: \"""
{question}
\"""

Standalone question:"""

condense_question_prompt = PromptTemplate.from_template(template)

template = """You are a friendly, conversational retail shopping assistant. Use the following context including product names, descriptions, and keywords to show the shopper whats available, help find what they want, and answer any questions.
It's ok if you don't know the answer.

Context:\"""
{context}
\"""

Question:\"""
\"""

Helpful Answer:"""

qa_prompt= PromptTemplate.from_template(template)

llm = AzureOpenAI(deployment_name="gpt-35-turbo",  temperature=0)

streaming_llm = AzureOpenAI(
    streaming=True,
    callback_manager=CallbackManager([
        StreamingStdOutCallbackHandler()]),
    verbose=True,
    engine=deployment_name,
    temperature=0.2,
    max_tokens=150
)

# use the LLM Chain to create a question creation chain
question_generator = LLMChain(
    llm=llm,
    prompt=condense_question_prompt
)

# use the streaming LLM to create a question answering chain
doc_chain = load_qa_chain(
    llm=streaming_llm,
    #llm=llm,
    chain_type="stuff",
    prompt=qa_prompt
)


chatbot = ConversationalRetrievalChain(
    retriever=vectorstore.as_retriever(),
    combine_docs_chain=doc_chain,
    question_generator=question_generator
)

# create a chat history buffer
chat_history = []

# gather user input for the first question to kick off the bot
question = input("Hi! What are you looking for today?")

# keep the bot running in a loop to simulate a conversation
while True:
    result = chatbot(
        {"question": question, "chat_history": chat_history}
    )
    print("\n")
    chat_history.append((result["question"], result["answer"]))
    question = input()
```

Engine is "gpt-35-turbo" and the correct environment variables are provided.

2. Input anything in the input field.
3. Error Occurs.

Results in the following error:
`InvalidRequestError: logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346.`

### Expected behavior

To execute without error.

### P.S.
This is my first bug report on GitHub, so if anything is missing please let me know.

**Comment by RazHadas** [comment]
👎
There isn't support of streaming parameter in AzureOpenAI langchain class.

**Comment by dmyoung9** [comment]
This appears to be the exact same issue as #9038.

**Comment by AaronStackBarnes** [comment]
This is also not working for me.

**Comment by corticalstack** [comment]
Anyone know if this is resolved, i.e. streaming works using Azure OpenAI gpt-3.5turbo model?

**Comment by Blackkadder** [comment]
> In the API reference it says you can pass in a streaming parameter: https://api.python.langchain.com/en/latest/chat_models/langchain.chat_models.azure_openai.AzureChatOpenAI.html
> 
> But it’s not working for me. Did anyone here have success with streaming using Azure?

Facing same problem
