### ISSUE TITLE
ConversationBufferMemory fails to capture OpenAI functions messages in LLMChain

### ISSUE THREAD

**Issue by paschembri** [langchain-ai/langchain#6761]
### System Info

Adding memory to a LLMChain with OpenAI functions enabled fails because of `AIMessage` are generated instead of `FunctionMessage`

```python
    self.add_message(AIMessage(content=message))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pas/development/advanced-stack/sandbox/sublime-plugin-maker/venv/lib/python3.11/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AIMessage
content
  str type expected (type=type_error.str)
```

where `AIMessage.content` is in fact a dict.

Tested version : `0.0.215`

### Who can help?

@dev2049 
@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a LLMChain with both functions and memory
2. Enjoy :)

### Expected behavior

When LLMChain is created with `functions` and memory, generate FunctionMessage and accept dict (or json dumps)

**Comment by paschembri** [comment]
It may be the `JsonOutputFunctionsParser` that is executed and then provides a dict to the Memory backend (and then failing)

**Comment by CoLdIcE42** [comment]
I'm having the same issue working with an Agent with conversational memory and open source models

**Comment by dregules** [comment]
same issue here. I can't chain in a SequentialChain both a structured_output_chain (openai functions) and another LLMchain with memory because it fails in the same way as explained here. 

```
ValidationError: 1 validation error for AIMessage
content
  str type expected (type=type_error.str)
```

**Comment by abdulrahimpds** [comment]
Encountered a similar issue:
```
self.messages.append(AIMessage(content=message))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AIMessage
content
  str type expected (type=type_error.str)
  ```
  
  Here's a "solution" (more like a workaround):
  Open `chat_memory.py` in `C:\Users\YOURNAME\Programs\Python\Python311\Lib\site-packages\langchain\memory\chat_memory.py` and replace this part:
  ```
  class ChatMessageHistory(BaseModel):
    messages: List[BaseMessage] = Field(default_factory=list)

    def add_user_message(self, message: str) -> None:
        self.messages.append(HumanMessage(content=message))

    def add_ai_message(self, message: str) -> None:
        self.messages.append(AIMessage(content=message))

    def clear(self) -> None:
        self.messages = []
  ```
  
  with:
  ```
  class ChatMessageHistory(BaseModel):
    messages: List[BaseMessage] = Field(default_factory=list)

    def add_user_message(self, message: str) -> None:
        self.messages.append(HumanMessage(content=message))

    def add_ai_message(self, message: str) -> None:
        if not isinstance(message, str):
            message = str(message)
        self.messages.append(AIMessage(content=message))

    def clear(self) -> None:
        self.messages = []
  ```

**Comment by ferasawadi** [comment]
@abdulrahimpds  but this workaround will fail when attempt to reinstall the pkg correct? 
the issue appears when i tried to pass an extra variable 
 results = self.agent_chain.run(input={
            "message": message,
            "phone_number": phone_number,
        })

**Comment by abdulrahimpds** [comment]
@ferasawadi The workaround essentially converts any non-string `message` to a string before adding it to the `messages` list, which addresses the `ValidationError`. This alteration in the `add_ai_message` method ensures that the `message` is always a string type, thus preventing the error. You're correct that reinstalling the package would overwrite this change, but this modification is just a temporary fix. (Devs should notice this issue and get it fixed ASAP)

In your case, when passing an extra variable (`phone_number`), you should ensure that the `input` parameter is a string type to avoid similar issues. You can do so by converting the `input` parameter to a string as shown:
```
results = self.agent_chain.run(input=str({
    "message": message,
    "phone_number": phone_number,
}))
```

This will convert the entire `input` dictionary to a string, ensuring that the `message` is a string type as expected by the `add_ai_message` method.

**Comment by abdulrahimpds** [comment]
@ferasawadi For a permanent solution, developers should modify the `ChatMessageHistory` class to ensure both `input` and `output` messages are always converted to string types, preventing the `ValidationError`. The revised `add_user_message` and `add_ai_message` methods should check the message type and convert it to a string if it's not already, as shown below:
```
class ChatMessageHistory(BaseModel):
  messages: List[BaseMessage] = Field(default_factory=list)

  def add_user_message(self, message: str) -> None:
      if not isinstance(message, str):
          message = str(message)
      self.messages.append(HumanMessage(content=message))

  def add_ai_message(self, message: str) -> None:
      if not isinstance(message, str):
          message = str(message)
      self.messages.append(AIMessage(content=message))

  def clear(self) -> None:
      self.messages = []
```

This adjustment will handle the `ValidationError` by ensuring that messages are always of string type, negating the need for manual conversion and addressing the issue at its root.

**Comment by ryanholtschneider2** [comment]
Getting this error in 0.1.0 as well

**Comment by alessandro-ceccarelli** [comment]
I'm experiencing this issue with version langchain==0.1.13 too. How can I fix that? Thank you

**Comment by mattfoxvog** [comment]
This still exists in langchain_0.1.13, as stated above.
The issue is coming all the way from BaseChain or BaseChatMemory, depending on how it's fixed.  
The type-hints need to be fixed in both of those classes, since they expect output_str == str, but the output_str comes from a dictionary and could be a compound dictionary (as is the case here), meaning output_str == dict (currently).

Instead of editing source-code that'll be broken by updates, here is a temporary fix using inheritance method override:

```
class PatchedConversationBufferMemory(ConversationBufferMemory):
    def save_context(self, inputs, outputs) -> None:
        """Save context from this conversation to buffer."""
        input_str, output_str = self._get_input_output(inputs, outputs)
        output_str = output_str if isinstance(output_str, str) else str(output_str) # this line is the temp-fix
        self.chat_memory.add_messages(
            [HumanMessage(content=input_str), AIMessage(content=output_str)]
        )

# so now, instead of creating memory from ConversationBufferMemory, you just use PatchedConversationBufferMemory

```

I'll see how much work it is to submit a PR for this, but a workaround is above.
