### ISSUE TITLE
Issue: Qdrant does not support the vector_size parameter, which is a very common and frequently used parameter. I hope it can be supported.

### ISSUE THREAD

**Issue by zhugexinxin** [langchain-ai/langchain#6766]
### Issue you'd like to raise.

Qdrant does not support the vector_size parameter, which is a very common and frequently used parameter. I hope it can be supported.

langchain/vectorstores/qdrant.py

```
# Just do a single quick embedding to get vector size
   partial_embeddings = embedding.embed_documents(texts[:1])
   vector_size = len(partial_embeddings[0])
```

### Suggestion:

I hope it can be supported.

**Comment by hanit-com** [comment]
Hi, I see that whenever a number that does not match the exact size is used there is an error saying:
`ValueError: could not broadcast input array from shape (10,) into shape (30,)`
Currently it uses the right size when creating a collection, can you help me understand the need to make it changeable?

**Comment by kacperlukawski** [comment]
@zhugexinxin The vector size is derived from the created embeddings. You don't need to set it since this is transparent for the user. The issue may occur only if you try to reuse a collection that was created without Langchain and has a different vector size configured. Could you please share some more details?

**Comment by zhugexinxin** [comment]
> @zhugexinxin The vector size is derived from the created embeddings. You don't need to set it since this is transparent for the user. The issue may occur only if you try to reuse a collection that was created without Langchain and has a different vector size configured. Could you please share some more details?

The main thing is that the best dimension of the model is not the same, like openai is 1536 dimensions, this is my understanding, please help me correct if wrong.

**Comment by kacperlukawski** [comment]
@zhugexinxin I don't get it. If you choose embeddings, for example, OpenAI, they are already 1536-dimensional. And Qdrant will derive that automatically. Would you like to use just part of those embeddings?
