### ISSUE TITLE
add streaming to chains

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#679]

**Comment by etown** [comment]
Would love to see this happen. The documentation says that architectures are being considered, any guidance on how I could help make this happen? I have a hacky solution, but happy to help build out what's needed for full support.

**Comment by janpawellek** [comment]
Yes please! Also happy to help 👍🏻 

@etown could you describe your ideas on a solution? Sounds very interesting 😃

**Comment by dmyoung9** [comment]
@hwchase17 Is this resolved? I am pretty sure that by now almost every chain has implemented streaming, and there are specific issues open for most instances that are still not working.
