### ISSUE TITLE
Custom tool class not working with extra properties

### ISSUE THREAD

**Issue by lironezra** [langchain-ai/langchain#6828]
### System Info

Hello everyone,

I am currently utilizing the OpenAIFunctions agent along with some custom tools that I've developed. I'm trying to incorporate a custom property named `source_documents` into one of these tools. My intention is to assign a value to this property within the tool and subsequently utilize this value outside of the tool.

To illustrate, this is how I invoke my custom tool: `tools = [JamesAllenRetrievalSearchTool(source_documents), OrderTrackingTool()]`. Here, `source_documents `is the property that I wish to update within the `JamesAllenRetrievalSearchTool `class.

I attempted to create a constructor within the custom tool and pass the desired variable for updating, but unfortunately, this approach was unsuccessful. If anyone has knowledge of a solution to my problem, I would greatly appreciate your assistance.

Thank you!

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here is My custom tool Class: 

`class JamesAllenRetrivalSearchTool(BaseTool):

    name = "jamesallen-search"
    description = "Use this tool as the primary source of context information. Always search for the answers using this tool first, don't make up answers yourself"
    return_direct = True
    args_schema: Type[BaseModel] = JamesAllenRetrivalSearchInput  

    def _run(self, question: str, run_manager: Optional[CallbackManagerForToolRun] = None) -> str:
        knowledge_base_retrival_chain = RetrivalQAChain(prompt)
        result = knowledge_base_retrival_chain.run(question)
        # **HERE -> I need to update returned source_documents from the chain outside the custom tool class**
        # source_documents = result["source_documents"]
        # self.retrival_source_docs = source_documents
        return result["result"]
    
    async def _arun(self, question: str, run_manager: Optional[AsyncCallbackManagerForToolRun] = None) -> str:
        """Use the tool asynchronously."""
        raise NotImplementedError("Not implemented")
`

### Expected behavior

When I run the tool I expect that the answer from the chain will return and the source documents will be update.

**Comment by meet1919** [comment]
You can pass any custom variable to the tool with `metadata` argument.

## Below is the BaseTool source code.
```python
class BaseTool(RunnableSerializable[Union[str, Dict], Any]):
    metadata: Optional[Dict[str, Any]] = None
        """Optional metadata associated with the tool. Defaults to None
        This metadata will be associated with each call to this tool,
        and passed as arguments to the handlers defined in `callbacks`.
        You can use these to eg identify a specific instance of a tool with its use case.
        """
```

## Below is example code on how to add metadata to the custom tool.
```python
class CustomTool(BaseTool)  
    name = "jamesallen-search"
    description = "Use this tool as the primary source of context information. Always search for the answers using this tool first, don't make up answers yourself"
    return_direct = True
    args_schema: Type[BaseModel] = JamesAllenRetrivalSearchInput  
    
    def _run(self, question: str, run_manager: Optional[CallbackManagerForToolRun] = None) -> str:
        # External variable return when tool runs
        return self.metadata['custom_variable']
    
    async def _arun(self, question: str, run_manager: Optional[AsyncCallbackManagerForToolRun] = None) -> str:
        """Use the tool asynchronously."""
        raise NotImplementedError("Not implemented")


class Agent:

    def __init__(self):
        llm = ChatOpenAI(
            model_name='gpt-3.5-turbo-1106', 
            temperature=0.1,
        )
        memory = ConversationBufferMemory(output_key='output')
       self.custom_variable = True
        tools = [
            CustomTool(metadata={'custom_variable': self.custom_variable})
        ]
        self.agent = initialize_agent(
            tools=tools,
            llm=llm,
            agent="conversational-react-description",
            verbose=True,
            memory=memory,
            return_intermediate_steps=True,
        )
```

**Comment by owais-globalnorthstar** [comment]
Can we update the metadata or tags in run method of tool to get the traces on langsmith ?
