### ISSUE TITLE
sqldatabasechain result incomplete

### ISSUE THREAD

**Issue by xvgaoxing2023** [langchain-ai/langchain#6861]
### Issue you'd like to raise.

db_chain = SQLDatabaseChain(llm=llm, database=db, prompt=PROMPT, verbose=True, return_intermediate_steps=True, top_k=3)
result = db_chain("Make a list of those taking the exam")
result['result']  is incomplete，why ？token ?

**Comment by xvgaoxing2023** [comment]
I check carefully again，SQLQuery is right,SQLResult is right,but Answer  incomplete..

**Comment by xvgaoxing2023** [comment]
is anybody here?why not answer me again?

**Comment by theshook** [comment]
hello @xvgaoxing2023 does your result automatically truncated? I got the same issue

**Comment by xvgaoxing2023** [comment]
@theshook hi，yes,i am confused，why the  result automatically truncated

**Comment by anuratayal** [comment]
I have the same problem. The response from LLM is truncated.

**Comment by devojony** [comment]
In my case, I solved this by setting the 'max_string_length' parameter when creating 'SQLDatebase'
```python
db = SQLDatabase.from_uri(
    ...
    max_string_length=10000,
)

```
