### ISSUE TITLE
how to track token usage for OpenAIEmbeddings? it seems that  get_openai_callback always return 0.

### ISSUE THREAD

**Issue by xiaoyhuang123** [langchain-ai/langchain#6869]
### Issue you'd like to raise.

how to track token usage for OpenAIEmbeddings? it seems that  get_openai_callback always return 0.

**Comment by Vineet-the-git** [comment]
I am facing the same issue. I want to calculate the cost of using openAIEmbeddings. But I couldn't a supported functionality. How can we do it?

**Comment by Vineet-the-git** [comment]
@xiaoyhuang123 can you provide the piece of code how you are using `get_openai_callback` with `OpenAIEmbeddings`?
