### ISSUE TITLE
Handling tokens exceeding exception in Stuff Chain

### ISSUE THREAD

**Issue by Who828** [langchain-ai/langchain#687]
Hello, I love using the stuff chain for my docs/blogs; it gives me better answers, is faster, and is cheaper. However, sometimes some questions lead to token-exceeded errors from OpenAI; I thought maybe in those cases, I could reduce the `K` value and try again.

I ended up writing this for my use case,
```Python
tiktoken_encoder  = tiktoken.get_encoding("gpt2")

def page_content(doc):
    return doc.page_content
def reduce_tokens_below_limit(docs, limit=3400):
    tokens = len(tiktoken_encoder.encode("".join(map(page_content, docs))))
    return docs if (tokens <= limit) else reduce_tokens_below_limit(docs[:-1])

class MyVectorDBQAWithSourcesChain(VectorDBQAWithSourcesChain):
    def _get_docs(self, inputs):
        question = inputs[self.question_key]
        docs = self.vectorstore.similarity_search(question, k=self.k)
        return reduce_tokens_below_limit(docs)
```

I used recursion because I liked the clarity of the method, and the `K` value isn't going to be higher than single-digit numbers in a practical scenario.

I would love to contribute this back upstream; where do you suggest I include this, and what should I name it? I'll take care of docs and other things for this use case. :)

**Comment by hwchase17** [comment]
i love this idea! i would love to add this add a paramter to the VectorDBQAWithSourcesChain where if True it does what you described, but if False it has the current functionality. can probably default to True

**Comment by harithzulfaizal** [comment]
I tried using `reduce_k_below_max_tokens` but it doesn't seem to work. I still get the "InvalidRequestError: This model's maximum context length is 4096 tokens" error.

Code snippet:
```
qa_chain = load_qa_with_sources_chain(OpenAIChat(temperature=0), chain_type="stuff")
qa = VectorDBQAWithSourcesChain(combine_documents_chain=qa_chain, vectorstore=vectorstore, reduce_k_below_max_tokens=True)
```

**Comment by AldawsariNLP** [comment]
I am getting the same error with "Stuff" chain

**Comment by dxv2k** [comment]
does any know how to fix this? 
My work around solution right is trying to keep indexed documents smaller

**Comment by SinaArdehali** [comment]
did you find any solution @dxv2k ?
