### ISSUE TITLE
Allow skipping "condense_question_prompt" when using ConversationalRetrievalChain

### ISSUE THREAD

**Issue by bastoo0** [langchain-ai/langchain#6879]
### Feature request

Add a parameter to ConversationalRetrievalChain to skip the condense question prompt procedure.

### Motivation

Currently, when using ConversationalRetrievalChain (with the from_llm() function), we have to run the input through a LLMChain with a default "condense_question_prompt" which condenses the chat history and the input to make a standalone question out of it.

This could be a good idea, but in my test cases (in French) it performs very poorly when switching between topics. It mixes things up and hallucinates a new question which is nowhere near the original question.

The only solution I can think of is to just allow the actual chat history to be sent in the prompt but we can't skip the condense question prompt part. For now, a workaround could be to provide a custom condense prompt asking the LLM to do nothing but that would call the LLM twice for no reason...

### Your contribution

Since I am not sure why this isn't already an option, I'd assume it's for a good reason so I'm asking here before thinking of implementing anything.

**Comment by iPanchalShubham** [comment]
how can i do the same thing in langchain.js ??

**Comment by iPanchalShubham** [comment]
> how can i do the same thing in langchain.js ??

I actually figured it out, for Nextjs, Nodejs and js guys

```

  type Record<K extends keyof any, T> = {
    [P in K]: T;
  };
  type ChainValues = Record<string, any>;

  class NoOperationLLMChain extends LLMChain {
    constructor() {
      const prompt = new PromptTemplate({ template: "", inputVariables: [] });
      super({ llm: new OpenAI(), prompt });
    }

    async call(
      values: ChainValues & this["llm"]["CallOptions"],
      ...args: any[]
    ): Promise<any> {
      console.log(`values ${JSON.stringify(values)}`);
      values = {
        question: values.question,
      };
      return values;
    }
  }

  const chain = ConversationalRetrievalQAChain.fromLLM(
    streamingModel,
    (await vectorStore).asRetriever(),

    {
      qaChainOptions: {
        prompt: customPromptTemplate,
        type: "stuff",
        verbose: true,
      },

      verbose: true,
      memory: new BufferMemory({
        returnMessages: true,

        // k: 1, //remember the most recent  conversation
        chatHistory: new ChatMessageHistory(getPastMessages(pastMessages)),
        memoryKey: "chat_history", // Must be set to "chat_history"
        inputKey: "question", // The key for the input to the chain
        outputKey: "text", // The key for the final conversational output of the chain
      }),
      returnSourceDocuments: true,
      questionGeneratorChainOptions: {
        llm: nonStreamingModel,
      },
    }
  );

  chain.questionGeneratorChain = new NoOperationLLMChain();

chain.call({
    question: query,
  });
```
Let me know, if i can help more with this.

**Comment by gonzar11** [comment]
Why not to just use RetrievalQAChain instead of ConversationRetrievalQAChain ?

**Comment by bastoo0** [comment]
> Why not to just use RetrievalQAChain instead of ConversationRetrievalQAChain ?

I ended up doing this. But it's less handy than this kind of all-in-one function.

**Comment by gonzar11** [comment]
> > Why not to just use RetrievalQAChain instead of ConversationRetrievalQAChain ?
> 
> I ended up doing this. But it's less handy than this kind of all-in-one function.

Did you put the chat_history in the prompt template?

**Comment by ch1zzzz** [comment]
I used NoOpLLMChain() it does skip the condensing process but it also generates a weird memory which is totally non-relevant to my content. 

```
    memory = ConversationSummaryMemory(
        llm=OpenAI(temperature=0), memory_key="chat_history", return_messages=True)

    llm = ChatOpenAI(model_name="gpt-3.5-turbo-16k", temperature=0.2, streaming=True)

    qa = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=db.as_retriever(),
        combine_docs_chain_kwargs={"prompt": prompt},
        memory=memory,
        # condense_question_prompt=condense_question_prompt,
        verbose=True
    )
    qa.question_generator = NoOpLLMChain()
    return qa
```

When I input "hello" it shows:
```
Human: require 'faker'
FactoryGirl.define do
  factory :user do
    name { Faker::Name.name }
    email { Faker::Internet.email }
    password "password"
    password_confirmation "password"
  end
end
Chatbot:
```
Does anyone know what happened?

**Comment by thelazydogsback** [comment]
@iPanchalShubham 
When attempting to use your `NoOpLLMChain` method I get the following error:
(I adjusted it to set the `question_generator` after the init to avoid a "multiple kwargs" error.)

```
TypeError("Chain.run() missing 1 required positional argument: 'self'")Traceback (most recent call last):

  File "...lib\site-packages\langchain\chains\base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
```

I also notice the is a `rephrase_question` boolean, but it doesn't seem to do anything.

**Comment by thelazydogsback** [comment]
@iPanchalShubham 
When trying to use you no-op LLM method, I get the following error:
```
instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
```
As NoOpLLMChain inherits from LLMChain, which eventually inherits from Runnable, it seems like it should work.

**Comment by upendraCTPL** [comment]
how to use this in create_openai_functions_agent ??
