### ISSUE TITLE
Incompatibility with latest Anthropic Client

### ISSUE THREAD

**Issue by rasharab** [langchain-ai/langchain#6883]
### System Info

Massive client changes as of this pr:
https://github.com/anthropics/anthropic-sdk-python/commit/8d1d6af6527a3ef80b74dc3a466166ab7df057df

Installing the latest anthropic client will cause langchain Anthropic LLM utiltiies to fail.
Looks like api_url no longer exists (they've moved to base_url).

```
   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for ChatAnthropic
E   __root__
E     __init__() got an unexpected keyword argument 'api_url' (type=type_error)
```

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Install latest version of anthropic.
2. Attempt to run Anthropic LLM and it will produce a runtime failure about api_url which no longer exists in the Anthropic client initializer.

### Expected behavior

Should work with latest release of Anthropic client.

**Comment by jmkuebler** [comment]
For those just needing a quick work-around. `pip install anthropic==0.2.10` get's you back to the latest version before this change.

**Comment by adityamookerjee** [comment]
@jmkuebler Do you happen to know if this was addressed in another issue/commit to the `langchain` library?

**Comment by jmkuebler** [comment]
> @jmkuebler Do you happen to know if this was addressed in another issue/commit to the `langchain` library?

@adityamookerjee No I am not aware of another issue that could be linked.
