### ISSUE TITLE
load_prompt Unable to set encoding for JSON files

### ISSUE THREAD

**Issue by jiaxin576** [langchain-ai/langchain#6900]
### System Info

llm = OpenAI(temperature=0)
chain = LLMChain(llm=llm, prompt=load_prompt("coolapk_prompt.json"))

config = json.load(f)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 108: illegal multibyte sequence

### Who can help?

llm = OpenAI(temperature=0)
chain = LLMChain(llm=llm, prompt=load_prompt("coolapk_prompt.json"))

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

 
llm = OpenAI(temperature=0)
chain = LLMChain(llm=llm, prompt=load_prompt("coolapk_prompt.json"))

### Expected behavior

add set encoding for JSON files

**Comment by yuhenggh** [comment]
This indeed is a problem. By default, this method uses system encoding to decode when loading template files, which would inevitably lead to errors for non-utf-8 encoded files. It would be ideal to include the autodetect_encoding=True option or provide an encoding parameter. I kindly ask you to consider adding these features to enhance flexibility and user experience. For modifications, you can refer to responses to similar issues at https://github.com/langchain-ai/langchain/issues/9005.

**Comment by Jasper-zh** [comment]
Has this problem been solved? can load_prompt () specify utf-8?

**Comment by josebenitezg** [comment]
same question here

**Comment by Leonx01** [comment]
same question

**Comment by zakki** [comment]
Fixed by https://github.com/langchain-ai/langchain/pull/21559
