### ISSUE TITLE
DOC: 

### ISSUE THREAD

**Issue by jroberge16** [langchain-ai/langchain#6921]
### Issue with current documentation:

Hey,
Love your product, and just wanted to give some constructive feedback. Your new layout and organization strategy on "https://python.langchain.com/docs/get_started/introduction.html" is significantly harder to navigate

**Comment by devstein** [comment]
Hey @jroberge16 thanks for the feedback. Do you have any specific suggests on how to improve the layout and organization strategy? What parts of the previous structure did you prefer?

**Comment by jroberge16** [comment]
I would also say that there seems to be a lot of missing content from your old structure. For example, I was able to find huggingpilines for LLMs quickly and easily on you old system but now I cannot even navigate to it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
