### ISSUE TITLE
Structured Agent Search Not Working

### ISSUE THREAD

**Issue by frederikskovw** [langchain-ai/langchain#6923]
### System Info

Trying to get an agent to describe the contents of a particular URL for me, however, **my agent does not execute past first step**. Attached image to show what my code looks like and where it freezes as it runs.

<img width="683" alt="freezing_agent" src="https://github.com/hwchase17/langchain/assets/97087128/b3888b6e-f016-479e-ac1a-3036b7f16d97">

Thanks <3 !

(also posted as discussion, was not sure where to add)

### Who can help?

@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from config import SERPAPI_API_KEY, OPENAI_API_KEY
from langchain.agents import AgentType
from langchain.chat_models import ChatOpenAI
from langchain.agents import initialize_agent
from langchain.agents.agent_toolkits import PlayWrightBrowserToolkit
from langchain.tools.playwright.utils import create_async_playwright_browser
import asyncio

async_browser = create_async_playwright_browser()
browser_toolkit = PlayWrightBrowserToolkit.from_browser(async_browser=async_browser)
tools = browser_toolkit.get_tools()

gpt_model = "gpt-4"

llm = ChatOpenAI(
    temperature=0,
    model_name=gpt_model,
    openai_api_key=OPENAI_API_KEY
)

agent_chain = initialize_agent(tools, llm, agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

async def main():
    response = await agent_chain.arun(input="Browse to https://www.theverge.com/2023/3/14/23638033/openai-gpt-4-chatgpt-multimodal-deep-learning and describe it to me.")
    return response

result = asyncio.run(main())
print(result)

### Expected behavior

Enter chain, navigate to browser, read content in browser, return description.

Based on: https://python.langchain.com/docs/modules/agents/agent_types/structured_chat.html

**Comment by NathanielCode** [comment]
Hello, 

I'm trying to look into this issue and just wanted some clarification from your screenshot.
Does the agent hang on the first action or is it able to complete the first action, and then stops?

Because if it is the latter, the default model of gpt-3.5-turbo has a similar issue, since it doesn't return the format we want to continue the AgentChain.

![image](https://github.com/langchain-ai/langchain/assets/35385552/0465b143-3e09-4bf3-a94d-8d2eb7b44eeb)

**Comment by codegod100** [comment]
I'm having the same issue

**Comment by Valdanitooooo** [comment]
same here
