### ISSUE TITLE
PR-s wait the review forever

### ISSUE THREAD

**Issue by leo-gan** [langchain-ai/langchain#6930]
### Issue you'd like to raise.

The PRs wait for review  (for any feedback) very long time.

- Some sort of triage would be helpful.
- Some sort of PR closure can be helpful. If something is wrong with PR this should be explained/discussed/addressed. Not providing **any feedback** is demoralizing for contributors.

Thanks!
PS Take a look at the PR list and check PRs that passed all checks and has no answer/feedback. Hundreds of such PRs?

**Comment by devstein** [comment]
@leo-gan Thanks for raising this. I know the maintainers are stretched for time. I'm not a maintainer but have been thinking about this problem and how automation might be able to help. A few follow up questions:

1. What do you mean by "some sort of triage"? What's an example?
2. Maintainers will have the ultimate yes/no decision on merging the PR, but what other types of lower-hanging feedback would be helpful? 
3. Any other ideas for automaton that would give contributors more feedback and visibility in the process?

**Comment by leo-gan** [comment]
It is still relevant

**Comment by leo-gan** [comment]
It mostly fixed
