### ISSUE TITLE
Missing reference to o365_toolkit module in __init__.py of agent_toolkits

### ISSUE THREAD

**Issue by oberthou** [langchain-ai/langchain#6936]
### System Info

Langchain 0.0.218 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

![E4D3964C-8891-46EE-879F-D4F862351BC1](https://github.com/hwchase17/langchain/assets/24804373/399a5a2f-0328-4bf9-bc4a-e4f7a856611a)

### Expected behavior

The module should be found automatically.

**Comment by sdelgadoc** [comment]
Thanks you for submitting! This is caused because the __init__.py file in the "agent_toolkits" folder does not include the O365_Toolkit module, so Python can't find the toolkit. I will update the file and submit a PR to resolve.

**Comment by sdelgadoc** [comment]
Hello @dosu-beta. This issue is resolved in pull request https://github.com/langchain-ai/langchain/pull/7046.
