### ISSUE TITLE
Sentencebert/Bert/Spacy/Doc2vec embedding support

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#6952]
### Feature request

Is there any way to store the Sentencebert/Bert/Spacy/Doc2vec based embeddings in the vector database using langchain
```
pages= "page content"
embeddings = OpenAIEmbeddings()
persist_directory = 'db'
vectordb = Chroma.from_documents(documents=pages, embedding=embeddings, persist_directory=persist_directory)
```
shall use **Sentencebert/Bert/Spacy/Doc2vec embeddings** instead of OpenAIEmbeddings() in the above code?
if possible then what is the syntax for that?

### Motivation

For using native embedding formats likeSentencebert/Bert/Spacy/Doc2vec in langchain

### Your contribution

For using native embedding formats likeSentencebert/Bert/Spacy/Doc2vec in langchain

**Comment by rjarun8** [comment]
Have you checked

- `https://python.langchain.com/docs/modules/data_connection/text_embedding/integrations/sentence_transformers`
- `https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/chroma`

**Comment by pradeepdev-1995** [comment]
@rjarun8 
Okay sentence transformers is there.
what about other native embeddings like Word2vec/Glove/FastText /Bert/Spacy/Doc2vec..etc?

**Comment by rjarun8** [comment]
I am sure a feature to natively support would be great. If you are in a hurry , as a workaround, it can be implemented via the following code. _(This example is for spacy)_

```
import spacy
from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader

class SpacyEmbeddings:
    def __init__(self):
        self.nlp = spacy.load('en_core_web_sm')

    def embed_documents(self, texts):
        return [self.nlp(text).vector.tolist() for text in texts]

# Load the document 
loader = TextLoader("/content/doc.txt")
documents = loader.load()

spacy_embeddings = SpacyEmbeddings()

vectordb = Chroma.from_documents(documents=documents, embedding=spacy_embeddings, persist_directory="./content")
```

However, it's worth adding it as a feature.

**Comment by pradeepdev-1995** [comment]
Thank you. In the code that you mentioned here when to call the **embed_documents** function?

**Comment by rjarun8** [comment]
> Thank you. In the code that you mentioned here when to call the **embed_documents** function in the SpacyEmbeddings class?

you dont have to. The _from_documents_ takes the class as an input argument and calls the methods in it based on the interface defined.

Here is the complete code.

```
import spacy
from langchain.vectorstores import Chroma
from langchain.document_loaders import TextLoader

class SpacyEmbeddings:
    """
    Class for generating Spacy-based embeddings for documents and queries.
    """

    def __init__(self):
        """
        Initialize the SpacyEmbeddings object by loading the Spacy model.
        """
        self.nlp = spacy.load('en_core_web_sm')

    def embed_documents(self, texts):
        """
        Embed a list of documents using Spacy.

        Args:
            texts (list): A list of documents.

        Returns:
            list: A list of document embeddings.
        """
        return [self.nlp(text).vector.tolist() for text in texts]

    def embed_query(self, text):
        """
        Embed a query using Spacy.

        Args:
            text (str): The query text.

        Returns:
            list: The query embedding.
        """
        return self.nlp(text).vector.tolist()

# Load the document and split it into chunks
loader = TextLoader("/content/doc.txt")
documents = loader.load()

spacy_embeddings = SpacyEmbeddings()

vectordb = Chroma.from_documents(documents=documents, embedding=spacy_embeddings, persist_directory="./content")

# query it
query = ""
docs = vectordb.similarity_search(query)

# print results
print(docs[0].page_content)
```

**Comment by pradeepdev-1995** [comment]
@rjarun8 Thank you very much. Let me try this. Hope the other native word embeddings also integrate to langchain soon

**Comment by rjarun8** [comment]
> @rjarun8 Thank you very much. Let me try this. Hope the other native word embeddings also integrate to langchain soon

Sure. I will progressively roll them out under this issue. Hopefully, they get integrated into the langchain ecosystem. cheers!
