### ISSUE TITLE
ValueError: `run` not supported when there is not exactly one output key. Got ['output', 'intermediate_steps']

### ISSUE THREAD

**Issue by zhugexinxin** [langchain-ai/langchain#6956]
### Issue you'd like to raise.

```
agent = initialize_agent(tools, llm, agent="zero-shot-react-description", return_intermediate_steps=True, verbose=True)
agent = initialize_agent(tools, llm, agent="zero-shot-react-description", return_intermediate_steps=True, memory=ConversationBufferMemory(memory_key="chat_history", input_key='input', output_key="output"), verbose=True)

```

https://python.langchain.com/docs/modules/agents/how_to/intermediate_steps

<img width="857" alt="image" src="https://github.com/hwchase17/langchain/assets/42615243/9ea12e4b-1775-4114-a750-0625e1cf8302">

### Suggestion:

I don't know how to solve it!

**Comment by albertovilla** [comment]
@zhugexinxin not sure if this could be the source of the error but I'm not sure the value you're passing to `agent` is correct, you're passing a string but that should be of type `AgentType`.

```python
# Initialize the agent
agent = initialize_agent(tools, llm, AgentType.ZERO_SHOT_REACT_DESCRIPTION, return_intermediate_steps=True, verbose=True)

# run the agent
response = agent.run("zero-shot-react-description")
```

Maybe you could you give this a try.

**Comment by zhugexinxin** [comment]
> ```python
> zero-shot-react-description
> ```

Thanks, I tried that too and it's still the same
```
from enum import Enum


class AgentType(str, Enum):
    ZERO_SHOT_REACT_DESCRIPTION = "zero-shot-react-description"
    REACT_DOCSTORE = "react-docstore"
    SELF_ASK_WITH_SEARCH = "self-ask-with-search"
    CONVERSATIONAL_REACT_DESCRIPTION = "conversational-react-description"
    CHAT_ZERO_SHOT_REACT_DESCRIPTION = "chat-zero-shot-react-description"
    CHAT_CONVERSATIONAL_REACT_DESCRIPTION = "chat-conversational-react-description"
    STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION = (
        "structured-chat-zero-shot-react-description"
    )
    OPENAI_FUNCTIONS = "openai-functions"

```

AgentType.ZERO_SHOT_REACT_DESCRIPTION == '"zero-shot-react-description"'

**Comment by chris-clarke-evml** [comment]
The key to a number of these types of errors is the chain type your agent is using.  Not all chains support the same structured responses.  How are you defining your tools?  For some types, simply invoking the agent response without the ".run" method will work.  For others, the problem is deeper (like RetrievalQAWithSourcesChain, for instance) and these chains aren't as built out for some output types.  

`response = agent("here is my question")`

instead of:

`# run the agent
response = agent.run("here is my question")`

**Comment by dsummersl** [comment]
I ran into this error while using Chroma as a data source. I needed to set `verbose=True` in the `RetrievalQA.from_chain_type()` method:

```python
db = ...load Chroma db...
llm = OpenAI()
obsidian_tool = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=db.as_retriever(), verbose=True
)

tools = [
    Tool(
        name="an external datasource",
        func=obsidian_tool.run,
        description="searches an external datasource for interesting information about foobar",
    )
]
agent = initialize_agent(
    tools,
    llm,
    agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    return_intermediate_steps=True,
)

```

**Comment by Valdanitooooo** [comment]
same here

**Comment by bgokden** [comment]
If anyone comes here, I have fixed this by using `acall` instead of `arun` and `call` instead of `run`, they are very similar just  run accepts a dictionary and call accepts named parameters. If you have one parameter they are the same.

**Comment by 5zjk5** [comment]
> here is my question

这个有用

**Comment by madhubandru** [comment]
> The key to a number of these types of errors is the chain type your agent is using. Not all chains support the same structured responses. How are you defining your tools? For some types, simply invoking the agent response without the ".run" method will work. For others, the problem is deeper (like RetrievalQAWithSourcesChain, for instance) and these chains aren't as built out for some output types.
> 
> `response = agent("here is my question")`
> 
> instead of:
> 
> `response = agent.run("here is my question")`

This worked! Thank you.
