### ISSUE TITLE
Enable CSVLoader to take list of columns as source_column (or metadata)

### ISSUE THREAD

**Issue by amani-acog** [langchain-ai/langchain#6961]
### Feature request

Please update the CSVLoader to take list of columns as source_column.

### Motivation

This update will be be helpful, if the documents are embedded and used with vectordbs like Qdrant. As vectordbs like Qdrant offers filtering option, if the metadata is of Document object is used as payload then it will provide a great enhancement.

### Your contribution

No

**Comment by albertovilla** [comment]
@amani-acog I think the `source_column` has a very specific purpose which is to keep a reference for the source of the document. The `CSVLoader` generates one document per row in th CSV, that document is generated using all columns of the corresponding row. 

I understand what you want to do and it's quite easy to implement, although I'm not sure if it would be accepted for inclusion into the project. If it's not then you could define this class yourself and use it instead of their `CSVLoader`. Basically it includes two changes:
- In the constructor there is a parameter `metadata_columns` where you could provide the list of the columns that will be included as metadata
- In the `load` method if the `metadata_columns` was defined then those are added to the metadata of the documents.

```python
import csv
from typing import Dict, List, Optional
from langchain.document_loaders.base import BaseLoader
from langchain.docstore.document import Document

class CSVLoader(BaseLoader):
    """Loads a CSV file into a list of documents.

    Each document represents one row of the CSV file. Every row is converted into a
    key/value pair and outputted to a new line in the document's page_content.

    The source for each document loaded from csv is set to the value of the
    `file_path` argument for all doucments by default.
    You can override this by setting the `source_column` argument to the
    name of a column in the CSV file.
    The source of each document will then be set to the value of the column
    with the name specified in `source_column`.

    Output Example:
        .. code-block:: txt

            column1: value1
            column2: value2
            column3: value3
    """

    def __init__(
        self,
        file_path: str,
        source_column: Optional[str] = None,
        metadata_columns: Optional[List[str]] = None,   # < ADDED
        csv_args: Optional[Dict] = None,
        encoding: Optional[str] = None,
    ):
        self.file_path = file_path
        self.source_column = source_column
        self.encoding = encoding
        self.csv_args = csv_args or {}
        self.metadata_columns = metadata_columns        # < ADDED

    def load(self) -> List[Document]:
        """Load data into document objects."""

        docs = []
        with open(self.file_path, newline="", encoding=self.encoding) as csvfile:
            csv_reader = csv.DictReader(csvfile, **self.csv_args)  # type: ignore
            for i, row in enumerate(csv_reader):
                content = "\n".join(f"{k.strip()}: {v.strip()}" for k, v in row.items())
                try:
                    source = (
                        row[self.source_column]
                        if self.source_column is not None
                        else self.file_path
                    )
                except KeyError:
                    raise ValueError(
                        f"Source column '{self.source_column}' not found in CSV file."
                    )
                metadata = {"source": source, "row": i}
                # ADDED TO SAVE METADATA
                if self.metadata_columns:
                    for k, v in row.items():
                        if k in self.metadata_columns:
                            metadata[k] = v
                # END OF ADDED CODE
                doc = Document(page_content=content, metadata=metadata)
                docs.append(doc)

        return docs
```

**Comment by amani-acog** [comment]
Hey...

Thank you for your quick response...I have implemented this on my end, but
wanted it to include in langchain...Thanks once again

**Comment by codingvlad** [comment]
I would happy to add a merge request with the implementation for this. I found it very useful and I think more people would benefit from this. Let me know if this is something you would approve to be merged

**Comment by amani-acog** [comment]
Hi Vlad Filip,Yes, please! . And also I want langchain to be able to load
any type of document and generate only embeddings without storing in any
vectordb, so that user can try on their own vectordb even if it is not
implemented in langchain.

Thank you

**Comment by simpleDgq** [comment]
I also want it to be included in langchain. Thanks a lot
