### ISSUE TITLE
langchain agent took a lot of time

### ISSUE THREAD

**Issue by houjibofa2050** [langchain-ai/langchain#6965]
### Issue you'd like to raise.

run langchain agent takes a lot of time,about 20s。the question is simple. Is there any good way reduce time?

**Comment by houjibofa2050** [comment]
![image](https://github.com/hwchase17/langchain/assets/19608744/0ea7109e-0320-4612-9714-13840a09e5c6)
这个是调用的耗时监控

**Comment by albertovilla** [comment]
Looking at the execution times it looks like most of the time was consumed on OpenAI API calls so maybe you could try some of their suggestions to improve latency: https://platform.openai.com/docs/guides/production-best-practices/improving-latencies

**Comment by nihalpawar4** [comment]
may I work on it
