### ISSUE TITLE
VectaraRetriever does not use the parameters passed in by `Vectara.as_retriever()`

### ISSUE THREAD

**Issue by dcellison** [langchain-ai/langchain#6984]
`class VectaraRetriever` does not use the parameters passed in by `Vectara.as_retriever()`. The class definition sets up `vectorstore` and `search_kwargs` but then there is no check for values coming in from `Vectara.as_retriever()`.

https://github.com/hwchase17/langchain/blob/e3b7effc8f39333076c2bedd7306de81ce988de6/langchain/vectorstores/vectara.py#L307

**Comment by luca-git** [comment]
The parameters are indeed ignored. Any progress?

**Comment by luca-git** [comment]
@dcellison Been having the same problem, I figured out parameters need to be passed as search_kwargs:
```python
search_kwargs={   
    "lambda_val" : 0.25,
    'k' : 20,
    'n_sentence_context' : 2,    
    }
 
my_retriever = vs.as_retriever(search_kwargs=search_kwargs)
  ```

**Comment by dcellison** [comment]
That seems to work. Thank you, @luca-git! Is that the intended behaviour? No matter, it lets me avoid having to modify the LangChain source code to use Vectara.
