### ISSUE TITLE
langchain takes much time to reload

### ISSUE THREAD

**Issue by nihalpawar4** [langchain-ai/langchain#6991]
### System Info

Macos system

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

loading malfunction

**Comment by devstein** [comment]
@nihalpawar4 Thanks for making an issue. Can you please provide more details?

**Comment by nihalpawar4** [comment]
give me some time

**Comment by nihalpawar4** [comment]
> @nihalpawar4 Thanks for making an issue. Can you please provide more details?

give me some time lemma check my environment
