### ISSUE TITLE
PipelinePromptTemplate  format_prompt should support missing keyword

### ISSUE THREAD

**Issue by NINTING** [langchain-ai/langchain#7016]
### Feature request

the following is part of  the format code for PipelinePromptTemplate
```python
def _get_inputs(inputs: dict, input_variables: List[str]) -> dict:
    return {k: inputs[k] for k in input_variables}
class PipelinePromptTemplate(BasePromptTemplate):
  ....
  def format_prompt(self, **kwargs: Any) -> PromptValue:
      for k, prompt in self.pipeline_prompts:
          _inputs = _get_inputs(kwargs, prompt.input_variables)
          if isinstance(prompt, BaseChatPromptTemplate):
              kwargs[k] = prompt.format_messages(**_inputs)
          else:
              kwargs[k] = prompt.format(**_inputs)
      _inputs = _get_inputs(kwargs, self.final_prompt.input_variables)
      return self.final_prompt.format_prompt(**_inputs)
```
the function _get_inputs should support miss keyword process，like:
```python
def _get_inputs(inputs: dict, input_variables: List[str]) -> dict:
    return {k: inputs.get(k) for k in input_variables}
```

### Motivation

I primarily use the Jinja2 template format and frequently use control statements. Consequently, there are times when I choose not to pass in certain variables. Thus, I hope that PipelinePromptTemplate could support handling missing variables.

### Your contribution

Perhaps, I can submit a PR to add this feature or fix this bug . If you don't have the time to address it, that is.

**Comment by baskaryan** [comment]
Not sure I full understand the use case, could you provide an example where you'd want to support missing keywords (and it wouldn't be better to just adjust the prompt to not have the missing keyword)

**Comment by NINTING** [comment]
```python
for k, prompt in self.pipeline_prompts:
          _inputs = _get_inputs(kwargs, prompt.input_variables)
         ......
 _inputs = _get_inputs(kwargs, self.final_prompt.input_variables)

def _get_inputs(inputs: dict, input_variables: List[str]) -> dict:
    return {k: inputs[k] for k in input_variables}
``` 

Consider the following two lines of code. 

They require the number of 'self.prompt.input_variables' to be consistent with the quantity of incoming parameter 'kwargs'. Due to the usage of subscript indexing rather than 'get' in the dictionary, a 'keyword error' will occur when a variable is missing.

For instance, my prompt template is in the following format:
```
{{A}}
{{B}}
```
A:
```
{{user}}
{{age}}
```
if i just pass 'user' variable,
prompt.input_variable = {user,age},  kwargs = {user:'xxx'}
and then i will get a error in _get_inputs(kwargs, prompt.input_variables).

This is because 'get_input' will loop through 'input_variable' and attempt to retrieve the corresponding variables from 'kwargs'. When a variable is missing, an error will occur.

Of course, to avoid this issue, I could pre-set all possible variables to an empty string by default(默认).

 However, I'm wondering if Langchain could provide a method for retrieving default(默认) values of indexed variables, rather than directly accessing them through 'dict[key]'.

**Comment by NINTING** [comment]
Are you suggesting that you would like me to adjust the prompt to remove variables that might be missing?

**Comment by NINTING** [comment]
I am trying to build a universal Prompt Template that includes control semantics. 

When I use the control semantics of jinja2, I think it's unlikely that I will write a prompt for every different scenario.

Instead, I prefer to output different prompts by passing different parameters in conjunction with jinja2.
