### ISSUE TITLE
Don't try tools that have already been invalidated in the current run

### ISSUE THREAD

**Issue by drshrey** [langchain-ai/langchain#702]
If you reproduce the agents example in https://langchain.readthedocs.io/en/latest/getting_started/getting_started.html but remove the "serpapi" parameter, the agent gets into an infinite loop with respect to trying actions with tools in which it has already observed the tool is not a valid tool. 

A proposed fix is to maintain a set of all visited tools and do a check before having the agent settle on using that tool. I haven't seen the source code to validate this viability, but this outcome definitely seems not ideal.

<img width="786" alt="Screenshot 2023-01-23 at 12 01 45 PM" src="https://user-images.githubusercontent.com/3188413/214102958-eec3ef46-4fa9-42cc-a43a-213966332fdd.png">

**Comment by jackapbutler** [comment]
Hey @hwchase17, I'm a research engineer working on language modelling and I'm interested in contributing to langchain. I'm happy investigate this and try to fix it? Do you have any advice or thoughts on the best way to proceed?
