### ISSUE TITLE
Agent for MongoDB

### ISSUE THREAD

**Issue by RadhikaBansal97** [langchain-ai/langchain#7036]
### Feature request

I was skimming through the repository for the MongoDB Agent and I discovered that it does not exist. Is it feasible to develop a MongoDB agent that establishes a connection with MongoDB, generates MongoDB queries based on given questions, and retrieves the corresponding data?

### Motivation

Within my organization, a significant portion of our data is stored in MongoDB. I intend to utilize this agent to establish connections with our databases and develop a practical application around it.

### Your contribution

If it is indeed possible, I am willing to work on implementing this feature. However, I would greatly appreciate some initial guidance or assistance from someone knowledgeable in this area.

**Comment by preritdas** [comment]
I wonder if the right way to go about this would be to create a Python REPL agent specifically designed for MongoDB, kind of like the DataFrame agent. The Python REPL agent would use pymongo. Just a thought.

**Comment by schinto** [comment]
I would be happy to have MongoDB agent as well !

There is a [MongoDB reader in LlamaIndex](https://gpt-index.readthedocs.io/en/latest/examples/data_connectors/MongoDemo.html), however it can be used only for very simple MongoDB queries.
See also https://llama-hub-ui.vercel.app/l/mongo

Similar to SQL queries, MongoDB queries can be quite complex, for example
```
/* Case insensitive text search for any term in the patent collection returning only the title field */
db.patents.find({$text: {$search: "Antagonist", $caseSensitive: true  }},{title:1 })
```
or
```
db.products.aggregate([
    { $project: { "highest_phase": { "$cond": [ {"$not": ["$highest_phase.name"]}, "$highest_phase", "$highest_phase.name"] }  }},
	{"$group": { "_id": "$highest_phase", "count": {"$sum": 1} }},
	{ "$sort": { "_id": -1 } },
])
```
or 
```
/* Lookup in collection products described in collection patents published after 2016-01-01 */
db.patents.aggregate([
  { $match:
    {"patent.publication_date": {$gte: new Date("2016-01-01")}}
  },
  { $lookup: {
	from:"products",
	localField:"_id",
	foreignField:"patent_id",
	as:"products" 
  }},
  { $project: {
    patent_title: "$title",
	patent: "$patent",
	"products.entry_number": 1,
	"products.patent_id": 1
  }},
])
```
and for such cases a simple mongodb reader is not good enough.

I hope a LLM is able to learn creating more complex MongoDB queries.

**Comment by lixuejiong** [comment]
+1 , NoSQL db queries have become more and more enterprise use cases, and I am very much looking forward to the launch of mongoDB Agent in langchain

**Comment by prameela1610** [comment]
Hello guys.........
have you found any solutions to connect to mongodb?

**Comment by omer-shahzad-codeDistrict** [comment]
> Hello guys......... have you found any solutions to connect to mongodb?

Yes

**Comment by Zhreyu** [comment]
any solution so far?

**Comment by omer-shahzad-codeDistrict** [comment]
use chain to do that

**Comment by Zhreyu** [comment]
> use chain to do that

Can you explain how? Thanks

**Comment by omer-shahzad-codeDistrict** [comment]
> > use chain to do that
> 
> Can you explain how? Thanks

You have to  provide your MongoDB collection schema to the LLM and with the "Messgae" from which you want to make a query to the database. the LLM return the MOngoDb QUestion which you can easily use in any Programmming language

**Comment by Zhreyu** [comment]
> > > use chain to do that
> > 
> > 
> > Can you explain how? Thanks
> 
> You have to provide your MongoDB collection schema to the LLM with the "Message" from which you want to make a query to the database. the LLM returns the MongoDB Query which you can easily use in any Programming language

Can you provide me with an example code or any link I can refer to? that would be very helpful

**Comment by omer-shahzad-codeDistrict** [comment]
> > > > use chain to do that
> > > 
> > > 
> > > Can you explain how? Thanks
> > 
> > 
> > You have to provide your MongoDB collection schema to the LLM with the "Message" from which you want to make a query to the database. the LLM returns the MongoDB Query which you can easily use in any Programming language
> 
> Can you provide me with an example code or any link I can refer to? that would be very helpful

Right Now I don't have a separate link for this particular thing I have implemented in my main codeBase which I can not share publicly soon I will share my medium where I am going to add this stuff with the code you can check and follow for more articles 

Here is the link you can follow when I posted you will get the notification "https://omershahzad.medium.com/"

**Comment by ahmetbagci8** [comment]
Any update?

**Comment by Ilya-666** [comment]
It would be a great thing, I was looking Studio 3T supposedly has an AI helper but you need to use chat gpt-4. Mongo want you to use Atlas. I'd love to get Mistral self-hosted handling questions of our self-hosted mongo.

**Comment by DataZenatic** [comment]
Hello~ Any update? anything equivalent to SQLDatabaseChain?

**Comment by omer-shahzad-codeDistrict** [comment]
> Hello~ Any update? anything equivalent to SQLDatabaseChain?

As I mentioned You can use the custom chain to build the query for Mongo DB by providing the table schema

**Comment by iw4p** [comment]
> > Hello~ Any update? anything equivalent to SQLDatabaseChain?
> 
> As I mentioned You can use the custom chain to build the query for Mongo DB by providing the table schema

Currently, [mongodb.com](https://www.mongodb.com/) added this feature to query and get data by prompt., but I think It can be useless to provide ALL THE TABLE SCHEMA to an LLM. Maybe there is a better way, specially when your data is huge.

**Comment by RichardHruby** [comment]
Is anyone working on this already? I would be happy to contribute.

**Comment by m-omer-shahzad** [comment]
Here is the solution: https://omershahzad.medium.com/agent-for-mongodb-langchain-ccf69913a11a

**Comment by AryanKarumuri** [comment]
Hey folks,
Is there any update?
