### ISSUE TITLE
Issue: LLMSingleActionAgent vs STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#7038]
### Issue you'd like to raise.

Is there a difference between these two agent types? Where should one use either of them?

**Comment by sarniu** [comment]
Yes, there is a difference between these two agents. As the name suggests, LLMSingleActionAgent is a simple agent which is designed to complete a single action. 
Whereas the STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION is a much more complex agent which is designed to carry on a conversation with the user i.e. it can respond to a wider range of prompts and questions.
However, STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION is slower than LLMSingleActionAgent and hence the latter is good at completing specific tasks quickly.

As for the question where should one use these agents, LLMSingleActionAgent should be used when you have to complete a specific task quickly and efficiently. 
While STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION is to be used when you need to have a conversation with a user and understand their requirements.
