### ISSUE TITLE
Chain support missing variable

### ISSUE THREAD

**Issue by NINTING** [langchain-ai/langchain#7044]
### Feature request

The LLM chain strictly validates all input variables against placeholders in the template. It will throw an error if they don't match. I wish it could handle missing variables, thus making the prompt template more flexible.

```python
  def _validate_inputs(self, inputs: Dict[str, Any]) -> None:
        """Check that all inputs are present."""
        missing_keys = set(self.input_keys).difference(inputs)
        if missing_keys:
            raise ValueError(f"Missing some input keys: {missing_keys}")
```

### Motivation

I'm using jinja2 to build a generic prompt template, but the chain's enforcement on variable validation forces me to take some extra steps, such as pre-rendering the prompt before running it through the chain. 

I hope the official could support the handling of missing variables.

### Your contribution

I think I could add a variable to determine whether to check the consistency between input variables and template variables, and then submit a PR. 

if you have better ideas, such as complex and complete solutions like custom detection rule callback functions.

I look forward to the official update. Please, I really need this, and I believe others do too. 

This will make the design of the Prompt more flexible.

**Comment by NINTING** [comment]
I realized my considerations may not be comprehensive enough. _validate_inputs may not only target the prompt template, but also the entire chain's input validation. Whether placeholder variables in the template allow missing should be determined by the prompt template itself.

Perhaps more detailed input validation could be achieved by inheriting from Chain. However, I still believe that the official side could consider more refined divisions for input validation.

**Comment by keenborder786** [comment]
@NINTING , If i understand your requirement correctly, you need the ability to pass in extra or less variables meaning `validate_jinja2` does not raise an exception in the following case:
```python
from langchain.prompts.base import validate_jinja2
jinja2_template = "Tell me a {{ adjective }} joke about {{ content }}"
validate_jinja2(jinja2_template , input_variables = ["adjective"])
```

**Comment by NINTING** [comment]
yes ,Since jinja2 provides control statements, paragraphs will not render when certain parameters are empty. I mainly use jinja2 as the template format.

**Comment by NINTING** [comment]
Moreover, I believe it should be the responsibility of the prompt template, not the chain, to strictly check the input parameters. 

After all, only the developers designing the prompt template know which parameters have a significant impact on the overall effectiveness of the prompt. And these parameters are absolutely essential.

Of course, for most prompts, all parameters are indispensable.

I'm just trying to articulate the division of functions between modules, as this seems to offer greater flexibility

**Comment by keenborder786** [comment]
okay. I will start on working on it @NINTING

**Comment by morganveyret** [comment]
Would it make sense to have the same for f-string based templates.
I am writing a custom StringPromptTemplate where I defined default values as the `format()` method arguments.
Due to the chain input validation I am forced to pass values if variables are present in `input_variables`, if not present they are just ignored.
I'd like to be able to create a custom prompt like this and have the chain just use the default values when not passed to `predict()`:
```python
def format(self,*,language,min_turns=10,max_turns=20):
.....
```
