### ISSUE TITLE
Chroma, Deeplake, Faiss indexing error ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10379,) + inhomogeneous part.

### ISSUE THREAD

**Issue by luca-git** [langchain-ai/langchain#7053]
### System Info

langchain Version: 0.0.220
python 3.9.16 
Windows 11/ ubuntu 22.04
anaconda

### Who can help?

@agola11 When ingesting the attched file (I'm attaching a zip as .pkl cannot be updated) in a normal document splitting loop
```python
embeddings = OpenAIEmbeddings()
chunk_sizes = [512, 1024, 1536]
overlap= 100
docs_n_code = "both"
split_documents = []
base_dir ="..."

for chunk_size in chunk_sizes:
    
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=overlap)
    docs = text_splitter.split_documents(documents)
    faiss_dir = "..."
    faiss_vectorstore = FAISS.from_documents(docs, embeddings)
    faiss_vectorstore.save_local(faiss_dir)
```
I get the following error:
```
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10379,) + inhomogeneous part.
```
similar errors occur with chroma and deeplake, locally. With chroma i can get the error more frequently even when ingesting other documents.
[api_docs.zip](https://github.com/hwchase17/langchain/files/11930126/api_docs.zip)

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python

from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.document_loaders import TextLoader

from langchain.document_loaders import TextLoader

with open('api_docs.pkl', 'rb') as file:
    documents = pickle.load(file)


text_splitter = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=100)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

db = FAISS.from_documents(docs, embeddings)
```

### Expected behavior

Create the index

**Comment by luca-git** [comment]
I checked the chunks that are not embedded, they don't have anything wrong, there should be something that checks the variable 'embedded_data' in dataset.py lines 405 to 409, 

```python
embedded_data = func(data)
try:
         embedded_data = np.array(embedded_data, dtype=np.float32)
except ValueError:
         raise IncorrectEmbeddingShapeError()
```

and force the embedding of the lists with size 1 or value = [nan] as the issue is there. maybe looping via:
```python
func(data_not embeed_for_some_reason)
```
That should happen in a loop as one iteration might not suffice, but this should be handled by you guys @hwchase17 , it's too big and core for me. The issue has been raised here as well: https://github.com/hwchase17/langchain/discussions/6127#discussion-5296078

**Comment by hwang136** [comment]
Same issue here~ 

` File "/usr/local/python38/lib/python3.8/site-packages/langchain_community/vectorstores/faiss.py", line 196, in __add
    vector = np.array(embeddings, dtype=np.float32)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1654,) + inhomogeneous part.`
