### ISSUE TITLE
Chain.run() without any param will cause error

### ISSUE THREAD

**Issue by jasoncaojingren** [langchain-ai/langchain#7059]
### System Info
Langchain 0.0.221
WSL
Python 3.11

###
If design a very simple chain which do not need any input parameters. Then run it, it will throw error. I think this without any input params may be useful.

    llm = conn.connecting.get_model_azureopenai()
    mem = langchain.memory.ConversationBufferMemory()
    msg1 = langchain.prompts.HumanMessagePromptTemplate.from_template("Hi there!")
    prompt1 = langchain.prompts.ChatPromptTemplate.from_messages([msg1])
    print(prompt1.input_variables)

    chain1 = langchain.chains.LLMChain(
        llm=llm,
        prompt=prompt1,
        memory=mem,
    )
    resp1 = chain1.run()
    print(resp1)

==================
Error:

/usr/local/miniconda3/bin/python /mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py 
Traceback (most recent call last):
  File "/mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py", line 87, in <module>
    run2()
  File "/mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py", line 81, in run2
    resp1 = chain1.run()
            ^^^^^^^^^^^^
  File "/usr/local/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 296, in run
    raise ValueError(
ValueError: `run` supported with either positional arguments or keyword arguments, but none were provided.
[]

Process finished with exit code 1

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Step1, develop a simple chain

/usr/local/miniconda3/bin/python /mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py 
Traceback (most recent call last):
  File "/mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py", line 87, in <module>
    run2()
  File "/mnt/c/TechBuilder/AIML/LangChain/Dev20230701/chains/runchain1.py", line 81, in run2
    resp1 = chain1.run()
            ^^^^^^^^^^^^
  File "/usr/local/miniconda3/lib/python3.11/site-packages/langchain/chains/base.py", line 296, in run
    raise ValueError(
ValueError: `run` supported with either positional arguments or keyword arguments, but none were provided.
[]

Process finished with exit code 1

Step 2, run it without input params, because it does not need any input params.

### Expected behavior

Should run without error

**Comment by molntamas** [comment]
Is there a clean solution for this which is not a workaround?
