### ISSUE TITLE
OPENAI_FUNCTIONS Agent Memory won't work inside of Streamlit st.chat_input element

### ISSUE THREAD

**Issue by hinskip92** [langchain-ai/langchain#7061]
### System Info

langchain = 0.0.218
python = 3.11.4

### Who can help?

@hwchase17 , @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

To reproduce:

1. Follow [Add Memory Open Ai Functions](https://python.langchain.com/docs/modules/agents/how_to/add_memory_openai_functions)
2. Import Streamlit
3. Create Chat Element using st.chat_input 
4. Try running agent through Streamlit

### Expected behavior

The agent memory works correctly when the Agent is called via ``` agent_chain.run("Insert prompt") ```  but when this is being done via a Streamlit Chat element like:

```python
if prompt := st.chat_input():
    st.session_state.messages.append({"role": "user", "content": prompt})
    st.chat_message("user").write(prompt)
    with st.spinner('Thinking...'):
        st_callback = StreamlitCallbackHandler(st.container())
        agent_chain.run(prompt, callbacks=[st_callback])
    st.chat_message("assistant").write(response)
    st.session_state.messages.append({"role": "assistant", "content": response})
``` 

It no longer works.

**Comment by alice23sav** [comment]
have you solved the issue? Any suggestions? I have the same problem

**Comment by alice23sav** [comment]
actually in my case the memory works fine when I call the agent directly in a while loop, observing its working process in terminal. When I use the chat structures of streamlit, the memory does no longer work. 
here's a snippet of my code :
this is the function I use to define the agent, along with its memory component:
def response(llm_large ,tools):
    
    
    agent_kwargs = {
        "extra_prompt_messages": [MessagesPlaceholder(variable_name='memory')],
        "system_message": SystemMessage(
          content="""Act as an italian public administration employee.    
          
          Always answer in italian."""         
          ),
    }
    memory = ConversationBufferMemory(memory_key='memory',return_messages=True)
    openai_agent= initialize_agent(
        tools, 
        llm=llm_large, 
        agent=AgentType.OPENAI_FUNCTIONS,
        verbose=True,         
        agent_kwargs=agent_kwargs,
        memory=memory)
    
    return openai_agent, memory
--------
in the main_streamilit.py file this is what I do:
 openai_agent, memory = response(llm_large, tools)
...
if "messages" not in st.session_state:
            st.session_state.messages = []

        for message in st.session_state.messages:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])

        if memory not in st.session_state:
            st.session_state['memory'] = []        

        
        try:
            if prompt := st.chat_input():
                st.session_state.messages.append({"role": "user", "content": prompt})
                st.chat_message("user").write(prompt)
                with st.spinner('Thinking...'):
                    #st_callback = StreamlitCallbackHandler(st.container())
                    
                    answer= openai_agent.run({"input":prompt, "memory": memory})
                    
                    
                st.chat_message("assistant").write(answer)
                st.session_state.messages.append({"role": "assistant", "content": answer})
                
                    
        except Exception as e:
            st.error(f"Error occurred: {e}")
------------
It perfercly works with the retrieval chains as tools and the multiple action process, but it doesn't keep track of any of its past taken steps.
Any idea?? thx

**Comment by AnhNgDo** [comment]
@hinskip92 
Hello, just wonder if you managed to find a solution for this? - I'm stuck with the same issue :(

Here is the code:
`# Accept user input
if question := st.chat_input("Ask me any thing..."):
    # Add user message to chat history
    st.session_state.messages.append({"role": "user", "content": question})
    # Display user message in chat message container
    with st.chat_message("user"):
        st.markdown(question)
    # Display assistant response in chat message container
    with st.chat_message("assistant"):
        st_callback = StreamlitCallbackHandler(st.container()) # streamlit container for output
        answer = agent.run(question, callbacks=[st_callback, langfuse_handler])
        st.session_state.messages.append({"role": "assistant", "content": answer})
        st.markdown(answer)`

**Comment by alice23sav** [comment]
@AnhNgDo I solved the issue using the new streamlit-langchain component StreamlitChatMessageHistory.
You can check this repo as reference: 
https://github.com/langchain-ai/streamlit-agent/blob/main/streamlit_agent/chat_with_documents.py

**Comment by AnhNgDo** [comment]
@alice23sav  - thanks for the suggestion! Tried StreamlitChatMessageHistory and it works 👍 

@hinskip92 - see my code below if you still have issue. Note the agent_kwargs is important to add MessgagePlaceHolder to the Agent Prompt, wouldn't work otherwise:

```
# CHAT MEMORY FOR AGENT
chat_history_size = 3   # store 3 recent chat messages
msgs = StreamlitChatMessageHistory()
memory = ConversationBufferWindowMemory(memory_key="chat_history", chat_memory=msgs, k=chat_history_size, return_messages=True)
agent_kwargs = {
    "extra_prompt_messages": [MessagesPlaceholder(variable_name="chat_history")],
}


# initialize agent executor (run time)
agent = initialize_agent(
    tools, 
    llm, 
    agent=AgentType.OPENAI_FUNCTIONS, 
    verbose=True,
    agent_kwargs=agent_kwargs,
    memory=memory,
)
```

**Comment by Chandru-21** [comment]
@AnhNgDo  I had similar issue,this solution works out. Thanks !

**Comment by gpy1234** [comment]
@Chandru-21 I am getting the following error. Did you get the same error as well?

```
from langchain.memory.chat_message_histories import StreamlitChatMessageHistory
ImportError: cannot import name 'StreamlitChatMessageHistory' from 'langchain.memory.chat_message_histories'
```

**Comment by Chandru-21** [comment]
@gpy1234   Update langchain library and try it out.
