### ISSUE TITLE
OpenAIChat(streaming=True) donot work

### ISSUE THREAD

**Issue by yuanjie-ai** [langchain-ai/langchain#7062]
### System Info

index = VectorstoreIndexCreator(vectorstore_cls=DocArrayInMemorySearch, embedding=embeddings) 
index = index.from_loaders([PyMuPDFLoader('孙子兵法.pdf')])
query = '孙子兵法的战略'
index.query(llm=OpenAIChat(streaming=True), question=query, chain_type="stuff")

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
index = VectorstoreIndexCreator(vectorstore_cls=DocArrayInMemorySearch, embedding=embeddings) 
index = index.from_loaders([PyMuPDFLoader('孙子兵法.pdf')])
query = '孙子兵法的战略'
index.query(llm=OpenAIChat(streaming=True), question=query, chain_type="stuff")
```
streaming ...

### Expected behavior

```
index = VectorstoreIndexCreator(vectorstore_cls=DocArrayInMemorySearch, embedding=embeddings) 
index = index.from_loaders([PyMuPDFLoader('孙子兵法.pdf')])
query = '孙子兵法的战略'
index.query(llm=OpenAIChat(streaming=True), question=query, chain_type="stuff")
```
streaming ...

**Comment by dmyoung9** [comment]
`OpenAIChat` is deprecated. Use `ChatOpenAI` instead.

**Comment by dmyoung9** [comment]
This appears to be the exact same issue as #9038.
