### ISSUE TITLE
Issue:IndexError: list index out of range

### ISSUE THREAD

**Issue by ninjiakill** [langchain-ai/langchain#7067]
### System Info

langchain-0.0.221
python-3.10.11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.schema import Document
from langchain.vectorstores import FAISS

list_of_documents = [
    Document(page_content="foo", metadata=dict(page=1)),
    Document(page_content="bar", metadata=dict(page=1)),
    Document(page_content="foo", metadata=dict(page=2)),
    Document(page_content="barbar", metadata=dict(page=2)),
    Document(page_content="foo", metadata=dict(page=3)),
    Document(page_content="bar burr", metadata=dict(page=3)),
    Document(page_content="foo", metadata=dict(page=4)),
    Document(page_content="bar bruh", metadata=dict(page=4)),
]
db = FAISS.from_documents(list_of_documents, embeddings)

### Expected behavior

Now  i'm following the FAISS Similarity Search with filtering code example on official Website,which is on https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/faiss,an error occur:
IndexError                                Traceback (most recent call last)
Cell In[56], line 13
      2 from langchain.vectorstores import FAISS
      3 list_of_documents = [
      4     Document(page_content="foo", metadata=dict(page=1)),
      5     Document(page_content="bar", metadata=dict(page=1)),
   (...)
     11     Document(page_content="bar bruh", metadata=dict(page=4)),
     12 ]
---> 13 db = FAISS.from_documents(list_of_documents, embeddings)

File [d:\Python310\lib\site-packages\langchain\vectorstores\base.py:332](file:///D:/Python310/lib/site-packages/langchain/vectorstores/base.py:332), in VectorStore.from_documents(cls, documents, embedding, **kwargs)
    330 texts = [d.page_content for d in documents]
    331 metadatas = [d.metadata for d in documents]
--> 332 return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)

File [d:\Python310\lib\site-packages\langchain\vectorstores\faiss.py:551](file:///D:/Python310/lib/site-packages/langchain/vectorstores/faiss.py:551), in FAISS.from_texts(cls, texts, embedding, metadatas, ids, **kwargs)
    525 @classmethod
    526 def from_texts(
    527     cls,
   (...)
    532     **kwargs: Any,
    533 ) -> FAISS:
    534     """Construct FAISS wrapper from raw documents.
...
--> 314     results[indices[i]].append(batched_embeddings[i])
    315     num_tokens_in_batch[indices[i]].append(len(tokens[i]))
    317 for i in range(len(texts)):

IndexError: list index out of range

How's that happened and how can i fix it?

**Comment by albertovilla** [comment]
hi @ninjiakill, I haven't been able to reproduce this error. I have tried with a HF embedding function (I don't see the `embeddings` part in your code). See below:

```python
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS
from langchain.schema import Document

docs = [
    Document(page_content="foo", metadata=dict(page=1)),
    Document(page_content="bar", metadata=dict(page=1)),
    Document(page_content="foo", metadata=dict(page=2)),
    Document(page_content="barbar", metadata=dict(page=2)),
    Document(page_content="foo", metadata=dict(page=3)),
    Document(page_content="bar burr", metadata=dict(page=3)),
    Document(page_content="foo", metadata=dict(page=4)),
    Document(page_content="bar bruh", metadata=dict(page=4)),
]

embeddings = HuggingFaceEmbeddings(model_name="all-mpnet-base-v2")

db = FAISS.from_documents(docs, embeddings)

query = "What is foo?"
docs = db.similarity_search(query)

print(docs[0].page_content)
```

The documents are inserted in to the vector database and the query is performed as expected.

**Comment by ninjiakill** [comment]
The embedding function that I simply used is ：

from langchain.embeddings.openai import OpenAIEmbeddings
os.environ['OPENAI_API_KEY'] = “SK-XXXXXX”
os.environ['OPENAI_API_BASE'] = ”https://api.closeai-asia.com/v1“
embeddings = OpenAIEmbeddings()

still dont figure it out

**Comment by ninjiakill** [comment]
figure out if the list_of_documents has only one element，the code works fine，which is:

import os
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.schema import Document
from langchain.vectorstores import FAISS

os.environ['OPENAI_API_KEY'] = "sk-*******"
os.environ['OPENAI_API_BASE'] = "https://api.closeai-asia.com/v1"
embeddings = OpenAIEmbeddings()

list_of_documents = [
    Document(page_content="foo", metadata=dict(page=1))
]
db = FAISS.from_documents(list_of_documents, embeddings)

When it goes with two or more elements,the"list index out of range" error rasied up
might it has anything to do with openai api proxy,or just due to some other reasons？

**Comment by albertovilla** [comment]
If the example code in my previous comment with the `HuggingFaceEmbeddings` works in your environment maybe it has something to do with the `OpenAIEmbeddings`. Unfortunately I cannot test it with that as I don't have an API key anymore :)

Did you try the example in the Get Started section of the documentation? It's not exactly what you want to do but it could help to isolate the problem.
https://python.langchain.com/docs/modules/data_connection/vectorstores/

**Comment by ninjiakill** [comment]
Yes,I also tried the example in the Get Started section of the documentation(in the Get Started section of the documentation)，since I dont have "state_of_the_union.txt"，I  wrote one with content:
    Tonight. I call on the Senate to: Pass the Freedom to Vote Act. Pass the John Lewis Voting Rights Act. And while you’re at it, pass the Disclose Act so Americans can know who is funding our elections.

    Tonight, I’d like to honor someone who has dedicated his life to serve this country: Justice Stephen Breyer—an Army veteran, Constitutional scholar, and retiring Justice of the United States Supreme Court. Justice Breyer, thank you for your service.

    One of the most serious constitutional responsibilities a President has is nominating someone to serve on the United States Supreme Court.

    And I did that 4 days ago, when I nominated Circuit Court of Appeals Judge Ketanji Brown Jackson. One of our nation’s top legal minds, who will continue Justice Breyer’s legacy of excellence.


save it as "state_of_the_union.txt",then excute  the example code as below:
import os
os.environ['OPENAI_API_KEY'] = "sk-*****"
os.environ['OPENAI_API_BASE'] = "https://api.closeai-asia.com/v1"
from langchain.document_loaders import TextLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS

raw_documents = TextLoader('D:/file_db/database/temp.txt').load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(raw_documents)

embeddings = OpenAIEmbeddings()
db = FAISS.from_documents(documents, embeddings)

And I found that when the "chunk_size=1000", it works fine cause documents just has 1 element;
when "chunk_size=500" or smaller,the "list index out of range" showed up with documents has more then 1 element

**Comment by Taikono-Himazin** [comment]
I don't know if it's the same as this, but I'm getting a similar error.

You can download the directory loaded by DirectoryLoader from here.
https://docs.python.org/3/download.html

The code is below.

```python
import os

from dotenv import load_dotenv
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.document_loaders import DirectoryLoader, UnstructuredHTMLLoader
from langchain.indexes import VectorstoreIndexCreator

loader = DirectoryLoader(
    './python-3.11.5-docs-html',
    glob='**/*.html',
    show_progress=True,
    loader_cls=UnstructuredHTMLLoader, 
    use_multithreading=True
)
embeddings = OpenAIEmbeddings(
    openai_api_key=os.environ.get('OPENAI_SECRET_KEY'),
    openai_organization=os.environ.get('OPENAI_ORGANIZATION')
)
index = VectorstoreIndexCreator(vectorstore_cls=FAISS, embedding=embeddings).from_loaders([loader])
index.vectorstore.save_local("faiss_index")
```

The error is below.
```
  File "C:\Users\XXX\Documents\sorces\git_main\tools\create_faiss_file\create_faiss_index.py", line 41, in <module>
    index = VectorstoreIndexCreator(vectorstore_cls=FAISS, embedding=embeddings).from_loaders([loader])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\Documents\python_envs\env_3.11\Lib\site-packages\langchain\indexes\vectorstore.py", line 82, in from_loaders
    return self.from_documents(docs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\Documents\python_envs\env_3.11\Lib\site-packages\langchain\indexes\vectorstore.py", line 87, in from_documents
    vectorstore = self.vectorstore_cls.from_documents(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\Documents\python_envs\env_3.11\Lib\site-packages\langchain\vectorstores\base.py", line 417, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\Documents\python_envs\env_3.11\Lib\site-packages\langchain\vectorstores\faiss.py", line 603, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
  File "C:\Users\XXX\Documents\python_envs\env_3.11\Lib\site-packages\langchain\vectorstores\faiss.py", line 562, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
                                  ~~~~~~~~~~^^^
IndexError: list index out of range
```

Strangely, this problem does not occur with python3.9 even with the same version of langchain.
Is it a specific issue since 3.10?

**Comment by xalakox** [comment]
as a workaround I ended up setting the chunk_size to 1:
```
            embeddings = OpenAIEmbeddings(
                chunk_size=1,
            )
```
I guess not ideal but the badge size internally kept returning a single item while the collection expected to match the number of docs.

**Comment by vithalsm** [comment]
Hello, I am hitting the exact same issue.  Any solutions yet please?  Using python 3.11
