### ISSUE TITLE
DOC: The LLM type given in the Caching section is incorrect. It should be changed from ChatOpenAI to ChatGPT

### ISSUE THREAD

**Issue by luyuan1997** [langchain-ai/langchain#7129]
### Issue with current documentation:

During the use of ChatOpenAI, it was found that even if langchain.llm_cache=True is set, the answer is different each time for the same question, such as "What is LangChain".
 Upon tracing the source code, it was discovered that ChatOpenAI inherited BaseChatModel, which does not support the caching logic.
 If the type of LLM switched from ChatOpenAI to ChatGPT, caching will be effective. Therefore, using ChatOpenAI in the LangChain Document example is incorrect, and should be replaced with ChatGPT. The corresponding address is: https://python.langchain.com/docs/modules/model_io/models/chat/how_to/chat_model_caching.

### Idea or request for content:

It is suggested to modify the example and replace ChatOpenAI with ChatGPT.
llm = ChatGPT()

**Comment by rjarun8** [comment]
The base chat model does seem to support cache. Am i missing something here?:  
[https://github.com/hwchase17/langchain/blob/81eebc40702ff676c2f62c42ab4c6732ff794164/langchain/chat_models/base.py](url)

```
class BaseChatModel(BaseLanguageModel, ABC):
    cache: Optional[bool] = None ##Caching supported in base model
    verbose: bool = Field(default_factory=_get_verbosity)
    """Whether to print out response text."""
    callbacks: Callbacks = Field(default=None, exclude=True)
    callback_manager: Optional[BaseCallbackManager] = Field(default=None, exclude=True)
    tags: Optional[List[str]] = Field(default=None, exclude=True)
    """Tags to add to the run trace."""
```

**Comment by luyuan1997** [comment]
Thank you very much for your reply. The new version of BaseChatModel in LangChain already supports caching, and using the new version has resolved my question. Thank you for your response.
