### ISSUE TITLE
"ConversationBufferMemory" object has no field "buffer" 

### ISSUE THREAD

**Issue by ybbthou8** [langchain-ai/langchain#7135]
### System Info

0.0.220

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

self.memory = ConversationBufferMemory(memory_key="chat_history", output_key='output')
self.agent.memory.buffer = self.agent.memory.buffer + Human_prompt + 'AI: ' + AI_prompt

### Expected behavior

no error output

**Comment by albertovilla** [comment]
I'm not sure what you're trying to do but you have created the `ConversationBufferMemory `and stored it in `self.memory`, if you want to access the buffer property of the `ConversationBufferMemory` shouldn't you refer to `self.memory.buffer`?

**Comment by ybbthou8** [comment]
> I'm not sure what you're trying to do but you have created the `ConversationBufferMemory `and stored it in `self.memory`, if you want to access the buffer property of the `ConversationBufferMemory` shouldn't you refer to `self.memory.buffer`?

I may need to add the relationship between the two memories：
        self.agent = initialize_agent(
            self.tools,
            self.llm,
            agent="conversational-react-description",#AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
            verbose=True,
            memory=self.memory,
            return_intermediate_steps=True,
            agent_kwargs={'prefix': PREFIX, 'format_instructions': FORMAT_INSTRUCTIONS,
                          'suffix': SUFFIX}, 
        )
so in my point, self.agnet.memory and self.memory are the same object.
