### ISSUE TITLE
Returns the standone alone question while using ConversationalRetrievalChain 

### ISSUE THREAD

**Issue by czmmiao** [langchain-ai/langchain#7136]
### Feature request

I am using the ConversationalRetrievalChain to retrieve answers for questions while condensing the chat history to a standalone question.  However, the standalone question would show in the streaming output. 

I expect only to return the final answer. Is there any way to achieve it?

### Motivation

The immediate is not necessary for the answer.

### Your contribution

I am not sure.

**Comment by MuriloBianco** [comment]
Yes, the problem also occurs for me. I'm using ConversationalRetrievalChain with streaming, but when there is memory, the response I receive is the question itself

**Comment by MuriloBianco** [comment]
I don't know if it helps, but I can send some prints, look:

This is my input using fastapi (the question is in Portuguese BR):
![image](https://github.com/langchain-ai/langchain/assets/113943582/0ea85ff5-efe0-4c29-b16b-bc4bd934796b)

This is the response in terminal ():
![image](https://github.com/langchain-ai/langchain/assets/113943582/6cbad5c0-1697-4505-8e27-54c159a27c71)


Response in fastapi:
![image](https://github.com/langchain-ai/langchain/assets/113943582/a84ed2fc-3388-456b-a8a6-fe4005ac4596)
