### ISSUE TITLE
OpenAIFunctionsAgent + ConversationalChatAgent?

### ISSUE THREAD

**Issue by jbkoh** [langchain-ai/langchain#7163]
### Feature request

I'd like to make the user experience more conversational while supporting OpenAI functions. However, OpenAIFunctionsAgent implementation doesn't accept "memory" to make it more conversational. I'd like to have ReACT planning capability + functions as tools. I think the minimal implementation is to just add a memory to OpenAIFunctionsAgent.

### Motivation

While answering and executing tools is a great feature supported by OpenAIFunctionsAgent, more streamlined user experiences like chat are often desired as well.

### Your contribution

Happy to make a PR with a guideline if this is something desired in langchain.

**Comment by hwchase17** [comment]
it should support memory - https://python.langchain.com/docs/modules/agents/how_to/add_memory_openai_functions

does this not work?

**Comment by jbkoh** [comment]
Ah, I missed the `extra_prompt_messages` and it's working now. Thanks for the quick response!

**Comment by jbkoh** [comment]
I think I still want to know how to utilize OpenAIFunctions within the ReACT framework? Can ReACT recognize functions and utilize the functions API?

**Comment by NikolaMr** [comment]
@jbkoh I'm trying to accomplish the same thing myself so I'm following this as well :)

**Comment by zzz2016** [comment]
me too.
I refactor my project with OpenAIFunctionsAgent, It's awesome for simple task but difficult to complex one.
