### ISSUE TITLE
DOC: The Quickstart tutorial for Agents has an error

### ISSUE THREAD

**Issue by minseochh02** [langchain-ai/langchain#7166]
### Issue with current documentation:

https://python.langchain.com/docs/get_started/quickstart.html
On the above link, I have tried following along on google colab and ran into an issue as following:

Observation: Olivia Wilde started dating Harry Styles after ending her years-long engagement to Jason Sudeikis — see their relationship timeline.
Thought:I have found information about Olivia Wilde's boyfriend. Now I need to calculate his current age raised to the 0.23 power.

Action:
```
{
  "action": "Calculator",
  "action_input": "age ^ 0.23"
}
```

As you can see, instead of getting information about Harry Styles' age, it just puts in the string 'age' and raises value error.
This is quite weird seeing the tutorial for agents work well:
https://python.langchain.com/docs/modules/agents.html
What could be the issue?

**Comment by jjurg** [comment]
I experience similar issues with textbook examples since yesterday. When I switch to gpt-4 it all works. I started ti question myself. but convinced it did work with 3.5-turbo before as the examples default to 3.5.

**Comment by danpechi** [comment]
I opened an issue similar to this with GPT3.5 Turbo - this seems fairly widespread
