### ISSUE TITLE
SupabaseVectorStore.from_documents returns APIError: {'code': '22P02'

### ISSUE THREAD

**Issue by DmitryKatson** [langchain-ai/langchain#7179]
### System Info

Langchain version: 0.0.221

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When trying to index documents return API error
`APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "54d7bd9c-9822-40ca-ade6-ae173b65d34e"'}`

This code perfectly worked on previous versions of Langchain. 
After upgrading, got the error. 

Supabase backend didn't change.

`
# load required libraries
from langchain.document_loaders import WebBaseLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import SupabaseVectorStore
from supabase import Client, create_client
import os
from dotenv import load_dotenv

# load document from web
url = "https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase"
loader = WebBaseLoader(url)
documents = loader.load()

# split documents into chunks
docs_splitter = RecursiveCharacterTextSplitter(chunk_size=2500,chunk_overlap=250)
splitted_docs = docs_splitter.split_documents(documents=documents)

# initialize embeddings model
embeddings = OpenAIEmbeddings()

# initialize vector store
supabase_url = os.getenv('SUPABASE_URL')
supabase_key = os.getenv('SUPABASE_KEY')
supabase = create_client(supabase_url, supabase_key)

# save values to supabase
vector_store = SupabaseVectorStore.from_documents(documents=splitted_docs, embedding=embeddings, client=supabase)
`

### Expected behavior

document embeddings should be saved in a Supabase database

**Comment by DanielhCarranza** [comment]
The error still remains even if you change `id bigint` to `id uuid` on Supabase. Also if you provide your own ids you can't because the method `from_texts` only uses their own ids.

**Comment by Yogev-Sepana** [comment]
I experienced this issue as well.
I recreated my table with a uuid id field:

```
       -- Create a table to store your documents
       create table documents (
       id **uuid** primary key,
       content text, -- corresponds to Document.pageContent
       metadata jsonb, -- corresponds to Document.metadata
       embedding vector(1536) -- 1536 works for OpenAI embeddings, change if needed
       );
```

       But now I'm getting a timeout exception: `httpx.WriteTimeout: The write operation timed out`
