### ISSUE TITLE
does llms.AzureOpenAI support gpt4 or gpt-32k?

### ISSUE THREAD

**Issue by crazyseabiscuit** [langchain-ai/langchain#7182]
### System Info

llm = AzureOpenAI(
model_name="gpt-4-32k",
engine="gpt-4-32k"
)
llm("tell me a joke")
Exception:
The completion operation does not works with the specific model, gpt-4-32k, pls choose different model....

Environment:
LangChain:0.0.218

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Environment:
LangChain:0.0.218

llm = AzureOpenAI(
model_name="gpt-4-32k",
engine="gpt-4-32k"
)
llm("tell me a joke")
run the code above

### Expected behavior

the program should work

**Comment by Xmaster6y** [comment]
GPT-4 like models are only available through the `ChatCompletion` API, both with OpenAI and Azure. See [OpenAI model-endpoint-compatibility](https://platform.openai.com/docs/models/model-endpoint-compatibility) and [Azure models specs](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models#gpt-4-models-1) which directly derive from OpenAI specs.
