### ISSUE TITLE
Issue: RetrievalQAWithSourcesChain gives error 'too many values to unpack (expected 2)' after running.

### ISSUE THREAD

**Issue by vianamatesanz** [langchain-ai/langchain#7184]
Hello,

I'm using _langchain_ for QA with court case documents. More specifically, the RetrievalQAWithSourcesChain to retrieve the answer and document source information. However, when running the chain with embedded documents, I get the following error:

```
ValueError: too many values to unpack (expected 2)
Traceback:


    response = qa({"question": pregunta}, return_only_outputs=True)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 166, in __call__
    raise e
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\base.py", line 160, in __call__
    self._call(inputs, run_manager=run_manager)
File "C:\Anaconda3\envs\iagen_3_10\lib\site-packages\langchain\chains\qa_with_sources\base.py", line 132, in _call
    answer, sources = re.split(r"SOURCES:\s", answer)

```

The passed documents are the sections from the court case. I added the following **metadata** fields:

1. Source: PDF file name.
2. Section: Name of the section
3. Section_chunk:  Numeral value used for identification in case the section was divided into chunks.
4. Page: Page where the section chunk starts.

The documents are passed as retriever to the chain with FAISS (FAISS.from_documents(documents, self.embeddings)).

I tried out two approaches (both resulting in the same error): 
1. providing the _load_qa_chain_ as chain 
2. creating it using the class method **_.from_chain_type_**

My question is why does this error ocurrs. And also, if the type of metadata used may cause the errors.
Thank you in advance!

**Comment by krishnapraveen7** [comment]
Is there any solution for this?
