### ISSUE TITLE
DOC: https://python.langchain.com/docs/modules/model_io/models/llms/integrations/sagemaker

### ISSUE THREAD

**Issue by kiranshivaraju** [langchain-ai/langchain#7187]
### Issue with current documentation:
https://python.langchain.com/docs/modules/model_io/models/llms/integrations/sagemaker

This example is not working. I've just copy pasted the code from here and ran it in my notebook instance. I'm using falcon-40b-instruct model. 

The error I'm getting is as follows
Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (422) from primary with message "Failed to deserialize the JSON body into the target type: missing field `inputs` at line 1 column 509".

**Comment by JorisVdBos** [comment]
The bot is almost correct: If you change:
`json.dumps({prompt: prompt, **model_kwargs})`
to:
`json.dumps({"inputs": prompt, **model_kwargs})`

The issue is solved.
