### ISSUE TITLE
kwargs are forgot to send to huggingface pipeline call

### ISSUE THREAD

**Issue by zhangmaosen** [langchain-ai/langchain#7192]
https://github.com/hwchase17/langchain/blob/e27ba9d92bd2cc4ac9ed7439becb2d32816fc89c/langchain/llms/huggingface_pipeline.py#L169

should modified to 
#response = self.pipeline(prompt)
response = self.pipeline(prompt, **kwargs)

**Comment by andrei-edward-popa** [comment]
Can you create a PR with this change? It is an easy fix, so maybe it will be merged fast.
