### ISSUE TITLE
ConversationalRetrievalChain return only the prompt not the answer

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#7193]
### System Info

**Python : Python 3.9.13
Langchain: langchain==0.0.219
OS : Ubuntu**

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
    from langchain.chains import ConversationalRetrievalChain
    from langchain.vectorstores import Chroma
    from langchain.embeddings import SentenceTransformerEmbeddings
    embeddings =  SentenceTransformerEmbeddings(model_name="paraphrase-MiniLM-L6-v2")
    from langchain.document_loaders import PyPDFLoader
    loader = PyPDFLoader("file.pdf")
    documents = loader.load()
    from langchain.llms import HuggingFaceHub
    model = HuggingFaceHub(repo_id="facebook/mbart-large-50",
                       model_kwargs={"temperature": 0, "max_length":200},
                       huggingfacehub_api_token=HUGGING_FACE_API_KEY)
    from langchain.text_splitter import CharacterTextSplitter
    text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
    texts=text_splitter.split_documents(documents)
    db = Chroma.from_documents(texts, embeddings)
    retriever = db.as_retriever(search_type="similarity", search_kwargs={"k": 1})
    qa = ConversationalRetrievalChain.from_llm(model,retriever)
    chat_history= []
    query = "sample query"
    result = qa({"question": query,"chat_history":chat_history})
    print("\nResult of ConversationalRetrievalChainMethod")
    print(result)
```

It return the **result** as follows
{'question': 'sample question', 'chat_history': [], '**answer': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.**"}

### Expected behavior

Expecting the answer in the result. But it returns the prompt itself now

**Comment by hwchase17** [comment]
this is probably a combination of using an example question (try asking a real question) and a not great model. what happens if you try for real with openai?

**Comment by pradeepdev-1995** [comment]
@hwchase17  So you are asking to test with **openai** model instead of **HuggingFaceHub** model?

**Comment by arreumb** [comment]
I have the same problem, with openai model.
