### ISSUE TITLE
Add Document Index Information for QA Inline Citations

### ISSUE THREAD

**Issue by wiskojo** [langchain-ai/langchain#7239]
### Feature request

Include source document index information in the combine document chain prompt. For example in `_get_inputs` of `StuffDocumentChain` we could make the following change (in addition to corresponding changes to `format_document`):

```
# From
doc_strings = [format_document(doc, self.document_prompt) for doc in docs]

# To
doc_strings = [format_document(doc, i, self.document_prompt) for i, doc in enumerate(docs)]
```

### Motivation

The point of this change is to enable QA based chains (e.g. `ConversationalRetrievalChain`) to easily do inline citations using the source document's index.

### Prompt
```
Context:
[1] Harrison went to Harvard.
[2] Ankush went to Princeton.
[3] Emma went to Yale.

Question:
Where did Harrison and Emma go to college?
```

### Response
```
Harrison went to Harvard【1】 and Emma went to Yale【3】.
```

This type of structure is also found in popular "QA" models like Bing Chat and ChatGPT's Browse feature (WebGPT etc.). I feel like there should at least be high-level options to enable something like this without having to make custom modifications/extensions to the existing chains.

Without explicitly including these document indices, I find prompting the LLM to cite documents by index could lead to hallucinated citations (e.g. with retrieved `k=4` documents it cites "[8]")

## More Details

As far as I can tell, existing QA implementations in Langchain seem to return source documents separately (i.e. `return_source_documents=True`), or at the end of the response (e.g. `{'output_text': ' The president thanked Justice Breyer for his service.\nSOURCES: 30-pl'}` as in [document-qa-with-sources](https://python.langchain.com/docs/modules/chains/additional/question_answering#document-qa-with-sources)) rather than provide them in-line.

Even newer approaches using OpenAI's Functions API e.g. from `create_citation_fuzzy_match_chain` and `create_qa_with_sources_chain` do not provide this option.

The approach of [QA with sources chain](https://python.langchain.com/docs/modules/chains/additional/openai_functions_retrieval_qa) has a drawback that the LLM has to generate the entire source of the document (e.g. full URL). This is slower because we can just reference the index of the document instead. Also, this is prone to hallucination especially with `gpt-3.5` where fake sources (like URLs) could be generated.

Similarly, the method in [Question-Answering Citations](https://python.langchain.com/docs/modules/chains/additional/qa_citations) provides quotes from source documents, but doesn't actually identify which document they're from. Referencing documents by index should help reduce hallucination and generation speed here as well.

### Your contribution

I'm happy to assist with this, but first I'd like to gather feedback on the idea. It's possible that there are existing approaches or best practices that I'm not familiar with, which could facilitate inline citations without additional implementation. If there are any recommendations on how to proceed with this, I'd be interested in having a discussion around that.

**Comment by harisrab** [comment]
Have you found any details on this. To perform in-text citations there seems to be no straightforward way.

**Comment by bkamapantula** [comment]
Looks like it can be achieved via RetrievalQAWithSourcesChain: https://python.langchain.com/docs/use_cases/question_answering#return-citations

Have you tried it?

**Comment by wiskojo** [comment]
Please correct me if I'm wrong, but I don't believe `RetrievalQAWithSourcesChain` would allow me to achieve what I'm looking for. While it does provide the sources that each response is based on, it does not provide the citation/reference number within the response text itself (i.e. the in-line "[doc#]", "【doc#】", etc. next to the statement which is making that reference). These numbers are often used by the front-end as hooks to render clickable links within the response body to the source content (e.g. in the case of ChatGPT Browse and Bing Chat).

I have not found an elegant solution for this, and have largely resorted to simply overriding the `_get_inputs` function of `StuffDocumentsChain` to use a slightly different `format_document` implementation which takes an additional "document index" as a parameter. Happy to hear any alternative solutions people have come across.

**Comment by bkamapantula** [comment]
You're right. I'm pretty much in the same place now as it doesn't provide in-line citations.

**Comment by halyearzero** [comment]
Bump. A user being able to verify that the chain is correct is important, and in-line citations a-la Bing are the most helpful for this.

**Comment by Tsukumizu** [comment]
Excuse me, do you have any ideas about in-line citations so far?

**Comment by Tsukumizu** [comment]
I recommend that you just directly write some words like "please cite the viewpoints from context in the form of [1], [2] to verify your idea" included in your custom prompt, then put it into VectorStoreRetriever. It behaves well.

**Comment by Tsukumizu** [comment]
@mariushes 
1. We need to rewrite the get_relevant_docs() in VectorStoreRetriever, suppose that it returns k=8 documents, you should explicitly add a prefix like [1], [2], .....[8] for each document to let LLM know the order of documents. 
2. Rewrite the prompt template of RetrieverQA. After you say words like "Please refer to the context provided", tell LLM "be sure to cite the corresponding index in the context (eg: [1], [2], etc.) to support your idea."
3. Then our LLM will behave like "According to [3][6], this company is worth investing in."

**Comment by wiskojo** [comment]
Thanks everyone for the thoughtful discussion. Below are my thoughts and an example code snippet with some findings after having worked on this for a bit.

For me, I used `ConversationalRetrievalChain`, which I modified with a custom `StuffDocumentsChain` as mentioned in my OP. Following is a snippet containing an example (not exactly the implementation/prompt I used, but this is just to illustrate the idea):

```python
# Function to format each document with an index, source, and content.
def format_document(doc, index, prompt):
    """Format a document into a string based on a prompt template."""
    # Create a dictionary with document content and metadata.
    base_info = {"page_content": doc.page_content, "index": index, "source": doc.source}
    
    # Check if any metadata is missing.
    missing_metadata = set(prompt.input_variables).difference(base_info)
    if len(missing_metadata) > 0:
        raise ValueError(f"Missing metadata: {list(missing_metadata)}.")
    
    # Filter only necessary variables for the prompt.
    document_info = {k: base_info[k] for k in prompt.input_variables}
    return prompt.format(**document_info)

# Custom chain class to handle document combination with source indices.
class StuffDocumentsWithIndexChain(StuffDocumentsChain):
    def _get_inputs(self, docs, **kwargs):
        # Format each document and combine them.
        doc_strings = [
            format_document(doc, i, self.document_prompt)
            for i, doc in enumerate(docs, 1)
        ]
        
        # Filter only relevant input variables for the LLM chain prompt.
        inputs = {k: v for k, v in kwargs.items() if k in self.llm_chain.prompt.input_variables}
        inputs[self.document_variable_name] = self.document_separator.join(doc_strings)
        return inputs

# Define a chat prompt with instructions for citing documents.
combine_doc_prompt = PromptTemplate(
    input_variables=["context", "chat_history", "question"],
    template="""Your role is to provide information based on the following sources.
When referencing the documents, add a citation right after. Use "[SOURCE_NUMBER]" for the citation (e.g. "The Space Needle is in Seattle [1][2].").

Sources:
{context}

Chat History:
{chat_history}

Question:
{question}"""
)

# Initialize the custom chain with a specific document format.
combine_docs_chain = StuffDocumentsWithIndexChain(
    llm_chain=LLMChain(
        llm=ChatOpenAI(),
        prompt=combine_doc_prompt,
    ),
    document_prompt=PromptTemplate(
        input_variables=["index", "source", "page_content"],
        template="[{index}] {source}:\n{page_content}",
    ),
    document_variable_name="context",
)
```

Some of my thoughts with this are as follows:

1. You could also add the prompt "When referencing the documents, add a citation right after. Use '[SOURCE_NUMBER]' for the citation (e.g., 'The Space Needle is in Seattle [1][2].')" without modifying the document prompt to add the document index prefix ([1][2], etc.). This approach will also work but leads to higher rates of hallucination because it relies on the model counting the documents to derive the index rather than being explicit about it.

2. Index-based citations, even with the document index prefix, could lead to hallucinations. With `gpt-3.5-turbo`, I've seen a fair amount of hallucinations, e.g., k=5 documents retrieved, but the model outputs [7][8], etc. With `gpt-4`, this rarely happens.

3. Another idea is you could also output the entire source directly, e.g., "The Space Needle is in Seattle [https://www.spaceneedle.com/]." This should (probably?) lower hallucinations at the cost that the model has to output entire sources like URLs rather than just a number.

Open to hearing more about how others have approached in-line citations and their findings/experiences.

**Comment by tickx-cegeka** [comment]
@wiskojo 
Thank you for your insights, I have been looking for exactly this.

You meantioned you use ConversationalRetrievalChain. How do you use your "combine_docs_chain" variable in relation to the ConversationalRetrievalChain?

I would think it is like this:
```
ConversationalRetrievalChain.from_llm(
            llm=llm,
            retriever=retriever,
            return_source_documents=True,
            combine_docs_chain_kwargs= {"combine_documents_chain": combine_docs_chain}
        )   
```

But then I get the following error:
_ValidationError: 1 validation error for StuffDocumentsChain
combine_documents_chain
  extra fields not permitted (type=value_error.extra)_
  
Could anyone tell me how to use the above code? Thanks

**Comment by Tsukumizu** [comment]
@tickx-cegeka 
To use a ConversationalRetrievalChain, You can refer to this:

convR_qa = ConversationalRetrievalChain(
    retriever=customRetriever,
    memory=memory,
    question_generator=question_generator_chain,
    combine_docs_chain=qa_chain,
    
    return_source_documents=True,
    return_generated_question=True,
    verbose=True
)

Where question_generator_chain is a LLMChain, and qa_chain is a load_qa_chain. If you want more information about chains above, please ask me.

**Comment by tickx-cegeka** [comment]
@Tsukumizu 

The argument "combine_docs_chain=qa_chain" does not work. See https://github.com/langchain-ai/langchain/issues/9052 .
I have to pass it in "combine_docs_chain_kwargs". See my previous comment. However there I get the "extra fields not permitted" error on StuffDocumentsChain.

**Comment by tickx-cegeka** [comment]
@Tsukumizu  My apologies for the oversight. You are right, it is working right now, thank you.

**Comment by Tsukumizu** [comment]
> @mariushes
> 
> 1. We need to rewrite the get_relevant_docs() in VectorStoreRetriever, suppose that it returns k=8 documents, you should explicitly add a prefix like [1], [2], .....[8] for each document to let LLM know the order of documents.
> 2. Rewrite the prompt template of RetrieverQA. After you say words like "Please refer to the context provided", tell LLM "be sure to cite the corresponding index in the context (eg: [1], [2], etc.) to support your idea."
> 3. Then our LLM will behave like "According to [3][6], this company is worth investing in."

It seems like only ChatGPT can work well with this prompt template.  I have tried ChatGLM2-6B and Baichuan2-13B, both of them didn't catch the command "cite the index like [1], [2]". Can anyone provide a better template to help a "weak" LLM to realize his task and handle this situation?

**Comment by timxieICN** [comment]
Hi @wiskojo - I tested something like this following your sample code
https://github.com/langchain-ai/langchain/issues/7239#issuecomment-1703916108

But I see very inconsistent results every time when I ask the questions - ie, sometimes it attaches a citation but sometimes it does not.

Do you observe the same?

**Comment by timxieICN** [comment]
btw, has anyone had any success integrating [create_citation_fuzzy_match_chain](https://api.python.langchain.com/en/latest/_modules/langchain/chains/openai_functions/citation_fuzzy_match.html) with `ConversationalRetrievalChain`?

**Comment by aiwalter** [comment]
can anyone post a full running (minimal) example using the code from @wiskojo ?

**Comment by tickx-cegeka** [comment]
I believe it is still relevant.
