### ISSUE TITLE
How to disable the OpenAI initialization when you're not using an OpenAI model

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#7251]
### Feature request

how to disable the OpenAI initialization when you're not using an OpenAI model.
[Please check this issue](https://github.com/hwchase17/langchain/issues/7189#issuecomment-1621931461)

### Motivation

 I am trying to build a VectorstoreIndexCreator using the following configuration

embeddings= SentenceTransformerEmbeddings embeddings
vectorstore_cls = Chroma
llm = HuggingfaceHub Model

Note: I am not using any openai model as llm or embedding purpose

here is the code
```
  from langchain.indexes import VectorstoreIndexCreator
  from langchain.vectorstores import Chroma
  from langchain.text_splitter import CharacterTextSplitter
  from langchain.embeddings import SentenceTransformerEmbeddings
  from langchain.llms import HuggingFaceHub
  from langchain.document_loaders import PyPDFLoader
  loader = PyPDFLoader("pdffile.pdf")

  embeddings =  SentenceTransformerEmbeddings(model_name="paraphrase-MiniLM-L6-v2")
  model = HuggingFaceHub(repo_id="facebook/mbart-large-50",
                       model_kwargs={"temperature": 0, "max_length":200},
                       huggingfacehub_api_token=HUGGING_FACE_API_KEY)
  index = VectorstoreIndexCreator(
                                  embedding=embeddings,
                                  vectorstore_cls=Chroma,
                                  text_splitter=CharacterTextSplitter(chunk_size=100,chunk_overlap=0)
                                  ).from_loaders([loader])
  result = index.query(llm=model,question=query,chain_type="refine")
```
But still iam getting the open_ai key dependency error when i run the code

```
Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```
using langchain version: langchain==0.0.219

### Your contribution

To disable the OpenAI initialization when you're not using an OpenAI model

**Comment by techwithshadab** [comment]
Any work around for this? I'm also running into same issue.

**Comment by IvoPereira** [comment]
From what I understand, as long as we are using Chroma we can't disable OpenAI since it runs remotely on their servers?

> Chroma provides a convenient wrapper around [OpenAI](https://openai.com/api/)'s embedding API. This embedding function runs remotely on OpenAI's servers, and requires an API key. You can get an API key by signing up for an account at OpenAI.

https://docs.trychroma.com/embeddings/openai

I would like to prevent this as well, but I believe it is a hard dependency from what I understand of it.
