### ISSUE TITLE
Demonstrate-Search-Predict: Composing retrieval and language models for knowledge-intensive NLP

### ISSUE THREAD

**Issue by JohnNay** [langchain-ai/langchain#726]
https://github.com/stanfordnlp/dsp/blob/main/intro.ipynb

**Comment by JohnNay** [comment]
Looks like we could incorporate this and use their hosted retrieval model

**Comment by KasperOnPC** [comment]
100% looks very promising for answering questions with sources!

**Comment by aabdullah-getguru** [comment]
I'd love to do this, including maybe implement myself. Not sure if there's a group somewhere already working on this though? https://github.com/hwchase17/langchain/issues/753 . I don't see any branches though.

**Comment by songole** [comment]
Interested in this feature. Any thoughts on this?
