### ISSUE TITLE
Langchain Tools and Agents

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#7269]
### Issue you'd like to raise.

I am using Tools and Agents to query on different vectorstores. But when I am asking question which is not from the vectorstore.It responds i dont know. So is there any approach i can try where if the answer is not from the vectorstore i can carry out the conversation like chatgpt. If Yes? Can you Please let me know how we can integrate this

**Comment by Kuramdasu-ujwala-devi** [comment]
I am using Tools and Agents to query on different vectorstores. But when I am asking question which is not from the vectorstore.It responds. So is there any approach i can try where if the answer is not from the vectorstore it should respond i didn't found the answer.

**Comment by Ajaypawar02** [comment]
Try to use this approach https://python.langchain.com/docs/modules/agents/how_to/custom_agent_with_tool_retrieval

**Comment by khurramwbox** [comment]
I encountered a similar issue myself, but I discovered a **solution**. Just include this instruction in your **system message** prompt exactly as it is, and it should function very effectively.

`system_message = SystemMessage(
    content=(
        "REMEMBER : If you're unable to find an answer using the retriever, utilize the OpenAI Language Model to generate a response. Avoid responses like 'I don't know'; instead, provide helpful answers."
    )
)`
