### ISSUE TITLE
'Qdrant.from_documents' Memory overflow

### ISSUE THREAD

**Issue by zhugexinxin** [langchain-ai/langchain#7272]
### Issue you'd like to raise.

```
def handle_embeddings(payload):
     loader = UnstructuredPDFLoader(payload["filepath"])
     documents = loader.load()

    text_splitter = SpacyTextSplitter(pipeline=payload["language"], chunk_size=1536, chunk_overlap=0)
    docs = text_splitter.split_documents(documents)
    
    embeddings = OpenAIEmbeddings(**payload)
    qdrant = Qdrant.from_documents(
        docs, embeddings,
        path=path,
        collection_name=collection_name,
    )
    
import dramatiq
from dramatiq.brokers.redis import RedisBroker
from tasks import handle_embeddings

redis_broker = RedisBroker(url='redis://redis.helloreader.docker/10')
dramatiq.set_broker(redis_broker)

@dramatiq.actor(max_retries = 0)
def handle_embeddings_task(payload):
    result = handle_embeddings(payload)
    return result
```

Due to the time-consuming nature of embeddings and storing them in a vector database, I opted for asynchronous queue tasks to handle them. However, I noticed that when processing documents of size 30 MB, the memory usage of the queue task kept increasing until it eventually crashed due to overflow. At this point, I investigated and found that the memory overflow occurred even before the embeddings interface was called, indicating that the issue was with the `Qdrant.from_documents` method. I have been searching for the root cause for a while but haven't found it yet.

### Suggestion:

I hope someone who is familiar with the `Qdrant.from_documents` method or has knowledge of other possible causes can help me resolve this issue. 
The document size of approximately 30 MB corresponds to approximately 560,000 tokens.
During the process, I tried using Dramatiq, Celery, and RQ, and encountered the same issue with all of them. Therefore, we can exclude the possibility of the issue being specific to these queue tools.

**Comment by zhugexinxin** [comment]
> * langchain/vectorstores/qdrant.py

Can this solution be added to the same collection_name

**Comment by hopkins385** [comment]
yes, I've just opened the following PR which adds the ability to add vectors to an existing collection in a automated way. #7334

**Comment by zhugexinxin** [comment]
> 第7334章

Thank you very much, but I have a question.
For example
I will be a pdf book in 319 pieces, the expectation is that Qdrant.from_documents will launch 319 embeddings interface, but eventually every time I try, I found that he will, the first time he will happen embeddings interface about 1000 tokens, the rest will be sent to all, too large will cause a limit.

I read the source code and I think it is expected to split the number of times to send, I can't understand why this is the case.

**Comment by zhugexinxin** [comment]
> mh.. not sure if I can help you with that. To me it's unclear if your issue is caused by one or multiple of the following:
> 
> * batch size
> * memory limits
> * api rate limits exceeded (RPM/TPM)
> * issues with the file itself
> * issues with the host machine (e.g. high cpu load, low memory)
> 
> So I guess you need to dig a bit deeper and debug. I would propose to start with a smaller file. eg. split manually the file in multiple files and try to feed the smaller files (piece by piece) into the system. If that works, start increasing the filesize (with filesize I mean amount of characters/pages)
> 
> In my case I am using a different approach and use the following code as described here [https://python.langchain.com/docs/modules/data_connection/retrievers](https://python.langchain.com/docs/modules/data_connection/retrievers/#walkthrough) PS: I've indexed pdf files with up to 150 pages without an issue. Maybe worth to try it out? idk
> 
> ```python
> VectorstoreIndexCreator(
>     vectorstore_cls=Qdrant,
>     embedding=OpenAIEmbeddings(),
>     text_splitter=SpacyTextSplitter(pipeline=payload["language"], chunk_size=1536, chunk_overlap=0)
>     vectorstore_kwargs=dict(
>           host=qdrant
>           port=6333
>           grpc_port=6334
>           prefer_grpc=True
>           collection_name=collection_name,
>           recreate_collection=False, # <-- this is new, and only available after my PR was commited to main
>           vector_size=1536 # <-- this is new, and only available after my PR was commited to main
>        ),
> ).from_documents(documents)
> ```

Here's the translation of your concerns and observations into English:

I've attempted to consider various factors that might be causing my issue:

1. Batch size (I've already divided the document into 319 chunks)
2. Memory limit (I have 8GB of RAM)
3. Exceeding the API rate limit (RPM/TPM) (the limit is 350,000 tokens and 3,500 requests per minute, which I'm sure I haven't exceeded)
4. Issues with the file itself (this has been ruled out)
5. Host issues (such as high CPU load, low memory) (this has been ruled out)
6. Types of text (I've tried multiple texts, 300,000 tokens, 600,000 tokens)

Here is the code I'm executing:

```python
loader = UnstructuredPDFLoader(filepath)
documents = loader.load()
text_splitter = TokenTextSplitter(chunk_size=1536, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings(**payload)
qdrant = Qdrant.from_documents(
    docs, embeddings,
    path=vectorstore_path,
    collection_name=collection_name,
)
```

Additionally, I would like to highlight that there seems to be a memory overflow issue with the SpacyTextSplitter when you have a very large document and you're using the Chinese language model. It appears that the memory starts to dramatically increase until it leads to memory overflow and the program exits.

After executing, the result I get from the official API is as follows:


2023/7/8 17:28:21 | text-embedding-ada-002 Model Request, total tokens: 344317
2023/7/8 17:28:15 | text-embedding-ada-002 Model Request, total tokens: 813

**Comment by hopkins385** [comment]
@rlancemartin any ideas if this could be a memory leak?
