### ISSUE TITLE
[FEATURE] SOLR Based Vector Store

### ISSUE THREAD

**Issue by samadkoita** [langchain-ai/langchain#7273]
### Feature request

This adds support for Apache SOLRs vector search capabilities
(https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html)

### Motivation

As SOLR is a commonly used search index and now offers this feature, it is important to allow SOLR users to be able to integrate seamlessly with LangChain (and the associated benefits).

### Your contribution

I can try submitting a PR

**Comment by moinuddinsyed** [comment]
Any development on this?

**Comment by irene1391** [comment]
Any updates?

**Comment by Noor-A-Khalifa** [comment]
> I have started working on this, checking the functionalities on python client

Is there a possible release date?

**Comment by MitchellJThomas** [comment]
Awesome. I'm also interested in your progress @subkanthi

**Comment by vincentlambert** [comment]
We just released a package for adding SolR support to Langchain.
[https://pypi.org/project/eurelis-langchain-solr-vectorstore/](https://pypi.org/project/eurelis-langchain-solr-vectorstore/)
