### ISSUE TITLE
anthropic_version = packaging.version.parse(version("anthropic")) AttributeError: module 'packaging' has no attribute 'version'

### ISSUE THREAD

**Issue by junruxiong** [langchain-ai/langchain#7283]
### System Info

When I initialise ChatAnthropic(), it got the error:

anthropic_version = packaging.version.parse(version("anthropic"))
AttributeError: module 'packaging' has no attribute 'version'

### Who can help?

@hwchase17 @agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chat_models import ChatOpenAI, ChatAnthropic
llm = ChatAnthropic()

### Expected behavior

As shown above.

**Comment by dudesparsh** [comment]
I tried to run the same, and I am able to reproduce the same error (AttributeError: module 'packaging' has no attribute 'version')

1. What's working is the solution suggested by bot i.e.

```
from importlib.metadata import version
from packaging.version import parse
```
2. What might be going wrong in our case is that, package.version is getting confused with importlib.metadata.version and there is a mixup.
- What we can do to resolve is:
```
from importlib.metadata import version
from packaging.version import parse

anthropic_version = parse(version("anthropic"))
```

**Comment by baskaryan** [comment]
out of curiosity, what python version are you getting issue with?

**Comment by junruxiong** [comment]
> 

My version is 3.10.12
