### ISSUE TITLE
What is the best size for a chunk

### ISSUE THREAD

**Issue by MIMI180306** [langchain-ai/langchain#7322]
### Issue you'd like to raise.

I used RecursiveCharacterTextSplitter.from_tiktoken_encoder to split a document, and if I set chunk_size to 2000, OpenAI cannot answer my question by the documents, if I set chunk_size to 500, OpenAI can work very well. I want to know, As a rule of thumb, what is the best size for a chunk

**Comment by SDcodehub** [comment]
no straight forward answer, trial and error, can suggest few point to look to decide

1. check the splits post loading `vector_store.similarity_search_with_score()` make sure it makes sense to your question
2. experiment with `k` and` score_threshold`
4. try to change to different splitter, make sure your splits are correct
5. it all of it does not work, meaning you data has parse answer, either do some post processing on data, clean up, add some manual text splitting characters, etc
6. try the compressor techniques to get crucks of data if required
