### ISSUE TITLE
Issue: question about agents

### ISSUE THREAD

**Issue by zhangjunqiang** [langchain-ai/langchain#7336]
I want pass "chat_history" to the agents like :
```python
...
agent = initialize_agent(tools, llm, agent=AgentType.OPENAI_FUNCTIONS, verbose=True)
response = agent.run({"input": {"chat_history": _message_to_tuple(history), "question": query}})

```
but got an error. how can i pass 'chat_history' to the agent?

**Comment by sarniu** [comment]
could you pls tell what error u got?

**Comment by zhangjunqiang** [comment]
> could you pls tell what error u got?

how to pass chat_history to agent?

**Comment by zhangjunqiang** [comment]
![image](https://github.com/hwchase17/langchain/assets/5388898/a9f54818-b6a6-42e7-8a76-ec547950ad9f)

**Comment by zhangjunqiang** [comment]
I set the ConversationalRetrievalChain with return_source_documents=True,

**Comment by zhangjunqiang** [comment]
the tools contains a ConversationalRetrievalChain, and the chain set return_source_documents = True.

**Comment by zhangjunqiang** [comment]
if i remove _return_source_documents = True._. it will throw another err.
![image](https://github.com/hwchase17/langchain/assets/5388898/6f4353be-d8cc-4cf6-b69a-de7ba1141954)
