### ISSUE TITLE
Create a built in translator for SelfQueryRetriever for Elasticsearch

### ISSUE THREAD

**Issue by lemig** [langchain-ai/langchain#7341]
### Feature request

Inferring query filters from natural language is powerful. The SelfQuery retriever is a great implementation but is not yet compatible with Elasticseach.

### Motivation

Choosing Elasticsearch as a vector store is interesting in terms of hybrid search.
It also makes sense when you have an established infrastructure and technical expertise.

 

### Your contribution

cc: @jeffvestal, @derickson

**Comment by joemcelroy** [comment]
Now merged https://github.com/langchain-ai/langchain/pull/9248. Waiting for release.
