### ISSUE TITLE
Issue: When implementing Cypher Search using  neo4j environment

### ISSUE THREAD

**Issue by NLPAN** [langchain-ai/langchain#7346]
### Issue you'd like to raise.

python environment：
neo4j 5.0.0
neobolt 1.7.17
neo4j version: neo4j-35-apoc:v20220808

报错：
File "D:\Anaconda3\envs\langchain\lib\site-packages\neo4j_sync\io_bolt3.py", line 200, in run
raise ConfigurationError(
neo4j.exceptions.ConfigurationError: Database name parameter for selecting database is not supported in Bolt Protocol Version(3, 0). Database name 'neo4

**Comment by NLPAN** [comment]
👍 Thank you very much, this potential solution is useful and it solves my problem.

**Comment by VinayaSathyanarayana** [comment]
I have the same issue

**Comment by VinayaSathyanarayana** [comment]
I get error in the statement verify_connectivity() . Unable to make progress
