### ISSUE TITLE
ConversationBufferWindowMemory returns empty string on empty history instead of empty array.

### ISSUE THREAD

**Issue by Joseph-Cardwell** [langchain-ai/langchain#7365]
### System Info

Python 3.10
Langchain 0.0.226

Windows 11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
```
import os, langchain

os.environ['SERPAPI_API_KEY'] = ""
os.environ['OPENAI_API_KEY'] = ""

from langchain.chains import LLMChain
from langchain.agents import ConversationalChatAgent, SelfAskWithSearchChain, AgentExecutor
from langchain.memory import ConversationBufferWindowMemory
from langchain.tools import Tool
from langchain.llms import OpenAI

conversation_buffer_window_memory: ConversationBufferWindowMemory = ConversationBufferWindowMemory(
    input_key="input", memory_key="chat_history")

search = langchain.SerpAPIChain()
self_ask_and_search = SelfAskWithSearchChain(llm=OpenAI(), search_chain=search, verbose=True)

tools = [
    Tool(
        name="Search",
        func=self_ask_and_search.run,
        description="useful for when you need to answer questions about current events",
    )
]

prompt = ConversationalChatAgent.create_prompt(
    tools, input_variables=["input", "chat_history", "agent_scratchpad"]
)

llm_chain = LLMChain(
    llm=OpenAI(temperature=0), prompt=prompt)

agent = ConversationalChatAgent(
    llm_chain=llm_chain, tools=tools, verbose=True)

agent_executor = AgentExecutor.from_agent_and_tools(
    agent=agent, tools=tools, verbose=True, memory=conversation_buffer_window_memory)
  
agent_executor.run('what is the capital of texas?')
```

returns the following error:
(<class 'ValueError'>, ValueError('variable chat_history should be a list of base messages, got '), <traceback object at 0x0000027BA6366E40>)

### Expected behavior

Return the LLM result while updating the memory mechanism.

**Comment by Joseph-Cardwell** [comment]
The problem appears in the file:
langchain/memory/buffer_window.py

It appears to be caused in the following function:
langchain.memory.buffer_window.ConversationBufferWindowMemory.load_memory_variables

In load_memory_variables it makes a call to get_buffer_string which converts the empty array of messages to an empty string, which then throws the error in langchain/prompts/chat.py when it tests for memory to be an instance of List.

**Comment by Joseph-Cardwell** [comment]
This would likely break compatibility. If the API is going to make this alteration then an automatic adapter must be employed. Either way, it is a larger consideration.

**Comment by erlandsen-tech** [comment]
This is still relevant as of 0.345

**Comment by umair313** [comment]
@hwchase17, @efriis @baskaryan did you didn't fix it intentionally?
