### ISSUE TITLE
conversationalRetrievalChain - how to improve accuracy

### ISSUE THREAD

**Issue by RanElgedawy** [langchain-ai/langchain#7368]
I am using conversational retrieval chain with memory, but I am getting incorrect answers for trivial questions. 
Any suggestions what can I do to improve the accuracy of the output? 

#memory = ConversationEntityMemory(llm=llm, return_messages=True)
memory=ConversationBufferMemory(memory_key="chat_history",output_key='answer')
chain = ConversationalRetrievalChain.from_llm(
llm = llm,
retriever=retriever,
memory=memory, 
get_chat_history=lambda h :h,
return_source_documents=True)

![memoryerror](https://github.com/hwchase17/langchain/assets/95228400/03142f3f-65ff-48ad-8890-e64856749a58)

**Comment by nithinreddyyyyyy** [comment]
Hey! I'm using the below code

```
llm_name = "gpt-3.5-turbo"
os.environ["OPENAI_API_KEY"] = ""

st.set_page_config(layout="wide")

def load_db(file_path, chain_type, k):
    loader = PyPDFLoader(file_path)
    documents = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=300)
    docs = text_splitter.split_documents(documents)
    embeddings = OpenAIEmbeddings()
    db = DocArrayInMemorySearch.from_documents(docs, embeddings)
    retriever = db.as_retriever(search_type="similarity", search_kwargs={"k": k})
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(model_name=llm_name, temperature=1), 
        chain_type=chain_type, 
        retriever=retriever, 
        return_source_documents=False,
        return_generated_question=False
    )
    return qa 
```

Even though i'm using RecursiveCharacterTextSplitter, it is returning below error

`InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5822 tokens. Please reduce the length of the messages.`

Is there anything we can do?
