### ISSUE TITLE
from langchain.llms import OpenAI causing ImportError: cannot import name 'Protocol'

### ISSUE THREAD

**Issue by srikanthgirijala** [langchain-ai/langchain#7369]
### System Info

from typing_extensions import Protocol
from langchain.llms import OpenAI
llm = OpenAI(model_name='text-davinci-003', temperature=0.7, max_tokens=512)
print(llm)
-----------------------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-28-c0d04f63c5e1> in <module>
      1 get_ipython().system('pip install typing-extensions==4.3.0')
      2 from typing_extensions import Protocol
----> 3 from langchain.llms import OpenAI
      4 llm = OpenAI(model_name='text-davinci-003', temperature=0.7, max_tokens=512)
      5 print(llm)

~\anaconda3\envs\GPTLLM\lib\site-packages\langchain\__init__.py in <module>
      1 """Main entrypoint into package."""
      2 
----> 3 from importlib import metadata
      4 from typing import Optional
      5 

~\anaconda3\envs\GPTLLM\lib\importlib\metadata\__init__.py in <module>
     15 import collections
     16 
---> 17 from . import _adapters, _meta
     18 from ._collections import FreezableDefaultDict, Pair
     19 from ._functools import method_cache, pass_none

~\anaconda3\envs\GPTLLM\lib\importlib\metadata\_meta.py in <module>
----> 1 from typing import Any, Dict, Iterator, List, Protocol, TypeVar, Union
      2 
      3 
      4 _T = TypeVar("_T")
      5 

ImportError: cannot import name 'Protocol'

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.llms import OpenAI
llm = OpenAI(model_name='text-davinci-003', temperature=0.7, max_tokens=512)
print(llm)

### Expected behavior

OpenAI
Params:{model_name, temperature, max_tokens}

**Comment by adityassharma-ss** [comment]
If someone else faces the same issue, try running

```
pip install langchain_community
```

it might work
