### ISSUE TITLE
how to use a model loaded from HuggingFace transformers?

### ISSUE THREAD

**Issue by i-am-neo** [langchain-ai/langchain#737]
@hwchase17 Thanks for sharing this project. I've encountered several challenges in trying to use it and hope you can point me to examples. I haven't found examples in the docs/issues.

1. I'd like to use an LLM already loaded from transformers on a set of text documents saved locally.  Any suggestions?

Something like?
`model_name = "google/flan-t5-large"
t5_tokenizer = T5Tokenizer.from_pretrained(model_name)
llm = T5ForConditionalGeneration.from_pretrained(model_name, max_length = 500)`

2. I'd like to use a custom "search" function for an agent.  Can you please share an example? (For what it's worth, I tried FAISS which didn't yield accurate results).

**Comment by logan-markewich** [comment]
Yea, I second this. Is there no way to use LangChain with a model that is loaded locally?

**Comment by logan-markewich** [comment]
I think you'll need to create a custom LLM class: https://langchain.readthedocs.io/en/latest/modules/llms/examples/custom_llm.html

**Comment by solyarisoftware** [comment]
q1: using a local model.

Right question. 
As far as I understand, so far you can't, but you can use a model from huggingface hub. See:  
https://langchain.readthedocs.io/en/latest/modules/llms/integrations/huggingface_hub.html

**Comment by logan-markewich** [comment]
You need an API key for HuggingFaceHub to work

If you have an LLM locally already, you can follow the example on the page I linked above

I tried with google-flan... it was meh. Tough to get it to follow instructions in the prompt. Maybe GPT-J would fair better

**Comment by logan-markewich** [comment]
Yea, the docs leave a lot to be desired lol

Here's a quick example

```
import torch
from langchain.llms.base import LLM
from transformers import pipeline

class FlanLLM(LLM):
    model_name = "google/flan-t5-xl"
    pipeline = pipeline("text2text-generation", model=model_name, device="cuda:0", model_kwargs={"torch_dtype":torch.bfloat16})

    def _call(self, prompt, stop=None):
        return self.pipeline(prompt, max_length=9999)[0]["generated_text"]

    def _identifying_params(self):
        return {"name_of_model": self.model_name}

    def _llm_type(self):
        return "custom"
```

**Comment by solyarisoftware** [comment]
yes, thanks. The documentation has been just improved about it: https://github.com/hwchase17/langchain/issues/936#issuecomment-1422283398

It could be useful to have a notebook that merge your code above here:
https://langchain.readthedocs.io/en/latest/ecosystem/huggingface.html#llm

See also https://github.com/hwchase17/langchain/issues/936
