### ISSUE TITLE
ChromaDB score goes the wrong way

### ISSUE THREAD

**Issue by NicoWeio** [langchain-ai/langchain#7384]
### System Info

> langchain==0.0.227
> langchainplus-sdk==0.0.20
> chromadb==0.3.26

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I'm sorry, but I don't have the time to carve out a MRE right now. My take is that it's still better to report it than not to.

### Expected behavior

`similarity_search_with_score` returns the distance as expected, but `similarity_search_with_relevance_scores` gives the same values, so that the closest distances return the smallest values, even though the output of the latter function is supposed to be higher for vectors that are closer:

> `similarity_search_with_relevance_scores`
> Return docs and relevance scores in the range [0, 1].
> 0 is dissimilar, 1 is most similar.

**Comment by paplorinc** [comment]
I just noticed the same, the code should do a `1 - score`

**Comment by NicoWeio** [comment]
Can't check right now, but maybe this has been resolved by the merge of #6570?
