### ISSUE TITLE
Add the `name` and `arguments` from `function_call` to `on_llm_new_token` when `streaming=True`

### ISSUE THREAD

**Issue by rasca** [langchain-ai/langchain#7385]
### Feature request

Add the `name` and `arguments` from `function_call` to `on_llm_new_token` when `streaming=True`.

Now it's getting called with an empty token several times and no way to retrieve the `function_call['arguments']`.

We need to add this to every llm/

### Motivation

I'm streaming my calls (user get's to see the output realtime) to an llm and I've decided to use function calls so I get a structured output. I want to show the user the results (one argument is `message`) but I cannot cause only the tokens from `content` are streamed. 

Using the plain openai api I can do this.

### Your contribution

I can contribute a PR to a model and some tests, but I need guidance, as what the API should be. As I understand only `chat_models.openai` should be modified.

**Comment by rasca** [comment]
For my usecase I subclassed `ChatOpenAI` and modified `_generate` and `_agenerate` functions changing these lines:

Inside `_generate`
from `run_manager.on_llm_new_token(token)`
to `run_manager.on_llm_new_token(token, arguments=_function_call["arguments"])`

Inside `_agenerate`
from `await run_manager.on_llm_new_token(token)`
to `await run_manager.on_llm_new_token(token, arguments=_function_call["arguments"])`

Please tell me if this is a desired change, in that case I'll try to provide a test and a PR. We would still need to decide how to pass the function name.

**Comment by dmyoung9** [comment]
@rasca Have you been able to make this work?

I found a slightly different solution (since it seems the code structure has changed a bit since this issue was opened) that seems to be working for me:
```python
...
            if run_manager:
                if (chunk_content := chunk.additional_kwargs.get("function_call", None)) is not None:
                    run_manager.on_llm_new_token(chunk_content['arguments'])
                else:
                    run_manager.on_llm_new_token(chunk.content)
```
This properly passes all of the tokens to my callback handlers, and works with `LLMChain` and `ChatOpenAI` instances, including where they are invoked during a tool or agent run 😁

**Comment by dmyoung9** [comment]
Whoops, opened it towards my own fork first 😅

**Comment by duy-nguyen-ts** [comment]
Hi everybody, I also have the same issue when using function calling and callbacks streaming. Does langchain fix this issue ?😄

**Comment by dmyoung9** [comment]
> Hi everybody, I also have the same issue when using function calling and callbacks streaming. Does langchain fix this issue ?😄

#8991 should fix it.

**Comment by nfcampos** [comment]
This is now available as the `chunk` arg to on_llm_new_token
