### ISSUE TITLE
InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5822 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#7411]
### System Info

Hey! Below is the code i'm using

```
llm_name = "gpt-3.5-turbo"
# llm_name = "gpt-4"
os.environ["OPENAI_API_KEY"] = ""

st.set_page_config(layout="wide")

def load_db(file_path, chain_type, k):
    loader = PyPDFLoader(file_path)
    documents = loader.load()
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=2000, chunk_overlap=300)
    docs = text_splitter.split_documents(documents)
    embeddings = OpenAIEmbeddings()
    db = DocArrayInMemorySearch.from_documents(docs, embeddings)
    retriever = db.as_retriever(search_type="similarity", search_kwargs={"k": k})
    qa = ConversationalRetrievalChain.from_llm(
        llm=ChatOpenAI(model_name=llm_name, temperature=1), 
        chain_type=chain_type, 
        retriever=retriever, 
        return_source_documents=False,
        return_generated_question=False
    )
    return qa 
```

Even though i'm using RecursiveCharacterTextSplitter function, it is returning below error. 

`InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5822 tokens. Please reduce the length of the messages.`

Is there anything which will fix this issue?

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

-

### Expected behavior

I'm using RecursiveCharacterTextSplitter function where it'll make use of the function and will exceed the context length. It should work right?

**Comment by clemlesne** [comment]
Seems related to https://github.com/langchain-ai/langchain/issues/1349.

**Comment by GeneralLHW** [comment]
I also encountered this problem, but I haven't found a solution yet. I only asked 1+1, and this error occurred. I want to know how to see the content of prompt and completion when he said that the length is exceeded.
