### ISSUE TITLE
[Feature Request] Easy webserver with FastAPI

### ISSUE THREAD

**Issue by tiagoefreitas** [langchain-ai/langchain#742]
A built-in webserver that serves prompts as APIs with FastAPI.

lambdaprompt is similar to langchain prompt templates and implements this easily:

https://github.com/approximatelabs/lambdaprompt

I don't have any experience so can't do a PR now, but if no one else does I will try.

**Comment by tiagoefreitas** [comment]
I know its easy to create individual apis for each prompt, but something automated would be good, that also saves queries and results to a database.

Then we could build something like https://promptable.ai on top, in a standard way

**Comment by aschwa** [comment]
I have been playing with langchain and have experience building FastAPI apps, interested in taking this on.

**Comment by tiagoefreitas** [comment]
I built a cool generic api to call any prompt with an arbitrary number of parameters. I still need to do the same for calling the llm.

I have 0 experience with fastapi and haven't programmed for a few years but ChatGPT + Google do wonders.

from fastapi import FastAPI, HTTPException, Request
from <api.prompts> import <Add Prompt templates here>

app = FastAPI()

@app.get("/generatePrompt")
async def generatePrompt(request: Request):
    prompt_name = request.query_params.get("prompt")
    if not prompt_name:
        raise HTTPException(status_code=400, detail="Missing 'prompt' query parameter.")

    prompt_module = globals().get(prompt_name)

    prompt_template_class = getattr(prompt_module, prompt_name)

    if prompt_template_class is None:
        raise HTTPException(status_code=404, detail="Prompt template " + prompt_name + " not found.")
    
    params=dict(request.query_params);
    input_variables = [k for k in params.keys() if k != "prompt"]

    prompt_template = prompt_template_class(**{"input_variables": list(input_variables)});
    
    prompt = prompt_template.format(**params);
   
    return {"prompt": prompt}

`

This will instantiate the necessary template with the input variables from query parameters.
The "prompt" parameter is the name of the template class that must be in a file/module with the same name.
I'm sure this can be improved as it was built for my use case.

**Comment by tiagoefreitas** [comment]
I also want to add a way to get the llm to make up a template if one doesn't exist, to make the frontend always work even if the backend doesn't exist.

**Comment by tiagoefreitas** [comment]
Here is another version that create a different API per prompt, but not as useful for me.
```

@app.get("/generatePrompt/{prompt_name}")
async def generatePrompt(prompt_name: str, request: Request):
    prompt_module = globals().get(prompt_name)
    prompt_template_class = getattr(prompt_module, prompt_name)

    if prompt_template_class is None:
        raise HTTPException(status_code=404, detail="Prompt template " + prompt_name + " not found.")
    
    params=dict(request.query_params);
    input_variables=params.keys();
    prompt_template = prompt_template_class(**{"input_variables": list(input_variables)});
    
    prompt = prompt_template.format(**params);
   
    return {"prompt": prompt}
```

**Comment by SimonBiggs** [comment]
We're spinning up a FastAPI LLM server over at if that helps you:
https://github.com/assistancechat/assistance.chat/blob/main/src/python/assistance/_api/main.py

I initially wanted to base it on LangChain but for now have opted to directly create the chains ourselves.

**Comment by hemangjoshi37a** [comment]
I want to develop frontend for langchain. If anyone ineterested or has any lead please let me know ASAP.

**Comment by lucapericlp** [comment]
Not sure if still relevant but I've found [this repo](https://github.com/jina-ai/langchain-serve) in [the docs](https://python.langchain.com/en/latest/deployments.html) which seems applicable?
