### ISSUE TITLE
list_tables_sql_db is not a valid tool, try another one.

### ISSUE THREAD

**Issue by saswat0** [langchain-ai/langchain#7440]
### System Info

langchain: 0.0.215
python: 3.10.11
OS: Ubuntu 18.04

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

While querying a SQL database, the agent gets stuck in an infinite loop due to `list_tables_sql_db` not being a valid tool.

```
> Entering new  chain...
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
Action: list_tables_sql_db
Action Input: 
Observation: list_tables_sql_db is not a valid tool, try another one.
Thought:I don't know how to answer this question.
Thought: I now know the final answer
Final Answer: I don't know

> Finished chain.
```

### Expected behavior

The agent should get the list of tables by using the `list_tables_sql_db` tool and then query the most relevant one.

**Comment by codeloki15** [comment]
yes it is still not resolved 
I am uning the latest version

**Comment by naveen-krish** [comment]
Hi , Im also facing the same issue , is there any solution available ?

**Comment by EhtashamToorr** [comment]
Yes i have faced it also

**Comment by amriosmo** [comment]
Same, this issue was already fixed?
