### ISSUE TITLE
The single quote in Example Input of SQLDatabaseToolkit will mislead LLM

### ISSUE THREAD

**Issue by edwardzjl** [langchain-ai/langchain#7457]
### System Info

langchain 0.0.228
python 3.11.1
LLM: self hosting llm using [text-generation-inference](https://github.com/huggingface/text-generation-inference)

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

There is a Sample Input in the description for `InfoSQLDatabaseTool` ([this line](https://github.com/hwchase17/langchain/blob/560c4dfc98287da1bc0cfc1caebbe86d1e66a94d/langchain/agents/agent_toolkits/sql/toolkit.py#L48C18-L48C18)), and the Sample Input quotes all table names in a pair of single quotes, which will mislead the llm to also quote Action Input in single quotes.

An example of the LLM behaviour:

```console
$ agent_executor.run("According to the titanic table, how many people survived?")
> Entering new  chain...
Action: sql_db_list_tables
Action Input:
Observation: aix_role, aix_user, chat, client_info, dataset, dataset_version, oauth2_authorization, oauth2_authorization_consent, oauth2_registered_client, titanic, user_role
Thought:The titanic table seems relevant, I should query the schema for it.
Action: sql_db_schema
Action Input: 'titanic'
Observation: Error: table_names {"'titanic'"} not found in database
Thought:I should list all the tables in the database first.
Action: sql_db_list_tables
Action Input:
Observation: aix_role, aix_user, chat, client_info, dataset, dataset_version, oauth2_authorization, oauth2_authorization_consent, oauth2_registered_client, titanic, user_role
Thought:The titanic table is in the database, I should query the schema for it.
Action: sql_db_schema
Action Input: 'titanic'
Observation: Error: table_names {"'titanic'"} not found in database
```

And this example is more clear (note the Action Input):

```console
$ agent_executor.run("When is the last dataset created?")
> Entering new  chain...
Action: sql_db_list_tables
Action Input:
Observation: aix_role, aix_user, chat, client_info, dataset, dataset_version, oauth2_authorization, oauth2_authorization_consent, oauth2_registered_client, titanic, user_role
Thought:The 'dataset' and 'dataset_version' tables seem relevant. I should query the schema for these tables.
Action: sql_db_schema
Action Input: 'dataset, dataset_version'
Observation: Error: table_names {"dataset_version'", "'dataset"} not found in database
```

After removing the quotes around the Example Input the SQL Agent works fine now.

### Expected behavior

The Action Input of `InfoSQLDatabaseTool` should be a list of table names, not a quoted str.

**Comment by guireis1** [comment]
Same problem here.. trying to force on template and example, but doesn't work as good as should be

**Comment by sinhainsight** [comment]
same issue here

**Comment by pedram-tehranchi** [comment]
same problem

**Comment by pedram-tehranchi** [comment]
I changed the template and the problem was solved. I hope this modified part helps you:
'''
```
Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question
```

you need to remove the single quotes around the table names in Action Input.
Begin!

Question: {input}
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
{agent_scratchpad}
'''

**Comment by sinhainsight** [comment]
> I changed the template and the problem was solved. I hope this modified part helps you:
> 
> ```
> Question: the input question you must answer
> Thought: you should always think about what to do
> Action: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]
> Action Input: the input to the action
> Observation: the result of the action
> ... (this Thought/Action/Action Input/Observation can repeat N times)
> Thought: I now know the final answer
> Final Answer: the final answer to the original input question
> 
> 
> you need to remove the single quotes around the table names in Action Input.
> Begin!
> 
> Question: {input}
> Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
> {agent_scratchpad}
> ```

actually i am using create_sql_agent, i dont think it supports PROMPT, any suggestions?

code snippet:
`toolkit = SQLDatabaseToolkit(db=db, llm=llm)

agent = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    top_k=25,
    output_parser=output_parser
)
agent.run("user's question")`

**Comment by edwardzjl** [comment]
@sinhainsight You can customize the tool's description in the toolkits

**Comment by pedram-tehranchi** [comment]
> > I changed the template and the problem was solved. I hope this modified part helps you:
> > ```
> > Question: the input question you must answer
> > Thought: you should always think about what to do
> > Action: the action to take, should be one of [sql_db_query, sql_db_schema, sql_db_list_tables, sql_db_query_checker]
> > Action Input: the input to the action
> > Observation: the result of the action
> > ... (this Thought/Action/Action Input/Observation can repeat N times)
> > Thought: I now know the final answer
> > Final Answer: the final answer to the original input question
> > 
> > 
> > you need to remove the single quotes around the table names in Action Input.
> > Begin!
> > 
> > Question: {input}
> > Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
> > {agent_scratchpad}
> > ```
> 
> actually i am using create_sql_agent, i dont think it supports PROMPT, any suggestions?
> 
> code snippet: `toolkit = SQLDatabaseToolkit(db=db, llm=llm)
> 
> agent = create_sql_agent( llm=llm, toolkit=toolkit, verbose=True, agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION, top_k=25, output_parser=output_parser ) agent.run("user's question")`
> 
> i had created prompt, earlier but it didn't work

yes you can:
'''
template = ' you template '

agent = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True
)

agent.agent.llm_chain.prompt.template = template

'''

**Comment by sinhainsight** [comment]
@edwardzjl Thanks for the input, i tried that but the agent still messed up sometimes in complex queries.

@pedram-tehranchi Thanks for the input, adding template like this is working everytime, i just have to improve the template further as sometimes it adds previous Agent Input in current itteration.

**Comment by ms4sman** [comment]
Any idea if this will get corrected in the official repo any time soon? So that we don't have to manually override the prompt to get around it?

**Comment by m000lie** [comment]
> After removing the quotes around the Example Input the SQL Agent works fine now.

How did you do this? @hwchase17 doesn't seem like he's gonna be merging any PRs related to this issue any time soon. Please let me know as I'd like to attempt fixing it myself.

**Comment by edwardzjl** [comment]
@m000lie I extended the `SQLDatabaseToolkit` and modified some tool descriptions.

The related one is:

```python
table_schema_tool_description = (
    "Use this tool to get the schema of specific tables. "
    "Input to this tool is a comma-separated list of tables, output is the "
    "schema and sample rows for those tables. "
    "Be sure that the tables actually exist by calling "
    f"{list_tables_tool.name} first! "
    "Example Input: table1, table2, table3"
)
table_schema_tool = InfoSQLDatabaseTool(
    db=self.db,
    description=table_schema_tool_description,
)
```

**Comment by m000lie** [comment]
@edwardzjl awesome, thanks! Did you compile & build from source after this?

**Comment by edwardzjl** [comment]
Nope, I did not modify the source code of langchain, it's just a custom toolkit, and I passed that toolkit when creating agent

**Comment by m000lie** [comment]
Oh okay. Do you have an example file for that code? Seems like a more elegant solution than recompiling haha.

**Comment by edwardzjl** [comment]
The code i'm using has changed to much. If I remember correctly it should be something like:

my_tookit.py:

```python
from langchain.agents.agent_toolkits.sql.toolkit import SQLDatabaseToolkit
from langchain.tools import BaseTool
from langchain.tools.sql_database.tool import (
    InfoSQLDatabaseTool,
    ListSQLDatabaseTool,
    QuerySQLCheckerTool,
    QuerySQLDataBaseTool,
)


class CustomSQLDatabaseToolkit(SQLDatabaseToolkit):
    def get_tools(self) -> list[BaseTool]:
        """Get the tools in the toolkit."""
        list_tables_tool = ListSQLDatabaseTool(db=self.db)
        table_schema_tool_description = (
            "Use this tool to get the schema of specific tables. "
            "Input to this tool is a comma-separated list of tables, output is the "
            "schema and sample rows for those tables. "
            "Be sure that the tables actually exist by calling "
            f"{list_tables_tool.name} first! "
            "Example Input: table1, table2, table3"  # NOTE: removed the single quotes here
        )
        table_schema_tool = InfoSQLDatabaseTool(
            db=self.db,
            description=table_schema_tool_description,
        )
        query_sql_database_tool_description = (
            "Use this tool to execute query and get result from the database. "
            "Input to this tool is a SQL query, output is a result from the database. "
            "If the query is not correct, an error message will be returned. "
            "If an error is returned, rewrite the query and try again. "
            "If you encounter an issue with Unknown column "
            f"'xxxx' in 'field list', or no such column 'xxxx', use {table_schema_tool.name} "
            "to get the correct table columns."
        )
        query_sql_database_tool = QuerySQLDataBaseTool(
            db=self.db,
            description=query_sql_database_tool_description,
        )
        query_sql_checker_tool_description = (
            "Use this tool to check if your query is correct before executing "
            "it. Always use this tool before executing a query with "
            f"{query_sql_database_tool.name}!"
        )
        query_sql_checker_tool = QuerySQLCheckerTool(
            db=self.db,
            llm=self.llm,
            description=query_sql_checker_tool_description,
        )
        return [
            list_tables_tool,
            table_schema_tool,
            query_sql_checker_tool,
            query_sql_database_tool,
        ]
```

and create agent like:

```python
from my_tookit import CustomSQLDatabaseToolkit

db = SQLDatabase.from_uri("sqlite:///../../../../../notebooks/Chinook.db")
toolkit = CustomSQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0))

agent_executor = create_sql_agent(
    llm=OpenAI(temperature=0),
    toolkit=toolkit,
    verbose=True,
    agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
)
```
