### ISSUE TITLE
pgvector add implemention of MMR

### ISSUE THREAD

**Issue by lanyuer** [langchain-ai/langchain#7466]
### Feature request

I am using pgvector and hoping for an MMR retrieval method similar to qdrant implementation.

### Motivation

MMR retrieval can return more diverse results, removing duplicate rows, which meets my needs (I did some testing on qdrant). However, I couldn't find an implementation in vectorstore of type pgvector.

### Your contribution

I found that in the current implementation of the pgvector class, the retrieval results do not return the original vectors, so it is not possible to simply add MMR post-processing. Is this due to performance considerations? Have you considered adding an option for this?

**Comment by rahulnyk** [comment]
Any updates on this?
Looking forward to a way to implement/use MMR using PGVector.

**Comment by lifan0127** [comment]
The "not planned" label by dosubot is misleading. This feature has been added as per https://github.com/langchain-ai/langchain/pull/10396
