### ISSUE TITLE
RecursiveCharacterTextSplitter strange behavior after v0.0.226

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#7485]
### System Info

After v0.0.226, the RecursiveCharacterTextSplitter seems to no longer separate properly at the end of sentences and now cuts many sentences mid-word.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
splitter = RecursiveCharacterTextSplitter(
    chunk_size=450,
    chunk_overlap=20,
    length_function=len,
    #separators=["\n\n", "\n", ".", " ", ""], # tried with and without this
)
```

### Expected behavior

Would like to split at newlines or period marks.

**Comment by dudesparsh** [comment]
From a high level understanding, if we use textsplitter with the separators mentioned - separators=["\n\n", "\n", ".", " ", ""] -> then it already has the option of splitting on a normal ' ' ( space ) or any word in case of "" . I think your question is not clear and please try to elaborate on how to reproduce the same. TIA!

**Comment by austinmw** [comment]
@dudesparsh I'm not sure if I follow your comment. The default separators list, which I tried as well, is `["\n\n", "\n", " ", ""]`. 

Starting in v0.0.226, when I inspect the context retrieved in my RAG system, this retriever along with the default separators list seems to produce very (and in my opinion poorer) results than it did in previous versions. It does not seem to attempt well to prioritize separating on newlines or end of sentences, and it instead separates quite often directly in the middle of words.

**Comment by firezym** [comment]
I get similar poor result. For example
`text_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", "。", "&nbsp;"], keep_separator=False, chunk_size=256, chunk_overlap=80)`
Some of the results does not get overlap entirely!

**Comment by IlyaMichlin** [comment]
@austinmw and @firezym, I tried some random texts and could not reproduce the issue. Please provide an example text that produces the issue.

**Comment by firezym** [comment]
@IlyaMichlin I have uploaded a txt file and append following code. The behavior is strange. For example, if you run the code, the first 3 documents don't actually have overlaps for each other:

```
[Document(page_content='【财经早餐：中共中央、国务院印发《质量强国建设纲要》；工信部多措并举做好新能源汽车关键原材料保供稳价工】财经早餐摘要：中共中央、国务院印发《质量强国建设纲要》；工信部：多措并举做好 新能源 汽车关键原材料保供稳价工作；多地开足马力稳经济，超百项&ldquo;政策清单&rdquo;密集发布。&nbsp;一、政策和行业新闻&nbsp;1、新华社：近日，中共中央、国务院印发了《质量强国建设纲要》，并发出通知，要求各地区各部门结合实际认真贯彻落实', metadata={}),
 Document(page_content='纲要提出，到2025年，质量整体水平进一步全面提高，中国品牌影响力稳步提升，人民群众质量获得感、满意度明显增强，质量推动经济社会发展的作用更加突出，质量强国建设取得阶段性成效。到2035年，质量强国建设基础更加牢固，先进质量文化蔚然成风，质量和品牌 综合 实力达到更高水平。&nbsp;2、工信部：相关负责人就《关于组织开展公共领域车辆全面电动化先行区试点工作的通知》答记者问时表示，要优化政策供给，保障稳定运行，多措并举做好关键原材料保供稳价工作，支持创新突破，优化发展环境，深化开放发展', metadata={}),
 Document(page_content='&nbsp;3、工信部：发布《关于电信设备进网许可制度若干改革举措的通告》，调整部分电信设备监管方式。对11种电信设备，不再受理和审批新的进网许可申请。对卫星 互联网 设备、功能虚拟化设备，纳入现行进网许可管理。&nbsp;4、国资委：要聚焦新型基础设施、 新型城镇化 、交通水利等重大工程建设和短板领域扩大有效投资，实施一批强基础、增功能、利长远的重大项目；争做高水平科技自立自强的国家队，打造创新联合体，汇集 优势资源 加大关键材料、核心元器件、基础 软件 等重点领域攻关力度，加快原创技术策源地建设', metadata={}),
...
```


[text_for_split.txt](https://github.com/hwchase17/langchain/files/12080054/text_for_split.txt)
```
import os
from langchain.text_splitter import CharacterTextSplitter, RecursiveCharacterTextSplitter

def load_text(filename):
    with open(filename, 'r') as f:
        text = f.read()
    return text

text = load_text('text_for_split.txt')

text_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", "。", "&nbsp;"], keep_separator=False, chunk_size=256, chunk_overlap=64)
docs = text_splitter.create_documents([text])
docs
```

**Comment by IlyaMichlin** [comment]
@firezym I will look into it but that is a different issue from what the OP described.
The original issue was `cuts many sentences mid-word`. @austinmw Can you please provide ancexaple text for that?

**Comment by firezym** [comment]
@IlyaMichlin Thanks a lot! Sorry to put another issue inside an original issue.

**Comment by IlyaMichlin** [comment]
@firezym I dont see any issue. Running your code:

```
from langchain.text_splitter import RecursiveCharacterTextSplitter


def load_text(filename):
    with open(filename, 'r') as f:
        text = f.read()
    return text


text = load_text("text_for_split.txt")

text_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", "。", "&nbsp;"], keep_separator=False, chunk_size=256, chunk_overlap=64)
docs = text_splitter.create_documents([text])
```
Produces 19 documents which overlap.

Check you langchain version.

**Comment by firezym** [comment]
@IlyaMichlin My langchain version is `langchain 0.0.235`
I do get 19 documents. But let's see the 2nd and 3rd document. They actually don't have any overlaps. They are exactly cut by  `。`  in the middle (which I mark it with || : `2月6日，沪深两市三大指数弱势震荡，沪指跌0.76%， 深证成指 跌1.18%， 创业板 指跌1.4%` | |`。` || `盘面上看， ChatGPT概念 持续火爆， 海天瑞声 、 云从科技 涨停6个交易日翻倍； ` Can you reproduce the 2nd and 3rd document exactly like below?

2nd: `2月5日单日实时票房超1.3亿元，领先第二名《满江红》近2000万，锁定单日票房冠军。目前，《流浪地球2》的票房占比34.5%，排片场次92126次。&nbsp;二、市场回顾【国内股市】&nbsp;1、2月6日，沪深两市三大指数弱势震荡，沪指跌0.76%， 深证成指 跌1.18%， 创业板 指跌1.4%`
3rd: `盘面上看， ChatGPT概念 持续火爆， 海天瑞声 、 云从科技 涨停6个交易日翻倍； 数字经济 概念盘中发酵， 铜牛信息 涨停；信创、软件股逆市走强， 青 云科技 涨停；八部门适度超前建设充换电基础设施， 充电桩 概念活跃。 白酒 、CRO、新冠 疫苗 、 券商 、 黄金 有色、 保险 、 磷化工 等板块跌幅居前。&nbsp;2、港股低开低走，截至收盘， 恒生指数 跌2.02%，报21222.16点； 国企指数 跌2.68%， 红筹指数 跌1.37%`

**Comment by firezym** [comment]
@dosubot This problem is not solved in the latest verison.

**Comment by Munz1993** [comment]
Hello there. Also experiencing the same issue. I did some analysis on it and shared it in two comments #8142.

**Comment by austinmw** [comment]
Not sure if this is resolved, others still reported issues.
