### ISSUE TITLE
TransportQueryError when using GraphQL tool

### ISSUE THREAD

**Issue by Ori-Shahar** [langchain-ai/langchain#7488]
### System Info

When running the following code:

```
from langchain import OpenAI
from langchain.agents import load_tools, initialize_agent, AgentType
from langchain.utilities import GraphQLAPIWrapper
from langchain.memory import ConversationBufferMemory


llm = OpenAI(temperature=0, openai_api_key=openai_api_key)
token = "..."
tools = load_tools(
    ["graphql"],
    custom_headers={"Authorization": token, "Content-Type": "application/json"},
    graphql_endpoint="...",
    llm=llm
)

memory = ConversationBufferMemory(memory_key="chat_history")
agent = initialize_agent(
    tools, llm, agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION, verbose=True, memory=memory
)

graphql_fields = """query getCompanies {get_companies}"""

suffix = "Call the API with schema "

agent.run(f"{suffix} {graphql_fields}")
```

Im getting the error:
TransportQueryError: Error while fetching schema: {'errorType': 'UnauthorizedException', 'message': 'You are not authorized to make this call.'}
If you don't need the schema, you can try with: "fetch_schema_from_transport=False"

It doesn't matter what value is provided under custom_headers, or if it is passed as a parameter at all. The error is always the same. Playground code from https://python.langchain.com/docs/modules/agents/tools/integrations/graphql worked as intended.

Any idea of what the problem is?

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain import OpenAI
from langchain.agents import load_tools, initialize_agent, AgentType
from langchain.utilities import GraphQLAPIWrapper
from langchain.memory import ConversationBufferMemory


llm = OpenAI(temperature=0, openai_api_key=openai_api_key)
token = "..."
tools = load_tools(
    ["graphql"],
    custom_headers={"Authorization": token, "Content-Type": "application/json"},
    graphql_endpoint="...",
    llm=llm
)

memory = ConversationBufferMemory(memory_key="chat_history")
agent = initialize_agent(
    tools, llm, agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION, verbose=True, memory=memory
)

graphql_fields = """query getCompanies {get_companies}"""

suffix = "Call the API with schema "

agent.run(f"{suffix} {graphql_fields}")

TransportQueryError: Error while fetching schema: {'errorType': 'UnauthorizedException', 'message': 'You are not authorized to make this call.'}
If you don't need the schema, you can try with: "fetch_schema_from_transport=False"
```

### Expected behavior

An allowed API call that doesn't cause authentication issues

**Comment by aerrober** [comment]
This is fixed in this PR here: https://github.com/langchain-ai/langchain/pull/8187

**Comment by slamer59** [comment]
Hi, 
I have the same issue. 
Graphql endpoint is public so 
I don't know why I should authenticate ?

Will the pull request solve this ? 

Thanks :)
