### ISSUE TITLE
Glob patterns not finding documents when using it as an argument to DirectoryLoader

### ISSUE THREAD

**Issue by axiom-of-choice** [langchain-ai/langchain#7506]
### System Info

I'm using langchain 0.0.218 in python 3.10.0 and when I use glob patterns as a direct argument to initialize the class this does not load anything. e.g. DirectoryLoader(path = root_dir + 'data', glob = "**/*.xml") 

But when I use it in loader_kwargs it works perfect. 
e.g. DirectoryLoader(path = path, loader_kwargs={"glob":"**/*.xml"}
May this be a bug that when class is initialized in the line?https://github.com/hwchase17/langchain/blob/master/langchain/document_loaders/directory.py#L33
It seems to always be set as "**/[!.]*" when using it as an arg but not when using it inside loader_kwargs

### Who can help?

@eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Make a directory called data
2. Inside that directory store all kind of supported documents  (docx, text, etc) excepting -for example- xml files and also a folder that only contains all the xml files 
3.  Use loader = Directoryloader = (path = root_dir + 'data', glob = "**/*.xml") 
5. execute loader.load() will not load any documents

Then use loader = DirectoryLoader(path = path, loader_kwargs={"glob": "**/*.xml"} 
loader.load() and will work perfectly

### Expected behavior

Must work using it like loader = Directoryloader(path = root_dir + 'data', glob = "**/*.xml") 

*NOTE* This happens with all kind of glob patterns passed through glob argument. It does not has to do with the file extension or something. 

Let me know if you need more info :)

**Comment by axiom-of-choice** [comment]
Not sure if this is the expected behaviour

**Comment by salomonMuriel** [comment]
Very sure it isnt. The documentation itself instructs to use it directly.

**Comment by axiom-of-choice** [comment]
I'll be contributing in this issue then...
