### ISSUE TITLE
AttributeError: 'str' object has no attribute 'upsert' in Pinecone Hybrid Search

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#7523]
### System Info

0.0.228

### Who can help?

@lbsnrs

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Following tutorial here:
https://python.langchain.com/docs/modules/data_connection/retrievers/integrations/pinecone_hybrid_search

```
bm25_encoder = BM25Encoder().default()
embed = OpenAIEmbeddings(deployment=OPENAI_EMBEDDING_DEPLOYMENT_NAME, model=OPENAI_EMBEDDING_MODEL_NAME, chunk_size=1)
 
retriever = PineconeHybridSearchRetriever(
        embeddings=embed, sparse_encoder=bm25_encoder, index="cubigometadatanotindexed"
)
retriever.add_texts(["foo", "bar", "FirstName0003384 is a guy", "FirstName0003381 is a girl"])
result = retriever.get_relevant_documents("Who is FirstName0003381?")
```
 
I get this error:

```

AttributeError: 'str' object has no attribute 'upsert'
Traceback:
File "C:\Users\xx\anaconda3\envs\xxChatbotv3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\xx\repos\xxChatbotv1\app\pages\Pinecone Hybrid Search.py", line 116, in <module>
    main()
File "C:\Users\xx\repos\xxChatbotv1\app\pages\Pinecone Hybrid Search.py", line 112, in main
    retriever.add_texts(["foo", "bar", "FirstName0003384 is a guy", "hello"])
File "C:\Users\xx\anaconda3\envs\zzChatbotv3\Lib\site-packages\langchain\retrievers\pinecone_hybrid_search.py", line 121, in add_texts
    create_index(
File "C:\Users\xx\anaconda3\envs\zzChatbotv3\Lib\site-packages\langchain\retrievers\pinecone_hybrid_search.py", line 98, in create_index
    index.upsert(vectors)
    ^^^^^^^^^^^^
```

### Expected behavior

The texts should be added to the index without error

**Comment by gaurang98671** [comment]
Hello @levalencia, not sure if this is the cause of issue, but there's a small typo 
in word **environment** in the tutorial that you've linked.

```pinecone.init(api_key=api_key, enviroment=env)```
