### ISSUE TITLE
SelfQueryRetriever, Add option to return all when user asks

### ISSUE THREAD

**Issue by levalencia** [langchain-ai/langchain#7527]
### Feature request

I tested the enable_limit to True and asking thins like
1. Get 3 residents who were born in xxx
2.  Get 5 Residens who were bon in xxx

It works pretty well.

However in my use case, users can ask also:  List all the residents who were born in xxx. 
When questions like this are done, by default it will return only 4 documents and not all.

![image](https://github.com/hwchase17/langchain/assets/6962857/aaeec974-56d3-47c4-90eb-9bde4782cb22)

### Motivation

My use case requires sometimes to list all documents that match the criteria, not only 4. 

### Your contribution

I am a beginner in langchain (only used it for 2 months), so not sure where in the code this can be fixed, but with the proper guidance I should be able to contribute (if somebody is willing to guide me)

**Comment by gaurang98671** [comment]
@levalencia if you look at [base.py](https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/base.py) file, which is parent class for all vectorstores, all the query functions sets k = 4 by default. k is number of top results returned  from your vector database.

You can override this by passing search_kwargs in your retriever object.
```
retriever = SelfQueryRetriever.from_llm(
    llm, vectorstore, document_content_description, metadata_field_info, verbose=True, enable_limit=True, 
    search_kwargs={"k":10}
)
```
Max value of k depends on what vector database you are using. For [Pinecone](https://docs.pinecone.io/docs/limits) its 10,000.
I hope this helps.

**Comment by aiakubovich** [comment]
I am also interested in such use cases. What I think is that there should be additional logic on top. Initial chain (1) should decide either send result in SelfQueryRetriever (2) or just create pandas/SQL statement (3) to extract all users for particular year.  

        2
      /
1--
      \
        3

(1) can be achieve using langchain functional calling.  
(3) can be achieve using langchain functional calling, codeinterpreter-api or PandasAI. 

Let me know what you think guys.
