### ISSUE TITLE
[Feature Request] Add DSP to langchain

### ISSUE THREAD

**Issue by atemaguer** [langchain-ai/langchain#753]
DSP is a framework that provides abstractions and primitives for easily composing language and retrieval models. Furthermore, it proposes an algorithmic approach to prompting LLMs that does away with prompt engineering

https://arxiv.org/pdf/2212.14024.pdf, https://github.com/stanfordnlp/dsp

**Comment by atemaguer** [comment]
@hwchase17, I'm open to working on this if we can agree on the right API for langchain

**Comment by conceptofmind** [comment]
@atemaguer We have a group on the discord currently working on adding DSP to LangChain: https://discord.com/channels/1038097195422978059/1068175360648286248

**Comment by atemaguer** [comment]
The discord link you provided doesn't seem to be valid

**Comment by conceptofmind** [comment]
> The discord link you provided doesn't seem to be valid

Hmmm. It worked when I tried it just now. Is there a discord name I can just @ you in the chat with?

**Comment by atemaguer** [comment]
alby#7212

**Comment by aabdullah-getguru** [comment]
@conceptofmind  hello! I'm `squared_circle` on discord. Out of curiosity, what is the status of this work? Like atemaguer , I'd be interested in adding this if someone else isn't working on it.

**Comment by conceptofmind** [comment]
> @conceptofmind hello! I'm `squared_circle` on discord. I don't know what server and channel you're referring to, it's probably a private server :). Out of curiosity, what is the status of this work? Like atemaguer , I'd be interested in adding this if someone else isn't working on it.

Hi,

We already have a large majority of it done. I can add you to the thread.

Best,

Enrico

**Comment by aabdullah-getguru** [comment]
> > @conceptofmind hello! I'm `squared_circle` on discord. I don't know what server and channel you're referring to, it's probably a private server :). Out of curiosity, what is the status of this work? Like atemaguer , I'd be interested in adding this if someone else isn't working on it.
> 
> Hi,
> 
> We already have a large majority of it done. I can add you to the thread.
> 
> Best,
> 
> Enrico

Hey Enrico. Thanks that would be wonderful if you can! I'd appreciate it :).

**Comment by conceptofmind** [comment]
> > > @conceptofmind hello! I'm `squared_circle` on discord. I don't know what server and channel you're referring to, it's probably a private server :). Out of curiosity, what is the status of this work? Like atemaguer , I'd be interested in adding this if someone else isn't working on it.
> > 
> > 
> > Hi,
> > We already have a large majority of it done. I can add you to the thread.
> > Best,
> > Enrico
> 
> Hey Enrico. Thanks that would be wonderful if you can! I'd appreciate it :).

What is the four digit tag after your username?

**Comment by aabdullah-getguru** [comment]
> > > > @conceptofmind hello! I'm `squared_circle` on discord. I don't know what server and channel you're referring to, it's probably a private server :). Out of curiosity, what is the status of this work? Like atemaguer , I'd be interested in adding this if someone else isn't working on it.
> > > 
> > > 
> > > Hi,
> > > We already have a large majority of it done. I can add you to the thread.
> > > Best,
> > > Enrico
> > 
> > 
> > Hey Enrico. Thanks that would be wonderful if you can! I'd appreciate it :).
> 
> What is the four digit tag after your username?

Whoops. 9344. Thanks!

**Comment by aabdullah-getguru** [comment]
> Hi there, I’m just following up on this.
> 
> Is there progress related to DSP integration? Or at least an open pull request.
> 
> I’m hoping to understand if it’s worth investing my own time from scratch, contributing to an existing branch, or just waiting/using if it’s done.
> 
> Thanks in advance!

Not sure either. There seems to be this repo here which has a lot of this implemented in langchain, but its been silent a couple of months: https://github.com/conceptofmind/dsp-langchain

**Comment by conceptofmind** [comment]
> Hi there, I’m just following up on this.
> 
> Is there progress related to DSP integration? Or at least an open pull request.
> 
> I’m hoping to understand if it’s worth investing my own time from scratch, contributing to an existing branch, or just waiting/using if it’s done.
> 
> Thanks in advance!

As @aabdullah-getguru has noted. We have already implemented most of DSP. I can just open a PR with what I have already done.

We had stopped working on DSP when we realized it was unfeasible in production. The cost and inference time are both quite heavy. And the performance currently does not significantly outweigh those costs when compared to just using retrieval alone. It is an interesting research avenue though.

Also, the main author of DSP does not want it added to LangChain and has publicly stated so.

**Comment by michox** [comment]
I thought the point of DSP was that once you have built the tools you can now use much smaller models like Ada or a local model and still achieve a similar performance? see here for example https://github.com/stanfordnlp/dsp/blob/main/compiler.ipynb
