### ISSUE TITLE
Generating answers from LLM's pretrianed knowledge  base, instead of from the embedded document.

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#7532]
### System Info

langchain==0.0.219
python 3.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
import os
import openai
import pinecone
from langchain.document_loaders import DirectoryLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Pinecone
from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain
directory = '/content/data'

def load_docs(directory):
  loader = DirectoryLoader(directory)
  documents = loader.load()
  return documents

documents = load_docs(directory)

def split_docs(documents, chunk_size=1000, chunk_overlap=20):
  text_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)
  docs = text_splitter.split_documents(documents)
  return docs

docs = split_docs(documents)

embeddings = OpenAIEmbeddings(model_name="ada")
pinecone.init(
    api_key="pinecone api key",
    environment="env"
)
index_name = "langchain-demo"
index = Pinecone.from_documents(docs, embeddings, index_name=index_name)

model_name = "gpt-4"
llm = OpenAI(model_name=model_name)

chain = load_qa_chain(llm, chain_type="stuff")

def get_similiar_docs(query, k=2, score=False):
  if score:
    similar_docs = index.similarity_search_with_score(query, k=k)
  else:
    similar_docs = index.similarity_search(query, k=k)
  return similar_docs

def get_answer(query):
  similar_docs = get_similiar_docs(query)
  answer = chain.run(input_documents=similar_docs, question=query)
  return answer

```

In the above code, If I ask any question it is answered from an outer world other than the document corpus.

### Expected behavior

If I am asked any domain-specific query, it should answer based on the embedded document corpus only. I am not expecting any outer-domain answer.  
If the query is not related to the embedded document store, then it shouldn't answer anything, instead of searching and generating the answer from its own base pretrained knowledge.

**Comment by gaurang98671** [comment]
Hello, instead of using `.run()` method try `__call__` method i.e. directly calling chain object. 
```
def get_answer(query):
  similar_docs = get_similiar_docs(query)
  answer = chain({"input_documents":similar_docs, "question":query})
  return answer["output_text"] 
```

Also instead of using OpenAI for llm initialization use ChatOpenAI from langchain.chat_models.
Lmk if this helps.

**Comment by pablocastilla** [comment]
don´t you need to say that you want the results from the docs? you need to use, for instance, load_qa_with_sources_chain function.

Here a simple example I made:
https://github.com/pablocastilla/llm-openai-langchain-playground/blob/main/langchain_document_qa.ipynb

**Comment by pradeepdev-1995** [comment]
@pablocastilla 
I tried the above code. But along with my exact answer, it shows a lot of other unwanted data like QUESTION, Content,...etc.
How can u disable those and display only my required answer?

**Comment by Kuramdasu-ujwala-devi** [comment]
Hey, use good prompt template for answering questions  only related to domain-specific.
Say in prompt like don't do web search answer questions if it found in the vector store or else simple say you didn't found.
```
prompt_template1 = """
You are a Bot assistant for answering any questions related to the given documents.
For a given question find the answer from the documents given to you.Use the question column from the document given to find the answer.
Please follow below instruction:
- To find the answer first read the context and question properly.
- Do not rely on any prior knowledge.
- Avoid using web search.
- show only the top result.
- If you don't find the answer, simply state that you could not find. Avoid make up an answer.
-------------------------------------
context : {context}

now based on above context answer the question accurately:

Question: {question}

Answer:
```

------------------------------------
"""

**Comment by Kuramdasu-ujwala-devi** [comment]
I tried the above code. But along with my exact answer, it shows a lot of other unwanted data like QUESTION, Content,...etc.
How can u disable those and display only my required answer?
@pradeepdev-1995  for your question 
```
def get_answer(query):
  similar_docs = get_similiar_docs(query)
  answer = chain.run(input_documents=similar_docs, question=query)
  return answer
###here instead you return answer['result']
return answer['result']
```
