### ISSUE TITLE
Importance of VectorStoreToolkit, vectorstore_agent and VectorStoreInfo in document based domain specific question answering

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#7539]
### Issue you'd like to raise.

I am trying to query the documents using the below stack

**Langchain+ embedding tool + vectore store + LLM model**

There are many tools and techniques for this in langchain including **load_qa_chain, RetrievalQA,VectorstoreIndexCreator,ConversationalRetrievalChain**. Those are already giving the good results(Not optimal)

But found one more technique including **VectorStoreInfo,VectorStoreToolkit and vectorstore_agent**

What is the advantage/Importance of this pipeline which using **VectorStoreInfo,VectorStoreToolkit and vectorstore_agent** over the other which doesnt follow this pipeline(use any of **load_qa_chain, RetrievalQA,VectorstoreIndexCreator,ConversationalRetrievalChain**)

**Comment by pradeepdev-1995** [comment]
So multi hop questions are not possible in load_qa_chain, RetrievalQA, VectorstoreIndexCreator, and ConversationalRetrievalChain?
Then how the proposed pipeline(VectorStoreInfo,VectorStoreToolkit and vectorstore_agent) make it happen internally?
Please explain the internal flow of this to make it multi hop questions to answerable.

**Comment by sankar-forrester** [comment]
does the VectorStoreToolkit require that we use OpenAI? I am trying to use it with huggingfacePipepline and dolly as the model

**Comment by pradeepdev-1995** [comment]
@sankar-forrester No it doesnt
