### ISSUE TITLE
Error when creating a custom ConversationalChatAgent

### ISSUE THREAD

**Issue by eesoymilk** [langchain-ai/langchain#7585]
### System Info

MacOS
Python 3.10.6
langchain 0.0.230
langchainplus-sdk 0.0.20

### Who can help?

@hwchase17  @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

For now, there are only the default `ConversationalChatAgent` and `ConversationalAgent`, and we cannot create custom prompt templates in them. At least, I don't see how to do that in both the docs and source code.

I think there should be a straight-forward way to do so, just like how you can have a [custom LLM agent](https://python.langchain.com/docs/modules/agents/how_to/custom_llm_chat_agent):
```py
agent = LLMSingleActionAgent(
    llm_chain=llm_chain, 
    output_parser=output_parser,
    stop=["\nObservation:"], 
    allowed_tools=tool_names
)
```
However, when the same code is applied to `ConversationalChatAgent`, that is:
```py
agent = LLMSingleActionAgent(
    llm_chain=llm_chain, 
    output_parser=output_parser,
    stop=["\nObservation:"], 
    allowed_tools=tool_names
)
```
I get the following error:
```shell
pydantic.error_wrappers.ValidationError: 1 validation error for ConversationalChatAgent
__root__
  Got unexpected prompt type <class '__main__.CustomPromptTemplate'> (type=value_error)
```

I'm not sure if this belongs to **Bug Report** so if I'm doing anything wrong, please tell me about it. Thanks!

### Expected behavior

The agent should be created without errors.

**Comment by ZuzooVn** [comment]
@eesoymilk Have you discovered a solution?
