### ISSUE TITLE
Improve the usage of relevance score threshold and allow the return of the scores

### ISSUE THREAD

**Issue by ROMEEZHOU** [langchain-ai/langchain#7590]
### Feature request

In `VectorStore`/`VectorStoreRetriever` class, `_similarity_search_with_relevance_scores`function,
1) Allow different choices of threshold kind: allow users to choose whether >= threshold or <= threshold
2) Allow users to choose to return the relevance score along with the docs

### Motivation

I am working with returning relevant docs that satisfy a certain threshold, and I encountered some problems. 
One problem is that for different embedding algorithms and similarity calculations, it is not always the case that higher relevance scores are better. Actually, when I use `HuggingFaceEmbedding` with `Chroma` database, the smaller the relevance score, the better. So I believe it would be necessary to allow users choose between different options here.
The second problem is that I want to see the relevance score, however, in https://github.com/hwchase17/langchain/blob/master/langchain/vectorstores/base.py, line 474 to 492, it is fixed that only the docs are finally returned. 
```
def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        if self.search_type == "similarity":
            docs = self.vectorstore.similarity_search(query, **self.search_kwargs)
        elif self.search_type == "similarity_score_threshold":
            docs_and_similarities = (
                self.vectorstore.similarity_search_with_relevance_scores(
                    query, **self.search_kwargs
                )
            )
            docs = [doc for doc, _ in docs_and_similarities]
        elif self.search_type == "mmr":
            docs = self.vectorstore.max_marginal_relevance_search(
                query, **self.search_kwargs
            )
        else:
            raise ValueError(f"search_type of {self.search_type} not allowed.")
        return docs
```
I wish there is an option that the relevance scores could also be returned.

### Your contribution

I would love to open a PR if applicable ;) @hwchase17

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like adding small features) by writing pull requests. This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)
