### ISSUE TITLE
Error while trying to run SQL Database Agent example

### ISSUE THREAD

**Issue by krishnashed** [langchain-ai/langchain#7594]
### System Info

Langchain version: 0.0.230
python version: Python 3.9.12

### Who can help?

@hwchase17
@agola11

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Im trying run the to code mentioned at: https://python.langchain.com/docs/modules/agents/toolkits/sql_database

But I'm getting the error as: 
ModuleNotFoundError: No module named 'MySQLdb'

Then trying 'pip install MySQL-python' gives the following error:
ModuleNotFoundError: No module named 'ConfigParser'

Then trying 'pip install configparser' even doesn't solve the issue.

Please help me figure out this issue. Thanks!

### Expected behavior

The code should have just executed the prompt, And installation of the required libraries should be easier.

**Comment by akashkumar398** [comment]
on aws lambda, i am getting a similar error for         # Create an instance of SQLDatabase using the engine
        db = SQLDatabase(engine)

**Comment by SfaraFind** [comment]
> on aws lambda, i am getting a similar error for # Create an instance of SQLDatabase using the engine db = SQLDatabase(engine)

Hi! Did you find the solution to this issue?
