### ISSUE TITLE
Question!! Multiple agent use? agent within agent? 

### ISSUE THREAD

**Issue by sk9288go** [langchain-ai/langchain#7597]
### Feature request

Hello Langchain community! 

I'm currently in the process of developing a company's chatbot, and I've chosen to use both a CSV file and Pinecone DB for the project.

Here's a basic outline of the structure I've adopted so far:
![캡처](https://github.com/hwchase17/langchain/assets/81153340/de1d5abf-d6d4-4f30-aad8-f1711fcf8716)

I've managed to set the two tools, and its example usage has been providing accurate answers
![캡처1](https://github.com/hwchase17/langchain/assets/81153340/75b8ee0d-01cd-4276-b926-5f288ad50053)
the first tool gets me the answers based on pandas’s result from the example usage, the answers are based on csv and it’s correct in all cases 
![캡처2](https://github.com/hwchase17/langchain/assets/81153340/0b55e176-8eb4-4db7-be81-227dabcf90eb)

Also set the second tool and its example usage is answered correctly. 
![캡처3](https://github.com/hwchase17/langchain/assets/81153340/d816eb6a-926c-4e45-b033-18f3680fccd4)

until here things are very promising and i expected everything to work as it is. 
so i have set the LLM and combined the two tools and used agent
![캡처4](https://github.com/hwchase17/langchain/assets/81153340/64d11ca9-f7a4-4839-ab94-95a5f1970f42)

However, when I combined both tools using an agent, the answers started to deviate from the expected output. I'm not entirely sure whether the method I'm using to utilize the agent is optimal.
![캡처5](https://github.com/hwchase17/langchain/assets/81153340/3dc8b7ef-990a-446b-8838-021b1037a501)

To address this issue, I've experimented with the MultiretrievalQA chain using vector embedding. But the results are not consistently reliable, and moreover, I'd rather not generate new embeddings every time I modify the CSV.

Is there anyone in the community who can shed light on these issues I'm encountering? Any feedback on my current approach, suggestions on how to optimize it, or alternative strategies would be greatly appreciated!

Thank you.

### Motivation

I'm making a company's gpt and i hope to link my csv with the chatbot so that whenever i change the csv the chatbot is automatically linked with it 

### Your contribution

um solving the problem would help others?

**Comment by wolfassi123** [comment]
> ### Feature request
> Hello Langchain community!
> 
> I'm currently in the process of developing a company's chatbot, and I've chosen to use both a CSV file and Pinecone DB for the project.
> 
> Here's a basic outline of the structure I've adopted so far: ![캡처](https://user-images.githubusercontent.com/81153340/252980479-de1d5abf-d6d4-4f30-aad8-f1711fcf8716.PNG)
> 
> I've managed to set the two tools, and its example usage has been providing accurate answers ![캡처1](https://user-images.githubusercontent.com/81153340/252980697-75b8ee0d-01cd-4276-b926-5f288ad50053.PNG) the first tool gets me the answers based on pandas’s result from the example usage, the answers are based on csv and it’s correct in all cases ![캡처2](https://user-images.githubusercontent.com/81153340/252980905-0b55e176-8eb4-4db7-be81-227dabcf90eb.PNG)
> 
> Also set the second tool and its example usage is answered correctly. ![캡처3](https://user-images.githubusercontent.com/81153340/252981142-d816eb6a-926c-4e45-b033-18f3680fccd4.PNG)
> 
> until here things are very promising and i expected everything to work as it is. so i have set the LLM and combined the two tools and used agent ![캡처4](https://user-images.githubusercontent.com/81153340/252981349-64d11ca9-f7a4-4839-ab94-95a5f1970f42.PNG)
> 
> However, when I combined both tools using an agent, the answers started to deviate from the expected output. I'm not entirely sure whether the method I'm using to utilize the agent is optimal. ![캡처5](https://user-images.githubusercontent.com/81153340/252981495-3dc8b7ef-990a-446b-8838-021b1037a501.PNG)
> 
> To address this issue, I've experimented with the MultiretrievalQA chain using vector embedding. But the results are not consistently reliable, and moreover, I'd rather not generate new embeddings every time I modify the CSV.
> 
> Is there anyone in the community who can shed light on these issues I'm encountering? Any feedback on my current approach, suggestions on how to optimize it, or alternative strategies would be greatly appreciated!
> 
> Thank you.
> 
> ### Motivation
> I'm making a company's gpt and i hope to link my csv with the chatbot so that whenever i change the csv the chatbot is automatically linked with it
> 
> ### Your contribution
> um solving the problem would help others?

I have been facing the exact same issue. Each tool by itself performs wonderful, just once added into an agent, it goes south. Are you still facing the issue?

**Comment by 1vash** [comment]
Hello @sk9288go, It seems like you have encountered a situation that appears quite similar to my own experience. I would like to bring your attention to my problem detailed in this [DOC: How to properly initialize Function Agent as a Tool for other Agent #10375 ](https://github.com/langchain-ai/langchain/issues/10375)

In this issue, I discuss the usage of an Agent as a Tool for another Agent, and I suspect that attempting to implement this through the BaseTool Inheritance Interface might not be the correct approach, as it seems that the message isn't being effectively transmitted to the other agent. Regrettably, I haven't been able to find a satisfactory solution yet.

**Comment by joshuasundance-swca** [comment]
@sk9288go @1vash 

Today, I got it working like this:

```python
                research_assistant_tool = Tool.from_function(
                    func=lambda s: research_assistant_chain.invoke(
                        {"question": s},
                        config=get_config(callbacks),
                    ),
                 name="web-research-assistant",
                    description="this assistant returns a comprehensive report based on web research. for quick facts, use duckduckgo instead.",
                )
```

https://github.com/joshuasundance-swca/langchain-streamlit-demo/blob/main/langchain-streamlit-demo%2Fapp.py#L452-L459


The current implementation is still messy, but the main point is to use `Tool.from_function` with a lambda to match the expected input key and other requirements. 

I hope this is helpful; feel free to ask for clarification or further assistance.
