### ISSUE TITLE
Output parser set number of list result

### ISSUE THREAD

**Issue by paulthemagno** [langchain-ai/langchain#7598]
### Issue you'd like to raise.

I'd like to understand if there is a way to have from OpenAI response a **list of values** (string or objects: it's the same) of a **fixed length**. I read the documentation here: https://python.langchain.com/docs/modules/model_io/output_parsers/comma_separated but I didn't find anything related to a length (maybe it's not possible?). Indeed I understood that probably these parsers only add a well-formatted piece of prompt, but you don't have the safety to have the expected results.

In my use case, I have a list of texts and I want to have a title on each of them. My prompt is something like that:
```
####
Text 1:
- Bla bla bla
...
Text 8:
- Bla bla bla
###

Use these texts to generate a title for each text. The number of the titles must be 8.
```

At the end of the prompt I "force" the number to the number of the expected results with the same number of the text, but sometimes the model gives me more titles (above all when the number of texts is 1).

So I thought to use these parsers. But I don't find any constraints on the length of the results, the only thing is a validator to check if the length is correct.

**Comment by gaurang98671** [comment]
Hello @paulthemagno, I think this is more of a prompt issue. The prompt that you are using can provide unpredictable results.
You can either call model 8 times passing each text and asking for title or you could change your prompt to something like this

```
Please generate a title for each of the following texts. Provide exactly 8 titles and not more than that, one for each text:

Text 1:
- Bla bla bla
...
Text 8:
- Bla bla bla
```
You can also experiment this prompt with different **temperature** and **top_p** values to make sure it will always give same results.

**Comment by paulthemagno** [comment]
Yeah, I wonder if there was a sort of constraint in the structure of the parser, since I already tried with a lot of prompts and it usually works, but sometimes it makes mistakes in the number of results.
