### ISSUE TITLE
Add support for Meilisearch vector databases

### ISSUE THREAD

**Issue by alallema** [langchain-ai/langchain#7603]
### Feature request

Add support for Meilisearch vector search.
[Meilisearch](https://www.meilisearch.com) is an open-source search engine. See [documentation](https://www.meilisearch.com/docs)

### Motivation

Meilisearch is releasing the vector search/store feature, which should be available from July 31st.

### Your contribution

I'm working on it and will submit a PR for this issue soon.

**Comment by baskaryan** [comment]
@alallema This would be awesome! Happy to review if you open a PR

**Comment by wwzeng1** [comment]
Hi @baskaryan @alallema! I’m one of the founders of Sweep, a github app that solves issues by writing pull requests. I recently commented in another issue, but this also looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We probably can add docs about Meilisearch, which should help the bot.

We have more onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)
