### ISSUE TITLE
If we continuously send "Hello" messages to the "conversational retrieval chain," the model produces weired/wrong answers.

### ISSUE THREAD

**Issue by chowdary1209** [langchain-ai/langchain#7606]
### System Info

langchain==0.0.170
openai==0.27.4
python
windows

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am using the "**ConversationalRetrievalChain**", Whenever I send a message to a model, it produces wrong results with history, whereas if I send the same message without history, it produces correct results. The issue here is that the model is forming the wrong standalone question, and the same wrong standalone question is passing to the OpenAI Model.

Steps to reproduce:
1. Use the Conversational Retrieval Chan
2. Pass the history on to the chain.
3. Send the "Hello" message continuously.
Here you can observe wrong/weired answers.

The above scenario is Just an example. But whenever we ask some question, immediately if we send the message "Hello", the "conversational retrieval chain" forms the wrong standalone question, hence the openAI model producing wrong answers.

This is the code I am using: -

_template = """
	Use the following pieces of context to answer the question at the end.
	{context}
	If you still cant find the answer, just say that you don't know, don't try to make up an answer.
	You can also look into chat history.
	{chat_history}
	Question: {question}
	Answer:                
	"""
	
	
CONDENSE_QUESTION_PROMPT = PromptTemplate(
	template=_template,
	input_variables = ["context","question", "chat_history"],
)

chain = ConversationalRetrievalChain.from_llm(
	llm= azure_chat_api_llm_objct,
	retriever=vectors.as_retriever(),
	verbose=True,
	chain_type="stuff",
	memory = memory,
	get_chat_history=lambda h:h,    
	# condense_question_prompt=CONDENSE_QUESTION_PROMPT,
	combine_docs_chain_kwargs={"prompt": CONDENSE_QUESTION_PROMPT},
	return_generated_question=True,
	)   
	
chain.run("Hello")

Note:- I have tried multiple way like removing "CONDENCE_QUESTION", without prompt, with different types of prompts, etc..but still its producing wrong standalone question.
Ex:-
_template = """
  Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.
  
  Chat History:
  {chat_history}
  Follow Up Input: {question}
  Standalone question:
"""

Thanks in advance, and please correct me if I made any mistakes in the code.

<img width="458" alt="image" src="https://github.com/hwchase17/langchain/assets/52491904/eb0e3aba-6151-42f8-924b-bda2cb4ccfaf">

### Expected behavior

It should form a proper standalone question when we pass history before passing to model.

**Comment by chowdary1209** [comment]
In between the conversation, if we ask the question like 'what we have discussed so far', model is unable to answer this question.

**Comment by ruchika-wadkar** [comment]
I am facing a similar issue. Did you find a solution?

**Comment by Nghiauet** [comment]
I am facing similar problems too

**Comment by chowdary1209** [comment]
"ConversationalRetrievalChain" is not suitable here, especially when handling the history of messages. I have replaced it with the chain "RetrievalQA." RetrievalQA is producing better results when compared with "ConversationalRetrievalChain."

> I am facing a similar issue. Did you find a solution?

"ConversationalRetrievalChain" is not suitable here, especially when handling the history of messages. I have replaced it with the chain "RetrievalQA." RetrievalQA is producing better results when compared with "ConversationalRetrievalChain."

**Comment by chowdary1209** [comment]
> I am facing a similar issue. Did you find a solution?

"ConversationalRetrievalChain" is not suitable here, especially when handling the history of messages. I have replaced it with the chain "RetrievalQA." RetrievalQA is producing better results when compared with "ConversationalRetrievalChain."

**Comment by chowdary1209** [comment]
"ConversationalRetrievalChain" is not suitable here, especially when handling the history of messages. I have replaced it with the chain "RetrievalQA." RetrievalQA is producing better results when compared with "ConversationalRetrievalChain."
