### ISSUE TITLE
_get_python_function_name does not work with classes

### ISSUE THREAD

**Issue by paschembri** [langchain-ai/langchain#7616]
### System Info

LangChain : v0.0.231

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

# Issue
`convert_to_openai_function` does not work as intended:
- Classes are not supported
- Any function without its source is not supported

# Reproduce

```python
from dataclasses import dataclass
from langchain.chains.openai_functions.base import (
    convert_to_openai_function,
)

@dataclass
class System:
    name: str
    ram: int

convert_to_openai_function(System)
```

### Expected behavior

When calling `langchain.chains.openai_functions.base.convert_to_openai_function`, the subsequent call to `_get_python_function_name` fails because it tries to read source code (and cannot find it).

Something much simpler would be to access the `__name__` attribute of the callable.

**Comment by baskaryan** [comment]
out of curiosity, any reason you're using data class instead of pydantic BaseModel for this?

**Comment by paschembri** [comment]
I use dataclasses because:
- it's built in the standard library (same reason for the attrs library)
- I didn't encountered a use case where I needed more features

if pydantic is what requests is to urllib, i'll definitely look into it though
