### ISSUE TITLE
Issue with Langchain LLM Chains 

### ISSUE THREAD

**Issue by dknamikaze** [langchain-ai/langchain#7618]
### System Info

I am using Windows 11 as OS, RAM = 44GB. Also, I am using  LLaMa vicuna-7b-1.1.ggmlv3.q4_0.bin as Local LLM.
I am using Python 3.11.3 in venv virtual environment in VS code IDE and Langchain version 0.0.221.

<img width="948" alt="Screenshot 2023-07-13_Pydantic Error" src="https://github.com/hwchase17/langchain/assets/88419852/6f172fcd-5a06-472f-b3bb-aec069f626f0">

### Who can help?

@hwchase17 
@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use the following code - 

from llama_cpp import Llama
from langchain import PromptTemplate
from langchain.chains import LLMChain
from langchain.chat_models import ChatOpenAI
import os
from dotenv import load_dotenv
import json
import time

load_dotenv()

model_path = os.environ.get('MODEL_PATH')
print(model_path)
# Load the model
print("....Loading LLAMA")
llm = Llama(model_path=model_path, n_ctx=2048, n_threads=8)
# llm = ChatOpenAI(
#         temperature=0, model_name="gpt-3.5-turbo"
#     )  

text="A lion lives in a jungle"

template = """/
Given the text data {text}, I want you to:
 extract all possible semantic triples in the format of (subject, predicate,object)"""

triple_template = PromptTemplate(input_variables=["text"], template=template)
#print(triple_template)
#triple_template.format(text=t)
chain = LLMChain(llm=llm, prompt=triple_template)
#Run the model
print("RUnning Model.....")
print(chain.run(text=text))

I have commented out llm generated by ChatOpenAI, this code executes and gives desired results if we use OpenAI LLM. However, I am using LLaMa vicuna-7b-1.1.ggmlv3.q4_0.bin, the chain gives the following error - 
File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LLMChain
llm
  value is not a valid dict (type=type_error.dict)

I have tested the LLaMa LLM, it works outside LLM chain without any problem.

### Expected behavior

In response to the given text, it should have returned a semantic triple of form ( Subject, Predicate Object) ie. ( Lion, Lives in , Jungle) or something similar.

**Comment by dknamikaze** [comment]
I would say it's better to extend `BaseChatModel`

```
from langchain.chat_models.base import BaseChatModel
class LlamaWrapper(BaseChatModel): 

    def __init__(self, model_path, n_ctx, n_threads):
        self.llm = Llama(model_path=model_path, n_ctx=n_ctx, n_threads=n_threads)
        client: Any  #: :meta private:
```

Is anyone currently working on wrapper class for LLama wrapper. I am having trouble implementing all abstract methods

**Comment by hinthornw** [comment]
https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp
^ is this what you're looking for?

You can check the integrations currently supported: https://integrations.langchain.com/llms
