### ISSUE TITLE
Pandas / CSV agent only show partial results from dataframe head

### ISSUE THREAD

**Issue by lynngao** [langchain-ai/langchain#7623]
### System Info

Hi my data has 10 rows and I tried with both pandas and csv agent, in the observations I can see the agents are able to process all rows, but in the final answer both agents only output the first 5 rows from df.head(). I tried to set 'number_of_head_rows' to 10 but it doesn't work. Is there any way to make the agents to show results from all rows rather the the head?

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chat_models import AzureChatOpenAI
from langchain.agents import create_pandas_dataframe_agent
from langchain.agents.agent_types import AgentType

pd_agent = create_pandas_dataframe_agent(AzureChatOpenAI(deployment_name="gpt-4", model_kwargs={
    "api_key": openai.api_key,
    "api_base": openai.api_base,
    "api_type": openai.api_type,
    "api_version": openai.api_version
}, temperature=0.0), 
    df, 
    agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    verbose=True,
    handle_parsing_errors=True)

### Expected behavior

should output the results from whole table

**Comment by dudesparsh** [comment]
Hi @lynngao , I think the bot has commented correctly. As an alternative what you can do ->

1. In your local / repo find-> [langchain/agents/agent_toolkits/pandas/base.py](https://github.com/hwchase17/langchain/blob/-/langchain/agents/agent_toolkits/pandas/base.py)
2. In this update the variable - number_of_head_rows -> to the number you want ( currently as default it is setup as 5 ).

I think then you'll be able to get expected number of outputs in the head section correctly.
