### ISSUE TITLE
Dimension from embeddings

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#7632]
### Feature request

import os
from langchain.embeddings import HuggingFaceEmbeddings 

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
model_kwargs = {"device": "cpu"}
encode_kwargs = {"normalize_embeddings": False}

embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL, model_kwargs=model_kwargs, encode_kwargs=encode_kwargs
)

Now I want to get the dimension from embeddings like SentenceTransformer.

from sentence_transformers import SentenceTransformer
device = "cpu"
model = SentenceTransformer(EMBEDDING_MODEL, device=device)

dimension = model.get_sentence_embedding_dimension()

### Motivation

Wrapper method of SentenceTransformer (get_sentence_embedding_dimension())

### Your contribution

no yet

**Comment by JulesGM** [comment]
Trying to reopen this, having to encode an embedding to know the size of the embeddings looks pretty dirty and is not great.

**Comment by pixelogik** [comment]
I agree with @JulesGM . Doing something like this feels wrong 

```
embedding_model = HuggingFaceEmbeddings(model_name=model_name)
dimension = len(embedding_model.embed_query("I just want to know the embedding space dimension"))
```

I would rather do something like 

```
embedding_model = HuggingFaceEmbeddings(model_name=model_name)
dimension = embedding_model.get_embedding_dimension() 
```
