### ISSUE TITLE
chromadb.errors.InvalidDimensionException: Dimensionality of (512) does not match index dimensionality (768)

### ISSUE THREAD

**Issue by baiziyuandyufei** [langchain-ai/langchain#7634]
### System Info

langchain               0.0.230

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
class SemanticSearch():
    """Class containing modules for the semantic search.
    """

    model_name: str
    model: HuggingFaceEmbeddings

    def __init__(self,
                 model_name: str = "sentence-transformers/distiluse-base-multilingual-cased-v2",
                 **kwargs
        ) -> None:
        self.model_name = model_name
        self.model = HuggingFaceEmbeddings(model_name=self.model_name, **kwargs)

    def vectorize_doc(self, doc: Path, vectordb_dir: Path) -> None:
        """Transform a doc containing all the information into a VectorDB.

        Args:
            doc (Path): File path containing the information. doc is a .txt file with /n/n/n separator.
            vectordb_path (Path, optional): _description_. Defaults to config.VECTORDB_PATH.
        """
        if os.path.exists(doc):
            with open(doc, "r") as f:
                text = f.read()
            texts = text.split("\n\n\n")
            LOGGER.info(f'Number of chunks: {len(texts)}')
            Chroma.from_texts(texts=texts, 
                              embedding=self.model, 
                              persist_directory=str(vectordb_dir) # Need to be a string
            )
            LOGGER.info(f"VectorDB correctly created at {vectordb_dir}")
        else:
            raise FileNotFoundError(f"{doc} does not exist.")

    def search(self, query: str, vectordb_dir:str = config.get('config', 'VECTORDB_PATH'), k: int = 1) -> List[Tuple[Document, float]]:
        """From a query, find the elements corresponding based on personal information stored in vectordb.
        Euclidian distance is used to find the closest vectors.

        Args:
        query (str): Question asked by the user.
        vectordb_dir (str, optional): Path to the vectordb. Defaults to config.VECTORDB_DIR.

        Returns:
        List[Tuple[Document, float]]: Elements corresponding to the query based on semantic search, associated
        with their respective score.
        """
        timestamp = time.time()
        vectordb = Chroma(persist_directory=vectordb_dir, embedding_function=self.model)
        results = vectordb.similarity_search_with_score(query=query, k=k)
        LOGGER.info(f"It took {time.time() - timestamp} to search elements with semantic search.")
        return results
```

### Expected behavior

no error

**Comment by Bearnardd** [comment]
Hi @baiziyuandyufei! As an initial solution, you can attempt to resolve this issue in a similar manner as described in the similar issue: https://github.com/hwchase17/langchain/issues/5046. The problem may be caused by having embeddings with different dimensions that are already stored within the chroma db. If this situation applies to you, try removing the chroma db folder that contains the stored embeddings.

**Comment by laeljh** [comment]
I have a similar issue, in my case I used custom batching method and a llama 2 tokenizer to create embeddings and then I'm trying to store the embeddings. My batching process cuts the text into uneven length fragments if it helps to split at more reasonable place, similarly to recursive splitting. 
Generated embeddings have length up to max configured token length. 
Using max tokens set to 256 the embeddings can have length of UP TO 256 tokens. 
Does ChromeDB support any type of default padding to even out the length of the tokens or should that be done by the models tokenizer? I don't do chunk overlaps and I'm wondering if adding padding will affect how embeddings are understood by the model.

**Comment by lmsanch** [comment]
I am finding the same issue. Considering switching to another vector db.
