### ISSUE TITLE
Uncap pydantic dependency (allow pydantic 2.x)

### ISSUE THREAD

**Issue by rec** [langchain-ai/langchain#7663]
### Feature request

Hello, and thanks for this fantastic library!!

In pyproject.toml, the Pydantic library [is pinned to version 1.x](https://github.com/hwchase17/langchain/blob/master/pyproject.toml#L15) 

I'd like to unpin that dependency by changing `^1` to `>=1`.

### Motivation

Pydantic 2.0.2 is apparently production-ready, and it has a feature we badly need but our dependency on langchain prevents us from using it.

Deep background on dependency pinning here: https://iscinumpy.dev/post/bound-version-constraints/

### Your contribution

Two tiny commits like [this](https://github.com/rec/langchain/commits/master) and [this one in langsmith](https://github.com/rec/langchainplus-sdk/commits/main) are all that is needed.

I can test the langchain commit and submit it for review; I can send the langsmith one for review, but not sure how to test it.

**Comment by peter65374** [comment]
Will langchain support Pydantic V2 in near future? BTW, with fastapi and some essential software bumping to pydantic v2, does langchain have the plan to support that?

**Comment by DeoLeung** [comment]
some usage of `root_validator` is failing on pydantic v2

**Comment by rec** [comment]
Can you post the error message here, please? :-)

**Comment by DeoLeung** [comment]
```
    from langchain.docstore.document import Document
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/__init__.py:8: in <module>
    from langchain.chains import (
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/chains/__init__.py:2: in <module>
    from langchain.chains.llm import LLMChain
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/chains/llm.py:7: in <module>
    from langchain.llms.base import LLM
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/llms/__init__.py:2: in <module>
    from langchain.llms.cohere import Cohere
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/llms/cohere.py:11: in <module>
    class Cohere(BaseModel, LLM):
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/langchain/llms/cohere.py:51: in Cohere
    @root_validator()
../../.virtualenvs/dispatcher/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py:228: in root_validator
    raise PydanticUserError(
E   pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
E
E   For further information visit https://errors.pydantic.dev/2.0.3/u/root-validator-pre-skip
```

**Comment by rec** [comment]
Thank you!  I'll take a look at this over the next week.

**Comment by baskaryan** [comment]
Hi all! As of `langchain==0.0.267` the pydantic version is uncapped and we should largely be cross-compatible with pydantic v1 and v2. There are still some known pydantic v2 failure modes explained in #9337, and some potentially unknown failure modes. 

We'd **love** to hear if the latest version unblocks your use cases or if you're still running into issues!

cc @rec @DeoLeung @peter65374

**Comment by peter65374** [comment]
Thanks a lot. @baskaryan I upgraded langchain and other dependencies and moved to pydantic v2. It works smoothly. Well done.

**Comment by rec** [comment]
Thanks, I think this is long fixed.
