### ISSUE TITLE
DOC: Text Splitter Python Doc down webpage

### ISSUE THREAD

**Issue by JanLeyva** [langchain-ai/langchain#7665]
### Issue with current documentation:

Hello, I was looking into the LangChain `text_splitter` documentation and found that Python documentation for this section is down https://python.langchain.com/docs/modules/data_connection/text_splitters.html.  Thank you for checking it!

**Comment by keenborder786** [comment]
@JanLeyva: Please use this link -> https://python.langchain.com/docs/modules/data_connection/document_transformers/

**Comment by baskaryan** [comment]
we should a a redirect from the old link to the new one, @JanLeyva thanks for flagging!
