### ISSUE TITLE
ArxivRetriever should return a metadata Sources field

### ISSUE THREAD

**Issue by dcieslak19973** [langchain-ai/langchain#7666]
### System Info

langchain=0.0.230

### Who can help?

@eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Looks like in `ArxivAPIWrapper` perhaps could change:
```
            if self.load_all_available_meta:
                extra_metadata = {
                    "entry_id": result.entry_id,
                    "published_first_time": str(result.published.date()),
                    "comment": result.comment,
                    "journal_ref": result.journal_ref,
                    "doi": result.doi,
                    "primary_category": result.primary_category,
                    "categories": result.categories,
                    "links": [link.href for link in result.links],
                }
            else:
                extra_metadata = {}
            metadata = {
                "Published": str(result.updated.date()),
                "Title": result.title,
                "Authors": ", ".join(a.name for a in result.authors),
                "Summary": result.summary,
                **extra_metadata,
            }
```
To include a "Sources" tag, perhaps with the direct link(s) to the paper

### Expected behavior

Metadata containing a "Sources" tag

**Comment by keenborder786** [comment]
That's a good point. I can add this.

**Comment by keenborder786** [comment]
@dcieslak19973 is this fine^^^
