### ISSUE TITLE
Issue: Can't use NotebookLoader to load ipynb files generically

### ISSUE THREAD

**Issue by eilone** [langchain-ai/langchain#7671]
### Issue you'd like to raise.

Hi!
I have some problem with the `NotebookLoader` loader:
I'm trying to access my repo and detect all of the `.ipynb` files, and then load them to the LLM Chain I'm implementing using LangChain. The repo can be viewed [here](https://github.com/eilone/RepoReader/tree/eilon-br) 

```
    for ext in extensions:
        glob_pattern = f'**/*.{ext}'
        try:
            loader = None
            if ext == 'ipynb':
                loader = **NotebookLoader**(str(repo_path), include_outputs=True, max_output_length=20,
                                        remove_newline=True,  loader_kwargs={"content_type": "text/plain"})
```

Yet I don't know how to pass the `glob_pattern` to this loader, resulting in going to the base dir and not being able to look for the notebook files...

```
[Errno 21] Is a directory: 'my_dir'
```

Can you please help me figure it out? Considering I don't want to pass each `ipynb` file-path individually?

**Comment by mswoff** [comment]
The `NotebookLoader` in LangChain does not directly support glob patterns. It expects a direct path to a single notebook file. If you want to load multiple notebooks from a directory, you will need to iterate over the files in the directory and create a `NotebookLoader` for each one. Here is an example of how you might do this:

```
import glob

notebook_files = glob.glob(f'{repo_path}/**/*.{ext}', recursive=True)

for notebook_file in notebook_files:
    loader = NotebookLoader(notebook_file, include_outputs=True, max_output_length=20,
                            remove_newline=True,  loader_kwargs={"content_type": "text/plain"})
    # Use loader here
```

This code will find all `.ipynb` files in the directory specified by `repo_path` and its subdirectories, and create a `NotebookLoader` for each one.
