### ISSUE TITLE
handle_tool_error in @tool decorator

### ISSUE THREAD

**Issue by iuiu34** [langchain-ai/langchain#7715]
### Feature request

we have the `@tool` decorator and the `Tool.from_function` function.

But they are (or seem to me) inconsistent. The kwargs `handle_tool_error` and `return_direct` are only available in `Tool.from_function` .

Shouldn't be available in both?

Shouldn't be `@tool` just a mirror of `Tool.from_function` ?

### Motivation

I want to be able to do `@tool(handle_tool_error=True)`

### Your contribution

If this is not me just reading wrong the docs. And needs development, happy to do a PR

**Comment by DM1122** [comment]
In the same boat here, this would be a valuable addition

**Comment by MattNot** [comment]
still not consistent, any workaround?

**Comment by karux** [comment]
because handling exceptions is a good coding practice, would be good to add hanndle_tool_error as a valid tool decorator annotation.
