### ISSUE TITLE
pip-audit detects numerous vulnerabilities

### ISSUE THREAD

**Issue by matthew-e-thomas** [langchain-ai/langchain#7716]
### System Info

Using Lanchain version .233 currently, and each time I make an update and run tests on my project, pip-audit is returning an additional vulnerability. I use Gitlab for the project and I am adding commands to ignore these vulnerabilities in gitlab-ci.yml, but currently the command looks like:

`- pip-audit --ignore-vuln PYSEC-2023-109 --ignore-vuln PYSEC-2023-110 --ignore-vuln PYSEC-2023-98 --ignore-vuln PYSEC-2023-91 --ignore-vuln PYSEC-2023-92`

these are all langchain vulnerabilities. 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce behavior:

1. Use Gitlab's CI-CD flow with a gitlab-ci.yml file
2. use pip-audit from pip-tools as part of the testing
3. push a change to production

### Expected behavior

Most well-known packages don't get any vulnerabilities, or when they do they get fixed shortly.

**Comment by aiakubovich** [comment]
having the same problem
