### ISSUE TITLE
Issue: Need a trace or debug feature in Lanchain DirectoryLoader

### ISSUE THREAD

**Issue by botchagalupe** [langchain-ai/langchain#7725]
### Issue you'd like to raise.

I've set "langchain.debug=True"; however, it does not work for the DirectoryLoader. I have a notebook that tried to load a dozen or more PDFs, and typically, at least one of the files fails (see attached). I looked at the code, and as far as I can tell, there is no trace or debug feature in (https://github.com/hwchase17/langchain/tree/master/langchain/document_loaders). 

My issue is that the loader code is a black box. I can't tell which file is failing; therefore, I have to process each one individually to find out which one is failing. It would be beneficial if a trace/debugger could help me identify which file it's failing on. 

TIA
<img width="912" alt="Screen Shot 2023-07-14 at 9 04 56 AM" src="https://github.com/hwchase17/langchain/assets/457288/fd5b7732-1040-4c73-91dc-abc41fb9cadd">

### Suggestion:

Please make a debug option for "https://github.com/hwchase17/langchain/tree/master/langchain/document_loaders" code.

**Comment by mattwa1sh** [comment]
This can not possibly be the answer to modify source. This is super basic?
