### ISSUE TITLE
SagemakerEndpoint model doesn't return full output..only when prompted with langchain

### ISSUE THREAD

**Issue by VivekLokesh** [langchain-ai/langchain#7731]
### System Info

infra - sagemaker
model - model deployed with `HuggingFaceModel(...).deploy()`
langchain version - v0.0.233
chain types used - RetrievalQA, load_qa_chain

I have a huggingface model deployed behind a sagemaker endpoint which produces outputs as expected when run prediction against it directly. However, when I initialize it with SagemakerEndpoint class from langchain, it only return two characters and sometimes an empty string. I scoured through the internet and langchain docs for the last couple days and my initialization and chain prompting aspects of the code seem to be in line with the docs guidelines and anecdotal recommendations laid out. 
I think this either a lack integration support for huggingface models deployed with sagemaker or I'm missing something here that's not been written in the docs and examples. Please review and let me know either way. 

### Below code will reproduce the behavior I'm experiencing.

```
from langchain import SagemakerEndpoint
from langchain.llms.sagemaker_endpoint import ContentHandlerBase, LLMContentHandler

endpoint = "xxxxxx-2023-07-14-05-34-901"

parameters = {
    "do_sample": True,
    "top_p": 0.95,
    "temperature": 0.1,
    "max_new_tokens": 256,
    "num_return_sequences": 4,
}
    
class ContentHandler(LLMContentHandler):
        content_type = "application/json"
        accepts = "application/json"
        
        def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
            input_str = json.dumps({"inputs": prompt, **model_kwargs})
            return input_str.encode('utf-8')
        
        def transform_output(self, output: bytes) -> str:
            response_json = json.loads(output.read().decode("utf-8"))
            return response_json[0]['generated_text']
        
content_handler = ContentHandler()
        
sm_llm=SagemakerEndpoint(
        endpoint_name=endpoint,
        region_name="us-west-2",
        model_kwargs= parameters,
        content_handler=content_handler,
    )

vectordb = Chroma(persist_directory="db", embedding_function=embedding, collection_name="docs")
retriever = vectordb.as_retriever(search_kwargs={'k':3})
print("retriever: ", retriever)

qa_chain = RetrievalQA.from_chain_type(llm=sm_llm, 
                                  chain_type="stuff", 
                                  retriever=retriever,
                                  return_source_documents=True)
```

#### Here's the output (or lack thereof) from prompting with langchain, in above code. 

```
system_prompt = """<|SYSTEM|># Your are a helpful and harmless assistant for providing clear and succinct answers to questions."""

question = "What is your purpose?"
query = (system_prompt + "<|USER|>" + question + "<|ASSISTANT|>")
llm_response = qa_chain(query)
print(llm_response['result'])

---------------------------------------------------------------------------
Output:

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

<some doc context from vectordb goes here - removed due to info sensitivity>

Question: # <|SYSTEM|># Your are a helpful and harmless assistant for providing clear and succint answers to questions.
What is your purpose?
Helpful Answer: 
```
As shown above, there's no output for 'Helpful Answer: '. 
### Model returns the full output with the below code which runs direct prediction against the endpoint.

```
import boto3
from sagemaker.huggingface import HuggingFacePredictor
from sagemaker.session import Session

sm_session = Session(boto_session=boto3.session.Session())

payload = {
    "inputs": "What is your purpose?",
    "parameters": {"max_new_tokens": 256, "do_sample": True}
}

local_llm = HuggingFacePredictor(endpoint, sm_session)
chat = local_llm.predict(data=payload)
result = chat[0]["generated_text"]
print(result)
```

#### Output for direct prediction from the code executed above. 

```
What is your purpose?
You seem important. What is your value? What can you do that makes you unique? What is your unique value?

* You are important to the people who know you best. 
* When you accomplish the things you want to do, you will become valuable to the people who matter to you.
* We value you because you are special
```

As it can be seen above, the model returns an output (not a great one) but the fact is it does when I'm prompted and not when wrapped with SagemakerEndpoint class and prompted with prompted with langchain.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Expected behavior

SagemakerEndpoint Model returning the full output, similar to how it does when prompted directly with a predictor.

**Comment by VivekLokesh** [comment]
The transform_output fn recommended by the bot is identical to my transform_output fn in code, except for the conditional statement to check for the generated text. This doesn't alter the model behavior to return the full output when I'm prompted with langchain.

#### my function:

```
        def transform_output(self, output: bytes) -> str:
            response_json = json.loads(output.read().decode("utf-8"))
            return response_json[0]['generated_text']
```
        
#### bot recommended function:

```
        def transform_output(self, output: bytes) -> str:
            response_json = json.loads(output.read().decode("utf-8"))
            if 'generated_text' in response_json[0]:
                return response_json[0]['generated_text']
            else:
                return ''
```

**Comment by knkarthick** [comment]
I'm facing the same issue. When using Sagemaker Endpoint directly, the complete response is returned.
Also, when trying with langchain.HuggingFaceHub, it's returing the complete response. With LLMContentHandler, it's returning a truncated response.

`from langchain import PromptTemplate, LLMChain
ENDPOINT_NAME = "open-chat-falcon-7B-24-07-2023-05-44-26"

from typing import Dict

from langchain import PromptTemplate, SagemakerEndpoint
from langchain.llms.sagemaker_endpoint import LLMContentHandler
import json

parameters = {
        "early_stopping": True,
        "length_penalty": 2.0,
        "max_new_tokens": 1024,
        "temperature": 0.01,
    }


class ContentHandler(LLMContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        input_str = json.dumps({"inputs": prompt, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json[0]["generated_text"]


content_handler = ContentHandler()

llm=SagemakerEndpoint(
        endpoint_name=ENDPOINT_NAME,
        region_name="us-west-2",
        model_kwargs=parameters,
        content_handler=content_handler,
    )

template = """
You are an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

{question}
"""
prompt = PromptTemplate(template=template, input_variables=["question"])
llm_chain = LLMChain(prompt=prompt, llm=llm)

question = "Write a resignation letter addressing the manager"

print(llm_chain.run(question))`

>>>>>>RESULT:
You are an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

Write a resignation letter addressing the manager
Dear [Manager],

I am writing to inform you of my intention to resign from my

`llm.predict(question)`

>>>>>>RESULT:
'Write a resignation letter addressing the manager\nDear [Manager],\n\nI am writing to inform you of my intention to resign from'


`import boto3
import json
import time

runtime= boto3.client('runtime.sagemaker')

payload = """Write a resignation letter addressing the manager"""

parameters = {
        "early_stopping": True,
        "length_penalty": 2.0,
        "max_new_tokens": 1024,
        "temperature": 0.01,
    }

start = time.time()
response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,
                                      ContentType='application/json',
                                      Body=json.dumps({
                                          "inputs": payload,
                                          "parameters": parameters
                                            })
                                          )
time_taken = (time.time() - start)
output = json.loads(response['Body'].read())

print("Time Taken (s): ", time_taken)
print(output[0]['generated_text'])`

Write a resignation letter addressing the manager
Dear [Manager],

I am writing to inform you of my intention to resign from my current position at [Company Name]. My last day of work will be [insert date].

I have appreciated my time here and the opportunities given to me. I have learned a lot and grown professionally during my time with the company.

I am confident that I will be able to find a suitable position in the future. If you need any assistance during this transition, please do not hesitate to contact me.

Thank you for the opportunity and I look forward to hearing from you.

Sincerely,
[Your Name]

**Comment by VivekLokesh** [comment]
Appears to be some sort of bug with how the langchain SagemakerEndpoint class is wrapping and invoking the model endpoint, as part of combined prompting in load_qa and retrivel_qa chain. It's a simple and yet a severe bug/lack-of-support for sagemaker.

I even tried langchain's [custom llm class wrapper](https://python.langchain.com/docs/modules/model_io/models/llms/custom_llm) to extend it to use HuggingFacePredictor, as it's the only one that returns the full output, and yet I'm still experiencing the same behavior with langchain.

This seems to be clear lack of support for sagemaker, it will be great if some devs here took notice of this. 
fyi/a- @hwchase17 @hinthornw @nfcampos @leo-gan

**Comment by hinthornw** [comment]
Thanks for raising this issue! I'd be happy to review / test out a PR proposing a fix

**Comment by itachi-452b** [comment]
Tried tweaking the handler and it worked for me


`class ContentHandler(LLMContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        input_str = json.dumps({"inputs": prompt,"parameters": {"max_new_tokens": 1000}, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json[0]["generated_text"]

llm=SagemakerEndpoint(
        endpoint_name="ENDPOINT NAME",
        model_kwargs={"temperature": 1e-10},
        region_name="AWS REGION",
        content_handler=content_handler,
    )`
    
    
    

In the above code, I set the parameter inside the content handler and when I tried this it worked for me.


Can you try tweaking the code as below:

`parameters = {
    "do_sample": True,
    "top_p": 0.95,
    "temperature": 0.1,
    "max_new_tokens": 256,
    "num_return_sequences": 4,
}
    
class ContentHandler(LLMContentHandler):
        content_type = "application/json"
        accepts = "application/json"
        
        def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
            input_str = json.dumps({"inputs": prompt, "parameters": parameters, **model_kwargs})
            return input_str.encode('utf-8')
        
        def transform_output(self, output: bytes) -> str:
            response_json = json.loads(output.read().decode("utf-8"))
            return response_json[0]['generated_text']
        
content_handler = ContentHandler()
        
sm_llm=SagemakerEndpoint(
        endpoint_name=endpoint,
        region_name="us-west-2",
        content_handler=content_handler,
    )

vectordb = Chroma(persist_directory="db", embedding_function=embedding, collection_name="docs")
retriever = vectordb.as_retriever(search_kwargs={'k':3})
print("retriever: ", retriever)

qa_chain = RetrievalQA.from_chain_type(llm=sm_llm, 
                                  chain_type="stuff", 
                                  retriever=retriever,
                                  return_source_documents=True)`

**Comment by VivekLokesh** [comment]
@itachi-452b Although it's a minor one, that tweak did it. The model returns full output now. Thanks!
It would be great if the sagemaker usage examples in the langchain docs are updated to reflect this.
