### ISSUE TITLE
Streaming does not work using streaming callbacks for gpt4all model

### ISSUE THREAD

**Issue by Anindyadeep** [langchain-ai/langchain#7747]
### System Info

**System Information**

System: `Linux`
OS: `Pop OS`
Langchain version: `0.0.232`
Python version: `3.9.17`
gpt4all version: used for both version `1.0.1` and version `1.0.3`.

### Who can help?

Models:

@hwchase17 

Streaming Callbacks:

@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

```python3
import gpt4all as gpt 
from langchain import PromptTemplate, LLMChain
from langchain.llms import GPT4All
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

template = """
Let's think step by step of the question: {question}
Based on all the thought the final answer becomes:
"""

prompt = PromptTemplate(template=template, input_variables=["question"])

local_path = (
    "./model/ggml-gpt4all-j-v1.3-groovy.bin" 
)

callbacks = [StreamingStdOutCallbackHandler()]

llm = GPT4All(
    model=local_path, 
    backend="llama", 
    verbose=True, callbacks=callbacks
)

llm_chain = LLMChain(prompt=prompt, llm=llm, verbose=True)

question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"
llm_chain.run(question)
```

### Expected behavior

I should tokens streaming and printing in the terminal one at a time, but everything I get all at once.

**Comment by FernandoFerrerTDK** [comment]
I'm having the same issue.

**Comment by Mabenan** [comment]
you have to  set streaming = True in GTP4All Constructor

**Comment by afedotov-align** [comment]
Hey guys, this is still not working with the latest langchain version. 
@Mabenan I tried like this, but it doesn't work

`from langchain.llms import GPT4All
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.callbacks.base import BaseCallbackManager
import os

callback_manager = BaseCallbackManager([StreamingStdOutCallbackHandler()])

llm = GPT4All(
    **streaming=True,**
    model=f"./{os.getenv('GPT4ALL_MODEL')}",
    verbose=True,
    callback_manager=callback_manager,
)`

@Anindyadeep could you clarify did you figure it out?

**Comment by Anindyadeep** [comment]
@afedotov-align can you  please share your full code and the output which is generated?

Also, it would be awesome to use "```" before and after pasting the code, like this:

```python
from langchain.llms import GPT4All
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.callbacks.base import BaseCallbackManager
import os

callback_manager = BaseCallbackManager([StreamingStdOutCallbackHandler()])

llm = GPT4All(
streaming=True,
model=f"./{os.getenv('GPT4ALL_MODEL')}",
verbose=True,
callback_manager=callback_manager,
)`

```

**Comment by afedotov-align** [comment]
Hi @Anindyadeep , sure, thanks for quick response,
Here is the full code example which is basically the same that you posted in your original question.
The output is printed at once at the end of generation.

```from langchain.prompts import PromptTemplate
from langchain.llms import GPT4All
from langchain.chains import LLMChain
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

template = """
Let's think step by step of the question: {question}
"""

prompt = PromptTemplate(template=template, input_variables=["question"])

callbacks = [StreamingStdOutCallbackHandler()]

llm = GPT4All(
    streaming=True,
    model="./mistral-7b-openorca.Q4_0.gguf",
    verbose=True,
    callbacks=callbacks,
)

llm_chain = LLMChain(prompt=prompt, llm=llm, verbose=True)

question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"
llm_chain.run(question)
```
<img width="1693" alt="image" src="https://github.com/langchain-ai/langchain/assets/91598042/1d81be07-965f-4901-92df-8b401e4f6d44">

**Comment by Anindyadeep** [comment]
I see, thanks @afedotov-align for raising this issue, I will get back to you on this

**Comment by davidngrc** [comment]
@niansa please help look into this one, thank you.
@Anindyadeep  this ticket is not the same as the one in #704 . that one is python, this one is web server call, please re-open it.

**Comment by StatisticAnomaly** [comment]
Any fix for this yet, or anyone manage to get the stoken streaming predictions working? if so can anyone provide a working code snippit?

**Comment by yjg30737** [comment]
Modern version:
```python
from langchain_community.llms import GPT4All as GPT4All_langchain
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain_core.prompts import PromptTemplate

template = """
Let's think step by step of the question: {question}
"""

prompt = PromptTemplate(template=template, input_variables=["question"])

callbacks = [StreamingStdOutCallbackHandler()]

llm = GPT4All_langchain(
    streaming=True,
    model="./Meta-Llama-3-8B-Instruct.Q4_0.gguf",
    verbose=True,
    callbacks=callbacks,
)

llm_chain = prompt | llm

question = "What NFL team won the Super Bowl in the year Justin Bieber was born?"
llm_chain.invoke({
    "question": question
})
