### ISSUE TITLE
streaming support for LLM, from HuggingFaceEndpoint

### ISSUE THREAD

**Issue by sglebs** [langchain-ai/langchain#7785]
### System Info

Python 3.9.6
langchain==0.0.229
MacOS on Apple M2 hardware

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

 I use RetrievalQA.from_chain_type(llm=llm, ...) and with these LLMs streaming works:

  - ChatOpenAI.  (I can pass streaming=True)
  - OpenAI.   (I can pass streaming=True)

However, with HuggingFaceEndpoint the streaming just does not work. It does not even take streaming=bool.

### Expected behavior

I am able to switch LLM engines via config, and would like to have the streaming feature as the output is incrementally shown to the user, which is great for slow responses (much better usability - no need to wait for the entire time to compute the entire answer). Unfortunately this is not possible with HuggingFaceEndpoint.

https://github.com/hwchase17/langchain/issues/2918 talks about HuggingFaceHub , which is not really my case (HuggingFaceEndpoint)

Is there a simple way to make it work with RetrievalQA.from_chain_type(llm=llm,...) where the llm is created like 

```
    llm = HuggingFaceEndpoint(endpoint_url=my_endpoint,
                                task="text-generation",
                                streaming=True
                                callbacks = callbacks,
                                model_kwargs={"temperature": temperature, "max_length": 1024})
```
Thanks!

**Comment by Gitwangpin** [comment]
Do HuggingFaceEndpoint and LlamaCpp also support streaming? The current version only supports OpenAI, ChatOpenAI, and ChatAnthropic? I want to integrate LLAMA2 and LangChain, what is the best practice?

**Comment by ravidhu** [comment]
Hugginface endpoint use TGI (https://github.com/huggingface/text-generation-inference) as a backend api. So you need to use the langchain wrapper for this backend, here an example :

```python
huggingFaceTGILlm = HuggingFaceTextGenInference(
    inference_server_url=hg_endpoint_url,
    streaming=True,
    server_kwargs={
        "headers": {
          "Authorization": f"Bearer {hf_token}",
          "Content-Type": "application/json",
        }
    },
)
```

Then you can use it as the llm parameter for the chains :
```python
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

llm_chain = LLMChain(
  llm=huggingFaceTGILlm,
  prompt=PromptTemplate(
    input_variables=["instruction"],
    template="{instruction}"
  )
)

res = llm_chain.run({
    "instruction":prompt
}, callbacks=[StreamingStdOutCallbackHandler()])
```

**Comment by PeterTucker** [comment]
@ravidhu Do you know how you would run your example in a FastAPI route?

**Comment by lmoy28** [comment]
@PeterTucker did you find how to do it with FastAPI ?

**Comment by Tarun2004e** [comment]
repo_id="mistralai/Mistral-7B-Instruct-v0.2"
llm=HuggingFaceEndpoint(repo_id=repo_id,max_new_tokens=2048,temperature=1,huggingfacehub_api_token=key)




StopIteration                             Traceback (most recent call last)
[<ipython-input-19-7fb5b0ddeb9f>](https://localhost:8080/#) in <cell line: 0>()
----> 1 llm.invoke("what is machine learning?")

7 frames
[/usr/local/lib/python3.11/dist-packages/huggingface_hub/inference/_providers/__init__.py](https://localhost:8080/#) in get_provider_helper(provider, task, model)
    163             raise ValueError("Specifying a model is required when provider is 'auto'")
    164         provider_mapping = _fetch_inference_provider_mapping(model)
--> 165         provider = next(iter(provider_mapping))
    166 
    167     provider_tasks = PROVIDERS.get(provider)  # type: ignore

StopIteration:



can someone help?
