### ISSUE TITLE
Confluence loader usage of id causes a conflict with Weaviate

### ISSUE THREAD

**Issue by elabbarw** [langchain-ai/langchain#7803]
### System Info

Langchain Version 0.0.233

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Embed from the confluence loader documents direct to weaviate.from_documents and you will get errors related to the id. (e.g.: {'error': [{'message': "'id' is a reserved property name, no such prop with name 'id' found in class 'LangChain_96f9046045fd4623acec34b0ee6acebb' in the schema. Check your schema files for which properties in this class are available"}]}_

**** Code to reproduce ****

from langchain.document_loaders import ConfluenceLoader

loader = ConfluenceLoader(url="https://yoursite.atlassian.com/wiki", token="12345")
documents = loader.load(
    space_key="SPACE", include_attachments=True, limit=50, max_pages=50
)

text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings()

db = Weaviate.from_documents(docs, embeddings, weaviate_url=WEAVIATE_URL, by_text=False)

I can fix it by creating a new list with documents that have pageid instead of id in metadata:

new_documents = []
for doc in documents:
    metadata = doc.metadata.copy()  
    metadata['pageid'] = metadata.pop('id') 
    new_doc = Document(page_content=doc.page_content, metadata=metadata)  
    new_documents.append(new_doc) 

and then continue with :

db = Weaviate.from_documents(docs, embeddings, weaviate_url=WEAVIATE_URL, by_text=False)

### Expected behavior

Documents to get embedded without the error of:  {'error': [{'message': "'id' is a reserved property name, no such prop with name 'id' found in class 'LangChain_96f9046045fd4623acec34b0ee6acebb' in the schema. Check your schema files for which properties in this class are available"}]}

**Comment by elabbarw** [comment]
Would it be better to fix the Confluenceloader so that it saves Document metadata with pageid instead of id, or should I add a check to Weaviate to change id to textid?

**Comment by Jflick58** [comment]
Given that the key is reserved by Weaviate, and not by Confluence, I'd be in favor of adding the check to the Weaviate loader.
