### ISSUE TITLE
vectorstores Chroma client_settings anonymized_telemetry=False dont work

### ISSUE THREAD

**Issue by cabbonadio** [langchain-ai/langchain#7804]
### System Info

0.0.234 MacOS Big Sur

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Create a vectorstore with some documents

Try this code to retrieve the documents

`
from chromadb.config import Settings
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma

embeddings = OpenAIEmbeddings()

vectorstore = Chroma(
    collection_name="langchain_store",
    embedding_function=embeddings,
    client_settings=Settings(anonymized_telemetry=False),
    persist_directory="./dist/vectordb",
)
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
docs = retriever.get_relevant_documents("quantos litros de oleo vai no motor?")
print(docs)`

The result is [] no documents 

Now if I change the client_settings parameter to 
client_settings=Settings(anonymized_telemetry=False, chroma_db_impl="duckdb+parquet", persist_directory="./dist/vectordb"),

I get the results correct

### Expected behavior

Should be able to set 
client_settings=Settings(anonymized_telemetry=False) # to disable telemetry 
and receive the results back from the vectorstore

**Comment by kristellewidjaja** [comment]
@cabbonadio I also encountered the same issue when explicitly enabling or disabling the telemetry by following the recommended way from the [official Chroma DB website](https://docs.trychroma.com/telemetry). 

In case other people run into the same issue like us, I've decided to create a pull request to make Langchain Chroma's constructor to be more robust.

**Comment by gxrxrdx** [comment]
solved same issue with chroma 0.4.9 by specifying **is_persistent**:
`Chroma('mydatabase', 
                      embedding_function=embeddings, 
                      persist_directory='./data',
                      client_settings= Settings(
                          anonymized_telemetry=False,
                          is_persistent=True,
                          ))`

**Comment by fpaupier** [comment]
@gxrxrdx Regarding this langchain doc on RAG, https://python.langchain.com/docs/use_cases/question_answering/, especiallly the line `
vectorstore = Chroma.from_documents(documents=splits, embedding=OpenAIEmbeddings())` how would you adapt the Chroma call to disable telemetry ? Simply passing the client settings `Settings(anonymized_telemetry=False)` did not work for me.

**Comment by ZuzooVn** [comment]
@fpaupier Did you find the solution?

**Comment by ZuzooVn** [comment]
It works like a champ

```
vectordb = Chroma.from_texts(
        documents,
        embeddings, 
        collection_name="xxxxx", 
        persist_directory="xxxxx", 
        client_settings= Settings(anonymized_telemetry=False, is_persistent=True)
    )
```

**Comment by arwahdevops** [comment]
```
from chromadb.config import Settings

docsearch = Chroma.from_texts(
    texts, 
    embeddings, 
    persist_directory="./chroma_db",
    client_settings=Settings(anonymized_telemetry=False)
)
```
