### ISSUE TITLE
How to use multiple tags in metadata filtering

### ISSUE THREAD

**Issue by javedafroz** [langchain-ai/langchain#7824]
### Issue you'd like to raise.

I am using below chain. I want to use multiple categories in the filters. My logic is to bring the results from category=c1 OR category=c2 OR category=c3. How can we modify below code the achieve the objective

`chain = ConversationalRetrievalChain.from_llm(OpenAI(temperature=0),  retriever= vectorstore.as_retriever(search_kwargs={'filter': {'category':category}}), memory=memory, return_source_documents = True) `

**Comment by samanta-souhardya** [comment]
`qa = ConversationalRetrievalChain.from_llm(AzureChatOpenAI(
            deployment_name="gpt-4", model_name="gpt-4", temperature=0), vectorstore.as_retriever(search_kwargs={'filter': {'file_id': "aef3a936-26db-11ee-b209-44e517a137fd"}}))`
            
Tried this approach but it is going to the whole vectors in vector-db rather than the particular one with the id.

**Comment by chancharikmitra** [comment]
@samanta-souhardya This might be late, but I'll try to answer your question. Langchain uses `Document` objects as its main currency of data. `Document` objects have a `page_content` attribute and `metadata` attribute. Thus, you can manually create a document (as opposed to the methods of creating them from files as discussed in the documentation) by doing:

```
doc = Document(page_content="Some string", metadata={"some_key": "some_val"}
```

For example, for metadata, I usually like to do `metadata = {"source": "name_of_text_file_from_which_content_came"}`. Then, the filter parameter searches through _metadata tags_ not _vector database IDs_, which is what I think you were assuming the filter parameter achieves.

**Comment by pai4451** [comment]
> @samanta-souhardya This might be late, but I'll try to answer your question. Langchain uses `Document` objects as its main currency of data. `Document` objects have a `page_content` attribute and `metadata` attribute. Thus, you can manually create a document (as opposed to the methods of creating them from files as discussed in the documentation) by doing:
> 
> ```
> doc = Document(page_content="Some string", metadata={"some_key": "some_val"}
> ```
> 
> For example, for metadata, I usually like to do `metadata = {"source": "name_of_text_file_from_which_content_came"}`. Then, the filter parameter searches through _metadata tags_ not _vector database IDs_, which is what I think you were assuming the filter parameter achieves.

Hi, @chancharikmitra , Can you elaborate more on how to search filtered by the metadata with the `vectorstore.as_retriever`?

**Comment by chancharikmitra** [comment]
@pai4451 Your code is almost correct. Your filter argument is automatically looking through the `metadata` attribute. So all you would need is:

```
db.as_retriever(
 search_kwargs = {"filter": {"source": "name_of_text_file_from_which_content_came"}}
)
```

Another identical way to do it without creating a separate retriever is as follows:

```
vectordb = FAISS.from_documents(documents=texts, embedding=embeddings)
sim_docs = vectordb.similarity_search(question_text, filter={'source': ['general', 'logistics', 'payroll']}, k=3)
```

I purposefully did an example that returns three relevant documents searching through _multiple_ different tags. You would pass them as a list like above if you wanted the vectordb to look through multiple metadata tags. Note: **This only seems to work for LangcChain's FAISS implementation and not Chroma.**

Hope this answers your question as well as the main question posed in this thread. I discovered this missing feature on Chroma when trying this myself. Use FAISS instead if you want to search using multiple metadata tags and pass them as a list.

**Comment by pai4451** [comment]
@chancharikmitra Thanks for your guidance. I am using Milvus as a vector store and I find that I can pass the `expr` argument to perform a hybrid search (filtered vector search.)
