### ISSUE TITLE
prefix and suffix as PromptTemplates in FewShotPromptTemplate

### ISSUE THREAD

**Issue by g-simmons** [langchain-ai/langchain#783]
Hi there!

I am wondering if it's possible to use PromptTemplates as values for the `prefix` and `suffix` arguments of `FewShotPromptTemplate`. 

Here's an example of what I would like to do. The following works as-is, but I would like it to work the same with the commented lines uncommented. 

I would like this functionality because I have conditional logic for the prefix and suffix that would be more conveniently implemented with a PromptTemplate class rather than relying on f-string formatting. 

```
from langchain import FewShotPromptTemplate, PromptTemplate

prefix = "Prompt prefix {prefix_arg}"
suffix = "Prompt suffix {suffix_arg}"

# prefix = PromptTemplate(template=prefix,input_variables=["prefix_arg"])
# suffix = PromptTemplate(template=suffix,input_variables=["suffix_arg"])

example_formatter = "In: {in}\nOut: {out}\n"

example_template = PromptTemplate(template=example_formatter,input_variables=["in","out"])


template = FewShotPromptTemplate(
    prefix=prefix,
    suffix=suffix,
    example_prompt=example_template,
    examples=[{"in":"example input","out":"example output"}],
    example_separator="\n\n",
    input_variables=["prefix_arg","suffix_arg"],
)

print(template.format(prefix_arg="prefix value",suffix_arg="suffix value"))
```

**Comment by g-simmons** [comment]
I'm new to LangChain, so not sure, but I imagine that this pattern might occur elsewhere... I will probably try to modify FewShotPromptTemplate to support this, and I would be happy to submit a PR if I can get some advice on where else similar changes might be necessary.

**Comment by hwchase17** [comment]
i like this a lot! will try to get this in tmrw!

**Comment by hwchase17** [comment]
i lied about the speed of getting this in :(

will try hard to get it in this weekend, sorry for delay!

i may end up modifying it to be a separate class for modularity

**Comment by g-simmons** [comment]
@hwchase17 no problem :) No rush on my end, I can use my forked version for the time being.

Are you thinking like a mixin for templated suffix and prefix?
