### ISSUE TITLE
BaseRetriever: Latest langchain update is breaking the implementation of extended classes

### ISSUE THREAD

**Issue by brunopistone** [langchain-ai/langchain#7835]
### System Info

MacOS: Ventura 13.4
langchain: 0.0.234

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Extend the class BaseRetriever like the following:

´´´
class DocumentRetrieverExtended(BaseRetriever):
    def __init__(self, retriever, vector_field, text_field, k=3, return_source_documents=False, score_threshold=None, **kwargs):
        self.k = k
        self.vector_field = vector_field
        self.text_field = text_field
        self.return_source_documents = return_source_documents
        self.retriever = retriever
        self.filter = filter
        self.score_threshold = score_threshold
        self.kwargs = kwargs
´´´
2. Provide DocumentRetrieverExtended as retriever object to ConversationalRetrievalChainExtended.from_llm()
3. You will receive the following exception:

```
  File "pydantic/main.py", line 357, in pydantic.main.BaseModel.__setattr__
ValueError: "DocumentRetrieverExtended" object has no field "k"
```

### Expected behavior

Until version 0.0.189 it was working properly. Please consider to fix the bug or update the langchain documentation for providing the new way of implementing it (Honestly I was expecting that new releases should not break what was working previously)

**Comment by thedamnedrhino** [comment]
This is a pydantic issue. Since `DocumentRetrieverExtended` extends `pydantic.BaseModel` you must declare `k` and all other additional properties in the class. i.e.:

```
class DocumentRetrieverExtended(BaseRetriever):
  k: int
  ...
  def __init__(...
```

**Comment by Panoplos** [comment]
Note that you will face this issue if you have a component that uses the newer` BaseRetriever` class but  have not updated your underlying langchain version.

**Comment by thedamnedrhino** [comment]
@Panoplos `k` is not defined in `BaseRetriever` or its parent classes. This is an expected pydantic error. What am I missing?  
-- looking at e2a99bd.

**Comment by visAnu17** [comment]
@Panoplos I am getting the same error. Were you able to resolve this?

**Comment by brrav** [comment]
Any updates on this
