### ISSUE TITLE
InvalidVectorQuery error when using AzureSearch with vector db

### ISSUE THREAD

**Issue by DSgUY** [langchain-ai/langchain#7841]
### System Info

langchain==0.0.234, windows 10, azure-identity==1.13.0, Python 3.11.4

### Who can help?

I manage to create an index in Azure Cognitive Search with _id_, _content_, _vector_content_ and _metadata_ fields.
I check that docs and chunks are not nulls.
I'm getting and error when querying the vector store.

docs: 
[azuresearch-langchain-example](https://python.langchain.com/docs/modules/data_connection/vectorstores/integrations/azuresearch)

Any fix for this?
@hwchase17
@agola11
Regards

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
Embedding is working as I test:

```
# Check that embbding is working
input_text = "This is for demonstration."
outcome = embeddings.embed_query(input_text)

```
When I'm trying to query with:
```
# Perform a similarity search
docs = vector_store.similarity_search(
    query="What did the president say about Ketanji Brown Jackson",
    k=3,
    search_type="similarity",
)
print(docs[0].page_content)
```
Error:

```
HttpResponseError: (InvalidRequestParameter) The 'value' property of the vector query can't be null or an empty array. Make sure to enclose the vector within a "value" property: '{"vector": { "value": [  ] } }'
Parameter name: vector
Code: InvalidRequestParameter
Message: The 'value' property of the vector query can't be null or an empty array. Make sure to enclose the vector within a "value" property: '{"vector": { "value": [  ] } }'
Parameter name: vector
Exception Details:	(InvalidVectorQuery) The 'value' property of the vector query can't be null or an empty array. Make sure to enclose the vector within a "value" property: '{"vector": { "value": [  ] } }'
	Code: InvalidVectorQuery
	Message: The 'value' property of the vector query can't be null or an empty array. Make sure to enclose the vector within a "value" property: '{"vector": { "value": [  ] } }'
```

### Expected behavior

I can't define is is the azure cognitive configuration index that i manually add or a bug in the code. 
Splitting and adding chunks to the vector store (Azure Cognitive Search) all where dont without any warning.

**Comment by DSgUY** [comment]
Well the problem is in the vector parameter in each function that uses the embedding_function. I manage to create a working code using:

from typing import Any
from langchain.vectorstores.azuresearch import AzureSearch
from azure.search.documents.models import Vector
from langchain.docstore.document import Document
import numpy as np
from typing import Any, List, Optional, Tuple


```
class MyAzureSearch(AzureSearch):
    def vector_search_with_score(
        self, query: str, k: int = 4, filters: Optional[str] = None
    ) -> List[Tuple[Document, float]]:
        results = self.client.search(
            search_text=None,
            vector=self.embedding_function(query),
            top_k=k,
            vector_fields=FIELDS_CONTENT_VECTOR,
            select=[f"{FIELDS_ID},{FIELDS_CONTENT},{FIELDS_METADATA}"],
            filter=filters,
        )

        # Convert results to Document objects
        docs = [
            (
                Document(
                    page_content=result[FIELDS_CONTENT],
                    metadata=json.loads(result[FIELDS_METADATA]),
                ),
                float(result["@search.score"]),
            )
            for result in results
        ]

        return docs    
```    

```
vector_store: MyAzureSearch = MyAzureSearch(
    azure_search_endpoint=AZURE_SEARCH_SERVICE_ENDPOINT,
    azure_search_key=AZURE_SEARCH_API_KEY,
    index_name="langchain-vector-demo",
    embedding_function=embeddings.embed_query
)
```

```
# Perform a similarity search
docs = vector_store.similarity_search(
    query="What did the president say about Ketanji Brown Jackson",
    k=3,
    search_type="similarity",
)
```

**Comment by finnless** [comment]
@DSgUY Don't you also need to import the fields for your example fix to work?

```python
from langchain.vectorstores.azuresearch import FIELDS_ID, FIELDS_CONTENT, FIELDS_METADATA, FIELDS_CONTENT_VECTOR
import json
```

**Comment by DSgUY** [comment]
> @DSgUY Don't you also need to import the fields for your example fix to work?
> 
> ```python
> from langchain.vectorstores.azuresearch import FIELDS_ID, FIELDS_CONTENT, FIELDS_METADATA, FIELDS_CONTENT_VECTOR
> import json
> ```

yes, sorry. I was using:
```
FIELDS_ID = os.getenv('FIELDS_ID')
FIELDS_CONTENT = os.getenv('FIELDS_CONTENT')
FIELDS_CONTENT_VECTOR = os.getenv('FIELDS_CONTENT_VECTOR')
FIELDS_METADATA = os.getenv('FIELDS_METADATA')
```

but that seems better. Thanks!

**Comment by JasonIsaac** [comment]
> Well the problem is in the vector parameter in each function that uses the embedding_function. I manage to create a working code using:
> 
> ```
> from typing import Any
> from langchain.vectorstores.azuresearch import AzureSearch
> from azure.search.documents.models import Vector
> from langchain.docstore.document import Document
> import numpy as np
> from typing import Any, List, Optional, Tuple
> ```
> 
> ```
> class MyAzureSearch(AzureSearch):
>     def vector_search_with_score(
>         self, query: str, k: int = 4, filters: Optional[str] = None
>     ) -> List[Tuple[Document, float]]:
>         results = self.client.search(
>             search_text=None,
>             vector=self.embedding_function(query),
>             top_k=k,
>             vector_fields=FIELDS_CONTENT_VECTOR,
>             select=[f"{FIELDS_ID},{FIELDS_CONTENT},{FIELDS_METADATA}"],
>             filter=filters,
>         )
> 
>         # Convert results to Document objects
>         docs = [
>             (
>                 Document(
>                     page_content=result[FIELDS_CONTENT],
>                     metadata=json.loads(result[FIELDS_METADATA]),
>                 ),
>                 float(result["@search.score"]),
>             )
>             for result in results
>         ]
> 
>         return docs    
> ```
> 
> ```
> vector_store: MyAzureSearch = MyAzureSearch(
>     azure_search_endpoint=AZURE_SEARCH_SERVICE_ENDPOINT,
>     azure_search_key=AZURE_SEARCH_API_KEY,
>     index_name="langchain-vector-demo",
>     embedding_function=embeddings.embed_query
> )
> ```
> 
> ```
> # Perform a similarity search
> docs = vector_store.similarity_search(
>     query="What did the president say about Ketanji Brown Jackson",
>     k=3,
>     search_type="similarity",
> )
> ```

Hi @DSgUY,  Thanks for this solution. This works when the search type is ``` similarity``` but for ```hybrid```  it is not working. Please let me know if something needs to be added to the implementation.
