### ISSUE TITLE
Error while creating WeaviateHybridSearchRetriever instance

### ISSUE THREAD

**Issue by ashutosh-suryawanshi** [langchain-ai/langchain#7851]
### System Info

LangChain version: 0.0.232
Python version: 3.10.8
Platform: Windows 11, VS Code

For following usage of WeaviateHybridSearchRetriever - 
`w_url = os.environ["WEAVIATE_URL"]`
    `api_key_w= weaviate.AuthApiKey(api_key=os.environ["WEAVIATE_API_KEY"])`
    `wclient = weaviate.Client(url=w_url,
                              auth_client_secret=api_key_w,
                              additional_headers={
                                    "X-Openai-Api-Key": os.getenv("OPENAI_API_KEY"),
                               },)`
   `retriever = WeaviateHybridSearchRetriever(wclient, index_name="testindex", text_key="text")`

Getting following error for the line of retriever instance creation - 
`
TypeError: Serializable.__init__() takes 1 positional argument but 2 were given
`
### Who can help?

@hwchase17
@agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Follow the steps given in the official documentation - https://python.langchain.com/docs/modules/data_connection/retrievers/integrations/weaviate-hybrid

### Expected behavior

Retriever should be able to initiate correctly and should able to return queried documents.

**Comment by thedamnedrhino** [comment]
Can you include the full stack trace

**Comment by scottdshan** [comment]
You need to change:

retriever = WeaviateHybridSearchRetriever(wclient, index_name="testindex", text_key="text") to 
retriever = WeaviateHybridSearchRetriever(client=wclient, index_name="testindex", text_key="text")

0.225 changed the way the class was instantiated. 

https://github.com/langchain-ai/langchain/pull/7074/files/451dcdb89ca4fc1a4e263c0b28e025752057b6d4
