### ISSUE TITLE
OperationalError with docsearch

### ISSUE THREAD

**Issue by rena9155** [langchain-ai/langchain#7872]
### System Info

Running on Colab.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import GoogleDriveLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.text_splitter import CharacterTextSplitter
from langchain import OpenAI
from langchain.document_loaders import PyPDFDirectoryLoader
from langchain.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA

os.environ["OPENAI_API_KEY"] = 'Your API Key'

loader = GoogleDriveLoader(
    folder_id="Your folder ID",
    recursive=True,
)

docs = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=100, chunk_overlap=0)
split_docs = text_splitter.split_documents(docs)

embeddings = OpenAIEmbeddings()
docsearch = Chroma.from_documents(split_docs, embeddings)

### Expected behavior

Expect to load embedding into Chroma, then create a QA object upon that. The code was able to run without a problem yesterday but encountered an error today

**Comment by wolfassi123** [comment]
Is it the OperationalError: no such tokenizer: trigram error??

**Comment by rena9155** [comment]
@wolfassi123 Yes

**Comment by wolfassi123** [comment]
> @wolfassi123 Yes

For now it seems to be an issue with the latest ChromaDB update. I switched to FAISS and code works smoothly. Waiting for them to apply the fix hopefully.
Just instead of importing Chroma from langchain.vectorstore, import FAISS and proceed.

**Comment by devstein** [comment]
Related issue https://github.com/chroma-core/chroma/issues/836

**Comment by atroyn** [comment]
Fix is here: https://github.com/chroma-core/chroma/pull/841

We'll cut a new release shortly

**Comment by HammadB** [comment]
Hi folks, we've landed https://github.com/chroma-core/chroma/pull/841 and shipped 0.4.1 which reverts using the trigram tokenizer. While this will degrade search quality, we think preserving the colab experience as working is critical and will add an optional path to using more sophisticated tokenizers in the future.
