### ISSUE TITLE
Encryption Key support

### ISSUE THREAD

**Issue by iatpatelishan** [langchain-ai/langchain#7886]
### Feature request

When entering the embed text in the database like pgvector, I would like to encrypt the raw text with KMS Key or any such encryption and use raw text for generating embedding

### Motivation

Security

### Your contribution

N/A

**Comment by rangelrey** [comment]
+1 Nowadays, saving data without any type of encrpyton is a no-go for many type of projects. This feature should be a must.

**Comment by rooom13** [comment]
I'm interested in this feature as well, due data security policies it is important that in case of a database dump the documents content is encrypted.

If anybody guides me a bit on implementation details I can give it a go
