### ISSUE TITLE
Async calls for HuggingFaceHub

### ISSUE THREAD

**Issue by cserpell** [langchain-ai/langchain#7902]
### Feature request

It would be nice if HuggingFaceHub models could be called in async mode (concurrently), as currently supported by Anthropic and OpenAI models.

### Motivation

I wanted to compare performance of some models in a bunch of tasks. I was comparing Anthropic and OpenAI models, and when I tried using a HuggingFaceHub model, I noticed this functionality is not implemented.

### Your contribution

I would like to know if someone is already taking on this. I could try to replicate code from other APIs to do it, but I am not sure I would be able to get to a level that is high enough to submit to LangChain.

**Comment by cserpell** [comment]
I understand that the current HuggingFace Hub's `AsyncInferenceClient` [here](https://github.com/huggingface/huggingface_hub/blob/4f1e4bbb28b58ffbc2588d2c549c6be0d083bac8/src/huggingface_hub/inference/_generated/_async_client.py#L81) may be used

**Comment by hinthornw** [comment]
This would be a great addition

**Comment by mayankagarwals** [comment]
@cserpell I can see the issue, will pick it up
