### ISSUE TITLE
Bedrock Embeddings: Add support for endpoint_url

### ISSUE THREAD

**Issue by erezzarum** [langchain-ai/langchain#7925]
### System Info

Bedrock Embeddings doesn't have support for modifying the endpoint_url, the LLMs one have.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Not able to provide a custom endpoint_url

### Expected behavior

Able to provide a custom endpoint_url

**Comment by dwaiba** [comment]
#7927
