### ISSUE TITLE
 llm can only use OpenAI?

### ISSUE THREAD

**Issue by andyzhou1982** [langchain-ai/langchain#7926]
### Issue you'd like to raise.

when I use langchain.agents,the parameter llm can only use OpenAI or other large language model ?

**Comment by aligajani** [comment]
It would be nice to have a unified interface that offers a fallback to a secondary model, say OpenAI as primary and then others if OpenAI is down. I am not sure if someone has found an elegant way to do this.

**Comment by smridhi-seth** [comment]
I think reliableGPT by Ishaan does this @aligajani
