### ISSUE TITLE
ImportError: cannot import name 'ChatMessage' from 'vertexai.language_models' (/usr/local/lib/python3.10/dist-packages/vertexai/language_models/__init__.py)

### ISSUE THREAD

**Issue by amirsartipi13** [langchain-ai/langchain#7932]
### System Info

I run my code in google colab. [this is link to code.](https://colab.research.google.com/drive/1vqTz68WVT7qCGpDSahROztCUphmXy9xI?usp=sharing)

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
! pip install google-cloud-aiplatform==1.26 langchain==0.0.232
! pip uninstall shapely
! pip install shapely<2.0.0


import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = ''


from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
    AIMessagePromptTemplate
)
from langchain.schema import HumanMessage, SystemMessage
from langchain.chat_models import ChatVertexAI



prompt = f"""Give me a jok!"""

system_template = (
    "Act as an conversationl chat bot"
)

human_template = "{prompt}"

system_message_prompt = SystemMessagePromptTemplate.from_template(system_template)
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)

chat_prompt = ChatPromptTemplate.from_messages(
    [system_message_prompt, human_message_prompt]
)
messages = chat_prompt.format_prompt(prompt=prompt).to_messages()


model = ChatVertexAI(model_name="chat-bison@001")

response = model(messages)
```

### Expected behavior

It should get response, but I face this err.

```
/usr/local/lib/python3.10/dist-packages/langchain/chat_models/vertexai.py in _parse_chat_history(history)
     46         first place.
     47     """
---> 48     from vertexai.language_models import ChatMessage
     49 
     50     vertex_messages, context = [], None

ImportError: cannot import name 'ChatMessage' from 'vertexai.language_models' (/usr/local/lib/python3.10/dist-packages/vertexai/language_models/__init__.py)

```
I think it should read from _vertexai._language_models_ instead.

**Comment by lkuligin** [comment]
Please, try to upgrade the version of google-cloud-aiplatform library to `1.28.0` (or better `1.28.1`). I added a better error description.
