### ISSUE TITLE
Serpapi API key not working with Langchain 

### ISSUE THREAD

**Issue by SpyderRex** [langchain-ai/langchain#7971]
### Issue you'd like to raise.

I have a valid serpapi API key that I can use in the serpapi playground and with direct calls using python requests, but when I use it with Langchain I get an error saying that the key is invalid. I have my key set as environment variable, but I continue to get this error:

ValueError: Got error from SerpAPI: Invalid API key. Your API key should be here: https://serpapi.com/manage-api-key

I have even got a new API key with the same results. I have tried Pydroid3 for Android, Ubuntu in Termux for Android (64 bit), and Ubuntu in AWS ec2, with the same result.

**Comment by SpyderRex** [comment]
My Langchain version is 0.0.237. Here is the entire error output:

Entering new AgentExecutor chain...
 I need to find out who Leo DiCaprio's girlfriend is and then calculate her
age raised to the 0.43 power.
Action: Search
Action Input: "Leo DiCaprio girlfriend"Traceback (most recent call last):
  File "/root/Chain/chain.py", line 20, in <module>
    agent.run("Who is Leo DiCaprio's girlfriend? What is her current age
raised to the 0.43 power?")
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py",
line 440, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py",
line 243, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py",
line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/usr/local/lib/python3.10/dist-packages/langchain/agents/agent.py",
line 1010, in _call
    next_step_output = self._take_next_step(
  File "/usr/local/lib/python3.10/dist-packages/langchain/agents/agent.py",
line 871, in _take_next_step
    observation = tool.run(
  File "/usr/local/lib/python3.10/dist-packages/langchain/tools/base.py",
line 320, in run
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/tools/base.py",
line 292, in run
    self._run(*tool_args, run_manager=run_manager, **tool_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain/tools/base.py",
line 450, in _run
    else self.func(*args, **kwargs)
  File
"/usr/local/lib/python3.10/dist-packages/langchain/utilities/serpapi.py",
line 85, in run
    return self._process_response(self.results(query))
  File
"/usr/local/lib/python3.10/dist-packages/langchain/utilities/serpapi.py",
line 131, in _process_response
    raise ValueError(f"Got error from SerpAPI: {res['error']}")
ValueError: Got error from SerpAPI: Invalid API key. Your API key should be
here: https://serpapi.com/manage-api-key

**Comment by SpyderRex** [comment]
Ok, I feel like a dummy. I actually signed up for an API called "SerpWow"
instead of "Serpapi", and I was using that API key 😂🤦. I just signed up
for the real Serpapi, and everything is now working correctly. Thank you
for your help, and this issue can be considered closes.

**Comment by peterhchen** [comment]
import os
import sys
# You need to create your own key.
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')
print('GOOGLE_API_KEY:', GOOGLE_API_KEY)
# HuggingFace API Key for LMMChain
HUGGINGFACEHUB_API_KEY = os.getenv('HUGGINGFACEHUB_API_KEY')
print('HUGGINGFACEHUB_API_KEY:', HUGGINGFACEHUB_API_KEY)
# Google Search Platform
GOOGLE_SERP_API_KEY = os.getenv('GOOGLE_SERP_API_KEY')
print('GOOGLE_SERP_API_KEY:', GOOGLE_SERP_API_KEY)

# In jupyter Notebook
!pip install google-search-results   # Google Search
!pip install numexpr                 # LLM Math

from langchain.agents import AgentType, initialize_agent, load_tools
#from langchain.llms import OpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

#llm = OpenAI(temperature=0)
llm=ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=GOOGLE_API_KEY)

# The tools we'll give the Agent access to. Note that the 'llm-math' tool uses an LLM, so we need to pass that in.
#tools = load_tools(["serpapi", "llm-math"], llm=llm)
from langchain.utilities.google_serper import GoogleSerperAPIWrapper

#google_serper = GoogleSerperAPIWrapper(serper_api_key="your_actual_serpapi_key_here")
google_serper = GoogleSerperAPIWrapper(serper_api_key=GOOGLE_SERP_API_KEY)
#tools = load_tools(["serpapi", "llm-math"], llm=llm)
tools = load_tools(["serpapi", "llm-math"], llm=llm, serpapi_api_key = GOOGLE_SERP_API_KEY )

# Finally, let's initialize an agent with the tools, the language model, and the type of agent we want to use.
agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True)

# Let's test it out!
agent.run("What was the GDP of US in 2022 plus 5?")

## below is the answer from Gimini, LangChain, Serp (require key). LLM-math (use HuggingFace Key).
> Entering new AgentExecutor chain...
Action: Search
Action Input: What was the GDP of US in 2022
Observation: ["The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles' Hollywood is famed for filmmaking. ― Google", 'United States type: Country in North America.', 'United States entity_type: countries, locations, travel, competitions, military, travel.', 'United States kgmid: /m/09c7w0.', 'Current-dollar GDP increased 9.2 percent, or $2.15 trillion, in 2022 to a level of $25.46 trillion, compared with an increase of 10.7 percent, ...', 'Real gross domestic product (GDP) increased at an annual rate of 1.6 percent in the first quarter of 2024, according to the “advance” estimate.', 'U.S. annual GDP 1990-2023 ... In 2023, the U.S. GDP increased from the previous year to about 27.36 trillion U.S. dollars. This increase in GDP ...', 'The Gross Domestic Product (GDP) in the United States was worth 25439.70 billion US dollars in 2022, according to official data from the World Bank.', 'GDP in United States grows 0.4% ; 2022, €72,440, $76,343, 23.9%, 10.3% ; 2021, €58,492, $69,227, 5.8%, 9.8%.', 'Real GDP (constant, inflation adjusted) of the United States of America reached $18,924,600,000,000 in 2022. GDP Growth Rate in 2022 was 2.06%, representing a ...', 'U.S. gdp for 2022 was $25,439.70B, a 9.11% increase from 2021. U.S. gdp for 2021 was $23,315.08B, a 10.71% increase from 2020. U.S. gdp for 2020 was ...', 'GDP Growth Rate in the United States is expected to be 1.50 percent by the end of this quarter, according to Trading Economics global macro models and analysts ...', 'Measured from the fourth quarter of 2022 to the fourth quarter of 2023, real GDP increased 3.1 percent during the period compared with an ...', 'US gross domestic product (GDP) increased 1.9% in 2022 and another 2.5% in 2023. Year-over-year inflation — the rate at which consumer prices increase — was 3.1 ...']
Thought:Action: Calculator
Action Input: 25.46 + 5
Observation: Answer: 30.46
Thought:Final Answer: 30.46

> Finished chain.
'30.46'
