### ISSUE TITLE
Issue: How to pass in database name parameter into Milvus

### ISSUE THREAD

**Issue by ashczq** [langchain-ai/langchain#7979]
### Issue you'd like to raise.

![image](https://github.com/hwchase17/langchain/assets/49942750/e6cf4a3a-da28-4133-9f3e-9b9998d0adb2)

In Milvus, we are able to create databases and create collections within the database itself. Hence i will be able to create a collection with the same name in different databases. How can we specify the specific database and collection to use, currently the parameters only accept collection_name and not db_name like in pymilvus.

**Comment by vboy1010** [comment]
Meet same issue

**Comment by genzerstech** [comment]
we have this issue as well

**Comment by forgethub** [comment]
i have this issue too

**Comment by dotbalo** [comment]
I also encountered the same problem, langchain always links to the default database. Any solution?

**Comment by YCG09** [comment]
+1

**Comment by wheatfox** [comment]
set "db_name" in "connection_args".
```
object = Milvus(
    connection_args = {
        "db_name": "your db name"
    }
```

**Comment by ohbeep** [comment]
Tested in v0.1.0, the solution of @wheatfox works.

**Comment by hmosousa** [comment]
@ohbeep  Should this be added to [this section](https://github.com/langchain-ai/langchain/blob/021b0484a8d9e8cf0c84bc164fb904202b9e4736/libs/community/langchain_community/vectorstores/milvus.py#L66) the documentation? I can create a pull requests.

**Comment by ohbeep** [comment]
> @ohbeep Should this be added to [this section](https://github.com/langchain-ai/langchain/blob/021b0484a8d9e8cf0c84bc164fb904202b9e4736/libs/community/langchain_community/vectorstores/milvus.py#L66) the documentation? I can create a pull requests.

I don't think so. This `db_name` parameter should be a key of the `connection_args` field.

**Comment by 50ajmalkhan** [comment]
drop_old is very expensive operation that you are using while building connection, It delete existing data in collection before making new collection

**Comment by share1001** [comment]
connection_args需要添加参数 alias
langchain 0.1.15 milvus.py _create_connection_alias()方法
```
        # If a valid address was given, then check if a connection exists
        if given_address is not None:
            for con in connections.list_connections():
                addr = connections.get_connection_addr(con[0])
                if (
                    con[1]
                    and ("address" in addr)
                    and (addr["address"] == given_address)
                    and ("user" in addr)
                    and (addr["user"] == tmp_user)
                ):
                    logger.debug("Using previous connection: %s", con[0])
                    return con[0]

        # Generate a new connection if one doesn't exist
        alias = uuid4().hex
```
con[0]没做空校验的，如果传入了alias参数，就应该在连接时指定alias，这里完全没去做校验，完全没法指定数据库，我如果部署了一套环境 ，使用数据库来区分环境，这个没法做到，希望官方后面版本修复这个问题

**Comment by UltimateLaForsch** [comment]
This should definitely by added:
Using MilvusClient from pymilvus, you can connect like this:
`class MilvusClient(
    uri: str = "http://localhost:19530",
    user: str = "",
    password: str = "",
    db_name: str = "",
    token: str = "",
    timeout: float | None = None,
    **kwargs: Any
)`
Here obviously, db_name is a parameter which one can use (and we did that already). Furthermore confirmed by the Attu-GUI, where we can see e.g. several databases, not just the default one...

**Comment by singhteekam01** [comment]
> ### Issue you'd like to raise.
> ![image](https://private-user-images.githubusercontent.com/49942750/254779766-e6cf4a3a-da28-4133-9f3e-9b9998d0adb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDUzNjIsIm5iZiI6MTcyMjg0NTA2MiwicGF0aCI6Ii80OTk0Mjc1MC8yNTQ3Nzk3NjYtZTZjZjRhM2EtZGEyOC00MTMzLTlmM2UtOWI5OTk4ZDBhZGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA4MDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTA1MDU5NmQ0MGM2OTc3MTE4MjY3M2U4OTUwYTQxZDg3MDYwNmRlZGJjOTg3MzhiN2I0NWJjMzJhYzZhNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syXV_WlkyPyOvZSCgkg47QSbP-lzTpG-tv66wqjWE30)
> 
> In Milvus, we are able to create databases and create collections within the database itself. Hence i will be able to create a collection with the same name in different databases. How can we specify the specific database and collection to use, currently the parameters only accept collection_name and not db_name like in pymilvus.
> 
> ### Suggestion:
> _No response_

LangChain doesn't support this feature directly, but you can achieve it using the following approach:

# Import
from pymilvus import connections, db, utility
from langchain.vectorstores import Milvus

# Connect to Milvus
CONNECTION_URI = "http://localhost:19530"
connections.connect(uri=CONNECTION_URI)

# Define database name
db_name = "my_db"

# Check if the database exists, and create it if it does not
db_list = db.list_database()
if db_name not in db_list:
    db.create_database(db_name)


# Example usage with Milvus
vector_db = Milvus.from_documents(
    documents=text_chunks,
    embedding=embeddings,
    connection_args={
        "uri": CONNECTION_URI,
        "db_name": db_name
    }
)

**Comment by dedumas** [comment]
I can't believe specifying a database is not an option. This should definitely be an open / planned issue. Unfortunately, Haystack suffers from the same omission.
