### ISSUE TITLE
Redis does not use the parameters passed in by Redis.as_retriever()

### ISSUE THREAD

**Issue by gsparsh220598** [langchain-ai/langchain#7986]
### System Info

langchain==0.0.237
python==3.8.16

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

same issue as https://github.com/hwchase17/langchain/issues/6984 but for Redis, but the proposed fix does not work

llm = OpenAI(temperature=0.1)
question_generator = LLMChain(llm=llm, prompt=CONDENSE_QUESTION_PROMPT)
doc_chain = load_qa_with_sources_chain(llm, chain_type="stuff")
retriever = db.as_retriever(search_kwargs={"k": 10})

chain = ConversationalRetrievalChain(
    retriever=retriever, #redis retriever
    question_generator=question_generator,
    combine_docs_chain=doc_chain,
    return_source_documents=True,
)

### Expected behavior

query = "who slayed Karna in the battle?"
result = chain({"question": query})

print(len(result['source_documents'])) #ouput: 4 but should be 10

**Comment by Spartee** [comment]
@gsparsh220598 While the api will be a little different, this should be fixed in the latest releases by using the ``search_kwargs`` dictionary such as in these examples: https://python.langchain.com/docs/integrations/vectorstores/redis#redis-as-retriever

If this works then I think this can be closed @baskaryan
