### ISSUE TITLE
Does it support 文心一言？

### ISSUE THREAD

**Issue by vilenice** [langchain-ai/langchain#7990]

**Comment by LegendLeo** [comment]
> _Answer generated by a 🤖_
> 
> ## Answer
> I'm sorry, but I couldn't find any information about "文心一言" in relation to LangChain. Could you please provide more details about what "文心一言" is and how you would like to use it with LangChain? This will help me better understand your question and assist you further.
> 
> This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

“文心一言“ is a LLM service just like OpenAI, provided by Baidu, this is the API document:
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/jlil56u11

Our Chinese developers eagerly hope that langchain can follow up as soon as possible

**Comment by flyspirit99** [comment]
> > _Answer generated by a 🤖_
> > ## Answer
> > I'm sorry, but I couldn't find any information about "文心一言" in relation to LangChain. Could you please provide more details about what "文心一言" is and how you would like to use it with LangChain? This will help me better understand your question and assist you further.
> > This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> > Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> “文心一言“ is a LLM service just like OpenAI, provided by Baidu, this is the API document: https://cloud.baidu.com/doc/WENXINWORKSHOP/s/jlil56u11
> 
> Our Chinese developers eagerly hope that langchain can follow up as soon as possible

How about we add ERNIE Bot into langchain ourselves?

**Comment by axiangcoding** [comment]
i need this feature too. There is a roadmap or eta?

**Comment by flyspirit99** [comment]
Currently I'm playing around ERNIE bot API while getting familiar with Langchain source code. Will start the integration when I have more confidence.

**Comment by axiangcoding** [comment]
I will submit a PR for this, integration ERNIE for quick usage.
Should be done this weekend.

**Comment by axiangcoding** [comment]
> I will submit a PR for this, integration ERNIE for quick usage. Should be done this weekend.

sadly my trial account is expired...it will take more time than i think....

**Comment by axiangcoding** [comment]
Hi everyone there. I already submit a PR to main branch, this ErnieBot should be avaliable at the next update!
try
```
from langchain.chat_models import ErnieBotChat
from langchain.schema import AIMessage, HumanMessage, SystemMessage
chat = ErnieBotChat(ernie_client_id='YOUR_CLIENT_ID', ernie_client_secret='YOUR_CLIENT_SECRET')
chat([
    HumanMessage(content='你好')
])
```

**Comment by axiangcoding** [comment]
Hi everyone there. I also support ERNIE Embeddings-V1 for more wide usage cases, if anything wrong, please submit a PR to fix or tell me, i'm happy to help!

see #9370 for merge details and [docs](https://python.langchain.com/docs/integrations/text_embedding/ernie) for usage

**Comment by axiangcoding** [comment]
@vilenice can we close this issue now?

**Comment by siuheart** [comment]
When will streaming be supported?

**Comment by xzy103** [comment]
Currently, only the chat model is supported (not LLM)?

**Comment by axiangcoding** [comment]
> When will streaming be supported?

sorry, but no plan for this now

**Comment by axiangcoding** [comment]
> Currently, only the chat model is supported (not LLM)?

yes, only chat model is supported.
