### ISSUE TITLE
ChatLangChain requesting _default_relevance_score_fn' on <module 'langchain.vectorstores.faiss> on init

### ISSUE THREAD

**Issue by inaim** [langchain-ai/langchain#7992]
### System Info

Langchain 0.0.237.
Python 3.11
Mac OS X M1

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

make start. 
INFO:     Uvicorn running on http://127.0.0.1:9002 (Press CTRL+C to quit)
INFO:     Started reloader process [80851] using StatReload
INFO:     Started server process [80855]
INFO:     Waiting for application startup.
in startup_event
AttributeError: Can't get attribute '_default_relevance_score_fn'

### Expected behavior

Load the chat.
Note: the faiss wrapper seems updated back in May to from _default_relevance_score_fn to relevance_score_fn

**Comment by ragzman** [comment]
same here.

**Comment by waylon-paypay** [comment]
same here

**Comment by jammastergirish** [comment]
I'm having the same issue with `langchain==0.0.243`

```
AttributeError: Can't get attribute '_default_relevance_score_fn' on <module 'langchain.vectorstores.faiss' from '.../env/lib/python3.11/site-packages/langchain/vectorstores/faiss.py'>`

**Comment by 13682673486** [comment]
same here

**Comment by r-fumachi** [comment]
I was loading an old .pkl so I fixed this by deleting it and creating again         

```
VectorStore = FAISS.from_texts(text_chunks, embedding=HuggingFaceEmbeddings())
        with open(f"{file}.pkl", "wb") as f:
            pickle.dump(VectorStore, f)
```
