### ISSUE TITLE
Can't connect to Qdrant since 0.0.234

### ISSUE THREAD

**Issue by motestw64631** [langchain-ai/langchain#7995]
### System Info

python 3.9 
langchain 0.0.234
qdrant-client   1.1.7

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`client = qdrant_client.QdrantClient(self.qdrant_url, port=6333)`
`qdrant = Qdrant(
            client=client, collection_name=self.collection_name, 
            embeddings=embeddings,
        )`

### Expected behavior

I'm getting this error since i upgrade my langchain to 0.0.234 from 0.0.233
<AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Failed to connect to remote host: Connection refused"
	debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:6334: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-07-20T18:17:20.830536+08:00"}"

I didn't change any code in my project.
Is there any setting change?
it seems that it connect to 6334 port of Qdrant

**Comment by beratcmn** [comment]
I'm experiencing the same problem. Have you solve it?

**Comment by motestw64631** [comment]
no, i just downgrade langchain to 0.0.233 now.

**Comment by Austinito** [comment]
I think this [answer](https://github.com/orgs/qdrant/discussions/2195#discussioncomment-6350164) here will solve your issue.

Qdrant has a REST (HTTP) and gRPC server. The web console uses REST on 6333, but the Python client uses gRPC on 6334.

**Comment by jay05thakareee** [comment]
> I think this [answer](https://github.com/orgs/qdrant/discussions/2195#discussioncomment-6350164) here will solve your issue.
> 
> Qdrant has a REST (HTTP) and gRPC server. The web console uses REST on 6333, but the Python client uses gRPC on 6334.

This helped me

I removed the current qdrant docker image

Pulled the latest image using
`docker pull qdrant/qdrant `

Then rebuild container using
 ` docker run -p 6333:6333 -p 6334:6334 \
    -v $(pwd)/qdrant_storage:/qdrant/storage \
    qdrant/qdrant `
