### ISSUE TITLE
I don't have access to the short-term memory using Agent with gpt-3.5-turbo

### ISSUE THREAD

**Issue by ericbellet** [langchain-ai/langchain#7996]
### System Info

langchain==0.0.230
MacOS

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I do not know how exactly to reproduce this, but I would like to know if someone had the same error using GPT-3.5-turbo with this agent, tool, and prompts:

Agent: LLMSingleActionAgent
Tool and prompt:

```
        template_hello = """You are a chatbot, answer to this
        {input}

        Previous conversation history:
        {history}
        """

        prompt_hello = PromptTemplate(input_variables=["input", "history"], template=template_hello)

        hello_chain = LLMChain(
            llm=ChatOpenAI(model='gpt-3.5-turbo',
            prompt=prompt_hello,
            verbose=True,
            memory=self.memory
        )
```
Memory:
```
from langchain.memory import ConversationTokenBufferMemory
self.memory = ConversationTokenBufferMemory(llm=ChatOpenAI(temperature=0, 
                                                                   max_tokens=500, 
                                                                   model='gpt-3.5-turbo'), 
                                                    memory_key="history",
                                                    max_token_limit=500)
```
When I run the agent with gpt-4 it can access to the memory, if I change the agent model to gtp-3.5-turbo I have this error: 

> I don't have access to the short-term memory

### Expected behavior

Answer based on the memory

**Comment by thedamnedrhino** [comment]
Please include the full relevant code and stack trace.  
What is `self` referring to above? etc.
