### ISSUE TITLE
APIfy dataset loader does not provide the attribute "page_content" in the loaded documents

### ISSUE THREAD

**Issue by TKanyere** [langchain-ai/langchain#7999]
### System Info

Langchain Version== 0.0.237
Platform == Google Colaboratory

### Who can help?

@eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Step 1: Import packages

Step 2: Use APIfy dataset loader

loader = ApifyDatasetLoader(
    dataset_id="KCoOphOr1tQmmUhsS",
    dataset_mapping_function=lambda item: Document(
        page_content=item["description"] or "name", metadata={"id": item["id"]}
    ),
)

Step 3: Attempt to create a vector store index

from langchain.indexes import VectorstoreIndexCreator

index = VectorstoreIndexCreator().from_loaders([loader])

### Expected behavior

It should create the index from the data loader provided, but the loader does not produce the attribute "page content" when loading APIfy datasets.

<img width="919" alt="Screenshot 2023-07-19 at 12 24 02" src="https://github.com/hwchase17/langchain/assets/63857960/11aee742-c513-4cc6-863e-56c5e10a43db">

**Comment by thedamnedrhino** [comment]
Did dosu's solution help? can you include the full stack trace?

**Comment by TKanyere** [comment]
It was not helpful. 

Here's a link to the notebook (with API keys redacted)

<img width="742" alt="Screenshot 2023-07-21 at 10 31 31" src="https://github.com/hwchase17/langchain/assets/63857960/a9d6da5e-7f7e-408e-ae85-973985526517">

**Comment by thedamnedrhino** [comment]
The `page_content` error is expected. The langchain loader expects `langchain.docstore.document.Document. You're giving it `llama_index.readers.schema.base.Document`.

**Comment by thedamnedrhino** [comment]
The `page_content` error is expected. The loader expects `langchain.docstore.document.Document`s. You're giving it `llama_index` Documents.
