### ISSUE TITLE
Difference between  ConversationBufferMemory and chat_history parameter

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#8002]
### Issue you'd like to raise.

I came to know that there are two methods to keep memory in **ConversationalRetrievalChain**

1. Method -1
Using **ConversationBufferMemory**
```
from langchain.chains import ConversationalRetrievalChain
from langchain.memory import ConversationBufferMemory
memory = ConversationBufferMemory(
    memory_key="chat_history",
    return_messages=True
)

qa= ConversationalRetrievalChain.from_llm(
    llm,
    retriever=retriever),
    memory=memory
)
```

3. Method -2
Using **chat_history** parameter
```
from langchain.chains import ConversationalRetrievalChain
qa= ConversationalRetrievalChain.from_llm(
    llm,
    retriever=retriever)
)
chat_history = []
result = qa({"question": question, "chat_history": chat_history})

```

What is the exact difference between the above two methods?  When should use one over another and why?

**Comment by DSgUY** [comment]
Do you get any insight of this?

**Comment by pradeepdev-1995** [comment]
Not yet

**Comment by smartge3k** [comment]
I think with the ConversationBufferMemory you cannot distinguish between different users. You will have to create some sort of user session management in the backend to keep track. However, chat_history, give you freedom to simply collect the chat history from your frontend and attach to the request.

**Comment by mishra011** [comment]
ConversationBufferMemory is good for Demo/Dev application using streamlit. But for Production usecase the chat_history parameter is better and give you more control on the session history.
