### ISSUE TITLE
Issue: Using "llama-2-70b-chat/ggml-model-q4_0.bin" with LlamaCpp()

### ISSUE THREAD

**Issue by jain-t** [langchain-ai/langchain#8004]
### Issue you'd like to raise.

Hi Everyone, 

I am trying to use `llama-2-70b-chat` with the LlamaCpp() as described here : https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp#metal

My system specs are
MacBook Pro, M1 Chip, 16GB, 500GB SSD

Here is my code using LlamaCpp:

```
DEFAULT_CHAT_MODEL_LLAMA = '/Volumes/Gargantua/LLAA2/llama-2-70b-chat/ggml-model-q4_0.bin'
class HelpprBaseLLAMAV2(LlamaCpp):
    
    model_path = DEFAULT_CHAT_MODEL_LLAMA
    callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
    verbose = True
    input = {"temperature": 0.75, "top_p": 1, "max_length": 2048}
    n_gpu_layers = 1
    n_batch = 512
    f16_kv = True
```

Whenever I call `llm = HelpprBaseLLAMAV2()`  via the following: 

```
(venv) tapanjain@MacBook-Pro-2 helppr % python main.py
```

I get the following error: 

```
zsh: illegal hardware instruction  python main.py
```

Can anyone help me what exactly is the reason here? Is langchain right now not supported for llama 2?

**Comment by thedamnedrhino** [comment]
Did you try dosu-beta's solution?

**Comment by jain-t** [comment]
Hi, yes still in the process.

**Comment by jain-t** [comment]
Hi, its still not working :(.

**Comment by devstein** [comment]
Potentially related gist: https://gist.github.com/cedrickchee/e8d4cb0c4b1df6cc47ce8b18457ebde0?permalink_comment_id=4601905#gistcomment-4601905

**Comment by jain-t** [comment]
So, I reliased that 70b will need 38GB RAM (which my macbook is devoid off ~ 16gb) hence I shifted to 7b-chat model. when I run using what @devstein  mentioned (i.e via ./main cmd ) it works well but invoking via langchain is still same issue.

**Comment by SecretiveShell** [comment]
llama 70B uses a different attention mechanism to the 7/13B models

**Comment by jain-t** [comment]
But then what’s the solution? Also even for 7B model I’m getting illegal
hardware instructions.

**Comment by 1b5d** [comment]
I wrote a lib [llm-api](https://github.com/1b5d/llm-api) that you can use to run Llama 2 (or other models) then integrate with langchain using this lib [langchain-llm-api](https://github.com/1b5d/langchain-llm-api)

**Comment by Hanzofm** [comment]
Is possible nowadays to load the Llama 70B on a Macbook pro?

**Comment by QROST** [comment]
M1 Max 64GB ram runs 70b with **Llama.cpp directly** (no langchain) without issue. However, langchain always crashes the kernel when using 70b model, even with `n_gqa =8`.
