### ISSUE TITLE
What is the difference between OpenAI Function and OpenAI Multi Functions Agent

### ISSUE THREAD

**Issue by keenborder786** [langchain-ai/langchain#8011]
### Issue you'd like to raise.

I was looking up the documentation as well. However, from the documentation it seems as if both types of agents are doing the same thing. Even when I looked at the backend code, both agent codes seemed almost identical. I am not so sure what I am missing in terms of my understanding. Any leads would be appreciated. 

### Suggestion:

Documentation between the two types can be made more clear.

**Comment by bgonzalezfractal** [comment]
I was just looking at this myself a couple minutes ago so I can help you out, if you notice the code in the Multi Functions Agent:
![image](https://github.com/hwchase17/langchain/assets/56733173/b12dc350-3ca9-4ec9-9151-1ec73b957394)
It states: 
```
# OpenAI functions returns a single tool invocation
            # Here we force the single tool invocation it returns to
            # itself be a list of tool invocations. We do this by constructing
            # a new tool that has one argument which is a list of tools
            # to use.
```
Meaning that in the case if Multi Function Agent you can actually execute 2 functions in just one iterations, the OpenAI Functions Agent can only execute one of those functions at the same time.
Cheers.

**Comment by keenborder786** [comment]
That makes sense, thank you. Will keep the issue open so that documentation gets improved. If you have time can you create a PR in which you improve the Docs file explaining the difference between the two?

**Comment by ari62** [comment]
Please improve the documentation concerning this issue
