### ISSUE TITLE
Streaming support for Oobabooga API?

### ISSUE THREAD

**Issue by gameveloster** [langchain-ai/langchain#8028]
### Feature request

Update `TextGen` to include `streaming` support for Oobabooga.

### Motivation

Oobabooga provides a streaming API that will be very helpful. [TextGen](https://github.com/hwchase17/langchain/pull/5997) already supports the regular API.

### Your contribution

:)

**Comment by shengkaixuan** [comment]
@lonestriker  please add the streaming feature

**Comment by tnsai** [comment]
Any timescale for this? :)

**Comment by lonestriker** [comment]
Been on vacation and finishing up a move. I didn't add streaming support initially because it was non-trivial (the blocking, non-streaming support was dead simple.) When I get some free time from my day job and family, I'll have a look again.
