### ISSUE TITLE
Verbose setting not recognised in serialised vectorDBQA chain

### ISSUE THREAD

**Issue by seanaedmiston** [langchain-ai/langchain#803]
Using serialised version of vectorDBQA, setting verbose =True results in the 'starting chain/ending chain' messages being printed but not the actual content. I think I have traced it to this line... at this point 'verbose' is True, but inside the combine_docs function verbose becomes False. Having traced it this far I am not confident of how to fix... hopefully someone can help

https://github.com/hwchase17/langchain/blob/ae1b589f60a8835d5df255984bcb9223ef8cd3ed/langchain/chains/vector_db_qa/base.py#L135

**Comment by hwchase17** [comment]
when you say "serialized version", are you pulling from the hub? if so, which exact url?

**Comment by seanaedmiston** [comment]
Yes - pulling from hub: 
lc://chains/vector-db-qa/stuff/chain.json

https://github.com/hwchase17/langchain-hub/blob/master/chains/vector-db-qa/stuff/chain.json

**Comment by hwchase17** [comment]
okay so i hadnt actually designed the loading function to allow for overriding of serialized parameters (its serialized as `false`)

so, treating this as a feature request, i guess the request would be for it allow for overriding of verbose flag?

**Comment by seanaedmiston** [comment]
Maybe just a note in the docs or something. Not really that important. It was just that the behaviour was a bit 'surprising' (i.e. when I tried overriding I got the Starting chain... Ending chain... messages so that made me think that that overriding was ok.) For me personally I am now using tracing in a lot of scenarios where I was using verbose

**Comment by seanaedmiston** [comment]
Just looking at my code again, not being able to override verbose is not really a big deal, but I have been overriding `k` and `search_kwargs`. I haven't had any issues - so I assume that is ok. Overriding these values is definitely useful, to dynamically tweak the vector search. So if anything gets changed - would like to see overriding of these values (continue to be) supported.

**Comment by hwchase17** [comment]
makes total sense. im not sure how easy this will be, especially for nested elements, but will keep it open to track it. maybe only worth doing for the chain at the top level?
