### ISSUE TITLE
can it be possible to take input in custom tool 

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#8039]
### Issue you'd like to raise.

Hello everyone, 
I am trying to make a mcq tool but that tools need input for that particular question everytime what that quiz tool is called. Any approach which i can try

**Comment by risingsunomi** [comment]
Try using the interaction tool https://github.com/hwchase17/langchain/blob/master/langchain/tools/interaction/tool.py

**Comment by Ajaypawar02** [comment]
Can you let me know approach to connect this Human tool to websocket. I went through the Human tool it uses input() method to take input. But what if i need to take input from the client after the service is deployed .
