### ISSUE TITLE
  Langchain support Alibaba Cloud's Tongyi Qianwen model?

### ISSUE THREAD

**Issue by syhleo** [langchain-ai/langchain#8054]
### Feature request

How does Alibaba Cloud's Tongyi Qianwen Big Model combine with Langchain?
langchain如何与阿里云的通义千问大模型结合起来

### Motivation

 Alibaba Cloud's Tongyi Qianwen

### Your contribution

none

**Comment by charlescui** [comment]
llm = Tongyi(dashscope_api_key=DASHSCOPE_API_KEY)

this code is not correct, the api_key didnot pass to DashScope instance in langchain.

I got this error

```bash
    raise AuthenticationError(
dashscope.common.error.AuthenticationError: No api key provided. You can set by dashscope.api_key = your_api_key in code, or you can set it via environment variable DASHSCOPE_API_KEY= your_api_key. You can store your api key to a file, and use dashscope.api_key_file_path=api_key_file_path in code, or you can set api key file path via environment variable DASHSCOPE_API_KEY_FILE_PATH, You can call save_api_key to api_key_file_path or default path(~/.dashscope/api_key).
```

**Comment by wangxuqi** [comment]
> 

if you use llm = Tongyi(dashscope_api_key=DASHSCOPE_API_KEY). you should use DASHSCOPE_API_KEY = getpass().
or just  `export DASHSCOPE_API_KEY=xxxx`

**Comment by charlescui** [comment]
![image](https://github.com/langchain-ai/langchain/assets/875374/ea3fe101-a5c9-4b57-aa82-994adb1e71a5)
@wangxuqi let api_key in Tongyi() parameters

**Comment by wangxuqi** [comment]
> ![image](https://user-images.githubusercontent.com/875374/255883092-ea3fe101-a5c9-4b57-aa82-994adb1e71a5.png) @wangxuqi let api_key in Tongyi() parameters

The answer from the robot is not right. Please use `llm = Tongyi()`

**Comment by tcfly** [comment]
@wangxuqi  How to access qwen-plus-v1 model,for now I am using llm = Tongyi(model_name="qwen-v1")

**Comment by tcfly** [comment]
@wangxuqi  only qwen-v1 model supported
![image](https://github.com/langchain-ai/langchain/assets/49434080/01f62fc2-0d20-43e9-a230-772587bb38c7)

**Comment by wangxuqi** [comment]
> You need to apply for the access of  'qwen-plus-v1' model. And the code should also works for 'qwen-v1' model.

**Comment by doudou-itachi** [comment]
When I was using TongYi, I found an err `Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied.. ,File "C:\Users\Administrator\Envs\test\lib\site-packages\langchain\llms\tongyi.py", line 53, in _generate_with_retry
    raise HTTPError(
requests.exceptions.HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied.`
 Why is it reporting 403?I omitted some err in the middle,And when I write like this, I found that the program will block at this position`DASHSCOPE_API_KEY = getpass()`.when i write like this`os.environ["DASHSCOPE_API_KEY"] = "sk-3acb65072xxxxx` err is 403

**Comment by doudou-itachi** [comment]
> 当我使用同义时，我发现了一个错误，为什么它报告403？我在中间省略了一些错误，当我这样写的时候，我发现程序会在这个位置阻塞，当我这样写的时候，err是403`Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 code: AccessDenied message: Access denied.. Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 code: AccessDenied message: Access denied.. Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 code: AccessDenied message: Access denied.. ,File "C:\Users\Administrator\Envs\test\lib\site-packages\langchain\llms\tongyi.py", line 53, in _generate_with_retry raise HTTPError( requests.exceptions.HTTPError: HTTP error occurred: status_code: 403 code: AccessDenied message: Access denied.``DASHSCOPE_API_KEY = getpass()``os.environ["DASHSCOPE_API_KEY"] = "sk-3acb65072xxxxx`

CODE:`import os
    from langchain.llms import Tongyi
    from langchain import PromptTemplate, LLMChain


    # DASHSCOPE_API_KEY = getpass()

    os.environ["DASHSCOPE_API_KEY"] = "sk-3acb6x66bxxxx4d309fdb07xxxxxxx"

    llm = Tongyi()

    template = """Question: {question}

    Answer: Let's think step by step."""

    prompt = PromptTemplate(template=template, input_variables=["question"])
    llm_chain = LLMChain(prompt=prompt, llm=llm)
    question = "What NFL team won the Super Bowl in the year Justin Beiber was born?"

    llm_chain.run(question)`

GET ERR:`Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied..
Retrying langchain.llms.tongyi.generate_with_retry.<locals>._generate_with_retry in 4.0 seconds as it raised HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied.....
 File "C:\Users\x\Exxvs\xx\lixxxxb\site-packages\langchain\llms\tongyi.py", line 53, in _generate_with_retry
    raise HTTPError(
requests.exceptions.HTTPError: HTTP error occurred: status_code: 403 
 code: AccessDenied 
 message: Access denied.`

**Comment by CodingJzy** [comment]
本地部署的千问是否支持？

**Comment by lunalulu** [comment]
> 本地部署的千问是否支持？

@CodingJzy 请问你跑通了吗？

**Comment by wangxuqi** [comment]
> 本地部署的千问是否支持？

这个版本只支持使用dashscope 并不支持本地部署的版本

**Comment by wangxuqi** [comment]
> 3acb65072xxxxx
没有权限。模型的使用权限需要单独申请

**Comment by lunalulu** [comment]
我使用langchain-chatchat跑通了
