### ISSUE TITLE
DOC: Unable to Pass HuggingFace Access Token via Huggingface TextGen Inference for large language model hosted in HuggingFace Inference Endpoint in protected mode.

### ISSUE THREAD

**Issue by thapaliya123** [langchain-ai/langchain#8060]
### Issue with current documentation:

**Documentation Link:** https://python.langchain.com/docs/modules/model_io/models/llms/integrations/huggingface_textgen_inference

**Comment by Suv4o** [comment]
I am facing the same issue here. I cannot figure out if the how to add an access token. It looks like we can only use with public endpoints

**Comment by Eilliar** [comment]
Any way to pass a token? Even though my `HUGGING_FACE_HUB_TOKEN `env var is setup, I keep getting  `A valid user token is required`.

🤔

**Comment by seyedsaeidmasoumzadeh** [comment]
I have the same issue

**Comment by d4nielmeyer** [comment]
Have the same issue. 

As an alternative I came across using _HuggingFaceEndpoint_ -> https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/huggingface_endpoint.py

This works for me since you can pass your key. The issue, however, is that I couldn't figure out yet, how to specify model parameters, e.g. such as `max_new_tokens` etc. 

Just using the standard parameters is not an option either ...

**Comment by janpawellek** [comment]
A workaround is to set the authorization header in your own code.

Assume `llm` is your instance of `HuggingFaceTextGenInference`, then you can do in your code:

```Python
token = os.environ.get("TEXT_GENERATION_INFERENCE_TOKEN", None)
llm.client.headers = {"Authorization": f"Bearer {token}"}
```

If you have the `HuggingFaceTextGenInference` inside an agent or chain, a somewhat hacky solution is to:

```Python
set_text_generation_inference_token(chain)
```

When you define:

```Python
def find_instances(obj, cls):
    """Find all instances of a class in an object."""
    instances = []
    if isinstance(obj, cls):
        instances.append(obj)
    if isinstance(obj, list):
        for item in obj:
            instances.extend(find_instances(item, cls))
    elif hasattr(obj, "__dict__"):
        for prop in vars(obj).values():
            instances.extend(find_instances(prop, cls))
    return instances


def set_text_generation_inference_token(chain: Chain):
    """Set the token for all HuggingFaceTextGenInference instances in the chain."""
    token = os.environ.get("TEXT_GENERATION_INFERENCE_TOKEN", None)
    if not token:
        return
    all_huggingface_instances = find_instances(chain, HuggingFaceTextGenInference)
    for instance in all_huggingface_instances:
        instance.client.headers = {"Authorization": f"Bearer {token}"}
```

**Comment by jflournoy** [comment]
Try

```python
os.environ["HUGGING_FACE_HUB_TOKEN"] = "...token..."
```

via https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables
