### ISSUE TITLE
Bug: Chroma().add_texts() return empty ids list when metadata is not None

### ISSUE THREAD

**Issue by macul99** [langchain-ai/langchain#8061]
### System Info

LangChain version: '0.0.238'

### Who can help?

SemanticSimilarityExampleSelector().add_example() raise "IndexError" exception due to empty list ids returned from Chroma().add_texts() when metadata is not None.

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.prompts.example_selector.semantic_similarity import SemanticSimilarityExampleSelector
from langchain.vectorstores import Chroma
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

examples_dict = [{'a':'b'}]
embedding_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
example_selector = SemanticSimilarityExampleSelector.from_examples(
                                # This is the list of examples available to select from.
                                examples_dict,
                                # This is the embedding class used to produce embeddings which are used to measure semantic similarity.
                                embedding_function,
                                # This is the VectorStore class that is used to store the embeddings and do a similarity search over.
                                Chroma,  # type: ignore
                                # This is the number of examples to produce and include per prompt
                                k=min(3, len(examples_dict)),
                            )

example_selector.add_example(examples_dict[0])

### Expected behavior

ids returned from Chroma().add_texts() should be a list of ids of texts are added

**Comment by denggaoshan** [comment]
I think this issue was introduced here: #7643
@baskaryan

**Comment by Bearnardd** [comment]
It seems like a duplicate of https://github.com/hwchase17/langchain/issues/7865. I am fixing it :)

**Comment by macul99** [comment]
Will close this issue since it is duplicated. Thx!
