### ISSUE TITLE
unable to implement memory with sql agent toolkit

### ISSUE THREAD

**Issue by amani-acog** [langchain-ai/langchain#8069]
### System Info

I am using langchain 0.0.238, I want to use ConversationBufferMemory with sql-agent-toolkit. Please support in this regard.
I changed prompt :
# flake8: noqa

SQL_PREFIX = """You are an agent designed to interact with a SQL database.
Given an input question, create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer.
Unless the user specifies a specific number of examples they wish to obtain, else fetch all results then fetch all results donot use 'LIMIT'.
When you are using 'WHERE' clause to fetch specific data, you have to apply 'WHERE' clause in several ways like exact matchusing '=' or substring match using 'LIKE'. 
You can order the results by a relevant column to return the most interesting examples in the database.
Never query for all the columns from a specific table, only ask for the relevant columns given the question. If you did notfind the column asked by the user, then return "data for the specified column doesnot exists." as the answer.
You have access to tools for interacting with the database.
Only use the below tools. Only use the information returned by the below tools to construct your final answer.
You MUST double check your query before executing it. If you get an error while executing a query, rewrite the query and try again.

DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.

If the question does not seem related to the database, just return "I don't know" as the answer.

This reminds you of your past memory and events:{chat_history}

Know that only the "Question" ("HumanMessage") and "Final answer" ("AIMessage") to each previous question are available inthe past memory section above.
Hence, always include enough detail in the Final answer so that you can answer subsequent questions.
If you believe any of the data computed to answer a question is likely to be useful in answering a possible follow-on question.

"""

SQL_SUFFIX = """Begin!

Question: {input}
Thought: I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables.
{agent_scratchpad}"""

SQL_FUNCTIONS_SUFFIX = """I should look at the tables in the database to see what I can query.  Then I should query the schema of the most relevant tables."""

And changed base.py:
"""SQL agent."""
from typing import Any, Dict, List, Optional

from langchain.agents.agent import AgentExecutor, BaseSingleActionAgent
#from sql_agent_toolkits.sql.prompt import ( SQL_FUNCTIONS_SUFFIX,SQL_PREFIX,SQL_SUFFIX,)
from langchain.agents.agent_toolkits.sql.prompt import (
    SQL_FUNCTIONS_SUFFIX,
    SQL_PREFIX,
    SQL_SUFFIX,
)
from langchain.agents.agent_toolkits.sql.toolkit import SQLDatabaseToolkit
from langchain.agents.agent_types import AgentType
from langchain.agents.mrkl.base import ZeroShotAgent
from langchain.agents.mrkl.prompt import FORMAT_INSTRUCTIONS
from langchain.agents.openai_functions_agent.base import OpenAIFunctionsAgent
from langchain.callbacks.base import BaseCallbackManager
from langchain.chains.llm import LLMChain
from langchain.prompts.chat import (
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessagesPlaceholder,
)
from langchain.schema.language_model import BaseLanguageModel
from langchain.schema.messages import AIMessage, SystemMessage
from langchain.memory import ConversationBufferMemory

global memory
memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)

def create_sql_agent(
    llm: BaseLanguageModel,
    toolkit: SQLDatabaseToolkit,
    agent_type: AgentType = AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    callback_manager: Optional[BaseCallbackManager] = None,
    prefix: str = SQL_PREFIX,
    suffix: Optional[str] = SQL_SUFFIX,
    format_instructions: str = FORMAT_INSTRUCTIONS,
    input_variables: Optional[List[str]] = None,
    top_k: int = 10,
    max_iterations: Optional[int] = 15,
    max_execution_time: Optional[float] = None,
    early_stopping_method: str = "force",
    verbose: bool = False,
    agent_executor_kwargs: Optional[Dict[str, Any]] = None,
    **kwargs: Dict[str, Any],
) -> AgentExecutor:
    """Construct an SQL agent from an LLM and tools."""
    tools = toolkit.get_tools()
    #prefix = prefix.format(dialect=toolkit.dialect, top_k=top_k)
    #print("prefix", prefix)
    if input_variables is None:
        input_variables = ["dialect", "input", "agent_scratchpad"]
    agent: BaseSingleActionAgent
    print("input_variables", input_variables)
    if agent_type == AgentType.ZERO_SHOT_REACT_DESCRIPTION:
        prompt = ZeroShotAgent.create_prompt(
            tools,
            prefix=prefix,
            suffix=suffix or SQL_SUFFIX,
            format_instructions=format_instructions,
            input_variables=input_variables,
        )
        llm_chain = LLMChain(
            llm=llm,
            prompt=prompt,
            callback_manager=callback_manager,
        )
        tool_names = [tool.name for tool in tools]
        agent = ZeroShotAgent(llm_chain=llm_chain, allowed_tools=tool_names, **kwargs)
#         memory = ConversationBufferMemory(memory_key="chat_history")
    elif agent_type == AgentType.OPENAI_FUNCTIONS:
        messages = [
            SystemMessage(content=prefix),
            HumanMessagePromptTemplate.from_template("{input}"),
            AIMessage(content=suffix or SQL_FUNCTIONS_SUFFIX),
            MessagesPlaceholder(variable_name="agent_scratchpad"),
        ]
        input_variables = ["input", "agent_scratchpad"]
        _prompt = ChatPromptTemplate(input_variables=input_variables, messages=messages)

        agent = OpenAIFunctionsAgent(
            llm=llm,
            prompt=_prompt,
            tools=tools,
            callback_manager=callback_manager,
            **kwargs,
        )
    else:
        raise ValueError(f"Agent type {agent_type} not supported at the moment.")

    return AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        callback_manager=callback_manager,
        verbose=verbose,
        max_iterations=max_iterations,
        max_execution_time=max_execution_time,
        early_stopping_method=early_stopping_method,
        memory=memory,
        **(agent_executor_kwargs or {}),
    )

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I have changed Prompt.py and base.py to provide chat_history as input but I am running into errors from create_prompt method using ZeroShotAgent or from LLMChain(expecting inputs in dictionary)
Error:

input_variables ['dialect', 'input', 'agent_scratchpad']
input_variables from /opt/miniconda/lib/python3.10/site-packages/langchain/agents/mrkl/ ['dialect', 'input', 'agent_scratchpad']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 2
      1 from tools.db_llm_with_memory import *
----> 2 db_llm_with_memory("which all enzymes have urate as substrate")

File ~/notebooks/atossa-usecase/atossa_usecase/tools/db_llm_with_memory.py:42, in db_llm_with_memory(query)
     35     agent = create_sql_agent(
     36         llm=ChatOpenAI(temperature=0),
     37         toolkit=toolkit,
     38         verbose=True,
     39         agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,memory=memory
     40     )
     41 #     agent_chain = AgentExecutor.from_agent_and_tools(agent=agent, tools=toolkit, verbose=True, memory=memory)
---> 42     agent.run(query)

File /opt/miniconda/lib/python3.10/site-packages/langchain/chains/base.py:440, in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    438     if len(args) != 1:
    439         raise ValueError("`run` supports only one positional argument.")
--> 440     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    441         _output_key
    442     ]
    444 if kwargs and not args:
    445     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    446         _output_key
    447     ]

File /opt/miniconda/lib/python3.10/site-packages/langchain/chains/base.py:220, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    185 def __call__(
    186     self,
    187     inputs: Union[Dict[str, Any], Any],
   (...)
    193     include_run_info: bool = False,
    194 ) -> Dict[str, Any]:
    195     """Execute the chain.
    196 
    197     Args:
   (...)
    218             `Chain.output_keys`.
    219     """
--> 220     inputs = self.prep_inputs(inputs)
    221     callback_manager = CallbackManager.configure(
    222         callbacks,
    223         self.callbacks,
   (...)
    228         self.metadata,
    229     )
    230     new_arg_supported = inspect.signature(self._call).parameters.get("run_manager")

File /opt/miniconda/lib/python3.10/site-packages/langchain/chains/base.py:364, in Chain.prep_inputs(self, inputs)
    362         _input_keys = _input_keys.difference(self.memory.memory_variables)
    363     if len(_input_keys) != 1:
--> 364         raise ValueError(
    365             f"A single string input was passed in, but this chain expects "
    366             f"multiple inputs ({_input_keys}). When a chain expects "
    367             f"multiple inputs, please call it by passing in a dictionary, "
    368             "eg `chain({'foo': 1, 'bar': 2})`"
    369         )
    370     inputs = {list(_input_keys)[0]: inputs}
    371 if self.memory is not None:

ValueError: A single string input was passed in, but this chain expects multiple inputs ({'dialect', 'input'}). When a chain expects multiple inputs, please call it by passing in a dictionary, eg `chain({'foo': 1, 'bar': 2})`

### Expected behavior

Please provide some simple addon behaviour to use memory with sql agent

**Comment by amani-acog** [comment]
Hi...
Thank you for quick response. I fixed the issue in create_sql_agent and
doing agent.run as you specified. I changed input variables in
agents/mrkl/base.py, but still getting the error as:

input_variables None
input_variables from
/opt/miniconda/lib/python3.10/site-packages/langchain/agents/mrkl/
None
input_variables from
/opt/miniconda/lib/python3.10/site-packages/langchain/agents/mrkl/
['dialect', 'chat_history', 'input', 'agent_scratchpad']

---------------------------------------------------------------------------ValidationError
                          Traceback (most recent call last)
Cell In[1], line 2      1 from tools.db_llm_with_memory import *---->
2 db_llm_with_memory("which all enzymes have urate as substrate")

File ~/notebooks/atossa-usecase/atossa_usecase/tools/db_llm_with_memory.py:39,
in db_llm_with_memory(query)     21 #     tools = toolkit.get_tools()
   22 # #     print(tools)     23        (...)     35 #
input_variables=["input", "chat_history", "agent_scratchpad"],     36
#     )     37     memory =
ConversationBufferMemory(memory_key="chat_history",
return_messages=True)---> 39     agent = create_sql_agent(     40
   llm=ChatOpenAI(temperature=0),     41         toolkit=toolkit,
42         verbose=True,     43
agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,memory=memory     44
   )     45     agent.run({"dialect":
"sqlite:////home/jupyter/notebooks/atosa_testdb.db", "input":
"your_input_query"})

File ~/notebooks/atossa-usecase/atossa_usecase/sql_agent_toolkits/sql/base.py:59,
in create_sql_agent(llm, toolkit, agent_type, callback_manager,
prefix, suffix, format_instructions, input_variables, top_k,
max_iterations, max_execution_time, early_stopping_method, verbose,
memory, agent_executor_kwargs, **kwargs)     57
print("input_variables", input_variables)     58 if agent_type ==
AgentType.ZERO_SHOT_REACT_DESCRIPTION:---> 59     prompt =
ZeroShotAgent.create_prompt(     60         tools,     61
prefix=prefix,     62         suffix=suffix or SQL_SUFFIX,     63
   format_instructions=format_instructions,     64
input_variables=input_variables,     65     )     66     llm_chain =
LLMChain(     67         llm=llm,     68         prompt=prompt,     69
        callback_manager=callback_manager,     70     )     71
tool_names = [tool.name for tool in tools]

File /opt/miniconda/lib/python3.10/site-packages/langchain/agents/mrkl/base.py:88,
in ZeroShotAgent.create_prompt(cls, tools, prefix, suffix,
format_instructions, input_variables)     86     input_variables =
["dialect","chat_history","input", "agent_scratchpad"]     87
print("input_variables from
/opt/miniconda/lib/python3.10/site-packages/langchain/agents/mrkl/",
input_variables)---> 88 return PromptTemplate(template=template,
input_variables=input_variables)

File /opt/miniconda/lib/python3.10/site-packages/langchain/load/serializable.py:74,
in Serializable.__init__(self, **kwargs)     73 def __init__(self,
**kwargs: Any) -> None:---> 74     super().__init__(**kwargs)     75
  self._lc_kwargs = kwargs

File /opt/miniconda/lib/python3.10/site-packages/pydantic/main.py:341,
in pydantic.main.BaseModel.__init__()
ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid prompt schema; check for mismatched or missing input
parameters. {'chat_history'} (type=value_error)

Can you please help in this regard

**Comment by amani-acog** [comment]
Hey,
I am using the following code for using memory with sql_agent, so I created
custom agent with sql_toolkit and custom prompt. But it is not using
chat_history in follow up questions. How can I make sure whether
chat_history is appended in the end of every agent.run("query").
def db_llm_with_memory_zeroshot(query: str):

    db =
SQLDatabase.from_uri("sqlite:////home/jupyter/notebooks/atosa_testdb.db")

    toolkit = SQLDatabaseToolkit(db=db,
llm=ChatOpenAI(model='gpt-3.5-turbo',temperature=0))

    tools = toolkit.get_tools()
    print(tools)

    tool_names = [tool.name for tool in tools]
    print("tool_names:", tool_names)

    prefix = """Have a conversation with a human, answering the following
questions as best you can. You have access to the following tools:
    You are an agent designed to interact with a SQL database.
    Given an input question, create a syntactically correct {dialect} query
to run, then look at the results of the query and return the answer. You
should be able to use appropriate columns of sql tables based on user query
as user may not specify the same column in his query.
    You should look at the tables in the database to see what I can query.
Then you should query the schema of the most relevant tables.
    Unless the user specifies a specific number of examples they wish to
obtain, else fetch all results donot use 'LIMIT'.
    When you are using 'WHERE' clause to fetch specific data, you have to
apply 'WHERE' clause in several ways like exact matchusing '=' or substring
match using 'LIKE'.
    You can order the results by a relevant column to return the most
interesting examples in the database.
    Never query for all the columns from a specific table, only ask for the
relevant columns given the question. If you did notfind the column asked by
the user, then return "data for the specified column doesnot exists." as
the answer.
    You have access to tools for interacting with the database.
    Only use the below tools. Only use the information returned by the
below tools to construct your final answer.
    You MUST double check your query before executing it. If you get an
error while executing a query, rewrite the query and try again.

    DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to
the database.

    If the question does not seem related to the database, just return "I
don't know" as the answer.
    This reminds you of your past memory and events:{chat_history}.And also
print the {chat_history}

    Know that only the "Question" ("HumanMessage") and "Final answer"
("AIMessage") to each previous question are available inthe past memory
section above.
    Hence, always include enough detail in the Final answer so that you can
answer subsequent questions.
    If you believe any of the data computed to answer a question is likely
to be useful in answering a possible follow-on question.
"""
    suffix = """Begin!"

    {chat_history}
    Question: {input}
    {agent_scratchpad}"""

    FORMAT_INSTRUCTIONS = """Use the following format:

    Question: the input question you must answer
    Thought: you should always think about what to do
    Action: the action to take, should be one of [{tool_names}]
    Action Input: the input to the action
    Observation: the result of the action
    ... (this Thought/Action/Action Input/Observation can repeat N times)
    Thought: I now know the final answer
    Final Answer: the final answer to the original input question"""

    prompt = ZeroShotAgent.create_prompt(
        tools,
        prefix=prefix,
        suffix=suffix,
        format_instructions=FORMAT_INSTRUCTIONS,
        input_variables=["dialect","input", "chat_history",
"agent_scratchpad"],
    )
    print(prefix)
    memory =
ConversationBufferMemory(memory_key="chat_history",output_key='output')
    llm_chain =
LLMChain(llm=ChatOpenAI(model='gpt-3.5-turbo',temperature=0), prompt=prompt)
    agent = ZeroShotAgent(llm_chain=llm_chain, allowed_tools=tool_names)

    agent_executor = AgentExecutor.from_agent_and_tools(agent=agent,
tools=tools,

verbose=True,handle_parsing_errors=True,memory=memory,max_iterations= 25)
#     agent_executor.run(query)
    agent_executor.run({"dialect":
"sqlite:////home/jupyter/notebooks/atosa_testdb.db", "input": query})

And I also changed utils.py in memory module as:
from typing import Any, Dict, List

from langchain.schema.messages import get_buffer_string  # noqa: 401


def get_prompt_input_key(inputs: Dict[str, Any], memory_variables:
List[str]) -> str:
   ...
    prompt_input_keys = list(set(inputs).difference(memory_variables +
["stop"]))
    if len(prompt_input_keys) != 1:
        #raise ValueError(f"One input key expected got {prompt_input_keys}")
        if "input" in prompt_input_keys:
            return 'input'
    return prompt_input_keys[0]

Please let me know how to check whether it is using chat_history. If not
how to include. Awaiting your response

**Comment by keenborder786** [comment]
I have already worked on this feature: PR #7546. Please see the PR, it is still in review.
