### ISSUE TITLE
Calling the OpenAI Functions agent with an empty tool list crashes

### ISSUE THREAD

**Issue by Markus-sevend** [langchain-ai/langchain#8080]
### System Info

langchain version 0.0.238
openai version 0.27.8

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Set up your Open AI keys in your .env file then run this python script:

```py
from dotenv import load_dotenv

from langchain.agents import initialize_agent, AgentType
from langchain.chat_models import ChatOpenAI

load_dotenv()

llm = ChatOpenAI(model_name="gpt-3.5-turbo")

agent = initialize_agent(
    tools=[],
    llm=llm,
    agent=AgentType.OPENAI_FUNCTIONS
)

agent.run("Hello World!")
```

### Expected behavior

The agent should be run successfully and just not be able to use any tools if none are provided. This does happen if the functions parameter is not passed to the openai interface when its empty. So should be an easy fix:
1. Detect if the tools list is empty
2. Only pass the function parameter to the openai interface if its not empty

The interface call in question (`langchain/chat_models/openai.py` in line 319):
```py
        @retry_decorator
        def _completion_with_retry(**kwargs: Any) -> Any:
            return self.client.create(**kwargs) # <-- HERE, just filter out key functions if empty
```

**Comment by willxie** [comment]
Also looking for support for this. Sometimes I want to test the same code with and without functions and compare results without changing the API.
