### ISSUE TITLE
OpenSearchVectorStore's similarity search functions can't handle k>10 with script_scoring

### ISSUE THREAD

**Issue by Karin-Basis** [langchain-ai/langchain#8081]
### System Info

Langchain version 0.0.225
M1 Mac
Python 3.11.3

### Who can help?

@naveentatikonda 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import OpenSearchVectorSearch
from opensearchpy import RequestsHttpConnection
from requests_aws4auth import AWS4Auth
import os

aws_auth = AWS4Auth(
    os.environ["AWS_ACCESS_KEY"], 
    os.environ["AWS_SECRET_KEY"],
    "us-east-1",
    "es"
)
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/distiluse-base-multilingual-cased-v2",
    model_kwargs={'device': 'cpu'}
)
opensearch_vector_search = OpenSearchVectorSearch(
    os.environ["OPENSEARCH_URL"],
    "testindex",
    embeddings,
    http_auth=aws_auth,
    connection_class=RequestsHttpConnection,
)
texts = []
for i in range(1, 41):
    texts.append(f"This is document {i}")
opensearch_vector_search.add_texts(texts)

query = "This is a document"
search_result = opensearch_vector_search._raw_similarity_search_with_score(
    query,
    k=30,
    metadata_field="*",
    search_type="script_scoring"
)
print("Number of docs in response: ", len(search_result))
```
Output:
```
Number of docs in response:  10
```

When using script_scoring, the code does not pass a "size=k" option to the client query, so it returns a maximum of 10 hits by default.  Therefore, the user cannot receive more than 10 results regardless of the value of k.  I believe all that is necessary it to add a `size=k` parameter to line 537 in `opensearch_vector_search.py`, and then the `[:k]` in line 539 is superfluous.

### Expected behavior

The above code should produce 30 results, not 10.

**Comment by aerickson-clt** [comment]
I just reproduced this with AWS OpenSearch as well.  My index has 41 documents, I request 30, and only get 10.

All texts are the same in my index.

```
results = docsearch.similarity_search("What's the best way to enjoy butter?", k=30, search_type="script_scoring",metadata_field="*")
print(len(results))
```

I'm looking into this now.  I think the bot's suggestion doesn't hurt but I'm not sure it will fix this.

**Comment by aerickson-clt** [comment]
Ok, so the bot's suggestion should work

```
def _raw_similarity_search_with_score(
        self, query: str, k: int = 4, **kwargs: Any
    ) -> List[dict]:
        # ... existing code ...
        elif search_type == SCRIPT_SCORING_SEARCH:
            # ... existing code ...
            search_query["size"] = k  # Add this line
        # ... existing code ...
        return [hit for hit in response["hits"]["hits"][:k]]
```

Likely the reason why you encounter this is that OpenSearch's default `k` is 10, so it needs to be specified.  The `[:k]` doesn't hurt and may need to remain for other search methods.

Here's a similar question about its cousin ElasticSearch
https://discuss.elastic.co/t/elasticsearch-returns-only-10-records-but-the-hit-is-507/136605

Here's my own test putting "size": 30 into the query and you can see the number of results is about 46800/1536 (dividing by the vector's dimension) is 30.4...

I'll open a PR in a sec.

**Comment by Karin-Basis** [comment]
Thanks @aerickson-clt.  Looking at the code it seems like the "painless_scripting" option might have the same problem, but I haven't tested it.

**Comment by aerickson-clt** [comment]
Yes, I fixed that too.
