### ISSUE TITLE
YoutubeLoader to load documents from transcripts as chunks

### ISSUE THREAD

**Issue by beaterblank** [langchain-ai/langchain#8087]
### Feature request

Currently, The YoutubeLoader class loads transcripts and converts all of them into a single large piece of text loosing all the information regarding when it was said in the video to be able to reference it later.
I understand we cannot have very small/ unpridictable lengths of transcripts, which is why it would be great to chunk them according to a input duration by user and retain some information regarding when its said. which get the best of both worlds by having large enough data and also retaining context

### Motivation

I was trying to make a vedio qa retriever, Then I noticed how the transcripts were being loaded, I have also noticed this issue with other transcript loaders such as VTT, then I had to make my custom function to load the transcripts in chunks of duration that made sense to me, which lead me to making this issue

### Your contribution

I already have the code for chunking the transcripts, would love to submit a PR.

**Comment by dcieslak19973** [comment]
Adding the timestamp (and/or URL to that timestamp) in the `source` metadata would be fantastic

**Comment by beaterblank** [comment]
yea that should be possible 

url to a timestamp is generally  videoId followed by t=seconds
https://youtu.be/dQw4w9WgXcQ?t=80
