### ISSUE TITLE
DOC: Link broken for Python Guide on Prompts Page

### ISSUE THREAD

**Issue by siddesai80** [langchain-ai/langchain#8105]
### Issue with current documentation:

The hyperlink which should navigate to the Python guide for Prompts seems to be broken.

Affected link -> https://docs.langchain.com/docs/components/prompts/

Click on the `Python Guide` link under the `info` section. It leads to `Page Not Found`.

![image](https://github.com/hwchase17/langchain/assets/50095990/6a008b08-60a1-4736-b45d-ee37f38e1664)

**Comment by Gordon-BP** [comment]
Looks like those pages got moved to https://python.langchain.com/docs/modules/model_io/

**Comment by Bharat123rox** [comment]
This issue is probably fixed by #8408 and can be closed.

**Comment by siddesai80** [comment]
@Bharat123rox Thanks. Closing the issue.
