### ISSUE TITLE
call directly the prompt of GPT4All Model

### ISSUE THREAD

**Issue by Mabenan** [langchain-ai/langchain#8125]
### System Info

Langchain 0.0.238
System: WSL - Ubuntu

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use the ConversationBufferMemory and Prompt Templates.

if you have the template
```python
"""
Human: Ask question
Assistant:
"""
```

The prompt passed to GPT4AllModel is again templated by gpt4all.py to avoid which results in the following prompt which is passed to the model

```python
"""
### Human Human: Ask question
Assistant:
### Assistant:
"""
```
This leads to incorrect answers where models are trying to talk to them self as human and assistant

if we directly call GPT4AllModel.model.prompt_model_streaming we are giving the prompt the user indented.

### Expected behavior

That the prompt Template is used that the user/developer gives the Chain

**Comment by hinthornw** [comment]
Could you provide a code snippet to reproduce this?

**Comment by Mabenan** [comment]
Never mind was my mistake some way i got the session parameter set and this lead to the execution of the prompt template
