### ISSUE TITLE
Issue: Using qdrant.as_retriver() to use the filtered data of a collection (filtered on the basis of payload data)

### ISSUE THREAD

**Issue by shubham184** [langchain-ai/langchain#8126]
### Issue you'd like to raise.

Unable to use metadata filtering of a collection qdrant and then use it in as_retriever function.

### Suggestion:

Qdrant.from_documents should include a filtering method as well to filer on the collection with payload (metadata)

**Comment by shubham184** [comment]
I am using the the langchain = 0.0.238
so I am creating a collection in qdrant for User which has multiple documents and which can be filtered by the payload info (metadata contains the document id)
now a user also has multiple agents, so my specific use case is to either recreate a new collection per agent which will have access to some of the docs of user (depends on selection) or if qdrant.as_retrievrer() could filter out the documents which an agent could then use.

**Comment by Vagif12** [comment]
This is a problem for me as well.
I want to set the default search type as mmr and  limit k to 5 using search_kwargs as follows:

`db.as_retriever(search_type="mmr",search_kwargs={'k':4, 'reduce_k_below_max_tokens':True})`
, but it seems like the `Qdrant` retriever in langchain does not support this

 @hwchase17  perhaps you could help?

**Comment by nndnha** [comment]
This should work
```python
from qdrant_client.http import models as qdrant_models

retriever = qdrant.as_retriever(
            search_kwargs=dict(
                filter=qdrant_models.Filter(
                    must=[
                        qdrant_models.FieldCondition(
                            key="metadata.nested_field_name",
                            match=qdrant_models.MatchValue(value='123456')
                        )
                    ]
                )
            )
        )
```

**Comment by Vagif12** [comment]
@nndnha how would you specify k and set mmr as the search type using this method?

**Comment by ANUSHA-hub-bit** [comment]
retriever = vector_store.as_retriever(
    include_metadata=True,
    metadata_key='source',
    top_k=30,
    search_type="similarity",
    search_kwargs=dict(
                filter=qdrant_models.Filter(
                    must=[
                        qdrant_models.FieldCondition(
                            key="file_id",
                            match=qdrant_models.MatchValue(value=file_id)
                        )
                    ]
                )
            )

)
{'question': 'what is collaterla?', 'chat_history': [], 'answer': "Apologies, but I couldn't find the information you requested in the document.", 'source_documents': []} .................................
getting empty source documents even the db contains data
