### ISSUE TITLE
create_sql_aqent not working with `AgentType.OPENAI_FUNCTIONS`

### ISSUE THREAD

**Issue by mljlynch** [langchain-ai/langchain#8132]
### System Info

Langchain version: ```langchain = "^0.0.236"````
Python 3.10.10
MacOSx 13.4.1 (c) (22F770820d)

### Who can help?

@hwchase17 @agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Mysql 5.7 db. 

```
toolkit = SQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0))

agent_executor = create_sql_agent(
    llm=ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613"),
    toolkit=toolkit,
    verbose=False,
    agent_type=AgentType.OPENAI_FUNCTIONS,
)

    response = agent_executor.run(question)
```

Error message:

```none is not an allowed value (type=type_error.none.not_allowed)```

Note: It does work with `AgentType.ZERO_SHOT_REACT_DESCRIPTION`

### Expected behavior

I would expect a response from the agent

Observed:

```none is not an allowed value (type=type_error.none.not_allowed)```

**Comment by mljlynch** [comment]
I think you just suggested I do the same thing I'm doing. I don't see the difference.

**Comment by keenborder786** [comment]
Please update your langchain package. The issue has been resolved in the newer version.
