### ISSUE TITLE
Issue: Why condense the conversational history when Open AI provides a 'messages' field in its API?

### ISSUE THREAD

**Issue by brett-matson** [langchain-ai/langchain#8141]
### Issue you'd like to raise.

Hi there, 

I've found many scenarios where ConversationalRetrievalChain's attempt to condense a conversation history into a stand-alone question fails, either because the history is too complex or, for example, if the user simply provides an affirmation.

Why do we attempt to condense the conversational history when Open AI's chat API provides a [messages](https://platform.openai.com/docs/api-reference/chat/create#chat/create-messages) field for this purpose?

Is there a way to construct a retrieval chain such that the messages field in Open AI's chat API can be used instead of attempting to condense the chat history into a stand-alone question?

### Suggestion:

Provide a way to construct a retrieval chain such that Open AI's chat API's messages field can be used instead of attempting to condense the question.

**Comment by kdcokenny** [comment]
I believe the condensed question is used for the vectorstore's get_similar_documents query.

**Comment by brett-matson** [comment]
Thanks @kdcokenny, that makes sense. 

I wonder whether there'd be a way to then structure the chain to get the LLM to use the full chat history.
