### ISSUE TITLE
[LLM] Wrapper for Forefront AI API

### ISSUE THREAD

**Issue by vertinski** [langchain-ai/langchain#815]
It would be great if we had a LLMs wrapper for Forefront AI API. They have a selection of open source LLMs accessible, such as GPT-J and GPT-NeoX.

**Comment by batmanscode** [comment]
Fwiw goose.ai (GPT-J, Neo etc) uses OpenAI API. They have a few extra parameters that'll be nice to have with Langchain but for the most part I think it should just work out of the box

**Comment by solyarisoftware** [comment]
BTW: https://langchain.readthedocs.io/en/latest/modules/llms/integrations/huggingface_hub.html

**Comment by batmanscode** [comment]
> BTW: https://langchain.readthedocs.io/en/latest/modules/llms/integrations/huggingface_hub.html 

I wonder if this method can be used to access bloom/bloomz via petals

https://github.com/bigscience-workshop/petals
