### ISSUE TITLE
Retain links when extracting text using PDFLoader

### ISSUE THREAD

**Issue by ahm750** [langchain-ai/langchain#8157]
### System Info

Hi,

I'm using version 0.0.105 of langchain (nodejs). 

I'm using PDFLoader to embed PDF documents, and I've noticed that the extracted documents do not retain the hyperlinks that were present in the files.

Is there a way to retain them? I couldn't find it in the document or the PDFLoader class.

### Who can help?

@eyurtsev @hwchase17 @agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

var pdfLoader = new PDFLoader(filePath, {
    splitPages: false,
});

var rawDocs = await pdfLoader.load();
console.log(rawDocs);

### Expected behavior

I was expecting PDFLoader to convert the hyperlinks in the PDF to either raw URLs or markdown URL.

**Comment by ahm750** [comment]
Bump

**Comment by devstein** [comment]
@ahm750 This is the wrong repository. Can you close this and open an issue on [LangChainJS](https://github.com/hwchase17/langchainjs/issues)
