### ISSUE TITLE
Migration OpenAIEmbedding from Azure to OpenAI reproduce gives an error message "ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions."

### ISSUE THREAD

**Issue by somisawa** [langchain-ai/langchain#8159]
### System Info

python = ">=3.9,<3.12"
fire = "0.5.0"
pandas = "2.0.2"
sqlalchemy = "2.0.15"
rich = "13.4.1"
mysqlclient = "2.1.1"
pandera = "0.15.1"
openai = "0.27.7"
guidance = "0.0.62"
langchain = "0.0.221"
textual = "^0.29.0"

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Prepare data. In our case, there are 3576 documents.
2. Migrate API
before migration:
```python
embeddings = OpenAIEmbeddings(
    model="text-embedding-ada-002",
    deployment=<MY_DEPLOYMENT_NAME>,
    chunk_size=1,
    openai_api_base=os.environ["OPENAI_API_BASE"],
    openai_api_key=os.environ["OPENAI_API_KEY"],
    openai_api_type="azure",
)
```
after migration:
```python
embeddings = OpenAIEmbeddings(
    model="text-embedding-ada-002",
    openai_api_key=os.environ["OPENAI_API_KEY"],
    openai_api_type="openai",
)
```
3. Make FAISS DB
The code are the same as that of before-migration version.
db = FAISS.from_documents(docs, embeddings)

4. Error occurs
```
Traceback (most recent call last):
  File "/path/make_dataframe.py", line 54, in <module>
    db = FAISS.from_documents(docs, embeddings)
  File "/path/.venv/lib/python3.9/site-packages/langchain/vectorstores/base.py", line 337, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "/path/.venv/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 554, in from_texts
    return cls.__from(
  File "/path/.venv/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 506, in __from
    vector = np.array(embeddings, dtype=np.float32)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3576,) + inhomogeneous part.
```

### Expected behavior

Correctly construct FAISS DB without error.

**Comment by zishanahmed-tomtom** [comment]
I also have the same issue
