### ISSUE TITLE
langchain.llms.Petals doesnt support llama models

### ISSUE THREAD

**Issue by okyx** [langchain-ai/langchain#8161]
### Feature request

support for llama models for petals module

### Motivation

i'm furstated when i want to use petals (distributed model) for llama2, my gpu is not enough to run all models

### Your contribution

-

**Comment by janpawellek** [comment]
Llama support for the Petals LLM has been added in v0.0.247 in this PR: https://github.com/langchain-ai/langchain/pull/8356

A GPU is not needed to run Petals I think.
