### ISSUE TITLE
Adding Adobe PDF extraction API as an additional langchain document loader

### ISSUE THREAD

**Issue by moein-shariatnia** [langchain-ai/langchain#8163]
### Feature request

Hi langchain team!

I'd like to contribute this feature to the langchain document loaders. 

There are multiple pros for using Adobe API instead of the existing libraries for converting pdf to text and other metadata; e.g, adobe API allows for extraction of tables and figures in pdf documents as separate .csv and .png files, respectively. 
These are of course in addition to raw text extraction which in my opinion works better most of the time compared to other libraries. 

Here are a few links to examples and source code:
[Adobe python API example](https://developer.adobe.com/document-services/docs/overview/pdf-extract-api/quickstarts/python/)
[Adobe SDK](https://github.com/adobe/pdfservices-python-sdk-samples/tree/main/src/extractpdf)

### Motivation

I needed to extract the tables in pdf files in a standard format to extract the data in them more carefully. I was also not satisfied by the existing libraries performance on raw text extraction.

### Your contribution

I'd like to contribute this feature as a new document loader in langchain. Let me know if I can start working on it.
Thanks!

**Comment by jacobboon** [comment]
This is still relevant to the LangChain repository!

We're currently using this as main PDF extraction method and would like for this to be part of LangChain and be able to use `.load_and_split` 😊
