### ISSUE TITLE
How to use MongoDB to store vector embeddings and during extracting the relevant document, using `FAISS` for similarity search based document relevancy?

### ISSUE THREAD

**Issue by Shuhul24** [langchain-ai/langchain#8170]
### Issue you'd like to raise.

I am using FAISS vector store for storing the vector embeddings of the documents and retrieving the relevant document with respect to the query. My question is that `FAISS` does not store the embeddings permanently, instead it stores it in RAM and when running the code once again, it simply overwrites on the previous one or simply adds another index for it (I am not sure on this one). What I want is that to store these embeddings, say on `MongoDB` so that it gets stored there for longer period of time and when extracting those embeddings, `FAISS` is the algorithm to be used for similarity search based extraction (as it is best for large documents). Is it possible?

### Suggestion:

I tried `MongoDBAtlasVectorSearch` for this and came to know that it does store the vector embeddings in MongoDB database but when extracting the relevant document with respect to a query it does not use `FAISS` based similarity search algorithm (which is, I believe, better than the one used by `MongoDBAtlasVectorSearch`).

**Comment by Shuhul24** [comment]
Can you show me an example of how to use the above mentioned python script in Langchain's `ConversationalRetrievalChain` or `RetreivalQA` chain?

**Comment by Shuhul24** [comment]
How to load vector embeddings of a text document (reading the text document using ` langchain.document_loaders.TextLoader`) using `langchain.embeddings.OpenAIEmbeddings` and then extract the embeddings using `langchain.vectorstores.FAISS`?

**Comment by Shuhul24** [comment]
I am sorry but in the above mentioned code script you haven't used `langchain.vectorstores.FAISS` for extracting the similar documents based on the FAISS method. Can you please check and let me know?

**Comment by aaa-keerthana** [comment]
embedding = OpenAIEmbeddings(
        deployment="sample-deployment",
        model="text-embedding-sample-model",
        openai_api_base="https://sample.openai.azure.com/",
        openai_api_type="azure",
        openai_api_key="api_key"
    )    

collection -> Existing mongoDB collection

vectorStore = MongoDBAtlasVectorSearch(embedding=embedding, collection=collection)

when invoking this vectorStore.similaritySearch(query) , it is hanging on the langchain version 0.0.250 and above but works in the 0.0.249.

**Comment by Sachidanand-shah** [comment]
suppose i am creating a embeddings and storing inside mongodb now i want to merge new embeddings to existing once in mongodb how can i achive that?
