### ISSUE TITLE
DOC: Langchain integration with sagemaker missing

### ISSUE THREAD

**Issue by debasisdwivedy** [langchain-ai/langchain#8178]
### Issue with current documentation:

Hi,

The integration document for langchain with AWS sagemaker has been removed.
Do we have an updated doc for that.

[https://python.langchain.com/docs/modules/model_io/models/llms/integrations/sagemaker.html](url)

**Comment by corvuslee** [comment]
Do you mean this - https://python.langchain.com/docs/integrations/llms/sagemaker ?

**Comment by debasisdwivedy** [comment]
Yes. Thanks
