### ISSUE TITLE
Issue: Using HuggingFace Inference Endpoint as LLM in QA Chain

### ISSUE THREAD

**Issue by kmaurinjones** [langchain-ai/langchain#8181]
### Issue you'd like to raise.

Hi there, I've been trying to come up with a system that can do the following:

1. take in a string as input (much longer len than the 512 token limit of the flan-t5-large model I'm using)
2. Use vector db (currently using FAISS) + langchain to index and query for relevant chunks
3. Use a model I've deployed at a HF endpoint to get inference for a question I have relating to the data

I've been able to achieve this just fine using the Huggingfacehub() class to create the LLM for the chain, but this uses the HF free inference endpoint, which of course has rate limits and is slow, which is why I'd like to use my own endpoint. I have not been able to find a way to use my endpoint in place of the free endpoint, and I've looked everywhere. I'm hoping it's something simple I've overlooked but any help would be greatly appreciated.

It would amazing I could see a specific Python example. Thanks in advance.

**Comment by scottdshan** [comment]
I think you are looking for this:

https://github.com/huggingface/text-generation-inference

There are built in langchain integrations.

**Comment by scottdshan** [comment]
It sounds like a huggingface token no? Sometimes you need to use a token to download certain models even if they are free.
