### ISSUE TITLE
AttributeError: 'Redis' object has no attribute '_Redis__get_retriever_tags'. Did you mean: '_VectorStore__get_retriever_tags'?

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [langchain-ai/langchain#8185]
### System Info

langchain ==  0.0.240
Python 3.10.9

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chains import RetrievalQA
from langchain.indexes import VectorstoreIndexCreator
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings

from langchain.llms import OpenAI
from langchain.document_loaders import PyPDFLoader
import os 
from langchain.vectorstores.redis import Redis

loader = PyPDFLoader("test.pdf")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)
embeddings = OpenAIEmbeddings( deployment="text-embedding-ada-002",model="text-embedding-ada-002",chunk_size=1)
db = Redis.from_documents(
    texts, embeddings, redis_url="redis://localhost:6379", index_name="link"
)
retriever = db.as_retriever(search_type="similarity", search_kwargs={"k":2})
qa = RetrievalQA.from_chain_type(
    llm=OpenAI(), chain_type="stuff", retriever=retriever, return_source_documents=True)
query = "What is Compilance"
result = qa({"query": query})

print(result)

### Expected behavior

Getting the result of the query but having error at as_retriver() like  AttributeError: 'Redis' object has no attribute '_Redis__get_retriever_tags'. Did you mean: '_VectorStore__get_retriever_tags'?

**Comment by KirillKazakov8** [comment]
The same problem: "Getting the result of the query but having error at as_retriver() like AttributeError: 'Redis' object has no attribute '_Redis__get_retriever_tags'. Did you mean: '_VectorStore__get_retriever_tags'?" How can I fix it?

**Comment by GMartin-dev** [comment]
Same error here!
This issue is likely due to the use of name mangling in Python. I need to fix this asap for me so I will have news soon.

**Comment by GMartin-dev** [comment]
PR ready with a temporary fix that perhaps is not definitive.
https://github.com/langchain-ai/langchain/pull/8274

**Comment by hinthornw** [comment]
Should probably change the dunder method to a sunder method

**Comment by GMartin-dev** [comment]
> Hello Martin, i tried with this fixes for redis but i started getting: AttributeError: 'Redis' object has no attribute '_Redis__get_retriever_tags'. without the "Did you mean: '_VectorStore__get_retriever_tags'?" i check the source and for some reason wants reading the "self" attributes, had to go back to 0.0.235 with the direct return of return VectorStoreRetriever

The PR was merged already and it was working for me after that merge latest I tested was 0.0.244. Are you seeing the exact same error again?
