### ISSUE TITLE
DOC: Apify integration missing

### ISSUE THREAD

**Issue by scaratec** [langchain-ai/langchain#8201]
### Issue with current documentation:

The Apify integration has been delete by @hwchase17 in commit aa0e69bc98fa9c77b01e5104f12b2b779f64fd33 and thus this documentation is not valid anymore:

https://python.langchain.com/docs/integrations/tools/apify

### Idea or request for content:

It would be highly beneficial to have information on a suitable replacement for the Apify integration.

**Comment by dmyoung9** [comment]
While it does indeed look like the docs are outdated, it appears the Apify integration has just been moved into `langchain.document_loaders`: #2215

**Comment by jirimoravcik** [comment]
Fixed in https://github.com/langchain-ai/langchain/pull/10067
