### ISSUE TITLE
Issue: How do I search for the result in the past 24 hours with GoogleSerperAPIWrapper

### ISSUE THREAD

**Issue by dinhan92** [langchain-ai/langchain#8216]
### Issue you'd like to raise.

With GoogleSerperAPIWrapper(type="news"), how do I config to get the result in the past 24 hours?

**Comment by dinhan92** [comment]
Thank you for that, I am able to get posts in the past 24 hours, but how can I get the content of the posts in the websites I got ?

**Comment by MarcinRutecki** [comment]
How to use Scrapy together with GoogleSerperAPIWrapper?
