### ISSUE TITLE
PDFLoader metadata.source points to temp file path rather than pdf url

### ISSUE THREAD

**Issue by kubre** [langchain-ai/langchain#8222]
### System Info

langchain = 0.0.240
python = 3.9.13
OS = Windows 11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Use the PyMuPDFLoader
2. Load online pdf from URL without any special args name

EX:

![image](https://github.com/langchain-ai/langchain/assets/20380094/c048abfc-ace3-4f35-8259-348f865826c2)

### Expected behavior

The source should point to the online web URL rather than the temp file in the system.

**Comment by frangin2003** [comment]
Hi @kubre 👋
It would help to see the code that produces that error.

Recommend you add it 🖥️⌨️

**Comment by kubre** [comment]
Nothing special as pointed out in the screenshot above, you just need to use pdf_loader with web URL

```python
from langchain.document_loaders.pdf import PyMuPDFLoader
pdf_url = "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
loader = PyMuPDFLoader(pdf_url)
print("Incorrect ==>", loader.load()[0].metadata["source"])
print("Correct ==>", loader.source)
```

In any Document, you will now see `document.metadata["source"]` pointing to the tmp_path rather than `loader.source` which will point to web URL correctly

**Comment by kubre** [comment]
> @kubre since you have an issue created already, would you mind if I pushed some changes to address this issue?

Like a PR? Fine with me I didn't time to work on this or anything

**Comment by KentonParton** [comment]
@eyurtsev Could I get your thoughts on how we want to address this issue?

### Here's some context 
If you run the code below you will notice that `data[0].metadata['source']` is the temporary file path instead of the web path.

### Example Code and output:
```python
from langchain.document_loaders.pdf import PyMuPDFLoader

loader = PyMuPDFLoader("https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf")
data = loader.load()
print(data[0].metadata)

# {'source': '/var/folders/51/yntqh8ls05j42ttlcffmcl7m0000gn/T/tmpzo6dx73j/tmp.pdf', 'file_path': '/var/folders/51/yntqh8ls05j42ttlcffmcl7m0000gn/T/tmpzo6dx73j/tmp.pdf', 'page': 0, 'total_pages': 4, 'format': 'PDF 1.3', 'title': 'PDF Bookmark Sample', 'author': 'Accelio Corporation', 'subject': '', 'keywords': '', 'creator': '', 'producer': 'Acrobat Distiller 4.05 for Windows', 'creationDate': 'D:20011026133934', 'modDate': "D:20011026134041-04'00'", 'trapped': '', 'encryption': 'Standard V1 R2 40-bit RC4'}
```
This applies to a number of other PDFLoaders too.

### What is causing this behaviour (in reverse)
`source` is populated by `blob.source` here:
https://github.com/langchain-ai/langchain/blob/5d60ced7b39733afc43e2aa2b72279082ac996c0/libs/langchain/langchain/document_loaders/parsers/pdf.py#L63-L78

and `blob.source` is set to `file_path`:
https://github.com/langchain-ai/langchain/blob/5d60ced7b39733afc43e2aa2b72279082ac996c0/libs/langchain/langchain/document_loaders/blob_loaders/schema.py#L21-L47

### Potential solutions
1. We start passing in `web_path` to Blob and set `source` accordingly e.g.

```python
class PyMuPDFLoader(BasePDFLoader):
    """Load `PDF` files using `PyMuPDF`."""

    def __init__(self, file_path: str) -> None:
        """Initialize with a file path."""
        try:
            import fitz  # noqa:F401
        except ImportError:
            raise ImportError(
                "`PyMuPDF` package not found, please install it with "
                "`pip install pymupdf`"
            )

        super().__init__(file_path)

    def load(self, **kwargs: Optional[Any]) -> List[Document]:
        """Load file."""

        parser = PyMuPDFParser(text_kwargs=kwargs)
        blob = Blob.from_path(self.file_path, web_path=self.web_path) # <--change
        return parser.parse(blob)
```
```python
class Blob(BaseModel):
    data: Union[bytes, str, None]  # Raw data
    mimetype: Optional[str] = None  # Not to be confused with a file extension
    encoding: str = "utf-8"  # Use utf-8 as default encoding, if decoding to string
    path: Optional[PathLike] = None
    web_path: Optional[str] = None # <--change

    @property
    def source(self) -> Optional[str]:
        """The source location of the blob as string if known otherwise none."""
        if self.web_path: # <--change
            return str(self.web_path) # <--change
        return str(self.path) if self.path else None
```

2. We pass `web_path` into `parser.parse(blob, web_path=self.web_path)
```python
class PyMuPDFLoader(BasePDFLoader):
    """Load `PDF` files using `PyMuPDF`."""

    def __init__(self, file_path: str) -> None:
        """Initialize with a file path."""
        try:
            import fitz  # noqa:F401
        except ImportError:
            raise ImportError(
                "`PyMuPDF` package not found, please install it with "
                "`pip install pymupdf`"
            )

        super().__init__(file_path)

    def load(self, **kwargs: Optional[Any]) -> List[Document]:
        """Load file."""

        parser = PyMuPDFParser(text_kwargs=kwargs)
        blob = Blob.from_path(self.file_path)
        return parser.parse(blob, web_path=web_path) # <--change
```
```python
class PyMuPDFParser(BaseBlobParser):
    """Parse `PDF` using `PyMuPDF`."""

    def __init__(self, text_kwargs: Optional[Mapping[str, Any]] = None) -> None:
        """Initialize the parser.

        Args:
            text_kwargs: Keyword arguments to pass to ``fitz.Page.get_text()``.
        """
        self.text_kwargs = text_kwargs or {}

    def lazy_parse(self, blob: Blob, *, web_path=None) -> Iterator[Document]:
        """Lazily parse the blob."""
        import fitz

        with blob.as_bytes_io() as file_path:
            doc = fitz.open(file_path)  # open document

            yield from [
                Document(
                    page_content=page.get_text(**self.text_kwargs),
                    metadata=dict(
                        {
                            "source": web_path if web_path else blob.source, # <--change
                            "file_path": web_path if web_path else blob.source, # <--change
                            "page": page.number,
                            "total_pages": len(doc),
                        },
                        **{
                            k: doc.metadata[k]
                            for k in doc.metadata
                            if type(doc.metadata[k]) in [str, int]
                        },
                    ),
                )
                for page in doc
            ]
```

Do you have a preference over option 1 or option 2? I think adding web_path to Blob isn't really in alignment with it's purpose so I'm in favour of option 2. Is there another solution you think would be better?

Thanks!

**Comment by eyurtsev** [comment]
Hi @KentonParton ! Thanks for providing all the references, and apologies for taking a few days to get back!

Here are the two solutions that we're thinking about:

1. Adding a metadata field to blob, turning it into a generalization of a document. A blob can represent any binary data (not just text), and be associated with metadata. Then `source` can be dropped into the a metadata field. 

The main concern with this approach is that the metadata field becomes a free for all field. And I'm thinking about whether we should be standardizing it.

2. Allowing a user to set the `source` on the blob when creating it. `source` would always be expected to represent the ultimate provenance.

----

I wanted to explain the reasoning behind the interfaces for the parser and the blob w/ regards to the 2 solutions above:

1. For document loading/transforming abstractions and implementations we want all the configuration to come solely through the initializer. This will make it easy to chain the transformations into a single pipeline and also serialize it.

2. I would like to deprecate the notion of `web-path` going forward. A string field can be used as a generic URL and reference either local files, or files on the web, or files on s3, or files in a database etc. We need 2 fields to represent immediate provenance and ultimate provenance(s) respectively
