### ISSUE TITLE
Retrying langchain.embeddings.openai.embed_with_retry

### ISSUE THREAD

**Issue by betterMax** [langchain-ai/langchain#8259]
### System Info

Here is my code:
```from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings
persist_directory = 'docs/chroma/'
embedding = OpenAIEmbeddings(request_timeout=60)
vectordb = Chroma(persist_directory=persist_directory, embedding_function=embedding)
question = "What are major topics for this class?"
docs = vectordb.similarity_search(question,k=3)
len(docs)
```

Here is the issue:
`Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))).`

I have tried my apikey with other code and it works just fine. First time it happens when I use `embedding = OpenAIEmbeddings()` with another group of codes and then I change it to `embedding = OpenAIEmbeddings(request_timeout=60)` and it works. But this time, even if I increase the request_timeout to 120 and it still doesn't work. Any thought on this?

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
import os
import openai
import sys
sys.path.append('../..')

import panel as pn  # GUI
pn.extension()

from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv()) # read local .env file

openai.api_key  = os.environ['OPENAI_API_KEY']
import datetime
current_date = datetime.datetime.now().date()
if current_date < datetime.date(2023, 9, 2):
    llm_name = "gpt-3.5-turbo-0301"
else:
    llm_name = "gpt-3.5-turbo"
print(llm_name)
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings
persist_directory = 'docs/chroma/'
embedding = OpenAIEmbeddings(request_timeout=60)
vectordb = Chroma(persist_directory=persist_directory, embedding_function=embedding)
question = "What are major topics for this class?"
docs = vectordb.similarity_search(question,k=3)
len(docs)
```

### Expected behavior

How can I make it work stably instead of having this occasionally?

**Comment by devstein** [comment]
@betterMax I run into this issue sporadically. I have always assumed the root cause is on OpenAI's side because retrying it over some period of time typically solves it for me

**Comment by timxieICN** [comment]
Same here - I definitely set proxy in my code. I think there's timeout due to rate limit from time to time.

**Comment by betterMax** [comment]
> @betterMax I run into this issue sporadically. I have always assumed the root cause is on OpenAI's side because retrying it over some period of time typically solves it for me

Yes. I thought the same. But I tried another code that also uses the openai API, and it works fine. So that's not related to API.
