### ISSUE TITLE
Issue: LLMChain throwing abstract class BasePromptTemplate error, even when the prompt templates used are not abstract.

### ISSUE THREAD

**Issue by lydiayu26** [langchain-ai/langchain#8266]
### Issue you'd like to raise.

I am trying to instantiate 2 LLMChains, each of which should use a SystemMessagePromptTemplate to specify the way that it should communicate. Both are using the same LLM from the HF pipeline. 

The following code gives the error "ValidationError: 1 validation error for LLMChain prompt Can't instantiate abstract class BasePromptTemplate with abstract methods format, format_prompt (type=type_error)" at the instantiation of the LLMChain. 
```
llm = HuggingFacePipeline.from_model_id(
model_id="microsoft/DialoGPT-medium",
task="text-generation",
model_kwargs={"temperature": 0, "max_length": 100},
)

ai_bot_template = "You are an AI chatbot that interacts with humans. You will also be interacting with a Therapist with the goal of improving the safety, trustworthiness, and ethics of your communication. There will also be a moderator that checks in throughout your interactions with the therapist and the human."
ai_therapist_template = "You are an AI therapist that interacts with AI chat bots. Your goal is to help the chat bot improve the safety, trustworthiness, and ethics of its interactions with humans."

ai_bot_prompt = SystemMessagePromptTemplate.from_template(ai_bot_template)
ai_therapist_prompt = SystemMessagePromptTemplate.from_template(ai_therapist_template)

therapist_chain = LLMChain(prompt=ai_therapist_prompt, llm=llm)
ai_bot_chain = LLMChain(prompt=ai_bot_prompt, llm=llm)
```

**Comment by Matx00** [comment]
hi @lydiayu26, did you solve it in the end?

**Comment by KD-TrendOn** [comment]
i had a similar problem and problem was with import. I was importing 
from langchain_core.prompts import PromptTemplate
instead of 
from langchain.prompts import PromptTemplate
Honestly, that problem occured because i used the code that langchain's doc's chatbot writed

**Comment by jasperblues** [comment]
For me it was a circular import.
