### ISSUE TITLE
devcontainer in vscode is not working

### ISSUE THREAD

**Issue by Bennoo** [langchain-ai/langchain#8277]
### System Info

Macos 13.5, vscode 1.80.1

### Who can help?

@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

As mentioned in the readme if .devcontainer
1. Clone locally
2. In Vscode select Build and open in dev container

### Expected behavior

The Devcontainer is working well, Building and running 
![image](https://github.com/langchain-ai/langchain/assets/2066836/25054f29-4928-4256-aba3-eab37d8b4a8e)
 but the mounted folder is incorrect and empty, so the vscode file explorer is empty 
![image](https://github.com/langchain-ai/langchain/assets/2066836/8a9c58fa-ffb9-49ba-bfca-90fc2469f068)

![image](https://github.com/langchain-ai/langchain/assets/2066836/37093dbb-8a8c-40b5-bd0d-438ee37a2928)

Maybe due to the devcontainer.json file, referring to a FolderBaseName variable 
![image](https://github.com/langchain-ai/langchain/assets/2066836/8eea662b-3d31-41d7-89e4-660205c1d260)

**Comment by hinthornw** [comment]
Likely broke during the refactor of experimental package

**Comment by whuwxl** [comment]
You need to update the file mount in `.devcontainer/docker-compose.yaml` to match the location specified by 'workspaceFolder' in `devcontainer.json`. In the case of @Bennoo, update the volumes to: `- ..:/workspaces/langchain:cached`, and it will work fine.
