### ISSUE TITLE
Problem using HuggingFacePipeline by passing pipeline in directly

### ISSUE THREAD

**Issue by Jakmoon** [langchain-ai/langchain#8280]
### System Info

langchain 0.0.242
python 3.11.4

### Who can help?

@hwchase17
@hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I try using a local LLM from HuggingFace: 

1. Using from_model_id works perfectly: 
llm = HuggingFacePipeline.from_model_id(
    model_id="TheBloke/wizardLM-7B-HF",
    task="text-generation",
    pipeline_kwargs={"max_new_tokens": 1200, "temperature": 0.3, "top_p": 0.95, "repetition_penalty": 1.15,},
    device=0,
)

print(llm)
Params: {'model_id': 'TheBloke/wizardLM-7B-HF', 'model_kwargs': {}, 'pipeline_kwargs': {'max_new_tokens': 1200, 'temperature': 0.3, 'top_p': 0.95, 'repetition_penalty': 1.15}}

2. Now the problem is when **passing pipeline directly**: 
I just followed the example given in Langchain.

from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import transformers

model_id  = "TheBloke/wizardLM-7B-HF"
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, trust_remote_code=True)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    device_map="auto",
    max_new_tokens = 1200,
    temperature = 0.3,
    top_p = 0.95,
    repetition_penalty = 1.15,
)
hf = HuggingFacePipeline(pipeline=pipe)
print(hf)
### Expected behavior

What is the matter? 
Why are the paramters that I set not taken? 
Why does it use the default ones? 

I tried it now over and over and over again, but I can't get it work. 
Sb has any idea why? I am a bit desperate, cause I need to pass pipeline directly. 

Official langchain documentation: 
Example passing pipeline in directly:

    from langchain.llms import HuggingFacePipeline
    from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

    model_id = "gpt2"
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model = AutoModelForCausalLM.from_pretrained(model_id)
    pipe = pipeline(
        "text-generation", model=model, tokenizer=tokenizer, max_new_tokens=10
    )
    hf = HuggingFacePipeline(pipeline=pipe)

**Comment by Jakmoon** [comment]
Sorry, that's not what I was looking for: 

I see people using the way I described it and it works for them obviously, but not for me. 
I have Python 3.11.4 and all packages up to date installed. Any idea?

**Comment by praveenv** [comment]
I have the exact same problem listed above

**Comment by praveenv** [comment]
@dosubot

The issue is relevant and has been addressed in this [PR](https://github.com/langchain-ai/langchain/pull/12817) , but it has not been merged yet.
