### ISSUE TITLE
AttributeError: `Document` object has not attribute `replace`

### ISSUE THREAD

**Issue by Shuhul24** [langchain-ai/langchain#8286]
### System Info

langchain==0.0.144
python3 == 3.11.4

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am running the following code:
```
from langchain.document_loaders import PyMuPDFLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS

# Load the text document
loader = PyMuPDFLoader("path/to/file.pdf")
documents = loader.load()

# Split the document into chunks
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

# Generate the embeddings
embeddings = OpenAIEmbeddings()
embedded_docs = embeddings.embed_documents(docs)

# Initialize FAISS
db = FAISS.from_documents(embedded_docs, embeddings)

# Perform a similarity search between the embedding of the query and the embeddings of the documents
query = "Your query here"
similar_docs = db.similarity_search(query)

# Print the content of the most similar document
print(similar_docs[0].page_content)
```

The error occurs as follows:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/folders/q3/9988ccxx13q_x9yfdkv36x2r0000gn/T/ipykernel_22317/1552469458.py:1 in <module>     │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/var/folders/q3/9988ccxx13q_x9yfdkv36x2r0000gn/T/ipykernel_22317/1552469458.py'                 │
│                                                                                                  │
│ /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/embedd │
│ ings/openai.py:275 in embed_documents                                                            │
│                                                                                                  │
│   272 │   │   """                                                                                │
│   273 │   │   # handle batches of large input text                                               │
│   274 │   │   if self.embedding_ctx_length > 0:                                                  │
│ ❱ 275 │   │   │   return self._get_len_safe_embeddings(texts, engine=self.document_model_name)   │
│   276 │   │   else:                                                                              │
│   277 │   │   │   results = []                                                                   │
│   278 │   │   │   _chunk_size = chunk_size or self.chunk_size                                    │
│                                                                                                  │
│ /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/embedd │
│ ings/openai.py:209 in _get_len_safe_embeddings                                                   │
│                                                                                                  │
│   206 │   │   │   encoding = tiktoken.model.encoding_for_model(self.document_model_name)         │
│   207 │   │   │   for i, text in enumerate(texts):                                               │
│   208 │   │   │   │   # replace newlines, which can negatively affect performance.               │
│ ❱ 209 │   │   │   │   text = text.replace("\n", " ")                                             │
│   210 │   │   │   │   token = encoding.encode(                                                   │
│   211 │   │   │   │   │   text,                                                                  │
│   212 │   │   │   │   │   allowed_special=self.allowed_special,                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Document' object has no attribute 'replace'
```

### Expected behavior

Expected behaviour is that the variable `embedded_docs` should return a list of vector embeddings for each document.

**Comment by jaganadhg** [comment]
I encountered the same issue. The source of this error is from the document chunking. After chunking, we get a list of objects with `page_content` and `metadata`. The embedding may expect a `str`.

Note: our use case was with ChromaDB.

**Comment by naveenfaclon** [comment]
[EXCEPTION] Reason: 'list' object has no attribute 'replace'

`query_embedding = embeddings.embed_query([query])

            # Define kwargs
            kwargs = {
                "score_threshold": 0.75 # Minimum score
            }

            results = Knowledge_vector_database.similarity_search_with_relevance_scores(query=query, k=c.NUM_RETRIEVED_DOCS,
                                                                                                **kwargs)
            
            # query_embedding = embeddings.embed_query(query)

            # # Check relevance o the query Method 1
            # results = Knowledge_vector_database.similarity_search_with_score_by_vector(query_embedding, 
            #                                                                                        k=c.NUM_RETRIEVED_DOCS, 
            #                                                                                        fetch_k=10,
            #                                                                                        kwargs={"score_threshold": 0.8}
                                                                                                #    )
            retrieved_docs = []
            for doc, score in results:
                if score >= kwargs["score_threshold"]:
                    retrieved_docs.append({
                        "content": doc.page_content,
                        "relevance_score": score
                    })

            # check relevance with similarity methods 2
            # results = Knowledge_vector_database.similarity_search_with_score_by_vector(query_embedding, k=c.NUM_RETRIEVED_DOCS, kwargs={"score_threshold": 0.9})
                
            # prompt_for_general_query_format = [
            #     {"role": "user", 
            #     "content": 
            #         """please generate a response based on the user's prompt.
            #         Present the response in HTML format as if it were content for the inside of an HTML <body> tag, but do not include
            #         the <body> tag or any other HTML boilerplate and don't add quotation symbols or newline characters. if you're unsure of the answer, say "Sorry, I don't know".
            #         """
            #     },

            #     {"role": "assistant", 
            #     "content": "Context:\n{context}\n---\nNow here is the question you need to answer.\nQuestion: {question}"}
            # ]
            # RAG_PROMPT_TEMPLATE_2 = tokenizer.apply_chat_template(prompt_for_general_query_format, tokenize=False, add_generation_prompt=False)
            # general_query_prompt = RAG_PROMPT_TEMPLATE_2.format(question=query_embedding, context=context)                                                             
            
            # retrieved_docs = []
            # for doc, score in results:
            #     if score > kwargs["score_threshold"]:
            #         retrieved_docs.append({"content": doc.page_content, "score": score})
                # else:
                #     answer = util.generate_answer_with_user_prompt(llm, general_query_prompt)                                             

           
        
            retrieved_docs_text = [doc.page_content for doc in retrieved_docs]
            # context = "\nExtracted documents:\n" + "".join([f"Document {str(i)}:::\n" + doc for i, doc in enumerate(retrieved_docs_text)])
            context = "\n".join([f"Document {i}: {doc['content']} \nRelevance: {doc['relevance_score']})" for i, doc in enumerate(retrieved_docs_text)])`

**Comment by lcy412** [comment]
> I encountered the same issue. The source of this error is from the document chunking. After chunking, we get a list of objects with `page_content` and `metadata`. The embedding expects a string. If we crate a list with `pagecontent` alone and pass it to embedding and Vector Store the issue will be resolved.
> 
> Solution
> 
> ```
> from langchain.document_loaders import PyMuPDFLoader
> from langchain.embeddings.openai import OpenAIEmbeddings
> from langchain.text_splitter import CharacterTextSplitter
> from langchain.vectorstores import FAISS
> 
> # Load the text document
> loader = PyMuPDFLoader("path/to/file.pdf")
> documents = loader.load()
> 
> # Split the document into chunks
> text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
> docs = text_splitter.split_documents(documents)
> docs_as_str = [doc.page_content for doc in docs]
> # Generate the embeddings
> embeddings = OpenAIEmbeddings()
> embedded_docs = embeddings.embed_documents(docs_as_str)
> 
> 
> # Initialize FAISS
> db = FAISS.from_documents(embedded_docs, embeddings)
> 
> # Perform a similarity search between the embedding of the query and the embeddings of the documents
> query = "Your query here"
> similar_docs = db.similarity_search(query)
> 
> # Print the content of the most similar document
> print(similar_docs[0].page_content)
> ```
