### ISSUE TITLE
installing pip install langchain[all] installs the old version of langchain 0.0.39 

### ISSUE THREAD

**Issue by khanakia** [langchain-ai/langchain#8298]
### System Info

When i install for the first time using this command
```
pip install 'langchain[all]'
```
It installs the older version `langchain 0.0.39` 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. pip install 'langchain[all]'

### Expected behavior

It should install the latest version of langchain

**Comment by dmyoung9** [comment]
@khanakia How about with the `-U` flag?

`pip install -U langchain[all]`
