### ISSUE TITLE
VertexAI using `text-bison` returns no output

### ISSUE THREAD

**Issue by thehunmonkgroup** [langchain-ai/langchain#8304]
### System Info

Pop!_OS 22.04 LTS
Python 3.11.4
Langchain v0.0.242

### Who can help?

@hwchase17 
@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`code-bison` works fine, `text-bison` returns no output. I've got full `Vertex AI User` perms, and every other model, including the chat models work fine in my config.

```
>>> from langchain.llms.vertexai import VertexAI
>>> llm = VertexAI(model_name="code-bison")
>>> llm("say hello")
'Hello! How are you doing today?'
>>> llm = VertexAI(model_name="text-bison")
>>> llm("say hello")
''
>>>
```

### Expected behavior

`text-bison` should return content.

**Comment by wnmurphy** [comment]
I'm seeing this intermittently as well, followed by a 400 "no content" from PaLM. Using `text-bison@001` as well.

When I route to a different chain with the same model, same memory, but different prompt, it resolves.

It also seems to occur based on topic, which for me is health. I wonder if that safety attribute threshold is being triggered on Google's end, and either LC or my code isn't handling it properly

**Comment by wnmurphy** [comment]
For posterity, this had two causes:
1. We were using a "parroting trimmer" output parser to strip any artifacts that come from injecting a chat history into a prompt for a text model, like "AI: AI: AI: AI: How's it going? Human: Oh fine" etc. It was occasionally trimming the entire prediction response.
2. Google's safety thresholds are triggered, resulting in an error code that isn't accessible to LangChain, but returning an empty response.
