### ISSUE TITLE
ImportError: cannot import name 'ApifyWrapper' from 'langchain.utilities'

### ISSUE THREAD

**Issue by achilela** [langchain-ai/langchain#8307]
### System Info

Hi All,
I tried to run Apify tutorial and I ran on the issue of ImportError: cannot import name 'ApifyWrapper' from 'langchain.utilities'. I checked the Utilities library under utilities/__init__.py and I couldn't find anything under the Generic integrations with third-party systems and packages.
Any thoughts or support?

### Who can help?

@hwchase17, @agola

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import os

openai.api_key = os.environ["OPEN_API_KEY"]
os.environ["APIFY_API_TOKEN"] = "apify_api_qNa00bcYGUYFwIZltWiOuhskmer7E61VE6GN"

apify = ApifyWrapper()

loader = apify.call_actor(
    actor_id="apify/website-content-crawler",
    run_input={"startUrls": [{"url": "https://python.langchain.com/en/latest/"}]},
    dataset_mapping_function=lambda item: Document(
        page_content=item["text"] or "", metadata={"source": item["url"]}
    ),
)
index = VectorstoreIndexCreator().from_loaders([loader])

query = "What is LangChain?"
result = index.query_with_sources(query)

print(result["answer"])
print(result["sources"])

### Expected behavior

LangChain is a standard interface through which you can interact with a variety of large language models (LLMs). It provides modules that can be used to build language model applications, and it also provides chains and agents with memory capabilities.
    
https://python.langchain.com/en/latest/modules/models/llms.html, https://python.langchain.com/en/latest/getting_started/getting_started.html

**Comment by achilela** [comment]
Still not working. No ApifyWrapper in any of the libraries 
![Screenshot from 2023-07-26 21-06-24](https://github.com/langchain-ai/langchain/assets/112531858/01e5076f-fd80-40be-a066-35617eb5d93e)

**Comment by biraj21** [comment]
you can try this out:

```python
import os

from apify_client import ApifyClient
from langchain.document_loaders.base import Document
from langchain.document_loaders import ApifyDatasetLoader
from langchain.indexes import VectorstoreIndexCreator

os.environ["OPENAI_API_KEY"] = "Your OpenAI API key"

apify_client = ApifyClient("Your Apify token")

actor_call = apify_client.actor("apify/website-content-crawler").call(
    run_input={"startUrls": [{"url": "https://python.langchain.com/en/latest/"}]},
)

loader = ApifyDatasetLoader(
    dataset_id=actor_call["defaultDatasetId"],
    dataset_mapping_function=lambda item: Document(
        page_content=item["text"] or "", metadata={"source": item["url"]}
    ),
)

# Initialize the vector database with the text documents:
index = VectorstoreIndexCreator().from_loaders([loader])

# Finally, query the vector database:
query = "What is LangChain?"
result = index.query_with_sources(query)
print(result["answer"])
print(result["sources"])
```

**Comment by hinthornw** [comment]
Hm yeah it seems like ApifyWrapper was never added / doesn't exist

**Comment by scenaristeur** [comment]
https://python.langchain.com/docs/integrations/tools/apify should be fixed

**Comment by AniketMishra23** [comment]
https://youtu.be/zcfeiVdiGJg
Guys check this out.

**Comment by simpleappdesigner** [comment]
> https://youtu.be/zcfeiVdiGJg Guys check this out.

this video was made with langchain==0.0.187 and was working at that time. so one way is install that version of langchain !pip install langchain==0.0.187

**Comment by AbdullahHabib-github** [comment]
@hwchase17 @baskaryan I have got an experience of over 3 years with Python development.  I want to help, please assign this issue to me.

**Comment by jirimoravcik** [comment]
Fixed in https://github.com/langchain-ai/langchain/pull/10067

**Comment by eyurtsev** [comment]
@achilela your original POST had a secret for APIFY which is marked as still active by github. Please disable this secret ASAP.
