### ISSUE TITLE
SagemakerEndpoint LLM does not support InvokeEndpoint CustomAttributes needed for Llama-V2

### ISSUE THREAD

**Issue by sarthak10193** [langchain-ai/langchain#8326]
### Feature request

Add support for passing CustomAttributes to the `SagemakerEnpiontLLM` wrapper around `client.invoke_enpoint()`
With the release of LLama-v2 on Sagemaker Jumpstart, we are required to pass EULA=TRUE # END USER LICENSE AGREEMENT

Endstate
```python 

class SagemakerEndpoint(LLM):
       ...
       ...
       custom_attributes: Dict

      
       custom_attributes = 
       # send request
       try:
            response = self.client.invoke_endpoint(
                EndpointName=self.endpoint_name,
                Body=body,
                ContentType=content_type,
                Accept=accepts,
                Custom_Attributes=self.custom_attributes
                **_endpoint_kwargs,
            )
       except Exception as e:
            raise ValueError(f"Error raised by inference endpoint: {e}")
```

### Motivation

Lanchain is incompatible with llama-v2 model using SagemakerEnpointLLM in langchain

without the fix, Lanchain throws an error

`Unknown parameter in input: "accept_eula", must be one of: EndpointName, Body, ContentType, Accept, CustomAttributes, TargetModel, TargetVariant, TargetContainerHostname, InferenceId, EnableExplanations`

### Your contribution

Happy to create a PR

**Comment by david-watkins-se** [comment]
You can provide the custom attribute in the `endpoint_kwargs` argument for `SagemakerEndpoint`; e.g. `endpoint_kwargs={"CustomAttributes": "accept_eula=true"},`

**Comment by gandalf-repo** [comment]
[this example](https://python.langchain.com/docs/integrations/llms/sagemaker) doesn't run for me and throws error

even after adding     endpoint_kwargs={"CustomAttributes": "accept_eula=true"} to ContentHandler

ModelError                                Traceback (most recent call last)
File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/langchain/llms/sagemaker_endpoint.py:237](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/langchain/llms/sagemaker_endpoint.py:237), in SagemakerEndpoint._call(self, prompt, stop, run_manager, **kwargs)
    236 try:
--> 237     response = self.client.invoke_endpoint(
    238         EndpointName=self.endpoint_name,
    239         Body=body,
    240         ContentType=content_type,
    241         Accept=accepts,
    242         **_endpoint_kwargs,
    243     )
    244 except Exception as e:

File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:535](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:535), in ClientCreator._create_api_method.._api_call(self, *args, **kwargs)
    534 # The "self" in this scope is referring to the BaseClient.
--> 535 return self._make_api_call(operation_name, kwargs)

File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:980](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:980), in BaseClient._make_api_call(self, operation_name, api_params)
    979     error_class = self.exceptions.from_code(error_code)
--> 980     raise error_class(parsed_response, operation_name)
    981 else:

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
  "code":424,
  "message":"prediction failure",
...
ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
  "code":424,
  "message":"prediction failure",
  "error":"'inputs'"
}"

**Comment by thuandoan-hcl** [comment]
> [this example](https://python.langchain.com/docs/integrations/llms/sagemaker) doesn't run for me and throws error
> 
> even after adding endpoint_kwargs={"CustomAttributes": "accept_eula=true"} to ContentHandler
> 
> ModelError Traceback (most recent call last) File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/langchain/llms/sagemaker_endpoint.py:237](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/langchain/llms/sagemaker_endpoint.py:237), in SagemakerEndpoint._call(self, prompt, stop, run_manager, **kwargs) 236 try: --> 237 response = self.client.invoke_endpoint( 238 EndpointName=self.endpoint_name, 239 Body=body, 240 ContentType=content_type, 241 Accept=accepts, 242 **_endpoint_kwargs, 243 ) 244 except Exception as e:
> 
> File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:535](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:535), in ClientCreator._create_api_method.._api_call(self, *args, **kwargs) 534 # The "self" in this scope is referring to the BaseClient. --> 535 return self._make_api_call(operation_name, kwargs)
> 
> File [~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:980](https://file+.vscode-resource.vscode-cdn.net/Users/arvi/DevDynamics/collabs/~/DevDynamics/collabs/sagemaker_endpoint_venv/lib/python3.9/site-packages/botocore/client.py:980), in BaseClient._make_api_call(self, operation_name, api_params) 979 error_class = self.exceptions.from_code(error_code) --> 980 raise error_class(parsed_response, operation_name) 981 else:
> 
> ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{ "code":424, "message":"prediction failure", ... ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{ "code":424, "message":"prediction failure", "error":"'inputs'" }"

I had the same issue. Did you overcome this? Can you share your solution?

Thank you

**Comment by abasu0713** [comment]
any update on this one? I am getting the same error. for llama2.
`ValueError: Error raised by inference endpoint: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (424) from primary with message "{
  "code":424,
  "message":"prediction failure",
  "error":"Need to pass custom_attributes='accept_eula=true' as part of header. This means you have read and accept the end-user license agreement (EULA) of the model. EULA can be found in model card description or from https://ai.meta.com/resources/models-and-libraries/llama-downloads/."
}"`

**Comment by jaotheboss** [comment]
@abasu0713 as @david-watkins-se replied, you can pass custom attributes under the endpoint kwargs argument as such:

`endpoint_kwargs={"CustomAttributes": "accept_eula=true"}`

**Comment by simpleverso** [comment]
And how to use it in batch transform??
