### ISSUE TITLE
[Feature] Improvements in ElasticVectorStore

### ISSUE THREAD

**Issue by yasha-dev1** [langchain-ai/langchain#834]
Hey, here are some proposals on improvements in ElasticVectorStore. I have forked the project already and made some basic changes to fit ElasticVectorStore to my needs. You can see the commits in here: 
https://github.com/hwchase17/langchain/compare/master...yasha-dev1:langchain:master
Still I will have to write unit tests for it and test it more thoroughly. 
However these are the implementations that I have already done:
1. Added https connection and basic Auth for connection to elasticsearch. I have to Add `ElasticConf` in order to incorporate Auth settings into the library because Elasticsearch is suppoused to be an optional dep
2. Added Filter for all types of `VectorStores` due to the fact that for large scale data, Ann would be really slow and in most of my use cases, I need to fetch the similarity in a filtered context. I have added filter for the metadata that gets saved on to vector store in order to filter the data before performing similarity search. (Its already implemented by most of the vector stores, so its as easy as changing the query)
3. Added `setup_index` in order for the client, to specify the schema structure of the data saved there (aka metadata). For example in my use case, I didn't want to index some specific metadata in elasticsearch, that's why I needed to specify my own data mapping. But also some mapping logic depends on the lib, so best would be that the client passes the metadata schema structure to each `VectorStore` so that they get created if it doesn't exist.

_Note: All of the above suggested features are already implemented in the mentioned commits, However I will have to do more thourough testing. And It would be nice to get a feedback if this doesn't meet some of your lib's rules, Because the overall interface of `VectorStore` has been changed significantly. these are only my needs that I implemented, But it would be cool for you guys to review, and potentially, if I have done more tests, I can make a PR_

**Comment by hwchase17** [comment]
i think it probably depends on how significantly the interface is changed - if you want to open a pr im happy to review. can even just be a draft/rfc pr
