### ISSUE TITLE
Playwright Browser Tools: add screenshot feature

### ISSUE THREAD

**Issue by juan-abia** [langchain-ai/langchain#8347]
### Feature request

The Playwright toolkit is awesome. But it would be great to be able to see what the agent is doing. We could add a feature that takes screenshoots of the current state of the web page

### Motivation

It feels strange to use the toolkit but being blind, we cannot see what the agent is doing. The original idea is that by taking screenshoot we could use agents to perform UI testing.

### Your contribution

I could help writing a PR, but I’ll need help from the Playwright community. I also want to know what the community thinks of this feature.

**Comment by ishish222** [comment]
Hello @juan-abia. Are you still considering implementing this? I will need it in my project so I'd be glad to help. It seems even more relevant now with projects around agentic computer use such as WebVoyager or Anthropic's Quick Start Computer Use Demo and the last I checked the Playwright toolkit in langchain_community package does not support visual content is results
