### ISSUE TITLE
Custom tool return_direct except when a ToolException occurs.

### ISSUE THREAD

**Issue by EB1811** [langchain-ai/langchain#8348]
### Feature request

Some kind of possibility to make a custom tool with return direct not do so when faced with a error such as a ToolException.

### Motivation

Currently, when a tool with return_direct faces a handled error, it returns the error directly. I would want a tool to return an output directly but only if there are no errors, since the errors aren't useful to be directly returned.

### Your contribution

I am not sure how this could be implemented, but would gladly help working on any ideas. Found this issue which would also enable this https://github.com/langchain-ai/langchain/issues/8306

**Comment by harkrish1** [comment]
Any solution for this?
