### ISSUE TITLE
GCP Matching Engine support for public index endpoints

### ISSUE THREAD

**Issue by danielfrg** [langchain-ai/langchain#8378]
### System Info

langchain==0.0.244

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Create a new Matching Engine Index Endpoint that is public.

Follow the tutorial to make a similarity search:

```
vector_store = MatchingEngine.from_components(
    project_id="",
    region="us-central1",
    gcs_bucket_name="",
    index_id="",
    endpoint_id="",
    embedding=embeddings,
)

vector_store.similarity_search("what is a cat?", k=5)
```

Error:

```

File ~/code/gcp-langchain-retrieval-augmentation/embeddings/.venv/lib/python3.9/site-packages/grpc/_channel.py:1030, in _UnaryUnaryMultiCallable.__call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
   1021 def __call__(self,
   1022              request: Any,
   1023              timeout: Optional[float] = None,
   (...)
   1026              wait_for_ready: Optional[bool] = None,
   1027              compression: Optional[grpc.Compression] = None) -> Any:
   1028     state, call, = self._blocking(request, timeout, metadata, credentials,
   1029                                   wait_for_ready, compression)
-> 1030     return _end_unary_response_blocking(state, call, False, None)

File ~/code/gcp-langchain-retrieval-augmentation/embeddings/.venv/lib/python3.9/site-packages/grpc/_channel.py:910, in _end_unary_response_blocking(state, call, with_call, deadline)
    908         return state.response
    909 else:
--> 910     raise _InactiveRpcError(state)

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed for :10000: unparseable host:port"
	debug_error_string = "UNKNOWN:DNS resolution failed for :10000: unparseable host:port {created_time:"2023-07-27T20:12:23.727315699+00:00", grpc_status:14}"
>
```

### Expected behavior

It should be possible to do this. The VertexAI Python SDK supports it with the `endpoint.find_neighbors` function.

I think just changing [the wrapper](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/matching_engine.py#L178) from `.match` to `.find_neighbors` for when the endpoint is public should do it.

**Comment by neeraj-mahapatra** [comment]
I am also facing same error

**Comment by UmerQam** [comment]
I am also facing same issue, how to overcome this @neeraj-mahapatra @danielfrg

**Comment by bbowler86** [comment]
I am also facing the same error when trying to run a similarity search

**Comment by rjimr** [comment]
I am also facing same issue. Team - Could you please fix this ? any ETA on this issue.

**Comment by Elnino0009** [comment]
Please solve this soon.

**Comment by bourliam** [comment]
Hi all !
Just faced the same issue, and followed @danielfrg 's idea : I copied the file in local and changed the ".match()" to ".find_neighbors()"  line 177 and it works.

**Comment by joaquinmenendez** [comment]
> Hi all ! Just faced the same issue, and followed @danielfrg 's idea : I copied the file in local and changed the ".match()" to ".find_neighbors()" line 177 and it works.

Confirm that this works. I think that an easy work around is to check if the endpoint is public or private. (maybe assign that as a class attribute) and inside 'similarity_search´ check for it. According to the endpoint type call a method or another one. 
Don't think is the most elegant but could it work.

**Comment by xiaoyaoyang** [comment]
still seeing the error with 1.34 version aiplatform.
