### ISSUE TITLE
RetrievalQA: Submit different queries to Retriever and LLM

### ISSUE THREAD

**Issue by amw5g** [langchain-ai/langchain#8380]
### Feature request

This is related to [HyDE](https://python.langchain.com/docs/modules/chains/additional/hyde).  But I feel my feature request puts the HyDE example in a more realistic context, and naturally extends the RetrievalQA chain.

My suggestion would be allow the text passed to the retriever to be different from the query passed to the LLM.  This would be useful as fallback when the original query, as provided by the user, yields a response of "I don't know" from the LLM; or if it returns no or poor-scoring documents during the retrieval step.

Step 1, Embed original query
Step 2, retrieve candidate documents based on embedded original query
Step 3, pass original query & retrieved documents to LLM for answer
If Step 2 yields 0/low score documents OR Step 3 yields no/low confidence answer...
Step 4, generate an alternate _hypothetical_ answer (i.e., as described in [HyDE](https://arxiv.org/abs/2212.10496)
Step 5, embed  _hypothetical_ answer
Step 6, retrieve candidate documents based on embedded  _hypothetical_ answer
Step 7, pass original query & _newly_ retrieved documents to LLM for answer

### Motivation

Perhaps I have a query that does not yield good retrieval documents from my main knowledgebase corpus.  It is poorly formed, it has spelling errors, it is vague, it is brief.  Even though the corpus does contain the factual answer to the intent of the query.  Instead, a different form of the original query would yield better retrieved documents, and therefore produce the correct & complete answer desired.

For example, very simple questions like "Who's Character X?" may yield a wide range of sub-optimal documents from a QA Retriever.  As a result, the LLM's response may be muddled or impossible to generate.

### Your contribution

Happy to refine the suggestion and provide concrete examples.

**Comment by richardw0ng** [comment]
I have a question about this issue.
Is it possible to rewrite a broad, incorrect, or ambiguous query into an accurate one through a query based on historical data, thus completing the task you described

**Comment by amw5g** [comment]
> I have a question about this issue. Is it possible to rewrite a broad, incorrect, or ambiguous query into an accurate one through a query based on historical data, thus completing the task you described

That seems like a neat idea.  And definitely worth exploring.  

It is unclear to me if my user base is large enough as to generate different versions of the same question over time.  If not, then it's not going to work.  I suppose I should also look into having the LLM ask clarifying questions before attempting to answer.

But for now, I'd like to explore the possibility of generating a hypothetical user input that successfully retrieves context documents as an extension of the RetrievalQA chain.
