### ISSUE TITLE
Questions Regarding load_summarize_chain Implementation and LLM Models Usage

### ISSUE THREAD

**Issue by geetansh** [langchain-ai/langchain#8399]
### Issue you'd like to raise.

Hello, I'm currently using the load_summarize_chain function to summarize extensive documents, specifically those about 250 pages or more. In this process, I'm employing the map_reduce chain type along with a custom prompt.

The process works as follows:

In the initial step, the chain sends parallel requests to LLM to summarize chunks of data.
Upon receiving all responses, the summary chain collects them, combines them into a single prompt, and generates the final output.

I'm curious about two aspects of this process:
In the second step, the chain employs the StuffDocumentsChain method to create the final summary despite setting mapreduce in chaintype. Is it possible to use an alternative chain type for this? If yes, could you recommend any?

Would it be feasible to utilize different Language Learning Models (LLMs) in the two steps? For instance, could I use GPT3.5 for the first step and GPT4 for generating the final summary?

I appreciate your help and look forward to your response.

Thanks in advance!

**Comment by klein-t** [comment]
Hello mate, just randomly came across this issue, is a bit late, but maybe can be helpful for someone.

If you pass to just the `llm` argument to the `load_summarize_chain`, then it will use such LLM for both steps, however you can also set the `reduce_llm` parameter to use such LLM in the reduce step.

Here is an example:
`map_llm = ChatOpenAI(model_name=model_name)
reduce_llm = ChatOpenAI(model_name=model_name, temperature=0.5)
chain = load_summarize_chain(
        llm=map_llm,
        reduce_llm = reduce_llm,
        chain_type="map_reduce",
        return_intermediate_steps=True,
        map_prompt=map_prompt,
        combine_prompt=combine_prompt,
    )
`

As for the second chain type, that is used to prevent context length limits, I guess you can change it for sure, but I'm not aware if there's an easy way.

Hope it was helpful for someone c:
