### ISSUE TITLE
Add more CodeSegmenters

### ISSUE THREAD

**Issue by Middleman3** [langchain-ai/langchain#8405]
### Feature request

I'm interested in the code segmenters created. So far we have python and javascript. I'm looking for a typescript one in particular, the JS one marks my typescript as invalid. But in general, having the language support shown in the text splitter Language enum would be ideal but with full on parsing. 

### Motivation

This call is ok to start: 
`RecursiveCharacterTextSplitter.get_separators_for_language(Language.JS)`
but when we're splitting by the word function we're cutting off `export async` or `default`, and especially JsDoc, which is probably the best think to start a chunk of a function with. 

Splitting by keywords like this is kinda clunky as a long term solution because of the above cases and others, having something that's more carefully splitting files up would be better. 

### Your contribution

Maybe instead of a parser like eprisma, there's just a generic one that's powered by an LLM.

**Comment by Harrolee** [comment]
Check out this [issue 11229](https://github.com/langchain-ai/langchain/issues/11229).
