### ISSUE TITLE
Issue: prefix `Use ` being added to agent action causing InvalidTool to be invoked again and again

### ISSUE THREAD

**Issue by mrvaruntandon** [langchain-ai/langchain#8407]
### Issue you'd like to raise.

I have added the tools named A_tool, default_tool  to a `ZeroShotAgent`.

The output from one of the execution looks like:

```
Thought: We need to use the A_tool.
Action: Use A_tool
Observation: Use A_tool is not a valid tool, try another one.
Thought:We need to use the default_tool since A_tool is not a valid tool.
    
Action: Use default_tool
Action Input: None
Observation: Use default_tool is not a valid tool, try another one.
```

I am not sure why the prefix `Use ` is getting added to Action.....ideally action should be just the name of the tool [`A_tool`,` default_tool`]

This is causing InvalidTool to be invoked again and again.

What can i do to fix this issue?

**Comment by mrvaruntandon** [comment]
https://stackoverflow.com/questions/76785286/prefix-use-being-added-to-agent-action-causing-invalidtool-to-be-invoked-agai

**Comment by Avinash-Raj** [comment]
Anything wrong with https://github.com/langchain-ai/langchain/issues/1559#issuecomment-1483791903 ?

**Comment by asagarw** [comment]
@mrvaruntandon Did you get a workaround this problem?

**Comment by mrvaruntandon** [comment]
What I found for my usecase was the name of the tool is as important as the description of the tool. 

I removed `_tool` from my tool names and made it more meaningful. I would suggest using a noun for tool name.

Also, I observed that altering the [`FORMAT_INSTRUCTION`](https://github.com/langchain-ai/langchain/blob/a2d30428237695f076060dec881bae0258123775/libs/langchain/langchain/agents/mrkl/prompt.py#L7) while creating an agent also helps. 

I changed `Action: the action to take, should be one of [{tool_names}]` to `Action: the action to take, should be only one of the values from [{tool_names}] list`

**Comment by mrvaruntandon** [comment]
> Anything wrong with [#1559 (comment)](https://github.com/langchain-ai/langchain/issues/1559#issuecomment-1483791903) ?

I have not tried with `chat-zero-shot-react-description` for my usecase.
