### ISSUE TITLE
Issue: LangChain is fairly consistently dropping the first one or two characters of the chain answer.

### ISSUE THREAD

**Issue by KuuCi** [langchain-ai/langchain#8413]
### Issue you'd like to raise.

My Chatbot is fairly straight forward. It uses MosaicMLInstructorEmbeddings() as the embedding and MosaicML() as the model. I have a file that I want to retrieve from. When outputting an answer, for instance:

What is AliBi?

It will give a response like:

Answer: LiBi (Attention with Linear Biases) dispenses with position embeddings for tokens in transformer-based NLP models, instead encoding position information by biasing the query-key attention scores proportionally to each token pair’s distance. ALiBi yields excellent extrapolation to unseen sequence lengths compared to other position embedding schemes. We leverage this extrapolation capability by training with shorter sequence lengths, which reduces the memory and computation load. 

Or when I give it:

Answer: arded checkpointing is a feature in distributed systems that allows for the checkpointing of the state of the system to be divided into multiple shards. This is useful for systems that have a large amount of data or compute to perform. 

I have noticed that the chatbot fairly consistently drops the first or first two characters and I'm wondering if this is a bug with LangChain, MosaicMLInstructorEmbeddings, or MosaicML.

Here is my chatbot file:
https://github.com/KuuCi/examples/blob/support-bot/examples/end-to-end-examples/support_chatbot/chatbot.py

**Comment by KuuCi** [comment]
I'm using MosaicMLInstructorEmbeddings and MosaicML(), where in MosaicML I set 'output_len': 40 tokens, which should be enough

**Comment by janpawellek** [comment]
Thank you for opening this @KuuCi 
I have the same issue with an LLMChain.

**Comment by hinthornw** [comment]
Is the output fine if you pass the prompt directly into the LLM? This kind of thing is pretty common with certain types of tokenization

**Comment by KuuCi** [comment]
I wouldn’t be terribly surprised if it was a tokenizer issue. I have passed the query + sources obtained by langchain into the llm and it looks fine

**Comment by KuuCi** [comment]
Actually I don't believe it is a tokenizer issue since I fed the source_documents + query into the model raw and the output was fine.

**Comment by KuuCi** [comment]
Bug was solved! The culprit was the following line:
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/llms/mosaicml.py#L192

Basically, when the tokenizer tokenizes a string, any space before a punctuation would be removed as it is "non-sensical". For instance, let's say 

tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
encoded_prompt = tokenizer.encode("hello !", add_special_tokens=False)
decoded_prompt = tokenizer.decode(encoded_prompt, skip_special_tokens=False)

decoded_prompt would be "hello!", not "hello !". 

A hacky roundabout way of getting around this error would be:
tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
encoded_prompt = tokenizer.encode(prompt, add_special_tokens=False)
decoded_prompt = tokenizer.decode(encoded_prompt, skip_special_tokens=False)
text = text[len(decoded_prompt) :]
