### ISSUE TITLE
Huggingface_Pipeline for summarization returning generalized response

### ISSUE THREAD

**Issue by AjinkyaBankar** [langchain-ai/langchain#8444]
### System Info

Python = 3.9
Langchain = 0.0.245

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I checked the recent update for summarization pipeline with memory as:
```
from langchain.llms import HuggingFacePipeline
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, pipeline
from langchain.memory import ConversationSummaryBufferMemory
import torch

summarize_model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn", device_map="auto", torch_dtype=torch.bfloat16, trust_remote_code=True)
summarize_tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn", padding_side="left")
pipe_summary = pipeline("summarization", model=summarize_model, tokenizer=summarize_tokenizer) #, max_new_tokens=500, min_new_tokens=300

hf_summary = HuggingFacePipeline(pipeline=pipe_summary)
memory=ConversationSummaryBufferMemory(llm=hf_summary, max_token_limit=10)
```
Then, added chat history to the memory and observed the memory afterwards as:
```
memory.save_context({"input": "hi"}, {"output": "whats up"})
memory.save_context({"input": "not much you"}, {"output": "not much"})
memory.save_context({"input": "what's my name"}, {"output": "AJ"})

memory.load_memory_variables({})
```
It returned:
```
{'history': "System: The human asks what the AI thinks of artificial intelligence. The AI thinks artificial intelligence is a force for good because it will help humans reach their full potential. Progressively summarize the lines of conversation provided, adding onto the previous summary returning a new summary. The human asks the AI: Why do you think artificial Intelligence is a Force for good? The AI: Because artificial intelligence will help human reach their potential.\nHuman: what's my name\nAI: AJ"}
```
This doesn't summarize the actual chat history, but returns a generalized text: `The human asks what the AI thinks of artificial intelligence. The AI thinks artificial intelligence is a force for good because it will help humans reach their full potential. Progressively summarize the lines of conversation provided, adding onto the previous summary returning a new summary. The human asks the AI: Why do you think artificial Intelligence is a Force for good? The AI: Because artificial intelligence will help human reach their potential.`

### Expected behavior

This would pass wrong prompt to the LLM for question-answering. The expectation is the summary of the chat history.

**Comment by AjinkyaBankar** [comment]
This is not helpful, bot. Can someone take a look at this issue?

**Comment by devstein** [comment]
@AjinkyaBankar Per the bot's message, do you get different results by using a different model? If so, it might be that 
- the default prompts are not suitable for the `facebook/bart-large-cnn` model
-  `facebook/bart-large-cnn` is not suitable for summarization

**Comment by AjinkyaBankar** [comment]
@devstein I tried with `sshleifer/distilbart-cnn-12-6` and `t5-small` models. But observing the same behavior. Any recommendation for choosing the model?

**Comment by devstein** [comment]
I don't have specific model recommendations, but would imagine the more recent LLM/transformer based models will perform better

**Comment by AjinkyaBankar** [comment]
@devstein It worked as expected for the recent models, such as `marianna13/flan-t5-base-summarization` and `ArtifactAI/flan-t5-base-arxiv-cs-ml-question-answering`. Thanks for taking time to answer my question.
