### ISSUE TITLE
GooglePalm requires google.generativeai?

### ISSUE THREAD

**Issue by hemanth** [langchain-ai/langchain#8449]
### System Info

```python
from langchain.llms.base import LLM
from langchain.llms import GooglePalm
```

This throws an error saying it requires `google.generativeai`; pervious it used to work, something changed and is it documented? 

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
pip install langchain
```

```python
from langchain.llms.base import LLM
from langchain.llms import GooglePalm
```

### Expected behavior

Should load without errors?

**Comment by dmyoung9** [comment]
`pip install google-generativeai`

**Comment by hemanth** [comment]
Yup, but that was not required previously.

**Comment by Akashhverma** [comment]
Hey I am trying to import google palm from langchain using  
pip install langchain transformers streamlit python-dotenv pandas
pip install google-generativeai
from langchain.llms.base import LLM
from langchain.llms import GooglePalm    

## i am getting an error   
ModuleNotFoundError: No module named 'langchain_community'    

please help me out
