### ISSUE TITLE
VectorStore.from_documents() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by lud-hu** [langchain-ai/langchain#8457]
### System Info

... % python --version                
Python 3.11.4
... % pip show langchain | grep Version
Version: 0.0.247

### Who can help?

@eyurtsev

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

When following the langchain docs [here](https://python.langchain.com/docs/integrations/vectorstores/qdrant#qdrant-cloud), there will be an error thrown:

```py
qdrant = Qdrant.from_documents(
    docs,
    embeddings,
    url,
    prefer_grpc=True,
    api_key=api_key,
    collection_name="test",
)
```

error:
```
Traceback (most recent call last):
  File "...myscript.py", line 29, in <module>
    qdrant = Qdrant.from_documents(
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: VectorStore.from_documents() takes 3 positional arguments but 4 were given
```

Is it related to https://github.com/langchain-ai/langchain/pull/7910 ?

### Expected behavior

QDrant being initialized properly.

**Comment by DonovanKelly** [comment]
It looks like that documentation is out of date.
`from_documents` expects positional args `cls, documents, embeddings`. You can see that [here](https://github.com/langchain-ai/langchain/blob/13b4f465e2e67451549dc0662495ae07b3530659/libs/langchain/langchain/vectorstores/base.py#L413) 
`from_documents` calls the abstract method `from_texts` and you see that implementation [here](https://github.com/langchain-ai/langchain/blob/13b4f465e2e67451549dc0662495ae07b3530659/libs/langchain/langchain/vectorstores/qdrant.py#L959C3-L959C3) 
If you take a look at the method Qdrant.from_texts, you'll see url is a keyworded argument. Your code should work if you rewrite it like this:

```
qdrant = Qdrant.from_documents(
    docs,
    embeddings,
    url=url, # <-------
    prefer_grpc=True,
    api_key=api_key,
    collection_name="test",
)
```

**Comment by lud-hu** [comment]
Thanks @DonovanKelly !
It works perfectly now.
I've created a PR for adapting the docs.
