### ISSUE TITLE
unsupported operand type(s) for +: 'SystemMessage' and 'HumanMessage'

### ISSUE THREAD

**Issue by qingtian1771** [langchain-ai/langchain#8472]
### System Info

Langchain version: 0.0.247
python version: 3.11.0

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

You can reproduce this issue according following link:
https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/prompts_pipelining

```
from langchain.prompts import ChatPromptTemplate, HumanMessagePromptTemplate
from langchain.schema import HumanMessage, AIMessage, SystemMessage

prompt = SystemMessage(content="You are a nice pirate")

new_prompt = (
    prompt
    + HumanMessage(content="hi")
    + AIMessage(content="what?")
    + "{input}"
)
```
prompy + HumanMessage(content="hi") will generate this issue

### Expected behavior

operand + for 'SystemMessage' and 'HumanMessage' should be support

**Comment by godpeny** [comment]
Same Issue for me.

**Comment by keenborder786** [comment]
@qingtian1771 having a look at the issue.

**Comment by eyurtsev** [comment]
I'll revert the change that broke this functionality tomorrow -- need to re-add `__add__` functionality on BaseMessage class. 

In the meantime you can do this: 

```python

from langchain.prompts import ChatPromptTemplate

new_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a nice pirate"),
        ("human", "hi"),
        ("ai", "what?"),
        ("human", "{input}"),
    ],
)
```

**Comment by keenborder786** [comment]
@qingtian1771 another way of doing the same thing until `__add__` functionality gets reverted

```python
from langchain.prompts import HumanMessagePromptTemplate,ChatPromptTemplate
from langchain.schema import HumanMessage, AIMessage, SystemMessage
messages = [
    SystemMessage(content="You are a nice pirate"),
    ,HumanMessage(content="hi")
    ,AIMessage(content="what?")
    ,HumanMessagePromptTemplate.from_template("{input}")
]
prompt = ChatPromptTemplate.from_messages(messages=messages)
prompt.format_messages(input='I said hi.')
```
