### ISSUE TITLE
no support for loading 70B models via llamacpp

### ISSUE THREAD

**Issue by yairVanti** [langchain-ai/langchain#8486]
### System Info

LangChain 0.0.242

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

tried to load https://huggingface.co/TheBloke/StableBeluga2-70B-GGML model to work with lanchain's Llamacpp : 

`llm = LlamaCpp(model_path="./stablebeluga2-70b.ggmlv3.q4_0.bin", n_gpu_layers=n_gpu_layers,
 n_batch=n_batch, n_ctx=8192, input={"temperature": 0.01},n_threads=8)
llm_chain = LLMChain(llm=llm, prompt=prompt)`

i see that there is no support in passing  n_gqa=8 parameter that according to [https://github.com/abetlen/llama-cpp-python](https://github.com/abetlen/llama-cpp-python) should be used for 70B models
the error i get is :
error loading model: llama.cpp: tensor 'layers.0.attention.wk.weight' has wrong shape; expected  8192 x  8192, got  8192 x  1024

### Expected behavior

model should be loaded successfuly

**Comment by william-incode** [comment]
+1 I'm having the same issue, the n_gqa arg is not working in `LlamaCpp`

**Comment by ankuratudemy** [comment]
This was merged 5 hours ago: https://github.com/ggerganov/llama.cpp/pull/2459

**Comment by ankuratudemy** [comment]
embeddings = LlamaCppEmbeddings(model_path="..../llama-2-70b.ggmlv3.q4_0.bin", **n_gqa=8**)

Support for n_gqa added in : https://github.com/abetlen/llama-cpp-python/issues/539
