### ISSUE TITLE
RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by screwyforcepush** [langchain-ai/langchain#8494]
### System Info

python 3.11

### Who can help?

@rlancemartin 
File langchain/document_loaders/async_html.py:136-->  results = asyncio.run(self.fetch_all(self.web_paths))

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.retrievers.web_research import WebResearchRetriever

import pinecone
import os
from langchain.vectorstores import Pinecone
from langchain.utilities import GoogleSearchAPIWrapper
from common_util.llms import LLM_FACT, EMBEDDINGS
from dotenv import load_dotenv
from common_util.namespaceEnum import PineconeNamespaceEnum

load_dotenv()
index_name = "langchain-demo"

pinecone.init(api_key=os.getenv("PINECONE_API_KEY"), environment=os.getenv("PINECONE_ENV"))

# Vectorstore
vectorstore = Pinecone.from_existing_index(index_name, EMBEDDINGS, namespace=PineconeNamespaceEnum.WEB_SEARCH.value)

# LLM
llm = LLM_FACT

# Search 
os.environ["GOOGLE_CSE_ID"] = os.getenv("GOOGLE_CSE_ID")
os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_API_KEY")
search = GoogleSearchAPIWrapper()

web_research_retriever = WebResearchRetriever.from_llm(
    vectorstore=vectorstore,
    llm=llm, 
    search=search, 
)

from langchain.chains import RetrievalQAWithSourcesChain
user_input = "How do LLM Powered Autonomous Agents work?"
qa_chain = RetrievalQAWithSourcesChain.from_chain_type(llm,retriever=web_research_retriever)
result = qa_chain({"question": user_input})
result

### Expected behavior

should search the web async

**Comment by rlancemartin** [comment]
Yes, one other user reported this w/ Jupyter lab. 

I never saw it using Jupyter noitebook.

One option to unblock: nest the event loops - 
```
!pip install nest-asyncio
import nest_asyncio
nest_asyncio.apply()
```

Will work w/ @eyurtsev in the coming week on a better fix.

**Comment by screwyforcepush** [comment]
This works thanks!

**Comment by plyu3** [comment]
> Yes, one other user reported this w/ Jupyter lab.
> 
> I never saw it using Jupyter noitebook.
> 
> One option to unblock: nest the event loops -
> 
> ```
> !pip install nest-asyncio
> import nest_asyncio
> nest_asyncio.apply()
> ```
> 
> Will work w/ @eyurtsev in the coming week on a better fix.

I have tried this, but got an error: Exception: Connection closed while reading from the driver

**Comment by wuyoscar** [comment]
> Yes, one other user reported this w/ Jupyter lab.
> 
> I never saw it using Jupyter noitebook.
> 
> One option to unblock: nest the event loops -
> 
> ```
> !pip install nest-asyncio
> import nest_asyncio
> nest_asyncio.apply()
> ```
> 
> Will work w/ @eyurtsev in the coming week on a better fix.

It works for me, thanks

**Comment by hanifizzudinrahman** [comment]
> Yes, one other user reported this w/ Jupyter lab.
> 
> I never saw it using Jupyter noitebook.
> 
> One option to unblock: nest the event loops -
> 
> ```
> !pip install nest-asyncio
> import nest_asyncio
> nest_asyncio.apply()
> ```
> 
> Will work w/ @eyurtsev in the coming week on a better fix.

Thanks a lot
