### ISSUE TITLE
Add AI21 Embeddings support

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchain#85]

**Comment by Pablongo24** [comment]
AI21 offers embeddings thru an API?

**Comment by bcjordan** [comment]
Resolved already / can be closed? In: https://github.com/hwchase17/langchain/blob/7728a848d019b7a001f50c5c7e24be3798f319bb/langchain/llms/ai21.py#L22

**Comment by VikashTudu** [comment]
can I work on this issue

**Comment by LaloLalo1999** [comment]
Solved on #2253

**Comment by Andavarapu-Sampat-Kalyan** [comment]
is this issue solved or can I assign this issue to myself.

**Comment by bcjordan** [comment]
This looks resolved / can be closed 👍
