### ISSUE TITLE
Add memory to an Agent using RedisChatMessageHistory with sentinels throwing an error

### ISSUE THREAD

**Issue by lironezra** [langchain-ai/langchain#8511]
### System Info

I am trying to use `RedisChatMessageHistory` within an agent, but I'm encountering this error:
![image](https://github.com/langchain-ai/langchain/assets/28096499/2b5b5002-3f6c-4ca3-8d28-7439a6bcbf74)

My redis url I am using looks like that:
`redis_url = "redis+sentinel://:password@host:port/service_name/db"`

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
message_history = RedisChatMessageHistory(url=redis_url, ttl=600, session_id="test_id")
message_history.add_user_message("hi!")
message_history.add_ai_message("whats up?")
memory = ConversationBufferWindowMemory(memory_key="memory", chat_memory=message_history,  return_messages=True, k=15)
```

### Expected behavior

See on Redis the messages I added in my code.

**Comment by willbackslash** [comment]
which version of the package are you using? support for sentinel was added in this version v0.0.235 , I found that the flag to use sentinel is correctly added here https://github.com/langchain-ai/langchain/blob/b574507c51c0a2183ed4cde41efa5b2e8c0d98f7/libs/langchain/langchain/utilities/redis.py#L69C47-L69C47
