### ISSUE TITLE
how to Stream Search tool responses

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#8526]
### Issue you'd like to raise.

search = SerpAPIWrapper()
tools = define_tools(llm_chain,search)

tools = [
      Tool(
          name="Search",
          func=search.run,
          description="useful for when you need to answer questions about current events",
          # return_direct = True
      ),

  ]

prompt = CustomPromptTemplate(
        template=template,
        tools=tools,
        input_variables=["input", "intermediate_steps", "chat_history"]
    )

output_parser = CustomOutputParser()
llm = ChatOpenAI(temperature=0, model_name = "gpt-4-0613", streaming = True, callbacks = [MyCustomHandler(new_payload=new_payload)])
llm_chain = LLMChain(llm=llm, prompt=prompt)

agent = LLMSingleActionAgent(llm_chain=llm_chain, output_parser=output_parser, stop=["\nObservation:"], allowed_tools=tools)
agent_executor = AgentExecutor.from_agent_and_tools(agent=agent,
                                                tools=tools,
                                                verbose=True, memory = memory, early_stopping_method='generate')

**Comment by dmyoung9** [comment]
This issue doesn't have any supporting information... Only an unformatted script.

What is the issue you're facing?
