### ISSUE TITLE
search helper with Searx API

### ISSUE THREAD

**Issue by blob42** [langchain-ai/langchain#855]
I am implementing in #854 a helper search api for [searx](https://github.com/searxng/searxng) which is a famous self hosted meta search engine. This will offer the possibility to use search without relying on google or any paid APIs.

I started this issue to get some early feedback

**Comment by hwchase17** [comment]
i like the idea - im not super familiar with how to setup/use searx so some documentation there may be helpful

**Comment by blob42** [comment]
I am almost done with the base features of the module. I made it mirror the usage of the Google Search utility, but since it outputs results in JSON and can provide `answers` it is similar also to SerpAPI in some regards. 

As time goes on, I have no doubt that more and more people will turn to meta search engines like Searx, as they offer an alternative to paid and restricted options like Google. It's also interesting to note that there is currently a discussion [taking place](https://github.com/searxng/searxng/issues/2163) in the SearxNG community regarding the integration of large language models (LLMs).

I started working on the documentation to provide some examples of usage, I managed to produce the same results using the zero-shot-react [example](https://langchain.readthedocs.io/en/latest/modules/agents/getting_started.html) with the added advantage of the possibility to select which backend engine to use when the search is done. In my case, by default agent was not getting the correct age of the boyfriend, I switched the engine to `qwant` and it provided the correct answers.

**Comment by yaodongC** [comment]
Hi @blob42 , thanks for you great work on adding searx.  I am new to Searx and I have been encountering 403 errors while using the Searx wrapper. Here's the error message I am receiving:

ValueError: ('Searx API returned an error: ', '<!doctype html>\n<html lang=en>\n<title>403 Forbidden</title>\n<h1>Forbidden</h1>\n<p>You don&#39;t have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>\n')

I have tried using different Searx hosts, both public and local, but the issue persists. While my local instance "127.0.0.1:8888" works fine on my browser, it does not work with the SearxSearchWrapper.

I would appreciate any help you can provide to resolve this issue. I apologize if this is a basic question, as I am new to Searx.

**Comment by blob42** [comment]
Hi @yaodongC . There should be two reasons for this problem. 

1. You need to enable the `json` output format in the searx configuration under the `search` key like this:
```yml
search:
  formats:
    - html
    - json
```

2. You need to disable the rate limiter plugin on your self hosted instance or use the patch from [this pr](https://github.com/searxng/searxng/pull/2129).  This is also why it's not recommended to use public instances as they all have the rater limiter plugin and disabled `json` format.

**Comment by yaodongC** [comment]
Thank you so much @blob42 ! By adding - json in format, the problem is solved!!

**Comment by EnviralDesign** [comment]
also had this issue, and this solved it for me. I was using searxng app in my unraid nas, and the setting is not in the preferences gui so far as I could tell, but I was able to open a terminal, and edit to the specs above, and restart the docker instance, and all was well.

**Comment by aayusharyan** [comment]
> Thank you so much @blob42 ! By adding - json in format, the problem is solved!!

This needs to be followed by a restart to load this config.
