### ISSUE TITLE
ValueError: Expected metadata value to be a str, int, or float, got [{'text': 'Git', 'url': '#git'}] which is a <class 'list'> when storing into Chroma vector stores using using element mode of UnstructuredMarkdownLoader

### ISSUE THREAD

**Issue by cheeseQI** [langchain-ai/langchain#8556]
### System Info

LangChain: 0.0.248
Python: 3.9.17
OS version: Linux 6.1.27-43.48.amzn2023.x86_64

### Who can help?

I will submit a PR for a solution to this problem

### Information

- [ ] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Code:
```python
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.document_loaders import UnstructuredMarkdownLoader
from langchain.text_splitter import CharacterTextSplitter

def testElement():
    loader = UnstructuredMarkdownLoader(
        "filepath", mode="elements")
    documents = loader.load()
    text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=0)
    split_docs = text_splitter.split_documents(documents)

    embeddings = OpenAIEmbeddings()
    docsearch = Chroma.from_documents(split_docs, embeddings)
```
Also need to have a link format in the markdown file to be load, for example:
```
- [Google Developer Documentation Style Guide](https://developers.google.com/style)
```
Error Message:
```
    138         # isinstance(True, int) evaluates to True, so we need to check for bools separately
    139         if not isinstance(value, (str, int, float)) or isinstance(value, bool):
--> 140             raise ValueError(
    141                 f"Expected metadata value to be a str, int, or float, got {value} which is a {type(value)}"
    142             )
ValueError: Expected metadata value to be a str, int, or float, got [{'text': 'Git', 'url': '#git'}] which is a <class 'list'>
```

### Expected behavior

I expect to see the split documents loaded into Chroma, however, this raise error for not passing type check for metadata.

**Comment by PowderXu** [comment]
I also found this problem, I can work with you.

**Comment by cheeseQI** [comment]
> 

Awesome! I have found out the reason was Chroma does not support type for str to list dic. For example, 'links': [{'text': 'someText', 'url': 'someUrl'}]. And I have worked out a possible way so that we can work on that.

**Comment by feladorhet** [comment]
Have you found an alternative to Chroma in that sense? I'm looking for ways of passing in a list of perturbed questions as metadata but as you stated Chroma doesn't support this type. Any workarounds?

**Comment by cheeseQI** [comment]
> 

For the issue I mentioned, my current approach involves flattening or restructuring the list. I changed (str->list) to couples of (str->str). Here is my pr link if you like to check #8605

Note that this may not be a finalized solution and is only specific to the case I mentioned. I hope that provides some insight or has a connection to your problem. If you have any comments or feedback, please share your thoughts.

**Comment by feladorhet** [comment]
> > Have you found an alternative to Chroma in that sense? I'm looking for ways of passing in a list of perturbed questions as metadata but as you stated Chroma doesn't support this type. Any workarounds?
> 
> For the issue I mentioned, my current approach involves flattening or restructuring the list. I changed (str->list) to couples of (str->str). Here is my pr link if you like to check #8605
> 
> Note that this may not be a finalized solution and is only specific to the case I mentioned. I hope that provides some insight or has a connection to your problem. If you have any comments or feedback, please share your thoughts.

Seems logical, thank you for this. I actually just changed from Chroma to FAISS that supports list of strings, much simpler 😄

**Comment by hvassard** [comment]
Hello everyone, thank you for this amazing tool and community ! :rocket: 

If it could help you to solve similar linked problems :  I encountered almost the same problem with an `UnstructuredPDFLoader` with argument `mode=elements` instead of defaut "single". Here's the error message : 

```python3
Traceback (most recent call last):
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/4__test_langchain_pdf_breakdown.py", line 69, in <module>
    vectorstore = Chroma.from_documents(
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 603, in from_documents
    return cls.from_texts(
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 567, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 208, in add_texts
    self._collection.upsert(
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 294, in upsert
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 349, in _validate_embedding_set
    validate_metadatas(maybe_cast_one_to_many(metadatas))
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/types.py", line 172, in validate_metadatas
    validate_metadata(metadata)
  File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/types.py", line 140, in validate_metadata
    raise ValueError(
ValueError: Expected metadata value to be a str, int, float or bool, got {'points': ((70.86, 56.71268726919993), (70.86, 349.85999999999996), (521.45003121198, 349.85999999999996), (521.45003121198, 56.71268726919993)), 'system': 'PixelSpace', 'layout_width': 595.32, 'layout_height': 841.92} which is a <class 'dict'>
```
The PDF that I worked on can be found [here](https://commission.europa.eu/publications/white-paper-artificial-intelligence-european-approach-excellence-and-trust_en)

**Comment by cheeseQI** [comment]
> Hello everyone, thank you for this amazing tool and community ! 🚀
> 
> If it could help you to solve similar linked problems : I encountered almost the same problem with an `UnstructuredPDFLoader` with argument `mode=elements` instead of defaut "single". Here's the my code and the error message :
> 
> ```python
> from langchain.document_loaders import UnstructuredPDFLoader
> from langchain.text_splitter import RecursiveCharacterTextSplitter
> from langchain.embeddings import HuggingFaceEmbeddings
> from langchain.vectorstores import Chroma
> 
> loader = UnstructuredPDFLoader(PDF_FILE_PATH, mode="elements")
> data = loader.load()
> text_splitter = RecursiveCharacterTextSplitter(chunk_size=700, chunk_overlap=50)
> all_splits = text_splitter.split_documents(data)
> vectorstore = Chroma.from_documents(
>     documents=all_splits, embedding=HuggingFaceEmbeddings()
> )
> ```
> 
> ```python
> Traceback (most recent call last):
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/4__test_langchain_pdf_breakdown.py", line 69, in <module>
>     vectorstore = Chroma.from_documents(
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 603, in from_documents
>     return cls.from_texts(
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 567, in from_texts
>     chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 208, in add_texts
>     self._collection.upsert(
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 294, in upsert
>     ids, embeddings, metadatas, documents = self._validate_embedding_set(
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 349, in _validate_embedding_set
>     validate_metadatas(maybe_cast_one_to_many(metadatas))
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/types.py", line 172, in validate_metadatas
>     validate_metadata(metadata)
>   File "/home/hugo/Documents/Missions/POC_GEN_AI/langchain_discovery/.venv_3/lib/python3.10/site-packages/chromadb/api/types.py", line 140, in validate_metadata
>     raise ValueError(
> ValueError: Expected metadata value to be a str, int, float or bool, got {'points': ((70.86, 56.71268726919993), (70.86, 349.85999999999996), (521.45003121198, 349.85999999999996), (521.45003121198, 56.71268726919993)), 'system': 'PixelSpace', 'layout_width': 595.32, 'layout_height': 841.92} which is a <class 'dict'>
> ```
> 
> The PDF that I worked on can be found [here](https://commission.europa.eu/publications/white-paper-artificial-intelligence-european-approach-excellence-and-trust_en)

"Thanks for sharing that! It seems like the problem with unsupported metadata value types is common when put into Chroma. Other than my initial solution, I'm considering whether using a filter might be a better and more general way to solve this issue. Just like this pr #9015

**Comment by vhxs** [comment]
Chroma appears to fail to handle `datetime`s as well. Here's code I tried to run to ask questions of my own Mastodon posts:

```python
from langchain.document_loaders import MastodonTootsLoader
from langchain.indexes import VectorstoreIndexCreator

loader = MastodonTootsLoader(mastodon_accounts=["@vsaraph@mathstodon.xyz"], number_toots=300)
index = VectorstoreIndexCreator().from_loaders([loader])

print(index.query("What kind of content does this user post?"))
```

Fails with the following:
```
Traceback (most recent call last):
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 209, in add_texts
    self._collection.upsert(
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 294, in upsert
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 349, in _validate_embedding_set
    validate_metadatas(maybe_cast_one_to_many(metadatas))
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/types.py", line 172, in validate_metadatas
    validate_metadata(metadata)
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/types.py", line 140, in validate_metadata
    raise ValueError(
ValueError: Expected metadata value to be a str, int, float or bool, got 2023-08-12 14:47:08+00:00 which is a <class 'datetime.datetime'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vsaraph/PycharmProjects/langchainTest/main.py", line 7, in <module>
    index = VectorstoreIndexCreator().from_loaders([loader])
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 83, in from_loaders
    return self.from_documents(docs)
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 88, in from_documents
    vectorstore = self.vectorstore_cls.from_documents(
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 613, in from_documents
    return cls.from_texts(
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 577, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 221, in add_texts
    raise ValueError(e.args[0] + "\n\n" + msg)
ValueError: Expected metadata value to be a str, int, float or bool, got 2023-08-12 14:47:08+00:00 which is a <class 'datetime.datetime'>

Try filtering complex metadata from the document using langchain.vectorstore.utils.filter_complex_metadata.
```

**Comment by cheeseQI** [comment]
> 

It seems like the filter feature has been merged. So maybe you can try calling 'filter_complex_metadata' as it was mentioned in the message, before putting it into chroma?

**Comment by cheeseQI** [comment]
> Chroma appears to fail to handle `datetime`s as well. Here's code I tried to run to ask questions of my own Mastodon posts:
> 
> ```python
> from langchain.document_loaders import MastodonTootsLoader
> from langchain.indexes import VectorstoreIndexCreator
> 
> loader = MastodonTootsLoader(mastodon_accounts=["@vsaraph@mathstodon.xyz"], number_toots=300)
> index = VectorstoreIndexCreator().from_loaders([loader])
> 
> print(index.query("What kind of content does this user post?"))
> ```
> 
> Fails with the following:
> 
> ```
> Traceback (most recent call last):
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 209, in add_texts
>     self._collection.upsert(
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 294, in upsert
>     ids, embeddings, metadatas, documents = self._validate_embedding_set(
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 349, in _validate_embedding_set
>     validate_metadatas(maybe_cast_one_to_many(metadatas))
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/types.py", line 172, in validate_metadatas
>     validate_metadata(metadata)
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/chromadb/api/types.py", line 140, in validate_metadata
>     raise ValueError(
> ValueError: Expected metadata value to be a str, int, float or bool, got 2023-08-12 14:47:08+00:00 which is a <class 'datetime.datetime'>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/vsaraph/PycharmProjects/langchainTest/main.py", line 7, in <module>
>     index = VectorstoreIndexCreator().from_loaders([loader])
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 83, in from_loaders
>     return self.from_documents(docs)
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 88, in from_documents
>     vectorstore = self.vectorstore_cls.from_documents(
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 613, in from_documents
>     return cls.from_texts(
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 577, in from_texts
>     chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
>   File "/home/vsaraph/.cache/pypoetry/virtualenvs/langchaintest-wCCzSbS6-py3.10/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 221, in add_texts
>     raise ValueError(e.args[0] + "\n\n" + msg)
> ValueError: Expected metadata value to be a str, int, float or bool, got 2023-08-12 14:47:08+00:00 which is a <class 'datetime.datetime'>
> 
> Try filtering complex metadata from the document using langchain.vectorstore.utils.filter_complex_metadata.
> ```

It seems like the filter feature has been merged. So maybe you can try calling 'filter_complex_metadata' as it was mentioned in the message, before putting it into chroma?

**Comment by githubbar** [comment]
Something like this should do it:

```
from langchain.document_loaders import UnstructuredMarkdownLoader
from langchain.vectorstores import Chroma
from langchain.vectorstores import utils as chromautils

loader = UnstructuredMarkdownLoader(filename, mode="elements")
docs = loader.load()
docs = chromautils.filter_complex_metadata(docs)
db = Chroma.from_documents(docs, embeddings, persist_directory="./db")

```

**Comment by handsomexiu** [comment]
you can remove the parameter  mode="elements",the parameter generate a lot of information in metadata , such as language etc.
`metadata={'source': '/tmp/gradio/1152842a4af264b2c7ba1d8410ca299a625418e5/草稿.md', 'filename': '草稿.md', 'file_directory': '/tmp/gradio/1152842a4af264b2c7ba1d8410ca299a625418e5', 'last_modified': '2023-11-04T10:24:22', 'filetype': 'text/markdown', 'languages': ['zho'], 'page_number': 1, 'category': 'Title'}`

if you remove ,the metadata only has `{'source':"...........'}`
`metadata={'source':'/tmp/gradio/1152842a4af264b2c7ba1d8410ca299a625418e5/草稿.md'}`

**Comment by ML-Abdula** [comment]
> @feladorhet May I ask how did you achieve this in FAISS ? I have my Metadata as follows:
> 
> ```
> Content: foo, Metadata: {'brand': ['Nintendo']} 
> Content: foo, Metadata: {'brand': ['Microsoft', 'Sony']} 
> Content: bar, Metadata: {'brand': ['Microsoft']}
> Content: foo, Metadata: {'brand': ['Nintendo']}
> ```
> 
> If I want to filter on brand='Nintendo' for query related to `foo`, how could we do it ? :)

Any updates on this, I'm facing same issue?

**Comment by One-djey** [comment]
As mentioned @cheeseQI  you can convert all metadata to str with a disgusting but working:
```
for doc in docs:
    for md in doc.metadata:
        doc.metadata[md] = str(doc.metadata[md])
```

**Comment by smortezah** [comment]
> Something like this should do it:
> 
> ```python
> from langchain.document_loaders import UnstructuredMarkdownLoader
> from langchain.vectorstores import Chroma
> from langchain.vectorstores import utils as chromautils
> 
> loader = UnstructuredMarkdownLoader(filename, mode="elements")
> docs = loader.load()
> docs = chromautils.filter_complex_metadata(docs)
> db = Chroma.from_documents(docs, embeddings, persist_directory="./db")
> ```

This is not the best idea, as it removes the metadata that are not of supported types.

**Comment by smortezah** [comment]
> As mentioned @cheeseQI you can convert all metadata to str with a disgusting but working:
> 
> ```
> for doc in docs:
>     for md in doc.metadata:
>         doc.metadata[md] = str(doc.metadata[md])
> ```

This does the job for most data types, such as lists.

```
metadata = {'id': [1, 4]}

# Convert list to str
metadata = {'id': str([1, 4])}

# Store in Chromadb
...

# Convert str back to list
import json
metadata = {'id': json.loads(str([1, 4]))}
```
