### ISSUE TITLE
Petals API Support

### ISSUE THREAD

**Issue by Sharpz7** [langchain-ai/langchain#8563]
### Feature request

Currently, langchain supports petals, but I think we should also support using a petals API endpoint. https://github.com/petals-infra/chat.petals.dev

### Motivation

The idea here is that users don't need to run the base application on their system, and can just use the API directly.

I think this is useful as a developer for speed, and just testing things quickly. I also think it would be the easiest and most reliabile way for any langchain user to get access to a high quality LLM on low-spec hardware.

### Your contribution

I am happy to add this myself if I can be guided on what parts of the code need changed.

**Comment by Priyanshupareek** [comment]
@Sharpz7 Hey, I'm working on something similar. Using WebSockets to open a connection for using the Petals model output to build agents with Langchain. Would love to discuss more.
