### ISSUE TITLE
Issue: Agent with memory and intermediate steps

### ISSUE THREAD

**Issue by lebg1** [langchain-ai/langchain#8579]
### Issue you'd like to raise.

Hi everyone,

I'm having trouble working with the agent structure in Langchain.
I would like to have an agent that has memory and can return intermediate steps.
However It doesn't work, when I make an agent executor, the return_intermediate_steps=True makes it crash as the memory cannot read the output and when I use the agent directly, the return_intermediate_steps=True does nothing.

Do you know if there is a way to have an agent with memory and that can return intermediate steps at the same time ?

Thanks for your help

**Comment by lebg1** [comment]
I'll show some of my code

```
memory = ConversationBufferMemory(memory_key=memory_key, return_messages=True)

prompt = CustomPromptTemplate(
    template=template,
    tools=tools,
    input_variables=["input", "intermediate_steps", memory_key],
)

agent = LLMSingleActionAgent(
        llm_chain=llm_chain,
        output_parser=output_parser,
        stop=["\nObservation:"],
        allowed_tools=tool_names,
        memory=memory,
)

agent_executor = AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        verbose=True,
        handle_parsing_errors=True,
        return_intermediate_steps=True,
)

```

When I try to run multiple requests, I get this error:
ValueError: One output key expected, got dict_keys(['output', 'intermediate_steps'])

**Comment by Tech-Netiums** [comment]
I face the same issue @lebg1

**Comment by ryanholtschneider2** [comment]
I believe what you want to do is change the output key of the memory so that it uses the output only of the agent for the memory but still returns intermediate steps as well.
Here is your modified code - 

memory = ConversationBufferMemory(memory_key=memory_key, return_messages=True,output_key='output')

prompt = CustomPromptTemplate(
    template=template,
    tools=tools,
    input_variables=["input", "intermediate_steps", memory_key],
)

agent = LLMSingleActionAgent(
        llm_chain=llm_chain,
        output_parser=output_parser,
        stop=["\nObservation:"],
        allowed_tools=tool_names,
        memory=memory,
)

agent_executor = AgentExecutor.from_agent_and_tools(
        agent=agent,
        tools=tools,
        verbose=True,
        handle_parsing_errors=True,
        return_intermediate_steps=True,
)

**Comment by Shaon2221** [comment]
```
ValueError                                Traceback (most recent call last)
[<ipython-input-100-64de87c2b7d2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 response=agent_executor.run(f"hi")

2 frames
[/usr/local/lib/python3.10/dist-packages/langchain/chains/base.py](https://localhost:8080/#) in _run_output_key(self)
    479     def _run_output_key(self) -> str:
    480         if len(self.output_keys) != 1:
--> 481             raise ValueError(
    482                 f"`run` not supported when there is not exactly "
    483                 f"one output key. Got {self.output_keys}."

ValueError: `run` not supported when there is not exactly one output key. Got ['output', 'intermediate_steps'].
```
