### ISSUE TITLE
Need support for async memory, especially for ConversationSummaryMemory and ConversationSummaryBufferMemory

### ISSUE THREAD

**Issue by chrislrobert** [langchain-ai/langchain#8580]
### Feature request

`ConversationSummaryMemory` and `ConversationSummaryBufferMemory` can be used as memory within async conversational chains, but they themselves are fully blocking. In particular, `Chain.acall()` is async, but it calls `Chain.prep_outputs()`, which calls `self.memory.save_context()`. In the case of `ConversationSummaryBufferMemory`, `save_context()` calls `prune()`, which calls `SummarizerMixin.predict_new_summary()`, which creates an `LLMChain` and then calls `LLMChain.predict()`. We really need to be able to specify an async handler when we create the memory object, pass that through to the `LLMChain`, and ultimately `await LLMChain.apredict()`.

### Motivation

The blocking nature of the `LLMChain.predict()` calls means that otherwise-async chains end up blocking regularly. If you use an ASGI server like `uvicorn`, this means that lots of requests can end up waiting. You can wrap `uvicorn` in a WSGI server like `gunicorn` so that there are multiple processes available, but blocking one whole process every time the memory object needs to summarize can still block any websocket users connected to the blocked process. It's just not good.

### Your contribution

We're going to have to solve this problem for ourselves, and we'd be happy to try to contribute a solution back to the community. However, we'd be first-time contributors and we're not sure whether there are others already making similar improvements.

**Comment by dmyoung9** [comment]
Possible duplicate of #8329?

**Comment by chrislrobert** [comment]
> Possible duplicate of #8329?

Yes, indeed, it looks that way. FWIW, we solved this by overriding save_context() and prune() with async versions.

**Comment by dmyoung9** [comment]
@chrislrobert I don't have permissions to do so on this repo, but if you feel like your concerns have been addressed (either you've solved them internally or the other issue is sufficient), you could close this issue.

I just hopped in to do some triage, but the backlog is > 2000 issues at this point 😬

**Comment by chrislrobert** [comment]
As far as I know, this is still relevant, but I just don't know the full scope of other efforts and changes. Since this keeps getting bounced back to me and the suggestion is always to close this, I'll just close it now. If somebody hasn't already done it, somebody really should make async versions for these functions.
