### ISSUE TITLE
GPTCache implementation isnt working with ChatOpenAI

### ISSUE THREAD

**Issue by kdcokenny** [langchain-ai/langchain#8584]
### System Info

langchain = "^0.0.248"

### Who can help?

@hwchase17 @agola11 

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
import os
import hashlib
import langchain

from gptcache import Cache  # type: ignore
from gptcache.manager.factory import manager_factory  # type: ignore
from gptcache.processor.pre import get_prompt  # type: ignore

from langchain.cache import GPTCache
from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI

os.environ["OPENAI_API_KEY"] = "sk-..."


llm = ChatOpenAI(temperature=0) # type: ignore


def get_hashed_name(name):
    return hashlib.sha256(name.encode()).hexdigest()


def init_gptcache(cache_obj: Cache, llm: str):
    hashed_llm = get_hashed_name(llm)
    cache_obj.init(
        pre_embedding_func=get_prompt,
        data_manager=manager_factory(manager="map", data_dir=f"map_cache_{hashed_llm}"),
    )


langchain.llm_cache = GPTCache(init_gptcache)

# The first time, it is not yet in cache, so it should take longer
response = llm("Tell me a joke")
print(f"Response 1: {response}")

# The first time, it is not yet in cache, so it should take longer
response = llm("Tell me a joke")
print(f"Response 2: {response}")
```

### Expected behavior

Response 1: 

Why did the chicken cross the road?

To get to the other side.
Response 2: 

Why did the chicken cross the road?

To get to the other side.

**Comment by kdcokenny** [comment]
After further research, I noticed that the implementation for ChatOpenAI vs OpenAI is completely different. I will work on creating an implementation for this + the sql storage

**Comment by RayceRossum** [comment]
@kdcokenny, @pranaychandekar
Politely checking in on this issue :) I see the proposed fix was closed, is there anything I can do to push this along?
