### ISSUE TITLE
@guard directive

### ISSUE THREAD

**Issue by John-Church** [langchain-ai/langchain#860]
A directive that, when applied to chains, takes a restriction sentence like “does not contain profanity” and asks a llm if a chain output fits the restriction + denies or loops back with new context if it does. 

Core features:
- ability to guard a chain with a list of restrictions
- option to throw an error or to retry a given number of times with restriction appended to context

Possible additional features:
- sentiment analysis guard (@sentiment_guard or something) to save on llm calls for simple stuff

**Comment by John-Church** [comment]
Don't have access to assigning this to myself but I'm working on it.

**Comment by hwchase17** [comment]
assigned this to you! i like it

may want to check out https://langchain.readthedocs.io/en/latest/modules/chains/examples/moderation.html (which does this with moderation) for inspiration
