### ISSUE TITLE
How to create a custom retriever

### ISSUE THREAD

**Issue by llmadd** [langchain-ai/langchain#8623]
### Feature request

When I use RetrievalQA, I need to add and reorder the content retrieved by retriever
```
qa = RetrievalQA.from_chain_type(llm=chat, 
                                 chain_type="stuff",
                                 retriever=docsearch.as_retriever(search_kwargs={"k": 2}), 
                                 chain_type_kwargs={"prompt": PROMPT,"memory":memory })
```
I want the retrieved content from retriever to be reordered by "source".
The following code is used by me to manipulate the retrieved content to achieve my needs.
```
retriever = docsearch.as_retriever(search_kwargs={"k": 6})
search_result = retriever.get_relevant_documents(quey)
def sort_paragraphs(paragraphs):
    sorted_paragraphs = sorted(paragraphs, key=lambda x: x.metadata["source"])
    return sorted_paragraphs
paragraphs = sort_paragraphs(search_result)
sorted_paragraphs = ""
for i in paragraphs:
    sorted_paragraphs = sorted_paragraphs + i.page_content + "\n"
```
How can I define an retriever that I can use in my chain to organize the search content as I wish

### Motivation

Some custom retrieval logic is required to seek optimal performance.

### Your contribution

I would like to have tutorials related to custom retriever documentation
@hwchase17
https://twitter.com/hwchase17/status/1646272240202432512
I think langchain needs to be a custom retriever

**Comment by llmadd** [comment]
This is based on the bot's answer to modify the implementation of the search content sorting, custom Retriever.
The bot's answer does not define the database and method for the search, and an error occurs.
```
class CustomRetriever(BaseRetriever):
    vectorstores:VectorStore
    retriever:docsearch.as_retriever(search_kwargs={"k": 6})

    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        
        documents = self.retriever.get_relevant_documents(query, callbacks=run_manager.get_child())
        
        documents = sorted(documents, key=lambda doc: doc.metadata.get('source'))
        
        return documents

    async def _aget_relevant_documents(
        self,
        query: str,
        *,
        run_manager: AsyncCallbackManagerForRetrieverRun,
        **kwargs: Any,
    ) -> List[Document]:
        raise NotImplementedError()
```

**Comment by llmadd** [comment]
Hello @hwchase17,
I think you need to add a custom retriever into the tutorial.

**Comment by sid8491** [comment]
> 

how did you pass docsearch and Vectorstore to this custom class? and how did you use it in langchain?

**Comment by llmadd** [comment]
This is an example：

```
from langchain.vectorstores import VectorStore
class CustomRetriever(BaseRetriever):
    vectorstores:VectorStore
    retriever:db.as_retriever()

    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        pass
CustomRetriever(vectorstores = db,retriever = db.as_retriever(search_kwargs={"k": 8}))
```
You can create a BaseRetriever class and set a custom vector database and retriever attribute. You can pass in the corresponding parameters when you instantiate this class

**Comment by mirodrr** [comment]
When I try any of these examples, I get an error: "TypeError: CustomRetriever() takes no arguments"

My retriever:

`from langchain.schema.retriever import BaseRetriever, Document
from langchain.callbacks.manager import CallbackManagerForRetrieverRun
from langchain.vectorstores.base import VectorStoreRetriever
from typing import List

class CustomRetriever(BaseRetriever):
    retriever: VectorStoreRetriever

    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        # Use your existing retriever to get the documents
        documents = self.retriever.get_relevant_documents(query, callbacks=run_manager.get_child())
        
        # Sort the documents by "chunk_num"
        documents = sorted(documents, key=lambda doc: doc.metadata.get('chunk_num'))

        return documents
`

Trying to use the retriever:

`
    qa = RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",
        retriever=CustomRetriever(retriever=load_database(vectorstore_key).as_retriever(k=NUM_DOCS_TO_RETRIEVE, search_kwargs={"k": NUM_DOCS_TO_RETRIEVE})),
        chain_type_kwargs=chain_type_kwargs)
`

Could someone provide a fully working example?

**Comment by mirodrr** [comment]
I would think that I would need to create an `__init__` method? But no examples so far have shown that

**Comment by mirodrr** [comment]
Nevermind, the second answer provided by the bot actually works perfectly: https://github.com/langchain-ai/langchain/issues/8623#issuecomment-1663242706

Idk why that one didn't get as many thumbs up as any of the other posts that did not work for me.

**Comment by jamesljl** [comment]
CustomRetriever is so helpful when I try to use ConversationalRetrievalChain with context and memory , and try to do some post-process to the context documents. Thx a lot!

**Comment by jamesljl** [comment]
this is very helpful for doing some post-process once we got the relevant documents before we send them to LLM as context, such as remove duplicate docs, shorten docs , etc.

**Comment by shade307** [comment]
You can call any api using the following implementation and use the api as the retriever. As in my case, I didn't have access to the redis vector store. But one api was open to me using which I could get the closest n records (text chunks) based on threshold.

Implementation in python:
```
from langchain.schema.retriever import BaseRetriever, Document
from typing import TYPE_CHECKING, Any, Dict, List, Optional 
from langchain.callbacks.manager import CallbackManagerForRetrieverRun

class CustomRetriever(BaseRetriever):
    api_token_key:str
    api_end_point:str
    api_redis_index_name:str
    threshold_for_search_api:str
    
    def _get_relevant_documents(self, query: str, *, run_manager: CallbackManagerForRetrieverRun) -> List[Document]:
        """
        _get_relevant_documents is function of BaseRetriever implemented here

        :param query: String value of the query

        """
        result_docs = list()
        headers = {
            'apiToken': f'{self.api_token_key}',
            'Content-Type': 'application/json'
        }

        data = '{"output":"*","query": "@similarity:' + query + '}","index":"' + self.api_redis_index_name + '"}'

        response = requests.post(f'{self.api_end_point}',
                                 headers=headers,
                                 data=data)
        list_of_val = response.json()
        least_score = 1
        least_score_index = 0
        threshold_val = float(self.threshold_for_search_api)
        for c, i in enumerate(list_of_val):
            fetched_score = i["score"]
            if least_score < fetched_score:
                least_score = fetched_score
                least_score_index = c
            if fetched_score <= threshold_val:
                doc = Document(page_content=i["content"])
                result_docs.append(doc)

        if len(result_docs) == 0:
            i = list_of_val[least_score_index]
            doc = Document(page_content=i["content"])
            result_docs.append(doc)
        return result_docs

```
Then initialize the retriever as:
```
retriever_r = CustomRetriever(api_token_key=<your key>,
                              api_end_point=<your api endpoint>,
                             api_redis_index_name = <your redis index name>,
                             threshold_for_search_api= "0.5")
```

Then use the retriever in qa chain:
```
qa_chain = RetrievalQA.from_chain_type(
    llm=llm, 
    chain_type='map_reduce', 
    retriever=retriever_r, 
    chain_type_kwargs={"question_prompt": question_prompt_template, "combine_prompt": combine_prompt_template},
    verbose = True
)
```

Now you have a custom retriever that you can use for your custom qa chain

**Comment by mytiRobo** [comment]
If it helps there's a chain RetrievalQAwithSourcesChain https://api.python.langchain.com/en/latest/chains/langchain.chains.qa_with_sources.retrieval.RetrievalQAWithSourcesChain.html#langchain.chains.qa_with_sources.retrieval.RetrievalQAWithSourcesChain
