### ISSUE TITLE
Catch and Filter OpenAI "As an AI model" responses

### ISSUE THREAD

**Issue by sarmientoj24** [langchain-ai/langchain#8637]
### Feature request

When connecting to ChatGPT API, it is possible to get responses by the chatbot as "As an AI model...", which ruins the chatbot experience on your application.

A way to filter this and generate a default response might be better.

### Motivation

For applications using OpenAI API, this would enable filtering those requests.

### Your contribution

Not really

**Comment by KeshavSingh29** [comment]
I dont think you need a filter for this. Such a behavior can be easily controlled via prompting or changing system prompt.

**Comment by sarmientoj24** [comment]
@KeshavSingh29 For example, someone says an R-18 or something racist, it will say something like this. It can be controlled via prompts but I think it can still be uncontrollable at times.

**Comment by KeshavSingh29** [comment]
@sarmientoj24 Thats true. One way I do it is to have a validation method where I use a customized prompt to change/rewrite such responses. But again its filtering through prompting. Do you have some other way in mind? In that case such a feature would be nice to have.
