### ISSUE TITLE
how to set chat_history for different user

### ISSUE THREAD

**Issue by kimiller** [langchain-ai/langchain#8671]
### Issue you'd like to raise.

I just want to set chat history for different user in ConversationBufferMemory, user can only get his own chathistory
this is my code：

    **embeddings = OpenAIEmbeddings(model="text-embedding-ada-002", chunk_size=1000)
 
    docsearch = Chroma.from_documents(split_docs, embeddings)
    memory = ConversationBufferMemory(memory_key="chat_history")
 
    qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="map_rerank", 
   retriever=docsearch.as_retriever(),memory=memory, return_source_documents=False)**

could anyone give me some advice please

**Comment by Magicen0722** [comment]
In my practical experience, I suggest you check this out:
[memory](https://python.langchain.com/docs/integrations/memory/)
Finding a suitable storage medium is what you need to do if you need to distinguish between different conversations from different users.
Here's a simple example of how I use Redis to store conversation history:
```
from langchain.memory import RedisChatMessageHistory
import dotenv
import logging
import os
from langchain.chat_models import ChatOpenAI, AzureChatOpenAI
from langchain.memory import ConversationSummaryBufferMemory
from langchain.prompts import PromptTemplate
from langchain.chains import ConversationChain

dotenv.load_dotenv()
openai_api_type = os.environ["OPENAI_API_TYPE"]
openai_api_base = os.environ["OPENAI_API_BASE"]
openai_api_version = os.environ["OPENAI_API_VERSION"]
deployment = os.environ["CHAT_DEPLOYMENT"]
llm = AzureChatOpenAI(
    openai_api_type=openai_api_type,
    openai_api_base=openai_api_base,
    deployment_name=deployment,
    openai_api_version=openai_api_version,
)
print("beginning memory test")

REDIS_USERNAME = os.environ["REDIS_USERNAME"]
REDIS_PASSWORD = os.environ["REDIS_PASSWORD"]
REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = os.environ["REDIS_PORT"]
REDIS_DB = os.environ["REDIS_DB"]
REDIS_URL = f"redis://{REDIS_USERNAME}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
history = RedisChatMessageHistory(url=REDIS_URL, session_id="", key_prefix='SUMMARY_BUFFER_TEST')
memory = ConversationSummaryBufferMemory(memory_key="chat_history_lines", llm=llm, max_token_limit=10, chat_memory=history)
memory.save_context({"input": "hi"}, {"output": "whats up"})
memory.save_context({"input": "not much you"}, {"output": "not much"})
_DEFAULT_TEMPLATE = """The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.

Current conversation:
{chat_history_lines}
Human: {input}
AI:"""
PROMPT = PromptTemplate(
    input_variables=["input", "chat_history_lines"],
    template=_DEFAULT_TEMPLATE,
)
conversation = ConversationChain(llm=llm, verbose=True, memory=memory, prompt=PROMPT)
conversation.run("Hi!")
```
You can use a combination of session_id and key_prefix to uniquely mark a chat, or customize it by overriding its `key `method :)

**Comment by kimiller** [comment]
@Magicen0722  Oh ,I see , let me check the  memory docs. Thanks a lot for you advice !!!

**Comment by VpkPrasanna** [comment]
hi @Magicen0722 how can i able to dockerize this with redis in place ?
which redis i have to use there ?? any idea ?

**Comment by 19950606** [comment]
@Magicen0722 your code is helpful.. I would also need to know on how can then link this to api like FastAPI etc in such a way that if i ask anything it then pulls the history in db and add to conversation buffer so that it reply the question and then after it saves the new question and answer in db
