### ISSUE TITLE
Failed to calculate number of tokens, falling back to approximate count

### ISSUE THREAD

**Issue by john930d** [langchain-ai/langchain#8675]
### System Info

Hi guys, I wanted to ask you does anyone know where is the problem with this because Im getting an error: (Failed to calculate number of tokens, falling back to approximate count) after trying to make a request to open ai by using langchain and sql database connection. On the request I can see that there is a property with max_tokens: 256, is there a problem with the api key or pricing plan or anything related to the database size?

The version of langchain library that Im using is "langchain": "0.0.110",

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [x] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Im trying to chat with my database and Im getting the error above.

### Expected behavior

It is showing me an error (Failed to calculate number of tokens, falling back to approximate count) and it is taking so much time to load.

**Comment by john930d** [comment]
> _Answer generated by a 🤖_
> 
> ## Answer
> Hello,
> 
> The error message "Failed to calculate number of tokens, falling back to approximate count" could be due to a few reasons:
> 
> 1. The LangChain library uses the `tiktoken` Python package to calculate the number of tokens in the input messages. If `tiktoken` is not installed or if there's an issue with it, the library might fail to calculate the exact number of tokens and fall back to an approximate count.
> 2. The model name specified in the `tiktoken_model_name` attribute of the `ChatOpenAI` class might not be supported by `tiktoken`. If the model name is not supported by `tiktoken`, it could lead to the error.
> 
> The long loading time could be due to:
> 
> 1. The `openai.ChatCompletion` API call made by the `ChatOpenAI` class might be taking a long time to respond. This could be due to network latency, server-side issues, or the complexity of the input messages.
> 2. If the `streaming` attribute of the `ChatOpenAI` class is set to `True`, the library will stream the results from the OpenAI API. This could potentially take a long time if the input messages are complex or if there are many of them.
> 3. The `max_retries` attribute of the `ChatOpenAI` class is set to 6. If the OpenAI API call fails, the library will retry the call up to 6 times. This could also contribute to the long loading time.
> 
> You mentioned that you're using LangChain version 0.0.110. There have been many updates since then, and the latest version is 0.0.251. It's possible that the issue you're experiencing has been resolved in a later version. I recommend updating to the latest version and trying again.
> 
> If the problem persists after updating, please provide more information about your setup and the exact steps you're taking that lead to the error. This will help us better understand the issue and provide a more accurate solution.
> 
> Best, Dosu
> 
> ## Sources
> * [libs/langchain/langchain/chat_models/openai.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/chat_models/openai.py)
> * [docs/extras/modules/callbacks/token_counting.ipynb](https://github.com/langchain-ai/langchain/blob/-/docs/extras/modules/callbacks/token_counting.ipynb)
> 
> This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

Hi @dosu-beta, my backend is created with express js (node js) and Im not using python.

**Comment by devstein** [comment]
@john930d I think you meant to create this issue in [LangChain JS](https://github.com/hwchase17/langchainjs/issues)
