### ISSUE TITLE
ValueError: ChatAgent does not support multi-input tool do_my_job. with a non-argaument function

### ISSUE THREAD

**Issue by verils** [langchain-ai/langchain#8695]
### System Info

OS: Linux Mint 21.2 Cinnamon
Python 3.10
LangChain v0.0.251

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I defined a function like:

```python
@tool
def do_my_job() -> list:
    """Just do my job"""
    return []
```

Obviously it has none of arguments.

After I made an agent and run:

```python
lc_tools = [
    tool.do_my_job
]
lc_agent_executor = initialize_agent(agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION, llm=lc_llm, tools=lc_tools,
                            verbose=config.verbose)
lc_reply = lc_agent_executor.run("do my job")
```

I got this error: `ValueError: ChatAgent does not support multi-input tool do_my_job.`, which raised at `langchain.agents.utils.py`:

```python
def validate_tools_single_input(class_name: str, tools: Sequence[BaseTool]) -> None:
    """Validate tools for single input."""
    for tool in tools:
        if not tool.is_single_input:
            raise ValueError(
                f"{class_name} does not support multi-input tool {tool.name}."
            )
```

When the function `do_my_job` has arguments = 1, the `tool.is_single_input` was `True`
When the function `do_my_job` has arguments > 1, the `tool.is_single_input` was `False`
When the function `do_my_job` has arguments < 1, the `tool.is_single_input` was `False`

I can specify an unused argument for the function, but it is a bit weird.

Should this check be correct?

### Expected behavior

Non-argument functions should work with **Zero-shot ReAct**

**Comment by hinthornw** [comment]
Ya this agent only supports tools that accept a single string as input and single string as output

**Comment by verils** [comment]
I tried to modify this script to support a zero-argument function, it worked, so the restriction is not from the underlying llm. (at least not from Azure OpenAI)

If this was designated purposely, it's better to have a documentation. :-D
