### ISSUE TITLE
Allow GPT4AllEmbeddings() constructor to be configured

### ISSUE THREAD

**Issue by godlikemouse** [langchain-ai/langchain#8708]
### Feature request

I would be great to be able to pass in configuration info to the `Embeddings` from the `GTP4AllEmbeddings()` constructor in the same manner as the `GPT4All()` constructor.  For example. To be able to turn of allow_download, model, etc..

`embeddings = GPT4AllEmbeddings(allow_download=False)`

### Motivation

It would allow for the same level of customization as the `GPT4All()` constructor.  Right now there is no way to run FAISS in completely offline mode.  Trying to do so will hang and error out with the models lookup call to https://gpt4all.io/models/models.json.  Being able to pass in configuration information would fix issues such as these.  As it is right now, I have to download the gpt4all repo and manually patch the `Embeddings` to pass in the configuration I need.

### Your contribution

Probably not at this time.  I would love to, but I'm a bit too busy with work at the moment.

**Comment by godlikemouse** [comment]
This would definitely be a good feature with regards to offline or private instances.  Without this feature, the process hangs until the request times out.

**Comment by AndersBennedsgaard** [comment]
Just for anyone as confused about this as I've been, it is possible to use an initialized GPT4All client in the embeddings:

```python
from langchain.llms.gpt4all import GPT4All
from langchain.embeddings.gpt4all import GPT4AllEmbeddings

llm = GPT4All(model="model-name", allow_download=False) # or whatever settings
embeddings = GPT4AllEmbeddings(client=llm)
```

This should probably be added to the documentation

**Comment by DeskInvestor** [comment]
Did someone fix this? This is causing a lot of issues and not able to run GPT4ALLEmbeddings() without internet. 
Also @godlikemouse could you please let me know once you download the gpt4all repo what do you fix in it and how do you then import it into your project/server python files?

Please let me know, it will help a lot

**Comment by DeskInvestor** [comment]
> > Did someone fix this? This is causing a lot of issues and not able to run GPT4ALLEmbeddings() without internet. Also @godlikemouse could you please let me know once you download the gpt4all repo what do you fix in it and how do you then import it into your project/server python files?
> > Please let me know, it will help a lot
> 
> Hi @DeskInvestor,
> 
> I downloaded the `pygpt4all` from the source then patched `gpt4all.py` file.
> 
> For example:
> 
> ```
>     git clone --recurse-submodules https://github.com/nomic-ai/gpt4all.git
>     cd gpt4all/gpt4all-backend/
>     mkdir build
>     cd build
>     cmake ..
>     cmake --build . --parallel --config Release
> 
>     cd ../../gpt4all-bindings/python
>     pip install -e .
>     cd ../../..
> 
>     # Patch gpt4all/gpt4all-bindings/python/gpt4all/gpt4all.py
>     sed -i 's/n_threads=n_threads/n_threads=n_threads, allow_download=False/g' gpt4all/gpt4all-bindings/python/gpt4all/gpt4all.py
> ```
> 
> I basically added the parameter myself.

Thank you so much! @godlikemouse It will be helpful for any updates on the package I'd like to do.. 

I figured out another way to do it without having to patch which may be helpful for you as well. 

embeddings = GPT4AllEmbeddings(model_name=model_path,gpt4all_kwargs={'allow_download': False}) 

Passing gpt4all_kwargs={'allow_download': False} basically gets it to work directly.  

Hope this helps!

**Comment by godlikemouse** [comment]
Very nice, I like that way much more. Thanks for letting me know.
