### ISSUE TITLE
Issue: Issue providing LLMChain with multiple variables when memory is used

### ISSUE THREAD

**Issue by dreysco** [langchain-ai/langchain#8710]
### Issue you'd like to raise.

I'm having an issue with providing the LLMChain class with multiple variables when I provide it with a memory object. It works fine when I don't have memory attached to it. I followed the example given in this document: [LLM Chain Multiple Inputs](https://python.langchain.com/docs/modules/chains/foundational/llm_chain#additional-ways-of-running-llm-chain)

Here is the code that I used, which is mostly based on the example from the above documentation, besides I've added memory.

```
# Multiple inputs example

template = """Tell me a {adjective} joke about {subject}."""
prompt = PromptTemplate(template=template, input_variables=["adjective", "subject"])
llm = OpenAI(temperature=0)
memory = ConversationKGMemory(llm=llm)
llm_chain = LLMChain(prompt=prompt, llm=OpenAI(temperature=0))

llm_chain.predict(adjective="sad", subject="ducks")
```

With the above code, I get the following error:
```
ValueError: One input key expected got ['adjective', 'subject']
```

Python version: 3.11 
LangChain version: 0.0.250

### Suggestion:

Is there support for using multiple input variables when memory is involved?

**Comment by keenborder786** [comment]
I am not so sure why are you using `ConversationKGMemory` in this case. But still to clarify `ConversationKGMemory` needs to have one single input key. Since your prompt has two input keys, the `ConversationKGMemory` raises a ValuerError. Therefore you need to specify the single input key for `ConversationKGMemory` that you would like to use:

```python


template = """Tell me a {adjective} joke about {subject}."""
prompt = PromptTemplate(
    template=template, input_variables=["adjective", "subject"]
)
llm = OpenAI(temperature=0)
memory = ConversationKGMemory(llm=llm, input_key="adjective")
llm_chain = LLMChain(prompt=prompt, llm=OpenAI(temperature=0), memory=memory)

print(llm_chain.predict(adjective="sad", subject="ducks"))



```

**Comment by dreysco** [comment]
Just to clarify. Whenever **any** Memory is used, it will take at most one single input key?

**Comment by keenborder786** [comment]
No, that's not right. The number of input keys and Memory are independent, but the Memory requires a way to access its buffer through input keys. Therefore, you need to specify an input key for certain types of memory, such as VectorBasedMemory. This input key allows the VectorBased memory to identify which specific input it needs to compare against the documents in the Vector DB.

**Comment by keenborder786** [comment]
If you are satisfied, please close the issue.

**Comment by AndrewMacho** [comment]
I face similar issue while using `ConversationBufferWindowMemory`
after specifying the `history` key in memory it worked

template:
``` 
{history}

cusom key: {custom_key}
Human: {human_input}
Assistant:
```

chain:
```
 LLMChain(
            llm=ChatOpenAI(temperature=temperature, model=model),
            prompt=prompt,
            # verbose=True,
            memory=ConversationBufferWindowMemory(k=2, input_key='history')
            )            
```

**Comment by nikitacorp** [comment]
Oh, ok, I got it... I was facing the same issue, but adding `input_key='input'` resolved my problem, so if anyone needed to create LLMChain and then pass it into "custom" agent - here is slice my code:
```
...
memory = ConversationBufferMemory(memory_key="chat_history", **input_key='input'**)
readonlymemory = ReadOnlySharedMemory(memory=memory)

prompt = PromptTemplate(input_variables=["input", "chat_history", "custom_variable"], template=template)

filter_chain = LLMChain(
    llm=OpenAI(),
    prompt=prompt,
    verbose=True,
    memory=readonlymemory
)
llm_chain = LLMChain(llm=ChatOpenAI(temperature=0), prompt=prompt)
agent_test = ZeroShotAgent(llm_chain=filter_chain, tools=tools, verbose=True)
agent_chain_test = AgentExecutor.from_agent_and_tools(
    agent=agent_test, tools=tools, verbose=True, memory=memory
)
question = "What is ...?"
custom_variable= define_custom_variable(question)
res_agent = agent_chain_test.run(input=question,
                                                      custom_variable=custom_variable)
```
