### ISSUE TITLE
Getting NameError: name 'partition_pdf' is not defined when running "documents = loader.load()"

### ISSUE THREAD

**Issue by botchagalupe** [langchain-ai/langchain#8714]
### System Info

I have been running this code for weeks, and today it looks like something changed to break it. I'm using the following code snippets...

from langchain.document_loaders import DirectoryLoader
...
loader = DirectoryLoader(directory_path, glob='**/*.pdf')
documents = loader.load()

This is the error I am getting...

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-9-8159690dd515>](https://localhost:8080/#) in <cell line: 2>()
      1 loader = DirectoryLoader(directory_path, glob='**/*.pdf')
----> 2 documents = loader.load()
      3 print("Number of documents: ", len(documents))
      4 
      5 timestampit()

5 frames
[/usr/local/lib/python3.10/dist-packages/unstructured/partition/auto.py](https://localhost:8080/#) in partition(filename, content_type, file, file_filename, url, include_page_breaks, strategy, encoding, paragraph_grouper, headers, skip_infer_table_types, ssl_verify, ocr_languages, pdf_infer_table_structure, xml_keep_tags, data_source_metadata, **kwargs)
    219         )
    220     elif filetype == FileType.PDF:
--> 221         elements = partition_pdf(
    222             filename=filename,  # type: ignore
    223             file=file,  # type: ignore

NameError: name 'partition_pdf' is not defined

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

loader = DirectoryLoader(directory_path, glob='**/*.pdf')
documents = loader.load()

### Expected behavior

Loaded documents.

**Comment by botchagalupe** [comment]
It's been running successfully on 3.10 for several weeks without any changes. I'm pretty sure this is an error related to a recent change in Langchain.

**Comment by botchagalupe** [comment]
unstructured is installed. 

/usr/lib/python3.10# pip show unstructured
Name: unstructured
Version: 0.9.0
Summary: A library that prepares raw documents for downstream ML tasks.
Home-page: https://github.com/Unstructured-IO/unstructured
Author: Unstructured Technologies
Author-email: devops@unstructuredai.io
License: Apache-2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: chardet, filetype, lxml, nltk, python-magic, requests, tabulate
Required-by:

**Comment by eyurtsev** [comment]
Hi @botchagalupe, 

If you have a full stack trace that would be more helpful (the one included in your previous response is abbreviated). 

Based on that stack trace I'd check if this is an unstructured issue, since it's exception origins from unstructured complaining about being unable to resolve a function.

You could try upgrading/downgrading unstructured -- it's possible that unstructured got upgraded while bumping langchain version.

**Comment by botchagalupe** [comment]
Thanks For looking into this... 

Does this help?

Error loading documents
Traceback (most recent call last):
  File "<ipython-input-21-6037a390e7df>", line 5, in <cell line: 3>
    documents = loader.load()
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/directory.py", line 137, in load
    self.load_file(i, p, docs, pbar)
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/directory.py", line 94, in load_file
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/directory.py", line 88, in load_file
    sub_docs = self.loader_cls(str(item), **self.loader_kwargs).load()
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
  File "/usr/local/lib/python3.10/dist-packages/langchain/document_loaders/unstructured.py", line 171, in _get_elements
    return partition(filename=self.file_path, **self.unstructured_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/unstructured/partition/auto.py", line 221, in partition
    elements = partition_pdf(
NameError: name 'partition_pdf' is not defined

**Comment by FirstGalacticEmpire** [comment]
I'm experiencing exactly the same issue, which appeared after no code change, just update of langchain and I presume unstructured library.

**Comment by FirstGalacticEmpire** [comment]
After further experiments, I think it's causes by new releases of unstructured.
Downgrading to:
unstructured==0.7.12
Solved the issue. 
Wainting for official solution.

**Comment by botchagalupe** [comment]
That worked it. Thank You.

**Comment by johnda98** [comment]
doing the same.. trying to run a Langchain project.. uninstalling and trying  % python3 -m pip install unstructured==0.7.12

**Comment by TheFrancho** [comment]
> After further experiments, I think the error is caused by the new releases of unstructured. Downgrading to: unstructured==0.7.12 Solved the issue. Waiting for the official solution.

Downgrading unstructured worked so far, thx.

**Comment by keiru517** [comment]
Thank you @FirstGalacticEmpire !

**Comment by siidny** [comment]
> After further experiments, I think the error is caused by the new releases of unstructured. Downgrading to: unstructured==0.7.12 Solved the issue. Waiting for the official solution.

Worked for me too. Thanks so much !

**Comment by keiru517** [comment]
Thanks

**Comment by pcschreiber1** [comment]
Also worked for me, thanks!

**Comment by bobbyfongprivate** [comment]
> After further experiments, I think the error is caused by the new releases of unstructured.
> Downgrading to:
> unstructured==0.7.12
> Solved the issue.
> Waiting for the official solution.

Worked for me too. Thanks so much !

**Comment by tarockey** [comment]
I was running into this issue - for me the problem was that unstructured has several dependencies for cracking PDFs, but it doesn't expose that very well. The import statement for partition_pdf has an `if else` check to see if `pdf2image, pdfminer, and PIL` are all installed, but if they aren't it doesn't throw an error, it simply doesn't import the module.

Once I installed pdf2image, pdfminer (and it's subpackage pdfminer.six), and pillows, everything ran as expected.

**Comment by lhayana** [comment]
> I was running into this issue - for me the problem was that unstructured has several dependencies for cracking PDFs, but it doesn't expose that very well. The import statement for partition_pdf has an `if else` check to see if `pdf2image, pdfminer, and PIL` are all installed, but if they aren't it doesn't throw an error, it simply doesn't import the module.
> 
> Once I installed pdf2image, pdfminer (and it's subpackage pdfminer.six), and pillows, everything ran as expected.

this worked for me. Thanks!

**Comment by hsnaderi** [comment]
I'm getting this error in my jupyter notebook. I tried the above solution of putting in a specific version of unstructured that @FirstGalacticEmpire referenced. I also tried the additional packages that @tarockey suggested. Still nothing.

What's even stranger is there are no PDFs in the directory, so I wonder why it's even spending any time going through this.  Below is the error I'm getting:

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[15], line 2
      1 loader = DirectoryLoader("./articles","*.txt")
----> 2 index = VectorstoreIndexCreator().from_loaders([loader])

File ~/Library/Python/3.9/lib/python/site-packages/langchain/indexes/vectorstore.py:81, in VectorstoreIndexCreator.from_loaders(self, loaders)
     79 docs = []
     80 for loader in loaders:
---> 81     docs.extend(loader.load())
     82 return self.from_documents(docs)

File ~/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/directory.py:156, in DirectoryLoader.load(self)
    154 else:
    155     for i in items:
--> 156         self.load_file(i, p, docs, pbar)
    158 if pbar:
    159     pbar.close()

File ~/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/directory.py:105, in DirectoryLoader.load_file(self, item, path, docs, pbar)
    103         logger.warning(f"Error loading file {str(item)}: {e}")
    104     else:
--> 105         raise e
    106 finally:
    107     if pbar:

File ~/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/directory.py:99, in DirectoryLoader.load_file(self, item, path, docs, pbar)
     97 try:
     98     logger.debug(f"Processing file: {str(item)}")
---> 99     sub_docs = self.loader_cls(str(item), **self.loader_kwargs).load()
    100     docs.extend(sub_docs)
    101 except Exception as e:

File ~/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/unstructured.py:86, in UnstructuredBaseLoader.load(self)
     84 def load(self) -> List[Document]:
     85     """Load file."""
---> 86     elements = self._get_elements()
     87     self._post_process_elements(elements)
     88     if self.mode == "elements":

File ~/Library/Python/3.9/lib/python/site-packages/langchain/document_loaders/unstructured.py:172, in UnstructuredFileLoader._get_elements(self)
    169 def _get_elements(self) -> List:
    170     from unstructured.partition.auto import partition
--> 172     return partition(filename=self.file_path, **self.unstructured_kwargs)

File ~/Library/Python/3.9/lib/python/site-packages/unstructured/partition/auto.py:361, in partition(filename, content_type, file, file_filename, url, include_page_breaks, strategy, encoding, paragraph_grouper, headers, skip_infer_table_types, ssl_verify, ocr_languages, languages, detect_language_per_element, pdf_infer_table_structure, xml_keep_tags, data_source_metadata, metadata_filename, **kwargs)
    352     elements = _partition_md(
    353         filename=filename,
    354         file=file,
   (...)
    358         **kwargs,
    359     )
    360 elif filetype == FileType.PDF:
--> 361     _partition_pdf = _get_partition_with_extras("pdf")
    362     elements = _partition_pdf(
    363         filename=filename,  # type: ignore
    364         file=file,  # type: ignore
   (...)
    370         **kwargs,
    371     )
    372 elif (filetype == FileType.PNG) or (filetype == FileType.JPG) or (filetype == FileType.TIFF):

File ~/Library/Python/3.9/lib/python/site-packages/unstructured/partition/auto.py:113, in _get_partition_with_extras(doc_type, partition_with_extras_map)
    111 _partition_func = partition_with_extras_map.get(doc_type)
    112 if _partition_func is None:
--> 113     raise ImportError(
    114         f"partition_{doc_type} is not available. "
    115         f"Install the {doc_type} dependencies with "
    116         f'pip install "unstructured[{doc_type}]"',
    117     )
    118 return _partition_func

ImportError: partition_pdf is not available. Install the pdf dependencies with pip install "unstructured[pdf]"`

**Comment by hsnaderi** [comment]
I restarted my kernal and this particular error disappeared (but I'm getting other dependency issues). 

I was wondering why this is showing up as an error in my jupyter notebook but I have no issues when running the same code in pycharm

**Comment by hsnaderi** [comment]
just FYI latest error is

`ImportError: cannot import name 'PDFResourceManager' from 'pdfminer.converter' (/Users/haroonnaderi/Library/Python/3.9/lib/python/site-packages/pdfminer/converter.py)`

**Comment by truongquoc** [comment]
> After further experiments, I think the error is caused by the new releases of unstructured. Downgrading to: unstructured==0.7.12 Solved the issue. Waiting for the official solution.

Really helpful. Thanks for your comment

**Comment by dionis** [comment]
Terrific, work form me too, please fix unstructured issue.

**Comment by SaishSaw** [comment]
I am currently building a chatbot from pdf files. I was having same issue. One of the way i found was using pypdf
So langchain.document_loaders has PyPDFLoader for single files and PyPDFDirectoryLoader for accessing multiple files in same folder. This helps in loading the files without showing partition_pdf error.
Hope this helps.

**Comment by mlc-mlapis** [comment]
It's a problem related to the LangChain 0.1.3 (latest) when using Unstructured 0.12.2 (latest).
Everything works correctly when using `partition_pdf` separately, so it's installed and available.
```
from unstructured.partition.pdf import partition_pdf
test_elements = partition_pdf("xxx.pdf")
```

**Comment by mlc-mlapis** [comment]
@dosu-bot As I wrote above, I am using the latest versions as **LangChain 0.1.3** (latest) and **Unstructured 0.12.2** (latest). **The environment is Python 3.10.5.** Because of the fact that if you import `from unstructured.partition.pdf import partition_pdf` separately (outside of the `from langchain.document_loaders import DirectoryLoader`), it works correctly, I tried to explain such a behavior.

The error message `ImportError: partition_pdf is not available. Install the pdf dependencies with pip install "unstructured[pdf]"` comes from the call `_partition_pdf = _get_partition_with_extras("pdf")` of the `unstructured > partition > auto.py` code.

```
def _get_partition_with_extras(
    doc_type: str,
    partition_with_extras_map: Optional[Dict[str, Callable]] = None,
):
    if partition_with_extras_map is None:
        partition_with_extras_map = PARTITION_WITH_EXTRAS_MAP
    _partition_func = partition_with_extras_map.get(doc_type)
    if _partition_func is None:
        raise ImportError(
            f"partition_{doc_type} is not available. "
            f"Install the {doc_type} dependencies with "
            f'pip install "unstructured[{doc_type}]"',
        )
    return _partition_func
```
and
```
pdf_imports = ["pdf2image", "pdfminer", "PIL"]
if all(dependency_exists(dep) for dep in pdf_imports):
    from unstructured.partition.pdf import partition_pdf

    PARTITION_WITH_EXTRAS_MAP["pdf"] = partition_pdf
```
There are required ["pdf2image", "pdfminer", "PIL"] dependencies, and one of them, the PIL library, stands for Python Imaging Library, and it's the original library that enabled Python to deal with images. PIL was discontinued in 2011 and only supported Python 2.

That also explains the problem because `PIL` can't be installed in the Python v3 environment. The `Pillow` library should probably replace it. That dependency condition is not applied when you import `from unstructured.partition.pdf import partition_pdf` separately.

**Comment by mlc-mlapis** [comment]
As I described in my previous comment, it seems that the problem is on the unstructured library side, and here is the issue I have created in its repository: https://github.com/Unstructured-IO/unstructured/issues/2456. It would be nice of you to support a solution to the problem and express your opinion there. Finally, some consequences affect the **LangChain** side also.

**Comment by raksrivastava** [comment]
> After further experiments, I think the error is caused by the new releases of unstructured. Downgrading to: unstructured==0.7.12 Solved the issue. Waiting for the official solution.

Getting below error on installing this version. register_finder(pkgutil.ImpImporter, find_on_path) ^^^^^^^^^^^^^^^^^^^ AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by infogain-rishabh** [comment]
> > After further experiments, I think the error is caused by the new releases of unstructured. Downgrading to: unstructured==0.7.12 Solved the issue. Waiting for the official solution.
> 
> Getting below error on installing this version. register_finder(pkgutil.ImpImporter, find_on_path) ^^^^^^^^^^^^^^^^^^^ AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output. note: This error originates from a subprocess, and is likely not a problem with pip.


I am also encountering the same error while installing the unstructured==0.7.12. Any suggestions on this?

**Comment by wahidpanda** [comment]
> ### System Info
> I have been running this code for weeks, and today it looks like something changed to break it. I'm using the following code snippets...
> 
> from langchain.document_loaders import DirectoryLoader ... loader = DirectoryLoader(directory_path, glob='**/*.pdf') documents = loader.load()
> 
> This is the error I am getting...
> 
> NameError Traceback (most recent call last) in <cell line: 2>() 1 loader = DirectoryLoader(directory_path, glob='**/*.pdf') ----> 2 documents = loader.load() 3 print("Number of documents: ", len(documents)) 4 5 timestampit()
> 
> 5 frames [/usr/local/lib/python3.10/dist-packages/unstructured/partition/auto.py](https://localhost:8080/#) in partition(filename, content_type, file, file_filename, url, include_page_breaks, strategy, encoding, paragraph_grouper, headers, skip_infer_table_types, ssl_verify, ocr_languages, pdf_infer_table_structure, xml_keep_tags, data_source_metadata, **kwargs) 219 ) 220 elif filetype == FileType.PDF: --> 221 elements = partition_pdf( 222 filename=filename, # type: ignore 223 file=file, # type: ignore
> 
> NameError: name 'partition_pdf' is not defined
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [ ]  The official example notebooks/scripts
> * [x]  My own modified scripts
> 
> ### Related Components
> * [ ]  LLMs/Chat Models
> * [ ]  Embedding Models
> * [ ]  Prompts / Prompt Templates / Prompt Selectors
> * [ ]  Output Parsers
> * [x]  Document Loaders
> * [ ]  Vector Stores / Retrievers
> * [ ]  Memory
> * [ ]  Agents / Agent Executors
> * [ ]  Tools / Toolkits
> * [ ]  Chains
> * [ ]  Callbacks/Tracing
> * [ ]  Async
> 
> ### Reproduction
> loader = DirectoryLoader(directory_path, glob='**/*.pdf') documents = loader.load()
> 
> ### Expected behavior
> Loaded documents.

pip install unstructured==0.7.12
