### ISSUE TITLE
ChromaDB integration should properly handle the new Ephemeral/Persistent client objects in recent Chroma version.

### ISSUE THREAD

**Issue by JackLeick** [langchain-ai/langchain#8719]
With the new Chroma version introducing EphemeralClient and PersistentClient objects, I believe the LangChain integration should be updated to properly handle this.

Below is the relevant code, I believe, where this should be done in the Chroma constructor (chroma.py)

```python
            elif persist_directory:
                # Maintain backwards compatibility with chromadb < 0.4.0
                major, minor, _ = chromadb.__version__.split(".")
                if int(major) == 0 and int(minor) < 4:
                    _client_settings = chromadb.config.Settings(
                        chroma_db_impl="duckdb+parquet",
                    )
                else:
                    _client_settings = chromadb.config.Settings(is_persistent=True)
                _client_settings.persist_directory = persist_directory
            else:
                _client_settings = chromadb.config.Settings()
            self._client_settings = _client_settings
            self._client = chromadb.Client(_client_settings)
            self._persist_directory = (
                _client_settings.persist_directory or persist_directory
            )
```

My thought, is set self._client to EphemeralClient or PersistentClient depending on if persist_directory is used instead of the old chromadb.Client way.

Is there any work being done on this? Noticing the comment about chromadb 0.4.0, it seems like its been noted, but not corrected.

Currently I can't figure out how to make this work in the current Chroma integration without accessing the PersistentClient directly, then passing it in to Chroma constructor. Here is how I am doing it currently:

```python
client = chromadb.PersistentClient(path=persist_directory, settings=settings)
db = Chroma(
    client=client,
    embedding_function=embedding_function,
    client_settings=settings,
    persist_directory=persist_directory
)
```

**Comment by peidaqi** [comment]
The new EphemeralClient() is just Client() with settings.is_persistent = False (default).

See this for details:
https://github.com/chroma-core/chroma/blob/c387e1d60190e0d9c5687748c8f8e75b54e8a61b/chromadb/__init__.py#L52

**Comment by JackLeick** [comment]
Duh.... Thank you, can't believe I missed that. The langchain implementation seems right on in that case. Closing this.
