### ISSUE TITLE
on_llm_start callback doesn't change the prompts sent to LLM

### ISSUE THREAD

**Issue by zizhong** [langchain-ai/langchain#8725]
### System Info

Python 3.10.12
langchain                                    0.0.233

### Who can help?

@agola11

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from typing import Dict, Union, Any, List

from langchain.callbacks.base import BaseCallbackHandler
from langchain.schema import AgentAction
from langchain.agents import AgentType, initialize_agent, load_tools
from langchain.callbacks import tracing_enabled
from langchain.llms import OpenAI
from langchain.schema.agent import AgentAction
from langchain.schema.output import LLMResult
from uuid import UUID

class MyCustomHandlerOne(BaseCallbackHandler):
    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> Any:
        print(f"on_llm_start {prompts}")
        prompts[0] = "Tell me a joke?"
        print(f"on_llm_start {prompts}")

import langchain
langchain.verbose = True
langchain.debug = True

handler1 = MyCustomHandlerOne()
llm = OpenAI(temperature=0, streaming=True, callbacks=[handler1], verbose=True)
print(llm.__call__("""Context : Mr. Carl Smith is a 31-year-old man who has been experiencing homelessness 
                   on and off for all his adult life.
                   Questioin: How old is Mr. Carl Smith?"""))
```

The output is
```
on_llm_start ['Context : Mr. Carl Smith is a 31-year-old man who has been experiencing homelessness \n                   on and off for all his adult life.\n                   Questioin: How old is Mr. Carl Smith?']
on_llm_start ['Tell me a joke?']
[llm/start] [1:llm:OpenAI] Entering LLM run with input:
{
  "prompts": [
    "Tell me a joke?"
  ]
}
[llm/end] [1:llm:OpenAI] [699.067ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "\n\nAnswer: Mr. Carl Smith is 31 years old.",
        "generation_info": {
          "finish_reason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llm_output": {
    "token_usage": {},
    "model_name": "text-davinci-003"
  },
  "run": null
}


Answer: Mr. Carl Smith is 31 years old.
```

### Expected behavior

LLM will respond to the new prompt set by the callback

**Comment by zizhong** [comment]
@agola11 @hwchase17 is this true that `callback is not designed to modify the prompts`?

**Comment by zizhong** [comment]
The `on_chain_start` can actually modify the input which makes `callback is not designed to modify the prompts` questionable.

**Comment by dmyoung9** [comment]
`on_chain_start` ≠ `on_llm_start`

**Comment by zizhong** [comment]
@dmyoung9 Yes I understand that. My point is that different handlers are better to provide consistent user experience. It doesn't feel right that `on_chain_start` can modify the input but `on_llm_start` cannot.

**Comment by dmyoung9** [comment]
What is the use case here? Why would you need to modify prompts after they've been sent?

**Comment by zizhong** [comment]
> Why would you need to modify prompts after they've been sent?

@dmyoung9 I'm assuming the on_llm_start will run before the prompts sent to LLM. My team is writing a service doing prompt anonymization, which would be run before the prompts sent to LLM. Do you think `on_llm_start` is the right hook to add the callback? Thanks!

**Comment by zizhong** [comment]
Right. Integrating to Langchain would provide better user experiences.

**Comment by dmyoung9** [comment]
Are you not already integrating Langchain?

**Comment by zizhong** [comment]
From 
> It seems like a far simpler approach to modify the prompt before you send it to the model in the first place 🤔

I'm assuming the solution you are suggesting is 
```
# user app
prompts = ...
transformed_prompts = ...
Run chain(transformed_prompts)
```

What I'm trying to achieve

```
# some lib function
class CallBackHandler(...)
  def on_llm_start(...)
        transformed_prompts = ...
       return transformed_prompts
```

```
# user app
Run chain(prompts, callbacks=[CallBackHandler()])
```

which will make the user's life easier.

What do you think?

**Comment by dmyoung9** [comment]
From a user standpoint, those would be equivalent.

From a developer (you) standpoint, what is the drawback of transforming the prompt *after* the user's original input is received, but *before* you call your chain?

**Comment by zizhong** [comment]
> From a developer (you) standpoint, what is the drawback of transforming the prompt after the user's original input is received, but before you call your chain?

Hmm, I'm not the developer exactly but more of a lib developer. The user of the lib util is the developer. The second solution will reduce the effort for the developer to integrate the lib util.

**Comment by dmyoung9** [comment]
Ah, that makes more sense.

**Comment by 4wuyoon** [comment]
I would like to modify the prompt in the `on_llm_start` as well,
because I want to create a safeguard to prevent users from experiencing errors with the LLM API by exceeding the prompt's token limit due to large `observation` of `tool`.

The errors occur occasionally as the `tool` is called multiple times... 😥

**Comment by zizhong** [comment]
@4wuyoon unfortunately, from Langchain team, better not to do it this way.

**Comment by huichen5796** [comment]
Hi, if anyone is still interested in this problem and needs a not elegant but useful solution 
-> do it within `AgentExecutor.iter()` instead of using `on_llm_start` of `AgentExecutor.invoke()`:

I encountered a similar problem. I hope that when the agent uses multiple tools in sequence, it can konw the instrument status changes caused by the previous tool when using the next tool. Therefore, the status will be passed into llm as a prompt, and the prompt must be updated after calling previous tool (before start llm to call next tool). That is how i solve it: 

Let's assume your prompt looks like this
```python
"""you name is {agent_name}"""
```

and you have a AgentExecutor
```
agent_executor = AgentExecutor(agent=agent, tools=tools)
```
when you use `AgentExecutor.iter()`, you can modify the parameter `_input` passed into the iterator within the iterator like this:
```
agent_iter = agent_executor.iter(
            {
                "agent_name": old_name,
            }
        )
for step in agent_iter:
        agent_iter._inputs['agent_name'] = new_name
```

This will change the parameters `agent_name` passed in prompt every time the agent runs llm and uses a new tool.

and you just add `input` attr on last `step` outside the iterator to get the same result as using `invoke` at the end:
```
step["input"] = input
return step
```

you can check the change of prompt by using `on_llm_start`:

```
class MyCustomHandler(BaseCallbackHandler):
    def on_llm_start(
        self, serialized: Dict[str, Any], prompts: List[str], **kwargs: Any
    ) -> Any:
        print(f"\nPrompt:\n{prompts[0]}")
llm = ChatOpenAI(
        temperature=0,
        model=model,
        callbacks=[MyCustomHandler()],
    )
agent = create_openai_functions_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools)
agent_iter = agent_executor.iter(
            {
                "agent_name": old_name,
            }
        )
for step in agent_iter:
        agent_iter._inputs['agent_name'] = new_name
step["input"] = input
print(step)
```

please tell me if there is a elegant solution :-)
