### ISSUE TITLE
Agent does not recognize chat history (Missing some input keys: {'chat_history'})

### ISSUE THREAD

**Issue by lCrashl** [langchain-ai/langchain#8746]
### Issue you'd like to raise.

Hey, my agent won't recognize any chat history. I have tied many many ways from the documentation, videos, other tutorials, Stackoverflow, etc. I cant find out a way how it works for my setup:

I have tried with different types of memory:
`memory = ConversationBufferWindowMemory(memorykey="chat_history", k=3, return_messages=True,)`
`memory = ConversationSummaryBufferMemory(llm=llm, memory_key="chat_history", return_messages=True)`

Here is how I initialize the agent:
```
conversational_agent = initialize_agent(
    agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=3,
    memory=memory,
)
```
I can't seem to pass the chat_history. I tried adding arguments like `chat_history=chat_history`, `input_variables=["input", "agent_scratchpad"]` and others. Even separately defining the `kwargs` with the chat_history (`e.g. kwargs=["chat_history"]` and other ways).

Anyone has an idea how to set this up?

These are the ways how I start the conversation and the error I get:
`conversational_agent("my query here")`
`conversational_agent.run(input="my query here", chat_history=chat_history)`

Error I get every time: `ValueError: Missing some input keys: {'chat_history'}`

### Suggestion:

There are so many ways to set up an agent and the syntax is all different it seems. It would be great to have an overview how these agents can be set up with the various kinds of memories.

**Comment by wnmurphy** [comment]
`Missing some input keys: {'chat_history'}` means the prompt has variables defined that aren't passed in to the chain when it runs.

Your issue may be that `initialize_agent` doesn't seem to support a `memory` variable. You should drill down into the class you're using to verify what it supports. I haven't played with agents yet, but you might confirm that they support using memory, which is mostly for chat chains

**Comment by pvangara** [comment]
I am facing same issue, where chat_history is not working. Any suggestions on how to make it work?

**Comment by wnmurphy** [comment]
One option would be to pass in the chat history as a partial variable to the PromptTemplate, prior to the chain run. This basically pre-injects whatever you want.

Example here: https://wnmurphy.com/creating-a-versatile-multi-prompt-chatbot-with-memory-and-a-data-store-in-langchain/#helper-function---generating-the-destination-chains

**Comment by wnmurphy** [comment]
Although... if you're passing `memory` (your chat history) when you initialize the agent, I would assume that already injects the chat history, so you don't need to specify that as an input variable yourself. 

When you call `initialize_agent`, it should pass `memory` as a `kwarg` down into the `AgentExecutor` that gets returned.

**Comment by pvangara** [comment]
Thanks for the quick responses:
I am able to pass that problem by using ConversationChatAgent.create_prompt instead of ZeroShotAgent.create_prompt method:
---
    prompt = ConversationalChatAgent.create_prompt(
        tools,
        system_message=prefix + format_instructions
    )
       
    llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo")
    
    memory = ConversationBufferMemory(memory_key='chat_history')
    
    agent = initialize_agent(
        tools=tools,
        llm=llm,
        agent_type=AgentType.CHAT_CONVERSATIONAL_REACT_DESCRIPTION,
        verbose=True,
        prompt=prompt,
        memory=memory,
        handle_parsing_errors=True,
        max_iterations=5
    )

Now, have a different problem, when I ask the agent about "What was my first question?", it doesn't refer to the chat_history and respond. It says it doesn't know the history.
Any suggestions! 
Thanks in advance!
P.S: It's no more related to this issue. Thnx

**Comment by i-sanjay-cs** [comment]
I dont want the Memory for my agents but still getting error if i dont iniatlize it 

```
Error during satisfaction check: Missing some input keys: {'chat_history'}
```

My code 

```


def create_agent(agent_type):
    global global_agent  
    
    if global_agent is None:  
        agent_config = AGENT_SETTINGS.get(agent_type)
        if not agent_config:
            raise ValueError(f"Invalid agent type: {agent_type}")

        chat = get_llm(
            VENDOR.GOOGLE_GENAI,
            agent_config["llm_model"],
            temperature=agent_config["temperature"],
            max_new_tokens=agent_config["max_new_tokens"],
        )

        global_agent = initialize_agent(
            [],
            chat,
            agent=AgentType.CONVERSATIONAL_REACT_DESCRIPTION,
            handle_parsing_errors=True,
        )
    
    return global_agent
    
    ```
