### ISSUE TITLE
Just install Langchain and getting Import error from typing extensions

### ISSUE THREAD

**Issue by RishabhDey** [langchain-ai/langchain#8775]
### System Info

Latest versions of langchain at the current time. 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Literally just pip installed lang-chain and getting the error: ImportError: cannot import name 'dataclass_transform' from 'typing_extensions'. I tried upgrading pydantic and typing_extensions which only make the problem worse. 

### Expected behavior

No import errors.

**Comment by tomasfernandez1212** [comment]
I also have issues because of this. Langchain is using an outdated version of pydantic and in my project I need one of pydantic's newest features (model_post_init method for BaseModels). Since installing langchain downgrades pydantic, I can't use langchain.

**Comment by keenborder786** [comment]
Yes Langchain is currently not supporting Pydantic version >= 2.0.0
