### ISSUE TITLE
"n" hyperparmeter doesn't work in ChatOpenAI

### ISSUE THREAD

**Issue by bergr7** [langchain-ai/langchain#8789]
### System Info

Name: langchain
Version: 0.0.250

Python=3.11.4

### Who can help?

@agola @hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
llm = ChatOpenAI(
        model="gpt-4",
        temperature=0.0,
        top_p=1.0,
        n=20,
        max_tokens=30
    )

results = llm(chat_prompt.format_prompt(
        inputs_description=vars["inputs_description"],
        task_description=vars["task_description"],
        criteria=vars["criteria"],
        criteria_description=vars["criteria_description"],
        eval_steps=vars["eval_steps"],
        input=vars["input"],
        input_type=vars["input_type"],
        output=vars["output"],
        output_type=vars["output_type"]
    ).to_messages())
```

### Expected behavior

I was expecting to get a response with 20 results, instead of just one since I set n=20. This is the behaviour when using Openai SDK.

**Comment by shunk031** [comment]
Hi. I'm using `langchain >= 0.3.0`, and it looks like the solution presented here, using `LLMChain`, will be no longer valid in the future [due to it being deprecated](https://python.langchain.com/api_reference/langchain/chains/langchain.chains.llm.LLMChain.html#llmchain). Here is my environment.


```
> uv pip list | grep lang

langchain                0.3.22
langchain-aws            0.2.18
langchain-core           0.3.49
langchain-openai         0.3.11
langchain-text-splitters 0.3.7
langgraph                0.3.24
langgraph-checkpoint     2.0.24
langgraph-prebuilt       0.1.7
langgraph-sdk            0.1.60
langsmith                0.3.22
```

Here is the code I used. Is there any solution?

```python
from langchain.chat_models import init_chat_model

llm = init_chat_model(
    model_provider="openai",
    model="gpt-4o",
    n=10, # Added this option but it seems to be ignored ;(
)

messages = [
    (
        "system",
        "You are a helpful assistant that translates English to French. Translate the user sentence.",
    ),
    (
        "human",
        "I love programming.",
    ),
]

ai_msg = llm.invoke(messages)
print(ai_msg)

```
