### ISSUE TITLE
 File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__ pydantic.error_wrappers.ValidationError: 1 validation error for Document"

### ISSUE THREAD

**Issue by data-xyz** [langchain-ai/langchain#8794]
### System Info

Traceback:

 docsearch.similarity_search(
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py", line 162, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/pinecone.py", line 136, in similarity_search_with_score
    docs.append((Document(page_content=text, metadata=metadata), score))
  File "/usr/local/lib/python3.9/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Document"
page_content  str type expected (type=type_error.str)

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

langchain pinecone similarity_search_with_score
 docs.append((Document(page_content=text, metadata=metadata), score))
seem to raise error when page_content is not an string type 
while  when we wrote the document to the pinecone using pdf loader 
maybe the loader produce something unexpected.
it should be a bug

### Expected behavior

No erro raised

**Comment by htang2012** [comment]
hit the same issue.

**Comment by vivekananth** [comment]
hitting same issue , any solution ?

**Comment by ionescofung** [comment]
same issue.

**Comment by poojitharamachandra** [comment]
any solution yet?

**Comment by EricPostMaster** [comment]
Getting the same issue as well. It was working for part of the evening and then suddenly started giving the error.

**Comment by chann-elevait** [comment]
same issue, I suddenly got this error. Any solution?
