### ISSUE TITLE
Issue: Amazon Bedrock can't load my credentials when called from a Lambda function

### ISSUE THREAD

**Issue by MustaphaU** [langchain-ai/langchain#8800]
### Issue you'd like to raise.

Bedrock can't seem to load my credentials when used within a Lambda function. My AWS credentials were set up in my local environment using environment variables. When I use the bedrock class directly, it is able to load my credentials and my code runs smoothly. Here is the RetrievalQA function that utilizes the bedrock class: 

```
def qa(query):
    secrets = json.loads(get_secret())
    kendra_index_id = secrets['kendra_index_id']


    llm = Bedrock(model_id="amazon.titan-tg1-large", region_name='us-east-1')
    llm.model_kwargs = {"maxTokenCount": 4096}
    

    retriever = AmazonKendraRetriever(index_id=kendra_index_id)
    
    prompt_template = """
    {context}
    {question} If you are unable to find the relevant article, respond 'I can't generate the needed content based on the context provided.'
    """
    
    PROMPT = PromptTemplate(
    template=prompt_template, input_variables=["context", "question"])
    
    chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    verbose=True,
    chain_type_kwargs={
    "prompt": PROMPT
    }
    )
    
    return chain(query)
```

The above code runs without issues when used directly. However, when used within a lambda function, it fails. The scripts file used to build my lambda function uses the bedrock class as written above, however, I run into the `validation errors` when I invoke the Lambda function. 
`
{
  "errorMessage": "1 validation error for Bedrock\n__root__\n  Could not load credentials to authenticate with AWS client. Please check that credentials in the specified profile name are valid. (type=value_error)",
  "errorType": "ValidationError",
  "requestId": "b772f236-f582-4308-8af5-b5a418d4327f",
  "stackTrace": [
    "  File \"/var/task/main.py\", line 62, in handler\n    response = qa(query)\n",
    "  File \"/var/task/main.py\", line 32, in qa\n    llm = Bedrock(model_id=\"amazon.titan-tg1-large\", region_name='us-east-1',) #client=BEDROCK_CLIENT)\n",
    "  File \"/var/task/langchain/load/serializable.py\", line 74, in __init__\n    super().__init__(**kwargs)\n",
    "  File \"pydantic/main.py\", line 341, in pydantic.main.BaseModel.__init__\n    raise validation_error\n"
  ]
`

As clearly indicated by the error message, bedrock couldn't load credentials. 

### Suggestion:

I have looked at the official documentation of the [bedrock class](https://github.com/langchain-ai/langchain/blob/b786335dd10902489f87a536ee074d747b6df370/libs/langchain/langchain/llms/bedrock.py#L51) but still do not understand why my code fails. Any help will be appreciated. @3coins @jasondotparse @hwchase17

**Comment by MustaphaU** [comment]
Sorry I don't think is an access issue since the IAM role associated with the Lambda function has full access to bedrock. Please see below:
![fn_resource](https://github.com/langchain-ai/langchain/assets/123378149/3d90f6dc-4a81-49c1-bb47-b74b71fbb458)
![bedrock_access_policy](https://github.com/langchain-ai/langchain/assets/123378149/42cc61d3-4d0b-4f82-ae62-04d63c473765)

**Comment by jonathan260589** [comment]
Hi @MustaphaU,

In the end, did you find a solution? I would also be interested in running Bedrock from Lambda and I guess I am going to run in the same problem...

**Comment by MustaphaU** [comment]
Hi @jonathan260589 , I haven't found a solution till date.

**Comment by gel001** [comment]
I haven't actually tried this in Lambda, but are you packaging the boto3 that comes with Bedrock with your Lambda function?

I ran around in circles for a bit running locally with the real error being this line:

            values["client"] = session.client("bedrock", **client_params)

...because the boto3 client that is the default pip install doesn't have support for the "bedrock" service. Once I made sure to use the bedrock-aware boto3 my auth issues went away.

**Comment by hghandri** [comment]
Hi,

I've faced a same issue and solved it via this link : https://github.com/aws-samples/amazon-bedrock-workshop/blob/77abc340c4548ae014f2b948bb607c7c3b8cf89c/00_Intro/bedrock_boto3_setup.ipynb

Bedrock service is not available in live is still in preview, you have to install manually a specific version of Boto3 to access this new feature.

I've tested and everything works fine.


Good Luck.

**Comment by MustaphaU** [comment]
> I haven't actually tried this in Lambda, but are you packaging the boto3 that comes with Bedrock with your Lambda function?
> 
> I ran around in circles for a bit running locally with the real error being this line:
> 
> ```
>         values["client"] = session.client("bedrock", **client_params)
> ```
> 
> ...because the boto3 client that is the default pip install doesn't have support for the "bedrock" service. Once I made sure to use the bedrock-aware boto3 my auth issues went away.

Yes, both new wheels (boto3 and botocore) are in my deployment package. The issue is not with `bedrock` being unsupported, otherwise the error would read "Unknown service: 'bedrock'. `bedrock` is an unknown service ........"

**Comment by MustaphaU** [comment]
> Hi,
> 
> I've faced a same issue and solved it via this link : https://github.com/aws-samples/amazon-bedrock-workshop/blob/77abc340c4548ae014f2b948bb607c7c3b8cf89c/00_Intro/bedrock_boto3_setup.ipynb
> 
> Bedrock service is not available in live is still in preview, you have to install manually a specific version of Boto3 to access this new feature.
> 
> I've tested and everything works fine.
> 
> Good Luck.

Yes, both new wheels (boto3 and botocore) are in my deployment package. The issue is not with `bedrock` being unsupported, otherwise the error would read "Unknown service: 'bedrock'. `bedrock` is an unknown service ........"

**Comment by hghandri** [comment]
Fine if you already have done with package installation then you could write something like that : 


```
from boto3
from langchain.llms import Bedrock
session = boto3.Session(region_name = 'us-west-2')
boto3_bedrock = session.client(service_name="bedrock")

# Langchain LLM
llm = Bedrock(client=boto3_bedrock, model_id="anthropic.claude-v2", region_name='us-west-2')
```

in this case you bypass your first issue and your needs credential are provided by lambda role and not from profile. I made it works on Lambda and it works for me

**Comment by gel001** [comment]
That Exception block will swallow the unknown service exception and replace it with the generic credentials one:

`        except Exception as e:
            raise ValueError(
                "Could not load credentials to authenticate with AWS client. "
                "Please check that credentials in the specified "
                "profile name are valid."
            ) from e
`

As a test you could do the code like @hghandri suggests, that boto3_bedrock = session.client() call will tell you for sure if those Bedrock boto3 dependencies are really included or not.

**Comment by MustaphaU** [comment]
> Fine if you already have done with package installation then you could write something like that :
> 
> ```
> from boto3
> from langchain.llms import Bedrock
> 
> session = boto3.Session(region_name = 'us-west-2')
> boto3_bedrock = session.client(service_name="bedrock")
> 
> # Langchain LLM
> llm = Bedrock(client=boto3_bedrock, model_id="anthropic.claude-v2", region_name='us-west-2')
> ```
> 
> in this case you bypass your first issue and your needs credential are provided by lambda role and not from profile. I made it works on Lambda and it works for me

Unfortunately, I had tried this in one of my attempts to fix the issue but it didn't work as I was faced with another error. _"Unknown service": ''bedrock.  `bedrock` is an unknown service......_, even though the boto wheels were installed in the deployment package. Here is a snapshot of the deployment package used to build the lambda function. 
![image](https://github.com/langchain-ai/langchain/assets/123378149/adf512d7-fe41-47ee-89f5-bc71658fd6e6)

**Comment by MustaphaU** [comment]
> That Exception block will swallow the unknown service exception and replace it with the generic credentials one:
> 
> ` except Exception as e: raise ValueError( "Could not load credentials to authenticate with AWS client. " "Please check that credentials in the specified " "profile name are valid." ) from e`
> 
> As a test you could do the code like @hghandri suggests, that boto3_bedrock = session.client() call will tell you for sure if those Bedrock boto3 dependencies are really included or not.

Unfortunately, I had tried this in one of my attempts to fix the issue but it didn't work as I was faced with another error. _"Unknown service": ''bedrock.  `bedrock` is an unknown service......_, even though the boto wheels were installed in the deployment package. 
Here is a snapshot of the deployment package used to build the lambda function. 
![image](https://github.com/langchain-ai/langchain/assets/123378149/adf512d7-fe41-47ee-89f5-bc71658fd6e6)

And here is the query function in my main.py: 
![image](https://github.com/langchain-ai/langchain/assets/123378149/f1ceb875-e45a-462d-88d2-148a5d98a147)

Note: I do not encounter any of these issues when working in a SageMaker notebook or other environments.

**Comment by gel001** [comment]
Not sure what to tell you, that error you seeing is almost assuredly because it doesn't have the right version of boto3.

**Comment by MustaphaU** [comment]
Hence, my confusion. Does lambda override the installed (custom) boto wheels with the default, I doubt it.

**Comment by MustaphaU** [comment]
> Not sure what to tell you, that error you seeing is almost assuredly because it doesn't have the right version of boto3.

Hence, my confusion. Does lambda override the installed (custom) boto wheels with the default, I doubt it.

**Comment by hghandri** [comment]
Hi @MustaphaU, 
Here it's clearly an issue with version of Boto3 and botocore.
Did you install a specific dependencies like in documentation ?

Here the code : 

`
#!/bin/sh

set -e

echo "(Re)-creating directory"
rm -rf ./dependencies
mkdir ./dependencies
cd ./dependencies
echo "Downloading dependencies"
curl -sS https://d2eo22ngex1n9g.cloudfront.net/Documentation/SDK/bedrock-python-sdk.zip > sdk.zip
echo "Unpacking dependencies"
# (SageMaker Studio system terminals don't have `unzip` utility installed)
if command -v unzip &> /dev/null
then
    unzip sdk.zip && rm sdk.zip && echo "Done"
else
    echo "'unzip' command not found: Trying to unzip via Python"
    python -m zipfile -e sdk.zip . && rm sdk.zip && echo "Done"
fi
`

Did you use docker image with Lambda ? Because all the library you need are too heavy to deployed simply in standard lambda package. Max allowed package size is 50MB.
On my side  I have mounted an EFS where everything installed on it.

**Comment by LogeshwaranV** [comment]
> > I haven't actually tried this in Lambda, but are you packaging the boto3 that comes with Bedrock with your Lambda function?
> > I ran around in circles for a bit running locally with the real error being this line:
> > ```
> >         values["client"] = session.client("bedrock", **client_params)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ...because the boto3 client that is the default pip install doesn't have support for the "bedrock" service. Once I made sure to use the bedrock-aware boto3 my auth issues went away.
> 
> Yes, both new wheels (boto3 and botocore) are in my deployment package. The issue is not with `bedrock` being unsupported, otherwise the error would read "Unknown service: 'bedrock'. `bedrock` is an unknown service ........"

How did you overcome the unknown service error? I was trying to access the bedrock from boto3 from wheel file. I was able to run in my local but getting the unknown service error in the lambda container image. can you provide any steps I could I follow to overcome this issue?

**Comment by MustaphaU** [comment]
> > > I haven't actually tried this in Lambda, but are you packaging the boto3 that comes with Bedrock with your Lambda function?
> > > I ran around in circles for a bit running locally with the real error being this line:
> > > ```
> > >         values["client"] = session.client("bedrock", **client_params)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ...because the boto3 client that is the default pip install doesn't have support for the "bedrock" service. Once I made sure to use the bedrock-aware boto3 my auth issues went away.
> > 
> > 
> > Yes, both new wheels (boto3 and botocore) are in my deployment package. The issue is not with `bedrock` being unsupported, otherwise the error would read "Unknown service: 'bedrock'. `bedrock` is an unknown service ........"
> 
> How did you overcome the unknown service error? I was trying to access the bedrock from boto3 from wheel file. I was able to run in my local but getting the unknown service error in the lambda container image. can you provide any steps I could I follow to overcome this issue?

Ensure you're using the boto3 and botocore wheels that support Bedrock. Refer to page 21 of the [Amazon Bedrock User Guide](https://d2eo22ngex1n9g.cloudfront.net/Documentation/BedrockUserGuide.pdf) . The required files are `boto3-1.28.21-py3-none-any.whl` and `botocore-1.31.21-py3-none-any.whl` available in the [bedrock python sdk](https://d2eo22ngex1n9g.cloudfront.net/Documentation/SDK/bedrock-python-sdk.zip). Note that these wheels aren't on the official PIP repository, so you'll need to download and install them manually.

**Comment by rodbutters** [comment]
I still am having this issue with the production release of boto3. Gave my test lambda admin credentials. Is anyone having success with this?

**Comment by acastro2** [comment]
I'm facing the same problem, locally with my credentials in the `~/.aws/credentials` it works just fine, but in the Lambda it fails with:

```
  "errorMessage": "1 validation error for Bedrock\n__root__\n  Could not load credentials to authenticate with AWS client. Please check that credentials in the specified profile name are valid. (type=value_error)",
```

I don't think the upgrades above about `boto3` make sense anymore since it is already in version 1.28.63 and clearly already supports bedrock.
