### ISSUE TITLE
How to pass a CSV file or a dataframe to Pandas REPL tool in Langchain?

### ISSUE THREAD

**Issue by moayadeldin** [langchain-ai/langchain#8821]
I am trying to utilize Python Repl Tool in langchain with a CSV file and send me the answer based on the CSV file content. The problem is that it gets the action_input step of writing the code to execute right. However, it fails to answer because it couldn't determine the dataframe it should run the code on.

For example, I ask it about the longest name in a dataframe containing a column named "name" and it returns the following:

Entering new AgentExecutor chain...
{
    "action": "python_repl_ast",
    "action_input": "import pandas as pd\n\n# Assuming the dataset is stored in a pandas DataFrame called 'data'\nnames = data['NAMES']\nlongest_name = max(names, key=len)\nlongest_name"
}
Observation: NameError: name 'data' is not defined
Thought:{
    "action": "Final Answer",
    **"action_input": "I apologize for the confusion. Unfortunately, I do not have access to the dataset required to find the longest name. Is there anything else I can assist you with?"**
}

Is there a way to pass the dataframe object to the Pandas REPL tool in order for the code to execute properly and return me the answer? This problem is encountered while using the GPT-3.5-turbo API model.

This is the full code:

    ```
    df = pd.read_csv(file_path)

    tools = [PythonAstREPLTool(locals={"df": df})]

    agent = initialize_agent(
        agent='chat-conversational-react-description',
        tools=tools,
        llm=llm,
        verbose=True,
        max_iterations=3,
        early_stopping_method='generate',
        memory=conversational_memory
    )

    query = 'What is the longest name?'

    print(agent(query))

```

**Comment by theone4ever** [comment]
I had the same question, but after check the built in csv agent, i got most of clues. You can take a look:

```
import pandas as pd

from langchain.agents import create_csv_agent
from langchain.llms import OpenAI
agent = create_csv_agent(OpenAI(temperature=0), 'data/orders.csv', verbose=True)
agent.agent.llm_chain.prompt.template
```

Most of the trick are in the template, basically it instruct LLM to use variable `df` and print header of the dataframe to understand different columns.
```
'\nYou are working with a pandas dataframe in Python. The name of the dataframe is `df`.\nYou should use the tools below to answer the question posed of you:\n\npython_repl_ast: A Python shell. Use this to execute python commands. Input should be a valid python command. When using this tool, sometimes output is abbreviated - make sure it does not look abbreviated before using it in your answer.\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should always think about what to do\nAction: the action to take, should be one of [python_repl_ast]\nAction Input: the input to the action\nObservation: the result of the action\n... (this Thought/Action/Action Input/Observation can repeat N times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\n\nThis is the result of `print(df.head())`:\n{df_head}\n\nBegin!\nQuestion: {input}\n{agent_scratchpad}'
```
