### ISSUE TITLE
Refine prompt modification

### ISSUE THREAD

**Issue by PavelAgurov** [langchain-ai/langchain#8824]
### Feature request

I want to offer to change refine prompts to make a summary more correct.

### Motivation

In some cased (I can't say when exactly, but one time per 10-20) I saw that refine LLM added some additional text for summary.
Example:

> Since the provided context does not add any relevant information to the original summary, we will return the original summary:
> ... summary here...

On other cases I even saw output of refine prompt as:

>The existing summary is more comprehensive and provides a clear understanding of <my topic here>. The additional context provided does not contribute to the summary and can be disregarded.

As result I have this text as summary, but not my summary itself.

### Your contribution

I want to propose to use other prompts and check JSON result.

```
refine_initial_prompt_template = """\

Write a concise summary of the text (delimited with XML tags).
Please provide result in JSON format:
{{
    "summary": "summary here"
}}

<text>
{text}
</text>
"""

refine_combine_prompt_template = """\
Your job is to produce a final summary. We have provided an existing summary up to a certain point (delimited with XML tags).
We have the opportunity to refine the existing summary (only if needed) with some more context (delimited with XML tags).
Given the new context, refine the original summary (only if new context is useful) otherwise say that it's not useful.
Please provide result in JSON format:
{{
    "not_useful": "True if new context was not useful, False if new content was used",
    "refined_summary": "refined summary here if new context was useful"
}}

<existing_summary>
{existing_summary}
</existing_summary>

<more_context>
{more_context}
</more_context>
"""
```

Now I have JSON with field not_useful=True and can easy ignore it.

**Comment by PavelAgurov** [comment]
For me it's actual and I use it in my projects to reduce used tokens. But as nobody from langchain team reacted on it I guess it's not interesting for langchain team.

**Comment by baskaryan** [comment]
@PavelAgurov are you referring to the `RefineDocumentsChain`? you can already pass custom prompts into it directly (see [reference docs](https://api.python.langchain.com/en/latest/chains/langchain.chains.combine_documents.refine.RefineDocumentsChain.html#langchain.chains.combine_documents.refine.RefineDocumentsChain)), would that be enough for your use?
