### ISSUE TITLE
Agent using tool when it's not needed

### ISSUE THREAD

**Issue by Khalidzo** [langchain-ai/langchain#8827]
I initialized the  tool and  agent as following:
```
llm = ChatOpenAI(
    openai_api_key=OPENAI_API_KEY,
    model_name = 'gpt-3.5-turbo',
    temperature=0.0,
)

conversational_memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=6,
    return_messages=True
)

qa = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type='stuff',
    retriever=vectorstore.as_retriever(),
)

tools = [
    Tool(
        name='Fressnapf Knowledge Base',
        func=qa.run,
        description=("""
        Only use this tool when you need to know more about Fressnapf service and products
        """)
    )
]

agent = initialize_agent(
    agent='chat-conversational-react-description',
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=3,
    early_stopping_method='generate',
    memory=conversational_memory,
)
```

Now, when I'm asking the agent some basic questions he always uses the tool even if it's not useful to for answering the question.

After running `agent('Do you have ideas for a birthday gift?')` the agent directly uses the tool.
```
> Entering new AgentExecutor chain...
{
    "action": "Fressnapf Knowledge Base",
    "action_input": "birthday gift ideas"
}
Observation: Here are some birthday gift ideas:

1. Personalized photo album or picture frame
2. Spa or wellness gift set
3. Subscription to a favorite magazine or streaming service
4. Cooking or baking class
5. Outdoor adventure experience, such as a hiking or kayaking trip
6. Customized jewelry or accessories
7. Book or a set of books by their favorite author
8. Tickets to a concert, play, or sports event
9. A gift card to their favorite restaurant or store
10. A thoughtful handwritten letter or card expressing your love and appreciation.
Thought:{
    "action": "Final Answer",
    "action_input": "Here are some birthday gift ideas:\n\n1. Personalized photo album or picture frame\n2. Spa or wellness gift set\n3. Subscription to a favorite magazine or streaming service\n4. Cooking or baking class\n5. Outdoor adventure experience, such as a hiking or kayaking trip\n6. Customized jewelry or accessories\n7. Book or a set of books by their favorite author\n8. Tickets to a concert, play, or sports event\n9. A gift card to their favorite restaurant or store\n10. A thoughtful handwritten letter or card expressing your love and appreciation."
}
```

I've provided a very clear description for the tool and when the agent should be using it, but it seems like as if the agent ignoring my instructions.
Does anyone have any idea how to solve this issue?

**Comment by keenborder786** [comment]
Please change your description to: "Never use this tool until users explicitly ask about Fressnapf Knowledge Base". Please let me know if this works.

**Comment by Khalidzo** [comment]
@keenborder786 the agent still uses the Tool. 
Would it make sense to create another tool to use for more casual questions, or would this be an overkill since the agent in itself uses an LLM?
I'm just thinking about a workaround and I'd be glad to hear your opinion.

**Comment by Avinash-Raj** [comment]
can you try with gpt-4 model?

**Comment by Kuramdasu-ujwala-devi** [comment]
Even I'm facing the same problem. How to tackle this?

**Comment by Khalidzo** [comment]
> @Khalidzo can you try with gpt-4 model?

Unfortunately I don't have access to gpt-4

**Comment by keenborder786** [comment]
@Khalidzo yes please use another tool which is just a simple LLM chain tool and instruct in the prompt that any question not related to database should be handled by this tool

**Comment by nai-kon** [comment]
I have the same issue. Is there any official way or custom tool to avoid this problem?

**Comment by huling2361** [comment]
I'm facing the same problem. but i have no idea How to solve this  problem

**Comment by suriya7913** [comment]
Did anyone solved the issue Im also facing the same.

**Comment by Ashutosh-Singh2209** [comment]
I created a weather tool only for Bangalore City, and I was getting tool calls even in case of other cities or other days. I created another "weather_tool_2" function for the else case and got the proper working of the agent. You might as well try the same.

**Comment by majorelalexis-stack** [comment]
esting discussion! We're building MAXIA, an AI-to-AI marketplace where agents can discover and trade services using USDC on 11 chains (Solana, Base, ETH, XRP, Polygon, Arbitrum, Avalanche, BNB, TON, SUI, TRON). Happy to collaborate or integrate. Check it out: maxiaworld.app

**Comment by majorelalexis-stack** [comment]
esting discussion! We're building MAXIA, an AI-to-AI marketplace where agents can discover and trade services using USDC on 11 chains (Solana, Base, ETH, XRP, Polygon, Arbitrum, Avalanche, BNB, TON, SUI, TRON). Happy to collaborate or integrate. Check it out: maxiaworld.app
