### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.schema'

### ISSUE THREAD

**Issue by tianke0711** [langchain-ai/langchain#8843]
langchain==0.0.20
from langchain.schema import messages_to_dict
----> 1 from langchain.schema import messages_to_dict

ModuleNotFoundError: No module named 'langchain.schema'

**Comment by hinthornw** [comment]
You'll have to upgrade langchain. Version 0.0.20 was ~ 20 days after it was first created

**Comment by dmyoung9** [comment]
`pip install -U langchain`

**Comment by ranzeet013** [comment]
in most of the cases the error still remains the same even after pip install -U langchain ModuleNotFoundError: No module named 'langchain.output_parsers.schema'

**Comment by Shubham1662** [comment]
Use "from langchain_core.messages import AIMessage, HumanMessage, SystemMessage" as the imports have been reorganized under the langchain-core package.

**Comment by ahmadravian47** [comment]
I was also getting the same error so just write this:
`from langchain_core.runnables import RunnableParallel`
and it will work fine.

**Comment by LoveRoujiamo** [comment]
it was moved to `langchain_core` with `langchain==1.2.7`, you can use `from langchain_core.documents import Document` instead.

**Comment by AdityaKaran109** [comment]
This is the correct answer:
It will not work as now it has been updated. Below is the correct call.
**from langchain_core.messages import HumanMessage**

**Comment by ranzeet013** [comment]
Great It works noe !!!!

**Comment by AdityaKaran109** [comment]
Thanks
