### ISSUE TITLE
Bug with os.environ['FAISS_NO_AVX2'] = '1' 

### ISSUE THREAD

**Issue by aiakubovich** [langchain-ai/langchain#8857]
### System Info

I was trying to create FAISS embeddings that would work on different platforms so I tried to use:
`os.environ['FAISS_NO_AVX2'] = '1' `
as recommended in https://github.com/langchain-ai/langchain/blob/6cdd4b5edca511b0015f1b39102225fe638d8359/langchain/vectorstores/faiss.py

It works for windows, but I am getting `TypeError: IndexFlatCodes.add() missing 1 required positional argument: 'x'` when I try to create embeddings in Docker image

Full error:
```
TypeError: IndexFlatCodes.add() missing 1 required positional argument: 'x'
Traceback:
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/src/pages/1_💬__AI-Chat.py", line 127, in <module>
    chatbot = utils.setup_chatbot(
              ^^^^^^^^^^^^^^^^^^^^
File "/app/./src/modules/utils.py", line 121, in setup_chatbot
    vectors = embeds.getDocEmbeds(file, uploaded_file.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/./src/modules/embedder.py", line 104, in getDocEmbeds
    self.storeDocEmbeds(file, original_filename)
File "/app/./src/modules/embedder.py", line 86, in storeDocEmbeds
    vectors = FAISS.from_documents(data, embeddings)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/base.py", line 336, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 550, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/langchain/vectorstores/faiss.py", line 505, in __from
    index.add(vector)
```

langchain==0.0.226

### Who can help?

@hwchase17

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders.csv_loader import CSVLoader
from langchain.vectorstores import FAISS
from langchain.embeddings.openai import OpenAIEmbeddings

 loader = CSVLoader(file_path=tmp_file_path, encoding="utf-8",csv_args={
                'delimiter': ',',})
            data = loader.load()
 embeddings = OpenAIEmbeddings(...)
 vectors = FAISS.from_documents(data, embeddings)

### Expected behavior

embeddings should generated

**Comment by blue-hope** [comment]
I think when turn on the FAISS_NO_AVX2 as "1",
the function `dependable_faiss_import` returns faiss from `from faiss import swigfaiss as faiss`

and it doesn't wrapped by handle_Index on `__init__.py` of 'faiss', so signature doesn't match at all.
