### ISSUE TITLE
Issue: Supabase python client pydantic dependency mismatch

### ISSUE THREAD

**Issue by rahulnyk** [langchain-ai/langchain#8866]
### Issue you'd like to raise.

When using supabase client I get dependency errors, which I believe originate from the pydantic library 

Supabase uses requires pydantic<3.0,>=2.1.0 
Langchain requires (I guess) 1.10.12 

With langchain compatible pydantic versions, supabase errors out. 

``` python
from supabase.client import Client, create_client
supabase_url = os.environ.get("SUPABASE_URL")
supabase_key = os.environ.get("SUPABASE_SERVICE_KEY")
supabase: Client = create_client(supabase_url, supabase_key)
```

    ImportError: cannot import name 'field_validator' from 'pydantic' 

But if I upgrade pydantic, langchain starts erroring out. 

``` python
from langchain.vectorstores.pgvector import PGVector
```

    PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

Is there any quick fix for this?

Thanks

**Comment by rahulnyk** [comment]
Using two virtual environments for one project is not really a good solution.

**Comment by eyurtsev** [comment]
@rahulnyk we're taking a look at how to handle this

**Comment by Abdullahw72** [comment]
What version of langchain are you using with Supabase==1.0.0? @vdaita This would be really helpful for me.

**Comment by vdaita** [comment]
@Abdullahw72 I'm using langchain==0.0.254

**Comment by Srajangpt1** [comment]
I still see dependency mismatch with supabase==1.0.0, langchain==0.0.263
<img width="415" alt="image" src="https://github.com/langchain-ai/langchain/assets/10047986/6007d1a7-169f-44e6-8c98-c91c4ccf6d6d">

**Comment by Srajangpt1** [comment]
@eyurtsev @baskaryan would it be possible to update on this issue. This is literally making impossible to use langchain. Unless we bump the version of pydantic.

**Comment by moazvolga** [comment]
+1

**Comment by baskaryan** [comment]
Hi all! As of langchain==0.0.267 the pydantic version is uncapped and we should largely be cross-compatible with pydantic v1 and v2. There are still some known pydantic v2 failure modes explained in https://github.com/langchain-ai/langchain/discussions/9337, and some potentially unknown failure modes.

We'd love to hear if the latest version unblocks your use cases or if you're still running into issues!

cc @Srajangpt1 @rahulnyk @moazvolga

**Comment by vdaita** [comment]
Below is my requirements.txt - sorry for the late response.

`aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1688651106312/work/dist
async-timeout==4.0.3
atlassian-python-api==3.40.0
attrs==23.1.0
backoff==2.2.1
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
certifi==2023.7.22
cffi @ file:///Users/cbousseau/work/recipes/ci_py311/cffi_1677903595907/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1688813409104/work
chroma-hnswlib==0.7.2
chromadb==0.4.5
click @ file:///home/conda/feedstock_root/build_artifacts/click_1689751945043/work
click-log @ file:///home/conda/feedstock_root/build_artifacts/click-log_1661327951104/work
cmarkgfm @ file:///private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_6cuxcxoojm/croot/cmarkgfm_1689941085829/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
coloredlogs==15.0.1
dataclasses-json==0.5.14
Deprecated==1.2.14
deprecation @ file:///home/conda/feedstock_root/build_artifacts/deprecation_1589881437857/work
dnspython==2.4.2
docutils==0.20.1
dotty-dict @ file:///home/conda/feedstock_root/build_artifacts/dotty-dict_1691242756105/work
email-validator==2.0.0.post2
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1692026125334/work
fastapi==0.99.1
flatbuffers==23.5.26
frozenlist==1.4.0
fsspec==2023.6.0
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1669279893622/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1689017552161/work
gotrue==1.0.0
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1664132893548/work
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1634280454336/work
hpack==4.0.0
html2text==2020.1.16
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1688612313164/work
httptools==0.6.0
httpx==0.23.3
humanfriendly==10.0
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata==6.8.0
importlib-resources==6.0.1
invoke==1.7.3
itsdangerous==2.1.2
jaraco.classes==3.3.0
Jinja2==3.1.2
keyring==24.2.0
langchain==0.0.254
langsmith==0.0.22
llama-hub==0.0.21
llama-index==0.7.9
MarkupSafe==2.1.3
marshmallow==3.20.1
monotonic==1.6
more-itertools==10.1.0
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
nest-asyncio==1.5.7
numexpr==2.8.5
numpy==1.25.2
oauthlib==3.2.2
onnxruntime==1.15.1
openai==0.27.8
openapi-schema-pydantic==1.2.4
orjson==3.9.4
overrides==7.4.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==2.0.3
pkginfo @ file:///home/conda/feedstock_root/build_artifacts/pkginfo_1673281726124/work
postgrest==0.10.3
postgrest-py==0.10.3
posthog==3.0.1
protobuf==4.24.0
psutil==5.9.5
pulsar-client==3.2.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic==1.10.12
pydantic_core==2.4.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1691408637400/work
PyPika==0.48.9
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-dotenv==1.0.0
python-gitlab @ file:///home/conda/feedstock_root/build_artifacts/python-gitlab_1686307247447/work
python-multipart==0.0.6
python-semantic-release==7.33.0
pytz==2023.3
PyYAML==6.0.1
readme-renderer @ file:///home/conda/feedstock_root/build_artifacts/readme_renderer_1687332422683/work
realtime @ file:///home/conda/feedstock_root/build_artifacts/realtime_1675617097180/work
regex==2023.8.8
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
requests-oauthlib==1.3.1
requests-toolbelt @ file:///home/conda/feedstock_root/build_artifacts/requests-toolbelt_1682953341151/work
retrying==1.3.4
rfc3986==1.5.0
semver @ file:///home/conda/feedstock_root/build_artifacts/semver_1603697772578/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.0
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
SQLAlchemy==2.0.19
starlette==0.27.0
storage3==0.5.0
StrEnum @ file:///home/conda/feedstock_root/build_artifacts/strenum_1688131856999/work
supabase==1.0.0
supafunc==0.2.2
sympy==1.12
tenacity==8.2.2
tiktoken==0.4.0
tokenizers==0.13.3
tomlkit @ file:///home/conda/feedstock_root/build_artifacts/tomlkit_1690472772788/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1691671248568/work
twine==3.8.0
typing-inspect==0.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1688315532570/work
tzdata==2023.3
ujson==5.8.0
urllib3==1.26.16
uvicorn @ file:///Users/cbousseau/work/recipes/ci_py311_2/uvicorn-split_1678996068223/work
uvloop==0.17.0
watchfiles==0.19.0
webencodings==0.5.1
websockets @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_d8ij4gljy1/croot/websockets_1678966799107/work
wrapt==1.15.0
yarl==1.9.2
zipp==3.16.2
`

**Comment by vdaita** [comment]
> I still see dependency mismatch with supabase==1.0.0, langchain==0.0.263
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/10047986/260620013-cadabaa8-8cd4-4f6a-a53e-aa0d7a908c4e.png">

I'm using httpx==0.23.3 and pydantic==1.10.12.
I had to delete most of the supabase dependency packages and reinstall them with a previous version.

Sorry for my late response.

**Comment by Abdullahw72** [comment]
I managed to get it work as well, with older langchain and supabase versions. Successfully integrated supabase db with langchain chatbot. Here's my requirements.txt as well. The key is to use:
`supabase==1.0.0` ,`langchain==0.0.202`, `httpx==0.23.3`, `pydantic==1.10.9`.

[requirements.txt](https://github.com/langchain-ai/langchain/files/12379389/requirements.txt)

**Comment by Srajangpt1** [comment]
@baskaryan thanks for the update. v0.0.272 works with superbase, but it is still an issue with openAI functions. Langchain internally is referring to pydantic v1.
