### ISSUE TITLE
Language support for Agents

### ISSUE THREAD

**Issue by timonpalm** [langchain-ai/langchain#8867]
### Feature request

Agents can deal with prompts in different languages, but they might get confused or more unreliable if the internal prompts (e.g. format structure with the action, action input, thought etc.) are still in English.

That's why I thought about an additional language option when initializing an agent. I tried to come up with an idea of how to implement this efficiently, but I found it particularly hard to implement it, so it can be used for every language. 

My initial thought was to specify the necessary prompts in a different language and initialize the agent with an extra keyword. With this approach only a finite number of languages can be covered and it could end up in a mess to save all the prompts in different languages.

My second thought was to initialize the agent with a language keyword and then translate all the prompts in the desired language. That could be too much of a hustle for just initializing an agent with prompts that are actually known.

I wanted to share this and see if this is actually something that could be useful, and maybe gather some ideas of how to implement it.

### Motivation

I've implemented an MRKL agent that writes a detailed article on a specified topic based on internet search. In my specific case, it should write an article about topics related to Germany, e.g. the drought situation in Germany. Naively, my first attempt was to give it a prompt like _Write a detailed article about the drought situation in Germany. The article must be written in German language_.

I discovered two problems:

1. As I was giving the prompt in English, the model "thought" in English as well. Therefore, the action inputs were in English, too. This led to the result that all search results were also in English and primarily from sources (e.g. The Guardian, BBC) outside of Germany reporting about the drought situation in Germany. What I would have liked instead are search results from German newspapers or similar.
2. The text generation was very much inconsistent. It wasn't quite able to write the final article in German, as all information was given in English. Sometimes, it managed to write the text in German, but I also wrote all intermediate steps (action, action input, Observation, Thought, etc.) in German, too. That led to the problem of not finding the tool (tool descriptions were also in English) and resulting OutputParser Error, because the English keywords _thought_ and _action_ etc. could be found.

So my goal was to create an agent that solely worked in the German language. Meaning, that the prompt, intermediate steps, search results and the final output are all in German.

So what I did was reimplementing all the necessary MRKL agent functions and templates in a German version. It worked out and the results were as expected and reliable.

I think that agents with different language support could be beneficial for more users. You can give it a prompt in other languages but that the agent's internal prompts are in specific language, too.

### Your contribution

I am not really sure how to do that in a good way, so that multiple languages are supported for all the agents, and if that's even desired. But if there is a good strategy, I would like to try to implement it.

**Comment by zqszqszqstvt** [comment]
Hello, deer Timonpalm,
may I take a look at your MRKL agent? For reference only.

**Comment by timonpalm** [comment]
I redefined all the global variables:

```
FORMAT_INSTRUCTIONS ="""Verwende das folgende Format:

Gedanke: du sollst immer überlegen, was du als nächstes machst (Du kannst NICHT auf Webseiten zugreifen)
Aktion: du kannst ausschließlich die Funktion {tool_names} benutzen
Aktionseingabe: Eingabe der Aktion
Beobachtung: das Ergebnis der Aktion
... (dieser Gedanke/Aktion/Aktionseingabe/Beobachtung kann sich N mal wiederholen)
Gedanke: ich habe ausreichende Informationen um den Artikel zu schreiben
Artikel:
    Titel: Titel des Artikels
    ##
    Text: Artikel im HTML-Format
    ##
    Quellen: [1]: HTML Link zur Quelle | [2]: HTML Link zur Quelle | [3]: ..."""

PREFIX = """Schreibe einen anregenden und informativen Artikel über den heutigen (Datum: {date}) Welttag. Gib immer die Quelle/Link zur Information an, indem du Referenznummern verwendest. Du hast Zugang zu den folgenden Werkzeugen:"""
SUFFIX = """Der Artikel MUSS in deutscher Sprache verfasst sein!

Beginn!
Welttag: {input}
{agent_scratchpad}"""

FINAL_ANSWER_ACTION = "Artikel:"

ACTION_WORD = "Aktion"
ACTION_INPUT_WORD = "Aktionseingabe"
```

Copied the OutputParser and changed the two keywords.


```class GermanMRKLOutputParser(AgentOutputParser):

    def get_format_instructions(self) -> str:
        return FORMAT_INSTRUCTIONS

    def parse(self, text: str) -> Union[AgentAction, AgentFinish]:
        includes_answer = FINAL_ANSWER_ACTION in text
        regex = (
            r"Aktion\s*\d*\s*:[\s]*(.*?)[\s]*Aktionseingabe\s*\d*\s*:[\s]*(.*)"
        )
        action_match = re.search(regex, text, re.DOTALL)
        if action_match:
            if includes_answer:
                raise OutputParserException(
                    "Parsing LLM output produced both a final answer "
                    f"and a parse-able action: {text}"
                )
            action = action_match.group(1).strip()
            action_input = action_match.group(2)
            tool_input = action_input.strip(" ")
            # ensure if its a well formed SQL query we don't remove any trailing " chars
            if tool_input.startswith("SELECT ") is False:
                tool_input = tool_input.strip('"')

            return AgentAction(action, tool_input, text)

        elif includes_answer:
            finish = AgentFinish(
                {"output": text.split(FINAL_ANSWER_ACTION)[-1].strip()}, text
            )

            return finish

        if not re.search(r"Aktion\s*\d*\s*:[\s]*(.*?)", text, re.DOTALL):
            raise OutputParserException(
                f"Could not parse LLM output: `{text}`",
                observation="Invalid Format: Missing 'Aktion:' after 'Gedanke:'",
                llm_output=text,
                send_to_llm=True,
            )
        elif not re.search(
            r"[\s]*Aktionseingabe\s*\d*\s*:[\s]*(.*)", text, re.DOTALL
        ):
            raise OutputParserException(
                f"Could not parse LLM output: `{text}`",
                observation="Invalid Format:"
                " Missing 'Action Input:' after 'Action:'",
                llm_output=text,
                send_to_llm=True,
            )
        else:
            raise OutputParserException(f"Could not parse LLM output: `{text}`")

    @property
    def _type(self) -> str:
        return "mrkl"
```
And created the GermanZeroShotAgent

```
class GermanZeroShotAgent(ZeroShotAgent):
    """Agent for the MRKL chain in German."""

    @property
    def observation_prefix(self) -> str:
        """Prefix to append the observation with."""
        return "Beobachtung: "

    @property
    def llm_prefix(self) -> str:
        """Prefix to append the llm call with."""
        return "Gedanke:"

    @classmethod
    def init(
            cls,
            tools: Sequence[BaseTool],
            prefix: str = PREFIX,
            suffix: str = SUFFIX,
            format_instructions: str = FORMAT_INSTRUCTIONS,
            input_variables: Optional[List[str]] = None,
            ):
        
        tool_strings = "\n".join([f"{tool.name}: {tool.description}" for tool in tools])
        tool_names = ", ".join([tool.name for tool in tools])
        format_instructions = format_instructions.format(tool_names=tool_names)
        template = "\n\n".join([prefix, tool_strings, format_instructions, suffix])
        if input_variables is None:
            input_variables = ["input", "date", "agent_scratchpad"]
        template = PromptTemplate(template=template, input_variables=input_variables)

        llmchain = LLMChain(
            llm=ChatOpenAI(temperature=0, model="gpt-4"), 
            prompt=template,
            verbose=True,
        )

        tool_names = [tool.name for tool in tools]
        _output_parser = GermanMRKLOutputParser()

        return cls(
            llm_chain=llmchain, 
            allowed_tools=tool_names,
            output_parser=_output_parser,
            max_iterations=2
        )
```
Note: I didn't use the agent for question answering, but rather to write text.

**Comment by zqszqszqstvt** [comment]
Thanks,it is very kind of you.

**Comment by jolackner** [comment]
I think you hit a topic that's going to be decisive in terms of how widely Langchain will/can be adopted by non-English users. Thank you for working on it!

**Comment by HorstA** [comment]
would also be a great help for me!

**Comment by rafag0n** [comment]
I'm trying to do the same for Brazilian Portuguese in the JS repo. Really nice to see the effort happening in other languages as well!
