### ISSUE TITLE
Issue: ConversationalRetrievalChain.from_llm sometime answer with the following up question

### ISSUE THREAD

**Issue by DSgUY** [langchain-ai/langchain#8875]
### Issue you'd like to raise.

Hi, Im using  ConversationalRetrievalChain.from_llm and I notice that sometimes the answer is the following up question.
Also sometimes the answer generates a few Q and A all togheter.

Anyone with the same problem?

regards.

**Comment by shreyabhadwal** [comment]
Hi, 
Can you give an example of the problem you're facing?

**Comment by DSgUY** [comment]
> Hi, Can you give an example of the problem you're facing?

Yes,
1) The `ConversationalRetrievalChain.from_llm` answers with a the following up question. For example: 
```
User: hi, I want to know the color of the sky?
LLM: what is the color of the sky?
```

2) The  `ConversationalRetrievalChain.from_llm` answers a chain of QnA. For example:
```
User: hi, I want to know the color of the sky?
LLM: User: hi, I want to know the color of the sky?. Assistant: The color of the sky is blue. User: xxxx 

I`m using AzureOpenAI as LLM. 
```

**Comment by shreyabhadwal** [comment]
I am still not sure about the context the question is answering from. Could you let us know 
1. Over what kind of documents you're running the chain
2. If there is a custom condense question prompt that you're using

From the example you've given, it seems like you just want to retain memory from previous conversations instead of doing a document retrieval Q&A.

**Comment by Balerion14** [comment]
hello, is it possible to recover the generated question from the history and the base question:memory = ConversationBufferMemory(memory_key="chat_history", return_messages=True)
        retriever = load_embedding(list_nom_fichier).as_retriever()
        return ConversationalRetrievalChain.from_llm(
            llm,
            retriever=retriever,
            memory=memory
        )
