### ISSUE TITLE
Simplify linting workflow by adding to pre-commit

### ISSUE THREAD

**Issue by 3coins** [langchain-ai/langchain#8884]
## Description
Add format/lint actions to the pre-commit tool, so user's don't have to run these locally on their machines. This is a 2 stage process:

1. Make this part of the local commit process. This will ensure that all commits run these explicitly before pushing the change. 
2. Adding this to the CI will ensure that users who choose to ignore setting up the pre-commit in their local repo, can rely on the CI to fix some of the formatting and linting (fixable). This also avoids some of the system specific issues/differences that users might end up having on their local machines (stale versions of lint tools) by ensuring that the CI is running these on one consistent up-to-date platform. 

### Motivation

The current manual linting process adds churn and friction to the dev workflow as most devs end up pushing their changes without running these steps, and rely on the CI to remind them on running them. Some of the formatting and linting can be automated with CI, and does not require a dev's direct involvement. 

### Your contribution

I am happy to work on this, but would need the core team's input before going ahead with this change.

**Comment by eyurtsev** [comment]
I haven't set up pre-commit hooks before. 

Couple of questions:

1. Can it be made opt-in?
2. Which commands does it run on? (`git commit` / `git push` / `gh pr create`) ? 
3. What linters/tests would this run by default?

**Comment by 3coins** [comment]
> * Can it be made opt-in?

Yes, if the user does not install pre-commit, and run `pre-commit install` the hooks are not setup.
`git commit --no-verify -m "message" ` also skips the hook if installed.

> * Which commands does it run on? (`git commit` / `git push` / `gh pr create`) ?

`git commit` by default and it runs only on the files in the commit. This is configurable though, and you can choose to run some or all checks on other stages.

> * What linters/tests would this run by default?

Whatever you add to your config file `.pre-commit-config.yaml`. More info here:
https://pre-commit.com/#2-add-a-pre-commit-configuration
