### ISSUE TITLE
Cloud Firestore Chat Message History

### ISSUE THREAD

**Issue by marcoberlot1** [langchain-ai/langchain#8906]
### Feature request

Implement a Chat Message History  class backed up by Google Cloud Firestore. 

### Motivation

It's a common No-SQL database, used by a lot of people to build MVPs, due to its friendly pricing.

### Your contribution

I'd submit a PR to implement this, if you guys think that it could be a helpful feature

**Comment by wnmurphy** [comment]
This exists already, try:

```
# Instantiate, passing your own FS client instance if you like
chat_history_obj = FirestoreChatMessageHistory(
    firestore_client=firestore_client,
    collection_name="FirestoreCollectionName",
    user_id=some_user_id,
)

# Add Firestore history to memory
main_memory = ConversationBufferMemory(
    memory_key="chat_history",
    chat_memory=chat_history_obj,
    return_messages=True,
)

# Use in your chain
default_chain = ConversationChain(
    llm=chat_model,
    prompt=default_chat_prompt,
    memory=main_memory,
    verbose=settings.CHAIN_VERBOSITY,
    output_key="text",
)
```

**Comment by RedouanAssakali** [comment]
@dosunbot An error occurred: FirestoreChatMessageHistory.__init__() got an unexpected keyword argument 'sessionId'
Executor created

async def run_chatbot(vectorstore, session_id, uid, chatbot_data):
    try:
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise ValueError("Missing OpenAI API key in environment variables")
        print(chatbot_data['activeModel'])
        model = ChatOpenAI(
            temperature=0.5,
            model_name=chatbot_data['activeModel'],
            openai_api_key=openai_api_key,
        )

        firestore_config = {
            "collection": "chathistory",
            "sessionId": session_id,
            "userId": uid,
            "config": {"projectId": "unity-352c6"},
        }

        chat_history = FirestoreChatMessageHistory(**firestore_config)

        memory = ConversationBufferWindowMemory(
            chat_history=chat_history,
            memory_key="chat_history",
            input_key="question",
            output_key="text",
        )

        # retrieval qa chain
        qa = RetrievalQA.from_chain_type(
            llm=model,
            chain_type="stuff",
            retriever=vectorstore.as_retriever()
        )

        qa_tool = Tool(
            name='Knowledge Base',
            func=qa.run,
            description=(
                'use this tool when answering general knowledge queries to get '
                'more information about the topic'
            )
        )

        tools = [qa_tool]

        agent = initialize_agent(
            agent='chat-conversational-react-description',
            tools=tools,
            llm=model,
            verbose=True,
            max_iterations=3,
            early_stopping_method='generate',
            memory=memory,
        )

**Comment by RedouanAssakali** [comment]
@dosubot An error occurred: FirestoreChatMessageHistory.__init__() got an unexpected keyword argument 'sessionId'
Executor created

async def run_chatbot(vectorstore, session_id, uid, chatbot_data):
    try:
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise ValueError("Missing OpenAI API key in environment variables")
        print(chatbot_data['activeModel'])
        model = ChatOpenAI(
            temperature=0.5,
            model_name=chatbot_data['activeModel'],
            openai_api_key=openai_api_key,
        )

        firestore_config = {
            "collection": "chathistory",
            "sessionId": session_id,
            "userId": uid,
            "config": {"projectId": "unity-352c6"},
        }

        chat_history = FirestoreChatMessageHistory(**firestore_config)

        memory = ConversationBufferWindowMemory(
            chat_history=chat_history,
            memory_key="chat_history",
            input_key="question",
            output_key="text",
        )

        # retrieval qa chain
        qa = RetrievalQA.from_chain_type(
            llm=model,
            chain_type="stuff",
            retriever=vectorstore.as_retriever()
        )

        qa_tool = Tool(
            name='Knowledge Base',
            func=qa.run,
            description=(
                'use this tool when answering general knowledge queries to get '
                'more information about the topic'
            )
        )

        tools = [qa_tool]

        agent = initialize_agent(
            agent='chat-conversational-react-description',
            tools=tools,
            llm=model,
            verbose=True,
            max_iterations=3,
            early_stopping_method='generate',
            memory=memory,
        )
