### ISSUE TITLE
GCSFileLoader stores a wrong source in the metadata

### ISSUE THREAD

**Issue by lkuligin** [langchain-ai/langchain#8911]
### System Info

`0.0.257`

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Load a document from GCS and check the metadata["source"], it would point to the file in `/tmp` directory

### Expected behavior

source pointing to an original file on GCS

**Comment by eyurtsev** [comment]
Should be resolved with merged code
