### ISSUE TITLE
SearchFieldDataType.Single raises error in azuresearch.py, under AzureSearch() class.

### ISSUE THREAD

**Issue by yigitsimsek** [langchain-ai/langchain#8917]
### System Info

Platform: MacOS
Python version: Python 3.10.12
LangChain version: 0.0.257
Azure Search package version: 1.0.0b2
Azure Search Document package version: 11.3.0

azure-search==1.0.0b2
azure-search-documents==11.3.0
langchain==0.0.257

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. pip install packages langchain, azure-search, azure-search-documents.
2. Try to create an instance of AzureSearch as described [here](https://python.langchain.com/docs/integrations/vectorstores/azuresearch). (Official LangChain documentation.)
3. Receive error `AttributeError: module ‘azure.search.documents.indexes.models._edm’ has no attribute ‘Single’` from:
```
vector_store: AzureSearch = AzureSearch(
    azure_search_endpoint=vector_store_address,
    azure_search_key=vector_store_password,
    index_name=index_name,
    embedding_function=embeddings.embed_query,
)
```

### Expected behavior

AzureSearch instance should be created without any errors from langchain dependencies. _edm.py file in azure-search-documents package does not define Single as a data type.

**Comment by mattmalcher** [comment]
Hit this - I _think_ that the current stable version of the azure-search-documents package (11.3.0) which you are using does not support creating a vector index

The other version listed at https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-library-package-index is 11.4.0b8. 

This has the following sample, which is not present in 11.3.0:

https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.4.0b8/sdk/search/azure-search-documents/samples/sample_vector_search.py

**Comment by yigitsimsek** [comment]
> Hit this - I _think_ that the current stable version of the azure-search-documents package (11.3.0) which you are using does not support creating a vector index
> 
> The other version listed at https://learn.microsoft.com/en-us/azure/developer/python/sdk/azure-sdk-library-package-index is 11.4.0b8.
> 
> This has the following sample, which is not present in 11.3.0:
> 
> https://github.com/Azure/azure-sdk-for-python/blob/azure-search-documents_11.4.0b8/sdk/search/azure-search-documents/samples/sample_vector_search.py

Yes, I started to use version 11.4.0b6, which resolved the issue. Thank you for clarifying the solution with documentation!

**Comment by mattmalcher** [comment]
Yeah 11.4.0b6 looks like the one to go for, not b8.

Spotted in the docs [here](https://python.langchain.com/docs/integrations/vectorstores/azuresearch) they install b6.

```
pip install azure-search-documents==11.4.0b6
pip install azure-identity
```
