### ISSUE TITLE
Local huggingface model for summarization task 

### ISSUE THREAD

**Issue by hellorp1990** [langchain-ai/langchain#8931]
### Issue you'd like to raise.

I was using Langchain (map reduce) for summarization of longer documents with local HuggingFace model. I am using local models as my work prohibits me to directly connect to huggingface and/or openai. 

I am having some issue in running the model. I am getting the following errors: 

"'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f11d2f511d0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json"

My code is:

`from transformers import AutoTokenizer, LlamaForCausalLM,AutoModelForSeq2SeqLM,AutoModel, AutoModelForCausalLM, , LlamaTokenizer, LlamaForCausalLM,AutoModelForCausalLM,pipeline
from langchain.chains.summarize import load_summarize_chain
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains.mapreduce import MapReduceChain
from langchain.docstore.document import Document
from langchain.document_loaders import PyPDFLoader
import os
import torch

model = AutoModelForSeq2SeqLM.from_pretrained("/home/projects/nlp_summarize/led-large-16384")
tokenizer2 = AutoTokenizer.from_pretrained("/home/projects/nlp_summarize/led-large-16384")
tokenizer2.deprecation_warnings["Asking-to-pad-a-fast-tokenizer"] = True

pipe = pipeline(
    "text2text-generation",
    model=model,
    tokenizer=tokenizer2,
    #max_new_tokens= 4096,
    temperature=0.7,
    top_p=0.95,
    repetition_penalty=1.15,device= DEVICE
)
llm = HuggingFacePipeline(pipeline=pipe)

text_splitter = CharacterTextSplitter()
with open("stateoftheunion.txt") as f:
    data = f.read()
texts = text_splitter.split_text(data)

docs = [Document(page_content=t) for t in texts[:]]
chain = load_summarize_chain(llm, chain_type="map_reduce")
output_summary = chain.run(docs)
`

Even though I am not using any gpt2 model2 but still the model is looking for a gpt2 model online. 

Any idea why such behavior is happening and how can I avoid it?

**Comment by evyy1234** [comment]
> _Answer generated by a 🤖_
> 
> ## Answer
> Hello,
> 
> Based on the error message you provided, it seems like the issue is related to the HuggingFace transformers library trying to download the GPT-2 tokenizer from the HuggingFace model hub, even though you're using a local model.
> 
> This could be due to the way the `AutoTokenizer.from_pretrained()` method works. By default, it tries to download the tokenizer from the HuggingFace model hub using the provided `model_id`. In your case, you're providing a local path to your model, but the method might still be trying to download the GPT-2 tokenizer because it's the default tokenizer for the `AutoModelForSeq2SeqLM` model class.
> 
> To solve this issue, you can try to use the `SelfHostedHuggingFaceLLM` class from the LangChain framework, which is designed to work with local models. Here's how you can do it:
> 
> ```python
> from langchain.llms import SelfHostedHuggingFaceLLM
> 
> llm = SelfHostedHuggingFaceLLM(
>     model_id="/home/projects/nlp_summarize/led-large-16384",
>     task="summarization",
> )
> ```
> 
> In this example, the `model_id` is the path to your local model. The `task` is set to "summarization". The `SelfHostedHuggingFaceLLM` class will load the local model and tokenizer using the `from_pretrained` method of the `AutoModelForCausalLM` or `AutoModelForSeq2SeqLM` and `AutoTokenizer` classes, respectively, based on the task. The pipeline is then constructed with these components and used for text generation or summarization.
> 
> Please replace the `HuggingFacePipeline` with `SelfHostedHuggingFaceLLM` in your code and let me know if this resolves your issue.
> 
> For more information, you can refer to the following source files in the LangChain repository:
> 
> * [libs/langchain/langchain/llms/huggingface_endpoint.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_endpoint.py)
> * [libs/langchain/langchain/llms/huggingface_hub.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_hub.py)
> * [libs/langchain/langchain/llms/huggingface_pipeline.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_pipeline.py)
> * [libs/langchain/langchain/llms/self_hosted_hugging_face.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/self_hosted_hugging_face.py)
> 
> I hope this helps! If you have any other questions or if the issue persists, please let me know.
> 
> Best, Dosu
> 
> ## Sources
> * [libs/langchain/langchain/llms/huggingface_endpoint.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_endpoint.py)
> * [libs/langchain/langchain/llms/huggingface_hub.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_hub.py)
> * [libs/langchain/langchain/llms/huggingface_pipeline.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/huggingface_pipeline.py)
> * [libs/langchain/langchain/llms/self_hosted_hugging_face.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/self_hosted_hugging_face.py)
> * [libs/langchain/tests/integration_tests/llms/test_huggingface_pipeline.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/tests/integration_tests/llms/test_huggingface_pipeline.py)
> 
> This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

hello, if i use local custom llm(such as chatglm) ,without connect to huggingface, when i use langchain map reduce to summary long  text, What should I do in this situation, thanks!

**Comment by evyy1234** [comment]
> ### Issue you'd like to raise.
> I was using Langchain (map reduce) for summarization of longer documents with local HuggingFace model. I am using local models as my work prohibits me to directly connect to huggingface and/or openai.
> 
> I am having some issue in running the model. I am getting the following errors:
> 
> "'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f11d2f511d0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json"
> 
> My code is:
> 
> `from transformers import AutoTokenizer, LlamaForCausalLM,AutoModelForSeq2SeqLM,AutoModel, AutoModelForCausalLM, , LlamaTokenizer, LlamaForCausalLM,AutoModelForCausalLM,pipeline from langchain.chains.summarize import load_summarize_chain from langchain.text_splitter import CharacterTextSplitter from langchain.chains.mapreduce import MapReduceChain from langchain.docstore.document import Document from langchain.document_loaders import PyPDFLoader import os import torch
> 
> model = AutoModelForSeq2SeqLM.from_pretrained("/home/projects/nlp_summarize/led-large-16384") tokenizer2 = AutoTokenizer.from_pretrained("/home/projects/nlp_summarize/led-large-16384") tokenizer2.deprecation_warnings["Asking-to-pad-a-fast-tokenizer"] = True
> 
> pipe = pipeline( "text2text-generation", model=model, tokenizer=tokenizer2, #max_new_tokens= 4096, temperature=0.7, top_p=0.95, repetition_penalty=1.15,device= DEVICE ) llm = HuggingFacePipeline(pipeline=pipe)
> 
> text_splitter = CharacterTextSplitter() with open("stateoftheunion.txt") as f: data = f.read() texts = text_splitter.split_text(data)
> 
> docs = [Document(page_content=t) for t in texts[:]] chain = load_summarize_chain(llm, chain_type="map_reduce") output_summary = chain.run(docs) `
> 
> Even though I am not using any gpt2 model2 but still the model is looking for a gpt2 model online.
> 
> Any idea why such behavior is happening and how can I avoid it?
> 
> ### Suggestion:
> _No response_

hello ,do you have  solve this problem, i have the same situation, do not now how to deal with it , if you have any idea,please let  me know, thanks!
