### ISSUE TITLE
 Issue: unclear processing of natural language query parsing + external api querying afterwards

### ISSUE THREAD

**Issue by kirdin1** [langchain-ai/langchain#8953]
### Issue you'd like to raise.

I believe one of the most popular directions for langchain-based applications will be to parse the query in a natural language and to use some external api for the response generation. However, as soon as this external API doesn't have an OpenAISchema-based specification, the easiest way to do it will be via chain parsing + request.

I tried to implement it via a sequential chain, the example is provided below:

```
EXCHANGE_API_KEY = SOME_KEY

from langchain.chains import LLMRequestsChain, LLMChain, SimpleSequentialChain
from langchain.chains.openai_functions.openapi import get_openapi_chain
from langchain.prompts import PromptTemplate, SystemMessagePromptTemplate, ChatPromptTemplate, HumanMessagePromptTemplate

template = """You help to convert currencies.
You need to convert the input phrase into the query like from=EUR&to=GBP&amount=100"
You need to extract these parameters yourself from the query in natural language.
Please, return the string like https://api.currencylayer.com/convert?from=EUR&to=GBP&amount=100, where you need to fill in "from", "to", and "amount" based on previous instructions"
"""

system_prompt = SystemMessagePromptTemplate.from_template(template)

human_message_prompt = HumanMessagePromptTemplate.from_template("{question}")

first_prompt = ChatPromptTemplate(
messages=[
        system_prompt,
        human_message_prompt
    ]
)

## this one above may be done nicer, via PromptTemplate, but I don't think it's necessary here

template_2 = """
Query api with {synopsis} and return api response
"""

llm = OpenAI(temperature=0)
convert_chain = LLMChain(llm=llm, prompt=first_prompt, output_key="synopsis")

system_prompt_2 = PromptTemplate(input_variables=["synopsis"], template=template_2)
chain = LLMRequestsChain(llm_chain=LLMChain(llm=OpenAI(temperature=0), prompt=system_prompt_2))

overall_chain = SimpleSequentialChain(chains=[convert_chain, chain], verbose=True)

question = "Convert 1000 American Dollars to euros please"
inputs = {"input": question,
    #"url": "https://api.currencylayer.com/convert",
    "headers": {"access_key": EXCHANGE_API_KEY}
}

overall_chain(inputs)
```

The code above fails due to _requests_ library stacktrace: `InvalidSchema: No connection adapters were found for 'System: [https://api.currencylayer.com/convert?from=USD&to=EUR&amount=1000'](https://api.currencylayer.com/convert?from=USD&to=EUR&amount=1000%27)`

It happens because the string "System: " is inevitably attached to the output of the first chain.

So, my questions are as follows:

1. Is the way I showed above right now the best option to interact with the APIs which have not been implemented yet to langchain and haven't got OpenAISchema-based docs?

2. If so, how to deal with my problem and strip the "System: " part for query? Is there a natural way to parse the natural language query into an API request via this chain? 

### Suggestion:

I think there should be a very clear way and documentation of how to deal with external APIs after natural language parsing done by generative network

**Comment by tfbecker** [comment]
+1
