### ISSUE TITLE
lang chain connection with mongo DB 

### ISSUE THREAD

**Issue by prameelareddi** [langchain-ai/langchain#8956]
### Issue you'd like to raise.

Can you please help me with connecting my LangChain agent to a MongoDB database?
I have connected my relational database below like 

db = SQLDatabase.from_uri("mysql_db_url")

The above process is not working for Mongo Db because it is a NoSQL database 
anyone can help me to do this ???????
Thank you .....

**Comment by timxieICN** [comment]
You have to build a custom connection agent/tool

**Comment by prameela1610** [comment]
Thank you for your response @timxieICN 
can you please help me to build a custom connection agent.

**Comment by Saransh29** [comment]
Explain your use case a bit. Do you want to use mongoDb as a vector store or do you want to query the collections.

anyway you can use pymongo
```py
from pymongo.mongo_client import MongoClient

client = MongoClient(uri)
db=client[db_name]
```

**Comment by prameela1610** [comment]
Thank you for your response @Saransh29 
I used pymongo for connecting the database but i need to connect the langchain with MongoDB 
for  relational database , we have a connecter called sqldatabase in langchain but mongoDb is noSQL right???
I need to chat with mongoDB with the help of langchain connector and llm 
Thanks !!!

**Comment by Saransh29** [comment]
okay, so Langchain and llamaIndex both don't support this right now.

So, for this usecase you can use gpt4 with a customized prompt (containing your db schema and details).
And use it to generate query piplelines and execute them.

**Comment by prameelareddi** [comment]
Great Thanks !!! @dosubot
db=SQLDatabase.from_uri('mongodb://username:password@host:port/database'

if I use above I got the error below like 

sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mongodb

When i use this  " postgresql+psycopg2://username:password@host:port/database "  Its working fine .

I understand SQLAlchemy considers only relational databases 

if any suggestions ? 
Thank you

**Comment by digitalblur** [comment]
Mongo connection support is built in here
https://python.langchain.com/docs/integrations/document_loaders/mongodb

**Comment by digitalblur** [comment]
Mongo connection support is built in.
https://python.langchain.com/docs/integrations/document_loaders/mongodb
