### ISSUE TITLE
Embeddings are regenerated for entire vector db on updating collections

### ISSUE THREAD

**Issue by sitz** [langchain-ai/langchain#8957]
### System Info

macOS Ventura Version `13.4.1`
Python `3.11.4`
```
langchain==0.0.251
chromadb==0.4.5
```

### Who can help?

@hwchase17 @eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Create a vector database and insert some items with relevant embeddings
2. Update vector database collection with some new docs

Python snippet to create/update vector db collection and it's embeddings:
```
documents = []
for row in get_data_rows():
    documents.append(
        Document(
            page_content=row['full_text'],
            metadata={
                'id': int(row['id']),
                'created_at': parser.parse(row['created_at']).timestamp(),
            }
        )
    )

Chroma.from_documents(
    documents,
    embedding=OpenAIEmbeddings(),
    collection_name='my_collection',
    persist_directory=f'embeddings/my_collection'
)
```

### Expected behavior

Running above snippet in both scenarios should only call embeddings function for newly added or changed docs instead of everything?

**Comment by eyurtsev** [comment]
@sitz here's information on how to cache embeddings:

https://python.langchain.com/docs/modules/data_connection/text_embedding/caching_embeddings

And new indexing code can help avoid even more redundant computation for some workflows: https://python.langchain.com/docs/modules/data_connection/indexing
