### ISSUE TITLE
Wrong paper reference

### ISSUE THREAD

**Issue by eliorc** [langchain-ai/langchain#8964]
In the docs it seems the ReAct reference references to the wrong paper.
The actual ReAct paper is [this](https://arxiv.org/pdf/2210.03629.pdf)

https://github.com/langchain-ai/langchain/blob/b8df15cd647ca645ef16b2d66be271dc1f5187c1/docs/docs_skeleton/docs/modules/agents/agent_types/index.mdx#L15

**Comment by emilesilvis** [comment]
@eyurtsev trying to understand the process here: why is this issue still open and not closed by the above merge?

**Comment by eliorc** [comment]
Fixed by #8970
