### ISSUE TITLE
Human as a Tool in Production 

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#8973]
### Issue you'd like to raise.

Can we use Human as a tool in product?
def get_input() -> str:
    print("Insert your text. Enter 'q' or press Ctrl-D (or Ctrl-Z on Windows) to end.")
    contents = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line == "q":
            break
        contents.append(line)
    return "\n".join(contents)

# You can modify the tool when loading
tools = load_tools(["human", "ddg-search"], llm=math_llm, input_func=get_input)

what to do with input() in get_input() function if we need to use this tool in production?

reference:-https://python.langchain.com/docs/integrations/tools/human_tools

**Comment by pprados** [comment]
I suppose using the 'human' tool is difficult on a web server ;-)

**Comment by MariusAure** [comment]
Yeah `input()` is useless in production. I ended up making an API the agent can POST to, a human picks it up and does the thing, agent GETs the result when it's ready. https://needhuman.ai
