### ISSUE TITLE
Force LangChain Agent to Use a Tool

### ISSUE THREAD

**Issue by miggytrinidad** [langchain-ai/langchain#8979]
### Issue you'd like to raise.

How do you force a langchain agent to use a tool and not use any information outside the tool? Currently, if the question is not related to the Tool it uses its own data to generate answer which I don't want it to be.

Use Case: I have an index which has a lot of documents. I want to make sure the agent will use the index ALWAYS to get information. If the question is not in the index it should return "I don't know" or similar.

P.S I am using OPENAI_FUNCTION agent.

**Comment by Aagosh10** [comment]
@miggytrinidad You should be able to modify the prompt to make sure that the output generated by the llm always invokes a tool instead of generating an answer directly. The prompt can be modified while initialising the agent.

**Comment by jesper-bylund** [comment]
@miggytrinidad did it work? What did you add to the prompt?

**Comment by mrenlivex** [comment]
I have told the agent must use a tool in system prompt, but it still answer directly without calling a tool.  lots of model is already support "tool_choice" option btw.
