### ISSUE TITLE
pydantic upgrade

### ISSUE THREAD

**Issue by chengyjonathan** [langchain-ai/langchain#8984]
### Feature request

Many packages use pydantic versions that are much more recent than the one in langchain.

### Motivation

It is very difficult to use langchain with other packages that use recent versions of pydantic

### Your contribution

Just wanting to signal this as a needed feature

**Comment by eyurtsev** [comment]
hi @chengyjonathan we're working on adding v1 and v2 compatibility right now likely a few days away

**Comment by AlexTo** [comment]
@eyurtsev that's very cool. I've been refreshing langchain github page to hear this news. Thanks a lot :D

**Comment by tuliostarling** [comment]
I was looking forward to hearing this news as well. I have a project which is having a dependency conflict between pydantic, pydantic-settings and langchain.

If langchain had compatibility with pydantic versions above 2, it would already solve my problem

**Comment by baskaryan** [comment]
Hi all! As of `langchain==0.0.267` the pydantic version is uncapped and we should largely be cross-compatible with pydantic v1 and v2. There are still some known pydantic v2 failure modes explained in #9337, and some potentially unknown failure modes. 

We'd **love** to hear if the latest version unblocks your use cases or if you're still running into issues!

cc @chengyjonathan @AlexTo @tuliostarling

**Comment by AlexTo** [comment]
@baskaryan very nice, I just upgraded. Thanks a lot :D
