### ISSUE TITLE
Issue in running ConversationalRetrievalChain query across multiple Opensearch indices with wildcard specification

### ISSUE THREAD

**Issue by abhinavmishra590** [langchain-ai/langchain#8985]
### System Info

Langchain version: 0.0.257
Python version: 3.11
Opensearch-py version: 2.3.0

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I have this `Opensearch Vector DB `and I maintain multiple indices that start with "index-" (for example index-pdf, index-html). I have indexed sets of documents to each of the indices using Langchain's OpenSearchVectorSearch.from_documents() function.

Now, I want to run some queries which I want them to be run across multiple indices. An example would be "What is the title of each document?". When I execute below code, it either just outputs answer from first or last matching index, or says it cannot find the answer. Here is my current code:

```
from langchain.vectorstores import OpenSearchVectorSearch
from langchain.chains import RetrievalQA, ConversationalRetrievalChain
import os
from langchain.embeddings import OpenAIEmbeddings
from langchain.chat_models import ChatOpenAI


embeddings = OpenAIEmbeddings()

def get_llm(model):
    llm = ChatOpenAI(model_name=model.lower(), verbose=False, temperature=0)
    return llm


docsearch = OpenSearchVectorSearch(opensearch_url="http://localhost:9200",
                                           
                                            index_name="index-*",
                                            embedding_function=embeddings)



chain = ConversationalRetrievalChain.from_llm(
    llm=get_llm("gpt-3.5-turbo"),
    retriever=docsearch.as_retriever(),
)


result = chain({'question': 'What is the title of each document?', "chat_history": []})
response = result['answer']

print(response)
```
The response I get is either of the format "The document provided does not list different titles..."

### Expected behavior

Response should be span across multiple indices

**Comment by timxieICN** [comment]
I think right now `OpenSearchVectorSearch` only supports 1 index.

**Comment by abhinavmishra05** [comment]
`MergerRetriever`  throws error at line `merger_retriever =  MergerRetriever(retrievers)`. The error is `Serializable.__init__() takes 1 positional argument but 2 were given`. Also `MergerRetriever` function is shown under `langchain.retrievers.merger_retriever` instead of `langchain.chains`.
