### ISSUE TITLE
run() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by MuhammadBilal848** [langchain-ai/langchain#8990]
### Issue you'd like to raise.

Hey y'all. i have this code. i wrote it one month back and when i am running it now, it is giving me an error.

**CODE**:

<code>import os
from langchain.llms import OpenAI
from langchain import PromptTemplate
from langchain.chains import LLMChain
from constant import openai_key
import streamlit as st
os.environ['OPENAI_API_KEY'] = openai_key
llm = OpenAI(temperature=0.8)
multiple_inputs = PromptTemplate(
    input_variables=["name", "age", "location"],
    template="My name is {name}, I am {age} years old and live in {location}."
)
chain = LLMChain(llm=llm, prompt=multiple_inputs)
output = chain.run(
    name="John", 
    age=30,
    location="New York"
)
print(output)
</code>

**ERROR**:

<code>Traceback (most recent call last):
  File ".\questions.py", line 19, in <module>
    output = chain.run(
TypeError: run() got an unexpected keyword argument 'name'</code>

**Comment by sepiatone** [comment]
I was able to get (what I think) is what you want with a slight tweak -

code
```
from langchain.chains import LLMChain
from langchain.llms import OpenAI
from langchain import PromptTemplate

llm = OpenAI(openai_api_key = "...")

multiple_inputs = PromptTemplate(
                    input_variables = ['name', 'age', 'location'],
                    template = "Pretend that {name} is your name, {age} is your age and {location} is your location. Respond with your name, age and location."
                )

chain = LLMChain(
            llm = llm,
            prompt = multiple_inputs
        )

output = chain.run(name="John", age=30, location="New York")

print(output)
```
And as output
>My name is John, I'm 30 years old and I'm from New York.

**Comment by sepiatone** [comment]
Your code works for me,

I'm using v0.0.262, fyi. Perhaps update your version? Though considering it worked for you a month ago, I'm not too sure.

**Comment by MuhammadBilal848** [comment]
> Your code works for me,
> 
> I'm using v0.0.262, fyi. Perhaps update your version? Though considering it worked for you a month ago, I'm not too sure.

This worked!!!!!!!
I was using the v0.0.27 version which was causing errors.

Thanks, Bro! 😁
