### ISSUE TITLE
`AirbyteStripeLoader` throws an error

### ISSUE THREAD

**Issue by homanp** [langchain-ai/langchain#8996]
### System Info

When importing the `AirbyteStripeLoader` introduced in v0.0.259 it throws an `module not found error`. 

```
from libs.langchain.langchain.utils.utils import guard_import

ModuleNotFoundError: No module named 'libs'
```

### Who can help?

@eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
from langchain.document_loaders.airbyte import AirbyteStripeLoader

config = {
    # your stripe configuration
}

loader = AirbyteStripeLoader(config=config, stream_name="invoices") # check the documentation linked above for a list of all streams
```

### Expected behavior

Import the document should not throw an error.

**Comment by eyurtsev** [comment]
ah great catch! sending a fix

**Comment by homanp** [comment]
Oh, I added a contribution for it https://github.com/langchain-ai/langchain/pull/9000

**Comment by eyurtsev** [comment]
ah got it sorry didn't see -- merged merged: https://github.com/langchain-ai/langchain/pull/8998

**Comment by eyurtsev** [comment]
closing issue for now as this is fixed on master

**Comment by homanp** [comment]
@eyurtsev when will you release to SDK?
