### ISSUE TITLE
Issue: UnicodeDecodeError when running .txt files using TextLoader

### ISSUE THREAD

**Issue by mepurgamentum** [langchain-ai/langchain#9005]
### Issue you'd like to raise.

Hello - I receive a UnicodeDecodeError when running the below code:

from dotenv import load_dotenv
load_dotenv()
from langchain.llms import OpenAI
from langchain.vectorstores import Chroma
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.chains import RetrievalQA
llm = OpenAI(temperature=0.1)
from langchain.document_loaders import TextLoader
loader = TextLoader("./Training/test2.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
texts = text_splitter.split_documents(documents)
embeddings = OpenAIEmbeddings()
docsearch = Chroma.from_documents(texts, embeddings)
qa = RetrievalQA.from_chain_type(llm=OpenAI(), chain_type="stuff", retriever=docsearch.as_retriever(search_kwargs={"k": 1}))
query = "How much did the judge fine Twitter?"
qa.run(query)

The test2.txt is a 1,600-word UTF-8 encoded file. Here is the error text that I receive:

**Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\pythonProject\Misc\Testing.py", line 17, in <module>
    documents = loader.load()
                ^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\pythonProject\Misc\venv\Lib\site-packages\langchain\document_loaders\text.py", line 18, in load
    text = f.read()
           ^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1079: character maps to <undefined>**

Any advice would be greatly appreciated.

**Comment by mepurgamentum** [comment]
This worked, thank you!

**Comment by Warlib1975** [comment]
Hello, 

I used encoding='cp1251' in TextLoader. Everything is ok when I see the result of loading. But when I execute
qa_chain = RetrievalQA.from_chain_type(llm, retriever=db.as_retriever())

I got the error: 'charmap' codec can't decode byte 0x81 in position 33: character maps to <undefined>
I tried to convert source file into utf-8 encoding, but the error still the same. :-( 
None of your recommendations doesn't work.

**Comment by Rudra-G-23** [comment]
Hello,

I was also facing the same error.

After installing `chardet`, the `.txt` file started loading correctly.

```cmd
uv add "chardet<6.0.0"
```

Installed version:

```diff
+ chardet==5.2.0
```

My LangChain versions are:

```toml
dependencies = [
  "langchain>=1.2.3",
  "langchain-anthropic>=1.3.1",
  "langchain-community>=0.4.1",
  "langchain-core>=1.2.7",
  "langchain-google-genai>=4.1.3",
  "langchain-groq>=1.1.1",
  "langchain-huggingface>=1.2.0",
  "langchain-ollama>=1.0.1",
  "langchain-openai>=1.1.7",
]
```

This resolved the issue for me.

Thank you.
