### ISSUE TITLE
Conversational agent returning action plan as response after 0.0.260 release

### ISSUE THREAD

**Issue by pedropaulobm** [langchain-ai/langchain#9011]
### System Info

After I upgraded my Langchain to version 0.0.260, the ConversationalChatAgent returns the action plan as the chat response.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduce: request something that will make a ConversationalChatAgent call a tool.

### Expected behavior

The agent should pass the action and action_input to the tool and not return it as a final response to the user.

**Comment by keenborder786** [comment]
It's very difficult to come up with a solution without you giving the exact code that you used. In my case, I used the `ConversationalChatAgent` as follows and everything is working fine. If I don't turn the verbosity, it only gives me the final response:

```python

from langchain.agents.conversational_chat.base import ConversationalChatAgent
from langchain.agents import load_tools, AgentExecutor
from langchain.chat_models import ChatOpenAI
from langchain.chains import LLMChain
from langchain.memory import ConversationBufferMemory
import os

os.environ['OPENAI_API_KEY'] = '<TEST>'
chat_llm = ChatOpenAI(model_name="gpt-3.5-turbo-16k")
tools = load_tools(["arxiv", "wikipedia"])
prompt = ConversationalChatAgent.create_prompt(tools = tools)
llm_chain = LLMChain(llm=chat_llm,prompt=prompt)
agent = ConversationalChatAgent(llm_chain=llm_chain)
executor = AgentExecutor.from_agent_and_tools(
    agent=agent,
    tools=tools,
    memory=ConversationBufferMemory(input_key="input", memory_key="chat_history",return_messages=True),
)
while True:
    print(executor.run(input()))
```

My Conversation

```Logs
Hello
Hello! How can I assist you today?
Who is John wick?
John Wick is an American neo-noir action thriller media franchise created by Derek Kolstad. It centers on the character John Wick, a former hitman who is forced back into the criminal underworld. The franchise includes several films, starting with 'John Wick' in 2014, followed by sequels such as 'John Wick: Chapter 2' in 2017, 'John Wick: Chapter 3 – Parabellum' in 2019, and 'John Wick: Chapter 4' in 2023. The films have been critically acclaimed and have collectively earned over $1 billion worldwide.
How many sequenls of the above movie has been released?
There have been four sequels of the John Wick movie released so far.
```
