### ISSUE TITLE
WebResearchRetriever - RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by oliverdixon85** [langchain-ai/langchain#9014]
### System Info

Langchain version 0.0.260, Python 

### Who can help?

@agola11
@hwchase17

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Both chunks of code gave me the error. 
Chunk 1
`from langchain.chains import RetrievalQAWithSourcesChain
user_input = "How do LLM Powered Autonomous Agents work?"
qa_chain = RetrievalQAWithSourcesChain.from_chain_type(llm,retriever=web_research_retriever)
result = qa_chain({"question": user_input})
result`

Chunk 2 
'import logging
logging.basicConfig()
logging.getLogger("langchain.retrievers.web_research").setLevel(logging.INFO)
user_input = "How do LLM Powered Autonomous Agents work?"
docs = web_research_retriever.get_relevant_documents(user_input)
docs'

Both gave me this error 
`[/usr/lib/python3.10/asyncio/runners.py](https://localhost:8080/#) in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop`

### Expected behavior

In both cases I just wanted it to produce website text with a source.

**Comment by lasagna0** [comment]
anybody has tested the bot solution?

**Comment by andrew-hossack** [comment]
@leferradkw Thanks -- this works for now to allow async requests.
