### ISSUE TITLE
Issue: make command is not working after installing langchain

### ISSUE THREAD

**Issue by sri-dhurkesh** [langchain-ai/langchain#9033]
### Issue you'd like to raise.

I've been trying to install langchain using `pip install langchain[all]` in the conda environment where it already had packages to run hugging face text-generation-inference module. 

Let me know how to handle this issue. While running make command i'm facing this error.

```python
Traceback (most recent call last):
  File "/home/sri/miniconda3/envs/text-generation-inference/bin/make", line 5, in <module>
    from scripts.proto import main
ModuleNotFoundError: No module named 'scripts'

```

**Comment by mgvalverde** [comment]
Hi there,

I have the same issue after cloning the langchain repo, doing the `poetry install -E all` using a py39 as base interpreter, as detailed in the [CONTRIBUTE](https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md).
```python
Traceback (most recent call last):
  File "PATH/TO/STUFF/langchain/libs/langchain/.venv/bin/make", line 5, in <module>
    from scripts.proto import main
ModuleNotFoundError: No module named 'scripts'
```

**Comment by sri-dhurkesh** [comment]
Check out this command https://github.com/langchain-ai/langchain/issues/6915#issuecomment-1684868718m . This might be useful for you.

**Comment by piotr-grodek-dsai** [comment]
This is a problem of `tigrisdb`. I suggest to not install it at all (it is installed by default if you follow guidelines for all). 
If you installed it it is better to use `/usr/bin/make` directly or add this system directory to $PATH to be default to use.

**Comment by mgvalverde** [comment]
Thank you @sri-dhurkesh, @piotr-grodek-dsai, using `/usr/bin/make` instead of just `make` solves the issue!
