### ISSUE TITLE
ArxivLoader incorrect results

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#9046]
### System Info

Latest pip versions

### Who can help?

@eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I tried searching by exact title in the following way:

```python
docs = ArxivLoader(query="MetaGPT: Meta Programming for Multi-Agent Collaborative Framework", load_max_docs=1).load()
```
But the result is incorrect. The search works properly on the arxiv website. 

### Expected behavior

Correct paper returned

**Comment by eyurtsev** [comment]
cc @leo-gan

**Comment by austinmw** [comment]
Sure:

```python
docs = ArxivLoader(query="MetaGPT: Meta Programming for Multi-Agent Collaborative Framework", load_max_docs=1).load()
docs[0].metadata['Title']
```

The above code returns:

> 'Impact of International Cooperation for Sustaining Space-Science Programs'

Whereas I expect it to return:

> 'MetaGPT: Meta Programming for Multi-Agent Collaborative Framework'

**Comment by leo-gan** [comment]
@austinmw Thank you for reporting this issue! Much appreciated! 
It happens that ":" character somehow messed with the search. It works without problem in the arxiv UI but not in the arxiv API.
