### ISSUE TITLE
ArxivLoader support searching by arxiv id_list

### ISSUE THREAD

**Issue by austinmw** [langchain-ai/langchain#9047]
### Feature request

If I know exactly what paper(s) I'd like to load, it would be nice to be able to retrieve them by their arxiv IDs. The arxiv library seems to support this:

```
import arxiv

paper = next(arxiv.Search(id_list=["1605.08386v1"]).results())
```

### Motivation

Sometimes searching by exact paper title still returns the incorrect paper. Searching by ID should be more fool-proof.

### Your contribution

🤷🏻‍♂️

**Comment by LMC117** [comment]
Hi,

have you implemented this feature yet? If not, I can help with it :)

**Comment by leo-gan** [comment]
I've tried
`    loader = ArxivLoader(query="1605.08386 2308.07912 2308.07910", load_max_docs=3)`
and it returns all 3 papers. 
Disclaimer: if IDs are separated by `,` it didn't work! Only the space separator works.
 
I don't think we need special treatment for multiple paper IDs.
