### ISSUE TITLE
Metaphor Search throws key error when `publishedDate` is missing

### ISSUE THREAD

**Issue by homanp** [langchain-ai/langchain#9048]
### System Info

LangChain: v0.0.260
Python: v3.11

### Who can help?

@hwchase17 @eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Sometime `Metaphor` tool returns results without publishedDate which makes the Tool wrapper break due not guarding against empty values:

```
langchain/utilities/metaphor_search.py", line 169, in _clean_results

"published_date": result["publishedDate"],

KeyError: 'publishedDate'
```

### Expected behavior

Preferably the Tool should guard agains missing keys in API response.

**Comment by jeffzwang** [comment]
Thanks man!

**Comment by homanp** [comment]
> Thanks @homanp !

We are releasing this on superagent.sh on Tuesday. Wanna do a collab push on Twitter?
