### ISSUE TITLE
Issue: I want to attach metadata in my PGVector vector store used as retriever for my ConversationChain memory

### ISSUE THREAD

**Issue by RafaelCantoVazquez** [langchain-ai/langchain#9067]
### Issue you'd like to raise.

I am creating a chatbot that records the history of the conversation through vectors in my vector store per user that uses the chatbot, and for this, I identify who is the owner of the vectors through metadata.
How can I add this metadata to the vectors if I'm using the vector store as a retriever for the memory in my ConversationChain?

This is my code:
```
import os
from langchain.llms import OpenAI
from langchain.chains import ConversationChain
from langchain.memory import VectorStoreRetrieverMemory
from langchain.vectorstores.pgvector import PGVector
from langchain.embeddings.openai import OpenAIEmbeddings

exit_conditions = ("q", "quit", "exit")
metadata={"id": "John Doe", "key": 123}
llm = OpenAI(openai_api_key=os.getenv("OPENAI_API_KEY"), temperature=0)
store = PGVector(
            collection_name="chatbot_embeddings",
            connection_string=os.getenv("POSTGRES_CONNECTION_STRING"),
            embedding_function=OpenAIEmbeddings(),
            collection_metadata=metadata
        )

while True:
    query = input("> ")
    if query in exit_conditions:
        break

    conversation_with_summary = ConversationChain(
        llm=llm,
        memory=VectorStoreRetrieverMemory(retriever=store.as_retriever()),
        verbose=True,
        metadata=metadata,
    )
    print(conversation_with_summary.predict(input=query))
```

**Comment by RafaelCantoVazquez** [comment]
That doesn't work for me, since being a vector store that is used as a retriever, the vectors from the chat memory are saved more automatically, and not so manually through those methods of the vector store.

**Comment by gwc4github** [comment]
FYI- The best I can tell is that this code does not work at all and I not really a useful starting point.  Look at the code inside Langchain to understand how to use this.

**Comment by scs2learn** [comment]
@RafaelCantoVazquez I am working on creating a chatbot using VectoreStoreRetrieveMemory, ConversationChain and CustomLLM. Currently its CLI version similar to what you have mentioned. I am using Chromadb as my vector store. In my case the conversation chain exits as soon as the llm returns the response (verified using debug log). ConversationChain does not return the response and the control does not go back to the question prompt within the while loop. Have you encountered such behaviour? TIA

**Comment by gwc4github** [comment]
@scs2learn as best I can tell this doesn't work at all so I stopped using it and moved on to something else. (There was no support either so there was no alternative- the bot seemed to always be wrong.)
