### ISSUE TITLE
Referencing experimental version of SQLDatabaseChain from the production project

### ISSUE THREAD

**Issue by RHendrixn** [langchain-ai/langchain#9071]
https://github.com/langchain-ai/langchain/blob/a5a4c53280b4dae8ea2e09430fed88e0cd4e03d2/libs/langchain/langchain/chains/loading.py#L376

Work was done earlier this year to move all experimental and vulnerable code over to the experimental project. SQLDatabaseChain had (and still has) an open CVE against it so it was moved to the experimental project. However the experimental version of SQLDatabaseChain is being referenced in the production project on the line above. Our organization would like to start using LangChain but we cannot due to the open High severity CVE. Is it possible to either patch the vulnerability in code or complete the move of SQLDatabaseChain from the production project to the experimental?

**Comment by eyurtsev** [comment]
Hi @RHendrixn! 

Thanks so much for the feedback.

At the moment, `langchain_experimental` is an optional package and does not get installed by `langchain`. Installation of the package is entirely up to the user, and I suspect the security team should be able to entirely block installation of `langchain_experimental`.

We're open to feedback and the structure is not finalized yet. Would you be able to tell us why this is getting flagged by your security team right now?

Thanks in advance!

Eugene

**Comment by eyurtsev** [comment]
@RHendrixn I haven't heard back  -- so closing this comment. please feel free to ping me / re-open if still an issue
