### ISSUE TITLE
Issue: Elasticsearch BM25

### ISSUE THREAD

**Issue by VinuAbraham** [langchain-ai/langchain#9103]
### Issue you'd like to raise.

I am using Elasticsearch BM25 to fetch relevant documents. How can I add a parameter to tell the retriever to return only first n matching docs?

**Comment by JustinCharbonneau** [comment]
Hello, 

I've encountered the same need. This solution would work if you were the one calling directly the method `_get_relevant_documents`, but if this isn't the case (e.g., you are using existing chains), then we need a way to pass in the desired `n`.

What I've done is create a new class CustomElasticBM25Retriever that inherits from the ElasticSearchBM25Retriever class, add an additional attribute, and change the method to customize its behavior.

- add in the parameter n with default = 10
- update query_dict variable in _get_relevant_documents to use self.n to set the size (total number of returned hits)

![image](https://github.com/langchain-ai/langchain/assets/25487881/f19a1945-71a4-4d90-b098-1251a47f8637)

```python
class CustomElasticBM25Retriever(ElasticSearchBM25Retriever):
    
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)

    client: Any
    """Elasticsearch client."""
    index_name: str
    """Name of the index to use in Elasticsearch."""
    n: int = 10
    """Number of hits to retrieve."""

    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        query_dict = {"query": {"match": {"content": query}}, "size": self.n}
        res = self.client.search(index=self.index_name, body=query_dict)

        docs = []
        for r in res["hits"]["hits"]:
            docs.append(Document(page_content=r["_source"]["content"]))
        return docs
```

I'd be curious to know what others have done for this.

Cheers,
