### ISSUE TITLE
Add `do_sample` to HuggingFaceTextGenInference

### ISSUE THREAD

**Issue by QLutz** [langchain-ai/langchain#9120]
### Feature request

Many parameters described on the TGI [Swagger](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/generate) find their direct equivalent in the corresponding LangChain [API](https://api.python.langchain.com/en/latest/llms/langchain.llms.huggingface_text_gen_inference.HuggingFaceTextGenInference.html?highlight=textgeninference#langchain.llms.huggingface_text_gen_inference.HuggingFaceTextGenInference). 

### Motivation

At least one of those parameters is missing: the `do_sample` parameter which I needed.

### Your contribution

Why is this parameter missing? How hard would it be to add this and can this be circumvented?

**Comment by viditjain99** [comment]
I can help with this change.
