### ISSUE TITLE
Intermediate answer from STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION received as a final answer

### ISSUE THREAD

**Issue by igormis** [langchain-ai/langchain#9122]
### System Info

langchain==0.0.260
model = "gpt-3.5-turbo-16k"
temperature = 0.0

### Who can help?

@hwchase17 and @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [X] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
search_agent = initialize_agent(
        tools=tools,
        llm=llm,
        agent=AgentType.STRUCTURED_CHAT_ZERO_SHOT_REACT_DESCRIPTION,
        memory = memory,

        agent_kwargs = {
        #"suffix": NEW_SUFFIX,
        "memory_prompts": [chat_history],
        "input_variables": ["input", "agent_scratchpad", "chat_history"]
        },
        #prompt=cf_template,
        #handle_parsing_errors=True,
        #max_iterations=2,
        #max_execution_time=10,
        verbose = True,
        handle_parsing_errors=True,
    )
from pprint import pprint
#planner = load_chat_planner(llm)
#executor = load_agent_executor(llm, tools, verbose=True)
#search_agent = PlanAndExecute(planner=planner, executor=executor, verbose=True)
#print(search_agent.agent.llm_chain.prompt)

search_agent.agent.llm_chain.verbose=True
question = "What are the stock price for Apple"
response =  search_agent.run(input = question)
print(response)
#pprint(search_agent.agent.llm_chain.prompt)
question = "What about Google."
response =  search_agent.run(input = question)
print(response)
#pprint(search_agent.agent.llm_chain.prompt)
question = "Show me news for fires in Greece in the last month."
response =  search_agent.run(input = question)
print(response)
question = "what about Macedonia in the previous week."
response =  search_agent.run(input = question)
print(response)
```

### Expected behavior

For the:
```
question = "What about Google."
response =  search_agent.run(input = question)
```
The Agent response is:
```
Human: What about Google.
AI: To provide the current stock price for Google, I will use the "get_current_stock_price" tool. Please wait a moment.
```
Instead it should execute the tool and get the results similar as Apple which is the first query...

**Comment by igormis** [comment]
BTW, I have issue with the response:
Human: What about Google.
AI: To provide the current stock price for Google, I will use the "get_current_stock_price" tool. Please wait a moment.
SO it means that the context with the memory is inderstood by the agent

**Comment by igormis** [comment]
Ok, can u write python code now to generate this prompt

**Comment by igormis** [comment]
I was thinking in a more dynamic way and also to include:

Previous chat history:

Human: Show me the ingredients for making greek salad
AI: XXX
Human: XXX
AI: XXX

Begin!:

New Input:

**Comment by igormis** [comment]
Do you know how to get the user question in a Structured Tool?

**Comment by igormis** [comment]
I was thinking on existing tool

**Comment by Yanni8** [comment]
@igormis Have you found a solution for the issue?
