### ISSUE TITLE
inference configurations are invalid forBedrockEmbeddings models 

### ISSUE THREAD

**Issue by HannaHUp** [langchain-ai/langchain#9127]
### System Info

in sagemaker.
langchain==0.0.256 or 0.0.249 (I tried both)
Image: Data Science 3.0
Kernel: Python 3
Instance type: ml.t3.medium 2 vCPU + 4 GiB

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

https://github.com/aws-samples/amazon-bedrock-workshop/blob/main/03_QuestionAnswering/01_qa_w_rag_claude.ipynb
im trying to following this notebook:

i increase the data input size:
from urllib.request import urlretrieve

```
os.makedirs("data", exist_ok=True)
files = [
    "https://www.irs.gov/pub/irs-pdf/p1544.pdf",
    "https://www.irs.gov/pub/irs-pdf/p15.pdf",
    "https://www.irs.gov/pub/irs-pdf/p1212.pdf",
    "https://www.irs.gov/pub/irs-pdf/p3.pdf",
    "https://www.irs.gov/pub/irs-pdf/p17.pdf",
    "https://www.irs.gov/pub/irs-pdf/p51.pdf",
    "https://www.irs.gov/pub/irs-pdf/p54.pdf",
]
for url in files:
    file_path = os.path.join("data", url.rpartition("/")[2])
    urlretrieve(url, file_path)

```

my data input:
Average length among 1012 documents loaded is 2320 characters.
After the split we have 1167 documents more than the original 1012.
Average length among 1167 documents (after split) is 2011 characters.

```
import numpy as np
from langchain.text_splitter import CharacterTextSplitter, RecursiveCharacterTextSplitter
from langchain.document_loaders import PyPDFLoader, PyPDFDirectoryLoader

loader = PyPDFDirectoryLoader("./data/")

documents = loader.load()
# - in our testing Character split works better with this PDF data set
text_splitter = RecursiveCharacterTextSplitter(
    # Set a really small chunk size, just to show.
    chunk_size = 1000,
    chunk_overlap  = 100,
)
docs = text_splitter.split_documents(documents)

avg_doc_length = lambda documents: sum([len(doc.page_content) for doc in documents])//len(documents)
avg_char_count_pre = avg_doc_length(documents)
avg_char_count_post = avg_doc_length(docs)
print(f'Average length among {len(documents)} documents loaded is {avg_char_count_pre} characters.')
print(f'After the split we have {len(docs)} documents more than the original {len(documents)}.')
print(f'Average length among {len(docs)} documents (after split) is {avg_char_count_post} characters.')

from langchain.chains.question_answering import load_qa_chain
from langchain.vectorstores import FAISS
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper

vectorstore_faiss = FAISS.from_documents(
    docs,
    bedrock_embeddings,
)

wrapper_store_faiss = VectorStoreIndexWrapper(vectorstore=vectorstore_faiss)

```

funny thing is if my doc is smaller(docs[:5]), it worked.
vectorstore_faiss = FAISS.from_documents(
**docs[:5]**,
bedrock_embeddings,
)

error:

---------------------------------------------------------------------------
ValidationException                       Traceback (most recent call last)
File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:120, in BedrockEmbeddings._embedding_func(self, text)
    119 try:
--> 120     response = self.client.invoke_model(
    121         body=body,
    122         modelId=self.model_id,
    123         accept="application/json",
    124         contentType="application/json",
    125     )
    126     response_body = json.loads(response.get("body").read())

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:535, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    534 # The "self" in this scope is referring to the BaseClient.
--> 535 return self._make_api_call(operation_name, kwargs)

File /opt/conda/lib/python3.10/site-packages/botocore/client.py:980, in BaseClient._make_api_call(self, operation_name, api_params)
    979     error_class = self.exceptions.from_code(error_code)
--> 980     raise error_class(parsed_response, operation_name)
    981 else:

ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[35], line 10
      4 from langchain.indexes.vectorstore import VectorStoreIndexWrapper
      6 
      7 
      8 # 
      9 #
---> 10 vectorstore_faiss = FAISS.from_documents(
     11     docs,
     12     bedrock_embeddings,
     13 )
     15 wrapper_store_faiss = VectorStoreIndexWrapper(vectorstore=vectorstore_faiss)

File /opt/conda/lib/python3.10/site-packages/langchain/vectorstores/base.py:420, in VectorStore.from_documents(cls, documents, embedding, **kwargs)
    418 texts = [d.page_content for d in documents]
    419 metadatas = [d.metadata for d in documents]
--> 420 return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)

File /opt/conda/lib/python3.10/site-packages/langchain/vectorstores/faiss.py:607, in FAISS.from_texts(cls, texts, embedding, metadatas, ids, **kwargs)
    581 @classmethod
    582 def from_texts(
    583     cls,
   (...)
    588     **kwargs: Any,
    589 ) -> FAISS:
    590     """Construct FAISS wrapper from raw documents.
    591 
    592     This is a user friendly interface that:
   (...)
    605             faiss = FAISS.from_texts(texts, embeddings)
    606     """
--> 607     embeddings = embedding.embed_documents(texts)
    608     return cls.__from(
    609         texts,
    610         embeddings,
   (...)
    614         **kwargs,
    615     )

File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:148, in BedrockEmbeddings.embed_documents(self, texts, chunk_size)
    146 results = []
    147 for text in texts:
--> 148     response = self._embedding_func(text)
    149     results.append(response)
    150 return results

File /opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py:129, in BedrockEmbeddings._embedding_func(self, text)
    127     return response_body.get("embedding")
    128 except Exception as e:
--> 129     raise ValueError(f"Error raised by inference endpoint: {e}")

ValueError: Error raised by inference endpoint: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid

### Expected behavior

I would like to generate embeddings for the entire corpus and stored in a vector store.

**Comment by HannaHUp** [comment]
The issue_text len is 994
![image](https://github.com/langchain-ai/langchain/assets/43529795/7a719a37-e0fb-4e0d-8f18-f1e4cbd16ae5)

I have tried other text that its len is 1418. I got no issue though.
![image](https://github.com/langchain-ai/langchain/assets/43529795/73d07e70-de5e-4891-a655-45836af8f4ab)

**Comment by HannaHUp** [comment]
@dosu-bot
I don't think I'm using DeepInfraEmbeddings though. The error is from opt/conda/lib/python3.10/site-packages/langchain/embeddings/bedrock.py

**Comment by VadneyK** [comment]
I'm having the same error message with the default configurations too:

`---------------------------------------------------------------------------
ValidationException                       Traceback (most recent call last)
File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/bedrock.py:191, in Bedrock._call(self, prompt, stop, run_manager, **kwargs)
    190 try:
--> 191     response = self.client.invoke_model(
    192         body=body, modelId=self.model_id, accept=accept, contentType=contentType
    193     )
    194     text = LLMInputOutputAdapter.prepare_output(provider, response)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/client.py:535, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    534 # The "self" in this scope is referring to the BaseClient.
--> 535 return self._make_api_call(operation_name, kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/botocore/client.py:980, in BaseClient._make_api_call(self, operation_name, api_params)
    979     error_class = self.exceptions.from_code(error_code)
--> 980     raise error_class(parsed_response, operation_name)
    981 else:

ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[24], line 1
----> 1 answer = wrapper_store_faiss.query(question=query, llm=llm)
      2 print_ww(answer)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/indexes/vectorstore.py:41, in VectorStoreIndexWrapper.query(self, question, llm, **kwargs)
     37 llm = llm or OpenAI(temperature=0)
     38 chain = RetrievalQA.from_chain_type(
     39     llm, retriever=self.vectorstore.as_retriever(), **kwargs
     40 )
---> 41 return chain.run(question)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:451, in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    449     if len(args) != 1:
    450         raise ValueError("`run` supports only one positional argument.")
--> 451     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    452         _output_key
    453     ]
    455 if kwargs and not args:
    456     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    457         _output_key
    458     ]

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:258, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)
--> 258     raise e
    259 run_manager.on_chain_end(outputs)
    260 final_outputs: Dict[str, Any] = self.prep_outputs(
    261     inputs, outputs, return_only_outputs
    262 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:252, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    246 run_manager = callback_manager.on_chain_start(
    247     dumpd(self),
    248     inputs,
    249 )
    250 try:
    251     outputs = (
--> 252         self._call(inputs, run_manager=run_manager)
    253         if new_arg_supported
    254         else self._call(inputs)
    255     )
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py:133, in BaseRetrievalQA._call(self, inputs, run_manager)
    131 else:
    132     docs = self._get_docs(question)  # type: ignore[call-arg]
--> 133 answer = self.combine_documents_chain.run(
    134     input_documents=docs, question=question, callbacks=_run_manager.get_child()
    135 )
    137 if self.return_source_documents:
    138     return {self.output_key: answer, "source_documents": docs}

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:456, in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    451     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    452         _output_key
    453     ]
    455 if kwargs and not args:
--> 456     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    457         _output_key
    458     ]
    460 if not kwargs and not args:
    461     raise ValueError(
    462         "`run` supported with either positional arguments or keyword arguments,"
    463         " but none were provided."
    464     )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:258, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)
--> 258     raise e
    259 run_manager.on_chain_end(outputs)
    260 final_outputs: Dict[str, Any] = self.prep_outputs(
    261     inputs, outputs, return_only_outputs
    262 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:252, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    246 run_manager = callback_manager.on_chain_start(
    247     dumpd(self),
    248     inputs,
    249 )
    250 try:
    251     outputs = (
--> 252         self._call(inputs, run_manager=run_manager)
    253         if new_arg_supported
    254         else self._call(inputs)
    255     )
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py:106, in BaseCombineDocumentsChain._call(self, inputs, run_manager)
    104 # Other keys are assumed to be needed for LLM prediction
    105 other_keys = {k: v for k, v in inputs.items() if k != self.input_key}
--> 106 output, extra_return_dict = self.combine_docs(
    107     docs, callbacks=_run_manager.get_child(), **other_keys
    108 )
    109 extra_return_dict[self.output_key] = output
    110 return extra_return_dict

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py:165, in StuffDocumentsChain.combine_docs(self, docs, callbacks, **kwargs)
    163 inputs = self._get_inputs(docs, **kwargs)
    164 # Call predict on the LLM.
--> 165 return self.llm_chain.predict(callbacks=callbacks, **inputs), {}

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/llm.py:252, in LLMChain.predict(self, callbacks, **kwargs)
    237 def predict(self, callbacks: Callbacks = None, **kwargs: Any) -> str:
    238     """Format prompt with kwargs and pass to LLM.
    239 
    240     Args:
   (...)
    250             completion = llm.predict(adjective="funny")
    251     """
--> 252     return self(kwargs, callbacks=callbacks)[self.output_key]

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:258, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)
--> 258     raise e
    259 run_manager.on_chain_end(outputs)
    260 final_outputs: Dict[str, Any] = self.prep_outputs(
    261     inputs, outputs, return_only_outputs
    262 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/base.py:252, in Chain.__call__(self, inputs, return_only_outputs, callbacks, tags, metadata, include_run_info)
    246 run_manager = callback_manager.on_chain_start(
    247     dumpd(self),
    248     inputs,
    249 )
    250 try:
    251     outputs = (
--> 252         self._call(inputs, run_manager=run_manager)
    253         if new_arg_supported
    254         else self._call(inputs)
    255     )
    256 except (KeyboardInterrupt, Exception) as e:
    257     run_manager.on_chain_error(e)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/llm.py:92, in LLMChain._call(self, inputs, run_manager)
     87 def _call(
     88     self,
     89     inputs: Dict[str, Any],
     90     run_manager: Optional[CallbackManagerForChainRun] = None,
     91 ) -> Dict[str, str]:
---> 92     response = self.generate([inputs], run_manager=run_manager)
     93     return self.create_outputs(response)[0]

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/chains/llm.py:102, in LLMChain.generate(self, input_list, run_manager)
    100 """Generate LLM result from inputs."""
    101 prompts, stop = self.prep_prompts(input_list, run_manager=run_manager)
--> 102 return self.llm.generate_prompt(
    103     prompts,
    104     stop,
    105     callbacks=run_manager.get_child() if run_manager else None,
    106     **self.llm_kwargs,
    107 )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/base.py:451, in BaseLLM.generate_prompt(self, prompts, stop, callbacks, **kwargs)
    443 def generate_prompt(
    444     self,
    445     prompts: List[PromptValue],
   (...)
    448     **kwargs: Any,
    449 ) -> LLMResult:
    450     prompt_strings = [p.to_string() for p in prompts]
--> 451     return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/base.py:582, in BaseLLM.generate(self, prompts, stop, callbacks, tags, metadata, **kwargs)
    573         raise ValueError(
    574             "Asked to cache, but no cache found at `langchain.cache`."
    575         )
    576     run_managers = [
    577         callback_manager.on_llm_start(
    578             dumpd(self), [prompt], invocation_params=params, options=options
    579         )[0]
    580         for callback_manager, prompt in zip(callback_managers, prompts)
    581     ]
--> 582     output = self._generate_helper(
    583         prompts, stop, run_managers, bool(new_arg_supported), **kwargs
    584     )
    585     return output
    586 if len(missing_prompts) > 0:

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/base.py:488, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    486     for run_manager in run_managers:
    487         run_manager.on_llm_error(e)
--> 488     raise e
    489 flattened_outputs = output.flatten()
    490 for manager, flattened_output in zip(run_managers, flattened_outputs):

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/base.py:475, in BaseLLM._generate_helper(self, prompts, stop, run_managers, new_arg_supported, **kwargs)
    465 def _generate_helper(
    466     self,
    467     prompts: List[str],
   (...)
    471     **kwargs: Any,
    472 ) -> LLMResult:
    473     try:
    474         output = (
--> 475             self._generate(
    476                 prompts,
    477                 stop=stop,
    478                 # TODO: support multiple run managers
    479                 run_manager=run_managers[0] if run_managers else None,
    480                 **kwargs,
    481             )
    482             if new_arg_supported
    483             else self._generate(prompts, stop=stop)
    484         )
    485     except (KeyboardInterrupt, Exception) as e:
    486         for run_manager in run_managers:

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/base.py:961, in LLM._generate(self, prompts, stop, run_manager, **kwargs)
    958 new_arg_supported = inspect.signature(self._call).parameters.get("run_manager")
    959 for prompt in prompts:
    960     text = (
--> 961         self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
    962         if new_arg_supported
    963         else self._call(prompt, stop=stop, **kwargs)
    964     )
    965     generations.append([Generation(text=text)])
    966 return LLMResult(generations=generations)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/langchain/llms/bedrock.py:197, in Bedrock._call(self, prompt, stop, run_manager, **kwargs)
    194     text = LLMInputOutputAdapter.prepare_output(provider, response)
    196 except Exception as e:
--> 197     raise ValueError(f"Error raised by bedrock service: {e}")
    199 if stop is not None:
    200     text = enforce_stop_tokens(text, stop)

ValueError: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid`

**Comment by Kevin-McIsaac** [comment]
I have the same problem. The issue appears to be the number of tokens (or lenght of the text)

```
from langchain.embeddings import BedrockEmbeddings
BedrockEmbeddings(region_name="us-east-1").embed_query('word '*509)
```
works
```
from langchain.embeddings import BedrockEmbeddings
BedrockEmbeddings(region_name="us-east-1").embed_query('word '*510)
```
gives a validation error
```
ValueError: Error raised by inference endpoint: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid
```

**Comment by HannaHUp** [comment]
> I have the same problem. The issue appears to be the number of tokens (or lenght of the text)
> 
> ```
> from langchain.embeddings import BedrockEmbeddings
> BedrockEmbeddings(region_name="us-east-1").embed_query('word '*509)
> ```
> 
> works
> 
> ```
> from langchain.embeddings import BedrockEmbeddings
> BedrockEmbeddings(region_name="us-east-1").embed_query('word '*510)
> ```
> 
> gives a validation error
> 
> ```
> ValueError: Error raised by inference endpoint: An error occurred (ValidationException) when calling the InvokeModel operation: The provided inference configurations are invalid
> ```

Yes it is embedding model issue. I keep set the chunk size smaller and smller in order to get the embedding model works.
But it doesn't make sense.  Since the length of input tokens limited to 512 tokens, which roughly translates to ~2000 characters, I assume that all my input should not give me error because the max was 1000 characters and it is well below 2000 characters.

**Comment by Kevin-McIsaac** [comment]
Another way to sovle the chunking problem is to use `from_tiktoken_encoder` to count by tokens rather than characters.e.g, 

```
from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

tiktoken_splitter = RecursiveCharacterTextSplitter.from_tiktoken_encoder(
    chunk_size=500, chunk_overlap=0
)
pdf_docs = [doc for pdf in glob.glob('data/*.pdf') for doc in PyPDFLoader(pdf).load_and_split(tiktoken_splitter)  ]
```
