### ISSUE TITLE
LangChain tools as gpt func, always fails at the JSON decode

### ISSUE THREAD

**Issue by dafang** [langchain-ai/langchain#9130]
### System Info

Python 3.10
LangChain: 0.0.245

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I write a 'Python interpreter' tool, as below sample code:

```
class PythonInterpreterTool(BaseTool):
    name = "python_interpreter"
    name_display = "Python Interpreter"
    description = """Give me the Python to execute，it returns the execution result"""

    def _run(self, code: str) -> str:
        with PythonInterpreter() as executor: # type: ignore
            output = executor.run_python_code(code)

            return output

    async def _arun(self, code: str) -> str:
        raise NotImplementedError
```
But, for many times, I always got "Could not parse tool input... because the `arguments` is not valid JSON." error:

Could not parse tool input: {'name': 'python_interpreter', 'arguments': '{\n  "__arg1": "\nimport moviepy.editor as mp\n\nvideo_path = \'https://video-clip.oss.com/upload/40ae1ae0-3799-11ee-9c80-476f00f64986.mp4\'\noutput_path = \'output.mp3\'\n\nvideo = mp.VideoFileClip(video_path)\nvideo.audio.write_audiofile(output_path)\n"\n}'} because the `arguments` is not valid JSON.

### Expected behavior

I write a 'Python interpreter' tool, as below sample code:

```
class PythonInterpreterTool(BaseTool):
    name = "python_interpreter"
    name_display = "Python Interpreter"
    description = """Give me the Python to execute，it returns the execution result"""

    def _run(self, code: str) -> str:
        with PythonInterpreter() as executor: # type: ignore
            output = executor.run_python_code(code)

            return output

    async def _arun(self, code: str) -> str:
        raise NotImplementedError
```
But, for many times, I always got "Could not parse tool input... because the `arguments` is not valid JSON." error:

Could not parse tool input: {'name': 'python_interpreter', 'arguments': '{\n  "__arg1": "\nimport moviepy.editor as mp\n\nvideo_path = \'https://video-clip.oss.com/upload/40ae1ae0-3799-11ee-9c80-476f00f64986.mp4\'\noutput_path = \'output.mp3\'\n\nvideo = mp.VideoFileClip(video_path)\nvideo.audio.write_audiofile(output_path)\n"\n}'} because the `arguments` is not valid JSON.

**Comment by dafang** [comment]
This code is generated by gpt.

**Comment by keenborder786** [comment]
@dafang why don't you simply use `PythonREPLTool` from langchain itself.
