### ISSUE TITLE
GoogleSerperRun._arun() got an unexpected keyword argument 'arg1'

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#9144]
### Issue you'd like to raise.

llm = OpenAI(temperature=0, model_name = args.ModelName)
system_message = SystemMessage(content=template)
agent_kwargs = {
    "extra_prompt_messages": [MessagesPlaceholder(variable_name="memory")],
    "system_message": system_message,
}

tools = load_tools(["google-serper"], llm=llm)
agent_executor = initialize_agent(
        tools,
        llm,
        agent=AgentType.OPENAI_FUNCTIONS,
        agent_kwargs= agent_kwargs,
        verbose = True,
        memory = memory,
        handle_parsing_errors=True,
    )

I am getting this error GoogleSerperRun._arun() got an unexpected keyword argument 'arg1'.
Can anyone explain why is it so

**Comment by aniruddha-adhikary** [comment]
Just in case anyone found this...

One of the reasons for this happening is, a BaseTool declaring `_run` with `*args` and `**kwargs`, while declaring `_arun` with concrete argument names.
