### ISSUE TITLE
Custom Parameter/ Json Payload for from_llm_and_api_docs() function

### ISSUE THREAD

**Issue by tfbecker** [langchain-ai/langchain#9151]
### Feature request

I am trying to use the from_llm_and_api_docs() function with an API that only supports parameters via the "params" parameter in the request library: 
The from_llm_and_api_docs works well with apis that encode parameters in the URl. Eg: https://api.open-meteo.com/v1/forecast/latitude=123&longitude=123

I would need langchain to generate a json_payload and input it into the "params" parameter in the request header. I looked into the Langchain code and it seems like that this line:
requests_wrapper = TextRequestsWrapper(headers=headers)
needs to be augmented with a "params" parameter.

Example:
r = requests.get('https://www.domain.com/endpoint',params=params,cookies=cookies, headers=headers,json=json_data)

json_data = {
        'field_ids': field_ids,
        'order': [
            {
                'field_id': 'rank_org_company',
                'sort': sort_order,
            },
        ],
        'query': [
                {
                    'type': 'predicate',
                    'field_id': 'founded_on',
                    'operator_id': 'gte',
                    'values': [
                        '01/01/2018',
                    ],
                },
                {
                    'type': 'predicate',
                    'field_id': 'equity_funding_total',
                    'operator_id': 'lte',
                    'values': [
                        {
                            'value': 15000000,
                            'currency': 'usd',
                        },
                    ],
                },
                {
                    'type': 'predicate',
                    'field_id': 'location_identifiers',
                    'operator_id': 'includes',
                    'values': [
                        '6106f5dc-823e-5da8-40d7-51612c0b2c4e',
                    ],
                }
            ],
        'field_aggregators': [],
        'collection_id': 'organization.companies',
        'limit': 1000,
    }

How do I need to change the from_llm_and_api_docs() accordingly?

### Motivation

Many APIs are controlled via a json payload and not solely via parameters in the URL.

### Your contribution

I could look into changing the request wrapper but maybe there is a more elegant way of doing so.

**Comment by tfbecker** [comment]
Thank you. This is partially solving the problem. I would like to define the parameters and how to use them in the  api_docs object. Then I want the agent to figure out how to modify the "params" object (example: list of dicts) to get the desired output.
The "params" object would replace the request URL that langchain generates. The agent would purely query the API via the parameters object.

**Comment by tfbecker** [comment]
Example:
API DOCS: 
Parameter	Format	Required	Default	Description
funding_total	integer	No	Total funding amount of a company

Input: "I want to find companies that have a minimum total funding amount of 10million USD"
Parsed Query:

json_data = {
'field_ids': field_ids,
'order': [
{
'field_id': 'rank_org_company',
'sort': sort_order,
},
],
'query': [
{
'type': 'predicate',
'field_id': 'funding_total',
'operator_id': 'lte',
'values': [
{
'value': 10000000,
'currency': 'usd',
},
],
}
],
'field_aggregators': [],
'collection_id': 'organization.companies',
'limit': 50,
}

r = requests.get('https://www.domain.com/endpoint',params=params,cookies=cookies, headers=headers,json=json_data)

The agent will correctly have changed the json payload/ params object to facilitate the query.
The API will return a list of 50 companies that match the criteria: total_funding_amount > 10000000.

**Comment by pariwartan** [comment]
@dosubot How to call a Post API and pass request body in APIChain.from_llm_and_api_docs?
