### ISSUE TITLE
Caching (SQLiteCache/InMemoryCache etc.) is not working with ConversationalRetrievalChain

### ISSUE THREAD

**Issue by mail2mhossain** [langchain-ai/langchain#9168]
### System Info

LangChain Version- 0.0.260, platform- Windows, Python Version-3.9.16

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am trying to use SQLiteCache  along with ConversationalRetrievalChain, but never getting results from cache, always executing LLMs.

My code is as follows:

langchain.llm_cache = SQLiteCache(database_path=".langchain.db")

langchain.llm_cache = SQLiteCache(database_path=".langchain.db")
from langchain.cache import InMemoryCache

langchain.llm_cache = InMemoryCache()
# Embeddings
embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL, model_kwargs=model_kwargs, encode_kwargs=encode_kwargs
)
# langchain.llm_cache = RedisSemanticCache(
#     redis_url="redis://localhost:6379", embedding=embeddings
# )

dimension = 768
index = faiss.IndexFlatL2(dimension)

vectorstore = FAISS(
    HuggingFaceEmbeddings().embed_query, index, InMemoryDocstore({}), {}
)

history_retriever = vectorstore.as_retriever(search_type="mmr", search_kwargs=dict(k=3))

memory = VectorStoreRetrieverMemory(
    retriever=history_retriever,
    memory_key="chat_history",
    return_docs=False,
    return_messages=True,
)

chroma = Chroma(
    collection_name="test_db",
    embedding_function=embeddings,
    persist_directory=persist_directory,
)

llm = ChatOpenAI(temperature=0, model=GPT_MODEL)

retriever = MultiQueryRetriever.from_llm(
    retriever=chroma.as_retriever(search_type="mmr", search_kwargs=dict(k=3)), llm=llm
)

qa_chain = ConversationalRetrievalChain.from_llm(
    llm,
    retriever=retriever,
    memory=memory,
    return_source_documents=True,
    get_chat_history=lambda h: h,
)

responses = qa_chain({"question": user_input})

### Expected behavior

Should be return results from cache if the query is same

**Comment by mail2mhossain** [comment]
langchain.llm_cache = SQLiteCache(database_path=".langchain.db")

dimension = 768
index = faiss.IndexFlatL2(dimension)

vectorstore = FAISS(
    HuggingFaceEmbeddings().embed_query, index, InMemoryDocstore({}), {}
)

history_retriever = vectorstore.as_retriever(search_type="mmr", search_kwargs=dict(k=3))

memory = VectorStoreRetrieverMemory(
    retriever=history_retriever,
    memory_key="chat_history",
    return_docs=False,
    return_messages=True,
)

chroma = Chroma(
    collection_name="corporate_db",
    embedding_function=embeddings,
    persist_directory=persist_directory,
)

llm = ChatOpenAI(temperature=0, model=GPT_MODEL)

retriever = MultiQueryRetriever.from_llm(
    retriever=chroma.as_retriever(search_type="mmr", search_kwargs=dict(k=3)), llm=llm
)

qa_chain = ConversationalRetrievalChain.from_llm(
    llm,
    retriever=retriever,
    memory=memory,
    return_source_documents=True,
    get_chat_history=lambda h: h,
)

responses = qa_chain({"question": user_input})

**Comment by Kittyxox** [comment]
@mail2mhossain , have u found the solution for this? I am also facing same issue!
