### ISSUE TITLE
Unable to add PromptTemplate/FewShotPromptTemplate to LangChain Agents

### ISSUE THREAD

**Issue by gaushh** [langchain-ai/langchain#9175]
### System Info

Langchain Version - 0.0.261
Python Version - 3.9.6
OS -MacOS

### Who can help?

@hwchase17 @ago

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Here is how I am initialising the agent
`sys_msg = """
The custom system message of the chatbot goes here. 
"""
tools = [CustomTool()]
agent = initialize_agent(
    agent='chat-conversational-react-description',
    tools=tools,
    llm=llm,
    verbose=True,
    max_iterations=4,
    early_stopping_method='generate',
    memory=conversational_memory,
    handle_parsing_errors=True,
)

new_prompt = agent.agent.create_prompt(
    system_message=sys_msg,
    tools=tools
)

agent.agent.llm_chain.prompt = new_prompt`

### Expected behavior

I want to be able to align the output content and format of the chatbot better with my expectations. Right now I just give those instructions using system message. I believe the Final Output can be aligned better using a few shot examples. How can I possibly do that with an Agent?

**Comment by onanorange** [comment]
Thank you for your reply! I encountered a similar problem and I ran your code and has this error:
from langchain.prompts import FewShotChatMessagePromptTemplate, ChatPromptTemplate

examples = [
    {"input": "2+2", "output": "4"},
    {"input": "2+3", "output": "5"},
]

example_prompt = ChatPromptTemplate.from_messages(
    [('human', '{input}'), ('ai', '{output}')]
)

few_shot_prompt = FewShotChatMessagePromptTemplate(
    examples=examples,
    example_prompt=example_prompt,
)

final_prompt = ChatPromptTemplate.from_messages(
    [
        ('system', 'You are a helpful AI Assistant'),
        few_shot_prompt,
        ('human', '{input}'),
    ]
)
final_prompt.format(input="What is 4+4?")
