### ISSUE TITLE
Error Response payload is not complete 

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#9187]
### Issue you'd like to raise.

 I am using pusher for streaming purpose.
I am getting error as "Response payload is not completed"

async def pusher__cal(new_payload, token):
# print(token)
session_id = new_payload["session_id"]
session_id_channel = f"{session_id}_channel"
user_id = new_payload["user_id"]
message_id = new_payload["message_id"]
status = "processing"

await asyncio.sleep(0)  # Allow other async tasks to run
pusher_client.trigger(session_id_channel ,'query_answer_stream', {
                    "user_id": user_id,
                    "session_id": session_id,
                    "message_id": message_id,
                    "answer": token,
                    "status": status
                    },
                    )

class MyCallbackHandler(AsyncCallbackHandler):
def init(self,new_payload : Dict):
self.new_payload = new_payload
self.user_id = new_payload["user_id"]
self.session_id = new_payload["session_id"]
self.message_id = new_payload["message_id"]
self.session_id_channel = f"{self.session_id}_channel"
self.status = "streaming"
self.list = []

async def on_llm_new_token(self, token, **kwargs) -> None:

    if token != "":
        await pusher__cal(self.new_payload,token)

**Comment by ShantanuNair** [comment]
@Ajaypawar02 Did you fix this? I'm running into the same, and it's causing retries.

**Comment by Kevinello** [comment]
https://github.com/openai/openai-python/issues/574
