### ISSUE TITLE
Issue: Using custom_id with PGVector store

### ISSUE THREAD

**Issue by rahulnyk** [langchain-ai/langchain#9209]
### Issue you'd like to raise.

Hi, 
I have a pandas dataframe with a column name 'chunk_id'. 
I want to use this chunk_id as the custom_id in the langchain_pg_embedding table. 

The langchain documentation search bot tells me this is how I can do it. 

```python
from langchain.vectorstores import PGVectorStore

vector_store = PGVectorStore(
    table_name="documents", 
    conn_str="postgresql://username:password@localhost:5432/database",
    custom_id="my_custom_id" 
)
```

This doesn't seem right to me. For one, there is no PGVectorStore in langchain.vectorstores. Secondly the PGVector from `from langchain.vectorstores.pgvector import PGVector` does not accept the custom_id argument. 

Is there any way to use my 'chunk_id' as the custom_id?

**Comment by rahulnyk** [comment]
Thanks, this works with add_embeddings as well as add_texts

**Comment by auyer** [comment]
In case it helps anyone, this also works with `add_documents(docs, ids=ids)`. The names key "ids" will be passed as `kwargs` all the way.
