### ISSUE TITLE
Kernel dies for SVMRetriever with Huggingface Embeddings Model

### ISSUE THREAD

**Issue by AjinkyaBankar** [langchain-ai/langchain#9219]
### System Info

langchain==0.0.245
python==3.9

### Who can help?

@hw

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I am trying to use HuggingFace Embeddings model for SVMRetriever method as follows:
```
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.retrievers import SVMRetriever

embedding = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
retriever = SVMRetriever.from_texts(["foo", "bar", "world", "hello", "foo bar"], 
                                                           embedding, 
                                                           k=4, relevancy_threshold=.25)
```
Kernel looks busy for a while and then dies when I run above snippet.

### Expected behavior

I expect to run this smoothly and upon completion, should be able to retrieve similar documents as:
`result = retriever.get_relevant_documents("foo")`

**Comment by AjinkyaBankar** [comment]
Hello @dosu-beta, it works with `HuggingFaceHubEmbeddings`, where I can specify `task=feature-extraction` as follows:
```
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "hf_my_key"
from langchain.embeddings import HuggingFaceHubEmbeddings

embedding = HuggingFaceHubEmbeddings(repo_id="sentence-transformers/all-mpnet-base-v2", task="feature-extraction")
retriever = SVMRetriever.from_texts(["foo", "bar", "world", "hello", "foo bar"], 
                                                           embedding, 
                                                           k=4, relevancy_threshold=.25)
result = retriever.get_relevant_documents("foo")
```
But I don't want to use HuggingFaceHub API. I want to download the model locally and then run with `HuggingFaceEmbeddings`. But `HuggingFaceEmbeddings` doesn't accept  `task=feature-extraction` as a parameter. Is there any alternate way?

**Comment by AjinkyaBankar** [comment]
@dosu-bot Can you give example script to pass above `doc_embeddings` to `SVMRetriever` method? And how to retrieve similar documents?

**Comment by AjinkyaBankar** [comment]
@dosu-bot It doesn't work. It's giving the error as follows-
```
---> 25         return np.array(list(executor.map(embeddings.embed_query, contexts)))
     26 
     27 

AttributeError: 'list' object has no attribute 'embed_query'
```

**Comment by AjinkyaBankar** [comment]
Can someone look into this issue?

**Comment by devstein** [comment]
@AjinkyaBankar Are you able to run the code as Python script instead of within a Jupyter notebook? The error message you get from a local script will likely be more helpful than what is getting swallowed by the kernel.

Sometimes kernels can die silently from out of memory issues too (local models can be resource intensive)

**Comment by AjinkyaBankar** [comment]
@devstein Sorry, I can't run the script as a local python code instead of a Jupyter notebook.

**Comment by devstein** [comment]
@AjinkyaBankar Ok that helps narrow down the issue. Can you use sentence transformer models without LangChain in a GPU environment? My guess is this is unrelated to LangChain and would recommend looking at Hugging face issues or ask their community

**Comment by AjinkyaBankar** [comment]
@devstein I ran the following lines in Google Colab notebook (without Langchain):
```
!pip install sentence_transformers

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2')

#Sentences we want to encode. Example:
sentence = ['This framework generates embeddings for each input sentence']

#Sentences are encoded by calling model.encode()
embedding = model.encode(sentence)

print(embedding)
```
It executes with GPU and CPU without any issues. I also tried with other `paraphrase-MiniLM-L6-v2` model. My kernel freezing for SVMRetriever shouldn't be related to Hugging Face?

**Comment by devstein** [comment]
@AjinkyaBankar Got it. Not sure what the issue is then 🤷‍♂️  The only suspect lines in SVMRetriever code is [this coroutine code](https://github.com/langchain-ai/langchain/blob/c194828be063a6e8e1fb6156e139e0d109a2b26c/libs/langchain/langchain/retrievers/svm.py#L24-L25)

**Comment by AjinkyaBankar** [comment]
Thanks @devstein for taking time to help debug the issue. Can someone else from Langchain check this issue?

**Comment by Abhinay1997** [comment]
I faced the same issue using `HuggingFaceEmbeddings` and `SVMRetriever`. In my case the issue was with `create_index` in `svm.py`

The Threadpool executer was somehow failing on `executor.map(embeddings.embed_query, contexts)` so I made my own without a Threadpool ( I know I know, yet to implement multithreading on it)

But the idea is to build index yourself so you can just do 

```python
embeddings = HuggingFaceEmbeddings()

def create_svm_index(docs, embeddings):
     result = []
     for doc in docs:
          result.append(embeddings.embed_query(doc))
     return np.array(result)

index = create_svm_index(docs, embeddings)
svm_retriever = SVMRetriever(index = index, texts = docs, embeddings = embeddings)

#instead of:
#svm_retriever = SVMRetriever.from_texts(texts=docs, embeddings=embeddings)
```
