### ISSUE TITLE
Error importing langchain in streamlit

### ISSUE THREAD

**Issue by nqbao** [langchain-ai/langchain#922]
I was following this template but If you import the root langchain module in streamlit, you will get the following error

```
import langchain
```

```
ConfigError: duplicate validator function "langchain.prompts.base.BasePromptTemplate.validate_variable_names"; if this is intended, set `allow_reuse=True`
```

<img width="721" alt="Screen Shot 2023-02-06 at 11 27 25 PM" src="https://user-images.githubusercontent.com/177742/217177663-945f54c1-2816-404c-9d0c-145cd7cce3f2.png">

any idea what it could be?

**Comment by vvv-tech** [comment]
that's a pydantic package problem 
https://github.com/streamlit/streamlit/issues/3218

**Comment by nqbao** [comment]
Do you know if we have a page somewhere i can put this document to? so that someone can have the answer next time?
