### ISSUE TITLE
Issue: trying to call generate_queries() on a MultiQueryRetriever but where do I get a run_manager from?

### ISSUE THREAD

**Issue by maspotts** [langchain-ai/langchain#9231]
### Issue you'd like to raise.

I'm trying to use `MultiQueryRetriever` to generate variations on a question: it seems to work, but I can't use it inside a chain created with `load_qa_with_sources_chain()` because that generates a chain that expects a list of input_documents, rather than a retriever, and I don't want to use `RetrievalQAWithSourcesChain` instead of `load_qa_with_sources_chain()` because I want to continue implementing my own similarity search (eg. I'm supporting switches to select using `index.similarity_search()` vs. `index.max_marginal_relevance_search()` on my `index`, and to specify the number of matches (`k`)), so I figured I could just call `generate_queries()` on my `MultiQueryRetriever` instance and then manually run my (`load_qa_with_sources_chain()`) chain for each variation.  However, that method requires a `run_manager`, and I can't figure out how to create one.  I already have the `load_qa_with_sources_chain()` chain: can I get a `run_manager` from that?  Or more generally, what's the best way to use `MultiQueryRetriever` whilst maintaining one's own code for fetching matching text snippets?

**Comment by maspotts** [comment]
I see that `CallbackManagerForRetrieverRun()` actually requires 3 arguments: `run_id`, `handlers` and `inheritable_handlers`, so I am still not able to run `generate_queries()` on my `MultiQueryRetriever` instance.  Does anyone know if I'm barking up the wrong tree here?

**Comment by maspotts** [comment]
I'm wondering whether I need to define a subclass of MultiQueryRetriever, in which I override `_get_relevant_documents()` to incorporate my own similarity search code?

**Comment by pagspann** [comment]
Nope, having the same issue, pls help me too
