### ISSUE TITLE
Issue: load_summarization_chain in 'map_reduce' mode not breaking up document

### ISSUE THREAD

**Issue by omnific9** [langchain-ai/langchain#9235]
### Issue you'd like to raise.

I'm using the load_summarization_chain with the type of 'map_reduce' in the following fashion:

```
    summary_prompt = ChatPromptTemplate.from_template(
        "Write a long-form summary of the following text delimited by triple backquotes. "
        "Include detailed evidence and arguments to make sure the generated paragraph is convincing. "
        "Write in Chinese."
        "```{text}```"
    )

    combine_prompt = ChatPromptTemplate.from_template(
        "Write a long-form summary of the following text delimited by triple backquotes. "
        "Include all the details as much as possible."
        "Write in Chinese."
        "```{text}```"
    )
    combined_summary_chain = load_summarize_chain(llm=llm, chain_type="map_reduce", map_prompt=summary_prompt,
                                                  combine_prompt=combine_prompt, return_intermediate_steps=True)

    summary, inter_steps = combined_summary_chain({"input_documents": data, "token_max": 8000})

```

I've checked several tutorials and there doesn't seem to be anything wrong with this. But I keep getting this error:
`openai.error.InvalidRequestError: This model's maximum context length is 8192 tokens. However, your messages resulted in 15473 tokens. Please reduce the length of the messages.`

It's as if the map_reduce chain isn't breaking up the data and running as if it's a stuffing chain instead. What did I do wrong?

**Comment by metaswang** [comment]
Hi I believe this issue will still confuse you if you keep `max_tokens` **NOT none** when init llm before run your map_reduce chain.
```python
llm = ChatOpenAI(temperature=0, max_tokens=MAX_TOKENS)
```
