### ISSUE TITLE
This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by Ajaypawar02** [langchain-ai/langchain#9237]
### Issue you'd like to raise.

def define_model(model_threshold):
  get_no = np.random.randint(1, 11)
  if int(model_threshold) >= get_no:
    return "gpt-4-0613"
  else:
    return "gpt-3.5-turbo-16k-0613"

messages = get_chat_history_format(api_params=api_params)    
    model_name = define_model(model_threshold)
    print(f"Model Name : {model_name}")
    llm = ChatOpenAI(temperature=0.7, model_name = model_name, streaming = True, callbacks = [MyCallbackHandler(api_params)])
    agent_executor = initialize_agent(
        define_search_tools(llm),
        llm,
        system_message = system_message,
        extra_prompt_messages = [MessagesPlaceholder(variable_name="memory")],
        agent_instructions = "Analyse the query closely and decide the query intend. If the query requires internet to search than use google-serper to answer the query. Try to invoke `google-serper` most of the times",
        agent=AgentType.OPENAI_FUNCTIONS,
        agent_kwargs= agent_kwargs,
        verbose = True,
        memory = memory,
        handle_parsing_errors=True,
    )

I am getting endpoint error

**Comment by Ajaypawar02** [comment]
I am getting this error "This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?"

**Comment by Ajaypawar02** [comment]
change gpt-4 to gpt-4-0613

**Comment by reedwi** [comment]
that does not work

**Comment by davidgao7** [comment]
It doesn't work for me on csv agent either, I want the agent to output the result dataframe also, is there any template example to create a csv agent myself?
