### ISSUE TITLE
Random question and Answer generation while using ConversationalRetrievalChain  

### ISSUE THREAD

**Issue by codebyte17** [langchain-ai/langchain#9241]
### System Info

python 3.11
langchain 0.0.263.

### Who can help?

@agol

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [X] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

I want to add memory into docs based question answer chatbot but after adding memory the chatbot randomly generate question and answer automatically.
![testing](https://github.com/langchain-ai/langchain/assets/125140336/52cf28c9-da29-42c0-8ab5-075983679c61)

### Expected behavior

I need chatbot for docs based question answer and chat history.

**Comment by RohanSohani30** [comment]
did you find a solution to this issue?
