### ISSUE TITLE
intermediate_steps missing last thought content

### ISSUE THREAD

**Issue by jiangcheng1214** [langchain-ai/langchain#9262]
### System Info

Problem:
The intermediate_steps don't contain last `AI thought information`. Did I do anything wrong or was that a bug?
Or is there anything I can do to extract the last `AI thought information`?

Code:
```
agent = initialize_agent(
            [self.search_tool, self.wikipedia_tool],
            self.llm,
            agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
            verbose=True,
            max_iterations=5,
            handle_parsing_errors=True,
            return_intermediate_steps=True
        )
        result = agent(formatted_script_template)
        intermediate_steps = result['intermediate_steps']
```

The intermediate_steps contains only one step and it is missing the last `Thought`

What intermediate_steps look like:
<img width="644" alt="Screenshot 2023-08-15 at 11 19 40 AM" src="https://github.com/langchain-ai/langchain/assets/3535601/d22bc6dd-11b1-4974-97dd-594bd7038d04">

What I expected to have:
<img width="1170" alt="Screenshot 2023-08-15 at 11 20 59 AM" src="https://github.com/langchain-ai/langchain/assets/3535601/6457135b-3257-42ba-801c-8f5523830337">

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run the code I provided in the description and set breakpoint to inspect intermediate steps.
The thought was missing in intermediate steps.

### Expected behavior

The complete observation & thought will be available in intermediate steps.

**Comment by jiangcheng1214** [comment]
@dosu-bot
I'm actually using `ZERO_SHOT_REACT_DESCRIPTION` agent type.

According to your suggestion. `final_outputs` was None for me :(
```
agent = initialize_agent(
            [self.search_tool, self.wikipedia_tool],
            self.llm,
            agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
            verbose=True,
            max_iterations=5,
            handle_parsing_errors=True,
            return_intermediate_steps=True
        )
        result = agent(formatted_script_template)
        intermediate_steps = result['intermediate_steps']
        scratchpad = agent.agent._construct_scratchpad(result['intermediate_steps'])
        final_outputs = agent.iter(agent).final_outputs
```

**Comment by jiangcheng1214** [comment]
@dosu-bot
Unfortunately, `intermediate_steps[-1]` gives me the second to the last iteration result.
In other words, intermediate_steps didn't catch the all last iteration result but everything before that.

**Comment by lruppe** [comment]
hi @jiangcheng1214 did you find any solution to this?
