### ISSUE TITLE
ImportError of lark when packaging a standalone application with PyInstaller

### ISSUE THREAD

**Issue by Mazzesy** [langchain-ai/langchain#9264]
### System Info

When attempting to package my application using PyInstaller, I encounter an error related to the "lark" library. When trying to initiate the SelfQueryRetriever from langchain, I encounter the following problem:

> Traceback (most recent call last):
> File "test.py", line 39, in
> File "langchain\retrievers\self_query\base.py", line 144, in from_llm
> File "langchain\chains\query_constructor\base.py", line 154, in load_query_constructor_chain
> File "langchain\chains\query_constructor\base.py", line 115, in _get_prompt
> File "langchain\chains\query_constructor\base.py", line 72, in from_components
> File "langchain\chains\query_constructor\parser.py", line 150, in get_parser
> ImportError: Cannot import lark, please install it with 'pip install lark'.

I use:
- Langchain 0.0.233
- Lark 1.1.7
- PyInstaller 5.10.1
- Python 3.9.13
- OS  Windows-10-10.0.22621-SP0

I have already ensured that the "lark" library is installed using the appropriate command: pip install lark.

I have also tried to add a hook-lark.py file to the PyInstaller as suggested [here](https://github.com/lark-parser/lark/issues/548.) and also opened a issue in [Lark](https://github.com/lark-parser/lark/issues/1319).

Can you help? Thanks in advance!

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

With the following code the problem can be reproduced:

```
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.retrievers import SelfQueryRetriever
from langchain.llms import OpenAI
from langchain.chains.query_constructor.base import AttributeInfo

embeddings = OpenAIEmbeddings()

persist_directory = "data"
text= ["test"]

chunk_size = 1000
chunk_overlap = 10
r_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap,
                                            separators=["\n\n", "(?<=\. )", "\n"])
docs = r_splitter.create_documents(text)

for doc in docs:
    doc.metadata = {"document": "test"}

db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory=persist_directory)

db.persist()

metadata_field_info = [
                AttributeInfo(
                    name="document",
                    description="The name of the document the chunk is from.",
                    type="string",
                ),
            ]

document_content_description = "Test document"

llm = OpenAI(temperature=0)
retriever = SelfQueryRetriever.from_llm(
    llm,
    db,
    document_content_description,
    metadata_field_info,
    verbose=True
)
```
The spec-file to create the standalone application looks like this:

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['tiktoken_ext', 'tiktoken_ext.openai_public', 'onnxruntime', 'chromadb', 'chromadb.telemetry.posthog', 'chromadb.api.local', 'chromadb.db.duckdb'],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

a.datas += Tree('path\to\langchain', prefix='langchain')

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='test',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

### Expected behavior

The SelfQueryRetriever should be initiated properly for futher use.

**Comment by Mazzesy** [comment]
@dosu-bot
I will gladly answer the questions:

1. The library is installed in the same Pyhton environment
2. The content of the hook-file is:
```
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('lark')
```
3. The error does not occur when packaging a minimal Python script that only imports and uses lark.
4. The full command to run PyInstaller is `py -m PyInstaller main.spec`. The content of the main.spec file is described in the problem description.

**Comment by Mazzesy** [comment]
@dosu-bot
The answer to your questions are:

1. the exact code to initiate the retriever is:

```
retriever = SelfQueryRetriever.from_llm(
    llm,
    db,
    document_content_description,
    metadata_field_info,
    verbose=True
)
```
2.  The content of the `main.spec` file is:

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['tiktoken_ext', 'tiktoken_ext.openai_public', 'onnxruntime', 'chromadb', 'chromadb.telemetry.posthog', 'chromadb.api.local', 'chromadb.db.duckdb'],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

a.datas += Tree('path\to\langchain', prefix='langchain')

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='test',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```
3. I could not find a warning related to the issue. However, the `hook-lark.py` file is loaded as stated during packaging `Loading module hook 'hook-lark.py' from 'C:\\Users\\user\\PycharmProjects\\test'`.
4. The steps I take are: I open the terminal and navigate to the folder where the `main.spec` file and `main.py` file are, there I run the command `py -m PyInstaller main.spec`. From the resulting dist folder I start the exe file.

**Comment by Mazzesy** [comment]
@dosu-bot
I tried your suggestions but unfortunately the error persists.

**Comment by Mazzesy** [comment]
Adding `lark` in the `hiddenimports` solve the issue. The path to the `hook-lark.py` is defined in the `spec` file option `hookspath`, but the `ImportError` persists.

The exact traceback of the error is:

> Traceback (most recent call last):
> File "test.py", line 39, in
> File "langchain\retrievers\self_query\base.py", line 144, in from_llm
> File "langchain\chains\query_constructor\base.py", line 154, in load_query_constructor_chain
> File "langchain\chains\query_constructor\base.py", line 115, in _get_prompt
> File "langchain\chains\query_constructor\base.py", line 72, in from_components
> File "langchain\chains\query_constructor\parser.py", line 150, in get_parser
> ImportError: Cannot import lark, please install it with 'pip install lark'.

The code example, where the error occurs is:
```
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.retrievers import SelfQueryRetriever
from langchain.llms import OpenAI
from langchain.chains.query_constructor.base import AttributeInfo

embeddings = OpenAIEmbeddings()

persist_directory = "data"
text= ["test"]

chunk_size = 1000
chunk_overlap = 10
r_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap,
                                            separators=["\n\n", "(?<=\. )", "\n"])
docs = r_splitter.create_documents(text)

for doc in docs:
    doc.metadata = {"document": "test"}

db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory=persist_directory)

db.persist()

metadata_field_info = [
                AttributeInfo(
                    name="document",
                    description="The name of the document the chunk is from.",
                    type="string",
                ),
            ]

document_content_description = "Test document"

llm = OpenAI(temperature=0)
retriever = SelfQueryRetriever.from_llm(
    llm,
    db,
    document_content_description,
    metadata_field_info,
    verbose=True
)
```

**Comment by Mazzesy** [comment]
@dosu-bot
Adding `lark` in the `hiddenimports` did not solve the issue. The path to the `hook-lark.py` is defined in the `spec` file option `hookspath`, but the `ImportError` persists.

The exact traceback of the error is:

> Traceback (most recent call last):
> File "test.py", line 39, in
> File "langchain\retrievers\self_query\base.py", line 144, in from_llm
> File "langchain\chains\query_constructor\base.py", line 154, in load_query_constructor_chain
> File "langchain\chains\query_constructor\base.py", line 115, in _get_prompt
> File "langchain\chains\query_constructor\base.py", line 72, in from_components
> File "langchain\chains\query_constructor\parser.py", line 150, in get_parser
> ImportError: Cannot import lark, please install it with 'pip install lark'.

The code example, where the error occurs is:
```
from langchain.embeddings import OpenAIEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import Chroma
from langchain.retrievers import SelfQueryRetriever
from langchain.llms import OpenAI
from langchain.chains.query_constructor.base import AttributeInfo

embeddings = OpenAIEmbeddings()

persist_directory = "data"
text= ["test"]

chunk_size = 1000
chunk_overlap = 10
r_splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap,
                                            separators=["\n\n", "(?<=\. )", "\n"])
docs = r_splitter.create_documents(text)

for doc in docs:
    doc.metadata = {"document": "test"}

db = Chroma.from_documents(documents=docs, embedding=embeddings, persist_directory=persist_directory)

db.persist()

metadata_field_info = [
                AttributeInfo(
                    name="document",
                    description="The name of the document the chunk is from.",
                    type="string",
                ),
            ]

document_content_description = "Test document"

llm = OpenAI(temperature=0)
retriever = SelfQueryRetriever.from_llm(
    llm,
    db,
    document_content_description,
    metadata_field_info,
    verbose=True
)
```

**Comment by Mazzesy** [comment]
@dosu-bot
The issue persists. The exact version of `lark` is `1.1.7`

**Comment by eynomr** [comment]
Im having the same issue.

**Comment by ingridstevens** [comment]
**I had this issue and solved it following the steps:**
1. Install lark `pip install lark` (I have installed version `1.1.7`)
2. Install lark parser `pip install lark-parser` (I have installed `0.12.0`)
3. Restart Jupyter notebook instance after both installations



**For context, I was running the following code:**

```
retriever = SelfQueryRetriever.from_llm(
    llm,
    vectordb,
    document_content_description,
    metadata_field_info,
    verbose=True,
)
```

which generated the following error message: 

```
ImportError                               Traceback (most recent call last)
Cell In[60], line 3
      1 document_content_description = "Lecture notes"
      2 llm = OpenAI(temperature=0)
----> 3 retriever = SelfQueryRetriever.from_llm(
      4     llm,
      5     vectordb,
      6     document_content_description,
      7     metadata_field_info,
      8     verbose=True,
      9 )

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/langchain/retrievers/self_query/base.py:166, in SelfQueryRetriever.from_llm(cls, llm, vectorstore, document_contents, metadata_field_info, structured_query_translator, chain_kwargs, enable_limit, use_original_query, **kwargs)
    162 if "allowed_operators" not in chain_kwargs:
    163     chain_kwargs[
    164         "allowed_operators"
    165     ] = structured_query_translator.allowed_operators
--> 166 llm_chain = load_query_constructor_chain(
    167     llm,
    168     document_contents,
    169     metadata_field_info,
    170     enable_limit=enable_limit,
    171     **chain_kwargs,
    172 )
...
    154     allowed_comparators=allowed_comparators, allowed_operators=allowed_operators
    155 )
    156 return Lark(GRAMMAR, parser="lalr", transformer=transformer, start="program")

ImportError: Cannot import lark, please install it with 'pip install lark'.
```

Thanks to [tsbertalan](https://github.com/tsbertalan) for this helpful [comment](https://github.com/lark-parser/lark/issues/577#issuecomment-655655324)

**Comment by Mazzesy** [comment]
The problem remains using 'PyInstaller'

**Comment by Mazzesy** [comment]
@dosu-bot with langchain version `0.1.15` I get a different error, as seen below, eventhough the `chromadb` is installed.
> Traceback (most recent call last):
>   File "langchain_community\vectorstores\chroma.py", line 81, in __init__
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "chromadb\__init__.py", line 5, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "chromadb\auth\token\__init__.py", line 26, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "chromadb\telemetry\opentelemetry\__init__.py", line 6, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
>   File "opentelemetry\sdk\resources\__init__.py", line 144, in <module>
>   File "importlib_metadata\__init__.py", line 909, in version
>   File "importlib_metadata\__init__.py", line 882, in distribution
>   File "importlib_metadata\__init__.py", line 410, in from_name
> importlib_metadata.PackageNotFoundError: No package metadata was found for opentelemetry-sdk
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test2.py", line 25, in <module>
>   File "langchain_community\vectorstores\chroma.py", line 778, in from_documents
>   File "langchain_community\vectorstores\chroma.py", line 714, in from_texts
>   File "langchain_community\vectorstores\chroma.py", line 84, in __init__
> ImportError: Could not import chromadb python package. Please install it with `pip install chromadb`.
> [6724] Failed to execute script 'test2' due to unhandled exception!

**Comment by Soham-Kakade** [comment]
hey @Mazzesy 
did you find a way to a solution to include lark in pyinstaller yet ?

**Comment by Soham-Kakade** [comment]
no its not related to chromadb 
i just want to  my pyinstaller exe file to import lark correctly

**Comment by Mazzesy** [comment]
@Soham-Kakade 
when adding `a.datas += Tree('path\\to\\lark', prefix='lark')` to the spec file, the `lark` libary seems to be included correctly. But for me with the given script above, the problem with the `chromadb` remains, eventhough it is included in the packed folder.

@dosubot
I tried your suggestions, but the problem remains. My `spec`-file looks like this:
```
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['opentelemetry_sdk', 'chromadb.config', 'tiktoken_ext', 'tiktoken_ext.openai_public', 'onnxruntime', 'chromadb', 'chromadb.telemetry.posthog', 'chromadb.api.local', 'chromadb.db.duckdb'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

a.datas += Tree('path\\to\\langchain', prefix='langchain')
a.datas += Tree('path\\to\\chromadb', prefix='chromadb')
a.datas += Tree('path\\to\\lark', prefix='lark')

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='test',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='test',
)
```

**Comment by Soham-Kakade** [comment]
@Mazzesy 
My spec file looks like this:
`# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['UAT_SQL_Dependency_Removed.py'],
    pathex=[],
    binaries=[],
    datas=collect_data_files('lark'),
    hiddenimports=['lark'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/langchain', prefix='langchain')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/pinecone', prefix='pinecone')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/lark', prefix='lark')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/tiktoken', prefix='tiktoken')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/torch', prefix='torch')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/txtai', prefix='txtai')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/win32com', prefix='win32com')
a.datas += Tree('D:/Anaconda-python/envs/depe/Lib/site-packages/sqlalchemy', prefix='sqlalchemy')

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='UAT_SQL_Dependency_Removed',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
`
And i m getting the error saying:

`Traceback (most recent call last):
 
File "UAT SQL [Dependency_Removed.py](http://dependency_removed.py/)", line 184, in <module>
 
retriever SelfQueryRetriever.from_lla(
 
File "langchain\retrievers\self_query [base.py](http://base.py/)", line 225, in from la File "langchain\chains\query_constructor\[base.py](http://base.py/)", line 357, in load query_constructor_runnable
 
File "langchain\chains\query_constructor\[base.py](http://base.py/)", line 99, in from_components File "langchain\chains\query_constructor\[parser.py](http://parser.py/)", line 174, in get parser install lark'.
 
ImportError: it with 'pip Cannot import lark, please install [18828] Failed to execute script 'UAT SQL Dependency Removed' due to unhandled exception!`

Is this lark error or something else ?

**Comment by Mazzesy** [comment]
@Soham-Kakade 
The `ImportError` with `lark` occured for me, when using langchain`0.0.233`. With `0.1.15` I get the error with `chromdb`.

**Comment by Soham-Kakade** [comment]
I have langchain `0.0.303` and i m unable to install langchain `0.1.15 ` as the latest distribution is `0.1.11`

**Comment by lawyinking** [comment]
tried all the methods and this works

1. %pip install --upgrade --quiet  lark chromadb
2. restart kernel

references:
https://python.langchain.com/docs/modules/data_connection/retrievers/self_query

**Comment by davidgao7** [comment]
> tried all the methods and this works
> 
> 1. %pip install --upgrade --quiet  lark chromadb
> 2. restart kernel
> 
> references: https://python.langchain.com/docs/modules/data_connection/retrievers/self_query

Hello everyone! Unfortunately I'm still having the same error after reinstalling and restarting kernel...

# Reproduction
With the following code the problem can be reproduced:

```python
!pip install --upgrade --quiet lark chromadb langchain
# Python 3.10.0
```

```bash
!pip list | grep -E 'lark|chroma|langchain|openai'

chroma-hnswlib                           0.7.3
chromadb                                 0.5.0
langchain                                0.0.27
lark                                     1.1.9
openai                                   1.23.6
```

```python
# vectorstores and embeddings
loaders = [
    loader, # road to react pdf loader
    PyPDFLoader('the-road-to-learn-react.pdf') # another react book, might have overlapped content, treat as dirty data
]
docs=[]
for l in loaders:
    docs.extend(l.load())

from langchain.text_splitter import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1500,
    chunk_overlap = 150
)
splits = text_splitter.split_documents(docs)

# create a directory to store
vectordb = Chroma.from_documents(
    documents=splits,
    embedding=embedding, # openai embeddings
    persist_directory='...' # some local location
)

document_content_description = "only from intro to react"
llm = OpenAI(temperature=0,openai_api_key=api_keys['OPENAI_API_KEY'])
retriever = SelfQueryRetriever.from_llm(
    llm,
    vectordb,
    document_content_description,
    metadata_field_info,
    verbose=True
)
```

<details>
<summary>The whole error message</summary>
<p>

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[46], line 3
      1 document_content_description = "only from intro to react"
      2 llm = OpenAI(temperature=0,openai_api_key=api_keys['OPENAI_API_KEY'])
----> 3 retriever = SelfQueryRetriever.from_llm(
      4     llm,
      5     vectordb,
      6     document_content_description,
      7     metadata_field_info,
      8     verbose=True
      9 )

File [~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/retrievers/self_query/base.py:240](http://localhost:8888/lab/tree/~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/retrievers/self_query/base.py#line=239), in SelfQueryRetriever.from_llm(cls, llm, vectorstore, document_contents, metadata_field_info, structured_query_translator, chain_kwargs, enable_limit, use_original_query, **kwargs)
    233 if (
    234     "allowed_operators" not in chain_kwargs
    235     and structured_query_translator.allowed_operators is not None
    236 ):
    237     chain_kwargs[
    238         "allowed_operators"
    239     ] = structured_query_translator.allowed_operators
--> 240 query_constructor = load_query_constructor_runnable(
    241     llm,
    242     document_contents,
    243     metadata_field_info,
    244     enable_limit=enable_limit,
    245     **chain_kwargs,
    246 )
    247 return cls(
    248     query_constructor=query_constructor,
    249     vectorstore=vectorstore,
   (...)
    252     **kwargs,
    253 )

File [~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/base.py:358](http://localhost:8888/lab/tree/~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/base.py#line=357), in load_query_constructor_runnable(llm, document_contents, attribute_info, examples, allowed_comparators, allowed_operators, enable_limit, schema_prompt, fix_invalid, **kwargs)
    354 for ainfo in attribute_info:
    355     allowed_attributes.append(
    356         ainfo.name if isinstance(ainfo, AttributeInfo) else ainfo["name"]
    357     )
--> 358 output_parser = StructuredQueryOutputParser.from_components(
    359     allowed_comparators=allowed_comparators,
    360     allowed_operators=allowed_operators,
    361     allowed_attributes=allowed_attributes,
    362     fix_invalid=fix_invalid,
    363 )
    364 return prompt | llm | output_parser

File [~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/base.py:99](http://localhost:8888/lab/tree/~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/base.py#line=98), in StructuredQueryOutputParser.from_components(cls, allowed_comparators, allowed_operators, allowed_attributes, fix_invalid)
     96         return fixed
     98 else:
---> 99     ast_parse = get_parser(
    100         allowed_comparators=allowed_comparators,
    101         allowed_operators=allowed_operators,
    102         allowed_attributes=allowed_attributes,
    103     ).parse
    104 return cls(ast_parse=ast_parse)

File [~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/parser.py:174](http://localhost:8888/lab/tree/~/anaconda3/envs/llmstreamlit/lib/python3.10/site-packages/langchain/chains/query_constructor/parser.py#line=173), in get_parser(allowed_comparators, allowed_operators, allowed_attributes)
    172 # QueryTransformer is None when Lark cannot be imported.
    173 if QueryTransformer is None:
--> 174     raise ImportError(
    175         "Cannot import lark, please install it with 'pip install lark'."
    176     )
    177 transformer = QueryTransformer(
    178     allowed_comparators=allowed_comparators,
    179     allowed_operators=allowed_operators,
    180     allowed_attributes=allowed_attributes,
    181 )
    182 return Lark(GRAMMAR, parser="lalr", transformer=transformer, start="program")

ImportError: Cannot import lark, please install it with 'pip install lark'.
```

</p>
</details>
