### ISSUE TITLE
How do fix GPT2 Tokenizer error in Langchain map_reduce (LLama2)?

### ISSUE THREAD

**Issue by dm-2111** [langchain-ai/langchain#9273]
### System Info

I'm using AWS Sagemaker Jumpstart model for Llama2 13b: meta-textgeneration-llama-2-13b-f

On running a Langchain summarize chain with chain_type="map_reduce" I get the below error. Other chain types (refine, stuff) work without issues. I do not have access to https://huggingface.co/ from my environment. Is there a way to set the gpt2 tokenizer in a local dir?

```
parameters = {
        "properties": {
            "min_length": 100,
            "max_length": 1024,
            "do_sample": True,
            "top_p": 0.9,
            "repetition_penalty": 1.03,
            "temperature": 0.8
        }
    }

class ContentHandler(LLMContentHandler):
    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt: str, model_kwargs: Dict) -> bytes:
        input_str = json.dumps({"inputs": prompt, **model_kwargs})
        print(input_str)
        return input_str.encode("utf-8")

    def transform_output(self, output: bytes) -> str:
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json[0]["generation"]["content"]

content_handler = ContentHandler()

endpoint_name='xxxxxxxxxxxxxxxxxx'

llm=SagemakerEndpoint(
        endpoint_name=endpoint_name,
        region_name="us-east-1",
        model_kwargs=parameters,
        content_handler=content_handler,
        endpoint_kwargs={"CustomAttributes": 'accept_eula=true'}
)

chain = load_summarize_chain(llm, chain_type="map_reduce")
chain.run(docs)
```

Error:

```
File /usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1788, in PreTrainedTokenizerBase.from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1782     logger.info(
   1783         f"Can't load following files from cache: {unresolved_files} and cannot check if these "
   1784         "files are necessary for the tokenizer to operate."
   1785     )
   1787 if all(full_file_name is None for full_file_name in resolved_vocab_files.values()):
-> 1788     raise EnvironmentError(
   1789         f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
   1790         "'https://huggingface.co/models', make sure you don't have a local directory with the same name. "
   1791         f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct path to a directory "
   1792         f"containing all relevant files for a {cls.__name__} tokenizer."
   1793     )
   1795 for file_id, file_path in vocab_files.items():
   1796     if file_id not in resolved_vocab_files:

OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Provided above

### Expected behavior

Provided above

**Comment by dm-2111** [comment]
I'm using the Llama2 jumpstart model in sagemaker (model name: Llama-2-13b-chat | model_id: meta-textgeneration-llama-2-13b-f) setup as an inference endpoint.

Outside on the sagemaker environment, I'm running my langchain summarize chain with map_reduce.

```
llm=SagemakerEndpoint(
        endpoint_name=endpoint_name,
        region_name="us-east-1",
        model_kwargs=parameters,
        content_handler=content_handler,
        endpoint_kwargs={"CustomAttributes": 'accept_eula=true'}
)
```

I dont have access to openai or huggingface in my environment. I do have the gpt2 model downloaded locally. How do I supply this parameter to the map_reduce function thats throwing the error?

**Comment by luzhouuu** [comment]
Hi @dm-2111 
I encountered a similar issue as you did, where my environment couldn't access the internet, which prevented me from loading GPT-2. Have you managed to resolve this problem？
Thank you very much!

**Comment by analyticsinsights** [comment]
> _🤖_
> 
> Hello,
> 
> Based on the information you've provided and the context from the LangChain repository, it seems like you're trying to use a locally downloaded GPT2 model with the LangChain's map_reduce function.
> 
> Currently, the LangChain framework does not directly support the use of locally downloaded models in its map_reduce function. The map_reduce function in LangChain is designed to work with language models that are hosted on a server and accessed via an API endpoint, such as the AWS Sagemaker endpoint you're using.
> 
> However, you can modify the LangChain code to support locally downloaded models. Here's a rough idea of how you can do this:
> 
> 1. Create a new class that inherits from the `LLM` base class in LangChain. This new class should override the `__call__` method to use your locally downloaded GPT2 model instead of making a request to an API endpoint.
> 
> ```python
> from langchain.llms import LLM
> 
> class LocalGPT2(LLM):
>     def __init__(self, model_path, **kwargs):
>         super().__init__(**kwargs)
>         self.model = GPT2Model.from_pretrained(model_path)
> 
>     def __call__(self, text, **kwargs):
>         # Use your GPT2 model to generate a response
>         response = self.model.generate(text, **kwargs)
>         return response
> ```
> 
> 2. Use this new `LocalGPT2` class when creating your `chain` object:
> 
> ```python
> llm = LocalGPT2(model_path="/path/to/your/model/gpt2-model.bin")
> chain = load_summarize_chain(llm, chain_type="map_reduce")
> chain.run(docs)
> ```
> 
> Please note that this is a rough idea and you might need to adjust the code to fit your specific needs. Also, this approach requires a good understanding of the LangChain codebase and the workings of the GPT2 model.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> ## Sources
> * [libs/langchain/langchain/llms/gpt4all.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/llms/gpt4all.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

This answer appears to be wrong. 

First, it should be `from langchain.llms.base import LLM` instead of `from langchain.llms import LLM`. 

Second, running this suggested solution creates an error: 'TypeError: Can't instantiate abstract class LocalGPT2 with abstract methods _call, _llm_type'.

Please provide a working solution for using a local version of the GPT2-model instead of attempting to download it from the internet, in cases when an internet connection is not available.
