### ISSUE TITLE
Issue: `ApifyWrapper` was removed from the codebase breaking user's code

### ISSUE THREAD

**Issue by jirimoravcik** [langchain-ai/langchain#9294]
### Issue you'd like to raise.

In LangChain 0.0.240, the `ApifyWrapper` class was removed. This caused a breaking change and broke any code using this class.

It was deleted in this PR https://github.com/langchain-ai/langchain/pull/8106 @hwchase17 

Could you please outline the reason it was removed?

Other issues related to this one: https://github.com/langchain-ai/langchain/issues/8201 and https://github.com/langchain-ai/langchain/issues/8307

### Suggestion:

I'd suggest adding the integration back so that code written using it will continue to work.

I'm offering to take ownership of the Apify-related code, so if any issue arises, you can just tag me and I'll resolve it.

**Comment by jirimoravcik** [comment]
Could you please take a look at this @hwchase17 ? Thanks!

**Comment by baskaryan** [comment]
landed fix in #10067, thanks @jirimoravcik!
