### ISSUE TITLE
Issue: embedding rate limit error

### ISSUE THREAD

**Issue by Zzz233** [langchain-ai/langchain#9298]
### Issue you'd like to raise.

Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: Rate limit reached for default-text-embedding-ada-002 in organization org-uIkxFSWUeCDpCsfzD5XWYLZ7 on tokens per min. Limit: 1000000 / min. Current: 837303 / min. Contact us through our help center at help.openai.com if you continue to have issues..

how can i fix this?

**Comment by adumont** [comment]
I'm also hitting this rate limit, and unfortunately the min_seconds/max_seconds from the decorators are too deep into the openai.py file and not modifiable by the user and are not exposed as parameters that a user could pass to the OpenAIEmbeddings constructor.

I'd suggest for example adding a couple of new arguments to OpenAIEmbeddings  (min_seconds = 4, max_seconds = 10), and change both the decorator _create_retry_decorator and _async_retry_decorator to use the embeddings.min_seconds  and embeddings.max_seconds  instead.

I think I could add this to the code myself, but I don't know how to test a local version of modified "langchain" code and import it as a module to test.

**Comment by krrishdholakia** [comment]
Hey @adumont @Zzz233  I'm the maintainer of [LiteLLM](https://docs.litellm.ai/docs/routing) we allow you to create a Router to maximize throughput by load balancing + queuing (beta). 

I'd love to get your feedback if this solves your issue

Here's the quick start
```python
from litellm import Router

model_list = [{ # list of model deployments 
    "model_name": "gpt-3.5-turbo", # model alias 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-v-2", # actual model name
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-functioncalling", 
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "gpt-3.5-turbo", 
        "api_key": os.getenv("OPENAI_API_KEY"),
    }
}]

router = Router(model_list=model_list)

# openai.ChatCompletion.create replacement
response = await router.acompletion(model="gpt-3.5-turbo", 
                messages=[{"role": "user", "content": "Hey, how's it going?"}])

print(response)
```

P.S: also langchain compatible - https://python.langchain.com/docs/integrations/chat/litellm

**Comment by adumont** [comment]
Hum, interesting, does the Router also works for embedding models , and
does it support openai 1.x?
--
Alex

**Comment by krrishdholakia** [comment]
@adumont yep - we're openai 1.x compatible. (Any litellm version > 1.x is).
