### ISSUE TITLE
other llm api

### ISSUE THREAD

**Issue by doudou-itachi** [langchain-ai/langchain#9299]
### Issue you'd like to raise.

Hello, I have a question, I didn't find it from the official documentation, I want to know, if I have another llm now, he provides me with a calling api, how can I do it, can it be used like openai, such as This https://python.langchain.com/docs/use_cases/sql in the official document, I want to replace openai with my API provided by others, what should I do?

**Comment by abdulhaseebmir** [comment]
This might be useful: https://python.langchain.com/docs/guides/local_llms

**Comment by doudou-itachi** [comment]
I read this information, and there is another one that provides the address of the api. My idea is to call a similar openai api instead of using the openai module call, but I thought about inheriting the LLM class from a custom class like Chatglm and rewriting  _ call() method
