### ISSUE TITLE
better explain in docs that langchain is independent from LLMs providers

### ISSUE THREAD

**Issue by solyarisoftware** [langchain-ai/langchain#930]
> suggested label: documentation imporvement

One of the langchain strong points is its independence "by design" from any LLM provider. 
IMMO this is not fully clear in the current documentation. By example, the [getting started page](https://langchain.readthedocs.io/en/latest/modules/llms/getting_started.html#) start to mention Openai:

```python
from langchain.llms import OpenAI
```

The fact langchain can currently operate not just with openai models is described in the [integrations](https://langchain.readthedocs.io/en/latest/modules/llms/integrations.html) page. That's fine, but I'd point out at first (maybe in the initial [llm](https://langchain.readthedocs.io/en/latest/modules/llms.html) page), this foundamental feature.

**Comment by mukut03** [comment]
hi I updated the documentation to reflect this change
