### ISSUE TITLE
RecursiveCharacterTextSplitter splits even if text is smaller than chunk size

### ISSUE THREAD

**Issue by Leon-Sander** [langchain-ai/langchain#9305]
### System Info

Python 3.10.12
Langchain  0.0.266

### Who can help?

@eyurtsev

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Import any loader or just directly use the RecursiveCharacterTextSplitter

define chunk size to lets say 3950 

Get a text that is way smaller, for example 1k tokens.

run the text splitter and recieve multiple documents.

```
from langchain.text_splitter import SentenceTransformersTokenTextSplitter
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders.youtube import YoutubeLoader

def get_token_count(text):
    splitter = SentenceTransformersTokenTextSplitter(chunk_overlap=0)
    text_token_count = splitter.count_tokens(text=text.replace("\n"," "))
    return text_token_count

text_splitter = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", " "], chunk_size=3950, chunk_overlap=100)

def summarize_youtube_video(youtube_url: str) -> str:
    """
    Useful to get the summary of a youtube video. Applies if the user sends a youtube link.
    """
    id_input = youtube_url.split("=")[1]
    splitter = text_splitter
    loader = YoutubeLoader(id_input)
    docs = loader.load_and_split(splitter)
    return docs

docs = summarize_youtube_video("https://www.youtube.com/watch?v=vXIkc40UiH0")

for item in docs:
    print(get_token_count(item.page_content))
```

![screenshot_20230816135005](https://github.com/langchain-ai/langchain/assets/72946124/249cccf3-1209-4929-b62d-cf8acaed4ff8)

### Expected behavior

If the text is smaller than the chunk size, only one document should get returned.

**Comment by pi-curst** [comment]
@Leon-Sander 

`[RecursiveCharacterTextSplitter](https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter)` splits by **number of characters** not number of tokens. 
In the example you shared, the document has 1103 tokens and 5424 characters. Which when `RecursiveCharacterTextSplitter` is used, it is split into 797 tokens (3909 characters) and 325 tokens (1605 characters)

**Comment by Leon-Sander** [comment]
Yes you're right I didn't see that at first.
It seems to work now.
