### ISSUE TITLE
Is there any option to store direct text to VectorDB to get faster response? 

### ISSUE THREAD

**Issue by nithinreddyyyyyy** [langchain-ai/langchain#9324]
### Issue with current documentation:

Instead of embeddings, I'm using chat models with RecursiveTextSplitter because they simply return the response without any further justification. The input PDF files that I'm providing have a 36k input length. It takes a long time to return the output when using straight code. Can we store the direct text in any vector database and use it to get faster response?

Note: I'm not talking about embeddings, i'm trying to use direct chat models from OpenAI

Below is the code which i'm using

```
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from dotenv import load_dotenv
from pytesseract import image_to_string
from langchain.text_splitter import RecursiveCharacterTextSplitter, Document
from PIL import Image
from io import BytesIO
import pypdfium2 as pdfium
import pandas as pd
import pytesseract
import json
import os
import requests

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

load_dotenv()
os.environ["OPENAI_API_KEY"] = "sk-H......."


class DocumentProcessor:
    def __init__(self):
        self.llm = ChatOpenAI(temperature=0, model="gpt-3.5-turbo-0613")

    def convert_pdf_to_images(self, file_path, scale=300 / 72):
        pdf_file = pdfium.PdfDocument(file_path)
        page_indices = [i for i in range(len(pdf_file))]
        renderer = pdf_file.render(
            pdfium.PdfBitmap.to_pil,
            page_indices=page_indices,
            scale=scale,
        )
        final_images = []
        for i, image in zip(page_indices, renderer):
            image_byte_array = BytesIO()
            image.save(image_byte_array, format='jpeg', optimize=True)
            image_byte_array = image_byte_array.getvalue()
            final_images.append(dict({i: image_byte_array}))
        return final_images

    def extract_text_from_img(self, list_dict_final_images):
        image_list = [list(data.values())[0] for data in list_dict_final_images]
        image_content = []
        for index, image_bytes in enumerate(image_list):
            image = Image.open(BytesIO(image_bytes))
            raw_text = str(image_to_string(image))
            image_content.append(raw_text)
        return "\\n".join(image_content)

    def extract_content_from_url(self, url):
        images_list = self.convert_pdf_to_images(url)
        text_with_pytesseract = self.extract_text_from_img(images_list)
        return text_with_pytesseract

    def extract_structured_data(self, content):
        template = """
        You are an expert admin people who will extract core information from documents

        {content}

        Above is the content; please try to return the abstract and extractive summary

        """
        prompt = PromptTemplate(
            input_variables=["content"],
            template=template,
        )
        chain = LLMChain(llm=self.llm, prompt=prompt)

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1024,  # Maximum size of chunks to return
            chunk_overlap=50,  # Overlap in tokens between chunks
        )

        # Create a Document object for each document
        documents = [Document(page_content=text) for text in content]

        # Split the documents into chunks
        chunks = text_splitter.split_documents(documents)

        results = [chain.run(content=chunk) for chunk in chunks]

        print(results)
        return results

    def process_documents(self, file_paths):
        results = []
        for file_path in file_paths:
            content = self.extract_content_from_url(file_path)
            data = self.extract_structured_data(content)
            if isinstance(data, list):
                results.extend(data)
            else:
                results.append(data)
        return results


# Example usage
if __name__ == '__main__':
    document_processor = DocumentProcessor()
    uploaded_files_paths = [r'Questionnaire_2021 (1).pdf']
    processed_results = document_processor.process_documents(uploaded_files_paths)
    if len(processed_results) > 0:
        try:
            df = pd.DataFrame(processed_results)
            print("Results:")
            df.to_excel('output.xlsx', index=False)
            print(df)
        except Exception as e:
            print(f"An error occurred while creating the DataFrame: {e}")
```

Can anyone please help me with this?

**Comment by nithinreddyyyyyy** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for reaching out with your question. Yes, there is a way to store the direct text from PDF files in a vector database to improve the response time when using the ChatOpenAI model in the LangChain framework. You can use the `add_texts` method of the `Meilisearch` class to add the text data to the vector store.
> 
> Here is an example of how you can do it:
> 
> ```python
> from langchain.vectorstores import Meilisearch
> from langchain.embeddings.openai import OpenAIEmbeddings
> from langchain.documents import Document
> from langchain.document_loaders.pdf import PyPDFLoader
> import meilisearch
> 
> # Assuming you have a list of PDF files
> pdf_files = ["file1.pdf", "file2.pdf", ...]
> 
> # Create a PDF loader
> pdf_loader = PyPDFLoader()
> 
> # Load the documents from the PDF files
> pdf_documents = [pdf_loader.load(file) for file in pdf_files]
> 
> # Create a Meilisearch client
> client = meilisearch.Client(url='http://127.0.0.1:7700', api_key='***')
> embeddings = OpenAIEmbeddings()
> vectorstore = Meilisearch(
>     embedding=embeddings,
>     client=client,
>     index_name='langchain_demo',
>     text_key='text')
> 
> # Extract the texts from the documents
> texts = [doc.page_content for doc in pdf_documents]
> # Add the texts to the vector store
> vectorstore.add_texts(texts)
> ```
> 
> In this example, `pdf_files` is a list of PDF files. The `PyPDFLoader` class from the `langchain.document_loaders.pdf` module is used to load the documents from the PDF files. The `Meilisearch` class is used to create a new vector store from the documents and their embeddings. The `OpenAIEmbeddings` class is used to generate the embeddings for the texts. The `client` is the Meilisearch client and `index_name` is the name of the index in the vector store where the texts and their embeddings will be stored.
> 
> Please note that this is just an example and you might need to adjust the code to fit your specific needs. Also, please make sure to replace the `***` with your actual Meilisearch API key.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [libs/langchain/langchain/vectorstores/pgvector.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/pgvector.py)
> * [libs/langchain/langchain/vectorstores/qdrant.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/qdrant.py)
> * [libs/langchain/langchain/document_loaders/**init**.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/document_loaders/__init__.py)
> * [libs/langchain/langchain/vectorstores/meilisearch.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/meilisearch.py)
> * [libs/langchain/langchain/vectorstores/**init**.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/__init__.py)
> * [libs/langchain/langchain/vectorstores/dashvector.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/dashvector.py)
> * [libs/langchain/langchain/vectorstores/lancedb.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/lancedb.py)
> * [libs/langchain/langchain/vectorstores/vectara.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/vectorstores/vectara.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I'm bit perplexed with the code you gave. You're adding the embeddings to the vector store using OpenAI embeddings, then how to use that in the Chat Model?

**Comment by nithinreddyyyyyy** [comment]
I'm bit perplexed with the code you gave. You're adding the embeddings to the vector store using OpenAI embeddings, then how to use that in the Chat Model and can we use any open source vector store like ChromaDB for this?

**Comment by nithinreddyyyyyy** [comment]
> With Redis you can store text and vectors in the same hash slot or JSON document. one call to search and retrieve.

Do you have reference code by any chance?

**Comment by adolkhan** [comment]
Hey @nithinreddyyyyyy! If plan to store only texts without embeddings you can try deeplake, it is very user friendly.

Can I get more context, how are you planning to do embedding search if you're not going to store embeddings? Just a pure key word based search?

**Comment by nithinreddyyyyyy** [comment]
Hey @adolkhan , thanks for the reply. For instance, I might give a PDF file with a 30k input length and ask for a summary of the entire file in response. In this case, Chat Models can only accept input lengths up to 16k. In order to do this, I must first open a certain pdf file, send the input to chat models, and then receive the response from the chat models (not OpenAI Embeddings). I need any vector store to store the data and directly utilize the raw text (Not the Embeddings)

**Comment by Spartee** [comment]
So here's a decent example

```python
import os
from typing import List, Tuple

import openai

openai.api_key = os.environ["OPENAI_API_KEY"]


from langchain.chains import RetrievalQA
from langchain.docstore.document import Document
from langchain.document_loaders import ArxivLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.llms import OpenAI
from langchain.llms.base import LLM
from langchain.prompts import PromptTemplate
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores.redis import Redis, RedisTag, RedisText

EMBEDDINGS = OpenAIEmbeddings()


def get_arxiv_docs(query, num_docs=10):
    loader = ArxivLoader(query, load_max_docs=num_docs, load_all_available_meta=True)
    raw_documents = loader.load()
    text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
    documents = text_splitter.split_documents(raw_documents)
    texts = [d.page_content for d in documents]
    metadatas = [d.metadata for d in documents]
    return texts, metadatas


def get_vectorstore(search_query, num_papers, redis_url="redis://localhost:6379"):
    texts, metadata = get_arxiv_docs(search_query, num_docs=num_papers)

    rds, keys = Redis.from_texts_return_keys(
        texts,
        EMBEDDINGS,
        metadatas=metadata,
        redis_url=redis_url,
        index_name="arxiv",
    )
    return rds


def run_search(
    search_query,
    content_query,
    num_papers=10,
    num_results=5,
) -> List[Tuple[Document, float]]:
    """Run a search on arxiv and then semantic search on the results


    Args:
        search_query (str): The query to search arxiv for
        content_query (str): The query to search the content of the papers for
        num_papers (int, optional): The number of papers to search. Defaults to 10.
        num_results (int, optional): The number of results to return. Defaults to 5.

    """

    # make filter
    has_cslg_category = RedisTag("categories") == "cs.LG"
    published_in_2023 = RedisText("published_first_time") % "202*"
    cslg_in_2023 = has_cslg_category & published_in_2023

    docs = rds.similarity_search_with_relevance_scores(
        content_query,
        k=num_results,
        filter=published_in_2023,
    )
    return docs


def get_llm() -> LLM:
    llm = OpenAI(model_name="text-davinci-003")
    return llm


def make_qna_chain(vector_db):
    """Create the QA chain."""

    # Define our prompt
    prompt_template = """Use the following pieces of context to answer the question at the end. If you don't know the answer, say that you don't know, don't try to make up an answer.

    This should be in the following format:

    Question: [question here]
    Answer: [answer here]

    Begin!

    Context:
    ---------
    {context}
    ---------
    Question: {question}
    Answer:"""

    prompt = PromptTemplate(
        template=prompt_template, input_variables=["context", "question"]
    )

    # Create retreival QnA Chain
    chain = RetrievalQA.from_chain_type(
        llm=get_llm(),
        chain_type="stuff",
        retriever=vector_db.as_retriever(distance_threshold=0.5),
        return_source_documents=True,
        chain_type_kwargs={"prompt": prompt},
    )
    return chain


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--search_query", type=str, default="Astrophysical Black Holes")
    parser.add_argument("--content_query", type=str, default="What is a black hole?")
    parser.add_argument("--num_papers", type=int, default=2)
    parser.add_argument("--num_results", type=int, default=2)
    parser.add_argument("--redis_url", type=str, default="redis://localhost:6379")
    args = parser.parse_args()
    """
    docs = run_search(
        args.search_query,
        args.content_query,
        num_papers=args.num_papers,
        num_results=args.num_results,
        redis_url=args.redis_url,
    ) """

    vector_db = get_vectorstore(
        args.search_query, args.num_papers, redis_url=args.redis_url
    )
    chain = make_qna_chain(vector_db)
    result = chain({"query": args.content_query})
    print(result["result"])
    for doc in result["source_documents"]:
        print(doc.metadata["Title"])
        print(doc.metadata["links"])
        print(doc.metadata["published_first_time"])

    """     print(len(docs))
    for out, score in docs:
        meta = out.metadata
        print("Title: ", meta["Title"])
        print("URL: ", meta["links"])
        print("Score: ", score)
        print("Published: ", meta["published_first_time"]) """

```

This one automatically creates the following metadata fields in Redis.


Index Information:
| Index Name   | Storage Type   | Prefixes      | Index Options   |   Indexing |
|--------------|----------------|---------------|-----------------|------------|
| arxiv        | HASH           | ['doc:arxiv'] | []              |          0 |
Index Fields:
| Name                 | Attribute            | Type   | Field Option   | Option Value   |
|----------------------|----------------------|--------|----------------|----------------|
| Published            | Published            | TEXT   | WEIGHT         | 1              |
| Title                | Title                | TEXT   | WEIGHT         | 1              |
| Authors              | Authors              | TEXT   | WEIGHT         | 1              |
| Summary              | Summary              | TEXT   | WEIGHT         | 1              |
| entry_id             | entry_id             | TEXT   | WEIGHT         | 1              |
| published_first_time | published_first_time | TEXT   | WEIGHT         | 1              |
| comment              | comment              | TEXT   | WEIGHT         | 1              |
| primary_category     | primary_category     | TEXT   | WEIGHT         | 1              |
| content              | content              | TEXT   | WEIGHT         | 1              |
| categories           | categories           | TAG    | SEPARATOR      | ,              |
| links                | links                | TAG    | SEPARATOR      | ,              |
| content_vector       | content_vector       | VECTOR |                |                |

You can then just pull the content field from the result object. Same query. super fast.
