### ISSUE TITLE
langchain-server script fails to run on new Docker install

### ISSUE THREAD

**Issue by craigdrayton** [langchain-ai/langchain#935]
In a freshly installed instance of Docker for Ubuntu (following the instructions at https://docs.docker.com/desktop/install/ubuntu/), the `langchain-server` script fails to run.

The reason is that `docker-compose` is not a valid command following this install process:
https://github.com/hwchase17/langchain/blob/afc7f1b892596bd0d4687e1d5882127026bad991/langchain/server.py#L9-L10

This change fixes the issue (while breaking the script for people using the `docker-compose` command):
```
def main() -> None:
    """Run the langchain server locally."""
    p = Path(__file__).absolute().parent / "docker-compose.yaml"
    subprocess.run(["docker", "compose", "-f", str(p), "pull"])
    subprocess.run(["docker", "compose", "-f", str(p), "up"])
```

**Comment by hwchase17** [comment]
flagging for @agola11 

fix would be... to detect os?

**Comment by agola11** [comment]
It's not an os problem, it seems. It's that `docker compose` (with space) is v2 of the tool and is rewritten in go. I think we should just tell people to use the latest version of Docker Desktop and use `docker compose`, maybe fall back to `docker-compose` if that fails

https://github.com/docker/compose/tree/v2#docker-compose-v2

**Comment by tensiondriven** [comment]
I run headless on an Ubuntu VM; unless Docker Desktop can be installed in this environment, I think I and others will have problems with this solution.

**Comment by franperezlopez** [comment]
I've got an ubuntu 20.04, download latest docker-compose from [github](https://github.com/docker/compose/releases/tag/v2.17.3) and it worked like a charm
