### ISSUE TITLE
why the  vector database  of vectorstores  must   load  document ？

### ISSUE THREAD

**Issue by pandab0y** [langchain-ai/langchain#9357]
### Issue with current documentation:

code 
-------------
raw_documents = TextLoader('../../../state_of_the_union.txt').load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(raw_documents)
db = Chroma.from_documents(documents, OpenAIEmbeddings())

query = "What did the president say about Ketanji Brown Jackson"
docs = await db.asimilarity_search(query)

--------------
"chroma" requires the input of a document when used. If I have existing data in my vector library and only need to retrieve data without uploading new ones, I cannot define a vectorDB.
 
myflow

query   ----->   embedding  ----->  vectorDB ----> llm  ----->  out  

the  vectorDB  existing data, don't nedd  load  document

how abount use  vectorstores ?

**Comment by adolkhan** [comment]
Hey @pandab0y! I am wondering have you tried using DeepLake? To load the already uploaded data you'll just need to do the following:

``` 
from langchain.vectorstore.deeplake import DeepLake

db = DeepLake(dataset_path="my_dataset_path", embedding=embedding)
```

This will load data that is stored in "my_dataset_path".

To upload data to DeepLake you can use exactly same syntax as for Chroma, but you'll need to change the actual class name from Chroma -> DeepLake

**Comment by pandab0y** [comment]
Thank you for the ideas you provided. I have rewritten the milvus class and added custom methods to address my needs, which only retrieves vectors from the library.
