### ISSUE TITLE
DOC: Where i can find Elasticsearch integration docs?

### ISSUE THREAD

**Issue by Zzz233** [langchain-ai/langchain#9363]
### Issue with current documentation:

`/usr/local/lib/python3.9/dist-packages/langchain/vectorstores/elastic_vector_search.py:135: UserWarning: ElasticVectorSearch will be removed in a future release. See Elasticsearch integration docs on how to upgrade.`

**Comment by joemcelroy** [comment]
hey @Zzz233,

Upgrade instructions:

https://python.langchain.com/docs/integrations/vectorstores/elasticsearch#im-using-elasticvectorsearch

Let me know if you need help, available on discord too.
