### ISSUE TITLE
Help: How to stop the chain if no chunks are retrieved?

### ISSUE THREAD

**Issue by sid8491** [langchain-ai/langchain#9364]
### Issue you'd like to raise.

I am using ConversationalRetrievalChain for RAG based chatbot and I am using custom retriever to get the relevant chunks.

```
custom_retriever = FilteredRetriever(
        vectorstore=vectorstore.as_retriever(search_kwargs={"k": 5, "filter": {}}, search_type="mmr"),
        category=sess_metadata["category"],
        product=sess_metadata["product"],
        service=sess_metadata["service"],
    )

qa_chain = ConversationalRetrievalChain.from_llm(
        llm=llm,
        retriever=custom_retriever,
        chain_type="stuff",
        combine_docs_chain_kwargs=QA_PROMPT,
        return_source_documents=True,
        verbose=True,
    )
    result = qa_chain({"question": translated_query, "chat_history": chat_history})
```

If no chunks are retrieved then I don't want the LLM to execute and just return a simple response to the customer. 
How can I do that?

**Comment by VijayRajIITP** [comment]
I have a question how does llm chain stops.What are the stoping criteria for llm chain.How does llm chains knows whent to stop 
.In coding where it is written.
