### ISSUE TITLE
Streaming with function calling feature

### ISSUE THREAD

**Issue by duy-nguyen-ts** [langchain-ai/langchain#9374]
### Issue you'd like to raise.

Hi everybody, I am using langchain and I want to use new feature "function_calling" of openai. Actually, my app worked when I add functions and function_call params into function apredict_message. But I want to use stream, currently when I add function_calling into my call (with stream = true), it does not work and worked when I remove function_calling. 
So I want to know that does langchain support function_calling + stream ?
Thanks all

**Comment by vangetpersona** [comment]
Hi there,
I got an issue when trying apply functional streaming. Here is my code for /api/chat and it work fine with text response. But when it return a function call showed by enable verbosem, the API return a blank page.
```ts
   const llm = new ChatOpenAI({
      modelName: 'gpt-4-0613',
      streaming: true,
      openAIApiKey: process.env.OPENAI_API_KEY as string,
      maxTokens: 2048,
      temperature: 0.2,
      presencePenalty: 0,
      verbose: true,
    }).bind({
      functions: [getWeather],
    })

    const vectorStore = await PineconeStore.fromExistingIndex(new OpenAIEmbeddings(), {
      pineconeIndex: pineconeIndex,
      filter: {
        personaId: { $eq: body.personaId },
      },
    })

    const retriever = vectorStore.asRetriever()

    const standaloneQuestionChain = RunnableSequence.from([
      {
        question: (input: ConversationalRetrievalQAChainInput) => input.question,
        chat_history: (input: ConversationalRetrievalQAChainInput) => formatVercelMessages(input.chat_history),
      },
      condenseQuestionPrompt,
      llm,
      new StringOutputParser(),
    ])

    const answerChain = RunnableSequence.from([
      {
        context: retriever.pipe(combineDocumentsFn),
        question: new RunnablePassthrough(),
      },
      answerPrompt,
      llm,
      new BytesOutputParser(),
    ])
    const conversationalRetrievalQAChain = standaloneQuestionChain.pipe(answerChain)

    const stream = await conversationalRetrievalQAChain.stream({
      question: currentMessageContent,
      chat_history: previousMessages,
    })


    return new StreamingTextResponse(stream)

```
*Return a function call by LLM*
![image](https://github.com/langchain-ai/langchain/assets/144214304/c590dbfa-097b-442f-ad90-c5123b18afd8)
*API request information*
<img width="1201" alt="image" src="https://github.com/langchain-ai/langchain/assets/144214304/44ebfadb-eea0-437a-bfe5-11e2348fea76">
<img width="716" alt="image" src="https://github.com/langchain-ai/langchain/assets/144214304/dcc889ed-4b11-46c2-a74c-613081262377">
<img width="1203" alt="image" src="https://github.com/langchain-ai/langchain/assets/144214304/e5693163-bf2f-4451-9c5d-e6080d775c44">
<img width="1210" alt="image" src="https://github.com/langchain-ai/langchain/assets/144214304/a5234809-35ee-430a-9e2d-205c115a639e">
