### ISSUE TITLE
Fallbacks with LLMChain

### ISSUE THREAD

**Issue by EyeOfHorus396** [langchain-ai/langchain#9391]
### System Info

@hwchase17
@agola11 

Trying to implement https://python.langchain.com/docs/guides/fallbacks into our current environment that is using LLMChain, but when I pass in the fallback llm into the LLMChain, it throws the following error: 

`**ValidationError: 1 validation error for LLMChain**
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)`

Here is part of the code that I am trying to apply:

`
tools = [
        Tool(
            func=search.run, description=search_desc, name="Search_the_web"
        ),
]

conv0memory = ConversationBufferMemory(
        memory_key="chat_history_lines",
        return_messages=True,
        input_key="input",
        human_prefix="Human",
        ai_prefix="AI"
    )

openai_llm = ChatOpenAI(max_retries=0)
anthropic_llm = ChatAnthropic()
llm = openai_llm.with_fallbacks([anthropic_llm])

input_variables = ["input", "chat_history", "agent_scratchpad"]
prompt = ZeroShotAgent.create_prompt(
        tools,
        prefix=prefix,
        suffix=suffix,
        input_variables=input_variables
    )
    
    llm_chain = LLMChain(
        llm=llm, callbacks=[StreamingStdOutCallbackHandler()], prompt=prompt
    )
`

What must be done to pass the fallback LLM into LLMChain?

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

1. To reproduce the same output error, follow the steps indicated in https://python.langchain.com/docs/guides/fallbacks  to initiate the fallback
2. Pass the fallback LLM into LLMChain, where it usually passes the standard LLM methods i.e ChatModels, we add the fallback LLM to it instead. 
3. Use the code snippet provided in my ticket.

### Expected behavior

To have the fallback LLM work as per the documentation within LLMChain, whereas it fallback to the second LLM encase the API is busy, returns max token limit error, or to fall back for a better model to answer certain questions.

**Comment by cfurlong0018** [comment]
Is there an alternative? I think it's obvious we don't have access to update ChatOpenAI, and given it's likely one of the most used for LangChain, and that they're currently the most stringent with rate limiting, it seems like it'd be highly beneficial to outline a workable path forward.
