### ISSUE TITLE
ConversationalRetrievalChain doesn't work along with memory and return_source_documents

### ISSUE THREAD

**Issue by fcalabrow** [langchain-ai/langchain#9394]
### Issue you'd like to raise.

I'm trying to use a `ConversationalRetrievalChain` along with a `ConversationBufferMemory` and `return_source_documents` set to `True`. The problem is that, under this setting, I get an error when I call the overall chain.

```
from langchain.chains import ConversationalRetrievalChain

chain = ConversationalRetrievalChain(
    retriever=retriever,
    question_generator=question_generator,
    combine_docs_chain=doc_chain,
    memory = memory,
    return_source_documents=True,
)

query = 'dummy query'
chain({"question": query})
```
The error message says:
```
File [~/.local/share/virtualenvs/qa-8mHXn5ez/lib/python3.10/site-packages/langchain/chains/base.py:354](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/my_user/~/.local/share/virtualenvs/env-8mHXn5ez/lib/python3.10/site-packages/langchain/chains/base.py:354), in Chain.prep_outputs(self, inputs, outputs, return_only_outputs)
    352 self._validate_outputs(outputs)
    353 if self.memory is not None:
--> 354     self.memory.save_context(inputs, outputs)
...
---> 28         raise ValueError(f"One output key expected, got {outputs.keys()}")
     29     output_key = list(outputs.keys())[0]
     30 else:

ValueError: One output key expected, got dict_keys(['answer', 'source_documents'])
```
It works if I remove either the memory or the `return_source_documents` parameter.

So far, the only workaround that I found out is querying the chain using an external chat history, like this:

`chain({"question": query, "chat_history":"dummy chat history"})`

Thank you in advance for your help.

**Comment by hashim-ch** [comment]
Same issue, please help

**Comment by hashim-ch** [comment]
Nvm I found the fix, you need to define `output_key='answer'` inside `ConversationBufferMemory`

```
ConversationBufferMemory(memory_key="chat_history", output_key='answer', return_messages=True)
```

**Comment by fcalabrow** [comment]
> output_key='answer'

Great, now it's working. Thanks!

**Comment by nkityd09** [comment]
I tried this with output_key='answer but get the same error

    qa_chain = ConversationalRetrievalChain.from_llm(llm=llm, 
                                       chain_type="stuff", 
                                       retriever=set_retriver(retriever),
                                       memory=memory,
                                       output_key='answer',
                                       return_source_documents=True,
                                       verbose=True)

ValueError: One output key expected, got dict_keys(['answer', 'source_documents'])

When I try to remove the return_source_documents=True setting, the chain works but does not refer to the chat history when answering the follow up question.

Any insights or ETA for when this can be resolved ?

**Comment by qmaruf** [comment]
Same error for the following code

prompt
```
def get_prompt():    
    template = """Use the following pieces of context to answer the question at the end.
    ---
    CONTEXT: {context}
    QUESTION: {question}
    FINAL ANSWER: {answer}
    SOURCES: {sources}"""
    qa_prompt = PromptTemplate(
        template=template, input_variables=[
            'question', 'context', 'answer', 'sources'
        ],
    )
    return qa_prompt
```
memory
```
memory = ConversationBufferMemory(
        memory_key='chat_history', return_messages=True,
        input_key='question', output_key='answer'
    )
```
chain
```
model = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=retriever,
    memory=memory,
    return_source_documents=True,
    verbose=True,
    chain_type="stuff",
    output_key='answer',
    combine_docs_chain_kwargs={'prompt': prompt},  
)
```
error
```
An error occurred: Missing some input keys: {'sources', 'answer'}
```
