### ISSUE TITLE
SQLAlchemy Cache Issues

### ISSUE THREAD

**Issue by totalhack** [langchain-ai/langchain#940]
This is pretty simple to override but just giving you a heads up that the current sqlalchemy definition does not work with MySQL since it requires a length specified for varchar columns: `VARCHAR requires a length on dialect mysql`

```
class FullLLMCache(Base):  # type: ignore
    """SQLite table for full LLM Cache (all generations)."""

    __tablename__ = "full_llm_cache"
    prompt = Column(String, primary_key=True)
    llm = Column(String, primary_key=True)
    idx = Column(Integer, primary_key=True)
    response = Column(String)
```

It also failed with sqlalchemy < 1.4 due to a bad import btw, you may want to pin your requirements.

I'm also curious what the purpose of the `idx` column is. Seems to always be set to 0 when testing with the sqlite cache.

**Comment by hwchase17** [comment]
thanks for flagging - sqlalchmey should be fixed

idx column is used when multiple prompts are sent to api at once. in most cases, only one prompt is sent so will often be 0
