### ISSUE TITLE
while importing the llama_index occurred error that

### ISSUE THREAD

**Issue by Hiren838** [langchain-ai/langchain#9412]
---------------------------------------------------------------------------
from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext

--------------------------------------------------------------------------
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)

PydanticUserError                         Traceback (most recent call last)
[<ipython-input-15-2df7a532c2da>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
      2 from llama_index.llms import HuggingFaceLLM

6 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/deprecated/class_validators.py](https://localhost:8080/#) in root_validator(pre, skip_on_failure, allow_reuse, *__args)
    226     mode: Literal['before', 'after'] = 'before' if pre is True else 'after'
    227     if pre is False and skip_on_failure is not True:
--> 228         raise PydanticUserError(
    229             'If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`.'
    230             ' Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.',

PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.0/u/root-validator-pre-skip

**Comment by baskaryan** [comment]
what version of pydantic and langchain do you have? this is likely being caused by having pydantic >=2 with langchain <= 0.266

**Comment by Hiren838** [comment]
> what version of pydantic and langchain do you have? this is likely being caused by having pydantic >=2 with langchain <= 0.266

pydantic-core==2.6.0 right now this is version of pydantic

**Comment by baskaryan** [comment]
> > what version of pydantic and langchain do you have? this is likely being caused by having pydantic >=2 with langchain <= 0.266
> 
> pydantic-core==2.6.0 right now this is version of pydantic

guessing that's the issue. i would try bumping langchain to >=0.0.267, or pydantic<2
