### ISSUE TITLE
While using a GPT-4 deployed on AzureOpenAI, model name is showing as 'gpt-3.5-turbo', while the engine is showing as 'gpt-4'

### ISSUE THREAD

**Issue by AanchalA** [langchain-ai/langchain#9434]
### System Info

LangChain Version: 0.0.267

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`llm = AzureChatOpenAI(deployment_name='gpt-4', temperature=0.0)`

`llm.dict()`

`{'model': 'gpt-3.5-turbo',
 'request_timeout': None,
 'max_tokens': None,
 'stream': False,
 'n': 1,
 'temperature': 0.0,
 'engine': 'gpt-4',
 '_type': 'azure-openai-chat'}`

### Expected behavior

The model name and the engine should match.

**Comment by derekhsu** [comment]
I found this issue as well. 

I think the model should be taken from Azure OpenAI and it does in `azure_openai.py`, not specified by constructor, because the deployed model can be changed within the same deployment name.

Does anyone want to fix this?
