### ISSUE TITLE
Langsmith expose is not working Azure OpenAI services

### ISSUE THREAD

**Issue by mrcmoresi** [langchain-ai/langchain#9438]
### Issue you'd like to raise.

Hi everyone, I'm trying to deploy and use langsmith locally. 
I deployed in a docker container using
```
langsmith start --expose --openai-api-key=<my azure OpenAi key>
```
the docker container looks good
![image](https://github.com/langchain-ai/langchain/assets/12852824/28aae23a-0272-4f0f-b298-26e3e2223caa)
I opened all the used ports to avoid any problem there, I'm running langsmith in a remote computer

I set up the environment variables
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT=https://cc23-20-79-217-xxx.ngrok.io
LANGCHAIN_API_KEY=<my key>

but the interface is not loading the projects
![image](https://github.com/langchain-ai/langchain/assets/12852824/5ced7d99-bac3-4b1f-84f3-c606b98f5ee8)

when I try to access the langsmith endpoint it returns
```
{
"detail": "Not Found"
}
```

using the chat example that appears in this repo
https://github.com/langchain-ai/langsmith-cookbook/tree/main/feedback-examples/streamlit

I can see in the endpoint https://cc23-20-79-217-xxx.ngrok.io that the runs are being tracked, but I can't see them in the frontend 

**debugging the front end it is failing trying to fetch the tenants, it's trying to fetch them from http://127.0.0.1:1984/tenants while if I'm not understanding it wrong it should get them from http://20.79.217.xxx:1984/tenants**
![image](https://github.com/langchain-ai/langchain/assets/12852824/7bfb3c92-2db8-4ca9-8ecb-9f2d36500ffe)

could it be a problem with the Azure OpenAI? or did I do something wrong with the installation?

Thanks in advance

**Comment by sudevschiz** [comment]
Hi @mrcmoresi , I am facing the same issue while trying to host the application in a GCP VM. Were you able to fix this?

**Comment by mrcmoresi** [comment]
Hi @sudevschiz unfortunately I couldn't spend more time on it. in the following weeks I'll try to find a solution to this problem.
