### ISSUE TITLE
StructuredTool raises an error when instantiated

### ISSUE THREAD

**Issue by Markus-sevend** [langchain-ai/langchain#9441]
### Environment:
Google COLAB project. When running `!cat /etc/os-release` it prints:
```
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Python Environment
`!python -V`:
```
Python 3.10.12
```

`!pip show langchain`:
```
Name: langchain
Version: 0.0.267
Summary: Building applications with LLMs through composability
Home-page: https://www.github.com/hwchase17/langchain
Author: 
Author-email: 
License: MIT
Location: /usr/local/lib/python3.10/dist-packages
Requires: aiohttp, async-timeout, dataclasses-json, langsmith, numexpr, numpy, openapi-schema-pydantic, pydantic, PyYAML, requests, SQLAlchemy, tenacity
Required-by: 
```

### Who can help?

@hwchase17 

### Information

- [x] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Create a blank Google Colab Project (https://colab.research.google.com/#create=true) then add a code block and paste in this code:
```py
!pip install langchain==0.0.267
# or try just '!pip install langchain' without the explicit version

from pydantic import BaseModel, Field

class InputArgsSchema(BaseModel):
  strarg: str = Field(description="The string argument for this tool")

# THIS WORKS:

from typing import Type

class Foo(BaseModel):
  my_base_model_subclass: Type[BaseModel] = Field(..., description="Equivalent to the args_schema field in langchain/StructuredTool")

my_foo = Foo(
    my_base_model_subclass=InputArgsSchema
)

print(f"My foo {my_foo} is successfully instantiated")

# BUT THIS DOES NOT:

from langchain.tools import StructuredTool

def my_tool_impl(strarg: str):
  print(f"Called myTool with strarg={strarg}")

my_tool = StructuredTool(
    name="my_tool",
    description="A demo tool for testing purposes",
    args_schema=InputArgsSchema,
    func=my_tool_impl
)
```

Now run the code block.

### Expected behavior

The `StructuredTool` instance should be instantiated without an exception and the `InputArgsSchema` should be accepted as argument for `args_schema`.

**Comment by Markus-sevend** [comment]
Some updates on the topic:

The exact output and error message i get in the Colab environment (as suggested by @dosu-bot):
```
My foo my_base_model_subclass=<class '__main__.InputArgsSchema'> is successfully instantiated
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[<ipython-input-9-8e060e10267e>](https://localhost:8080/#) in <cell line: 28>()
     26   print(f"Called myTool with strarg={strarg}")
     27 
---> 28 my_tool = StructuredTool(
     29     name="my_tool",
     30     description="A demo tool for testing purposes",

[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for StructuredTool
args_schema
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

I can also reproduce this bug locally like so:
1. Setup a new blank venv and activate it
2. pip install langchain 0.0.267
3. remove the colab pip install statement from the code snippet (the "!pip install ...")
4. Run it

I debugged it locally and found that it seems like it is checking that `args_schema` is a subclass of the `BaseModel` in `.../site-packages/pydantic/v1/main.py` however my class inherits from the `BaseModel` in `.../site-packages/pydantic/main.py` (note the missing 'v1' sub-directory).

So to address the issue/bug again it should work with the `BaseModel` without the 'v1' part as this is the one thats imported when running `from pydantic import BaseModel`.

**Comment by Markus-sevend** [comment]
@dosu-bot I did provide the error message in my comment

**Comment by eyurtsev** [comment]
@Markus-sevend thanks for reporting the issue see:


* https://github.com/langchain-ai/langchain/discussions/9337 
* https://github.com/langchain-ai/langchain/blob/master/docs/extras/guides/pydantic_compatibility.md

**Comment by hminooei** [comment]
For me, installing pydantic 1.10.10 worked: `pip install pydantic==1.10.10`
