### ISSUE TITLE
Add some control over the summary length for summarize chains

### ISSUE THREAD

**Issue by shinglyu** [langchain-ai/langchain#9449]
### Feature request

For the chains in libs/langchain/langchain/chains/summarize, it might be useful to add to the prompt something like: 

"Try to limit the summary to {length} words", and set the length as an input parameter. So that we can have some influence over the length of the output summary.

I know that most LLMs are not good at counting words, maybe we should use token instead of words?

### Motivation

When doing summarization, we sometimes want summaries of different length. For example, we might fit the summary into some system with length limit, or sometimes we want a longer summary so we can include more details. 

### Your contribution

I can submit a pull request, but I'm not sure if people believe the proposal is a good idea or not.

**Comment by hteeyeoh** [comment]
what was the decision here? Im facing similar issue where running with stuff chain for large document the output always be small even though i have set large number for max_tokens parameters
