### ISSUE TITLE
cannot import name 'AzureOpenAI' from 'langchain.llms'

### ISSUE THREAD

**Issue by ozkank** [langchain-ai/langchain#9453]
### System Info

I got this error from on my office laptop
OS: Win 10

I checked AzureAI key, url, deployment and model names. No problem about that.
This guy having same issue with me : https://stackoverflow.com/questions/76750207/azureopenai-not-available-in-langchain

I deleted "import openai" part but no change.

Could somebody pls help me?

```
from dotenv import load_dotenv
from langchain.llms import AzureOpenAI
from langchain.embeddings import OpenAIEmbeddings
import openai
import os


# Load environment variables
load_dotenv()

# Configure Azure OpenAI Service API
openai.api_type = "azure"
openai.api_version = "2022-12-01"
openai.api_base = os.getenv('OPENAI_API_BASE')
openai.api_key = os.getenv("OPENAI_API_KEY")

# Create a completion
llm = AzureOpenAI(deployment_name="text-davinci-003", model_name="text-davinci-003")
joke = llm("Tell me a dad joke")
print(joke)
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from dotenv import load_dotenv
from langchain.llms import AzureOpenAI
from langchain.embeddings import OpenAIEmbeddings
import openai
import os

# Load environment variables
load_dotenv()

# Configure Azure OpenAI Service API
openai.api_type = "azure"
openai.api_version = "2022-12-01"
openai.api_base = os.getenv('OPENAI_API_BASE')
openai.api_key = os.getenv("OPENAI_API_KEY")

### Expected behavior

from dotenv import load_dotenv
from langchain.llms import AzureOpenAI
from langchain.embeddings import OpenAIEmbeddings
import openai
import os

**Comment by ozkank** [comment]
from langchain.chat_models.azure_openai import AzureChatOpenAI

ModuleNotFoundError: No module named 'langchain.chat_models'

It is same.

**Comment by sssssshf** [comment]
> from langchain.chat_models.azure_openai import AzureChatOpenAI
> 
> ModuleNotFoundError: No module named 'langchain.chat_models'
> 
> It is same.

do you selvo this prpblem?

**Comment by nikhil7601** [comment]
> from langchain.chat_models.azure_openai import AzureChatOpenAI
> 
> ModuleNotFoundError: No module named 'langchain.chat_models'
> 
> It is same.

Try this, it should work:
from langchain.chat_models import AzureChatOpenAI
