### ISSUE TITLE
OpenAI function call is not a FunctionMessage type

### ISSUE THREAD

**Issue by jsbryaniv** [langchain-ai/langchain#9457]
### System Info

I am playing around with tools in LangChain,  but I am running into an issue where the output of the model is not a `FunctionMessage` type even though the LLM is making a function call. For example in this code below
```python

# Import libraries
from langchain.chat_models import ChatOpenAI
from langchain.schema import HumanMessage, SystemMessage, AIMessage, FunctionMessage
from langchain.tools import tool, format_tool_to_openai_function

# Initialize the chat model
model = ChatOpenAI(model="gpt-3.5-turbo-0613", temperature=0)

# Define tools
@tool
def myfunc(x):
    """Calculate myfunc(x)."""
    return x ** 0.5
@tool
def myotherfunc(x):
    """Calculate myotherfunc(x)."""
    return x ** 2
tools = [myfunc]

# Define your messages
messages = [
    SystemMessage(content="You are a helpful AI who can calculate special functions using provided functions."),
    HumanMessage(content="What is func(4)?")
]

# Call the predict_messages method
functions = [format_tool_to_openai_function(t) for t in tools]
response = model.predict_messages(messages, functions=functions)

# Print the assistant's reply
print(response)
```
`response` is an AI message
```
AIMessage(content='', additional_kwargs={'function_call': {'name': 'myfunc', 'arguments': '{\n  "x": 4\n}'}}, example=False)
```
But I believe it should be a FunctionMessage.

Secondly, there is no clear way to turn an `AIMessage` of this type into a FunctionMessage to pass downstream. I have tried
```python
FunctionMessage(content='', **response.additional_kwargs)
FunctionMessage(content='', additional_kwargs=response.additional_kwargs)
FunctionMessage(content='', additional_kwargs=str(response.additional_kwargs))
```
but each of these attempts gives an error.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Run the code provided above.

### Expected behavior

The output should be a `FunctionMessage`.

**Comment by baskaryan** [comment]
The FunctionMessage is meant for sending the output of executing a function back to the model. Any response from the model is always an AIMessage. This mirrors the OpenAI message types: https://platform.openai.com/docs/api-reference/chat/create#chat/create-messages
![Screenshot 2023-08-18 at 10 24 08 AM](https://github.com/langchain-ai/langchain/assets/22008038/e55ab61c-31bd-4f67-b5ea-0d7320443a2b)

**Comment by jsbryaniv** [comment]
I see, I guess I misunderstood the role of functionmessages. They are messages from functions to AIs, not special messages for AIs to call functions.

**Comment by baskaryan** [comment]
> I see, I guess I misunderstood the role of functionmessages. They are messages from functions to AIs, not special messages for AIs to call functions.

Yep! I also mixed this up when i first tried using functions 😅. Sounds like issue can be closed, but let me know if I'm missing something.
