### ISSUE TITLE
Add Functionality to Update Embeddings in pgvector

### ISSUE THREAD

**Issue by redgeoff** [langchain-ai/langchain#9461]
### Feature request

I propose an enhancement to the pgvector functionality: the addition of an update feature in [pgvector.py](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/vectorstores/pgvector.py). As it stands, the code only seems to allow for the addition of new embeddings. I believe a specific function, potentially named `PGVector.update_documents()`, would greatly improve the utility of this module.

### Motivation

The inspiration for this proposal comes from an opportunity I've identified in my project to enhance efficacy and efficiency. I believe that the ability to update embeddings when one of my documents changes would streamline the process significantly. The current workaround of deleting the entire collection or removing all embeddings for the target document to save new ones, though functional, leaves room for improvement. This feature would not only optimize my project but could also benefit other users of pgvector who might face a similar need.

### Your contribution

I am prepared and eager to contribute to the creation of this feature. The `PGVector.update_documents()` function I propose would:
1. Retrieve the current list of embeddings for the document and load it into memory.
2. Obtain the chunks of the updated document.
3. Compare the updated document's chunks with the existing embeddings in memory to identify matches, potentially saving unnecessary model calls for existing embeddings. If the embedding doesn't exist in memory, the model would be called to generate the embedding.
4. Issue an update to the DB for any changing embeddings, an insert for any new ones, and a delete for any missing embeddings.
I am willing to submit a PR for this feature upon receiving feedback from the langchain maintainers.

**Comment by wukathy21** [comment]
@redgeoff Thank you for your proposal to enhance the pgvector functionality in LangChain! May I be so bold as to ask, in what context did you discover this more efficient method of updating embeddings?

**Comment by redgeoff** [comment]
It's just an observation I had while working with vector databases. Do you see a cleaner/simpler way?

**Comment by wukathy21** [comment]
I'm afraid i don't!

**Comment by redgeoff** [comment]
With the recently released [Indexing](https://github.com/langchain-ai/langchain/issues/9461), it appears that this enhancement is not longer needed.

**Comment by AIApprentice101** [comment]
@redgeoff Can you advise how to do that? I saw the documentation saying for overriding, use `pre_delete_collection=True`. But that's delete and create new right?

**Comment by ramsrib** [comment]
> With the recently released [Indexing](https://github.com/langchain-ai/langchain/issues/9461), it appears that this enhancement is not longer needed.

Link for Indexing API is [here](https://python.langchain.com/docs/modules/data_connection/indexing)
