### ISSUE TITLE
SQLDatabase object returns empty list with get_usable_table_names() 

### ISSUE THREAD

**Issue by Ramasrikanth** [langchain-ai/langchain#9469]
### System Info

Langchain 0.0.264
sqlalchemy 1.4.39
Platform mac os ventura 13.2.1
Python 3.11.4

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [X] Agents / Agent Executors
- [X] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. from langchain.utilities import SQLDatabase 
2. create a connection string (conn) with mssql dialect
3. create a connection using  db = SQLDatabase.from_uri(conn) 
4. use db.get_usable_table_names() to print table names 
5. you will see an empty list returning 

### Expected behavior

it should return table names from the database hosted in mssql

**Comment by Ramasrikanth** [comment]
![MicrosoftTeams-image](https://github.com/langchain-ai/langchain/assets/13881069/7bc9d0fb-d302-438c-89b7-26a60781e582)

it always gives table not found error when I include tables. i am sure this table is present is database

**Comment by mkalidas** [comment]
ValueError: include_tables {'****'} not found in database
Receiving the same error, any idea of the fix.

**Comment by Ramasrikanth** [comment]
@mkalidas are you able to fix this or any workaround ?

**Comment by mkalidas** [comment]
With 
langchain-experimental==0.0.16
sqlalchemy==1.4.49
and including schema with include_tables all in low case worked for me.

    table_list = [
        "***lower case****"]
    db = SQLDatabase(sf_engine,
                     schema="****lower case****",
                     include_tables=table_list,
                     sample_rows_in_table_info=2
                     )
