### ISSUE TITLE
Doc Legibility - Increase Width

### ISSUE THREAD

**Issue by totalhack** [langchain-ai/langchain#948]
The documentation center column is quite narrow which causes a lot of unnecessary wrapping on code examples and API reference docs. Example of the qdrant code pictured.

![image](https://user-images.githubusercontent.com/43683140/217641523-958dbe4e-58ca-4814-91db-14450eb343c0.png)

**Comment by TheApeMachine** [comment]
You can try to hide the menu with the three bars top middle to the left a little. Or try full screen, alternatively, I think your issue is your monitor is very wide, so the css gets confused. Make your browser window a little smaller.

**Comment by totalhack** [comment]
I tried both of those and neither worked. I'm on a 14" laptop.

**Comment by totalhack** [comment]
So this is obviously just some default in the them that doesn't handle large pixel width devices well. I am on a 14" laptop that has 2560 pixels across and is running at 100% scale (not a macbook which usually scales down by default I think). 

There are two settings main impacting this:

```
@media (min-width: 1200px)
.container, .container-lg, .container-md, .container-sm, .container-xl {
  max-width: 1140px;
}

#main-content {
    max-width: 70%;
}
```

Not sure why the 70% one is needed at all since the div it lives in is already limited in size, and the other media query just isn't working well on larger devices. Anyhow, not a high priority compared to the many other things you guys are working on, but just figured I'd bring it to your attention. Thanks.

**Comment by hwchase17** [comment]
i very much agree - i spent 10 min and couldn't figure it out, so may save it for later. but completely agreee
