### ISSUE TITLE
Handling "openAI API error received"

### ISSUE THREAD

**Issue by gameveloster** [langchain-ai/langchain#950]
I have a function that calls the openai API multiple times. Yesterday the function crashed occasionally with the following error in my logs

> error_code=None error_message='The server had an error while processing your request. Sorry about that!' error_param=None error_type=server_error message='OpenAI API error received' stream_error=False

However I cant reproduce this error today to find out which langchain method call is throwing this. My function has a mix of

```py
load_qa_chain(**params)(args)

LLMChain(llm=llm, prompt=prompt).run(text)

LLMChain(llm=llm, prompt=prompt).predict(text_2)
```

Should I be wrapping each of these langchain method calls using `try/except`?

```py
try:
    LLMChain(llm=llm, prompt=prompt).run(text)
except Exception as e:
    log.error(e)
```

I did try it and when the error message is printed, it appears that it was not catch by the try/except... and even appears to retry the api call?

Thanks!

**Comment by TheApeMachine** [comment]
It seems to just be logging and exiting, which makes sense. If you want it to retry, you must somehow restart your process in the Except clause. For instance:

```python
    while True:
        try:
            agent.prompt(input())
        except Exception as err:
            print("ERROR:", err)
```
In this case the while loop will just make sure it does not quit.

**Comment by hwchase17** [comment]
this is caused by the openai server - i bet yesterday it was a bit overloaded and not working great, but is fixed now (it sometimes goes down)

**Comment by dheerajiiitv** [comment]
Is there a way to handle errors from openai even if the retries fails. I am using predict at many places, and this is very diffcult and not so cleaner way to add try and except at each place, instead I can define some httperror

**Comment by pors** [comment]
Another error that can be relevant (it is for me) is when the OpenAI API key is invalid. This is what is returned:
`error_code=invalid_api_key error_message= error_param=None error_type=invalid_request_error`

When I catch the exception, the error is `<empty message>`. So that is not very helpful, but the `error_code` is, how can we get to that?
