### ISSUE TITLE
QAGenerationChain.run often ends in JSONDecodeError

### ISSUE THREAD

**Issue by joshuasundance-swca** [langchain-ai/langchain#9505]
The `QAGenerationChain` as it is currently written is prone to a `JSONDecodeError`, as mentioned in https://github.com/langchain-ai/langchain/pull/9503. That was my naive attempt to fix the problem I was having, but as I explained in closing the PR, I think a `PydanticOutputParser` with a more instructive prompt or an auto-fixing parser would be more robust. Plus, I think the successful runs after implementing my fix were just luck. 🤣 

In `QAGenerationChain._call`, after generation, `json.loads` frequently raises a `JSONDecodeError`. This is usually because the response is wrapped in Markdown code tags or prefaced with a message, as seen in the following traces:

- `ChatOpenAI` gpt-3.5-turbo: [successful trace](https://smith.langchain.com/public/6c42845c-bbe2-41c1-99a4-7669112f1504/r)
- `ChatOpenAI` gpt-4: [`JSONDecodeError` due to Markdown formatting](https://smith.langchain.com/public/d235ef1e-fb13-4177-adb3-6ddaf159bfea/r)
- `ChatAnthropic` Claude 2: [`JSONDecodeError` due to message before the JSON + Markdown formatting](https://smith.langchain.com/public/27eed20e-9ca5-4b4a-a3d3-71efde7aee3c/r)
- `ChatAnyscale` llama 2 70b: [successful trace](https://smith.langchain.com/public/e8f0b44c-424f-47ef-8cb3-31713b548d46/r?tab=0)
- `ChatAnyscale` llama 2 70b: [`JSONDecodeError` due to message before the JSON + Markdown formatting](https://smith.langchain.com/public/c89a7415-477d-4b82-a0a4-0a333b8b5680/r)

Each of these models had a mix of successful and failed runs. I probably should have lowered the temperature and tried non-chat models as well.

![image](https://github.com/langchain-ai/langchain/assets/84336755/1e4da267-3b7e-40c0-b726-3a0304533b44)

I would like to help however I could on this, I just want to be sure my fix aligns with the greater vision for this chain since it seems particularly useful. :)

### System Info

Version info from LangSmith:
```
RUNTIME
langchain_version: "0.0.268"
library: "langchain"
library_version: "0.0.268"
platform: "Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.36"
runtime: "python"
runtime_version: "3.11.4"
sdk_version: "0.0.25"
```

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [X] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```python
from langchain.chains import QAGenerationChain

# tested with gpt-3.5-turbo, gpt-4, claude 2, and llama 2 70b

qagen = QAGenerationChain.from_llm(llm=llm)

question = qagen.run(docs[0].page_content)

# JSONDecodeError (sometimes)
```

The error is inconsistent, as seen in the screenshot above. This is for reasons we're all familiar with: perhaps the output is wrapped in Markdown code formatting with triple-backticks, maybe it's prefaced with a "sure, here's your JSON", etc.

Relevant examples from LangSmith:

- `ChatOpenAI` gpt-3.5-turbo: [successful trace](https://smith.langchain.com/public/6c42845c-bbe2-41c1-99a4-7669112f1504/r)
- `ChatOpenAI` gpt-4: [`JSONDecodeError` due to Markdown formatting](https://smith.langchain.com/public/d235ef1e-fb13-4177-adb3-6ddaf159bfea/r)
- `ChatAnthropic` Claude 2: [`JSONDecodeError` due to message before the JSON + Markdown formatting](https://smith.langchain.com/public/27eed20e-9ca5-4b4a-a3d3-71efde7aee3c/r)
- `ChatAnyscale` llama 2 70b: [successful trace](https://smith.langchain.com/public/e8f0b44c-424f-47ef-8cb3-31713b548d46/r?tab=0)
- `ChatAnyscale` llama 2 70b: [`JSONDecodeError` due to message before the JSON + Markdown formatting](https://smith.langchain.com/public/c89a7415-477d-4b82-a0a4-0a333b8b5680/r)

### Expected behavior

`QAGenerationChain.run` should return its expected output with no `JSONDecodeError`. I realize there's only so much we can do for the chain's default settings, and an LLM call can be inherently predictable, but some parsing and error handling would be nice. :)

**Comment by joshuasundance-swca** [comment]
> _🤖_
> 
> Hi there,
> 
> Thank you for bringing this issue to our attention and for your detailed report. It seems like you're encountering a `JSONDecodeError` when the output from the language model is wrapped in Markdown code tags or prefaced with a message. This is indeed a known issue and we've had a similar problem reported in the past ([issue #8357](https://github.com/langchain-ai/langchain/issues/8357)).
> 
> The solution to that issue was to modify the regular expression used for parsing the JSON output to be greedy, which helped in cases where the output was wrapped in Markdown code blocks. However, it seems like this solution might not be sufficient for your case, especially when the output is prefaced with a message.
> 
> One way to handle this could be to modify the `_call` method in the `QAGenerationChain` class to use the `parse_json_markdown` function from the `json.py` file in the `output_parsers` directory. This function is designed to parse a JSON string from a Markdown string. Here's how you can modify the `_call` method:
> 
> ```python
> from langchain.output_parsers.json import parse_json_markdown
> 
> def _call(
>     self,
>     inputs: Dict[str, Any],
>     run_manager: Optional[CallbackManagerForChainRun] = None,
> ) -> Dict[str, List]:
>     docs = self.text_splitter.create_documents([inputs[self.input_key]])
>     results = self.llm_chain.generate(
>         [{"text": d.page_content} for d in docs], run_manager=run_manager
>     )
>     qa = []
>     for res in results.generations:
>         try:
>             qa.append(parse_json_markdown(res[0].text))
>         except JSONDecodeError:
>             # Handle the exception here, for example, by skipping this item
>             pass
>     return {self.output_key: qa}
> ```
> 
> In this modified version of the `_call` method, if `parse_json_markdown(res[0].text)` raises a `JSONDecodeError`, the exception is caught and the current item is skipped. This should prevent the `JSONDecodeError` from stopping the execution of the program. However, you might want to add some additional handling for this case, such as logging the error or the problematic text.
> 
> Please note that this is a workaround and might not be the best solution. We're always open to contributions and if you have a better solution, feel free to open a pull request. We appreciate your help in improving LangChain!
> 
> Let me know if this helps or if you have any other questions.
> 
> ## Sources
> - [LLM output parsing error for answers including code sections.](https://github.com/langchain-ai/langchain/issues/8357)
> - [libs/langchain/langchain/chains/qa_generation/base.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/chains/qa_generation/base.py)
> - [libs/langchain/langchain/output_parsers/json.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/output_parsers/json.py)
> 
> ---
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I do not dislike this approach, but shouldn't that kind of logic be placed in the relevant output parser instead of in `_call`?

**Comment by joshuasundance-swca** [comment]
In my fork, I've edited `prompt.py`: https://github.com/joshuasundance-swca/langchain/blob/4817f46388e9ed46b136d003c185eeb5ea832846/libs/langchain/langchain/chains/qa_generation/prompt.py

and `base.py`: https://github.com/joshuasundance-swca/langchain/blob/4817f46388e9ed46b136d003c185eeb5ea832846/libs/langchain/langchain/chains/qa_generation/base.py


But I think it may be too tightly coupled and/or not structured in a way that aligns with the rest of the repo. 

Here's what a chain run currently looks like:

https://smith.langchain.com/public/33b4f72d-212b-476d-a45d-16b737ea47a6/r 

```python
# ...

qagen = QAGenerationChain.from_llm(llm=chat, k=3)  # also implements `k`

chain_output = [
    qagen.run(pages[p].page_content)
    for p in (1, 5, 11)
]

chain_output
```

```python
[[QuestionAnswerPairList(QuestionAnswerPairs=[QuestionAnswerPair(question='What are rivers critical sources of for animals?', answer='food, water, shelter, and other necessary resources'), QuestionAnswerPair(question='What is the focus of this study?', answer='population structure and social organization in birds of the Southwestern desert riparian woodland'), QuestionAnswerPair(question='What is the objective of this study?', answer='to determine the relationship between vegetation structure of the habitats and population structure of the avian communities')])],
 [QuestionAnswerPairList(QuestionAnswerPairs=[QuestionAnswerPair(question='What is the main drainage of the Verde Valley?', answer='The main drainage of the Verde Valley is the Verde River.'), QuestionAnswerPair(question='What are the tree species found in the mixed deciduous areas?', answer='The tree species found in the mixed deciduous areas include Arizona sycamore, cottonwood, Arizona ash, Arizona cypress, junipers, net-leaf hackberry, Arizona walnut, and Arizona alder.'), QuestionAnswerPair(question='Which study area had the highest tree density per hectare?', answer='Study area M3 had the highest tree density per hectare.')])],
 [QuestionAnswerPairList(QuestionAnswerPairs=[QuestionAnswerPair(question='What are the weight classes of birds mentioned in the text?', answer='The weight classes mentioned in the text are 35-40 g, 45-50 g, 75-80 g, and 130-135 g.'), QuestionAnswerPair(question="What percentage of species and pairs exhibited 'class A' territories on the homogeneous cottonwood areas?", answer="Only 36% of the species and 22% of the pairs exhibited 'class A' territories on the homogeneous cottonwood areas."), QuestionAnswerPair(question='What is the relationship between colonial nesting and proximity to food supplies?', answer='Lack (1968) found that colonial nesting is closely linked to proximity to adequate food supplies.')])]]
```

**Comment by cpatrickalves** [comment]
@joshuasundance-swca 
Thanks for sharing this. I was having a similar issue when using GPT-4. 
I've updated the prompt adding the following: 

`"Do not provide additional commentary and do not wrap your response in Markdown formatting. Return RAW, VALID JSON."`

And it worked.
