### ISSUE TITLE
how to improve the perfromance of agents to get better responses from the local model like gpt4all

### ISSUE THREAD

**Issue by Kuramdasu-ujwala-devi** [langchain-ai/langchain#9506]
how to improve the perfromance of agents to get better responses from the local model like gpt4all

**Comment by Kuramdasu-ujwala-devi** [comment]
from load_data import load_document, split_documents
from create_vectorstore import generate_embeddings
from langchain.agents.agent_toolkits import (
    create_vectorstore_agent,
    VectorStoreToolkit,
    VectorStoreInfo,
)
import logging
import os
from langchain import OpenAI, VectorDBQA
from langchain.llms import OpenAI, GPT4All, LlamaCpp
from langchain.agents import initialize_agent, Tool
from langchain.agents import AgentType
from langchain.tools import BaseTool
import pandas as pd
import numpy as np
from langchain.chains.conversation.memory import ConversationBufferWindowMemory
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
import csv
from datetime import datetime
import time
import yaml
import os
from langchain.chat_models import ChatOpenAI

# Load parameters from YAML file
with open('qna/config.yml', 'r') as file:
    params = yaml.safe_load(file)


llm = ChatOpenAI(openai_api_key= params['openai_api_key'])
llm.predict("Hello, world!")

csv_file_path = params['csv_file_path']
model_path = params['model_path']
embedding_model = params['embedding_model']
os.environ["OPENAI_API_KEY"] = params['openai_api_key']
question = params['question']
context = params['context']
model = params['model_type']


data = load_document(csv_file_path)

documents = split_documents(data)

vector_store = generate_embeddings(documents, embedding_model)

##########prompt template
prompt_template1 = """
You are a Bot assistant for answering any questions related to the given documents.
For a given question find the answer from the documents given to you.Use the question column from the document given to find the answer.
Please follow below instruction:
- To find the answer first read the context and question properly.
- Do not rely on any prior knowledge.
- Avoid using web search.
- show only the top result.
- If you don't find the answer, simply state that you sorry! could not find. Avoid make up an answer.
-------------------------------------


context : {context}

now based on above context answer the question accurately:

Question: {question}

Answer:

------------------------------------
"""


def generate_prompt(prompt_template1):
    logger = logging.getLogger(__name__)
    prompt_template = PromptTemplate(template=prompt_template1, input_variables=["question", "context"]) 
    logger.info('Prompt template created Successfully!')
    return prompt_template

def load_qa_chain_model(model_type, prompt_template):
    logger = logging.getLogger(__name__)
    logger.info(f'model is,{model_type}')

    if model_type.lower() == "gpt4all":
        llm=GPT4All(
        model= model_path,   
        verbose=True, 
        streaming= True, 
        n_threads = 2,
        temp = 0.2,
        # top_p = 0.1,
        # top_k = 40,
        repeat_penalty = 200, 
        repeat_last_n = 0,
        backend='gptj', 
        )
    elif model_type.lower() == "openai":
        llm=OpenAI(model_name="text-davinci-003",
            temperature=0,
            max_tokens=300,
         )
    else:
        raise ValueError("Invalid embedding model specified.")
    
    chain_type = {"prompt": prompt_template}
    logging.info('Model loaded successfully!')
    return llm, chain_type

####memory
def memory():
    logger = logging.getLogger(__name__)
    conversational_memory = ConversationBufferWindowMemory(
    memory_key='chat_history',
    k=5,
    return_messages=True
    )
    logger.info('Conversational_memory created successfully')
    return conversational_memory


####QA_chain
def qa_chain(retriever, llm, chain_type):
    logger = logging.getLogger(__name__)
    tacit_db = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff",chain_type_kwargs = chain_type,  retriever=retriever.as_retriever()
    )
    logger.info('Created RetrievalQA chain')
    return tacit_db


####creating custom tacit db_tool
def custom_db_tool(retriever, llm, chain_type):
    logger = logging.getLogger(__name__)
    tacit_db = qa_chain(retriever, llm, chain_type)
    tools = [
    Tool(
        name="Tacit knowledge QA System",
        func=tacit_db.run,
        description="useful for when you need to answer questions about the Tacit knowledge. Decompose the question if the question is complex then search answers for related parts of the questions finally combine all the answers as a final output. Follow the instructions given in the prompt_template before searching answer. If you could not find the answer say you didn't found",
    ),
    ]
    logger.info('RetrievalQA Tool created')
    return tools

def track_lang_model(question, model_gen_answer, prompt_template, llm, duration):
    csv_file_path = "qna/llm_tracking.csv"

    # Check if the CSV file already exists or not
    if not os.path.exists(csv_file_path):
        # If the file doesn't exist, create a new one with headers
        with open(csv_file_path, mode='w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(['question','model_gen_answer','prompt template', 'llm','duration'])

    # Append the new data to the CSV file
    with open(csv_file_path, mode='a', newline='') as file:
        writer = csv.writer(file)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        writer.writerow([question,model_gen_answer,  prompt_template,llm,  duration])

####Intialize agent
def call_agent_func(retriever, llm, chain_type, query, prompt_template):
    logger = logging.getLogger(__name__)
    start_time = time.time()
    conversational_memory = memory()
    tools = custom_db_tool(retriever,llm, chain_type)
    agent = initialize_agent(
    tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True, memory = conversational_memory,
        max_iterations=2,
        early_stopping_method='generate'    #return_intermediate_steps = True
    )
    logger.info('Initialization of Agent is done')

    answer  = agent.run(query)
    end_time = time.time()
    duration = end_time - start_time
    logger.info('Agent executed successfully!')

    track_lang_model(query , answer, prompt_template, llm, duration)
    return answer

template = generate_prompt(prompt_template1)

llm, chain_type = load_qa_chain_model(model, template)

# answer = main_agent_tool(vector_store, llm, chain_type, question)
answer = call_agent_func(vector_store,llm, chain_type,  question, prompt_template1)

print(answer)``

Here is my code - 
I want to run complex queries using gpt4all model, but the model is not able to give response atleast. 

output -
> Entering new AgentExecutor chain...
 Pricing strategy, effective closing techniques, and handling objections during a sales pitch are important aspects of sales.
Action: Research the topic and gather information on pricing strategy, effective closing techniques, and handling objections during a sales pitch.
Action Input: The information gathered from research.
Observation: Research the topic and gather information on pricing strategy, effective closing techniques, and handling objections during a sales pitch. is not a valid tool, try another one.

It is failing badly.
How to improve the performance here?

**Comment by Kuramdasu-ujwala-devi** [comment]
@ dosu-bot
please answer

**Comment by naman-modi** [comment]
Hey @Kuramdasu-ujwala-devi 👋, great question!  

You should definitely checkout  [Infino's](https://github.com/infinohq/infino) callback to monitor and improve the LLM performance. Link to [docs here](https://python.langchain.com/docs/integrations/providers/infino). Please feel free to reach out in case of any issues.
