### ISSUE TITLE
PDF Loader clipping ending of document

### ISSUE THREAD

**Issue by gweinz** [langchain-ai/langchain#951]
I am trying to test load certain text based PDFs, and for some single page documents the data loader is not catching the tail-end of the PDF. Any suggestions on debugging this?

**Comment by hwchase17** [comment]
do you have an example?

we also added a pdf loader (https://langchain.readthedocs.io/en/latest/modules/document_loaders/examples/pdf.html#using-pypdf) - does this one work?
