### ISSUE TITLE
missing model_name param in ChatAnthropic

### ISSUE THREAD

**Issue by shon-otmazgin** [langchain-ai/langchain#9510]
### System Info

Python 3.8.16
langchain==0.0.268

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

`ChatAnthropic` doesn't have `model_name` attribute. instead, it has a `model` attribute that specifies the name. Other chat models such as `ChatOpenAI`, `ChatVertexAI` has `model_name` attribute, this breaks the interface while integrating with multiple LLMs.

### Expected behavior

`llm = ChatAnthropic(model_name='claude-2')`
`print(llm.model_name)`

**Comment by shon-otmazgin** [comment]
one of the main points of this pkg is to provide a unified interface for LLM no? if so, I can't see any reason to implement it like this. Also they `max_retries` and `n` param are missing

**Comment by shon-otmazgin** [comment]
hi @joshuasundance-swca and @baskaryan I also found `max_retries` missing does it will also be included in the merge?

**Comment by codeonprod** [comment]
I have added a PR for the similar change.

https://github.com/langchain-ai/langchain/pull/29580
