### ISSUE TITLE
FAISS vectorstore `similarity_search_with_relevance_scores` returns strange/false result with `MAX_INNER_PRODUCT`

### ISSUE THREAD

**Issue by jpzhangvincent** [langchain-ai/langchain#9519]
### System Info

langchain==0.0.268
python=3.9
mac

### Who can help?

I used the FAISS as the vector store. it seems that the `similarity_search_with_score` (supposedly ranked by distance: low to high) and `similarity_search_with_relevance_scores`((supposedly ranked by relevance: high to low) produce conflicting results when specifying `MAX_INNER_PRODUCT` as the distance strategy. Please see the screenshot below:
<img width="675" alt="Screenshot 2023-08-20 at 6 54 15 PM" src="https://github.com/langchain-ai/langchain/assets/7220686/88981277-a0b4-462b-929c-63bd19d4faff">

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.vectorstores.faiss import FAISS
from langchain.embeddings import HuggingFaceEmbeddings

embedding_engine = HuggingFaceEmbeddings(
                model_name= "BAAI/bge-base-en", #"sentence-transformers/all-mpnet-base-v2",
                model_kwargs={"device": "cpu"},
                encode_kwargs={'normalize_embeddings': True} # set True to compute cosine similarity
            )
texts = ["I like apples", "I hate apples", "I like oranges"]
simple_vecdb = FAISS.from_texts(texts, 
                                embedding_engine,
                                distance_strategy="MAX_INNER_PRODUCT")

# test 1
simple_vecdb.similarity_search_with_score("I like apples")

# test 2
simple_vecdb.similarity_search_with_relevance_scores("I like apples")

### Expected behavior

For similarity_search_with_score, if the `similarity_search_with_score` documentation is correct saying that "List of documents most similar to the query text with L2 distance in float. Lower score represents more similarity.", then the result from `similarity_search_with_score` should have matched the identical text `I like apple` with `(distance)score=0` and the `similarity_search_with_relevance_scores` with `(relevance)score=1`, no?

if the FAISS return the cosine similarity score already during the `similarity_search_with_score`call, should the `_max_inner_product_relevance_score_fn` for the FAISS just return the identical score instead of `1-score` when calculating the relevance score?

**Comment by SajalRandhar** [comment]
Hi, 
How to get the docstore_id of the returned documents?
