### ISSUE TITLE
AttributeError: 'super' object has no attribute 'parse_obj' when using OpenAPISpec.from_file

### ISSUE THREAD

**Issue by elliexcoding** [langchain-ai/langchain#9520]
### System Info

Langchain version 0.0.268

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [X] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Load in .yaml file containing the OpenAPI specification.
2. Call the OpenAPISpec with   ` open_api_spec = OpenAPISpec.from_file(file_path)`

Error shows that in _openapi.py_ line 202 ,`return super().parse_obj(obj)` no longer inherits the super method from Pydantic's BaseModel parse_obj.  

### Expected behavior

The OpenAPISpec should be delivered so that it can be passed on to `NLAToolkit.from_llm_and_spec`.

**Comment by kreneskyp** [comment]
Also affecting 
- `OpenAPISpec.from_url`
- `get_openapi_chain`


The `get_openapi_chain` error is hidden, but I confirmed it's the same error as above.
```
File "/usr/local/lib/python3.11/site-packages/langchain/chains/openai_functions/openapi.py", line 272, in get_openapi_chain
    raise ValueError(f"Unable to parse spec from source {spec}")
```

**Comment by kreneskyp** [comment]
cc @baskaryan @eyurtsev 

Tracked this regression to `openapi-schema-pydantic` being switched to an optional dependency (https://github.com/langchain-ai/langchain/pull/9408). 

### Work around:
install  `openapi-schema-pydantic` into your environment.

### Root cause:

1. `OpenAPISpec's` parent class defaults to `object` when  `openapi-schema-pydantic` is unavailable.

    https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/utilities/openapi.py#L54-L57

2. This leads to an exception in `OpenAPISpec.parse_obj` when it calls `super().parse_obj()`. 

    https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/utilities/openapi.py#L201-L202

**Comment by batmanscode** [comment]
Thanks for looking into it and figuring out a workaround @kreneskyp

Unfortunately for me installing `openapi-schema-pydantic` didn't work

**Comment by PizBernina** [comment]
> > Having the same issue, installing `openaiapi-schema-pydantic` did not work. :(
> 
> I ran into this issue again when using Pydantic 2.0 with LangChain.
> 
> Try `langchain==0.0.319` with `openapi-pydantic==0.3.2`. Hopefully fixes all the issues now!

This resolved the issue for me, cheers!

**Comment by borisko123** [comment]
openapi_schema_pydantic is changed to:
openapi-pydantic          0.3.2  (last version)
install it when using langchain

**Comment by jepsenwan** [comment]
openapi_schema_pydantic is changed to:
openapi-pydantic 0.3.2 (last version)
install it when using langchain

This works perfectly fine, thanks for the advise.

**Comment by marufaytekin** [comment]
openapi_schema_pydantic is changed to:
openapi-pydantic 0.3.2 (last version)
install it when using langchain

This worked fine, thanks for the advise.

**Comment by payamsaremi** [comment]
"pip install openapi-pydantic" fixed it for me

**Comment by xinyangfan** [comment]
langchain 0.1.9
openapi-pydantic 0.4.0
Still having this issue

**Comment by prova** [comment]
My colleague is facing the same issue on Python 3.10.12 and langchain==0.1.12 plus openapi-pydantic==0.4.0 (and also tried 0.3.2). On my PC, all is good with the same versions and Python. This is some random stuff.

**Comment by ChanduTadanki** [comment]
> openapi_schema_pydantic is changed to: openapi-pydantic 0.3.2 (last version) install it when using langchain
> This works perfectly fine, thanks for the advise.
That solved my issue. Thanks. 
Note: (1) I also had to restart the kernel, (2) remove the imports from openapi_schema_pydantic, and (3) include imports from openapi-pydantic only. 
More details here: https://community.deeplearning.ai/t/attributeerror-super-object-has-no-attribute-parse-obj/481376/11

**Comment by ChanduTadanki** [comment]
> openapi_schema_pydantic is changed to: openapi-pydantic 0.3.2 (last version) install it when using langchain

That solved my issue. Thanks. 
Note: (1) I also had to restart the kernel, (2) remove the imports from openapi_schema_pydantic, and (3) include imports from openapi-pydantic only. 
More details here: https://community.deeplearning.ai/t/attributeerror-super-object-has-no-attribute-parse-obj/481376/11

**Comment by bigrobinson** [comment]
Thanks, @ChanduTadanki for reminding me to restart kernel. That was the last step to get things working for me.
