### ISSUE TITLE
Plain models are not calling callbacks when cached

### ISSUE THREAD

**Issue by mariokostelac** [langchain-ai/langchain#9537]
### System Info

```
pip freeze | grep langchain
langchain==0.0.268
langchainplus-sdk==0.0.17
```

### Who can help?

@hwchase17 @agola11 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

```py
from typing import Any, Dict, List

import langchain
from langchain.cache import SQLiteCache
from langchain.callbacks.base import BaseCallbackHandler
from langchain.chat_models import ChatVertexAI
from langchain.llms import VertexAI
from langchain.schema import HumanMessage

langchain.llm_cache = SQLiteCache(database_path="langchain-llm-cache.db")


class CallbackHandler(BaseCallbackHandler):
    run_inline = True

    def __init__(self, logger=None):
        self.messages = []

    def on_llm_start(self, serialized: Dict[str, Any], prompts: List[str], run_id, parent_run_id, **kwargs: Any) -> Any:
        self.messages.append(run_id)


callback = CallbackHandler()
bison_text_llm = VertexAI(model_name="text-bison@001", temperature=0.0, max_output_tokens=500, callbacks=[callback])
bison_chat_llm = ChatVertexAI(model_name="chat-bison@001", temperature=0.0, max_output_tokens=500, callbacks=[callback])

bison_chat_llm([HumanMessage(content="Hello, how are you?")])
assert len(callback.messages) == 1
bison_chat_llm([HumanMessage(content="Hello, how are you?")])
assert len(callback.messages) == 2

bison_text_llm("Hello, how are you?")
assert len(callback.messages) == 3
bison_text_llm("Hello, how are you?")
assert len(callback.messages) == 4
```

### Expected behavior

It's unclear to me whether callbacks should be called when call is cached, but we can see that chat and plain text models implement different behaviour.

Ideally, callbacks would be called, with a flag saying that call is cached.

**Comment by dmytro-karpovych-maxa** [comment]
@dosu-bot
What about adding a new event like `on_llm_cached`?
Maybe it will be simpler to implement?

**Comment by devstein** [comment]
Hey @dmytro-karpovych-maxa as of now Dosu only responds to the author of issues. This may change in the future.

Let me know if you have any feature requests or ideas for Dosu!

**Comment by dmytro-karpovych-maxa** [comment]
@devstein It's not so critical 
what about having one more event to track cached LLM calls?

**Comment by mariokostelac** [comment]
Sounds good to me, given that these requests are behaving quite differently (e.g. streaming LLMs won't call callbacks etc).

**Comment by mariokostelac** [comment]
This issue is still relevant.
