### ISSUE TITLE
Does langchain support using Contriever as an embedding method?

### ISSUE THREAD

**Issue by bryanyzhu** [langchain-ai/langchain#954]
It is great to see langchain already support [HyDE](https://langchain.readthedocs.io/en/latest/modules/utils/combine_docs_examples/hyde.html). But in its original paper, once the hypothetical documents are generated, the embedding is computed using [Contriever](https://github.com/facebookresearch/contriever) model as described in the HyDE official repo (https://github.com/texttron/hyde). Can I ask how should I enable using Contriever instead of using OpenAI embeddings? Thank you.

**Comment by hwchase17** [comment]
i looked into this breifly - i actually struggled to load it from huggingface. eg i ran

```
from transformers import AutoTokenizer, Contriever

tokenizer = AutoTokenizer.from_pretrained("facebook/contriever")

model = Contriever.from_pretrained("facebook/contriever")
```
as per https://huggingface.co/facebook/contriever but it didnt work. does this work for you?

**Comment by bryanyzhu** [comment]
Yeah, it works for me, I can run its demo without any problem.

```
from src.contriever import Contriever
from transformers import AutoTokenizer

contriever = Contriever.from_pretrained("facebook/contriever") 
tokenizer = AutoTokenizer.from_pretrained("facebook/contriever") #Load the associated tokenizer:

sentences = [
    "Where was Marie Curie born?",
    "Maria Sklodowska, later known as Marie Curie, was born on November 7, 1867.",
    "Born in Paris on 15 May 1859, Pierre Curie was the son of Eugène Curie, a doctor of French Catholic origin from Alsace."
]

inputs = tokenizer(sentences, padding=True, truncation=True, return_tensors="pt")
embeddings = contriever(**inputs)

score01 = embeddings[0] @ embeddings[1] #1.0473
score02 = embeddings[0] @ embeddings[2] #1.0095

print(score01, score02)
# tensor(1.0473, grad_fn=<DotBackward0>) tensor(1.0095, grad_fn=<DotBackward0>)
```

My python env is 3.10.9, pytorch version is 1.13.1-cuda117, and transformer version is 4.25.1. I can also run the demo in my M1 mac without problems.

**Comment by dimirc** [comment]
> It is great to see langchain already support [HyDE](https://langchain.readthedocs.io/en/latest/modules/utils/combine_docs_examples/hyde.html). But in its original paper, once the hypothetical documents are generated, the embedding is computed using [Contriever](https://github.com/facebookresearch/contriever) model as described in the HyDE official repo (https://github.com/texttron/hyde). Can I ask how should I enable using Contriever instead of using OpenAI embeddings? Thank you.

Does is actually make any significant difference between using OpenAI embedding vs Contriever?

Btw, something I additional I notice on the langchain implementation of Hyde, is that you’re only considering the hypothetical docs to calculate the final vector and not also considering the embedding of the origin query/question to be part of the group of vectors to get the mean from.

**Comment by vikaskookna** [comment]
@hwchase17 @bryanyzhu How are HyDE embeddings useful, I am going through the doc here https://langchain.readthedocs.io/en/latest/modules/indexes/examples/hyde.html, but I don't find the implementation any different from OpenAI embeddings, the hypothetical embeddings stored in result variable are not used for the further process?

**Comment by krakover** [comment]
Contriever works well with the example above (from the huggingface contriever page), and the issue still occurs with the latest LangChain version. It will be great to add support for it.
