### ISSUE TITLE
Being able to retry a chain until the output is valid

### ISSUE THREAD

**Issue by kevin-guimard-ext** [langchain-ai/langchain#9546]
### Feature request

The RetryOutputParser class has several drawbacks:
- it must point to a chain different from the one that calls it
- it does not make it possible to specify a number of retries

### Motivation

Following a request, ChatGPT sometimes answers with an invalid format and the same request must be resent to get the expected output.

It would be useful to have a new parameter added to a LLMChain (endowed with an output parser) to be able to retry the chain till the output is validated by the parser (i.e. it does not trigger any exception), with the possibility to specify a maximum of retries. It could take this form (just a proposal):
```
chain = LLMChain(llm=..., prompt=..., output_parser=..., retry=RetryChain(max_tries=10))
```

### Your contribution

Well, I don't think this feature would be complex to develop for the developers that already know the code. Let me know if this request makes sense.

**Comment by davidwu1412** [comment]
Hi Kevin Guimard,

Could you clarify what is an invalid output? Is it just output that is not properly formatted, or does it also include outputs that are considered properly formatted but are irrelevant/wrong based on the question posed to ChatGPT?

**Comment by kevin-guimard-ext** [comment]
Hi David,

An invalid output is an output that won’t be properly formatted, and this bad format will be detected by the output parser that is supposed to trigger an exception in langchain’s framework. This is a classical case in which a simple re-run of the chain can result in the expected output format. That’s the reason why I suggested an improvement in the framework to handle this situation. Note that this retry behavior is already implemented by langchain in the case when the LLM returns a timeout error.

Regards,
Kevin

**Comment by davidwu1412** [comment]
Thanks for the clarification. I am a first time contributor and would like to work on this.

**Comment by timxieICN** [comment]
Any update on this feature? I think this feature will be extremely useful for OpenAI's function calling via LLMChain, because the calling does not always guarantee to work on the first attempt

**Comment by davidwu1412** [comment]
Sorry for the late reply. It seems that somebody has already fixed this issue somewhere else: https://github.com/langchain-ai/langchain/pull/11903.

**Comment by kevin-guimard-ext** [comment]
Great news!

**Comment by marctorsoc** [comment]
@kevin-guimard-ext let's close the issue then? :)

**Comment by kevin-guimard-ext** [comment]
@marctorsoc could you point me to the documentation of the new feature so that I could test it and check whether it meets my needs?

**Comment by marctorsoc** [comment]
@kevin-guimard-ext you yourself wrote "good news!" above :) 

You can see https://github.com/langchain-ai/langchain/pull/11903. I just ended up here searching for the the feature you were asking for, and I felt like it was solved, but maybe you were asking for something else

**Comment by kevin-guimard-ext** [comment]
I just said it was a good news if the problem had been fixed, but I was waiting for its release in an official version of langchain to test it. The link you give only gives a vague description of the issue, so if you think that this problem has been solved, please direct me to the part of the documentation that describes the new feature.

**Comment by RicSala** [comment]
Also interested in this feature. Is it done?
