### ISSUE TITLE
Direct initial redis database can't successfully use searching function since index missing

### ISSUE THREAD

**Issue by r1407p** [langchain-ai/langchain#9585]
### System Info

langchain version: 0.0.267

### Who can help?

@hwchase17 
@eyurtsev 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

# Redis vector database initialization
<p>
embeddings = OpenAIEmbeddings(openai_api_key=os.getenv("OPENAI_API_TYPE"), <br/>
&nbsp;&nbsp;&nbsp;&nbsp;                              deployment=os.getenv("OPENAI_EMBEDDING_MODEL_NAME"), <br/>
 &nbsp;&nbsp;&nbsp;&nbsp;                             client="azure", <br/>
&nbsp;&nbsp;&nbsp;&nbsp;                              chunk_size=1)<br/>
redis_vector_db = Redis(<br/>
&nbsp;&nbsp;&nbsp;&nbsp;    redis_url="redis://localhost:6379", <br/>
&nbsp;&nbsp;&nbsp;&nbsp; index_name="test_1", <br/>
&nbsp;&nbsp;&nbsp;&nbsp; embedding_function=embedding.embed_query<br/>
)
</p>
# Load pdf 
loader = PyPDFLoader( file_path)
docs= loader.load_and_split()
redis_vector_db.add_documents(docs, index_name = "test_1")

# Searching --> bug here
docs = redis_vector_db.similarity_search(query = question,k = 4)
-------------------------- This is the end of python script ---------------------------------------

### Expected behavior

# Bug:  Even though we have set the index name  it will have bug of no such index
File [c:\Users\User\anaconda3\envs\advantech\lib\site-packages\langchain\vectorstores\redis.py:284](file:///C:/Users/User/anaconda3/envs/advantech/lib/site-packages/langchain/vectorstores/redis.py:284), in Redis.similarity_search(self, query, k, **kwargs)
    271 def similarity_search(
    272     self, query: str, k: int = 4, **kwargs: Any
    273 ) -> List[Document]:
    274     """
    275     Returns the most similar indexed documents to the query text.
    276 
   (...)
    282         List[Document]: A list of documents that are most similar to the query text.
    283     """
--> 284     docs_and_scores = self.similarity_search_with_score(query, k=k)
    285     return [doc for doc, _ in docs_and_scores]

File [c:\Users\User\anaconda3\envs\advantech\lib\site-packages\langchain\vectorstores\redis.py:361](file:///C:/Users/User/anaconda3/envs/advantech/lib/site-packages/langchain/vectorstores/redis.py:361), in Redis.similarity_search_with_score(self, query, k)
    354 params_dict: Mapping[str, str] = {
    355     "vector": np.array(embedding)  # type: ignore
...
    904 if isinstance(response, ResponseError):
--> 905     raise response
    906 return response

ResponseError: test_1: no such index

# My observation
print(redis_vector_db.index_name)
will show test_1

**Comment by Spartee** [comment]
Need to call ``From_documents``. ``add_documents`` adds to an existing index. I do believe this error is better now.

**Comment by baskaryan** [comment]
any argument to be made that init and from_documents should behave the same re initializing index if it doesn't exist? cc @eyurtsev

**Comment by Spartee** [comment]
``from_documents`` does re-init an index if it doesn't exist.... direct ``init`` does not because ``from_existing`` relies on that.

The workflow is 
1. use one of the class methods ex. ``from_documents``
2. use it

and then to add to existing
1. use ``from_existing``
2. use ``add_documents`` as necessary
3. use it.

right? am I missing something?

**Comment by Spartee** [comment]
@baskaryan I believe your latest PR solves these concerns.
