### ISSUE TITLE
Expose x-ratelimit-* headers from OpenAI API with Langchain

### ISSUE THREAD

**Issue by anaelmashinsky** [langchain-ai/langchain#9601]
### Describe the feature or improvement you're requesting

When making a direct call to OpenAI's POST /v1/chat/completions endpoint, we receive valuable headers that provide information about the rate limiting, including:

```
x-ratelimit-limit-requests: 3500
x-ratelimit-remaining-requests: 3499
x-ratelimit-reset-requests: 17ms
```
However, when using the `ChatOpenAI` and `OpenAIEmbeddings` APIs, these rate limit headers are not returned in the response or as part of the `OpenAICallbackHandler` object (as total_tokens or total_cost values). This makes it challenging to track and manage rate limits programmatically.

Can we get rate headers values using `ChatOpenAI` and `OpenAIEmbeddings`?

It would be nice if we could get access to these headers, or have them returned in a helpful format along with the response.

### Motivation

Having access to rate limit information is crucial for developers to effectively manage their API usage, especially when using these APIs in production environments. This addition would greatly enhance the usability and monitoring capabilities of the OpenAI API.

**Comment by kalanchoej** [comment]
This is very much needed, especially with how small the rate limits are with OpenAI and GPT4. 

Adding that the complete list of headers is:

```
x-ratelimit-limit-requests 
x-ratelimit-limit-tokens
x-ratelimit-remaining-requests
x-ratelimit-remaining-tokens
x-ratelimit-reset-requests
x-ratelimit-reset-tokens
```

All seem valuable.

**Comment by rudyrdx** [comment]
Any progress on this ?

**Comment by ForrestTrepte** [comment]
I notice that the openai package now supports returning these headers via a with_raw_response object as described [here](https://github.com/openai/openai-python/issues/416#issuecomment-1795428669). So, in theory, langchain could call openai in that way and store the x-ratelimit info with its response.

However, if using these headers is not a common need, there is another way. langchain and openai expose an httpx client object that can be used to intercept requests and save header information. Here is an example of how to do that:

```
import httpx
from langchain_openai import ChatOpenAI

def custom_response_hook(response: httpx.Response) -> None:
    print(f"Received response for {response.url}: {response.status_code}")
    assert "x-ratelimit-limit-requests" in response.headers


def test_intercept_http():
    # Create an httpx client instance with the `event_hooks` configured to use our custom hook
    http_client = httpx.Client(event_hooks={"response": [custom_response_hook]})
    llm = ChatOpenAI(temperature=0.0, model_name="gpt-4", http_client=http_client)
    result = llm.invoke("What would be a good company name for a company that makes colorful socks?")
```

**Comment by hansvdam** [comment]
I changed the following wrt @ForrestTrepte's approach: I added "request", otherwise things tended to stop working in my case:
`http_client = httpx.Client(event_hooks={"request":[], "response": [custom_response_hook]})`
