### ISSUE TITLE
TypeError: Object of type ConversationalRetrievalChain is not JSON serializable

### ISSUE THREAD

**Issue by JoAmps** [langchain-ai/langchain#9607]
### System Info

langchain==0.0.249

### Who can help?

@hwchase17 @agola11 @eyurtsev 

### Information

- [X] The official example notebooks/scripts
- [x] My own modified scripts

### Related Components

- [x] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.chains import  ConversationalRetrievalChain
qa = ConversationalRetrievalChain.from_llm(with some values such as vector store, memory etc)
now i want to serialize qa, or store it, the key is to be able to store the qa and pass it wherever i want, ideally store it in one endpoint and pass to another endpoint
but i get errors, about not being able to serialize, which makes it difficult
i have tried flask session, json.dumps, pickle, cloud pickle, tried to store in a database etc, still get an error

### Expected behavior

I should be able to serialize or save the QA, so i can pass it from one endpoint to another, to keep user in session, and isolate a user's QA from others

**Comment by JoAmps** [comment]
Key: I am using flask

**Comment by alcatraz47** [comment]
Hi, have you found any solution? I am trying to do almost the same.

**Comment by dragonskyside** [comment]
I have the same issue and keep getting the same error: 
    qa_chain = ConversationalRetrievalChain.from_llm(
    llm, vectordb.as_retriever(search_kwargs={'k': 2}), return_source_documents=True
)
