### ISSUE TITLE
Croma Db Wrapper not considering the **kwargs for quering the collection

### ISSUE THREAD

**Issue by mallepallihimasagar** [langchain-ai/langchain#9611]
### System Info

langchain-0.0.270 

Croma Db Wrapper not considering the **kwargs for querying the collection

Method: similarity_search_with_score
Code : 
results = self.__query_collection(
                query_embeddings=[query_embedding], n_results=k, where=filter
            )

the query collection doesn't uses **kwargs which will be helpful to query the document that contains "string"

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

langchain-0.0.270 

Croma Db Wrapper not considering the **kwargs for querying the collection

Method: similarity_search_with_score
Code : 
results = self.__query_collection(
                query_embeddings=[query_embedding], n_results=k, where=filter
            )

the query collection doesn't uses **kwargs which will be helpful to query the document that contains "string"

### Expected behavior

langchain-0.0.270 

Croma Db Wrapper not considering the **kwargs for querying the collection

Method: similarity_search_with_score
Code : 
results = self.__query_collection(
                query_embeddings=[query_embedding], n_results=k, where=filter
            )

the query collection doesn't uses **kwargs which will be helpful to query the document that contains "string"

**Comment by wukathy21** [comment]
Could you reveal the practical use cases in which you are utilizing Chroma DB and the reasons behind your choice of using Chroma DB as the vector database?
