### ISSUE TITLE
DOC: Langchain Supabase Vectorstore ID Incompatability

### ISSUE THREAD

**Issue by VVoruganti** [langchain-ai/langchain#9624]
### Issue with current documentation:

The current documentation recommends running the following SQL function to create a table and function for using a supabase postgres database as a vector store. 

```postgres
-- Enable the pgvector extension to work with embedding vectors
create extension vector;

-- Create a table to store your documents
create table documents (
  id bigserial primary key,
  content text, -- corresponds to Document.pageContent
  metadata jsonb, -- corresponds to Document.metadata
  embedding vector(1536) -- 1536 works for OpenAI embeddings, change if needed
);

-- Create a function to search for documents
create function match_documents (
  query_embedding vector(1536),
  match_count int default null,
  filter jsonb DEFAULT '{}'
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
```

This creates a table with a column named id of type `bigint`

However when using the `SupabaseVectorStore` class and trying to run methods such as `add_documents` or `add_texts`, an attempt is made to insert `Document` objects into the database. However it uses the uuid generated as the id which is incompatible with the `bigint`  column type resulting in errors such as 

```bash
postgrest.exceptions.APIError: {'code': '22P02', 'details': None, 'hint': None, 'message': 'invalid input syntax for type bigint: "dbf8aa60-8295-450c-83bc-7395e2836a6a"'}
```

### Idea or request for content:

Instead the documentation should recommend using the column type of uuid which is natively supported within supabase

**Comment by wukathy21** [comment]
I apologize for any inconvenience, but could you tell me the reasons behind your decision to use a Postgres database as your vector database instead of opting for vector databases like Milvus or AwDB? What is your actual use case?

**Comment by VVoruganti** [comment]
> I apologize for any inconvenience, but could you tell me the reasons behind your decision to use a Postgres database as your vector database instead of opting for vector databases like Milvus or AwDB? What is your actual use case?

I don't understand the relevance this has too the conversation - this is specifically in regards to documentation surrounding using Postgres as a vectordb

**Comment by wukathy21** [comment]
I've encountered the same issue as well, and it hasn't been resolved yet. So, I wanted to ask, which Vectorstore are you using? I'm wondering if our scenarios are similar and if we can find a solution together.

**Comment by VVoruganti** [comment]
The documentation has been updated and works in the latest edition of the documentation
