### ISSUE TITLE
Monitoring the progress of long running vectorDB index updates

### ISSUE THREAD

**Issue by Kevin-McIsaac** [langchain-ai/langchain#9630]
### Feature request

Add the option to output progress bar Methods that add documents to an index, e.g., `from_documents`. 

### Motivation

Methods that add documents to an index can take a long time to execute, e.g., `from_documents`.  When executing from a notebook or CLI it would be very convenient to be able to track the progressing using something like tqdm.

### Your contribution

No

**Comment by Danouchka** [comment]
+1
