### ISSUE TITLE
DQL DB Langchain : When running an db_run query based on the prompt it should execute sql query only when needed. 

### ISSUE THREAD

**Issue by Mraghuvaran** [langchain-ai/langchain#9686]
![image](https://github.com/langchain-ai/langchain/assets/53115668/70a42838-7758-4c0a-be99-ba41ad861aaf)
 The Prompt was to explain tables in the data. in this case it should query into the SQL database.

**Comment by Mraghuvaran** [comment]
@dosu-bot 

ProgrammingError: (pyodbc.ProgrammingError) ('42000', "[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Parse error at line: 1, column: 1: Incorrect syntax near 'There'. (103010) (SQLExecDirectW)")
[SQL: There is no SQL query needed for this question.

**Comment by jyoti194** [comment]
@dosubot
The question: what is the uan number for AD23010923

SQLQuery:SELECT [EmployeeID], [EmployeeName], [EmployeeEuid]
FROM [EGV_emp_departments_ChatGPT]
WHERE [EmployeeID] = 'AD23010923'
SQLResult: [('AD23010923', 'Suprashwanthan Panneer Selvan', Decimal('7656'))]
Answer:The UAN number for AD23010923 is 7656.
> Finished chain.
The UAN number for AD23010923 is 7656.

here my question is about uan number, as uan number is not present, it should not run any query, but instead giving answer as EmployeeEuid, how make it not to execute the query to give wrong answer
