### ISSUE TITLE
No way to Close an open connection in PGVector.py

### ISSUE THREAD

**Issue by devsaqibijaz** [langchain-ai/langchain#9696]
### Feature request

Initialization with Database Connection: When an instance of the PGVector class is created, it automatically establish a connection with the PostgreSQL Vector database.

Method for Closing Connection: we need to implement a method within the PGVector class that allows you to close the established connection with the PostgreSQL database.

`def __del__(self):
        # Close the session (and thus the connection) when the instance is destroyed.
        self.session.close()`

### Motivation

The problem is, I am unable to close a connection and the pool get overload with multiple connections and hence the service starts throwing error

### Your contribution

I guess, may be.

**Comment by AIApprentice101** [comment]
Also curious about the solution. 
@devsaqibijaz Can you instruct what you ended up doing? Thanks.

**Comment by Sumukh** [comment]
PR for a fix is here #13232 

This resolved the issue for me.

**Comment by Lengo46** [comment]
I still experience this issue, the pgvector connection with PostgreSQL (on Azure) stays open until the server max is reached.

Then it will follow with:

`psql: FATAL: remaining connection slots are reserved for non-replication superuser connections`

langchain-core: 0.3.21
langchain-community: 0.3.8
pgvector: 0.2.5

**Comment by Lengo46** [comment]
@Sumukh should I raise a new issue?

**Comment by Sumukh** [comment]
Is it possible that you are doing something else that is keeping the connections open (or another service is using the connection slots)? Maybe add a print statement to bot the connect and del methods 

I would suggest opening a new issue if you are able to diagnose where the open connections are coming from specifically. 

<img width="577" alt="image" src="https://github.com/user-attachments/assets/dd899f25-b55f-4df6-aca8-f17a369d3eb0" />

**Comment by Lengo46** [comment]
@Sumukh I think if found the problem, the PG Vector file has move to an import from langchain community somewhere since your PR. The langchain community version does not contain your PR: https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/pgvector.py
