### ISSUE TITLE
Calude models not able to output more than 8191 tokens.

### ISSUE THREAD

**Issue by Krobo224** [langchain-ai/langchain#9697]
### System Info

Platform - AWS
Python version: 3.11.4
OS - Mac

### Who can help?

@3coins , @hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

The code sample which produces the bug:

```
body = json.dumps({"prompt": prompt, "max_tokens_to_sample": 8192})
    accept = "application/json"
    contentType = "application/json"

    response_claudeV2 = boto3_bedrock.invoke_model(
        body=body, modelId="anthropic.claude-v2", accept=accept, contentType=contentType
    )
    response_body_claudeV2 = json.loads(response_claudeV2.get("body").read())

    print(response_body_claudeV2.get("completion"))
```

When the above code snippet is executed with boto3_client we get the error:
` botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: 8192 is not less or equal to 8191, please reformat your input and try again.`

As per the doc of anthropic claude the claude-instant can output 9k tokens, claude-v1 can output 12k tokens and claude-v2 can output 12k tokens but when 'max_token_sample' parameter exceeds 8191 values they give the above error.

### Expected behavior

Expected behaviour is that the model should give the output as it can produce max 12K tokens.

**Comment by ben-xl8** [comment]
@Krobo224 Have you found a fix?

**Comment by krrishdholakia** [comment]
Hey @Krobo224 @ben-xl8 this is expected behaviour. 

Anthropic models have max input tokens of 100k, and max output tokens of ~8k.

![codeimage-snippet_21](https://github.com/langchain-ai/langchain/assets/17561003/3354fa01-3039-42cf-b825-60f065566597)

If you want to access this data programmatically, check out [LiteLLM's model map](https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json) + helper functions for accessing this via code: https://docs.litellm.ai/docs/completion/token_usage#7-model_cost

Here's our bedrock-specific docs btw: https://docs.litellm.ai/docs/providers/bedrock

**Comment by ShantanuNair** [comment]
Sad to see how all models' max generation tokens have shrunk. Claude quietly shrunk all the way down to 4096, while openAI's  last model with > 4096 generation token capabilities is already 2 versions old and scheduled for deprecation in June 2024.

**Comment by hteeyeoh** [comment]
Refer to this https://docs.anthropic.com/claude/docs/models-overview, max output state 4k means the model only able to generate 4k token for now. Even though we can parse larger number like 8k in max_tokens argument when instantiate model. Am i correct?
