### ISSUE TITLE
Is there an incremental way to use Embedding to generate a FAISS vector DB or load multiple vectorstores at the same time?

### ISSUE THREAD

**Issue by westlinkin** [langchain-ai/langchain#970]
First of all, langchain ROCKS!

Is there an incremental way to use Embedding to generate a FAISS vector DB if new documents need to be added to the context every week. Or just generate new additional FAISS vector DB each week, use a chain that loads multiple vectorestore at the same time. Currently VectorDBQAWithSourcesChain can only load one vectorstore

**Comment by hwchase17** [comment]
i just added some instructions for adding texts - https://langchain.readthedocs.io/en/latest/modules/utils/combine_docs_examples/vectorstores.html#add-texts

does this help?

**Comment by westlinkin** [comment]
Thanks. This helps a little. but how can I use multiple `vectorstore`s in `VectorDBQAWithSourcesChain.from_llm`?
