### ISSUE TITLE
DOC: Custom Templates issue with Pydantic v2

### ISSUE THREAD

**Issue by maasikai** [langchain-ai/langchain#9702]
### Issue with current documentation:

The "Creating a Custom Prompt Template" documentation is outdated with Pydantic v2.

```
class FunctionExplainerPromptTemplate(StringPromptTemplate, BaseModel):
    """A custom prompt template that takes in the function name as input, and formats the prompt template to provide the source code of the function."""

    @validator("input_variables")
    def validate_input_variables(cls, v):
        """Validate that the input variables are correct."""
        if len(v) != 1 or "function_name" not in v:
            raise ValueError("function_name must be the only input_variable.")
        return v
```
        
The above code raises following TypeError:

```
>   class FunctionExplainerPromptTemplate(StringPromptTemplate, BaseModel):
E   TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

```
Frankly, I have no idea how to get the prompt templates to work with new Pydantic, even after changing @validator to @field_validator.

### Idea or request for content:

Update the documentation to include new version of Pydantic in examples.

**Comment by maasikai** [comment]
@dosu-bot Your answer still has the metaclass issue that raises from using both StringPromptTemplate and BaseModel.

**Comment by KubaSzarpak** [comment]
I had the same problem. Is there a better and simpler way to create custom prompt template?

**Comment by maasikai** [comment]
> I had the same problem. Is there a better and simpler way to create custom prompt template?

At least I haven't found any way to solve this without rewriting some parts of langchain.

**Comment by Meghansh-Maurya** [comment]
`import inspect
import types
import builtins  # Used instead of __builtin__ in Python 3

############## preliminary: two utility functions #####################

def skip_redundant(iterable, skipset=None):
    "Redundant items are repeated items or items in the original skipset."
    if skipset is None:
        skipset = set()
    for item in iterable:
        if item not in skipset:
            skipset.add(item)
            yield item

def remove_redundant(metaclasses):
    skipset = set([types.ClassType])
    for meta in metaclasses:  # determines the metaclasses to be skipped
        skipset.update(inspect.getmro(meta)[1:])
    return tuple(skip_redundant(metaclasses, skipset))

##################################################################
## now the core of the module: two mutually recursive functions ##
##################################################################

memoized_metaclasses_map = {}

def get_noconflict_metaclass(bases, left_metas, right_metas):
    """Not intended to be used outside of this module, unless you know
    what you are doing."""
    # make tuple of needed metaclasses in specified priority order
    metas = left_metas + tuple(map(type, bases)) + right_metas
    needed_metas = remove_redundant(metas)

    # return existing conflict-solving meta, if any
    if needed_metas in memoized_metaclasses_map:
        return memoized_metaclasses_map[needed_metas]
    # nope: compute, memoize and return needed conflict-solving meta
    elif not needed_metas:  # wee, a trivial case, happy us
        meta = type
    elif len(needed_metas) == 1:  # another trivial case
        meta = needed_metas[0]
    # check for recursion, can happen i.e. for Zope ExtensionClasses
    elif needed_metas == bases:
        raise TypeError("Incompatible root metatypes", needed_metas)
    else:  # gotta work ...
        metaname = '_' + ''.join([m.__name__ for m in needed_metas])
        meta = classmaker()(metaname, needed_metas, {})
    memoized_metaclasses_map[needed_metas] = meta
    return meta

def classmaker(left_metas=(), right_metas=()):
    def make_class(name, bases, adict):
        metaclass = get_noconflict_metaclass(bases, left_metas, right_metas)
        return metaclass(name, bases, adict)
    return make_class

`
Paste this code in new python file and import classmaker function and use this function like I have given below:
`from noconflict import classmaker
class BabyAGI(Chain, BaseModel):
    __metaclass__=classmaker()
`
If using jupyter code paste this code above class Babyagi and use classmaker function like given above

**Comment by 1openwindow** [comment]
save issue. any solution?

**Comment by Meghansh-Maurya** [comment]
> save issue. any solution?

https://github.com/langchain-ai/langchain/issues/9702#issuecomment-1696075253

Check out my above comment, I was also facing the same error and I have solved the issue.

**Comment by Babakjfard** [comment]
@Meghansh-Maurya in your solution, what is `Chain` in:

`class your_class(Chain, BaseModel):
    __metaclass__=classmaker()`

**Comment by Meghansh-Maurya** [comment]
> @Meghansh-Maurya in your solution, what is `Chain` in:
> 
> `class your_class(Chain, BaseModel):`

from pydantic import BaseModel, Field
from langchain.chains.base import Chain

From here I have got both these Chain and BaseModel.

**Comment by Meghansh-Maurya** [comment]
> @Meghansh-Maurya in your solution, what is `Chain` in:
> 
> `class your_class(Chain, BaseModel):`

You have to use your own classes according to your use cases

**Comment by Babakjfard** [comment]
Thank you for getting back to me. I used your code and tested the following code as a use case. It gives the same error message of metaclass conflict.  The problem is that it does not even move into the second line of the class construction to call your function and creates the error on the class call line.

`
from pydantic import BaseModel
from langchain.prompts import StringPromptTemplate

class FunctionExplainerPromptTemplate(StringPromptTemplate, BaseModel):
    __metaclass__=classmaker()

    #Remaining code ........
`

**Comment by sameergupta-11** [comment]
@Babakjfard Facing the same issue

**Comment by mrenner-ML** [comment]
Facing the same issue

**Comment by doodleEsc** [comment]
my solution is using pydantic 1.10.12
works fine

**Comment by prashanthi-instalily** [comment]
> my solution is using pydantic 1.10.12 works fine

this worked for me!

**Comment by srivatsabc** [comment]
from langchain.prompts import StringPromptTemplate
from pydantic import v1 as pydantic_v1

PROMPT = """\
Given the function name and source code, generate an English language explanation of the function.
Function Name: {function_name}
Source Code:
{source_code}
Explanation:
"""


class FunctionExplainerPromptTemplate(StringPromptTemplate, pydantic_v1.BaseModel):
    """A custom prompt template that takes in the function name as input, and formats the prompt template to provide the source code of the function."""

    @pydantic_v1.validator("input_variables")
    def validate_input_variables(cls, v):
        """Validate that the input variables are correct."""
        if len(v) != 1 or "function_name" not in v:
            raise ValueError("function_name must be the only input_variable.")
        return v

    def format(self, **kwargs) -> str:
        # Get the source code of the function
        source_code = get_source_code(kwargs["function_name"])

        # Generate the prompt to be sent to the language model
        prompt = PROMPT.format(
            function_name=kwargs["function_name"].__name__, source_code=source_code
        )
        return prompt

    def _prompt_type(self):
        return "function-explainer"

**Comment by srivatsabc** [comment]
I continued with pydantic 2.4.2 and did a little cheat seeing the pip install page info

```
PROMPT = """\
Given the function name and source code, generate an English language explanation of the function.
Function Name: {function_name}
Source Code:
{source_code}
Explanation:
"""

from langchain.prompts import StringPromptTemplate
from pydantic import v1 as pydantic_v1

class FunctionExplainerPromptTemplate(StringPromptTemplate, pydantic_v1.BaseModel):
    @pydantic_v1.validator("input_variables")
    def validate_input_variables(cls, v):
        """Validate that the input variables are correct."""
        if len(v) != 1 or "function_name" not in v:
            raise ValueError("function_name must be the only input_variable.")
        return v

    def format(self, **kwargs) -> str:
        # Get the source code of the function
        source_code = get_source_code(kwargs["function_name"])

        # Generate the prompt to be sent to the language model
        prompt = PROMPT.format(
            function_name=kwargs["function_name"].__name__, source_code=source_code
        )
        return prompt

    def _prompt_type(self):
        return "function-explainer"
```
