### ISSUE TITLE
Pgvector support to filter by List

### ISSUE THREAD

**Issue by MichaelPeterJoyce** [langchain-ai/langchain#9726]
### Feature request

Hi there, 

Currently using PGVector you can pass a filter object. But this filter object only allows key value pairs. 

`Dict[str, str]. 
`
I am requesting the ability to also send a list of strings for easy filter across many pieces of data.

`Dict[str, list[str]]
`
### Motivation

I have a lot of Data with Metadata that contains content type. 

I would like to provide a list of content types to PGvector and allow it to filter and return content from multiple types.

### Your contribution

N/A

**Comment by kaikun213** [comment]
Looking at the source code, there seems to be some undocumented support using the `in` keyword? I.e. `{ "filter_key": { "in": ["val1", "val2"]} `

```python
    def similarity_search_with_score_by_vector(
        self,
        embedding: List[float],
        k: int = 4,
        filter: Optional[dict] = None,
    ) -> List[Tuple[Document, float]]:
        with Session(self._conn) as session:
            collection = self.get_collection(session)
            if not collection:
                raise ValueError("Collection not found")

            filter_by = self.EmbeddingStore.collection_id == collection.uuid

            if filter is not None:
                filter_clauses = []
                for key, value in filter.items():
                    IN = "in"
                    if isinstance(value, dict) and IN in map(str.lower, value):
                        value_case_insensitive = {
                            k.lower(): v for k, v in value.items()
                        }
                        filter_by_metadata = self.EmbeddingStore.cmetadata[
                            key
                        ].astext.in_(value_case_insensitive[IN])
                        filter_clauses.append(filter_by_metadata)
                    else:
                        filter_by_metadata = self.EmbeddingStore.cmetadata[
                            key
                        ].astext == str(value)
                        filter_clauses.append(filter_by_metadata)
...
```

Haven't tested it though.

**Comment by MichaelPeterJoyce** [comment]
> 

@kaikun213 This works! 

`search_kwargs={'filter': { 'locale': 'en-US', "type": {"in": ["TYPE1", "TYPE2"]} `

Thank you so much for having a look and spotting this!
