### ISSUE TITLE
DirectoryLoader for different file types

### ISSUE THREAD

**Issue by nima-cp** [langchain-ai/langchain#9749]
### Discussed in https://github.com/langchain-ai/langchain/discussions/9605

<div type='discussions-op-text'>

<sup>Originally posted by **nima-cp** August 22, 2023</sup>
Hello everyone, I wanna have a Q&A over some documents including pdf, xml and csv. I'm having some difficulty to write a DirectoryLoader for different types of files in a folder. I'm using Chroma and couldn't find a way to solve this. However, I found this in TS documentation:

```typescript
   const directoryLoader = new DirectoryLoader(filePath, {
      '.pdf': (path) => new PDFLoader(path, { splitPages: true }),
      '.docx': (path) => new DocxLoader(path),
      '.json': (path) => new JSONLoader(path, '/texts'),
      '.jsonl': (path) => new JSONLinesLoader(path, '/html'),
      '.txt': (path) => new TextLoader(path),
      '.csv': (path) => new CSVLoader(path, 'text'),
      '.htm': (path) => new UnstructuredLoader(path),
      '.html': (path) => new UnstructuredLoader(path),
      '.ppt': (path) => new UnstructuredLoader(path),
      '.pptx': (path) => new UnstructuredLoader(path),
    });
```
How can I write the same in Python?

```python
loader = DirectoryLoader(
    filePath,
    glob="./*.pdf",
    loader_cls=PyMuPDFLoader,
    show_progress=True,
)
```</div>

**Comment by batjko** [comment]
And, for completeness since the original example is from the JS docs, how can the JS version of the DirectoryLoader use a glob pattern?

For example, I'd like to be able to use the `new DirectoryLoader()` call to be able to take a glob pattern so I can exclude files or folders from the load. The docs are not clear at the moment that this is not possible, the two versions are far from equivalent, it seems.

**Comment by raminmardani** [comment]
```
from langchain_community.document_loaders import WebBaseLoader

loader_web = WebBaseLoader(
    "https://github.com/basecamp/handbook/blob/master/37signals-is-you.md"
)

from langchain_community.document_loaders import PyPDFLoader

loader_pdf = PyPDFLoader("../MachineLearning-Lecture01.pdf")

from langchain_community.document_loaders.merge import MergedDataLoader

loader_all = MergedDataLoader(loaders=[loader_web, loader_pdf])

docs_all = loader_all.load()

len(docs_all)
```

**Comment by Andiezz** [comment]
> you should load the files separately and then merging them in this way:
> 
> ```
> from langchain_community.document_loaders import WebBaseLoader
> 
> loader_web = WebBaseLoader(
>     "https://github.com/basecamp/handbook/blob/master/37signals-is-you.md"
> )
> 
> from langchain_community.document_loaders import PyPDFLoader
> 
> loader_pdf = PyPDFLoader("../MachineLearning-Lecture01.pdf")
> 
> from langchain_community.document_loaders.merge import MergedDataLoader
> 
> loader_all = MergedDataLoader(loaders=[loader_web, loader_pdf])
> 
> docs_all = loader_all.load()
> 
> len(docs_all)
> ```

Using MergedDataLoader works like charm!
