### ISSUE TITLE
DOC: How to Connect Database Agent with SqlServer

### ISSUE THREAD

**Issue by programmersEmperor** [langchain-ai/langchain#9804]
### Issue with current documentation:

from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI
from langchain.agents import AgentExecutor
from langchain.agents.agent_types import AgentType
from langchain.chat_models import ChatOpenAI

db = SQLDatabase.from_uri("sqlite:///../../../../../notebooks/Chinook.db")
toolkit = SQLDatabaseToolkit(db=db, llm=OpenAI(temperature=0))

# how to connect to sql server instead of sqlite???

### Idea or request for content:

I need to connect with my sqlserver database, but the documention does not explain how to connect langchain database agent to sqlserver.

**Comment by programmersEmperor** [comment]
Ok this code like good to me: 
`db = SQLDatabase.from_uri("mssql+pyodbc://username:password@dsnname")
`
but I dont have username or password in my sql server?

can you show my how that code will be without username and password?

**Comment by programmersEmperor** [comment]
> _🤖_
> 
> Hello,
> 
> To connect LangChain with a SQL Server database, you would need to modify the connection string in the `from_uri` method of the `SQLDatabase` class. The connection string for a SQL Server database typically follows this format:
> 
> ```python
> mssql+pyodbc://<username>:<password>@<dsnname>
> ```
> 
> or
> 
> ```python
> mssql+pyodbc://<username>:<password>@<host>:<port>/<database>?driver=ODBC+Driver+17+for+SQL+Server
> ```
> 
> So, your code would look something like this:
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://username:password@dsnname")
> ```
> 
> or
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://username:password@host:port/database?driver=ODBC+Driver+17+for+SQL+Server")
> ```
> 
> Please replace `<username>`, `<password>`, `<dsnname>`, `<host>`, `<port>`, and `<database>` with your actual SQL Server credentials.
> 
> Please note that you would need to have the `pyodbc` package installed in your environment, and an appropriate ODBC driver installed on your machine to connect to the SQL Server database.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [libs/langchain/langchain/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Ok @dosu-beta this code like good to me:
db = SQLDatabase.from_uri("mssql+pyodbc://username:password@dsnname") 
but I dont have username or password in my sql server?

can you show my how that code will be without username and password?

**Comment by sruthivijay** [comment]
db = create_engine("mssql+pyodbc:///?odbc_connect=Driver={ODBC Driver 17 for SQL Server};Server=tcp:XXXX,1433;Database=XXXX;Uid=wolfadmin;Pwd=XXXX;MARS_Connection=Yes;").. This works, but when i try the same with db = SQLDatabase.from_uri("mssql+pyodbc:///?odbc_connect=Driver={ODBC Driver 17 for SQL Server};Server=tcp:XXXX,1433;Database=XXXX;Uid=wolfadmin;Pwd=XXXX;MARS_Connection=Yes;")..this just runs forever, no output nothing..can you suggest me what to do ?

**Comment by raghav-mundhra** [comment]
I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
1. Can we connect to a different schema instead of dbo?
2. Can we utilize tables from multiple schemas to generate the response?

**Comment by programmersEmperor** [comment]
> _🤖_
> 
> To connect to a SQL Server using LangChain without a username and password, you can modify the connection string in the `from_uri` method of the `SQLDatabase` class. If your SQL Server does not require a username and password, you can omit them from the connection string. Here's how you can do it:
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<dsnname>")
> ```
> 
> or
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<host>:<port>/<database>?driver=ODBC+Driver+17+for+SQL+Server")
> ```
> 
> Please replace `<dsnname>`, `<host>`, `<port>`, and `<database>` with your actual SQL Server details.
> 
> Regarding your second question, to specify the schemas from which the database agent should pick resources, you can use the `include_schemas` parameter when creating the `SQLDatabase` instance. Here's an example:
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<dsnname>", include_schemas=['schema1', 'schema2'])
> ```
> 
> Please replace `'schema1'` and `'schema2'` with the names of the schemas you want to include.
> 
> Please note that connecting to a SQL Server without a username and password might not be recommended due to security reasons. It's usually better to use some form of authentication when connecting to your database.
> 
> Also, the connection string format and the driver name might vary depending on your SQL Server version and the specific ODBC driver you have installed on your machine.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> Sources:
> 
> * [libs/langchain/langchain/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
> 
> ## Sources
> * [libs/community/langchain_community/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

What about if I want to connect it with MySql instead of Sql Server?
what would the code look like?

**Comment by raghav-mundhra** [comment]
> > I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
> 
> Try the following code, and let me know the result `db = SQLDatabase.from_uri(conn, include_schemas=['schema1', 'schema2'])`

Tried this code. It's giving out this error:

```
TypeError                                 Traceback (most recent call last)
Cell In[3], [line 7](vscode-notebook-cell:?execution_count=3&line=7)
      [1](vscode-notebook-cell:?execution_count=3&line=1) # import sqlalchemy
      [2](vscode-notebook-cell:?execution_count=3&line=2) # # db_engine = sqlalchemy.create_engine("mssql+pyodbc://M61Engine_RW:XLs3r^eB=Fxb`6B@m61engine.database.windows.net/M61EngineDBDev")
      [3](vscode-notebook-cell:?execution_count=3&line=3) 
      [4](vscode-notebook-cell:?execution_count=3&line=4) # mssql_engine = sqlalchemy.create_engine(
      [5](vscode-notebook-cell:?execution_count=3&line=5) #     "mssql+pyodbc://M61Engine_RW:XLs3r^eB=Fxb`6B@m61engine.database.windows.net:1433/M61EngineDBDev?driver=SQL Server",)
----> [7](vscode-notebook-cell:?execution_count=3&line=7) db = SQLDatabase.from_uri("mssql+pyodbc://Cres4_dev:h9[WEhu})WvWuP)@b0xesubcki1.database.windows.net/Cres4_dev?driver=SQL Server", include_schemas=['cre', 'core'])
      [8](vscode-notebook-cell:?execution_count=3&line=8) # db_engine = SQLDatabase.create_engine("mssql+pyodbc://CRES4_Hbot_Reader:uW})Sh9vuWuP)[WEh#@b0xesubcki1.database.windows.net/CRES4_Hbot_QA?driver=ODBC+Driver+17+for+SQL+Server")
      [9](vscode-notebook-cell:?execution_count=3&line=9) # SQLDatabase.

File [d:\EntityExtraction\.venv\lib\site-packages\langchain_community\utilities\sql_database.py:124](file:///D:/EntityExtraction/.venv/lib/site-packages/langchain_community/utilities/sql_database.py:124), in SQLDatabase.from_uri(cls, database_uri, engine_args, **kwargs)
    [122](file:///D:/EntityExtraction/.venv/lib/site-packages/langchain_community/utilities/sql_database.py:122) """Construct a SQLAlchemy engine from URI."""
    [123](file:///D:/EntityExtraction/.venv/lib/site-packages/langchain_community/utilities/sql_database.py:123) _engine_args = engine_args or {}
--> [124](file:///D:/EntityExtraction/.venv/lib/site-packages/langchain_community/utilities/sql_database.py:124) return cls(create_engine(database_uri, **_engine_args), **kwargs)

TypeError: SQLDatabase.__init__() got an unexpected keyword argument 'include_schemas'
```

**Comment by raghav-mundhra** [comment]
> > I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
> 
> Try the following code, and let me know the result `db = SQLDatabase.from_uri(conn, include_schemas=['schema1', 'schema2'])`

Tried this code. It's giving this error:

`TypeError: SQLDatabase.__init__() got an unexpected keyword argument 'include_schemas'`

This is the code piece U ran:
`db = SQLDatabase.from_uri("mssql+pyodbc://user:password@uri/db_name?driver=SQL Server", include_schemas=['schema1', 'schema2'])`

**Comment by raghav-mundhra** [comment]
> _🤖_
> 
> To connect to a SQL Server using LangChain without a username and password, you can modify the connection string in the `from_uri` method of the `SQLDatabase` class. If your SQL Server does not require a username and password, you can omit them from the connection string. Here's how you can do it:
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<dsnname>")
> ```
> 
> or
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<host>:<port>/<database>?driver=ODBC+Driver+17+for+SQL+Server")
> ```
> 
> Please replace `<dsnname>`, `<host>`, `<port>`, and `<database>` with your actual SQL Server details.
> 
> Regarding your second question, to specify the schemas from which the database agent should pick resources, you can use the `include_schemas` parameter when creating the `SQLDatabase` instance. Here's an example:
> 
> ```python
> db = SQLDatabase.from_uri("mssql+pyodbc://@<dsnname>", include_schemas=['schema1', 'schema2'])
> ```
> 
> Please replace `'schema1'` and `'schema2'` with the names of the schemas you want to include.
> 
> Please note that connecting to a SQL Server without a username and password might not be recommended due to security reasons. It's usually better to use some form of authentication when connecting to your database.
> 
> Also, the connection string format and the driver name might vary depending on your SQL Server version and the specific ODBC driver you have installed on your machine.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> Sources:
> 
> * [libs/langchain/langchain/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.
> 
> ## Sources
> * [libs/community/langchain_community/utilities/sql_database.py](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/utilities/sql_database.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot , When I try to use 'include_schemas'  while creating `SQLDatabase` instance, it throws this error:

`TypeError: SQLDatabase.__init__() got an unexpected keyword argument 'include_schemas'`

**Comment by subasah** [comment]
> I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
> 
> 1. Can we connect to a different schema instead of dbo?
> 2. Can we utilize tables from multiple schemas to generate the response?

Hey @raghav-mundhra how did you solve this, I am facing the similar issue?

**Comment by raghav-mundhra** [comment]
> > I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
> > 
> > 1. Can we connect to a different schema instead of dbo?
> > 2. Can we utilize tables from multiple schemas to generate the response?
> 
> Hey @raghav-mundhra how did you solve this, I am facing the similar issue?

Still couldn't find a solution to this. But if you only have limited number of tables, you can specify the table names with their schema (schema.table) and the model will work on only those tables.

**Comment by KallieLev** [comment]
I encountered the same issue, what worked for me was to set - `db = SQLDatabase.from_uri(connection_string, lazy_table_reflection=True)`.
The issue for me was that I had many tables in the DB (about 200), and it got stuck on [reflecting](https://docs.sqlalchemy.org/en/20/core/reflection.html) all tables (retrieving the schema for all tables), and because the amount of tables is big, it took a lot of time.

**Comment by Muthusivam-saip** [comment]
guys since im having tcp:servername:port in the string , the module takes servername as port and throughs error 


ValueError: invalid literal for int() with base 10: can somebody help me withthis

**Comment by KodumuruRaja1999** [comment]
> > > I am able to successfully connect to SQL Server but I found that the db agent only picks resources/tables from the "dbo" schema to run the queries. I have two questions:
> > > 
> > > 1. Can we connect to a different schema instead of dbo?
> > > 2. Can we utilize tables from multiple schemas to generate the response?
> > 
> > 
> > Hey @raghav-mundhra how did you solve this, I am facing the similar issue?
> 
> Still couldn't find a solution to this. But if you only have limited number of tables, you can specify the table names with their schema (schema.table) and the model will work on only those tables.

@raghav-mundhra It is running continuously without any output. If anyone knows help me

**Comment by BishalPoudel149** [comment]
Need to connect to specific schemas, without being properly solved it seems issue got closed

**Comment by yashprakashsharma** [comment]
Hi all, I also have similar issue posted here: https://repost.aws/questions/QUXtaPsrCaSTGmmZfgU_gcYQ/sagemaker-notebook-to-rds-ms-sql-server-web-edition-connection-issue-using-sqldatabase-from-langchain-community-utilities
