### ISSUE TITLE
ImportError: cannot import name 'StreamlitCallbackHandler' from 'langchain.callbacks' 

### ISSUE THREAD

**Issue by shawnesquivel** [langchain-ai/langchain#9811]
### System Info

**Background**
I'm trying to run the Streamlit Callbacks example

https://python.langchain.com/docs/integrations/callbacks/streamlit

My code is copy + paste but I get an error from the LangChain library import.

**Error**
```
ImportError: cannot import name 'StreamlitCallbackHandler' from 'langchain.callbacks' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/callbacks/__init__.py)
```

**What I tried**
- Upgrading LangChain `pip install langchain --upgrade`
- Reinstall `pip uninstall langchain` then `pip install langchain`

**Version**
langchain 0.0.274                 
streamlit 1.24.1 

**System**
Mac M2 Ventura –13.4.1 

### Who can help?

@hwchase17 

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Run the code snippet `streamlit run app.py`
2. Error message

**Run the code with `streamlit run app.py`**
```
import streamlit as st
from langchain.llms import OpenAI
from langchain.agents import AgentType, initialize_agent, load_tools
from langchain.callbacks import StreamlitCallbackHandler

from dotenv import find_dotenv, load_dotenv
load_dotenv(find_dotenv())

st_callback = StreamlitCallbackHandler(st.container())

llm = OpenAI(temperature=0, streaming=True)
tools = load_tools(["ddg-search"])
agent = initialize_agent(
    tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, verbose=True
)

if prompt := st.chat_input():
    st.chat_message("user").write(prompt)
    with st.chat_message("assistant"):
        st_callback = StreamlitCallbackHandler(st.container())
        response = agent.run(prompt, callbacks=[st_callback])
        st.write(response)
```

### Expected behavior

Should look like the tutorial

<img width="844" alt="image" src="https://github.com/langchain-ai/langchain/assets/94336773/f5a5f166-4013-4c2b-9776-b268156c41f8">

**Comment by shawnesquivel** [comment]
Seems to work now, not sure the fix but I switched to a home wifi and that may have made things work.

**Comment by amjadraza** [comment]
I had the same issue with `version=0.0294`, solved using below. Looks like the CallBack `__init__` somehoe missing streamlit call back as default. 

Solved using below 

`from langchain.callbacks.streamlit import StreamlitCallbackHandler`

Code from `lanhchain.callback.__init__.py`

```
""Callback handlers that allow listening to events in LangChain."""

from langchain.callbacks.aim_callback import AimCallbackHandler
from langchain.callbacks.argilla_callback import ArgillaCallbackHandler
from langchain.callbacks.clearml_callback import ClearMLCallbackHandler
from langchain.callbacks.comet_ml_callback import CometCallbackHandler
from langchain.callbacks.file import FileCallbackHandler
from langchain.callbacks.human import HumanApprovalCallbackHandler
from langchain.callbacks.manager import (
    get_openai_callback,
    tracing_enabled,
    wandb_tracing_enabled,
)
from langchain.callbacks.mlflow_callback import MlflowCallbackHandler
from langchain.callbacks.openai_info import OpenAICallbackHandler
from langchain.callbacks.stdout import StdOutCallbackHandler
from langchain.callbacks.streaming_aiter import AsyncIteratorCallbackHandler
from langchain.callbacks.wandb_callback import WandbCallbackHandler
from langchain.callbacks.whylabs_callback import WhyLabsCallbackHandler

__all__ = [
    "ArgillaCallbackHandler",
    "OpenAICallbackHandler",
    "StdOutCallbackHandler",
    "FileCallbackHandler",
    "AimCallbackHandler",
    "WandbCallbackHandler",
    "MlflowCallbackHandler",
    "ClearMLCallbackHandler",
    "CometCallbackHandler",
    "WhyLabsCallbackHandler",
    "AsyncIteratorCallbackHandler",
    "get_openai_callback",
    "tracing_enabled",
    "wandb_tracing_enabled",
    "HumanApprovalCallbackHandler",
]
```
