### ISSUE TITLE
Issue: Help to make a callback for Elevenlabs API streaming endpoint

### ISSUE THREAD

**Issue by ChristianEvc** [langchain-ai/langchain#9822]
Hi, 

I'm hoping someone smarter than me can help me understand how to write a callback that works with Elevenlabs.

I'm trying to get Elevenlabs to stream TTS based on a response from the GPT-4 API. I can do this easily using OpenAIs own libarary, but I cannot figure out how to do this using langchains callbacks instead. 

Here is the working code for the OpenAI library (without the various imports etc).

```
def write(prompt: str):
    for chunk in openai.ChatCompletion.create(
        model = "gpt-4",
        messages = [{"role":"user","content": prompt}],
        stream=True,
    ):
        content = chunk["choices"][0].get("delta", {}).get("content")
        if content is not None:
            yield content
            print("ContentTester:", content)

promtp = "Say a long sentence"

text_stream = write(wife)

audio_stream = elevenlabs.generate(
    text=text_stream,
    voice="adam",
    stream=True,
    latency=3,
)

output = elevenlabs.stream(audio_stream)
```

I think I need to use an Async callback, but I can't get it to work. I've tried simply adding the following custom callback, but it doesn't work.

```
class MyStreamingResonseHandler(StreamingStdOutCallbackHandler):
    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        yield token
```

The idea is to replicate what this part does as a callback:
```
        content = chunk["choices"][0].get("delta", {}).get("content")
        if content is not None:
            yield content
            print("ContentTester:", content)
            
```

This is probably a trivial thing to solve for someone more experienced, but I can't figure it out. Any help would be greatly appreciated!!

**Comment by keenborder786** [comment]
@ChristianEvc , I will be happy to have a look at it. Please give me some time.

**Comment by keenborder786** [comment]
Just one thing did you try see the following: https://python.langchain.com/docs/modules/callbacks/custom_callbacks

**Comment by hinthornw** [comment]
Could also use `model.stream()`

**Comment by hinthornw** [comment]
```
from langchain import chat_models, prompts
from langchain.schema.output_parser import StrOutputParser

import elevenlabs

prompt = prompts.ChatPromptTemplate.from_messages(
    [
        ("system", "You are an operetic singer who sings all responses."),
        ("human", "{input}"),
    ]
)

chain = prompt | chat_models.ChatOpenAI() | StrOutputParser()


def synthesize_voice(request: str):
    text_stream = chain.stream({"input": request})
    audio_stream = elevenlabs.generate(
        text=text_stream,
        # voice="adam",
        stream=True,
        latency=3,
    )
    return elevenlabs.stream(audio_stream)


```

This works fo rme

**Comment by ChristianEvc** [comment]
@keenborder786 thanks very much, this look promising! I’ll take a look and let you know hownit goes.
@hinthornw thanks for the suggestion as well, I’ll give this a shot too. I assume this would work with any chain type? Or only specific chains? I’ll be using a ConversationalChain :)

**Comment by ChristianEvc** [comment]
@keenborder786 Just looked through your link in detail now, and I have looked at that, but can't get it to work as a stream. It always waits for the output from the chain to complete before the audio starts.

@hinthornw I have yet to test your suggestion, but am about to shortly.

**Comment by ChristianEvc** [comment]
@hinthornw I'm afraid I can't get yours to work. Which version on you on? The "from langchain.schema.output_parser import StrOutputParser" doesn't seem to exist anymore, and there is no Output parser called StrOutputParser anymore it seems. Any ideas?

**Comment by agilebean** [comment]
From the langchain documentation, the best way would be:

1. instantiate the OpenAI model as a langchain class with `ChatOpenAI`
2. from this langchain `ChatOpenAI` model, call either
a. `stream` for synchronous streaming
b. `astream` for asynchronous streaming

No need for a callback manager with this solution.
