### ISSUE TITLE
DOC: Import path for NewsURLLoader needs to fixed

### ISSUE THREAD

**Issue by z4forzubair** [langchain-ai/langchain#9825]
### Issue with current documentation:

At https://python.langchain.com/docs/integrations/document_loaders/news, there is an issue with the path for importing `NewsURLLoader`. Currently, it's being imported from `from langchain.document_loaders`, but it gives `importerror`.

### Idea or request for content:

The import path for `NewsURLLoader` needs to be updated. The correct path is `from langchain.document_loaders.news import NewsURLLoader`

**Comment by keenborder786** [comment]
Can you please share the code snippet?  Because it is working fine for me.
