### ISSUE TITLE
Being able to see model's responses when using verbose mode

### ISSUE THREAD

**Issue by kevin-guimard-ext** [langchain-ai/langchain#9842]
### Feature request

Currently, when the _verbose_ attribute is set to True in the constructor of an _LLMChain_ object, only the input passed to the LLM is shown. It would be desirable to also see the raw output of the LLM before it is parsed.

### Motivation

Seeing both inputs and outputs of the LLM would help debug the chain. Exceptions often occur when an output parser is used and the parser throws an exception (because the LLM's output was not in the expected format). In that case one cannot see what the LLM's output was.

### Your contribution

I had a look at the code of LLMChain and it seems that a print (or a callback) could be added in the _call method, between the call to _generate_ and the call to _create_outputs_:
```
    def _call(
        self,
        inputs: Dict[str, Any],
        run_manager: Optional[CallbackManagerForChainRun] = None,
    ) -> Dict[str, str]:
        response = self.generate([inputs], run_manager=run_manager)
        # Add a print/callback here
        return self.create_outputs(response)[0]
```

**Comment by NatanMish** [comment]
@kevin-guimard-ext can you share code that raises such an exception with a parser so we can recreate it?

**Comment by kevin-guimard-ext** [comment]
Well, just add a _raise_ statement in the _parse_ method of the parser... But this was not the point of my request: the problem is that in verbose mode, only the inputs are shown, and not the outputs. I introduced the example of a parser throwing an exception to justify a case when this feature could be useful. There could be others.

**Comment by wnmurphy** [comment]
If you include `import langchain; langchain.debug = True`, you can get more granular information than verbose mode. When I use it with a `MultiPromptChain`, it appears to show the pre-parsed output from the router before going into `RouterOutputParser`; your use case may vary
