### ISSUE TITLE
AWS Sagemaker JS Integration

### ISSUE THREAD

**Issue by maggarwal25** [langchain-ai/langchain#9862]
### System Info

JS LangChain

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

@dosu-bot

I got this error now with my code: ModelError: Received client error (424) from primary with message "{
"code":424,
"message":"prediction failure",
"error":"Need to pass custom_attributes='accept_eula=true' as part of header. This means you have read and accept the end-user license agreement (EULA) of the model. EULA can be found in model card description or from https://ai.meta.com/res

```
const { SageMakerLLMContentHandler, SageMakerEndpoint } = require("langchain/llms/sagemaker_endpoint");
const AWS = require('aws-sdk');

AWS.config.credentials = new AWS.SharedIniFileCredentials({ profile: 'profile' });

class HuggingFaceTextGenerationGPT2ContentHandler {
  constructor(contentHandler) {
    this.contentHandler = contentHandler;
    this.contentType = "application/json";
    this.accepts = "application/json";
  }

  async transformInput(prompt, modelKwargs) {
    const inputString = JSON.stringify({
      text_inputs: prompt,
      ...modelKwargs,
    });
    return Buffer.from(inputString);
  }

  async transformOutput(output) {
    const responseJson = JSON.parse(Buffer.from(output).toString("utf-8"));
    return responseJson.generated_texts[0];
  }
}

const contentHandler = new HuggingFaceTextGenerationGPT2ContentHandler(SageMakerLLMContentHandler);

const model = new SageMakerEndpoint({
  endpointName: "endpointName",
  modelKwargs: { temperature: 1e-10 },
  contentHandler: contentHandler, // Pass the inner contentHandler
  clientOptions: {
    region: "region",
    credentials: AWS.config.credentials,
  },
});

async function main() {
  const res = await model.call("Hello, my name is ");
  console.log({ res });
}

main();


```

Can you show where to add the eula agreement acceptanced parameter

### Expected behavior

I expected it to pass, but it asked me to accept a EULA Agreement. I tried customized arguments but that didn't seem to solve hte issue either

**Comment by chrisr345** [comment]
This fix doesn't seem to work - I am also encountering this same issue with the following code suggested:
```
const awsModel = new SageMakerEndpoint({
      endpointName:
        "endpointname", 
      modelKwargs: { temperature: 0.6 },
      contentHandler,
      clientOptions: 
      {
        region: "us-east-1",
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY,
          secretAccessKey: process.env.AWS_SECRET_KEY,
        },
        customAttributes: 'accept_eula=true'
      },
    });

**Comment by owieboy** [comment]
Hello @chrisr345 , 

I believe the JS version of the class is here: [sagemaker_endpoint.ts](https://github.com/langchain-ai/langchainjs/blob/6e1a112934c2bbeb0bcc610c1a8a5cd2c685c1c7/langchain/src/llms/sagemaker_endpoint.ts).

Basing from the code, the `customAttributes` should be defined as:

```
const awsModel = new SageMakerEndpoint({
      endpointName: "endpointname", 
      modelKwargs: { temperature: 0.6 },
      endpointKwargs: {
        CustomAttributes: "accept_eula=true"
      },
      contentHandler,
      clientOptions: 
      {
        region: "us-east-1",
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY,
          secretAccessKey: process.env.AWS_SECRET_KEY,
        }
      }
});
```

**Comment by YYyp99** [comment]
I also encountered this issue when using Sagemaker's batch transform job, so where should I add this parameter to the batch transform job
