### ISSUE TITLE
llama.cpp does not support AsyncCallbackHandler

### ISSUE THREAD

**Issue by zimmerling** [langchain-ai/langchain#9865]
### System Info

python:3.11.3
langchain: 0.0.274
dist: arch

### Who can help?

```
fastapi==0.103.0
qdrant-client==1.4.0
llama-cpp-python==0.1.72
```

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [X] Callbacks/Tracing
- [X] Async

### Reproduction

Hey @agola11,
I got this runtime warning: 
`python3.11/site-packages/langchain/llms/llamacpp.py:312: RuntimeWarning: coroutine 'AsyncCallbackManagerForLLMRun.on_llm_new_token' was never awaited`

I try to stream over a websocket the generated tokens. When I try to add a `AsyncCallbackHandler` to manage this streaming and run `acall` the warning occurs and nothing is streamed out.

```python
class StreamingLLMCallbackHandler(AsyncCallbackHandler):
    def __init__(self, websocket: WebSocket):
        super().__init__()
        self.websocket = websocket

    async def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        resp = ChatResponse(sender="bot", message=token, type="stream")
        await self.websocket.send_json(resp.dict())


stream_manager = AsyncCallbackManager([StreamingLLMCallbackHandler(websocket)])



llm = return LlamaCpp(
                model_path="models/llama-2-7b-chat.ggmlv3.q2_K.bin",
                verbose=False,
                n_gpu_layers=40,
                n_batch=2048,
                n_ctx=2048,
                callback_manager=stream_manager
            )

qa_chain = RetrievalQA.from_chain_type(llm=llm,
                                       chain_type='stuff',
                                       retriever=vectordb.as_retriever(search_kwargs={'k': 4}),
                                       return_source_documents=True,
                                       chain_type_kwargs={'prompt': prompt}
                                       )

output = await qa_chain.acall(
                {
                    'query': user_msg,
                })
```

### Expected behavior

The expected behavior is that each token is streamed sequentially over the websocket.

**Comment by Zimmerling** [comment]
Hi @dosu-bot, @agola11,

Unfortunately, the answer does not help me and does not solve the problem. [This function](https://github.com/langchain-ai/langchain/blob/2d2b097fab8eb6f3626c86cb958d8cc762257061/libs/langchain/langchain/llms/llamacpp.py#L305) is called by the `acall`. I think the error occurs because [this function call](https://github.com/langchain-ai/langchain/blob/2d2b097fab8eb6f3626c86cb958d8cc762257061/libs/langchain/langchain/llms/llamacpp.py#L352C16-L353C79) is not awaited

**Comment by Zimmerling** [comment]
@agola11 This answer will not solve my issue.

**Comment by emmettprexus** [comment]
+1... I'm experiencing the exact same thing. I'm streaming the generated content over websockets and this issue makes it not as straight forward as it could be unfortunately.

**Comment by DmitryIo** [comment]
Facing the same issue

**Comment by davide-pet** [comment]
@zimmerling same problem here but with Bedrock. 
did you manage to solve it?

**Comment by zimmerling** [comment]
@davide-pet The problem is that there is no implementation for `_acall` in llamacpp.py. It only has the synchronous version [`_call`](https://github.com/langchain-ai/langchain/blob/d392e030bead62dd26d37b496221dbe478c3d2ad/libs/langchain/langchain/llms/llamacpp.py#L263C1-L303). The solution that worked for me is to switch to another llm. I use [C Transformers](https://python.langchain.com/docs/integrations/llms/ctransformers) because it has an implementation of [`_acall`](https://github.com/langchain-ai/langchain/blob/d392e030bead62dd26d37b496221dbe478c3d2ad/libs/langchain/langchain/llms/ctransformers.py#L109C4-L140C1)

**Comment by DmitryIo** [comment]
> @zimmerling same problem here but with Bedrock. did you manage to solve it?

I've solved this issue in this PR https://github.com/langchain-ai/langchain/pull/10908
It was closed, but there is a link to one, that has passed

**Comment by davide-pet** [comment]
@DmitryIo any hope this issue will be fixed in Bedrock too?
