### ISSUE TITLE
langchain.llms.Databricks does not save necessary params (e.g. endpoint_name, cluster_driver_port, etc.) to recover from its config

### ISSUE THREAD

**Issue by jinlinhe-db** [langchain-ai/langchain#9884]
### System Info

I used langchain=0.0.246 on Databricks, but this bug is due to the lack of implementation of `Databricks._identifying_params()`, so system info should not impact. 

### Who can help?

I see that @nfcampos contributed to most of the Databricks model serving wrapper, so tagging you here.
@hwchase17 @agola11 

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

```
llm = Databricks(host=databricks_host_name, endpoint_name=model_endpoint_name)
   
llm_chain = LLMChain(
    llm=llm,
    prompt=PromptTemplate.from_template(prompt_template),
    verbose=True

llm_chain.save("path/to/llm_chain.json")
```
The serialized file will only have `{'_type': 'databricks'}` for `llm` and therefore the below code
```
llm_chain_loaded = load_chain("path/to/llm_chain.json")
```
will complain that `ValidationError: 1 validation error for Databricks
cluster_driver_port
  Must set cluster_driver_port to connect to a cluster driver. (type=value_error)`. 

This is because `llm_chain.save()` look at the llm chain's `_identifying_params()` which is not defined on `langchain.llms.Databricks` 

### Expected behavior

`llm_chain_loaded = load_chain("path/to/llm_chain.json")` should recover the `langchain.llms.Databricks` instance correctly.

All fields on `langchain.llms.Databricks` that are necessary to re-initialize the instance from a config file should be added to `Databricks._identifying_params()`

**Comment by devstein** [comment]
@cjcjameson Sorry for the confusion! Dosu can't create PRs (yet). We've updated it so it should no longer say that. 

Is this issue still relevant?

**Comment by renata-gotler** [comment]
yes it is, I'm getting the same error.
