### ISSUE TITLE
I tried running a simple Langchain code from the docs. This is my error : Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..             I tried using different Openai API Keys...still not working. Does anyone know how to fix it?

### ISSUE THREAD

**Issue by Namitha-KS** [langchain-ai/langchain#9908]
### System Info

I tried running it in replit

### Information

- [x] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

import openai
import os
from langchain.llms import OpenAI
llm = OpenAI(temperature=0.3)
print(llm.predict("What is the capital of India?"))

### Expected behavior

I followed a tutorial and the expected output is a prediction of the given text

**Comment by lefta** [comment]
OpenAI API is not free. You need to add a payment method in your OpenAI account to use it.
