### ISSUE TITLE
'ValueError: Missing some input keys: {'query'}' but i added it?

### ISSUE THREAD

**Issue by VadeanFlaviuAlexandru** [langchain-ai/langchain#9918]
### System Info

long story short, i use streamlit to make a demo where i can upload a pdf, click a button and the content is extracted automatically based on the prompt template's questions.
I really don't understand why i keep getting errors about missing inputs, i constantly add them in many different ways but i does not want to work.
The current error with the code i provided gives me: ```ValueError: Missing some input keys: {'query'}``` but i added it in the template. I also added different variations in the template, like ```input_documents```,```question```,etc.. nothing seems to work.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

code:
```
prompt_template="""... {context} ... {query}"""
questions = """ ...big chunk of questions ..."""
prompt = PromptTemplate(template=prompt_template, input_variables=["context", "query"])

            rawText = get_pdf_text(pdf)
            textChunks = get_text_chunks(rawText)
            vectorstore = get_vectorstore(textChunks, option)
            docs = vectorstore.similarity_search(questions)
            llm = ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.1)
            chain_type_kwargs = {"prompt": prompt}
            chain = RetrievalQA.from_chain_type(llm=llm, chain_type="stuff", retriever=vectorstore.as_retriever(),
                                                chain_type_kwargs=chain_type_kwargs)
            st.write(chain.run(query=questions, context=docs))
```
the functions:
```
def get_pdf_text(pdf_docs):
    pdf_reader = PdfReader(pdf_docs)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text


def get_text_chunks(text):
    text_splitter = CharacterTextSplitter(
        separator="\n",
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.create_documents(text)
    return chunks


def get_vectorstore(text_chunks, freeEmbedding):
    embeddings = OpenAIEmbeddings()
    if freeEmbedding == "Gratis (dar incet)":
        embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl")
    vectorstoreDB = FAISS.from_documents(documents=text_chunks, embedding=embeddings)
    return vectorstoreDB
```

### Expected behavior

For me to get an output based on the prompt

**Comment by VadeanFlaviuAlexandru** [comment]
> _🤖_
> 
> Hello,
> 
> Based on the error message you're receiving, it seems like the LangChain framework is expecting a 'query' key in the input variables of your PromptTemplate, but it's not finding it.
> 
> From the code you've provided, it appears that you've included 'query' in your template string, but not in the input_variables of your PromptTemplate. Here's the relevant line of code:
> 
> ```python
> prompt = PromptTemplate(template=prompt_template, input_variables=["context", "query"])
> ```
> 
> In this line, you're telling LangChain that your prompt template will have two placeholders: 'context' and 'query'. If your template string doesn't include both of these placeholders, you'll get a ValueError.
> 
> If 'query' is supposed to be the same as 'question', you might need to change "question" to "query" in the input_variables and in the template string.
> 
> Here is the corrected code:
> 
> ```python
> prompt_template="""... {context} ... {query}"""
> questions = """ ...big chunk of questions ..."""
> prompt = PromptTemplate(template=prompt_template, input_variables=["context", "query"])
> ```
> 
> And replace all instances of 'question' with 'query' in the template string.
> 
> In the LangChain framework, the 'query' key is used to represent the query part of a story in the CPALChain class. It is used to transform the narrative input into an SQL expression that queries the outcome table. You can find more details about this in the LangChain source code, specifically in the [libs/experimental/langchain/experimental/cpal/base.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain/experimental/cpal/base.py) file.
> 
> I hope this helps! If you have any other questions or if something is not clear, please let me know.
> ## Sources
> 
>     * [ValueError: Missing some input keys: {'input'}](https://github.com/langchain-ai/langchain/issues/4673)
> 
>     * [Issue: Missing some input keys: {'question'} when using ConversationalRetrievalChain](https://github.com/langchain-ai/langchain/issues/7190)
> 
>     * [libs/langchain/langchain/chains/qa_with_sources/stuff_prompt.py](https://github.com/langchain-ai/langchain/blob/-/libs/langchain/langchain/chains/qa_with_sources/stuff_prompt.py)
> 
>     * [libs/experimental/langchain/experimental/cpal/base.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain/experimental/cpal/base.py)
> 
>     * [libs/experimental/langchain_experimental/cpal/base.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain_experimental/cpal/base.py)
> 
>     * [libs/experimental/langchain_experimental/cpal/templates/univariate/query.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain_experimental/cpal/templates/univariate/query.py)
> 
>     * [libs/experimental/langchain/experimental/cpal/templates/univariate/query.py](https://github.com/langchain-ai/langchain/blob/-/libs/experimental/langchain/experimental/cpal/templates/univariate/query.py)
> 
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

What?? i already included 'query' in input_variables,@dosu-bot :(

**Comment by VadeanFlaviuAlexandru** [comment]
Maybe im doing something wrong, but this doesn't help either

**Comment by VadeanFlaviuAlexandru** [comment]
got it working. posting the code for who ever is going to stumble upon this post:
```
got it working for who ever is going to stumble upon this post:
```
prompt_template="""...{summaries}...{question}..."""
questions="""...."""

def get_pdf_text(pdf_docs):
    pdf_reader = PdfReader(pdf_docs)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text


def get_text_chunks(text):
    text_splitter = CharacterTextSplitter(
        separator="\n",
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.split_text(text)
    return chunks


def get_vectorstore(text_chunks, freeEmbedding):
    metadata_list = [{'source': "local"}] * len(text_chunks)
    embeddings = OpenAIEmbeddings()
    if freeEmbedding == "Gratis (dar incet)":
        embeddings = HuggingFaceInstructEmbeddings(model_name="hkunlp/instructor-xl")
    vectorstoreDB = FAISS.from_texts(texts=text_chunks, embedding=embeddings, metadatas=metadata_list)
    return vectorstoreDB


load_dotenv()
st.set_page_config(page_title="ExtragereCicada - PDF", page_icon="📄")
st.header("Extragere Conținut - PDF")

pdf = st.file_uploader("Incarca PDF:", type="pdf")
option = st.selectbox("Modul de incorporare (cat de rapid se citeste PDF-u):",
                      ("Gratis (dar incet)", "Platit (dar rapid)"))

if pdf is not None:
    buttonPressed = st.button("Fa-mi un rezumat!")
    st.write("-------------------------------")
    if buttonPressed:
        with st.spinner("Se citeste... 📄🤔... o secunda, te rog..."):
            rawText = get_pdf_text(pdf)
            textChunks = get_text_chunks(rawText)
            print('---------TEXTCHUNKS', textChunks)
            vectorstore = get_vectorstore(textChunks, option)
            print('=========vectorSTORE', vectorstore)
            docs = vectorstore.similarity_search(questions)
            print('=========DOCS', docs)
            doc = Document(page_content=prompt_template,
                           metadata={"summaries": docs, "question": questions, "source": pdf.name})
            prompt = PromptTemplate.from_template("{source} {page_content} {summaries} {question}")
            format_document(doc, prompt)
            print('=========DOC', doc)
            llm = ChatOpenAI(model_name='gpt-3.5-turbo', temperature=0.1)
            chain = RetrievalQAWithSourcesChain.from_chain_type(llm=llm,
                                                                chain_type="stuff",
                                                                retriever=vectorstore.as_retriever(),
                                                                chain_type_kwargs={
                                                                    "prompt": PromptTemplate(
                                                                        template=prompt_template,
                                                                        input_variables=["summaries", "question"]
                                                                    )
                                                                })
            st.write(chain({"question": questions, "summaries": doc}, return_only_outputs=True)["answer"])
```
```

**Comment by deepak-habilelabs** [comment]
@VadeanFlaviuAlexandru even though using your solution, I still getting same error, Can u pls help me out? Thanks in advance
below is my code:
def generate_custom_prompt(query=None,name=None,not_uuid=None,chroma_db_path=None):  
    check = query.lower() 
    embedding = OpenAIEmbeddings()
    vectordb = Chroma(persist_directory=chroma_db_path, embedding_function=embedding)
    retriever = vectordb.as_retriever(search_kwargs={"k": 2})
    relevant_document = retriever.get_relevant_documents(query)
    print(relevant_document,"*****************************************")
    context_text="\n\n---\n\n".join([doc.page_content for doc in relevant_document])
    # print(context_text,"context_text")
    user_experience_inst = UserExperience.objects.get(not_uuid=not_uuid)
    greetings = ['hi', 'hello', 'hey', 'hui', 'hiiii', 'hii', 'hiii', 'heyyy']
    if check in greetings:
        custom_prompt_template = f"""
        Just simply reply with "Hello {name}! How can I assist you today?"
        """
    elif check not in greetings and user_experience_inst.custom_prompt:
        custom_prompt_template = f"""Answer the question based only on following context: ```{context_text} ```
        You are a chatbot designed to provide answers to User's Questions:```{check}```, delimited by triple backticks.
        Generate your answer to match the user's requirements: {user_experience_inst.custom_prompt}

        If you encounter a question for which you don't know the answer, please respond with 'I don't know' and refrain from making up an answer.
        - Before saying 'I don't know,' please re-verify your vector store to ensure the answer is not present in the database.

        Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, feel free to ask for clarification.

        User's Question: ```{check}```
        AI Answer:"""
    else:
        # Create the custom prompt template
        custom_prompt_template = f"""Generate your response exclusively from the provided context: {{context_text}}. You function as a chatbot specializing in delivering detailed answers to the User's Question: ```{{check}} ```, enclosed within triple backticks.
            Generate your answer in points in the following format:
            1. Point no 1
                1.1 Its subpoint in details
                1.2 More information if needed.
            2. Point no 2
                2.1 Its subpoint in details
                2.2 More information if needed.
            …
            N. Another main point.

            If you encounter a question for which you don't know the answer based on the predefined points, please respond with 'I don't know' and refrain from making up an answer.
            However, if the answer is not present in the predefined points, then Provide comprehensive information related to the user's query.
            Remember, your goal is to assist the user in the best way possible. If the question is unclear or ambiguous, you can ask for clarification.

            User's Question: ```{{check}} ```  
            AI Answer:"""


    # Create the PromptTemplate
    custom_prompt = ChatPromptTemplate.from_template(template=custom_prompt_template)
    formatted_prompt = custom_prompt.format(context_text=context_text, check=check)
    # QA_CHAIN_PROMPT = PromptTemplate(
    # input_variables=["context_text","check"],template=custom_prompt_template,)
    llm = ChatOpenAI(temperature=0.1)
    memory = ConversationBufferMemory(llm=llm,output_key='answer',memory_key='chat_history',return_messages=True)  
    # qa = ConversationalRetrievalChain.from_llm(llm=llm,memory=memory,chain_type="stuff",retriever=retriever,return_source_documents=True,get_chat_history=lambda h : h,verbose=True)
    qa = ConversationalRetrievalChain.from_llm(llm=llm,memory=memory,chain_type="stuff",retriever=retriever,return_source_documents=True,get_chat_history=lambda h : h,verbose=True, combine_docs_chain_kwargs={"prompt": PromptTemplate(template=custom_prompt_template,input_variables=["context_text","check"])})
    # prompt_qa={"qa": qa, "formatted_prompt": formatted_prompt}
    return qa
