### ISSUE TITLE
WebBaseLoader encoding issue

### ISSUE THREAD

**Issue by sim-so** [langchain-ai/langchain#9925]
### System Info

LangChain 0.0.275
Python 3.10.12
(Google Colaboratory)

### Who can help?

Hello, @eyurtsev!
We found an issue related to `WebBaseLoader`.

I guess the problem is related to `Response.apparent_encoding` leveraged by `WebBaseLoader. chardet.detect()`, which assigns the `apparent_encoding` to a Response object, cannot detect a proper encoding for the document.

Please find the details below.

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Import WebBaseLoader
2. Load the test url with WebBaseLoader
3. Check the content
```
from langchain.document_loaders import WebBaseLoader

url = 'https://huggingface.co/docs/transformers/v4.32.0/ko/tasks/sequence_classification'
loader = WebBaseLoader(url)
data = loader.load()
for k, v in data[0].metadata.items():
    print(f"{k} : {v}")
content = data[0].page_content
print("content : ")
content[5000:5300] # to truncate the front of the documents with many new lines.
```
then you can see the output as below:
```
source : https://huggingface.co/docs/transformers/v4.32.0/ko/tasks/sequence_classification
title : í…�ìŠ¤íŠ¸ ë¶„ë¥˜
description : Weâ€™re on a journey to advance and democratize artificial intelligence through open source and open science.
language : No language found.
content : 
‹¤.
ì�´ ê°€ì�´ë“œì—�ì„œ í•™ìŠµí•  ë‚´ìš©ì�€:
IMDb ë�°ì�´í„°ì…‹ì—�ì„œ DistilBERTë¥¼ íŒŒì�¸ íŠœë‹�í•˜ì—¬ ì˜�í™” ë¦¬ë·°ê°€ ê¸�ì •ì �ì�¸ì§€ ë¶€ì •ì �ì�¸ì§€ íŒ�ë‹¨í•©ë‹ˆë‹¤.
ì¶”ë¡ ì�„ ìœ„í•´ íŒŒì�¸ íŠœë‹� ëª¨ë�¸ì�„ ì‚¬ìš©í•©ë‹ˆë‹¤.
ì�´ íŠœí† ë¦¬ì–¼ì—�ì„œ ì„¤ëª…í•˜ëŠ” ì�‘ì—…ì�€ ë‹¤ì�Œ ëª¨ë�¸ ì•„í‚¤í…�ì²˜ì
```
To our knowledge, this is the only case that suffers from this issue.

### Expected behavior

We want to work like the below(another webpage):

```
source : https://www.tensorflow.org/versions?hl=ko
title : TensorFlow API 버전  |  TensorFlow v2.13.0
language : ko-x-mtfrom-en
content : 
TensorFlow API 버전  |  TensorFlow v2.13.0
    설치
    학습
                      소개          
                      TensorFlow를 처음 사용하시나요?
                      TensorFlow
                      핵심 오픈소스 ML 라이브러리
```
WebBaseLoader can detect encoding properly for almost all webpages that we know of.

**Comment by KodzghlyCZ** [comment]
I can confirm this issue is still happening on 5% of sites roughly. I have no skills to dig deeper into how the automatic encoding detection works, but I'd consider that to be bugged somehow, since all the affected pages had UTF-8 encoding set in the header, so there should be no issues with that. I've strictly set the encoding to UTF-8, however ugly that was and for my range of pages it works without any issues since. I'm running the latest versions of the time I'm writing this. The solution above is valid, except now you gotta copy the exact implementation of __scrape_ function, something like

`from langchain_community.document_loaders import WebBaseLoader
from typing import Union
from typing import Any
from typing import Optional

class CustomWebBaseLoader(WebBaseLoader):
    def _scrape(
        self,
        url: str,
        parser: Union[str, None] = None,
        bs_kwargs: Optional[dict] = None,
    ) -> Any:
        from bs4 import BeautifulSoup

        if parser is None:
            if url.endswith(".xml"):
                parser = "xml"
            else:
                parser = self.default_parser

        self._check_parser(parser)

        html_doc = self.session.get(url, **self.requests_kwargs)
        if self.raise_for_status:
            html_doc.raise_for_status()

        html_doc.encoding = 'utf-8'
        return BeautifulSoup(html_doc.text, parser, **(bs_kwargs or {}))`
