### ISSUE TITLE
ConversationalRetrievalChain [got multiple argument for question_generator]

### ISSUE THREAD

**Issue by abhi474731** [langchain-ai/langchain#9952]
### System Info

Getting error: got multiple values for keyword argument- question_generator .

return cls(\nTypeError: langchain.chains.conversational_retrieval.base.ConversationalRetrievalChain() got multiple values for keyword argument \'question_generator\'', 'SystemError'

`Qtemplate = (
"Combine the chat history and follow up question into "
"a standalone question. Chat History: {chat_history}"
"Follow up question: {question} withoud changing the real meaning of the question itself."
)
CONDENSE_QUESTION_PROMPT = PromptTemplate.from_template(Qtemplate)
question_generator_chain = LLMChain(llm=OpenAI(openai_api_key=openai.api_key), prompt=CONDENSE_QUESTION_PROMPT)
chain = ConversationalRetrievalChain.from_llm(
llm=llm,
retriever=self.vector_store.as_retriever(),
combine_docs_chain_kwargs=chain_type_kwargs,
verbose=True,
return_source_documents=True,
get_chat_history=lambda h: h,
memory=window_memory,
question_generator=question_generator_chain

)`

### Who can help?

@hwchase17 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Steps to reproduct the behaviour:
1. Generate standalone question, which does not change the meaning of question, if it is changing meaning of question, keep question as it is.
2. Generate output using memory and get most accurate answer.

### Expected behavior

Expecting the right code for implementing same functionality.

**Comment by abhi474731** [comment]
help me solve the issue !

**Comment by abhi474731** [comment]
Found the workaround.
But this was not the solution given by your bot.

**Comment by SudhanshuSaksham** [comment]
@abhi474731 I would need the snippet too as the workaround still is throwing the same message.
