### ISSUE TITLE
Multi Tenant Support for Weaviate

### ISSUE THREAD

**Issue by dudanogueira** [langchain-ai/langchain#9956]
### Feature request

Weaviate introduced multi-tenancy support in version 1.20
https://weaviate.io/blog/multi-tenancy-vector-search

### Motivation

This can help users using Langchain + Weaviate at scale, ingesting documents and attaching tenants to it.

### Your contribution

I have implemented, but would need some help to check if everything is ok and in accordance with LangChain.

Also, I would like help on the as_retriver, as I was not able to implement multitenant on it, Yet.

the code is living here: https://github.com/dudanogueira/langchain/tree/weaviate-multitenant

**Comment by mario-codes-apps** [comment]
has there been any updates on this? it would be great to have this merged to main

**Comment by dudanogueira** [comment]
Hi @mario-codes-apps I need only to understand better the as_retriever part. Any help here would be appreciated.

**Comment by dsx1986** [comment]
https://github.com/langchain-ai/langchain/pull/11842

**Comment by jeremyb-data** [comment]
Have a PR for a small bugfix. 
- from_texts needs the "tenant" keyword from add_documents, otherwise it'll throw an error without adding. Works great once it's passed as far as my own testing has gone. 

https://github.com/langchain-ai/langchain/pull/13827
