### ISSUE TITLE
azure.search.documents.indexes.models._edm no attribute "Single" under Langchain.AzureSearch()

### ISSUE THREAD

**Issue by Mart1nZg** [langchain-ai/langchain#9973]
### System Info

Platform: MacOS 13.5
Python Version: 3.10.11
Langchain: 0.0.257
Azure Search: 1.0.0b2
Azure Search Documents: 11.4.0b6
Openai: 0.27.8

Issue: AttributeError: module 'azure.search.documents.indexes.models._edm' has no attribute 'Single'

Code: `az_search = AzureSearch(azure_search_endpoint=os.getenv('AZURE_COGNITIVE_SEARCH_SERVICE_NAME'),
                                                          azure_search_key=os.getenv('AZURE_COGNITIVE_SEARCH_API_KEY'),
                                                          index_name=os.getenv('AZURE_COGNITIVE_SEARCH_INDEX_NAME'),
                                                          embedding_function=embeddings.embed_query)`

I read from another post here: [https://github.com/langchain-ai/langchain/issues/8917](url) that this is caused by a version miss match. So I downgraded my Azure search-documents package version to 11.4.0b6. But the same error occurred. 

I've also tried using langchin==0.0.245 or langchain==0.0.247 but didn't solve the issue.

### Information

- [X] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction
```
os.environ["AZURE_COGNITIVE_SEARCH_INDEX_NAME"]="vectordb001index"
embeddings = OpenAIEmbeddings(deployment_id="vectorDBembedding", chunk_size=1)
az_search = AzureSearch(azure_search_endpoint=os.getenv('AZURE_COGNITIVE_SEARCH_SERVICE_NAME'),
                                             azure_search_key=os.getenv('AZURE_COGNITIVE_SEARCH_API_KEY'),
                                             index_name=os.getenv('AZURE_COGNITIVE_SEARCH_INDEX_NAME'),
                                             embedding_function=embeddings.embed_query)
```

**Error Output**
```
File [~/Desktop/.../azuresearch.py:221](https://file+.vscode-resource.vscode-cdn.net/.../azuresearch.py:221), in AzureSearch.__init__(self, azure_search_endpoint, azure_search_key, index_name, embedding_function, search_type, semantic_configuration_name, semantic_query_language, fields, vector_search, semantic_settings, scoring_profiles, default_scoring_profile, **kwargs)
    206 # Initialize base class
    207 self.embedding_function = embedding_function
    208 default_fields = [
    209     SimpleField(
    210         name=FIELDS_ID,
    211         type=SearchFieldDataType.String,
    212         key=True,
    213         filterable=True,
    214     ),
    215     SearchableField(
    216         name=FIELDS_CONTENT,
    217         type=SearchFieldDataType.String,
    218     ),
...
    230 ]
    231 user_agent = "langchain"
    232 if "user_agent" in kwargs and kwargs["user_agent"]:

AttributeError: module 'azure.search.documents.indexes.models._edm' has no attribute 'Single'
```

### Expected behavior

Program running with no error interruption

**Comment by VijayTanneeru** [comment]
I got the same error , here is the solution

Add below line code to use "SearchFieldDataType.Single" type
SearchField(name="embedding", type=SearchFieldDataType.Collection(SearchFieldDataType.Single), searchable=True, vector_search_dimensions=1536, vector_search_configuration ="vector-config")

here is how you create vector_search_configuration :

def get_vector_config(m,efConstruction,efSearch):
    # Set up Vector Search Configuration
    vector_search = VectorSearch(
        algorithm_configurations=[
            HnswVectorSearchAlgorithmConfiguration(
                name="vector-config",
                kind="hnsw",
                parameters={
                    "m": m,
                    "efConstruction": efConstruction,
                    "efSearch": efSearch,
                    "metric": "cosine"
                }
            )
        ]
    )
    return vector_search

**Comment by Gagampy** [comment]
Installing
`azure-search-documents = "11.4.0b8"`
solved the issue for me.

**Comment by imkushwaha** [comment]
installing
azure-search-documents = "11.4.0b8"
worked for me as well

Thanks
