### ISSUE TITLE
GCSFileLoader need to read blob's metadata and populate it to documents metadata

### ISSUE THREAD

**Issue by bharatl** [langchain-ai/langchain#9975]
### Feature request

GCS blobs can have custom metadata defined either in google console or programatic way as shown below

```
from google.cloud import storage
storage_client = storage.Client()
bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(destination_blob_name)
metadata = {'from_source': 'https://localhost', 'genre': 'sci-fi'}
blob.metadata = metadata
blob.upload_from_filename("/home/jupyter/svc-mlp-staging.json", if_generation_match=0)

```
GCSFileLoader can get  blob's metadata if present and populate the same to document's metadata before returning docs. 

### Motivation

1. This feature can help load the documents with the required custom metadata. 
2. Splits (based on splitter) and vector embeddings of splits will be identified by custom metadata in vector store

### Your contribution

Interested in taking this up

**Comment by bharatl** [comment]
@dotsu-beta any comments on this as enhancement

**Comment by alexandra-varyuta** [comment]
we also required the same feature
