### ISSUE TITLE
React Agents sometimes fail if they only have one tool

### ISSUE THREAD

**Issue by bborn** [langchain-ai/langchain#998]
I've seen this a few times: if an agent only has one tool, it will sometimes do this: 

```Action: [Tool Name]
Action Input: Some input
Observation: [Tool Name] is not a valid tool
```

I think it's getting confused because the list of available tools only has one item, so it thinks the entire tool is called `[Tool Name]` instead of `Tool Name`

(And sorry for saying "thinks" - I know it doesn't think but it just sort of makes sense to describe it that way)

**Comment by chris-aeviator** [comment]
this reliably happens to me if only one tool is present

**Comment by sonnguyen-TS** [comment]
This also happens to me when I use only one tool (PythonREPLTool). The chain doesn't recognise it and assign to "Invalid tool". When I add an extra tool like Wikipedia, the the problem's solved.
