### ISSUE TITLE
How to pass a custom prompt in graphQA or GraphCypherQA chain

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain#9993]
### Feature request

```
from langchain.chat_models import ChatOpenAI
from langchain.chains import GraphCypherQAChain
from langchain.graphs import Neo4jGraph
graph = Neo4jGraph(
    url="bolt://localhost:7687", username="neo4j", password="pleaseletmein"
)
chain = GraphCypherQAChain.from_llm(ChatOpenAI(temperature=0), graph=graph, verbose=True)
print(chain.run("Question to the graph"))
```
In the above Code, How can I pass my custom prompt as promptTemplate? Please give me an example

### Motivation

Custom prompt support in Knowledge Graph QA

### Your contribution

Custom prompt support in Knowledge Graph QA

**Comment by pradeepdev-1995** [comment]
But how can I set the context in the given prompt?
```
custom_prompt_template = """Your custom template here with placeholders for input variables.
For example:
{context}
Question: {question}
Relevant text, if any:"""
```
Because the context will be either the knowledge graph or the answer object returned from the knowledge graph. So how can I pass the context in the above template?

NB: It is simple in the case of RAG pipelines. But here the context will be a knowledge graph instead of the text object like in RAG. So how to handle here?

**Comment by thib-verbanck** [comment]
Is it possible to add the generated query as context to a custom QA_prompt_template?

`my_graph_retriever_qa_prompt = PromptTemplate(input_variables = ["context", "question"], template = graph_retriever_qa_template, name = "qa_prompt")`

Now only the context (information retrieved) and question (original question) seem to be available. The QA_Chain however sometimes required the actual query to generate a relevant response.
