### ISSUE TITLE
Solve the problem of working with incomplete document chunks and multiple documents

### ISSUE THREAD

**Issue by kripper** [langchain-ai/langchain#9996]
### Feature request

An agent for searching iteratively multiple documents without the problem of processing incomplete document chunks.
An option to include the metadata (source references) in the prompt.

### Motivation

Normally documents are split into chunks before being added to Chroma
When the data is queried, Chroma returns these chunks of incomplete documents and feed them to the prompt.
Thus, the LLM sometimes is not provided with the complete information and will fail to answer.
This is a big problem, especially when the split occurs in the middle of a list (eg: a text listing the 10 commandments of god).
The LLM won't have a chance to know they are 10.

Besides, LangChain "stuff" retriever is just mixing all these chunks together, without even separating them nor adding the documents metadata of each chunk. Mixing different sentences could confuse the LLM.
If this can be solved using document_prompt templates, this should be added to the documentation.
I would also expect to include document souces into the prompt, so the LLM and provide the used sources (not all sources retrieved by the Chroma query).

I blieve the queries should be processed by an agent with the ability to detect when there may be missing previous and/or following chunks in order to fetch them in a subsequent iteration if required.

### Your contribution

I can help coding and testing, but I need feedback for the design and to know which other existing componentes could/should be used.

**Comment by kripper** [comment]
> Example Format:

No. "Example Format" should be "### Context" or something similar to tell we are providing documents.

> <Begin Document>
> ...
> <End Document>

Do we know what tag or format is appropiate to feed multiple documents to llama2 et. al. models?

> Metadata: {metadata}

The MetaData should be placed inside the `<Begin Document>` / `<End Document>` tags.

Please provide an example to accomplish this with existing code. I found some references about a document_prompt option.

**Comment by kripper** [comment]
This issue is still present.
The way the chunks of matched document parts are fed to the LLM is too poor and introduces unnecessary confusion (you cannot just concatenate different text fragments).
Use some separator, to separate different text matches. Give the LLM a chance to know that the text fragments were extracted from different sources and may be incomplete.

**Comment by seanmavley** [comment]
@kripper any idea what a potential workaround may be? We seem to be experiencing similar confused answers and queries.

**Comment by kripper** [comment]
Closing, since there are multiple solutions for this problem.
